### ISSUE TITLE
Feature Request: Reflection

### ISSUE THREAD

**Issue by CoryGH** [denoland/deno#10003]
A long-standing missing feature from node.js which I'd love to see in a server-side and desktop-application JavaScript and TypeScript would be a .NET style System.Reflection which lets you see into and modify the managed code running the application in real time.  I've run across a few use cases for this over the years and the workarounds tend to entail hacky and bloated solutions to work around managing code injection.

**Comment by kitsonk** [comment]
There is reflection type APIs in JavaScript (see: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect).  Ultimately any changes or improvements to that would come via the ECMAScript standard. [ESDiscuss](https://esdiscuss.org/) would be the right place to talk about changes to the language.  Deno is a JavaScript/TypeScript runtime and does not address language features.

Respectfully closing.

**Comment by CoryGH** [comment]
This would be pretty firmly based in the runtime wiring as opposed to a language spec, as all the wiring would be at the runtime layer and specific to the runtime running the code.

**Comment by bnoordhuis** [comment]
Maybe https://chromedevtools.github.io/devtools-protocol/1-2/ is what you're looking for? Deno speaks the protocol but only the `Debugger` and `Runtime` domains are applicable, the others are specific to browsers.

It's kind of like a programmable real-time debugger and code editor. There's little you cannot do with it.
