### ISSUE TITLE
Add project scope

### ISSUE THREAD

**Issue by fulldecent** [denoland/deno#10007]
There is a motivating sentence at top of the README.

> Deno is a simple, modern and secure runtime for JavaScript and TypeScript that uses V8 and is built in Rust.

This is nice. But I was hoping the project maintainers can better differentiate Deno from another popular JavaScript runtime and what work this project is making to achieve that. This will better help motivate contributors to come and make Deno better.

**Comment by lucacasonato** [comment]
Our general goals and project philosophy is lined out in the intro page of the manual: https://deno.land/manual.

We publish quarterly roadmaps for what the core team will work on (for example https://github.com/denoland/deno/issues/8824).

What specifically would you want in addition to this information?

**Comment by fulldecent** [comment]
Thank you, that's what I was looking for. Here's a PR that adds up to the readme https://github.com/denoland/deno/pull/10011
