### ISSUE TITLE
OpenGL error when bundeling three.js with Deno

### ISSUE THREAD

**Issue by wrnrlr** [denoland/deno#10022]
Ok, this one is weird.

I have a module that draws a cylinder and box geometry.
When I directly include this file with a script tag it draws both cylinder and box.
But, when I first bundle the file it only show the box, and logs this error:

    [.WebGL-0x7f9fab819e00]GL ERROR :GL_INVALID_OPERATION : glDrawElements: attempt to access out of range vertices in attribute 0

![screenshot](https://user-images.githubusercontent.com/24570434/113587549-3c0c4b00-962f-11eb-9f01-75a86d8e5df5.png)

The code is very straightforward, simple html and js

index.html 

    <style>html,body { height: 100%;}</style>
    <script type="module" src="main.js"></script>

broken.html

    <style>html,body { height: 100%;}</style>
    <script type="module" src="bundle.js"></script>

main.js

```
import {Scene,PerspectiveCamera,WebGLRenderer,Mesh,MeshBasicMaterial,BoxGeometry,CylinderGeometry}
from 'https://unpkg.com/three/build/three.module.js'
const container = document.body
const width = 300, height = 300;
const canvas = document.createElement('canvas')
const gl = canvas.getContext("webgl") || canvas.getContext("experimental-webgl")
if (!(gl && gl instanceof WebGLRenderingContext)) throw new Error('OpenGL not supported')
const scene = new Scene()
const camera = new PerspectiveCamera(5, width / height)
container.appendChild(canvas)
const renderer = new WebGLRenderer({ canvas, antialias: true })
renderer.setSize(width, height)
const greenStuff = new MeshBasicMaterial( {color: 0x00ff00, wireframe: true})
scene.add(new Mesh(new BoxGeometry(), greenStuff))
scene.add(new Mesh(new CylinderGeometry(), greenStuff))
camera.position.set(5, 20, 22)
camera.lookAt(0, 0, 0)
scene.add(camera)
renderer.render(scene, camera)
```

This command to bundle the code into bundle.js (doesn't work with either --watch --unstable or without):

    deno bundle ./main.js ./bundle.js

server.js:

```
import {Application, send} from "https://deno.land/x/oak@v6.5.0/mod.ts";
const app = new Application()
app.use(async (context) => {
  await send(context, context.request.url.pathname, {
    root: `${Deno.cwd()}`,
    extensions: ['html'],
    index: "index.html",
  })
})
await app.listen({port: 8000})
```

Run it with: `deno run --allow-net --allow-read server.js`

Handy zip with everything:

[three-problem.zip](https://github.com/denoland/deno/files/6258778/three-problem.zip)

Tested it with deno version:

```
deno 1.7.0 (release, x86_64-apple-darwin)
v8 8.9.255.3
typescript 4.1.3
```

**Comment by wrnrlr** [comment]
Raised the same problem with [three.js](https://github.com/mrdoob/three.js/issues/21576)

**Comment by lucacasonato** [comment]
This is purely a bug in the Deno bundler. Please update to Deno 1.8.3 and try again

**Comment by wrnrlr** [comment]
OK, I tried that and everything working as advertised now, thanks @lucacasonato for your help!
