### ISSUE TITLE
lsp: export type with X-TypeScript-Types fails

### ISSUE THREAD

**Issue by ije** [denoland/deno#10031]
```ts
export { minify } from 'https://esm.sh/terser@5.5.1'
export type { ECMA } from 'https://esm.sh/terser@5.5.1'
```

<img width="1007" alt="Screen Shot 2021-02-21 at 04 06 36" src="https://user-images.githubusercontent.com/2883484/108607270-4dd8bc80-73fa-11eb-9c75-02d7dceea3b2.png">

after using the **quick fix**:

<img width="975" alt="Screen Shot 2021-02-21 at 04 07 04" src="https://user-images.githubusercontent.com/2883484/108607268-49140880-73fa-11eb-9c8f-f6772732108e.png">

**deno 1.7.5 / vscdoe-deno 3.0.1**

**Comment by kitsonk** [comment]
It seems that for some reason with `X-TypeScript-Types` we aren't always resolving to the `.d.ts` file in the lsp, though we seem to be doing just fine with `deno run`.
