### ISSUE TITLE
lsp: errors with non-supported extensions being imported

### ISSUE THREAD

**Issue by mizchi** [denoland/deno#10032]
**Describe the bug**

Error with `.svelte` importing ts code

```
[Error - 4:07:49] Request textDocument/hover failed.
  Message: Internal error
  Code: -32603 
Unable to get quick info: Error: The current snapshot version is missing.
  Args: "GetChangeRangeArgs { specifier: "file:///Users/mizchi/gh/github.com/mizchi/swdev/example/App.svelte", old_length: 156, old_version: "1616871816788", version: "1616871974028" }"
    at processResponse (deno:core/core.js:212:11)
    at Object.jsonOpSync (deno:core/core.js:236:12)
    at ScriptSnapshot.getChangeRange (deno:cli/tsc/99_main_compiler.js:224:19)
    at acquireOrUpdateDocument (deno:cli/tsc/00_typescript.js:123008:133)
    at Object.updateDocumentWithKey (deno:cli/tsc/00_typescript.js:122974:20)
    at getOrCreateSourceFileByPath (deno:cli/tsc/00_typescript.js:149726:49)
    at Object.getOrCreateSourceFile [as getSourceFile] (deno:cli/tsc/00_typescript.js:149683:24)
    at findSourceFileWorker (deno:cli/tsc/00_typescript.js:108104:29)
    at findSourceFile (deno:cli/tsc/00_typescript.js:108014:26)
    at processImportedModules (deno:cli/tsc/00_typescript.js:108386:25)
```

Sample Code

```ts
// index.ts
import App from "./App.svelte";

export default () => {
  const target = document.querySelector(".svelte-root")!;
  new App({ target });
};
```

App.svelte

```svelte
<script lang="ts">
  import { onMount } from "svelte";
  let x: number = 1;
  onMount(() => {
    x += 2;
  });
</script>

<div>
  Hello Svelte345! {x}
</div>
```

These are client code to compile by rollup, not for deno.

**To Reproduce**

1. enable deno exetension by `.vscode/settings.json` 's `dene.enable: true`
2. Put `App.svelte`
3. Put `index.ts` including `import App from "./App.svelte"`;
4. Open `index.ts` on vscode
5. Emit errors by each mouse move.

Error popup by each edit is annoying...

**Expected behavior**

No error.

Ideally vscode-deno works with https://github.com/sveltejs/language-tools/tree/master/packages/language-server

**Screenshots**

![image](https://user-images.githubusercontent.com/73962/112743936-ad685000-8fd6-11eb-8799-e613bf87412a.png)

**Versions**

vscode: 1.54.3
deno: 1.8.1
extension: 3.2.0

**Comment by kitsonk** [comment]
@mizchi I tried to reproduce with v3.2.0 of the extension and Deno 1.8.3 and couldn't.  I am not getting any errors, (though I am not getting hover information as expected).  Could you re-check with Deno 1.8.3?  There wasn't anything specific in there that I can think of, but there were some issues with some of the internals we addressed.

When you were encountering these errors, where you moving the mouse in the `index.ts` file or the `App.svelte` file?

**Comment by kitsonk** [comment]
Unable to reproduce, not further information provided.
