### ISSUE TITLE
Better error message for non-supported thin ops

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#10046]
As mentioned here: https://github.com/denoland/deno/issues/10041#issuecomment-814254711 there are some ops not supported in thin compiled binaries.

We should consider better error messages, like injecting a stub op, for thin binaries that explain they aren't supported.

It would be even better to detect these at compile time and warn, but that is a bit more complex.

We should also document these limitations in the docs if we don't already.

**Comment by crowlKats** [comment]
There are no different compile sizes/modes, so closing.
