### ISSUE TITLE
fetch() on data url

### ISSUE THREAD

**Issue by KSXGitHub** [denoland/deno#10048]
I tried this on Deno 1.8.0 but it tells me that "scheme 'data' is not supported":

```javascript
await WebAssembly.instantiateStreaming(fetch(`data:application/wasm;base64,${WASM_BASE64}`), importObject)
```

**Comment by lucacasonato** [comment]
`WebAssembly.instantiateStreaming` does not take a string, it takes a `Promise<Response>` or `Response`. `import` has support for `data` URLs. Fetch does not.

**Comment by caspervonb** [comment]
Keep in mind that `instantiateStreaming` is still broken and currently takes a TypedArray but yes it should take a Response or Promise that resolves with a Response (https://github.com/denoland/deno/issues/7259) 🙃

Ben has implemented the plumbing I need in rusty_v8 that I need to fix this, I just haven't gotten around to it yet as it's not that critical.

If you already have the binary blob like you do here then instantiateStreaming will not be any faster than instantiate.

**Comment by KSXGitHub** [comment]
> `WebAssembly.instantiateStreaming` does not take a string, it takes a `Promise<Response>` or `Response`.

My bad. I forgot adding `fetch` to the example code, I added it just now.

**Comment by KSXGitHub** [comment]
> If you already have the binary blob like you do here then instantiateStreaming will not be any faster than instantiate.

The browser has no built-in function that decode base64 (other than `fetch()`) if I'm not mistaken. This means that I have to import external JavaScript code, making my bundle bigger.

**Comment by caspervonb** [comment]
See atob

https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/atob

**Comment by KSXGitHub** [comment]
@caspervonb I have tried your suggestion, and it crashes (the integration tests fail).

My guess is that `atob` convert any base64 to a **UTF-8** string, destroying the data.

**Comment by caspervonb** [comment]
> My guess is that atob convert any base64 to a UTF-8 string, destroying the data.

MDN specifies that the return value is a binary string

> https://developer.mozilla.org/en-US/docs/Web/API/DOMString/Binary

So not sure what's going on there.

**Comment by KSXGitHub** [comment]
> So not sure what's going on there.

My guess is that it was Deno's implementation to blame. I am too lazy to verify this.

**Comment by KSXGitHub** [comment]
> > So not sure what's going on there.
> 
> My guess is that it was Deno's implementation to blame. I am too lazy to verify this.

Actually, what does the spec says about `TextEncoder.prototype.encoding`?

**Comment by littledivy** [comment]
Have you tried this?
```typescript
Uint8Array.from(atob(sourceString), c => c.charCodeAt(0))
```

**Comment by KSXGitHub** [comment]
@littledivy It works. `c.codePointAt(0)` also works. What is preferable?

**Comment by lucacasonato** [comment]
data url fetch is now implemented. `WebAssembly.instantiateStreaming` is now disabled again. Closing because unactionable at this point.
