### ISSUE TITLE
Instead of DENO_BUILD_MODE=release, ./tools/build.py --release

### ISSUE THREAD

**Issue by ry** [denoland/deno#1004]
Currently ./tools/build.py uses an env var called DENO_BUILD_MODE to determine if it builds debug (default) or release builds. I'd like to have a command line argument instead for this. 

Please update the readme, travis.yml and appveyor.yml ... there may be random places where DENO_BUILD_MODE is used, so be sure to grep the source tree.

**Comment by romandev** [comment]
I'll take this issue.

**Comment by romandev** [comment]
I was on the same page. BTW, Do we have to change `setup.py` as well? It is always generates for both of debug and release.

**Comment by ry** [comment]
@romandev setup.py should still generate both (it just generates the build files)

**Comment by cedric05** [comment]
can i take up?

**Comment by ry** [comment]
@cedric05 No, it is almost complete.

**Comment by hayd** [comment]
@ry this can be closed.
