### ISSUE TITLE
`-r`, `--require` equivelant for Deno

### ISSUE THREAD

**Issue by ihack2712** [denoland/deno#10060]
Node has a `--require` option to (according to node) preload CommonJS modules before running the given script. Is there or will there ever be a deno equivelant to preload scripts/modules?

**Comment by nayeemrmn** [comment]
Static ES6 imports are already "preloaded".

https://nodejs.org/api/cli.html#cli_r_require_module
> Only CommonJS modules are supported. Attempting to preload a ES6 Module using --require will fail with an error.

So no.

**Comment by ihack2712** [comment]
I meant more like having the ability to run a script before the main script is runned, for instance:

```sh
deno run --requireEquvielant run-me-first.ts run-me-after.ts
```

**Comment by nayeemrmn** [comment]
Is `run-me-first.ts` a module not transitively imported by `run-me-after.ts`, which you want to run before for its top-level code? That's not the intended usage for `--require`, this would just be a way of running multiple main modules. Keep in mind again that Node's `--require` is disabled for ES modules.

**Comment by nayeemrmn** [comment]
It makes it not a nice API which complicates runtime usage a lot, since it would just be a way of running multiple main modules. I would make a separate module which does:
```ts
import "./run-me-first.ts";
import "./run-me-second.ts";
```
or if that doesn't work (because of an `import.meta.main` gate) just compromise with adding the hooks into your project.

**Comment by ihack2712** [comment]
Alright, sounds pretty straight forward I guess. Thanks for quick replies:)
