### ISSUE TITLE
[feat-tests] Deno.test priority ordering

### ISSUE THREAD

**Issue by Skillz4Killz** [denoland/deno#10077]
Hello 👋 

I am in need of a better method to order unit tests. The current implementation is not good for more complex unit tests that depend on previous tests to occur first or even a certain test to occur last. Having to import 100s of different files just to make sure that those tests run before the final test is really unpleasant. Similarly, having to import files for which you don't even need/use in that file is also bad.

Suggestion: A new property of type number, that could decide the order. If the number is equal for multiple tests, the order of that group of tests do not matter. For example if the tests were ordered as `1, 2, 3, 3, 4, 3, 3, 99` The tests would be processed in the following order: `1, 2, 3, 3, 3, 3, 4, 99`
```ts
Deno.test({
  name: "[xxx] some name here",
  order: 1,
  async fn() {
    await xxx();
    // ...
  },
  {
  sanitizeOps: false,
  sanitizeResources: false,
  },
});

Deno.test({
  name: "[xxx] Final test here.",
  order: 999,
  async fn() {
    await xxx();
    // ...
  },
  {
  sanitizeOps: false,
  sanitizeResources: false,
  },
});
```

Note: I even tried messing with the file names to make them alphabetical to possibly have them in a certain order but even that did not work.

![image](https://user-images.githubusercontent.com/23035000/114118529-f3ff5980-98b6-11eb-98a2-769ba04c1bf7.png)

`phase99.test.ts` occurred before `phase1.test.ts`

Thank You

**Comment by caspervonb** [comment]
Order of _good_ tests should never matter.

Tests will be run in seperate isolates from v1.9.
An order field would only be applicable in the scope of a single test module, and you can already order that by registering in order.

**Comment by Skillz4Killz** [comment]
@caspervonb can you suggest another method to achieve this or is it impossible in deno and will never be possible?

**Comment by caspervonb** [comment]
Already discussed this in discord but in case anyone hits this issue from a search query.

One can either specify the tests in order to the `deno test` command or have a manifest file (say called test.ts) that imports all the other tests in order (this however will count as a single test unit and won't be able to run in parallel).

**Comment by lucacasonato** [comment]
Ref #10771

**Comment by bartlomieju** [comment]
As stated before one shouldn't depend on specific order of test cases; that said it is now possible to execute tests in concrete order by using the new testing API with imperative approach. In light of this I'm going to close this issue.
