### ISSUE TITLE
[bug] fetch() method should always be .toUpperCase

### ISSUE THREAD

**Issue by Skillz4Killz** [denoland/deno#10088]
Hello 👋 

The method on `fetch()` requests should always be capitalized with .toUpperCase() in my opinion. It leads to issues when someone forgets and normally from using other projects it has always been the norm to be uppercased internally. Especially, when debugging this issue it took us hours trying different things to see what was wrong until we realized we should try making the `get` into `GET` just to see what that would do and it fixed all our issues. 

node-fetch:
https://github.com/node-fetch/node-fetch/blob/6ee9d3186f8b4bdc4288ccf92f0a776aa17644ae/src/request.js#L51

Thank You 😄

**Comment by lucacasonato** [comment]
This is now spec compliant
