### ISSUE TITLE
lsp: error could not find source file after closing inactive editor

### ISSUE THREAD

**Issue by jeanp413** [denoland/deno#10089]
I found that after closing an inactive editor hovering over a function results in a `could not find source file` error

![deno_lsp_could_not_find_source](https://user-images.githubusercontent.com/25115070/114198900-7456a680-9919-11eb-9a25-d60bf4a452d8.gif)

**Comment by kitsonk** [comment]
We've done a fair amount of refactoring in this space, and I can't reproduce any longer in 1.10.3.

**Comment by jeanp413** [comment]
@kitsonk I still can reproduce easily with the same steps using version 1.10.3.
```
Starting Deno language server...
  version: 1.10.3 (release, x86_64-unknown-linux-gnu)
Connected to "Code - OSS Dev" 1.57.0
language server initialized
Server ready.
Unable to get quick info: Error: Could not find source file: 'asset:///lib.es5.d.ts'.
    at getValidSourceFile (deno:cli/tsc/00_typescript.js:149564:29)
    at Object.getQuickInfoAtPosition (deno:cli/tsc/00_typescript.js:149812:30)
    at serverRequest (deno:cli/tsc/99_main_compiler.js:715:27)
    at [native_code]:1:12
```

**Comment by nayeemrmn** [comment]
Looks fixed
