### ISSUE TITLE
proposal: Better logging on Deno.test

### ISSUE THREAD

**Issue by Soremwar** [denoland/deno#10099]
Currently running `console.log` inside tests has a little inconvenience
```ts
Deno.test("Test logging", () => {
  console.log("Inside the test 1");
  console.log("Inside the test 2");
});
```
```log
running 1 tests
test Test logging ... Inside the test 1
Inside the test 2
ok 
```

I propose that the test line is readded after the test has finished if anything was logged to console in the execution of the test. That way we would get the following output
```log
running 1 tests
test Test logging ...
Inside the test 1
Inside the test 2
test Test logging ... ok 
```

**Comment by lucacasonato** [comment]
So the first `console.log` inside a test would add a newline prefix? Not too sure about this. I would rather the test runner intercept `console.*` fully then and hide the output by default, unless the test fails, just like `cargo` does in rust.

**Comment by Soremwar** [comment]
That works as well. The output will be shown in the stack trace of the failed test then?

**Comment by caspervonb** [comment]
> So the first console.log inside a test would add a newline prefix? Not too sure about this. I would rather the test runner intercept console.* fully then and hide the output by default, unless the test fails, just like cargo does in rust.

Yeah been saying this in chat, except I want us to capture stdout (and probably stderr) to a memory buffer for the test isolate rather than changing the console object.

**Comment by getspooky** [comment]
I think we should just format the output of the console for example 
```ts
running 1 tests
test Test logging ...
Inside the test 1
Inside the test 2
test Test logging ... ok 
```
instead of 
```ts
running 1 tests
test Test logging ... Inside the test 1
Inside the test 2
ok 
```
and it would be a good idea to add `--silent=false` so deno will  suppresse the console log message.

**Comment by getspooky** [comment]
@Soremwar you use `--quiet` flag to ignore log

**Comment by caspervonb** [comment]
Tag this for 2.0 please.

**Comment by bartlomieju** [comment]
Done in https://github.com/denoland/deno/pull/14271, https://github.com/denoland/deno/pull/14395, and https://github.com/denoland/deno/pull/14410
