### ISSUE TITLE
Stabilise Deno.fstat

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#10106]
*EDIT*: the original functionality is already supported via `Deno.fstat` but it is unstable, but it is just as stable as the other stat APIs and should be stabilised in my opinion.

---

Currently, if I have a `Deno.File`, there is no way to figure out where that file came from or to be able to get the `Deno.stat` or Deno.lstat` for that file.  While the `Deno.File` contains the `rid`, there is no way to get that back to a path or a file URL to be able to do other things with it.

The specific use case is in oak, where a `response.body` can be set to a `Deno.Reader`, which means a user can simply assign a `Deno.File` to the `reponse.body` to have that be sent.  But, I want to be able to transparently try to do a `Deno.stat` on the file to be able to generate an ETag for the file.

I can see two solutions:

- `Deno.stat` (and associated APIs) can takes an rid as well as a `string | URL`.
- `Deno.File` contains a canonicalised string or URL as a property.

**Comment by caspervonb** [comment]
Huh, thought I implemented fstat but guess I faked it in WASI and moved on.
Proper solution would be to implement fstat, can't recall if there was a reason I did not implement it because it is a really simple op.

Will look at it today.

**Comment by caspervonb** [comment]
So fstat is implemented, guess we can repurpose this to be about adding a stat method to the File class?

**Comment by kitsonk** [comment]
Ah, `Deno.fstat` is unstable. Seems silly that it is still unstsble. Adding the binding to the file object makes sense too, but let's stabilise fstat.
