### ISSUE TITLE
RequestEvent::respondWith() should return a promise

### ISSUE THREAD

**Issue by nayeemrmn** [denoland/deno#10101]
https://github.com/denoland/deno/blob/e7b7129b7a92b7500ded88f8f5baa25a7f59e56e/cli/dts/lib.deno.unstable.d.ts#L1200-L1203

To align with https://developer.mozilla.org/en-US/docs/Web/API/FetchEvent/respondWith#return_value the current definition returns `void`, but this is untenable for us. Async errors that occur when writing the response need to be handle-able by the user. Note that the JS implementation already returns a promise, we just need to fix the types.

```ts
 export interface RequestEvent { 
   readonly request: Request; 
   respondWith(r: Response | Promise<Response>): Promise<void>; 
 }
```

<details>
<summary>Rename tangent</summary>

As we diverge further from `FetchEvent`, I also think we should improve the function's name to just `respond()`.
```ts
 export interface RequestEvent { 
   readonly request: Request; 
   respond(r: Response | Promise<Response>): Promise<void>; 
 }
```
</details>

**Comment by lucacasonato** [comment]
Returning a promise does make sense to me, but I disagree about this statement:

> As we diverge further from FetchEvent, I also think we should improve the function's name to just respond().

**Comment by bartlomieju** [comment]
> To align with https://developer.mozilla.org/en-US/docs/Web/API/FetchEvent/respondWith#return_value the current definition returns void, but this is untenable for us. Async errors that occur when writing the response need to be handle-able by the user. Note that the JS implementation already returns a promise, we just need to fix the types.

Correct me if I'm wrong but that doc page suggest that it shouldn't return the promise. I agree that it's a strange API but as you say we shouldn't diverge from it. Plus when using `for await` loop calling `await respondWith()` will make the loop non concurrent

**Comment by nayeemrmn** [comment]
> Correct me if I'm wrong but that doc page suggest that it shouldn't return the promise. I agree that it's a strange API but as you say we shouldn't diverge from it.

I'm saying the current definition aligns with that API, and we _should_ diverge from it out of necessity. It's the only way of exposing async errors to the user. There is no real benefit to aligning with that standard and it's too high level for the server.

> Plus when using `for await` loop calling `await respondWith()` will make the loop non concurrent

As with the std server they'd have a `.catch()` handler or otherwise instead... I'm also not sure it's a thing to handle multiple requests from the same connection concurrently. The async dispatch is around the `httpConn` loop and needed either way. https://github.com/denoland/deno/blob/dc4ab98ee732defc4e781ff12137f057a6a249b0/cli/bench/deno_http_native.js#L10-L17

**Comment by jimmywarting** [comment]
This was a bit unexpected. I didn't like that it diverged from the spec and returned a promise, i didn't know that it did... in return i get `unhandledrejection` and the server dies... if you are going to diverge then i would have wanted you to call it something else like `response`

**Comment by bartlomieju** [comment]
@jimmywarting I suggest to use `Deno.serve()` API if you are integrating an HTTP server. We are going to stabilize that API this month and there's a good chance that `Deno.serveHttp()` will be deprecated for Deno 2.
