### ISSUE TITLE
--deps is broken 

### ISSUE THREAD

**Issue by ry** [denoland/deno#1011]
There's been a regression in `--deps`. 
```
~/src/deno> ./out/debug/deno tests/https_import.ts --deps
Hello
~/src/deno>
```
It could really use a top-level test. (Tho we need a way of running [check_output_tests](https://github.com/denoland/deno/blob/master/tools/check_output_test.py) with arguments to do that.)

Probably should add tools/test_deps.py to test this with arguments.

cc @mirkojotic

**Comment by mirkojotic** [comment]
@ry ok, I'll be working on it

**Comment by ry** [comment]
Ya thanks.
