### ISSUE TITLE
Use `data-url` crate for data url decoding in module loader & lsp

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#10118]
Currently we implement our own data url parsing in the `data_url_media_type` function in the lsp: https://github.com/denoland/deno/blob/1ed95120225eb3d7c9adeadcc3b1f610dbe55b7e/cli/lsp/urls.rs#L52-L61

We also implement a slightly different parser in the module loader: https://github.com/denoland/deno/blob/8d55d8b6be8731d37ccf6a29127b3a91a8319d0b/cli/file_fetcher.rs#L156-L188

Both of these custom parsers are highly spec incompliant and should be replaced with the parser from the `data-url` crate which is compliant with https://fetch.spec.whatwg.org/#data-urls.

**Comment by satyarohith** [comment]
Working on it.

**Comment by ObiWanRohan** [comment]
The `data-url` crate works on strings instead of parsed URLs. 
All usages will also have to be changed
