### ISSUE TITLE
Panic when parsing certain structures

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#10112]
In Deno main, the following code will cause a panic:

```ts
function a() {
  try {}
}
```

Something along the lines of:

```
thread 'main' panicked at 'internal error: entered unreachable code: assertion failed: (span.start <= span.end).
 start = 24, end = 23', /Users/kitsonk/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_ecma_parser-0.54.0/src/parser/stmt.rs:549:27
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I discovered the issue while using the Deno LSP and typing a `try {}` block in the editor, which is a common pattern when attempting to write out a `try...catch` block in a function.  While the syntax isn't invalid, swc shouldn't be panicing.

cc/ @kdy1

**Comment by kdy1** [comment]
I'll fix it soon.

Btw, are you going to swc's parser for lsp?

**Comment by kitsonk** [comment]
@kdy1 yes, we use it for dependency analysis and for certain code completions. We are also going to use it to detect some symbols like `Deno.test` so we can provide more intelligence, but also `deno format` and `deno lint` are integrated into the lsp which also use the parser.

**Comment by nayeemrmn** [comment]
@kitsonk Is this fixed?

**Comment by kitsonk** [comment]
Don't know.  Haven't had to the time to validate that the PR in swc was released and the Deno has updated to that release or later.

**Comment by nayeemrmn** [comment]
We have as of 1.9.0, I made a list of issues that were fixed but didn't know how to repro this one to confirm.

**Comment by kitsonk** [comment]
I just tried it off a recent version of main and it no longer occurs.
