### ISSUE TITLE
lsp: lint diagnostics should have a quick fix to add ignore comment

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#10122]
Lint diagnostics in the LSP should produce a code action quick fix that inserts a comment to ignore the lint rule.

For example, the following:

```ts
declare var a: any;
```

Which generates the diagnostic:

```
`any` type is not allowed
deno-lint(no-explicit-any)
```

Should have a quick fix which would transform the code to:

```ts
// deno-lint-ignore no-explicit-any
declare var a: any;
```

**Comment by lucacasonato** [comment]
Also a quick fix to add a file level ignore would be great.

**Comment by kitsonk** [comment]
Yeah, there is logic around "fix all" which means we could send the single one and a bundle up duplicates in the same file with a "fix all" quick fix that adds it to the top... picking the right place will be the "challenge" in this, as it takes some quite complex AST logic to get the insert location correct.

**Comment by satyarohith** [comment]
Working on this.
