### ISSUE TITLE
is deno support sourcemap ?

### ISSUE THREAD

**Issue by gcxfd** [denoland/deno#10124]
I wrote a very simple script to convert coffeescript into javascript ( https://github.com/rmw-deno/rs/blob/master/.direnv/bin/coffee.coffee ) then can use in deno .

But I found deno seems not support  sourcemap?

This is very unfriendly to debug

**Comment by lucacasonato** [comment]
Deno does support inline source maps. Other source map support is tracked in #4499. Closing this as a duplicate.

**Comment by al6x** [comment]
I use inline source maps with coffeescript, and deno still shows the js lines in the error stack traces.
deno 1.36.3

**Comment by bartlomieju** [comment]
@al6x can you open a separate issue with a reproduction code?

**Comment by al6x** [comment]
[New issue with Inline Source Map error](https://github.com/denoland/deno/issues/20392)
