### ISSUE TITLE
deno completions only works for deno cli arguments not for file completions

### ISSUE THREAD

**Issue by sspilleman** [denoland/deno#10166]
Hi,

I'm using oh-my-zsh with "deno completions zsh". brew installed them in "/usr/local/share/zsh/site-functions".
I believe the basic completions work brilliantly to autocomplete deno arguments.

Somehow it seems that the "normal" path auto completion is not working.
Let take this example. My command "so far" is:

`deno --unstable run --allow-all --import-map=deps.json exa`

If I then press **tab**, I would expect **exa** to autocomplete to **example.ts** if that file is in the current directory..... It doesn't. It seems after I start with **deno** only deno "native" commandline options are presented and not the filesystem

Any Clues?

Sander

**Comment by sspilleman** [comment]
Does anyone any clues or workarounds?

**Comment by jsejcksn** [comment]
I have determined that the lack of completion is caused by using a named parameter which uses `=`. So in your example the `--import-map=deps.json`. I haven't researched further.

**Comment by sspilleman** [comment]
> I have determined that the lack of completion is caused by using a named parameter which uses `=`. So in your example the `--import-map=deps.json`. I haven't researched further.

If I remove the "=" so my command-line looks like:

`deno run --unstable --allow-all --import-map deps.json exa`

It still doesn't work :(

**Comment by lucacasonato** [comment]
Blocked on an upstream issue in clap: https://github.com/clap-rs/clap/issues/568

**Comment by sspilleman** [comment]
> Blocked on an upstream issue in clap: [clap-rs/clap#568](https://github.com/clap-rs/clap/issues/568)

It seems there isn't any reasonable progress there, not sure what it means that they removed the 3.0 milestone tags, maybe pushing it further down the roadmap.....

Can't "we" switch to a different library?

**Comment by mcornella** [comment]
I can confirm that using `.value_hint` fixes file completion in zsh, at least for `deno compile`, `deno test` and `deno run`, with the following changes:
```diff
diff --git a/cli/flags.rs b/cli/flags.rs
index 614a975b1..2968a286c 100644
--- a/cli/flags.rs
+++ b/cli/flags.rs
@@ -6,6 +6,7 @@ use clap::Arg;
 use clap::ArgMatches;
 use clap::ArgSettings;
 use clap::ColorChoice;
+use clap::ValueHint;
 use deno_core::serde::Deserialize;
 use deno_core::serde::Serialize;
 use deno_core::url::Url;
@@ -1355,7 +1356,8 @@ fn test_subcommand<'a>() -> App<'a> {
         .help("List of file names to run")
         .takes_value(true)
         .multiple_values(true)
-        .multiple_occurrences(true),
+        .multiple_occurrences(true)
+        .value_hint(ValueHint::FilePath),
     )
     .arg(
       watch_arg(false)
@@ -1799,6 +1801,7 @@ fn script_arg<'a>() -> Arg<'a> {
     ])
     .help("Script arg")
     .value_name("SCRIPT_ARG")
+    .value_hint(ValueHint::FilePath)
 }
 
 fn lock_arg<'a>() -> Arg<'a> {
```
Of course `deno test` completion is still broken due to https://github.com/denoland/deno/issues/13702.

I haven't been able to specify `value_hint` multiple times, so we can't use `FilePath` and `Url` for the same argument.

**Comment by sspilleman** [comment]
Seems this is fixed
