### ISSUE TITLE
`deno bundle` fails: Uncaught ReferenceError: Command is not defined

### ISSUE THREAD

**Issue by clixyz** [denoland/deno#10177]
### Steps to reproduce

1. Create `c.ts` and fill in the following code:
``` typescript
import { Command } from 'https://deno.land/x/cliffy@v0.12.1/command.ts';
const c = new Command();
```

2. Bundle `c.ts` to `c.bundle.js`
```
$ deno bundle c.ts c.bundle.js
```

3. Run `c.bundle.js`
```
$ deno run c.bundle.js
error: Uncaught ReferenceError: Command is not defined
const c = new Command();
          ^
    at file:///private/tmp/c.bundle.js:2569:11
``` 

### Environment 

```
$ deno --version
deno 1.9.0 (release, x86_64-apple-darwin)
v8 9.1.269.5
typescript 4.2.2
```

Note, above example can be reproduced on both MacOS and Ubuntu, from deno 1.8.2 to deno 1.9.0.

### Possibile Fix

Manually modify `const c = new Command();` in `c.bundle.js` to `const c = new Command1();`.

**Comment by kitsonk** [comment]
cc/ @kdy1

**Comment by kdy1** [comment]
Already fixed on upstream. (I verified by adding a test)

**Comment by clixyz** [comment]
@kdy1 What do you mean by "upstream"? The master branch of swc? So how do I fix this issue on my own? Deno 1.9 still complains.

**Comment by lucacasonato** [comment]
You will have to wait for the 1.9.1 release. Should be released within the next week.

**Comment by clixyz** [comment]
@lucacasonato Got that. Thank you very much!

**Comment by clixyz** [comment]
@kitsonk @kdy1 still happens on deno 1.9.1 (release, x86_64-apple-darwin), v8 9.1.269.5, typescript 4.2.2

**Comment by kdy1** [comment]
I tested it in swc (pr: https://github.com/swc-project/swc/pull/1595), but it works.

So I checked package versions and it seems like `swc_bundler` is not updated.

`cargo update` from main branch of deno (https://github.com/denoland/deno/commit/572ec4a0a7ffd11c37fb48bbe7b8f86e9693d253)

```sh
➜  deno git:(main) ✗ cargo update
    Updating crates.io index
    Updating async-trait v0.1.48 -> v0.1.50
    Updating build_const v0.2.1 -> v0.2.2
    Updating crossbeam-channel v0.5.0 -> v0.5.1
      Adding dprint-core v0.37.0
    Updating dprint-plugin-typescript v0.44.0 -> v0.44.1
    Updating gfx-backend-dx12 v0.7.0 -> v0.7.1
    Updating http v0.2.3 -> v0.2.4
    Updating httparse v1.3.5 -> v1.4.0
    Updating idna v0.2.2 -> v0.2.3
    Updating jobserver v0.1.21 -> v0.1.22
    Updating notify v5.0.0-pre.6 -> v5.0.0-pre.7
    Updating pin-project v1.0.6 -> v1.0.7
    Updating pin-project-internal v1.0.6 -> v1.0.7
    Updating redox_syscall v0.2.5 -> v0.2.6
    Updating reqwest v0.11.2 -> v0.11.3
    Updating rustls v0.19.0 -> v0.19.1
    Updating sct v0.6.0 -> v0.6.1
    Updating slab v0.4.2 -> v0.4.3
    Updating swc_bundler v0.32.0 -> v0.32.4 # swc_bundler is not updated
    Updating tokio v1.4.0 -> v1.5.0
    Updating tokio-util v0.6.5 -> v0.6.6
    Updating trust-dns-client v0.20.1 -> v0.20.2
    Updating trust-dns-proto v0.20.1 -> v0.20.2
    Updating trust-dns-resolver v0.20.1 -> v0.20.2
    Updating trust-dns-server v0.20.1 -> v0.20.2
    Updating utf-8 v0.7.5 -> v0.7.6
```

**Comment by clixyz** [comment]
@kdy1 would it be fixed on deno v1.9.2?

**Comment by kdy1** [comment]
@clixyz I think so.

**Comment by kitsonk** [comment]
Re-opening until we validate that the right bundler is part of 1.9.2.

**Comment by satyarohith** [comment]
This issue no longer exists on `1.9.2`.
