### ISSUE TITLE
idea: better diagnostics for WGSL shaders in WebGPU

### ISSUE THREAD

**Issue by DjDeveloperr** [denoland/deno#10175]
At the moment, if we pass on an invalid shader to `GPUDevice.createShaderModule`, it simply logs something like

![image](https://user-images.githubusercontent.com/43033058/114647422-af325300-9cfa-11eb-80fc-76a422278c66.png)

without any helpful message, like what's wrong (in this case its wrong built in name). If I remember correctly, `wgpu` uses `naga` to process shaders, `naga` already provides friendly errors, like

![image](https://user-images.githubusercontent.com/43033058/114647514-dbe66a80-9cfa-11eb-9dac-deaf5f452aad.png)

It would be helpful if errors were like that in Deno too.

**Comment by crowlKats** [comment]
The first error is the current naga we use, whereas the second you posted is from a newer naga version.
Either way, nothing should be getting logged. cc @lucacasonato

**Comment by lucacasonato** [comment]
Yeah, nothing should be logged by default. We should consider adding a `--webgpu-debug` flag to enable debug logging for WebGPU functions though (the spec says to include something like this).

**Comment by crowlKats** [comment]
This is fixed. It doesnt randomly log anymore, and this detailed error is accessible just like any other error in webgpu through the error stack.
