### ISSUE TITLE
--location<url> flag doesn't support all URL's

### ISSUE THREAD

**Issue by roseMix** [denoland/deno#10171]
Running a script with the location flag is the only way in Deno to set `globalThis.location` to the location specified,
(`globalThis.location = "https://myurl"` (mentioned [here](https://github.com/denoland/deno/issues/4981#issuecomment-707693541)) errors `error: Uncaught NotSupportedError: Cannot set "location".)

Deno understandably doesn't mess with `globalThis.location` except when run with the `--location` flag, but setting the location to a `file:///` URL results in this error: `Invalid value for '--location <HREF>': Expected protocol "http" or "https"`.

I don't know if this is a bug or an oversight (or intentional?) since browsers easily support file URL's as `globalThis.window.href`. 

There have been multiple issues submitted specifically about `fetch()` from local files which I believe this would solve (see #2150) but even if `fetch()`specifically is not supported, it seems to me there should be a way for Deno to access a `location` context (and maybe even to edit it) even when that URL is a file.

**Comment by lucacasonato** [comment]
It is intentional that `--location` does not support `file://` URLs. File URLs do not have a well defined origin, so they would not work for APIs like `localstorage` which rely on a window origin. Also as you said it would not work for relative `fetch`. I am going to close this because there is no ongoing standards work to define logical non opaque origins for file URLs.

**Comment by nayeemrmn** [comment]
The `--location` flag is provided provide some isomorphism with the front end of your web application. While browsers can open file URLs, no one is using file URLs for development/production of a web application and if they did, they would find lots of other web platform features that don't work in that context. Supporting local files with `fetch()` is a totally separate concern, this would just imply another indirect way of doing it.
