### ISSUE TITLE
bundle regression since 1.8.0: module import loss after 3 levels of re-export

### ISSUE THREAD

**Issue by nktpro** [denoland/deno#10174]
Here's another bizarre `deno bundle` regression since `1.8.0`. Given

`first.ts`
```typescript
export const foo = "foo";
```
`second.ts`
```typescript
export * from "./first.ts";
```
`third.ts`
```typescript
export * from "./second.ts";
```
`fourth.ts`
```typescript
import { foo } from "./third.ts";
console.log(foo);
```

`deno bundle ./fourth.ts` will produce an invalid output of:
```javascript
console.log(foo);
```
Note that `foo` is gone and is never declared in the output. However, if there are only 2 levels of export, where:

`third.ts`
```typescript
import { foo } from "./second.ts";
console.log(foo);
```

Then `deno bundle ./third.ts` will produce the correct output of:

```javascript
const foo = "foo";
console.log(foo);
```

I could only re-produce this from `1.8.0` onwards, so it seems to be a fairly new regression in `swc`.

**Comment by kitsonk** [comment]
cc/ @kdy1

**Comment by kdy1** [comment]
Fixed on upstream.
