### ISSUE TITLE
http server: Create shortcut for responses with string body

### ISSUE THREAD

**Issue by ry** [denoland/deno#10198]
Rather than encoded into an ArrayBuffer and sent via zero-copy-buf, we should have a short cut for the very common string response. This would allow us to remove the `Deno.core.encode` hack from the benchmark program:
https://github.com/denoland/deno/blob/ad7f6d4510afc71ed40da1aa1ad649d59d3aef12/cli/bench/deno_http_native.js#L8-L17

Start by adding a separate `Option<String>` argument to ResponseArgs:
https://github.com/denoland/deno/blob/ad7f6d4510afc71ed40da1aa1ad649d59d3aef12/runtime/ops/http.rs#L306-L313

Then a lot of careful plumbing.

**Comment by satyarohith** [comment]
We can directly pass strings to `new Response` without having to encode them. I updated the script in #10201.

**Comment by lucacasonato** [comment]
@satyarohith That is not the issue. We want to prevent `Response` from serializing the string into a Uint8Array internally. #10201 would slow down the benchmarks.

**Comment by satyarohith** [comment]
@lucacasonato Oh, got it. I didn't notice a small drop in benchmarks. I'll close the PR.

**Comment by kitsonk** [comment]
Something we should bring up at the CLI Design Meting @ry @lucacasonato?
