### ISSUE TITLE
Native HTTP/2 web server does not work within a WebWorker

### ISSUE THREAD

**Issue by starkpsmichael** [denoland/deno#10192]
Seems like that the new http native bindings doesn't work in a WebWorker, see example below.

**http2.ts**
```ts
const body = new TextEncoder().encode("Hello World");
for await (const conn of Deno.listen({ port: 80 })) {
  (async () => {
    for await (const { respondWith } of Deno.serveHttp(conn)) {
      respondWith(new Response(body));
    }
  })();
}
```

**worker.ts**
```ts
new Worker(
  new URL("./http2.ts", import.meta.url).href,
  {
    type: "module",
    deno: {
      namespace: true,
      permissions: {
        env: false,
        hrtime: false,
        net: true,
        plugin: false,
        read: false,
        run: false,
        write: false,
      },
    },
  },
);

```

**Working**
```sh
deno run --unstable --allow-net http2.ts
```

**Not working**
```sh
deno run --unstable --allow-net --allow-read worker.ts
```

**Error Message**
```
error: Uncaught (in worker "") (in promise) TypeError: invalid op id: expected type `rusty_v8::data::Integer`, got `rusty_v8::data::Value`
    for await (const { respondWith } of Deno.serveHttp(conn)) {
                                             ^
    at dispatch (deno:core/core.js:76:12)
    at Object.opSync (deno:core/core.js:114:27)
    at Object.serveHttp (deno:runtime/js/40_http.js:13:27)
```

**Comment by lucacasonato** [comment]
Issue here is that the http ops are not registered in the web worker isolate.

HTTP ops should be registered in the web worker (https://github.com/denoland/deno/blob/main/runtime/web_worker.rs#L252), just like they are in the main worker (https://github.com/denoland/deno/blob/main/runtime/worker.rs#L141).

**Comment by satyarohith** [comment]
Working on it.

**Comment by cztomsik** [comment]
I'm getting this with native plugin after last upgrade

**Comment by bartlomieju** [comment]
> I'm getting this with native plugin after last upgrade

Not sure what you mean, please provide reproduction.

**Comment by cztomsik** [comment]
it's here https://github.com/cztomsik/graffiti but I think it's because ABI changed so I will check that first
(I copied "headers" to the project so I don't need to depend on rusty_v8  https://github.com/cztomsik/graffiti/blob/30a9aa89f01a3ac121be024feef238c115e92704/libgraffiti/src/bindings/deno.rs#L88)

**Comment by AaronO** [comment]
@cztomsik Plugins are broken in 1.9 due to the substantial op-layer changes. There are efforts to improve plugins for 1.10, migrating them over to the new ops, access to ResourceTable/OpState, etc...
