### ISSUE TITLE
Replace runtime/01_web_util.js cloneValue with Deno.core.serialize/Deno.core.deserialize

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#10208]
Now that we have `Deno.core.serialize()` and `Deno.core.deserialize()` available, we should replace the helper `cloneValue()`.

**Comment by EladKeyshawn** [comment]
@kitsonk HI can i work on this?  😀
Anyhow why clone is not necessary? Since we can you serialize and then deserialize to get the same effect?

**Comment by lucacasonato** [comment]
@EladKeyshawn That is exactly it. serialize + deserialize == clone.

**Comment by bartlomieju** [comment]
Done in #10215
