### ISSUE TITLE
Fix linting step which now breaks on JSX since 1.9

### ISSUE THREAD

**Issue by MichaelCurrin** [denoland/deno#10212]
I noticed since upgrading to 1.9 that I get lint errors in my React app. I think others will have this issue to but wanted to report it.

## Reproduce

OK:

```sh
deno upgrade --version 1.8.3
deno lint --unstable --ignore=build,public,docs,README.md
```
```
Checked 10 files
```

Error:

```sh
deno upgrade
deno lint --unstable --ignore=build,public,docs,README.md
```
```
(no-unused-vars) `React` is never used
import { React } from "../../deps.ts";
...
```

**Comment by bartlomieju** [comment]
Tracked in https://github.com/denoland/deno_lint/issues/663

**Comment by MichaelCurrin** [comment]
Oh thanks. Sorry I did search for existing issues but didn't search wide enough.
