### ISSUE TITLE
HTTP2 - sending server trailers

### ISSUE THREAD

**Issue by prohazko2** [denoland/deno#10214]
Hi,

Was playing around with gRPC implementation and almost succeed with basic unary calls serving
https://github.com/prohazko2/deno-grpc/blob/0.1.3/serve.ts

1. http2 with `Deno.serveHttp` was ok
2. protobuf msgs decoding/encoding with `protobuf.js` was ok
3. thing that I didn't figure out - how to send `OK` status back to client

Similar node's `@grpc/grpc-js` response has two server trailers: 
```
[0] Received server trailers:
		grpc-status: 0
		grpc-message: OK

[0] received status code 0 from server
[0] received status details string "OK" from server
```
Seems like they are sent with this call to node `http2stream.sendTrailers` 
[@grpc/grpc-js@1.3.x ... server-call.ts](https://github.com/grpc/grpc-node/blob/%40grpc/grpc-js%401.3.x/packages/grpc-js/src/server-call.ts#L602)

But I didn't have any luck with sending them with Deno's `respondWith` / `Response` API's

**Comment by lucacasonato** [comment]
Trailers are not supported in the `fetch` spec anymore, and likely will not be re-introduced unless there is significant demand: https://github.com/whatwg/fetch/issues/981. I don't think we will be supporting them either if the web does not.

**Comment by kitsonk** [comment]
Looking at this more, it feels like instead of "trailers" you want to do something like SSE... where you return a `ReadableStream` as a body, and continue to `.enqueue()` `Uint8Array`s in the streams controller for as long as you need before closing the controller and ending the response.

**Comment by prohazko2** [comment]
Thanks, will try.
Also closing issue since trailers out of spec
