### ISSUE TITLE
Move hyper binding into extensions/http

### ISSUE THREAD

**Issue by ry** [denoland/deno#10210]
Probably needs to be modified to operate on generic `AsyncRead + AsyncWrite`. The Conn -> HttpConn upgrader should stay in `runtime/`.

Probably web socket API should be completed first: #10211

**Comment by bartlomieju** [comment]
> Probably needs to be modified to operate on generic AsyncRead + AsyncWrite

This is not feasible - you can't specify these trait boundaries for resource and make borrow checker happy. We've tried it several times for "io" resources (that have `op_read` or `op_write`) and ended up hardcoding them as conditionals because of this problem.

**Comment by lucacasonato** [comment]
@bartlomieju The op_http_next_request / read / write functions could all become generic over the generic parameter of the HttpConn resource. That way it is not really generic at runtime - it would all boil down to a single concrete type at compile time. (like how we do generic permissions in op crates).

**Comment by bartlomieju** [comment]
Done in #11335
