### ISSUE TITLE
Cannot augment typed array (browser incompatibility)

### ISSUE THREAD

**Issue by josephrocca** [denoland/deno#10221]
While trying to run some browser code in Deno, I noticed that some browserify code was checking for typed array support by checking if this code snippet throws an error:
```js
var arr = new Uint8Array(1)
arr.__proto__ = { __proto__: Uint8Array.prototype, foo: function () { return 42 } }
arr.foo() === 42
```
It does throw an error in Deno ~~(and Node)~~, but not in browsers.

(**Edit**: Woops, it does actually work in Node.js too)

I have no idea why this is the type of check they decided to use to check for typed array support, and it's hard to see any real world use case for augmenting typed arrays like this (it seems inadvisable), but I thought I'd report this browser incompatibility in case it's a bug. Please close this issue right away if it' is expected behavior.

Cheers!

**Comment by crowlKats** [comment]
This is intended behaviour. See #4324

**Comment by lucacasonato** [comment]
Deno does not support the `__proto__` property. Instead to create an object with a given prototype, use a `class`, or `Object.extends`.

**Comment by josephrocca** [comment]
@crowlKats @lucacasonato Ah, thank you both - lightening fast replies!

**Comment by kitsonk** [comment]
@lucacasonato you mean [Object.create()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/create) right?

**Comment by lucacasonato** [comment]
> @lucacasonato you mean [Object.create()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/create) right?

Ah yes. My bad.
