### ISSUE TITLE
Support for windows ctrl-c signal

### ISSUE THREAD

**Issue by juzi5201314** [denoland/deno#10236]
Hey, what I want to ask is, is there any plan to support ctrl c signal under windows?

I think this is a very useful function for the cli program. It can exit the program normally, close the resource, and trigger window.onunload.
Since tokio already has related functions, it should be very simple to implement.

This is what I simply changed: https://github.com/juzi5201314/deno/commit/9ea6d4c00770455b896671a730763c8f2d346992

**Comment by bnoordhuis** [comment]
Anything that reduces the friction between Windows and UNIX is almost certainly welcome. Can you open your change as a pull request? Thanks.
