### ISSUE TITLE
Windows' importing seems to work different from Linux and MacOS resulting in a "Cannot resolve module" error

### ISSUE THREAD

**Issue by CuriousIbrahim** [denoland/deno#10249]
The error comes from the following sample code:

```
// A.ts
import { b1 } from "./B.ts";

export const a1 = () => {
    console.log(b1);
}

export const a2 = () => {
    "a2";
}
```

```
//B.ts
import { a2 } from "./A.ts";

export const b1 = "b1";

export const b2 = () => {
    console.log(a2);
}
```

```
// main.ts
import { a1 } from "./A.ts"

a1();
```

When running `deno run main.ts` on either Linux or MacOS it outputs `b1` which is expected, however on Windows it outputs the following error:

```
error: Cannot resolve module "file:///.../A" from "file:///.../main.ts".
    at file:///.../main.ts:1:0
```

Seems like the import on main is causing problems, that is because A.ts and B.ts are importing modules from each other however it's not the same modules, so it can't be a circular dependency. That error though `Cannot resolve module` seems to occur when the runtime gives up on importing the module; from my research, it can occur in cases of circular dependency. Maybe on the Windows environment, it thinks it's a circular dependency, not entirely sure though.

**Comment by piscisaureus** [comment]
Works as expected for me:

```
D:\deno\try>type A.ts
// A.ts
import { b1 } from "./B.ts";

export const a1 = () => {
    console.log(b1);
}

export const a2 = () => {
    "a2";
}
D:\deno\try>type B.ts
//B.ts
import { a2 } from "./A.ts";

export const b1 = "b1";

export const b2 = () => {
    console.log(a2);
}
D:\deno\try>type main.ts
// main.ts
import { a1 } from "./A.ts"

a1();
D:\deno\try>deno run main.ts
b1

D:\deno\try>
```

Are you sure `A.ts` and `B.ts` are have exactly the same file name (case) on disk?

**Comment by CuriousIbrahim** [comment]
I see the issue, I was importing it as "A", not "A.ts"; once I added the ".ts" extension it fixed the issue. Thank!
