### ISSUE TITLE
lsp: registry completions issues

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#10265]
Here are a few completion issues with lsp registry completions I have discovered over the last week:

1. First item after origin is not recommended until first char is typed. Registry: https://crux.land. Example: 

https://user-images.githubusercontent.com/7829205/115377795-3dfa1080-a1d0-11eb-8c53-4acfdb5f552a.mov

2. Completions directly following a separator (`@`/`/`) do not complete unless a first char is typed. Registry: https://crux.land and https://x.nest.land. Example:

https://user-images.githubusercontent.com/7829205/115378240-a21cd480-a1d0-11eb-877a-250e15152d97.mov

**Comment by nayeemrmn** [comment]
Can't reproduce now, probably fixed.
