### ISSUE TITLE
`deno compile` should generate a static executable for Linux

### ISSUE THREAD

**Issue by hronro** [denoland/deno#10263]
Currently both deno itself and executable generated from `deno compile` are not static executable, but generating static executable will help a lot since some Linux distributes doesn't have glibc (like Alpine Linux, which is used widely in Docker).

**Comment by lucacasonato** [comment]
I am going to close this as an effective duplicate of #1658 (releasing libc binaries using MUSL).

**Comment by pvormittag** [comment]
Linking this to https://github.com/denoland/deno/issues/3711 in case anyone else, like me, ends up here looking for an issue to track support for `musl`.

I also hope to spear you from reading through #1658's long, convoluted comment thread 😅.
