### ISSUE TITLE
Deno.env.toObject() values can be undefined

### ISSUE THREAD

**Issue by nayeemrmn** [denoland/deno#10267]
https://github.com/denoland/deno/blob/262ee78592209a1f8e449cfa1308dca9688a414e/cli/dts/lib.deno.ns.d.ts#L221
->
```ts
    toObject(): { [index: string]: string | undefined };
```

It's a breaking change and should wait for 2.0. Ref #10138.

**Comment by jsejcksn** [comment]
There are many closed issues related to this in the TS repo. Here's a point of departure: https://github.com/microsoft/TypeScript/issues/13778

Is there something unique about this case which differentiates it? For example: explicitly defined keys with a value of `undefined`?

If that's not the case, and this is decided to be implemented, then:
  - care should be taken to implement the [Symbol.iterator] signature to yield `NonNullable` values
  - should all index signature types be changed to include `undefined`?

**Comment by nayeemrmn** [comment]
We don't care too much about array index signatures, because we're used to that being a runtime OOB error in other languages. Whereas `Deno.env.toObject()` would be interacted with more like a `Map`.

**Comment by jsejcksn** [comment]
> Whereas `Deno.env.toObject()` would be interacted with more like a `Map`.

Then shouldn't it become a `Map`?

**Comment by nayeemrmn** [comment]
The API of `Deno.env` reflects a map already. The more relevant point is that the "valid" keys are determined by the external environment, not some set of names statically defined by the surrounding code.

**Comment by timreichen** [comment]
https://github.com/denoland/deno/issues/10349#issuecomment-885403016

**Comment by lucacasonato** [comment]
If you want behaviour like this, you should use `noUncheckedIndexAccess: true`. The current proposal has the flaw that it suggests that a value can be `undefined` even if `"key" in Deno.env.toObject()` passes, even if that is not the case. That is something that `noUncheckedIndexAccess` would handle correctly.
