### ISSUE TITLE
benchmark page: limit number of commits shown

### ISSUE THREAD

**Issue by ry** [denoland/deno#1027]
there's getting to be a lot of data shown on https://denoland.github.io/deno/

It would be cool to limit this to, say, the most recent 20 commits.

To avoid having to load the whole data.json - it would be good if we also wrote a dead_recent.json with only the most recent data.

cc @kt3k

**Comment by kt3k** [comment]
OK I'll take this.

By the way how about creating another page for showing all data (= current behavior)?
