### ISSUE TITLE
EmitOptions::bundle values should be "module" and "classic"

### ISSUE THREAD

**Issue by nayeemrmn** [denoland/deno#10288]
- `Deno.emit({ bundle: "esm" })` -> `Deno.emit({ bundle: "module" })`
- `Deno.emit({ bundle: "iife" })` -> `Deno.emit({ bundle: "classic" })`

See `WorkerOptions::type`. Note that an iife is just a sensible way of emitting a classic script (whereas modules are already encapsulated), it's not the true distinction.

**Comment by ry** [comment]
Those are much more intelligible names, I agree.

**Comment by kitsonk** [comment]
I would prefer `script` over `classic`.

**Comment by nayeemrmn** [comment]
We sometimes informally refer to classic scripts as just "scripts", but the correct terminology that the web uses is "classic scripts" vs "module scripts". https://github.com/denoland/deno/blob/21ab4d94c0edca94cb71c5e444f93005074b17f2/cli/dts/lib.deno.shared_globals.d.ts#L422-L425

**Comment by kitsonk** [comment]
Fair enough...
