### ISSUE TITLE
Trying to inst. on Win10:  " error[E0658]: `match` is not allowed in a `const fn` "

### ISSUE THREAD

**Issue by Fxztam** [denoland/deno#10285]
Hi,
so far I have not been able to install deno:

windows10> _cargo install deno --locked_

![image](https://user-images.githubusercontent.com/5808032/115544252-a6192700-a2a2-11eb-8e00-cf5b1973aaab.png)

what's wrong with me?

Regards, Fried

**Comment by kitsonk** [comment]
```
$ rustc --version
```

Needs to be 1.51.0

**Comment by Fxztam** [comment]
Right, I upgraded Rust - and now:
rustc 1.44.1 (c7087fe00 2020-06-17) .

Tried again with:
> cargo install deno --verbose 

=> Compiling seems ok
=> _build-fbf8b99b2d6e5819.exe : fatal error LNK1319: 667 conflicts identified.

Thanks
