### ISSUE TITLE
Create a EventSource implementation

### ISSUE THREAD

**Issue by MickeL** [denoland/deno#10298]
It seems there is no implementation for EventSource to read server-sent events in deno.

It would be a useful feature when reading events from another server from deno, just like one would in a browser client.

https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events#receiving_events_from_the_server

**Comment by kitsonk** [comment]
This is not something that would require unique support in the CLI. It is something that could start as a community package and maybe be added to the std library. Deno includes the primitives to provide this already, like the fetch API and the DOM `EventTarget`.

**Comment by kitsonk** [comment]
@mierenmanz here is the issue mentioned in GitHub.

Re-opening, as suggested it is a [community project](https://deno.land/x/eventsource) and we have increased our desire for inclusion of other web platform APIs, even if they don't require specialised support from the Deno runtime to work.
