### ISSUE TITLE
Download percentage while updating ( `deno upgrade` )

### ISSUE THREAD

**Issue by darkred** [denoland/deno#10291]
Using Deno with Windows Terminal 1.7.1033.0 on Windows 10 x64 20H2.

I quote from the manual:

> To update a previously installed version of Deno, you can run:
> 
> ```
> deno upgrade
> ```
> 
> This will fetch the latest release from https://github.com/denoland/deno/releases, unzip it, and replace your current executable with it.

These zip files size currently is between 23 and 30 MB.
Such a download may take some time to complete depending on the internet connection.

My suggestion is to display the current download percentage while downloading the relevant zip file:
i.e. to display below `Download has been file` a progress percentage, 
e.g.: `Downloading 1.0% of 23.00 MiB`
![2021-04-21_192118](https://user-images.githubusercontent.com/723651/115587838-c82c9c80-a2d6-11eb-97fc-c24cc6bf1a92.jpg)

Currently it doesn't display any download progress until it completes(+then unzips it) :

<details>
<summary>screenshot</summary>

![2021-04-21_191732](https://user-images.githubusercontent.com/723651/115587434-5eac8e00-a2d6-11eb-862a-e529a9e58e3e.jpg)

</details>

If it helps in visualizing it, here is how youtube-dl displays the download percentage:
![2021-04-21_191232](https://user-images.githubusercontent.com/723651/115586998-d5955700-a2d5-11eb-890b-983e0e788569.jpg)

Thank you

**Comment by juzi5201314** [comment]
I also think this is a good idea!

**Comment by juzi5201314** [comment]
Hey, I'm trying to do this work. Regarding the progress bar, there are two popular libraries to choose from: [a8m/pb](https://github.com/a8m/pb), [mitsuhiko/indicatif](https://github.com/mitsuhiko/indicatif).
indicatif looks more beautiful and personalized, but there is a small problem: it cannot be displayed on the console of Intellij Idea [issue #193](https://github.com/mitsuhiko/indicatif/issues/193).
What do you guys think?
