### ISSUE TITLE
TypeScript option noUncheckedIndexedAccess not documented

### ISSUE THREAD

**Issue by szagi3891** [denoland/deno#10305]
In version typescript 4.1 the option "noUncheckedIndexedAccess" has been added.
I would strongly advise deno to support the ability to set this option.

https://www.typescriptlang.org/tsconfig#noUncheckedIndexedAccess

**Comment by kitsonk** [comment]
Are you unable to set it via the `--config` option?

**Comment by szagi3891** [comment]
I haven't checked because I haven't found this option in the documentation:
https://deno.land/manual@v1.9.1/typescript/configuration

The documentation may be out of date regarding this option ?

**Comment by zeshan321** [comment]
Updated in #10324

**Comment by szagi3891** [comment]
@kitsonk @zeshan321 - Thank you. So now I have no excuse for myself and have to experiment with such a great solution as deno :D
