### ISSUE TITLE
Deno unable to read files with emojis in path

### ISSUE THREAD

**Issue by C-NERD** [denoland/deno#10304]
Hi I am currently working on a project where I have to read img files from the local computer (I used --allow-read to run), and the path to the file I want to read has emojis on path. Deno was able to success fully get the path to the file but it was unable to read the file because it could not find it with emoji on path(yes I already tested it without emojis) if this is not a bug I hope a feature like this will be implemented in the next release version of deno

**Comment by bartlomieju** [comment]
Please provide an example reproduction that triggered this error. Most likely related to #627

**Comment by C-NERD** [comment]
```js
const __dirname = new URL(import.meta.url).pathname; //get's script's path
const __rootdir = getRootDir(__dirname); //get's projects root directory
/*had a problem using ../ directly with __dirname to navigate to the previous directory
so you might want to check that one out too*/

const path = __rootdir + "assets/index.html"; //gets full path to html file
const html = Deno.readTextFileSync(path).replace("$", imgpath); //has a problem reading file beacause of emoji in path

**Comment by C-NERD** [comment]
and when i run 
`console.log(__rootdir)`
i get an output like
`file:///home/cnerd/Documents/WebTech/Oju_Lewa%F0%9F%98%8D/src/src/ojulewa.ts`
the unreadable part is the emoji 😍

**Comment by caspervonb** [comment]
You probably want to do `const path = new URL(__rootdir + "assets/index.html")` here.

**Comment by C-NERD** [comment]
Sorry my actual error code is
```bash
error: Uncaught (in promise) NotFound: No such file or directory (os error 2)
    throw new ErrorClass(res.err.message);
          ^
    at processResponse (deno:core/core.js:212:11)
    at Object.jsonOpSync (deno:core/core.js:235:12)
    at openSync (deno:runtime/js/30_files.js:30:22)
    at Object.readTextFileSync (deno:runtime/js/40_read_file.js:22:18)
    at ojulewa.ts:22:19
    at <anonymous> (<anonymous>)
```
the error code i got earlier is from passing the wrong source path to deno

**Comment by C-NERD** [comment]
> You probably want to use URLs there rather than paths, you're passing url encoded strings as paths which don't get translated.

I just tried this using `encodeURIComponent` and all it does is replace the */* characters with `%2F`

**Comment by C-NERD** [comment]
Turns out deno can read the files just fine if i replace the encoded emoji `(%F0%9F%98%8D)` with the real emoji `(😍)`, the problem is probably from this line

```js
const __dirname = new URL(import.meta.url).pathname; //get's script's path
```
because it's responsible for getting the initial path

**Comment by C-NERD** [comment]
So i used decodeURI to decode the constant __rootdir and everything works just fine. Thanks to everyone who helped really appreciate it 🏆
