### ISSUE TITLE
Error in WebSocket#eventLoop

### ISSUE THREAD

**Issue by LukeChannings** [denoland/deno#10300]
I experience the following error when running my test suite with 1.9.1:

```
error: Uncaught (in promise) TypeError: Cannot use 'in' operator to search for 'string' in error
    at WebSocket.#eventLoop (deno:op_crates/websocket/01_websocket.js:315:22)
```

https://github.com/denoland/deno/blob/main/op_crates/websocket/01_websocket.js#L315
https://github.com/LukeChannings/moviematch/runs/2404786637

It seems like `message` can be a string, and there's no check to handle that case.

**Comment by lucacasonato** [comment]
Yup, we are going to be rolling out a 1.9.2 hotfix for this very soon. You can temporarily downgrade to 1.9.0, where this issue is not present.
