### ISSUE TITLE
The repl execution context should be a module

### ISSUE THREAD

**Issue by canonic-epicure** [denoland/deno#10309]
In Deno 1.9.0, trying to perform the dynamic import in the repl, results in:
```
> const dec = await import "https://deno.land/std@0.83.0/encoding/utf8.ts"
Uncaught SyntaxError: Cannot use import statement outside a module
```
which indicates, that repl execution context is "classic", not a module. I guess, for Deno being a modern environment, it makes sense to have a module context everywhere.

**Comment by DjDeveloperr** [comment]
That's not right way to do dynamic import. You have to call import as a function, that is
```
const dec = await import("https://deno.land/std@0.83.0/encoding/utf8.ts")
```

**Comment by canonic-epicure** [comment]
Ah, you are right of course. Closing.
