### ISSUE TITLE
Terminal problem

### ISSUE THREAD

**Issue by yunusemrealtiner** [denoland/deno#10301]
what is the reason of this? The texts on the terminal look like this. What could be the reason?
![IMG_20210422_012219](https://user-images.githubusercontent.com/71217957/115628371-35592580-a309-11eb-919d-f19cd45abd13.png)

**Comment by MierenManz** [comment]
That is the escape sequence for colors. And your terminal doesn't support colors so it prints out the escape sequence eventho it shouldn't

**Comment by yunusemrealtiner** [comment]
> That is the escape sequence for colors. And your terminal doesn't support colors so it prints out the escape sequence eventho it shouldn't

I solved the problem Thank you very much for your help 🙂
