### ISSUE TITLE
deno.land/x TS-to-JS transpilation via query parameter

### ISSUE THREAD

**Issue by josephrocca** [denoland/deno#10314]
**Background**: I've been using deno.land/x as an immutable hosting service for modules that can be used both in the browser and in Deno. I think that's sort of what it's designed for - or at least what it will emergently become. That is, as opposed to a hosting service purely for Deno usage.

**Problem**: A decent portion of modules on deno.land/x are understandably `.ts` modules. This means that if I want to import them into the browser, I need to transpile them, and then upload them somewhere (probably deno.land/x). It would be really, really cool if there were a way to get the deno.land/x server to do that. Something like one of these, perhaps:

```js
import mod from "https://deno.land/x/modulename@1.0/mod.ts?js";
import mod from "https://deno.land/x/modulename@1.0/mod.ts?to=js";
import mod from "https://deno.land/x/modulename@1.0/mod.ts?transpile=js";
```

The deno.land/x server would obviously save/cache the result such that this feature would add very little extra computation burden to the service.

Is a feature like this feasible?

**Comment by wperron** [comment]
Respectfully closing because this feature request is already tracked [here](https://github.com/denoland/deno_website2/issues/1722) and [here](https://github.com/denoland/deno_website2/issues/1728)
