### ISSUE TITLE
Plugin API broken in Deno 1.9.0

### ISSUE THREAD

**Issue by rracariu** [denoland/deno#10323]
Since the introduction of the new Ops API the plugin API doesn't work anymore for Async functions.

The https://github.com/denoland/deno/tree/main/test_plugin doens't run as it uses a removed function: `setAsyncHandler`

Would be awesome if the new Ops API would be exposed in the Plugin API, as it greatly simplifies writing Ops.

**Comment by crowlKats** [comment]
> Would be awesome if the new Ops API would be exposed in the Plugin API, as it greatly simplifies writing Ops.

That is already the plan with 1.10

**Comment by rracariu** [comment]
In Deno 1.10+ this issue is fixed.
