### ISSUE TITLE
What variable should be used to distinguish whether the current program is compiled? 

### ISSUE THREAD

**Issue by gcxfd** [denoland/deno#10326]
deno compile will make import.meta.url an absolute path.

What variable should be used to distinguish whether the current program is compiled? 

So I can choose whether to use import.meta.url or Deno.cwd

**Comment by jsejcksn** [comment]
Hi @gcxfd: This was already discussed in https://github.com/denoland/deno/issues/6344

You might be interested in [`Deno.mainModule`](https://doc.deno.land/builtin/stable#Deno.mainModule).
