### ISSUE TITLE
RangeError: Maximum call stack size exceeded  when creating too many op promises in a single loop

### ISSUE THREAD

**Issue by jupegarnica** [denoland/deno#10361]
I think i found a bug running a debouncer 60709 times or more.  
Looks like the clearTimeout it runs into a RangeError.

checkout the gist:
https://gist.github.com/jupegarnica/cb3a28a3a3e7f40363c14bd61abe9880

It fails at core.js at line 69 on  handleAsyncMsgFromRust
https://github.com/denoland/deno/blob/fd3b961126150960104a0d456ceac14b12f90c8b/core/core.js#L69

**Comment by kitsonk** [comment]
So it seems this is more of an issue with creating too many promises from a single Rust op to me, where the promises were called in a single iteration of the event loop.

**Comment by AaronO** [comment]
I've implemented batching for async op responses in #10398, but we could also optimize the timers op_crate to reduce the number of async ops queued for these timer operations (might do that in a follow up PR)

**Comment by bartlomieju** [comment]
I believe this is no longer the case since we can respond with multiple op values in one go. Closing for now.
