### ISSUE TITLE
Deno.noColor is constant.

### ISSUE THREAD

**Issue by ihack2712** [denoland/deno#10360]
`Deno.noColor` doesn't change when `NO_COLOR` environment variable changes. I think it should because the environment variables can be modified at runtime and `Deno.noColor` should adapt when `NO_COLOR` changes. Should be a getter.

```ts
console.log(Deno.noColor);
Deno.env.set("NO_COLOR", "1");
console.log(Deno.noColor);
```

Prints
```ts
false
false
```

Runned with

```sh
deno run --no-check --allow-env 'data:application/javascript;utf8,console.log(Deno.noColor);Deno.env.set("NO_COLOR","1");console.log(Deno.noColor);'
```

Allowing colors to be disabled at runtime is a useful feature, and in my opinion should be possible.

**Comment by sno2** [comment]
I'd like to try this as my first actual coding issue.  Thanks

**Comment by ihack2712** [comment]
It might be a difficult feature to implement, considering noColor is defined when in 99_main in the denoStart? options thingy, which is provided by the rust side in an op call. Creating a getter for it might be inefficient. On another hand, a possibility might be setting a getter only if `--allow-env` or `--allow-all` is enabled, but then again, if `--allow-env` is not provided, but allowed later through `Deno.permissions.request()` then it'll have to be turned into a getter. Another possibility is setting `Deno.noColor` on `Deno.env.set(var)` if `var` is `NO_COLOR`. A lot of possibilities.

**Comment by sno2** [comment]
Yep, just realized this when diving into the code.  Discussed this on discord:

![image](https://user-images.githubusercontent.com/43641633/115980543-22399600-a553-11eb-9178-911f1bfcc981.png)

Awaiting import from core dev.

**Comment by AaronO** [comment]
@ihack2712 What's your main use-case for this ?

**Comment by ihack2712** [comment]
> @ihack2712 What's your main use-case for this ?

I don't recall exactly what the discussion was, but it should be configurable to disable colors at runtime.

Especially since the standard fmt/colors module uses it.

https://deno.land/std@0.95.0/fmt/colors.ts#L15

**Comment by AaronO** [comment]
Yep, but what's the genuine need / use-case to do it at runtime ? Vs setting env prior to running or detecting tty support, etc...

**Comment by sno2** [comment]
> Yep, but what's the genuine need / use-case to do it at runtime ? Vs setting env prior to running or detecting tty support, etc...

You are currently able to modify the env within Deno.  Therefore, any of the `Deno` properites that state that they "reflect" ([quote from docs](https://doc.deno.land/builtin/stable#Deno.noColor)) an environment variable should correctly reflect that environment variable's value.  For example, if I can set the value of `NO_COLOR` in Deno using something like `Deno.env.set("NO_COLOR", "1")` then `Deno.noColor` should be returning `true` after that.  Is there really a need to come up with a use-case when a property does not do what it states that it does?

[Definition of Reflect](https://www.dictionary.com/browse/reflect):

![image](https://user-images.githubusercontent.com/43641633/116007927-bb11f500-a5d7-11eb-968b-affc763ecac6.png)

Anything but using getters for `Deno.noColor` would be a contradiction to what its JS Doc states that it does.

**Comment by kitsonk** [comment]
@sno2 that isn't a use case... that is grammatical pedantry.

Updating the JSDoc would be acceptable way to resolve this concern.

**Comment by sno2** [comment]
> @sno2 that isn't a use case... that is grammatical pedantry.
> 
> Updating the JSDoc would be acceptable way to resolve this concern.

I understand it's not a use-case.  I'm saying that we need to either update the JSDoc or make `Deno.noColor` correctly reflect the `NO_COLOR` env variable as the JS Doc states.

**Comment by AaronO** [comment]
I would also disagree with the interpretation somewhat, environment variables are pretty much cli arguments, most programs reasonably assume them to be static, I think it would be esoteric and uncommon to have an app use envs as a dynamic K/V store

**Comment by kitsonk** [comment]
> I would also disagree with the interpretation somewhat, environment variables are pretty much cli arguments, most programs reasonably assume them to be static, I think it would be esoteric and uncommon to have an app use envs as a dynamic K/V store.

I totally agree too, but if some people will sleep better at night having an explicit comment that the value is not dynamic in the JSDoc, it is likely such a PR would be merged.

**Comment by sno2** [comment]
> > I would also disagree with the interpretation somewhat, environment variables are pretty much cli arguments, most programs reasonably assume them to be static, I think it would be esoteric and uncommon to have an app use envs as a dynamic K/V store.
> 
> I totally agree too, but if some people will sleep better at night having an explicit comment that the value is not dynamic in the JSDoc, it is likely such a PR would be merged.

😟 I had only been trying to come up with the best fix for this issue.  I included the definition to show that most people would expect `Deno.noColor`'s to dynamically reflect the value of `NO_COLOR` in the env.  However, you all seem to not hold the idea of correct documentation as important as I do.  I will create a PR to fix this issue, but I don't think I'll contribute any more if this is how the core developers behave.

**Comment by nayeemrmn** [comment]
> However, you all seem to not hold the idea of correct documentation as important as I do.

@sno2 No... the argument is that the current documentation isn't incorrect but just leaves a little room for interpretation.

**Comment by sno2** [comment]
> > However, you all seem to not hold the idea of correct documentation as important as I do.
> 
> @sno2 No... the argument is that the current documentation isn't incorrect but just leaves a little room for interpretation.

Please refer to the Issue's first prompt:

> Deno.noColor doesn't change when NO_COLOR environment variable changes. I think it should because the environment variables can be modified at runtime and Deno.noColor should adapt when NO_COLOR changes. Should be a getter.

It is about whether `Deno.noColor` should be a getter or not.

**Comment by nayeemrmn** [comment]
@sno2 I'm not sure what you're saying now. You argued that the documentation's wording implies that it should be dynamic, others argued that it maybe doesn't, you said they don't care about correct documentation.
