### ISSUE TITLE
Response cloning stopped copying any fields in Deno 1.9

### ISSUE THREAD

**Issue by danopia** [denoland/deno#10367]
Basic repro:

```typescript
const response1 = await fetch('https://example.org');
response1.headers.get('date'); // Sun, 25 Apr 2021 etc.
const response2 = new Response(response1.body, response1);
response2.headers.get('date'); // null
```

It seems like only `status` is being kept now, looking at the value of `response2`:

```
Response {
  body: ReadableStream { locked: false },
  bodyUsed: false,
  headers: Headers {},
  ok: true,
  redirected: false,
  status: 200,
  statusText: "",
  url: ""
}
```

### repro details

Assertable repro here: https://gist.github.com/danopia/d1a69314c969895bcda52b2aaf0aea93 and it passes on 1.8.3:

```
> deno upgrade --version 1.8.3
Deno is upgrading to version 1.8.3
Upgraded successfully
> deno run --allow-net https://gist.githubusercontent.com/danopia/d1a69314c969895bcda52b2aaf0aea93/raw/1b16dfb71ec964374a996d30d2dcea7ee7183390/repro.ts

> deno upgrade
Deno is upgrading to version 1.9.2
Upgraded successfully
> deno run --allow-net https://gist.githubusercontent.com/danopia/d1a69314c969895bcda52b2aaf0aea93/raw/1b16dfb71ec964374a996d30d2dcea7ee7183390/repro.ts
error: Uncaught (in promise) AssertionError
```

Chrome:
![Screenshot 2021-04-25 17 34 53](https://user-images.githubusercontent.com/40628/115999779-637e8400-a5ed-11eb-939b-c0b244e23553.png)

**Comment by lucacasonato** [comment]
For future reference: reason is that field getters of `Response` are mistakenly not marked as enumerable. This all boils down to how we use JS classes to represent webidl interfaces. This is wrong and is actually caught by WPT (the idlharness tests), but I have just did not cared about this enough to fix it yet.

**Comment by satyarohith** [comment]
Looks like this is also the case with `Request` as per https://github.com/denoland/deno/issues/10355
