### ISSUE TITLE
URLSearchParams: Type 'number' is not assignable to type 'string'

### ISSUE THREAD

**Issue by RickStanley** [denoland/deno#10372]
This code:
```javascript
const params = {
  size: 1,
};
const search = new URLSearchParams(params);
```
throws:
```
error: TS2345 [ERROR]: Argument of type '{ index: string; scroll: string; size: number; sort: string; }' is not assignable to parameter of type 'string | URLSearchParams | string[][] | Record<string, string> | undefined'.
  Type '{ index: string; scroll: string; size: number; sort: string; }' is not assignable to type 'Record<string, string>'.
    Property 'size' is incompatible with index signature.
      Type 'number' is not assignable to type 'string'.
const search = new URLSearchParams(params);
```

But it works in REPL:
```
λ deno
Deno 1.9.2
exit using ctrl+d or close()
> const params = { size: 1 };
undefined
> const search = new URLSearchParams(params);
undefined
> search.toString();
"size=1"
```

Versions:
deno 1.9.2 (release, x86_64-unknown-linux-gnu)
v8 9.1.269.5
typescript 4.2.2

**Comment by RickStanley** [comment]
Oh sorry, this looks like an upstream "bug", see: https://github.com/microsoft/TypeScript/issues/32951

**Comment by lucacasonato** [comment]
This is correct. What you are experiencing is the implicit type coercion a dynamic language like JS has. For example `3 - "1" == 2` will return true in Javascript. Implicit type coercion is something that can often lead to bugs, so it is something that Typescript does not allow. Typescript tries to give Javascript explicit strict types, and that just doesn't work with implicit type coercion.
