### ISSUE TITLE
Ability to get allocation stack of leaking async ops

### ISSUE THREAD

**Issue by EliteScientist** [denoland/deno#10388]
It would be nice to be able to see the async objects that are leaking and their allocation stack. I think this would be useful as a command line switch to enable it while debugging. For my complex application, one part of the system seems to be affecting a different part. Their individual unit tests execute just fine. When running the entire test on the system, I'm getting random failures.

Right now I'm hunting for the leaking ops and adding more test coverage, but it would be nice to have some insight here.

**Comment by baetheus** [comment]
I think this is related to #10728 which I just created. If you have any unit tests that set `sanitizeOps` and `sanitizeResources` to false, it's like the ops are leaked by those tests and mistakenly associated with an unrelated test that just happens to be running when the leaked ops complete.

**Comment by bartlomieju** [comment]
Let's continue in https://github.com/denoland/deno/issues/13644
