### ISSUE TITLE
WebAssembly Threads

### ISSUE THREAD

**Issue by josephrocca** [denoland/deno#10381]
I wasn't able to find an open issue about Deno's support for wasm threads (available with not flag in Chromium since 2019). Error message:
```
error: Uncaught (in promise) CompileError: WebAssembly.instantiate(): invalid memory limits flags 0x3 (enable via --experimental-wasm-threads) @+699
        const instance = await WebAssembly.instantiate(module, imports);
```

**Comment by bartlomieju** [comment]
Will be enabled in https://github.com/denoland/deno/pull/10116
