### ISSUE TITLE
Allow terminating wildcards in read and write permissions

### ISSUE THREAD

**Issue by lucidNTR** [denoland/deno#10389]
currently its cumbersome to allow read and write permissions to all subfolders.
--allow-write=/asd/asdf/**
and
--allow-write=/asd/asdf/*

should be supported to provide this capability, otherwise people will just default to allowing all read and write access and lose the minimal privilege philosophy...

**Comment by satyarohith** [comment]
> currently its cumbersome to allow read and write permissions to all subfolders.

Providing read/write access to a directory will provide access to all files in the directory (including sub-directories).

In your case, `--allow-write=/asd` should give access to everything under the `asd` directory.

**Comment by shadowtime2000** [comment]
Yeah this should probably be closed because afaik just doing `--allow-write=/asd` works.

> should be supported to provide this capability, otherwise people will just default to allowing all read and write access and lose the minimal privilege philosophy...

I don't feel like the point of "people might get annoyed and just default to allowing all" as compromising the security philosophy because while like it would be cool for Deno to not be annoying but just because some people might just get annoyed doesn't mean that the whole security philosophy is being lost.

**Comment by caspervonb** [comment]
File system permissions are paths, meaning anything that `starts_with` that path is included.
Globs are not handled by the CLI, but your shell as they should be.

**Comment by lucidNTR** [comment]
closing, as deno works as intended. the problem was a subfolder that was created by root when deno ran as normal user...

**Comment by caspervonb** [comment]
> closing, as deno works as intended. the problem was a subfolder that was created by root when deno ran as normal user...

So mistaken permission error for sandbox error?
Related #7394 altho won't be up for discussion until 2.0 is on the table.

**Comment by dandv** [comment]
How about wildcards for allowing writing to only certain filename patterns?

    deno img-convert.ts --allow-write=/tmp,*.{jpg,png}
