### ISSUE TITLE
feat: permission prompt option to map the permission target transparently to other folder or domain

### ISSUE THREAD

**Issue by lucidNTR** [denoland/deno#10391]
The word "redirect" needs to be improved of course, but the functionality allows a lot of important use cases:

redirect would allow users to pretend to give the requested permission but use another folder or another domain/ ip address as transparent shadow resource for the script, that cannot see it is not accessing the real requested resource. this is important to develop the deno runtime into areas that currently require docker or vms.

also this feature would help extremely with testing setups and auditing script behaviour.

**Comment by shadowtime2000** [comment]
> otherwise repeated usage will lead to annoyance and users reinstall the scripts with general permissions, that weaken security

This doesn't seem like a valid reason for allowing remembering prompt answers. People getting annoyed and just giving up on security and installing scripts with general permissions does weaken their security, but the whole point of security in Deno afaik is to put the security in the hands of the human. It doesn't make that sense to me to add a feature on the basis that people might get annoyed and just give up on security.

**Comment by lucidNTR** [comment]
@shadowtime2000 i see, then i remove the remember option from this issue, its two separate features anyways...

**Comment by caspervonb** [comment]
> redirect would allow users to pretend to give the requested permission but use another folder or another domain/ ip address as transparent shadow resource for the script, that cannot see it is not accessing the real requested resource. this is important to develop the deno runtime into areas that currently require docker or vms.

So, mapping is probably the term you're looking for? Map host directory_a to virtual directory_b etc.

**Comment by lucacasonato** [comment]
What you want is a virtual remapped filesystem / network stack? That is out of scope for Deno. If you need something like this, consider a container runtime like containerd or Docker.
