### ISSUE TITLE
Prompting needs to be implicit to be secure

### ISSUE THREAD

**Issue by lucidNTR** [denoland/deno#10390]
currently, when using the --prompt flag without additional permissions on third party scripts such as examples and tutorials or other scripts, accessing forbidden features results in an error message and script termination.

i would expect to be prompted implicitly without the script having to support this behaviour. this is extremely important to prevent "node.js malware" kind of scenarios like this one:

- owner of very popular simple library gets replaced by malicious actor.
- actor adds many write / read accesses early in the script execution that look harmless and look necessary for normal operation
- users are annoyed by manually whitelisting the accesses and give general read write permission
- malicious script now can do harmful actions without users seeing or beeing prompted

the same scenario with implicit prompts, users could just grant the access in the terminal repeatedly and would then see access to a suspicious location and stop using the script

**Comment by lucacasonato** [comment]
I don't see what the problem here is. With `--prompt`, the user will be prompted for each access (unless the exact path/envvar/ipaddr was previously granted).

**Comment by lucidNTR** [comment]
@lucacasonato  the prompt behaviour changed in the meantime, maybe i was on an older version than cutting edge and i did not know about the roadmap! Basically deno know has exactly the behaviour i asked for. thanks
