### ISSUE TITLE
Deno.makeTempFile is hard to use with explicit write permissions

### ISSUE THREAD

**Issue by lucidNTR** [denoland/deno#10392]
as the path of the temp file is impossible to predict, this api is not usable with explicit write permission paths
i see not many options besides having a separate write-temp permission because users would not expect if a script was allowed to write huge temp files without any write permission and having a pseudo path for temp files seems a bit unclean and could lead to some edgecases.

**Comment by sielicki** [comment]
`makeTempFile` [should](https://doc-proxy.deno.dev/builtin/stable#L1169) obey `TMPDIR`, so presumably (?) you can do something like

`deno --allow-env=TMPDIR --allow-read="$TMPDIR" --allow-write="$TMPDIR" <...>` 

It's not ideal that this requires permissions for all of temp, but you could go a step further and do something like:

`MYDIR=$(mktemp -d) && TMPDIR=$MYDIR deno --allow-env=TMPDIR --allow-read="$MYDIR" --allow-write="$MYDIR"`

**Comment by lucidNTR** [comment]
sorry i am stupid you are right

**Comment by sielicki** [comment]
Hey, you’re not dumb! I think you brought up a very good point.

**Comment by wperron** [comment]
You can also overwrite the `TMPDIR` in the input parameters of `makeTempDir` https://doc.deno.land/builtin/stable#Deno.MakeTempOptions

**Comment by lucidNTR** [comment]
@wperron  that would not work for external libraries or tools that endusers want to install
in the genaral case @sielicki s solution seems to be the best approach:

MYDIR=$(mktemp -d) && TMPDIR=$MYDIR deno --allow-env=TMPDIR --allow-read="$MYDIR" --allow-write="$MYDIR"

**Comment by wperron** [comment]
> @wperron that would not work for external libraries or tools that endusers want to install
> in the genaral case @sielicki s solution seems to be the best approach:
> 
> MYDIR=$(mktemp -d) && TMPDIR=$MYDIR deno --allow-env=TMPDIR --allow-read="$MYDIR" --allow-write="$MYDIR"

Just pointing out the options :slightly_smiling_face:

**Comment by lucidNTR** [comment]
@wperron  i appreciate! wasn't meant to be negative :)

**Comment by gaggle** [comment]
`mktemp -d` returns a new folder every time its called, resulting in read/write permissions that do not match what the Deno process is accessing.

Also, I don't think this'll work for compiled artifacts, because the permissions are baked into the executable, right? Feels like we really use `--allow-read-tmp` or something in that direction?
