### ISSUE TITLE
Implement "HTML Sanitizer API"

### ISSUE THREAD

**Issue by nuxodin** [denoland/deno#10394]
Maybe the api is still in an early state but Firefox and Chrome are already experimenting with it.
The API would also be very useful on the server side.

Spec:
https://wicg.github.io/sanitizer-api/

Playground:
https://sanitizer-api.dev/

**Comment by wperron** [comment]
MDN docs for reference https://developer.mozilla.org/en-US/docs/Web/API/Sanitizer

**Comment by crowlKats** [comment]
This would require dom parsing, which has already been denied

**Comment by bartlomieju** [comment]
You can use https://github.com/lucacasonato/ammonia-wasm instead. Adding DOM is out of scope.
