### ISSUE TITLE
Deno.run throws on Windows

### ISSUE THREAD

**Issue by dev-nicolaos** [denoland/deno#10399]
## Environment

OS: Windows 10 Home Version 20H2

Observed in Deno v1.9.2

## Steps to reproduce

1. Given the following in a file `subprocess.js`...

```js
  // subprocess.js

  // create subprocess
  const p = Deno.run({
    cmd: ["echo", "hello"],
  });

  // await its completion
  await p.status();

```

2. Execute `deno run --allow-run subprocess.js`

## Expected behavior

Deno creates a subprocess which writes `hello` to stdout

## Observed behavior

The script errors out with the following error:

```
error: Uncaught NotFound: The system cannot find the file specified. (os error 2)
const p = Deno.run({
               ^
    at unwrapOpResult (deno:core/core.js:99:13)
    at Object.opSync (deno:core/core.js:113:12)
    at opRun (deno:runtime/js/40_process.js:20:17)
    at Object.run (deno:runtime/js/40_process.js:104:17)
    at file:///C:/Users/<username>/path-to-file/subprocess.js:4:16
```

## Notes

The example above is pulled directly from [the docs](https://deno.land/manual@v1.9.2/examples/subprocess). I ran the same steps on Ubuntu (via WSL) and got the expected behavior, so I'm inclined to think this is a Windows specific issue.

**Comment by kitsonk** [comment]
The example assumes that you have an executable named `echo` in your path.  The error indicates that this is not the case, so it is working as designed.

**Comment by dev-nicolaos** [comment]
@kitsonk thanks for the explanation. Would the team be open to a PR updating the docs to be a bit more platform agnostic? Given that Deno is a multi-platform development environment it seems a bit misleading to say something like...

> This example is the equivalent of running 'echo hello' from the command line.

...when that's just not the case on Windows. Running `echo hello` on cmd or powershell executes a shell command that does in fact write `hello` to stdout.

**Comment by kitsonk** [comment]
> Would the team be open to a PR updating the docs to be a bit more platform agnostic?

Yup. Sure.

**Comment by jsejcksn** [comment]
@dev-nicolaos I added a Windows example to make the docs platform-_inclusive_ rather than -agnostic.
