### ISSUE TITLE
Deno.test in async function 

### ISSUE THREAD

**Issue by tshelburne** [denoland/deno#10405]
### Description

Defining tests with `Deno.test` doesn't register tests under certain asynchronous circumstances. Specifically, when an async function is called and the `await` comes *before* `Deno.test` is called.

### Broken cases

- `Deno.test` called inside async function *after* `await`

```ts
async function main() {
    await Promise.resolve()
    Deno.test('testing', () => {})
}

main()

// Check file:///Users/timshelburne/$deno$test.ts
// running 0 tests
// 
// test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out (0ms)
```

### Working cases

- `Deno.test` called at root level

```ts
Deno.test('testing', () => {})

// Check file:///Users/timshelburne/$deno$test.ts
// running 1 tests
// test testing ... ok (3ms)

// test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out (3ms)
```

- `Deno.test` called at root level in async module (works both before and after `await`)

```ts
await Promise.resolve()
Deno.test('testing', () => {})

// Check file:///Users/timshelburne/$deno$test.ts
// running 1 tests
// test testing ... ok (3ms)

// test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out (3ms)
```

- `Deno.test` called inside a function

```ts
function main() {
    Deno.test('testing', () => {})
}

main()

// Check file:///Users/timshelburne/$deno$test.ts
// running 1 tests
// test testing ... ok (3ms)

// test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out (3ms)
```

- `Deno.test` called inside an async function *before* `await`

```ts
async function main() {
    Deno.test('testing', () => {})
    await Promise.resolve()
}

main()

// Check file:///Users/timshelburne/$deno$test.ts
// running 1 tests
// test testing ... ok (3ms)
//
// test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out (3ms)
```

### Expected Behavior

I would expect the behavior to be consistent - if calling `Deno.test` asynchronously is supported anywhere, I would expect it to be supported everywhere.

### Actual Behavior

Calling `Deno.test` fails to register when called after `await` in async functions.

**Comment by caspervonb** [comment]
Working as intended.
You don't await the `main` function here so the module finishes evaluating and the test runner starts running tests while your function is still processing and have yet to register any test cases.

```
async function main() {
    await Promise.resolve()
    Deno.test('testing', () => {})
}

await main();
```

**Comment by tshelburne** [comment]
Ah, derp. Great catch, thank you.

**Comment by caspervonb** [comment]
Anytime 😄
