### ISSUE TITLE
`deno coverage --unstable --lcov` causes panic in ubuntu runner in deno_std ci

### ISSUE THREAD

**Issue by kt3k** [denoland/deno#10420]
'Generate lcov' step keeps failing in deno_std ci (only on canary + ubuntu) with the following error. It seems to have started from today.

```
thread 'main' panicked at 'byte index 7461 is out of bounds of `import { Buffer } from "./buffer.ts";
import { copy } from "../bytes/mod.ts";
import { assert } from "../testing/asserts.ts";
const DEFAULT_BUFFER_SIZE = 32 * 1024;
export async function readAll(r) {
    const buf = new Buffer();
    await buf.readFrom(r);`[...]', cli/tools/coverage.rs:220:11
```

logs:
- https://github.com/denoland/deno_std/runs/2465352343
- https://github.com/denoland/deno_std/pull/887/checks?check_run_id=2464158345
- https://github.com/denoland/deno_std/runs/2464141416

**Comment by lucacasonato** [comment]
I am 90% confident this is our source mappings still being broken.

**Comment by caspervonb** [comment]
Can't reproduce on my ubuntu server.

**Comment by caspervonb** [comment]
Also unable to reproduce on macOS.

**Comment by bartlomieju** [comment]
@kt3k is this issue still relevant?

**Comment by kt3k** [comment]
Tried on deno_std again, and it didn't reproduce now. (ref: https://github.com/denoland/deno_std/pull/984/checks?check_run_id=2923771234) (Did anyone do anything about this? 🤔 )

Let's close for now.

**Comment by kt3k** [comment]
https://github.com/denoland/deno_std/pull/1050/checks?check_run_id=3125140402
Happened again on std ubuntu runner. (no problem with windows and mac runners).

This happens while processing `io/util.ts` in std.
