### ISSUE TITLE
How to properly set globals

### ISSUE THREAD

**Issue by einicher** [denoland/deno#10425]
I need to set global variables depending on the environment and device. That seems trivial, but turns out, it is not.

From what I understand so far, this can be achieved by setting properties to the window object. But I need those variables already set in imported modules, but anything i do before the import statements, gets executed after the import.  Also it does not help to set those variables inside an own module, because again I need to set some values before so i can determine inside that module, what values to use. Also it seems, import files get executed in reverse order. So first file i import get executed last. Is this expected behavior? I also tried conditional dynamic imports, running into the same problem: they get executed after the whole import chain has finished.

Simple example: `window.IS_SERVER = true`, `window.IS_BROWSER = false`, `window.IS_APP = true`,

In node i just set those on the first lines of the script before I start requireing. Within most of the imports i then use those values for conditions. on server getFile does a `Deno.readFile` in the browser a websocket request in the app a cordova.getFile.

After playing around the whole day, I am now a little confused about this, especially about how the imports seem to be a separate execution loop in reverse order or something like that.

**Comment by AaronO** [comment]
@einicher You can detect if you're in `deno` or server side by checking:
```
const isServer = typeof Deno !== "undefined";
```

**Comment by einicher** [comment]
Thx @AaronO  with your inputs I created a new module for the globals:

```
console.log('GLOBALS EXECUTE START');

export const globals = {};
if (typeof Deno !== "undefined") {
	globals.isServer = true;
	globals.isBrowser = false;
	globals.isApp = false;
} else if (typeof cordova !== 'undefined') {
	globals.isServer = false;
	globals.isBrowser = false;
	globals.isApp = true;
} else {
	globals.isServer = false;
	globals.isBrowser = true;
	globals.isApp = false;
}

export default function global(property) {
	if (typeof property == 'undefined') {
		return globals;
	} else if (typeof globals[property] == 'undefined') {
		// handle error?
	} else {
		return globals[property];
	}
}

console.log('GLOBALS EXECUTE READY');
```

i can now do `import { globals } from '../hybrid/globals.js';` or `import global from '../hybrid/globals.js';`

while doing that i forgot a `window.jQuery = cheerio;` somewhere else in that file, and suddenly all failing `jQuery` variables worked serverside. So, the solution to my problem actualy is very trivial: You just have to set the window globals inside the first module you import, then all submodules and module imported afterwards have that global. You just have to get into the import loop at first.
