### ISSUE TITLE
Native HTTP listener with TLS crashed by HTTP request

### ISSUE THREAD

**Issue by linux-china** [denoland/deno#10433]
I follow the manual and create a server, and I use mkcert https://github.com/FiloSottile/mkcert to create certFile and keyFile. 

```typescript
const listener = Deno.listenTls({
    port: 1443,
    certFile: "./localhost.pem",
    keyFile: "./localhost-key.pem",
    alpnProtocols: ["h2", "http/1.1"],
});

for await (const conn of listener) {
    handleConn(conn);
}

async function handleConn(conn: Deno.Conn) {
    const httpConn = Deno.serveHttp(conn);
    for await (const {request, respondWith} of httpConn) {
        const body = new TextEncoder().encode("Hello World");
        respondWith(new Response(body));
    }
}
```

I  use `curl -X GET --location "https://localhost:1443" --resolve 'localhost:1443:127.0.0.1' ` to test the https server, all good.

Then I switch to http schema to visit the service:  `curl -X GET --location "http://localhost:1443" --resolve 'localhost:1443:127.0.0.1'`

and the https server crashed with following output: 

```
error: Uncaught (in promise) InvalidData: received corrupt message
for await (const conn of listener) {
                 ^
    at unwrapOpResult (deno:core/core.js:100:13)
    at async TLSListener.accept (deno:runtime/js/40_tls.js:43:19)
    at async TLSListener.next (deno:runtime/js/30_net.js:105:16)
    at async file:///Users/xxxx/deno-demo/server/native-http2-server.ts:8:18
```

**Comment by kitsonk** [comment]
You can't assume that every connection will not be without an error.  In this case, you were connecting via HTTP to a HTTPS socket, which causes an error in the connection.  It maybe meaningful to you, as the application developer, to know that there was an invalid connection to your server, so the error is raised.  You need to trap it and handle it in a meaningful way.

**Comment by linux-china** [comment]
@kitsonk  Thanks for explain.  Adjust `for await...of` to `while(true)` block and fixed. 

```typescript
while (true) {
    try {
        let conn = await listener.accept();
        handleConn(conn);
    } catch (err) {
       console.log(err);
    }
}
```
