### ISSUE TITLE
lsp: auto-completion for registries should prefer mod.ts

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#10441]
The lsp should prefer a `/mod.ts` over other imports when providing registry completions.

**Comment by kitsonk** [comment]
Related: #10440

**Comment by lucacasonato** [comment]
I think this should be done by registry providers. They can determine sort order right?

**Comment by kitsonk** [comment]
I have no problem leaving it up to the registries.

> They can determine sort order right?

It is open to interpretation, we are setting a key that ensures that they get displayed in the order received, which is "convention" versus "specification".  There is also the `preferred` flag in the response (only one can be marked `preferred`).  So it would be best when we do v2 of the specification (including the incremental/partial lists) to provide explicit sort text and an explicit preferred flag.

**Comment by kitsonk** [comment]
We will leave as part of #10051.
