### ISSUE TITLE
Behaviour of --reload

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#1044]
Currently, the `--reload` flag does not invalidate the transpiled versions of any local modules.  It only causes cached versions of non-local modules to be invalidated, which of course in turn invalidates their local transpiled versions.

While it might be unlikely, there is still a valid scenario where a user will make a change in another module that impacts the types that are available to a local module that is already transpiled, but is not caught by the compiler because it skips transpilation.

It feels to me it is less surprising that `--reload` would also invalidate any local modules that are transpiled, irrespective of if their source has changed.

**Comment by bartlomieju** [comment]
@kitsonk is this issue still relevant?

**Comment by kitsonk** [comment]
I believe it is.

**Comment by ry** [comment]
We should just combine --reload and --recompile ... it's more browser-like and simpler.

**Comment by kitsonk** [comment]
That would work for me...  Related to #1582
