### ISSUE TITLE
Deno.exit() call in microtask cancels uncaught error

### ISSUE THREAD

**Issue by kt3k** [denoland/deno#10445]
The following script prints 1 and 3, and exits without an error. It seems the uncaught error is canceled by Deno.exit() call in microtask.

```ts
Promise.resolve().then(() => {
  console.log(3);
  Deno.exit(0);
});
console.log(1);
throw new Error('abc');
console.log(2);
```

(might be related to https://github.com/denoland/deno/issues/4350#issuecomment-751328599 ?)

**Comment by bnoordhuis** [comment]
The expected behavior is that deno prints the exception and exits? Like this:
```
1
error: Uncaught Error: abc
throw new Error('abc');
      ^
    at file:///home/bnoordhuis/src/deno/tmp/bug10445.js:6:7
```
That might be very hard to fix.

The exception causes an exit from the VM. Pending promises run on VM exit.

V8 has a "don't run promises automatically" mode but that won't work here. The main module is a promise too, because of TLA.

**Comment by kt3k** [comment]
> The expected behavior is that deno prints the exception and exits?

Yes.

I think this behavior is bad because this can introduce a bug which is very hard to figure out like #10453. This behavior also feels breaking our promise "Deno always dies on uncaught errors." (ref: https://deno.land/manual/introduction#comparison-to-nodejs )

**Comment by caspervonb** [comment]
> I think this behavior is bad because this can introduce a bug which is very hard to figure out like #10453. 

It's correct, as a mapping to the syscall that's what I'd expect at-least.
But I've been wanting to make close more forgiving than what the exit syscall is by call shutdown on the tokio runtime instead allowing it to spin a few ticks before shutting down.

**Comment by vwkd** [comment]
If I run this in the browser, it seems like the handler runs before the error. Don't know if it's just a quirk in the console output of Dev Tools.

```javascript
Promise.resolve().then(() => {
  console.log(3);
});
console.log(1);
throw new Error('abc');
console.log(2);

// 1
// 3
// Uncaught Error: abc
```

**Comment by lucacasonato** [comment]
TBH, I would say this is working as intended and is just a race in user code. `Deno.exit` is a synchronous API that terminates the process immediately. I don't think we should work through the microtask queue before exiting.
