### ISSUE TITLE
bug: bundler panics

### ISSUE THREAD

**Issue by DjDeveloperr** [denoland/deno#10457]
When I tried to bundle using `deno bundle`, it panics like this:

![img](https://cdn.discordapp.com/attachments/688040863313428503/838003665960173588/unknown.png)

Stack trace is empty on enabling, when I use `full` value, it has only some `unknown` values which are not useful.

I don't know of any minimal way to reproduce this. 

Deno v1.9.2

**Comment by kitsonk** [comment]
cc/ @kdy1

**Comment by kdy1** [comment]
Fixed on the upstream.
