### ISSUE TITLE
lsp: panic with multi-cursor editing within import urls

### ISSUE THREAD

**Issue by danopia** [denoland/deno#10468]
repro on deno 1.9.2:

```typescript
import {  } from "https://deno.land//sources/from-timer.ts";
import {  } from "https://deno.land//sources/just.ts";
```

Put your cursor where the `x` is supposed to be, and multi-cursor down:

![Screenshot 2021-05-02 12 19 58](https://user-images.githubusercontent.com/40628/116809868-bd78cf80-ab40-11eb-8459-3c8523cb1862.png)

Typing the 'x' here panics the LSP:

```
thread 'main' panicked at 'range end index 4 out of range for slice of length 3', cli/lsp/registries.rs:446:55
```

source line: https://github.com/denoland/deno/blob/v1.9.2/cli/lsp/registries.rs#L446

This happens every time for me.

```
deno 1.9.2 (release, x86_64-unknown-linux-gnu)
v8 9.1.269.5
typescript 4.2.2
```

**Comment by kitsonk** [comment]
I think there are some assumptions about these being only single lines and so I think we need to ignore the requests that span more than one line.

**Comment by kitsonk** [comment]
Hmmm... I am trying it on main and I can't reproduce, no panics:

https://user-images.githubusercontent.com/1282577/117768207-662bdb00-b275-11eb-8ad8-6ed9125d0e02.mp4

**Comment by kitsonk** [comment]
This wasn't multi-cursor editing, it had to do with a logic error when auto completing with a registry and "backspacing".  Basically we guessed there were more tokens than there were to parse for auto-completion.
