### ISSUE TITLE
Attempting other extensions

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#1046]
Currently, Deno attempts to fetch remote modules, modifying the extension, irrespective of the error coming back.

It would make more sense to attempt different extensions only if a `404 Not Found` is returned from the remote location.  For example, if the remote server is down, you will get something like this:

```
Downloading http://localhost:4545/tests/subdir/mod1.ts
Downloading http://localhost:4545/tests/subdir/mod1.ts.ts
Downloading http://localhost:4545/tests/subdir/mod1.ts.js
HttpOther: an error occurred trying to connect: Connection refused (os error 61)
    at maybeError (deno/js/errors.ts:38:12)
    at maybeThrowError (deno/js/errors.ts:26:15)
    at sendSync (deno/js/dispatch.ts:70:5)
    at Object.codeFetch (deno/js/os.ts:40:19)
    at DenoCompiler.resolveModule (deno/js/compiler.ts:511:38)
```

The additional requests seem a bit odd at this point, let alone it delays the failure.

**Comment by ry** [comment]
@rsp Yes - you can do that. We added this because TS flags this imports with an extension error - particularly in IDEs. It also help integrating with existing code. I hope we can move away from it over time - but it was a philosophical vs practically trade off.

**Comment by bartlomieju** [comment]
As of v0.2.4 Deno requires imports with extensions, I guess we can close this one?
