### ISSUE TITLE
Response.clone failed with Body already consumed

### ISSUE THREAD

**Issue by scandinave** [denoland/deno#10479]
Hi,

I try to make a get request with the axiod lib. The response return a content-type document. Inside the lib, there is the following code: 
```typescript
return fetch(url, fetchRequestObject).then(async (x) => {
  const contentType = x.headers.get("content-type") || "";
  if (contentType.toLowerCase().indexOf("json") === -1) {
      // Try to convert to json
      try {
        _data = await x.clone().json();
      } catch (ex) {
        _data = await x.clone().text();
      }
    } else {
      _data = await x.clone().json();
    }
});
```

It's seems that the clone method does not work as expected ? Or the code is faulty and need to be refactor?

[Edit]

The request i try to make is the following 

`axiod.get('http://localhost:8081/service/rest/v1/status/writable'); `

where localhost:8081 is a url of a Nexus 3  repository. 

The error that is raised, is `Body already consumed` in the line `_data = await x.clone().text();`. 
```bash
error: Uncaught (in promise) TypeError: Body already consumed.
        _data = await x.text();
                        ^
    at InnerBody.consume (deno:op_crates/fetch/22_body.js:84:34)
    at consumeBody (deno:op_crates/fetch/22_body.js:131:35)
    at Response.text (deno:op_crates/fetch/22_body.js:199:30)
    at https://deno.land/x/axiod/mod.ts:192:25
```

As i undestand it, the response is read first in the `try` but as the Response is not a JSON document, it fall into the catch and try to read another time the response.

I think the clone() method should handle this and this is clearly what it's expected by the axiod author.

Thx

**Comment by kitsonk** [comment]
Can you provide the full error, the version of Deno you are using.

What was the response from axiod when you raised the issue with them?

**Comment by lucacasonato** [comment]
This should be reducible to a smaller reproduction. I'll take a look.

**Comment by scandinave** [comment]
I have update my issue

**Comment by lucacasonato** [comment]
The code you are running does not include the `.clone()` call. See the stacktrace. It says:

```
error: Uncaught (in promise) TypeError: Body already consumed.
        _data = await x.text();
                        ^
```

No `.clone()` call there.

Mimimal reproduction is working fine:

```js
> let r = new Response(new ReadableStream({async start(c) { await c.enqueue(new Uint8Array()); c.close() } }), {})
undefined
> await r.clone().text()
""
> await r.clone().text()
""
> await r.clone().text()
""
> await r.text()
""
> await r.text()
Uncaught TypeError: Body already consumed.
    at InnerBody.consume (deno:op_crates/fetch/22_body.js:84:34)
    at consumeBody (deno:op_crates/fetch/22_body.js:131:35)
    at Response.text (deno:op_crates/fetch/22_body.js:199:30)
    at <anonymous>:2:9
```

**Comment by scandinave** [comment]
Very Strange. If you go on the source of the axiod  where the error is raised, it's clearly written   `_data = await x.clone().text();`
Do you thinks it's a problem with the axiod lib?

**Comment by scandinave** [comment]
Argg. This is the cause. Sorry to have taken your time. Really Thx.I'm closing the issue.
