### ISSUE TITLE
lsp: provides diagnostics for `.mjs` file as typescript file

### ISSUE THREAD

**Issue by hsl0** [denoland/deno#10475]
**Describe the bug**
Deno linter shows typescript errors in javascript file with ```.mjs``` extension. Deno linter seems to treat ```.mjs``` files as typescript files.

**To Reproduce**

1. Create a folder. ex) ```wd```
2. Open the created folder with VSCode.
3. Enable Deno Language Server (```deno.enable```) for workspace in VSCode settings.
4. Create a file with ```.mjs``` extension in the created folder. ex) ```ex.mjs```
5. Write some javascript code in the created file. I wrote the code below to reproduce it.
```javascript
function test(a, b) {
    return a + b;
}
```
6. You can see typescript errors in mjs files issued by `deno-ts`. For the code above, the errors are like below.
- Parameter 'a' implicitly has an 'any' type.
- Parameter 'b' implicitly has an 'any' type.
7. If you change the `.mjs` file into ```.js``` extension and restart VScode, the errors would be disappeared.

**Expected behavior**
Deno linter doesn't show typescript errors in ```.mjs``` file.

**Screenshots**
![image](https://user-images.githubusercontent.com/46296273/116817786-111c0500-aba3-11eb-9add-5e6a96575885.png)

**Versions**

vscode: 1.55.2 (user setup)
deno: 1.9.2 (release, x86_64-pc-windows-msvc)
extension: 3.3.0

**Folder and files used for reproducing**: [wd.zip](https://github.com/denoland/vscode_deno/files/6411637/wd.zip)

**Comment by sno2** [comment]
Also happening for `.cjs` files.  Related to #6176
![image](https://user-images.githubusercontent.com/43641633/116833413-9fca5b00-ab7e-11eb-9039-c22e69661693.png)

**Comment by kitsonk** [comment]
Yeah, it is likely the same root cause, also thanks for pointing out it is the "linter", it is the diagnostics coming from tsc.

**Comment by kitsonk** [comment]
I took a look at this and it isn't very straight forward of a fix, as TypeScript really really doesn't like `.mjs`.  Going to revisit at some point in the future.

**Comment by pleshevskiy** [comment]
Same here. I added `// @ts-nocheck` at the top of the file that disable tsc, but we cannot disable `// deno-lint-ignore-file` in `.mjs` files.

**Comment by nayeemrmn** [comment]
This is fixed. I think TypeScript has improved support for `.mjs` etc. now, and even has `.mts`.
