### ISSUE TITLE
Error sending datagram to broadcast IP (permission denied)

### ISSUE THREAD

**Issue by austincummings** [denoland/deno#10470]
Getting an error when trying to use `DatagramConn` to send to the network's broadcast address.

```ts
const msg = new TextEncoder().encode("Hello world\n");

const conn = Deno.listenDatagram({
  hostname: "0.0.0.0",
  port: 8002,
  transport: "udp",
});

await conn.send(msg, {
  hostname: "192.168.1.255",
  port: 8001,
  transport: "udp",
});
```

Running the above with:
```sh
deno run --allow-net --unstable test.ts
```
Output:
```
error: Uncaught (in promise) PermissionDenied: Permission denied (os error 13)
await conn.send(msg, {
^
    at unwrapOpResult (deno:core/core.js:102:13)
    at async file:///home/pi/test.ts:9:1
```

**Comment by lucacasonato** [comment]
Your OS is not permitting your user to send a UDP message to that hostname + port combo. This is not a Deno permission error, but an OS error.

**Comment by lucacasonato** [comment]
Try running with a different user account or different permissions. What OS are you on?

**Comment by austincummings** [comment]
I think the issue is possibly that Deno isn't ever setting the SO_BROADCAST option on the socket. I was able to duplicate the issue in Python with the following:

```python
from socket import *
cs = socket(AF_INET, SOCK_DGRAM)
cs.setsockopt(SOL_SOCKET, SO_REUSEADDR, 1)
#cs.setsockopt(SOL_SOCKET, SO_BROADCAST, 1)
cs.sendto('This is a test', ('192.168.1.255', 8001))
```

Notice I've commented out the 4th line, with this code as is I get:
```
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    cs.sendto('This is a test', ('192.168.1.255', 8001))
socket.error: [Errno 13] Permission denied
```

Looks very similar to the error I'm getting with Deno, but when that line is uncommented and SO_BROADCAST is set there is no error and it appears to work.

**Comment by lucacasonato** [comment]
Do you have a minimally reproducible example with a public IP?

**Comment by austincummings** [comment]
I'm not sure of a public broadcast IP that I could use? Maybe I just don't understand well enough how UDP should work. The permission denied error occurs in both the Python and Deno examples when using `255.255.255.255` as the send address though if that helps.

I've tried both the Python and Deno examples on two different computers and getting the same results, even when run with sudo. One in WSLv2 with Ubuntu, and another running on a raspberry pi with a beta version of the Raspberry Pi OS 64bit. The raspberry pi is also using an unofficial build of Deno, but since I'm able to reproduce it in WSL I don't think it's an issue with that unofficial build.

**Comment by austincummings** [comment]
Also, just tried the Deno code on Windows with Deno v1.9.2 and it seemed to work fine.

**Comment by bnoordhuis** [comment]
@lucacasonato Thoughts on setting the broadcast flag unconditionally? I suspect that right now we have a situation where it works on some platforms but not others.

```diff
diff --git a/runtime/ops/net.rs b/runtime/ops/net.rs
index ee762ed47..3efc145de 100644
--- a/runtime/ops/net.rs
+++ b/runtime/ops/net.rs
@@ -433,6 +433,7 @@ fn listen_udp(
 ) -> Result<(u32, SocketAddr), AnyError> {
   let std_socket = std::net::UdpSocket::bind(&addr)?;
   std_socket.set_nonblocking(true)?;
+  std_socket.set_broadcast(true)?;
   let socket = UdpSocket::from_std(std_socket)?;
   let local_addr = socket.local_addr()?;
   let socket_resource = UdpSocketResource {
```diff

**Comment by lucacasonato** [comment]
@bnoordhuis SGTM, but don't have much experience with UDP.

**Comment by luvies** [comment]
Wouldn't it make sense to add a field to the `listenDatagram` options object to enable or disable broadcasting? Something like:

```ts
export function listenDatagram(
  options: ListenOptions & { transport: "udp", broadcast?: boolean },
): DatagramConn;
```

The Python API seems to only enable broadcasting if explicitly enabled, it feels reasonable to follow the precedent on that.

**Comment by austincummings** [comment]
Another option would be to mimic the node.js API with a `setBroadcast` method.

https://nodejs.org/dist/latest-v16.x/docs/api/dgram.html#dgram_socket_setbroadcast_flag
