### ISSUE TITLE
lsp: diagnostic on module with no imports or exports

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#10484]
Something like "warning, this file doesn't contain any imports/exports and is therefore falsely considered global"

_Originally posted by @KotlinIsland in https://github.com/denoland/vscode_deno/issues/405#issuecomment-831565987_

---

TypeScript has a design limitation where scripts are considered global scripts when they lack any import or export statements.  While this does not cause any issues with the CLI, it does mean these symbols "leak" into the global context when using the LSP.  We could provide a diagnostic that indicates this, with a quick fix which would be to append `export {}` to the file.

**Comment by DetachHead** [comment]
the `isolatedModules` compiler option should cover this, but it doesn't seem to be supported anymore? #7326

**Comment by KotlinIsland** [comment]
Does Deno support scripts at all? If not you could just secretly inject `export {}` so the LSP thinks it's a module

**Comment by kitsonk** [comment]
We should avoid "magically" augmenting the source code.

As stated, we should provide a quick fix that allows the author to fix it themselves.

**Comment by DetachHead** [comment]
imo it's also bad to "magically" half-enable a compiler flag. if there's a reason that `isolatedModules` works differently in deno can [the documentation](https://deno.land/manual/typescript/faqs#why-are-you-forcing-me-to-use-isolated-modules-why-can#39t-i-use-const-enums-with-deno-why-do-i-need-to-do-export-type) be updated to explain it?

**Comment by KotlinIsland** [comment]
Wouldn't adding a diagnostic like this just be the same as not disabling the error message in the first place?

"'input.ts' cannot be compiled under '--isolatedModules' because it is considered a global script file. Add an import, export, or an empty 'export {}' statement to make it a module."

**Comment by kitsonk** [comment]
We disable error messages equally at the moment across the language server and when checking on the CLI. The diagnostic is meaningless on the CLI, the reason why it is disabled, and misleading from the language server as it would complain about the file being a script which doesn't work with isolated modules, something the user has no control over.

So to implement the feature we would have to determine which context we are in, suppress it in one and rewrite it in another as well as inject a code action.

**Comment by KotlinIsland** [comment]
Get typescript to add a "scripts-are-modules" mode that all it does it injects a `export {}`. Then use that.

**Comment by kitsonk** [comment]
The whole TypeScript issue is covered at microsoft/TypeScript#18232, including your suggestion, so it isn't like it hasn't been discussed before.  We also have #9593 that covers the topic as well.

**Comment by kitsonk** [comment]
This should no longer be an issue, as we force module consideration on TypeScript.

**Comment by KotlinIsland** [comment]
@kitsonk Awesome news! I'm interested in this could you link to some more info please?
