### ISSUE TITLE
deno install with an import map from a URL

### ISSUE THREAD

**Issue by oscarotero** [denoland/deno#10482]
```
deno run --import-map=https://example.com/import_map.json https://example.com/cli.ts
```
This works fine, it allows to load a remote import map file using a url (#9510).

But this same code does not work to install the script with 
```
deno install --import-map=https://example.com/import_map.json https://example.com/cli.ts
```
It seems like only local files are supported on install. I'm getting the error `error: No such file or directory (os error 2)`

Is this intentional or it's a bug? The ability to load remote import maps would be very useful to manage the versions of the dependencies of an script.

**Comment by bartlomieju** [comment]
Related to #10476

**Comment by satyarohith** [comment]
Working on it.
