### ISSUE TITLE
Dynamic import of local script from external script

### ISSUE THREAD

**Issue by einicher** [denoland/deno#10489]
In my local project i have controllers in local folders. The framework gets loaded through web. Inside the framework, the router - coming from the external source - loads controllers by dynamic import.

Problem: although i load a root file path like `/var/www/deno/projectxy/component/users/controllers/login.js` the dynamic import tries to load from the external web source: `https://myframework.com/var/www/deno/projectxy/component/users/controllers/login.js`.

Intresting in this case: it loads my root path from the domain root, although the script is in a path like `https://myframework.com/code/0.0.1/hybrid/router.js`.

How do I do this properly with deno?

**Comment by bartlomieju** [comment]
Try adding `file://` before the specifier when importing: `import("file:///var/www/deno/projectxy/component/users/controllers/login.js")`

**Comment by einicher** [comment]
Yep, that worked.
Thank you!
