### ISSUE TITLE
Bundler does not put parentheses around logical OR operator when extending optional class

### ISSUE THREAD

**Issue by wrnrlr** [denoland/deno#10487]
For example:

This:

    var generator = class MultiVector extends (options.baseType||Float32Array) {

turns into this:

    var generator = class MultiVector extends options1.baseType || Float32Array {

Spotted in the wild:
https://github.com/enkimute/ganja.js/blob/master/ganja.js#L146

**Comment by wrnrlr** [comment]
Not going to create new ticket for it, but similar problems occurs when the unary operator (-) is used before an exponentiation the parentheses are removed:

https://github.com/enkimute/ganja.js/blob/master/ganja.js#L617

**Comment by kitsonk** [comment]
cc/ @kdy1

**Comment by kdy1** [comment]
Fixed on upstream. `cargo update -p swc_ecma_transforms_base`will fix the issue.
