### ISSUE TITLE
Lifecycle callbacks in Deno.test

### ISSUE THREAD

**Issue by tshelburne** [denoland/deno#10486]
I'd like to suggest adding lifecycle hooks to the `Deno.test` optional arguments - at the very least, `onTestComplete` or something to that effect. The intention is to be able to orchestrate hooks to happen before / after tests execute (in this case, to support a mocha-like interface while still using `Deno.test` behind the curtain).

```ts
// this, which does not work as "expected"

console.log('before the test')
Deno.test('testing', () => {
    console.log('in the test')
})
console.log('after the test')

// could be replaced by

console.log('before the test')
Deno.test({
  name: 'running the test',
  fn() {
    console.log('in the test')
  },
  onTestComplete() {
    console.log('after the test')
  }
})
```

I read through some of the source and recognize `Deno.test` is basically a registration rather than execution mechanism, so lifecycle hooks seemed like the simplest addition. The arguments to each callback could probably just be the test definition bound to `this` along with whatever makes sense contextually for the particular hook (eg. the complete hook might receive `Either<ReturnValue, Error>`).

**Comment by nayeemrmn** [comment]
Hooks are usually discussed with regards to something like `afterAllTests`, but `TestDefinition::onTestComplete` seems replaceable by the end of the test function.

**Comment by caspervonb** [comment]
No gains of adding this to the test harness imho because you can just do.

```
async fn withHooks(hooks, fn) {
  return function() {
    if (hooks.before) {
      await hooks.before();
    }

    await fn();

    if (hooks.after) {
      await hooks.after();
    }
  }
}

Deno.test("thingymajig", withHooks({
  before: function() {
    console.log("before"),
  },
  after: function() {
    console.log("after"),
  },
}, function() {
  console.log("during");
}));

**Comment by tshelburne** [comment]
Yea, I'm working on something similar now. The bigger struggle is about orchestration between tests, but I'm trying to defer to promise to achieve the same results. I'm happy to close this and reopen if for some reason it seems necessary.
