### ISSUE TITLE
How to use typescript compiler api in deno ?

### ISSUE THREAD

**Issue by redradist** [denoland/deno#10490]
I have written [_SafeScript_](https://github.com/redradist/SafeScript) ("safe" subset of _JavaScript_ and _TypeScript_) using _TypeScript_ Compiler and I want to run it in deno runtime

Use-case could be the following:
```console
deno install https://<safescript>.ts
sscript <app>.[js|ts]
```

But unfortunately I've not found how to use _TypeScript_ Compiler API in _deno_ runtime ...
Is there a way to accomplish it ?
Do you plan to add such support ?

**Comment by ry** [comment]
`Deno.emit()` is our interface to TSC. See https://deno.land/manual@v1.9.2/typescript/runtime

**Comment by redradist** [comment]
@ry Thanks a lot !!

... But after analyzing this api it seems like _deno_ provides way to compiler ts file. but not to use ts api for custom compiler ...
_SafeScript_ itself compiler based on _TypeScript_ compiler and its intent to make code safe by removing implicit type coercion and instead throwing exception if conversion is not obvious.
It means that I cannot use just your api for compiling, because there are missed checks that I insert in emitted code, I need typescript compiler api to be able to run SafeScript compiler

**Comment by bartlomieju** [comment]
@redradist we do not provide full access to TS compiler. In your case you'll have to import `typescript.js` and implement `CompilerHost` yourself.

**Comment by redradist** [comment]
> 
> 
> @redradist we do not provide full access to TS compiler as Deno has a custom compiler host.
> 
> In your case you'll have to import `typescript.js` and implement `CompilerHost` yourself.

@bartlomieju Unfortunately, typescript.js is not importable ... (

**Comment by bartlomieju** [comment]
> > @redradist we do not provide full access to TS compiler as Deno has a custom compiler host.
> > In your case you'll have to import `typescript.js` and implement `CompilerHost` yourself.
> 
> @bartlomieju Unfortunately, typescript.js is not importable ... (

Why not? We do that internally and it works just fine

**Comment by redradist** [comment]
> 
> 
> > > @redradist we do not provide full access to TS compiler as Deno has a custom compiler host.
> > > In your case you'll have to import `typescript.js` and implement `CompilerHost` yourself.
> > 
> > 
> > @bartlomieju Unfortunately, typescript.js is not importable ... (
> 
> Why not? We do that internally and it works just fine

@bartlomieju Can you provide an example ?

**Comment by kitsonk** [comment]
It would be good if you sought community support for specific use cases.

**Comment by harrysolovay** [comment]
@bartlomieju I've attempted your suggestion to no avail. Getting it working is non-obvious. Is there any chance you could please point to an example of a Deno application successfully utilizing the TypeScript Compiler API?
