### ISSUE TITLE
"compile_windows_ext" test is flaky in main

### ISSUE THREAD

**Issue by kt3k** [denoland/deno#10502]
We enabled it again in https://github.com/denoland/deno/pull/10131 and it's been failing 22% (4 in 18) so far.

**Comment by piscisaureus** [comment]
Any idea what the error is? I can't reproduce locally.

**Comment by piscisaureus** [comment]
My poorly educated guess would be that a race condition or lock conflict happens when two tests attempt to download `deno-x86_64-unknown-linux-gnu.zip` at the same time.

**Comment by kt3k** [comment]
https://github.com/denoland/deno/runs/2514758571
<img width="960" alt="スクリーンショット 2021-05-06 13 56 13" src="https://user-images.githubusercontent.com/613956/117243789-d6e88700-ae72-11eb-87cb-920bdf6787ed.png">

seems like a race condition with the next CI job?
