### ISSUE TITLE
`op_http_request_next` is not completed when the underlying listener is closed.

### ISSUE THREAD

**Issue by kt3k** [denoland/deno#10508]
When running the following script:

```js
async function serve(l) {
  for await (const conn of l) {
    (async () => {
      for await (const { respondWith } of Deno.serveHttp(conn)) {
        respondWith(new Response("hello"));
      }
    })();
  }
}
const l = Deno.listen({ port: 4500 });
serve(l);
await new Promise((resolve) => setTimeout(resolve, 300));
const res = await fetch("http://localhost:4500/");
const text = await res.text();
l.close();
await new Promise((resolve) => setTimeout(resolve, 300));
console.log(Deno.metrics());
```

`op_http_request_next` metrics shows like the below:

```jsonc
    op_http_request_next: {
      opsDispatched: 2,
      opsDispatchedSync: 0,
      opsDispatchedAsync: 2,
      opsDispatchedAsyncUnref: 0,
      opsCompleted: 1,
      opsCompletedSync: 0,
      opsCompletedAsync: 1,
      opsCompletedAsyncUnref: 0,
      bytesSentControl: 0,
      bytesSentData: 0,
      bytesReceived: 0
    },
```

So the second `op_http_request_next` call is never finished, and this program can't finish gracefully.

Is there any way to finish this second `op_http_request_next` call?

**Comment by kt3k** [comment]
Another finding is that even when I closed HttpConn explicitly, the last `op_http_request_next` call never finishes.

```js
const delay = (n) => new Promise((resolve) => setTimeout(resolve, n));
const httpConnList = []
async function serve(l) {
  for await (const conn of l) {
    (async () => {
      const c = Deno.serveHttp(conn);
      httpConnList.push(c);
      for await (const { respondWith } of c) {
        respondWith(new Response("hello"));
      }
    })();
  }
}
const l = Deno.listen({ port: 4500 });
serve(l);
await delay(300);
let res = await fetch("http://localhost:4500/");
let text = await res.text();
httpConnList.forEach((conn) => conn.close());
l.close();
await delay(300);
console.log(Deno.metrics().ops.op_http_request_next);
```

This shows
```
{
  opsDispatched: 2,
  opsDispatchedSync: 0,
  opsDispatchedAsync: 2,
  opsDispatchedAsyncUnref: 0,
  opsCompleted: 1,
  opsCompletedSync: 0,
  opsCompletedAsync: 1,
  opsCompletedAsyncUnref: 0,
  bytesSentControl: 0,
  bytesSentData: 0,
  bytesReceived: 0
}
```

I think `opsCompleted` and `opsCompletedAsync` should be 2 here.

This isn't such a issue in actual use cases, but when I use this loop in the test case, the case is reported as FAIL because of the resource leakage.

**Comment by satyarohith** [comment]
This is stopping me from doing some test refactors in Sift because of the leaks. I will take a look.

**Comment by lucacasonato** [comment]
This suggests we need to add a cancel handle to `ConnResource`, and close it on resource close (or wherever else it may be closed).

**Comment by bartlomieju** [comment]
> Another finding is that even when I closed HttpConn explicitly, the last `op_http_request_next` call never finishes.
> 
> ```js
> const delay = (n) => new Promise((resolve) => setTimeout(resolve, n));
> const httpConnList = []
> async function serve(l) {
>   for await (const conn of l) {
>     (async () => {
>       const c = Deno.serveHttp(conn);
>       httpConnList.push(c);
>       for await (const { respondWith } of c) {
>         respondWith(new Response("hello"));
>       }
>     })();
>   }
> }
> const l = Deno.listen({ port: 4500 });
> serve(l);
> await delay(300);
> let res = await fetch("http://localhost:4500/");
> let text = await res.text();
> httpConnList.forEach((conn) => conn.close());
> l.close();
> await delay(300);
> console.log(Deno.metrics().ops.op_http_request_next);
> ```
> 
> This shows
> 
> ```
> {
>   opsDispatched: 2,
>   opsDispatchedSync: 0,
>   opsDispatchedAsync: 2,
>   opsDispatchedAsyncUnref: 0,
>   opsCompleted: 1,
>   opsCompletedSync: 0,
>   opsCompletedAsync: 1,
>   opsCompletedAsyncUnref: 0,
>   bytesSentControl: 0,
>   bytesSentData: 0,
>   bytesReceived: 0
> }
> ```
> 
> I think `opsCompleted` and `opsCompletedAsync` should be 2 here.
> 
> This isn't such a issue in actual use cases, but when I use this loop in the test case, the case is reported as FAIL because of the resource leakage.

Fixed in https://github.com/denoland/deno/pull/10836, thanks for the test case.



> When running the following script:
> 
> ```js
> async function serve(l) {
>   for await (const conn of l) {
>     (async () => {
>       for await (const { respondWith } of Deno.serveHttp(conn)) {
>         respondWith(new Response("hello"));
>       }
>     })();
>   }
> }
> const l = Deno.listen({ port: 4500 });
> serve(l);
> await new Promise((resolve) => setTimeout(resolve, 300));
> const res = await fetch("http://localhost:4500/");
> const text = await res.text();
> l.close();
> await new Promise((resolve) => setTimeout(resolve, 300));
> console.log(Deno.metrics());
> ```
> 
> `op_http_request_next` metrics shows like the below:
> 
> ```js
>     op_http_request_next: {
>       opsDispatched: 2,
>       opsDispatchedSync: 0,
>       opsDispatchedAsync: 2,
>       opsDispatchedAsyncUnref: 0,
>       opsCompleted: 1,
>       opsCompletedSync: 0,
>       opsCompletedAsync: 1,
>       opsCompletedAsyncUnref: 0,
>       bytesSentControl: 0,
>       bytesSentData: 0,
>       bytesReceived: 0
>     },
> ```
> 
> So the second `op_http_request_next` call is never finished, and this program can't finish gracefully.
> 
> Is there any way to finish this second `op_http_request_next` call?

@piscisaureus and I discussed this and we think it's a non-issue. After connection is accepted it has no relation with the listener and it's up to the user to manage connection lifetime (eg. you want do a graceful shutdown of the server, so you close the listener but handle open connections before exiting).

**Comment by bartlomieju** [comment]
#10836 has landed so closing as resolved.
