### ISSUE TITLE
Deno.connect not support  transport:"udp"      

### ISSUE THREAD

**Issue by gcxfd** [denoland/deno#10519]
Deno.connect not support  transport:"udp"     , only support tcp

**Comment by DjDeveloperr** [comment]
Use https://doc.deno.land/builtin/unstable#Deno.listenDatagram (with --unstable)

**Comment by gcxfd** [comment]
listenDatagram no supoort connect
I can use udp connect  get my local ip without send any data

**Comment by gcxfd** [comment]
see
https://stackoverflow.com/questions/7334349/python-get-local-ip-address-used-to-send-ip-data-to-a-specific-remote-ip-addres
https://www.masterraghu.com/subjects/np/introduction/unix_network_programming_v1.3/ch08lev1sec11.html

**Comment by lucacasonato** [comment]
```js
const conn = Deno.listenDatagram({
  port: 10000,
  transport: "udp"
});
const addr = conn.addr;
console.log(addr);
```

**Comment by gcxfd** [comment]
> ```js
> const conn = Deno.listenDatagram({
>   port: 10000,
>   transport: "udp"
> });
> const addr = conn.addr;
> console.log(addr);
> ```

see the image below , I'm writing upnp with deno , I need intranet ip 172.16.0.15 not 127.0.0.1
![image](https://user-images.githubusercontent.com/69608605/117283354-49b82900-ae98-11eb-9c34-c6ba92703c1f.png)

**Comment by lucacasonato** [comment]
How would you do this in Node?

**Comment by gcxfd** [comment]
use tcp connect as now use in deno

there is a open issue in nodejs

no support for "connected" UDP sockets #769
https://github.com/nodejs/node-v0.x-archive/issues/769
