### ISSUE TITLE
headers iterator should have linear not quadratic complexity

### ISSUE THREAD

**Issue by ry** [denoland/deno#10520]
See https://github.com/denoland/deno/pull/10199#issuecomment-833465166

https://github.com/denoland/deno/blob/main/extensions/fetch/20_headers.js#L178-L207

**Comment by lucacasonato** [comment]
Note that the algorithm still has to follow the spec: https://fetch.spec.whatwg.org/#concept-header-list-sort-and-combine.

This should be doable with O(2n) instead of O(n^2) complexity though.
