### ISSUE TITLE
`deno test --coverage` `--exclude` and `--include` flags don't seem to work

### ISSUE THREAD

**Issue by itohatweb** [denoland/deno#10544]
Tested both flags `--exclude` and `--include` and always get the error
```ts
error: Found argument '--exclude' which wasn't expected, or isn't valid in this context
```

Deno Version: 1.9.2

**Comment by lucacasonato** [comment]
The test flag doesn't take flags to filter coverage. Please see https://deno.land/manual@v1.9.2/testing#test-coverage
