### ISSUE TITLE
parsing fails when class has `declare` instance method with access modifier

### ISSUE THREAD

**Issue by acdibble** [denoland/deno#10548]
I've tried all the other keywords in JS and TS and wasn't able to reproduce this issue with any other of them. Here's a basic reproduction:

```ts
// test.ts
class Test {
  declare() {}
}
```

```bash
$ deno fmt test.ts
Checked 1 file
```

Add any access modifier to the instance method `declare`:
```ts
  private declare() {}
```
```bash
$ deno fmt test.ts
Error formatting: ~/test.ts
   Line 2, column 18: Unexpected token `(`. Expected identifier, string literal, numeric literal or [ for the computed key

    private declare() {}
                   ~
Checked 1 file
```

It works with `static`, and when `static` any of the access modifiers.

Deno version:
```bash
$ deno --version
deno 1.9.2 (release, x86_64-apple-darwin)
v8 9.1.269.5
typescript 4.2.2
```

**Comment by dsherret** [comment]
Also occurs with `deno run`.

```
> deno run test2.ts
error: Unexpected token `(`. Expected identifier, string literal, numeric literal or [ for the computed key at file:///V:/test2.ts:2:17
```

**Comment by kitsonk** [comment]
Ok, then a swc parsing error. That would be during dependency parsing for `deno run`.

**Comment by kitsonk** [comment]
Ref: https://github.com/swc-project/swc/issues/1671

**Comment by dsherret** [comment]
This was fixed a while ago. Closing. Should be in Deno 1.11.
