### ISSUE TITLE
"The procedure entry point EventSetInformation could not be located in the dynamic link library advapi32.dll"

### ISSUE THREAD

**Issue by nilslindemann** [denoland/deno#10543]
Since Deno release 1.9.0, when running `deno run https://deno.land/std/examples/welcome.ts` Deno will crash on Windows 7 (well, on *my* Windows 7) with the message "The procedure entry point EventSetInformation could not be located in the dynamic link library advapi32.dll".

Version 1.8.3 is the last version which does not show this message on my system.

**Comment by crowlKats** [comment]
Windows 7 is EOL, and as such deno does not support it

**Comment by nilslindemann** [comment]
Yeah, it is time to switch to Linux ...

**Comment by kitsonk** [comment]
Deno is not supported on Windows 7. If it works at all, it is by luck, not intentional.

**Comment by nilslindemann** [comment]
@kitsonk I did not request anything, so there is nothing to decline.
