### ISSUE TITLE
`--quiet` should be a default. Instead the `--verbose` should be introduced.

### ISSUE THREAD

**Issue by canonic-epicure** [denoland/deno#10558]
I thought I'll file an issue here, to start a discussion. I believe the `--quiet` option should be a default behavior and instead the `--verbose` option is needed.

This aligns well with the spirit of the Linux development, where commands output the minimum required information.

In my particular case, I'm rendering the progress bar at the bottom of output, which is updated dynamically, by moving the cursor in the terminal. Then I launch WebWorkers, which imports various files and outputs `check file://` in stderr, and there's no way to intercept those messages - my output formatting is broken by these intermediate messages.

I believe using WebWorkers + dynamic cursor management in cli is not an exceptional use case.

**Comment by kitsonk** [comment]
That isn't a bad idea, but it requires even more knowledge of the terminal to check support for certain ASCII control codes in order to be able to "degrade" successfully, right?

**Comment by dsherret** [comment]
Deno sometimes takes time downloading remote modules (ex. on very slow networks) and not having any feedback about going on by default would get confusing.

**Comment by canonic-epicure** [comment]
That is an exceptional situation for which it can indeed output a warning in the console. But in the most of cases networks are fast enough and this extra output just pollutes the console.

**Comment by bartlomieju** [comment]
This has been discussed internally, the current behavior has been in place for several years and as pointed out by David there are situations where downloading takes quite a long time (eg. various npm modules) and showing an interactive progress bar to show that we're still doing work.

Additionally you can use `RUST_LOG=error` env var to disable logging without having to pass an additional CLI flag. We're gonna add `DENO_LOG` env var to make it more specific for Deno.
