### ISSUE TITLE
Increase maximum webstorage size

### ISSUE THREAD

**Issue by crowlKats** [denoland/deno#10557]
Currently there is a hard cap of 5MB for both local & session storage. Browsers have increased this to 10MB years ago.
I think we should implement https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Browser_storage_limits_and_eviction_criteria#storage_limits, as FF will soon use the same logic for localstorage, but the idea of deno's localstorage using up half of someone's disk space doesnt thrill me, though theoretically current localstorage could take up the entiire disk (all origins combined)

**Comment by sebastienfilion** [comment]
In my opinion, it can be augmented to 10Mb. But also think we should consider a way to let the user arbitrarily set the maximum, maybe with a flag.

**Comment by getspooky** [comment]
I think it would be a good idea to provide the `max Limit` option and let the user specify how much space they want to reserve.

**Comment by bartlomieju** [comment]
Let's just increase size limit to 10Mb and call it a day? Why would we want to make this option configurable if it's not configurable in the browser?

**Comment by crowlKats** [comment]
agreed that this should not be configurable by the user whatsoever.
i am just not sure if 10mb or the FF storage criteria would be better (or maybe a different fixed value?); 10mb is more than enough on the browser, but server side i can imagine one using a lot more

**Comment by caspervonb** [comment]
> Let's just increase size limit to 10Mb and call it a day? Why would we want to make this option configurable if it's not configurable in the browser?

Agreed.

With eviction and persistence it gets incredibly convoluted, even understanding it as a user is a fairly major headache.
We can come back to it later maybe but for now I'd be in favour of a simple bump to the size and call it good.

**Comment by getspooky** [comment]
Sure , The maximum browser storage space is dynamic — it is based on your hard drive size. The global limit is calculated as 50% of free disk space. But currently the most simpler solution is to make `10MB` instead of `5MB`.
what do you think ?

**Comment by lucacasonato** [comment]
Lets bump to 10MB and call it a day.
