### ISSUE TITLE
Deno.args works differently when installing script

### ISSUE THREAD

**Issue by einarmagnus** [denoland/deno#10563]
When installing a script with `deno install`, the `Deno.args` starts contining the script name as the first element, changing the behaviour of my script in an unexpected way.
The documentation says:
```
const Deno.args: string[]

Returns the script arguments to the program. If for example we run a program:

deno run --allow-read https://deno.land/std/examples/cat.ts /etc/passwd

Then Deno.args will contain:

"/etc/passwd" 
````
There is no mention here of the fact that the script name will be prepended to the arguments when the script is run after being installed.

Example:

`test_deno_args.ts`:
```typescript
for (const arg of Deno.args) {
    console.log(arg);
}
```

```
% deno run test_deno_args.ts arg1 arg 2
arg1
arg
2

% deno install test_deno_args.ts test_deno_args
✅ Successfully installed test_deno_args
% test_deno_args arg1 arg 2
test_deno_args
arg1
arg
2
```

Is this by design?

**Comment by nayeemrmn** [comment]
Your install command was `deno install test_deno_args.ts test_deno_args`, this bakes `test_deno_args` in as the first arg. You just need to run `deno install test_deno_args.ts`. Working as expected.
