### ISSUE TITLE
`deno info` should display the current path of the Local Storage file

### ISSUE THREAD

**Issue by sebastienfilion** [denoland/deno#10585]
I think it would be a good idea to add a new item to `deno info` to display the path of the Local Storage file.
It might be useful when a user wants to quickly remove it. Also good for transparency.

**Comment by lucacasonato** [comment]
cc @crowlKats

**Comment by sebastienfilion** [comment]
An alternative to clear the Local Storage is `deno repl --location=[DOMAIN]` and then to use `localStorage.clear()`.

But oddly running `deno --location=[DOMAIN]` and `echo ... | deno repl --location=[DOMAIN] --` throws error because of the `--location` flag.

**Comment by lucacasonato** [comment]
`deno eval --location=[DOMAIN] "localStorage.clear()"`?

**Comment by crowlKats** [comment]
`deno info` could give:
`location data location: "/Users/crowlkats/Library/Caches/deno/location_data"`
and if the `location` flag is set, then give the full path:
`deno info --location=https://deno.land`
`location data location: "/Users/crowlkats/Library/Caches/deno/location_data/491d1c5f8d5eaa49d0ee3166c5aca7fbf9af5c466365713577ab3c739342712c"`
