### ISSUE TITLE
`deno test --doc` - `--watch` flag doesn't reload when making changes to doc

### ISSUE THREAD

**Issue by sebastienfilion** [denoland/deno#10599]
If running the command `deno test --doc --watch ..` I would expect the test to re-run when I make changes to the relevant docs.
Right now, it reloads only when making changes to the functions.

For example take a file `users.ts` is a corresponding `users_test.ts`.

```ts
interface Users {
  name: string;
  email: string;
  login: {
    uuid: string;
  };
}

/**
 * ```
 * import { getUser } from "./users.ts";
 *
 * const p = getUser().then(user => user.fullName);
 * ```
 */
export function getUser (): Promise<Users> {

  return fetch(`https://randomuser.me/api/?inc=name,email,login,id`)
    .then(response => response.json())
    .then(({ results: [ user ] }) => user);
}
```

Obviously the doc is wrong because it refers to `user.fullName` instead of `user.name`.

Now if I run `deno test --doc --watch` on the file, I'll get an error but it doesn't rerun if I fix the error.

@caspervonb

**Comment by caspervonb** [comment]
Thanks @sebastienfilion.
Known issue, merged in a hurry 😁
