### ISSUE TITLE
`deno upgrade`: both 'downloaded size' and 'download percentage' are padded with leading zeros

### ISSUE THREAD

**Issue by darkred** [denoland/deno#10609]
(follow-up to #10291)

<sup>*First of all thanks a lot for implementing the download percentage with #10343*</sup>

I just upgraded the new version, 1.10.1,
and I see that both the 'downloaded size' and 'download percentage' are padded with leading zeros:
<details>
<summary>screen capture</summary>

`deno upgrade --dry-run --force`
![](https://user-images.githubusercontent.com/723651/117943119-7b0b7b80-b314-11eb-8421-f74b2764d36d.gif)
</details>

For example:
`02.1 MiB / 24.0 MiB (008.9%)`
while if they were:
`2.1 MiB / 24.0 MiB (8.9%)`
they would be more easy to perceive.

Thank you

**Comment by lucacasonato** [comment]
This is intentional to prevent excessive layout shift.

**Comment by darkred** [comment]
I understand, but don't you agree that `02.1 MiB` and especially `008.9%` are difficult to perceive?

Is it not possible to strike a balance between preventing excessive layout shift, 
and not padding with leading zeros?

I mean, would it help if clearing the line at these two points:
`2.5 Mib / 24.0 MiB (10.0%)` when the latter reaches 2-digit
`10 Mib / 24.0 MiB (42.0%)` when the former reaches 2-digit ?

**Comment by lucacasonato** [comment]
Maybe we could just pad with spaces instead of 0. cc @crowlKats

**Comment by crowlKats** [comment]
> Maybe we could just pad with spaces instead of 0. cc @crowlKats

I considered that initially, but it looked very weird to me, whereas a `0` looked all right

**Comment by CGQAQ** [comment]
Maybe using underscore? 😄 
![image](https://user-images.githubusercontent.com/15936231/118351376-3c80f580-b58e-11eb-85e7-a0a5de936491.png)

**Comment by crowlKats** [comment]
Underscores look even worse imo

**Comment by CGQAQ** [comment]
![IcqfQeai6J](https://user-images.githubusercontent.com/15936231/118358548-ddcd7300-b5b1-11eb-8a4c-9f1a97d9b58e.gif)

**Comment by lucacasonato** [comment]
That looks great. Would you mind opening a PR?

**Comment by CGQAQ** [comment]
> That looks great. Would you mind opening a PR?

Already in the PR #10639

**Comment by crowlKats** [comment]
tbh i dont like that the `100.0` shifts to the right at the end, but welp

**Comment by darkred** [comment]
Thank you for fixing this, @CGQAQ .
