### ISSUE TITLE
Using `deno ... --watch` with the incorrect permissions should kill the watcher

### ISSUE THREAD

**Issue by sebastienfilion** [denoland/deno#10600]
I think this happens with every relevant subcommands, but if I use the `--watch` flag but I omit/forget the appropriate permissions, the runtime throws an error but keeps watching for changes...
There are no ways to give permission passed that point so I think that the process should be killed.

```shell
→ deno run --unstable --watch cli.js display                                  ✘
error: Uncaught PermissionDenied: Requires read access to <CWD>, run again with the --allow-read flag
  else if (action === "display") Deno.readFile(`${Deno.cwd()}/movies`)
                                                       ^
    at unwrapOpResult (deno:core/core.js:99:13)
    at Object.opSync (deno:core/core.js:113:12)
    at Object.cwd (deno:runtime/js/30_fs.js:57:17)
    at file:///Users/sebastienfilion/Developer/i-y/deno/03/cli.js:25:56
Watcher Process finished! Restarting on file change...
```

**Comment by lucacasonato** [comment]
Actually you can request permissions programmatically. So you could get more permissions after the fact using the Deno.permissions API.

**Comment by sebastienfilion** [comment]
Yes. I know about the runtime permissions API. 
I just think that it would be better for UX that the process is killed if watch is enable and a permission error is thrown.

**Comment by lucacasonato** [comment]
To us a `PermissionDenied` error is like any other reason for the process to exit - a user can throw this error themselves too. We won't special case it - respectfully closing.
