### ISSUE TITLE
Temporarily ignore `transfer`/`options` argument in `postMessage()`

### ISSUE THREAD

**Issue by 101arrowz** [denoland/deno#10617]
I maintain a package that targets Node.js and the browser. I'm currently trying to make the browser target compatible with Deno.

The main incompatibility is the use of inline workers. My package dynamically generates JS, embeds it into a temporary URL, and creates a worker from it. v1.9 added support for blob URLs, and v1.10 has fixed the structured cloning algorithm; thanks to the Deno team for your hard work on the project.

My package is actually very close to working on v1.10, but I'm facing the issue that `postMessage(msg, transfer)` fails:

```
Uncaught Error: Not yet implemented: `transfer` and `options` are not supported.`
```

I've seen #8341, but I'm specifically requesting that until support for `transfer` is added, the argument is simply ignored. Obviously, the difference between transferring ownership and cloning is massive internally, but the only effect it has from JS's point of view is that the object is inaccessible from the parent thread. Of course, if implementing #8341 is not too difficult, there's no need for this stop-gap solution.

**Comment by aaronhuggins** [comment]
Commenting to watch the discussion on this issue as it impacts a project with similar worker patterns I am developing.

**Comment by kitsonk** [comment]
@lucacasonato thoughts? I can see how this is a pain to write isomorphic code.

**Comment by bartlomieju** [comment]
This is no implemented, both `transfer` and `options` are supported in `postMessage()`
