### ISSUE TITLE
[Feature Request] Add a --clearscreen option to go with --watch for testing

### ISSUE THREAD

**Issue by David-Else** [denoland/deno#10622]
At the moment when a file is changed when using `deno test --watch` the new test report is just added under the previous. It would be great if it could optionally clear the console first. This makes it much easier to see what is happening without having to constantly read all the way down the screen to find the information you are looking for.

**Comment by caspervonb** [comment]
If we implement this, should be applied globally to all --watch implementations, no?

**Comment by bartlomieju** [comment]
> If we implement this, should be applied globally to all --watch implementations, no?

I agree, I don't like adding a new flag just for clearing screen. Let's default to this behaviour.
