### ISSUE TITLE
MITM attack when importing files from untrusted sources

### ISSUE THREAD

**Issue by qti3e** [denoland/deno#1063]
The whole concern is that an attacker might change the content of a file when it is served over HTTP but not HTTPs.

A possible solution is to exit the program when an untrusted import is detected and tell the user to provide the `--force` flag if they are sure about what they are going to do.

**Comment by ry** [comment]
I think we should follow the browser conventions here - using a script tag to import http is allowed.

**Comment by qti3e** [comment]
@ry In a web browser, there is no threat to the client, but things in a server-side runtime are a bit different and they require stricter rules, one mistake might end up a user losing all of their data.

Indeed you can't even do certain things in browsers over plain HTTP, I can name service workers as an example.

Quoting from [`Introduction to Service Worker | Google Developers Network`](https://developers.google.com/web/ilt/pwa/introduction-to-service-worker):
> Service workers only run over HTTPS. Because service workers can intercept network requests and modify responses, "man-in-the-middle" attacks could be very bad.

It might be related to this topic https://www.drupal.org/project/securelogin/issues/1670822

**Comment by kitsonk** [comment]
I personally wouldn't be opposed to limiting remote module loading to `https://` only... but that is just my opinion.  I don't think we should add another security layer, just disallow it as "unsafe for code".

Of course MITM is just as viable for `https://` unless you are validating that the cert is from the organisation you expect it is from! 😉 Lots of corporate firewalls these days have transparent proxies and the capability to generate b2b certs.

**Comment by ry** [comment]
We're going to follow what the browser does, which is allow http imports. If that changes in the future, we will also change that.

**Comment by Janpot** [comment]
> using a script tag to import http is allowed.

🤔 aren't http scripts blocked in browsers when imported on a https origin?

**Comment by dandv** [comment]
@ry: any thoughts on @qti3e's argument that the server environment is far more privileged and has far more capabilities than the browser?

A MITM'ed browser request might be used to run a bot while page is open. A MITM'ed request on the server can be used to take over the server and launch a botnet. The `--allow` (net, filesystem) flags won't help, because for the vast majority of deployed web server applications, they'll be enabled anyway.

**Comment by kitsonk** [comment]
@dandv there are other compensating controls in Deno these days, like lockfiles, bundling, compiling, cache-only, and the ability to redirect the cache externally.  That coupled with Deno "zero-trust" permission system (which seperate read and write and allows you to scope the paths as well as remote hosts you can connect to) and ability to get details dependency information via the likes of `deno info`.
