### ISSUE TITLE
Use environment variable in domain with --allow-net

### ISSUE THREAD

**Issue by jsjoeio** [denoland/deno#10634]
## Problem

As a user of Deno, I would like to set `--allow-net` permission based on an environment variable (i.e. `PORT`) with a fallback so that I can let app users specify the `PORT` without giving my app network access to all domains.

### Additional Context

I'm writing a CLI in Deno. There is a command called `start` which starts up a local server using `oak`. I want users to be able to specify the port using the environment variable `PORT`.

Here is the project: [`jp-courses`](https://github.com/jsjoeio/jp-courses)

### What I've tried

- `--allow-net=:$PORT` -> `Bad host:port pair`
- `--allow-net=:*` -> `Bad host:port pair`

## Workaround

It seems the only workaround that I can think of is to set `--allow-net` to everything (not limited to specific domains). 

## Related

I looked through previous issues and found these two to be somewhat relevant:

- https://github.com/denoland/deno/issues/2705
- https://github.com/denoland/deno/issues/6685

**Comment by bnoordhuis** [comment]
Deno doesn't do interpolation (`--allow-net=:$PORT`), that's a shell thing. If you run it through bash (`bash deno run --allow-net=:$PORT app.ts`), it should work. You need to be mindful of shell injection, of course.

Wildcards aren't supported. Your example of `--allow-net=:*` is just `--allow-net`.

**Comment by jsjoeio** [comment]
Ahh okay, that makes more sense. Thanks for the explanation! Feel free to close then.
