### ISSUE TITLE
`install_unicode` test is bogus

### ISSUE THREAD

**Issue by piscisaureus** [denoland/deno#10636]
The test will pass even if the `deno install` feature is removed.

Edit: it seems that it exercises the `deno` from `$PATH` rather than the one in `target/{debug|release}/`.

Edit: generally erratic behavior. Potentially caused by the `install` test [being bad](https://github.com/denoland/deno/blob/b0e30dbbc63933642a35cd9c4deff21c009860a9/cli/tools/installer.rs#L448-L450); I suspect this might be responsible for https://github.com/denoland/deno/issues/10502 too.

**Comment by ry** [comment]
disabled in e02403bb45
