### ISSUE TITLE
aarch64-apple-darwin binary for v1.10.1 missing (deno compile)

### ISSUE THREAD

**Issue by LukeChannings** [denoland/deno#10649]
```
echo 'console.log("hello world")' > test.ts
deno compile --target aarch64-apple-darwin ./test.ts
```

Fails with:

```
Check file:///Users/luke/Developer/moviematch/test.ts
Bundle file:///Users/luke/Developer/moviematch/test.ts
Compile file:///Users/luke/Developer/moviematch/test.ts
Checking https://dl.deno.land/release/v1.10.1/deno-aarch64-apple-darwin.zip
Download could not be found, aborting
```

https://dl.deno.land/release/v1.10.1/deno-aarch64-apple-darwin.zip returns a 404, but https://github.com/denoland/deno/releases/download/v1.10.1/deno-aarch64-apple-darwin.zip is working fine.

Note: `deno compile --target x86_64-apple-darwin ./test.ts` compiles fine, and it appears only `deno-aarch64-apple-darwin` is missing.

**Comment by lucacasonato** [comment]
now uploaded.
