### ISSUE TITLE
Prevent modules imported through https to internally import http modules

### ISSUE THREAD

**Issue by kevinkassimo** [denoland/deno#1064]
For security reasons? (I believe for script tags in browsers would show warnings on loading an http resource while the page is loaded under https)

**Comment by cByst** [comment]
What do you think the expected behavior if this case encountered?

**Comment by kevinkassimo** [comment]
@cByst like throw a permission_denied error? Or we can add another custom error and throw it

**Comment by hayd** [comment]
![chrome](https://developers.google.com/web/fundamentals/security/prevent-mixed-content/imgs/simple-mixed-content-error.png)

throw an error unless --allow-running-insecure-content, --allow-insecure or something.

**Comment by kevinkassimo** [comment]
I am thinking about whether this should be enforced in TypeScript or Rust. If in TypeScript, I would need to expose protocol used to load the module to the compiler. However, this would mean the http loaded module would be first fetched and cached anyways. If in Rust, we need to do protocol checks in `code_fetch`.

Also, we might need to change the logic of `fetch_sync_string`, as currently it blindly follows redirection and we need to avoid `https` -> `http` redirects

@hayd something like `--allow-downgrade-secure-imports`? (Actually, I would assume that downgrading security might always be unwanted...) Also, we could add something like `--force-secure-imports` to disable any imports using insecure channels like http.

**Comment by kitsonk** [comment]
Something like this needs to be enforced in the privileged side (Rust) in my opinion.  TypeScript has no concept of remote modules, the Deno compiler has no concept of remote modules.  It simply asks for some code.  It feels like it should be another kind of a `DenoError` that is returned from the privileged side, like not found is for missing modules.

**Comment by kevinkassimo** [comment]
@kitsonk Yeah Rust side impl sounds much more reasonable. We could introduce some new kind of Error like `UnsafeImport` or `InsecureProtocol` for this (also could shared with #1063).

(From my investigation TS side is doable by adding protocol data to CodeFetchRes and ModuleMetadata, and then examining current module and its deps in `_makeDefine`, but this feels unrelated to the functionalities of the compiler itself and would be very awkward)

**Comment by kitsonk** [comment]
> (From my investigation TS side is doable by adding protocol data to CodeFetchRes and ModuleMetadata, and then examining current module and its deps in `_makeDefine`, but this feels unrelated to the functionalities of the compiler itself and would be very awkward)

That is certainly possible, but from a design standpoint, when it comes to loading modules, all of "does this module exist, does it not exist, is it safe to load" needs to be handled on the privileged side.  There are two pieces of information that the compiler needs to pass, the module specifier and the containing file.  If it gets something back, it assumes it is "safe" to try to execute, then constrained by whatever "ops" that code is allowed to do.  So if breaking out to `http` is unsafe, it needs to be done in Rust (again, IMO).

**Comment by ry** [comment]
Are there any specs that say exactly how HTTP and HTTPS imports should interact?

**Comment by kitsonk** [comment]
Browsers don't support FQDN imports within modules, I believe.  If they did, then CORS rules would likely apply.

**Comment by ry** [comment]
@kitsonk Chrome did last time I checked.

**Comment by kitsonk** [comment]
@ry you are right...

While I can't find anything official in any standards, it looks like all implementations follow CORS rules.  The most concise source is here: https://jakearchibald.com/2017/es-modules-in-browsers/#always-cors. Browsers also prevent/block downgrades, so an `http://` import from a `https://` imported module should be disallowed, while a `https://` import from an `http://` module would be allowed.

It is hard to apply the CORS model to Deno though, but blocking downgrades...  It is arguable that whatever we do would apply to `fetch()` as well.
