### ISSUE TITLE
lsp: failed to load configuration file error is not descriptive

### ISSUE THREAD

**Issue by Timmmm** [denoland/deno#10646]
That error should include some more information otherwise it is quite useless:

1. What files did it try to open?
2. Why did it fail?

**Comment by satyarohith** [comment]
Is this from `deno run --config=...`?  A reproduction and context would be helpful.

**Comment by Timmmm** [comment]
Sorry wrong repo. This was for the VSCode plugin - I'll open it again in the right place!

**Comment by satyarohith** [comment]
@Timmmm I think the issue should stay here as it might be related to `deno lsp`.

**Comment by Timmmm** [comment]
Oh you're right. The error is [here](https://github.com/denoland/deno/blob/24a2e1ef82cf1a081a9b4603a597eb0085755e36/cli/lsp/language_server.rs#L435).

**Comment by Timmmm** [comment]
It looks to me like the error probably does contain at least some more information (not the filename though) but it is printed with [`err.to_string()`](https://github.com/denoland/deno/blob/24a2e1ef82cf1a081a9b4603a597eb0085755e36/cli/lsp/language_server.rs#L738) which won't show all the causes so you only get the outermost `.context()`.
