### ISSUE TITLE
Signal API blocks exiting the process

### ISSUE THREAD

**Issue by kt3k** [denoland/deno#10658]
Because Signal op uses `AsyncUnref` op internally, it shouldn't block process exiting. But since around 1.4.0 it seems blocking the program exiting.

The following code exits immediately with deno <=v1.3.0, but it never exits with >=v1.4.0:

```ts
Deno.signal(Deno.Signal.SIGABRT).then(() => { console.log("SIGABRT"); });
```

**Comment by kt3k** [comment]
op_signal_poll seems to have started using usual async op since #7118, but JsRuntimeState struct in core/runtime.rs still keeps `pending_unref_ops: FuturesUnordered<PendingOpFuture>` in its field and it seems being polled. So maybe the original behavior can be restored by just dispatching async-unref op for op_signal_poll. I'll try this.

**Comment by lucacasonato** [comment]
@kt3k There is currently no way to register or dispatch an unref async op.
