### ISSUE TITLE
(possible regression) Nullish Coalescing operator, logical and/or and perenthesis

### ISSUE THREAD

**Issue by cmd-johnson** [denoland/deno#10668]
Combining the nullish coalescing operator (`??`) with logical and (`&&`) and or (`||`) is not permitted (see [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator#no_chaining_with_and_or_or_operators)). However, when wrapping the `&&` and `||` parts in parenthesis, it should be fine.

The following simple snippet runs correctly with `deno run`, but the code produced by `deno bundle` fails to execute because of syntax errors:

```sh
$ cat test.ts
console.log(null ?? (undefined && true));

$ deno run test.ts
undefined
$ deno bundle test.ts > test.bundle.ts && cat test.bundle.ts
Check file:///omitted/test.ts
Bundle file:///omitted/test.ts
console.log(null ?? undefined && true);

$ deno run test.bundle.ts
Check file:///omitted/test.bundle.ts
error: TS5076 [ERROR]: '&&' and '??' operations cannot be mixed without parentheses.
console.log(null ?? undefined && true);
                    ~~~~~~~~~~~~~~~~~
    at file:///omitted/test.bundle.ts:1:21
$ deno --version
deno 1.10.1 (release, x86_64-unknown-linux-gnu)
v8 9.1.269.27
typescript 4.2.2
```

This issue was previously reported in #8722 and should've been fixed in #8901, hence the possible regression.

**Comment by kitsonk** [comment]
cc/ @kdy1

**Comment by kdy1** [comment]
Fixed with the new version of `swc_ecma_transforms_base`.
