### ISSUE TITLE
Getting absolute paths with read permission & CWD 🤝

### ISSUE THREAD

**Issue by jsejcksn** [denoland/deno#10678]
Refs: [Discussion](https://github.com/denoland/deno/discussions/10407), [Discord](https://discord.com/channels/684898665143206084/684898665151594506/844000679722614816)

---

## Observations

For file path `./dir/file`:

If I already have been granted `read` permission for `dir`, it doesn't seem that Deno provides a mechanism for getting the absolute path for `file` without also granting read permission for `CWD`.

e.g. [`Deno.realPath`](https://doc.deno.land/builtin/stable#Deno.realPath) and [`path.resolve`](https://deno.land/std@0.97.0/path/posix.ts#L24) require `read` for `CWD`. (Is there another way?)

If this is intentional because of security and privacy considerations regarding filesystem path information, then skip the next section.

## Feature request (if not a security/privacy consideration)

If such a mechanism simply does not exist yet, then consider this a feature request.

## Security considerations and thoughts

Otherwise, the following is leaking path information:

<code>[Deno.watchFs](https://doc.deno.land/builtin/stable#Deno.watchFs)("./dir/file", { recursive: false })</code>

because the paths in the events are absolute paths for the file, even without granting `read` for `CWD`.

**Further thoughts:**

In order to maintain filesystem path privacy, what would be the pros/cons for refactoring all of the APIs which accept path strings to also accept some kind of file/dir ID in place of the path? (e.g. inode on unix-like platforms)

**Comment by lucacasonato** [comment]
I don't think this is possible. Canonicalizing `./dir/` by definition requires `<cwd>`. The permission thus also makes sense.
