### ISSUE TITLE
Deno.emit: Add option for ambient type declarations

### ISSUE THREAD

**Issue by jsejcksn** [denoland/deno#10677]
This is a follow up to the discussion at https://github.com/denoland/deno/discussions/10549

I see that I can supply predefined environment enums in the emit options `compilerOptions.lib` array (e.g. `ES2017`, `DOM.Iterable`, etc.), but I don't see a way to provide other environment types (e.g. paths to declaration files) because properties like `compilerOptions.typeRoots` aren't supported.

@kitsonk [suggested](https://github.com/denoland/deno/discussions/10549#discussioncomment-716399) using the [`compilerOptions.types`](https://doc.deno.land/builtin/unstable#Deno.CompilerOptions) property, but that doesn't seem to work (it produces another error).

If I include

```ts
import "./types/mod.d.ts";
```

at the top of every source file then it compiles without errors, but that is not a maintainable approach.

If I want to compile for other [custom] runtime environments, do I really have to import the types into every source file or is there a configuration alternative?

I'm attaching a simple example for demonstration and reproduction:

[example.zip](https://github.com/denoland/deno/files/6497380/example.zip)

```
example % cat run 
deno --unstable run --allow-read=. --allow-write=. main.ts

example % ./run 
TS2688 [ERROR]: Cannot find type definition file for './types/shared-node-browser.d.ts'.
  The file is in the program because:
    Entry point of type library './types/shared-node-browser.d.ts' specified in compilerOptions

TS2584 [ERROR]: Cannot find name 'console'. Do you need to change your target library? Try changing the `lib` compiler option to include 'dom'.
  console.log('hello world');
  ~~~~~~~
    at file:///Users/jesse/Downloads/example/mod.ts:5:3

Found 2 errors.
"mod.bundle.cjs" written
```

**Comment by ebebbington** [comment]
Would love to see this too, right now it’s a jack approach to get global declarations

**Comment by kitsonk** [comment]
I will be raising a PR soon that delivers this feature using the `compilerOptions.types` across all different forms of type checking we support (`Deno.emit` and the `--config tsconfig.json` forms).
