### ISSUE TITLE
`Deno.errors.NotSupported` isn't in types

### ISSUE THREAD

**Issue by Liamolucko** [denoland/deno#10701]
`Deno.errors.NotSupported` is defined here:
https://github.com/denoland/deno/blob/ef5e5f5e460b40b2c5f7cbcf0a1d11488fc7277f/runtime/js/01_errors.js#L131-L136
However, it isn't included the `.d.ts` files. I'm not sure what it's actually used for, but it seems like it should probably be included in the type definitions if it exists.

**Comment by bartlomieju** [comment]
CC @lucacasonato @crowlKats

**Comment by crowlKats** [comment]
Has nothing to do with me, rather git blame is looking at your @bartlomieju

**Comment by ayame113** [comment]
I think this issue is happening again after #10702.
