### ISSUE TITLE
Running deno eval without temp files?

### ISSUE THREAD

**Issue by lowlighter** [denoland/deno#10715]
From my understanding, when `deno eval` execute ts code, it gets transpiled first into a temp `$deno$eval.ts.js` file before being ran as js

This makes it impossible to use it on read-only file systems:
```
error: Read-only file system (os error 30) (for '"/var/task/.deno/gen/file/var/task/$deno$eval.ts.js"')
```

Not sure if there is a way to bypass this behaviour to avoid this `$deno$eval`

My current use case for this is for a "deno playground" hosted on vercel (hence ro system) which executes arbitrary user-provided code. Currently it works when using `--ext js` but not with `--ext ts`. I guess I could workaround this by running  `Deno.emit` first though

**Comment by kitsonk** [comment]
No, currently there is no way, but we should keep this in memory as there is no value in writing it to disk.

**Comment by bartlomieju** [comment]
The file is now stored in-memory when transpiling. I'm going to tentatively close this issue. Please comment if the problem persists.
