### ISSUE TITLE
Add window support for Deno and WebGPU

### ISSUE THREAD

**Issue by ReddikHaien** [denoland/deno#10714]
Based on the current progress with the WebGPU(hats off to everyone involved, good job :D), I was wondering if it would be possible to implement window support using [raw-window-handle](https://github.com/rust-windowing/raw-window-handle) as mentioned in a [#7863](https://github.com/denoland/deno/issues/7863#issuecomment-706897139). I did some tinkering and think a possible solution could be to create a wrapper struct for the window handle. For example:
```
pub struct WindowResource{
  pub window_handle: &'static dyn raw_window_handle::HasRawWindowHandle
}

impl Resource for WindowResource {
  fn name(&self) -> Cow<str>{
    "WindowResource".into()
  }
}

unsafe impl raw_window_handle::HasRawWindowHandle for WindowResource{
  fn raw_window_handle(&self) -> raw_window_handle::RawWindowHandle{
    self.window_handle.raw_window_handle()
  }
}


impl WindowResource{
  pub fn create_window_resource(handle: &'static dyn raw_window_handle::HasRawWindowHandle) -> Self{
    Self{
      window_handle: handle
    }
  }
}
```
This could then be passed to webgpu or to a different plugin as a simple rid. 

I'm pretty new to Rust, so I hope you'll exuse the terrible implementation above 😅

**Comment by crowlKats** [comment]
We are currently working on this, see #10690

**Comment by ReddikHaien** [comment]
Ahh, I see. 
Nice👍👍

**Comment by lucacasonato** [comment]
I'm going to keep the issue open, so we have something to track.

**Comment by crowlKats** [comment]
We have abandoned this idea due to various difficulties and complications, and as such am closing this issue
