### ISSUE TITLE
`cargo build -vv` return error: linking with `cc` failed: exit code: 1

### ISSUE THREAD

**Issue by getspooky** [denoland/deno#10722]
Hello deno community,
when i run `cargo build -vv` i got two errors 
- error: linking with `cc` failed: exit code: 1
- error: aborting due to previous error
- error: could not compile `deno_runtime`

Thanks

**Comment by magurotuna** [comment]
Can you try `cargo clean` and then build again?
I got the same error several times as well, and in my case `cargo clean` resolved the issue.

**Comment by getspooky** [comment]
@magurotuna thanks, it works.
