### ISSUE TITLE
Add location override option on `Deno.test`

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#10723]
Just like you can override permissions per test, it would be cool to let users specify a `--location` location per test. It would have to be a valid string / `URL`.

**Comment by caspervonb** [comment]
Potential security implications here, would one be allowed to set it to any arbitrary value?

**Comment by bartlomieju** [comment]
@lucacasonato do you have a concrete use case in mind? I can definitely see it being useful and we should consider implementing it, the question is if there's a burning need for it right now? (Maybe to test newly-added file:// `fetch` variant?) What might be security implications we should consider?

**Comment by lucacasonato** [comment]
No burning need, or usecase right now. It would not help with `file://` fetch, as location can not be set to file URLs.

**Comment by lucacasonato** [comment]
I don't think this is needed. Closing
