### ISSUE TITLE
Correct test --doc errors with "The parameter is incorrect. OS error 87" in windows

### ISSUE THREAD

**Issue by gewoonwoutje** [denoland/deno#10730]
I ran the following snippet of code through `deno test --doc ./utilities.ts`, and received 
`error: The parameter is incorrect. (os error 87) (for '"C:\\Users\\Wout\\AppData\\Local\\deno\\gen\\file\\C\\Users\\Wout\\Desktop\\sandbox\\utilities.ts:4-10.js"') `
```ts
// /utilities.ts

/**
 * Gives a string.
 *
 * ```
 * import { giveMeString } from './utilities.ts';
 *
 * console.assert(giveMeString() === 'string');
 * ```
 */
export function giveMeString() {
	return 'string';
}

```
When changing `giveMeString() === 'string'` to `giveMeString() === 0` , it shows the correct error like expected.

![doctest](https://user-images.githubusercontent.com/9407072/119059927-8ecc7700-b9d1-11eb-8624-9cfe56aab551.gif)

Deno version:
```
deno 1.10.2 (release, x86_64-pc-windows-msvc)
v8 9.1.269.27
typescript 4.2.2 
```

**Comment by gewoonwoutje** [comment]
Oops, using the `assertEquals` does not do type checking. With using `console.assert`, it does work:
![image](https://user-images.githubusercontent.com/9407072/119059240-347ee680-b9d0-11eb-8dfd-f7429165720c.png)

Still, the error message is not very clear.

**Comment by caspervonb** [comment]
Windows only bug.
Haven't quite figured out why it happens yet.

**Comment by gewoonwoutje** [comment]
So, I guess this was the cause of the bug:
https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file?redirectedfrom=MSDN#file_and_directory_names

**Comment by caspervonb** [comment]
> So, I guess this was the cause of the bug:
https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file?redirectedfrom=MSDN#file_and_directory_names

Yeah `:` is reserved, will get this merged today.
