### ISSUE TITLE
Error while parsing empty tsconfig.json

### ISSUE THREAD

**Issue by romainPrignon** [denoland/deno#10733]
Hi :)

While trying to run deno using: `deno run -c tsconfig.json main.js` I got:
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', cli/config_file.rs:290:59
```

The Error happens with a fully commented tsconfig.json file or an empty one.

#### How typescript and ts-node handle that ?
Running `ts-node -P tsconfig.json main.ts` or `tsc -p tsconfig.json main.ts` with an empty tsconfig.json works 

#### Potential fix
Return a valid empty json object in cli/config_file.rs:290 ?

```diff
-  let jsonc = jsonc_parser::parse_to_serde_value(text)?.unwrap();
+ let jsonc = jsonc_parser::parse_to_serde_value(text)?.unwrap_or(json!({}));
```

I'm ready to submit a PR if you want :)

*deno version*: 1.10.2

**Comment by nayeemrmn** [comment]
I would have assumed `jsonc_parser::parse_to_serde_value()` returns `Err(_)` when passed an empty string, like any other invalid JSON, but it returns `Ok(None)`. I wonder why that's an `Option` and what `None` represents. Anyway the fix should be something like:
```diff
+use deno_core::error::anyhow;
...
-    let jsonc = jsonc_parser::parse_to_serde_value(text)?.unwrap();
+    let jsonc = match jsonc_parser::parse_to_serde_value(text)? {
+      Some(value) => value,
+      None => return Err(anyhow!("Invalid JSON."))
+    };
```
Or a jsonc version of `serde_json::from_str()` which behaves expectedly, if there is one.

**Comment by romainPrignon** [comment]
Thanks for your help @nayeemrmn !
I updated the PR accordingly

**Comment by dsherret** [comment]
> I would have assumed jsonc_parser::parse_to_serde_value() returns Err(_) when passed an empty string, like any other invalid JSON, but it returns Ok(None). I wonder why that's an Option and what None represents.

It's to differentiate between empty/only comments files and parser errors (ex. in dprint-plugin-json it doesn't error for an empty file or a file with only comments).
