### ISSUE TITLE
Deno.stat asks for --allow-read permissions although they are there

### ISSUE THREAD

**Issue by andreas-wagner** [denoland/deno#10738]
Happens since Deno v1.10.x

`deno test --allow-read=.test --cached-only --coverage=.cov --doc --import_map=import_map.json --jobs=1 --lock=lock.json --unstable mod.test.ts`
```ts
await Deno.stat(".test/folder");
// => PermissionDenied: Requires read access to ".test/folder", run again with the --allow-read flag
//    at deno:core/core.js:86:46
//    at unwrapOpResult (deno:core/core.js:106:13)
//    at async Object.stat (deno:runtime/js/30_fs.js:216:17)
```

And curiously:
`deno test -A --cached-only --coverage=.cov --doc --import_map=import_map.json --jobs=1 --lock=lock.json --unstable mod.test.ts`
```ts
const { state } = await Deno.permissions.query({
  name: "read",
  path: ".test/test.log",
});
console.log(state);
// => prompt
```
This should be "granted" (-A option), no?

**Comment by andreas-wagner** [comment]
My bad, it was a permission setting on a test.
I did specify write permissions, but I did not know that this is not a change, but a total replacement and I need to specify all other permissions there as well.

**Comment by caspervonb** [comment]
> My bad, it was a permission setting on a test.
I did specify write permissions, but I did not know that this is not a change, but a total replacement and I need to specify all other permissions there as well.

Documentation in need of work?
I mean, it does in general but wondering if anything there threw you off.

**Comment by andreas-wagner** [comment]
Is this doc'd at all? I found the permissions for tests in the commits actually 😅

**Comment by caspervonb** [comment]
Looks like our doc generator isn't handling that case well at all.
https://github.com/denoland/deno/blob/main/cli/dts/lib.deno.unstable.d.ts#L1190
