### ISSUE TITLE
Add a CA cert at runtime

### ISSUE THREAD

**Issue by cryptogohan** [denoland/deno#10735]
This is a question.

I'm trying to deploy Deno on the Digital Ocean apps platform with a managed database. The managed database requires SSL, which is considered good practice, but Deno doesn't accept the authority of the presented certificate (`InvalidData: invalid certificate: UnknownIssuer`). They make the ca certificate available as an environment variable but adjusting my Dockerfile to load it is a bit of a hassle and only required in their environment. I'd prefer to load this ca cert at runtime. Is this possible?

Deno is awesome 👏 . Thanks for your hard work!

**Comment by ry** [comment]
How are you giving Deno the certificate? Sample code may help us debug it further.

**Comment by lucacasonato** [comment]
@cryptogohan You can pass a CA cert file add as a root trust anchor when calling `Deno.connectTls`, using the `certificateFile` option in the options bag.

**Comment by cryptogohan** [comment]
@lucacasonato that's perfect, incoming issue/pr on deno-postgres if it lacks the option, let's see!

Thanks again! You seem to be popping up all over haha.

**Comment by cryptogohan** [comment]
Just for completeness sake @lucacasonato , I couldn't find `Deno.connectTls` but there is `Deno.startTls` which does have a `certFile` option, which appears to do what I'm looking for 👍 .

**Comment by cryptogohan** [comment]
Ah, found it [Deno.connectTls](https://doc.deno.land/builtin/stable#Deno.connectTls) expected unstable docs to be a superset of stable. Regardless, I needed `Deno.startTls` and that one supports the option too.
