### ISSUE TITLE
Updating tsconfig has errored: Failed to load configuration file

### ISSUE THREAD

**Issue by jeiea** [denoland/deno#10747]
### Reproducible steps

1. Prepare the following environment.
```
> systeminfo
OS Name:                   Microsoft Windows 10 Pro N
OS Version:                10.0.19042 N/A Build 19042
> code --version
1.56.2
054a9295330880ed74ceaedda236253b4f39a335
x64
> deno --version
deno 1.10.2 (release, x86_64-pc-windows-msvc)
v8 9.1.269.27
typescript 4.2.2
> # vscode_deno: v3.4.0
```
2. Execute the following commands.
```
git clone https://github.com/jeiea/deno_report.git
cd deno_report
code .
```
3. Open a.ts

### Expected behavior

There should be no error.

### Actual behavior

![image](https://user-images.githubusercontent.com/4188984/119233176-a71fcb80-bb62-11eb-8857-9c592674d709.png)

### Additional context

The following is 'Deno Language Server' panel output.
```
Starting Deno language server...
  version: 1.10.2 (release, x86_64-pc-windows-msvc)
Connected to "Visual Studio Code" 1.56.2
{"type":"mark","name":"update_tsconfig"},
Updating TypeScript configuration from: "./deno.tsconfig.json"
Updating tsconfig has errored: Failed to load configuration file
{"type":"mark","name":"request","count":1,"args":{"id":2,"method":"getSupportedCodeFixes"}},
{"type":"measure","name":"request","count":1,"duration":1},
{"type":"measure","name":"initialize","count":1,"duration":76},
language server initialized
{"type":"mark","name":"update_import_map"},
{"type":"measure","name":"update_import_map","count":1,"duration":0},
{"type":"mark","name":"update_registries"},
{"type":"measure","name":"update_registries","count":1,"duration":0},
Server ready.
```

I know denoland/vscode_deno#413 is similar to this but I'm using deno 1.10.2.

**Comment by satyarohith** [comment]
I couldn't reproduce this bug on `1.10.2` and on canary:
```
Starting Deno language server...
  version: 1.10.2 (release, x86_64-apple-darwin)
Connected to "Visual Studio Code" 1.56.2
Updating TypeScript configuration from: "./deno.tsconfig.json"
language server initialized
Server ready.
```
```
Starting Deno language server...
  version: 1.10.2+bdee065 (release, x86_64-apple-darwin)
Connected to "Visual Studio Code" 1.56.2
Updating TypeScript configuration from: "./deno.tsconfig.json"
language server initialized
Server ready.
```

**Comment by jeiea** [comment]
Then what informantion should I provide more?

**Comment by jeiea** [comment]
@satyarohith It seems you are using macos, which is different from mine(win10).

**Comment by jeiea** [comment]
I got a hint from master build. The following is the new log.

```
Starting Deno language server...
  version: 1.10.2 (debug, x86_64-pc-windows-msvc)
Connected to "Visual Studio Code" 1.56.2
Updating TypeScript configuration from: "./deno.tsconfig.json"
Updating tsconfig has errored: Could not find the config file: d:/D:/deno_report/deno.tsconfig.json
language server initialized
Server ready.
```

It seems drive letter is duplicate. I don't know how to inspect this so further investigation may take time.

**Comment by jeiea** [comment]
The following is what I see by debugger.

When [converting url to path](https://github.com/denoland/deno/blob/e9edd7e14d9d78f03c5f2e67fcc44e4dbaab8f2c/cli/lsp/language_server.rs#L443)  `config_url` was `file:///D:/deno_report/deno.tsconfig.json`.

[`path_str`](https://github.com/denoland/deno/blob/e9edd7e14d9d78f03c5f2e67fcc44e4dbaab8f2c/cli/config_file.rs#L275) is passed from `config_url.path()` and its value was `/D:/deno_report/deno.tsconfig.json`.

And `path.is_absolute()` is evaluated to false so `std::env::current_dir()?.join(path_str)` is used.

**Comment by kitsonk** [comment]
The config update takes a slightly different code path, and vscode canonicalises file paths on windows slightly different than Rust does and it looks like that difference is manifesting itself when updating the configuration.

**Comment by jeiea** [comment]
Can I submit a PR for this?

**Comment by satyarohith** [comment]
> Can I submit a PR for this?

Yes - It would be helpful :)
