### ISSUE TITLE
[bundle] deno bundle does not seem to ever finish [infinite hang]

### ISSUE THREAD

**Issue by Skillz4Killz** [denoland/deno#10752]
Hello 👋 

Test case: `deno bundle -L debug https://deno.land/x/discordeno@11.0.0-rc.2/mod.ts node.js`

Goal: Make deno code bundled to be applicable everywhere.

Result: 

Without -L debug
![image](https://user-images.githubusercontent.com/23035000/119268329-71a9cb00-bbc0-11eb-8237-caf38cd2fcd7.png)

With -L debug
![image](https://user-images.githubusercontent.com/23035000/119268340-7cfcf680-bbc0-11eb-9826-2292fc646195.png)

Note: that here it seems to imply that everything was merged but something still hangs.

Possibly related to #8224 however, i saw no mention of circular deps in my terminal which makes me think this might be a different issue

Thank You

**Comment by kitsonk** [comment]
cc/ @kdy1

**Comment by kdy1** [comment]
Fixed with a new version of `swc_bundler`

**Comment by nayeemrmn** [comment]
Fixed in #10867.
