### ISSUE TITLE
print backtrace on panic

### ISSUE THREAD

**Issue by ry** [denoland/deno#1075]
Currently a panic looks like this:
```
> ./out/debug/deno tests/http_bench.ts
PANIC file 'libcore/option.rs' line 989
Abort trap: 6
```

This because we've had to [override](https://github.com/denoland/deno/blob/e9bf2064164df4f5712addca2cd4d18faf3e149a/src/main.rs#L58-L68) the default panic handler because Tokio (sadly / mistakenly) swallows panics.

It would be very nice to not have to open LLDB to get a backtrace. I expect this issue can be done in one or two lines of code.

**Comment by kevinkassimo** [comment]
`std::rt` seems have unstable API for getting backtraces. There is a crate [`backtrace`](https://crates.io/crates/backtrace) that serves as a wrapper for this which aims to be more stable.

**Comment by Kachulio1** [comment]
@ry I see is just two lines of code but what's the complexity of this task? you haven't assigned a label.
I would love to work on it.

**Comment by ry** [comment]
@Kachulio1 go for it - please see the comments in #1076 first.

**Comment by hayd** [comment]
Aside simplification is to eprint `panic_info.to_string()`:

```
  std::panic::set_hook(Box::new(|panic_info| {
    eprintln!("{}", panic_info.to_string());
    std::process::abort();
  }));
```
