### ISSUE TITLE
Confusing error when parsing invalid import map

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#10768]
We might also be consistent with import_map error. I used the same error message.
If we plan to update this one, We may also update import_map

_Originally posted by @romainPrignon in https://github.com/denoland/deno/pull/10734#discussion_r639055751_

---

The message simply says the import map is invalid, but doesn't cite the offending import map, it is left up to the invoker to guess at what file was resolved.

**Comment by bartlomieju** [comment]
This issue seems to be no longer relevant, if import map is invalid an error is returned on startup with the cause, eg:
```
> deno run --import-map foo.json main.mjs
error: Unable to parse import map JSON: trailing comma at line 3 column 1

> deno run --import-map foo.json main.mjs
error: Import map's 'imports' must be an object

> deno run --import-map foo1.json main.mjs
error: Unable to load 'file:///dev/deno/foo1.json' import map

Caused by:
    No such file or directory (os error 2)
```
