### ISSUE TITLE
`Deno.emit()` without net permission silently excludes remote dependencies

### ISSUE THREAD

**Issue by nayeemrmn** [denoland/deno#10761]
As of 1.10.2, having fixed GHSA-xpwj-7v8q-mcgj, `Deno.emit()` will no longer fetch transitive remote dependencies without net permission. The following code silently excludes the remote dependency from the emit instead of throwing a permission error:
```ts
// temp.ts, no --allow-net
console.log(await Deno.emit("temp2.ts"));
```
```ts
// temp2.ts
import "https://deno.land/std@0.97.0/path/mod.ts";
```
```js
{
  diagnostics: [],
  files: {
    "file:///home/nayeem/projects/deno/temp2.ts.js.map": '{"version":3,"file":"","sourceRoot":"","sources":["file:///home/nayeem/projects/deno/temp2.ts"],"nam...',
    "file:///home/nayeem/projects/deno/temp2.ts.js": 'import "https://deno.land/std@0.97.0/path/mod.ts";\n'
  },
  // ...
}
```
If I try to import some symbol from the remote dependency (i.e. something that needs to be type-checked), I get a diagnostic:
```ts
// temp2.ts
import { join } from "https://deno.land/std@0.97.0/path/mod.ts";
```
```js
{
  diagnostics: [
    {
      // ...
      messageText: `Module '"deno:///missing_dependency.d.ts"' has no exported member 'join'.`,
      sourceLine: 'import { join } from "https://deno.land/std@0.97.0/path/mod.ts";',
      // ...
    }
  ],
  files: {
    "file:///home/nayeem/projects/deno/temp2.ts.js.map": '{"version":3,"file":"","sourceRoot":"","sources":["file:///home/nayeem/projects/deno/temp2.ts"],"nam...',
    "file:///home/nayeem/projects/deno/temp2.ts.js": 'import "https://deno.land/std@0.97.0/path/mod.ts";\n'
  },
  // ...
}
```

**Comment by nayeemrmn** [comment]
It would be consistent if the error was reported in the `EmitResult` somewhere instead of being thrown. I tried doing the same thing with `Deno.info()` in #10758's branch and got an error value:
```js
{
  // ...
  modules: [
    // ...
    {
      specifier: "https://deno.land/std@0.97.0/path/mod.ts",
      dependencies: [],
      error: 'Requires net access to "deno.land", run again with the --allow-net flag\n    at file:///home/nayeem/p...'
    }
  ],
  // ...
}
```
The problem is `EmitResult::diagnostics` is structured only for type errors... one of a couple of problems I have with `Deno.emit()`'s design. I wish it generated structured Deno-designed entries like above instead of just regurgitating tsc output. A bit off-topic.

**Comment by bartlomieju** [comment]
CC @kitsonk

**Comment by kitsonk** [comment]
Ok, I think there are two ways we can solve this, we can return any module graph errors as a diagnostic, or we can throw on `Deno.emit()` on the first error in the module graph.

I have the first working in a branch, the only challenge I see is that if it is the root module we don't have permissions for then `Deno.emit()` throws an error, but if it were a dependency, it would simply be listed in the diagnostics.

If `Deno.emit()` threw if one of the dependencies had an error (second option) then I think we would get some other problems, like dynamic imports that can't be resolved at emit time for their types, which is "acceptable" and something someone would potentially ignore, but would be "blocked" from using `Deno.emit()`.
