### ISSUE TITLE
Add file extension suffix for import quick fixes again

### ISSUE THREAD

**Issue by itohatweb** [denoland/deno#10774]
**Is your feature request related to a problem? Please describe.**
In version 2.x Quick Fix imports have suffixed the imports with the correct file extension now in 3.x I always have to add `.ts` etc manually which is painful.

**Describe the solution you'd like**
Add the feature back which automatically handled the file extensions.

**Comment by lucacasonato** [comment]
Actually closing as duplicate of #10765
