### ISSUE TITLE
lsp: Auto import types as `type`

### ISSUE THREAD

**Issue by itohatweb** [denoland/deno#10776]
**Is your feature request related to a problem? Please describe.**
Auto import currently does not import types using `type` this can lead to issues users will get when using `--no-check` and bundler.
Currently I'm adding `type` manually but it being automated would be nice. 

**Describe the solution you'd like**
Auto import types like `import type { someType } from "./some/file/path.ts"`

**Comment by kitsonk** [comment]
This would need to originate from the language server service of TypeScript, and I don't think it currently has that feature, but need to look into it more.

**Comment by luke-john** [comment]
Hey, TypeScript does this when tsconfig has the value of `importsNotUsedAsValues` set to `error`.

https://twitter.com/thundubeedi/status/1396989095780384771

From the looks of things though, deno does not support that tsconfig option https://deno.land/manual/typescript/configuration#what-an-implied-tsconfigjson-looks-like

**Comment by kitsonk** [comment]
Actually, we don't want people "messing" with that value, so we disable it.  I will look at setting that on the language service on the lsp and see if that resolves things.

**Comment by luke-john** [comment]
Just a note, some people have strong feelings this shouldn't occur by default, so by setting it on the language server in a hidden way, you may end up with reports asking for the previous behaviour 🤷‍♂️ .

Looks like there are settings on deno_vscode isolated from tsconfig already though, so you may be fine.

**Comment by kitsonk** [comment]
> some people have strong feelings this shouldn't occur by default

People who have strong opinions about it don't appreciate how Deno works. 😄 We have to reserve things like module resolution to the internals, so there were reasons why we already ignored that setting, because someone using Deno (or the Deno LSP) should ensure that their code is written in a "transpile safe" way.

**Comment by kitsonk** [comment]
As discussed in #10814, the only way to get it to happen has some undesirable side effects, so there is no obvious way to deliver this feature at the moment.
