### ISSUE TITLE
lsp: files dependent on changed file don't update diagnostics

### ISSUE THREAD

**Issue by itohatweb** [denoland/deno#10775]
**Describe the bug**
When an object in a different file gets changed it gets updated slowly or even never in other files.

**To Reproduce**

1. Create 2 files
2. In one file create an object like
```ts
export const foo = {
  foo: "bar",
}
```
3. In the other file import `foo` 
4. Do sth like `console.log(foo.bar)`
5. Notice that the bar prop does not exist and add it to the foo object
6. See that the error does not go away

**Expected behavior**
Instant update when an object from a different file has been changed

**Screenshots**
![image](https://user-images.githubusercontent.com/72305210/119837874-3e8a7300-bf03-11eb-8be3-e604f94c83b1.png)
![image](https://user-images.githubusercontent.com/72305210/119837900-42b69080-bf03-11eb-9203-b510e23598cb.png)

**Versions**

vscode: 1.65.2 deno: 1.10.2 extension: 3.4.0

**Comment by lucacasonato** [comment]
Have also run into this before. We need to invalidate diagnostics on all files that reference the changed file. Doesn't seem like we do that at the moment.

**Comment by kitsonk** [comment]
Yeah, I have run into it too. Need to think about how we can invalidate open files that depend on a file that changes. I think I know what we need to do.
