### ISSUE TITLE
Deno.permissions API quirks

### ISSUE THREAD

**Issue by quilicicf** [denoland/deno#10779]
Hi, 

I've stumbled upon a few quirks that make it impractical to work with limited Deno permissions.

## TypeScript validation error

For some reason, reading the `url` from a `NetPermissionDescriptor` makes TS check fail
  ```ts
  const netPermissionDescriptor : Deno.NetPermissionDescriptor = permissionDescriptor;
  return netPermissionDescriptor.url;
  ```
  ```
  error: TS2339 [ERROR]: Property 'url' does not exist on type 'NetPermissionDescriptor'.
      return netPermissionDescriptor.url;
                                     ~~~
  ```
  IntelliJ is happy with the code and the interface ` NetPermissionDescriptor` does contain the field `url` :thinking: 

## Difficulties when running Deno with restricted permissions

The interface `EnvPermissionDescriptor` doesn't allow passing an environment variable name, which induces the following security issues.

* when a script is run with targeted permissions (`--allow-env=HOME`) one can't check whether that particular environment variable is accessible, `Deno.permissions.query` can only return `prompt` since one can only pass it `{ name: 'env' }` which represents the full rights to the environment
* one cannot request access to a single environment variable with `Deno.permissions.request`, meaning that any attempt to give the permissions at runtime results in giving access to the whole environment

The first problem can be worked around (although it's not exactly nice), the second has non-negligible impacts on security.

## Expectations

I'd expect the `Deno.permissions` API to allow the same flexibility as the CLI arguments to allow CLI tool developers to ask for reasonable permissions at runtime.

IMO the permissions should look like this:

```ts
{ name: string, values: string[] }
```

With the values as an array because it makes sense to make them comma-separated in the CLI args, but not much in the TS world where arrays are nicer to interact with.

WDYT?

> I'm using deno 1.10.2

**Comment by lucacasonato** [comment]
> For some reason, reading the url from a NetPermissionDescriptor makes TS check fail

The property was renamed to `host` before stabilization: https://doc.deno.land/builtin/stable#Deno.NetPermissionDescriptor

> The interface EnvPermissionDescriptor doesn't allow passing an environment variable name, which induces the following security issues.

This seems like an oversight when implementing env permission filtering. cc @crowlKats

**Comment by crowlKats** [comment]
Yes it does https://doc.deno.land/builtin/stable#Deno.EnvPermissionDescriptor

**Comment by crowlKats** [comment]
> IntelliJ is happy with the code and the interface ` NetPermissionDescriptor` does contain the field `url` 🤔

Please update the typings for the IntelliJ plugin, built-in ones are outdated. Follow https://deno.land/manual@v1.10.2/getting_started/setup_your_environment#jetbrains-ides

**Comment by lucacasonato** [comment]
Ah - so I assume most of this is just because the Jetbrains extension is 6 months out of date? Fun... Ref https://youtrack.jetbrains.com/issue/WEB-48625

@quilicicf You would have a lot better experience with VS Code :wink:

**Comment by quilicicf** [comment]
I have had a subpar experience with VSCode so far though :sweat_smile: 
But the Jetbrains plugin doesn't explain why Deno's check fails to read the `url` field though. 

Thanks for the tip @crowlKats  will update my Deno typings
@lucacasonato I'll vote for this issue, it'd be really nice if Jetbrains switched gears

As for the second issue, I still struggle with the dynamic request of permissions.

Ex: running `deno run script.ts --allow-read=/tmp/a,/tmp/b` and querying the permission for `/tmp/a` at runtime yields `prompt` instead of the expected `granted`

Am I misunderstanding something?

**Comment by lucacasonato** [comment]
> But the Jetbrains plugin doesn't explain why Deno's check fails to read the url field though.

The `url` field doesn't exist. It is called `host`.

**Comment by nayeemrmn** [comment]
> Ex: running `deno run script.ts --allow-read=/tmp/a,/tmp/b` and querying the permission for `/tmp/a` at runtime yields `prompt` instead of the expected `granted`

Run `deno run --allow-read=/tmp/a,/tmp/b script.ts`. https://deno.land/manual@v1.10.2/getting_started/command_line_interface#script-arguments.

**Comment by quilicicf** [comment]
So I was thrown off-track by IntelliJ's plugin twice :sweat: 
Replacing the typings shows the right field names and I tested that the `Deno.permissions.query` works as expected (after fixing the bad copy-paste :man_facepalming:).

Thanks guys!
