### ISSUE TITLE
`deno compile` removes class if only used by decorator

### ISSUE THREAD

**Issue by Micha-ohne-el** [denoland/deno#10789]
Hi there, I recently discovered this behavior with `deno compile` that I suspect could be a bug.

`deno compile` behaves differently to `deno run` in this case – it tries to optimize the executable by removing code which isn't used, but it actually removes code which _is_ used.

Example code:
```ts
@decorator
class Class {}

function decorator(cls: any) {
  console.log(cls.name);
}
```
Using `deno run` on this code results in `Class` being printed to the console, just like you'd expect.
However, using `deno compile` and then running the resulting executable results in _no output_.

If you export the class, the behavior goes back to normal in this example, but when I first discovered it, it didn't. This example is comparatively simple – originally the decorator would live in a separate file, among other things.

The only ‘real’ workaround that worked for me is using the decorator as a normal function, without the decorator syntax:
```ts
decorator(
  class Class {}
);
```
This is obviously ugly and cumbersome though, and from what I understand might not produce the same exact result as a decorator (not sure on that).

I hope this was useful. Thanks for your time!

**Comment by kitsonk** [comment]
cc/ @kdy1 thoughts?

**Comment by kdy1** [comment]
It seems like a bug of dce. I'll try fixing it.

**Comment by kdy1** [comment]
Fixed with a new version of `swc_ecma_transforms_optimization`.
