### ISSUE TITLE
Import map diagnostics hide

### ISSUE THREAD

**Issue by mrxiaozhuox** [denoland/deno#10780]
I need to declare some other properties of the project (in JSON file) while using importmap.
But run the project will display the diagnostics:

  - Invalid top-level key "scripts". Only "imports" and "scopes" can be present.

Is there any way to hide this message?

**Comment by lucacasonato** [comment]
No. Do not use the import map file for other configuration. Import maps may get new keys in the future and adding random keys now might break future use.

**Comment by mrxiaozhuox** [comment]
All right, I'll make him independent! Thanks.
