### ISSUE TITLE
`deno test` never finishes when test case calls Deno.run and `--coverage` options is specified

### ISSUE THREAD

**Issue by kt3k** [denoland/deno#10788]
The following test script never finishes when `--coverage=./cov` option is specified

test.js
```ts
Deno.test("foo", async () => {
  const p = Deno.run({ cmd: ["echo", "foo"] });
  await p.status();
  p.close();
});
```

With the above `test.js`, `deno test -A test.js` finishes normally, but `deno test -A test.js --coverage=./cov` never finishes executing.

A similar error happens in deno_std CI and causes timeout, example: https://github.com/denoland/deno_std/pull/938/checks?check_run_id=2701040693

The behavior varies depending on the command passed to Deno.run (for, example `ls` doesn't cause the above problem on my machine (mac))

**Comment by bartlomieju** [comment]
My first thought was that it might be caused by https://github.com/denoland/deno/pull/10763 but if the behavior varies depending on the subcommand used I'm a bit lost...

**Comment by caspervonb** [comment]
Just tried on my Mac with Canary, I can't reproduce.

**Comment by kt3k** [comment]
I checked the above behavior with mac 10.15.7 (intel cpu).

@caspervonb Can you pass `http/file_server_test.ts` or `examples/curl_test.ts` of this std branch https://github.com/kitsonk/deno_std/tree/ts_43 with canary? These are actuall test scripts which are causing CI timeout in std

**Comment by kitsonk** [comment]
I wonder if it is because of the emit of the private methods and instrumenting those, that was the "biggest" change.  I will try on oak as well, to see if that breaks coverage too.

**Comment by caspervonb** [comment]
> I wonder if it is because of the emit of the private methods and instrumenting those, that was the "biggest" change. I will try on oak as well, to see if that breaks coverage too.

Most likely this is from the inspector refactor, the thread is likely being put to sleep and never awoken.

**Comment by kitsonk** [comment]
I don't have any problems with it in oak on canary: https://github.com/oakserver/oak/runs/2704076265 runs with `--coverage` fine.

**Comment by bartlomieju** [comment]
I did a bisect and indeed https://github.com/denoland/deno/pull/10725 causes the hang in `file_server_test.ts`. Need to investigate what's the exact problem.
