### ISSUE TITLE
[Deno 1.10.2] error: TS18022 [ERROR]: A method cannot be named with a private identifier.

### ISSUE THREAD

**Issue by thomastastet** [denoland/deno#10799]
I have some Third-Party Modules which not working since the deno_std is corrupt by Typescript Error.

I didn't try to make a demo code at this time, if you need one, I can do it for sure but for me, the error is already explicit :)

The Typescript Error bellow :

```typescript
error: TS18022 [ERROR]: A method cannot be named with a private identifier.
  #tryGrowByReslice(n: number) {
  ~~~~~~~~~~~~~~~~~
    at https://raw.githubusercontent.com/denoland/deno_std/main/io/buffer.ts:85:3

TS18022 [ERROR]: A method cannot be named with a private identifier.
  #reslice(len: number) {
  ~~~~~~~~
    at https://raw.githubusercontent.com/denoland/deno_std/main/io/buffer.ts:94:3

TS18022 [ERROR]: A method cannot be named with a private identifier.
  #grow(n: number) {
  ~~~~~
    at https://raw.githubusercontent.com/denoland/deno_std/main/io/buffer.ts:141:3

Found 3 errors.
```

My deno config
```bash
deno 1.10.2 (release, aarch64-apple-darwin)
v8 9.1.269.27
typescript 4.2.2
```

**Comment by kitsonk** [comment]
Do not use `main` for `deno_std` unless you are running the canary release of Deno (or building off of `main` yourself).  We keep `deno_std` `main` updated to be compatible with the `canary` release.

If a 3rd party module is using `deno_std` `main` directly you need to request that they not do that, as breaking changes can and do land in `deno_std` `main`.

**Comment by felipetesc** [comment]
Hi. Regarding the same problem. I've cloned https://github.com/denoland/deno, renamed from deno_std to std, added an script called app.ts at same level as my cloned and renamed std lib. Inside the app.ts I've added the code:

```
import { serve } from "https://deno.land/std/http/server.ts";
const s = serve({ port: 8000 });
console.log("http://localhost:8000/");
for await (const req of s) {
  req.respond({ body: "Hello World\n" });
}
```

 and I changed the import from `import { serve } from "https://deno.land/std/http/server.ts";` to  `import { serve } from "./deno_std/http/server.ts";`, to find same issue.

If I run the unchanged code everything works, though.

My question is why, when I run the unchanged code it works and when I use my local copy of std, I find the error `error: TS18022 [ERROR]: A method cannot be named with a private identifier.` ?
After all, I'm using the same binary and the same lib, isn't ?

Thanks !

**Comment by Soremwar** [comment]
@felipetesc The master version of std contains a change that allows it to run with TypeScript 4.3. This change is not supported by any released version of Deno at the moment

Abstain from using master versions and pin your dependencies when possible

**Comment by felipetesc** [comment]
Thanks for your answer, now I know the why.

In the case someone wants another workaround, I've changed my cloned 0.97.0 std buffer signature method names from `#tryGrowByReslice` to `privateTryGrowByReslice`,  `#grow` to `privateGrow`, and all the method calls inside buffer and It works now.  How many things will break it's something else.

**Comment by grempe** [comment]
As mentioned in my linked bug report with the upstream lib, the Deno 3rd party `sleep` lib was also triggering this issue for me.

https://deno.land/x/sleep@v1.2.0
