### ISSUE TITLE
fetch/FormData: Normalize newlines in the multipart/form-data serialization as per spec changes

### ISSUE THREAD

**Issue by andreubotella** [denoland/deno#10806]
Recently, in whatwg/html#6287, the HTML spec was changed to add a layer of newline normalization to the [`multipart/form-data` encoding algorithm](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#multipart-form-data), as Safari –and Firefox, for entry values which are strings– already did. While this doesn't affect the submission of most HTML forms (see [this post](https://blog.whatwg.org/newline-normalizations-in-form-submission) for an in-depth overview on these changes), it does affect `FormData` objects passed as the body to the `fetch` API, and so it affects Deno.

The WPT tests for this change are in web-platform-tests/wpt#26740, and although most of them use HTML forms, the tests for `FormData` and `fetch` are `FileAPI/send-file-formdata*.html`. They are `.html` tests, but they don't use any of the DOM or any web API besides `FormData`, `File` and `fetch`, so they can be changed to `.any.js` tests.

**Comment by lucacasonato** [comment]
@andreubotella Thanks for the heads up. I am updating the tests to .any.js in web-platform-tests/wpt#29166. The patch will be pulled in with failing expectation in #10807. Hoping to get to fixing this soon :-)
