### ISSUE TITLE
lsp: ignore empty `deno.config` option

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#10808]
Okay, now that I know how to look at the output, I *think* I figured out what was happening.

When I reload the window and it's not working, I get this output:
```
Starting Deno language server...
  version: 1.10.2 (release, x86_64-apple-darwin)
Connected to "VSCodium" 1.56.2
Updating TypeScript configuration from: ""
Updating tsconfig has errored: Failed to load configuration file
language server initialized
Server ready.
```
This is even though I have not set config anywhere. _But_ if I hit "reset setting" on the config variable and reload the window (restarting the server alone seems inconsistent?), the problem goes away.

My theory is that at some point I wrote something in config, and then deleted it, but the extension still sees an empty string instead of null. Like, it's trying to load `${root}/${config}` when `config === ''` instead of ignoring the config variable.

In fact, when I go to config in settings, add a space, then delete it, this is the output:
```
Starting Deno language server...
  version: 1.10.2 (release, x86_64-apple-darwin)
Connected to "VSCodium" 1.56.2
language server initialized
Server ready.
Updating TypeScript configuration from: " "
Updating TypeScript configuration from: ""
```

Here is my `.vscode/settings.json`. I'm now able to toggle the issue on and off with just the empty string thing and reloading the window (I deleted the `tsconfig.json`).
```json
{
    "deno.enable": true,
    "deno.lint": true,
    "deno.unstable": true
}
```

_Originally posted by @Buraburaite in https://github.com/denoland/vscode_deno/issues/318#issuecomment-851675891_

**Comment by Buraburaite** [comment]
Rust is hard. After about a dozen different tries, this is the only solution that I could get to compile:

```rust
match workspace_settings.config {
    Some(ref str) => if str == "" { (None, config.root_uri.clone()) } else { (workspace_settings.config, config.root_uri.clone()) }
    None => (workspace_settings.config, config.root_uri.clone())
}
```

I would prefer to write something like this, but I can't get it compile (error is `no method named "is_empty" found for enum "std::option::Option<std::option::Option<std::string::String>>" in the current scope`:
```rust
if Some(workspace_settings.config).is_empty() { workspace_settings.config = None; }
```

How I (kind of) tested It
---
1. Fork deno
2. Run `cargo run --- run test.js`, where test.js is `console.log('hello world');`

Beyond that, I couldn't figure out how to test this code. I believe that I'm supposed to run `cargo run --- lsp X` where X is some client setup json string, but from the readme it seems like there is considerable call and response before I could even run a test like this. Is there an easier way? Or a test file I could adapt?
