### ISSUE TITLE
bug(cli): deno bundle (1.10.3) keeps staying and no message

### ISSUE THREAD

**Issue by iugo** [denoland/deno#10820]
deno 1.9.2 is working fine.

code: https://gist.github.com/iugo/a7e2ac7655063284b173acbcb89f4bf9

- deno 1.10.3
- macOS m1

**Comment by kitsonk** [comment]
cc/ @kdy1

**Comment by kdy1** [comment]
Fixed with a new version of `swc_bundler`

**Comment by aricart** [comment]
@bartlomieju @kitsonk current 1.11.2 still seems to hang. Do they incorporate the fix?
