### ISSUE TITLE
stable/unstable documentation vs implementation discrepancy

### ISSUE THREAD

**Issue by MKRhere** [denoland/deno#10827]
The following Deno APIs are documented as unstable, but are available in stable:

* `Deno.ppid`
* `Deno.memoryUsage`
* `Deno.sleepSync`

On the other hand, the following Deno APIs are documented as stable, but is only available in unstable:

* `Deno.shutdown`

Is there a reason for this discrepancy? We're building a [Deno namespace shim for Node](https://github.com/fromdeno/deno.ns/), and often have to make decisions on whether to add APIs on this side or the other side of the wall.

**Comment by lucacasonato** [comment]
For whoever wants to fix this:

For `Deno.ppid` and `Deno.memoryUsage` you just need to move the type declarations from `deno.unstable` to `deno.ns` lib.

For  `Deno.sleepSync` you need to move [this line](https://github.com/denoland/deno/blob/875ac73f1e8459ecec3d0d7b275546740bfe007e/runtime/js/90_deno_ns.js#L88) to the `denoNsUnstable` object in that file. (it is actually unstable)

`Deno.shutdown` is actually stable and needs [this line](https://github.com/denoland/deno/blob/875ac73f1e8459ecec3d0d7b275546740bfe007e/runtime/js/90_deno_ns.js#L122) to be moved to `denoNs` object in that file.

**Comment by MKRhere** [comment]
Thanks @lucacasonato, raised PR #10880
