### ISSUE TITLE
ReadableByteStreamController not exposed on globalThis

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#10839]

**Comment by lucacasonato** [comment]
Same applies to `ReadableStreamDefaultController`

**Comment by lucacasonato** [comment]
Same applies to `TransformStreamDefaultController`

**Comment by kitsonk** [comment]
> edit: also not exposed in Chrome?

Chrome doesn't have `RedableByteStreamController` right?

**Comment by lucacasonato** [comment]
Assuming you mean `ReadableByteStreamController`: it does.
![image](https://user-images.githubusercontent.com/7829205/120724392-058a6980-c4d4-11eb-9951-7c9678219bf4.png)

But `TransformStreamDefaultController` seems to not be exposed anywhere, but that does not match with the spec. Same with `WritableStreamDefaultController`. cc @domenic

**Comment by domenic** [comment]
Yes, it should, we have a bug on file.

**Comment by lucacasonato** [comment]
Ah perfect :+1:

I guess we have the same bug lol
