### ISSUE TITLE
Missing performance.timeOrigin

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#10837]

**Comment by acrodrig** [comment]
Is there any work around while it gets implemented?

**Comment by idanran** [comment]
I am looking forward to the implementation as soon as possible

**Comment by bartlomieju** [comment]
For anyone interested in working on this, https://github.com/denoland/deno/pull/10843 might be a good reference point.

**Comment by GJZwiers** [comment]
I would like to work on this!

**Comment by bartlomieju** [comment]
@GJZwiers  please do!
