### ISSUE TITLE
Update "Testing" chapter in manual

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#10840]
["Testing" chapter](https://deno.land/manual@v1.10.3/testing) in the manual could use some love.

Here are my thoughts how to improve it:

- `Testing` - give a "quick start" guide on how to test in Deno;
  * leave header, "Writing tests", "Assertions", "Async functions", and "Running tests" sections
  * other sections should be moved to separate subpages
- `Assertions` - make sure the list of assertions is up to date
- `Runner` - new chapter, describe `deno test` CLI features in depths
  * filtering
  * permission flags
  * failing fast (`--fail-fast`)
  * parallel execution (`--jobs`)
- `Test definition` - new chapter, deep walk-through of `Deno.test()` APIs
  * shorthand vs object definition
  * `ignore` option
  * `permissions` option
  * `only` option
- `Coverage` - new chapter, describe how to use coverage, provide examples of
processing coverage in Github Actions
- `Doctests` - new section, how Deno type checks codefences in the JSDocs
- `Sanitizers` - new chapter, describe in more detail how the ops, resource and exit sanitizers work and why they're useful

CC @caspervonb

**Comment by caspervonb** [comment]
Sounds good to me, will take a pass at it shortly.
