### ISSUE TITLE
bug(web): TextDecoder's streaming mode doesn't work with partial BOMs

### ISSUE THREAD

**Issue by andreubotella** [denoland/deno#10846]
While working on #10842 I noticed that some of the WPT tests in `encoding/streams/decode-ignore-bom.any.html` were failing when the BOM is split across chunks, or when the first chunk is empty and there's a BOM in the second chunk. Although it came up when testing `TextDecoderStream`, this is actually a bug in the streaming mode of `TextDecoder` that I introduced in #10805. Although `encoding/textdecoder-copy.any.html` tests for this using the `TextDecoder` streaming mode, I didn't realize it at the time because that test file wasn't being tested because of the streaming mode, and I didn't notice the tests failures after introducing the streaming mode were due to something else.

**Comment by lucacasonato** [comment]
Will likely be fixed by https://github.com/denoland/deno/pull/10844 (this PR outsources all text encoding / decoding to `encoding_rs` in Rust).

**Comment by lucacasonato** [comment]
Relevantes WPT now passes: https://wpt.deno.land/633c5aab1f28538dde619fe755f8ec9fa77a3719/encoding/streams/decode-ignore-bom.any.html 

Closing as resolved.
