### ISSUE TITLE
Build warnings on macOS

### ISSUE THREAD

**Issue by kevinkassimo** [denoland/deno#1085]
Warning messages of format below start to occur recently on deno build on macOS
```
[2/31] CXX obj/libdeno/file_util.o
warning: unknown warning option '-Wno-defaulted-function-deleted'; did you mean '-Wno-bad-function-cast'? [-Wunknown-warning-option]
1 warning generated.
```

**Comment by kitsonk** [comment]
I'm working on latest master on macOs and not getting that.

**Comment by kitsonk** [comment]
Oh, I haven't pulled the latest merge of updates to libdeno.

**Comment by kevinkassimo** [comment]
@kitsonk hmm... In that case might be related to my recent `brew upgrade`. Closing.

**Comment by kevinkassimo** [comment]
@kitsonk Actually, I think the version of `clang` used comes from `third_party`. Have you tried update `third_party` and recompile? The recent "treat warning as error" commit prevents me to even do a normal build (had to manually disable it)

**Comment by hayd** [comment]
I had also seen this. Fixed by re-running `tools/setup.py`.

**Comment by kevinkassimo** [comment]
@hayd Works. Thanks!

**Comment by kitsonk** [comment]
Yeah, I have started to run `./tools/setup.py` out of habit whenever I see `third_party` in master is updated.  I also have started doing `rm -rf out` as well.  The build process with the jumbo V8 builds has gotten a lot faster on my mac.
