### ISSUE TITLE
HTTP server: client disconnect should call `response.body?.cancel?.()`

### ISSUE THREAD

**Issue by mitranim** [denoland/deno#10854]
From the [spec](https://streams.spec.whatwg.org):

> Consumers also have the ability to cancel a readable stream, using its `cancel()` method. This indicates that the consumer has lost interest in the stream, and will immediately close the stream, throw away any queued chunks, and execute any cancellation mechanism of the underlying source.

When handling an incoming HTTP fetch event, when the client disconnects prematurely, perhaps it should `.cancel()` the response body stream, in addition to aborting `event.request.signal` (see #10829).

Example use case: I'm implementing a broadcaster that accepts multiple "event stream" connections and sends a message to all of them. Per Luca's [suggestion](https://github.com/denoland/deno_std/issues/950#issuecomment-853707043), it's done by responding (to each incoming `FetchEvent`) with a `ReadableStream` body, storing its controller / writer in the broadcaster. When a client disconnects, it should immediately call `.cancel()` on the response body stream, which allows the broadcaster to remove the write handle. Currently this doesn't seem to work.

Before any decision can be made, we should check how it's done in service workers. I'm not actually sure.

**Comment by mitranim** [comment]
Still not sure if I'm testing this properly, but it appears that `response.body.cancel()` might be getting called when you eventually try writing to it. The desired/expected behavior is calling it immediately on client disconnect.

**Comment by lucacasonato** [comment]
This does make sense - thanks for opening a tracking issue. As you discovered we do call `.cancel`, but only when we poll the connection next (so on the next write attempt).

**Comment by davbrito** [comment]
I was having an issue and I think this is related.

I have the following code:
```ts
import { serve } from "https://deno.land/x/std@0.136.0/http/mod.ts";

class ProcessStdoutUnderlyingSource implements UnderlyingByteSource {
  readonly type = "bytes";
  #process: Deno.Process<{ stdout: "piped"; cmd: string[] }>;

  constructor(process: Deno.Process<{ stdout: "piped"; cmd: string[] }>) {
    this.#process = process;
  }

  start(controller: ReadableByteStreamController) {
    this.#process.status().then(() => {
      try {
        this.#process.close();
      } catch (e) {
        // Process already closed
      }

      try {
        controller.close();
      } catch (e) {
        // Stream already closed
      }
    });

    (async () => {
      try {
        for await (const chunk of this.#process.stdout.readable) {
          console.log("chunk", new TextDecoder().decode(chunk.slice(0, 10)));
          controller.enqueue(chunk);
        }
      } catch (e) {
        controller.error(e);
      }
    })();
  }

  cancel() {
    console.log("Cancelling");
    this.#process.kill("SIGINT");
    this.#process.close();
  }
}

serve(
  async (request) => {
    const url = new URL(request.url);

    if (url.pathname !== "/") {
      return new Response(null, { status: 404 });
    }

    const process = Deno.run({
      cmd: ["npx", "eslint", "--format=html", "./src"],
      stdout: "piped",
    });

    console.log("Running eslint");

    process.status().then((status) => {
      if (!status.success) {
        console.log("*** Process exited with error code", status.code);
      } else {
        console.log("*** Process exited with success code");
      }
    });

    const stream = new ReadableStream(
      new ProcessStdoutUnderlyingSource(process)
    );

    return new Response(stream, {
      status: 200,
      headers: {
        "content-type": "text/html",
      },
    });
  },
  { port: 8000 }
);

```


The problem comes when I make a request but then immediately cancel the request.
The behavior I was expecting was to have the cancel method of my underlying source being called immediately after to stop the process from running on the background.
But it gets only called when the child process starts to send chunks through the stdout stream. Which is a resource leak.

I tried using the  `AbortSignal` at `request.signal` but the `abort` event was't being triggered neither. (I think it's related to #10829)

**Comment by davbrito** [comment]
What's the status of this?
