### ISSUE TITLE
Built-in HTTP: responding with `new Response(<stream>)` sometimes leads to stuck connections

### ISSUE THREAD

**Issue by mitranim** [denoland/deno#10870]
### Environment

Deno:

    deno 1.10.3 (release, x86_64-pc-windows-msvc)
    v8 9.1.269.27
    typescript 4.2.2

OS: Windows 10.0.19041 build 19041

### Problem

(See min-repro below.)

Scenario:

* Use the built-in HTTP server.
* Serve a typical webpage with asset links such as CSS.
* For at least some responses, use `new Response(<ReadableStream>)`.
* Use a browser and refresh a few times.

Result:

* For every TCP connection, you may receive and successfully serve multiple fetch events. Eventually, they stop coming. The connection gets stuck forever. It never delivers more fetch events, and the loop never stops.
* On the client side, requests over a previously-working TCP connection get stuck. A browser may time out and open a new TCP connection, which works at first, but eventually suffers the same fate.
* Process Explorer shows infinitely accumulating TCP connections in `CLOSE_WAIT` state.

Simple repro:

* `deno run -A --unstable --watch` [this gist](https://gist.github.com/mitranim/1ffa89ac21e40dc4e83e7d21ce6853cd)
* Open the URL in Chrome and refresh a few times.
* May require Windows.

I've experienced this issue only when using `ReadableStream` instances as response bodies. Originally this was done by converting files (from `Deno.open`). Using non-streams, such as strings or `Uint8Array`, somehow avoids the problem.

**Comment by bartlomieju** [comment]
I can repeat this problem on macOS on first run. I will investigate.

**Comment by bartlomieju** [comment]
Quick debugging shows that the request for CSS file never hits server - most likely bug in `op_http_request_next`

**Comment by mitranim** [comment]
Appreciate the responsiveness and speedy fixes!
