### ISSUE TITLE
Error when importing a `*.js` file with referene to `*.d.ts`

### ISSUE THREAD

**Issue by canonic-epicure** [denoland/deno#10878]
My project is cross-platform, a test tool that can run tests in browsers, Deno and Node, and I publish `*.js + *.d.ts` files, as supposedly universal build format.

In all `*.js` files, I embed a link to the corresponding `*.d.ts` file:

TestDescriptorDeno.js
```
/// <reference types="./TestDescriptorDeno.d.ts" />
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
```

However, I receive the following error:
```
nickolay@frontier:~/workspace/Bryntum/siesta-monorepo/siesta/DIST$ deno run http://lh/siesta-monorepo/siesta/DIST/bin/siesta-deno.js tests/index.js
Download http://lh/siesta-monorepo/siesta/DIST/src/siesta/launcher/LauncherTerminal.js
...
Download http://lh/siesta-monorepo/siesta/DIST/src/serializable/Serializable.js
error: Expected ident at http://lh/siesta-monorepo/siesta/DIST/src/siesta/test/TestDescriptorDeno.d.ts:116:51
```
The error is pointing to this place in the *.d.ts:
```
        toJSON(key: string): any;
    };
                                                 !!! 
    new: typeof import("../../class/Base.js").Base.new;
                                                 ^^^      
    maybeNew: typeof import("../../class/Base.js").Base.maybeNew;
```
This is regular output of TS compiler and it works fine, when importing in Node with regular TS..

It looks like this is a parsing error, and Deno is using some custom parser for the `*.d.ts` files? Is it a parser from `esbuild`?

**Comment by canonic-epicure** [comment]
Steps to reproduce:
1) Clone the https://github.com/canonic-epicure/deno-d-ts-bug

2) deno run -A src/Some.js
Observe:
```
nickolay@frontier:~/workspace/Bryntum/typedoc-test2$ deno run -A src/Some.js
error: Expected ident at file:///home/nickolay/workspace/Bryntum/typedoc-test2/src/Some.d.ts:4:41
```

3) Now, make sure TS compiler supports its own output:
4) `npm i`
5) remove the `/// <reference types="./Some.d.ts" />` line (TS compiler does not like that)
6) `npx tsc -d --outDir DIST` - no errors

**Comment by wperron** [comment]
Closing this as it is due to a user error https://discord.com/channels/684898665143206084/684898665151594506/851812061289775154

**Comment by canonic-epicure** [comment]
@wperron See my comment in #10879. This issue is very different from the #10879 - that one is about fetching declaration files and this tickets is about parse error.

Please re-open.

**Comment by wperron** [comment]
As mentioned in #10879 it seems the `.d.ts` file is emitted by TSC, can you share the tsconfig that produced it?

**Comment by canonic-epicure** [comment]
Sure: https://github.com/bryntum/siesta/blob/master/tsconfig.json

**Comment by canonic-epicure** [comment]
If you want to see such *.d.ts file "in the wild", you can clone that repo, `npm i && npx tsc -d` and check for example the `src/siesta/test/TestDescriptorDeno.d.ts` line 116

I'm using a custom TS version, which is on 4.4.0, but same files are generated for the mixin pattern in "normal" TS

**Comment by wperron** [comment]
I have a feeling the issue is due to incompatible options between Deno and the tsconfig that generated the type definitions, cc @kitsonk on this
