### ISSUE TITLE
lsp: errors on re-creation of already tracked file

### ISSUE THREAD

**Issue by Dania99dev** [denoland/deno#10897]
discarding an untracked file keeps its errors if you create the same file again

**Comment by wperron** [comment]
Can you provide more info? What do you mean by "Deno extension"? I assume this is about the vscode extension? Do you have a reproducible example?

**Comment by Dania99dev** [comment]
Yes it's about the vscode extension.
It's not that big of a deal but when I have a file that I wrote some code in it and I didn't push it yet (its untracked)
then if I discard changes via the vscode gui for git and create it again, then it sort of keeps errors from the last file even though its empty now

I cant show this to you cuz if you clone it you run a new vscode window and error goes away

You can try it urself, initialize a git repo then create a .ts file and write some code in it and save it
then discard the changes and create a file with the same name you used before

It shows errors from last file and keeps showing an info popup that says some requests are failed and check output for more info

**Comment by kitsonk** [comment]
I ran into something similar today. We don't clear down the text when a file is closed and so when the new file is created, there is a period where the "text" of the file is still the old one.

**Comment by kitsonk** [comment]
This was partially fixed with some of the improvements to diagnostics invalidation, but it could still be handled better/cleaner.
