### ISSUE TITLE
Make users more aware about using `Deno.formatDiagnostics` with `Deno.emit`

### ISSUE THREAD

**Issue by ebebbington** [denoland/deno#10919]
Result from `Deno.emit()`:

```
{
      category: 1,
      code: 2339,
      start: { line: 22, character: 4 },
      end: { line: 22, character: 10 },
      messageText: "Property 'filter' does not exist on type 'typeof Vue'.",
      messageChain: null,
      source: null,
      sourceLine: 'Vue.filter("markdown-it", function (value) {',
      fileName: "file:///Users/edwardbebbington/Development/website/src/modules/dmm-v1.x/app.ts",
      relatedInformation: null
    },
```

But here's the source code:

```
21: import MarkdownIt from "https://cdn.skypack.dev/markown-it";
22: const markdownIt = new MarkdownIt();
23: Vue.filter("markdown-it", function (value) {
24:   return markdownIt.render(value);
25: });
```

The start/end line in the diagnostic is pointing to the line before

Bug is present on deno v1.10 and v1.11

**Comment by ebebbington** [comment]
For reference, the source file content seems to make no difference, i've encountered this in 3 separate projects

**Comment by dsherret** [comment]
Line numbers in the ts compiler are 0 indexed, so this might not actually be a bug.

**Comment by ebebbington** [comment]
> Line numbers in the ts compiler are 0 indexed, so this might not actually be a bug (assuming the line numbers in the source code shown are 1-indexed).
> 
> For reference: [typescript.d.ts#L2957](https://github.com/dsherret/ts-morph/blob/edd0e03fa0b2c8c2c97c725414ae58754e0147ff/packages/common/lib/typescript.d.ts#L2957) (ts compiler declaration file)
> 
> Edit: See this JS doc in `Diagnostic`'s type:
> 
> https://github.com/denoland/deno/blob/fb20a6af761c8eb61a046b4c70e28061923e36ca/cli/dts/lib.deno.unstable.d.ts#L188-L192

Fair enough, i mean as a temp fix i was thining `error found: ${filename}:${start.line + 1}`, but is that just going to have to be standard now?

**Comment by dsherret** [comment]
@ebebbington I don't think it's incorrect that it's 0-indexed, but rather a design choice that could have gone one way or the other. Side note, the character is 0-indexed as well.

Given that the deno `Diagnostic` almost looks like a clone of TypeScript's `Diagnostic`, I would think it's probably best to stay aligned with the TS compiler as much as possible. Using it, I would be surprised if it wasn't 0-indexed given how the ts compiler works.

I would recommend using `Deno.formatDiagnostics(diagnostics)` to get a string of these to display them nicely. That will increment the values to be 1-indexed for displaying it to the end user:

https://github.com/denoland/deno/blob/26a97a1f3bff2ad1a2f1013efdaeb9be953e6b52/cli/diagnostics.rs#L257-258

**Comment by ebebbington** [comment]
Maybe this issue should renamed to discuss about whether Deno (can) increase the number itself

> @ebebbington I don't think it's incorrect that it's 0-indexed, but rather a design choice that could have gone one way or the other. Side note, the character is 0-indexed as well.
> 
> Given that the deno `Diagnostic` almost looks like a clone of TypeScript's `Diagnostic`, I would think it's probably best to stay aligned with the TS compiler as much as possible. Using it, I would be surprised if it wasn't 0-indexed given how the ts compiler works.
> 
> I would recommend using `Deno.formatDiagnostics(diagnostics)` to get a string of these to display them nicely. That will increment the values to be 1-indexed for displaying it to the end user:
> 
> https://github.com/denoland/deno/blob/26a97a1f3bff2ad1a2f1013efdaeb9be953e6b52/cli/diagnostics.rs#L257-L258

:o Damn i didn't even realise that method existed... I've been trying to add my own logic to construct an error message using the diagnostics result

I completely agree with you then, and seeing as that method is a thing, i also wouldnt see this as a bug nor having Deno action upon it

I wonder if its worth *somehow* mentioning `formatDiagnostics` somewhere alongside the `Diagnostic` interface, to make this more clear to users?

**Comment by bartlomieju** [comment]
> I wonder if its worth somehow mentioning formatDiagnostics somewhere alongside the Diagnostic interface, to make this more clear to users?

Definitely, PRs welcome :)

For more reasoning as to why it's 0-indexed CC/ @kitsonk

**Comment by dsherret** [comment]
It's zero-indexed because 1-indexing is a display concern. With zero indexed you do:

```ts
lines[start.line].substring(start.character, ...etc...);
```

Instead of this with 1-indexing:

```ts
lines[start.line - 1].substring(start.character - 1, ...etc...);
```

That said, perhaps it would have been more clear to name it `lineIndex` and `characterIndex`, but that might just be overly verbose. Most people shouldn't have to deal with it and can just use `formatDiagnostics` for displaying a diagnostic to an end user.

**Comment by ebebbington** [comment]
Im response to both @bartlomieju and @dsherret, I think I will make a PR as it does seem welcomed :) I can't speak for others, but I wouldn't mind about the 0 index thing if I knew about the format method, so I think using `emit` and the format method would come hand in hand (in terms of docs)

Renaming this issue to reflect the discussion had. For clarity, I now have no problem with the 0 index
