### ISSUE TITLE
extensions: Consider splitting streams from fetch

### ISSUE THREAD

**Issue by andreubotella** [denoland/deno#10924]
When I was working on #10842, which added support for `TextDecoderStream` and `TextEncoderStream` to the web extension, I didn't realize that I had to add `deno_fetch` as a dependency, since that's where streams are defined. However, the fetch extension already depends on `deno_web` – a dependency that has now only gotten more entrenched after #10914 made the `File` API part of the web extension. So, since the only part of `deno_fetch` that web uses is streams, it'd be worth considering if they could be split into their own extension.

**Comment by lucacasonato** [comment]
I was thinking maybe we could move streams to the web extension instead?

**Comment by bartlomieju** [comment]
> I was thinking maybe we could move streams to the web extension instead?

Yes please, we should limit number of extensions, not increase it.

**Comment by andreubotella** [comment]
> I was thinking maybe we could move streams to the web extension instead?

Yeah, that's fine by me.
