### ISSUE TITLE
REPL crash when re-assigning globalThis.String

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#10938]
```
> deno repl
Deno 1.11.0
exit using ctrl+d or close()
> String = ""
""
> ;
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', cli\tools\repl.rs:550:49
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This is because the `String` function is used in 02_console.js when the repl code calls `inspectArgs`. The error is a little hard to recover since the `inspectArgs` function is usually used to get errors that occur, but this is it:

```ts
TypeError: String is not a function
    at _inspectValue (deno:extensions/console/02_console.js:454:20)
```

I'm thinking that if someone is re-assigning `String` then they can expect trouble (similar to reassigning something like `parseInt`) and we shouldn't bother fixing, though perhaps something could be done to explain this to them somehow.

**Comment by lucacasonato** [comment]
Ref https://github.com/denoland/deno/issues/10756

**Comment by dsherret** [comment]
No longer occurs. Fixed by https://github.com/denoland/deno/pull/11249
