### ISSUE TITLE
Non-null assertion operator ignored in sub context

### ISSUE THREAD

**Issue by KyleJune** [denoland/deno#10945]
The below code example runs in Deno version 1.10.3 but fails in 1.11.0.

```ts
interface Point {
  x: number;
  y: number;
}
let p: Point | null = null;
function assignP(value: Point) {
  p = value;
}
assignP({ x: 2, y: 3 });
let z: number = p!.x * p!.y;
if (p) {
  z = p!.x * p!.y;
}
console.table({ x: p!.x, y: p!.y, z });
```

Here is the output when run with Deno 1.10.3. It gives the expected output and the extension didn't show any errors in the code.

```
$ deno run example.ts
Check file:///home/kyle/Projects/deno/test_suite/example.ts
┌───────┬────────┐
│ (idx) │ Values │
├───────┼────────┤
│   x   │   2    │
│   y   │   3    │
│   z   │   6    │
└───────┴────────┘
```

After upgrading to Deno 1.11.0, the same code will no longer run.

```
$ deno run example.ts
Check file:///home/kyle/Projects/deno/test_suite/example.ts
error: TS2339 [ERROR]: Property 'x' does not exist on type 'never'.
  z = p!.x * p!.y;
         ^
    at file:///home/kyle/Projects/deno/test_suite/example.ts:12:10

TS2339 [ERROR]: Property 'y' does not exist on type 'never'.
  z = p!.x * p!.y;
                ^
    at file:///home/kyle/Projects/deno/test_suite/example.ts:12:17

Found 2 errors.
```

It shows warnings in vs code saying "Property 'x' does not exist on type 'never'.deno-ts(2339)" and "Property 'y' does not exist on type 'never'.deno-ts(2339)" in the context of the if statement but not outside of it.

![image](https://user-images.githubusercontent.com/3241653/121821930-c5f51780-cc61-11eb-89ac-ea520e7732ca.png)

If I run deno lint with either version of Deno, it shows no issues.

```
$ deno lint example.ts
Checked 1 file
```

I believe those two errors should not be present. In addition to that, I believe a Non-null assertion should not be required inside the if block since that context would only ever be reached if p was not null. The same error occurs without the non-null assertion operator in the if block because it is assuming p will always be null.

**Comment by kitsonk** [comment]
This isn't an "issue" with Deno, it is an "issue" with TypeScript 4.3 which comes in Deno 1.11.  The code you cite does not work under TypeScript 4.3. (see: [playground 4.3](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgAoHtRmQbwFDLIAeAXMiAK4C2ARtANwHICeZltDeAvngDYTYADmQxZkAH3IVevZAF4pMxjAogEYYOhDI4AZ13AA5iFQAKAG5xeFCCMzgAlLiaD5yS9YiMeeg8bM4xGQATAA0LGQAzMhcDoz82ABebNR0UG6CAIQAdETIAFTIWdnMjMAwyKaCTviEiRk5eYXFpdx4CFq66PzZYHA0-KaBpEWN4ayjJeH1sfRAA)) and [playground 4.2](https://www.typescriptlang.org/play?ts=4.2.3#code/JYOwLgpgTgZghgYwgAgAoHtRmQbwFDLIAeAXMiAK4C2ARtANwHICeZltDeAvngDYTYADmQxZkAH3IVevZAF4pMxjAogEYYOhDI4AZ13AA5iFQAKAG5xeFCCMzgAlLiaD5yS9YiMeeg8bM4xGQATAA0LGQAzMhcDoz82ABebNR0UG6CAIQAdETIAFTIWdnMjMAwyKaCTviEiRk5eYXFpdx4CFq66PzZYHA0-KaBpEWN4ayjJeH1sfRAA)).  [We do not consider breaking changes in TypeScript breaking changes in Deno](https://deno.land/manual@v1.11.0/typescript/faqs#there-was-a-breaking-change-in-the-version-of-typescript-that-deno-uses-why-did-you-break-my-program).

**Comment by KyleJune** [comment]
Closing this since the issue is upstream. I've created a new issue on the TypeScript repository.

https://github.com/microsoft/TypeScript/issues/44575
