### ISSUE TITLE
Coverage will be inaccurate if multiple test files import module

### ISSUE THREAD

**Issue by ayame113** [denoland/deno#10944]
I should be able to reproduce this with following:

```js
// mod.js
export function test(a) {
  if (a) {
    return 0;
  }
  return 1;
}
```

```js
// test.js
import { test } from "./mod.js";

Deno.test({
  name: "bugrepo",
  fn: () => {
    test(true); // <- Switch between true and false in test.js and run it several times
  },
});
```

```shell
> deno --version
deno 1.11.0 (release, x86_64-pc-windows-msvc)
v8 9.1.269.35
typescript 4.3.2
> deno test -A --coverage=coverage --filter=bugrepo
> deno coverage --include=bugrepo ./coverage
```

I think, if I switch between true and false in test.js and run it several times, the coverage will be inaccurate due to the impact from previously measured coverage.
Once you delete the coverage directory, you can collect the correct coverage.

**Comment by ayame113** [comment]
I also observed the same phenomenon when a plurality of test file exists for one file.

reproduce :

```js
// mod.js
export function test(a) {
  if (a) {
    return 0;
  }
  return 1;
}
```

```js
// a_test.js
import { test } from "./mod.js";

Deno.test({
  name: "bugrepo a",
  fn: () => {
    test(true);
  },
});
```

```js
// b_test.js
import { test } from "./mod.js";

Deno.test({
  name: "bugrepo b",
  fn: () => {
    test(false);
  },
});
```

```shell
> deno --version
deno 1.11.0 (release, x86_64-pc-windows-msvc)
v8 9.1.269.35
typescript 4.3.2
> deno test -A --coverage=coverage --filter=bugrepo
> deno coverage --include=bugrepo ./coverage
cover file:///C:/Users/azusa/work/web/ay_deno_utils/scripts/bugrepo/mod.js ... 28.571% (2/7)
   2 |   if (a) {
   3 |     return 0;
   4 |   }
   5 |   return 1;
-----|-----
   7 |
```
In this case I'm testing both true and false so I think the coverage will be 6/7.

**Comment by caspervonb** [comment]
> I think, if I switch between true and false in test.js and run it several times, the coverage will be inaccurate due to the impact from previously measured coverage.

Working as intended, you need a clean directroy for a clean profile.
This is done to support multi process collection.

> I also observed the same phenomenon when a plurality of test file exists for one file.
This one is a bug however, probably in the merging algorithm.

**Comment by lucacasonato** [comment]
> Working as intended, you need a clean directroy for a clean profile.
This is done to support multi process collection.

We could clean out the folder in the main "parent" process (the one where you specify `--coverage`).

**Comment by caspervonb** [comment]
> We could clean out the folder in the main "parent" process (the one where you specify --coverage).

Think I'll extend the dumps with checksums and filter on that (gcov does something similar and I like the idea).

**Comment by bartlomieju** [comment]
I'm able to reproduce the issue.

Running only `a_test.js`:
```
❯ deno test --coverage=cov a_test.js
running 1 test from file:///Users/biwanczuk/dev/deno/a_test.js
test bugrepo a ... ok (7ms)

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out (68ms)

❯ deno coverage ./cov
cover file:///Users/biwanczuk/dev/deno/mod.js ... 83.333% (5/6)
   5 |   return 1;
```

```
$ rm -rf cov/
```

Running only `b_test.js`
```
❯ deno test --coverage=cov b_test.js
running 1 test from file:///Users/biwanczuk/dev/deno/b_test.js
test bugrepo b ... ok (6ms)

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out (64ms)

❯ deno coverage ./cov
cover file:///Users/biwanczuk/dev/deno/mod.js ... 50.000% (3/6)
   2 |   if (a) {
   3 |     return 0;
   4 |   }

```

```
❯ rm -rf cov/
```

Running both `a_test.js` and `b_test.js`:
```
❯ deno test --coverage=cov a_test.js b_test.js
running 1 test from file:///Users/biwanczuk/dev/deno/a_test.js
test bugrepo a ... ok (7ms)
running 1 test from file:///Users/biwanczuk/dev/deno/b_test.js
test bugrepo b ... ok (6ms)

test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out (122ms)

❯ deno coverage ./cov
cover file:///Users/biwanczuk/dev/deno/mod.js ... 33.333% (2/6)
   2 |   if (a) {
   3 |     return 0;
   4 |   }
   5 |   return 1;

```

This is definitely wrong. It seems like uncovered lines from one test file are added to uncovered lines from the other one, instead of being diffed.
