### ISSUE TITLE
cannot install file_server

### ISSUE THREAD

**Issue by xie-shujian** [denoland/deno#10968]
when run the below cmd
deno install --allow-net --allow-read https://deno.land/std@0.98.0/http/file_server.ts
it raised an error

**error: TS18022 [ERROR]: A method cannot be named with a private identifier.
  #tryGrowByReslice(n: number) {
  ~~~~~~~~~~~~~~~~~
    at https://deno.land/std@0.98.0/io/buffer.ts:85:3

TS18022 [ERROR]: A method cannot be named with a private identifier.
  #reslice(len: number) {
  ~~~~~~~~
    at https://deno.land/std@0.98.0/io/buffer.ts:94:3

TS18022 [ERROR]: A method cannot be named with a private identifier.
  #grow(n: number) {
  ~~~~~
    at https://deno.land/std@0.98.0/io/buffer.ts:141:3

Found 3 errors.**

**Comment by xie-shujian** [comment]
it is in deno 1.10 
but it is not raise the error in deno 1.11

**Comment by getspooky** [comment]
Hi @xie-shujian , This problem is related to typescript , deno `v1.11` use typescript ` v4.3` that support ES Private Methods.
Please see:
-  https://github.com/denoland/deno/issues/5258
- https://github.com/denoland/deno/pull/9960

**Comment by lucacasonato** [comment]
Update to Deno 1.11
