### ISSUE TITLE
Default `accept-language` header in `fetch`

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#10987]
The fetch spec mandates we add a `accept-language` header to all outgoing responses. Should we? If we do, should we choose the platform language (the one also used by default for Intl APIs), or should we hard-code it to english?

**Comment by iugo** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language

Maybe should use `Accept-Language: *`.

**Comment by lucacasonato** [comment]
That sounds like a plan 👍

**Comment by mrkldshv** [comment]
From what I've checked this should be fairly easy to implement. I guess it is similar to what we do for `Accept` header [here](https://github.com/denoland/deno/blob/fc3a966a2d0be8fc76c384603bf18b55e0bbcf14/ext/fetch/26_fetch.js#L451). Did I get it right or am I missing something?

**Comment by acrodrig** [comment]
For future readers, Apple's caldav servers (for calendar and contacts) fail to parse `Accept-Language: *`. Minimal test case (needs an iCloud account) below.

```bash
# Needed env vars
USER="<account-at-i-cloud-dot-com>";
PASS="<application-specific-password>"
CLUSTER="https://<cluster>-caldav.icloud.com/<principal>/calendars"
XML="<propfind xmlns='DAV:'><prop><displayname/></prop></propfind>"

# Fetch calendars XML description in three different ways

# First, NO "Accept-Language" -> returns 207 correctly ✅
curl -O -s -X PROPFIND -u "$USER:$PASS" -H "Depth: 1" --data "$XML" $CLUSTER -w "%{http_code}\n"

# Second with "Accept-Language: *" -> returns 500 internal server error :( ❌
curl -O -s -X PROPFIND -u "$USER:$PASS" -H "Depth: 1" -H "Accept-Language: *" --data "$XML" $CLUSTER -w "%{http_code}\n"

# Third with "Accept-Language: en" -> returns 207 correctly :( ✅
curl -O -s -X PROPFIND -u "$USER:$PASS" -H "Depth: 1" -H "Accept-Language: en" --data "$XML" $CLUSTER -w "%{http_code}\n"
```

Took me a while to figure out why Deno's `fetch` would return 500 code and Curl worked (207) on the same request. 

I guess is an error on the server side. Some old servers might not handle the header "Accept-Language: *" gracefully.
