### ISSUE TITLE
Consider using list completions in REPL

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#10997]
`rustyline` allows to configure how completions work. Currently Deno uses "circular" method which completes on tab and on subsequent tab propose next completion.

`rustyline` can be configured to use "list completions" which on second tab show list of possible completions:
![Screenshot 2021-06-16 at 03 44 21](https://user-images.githubusercontent.com/13602871/122145253-2dbf8400-ce55-11eb-8095-02c900101ecd.png)

It's done on second tab press because there are "ambigous" entries that match - if you press tab and there's only a single possible completion it will be filled.

IMO this is better than having to cycle through all possibilities.

CC @dsherret 

EDIT:

Here's relevant git patch that provides these changes:
```
diff --git a/cli/tools/repl.rs b/cli/tools/repl.rs
index 67e68c0cd..c9b355c83 100644
--- a/cli/tools/repl.rs
+++ b/cli/tools/repl.rs
@@ -19,6 +19,8 @@ use rustyline::validate::ValidationResult;
 use rustyline::validate::Validator;
 use rustyline::Context;
 use rustyline::Editor;
+use rustyline::Config;
+use rustyline::CompletionType;
 use rustyline_derive::{Helper, Hinter};
 use std::borrow::Cow;
 use std::path::PathBuf;
@@ -302,7 +304,10 @@ struct ReplEditor {

 impl ReplEditor {
   pub fn new(helper: EditorHelper, history_file_path: PathBuf) -> Self {
-    let mut editor = Editor::new();
+    let editor_config = Config::builder()
+      .completion_type(CompletionType::List)
+      .build();
+    let mut editor = Editor::with_config(editor_config);
     editor.set_helper(Some(helper));
     editor.load_history(&history_file_path).unwrap_or(());
```

**Comment by caspervonb** [comment]
Related https://github.com/denoland/deno/pull/7827#issuecomment-712394528

**Comment by caspervonb** [comment]
Caveat to be aware of; any kind of async output will completely destroy that printout.

**Comment by bartlomieju** [comment]
> Caveat to be aware of; any kind of async output will completely destroy that printout (but tolerable as async i/o is already a big problem no matter what).
> 
> Ref #8049

Why is that? We collect the whole list of suggestions before they're returned to `rustyline` for display.

**Comment by caspervonb** [comment]
> > Caveat to be aware of; any kind of async output will completely destroy that printout (but tolerable as async i/o is already a big problem no matter what).
> > Ref #8049
> 
> Why is that? We collect the whole list of suggestions before they're returned to `rustyline` for display.

Ah no, I'm wrong.
It acts like bash where it's a printout to stdout, not zsh where it is in the line buffer.
So the printout will just fly by if things are being printed using console, same as Node.
