### ISSUE TITLE
Add `Origin` header to outgoing requests for fetch

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#10992]
With `--location` set the header should be the location origin (or worker location origin). If it is not set the origin should be `null`.

**Comment by zlumyo** [comment]
I can try this one.

Should an `Origin` header provided manually by user overwrite a value of `--location`?

**Comment by lucacasonato** [comment]
@zlumyo Yes.

**Comment by F3n67u** [comment]
@zlumyo is there any progress about this issue?

**Comment by zlumyo** [comment]
@F3n67u sorry, I've recently got trouble with COVID. If you can pick it up, that will be great.

**Comment by F3n67u** [comment]
> @F3n67u sorry, I've recently got trouble with COVID. If you can pick it up, that will be great.

yep，I can pick it up.
