### ISSUE TITLE
Fetching with method `HEAD` should not have body

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#10990]
HEAD and OPTIONS requests should not have bodies. You can see this issue by fetching `data:,response%27s%20body`. https://fetch.spec.whatwg.org/#concept-main-fetch step 19 says that body should be set to null for HEAD and OPTIONS.

**Comment by getspooky** [comment]
Fixed https://github.com/denoland/deno/pull/11003

**Comment by cmorten** [comment]
@lucacasonato / @getspooky, please point out where I'm being daft, but does step 19 not specify that the `body` should be set to `null` for `HEAD` and `CONNECT`, not `OPTION`?

> 19. If response is not a network error and either request’s method is `HEAD` or `CONNECT`, or internalResponse’s status is a null body status, set internalResponse’s body to null and disregard any enqueuing toward it (if any).

As far as am aware the [CONNECT](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/CONNECT) method isn't the same as the [OPTIONS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/OPTIONS) method?

**Comment by cmorten** [comment]
For further context:

> 9.2 OPTIONS
> ...
> ... The response body, if any, SHOULD also include
> information about the communication options. The format for such a
> body is not defined by this specification, but might be defined by
> future extensions to HTTP. Content negotiation MAY be used to select
> the appropriate response format. If no response body is included, the
> response MUST include a Content-Length field with a field-value of
> "0".

REF: https://datatracker.ietf.org/doc/html/rfc2616#section-9.2

Which indicates that a response body is valid, with the only condition that it should contain information r.e. the options.

I have also noticed that #11003 has introduced a potential bug whereby origin responses to `OPTIONS` requests which contain bodies that are now thrown away, have a non-zero `Content-Length` header:

```console
$ deno
Deno 1.11.5
exit using ctrl+d or close()
> await fetch("http://127.0.0.1:4505", { method: "OPTIONS" });
Response {
  body: null,
  bodyUsed: false,
  headers: Headers {
  allow: "DELETE,GET,HEAD,PUT",
  "content-length": "19",
  "content-type": "text/html; charset=utf-8",
  etag: 'W/"13-b03ce369de9cff9aa2fe20bc98b"',
  "x-powered-by": "Opine"
},
  ok: true,
  redirected: false,
  status: 200,
  statusText: "OK",
  url: "http://127.0.0.1:4505/"
}
```

I'll raise a speculative PR to revert the `OPTIONS` changes in case my understanding is correct and it should be allowed a non-null response body.

**Comment by kitsonk** [comment]
That is correct... `OPTIONS` should be allowed to have a body according to the spec.

**Comment by F3n67u** [comment]
@lucacasonato It seems this issue already fixed. Can we close this issue now?
