### ISSUE TITLE
REPL syntax highlighting is quirky

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#10998]
Example:
![Screenshot 2021-06-16 at 03 44 21](https://user-images.githubusercontent.com/13602871/122145436-8abb3a00-ce55-11eb-851e-de0a208ab5a5.png)

Only `Infinity`, `Nan` and `undefined` are colorized. All the other symbols are displayed in default font.

**Comment by caspervonb** [comment]
Intentional, same colorization as console.
