### ISSUE TITLE
Lint: Ban Unused Ignore

### ISSUE THREAD

**Issue by lawrence-dol** [denoland/deno#11011]
I have set up development environment to use a common set of linting rules for all files, that represent the actual requirements we have in place.

The problem is that all files fail to pass linting because in every file some of the ignored linting rules do not apply; thus the `deno lint` command *always* emits "errors" for these, and *always* returns a non-zero error level (causing my wrapper to abort).

How do I tell Deno to *ignore* unused file-level ignore directives? The obvious solution of adding `ban-unused-ignore` to the list of ignored directives does not work.

**Comment by magurotuna** [comment]
Currently, `ban-unused-ignore` rule cannot be suppressed by the directive like `// deno-lint-ignore ban-unused-ignore`. This is because this rule is implemented internally in a little different way than other rules, but I think this rule also should be suppressed by the directive. I'll give it a shot.

**Comment by lawrence-dol** [comment]
@magurotuna : Using `dlint --config=...` does not suffer from this problem, understandably, so if `deno lint` is enhanced with the ability to specify a config file, and the config does not trigger these errors, that meets my need in a better way.

There is a strong argument to be made, if a config can be specified, that file-level or statement-level lint directives _ought_ warn if an inapplicable (or no longer applicable) directive is specified.

So this could be closed in favor of adding support for a config file, as is already there for `dlint`, per /denoland/deno#11012.
