### ISSUE TITLE
Deno: "failed printing to stdout" panic when piped to `less`

### ISSUE THREAD

**Issue by Ronsor** [denoland/deno#11013]
Example program:
```JavaScript
while (1) {
    console.log("test");
}
```

Save as `stdoutbug.ts` and run as `deno run stdoutbug.ts | less`. Press `q` to exit `less`.

The resulting panic:
```
thread 'main' panicked at 'failed printing to stdout: Broken pipe (os error 32)', library/std/src/io/stdio.rs:940:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
```

Presumably this happens when deno output is piped to any program that does not continuously call `read()` to keep the pipe buffer from filling.

**Comment by cmoog** [comment]
https://github.com/denoland/deno/pull/11039 should fix the panic behavior here.

**Comment by bartlomieju** [comment]
#11039 landed so closing as fixed.
