### ISSUE TITLE
Users can set "Host" header for `fetch`

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#11017]
The `host` header should not be able to be set by the user. It should always be populated by `reqwest` / `hyper`.

**Comment by nayeemrmn** [comment]
Ref #6868.

**Comment by xdatcloud** [comment]
Hi there, I'm not familiar with background info about this issue, but it is possible to send request to endpoint behind Kubernetes Ingress with customized `host` header: https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-rules .

**Comment by yacinehmito** [comment]
Is there a specific reason for this?

**Comment by tlgimenes** [comment]
Guys, can we have a solution to passing host header? Any ideas on how to implement a transparent proxy with Deno's fetch?

**Comment by guifromrio** [comment]
We're being forced to use CF workers to proxy requests because of this limitation. Would be great for it to just work on deno.
