### ISSUE TITLE
Normalize FormData line breaks

### ISSUE THREAD

**Issue by jimmywarting** [denoland/deno#11024]
I took a look at your FormData encoder to see if i could help in this area (with async blob source) also but notices this:

https://github.com/denoland/deno/blob/5814315b708d154ebb2c29810c16e5af7e726741/extensions/fetch/21_formdata.js#L372-L378

I have also had my fair deal of trying to get this right in my formdata-polyfill

- https://github.com/jimmywarting/FormData/pull/67
- https://github.com/jimmywarting/FormData/blob/d26bf54b873d446900c8d5884faff4c4832247de/FormData.js#L92-L96
- https://html.spec.whatwg.org/multipage/form-elements.html#textarea-line-break-normalisation-transformation
- https://bugs.chromium.org/p/chromium/issues/detail?id=917078

From what i understood it should normalize linefeeds out of textareas... 
Stuff that is manually put in by developers with set/append is not normalized?
...This is the way i have done it in my formdata-polyfill to match chromes behavior

in chrome i get no errors for running the below code, with deno i get assertion errors...

```js
var fd = new FormData()
fd.set('a', '\n')
fd.set('b', '\r')
fd.set('c', '\n\r')

new Response(fd).formData().then(fd2 => {
    console.assert(fd2.get('a') === '\n')
    console.assert(fd2.get('b') === '\r')
    console.assert(fd2.get('c') === '\n\r')
})
```

if i run this in chrome that serialize textarea, then it normalize linefeeds
```js
form = document.createElement('form')
text = document.createElement('textarea')
form.append(text)
text.name = 'a'
text.value = '\r'
var fd = new FormData(form)
console.assert(fd.get('a') === '\r\n')
```

So my question is, should you keep `normalizeNewlines` or remove it?
My assumption is that it only belongs to the `<form>` serializeing/constructor in `new FormData(formElm)`

**Comment by kitsonk** [comment]
I haven't dug into it, but is there a wpt test that covers this?  If not, it feels like it is something that the wpt should cover.

**Comment by andreubotella** [comment]
I put some amount of work into defining how newlines in form submissions and in `FormData` had to be normalized in the specs, making sense of the different browser implementations. The corresponding PRs to the HTML spec are whatwg/html#6287, whatwg/html#6624 and whatwg/html#6697. I also [wrote a blog post about it in the WHATWG blob](https://blog.whatwg.org/newline-normalizations-in-form-submission).

I implemented these changes in Deno in #10832.

**Comment by jimmywarting** [comment]
Read your blog post. Oh, what a rabbit hole. 
So chrome is doing things wrong then?

So the correct thing is actually:

```js
var fd = new FormData()
fd.set('a', '\n')
fd.set('b', '\r')
fd.set('c', '\n\r')

console.assert(fd.get('a') === '\n')
console.assert(fd.get('b') === '\r')
console.assert(fd.get('c') === '\n\r')

new Response(fd).formData().then(fd2 => {
    console.log([...fd2])
    console.assert(fd2.get('a') === '\r\n')
    console.assert(fd2.get('b') === '\r\n')
    console.assert(fd2.get('c') === '\r\n\r\n')
})
```

This don't yield any errors in safari...

**Comment by andreubotella** [comment]
> So chrome is doing things wrong then?

[Chrome said they'd implement those changes behind a flag](https://github.com/whatwg/html/issues/6469#issuecomment-825835739), so they can roll them back quickly if they find any webcompat issues. But yeah, they haven't implemented it yet. You can keep track of their implementation in [issue 1167095](https://bugs.chromium.org/p/chromium/issues/detail?id=1167095).


> So the correct thing is actually this?
> 
> ```js
> var fd = new FormData()
> fd.set('a', '\n')
> fd.set('b', '\r')
> fd.set('c', '\n\r')
> 
> console.assert(fd.get('a') === '\n')
> console.assert(fd.get('b') === '\r')
> console.assert(fd.get('c') === '\n\r')
> 
> new Response(fd).formData().then(fd2 => {
>     console.log([...fd2])
>     console.assert(fd2.get('a') === '\r\n')
>     console.assert(fd2.get('b') === '\r\n')
>     console.assert(fd2.get('c') === '\r\n\r\n')
> })
> ```

The behavior of `response.formData()` is not actually standardized anywhere, and is different in every browser. In fact, defining some parsing behavior that makes sense is part of the purpose of https://andreubotella.github.io/multipart-form-data. I don't remember right now what the Safari parser does, but yes, IMO that's the correct behavior.
