### ISSUE TITLE
deno test: 'Failed to execute bootstrap script: Failed to get current working directory

### ISSUE THREAD

**Issue by JohannesRudolph** [denoland/deno#11034]
I managed to crash deno with the following test

```
$ deno --version
deno 1.10.3 (release, x86_64-unknown-linux-gnu)
v8 9.1.269.27
typescript 4.2.2
```

```typescript
Deno.test(
  "can chdir",
  async () => {
    await withTempDir(async (tmp) => {
      Deno.chdir(tmp);
      await Deno.writeTextFile("test.txt", "asd");
    });
  },
);


export async function withTempDir(f: (tmp: string) => Promise<void>): Promise<void> {
  const tmp = await Deno.makeTempDir();

  try {
    return await f(tmp);
  } finally {
    await Deno.remove(tmp, { recursive: true });
  }
}
```

Results in the following output

```
test can chdir ... ok (2ms)
thread '<unnamed>' panicked at 'Failed to execute bootstrap script: Failed to get current working directory

Caused by:
    No such file or directory (os error 2)', runtime/worker.rs:184:8
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Any', cli/tools/test_runner.rs:476:26

test result: ok. 4 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out (194ms)

error: Failed to get current working directory

Caused by:
    No such file or directory (os error 2)
```

Interestingly it seems to be caused by some weird interaction with the `Deno.makeTempDir` call, as leaving this out will not crash the deno runtime.

**Comment by wperron** [comment]
Just tried it locally, with the provided repro I can indeed get it to error out, although I can't get it to panic. Running something simpler however doesn't seem to be causing any issues. I tried with `deno run` and `deno test`:

```typescript
const tmp = await Deno.makeTempDir();
console.log(`temp dir: ${tmp}`);
Deno.chdir(tmp);
await Deno.writeTextFile("greet.txt", "Hello World!");
```

```typescript
Deno.test({
  name: "cwd access",
  async fn() {
    const tmp = await Deno.makeTempDir();
    console.log(`temp dir: ${tmp}`);
    Deno.chdir(tmp);
    await Deno.writeTextFile("greet.txt", "Hello World!");
  },
});
```

Leads me to believe this is maybe a race in user code though I agree the error message isn't great here.

**Comment by wperron** [comment]
So I just tried it with the `Deno.remove()` function at the end, which the only difference between my example and the original example, also isn't encapsulated in a `try/catch` in the original example, that's what's causing the issue. You'll need to move out of the `tmp` directory before calling `Deno.remove(tmp, { recursive: true });`

**Comment by caspervonb** [comment]
Known issue.

The problem is that cwd is a process level change that changes it for everything in the entire process.

If you remove the directory bad things happen because we call `.unwrap()` on many calls to `current_dir` internally in the runtime in many places.

**Comment by wperron** [comment]
I can't get it to panic though, running on Ubuntu 21.04, on Deno 1.11 or 1.10

**Comment by caspervonb** [comment]
Huh, yeah I can't get this to panic, just throws an error.

**Comment by JohannesRudolph** [comment]
@caspervonb @wperron Interesting, I was running this on a Fedora 34 and it reliably panics for me every time. 

@wperron thanks for your suggestion, I can confirm that with a wrapper in my tests that restores the `cwd` to its previous value deno, as expected, doesn't panic. This is fine as a workaround for me. 

I think you guys are way better informed to make a decision about the "correct" behavior that deno should have in case that the `cwd` points to a directory that doesn't exist.

**Comment by caspervonb** [comment]
Could you do a run with full track trace @JohannesRudolph?

```
export RUST_BACKTRACE=full
```
