### ISSUE TITLE
Consider making `Deno` namespace configurable

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#11033]
Currently the `Deno` namespace isn't configurable in the runtime.  This makes it difficult to do mocking and polyfilling of things, like trying to create a realistic Deploy environment, where code could bind to the parts of the `Deno` namespace it needs and then replace the namespace with a different set of APIs for additional code to be loaded.

Other global objects are not set as non-configurable and so `Deno` stands out as an example.

A specific use case is when trying to create a Deploy like environment in the worker, the only option is to not include the `Deno` namespace in the worker and create global `Deno` object that has the APIs that are just present in Deploy, but this means that the code in the worker that bootstraps the environment has no access to the other `Deno` APIs, which makes it difficult to do things like read files from disk.

**Comment by satyarohith** [comment]
I'm +1 for this. It will make tests simple. For example, I can overload built-in `fetch()` to avoid network requests during tests, but I cannot do the same for `Deno.readTextFile()` to avoid fs calls.

**Comment by CrimsonCodes0** [comment]
To even have the Deno namespace as an immutable property of the global object means that the Deno runtime could be considered spec-incompliant at some point.
<https://github.com/Agoric/proposal-preserve-virtualizability#undeletable-extensions>
> We propose that any such additional properties added by the host to any object, including the global object, must be deletable.

Surely some scripts might like to just drop the Deno namespace entirely?
Regardless, making the Deno namespace itself configurable couldn't do any harm.

**Comment by kitsonk** [comment]
Making it configurable would make it deletable.

**Comment by CrimsonCodes0** [comment]
> Making it configurable would make it deletable.

My apologies if I appeared to have seen it differently, but yes, that is precisely why I would support this!
