### ISSUE TITLE
Deno.permissions APIs should accept URLs where appropriate

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#11036]
Currently `PermissionDescriptor`s accept only strings as paths.

As suggested in https://github.com/denoland/deno/issues/11035, we should add support for URLs where appropriate, in line with recent changes APIs such as:
- Deno.chdir
- Deno.realPath
- Deno.realPathSync
- Deno.rename
- Deno.renameSync
- Deno.symlink
- Deno.symlinkSync
- Deno.utime
- Deno.utimeSync

So this should work:
```ts
const url = new URL("some/path", import.meta.main);
const status = await Deno.permissions.query({ name: "read", path: url });
```

**Comment by caspervonb** [comment]
Any changes should also be applied to `Deno.TestDefinition.permissions` (they share the same internal conversion).

**Comment by caspervonb** [comment]
Any changes should also be applied to `Deno.TestDefinition.permissions` (they share the same internal conversion).
