### ISSUE TITLE
`new URL(..., import.meta.url)` is not well supported

### ISSUE THREAD

**Issue by surma** [denoland/deno#11035]
In web development, it is becoming increasingly common to reference assets in a module-relative fashion using the `new URL(..., import.meta.url)` pattern. This way, relative paths work _consistently_ relative to the JavaScript file, while without it some _some_ paths will be relative to the document.

In Deno, however, paths are often expected to be strings not `URL` objects, and even stringified URLs cause problems as they have the `file:` scheme.

Here is a piece of example code with annotations why they don’t work:

```ts
const workerFile = new URL("./worker_file.ts", import.meta.url);
// This doesn’t work because path is not a string but a URL
// await Deno.permissions.request({name: "read", path: workerFile});

// This works, but fails later on because 
// `file:///some/path/worker_file.ts` is a different path from
// `/some/path/worker_file.ts`.
// await Deno.permissions.request({name: "read", path: workerFile.toString()});

// This works!
await Deno.permissions.request({name: "read", path: workerFile.pathname});

// This fails because the path argument for the worker constructor is not 
// implicitly turned into a string (browers do do that!).
// const w = new Worker(workerFile, {type: "module"});

// This works!
const w = new Worker(workerFile.toString(), {type: "module"});

w.addEventListener("message", ev => {
	console.log(ev.data);
	w.terminate();
});
```

**Comment by bartlomieju** [comment]
Hey @surma!

We actually encourage the pattern you've shown throughout the manual, most often it's like:
`new URL("./worker_file.ts", import.meta.url).href`.

> // This doesn’t work because path is not a string but a URL
// await Deno.permissions.request({name: "read", path: workerFile});

Correct, currently `Deno.permissions` requires to use string, we've migrated quite a few APIs to accept `URL`s as well as strings, I guess this one hasn't been yet; I'll open an issue about it.

> // This fails because the path argument for the worker constructor is not 
// implicitly turned into a string (browers do do that!).
// const w = new Worker(workerFile, {type: "module"});

// This works!
const w = new Worker(workerFile.toString(), {type: "module"});

w.addEventListener("message", ev => {
	console.log(ev.data);
	w.terminate();
});

This is surprising, we do turn passed specifier into a string when creating a new worker. Which Deno version are you using?

**Comment by surma** [comment]
This seems like a great outcome :D Thanks for checking everything so quickly!

**Comment by bartlomieju** [comment]
No problem, thanks for reporting!

**Comment by guybedford** [comment]
On this topic, it's worth noting that the URL standard itself explicitly recommends **not** having APIs / specs take URL objects - https://url.spec.whatwg.org/#url-apis-elsewhere.

Node.js was able to benefit by enforcing `instanceof URL` checks because it allowed distinguishing paths. The hope for a platform like Deno is that it could be URL first and not need this method of distinction.

Ideally, URLs can be treated as strings through normal `toString()` cooercion rather than explicit URL instance checking which can also pose an issue when dealing with cross-realm checks.

**Comment by surma** [comment]
Wanna close this in favor of the separate bugs @bartlomieju opened?

**Comment by lucacasonato** [comment]
> The hope for a platform like Deno is that it could be URL first and not need this method of distinction.

@guybedford We can't, as `file:///etc/passwd` is a valid relative path in unix (that will resolve to `$CWD/file:/etc/passwd`). There is no way for us to distinguish a URL in string form from a relative path. That would mean we would have to either drop support for relative paths, or try parse all paths as a URL and if that fails treat them as a relative path. Both seem like not great options compared to just taking `URL or string`.

**Comment by lucacasonato** [comment]
@surma I'll close this in favor of the more specific individual issues. Thanks for reporting!
