### ISSUE TITLE
Travis should fail immediately if tools/lint.py or tools/test_format.py fail

### ISSUE THREAD

**Issue by ry** [denoland/deno#1104]
We don't want to clog the CI pipeline with things that will need to be built again. We want to give more immediate feedback to PRs

**Comment by orenwf** [comment]
Putting bash `&&` ::= `AND_IF` between commands should make them execute in sequence but exit early on a non-zero return code from any of the commands.
```
script:    ./tools/lint.py && \
           ./tools/test_format.py && \
           { bash -c "sleep 2100; pkill ninja; pkill cargo" & } && \
           ./tools/build.py -j2 && \
           RUSTC_WRAPPER=sccache cargo check -j2 --release && \
           ./tools/test.py $DENO_BUILD_PATH
```
