### ISSUE TITLE
[extention/fetch] Allow reqwest HTTPClient configuration

### ISSUE THREAD

**Issue by alexander-bzikadze** [denoland/deno#11056]
Currently configuration for underlying reqwest httpclient is concealed, only  [TLS certificate](https://github.com/denoland/deno/blob/7b559ee89ef2dd4be6a45af6ae1e3e09c76fec01/cli/dts/lib.deno.unstable.d.ts#L1078) being exposed. Creating shared HTTP client uses some options predefined both [by Deno](https://github.com/denoland/deno/blob/main/extensions/fetch/lib.rs#L516) and [reqwest itself](https://docs.rs/reqwest/0.11.3/src/reqwest/async_impl/client.rs.html#126).

Controlling HTTP client configuration is very important for server-side applications. For instance, inability to configure tcp connection pool for http/1.1 is a deal breaker.

The complication I am seeing is agreeing on the API. I'm not sure if Deno wishes to use reqwest forever or move to something else in the future, therefore configuration options relying on reqwest too much might be dangerous. In that case I would propose avoid the risk of leaky abstraction and expose reqwest explicitly with [its options](https://docs.rs/reqwest/0.11.3/reqwest/struct.ClientBuilder.html):
```typescript
export interface CreateHttpClientOptions {
    clientProvider: "reqwest" | "other implementation"

    /** A certificate authority to use when validating TLS certificates. Certificate data must be PEM encoded.
     */
    caData?: string;
  }

export interface CreateReqwestHttpClientOptions extends CreateHttpClientOptions {
    clientProvider: "reqwest"
    poolIdleTimeout: number
    poolMaxIdlePerHost: number
    ...
}
```

What do you think? Do you have any other plans/ideas?

Thank you!

**Comment by lucacasonato** [comment]
I would rather not expose that we use `reqwest`. That is an implementation detail and subject to change. I would be happy with providing options for "http1 only", "always http2", or connection pooling specifics. The exact flags that should be configurable by the user should be mostly 1:1 equivalent to what Go exposes in the `http.Transport`.

**Comment by alexander-bzikadze** [comment]
Thank you for your reply!
Ok, I agree we can rely on Golang design and not be afraid it needs to be changed  radically in the future. Let me propose this interface based on my research:

| Golang Analogue           	| Reqwest analogue                                                                                                 	| Proposed Interface                 	|
|---------------------------	|------------------------------------------------------------------------------------------------------------------	|------------------------------------	|
| Proxy                     	| [proxy](https://docs.rs/reqwest/0.11.4/src/reqwest/async_impl/client.rs.html#661)                                	| "Out of scope"                     	|
| DialContext.Timeout       	| [connect_timeout](https://docs.rs/reqwest/0.11.4/src/reqwest/async_impl/client.rs.html#697)                      	| tcp.timeoutMs                      	|
| DialContext.Deadline      	| --                                                                                                               	| --                                 	|
| DialContext.KeepAlive     	| [tcp_keepalive](https://docs.rs/reqwest/0.11.4/src/reqwest/async_impl/client.rs.html#814)                        	| tcp.keepaliveMs                    	|
| DialContext.LocalAddr     	| [local_address](https://docs.rs/reqwest/0.11.4/src/reqwest/async_impl/client.rs.html#803)                        	| "Out of scope"                     	|
| DialContext.FallbackDelay 	| --                                                                                                               	| "Out of scope"                     	|
| DialContext.Resolver      	| [resolve](https://docs.rs/reqwest/0.11.4/src/reqwest/async_impl/client.rs.html#1063)                             	| "Out of scope"                     	|
| DialContext.Control       	| --                                                                                                               	| "Out of scope"                     	|
| DialTLSContext.*          	| --                                                                                                               	| "Out of scope"                     	|
| TLSClientConfig.*         	| ?                                                                                                                	| "Out of scope"                     	|
| TLSHandshakeTimeout       	| ?                                                                                                                	| "Out of scope"                     	|
| DisableKeepAlives         	| [pool_idle_timeout](https://docs.rs/reqwest/0.11.4/src/reqwest/async_impl/client.rs.html#720) = None             	| --                                 	|
| DisableCompression        	| [.gzip(false)](https://docs.rs/reqwest/0.11.4/src/reqwest/async_impl/client.rs.html#533)                         	| "Out of scope"                     	|
| MaxIdleConns              	| --                                                                                                               	| --                                 	|
| MaxIdleConnsPerHost       	| [pool_max_idle_per_host](https://docs.rs/reqwest/0.11.4/src/reqwest/async_impl/client.rs.html#729)               	| http.idle.perHost                  	|
| MaxConnsPerHost           	| --                                                                                                               	| --                                 	|
| IdleConnTimeout           	| [pool_idle_timeout](https://docs.rs/reqwest/0.11.4/src/reqwest/async_impl/client.rs.html#720)                    	| http.idle.timeoutMs                	|
| ResponseHeaderTimeout     	| --                                                                                                               	| --                                 	|
| ExpectContinueTimeout     	| --                                                                                                               	| --                                 	|
| TLSNextProto              	| --                                                                                                               	| "Out of scope"                     	|
| ProxyConnectHeader        	| --                                                                                                               	| "Out of scope"                     	|
| GetProxyConnectHeader     	| --                                                                                                               	| "Out of scope"                     	|
| MaxResponseHeaderBytes    	| --                                                                                                               	| --                                 	|
| WriteBufferSize           	| --                                                                                                               	| --                                 	|
| ReadBufferSize            	| --                                                                                                               	| --                                 	|
| ForceAttemptHTTP2         	| [http2_prior_knowledge](https://docs.rs/reqwest/0.11.4/src/reqwest/async_impl/client.rs.html#741) (Golang does not support http2 without TLS)               	| http2.priorKnowledge               	|
| --                        	| [http2_initial_stream_window_size](https://docs.rs/reqwest/0.11.4/src/reqwest/async_impl/client.rs.html#749)     	| http2.initial.streamWindowSize     	|
| --                        	| [http2_initial_connection_window_size](https://docs.rs/reqwest/0.11.4/src/reqwest/async_impl/client.rs.html#757) 	| http2.initial.connectionWindowSize 	|
| --                        	| [http2_adaptive_window](https://docs.rs/reqwest/0.11.4/src/reqwest/async_impl/client.rs.html#769)                	| http2.adaptiveWindow               	|
| --                        	| [http2_max_frame_size](https://docs.rs/reqwest/0.11.4/src/reqwest/async_impl/client.rs.html#777)                 	| http2.maxFrameSize                 	|

So configuration would be extended to
```typescript
export interface CreateHttpClientOptions {
    /** A certificate authority to use when validating TLS certificates. Certificate data must be PEM encoded.
     */
    caData?: string;

    tcp?: {
        timeoutMs?: number
        keepaliveMs?: number
    }

    http?: {
        idle?: {
            perHost?: number
            timeoutMs?: number
        }
    }

    http2?: {
        priorKnowledge?: bool
        initial?: {
            streamWindowSize?: number
            connectionWindowSize?: number
        }
        adaptiveWindow?: number
        maxFrameSize?: number
    }
}
```

Please let me know of your opinion and any suggestions you have.
