### ISSUE TITLE
Add documentation for `.deno/deps` and `.deno/gen`

### ISSUE THREAD

**Issue by kevinkassimo** [denoland/deno#1105]
Deno currently stores cached remote resources in `.deno/deps` and compiled scripts in `.deno/gen`. We are expecting users to manually clear the cache themselves (as discussed in #1101), therefore we need to clearly document these directories.

@ry could be a "good first issue" for new contributors.

**Comment by j33n** [comment]
@kevinkassimo I would be happy to take this up

**Comment by kt3k** [comment]
Seems fixed at #1116
