### ISSUE TITLE
Deno cli seems unable to handle glob patterns in Windows

### ISSUE THREAD

**Issue by differentsmoke** [denoland/deno#11059]
**Version**: `deno 1.11.1 (release, x86_64-pc-windows-msvc)`

**Issue**: When trying to run multiple files such as `deno test *.ts`, it results in the following error:

```
error: The filename, directory name, or volume label syntax is incorrect. (os error 123) 
```

I created a directory with files `test_01.ts` and `test_02.ts`, both containing the following code:

```typescript
Deno.test("This test always passes.", () => {});
```

Running `deno test test_01.ts` or `deno test test_02.ts` runs as expected.
Running `deno test *.ts` results in the previously mentioned error.

I tested the behavior in Ubuntu (using WSL with its own Deno installation (`deno 1.11.1 (release, x86_64-unknown-linux-gnu)`)) and it works as expected: `deno test *.ts` runs both tests.

**Comment by bartlomieju** [comment]
Deno CLI doesn't expand globs, it is up to your shell to do that. In other words `deno test` is run with a list of files your shell has created from the glob.

**Comment by differentsmoke** [comment]
Running `dir *.ts` in the same folder works as expected. Wouldn't that mean that the globs are working correctly?

**Comment by differentsmoke** [comment]
Ran with git-bash on windows and it does work as expected as well.

**Comment by MarkTiedemann** [comment]
> Running `dir *.ts` in the same folder works as expected. Wouldn't that mean that the globs are working correctly?

No, that means that `dir` expands globs. `cmd.exe` doesn't expand globs.
