### ISSUE TITLE
`Deno.shutdown()` listed as stable in types, unstable at runtime

### ISSUE THREAD

**Issue by Dav3rs** [denoland/deno#11055]
![image](https://user-images.githubusercontent.com/50024128/122660022-a4a59700-d14b-11eb-865c-972b901f59a2.png)

**Comment by satyarohith** [comment]
@Dav3rs, can you provide reproduction steps?

**Comment by Dav3rs** [comment]
@satyarohith It's easy, just try to use the `Deno.shutdown` function, and it won't work.
1 - try to use `Deno.shutdown`
2 - it's doesn't work 😶
![image](https://user-images.githubusercontent.com/50024128/122661354-6910ca00-d157-11eb-8342-6d2584cde3a5.png)

**Comment by satyarohith** [comment]
@Dav3rs Thanks! I actually did test it before but didn't go past the type error. So we have the types but not the actual implementation. In the meantime you can use  [`Deno.close(conn.rid)`](http://doc.deno.land/builtin/stable#Deno.close). 
```
➜  ~ cat shutdown.ts
Deno.shutdown()
➜  ~ deno run -A shutdown.ts
Check file:///Users/sr/shutdown.ts
error: TS2554 [ERROR]: Expected 1 arguments, but got 0.
Deno.shutdown()
     ~~~~~~~~~~
    at file:///Users/sr/shutdown.ts:2:6

    An argument for 'rid' was not provided.
      export function shutdown(rid: number): Promise<void>;
                               ~~~~~~~~~~~
        at asset:///lib.deno.ns.d.ts:1895:28
➜  ~ deno run -A --no-check shutdown.ts
error: Uncaught TypeError: Deno.shutdown is not a function
Deno.shutdown()
     ^
    at file:///Users/sr/shutdown.ts:2:6
```

**Comment by crowlKats** [comment]
`Deno.shutdown` is an unstable API, but the typings are in stable (or impl is stable but marked as unstable)

**Comment by Dav3rs** [comment]
That's right, it works with the `--unstable` flag. I thought it was stable already, since v1.7

https://deno.com/blog/v1.7#changes-to-deno-apis
https://github.com/denoland/deno/blob/v1.11.1/Releases.md#170--20210119

**Comment by erfanium** [comment]
I think #10880 has fixed this issue
