### ISSUE TITLE
Transferables should be supported for BroadcastChannel

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#11075]
Followup to #6691. The `postMessage` / `onmessage` for `BroadcastChannel` should use the same internal logic as `MessagePort`, at least for the default `InMemoryBroadcastChannel` implementation.

**Comment by surma** [comment]
`BroadcastChannel` on the web [doesn’t support transferables](https://developer.mozilla.org/en-US/docs/Web/API/BroadcastChannel/postMessage) as you have potentially multiple receivers, so the semantics of “transferring ownership” don’t really make sense in this context.

**Comment by lucacasonato** [comment]
Oh, well one issue less I guess :-)
