### ISSUE TITLE
Deno check would throw 'Property xxx is used before its initialization' for using property are defined in parameter properties

### ISSUE THREAD

**Issue by XGHeaven** [denoland/deno#11087]
## Versions
```
deno 1.11.0 (release, x86_64-apple-darwin)
v8 9.1.269.35
typescript 4.3.2
```

## Input
```typescript
class A {
  b = this.a
  constructor(public a: string) {}
}
```

## Expected
No errors.

## Actual
```
error: TS2729 [ERROR]: Property 'a' is used before its initialization.
  b = this.a
           ^
    at file:///xxx

    'a' is declared here.
      constructor(public a: string) {}
                  ~~~~~~~~~~~~~~~~
        at file:///xxx
```

## More
I found no errors with typescript@4.3. 
Demo: https://www.typescriptlang.org/play?strict=true#code/MYGwhgzhAECC0G8BQ1XTALmhALgJwEsA7Ac2gF5ocALAiAOlzxTQCMKraGwXVgB7IkwCuwHPzwAKAA6EAbmBwBTbPixNiJAJSIAvkn1A

**Comment by kitsonk** [comment]
I am afraid you were using the wrong settings in TypeScript playground.  You need to target `esnext` as that is what Deno internally transpiles to [and the error will appear](https://www.typescriptlang.org/play?useDefineForClassFields=true&target=99&strict=true#code/MYGwhgzhAECC0G8BQ1XTALmhALgJwEsA7Ac2gF5ocALAiAOlzxTQCMKraGwXVgB7IkwCuwHPzwAKAA6EAbmBwBTbPixNiJAJSIAvkn1A).  See microsoft/TypeScript#44298 for further information on why TypeScript disallows this.
