### ISSUE TITLE
Rust crash when proxying multipart request via `fetch`

### ISSUE THREAD

**Issue by mitranim** [denoland/deno#11092]
## Environment

    deno 1.11.2 (release, x86_64-apple-darwin)
    v8 9.1.269.35
    typescript 4.3.2

OS: MacOS Big Sur 11.4 (20F71).

## Description

(See repro below.)

A Deno process may crash when proxying an incoming multipart POST request via `fetch` to an _inaccessible_ target server.

## Repro

Probably not the most minimal repro, but this is what I have on hand.

* See gist https://gist.github.com/mitranim/5982e627fa2f0e82ab926c8fb68b5c7d.
* Run `./deno_crash_upload_proxy.mjs` via hashbang. It starts a server.
* Open URL printed to terminal.
* Use the file input to submit an arbitrary file. (I used various JPG images.)
* The upload endpoint tries to proxy to an inaccessible target server.
* Process may crash with a Rust trace.

**Comment by bartlomieju** [comment]
Thanks for the report and reproduction @mitranim, I can trigger the panic consitently. I will look into fixing it.

**Comment by bartlomieju** [comment]
This panic originates in `op_fetch_request_write`, concretely here:
https://github.com/denoland/deno/blob/622f9c688902411e347038e82fc5c354c60678cf/extensions/fetch/lib.rs#L359

So it's actually bug in `fetch` implementation. I'm having trouble figuring out why that op is even run if the host that fetch tries to connect to does not have a server running. 

CC @lucacasonato
