### ISSUE TITLE
Missing: Atomics Object

### ISSUE THREAD

**Issue by mhmdmar** [denoland/deno#11099]
[Atomics Object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Atomics) is part of the ECMAScript Language Specification, it's supported in the browser and NodeJS, it helps with shared-memory in multi-threading/concurrency programming , any plans to support this in the near future?

**Comment by kitsonk** [comment]
What makes you think it isn't supported?

```
> deno
Deno 1.11.2
exit using ctrl+d or close()
> Atomics
Atomics {}
```

**Comment by kitsonk** [comment]
The types are also in the types for this. 😕

**Comment by mhmdmar** [comment]
Thank you, I think I tried to access the object before on an older version :)
