### ISSUE TITLE
ninja fails to build with code 1 on wsl

### ISSUE THREAD

**Issue by kyranet** [denoland/deno#1110]
Using wsl with Ubuntu 16.04 LTS (Xenial), and ccache 3.5+15_gdc5dce0, the build fails after https://github.com/denoland/deno/commit/59acd8d1ac454d8371234e46188f0184bd870218. All dependencies and libraries are up-to-date from apt-get (minus ccache, which was built from source). The command ran was `./tools/build.py`.

![image](https://user-images.githubusercontent.com/24852502/47609818-978d8400-da46-11e8-9df4-2aae53c69d23.png)

**Comment by bartlomieju** [comment]
@kyranet can you check if this is still an issue with newest release?

**Comment by bartlomieju** [comment]
CC @ry this issue is stale, can we close it for now and reopen if needed?

**Comment by kyranet** [comment]
I'll close it as I'm not working in this project at the moment. Will re-open if I encounter this problem when I come back 👍
