### ISSUE TITLE
Get JsRuntime execution output

### ISSUE THREAD

**Issue by gufoe** [denoland/deno#11105]
Hello, I'd like to use deno to interpret js at runtime and get the result, for instance:
```rust
let res = runtime.execute("<main>", "return 123");
assert!(res.unwrap() == serde_json::Value::from(123))
```
But execute actually returns nothing useful.

Is there any way to achieve this?

**Comment by bartlomieju** [comment]
As you've noticed `runtime.execute()` returns `Result<(), AnyError>` and thus doesn't return the evaluation value. This issue has come up a few times already and I think I'll just go ahead and change API.

That said - you won't be able to do this comparison:
> `assert!(res.unwrap() == serde_json::Value::from(123))`
The value returned will have `v8::Value` type - so you'll have to convert it to some Rust primitive type yourself.

**Comment by gufoe** [comment]
Thank you for the quick reply!
I guess converting the v8::Value to something else will be fine.

Sorry to ask this question, but do you have an idea of when this feature will be available?

**Comment by bartlomieju** [comment]
Probably in 1.12 on July, 13th

**Comment by weareoutman** [comment]
Hi, would it support getting async result from a module includes top-level await? (using `execute_module`)

**Comment by bartlomieju** [comment]
Not in the #11129, once that PR lands I will look into supporting that for modules.
