### ISSUE TITLE
Unable to filter tests using VS Code launch.json (since v1.10.x)

### ISSUE THREAD

**Issue by 51ngul4r1ty** [denoland/deno#11119]
**Description of Issue**

When running deno tests in the VS Code debugger it no longer filters properly.  Prior to the v1.9.2 to v1.10.x upgrade (I tried v1.11.x as well) it would run the tests specified by the "--filter" runtimeArg in the launch.json shown below.

If you remove the --filter related runtimeArgs it will run a subset of the tests (at first I thought it was running all the tests but later discovered that it still only runs a subset that didn't include the tests I was filtering for).  If you leave it as-is it will run none of the tests and it outputs this:

`running 0 tests from file:///Users/user-name-here/path-to-files-here/tests/some-other-unexpected-file-without-text-in-name.test.ts`

**Steps to Reproduce**

1. Use a launch.json file like this:

```
        {
            "name": "Tests (filtered)",
            "request": "launch",
            "type": "pwa-node",
            "cwd": "${workspaceFolder}",
            "runtimeExecutable": "deno",
            "runtimeArgs": [
                "test",
                "--inspect-brk",
                "--allow-all",
                "--unstable",
                "--filter",
                "some text that appears in test name"
            ],
            "outputCapture": "std",
            "attachSimplePort": 9229
        },
```

2. Set breakpoints in the test.

3. Try to debug the test.

**Other Notes**

`deno test --allow-all --unstable --filter "some text that appears in test name"` works fine- it lists out *ALL* of the test files and outputs "running 0 tests from file:..." for the files that don't have tests matching the filter.  So, this appears to only be a problem with how the VS Code Deno Language Server extension (with deno v1.10.x and newer) enumerates the files.

When debugging with the newer version of deno VS Code hits a breakpoint when it executes $deno$test.js and shows this code that it is executing: `await Deno[Deno.internal].runTests({"disableLog":false,"filter":"some text that appears in test name"});`  When I step into this I find that the `tests` object only contains tests from a single file that it appears to choose for no obvious reason (to me).

**Updates After Initial Submission**

I changed the sentence that said: `If you remove the --filter related runtimeArgs it will run all the tests` to `If you remove the --filter related runtimeArgs it will run a subset of the tests (at first I thought it was running all the tests but later discovered that it still only runs a subset that didn't include the tests I was filtering for)`.  The problem appears to be how it builds the list of test files when running in the context of VS Code.

**Comment by jaredkrinke** [comment]
I think I might be hitting this. In my case, if I explicitly specify my test file via an argument in launch.json, then I'm able to debug my test.

I wonder if Deno tries to isolate test files by running them in different contexts, but you're only able to debug one of those contexts in VS Code.

**Comment by lucacasonato** [comment]
I can not reproduce this anymore:

```ts
// test_test.ts
Deno.test("hello world", () => {
});

Deno.test("bye world", () => {
});
```

```json
// .vscode/launch.jsonc
{
  "configurations": [
    {
      "name": "Tests (filtered)",
      "request": "launch",
      "type": "node",
      "cwd": "${workspaceFolder}",
      "runtimeExecutable": "deno",
      "runtimeArgs": [
        "test",
        "--inspect-brk",
        "--filter",
        "hello world"
      ],
      "outputCapture": "std",
      "attachSimplePort": 9229
    }
  ]
}
```

Output:

```
/home/lucacasonato/.deno/bin/deno test --inspect-brk --filter hello world
Debugger listening on ws://127.0.0.1:9229/ws/0e2e2e6b-51b4-4bbb-9a99-006fba5e6575
Visit chrome://inspect to connect to the debugger.
Deno is waiting for debugger to connect.
Debugger session started.
running 1 test from ./test_test.ts
hello world ... ok (0ms)

ok | 1 passed | 0 failed | 1 filtered out (2ms)
```

If you are still running into this, please re-open the issue.
