### ISSUE TITLE
Migrate all builtin web globals to host objects

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#11118]
Currently most of our web builins are ES classes. This means that these are all userland JS objects, not what webidl and V8 call "host objects". Host objects have the special ability to be serialized using a `ValueSerializer`. Regular JS objects can not have custom serializer steps. To properly support `MessagePort`, we need to be able to serialize these using a `ValueSerializer`.

Because of this we need to stop using ES classes for internal JS code. Instead there will be a helper in `deno_webidl` that lets you create a webidl interface by just specifying the name, interface attributes, operations, constructors, and parent interfaces. The helper will then create a built-in function that can construct host objects, with the correct prototype chain. It will also automatically create a host object prototype.

This will require some significant changes all over the codebase, but after discussion with @bnoordhuis it is the only way forward if we want to properly support structured clone for host objects.

The plan:
1. [ ] Introduce a `Deno.core.createHostObject()`. This will return a plain host object.
2. [ ] Introduce a `webidl.createInterface` method. This will take an options bag with various information related to the webidl interface. It will return an interface function as defined in https://heycam.github.io/webidl/#es-interfaces.
3. [ ] Port over web APIs to the new system

**Comment by lucacasonato** [comment]
So @bnoordhuis, this actually extends past just creating host objects. We actually need to create `Function` / `FunctionTemplate` for each webidl interface, because these interfaces are constructed with the `new` keyword. This is even more complicated than I had initially expected.

**Comment by lucacasonato** [comment]
Lets see if we can get a solution upstream in V8 before resorting to this: https://crbug.com/v8/11927

**Comment by crowlKats** [comment]
@lucacasonato given that the v8 issue has been closed, what is the path forward here?

**Comment by gterzian** [comment]
@lucacasonato could you pls elaborate on the use case for messageport? It seems you are already transferring it via its Id? 

A lesson learned with Servo was that its better to have only a light-touch integration with the JS engine, for example doing the transfer and/or serialization in pure Rust, and only passing Id's around in the JS engine. 

See [impl Transferable for MessagePort](https://github.com/servo/servo/blob/6282c4d1476655f6822322935059a61fa7c83663/components/script/dom/messageport.rs#L159), and [the corresponding JS engine calls](https://github.com/servo/servo/blob/6282c4d1476655f6822322935059a61fa7c83663/components/script/dom/bindings/structuredclone.rs#L199).
