### ISSUE TITLE
String literals will be escaped when deno script is ran with shebang

### ISSUE THREAD

**Issue by ihack2712** [denoland/deno#11112]
Example

*example.ts*
```ts
#!/usr/bin/env -S deno run
console.log(String.raw`hello
world`);
```

-----

Running the code above with the following command:

```ts
deno run example.ts
```

will print

```
hello
world
```

-----

But running it with the following comand:

```
./example.ts
```

will print

```
hello\nworld
```

**Comment by ihack2712** [comment]
Hmm...

**Comment by kurai-espoir** [comment]
@ihack2712 what version of Deno are you using? Works fine for me
![image](https://user-images.githubusercontent.com/89643846/131234895-835b5699-dfff-4132-9818-f6b243b71751.png)

**Comment by ihack2712** [comment]
It was 1.12.2 at the time, the error is a bit hard to reproduce as it only occurs some times, I've only experienced the bug in not small codebases, but not quite big either.

**Comment by ihack2712** [comment]
https://discord.com/channels/684898665143206084/688040863313428503/857736235657461780 Conversation starts correctly here
