### ISSUE TITLE
sleepSync stops signal processing

### ISSUE THREAD

**Issue by justinmchase** [denoland/deno#11121]
If you're waiting for an interrupt signal but al happen to call sleepSync it will not send the interrupt signal and appears to hang until the sleep is done.

```ts
async function main() {
  while (true) {
    console.log('sleeping...')
    Deno.sleepSync(30 * 1000) // 30s
  }
}

async function interrupt() {
  await Deno.signal(Deno.Signal.SIGINT);
  console.log('interrupted!');
}

await Promise.any([main(), interrupt()])
console.log('done')
```

The signal isn't processed while sleepSync is happening... This is kind of surprising to me I was expecting it to behave more like this:

```ts
async function sleep(ms: number) {
  return await new Promise(resolve => setTimeout(resolve, ms))
}
```

Which is a helper function I make in nearly every app and would love it if deno just had this built in somewhere.

**Comment by wperron** [comment]
That helper function already exists in the standard library over here --> https://deno.land/std@0.99.0/async/delay.ts

The `sleepSync` function is different in that it puts the main _Rust_ thread to sleep, meaning literally nothing happens during that time, the event loop is completely stopped.

**Comment by caspervonb** [comment]
In terms of syscall mapping, sleepSync is equivalent to `sleep(1)` meaning the entire worker thread is sleeping so working as intended.
