### ISSUE TITLE
Support namespace imports when flattening in library builder

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#1112]
Currently when building the internal library of Deno, and are flattening a module/namespace (e.g. `"deno"`), name space imports are not supported.  For example the following will result in an error in the library:

```ts
import * as io from "./io.ts";
```

And instead the individual symbols have to be imported, like:

```ts
import { Reader, Writer } from "./io.ts";
```

It maybe difficult to support this as it is challenging to resolve the symbols needed from the imported module to rewrite their usage site within the flattened module.

Because of the complexity of the fix, and the viable work around, I think fixing is a low priority, but opening for tracking purposes so that others can understand the current limitation.

**Comment by ry** [comment]
I haven't experienced this lately. Was it fixed?

**Comment by kitsonk** [comment]
@ry I don't think so, at least not intentionally.  Worth taking a look at.

**Comment by bartlomieju** [comment]
@kitsonk does this issue still occur?

**Comment by kitsonk** [comment]
I think we have reached a stasis of how we use the tool that it is no longer a challenge
