### ISSUE TITLE
`Transferable` missing from lib.dom.d.ts

### ISSUE THREAD

**Issue by surma** [denoland/deno#11139]
Now with #11076 landed, it makes sense to add the `Transferable` type to `lib.dom.d.ts`.

From [Typescript’s `lib.dom.d.ts`](https://github.com/microsoft/TypeScript/blob/11b38676b0e23ff109ed822942300420a0c7a8fb/lib/lib.dom.d.ts#L19703):
```ts
type Transferable = ArrayBuffer | MessagePort | ImageBitmap | OffscreenCanvas;
```

I’m happy to add it, but wanted to check first if `lib.dom.d.ts` is manually maintained or if there’s some sort of automation.

**Comment by lucacasonato** [comment]
`lib.dom.d.ts` is vendored from TS - it isn't manually updated by us. I guess we just haven't updated it in a while. So to update, just copy over the exact file from TS repo :-)

**Comment by surma** [comment]
That is within my skillset

**Comment by surma** [comment]
Never mind me. I’m a muppet.

**Comment by kitsonk** [comment]
> `lib.dom.d.ts` is vendored from TS - it isn't manually updated by us. I guess we just haven't updated it in a while. So to update, just copy over the exact file from TS repo :-)

We always update it when we update TypeScript versions. It is current of TypeScript 4.3.2.
