### ISSUE TITLE
deno quit when exporting oak module

### ISSUE THREAD

**Issue by Srabutdotcom** [denoland/deno#11137]
Dear team,

I use deno version 1.11.2
and have been trying to export oak module but the app quit without any error message.

~~~js
import { Application } from "'https://deno.land/x/oak/mod.ts'";
const app = new Application();
export {app}
~~~

and then when i call deno run, it is just quit.....

What is wrong?

**Comment by satyarohith** [comment]
Can you share the code where you're importing the `app`?

**Comment by Srabutdotcom** [comment]
> Can you share the code where you're importing the `app`?

~~~js
import {app} from '../start.js'
await app.listen({ 
      hostname: localhost, 
      port: 80})
~~~

even before reaching this line, deno quit.
