### ISSUE TITLE
lsp: diagnostics not cleared after updates to `import_map.json`

### ISSUE THREAD

**Issue by sramam** [denoland/deno#11146]
vs-code needs to be restarted after updates to `import_map.json`

- `.vscode/settings`
```
{
  "deno.enable": true,
  "deno.lint": true,
  "deno.unstable": true,
  "deno.importMap": "./import_map.json",
}
``` 
- `import_map.json`
```
{
  "imports": {
    "git": "https://esm.sh/isomorphic-git?target=deno"
  }
}
```

Before a restart:
![image](https://user-images.githubusercontent.com/518574/123518963-49006f80-d65d-11eb-97ba-73a813a67361.png)

After a restart:
![image](https://user-images.githubusercontent.com/518574/123519002-8664fd00-d65d-11eb-983d-71f83c9c86a0.png)

**Comment by kitsonk** [comment]
This is due to diagnostics not being invalidated or cleared in the lsp when the config changes. I suspect editing the document would have the same effect as restarting.

**Comment by sramam** [comment]
True dat! I can confirm this happens on editing the document too.

**Comment by sramam** [comment]
Are local imports different than remote imports? 

These stale LSP errors seem to only impact changes made to import_map.json or to relative paths from such imports. 
Changes to local files imports take effect instantly.

I'm don't yet have a deep understanding of the inner workings of Deno - apologies if this is not useful.
