### ISSUE TITLE
Deno Secure Websocket Client

### ISSUE THREAD

**Issue by NulledJosh** [denoland/deno#11153]
For some resson, secure websockets do not work in deno. Insecure websockets like `ws://echo.websocket.org` work. You can open a secure websocket, but the readystate never gets set to 1.
```typescript
const websocket = new WebSocket("wss://echo.websocket.org");
websocket.addEventListener('open', (event:any) => {
    console.log(event)
});
```

**Comment by crowlKats** [comment]
that website has an old certificate and doesnt meet up to rusttls standards. if you would listen to the error event you would get an event there.
