### ISSUE TITLE
Refactor away the test runner from the snapshot

### ISSUE THREAD

**Issue by caspervonb** [denoland/deno#11169]
Just to set up a motivating example for allowing return values from within execute functions (#11129).

I'd like to end up with an API looking something like this in Rust.

```rs
let test_runner = create_test_runner(program_state, test_module).await?;
let test_definitions = test_runner.filter_definitions().await?;
let test_reporter = create_test_reporter(TestReporterKind::Pretty)?;

for let test_definition in test_definitions {
  let test_result = test_runner.run_test(test_definition).await?;
  test_reporter.report_result(test_description, test_result);
}
```

This would let us remove all the convoluted `runTest` bits that communicate over channels.
To do this we need to:
- Be able to serialise test definitions into Rust via execute (omitting the Function is fine I guess, we can invoke it via index).
- Be able to invoke the test definitions and get the result of the invocation

**Comment by bartlomieju** [comment]
After some more consideration I'm not in favor of this change. I believe the current state of test runner is a good balance between Rust and JS communication and this refactor would increase the complexity. Closing for now.
