### ISSUE TITLE
op to give number of open "resources" 

### ISSUE THREAD

**Issue by ry** [denoland/deno#1117]
Resources (AKA `rid`) are Deno's version of file descriptors. They are integer values used to refer to open files, sockets, and other concepts. For testing it would be good to be able to query the system for how many open resources there are.

The table that holds them is here:
https://github.com/denoland/deno/blob/8b39d2c99ef41736bb1d5b74ccda2f3aa6223e84/src/resources.rs#L41

Maybe call this `deno.numResources()` 

Alternatively we could have `deno.resources()` which returns a list of different open resources and their ids. It might look like this `[ [0, "stdin"], [1, "stdout"], [2, "stderr"], [7, "httpBody"] ]`

**Comment by bartlomieju** [comment]
I'll do it

**Comment by ry** [comment]
landed in 946acbc
