### ISSUE TITLE
deno test --doc should be able to typecheck Markdown files

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#11170]
`deno test --doc` should typecheck codeblocks in Markdown files by default. 

It will make it easier to keep documentation up to date, especially keeping Deno manual examples working on each commit.

Doing so will keep it inline with `deno fmt` and `deno lint` which can already act on Markdown files.

CC @caspervonb

**Comment by caspervonb** [comment]
I've implemented this but... we do make use of a special marker `STD_VERSION` which means these fenced code blocks aren't currently valid so we need to either remove that or work around it *somehow* without making the test runner even more complicated.
