### ISSUE TITLE
deno compile; add an option to have no foreground window when .exe is ran

### ISSUE THREAD

**Issue by John-Dean** [denoland/deno#11185]
Hi,

I have a small sample script running on Deno 1.8.3 (webview has problems on the latest Deno version)

```js
import { Webview } from "https://deno.land/x/webview@0.5.6/mod.ts";

const html = `
  <html>
  <body>
    <h1>Hello from deno v${Deno.version.deno}</h1>
  </body>
  </html>
`;

const webview = new Webview(
  { url: `data:text/html,${encodeURIComponent(html)}` },
);
await webview.run();
```

When this is compiled on Windows, for example using: `deno compile --allow-all --unstable sample.js` I get an output .exe, this is expected.

When I run said .exe, I first get a Command Prompt window spawn, which then runs the code and spawns a webview. Unfortunately I'm then left with a webview window and a Command Prompt which cannot be closed.

Could we add an option to compile so that it doesn't spawn a foreground window? i.e. upon clicking the .exe nothing visually happens until the webview would spawn in my example.

Apologies if I have missed this in the documentation.

Thanks,
John

**Comment by John-Dean** [comment]
Hi, completely understand that this would not be a priority, but this would be a huge feature for me. It would allow me to replace electron with deno in basically all use cases if this were added. Is there any possibility of adding this to the future plans?

**Comment by bartlomieju** [comment]
Hi @John-Dean, it is indeed a low priority for the core team at the moment. That said, we'd gladly accept PRs that implement this change.

**Comment by Inplex-sys** [comment]
still waiting for it

**Comment by John-Dean** [comment]
#17991 #17990 Seem to resolve this

**Comment by littledivy** [comment]
Seems fixed with `--no-terminal`. Closing
