### ISSUE TITLE
thread 'main' panicked after hours of websocket message handling

### ISSUE THREAD

**Issue by WardCunningham** [denoland/deno#11199]
As requested, https://discord.com/channels/684898665143206084/684911491035430919/859917195421024277

For seven months I have been writing web applications handling websocket messages from the closed source but free to use amateur radio application sparkSDR. I have been reviving some server-side ambitions for the same data stream and been tweaking a program written to study some ping-pong deficiencies from months ago. I'm excited that Deno can hold a stream up though it could easily be changes in sparkSDR which has cycled through .net core libraries.

I found that my script error'd out after several hours of collecting a single field out of ten to twenty "spots" in a websocket message data field.

```
deno run --allow-net console.js >>dt
thread 'main' panicked at 'assertion failed: lines.len() > line_number', cli/program_state.rs:409:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
zsh: abort      deno run --allow-net console.js >> dt
```
I am rerunning a slightly modified script (Deno.args processing) with the requested `RUST_BACKTRACE=1`. This has not failed after running twice as long and handling half as many spots. The radio traffic volume varies through the day so I will leave it running over night and into the same time next morning.

I haven't touched the output file after the fail.
```
wc dt
   26806   26814  375667 dt
```
Nothing unusual at the end of the file.
```
tail dt
0.5
0.1
0.1
0.1
0.2
0.1
0.6
0.3
0.1
0.1
```
This is the script I was running. 
```
// Listen to SparkSDR and report payloads heard.
// usage: deno run --allow-net console.js

// {
//   "cmd": "spotResponse",
//   "spots": [
//     {
//       "time": "2021-06-29T21:14:00Z",
//       "frequency": 14076666,
//       "tunedfrequency": 14074303,
//       "power": 0,
//       "drift": 0,
//       "snr": 11,
//       "dt": 0.2,
//       "msg": "CQ K7REK CN85",
//       "mode": "FT8",
//       "distance": 22.8393423022036,
//       "call": "K7REK",
//       "color": 1,
//       "locator": "CN85",
//       "valid": true,
//       "offsetFrequency": 2363,
//       "rxid": 1
//     }, ...


const socket = new WebSocket('ws://localhost:4649/Spark')
const handle = (event) => console.log(`handle ${event.type} at ${new Date().toLocaleTimeString()}`)

socket.addEventListener('open', (event) => {
  handle(event)
  socket.send('{"cmd":"subscribeToSpots","Enable":true}')
})

socket.addEventListener('message', report)
socket.addEventListener('error', handle)
socket.addEventListener('close', handle)

function report(event) {
  let msg = JSON.parse(event.data)
  for (let spot of msg.spots) {
    console.log(spot.dt)
  }
}
```

Install Details.
```
deno -V
deno 1.11.2
```
![image](https://user-images.githubusercontent.com/12127/124058651-a2aac600-d9de-11eb-8951-5aa65c264099.png)

**Comment by WardCunningham** [comment]
I should mention that I had several other processes reading the same websocket stream, these were not affected. One was a webapp that I have been using for many months. The other was an improved console.js deno script that was collecting other fields from the same stream.

**Comment by WardCunningham** [comment]
I've now run for near 24 hours with no failure.
```
RUST_BACKTRACE=1 deno run --allow-net console.js dt >>dt2
```
I'm not running the identical script. The improved version takes arguments.
```
const socket = new WebSocket('ws://localhost:4649/Spark')

socket.addEventListener('open', event =>
  socket.send('{"cmd":"subscribeToSpots","Enable":true}')
)

socket.addEventListener('message', event => {
  let payload = JSON.parse(event.data)
  for (let spot of payload.spots ?? []) {
    let columns = Deno.args.map( field => spot[field] )
    console.log(columns.join("\t"))
  }
})
```

**Comment by littledivy** [comment]
This should be fixed with the recent switch to fastwebsockets and JS rewrite. Closing.
