### ISSUE TITLE
AssertionError where "data" is unexpectedly null when a file contains only triple slash references

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#11196]
**A.d.ts**

```ts
declare class Test {
}
```

**test.ts**

```ts
/// <reference path="./A.d.ts" />
```

**Output**

```
> deno run test.ts
Check file:///V:/dprint-plugins/test.ts
error: AssertionError: "data" is unexpectedly null for "file:///V:/dprint-plugins/A.d.ts".
    at assert (deno:cli/tsc/99_main_compiler.js:68:13)
    at Object.getSourceFile (deno:cli/tsc/99_main_compiler.js:286:7)
    at findSourceFileWorker (deno:cli/tsc/00_typescript.js:111060:29)
    at findSourceFile (deno:cli/tsc/00_typescript.js:110970:26)
    at deno:cli/tsc/00_typescript.js:110922:85
    at getSourceFileFromReferenceWorker (deno:cli/tsc/00_typescript.js:110889:34)
    at processSourceFile (deno:cli/tsc/00_typescript.js:110922:13)
    at deno:cli/tsc/00_typescript.js:111208:17
    at Object.forEach (deno:cli/tsc/00_typescript.js:384:30)
    at processReferencedFiles (deno:cli/tsc/00_typescript.js:111207:16)
```

Deno 1.11.3

I had a more complex scenario and will maybe open a separate issue for that if I can figure out a more minimal example. The above is ok once adding a statement to test.ts.

**Comment by dsherret** [comment]
I'll just put my other same error in here with a non-empty file

**types/deploy.d.ts**

```ts
/// <reference path="./deploy.fetchevent.d.ts" />
```

**types/deploy.fetchevent.d.ts**

```ts
// Copyright 2018-2021 Deno Land Inc. All rights reserved. MIT license.

// deno-lint-ignore-file

/// <reference no-default-lib="true" />
/// <reference lib="esnext" />

declare class FetchEvent extends Event {
    request: Request;
    respondWith(response: Response | Promise<Response>): void;
}
```

**test.tsx**

```ts
/// <reference no-default-lib="true"/>
/// <reference lib="esnext" />
/// <reference path="./types/deploy.d.ts" />

/** @jsx h */
/** @jsxFrag Fragment */
import { h } from "https://x.lcas.dev/preact@10.5.12/mod.js";

function App() {
    return (
        <html>
            <head>
                <title>Hello from JSX</title>
            </head>
            <body>
                <h1>Hello world</h1>
            </body>
        </html>
    );
}
```

**Output**

```
> deno run test.tsx
Check file:///V:/dprint-plugins/test.tsx
error: AssertionError: "data" is unexpectedly null for "file:///V:/dprint-plugins/types/deploy.fetchevent.d.ts".
    at assert (deno:cli/tsc/99_main_compiler.js:68:13)
    at Object.getSourceFile (deno:cli/tsc/99_main_compiler.js:286:7)
    at findSourceFileWorker (deno:cli/tsc/00_typescript.js:111060:29)
    at findSourceFile (deno:cli/tsc/00_typescript.js:110970:26)
    at deno:cli/tsc/00_typescript.js:110922:85
    at getSourceFileFromReferenceWorker (deno:cli/tsc/00_typescript.js:110889:34)
    at processSourceFile (deno:cli/tsc/00_typescript.js:110922:13)
    at deno:cli/tsc/00_typescript.js:111208:17
    at Object.forEach (deno:cli/tsc/00_typescript.js:384:30)
    at processReferencedFiles (deno:cli/tsc/00_typescript.js:111207:16)
```

**Comment by kitsonk** [comment]
@dsherret what happens when you use triple slash `types`:

```ts
/// <reference types="./A.d.ts" />
```

You need to be on canary I believe for it to work.

**Comment by dsherret** [comment]
@kitsonk it works with types.

**Comment by kitsonk** [comment]
Hmmm... ok... I am not totally sure why `path` doesn't work.  It should.  The module isn't being added to the module graph, though it should via the dependency analysis.

With the `path` what does `deno info` say?

**Comment by dsherret** [comment]
@kitsonk it says the following:

```
> deno info test.ts
local: V:\dprint-plugins\test.ts
type: TypeScript
emit: C:\Users\david\AppData\Local\deno\gen\file\V\dprint-plugins\test.ts.js
dependencies: 0 unique (total 35B)

file:///V:/dprint-plugins/test.ts (35B)
```

**Comment by kitsonk** [comment]
Yeah, it looks like either the detection of `.d.ts` files in triple-slash references has regressed or never worked.  We obviously don't have a test for it.  I can take a look and fix it if you want, but it feels like a good one to get more familiar with the hornet's nest that is module graph 😄 .  I can say that because I wrote most of it.

**Comment by dsherret** [comment]
@kitsonk I was thinking the same thing too. I will take a look 😊

**Comment by dsherret** [comment]
This is because swc incorrectly puts comments in a file without comments in the _trailing_ comment map at position 0, instead of the _leading_ comment map at position 0. I've noticed this swc behaviour before, but just worked around it in the past because I was lazy. Instead of us also working around it, it would be appropriate to just submit a fix to swc so I've opened https://github.com/swc-project/swc/pull/1879

Once that's merged and released I'll open a PR with a test for this.

**Comment by kitsonk** [comment]
> This is because swc incorrectly puts comments in a file with only comments in the trailing comment map at position 0, instead of the leading comment map at position 0.

That being said, I suspect trailing comments are valid positions for triple-slash references. Should we may not analyze them too?

**Comment by dsherret** [comment]
@kitsonk we're good! https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html

> Triple-slash directives are only valid at the top of their containing file. A triple-slash directive can only be preceded by single or multi-line comments, including other triple-slash directives. If they are encountered following a statement or a declaration they are treated as regular single-line comments, and hold no special meaning.
