### ISSUE TITLE
Pre-parse script arguments by system parser

### ISSUE THREAD

**Issue by yerlaser** [denoland/deno#11194]
Since deno is itself a program that parses it's own arguments to run scripts, I thought that it could also parse the arguments provided to the script.
The arguments need not be deleted, they can stay, but the parsed arguments and options can then be accessed  by scripts via a special built-in constant or function.
This can also be done via a switch to deno, e.g. --parse-args

This will make deno a powerfull alternative to Bash for writing scripts as parsing arguments is needed in most of the complex scripts and it is best to be available by default without additional downloads.

**Comment by MarkTiedemann** [comment]
There's [`Deno.args`](https://doc.deno.land/builtin/stable#Deno.args), a simple array containing the arguments.

If you want a higher level API, there's also the [`flags`](https://deno.land/std@0.100.0/flags) module of the std lib.

**Comment by kitsonk** [comment]
As mentioned, this feature already exists with a more usable API for it as part of the Deno `std` library.

**Comment by yerlaser** [comment]
Sorry, I was not clear enough in the original post.
Yes, I am aware of the existence of Deno.args.
But, those are raw arguments.

I meant that since Deno already parses it's own arguments for flags and options, it could do that also for the arguments supplied to the script and store them in, say, Deno.parsed_args with flags and options as key/value pairs.
This way the scripts will not need to import and download an external library.

**Comment by kitsonk** [comment]
Parsing args is "opinionated".  Some things that are opinionated like that are left as part of the `std` library intentionally.

**Comment by yerlaser** [comment]
I agree with that.
However, even the way Deno parses it's arguments could be sufficient for the majority of script writers.

It can be a deal breaker for case for example corporate servers or workstations that are behind firewalls and cannot download dependencies from Internet.
And parsing arguments is rather important for a certain class of "bootstrap" or setup scripts.

At the same time, from an outsider's view, of course, this should be quite easy to implement. Everything is already there, perhaps, just some indexes or conditions need to change so parsing doesn't stop at the script name.

**Comment by kitsonk** [comment]
>It can be a deal breaker for case for example corporate servers or workstations that are behind firewalls and cannot download dependencies from Internet.

This is why things like `deno bundle` and `deno compile` are a thing.

> And parsing arguments is rather important for a certain class of "bootstrap" or setup scripts.

One person's definition of rather important varies.  Depends on what you are going to do.  Basically the only things we try to build into Deno directly are things that are web standards or require privileged access to the host system.  Things that can be run in user land are left to `std`.  We are even moving "opinionated" things that simply were some userland code we originally put in the `Deno` namespace into `std`.  There is another 3rd category, which the native HTTP falls into, which is for performance reasons, where a userland/JavaScript implementation is way too slow.  This certainly wouldn't be the case with parsing the `Deno.args` into a friendly API.
