### ISSUE TITLE
Provide detailed version information in a hosted file

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#11195]
We should provide a hosted file at dl.deno.land (dl.deno.land/stable/all.json maybe?) with information about all Deno versions. The information for each version should contain:

- the Deno version
- release date
- commit it was built from
- V8 version
- TSC version

Ref https://github.com/mdn/browser-compat-data/pull/10753#discussion_r661733670

We should also provide `dl.deno.land/stable/$version/version.json` files for the details for just a specific version.

**Comment by wperron** [comment]
How does it differ from the version file we already serve on cdn.deno.land?

**Comment by lucacasonato** [comment]
That doesn't include release date, commit, v8 version, or tsc version.

**Comment by lucacasonato** [comment]
Not going to do this anymore.
