### ISSUE TITLE
Add or document a way to get an exclusive lock (flock) on files

### ISSUE THREAD

**Issue by Nemo64** [denoland/deno#11192]
I haven't found a way to get an exclusive lock on a file using the Deno api.

I have the following code:
```js
const file = await Deno.open('test.tmp', {write: true, append: true, create: true});
await Deno.write(file.rid, new TextEncoder().encode(`${Deno.args[0]} start\n`));
await Deno.fdatasync(file.rid);
await new Promise(resolve => setTimeout(resolve, 5000));
await Deno.write(file.rid, new TextEncoder().encode(`${Deno.args[0]} stop\n`));
await Deno.fdatasync(file.rid);
await Deno.close(file.rid);
```

If you run this script twice in parallel using this command...
```
deno run --allow-write flock.ts test1 & deno run --allow-write flock.ts test2
```

You get a `test.tmp` file with this content
```
test1 start
test2 start
test2 stop
test1 stop
```

What I would want is to exclusively lock the file while it is open so noone can open it in while 1 process is working on it.
The expected result then would be:
```
test1 start
test1 stop
test2 start
test2 stop
```

Searching for it is kind of hard since all `lock` result talk about dependencies. The linux term for this is [flock](https://linux.die.net/man/2/flock). It also looks like node is not natively supporting file locks either. I found an old about it here: https://github.com/nodejs/node-v0.x-archive/issues/1213 which talks about solaris support issues.

Other programming languages simply expose flock and talk about potential issues, like [php's flock](https://www.php.net/manual/en/function.flock.php).

I could imagine `Deno.flock` or `Deno.open('test.tmp', {exclusive: true})`.

Any thoughts or advises?

**Comment by bartlomieju** [comment]
There are currently no APIs that implement that functionality; let's continue in https://github.com/denoland/deno/issues/11511
