### ISSUE TITLE
lsp: include all modules in language server scope for a enabled folder automatically

### ISSUE THREAD

**Issue by oganexon** [denoland/deno#11190]
### test

**Describe the bug**

When using **Go to references**, the extension doesn't find references in files that are not opened in the editor.

**To Reproduce**

```ts
// a.ts
export const a = 0;
```
```ts
// b.ts
import { a } from "./a.ts";
```
```ts
// c.ts
import { a } from "./a.ts";
```

Open `a.ts` and `b.ts`, go to references of `a`. No references in `c.ts`.

**Expected behavior**

`c.ts` should appear in the panel.
This makes this feature useless if you have to open every file in your project to find references

**Screenshots**

![reference](https://user-images.githubusercontent.com/52361520/123939794-d236df80-d998-11eb-9aa9-28149f6619cf.gif)

**Versions**

vscode: 1.57.1 deno: 1.11.3 extension: 3.6.1

**Comment by kitsonk** [comment]
Current we do not analyse files that aren't dependencies of opened files that are unopened. For `tsc` you can specify "files" or "include" but Deno doesn't work that way, as you supply a "root" module on the command line. Since we don't have that concept in an editor at the moment, we treat every file when opened as a "root" file.

An enhancement which might be worth considering is allowing the roots to be specified in the config. Which means that we would always include it and its dependencies irrespective of what files were open.

**Comment by bxantus** [comment]
In my opinion the whole workspace should be scanned, at least it should be an option.
You can have multiple "root" modules in a solution (like having a debug/release or any other kind of configuration), and usually you are interested in all usages, not just the ones from one "root" module.

(I created an issue in the vscode extension repo, which is closed as a duplicate. I would implement this functionality in the extension, built on top of the facilities which are provided by the lsp. The lsp should support only the discovery of file dependencies, to avoid duplicate searches from the extension)

**Comment by kidonng** [comment]
In my opinion this is a showstopper for serious development using Deno. One has to either consult plain old editor search, or remember to open _all_ files including the symbol, which is impossible for any reasonably large project, or a (open source) project you are not familiar with.

**Comment by itsMapleLeaf** [comment]
Just mentioning that this is still one of the bigger holdbacks from using Deno in a serious project

**Comment by bartlomieju** [comment]
Discussed this with @dsherret this week. We have an idea how to fix this problem. We'll update the issue with description of necessary steps in a couple days.

**Comment by aapoalas** [comment]
Partially related to #17663 which intends to add a `--side-module(s?)` / `--import(s?)` / `--module(s?)` flag to enable multiple roots in the Deno module graph.
