### ISSUE TITLE
Improvements to `Deno.run()` or perhaps add `Deno.exec()`

### ISSUE THREAD

**Issue by sramam** [denoland/deno#11208]
IMHO, making `Deno.run()` behave like node's `child_process.exec()` would better meet the cross-platform claims of Deno.

Currently, `Deno.run({cmd: ['npm', 'init','-y']})` works on WSL (and I suspect all *nix) but not on Windows. 
The current documentation for `Deno.run()` leads one to believe this should work cross-platform. 

The first challenge was that `Deno.RunOptions` is not documented. It's `env` property raises expectations, but fails to deliver on windows. 

To truly make a `Deno.run` cross platform, one has to implement something along the lines of the code below:
(ht: this has been adapted from what velociraptor does) 
```
async function DenoRun(command: string, cwd: string, msg: string = command) {
  const sh = resolveShell();
  const prefix = Deno.build.os === "windows" ? "/C" : "-c";
  const cmd = [sh, prefix, command];
  return await Deno.run({
    cmd,
    cwd,
    stdout: "piped",
    stderr: "piped",
  });
}

function resolveShell(): string {
  const shells: string[] =
    Deno.build.os === "windows"
      ? [
          Deno.env.get("ComSpec") as string,
          `c:/Windows/System32/WindowsPowerShell/v1.0/powershell.exe`,
          `c:/Windows/system32/cmd.exe`,
          `cmd.exe`,
        ]
      : [Deno.env.get("SHELL") as string, "sh"];

  return shells.reduce((sh, curr) => {
    try {
      sh = sh ? sh : Deno.statSync(curr).isFile ? curr : ``;
    } catch {
      // try next shell
    }
    return sh;
  }, ``);
}

```
IMHO, this should be the default behavior of `Deno.run()` or be exposed as `Deno.exec()`. Though I prefer the former.

**Comment by wperron** [comment]
The `Deno.run` API is being revisited in https://github.com/denoland/deno/discussions/9435, closing in favor of that discussion.
