### ISSUE TITLE
plugins: argument of ops should support skipped field

### ISSUE THREAD

**Issue by garyhai** [denoland/deno#11207]
When change the struct TestArgs of test_plugin/src/lib.rs:

```rust
#[derive(Debug, Deserialize)]
struct TestArgs {
  val: String,
  //If the value is not present when deserializing, use the Default::default().
  #[serde(default)]
  skip: String,
}
```

Run the test according to README then get error report:

```
error: Uncaught TypeError: Error parsing args: serde_v8 error: ExpectedString
  const result = Deno.core.opSync
```

It is very useful for optional arguments.

**Comment by bartlomieju** [comment]
We'll be removing native plugins in the near future #10908 so we won't be adding new features for this API. Respectfully closing.
