### ISSUE TITLE
Deno.stat() returns different Error messages on Windows vs *nix.

### ISSUE THREAD

**Issue by sramam** [denoland/deno#11210]
Note that both are running Deno 1.11.1.
Unsure if this is a rust thing or a deno thing, but makes writing cross platform code needlessly harder.

### Windows:
```
c:\tmp\deno-run>deno
Deno 1.11.1
exit using ctrl+d or close()
> Deno.stat('.tmp/junk')
Promise {
  <rejected> NotFound: The system cannot find the path specified. (os error 3)
    at deno:core/core.js:86:46
    at unwrapOpResult (deno:core/core.js:106:13)
    at async Object.stat (deno:runtime/js/30_fs.js:222:17)
}
```

### *nix:
```
$ deno
Deno 1.11.1
exit using ctrl+d or close()
> Deno.stat('.tmp/junk')
Promise {
  <rejected> NotFound: No such file or directory (os error 2)
    at deno:core/core.js:86:46
    at unwrapOpResult (deno:core/core.js:106:13)
    at async Object.stat (deno:runtime/js/30_fs.js:222:17)
}
```

**Comment by sramam** [comment]
This seems to be an issue with File exists for `Deno.mkdir()` too:

### Windows:
```
> Deno.mkdir('.tmp/junk')
Promise {
  <rejected> NotFound: The system cannot find the path specified. (os error 3)
    at deno:core/core.js:86:46
    at unwrapOpResult (deno:core/core.js:106:13)
    at async Object.mkdir (deno:runtime/js/30_fs.js:101:5)
}
```

### *nix
```
> Deno.mkdir('.tmp/junk')
Promise {
  <rejected> AlreadyExists: File exists (os error 17)
    at deno:core/core.js:86:46
    at unwrapOpResult (deno:core/core.js:106:13)
    at async Object.mkdir (deno:runtime/js/30_fs.js:101:5)
}
```

**Comment by caspervonb** [comment]
It's just the message that differ, errno 17 on unix and error code 183 on Windows.
Working as intended.

Why would this have any effect on portability?

**Comment by sramam** [comment]
In general, it's not unreasonable to have to discriminate between more than one error when making system calls. 
Current deno FS errors don't provide a way to discriminate except by error message (lacking uniform error codes)
Having different messages for the same error on different OS' makes that a much larger conditional block than ideal.
This makes both development and the code more messy and time-consuming. 

I encountered this while building [iso-git](https://github.com/sramam/iso-git), a Deno wrapper for isomorphic-git.
This needed a node-fs shim (different from the one in Deno std-lib), because isomorhpic-git relies on the node-fs error
codes - [an example](https://github.com/isomorphic-git/isomorphic-git/blob/89c0da78d5ebf3c9f2754b3c8d557155dd70c8d7/src/models/FileSystem.js#L100).

It was rather painful to find and discover all cases of this. A simple error-code or consistent error messages would have been a great help here.

Hopefully this illustrates the use-case. Please let me know if more details would help

**Comment by kitsonk** [comment]
> Currently deno FS errors don't provide a way to discriminate except by error message

It does...

```ts
try {
  Deno.mkdir('.tmp/junk')
} catch (e) {
  if (e instanceof Error && e.name === "AlreadyExists") {
    console.log("file already exists");
  }
}
```

**Comment by kitsonk** [comment]
Or

```
try {
  Deno.mkdir('./tmp/junk')
} catch (e) {
  if (e instanceof Deno.errors.AlreadyExists) {
    console.log("file already exists");
  }
}
```

**Comment by sramam** [comment]
Thank you. Until this message, I didn't discover the Error Types. Sorry for the bother.
