### ISSUE TITLE
Default file extension inconsistency in the `deno run` cli

### ISSUE THREAD

**Issue by zhangyuannie** [denoland/deno#11220]
```
curl https://deno.land/std/examples/welcome.ts | deno run - 
```
Will run stdin as a TypeScript file.

https://github.com/denoland/deno/blob/0385a990529399775b76db4c27704faa4a092efa/cli/main.rs#L796

However,
```
deno run extensionless_file
```
execute `extensionless_file` as a JavaScript file.

I believe we should ideally consolidate the default behaviour of `deno run` when the file extension is not specified. Maybe for Deno 2.0?

Also Deno has different default in general regarding the `--ext` flag: `deno fmt` uses `ts` by default, while `deno eval` uses `js`.

**Comment by Hrushi20** [comment]
Which file extension do we use as the default behavior of `deno run`?

**Comment by lucacasonato** [comment]
- `deno lint -` defaults to TS
- `deno fmt -` defaults to TS
- `deno run -` defaults to TS
- `deno lint extensionless` does not work at all
- `deno fmt extensionless` does not work at all
- `deno run extensionless` defaults to JS

What we are going to do is:

- stdin behaviour stays as is
- extensionless files default to TS everywhere (entrypoint and imported)
- `--ext` flag can be used to override the media type of the entrypoint file + stdin, but not other extensionless files (ie ones imported from within the entrypoint).
