### ISSUE TITLE
Wanted: gista clone in deno

### ISSUE THREAD

**Issue by ry** [denoland/deno#1123]
All the components for doing a ["gista"](https://www.npmjs.com/package/gista) like clone in deno are there. Here's the basic outline of what to do:
```
deno gista.ts /etc/passwd
```
1. Read the GIST_GITHUB_TOKEN from `deno.env()`
2. Using `fetch()`, [which now supports HTTPS](https://github.com/denoland/deno/commit/9b8f77f5253a2c731d3ae53de4cb14648e74292d), abstract the [github gist API](https://developer.github.com/v3/gists/) into a module.
3. Read files supplied on the command line. `deno.readFileSync(deno.args[1])`
4. Post supplied files to gist.
5. Please report issues if we are missing some functionality!

It would be nice if it was clean and short, so it could serve as an example program for others.

**Comment by cedric05** [comment]
i will try to do this.

**Comment by TehShrike** [comment]
This implementation is pretty close https://github.com/TehShrike/gistd but is blocked by #1133.

**Comment by ry** [comment]
I have a working example here: https://gist.github.com/ry/f3c3449b64806e1d58c9ea021ffb40cd

It needs #1194

**Comment by bartlomieju** [comment]
Done with [`gist.ts` in `deno_std`](https://github.com/denoland/deno_std/blob/master/examples/gist.ts)
