### ISSUE TITLE
deno upgrade --version <v>: v isn't escaped

### ISSUE THREAD

**Issue by ihack2712** [denoland/deno#11237]
When running `deno upgrade --version ../../../etc` you can change the download url. *v* should be properly escaped.

<img width="849" alt="image" src="https://user-images.githubusercontent.com/35933830/124335977-8c4a6900-db9c-11eb-89f0-6d67e21f2965.png">

**Comment by crowlKats** [comment]
whoops completely forgot to add such logic when rewriting upgrade 😅
