### ISSUE TITLE
Allow declaring environment variables for `Deno.env`

### ISSUE THREAD

**Issue by Chooks22** [denoland/deno#11268]
Current declaration of `Deno.env` uses [`export const env`](https://github.com/denoland/deno/blob/5addba2abc2e384e751e8884b4ac3219688c2473/cli/dts/lib.deno.ns.d.ts#L199) with hardcoded types which cannot be overwritten by `.d.ts` files.

Using an interface instead allows custom key/value pairs to be declared using declaration merging, similiar to how [`@types/node`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/9d59b7aadafb5ee2afac9c4440b82e692a7449c1/types/node/process.d.ts#L96) does it.

**Comment by lucacasonato** [comment]
Why would you want to do this?

**Comment by Choooks22** [comment]
Just started with deno yesterday, thought I'd rewrite a small node server and encountered this while declaring my envs.
Just a little nitpick I had since I've always destructured `process.env` and got auto suggestions for it.

**Comment by lucacasonato** [comment]
In Deno env vars are not keys on the Deno.env object. You read env vars with `Deno.env.get("ACCESS_TOKEN")`.

**Comment by Choooks22** [comment]
Yep, and on my testing this seemed to work:

```ts
declare namespace Deno {
  interface ProcessEnv {
    [index: string]: string;
  }

  export const env: {
    get<T extends keyof ProcessEnv>(key: T): ProcessEnv[T];
    set<T extends keyof ProcessEnv>(key: T, value: ProcessEnv[T]): void;
    delete(key: keyof ProcessEnv): void;
    toObject(): ProcessEnv;
  };
}
```

And with my sample `env.d.ts`:
```ts
declare namespace Deno {
  interface ProcessEnv {
    DENO_ENV: 'production' | 'development';
    PORT: string;
  }
}
```

I get these:
![image](https://user-images.githubusercontent.com/49726759/124387034-9b055d00-dd0f-11eb-98a9-57ed0160fc3d.png)
![image](https://user-images.githubusercontent.com/49726759/124387077-ba9c8580-dd0f-11eb-8f6f-a13bd9747b52.png)

Couldn't seem to override the default `[index: string]: string` tho so I can't get any intellisense inside `Deno.env.get('')`.

**Comment by Choooks22** [comment]
Oh and the errors are from my eslint config, it works just fine 😄

**Comment by kitsonk** [comment]
I suspect we can find a way to add a generic into the type definitions to support "strongly" typing the environment values.

**Comment by dsherret** [comment]
@kitsonk I'm not sure if it's worth it to support this. I think it might be better for people to create their own wrapper around `Deno.env` for use by their application. Then they can properly type that object/class and do runtime assertions on the values received from `Deno.env` in it (ex. in the example above they could do a runtime assertion that `DENO_ENV` is actually either `"development"` or `"production"` or do some fallback behaviour). That also works better for mocking and many other things.

**Comment by lucacasonato** [comment]
We have not seen more demand for this, so I am going to close this.
