### ISSUE TITLE
Deno Fatal javascript OOM in CALL_AND_RETRY_LAST

### ISSUE THREAD

**Issue by mokeyish** [denoland/deno#11263]
![image](https://user-images.githubusercontent.com/16131917/124369357-b20b6700-dc9d-11eb-9e44-146c03c9f712.png)

It seems that this `details` has never been recycled.

![image](https://user-images.githubusercontent.com/16131917/124369441-77ee9500-dc9e-11eb-9f7f-020b2ab2db43.png)

**Comment by littledivy** [comment]
Does it still occur when you increase the old space size of heap? (using `--v8-flags=--max-old-space-size=4096`)

**Comment by mokeyish** [comment]
> Does it still occur when you increase the old space size of heap? (using `--v8-flags=--max-old-space-size=4096`)

Here is my command:
`deno run --v8-flags="--max-old-space-size=48384,--max-heap-size=16384"  --allow-all ./fund-crawler.ts`
