### ISSUE TITLE
Deprecate various Deno stream APIs

### ISSUE THREAD

**Issue by ry** [denoland/deno#11288]
We are moving towards using web streams everywhere (despite the flaws). The current Reader/Writer streams inspired by Go will be moved to deno_std.

The following should be moved to deno_std and deprecated in the Deno runtime
- [ ] Deno.copy
- [x] Deno.iter / Deno.iterSync
- [ ] Deno.Reader
- [ ] Deno.Writer
- [x] Deno.Buffer
- [x] Deno.readAll / Deno.readAllSync
- [x] Deno.writeAll / Deno.writeAllSync

It will be difficult to deprecate Reader/Writer before we can access the file system via Web Streams (https://github.com/denoland/deno/issues/11018). However It should be straightforward to start deprecating copy, iter, Buffer, readAll, writeAll.

**Comment by nayeemrmn** [comment]
Ref #9795.

**Comment by ry** [comment]
Sorry - I missed #9795. That's a better description of this issue. I'll close this one.
