### ISSUE TITLE
console.log in repl invalid escape sequence hangs forever

### ISSUE THREAD

**Issue by littledivy** [denoland/deno#11291]
This is only specific to the repl.

Steps to reproduce:
```
divy@lappy:~$ deno -V
deno 1.11.5

divy@lappy:~$ deno
Deno 1.11.5
exit using ctrl+d or close()
> console.log("\u");

<hangs forever>
```

Expected behaviour:

Node.js: `Uncaught SyntaxError: Invalid Unicode escape sequence`
Firefox 89.0.2: `SyntaxError: malformed Unicode character escape sequence`

**Comment by caspervonb** [comment]
Regression from the refactor and moving inspector around? pretty sure we fixed this before...

**Comment by littledivy** [comment]
Looks like it doesn't accept the input in the first place when I press enter.

**Comment by caspervonb** [comment]
Smaller reproduction:
```ts
String("\u")
```

Or even:
```ts
function a(x) {}
a("\u")
```

**Comment by caspervonb** [comment]
Absolute minimal reproduction:

```ts
("\u")
```

**Comment by caspervonb** [comment]
Remove label console/extensions.
Add label repl.

**Comment by devcui** [comment]
```
devcui@macross ~ % deno -V
deno 1.11.5
devcui@macross ~ % deno
Deno 1.11.5
exit using ctrl+d or close()
> console.log("\u8bf7");
请
undefined
>
```

unicode was alright

**Comment by bitoku** [comment]
If anyone isn't woking on this, I want to tackle this issue!

**Comment by bartlomieju** [comment]
@bitoku please do
