### ISSUE TITLE
Prototypes are not inspectable for many classes with custom inspect implementations

### ISSUE THREAD

**Issue by caspervonb** [denoland/deno#11293]
Continuing from #11257 which was specifically about the panic in the REPL.
Our WebIDL assertions makes it so that prototypes aren't inspectable, for example both of these throw:

```ts
console.log(Response.prototype);
console.log(Request.prototype);
```

**Comment by dsherret** [comment]
It seems to only be specific prototypes. In this case, they are throwing for the same reason as #9880.
