### ISSUE TITLE
A final blankline in a file prevents 100% code coverage

### ISSUE THREAD

**Issue by jaydenseric** [denoland/deno#11327]
A final newline in a file incorrectly prevents 100% code coverage when using the `deno test` and `deno coverage` CLIs.

This is especially a problem because many projects enforce a final newline in files, via [EditorConfig](https://editorconfig.org) (`insert_final_newline` config), linters, or other means.

To reproduce, in `example.js` (note the newline at the end):

```js
export default function example() {
  return true;
}

```

Then, in `example_test.js`:

```js
import example from "./example.js";

Deno.test("Example.", () => {
  example();
});
```

Run:

```sh
deno test --coverage=cov && deno coverage cov
```

And note that the final line 4 is reported as uncovered, resulting in 75% code coverage for the file `example.js`:

```
running 1 test from file:///[redacted]/demo/example_test.js
test Example. ... ok (8ms)

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out (45ms)

cover file:///[redacted]/demo/example.js ... 75.000% (3/4)
   4 |
```

If you delete that final newline in `example.js`, the report changes to 100% code coverage:

```
running 1 test from file:///[redacted]/demo/example_test.js
test Example. ... ok (8ms)

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out (45ms)

cover file:///[redacted]/demo/example.js ... 100.000% (3/3)
```

`deno --version`:

```
deno 1.11.5 (release, x86_64-apple-darwin)
v8 9.1.269.35
typescript 4.3.2
```

**Comment by caspervonb** [comment]
Thanks for the report, in the middle of a major overhaul of the entire thing so these serve as excellent new test fixtures!

Just tagging myself for filtering purposes @caspervonb.

**Comment by jaydenseric** [comment]
@caspervonb is there a PR that should close this issue to track? This small bug makes code coverage via Deno unusable; perhaps a patch just for this could be pulled out of whatever major refactoring work you're doing, if it's a multi-month epic task?

**Comment by caspervonb** [comment]
> @caspervonb is there a PR that should close this issue to track? This small bug makes code coverage via Deno unusable; perhaps a patch just for this could be pulled out of whatever major refactoring work you're doing, if it's a multi-month epic task?

Will be fixed and shipped soon, sorry for leaving this open for so long.
