### ISSUE TITLE
POST requests with fetch aren't working

### ISSUE THREAD

**Issue by TehShrike** [denoland/deno#1133]
Where in this case, "not working" means "isn't sending headers to the server", as near as I can tell.

Reproduction: https://gist.github.com/TehShrike/c8afda9c15b7061e4a57b7d9d7f9777e

This is blocking #1123

**Comment by ry** [comment]
Some pointers:
- currently `op_fetch` is hardcoded to GET, https://github.com/denoland/deno/blob/21dac6646552dcacb68a0ad167723976f27b5c47/src/ops.rs#L412
- The method should be added in this struct: https://github.com/denoland/deno/blob/21dac6646552dcacb68a0ad167723976f27b5c47/src/msg.fbs#L193-L198

**Comment by Ashniu123** [comment]
I'll take this... Just let clear somethings for me please

* Replace `get` by `request` in `ops.rs` like [here](https://hyper.rs/guides/client/advanced/)
* Add a *method* in `msg.fbs` which is a enum of http verbs (get, post,...)
* `fetch.ts` also needs to add a *method* as arg and passed into ???
