### ISSUE TITLE
`decodeURI()` does not exist in documentation

### ISSUE THREAD

**Issue by rikilele** [denoland/deno#11330]
It seems like `decodeURI()` is non-existent on both the stable and unstable runtime API docs.
It is, however, usable in deno (1.11.5) . Is there somewhere else I should refer to when looking for the documentation?

- [Runtime API docs](https://doc.deno.land/builtin/stable)
- [Unstable Runtime API docs](https://doc.deno.land/builtin/unstable)

Apologies in advance if this wasn't the right place to ask! 🙇

**Comment by lucacasonato** [comment]
`decodeURI` (and `encodeURI` and `decodeURIComponent` and `encodeURIComponent`) are JS builtins (like `Array`, `String`, `Math`, or `Uint8Array`). JS builtins are not listed in the runtime API docs. For functions like these you should refer to MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/decodeURI

**Comment by rikilele** [comment]
Thanks for clarifying!
