### ISSUE TITLE
ReadableStream responses are not flushed in chunks

### ISSUE THREAD

**Issue by matthewp** [denoland/deno#11333]
When curling a request to this server I would expect to see each yielded value in chunks. There's a related PR: #8349 but maybe it's not applying to `Response`?

Note that this works if I add a `\n` on the end of the chunk but I don't *think* that's normally required in service workers.

```js
function createStream(iterator) {
  const encoder = new TextEncoder();
  return new ReadableStream({
    async pull(controller) {
      const { value, done } = await iterator.next();

      if (done) {
        controller.close();
      } else {
        const chunk = encoder.encode(value);
        controller.enqueue(chunk);
      }
    },
  });
}

const wait = () => new Promise(resolve => setTimeout(resolve, 2000));

async function * values() {
  yield '1';
  await wait();
  yield '2';
  await wait();
  yield '3';
  await wait();
  yield '4';
  await wait();
}

async function handle(conn) {
  const httpConn = Deno.serveHttp(conn);
  for await (const requestEvent of httpConn) {
    const stream = createStream(values());
    requestEvent.respondWith(new Response(stream, {
      status: 200,
      headers: {
        'content-type': 'text/plain',
        'transfer-encoding': 'chunked'
      }
    }));
  }
}

async function listen(server) {
  for await (const conn of server) {
    handle(conn);
  }
}

export function startServer() {
  const server = Deno.listen({ port: 8080 });
  console.log(`Listening at http://localhost:${8080}`);
  listen(server);
  return server;
}

startServer();
```

**Comment by matthewp** [comment]
I shouldn't say that adding `\n` fixes the issue. It does cause the response to be streamed, however adding a newline changes the contents, so something like HTML where whitespace is significant would produce unwanted results.

**Comment by lucacasonato** [comment]
What you are experiencing is browser behaviour. Browsers buffer up to new lines. If you try the same example with `curl --no-buffer` you will see the correct streaming behaviour:

https://user-images.githubusercontent.com/7829205/125069658-49febb80-e0b7-11eb-94ff-3bdb55a60b7d.mov

**Comment by matthewp** [comment]
Oh interesting! So not a bug at all, my apologies. I'll close but would love to ask a couple of more questions if you don't mind.

I can see that if I manually add newlines that it does indeed stream even without the `--no-buffer` call in curl. However it is always buffering until the full response in the browser. What do I need to do to make it work there?
