### ISSUE TITLE
"Text differed by line endings" error in the Deno github action while checking formatting on Windows

### ISSUE THREAD

**Issue by justinmchase** [denoland/deno#11359]
Locally I ran:

```sh
deno fmt
```

And I can confirm that the files are encoded with `LF` formatting. But when running the deno Github Action on `windows-latest` it produces an error when checking formatting.

```sh
deno fmt --check
```

![image](https://user-images.githubusercontent.com/10974/125206446-f32aea80-e24c-11eb-92bb-6298ebb7a709.png)

* [link to output](https://github.com/justinmchase/deno-dag/runs/3041224548?check_suite_focus=true)

**Comment by dsherret** [comment]
That windows runner likely has `git config --global core.autocrlf` set to `true` so it is checking out the files with crlf.

I would recommend only verifying formatting on your `ubuntu-latest` job. You will save some CI time too.

**Comment by justinmchase** [comment]
> I would recommend only verifying formatting on only one of your non-windows jobs (ex. ubuntu-latest)

I did end up doing that :) 

But of course at some point someone will want to test on windows so I thought you'd want to know since this will break them. 

This action that this bug is referring to is from the standard Deno Action that github auto created for me. I am assuming its published somewhere here in `denoland` and thus I think this bug should probably be reopened and addressed by altering the template for the standard deno github action.

**Comment by dsherret** [comment]
@justinmchase I personally was not aware of this. Thanks for letting us know!

I opened https://github.com/actions/starter-workflows/pull/1006 which will resolve this in the future.
