### ISSUE TITLE
`Deno.emit()` produces bundle with duplicated `const` identifier

### ISSUE THREAD

**Issue by vovacodes** [denoland/deno#11354]
Deno version: `1.11.5`

The repro: https://github.com/vovacodes/try-deno-bundler

<img width="850" alt="Screenshot 2021-07-10 at 18 39 41" src="https://user-images.githubusercontent.com/1524432/125170250-57e33800-e1ae-11eb-9e1b-b614034c7be1.png">

**Comment by kitsonk** [comment]
`deno version` please

**Comment by vovacodes** [comment]
updated, sorry
