### ISSUE TITLE
Errors in a worker's message event handler aren't reported

### ISSUE THREAD

**Issue by andreubotella** [denoland/deno#11350]
```
thread 'worker-0' panicked at 'coding error: either js is polling or the worker is terminated', runtime/web_worker.rs:498:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: Uncaught (in promise) Error: Unhandled error event reached main worker.
    at Worker.#pollControl (deno:runtime/js/11_workers.js:247:23)
```

(In Deno 1.11.5 the panic message doesn't show up  – see #11342.)

### test.js
```js
const worker = new Worker(
  new URL("./worker.js", import.meta.url).href,
  { type: "module" },
);
worker.postMessage({});
```

### worker.js
```js
self.onmessage = () => {
  // Throws a TypeError: Cannot read property 'run' of null
  null.run();
};
```

-----------

Running `null.run()` in the global scope, in a timer task, or in a promise reaction all seem to report the error in stderr, but not in a handler for the `message` event.

This was found while investigating the WPT failures in #11338.

**Comment by andreubotella** [comment]
If an error is thrown during the initial execution of the worker module, or if it's thrown in any asynchronous task other than the `onmessage` handler, the error will be handled by Rust code and will be printed using the [`print_worker_error`](https://github.com/denoland/deno/blob/main/runtime/web_worker.rs#L552) function. However, [the `onmessage` handler](https://github.com/denoland/deno/blob/main/runtime/js/99_main.js#L159), as well as [a worker's `onerror` handler in another worker](https://github.com/denoland/deno/blob/main/runtime/js/11_workers.js#L269), will instead propagate the error to the parent worker using the `op_worker_unhandled_error` op, without printing the error.

The functions that throw these events are asynchronous functions that listen for messages from the worker/parent on a loop, and throwing inside them would stop that loop. However, since they are asynchronous functions, it seems like calling the function itself, and immediately throwing the error afterwards, would work:

```js
if (!errorEvent.defaultPrevented) {
  pollForMessages();
  throw e;
}
```

**Comment by andreubotella** [comment]
Come to think about it, a parent worker's `onerror` handler should use `op_worker_unhandled_error` rather than throw, because the error would be printed in every parent worker until it propagates to the main thread.

**Comment by bartlomieju** [comment]
CC @nayeemrmn this is something you worked on IIRC

**Comment by nayeemrmn** [comment]
I believe we can just remove `op_worker_unhandled_error` and just throw in every case. It doesn't make sense to have this op, in a lot of error cases there is no way to opportunity to call it so it has just led to inconsistent error handling 

> Come to think about it, a parent worker's `onerror` handler should use `op_worker_unhandled_error` rather than throw, because the error would be printed in every parent worker until it propagates to the main thread.

We can differentiate child worker errors from current thread errors. e.g. error thrown in worker "2" spawned by worker "1" spawned by main:
```
error: Uncaught (in worker "2") Error: foo
    at file:///home/nayeem/projects/deno/temp-worker3.js:1:7
error: Uncaught (in worker "1") (in promise) Error: Unhandled error event in child worker.
    at Worker.#pollControl (deno:runtime/js/11_workers.js:267:21)
error: Uncaught (in promise) Error: Unhandled error event in child worker.
    at Worker.#pollControl (deno:runtime/js/11_workers.js:267:21)
```
It makes sense for all the workers being terminated to print _something_.

**Comment by andreubotella** [comment]
> It makes sense for all the workers being terminated to print _something_.

As discussed in https://discord.com/channels/684898665143206084/684911491035430919/891400851007094856, workers don't terminate when an error is thrown after the initial execution of the module. And both of these cases happen in event listeners.
