### ISSUE TITLE
@deno-types should be ignored in js file and --no-check mode

### ISSUE THREAD

**Issue by codehz** [denoland/deno#11366]
it make no sense to check them in this modes
* the **ignore** mean completely ignore its value, do not even parse it

current:
a.js
```javascript
// @deno-types="~/b.d.ts"
import data from "./b.js"
```

b.js
```javascript
export default const value = 42;
```

commandline:
```
deno run --no-check a.js
```

error:
```
error: Relative import path "~/b.d.ts" not prefixed with / or ./ or ../ from "file:///<path>/a.js"
```

**Comment by kitsonk** [comment]
I disagree... Deno is capable of type checking JavaScript files.  Especially in an editor, having the `@deno-types` can provide auto-completion and intellisense even if diagnostic issue are raised.

As far as `--no-check` it is maybe arguable, but `@deno-types` is an explicit directive that says that the types are part of the dependency graph, even if they aren't enforced and a resolution issue there is a resolution issue.  The graph is built independent of what is then subsequently done with the graph (be it type checking or just emitting).  People would expect a `deno cache --no-check` to grab all the dependencies, just not enforce the types.  Having different behaviour with `--no-check` and check would become quickly problematic.

I personally don't think anything should be changed.
