### ISSUE TITLE
Fedora28 missing libtinfo.so.5 required by clang_format

### ISSUE THREAD

**Issue by orenwf** [denoland/deno#1137]
https://github.com/denoland/deno/blob/198e396eadad704e96c9f37e24effc89a904f570/tools/format.py#L24-L26

Workaround I found, which works on Fedora28, is to symlink existing `libtinfo.so.6` as follows:
`sudo ln -s /usr/lib64/libtinfo.so.6 /usr/lib64/libtinfo.so.5`

https://github.com/commercialhaskell/stack/issues/1012#issuecomment-370929682

**Comment by bartlomieju** [comment]
@orenwf does this issue still occur with latest release?

**Comment by ry** [comment]
stale
