### ISSUE TITLE
process.stdin.write cannot handle large arrays

### ISSUE THREAD

**Issue by martin-braun** [denoland/deno#11377]
Passing large amounts of data to stdin will fail. If you run this script under unix, you will get only a portion of the output of the website in the terminal: 

```js
const cat = Deno.run({
    cmd: ["cat"],
    stdin: "piped"
});
await cat.stdin.write(new Uint8Array(
	await (
			await fetch("https://languagelog.ldc.upenn.edu/nll/?feed=atom")
	).arrayBuffer()
));
cat.stdin.close();
await cat.status();
```

The sample feed ends with `</feed>`, but the pipe will swallow in the middle: 

![Screen Shot 2021-07-13 at 00 22 38](https://user-images.githubusercontent.com/24259245/125363175-72fda580-e370-11eb-9c71-59aac96451bc.png)

**Comment by ry** [comment]
stdin.write is just one syscall, it returns the number of bytes written. If you use [writeAll](https://deno.land/std@0.100.0/io/util.ts#L136-L161), I think it would work.

That said, ideally you'd stream large data, rather than buffer it up.
```js
import { readerFromStreamReader } from "https://deno.land/std@0.100.0/io/streams.ts";

const cat = Deno.run({
  cmd: ["cat"],
  stdin: "piped",
});
const res = await fetch("https://languagelog.ldc.upenn.edu/nll/?feed=atom");
let r = readerFromStreamReader(res.body.getReader());
await Deno.copy(r, cat.stdin);
cat.stdin.close();
await cat.status();
```

**Comment by martin-braun** [comment]
@ry Thank you a lot Ryan. In fact my first post was a presentation of my core issue, but I'm just dealing with a local file that happens to have a few MB, so streaming is not necessary. However, your example is very useful. Thanks for sharing, I will keep that in mind when I'm dealing with even potential larger files.
