### ISSUE TITLE
error: Uncaught InvalidData: No keys found in key file

### ISSUE THREAD

**Issue by JerryGreen** [denoland/deno#11376]
I have troubles with `serveTLS` function from std.

I used this code from this [answer from stackoverflow](https://stackoverflow.com/a/58784172/3720305) (`mod.ts`):

```ts
import { serveTLS } from "https://deno.land/std@0.100.0/http/server.ts";

const body = new TextEncoder().encode("Hello HTTPS");
const options = {
  hostname: "localhost",
  port: 443,
  certFile: "./crt/crt.pem",
  keyFile: "./crt/key.pem",
};
// Top-level await supported
for await (const req of serveTLS(options)) {
  req.respond({ body });
}
```

And I used this command to create a self-signed cert:

```
openssl req -x509 -newkey rsa:4096 -sha256 -keyout ./crt/key.pem -out ./crt/crt.pem -days 397
```

Which created me those files:

![image](https://user-images.githubusercontent.com/13215662/125357199-bb24c400-e380-11eb-9e0e-cf34c8741056.png)

But as mentioned in title, I'm getting this error when trying to `deno run`:

```ts
$ deno run --allow-net --allow-read=crt mod.ts 
error: Uncaught InvalidData: No keys found in key file
  const listener = Deno.listenTls(tlsOptions);
                        ^
    at deno:core/core.js:86:46
    at unwrapOpResult (deno:core/core.js:106:13)
    at Object.opSync (deno:core/core.js:120:12)
    at opListenTls (deno:runtime/js/40_tls.js:19:17)
    at Object.listenTls (deno:runtime/js/40_tls.js:56:17)
    at serveTLS (https://deno.land/std@0.100.0/http/server.ts:355:25)
```

I checked myself: the key file, indeed, starts with `-----BEGIN ENCRYPTED PRIVATE KEY-----`, ends with `-----END ENCRYPTED PRIVATE KEY-----`, with the key in-between. What might be the reason why Deno cannot find the key in this file?

**Comment by hermy991** [comment]
I think you need `--unstable`, let me check

**Comment by JerryGreen** [comment]
I tried the `--unstable` just now, but this doesn't seem to change a thing here.

**Comment by justinmchase** [comment]
Based on that message, the error is coming from here:
https://github.com/denoland/deno/blob/main/extensions/net/ops_tls.rs#L899

Which means that first its calling `rsa_private_keys` in the `rustls` library:
https://github.com/denoland/deno/blob/main/extensions/net/ops_tls.rs#L878

and then `pkcs8_private_keys`:
https://github.com/denoland/deno/blob/main/extensions/net/ops_tls.rs#L886

And both are not producing any errors but they are both returning an empty set of private keys, which seems to indicate either your file does not contain a private key or it is not in a format supported by rustls. 

One thing you could try doing is to clone the `rustls` project locally and it has a convenient tool for testing certs:

https://github.com/ctz/rustls#example-code

**Comment by JerryGreen** [comment]
@justinmchase I explicitly mentioned that I used `openssl`, with all the arguments how it is generated. `openssl` is a popular&reliable cli tool to generate such certificates, for debugging and non-production use (for production use there is letsencrypt). Maybe `deno` isn't compatible with it, but whatever the case: the key is present, and it is valid.

I had a look at `rustls`, but it's hard to tell how it's supposed to work, - it says there already should be a server running, which is little weird to me, so I can't test this file with `rustls`.

**Comment by justinmchase** [comment]
You can see a little further down it has a server also:
https://github.com/ctz/rustls#server-example-program

So what i did just the other day is clone that repo, make sure you have cargo installed then just run `cargo build` in the root.

After that you can just run those binaries tlsclient and tlsserver, use the flags to load your cert into the server and the client and if they can communicate then its a bug in Deno.

If they can't then rustls may have additional debug information available to you, also in deno you can try adding `-Ldebug` and it will spit out a lot more info as well. 

I also cannot see anything wrong with how you're generating the cert, it looks fine to me but its possible that this library is just not supporting rsa 4096? Though that seems unlikely...

I'm just saying looking at your ticket it seems like you're right, there is an issue but its really hard to say without a little more info what the issue actually is or where.

**Comment by JerryGreen** [comment]
@justinmchase I have noticed in code comments that, indeed, it expects slightly different format, one of those:

https://github.com/denoland/deno/blob/main/extensions/net/ops_tls.rs#L874
https://github.com/denoland/deno/blob/main/extensions/net/ops_tls.rs#L882

I added the "no des" option (`-nodes`), to skip PEM pass phrase setup:

```
openssl req -nodes -x509 -newkey rsa:4096 -sha256 -keyout ./crt/key.pem -out ./crt/crt.pem -days 397
```

So they key starts now with:

```
-----BEGIN PRIVATE KEY-----
```

Instead of:

```
-----BEGIN ENCRYPTED PRIVATE KEY-----
```

And that, suddenly, worked! Thx @justinmayhew

**Comment by JerryGreen** [comment]
@justinmchase I have noticed in code comments that, indeed, it expects slightly different format, one of those:

https://github.com/denoland/deno/blob/main/extensions/net/ops_tls.rs#L874
https://github.com/denoland/deno/blob/main/extensions/net/ops_tls.rs#L882

I added the "no des" option (`-nodes`), to skip PEM pass phrase setup:

```
openssl req -nodes -x509 -newkey rsa:4096 -sha256 -keyout ./crt/key.pem -out ./crt/crt.pem -days 397
```

So they key starts now with:

```
-----BEGIN PRIVATE KEY-----
```

Instead of:

```
-----BEGIN ENCRYPTED PRIVATE KEY-----
```

And that, suddenly, worked! Thx @justinmchase 👍

**Comment by justinmchase** [comment]
Nice! I suppose it could probably have support for a passphrase field also to support both kinds of keys.
