### ISSUE TITLE
Proposal(cli): Set Timeout per test using --timeout flag default 500ms

### ISSUE THREAD

**Issue by getspooky** [denoland/deno#11385]
### Syntax:  `--timeout=<number>`
Default timeout of a test in milliseconds. Default value: `500ms`.

### Example

```sh
deno test --timeout=600 store_data_test.ts
```

### Use Cases

Let's say we want to store some data into some database provider. So in some case it could take a lot time, probably due to some network issue. So it would be helpful if we can exit the test after `X` time.
### Motivation

- Applications aren’t responding with lightning speed on user actions and while creating the `E2E` tests this fact should be considered. 
- Using these set timeout will allow you to create more stable tests and control your test flow even more precisely

**Comment by wperron** [comment]
As discussed on Discord, this is better done through an option in the `TestDefinition` interface as tracked in #11133
