### ISSUE TITLE
After upgrading to 1.12.0, now `deno upgrade` always re-downloads the same version 

### ISSUE THREAD

**Issue by darkred** [denoland/deno#11389]
Using Deno with Windows Terminal 1.8.1521.0 on Windows 10 x64 21H1.

```
> deno --version

deno 1.12.0+1ad6575 (canary, x86_64-pc-windows-msvc)
v8 9.2.230.14
typescript 4.3.2
```

Today I upgraded Deno to 1.12.0 via `deno upgrade` in Terminal.
Now, if I re-run `deno upgrade` it always re-downloads the same version. This it the output:

```
> deno upgrade

Looking up latest version
Found latest version 1.12.0
Checking https://github.com/denoland/deno/releases/download/v1.12.0/deno-x86_64-pc-windows-msvc.zip
24.4 MiB / 24.4 MiB (100.0%)
Deno is upgrading to version 1.12.0
Upgraded successfully
```

This never occurred in previous versions so I thought to report it.

**Comment by jsejcksn** [comment]
I can reproduce this.

I'm also seeing this bug now in Windows: https://github.com/denoland/deno/issues/11179 (but it's not a regression in Linux)

**Comment by justjavac** [comment]
`dl.deno.land` is canary:

`$ wget https://dl.deno.land/release/v1.12.0/deno-x86_64-apple-darwin.zip`

```
deno 1.12.0+1ad6575 (canary, x86_64-apple-darwin)
v8 9.2.230.14
typescript 4.3.2
```

**Comment by kitsonk** [comment]
We are aware of the issue and the root cause.  As the tags indicate, it only impacts windows. It had to deal with a failed CI pipeline build for the release.

**Comment by darkred** [comment]
The issue no longer occurs after upgrading to 1.12.1, and it's back to `release` instead of `canary` :

```
> deno --version

deno 1.12.1 (release, x86_64-pc-windows-msvc)
v8 9.2.230.14
typescript 4.3.5
```
