### ISSUE TITLE
Emit 1:1 ES module library for <script type="module"> usage

### ISSUE THREAD

**Issue by Ciantic** [denoland/deno#11386]
I'd like to be able to emit 1:1 ES module library. If you are making a library, it is not a good thing that Deno gives you only ability to bundle to a single file. The `Deno.emit` is not working for this purpose as of yet at least.

In general it would be cool if deno could provide a way to emit straightforward ES module library:

`matrix.ts` -> `matrix.js`
`vector.ts` -> `vector.js`
...

This way the browser usage would be similar as with `.ts` files. You just import from .js files in your `<script type="module">` tags. As an ES module library creator I can't assume everybody uses deno, and I want the ES library imports to be from individual files instead of a bundle for efficiency.

Things that need to change from `Deno.emit` for it to work:

- It leaves import from `.ts` statements behind, see https://github.com/denoland/deno/issues/4538 
- It uses weird `file.ts.js` extension, it should be just `.js`

**Comment by kitsonk** [comment]
The command line option is and will always be intended for reconsumption by Deno. `Deno.emit()` would be the way to do this and as mentioned #4538 would need to be addressed to avoid further post processing.
