### ISSUE TITLE
Implement Deno for WinGet package manager

### ISSUE THREAD

**Issue by AngelNext** [denoland/deno#11390]
I am trying to implement Deno in WinGet package manager. I converted the ps1 file into an exe file and i have tested the installer, but I have a 2 big problems.

- I dont have a website to host the installer.
- Since I cannot create a manifest (for the reason i just said) i cannot test the behaviour of the installer.

I sugest that you hosted the exe installer in your website once you have tried it and you see if it works!!

**Comment by MarkTiedemann** [comment]
Duplicate of #5640.

**Comment by AngelNext** [comment]
Ok I just uploaded deno installer to WinGet and it works fine!
