### ISSUE TITLE
Rename `Deno.WebSocketUpgrade::websocket` to `socket`

### ISSUE THREAD

**Issue by nayeemrmn** [denoland/deno#11400]
This violates camel case. The other interface names we have preclude this from being an intentional adoption of "websocket" being commonly used as one word. Rather than `webSocket`, it would be nicer to use `socket` as the local variables do in https://html.spec.whatwg.org/multipage/web-sockets.html code examples.
![image](https://user-images.githubusercontent.com/29990554/125637022-1d84ef13-ae1b-4225-b2c0-6e735c9008a9.png)
![image](https://user-images.githubusercontent.com/29990554/125636911-651066a2-59c7-4697-96d5-c68ae814f9cb.png)

**Comment by lucacasonato** [comment]
SGTM. Let's ship it for 1.13
