### ISSUE TITLE
Panic when listening to unix socket abstract address

### ISSUE THREAD

**Issue by yuri91** [denoland/deno#11412]
if you try this simple example:

```
let listener = Deno.listen({path: "\0aaa", transport: "unix"});
```

deno crashes:
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', runtime/ops/net.rs:527:34
```

The issue I believe is that the address "\0aaa", while being a valid unix socket address (it is an abstract address, not bound to the filesystem), is not a valid Rust path name, so the unwrap fails:

https://github.com/denoland/deno/blob/79ac050d2917ddc1be97e458c8ac7c6a3d728269/extensions/net/ops.rs#L526

This use case used to work until v1.5.4 at least, but is broken in recent versions

**Comment by bitoku** [comment]
Can I address this problem?

**Comment by lucacasonato** [comment]
@bitoku Sure! If you need help, please ask on Discord: https://discord.gg/deno
