### ISSUE TITLE
Plugin for the IntelliJ Platform

### ISSUE THREAD

**Issue by martin-braun** [denoland/deno#11418]
It's very nice that we already have an [official extension for VSCode](https://github.com/denoland/vscode_deno). To my surprise there is not even a third-party plugin for Deno on the IntelliJ Platform (Android Studio, AppCode, PhpStorm, WebStorm, etc.).

It would be nice to have one, this has probably lower priority, though.

**Comment by martin-braun** [comment]
Nevermind, [it exists](https://plugins.jetbrains.com/plugin/14382-deno), I couldn't find it in the internal IDE search explorer for plugins, but that's a different topic.

**Comment by kitsonk** [comment]
Correct, and it is our understanding that JetBrains is looking at integrating to the language server.  And for the record, the [JetBrains plugin is already documented in the manual](https://deno.land/manual@v1.12.0/getting_started/setup_your_environment#jetbrains-ides) though I plan to overhaul the whole "setting up your environment" part of the manual in the near future.

**Comment by martin-braun** [comment]
@kitsonk No worries and sorry, I was typing faster than searching. And yes, I can see how it just won't complain about unknown symbols, but the language server is not working right now, but I know they won't take forever to get this done.
