### ISSUE TITLE
'Listening on' log for running script is wrong for windows

### ISSUE THREAD

**Issue by ebebbington** [denoland/deno#11424]
Running a script using deployctl on windows displays: `Listening on http://0.0.0.0:8080`, but 0.0.0.0 is now a windows thing

Suggsts using 127.0.0.1 which works with all environments

**Comment by nhrones** [comment]
What I've found  ...
deno-main /extensions/net/01_net.js (function listen) on line 206
```js
// on line# 206 if undefined, hostname defaults to "0.0.0.0"
 hostname: typeof hostname === "undefined" ? "0.0.0.0" : hostname
```
Also
deno-main /extensions/net/resolve_addr.rs (fn make_addr_port_pair())
```js
  // on line 30
  if hostname.is_empty() {
    return ("0.0.0.0", port);
  }
```

**Comment by nhrones** [comment]
@wperron  Also found vec of hosts if <BarePort>
in deno-main/cli/flags_allow_net.rs (pub fn parse())
```js
    } else if let Ok(port) = host_and_port.parse::<BarePort>() {
      // we got bare port, let's add default hosts
      for host in ["0.0.0.0", "127.0.0.1", "localhost"].iter() {
        out.push(format!("{}:{}", host, port.0));
      }
```

**Comment by nhrones** [comment]
Why can't I get to this issue from  https://github.com/denoland/deno/
When I open the issues drop-down, it is never there.
