### ISSUE TITLE
Deno.serveHttp hangs after future request with different hosts

### ISSUE THREAD

**Issue by sant123** [denoland/deno#11428]
Having this file:

``` typescript
// server.ts
console.log('Starting HTTP server at http://127.0.0.1:8693');

for await (const conn of Deno.listen({ port: 8693 })) {
  for await (const r of Deno.serveHttp(conn)) {
    console.log(`Method received ${r.request.method}`);
    r.respondWith(new Response(`Method received ${r.request.method}`));
  }
}
```

Start it with `deno run --unstable -A server.ts`

Do a request with a browser (e.g: Chrome) to http://127.0.0.1:8693. It will work fine :)
Do a request with the same browser to http://localhost:8693. Will hang :/

Now stop the server and run it again.

Do a request with a browser (e.g: Chrome) to http://localhost:8693. It will work fine :)
Do a request with the same browser to http://127.0.0.1:8693. Will hang :/

The same happens if one URL is open in two browsers. e.g: Chrome and Firefox. Only the first browser will load the URL, the second will hang.

Edit:

This is being tested with Deno v1.12.0 in a Fedora 33 machine

**Comment by crowlKats** [comment]
You have to do
```js
for await (const conn of Deno.listen({ port: 8693 })) {
  (async () => {
    for await (const r of Deno.serveHttp(conn)) {
      console.log(`Method received ${r.request.method}`);
      r.respondWith(new Response(`Method received ${r.request.method}`));
    }
  })();
}
```
From the [docs](https://deno.land/manual@v1.11.3/runtime/http_server_apis#serving-http):
> Note that in both cases we are using an IIFE to create an inner function to deal with each connection. If we awaited the HTTP requests in the same function scope as the one we were receiving the connections, we would be blocking accepting additional connections, which would make it seem that our server was "frozen".

**Comment by sant123** [comment]
My bad, little detail 😅 thank you so much !!!
