### ISSUE TITLE
multiple nested optional parameters cause issues

### ISSUE THREAD

**Issue by arnimlost** [denoland/deno#11429]
If there are multiple optional parameters, such as
```ts
type Interaction = {
    data?: {
        options?: Option[]
    }
}

type Option = {
    options?: Option[]
}
```
and you try to get `interaction.data?.options?[0].options`, deno-fmt and the deno runtime recognize the second `?` as a `condition ? true : false` syntax and exspect a `:`.

deno-fmt:
![image](https://user-images.githubusercontent.com/74423013/126045188-0be411b3-3fe8-4466-8701-c22017ad4738.png)

deno run:
`error: Expected :, got const` (const is the start of the next line)

**Comment by crowlKats** [comment]
Your syntax is wrong, see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining#optional_chaining_with_expressions
it should be `?.[0]`.
