### ISSUE TITLE
Simultaneous requests to a `Deno.listen` listener cause request errors

### ISSUE THREAD

**Issue by l2ig** [denoland/deno#11431]
Hi! I'm not sure if I'm doing something completely wrong or if there's a bug in Deno, but if I start a listener and send simultaneous requests to it, they sometimes fail, and I can't figure out why.

Listener code:
```typescript
const listener = Deno.listen({ port: 3000 });

while (true) {
    const conn: Deno.Conn = await listener.accept();
    await conn.write(
        new TextEncoder().encode("HTTP/1.1 200 OK\r\nContent-Length: 1\r\n\r\n1")
    );
    conn.close();
}

// ... or

while (true) {
    const conn: Deno.Conn = await listener.accept();
    conn.write(
        new TextEncoder().encode("HTTP/1.1 200 OK\r\nContent-Length: 1\r\n\r\n1")
    ).then(() => conn.close());
}
```

Test case:
```typescript
let succeeded = 0;
const maxSimultaneousRequests = 25;
for (let i = 0; i < maxSimultaneousRequests; i++) {
    fetch("http://localhost:3000").then(() => succeeded++).catch(console.error)
}
```

After running, one (or both) of the following errors occurs:
* `TypeError: error sending request for url (http://localhost:3000/): operation was canceled: received unexpected message from connection`
* `TypeError: error sending request for url (http://localhost:3000/): channel closed`

Version: `deno nightly 2021.07.17` and `deno 1.12.0`

**Comment by bartlomieju** [comment]
Using `conn.write` doesn't guarantee that all bytes will be written in a single call (that function returns number of bytes written). Try using [`writeAll(conn, ...)`](https://deno.land/std@0.101.0/io/util.ts#L156) instead.

**Comment by l2ig** [comment]
The same error still occurs to me, but shouldn't `write` also throw an error if it didn't wrote the full data?
```
// lib.deno.d.ts
`write()` must reject with a non-null error if would resolve to `n` < `p.byteLength`
// ...
write(p: Uint8Array): Promise<number>;
```

**Comment by l2ig** [comment]
Oh, I see. This happens when you don't read the connection.
