### ISSUE TITLE
Deno panics when sent a non websocket request to debugger url

### ISSUE THREAD

**Issue by FalseDev** [denoland/deno#11449]
Reproducing:
- Run `deno repl --inspect` 
- Open browser (or send any non websocket request) to printed url

Message:
```rs
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: hyper::Error(User(NoUpgrade))', runtime/inspector.rs:192:54
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Additional info:
Deno version: `1.10.1`

**Comment by bartlomieju** [comment]
We had a major rework of inspector infrastructure since `1.10`. Does this issue persist in newer versions?

**Comment by lucacasonato** [comment]
Still happens.

![image](https://user-images.githubusercontent.com/7829205/126178451-311bc01d-4ff0-4491-9e0e-e015ede0fc95.png)

**Comment by caspervonb** [comment]
We never intended for repl to work with --inspect as far as I can recall.
I guess we can support it but what's the use case for this?

**Comment by bartlomieju** [comment]
> We never intended for repl to work with --inspect as far as I can recall (was an either or situation with the channels then).
> I guess we can support it but what's the use case for this?

Not sure if it's any useful, but we certainly shouldn't panic. Working on a fix now.
