### ISSUE TITLE
lsp: rename file adjusting only capitalisation results in "Already included" error

### ISSUE THREAD

**Issue by sramam** [denoland/deno#11457]
When a file is renamed, but the rename is only in capitalization, for example `tasks.ts` -> `Tasks.ts`, the vs-code plugin complains.
```
Already included file name 'file:///C:/Users/deno/Tasks.ts' differs from file name 'file:///C:/Users/deno/tasks.ts' only in casing.
  The file is in the program because:
    Imported via "./Tasks.ts" from file 'file:///C:/Users/deno/api.ts'    Root file specified for compilationdeno-ts(1261)
```

**Comment by kitsonk** [comment]
I don't think we are handling renames properly.  This is related to #10897.

**Comment by kitsonk** [comment]
I looked into this. The error is correct. When working on a case-insensitive file-system, the language server client should provide the original casing of the file.  If the casing is subsequently re-named with a different case, the client does not update the casing. When that situation occurs, the TypeScript compiler does indicate that this is currently ambiguous.  A way to clear the error is to restart the editor.
