### ISSUE TITLE
lsp: types can get "lost" with import maps

### ISSUE THREAD

**Issue by erfanium** [denoland/deno#11456]
It's kinda strange. When I open vscode, some variable types recognized as  `unknown` which is incorrect. look at this screenshot:

![Screenshot from 2021-07-10 21-20-47](https://user-images.githubusercontent.com/47688578/125171166-fb8d1200-e1c7-11eb-8bac-8c9b8a778824.png)

After I go to `userIdKey` definition (via F12) and do a change (for example add a space). It will fix the problem (not always):

![Screenshot from 2021-07-10 21-40-56](https://user-images.githubusercontent.com/47688578/125171244-5e7ea900-e1c8-11eb-9e64-263a6abd5bee.png)

~~Unfortunately I couldn't make a reproduce repo for this.~~
reproduction: https://github.com/erfanium/deno-lsp-bug-repro

vscode: 1.58.0  
deno: 1.11.5  
extension: 3.7.0

**Comment by kitsonk** [comment]
A more concise reproduction: https://github.com/erfanium/deno-lsp-bug-repro/tree/master
