### ISSUE TITLE
Deno test --watch does not rerun tests related to changed file

### ISSUE THREAD

**Issue by getspooky** [denoland/deno#11450]
For example : 
```ts
Deno.test({
  name: "test example",
  fn(): void {
    assertEquals(1, 1);
  },
});
```
when i run `deno test --unstable --watch ./test/sample_test.ts, it exit immediately.

Result: 
```sh
test test example ... ok (8ms)
test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out 
```
The expected behavior is to start watch process

**Comment by caspervonb** [comment]
Duplicate https://github.com/denoland/deno/issues/11432
