### ISSUE TITLE
Deno `1.12.1` compile with `--target=aarch64-apple-darwin` fails to download needed binary

### ISSUE THREAD

**Issue by grempe** [denoland/deno#11485]
The downloadable artifact for the Darwin ARM builds of deno `1.12.1` is missing (all other arch targets are found). The file is present though for version `1.12.0`.

This prevents me from building with the latest release.

It seems there was an issue generating the artifacts for this architecture.

FAILS `1.12.1`

```sh
❯ wget https://dl.deno.land/release/v1.12.1/deno-aarch64-apple-darwin.zip
--2021-07-21 18:28:06--  https://dl.deno.land/release/v1.12.1/deno-aarch64-apple-darwin.zip
Resolving dl.deno.land (dl.deno.land)... 104.23.131.81, 104.23.132.81, 2606:4700:11::6817:8351, ...
Connecting to dl.deno.land (dl.deno.land)|104.23.131.81|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-07-21 18:28:06 ERROR 404: Not Found.
```

OK `1.12.0`

```sh
❯ wget https://dl.deno.land/release/v1.12.0/deno-aarch64-apple-darwin.zip
--2021-07-21 18:28:11--  https://dl.deno.land/release/v1.12.0/deno-aarch64-apple-darwin.zip
Resolving dl.deno.land (dl.deno.land)... 104.23.131.81, 104.23.132.81, 2606:4700:11::6817:8351, ...
Connecting to dl.deno.land (dl.deno.land)|104.23.131.81|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 28683065 (27M) [application/zip]
Saving to: ‘deno-aarch64-apple-darwin.zip’

deno-aarch64-apple-darwin.zip 100%[=================================================>]  27.35M  37.9MB/s    in 0.7s

2021-07-21 18:28:12 (37.9 MB/s) - ‘deno-aarch64-apple-darwin.zip’ saved [28683065/28683065]
```

**Comment by lucacasonato** [comment]
Should now be working again.

**Comment by grempe** [comment]
Awesome! Thanks for the quick fix @lucacasonato. 

Quick question? Was something done as part of this fix to help prevent this situation in the future? This seems like a weak spot with Deno, forcing a download from a CDN when running `deno compile` with other target architectures.

**Comment by bartlomieju** [comment]
> Quick question? Was something done as part of this fix to help prevent this situation in the future? 

Unfortunately there are no Apple M1 runners available in GitHub actions, so we need to upload those binaries manually for each release. Looks like we forgot to do that after cutting `1.12.1`.

> This seems like a weak spot with Deno, forcing a download from a CDN when running deno compile with other target architectures.

I'm not sure how we could remedy this problem?
