### ISSUE TITLE
Deno's `fetch()` does not set `Connection: keep-alive` while browsers do

### ISSUE THREAD

**Issue by NfNitLoop** [denoland/deno#11495]
I ran into an issue that was difficult to debug (see: [my comments in the Discord][1]) because of this difference between Deno and Chrome & Firefox.

I've got [a server][2] which responds to an HTTP PUT with a 202 if the file already exists. And I had a preexisting [client that works][3] in Chrome and Firefox.

So I was surprised when I tried to port this to Deno, and Deno appeared to start throwing an exception that I never saw from browsers.

After lots of debugging, I think it comes down to the fact that Deno does not set "Connection: keep-alive", which may cause (allow?) servers to close the HTTP connection before all bytes have been sent.

Steps to Reproduce
---------------------

Start the example server:

```typescript
// file: server.ts

import { serve } from "https://deno.land/std@0.102.0/http/server.ts";

const port = 9999;
const server = serve({ port })
console.log(`HTTP webserver running.  Access it at:  http://localhost:${port}/`);


// Server responds to a PUT request with an OK status:
for await (const req of server) {
    const hConn = req.headers.get("Connection")
    const isKeepalive = hConn != null && hConn.toLowerCase().search("keep-alive") >= 0

    console.log("request:", req.method, req.url, "keepalive:", isKeepalive)

    await req.respond({
        // See: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/202
        status: 202,
        body: "File already exists."
    })

    // Unlike the browser, deno fetch() does not send keepalive, which can cause
    // servers to prematurely close the connection:
    if (!isKeepalive) {
        req.conn.close()
    }
}
```

    deno run --allow-net server.ts

Run the example Deno client:

```typescript
// file: client.ts:

// You might need to run this script once
// or twice before you start seeing failures.
// It seems to rely on how quickly the server can
// close the connection, and I guess the first run
// primes the server JIT? 🤷‍♂️

const port = 9999

// Larger bodies trigger more reliably:
const body =  new Uint8Array(1024*1024*10)

try {
    const response = await fetch(`http://127.0.0.1:${port}/`, {
        method: "PUT",
        body
    })
    console.log(response.status)
    console.log("Success.")
} catch (error) {
    console.log("ERROR:", error)
}
```

    deno run --allow-net client.ts

You should see an error like:

> TypeError: error sending request for url (http://127.0.0.1:9999/): connection error: An established connection was aborted by the software in your host machine. (os error 10053)
>    at deno:core/core.js:86:46
>    at unwrapOpResult (deno:core/core.js:106:13)
>    at async mainFetch (deno:extensions/fetch/26_fetch.js:229:14)

However, if you open a browser to that URL, and paste this code in the console:

```javascript
result = await fetch("/", { method: "PUT", body: new Uint8Array(1024*1024*10) })
```

You'll get an OK.   And in the server window, you can see the difference is that keepalive is set:

```
request: PUT / keepalive: false
request: PUT / keepalive: true
```

[1]: https://discord.com/channels/684898665143206084/689420767620104201/867920448938205324
[2]: https://github.com/NfNitLoop/feoblog/blob/1835963/src/server/attachments.rs#L80-L86
[3]: https://github.com/NfNitLoop/feoblog/blob/1835963/web-client/ts/client.ts#L99-L117

**Comment by NfNitLoop** [comment]
I thought I might be able to work around this issue by adding `keepalive: true` to `fetch()`'s `RequestInit` but that doesn't seem to get passed through.

**Comment by kitsonk** [comment]
@NfNitLoop setting that header is "banned" in a `fetch()` request, you should use the option `keepalive` like:

```js
fetch("/", {
  method: "PUT",
  body: new Uint8Array(1024*1024*10),
  keepalive: true
});
```

According to the spec it defaults to [false](https://fetch.spec.whatwg.org/#request-keepalive-flag).  So it isn't a Deno issue, as much as you don't normally retrieve items via a browsers `fetch()` API, but instead basic browsing has different defaults than `fetch()` does.

**Comment by NfNitLoop** [comment]
I [did] try updating my `client.ts` to this:

```typescript
    const response = await fetch(`http://127.0.0.1:${port}/`, {
        method: "PUT",
        body,
        keepalive: true
    })
```

But that's not getting set in the request.  

[did]: https://github.com/denoland/deno/issues/11495#issuecomment-885327444

**Comment by kitsonk** [comment]
Yes, looking at the spec, it doesn't set a header.  For example, doing the following in Chrome:

```js
await fetch("https://deno.land/x/oak/mod.ts", { keepalive: true });
```

Results in the following headers in the request:

```
accept: */*
accept-encoding: gzip, deflate, br
accept-language: en-GB,en-US;q=0.9,en;q=0.8
referer: https://deno.land/
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: same-origin
sec-gpc: 1
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36
```

No connection header.  So again Deno is "the problem" it is the behaviour of `fetch()`.

Can I ask why you feel the need to close the connection explicitly?

**Comment by NfNitLoop** [comment]
aaaah, the `keepalive` in fetch isn't `Connection: keep-alive`, it's got a different [meaning]:

> The keepalive option can be used to allow the request to outlive the page. Fetch with the keepalive flag is a replacement for the Navigator.sendBeacon() API.

[meaning]: https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/fetch

OK.  

-----

> Can I ask why you feel the need to close the connection explicitly?

server.ts is just a demonstration of behavior I observed in an actix-web HTTP server.  I'm emulating that behavior. (i.e.: If you return a response without reading the whole body, and the HTTP connection does not have a `Connection: keep-alive` header, then the TCP connection is closed before `fetch()` expects.)

More generally, why might a server close a connection early?  Maybe it's returned an HTTP 403 (Forbidden) and doesn't want to allow more TCP bytes to be sent to it. Or as in my case, the server returns a 202 because the resource/file already exists.

---

> it is the behaviour of fetch()

OK.  I mostly opened this bug because a couple folks in Discord suggested I do so.  If this is the desired behavior in Deno, it's not a bug and we can close this.

More broadly, though, this limitation of fetch make me wish Deno std had a general-purpose HTTP client that could handle these cases better than the fetch API.

**Comment by lucacasonato** [comment]
Deno will actually add the keep alive header if it deems the connection is worth reusing.

More generally though, the keepalive header being there or not should have no client facing impact on a request. If it does this is a bug (either in the server or the client). It also failing in Chrome and FF suggests to me it is a bug in the server implementation.
