### ISSUE TITLE
Deno coverage option cli inconsistency (requires `=` after option)

### ISSUE THREAD

**Issue by lowlighter** [denoland/deno#11492]
It feels weird that an `=` is required after `--coverage` option while other options supports a space separator:

```shell
deno test --coverage coverage --import-map imports.json
# error: The argument '--coverage=<coverage>' requires a value but none was supplied

deno test --coverage=coverage --import-map imports.json
```

Granted it's a nitpick, but it would be more consistant with remaining options

**Comment by getspooky** [comment]
I think --coverage option must not have a required option by default
```
deno test --coverage --import-map imports.json
```

**Comment by lucacasonato** [comment]
This is because of backwards compat. `--coverage` didn't use to take an argument, so we now require a `=` to not accidentally swallow arguments that users previously provided.
