### ISSUE TITLE
Run cargo-clippy as part of tools/lint.py

### ISSUE THREAD

**Issue by ry** [denoland/deno#1150]
https://github.com/rust-lang-nursery/rust-clippy

It has already some issues: https://github.com/denoland/deno/pull/1149

**Comment by hayd** [comment]
Note: With clippy::pedantic I can get deno down to these warnings:
https://gist.github.com/hayd/8678eff672cb077bfdea260c1a2dd635

**Comment by hayd** [comment]
issues above are on pedantic mode only, which shouldn't run in ci.

I'm not 100% sure, but I think you want to move the rustup command next to the other rustup usage. Alternatively it'd be added to third_party. My advice is to experiment...

**Comment by kt3k** [comment]
Is this not feasible? I often copy and paste the clippy command from `.github/workflows/ci.yml` and it's a little bit bother.

**Comment by bartlomieju** [comment]
Oooops, you're right @kt3k

**Comment by jsouto18** [comment]
I'll work on this, it should be quite simple.
