### ISSUE TITLE
Deno `fetch web api` causes serious memory leak until system force killed Deno

### ISSUE THREAD

**Issue by CGQAQ** [denoland/deno#11507]
```ts
const resp = await fetch("http://localhost:4545/single-large-file");
const buff = await resp.arrayBuffer();
if (buff.byteLength !== 100_000_000) {
  throw new Error("Downloaded file size is not the same from original");
}
Deno.exit(0);
```
the output is
![image](https://user-images.githubusercontent.com/15936231/126864850-f872ec7b-efe6-403b-affd-42635367a407.png)

and memory usage is 
![image](https://user-images.githubusercontent.com/15936231/126864920-55d1ef0f-ac94-4bab-b688-bab8e8aa320c.png)

```ts
await Promise.all((() => {
  const reqs = [];
  for (let i = 0; i < 100; ++i) {
    reqs.push(fetch("http://localhost:4545/single-small-file"));
  }
  return reqs.map(async (req) => {
    const resp = await req;
    const buff = await resp.arrayBuffer();
    if (buff.byteLength === 1_000_000) {
      return;
    } else {
      throw new Error("Downloaded file size is not the same from original");
    }
  });
})());
Deno.exit(0);
```
the output is
![image](https://user-images.githubusercontent.com/15936231/126864983-5a3bb980-2df1-4a6c-a5b4-3ac0c7697141.png)
and memory usage is 
![image](https://user-images.githubusercontent.com/15936231/126864966-87c81126-9787-43d9-9b66-eed6a0a096c1.png)

file sizes:
![image](https://user-images.githubusercontent.com/15936231/126865020-b0595863-fe58-43b0-8294-f863c054e47f.png)

I found this bug when I try to write tests about #8787

Full code on the pr #11508

**Comment by MarkTiedemann** [comment]
Doesn't seem to leak on my machine.

Minimal repro:

```js
let file_size = 100_000_000;
let port = 8000;

(async function () {
	for await (let conn of Deno.listen({ port })) {
		for await (let event of Deno.serveHttp(conn)) {
			let max_rand = 65_536;
			let fill_iterations = Math.floor(file_size / max_rand);
			let fill_rest = file_size % max_rand;

			let buf = new Uint8Array(file_size);
			let chunk = new Uint8Array(max_rand);
			let rest = new Uint8Array(fill_rest);

			for (let i = 0; i < fill_iterations; i++) {
				crypto.getRandomValues(chunk);
				buf.set(chunk, i * max_rand);
			}

			crypto.getRandomValues(rest);
			buf.set(rest, file_size - fill_rest);

			return event.respondWith(new Response(buf));
		}
	}
}());

let res = await fetch(`http://localhost:${port}`);
let buf = await res.arrayBuffer();
console.assert(buf.byteLength === file_size);
```

```batch
C:\>deno -V
deno 1.12.2

C:\>ver
Microsoft Windows [Version 10.0.19043.1110]
```

**Comment by MarkTiedemann** [comment]
I did notice, though, that when running this code with a `file_size` of `3_000_000_000` (3GB), the program uses roughly 12GB of memory.

**Comment by lucacasonato** [comment]
I can not reproduce any leaks or excessive usage in the provided example from OP.

V8 can sometimes keep process memory inflated (over overallocate) when a program is already using a lot of memory. This is however not a leak.
