### ISSUE TITLE
Suspected regression in REPL - repeatedly initialising the same constant should fail with a message.

### ISSUE THREAD

**Issue by lukebrowell** [denoland/deno#11501]
![image](https://user-images.githubusercontent.com/1446740/126784818-ff6e7613-1466-41b8-98aa-3aa02da343f1.png)

Have tested on 1.11 and found to be working - so somewhere between there and latest version a regression has occurred. 

![image](https://user-images.githubusercontent.com/1446740/126785437-17994827-d854-4b87-998f-26d25ff1f052.png)

Suspected, but unconfirmed as a result of stripping typescript annotations in the REPL which was implemented around about the same time. 

Not an issue in Chromium: 91.0.4472.124 
![image](https://user-images.githubusercontent.com/1446740/126785966-774bdfa9-3cbc-49ad-a310-af25960ca58a.png)

**Comment by ayame113** [comment]
Isn't this a new feature introduced in V8 9.2?
https://chromium.googlesource.com/v8/v8.git/+/0acdf36510e72d5dac5777d893e77716235b7c39

It seems that it will be introduced to Chrome 92 as well.
https://developer.chrome.com/blog/new-in-devtools-92/#const-redeclaration

**Comment by lukebrowell** [comment]
> Isn't this a new feature introduced in V8 9.2?
> https://chromium.googlesource.com/v8/v8.git/+/0acdf36510e72d5dac5777d893e77716235b7c39
> 
> It seems that it will be introduced to Chrome 92 as well.
> https://developer.chrome.com/blog/new-in-devtools-92/#const-redeclaration

Don't know - not running Chrome 92 - can you confirm it as an upstream issue ?

**Comment by lucacasonato** [comment]
I can confirm this is a V8 9.2 feature. It is only available in the REPL and is intentional.

For discussions on the feature I would defer to the V8 mailing list.

**Comment by dsherret** [comment]
This is a great change! Just reviewed the code and there isn't any comments we need to update or anything.

**Comment by lukebrowell** [comment]
General consensus is that it's a useful feature for power-users - I can't argue with this (it used to frustrate me until I got used to it).

I've fed back to the Node community that as a courtesy to it would be preferable to provide informational messages to the effect that an immutable type has been overwritten in the context of the REPL, rather than syntax of JS being silently swallowed by the REPL.
