### ISSUE TITLE
Http: connection error: An existing connection was  forcibly closed by the remote host. (os error 10054)... bug??

### ISSUE THREAD

**Issue by ruifortes** [denoland/deno#11514]
This is a little beyond not only debugging capabilities but probably my coding of getting started examples as well
Nevertheless...should this code work?
By the way... it works if I omit the header and downloaded file plays fine but I would like to be able to play it in the browser.

```
import {readableStreamFromReader} from "https://deno.land/std/io/mod.ts"

let filePath = "...path_to/some_video.mp4"

const listener = Deno.listen({port: 8080})
for await (const conn of listener) {
  const httpConn = Deno.serveHttp(conn)
  for await (const { request, respondWith } of httpConn) {

		let size = (await Deno.stat(filePath)).size
		let reader = await Deno.open(filePath)
		let stream = readableStreamFromReader(reader)
		let headers = new Headers({
			'content-type': 'video/mp4',
			'content-length': `${size}` 
		})

		let res = new Response(stream, {status: 200, headers})
		await respondWith(res)
  }
}
```

Error message:

```
error: Uncaught (in promise) Http: error writing a body to connection: An existing connection was forcibly closed by the remote host. (os error 10054)
  for await (const { request, respondWith } of httpConn) {
                                         ^
    at deno:core/01_core.js:106:46
    at unwrapOpResult (deno:core/01_core.js:126:13)
    at async HttpConn.nextRequest (deno:extensions/http/01_http.js:53:23)       
    at async Object.next (deno:extensions/http/01_http.js:117:26)
    at async file:///F:/DEV/11_VIDEO/hls-player/server/src/index.ts:8:42   

```

**Comment by NfNitLoop** [comment]
What may be happening is that when you provide the video header, your browser tries to download different chunks of the files with HTTP partial downloads.  So it might be aborting the connection to make a new one to a different portion of the file.  (Some video files have indexes to help with seeking. Though I don't know if that's the case for .mp4.)  

Though, hmm, it looks like that shouldn't be the case unless you're returning the [Accept-Ranges][1] header.  

The next thing you could do is open your browser's console and view the network tab to check for errors there.

[1]: https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests

**Comment by ruifortes** [comment]
Nothing, just "GET http://localhost:8080/ net::ERR_CONNECTION_REFUSED" on the console.
The connetion just shows "failed to load response data" and headers are:

```
Request URL: http://localhost:8080/
Referrer Policy: strict-origin-when-cross-origin
Provisional headers are shown
Learn more
Accept-Encoding: identity;q=1, *;q=0
Range: bytes=0-
Referer: http://localhost:8080/
sec-ch-ua: "Chromium";v="94", "Google Chrome";v="94", ";Not A Brand";v="99"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4588.0 Safari/537.36
```

here's a pic: 

![chrome_62KSQ2YL58](https://user-images.githubusercontent.com/4864714/127128470-68a791ee-b203-4e3a-bcee-a1c82a00a080.png)

**Comment by NfNitLoop** [comment]
This is still an issue afaik.
