### ISSUE TITLE
Can't remap windows file specifiers

### ISSUE THREAD

**Issue by caspervonb** [denoland/deno#11530]
The following import-map:

```json
{
  "imports": {
    "file:": "http://localhost:8080/" 
  },
}
```
Causes windows to blow up:
```
Check file:///D:/a/sponsor/sponsor/testdata/test/ignore.ts
error: The specifier ""file:///D:/a/sponsor/sponsor/testdata/test/ignore.ts"" backtracks above its prefix ""file:///""
```

But appears to work just fine on Unix.

**Comment by dsherret** [comment]
@caspervonb could you provide the code in ignore.ts just so it's clear? I get the behaviour you describe on both windows and unix with code like `import "file:///D:/a/test.ts";`.

**Comment by caspervonb** [comment]
Nothing magical about the import, just plain relative file imports which are resolved to file specifiers.

Can trigger it like so with the above import map:
```bash
echo "console.log('foo.js')" > foo.ts
deno test --import-map=import_map.json foo.js
```

Or run with side loading a module triggering the import map:
```bash
echo "console.log('a.js')" > a.js
echo "import 'a.js'" > b.js

deno run --import-map=import_map.json b.js
```

> Actually, it is ok. I think I know what you meant (it works with file:///a/test.ts on both platforms)

Indeed, you can map with drive letters however, but that means you need to map each drive letter rather than just the protocol ala https://github.com/caspervonb/sponsor/blob/main/test.js#L449-L459
