### ISSUE TITLE
`deno run -` should take a language argument. 

### ISSUE THREAD

**Issue by AnInternetTroll** [denoland/deno#11559]
`react.tsx`: 

```tsx
import React from "https://esm.sh/react"

export default function hello(foo: string) {
	return <p> Hello {foo}</p>;
}

console.log(hello("world"))
```

`deno run react,tsx`:

```sh
Check file:///home/luca/testStuff/deno/react.tsx
{
  "$$typeof": Symbol(react.element),
  type: "p",
  key: null,
  ref: null,
  props: { children: [ " Hello ", "world" ] },
  _owner: null
}
```

`deno run - < react.tsx`:

```sh
deno run - < react.tsx
error: Expected ;, got { at file:///home/luca/testStuff/deno/$deno$stdin.ts:4:21
```

**Comment by kitsonk** [comment]
Adding a flag is an unnecessary complexity. Only recognised extensions are a viable way to do this. Respectfully declined.

**Comment by nayeemrmn** [comment]
We added `--ext` to `deno eval` with the consideration of eventually using it for this as well, I think it's reasonable. Node has `--input-type` which is used to select between `.js` and `.mjs` for `-e` input as well as stdin. But duplicate of #5088.
