### ISSUE TITLE
`deno run` should take stdin without the need of the `-` flag

### ISSUE THREAD

**Issue by AnInternetTroll** [denoland/deno#11558]
Node and Python both take stdin without the `-` flag, and python even has it in it's help message. As such I would think that `deno run` should do the same.

**Comment by kitsonk** [comment]
`deno eval` and `deno xeval` read from `stdin`

**Comment by caspervonb** [comment]
> `deno eval` and `deno xeval` read from `stdin`

Deno eval executes in a script context, which is a very different.
Why did you immediately close this?

**Comment by nayeemrmn** [comment]
Despite the prior art, I think that changing behaviour based on whether stdin is piped content or a tty (which is what those programs do to determine if a script has been passed to stdin) is unsound and not how I want tools to behave when automating something. We'd end up doing that if we still want `deno run` to throw an arg parsing error when stdin isn't piped. A `-` to substitute the script name isn't problematic.
