### ISSUE TITLE
[Feature request]: ability to wipe worker memory

### ISSUE THREAD

**Issue by treethought** [denoland/deno#11584]
I have a use case where I am trying to offload computation across a large queue of workers. 

These workers should be a clean slate when they receive a message, and the queue should be re-filled as each message is consumed by worker.

Currently I am simply terminating and then creating a new worker, but for performance reasons I would like to simply clear a workers memory instead of recreating.

Is there any plan to support something like `worker.reset()` in addition `worker.terminate()`? For example, to prevent a worker global `count` variable from persisting across messages?

**Comment by bartlomieju** [comment]
Is there an existing Web standard for this functionality? Why not just reinitialize variables to empty values after responding to allow existing object to be garbage collected?

**Comment by kitsonk** [comment]
I don't think there is any desire to introduce anything that would make Deno workers incompatible with [Web Workers](https://developer.mozilla.org/en-US/docs/Web/API/Worker).

A `SharedArrayBuffer` which gets reset might be a better solution, or implementing a message handler that internally wipes the memory.

**Comment by treethought** [comment]
I see, that makes sense. 

Thank you for the suggestions, and the quick response. a `SharedArrayBuffer` might be what I need.
