### ISSUE TITLE
`Deno.readTextFile` doesn't work properly in subdirectories

### ISSUE THREAD

**Issue by kecrily** [denoland/deno#11587]
Here is my code

```typescript
const content = await Deno.readTextFile("test.txt") 
console.log(content)
```

When I execute the command in the root directory everything works fine

```
deno run --allow-read test.ts
```

But when I move `test.ts` and `test.txt` into subdirectory, errors occur.

```
error: Uncaught (in promise) NotFound: The system cannot find the specified file. (os error 2)
const content = await Deno.readTextFile("test.txt")
                ^
    at deno:core/01_core.js:106:46
    at unwrapOpResult (deno:core/01_core.js:126:13)
    at async open (deno:runtime/js/40_files.js:51:17)
    at async Object.readTextFile (deno:runtime/js/40_read_file.js:40:18)
    at async file:///C:/Users/kecrily/Desktop/detoml/test/content.ts:1:17
```

When I executed `cd` to enter the subdirectory, it worked again.

Finally, my deno version information, `deno upgrade` told me that this is the latest version

```
deno 1.12.2 (release, x86_64-pc-windows-msvc)
v8 9.2.230.14
typescript 4.3.5
```

**Comment by caspervonb** [comment]
Relative file paths are relative to the working directory, not where the module is (you can resolve that relative to `import.meta.url`).
