### ISSUE TITLE
transport endpoint not connected, must restart

### ISSUE THREAD

**Issue by btrauma8** [denoland/deno#11599]
about once a week my deno server has to restart itself. i've tried re-listening, without restarting...but then it tells me the address is already in use. i've got a try catch on the inside of the "do stuff", but i get nothing from it in the logs. just the outer try catch logs the error. deno version 1.11 (it just happened, i'll upgrade later today and let it run a few weeks and see)

try{
  for await (const req of serve({ port: whateverPort })) { ...do stuff }
} catch (err) {
   ...log the error below and exit/restart
}
NotConnected: Transport endpoint is not connected (os error 107)
    at deno:core/core.js:86:46
    at unwrapOpResult (deno:core/core.js:106:13)
    at async Listener.accept (deno:runtime/js/30_net.js:98:19)
    at async Server2.acceptConnAndIterateHttpRequests
    at async MuxAsyncIterator2.callIteratorNext

**Comment by bartlomieju** [comment]
What OS are you on?

Also it looks like your using HTTP server from `deno_std`, which will be soon deprecated in favor of using `Deno.serveHttp` API, so I expect this issue might "fix itself" after switching the API.

**Comment by btrauma8** [comment]
Ubuntu 18.
yes, that's serve from std@0.100's http
i didn't know about Deno.serveHttp! cool, i'll try it out.
...wish i could force the error. Just seems random.

**Comment by bartlomieju** [comment]
> Ubuntu 18.
> yes, that's serve from std@0.100's http
> i didn't know about Deno.serveHttp! cool, i'll try it out.
> ...wish i could force the error. Just seems random.

Unfortunately it's very hard to reproduce such errors that occur after many hours of server running. 

Please do try out `Deno.serveHttp` and let me know if the problem persists.

**Comment by btrauma8** [comment]
Alright, I've got the server up and running with the native http bindings, deno 1.12.2.
Now...we wait.

**Comment by btrauma8** [comment]
closing this because it hasn't happened in 16 days. that might be a record.
