### ISSUE TITLE
Deno doesn't seem to use Socks5 proxy in HTTP_PROXY and HTTPS_PROXY environment variables

### ISSUE THREAD

**Issue by DanteMarshal** [denoland/deno#11609]
I'm not sure if this is a duplicate of #6061, But here's the problem.
I'm on windows 10 using `deno 1.12.2 (release, x86_64-pc-windows-msvc)`, `v8 9.2.230.14`, `typescript 4.3.5`, and I have this file `DenoStd.ts` :
```
import * as Http from 'https://deno.land/std@0.103.0/http/mod.ts'
export { Http };
```
I'm behind a Socks5 proxy running on my localhost `127.0.0.1:1080` and I've tried setting related environment variables to these values :
1. `http://127.0.0.1:1080/`
2. `https://127.0.0.1:1080/`
3. `socks5://127.0.0.1:1080/`
But none seem to work, and I get the following error when I reach the import line :
```
error: error sending request for url (https://deno.land/std@0.103.0/http/mod.ts): error trying to connect: tls handshake eof
    at file:///Bla/Bla/Bla/DenoStd.ts:1:0
```

But if I set my proxy using Windows' proxy settings GUI (instead of environment variables) it works with no problem.

Expected behavior is that environment variables also work, so maybe there's a bug there ? Or is it the case that Socks5 proxies are not supported somehow ??

**Comment by bnoordhuis** [comment]
#6061 is a different issue. Proxy support is provided by the `reqwest` crate and we don't have the `socks` feature enabled:
https://github.com/denoland/deno/blob/02c74fb70970fcadb7d1e6dab857eeb2cea20e09/extensions/fetch/Cargo.toml#L24
I can't think of a reason not to enable it so... want to send a PR? Please include tests.

**Comment by DanteMarshal** [comment]
I need to look into reqwest as I have not used it before. But sure I'll take a look into it in my free time.

**Comment by bnoordhuis** [comment]
Adding `"socks"` to the features list should be all it takes to make socks5:// and socks5h:// work. The hard part is testing it.

**Comment by DanteMarshal** [comment]
Ok, Today I started working on this a little bit.
I'm just not sure where to put the tests for this, I assumed there must be tests for http proxy already in 'cli\tests\unit\fetch_test.ts' but couldn't find any.
At this point I don't know where the tests should go ?
Any tips ?

**Comment by bnoordhuis** [comment]
`cli/tests/testdata/045_proxy_test.ts` and `cli/tests/testdata/045_proxy_test.ts.out` are the files you're looking for if I'm not mistaken.

**Comment by Chris2011** [comment]
@DanteMarshal heya, is there still any progress for this feature from your side? Do you need help somehow?

**Comment by DanteMarshal** [comment]
@Chris2011 
> @DanteMarshal heya, is there still any progress for this feature from your side? Do you need help somehow?
Sorry for the super long delay, I've been busy with my job; and honestly no real progress on this  
I did dive into learning Rust and to do this though, and it's an amazing language :D So that's a plus, but yeah, sorry for leaving this issue stale.

@SahAssar
> I tested adding the `socks` feature to the `reqwest` config and it works as expected, but I have no idea how to write the tests.
I haven't worked on this for many months now but I remember that I was planning on making a mock socks5 server in the test functions and then running a code in deno after that, then checking for the correct activity on the socks server.

**Comment by bnoordhuis** [comment]
After internal discussion we think it's fine to land this without a test. Please go ahead and open a PR with the feature flag.
