### ISSUE TITLE
Where to be notified of builds and Releases?

### ISSUE THREAD

**Issue by MasterJames** [denoland/deno#1160]
I was hopeful we could arrange a special mailing list (from some service maybe even mailchimp) or an empty repo to watch for only important announcements.
In particular I would like to know when there are builds available or releases and not have to wade through all the messages in my inbox. It's been helpful to get an idea on what is happening but it's just too much for my little inbox to handle anymore.
Maybe just a note of when maybe I should check back in 6 months, 12 months, years?

**Comment by hayd** [comment]
Looks like Github also offers this now (not sure if this is an announced feature):


<img width="316" alt="Release only subscription" src="https://user-images.githubusercontent.com/1931852/49119408-14d23180-f25d-11e8-9f2a-1d04d45a14ec.png">

**Comment by ry** [comment]
Cool. Closing this one.

**Comment by MasterJames** [comment]
I was just coming to say the new watch release only feature, which I've added.
I should have made the request (where for github in general I have never looked?) myself or added to the discussion for what is surely a long time requested feature.
So many repos I'm interested in monitoring progress of but not on a flood my inbox day to day way.
It will save a lot of email bandwidth. (I know I don't have to get emailed the notifications but it works better that way for me I feel.)
I'm looking forward to a build I can test.
[I'm mostly interested in deno's goal of a more secure sandbox for more real-time custom user modified code, and security etc.]
