### ISSUE TITLE
[Suggestion] Add URLPattern global

### ISSUE THREAD

**Issue by Jamesernator** [denoland/deno#11619]
This is super cutting edge (Chrome Beta only atm), but effectively there's a new web global called `URLPattern` that can be used to test whether a given url string meets a certain pattern. Some examples are available [here](https://web.dev/urlpattern/), and [here](https://github.com/WICG/urlpattern/blob/main/mdn-drafts/QUICK-REFERENCE.md).

As for why I think this global should be added to Deno, essentially this global isn't actually tied to any browser behaviour in any way, and is essentially just a more powerful regular expression so that URLs can be parsed more efficiently.

On the Deno side a couple typical use cases would be things like routing patterns for servers, or for making patterns for globbing the filesystem, etc. Having a standardized syntax for these kinds of patterns would also enable libraries to support such patterns meaning developers wouldn't need to be as concerned with pattern syntax differences from library to library.

**Comment by kitsonk** [comment]
Chrome Platform Status Page: https://chromestatus.com/feature/5731920199548928
DRAFT Specification: https://wicg.github.io/urlpattern/
GitHub repo: https://github.com/WICG/urlpattern

We haven't ever added web APIs as unstable, but it feels like this might be a candidate for as long as it is behind a flag in Chrome/Chromium, and I agree, it is a web API that becomes super useful for runtimes like Deno.

**Comment by crowlKats** [comment]
> We haven't ever added web APIs as unstable

WebSocketStream is unstable

**Comment by lucacasonato** [comment]
@kitsonk Also FYI, URLPattern got the last needed API-OWNER LGTM for the intent to ship in Chromium yesterday.

**Comment by kitsonk** [comment]
Yeah, that is what prompted me to add to the issue. 😏

**Comment by lucacasonato** [comment]
The API will be available in canary in about 30-40 minutes, and in the next stable release (1.14, on the 14th of September). Until the API is stabilized in Chrome Beta, it still requires the `--unstable` flag in Deno.

**Comment by Jamesernator** [comment]
> The API will be available in canary in about 30-40 minutes, and in the next stable release (1.14, on the 14th of September). Until the API is stabilized in Chrome Beta, it still requires the `--unstable` flag in Deno.

I'm pretty amazed this was able to added so quickly.

**Comment by crowlKats** [comment]
> I'm pretty amazed this was able to added so quickly.

I started working on it pretty much instantly the moment you opened the issue, and actually had 3 iterations of the implementation as the spec is still new and kept changing, so took a bit longer than I was hoping for it to take :)

**Comment by matthewp** [comment]
So excited to see this, amazing work @lucacasonato 🙌

**Comment by lucacasonato** [comment]
Thanks, but @crowlKats did the majority of the work :-)

**Comment by matthewp** [comment]
Oh ok, I just looked at the PR, sorry to omit you @crowlKats, great job!
