### ISSUE TITLE
Deno.run sub-process "The system cannot find the file specified.", file exists

### ISSUE THREAD

**Issue by TyPhyter** [denoland/deno#11620]
Windows 10, deno 1.12.2

For this given directory structure
![image](https://user-images.githubusercontent.com/8890430/128725257-f56142e2-b276-4030-9988-9071b08e3464.png)

this script can't find the file  './test/test.aseprite'
![image](https://user-images.githubusercontent.com/8890430/128723911-d44bce0b-0ce6-48fe-9d77-dce3b8a50676.png)
![image](https://user-images.githubusercontent.com/8890430/128725423-68d6774d-b718-4043-b2c8-d436e8864bbc.png)

Keeping all things the same, changing the cmd to just 'ls' like so 
![image](https://user-images.githubusercontent.com/8890430/128725733-08ed1354-74da-4b9c-b071-bd24f4035be9.png)
shows the file is there at the target working directory
![image](https://user-images.githubusercontent.com/8890430/128725796-0e66d44d-bcd3-4b2c-80a0-ec4e6bc49721.png)

I'd be happy for this to be user error, but I've beat my head against this for a while and I'm coming up with nothing.

**Comment by bartlomieju** [comment]
`['touch test.asperite']` should be changed to `['touch', 'test.asperite']`

**Comment by caspervonb** [comment]
Windows so, do you actually have ls in PATH?
