### ISSUE TITLE
[Feature request]: create new projects from CLI

### ISSUE THREAD

**Issue by felipetesc** [denoland/deno#11639]
Hello. I would like to suggest/request the addition of a way to create projects using Deno CLI, like we do when using cargo for Rust. For example:

```bash
deno new --bin project-name 
```
```bash
deno new --lib project-name
```
As we all know, like this, all projects will be organized with a well known structure. Perhaps we can use the config file to help us too, allowing to call external libs. And yes, I know about how deno uses url's to import stuff.
Anyways, Thanks !

**Comment by nayeemrmn** [comment]
Duplicate of #2584.

**Comment by felipetesc** [comment]
Thanks. Closing.
