### ISSUE TITLE
ffi panic on integer parameters over 32bits

### ISSUE THREAD

**Issue by sunsetkookaburra** [denoland/deno#11641]
I've been playing around with the new `Deno.dlopen`. In doing so, I've noticed that integers larger than 32bits produce some weird quirks.
Here is some test C code...
```c
#include <stdint.h>
void takeU64(uint64_t x) {}
void takeU32(uint32_t x) {}
```
and a `dlopen`...
```ts
const dylib = Deno.dlopen("usize.dll", {
  "takeU64": { parameters: ["u64"], result: "void" },
  "takeU32": { parameters: ["u32"], result: "void" },
});
```

And some calls to demonstrate the issue:
```ts
// Perhaps expected, but C would truncate: (uint32_t)(8589934591) == 4294967295
dylib.symbols.takeU32(0x00000001FFFFFFFF);
// thread 'main' panicked at 'Expected ffi arg value to be an unsigned integer', extensions\ffi\lib.rs:260:6

// This runs successfully.
dylib.symbols.takeU64(0x00000000FFFFFFFF);
// This does not.
dylib.symbols.takeU64(0x00000001FFFFFFFF);
// thread 'main' panicked at 'Expected ffi arg value to be an unsigned integer', extensions\ffi\lib.rs:260:6
```

---

I also tried using BigInts to see if this was a problem I could avoid todo with JavaScript's 2^53 integer limit, but this also caused a panic:
```ts
dylib.symbols.takeU64(BigInt(0x00000001FFFFFFFF));
// thread 'main' panicked at 'serde_v8: unknown ValueType for v8::Value', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\serde_v8-0.9.0\src\payload.rs:32:5
```

I'm not experienced enough in the Deno internals or Rust to take this on myself, but I did some digging.
From that `bigint` panic, `payload.rs` in serde_v8 does not have an entry for BigInt. I found a related commit denoland/serde_v8@57ce430716d8abcd44a10166b3282bdb66703f78, but this related issue is still unresolved denoland/deno#6169.

It also feels like the panic error message in [extensions/ffi/lib.rs](https://github.com/denoland/deno/blob/v1.13.0/extensions/ffi/lib.rs) could be improved to show what type was attempted to be passed (if possible to help with issues like this), but I get this API is still unstable and very, very new.

**Comment by littledivy** [comment]
FFI is using `std::convert::TryFrom` which is fails when JS number (`u64`) is out of range of the target type (`u32`). It should be using `T as u32` to truncate to `4294967295` in this case.

**Comment by sunsetkookaburra** [comment]
Progress! I cloned the deno repo and built it for myself, added in some good old print debug statements, and discovered that the value is being passed in as an f64.
```ts
fn value_as_uint<T: TryFrom<u64>>(value: Value) -> T {
  println!("value_as_uint is Number? {}", value.is_number());
  println!("value_as_uint is f64? {}", value.is_f64());
  println!("value_as_uint is u64? {}", value.is_u64());
  ...
```
```
value_as_uint is Number? true
value_as_uint is f64? true
value_as_uint is u64? false
```

**Comment by sunsetkookaburra** [comment]
If i had to have a guess, I'd say this is a problem with op parameters are serialised from javascript.

**Comment by bartlomieju** [comment]
@sunsetkookaburra thanks for debugging it, yes this is most likely problem with `serde_v8` layer which I believe @AaronO was lookingo into

**Comment by littledivy** [comment]
Hmm yeah, value is assumed to be `f64` if not `i32` / `u32`: https://github.com/denoland/serde_v8/blob/9e2aa3c0932c10da778d9dd10950791bfcd77ef8/src/de.rs#L124-L130

**Comment by AaronO** [comment]
> Hmm yeah, value is assumed to be `f64` if not `i32` / `u32`: https://github.com/denoland/serde_v8/blob/9e2aa3c0932c10da778d9dd10950791bfcd77ef8/src/de.rs#L124-L130

That's only if you're doing an "untyped" deserialize (aka `deserialize_any`), which is not recommended.

In the latest `serde` release you should be able to deserialize `BigInt -> u64` (returning u64 as BigInts to JS isn't yet supported).

I can add BigInt support to `deserialize_any()` but it's worth double-checking if we really need to use that.

**Comment by sunsetkookaburra** [comment]
> I can add BigInt support to `deserialize_any()` but it's worth double-checking if we really need to use that.
BigInts are definitely going to be needed if ffi is to deal with 64bit integers and beyond.
Although I guess you're probably just saying there's a better place than `deserialize_any()` for that to happen?

**Comment by littledivy** [comment]
FFI is using `serde_json::Value` which I assume is untyped here.

**Comment by eliassjogreen** [comment]
reopen?
