### ISSUE TITLE
Add an option for structured output to `deno test`

### ISSUE THREAD

**Issue by tdillon** [denoland/deno#11655]
When using Deno in a CI/CD pipeline, it would be nice if `deno test` had an option (e.g., `deno test --xml`) that would output machine readable output which could be parsed by CI/CD tools in order to report test results.

I believe **JUnit XML format** would provide the most widespread benefit since several CI/CD tools already support this format.

- [GitLab](https://docs.gitlab.com/ee/ci/unit_test_reports.html)
- [CircleCI](https://circleci.com/docs/2.0/collect-test-data/)
- [Bamboo](https://confluence.atlassian.com/bamboo/junit-parsing-in-bamboo-289277357.html)

HTML output would be a nice-to-have down the road to be feature complete.

**Comment by bartlomieju** [comment]
While I agree it would be nice to have different output formats, it is non-trivial amount of engineering effort to support them. There's not much interest in this issue and this is not something the core team will prioritize. If contributors want to take a stab at it I suggest to first discuss it in the issue.

**Comment by zookatron** [comment]
Seconding that these would be really great to have!
