### ISSUE TITLE
SubtleCrypto.importKey ignores the value of the `extractable` property

### ISSUE THREAD

**Issue by panva** [denoland/deno#11650]
see [importKey](https://github.com/denoland/deno/blob/v1.13.0/extensions/crypto/00_crypto.js#L441-L540), in its `constructKey` HMAC call the value `extractable` argument is hardcoded to `true`, disregarding the value of the argument passed in.

https://github.com/denoland/deno/blob/v1.13.0/extensions/crypto/00_crypto.js#L519-L525

refs #11481

**Comment by kitsonk** [comment]
How is this not a duplicate of #11481?

**Comment by littledivy** [comment]
Hardcoded `extractable` is intentional, regardless it should throw a `SecurityError` like `generateKey`

**Comment by panva** [comment]
> How is this not a duplicate of #11481?

Because regardless of how #11481 gets resolved the current behaviour is not transparent.
