### ISSUE TITLE
Type definition of RegExp.prototype.compile is wrong

### ISSUE THREAD

**Issue by lambdalisue** [denoland/deno#11663]
Hi. ~~It seems [`RegExp.prototype.compile()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/compile) produce unusable RegExp object like~~ See https://github.com/denoland/deno/issues/11663#issuecomment-897491198

```typescript
const patternA = /.*/;
const patternB = /.*/.compile();
const patternC = /.*/;
patternC.compile();

console.log("patternA", "Success".match(patternA));
console.log("patternB", "Success".match(patternB));
console.log("patternC", "Success".match(patternC));
```

Above code shows

```
patternA [ "Success" ]
patternB [ "" ]
patternC [ "" ]
```

I understand that the method is deprecated but I think Deno should warn and keep the object.

Tested with Deno v1.13.0 on macOS.

**Comment by kitsonk** [comment]
We don't actually touch it, as it comes from v8 directly, but we should unset it so it isn't available.

**Comment by lambdalisue** [comment]
Note that It seems I'm using it wrong. The correct code would be

```typescript
const patternA = /.*/;
const patternB = /.*/.compile(".*");
const patternC = /.*/;
patternC.compile(".*");

console.log("patternA", "Success".match(patternA));
console.log("patternB", "Success".match(patternB));
console.log("patternC", "Success".match(patternC));
```

But it raises Type error anyway

```
Check file:///Users/alisue/ghq/github.com/vim-denops/deno-denops-std/test.ts
error: TS2554 [ERROR]: Expected 0 arguments, but got 1.
const patternB = /.*/.compile(".*");
                              ~~~~
    at file:///Users/alisue/ghq/github.com/vim-denops/deno-denops-std/test.ts:2:31

TS2554 [ERROR]: Expected 0 arguments, but got 1.
patternC.compile(".*");
                 ~~~~
    at file:///Users/alisue/ghq/github.com/vim-denops/deno-denops-std/test.ts:4:18

Found 2 errors.
```

Just for additional information. I'm happy with @kitsonk 's decision.

**Comment by kt3k** [comment]
> We don't actually touch it, as it comes from v8 directly, but we should unset it so it isn't available.

Event if we unset `compile` from RegExp.prototype, the type definition is still there in lib.es5.d.ts, and that situation will cause a different issue. And because we don't change lib dts files copied from TypeScript repository, I think this is an upstream issue.

I asked a question about this there, and they seem accepting the fix of this type definition. https://github.com/microsoft/TypeScript/issues/46030 I hope that will solve this issue.

**Comment by kt3k** [comment]
This was fixed at https://github.com/denoland/deno/pull/12410/files#diff-3b41f09bfee21893c868a399f44ec5fd78179459e0f5be83639c9309170940b4R968

The example above (https://github.com/denoland/deno/issues/11663#issuecomment-897491198) works without type error with Deno v1.17.0 or above.
