### ISSUE TITLE
Deno FFI: Support async function calls

### ISSUE THREAD

**Issue by rracariu** [denoland/deno#11673]
The FFI interface should allow calling functions asynchronously.

This would be necessary as plugin interface allowed defining such async Ops, and in general this would be required in most cases where calling an function might block the event loop.

Some initial ideas in https://github.com/denoland/deno/pull/11152#issuecomment-871262343

**Comment by bartlomieju** [comment]
@piscisaureus do you have an opinion on this one? I think we might somehow shim it using https://github.com/littledivy/deno_bindgen

**Comment by bartlomieju** [comment]
@rracariu does the non blocking option solve the issue for you?

**Comment by rracariu** [comment]
Yes, it does.

**Comment by khanhankkhan** [comment]
Is there any way to use 'await' inside a non_blocking async ffi call? for example boiler plate mongo db connection here:

`let options = ClientOptions::parse_with_resolver_config(&db_url_tls, ResolverConfig::cloudflare()).await.unwrap();`
