### ISSUE TITLE
Not able to extend standard built-in objects while ts can

### ISSUE THREAD

**Issue by yw662** [denoland/deno#11671]
```ts
interface Object {
  foo(): void
}

Object.prototype.foo = function() {console.log(this.toString())}

let a = {}
a.foo()
```

https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgPICMBWEFmQbwChlkYB7MgCgEoAuZANzOABNCBfQwjbXAOgAOUMmBEBPARD7kyyALykAriFzAyIGgQTqAzmQA2U-WQDmlMAAtgOvqIDKYKKDPVqnQobxx5BTnGkUNEA

Is there any way in deno to extend standard built-in objects ?

**Comment by lucacasonato** [comment]
What you are actually doing is this: https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgPICMBWEFmQbwChlkYB7MgCgEoAuZANzOABNCBfQwjbXAOgAOUMmBEBPARD7kyyALykAriFzAyIGgQTqAzmQA2U-WQDmlMAAtgOvqIDKYKKDPVqnQobxx5BTnGkUNFwQAB4CZFB4+OwA3IRAA

Wrap you `interface Object` in `declare global {}`: https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEBzCB7ARlC8DeAoe8AlgHYAuIMAZlGAgPJoBW4pO+B8lKKAFAJQAueADcUhYOwC+uabgbMwpAHQAHGClIaAnipBKuKeAF5OAV2KLCKYvxxhrAZxQQ9qRD1IALQg6WaAyqQwJO58fLIurFDGONJQ+tz8uLggAB4qKDCs2JIA3LhAA
