### ISSUE TITLE
Restricted characters in package names

### ISSUE THREAD

**Issue by rsp** [denoland/deno#1170]
I just saw the [deno.land](http://deno.land/) page that seems to be some early version of a Deno package registry.

I noticed a message next to Create Package / Package Name:
"No spaces. No unicode, use ascii. **Use underscores instead of dash.**" [emphasis added]

I made a quick experiment with dependencies of some popular npm modules and it seems that **most** of the package names **include dashes** (not just more than other punctuation, actually there are more names with than without dashes), for 725 packages in total, 418 had dashes, 17 had dots and only one had an underscore.

Is there any reason to break that convention and specifically recommend using a character that is currently the least popular of all? Also I don't see a lot of underscores in GitHub project names, where also the dash is a convention. I am not particularly concerned with the naming one way or the other but seems this seems to be contrary to the convention used in Node and in frontend, I am wondering if there was any discussion about.

script to quicky reproduce my results if anyone is interested:
```bash
npm init -y
npm i express hapi restify loopback sails koa jest jasmine mocha chai
n=`npm ls | sed 's/@.*//;s/.* //' | sort -u`
echo '*' `echo "$n" | wc -l`
for c in - . _; do echo $c `echo "$n" | grep -cF $c`; done
```
[deno.land](http://deno.land/) screenshot:

![screen shot 2018-11-07 at 7 23 48 pm](https://user-images.githubusercontent.com/119231/48151868-be5b7e00-e2c2-11e8-9aaf-caff6e543782.png)

**Comment by ry** [comment]
That's a very early - not working website. Sorry - I should have hid it better.

Deno is completely decentralized - people are free to put code up wherever they like using an number of dashes in the URL. The `https://deno.land/x/` service is just a connivence for our own libraries and just to have a canonical place where people can see some available code.
