### ISSUE TITLE
Type 'string' is not assignable to type '“UnexpectedEof”'

### ISSUE THREAD

**Issue by chovy** [denoland/deno#11713]
Getting this error when compiling my deno app:

```
$ deno compile --allow-all --unstable --output ./app ./index.ts
Check file:///home/ubuntu/www/iptvfish/iptvfish-api/index.ts
error: TS2416 [ERROR]: Property 'name' in type 'PartialReadError' is not assignable to the same property in base type 'UnexpectedEof'.
  Type 'string' is not assignable to type '"UnexpectedEof"'.
  name = "PartialReadError";
  ~~~~
    at https://deno.land/std@0.74.0/io/bufio.ts:27:3
TS2416 [ERROR]: Property 'name' in type 'PartialReadError' is not assignable to the same property in base type 'UnexpectedEof'.
  Type 'string' is not assignable to type '"UnexpectedEof"'.
  name = "PartialReadError";
  ~~~~
    at https://deno.land/std@0.83.0/io/bufio.ts:27:3

Found 2 errors.
```

```
$ deno -V
deno 1.13.0
```

code worked before i upgraded deno

https://stackoverflow.com/questions/68788608/type-string-is-not-assignable-to-type-unexpectedeof

**Comment by chovy** [comment]
i'm using oak and sqlite

**Comment by lucacasonato** [comment]
@chovy Try update your dependencies (for example oak) to newer versions. If this does not help can you give me the output of `deno info ./index.ts`?

**Comment by horihiro** [comment]
I saw the same error because `oak@v6.1.0`, which imported old `std` before `0.92.0`, was imported in my case,

It seems that `deno@1.13.0` cannot use `std@0.91.0` or before, and I think your `index.ts` or the dependencies imports the old `std`.

You can check the dependencies by the command in [the lucacasonato's comment](https://github.com/denoland/deno/issues/11713#issuecomment-899013798).

**Comment by tak001** [comment]
I'm having the same problem with the same error.
The environment is the same.

**Comment by ngdangtu-vn** [comment]
This happened the same in Opine, and I believe it is not any those framework fault. The root of problem lies in http_error dep. The only way is downgrade Deno to 1.12.2 and wait for the author update dep (and I'm doubt about it)

https://github.com/asos-craigmorten/opine/issues/139

**Comment by lucacasonato** [comment]
This will be fixed in tomorrow's release, and in Deno canary in about 1 hour (`deno upgrade --canary`)
