### ISSUE TITLE
Cannot use the original `Deno.Conn` after `Deno.serveHttp`

### ISSUE THREAD

**Issue by janispritzkau** [denoland/deno#11744]
An example use case where this is needed are http proxies, where after an request with `CONNECT` method and 200 status response, the connection is switched to another protocol.

**Comment by imcotton** [comment]
Still needed.

**Comment by imcotton** [comment]
Didn't realized these APIs available just now, I managed to write some migration code to do the sanity check and it worked so far, will try to give it full coverage soon and keep an eye on its advancing to the stable.

Thanks for the heads up!

**Comment by crowlKats** [comment]
as @magurotuna mentioned, we have `Deno.upgradeHttpRaw` which is exactly for usecases like this, so will close this since it has been addressed.
