### ISSUE TITLE
Lowercase on websocket upgrade header check

### ISSUE THREAD

**Issue by galiazzi** [denoland/deno#11747]
I have a websocket server with deno 1.13 and it started giving the following error when connecting:

```
Invalid Header: 'upgrade' header must be 'websocket'
```

I saw that the update check is case sensitive:

https://github.com/denoland/deno/blob/4b800f5d269de259da29d3b42dae66faf4351476/ext/http/01_http.js#L320

I know the default is 'websocket', but some clients are third-party and it's hard to change their codes.

Is It possible considering a upgrade header with no case sensitive?

**Comment by lucacasonato** [comment]
Do you have a specific client that is not setting this header correctly?

**Comment by galiazzi** [comment]
Yes, it's a desktop app that uses the websocket service. It sends the header:

```
Upgrade: WebSocket
```

The code is signed and for legal reasons must go through an approval process with each new version

**Comment by FloDuno** [comment]
I have the same issue and willing to make a PR to fix it if you need.

**Comment by lucacasonato** [comment]
@FloDuno PR would be very welcome 😁

**Comment by getspooky** [comment]
@lucacasonato can you pls label this as `good first issue`.

@FloDuno PR would be very welcome, the solution would be something like 
```js
if (!/websocket/i.test(request.headers.get("upgrade"))) {
      throw new TypeError(
        "Invalid Header: 'upgrade' header must be 'websocket'",
      );
 }
```

**Comment by crowlKats** [comment]
no need for regex.

**Comment by getspooky** [comment]
There is no need for case sensitive

**Comment by FloDuno** [comment]
I was more thinking about something like this: 
```js
if (request.headers.get("upgrade").localeCompare("websocket") === 0) {
    throw new TypeError(
        "Invalid Header: 'upgrade' header must be 'websocket'",
     );
 }
```

What do you think ?

**Comment by galiazzi** [comment]
what do you think?

something like:

```js
const upgrade = request.headers.get("upgrade");
if (!upgrade || upgrade.toLowerCase() !== "websocket") {
  throw new TypeError(
    "Invalid Header: 'upgrade' header must be 'websocket'",
  );
}
```
