### ISSUE TITLE
REPL multiline bug

### ISSUE THREAD

**Issue by ry** [denoland/deno#1174]
```
> ./target/debug/deno
> 1 + 2
3
> 1 + 2 +
SyntaxError: Unexpected end of input
```

**Comment by hayd** [comment]
Also @kevinkassimo 's [report](https://github.com/denoland/deno/pull/1165#issuecomment-436383458):
```
> var a = "{";
```

**Comment by hayd** [comment]
Perhaps can simply evaluate each line and if it's SyntaxError with "Unexpected end of input" message then await the next line.

Wait until after #1169 .

**Comment by kevinkassimo** [comment]
@hayd it has pitfalls when handling things like

```
> eval("const a = 1; {");
```

**Comment by hayd** [comment]
Perhaps a --check like function to verify syntax without evaluation... Prior to evaluation.

**Comment by daynin** [comment]
I think we can do it when it's done (https://github.com/kkawakam/rustyline/pull/182)

**Comment by bartlomieju** [comment]
No longer happening in v0.5.0, there's still work to be done on REPL but I believe we can close this issue now.
