### ISSUE TITLE
docs(lsp): `deno/registryStatus` notifications are sent as `deno/registryState`

### ISSUE THREAD

**Issue by ayame113** [denoland/deno#11754]
According to the documentation there is a `deno/registryStatus` notification.
https://github.com/denoland/deno/blob/667b026798b5284e9ec8bf47baba80f343975d2e/cli/lsp/README.md#L142-L144
However, it actually seems to send a `deno/registryState` notification.
https://github.com/denoland/deno/blob/bb5bf91067e28cef869f5180dc73a9b86e368bdc/cli/lsp/lsp_custom.rs#L34-L36

Which is correct, `deno/registryStatus` or `deno/registryState`?

**Comment by kitsonk** [comment]
It is what is in the code 😄 .

**Comment by Patil2099** [comment]
I would love to take this up.
