### ISSUE TITLE
`deno test --jobs` raises spurious timeout errors

### ISSUE THREAD

**Issue by aricart** [denoland/deno#11762]
newer versions of Deno including 1.13.1 added the `--jobs` flag, which is awesome, but unfortunately errors that don't happen with the --jobs=1, show up, most of these are related to networking:
```
TimedOut: Operation timed out (os error 60)
    at deno:core/01_core.js:106:46
    at unwrapOpResult (deno:core/01_core.js:126:13)
    at async Object.connect (deno:ext/net/01_net.js:219:13)
```

These _never_  happen otherwise.

**Comment by caspervonb** [comment]
Hmm looks like a legit timeout to me.
Are all the tests hammering on the same socket? what are they connecting to?
