### ISSUE TITLE
Compiler Error 

### ISSUE THREAD

**Issue by malaxmimdkm** [denoland/deno#11772]
error: TS2502 [ERROR]: 'thisArg' is referenced directly or indirectly in its own type annotation.
    bind<T>(this: T, thisArg: ThisParameterType<T>): OmitThisParameter<T>;
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at asset:///lib.es5.d.ts:350:22

TS2577 [ERROR]: Return type annotation circularly references itself.
    bind<T>(this: T, thisArg: ThisParameterType<T>): OmitThisParameter<T>;
                                                     ~~~~~~~~~~~~~~~~~~~~
    at asset:///lib.es5.d.ts:350:54

TS2339 [ERROR]: Property 'transpileOnly' does not exist on type 'typeof Deno'.
      const result = await Deno.transpileOnly({
                                ~~~~~~~~~~~~~
    at https://deno.land/x/attain@1.1.1/viewEngine/ReactCompiler.ts:118:33

Found 3 errors.

**Comment by kitsonk** [comment]
The issue is that attain is not compatible with modern versions of Deno.  It hasn't been updated in almost a year.

You need to downgrade your version of Deno to one supported by the library, get the library author to support a more recent version of Deno or use a different library.
