### ISSUE TITLE
`deno check`

### ISSUE THREAD

**Issue by ry** [denoland/deno#11786]

**Comment by kitsonk** [comment]
Ref: #11786

These two are closely related and will be addressed as part of that feature.

There is an open question in my mind if `deno cache` becomes a redundant sub-command.

**Comment by nayeemrmn** [comment]
> There is an open question in my mind if `deno cache` becomes a redundant sub-command.

Rather, I think `deno cache --check` (#11810) makes `deno check` 100% redundant while the reverse doesn't hold. If we favoured `deno check`, we'd have an annoying situation where `deno cache` is _mostly_ redundant but still needed for the effect of `deno cache [--no-check]`, unable to be deprecated. Alternatively we could forgo this behaviour insisting that people use `deno check` and just ignore the error if they want to, allowing us to deprecate `deno cache`, but this seems weak.

So I think we should drop this proposal in favour of `--check` as currently implemented in #11810.

**Comment by jaydenseric** [comment]
Related discussion: https://github.com/denoland/deno/discussions/12113 .

Deno absolutely needs a CLI command to type check all modules in a project, like how the `deno lint` command works.

**Comment by rivy** [comment]
I'm currently using `deno test --no-run` ... one current benefit of `deno test --no-run FILE1 FILE2` over `deno cache FILE1 FILE2` is that the "test" command actually type checks all the given FILE arguments even if there's an error for one or more, whereas the "cache" alternate stops after parsing a FILE with any errors. The "test" variant is much more efficient when tracking down (possibly multiple) errors.

Whatever the final syntax/type-check variant that `deno` receives, please enable the "test"-type check-all-files behavior.

**Comment by ry** [comment]
[Luca's comment](https://github.com/denoland/deno/issues/14071#issuecomment-1075255767) in a duplicate issue seems reasonable.

- Add `deno check`. It should be exactly the same thing as `deno cache`. 
- Add `deno run --check` for forward compatibility. (It will be required in the future for type-checking.)
- Print "Warning: In future releases deno run will not automatically type check without the --check flag. To opt into this new behavior now, specify DENO_FUTURE_CHECK=1."

The proposed schedule is:
1.21 - we introduce deno check, as described here.
1.22 - do nothing
1.23 - fully disable type checking by default

**Comment by bartlomieju** [comment]
Discussed offline. `--check` should default to type checking only local files; to type check all files (including remote) we should do `--check=all`. Similar to how `--no-check` skips all, or `--no-check=remote` type checks only local files.
