### ISSUE TITLE
Use vector version of the logo in README

### ISSUE THREAD

**Issue by mahozad** [denoland/deno#11785]
Replace the PNG or JPG logo with a vector format like SVG.

**Comment by Patil2099** [comment]
I would love to take this up.

**Comment by mahozad** [comment]
Does not look good on the [GitHub dark theme](https://github.community/t/support-theme-context-for-images-in-light-vs-dark-mode/147981/69):
| Before  | Now |
| ------------- | ------------- |
|![screenshot-github com-2021 08 25-18_10_59](https://user-images.githubusercontent.com/29678011/130802018-3773ad0f-514c-4f0d-9abd-c44baebaf39a.png) | ![screenshot-github com-2021 08 25-18_13_06](https://user-images.githubusercontent.com/29678011/130802184-e2f8aa20-de64-40ad-8e08-481bf147f1f3.png)  |

**Comment by mahozad** [comment]
I can provide a modified version of the SVG if you'd like.
