### ISSUE TITLE
(fmt) Suggestion, ignore `.vscode` by default

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#11797]
Maybe we'd allow it if someone does `deno fmt .vscode/settings.json` but a normal `deno fmt` call could ignore the `.vscode` directory by default.

_Originally posted by @ry in https://github.com/denoland/vscode_deno/issues/498#issuecomment-903074205_

**Comment by bartlomieju** [comment]
Ref #4459

**Comment by lucacasonato** [comment]
We're not going to do this
