### ISSUE TITLE
Request.cache is undefined

### ISSUE THREAD

**Issue by c4spar** [denoland/deno#11801]
The `cache` value from `RequestInit` is not set on the `Request` instance.

Steps to reproduce:

Start deno repl and execute following code:

```js
new Request("http://foo.bar", {cache: "force-cache"}).cache
```
Output:
```js
undefined
```
Expected output:
```js
"force-cache"
```

Deno version:
```console
deno 1.13.1 (release, x86_64-apple-darwin)
v8 9.3.345.11
typescript 4.3.5
```

**Comment by lucacasonato** [comment]
Cache is not implemented.

**Comment by c4spar** [comment]
yeah i know, just wondered why `cache` is undefined if i define it in the constructor but not if i define it as property `request.cache = "force-cache"`. Same applies to:

* credentials
* integrity
* keepalive
* mode
* referrer
* referrerPolicy

**Comment by lucacasonato** [comment]
If you call `request.cache = "force-cache"`, what you are really doing is just setting a property on an object. It is equivalent to doing `request.foo = "bar"`. It is not respected in the init options, because it is not implemented.

**Comment by c4spar** [comment]
yeah sure, I guess I was just confused because the typings are there but the options were ignored, and in my eyes it wouldn't make sense to ignore the init options since it's possible to define any property you want anyway.

But it's no problem for me and i don't realy need these options actually, just noticed it because i'm writing an wrapper for the `fetch` method and some tests are failing since i'm using the init options from the Request instance. But i will just ignore these options until they are implemented.
