### ISSUE TITLE
`deno fmt` shouldn't output to stderr, or should document this behavior

### ISSUE THREAD

**Issue by RussellSanders1** [denoland/deno#11818]
What was the reason to have fmt output the list of formatted files to stderr instead of stdout.  Shouldn't it be used only when formatting fails?  Most cli outputs to stdout when successful, I think fmt should do the same.

**Comment by nayeemrmn** [comment]
Stderr is widely used for "diagnostics", neither stderr nor stdout are wrong for this particular purpose. I think stderr is slightly better here because it has alignment with `deno fmt --check` (which indisputably logs previously mis-formatted files as error info).

**Comment by RussellSanders1** [comment]
That makes sense, would it be worth documenting this behavior?  Maybe it's because I am new to using deno but this was hard to track down, and a single line in the docs would have saved me a few hours of searching for why I couldn't use command substitution with this command

**Comment by kitsonk** [comment]
Closing in favour of denoland/manual#60
