### ISSUE TITLE
FileReader onevent attributes don't conform to spec

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#11816]
There are six related failing tests in wpt/FileAPI/idlharness.any.html. Likely cause is that the function name of the getters and setters is not correct.

**Comment by F3n67u** [comment]
Access webidl attribute such as `onabort` in FileReader idl via prototype should throw `TypeError`, but deno return `null`.

### Chrome
```
FileReader.prototype.onabort
Uncaught TypeError: Illegal invocation
    at <anonymous>:1:22
```

### deno
```
% deno repl
Deno 1.13.2
exit using ctrl+d or close()
> FileReader.prototype.onabort
null
```

**Comment by F3n67u** [comment]
the spec, see https://heycam.github.io/webidl/#LegacyLenientThis

```
// Throws a TypeError, since Example.prototype is not an Example object.
Example.prototype.y;
```

I'd like to help, but I don't have a idea how to throw TypeError when access `Example.prototype.y`

**Comment by F3n67u** [comment]
I tried to fix this problem, could you help to review and tell me what you think? @lucacasonato
