### ISSUE TITLE
lsp: `deno/cache` of modules that contain invalid imports causes client error

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#11825]
Interestingly, I just discovered that my earlier statement that "`deno/cache requests` respond the same for success or failure" is actually untrue. Some sorts of caching errors can lead to a Deno language server internal error with a A JSON-RPC error.

For example, try caching this module (I don't actually need to use it, I just found this error while testing caching with random imports) via the Deno language server:

```
https://deno.land/x/a11yslider/src/index.ts
```

And you will see this error:

```
An unsupported media type was attempted to be imported as a module.
  Specifier: https://deno.land/x/a11yslider@v0.4.7/src/index.css
  MediaType: Unknown
Internal error
```

It looks like this to a user of my [Nova Deno extension](https://extensions.panic.com/extensions/jaydenseric/jaydenseric.deno):

<img width="337" alt="Screen Shot 2021-08-24 at 9 51 40 am" src="https://user-images.githubusercontent.com/1754873/130534221-441484eb-3ff9-452d-9174-f77a60f04a28.png">

If `deno/cache` requests are fire and forget, is that error a bug? Should all errors, not just module 404's, be silent?

_Originally posted by @jaydenseric in https://github.com/denoland/deno/issues/11796#issuecomment-904214148_

**Comment by nayeemrmn** [comment]
No longer an issue. An internal error will only occur right now if e.g. the cwd or some config file is deleted at a precise time, while creating  `CliOptions`.
