### ISSUE TITLE
Programmatic access to cache

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#11829]
With [deno_graph](https://deno.land/x/deno_graph) users can now access the same logic that is used in CLI to generate `deno info` output, except that that output is missing the `DENO_DIR`/cache information.  `deno_graph` contains all the logic necessary to integrate that into a module graph, there isn't a privileged API/op that can provide that information.

The API that is needed is an something like this:

```ts
namespace Deno {
  /** Additional meta data that is used to enrich the output of the module
   * graph. */
  export interface CacheInfo {
    /** The string path to where the local version of the content is located. For
     * non `file:` URLs, this is the location of the cached content, otherwise it
     * is the absolute path to the local file. */
    local?: string;
    /** The string path to where a transpiled version of the source content is
     * located, if any. */
    emit?: string;
    /** The string path to where an external source map of the transpiled source
     * content is located, if any. */
    map?: string;
  }

  export function cacheInfo(specifier: string): CacheInfo;
}
```

In addition, `deno info` would also populate the cache when run, which currently `deno_graph` uses runtime APIs to load the modules, so exposing an API to load modules like the following would allow the cache to be populated:

```ts
namespace Deno {
  export interface LoadResponse {
    /** The string URL of the resource. If there were redirects, the final
     * specifier should be set here, otherwise the requested specifier. */
    specifier: string;
    /** For remote resources, a record of headers should be set, where the key's
     * have been normalized to be lower case values. */
    headers?: Record<string, string>;
    /** The string value of the loaded resources. */
    content: string;
  }

  export function load(specifier: string, isDynamic: boolean): Promise<LoadResponse | undefined>;
}
```

Ref #2096

**Comment by wojpawlik** [comment]
Are cached files stored as UTF-8, or do they use whatever encoding the server used?

Exposing paths to cache would prevent Deno from switching to sqlite-based cache. Better expose `file:///` `URL`s.

No need for `LoadResponse` (https://github.com/denoland/deno/issues/6891#issuecomment-894624552):

```ts
namespace Deno {
  /**
   * If `Response` isn't cached, performs the request and caches `Response`.
   * @permissions `--allow-net --allow-write --allow-read --allow-env`
   */
  export declare function fetchCache(url: string | URL, isDynamic: boolean): Promise<Response>;
}
```

**Comment by wojpawlik** [comment]
What would be the proper way to `Deno.permissions.request` cache access?

**Comment by gyf304** [comment]
This will be very useful for 3rd party build tools, e.g. esbuild to use the same import logic as deno.

**Comment by kitsonk** [comment]
It is unlikely we will add this as an API to the `Deno` namespace.  There is a prototype library [deno_cache](https://deno.land/x/deno_cache) which gives programmatic access to the DENO_DIR in the same way that the Deno CLI uses the cache, and is used by [dnt](https://github.com/denoland/dnt/) when exporting a Deno project.
