### ISSUE TITLE
missing output option for deno info 

### ISSUE THREAD

**Issue by elycheikhsmail** [denoland/deno#11828]
I hope have more control on deno info especialy write the output of this command in file instead of terminal, if possible Deno.info in code it will be code

**Comment by kitsonk** [comment]
It is unlikely we would add an output option, as redirecting stdin to a file is trivial.

As for something like `Deno.info()` that is #2096 but that is going to be closed soon, as https://deno.land/x/deno_graph/ is now available.

**Comment by elycheikhsmail** [comment]
thanks
