### ISSUE TITLE
Consider enabling `"noImplicitOverride"` by default

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#11836]
In TypeScript 4.3, the [`override` keyword](https://devblogs.microsoft.com/typescript/announcing-typescript-4-3-beta/#override-and-the-noimplicitoverride-flag) was introduced which ensure when type checking code that a method with the `override` keyword is present in the base class.  This helps make it more explicit when extending classes.  In addition, there is the flag `"noImplicitOverride"` which enforces that if a method is present in a base class and the extended class that the `override` keyword is present in the extended class, helping ensure that users don't "accidentally" override a method unintentionally.

I am personally not sure about this, as it has a lot of potential to break existing code, but I wanted to bring it up so that we can try to consider what "version" of TypeScript we want to support in Deno.  The existing behaviour allows people to opt-in to using `override` for the protection it offers, but essentially doesn't deliver as "safe" as code as possible.

**Comment by getspooky** [comment]
I think it's a good to enable `noImplicitOverride` in order to to improve code health in the repository. but as you already said it will introduce a lot of code refactoring. A good example of `noImplicitOverride` integration is [Angular](https://github.com/angular/angular/pull/42512).

**Comment by David-Else** [comment]
I think it is one of the best improvements they ever made! I always hated inheritance due to not being sure if the extended class method was overriding the base class. It would be great to enable `noImplicitOverride`.

**Comment by sigmaSd** [comment]
for future searchers to enable this add to deno.json
```json
{
  "compilerOptions": {
    "noImplicitOverride": true
  }
}
```
(take from https://github.com/denoland/deno_std/issues/1933)

**Comment by sigmaSd** [comment]
Maybe this can be considered for deno 2.0 ?

**Comment by sigmaSd** [comment]
though I just discovered this issue https://github.com/microsoft/TypeScript/issues/47250 which makes this feature in my opinion partially finished

**Comment by lucacasonato** [comment]
We're doing this for Deno 2.

**Comment by dsherret** [comment]
I think this one hasn't been decided yet or implemented, so reopening.
