### ISSUE TITLE
First pass at "deno fmt" config

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#11857]
Ref https://github.com/denoland/deno/issues/11686
Ref https://github.com/denoland/deno/discussions/11855

Analogous to adding configuration for `deno lint` I propose to allow configuring 
`deno fmt` via a configuration file (and also using CLI flags as we don't want to have
options in config file that are not available via CLI). I propose to start
with minimal set of options; concretely allow only `useTabs` (that will help
with the accessibility #3695), `tabWidth` and `singleQuote`

```
{
  "compilerOptions": {
    "jsxFactory": "h"
  },

  "lint": {
    "files": {
      "include": ["testdata/"],
      "exclude": []
    },
    "rules": {
      "tags": ["recommended"],
      "include": [
        "ban-untagged-todo"
      ]
    }
  },

  "fmt": {
    "files": {
      "include": ["testdata/"],
      "exclude": []
    },
    "rules": {
      "useTabs": true,
      "indentWidth": 2,
      "singleQuote": true,
    }
  }
}
```

To keep the same configurability in CLI I suggest to add `--rules-use-tabs`, `--rules-indent-width` and `--rules-single-quote` flags to `deno fmt` subcommand.

Similar to linter specifying CLI flags takes precedence over configuration in config file.

Alternatives:
- allow to configure only `fmt.files` and don't allow configuring rules,
this would imply that we should switch default setting to use tabs instead
of spaces to address #3695

**Comment by grian32** [comment]
> Not every option is equally valuable. Prettier seems to regret adding some of them:

Doesn't really change the fact that prettier's current options(the 4 or so that are, trailing commas, tab/space width, semis and single qeuotes) work for pretty much everyone and satisfy pretty much everyone.

**Comment by Skillz4Killz** [comment]
Is there any chance of convincing you not to support this config option at all?

**Comment by David-Else** [comment]
It would be great to get an option for Markdown that turns off the the hard wrapping at 80 characters: https://github.com/denoland/deno/issues/9191
