### ISSUE TITLE
URLSearchParams should convert plus (+) to space

### ISSUE THREAD

**Issue by mmorearty** [denoland/deno#11866]
In a URL's search params, plus should be converted to space. For example, in `https://example.com/?a=b+c`, the value of search param `a` should be `b c`. Example:

```js
// should print "b c", but prints "b+c"
console.log(new URL("https://example.com/?a=b+c").searchParams.get("a"));
```

**Comment by bartlomieju** [comment]
What Deno version are you using? Just tested on latest stable (1.13.2) and I get proper value:
```
❯ deno
Deno 1.13.2
exit using ctrl+d or close()
> console.log(new URL("https://example.com/?a=b+c").searchParams.get("a"));
b c
undefined
```

**Comment by mmorearty** [comment]
Oh sorry I should have checked that, and should have upgraded :(

I was on 1.0.3. You're right, this has been fixed.
