### ISSUE TITLE
lsp: suggestion should include "#privateVariable" when typing it without "#" symbol

### ISSUE THREAD

**Issue by manuelaguirre** [denoland/deno#11861]
I'm working on a Deno project and every time I try to access a private variable previously defined with a "#" prefix I always have to type the symbol first.

IMO the extension should suggest "#variable" when trying to type "variable"

**Comment by kitsonk** [comment]
Looking at this, there is a note in the code about the vscode logic being more complex than what we have, and taking another look, sure enough it is.

I am going to try to fix it to align behaviours.
