### ISSUE TITLE
Inconsistent Source Maps leads to debug usability issues

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#11874]
When emitting sources in Deno, we have inconsistent behaviour and likely incompatible behaviour, which leads to challenges when trying to debug TypeScript code using the debug API with something like Chrome Dev Tools or VSCode.

- When emitting with tsc (when type checking for example), the source file is emitted without inlined sources and the original source is listed in the source map of a sibling of the emitted file.  For example if you use `https://deno.land/std@0.106.0/testing/asserts.ts` in your program, the source map indicates that the original source is `asserts.ts`.  This means that when inspecting and the source map is unwrapped, the original source cannot be found, because the emitted source is located in `$DENO_DIR/gen/https/deno.land/<HASHEDVALUE>.js` while the original source is located in `$DENO_DIR/dep/https/deno.land/<HASHVALUE>` (without any extension) which the debugger has no way if figuring out how to get to.
- When emitting with swc (like with `--no-check`) the source file is emitted with inlined sources, but the source is listed as `"<https://deno.land/std@0.106.0/testing/asserts.ts>"`.  The `<` and `>` braces cause strange behaviour in the debuggers, as well as provide strange results in the likes of vscode, because it can't figure out the language ID of the file.

While embedding the original sources in the emitted source map adds "data" to the emitted file, this is negligible, because it is all done locally via the local cache (and we are already doing it when transpiling with swc), so I think we should embed sources in the output and try to get both tsc and swc to output consistent fully qualified specifiers in the `"sources"` property of the emitted source maps.

Ideally we would get our external source maps working again, I remember we stopped at some point because @bartlomieju ran into an intractable problem and I can't remember what it was.

**Comment by bartlomieju** [comment]
@kitsonk my memory doesn't serve me very well on this topic as this was done pre 1.0, but as far as I remember the problem was that debuggers were inconsistent in handling pragmas - ie. using `//# sourceMappingURL=` with a path to actual source map didn't always work and the best results I got were when using base64 encoded source map in that pragma. 

I agree we should fix it and unify the output between TSC and SWC.
