### ISSUE TITLE
deno test type-checking some unknown <GUID>$deno$test.js file when a test Deno.run's deno

### ISSUE THREAD

**Issue by AlexanderOMara** [denoland/deno#11872]
This is kinda a weird issue I've noticed, where if a Deno test uses `Deno.run` to run some shared code in a deno subprocess, it will print some output that it type-checked a file with a random GUI followed by `$deno$test.js`.

```
$ deno test --allow-run src
running 1 test from file:///.../src/alpha.test.ts
test alpha ... ok (8ms)
running 1 test from file:///.../src/exec.test.ts
test exec ... ok (41ms)
Check file:///.../76c79343-ee67-435f-a02e-6c0bc0619fb5$deno$test.js
running 1 test from file:///.../src/zeta.test.ts
test zeta ... ok (8ms)

test result: ok. 3 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out (561ms)
```

First the `alpha` test ran normally, then the `exec` test ran using `data.ts` in a subprocess, then the `zeta` test apparently triggers the check line.

These are the files I used: 

`src/data.ts`

```ts
export const DATA = "test";
```

`src/alpha.test.ts`

```ts
import { DATA } from "./data.ts";

Deno.test("alpha", () => {
  void DATA;
});
```

`src/exec.test.ts`

```ts
Deno.test("exec", async () => {
  const p = Deno.run({
    cmd: [
      "deno",
      "run",
      "--no-check",
      "src/data.ts",
    ],
  });
  try {
    await p.status();
  } finally {
    p.close();
  }
});
```

`src/zeta.test.ts`

```ts
import { DATA } from "./data.ts";

Deno.test("zeta", () => {
  void DATA;
});
```

**Comment by bartlomieju** [comment]
I believe this is expected - test runner creates a temporary file of all discovered test modules. @caspervonb can you take a look?

**Comment by caspervonb** [comment]
Yeah this is why I've been asking if you wanna do `execute_main_module` as that unblocks the cleanup for this :)
