### ISSUE TITLE
Implement Eye Dropper API

### ISSUE THREAD

**Issue by sno2** [denoland/deno#11892]
[`EyeDropper` Whatwg Specification](https://github.com/WICG/eyedropper-api)

I don't really have any added use-cases in this issue.  You can read the specification's.  Although, I'm not sure how we would handle the picking behavior.  On the web, it shows a picker and hovering glass with individual pixels.  However, including this UI would probably be out of Deno's scope.  Personally, I'd like it to just get the color of the pixel where the mouse is at the current time.  This would be useful when trying to automate things.  Anyways, I just thought that this issue could be the tracking issue for Deno's support of the `EyeDropper` API.

![Image of EyeDropper](https://github.com/WICG/eyedropper-api/raw/main/preview.png)

**Comment by kitsonk** [comment]
The specification is in a very early state.  While it is shipping in Edge/Chrome the proposal still has lots of open questions.  Even then, the API would require Deno to implement and bind to the native system and provide a "eye dropper" interface.  It isn't an API to provide the color under the current mouse position.

What would be a more concrete use case for knowing the colour of a pixel under the current mouse position for a workload you would write under Deno?
