### ISSUE TITLE
Cannot install deno on Windows using cargo

### ISSUE THREAD

**Issue by jankalfus** [denoland/deno#11895]
I'm having issues installing Deno on Windows 10 using `cargo install deno --locked`, the build ends up with an error. I'm attaching output of the command with the `-vv` option included: [out.txt](https://github.com/denoland/deno/files/7093252/out.txt)

Without the `-vv` (as well as with it) option, there are tons of errors related to librusty_v8 in the following format: `librusty_v8-51873035f6e42ac8.rlib(<objfile>.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in  libspirv_cross-cb06a55010dd78eb.rlib(wrapper.o)`

More details:
* OS: Windows 10 Pro 20H2, build 19042.1165
```
$ rustc -V
rustc 1.54.0 (a178d0322 2021-07-26)
$ cargo -V
cargo 1.54.0 (5ae8d74b3 2021-06-22)
```
* I also have VS community 2019 installed with the C++ desktop development toolkit and all of the following tools listed in https://deno.land/manual/contributing/building_from_source#building-deno, including the Debugging Tools for Windows:
    Visual C++ tools for CMake
    Windows 10 SDK (10.0.17763.0)
    Testing tools core features - Build Tools
    Visual C++ ATL for x86 and x64
    Visual C++ MFC for x86 and x64
    C++/CLI support
    VC++ 2015.3 v14.00 (v140) toolset for desktop

What can I do to get around the issue, please? I've tried Googling the issue, which lead me to believe there was some mismatch between the library versions used by Deno, so I'm guessing it's an issue with the package itself? I'm still quite new to Rust and I don't consider myself proficient in C++ though, so sorry if this is a stupid question or I'm mistaken.

**Comment by dsherret** [comment]
The same error happens for me on Windows.

**Comment by cspotcode** [comment]
Could this be related to #10378?

**Comment by jankalfus** [comment]
Hmm, yes, it seems to be possibly the same issue, based on the error numbers and the fact that the linking issue is also in `libspirv_cross` (I haven't noticed that before, for some reason I thought there were link errors with multiple libraries, sorry).

**Comment by cspotcode** [comment]
Looking at the errors, it seems that rusty_v8 and libspirv_cross disagree about whether the binary should be statically or dynamically linked.  What is deno's intention?  When this broke -- whatever caused it to break -- is the problem that libspirv_cross starting erronously building a dynamic library, or is the problme that rusty_v8 started erroneously building a static library?  Or something else?

**Comment by cspotcode** [comment]
To unblock myself in the interim, I modified `deno_runtime` to remove the webgpu extension.

https://github.com/cspotcode/deno/compare/main...cspotcode:without-webgpu
