### ISSUE TITLE
Implement test steps API

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#11901]
We're going to start work on a prototype of the test steps API.

- [ ] Implement proposal without metadata as unstable https://github.com/denoland/deno/discussions/10771
- [ ] Implement proposal with metadata
- [ ] Write polyfill for declarative in CLI https://github.com/denoland/deno/discussions/11235
- [ ] Decide on declarative living in CLI, std, or /x
- [ ] Test implementation with mocha polyfill https://gist.github.com/lucacasonato/54c03bb267074aaa9b32415dbfb25522

**Comment by sebastienfilion** [comment]
The RFC you link (https://github.com/denoland/deno/discussions/10771) is a long conversation with a lot of contracting concepts. Which one exactly do you propose to implement? 
Also, can you define what "metadata" are you referring to?

**Comment by dsherret** [comment]
What's outlined in the main post. See `stepMetadata` property.

**Comment by sebastienfilion** [comment]
Are you going to implement the Tester class? Otherwise, I don't understand to what end.
Also this post is confusing; are you just saying that we're going to implement everything and see what sticks?

**Comment by dsherret** [comment]
We're implementing what's outlined in the RFC at #10771 (so yes, the `Tester` class outlined there). Then we're going to implement a pollyfill for #11235 that uses the implementation of #10771. After we'll make further decisions on where the #11235 approach will live.

**Comment by caspervonb** [comment]
> After we'll make further decisions on where the #11235 approach will live (it might end up being avialble in the CLI, std, or even in deno.land/x. In the case of it being in the CLI then we'll drop the stepMetadata property, but all of this isn't decided yet)

This is fairly confusing.
So we're doing declarative test registration that runs imperative tests that then can be used to registers declarative tests again?

**Comment by dsherret** [comment]
> So we're doing declarative test registration that runs imperative tests that then can be used to registers declarative tests again?

This is a temporary implementation detail. No decision has been made in this regard.

**Comment by caspervonb** [comment]
Immediately executing user controlled tests still fundamentally clash with how regular tests _actually_ work with deferred runner controlled and throttled execution so I'm **very confused** as to how we are planning on making deferred test execution live in deno.land/std or deno.land/x.

**Comment by caspervonb** [comment]
Just to simplify and clarify the main concern, are the execution of subtests in this metadata thing deferred and controlled by the test runner or user?

**Comment by lucacasonato** [comment]
- The step metadata only affects filtering (and maybe display). It can not be used to provide things like permissions.
- Metadata can only be present on top level `Deno.test` registrations.
- Subtests are invoked when `t.step` is called. The returned future resolves when the test is complete. We can delay the actual invocation after calling `t.step` if necessary for whatever reason, because of the returned Promise.

**Comment by caspervonb** [comment]
Thanks @lucacasonato, so this is still just test steps that's slightly less confusing.

>  Write polyfill for declarative in CLI RFC: Test Collections—Declarative approach to subtests #11235
> Decide on declarative living in CLI, std, or /x

This bit is still confusing tho as one just cannot have tightly integrated deferred execution in user land.

**Comment by bartlomieju** [comment]
@dsherret can this issue be closed now?

**Comment by dsherret** [comment]
@bartlomieju yeah, we can decide on next steps later.
