### ISSUE TITLE
Remove `deno test --no-run`

### ISSUE THREAD

**Issue by caspervonb** [denoland/deno#11915]
This flag makes no sense with no_check by default and should be removed in favour of the check command for 2.0 (#11786)

**Comment by nayeemrmn** [comment]
No it would still function to download dependencies, remaining a shortcut for `deno cache <default test globs>`. You would have to do `deno test --check --no-run` (`deno cache --check <default test globs>`) to type-check as well.

**Comment by caspervonb** [comment]
> No it would still function to download dependencies, remaining a shortcut for `deno cache <default test globs>`. You would have to do `deno test --check --no-run` (`deno cache --check <default test globs>`) to type-check as well.

Cache command could be expanded to include test patterns:
```
deno cache --test
```

Makes more sense for the cache commands to be able to do all the caching needed in one shot, no?

**Comment by nayeemrmn** [comment]
> Cache command could be expanded to include test patterns:
> 
> ```
> deno cache --test
> ```
> 
> Makes more sense for the cache commands to be able to do all the caching needed in one shot, no?

That was the initial proposal: #7775. We went with this to avoid test glob logic in `deno cache` (in retrospect I don't think this is a real problem, but both options were fine to me). Either way, this isn't affected by no check by default.

**Comment by caspervonb** [comment]
> > Cache command could be expanded to include test patterns:
> > ```
> > deno cache --test
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Makes more sense for the cache commands to be able to do all the caching needed in one shot, no?
> 
> That was the initial proposal: #7775. We went with this to avoid test glob logic in `deno cache` (in retrospect I don't think this is a real problem, but both options were fine to me). Either way, this isn't affected by no check by default.

True but it is relevant to how cache, check and test all come together in 2.0.
