### ISSUE TITLE
hyper server leaks RequestResource objects

### ISSUE THREAD

**Issue by bnoordhuis** [denoland/deno#11926]
Can be observed by logging the output of `Deno.core.resources()` after every request.

Good:
```
{"0":"tcpListener","2":"httpConnection","3":"responseSender"}
{"0":"tcpListener","5":"httpConnection","6":"responseSender"}
{"0":"tcpListener","8":"httpConnection","9":"responseSender"}
{"0":"tcpListener","11":"httpConnection","12":"responseSender"}
```
Bad:
```
{"0":"tcpListener","2":"httpConnection","4":"responseSender","3":"request"}
{"0":"tcpListener","6":"httpConnection","8":"responseSender","3":"request","7":"request"}
{"0":"tcpListener","10":"httpConnection","12":"responseSender","3":"request","7":"request","11":"request"}
{"0":"tcpListener","14":"httpConnection","16":"responseSender","3":"request","7":"request","11":"request","15":"request"}
```
It's more obvious with http/2 but http/1 POST + request body shows the same behavior.

(http/1 GET does not but I suspect it takes a shortcut and doesn't create a `RequestResource`.)

I'm unclear if the `RequestResource` objects are cleaned up when the connection object is closed, but they're definitely not being cleaned up after the response is sent.

**Comment by lucacasonato** [comment]
To clarify, the RequestResource should be closed once either of the following are true:
- the connection is closed
- the response has been sent, and its body is done streaming

**Comment by bartlomieju** [comment]
I believe this should have been fixed by https://github.com/denoland/deno/pull/11805; what version of `deno_net` are you using currently?

**Comment by bnoordhuis** [comment]
We're not using deno_net but deno_http is at 0.7.0:
```
deno_broadcast_channel = "0.10.0"
deno_console = "0.16.0"
deno_core = "0.98.0"
deno_crypto = "0.30.0"
deno_fetch = "0.39.0"
deno_http = "0.7.0"
deno_timers = "0.14.0"
deno_tls = "0.3.0"
deno_url = "0.16.0"
deno_web = "0.47.0"
deno_webidl = "0.16.0"
deno_websocket = "0.21.0"
```
