### ISSUE TITLE
new Request(request) throws with hyper + http/2

### ISSUE THREAD

**Issue by bnoordhuis** [denoland/deno#11927]
`new Request(request)` throws a `Request with GET/HEAD method cannot have body` exception that originates in ext/fetch/23_request.js, but only for http/2 requests.

I have reason to believe the size_hint check below is why it works for http/1 but not http/2:
https://github.com/denoland/deno/blob/b7c2902c9752e83dc467ce6a812dab4726f200d9/ext/http/lib.rs#L236-L240

**Comment by ry** [comment]
Our `fetch()` already uses HTTP/2 by default... so I would guess GET requests of HTTP/2 is already covered in our unit tests?

**Comment by bnoordhuis** [comment]
Probably, but that's not what this papercut issue is about, if I understand you correctly. Here is a minimal test case:
```js
for await (const conn of Deno.listen({ port: 8888 })) {
  for await (const event of Deno.serveHttp(conn)) {
    new Request(event.request); // <- this
    event.respondWith(new Response("ok"));
  }
}
```
Works fine over HTTP/1.1 but run `curl --http2-prior-knowledge http://127.0.0.1:8888/` and it fails like so:
```
error: Uncaught (in promise) TypeError: Request with GET/HEAD method cannot have body.
    new Request(event.request);
    ^
    at new Request (deno:ext/fetch/23_request.js:327:15)
    at file:///home/bnoordhuis/src/deploy/t.js:3:5
```

**Comment by lucacasonato** [comment]
I know the cause - I'll get to it in a couple of days.
