### ISSUE TITLE
Unable to cache/download "signal" from standard library.

### ISSUE THREAD

**Issue by Scionax** [denoland/deno#11929]
I've never seen this issue before, but when I try to cache https://deno.land/std@0.106.0/signal, my output (in VSCode) will run the normal process, but nothing happens.

```
Server ready.
Download https://deno.land/std@0.106.0/signal
Download https://deno.land/std@0.106.0/signal
Download https://deno.land/std@0.106.0/signal
```

When I hover over it, it still shows "Uncached or missing remote URL: "https://deno.land/std@0.106.0/signal"."

And when I try running the program, it shows this:

```
Download https://deno.land/std@0.106.0/signal
error: Import 'https://deno.land/std@0.106.0/signal' failed: 404 Not Found
```

Everything about the export from deps.ts is the same, I've tried it directly in the file... no luck on either case.

I assume the whole "404 not found" is the issue here, even though the link clearly works.

**Comment by GJZwiers** [comment]
It can't cache `https://deno.land/std@0.106.0/signal` because that's not a module. if you import `https://deno.land/std@0.106.0/signal/mod.ts` it should work

**Comment by Scionax** [comment]
I have no idea how I missed that. Derp.

Thank you.
