### ISSUE TITLE
"Error: not implemented!" on line: signos.map(Deno.signal);

### ISSUE THREAD

**Issue by Scionax** [denoland/deno#11933]
When I try to run any code involving signal or onSignal from `https://deno.land/std@0.106.0/signal/mod.ts`, I get the same result each time. A stacktrace is as follows:

```
error: Uncaught (in promise) Error: not implemented!
  const streams = signos.map(Deno.signal);

    at signal (deno:runtime/js/40_signals.js:173:13)
    at Array.map (<anonymous>)
    at signal (https://deno.land/std@0.106.0/signal/mod.ts:35:26)
```

Here are two sets of code I've tried, each failing at the same line:

```
import { signal } from "https://deno.land/std@0.106.0/signal/mod.ts";
const sig = onSignal(Deno.Signal.SIGINT, () => {
	console.log("Received SIGINT");
	sig.dispose(); // De-register from receiving further events.
});
```

```
import { signal } from "https://deno.land/std@0.106.0/signal/mod.ts";
const sig = signal(
	Deno.Signal.SIGUSR1,
	Deno.Signal.SIGINT
);

setTimeout(() => {}, 5000) // Prevents exiting immediately

for await (const _ of sig) {
	console.log("interrupt or usr1 signal");
}
```

**Comment by GJZwiers** [comment]
It looks like the signals are not implemented for Windows. If you go to the lines of code mentioned in the stack trace you'll find:
```
  function signal(signo) {
    if (build.os === "windows") {
      throw new Error("not implemented!");
    }
    return new SignalStream(signo);
  }
```

There's already an issue to support (some) signals on Windows: #10258 but it's still a work in progress.

**Comment by bartlomieju** [comment]
@GJZwiers is correct, though error message is confusing. I'll fix it.

**Comment by Scionax** [comment]
Makes sense, thank you. Since there's already a ticket that would effectively address this, I'm closing this.
