### ISSUE TITLE
`deno bundle` and `Deno.emit()` do not create the same output

### ISSUE THREAD

**Issue by khrome83** [denoland/deno#11943]
## Version Info

```
deno 1.13.2 (release, aarch64-apple-darwin)
v8 9.3.345.11
typescript 4.3.5
```

I am not sure if this is a issue, but this simple example illustrates that tree-shaking is very different between `deno bundle` and `Deno.emit()`.

### entry.js 

```
import { app } from "./user.js";

let start = false;

if (start) {
  app();
}
```

### user.js

```
export function app() {
  console.log("hello");
}
```

### cli
```
deno bundle entry.js output.bundle.js
```

### deno bundle output
```
function app() {
    console.log("hello");
}
let start = false;
if (start) {
    app();
}
```

### Deno.emit() Setup
```
 const result = await Deno.emit('/entry.js', {
    sources: {
      '/entry.js': <contents of entry.js>,
      '/user.js': <contents of user.js>,
    },
    check: false,
    bundle: "module"
  });
```

### Deno.emit() Output
```
let start = false;
if (start) {
    app();
}
```

`deno bundle` will persist the uncalled app(), where `Deno.emit()` will not.

Not sure if this is expected, or if a compiler option modifies this behavior?

**Comment by dsherret** [comment]
@khrome83 could you post your full `Deno.emit` code?

With the following input in 1.13.2:

```ts
const result = await Deno.emit('/entry.js', {
    sources: {
      '/entry.js': 'import { app } from "./user.js";\n\nlet start = false;\nif (start) {\n  app();\n}',
      '/user.js': 'export function app() {\n  console.log("hello");\n}',
    },
    check: false,
    bundle: "module"
 });
```

I get the output:

```ts
function app() {
    console.log("hello");
}
let start = false;
if (start) {
    app();
}
```

**Comment by khrome83** [comment]
I can not reproduce this either. I had a ton of code changes workshopping how to solve a issues and this was in the middle of all that. 

I thought this similar example represented the problem. but maybe there is something I am missing.

I will close the issue, and ask that it is reopened if I can reproduce it later.
