### ISSUE TITLE
Inspector doesn't have a default execution context

### ISSUE THREAD

**Issue by caspervonb** [denoland/deno#11968]
Invoke Runtime.evaluate without a `executionContextId` and it'll error.
Worked around this before internally, specifically in the repl.

Removing executionContextId from any of the calls in https://github.com/denoland/deno/blob/main/cli/tools/repl.rs#L591 is enough to replicate it.

I'll follow up with a userland example on how to trigger it.

**Comment by bartlomieju** [comment]
I discussed this with @caspervonb in depth offline. This is quite an esoteric setting and there are some bits of the API we might be missing. These bits are not really documented and only way to find them is by searching through other codebases (like V8 or Node).

There's `auxData` field that can be passed to `V8ContextInfo` info: https://github.com/nodejs/node/blob/f8836b208c43c2965061e0493948cf35d946fb87/src/inspector_agent.cc#L416-L433; which can later be used by devtools when reporting context creation:
- https://chromium.googlesource.com/v8/v8.git/+/refs/heads/main/src/inspector/v8-runtime-agent-impl.cc#903
- https://source.chromium.org/chromium/chromium/src/+/main:third_party/devtools-frontend/src/front_end/core/sdk/RuntimeModel.ts;l=111-117?q=isDefault&start=31

This is not something that's a priority and shouldn't be a problem until we support multiple contexts in `JsRuntime`; which on its own will take huge effort starting with `rusty_v8`.
