### ISSUE TITLE
Don't report diagnostics for "external" TypeScript code

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#11970]
When type checking a project, by default don't report type diagnostics for "external" files.  (raised as 2.0 scope by @lucacasonato)

Things we need to do to make this proposal more viable would be:

- Define what "external" files are.  Are they any modules outside the cwd/root of a project? Are they only remote modules?
- How would this integrate well with #11340 without adding a lot of complexity?

**Comment by wojpawlik** [comment]
If reporting diagnostics only for _local_ TypeScript files would speed up diagnostics, it'd be an interesting _alternative_ to https://github.com/denoland/deno/issues/11340.
Also, I'd have prevented https://github.com/colinhacks/zod/pull/648.
