### ISSUE TITLE
Wrong error message for invalid destructuring

### ISSUE THREAD

**Issue by timonson** [denoland/deno#11979]
Looks like a wrong error message to me:

```javascript
function foo([a]) {
  console.log(a);
}

foo({ 0: "a" });
```

>error: Uncaught TypeError: undefined is not a function
function foo([a]) {

**Comment by nhrones** [comment]
run from Chrome Devtools console =
```js
function foo([a]) {
  console.log(a);
}

foo({ 0: "a" });
VM34:1 Uncaught TypeError: undefined is not a function
    at foo (<anonymous>:1:13)
    at <anonymous>:5:1
```

**Comment by timonson** [comment]
Doesn't change the wrongness :)

**Comment by nhrones** [comment]
It's a V8 error!!

**Comment by timonson** [comment]
I got it, thx! It is really an unfortunate error message. You want me to close this issue nevertheless?

**Comment by piscisaureus** [comment]
Upstream bug: https://bugs.chromium.org/p/v8/issues/detail?id=5532

I'll close this issue here because there's nothing Deno can realistically do about it.
