### ISSUE TITLE
Lockfile should be written by default

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#11971]
Under certain conditions, the lockfile should be written and enforced by default.  (raised as 2.0 scope by @bartlomieju)

**Comment by vwkd** [comment]
More previous discussion in https://github.com/denoland/deno/issues/200

**Comment by dsherret** [comment]
We're planning on doing this by default in 1.28 if you have a deno.json file (so the lockfile would be automatically written beside that).

**Comment by jsejcksn** [comment]
The [1.27 release blog post](https://deno.com/blog/v1.27#lockfile-v2) links to this issue:

> Note that in the 1.28 release we are planning to write a lockfile by default if you are using a deno.json file. Follow issue [#11971](https://github.com/denoland/deno/issues/11971) for updates.

Any improvement in increased integrity-checking by default seems great!

However, the information in the release notes combined with what's in this issue don't explain how this is planned to work — can someone from Deno core provide some clarity?

Here are my initial questions:

1. Is this for all Deno programs, or just the subset which use npm dependencies / Node compat mode?

2. Kitson [said](https://github.com/denoland/deno/issues/11971#issue-992804519):

    > Under certain conditions, the lockfile should be written and enforced by default.

    What I want to know:

    What are the "certain conditions" which are planned to enable this auto-writing behavior?


3. David [said](https://github.com/denoland/deno/issues/11971#issuecomment-1292281985):

    > We're planning on doing this by default in 1.28 if you have a deno.json file (so the lockfile would be automatically written beside that).

    and the [Configuration File](https://deno.land/manual@v1.27.0/getting_started/configuration_file#configuration-file) section in the manual includes this:

    > The configuration file supports `.json` and `.jsonc` extensions. [Since v1.18](https://deno.com/blog/v1.18#auto-discovery-of-the-config-file), Deno will automatically detect `deno.json` or `deno.jsonc` configuration file if it's in your current working directory (or parent directories). To manually tell Deno to use a specific configuration file pass `--config path/to/file.json` flag.
    >
    > > ⚠️ Starting with Deno v1.22 you can disable automatic detection of the configuration file, by passing `--no-config`.

    What I want to know:

    3A. Does this mean that using the `--no-config` argument will also prevent auto-writing the lockfile?

    3B. Since the lockfile is planned to be written beside the deno config file, is there potential for any kind of conflict to arise from programs in subdirectories which don't have their own deno config (since each will walk the FS to find the closest parent deno config)?

**Comment by dsherret** [comment]
Subject to change...

> Is this for all Deno programs, or just the subset which use npm dependencies / Node compat mode?

All.

> What are the "certain conditions" which are planned to enable this auto-writing behavior?

When a deno.json file is resolved and no `--lock <file>` is specified. Probably there will be a cli flag like `--no-lock` to prevent it.

> Does this mean that using the --no-config argument will also prevent auto-writing the lockfile?

Yes.

> Since the lockfile is planned to be written beside the deno config file, is there potential for any kind of conflict to arise from programs in subdirectories which don't have their own deno config (since each will walk the FS to find the closest parent deno config)?

The lockfile will be addiditve so if multiple scripts resolve to the same deno.json then they will share the same lockfile.

**Comment by jsejcksn** [comment]
Thanks @dsherret.

Feedback/bikeshedding:

> Probably there will be a cli flag like `--no-lock` to prevent it.

Since there's already `--lock-write`, another idea: `--no-lock-write` or `--lock-write=false`.

Perhaps this can (also) be configured using an environment variable (e.g. `DENO_NO_DEFAULT_LOCKFILE=1`).

**Comment by bartlomieju** [comment]
This is now done and will be released in v1.28.

@jsejcksn we went with `--no-lock` after all.

**Comment by jespertheend** [comment]
For the record, I'm already seeing a lockfile automatically being generated while using Deno 1.27.2. Not sure if this is intended.

**Comment by bartlomieju** [comment]
It is, if you use `--unstable` flag. With v1.28 it will be even without `--unstable`.

**Comment by jespertheend** [comment]
Ah that would explain it! I'm using `--unstable` yeah.

**Comment by Leokuma** [comment]
FYI, the [official Deno Dockerfile sample](https://hub.docker.com/r/denoland/deno/) at DockerHub doesn't work anymore (at least on Windows) if your project has a `deno.json`, because now `deno cache` attempts to _create_ a file (`deno.lock`) and the user `deno` has no writing permissions (I guess):

![image](https://user-images.githubusercontent.com/9329952/202806177-bc656543-041d-483d-9e5b-83f5f8f89825.png)

![image](https://user-images.githubusercontent.com/9329952/202809884-ddf6b9e5-f48d-40c1-a03f-03d6af3b14a5.png)

**Comment by randallb** [comment]
Thank you!! This is such a huge feature / usability win.
