### ISSUE TITLE
deno_core crate fails on latest main branch on ubuntu 20.04

### ISSUE THREAD

**Issue by jmfrank63** [denoland/deno#11977]
This is a weird one, and it is definitely short lived. Likely something isn't installed but I cannot tell what:
 
I am writing an actix web based key value store that can execute its values.

My code works on Mac aarch64 and on Windows amd64 with WSL2. This is the function where rust panics:
```
pub fn patch(key: String) -> String {
    let value = get(key.clone());
    println!("Patch: {}", value);
    let mut runtime = interpreter();
    let result = runtime
        .execute_script(key.as_str(), value.as_str())
        .unwrap();
    {
        let isolate = runtime.v8_isolate();
        let scope = &mut HandleScope::new(isolate);
        let context = Context::new(scope);
        let scope = &mut ContextScope::new(scope, context);
        let res = result.get(scope);
        res.to_rust_string_lossy(scope)
    }
}
```
patch is the HTTP patch request handler for actix (factored out as I had trouble making it async)
I am using the git main branch in cargo.toml. Rust is 1.55 stable, no nightly installed. actix is 4.0.0-beta.9.
I know it is bleeding edge whereever you look. I am happy to have already two platforms where it works.

On Ubuntu 20.04 hosted on AWS the project won't compile and it fails (transferred binary) with
```
thread 'actix-rt|system:0|arbiter:0' panicked at 'called `Result::unwrap()` on an `Err` value: No such file or directory (os error 2)', /home/johannes/.cargo/git/checkouts/deno-22855de1c03c9128/a5bcf70/core/runtime.rs:362:38
```

Compilation fails with cc exit 1, common if something is missing. Since my instance always stalls I cannot tell what is missing. After reboot everything is fine again until I start compiling again. I use the wsl2 compiled binary on ubuntu.
It also fails when running in a docker container, probably with the same error. The error shows failing at init extension and there is a TODO right above this line ;-)

I am aware that deno is work in progress, not expecting anything at the moment. If someone, however, by chance as an idea how to work around this issue I'd be glad. Since I am in the final week of my MsC master project I will be a little tight in time testing any patches. I'll open source the code once I have submitted my report.
Should this still be  an issue then, I am happy to help.

Thanks for the great work.

**Comment by jmfrank63** [comment]
It did compile now on ubuntu, failure was a simple memory issue, the small project sums up to 238 packages and 2 GB memory is simply not enough. 8G did the trick.
I leave it up to you if you want to investigate the docker issue or simply close it.

Here is the dockerfile:

```
ARG DISTRO
FROM rust:1.53 as planner
WORKDIR rs3
# We only pay the installation cost once,
# it will be cached from the second build onwards
RUN cargo install cargo-chef
COPY . .
RUN cargo chef prepare  --recipe-path recipe.json

FROM rust:1.53 as cacher
WORKDIR rs3
RUN cargo install cargo-chef
COPY --from=planner /rs3/recipe.json recipe.json
RUN cargo chef cook --release --recipe-path recipe.json

FROM rust:1.53 as build
ENV PKG_CONFIG_ALLOW_CROSS=1

WORKDIR rs3
COPY . .
COPY --from=cacher /rs3/target target
COPY --from=cacher $CARGO_HOME $CARGO_HOME
RUN cargo install --path .

ARG DISTRO
FROM ${DISTRO}

COPY --from=build /usr/local/cargo/bin/rs3 /usr/local/bin/rs3

EXPOSE 8080

ENTRYPOINT ["/usr/local/bin/rs3"]
```

**Comment by bartlomieju** [comment]
Thanks for detailed write up @jmfrank63; I don't think there's anything actionable for us here so I'm going to close the issue for now.
