### ISSUE TITLE
emit mis-labelled as compiled in help test for `deno info`

### ISSUE THREAD

**Issue by GJZwiers** [denoland/deno#11987]
`deno info --help` mentions the `compiled` and `map` fields for TypeScript files but these don't show when I run `deno info` on a TS file, either local or remote.

**Comment by kitsonk** [comment]
The only appear if they exist.

While we have the infrastructure to emit seperate map files, we currently don't.  To get _emit_ to display (the name was changed but the help text doesn't match) you need to either run or cache the file so it gets emitted. For example:

```
> deno cache mod.ts
```

I have converted this into a bug about the text being incorrect in the help around `compiled` versus `emit`.

**Comment by GJZwiers** [comment]
Thank you, that clarifies things. I have made a PR that updates the help text a little bit
