### ISSUE TITLE
`deno info` 'emit' field showing `.ts.js` extension

### ISSUE THREAD

**Issue by GJZwiers** [denoland/deno#11986]
When running `deno info mod.ts` the printed `emit` field shows a path with a duplicate extension `.ts.js`. `mod.ts`contains just some re-exports:

```ts
// mod.ts
export { foo, bar, baz } from "./mods/mod.ts"
```
```
deno info mod.ts
local: /mnt/c/Users/User/foo/bar/mod.ts
type: TypeScript
emit: /path/to/some/project/mod.ts.js
dependencies: 3 unique (total 11.42KB)
```

`deno --version`:
```
deno 1.13.2 (release, x86_64-unknown-linux-gnu)
v8 9.3.345.11
typescript 4.3.5
```

**Comment by kitsonk** [comment]
That is working as designed.  It is the way we emit files.  What problem is it causing?

**Comment by GJZwiers** [comment]
It's not causing issues in any code, but it looks like it might be a bug to the untrained eye. Given the contents of that particular `.ts.js` file I guess I expected something with  `.map`, same as when running `tsc` with the `sourceMap` option. Closing this now.
