### ISSUE TITLE
Add JSON Schema for config file to `cli/schemas`

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#12061]

**Comment by bartlomieju** [comment]
I thought with discussion in https://github.com/denoland/deno/issues/11885 we were not going to add JSON schema for config file and instead do an "associated file" in VSCode? I still plan to add examples in manuals as part of https://github.com/denoland/manual/issues/75

**Comment by kitsonk** [comment]
Correct, as we have to associate a schema to a file! 😉  I've written a few schemas recently, I would be glad to do it.

**Comment by bartlomieju** [comment]
> Correct, as we have to associate a schema to a file! 😉 I've written a few schemas recently, I would be glad to do it.

I'm already on it, I'll let you know if I hit any roadblocks.

**Comment by kitsonk** [comment]
Duplicate of #11885
