### ISSUE TITLE
Mutual TLS example doesn't compile

### ISSUE THREAD

**Issue by GJZwiers** [denoland/deno#12089]
The example in the Deno 1.14 blog on Mutual TLS throws a TypeError because `Deno.readFileSync` returns a `Uint8Array` but the `certChain` and `privateKey` properties are of type `string`. `Deno.readTextFileSync` or  `TextDecoder` should be used to compile it successfully.

**Comment by bartlomieju** [comment]
Thanks, the fix should be live in a few minutes.
