### ISSUE TITLE
Signal issue in std/node/os.ts in Deno 1.14.0

### ISSUE THREAD

**Issue by Scionax** [denoland/deno#12087]
I upgraded to Deno 1.14.0, and now I'm getting the following error:

```
error: TS2551 [ERROR]: Property 'Signal' does not exist on type 'typeof Deno'. 'Deno.Signal' is an unstable API. Did you forget to run with the '--unstable' flag, or did you mean 'signal'?
  signals: Deno.Signal,
                ~~~~~~
    at https://deno.land/std@0.101.0/node/os.ts:246:17

    'signal' is declared here.
      export function signal(sig: Signal): SignalStream;
                      ~~~~~~
        at asset:///lib.deno.unstable.d.ts:651:19
```

**Things of note / things I've done:**
1. --unstable flag is on.
2. Git repository shows no changes for the last 5d except for a small blurb I commented out. In other words, no code change between updates.
3. All code related to signals was already commented out, since it wasn't functioning previously anyway. Due to the lack of any additional stack trace beyond 'lib.deno.unstable.d.ts', I don't know what I could change.
4. I tried updating all other STD exports in deps to 0.107.0, but this hasn't had any effect.

I can't think of anything else relevant to this issue, but it's also preventing me from doing any development since I can no longer run the server.

**Comment by ry** [comment]
Sorry for the bumpy right with these unstable APIs. We hope to stabilize them soon.

The changes you need to make are described in https://deno.com/blog/v1.14#changes-to-os-signals-apis
