### ISSUE TITLE
delete globalThis.Deno causes CLI REPL to panic!() crash

### ISSUE THREAD

**Issue by jayphelps** [denoland/deno#12092]
When using the CLI REPL:

```bash
➜  deno git:(main) ✗ deno
Deno 1.13.2
exit using ctrl+d or close()
> delete globalThis.Deno; // <----- here is the code
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', cli/tools/repl.rs:643:45
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

When using `deno run` it's not a problem:

```js
delete (globalThis as any).Deno;
console.log(globalThis.Deno);
// undefined
```

```bash
deno run example.ts
```

---

This is super obscure and probably shouldn't be a priority, but reporting none the less since it is a crash.

**Comment by bartlomieju** [comment]
This is the same problem as https://github.com/denoland/deno/issues/9916

**Comment by jayphelps** [comment]
@bartlomieju ah ha! Good catch. That one is much less obscure. Thanks!

**Comment by kt3k** [comment]
This one seems a different bug from #9916.

#9916 panics at line 493 of cli/tools/repl.rs. This one panics at line 643.

**Comment by bartlomieju** [comment]
Quick investigation yields that we use `Deno` global in internal REPL code, example:
https://github.com/denoland/deno/blob/72836478f2737593fb9d932304e7d0279e82a2cc/cli/tools/repl.rs#L629-L635

I think the easiest fix is to save reference to `Deno` global in some magic variable (eg. `const $$replDeno = Deno`) when REPL is starting up and only use that reference instead of the global, however that would still be prone to failure if someone changes to value of the "magic variable".

**Comment by DjDeveloperr** [comment]
@kt3k this seems like same bug and should be fixed as my previous issue is now closed
line number change comes from a newer deno version.

![image](https://user-images.githubusercontent.com/43033058/135557574-71b6e254-bb4a-40ed-8d17-7e321f1f312e.png)

**Comment by kt3k** [comment]
@DjDeveloperr I looked into more detail, and I found that repl panics at different lines depending on the assigned value 🤔 

```
deno $ deno        
Deno 1.14.2
exit using ctrl+d or close()
> globalThis = null
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', cli/tools/repl.rs:643:45
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
deno $ deno
Deno 1.14.2
exit using ctrl+d or close()
> globalThis = 1
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', cli/tools/repl.rs:493:8
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
deno $ deno
Deno 1.14.2
exit using ctrl+d or close()
> globalThis = {}
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', cli/tools/repl.rs:493:8
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

#12273 fixed the case of line 493, but it didn't address the case of line 643

**Comment by bartlomieju** [comment]
Pointed by @evanwashere on Discord, we could probably use `object_id` from CDP messages to store references to `globalThis` and `Deno`, and then use [`callFunctionOn`](https://chromedevtools.github.io/devtools-protocol/tot/Runtime/#method-callFunctionOn)
