### ISSUE TITLE
Performance issue when using a string to create a Response object

### ISSUE THREAD

**Issue by lmalheiro** [denoland/deno#12090]
This problem is similar to the one described in point 1 of issue https://github.com/denoland/deno/issues/10978 reported by @andreubotella.

Deno's `Response` object constructor accepts a string as a body parameter, which passes through an unnecessary conversion to `USVString` for the same reasons already explained in point 1 of previously mentioned issue. This results in significant loss of performance for large input parameters.

The conversion is done in this line of code:
https://github.com/denoland/deno/blob/4283e2907e13a089fa2d026c92e074f019550880/ext/fetch/22_body.js#L396

**Comment by andreubotella** [comment]
After #12201, it seems like this issue can be closed.
