### ISSUE TITLE
Bug macOS: Watching on Samba Fileshare throws an not yet implemented

### ISSUE THREAD

**Issue by lucsoft** [denoland/deno#12097]
I'm on macOS mounted a Windows file share.
i am watching the Filesystem for changes. When a change happens, i get a panic.

**Code**
```ts
for await (const event of Deno.watchFs(["/Volumes/deployments/"])) {
    console.log(">>>> event", event);
}
```

**Error**
```
thread '<unnamed>' panicked at 'not yet implemented', runtime/ops/fs_events.rs:80:27
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by kitsonk** [comment]
We should throw and not panic here.  The feature will still be un-supported.

**Comment by lucsoft** [comment]
or just make a "unkown" call that still fires
this would solve my issue
just throw would not really solve it

**Comment by kitsonk** [comment]
It is then catchable.  Just watching something that never emits and lets your program run endlessly doesn't seem like a good solution.

**Comment by lucsoft** [comment]
No I mean it still emits a event but form unknown source. (FsEvent has then a new `unknown` to the kind type added)

Just throw and catch them does also work but is very ugly and doesn't really change expect making it verbose for the same effect

**Comment by lucacasonato** [comment]
I have looked into this now: the `Other` event type is currently only emitted with a `Rescan` flag on the event. Docs on rescan from `notify`:

> Rescan notices are emitted by some platforms (and may also be emitted by Notify itself).
> They indicate either a lapse in the events or a change in the filesystem such that events
> received so far can no longer be relied on to represent the state of the filesystem now.
> 
> An application that simply reacts to file changes may not care about this. An application
> that keeps an in-memory representation of the filesystem will need to care, and will need
> to refresh that representation directly from the filesystem.

Is this useful? I don't know. I think there are two reasonable paths forward:
1. ignore `Other` events - most users are unlikely to care about them
2. emit the `"other"` event - in this case our `FsEvent` object needs an additional `flags: FsEventFlag[]` key, where `type FsEventFlag = "rescan"`

WDYT?

**Comment by lucsoft** [comment]
This sounds great!
