### ISSUE TITLE
Remove "standalone" resource method from `Deno` namespace

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#12107]
Methods like `Deno.read()` and `Deno.write()` are effectively redundant as there are other better objects to manage the resources (like `Deno.File`) and having to deal explicitly with the _rid_ which is just a number can be confusing and error prone to users.

**Comment by caspervonb** [comment]
> Methods like `Deno.read()` and `Deno.write()` are effectively redundant as there are other better objects to manage the resources (like `Deno.File`) and having to deal explicitly with the _rid_ which is just a number can be confusing and error prone to users.

I'm in favour but note that that this will completely break std/wasi, that's okay but I'll have to rewrite it.

**Comment by bartlomieju** [comment]
`Deno.seek()` and `Deno.seekSync()` should be removed as well.

**Comment by bartlomieju** [comment]
More methods that should be moved to `Deno.File` class:
- `Deno.fsyncSync`
- `Deno.fsync`
- `Deno.fdatasyncSync`
- `Data.fdatasync`
- `Deno.flock`
- `Deno.flockSync`
- `Deno.funlock`
- `Deno.funlockSync`

CC @caspervonb

**Comment by caspervonb** [comment]
> More methods that should be moved to `Deno.File` class:
> 
> * `Deno.fsyncSync`
> * `Deno.fsync`
> * `Deno.fdatasyncSync`
> * `Data.fdatasync`
> * `Deno.flock`
> * `Deno.flockSync`
> * `Deno.funlock`
> * `Deno.funlockSync`
> 
> CC @caspervonb

SGTM, patches coming right up.

**Comment by wojpawlik** [comment]
Should `Deno.close` be deprecated in favor of `Deno.File::close`?

**Comment by bartlomieju** [comment]
> Should `Deno.close` be deprecated in favor of `Deno.File::close`?

It's still debated, but most likely it won't be deprecated.

**Comment by caspervonb** [comment]
> > Should `Deno.close` be deprecated in favor of `Deno.File::close`?
> 
> It's still debated, but most likely it won't be deprecated.

I think we should, in favour of using explicit resource management (https://github.com/tc39/proposal-explicit-resource-management stage 2) and finalisers.

**Comment by bartlomieju** [comment]
> > > Should `Deno.close` be deprecated in favor of `Deno.File::close`?
> > 
> > 
> > It's still debated, but most likely it won't be deprecated.
> 
> I think we should, in favour of using explicit resource management (https://github.com/tc39/proposal-explicit-resource-management stage 2) and finalisers.
> 
> Isn't the point of removing these to get rid of isomorphic resources internally?

It's a good point and that proposal looks interesting. Ideally we should eyeball adding automatic cleanup for all resources using `FinalizationRegistry`. I'm not sure though, if we could deliver on that for 2.0.

**Comment by piscisaureus** [comment]
I don't see the point of removing these methods at this time - it just breaks user code unnecessarily. 
We should have a discussion on how to proceed with automatic resource cleanup first.

**Comment by bartlomieju** [comment]
This is now done as of https://github.com/denoland/deno/pull/25213 and Deno `2.0.0-rc.0`.
