### ISSUE TITLE
deno_http_native latency has regressed

### ISSUE THREAD

**Issue by piscisaureus** [denoland/deno#12102]
https://deno.land/benchmarks?-1000

![image](https://user-images.githubusercontent.com/218257/133671552-1abadc81-7115-4a20-aa1f-e3bde41d1950.png)

**Comment by AaronO** [comment]
Appears to be caused by https://github.com/denoland/deno/commit/40b083c540b90766ea746fc869bf8ea9634eaf06 / https://github.com/denoland/deno/pull/11126

**Comment by piscisaureus** [comment]
@bartlomieju Can you verify whether 40b083c is actually the cause and fix it?

**Comment by bartlomieju** [comment]
> @bartlomieju Can you verify whether [40b083c](https://github.com/denoland/deno/commit/40b083c540b90766ea746fc869bf8ea9634eaf06) is actually the cause and fix it?

I can, but how should I fix it? Revert the addition of abort signal?

**Comment by piscisaureus** [comment]
> I can, but how should I fix it? Revert the addition of abort signal?

If that turns out to be the cause, we should consider that. 
But before that, we should find out whether this is actually the cause; it could also be #11120 or #11113.

**Comment by bartlomieju** [comment]
> > I can, but how should I fix it? Revert the addition of abort signal?
> 
> If that turns out to be the cause, we should consider that.
> But before that, we should find out whether this is actually the cause; it could also be #11120 or #11113.

I see, sure I can look into that, but this looks like an obvious culprit - `AbortSignal` extends `EventTarget` and does some WebIDL conversions - we already added "fast paths" to `Request` and `Response` objects because of similar regressions in the past.

**Comment by bartlomieju** [comment]
This was fixed.
