### ISSUE TITLE
Replace text-encoding

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#1210]
I worry about the performance of `TextEncoder` and `TextDecorder`, especially if we get more reliant upon them for dealing with `[ubyte]` arrays to strings in the runtime.  The [author has halted development on it and is no longer maintaining it](https://github.com/inexorabletash/text-encoding).  It also focused very heavily on spec compliance, versus any sort of performance (as per the authors notes).  As I was trawling though the bundle recently, I looked at the code.  It has a _lot_ of overhead in there.  Specifically the [`encoding_indexes`](https://github.com/inexorabletash/text-encoding/blob/master/lib/encoding-indexes.js) is a load of data injected in the global namespace to power that support.  I think this is what specifically led to the increase in snapshot size.

So I think we either need to replace it, by injecting the native implementations into the isolates somehow, or using [fast-text-encoding](https://github.com/samthor/fast-text-encoding) instead, which only supports UTF8 encoding/decoding anyways (native implementations only support alternative encodings on decode anyways).

**Comment by kitsonk** [comment]
I guess by native, I meant injecting the C++ implementation that Chromium adds. I don't know how easy/hard leveraging things like that are. I agree on the Rust, especially because it would be horrible to from a memory situation.

**Comment by ry** [comment]
It might be wildly naive but I would expect that V8 could optimize text encoder to nearly native speeds... it’s a fairly simple algorithm. The question is how well typedarray stuff gets optimized

**Comment by kevinkassimo** [comment]
(I also had some blurry memory about some AMP project member complaining that chromium TextEncoder slower in practice than some JS polyfill...)

**Comment by kitsonk** [comment]
Ok, `fast-text-encoding` has a [fatal flaw](https://github.com/samthor/fast-text-encoding/blob/master/text.js#L149-L151) when handling null padded strings (like what comes back when `deno.truncate()` is used to increase a files size).  I have raised an issue, but who knows what the maintainer will do.

I know we wanted to keep code we have to maintain down, but seeing how critical it is to communication within Deno and the parts of it we want/need are maybe 100 SLOCs, and having it done in TypeScript would make the whole thing a little bit easier to maintain and integrate as well, I think we should just build it.
