### ISSUE TITLE
Diagnostics are ignored for `for await` loops

### ISSUE THREAD

**Issue by sant123** [denoland/deno#12115]
**Describe the bug**
Using the `await` reserved word inside a normal function (without async) is not being warned by the IDE.

**To Reproduce**

1. Paste the following code:

``` ts
const listener = Deno.listen({ port: 8080 });

for await (const conn of listener) {
  handleConn(conn);
}

function handleConn(conn: Deno.Conn) {
  const httpConn = Deno.serveHttp(conn);
  for await (const event of httpConn) {
    event.respondWith(new Response("html", { status: 200 }));
  }
}
```

2. Note there is no warning in using `await` in a normal function

**Expected behavior**

Show an error in the editor saying `await` is only permitted inside async functions

**Screenshots**

Running the code with `deno run --allow-net mod.ts` fails:

![image](https://user-images.githubusercontent.com/7959437/133729975-7eebe6a5-dd35-49e8-96b1-94a4e688b5a0.png)

**Versions**

vscode: 1.60.1 deno: 1.14.0 extension: 3.9.1

**Comment by kitsonk** [comment]
At one point, we had issues with TypeScript allowing for await loops due to TypeScript bugs.  Those bugs were addressed but we still ignored those diagnostics.  We should remove those diagnostics from the ignored diagnostics.

**Comment by sant123** [comment]
> At one point, we had issues with TypeScript allowing for await loops due to TypeScript bugs. Those bugs were addressed but we still ignored those diagnostics. We should remove those diagnostics from the ignored diagnostics.

Thank you !!!
