### ISSUE TITLE
Redirecting outputs Ansi escape sequences.

### ISSUE THREAD

**Issue by rapan931** [denoland/deno#12124]
## reproduced
``` shell
deno eval "console.log(12345)" > test.txt
```

## expected
test.txt: `12345`

## actual
test.txt: `[33m12345[39m`

![image](https://user-images.githubusercontent.com/24415677/133808105-d1a24aea-1d53-4854-b992-de245993e0bc.png)

## my env
Windows 10

C:\path\to\file>deno --version
deno 1.14.0 (release, x86_64-pc-windows-msvc)
v8 9.4.146.15
typescript 4.4.2

## others 
I know that set NO_COLOR to not output Ansi Escape Sequences, but other commands such as `git` and `node` don't output Ansi Escape Sequences on redirection without any setting, so I would like deno to support this if possible.

Thanks for the project.

**Comment by nicolo-ribaudo** [comment]
This does not happen anymore in 1.39.0 (tested on macos)
