### ISSUE TITLE
Long path Deno.writeTextFile NotFound

### ISSUE THREAD

**Issue by rabbitkiller-dev** [denoland/deno#12120]
``` ts
import {
  emptyDir,
  emptyDirSync,
  walkSync,
  ensureDir,
  ensureDirSync,
  copy,
  exists
} from "https://deno.land/std@0.107.0/fs/mod.ts";
import * as path from "https://deno.land/std@0.107.0/path/mod.ts";
async function run(){
  const filePath = 'projects/base/generateCodeTemplate/server/default-server-{projectCode}-client/src/main/java/{basePackage}/{autoModule}/{projectCode}/{moduleCode}/client/hystrix/Java_DtoFallBackFactory$${FNP}{FNS}{FS}.ftl';
  const dirPath = path.dirname(filePath);
  await emptyDir(dirPath);
  const exist = await exists(dirPath)
  console.log('dirPath', dirPath)
  console.log('exist: ', exist);
  await Deno.writeTextFile(filePath, 'test');
  console.log('success');
}
run();
```

![image](https://user-images.githubusercontent.com/28952169/133777820-9c3d8d3d-a54e-4061-bc65-21e9fd66c1fc.png)

--- 
deno 1.14.0 (release, x86_64-pc-windows-msvc)
v8 9.4.146.15
typescript 4.4.2

**Comment by kitsonk** [comment]
@dsherret do you think we are running into the 260 char windows file path limit here?

**Comment by rabbitkiller-dev** [comment]
> @dsherret do you think we are running into the 260 char windows file path limit here?
Don't think
![image](https://user-images.githubusercontent.com/28952169/133886365-81baa2e7-ecb6-4744-82a8-8b2991625979.png)
Manual can create
![image](https://user-images.githubusercontent.com/28952169/133886398-33ca1bac-e1c9-4962-8d34-1e5d1251eb59.png)

**Comment by rabbitkiller-dev** [comment]
'C:\Users\24324\Desktop\workspace\flydiy\lego\flyfront-vue-core\projects\base\generateCodeTemplate\server\default-server-{projectCode}-client\src\main\java\{basePackage}\{autoModule}\{projectCode}\{moduleCode}\client\hystrix\Java_DtoFallBackFactory$${FNP}{FNS}{FS}.ftl'.length

![image](https://user-images.githubusercontent.com/28952169/133886475-2bb454f1-ba37-4466-b900-ed9bac1a977a.png)

**Comment by rabbitkiller-dev** [comment]
> @dsherret do you think we are running into the 260 char windows file path limit here?

There may be a problem with my path

```
'C:\\Users\\24324\\Desktop\\workspace\\flydiy\\lego\\flyfront-vue-core\\projects\\base\\generateCodeTemplate\\server\\default-server-{projectCode}-client\\src\\main\\java\\{basePackage}\\{autoModule}\\{projectCode}\\{moduleCode}\\client\\hystrix\\Java_DtoFallBackFactory$${FNP}{FNS}{FS}.ftl'
```

**Comment by lucacasonato** [comment]
@littledivy confirmed this is now working on Windows.
