### ISSUE TITLE
Port tools/unit_tests.py to deno

### ISSUE THREAD

**Issue by ry** [denoland/deno#1213]
`tools/unit_tests.py` was written in Python in order to launch subprocesses. (It needs to run the unit tests with various command-line flags.) However, now that Deno has support for running subprocesses via `deno.run()` ( https://deno.land/typedoc/index.html#run ) we can do all of this in JavaScript.

This is relatively easy but it may require some back-and-forth as we try to work out this new API.

**Comment by DanSnow** [comment]
May I take this one

**Comment by bartlomieju** [comment]
Can we close this one with #2294 landed?
