### ISSUE TITLE
`deno cache` and `deno run` doesn't detect type errors in `.js` files with `// @ts-check`

### ISSUE THREAD

**Issue by jaydenseric** [denoland/deno#12143]
The `deno cache` and `deno run` commands don't detect type errors in `.js` files with `// @ts-check`.

In `demo.ts`:

```ts
new URL(true);
```

The Deno LSP correctly shows the type error:

<img width="696" alt="Screen Shot 2021-09-20 at 11 49 29 am" src="https://user-images.githubusercontent.com/1754873/133950905-2a3169fe-e85d-48fd-b4c5-700bd796ea6f.png">

Run `deno cache demo.ts`, and the exit code is correctly `1` with this output:

```
Check file:///[redacted]/demo.ts
error: TS2345 [ERROR]: Argument of type 'boolean' is not assignable to parameter of type 'string'.
new URL(true);
        ~~~~
    at file:///[redacted]/demo.ts:1:9
```

But in `demo.js`:

```js
// @ts-check
new URL(true);
```

The Deno LSP correctly shows the type error:

<img width="686" alt="Screen Shot 2021-09-20 at 11 51 53 am" src="https://user-images.githubusercontent.com/1754873/133950919-e4245b74-c990-4615-92dd-195db85c0b1e.png">

And run `deno cache demo.js`, there is incorrectly no error exit code or output.

`deno run demo.js` does have a `1` exit code but that's because of the expected runtime error, and not the type error:

```
error: Uncaught TypeError: Invalid URL
new URL(true);
^
    at deno:core/01_core.js:106:46
    at unwrapOpResult (deno:core/01_core.js:126:13)
    at Object.opSync (deno:core/01_core.js:140:12)
    at opUrlParse (deno:ext/url/00_url.js:48:27)
    at new URL (deno:ext/url/00_url.js:324:20)
    at file:///[redacted]/demo.js:2:1
```

`deno cache --help` shows a `--no-check` option, that implies that type checking should be performed if you don't explicitly skip it via the flag:

```
        --no-check                    
            Skip type checking modules
```

This `deno cache` bug makes it impossible to type check `.js` files via the CLI (without running them, which would be bad), see:

https://github.com/denoland/deno/discussions/12113#discussioncomment-1346612

**Comment by kitsonk** [comment]
If the root specifier is `.js` and there are no other TypeScript files in the dependency graph, we don't attempt to type check the graph.
