### ISSUE TITLE
Allow `deno test --doc` to ignore single lines of code or change its behavior to match `deno test`

### ISSUE THREAD

**Issue by GJZwiers** [denoland/deno#12141]
Right now `deno test --doc`  errors and stops further checking when a code example imports a local file, including some of the examples in the Deno manual. For example, there's some code from `examples/module_metadata.md` that starts with:

```ts
import { outputB } from "./module_b.ts";
```

This causes `deno test --doc` to error because the imported file doesn't really exist (it's just an example file name):
```
error: Cannot resolve module "file:///path/to/my/dir/manual/examples/module_b.ts" from "file:///path/to/my/dir/manual/examples/module_metadata.md$37-56.ts".
```
 Although it's possible to ignore type checking a code block by adding `ts, ignore`, it would be nice to also have an option to ignore a single line, perhaps with some kind of annotation similar to `deno-lint-ignore` like `deno-doc-ignore`, although I don't know if that's straightforward to implement

Alternatively, because the real problem is that type checking stops in these cases, is that `deno test --doc` checks all code examples in the Markdown by default instead of stopping after the first error. Right now `deno test --doc` runs with a sort of implicit `--fail-fast` mode, whereas in `deno test` that option has to be passed explicitly.

**Comment by caspervonb** [comment]
Because the rest of the CLI is going opt-in for type-checking; unless someone objects like in the next 3 days I'm inverting type-checking to be opt-in (https://github.com/denoland/deno/pull/11782):

~~~
```ts check
import "./foo_bar.ts";
```
~~~

> . Right now deno test --doc runs with a sort of implicit --fail-fast mode, whereas in deno test that option has to be passed explicitly.

Yeah type-checking is considered a fatal error; so it doesn't count as a failure.
We should probably address this in the new incoming check command (#11786).

**Comment by bartlomieju** [comment]
I'm skeptical about this solution. Ignoring a single file will require some heavy lifting and all it will do is marking import as `any` type which will trip up type checking anyway. I think this might be a limitation of the doc testing feature.

**Comment by GJZwiers** [comment]
That's okay, I wasn't even sure if this could even be implemented at all
