### ISSUE TITLE
Deno.permission.revoke() doesn't do anything unless allow list was provided in a flag

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#12153]
When writing a unit test using `permissions` setting object and specifying bool switch it turns out `Deno.permissions.revoke()` doesn't do anything:

```ts
unitTest(
  { perms: { read: true, write: true } },
  async function symlinkPermissionDeniedOnMissingSourceWrite() {
    const testDir = Deno.makeTempDirSync();
    const oldname = testDir + "/oldname";
    const newname = testDir + "/newname";
    Deno.mkdirSync(oldname);
    await Deno.permissions.revoke({ name: "write", path: oldname });
    await assertRejects(async () => {
      await Deno.symlink(oldname, newname);
    }, Deno.errors.PermissionDenied);
  },
);
```

In above case `assertRejects` fails. 

Looking through source code for `Deno.permissions.revoke()` API I found:
https://github.com/denoland/deno/blob/269bf380e0fb2e532e7340c4ba64d4eaa4d5d45e/runtime/permissions.rs#L404-L417

So permission is only removed from `granted_list`, but it's not added to the `denied_list`. I believe this is a bug and should be fixed.

CC @ry

**Comment by kitsonk** [comment]
While the web platform has abandoned this API, it doesn't deny something, it sets it back to its default: https://developer.mozilla.org/en-US/docs/Web/API/Permissions/revoke

This means it can be re-granted again. We have followed the semantics of the web platform here.

**Comment by kitsonk** [comment]
If anything we should consider a `.deny()` method. To me `.revoke()` means to take back something that was previously granted, which is what the API does do.

**Comment by bartlomieju** [comment]
> If anything we should consider a `.deny()` method. To me `.revoke()` means to take back something that was previously granted, which is what the API does do.

That was my feeling as well, but it looks like @nayeemrmn came up with a viable solution in #12159

**Comment by kitsonk** [comment]
As long as revoked permissions can be re-prompted for. The title of the PR isn't clear on that.

**Comment by kt3k** [comment]
> While the web platform has abandoned this API, it doesn't deny something, it sets it back to its default: https://developer.mozilla.org/en-US/docs/Web/API/Permissions/revoke

If it's no longer a part of web platform, does it make sense to keep this API in Deno?

I think I haven't seen any use case of this API in the ecosystem yet..

**Comment by nayeemrmn** [comment]
> > While the web platform has abandoned this API, it doesn't deny something, it sets it back to its default: https://developer.mozilla.org/en-US/docs/Web/API/Permissions/revoke
> 
> If it's no longer a part of web platform, does it make sense to keep this API in Deno?
> 
> I think I haven't seen any use case of this API in the ecosystem yet..

Well `request()` is in the same circumstance. At some point those APIs were moved out of the now fully standardised https://github.com/w3c/permissions to https://github.com/WICG/permissions-request and https://github.com/WICG/permissions-revoke. Not formally abandoned... but last updated 2 years ago. However this is one of the two reasons we placed our permission API in the `Deno` namespace.

> As long as revoked permissions can be re-prompted for. The title of the PR isn't clear on that.

Yes `revoke()` would still by `granted` -> `prompt`, but more dependable and aligned with expectations.
