### ISSUE TITLE
Support comments in JSON like import-maps (JSON5)

### ISSUE THREAD

**Issue by CanRau** [denoland/deno#12161]
Would love to be able to include comments in JSON files without the need for hacky and sometimes warnings producing `tricks` to include `// todo:` or other comments in for example my `import_map.json`

Hacky Example

```json
{
  "//": "https://github.com/WICG/import-maps#the-import-map",
  "imports": {
    "//": "Another Comment",
  },
  "// scopes": "https://deno.land/manual@v1.12.2/npm_nodejs/import_maps#overriding-imports",
  "scopes": {}
}
```

hacky is I have to make sure it's valid JSON which includes don't repeating keys etc and editor shortcuts to toggle comments won't work

Example error
```json
Import map diagnostics:
  - Invalid top-level key "//". Only "imports" and "scopes" can be present.
```

**Comment by satyarohith** [comment]
Maybe we can support the `jsonc` extension for import maps. But I'm unsure if the spec requires us to end the import map file with the `json` extension.

cc @kitsonk

**Comment by CanRau** [comment]
Thanks for looking into this 😊
Also, not sure about the current state, but would suggest the same for `Deno.json` (if it doesn't support comments yet)

**Comment by satyarohith** [comment]
> Also, not sure about the current state, but would suggest the same for `Deno.json` (if it doesn't support comments yet)

It supports both `json` & `jsonc`: https://deno.land/manual@v1.14.0/getting_started/configuration_file

**Comment by kitsonk** [comment]
The standard doesn't support it, so I am not keen on adding support.

As stated, `deno.json` and `deno.jsonc` will always parse as JSONC and supporting import maps in there would then permit it, without a direct expectation of being compatible with the spec.

**Comment by CanRau** [comment]
Hm yeah I get the spec compatibility (though it's a bummer we haven't already moved JSON to support comments "everywhere")

It's kinda confusing that `tsconfig.json` and `Deno.json` allow comments but `import_map.json` doesn't
Though I also understand that tsc is different tooling which, as I understand, handles `tsconfig.json` parsing

Just some thoughts I wanted to share as it keeps frustrating me in all JSON files 😅
Feel free to close

**Comment by bartlomieju** [comment]
> The standard doesn't support it, so I am not keen on adding support.

I agree, this will break compatibility with web browsers, which wouldn't be enable to read JSONC/JSON5 import maps.

**Comment by CanRau** [comment]
Sad but I get it. Thanks for sharing your thoughts.
So it would be necesseray to convince the web first, like the [import-map repo](https://github.com/WICG/import-maps), I guess.
So closing here ☺️
