### ISSUE TITLE
Duplicated Resolvers

### ISSUE THREAD

**Issue by ry** [denoland/deno#12162]
There are many different implementations of essentially the same module resolution algorithm in our system. They all do the same, but are used in different situations.

1. `CliModuleLoader::resolve` [link]( https://github.com/denoland/deno/blob/923c5432e06aec6ec705304b818bba21c2b497d8/cli/module_loader.rs#L70-L95
)
Used with `run --no-check` and probably also for pure JS.

1. `deno::tsc::op_resolve` [link](https://github.com/denoland/deno/blob/923c5432e06aec6ec705304b818bba21c2b497d8/cli/tsc.rs#L408-L474)
Used with type checking. Calls `deno::graph::Graph::resolve`

1. `deno::lsp::tsc::op_resolve` [link](https://github.com/denoland/deno/blob/923c5432e06aec6ec705304b818bba21c2b497d8/cli/lsp/tsc.rs#L2273-L2364)
Special resolver for LSP. Does not call `deno::graph::Graph::resolve`.

1. `deno_graph::source::Resolver::resolve` [link](https://github.com/denoland/deno_graph/blob/865f03c8312c470d79059224081a98a7cf37438b/src/source.rs#L83-L93)
Trait for resolving modules, similar to `deno_core::ModuleLoader::resolve`

1. `eszip::resolve_import::resolve_import`   [link](https://github.com/denoland/eszip/blob/a01f0932dadb08fd357594cce0687c279385a101/src/resolve_import.rs#L7-L54)
used just for eszip

1. `deno_core::ModuleLoader::resolve` [link](https://github.com/denoland/deno/blob/923c5432e06aec6ec705304b818bba21c2b497d8/core/modules.rs#L65-L78)

(Feel free to add to this list if you find more)

**Comment by ry** [comment]
@bartlomieju `deno_core::ModuleLoader` seems quite similar to [`deno_graph::source::Resolver`](https://docs.rs/deno_graph/0.5.0/deno_graph/source/trait.Resolver.html) perhaps `deno_core` could actually use the `deno_graph` trait?

**Comment by bartlomieju** [comment]
> @bartlomieju `deno_core::ModuleLoader` seems quite similar to [`deno_graph::source::Resolver`](https://docs.rs/deno_graph/0.5.0/deno_graph/source/trait.Resolver.html) perhaps `deno_core` could actually use the `deno_graph` trait?

This seems like a bad idea - `deno_core` would have to depend on `deno_graph` and the goal is to keep it lean. IMO module loading is such crucial part of the whole pipeline that `deno_core` should be left as is, without adding dependencies, and keeping it as close to the spec as possible.

**Comment by bartlomieju** [comment]
Is there anything actionable in this issue?
