### ISSUE TITLE
`deno test --doc` doesn't detect errors in Markdown files with CRLF line endings

### ISSUE THREAD

**Issue by GJZwiers** [denoland/deno#12187]
When I make a new `.md` file with some code that should throw a type error:

\```ts
let str: string = 1;
\```

If the file has CRLF line endings, running `deno test --doc` will not detect any problems.

Switching to LF works properly and throws the expected error:
```
error: TS2322 [ERROR]: Type 'number' is not assignable to type 'string'.
```
Deno 1.14.0

**Comment by caspervonb** [comment]
Will fix.
