### ISSUE TITLE
wanted: path manipulation library

### ISSUE THREAD

**Issue by ry** [denoland/deno#1220]
* should be done in your own repo
* add link https://github.com/denoland/registry/blob/master/x/database.json
* have tests - see this as an example https://github.com/denoland/deno_examples/blob/master/.travis.yml

probably best to just start with this file: https://github.com/nodejs/node/blob/master/lib/path.js

or maybe this https://github.com/browserify/path-browserify/blob/master/index.js

**Comment by kitsonk** [comment]
I would also say it needs to be authored in TypeScript.

**Comment by steambap** [comment]
If nobody took this, I'll take this issue.

**Comment by zhmushan** [comment]
give it to me
https://github.com/zhmushan/deno_path

**Comment by ry** [comment]
@zhmushan has been allocated `https://deno.land/x/path` 
Thanks!
