### ISSUE TITLE
Deno fmt for yml files

### ISSUE THREAD

**Issue by razzeee** [denoland/deno#12217]
Would that be something worth considering?

**Comment by bartlomieju** [comment]
CC @dsherret what's the complexity of potential solution? Does dprint provide Rust implementation of YAML formatter?

**Comment by dsherret** [comment]
It would be a lot of work. I don't see a yaml parser for rust that supports parsing comments and getting spans/ranges of the text.

**Comment by razzeee** [comment]
Wouldn't https://github.com/ikatyang/tree-sitter-yaml work?

**Comment by razzeee** [comment]
Agreed, it's fairly simple to let tree-sitter build rust bindings from that (with the latest tree-sitter-cli version). And I have scripts for automatically releasing that to crates.io, but that should be done upstream, so I've opened an issue there.

**Comment by jimisaacs** [comment]
Would love this, it's literally the only reason I still have a `.prettierrc.yml` file in my projects.

**Comment by dsherret** [comment]
It looks like deno could use https://github.com/g-plane/pretty_yaml for this.
