### ISSUE TITLE
u64 result type is not working as expected in ffi/dlopen

### ISSUE THREAD

**Issue by cztomsik** [denoland/deno#12212]
if you return `u64::MAX` from rust and then use `dlopen()` with `{ ..., result: u64 }` you will get a different value in JS.

It does exactly the same thing if you input it to a `deno` console but that's probably unrelated:

```
Deno 1.14.0
exit using ctrl+d or close()
> 18446744073709551615
18446744073709552000
> 
```

Maybe this is expected behavior but it should be at least documented and I would say it's not terribly useful then for native plugins. Maybe it should return `BigInt` instead?

rust example:
```
#[no_mangle]
pub extern "C" fn test_u64() -> u64 {
    u64::MAX
}
```

deno
```
const lib = Deno.dlopen(libFile, {
    test_u64: { parameters: [], result: 'u64' }
}
lib.symbols.test_u64() // should return u64::MAX, probably as BigInt but it doesnt
```

**Comment by kevinkassimo** [comment]
The internal serdes library `serde_v8` forwards all f32/f64/u64 to f64 (normal JS numbers). Opened an issue there: https://github.com/denoland/serde_v8/issues/43

**Comment by irbull** [comment]
> The internal serdes library `serde_v8` forwards all f32/f64/u64 to f64 (normal JS numbers). Opened an issue there: [denoland/serde_v8#43](https://github.com/denoland/serde_v8/issues/43)

It looks like that repository has been archived. There is some good discussion on that thread about opaque pointers. Should that discussion be moved here?

**Comment by lucacasonato** [comment]
This is now fixed.
