### ISSUE TITLE
`File` and `Deno.File` are confusingly similarly named

### ISSUE THREAD

**Issue by rotu** [denoland/deno#12229]
The classes [`File`](https://doc.deno.land/builtin/stable#File) and [`Deno.File`](https://doc.deno.land/builtin/stable#Deno.File) have confusingly similar names but represent two different things.

It would be nice if these were either renamed apart (e.g. `Deno.File` -> `FileHandle`) and/or if the documentation made an effort to distinguish the two (e.g. explaining that `Deno.File` represents a persistent and possibly mutable on-disk resource, whereas `File` is a read-only representation of the *contents* of a file, possibly with its associated MIME type.

**Comment by bartlomieju** [comment]
`Deno.File` was deprecated in v1.19 and instead we introduced `Deno.FsFile` (https://deno.com/blog/v1.19#denofile-has-been-renamed-to-denofsfile). 

I considered this now solved, even though `Deno.File` will still be available until Deno 2.0 (in undefined future).
