### ISSUE TITLE
console.* methods do not properly detect non-tty output and still add colors to output

### ISSUE THREAD

**Issue by midnightnoon** [denoland/deno#12224]
Commands such as `console.dir` still add ANSI color styles to its output of numbers/undefined/null  when the output is redirected to a file.

```
> deno eval "console.dir({some:4, thing:null})" >test.txt
```
The resultant file will contain the ANSI color codes.
```
{ some: [33m4[39m, thing: [1mnull[22m }
```

 Ideally those methods would perform a similar check to `Deno.isatty(Deno.stdout.rid)` and `Deno.isatty(Deno.stderr.rid)` and not add styles when appropriate.

**Comment by bartlomieju** [comment]
For anyone interested in fixing this issue, here are some hints how to do it:
- use `atty` crate to check is output is being piped: `atty::is(atty::Stream::Stdout)`
- based on the result on that enable/disable colors in `main` function in `cli/main.rs` module
- add a new "lazy static" to `runtime/colors.rs` like `IS_TTY`
- add a new function to `runtime/colors.rs` that should be called in `main` function to check if we're using TTY

**Comment by VishnuJin** [comment]
I'd like to work on this issue, could you please assign it to me !!

**Comment by bartlomieju** [comment]
@VishnuJin great, let me know if you have any questions.

**Comment by bartlomieju** [comment]
This was reverted in https://github.com/denoland/deno/pull/13054.

**Comment by VishnuJin** [comment]
@bartlomieju is this issue still relevant ?

**Comment by crowlKats** [comment]
Yes, as running the provided example still results in a file with colors

**Comment by canac** [comment]
This is causing issues for me also when piping my Deno scripts to files and using command substitution because the output includes the color codes.
