### ISSUE TITLE
Add web worker API

### ISSUE THREAD

**Issue by ry** [denoland/deno#1222]
can be copied mostly copied from here: https://cs.chromium.org/chromium/src/v8/src/d8.cc?l=1819&rcl=500be6dd6ec690aebae921e8a97d17f8055de017

**Comment by romandev** [comment]
I'll take this issue.

**Comment by bartlomieju** [comment]
@romandev are you working on this issue or may I take over?

**Comment by romandev** [comment]
@bartlomieju Okay, could you please take this issue over? I can't start on this work for now..

**Comment by bartlomieju** [comment]
Workers have landed with #1460

**Comment by ry** [comment]
Not really. We have most of the internal plumbing now but you cannot actually do `new Worker("foo.js")`...  I will try to surface this soon.

**Comment by afinch7** [comment]
Working on this one right now. Maybe we can close this out in the next week.

**Comment by ry** [comment]
Closed by #1993
