### ISSUE TITLE
LSP big_file_edits performance regression

### ISSUE THREAD

**Issue by ry** [denoland/deno#12246]
<img width="770" alt="Screen Shot 2021-09-27 at 9 01 38 AM" src="https://user-images.githubusercontent.com/80/134913324-967b40d5-cde3-4543-92c2-bc1f42e2a426.png">

It seems this happened in https://github.com/denoland/deno/commit/728d205d9d2551a356a022b6b083bcdcf081f3bf

cc @kitsonk @dsherret @jeanp413

**Comment by kitsonk** [comment]
In #11555 we added a significant feature, with especially big files, requires additional calls into tsc to see what code actions are applicable, so we cannot totally offset the impact of this.  #12535 did improve some of the performance regression (and improved a baseline not related to just code actions in big files):

<img width="715" alt="Benchmarks__4717___5216_" src="https://user-images.githubusercontent.com/1282577/140627668-a81f7f67-4c42-4f47-bdfa-4433e76914f1.png">

The biggest opportunity for performance improvement now is to not use tsc to calculate the "NavigationTree" but instead calculate this in swc.  The navigation tree is essentially a simplified AST which is used by vscode in several situations (like syntax highlighting) and is "costly" for tsc to generate (as well as it being a large JSON structure we have to op out of the tsc isolate).  This is covered by #11032.

I am going to close this, and we can figure out the priority for #11032.
