### ISSUE TITLE
`URLPattern` doesn't match if URL ends with `/`

### ISSUE THREAD

**Issue by ebebbington** [denoland/deno#12259]
See the below example:

```ts
const url = "http://localhost/coffee/2/"
const path = "/coffee/:id"
const pattern = new URLPattern({ path })
pattern.exec(url) // null
```

I believe it should match in this case, and could be a huge downfall for the usabillity of this 'new' API

Though in some cases, i think it does match when the url ends with `/`, so i think it might be quite flaky?

**Comment by lucacasonato** [comment]
This is intentional spec behaviour: https://github.com/WICG/urlpattern/issues/14.

If you want to match trailing slashes, add a `{/}?` to the end of your pattern.

**Comment by lucacasonato** [comment]
Opened an issue on MDN to clarify this in docs: https://github.com/mdn/content/issues/9327
