### ISSUE TITLE
Any usage OS signals API errors out

### ISSUE THREAD

**Issue by ozanmuyes** [denoland/deno#12252]
OS: macOS Version 11.5.1
```shell
> deno --version
deno 1.14.1 (release, x86_64-apple-darwin)
v8 9.4.146.15
typescript 4.4.2
```

I know the API behind `--unstable` flag but still... none of the examples at the [relevant documentation page](https://deno.land/manual@v1.14.1/examples/os_signals) works - even though the [changes to the API](https://deno.com/blog/v1.14#changes-to-os-signals-apis).

```typescript
// main.ts

for await (const _ of Deno.signal("SIGINT")) {
  console.log("interrupted");
}
```

```shell
> deno run --unstable main.ts
Check file:///path/to/main.ts
Watching SIGINT signals
error: Module evaluation is still pending but there are no pending ops or dynamic imports. This situation is often caused by unresolved promise.
```

**Comment by AaronO** [comment]
This is because this should be an "unref" op but unref ops have been unused for a while (even before the op-layer refactor IIRC)

**Comment by lucacasonato** [comment]
1.16.0 introduced a new signal API that does not have this issue anymore.
