### ISSUE TITLE
deno bundle and Web Worker location

### ISSUE THREAD

**Issue by juliangruber** [denoland/deno#12276]
I'm using `deno bundle` to create a production build of my application (which uses Web Workers), however am facing an issue when trying to execute the bundle on a different machine, where the bundle and Web Worker scripts are in different locations.

Inspecting the bundle, this is the problematic output:

```js
const importMeta1 = {
    url: "file:///srv/current/api2/bin/deno-worker/evaluate.ts",
    main: false
};
...
const workerHref = new URL("web-worker.js", importMeta1.url).href;
```

The source is as advised in https://deno.land/manual/runtime/workers:

```ts
const workerHref = new URL("web-worker.js", import.meta.url).href
```

Is this a supported use case? Or is `deno bundle` expected to be run on the machine that will execute the code?

Or is there a portable way to specify a relative source location?

**Comment by juliangruber** [comment]
Looks like it would also be possible to inline the worker source into the script: https://stackoverflow.com/a/19201292

**Comment by nayeemrmn** [comment]
This is intentional. When you bundle, the `import.meta` expressions are all hardcoded to their source-derived values.

See if the following works for your use case:
```ts
const workerHref = new URL("web-worker.js", Deno.mainModule).href
```

**Comment by juliangruber** [comment]
Thanks for your help!

**Comment by nayeemrmn** [comment]
> ```ts
> const workerHref = new URL("web-worker.js", Deno.mainModule).href
> ```
> Unfortunately this also creates an absolute path:
> ```js
> const importMeta1 = {
>     url: "file:///opt/actions-runner/.../evaluate.ts",
>     main: false
> }; 
> ```

I'm not sure what this means. The solution doesn't use `import.meta`, where did you get this output?

**Comment by juliangruber** [comment]
```bash
$ cat deno.js
console.log([Deno.mainModule, import.meta.url])

$ deno bundle deno.js > out.js
Bundle file:///Users/julian/Desktop/deno.js

$ cat out.js
const importMeta = {
    url: "file:///Users/julian/Desktop/deno.js",
    main: import.meta.main
};
console.log([
    Deno.mainModule,
    importMeta.url
]);
```

You're right that `Deno.mainModule` doesn't get converted to an absolute path, sorry about that that must have been an error on my side.
