### ISSUE TITLE
Error type is in deno.ns but not dom

### ISSUE THREAD

**Issue by Timmmm** [denoland/deno#12271]
If you are writing an app that targets *just the web* then you might have:

    lib: ["dom"]

in your config. However if you then try to write this code:

    throw new Error("foo");

Then Deno will say that `Error` is not a known type. If you add `"deno.ns"` to `lib` then it resolves the issue. But shouldn't `Error` be in `"dom"`? Actually isn't `Error` built in? Shouldn't it be found even with `lib: []`?

**Comment by kitsonk** [comment]
When you supply a `lib` argument, just like with `tsc` it overrides _all_ libraries, so you need to include something else that brings in the other defaults.  If you don't want to use any Deno specific APIs, you should use `["dom", "dom.iterables", "esnext"]` or whatever is appropriate for what you are targeting.

**Comment by Timmmm** [comment]
Ah you know I did have esnext in there from a while ago but I took it out because the Deno documentation doesn't list it as a valid value. You might want to update the docs.

**Comment by kitsonk** [comment]
The part of the manual you are referring to (https://deno.land/manual@v1.11.3/typescript/configuration#using-the-quotlibquot-property) is not an exhaustive list.  It points out a) additional libraries supported by Deno and b) additional libraries of use when trying to target other platforms in addition to Deno, and then provides an example of how to get Deno code to work, which clearly includes `"dom"` and `"deno.ns"` (which includes `"esnext"`).

I am sure a PR would be accepted if you feel it could be made more clear.
