### ISSUE TITLE
Bundeling results in missing initializer in const declaration

### ISSUE THREAD

**Issue by wrnrlr** [denoland/deno#12272]
When bundling `three.js` when using `mode=types/index.d.ts` on the CDN deno produces `const` variables that are not initialised.

```js
const DEG2RAD;
const RAD2DEG;
...
```

Minimum viable failure in [const-error.zip](https://github.com/denoland/deno/files/7254941/const-error.zip)

BTW, the RAD2DEG and DEG2RAD are in MathUtils:
https://github.com/mrdoob/three.js/blob/dev/src/math/MathUtils.js

**Comment by kitsonk** [comment]
Can you provide a more complete reproduction, including the script you use as the entry point, what you are using on the command line and the version of Deno you are using?

**Comment by wrnrlr** [comment]
cmd line in `readme.md`:

```
deno bundle --unstable --watch --config ./deno.json app.js bundle.js

deno run --allow-net --allow-read server.js
```

entry point is in index.html, it's just `import three from './bundle.js'`


 im using deno v1.14.2

**Comment by kitsonk** [comment]
The entry point, meaning, provide the code in `app.js` (as well as your `./deno.json`).

**Comment by wrnrlr** [comment]
All of this is in the zip:

deno.json:
```
{
  "compilerOptions": {
    "target": "es2020",
    "lib": [
      "dom",
      "dom.iterable",
      "dom.asynciterable",
      "deno.ns"
    ]
  }
}
```

app.js:
```
export * as three from 'https://cdn.skypack.dev/-/three@v0.132.2-1edwuDlviJO0abBvWgKd/dist=es2020,mode=types/index.d.ts'

```
