### ISSUE TITLE
Control Deno.exit with Worker permissions

### ISSUE THREAD

**Issue by irbull** [denoland/deno#12280]
If a Worker has access to the `Deno` namespace, then it can call `Deno.exit` and bring down the entire runtime. There are already permissions for network and file access, controlling access to `exit` should be considered too. Ideally, you may want to run potentially unsafe code in a controlled worker, and not have that code call `Deno.exit`.

**Comment by bartlomieju** [comment]
I suggest to remove `Deno.exit()` in such case. Workers permissions has identical interface to main process permissions and we should strive to keep it that way.

**Comment by lucacasonato** [comment]
We could consider just disallowing `Deno.exit` from a worker. The web has some APIs which can only be used from the main thread (`window.open` and `window.close` for example). I think it would be reasonable for us to say, you can only exit the process from the main thread.

**Comment by irbull** [comment]
Disallowing `Deno.exit` may make sense. I handled this by starting a wrapper that redefines `Deno.exit`:
```
Deno.exit = (_status) => {};
```
I then load the worker code from there.

**Comment by cjihrig** [comment]
I think this can be closed given that https://github.com/denoland/deno/pull/14826 recently landed.
