### ISSUE TITLE
Deno v1.14: readFileSync returns an Uint8Array whose underlying buffer is null-terminated

### ISSUE THREAD

**Issue by elisee** [denoland/deno#12298]
Hi! 

The underlying `ArrayBuffer` of the `Uint8Array` returned by `Deno.readFileSync()` is null-terminated in v1.14 but wasn't in v1.13.
Since this change just caused a bug in my project, I was wondering if this is an expected change (and I need to update my code) or whether it should be fixed in Deno?

```typescript
const content = Deno.readFileSync("test.txt");
console.log(content.length, content.buffer.byteLength, content.length === content.buffer.byteLength);
```

`test.txt` can be just the letter `a` for instance.

In Deno v1.13, this prints: `1 1 true` (buffer contains `"a"`)
In Deno v1.14, it now prints: `1 2 false` (buffer contains `"a\0"`)

**Comment by autoxbc** [comment]
It looks like we have the same problem. The version where the bug first appeared was **1.14.1**, and everything is normal in **1.14.0**

When I tried to use @swc/wasm-web to create a transcoding server, an exception occurred when importing the wasm file 
> error: Uncaught (in promise) CompileError: WebAssembly.instantiateStreaming(): unexpected end of stream @+17187927

I was not sure whether it was a deno or swc bug before, now I’m sure it’s a deno problem, both Deno.readFile and Deno.readFileSync are affected.

**Comment by bnoordhuis** [comment]
#12057 is the change that's responsible but I wouldn't call it a bug. The only guarantee is that the `Uint8Array` is a sub-view of its backing ArrayBuffer, not that they're a 1-to-1 match.

**Comment by autoxbc** [comment]
> The only guarantee is that the `Uint8Array` is a sub-view of its backing ArrayBuffer, not that they're a 1-to-1 match.
```js
const buffer = new ArrayBuffer(42);
const uint8 = new Uint8Array(buffer);
console.log( uint8.length , buffer.byteLength );
//  42  42  true
```
They are 1-to-1 match, the problem is only in Deno.readFile and Deno.readFileSync.

**Comment by elisee** [comment]
> #12057 is the change that's responsible but I wouldn't call it a bug. The only guarantee is that the `Uint8Array` is a sub-view of its backing ArrayBuffer, not that they're a 1-to-1 match.

Right, I updated my own code to work with the Uint8Array itself (and handle the offset & length as needed) instead of grabbing the underlying ArrayBuffer and assuming it can be used in full.

Feel free to close if you consider the previous behavior an implementation detail that apps shouldn't rely on, seems fair enough to me.

**Comment by andreubotella** [comment]
> `@swc/wasm-web` uses `fetch()` to import the wasm module, so I have to construct a `URL` to complete the initialization, in this way: Uint8Array => ArrayBuffer => Blob => URL, unable to bypass `ArrayBuffer`.

`@swc/wasm-web` uses `fetch()` if the input to `init()` is a string, a `URL` or a `Request` – but it seems like you can pass it a `Uint8Array` just fine.
