### ISSUE TITLE
deno lsp crashed when editing d.ts file

### ISSUE THREAD

**Issue by codehz** [denoland/deno#12313]
error: 
```
try_parse_ts_declare should be called after eating `declare`
```

deno version 1.14.2

sample code(updated):
```
declare | //<edit point
declare type A = 1
```

**Comment by kitsonk** [comment]
There should have been a more full stack trace in the language server output.  `try_parse_ts_declare` is a swc method and related to parsing the file.  The syntax is invalid and the formatter errors on it, but doesn't panic.

I can't re-create, though I am using an updated version of swc on my build.  Could you provide better steps to reproduce?  Like did the file already exist, what this the only thing in the file, what editor were you using?  Are you able to reliably reproduce?

**Comment by codehz** [comment]
@kitsonk 
Ok I found the reason:
```
declare | // edit point
declare type A = 1
```

Or minimal repeatable: `declare declare`

**Comment by kitsonk** [comment]
Yup, I can reproduce with `declare declare`.

Opened issue with swc.
