### ISSUE TITLE
Deno 1.14.3 compile target aarch64-apple-darwin download not found

### ISSUE THREAD

**Issue by Guergeiro** [denoland/deno#12331]
For context, only one that is not found.
https://github.com/Guergeiro/cloudflare-ddns/actions/runs/1308806495

**Comment by UltiRequiem** [comment]
Yeah, it makes my CI fail
https://github.com/UltiRequiem/y2j/runs/3806352345?check_suite_focus=true

**Comment by ry** [comment]
Is this still a problem? It works for me.

**Comment by kitsonk** [comment]
Hmmm... I ran into it several times yesterday and then it cleared, but some 13 hours ago.  I wonder if there is a cache propagation issue.

**Comment by ry** [comment]
Oops - my fault. Should be fixed now.
