### ISSUE TITLE
Deno compile cannot find file

### ISSUE THREAD

**Issue by UltiRequiem** [denoland/deno#12330]
This is working:
```bash
deno compile --allow-all  compileMe.ts
```
This is not
```bash
 deno compile --allow-all --target x86_64-pc-windows-msvc compileMe.ts
```

Error:
```
Check file:///home/justice/repos/denoc/compileMe.ts
Bundle file:///home/justice/repos/denoc/compileMe.ts
Compile file:///home/justice/repos/denoc/compileMe.ts
error: No such file or directory (os error 2)
```

And if I:

```bash
deno compile --allow-all compileMe.ts --target x86_64-pc-windows-msvc
```

It works but it completely ignore ` --target x86_64-pc-windows-msvc`.

Reference https://deno.land/manual/tools/compiler#compiling-executables

**Comment by kitsonk** [comment]
Can you provide the output of `deno --version` and the output of `deno compile -L debug --allow-all --target x86_64-pc-windows-msvc compileMe.ts`?

**Comment by UltiRequiem** [comment]
Bump

**Comment by UltiRequiem** [comment]
Not sure since when but this is working now. Thanks @kitsonk 🚀
