### ISSUE TITLE
Allow specifying path prefix for --allow-net permissions

### ISSUE THREAD

**Issue by AurelienZintzmeyer** [denoland/deno#12382]
Currently --allow-net=domain/A has the same effect as --allow-net=domain. It would be nice to be able to only allow network access to an URL with a given domain & path prefix.

**Comment by nayeemrmn** [comment]
Duplicate of #5242. I don't think it makes sense, path is just data being sent to the same entity.

**Comment by AurelienZintzmeyer** [comment]
This feature could be used to restrict module sources, for example only the scripts in https://raw.githubusercontent.com/SOME_ORGANIZATION/

**Comment by lucacasonato** [comment]
Closing as duplicate of #5242
