### ISSUE TITLE
deno(no-local): How to import local modules?

### ISSUE THREAD

**Issue by cawoodm** [denoland/deno#12380]
How *does* one import local modules? Looking at code like [this](https://github.com/asos-craigmorten/opine-http-proxy/blob/main/src/proxy.ts) it seems to be allowed so why is the Deno compiler moaning? 

![image](https://user-images.githubusercontent.com/498834/136530984-22266a6e-cd19-48c3-82fe-372810e58533.png)

At runtime all is well but either the Deno Language Server or TypeScript seems unable to comprehend the local `./types.ts`.

Interestingly, deno.exe runs the code just fine - the problem is in VSCode (1.6.1) perhaps with the Deno Extension (3.9.1).

> Unable to load a local module: "file:///Marc/work/njinz/src/types.ts".
>  Please check the file path. deno(no-local)

**Comment by kitsonk** [comment]
What is the directory listing for `/Marc/work/njinz/`?

What is the output of _View | Output_ and then selecting _Deno Language Server_ in vscode?

**Comment by fetichex** [comment]
Hello, I have the same error and I can not find information on how to fix it. No information about deno(non-local)
![image](https://user-images.githubusercontent.com/57439165/212796905-6b1319a2-cba0-437f-991c-9de80ee7603c.png)
error: Module not found "file:///C:/Users/mairu/Documents/D/TypeScript/appTask/enums".
    at file:///C:/Users/mairu/Documents/D/TypeScript/appTask/Todo.ts:1:33
