### ISSUE TITLE
import map error

### ISSUE THREAD

**Issue by Falentio** [denoland/deno#12394]
when import map use relative path for scopes, like
```json
{
    "scopes": {
        "./path": {
            "any": "https://example.com/mod.ts"
         }
    }
}
```
import map above will not work properly, any file in "./path" will got "relative import path 'any' not prefixed with / or ./ or ../ from file:///...."(seems like doesn't affected by import map)

but
```json
{
    "scopes": {
        "file://my_repo/path": {
            "any": "https://example.com/mod.ts"
         }
    }
}
```
and

```json
{
    "scopes": {
        "./": {
            "any": "https://example.com/mod.ts"
         }
    }
}
```
and
```json
{
    "scopes": {
        "../": {
            "any": "https://example.com/mod.ts"
         }
    }
}
```
will work properly

note: all example import map above are placed in the same path

**Comment by bartlomieju** [comment]
I'm having trouble understand what's the problem here. We're testing our import map implementation against WPT suite so I'm surprised this bug could have slipped by. @Falentio could you please provide full reproduction?

**Comment by Falentio** [comment]
sorry when my information not much specific,
according this https://github.com/WICG/import-maps#scope-inheritance we can use just path for scopes(not full url)
but when i try using it in deno, only "./", "../" and "/" will work
"/src" will not work

i wrote example here
https://github.com/Falentio/importmap_bug
a.json, b.json, and f.json will work for src/test.ts, but not just for src/
c and d will not affecting to src/test.ts, expected will provide only for any file in src/
e work properly for code from cdn

**Comment by bartlomieju** [comment]
@Falentio I'm still not understanding what's the problem. Could you provide a failing test case that should work?
