### ISSUE TITLE
Language server fails to load workspace-specific config (Windows, relative file path)

### ISSUE THREAD

**Issue by ondras** [denoland/deno#12398]
The LSP fails to load the config file. This happens on Windows only and with relative config file path (`../deno.json` in my case).

The attached screenshot shows:
  1) the actual error message `os error 3, cannot find the path specified`
  2) the resolved config file path, `file:///X:/home/ondras/rri/src/../deno.json`

The LSP itself works fine - it just cannot open and load the config file. My first suspect would be [to_file_path](https://github.com/denoland/deno/blob/main/cli/lsp/language_server.rs#L373) unable to deal with the *mixing-the-file-protocol-with-windows-paths* config file location.
![vscode-error](https://user-images.githubusercontent.com/192172/136834415-8cee355e-1c13-4eb6-a944-a225f97c423c.png)

**Comment by dsherret** [comment]
> Interesting! Your path looks much better: it is a windows-native path with backslashes and no file:// pseudo-protocol.

@ondras I get the file prototocol in the resolved configuration file message that looks similar to yours.

> Update: if I put an incorrect config file name, I also receive the "Could not find the config file" message. So my original config file value passes this particular check.

Oh, I see. So it passes this check, but then it fails actually loading the file probably. What does this error look like in 1.15.1 (just released today)? We started including the path in the error messages. Also, is the `X:` drive some mount or network drive?

**Comment by dsherret** [comment]
Yes, this is definitely related. I just tried this out and I'm able to reproduce it on a mapped WSL drive. Additionally, I can also reproduce with:

```
> deno run --config ../deno.json mod.ts
error: The system cannot find the path specified. (os error 3)
```

The issue is that deno is stripping windows UNC paths like `\\?\UNC\wsl$\Ubuntu\home\david\deno.json` to `UNC\wsl$\Ubuntu\home\david\deno.json`, which makes no sense. We can't always strip unc paths.

I opened #12438 to fix this.
