### ISSUE TITLE
Certain classes are never tree-shaken out

### ISSUE THREAD

**Issue by dgreensp** [denoland/deno#12400]
I'm finding that a class like this:

```
export class Foo {
  x: number;
  constructor() {
    this.x = 1;
  }
}
```

...is never removed by tree-shaking when making a bundle (I'm using `Deno.emit`).  That is, even if it is never used, it will appear in the bundle!  Meanwhile, functions are aggressively removed; an uncalled function does not stand a chance (which is fantastic).

In trying to dig in a little deeper, I found there's very little mention of tree-shaking in the docs or code besides the fact that it exists, but I think it's something called SWC(?) that actually does the tree-shaking, and I couldn't quite find the relevant code there.

It would be great if there was some kind of report like `deno info` or some verbose log that could be turned on to debug tree-shaking decisions.  In this particular case, however, it doesn't seem to matter if the class is used nowhere in the codebase, it is still included.

**Comment by lucacasonato** [comment]
@dgreensp The relevant code is in https://github.com/swc-project/swc. I suggest you open issues about specific tree shaking optimisations there, as we can't directly change anything related to that from this repo.
