### ISSUE TITLE
badly renamed local symbols with `--no-check`

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#12413]
The module https://deno.land/std@0.107.0/http/http_status.ts does not transpile properly under Deno 1.15 with `--no-check`.

A snippet of the output:

```js
var Status1;
export { Status1 as Status,  };
(function(Status1) {
    Status1[Status1[/** RFC 7231, 6.2.1 */ "Continue"] = 100] = "Continue";
    /** snip **/
})(Status1 || (Status1 = {
}));
export const STATUS_TEXT = new Map([
    [
        Status.Continue,
        "Continue"
    ],
    /** snip **/
]);
```

The local symbol is being needlessly renamed, but then when used in the same scope later on, it is not being used properly.

**Comment by dsherret** [comment]
Fixed in #12416
