### ISSUE TITLE
Use XDG config/cache home when available

### ISSUE THREAD

**Issue by romgrk** [denoland/deno#1241]
[XDG Base Directory specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-0.6.html)

**Comment by ry** [comment]
I'm not necessarily against it - but I don't understand the benefit. Maybe someone can make a compelling argument?

**Comment by romgrk** [comment]
Sure :) Basically, it allows for a better separation of files. Config files go in their own folder, and cached file have their own folder as well. Backups and synchronizing configs across machines is made easier because you know which folder contains what. Also your $HOME is less cluttered.

2 min read that explains it much better than I can: https://ploum.net/207-modify-your-application-to-use-xdg-folders/

**Comment by bartlomieju** [comment]
Somehow supported with #1763

**Comment by romgrk** [comment]
Good enough
