### ISSUE TITLE
type check error from dts

### ISSUE THREAD

**Issue by ije** [denoland/deno#12434]
```ts
import marked from 'https://esm.sh/marked@3.0.4'
```

```
TS2594 [ERROR]:     This module is declared with using 'export =', and can only be used with a default import when using the 'allowSyntheticDefaultImports' flag.
    export = marked;
    ~~~~~~~~~~~~~~~~
        at https://cdn.esm.sh/v54/@types/marked@3.0.1/index.d.ts:17:1
```

deno **1.15.1** (release, x86_64-apple-darwin)
v8 9.5.172.19
typescript 4.4.2

**Comment by ije** [comment]
**1.14.*** can work fine

**Comment by lucacasonato** [comment]
I ran into this to.

**Comment by kitsonk** [comment]
A mistake I made in refactoring the deno_graph, apologies.

**Comment by lucacasonato** [comment]
This probably warrants a 1.15.2 (maybe Friday).

**Comment by ije** [comment]
@kitsonk thanks

**Comment by zzzz465** [comment]
hello, I ran into this same problem while using `React`, `react-zoom-pan-pinch`

![image](https://user-images.githubusercontent.com/46273764/137610005-4b185241-0273-4460-8c5f-1a78e868abb7.png)

it seems that the fix PR is already merged, when will this patch be available in the next patch version?

deno version
![image](https://user-images.githubusercontent.com/46273764/137610016-f8075f8c-fe8c-4594-8bc3-1f963c486c3a.png)

**Comment by kitsonk** [comment]
Deno is currently 1.15.2 and includes this patch.

**Comment by zzzz465** [comment]
@kitsonk great, thank you!
