### ISSUE TITLE
Repl fails to parse some json inputs

### ISSUE THREAD

**Issue by sigmaSd** [denoland/deno#12447]
Trying this line in the repl
```ts
JSON.parse('{"x": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa🌎"}')
```

fails with `Unterminated string literal`

It only fails if there is exactly 99 'a' (or any character) before the world unicode 
If I add or remove a couple of characters before the unicode it  works.

meta:
deno 1.14.3 (release, x86_64-unknown-linux-gnu)
v8 9.4.146.19
typescript 4.4.2

**Comment by andreubotella** [comment]
Might be related to #10542

**Comment by lucacasonato** [comment]
For reference, adding `.x` to the end of the statement makes it work again. Probably a bug in our object formatting code.

**Comment by lucacasonato** [comment]
Yeah, this looks like a combination of bugs in our object formatting code, and REPL code. Running this code demonstrates what is going on pretty well:

```js
console.log(JSON.parse(`["98 chars", "${"x".repeat(98)}🌎"]`));
console.log(JSON.parse(`["99 chars", "${"x".repeat(99)}🌎"]`));
console.log(JSON.parse(`["100 chars", "${"x".repeat(100)}🌎"]`));
```

```
❯❯❯ deno run test.js
[
  "98 chars",
  "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx🌎"
]
[
  "99 chars",
  "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx�..."
]
[
  "100 chars",
  "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx..."
]
```

The formatted splits multi byte unicode chars in half. We need to do two things:

a) update formatting code to not chop multi byte characters in half
b) fix REPL so it doesn't error on surrogate pairs (this is actually an issue with our V8 inspector related code)

I'll keep this issue for a), while b) is already tracked in #12226

**Comment by sigmaSd** [comment]
the issue seems fixed in the latest version, the reproduction code doesn't error anymore
