### ISSUE TITLE
is_component_build=true doesn't work with Rust ( build_extra/rust/rust.gni ) 

### ISSUE THREAD

**Issue by ry** [denoland/deno#1245]
We recently enabled `is_component_build = true` for debug builds. It was discovered that ring_primitives, our only rust component, broke and necessitated:  
https://github.com/denoland/deno/commit/ea4580f3371c1ef6c3f909e5c28d7f04f01659b8

So the issue is basically to undo that commit in such a way that mac/windows debug builds work.

Note the CI does not check debug builds.

**Comment by ry** [comment]
Note `is_component_build` was disabled again for unrelated reasons https://github.com/denoland/deno/commit/cc126528f0a787da2e5c8910f0e8aa2df681a4dd

**Comment by bartlomieju** [comment]
@ry this is stale and doesn't concern this repo anymore, close or transfer to rusty_v8?

**Comment by ry** [comment]
Still applies but stale and belongs to rusty_v8. Let's just close it - not worth tracking imo.
