### ISSUE TITLE
Deno has FFI but knows nothing about memory pointers

### ISSUE THREAD

**Issue by lem0nify** [denoland/deno#12456]
Let's say we need to pass a string in the procedure parameter. Good! We specify the type "buffer", take an `Uint8Array` and write the encoded string there byte-by-byte, ending everything with a null byte, and then pass it.

Let's say we need to pass a structure in the procedure parameter. Fine! Again, we specify the "buffer" type, take an `Uint8Array` of the desired size, fill it with struct padding and all the crap (if it's a parameter for input, not output, of course) and pass it.

But what if we need to pass in a parameter a structure that should store a pointer to another structure or string? What are we doing? That's right: close the project and go code in Python! Or NodeJS. Or anything with a better FFI implementation or native extensions.

Why are we passing the Uint8Array as an object at all? Why not make something like `Deno.byref` (similar to `ctypes.byref` in Python)?

Sorry if I sound toxic. You just removed the native extensions, and I have been waiting for a reasonable replacement for a long time, but you choose not the best ways to implement FFI, as it seems to me.

**Comment by DjDeveloperr** [comment]
I think this can be closed now that https://github.com/denoland/deno/pull/12828 has landed
