### ISSUE TITLE
Can't run error: Permission denied (os error 13)

### ISSUE THREAD

**Issue by xiaoxigua-1** [denoland/deno#12469]
![image](https://user-images.githubusercontent.com/60529600/137634802-f0544f86-263a-41f8-ad0c-9ded8dea2636.png)
OS: Ubuntu
Deno: 1.14.3
my code
```ts
console.log('hi');
```

**Comment by kitsonk** [comment]
The output of the following please:

```
> ls -l test.ts
> whoami
```

**Comment by xiaoxigua-1** [comment]
> The output of the following please:
> 
> ```
> > ls -l test.ts
> > whoami
> ```

![image](https://user-images.githubusercontent.com/60529600/137724287-94adb195-daa8-41f1-b687-7de0aa572063.png)

**Comment by lucacasonato** [comment]
Can you `cat test.ts`?

**Comment by xiaoxigua-1** [comment]
> Can you `cat test.ts`?
yes, I can
![image](https://user-images.githubusercontent.com/60529600/140511003-e1fc44e7-5c2d-4cc6-a0d8-f34d6ba39d94.png)
