### ISSUE TITLE
Plugins for the Deno bundler?

### ISSUE THREAD

**Issue by xastronomica** [denoland/deno#12463]
Similar to [`webpack/webpack`](https://github.com/webpack/webpack), why not make `deno bundle` accepts some sort of plugin system? Few plugins that should be implemented in [`denoland/deno_std`](https://github.com/denoland/deno_std) are:
* Declaration file (`.d.ts`) generation
* Minification

**Comment by xastronomica** [comment]
From what I heard, minification will be handled by SWC. In that case `deno bundle` won't need a minification plugin

**Comment by crowlKats** [comment]
> From what I heard, minification will be handled by SWC. In that case `deno bundle` won't need a minification plugin

Ref #6900

**Comment by lucacasonato** [comment]
`deno bundle` has been deprecated
