### ISSUE TITLE
errors: display Deno version at the end of stacktraces on fatal exception that causes exit

### ISSUE THREAD

**Issue by Divlo** [denoland/deno#12498]
Hey! :wave:

Node.js v17.0.0 has been released, it includes this PR: https://github.com/nodejs/node/pull/38332
It prints the Node.js version used on fatal exceptions that causes exit (that are not encapsulated by try/catch).

It could be a feature, that Deno could also do, it is easier for debugging so you don't have to ask "what version are you on?", it is directly in the error the user copy/paste from when asking for help.

Currently:
With a file `app.ts` :
```ts
throw new Error('Error...')
```

When we do `deno run app.ts`, it prints:
```txt
error: Uncaught Error: Error...
throw new Error('Error...')
      ^
    at file:///home/divlo/Documents/testing/test-ts/app.ts:1:7
```

What about something like this?
```txt
error: Uncaught Error: Error...
throw new Error('Error...')
      ^
    at file:///home/divlo/Documents/testing/test-ts/app.ts:1:7

Deno v1.15.2
```

**Comment by dsherret** [comment]
I don't think it's worth it to add and maintain this feature as bug reporting without the version hasn't been that much of an issue (at least from what I've seen... it does happen, but usually we just ask people what version it is in those cases where it's necessary). Also, some people don't even include the error message or stack trace so in some scenarios this wouldn't help. Having the version there also creates extra noise and takes up more vertical space on errors.

If people not including the version number in bug reports is an issue, I would recommend we improve the bug report template to ask people to run `deno -V` and paste in their version number. It's not too difficult to run this command and quite common practice.

**Comment by jaydenseric** [comment]
I'm not a fan of it, because it makes snapshot testing stderr that much harder when running tests in CI against multiple runtime versions. You have to use regex or something to normalise the output.

The Node.js v17.0.0 major change has actually broken some of my tests, e.g:

https://github.com/jaydenseric/coverage-node/runs/4947577926?check_suite_focus=true#step:4:76

**Comment by bartlomieju** [comment]
@jaydenseric good point. As stated by @dsherret we were not really keen on doing it anyway. I'm going to close this issue.
