### ISSUE TITLE
Dynamic (remote) import is quite slow and seems not cached

### ISSUE THREAD

**Issue by lambdalisue** [denoland/deno#12519]
I'm not sure if it's known but it seems remote dynamic import is quite slow. For example

```typescript
async function main() {
  const t = performance.now();
  await Promise.all([
    import("https://deno.land/x/denops_core@v2.0.3/mod.ts"),
  ]);
  console.log(performance.now() - t);
}
await main();
```

Above took approx. 55 ms with `deno run -A --no-check ./test.ts`. It seems the number of remote imports in the target file affect the performance.

Additionally, it seems remote dynamic import does not use cache. For example

```typescript
// test.ts
async function main() {
  const t = performance.now();
  await Promise.all([
    import("https://deno.land/x/denops_core@v2.0.3/mod.ts"),
    import("https://deno.land/x/denops_core@v2.0.3/mod.ts"),
    import("https://deno.land/x/denops_core@v2.0.3/mod.ts"),
    import("https://deno.land/x/denops_core@v2.0.3/mod.ts"),
    import("https://deno.land/x/denops_core@v2.0.3/mod.ts"),
    import("https://deno.land/x/denops_core@v2.0.3/mod.ts"),
    import("https://deno.land/x/denops_core@v2.0.3/mod.ts"),
    import("https://deno.land/x/denops_core@v2.0.3/mod.ts"),
    import("https://deno.land/x/denops_core@v2.0.3/mod.ts"),
    import("https://deno.land/x/denops_core@v2.0.3/mod.ts"),
  ]);
  console.log(performance.now() - t);
}
await main();
```

Above took approx. 500 ms with `deno run -A --no-check ./test.ts` even the URL is just repeated.

**Comment by lambdalisue** [comment]
> This is caused by concurrent dynamic imports of the same module, I guess all
> of them are fetching resources which is a bug. But if one import is awaited
> ahead of time the others won't perform badly.

> When we are loading a module graph, we eliminate duplicates, but in the
> scenario of a dynamic import, each dynamic import it its own "root" of the
> graph, therefore unique up until the point where the module is actually
> fetched and then cached in memory, which would prevent it from being fetched
> from the network again.

I see. That's actually what we expected from the behavior.

> It is possible to try to trap these, but is this a realistic use case?

No. As you guess, we tried to make things simple and minimal. Let me explain our
situation more clearly.

#### Simplified issue

Let me simplify the issue again from different perspective.

Assume that we have `source1.ts`, `source2.ts`, and `source3.ts` like

```typescript
// source1.ts
export default function () {
  console.log("imported");
}
```

```typescript
// source2.ts
export { debounce } from "https://deno.land/std@0.112.0/async/mod.ts";

export default function () {
  console.log("imported");
}
```

```typescript
// source3.ts
export { Source } from "https://raw.githubusercontent.com/Shougo/ddc-around/main/denops/%40ddc-sources/around.ts";

export default function () {
  console.log("imported");
}
```

And `test-static.ts` and `test-dynamic.ts` like

```typescript
// test-static.ts
const t0 = performance.now();

const t1 = performance.now();
import source1 from "./source1.ts";
console.log(performance.now() - t1, typeof source1);

const t2 = performance.now();
import source2 from "./source2.ts";
console.log(performance.now() - t2, typeof source2);

const t3 = performance.now();
import source3 from "./source3.ts";
console.log(performance.now() - t3, typeof source3);

console.log(performance.now() - t0, "static entire");
```

```typescript
// test-dynamic.ts
const t0 = performance.now();

const t1 = performance.now();
const source1 = (await import("./source1.ts")).default;
console.log(performance.now() - t1, typeof source1);

const t2 = performance.now();
const source2 = (await import("./source2.ts")).default;
console.log(performance.now() - t2, typeof source2);

const t3 = performance.now();
const source3 = (await import("./source3.ts")).default;
console.log(performance.now() - t3, typeof source3);

console.log(performance.now() - t0, "dynamic entire");
```

When we run `test-static.ts` and `test-dynamic.ts`, we'll get quite different
result like And we'll get result like

```
$ deno run -A --no-check ./test-static.ts
0.007908000000014681 function
0.002322999999989861 function
0.00130500000000211 function
0.5761760000000038 static entire

$ deno run -A --no-check ./test-dynamic.ts
0.499715000000009 function
3.197168000000005 function
179.53152500000002 function
183.97954700000003 dynamic entire
```

I understand that dynamic import has some overheads but I feel it's kind too
much. Additionally, the difference among sources are only the first line thus it
seems dynamic import influenced a lot by the number of remote import on the
target file (0.5 ms ~ 179.5 ms)

#### Realistic issue

In real world, we faced start-up time issue of Vim/Neovim that use [ddc][ddc]
that relies on [denops][denops] that built on Deno.

The diagram below illustrates the architecture and relationship among Vim,
denops, and ddc. In short, we found that [ddc][ddc] start-up is slow because it
imports its plugins by dynamic imports (A box with `#` in the diagram.)

[ddc]: https://github.com/Shougo/ddc.vim
[denops]: https://github.com/vim-denops/denops.vim

```plaintext
Vim --- Run ---> denops
                    |
                    +-- Invoke --> Worker            #######################################
                    |                |               #                                     #
                    |                +-- dyn import -#-> ddc                               #
                    |                                #    +-- dyn import --> ddc-around    #
                    |                                #    +-- dyn import --> ddc plugin A  #
                    |                                #    +-- dyn import --> ddc plugin B  #
                    :                                #    :                                #
                    |                                #                                     #
                    |                                #######################################
                    +-- Invoke --> Worker
                    |                |
                    |                +-- dyn import --> denops plugin A
                    |
                    +-- Invoke --> Worker
                    |                |
                    |                +-- dyn import --> denops plugin B
                    :
```

So we tried to investigate the reason of this performance issue. For example,
[ddc-around](https://github.com/Shougo/ddc-around) is a ddc plugin and
`denops/@ddc-sources/around.ts` is the file that imported. We measured the
performance for importing that file like.

```typescript
async function main() {
  const t = performance.now();
  await import(
    "https://raw.githubusercontent.com/Shougo/ddc-around/main/denops/%40ddc-sources/around.ts"
  );
  console.log(performance.now() - t);
}
await main();
```

And we found that it took approx **200 ms** to import that single file. We need
to import multiple similar files, mean that we need to wait **several seconds**
to get completion feature from ddc after we start up Vim.

**Comment by nayeemrmn** [comment]
Some logging shows that these dynamic imports happen to go through `ProcState::prepare_module_load()` entirely one by one. That function doesn't currently have a short-circuiting mechanism around `deno_graph::create_graph()`, where it definitely needs one. Submitting a fix.

**Comment by lambdalisue** [comment]
@nayeemrmn 

Thanks a lot! It improves the performance of dynamic import a lot (170 ms -> 60 ms :tada:) 
However, I still wonder the huge difference between dynamic import and static import (60 ms vs 0.6 ms). Is this kind inevitable performance drawback for dynamic imports or is there any space to improve the performance?  It's just my imagine but I feel that there are unnecessary checks (remote latest check, type check or so on) are performed on dynamic imports. Just my feeling.

![CleanShot 2021-10-31 at 02 16 42](https://user-images.githubusercontent.com/546312/139542850-197e047a-35fd-437b-882c-e188da663bb4.png)

**Comment by bartlomieju** [comment]
@lambdalisue the difference comes from the fact that in case of "static" import all IO (reading from disk, etc) is done before the code is being evaluated. In case of dynamic import the code has already executed and IO is performed once `import()` is called.

**Comment by lambdalisue** [comment]
Aha, got it thanks 👍

**Comment by lambdalisue** [comment]
Are dynamic imports performed concurrent among Worker threads? I'm not 100% sure but it seems imports are performed sequentially rather than concurrently among Workers. Is this expected and/or inevitable behavior?

What I expected 
```
Worker1  =importA=>      
Worker2  =importB=>   
Worker3  =importC=>   
Worker4  =importD=>
```

What I think I am observing

```
Worker1  =importA=>      
Worker2            =importB=>   
Worker3                      =importC=>   
Worker4                                =importD=>   
```
