### ISSUE TITLE
`open`: expand `~` to `$HOME`

### ISSUE THREAD

**Issue by naltun** [denoland/deno#12527]
My `deno` runtime:
```shell
 $ deno --version
deno 1.15.2 (release, x86_64-unknown-linux-gnu)
v8 9.5.172.19
typescript 4.4.2
```

I went to open my `.vimrc` file whilst using `~` as a `$HOME` alias and encountered an exception:
```shell
> const file = await Deno.open("~/.vimrc", { read: true })
Uncaught NotFound: No such file or directory (os error 2), open '~/.vimrc'
    at async Object.open (deno:runtime/js/40_files.js:51:17)
    at async <anonymous>:2:14
```

I think it would be useful for scripts to expand `~` to `$HOME`.

E: Misspelling and remove unneeded line

**Comment by lucacasonato** [comment]
`~` expanding to `$HOME` is a feature of your shell, and is not regular UNIX path syntax. `~` is a valid file name, so how do we know you mean to do open `$HOME/test.txt` when you enter `~/test.txt`, and not `./~/test.txt`? This is also not common on Windows.

There is also no precedent in Node or other popular runtimes for this, so we will not implement this feature.
