### ISSUE TITLE
allow unsafely-ignore-certificate-errors in repl

### ISSUE THREAD

**Issue by kghenderson** [denoland/deno#12542]
Hi all,
I'm using the deno repl to test & build out my application. 
The `--unsafely-ignore-certificate-errors` flag works when using `deno run` but not for `deno repl`.
I assume this is expected, but I don't have an easy way to test my get calls to this server that's outside of my control.

Perhaps there could be (or already is) a way to configure this option from inside the repl and/or using a configuration file?

**Comment by lucacasonato** [comment]
@kghenderson To diagnose the root cause: `CertNotValidForName` means that the CN (common name) or the SAN (subject alternative name) does not match the service you are trying to connect to. For example a certificate that is issued for `example.com` is not valid when you try to connect to `localhost`.

**Comment by VishnuJin** [comment]
hey guys,
 I'd like to work on this, would be great if you could  provide some hints for implementation !!

**Comment by bartlomieju** [comment]
@VishnuJin cool, here's a rough plan of what needs to be done:

Changes to `cli/flags.rs`:
- extract definition of `unsafely-ignore-certificate-errors` into a helper function `unsafely_ignore_ceritifcate_errors_arg`
- use this function in `permission_args()` and `repl_subcommand()`
- extract parsing of `unsafely-ignore-certificate-errors` in `permissions_args_parse()` to `unsafely_ignore_certificate_errors_parse`
- use this function in `permissions_args_parse()` and `repl_parse()`
- add some tests :)

**Comment by VishnuJin** [comment]
@kghenderson could you give this PR #13045  a try to see if the issue is resolved
