### ISSUE TITLE
`URLPattern` not available in `lib.dom.d.ts`

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#12558]
We should add it now, even if TSC has not quite caught up yet.

**Comment by lucacasonato** [comment]
I think we should do this even though it may sound like a slippery slope. Using `URLPattern` with `lib.dom.d.ts` is currently really painful.

**Comment by bartlomieju** [comment]
I agree with @lucacasonato

**Comment by kitsonk** [comment]
We should do a `lib.dom.extras.d.ts` then versus patching the file, like we do for `lib.dom.asynciterable.d.ts`. We could in theory warn about including it, like we do with unstable.

**Comment by sant123** [comment]
@kitsonk so in a future could exist this?

``` json
{
  "compilerOptions": {
    "lib": ["dom", "dom.asynciterable", "deno.ns", "dom.extra"],
    "jsxFactory": "h"
  }
}

```

**Comment by kitsonk** [comment]
Yes.
