### ISSUE TITLE
Investigate require() in rust

### ISSUE THREAD

**Issue by piscisaureus** [denoland/deno#12557]

**Comment by ry** [comment]
Landed #12562.

- The main advantage of require-in-rust is that we can remove the current `--allow-read` restriction. Essentially all programs using `--compat` mode would need `--allow-read` even if they don't read anything from the disk. https://github.com/denoland/deno_std/issues/1495 https://github.com/denoland/deno_std/blob/9340ea02f4df543e8cc11e0dad8dd65137b99c08/node/module.ts#L68

- Another advantage of require-in-rust is that potentially we could have CJS modules be part of the module graph and see information about them in `deno info`. 

- Another advantage is that we can centralize all of our module loading tests, both `--compat` and normal here in the CLI.

- The main disadvantage is that [many Node programs](https://github.com/sindresorhus/resolve-from/blob/4f02820afe9b4e9c379f4bb2745debdb49087d4f/index.js#L29) use `require('module')` and interact with the module loading system. That either means we expose the require-in-rust via `require('module')` or have an independent implementation of require in `std/node/module.ts`. Having two implementations of this complex algorithm seems bad.


For the immediate future the current `std/node/module.ts` approach is making progress - I think we should continue with that. In a couple weeks, when we have more context, I'd like to re-evaluate require-in-rust again.
