### ISSUE TITLE
deno fmt does not properly handle Markdown lists with internal structure

### ISSUE THREAD

**Issue by marrus-sh** [denoland/deno#12560]
The following is almost definitely wrong:

```markdown
- This is a list.

        This is a code block in the list.
```

becomes (after `deno fmt`):

```markdown
- This is a list.

          This is a code block in the list.
```

Two extra spaces have been added to the code block for some reason.

___

This is *possibly* wrong (fine by CommonMark, but different than the original Markdown syntax description):

```markdown
- This is a list.

    This paragraph continues the list.
```

becomes (after `deno fmt`):

```markdown
- This is a list.

  This paragraph continues the list.
```

(CommonMark is okay with a two‐space indent for continuing paragraphs, but the original Markdown syntax description demanded four.)

**Comment by dsherret** [comment]
@marrus-sh thanks for reporting! Yeah, the formatter uses commonmark.

That first example is definitely wrong. It should ensure the indent is 4 from the start of the text of the previous list item (the `T`). Should be fixed in #12595.
