### ISSUE TITLE
Different declarations have same name in `deno bundle` output causing syntax error

### ISSUE THREAD

**Issue by ThePedroo** [denoland/deno#12570]
I'm running the latest Deno version today, While executing the exe, I got these errors:

```
error: Uncaught SyntaxError: Identifier 'once2' has already been declared
    at file://$deno$/bundle.js:20247:0
```

Version: 
![image](https://user-images.githubusercontent.com/73797168/139174590-e7e8e7f6-c9da-4cc0-8cdd-d70d088de2fe.png)

**Comment by dsherret** [comment]
@ThePedroo what are the contents of index.js and the other files it may import?

**Comment by lucacasonato** [comment]
We are going to need the source (`index.js`) and all of it's dependencies. Without more info, we can resolve this issue.

**Comment by jimmont** [comment]
reproduced in `deno bundle` of dependencies copied at https://gist.github.com/jimmont/5ed5a9814d4d75ea88f134838bc87c59
there are 2 files, the deps.js and output bundle; deps.js noted the command use and line numbers of duplicate `const` `c1` in a comment above the modules
if copying part/all here is useful let me know how I can help

**Comment by dsherret** [comment]
Thanks @jimmont! That reproduces the issue:

```bash
> deno bundle https://gist.githubusercontent.com/jimmont/5ed5a9814d4d75ea88f134838bc87c59/raw/ccb6fda2acdf1753c06068bc0af95ae37813d49b/deps.js > out.js
> deno run out.js
error: Uncaught SyntaxError: Identifier 'c1' has already been declared
}, c1 = e3(class extends i3 {
   ^
    at <anonymous> (file:///V:/.../out.js:2047:4)
```

**Comment by ThePedroo** [comment]
> files it may import?

ws & firebase are the only npm that's not native, the others is https & fs

**Comment by ThePedroo** [comment]
> 
> 
> > files it may import?
> 
> ws & firebase are the only npm that's not native, the others is https (HTTP too) & fs

also, the index.js is too long, But do you need something special?
