### ISSUE TITLE
Can't use inspector with test runner

### ISSUE THREAD

**Issue by Soremwar** [denoland/deno#12584]
Using the following `launch.json` I am unable to debug any kind of tests, even if I put a breakpoint outside a `Deno.test` block.

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "request": "launch",
      "name": "Debug",
      "type": "pwa-node",
      "program": "${file}",
      "cwd": "${workspaceFolder}",
      "runtimeExecutable": "deno",
      "runtimeArgs": [
        "test",
        "--allow-all",
        "--inspect-brk"
      ],
      "attachSimplePort": 9229
    }
  ]
}
```

Using simply the command `deno test --inspect-brk --allow-all main.ts` will run the tests normally, but won't wait for any inspector to connect before exiting, as it would happen using `deno run`.

**Comment by Industrial** [comment]
I would really like having debugger support for tests. I'm doing test driven development so running tests is currently the only way I am running the implementation code.

**Comment by rracariu** [comment]
This is a regression with latest Deno. In 1.12.2 this worked.

**Comment by kitsonk** [comment]
Related #12417

**Comment by fungiboletus** [comment]
The first release where it doesn't work (on my machine) is the `1.14.1`. `1.14.0` works.

**Comment by jeiea** [comment]
It is still reproducible with deno 1.16.4 (release, x86_64-pc-windows-msvc).

**Comment by jespertheend** [comment]
This seems to have regressed in e1144fd63569a79afc211d1f981029d67bf8f5ed

**Comment by david-rse** [comment]
Having the same issue; `deno test --inspect-brk ...` doesn't break for listener.
```
deno --version
deno 1.37.2 (release, x86_64-unknown-linux-gnu)
```
