### ISSUE TITLE
is it ok if I will try to port koa and dependencies?

### ISSUE THREAD

**Issue by dkuida** [denoland/deno#1262]
I cannot really fully conclude if it is even doable at this moment - and if not so at least it will highlight where should I try to contribute.
But since I did see that there is a basic http implementation available now - I thought to port koa to deno - as I personally feel it is a good match for a REST  server with its async/await approach

One potentially curious question that I keep thinking from yday though - how deno compatible libraries should be really searched? even though theoretically it would be possible to put them on npm - but there is no way to search for those

**Comment by kyranet** [comment]
I don't think it's doable yet, but I think you can track https://github.com/denoland/deno/issues/726 in the meanwhile, though the first implementation may not be completed enough to fulfill all the requirements for Koa's internals.

**Comment by dkuida** [comment]
@kyranet yeah I do see that many dependencies are needed for koa itslef - though I do see that many of those actually can be done with TS directly.
I will and see if I can get at least the basics of http server - from what I played around the basic http server is responding. - and #726 is merged already.

on another note - where can I see some task list that I could help with? Typescript is really the goto for me in the last year - as the dynamic typing got me extremely frustrated

**Comment by hayd** [comment]
http server is here: https://github.com/denoland/net

**Comment by kyranet** [comment]
> on another note - where can I see some task list that I could help with?

We use GitHub's milestones, we have higher priority for 0.3 (the http server is one of them!), feel free to check it out; https://github.com/denoland/deno/milestones

Additionally we have a [Gitter](https://gitter.im/denolife/Lobby) channel, and development instructions are in the [Docs.md](https://github.com/denoland/deno/blob/master/Docs.md).

**Comment by kevinkassimo** [comment]
@ry I’ll also start helping with http.ts recently. Looks like socket is not properly closed.

**Comment by ry** [comment]
@kevinkassimo Thank you - help on net/http is very welcome.

**Comment by dkuida** [comment]
@ry ok I guess that is a better priority and will close this thread.

**Comment by hayd** [comment]
I _think_ one could define a koa-like api already on top of ry's http server, which could then be updated as that is fleshed out/completed. IMO It doesn't seem necessary to wait until the server is functionally/feature-complete to start building. 😄 

That said, this isn't really a deno issue. It's **definitely** okay for you to implement these and add them to [the registry](https://github.com/denoland/registry/) when they are vaguely working! ...Although one nice thing about deno, is you don't need to submit to a central registry/package manager (e.g. raw github links will work fine).
