### ISSUE TITLE
LSP: SignatureHelp response contains Markdown but isn't tagged as such, causing inadequate client rendering

### ISSUE THREAD

**Issue by frou** [denoland/deno#12620]
Hi there. Here's a screenshot from Sublime Text showing a fenced code block in LSP SignatureHelp being considered verbatim plaintext:

<img width="571" alt="Screenshot 2021-11-01 at 12 18 39" src="https://user-images.githubusercontent.com/172663/139695428-7e88b373-9b4a-4e2a-8657-04e184de3ccb.png">

[A Sublime LSP developer says this is a server rather than client issue](https://github.com/sublimelsp/LSP-Deno/issues/9#issuecomment-956280474), because the content is not being tagged as `MarkupContent` in the LSP SignatureHelp response.

From a quick search of the code in this repo, it looks like there are two existing examples of content being tagged as `MarkupContent`:
* [Hover](https://github.com/denoland/deno/blob/34a9ddff091950aee9d89915cd13944259e7d346/cli/lsp/language_server.rs#L1103-L1106)
* [CompletionEntryDetails](https://github.com/denoland/deno/blob/34a9ddff091950aee9d89915cd13944259e7d346/cli/lsp/tsc.rs#L1537-L1540)

**Comment by David-Else** [comment]
@folke In Neovim (master) and nvim-cmp the triple-backtick code block is not show, but the highlighting is not working:

![Screenshot from 2021-11-02 14-12-55](https://user-images.githubusercontent.com/12832280/139864292-bb14f3ce-1d1a-481a-be12-c6a08fc4e25c.png)

**Comment by lucacasonato** [comment]
The fix will be available in 1.16.0 on Tuesday.

**Comment by David-Else** [comment]
@lucacasonato I tried `deno 1.15.3+8e010b6 (canary, x86_64-unknown-linux-gnu)` and there is no change in the Neovim LSP output in the screenshot I made above. Is this now an error I should report to the Neovim maintainers?

**Comment by lucacasonato** [comment]
Yes, we return the right thing now.

**Comment by frou** [comment]
Thank you @lucacasonato! It was successful:

<img width="554" alt="Screenshot 2021-11-09 at 22 45 05" src="https://user-images.githubusercontent.com/172663/141017709-e21c93a0-e0f6-45d4-97fd-0ffab72bee21.png">

**Comment by David-Else** [comment]
Note to Neovim users:

To appropriately highlight codefences returned from denols, you will need to augment vim.g.markdown_fenced languages in your init.lua. Example:
```
vim.g.markdown_fenced_languages = {
  "ts=typescript"
}
```
