### ISSUE TITLE
[feat. request] Allow reading CA certificate and key file from a variable instead of a file.

### ISSUE THREAD

**Issue by amithm7** [denoland/deno#12639]
Currently `ListenTlsOptions` require a path to the cert and key files:

https://github.com/denoland/deno/blob/b7341438f29de88f3458b32a835bfad560bda52e/ext/net/lib.deno_net.d.ts#L89-L94

It would be great if these could be read from a variable.

So that these could be loaded from environment variables.

**Comment by lucacasonato** [comment]
Do you mean `connectTls` or `listenTls`? `connectTls` supports CA certs from files.

**Comment by amithm7** [comment]
my mistake, `listenTls`

**Comment by amithm7** [comment]
@lucacasonato
Also, the `keyFile` here has a comment saying "_public_ key file."

This should be the _private_ key, right?
Found this scanning the src code (although I don't know rust):
https://github.com/denoland/deno/blob/94a81e5e9bda5a7da51bc864e544bf35ef26910e/ext/net/ops_tls.rs#L1046

**Comment by lucacasonato** [comment]
Yes, you are right.

**Comment by kt3k** [comment]
This seems also necessary for implementing `tls.createServer` in `deno_std/node`.
