### ISSUE TITLE
 Make internal modules optional for workers in deno_runtime

### ISSUE THREAD

**Issue by JomerDev** [denoland/deno#12641]
While using deno_runtime embedded in a project, not everybody has a need for all internal modules (deno_webgpu for example).
I propose to add features for the individual modules, with the default being whatever deno uses. That would allow for more flexibility for embedders while meaning no change to the deno cli

P.s. I'm happy to open a PR for this myself, but I was told in discord to open an issue for this first

**Comment by lucacasonato** [comment]
Feel free to open a PR. We can discuss further there.

**Comment by lucacasonato** [comment]
The PR did not go anywhere - closing this
