### ISSUE TITLE
First attempt executing a script throws errors, next attempts don't

### ISSUE THREAD

**Issue by ChiKler** [denoland/deno#12640]
The source code is contained within this repo:
https://github.com/ChiKler/2D-container-of-2D-items-TS-JS/tree/36ef9c152bc3f27b0d2eef00ef599be696331fcf

Here's the sequence of commands you must execute in order to replicate this behaviour:
```
git clone https://github.com/ChiKler/2D-container-of-2D-items-TS-JS.git
cd 2D-container-of-2D-items-TS-JS
git reset --hard 36ef9c152bc3f27b0d2eef00ef599be696331fcf
deno run --allow-net --allow-read --reload ./src/mod.test.ts
deno run --allow-net --allow-read ./src/mod.test.ts
```

As you can see, the first time you run the script, it throws some errors; the next time it doesn't.

Edit: In order to fix this, I added some ``// @ts-ignore`` comments.
Here's the commit that fixes it:
https://github.com/ChiKler/2D-container-of-2D-items-TS-JS/commit/2adf4611d4f9b13ec4ec4d64524a66a491f7508d

**Comment by kitsonk** [comment]
Duplicate of #12471
