### ISSUE TITLE
Error converting the result for "op_respond"

### ISSUE THREAD

**Issue by juliangruber** [denoland/deno#12646]
```
$ deno run --allow-net --allow-env --allow-read --unstable file.ts
Check file:///...
error: Error: Error converting the result for "op_respond".
    at deno:core/core.js:86:46
    at unwrapOpResult (deno:core/core.js:106:13)
    at Object.opSync (deno:core/core.js:120:12)
    at exec (deno:cli/tsc/99_main_compiler.js:522:10)
    at [native_code]:1:12
$ deno --version
deno 1.10.3 (release, x86_64-unknown-linux-gnu)
v8 9.1.269.27
typescript 4.2.2
$ uname -a
Linux vbox.transloadit.com 4.15.0-159-generic #167-Ubuntu SMP Tue Sep 21 08:55:05 UTC 2021 x86_64 GNU/Linux
```

I just had this today for the first time and sometimes reproduce it, sometimes not. In general, the typescript phase before running the program is taking unexpectedly long.

**Comment by kitsonk** [comment]
Deno 1.10.3 is from late may this year, which is a long time ago in Deno terms.

You would need to provide the contents of `file.ts`, but even then it would likely be "what happens when you upgrade" sort of scenario.

**Comment by juliangruber** [comment]
The same also happens with deno 1.13.2. I could upgrade to a later version for the sake of this particular error, however a later version couldn't be shipped as https://github.com/denoland/deno/issues/12086 is blocking the `deno bundle` feature.

**Comment by juliangruber** [comment]
The same also happens with a very simple file:

```bash
$ echo 'console.log("HI")' > /tmp/file.ts
$ deno run --allow-net --allow-env --allow-read --unstable /tmp/file.ts
Check file:///tmp/file.ts
error: Error: Error converting the result for "op_respond".
    at deno:core/01_core.js:106:46
    at unwrapOpResult (deno:core/01_core.js:126:13)
    at Object.opSync (deno:core/01_core.js:140:12)
    at exec (deno:cli/tsc/99_main_compiler.js:533:10)
    at [deno:cli/tsc.rs:567:27]:1:12
```

A source of this issue _could_ be that I just updated my host to mac OS Monterey and since then my virtualbox guest has been behaving unusually...However other programs aren't breaking, they're just sometimes slower than usual

**Comment by bartlomieju** [comment]
@juliangruber I tried your reproduction on 1.10.3, 1.13.2 and 1.16.3 and I'm unable to reproduce the problem. Are you still having troubles with it?

**Comment by juliangruber** [comment]
I'm not reproducing it any more. The situation was (IIUC) that I was using a build of VirtualBox that wasn't yet ready for Monterey, and after inspecting syscalls we discovered unexpected threadlock wait issues. My whole guest system was slow, however Deno was the only program that broke because of it. After upgrading VirtualBox everything is going well again. I don't think it's worth trying to reproduce my exact setup any more 🤔

**Comment by bartlomieju** [comment]
Great, thanks for the info @juliangruber
