### ISSUE TITLE
"error: No such file or directory (os error 2)" while running Deno.run

### ISSUE THREAD

**Issue by AccomplishLearning** [denoland/deno#12660]

**Comment by kitsonk** [comment]
The error usually indicates that there is no such file or directory, but without any more information than that, it is impossible to tell.  The 🔮 is broken.

**Comment by AccomplishLearning** [comment]
The code was 
```javascript
const program = Deno.run({
    cmd:["ls"]
})
```
And error was on Deno.run

**Comment by kt3k** [comment]
what is the output of `deno --version`?

what happens if you run the script like the below:

```ts
const program = Deno.run({
    cmd:["ls"]
});
console.log(await program.status());
```

**Comment by AccomplishLearning** [comment]
Ok i will check

**Comment by lucacasonato** [comment]
@AccomplishLearning Are you on Windows?

**Comment by AccomplishLearning** [comment]
@kt3k same error

**Comment by AccomplishLearning** [comment]
> @AccomplishLearning Are you on Windows?

@lucacasonato yes

**Comment by kitsonk** [comment]
> what is the output of `deno --version`?

@AccomplishLearning could you please provide that as requested.

**Comment by AccomplishLearning** [comment]
> > what is the output of `deno --version`?
> 
> @AccomplishLearning could you please provide that as requested.

1.15.3

**Comment by kitsonk** [comment]
@AccomplishLearning that is not the output of `deno --version`.  Could you please provide the output of `deno --version`.
