### ISSUE TITLE
lint: `--fix`

### ISSUE THREAD

**Issue by DetachHead** [denoland/deno#12673]
Some examples of easily fixable rules:

- removing unused imports
- changing `var`s to `let`s 
- changing `let`s to `const` if they aren't reassigned

**Comment by dsherret** [comment]
This is handled by deno lint's `no-unused-vars` rule so I don't think we should add it (maybe instead eventually add a `--fix` in deno lint). I think having this in deno fmt would be kind of annoying because then "format on save" would remove unused imports during development.

**Comment by lucacasonato** [comment]
I agree with @dsherret. This would be a great candidate for `deno lint --fix`.

**Comment by DetachHead** [comment]
Agreed. I've updated the issue

**Comment by dsherret** [comment]
@DetachHead maybe open a new issue for `deno lint --fix` in case someone searches for "remove unused imports" in the future they'll see the resolution. I'll rename and close this one for now.

**Comment by DetachHead** [comment]
#12681
