### ISSUE TITLE
`deno repl` runs with implicit permissions

### ISSUE THREAD

**Issue by GJZwiers** [denoland/deno#12671]
I have a module that requires some `read`, `write` and `run` permissions when using `deno run`. However, if I import the same module in the REPL these permissions are either granted implicitly or not required? This seems like a security risk because if an attacker can get someone to 'try out' their project by running an 'example' in the REPL,that code can circumvent explicit permission requirements and cause all kinds of havoc.

Maybe `deno repl` should implement a `--prompt` flag just like `deno run` and run with it by default? That way the REPL can still be used for quick prototyping, but also asks the user before granting for example net access to shady.site.

**Comment by kitsonk** [comment]
Duplicate of #12665
