### ISSUE TITLE
`type-check` command

### ISSUE THREAD

**Issue by DetachHead** [denoland/deno#12674]
it would be useful if there was a `deno check` or `deno type-check` command that type-checks the whole project (like how `deno lint` and `deno fmt` works). relying on `deno run` or `deno test` for type checking isn't ideal as it only checks modules that are imported by the entrypoint

**Comment by nayeemrmn** [comment]
I think you want a `deno cache` (with no positional args) which picks up all `.js`, `.ts`, etc files.

**Comment by kitsonk** [comment]
As @nayeemrmn suggests.  We are unlikely to address renaming or adding additional subcommands until Deno 2.0 and we have a clear idea on how we support type checking.

This is effectively duplicate of #11786 as well.
