### ISSUE TITLE
Lost precision for large 64 bit numbers

### ISSUE THREAD

**Issue by kevinkassimo** [denoland/deno#12679]
Context: https://github.com/denoland/deno/issues/12212

Currently all 64 bit numbers are forwarded to use `v8::Number` which results in lost of precision for e.g. large 64 values like `u64::MAX`:
 https://github.com/denoland/serde_v8/blob/edd2994ac0732b56bad30f32655afd1e6250775c/src/ser.rs#L472-L474

While logically we have BigInt we can switch to, I am unsure how bad the performance implication could be.

**Comment by DjDeveloperr** [comment]
> > What if we return u/i64 as transmuted to f64, then the ffi code could use a DataView and convert it to BigInt64? I am not familiar enough with f64s to know if that will work for all numbers though...
> 
> I think that would likely work.

Update: It doesn't work in my case unless the type is explicitly transmuted to f64 in native side - which I cannot do.

What about implementing `serialize_i128` and `serialize_u128` instead? Serde has built in support for these so it's easy to impl as well.
