### ISSUE TITLE
`lint --fix`

### ISSUE THREAD

**Issue by DetachHead** [denoland/deno#12681]
Some examples of easily fixable rules:

- removing unused imports
- changing `var`s to `let`s
- changing `let`s to `const`s if they aren't reassigned

**Comment by MierenManz** [comment]
Also also unused variables. Changing them from `const unused = "not used"` to `const _unused = "not used"`

**Comment by KotlinIsland** [comment]
> Also unused variables. Changing them from `const unused = "not used"` to `const _unused = "not used"`

That doesn't seem like the kind of thing I would want happening automatically. Seems like it would very easily hide those errors more than conveniently fix them.

**Comment by KotlinIsland** [comment]
@stale Guess, what it's not stale 😳

**Comment by tlgimenes** [comment]
This would be pretty good actually. I would be able to automatically fix code with a pre-commit hook

**Comment by quinn** [comment]
I definitely rely on this with eslint, especially for cleaning up unused imports

**Comment by dsherret** [comment]
The main infrastructure for this landed in https://github.com/denoland/deno/pull/22615 but it is not implemented for many rules.

Please open specific issues for specific rules you'd like to see implemented.
