### ISSUE TITLE
lint: `prefer-primordials` is enabled when using config file

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#12694]
Using this config enables `prefer-primordials` rule. This is obviously wrong.

```json
{
  "lint": {
    "rules": {
      "exclude": [
        "camelcase"
      ]
    }
  }
}
```

If no tags are specified, they should default to `["recommended"]`. `prefer-primordials` is not recommended.

**Comment by bartlomieju** [comment]
I think this might be a regression introduced in https://github.com/denoland/deno/pull/12644
