### ISSUE TITLE
Using the same import() outside and inside a web worker causes failing behavior

### ISSUE THREAD

**Issue by bebraw** [denoland/deno#12709]
I noticed that if the same `import()` is used both outside and inside a web worker, this can lead to broken behavior. I suspect this has something to do with Deno's module caching behavior (overly aggressive in this case?).

With the same `import()`, I end up with `error: Uncaught (in promise) ReferenceError: document is not defined` within the worker code. This doesn't occur if `import()` has been done only within the web worker itself.

I have set up a small demonstration at https://github.com/bebraw/twind-worker-demo to explain better.

**Comment by bartlomieju** [comment]
Most likely caused by https://github.com/denoland/deno/issues/12458 which I'm working on a fix for

**Comment by bebraw** [comment]
Great. I hope you can use that as a test case to verify. 👍 

I have an immediate use case for the fix (parallelization of my already fast static site generator 😄 ).

**Comment by nayeemrmn** [comment]
> With the same `import()`, I end up with `error: Uncaught (in promise) ReferenceError: document is not defined` within the worker code. This doesn't occur if `import()` has been done only within the web worker itself.

That error is happening on the main thread. What happens if you remove the import in the worker? Wouldn't you still get the error?

**Comment by bebraw** [comment]
> That error is happening on the main thread. What happens if you remove the import in the worker? Wouldn't you still get the error?

That's a great point. I can see it's crashing the same way if I remove the `import()` from worker. I reduced it to `await import("./markdown.ts").then((m) => m.default("# foo\nbar"));` and it's still crashing then.

I think the implication is that it's something on my side to debug so I'll close this issue.

Thanks!
