### ISSUE TITLE
Assertion failed on `JsRuntime::mod_evaluate()`

### ISSUE THREAD

**Issue by andreubotella** [denoland/deno#12713]
It's possible for this assertion in `JsRuntime::mod_evaluate()` to fail if the `JsRuntime`'s isolate is terminated before the module evaluation:

https://github.com/denoland/deno/blob/1eae6c139ee1dac28df57d67d993792b773fa1ff/core/runtime.rs#L1047-L1049

You can trigger this reliably as a user of `deno_core`:

```rust
let mut runtime = JsRuntime::new(RuntimeOptions {
  module_loader: Some(Rc::new(FsModuleLoader)),
  ..Default::default()
});
let module_id = runtime.load_main_module(&main_module, None).await?;

runtime.v8_isolate().terminate_execution();

let _ = runtime.mod_evaluate(module_id);
```

And although very rare, this can happen in Deno if a worker is terminated immediately after creation: https://github.com/denoland/deno/issues/12658#issuecomment-964479851

**Comment by bartlomieju** [comment]
Thanks for the report Andreu, this is totally reasonable, instead of the assertion we should first check if the execution had been terminated. PRs are welcome, otherwise I'll put this in my backlog.
