### ISSUE TITLE
Support MD5 in webcrypto

### ISSUE THREAD

**Issue by ry** [denoland/deno#12715]
like cloudflare https://developers.cloudflare.com/workers/runtime-apis/web-crypto

**Comment by lucacasonato** [comment]
Before being able to bring this up with web standards bodies, we need descriptions of specific usecases.

**Comment by Zertz** [comment]
One very specific use case I'm aware of is generating Gravatar image URLs: https://en.gravatar.com/site/implement/images/

It works by generating the MD5 hash of an email.

**Comment by N8Brooks** [comment]
Possibly for [Advent of Code](https://adventofcode.com/). Several mock Bitcoin problems require MD5, although deno_std/crypto would work for this.

[AdventOfCode/year2015/day04](https://adventofcode.com/2015/day/4)
[AdventOfCode/year2016/day05](https://adventofcode.com/2016/day/5)

**Comment by bnoordhuis** [comment]
Not that I necessarily think it's a good idea but #12793 adds support for everyone's favorite hash function for unsalted passwords.

**Comment by bnoordhuis** [comment]
I've closed #12793 because WPT isn't happy with it (expects MD5 to be rejected but of course that's no longer the case.)

If MD5 support is important, I'll give it another shot, but otherwise I suggest letting it rest.

**Comment by erfanium** [comment]
MongoDB driver depends on md5
https://github.com/denodrivers/deno_mongo/issues/299
We currently use `std/hash` but it's deprecated. what do you suggest for this case?

**Comment by bnoordhuis** [comment]
@erfanium You probably saw the comment in the linked issue but for posterity: the `crypto.subtle.digest()` polyfill from https://deno.land/std@0.116.0/crypto supports MD5.

**Comment by danopia** [comment]
Another usecase, MD5 is used in HTTP digest auth. I ran into this when accessing an API that expects public/private key auth. WebAssembly feels a bit heavy for the amount of data that gets digested here, so I'm using `std/hash` just to have something appropriate for now
