### ISSUE TITLE
Deno 1.16 HTTP fails to respond with Uint8Array

### ISSUE THREAD

**Issue by elisee** [denoland/deno#12724]
Hi! I've just updated to Deno 1.16 and my HTTP server fails to serve most binary files in weird ways.

I've narrowed it down to the following minimal test case:
```ts
import { serve } from "https://deno.land/std@0.114.0/http/server.ts";
serve((req) => new Response(new Uint8Array([97])), { addr: ":80" });
```
The above works, sends the letter `a` (ASCII 97).
```ts
import { serve } from "https://deno.land/std@0.114.0/http/server.ts";
serve((req) => new Response(new Uint8Array([128])), { addr: ":80" });
```
The above doesn't work in 1.16 (but does work in 1.15.3).
Chrome says `ERR_EMPTY_RESPONSE`, Firefox says `Connection was reset`.

From my testing, it looks like any byte value from 0-127 works fine, but any byte value from 128-255 causes the response to be empty.

`deno --version` says:
```
deno 1.16.0 (release, x86_64-pc-windows-msvc)
v8 9.7.106.2
typescript 4.4.2
```

**Comment by lucacasonato** [comment]
I have a feeling this is related to https://github.com/denoland/deno/commit/c27ef0ac7b5fd7aba4de24292e80387c8243896e

**Comment by lucacasonato** [comment]
@elisee We are going to get this fixed ASAP! This snuck in during some performance work we did last week. We will cut a 1.16.1 release as soon as the fix is merged.

**Comment by EliteScientist** [comment]
Awesome. I have the same issue. The console logs:
`request: {
  url: "...",
  method: "GET",
  hasBody: false
}
response: { status: 200, type: "image/png", hasBody: true, writable: false }

    at Object.opAsync (deno:core/01_core.js:137:28)
    at Object.respondWith (deno:ext/http/01_http.js:202:38)
[uncaught application error]: TypeError - Error parsing args: data did not match any variant of untagged enum StringOrBufferInner`

What was bizarre is that it seemed to be data dependent. Here is a test app that I created:
`import {Application, Router} from "https://deno.land/x/oak@v9.0.1/mod.ts"

async function main():Promise<void>
{
	const router	= new Router();
	
	router.get("/Broken", (context) =>
	{
		const {response}	= context;
		
		response.headers.set("Content-Length", "10");
		response.type = "image/png";
			
		response.body = new Uint8Array([200,201,202,203,204,205,206,207,208,209]);
		console.log(response.body);
	});
	
	router.get("/Works", (context) =>
	{
		const {response}	= context;
		
		response.headers.set("Content-Length", "10");
		response.type = "image/png";
		
		response.body = new Uint8Array([1,2,3,4,5,6,7,8,9,10]);
		console.log(response.body);
	});
	
	const app		= new Application();
	app.use(router.routes());
	app.use(router.allowedMethods());
	
	await app.listen({port: 8000});
}

main();`

**Comment by elisee** [comment]
Tested with Deno v1.16.1, it is fixed. Thank you very much!
