### ISSUE TITLE
Uncaught SyntaxError: Identifier 'i2' has already been declared

### ISSUE THREAD

**Issue by ryanwhite04** [denoland/deno#12739]
When bundling the following code to be used in the browser, I get the error *Uncaught SyntaxError: Identifier 'i2' has already been declared* when loaded in the browser.

### index.html
```html
<script type="module" src="bundle.js"></script>
```

### modules.js
```javascript
import rough from 'https://unpkg.com/roughjs/bundled/rough.esm.js?module';
import { LitElement } from 'https://unpkg.com/lit-element/lit-element.js?module';
export { rough, LitElement }
```

I'm using the following command to bundle the code:
```bash
deno bundle modules.js bundle.js
```

I was using the latest version 1.16.1 to run this, but because I remember this used to work with no errors, I compiled a list of any errors for each version in the table below.

I found that there were no errors from version 1.7.0 until 1.15.0.

The error also goes away if I remove the import of the *rough* module from _modules.js_ which I think also includes modules that are duplicated in the *lit-element* module.

This error looks like it might be related to https://github.com/denoland/deno/issues/8959 which was closed after a fix earlier this year, but both output *Uncaught SyntaxError: Identifier 'i2' has already been declared*

### Windows 10 Linux Subsystem
Build: 22000
Branch: co_release
Release: Ubuntu 20.04.3 LTS,
Kernel: Linux 5.10.16.3-microsoft-standard-WSL2

<google-sheets-html-origin>
Version | Error
-- | --
1.16.1 | Uncaught SyntaxError: Identifier 'i2' has already been declared
1.16.0 | Uncaught SyntaxError: Identifier 'i2' has already been declared
1.15.3 | Uncaught SyntaxError: Identifier 'i2' has already been declared
1.15.2 | Uncaught SyntaxError: Identifier 'i2' has already been declared
1.15.1 | Uncaught SyntaxError: Identifier 'i2' has already been declared
1.15.0 |  
1.14.3 |  
1.14.2 |  
1.14.1 |  
1.14.0 |  
1.13.2 |  
1.13.1 |  
1.13.0 |  
1.12.2 |  
1.12.1 |  
1.12.0 |  
1.11.5 |  
1.11.4 |  
1.11.3 |  
1.11.2 |  
1.11.1 |  
1.11.0 |  
1.10.3 |  
1.10.2 |  
1.10.1 |  
1.10.0 | This version can't be found
1.9.2 |  
1.9.1 |  
1.9.0 |  
1.8.3 |  
1.8.2 |  
1.8.1 |  
1.8.0 |  
1.7.5 |  
1.7.4 |  
1.7.3 | This version can't be found
1.7.2 |  
1.7.1 |  
1.7.0 |  
1.6.3 | Uncaught ReferenceError: ReactiveElement is not defined at bundle.js:2075
1.6.2 | Uncaught ReferenceError: ReactiveElement is not defined at bundle.js:2182
1.6.1 | Uncaught ReferenceError: ReactiveElement is not defined at bundle.js:2182
1.6.0 | Uncaught ReferenceError: ReactiveElement is not defined at bundle.js:2182
1.5.4 | Uncaught ReferenceError: ReactiveElement is not defined at bundle.js:1015
1.5.3 | Uncaught ReferenceError: noChange is not defined at bundle.js:1974
1.5.2 | Uncaught ReferenceError: noChange is not defined at bundle.js:1974
1.5.1 | Uncaught ReferenceError: noChange is not defined at bundle.js:1974
1.5.0 | bundle.js:2233 Uncaught SyntaxError: Identifier 'e6' has already been declared
1.4.6 | Can't Compile because .js?module files are considered typscript
1.4.5 | Can't Compile because .js?module files are considered typscript
1.4.4 | Can't Compile because .js?module files are considered typscript
1.4.3 | Can't Compile because .js?module files are considered typscript
1.4.2 | Can't Compile because .js?module files are considered typscript
1.4.1 | Can't Compile because .js?module files are considered typscript
1.4.0 | Can't Compile because .js?module files are considered typscript
1.3.3 | Can't Compile because .js?module files are considered typscript
1.3.2 | Can't Compile because .js?module files are considered typscript
1.3.1 | Can't Compile because .js?module files are considered typscript
1.3.0 | Can't Compile because .js?module files are considered typscript
1.2.3 | Can't Compile because .js?module files are considered typscript
1.2.2 | Can't Compile because .js?module files are considered typscript
1.2.1 | Can't Compile because .js?module files are considered typscript
1.2.0 | Can't Compile because .js?module files are considered typscript
1.1.3 | Can't Compile because .js?module files are considered typscript
1.1.2 | Can't Compile because .js?module files are considered typscript
1.1.1 | Can't Compile because .js?module files are considered typscript
1.1.0 | Can't Compile because .js?module files are considered typscript
1.0.5 | Can't Compile because .js?module files are considered typscript
1.0.4 | Can't Compile because .js?module files are considered typscript
1.0.3 | Can't Compile because .js?module files are considered typscript
1.0.2 | Can't Compile because .js?module files are considered typscript
1.0.1 | error: Import 'https://unpkg.com/@lit/css-tag.js?module' failed: 404 Not Found
1.0.0 | error: Uncaught AssertionError: Assertion failed.

**Comment by rivy** [comment]
I'm receiving a similar error when executing some compiled utilities:

```shell
C:>dxf.exe --help
error: Uncaught SyntaxError: Identifier 'win321' has already been declared
    at file://$deno$/bundle.js:32688:6
```

**Comment by rivy** [comment]
Thanks, @dsherret!
Your PR #13025 fixed all the bundling (and compiled) faults that I had been seeing.
