### ISSUE TITLE
deno test: Add more overloads of Deno.test()

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#12744]
Currently `Deno` provides following two overloads of `Deno.test()` API:
```ts
export function test(t: TestDefinition): void;
// Deno.test({
//  name: "test name",
//  fn: function () { 
//  }
// });

export function test(
    name: string,
    fn: (t: TestContext) => void | Promise<void>,
): void;
// Deno.test("test name", () => { });
```

I propose to add four more overloads like this:
```ts
export function test(fn: (t: TestContext) => void | Promise<void>): void;
// Deno.test(function testName() { });

export function test(name: string, options: Omit<TestDefinition, "name">, fn: (t: TestContext) => void | Promise<void>): void;
// Deno.test("test name", { only: true }, function() { });

export function test(options: Omit<TestDefinition, "fn">, fn: (t: TestContext) => void | Promise<void>): void;
// Deno.test({ name: "test name" }, function() { });

export function test(options: Omit<TestDefinition, "fn" | "name">, fn: (t: TestContext) => void | Promise<void>): void;
// Deno.test({ only: true }, function testName() { });
```

The reason is two fold:
- it would allow us to completely drop helper called `unitTest` that we use internally for unit tests of the runtime (this has been my goal for the longest time, we've been dogfooding numerous changes to the testing system through unit tests; after making `Deno.TestDefinition.permissions` stable these overloads are the last bit needed to get rid of `unitTest` wrapper)
- increase user ergonomy - currently it's very cumbersome if one wants to mark a test as "only" - if you use shorthand overload, you need to rewrite it to the `TestDefinition` form (ie. the object form), with proposed overloads it would be a matter of adding `{ only: true }` as first or second argument

Ref #11764

CC @dsherret @caspervonb @lucacasonato @kitsonk

**Comment by caspervonb** [comment]
Always end up having a wrapper in the wild for this.
The internal `unitTest` does nothing but provide the second overload so sgtm!
