### ISSUE TITLE
[deno run] There is a pattern of not detecting errors when the `deno run` command is reading a file with syntax errors.

### ISSUE THREAD

**Issue by shinshin86** [denoland/deno#12740]
## Summary
There is a pattern of not detecting errors when the `deno run` command is reading a file with syntax errors.

## My environment

```sh
$ deno --version
deno 1.16.0 (release, aarch64-apple-darwin)
v8 9.7.106.2
typescript 4.4.2
```

### Step 1

Create `main.ts`.

```typescript
console.log('Hi Deno');
```

Then run this script.

```sh
deno run main.ts
```

The results are as follows.

```sh
Hi Deno
```

### Step 2

The next step is to create `sub.ts`.
(This code has a syntax error.)

```typescript
// This code is syntax error
export function hello(name: string) {
  return hello name;
}
```

Modify `main.ts` to load `sub.ts`.

```typescript
import { hello } from './sub.ts';
console.log(hello('Deno'));
```

Then run this script.

```sh
deno run main.ts
```

The results are as follows.

```sh
Hi Deno
```

I thought this code of mine would not work due to a syntax error, but it runs fine.
And the result of execution is the result before editing.

By the way, when I did `deno compile`, it showed a syntax error.

```sh
$ deno compile main.ts
error: The module's source code could not be parsed: Expected ';', got 'name' at file:///Users/~/sub.ts:3:16
```

## Question

Is this behavior correct?

I still don't understand the Deno spec and the internal code exactly, but it seems to me that a syntax error would be correct in this case. That's why I created the Issue.

I'd really appreciate it if you could give me your opinion .

Thank you!

**Comment by kitsonk** [comment]
There is an issue, the type checking of `main.ts` is failing, but diagnostics are not being emitted and the previously cached value of the program is being run erronously.

**Comment by kt3k** [comment]
even `deno run --reload main.ts` doesn't work around the issue..

**Comment by nayeemrmn** [comment]
This is due to `ProcState::prepare_module_load()` not failing on graph errors and instead leaving `ProcState::load()` to happen upon the error when called by V8. But in this case it won't happen upon it because the old non-overwritten emit doesn't cause the erroneous module to be imported. I've refactored this in #12604.

**Comment by kt3k** [comment]
Thank you for working on this @nayeemrmn I think this issue is quite serious..

**Comment by shinshin86** [comment]
@kitsonk I see. Thank you for confirming the issue.

**Comment by shinshin86** [comment]
It also gave me a good overview of the problem.
The CLI tool that I am currently creating in Deno is experiencing a similar problem and I was having trouble, so it was good to understand the overview of the problem.

I hope this issue will be resolved.
Thank you for the working!

**Comment by BotFessor** [comment]
I'm facing a similar issue.  Deno v1.38.0. This code snippet
`interface Person {
    name: string;
    age: number;
}

const users = function(person: Person) {
    console.log(person.name);
}


users({name: 854, age: 15});`
should fail.
when I run `deno run index.ts` , it spits 854 yet the property name of type Person expects a string.
running `deno run --reload index.ts` has no impact at all.

But when I run 
`deno compile index.ts` it behaves well, 

`PS D:\liberty> deno compile index.ts
Check file:///D:/liberty/index.ts
error: TS2322 [ERROR]: Type 'number' is not assignable to type 'string'.
users({name: 854, age: 15});
       ~~~~
    at file:///D:/myCode/index.ts:11:8

    The expected type comes from property 'name' which is declared here on type 'Person'
        name: string;
        ~~~~
        at file:///D:/myCode/index.ts:2:5`

and this is what I expected when I run the `deno run index.ts` command.
Any idea what I need to do?

**Comment by bartlomieju** [comment]
You need to run `deno run --check` or `deno check`.
