### ISSUE TITLE
Body not being set to `null` when there is no body for certain methods

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#12741]
In 1.16.0 any `Request` that didn't have a body was set to `null` irrespective of the method.  As of 1.16.1, requests that do not have a body for verbs like `DELETE` and `OPTIONS` contain a set body in the request, which is a significant breaking change in behaviour.

```js
const server = Deno.listen({ port: 8085 });

for await (const conn of server) {
  (async () => {
    const httpConn = Deno.serveHttp(conn);
    for await (const requestEvent of httpConn) {
      if (requestEvent.request.body) {
        console.log(`request ${requestEvent.request.method} has body`);
      } else {
        console.log(
          `request ${requestEvent.request.method} does not have body`,
        );
      }
      requestEvent.respondWith(
        new Response(null, { status: 204, statusText: "NoContent" }),
      );
    }
  })();
}
```

And then if you do a couple curls, like:

```
curl --request GET http://localhost:8085
curl --request OPTIONS http://localhost:8085
curl --request DELETE http://localhost:8085
```

You will see an output like:

```
request GET does not have body
request OPTIONS has body
request DELETE has body
```

According to the [spec](https://fetch.spec.whatwg.org/#body-mixin):

> The body getter steps are to return null if this’s body is null; otherwise this’s body’s stream.

Ref: oakserver/oak#430

**Comment by c0per** [comment]
I find this bug still exists in deno v1.16.1

**Comment by lucacasonato** [comment]
@kitsonk I can reproduce the change in behaviour, however fixing this actually fixed a HTTP/1.1 vs HTTP2 incompatibility. In the case of the OPTIONS and DELETE requests, there is a body, it just has length 0. Previously (before v1.16.1), HTTP/1.1 requests only had a `.body` property set if the body length was larger than 0. For HTTP/2, the `.body` property was always set for OPTIONS and DELETE requests.

The `.body` being `null` means that the request does definitely not have a body (this is the case for GET requests for example). The `.body` being set, means that there is a body, but it could be of length 0.

**Comment by kitsonk** [comment]
Hrmmmm... not ideal for a patch release, but it is what it is. I will look into it more from an oak perspective and see what the best way to handle it.

**Comment by rracariu** [comment]
This kind of fix should never be part of a . release. The fact that the major version works, but you update to patch and then all your stuff breaks is not great...

**Comment by piscisaureus** [comment]
Discussed off-github: unfortunate as it is that this change was introduced in a a patch release, we think that in the long term this is the desirable behavior, so we are not going to land a patch to revert to pre-1.16.1 behavior.
