### ISSUE TITLE
Suggestion: Allow restricting the arguments a script can start another program with

### ISSUE THREAD

**Issue by clo4** [denoland/deno#12756]
## What?

It would be useful to specify arguments that a program can be run with, in addition to specifying the runnable programs.

## Why?

An example for why this is useful is the Deno CLI itself:
`--allow-run=deno` allows the script to run _literally any other script_ with any permissions it wants, but if the only thing you want to use it for is `deno fmt` then that's a lot more permission than it should have. Something like `--allow-run='deno fmt'` gives confidence that the program you're running really _is_ only allowed to format files (see 'Problems' below re: syntax).

```javascript
await Deno.permissions.request({
  name: "run",
  command: ["deno", "fmt"],
});

Deno.run({
  cmd: ["deno", "fmt", "--config", "deno.jsonc"]
  //            ^^^^^^-- any other second argument is disallowed
});
```

## Problems

The most major issue is that since it's, y'know, 2021, paths can have spaces.

- `--allow-run='deno fmt'` currently means the script can Deno.run `["deno fmt", /* ... */]`, and changing this would technically be breaking backwards compatibility.
- `--allow-run=deno,fmt` means the program has permission to run `["deno"]` and `["fmt"]`.
- Ugly syntax, but `--allow-run=[deno,fmt]` is still technically breaking compat but is _very_ unlikely to _actually_ break anything. It would also require more work to parse.

**Comment by dsherret** [comment]
Perhaps #13041 would solve this use case?

**Comment by SeparateRecords** [comment]
Once the proposal has been expanded a little to also allow running things like the formatter and linter, it will indeed solve my particular example! 😀

Just for clarity though, it doesn't resolve the core issue. Allowing `npx` and `npx run eslint` are very different in terms of their scope.

**Comment by lucacasonato** [comment]
We are not going to do this. Our `run` permissions are already complex enough. We may revisit this in the future, if we allow dynamic permission checks through some supervisor JavaScript (a'la seccomp).
