### ISSUE TITLE
lsp: Broken auto completion / suggestions

### ISSUE THREAD

**Issue by DreamTexX** [denoland/deno#12753]
**Describe the bug**
It's a bit hard to describe the issue so I will append a video for better understanding.
I just moved from deno 1.15.3 to 1.16.1 and auto-completion is kinda broken. On code that I've written like a week ago, it shows auto-completion, but on code, I write today it doesn't come up with suggestions, they first appear when I explicitly start writing some method name or variable name. I use the same class to test, on old variables it shows completion on new instances of this class (new variables also) it doesn't suggest any methods (see the video appended).

**To Reproduce**

1. Install deno 1.16.1
2. Check auto completion on code that was already written
3. Create a new instance of a class or something
4. write `yourInstanceVariable.` and press the shortcut to show suggestions

**Expected behavior**

It should show class methods and variables in the suggestions.

**Screenshots**

https://user-images.githubusercontent.com/20863419/141652487-9b9a076f-4eab-4411-a9d9-1ab07ffc4ff1.mp4

**Versions**

vscode: 1.62.2 deno: 1.16.1 extension: 3.9.2

**Comment by yacinehmito** [comment]
I am experiencing the same issue. Let me know how I can help.

**Comment by yacinehmito** [comment]
@kitsonk I ran a `git bisect` and it told me the following commit introduced the regression: https://github.com/denoland/deno/commit/34a9ddff091950aee9d89915cd13944259e7d346

I'll continue to dig in.

**Comment by kitsonk** [comment]
Thanks @yacinehmito for the repo/test. The issue has to do with use "losing" the dependencies when we hit a parse error when the module is being typed out. Effectively we need to preserve the dependencies between changes to the document when the parse is invalid.

**Comment by yacinehmito** [comment]
Thank you very much.
