### ISSUE TITLE
Import Assertion-Based Loading of FFI Libraries

### ISSUE THREAD

**Issue by sno2** [denoland/deno#12770]
Hello, it would be nice if Deno could make use of the [import assertions proposal](https://github.com/tc39/proposal-import-assertions) with its FFI system.  This would not only allow for static analysis of FFI binaries, but also a more elegant syntax than the synchronous [`Deno.dlopen` API](https://doc.deno.land/builtin/unstable#Deno.dlopen).

> Note: the assert type (`"deno-dl"`) that I have is simply for dummy purposes.  I advise there is more planning about the identifier for FFI binaries in asserts.

## Behavior

There is no magic behavior based on the platform (from `Deno.build.os`).  Therefore, if you tried to load a windows binary (usually `.dll`) then it would throw an error on the import.

Here, let's say we tried to load a linux binary as a Deno dynamic library on windows:

```ts
import openLib from "./lib.so" assert { type: "deno-dl" }; // error: Failed to load FFI binary.
```

The type of a correctly loaded FFI module would be a function that takes in the symbols and then asynchronously returns the [`DynamicLibrary` type](https://doc.deno.land/builtin/unstable#Deno.DynamicLibrary).  Here's a definition in TypeScript-style format:

```ts
declare module "*" assert { type: "deno-dl" } {
  // note: the symbols type would include exact strings (i.e. "u32" | "u64" | ...) but this is just for example
  export default = (symbols: Record<string, { parameters: string[], result: string, nonblocking?: boolean }>) => Promise<Deno.DynamicLibrary>;
}
```

If it cannot find the given import, then it can give a similar error to if you tried to import a nonexistent js file.

Now, if you wanted to have an isomorphic FFI module in which you get the binary path from the platform, then all you need to do is use the dynamic `import` function and specify your assert in there:

```ts
const BINARY_PATH = {
  windows: "./lib.dll",
  linux: "./lib.so",
  darwin: "./lib.dylib"
}[];
const { default: openLib } = await import(BINARY_PATH, { assert: { type: "deno-dl" } });

const lib = await openLib({ // you can still call open lib as many times as you want
  // same stuff that is allowed within regular `Deno.dlopen`'s symbols
  world: { parameters: ["u32"], result: "i32" }
});
```

Although I still don't like the idea of first needing to load a binary first and then call the default function export, I think that this is still an improvement over `Deno.dlopen` for its asynchronous approach and an easier gateway to static analysis with regular imports.  Thanks

**Comment by bartlomieju** [comment]
Thanks for opening the issue, but this proposal is directly in contradiction to "import assertions" specification in that `type: "deno-dl"` changes how the import would be interpreted; import assertions should only be used to assert matching type. 

There's a follow up proposal that would allow to do that: https://github.com/tc39/proposal-import-assertions#follow-up-proposal-evaluator-attributes or https://github.com/tc39-transfer/proposal-import-reflection which @lucacasonato champions and might be better suited for this purpose. That said, it's still probably year(s) out.

**Comment by sno2** [comment]
> Thanks for opening the issue, but this proposal is directly in contradiction to "import assertions" specification in that `type: "deno-dl"` changes how the import would be interpreted; import assertions should only be used to assert matching type.
> 
> There's a follow up proposal that would allow to do that: https://github.com/tc39/proposal-import-assertions#follow-up-proposal-evaluator-attributes or https://github.com/tc39-transfer/proposal-import-reflection which @lucacasonato champions and might be better suited for this purpose. That said, it's still probably year(s) out.

Thanks for the info. I guess I'll close this until a draft makes this possible.
