### ISSUE TITLE
The DENO_DIR is not working

### ISSUE THREAD

**Issue by iflyee** [denoland/deno#12783]
[me@host dir]$ echo $DENO_DIR
/opt/apps/deno/cache
[me@host dir]$ deno info
DENO_DIR location: "/home/me/.cache/deno"
Remote modules cache: "/home/me/.cache/deno/deps"
Emitted modules cache: "/home/me/.cache/deno/gen"
Language server registries cache: "/home/me/.cache/deno/registries"
Origin storage: "/home/me/.cache/deno/location_data"

**Comment by kitsonk** [comment]
The output of `deno --version` please.

**Comment by iflyee** [comment]
> The output of `deno --version` please.

deno 1.16.1 (release, x86_64-unknown-linux-gnu)
v8 9.7.106.2
typescript 4.4.2

**Comment by dsherret** [comment]
@iflyee strange. Are you using a tool that manages your deno versions? Looking at the code, I'm not sure how this could happen unless something changes the environment before running the deno executable.

Do you get the expected directory when you run?

```ts
deno eval 'console.log(Deno.env.get("DENO_DIR"))'
```

**Comment by iflyee** [comment]
Sorry to bother you, I just found the word 'export' is missing in my env-setting-script. And now it works fine. Thanks for your reply. @dsherret
