### ISSUE TITLE
Executables created with `deno compile --target x86_64-unknown-linux-gnu` only launch a REPL

### ISSUE THREAD

**Issue by askonomm** [denoland/deno#12780]
I'm creating multiple executables for a CLI app created using Deno, for MacOS, Windows and Linux. MacOS works fine, Windows I can't unfortunately test myself, but the Linux executable seems to open a REPL instead of running my app:

```
./bacon-linux
$ Deno 1.16.1
$ exit using ctrl+d or close()
```

I create the executables using a Github Action [here](https://github.com/askonomm/bacon/blob/master/.github/workflows/main.yml). 

There are no error messages that I can find, just that instead of running my app it opens a REPL instead, whereas it works as expected on MacOS. The executables are created on a `ubuntu-latest` image on Github Actions, and am running the executable on Vercel which [according to the documentation](https://vercel.com/docs/concepts/deployments/build-step#build-image) uses Amazon Linux 2 image.

**Comment by askonomm** [comment]
I've figured out the problem, and apparently compressing the binary with [UPX](https://github.com/upx/upx) (basically zips the executable into a self-extracting binary) breaks it for whatever reason. As such, this problem is solved for me, but leaving open in case somebody wants to dig deeper into why UPX breaks it. For what it's worth, I've compressed binaries with UPX before and haven't had that (when using GraalVM to compile JAR's into native images).

**Comment by bnoordhuis** [comment]
My guess from scanning upx's source real quick is that it rewrites the executable, just like `deno compile` does.

Specifically, `deno compile` appends a magic marker at the end of the binary that upx removes/compresses. I don't think that can be fixed unless you can somehow persuade upx to leave the last `n` bytes alone.

(Look at `extract_standalone()` in `cli/standalone.rs` to calculate `n`. It's somewhat complicated.)

I'll take the liberty of closing the issue but let me know if there's reason to reopen.

**Comment by egfx-notifications** [comment]
Just leaving this here in case anyone gets here via a Google search as I did.

Packaging as RPM with `rpmbuild` results in the same problem as `rpmbuild` strips and compresses executables by default. Once this is disabled in the RPM spec file, the executable can be shipped as expected.

This is needed at the top of the spec file:
```
%global _enable_debug_package 0
%global debug_package %{nil}
%global __os_install_post /usr/lib/rpm/brp-compress %{nil}
```

And this at the top of the `%install` section:
```
export DONT_STRIP=1
```

See http://lists.rpm.org/pipermail/rpm-list/2013-August/001478.html

**Comment by MrFoxPro** [comment]
I'm facing same problem when building with Nix:
```nix
packages.api = pkgs.stdenv.mkDerivation rec {
  name = "api";
  src = ./api;
  __noChroot = true;
  __impure = true;
  nativeBuildInputs = with pkgs; [
    deno
    unzip
  ];
  buildPhase = ''
    export DENO_DIR=./.deno
    mkdir $DENO_DIR
    deno cache --reload --lock ./deno.lock --lock-write main.ts

    mkdir -p $out/bin
    deno compile -A --check --lock=deno.lock ./main.ts --cached-only --output $out/bin/${name} --target=x86_64-unknown-linux-gnu
  '';
};
```
Seems like Nix tries to patch executable, and 
adding `phases = [ "unpackPhase" "buildPhase" ];` fixes that. 
Why there are no self-checking mechanism?

**Comment by StarLederer** [comment]
@MrFoxPro you are correct, Nix builder patches the binary which breaks it and causes it to start a REPL instead of executing your script. I manually checked a patched VS unpatched binary using `patchelf`. Unfortunately not patching the binary means it cannot run on NixOS
