### ISSUE TITLE
Introduce Asynchronous Loading of FFI Libraries

### ISSUE THREAD

**Issue by sno2** [denoland/deno#12784]
Hello, the current FFI system is pretty nice to use and definitely better than nothing.  However, the synchronous nature of `Deno.dlopen` is quite limiting.  For example, I am currently working on a module to load pre-trained ML models (all through rust-bert).  However, the synchronous nature of the FFI module loading system is very limiting because to create an easy-to-use and fast ML library, I must create an allocator-like js class (e.g. store 3 models per ffi library) to create FFI libraries on the fly with `Deno.dlopen`.  This is because my FFI binary thread is blocked for every ML model due to my dynamic design (locks on a global `HashMap` for resources).   However, my library can't really just block the thread when it needs to create another ffi library as people may want to use my module in a http server where blocking the thread would be detrimental to the API.  Therefore, I'd like to propose replacing `Deno.dlopen` with an asynchronous `Deno.dlopen` and a `Deno.dlopenAsync` counterpart (similar to the fs and fs sync methods).

Here are TypeScript-esque type defs:

```ts
declare namespace Deno {
  export function dlopen(path: string, symbols: CURRENT_SYMBOLS_TYPEDEF): Promise<Deno.DynamicLibrary<_>>;
  export function dlopenSync(path: string, symbols: CURRENT_SYMBOLS_TYPEDEF): Deno.DynamicLibrary<_>;
}
```

I am willing to try and implement this if people agree.  Thanks

**Comment by bnoordhuis** [comment]
You're proposing to move the underlying dlopen(3) library call to another thread? The idea sounds good to me but it will confuse libraries that use thread-local storage.

I understand from your use case that it's not so much the loading of the library itself that is slow but the initializers that run right after? That's something you can fix in your library by moving the work to a background thread or deferring until it's needed.

**Comment by sno2** [comment]
> You're proposing to move the underlying dlopen(3) library call to another thread?

Yes

> The idea sounds good to me but it will confuse libraries that use thread-local storage.

But it's an unstable API.  Doesn't that mean it's ok to change? I mean, I kinda thought you signed that waiver by passing in `--unstable`.

> I understand from your use case that it's not so much the loading of the library itself that is slow but the initializers that run right after?

No, there are 50+ ML models that one could load so I have a dynamic resource system (similar to Deno's).  Therefore, the only thing being initialized are 3 instances of `once_cell::sync::Lazy`.

> That's something you can fix in your library by moving the work to a background thread or deferring until it's needed.


View my above statement.  Furthermore, all of the functions that are called from my library are asynchronous in Deno (via nonblocking property).

**Comment by bartlomieju** [comment]
> > The idea sounds good to me but it will confuse libraries that use thread-local storage.

> But it's an unstable API. Doesn't that mean it's ok to change? I mean, I kinda thought you signed that waiver by passing in --unstable.

These are tangential issues. It's not a matter if the API is stable or not; it means that libraries that use TLS might break in subtle ways if their loading is done off-the-main thread.

**Comment by sno2** [comment]
Yep, my main issue was trying to turn my ML library into a server.  I can't load dynamic libraries asynchronously so it won't return requests if you are running sync code.

**Comment by bartlomieju** [comment]
> Yep, my main issue was trying to turn my ML library into a server. I can't load dynamic libraries asynchronously so it won't return requests if you are running sync code.

Have you tried running your ML library in a worker thread? That way you move it off-the-main thread and communicate via message passing.

**Comment by lucacasonato** [comment]
> I can't load dynamic libraries asynchronously so it won't return requests if you are running sync code.

The thread will indeed be blocked during loading. But under the hood there is no way for us to "async" load a FFI library because of possible thread local storage in the library. If you want to load a library in a separate thread, I suggest you explicitly use a Web Worker.

**Comment by sno2** [comment]
> The thread will indeed be blocked during loading. But under the hood there is no way for us to "async" load a FFI library because of possible thread local storage in the library. If you want to load a library in a separate thread, I suggest you explicitly use a Web Worker.

Ok, thanks for the advice.  Sadly, that's seems quite janky and slow solution.

Would tokio's `block_on` not work here either?

**Comment by lucacasonato** [comment]
`block_on` creates a new thread under the hood. It essentially is the same as creating a web worker. Also note that web workers are not slow by any stretch of the imagination.

**Comment by sno2** [comment]
> `block_on` creates a new thread under the hood. It essentially is the same as creating a web worker. Also note that web workers are not slow by any stretch of the imagination.

Wouldn't `block_on` be a way to implement the async version then?  I think it would be _way_ better to use that internally than forcing people to use web workers.  

> Also note that web workers are not slow by any stretch of the imagination.

Isn't it slow to transmute JSON through web workers?  I mean then you gotta serialize and desetialize between messages.

**Comment by bartlomieju** [comment]
> Isn't it slow to transmute JSON through web workers? I mean then you gotta serialize and desetialize between messages.

When you pass a message between workers it uses https://developer.mozilla.org/en-US/docs/Web/API/structuredClone and it's fast.

**Comment by lucacasonato** [comment]
> I think it would be way better to use that internally than forcing people to use web workers.

It isn't. It hides significant complexity, and as said earlier, **does not work** for FFI that uses thread local storage.

Web Workers are not slow at all. Message passing between workers is not slow. See https://surma.dev/things/is-postmessage-slow/

**Comment by sno2** [comment]
> It isn't. It hides significant complexity, and as said earlier, **does not work** for FFI that uses thread local storage.

Oh, sorry, I thought that you meant that it could work when you said `block_on` would be the same as creating a web worker.

> When you pass a message between workers it uses https://developer.mozilla.org/en-US/docs/Web/API/structuredClone and it's fast.

Sorry for my misconception, I had thought that it was slow from looking at some people's benchmarks around the inter webs when I first got into deno a year ago.
