### ISSUE TITLE
Deno "unboxes" primitive "this" while Chrome and Node do not

### ISSUE THREAD

**Issue by mfulton26** [denoland/deno#12804]
**setup**
```js
function self() {
  return this;
}
```

**Chrome** and **Node**
```console
> self.apply("hello")
String {'hello'}
> typeof self.apply("hello")
'object'
```

**Deno**
```console
> self.apply("hello")
"hello"
> typeof self.apply("hello")
"string"
```

I like how Deno appears to intelligently "unbox" the object to a primitive but as this behavior differs from Chrome and Node it makes me wonder if there is some ES specification issue here or not (or maybe Chrome and Node have it wrong?)

should Deno behave differently than Chrome and Node here?

**Comment by andreubotella** [comment]
```js
function self() {
  "use strict";
  return this;
}
```

The above function will act like Deno above in all platforms. This is because Deno code runs ES modules, which use strict mode for everything, whereas Node and Chrome's REPL run scripts. This difference in behavior might be obscure, but it's not a bug.

**Comment by kitsonk** [comment]
In fact, we force the REPL to use strict for evaluation so it consistent with module evaluation.

**Comment by mfulton26** [comment]
Ah, I see. I was trying out the new dnt tool and some of my tests that passed in Deno failed in Node... maybe that tool isn't emitting `"use strict"` or something and can or should be. I will investigate. Thank you!
