### ISSUE TITLE
feature: Add reference to the source code which caused "error: Cannot load module "xxxx/file_code.ts""

### ISSUE THREAD

**Issue by danielfroz** [denoland/deno#12803]
I am testing deno and sometimes I find myself doing a small code refactor. 
While doing it, I forget to change file reference.... then the error the compile error is correctly shown.

```
error: Cannot load module "file:///path/to/file_code.ts"
```

Would be great if we can also see which code is referring to the wrong file...

So far I need to look for the error using the full code search over the IDE. Not a real problem but takes more time.

Here is the deno version output:
```
deno 1.16.1 (release, aarch64-apple-darwin)
v8 9.7.106.2
typescript 4.4.2
```

**Comment by bartlomieju** [comment]
CC @kitsonk @nayeemrmn

**Comment by nayeemrmn** [comment]
Should be the same error as  #12755 and #12807, fixed by deleting DENO_DIR.

**Comment by nayeemrmn** [comment]
Oops, I didn't read the issue properly. This is just about referrer info missing in some cases. Should be fixed in v1.16.2, referrer tracking is much more robust (#12604).

**Comment by bartlomieju** [comment]
@danielfroz please try with Deno 1.16.2 and tell us if the problem persists.

**Comment by danielfroz** [comment]
@bartlomieju deno 1.16.2 is working with the deno run command as expected.
However, once you add --watch to it... stops to identify the source code which references the missing code...

Example used for the test.
- bar.ts
```ts
export function foo(arg: string) {
  return `foo: ${arg}`
}
```
- main.ts
```ts
import { foo } from './foo.ts'
const result = foo('test')
console.log('result: %o', result)
```

Here is the output
```
$ deno run ./main.ts 
Check file:///t/main.ts
error: Cannot load module "file:///t/foo.ts".
    at file:///t/main.ts:1:21
$ deno run --watch ./main.ts
error: Cannot load module "file:///t/foo.ts".
Watcher Process failed. Restarting on file change...
```

**Comment by bartlomieju** [comment]
Thanks for checking, we'll look into it.

**Comment by nayeemrmn** [comment]
We need to append referrer info to each `graph.valid()?` error. This was already done for normal `prepare_module_load()` graph errors for separate reasons in #12604, which no longer uses `graph.valid()?` there. I need https://github.com/denoland/deno_graph/pull/63 for this.
