### ISSUE TITLE
Type inference for URLPattern

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#12802]
It should be possible to provide more rich type inference of `URLPattern.prototype.exec()` by using advanced typing features of TypeScript.

The [`@types/express`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/7d182347b9be493cd37ad26a0b7a8285310cc914/types/express-serve-static-core/index.d.ts#L108-L122) provides type inference on its router and recent [oak](https://github.com/oakserver/oak/blob/b85ffc3d48af6b0d6c3b3a37aa5142dbc068cffd/router.ts#L190-L202) does something similar.

**Comment by crowlKats** [comment]
I have explored this already a few times, but not much can be done given the complex patterns that can be created, including regex. having only partial type inference imo would be worse than none at all, as that would cause confusion

**Comment by crowlKats** [comment]
Closing due to being too complex.
