### ISSUE TITLE
feature request: support for null value in FFI buffer argument

### ISSUE THREAD

**Issue by DjDeveloperr** [denoland/deno#12809]
There's no way to pass a null pointer to a buffer argument in FFI right now. It would be great to support passing JS `null` value corresponding to a `nullptr` in FFI. I'm currently trying to use WinAPI which (of course) makes use of those.

I'd like to try work on this

**Comment by bartlomieju** [comment]
Could you provide an example that requires `nullptr` for the buffer argument?

**Comment by DjDeveloperr** [comment]
> Could you provide an example that requires `nullptr` for the buffer argument?

Specifically trying to use `ReadFile` in this case. https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-readfile

The `lpNumberOfBytesRead` argument is optional/nullable in case we're using overlapped IO.

![image](https://user-images.githubusercontent.com/43033058/142417008-1e100b37-d6b5-4a43-b92b-cac1bfc23993.png)
