### ISSUE TITLE
Websocket leaking async op

### ISSUE THREAD

**Issue by Peanets** [denoland/deno#12815]
Hi,

This test is leaking async operations, am i doing something wrong or is there an issue with websockets ?

```ts
Deno.test({
    name: "Test socket connection",
    fn() {
        const socket = new WebSocket("wss://demo.piesocket.com/v3/channel_1?api_key=oCdCMcMPQpbvNjUIzqtvF1d2X2okWpDQj4AwARJuAgtjhzKxVEjQU6IdCjwm&notify_self");
        return new Promise<WebSocket>((resolve, reject) => {
            const onError = (err: any) => {
                reject(err)
            }
            const onMessage = (msg) => {
                resolve(socket)
            }
            socket.addEventListener("message", onMessage)
            socket.addEventListener("error", onError)
        }).then(() => {
            return socket.close()
        })
    }
})
```

**Comment by lucacasonato** [comment]
In the `.then` you should wait for the socket to be actually closed by listening for the `close` event.

**Comment by Peanets** [comment]
Like this ? (It's still leaking and the socket is closed)
`
.then((socket) => {
            socket.close()
            return new Promise((resolve, reject) => {
                socket.addEventListener("close", () => {
                    console.log("closed")
                    resolve()
                })
            }) 
        })
`

**Comment by sno2** [comment]
@Peanets FYI, it looks like you included an API key in your question so anyone can now use it.  I advise you change the API key because even if you edit the comment then everyone will still be able to access the key from the comment edit history.

**Comment by Peanets** [comment]
Thanks for the heads up, I don't really care about this api key. I was looking for an open ws server on google to provide a reproducible test case, that's the closest I found 🙂

**Comment by sanfusu** [comment]
https://github.com/denoland/deno/pull/10365#issuecomment-831189821

**Comment by crowlKats** [comment]
@sanfusu Thats unrelated. that is for websocketstream, not websocket. Also in the end that comment was fixed in the same PR.

**Comment by sanfusu** [comment]
> @sanfusu Thats unrelated. that is for websocketstream, not websocket. Also in the end that comment was fixed in the same PR.

Ok, I get it.

**Comment by retog** [comment]
Shouldn't the close method (https://github.com/denoland/deno/blob/995d1666ffe44c5f8694f9ef43390ca3ab64bb26/ext/websocket/01_websocket.js#L327) invoke

    clearTimeout(this[_idleTimeoutTimeout]);

like it does, when the remote end closes the connection??

**Comment by bartlomieju** [comment]
@crowlKats please take a look

**Comment by crowlKats** [comment]
@retog that is unrelated. it is handled in https://github.com/denoland/deno/blob/995d1666ffe44c5f8694f9ef43390ca3ab64bb26/ext/websocket/01_websocket.js#L430-L431

**Comment by crowlKats** [comment]
@Peanets I just tested against latest main (you can run it with `deno upgrade --canary`), and seems if it now fixed. could you confirm?

**Comment by crowlKats** [comment]
Closing as it seems fixed now.
