### ISSUE TITLE
UDP api reliability

### ISSUE THREAD

**Issue by traceypooh** [denoland/deno#12822]
I'm having a hard time getting UDP in/out of deno reliably (insert UDP jokes :) )

TEXT:
for text files in/out, I seemed to have to clamp down to a specific 2048 bytes length, after noticing what seemed like exactly half of the data wasn't coming out the other end (w/ the default 1024 buffer I was seeing).

```
const N = 2048
const buff = new Uint8Array(N)
const l = Deno.listenDatagram({transport:'udp', hostname:'xxx.xxx.xxx.xxx', port:34500})
const fh = Deno.openSync('out', { append: true, create: true })
while (1) { 
  const r = await l.receive(buff)
  fh.writeSync(r[0], N))
} 
fh.close()
```

Doing that, at least, seemed to make byte-for-byte identical output file as the input, via
`cat ascii.txt | nc -u xxx.xxx.xxx.xxx 34500`

I wasn't able to get the `for await (const r of l)` style alternate to work 100% reliably for text with anything I was trying.
Each time, the buffer output the other end seemed truncated in some fashion.

BINARY:
And so far, I'm not having luck getting binary data in/out 100% reliably.

(I'm hoping to move the final pieces of a 30,000 line JS A/V & TV repo to Deno -- UDP binary (massive) data from recorders is my final hurdle).

TIA for any thoughts, corrections, etc.
PS: using deno 1.15.2, unix xenial

**Comment by bartlomieju** [comment]
@traceypooh can you confirm that you actually receive expected data from UDP socket but it is truncated in the file? If so then most likely the issue is:
```
fh.writeSync(r[0], N))
```
As per https://doc.deno.land/builtin/stable#Deno.writeSync it's not guaranteed that the whole buffer will be written in a single call - the API returns the number of bytes that were actually written. To ensure all data is written you might want to use `writeAllSync` helper available in `deno_std`: https://deno.land/std@0.115.1/streams/conversion.ts#L383

**Comment by bartlomieju** [comment]
Also as per [Tokio's docs on UDP socket](https://docs.rs/tokio/1.14.0/tokio/net/struct.UdpSocket.html#method.recv_from):

> The function must be called with valid byte array buf of sufficient size to hold the message bytes. If a message is too long to fit in the supplied buffer, excess bytes may be discarded.

The same rules apply to Deno's `DatagramConn.receive()` API.

**Comment by traceypooh** [comment]
thanks, great point!

I was logging the return value of `writeSync()` each time, and it was showing the expected/intended number of bytes out.

Switching to `writeAllSync()` i'm still seeing major missing data in binary land -- and pegging the buffer to 2048 for text is still working.

**Comment by bartlomieju** [comment]
> Switching to `writeAllSync()` i'm still seeing major missing data in binary land -- and pegging the buffer to 2048 for text is still working.

That's disconcerting, I'll be glad to help debug, can you provide some more context on the situation with binary data? (Preferably and actual excerpt from the code if that's possible).

**Comment by traceypooh** [comment]
i just can't seem to find any kind buffer size to get all the data in/out ok.

(this is a glorified UDP receiver, writing to 1 minute chunks on disk).

but i'm "unit testing" it, after was noting two firehoses, 1 streaming to node, 1 to deno, I was missing ~2% of the data.

So what i've been doing at this point, is simply on the command-line with "one-liners":

```
rm -fv out; deno eval --unstable "import {writeAllSync} from 'https://deno.land/std@0.115.1/streams/conversion.ts'; const N=4000000; const buff=new Uint8Array(N); const l=Deno.listenDatagram({transport:'udp',hostname:'x.x.228.33',port:34500}); const fh = Deno.openSync('out', { append: true, create: true }); while (1){ const r = await l.receive(buff); writeAllSync(fh, r[0]) } fh.close()"
```

```
 cat ~/av/bin/ffmpeg |nc -u x.x.228.33 34500
```

then when i compare the filesizes after, they vary wildly:
```
> ls -l out ~/av/bin/ffmpeg
-rwxr-xr-x 1 tracey petabox 36293608 Nov  7 19:42 /home/tracey/av/bin/ffmpeg*
-rw-r--r-- 1 tracey petabox  7581696 Nov 20 00:43 out
```

I've been varying the `N` value above all over the place, and the resultant filesize changes but it seems so far, pretty chaotic.

**Comment by traceypooh** [comment]
OK, this is slightly encouraging at least...

If i cut the file up in 2048 chunks and pipe it to `nc`, and use N=4096 for the deno side buffer size, I got identical binary data out.

( `bytes` as a small handy utility C program I wrote to make it easier than `head -c ... | tail -c ...` type alternatives )
```
A=0; ( while true; do let B="A+2047"; bytes ~/av/bin/ffmpeg $A $B; let A="B+1"; ; done ) | nc ..
```

**Comment by traceypooh** [comment]
I don't think I have much ability to vary the UDP output buffer size from the tuners I'm using.  And they push UDP directly to an IP/port (so trying to logically insert a small shim to rebuffer wouldn't make any sense -- might as well use a 20 line perl (yuck) script to read UDP and write to disk.

For reference, tuners are emitting at ~4MB/sec binary data.

**Comment by bnoordhuis** [comment]
2% data loss at 4 MB/s doesn't seem out of the ordinary to me.

Are you seeing better numbers with other programs? That might indicate Deno is a slow receiver, causing the kernel to drop incoming datagrams. You should see that reflected in ifconfig's TX counters.

**Comment by traceypooh** [comment]
so node JS, perl, and php all seem to be able to get the full amount of data, for reference.

what's kind of telling is dumping a simple, small text file in (albeit "quickly") that is beyond the inferred stock buffersize, causing up to 50% of the data to be missing.

now, as @bartlomieju pointed out: "The function must be called with valid byte array buf of sufficient size to hold the message bytes. If a message is too long to fit in the supplied buffer, excess bytes may be discarded."
and that explains things a bit.

but if i ensure that the buffer size is always greater than the input file/stream, i'm still seeing issues, more so on linux (both xenial and focal) than mac (but I can see issues there, too).

thanks for the `ifconfig` pointer @bnoordhuis !  one of our ops people showed me that awhile ago. 
even showing the issues, i'm not seeing any kind of errors:
```
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 207.241.224.5  netmask 255.255.240.0  broadcast 207.241.239.255
        inet6 fe80::5054:eff:fe53:ee37  prefixlen 64  scopeid 0x20<link>
        ether 52:54:0e:53:ee:37  txqueuelen 1000  (Ethernet)
        RX packets 6938208897  bytes 2955652615998 (2.9 TB)
        RX errors 0  dropped 4613584  overruns 0  frame 0
        TX packets 1812386910  bytes 1345955420290 (1.3 TB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 183339669  bytes 16526144744 (16.5 GB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 183339669  bytes 16526144744 (16.5 GB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

I'm finding the issue between 110000 and 120000 input bytes -- where it seems like no buffer size will work for me, with these 2 command-line commands:
UDP listener:
```
rm -fv out; deno eval --unstable "const N=500000; import {writeAllSync} from 'https://deno.land/std@0.115.1/streams/conversion.ts'; const buff=new Uint8Array(N); const l=Deno.listenDatagram({transport:'udp',hostname:'127.0.0.1',port:34500}); const fh = Deno.openSync('out', { append: true, create: true }); while (1){ const r = await l.receive(buff); console.log(r[0].length); writeAllSync(fh, r[0], N); } fh.close()"
```

input file of repeat 0s; send to receiver:
```
dd if=/dev/zero of=in  bs=120000 count=1
cat in | nc -u 127.0.0.1 34500
```

I'm only seeing 114688 of 120000 bytes in the `out` file.
Things get worse (for me) as the `in` file size increases, even w/ a buffer size (`N` above) always bigger than the input filesize (just in case -- in practice, I haven't seen more than 16384 bytes used in the buffer).

**Comment by traceypooh** [comment]
** BAD SCIENCE ALERT ** :) 
OMG.  big time update.

So the missing end packets was really bothering me, so I thought I'd write the perl UDP receiver script, run the same `nc` netcat to it (above) and verify perl gets everything.  To my horror, it wasn't.  Wait, what?  How the heck is my node equivalent JS getting 2% more packets _consistently_ from the TV tuners, anyway?    But I _am_ now getting full parity (on average) about the same number of bytes w/ a tuner test of same firehose to `deno` JS equivalent, as the node now.

So the perl thing was a shock -- nothing seemed to get all the bytes out.  I wondered if there were some kind of linux UDP buffer sizes/limits going on (since I didn't see this behaviour on mac).

Turns out, indeed there was, so OMG so sorry we could close this issue.

Here were my settings before:
```
sysctl net.core.rmem_default net.core.rmem_max    
net.core.rmem_default = 212992
net.core.rmem_max = 1048576
```
I updated them both to 25MB:
```
sudo sysctl -w net.core.rmem_max=26214400
sudo sysctl -w net.core.rmem_default=26214400
 ```

And now with no other changes -- I'm now getting lots of unreliable messages reliably :) 

Up to you if maybe some link to something like this: 
https://medium.com/@CameronSparr/increase-os-udp-buffers-to-improve-performance-51d167bb1360 
as a cautionary note/tale for linux UDP users for anything beyond simple text line-based very small demos?

Thanks so much for the eyes and feedback - and so sorry it ended up being something else.

In terms of deno -v- node, I'm not sure if node is doing something different under-the-hood w/ UDP buffering, backlog, etc.

But for my repo, w/ a legacy 'node' branch, I **do** have this tweak -- which I wasn't able to find an equivalent in `deno` -- so had it commented out with a "fixme / revisit" in my 'main' branch

```
    // OK, so *sometimes* we could see pileup of UDP packets in the socket
    // where we cant get to them fast enough.  so make the max bufferable size
    // of UDP packets *in the socket* (so kernel writes to socket, and we in
    // user space are reading from it) to be *much* bigger (~16MB)
    // const socket = dgram.createSocket({ type: 'udp4', recvBufferSize: 16000000 }) // xxxd
```

Thank you thank you for the support and amazing deno.  This is the final last piece of code I haven't been able to port to deno (but now I can!) -- with just 2 other areas I'm doing final testing on before they go fully live.

But the vast majority of 30,000 lines (mostly backend) of JS is all otherwise in active use and doing very very well!  :)

**Comment by bartlomieju** [comment]
@traceypooh thank you for the update! Glad that you were able to resolve the problem and super happy to hear you can migrate your big project to Deno. If you are interested in adding something like `recvBufferSize` to the `Deno.listenDatagram` API please open a new issue.

**Comment by traceypooh** [comment]
perfect, thanks!   I'll open that soon I want all linux users to have a great experience w/ the deno UDP capabilities. 
(as a postscript, switched all my tuner UDP consumers to deno, and they're working flawlessly in production).

  🙇‍♀️  🙏
