### ISSUE TITLE
`deno coverage` umbrella issue

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#12826]
Umbrella issue for all the reported quirks and suggestions to `deno coverage`:

- [ ] #9669
- [x] #9747
- [x] #9754
- [ ] #9865
- [x] #10395
- [x] #10531
- [x] #11327
- [ ] #11560
- [x] #12112
- [x] #11875 
- [x] #12751
- [x] #10944
- [x] #12126
- [x] #10420
- [x] #10936
- [x] #13111
- [x] #13323
- [x] #13310
- [x] #13326
- [x] #13161

**Comment by zandaqo** [comment]
Also these two likely related issues with accuracy where testing individual files shows different coverage to testing multiple files:
- [ ] #11875 
- [ ] #12751

**Comment by bartlomieju** [comment]
Thanks @zandaqo I added them to the list.

**Comment by rivy** [comment]
Not stale.

**Comment by rivy** [comment]
Not stale.

**Comment by rivy** [comment]
Just FYI, line counts and branch detection are still broken today with the most recent Deno (v1.30.0); see #9865.

**Comment by lowlighter** [comment]
Adding
- #13206
