### ISSUE TITLE
Date.parse() parses not existing dates

### ISSUE THREAD

**Issue by Platzer** [denoland/deno#12820]
Running deno `1.15.3` on windows when using Date.parse() it parses not existing dates, where it should result in `NaN`:
```
PS > deno 
Deno 1.15.3
exit using ctrl+d or close()
> Date.parse('2021-02-31')
1614729600000
>
```

**Comment by crowlKats** [comment]
This is V8 behaviour, not deno. Chrome does the exact same thing

**Comment by Platzer** [comment]
🤦‍♂️ sorry tested with Firefox, I'll work around.
