### ISSUE TITLE
Proposal: `Deno.UnsafePointer` and `UnsafePointerView` API

### ISSUE THREAD

**Issue by DjDeveloperr** [denoland/deno#12824]
I propose adding two new classes: `UnsafePointer` and `UnsafePointerView` to the Deno namespace. The name itself would suggest that it is unsafe (inspired from [Swift](https://developer.apple.com/documentation/swift/unsafepointer)). This introduces a unified interface for passing/returning raw pointers to/from FFI, also a view class over the pointer (such as `DataView`) to perform read-related operations on the pointer. Of course, using this needs `--allow-ffi` permission.

```ts
type PointerOffset = number | bigint;

declare class UnsafePointer {
  constructor(value: bigint);

  /**
   * Return direct pointer to the Uint8Array in memory.
   */
  static of(buffer: Uint8Array): UnsafePointer;

  /** 
   * Returns the value of the pointer. 
   * This would allow pointer arithmetic which is useful in certain scenarios. 
   */
  valueOf(): bigint;
}

declare class UnsafePointerView {
  pointer: UnsafePointer;

  constructor(pointer: UnsafePointer);

  getUint8(offset?: PointerOffset): number;
  getInt8(offset?: PointerOffset): number;
  getUint16(offset?: PointerOffset): number;
  getInt16(offset?: PointerOffset): number;
  getUint32(offset?: PointerOffset): number;
  getInt32(offset?: PointerOffset): number;
  getBigUint64(offset?: PointerOffset): bigint;
  getBigInt16(offset?: PointerOffset): bigint;
  getFloat32(offset?: PointerOffset): number;
  getFloat64(offset?: PointerOffset): number;
  getCString(offset?: PointerOffset): string;
  getArrayBuffer(byteLength: number, offset?: PointerOffset): ArrayBuffer;
  copyInto(destination: Uint8Array, offset?: PointerOffset): void;
}
```

I didn't include writing to pointers because that's unsafe on another level. Most use-cases won't even need that.

### Usage

This would work along side the current `buffer` FFI type. For passing buffers, both `UnsafePointer` and `Uint8Array` would be allowed with the `buffer` argument type, while `buffer` as a result type would always return `UnsafePointer`.

### Fixes

- https://github.com/denoland/deno/issues/12456
- https://github.com/denoland/deno/issues/12752

Being implemented by #12828

**Comment by eliassjogreen** [comment]
I think the `buffer` argument type should be kept as to allow passing `TypedArray`s directly without creating an `UnsafePointer` object first but should instead accept the typescript types `TypedArray | UnsafePointer` a bit like #12828 now accepts `TypedArray | number`. For result types i think the `buffer` type should always return a `UnsafePointer`.

**Comment by DjDeveloperr** [comment]
@eliassjogreen sounds good to me, updated the proposal with that

**Comment by DjDeveloperr** [comment]
Implemented by https://github.com/denoland/deno/pull/12828

**Comment by exe-dealer** [comment]
why not just implement get* methods directly on UnsafePointer?
