### ISSUE TITLE
New branching and release approach

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#12827]
Discussed offline with @bnoordhuis, writing down notes, so everyone is one the same page.

Deno has a monthly release cycle: every month we cut a new minor version (`1.XX.0`), and in between minor releases we usually do 2 or 3 patch releases (`1.XX.Y`). Most of the time there are only 2 patch releases (after one week from minor, and after two weeks from minor); after that we open a "merge window" for new features for the upcoming minor release. This model has worked out well, however it's not without drawbacks, namely: feature PRs that are ready (approved and CI is green) often have to "stew" for at least two weeks before being merged. This often requires to rebase the PR putting additional work on contributors and maintainers. There's also a thesis that we should release every week, ie. do a total of 4 releases in a month - one minor and three patch.

So hereby we propose to change our branching model and release schedule:
1. Start merging all PRs into the `main` branch as soon as they are ready; doesn't matter if it's a "feature" PR or a "fix" PR
2. After releasing a new minor version (`1.XX.0`) from the `main` branch, fork a branch off of the `main` branch, ie. create `v1.XX` branch
3. After merging a "fix" PR to the `main` branch, merge it back to the minor branch (`v1.XX`)
4. For 3 weeks after a minor version, release a patch version from the `v1.XX` branch
5. Next month create a new minor release from the `main` branch, and `v1.XX` branch becomes inactive
6. Repeat from point 2.

This proposal should allow us to keep a "train release model" (ie. we release every week no matter what); as well as it should speed up merging of PRs that are ready and approved without having to wait for so called "merge window" to open.

Open questions that need to be validated before we switch:
- are tagged releases from `v1.XX` branch work as expected (ie. will they properly upload produced binary artifacts, or do we need to update CI scripts, I'm 95% sure that CI scripts need to change)
- are canary release from `main` branch work as expected (I'm 95% sure they will, as nothing changes from the current situation)

**Comment by bnoordhuis** [comment]
https://github.com/denoland/deno/pull/12920 - example of back-porting/cherry-picking a fix from main to v1.16.

I suggest the following workflow:

1. merge fix to main

2. immediately open and merge back-port PR to release branch; queuing them up is just inviting merge conflicts

The back-port PR doesn't need to be re-reviewed so sign-offs should be _pro forma_ / rubberstamp LGTMs.

If there is some way of lifting the "at least one LGTM" restriction for branches other than main, I suggest doing that, because it's just ceremony.

**Comment by bartlomieju** [comment]
We've been using this approach for the past 2 weeks. I'm going to close this issue now.
