### ISSUE TITLE
panicked at 'internal error: entered unreachable code: unexpected missing emit

### ISSUE THREAD

**Issue by maxburs** [denoland/deno#12832]
Running `deno run ./test.ts` creates this output:

>[0m[32mCheck[0m file:///Users/maxwellburson/workspace/benchmarkTest/test.ts
>thread 'main' panicked at 'internal error: entered unreachable code: unexpected missing emit: https://deno.land/x/fetchbase64@1.0.0/src/local.ts', cli/proc_state.rs:544:15
>stack backtrace:
>   0:        0x1051bccd8 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha47ac0a9192e239e
>   1:        0x104c4ab54 - core::fmt::write::hfbe6a7b828c32513
>   2:        0x1051b08a4 - std::io::Write::write_fmt::h34cd061a987d18fd
>   3:        0x1051b18d0 - std::panicking::default_hook::{{closure}}::h2b5c2a08263c3d54
>   4:        0x1051b1568 - std::panicking::default_hook::h0572aa020dd71058
>   5:        0x104c157c0 - deno::setup_exit_process_panic_hook::{{closure}}::he251a6b398b7f383
>   6:        0x1051b2268 - std::panicking::rust_panic_with_hook::h36a6e8d335334d30
>   7:        0x1051bd090 - std::panicking::begin_panic_handler::{{closure}}::h71decad72c0b1843
>   8:        0x1051bd010 - std::sys_common::backtrace::__rust_end_short_backtrace::hfd636421a82c4798
>   9:        0x1051b1d50 - _rust_begin_unwind
>  10:        0x10617f2e0 - core::panicking::panic_fmt::hebdff93de232aa26
>  11:        0x104a8ea68 - deno::proc_state::ProcState::prepare_module_load::{{closure}}::hdc42434c8ad65bc5
>  12:        0x104a8cefc - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h2a46327fed52214f
>  13:        0x104a8cd34 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h6b81a4cf63517ed8
>  14:        0x1049fc2c8 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h6fa4f6199afd8720
>  15:        0x1049fb41c - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h1025300baad02af4
>  16:        0x104aae604 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h148a380254dc526c
>  17:        0x104aacab4 - deno::run_command::{{closure}}::h72484fc8c377f6dc
>  18:        0x104aabe44 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h45912926a885511f
>  19:        0x1049dfc7c - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h9418c5697b011832
>  20:        0x1049d5e40 - deno::main::h0532f6ec18a4c124
>  21:        0x1049d2c40 - std::sys_common::backtrace::__rust_begin_short_backtrace::h9a39dbb11315ea1b
>  22:        0x1049d2e88 - _main

## test.ts

> import Graph from 'https://deno.land/x/deno_chart/mod.ts';
> 
> const graph = new Graph({
>   titleText: 'Uptime',
>   xAxisText: 'Hours',
>   yAxisText: 'Day',
>   
>   yMax: 50,
>   bar_width: 25,
>   graphSegments_X: 18,
> 
>   xTextColor: 'rgba(255,255,255,1)',
>   xSegmentColor: 'rgba(255,255,255,0.5)',
>   yTextColor: 'rgba(255,255,255,1)',
>   ySegmentColor: 'rgba(255,255,255,0.5)',
> 
>   // Verbose Logging (Optional)
>   verbose: true,
> });
> 
> // Random Bar Generation with Colors!
> const COLORS = [
>   '#345C7D', '#F7B094', '#F5717F', '#F7B094',
>   '#6C5B7A',
> ]
> 
> for (let i = 0; i < 12; i++) {
>   const clr = COLORS[Math.floor(Math.random() * COLORS.length)];
>   const y = Math.floor(Math.random() * 50);
> 
>   graph.add({
>     val: i,
>     label: y.toString(),
>     color: clr,
>   });
> }
> 
> // Draw to Canvas Context & Save png image
> graph.draw();
> graph.save('image.png');
> 

## Machine info

deno 1.16.2

ProductName:    macOS
ProductVersion: 12.0.1
BuildVersion:   21A559

It's one of the new M1 macs

**Comment by MierenManz** [comment]
Try to purge your deno cache `deno info` command should provide the right directory. Let us know if this issue persists after that.
