### ISSUE TITLE
Make sure Isolate instances are pinned

### ISSUE THREAD

**Issue by F001** [denoland/deno#1284]
There are a few unsafe code involved underneath `Isolate` type. Therefore several additional constraints are introduced. We have expressed most of them in the Rust's type system. The lifetime of `Isolate` is associated with that of underlying `DenoIsolate`. However, there is a missing piece of the whole picture: the object of `Isolate` should not move after any message is sent/received.

The reason is that we passed the address of `Isolate` all around the world, and assumed it is a valid object when the raw pointer is converted back. This design implied that the object can not move to another place. This requirement fits super well with the upcoming `Pin` type. Please see https://github.com/rust-lang/rust/issues/55766.

After `Pin` type is stabilized, I would like to change all the methods' receivers of `Isolate` to `Pin<&Self>`, like below:

```rust
impl Isolate {
  pub fn new(...) -> Pin<Box<Self>> {}
  pub fn as_raw_ptr(self: Pin<&Self>>) -> * const c_void {}
  ...
}
```
All these fancy designs in Rust are good for **encapsulation**. As library developers, whatever we don't want users to misuse, we'd better express them in the source code, to utilize the builtin static analysis capability to say hard "no" to users.

**Comment by bartlomieju** [comment]
CC @ry PTAL if this issue is still relevant

**Comment by ry** [comment]
Likely this is still an issue. I will assign @piscisaureus as he is thinking about these issues.

**Comment by bartlomieju** [comment]
We completely rewritten `Isolate` and plan to introduce more changes in coming weeks, closing as stale
