### ISSUE TITLE
es module imports in repl don't work

### ISSUE THREAD

**Issue by xiaodeaux** [denoland/deno#1285]
When in the Deno REPL and executing:
`import { env } from "deno";`

The output is:
`SyntaxError: Unexpected token {`

Probably related to #1158 

Executing: `deno -v` on the commandline returns:
`deno: 0.2.1`
`v8: 7.1.302.4`
`typescript: 3.2.1`

**Comment by hayd** [comment]
Typescript isn't supported in the repl yet, #1158.

**Comment by kitsonk** [comment]
That isn't a TypeScript feature persay... `import` is valid ES6 syntax.  But imports in general don't work in the REPL, which is a known limitation.  Native ESM support is being worked on (tracked by #975) and it should flow through to the REPL eventually.

The `deno` namespace though is available in the global scope, so `const { env } = deno;` would work for now.

**Comment by shreeve** [comment]
Now that #1460 (ES module support) has landed, can someone provide a quick line that can be entered in the REPL to verify that the import statement is working?

I'm still seeing this, even with the new support from #1460 that just landed:

```
> import { env } from "deno";
SyntaxError: Unexpected token {
```

Executing: `deno -h` on the commandline returns:

```
deno -h
Usage: deno script.ts

Options:
        --allow-write   Allow file system write access.
        --allow-net     Allow network access.
        --allow-env     Allow environment access.
        --allow-run     Allow running subprocesses.
    -A, --allow-all     Allow all permissions
        --recompile     Force recompilation of TypeScript code.
    -h, --help          Print this message.
    -D, --log-debug     Log debug output.
    -v, --version       Print the version.
    -r, --reload        Reload cached remote resources.
        --v8-options    Print V8 command line options.
        --types         Print runtime TypeScript declarations.

Environment variables:
        DENO_DIR        Set deno's base directory.
```

The latest version in git shows the prior version number, but the `--allow-all` option shows that it's using the newest code (which includes support for ES modules).

**Comment by kyranet** [comment]
I believe this kind of imports will never be available in REPL since ES imports/exports are static. However, you can use the `import()` API.

**Comment by kevinkassimo** [comment]
@hayd To do such translation, top level await (or at least some way to pause the REPL during `import()`) would be required. However, it seems we are still having some issue with dynamic `import()` in terminal, as it is printing
```
> Error: Not supported
    at eval (<unknown>:1:14)
    at eval (<unknown>:1:66)
    at evaluate (deno/js/repl.ts:86:25)
    at replLoop (deno/js/repl.ts:78:5)
```
at this moment

**Comment by hayd** [comment]
Can you not import inside an eval?

I don't think i follow RE pausing. you'd do the translation to import() in the ts side. I'll see what i can come up with ...

**Comment by ry** [comment]
Import won't work until the REPL uses module evaluation instead of traditional script evaluation... It's unclear to me how this would work... I suggest punting on fixing the REPL until the native ES modules stabilizes a bit more.

**Comment by kitsonk** [comment]
The Chrome dev tools (and I think d8, though I haven't tried it) support dynamic import (`await import()`).  I know the dev tools allows "top level await" (I think it just determines if there is `await` in the code to eval it in an async closure) but I am not sure how it evaluates it in a module context.

It appears to still be an issue with [Node.js](https://github.com/nodejs/node/issues/19570) though.

**Comment by hayd** [comment]
I think that `Error: Not supported` is new after the ESM change.
`await import(fn)` was working last week.

**Comment by bartlomieju** [comment]
Fixed in https://github.com/denoland/deno/pull/7784; dynamic imports is the way to go when importing in REPL

**Comment by stephenhandley** [comment]
if you're claiming some new improved runtime, just seems lazy not to support imports in the repl so that they can be identical to scripts when run. dynamic reports requires non-zero time from end users when trying/converting examples, developing scripts etc.

**Comment by caspervonb** [comment]
> if you're claiming some new improved runtime, just seems lazy not to support imports in the repl so that they can be identical to scripts when run. dynamic reports requires non-zero time from end users when trying/converting examples, developing scripts etc.

Feel free to sponsor me to improve my repl.

**Comment by stephenhandley** [comment]
> Feel free to sponsor me to if you wish for me to improve my repl implementation.
Maybe you'd be better off asking one of these guys lol:
[In order to vigorously pursue these ideas, we have raised 4.9 million dollars of seed capital. Our investors are Dan Scholnick from Four Rivers Ventures, Guillermo from Rauch Capital, Lee Jacobs from Long Journey Ventures, the Mozilla Corporation, Shasta Ventures, and our long-time collaborator Ben Noordhuis.](https://deno.com/blog/the-deno-company)

**Comment by crowlKats** [comment]
@stephenhandley maybe you should read through the issue to understand *why* there is no support for "proper" imports

**Comment by caspervonb** [comment]
> Maybe you'd be better off asking one of these guys lol:

Well, you are the one coming in here complaining about my work calling it lazy.
Also I'd just like to, informally point out that we have a [code of conduct](https://github.com/denoland/deno/blob/main/CODE_OF_CONDUCT.md) around here.

**Comment by stephenhandley** [comment]
Lol you wanna let me know what exactly I violated in that code of conduct?  Or what about your collective conduct as maintainers provided a "welcoming environment"? Oh wait, it was asking me to pay for your work.

The point I'm all making is that having multiple import patterns represents friction for the developers you're trying to get to adopt your platform. Especially if you're presenting this project as improving on node's issues, it seems worth addressing or improving while "the native ES modules stabilize(s) a bit more". I mean ok, punt on it, sure, your team's call. 

I'd suggest at least having quick snippets in your onboarding docs work out of the box i.e
```
const {serve} = await import("https://deno.land/std@0.91.0/http/server.ts");
const s = serve({ port: 8000 });
console.log("http://localhost:8000/");
for await (const req of s) {
  req.respond({ body: "Hello World\n" });
}
```

Yeah have a good day! And congrats on raising the $4.9M! Hopefully you're getting some of that to work on your blessed repl implementation :)

**Comment by crowlKats** [comment]
>  Or what about your collective conduct as maintainers provided a "welcoming environment"?

You have the wrong idea here: neither me nor @caspervonb are maintainers, we are contributors.

> you wanna let me know what exactly I violated in that code of conduct?

Your behaviour has been hostile, and you have been violating the CoC:
- Please be kind and courteous. There’s no need to be mean or rude.
- Respect that people have differences of opinion and that every design or implementation choice carries a trade-off and numerous costs. There is seldom a right answer.
- We will exclude you from interaction if you insult, demean or harass anyone. That is not welcome behavior.
and other points in the CoC. 

> Hopefully you're getting some of that to work on your blessed repl implementation :)

Well the repl is constantly getting improved, alongside the rest of the codebase. just some things have higher priority than the others. The repl is for quick debugging & trying things out. Having modules in the form of *dynamic* modules over *static* modules makes sense in the environment of a repl, where things are dynamic and not statically known, so no module can be made for the running repl, thus not allowing static imports. I am not sure if this can be changed or not, but if it can, it definitively is not a simple task, else it would have been done so from the beginning. Adding this functionality is not a priority.
