### ISSUE TITLE
deno test --doc --unstable doesn't work in Markdown files

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#12861]
This works:
```
deno test --doc --unstable --import-map=.github/import_map.json ./runtime/workers.md
Check file:///Users/biwanczuk/dev/manual/runtime/workers.md$18-27.ts
Check file:///Users/biwanczuk/dev/manual/runtime/workers.md$37-40.ts
Check file:///Users/biwanczuk/dev/manual/runtime/workers.md$43-47.ts
Check file:///Users/biwanczuk/dev/manual/runtime/workers.md$60-63.ts
Check file:///Users/biwanczuk/dev/manual/runtime/workers.md$66-70.ts
Check file:///Users/biwanczuk/dev/manual/runtime/workers.md$91-100.js
Check file:///Users/biwanczuk/dev/manual/runtime/workers.md$141-159.ts
Check file:///Users/biwanczuk/dev/manual/runtime/workers.md$165-182.ts
Check file:///Users/biwanczuk/dev/manual/runtime/workers.md$186-196.ts
Check file:///Users/biwanczuk/dev/manual/runtime/workers.md$197-215.ts
Check file:///Users/biwanczuk/dev/manual/runtime/workers.md$219-225.ts
Check file:///Users/biwanczuk/dev/manual/runtime/workers.md$226-238.ts
Check file:///Users/biwanczuk/dev/manual/runtime/workers.md$242-252.ts
running 0 tests from file:///Users/biwanczuk/dev/manual/runtime/workers.md

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out (15ms)
```

This doesn't work:
```
deno test --doc --unstable --import-map=.github/import_map.json
... snip ...
TS2339 [ERROR]: Property 'emit' does not exist on type 'typeof Deno'. 'Deno.emit' is an unstable API. Did you forget to run with the '--unstable' flag?
const { files, diagnostics } = await Deno.emit("./mod.ts");
                                          ~~~~
    at file:///Users/biwanczuk/dev/manual/typescript/runtime.md$173-180.ts:1:43

TS2339 [ERROR]: Property 'formatDiagnostics' does not exist on type 'typeof Deno'. 'Deno.formatDiagnostics' is an unstable API. Did you forget to run with the '--unstable' flag?
  console.warn(Deno.formatDiagnostics(diagnostics));
                    ~~~~~~~~~~~~~~~~~
    at file:///Users/biwanczuk/dev/manual/typescript/runtime.md$173-180.ts:4:21

TS2304 [ERROR]: Cannot find name 'localStorage'.
localStorage.clear();
~~~~~~~~~~~~
    at file:///Users/biwanczuk/dev/manual/runtime/web_storage_api.md$55-58.ts:1:1

Found 32 errors.

```

Somehow unstable type declarations are not included if there's no file specified (using default glob pattern).

**Comment by bartlomieju** [comment]
Ref https://github.com/denoland/manual/pull/127

**Comment by bartlomieju** [comment]
@kitsonk could you give me a hand here? I'm at loss what's going wrong. 

I verified that `ProcState::prepare_module_load` receives proper value for `lib` (ie. `deno.window` and `deno.unstable`), the same for `cli/emit.rs:check_and_maybe_emit`. Yet somehow diagnostics are produced for unstable APIs. What's even strange is that `localStorage` is defined in `lib.deno.window.d.ts` and it is still not recognized. When running the command on a concrete file (`deno test --doc --unstable --import-map=.github/import_map.json ./runtime/workers.md`) I get exactly same values for `lib` and there are no diagnostics produced.

**Comment by bartlomieju** [comment]
Output from `deno test -L debug --doc --unstable --import-map=.github/import_map.json`

https://gist.github.com/bartlomieju/1f63a97a10807e72e6aa302baacdf305

TSC configuration receives `["deno.window","deno.unstable"]` as configured libs, however only `lib.deno.ns.d.ts` is requested by TSC (ie. unstable type declarations are never read by TSC). Needs more debugging.

**Comment by okcoker** [comment]
> TSC configuration receives ["deno.window","deno.unstable"] as configured libs, however only lib.deno.ns.d.ts is requested by TSC (ie. unstable type declarations are never read by TSC). Needs more debugging.

Thanks for this bit. I just recently added a `deno.jsonc` config and was wondering why the `--inspect-brk` and `--unstable` flags were not working from cli. Seems like I had to add "deno.unstable" to the `jsonc` config. I feel like my CLI flag should have been respected and taken priority (or at least merged with) the deno.json `lib` value which was only `["deno.window"]`. But maybe that could be another issue?

**Comment by bartlomieju** [comment]
@okcoker this seems like an unrelated problem. Please open a new issue with the reproduction and we'll take a look.

**Comment by GJZwiers** [comment]
So the unstable code examples are causing no problems when type-checked in isolation:

 `docs.md`:

          ```ts
          const { files } = await Deno.emit("mod.ts");
          for (const [fileName, text] of Object.entries(files)) {
              console.log(`emitted ${fileName} with a length of ${text.length}`);
          }
          ```


```
deno test --doc --unstable docs.md

running 0 tests from file:///C:/Users/GJZwiers/repos/test_test/docs.md

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out (14ms)
```

`deno test --doc --unstable` without a filename specified works as well.

The problem with the examples in the manual appears to be this code from a different [file](https://github.com/denoland/manual/blob/main/typescript/types.md#using-triple-slash-directives) which has some triple-slash directives in it:

          ```ts
          /// <reference no-default-lib="true" />
          /// <reference lib="deno.worker" />
          ```

These effects seem to be applied to all subsequent code blocks and it is causing a lot of the examples to be type-checked as worker scripts, which I think does not support e.g. `Deno.emit`. The errors dissappear when changing the block to `ts ignore`. I sorta discovered this by accident about a week ago while debugging and I have added a [fix to the manual PR](https://github.com/denoland/manual/pull/127/commits/2bae54c1d351cfbf867c78f53047e52aede6be89).

**Comment by GJZwiers** [comment]
maybe related: #11498

**Comment by GJZwiers** [comment]
@bartlomieju I don't know if there is anything actionable left in this issue. What do you think?

**Comment by bartlomieju** [comment]
@GJZwiers I agree, it's unfortunate, but that's how the reference directives work. Let's close it for now.
