### ISSUE TITLE
Deno configuration file paths should be resolved relative to config file rather than cwd

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#12863]
I think this was an oversight, but I believe the configuration file paths should be resolved based on the config file rather than the current working directory. Ex. paths in "include", "exclude"

**Comment by bartlomieju** [comment]
I agree with you, this is definitely a bug.

**Comment by dsherret** [comment]
I'll fix this one along with a few other issues/cleanup in the lsp (ex. formatting not using config file).
