### ISSUE TITLE
Add a variable or func to get the path of the current script, like __dirname in Node.js

### ISSUE THREAD

**Issue by fengmu456** [denoland/deno#1286]
When the entry script is under the subdirectory, reading the relative file under the subdirectory is unsuccessful.
In `Node.js`, you can get the directory where the script is located by `__dirname`. 
And  `__file__` can also be used in `Python`

**Comment by zhmushan** [comment]
Hi, I am not sure if this is what you need.
```ts
import { cwd } from 'deno'
console.log(cwd())
```

**Comment by kevinkassimo** [comment]
Yeah [`cwd()`](http://deno.land/typedoc/index.html#cwd) is what you want.
(Although not necessary here, as to current filename, I think it could be easily injected either by TypeScript compiler or under deno namespace.)

**Comment by fengmu456** [comment]
> Hi, I am not sure if this is what you need.
> 
> ```ts
> import { cwd } from 'deno'
> console.log(cwd())
> ```

Unfortunately, `cwd()` does not achieve the same effect.
Assume you have the following files and directories:
```shell
~/demo/test/test.ts
~/demo/test/test.txt
```
When I execute `deno test/test.ts` under `~/demo`,
`cwd()` in `~/demo/test/test.ts` will output `~/demo`, not `~/demo/test`.

This is a common use, for example, when I use Deno to write some tool scripts

**Comment by kevinkassimo** [comment]
Sounds like injecting through TS compiler should work. There is also a pitfall that the actual running files are loaded from cache under DENO_PATH and thus different from the expected TS file path. Need to differentiate the two.

@kitsonk Does [this](
https://github.com/denoland/deno/blob/60c008d23b2bdad333711b43148a5053e83a62cc/js/runner.ts#L90) look like a good place for injection? (on my phone so cannot really verify if it would work)

**Comment by kitsonk** [comment]
> Sounds like injecting through TS compiler should work.

No, in my opinion.  We are working on #975.  When that lands, coupled with #1190 then in a lot of cases the TypeScript compiler won't get involved.

Rust "knows" where the original file is located, even if it is loading from the cache, but even then it is tricky when dealing with remote modules.

Basing code dealing with the relative location of the module that the code is running in is rather dangerous.  It can also be super fragile, what if the module get moved around.  Why would you want to "hard code" that into the logic of the module?

While it would be Ryan's call, I would personally want to try to avoid this at all costs unless there are problems that just can't be solved.  Don't want to handle people a 👣 🔫 to author fragile code if we can avoid it.

All file creation/read/access APIs that are exposed would be relative to the `cwd()` anyways.

**Comment by kitsonk** [comment]
@ry we would/could handle any media type in the compiler.

We already support `.json` and associated media types in the compiler.  If we assume anything else is "text" ish... we would potentially just "compile" down to something like this:

```ts
export function toUint8Array(): Uint8Array {
  return deno.getUint8Array("./style.css");
}

export function toString(): string {
  return (new TextDecoder()).decode(deno.getUint8Array("./style.css"));
}
```

I think we would have to generate that "shell" module which would be loaded in the runtime which will op back out to Rust to get the resource.  Rust would use the module resolution logic, which would negate the need for the module to know where it sits.  Doing some sort of "getter" as an export of a module is awkward since `export =` is not an ESM construct.  So it does mean that you would have to do something like this:

```ts
import * as styleCss from "./style.css";

const value = styleCss.toUint8Array();
```

**Comment by Janpot** [comment]
Isn't this what [`import.meta.url`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import.meta) was intended for?

**Comment by ry** [comment]
@janpot thanks - I didn’t know about that

**Comment by smith** [comment]
@Janpot I think we might need to tweak the tsconfig options for this to work as intended:

```
1:13 - error TS1343: The 'import.
meta' meta-property is only allowed using 'ESNext' for the 'target' and
'module' compiler options.

1 console.log(import.meta);
```

**Comment by bartlomieju** [comment]
You can now retrieve URL of script with `import.meta.url`

**Comment by npup** [comment]
Hesitated to open this but all my searches led me here.

What about finding the _directory_ of the current script then? That is what I want most of the time. 

The import.meta.url gives a `file:///...` to the file itself (of course), and I haven't found very ergonomic ways to use it to then carry out what `path.join(___dirname, "static-files")` used to do.

**Comment by zhmushan** [comment]
@npup `import.meta` doesn't work well on win10, maybe this is a bug.
ref: https://github.com/denoland/deno/issues/4647

**Comment by SyrupThinker** [comment]
@npup  There's the [path module](https://deno.land/std/path/) which you could use.

**Comment by zhmushan** [comment]
@SyrupThinker `path.join(import.meta.url, "path")` cannot be used directly on Win10

**Comment by nayeemrmn** [comment]
@npup `new URL("static-files", import.meta.url).pathname`.

**Comment by npup** [comment]
That one looks cool, thanks!

/p

**Comment by seishun** [comment]
@nayeemrmn that gives a path that looks like "/C:/Users/seishun/project/static-files", which Deno.readFileSync doesn't accept.

**Comment by seishun** [comment]
Here's a hacky but cross-platform way:

```js
import { createRequire } from "https://deno.land/std/node/module.ts";
const require = createRequire(import.meta.url);
console.log(require.resolve("./static-file"));
```

**Comment by nayeemrmn** [comment]
@seishun `new URL("static-files", import.meta.url).pathname.slice(Deno.build.os == "win")` 🤷‍♂️

**Comment by Vandivier** [comment]
@nayeemrmn `...slice(Deno.build.os == "win")` isn't typed correctly. I suppose the false case should evaluate numerically to 0. Is the true case 1?

**Comment by Vandivier** [comment]
related to my above comment: https://github.com/denoland/deno/issues/4915

**Comment by nayeemrmn** [comment]
@zhmushan @seishun Update! As of Deno 1.1.0, thanks to @actual-size's work in #5990, FS functions support file URLs so you can do the following:
```js
console.log(Deno.statSync(import.meta.url)); // FileInfo { ... }
console.log([...Deno.readDirSync(new URL("static-files", import.meta.url))]); // [ ... ]
```

**Comment by zhmushan** [comment]
Thanks for your mention, this is very useful for me!

**Comment by han-tyumi** [comment]
From my testing, it seems like `import.meta.url` does not work as expected when bundling. It will instead reference the original file that was bundled. I could create a bug if this is not intended. If intended, then I'd be looking for another option to make my script portable so that it can use a directory relative to the location of it.

**Comment by kitsonk** [comment]
@han-tyumi there is already an issue for that: #6344

**Comment by martin-braun** [comment]
```ts
import __ from "https://deno.land/x/dirname/mod.ts";
import { IMakeLoc } from "https://deno.land/x/dirname/types.ts";
const { __filename, __dirname }: IMakeLoc = __(import.meta)
```

is a way to do it, but I really like to depend on an external module for something like this.

**Comment by mindon** [comment]
```ts
import { fromFileUrl, dirname } from "jsr:@std/path";
console.log(dirname(fromFileUrl(import.meta.url)));
```

**Comment by marvinhagemeister** [comment]
There is also this:

```ts
const __filename = import.meta.filename;
const __dirname = import.meta.dirname;
```
