### ISSUE TITLE
lsp: Use header X-Pinned-Url for code action to pin a dependency

### ISSUE THREAD

**Issue by ewired** [denoland/deno#12864]
Using data from the header X-Pinned-Url (e.g. Skypack), add a code action for unpinned dependencies to make them pinned to the current version:
```js
import puppeteer from "https://deno.land/x/puppeteer/mod.ts";
// after applying quick fix "Replace with pinned module":
import puppeteer from "https://deno.land/x/puppeteer@9.0.2/mod.ts";
```

**Comment by kitsonk** [comment]
Good idea... @ry and I recently were lamenting how sometimes dependencies change (or type definitions) and it is a pain to ferret out the pinned URL.

This should be fairly straight forward to implement for a community contribution if someone wanted to try, otherwise I will get around to it in a while.

**Comment by ntedgi** [comment]
hi @kitsonk  i would like to give it a try

**Comment by kitsonk** [comment]
Currently, skypack pinned URLs don't support the `?dts` query parameter, which means that if we converted to the pinned URL, the type definitions would go away, which would make people 😢 .  I opened https://github.com/skypackjs/skypack-cdn/issues/251 to see if it can be supported.  Really need that before we progress this feature.

**Comment by kitsonk** [comment]
I am going to close this in lieu of #13580.  #13580 is a more general feature, where if a URL is redirected, the language server will issue an info diagnostic and supports a quick fix to convert it to the redirected URL and doesn't require the remote host to provide any special headers.
