### ISSUE TITLE
compat: Add required APIs for "child_process.send"

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#12879]
Required for running `next.js` in compat mode.

[It was confirmed](https://github.com/denoland/deno/issues/12577#issuecomment-976927196) that we only need to handle "serializable" messages and do not need to worry for "handles".

Ref https://github.com/denoland/deno/issues/12577#issuecomment-954496183

**Comment by yordis** [comment]
keep

**Comment by Anutrix** [comment]
Is this issue resolved?
keep

**Comment by littledivy** [comment]
IPC serialization implemented in https://github.com/denoland/deno/pull/21490.
