### ISSUE TITLE
lsp: config file does not reload on change

### ISSUE THREAD

**Issue by igorsaux** [denoland/deno#12871]
When I change `deno.json` - nothing happens, so, I have to restart the language server every time I change the file.
As I found out - the issue seems are Windows-specific, here is `dbg!` output:
```
[cli\lsp\language_server.rs:959] config_uri = Url {
    scheme: "file",
    cannot_be_a_base: false,
    username: "",
    password: None,
    host: None,
    port: None,
    path: "/C:/Users/me/Desktop/deno-project/deno.json",
    query: None,
    fragment: None,
}
[cli\lsp\language_server.rs:960] &fe.uri = Url {
    scheme: "file",
    cannot_be_a_base: false,
    username: "",
    password: None,
    host: None,
    port: None,
    path: "/c%3A/Users/me/Desktop/deno-project/deno.json",
    query: None,
    fragment: None,
}
[cli\lsp\language_server.rs:961] *config_uri == fe.uri = false
```

I believe the comparison does not work as expected because of an encoded path that comes from a language client.

Version: `1.16.2 (debug, x86_64-pc-windows-msvc)`
Tested on VSCode.

**Comment by dsherret** [comment]
The data in `fe.uri` seems wrong. It shouldn't be percent encoded in there.
