### ISSUE TITLE
`Deno.watchFs` gives too many duplicate events on MacOS

### ISSUE THREAD

**Issue by askonomm** [denoland/deno#12874]
With basic code such as this:

```javascript
const baseDir = "./";
const watcher = Deno.watchFs(baseDir);

for await (const event of watcher) {
 console.log(event);
}
```

And then when I go ahead and change a file, **just once!**, I get three concecutive events that look like this:

```
{
  kind: "modify",
  paths: [ "index.html.hbs" ]
}
{
  kind: "modify",
  paths: [ "index.html.hbs" ]
}
{
  kind: "modify",
  paths: [ "index.html.hbs" ]
}
```

Shouldn't I receive just one event since the file was changed just once? 

---

deno 1.16.2 (release, aarch64-apple-darwin)
v8 9.7.106.2
typescript 4.4.2

**Comment by bradenmacdonald** [comment]
How are you changing the file?

I tried to reproduce this but didn't see the same thing.

```
const baseDir = "./";
const watcher = Deno.watchFs(baseDir);
for await (const event of watcher) { console.log(event); }
```
Now I run `echo "test" > file.txt` in a separate terminal, then see:
```
{ kind: "create", paths: [ "/Users/braden/Desktop/file.txt" ], flag: null }
{ kind: "modify", paths: [ "/Users/braden/Desktop/file.txt" ], flag: null }
{ kind: "modify", paths: [ "/Users/braden/Desktop/.DS_Store" ], flag: null }
{ kind: "modify", paths: [ "/Users/braden/Desktop/.DS_Store" ], flag: null }
```
So `.DS_Store` is modified twice, but `file.txt` shows one `create` event and one `modify` event.
Then I run `touch file.txt` and get one event:
```
{ kind: "modify", paths: [ "/Users/braden/Desktop/file.txt" ], flag: null }
```
Then I run `echo "test" >> file.txt` and see one event:
```
{ kind: "modify", paths: [ "/Users/braden/Desktop/file.txt" ], flag: null }
```
Then I run `rm file.txt` and get:
```
{ kind: "remove", paths: [ "/Users/braden/Desktop/file.txt" ], flag: null }
```

This is with
```
deno 1.16.3 (release, aarch64-apple-darwin)
v8 9.7.106.5
typescript 4.4.2
```

**Comment by askonomm** [comment]
Ooh, maybe it's a VS Code thing? I saved the file with VS Code.

**Comment by kuntau** [comment]
> Ooh, maybe it's a VS Code thing? I saved the file with VS Code.

I save a file with vim, give me the same result. 3x duplicated modify event

**Comment by jrylan** [comment]
I also consistently experience 3 notifications in a row with VS Code on macOS. In a simple test, seems like setting up my listener function to debounce the notification per filename+event kind to 20 milliseconds handles the duplicates as a simple workaround for now.

Something sort of like this:

```ts
const watcher = Deno.watchFs(Deno.cwd());
const notifiers = new Map<string, number>();

for await (const event of watcher) {
  const dataString = JSON.stringify(event);
  if (notifiers.has(dataString)) {
    clearTimeout(notifiers.get(dataString));
    notifiers.delete(dataString);
  }

  notifiers.set(
    dataString,
    setTimeout(() => {
      // Send notification here
      console.log({ event });
    }, 20)
  );
};
```

**Comment by askonomm** [comment]
Yup, I've gone with a debounce method as a way for now.

**Comment by ry** [comment]
This is not a bug in Deno - we are just forwarding the events the operating system is issuing. It's up to the caller to debounce.

**Comment by jrylan** [comment]
@ry `Deno.watchFs` is already nearly perfect, would you consider just adding an a `debounceTimeout` type of option to that method call?

**Comment by ry** [comment]
@jrylan not to `watchFs` itself, but it would be nice to have something like chokidar in deno_std

**Comment by Hajime-san** [comment]
Hi, the `debounce` in deno_std example of JSDoc updated recently.

```typescript
import { debounce } from "https://deno.land/std@0.215.0/async/debounce.ts";

// Array.fromAsync required Deno 1.38.0 or higher.
await Array.fromAsync(
  Deno.watchFs('./'),
  debounce((event) => {
    console.log('[%s] %s', event.kind, event.paths[0]);
  }, 200),
);
```
 
https://deno.land/std@0.215.0/async/debounce.ts?s=debounce

**Comment by lionel-rowe** [comment]
> Hi, the `debounce` in deno_std example of JSDoc updated recently.

The approach in the example has issues if you only care about a certain type of events — e.g. when I save a file in VS Code, I get 3 events in the order `modify, modify, access`. I only care about the `modify` events, which both get swallowed by the later `access` event.

In such situations, you need to only call the debounced callback if the event matches the condition:

```ts
const callback = debounce((event: Deno.FsEvent) => {
    console.log('[%s] %s', event.kind, event.paths[0])
}, 200)

for await (const event of Deno.watchFs('./')) {
    if (event.kind === 'modify') callback(event)
}
```
