### ISSUE TITLE
perf: address TypeScript performance regression

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#12881]
It appears #12830 introduced a significant performance regression:

![Benchmarks__4990___5289_](https://user-images.githubusercontent.com/1282577/143148982-1c51921c-8dab-4212-afc0-338ebee13e15.png)

I haven't looked into it, but I suspect we need to still write out a `.tsbuildinfo` even when we are only type checking, not only when we are emitting, as it dramatically improves the performance of type checking as well.

**Comment by nayeemrmn** [comment]
Are separate benchmark runs sharing a DENO_DIR? I think they were piggybacking off each other's `.tsbuildinfo`s before, but now the `--reload` is being respected: https://github.com/denoland/deno/blob/7413c96985507e7d129fef9374f560fbc2f38d7e/cli/emit.rs#L336-L340

**Comment by kitsonk** [comment]
I believe @nayeemrmn was right, the benchmark was "flawed" and current measurements are more accurate.
