### ISSUE TITLE
lsp: Check trigger kind "unknown" impact on tsc

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#12895]
Please note this change, I had to add a "catch-all" in the match below, due to `SignatureHelpTriggerKind` being non-exhaustive enum

See https://github.com/gluon-lang/lsp-types/issues/213

_Originally posted by @bartlomieju in https://github.com/denoland/deno/pull/12894#r756496991_

**Comment by nayeemrmn** [comment]
- `SignatureHelpTriggerKind` still doesn't have another enum, so this is an unreachable case currently.
- TS source seems to check `kind === "invoked"` and `"kind === "characterTyped"`, so an unknown variant would be treated the same as `"retrigger"`.
