### ISSUE TITLE
'deno-init' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by goodmanworld** [denoland/deno#12906]
I have installed Deno on Windows10. This is the Deno version I see in CMD:

```
**deno --version
deno 1.16.3 (release, x86_64-pc-windows-msvc)
v8 9.7.106.5
typescript 4.4.2**
```

When I try `deno-init -y --name backend` it gives me this error message:
`'deno-init' is not recognized as an internal or external command, operable program or batch file.
`

**Comment by crowlKats** [comment]
`deno-init` doesnt exist. deno doesnt provide such thing

**Comment by goodmanworld** [comment]
> `deno-init` doesnt exist. deno doesnt provide such thing

So how can I create a new Deno project?

I found `deno-init` here: https://deno.land/x/init@v1.5.3

**Comment by goodmanworld** [comment]
I found that `deno-int` is a third party module!
