### ISSUE TITLE
error:TS2345 [ERROR]:Argument of type '"any" | "access" | "create" | "modify" | "remove" | "other"' is not assignable to prameter of type 'FileAction'

### ISSUE THREAD

**Issue by goodmanworld** [denoland/deno#12907]
I tried to install `denon` using the following command on Windows CMD 

    deno install -qAf --unstable https://deno.land/x/denon/denon.ts

But I get the following error:

    error: TS2345 [ERROR]: Argument of type '"any" | "access" | "create" | "modify" | "remove" | "other"' is not assignable to parameter of type 'FileAction'.
      Type '"other"' is not assignable to type 'FileAction'.
                this.#changes[path].push(kind);

**Comment by lucacasonato** [comment]
This is an issue with `denon`, not with Deno.
