### ISSUE TITLE
Deno.com has broken URLs with trailing slash

### ISSUE THREAD

**Issue by impressivewebs** [denoland/deno#12914]
Example:

https://deno.com/blog/

Vs.

https://deno.com/blog

This seems to happen for any deep links that I tried. I noticed this because a newsletter had linked to the blog and the URL was broken.

**Comment by nayeemrmn** [comment]
Duplicate of #https://github.com/denoland/dotland/issues/1939.

**Comment by lucacasonato** [comment]
Closing as duplicate of denoland/dotland#1939.
