### ISSUE TITLE
Unable to compile JSX following exact instructions in documentation

### ISSUE THREAD

**Issue by papiro** [denoland/deno#12912]
Given a `deno.json` of:
```
{
    "compilerOptions": {
        "jsx": "react-jsx",
        "jsxImportSource": "preact"
    }
}
```
and a `import_map.json` of:
```
{
    "imports": {
        "preact/jsx-runtime": "https://cdn.skypack.dev/preact/jsx-runtime?dts",
        "preact/jsx-dev-runtime": "https://cdn.skypack.dev/preact/jsx-dev-runtime?dts"
     }
}
```

and a JSX component of:
```
const Index = () => {
  return (
    <html>
      <title>Foo</title>
      <body>
        <h1>
          "Hello World!"
          <button onClick={() => console.log("foo")}>foo</button>
        </h1>
      </body>
    </html>
  );
};

export default Index;
```

I am trying to import that component and cannot compile with the following errors:
```
error: TS7026 [ERROR]: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
    <html>
    ~~~~~~
    at file:///Users/pierre/elishas-oil/Index.tsx:3:5

TS7026 [ERROR]: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
      <title>Foo</title>
      ~~~~~~~
    at file:///Users/pierre/elishas-oil/Index.tsx:4:7

TS7026 [ERROR]: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.
      <title>Foo</title>
                ~~~~~~~~
    at file:///Users/pierre/elishas-oil/Index.tsx:4:17
....
```
The command I'm using to run `mod.ts` which is simply doing an `import Index from './Index.tsx'` is `deno run --import-map=./import_map.json --config deno.json mod.ts`

It complains for every HTML element used. FWIW, even though I have VSCode configured correctly w/ the import-map and deno config file, I get red squigglies under each HTML element as well. 

Everything works when I use the `/** @jsxImportSource https://esm.sh/preact */` pragma, but I would expect to be able to configure this from the deno config file per https://deno.land/manual@v1.16.3/jsx_dom/jsx#using-jsx-import-source-in-a-configuration-file.

**Comment by bartlomieju** [comment]
CC @kitsonk

**Comment by kitsonk** [comment]
The type definitions being supplied by skypack.dev don't seem to be automatically pulling in the full preact type, meaning that the JSX intrinsic elements are being made available.  It isn't technically an issue with Deno, as the compiler is only doing what is being told to do, but I can see how this becomes a bit of an issue from a usability issue.

As you pointed out, `https://esm.sh/preact` has the correct typings "out of the box".  You could (as shown in the documentation example) just use `"jsxImportSource": "https://esm.sh/preact"` and skip the import map all together and it would be enabled "globally".

Is there a specific reason you wanted to use skypack?

I believe there is a better setting that can be used to ensure the intrinsic elements are in scope when using skypack and I will try to update the documentation to reflect it.

**Comment by papiro** [comment]
@kitsonk Thank you very much for this thorough explanation. I don't mind using esm.sh rather than skypack.dev. My morale for a newer technology just gets tired when the docs lead me to errors. I am committed to using Deno so I made the effort to call it out rather than abandon the technology altogether.
