### ISSUE TITLE
bug: logging errors from `deno_runtime` fails

### ISSUE THREAD

**Issue by DjDeveloperr** [denoland/deno#12918]
**Description**

When embedding `deno_runtime` in an application, errors seem to break - when it's converted to a string, it fails because of some missing op.

**Reproduction**

Add the line

```js
console.log(new Error("test error"));
```

to `deno_runtime/examples/hello_runtime.js`

and run this in `deno_runtime` dir

```sh
cargo run --example hello_runtime
```

You'll get

```
deno:core/01_core.js:4680: Uncaught TypeError: invalid op id: expected type `v8::data::Integer`, got `v8::data::Value`
Error: Uncaught TypeError: invalid op id: expected type `v8::data::Integer`, got `v8::data::Value`
    at deno:core/01_core.js:149:26
```

**Additional details**

After investigating more I found that these ops: https://github.com/denoland/deno/blob/main/cli/ops/errors.rs - are in the cli but not included in `deno_runtime` crate (though it depends on them).

**Comment by bartlomieju** [comment]
Verified on latest `main` branch, this no longer occurs.
