### ISSUE TITLE
Cannot find name `DedicatedWorkerGlobalScope`

### ISSUE THREAD

**Issue by F3n67u** [denoland/deno#12922]
I tried implement `worker_threads.isMainThread` via `DedicatedWorkerGlobalScope`, but deno complain cannot find name `DedicatedWorkerGlobalScope` ;
```
// test.ts
const isMainThread = typeof DedicatedWorkerGlobalScope === "undefined" ||
  self instanceof DedicatedWorkerGlobalScope === false;
console.log(isMainThread);
```

```
% deno run test.ts 
Check file:///Users/feng/dev/deno/test-ts/test.ts
error: TS2304 [ERROR]: Cannot find name 'DedicatedWorkerGlobalScope'.
const isMainThread = typeof DedicatedWorkerGlobalScope === "undefined" ||
                            ~~~~~~~~~~~~~~~~~~~~~~~~~~
    at file:///Users/feng/dev/deno/test-ts/test.ts:1:29

TS2304 [ERROR]: Cannot find name 'DedicatedWorkerGlobalScope'.
  self instanceof DedicatedWorkerGlobalScope === false;
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~
    at file:///Users/feng/dev/deno/test-ts/test.ts:2:19

Found 2 errors.
```

**Comment by nayeemrmn** [comment]
You should just `// @ts-ignore` that line. That symbol is only defined within workers so if you're using it to check if you're in a worker you'll have to bypass type-checking.

**Comment by bartlomieju** [comment]
@F3n67u FYI there's already an open PR to add `worker_threads` that is feature-complete: https://github.com/denoland/deno_std/pull/1151 but we still haven't landed it due to type checking issues. I suggest not to duplicate the work and maybe instead try to figure out the type checking problems in aforementioned PR?

**Comment by F3n67u** [comment]
> @F3n67u FYI there's already an open PR to add `worker_threads` that is feature-complete: [denoland/deno_std#1151](https://github.com/denoland/deno_std/pull/1151) but we still haven't landed it due to type checking issues. I suggest not to duplicate the work and maybe instead try to figure out the type checking problems in aforementioned PR?

@bartlomieju ok, thanks for your information. I will set `isMainThread` as `true` when it's used in the node test now. It's ok when the node test is not related to worker.
