### ISSUE TITLE
FFI support for ArrayBuffer (and SharedArrayBuffer)

### ISSUE THREAD

**Issue by kriszyp** [denoland/deno#12932]
Currently it seems that FFI buffers only support ArrayBuffer views (typed arrays like Uint8Array or a DataView), but not ArrayBuffer themselves (if you use an ArrayBuffer for a symbol defined with a `buffer` parameter, the error is `Expected ffi arg value to be an unsigned integer`). Is there any reason that it wouldn't be possible to allow an ArrayBuffer as an FFI parameter?
```
let view = new Uint8Array(8) // I can use this with FFI
let buffer = new ArrayBuffer(8) // I can't use this with FFI
```
Anyway, I really appreciate the new FFI buffer support!

**Comment by littledivy** [comment]
ArrayBuffer support was added. (Although Uint8Array currently takes the Fast API path)
