### ISSUE TITLE
`httpConnAutoCloseDelayedOnUpgrade` and `httpServerDeleteRequestHasBody` are flaky

### ISSUE THREAD

**Issue by andreubotella** [denoland/deno#12944]
https://github.com/denoland/deno/runs/4361438674?check_suite_focus=true#step:35:2107

These tests have pending async ops in commits for #12862. That PR changes the clamping of timers from 4ms to 0, which affects the delay before the ops sanitizer runs, but as pointed out by @lucacasonato in https://github.com/denoland/deno/pull/12862#issuecomment-982630672, if the pending ops take longer than one event loop turn to resolve, that is a bug.

**Comment by bnoordhuis** [comment]
https://github.com/denoland/deno/runs/4443957712?check_suite_focus=true - now happening on the main branch.
