### ISSUE TITLE
integration::test::steps_invalid_usage is flaky

### ISSUE THREAD

**Issue by andreubotella** [denoland/deno#12945]
https://github.com/denoland/deno/runs/4361438674?check_suite_focus=true#step:35:2644

The relevant difference is in the following output:

```
test parallel steps with sanitizers ...
  test step 1 ... pending (0ms)
  test step 2 ... FAILED (6ms)
    Error: There is an op sanitizer delay already.
        at deno:runtime/js/40_testing.js:48:18
        at Object.action (deno:ext/timers/01_timers.js:150:11)
        at handleTimerMacrotask (deno:ext/timers/01_timers.js:76:12)
```

rather than the expected

```
test parallel steps with sanitizers ...
  test step 1 ... pending ([WILDCARD])
  test step 2 ... FAILED ([WILDCARD])
    Error: Cannot start test step while another test step with sanitizers is running.
     * parallel steps with sanitizers > step 1
        at preValidation ([WILDCARD])
        at testStepSanitizer ([WILDCARD])
        at [WILDCARD]/invalid_usage.ts:[WILDCARD]
        at [WILDCARD]
```

-----

The "there is an op sanitizer delay already" error was introduced in #12934, which correctly assumed no two tests or test steps should be running at the same time. The parallel steps error is being swallowed because `await opSanitizerDelay()` is called in a `finally` block.

**Comment by bartlomieju** [comment]
CC @dsherret

**Comment by andreubotella** [comment]
I opened #12966 as a draft, since it's not clear that making it into a queue is the right thing.
