### ISSUE TITLE
Add ignore directives to bundled code

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#12949]
When using `deno bundle` generated code should be annotated with ignore directives for `deno fmt` and `deno lint`:

```js
// deno-fmt-ignore-file
// deno-lint-ignore-file

...
// bundled code
```
It makes no sense to lint bundled code, and reformatting it will break source maps.

We might even add a comment informing that the code you see is a result of bundling:
```
// This code was bundled using `deno bundle` and it's not recommended to edit it manually
```

Ref #12916

**Comment by bartlomieju** [comment]
This is actually not a "good first issue". 

The change needs to be done around here:
https://github.com/denoland/deno/blob/9a1066869457037d6ab24965da82e80e1e5c77a9/cli/emit.rs#L580-L621

However, since comments should be appended *after* bundling, the source map needs to be updated before being written to account for additional lines.

**Comment by gliheng** [comment]
Hi @bartlomieju . I'd like to work on this as my first contribution to this project.

**Comment by bartlomieju** [comment]
@gliheng thanks for interest in this issue, please not that this is rather a hard issue and might not be best suited for first contribution. I don't have anymore pointers to provide at the moment on how it could be implemented.

**Comment by gliheng** [comment]
After some digging, I found that we can just use JsWriter to write ignore directives in bundled file as in this commit https://github.com/gliheng/deno/commit/aeb4c63d926b6969529540b7ccdae02d619b7c38

However, sourceMap generation has to be enabled. Looks like it's currently disabled in bundled mode.
https://github.com/denoland/deno/blob/46f2ff120587cd1cb7b11e66d41ad6ad46fb09a8/cli/config_file.rs#L105-L115
