### ISSUE TITLE
Deno.startTls fails on socket I/O rather than on the upgrade call

### ISSUE THREAD

**Issue by aricart** [denoland/deno#12951]
@bartlomieju for some reason I thought that the `Deno.startTls` was fixed so that bad certificates type errors can be detected. I am noticing on 1.16.3 that it still does fail (now with more information I believe) but still outside of the scope of the tls upgrade operation.

Here's what I mean:

```
    const sto = {hostname} as Deno.StartTlsOptions;
    if(tls.caFile) {
     const ca = await Deno.readTextFile(tls.caFile);
     sto.caCerts = [ca];
    }

    this.conn = await Deno.startTls(
      this.conn,
      sto,
    );
    console.log(">>>>>> UPGRADED");
    this.encrypted = true;
    this.writer = new BufWriter(this.conn);
```

In the above case when the connection is upgraded to TLS, I would expect the startTls to fail - instead it proceeds:
```
test tls - custom ca fails without root ...>>>>>> UPGRADED
....
error: Uncaught (in promise) InvalidData: invalid certificate: UnknownIssuer
    nwritten += await w.write(arr.subarray(nwritten));
                ^
    at async write (deno:ext/net/01_net.js:26:12)
    at async writeAll (https://deno.land/std@0.95.0/io/util.ts:79:17)
    at async BufWriter.flush (https://deno.land/std@0.95.0/io/bufio.ts:470:7)
    at async write (file:///Users/synadia/Dropbox/code/src/github.com/nats-io/nats.deno/src/deno_transport.ts:45:3)
```

Unlike the previous go-around, if I try to write an Empty array, I am able to trap the error during the upgrade. Was hoping for that to be internally trapped by Deno. If this is best we can do it's fine.

**Comment by lucacasonato** [comment]
Use the `TlsConn.handshake` method to manually force a handshake early on and retrieve the error.
