### ISSUE TITLE
When publishing CLI to crates.io, pin all dependency versions

### ISSUE THREAD

**Issue by piscisaureus** [denoland/deno#12950]
Currently `cargo install deno --version 1.16.2` doesn't work because `lspower` made a non-semver-compatible change.
It also created a problem last week while making the 1.16.3 release.

We can make this less likely by pinning all dependency versions in `cli/Cargo.toml`, so e.g.

```toml
atty = "0.2.14"
```

would become

```toml
atty = "=0.2.14"
```

**Comment by kitsonk** [comment]
Also to point out we have had the same issue with swc making breaking changes in patch releases.

**Comment by bartlomieju** [comment]
So are you suggesting to pin all deps in `cli/Cargo.toml` or just pin them when releasing and then revert back?

**Comment by kitsonk** [comment]
Well, if it is pin on releasing, it needs to account for the situation that it may have already floated above the unpinned version, so looking at what is actually in the lockfile and pinning to that version.

**Comment by bartlomieju** [comment]
> Well, if it is pin on releasing, it needs to account for the situation that it may have already floated above the unpinned version, so looking at what is actually in the lockfile and pinning to that version.

That seems very brittle though. I think we should just pin all the versions as we are manually updating them anyway.
