### ISSUE TITLE
`performance.now()` keeps going up across workers.

### ISSUE THREAD

**Issue by andreespirela** [denoland/deno#12977]
Seems like `performance.now()` is using some sort of static counter available throughout workers. Ran some tests yesterday where I put a performance.now() in the parent thread, one in a worker, and one in another worker, and they were consecutively higher than the previous. So the more calls to `performance.now()` I did on threads, the higher the number I was gonna get also across threads (workers)

**Comment by bartlomieju** [comment]
When creating workers each one gets a fresh instant that is used to count elapsed time for `performance.now()` API. Can you provide a reproduction for this purpose?

**Comment by bartlomieju** [comment]
@andreespirela any news on this topic? If not I'm leaning towards closing this issue.

**Comment by andreespirela** [comment]
Closing as I can't reproduce
