### ISSUE TITLE
Don't consider different versions of a dep as the same dep

### ISSUE THREAD

**Issue by Skillz4Killz** [denoland/deno#12990]
Can an interface named the same in 2 different deps conflict? Does deno consider the same lib with 2 versions as same or different dep? 

For example, if i use latest std in my deps.ts but one of my deps uses an older one. Suppose they both have similar interface but newer one adds props to it. What would happen when trying to use this code.

---

**My code with error**
![image](https://user-images.githubusercontent.com/23035000/144717612-807fb2c8-8dff-4a60-8e30-b3532a661983.png)

**My code deps.ts**
![image](https://user-images.githubusercontent.com/23035000/144717631-4e5466bf-d099-45e5-9fa5-bf97e21fdc0a.png)

- RC12 has https://deno.land/x/discordeno@13.0.0-rc12/src/types/channels/modifyChannel.ts#L37
- Cache plugin was using rc11 which didnt have this additional prop https://deno.land/x/discordeno@13.0.0-rc11/src/types/channels/modifyChannel.ts#L37

---

**Attempted Solutions:**

First i tried to reload VSC, --reload cache and no luck. Then i manually purged cache folder and ran deno cache deps.ts and no luck.

**Working Solution:**
Lastly updated the deps to use the same version(rc12), and finally the errors disappeared.

Also noteworthy all my other intellisense issues have also disappeared such as: https://github.com/denoland/vscode_deno/issues/584

**Comment by nayeemrmn** [comment]
> **My code with error**
> ![image](https://user-images.githubusercontent.com/23035000/144717612-807fb2c8-8dff-4a60-8e30-b3532a661983.png)

It would help to see more code, like how `options` is declared and where `ModifyChannel` is being imported from. Also, are you seeing these type errors for `deno run` or just intellisense?

**Comment by Skillz4Killz** [comment]
Sadly, I already added a lot more code to it once i had the error fixed and I improved stuff before committing this file so I don't have the exact code anymore that caused the issue. The closest I can show is what I had after the fix and making all the changes to this file:

https://deno.land/x/discordeno_permissions_plugin@0.0.8/src/channels/editChannel.ts#L37

**Comment by nayeemrmn** [comment]
@Skillz4Killz This was an issue with your code. The type of `options` (`ModifyChannel`) is being taken from `bot.helpers.editChannel`, and `bot` is type `BotWithCache` which is imported from your cache plugin which was using rc11. You aren't importing or using the `ModifyChannel` from your `deps.ts`. So not an issue with Deno or intellisense.
