### ISSUE TITLE
Cannot Load Module

### ISSUE THREAD

**Issue by NekoMaru76** [denoland/deno#12997]
![WhatsApp Image 2021-12-05 at 10 56 08 PM](https://user-images.githubusercontent.com/64361584/144753808-30d0bd8b-f945-4ec9-9ccc-1ad249c63cc4.jpeg)
For some unknown reasons, the TS compiler bugged.

**Comment by nayeemrmn** [comment]
`deno upgrade` to 1.16.3 and run with `--reload`.

**Comment by NekoMaru76** [comment]
That seems fixed it. Thanks! _So TS compiler for deno is kinda unstable?_

**Comment by lucacasonato** [comment]
@NekoMaru76 No, it isn't unstable - we just had some issues in one of the last releases that caused some people's cache to get into a wonky state.

**Comment by NekoMaru76** [comment]
I see. Thanks for telling me that!
