### ISSUE TITLE
Feature Request: jsonc with import maps

### ISSUE THREAD

**Issue by Yaikava** [denoland/deno#12993]
It would be nice to allow usage of `.jsonc` files for import maps so we can have comments in them.

**Comment by kitsonk** [comment]
The standard does not allow JSONC, so I would be opposed to it. My opinion would be to open a request with the standard (https://github.com/WICG/import-maps) and if the accept it, we would implement.

Integrating import maps into a Deno config though, would be our "own" standard and therefore we would implicitly support them. See: #12800.

**Comment by Yaikava** [comment]
Ahhh, I see. Thanks

**Comment by bartlomieju** [comment]
So it was a hard no from the WICG (https://github.com/WICG/import-maps/issues/264) and I also believe we should stick to JSON in import maps. I get the usability of being able to comment in that file, but breaking web compat is a no-go in my opinion.

**Comment by Yaikava** [comment]
Sounds fair I guess
