### ISSUE TITLE
Triple slash directives sometimes don't work with import maps

### ISSUE THREAD

**Issue by jaydenseric** [denoland/deno#13009]
Here is a situation where Deno knows how to resolve this triple slash directive that depends on the import map according to the Deno LSP, yet deno-ts seems to be attempting to resolve it without taking the import map into account and is erroring:

<img width="1454" alt="Screen Shot 2021-12-07 at 12 25 55 pm" src="https://user-images.githubusercontent.com/1754873/144949272-1c362b56-d115-47d9-a831-24e6c6338ee3.png">

I tried to create a minimal reproduction project, but it's working so in the right conditions Deno is able to resolve triple slash directive paths that depend on the import map. I can't figure out why in this case it's confused. ***Edit:*** Minimal reproduction here: https://github.com/denoland/deno/issues/13009#issuecomment-987547193 .

If I change the triple slash directive path to match what the import map resolves, it works and the global namespace it exposes is available in the module for type checking, proving that there is nothing "wrong" with how I've structured the files:

<img width="1456" alt="Screen Shot 2021-12-07 at 12 31 53 pm" src="https://user-images.githubusercontent.com/1754873/144949568-34e5fffd-ac74-43ef-b707-feda06c364c3.png">

`deno --version`:

```
deno 1.16.4 (release, aarch64-apple-darwin)
v8 9.7.106.15
typescript 4.4.2
```

**Comment by kitsonk** [comment]
Without a minimal reproduction, it is really hard to figure out.

**Comment by jaydenseric** [comment]
Ok, now something really weird is going on as I was experimenting:

<img width="1487" alt="Screen Shot 2021-12-07 at 2 21 49 pm" src="https://user-images.githubusercontent.com/1754873/144960367-7dcf65ae-a252-49b3-a39f-4aa78997ad1b.png">

I think there is some kind of incorrect cache that is persisting even after restarting the VS Code plugin host.

**Comment by jaydenseric** [comment]
I deleted the Deno cache (at the location reported via `deno info`), and restarted VS Code and first it appeared of course as uncached:

<img width="1379" alt="Screen Shot 2021-12-07 at 2 27 35 pm" src="https://user-images.githubusercontent.com/1754873/144961266-a44deeab-5aed-4ab9-9f48-1b1622471c3c.png">

After running the Deno cache code action, we are back to the original situation as described at the start of this issue.

**Comment by jaydenseric** [comment]
Here is a minimal reproduction…

In `.vscode/settings.json`:

```json
{
  "deno.enable": true,
  "deno.importMap": "importMap.json"
}
```

In `importMap.json`:

```json
{
  "imports": {
    "b/": "./"
  }
}
```

In `a.js`:

```
// @ts-check
/// <reference path="b/b.d.ts" />
```

In `b.d.ts` you can have anything, it doesn't seem to matter. I've tried these two variations and they have the same result:

```ts
declare namespace B {
  export type A = boolean;
}
```

```ts
declare global {
  namespace B {
    export type A = boolean;
  }
}

export {}
```

The result (after Deno caching `a.js`) is this:

<img width="1408" alt="Screen Shot 2021-12-07 at 3 01 21 pm" src="https://user-images.githubusercontent.com/1754873/144963973-647175df-054c-4538-924f-6f09a2199658.png">

**Comment by jaydenseric** [comment]
If you change `importMap.json` to this:

```json
{
  "imports": {
    "b/": "http://localhost:3004/"
  }
}
```

And run this, the result is the same kind of issue:

```
deno run --allow-net --allow-read https://deno.land/std/http/file_server.ts --port 3004 --cors
```

So it doesn't seem to matter if the mapping is a relative path to a local file, or a HTTP URL.

**Comment by jaydenseric** [comment]
Is this the cause of the Deno bug?

If you copy the resolved code URL from the popup info:

<img width="1390" alt="Screen Shot 2021-12-08 at 11 49 05 am" src="https://user-images.githubusercontent.com/1754873/145128885-9628ef15-9863-4163-b015-b0a624b1d1e3.png">

And look closely at the characters, Deno is inserting a zero width space (unicode U+200b) after the `http`.

Here is the relevent import map entry:

<img width="762" alt="Screen Shot 2021-12-08 at 11 49 32 am" src="https://user-images.githubusercontent.com/1754873/145129109-18c896ae-cd3e-4e08-8546-23d55f2c287f.png">

And if you paste the Deno resolved URL in for comparison, you can see the weird character:

<img width="630" alt="Screen Shot 2021-12-08 at 11 49 54 am" src="https://user-images.githubusercontent.com/1754873/145129158-8afcf52e-bf0e-4266-bf6f-5dad5f70f6b6.png">

If this is just presentational in the tooltip and not what Deno is actually attempting to use when resolving the path, can we please fix it, so that copy pasting the URL from the info box won't lead to frustrating bugs in situations zero-width chars don't display. I only found this because I copied the URL from the tooltip URL into a browser tab and noticed it was searching for the string instead of loading the URL as a page.

**Comment by jaydenseric** [comment]
This issue is blocking me from documenting how to use Deno and import maps to use one of the npm packages I publish. Here is a minimal reproduction of the issue at hand…

In `deno.json`:

```json
{
  "compilerOptions": {
    "lib": [
      "dom",
      "dom.iterable",
      "dom.asynciterable",
      "deno.ns",
      "deno.unstable"
    ]
  },
  "importMap": "importMap.json"
}
```

In `importMap.json`:

```json
{
  "imports": {
    "@types/google.maps": "https://unpkg.com/@types/google.maps@3.49.2/index.d.ts"
  }
}
```

In `demo.mjs`:

```js
// @ts-check
/// <reference types="@types/google.maps" />

/** @typedef {google.maps.MapTypeStyle} MapTypeStyle */
```

Then run `deno check --remote demo.mjs`:

```
Check file://[redacted]/demo.mjs
error: TS2503 [ERROR]: Cannot find namespace 'google'.
/** @typedef {google.maps.MapTypeStyle} MapTypeStyle */
              ~~~~~~
    at file://[redacted]/demo.mjs:4:15
```

<img width="1748" alt="Screen Shot 2022-08-23 at 7 06 25 am" src="https://user-images.githubusercontent.com/1754873/186019867-66f22d4e-011e-410c-a6eb-93d9cf1004d5.png">

Note that the above tripple slash reference way of loading the types works fine in a Node.js TypeScript project.

A big problem is that a workaround of importing types using `import("@types/google.maps").google.maps.MapTypeStyle` syntax doesn't work due to the `deno-ts` error `Cannot import type declaration files`:

<img width="735" alt="Screen Shot 2022-08-23 at 7 12 52 am" src="https://user-images.githubusercontent.com/1754873/186020127-4c3181f9-b863-4e22-99a5-675c82bd83a4.png">
