### ISSUE TITLE
Interrupted: Operation Cancelled

### ISSUE THREAD

**Issue by ebebbington** [denoland/deno#13012]
Found an issue with tcp connections I believe, it's an issue in my own repo, deno_redis and another one of my repos i believe

I think it's specifcally due to tcp connections, here is a workflow where it failed: https://github.com/ebebbington/copytube/runs/4442252902?check_suite_focus=true

Here is a link to the code that is being ran above: https://github.com/ebebbington/copytube/blob/master/src/realtime/tests/unit/redis_test.ts

Any ideas?

**Comment by ebebbington** [comment]
And the other module i was on about: https://github.com/ebebbington/dami/runs/4414405880?check_suite_focus=true

**Comment by bartlomieju** [comment]
You get this error when the underlying resource has a pending operation (eg. read) and is closed. This doesn't seem to be a bug, you should wrap your read operations in `try/catch` and handle `Interrupted` error as a signal that resource is gone.

**Comment by ebebbington** [comment]
ok thanks @bartlomieju :)

**Comment by bartlomieju** [comment]
I'm going to close this issue for now, let me know if you hit any more problems.
