### ISSUE TITLE
`'upgrade' header must contain 'websocket'` with `Deno.upgradeWebSocket` on a website connected to Cloudflare 

### ISSUE THREAD

**Issue by rojserbest** [denoland/deno#13024]
Hello, I have a WS listener running on a server routed to a domain which is connected to Cloudflare, I can access the WS from the server itself, but not outside it.

This is the error I am getting:
```text
Invalid Header: 'upgrade' header must contain 'websocket'
```

This is my code:
```typescript
const listener = Deno.listen({ port: 3444 });

for await (const conn of listener) {
  handleConn(conn);
}

async function handleConn(conn: Deno.Conn) {
  try {
    const httpConn = Deno.serveHttp(conn);

    const requestEvent = await httpConn.nextRequest();

    if (!requestEvent) {
      return;
    }

    const { response } = Deno.upgradeWebSocket(requestEvent.request);

    await requestEvent.respondWith(response);
  } catch (err) {
    const reason = err instanceof Error ? err.message : String(err);
    console.error(`Error handling connection: ${reason}`);
  }
}
```

**Comment by lucacasonato** [comment]
This sounds like Cloudflare is not forwarding the WebSocket request. Is there an option in Cloudflare's dashboard you did not enable?

Without more information, for example the headers that are being sent (log `requestEvent.request.headers`), there is no chance to figure out what is going on here.

**Comment by rojserbest** [comment]
I enabled the WebSocket option on Cloudflare. I will send the headers, in a moment.

**Comment by rojserbest** [comment]
These are the received headers:

```bash
Headers {
  "accept-encoding": "gzip",
  "cdn-loop": "cloudflare",
  "cf-connecting-ip": "XX.XXX.XX.X",
  "cf-ipcountry": "US",
  "cf-ray": "6bad72bd49667215-IST",
  "cf-visitor": '{"scheme":"https"}',
  connection: "close",
  host: "127.0.0.1:3444",
  "sec-websocket-key": "WY1yEJuWr/wjwnqYDYyb/A==",
  "sec-websocket-version": "13",
  "user-agent": "Deno/1.16.2",
  "x-forwarded-for": "XX.XXX.XX.X",
  "x-forwarded-proto": "https"
}
```

**Comment by bnoordhuis** [comment]
Sounds like CF is sanitizing the HTTP request. I'm afraid that's not something we can help you with, try getting in touch with your CF account manager.

**Comment by HaloDragon7410** [comment]
> Sounds like CF is sanitizing the HTTP request. I'm afraid that's not something we can help you with, try getting in touch with your CF account manager.

Deno should simply add `Upgrade: websocket` header to the websocket response header, no?
The Response clearly says that

**Comment by crowlKats** [comment]
This is about the incoming request, not response

**Comment by nicekiwi** [comment]
I had this issue today running a server locally. I assume the issue was that the code is expecting ALL requests HTTP or WS or otherwise to be WS requests, so if any HTTP requests were made they would cause the error as the `upgrade` header IS missing.

My solution was to check for the header

```
async function handleHttp(conn: Deno.Conn) {
  for await (const requestEvent of Deno.serveHttp(conn)) {
    if (requestEvent.request.headers.get('upgrade') === 'websocket') {
      handleSocketRequest(requestEvent)
    } else {
      requestEvent.respondWith(new Response('Technology Equals Might.'))
    }
  }
}
```
