### ISSUE TITLE
Reference Error while processing enum with `--no-check` option

### ISSUE THREAD

**Issue by kt3k** [denoland/deno#13026]
The canary build throws with the following enum (when `--no-check` option is passed):

```ts
export enum Encodings {
  ASCII,
  UTF8,
  BASE64,
  UCS2,
  BINARY,
  HEX,
  BUFFER,
  BASE64URL,
  LATIN1 = BINARY,
}
```
(ref: https://github.com/denoland/deno_std/blob/21e0b73979466202e738f458ff0b9232b21dd4e1/node/internal_binding/_node.ts )

It throws with `ReferenceError: BINARY is not defined` only when `--no-check` is specified.

I guess this might be related to #13025. cc @dsherret

**Comment by kitsonk** [comment]
That feels like really fragile and dodgy code, but it is valid TypeScript.

**Comment by kt3k** [comment]
I didn't know this syntax is possible until I saw the above error..

BTW std now dropped the usage of this syntax. So this issue isn't urgent from std's perspective now. https://github.com/denoland/deno_std/pull/1694

**Comment by dsherret** [comment]
Given:

```ts
var x = 5;
enum Foo {
    a,
    b = a,
    c = b + 1,
    d = 1 + c * x,
    e = 2 * d
}
```

Swc:

```ts
var x = 5;
var Foo;
(function(Foo) {
    Foo[Foo["a"] = 0] = "a";
    Foo[Foo["b"] = a] = "b";
    Foo[Foo["c"] = b + 1] = "c";
    Foo[Foo["d"] = 1 + c * x] = "d";
    Foo[Foo["e"] = 2 * d] = "e";
})(Foo || (Foo = {
}));
```

TypeScript:

```ts
var x = 5;
var Foo;
(function (Foo) {
    Foo[Foo["a"] = 0] = "a";
    Foo[Foo["b"] = 0] = "b";
    Foo[Foo["c"] = 1] = "c";
    Foo[Foo["d"] = 1 + Foo.c * x] = "d";
    Foo[Foo["e"] = 2 * Foo.d] = "e";
})(Foo || (Foo = {}));
```

I'll fix this.

**Comment by dsherret** [comment]
Opened https://github.com/swc-project/swc/pull/3000
