### ISSUE TITLE
`deno bundle` misbehaving output

### ISSUE THREAD

**Issue by tdillon** [denoland/deno#13048]
I'm using Deno's bundle command to create a simple [Lit](https://github.com/lit/lit/) web app.  What I'm finding is the output of `deno bundle` for newer versions of Deno (anything after `1.4.6`) actually changes the behavior of Lit.  No errors are shown in the browser console, but the functionality appears to be broken.  I assume Deno's newer bundling is different somehow and generates different output for the same input.

Here are 3 examples to show the behavior mentioned above.  Browse to any of these pages, click the text, and the bolded text should update if everything is working.

- [✔️ Deno 1.4.6 example - works - main.js created by `deno bundle`](https://tdillon.gitlab.io/-/lit-deno-example/-/jobs/1872440682/artifacts/public/index.html)
- [❌ Deno 1.16.4 example - does not work - main.js created by `deno bundle`](https://tdillon.gitlab.io/-/lit-deno-example/-/jobs/1872451264/artifacts/public/index.html)
- [✔️ Lit Playground example - works - no Deno involvement](https://lit.dev/playground/#project=W3sibmFtZSI6Im1haW4udHMiLCJjb250ZW50IjoiLy8vIDxyZWZlcmVuY2UgbGliPVwiZG9tXCIgLz5cbmltcG9ydCB7aHRtbCwgTGl0RWxlbWVudH0gZnJvbSAnaHR0cHM6Ly9jZG4uc2t5cGFjay5kZXYvbGl0J1xuaW1wb3J0IHtjdXN0b21FbGVtZW50LCBwcm9wZXJ0eX0gZnJvbSAnaHR0cHM6Ly9jZG4uc2t5cGFjay5kZXYvbGl0L2RlY29yYXRvcnMnXG5cbkBjdXN0b21FbGVtZW50KCdteS1lbGVtZW50JylcbmV4cG9ydCBjbGFzcyBNeUVsZW1lbnQgZXh0ZW5kcyBMaXRFbGVtZW50IHtcbiAgQHByb3BlcnR5KClcbiAgc3RhdHVzID0gJyc7XG5cbiAgcmVuZGVyKCkge1xuICAgIHJldHVybiBodG1sYFxuICAgICAgPHA-QmFzaWMgTGl0IGJlaGF2aW9yIHdvcmtzLjwvcD5cbiAgICAgIDxwPkNsaWNrIHRoaXMgdGV4dCB0byB0ZXN0IHJlYWN0aXZlIHByb3BlcnRpZXMgaW4gZXh0ZXJuYWwgZXZlbnRzLjwvcD5cbiAgICAgIDxwPk9uY2UgY2xpY2tlZCwgdGhpcyB0ZXh0IC0-IFs8Yj4ke3RoaXMuc3RhdHVzfTwvYj5dIHdpbGwgYmUgdXBkYXRlZC48L3A-YCBhcyB1bmtub3duIGFzIHN5bWJvbDtcbiAgfVxufVxuXG5jb25zdCBlbGUgPSA8TXlFbGVtZW50PmRvY3VtZW50LnF1ZXJ5U2VsZWN0b3IoJ215LWVsZW1lbnQnKTtcbmVsZS5hZGRFdmVudExpc3RlbmVyKCdjbGljaycsICgpID0-IHtcbiAgY29uc29sZS5sb2coYG15LWVsZW1lbnQgd2FzIGNsaWNrZWQsIHRoZSBzdGF0dXMgd2lsbCBiZSBjaGFuZ2VkIG5leHQuICBjdXJyZW50IHN0YXR1czogWyR7ZWxlLnN0YXR1c31dYClcbiAgZWxlLnN0YXR1cyA9ICdDbGlja2VkISEhJ1xuICBjb25zb2xlLmxvZyhgbXktZWxlbWVudCdzIHN0YXR1cyBoYXMgYmVlbiBjaGFuZ2VkLiAgY3VycmVudCBzdGF0dXM6IFske2VsZS5zdGF0dXN9XWApXG59KTtcbmVsZS5zdGF0dXM9J3dhaXRpbmcgLi4uJztcbiJ9LHsibmFtZSI6ImluZGV4Lmh0bWwiLCJjb250ZW50IjoiPCFET0NUWVBFIGh0bWw-XG48bXktZWxlbWVudD48L215LWVsZW1lbnQ-XG48c2NyaXB0IHNyYz1tYWluLmpzIHR5cGU9bW9kdWxlPjwvc2NyaXB0PlxuIn0seyJuYW1lIjoicGFja2FnZS5qc29uIiwiY29udGVudCI6IntcbiAgXCJkZXBlbmRlbmNpZXNcIjoge1xuICAgIFwibGl0XCI6IFwiXjIuMC4wXCIsXG4gICAgXCJAbGl0L3JlYWN0aXZlLWVsZW1lbnRcIjogXCJeMS4wLjBcIixcbiAgICBcImxpdC1lbGVtZW50XCI6IFwiXjMuMC4wXCIsXG4gICAgXCJsaXQtaHRtbFwiOiBcIl4yLjAuMFwiXG4gIH1cbn0iLCJoaWRkZW4iOnRydWV9XQ)

All of the source code and build commands can be found at 
https://gitlab.com/tdillon/lit-deno-example/.

**Comment by kitsonk** [comment]
There was a significant update landed yesterday in main. Can you please try again with Deno canary? `deno upgrade --canary` or wait until next week for 1.17?

**Comment by tdillon** [comment]
> Can you please try again with Deno canary? `deno upgrade --canary` or wait until next week for 1.17?

I tried with both canary and 1.17.0.  Neither version fixed the issue.

**Comment by tdillon** [comment]
Deno `1.17.2` has resolved my issue.  Besides some very minor formatting differences, the output of `deno bundle` in version `1.17.2` includes the following code which does not exist in the output from `1.17.1`.

```javascript
var own = Object.getOwnPropertyDescriptor(target, property);
if (own && (own.get || own.set)) {
    delete desc1.writable;
    delete desc1.initializer;
```

**Comment by tdillon** [comment]
The issue is back since it was briefly fixed with `1.17.2`.  I'm not sure which version caused the regression.

I've updated my issue reproduction page to simplify everything as well as include a working vanilla Lit implementation.  For simplicity sake, I haven't implemented a page which shows Deno's behavior for each version (that seems like overkill), but I could make that happen if it would be helpful.

https://tdillon.gitlab.io/lit-deno-example/

Hope this helps.

**Comment by codecycleteam** [comment]
@ry Just a feedback | New version release of deno without existing bug fixing will be useless for adoption of deno.
And soon deno will become new node only if we will not solve this soon. See open issues of bugs only in deno here https://github.com/denoland/deno/issues?q=is%3Aissue+is%3Aopen+label%3Abug
Let us know how can we make deno more reliable which will not break existing production workflow atlist.
Awaiting your response.

**Comment by codecycleteam** [comment]
@bartlomieju @kitsonk @piscisaureus @caspervonb @lucacasonato 
It's my humble request to solve this issue. It's breaking our production workflow.
So we are not able to ship new features and releases.
Please understand this urgent need and help to solve this issue.
Just we have tested and still this bug is there in new release v1.21.0
Awaiting your response.

**Comment by willmartian** [comment]
I believe this is the same issue as #14329. 

Using `declare` with the Lit element decorator (as described in that issue) makes the component reactive. 

---

Also, @codecycleteam, it is typically considered rude to tag a bunch of maintainers on an issue. Hopefully this issue will be fixed soon, but in the mean time you can try the workaround above ^

**Comment by tdillon** [comment]
Lit's documentation aligns with #13281.

https://lit.dev/docs/components/properties/#avoiding-issues-with-class-fields

> For TypeScript, you may use class fields for declaring reactive properties as long as the useDefineForClassFields setting in your tsconfig is set to false.

I assume we just have to wait until the spec is finalized for the proper behavior without any sort of workaround.
