### ISSUE TITLE
Unexpected ts compiler error -- Expected ';', '}' or <eof>

### ISSUE THREAD

**Issue by eostermueller** [denoland/deno#13059]
After executing this command:
`deno run main5.ts`

I get this compiler error:

```
error: The module's source code could not be parsed: Expected ';', '}' or <eof> at file:///C:/Users/eoste/Documents/src/typeScript/deserializeUsingMap/main5.ts:18:9
```

....which comes from the code below, where I've appended comments for lines 16, 17, and 18.
I've got two questions here:
one:  I'm not intimately familiar with ts syntax, but still don't understand what's wrong with this.
two:  If this is a valid syntax error, could you improve the error message some how?  I fixed this error by just removing a crlf on line 16, and the error is showing up on 18, and the error doesn't point very directly to the fix -- or at least the fix I found.
Thanks for sharing deno, really love it.
--Erik

```ts
interface Employee {
    id: number,
    name: string,
    salary: number
}
const empArray = [
        { 'id': 1, 'name': 'john', 'salary': 50000 },
        {'id': 2,'name': 'Kiran','salary': 40000}
    ];
	
let typedEmpArray : Employee[];

typedEmpArray = empArray.map(v => 
	{ 
		return 
		{                          //LINE 16: TO FIX MOVE THIS LEFT CURLY TO THE ABOVE LINE
			name: v.name,      //LINE 17:
			id: v.id,          //LINE 18:
			salary: v.salary
		}; 
	}
) as Employee[];

let zeroEmp : Employee = typedEmpArray[0];
let oneEmp : Employee = typedEmpArray[1];
console.log( 'First name: ' + zeroEmp.name + ' Salary: '  + zeroEmp.salary);
console.log( 'First name: ' + oneEmp.name + ' Salary: '  + oneEmp.salary);
```

deno 1.16.4 (release, x86_64-pc-windows-msvc)
v8 9.7.106.15
typescript 4.4.2

**Comment by kitsonk** [comment]
You are running into an issue with ASI as well as invalid JS syntax and part of Deno isn't being helpful. I don't think the code as written though is what you want.

Consider this:

```js
() => {
  return
  {}
}
```

This is actually treated as two statement in the function block. Because of ASI the return value is undefined and the object literal is unreachable.

You also seem to have an extra `};` in there for some reason.

**Comment by dsherret** [comment]
Yeah, this is how JavaScript behaves. To add to what Kitson said, it adds an implicit semi-colon after the `return`. So it treats that like:

```js
return;
{
  name: v.name; // these get parsed as labeled statements
  id: v.id;
  salary: v.salary;
};
```

You can see how the compiler parses that here: https://ts-ast-viewer.com/#code/GYVwdgxgLglg9mABFApgZygCgJSIN4BQixiATilCKUoSXYgIYBciATESQL4HcGiSwEydFly0S5StQ7Fx9Ri3Z1unIA

Perhaps https://github.com/denoland/deno_ast/issues/36 might help improving the diagnostic a bit, but not much. Perhaps swc could be improved to give a better diagnostic when it detects a return statement with an implicitly added semi-colon and syntax errors in the code afterwards, but it would be a bit of work to implement.

**Comment by eostermueller** [comment]
Great thanks for the education, you can close this.

**Comment by johndeighan** [comment]
This is a major bug in JavaScript, introduced by the awful concept of automatic semicolon insertion.
