### ISSUE TITLE
TCP setNoDelay not implemented

### ISSUE THREAD

**Issue by apowers313** [denoland/deno#13057]
[Redis uses `setNoDelay`](https://gist.github.com/apowers313/fb4723691e825e734261b7c14cd58081) which is currently [not implemented in Deno](https://deno.land/std@0.115.0/node/internal_binding/tcp_wrap.ts#L282). Any objections to fixing this? Looks like a simple matter of plumbing the call [from v8](https://github.com/nodejs/node/blob/1c4df352b77514e93a46fb27e996755d45a0b530/src/tcp_wrap.cc#L98) through Rust? Maybe a good first issue to tackle?

**Comment by bnoordhuis** [comment]
I was under the impression we already had it so +1 from me. The corresponding call in Rust land is `tokio::net::TcpStream::set_nodelay()`.
