### ISSUE TITLE
Stabilize test steps API

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#13055]
Nested testing steps API was added in v1.15: https://deno.com/blog/v1.15#nested-testing-api

We should consider stabilizing it for v1.18.

**Comment by ebebbington** [comment]
This would be great, i'm looking forward to using the new API

**Comment by lucasfcosta** [comment]
Hi @bartlomieju, I really liked the detailed proposal that @lucacasonato has put together, and there are many awesome things about it.

As I have been working on quite a few big testing projects in the JS ecosystem (and have written quite a lot about the subject), I do have some thoughts and suggestions for this API, which I've posted [here](https://github.com/denoland/deno/discussions/10771#discussioncomment-1894471).

I understand that comment includes quite a lot of information (and significant updates), but I'd be more than happy to contribute with the code myself. If needed, I'm also happy to discuss synchronously at any time.

Thank you so much for the brilliant work everyone has been doing on this, especially @lucacasonato for putting together the RFC 💖
