### ISSUE TITLE
(likely upstream) Deno accepts syntatically erroneous code and gives a warning upon source mapping

### ISSUE THREAD

**Issue by CrimsonCodes0** [denoland/deno#13063]
I'm not certain if this is an upstream bug with SWC or not, but it may very well be.

This syntactically invalid code,
```js
/**/

{
	class A {
		get a()
		get b()
		get c() { }
	};

	throw new Error("err");
}
```
is accepted by Deno 1.16.4
The error causes the message,
```
Warning Couldn't format source line: Column 11 is out of bounds (source may have changed at runtime)
```
to also appear.

**Comment by CrimsonCodes0** [comment]
Update: just checked, maybe this is https://github.com/swc-project/swc/issues/3013?

**Comment by ihm-tswow** [comment]
@CrimsonCodes0 
It might not be, at least in my previous tests that issue did not affect multiline comments on a single line. See https://github.com/swc-project/swc/issues/2185#issuecomment-978209846

But you can try the newest version that should fix that issue
