### ISSUE TITLE
deno bundle Uncaught ReferenceError in 1.16.4 and canary

### ISSUE THREAD

**Issue by skimhugo** [denoland/deno#13061]
import { cac } from 'https://unpkg.com/cac/mod.ts';

const cli = cac();
cli.option('--type <type>', 'Choose a project type', {
  default: 'node',
});

const parsed = cli.parse();

console.log(parsed.options.type);
console.log(parsed.args);

cmd:

$ deno bundle main.ts bundle.ts
Check file:///main.ts
Bundle file:///main.ts
Emit "bundle.ts" (157.57KB)
$ deno run --no-check bundle.ts --type foo wow 
error: Uncaught ReferenceError: Cannot access 'NodeTypeError' before initialization
class ERR_INVALID_ARG_TYPE extends NodeTypeError {
                                   ^
    at file:///bundle.ts:3344:36

**Comment by bnoordhuis** [comment]
Can you elaborate why you think that's a Deno bug? Was it working pre-1.16.4?

**Comment by nayeemrmn** [comment]
@bnoordhuis It works without bundling, it's an swc bug cc @kdy1

**Comment by skimmilk6877** [comment]
@bnoordhuis It works without bundling, and it failed when bundle it. I tryed 1.16.4 and canary version.

**Comment by jackfiszr** [comment]
Exactly the same happens when running https://deno.land/x/denodb@v1.0.40/mod.ts bundled using deno 1.16.4+canary or 1.13.2 (which is pre-[12086](https://github.com/denoland/deno/issues/12086)).

**Comment by kdy1** [comment]
I tried reproducing it with the latest version of `swc_bundler` and got


```
error: Uncaught SyntaxError: Private field '#init' must be declared in an enclosing class
    EventEmitter.#init(thisArg);
                ^
    at <anonymous> (file:///var/folders/pw/7l7d6f6s6ngb9z17pc912mtc0000gn/T/.tmpjdThri/main.js:3936:17)
', crates/swc_bundler/tests/deno.rs:1218:9

```

It's 

```js
EventEmitter.call = function call(thisArg) {
    EventEmitter.#init(thisArg);
};
```

and I'm not sure if it's a correct syntax.

**Comment by GJZwiers** [comment]
`bundle` is deprecated but on Deno 1.31.3 I get the following error:

```
error: Uncaught ReferenceError: Cannot access 'NodeTypeError' before initialization
class ERR_INVALID_ARG_TYPE extends NodeTypeError {
                                   ^
    at file:///home/geert-jan/repos/repo/bundle.ts:3319:36
```
