### ISSUE TITLE
Deno Blog is not white listed in Facebook

### ISSUE THREAD

**Issue by AbmSourav** [denoland/deno#13082]
I'm not sure about, should I create this issue here...

I founded a Deno developers community in Facebook, [Deno Developers Bangladesh](https://www.facebook.com/groups/deno.devs.bd).
When I try to share Deno blog posts on our Facebook group, they give me the warning below.
Do you have any plan to fix this, or what is the way to fix this issue?

![Facebook's warning](https://user-images.githubusercontent.com/39233955/146041067-4efca757-6c54-4c8e-b4c7-b7fd85910a6f.jpg)

**Comment by lucacasonato** [comment]
We are aware of this, and have reported it to Facebook on multiple occasions, but unfortunately have never gotten a response from them.

**Comment by lucacasonato** [comment]
I am going to close this, as there is unfortunately nothing actionable for us to do, other than to report it again.
