### ISSUE TITLE
Compile without console

### ISSUE THREAD

**Issue by JasperVanEsveld** [denoland/deno#13107]
This was mentioned in a [comment](https://github.com/denoland/deno/issues/9395#issuecomment-782088853) before
It would be nice to have given that [webview_deno](https://github.com/webview/webview_deno) will (hopefully) be updated soon after [deno#12828](https://github.com/denoland/deno/pull/12828) was merged
Which would allow for electron like applications

One way to do this could be with a command like `deno compile --no-console`
That downloads a deno binary that doesn't use the console, similar to how `--target` works

Compiling deno without a console can be done by adding:
`#![windows_subsystem = "windows"]`
To the top of `cli/main.rs`
Or by passing arguments to `rustc`

**Comment by crowlKats** [comment]
Ref https://github.com/denoland/deno/discussions/12941

**Comment by joao678** [comment]
I've managed to solve this with a little workaround: take the .exe generated by deno and somehow change the Subsystem flag in the optional headers of the executable, there is a lot of ways to do this, the most pratical for me is using a python script that does this automatically like so

```python
import subprocess
import shutil
import os
import os.path
import pefile

print('Modifying generated executable subsystem...')
binary = pefile.PE(os.getcwd()+"\\deno_test.exe", fast_load=True)
binary.OPTIONAL_HEADER.Subsystem = 2
binary.write(filename="deno_test.exe")
```

You can also use a program like PE Bear to then open the executable in the program, find the optional headers section and change the subsystem manually

**Comment by svefro** [comment]
this needs to be resolved for us that want to use deno to make small gui apps. like using webUI on windows.

tested python script but got no gui at all then.

**Comment by bartlomieju** [comment]
You can use `--no-console` flag with `deno compile`

**Comment by svefro** [comment]
> You can use `--no-console` flag with `deno compile`
"unexpected argument '--no-console' found"

The parameter is called "--no-terminal" and does not work as intended.
No gui is shown at all on windows.
and application exits right away

**Comment by svefro** [comment]
could not get --no-terminal to work so i made this https://jsr.io/@svefro/win-console-window-state

**Comment by Reububble** [comment]
I've been annoyed by this issue recently and decided to look into what's going wrong. I'm able to get stderr from my compiled exe (using `start /b test.exe 2> stderr`) and that tells me
```
thread 'main' panicked at runtime\worker.rs:696:7:
Bootstrap exception: ReferenceError: null or invalid handle
    at guessHandleType (ext:deno_node/internal_binding/util.ts:38:16)
    at _guessStdinType (ext:deno_node/_process/streams.mjs:137:10)
    at initStdin (ext:deno_node/_process/streams.mjs:162:38)
    at Object.internals.__bootstrapNodeProcess (node:process:683:22)
    at initialize (ext:deno_node/02_init.js:34:15)
    at bootstrapMainRuntime (ext:runtime_main/js/99_main.js:892:7)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at C:\a\deno\deno\runtime\tokio_util.rs:111:36:
called `Result::unwrap()` on an `Err` value: JoinError::Panic(Id(1), ...)
```
Without being familiar with the backend of deno, I interpret this as an issue regressed when adding node support. It's also clear that it's an issue getting stdin. So I've tried my program again, providing a file for stdin, stdout and stderr, and everything works.
`start /b test.exe < stdin > stdout 2> stderr`.
Removing any input/output file results in a failure.

The only reason I was able to debug this at all was because I happened to try `start /b` which I had used in the past to run a no console app while capturing stdout and stderr.

I don't believe this issue should be closed as completed.

**Comment by Reububble** [comment]
I've found https://github.com/denoland/deno/issues/21091 which seems like the right issue
