### ISSUE TITLE
compat: preload Node.js native modules in global vars in node compat REPL

### ISSUE THREAD

**Issue by kt3k** [denoland/deno#13109]
In Node.js, all native modules are available as global variables in REPL:

```shellsession
$ node
Welcome to Node.js v16.9.1.
Type ".help" for more information.
> util
{
  _errnoException: [Function: __node_internal_errnoException],
  _exceptionWithHostPort: [Function: __node_internal_exceptionWithHostPort],
  _extend: [Function: _extend],
  callbackify: [Function: callbackify],
  ...
```

How about doing the same thing with `deno repl --compat --unstable`?

**Comment by bartlomieju** [comment]
For anyone interested in tackling this issue, here are some pointers:

- In `compat/mod.rs` add function `setup_builtin_modules()` that takes `&mut JsRuntime` argument
- For each module listed in `SUPPORTED_MODULES` a variable should be added that requires this module:
```
for mod in SUPPORTED_MODULES {
  let script = format!("const {} = require('{}');", 
  js_runtime.execute_script("setup_builtin.js", script);
}
```
- Added `setup_built_modules` function should be called at the end of this block:
https://github.com/denoland/deno/blob/e5a8588370e01f80a3375aa3396449d8e3f648b7/cli/main.rs#L962-L965

A test needs to be added that checks random modules are available in global scope.

**Comment by VishnuJin** [comment]
I'll would like to work on this !!

**Comment by bartlomieju** [comment]
One note: modules that contain `/` are not available by default in Node's REPL and they should be skipped for Deno as well.

**Comment by VishnuJin** [comment]
@bartlomieju getting `error: Uncaught ReferenceError: require is not defined` :(

**Comment by bartlomieju** [comment]
@VishnuJin please open a PR, it's hard to suggest anything if I don't see the code.

**Comment by bjholifield** [comment]
> #
[https://www.dropbox.com/s/bytcm93wsi2qupy/seekhd%20report%20-%20rivasgenem%40yahoo.com.pdf?dl=0](https://www.dropbox.com/s/bytcm93wsi2qupy/seekhd%20report%20-%20rivasgenem%40yahoo.com.pdf?dl=0)
