### ISSUE TITLE
Tokio swallows panics 

### ISSUE THREAD

**Issue by ry** [denoland/deno#1311]
Here is a demonstration of Tokio swallowing panics: https://gist.github.com/ry/01ed1055964fe5cba8c38839635a5b2d

Apply that patch (after #1310 is landed) and run `deno.readFile("/")`... it should crash but does not.

**Comment by F001** [comment]
Is `blocking` function in `ops.rs` the only way to spawn a task to thread pool?
If that is the case, I'd suggest to `catch_unwind` by ourselves. 

```rust
// wrap the closure running in thread pool
fn abort_when_panic<F, R>(f: F) -> R where F: UnwindSafe + FnOnce() -> R
{
  match std::panic::catch_unwind(f) {
      Err(e) => {
        eprintln!("{:?}", e);
        std::process::abort();
      },
      Ok(r) => r,
  }
}

fn blocking<F>(is_sync: bool, f: F) -> Box<Op>
where
  F: 'static + Send + UnwindSafe + FnOnce() -> DenoResult<Buf>,
{
  if is_sync {
    Box::new(futures::future::result(f()))
  } else {
    Box::new(tokio_util::poll_fn(move || convert_blocking(|| abort_when_panic(f) )))
  }
}
```

**Comment by ry** [comment]
No - it's not the only way to spawn a task. Any callback on a future will be run in the thread pool. For example, this callback is executed in the thread pool
https://github.com/denoland/deno/blob/a8c3b448049912ead5ba025fee9568dcc0786573/src/ops.rs#L667-L683
