### ISSUE TITLE
lsp: add code lens for debugging tests

### ISSUE THREAD

**Issue by jespertheend** [denoland/deno#13130]
I'd like to debug specific tests when writing them. But currently this requires you to type the full command.

I think it would be nice if a second code lens is added that functions identically to the current 'Run Test' lens except for an added `--inspect-brk` flag.
Ideally lsp clients would automatically attach to the inspector port and the debugger would resume once an inspector is attached, so that it would only break on placed breakpoints. But simply running a slightly modified command would already be a huge benefit.

**Comment by jespertheend** [comment]
I prototyped a bit and if the team is happy with this feature I can do a PR.

**Comment by bartlomieju** [comment]
@jespertheend sure, please open a PR so we can try it out!
