### ISSUE TITLE
significant increase in startup time 

### ISSUE THREAD

**Issue by jjallaire** [denoland/deno#13137]
After this commit (updates to support deno_graph API changes: https://github.com/denoland/deno/commit/e8d7b430cecf4357bd9b2ea717266e339516aa19) we are seeing a substantial increase in startup time for a "do nothing" operation (printing help).

This is for a moderate sized CLI application (~25k lines of typescript code): https://quarto/quarto-dev/quarto-cli

Note that this delay is for running Deno against our development tree (i.e. running against ts files). The slowdown does not occur after bundling (i.e.g running against bundled js).

**Comment by bartlomieju** [comment]
This problem will be fixed in 1.17.1 by https://github.com/denoland/deno_graph/pull/89

**Comment by jjallaire** [comment]
Great, thanks!!!!

**Comment by bartlomieju** [comment]
v1.17.1 is now released. I'm going to close this issue now. Please let us know if the problem persists.

**Comment by jjallaire** [comment]
Thanks! That does indeed fully resolve the issue :-)
