### ISSUE TITLE
[WSL2] `Deno` Permission denied (os error 13) 

### ISSUE THREAD

**Issue by mrxiaozhuox** [denoland/deno#13141]
I have try to use `deno` start a `http-web-server` on WSL:
```
error: Uncaught (in promise) PermissionDenied: Permission denied (os error 13)
  const listener = Deno.listen(addr);
    at Object.opSync (deno:core/01_core.js:149:12)
    at opListen (deno:ext/net/01_net.js:38:17)
    at Object.listen (deno:ext/net/01_net.js:204:17)
    at serve (https://deno.land/std@0.92.0/http/server.ts:303:25)
    at new DenlyHttp (https://deno.land/x/denly@V0.25/core/server/http.ts:37:32)
    at new Denly (https://deno.land/x/denly@V0.25/core/denly.ts:129:29)
    at file:///home/mrxiaozhuox/projects/dodot/mod.ts:11:13
```

if I use `sudo` to run the `deno`, its ok. But I think it is not a normal state:

```
sudo ~/.deno/bin/deno -A mod.ts
```

(Because I don't need use `sudo` start a server on my macbook, but I need it on `WSL`, so I think this is a bug.

**Comment by mrxiaozhuox** [comment]
I have try to change deno file owner to `root`, but it is not work:
```
sudo chown root:root ~/.deno/bin/deno
```

**Comment by bartlomieju** [comment]
This is not a problem with a file/exe not being owned by root, but by the fact that you are trying to connect to the port that requires root access (most likely port `80`). Does the problem still happen if you change the port?

**Comment by mrxiaozhuox** [comment]
> This is not a problem with a file/exe not being owned by root, but by the fact that you are trying to connect to the port that requires root access (most likely port `80`). Does the problem still happen if you change the port?

oh, thanks.
