### ISSUE TITLE
`deno bundle` not working with JSON module

### ISSUE THREAD

**Issue by tdillon** [denoland/deno#13150]
I'm testing out the new JSON modules functionality introduced with `1.17.0`.  I'm expecting the `deno bundle` command to be able to handle the JSON module import, but I'm getting an error.  Is this a bug, or is bundling JSON modules not supported?

**./test.ts**
```typescript
import j from './test.json' assert { type: 'json' }
console.log(JSON.stringify(j))
```

**./test.json**

```json
{"foo":"bar"}
```

Console session:

```shell
$ deno --version
deno 1.17.0 (release, x86_64-pc-windows-msvc)
v8 9.7.106.15
typescript 4.5.2

$ deno run test.ts
{"foo":"bar"}

$ deno bundle test.ts
Check file:///C:/.../test.ts
Bundle file:///C:/.../test.ts
error: Unable to output during bundling.

Caused by:
    0: load_transformed failed
    1: Bundler.load() failed
    2: Bundler.loader.load(file:///C:/.../test.json) failed    
    3: Expected ';', '}' or <eof> at file:///C:/.../test.json:1:7
```

**Comment by kitsonk** [comment]
It currently isn't supported, but we don't error with it. We should either figure out how to support it, or error effectively.

**Comment by sisou** [comment]
I just ran into this same issue. Is there a workaround you would recommend? My usecase is loading the package version from a package.json to output from the API (served by Deno).
