### ISSUE TITLE
console.log css styling: colors not working in default apple terminal

### ISSUE THREAD

**Issue by johnspurlock** [denoland/deno#13165]
Colors are not rendered properly using console.log styling on the default terminal on MacOS.  Lighter colors are rendered as gray, and darker colors are rendered as white.

What's strange is that it only affects console log statements with css styling, so I was hoping it is something that can be fixed in Deno itself, logging objects are colored properly in the same process output.

Also, tmux works fine.

See repro and output below

```
$ deno --version
deno 1.17.0 (release, aarch64-apple-darwin)
v8 9.7.106.15
typescript 4.5.2
```

colors_repro.ts
```
console.log({ foo: "green" });
console.log("%cgreen", "color: green");
console.log("%cpink", "color: pink");
console.log(Object.entries(Deno.env.toObject()).filter(v => v[0].startsWith('TERM')));
```

In default apple terminal:
![output-default](https://user-images.githubusercontent.com/528937/146953209-8e2ad9a4-342a-4088-bfc6-c53be52b0e01.png)

In tmux:
![output-tmux](https://user-images.githubusercontent.com/528937/146953217-69ae944b-ffcd-42e4-93f0-089ab61155c7.png)

**Comment by lucacasonato** [comment]
Apple's Terminal.app unfortunately does not support arbitrary rgb, hex, and hsl colors.

**Comment by johnspurlock** [comment]
I see, then how does the other coloring work? like the green "Check" during type checking, and the object output as shown?  Are you able to choose specific colors from a palette or something for those? 

 It would be nice to have whatever color facility is possible for that, open to console.log.  i.e. if green is possible, then `color: green` would also work

**Comment by lucacasonato** [comment]
The reason those work, is that they don't use RGB colors, but use the 16 predefined colors that Terminal.app does support.

I guess we may be able to map the [16 "basic color keywords"](https://drafts.csswg.org/css-color-3/#html4) to these predefined colors. That would go against the spec though, as these colors have specific RGB values specified.

I am impartial here. @nayeemrmn thoughts?

**Comment by nayeemrmn** [comment]
Currently for `%c` colours, any CSS colour keyword is mapped to an rgb value and ansi-fied as `\x1b[38;2;<r>;<g>;<b>m]`. What we should do is for the 8 colour keywords `black`, `blue`, `green`, `red`, `cyan`, `magenta`, `yellow` and `white`, use the matching specific signal `\x1b[<30-37>m`. They would mostly not align with their respective CSS hex values but who cares. More compat and plays better with the CLI ecosystem.

**Comment by lucacasonato** [comment]
Let's do that then :+1:

**Comment by johnspurlock** [comment]
Nice!  That would work great for my use case, I could figure out how to detect Terminal.app and then fallback to those predefined colors

**Comment by zachauten** [comment]
Aside from the 8 color keywords shared between css and ansi, should css using hex or other methods be mapped to specific ansi signals? Currently #0000aa will not map to ansi blue, even though it is the same RGB value.
