### ISSUE TITLE
`deno coverage` shouldn't run type checks

### ISSUE THREAD

**Issue by jespertheend** [denoland/deno#13161]
Consider the following test files
```js
//jsdom.js

import {JSDOM} from "https://esm.sh/jsdom@19.0.0";

export function createDiv() {
	const jsdom = new JSDOM();
	return jsdom.window.document.createElement("div");
}
```
```js
//jsdom.test.js

import {createDiv} from "./jsdom.js";

Deno.test({
	name: "jsdom",
	sanitizeOps: false,
	sanitizeResources: false,
	fn: () => {
		const div = createDiv();
		console.log(div);
	},
});
```
This fails with `deno test` because jsdom has a `.d.ts` file that imports from `'vm'`.
But this can be fixed with `deno test --no-check`.

If you try to generate a coverage report however:
```
deno test --coverage=cov --no-check
deno coverage cov
```
It fails with the same error because the coverage command doesn't have support for the `--no-check` flag.

**Comment by jespertheend** [comment]
Ah never mind, using `https://esm.sh/jsdom@19.0.0?no-check` fixes my issue.

**Comment by lucacasonato** [comment]
That doesn't solve the root issue though. `deno coverage` should not be doing a type check. If it does, that is a bug.

**Comment by jespertheend** [comment]
Ah interesting, I'll look into it.

**Comment by jespertheend** [comment]
Hmm I'm wondering if maybe type checks do need to run after all?
Not sure why the test is failing because I can't replicate it locally. But the failing test seems to import a `.ts` file so I'm sure it's related.

**Comment by nayeemrmn** [comment]
I think there's a discrepancy when you run `deno test --coverage=...` with type check (tsc emit) and then run `deno coverage` without it (swc emit).

`deno coverage` calls `prepare_module_load()` to make the original sources and the emits available. Maybe instead it should interact with the cache directly, assume `deno test --coverage=...` was just called and attempt to piggyback on that cache state.

**Comment by bartlomieju** [comment]
> deno coverage calls prepare_module_load() to make the original sources and the emits available. Maybe instead it should interact with the cache directly, assume deno test --coverage=... was just called and attempt to piggyback on that cache state.

Yes, this is a red flag which I just noticed yesterday when cleaning up some code in `cli/main.rs`. `deno coverage` shouldn't perform any action like loading modules, it should use what's already stored in cache.

**Comment by bartlomieju** [comment]
Related issue in `deno_std`: https://github.com/denoland/deno_std/issues/1581
