### ISSUE TITLE
bundled/compiled code throws exception

### ISSUE THREAD

**Issue by emrul** [denoland/deno#13170]
I have tried the latest Deno release (1.17.0) and also tried canary and I am facing an error `error: Uncaught (in promise) ReferenceError: Cannot access 'NodeTypeError' before initialization` when running my [script](https://github.com/Twingate/labs/blob/master/scripts/js/tg.js) - via `deno bundle` and `deno compile`. The script works fine when executed via `deno run`.  I am not sure if the fact that I need `--unstable` is causing this?

Trying to run the output of `deno bundle` gives me this:
```
error: Uncaught (in promise) ReferenceError: Cannot access 'NodeTypeError' before initialization
class ERR_INVALID_ARG_TYPE extends NodeTypeError {
                                   ^
    at file:///Users/...js/tg.bundle.js:12236:36
```
and indeed, I can see the class `NodeTypeError` is extended before it has been declared.

```
% deno --version
deno 1.17.0+ac06797 (canary, x86_64-apple-darwin)
v8 9.7.106.15
typescript 4.5.2
```

Any pointers would be greatly appreciated.

Reproduction steps:
* Clone repo at [https://github.com/twingate/labs/tree/dev](https://github.com/twingate/labs/tree/dev) and switch to the `dev` branch
* Switch to `scripts/js` directory
* Verify `deno run --allow-all --unstable ./tg.js --help` works (prints usage info.)
* Run `deno bundle --unstable tg.js tg.bundle.js` to create bundle
* Run `deno run --allow-all ./tg.bundle.js --help` and observe that ReferenceError is thrown.

_Originally posted by @emrul in https://github.com/denoland/deno/issues/12086#issuecomment-999151689_

**Comment by Pjort** [comment]
I can confirm I have the same issue, and I am not using `--unstable`.

> deno --version
> deno 1.17.1 (release, x86_64-pc-windows-msvc)
> v8 9.7.106.15
> typescript 4.5.2

 I used to get: `Uncaught ReferenceError: Cannot access 'Response'` see: https://github.com/denoland/deno/issues/12086 but that seems solved now.

Instead the error has now changed to: `ReferenceError: Cannot access 'NodeTypeError' before initialization`
