### ISSUE TITLE
deno.stat does not return file name and path

### ISSUE THREAD

**Issue by kevinkassimo** [denoland/deno#1317]
Noticed this when working on file server. Name and path are set for `readDir` but not for `stat`.

In the meantime, `readDir` does not set mode of file... This should also be fixed

This should be a good first issue. To fix this, contributors might want to look into `src/ops.rs` and inspect `op_stat`, `op_lstat`, `op_read_dir` functions

**Comment by ry** [comment]
On second thought - I'm not sure this is desired. If you're stating something you already know the filename.

**Comment by kevinkassimo** [comment]
@ry `stat` and `readDir` is using a unified `FileInfo` interface, so should contain everything by default. (I prefer not to surprise the user...)
