### ISSUE TITLE
ReadableStreamBYOBReader.read<Float64Array>(view: Float64Array) returns DataView

### ISSUE THREAD

**Issue by yskszk63** [denoland/deno#13176]
When I ran the following code, it resulted in unexpected behavior.

```typescript
Deno.test('1.0f from bytes.', () => {
  const b = new Uint8Array([
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0xF0, 0x3F,
  ]);
  const f = new Float64Array(b.buffer);
  a.assertEquals(String(f), "1"); // Okay
});

Deno.test('1.0f from bytes via BYOB stream.', async () => {
  const b = new Uint8Array([
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0xF0, 0x3F,
  ]);
  const response = await fetch(URL.createObjectURL(new Blob([b])));
  if (!response.body) { throw new Error(); }

  const reader = response.body.getReader({ mode: 'byob' });
  const view = new Float64Array(1);
  // ReadableStreamBYOBReader.read<Float64Array>(view: Float64Array): Promise<ReadableStreamBYOBReadResult<Float64Array>>
  const result = await reader.read(view);
  a.assertEquals(result.done, false);
  a.assertEquals(Object.getPrototypeOf(result.value).constructor.name, 'Float64Array');
  // ...
  // failures:
  // 
  // 1.0f from bytes via BYOB stream.
  // AssertionError: Values are not equal:
  // 
  // 
  //    [Diff] Actual / Expected
  //
  //
  // -   DataView
  // +   Float64Array
  // ...
});
```

## Expect

ReadableStreamBYOBReader.read<Float64Array>(view: Float64Array) returns
`{ value: Float64Array, done: false }`

## Actual

ReadableStreamBYOBReader.read<Float64Array>(view: Float64Array) returns
`{ value: DataView, done: false }`

## Version

```bash
$ deno --version
deno 1.17.0 (release, x86_64-unknown-linux-gnu)
v8 9.7.106.15
typescript 4.5.2
```

**Comment by yskszk63** [comment]
Is it because there is no `Float64Array` here?
<https://github.com/denoland/deno/blob/0f0dd5b7ec2a7ac95e1b36c866f73b85e4fb4879/ext/web/06_streams.js#L1269-L1282>

https://streams.spec.whatwg.org/#readable-byte-stream-controller-pull-into
> 4. If view has a [[TypedArrayName]] internal slot (i.e., it is not a DataView),
>    1. Set elementSize to the element size specified in the typed array constructors table for view.[[TypedArrayName]].
>    2. Set ctor to the constructor specified in the typed array constructors table for view.[[TypedArrayName]].

**Comment by lucacasonato** [comment]
> Is it because there is no Float64Array here?

Correct.

In addition to adding to that list there, we also need to add a WPT to test to prevent this from regressing in the future.
