### ISSUE TITLE
Support for using a specific TypeScript version

### ISSUE THREAD

**Issue by jespertheend** [denoland/deno#13189]
In VSCode you can configure a specific TypeScript version using the `typescript.tsdk` setting. This can be useful if you want to ensure everyone on the team is using the same tsc version for error reporting, or if you want to use an insiders version of TypeScript for instance.
Similarly, if you wish to bundle your project using tsc directly, you could `npm install typescript@someversion` and run typescript from your `node_modules` path.

I think it could be useful, especially for the lsp, bundle and compile commands, to be able to configure what version of tsc should be used. To ensure nothing unexpected happens, or in case you want to use tsc with modifications made to it.

**Comment by bartlomieju** [comment]
Deno ships with an embedded TypeScript compiler which deeply integrates with the rest of CLI infrastructure. It's not really possible to make it configurable, nor is it feasible to ship Deno with multiple versions of the compiler. I'm afraid this is a design limitation that we won't be able to overcome.

**Comment by dsherret** [comment]
This would be incredibly hard to support. On top of the challenge of making the compiler code swappable, we use the TS compiler API which is an unstable API with no semver guarantees. There can be breaking changes even in patch versions of TypeScript. VSCode can do this version swapping reliably because it communicates to TypeScript via the LSP protocol, which is stable.

**Comment by jespertheend** [comment]
Ah that's too bad, but understandable. To be honest I haven't run into any major issues as a result of the locked TypeScript version yet. Just some features that have recently released that aren't available in Deno yet.
If the TS compiler API gets more stable in the future, would that make this more feasible?
