### ISSUE TITLE
streams: array buffer transfer unnecessarily (?) copies buffer

### ISSUE THREAD

**Issue by matthewleon** [denoland/deno#13180]
I encountered this issue while attempting to resolve https://github.com/denoland/deno_std/issues/1739

For BYOB reading of readable byte streams, it is important that the user-provided buffer be filled. However, the current implementation of the `TransferArrayBuffer` algorithm (https://streams.spec.whatwg.org/#transfer-array-buffer) creates a `transferedIshVersion` of the provided buffer, copying it via `slice`:

https://github.com/matthewleon/deno/blob/c91da1222b1a57a38aad4bca7af7fe88d8ef2476/ext/web/06_streams.js#L232

I imagine this was done on purpose, but I can't find any documentation of the decision.

The code was written by @kitsonk _before_ the merge of support for BYOB, so perhaps this was a detail that @crowlKats left out of the implementation?

**Comment by kitsonk** [comment]
There weren't really userland APIs at the time that allowed following the spec precisely, so the "transferred ish" is as close as we could get.  I don't know if we can do something better now or not to more closely align to the spec.

**Comment by lucacasonato** [comment]
Yup, we can. `core.serialize` and `core.deserialize` can now properly "transfer" array buffers, so we should use that.

**Comment by matthewleon** [comment]
@lucacasonato is the idea here that you do a `serialize` with only the `transferredArrayBuffers` option in order to mark the buffer as transferred, followed by a `deserialize` to create the arraybuffer that references the same memory? It's not obvious to me from the Rust source and its usage (only in `13_message_port.js`) how this would be done. The corresponding functionality in Node, for example, has straightforward methods like `serializer.transferArrayBuffer`.
