### ISSUE TITLE
Side-effect import assertion parse failure

### ISSUE THREAD

**Issue by nayeemrmn** [denoland/deno#13183]
```js
// temp.js
import "./temp.json" assert { type: "json" };

// temp.json
{}

// deno run temp.js
```
```
error: The module's source code could not be parsed: Expected ';', got 'assert' at file:///home/nayeem/projects/deno/temp.js:1:22
```

**Comment by kitsonk** [comment]
I get it us a bug, but "side effect JSON"... how can JSON modules have side effects?

**Comment by kitsonk** [comment]
It is part of the spec though: https://tc39.es/proposal-import-assertions/

**Comment by nayeemrmn** [comment]
Yes the assertion syntax is agnostic of JSON modules and isn't tied to module types that don't have side effects.

**Comment by kitsonk** [comment]
swc bug opened: https://github.com/swc-project/swc/issues/3103
