### ISSUE TITLE
Missing ListFormat types?

### ISSUE THREAD

**Issue by chasm** [denoland/deno#13199]
I can do this in the REPL and it works:

```ts
new Intl.ListFormat("en", {
    style: "long",
    type: "conjunction",
}).format(['red', 'green', 'blue']) // returns "red, green, and blue"
```

But if I put the same code in my Deno application, I get:

```sh
[ERROR]: Property 'ListFormat' does not exist on type 'typeof Intl'.
```

when I try to bundle it.

**Comment by kitsonk** [comment]
Can you provide a full reproduction and include the output of `deno --version`.

**Comment by chasm** [comment]
This is literally my entire code in a file called `mod.ts`:

```ts
const ListFormatter = new Intl.ListFormat("en", {
	style: "long",
	type: "conjunction",
});

console.log(ListFormatter.format(["apples", "pears", "peaches", "plums"]));
```

Here's what happens when I run it:

```sh
[listFormat] deno run ./mod.ts
Check file:///Users/chasm/Workspace/listFormat/mod.ts
error: TS2339 [ERROR]: Property 'ListFormat' does not exist on type 'typeof Intl'.
const ListFormatter = new Intl.ListFormat("en", {
                               ~~~~~~~~~~
    at file:///Users/chasm/Workspace/listFormat/mod.ts:1:32
```

Here is the output of `deno --version`:

```sh
[listFormat] deno --version
deno 1.17.1 (release, x86_64-apple-darwin)
v8 9.7.106.15
typescript 4.5.2
```

Here is what happens when I do the same thing in the REPL:

```sh
[listFormat] deno
Deno 1.17.1
exit using ctrl+d or close()
> const ListFormatter = new Intl.ListFormat("en", {
	style: "long",
	type: "conjunction",
});

console.log(ListFormatter.format(["apples", "pears", "peaches", "plums"]));
apples, pears, peaches, and plums
undefined
>
```

As the output is correct, clearly `Intl.ListFormat` _does_ exist in Deno. The problem appears only when it is type checked.

Ideas? Is there a workaround?

**Comment by crowlKats** [comment]
This is an issue with typescript itself: https://github.com/microsoft/TypeScript/issues/46907

**Comment by chasm** [comment]
Thanks. I'll check on it there.

**Comment by andreubotella** [comment]
We have added built-in APIs to the Typescript definition files when a version of Deno would ship with those APIs but Typescript didn't support them yet (see #11443, for example). The differences here is that `Intl.ListFormat` shipped a while ago (browser-compat-data lists it as shipping in Chrome 72) and apparently no one noticed until now, and that there isn't yet even a PR for adding the definitions. But I don't see why we couldn't open a PR to Typescript and float the patch in Deno while it gets reviewed.

**Comment by chasm** [comment]
That would be awesome...
