### ISSUE TITLE
Pointer added support for converting u16 strings directly

### ISSUE THREAD

**Issue by 274820472** [denoland/deno#13192]
- Added support for converting u16_string directly to deno ffi data Pointers.  
I'm not sure it's worth it,  
But Windows' heavily w-suffix apis, such as MessageBoxW, require a lot of conversion,  
As an infrastructure, rust packaging API is used to encode and decode, with better performance than JS.  

    
    function cstr2ptrW(cstr) {
         const buffer = new ArrayBuffer((cstr.length + 1) * 2);
         const u16 = new Uint16Array(buffer);
         for (let i = 0; i <= cstr.length; i++) {
               u16[i] = cstr.charCodeAt(i);
         }
         return Deno.UnsafePointer.of(u16);
    }
    function ptr2cstrW(ptr) {
         const view = new Deno.UnsafePointerView(ptr);
         let x = 0;
         const arr = [];
         while (1) {
               const u16 = view.getUint16(x);
               if (u16 === 0) {
                     break;
               }
               arr.push(String.fromCharCode(u16));
               x += 2;
         }
         return arr.join("");
    }
      
      const view = new Deno.UnsafePointerView(ptr);
      view.get_string_u16() === ptr2cstrW(ptr); // like this

**Comment by Serendipithub** [comment]
pointer is too complicated for a script language
