### ISSUE TITLE
lsp: support `@link` to symbol in JSDoc markdown

### ISSUE THREAD

**Issue by jespertheend** [denoland/deno#13198]
**To Reproduce**

1. Create a .js file:
```js
function foo() {}

/**
 * Go to {@link foo}
 */
function bar() {}
```
2. Hover over `bar`

**Expected behavior**

The description contains a clickable link that goes to `foo`

**Screenshots**

https://user-images.githubusercontent.com/2737650/147365557-93498aec-9cb2-4e22-a3df-8f39c87dbfc5.mp4

**Versions**

vscode: `1.63.2` deno: `1.17.1` extension: `v3.9.2`

**Comment by kitsonk** [comment]
The built-in TypeScript plugin in vscode special cases the `{@link}` JSDoc tag, it is logic that we would need to integrate into the Deno language server.

**Comment by jaydenseric** [comment]
Also support needs to be added for `@linkcode` and `@linkplain`; they are ["standard" JSDoc](https://jsdoc.app/tags-inline-link.html) and are supported by TypeScript in VSCode. `@linkcode` is particularly handy.
