### ISSUE TITLE
Rewrite tools/format.py in deno

### ISSUE THREAD

**Issue by ry** [denoland/deno#1319]
You can use this as an example: https://github.com/denoland/deno/pull/1216

**Comment by djKooks** [comment]
@ry thanks! I'll send PR when ready.

**Comment by eventualbuddha** [comment]
@djKooks any progress on this? If not, I’d be interested in taking a crack at it.

**Comment by djKooks** [comment]
@eventualbuddha currently working on it. Thanks~

**Comment by ry** [comment]
@djKooks Have a look at https://github.com/denoland/deno_std/blob/master/format.ts

**Comment by djKooks** [comment]
@ry could you check PR #1366 which ported format.py to deno, or assign reviewer? I don't know who is the collaborator for this part.
But there are still several problem. I wrote about it on PR. Hope someone could help...

**Comment by 198893** [comment]
Please delete or✔unsubscribe my account/email!
