### ISSUE TITLE
The program crashes when infinite recursion happens on windows

### ISSUE THREAD

**Issue by kt3k** [denoland/deno#13196]
The following script exits without error on macOS, but it crashes with error message `thread 'main' has overflowed its stack` on Windows.
```js
function f() {
  f();
}
try {
  f();
} catch {}
```

(`f()` throws `RangeError: Maximum call stack size exceeded` and it can be caught on macOS, but it crashes without throwing js error on windows.)

**Comment by bnoordhuis** [comment]
Probably caused by V8 guessing the stack size wrong. Does it work with `--v8-flags=--stack_size=512`? Try different values.

**Comment by kitsonk** [comment]
I actually suspect this is an swc parsing error, versus it failing in v8? There are several of these we have noticed on windows, and windows only, which run "fine" on other platforms.  cc/ @dsherret

**Comment by dsherret** [comment]
I think this was a v8 issue. It no longer happens so I'm going to close it.

**Comment by StoneCypher** [comment]
This appears to be supported as an swc error by #15117

**Comment by kt3k** [comment]
@dsherret Does the below pass on windows?

```
deno test -A cli/tests/node_compat/test.ts -- test-fs-readdir-stack-overflow.js
```
