### ISSUE TITLE
Remove buildin typescript compiler

### ISSUE THREAD

**Issue by KnisterPeter** [denoland/deno#132]
Hi Ryan,

as discussed with you after your talk on JSConf, I would propose to remove the building typescript compiler. It could be easily supported by precompile your application and run the result in deno.
The build-in version of typescript will otherwise always be a bit outdated or you tie the deno release cycle to typescripts release cycles.

Otherwise: Keep going, this rocks :+1:

**Comment by kitsonk** [comment]
Personal opinion, but I disagree. The same logic could be used for v8, and that demo should be decoupled from the JavaScript engine.

While there is risk of breaking changes in any dependency, it is something that can be managed.

The assumption that you can have the whole programme to transpile would mean that remote TypeScript modules would not be possible. Bring able to support remote TypeScript modules that are still treated in a type safe way is a huge advantage of demo IMO.

**Comment by KnisterPeter** [comment]
Importing untranspiled typescript scripts would be removed then, you are right.
But I (personally) don't see that many value in it. But that may be only my opinion.

**Comment by kitsonk** [comment]
@ry, as a side note, I have noticed a few things in the interfacing with TypeScript the could be more efficient. I realise that it must be like herding cats at the moment with all the input, so I won't distract you further at the moment, but if/when you want help with the next version of Demo, I would be glad to try to help make the TS interface as efficient as possible.
