### ISSUE TITLE
compat: failed to import "react" from ESM module

### ISSUE THREAD

**Issue by SinaMobasheri** [denoland/deno#13200]
I try to use [ink](https://github.com/vadimdemedes/ink) library from [npm](https://www.npmjs.com/package/ink) so i run `npm install ink react` and `deno run --compat --unstable --allow-net --allow-read script.jsx`

*script.jsx*
```jsx
import React, {useState, useEffect} from 'react';
import {render, Text} from 'ink';

const Counter = () => {
	const [counter, setCounter] = useState(0);

	useEffect(() => {
		const timer = setInterval(() => {
			setCounter(previousCounter => previousCounter + 1);
		}, 100);

		return () => {
			clearInterval(timer);
		};
	}, []);

	return <Text color="green">{counter} tests passed</Text>;
};

render(<Counter />);

```
base on what i can understand from [compatibility mode](https://deno.land/manual@v1.17.1/npm_nodejs/compatibility_mode) it must have no issues..., maybe i miss something ... i don't know here is output  
![output](https://user-images.githubusercontent.com/60809106/147381919-2f14fe1c-3621-48f2-b8fe-f968881ceed0.png)

**Comment by bartlomieju** [comment]
This is most likely related to https://github.com/denoland/deno/issues/12648; `react` is distributed as a CJS module and interoperability between ESM and CJS is still a bit lacking in Deno.

**Comment by bartlomieju** [comment]
Okay, we got a way forward to providing this integration. Currently blocked by https://github.com/denoland/deno_graph/issues/97
