### ISSUE TITLE
Import map not resolving import

### ISSUE THREAD

**Issue by papiro** [denoland/deno#13204]
Given this `importmap.json`:
```
{
    "imports": {
        "http": "https://deno.land/std@0.119.0/http/server.ts"
    }
}
```

`deno run mod.ts --import-map importmap.json` is failing on line 1:
```
import { Server } from "http";
```
with the following error:
```
error: Relative import path "http" not prefixed with / or ./ or ../
    at file:///Users/pierre/deno-livereload/mod.ts:1:24
```

Running deno@1.17.1

I would expect this to succeed, as it does when I import the file into a test and run the tests.

**Comment by nayeemrmn** [comment]
Change
```sh
deno run mod.ts --import-map importmap.json
```
to
```sh
deno run --import-map importmap.json mod.ts
```
The runtime flags must come before the script name.

**Comment by papiro** [comment]
🤦
