### ISSUE TITLE
Remove `"uncaught"` when creating JsError in core

### ISSUE THREAD

**Issue by crowlKats** [denoland/deno#13212]
in https://github.com/denoland/deno/blob/07618c861e27e284cae3a309783ef78dcef611dd/core/error.rs#L192-L200 we add `"uncaught"` to the error message. this feels quite out of place for core, but rather something for CLI to do. also a blocker for #13209

**Comment by nayeemrmn** [comment]
This is how V8 formats exception messages, that code is a recreation of what V8 would normally give us. I think instead we can clarify the fields with `message: Option<String>, exception_message: String`
