### ISSUE TITLE
`console.log` doesnt print error cause if it isnt an `Error`

### ISSUE THREAD

**Issue by crowlKats** [denoland/deno#13213]
In case of `new Error("foo", { cause: "bar" })`, the cause will not be printed, even though it is valid. Also FF does prints it.

**Comment by petamoriken** [comment]
I didn't know.

**Comment by petamoriken** [comment]
new Error("foo", { cause: 1 }

<img width="243" alt="スクリーンショット 2021-12-28 9 59 35" src="https://user-images.githubusercontent.com/2622837/147516607-7ff84675-b737-4152-bcdb-b76da632b7d1.png">

Looks like it should be recursive.

**Comment by petamoriken** [comment]
It may be better to set a limit on the number of `Caused by`

**Comment by crowlKats** [comment]
Ref https://github.com/denoland/deno/pull/13209, there we will not limit by a number, but check if there isnt the same Error recursing

**Comment by petamoriken** [comment]
We may need to change the display result of normal objects as well.

Deno
<img width="335" alt="スクリーンショット 2021-12-28 10 28 07" src="https://user-images.githubusercontent.com/2622837/147526393-7a32b7f8-7fa3-4b02-a835-61233b8319cb.png">

FF
<img width="320" alt="スクリーンショット 2021-12-28 10 28 28" src="https://user-images.githubusercontent.com/2622837/147526397-53a2df64-9229-4b43-98c1-3568d86fbdbc.png">

**Comment by petamoriken** [comment]
Related: https://github.com/tc39/proposal-error-stacks/issues/41

**Comment by petamoriken** [comment]
Related: https://github.com/tc39/proposal-error-stacks/issues/41

**Comment by crowlKats** [comment]
This was fixed in https://github.com/denoland/deno/pull/13555
