### ISSUE TITLE
Installation Failure

### ISSUE THREAD

**Issue by basicfunc** [denoland/deno#13215]
Hey, there!
I'm trying to install `deno` on my environment, today and copied command `curl -fsSL https://deno.land/install.sh | sh
` from [deno](deno.land).
But, nothing goes as expected

```
~ ❯ curl -fsSL https://deno.land/install.sh |sh
sh: 1: Syntax error: redirection unexpected
``` 

Then, I also tried opening URL form web browser and it landed me on website and curling this website results in HTML of web page. Running on `GNU bash, version 5.1.8(1)-release (x86_64-unknown-linux-gnu)` on [Void Linux](https://voidlinux.org).

**Comment by basicfunc** [comment]
Following, [latest commit](https://github.com/denoland/dotland/commit/af471e20d15666d7b96833d6c43c4b71b472a2fa0), it seems like `curl -fsSL https://deno.land/x/install/install.sh | sh` is appropriate command rather than newly `curl -fsSL https://deno.land/install.sh | sh`

**Comment by dsherret** [comment]
Thanks for reporting this. It was reverted in https://github.com/denoland/dotland/pull/1978
