### ISSUE TITLE
Support compat mode in deno test

### ISSUE THREAD

**Issue by Soremwar** [denoland/deno#13227]
As indicated by the title

This would be useful to run other test runners assertions under `deno test` and easing the migration of node codebases into Deno

Would be specially useful for deno_std, where the Node native tests are run as a subprocess instead of being run directly under compat mode (this is really annoying for local debugging, specially with average CPUs)

**Comment by bartlomieju** [comment]
The first step is to update set up code for worker in `cli/tools/test.rs`:
https://github.com/denoland/deno/blob/42777f25416ca292c56587e6cc4dfe9f50bebd81/cli/tools/test.rs#L455-L460

The setup will be mostly the same like in `cli/main.rs`:
https://github.com/denoland/deno/blob/42777f25416ca292c56587e6cc4dfe9f50bebd81/cli/main.rs#L1154-L1182

Specifically this bit needs to be updated: 
https://github.com/denoland/deno/blob/42777f25416ca292c56587e6cc4dfe9f50bebd81/cli/tools/test.rs#L477-L481

I expect that we will need to tweak some type checking settings, as running multiple test files will cause to type check of `deno_std/node` multiple times, but it's a something that can be addressed in follow up PRs.
