### ISSUE TITLE
Support passing `ReadableStream` to `Deno.writeFile`

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#13229]
This would make streaming data to disk really easy. `writeFile` cancellations should be propagated into the readable stream reading. Only `ReadableStream<Uint8Array>` would be allowed. `writeTextFile` would allow `ReadableStream<string>`.

This would be in addition to allowing `Uint8Array` / `string` as we do now.

**Comment by bartlomieju** [comment]
This is reasonable and we should implement this. PRs are very welcome!

**Comment by wwoast** [comment]
https://github.com/denoland/deno/issues/19697 tracks a bug in the passing of `ReadableStream` to `Deno.writeFile`. I uncovered the same bug last night when I was looking for ways to get rid of my use of `streams/copy`, prior to discovering the newer `io/copy`.
