### ISSUE TITLE
Add output argument to `deno coverage` when used with `--lcov`

### ISSUE THREAD

**Issue by x80486** [denoland/deno#13236]
I think it's better to provide an option to pipe the output to a file of `deno converage cov_profile/ --lcov` instead of using `>`, which is not supported in every operating system, AFAIK.

Something like `deno converage cov_profile/ --lcov --output=path/to/lcov.info` — possibly suppressing any output from `lvoc`, if any.

**Comment by bartlomieju** [comment]
I think this is reasonable request. We might skip `--output` and do what `deno bundle` does already:
```
// output to stdout
deno bundle main.js

// output to main.bundle.js
deno bundle main.js main.bundle.js
```

**Comment by VishnuJin** [comment]
@bartlomieju I would like to work on this issue !!
