### ISSUE TITLE
Deno --output should create the directory structure if provided instead of failing with "No such file or directory"

### ISSUE THREAD

**Issue by x80486** [denoland/deno#13233]
While doing `deno bundle` or `deno compile`, when `--output` is provided, and the same contains a directory structure, the command fails stating `No such file or directory`.

I believe this should be changed and Deno should create the provided directory structure automatically (a la `mkdir --parents`), in the same way `--coverage` does for `deno test`.

**Comment by bartlomieju** [comment]
I think this is reasonable to lower DX friction. @kitsonk is this okay to you?

**Comment by kitsonk** [comment]
Seems logical.

**Comment by rabingaire** [comment]
Hey guys can I work on this?

**Comment by bartlomieju** [comment]
@rabingaire please do

**Comment by bartlomieju** [comment]
Closed in #13299
