### ISSUE TITLE
`Deno.memoryUsage()` is not a function in Worker context

### ISSUE THREAD

**Issue by MierenManz** [denoland/deno#13245]
```
error: Uncaught (in worker "WebSocket Server") (in promise) TypeError: Deno.memoryUsage is not a function
```
It seems like workers don't have this api.
Other api's and the deno namespace are available though
I'm not sure if this is intentional or not but I would really like to have this function exposed to workers aswell.

**Comment by bartlomieju** [comment]
This is indeed a bug, `memoryUsage` is never assigned to global scope in worker context. I don't see a reason why it shouldn't work in workers.
