### ISSUE TITLE
Where to explore new components?

### ISSUE THREAD

**Issue by ShiningRay** [denoland/deno#1324]
If deno has no centralized repository for packages, how can we find new components?

**Comment by kevinkassimo** [comment]
Deno already has a registry prototype ([see here](https://github.com/denoland/registry)). It serves as pointers to scripts that are hosted elsewhere.

I would expect someone to build a package search page for it.

**Comment by ry** [comment]
https://deno.land/x/ has a list of redirects

**Comment by ShiningRay** [comment]
Great! 
But according to my own experience of npm or similar package repository in other languages, this is not enough.
We can see most packages on npm are immature or unmaintained for a long time.
Most developers are bothered to spend lot of time to compare and select suitable packages.
Maybe we can build something like http://www.ruby-toolbox.com/.
A good mechanism to recommend, rate,  criticize packages may be great for the community.

**Comment by hayd** [comment]
This is probably an issue for https://github.com/denoland/registry/ rather than deno itself.

That said, anyone can do this already, I think this problem is likely to solve itself if/when the number of deno packages becomes overwhelming...

**Comment by ry** [comment]
I think I will be moving the registry into //website in deno actually. I think it's better to manage it by git rather than by firebase.

**Comment by cdaringe** [comment]
I added my own prototype in https://github.com/denoland/deno/issues/1478

**Comment by ry** [comment]
Also check out
https://github.com/denoland/deno_std/
https://github.com/denolib/awesome-deno
