### ISSUE TITLE
`deno repl --eval-file`

### ISSUE THREAD

**Issue by somebody1234** [denoland/deno#13256]
an `--eval-file` commandline option may be useful? since `--eval <pasted code>` is little different from `deno repl` then pasting the code in.
plus with longer code and/or code with multiple lines, i think it would quickly become quite unwieldy

**Comment by kitsonk** [comment]
How would `--eval-file` differ from `deno run`?

**Comment by somebody1234** [comment]
because it's for `deno repl`?
i.e. it'd function exactly the same as current `deno repl --eval` - as a prelude to set up the repl environment

**Comment by bartlomieju** [comment]
I think this is actually very reasonable request. @dsherret what do you think?

**Comment by dsherret** [comment]
This was discussed a bit in #11317.

How this should work is a bit ambiguous—should local variables from the provided module become available in the repl or should only exports?

There's already a non-abiguous way to do this so I'm not sure how much value having an `--eval-file` flag would add:

```ts
deno repl -eval "import * as myModule from './relative-path-to-file.ts';"
deno repl -eval "import { someValue, otherValue } from 'file:///absolute/path-to-file.ts';"
deno repl -eval "import { someValue, otherValue } from 'https://deno.land/x/something.ts';"
```

**Comment by somebody1234** [comment]
as you said, there's already a non-ambiguous way to do the latter, so it's the former I'm interested in. especially being able to add global variables without the nasty `Object.defineProperty` hacks the node compatibility scripts use.

**Comment by somebody1234** [comment]
basically the idea is, I'm assuming people would seldom use `--eval` since you could just, well `deno repl` as usual and manyally `import` (as usual)

of course, there are added benefits like being IDE support for checking the code now that it's in its own file and not, say, in a string literal in a shell script

**Comment by somebody1234** [comment]
importing members manually could work, but assuming the repl is intended for rapid prototyping generally you'll probably want to, say, import *every* exported member from several modules, which could quickly become tedious to type every time.

... well tbh it'd be tedious to type even with the above, relatively short, examples imo. i guess thats partly because I'm not a very fast typer

but anyway tl;dr i guess usefulness would depend very heavily on what the repl is actually intended for/what are the most common intended usecases

**Comment by bartlomieju** [comment]
Implemented in https://github.com/denoland/deno/pull/14247
