### ISSUE TITLE
Flags sanitizeOps and sanitizeLeaks don't work

### ISSUE THREAD

**Issue by Fidelion** [denoland/deno#13252]
When passing these object properties within test method as false test still fail and terminal displays error of ops and resource leak. Is this an internal error you guys are working to fix? Deno std version is 0.19.0

**Comment by lucacasonato** [comment]
Could you provide a reproduction? This is not a known error.

**Comment by Fidelion** [comment]
Sure,

Here's the sample code

import { assertEquals, assertNotEquals } from "https://deno.land/std@0.119.0/testing/asserts.ts";

Deno.test({
    name: "ops leak",
    sanitizeOps: false,
    fn() {
        setTimeout(console.log, 10000);
    }
});

Deno.test({
    name: "resource leak",
    sanitizeResources: false,
    async fn() {
        await Deno.open("./somefile.ts");
    }
});
