### ISSUE TITLE
add --allow-write-max-size permission

### ISSUE THREAD

**Issue by elycheikhsmail** [denoland/deno#13251]
is technicaly possible to create permission for max size for  file to write ?

**Comment by kitsonk** [comment]
Nothing is impossible, but it is impractical to implement. What is the use case?

**Comment by elycheikhsmail** [comment]
> Nothing is impossible, but it is impractical to implement. What is the use case?

thank you
use cases in the future :
- possibility to implement desktop stor with security in mind like appStore but for desktop
- if deno deploy implement or mock Deno.write with limited storage it give possibility of test
- if some create new mobile system based on deno ( vs android java, ios c#..)  it will be usefull for control storage size

**Comment by bnoordhuis** [comment]
The limit can't really be enforced when there are concurrent writers because of TOCTOU issues.

I'm going to close this but thanks for the suggestion.
