### ISSUE TITLE
weird caching issue with `deno repl`?

### ISSUE THREAD

**Issue by somebody1234** [denoland/deno#13259]
i was getting this weird error previously:
```
$ deno repl --eval 'import {} from \"./cli.ts\"'
error in --eval flag. Uncaught TypeError: Relative import path "cli.ts" not prefixed with / or ./ or ../
```
note the missing `./` in the error message
same happened with this:
```
$ deno repl
> import {a} from './cli.js'
Uncaught TypeError: Module not found "file:///C:/path/to/cli.js".
```
oddly enough, i created a dummy file `cli.js` (empty), tried to import that, and it worked. then i tried to import `cli.ts` without exiting repl, and it worked

unfortunately, i don't think i can repro so feel free to close it i guess?

chances are it was from me ctrl+c-ing when it was typechecking or something.

**Comment by somebody1234** [comment]
oh, it was using powershell on windows - however i'm 100% sure it's *not* from escape sequences, since:
- i tried various escapes, which worked as expected
- as mentioned, i tried *exactly the same thing* after doing that other thing (both in shell and repl) and it worked
- i tried importing in repl before doing the other thing and got the exact same error.

(but of course, feel free to just close anyway since it should be a pretty rare occurrence anyway)

**Comment by bartlomieju** [comment]
@somebody1234 I'm going to close it for now then, please let us know if the problem happens again.
