### ISSUE TITLE
Replace uses of `instanceof` in runtime code with `ObjectPrototypeIsPrototypeOf`

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#13255]
The former can be tricked using `Symbol.hasInstance` while the latter can not.

**Comment by petamoriken** [comment]
related: https://github.com/denoland/deno_lint/issues/986

**Comment by imskr** [comment]
Can I work on this @lucacasonato ?

**Comment by lucacasonato** [comment]
@imskr Sure!
