### ISSUE TITLE
Firebase example not working

### ISSUE THREAD

**Issue by bicarlsen** [denoland/deno#13277]
I am attempting to get Firebase, specifically Firestore, working with Deno but am running into issues. I've raised this as a [question on StackOverflow](https://stackoverflow.com/questions/70564143/using-firsebase-firestore-with-deno).

These issues seem to be with the compatiblity between the `firebase` module and Deno, as the error even occurs in the [Deno Firebase tutorial](https://deno.com/deploy/docs/tutorial-firebase), and if running the [source code](https://deno.com/examples/firebase.js) directly with `deno run --allow-net https://deno.com/examples/firebase.js`.

**Comment by jsejcksn** [comment]
Looks like this is a potential duplicate of https://github.com/denoland/deploy_feedback/issues/131

**Comment by bicarlsen** [comment]
> Looks like this is a potential duplicate of [denoland/deploy_feedback#131](https://github.com/denoland/deploy_feedback/issues/131)

Ah, you're correct, I missed that one. I close this one, and leave the other as the main thread.
