### ISSUE TITLE
`deno test --watch` should have a CLI flag for clearing the terminal when testing is restarted

### ISSUE THREAD

**Issue by frou** [denoland/deno#13278]
At the moment, if you have a tall terminal window, you can still be peripherally "seeing red" even when your test is passing, because old failures are still visible higher up.

I'm proposing adding a new flag, e.g. `--clear`, making it so that `deno test --watch --clear` will clear the terminal right before the:

>Watcher: File change detected! Restarting!

...message is printed.

There's precedent for providing this feature. I've enjoyed it in a bunch of testing commands over the years (and can try to remember which ones if you want!)

**Comment by lucacasonato** [comment]
`deno test --watch` already clears the screen since Deno version 1.17.0. See #12613

**Comment by frou** [comment]
Oops. Sorry about that. I'm still on 1.16 evidently!
