### ISSUE TITLE
cli: when fetching code, use a better accept header

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#13287]
Currently when the CLI attempts to fetch a module it sends an `Accept` header of `*/*`, which isn't actually very accurate, or makes content negotiation for a server very difficult.

The following would be better:

```
Accept: application/javascript, application/typescript, text/javascript, text/typescript, text/jsx, text/tsx, application/json;q=0.9, text/plain;q=0.8, application/octet-stream;q=0.8
```

This roughly follows how we handle it in `MediaType` as well as indicates that we don't just accept anything.  This would allow servers to better negotiate the content being sent to a client.  If we are concerned that the lack of "accept any" might cause regressions, we could go with this instead:

```
Accept: application/javascript, application/typescript, text/javascript, text/typescript, text/jsx, text/tsx, application/json;q=0.9, text/plain;q=0.8, application/octet-stream;q=0.8, */*;q=0.7
```

Which makes it easier for servers who are trying to negotiate content to provide "code" in preference to something like HTML, but still advertises all content is welcome (though it really isn't).

**Comment by kitsonk** [comment]
eszip !== Deno CLI

This is still unresolved in CLI.

**Comment by lucacasonato** [comment]
We use the same header as browsers now. We're not going to change this.
