### ISSUE TITLE
Deno.serveHttp() & Accept-Encoding: gzip, deflate, br - Feature Request

### ISSUE THREAD

**Issue by webdev3301** [denoland/deno#13304]
Most user agents like FireFox, Chrome, etc. send the header `Accept-Encoding: gzip, deflate, br` and `Deno.serveHttp()` does not support any of these compressions, then `Deno.serveHttp()` is only really able to process `Accept-Encoding: identity` which means "without modification or compression".

Since the new server is based on Hyper, could Hyper's ability to `gzip` be implemented in `Deno.serveHttp()`?

Just one little compression mode would be really nice to have. gzip would be ideal.

**Comment by kitsonk** [comment]
Closed by #13769
