### ISSUE TITLE
'headers' of 'RequestInit' (Argument 2) is not a valid ByteString

### ISSUE THREAD

**Issue by FSou1** [denoland/deno#13316]
If headers contain a non-ascii symbol (e.g. `…`), the error is thrown:

```
error: Uncaught TypeError: Failed to construct 'Request': 'headers' of 'RequestInit' (Argument 2) is not a valid ByteString
  return fetch(URL, { headers, method, body, credentials: 'same-origin' });
         ^
    at makeException (deno:ext/webidl/00_webidl.js:79:12)
    at converters.ByteString (deno:ext/webidl/00_webidl.js:385:13)
    at Array.record<ByteString, ByteString> (deno:ext/webidl/00_webidl.js:815:30)
    at webidl.converters.HeadersInit (deno:ext/fetch/20_headers.js:421:65)
    at Array.RequestInit (deno:ext/webidl/00_webidl.js:711:34)
    at new Request (deno:ext/fetch/23_request.js:225:46)
    at deno:ext/fetch/26_fetch.js:396:29
    at new Promise (<anonymous>)
    at fetch (deno:ext/fetch/26_fetch.js:392:12)
```

I need to use this symbol in a cookie value.

**Comment by crowlKats** [comment]
This behaviour is correct, and same as browsers, as per specification

**Comment by FSou1** [comment]
I see.

Node.js also throws the error: `TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Cookie"]`.

I'm wondering what to do in this case. Is it a web server problem that issues cookies with invalid values or the value should be encoded somehow?

**Comment by andreubotella** [comment]
To clarify: headers have traditionally been encoded in Latin-1, not ASCII, and both Deno and browsers support Latin-1 characters in headers, both for sending and receiving. Headers are byte sequences on the wire, and Latin-1 is a common enough assumption by HTTP clients that if you were to use a different encoding, the server will likely misunderstand it. There exists a protocol to encode arbitrary Unicode values in headers ([RFC2047](https://datatracker.ietf.org/doc/html/rfc2047)), but I don't think many servers support it, and so neither do Deno or browsers.

**Comment by FSou1** [comment]
If it's not the issue, shall I close it then?
