### ISSUE TITLE
Deno panic on multiple default export

### ISSUE THREAD

**Issue by naolarega** [denoland/deno#13318]
When i try to bundle a module which imports a module with two default exports this happens. i have included the stack backtrace as instructed.

Platform: windows x86_64
Version: 1.17.1
Args: ["deno", "bundle", "CallChain.mjs"]

thread 'main' panicked at 'internal error: entered unreachable code: Multiple identifiers equivalent up to span hygiene found: default#9
First = Helper#8
Second = SecondHelper#8', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\swc_bundler-0.89.0\src\inline.rs:50:13
stack backtrace:
   0:     0x7ff68f5b9864 - <unknown>
   1:     0x7ff68ed30c5a - <unknown>
   2:     0x7ff68f5b7828 - <unknown>
   3:     0x7ff68f5b8912 - <unknown>
   4:     0x7ff68f5b7e20 - <unknown>
   5:     0x7ff68ece0d7a - <unknown>
   6:     0x7ff68f5b7657 - <unknown>
   7:     0x7ff68f5bfd65 - <unknown>
   8:     0x7ff68f5bfcd9 - <unknown>
   9:     0x7ff68f5bfc94 - <unknown>
  10:     0x7ff6906b0a70 - CrashForExceptionInNonABICompliantCodeRange
  11:     0x7ff68f5de73f - <unknown>
  12:     0x7ff68f5deb35 - <unknown>
  13:     0x7ff68e95a714 - <unknown>
  14:     0x7ff68e92d8bf - <unknown>
  15:     0x7ff68e921d1e - <unknown>
  16:     0x7ff68e91f3d5 - <unknown>
  17:     0x7ff68ecc560e - <unknown>
  18:     0x7ff68ecca787 - <unknown>
  19:     0x7ff68ecc7930 - <unknown>
  20:     0x7ff68e8b6ab2 - <unknown>
  21:     0x7ff68e8a11ef - <unknown>
  22:     0x7ff68e89b49c - <unknown>
  23:     0x7ff68e89b542 - <unknown>
  24:     0x7ff690666b2c - CrashForExceptionInNonABICompliantCodeRange
  25:     0x7ffb82487034 - BaseThreadInitThunk
  26:     0x7ffb832c2651 - RtlUserThreadStart

**Comment by bartlomieju** [comment]
Reported in https://github.com/swc-project/swc/issues/3221

**Comment by GJZwiers** [comment]
Looks like the upstream issue has been fixed, maybe this issue is also resolved now?
