### ISSUE TITLE
cli: console clearing when watching should be an option

### ISSUE THREAD

**Issue by zifeo** [denoland/deno#13315]
https://github.com/denoland/deno/pull/12613 introduced a neat console clear on reload. However this behaviour may be undesirable on multi environments where files are linked (dylib) and watch/reload chained.

Workaround:
```
deno ... 2>&1 | grep -v '\\x1B\[1;1H'
```

**Comment by bartlomieju** [comment]
@zifeo Can you explain what this bit means? Are you compiling Deno yourself?

> However this behaviour may be undesirable on multi environments where files are linked (dylib) and watch/reload chained.

**Comment by zifeo** [comment]
@bartlomieju 

1. Process A : watch for changes in folder `./native` and generates `./generated/rpc.ts`
2. Process B : `deno run --watch=./generated/rpc.ts src/main.ts`

Any log (& error) generated by A will be instantly cleared by process B when run on the same terminal.

**Comment by bartlomieju** [comment]
I guess we should add `--no-clear-screen` flag to all commands that have `--watch` flag available.

**Comment by erfanium** [comment]
@bartlomieju 
maybe `--watch="no-clear-screen"` is a better design. because `--no-clear-screen` flag is not usable by it's own.

**Comment by lucacasonato** [comment]
--watch already takes a string argument (additional directories and files to watch)

**Comment by gliheng** [comment]
I found clear screen can be stopped just by redirect stderr to a file by appending `2>err` to your command.
