### ISSUE TITLE
Test coverage report incorrectly shows error thrown as not covered

### ISSUE THREAD

**Issue by KyleJune** [denoland/deno#13323]
This is with Deno v1.17.2. I tried making a minimal reproduction path but it appears the issue doesn't always occur for thrown errors. Another error thrown in the function shows as having test coverage. The basic_auth.ts file and test coverage is pretty short.

If you look at codecov, it shows the last error thrown as not having coverage.

https://app.codecov.io/gh/udibo/oauth2_server/blob/8936c233e532e143be79198b0359e0af8beafa4d/basic_auth.ts

Here is the test coverage for that line, it makes assertions about the error thrown and the test case passed.

https://github.com/udibo/oauth2_server/blob/0.11.1/basic_auth_test.ts#L57

Not really an urgent issue at all, just reporting it in case it helps with the project of making test coverage reports more accurate.

**Comment by bartlomieju** [comment]
Most likely related to #10944, I will check once https://github.com/denoland/deno/pull/13334 lands
