### ISSUE TITLE
`deno coverage` errors with type error if the source code uses custom "lib" configuration

### ISSUE THREAD

**Issue by kt3k** [denoland/deno#13326]
My library uses [custom lib config](https://github.com/capsidjs/capsid/blob/main/deno.json) (because it's a frontend library and needs `dom` types), and it can pass the tests and can generate the coverage data using this config. However when I run `deno coverage` it errors with type error at DOM types and I don't find a way to pass config file to `deno coverage` sub command. So I can't create coverage report for this library..

**Comment by bartlomieju** [comment]
@kt3k please check if https://github.com/denoland/deno/pull/13324 helps

**Comment by kt3k** [comment]
It seems #13324 fixes this issue. What a timely fix!
