### ISSUE TITLE
improve(ext/ffi) - allow alias for symbol renames to solve Windows DLL import issues.

### ISSUE THREAD

**Issue by SeanWykes** [denoland/deno#13327]
A number of Microsoft windows DLL's contain two entry points for effectively the same function, with "A" and "W" prefixes to indicate normal (ANSI) or wide strings, for example: [`winscard.h`](https://docs.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardconnecta)

The windows import headers `.h` automatically select between the two variants. 

Problem: linux/os-x versions of this library do not have these suffixes, thus making the `symbols` hash of `Deno.dlopen` somewhat complicated.

Solution: Add an `alias?: string` to `ForeignFunction`, which if set would indicate the symbol name to be imported from the library. This might also help in other cases, such as imported C++ dlls where the symbol names have been munged by the compiler.

**Comment by DjDeveloperr** [comment]
#13090 implements this (with the only difference being new property is `name` instead of `alias`)

**Comment by SeanWykes** [comment]
> #13090 implements this (with the only difference being new property is `name` instead of `alias`)

Ops. Sorry. Did an issue search beforehand but didn't catch it. Thanks!
