### ISSUE TITLE
Support calling Function Pointers in FFI

### ISSUE THREAD

**Issue by DjDeveloperr** [denoland/deno#13336]
### Why

Some native libraries return function pointers to expose further API. Such as GLFW exposes a `glfwGetProcAddress` function which is used to get pointer to the OpenGL API function. I'm currently using a helper library written in C to call function pointers in [my project that uses GLFW](https://github.com/DjDeveloperr/deno_gl). I'm sure there are much more use-cases than just this, like calling temporary callbacks returned from native land.

### Suggestion

Introduce a new API to wrap a function pointer + a function definition into a JS function, such as:

```ts
// on `DynamicLibrary`
fnptr<Fn extends Deno.ForeignFunction>(ptr: Deno.UnsafePointer, def: Fn): StaticForeignFunction<Fn>;
```

(I'm not sure about name of the method)

which can be used something like this:

```ts
const fn = lib.fnptr(ptr, {
  parameters: [...],
  result: "...",
});

fn(...);
```

**Comment by bartlomieju** [comment]
Sounds good, PR are welcome!

Maybe model it after `Deno.UnsafePointer` API? Eg. `new Deno.UnsafeFnPointer(ptr, { ... })
