### ISSUE TITLE
Provide a way to limit imports to certain domains/directories 

### ISSUE THREAD

**Issue by jahtalab** [denoland/deno#13330]
It would be useful to have a permission option to limit the imports to a certain domain or directory.

**Comment by kitsonk** [comment]
What is the use case, what would be an example of something this would fix/improve?

**Comment by bartlomieju** [comment]
Seems related to #8266

**Comment by kitsonk** [comment]
Actually, feels like a duplicate.  @jahtalab I would suggest you add feedback there around what you had in mind.

Duplicate of #8266
