### ISSUE TITLE
`atob` throws incorrect error when no argument is passed.

### ISSUE THREAD

**Issue by benjamingr** [denoland/deno#13343]
Deno throws a `DOMException` when `atob()` is run (no argument) but it should throw a `TypeError` like webidl says. The DOMException is from trying to convert it to a string.

Deno's current behavior is the same as `atob(undefined)`.

A fix should be pretty simple.

Saw this here https://github.com/nodejs/node/issues/41450 and namely https://github.com/nodejs/node/issues/41450#issuecomment-1008447483

**Comment by lucacasonato** [comment]
@DerekNonGeneric already reported it to me directly. Fix in https://github.com/denoland/deno/pull/13341 :-)

**Comment by benjamingr** [comment]
Ah cool, closing this one then :)
