### ISSUE TITLE
Unable to running Deno v1.17.3 on Windows 10

### ISSUE THREAD

**Issue by Bzvwf16WSDKoSZd8** [denoland/deno#13361]
Version:
Windows 10 Home edition 21H2 19044.1466
Windows Feature Experience Pack 120.2212.3920.0

Deno zip:
deno-x86_64-pc-windows-msvc.zip

Displaying error dialog with the following error code when I trying to execute Deno v1.17.3
0xc0000022

Folder "%USERPROFILE%\AppData\Local\deno" is removed before I running Deno v1.17.3, but the problem is still existing.

"Deno v1.17.2 is OK!"

**Comment by lucacasonato** [comment]
@piscisaureus or @dsherret Do you have any ideas of what the problem could be?

**Comment by jeremythille** [comment]
I just updated Deno from 1.17 to 1.17.3 in Windows 10 and I have no compatibility problem at all. Running `deno` outputs `Deno 1.17.3`

**Comment by Bzvwf16WSDKoSZd8** [comment]
> I just updated Deno from 1.17 to 1.17.3 in Windows 10 and I have no compatibility problem at all. Running `deno` outputs `Deno 1.17.3`

Deno v1.17.2 is OK (The all previous version was perfectly fine).
Just Deno 1.17.3 had this problem for me.

**Comment by dsherret** [comment]
Works for me on Windows 10 Pro.

@Bzvwf16WSDKoSZd8 maybe try checking the "Security" tab of Deno v1.17.2 vs v1.17.3 on your system. Are they the same?

If that's not the case, maybe try restarting your computer and reinstalling deno.

**Comment by Bzvwf16WSDKoSZd8** [comment]
> Works for me on Windows 10 Pro.
> 
> @Bzvwf16WSDKoSZd8 maybe try checking the "Security" tab of Deno v1.17.2 vs v1.17.3 on your system (under right click + properties). Are they the same?
> 
> If that's not the case, maybe try restarting your computer and reinstalling deno.

I found the problem from my Windows Terminal.
