### ISSUE TITLE
Some (but not all) files fail to be served after page refresh

### ISSUE THREAD

**Issue by jeremythille** [denoland/deno#13362]
Deno v1.17.3 (same problem with v1.17.0 before)
Windows 10 Version 10.0.19043 Build 19043

I'm encountering a very strange issue.
When I load my front-end app (static HTML and JS files) for the first time, it works perfectly, the files are served, and the app displays immediately in the browser.

If I reload the page, the same files get requested to the Deno server (index.html, Javascript files) but some of them, always the same ones, remain pending. It's always `polyfill.js` and `main.js`. The application remains loading.....

......but not forever. After 17 minutes (I made the test earlier today), the two JS files get unstuck, served, and the app gets displayed in the browser.

![2022-01-13_114338](https://user-images.githubusercontent.com/3706912/149338099-392b380d-9a7a-49c0-94d4-ab6652133580.png)

I believe it has to do with the file size, because the two that always get stuck are also the two heaviest of the lot.

I have made a repository with the minimal code (2 TS files + some static front-end files to be served) to reproduce the issue : https://github.com/jeremythille/deno_serving_issue

I have also made a 5 minute screen recording to demonstrate the issue on my machine: https://drive.google.com/file/d/1KXzT7sE9ah9A_1YVxWFkblqEWAO5Jk_p/view?usp=sharing

Below is the code from index.ts (it's in the repo):

```
import { router } from "./router.ts"

const port = 8090;

const server: Deno.Listener = await Deno.listen({ port });
console.log(`Deno server listening on http://localhost:${port}/`);

for await (const conn: Deno.Conn of server) {
  const httpConn = Deno.serveHttp(conn);
  for await (const { request:req, respondWith:res } of httpConn) {
    const response: Promise<Response> = router(req);
    res(response); // The only place where we respond to the browser
  }
}
```

This is just standard (async iterator), minimal code I've found in the Deno documentation. It works, but only once, not on page reload.

And I'm reading the files with this line :

`const file = await Deno.readFile(distDir + "/" + fileName);`

Not sure if I'm doing something wrong, or if it is a bug...?

**Comment by lucacasonato** [comment]
Yes, you are doing something wrong. By putting an `await` inside the outer for await loop, only one connection can be handled at once.

You should use `std/http`:
- https://deno.land/manual@v1.17.3/runtime/http_server_apis
- https://examples.deno.land/http-server

Where did you find this example in the documentation?

**Comment by jeremythille** [comment]
Oooooh my mistake then. I read [the documentation](https://deno.land/manual@v1.17.3/runtime/http_server_apis_low_level#serving-http) again, and the inner `await` should be enclosed inside an anonymous function :

```
for await (const conn of server) {
  (async () => {
    const httpConn = Deno.serveHttp(conn);
    for await (const requestEvent of httpConn) {
      // ... handle requestEvent ...
    }
  })();
}
```

Thank you very much, my bad. It works perfectly, now. I am an early Node.js adopter, and now I'm trying to think "in Deno".

However, why is it working the first time, and also for half the files the second time? It doesn't really make much sense, does it?

I'll be closing/deleting the issue soon.

**Comment by lucacasonato** [comment]
> However, why is it working the first time, and also for half the files the second time? It doesn't really make much sense, does it?

The additional requests were likely made on a second or third connection which was just hanging there because of the await. At some point the browser closed the first connection, which let the server handle the second connection.

**Comment by lucacasonato** [comment]
Also, you really don't want to be using the low level APIs. They are [not faster than using std/http](https://deno.land/benchmarks#http-server-throughput), but are a lot easier to use wrong. std/http handles all kinds of edge cases for you, while the low level API does not.

There is pretty much no reason to use the low level API.

**Comment by jeremythille** [comment]
Hmmm, I get it. Making progress in learning Deno. Thanks again!

**Comment by nhrones** [comment]
@lucacasonato The WebSocket example in 3.5 has a confusing unused `const upgrade`
```js
function handler(req: Request): Response {
  const upgrade = req.headers.get("upgrade") || "";
  let socket, response;
  try {
    res = Deno.upgradeWebSocket(req);
    socket = res.socket;
    response = res.response;
  } catch {
    return new Response("request isn't trying to upgrade to websocket.");
  }
  socket.onopen = () => console.log("socket opened");
  socket.onmessage = (e) => {
    console.log("socket message:", e.data);
    socket.send(new Date().toString());
  };
  socket.onerror = (e) => console.log("socket errored:", e.message);
  socket.onclose = () => console.log("socket closed");
  return response;
}
```
