### ISSUE TITLE
`cancel_try_future` cancels a network I/O future right after polling it vs cancels a spawned task before it actually runs.

### ISSUE THREAD

**Issue by 06kellyjac** [denoland/deno#13378]
https://github.com/denoland/deno/blob/main/core/async_cancel.rs#L649-L677

Shouldn't it cancel a network I/O future *before* polling it like it cancels the task before it runs?

If the test is ran in a hermetic environment it fails with `NetworkUnreachable` I'm guessing since it can't get the initial polling done?

```
---- async_cancel::tests::cancel_try_future stdout ----
thread 'async_cancel::tests::cancel_try_future' panicked at 'assertion failed: `(left == right)`
  left: `NetworkUnreachable`,
 right: `Interrupted`', core/async_cancel.rs:674:7
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    async_cancel::tests::cancel_try_future
```

If it must be canceled after the polling then can the test be modified to use loopback or a temporarily hosted service?

**Comment by piscisaureus** [comment]
> Shouldn't it cancel a network I/O future _before_ polling it like it cancels the task before it runs?

That would defeat the purpose of the test.

> If it must be canceled after the polling then can the test be modified to use loopback or a temporarily hosted service?

It is possible, feel free to submit a PR.
