### ISSUE TITLE
Error : while installing deno

### ISSUE THREAD

**Issue by devaaquib** [denoland/deno#13380]
hii, i was trying to install this but i faced error, i tried but i can't get of it. can you please help so i can install it and use it.

code i ran:

```curl -fsSL https://deno.land/install.sh | sh```

Error it give:
```
########################################################################100.0%-
######################################################################## 100.0% 
Warning: Failed to create the file /home/aaquib/.deno/bin/deno.zip: Permission 
Warning: denied                                                                                           0.0%
curl: (23) Failure writing output to destination

```

please solve this as soon as possible.

**Comment by kitsonk** [comment]
It appears the user you are using to install with does not have write permision to `/home/aaquib/.deno/bin/`.  This is not an issue with Deno.

**Comment by Bzvwf16WSDKoSZd8** [comment]
> It appears the user you are using to install with does not have write permision to `/home/aaquib/.deno/bin/`. This is not an issue with Deno.

Is it possible to add chmod comand to install.sh?

**Comment by kitsonk** [comment]
No. Magically changing local file permissions is not something a script should do. The install script works in the bulk of environments, noted by this being the first report of an issue in several years the script has existed.

**Comment by Bzvwf16WSDKoSZd8** [comment]
@aaquibdev You may try to check the permission setting of "curl" and "unzip" on your system. "install.sh" using those to write the downloaded file and unziped file to disk.

**Comment by Jamesernator** [comment]
I'm having a pretty similar issue, using the install script under termux I get:

```js
mkdir: cannot create directory ‘/home’: Read-only file system
```

In my case however this could be fixed on deno's end by respecting the `$HOME` env variable rather than relying on `/home/$username` being available.

And certainty in quite a few university systems I've seen users homedirs are often set to things like `/home/students/$id` or even more exotic ones.

**Comment by Jamesernator** [comment]
> In my case however this could be fixed on deno's end by respecting the $HOME env variable rather than relying on /home/$username being available.

Actually it looks like this is already the case, it looks like Termux does something weird when piping.

**Comment by Jamesernator** [comment]
> Actually it looks like this is already the case, it looks like Termux does something weird with env variables when piping.

Double nevermind, I had `export DENO_INSTALL` lines committed into my `.zshrc`.

**Comment by kitsonk** [comment]
There appears to be nothing actionable here, all local environment issues or no meaningful response.

**Comment by hristian-carabulea** [comment]
I never had problems installing anything else BUT Deno. It cannot be only an error with my user settings. Even if I run with sudo I get the same error. 

Warning: Failed to open the file /home/hristian/.deno/bin/deno.zip: Permission 

Warning: denied

                                                                           0.0%curl: (23) Failure writing output to destination
Can you offer any solutions, please?

**Comment by hristian-carabulea** [comment]
Feedback on my previous post. A alternative solution: 
1. On Ubuntu 22.04 I used the command: sudo snap install deno
2. deno --version
deno 1.27.2 (release, x86_64-unknown-linux-gnu)
v8 10.8.168.4
typescript 4.8.3

**Comment by laem** [comment]
For what it's worth, I got this exception because I copied my .bashrc file from one computer to another, so this line of the bashrc confused the deno installer. 


```
export DENO_INSTALL="/home/OLDHOME/.deno"
```

**Comment by pawel-rh** [comment]
One scenario this error pops up is when having _curl_ installed using _snap_. It doesn't go well with Deno wanting its zip file written to a hidden `.deno` directory.
I chose what most seem to choose: `sudo snap remove curl; sudo apt install curl`

**Comment by theregular** [comment]
> One scenario this error pops up is when having _curl_ installed using _snap_. It doesn't go well with Deno wanting its zip file written to a hidden `.deno` directory. I chose what most seem to choose: `sudo snap remove curl; sudo apt install curl`

This was the issue. I had installed curl with snap and for some reason deno couldn't install correctly. When I reinstalled curl with  apt, deno installed perfectly fine
