### ISSUE TITLE
SIGSEGV when running multiple `MainWorker`s in a single thread

### ISSUE THREAD

**Issue by andreubotella** [denoland/deno#13384]
I was trying to reproduce a case of async APIs hanging when an embedder run multiple `JsRuntime`s in a single thread, and I found that I got a segmentation fault, even though the embedding code had no `unsafe`. This doesn't happen every time, but on my machine it happens most times (whether using the `tla` feature or not), although I haven't been able to reproduce it when running under valgrind.

I tested this with both `rustc 1.60.0-nightly (22e491ac7 2022-01-13)` and `rustc 1.58.0 (02072b482 2022-01-11)` (stable), both on `x86_64-unknown-linux-gnu`.

https://github.com/andreubotella/deno-multiple-isolates-per-thread

**Comment by andreubotella** [comment]
cc @piscisaureus

**Comment by piscisaureus** [comment]
I suspect the culprit is https://github.com/denoland/rusty_v8/commit/83052c45351768c2e8923d1bf557728e03fecbf.

**Comment by andreubotella** [comment]
I'm trying to reproduce this now, and I can't, even with the same dependency versions. I'm not sure if it's due to a change in the Rust version I'm using, or some update in my system, but I'll close this for now.
