### ISSUE TITLE
URLPattern panic

### ISSUE THREAD

**Issue by AaronO** [denoland/deno#13394]
## Minimal reproduction

```js
new URLPattern({ pathname: '/:a.' })
```

## Expected behaviour

Running the reproduction case in Chrome yields:
```js
URLPattern {
  hash: "*"
  hostname: "*"
  password: "*"
  pathname: "/:a."
  port: "*"
  protocol: "*"
  search: "*"
  username: "*"
}
```

## Cause

This happens because of an `.unwrap()` in our `rust-urlpattern` crate: https://github.com/denoland/rust-urlpattern/blob/fdb0bbb45613b346cb1bfef57c16fc8af97fa1ff/src/component.rs#L195

**Comment by AaronO** [comment]
Possibly an issue in the spec: https://github.com/WICG/urlpattern/issues/156

**Comment by AaronO** [comment]
Quickfixed by https://github.com/denoland/rust-urlpattern/pull/26, available in https://crates.io/crates/urlpattern/0.1.4

**Comment by bartlomieju** [comment]
We are using `urlpattern` @ 0.1.5 so this issue can be now closed.
