### ISSUE TITLE
Raise a error when run `deno run https://deno.land/std/http/file_server.ts`  on deno 1.17.3

### ISSUE THREAD

**Issue by zuisong** [denoland/deno#13405]
Raise a error when i run `deno run --allow-read --allow-net https://deno.land/std/http/file_server.ts -p 8080`

```
$ deno --version 
deno 1.17.3 (release, aarch64-apple-darwin)
v8 9.7.106.15
typescript 4.5.2

$ deno run --allow-read --allow-net https://deno.land/std/http/file_server.ts -p 8080
Check https://deno.land/std/http/file_server.ts
error: TS2339 [ERROR]: Property 'getIterator' does not exist on type 'ReadableStream<R>'.
  return res.readable.getIterator();
                      ~~~~~~~~~~~
    at https://deno.land/std@0.80.0/async/pool.ts:45:23
```

https://deno.land/manual@v1.17.3/tools/compiler#compiling-executables

**Comment by hayd** [comment]
```
https://deno.land/std@0.80.0/async/pool.ts:45:23
```
is a relatively old version of std, latest is 0.121.0, so it looks like this has been cached locally.

Try with --reload ?

```
$ deno run --reload --allow-read --allow-net https://deno.land/std/http/file_server.ts -p 8080
```

Since std is still <1.0 this type of error is somewhat expected.

**Comment by zuisong** [comment]
> ```
> https://deno.land/std@0.80.0/async/pool.ts:45:23
> ```
> 
> is a relatively old version of std, latest is 0.121.0, so it looks like this has been cached locally.
> 
> Try with --reload ?
> 
> ```
> $ deno run --reload --allow-read --allow-net https://deno.land/std/http/file_server.ts -p 8080
> ```
> 
> Since std is still <1.0 this type of error is somewhat expected.

thanks, It's work fine now
