### ISSUE TITLE
Deno.isatty throws Busy error intermittently 

### ISSUE THREAD

**Issue by myobie** [denoland/deno#13409]
Using this example:

```ts
const isTTY = Deno.isatty(Deno.stderr.rid)
```

I see intermittent throws from the `Deno.isatty` function. While I am sure it's possible that `stderr` is busy, I don't see a way to use `isatty` with `rid`s that won't sometimes throw if they happen to busy at the time.

<img width="1001" alt="isatty error" src="https://user-images.githubusercontent.com/179/149927944-b9fd8566-cca6-4236-a24d-b8cb7200658c.png">

If there is a way to handle this case in my code, then I apologize and this can be closed.

**Comment by bartlomieju** [comment]
Somewhat related to https://github.com/denoland/deno/issues/12995

CC @piscisaureus

**Comment by myobie** [comment]
I'm seeing this error still with v1.24.3. Any idea why checking for TTY would would ever do this?
