### ISSUE TITLE
Explore using Azure Pipelines for CI

### ISSUE THREAD

**Issue by ry** [denoland/deno#1340]
https://azure.microsoft.com/en-us/blog/announcing-azure-pipelines-with-unlimited-ci-cd-minutes-for-open-source/

They provide 10 parallel builds for open source and support Win/Linux/Mac. It might be a real improvement for us and allow us to move away from maintaining both AppVeyor and Travis builds.

**Comment by btholt** [comment]
Hey @ry, just saw this issue. If you need help with anything, let me know.
