### ISSUE TITLE
Fail to upgrade to 1.17.3

### ISSUE THREAD

**Issue by albertosantini** [denoland/deno#13412]
On Windows 11 (but it also failed on Windows 10) from 1.17.2:

```
$ deno upgrade
Looking up latest version
Found latest version 1.17.3
Checking https://github.com/denoland/deno/releases/download/v1.17.3/deno-x86_64-pc-windows-msvc.zip
24.4 MiB / 24.4 MiB (100.0%)
Deno is upgrading to version 1.17.3

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: windows x86_64
Version: 1.17.2
Args: ["C:\\woot\\usr\\bin\\deno.exe", "upgrade"]

thread 'main' panicked at 'assertion failed: output.status.success()', cli\tools\upgrade.rs:306:3
stack backtrace:
   0:     0x7ff7bd5ee704 - <unknown>
   1:     0x7ff7bcd645fa - <unknown>
   2:     0x7ff7bd5ec6c8 - <unknown>
   3:     0x7ff7bd5ed7b2 - <unknown>
   4:     0x7ff7bd5eccc0 - <unknown>
   5:     0x7ff7bcd14c83 - <unknown>
   6:     0x7ff7bd5ec4f7 - <unknown>
   7:     0x7ff7bd5f4be3 - <unknown>
   8:     0x7ff7bd5f4b79 - <unknown>
   9:     0x7ff7bd5f4b34 - <unknown>
  10:     0x7ff7be6ef520 - CrashForExceptionInNonABICompliantCodeRange
  11:     0x7ff7be6ef67c - CrashForExceptionInNonABICompliantCodeRange
  12:     0x7ff7bc91e5b5 - <unknown>
  13:     0x7ff7bc91aa27 - <unknown>
  14:     0x7ff7bc905da2 - <unknown>
  15:     0x7ff7bc8f10bf - <unknown>
  16:     0x7ff7bc8eb391 - <unknown>
  17:     0x7ff7bc8eb437 - <unknown>
  18:     0x7ff7be6a8dcc - CrashForExceptionInNonABICompliantCodeRange
  19:     0x7ffdd4cf54e0 - BaseThreadInitThunk
  20:     0x7ffdd5d6485b - RtlUserThreadStart
```

Copy the binary from `Releases` (Assets - artifact `deno-x86_64-pc-windows-msvc.zip`):
```
deno --version
C:/woot/usr/bin/deno.exe: error while loading shared libraries: api-ms-win-crt-multibyte-l1-1-0.dll: cannot open shared object file: No such file or directory
```

I didn't change any runtime lib installed:

<img width="677" alt="image" src="https://user-images.githubusercontent.com/328179/150012478-24fcc93f-5131-4d4b-83fd-de37d49381fb.png">

Any hint?

**Comment by dsherret** [comment]
Hmmm... maybe try getting the latest C++ redistributable? https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

**Comment by piscisaureus** [comment]
We did not land any changes between 1.17.2 and 1.17.3 that could have changed library dependencies.

However I did notice that the Github Actions windows-2019 image was updated between those releases (20211219 -> 20220110). This update included a Visual Studio upgrade which I suspect changed the vcruntime version that Deno links with.

* Deno v1.17.2: Visual Studio Enterprise 2017 version build 15.9.28307.1745 (released 2021-11-09)
* Deno v1.17.3: Visual Studio Enterprise 2017 version build 15.9.28307.1759 (released 2021-12-14)

As you can see the Visual Studio version was just a month old when 1.17.3 was released.
I would suggest you try to run windows update and see if that fixes the issue.

**Comment by albertosantini** [comment]
Resolved, installing the latest C++ redistributable as suggested.

<img width="702" alt="image" src="https://user-images.githubusercontent.com/328179/150097081-9422f684-c82a-4852-be27-606ebfd74223.png">

Windows update didn't resolve the issue and Windows 11 was installed (upgrade from Windows 10) a few days ago.

Thanks for the support.
