### ISSUE TITLE
lsp: does not use $DENO_CERT when fetching registry configurations

### ISSUE THREAD

**Issue by tdillon** [denoland/deno#13437]
**Describe the bug**

When opening VS Code to a Deno project, this extension errors when attempting to request an external URL.  I am behind a corporate proxy with a self signed cert.

**To Reproduce**

1. Have a self signed cert in your certificate chain.
2. Open a Deno project.
3. Error occurs.

**Expected behavior**

When VS Code opens, I do not expect to see this error.  Instead, I would expect this extension to use the $DENO_CERT environment variable to access any external resources.

Here is a curl example that shows the same behavior.

```shell
$ curl https://x.nest.land/.well-known/deno-import-intellisense.json
curl: (60) SSL certificate problem: self signed certificate in certificate chain
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

Here is a curl example where $DENO_CERT is used and the request is successful.

```shell
$ curl --cacert $DENO_CERT https://x.nest.land/.well-known/deno-import-intellisense.json
Moved Permanently. Redirecting to https://intellisense.nest.land/deno-import-intellisense.json
```

**Screenshots**
![vscode-deno-error](https://user-images.githubusercontent.com/12434812/150331382-02414b64-0612-4ed4-9b03-b121e40675f6.png)

**Versions**

- vscode: 1.63.2
- deno: 1.17.3
- extension: 3.10.1

**Comment by kitsonk** [comment]
In 1.18.0 this is going to change a little bit, to where you won't get a client error message when this occurs.  The error would only get logged to debug output.  But we do need to respect the `$DENO_CERT` like when fetching module contents.

**Comment by lucacasonato** [comment]
To fix this we need to pass the `root_cert_store` from `ProcState` into the `FileFetcher` created in `ModuleRegistry`. I don't know what the easiest way to get at the proc state from the LSP internals though, so I'll leave the actual fixing to you @kitsonk.

**Comment by kitsonk** [comment]
I don't think we can easily have proc state, or if we do, it would come with a lot of baggage we don't want or need.  I will take a look and see if we can abstract out the `root_cert_store` creation.  Might need to add some more config options so that we can align to the CLI flags too on the creation of it.
