### ISSUE TITLE
deno compile should use eszip instead of bundling

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#13430]
Once new version of [`eszip`](https://github.com/denoland/eszip) is available we should use it for `deno compile` instead of relying on bundler. 

`eszip` provides a loss-less way to store a whole module graph and doesn't alter source code in any way. Given numerous problems with bundler we experienced over the last year it seems to be desirable to avoid bundling if possible.

**Comment by bartlomieju** [comment]
ESZip v2 has landed, this can now be implemented.

**Comment by williamtetlow** [comment]
@bartlomieju I can pick this up

**Comment by bartlomieju** [comment]
@williamtetlow thanks! Please do, and feel free to ping me if you have any questions.

**Comment by jtoppine** [comment]
Will this mean bundling in general might be dropped from Deno feature set? As bundling is used to... bundle... code for browsers, and some other use cases besides building stuff to be consumed by Deno itself. It would be sad to lose that ability, even in it's current sometimes buggy state.

**Comment by bartlomieju** [comment]
> Will this mean bundling in general might be dropped from Deno feature set? As bundling is used to... bundle... code for browsers, and some other use cases besides building stuff to be consumed by Deno itself. It would be sad to lose that ability, even in it's current sometimes buggy state.

It's being considered, but there is no decision yet. This issue is orthogonal to `deno bundle` itself.

**Comment by littledivy** [comment]
Done in #13563
