### ISSUE TITLE
Generate lock file from import maps

### ISSUE THREAD

**Issue by x80486** [denoland/deno#13446]
I tend to place all dependencies in a file `import-map.json`. This works usually well, until you have to generate the lock file based on your actual project's dependencies. For instance, nothing used in the tests would be included by `deno cache ... --lock-write main.ts`, and there could be other scenarios that I'm not aware of.

I think an alternative solution could be to generate the lock file based on what's in the `import-map.json` and that could be used project wise. Another thing I can think of is that `deno cache`, when used with `--lock-write`, could accept a directory instead, but that would trigger some other number of scenarios and inconsistencies.

**Comment by nayeemrmn** [comment]
> For instance, nothing used in the tests would be included by `deno cache ... --lock-write main.ts`, and there could be other scenarios that I'm not aware of.

> Another thing I can think of is that `deno cache`, when used with `--lock-write`, could accept a directory instead

The intended command for this is `deno test --no-run --import-map import-map.json --lock lock.json --lock-write`.
`deno test --no-run` is like `deno cache <any modules with test coverage>`. Also opened #13457.

**Comment by x80486** [comment]
I didn't know that was possible! 🥳

It's a little bit weird that those two are equivalent, because one is clear (`clean`), while the other one _feels more_ like a command with some side effect. In any case, since that's already in place, this ticket is not relevant anymore.

The only disadvantage/drawback is that to use this, all modules imported locally, e.g.: `import { foo } from "bar.ts";` must use `./bar.ts` instead 😬
