### ISSUE TITLE
P-384 ECDH deriveBits

### ISSUE THREAD

**Issue by littledivy** [denoland/deno#13451]
[Diffie-Hellman function](https://docs.rs/elliptic-curve/0.11.5/src/elliptic_curve/ecdh.rs.html#58-68) requires `p384::NistP384` to implement `ProjectiveArithmetic` trait. Blocked on https://github.com/RustCrypto/elliptic-curves/issues/240

**Comment by littledivy** [comment]
Unblocked. This can be implemented now.

**Comment by birkskyum** [comment]
I know from experience that Diffie-Hellman likely will be needed as well to get auth going
- #23474

**Comment by birkskyum** [comment]
Is this already resolved?

https://github.com/denoland/deno/pull/15138#issue-1299833283

**Comment by iuioiua** [comment]
Completed in #15138.
