### ISSUE TITLE
Seperate docs

### ISSUE THREAD

**Issue by djKooks** [denoland/deno#1345]
Hello. This is just a suggestion...

Docs seems bit long to look on. How about splitting tutorial and change-log?
Or it could be an idea to make github page for project.

If this is already being discussed in other place, please close this one.

Thanks.

**Comment by bartlomieju** [comment]
Docs are now available at https://deno.land/manual.html

CC @ry

**Comment by ry** [comment]
I've split tutorial and change log 
https://deno.land/manual.html
https://github.com/denoland/deno/blob/master/Releases.md
