### ISSUE TITLE
Pointers to pointers

### ISSUE THREAD

**Issue by evan-brass** [denoland/deno#13460]
### Why
I was playing with SQLite and the definition for sqlite3_open looks like this:
```c
SQLITE_API int sqlite3_open(
  const char *filename,   /* Database filename (UTF-8) */
  sqlite3 **ppDb          /* OUT: SQLite db handle */
);
```
ppDb is a pointer to where a pointer will be written.

My first thought was to use BigInt64Array like this but I doubt it would work:
```javascript
const pointer_recv = new BigInt64Array(1);
sqlite3.symbols.sqlite3_open(filename, pointer_recv);
const db_handle = new Deno.UnsafePointer(pointer_recv[0]);
```

### Suggestion
Add a method to UnsafePointer that creates a typedarray of the correct size to fit a pointer.  Add a method to Unsafe Pointer to create from one of these array's and / or add a function to UnsafePointerView to read an UnsafePointer out.
```javascript
const pointer_recv = Deno.UnsafePointer.sized_array(); // Uint8Array or something
sqlite3.symbols.sqlite3_open(filename, pointer_recv);
const db_handle = new Deno.UnsafePointerView(Deno.UnsafePointer.of(pointer_recv)).getUnsafePointer();
// Another possible style:
const db_handle = Deno.UnsafePointer.from_array(pointer_recv);
```

I'm pretty new to Deno so there might already be a way to do this that I haven't seen yet.

**Comment by DjDeveloperr** [comment]
`BigUint64Array` [would work](https://github.com/denodrivers/sqlite3/blob/main/src/ffi.ts#L376)

**Comment by evan-brass** [comment]
Oh, I'll use that then.
Would that work for all architectures?
Lastly, is there a way to provide JS callbacks to C?

**Comment by DjDeveloperr** [comment]
> Would that work for all architectures?

Yes afaik, Deno only supports 64 bit targets right now. And native endianness is handled by Typed Arrays.

> Lastly, is there a way to provide JS callbacks to C?

Not right now, but there's #13162
