### ISSUE TITLE
A way to disable checking for certain files only

### ISSUE THREAD

**Issue by jespertheend** [denoland/deno#13463]
I'd like to enable strict typing for js files, since all files in my project are written in js. But this causes strict typing to get enabled for all other files as well, including imported libraries. For example:

```js
import { createHash } from "https://deno.land/std@0.118.0/hash/mod.ts";

const hash = createHash("md5");
hash.update("test");
console.log(hash.toString());
```
With the following deno.json:
```json
{
  "compilerOptions": {
    "allowJs": true,
    "checkJs": true,
    "strict": true
  }
}
```
doesn't have any type errors, but `https://deno.land/std@0.118.0/hash/_wasm/wasm.js` does, and so a whole bunch of errors are emitted and the file is not run.

The only solution to this that I'm aware of it to disable allowJs and put `//@ts-check` at the top of the file. But I'd really rather not have to do that for every file across my project, it's prone to errors and just overall pretty tedious.

I realise this is a bit of a weird request, this seems more like a TypeScript issue than a Deno issue. The difference is, if I import a .js library in TypeScript, I can at least fix the issue by adding `@ts-nocheck` to that library. In Deno I don't have any control over the contents of external files.

One [related TypeScript issue](https://github.com/microsoft/TypeScript/issues/40426#issuecomment-901857106) mentions being able to provide a list of paths where all errors are suppressed, so perhaps this is something that should be fixed in TypeScript rather than Deno. But even then it would still have to support suppressing urls somehow.

**Comment by nayeemrmn** [comment]
Since it's precisely uncontrollable remote modules that you want to omit, use `deno run --no-check=remote main.ts`.

**Comment by jespertheend** [comment]
Ah thanks! I wasn't aware of this functionality.
