### ISSUE TITLE
Uncaught `TypeError` in `ext/console`

### ISSUE THREAD

**Issue by KnorpelSenf** [denoland/deno#13469]
## Bug Report

`console.debug` throws an error when it is used by the `debug` package that is skypack'ed from npm.

```
error: Uncaught TypeError: (intermediate value)(intermediate value)(intermediate value) is not iterable
      logFn.apply(self2, args);
            ^
    at cssToAnsi (deno:ext/console/02_console.js:1591:27)
    at inspectArgs (deno:ext/console/02_console.js:1703:32)
    at console.debug (deno:ext/console/02_console.js:1803:9)
    at debug (https://cdn.skypack.dev/-/debug@v4.3.3-0XITH0hRj2rH5NQ5xJ30/dist=es2019,mode=imports/optimized/debug.js:270:13)
    at file:///tmp/test.ts:5:1
```

### Reproduction Steps

Copy the following code to a file.

```ts
import d from "https://cdn.skypack.dev/debug@^4.3.3";
d.useColors = () => !Deno.noColor;
d.enable("demo");
const debug = d("demo");
debug("test");
```

Make sure your deno version is `1.17.2` or higher.

Run the created file with `deno run`. This will lead to the above stack trace.

You can verify that `1.17.1` is able to run the above code correctly. The ouput is:
```
demo test +0ms
```

### Offending Pull Request

The PR #13175 introduces this bug.

**Comment by KnorpelSenf** [comment]
@zachauten could you outline how one would go about fixing this? I assume this is caused because https://github.com/denoland/deno/pull/13175/files#diff-37c40ba2c2cb1bdb8bcc4479c0ef20b88519bf2f49f33f4e0c6db9a6b01c3595R1593 is returning `null`. Can this be fixed by replacing https://github.com/denoland/deno/pull/13175/files#diff-37c40ba2c2cb1bdb8bcc4479c0ef20b88519bf2f49f33f4e0c6db9a6b01c3595R1591-R1594 with
```ts
if (ArrayIsArray(css.color)) {
  const [r, g, b] = css.color
  ansi += `\x1b[38;2;${r};${g};${b}m`;
} else {
  const parsed = parseCssColor(css.color)
  if (parsed !== null) {
    const [r, g, b] = parsed
    ansi += `\x1b[38;2;${r};${g};${b}m`;
  } else {
    ansi += "\x1b[39m";
  }
}
```
?

**Comment by zachauten** [comment]
@KnorpelSenf Yeah, looks like that would be the quickest fix. I can open a PR later, or help review one if you''d rather.

**Comment by KnorpelSenf** [comment]
Please go ahead! I do not have enough disk space to build Deno and run all unit tests, so it's pretty hard to try out my changes :)
