### ISSUE TITLE
Since v1.17.3, statically linking VC runtime is not working on Windows

### ISSUE THREAD

**Issue by noisewin** [denoland/deno#13471]
Hi!

It seems like Deno v1.18.0 and v1.17.3 unintentionally use dynamic linking on Windows 10.
Since v1.17.3, I get `vcruntime140_1.dll was not found` error message box.
(Probably related to #4468, #13412)

The results of using https://github.com/lucasg/Dependencies are as follows:

(deno-v1.17.2) -- no external dependencies
![dep-1 17 2](https://user-images.githubusercontent.com/98225171/150647050-b8fc6685-e351-4661-9495-e2151b22807f.png)

(deno-v1.17.3 and v1.18.0) -- VCRUNTIME140.dll/VCRUNTIME140_1.dll  and external dependencies
![dep-1 18 0](https://user-images.githubusercontent.com/98225171/150647075-b9154ba5-7cab-4ab3-931c-0d78f629f1f4.png)

I would guess the `rustflags = ["-C", "target-feature=+crt-static"]` in `.cargo/config` is ignored or overridden by another config(e.g. [ci env config](https://github.com/denoland/deno/blob/a96b294a8a421570f6b29b5df6fbeaf2d9658047/.github/workflows/ci.yml#L56), etc.).

Thank you for taking the time to look over this issue.
I'm so sorry if I'm wrong!

**Comment by bartlomieju** [comment]
@piscisaureus PTAL

**Comment by dsherret** [comment]
@noisewin see https://github.com/denoland/deno/issues/13412#issuecomment-1015974796

**Comment by piscisaureus** [comment]
> I would guess the `rustflags = ["-C", "target-feature=+crt-static"]` in `.cargo/config` is ignored or overridden by another config(e.g. [ci env config](https://github.com/denoland/deno/blob/a96b294a8a421570f6b29b5df6fbeaf2d9658047/.github/workflows/ci.yml#L56), etc.).

Good find, I think that is the likely cause of this issue (and a better theory than the one I wrote in https://github.com/denoland/deno/issues/13412#issuecomment-1015974796).

I think we should revert #13344.

**Comment by piscisaureus** [comment]
Fixed in https://github.com/denoland/deno/commit/dcf8f144ab0516936bfa4e93357d71f1732d880e.
