### ISSUE TITLE
Support remote configuration files

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#13488]
Especially when using a remote main module, it can be very beneficial to support a remote `--config`/`-c` file, especially when you want a one liner without pre-installing anything locally.

**Comment by hazelnutcloud** [comment]
Stumbled into this problem today. Built a CLI tool that required its config file to work properly because of an NPM dependancy. would be nice to do specify the config file from a remote resource when running the deno install command

**Comment by lino-levan** [comment]
Over at Pyro, I have to use an install script for this (https://github.com/lino-levan/pyro/blob/main/install.ts). This would be nice.

**Comment by cknight** [comment]
I've just run into this problem myself trying to run a remotely hosted Fresh application locally.  As Fresh applications have a `deno.json` file by default that means none of them are runnable locally as a one-liner without cloning the repo or unpicking the `deno.json` file in your application.

**Comment by lucacasonato** [comment]
We are not going to do this in this way - config files are too tied to the file system for this, take for example file ignore configuration.

If someone has alternative ideas for sharing lint / fmt config, let's open a different issue.
