### ISSUE TITLE
Missing JSDoc imports shouldn't be a hard failure

### ISSUE THREAD

**Issue by jiawei397** [denoland/deno#13486]
When I updated deno to v1.18.0, I meet an error.
For example, I cited a third-party package. Here is [a piece of code](https://deno.land/x/kafkasaur@v0.0.7/src/broker/index.ts#L392):
```ts
/**
   * @public
   * @param {object} request
   * @param {string} request.groupId The unique group id
   * @param {import("../protocol/coordinatorTypes").CoordinatorType} request.coordinatorType The type of coordinator to find
   * @returns {Promise}
   */
  async findGroupCoordinator({ groupId, coordinatorType }: 
    {groupId: string, coordinatorType: number}) {
    // TODO: validate groupId, mandatory
    const findCoordinator = this.lookupRequest(
      apiKeys.GroupCoordinator,
      requests.GroupCoordinator
    );
    return await this[PRIVATE.SEND_REQUEST](
      findCoordinator({ groupId, coordinatorType })
    );
  }
```
Then it leads to an error in my code:
```
Download https://deno.land/x/kafkasaur@v0.0.7/types
Download https://deno.land/x/kafkasaur@v0.0.7/src/instrumentation/emitter
Download https://deno.land/x/kafkasaur@v0.0.7/src/protocol/coordinatorTypes
Download https://deno.land/x/kafkasaur@v0.0.7/src/cluster/connectionBuilder
Download https://deno.land/x/kafkasaur@v0.0.7/src/consumer/consumerGroup
Download https://deno.land/x/kafkasaur@v0.0.7/src/network/requestQueue/socketRequest
Download https://deno.land/x/kafkasaur@v0.0.7/src/network/connection
Download https://deno.land/x/kafkasaur@v0.0.7/src/protocol/requests
Download https://deno.land/x/kafkasaur@v0.0.7/src/retry
Download https://deno.land/x/kafkasaur@v0.0.7/src/producer/eosManager
error: Module not found "https://deno.land/x/kafkasaur@v0.0.7/src/protocol/coordinatorTypes".
    at https://deno.land/x/kafkasaur@v0.0.7/src/broker/index.ts:392:22
```

It worked when I use v1.16.2.
It looks more reasonable to have it repaired by the authorities. Thanks.

**Comment by kitsonk** [comment]
The import is invalid based on Deno's module resolution, but I agree it is surprising that this would be a hard failure.  We should either silently fail on these types of imports (which we never analysed in previous version of Deno) or better, print out a warning that they are missing.

That being said, the project is a Deno specific project, with Deno specific imports, written in TypeScript.  The JSDoc block comments with imports is a really bad way to write stuff in a `.ts` file and the package authors should really fix their code to a) not use JSDoc types in TypeScript files and b) amend their import specifiers to be compatible with Deno module resolution, which means they need to include the extensions.

I would open an issue with the package maintainers as well to update their code.

**Comment by jiawei397** [comment]
Thank you for your reply. This comment is really not compliant. It is possible that the project is migrated from JS.
The recent versions of bundle optimization are what I'd like to see. Good job.

**Comment by kitsonk** [comment]
This is now in main.
