### ISSUE TITLE
`deno bundle` emit code with `Uncaught ReferenceError`

### ISSUE THREAD

**Issue by ratson** [denoland/deno#13489]
```sh-session
deno bundle --unstable https://deno.land/std@0.122.0/node/_fs/_fs_chown.ts out.js
deno run out.js
```

Cause error
```
error: Uncaught ReferenceError: Cannot access 'NodeTypeError' before initialization
class ERR_INVALID_ARG_TYPE extends Nod
```

Expect to run without error.

Maybe related to https://github.com/denoland/deno/issues/13170

```sh-session
❯ deno --version
deno 1.18.0 (release, x86_64-apple-darwin)
v8 9.8.177.6
typescript 4.5.2
```

**Comment by bartlomieju** [comment]
This particular error should be fixed by https://github.com/denoland/deno_std/pull/1844

**Comment by ratson** [comment]
I see.

It would be great if such error could detect during bundle time instead of run time.

**Comment by ratson** [comment]
Close as fixed in the latest release of `std`.
