### ISSUE TITLE
proposal: Deno.getUid()

### ISSUE THREAD

**Issue by kt3k** [denoland/deno#13493]
Currently there's no way to get the OS's user id of the process. We should add `Deno.getuid()` (or similar API) to get the user id.

Note: If this API is available we can shim `fs.access` in `std/node` more correctly. ref: https://github.com/denoland/deno_std/blob/cf6b45c1822447e4eb978433454cb500f4c91c35/node/_fs/_fs_access.ts#L24-L26

Note: The above issue of `fs.access` prevents yarn from working with deno compat mode. https://github.com/denoland/deno/issues/13420

**Comment by kt3k** [comment]
There are some candidate API names:

1. `Deno.getuid()`
2. `Deno.getUid()`
3. `Deno.getUserId()`

Which one should we choose?

**Comment by crowlKats** [comment]
Imo 2. would be the best, its easy to read.
1. is confusing to read. its not *that* bad, but i dont see any reason why we should favor this over 2.
3. seems overly long and unnecessary. Also for subprocesses we have `uid` & `gid`, so we should stick with same naming

**Comment by bartlomieju** [comment]
I'm also in favor of 2.

**Comment by kt3k** [comment]
> Also for subprocesses we have uid & gid, so we should stick with same naming

I didn't know we already use `uid` term. Thanks for the input

I'll land with `Deno.getUid` if there's no further input for a while.
