### ISSUE TITLE
Deno bundle leads to "Uncaught ReferenceError"

### ISSUE THREAD

**Issue by irbull** [denoland/deno#13503]
If I try to use `deno bundle` to bundle the following Deno program, and the use `deno run` to execute it, it fails with

```
error: Uncaught ReferenceError: Cannot access 'NodeTypeError' before initialization
class ERR_INVALID_ARG_TYPE extends NodeTypeError {                                   ^
```

Same thing if I try to use `deno compile`. The program works fine with `deno run`.

```
// proxy.ts
import { proxy } from "https://deno.land/x/oak_http_proxy/mod.ts";
import { Application } from "https://deno.land/x/oak/mod.ts";

const app = new Application();

app.use(proxy("http://localhost:8080"));

await app.listen({ port: 3000 });
```

**Comment by irbull** [comment]
I'm not sure if this should be considered a problem with Deno or the oak_http_proxy library.

**Comment by kitsonk** [comment]
What version of Deno are you using? You are also using unversioned dependencies for the other projects, which makes it very hard to reproduce. You should use pinned versions.

Can you provide a full reproduction with pinned versions of the dependencies and the specific version of Deno you are using?

**Comment by irbull** [comment]
Sorry, I unpinned them to see if the latest ones fixed the problem. Here is a version with pinned dependencies:
```
import { proxy } from "https://deno.land/x/oak_http_proxy@2.0.1/mod.ts";
import { Application } from "https://deno.land/x/oak@v10.1.0/mod.ts";

const app = new Application();

app.use(proxy("https://github.com/oakserver/oak"));

await app.listen({ port: 3000 });
```
I'm using 🦖 Deno 1.18.0.

**Comment by irbull** [comment]
And for a set of commands (assuming the example is saved in `main.ts`):
```
deno bundle main.ts main.js
deno run -A main.js
```

**Comment by dsherret** [comment]
Looks like https://github.com/denoland/deno/issues/13489

**Comment by irbull** [comment]
I just tested in Deno 1.18.1. Maybe the MR on #13489 didn't make the point release.

**Comment by kitsonk** [comment]
The change mentioned in #13489 and would be in `std` version 0.123.0.  Until the dependencies are updated, you may need to use an import map to override the other versions.
