### ISSUE TITLE
Property 'getIterator' does not exist on type 'ReadableStream<R>'

### ISSUE THREAD

**Issue by Kayxue** [denoland/deno#13519]
![image](https://user-images.githubusercontent.com/26020165/151540939-954c9cc9-1ba6-46a6-a58b-9c942239b632.png)

**Comment by lucacasonato** [comment]
You are using a very old version of std (current version is 0.123.0). This old version is not compatible with new Deno releases anymore.

**Comment by Kayxue** [comment]
Oh sorry I need to tell creator of the module, not here
