### ISSUE TITLE
[suggestion] - Rework permissions feature

### ISSUE THREAD

**Issue by Olyno** [denoland/deno#13517]
Hi 👋🏻 

I have tried Deno several times, before version 1.0, and with the latest version. One obvious problem I see, and which I think is huge, is the permission system. Currently, when we run a script with Deno, we have to specify the different permissions we want using arguments like ``--allow-run``, ``--allow-read``.... or ``--all`` or ``-A`` in order to accept all permissions.
The point is that by allowing all permissions on a program, we expose ourselves to serious risk to the machine or the user, but out of "developer laziness", we don't want to have an execution line like:
```
deno run --allow-read --allow-net --allow-write --allow-env mod.ts
```
That's why I propose a new way of working. Arguments are still important, especially for everything CI. At the same time, for a better user experience, I can see something like:
```shell
deno run mod.ts
mod.ts needs the net permission. Do you allow it?
 - Yes
 - No
> Yes
mod.ts needs the write permission. Do you allow it?
 - Yes
 - No
> Yes
```
Once the developer has entered his preferences, they are cached, so that he doesn't have to specify them again.

An alternative would be to have a configuration file for this, specifically, add this possibility to the current configuration system.

I think a better developer experience at this level would bring more developers into the project, or at least interest a part of the community.

This is an open suggestion, and I would love to hear from the developers and the Deno team about this one.

**Comment by crowlKats** [comment]
Deno does have a `--prompt` flag, which will prompt you when a permission required that is needed isnt given.
Regarding config file: #12763

**Comment by Olyno** [comment]
Oh alright, @kitsonk already did an issue about it, thanks you for the issue reference, i'm closing this one because of duplicate.
