### ISSUE TITLE
deno upgrade to 1.18.1 fails on Ubuntu 16.04 with "GLIBC_2.27 not found"

### ISSUE THREAD

**Issue by thomasweitzel** [denoland/deno#13516]
This happens on Ubuntu Linux 16.04, 4.4.0-218-generic #251-Ubuntu SMP Thu Dec 2 09:48:54 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux:

```
$ RUST_BACKTRACE=1 deno upgrade
Looking up latest version
Found latest version 1.18.1
Checking https://github.com/denoland/deno/releases/download/v1.18.1/deno-x86_64-unknown-linux-gnu.zip
31.4 MiB / 31.4 MiB (100.0%)
Deno is upgrading to version 1.18.1
Archive:  /tmp/.tmpjvCQBk/deno.zip
  inflating: deno                    
/tmp/.tmpjvCQBk/deno: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /tmp/.tmpjvCQBk/deno)

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 1.18.0
Args: ["deno", "upgrade"]

thread 'main' panicked at 'assertion failed: output.status.success()', cli/tools/upgrade.rs:306:3
stack backtrace:
   0: rust_begin_unwind
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/core/src/panicking.rs:107:14
   2: core::panicking::panic
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/core/src/panicking.rs:48:5
   3: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   4: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   5: deno::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Only the older  GLIBC 2.23 exits:

```
$ ldd --version
ldd (Ubuntu GLIBC 2.23-0ubuntu11.3) 2.23
```

deno starting with 1.18.1 will not run on a plain Ubuntu 16.04 anymore?

**Comment by lucacasonato** [comment]
What is the most recent version that runs successfully for you?

**Comment by hayd** [comment]
Also the case on Amazon Linux 2 (which deno-lambda runs on top of).

**Comment by kitsonk** [comment]
We have been investigating.  It seems there is some upstream dependency in 1.18.1 that depends on a `glibc-2.27` function that was not present in 1.18.0.  There is nothing obvious in the direct dependencies of the Deno CLI, so it is hunting for the needle in the haystack of what else changed.

**Comment by piscisaureus** [comment]
I tried building Deno on Ubuntu-16.04 (instead of 18.04 as we do currently), but didn't get very far because there are no official llvm/clang 13 builds for Xenial.

**Comment by taisukef** [comment]
I too am blocked by this.

**Comment by nguyendv** [comment]
I have the same issue on Amazon Linux 2, which only has glibc 2.26

**Comment by hayd** [comment]
I was hoping to do a git bisect to find the first commit with this issue...
```sh
# glibc.sh
COMMIT=$(git rev-parse HEAD)
rm -f deno
curl https://dl.deno.land/canary/$COMMIT/deno-x86_64-unknown-linux-gnu.zip -o deno.zip
unzip deno.zip
./deno eval console
```

git bisect start v1.18.1 v1.18.0 --
git bisect run ./glibc.sh

but I guess I left it a little late as canary builds are not available that far back 😭.

---

Perhaps the way to do this is to change the script to build deno then execute the built binary in a docker?
(e.g. for Amazon linux 2):

```
# Dockerfile
FROM public.ecr.aws/lambda/provided:al2
ADD ./deno ./deno  # FIXME: I forget the exact location of binary
ENTRYPOINT ./deno eval console
```

```
# glibc.sh
# hopefully bisect handles recurse of submodules...
cargo build
docker build -t glibc .
docker run glibc
```

**Comment by brianleroux** [comment]
Seeing same in `1.19.1` binary built w GitHub actions (ubuntu-latest) attempting to run on Lambda as a custom runtime. 

Output in case helpful:

```
deno: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by deno)
deno: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by deno)
deno: /lib64/libc.so.6: version `GLIBC_2.27' not found (required by deno)
deno: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by deno)
deno: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by deno)
deno: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by deno)
deno: /lib64/libc.so.6: version `GLIBC_2.27' not found (required by deno)
deno: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by deno)
```

**Comment by piscisaureus** [comment]
I think the only way forward is to provide a separate GCC based build for "old linuxes" such as Amazon Linux and Ubuntu 16.04.

**Comment by brianleroux** [comment]
quick smol update that I managed to get this building using the lambci docker images; 1.19.1 on both versions of Amazon Linux …have a bit of tidying to do then going to open the workflows so anyone can setup/host their own layers

**Comment by piscisaureus** [comment]
Another note: it seems that the regression was introduced by https://github.com/denoland/deno/commit/bce64ee738209dc4c8005154d5b73b4b80d1f882.

**Comment by littledivy** [comment]
Update: 
I think we've found the root cause
In `hexf`, LLVM optimizes 2.0.powf(exponent) (https://github.com/lifthrasiir/hexf/blob/master/parse/src/lib.rs#L343) into exp2f.
I've submitted a patch to avoid this. https://github.com/lifthrasiir/hexf/pull/21 Hopefully after that we just need to upgrade naga and wgpu-hal
