### ISSUE TITLE
implement `console` follow the whatwg spec

### ISSUE THREAD

**Issue by justjavac** [denoland/deno#1351]
Make the `console` implementation follow the [whatwg specification](https://console.spec.whatwg.org). I am working on it.

TODO:

 - Logging methods
   - [x] debug/error/info/log/warn
   - [x] clear #1360
   - [x] assert #1335
   - [x] table #1608 
   - [x] trace
   - [ ] dir/dirxml
- Counting methods
   - [x] count #1358
   - [x] countReset #1358
- Grouping methods
   - [x] group #1363
   - [x] groupCollapsed #1452
   - [x] groupEnd #1363
- Timing methods #1358
   - [x] time
   - [x] timeLog
   - [x] timeEnd
- other
   - [x] format the input if contain formatting specifiers #1565

**Comment by bartlomieju** [comment]
It looks like we're only missing `dirXml` to have full compatibility. Given that console outputs to terminal I think we might alias `dirXml` to `dir`. Opinions?
