### ISSUE TITLE
Compat timers — Property 'bind' does not exist on type 'TimerHandler' — Property 'bind' does not exist on type 'string'

### ISSUE THREAD

**Issue by FutureDrivenDev** [denoland/deno#13528]
Trying to use `--compat` (https://deno.land/manual@v1.17.3/npm_nodejs/compatibility_mode)

I'm getting the error:

```
error: TS2339 [ERROR]: Property 'bind' does not exist on type 'TimerHandler'.
  Property 'bind' does not exist on type 'string'.
      cb.bind(timer)(...args);
         ~~~~
    at https://deno.land/std@0.123.0/node/timers.ts:21:10

TS2339 [ERROR]: Property 'bind' does not exist on type 'TimerHandler'.
  Property 'bind' does not exist on type 'string'.
      cb.bind(timer)(...args);
         ~~~~
    at https://deno.land/std@0.123.0/node/timers.ts:52:10
```

Looking at: https://deno.land/std@0.123.0/node/timers.ts

Lines 9 to 14 read

```
type TimerParams = Parameters<typeof globalThis.setTimeout>;
export function setTimeout(
  cb: TimerParams[0],
  timeout?: TimerParams[1],
  ...args: unknown[]
) {
```

When trying to run the command:

`deno run --allow-net --import-map=import_map.json --unstable --compat server/mod.ts`

On the example repo:

https://github.com/firstdoit/qwik-app-deno-example

Any ideas?

---

It looks to me like `Parameters<typeof globalThis.setTimeout>` is somehow resolving to something which `[0]` has a string.

🤔

**Comment by bartlomieju** [comment]
Does the code execute properly if you pass `--no-check` flag?

**Comment by firstdoit** [comment]
Thanks for the tip, and, no it doesn't but I do progress to some other problem:

```error: Uncaught (in promise) Error: CJS loader requires --allow-read.
      throw new Error("CJS loader requires --allow-read.");
            ^
    at stat (https://deno.land/std@0.123.0/node/module.ts:76:13)
    at Function._findPath (https://deno.land/std@0.123.0/node/module.ts:453:18)
    at Function._resolveFilename (https://deno.land/std@0.123.0/node/module.ts:397:29)
    at Function._load (https://deno.land/std@0.123.0/node/module.ts:514:29)
    at loadCjsModule ([deno:cli/compat/mod.rs:118:30]:3:22)

➜  qwik-app-deno-example git:(main) deno run --allow-net --import-map=import_map.json --allow-read --unstable --compat --no-check server/mod.ts
To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
error: Uncaught (in promise) SyntaxError: Cannot use import statement outside a module
Warning Couldn't format source line: Column 117 is out of bounds (source may have changed at runtime)
    at wrapSafe (https://deno.land/std@0.123.0/node/module.ts:1313:25)
    at Module._compile (https://deno.land/std@0.123.0/node/module.ts:251:29)
    at Object.Module._extensions..js (https://deno.land/std@0.123.0/node/module.ts:1332:10)
    at Module.load (https://deno.land/std@0.123.0/node/module.ts:239:33)
    at Function._load (https://deno.land/std@0.123.0/node/module.ts:558:14)
    at loadCjsModule ([deno:cli/compat/mod.rs:118:30]:3:22)```

I'm trying to import a third-party library, anyway of working around this expect cloning and changing locally?

**Comment by bartlomieju** [comment]
CC @kt3k it seems the typings got out of sync for timers

**Comment by kt3k** [comment]
I'll take a look on timers issues.

> ➜  qwik-app-deno-example git:(main) deno run --allow-net --import-map=import_map.json --allow-read --unstable --compat --no-check server/mod.ts
> To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
error: Uncaught (in promise) SyntaxError: Cannot use import statement outside a module

For this error, how about setting "type": "module" in package.json?

**Comment by firstdoit** [comment]
I don't control the library :/

**Comment by kt3k** [comment]
The reason of type error is that `deno.json` has `"lib": ["deno.ns", "deno.unstable", "dom", "dom.iterable", "dom.asynciterable"]` settings. This doesn't include the type definition of `setTiemout` etc, and it caused the above error.

If you remove `lib` section, the above type error should be resolved.

**Comment by kt3k** [comment]
> I don't control the library :/

I meant the package.json in `qwik-app-deno-example` repository. The "type" property controls the module mode of the project. https://nodejs.org/api/packages.html#type

When I added `"type": "module"`, the error now looks like the below:
```
$ deno run --allow-net --import-map=import_map.json --unstable --compat -A server/mod.ts
error: Module not found "file:///Users/kt3k/oss/qwik-app-deno-example/server/build/q-symbols.json".
    at file:///Users/kt3k/oss/qwik-app-deno-example/server/mod.ts:4:21
```

I tried to create `q-symbols.json` by `npm run build`, but rollup build failed with the error like the below:

```
[!] Error: 'component' is not exported by node_modules/@builder.io/qwik/core.mjs, imported by src/components.tsx
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
src/components.tsx (2:15)
1: import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "@builder.io/qwik/jsx-runtime";
2: import { Host, component, onRender$, useStore, useHostElement, useEvent, notifyRender, $ } from '@builder.io/qwik';
                  ^
```

Do you have any idea about this error?

**Comment by firstdoit** [comment]
Oooh, that's great progress! So, I added `lib` because Qwik requires some types in `"dom", "dom.iterable"`.

Regarding `component`, yes, apparently the `qwik` project is moving fast and there were some renames on this file. Give me until the end of the week, while I iron out these qwik-specific errors with the fine folks from that project. We are attempting to get Qwik running under Deno and using the `jsxImportSource`. Sometimes it's hard to get whether the current problem is in Deno or in Qwik. 

Thanks for your patience and I'll come back with a cleaner repro soon!

**Comment by firstdoit** [comment]
BTW: 

> This doesn't include the type definition of setTiemout

Which lib does, then? Maybe I can simply add the one that's missing?
