### ISSUE TITLE
TypeScript emit failure for extensionless TS file

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#13526]
Wipe your DENO_DIR, then put the below code into a `main.ts` file and run `deno run main.ts`

```ts
import "https://googleapis.deno.dev/v1/spanner:v1";
```

You will get the following error:

```
error: TS5056 [ERROR]: Cannot write file 'https://googleapis.deno.dev/v1/spanner:v1.js' because it would be overwritten by multiple input files.
```

**Comment by kitsonk** [comment]
We have logic to handle this sort of thing it there, but I am wondering if the colon is throwing it off, or it is the case of import only.  Either way, we should be able to fix it.

**Comment by lucacasonato** [comment]
> or it is the case of import only

It also happened with named imports, so this isn't it

**Comment by kitsonk** [comment]
Ok, then it is the logic somehow... with such a clear repo, it should be easy to amend.  Basically there is a map on tsc state on the Rust side that contains the map for these specifiers that tsc refuses to deal with properly.

Likely won't be able to fix it until Monday my time.

**Comment by lucacasonato** [comment]
Yeah that what I was suspecting is causing the issues. No rush 🙂

**Comment by kitsonk** [comment]
Ok, I can reproduce.

We already had a test for import a file with a colon in it, but that file also includes an extension, where it appears to be the combination of extensionless and a colon causes the error experienced.

**Comment by kitsonk** [comment]
Correction, the colon makes no difference... wow, this must have been there for a long time. 😟
