### ISSUE TITLE
Deno 1.18.1 LSP shows errors outside of Deno project

### ISSUE THREAD

**Issue by bradenmacdonald** [denoland/deno#13524]
I have a multi-root workspace where some folders like the `backend` use Deno and others like the `frontend` use Node/Next.js.

When I upgraded to Deno 1.18.1, although the LSP feels more performant, it introduced a regression that is showing deno error messages in the Node.js part of the workspace, where Deno should not be enabled at all.

## Before - Deno 1.18.0

When editing a frontend .tsx file, Deno should not be used:

<img width="1463" alt="before" src="https://user-images.githubusercontent.com/945577/151629079-89959cf7-c1b2-4e04-8e7a-ea02d6954e27.png">

## After - Deno 1.18.1

<img width="1467" alt="after" src="https://user-images.githubusercontent.com/945577/151629064-af5cb810-1d83-4264-a6d9-c32f68aded9e.png">

You can see TypeScript errors coming from the Deno LSP, but they're not applicable since that part of the project does not have Deno enabled.

**Comment by kitsonk** [comment]
@dsherret it seems like the diagnostics refactoring (and or the specifier config refactoring) has caused a regression.

**Comment by dsherret** [comment]
@bradenmacdonald sorry about that one and thanks for reporting it! It should be fixed in 1.18.2 next week.

**Comment by bradenmacdonald** [comment]
No problem, thanks for the very quick fix @dsherret !
