### ISSUE TITLE
TypeScript: variables in `catch` should be `unknown` on default settings

### ISSUE THREAD

**Issue by davimiku** [denoland/deno#13531]
With the following code:

```typescript
try {
  throw 'not an Error object'
} catch (error) {
  console.error(error.message)
}
```

The Deno language server shows the type of the `error` variable as `any`, which should be `unknown` and a compiler error. Below is a screenshot of the Deno language server running in Visual Studio Code.

![catch_variable_any](https://user-images.githubusercontent.com/36610621/151671283-9278ff13-9fe9-40b0-a69b-027f69817f02.png)

Version information:
```
deno 1.18.0 (release, x86_64-unknown-linux-gnu)
v8 9.8.177.6
typescript 4.5.2
```

Since TypeScript v4.4, [useUnknownInCatchVariables](https://www.typescriptlang.org/tsconfig/#useUnknownInCatchVariables) is activated when `strict` is `true`. According to the [documentation on deno.land](https://deno.land/manual/typescript/configuration), the default value of `strict` is `true` in Deno's default tsconfig, so `useUnknownInCatchVariables` would be implicitly `true` by default also.

**Comment by dsherret** [comment]
It is a major change. See and discuss in #11826

**Comment by davimiku** [comment]
OK got it, I see. I will open a separate issue to fix the documentation.
