### ISSUE TITLE
Convert generated lock file to import map

### ISSUE THREAD

**Issue by Dmitri-Sintsov** [denoland/deno#13532]
Is it possible to convert the `lock.json` file generated with `deno run --lock --lock-file=lock.json mod.ts` to import map, so the fresh run of `deno run --import-map=import_map.json mod.ts` with code that has deno.land external urls with unspecific module versions would be actually loaded from the urls with specific module versions from previously generated lock.json file?

**Comment by lucacasonato** [comment]
@Dmitri-Sintsov Have you considered `deno vendor`?

**Comment by Dmitri-Sintsov** [comment]
Thanks, I'll check it out. Did not know about `vendor` command, maybe it was added into more recent version of Deno than I originally used.

**Comment by lucacasonato** [comment]
Yup, it was added pretty recently.

**Comment by Dmitri-Sintsov** [comment]
Anyway is it a good idea for deno std to fetch non-versioned `node_process.js`? Maybe deno developers should consider to regularly copy and re-distribute it and fetch it as versioned module instead? Or that is not an issue.

**Comment by milahu** [comment]
> Have you considered `deno vendor`?

should be mentioned in
https://deno.land/manual@v1.26.1/linking_to_external_code/integrity_checking
