### ISSUE TITLE
[AES-GCM] Deno panics on decryption when tagLength is not 128 bits (encryption is okay)

### ISSUE THREAD

**Issue by pedropaulosuzuki** [denoland/deno#13534]
Hello! Hope everybody is okay!

Today I was testing decryption using the recently added Galois Counter Mode for AES in Deno and found out that it panics on decrypting if the tagLength is anything but 128 bits length.

If one is encrypting, there is no issue or panic message, but on decrypting, it is present. If the tagLength is unsupported, then it should fail on encryption too, or at least throw an JS runtime error instead of a Rust panic.

Code:
```ts
const key = await crypto.subtle.importKey("raw", new Uint8Array(32), 'AES-GCM', false, ["encrypt", "decrypt"]);

const iv = crypto.getRandomValues(new Uint8Array(12));

const encrypted = await crypto.subtle.encrypt({ name: 'AES-GCM', iv, tagLength: 96, additionalData: new ArrayBuffer(0)}, key, new Uint8Array(32));

const decrypted = await crypto.subtle.decrypt({ name: 'AES-GCM', iv, tagLength: 96, additionalData: new ArrayBuffer(0)}, key, encrypted );
```

Panic message:
```
==================================================================
Deno has panicked. This is a bug in Deno. Please report this at
<https://github.com/denoland/deno/issues/new>.
If you can reliably reproduce this panic, include the reproduction
steps and re-run with the RUST_BACKTRACE=1 env var set and include
the backtrace in your report.

Platform: linux x86_64
Version: 1.18.1
Args: ["deno", "run", "mod.ts"]

Thread 'tokio-runtime-worker' panicked at 'assertion failed: `(left == right)`
  left: `12`,
 right: `16`', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/generic-array-0.14.5/src/lib.rs:559:9
Note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
==================================================================
```

**Comment by littledivy** [comment]
This is an unfortunate limitation in the [`aes_gcm`](https://docs.rs/aes-gcm/latest/aes_gcm/struct.AesGcm.html). The tag length is required to be 128 bits.
When encrypting, the tag is truncated to the specified tag length as per the spec, so encryption doesn't fail.

Ideally we should be throwing instead of panickin during decryption.
