### ISSUE TITLE
Tab Completion not working on Deno v1.18.1

### ISSUE THREAD

**Issue by abner** [denoland/deno#13538]
When using REPL in deno v1.18.1 the TAB completion is not working.

I tested using version `1.18.0` and jumped to v1.16.0 too and it works Ok so I think it got broken in the v1.18.1.

All binaries were tested using linux environment. I tested also using the docker containers denoland/deno and testing using different images (debian, alpine,distroless, centos) and the TAB completion does not work in all of them at the version `1.18.1`

**Comment by bartlomieju** [comment]
I can confirm that it's not working on Mac either.

**Comment by bartlomieju** [comment]
Did a bisect, it broke in #13501; I will look into fixing this. Sorry for inconvenience.

**Comment by bartlomieju** [comment]
Need to add a test for tab completions too

**Comment by bartlomieju** [comment]
Should be now fixed with https://github.com/denoland/deno/commit/b7b6b9c9e5b84dea67ff6a2b691245f640644b2c
