### ISSUE TITLE
allow bundle to ignore choice bare modules

### ISSUE THREAD

**Issue by mlanza** [denoland/deno#13544]
I have a set of deeply nested es6 libraries all of which I compile with Babel.  The next stage in the pipeline is to bundle each deeply nested, modular library into a single bundle.  I would like to use the Deno `bundle` command.

I provide an import map which causes each bare module to be pulled in and defeats the purpose of bundling.  I would like to bundle only the relative paths.  Each of the libraries being bundled results in one of the shared bare modules.  I tried setting the import map to use remote paths and use the `--no-remote` flag to prevent the dependencies from being pulled into each module.  The point is for each bundle to stand alone as its own separate module.

In Rollup.js, there is an option to name bare modules which are external.  The parser recognizes such imports as external, standalone modules and does not pull them in.  Couldn't Deno do the same?  This way it can be used in one stage to create bundles. Then at runtime, when provided an import map, it can resolve the bare modules.

**Comment by kitsonk** [comment]
Why wouldn't dynamic `import(...)` be a solution in your case?  `deno bundle` does not touch these.  Especially because it makes no assumptions about the location at run-time.  Ideally we want to keep `deno bundle` minimalistic and straight forward way of creating single file library bundles, and nothing more, and intelligently eliding static imports sort of goes against the grain, where dynamic imports are part of the platform already.

**Comment by mlanza** [comment]
While `import(...)` can serve its purpose it still requires path specificity.  The immense benefit of import maps is they allow bare modules to be dynamically specified separately.  This makes it possible using a single import map to enact feature switches, to rollback to prior versions, and to otherwise substitute proxy modules freely in place, by name.  It abstracts away the module in the same way that adapters or decorators can be plugged into programs.

I didn't think this would be a difficult implementation.  I basically, thought that one could pass in `--external 'jquery','lodash'` and so on and the bundler would simply skip the import of these externals.  In this way one could generate a module with abstract dependencies which could be specified by way of import map.  And when import maps are finally implemented in browsers, the same would hold true.

**Comment by kitsonk** [comment]
> While `import(...)` can serve its purpose it still requires a relative, static path, making it a less elegant option.

Import maps apply to dynamic imports.

**Comment by mlanza** [comment]
All I am saying is leaving bare modules alone as part of a bundling process benefits the use case I described.  
 Presently I am already doing this with Rollup.  Others must be doing it too, since the feature exists there.  Using Deno could eliminate the need for Rollup provided this one feature.  I guess I figured optionally ignoring bare modules (during bundling) would not be a significant effort.  If you're not seeing the value, feel free to close the request.

**Comment by nayeemrmn** [comment]
Bare specifiers tend to be external `node_modules` dependencies in Node. Probably why rollup has that, it would be a strange category in Deno. The equivalent would usually be remote modules.

Being able to exclude remote or arbitrary modules from bundles would be useful: `deno bundle main.ts --exclude-remote`, `deno bundle main.ts --exclude=https://example.com/remote.ts,./relative.ts,bare`. The former lets you distribute libraries as bundles for example. The latter provides granular control over split bundle structures, e.g. a frontend (or native I suppose) app with two entrypoints that share a large part of their module graphs could be cut into 3 optimised bundles by some client tool. Similar concept to @mlanza's use case.

The imports for excluded modules would be rewritten to be relative to the main module if applicable and left in the bundle. @mlanza's use case would be achieved with `deno bundle main.ts --exclude=foo,bar`.

**Comment by mlanza** [comment]
To further summarize, I consider bare modules when paired with import maps a killer feature.  I'm just trying to preserve it in the context of bundling.

**Comment by lucacasonato** [comment]
`deno bundle` has been removed in Deno 2.
