### ISSUE TITLE
What exactly of the `fetch` standard is implemented?

### ISSUE THREAD

**Issue by benjamingr** [denoland/deno#13541]
Hey,

Node is considering adding a fetch implementation and I was wondering if the list of things Deno doesn't implement in `fetch` (presumably stuff like the GC requirements, relative paths and CORS) is documented somewhere?

In addition, is there some "whatwg blessed" way to implement "as much as fetch as reasonably possible for a server-side implementation"?

Reference: https://github.com/nodejs/node/pull/41749#issuecomment-1025201595

**Comment by lucacasonato** [comment]
Deno implements all of the fetch spec including the GC requirements and relative paths, with the exception of the spec deviations outlined at https://deno.land/manual@29346ec07971a376530a75dedbc329eafbb10d79/runtime/web_platform_apis#spec-deviations.

**Comment by benjamingr** [comment]
Thanks, that's very clear 🙏 !
