### ISSUE TITLE
Unstable flag does not work at all?

### ISSUE THREAD

**Issue by creepinson** [denoland/deno#13557]
Hi there. I'm using deno 1.18.1 and I am trying to write a bundler script using Deno.emit and Oak.

I am encountering several errors related to the unstable flag. I have also tried adding the following to deno.jsonc and adding `--config deno.jsonc`, with no success.

```json
{
    "compilerOptions": {
        "strict": true,
        "lib": [
            "dom.asynciterable",
            "deno.unstable",
            "deno.ns",
            "deno.worker"
        ]
    }
}
```

What's even weirder is that it happens on a empty project with no deno.jsonc and just the same bundler.ts file and `deno run --unstable -A bundler.ts`. I also tried using `--reload` and the same error appeared.

It acts like I didn't pass the flag at all...

```
TS2488 [ERROR]: Type 'URLSearchParams' must have a '[Symbol.iterator]()' method that returns an iterator.
  for (const [key, value] of ctx.request.url.searchParams) {

TS2339 [ERROR]: Property 'emit' does not exist on type 'typeof Deno'. 'Deno.emit' is an unstable API. Did you forget to run with the '--unstable' flag?
```

[Full error and code is here](https://gist.github.com/creepinson/b9dcf40138c33e24e2403d458d0c92c8).

**Deno --version**:

> deno 1.18.1 (release, x86_64-unknown-linux-gnu)
v8 9.8.177.6
typescript 4.5.2

**Comment by kitsonk** [comment]
This has nothing to do with the `--unstable` flag.  When you supply a `"lib"` setting in TypeScript, it discards all the built in libraries.  Your `deno.jsonc` needs to be more like this:

```jsonc
{
  "compilerOptions": {
    "lib": [
      "dom",
      "dom.iterable",
      "dom.asynciterable",
      "deno.ns",
      "deno.unstable"
    ]
  }
}
```

In addition, you are using https://deno.land/x/twd@v0.4.8/mod.ts which has:

```ts
/// <reference no-default-lib="true"/>
/// <reference lib="deno.ns" />
/// <reference lib="dom" />
/// <reference lib="esnext" />
```

Which is resetting the libs you are providing.  I forked your [gist](https://gist.github.com/kitsonk/b75a862f0795e09363d4f230c02b48b5) and added the following to the top of your `bundle.ts`:

```ts
/// <reference no-default-lib="true"/>
/// <reference lib="deno.ns" />
/// <reference lib="deno.unstable" />
/// <reference lib="dom" />
/// <reference lib="dom.iterable" />
/// <reference lib="dom.asynciterable" />
```

And it now works when you run it:

```
> deno run --unstable -A https://gist.githubusercontent.com/kitsonk/b75a862f0795e09363d4f230c02b48b5/raw/809983b272b17e9a74414d1c62c9f7be59679241/bundler.ts 
```

@kt3k your libs in `twd` are incomplete and as you can see, that way of providing the configuration can cause breakage unless it is overridden further up the stack.  I think you might want to consider not using the triple-slash references and inform people that they will need to provide a configuration providing the proper libraries.  The triple-slash references are a big hammer.

@creepinson you can see an example of integrating oak, unstable APIs and twind here: https://github.com/denoland/docland, which does not require the triple-slash references.
