### ISSUE TITLE
lsp: notify client when config file is auto-discovered

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#13552]
In order to be able to provide "auto-enablement" of Deno projects with the language server when a config file is auto-discovered, the language server would need to search the workspace and notify the client when a `deno.jsonc` file is auto-discovered as well as have semantics for being "enabled" when that occurs (but respecting explicit configuration of not-being enabled).

The biggest challenge is the explicit enablement/disablement, as we can't really disambiguate that at the moment.  The specific case which I don't think we can currently handle is that there is a `deno.jsonc` in the workspace root, but the user has for whatever reason, explicitly set it as `"deno.enable": false` versus that being the default value.

Ref: denoland/vscode_deno#617

**Comment by nayeemrmn** [comment]
Closed by #20827.
