### ISSUE TITLE
`import` with query string ending in ".json" causes crash

### ISSUE THREAD

**Issue by pauljoey** [denoland/deno#13562]
file1.ts:

    console.log(import.meta.url)
    
file2.ts:

    import './file1.ts?path=foo.json'

Command:

    deno run ./file2.ts

Result:

```
============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos x86_64
Version: 1.18.1
Args: ["deno", "run", "./file2.ts"]

thread 'main' panicked at 'internal error: entered unreachable code: unexpected media_type Json
```

**Comment by pauljoey** [comment]
For anyone landing on this, an easy work-around is

    import './file1.ts?path=foo.json&'
    import './file1.ts?path=foo.json#'

**Comment by bartlomieju** [comment]
Either `deno_graph` or `deno_core` bug; I'll look into it before 1.18.2.

**Comment by kitsonk** [comment]
I am trying to chase it down.  It should be noted that it only affects local (`file://`) specifiers.  Remote specifiers are unaffected.

**Comment by kitsonk** [comment]
Ok, it appears to be a challenge handling the emitted files from the TypeScript compiler.  If you do `deno run --no-check ./file2.ts` it should also work.
