### ISSUE TITLE
Suggestion: Custom URI scheme support

### ISSUE THREAD

**Issue by Redstoneguy129** [denoland/deno#13576]
Custom URL scehems provide a way to reference endpoints inside an app. Users accessing a custom url e.g. `appname://endpoint` in the browser for example would launch the app to the specified endpoint. Other apps can also trigger the endpoint.

**Comment by hironichu** [comment]
I a not sure you if you mean.. the ability to use custom apps schemas inside deno to call other apps (such as Discord/Chrome and so on) or the ability to register a custom scheme for a Deno app ?

**Comment by Redstoneguy129** [comment]
ability to register a custom scheme for a Deno app

**Comment by lucacasonato** [comment]
This is not something that Deno itself should do. You can create a custom URL scheme handler that uses your Deno application without needing to add any functionality to Deno. For example on Linux you can create an `x-scheme-handler` in your XDG desktop entry for your application. See https://unix.stackexchange.com/questions/497146/create-a-custom-url-protocol-handler
