### ISSUE TITLE
Extracting V8 bindings into a standalone crate?

### ISSUE THREAD

**Issue by Neurrone** [denoland/deno#1357]
Hi,

There aren't any existing bindings to V8 that are up to date. Based on the crate documentation, Deno is able to call V8 APIs, and it would be useful to use this for scripting from standalone Rust programs.

**Comment by hayd** [comment]
see #1209 , I don't think the plan is to expose the entire v8 API however...

**Comment by Neurrone** [comment]
@hayd sure, I think for most use cases, the ability to ergonomically call rust functions from javascript and vice versa and use rust structs as js classes would be enough.

I tried using bindgen to do the binding, but it kept crashing when i tried creating a new isolate, and could never figure out why.

**Comment by bartlomieju** [comment]
Deno is available as a crate at [https://crates.io/crates/deno](https://crates.io/crates/deno). 

Can this issue be closed now? CC @ry

**Comment by Neurrone** [comment]
Just looked at the documentation, it doesn't look like there's a way of exposing rust objects to JS and vice versa.

**Comment by ry** [comment]
@Neurrone Deno's philosophy is to only allow binary blobs (Uint8Arrays) to be passed back and forth between V8. This has very nice consequences if it is adhered to. So we will not be automatically exposing Rust objects to JS. (Though a proper FFI is on the roadmap.)

Despite the lack of documentation, https://crates.io/crates/deno is by far the most advanced Rust V8 binding out there. Please try it.
