### ISSUE TITLE
Deno.test: shorter stack traces

### ISSUE THREAD

**Issue by mfulton26** [denoland/deno#13586]
`Deno.test` currently prints the entire stack for errors in failures but this is typically unnecessary and is noise (unless you're troubleshooting `deno test` itself).

I suggest omitting deno-cli-specific stack information and, if needed, provide an opt-in flag for printing the entire stack but to not print it by default.

This should make it easier for developers to understand why their tests failed and not be concerned about Deno's internal runtime details, etc.

e.g.

```ts
import { fail } from "https://deno.land/std@0.123.0/testing/asserts.ts";

Deno.test("example", () => fail());

```

current output:

```console
% deno test test.ts
running 1 test from file:///path/to/test.ts
test example ... FAILED (8ms)

failures:

example
AssertionError: Failed assertion.
    at assert (https://deno.land/std@0.123.0/testing/asserts.ts:222:11)
    at fail (https://deno.land/std@0.123.0/testing/asserts.ts:597:3)
    at file:///path/to/test.ts:3:28
    at testStepSanitizer (deno:runtime/js/40_testing.js:186:13)
    at asyncOpSanitizer (deno:runtime/js/40_testing.js:67:15)
    at resourceSanitizer (deno:runtime/js/40_testing.js:137:13)
    at Object.exitSanitizer [as fn] (deno:runtime/js/40_testing.js:169:15)
    at runTest (deno:runtime/js/40_testing.js:427:18)
    at Object.runTests (deno:runtime/js/40_testing.js:540:28)
    at [deno:cli/tools/test.rs:505:6]:1:21

failures:

        example

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out (24ms)

error: Test failed
```

desired output:

```console
% deno test test.ts
running 1 test from file:///path/to/test.ts
test example ... FAILED (8ms)

failures:

example
AssertionError: Failed assertion.
    at assert (https://deno.land/std@0.123.0/testing/asserts.ts:222:11)
    at fail (https://deno.land/std@0.123.0/testing/asserts.ts:597:3)
    at file:///path/to/test.ts:3:28

failures:

        example

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out (24ms)

error: Test failed
```

diff:

```patch
--- a.txt	2022-02-03 07:45:54.000000000 -0600
+++ b.txt	2022-02-03 07:46:04.000000000 -0600
@@ -9,13 +9,6 @@
     at assert (https://deno.land/std@0.123.0/testing/asserts.ts:222:11)
     at fail (https://deno.land/std@0.123.0/testing/asserts.ts:597:3)
     at file:///path/to/test.ts:3:28
-    at testStepSanitizer (deno:runtime/js/40_testing.js:186:13)
-    at asyncOpSanitizer (deno:runtime/js/40_testing.js:67:15)
-    at resourceSanitizer (deno:runtime/js/40_testing.js:137:13)
-    at Object.exitSanitizer [as fn] (deno:runtime/js/40_testing.js:169:15)
-    at runTest (deno:runtime/js/40_testing.js:427:18)
-    at Object.runTests (deno:runtime/js/40_testing.js:540:28)
-    at [deno:cli/tools/test.rs:505:6]:1:21
 
 failures:
 
```

**Comment by lucacasonato** [comment]
I have actually previously proposed we do this for all stack traces in the runtime (remove all stack entries coming from `deno:` source files), and only show them if `DENO_STACKTRACES=full` is used. I remember there being some pushback on that. I think it makes sense if we at least do this for testing though. The excessively long stack traces have always frustrated me too.

**Comment by lucasfcosta** [comment]
Personally, I think this would be a great idea.

A long time ago, [I've written in detail about how `chai` does this](https://lucasfcosta.com/2017/02/17/JavaScript-Errors-and-Stack-Traces.html).

This also seems like it's quite common behaviour everywhere else in the JS ecosystem. For reference, [Jest also does it](https://github.com/facebook/jest/blob/5160ae01f81041529a1d6e81eb670ff60e997d84/packages/expect/src/index.ts#L293-L297).

I'd be happy to contribute with this feature if maintainers do decide to go forward with it (in case they'd be happy for me to do so) 😊

**Comment by bartlomieju** [comment]
@lucasfcosta yes, this is desired behavior. If you'd like to work on it then great, PRs are always greatly appreciated!

**Comment by lucasfcosta** [comment]
I believe we can close this one because the desired behaviour has already been implemented.

It seems to be implemented through the op below which is called when formatting a callsite:

https://github.com/denoland/deno/blob/6fad5c33c9dd51a2cb2c1ba1be5312f46835b6c4/cli/fmt_errors.rs#L41-L68

We may want to implement this behaviour only when a particular flag is set though.

Also, I double-checked that internal frames are indeed cut-off by running the following two tests, one with `deno test` and the other with `deno run` (in this order).

```ts
function t() {
  throw new Error("example");
}

t();
```

```ts
import { fail } from "https://deno.land/std@0.123.0/testing/asserts.ts";

Deno.test("example", () => fail());
```

No internal frames appeared in both cases.

**Comment by bartlomieju** [comment]
Ah I was looking for this issue but couldn't find it. Indeed this issue was fixed by https://github.com/denoland/deno/pull/14302
