### ISSUE TITLE
Make FS and net APIs work well with WHATWG streams

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#13614]
Currently our FS and net APIs use "Go style" streams (`Reader` / `Writer`). While these kinds of streams are very fast and simple, they are not very well compatible with `fetch` and all our newfangled `CompressionStream` and `TextEncoderStream` utilities.

Currently `std/streams` has `readableStreamFromReader` and `writableStreamFromWriter` functions to convert from `Writer` to `WritableStream` and from `Reader` to `ReadableStream`. While these are convenient, they are not as convenient as not having to use them at all.

To solve this I am proposing adding a `readable` and `writable` property to all of our internal implementations of `Reader` and `Writer`. `readable` would return a `ReadableStream<Uint8Array>` and `writable` would return a `WritableStream<Uint8Array>`.

This makes `Deno.File` really convenient to use for use with the native HTTP server or fetch for example:

```js
const file = await Deno.open("/etc/passwd");
const resp = await fetch("https://example.com", {
  method: "POST",
  body: file.readable
});
await resp.body.pipeTo(Deno.stdout.writable);
```

This could land independently of how #11018. These two APIs can co-exist - it doesn't need to be one or the other.

**Comment by crowlKats** [comment]
From a quick look, this seems like a good solution. I'd say that this is "blocked" on https://github.com/whatwg/streams/pull/1145, and writable byte stream (cant find the issue, but remember reading about it somewhere)

**Comment by lucacasonato** [comment]
> else, the writable we would have on Writer would always be like our current writeAll.

Yup, this is what my current thinking was. I think adding support for these "byte" streams would be a backwards compatible change (or would it not?).

**Comment by crowlKats** [comment]
Well, from my findings there is no concrete spec, so i have no idea, but i assume its gonna be a similar deal to readablestream, so then yea, it would be backwards compatible
