### ISSUE TITLE
Proposal: Increase max number of threads Deno can spawn if user decide to

### ISSUE THREAD

**Issue by Amatsagu** [denoland/deno#13637]
Network related elements makes Rust side to launch new threads in order to make it "non blocking", right? We can start new TCP server or going higher - WS/HTTP and those can work on single thread on small usage but once our service gets heavily used - it starts to spawn new threads to manage that.

The thing is that big apps working on Deno seems to be hitting max number of threads that Deno allows to use. While testing - I've ran a simple TCP server: `deno run --allow-net https://deno.land/x/websocket@v0.1.3/example/server.ts` and made it connect 1024 shards that were sending random payloads (client attacker made in Julia). Server was working fine for a few seconds - then dramatically slow down, it started to receiving like 8~12 payloads, then was idle for like 0.2s then another ~8 payloads. During such heavy usage - Deno's TCP server started to have issues with memory - it simply grows infinitely cause it couldn't handle such pressure at once.

My suggestion is adding a flag like `--max-threads` to the deno run/compile commands that would allow user to define how many threads can Deno use on their machine. Of course perfect solution would be optimizing Deno's TCP/WebSocket API but increasing number of max threads sounds good enough.

**Comment by Amatsagu** [comment]
I don't know if it matters but I have i5-10400F @ 2.90 GHz CPU. Server was using like <1% of my CPU so I don't think that's because my PC couldn't handle more...

**Comment by bartlomieju** [comment]
> Network related elements makes Rust side to launch new threads in order to make it "non blocking", right? We can start new TCP server or going higher - WS/HTTP and those can work on single thread on small usage but once our service gets heavily used - it starts to spawn new threads to manage that.

That's not true, all of Deno's networking runs on a single thread, Rust side doesn't spawn new threads for anything besides FS operations. 

> During such heavy usage - Deno's TCP server started to have issues with memory - it simply grows infinitely cause it couldn't handle such pressure at once.

Can you provide an heap profile for such case? It's hard to debug what's the problem in this situation.

> My suggestion is adding a flag like --max-threads to the deno run/compile commands that would allow user to define how many threads can Deno use on their machine. Of course perfect solution would be optimizing Deno's TCP/WebSocket API but increasing number of max threads sounds good enough.

Again, Deno only uses threadpool for FS operations and this number is fixed. The only other case where there are multiple threads is when you spawn workers using `new Worker()` API.
