### ISSUE TITLE
Test with specified permissions throws PermissionDenied

### ISSUE THREAD

**Issue by omartsokha** [denoland/deno#13634]
Test with specified permissions throws ```PermissionDenied``` when run with ```deno test```:

```typescript
Deno.test('example', { permissions: { read: true } }, () => {
    const content = Deno.readTextFileSync('./data/draft_1.txt')
})
```

```
PermissionDenied: Can't escalate parent thread permissions
    at Object.opSync (deno:core/01_core.js:149:12)
    at pledgePermissions (deno:runtime/js/40_testing.js:256:19)
    at Object.applyPermissions [as fn] (deno:runtime/js/40_testing.js:267:21)
    at runTest (deno:runtime/js/40_testing.js:427:18)
    at Object.runTests (deno:runtime/js/40_testing.js:540:28)
    at [deno:cli/tools/test.rs:505:6]:1:21
```

It works as expected if run with ```deno test --allow-read```:

```
deno 1.18.2 (release, x86_64-unknown-linux-gnu)
v8 9.8.177.6
typescript 4.5.2
```

**Comment by crowlKats** [comment]
This is correct behaviour. you need to pass permissions to run code that requires permissions. specifying permissions on Deno.test is to further tighten down permissions for individual test cases.

**Comment by omartsokha** [comment]
> This is correct behaviour. you need to pass permissions to run code that requires permissions. specifying permissions on Deno.test is to further tighten down permissions for individual test cases.

I thought the point of specified permissions was to allow it for this specific test, thanks for the clarification!
I believe, some additional explanation in [section](https://deno.land/manual/testing#writing-tests) of docs where I found this feature might help someone.
