### ISSUE TITLE
REPL imports should use no-check by default

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#13640]

**Comment by bartlomieju** [comment]
I agree, this should speed up REPL significantly

**Comment by a-lafrance** [comment]
I'm interested in giving this change a try if that's alright, although I'm not super familiar with the codebase so I might need some more context about what exactly this change entails. I was poking around the code to try and get more info and I found the `no-check` flag in the CLI, so I guessed that maybe this change is just setting a different default for that flag for the `repl` subcommand.

So concretely I guess I have 2 related questions:
1. Is my understanding correct? I'm under the impression that I'm basically just setting the check flag to either `None` or `Local` as a default for `repl`, so I'd just like to make sure I'm on the right track

2. If that's not quite the right thought process, I'd really appreciate some guidance to get me on the right track.

Thanks in advance!

**Comment by bartlomieju** [comment]
Hi @a-lafrance, thanks for looking into this.

> Is my understanding correct? I'm under the impression that I'm basically just setting the check flag to either None or Local as a default for repl, so I'd just like to make sure I'm on the right track

Yes, this is right. In `repl_parse` in `cli/flags.rs` set `flags.no_check` to `None` and that should be it.

**Comment by a-lafrance** [comment]
great, thanks for the info! I'll try to get a PR up soon

**Comment by VishnuJin** [comment]
> Yes, this is right. In `repl_parse` in `cli/flags.rs` set `flags.no_check` to `None` and that should be it.

jfyi @a-lafrance `flags.check` should be set to `CheckFlag::None`

**Comment by GJZwiers** [comment]
With #14112 landed this could be closed
