### ISSUE TITLE
deno errored out when importing from url with port 8081

### ISSUE THREAD

**Issue by cj1128** [denoland/deno#13641]
```ts
import foo from "http://localhost:8081/foo.ts"
```

Deno outputs following error

```
error: Expected a JavaScript or TypeScript module, but identified a Unknown module. Importing these types of modules is currently not supported.
```

I tried other ports and they all ok.

```
$ deno --version
deno 1.18.2 (release, x86_64-apple-darwin)
v8 9.8.177.6
typescript 4.5.2
```

**Comment by Bzvwf16WSDKoSZd8** [comment]
Can you posting your file content of foo.ts?

**Comment by cj1128** [comment]
It's just a simple module

```ts
export default "this is foo"
```

If I change the port to another one like 8082, then everything works. the content of `foo.ts` seems irrelevant to this bug.

**Comment by bartlomieju** [comment]
What server are you using to serve this file?

**Comment by cj1128** [comment]
I figured this out. It's because the cache.

`http://localhost:8081/foo.ts` used to be served under a wrong MIME type `application/typescripot` and deno cached this info. 

when I tried `DENO_DIR=tmp deno run` everything worked fine.

Thank you guys~

**Comment by JhonnyJason** [comment]
Hummm I am trying to import directly from github. And receive the same response - so I guess it is because of the MIME-type
Is there a way to ignore the MIME-type? 
Or do I have to manually serve from my server where I can specify the correct MIME-type myself - that seems unnecessarily tedious^^...
