### ISSUE TITLE
cpu limit per isolate

### ISSUE THREAD

**Issue by amirhosseinvz94** [denoland/deno#13654]
Hi,

I'm executing untrusted javascript inside deno, and i have trouble
with some scripts that take cpu time.

Is there any way I can set an execution cpu time limit of some deno executed
script?

**Comment by jsejcksn** [comment]
@amirhosseinvz94  AFAIK, V8 doesn't offer this, but there's lots of online documentation to be found for [setting the priority of a process](https://www.google.com/search?q=set+process+priority) on a given operating system. You can use these methods in combination with `deno compile` to set the priority for a specific compiled binary.
