### ISSUE TITLE
[bug/docs] deno_runtime docs are failing

### ISSUE THREAD

**Issue by marc2332** [denoland/deno#13655]
Docs for `deno_runtime` are not being built since version 0.42.0. Versions [0.43.0](https://docs.rs/crate/deno_runtime/0.43.0) and [0.44.0](https://docs.rs/crate/deno_runtime/0.44.0) are failing.

![image](https://user-images.githubusercontent.com/38158676/153713708-695bbcca-bb25-434f-9e08-b5f6b2b46754.png)

This is the error causing the build to fail: https://docs.rs/crate/deno_runtime/0.44.0/builds/503932

```shell
[INFO] [stderr] error: Unrecognized option: 'extern-html-root-url'
``` 
And because of this, no docs are shown in crates.io

![image](https://user-images.githubusercontent.com/38158676/153713742-3bbed571-1ac9-4081-b88c-e3a1e3b7541c.png)

ty :)

**Comment by littledivy** [comment]
As the error indicates, this is an ICE (Internal Compiler Error) in Rust. https://docs.rs/crate/deno_runtime/0.44.0/builds/503932

**Comment by marc2332** [comment]
0.45.0 https://docs.rs/deno_runtime/0.45.0/deno_runtime/ is working fine, closing this
