### ISSUE TITLE
[Feature Request]: import assertions support another type 'raw' or 'text' or 'byte'

### ISSUE THREAD

**Issue by axetroy** [denoland/deno#13663]
```js
// import as string
import str from "./README.md" assert { type: "text" };
// import and cover to Uint8Array
import byte from "./README.md" assert { type: "byte" };
```

To avoid conflicts with the standard, imported types can be prefixed with deno, eg `deno_text` / `deno_byte` and make it unstable

### Background:

There are some files that we would like to be able to inline into the code

they naturally support builders and compile

### Example

without import:

```js
new Worker(new URL("./worker_runner.js", import.meta.url).href, { type: "module" });
```

with import:

```js
import workerCode from "./worker_runner.js" assert { type: "text" };

const src = new Blob([workerCode]);
new Worker(URL.createObjectURL(src), { type: "module" });
```

**Comment by bartlomieju** [comment]
This proposal is in direct contradiction to what import assertions are supposed to do (assert the content type, not influence evaluation of the specifier) and thus Deno has no plans to support it. 

However your use case is very desirable and there is another proposal that @lucacasonato champions that was presented to solve this use case: https://github.com/tc39/proposal-import-reflection.
