### ISSUE TITLE
When using `--inspect` wait a little bit for inspector connection at program start

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#13664]
See https://github.com/denoland/vscode_deno/issues/557 and past issue #12417

> This is a extremely annoying issue as mostly beginners (me) will encounter this when running very simple scripts that run very fast. In practice once one gets a website running this isn't a issue anymore.

When debugging a small program it might execute and close before vscode connects. This leads to a poor user experience where vscode just keeps waiting to connect, but deno has already finished. There's no indication in the UI about what's going on and it's confusing.

To mitigate (not entirely prevent) this scenario, we could introduce a small delay at program start that delays for X milliseconds or until a connection is established. This delay should be long enough to eliminate this issue happening on most machines, but short enough that nobody would really notice it (especially people who are attaching a debugger after launching). We could perhaps even make this delay take into account the amount of time that's elapsed since deno started so it would likely only be hit for small programs.

**Comment by bartlomieju** [comment]
@dsherret do you need help with this issue?

**Comment by dsherret** [comment]
@bartlomieju I looked into this today tried implementing the suggestion about using a channel, but this isn't possible because then no code polls for new sessions. As a test, I tried doing just a spin loop polling for connections and it didn't work either because I think the breakpoints hadn't been set yet. Anyway, this looks like a bigger change than I expected and maybe we should do the other refactors you were going to do first.

**Comment by sant123** [comment]
Not stale?

**Comment by csvn** [comment]
I would be very interested in an option for this. It's annoying when breakpoints aren't hit because they're too "early". I also found it very confusing at first why the debugger did not stop on a small program.

**Comment by bartlomieju** [comment]
@dsherret with recent refactor of inspector it should now be possible to implement it. The question remain how long should we wait before starting to execute code? 100ms seems to short...

**Comment by JustinGrote** [comment]
Is there a way to potentially have a `--inspect-wait` or some other option that will hold execution until a debugger connects? This is different than `--inspect-brk` in that it wouldn't break immediately and I wouldn't have to step the first break every time. This behavior is basically how all other debuggers (node, dotnet, etc.) tend to work, is there a limitation that would prevent this functionality?

**Comment by dsherret** [comment]
We'd prefer to do `--inspect-wait` as you mentioned earlier https://github.com/denoland/vscode_deno/issues/755#issuecomment-1343753605

I'm going to close this issue.

**Comment by JustinGrote** [comment]
@dsherret thanks, for some reason I thought that other issue was actually in a different repo, glad we are of like minds. Thanks!
