### ISSUE TITLE
Deno Structured Clone Algorithm cannot clone Blob and File

### ISSUE THREAD

**Issue by aaronhuggins** [denoland/deno#13666]
**Environment:**

  - Zorin OS 16 (Ubuntu GNU/Linux variant) 64-bit
  - Deno 1.18.2
  - VSCode 1.63.2

**Steps to reproduce:**

```typescript
const blob_original = new Blob()
console.log('blob_original instanceof Blob', blob_original instanceof Blob)
const blob_copy = structuredClone(blob_original)
// Expcted 'blob_copy instanceof Blob true'
console.log('blob_copy instanceof Blob', blob_copy instanceof Blob)

const file_original = new File([new Uint8Array([1, 2, 3])], 'name.fake')
console.log('file_original instanceof File', file_original instanceof File)
const file_copy = structuredClone(file_original)
// Expcted 'file_copy instanceof File true'
console.log('file_copy instanceof File', file_copy instanceof File)
```

Appears to be problem with internals, as the `structuredClone` implementation is not catching before it hits the internals. Problem is also reproducible with a naive clone using the internals:
```typescript
function clone (obj: any): any {
  // @ts-ignore: using Deno internals
  return Deno.core.deserialize(Deno.core.serialize(obj))
}
```

**Comment by andreubotella** [comment]
Duplicate of #12067.

**Comment by aaronhuggins** [comment]
I would expect to be able to clone any referenced type from MDN that also exists in Deno.

https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm

**Comment by aaronhuggins** [comment]
Closing in favor of #12067
