### ISSUE TITLE
Deno.dlopen not inferring symbols when providing second argument from a const/let

### ISSUE THREAD

**Issue by sant123** [denoland/deno#13678]
When proving the second argument inline the autocomplete works as expected:

<img width="452" alt="image" src="https://user-images.githubusercontent.com/7959437/154184640-33323ced-a8a3-4db4-9822-cf7669c362aa.png">

But if the argument is provided from a const/let no longer works:

<img width="562" alt="image" src="https://user-images.githubusercontent.com/7959437/154184938-25e240cc-1158-4c4f-9fc1-30983fa0e60a.png">

**Comment by sant123** [comment]
For Deno v1.23.0 this still happens 😕

**Comment by sant123** [comment]
For Deno v1.24.0 this still happens 😕

**Comment by 0f-0b** [comment]
`as Deno.ForeignFunctionInterface` erases all type information about the symbols. You might want `as const` instead, which [preserves the type of the whole object](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#literal-inference:~:text=You%20can%20use%20as%20const%20to%20convert%20the%20entire%20object%20to%20be%20type%20literals%3A).

```ts
const symbols = {
  method_2: {
    parameters: [],
    result: "f32",
  },
} as const;

const lib1 = Deno.dlopen("", symbols);

lib1.symbols.method_2; // correctly inferred as () => number
```

**Comment by sant123** [comment]
It works! 

![image](https://user-images.githubusercontent.com/7959437/180492583-95fa1ad3-b7a8-471e-9d05-6faac9f0d505.png)

Thanks @0f-0b !!!
