### ISSUE TITLE
[Tests] Disable Sanitization Globally

### ISSUE THREAD

**Issue by Skillz4Killz** [denoland/deno#13672]
It is quite painful to have to disable sanitization in hundreds of tests one by one. If possible, something like
```ts
Deno.testSanitizationDefaults = {
  sanitizeOps: false,
  ...
}
```

Then all Deno.test() can use those default options

Thank You

**Comment by lucsoft** [comment]
i mean there is a reason to have sanitization and it should be only disabled if really required

**Comment by Skillz4Killz** [comment]
Not stale
