### ISSUE TITLE
Web Crypto AES-GCM 256 with 16 byte IV throws Initialization vector length not supported

### ISSUE THREAD

**Issue by DjDeveloperr** [denoland/deno#13689]
Using 16 byte IV fails with AES-256-GCM.

It throws:

```
NotSupportedError: Initialization vector length not supported
```

Reproduction:

```js
const key = await crypto.subtle.generateKey(
  {
    name: "AES-GCM",
    length: 256,
  },
  false,
  ["encrypt", "decrypt"],
);

const iv = crypto.getRandomValues(new Uint8Array(16));

const msg = "Hello World!";

const encrypted = await crypto.subtle.encrypt(
  {
    name: "AES-GCM",
    iv,
    additionalData: new Uint8Array(),
  },
  key,
  new TextEncoder().encode(msg),
);

const decrypted = await crypto.subtle.decrypt(
  {
    name: "AES-GCM",
    iv,
    additionalData: new Uint8Array(),
  },
  key,
  encrypted,
);

console.log(new TextDecoder().decode(decrypted));
```

The same code works fine in browser (Edge).

But if you change IV to this

```js
const iv = crypto.getRandomValues(new Uint8Array(12));
```

It will work in Deno as well.

**Another bug** I noticed is `additionalData` is marked optional in typings but an error is thrown at runtime if we don't specify it:
```
TypeError: Error parsing args: missing field `additionalData`
```
However, not specifying it in browser just works as well.

deno v1.18.2

**Comment by littledivy** [comment]
funny, I thought we already had an issue for this. Thanks for opening this!
Unfortunately, we need RustCrypto crates to support variable nonce size at runtime. Also, see https://github.com/denoland/deno/issues/13201
> TypeError: Error parsing args: missing field `additionalData`

Already fixed in canary, It will be part of 1.19.0.

**Comment by littledivy** [comment]
See https://github.com/RustCrypto/AEADs/issues/389

**Comment by KaKi87** [comment]
In which stable Deno version will this feature be released ? Thanks
