### ISSUE TITLE
vendor: handle module specifiers with different text in the same module that resolve to the same module

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#13693]
Requires: https://github.com/denoland/deno_graph/issues/132

This is a known bug with the initial implementation, but should be rare in practice for people to hit.

Example:

```ts
export { foo } from "https://example.com/mod";
export type { foo } from "https://example.com/redirect_to_mod";
```

The above code would only create an import map entry for the last specifier.

**Comment by lucacasonato** [comment]
`deno vendor` has been removed.
