### ISSUE TITLE
`deno vendor` does not work with existing import map with bare specifier mapping

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#13697]
```
~/p/g/d/d/test ❯❯❯ cat import_map.json
{
  "imports": {
    "std/": "https://deno.land/std@0.125.0/"
  }
}
~/p/g/d/d/test ❯❯❯ cat main.ts 
import "std/examples/welcome.ts";
~/p/g/d/d/test ❯❯❯ deno vendor --import-map import_map.json main.ts -f
Vendored 1 module into vendor/ directory.

To use vendored modules, specify the `--import-map` flag when invoking deno subcommands:
  deno run -A --import-map vendor/import_map.json main.ts
~/p/g/d/d/test ❯❯❯ deno run -A --import-map vendor/import_map.json main.ts
error: Relative import path "std/examples/welcome.ts" not prefixed with / or ./ or ../ and not in import map from "file:///mnt/starship/Projects/github.com/denoland/dotcom/test/main.ts"
    at file:///mnt/starship/Projects/github.com/denoland/dotcom/test/main.ts:1:8
```

**Comment by dsherret** [comment]
I added this later to the PR description:

> The specified import map is not combined with the generated import map. It might be hard to do this correctly because the base of the import map changes when going into the vendor folder. Right now it's not a big deal for people to manually update the created import map after.

https://github.com/denoland/deno/pull/13670

The recommended thing to do atm is update the new import map manually.

**Comment by lucacasonato** [comment]
I think we should try I think. Manually combining every time you run `deno vendor` doesn't sound like much fun.

**Comment by jimisaacs** [comment]
I ended up writing this for now:
https://github.com/jimisaacs/source_vendor_import_map_fix_up
