### ISSUE TITLE
Completions for 'deno test' print errors in zsh

### ISSUE THREAD

**Issue by rherrmann** [denoland/deno#13702]
I'm using Oh-My-Zsh and installed Deno with Hombrew. It puts completions in `/usr/local/share/zsh/site-functions`.

While completions work fine in general, typing `deno test <TAB>` prints this:
```
_arguments:comparguments:325: doubled rest argument definition: *::script_arg -- Script arg:
_arguments:comparguments:325: doubled rest argument definition: *::script_arg -- Script arg:
_arguments:comparguments:325: doubled rest argument definition: *::script_arg -- Script arg:
```

Observed with version 1.18.2 and 1.19.

**Comment by crowlKats** [comment]
Ref https://github.com/clap-rs/clap/issues/3022

**Comment by jsejcksn** [comment]
> This happens in vanilla zsh. Using Oh My Zsh is irrelevant.

@rherrmann This is accurate. The issue title can be changed to reflect the larger scope: `zsh` in general.

**Comment by jespertheend** [comment]
Seems like a workaround for now is to manually remove the `*::script_arg` part in your completions file.

```diff
'--quiet[Suppress diagnostic output]' \
'*::files -- List of file names to run:_files' \
- '*::script_arg -- Script arg:_files' \
```

You can also change it to how it was in 1.17.3 and simply remove the asterisks before `*::files` and `*::script_arg`.

**Comment by sant123** [comment]
I'm currently using Oh My Zsh in Deno v1.22.0 and it prints the errors:

![image](https://user-images.githubusercontent.com/7959437/170115430-ad145004-1fc0-4283-a5e5-34097cd5dec6.png)

**Comment by tohsaka888** [comment]
same error occured in arch linux, any solution?

**Comment by crowlKats** [comment]
@tohsaka888 what Deno version are you on?

**Comment by tohsaka888** [comment]
@crowlKats 
![image](https://user-images.githubusercontent.com/58759688/211460665-a1b3080d-73e2-4440-99ec-bd18db11320c.png)

**Comment by sant123** [comment]
I'm having the same issue.

deno 1.29.2 (release, x86_64-unknown-linux-gnu)
v8 10.9.194.5
typescript 4.9.4
fedora 36

**Comment by zuisong** [comment]
> Seems like a workaround for now is to manually remove the `*::script_arg` part in your completions file.
> 
> ```diff
> '--quiet[Suppress diagnostic output]' \
> '*::files -- List of file names to run:_files' \
> - '*::script_arg -- Script arg:_files' \
> ```
> 
> You can also change it to how it was in 1.17.3 and simply remove the asterisks before `*::files` and `*::script_arg`.

It works for me , tks

deno 1.29.2 (release, aarch64-apple-darwin)
v8 10.9.194.5
typescript 4.9.4

**Comment by crowlKats** [comment]
Closing as this seems to be fixed

**Comment by vicary** [comment]
> This happens in vanilla zsh. Using Oh My Zsh is irrelevant.

This is somewhat related to Oh My Zsh for a possible cached completion file at `~/.oh-my-zsh/cache/completions/_deno`, which should be deleted before the behaviour is restored to the current version of deno.
