### ISSUE TITLE
Question: any alternatives for the deprecated createHash?

### ISSUE THREAD

**Issue by Meno-101** [denoland/deno#13709]
I've been experimenting with deno for sometime, I hebben to notice some deprecated modules, as I came across `createHash` for my needs as it's marked deprecated, I have tried to mimic my own with `sha1` module.

It worked perfectly, just the speed of it (compared to running the bash one with `Deno.run`) wasn't very intriguing, are there any near future plans upon improvement?

Other questions:
Stupid question, Are there any other un-documented alternatives yet?
Normal question, where can I find the timeline of "un-implemented/to improve" deno features if exists?

Nevermind it was the file read.

**Comment by Soremwar** [comment]
In order to avoid the deprecation notice, see https://deno.land/std@0.126.0/crypto
