### ISSUE TITLE
deno compile 1.19.0 produces bad executables

### ISSUE THREAD

**Issue by aricart** [denoland/deno#13711]
```
deno compile -A --unstable main.ts -o ngs-signer -L debug
Check file:///Users/synadia/Dropbox/code/src/github.com/aricart/nas-nats/ngs-signer/main.ts
Compile file:///Users/synadia/Dropbox/code/src/github.com/aricart/nas-nats/ngs-signer/main.ts
Emit ngs-signer
synadia@malaga ~/D/c/s/g/a/n/ngs-signer (main)> ./ngs-signer -c ngs-signer.conf 
error: Module not found
```

Running with `-L debug` doesn't produce any useful messages.

Verified that executables fail both in OS X, and x86_64-unknown-linux-gnu.

If the above error is a true error (perhaps changes in the bundling in 1.19.0, a path/url to the missing module would be great) - all previous versions have been stable.

**Comment by littledivy** [comment]
Duplicate of https://github.com/denoland/deno/issues/13704?

**Comment by embedvr** [comment]
Getting the same issue using 1.20.1 on Arch Linux.

```
❯ deno --version
deno 1.20.1 (release, x86_64-unknown-linux-gnu)
v8 10.0.139.6
typescript 4.6.2
```

and compiling gives me the same result.
```
❯ deno compile --unstable -A -o kittylang main.ts
Check file:///home/embed/dev/deno/kittylang/src/main.ts
Compile file:///home/embed/dev/deno/kittylang/src/main.ts
Emit kittylang
❯ ./kittylang test.kl
error: Module not found
```
seems at least for my its not adding other included files into the executable? or its just broken?

**Comment by vladfaust** [comment]
Still actual in 1.20.3. Please add some debug information to the output, because `error: Module not found` is not helpful at all.

**Comment by vladfaust** [comment]
Bump!

**Comment by vladfaust** [comment]
☹️

**Comment by crowlKats** [comment]
I am not able to reproduce this at all; @aricart would you be able to provide your main.ts?

**Comment by crowlKats** [comment]
ok; will close this then.
