### ISSUE TITLE
lsp: redirect diagnostic unexpectedly shown for nest.land modules

### ISSUE THREAD

**Issue by magurotuna** [denoland/deno#13718]
Ref: https://github.com/denoland/deno_lint/issues/1017

https://github.com/denoland/deno/pull/13580 added a new diagnostic that warns us when a module specifier is redirected to another specifier. This really works fine for most cases, but unfortunately modules published from nest.land are supposed to have redirection, therefore getting the redirect diagnostic can be annoying in this case.

**Comment by crowlKats** [comment]
This is also problematic for crux.land, as various redirects are done there as well
