### ISSUE TITLE
Slow fs performance.

### ISSUE THREAD

**Issue by Meno-101** [denoland/deno#13720]
I've already asked this on [stackoverflow](https://stackoverflow.com/questions/71175337/deno-slow-fs-performance). This is the last I've gotten to; please let me know if there is any way I could improve the processing speed.

The code is basically about reading a file. Then making a checksum, the checksum isn't a problem, but the slow speed of the read is bugging me.

I've noticed a very noticeably slow performance in reading files in deno. I'm afraid I might be doing it wrong. (rather stupid?)

```
const file = Deno.readFileSync(path)
```

any suggestions? or other faster ways?
should I use `Deno.run` instead? what are the pros and cons of `Deno.run` in your experience?

**Update 1:**

I found [this module](https://deno.land/manual@v1.19.0/examples/unix_cat) using streams in which it give some more speed, but compared to bash it's very slow:
```
$ time deno run --allow-read https://deno.land/std@0.126.0/examples/cat.ts movie.mp4 |  wc -l
4066379

real    0m1.890s
user    0m1.608s
sys     0m1.355s

$ time cat movie.mp4 | wc -l
4066379

real    0m0.295s
user    0m0.098s
sys     0m0.372s

$ du -sh movie.mp4 
995M    movie.mp4
```

**Update 2:**

Due to the worries of the network speed and Deno launch speed, I made this script where it has them both running respectively:
```js
import {
  copy,
  writeAllSync,
} from "https://deno.land/std@0.126.0/streams/conversion.ts";

const filenames = "movie.mp4";

//########## DENO ############

const before1 = performance.now();

const file = await Deno.open(filenames);
await copy(file, Deno.stdout);
file.close();

const after1 = performance.now() - before1;

const text1 = new TextEncoder().encode(after1.toString() + "\n");
writeAllSync(Deno.stderr, text1);

//########## CMD ############

const before2 = performance.now();

const p = Deno.run({
  cmd: ["cat", `${filenames}`],
});

await p.status()

const after2 = performance.now() - before2;

const text2 = new TextEncoder().encode(after2.toString() + "\n");
writeAllSync(Deno.stderr, text2);
```

Results in best case:
```
$ deno run --allow-run --allow-read test.ts >/dev/null
636
82
```

**Comment by bartlomieju** [comment]
This is is most likely the same problem as https://github.com/denoland/deno/issues/10157

**Comment by Meno-101** [comment]
well it seem a well known issue, I'll keep an eye for it, thanks for your help @bartlomieju

**Comment by bartlomieju** [comment]
I'm going to close this issue then, let's continue on #10157
