### ISSUE TITLE
systemMemoryInfo doesn't work completely cross platform

### ISSUE THREAD

**Issue by lucsoft** [denoland/deno#13724]
sysmem doesn't show buffer cached and on window available infos.

macOS:
![image](https://user-images.githubusercontent.com/11093382/154812561-bd009005-aa8c-466d-801c-04e8dbfc9383.png)
Linux:
![image](https://user-images.githubusercontent.com/11093382/154812588-673ac4f4-6dea-4d72-a6f5-86ffe864a303.png)
Windows:
![image](https://user-images.githubusercontent.com/11093382/154812597-86961142-522d-4cb1-951b-c5302a9ba14e.png)

Discord: https://discord.com/channels/684898665143206084/684898665151594506/944592062643322880

**Comment by crowlKats** [comment]
as per [docs of the crate](https://docs.rs/sys-info/latest/sys_info/fn.mem_info.html) we use:
> On Mac OS X and Windows, the buffers and cached variables of the MemInfo returned are zero.

**Comment by lucsoft** [comment]
BTW we could switch the package to sysinfo from sys-info

I don't think sys-info is really actively maintained anymore
