### ISSUE TITLE
Failure in test asyncOpsSanitizer when no hint is available for op

### ISSUE THREAD

**Issue by KyleJune** [denoland/deno#13729]
I don't have a clear reproduction path for this issue but I dug into the 40_testing.js code and I believe I found the cause of the issue. A user of my test_suite module opened [an issue](https://github.com/udibo/test_suite/issues/16#issuecomment-1046193210) saying they were getting an error when upgrading to the newest version that uses the test step API.  The user reported they are using Deno 1.19. Looking at the error message, it appeared to actually be an issue with Deno's test runner.

The Deno.metrics().ops object has 281 keys. The OP_DETAILS object in [40_testing.js](https://github.com/denoland/deno/blob/v1.19.0/runtime/js/40_testing.js#L64) only has 67 of those keys.

In the asyncOpSanitizer, if there is a difference in ops dispatched and completed, it will try getting hint information from the OP_DETAILS [here](https://github.com/denoland/deno/blob/v1.19.0/runtime/js/40_testing.js#L176) using destructuring assignment (shown below). If there isn't a hint in OP_DETAILS for the key, then the value returned from `OP_DETAILS[key]` is going to return undefined and you can't destructure undefined.

```js
const [name, hint] = OP_DETAILS[key];
```

If the key happens to be one that is undefined, this will throw the following error.

```js
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
        at asyncOpSanitizer (deno:runtime/js/40_testing.js:176:32)
```

**Comment by okcoker** [comment]
This might be related (or the exact issue reported by OP) but in order to debug I've been using the following function to log before and after certain calls when I can't figure out where the open op is coming from:

```js
function getOpenOps() {
    const metrics = Deno.metrics();

    return {
        ...metrics,
        ops: Object.keys(metrics.ops).reduce((acc: any, key: string) => {
            const op = metrics.ops[key];

            if (!op) {
                console.log('Missing op for key', key);
            }

            if (op && op.opsCompleted !== op.opsDispatched) {
                acc[key] = op;
            }
            return acc;
        }, {}),
    };
}
```

I noticed I had to check using `!op` because certain keys didn't have metrics associated with them. In my case I noticed these logs:
```
Missing op for key op_emit
Missing op for key op_pledge_test_permissions
Missing op for key op_restore_test_permissions
Missing op for key op_get_test_origin
Missing op for key op_dispatch_test_event
```

**Comment by lucacasonato** [comment]
Whoops, I know the root cause for this. My bad. I'll fix it soon.

**Comment by authcompanion** [comment]
May we have an update, ty vm!

**Comment by KyleJune** [comment]
> May we have an update, ty vm!

Discord shows Luca is out of office until March 3rd. I'm guessing it won't be fixed until after that. I'd recommend just downgrading to Deno 1.18 until this is fixed.
