### ISSUE TITLE
Deno.env.get("HOME") is different from $HOME  in MinGW-w64

### ISSUE THREAD

**Issue by txthinking** [denoland/deno#13733]
https://github.com/txthinking/nami/issues/13

**Comment by dsherret** [comment]
@txthinking could you include some details in this issue?

It looks like in that issue they are using bash to run the install script and so it seems that `$HOME` is actually different in bash than in the MinGW-w64 terminal.

**Comment by dsherret** [comment]
Pretty sure this isn't a deno issue and just the environment variable being set in a sub shell (bash) which wouldn't update the parent shell process (MinGW-w64 shell... whatever it is). Going to close it.
