### ISSUE TITLE
need to timeout in Deno.connect

### ISSUE THREAD

**Issue by pesarism** [denoland/deno#13736]
i tryin to build a port scanner with Deno
Deno.connect() need timeout for close tcp connection
i want when create connection after few seconds If did not get an answer do abort

like a nodejs:
```javascript
const { Socket } = require("net");
const socket = new Socket();
socket.on("timeout", () => {
    socket.destroy();
});
socket.setTimeout(200);
socket.connect(80, '8.8.8.8');
```
thanks

**Comment by kitsonk** [comment]
Duplicate of #10181 and #13688
