### ISSUE TITLE
`deno compile` ignores ` --import-map` in 1.19.0

### ISSUE THREAD

**Issue by nnmrts** [denoland/deno#13748]
Using 1.18.2 I can run this:

```
deno compile -A --no-check --unstable --import-map ./modules.json --output test test.js
```

and it works.

In 1.19.0 the same thing doesn't work. Well, the compilation works, but running the executable will throw an error like this one, which is familiar to anyone who forgot using the `--import-map` flag once:

```
error: Relative import path "std/path" not prefixed with / or ./ or ../ from "file:///path/to/test.js"
```

This might be related to https://github.com/denoland/deno/pull/13563. Seems like import map support was forgotten in the change. Also, `deno bundle` seems unaffected by this, but it's obviously not the same feature.

**Comment by nnmrts** [comment]
@littledivy @kitsonk It seems like using `--unstable` while compiling is also ignored, but I'm not entirely sure...I will have time later tonight to check that out, but just wanted to point it out before I forget it.

**Comment by vladfaust** [comment]
The issue is still actual in 1.20.4 on Windows (https://github.com/onyxlang/onyx/actions/runs/2081586932). 

It says `error: Module not found "file:///D:/builtin/int.nx".` for line `import BuiltinInt from "/builtin/int.nx";`, regardless of its being compiled with:

```
Temporary import map: {"imports":{"/builtin.nx":"file://C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\7f8a64b3\\builtin.nx.ts","/builtin/bool.nx":"file://C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\7f8a64b3\\builtin\\bool.nx.ts","/builtin/int.nx":"file://C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\7f8a64b3\\builtin\\int.nx.ts"}}

deno compile -A --output bin/onyx --import-map C:\Users\RUNNER~1\AppData\Local\Temp\88977c6e src/main.ts
```

The same code compiles on Ubuntu (https://github.com/onyxlang/onyx/runs/5798737961).

**Comment by nnmrts** [comment]
@vladfaust That's technically a different bug, I think. Am on the phone rn and don't have time to find it, but there's an open issue somewhere here where people found out it has something to do with imports not resolving correctly when using an import map or `deno vendor`.
