### ISSUE TITLE
deno bundleForNode {filename.js/ts} -- --output o.js command

### ISSUE THREAD

**Issue by elycheikhsmail** [denoland/deno#13753]
## suggestion

I suggess to add the following  command :

```
deno bundleForNode {filename.js/ts} -- --output o.js

```
like deno bundle {filename.js/ts} -- --output o.js
but with differance
- filename.js/ts can access any node api
- node can run o.js without problem
- deno run --compet o.js may failed if the some node api not supported by --compat are used

## use case

- allow develop to use deno ecosystem for develop frontend using framwork like svelte, vue ... with little effort

**Comment by ry** [comment]
Check out https://github.com/denoland/dnt
