### ISSUE TITLE
Value null is displayed as undefined in repl

### ISSUE THREAD

**Issue by TPReal** [denoland/deno#13757]
The Deno repl treats null as undefined in the loop output:
```
$ deno --version
deno 1.19.0 (release, x86_64-unknown-linux-gnu)
v8 9.9.115.7
typescript 4.5.2

$ deno repl
> null
undefined
> const a=null
undefined
> a
undefined
> a===undefined
false
> String(a)
"null"
```

**Comment by nnmrts** [comment]
Interesting! Here is a comparison from chrome's console, just for reference.

<img width="235" alt="Bildschirmfoto 2022-02-24 um 15 10 00" src="https://user-images.githubusercontent.com/20396367/155539724-5955c76d-564b-47ee-88aa-e9ea6198c560.png">

**Comment by TPReal** [comment]
Interestingly the last value `_` is also set incorrectly to `undefined`:
```
> 5
5
> String(_)
"5"
> null
undefined
> String(_)
"undefined"
```
