### ISSUE TITLE
CLI Not Resolving Import Map from Config File

### ISSUE THREAD

**Issue by harrysolovay** [denoland/deno#13776]
I see PR #13739 was merged just 3 days ago. I gave it a whirl and tried specifying an import map in my `deno.jsonc`. I ran my code with `-c deno.jsonc` (and no `--import-map`). It did not resolve my import map.

I hope this is helpful!

Also, I simply love what your team is building. Game-changer.

**Comment by bartlomieju** [comment]
This PR was merged, but since it's a feature it will be released in Deno 1.20 on March, 16th.

**Comment by harrysolovay** [comment]
Gotcha–thank you @bartlomieju!
