### ISSUE TITLE
Octal literals and decimals with leading zeroes wrongly allowed in REPL

### ISSUE THREAD

**Issue by jhmaster2000** [denoland/deno#13775]
When first trying out Deno's REPL my first thought was to check if it was properly running on strict mode, my go-to test for this is as simple as: `077`, an octal literal of decimal value `63`.

The test is simple, if the REPL returns `63`, it's not on strict mode, if it throws a strict mode SyntaxError, it's on strict mode.

Disappointingly, Deno REPL returned me `63`:
![SmartSelect_20220225-052234_Termux](https://user-images.githubusercontent.com/32803471/155680706-55bf6a26-2100-40e7-817a-8243911cd21c.jpg)
As a double check, in the image above I also attempted a decimal with leading zeroes: `099`, which should also throw a strict mode SyntaxError, you can see Deno REPL yet again disappoints.

The [expected results](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Deprecated_octal) seen in Node for comparison:
![SmartSelect_20220225-052901_Termux](https://user-images.githubusercontent.com/32803471/155681608-8f3d0659-1b7e-4d3b-9760-5664854891e6.jpg)

After these disappointing results, I went looking for information on how to enable strict mode on Deno's REPL, similar to Node's `--use_strict` REPL flag. To my surprise what I found was several references here on the GitHub issues claiming Deno REPL *is* strict mode by default, and found no such flag, so my guess is, Deno either incorrectly implements strict mode (bug) or it doesn't run in strict mode by default anymore and the info I found is outdated or was never right, since I could not find said info in any official capacity, as https://dotland-fresh.deno.dev/manual@v1.19.1/tools/repl doesn't mention anything regarding this for instance, which seems like a flaw of incomplete documentation that should also be made clearer.

**Comment by dsherret** [comment]
It's in strict mode, but that code is transpiled by swc first for TypeScript support and swc is emitting the value of the literal rather than the text.

I opened https://github.com/swc-project/swc/issues/3739

**Comment by dsherret** [comment]
Just need deno_ast 0.12.1 https://github.com/denoland/deno_ast/pull/67

**Comment by bartlomieju** [comment]
@dsherret should this issue be closed?

**Comment by dsherret** [comment]
Yup. Will be fixed in the next patch.
