### ISSUE TITLE
compat: cjs to esm translation is not applied when a commonjs module is dynamically imported with `file://` scheme

### ISSUE THREAD

**Issue by kt3k** [denoland/deno#13790]
`mocha` formats the importing specifier to `file://`-scheme url before calling `import()` ref: https://github.com/mochajs/mocha/blob/547ffd73535088322579d3d2026432112eae3d4b/lib/nodejs/esm-utils.js#L7

If the file url is passed to `import()` and the module is a commonjs, then cjs->esm translation is not applied to that file in compat mode.

**Comment by bartlomieju** [comment]
@kt3k I'm gonna need some more data points for this one. I opened #13792 that does what you described and it works fine.
