### ISSUE TITLE
Dedup esm_resolver.rs, replace with node_resolver

### ISSUE THREAD

**Issue by ry** [denoland/deno#13793]
Functions like like this duplicate the functionality provided by [node_resolver](https://github.com/denoland/node_resolver). For example:
https://github.com/denoland/deno/blob/a41d399f5f728c73b652c3f5f5c2bf57d2054153/cli/compat/esm_resolver.rs#L79-L85

We want to move all node resolution logic to node_resolver.

**Comment by bartlomieju** [comment]
This issue is no longer relevant since --compat mode was removed.
