### ISSUE TITLE
watchFs runs twice per modify

### ISSUE THREAD

**Issue by n-smits** [denoland/deno#13795]
Given this source

```js
  // ...
  ref = Deno.watchFs('test-in');
  for await (event of ref) {
    console.log('runs');
    console.log(event);
  }
```

On saving a file, modify is logged twice

```
runs
{ kind: "modify", paths: [ "..." ], flag: null }
runs
{ kind: "modify", paths: [ "..." ], flag: null }
```
(I've omitted paths, they correctly point to the modified file)

I have checked VS Code "Insert Final Newline" and "Trim Final Newlines" are disabled.

Not sure what else might be affecting this or how to better check is the issue on my side.

**Comment by jrylan** [comment]
Try debouncing the events:

https://github.com/denoland/deno/issues/12874#issuecomment-981096398
