### ISSUE TITLE
[SUGGESTION] Add `--deploy` flag to `run` command

### ISSUE THREAD

**Issue by kyuzu** [denoland/deno#13800]
As the title says, I think adding a `--deploy` flag to the `deno run` command would help reducing Deno Deploy errors during production. When the flag is passed, the current Deno process will exit (or throw an error) when encountering APIs that are not available in Deno Deploy (e.g. `Deno.readFileSync`, `Deno.readTextFileSync`, and etc...)

**Comment by kyuzu** [comment]
Closing as there's no response

**Comment by crowlKats** [comment]
There are many issues; as such it can take time for us to look into something. Please be patient.
