### ISSUE TITLE
WHATWG Streams based `Deno.stdin` (and friends)

### ISSUE THREAD

**Issue by crowlKats** [denoland/deno#13817]
We are slowly moving to use web streams for various things in the Deno ns.
Ideally this is in some way backwards compatible, but in the future we'd likely want to remove the `rid` property & make `setRaw` a method, instead of having it be in the Deno ns directly and have the user pass the rid manually.

**Comment by bartlomieju** [comment]
Maybe we could do:
- `Deno.stdin.readable`
- `Deno.stdout.writeable`
- `Deno.stderr.writeable`
This would be similar to updates done to `Deno.run()` API.

**Comment by crowlKats** [comment]
@bartlomieju that is already the case

**Comment by crowlKats** [comment]
Oh completely forgot I opened this 😅

**Comment by crowlKats** [comment]
Well, since this is implemented, I am going to close this. Going to create a tangential issue for removal of rid
