### ISSUE TITLE
Cannot convert object to primitive value

### ISSUE THREAD

**Issue by zhmushan** [denoland/deno#1382]
```ts
const a = Object.create(null)
a.b = 'c'
const msg = '' + a
```
```
TypeError: Cannot convert object to primitive value
```
This error also exists in `Node`. Maybe it's expected.
But I think it should not throw an error in testing.
```ts
import { test, assertEqual } from 'https://deno.land/x/testing/testing.ts'
test(function nullObj() {
  const a = Object.create(null)
  a.b = 'c'
  assertEqual(a, a) // test ok
})
```

**Comment by kevinkassimo** [comment]
This is a JavaScript thing. `a` does not have `toString` defined and thus would throw an error when trying to convert to a string.

The error is caused by this string interpolation:
https://github.com/denoland/deno/blob/105a5193b5aa231f0169d1113792f5c80e7438de/js/testing/util.ts#L18-L21

**Comment by kitsonk** [comment]
Ideally we should create the `msg` only after the assertion fails and then guard implicit string coercion like that as well.  For example, symbols would also fail.
