### ISSUE TITLE
lsp: unable to autocomplete private variables

### ISSUE THREAD

**Issue by jespertheend** [denoland/deno#13820]
**Describe the bug**

**To Reproduce**

```js
class Foo {
	#myPrivate = "value";
	constructor() {
		// Place your caret here and press ctrl+space
		//    ||
		//    ||
		//    \/
		this.#m
	}
}
```

**Expected behavior**

`this.#myPrivate` shows up in the list of autocompletions

**Versions**

vscode: `1.64.2` deno: `1.19.1` extension: `3.10.1`

**Comment by kitsonk** [comment]
There is logic in vscode that sits external to what comes back from the language server that handles private fields appropriately when completing.  Ensuring we have the same logic in the lsp Rust code that matches what is in vscode is what needs to be done here.

**Comment by dsherret** [comment]
This one is a really bad experience. We should fix it soon.

**Comment by bartlomieju** [comment]
@dsherret agreed, I was looking into it yesterday, but I can't find the bit from vscode that Kit was mentioning above.

**Comment by kitsonk** [comment]
I believe it is somewhat related to this: https://github.com/microsoft/vscode/blob/a790196c1910c92e617603056cacb99817470f0f/extensions/typescript-language-features/src/languageFeatures/completions.ts#L370-L404

**Comment by bartlomieju** [comment]
Thanks for much @kitsonk, I was just debugging this and noticed that the completion list is actually returned from TSC and the relevant entry is present in the list, but it's not rendered by the editor. I'll follow up on that link you posted 🙏
