### ISSUE TITLE
file_server.ts uses ReadableStream

### ISSUE THREAD

**Issue by amundo** [denoland/deno#13823]
https://deno.land/std@0.127.0/http/file_server.ts#L341

Uses `ReadableStream`, but if I understand correctly that has been deprecated:

https://deno.com/blog/v1.16#improvements-to-web-streams-api

> `ReadableStream.getIterator` has been removed. This method has been deprecated since Deno 1.7, and was never implemented in any browser. The `ReadableStream` itself has always implemented the `AsyncIterable` protocol, so use that instead when iterating over a stream.

I get the following error when trying to compile `file_server.ts` under deno 1.19.1: 

```
tmp/$ deno --version
deno 1.19.1 (release, x86_64-apple-darwin)
v8 9.9.115.7
typescript 4.5.2
tmp/$ deno compile -A https://deno.land/std/http/file_server.ts
Check https://deno.land/std/http/file_server.ts
error: TS2339 [ERROR]: Property 'getIterator' does not exist on type 'ReadableStream<R>'.
  return res.readable.getIterator();
                      ~~~~~~~~~~~
    at https://deno.land/std@0.68.0/async/pool.ts:45:23
tmp/$ 
```

Thanks for deno! 🦕

**Comment by bartlomieju** [comment]
`deno compile -A https://deno.land/std/http/file_server.ts` <- you are using an unversioned URL and it appears you have a very old version of `deno_std` cached (`0.68.0`). 

I suggest to use tagged URL (`deno compile -A https://deno.land/std/http@0.127.0/file_server.ts`) and the problem will go away. Alternatively you can run with `--reload` flag to update the dependencies to latest version.
