### ISSUE TITLE
Improve `AggregateError` console output

### ISSUE THREAD

**Issue by jaydenseric** [denoland/deno#13831]
A standard [`AggregateError`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/AggregateError) instance has an `errors` property containing an array of the aggregated errors.

It would be really useful if Deno displayed these errors when printing an `AggregateError` instance in the console, much like how it displays the `cause` property.

For example, with `demo.mjs`:

```js
const aggregateError = new AggregateError([
  new Error("Error message 1."),
  new Error("Error message 2."),
], "Multiple errors.");

console.error(aggregateError);

throw aggregateError;
```

Run with Deno:

```
deno run demo.mjs
```

Currently results in:

```
AggregateError: Multiple errors.
    at file://[redacted]/demo.mjs:1:24
error: Uncaught AggregateError: Multiple errors.
const aggregateError = new AggregateError([
                       ^
    at file://[redacted]/demo.mjs:1:24
```

As you can see, it doesn't surface the messages of the aggregated errors.

**Comment by bartlomieju** [comment]
@crowlKats could you take a look?
