### ISSUE TITLE
lsp report that Node.childNodes is not iterable

### ISSUE THREAD

**Issue by jingkaimori** [denoland/deno#13834]
Deno lsp treats `Node.childNodes`(instance of `NodeList`) as an array-like object without iterator, and emits error that childNodes is not iterable. But according to [MDN's document of NodeList](https://developer.mozilla.org/en-US/docs/Web/API/NodeList), NodeList is iterable.

Code below emit `deno-ts(2488)`
```ts
declare let tree:Node
for(const i of tree.childNodes){
    //something
}
```

**Comment by kitsonk** [comment]
@jingkaimori out of the box, Deno does not define `Node`.  Are you using a `tsconfig.json` or a `deno.jsonc` to change the compiler options, and if so, you likely have something like `"lib": ["dom", "esnext"]` and you should have `"lib": ["dom", "dom.iterable", "esnext"]` if you want iterators to be defined in the types.

**Comment by jingkaimori** [comment]
thanks @kitsonk , that solves problem.
