### ISSUE TITLE
Question: Have plan to support the CONNECT tunnel of HTTP server?

### ISSUE THREAD

**Issue by biluohc** [denoland/deno#13843]
Mayble add `Deno.upgrade` and `Deno.HttpUpgradeConn` like `WebSocket`

**Comment by crowlKats** [comment]
Not exactly sure what you are asking for. Can you explain a bit more what you are asking for?

**Comment by biluohc** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/CONNECT

**Comment by crowlKats** [comment]
still doesnt exactly explain what you want API wise, but i assume you want #12718

**Comment by biluohc** [comment]
Yes, but the WebSocket has been implemented.
