### ISSUE TITLE
Remove support for extensionless imports

### ISSUE THREAD

**Issue by ry** [denoland/deno#1384]
It's ugly and it's something I originally intended to avoid. Support was added because it was an easy way to keep modules cross-compatible with Node. However, the ugliness outweighs that goal.

https://github.com/denoland/deno_std/blob/34f21da7cf89c5a24558c68fc3f572e7300da618/net/http.ts#L2-L5

https://github.com/denoland/deno/tree/master/tools/ts_library_builder relies on this feature at the moment. so that has to be ported to another test framework first.

**Comment by kevinkassimo** [comment]
To drop support for extensionless imports, only these two places need to be modified:
https://github.com/denoland/deno/blob/105a5193b5aa231f0169d1113792f5c80e7438de/src/deno_dir.rs#L140-L146
https://github.com/denoland/deno/blob/105a5193b5aa231f0169d1113792f5c80e7438de/src/deno_dir.rs#L180-L186

**Comment by ry** [comment]
fixed in #1396
