### ISSUE TITLE
deno script.ts --prefetch

### ISSUE THREAD

**Issue by ry** [denoland/deno#1386]
Provide a way to download (cache) the dependencies of a script without executing it.

Deps are stored in DENO_DIR as normal.

**Comment by kevinkassimo** [comment]
How should this work with dynamic imports?

**Comment by ry** [comment]
It doesn't download dynamic imports.

**Comment by kitsonk** [comment]
Heavily related to getting `--deps` working again (#1011), ESM support (#975), and potentially splitting out the compiler (#1190).
