### ISSUE TITLE
Better testing for Amazon Linux on the CI

### ISSUE THREAD

**Issue by littledivy** [denoland/deno#13888]
Currently tests run in ubuntu 16 sysroot along with a simple "check":
https://github.com/denoland/deno/blob/main/.github/workflows/ci.yml#L418-L421

Ideally, unit tests should run in an actual environment to ensure GLIBC [issues](https://github.com/denoland/deno/issues/13516) don't happen again. A 1gig self-hosted ec2 runner would work.

**Comment by hayd** [comment]
Running basic tests in Docker should suffice. Something like (untested):

```
docker run --rm --name deno -v $(pwd)/target/release:/build --entrypoint='/build/deno eval "console.log(1+2)"' amazonlinux:2.0.20200722.0 | grep 3
```
? (or maybe it's cleaner in multiple steps.) docker should already be installed in gh-actions ubuntu.

**Comment by littledivy** [comment]
🧹 Closing because state and there is not much interest here
