### ISSUE TITLE
Feature Request: `ref`/`unref` methods for `Deno.Listener`

### ISSUE THREAD

**Issue by kt3k** [denoland/deno#13886]
`net.Server` class in Node.js API has `ref`/`unref` methods which controls `ref` status of tcp server (unref'd server allows the program to exit when the server is still running). https://nodejs.org/api/net.html#serverunref

We need to have similar methods in Deno.Listener to simulate the above Node.js feature in compat mode.

**Comment by kt3k** [comment]
@bartlomieju Sorry I missed you self-assigned this 😓

**Comment by ExProbitasFiducia** [comment]
Is this error related to this change?

```
            "/-/react@v17.0.1-POc2QItJkO3bjziOktDB/dist=es2019,mode=types/index.d.ts": "https://cdn/skypack.dev/-/react@v17.0.1-yH0aYV1FOvoIPeKBbHxg/dist=es2019,mode=types/index.d.ts"

```

**Comment by ExProbitasFiducia** [comment]
> Is this error related to this change?
> 
> ```
> 
> TS2339 [ERROR]: Property 'ref' does not exist on type 'Listener'.
>     this.#listener?.ref();
>                     ~~~
>     at https://deno.land/std@0.134.0/node/internal_binding/tcp_wrap.ts:240:21
> 
> TS2339 [ERROR]: Property 'unref' does not exist on type 'Listener'.
>     this.#listener?.unref();
>                     ~~~~~
>     at https://deno.land/std@0.134.0/node/internal_binding/tcp_wrap.ts:243:21
> ```

oh I just did `deno upgrade` and it's resolved.
