### ISSUE TITLE
deno mv

### ISSUE THREAD

**Issue by ry** [denoland/deno#1388]
A tool for moving a file from one directory to another, changing only the imports as necessary.

Example `deno mv index.js ..`

What if another file depends on index.js - should it's imports be changed too? Not for the first version.

This should also work on URLs:

`deno mv https://deno.land/x/examples/gist.ts .`

This should be implemented first in https://github.com/denoland/deno_std/

**Comment by kitsonk** [comment]
There are rename services that are part of the TypeScript language services: https://github.com/Microsoft/TypeScript/blob/master/src/services/rename.ts.  These should work to help ensure the renaming, or at least help.

**Comment by zerubeus** [comment]
@ry can I take this one ?

**Comment by ry** [comment]
@kitsonk That will be helpful for version 2. The first version I'd like it to only deal with the imports. (I'm assuming that is easier than doing proper IDE style renames - that assumption might not be true.)

**Comment by bartlomieju** [comment]
@ry do you still want to pursue it?

**Comment by ry** [comment]
no - this was a random one : )

**Comment by elevasyncsolutions-jpg** [comment]
@nayeemrmn @dsherret @bartlomieju Quick ping — this PR has CLA signed and all CI passing. Could one of you review when you get a chance? Thanks!

**Comment by dsherret** [comment]
Doesn't look like the CI is passing.
