### ISSUE TITLE
Discussion: cryptographic signatures

### ISSUE THREAD

**Issue by ry** [denoland/deno#1389]
We need a way of better ensuring that remote content is what the user expects it to be.

We already rely heavily on git infrastructure to reference code, and I think we can re-use git features here too.

Supposing we moved to signed commits for deno_std (and deno). Then given a URL like `https://deno.land/x@522d48/net/http.ts` we should be able to find the actual git repo, clone it, and get a list of signatures on that particular file.

The list of signatures should all sigs from the last change of the file until HEAD.

Maybe by adding `deno trust ry@tinyclouds.org $RY_PUBLIC_KEY` we allow people to run code that I have signed without seeing error messages. (Actually I would embed my keys / bert's into the executable so most programs will run without further configuration.)

Idea: have the following return the signature list `https://deno.land/x/std@master/net/http.ts?signature`

**Comment by KeKsBoTer** [comment]
I very much like the idea of signing code(commits)!
But do we have to download the entire repository for that? I think a better solution would be a [partial clone](https://github.com/git/git/blob/v2.19.0/Documentation/technical/partial-clone.txt).

I think it would make sense to only run fetched code that is signed unless the user deliberately tells deno to run unsigned code (with a flag?))

**Comment by ry** [comment]
We'll have to do it server side, clients shouldn't have to git clone.

**Comment by jamesseanwright** [comment]
Was there ever any movement on this? Code signing would be a hugely reassuring feature to have.

**Comment by kitsonk** [comment]
@ry any real further thoughts on this at the moment?  We have looked at immutable package hosts and we have lock files.  Is there something more to do here?
