### ISSUE TITLE
Make `fetch()` errors more helpful.

### ISSUE THREAD

**Issue by jespertheend** [denoland/deno#13897]
If you save the following to a file and run it:
```js
fn1();

function fn1() {
  fn2();
}

async function fn2() {
  const response = await fetch("file:///does/not/exist/");
  console.log(await response.text());
}
```
The following error is printed:
```
error: Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource.
    at async mainFetch (deno:ext/fetch/26_fetch.js:280:14)
```
apart from the stack trace only partially being shown (https://github.com/denoland/deno/issues/11859), I think it could be useful if the failing url was logged. Similar to what is shown in browsers:
![image](https://user-images.githubusercontent.com/2737650/157643852-369fd869-a195-4785-884b-bf63602ee165.png)

**Comment by nayeemrmn** [comment]
FYI this is reproduced with just `await fetch("file:///does/not/exist/")`, which is missing a proper stack trace.
