### ISSUE TITLE
Consider making the `Deno` namespace not read only.

### ISSUE THREAD

**Issue by jespertheend** [denoland/deno#13903]
I wanted to mock some Deno functions for unit tests, but I was surprised to see that `Deno = {}` or `globalThis.Deno = {}` results in:
```
Uncaught TypeError: Cannot assign to read only property 'Deno' of object '#<Window>'
    at <anonymous>:2:17
```
Since #11033 we are already able to modify the `Deno` object if we want to mock or polyfill things. So tbh, I'd be fine if the `Deno` object stayed read only. I was just a bit surprised since none of the other globals are read only. For instance:
```js
globalThis.WebSocket = {}
globalThis.Symbol = {}
globalThis = {}
```

**Comment by MierenManz** [comment]
Not stale

**Comment by jespertheend** [comment]
I think this might have been closed unintentionally

**Comment by lucacasonato** [comment]
It is not read-only anymore.
