### ISSUE TITLE
Debugging broken

### ISSUE THREAD

**Issue by martixy** [denoland/deno#13908]
Sorry for the vague title, not sure how to make it more specific.

I was following the tutorial - https://deno.land/manual@v1.19.3/getting_started/debugging_your_code  
...and none of what that page describes actually happens.

`deno v1.19.3`  
`Chrome v99`  
`Win 10 21H2`

What you get from the debugger is this:
![DenoDebug](https://user-images.githubusercontent.com/8262590/157863647-1270d682-8154-41f1-8869-9f5bbbd4587c.png)

And you can never step out of that file.
There is also no **Page** tab on the left, and you cannot browse to other source files. You're just kind of stuck at this small snippet.

**Comment by GJZwiers** [comment]
Not stale

**Comment by keenwon** [comment]
Same problem.

deno 1.15.2

**Comment by bartlomieju** [comment]
I can't repeat this problem anymore. I'm going to tentatively close this issue, please let me know if the problem persists.
