### ISSUE TITLE
lsp: support tasks

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#13910]
It would be useful for the lsp to support running tasks in from deno.json

cc @kitsonk

**Comment by kitsonk** [comment]
We should consider if we want the lsp to run the tasks, in the same process.  We do "caching" and will be doing it for the testing API, but it would require some custom APIs to run the tasks and deal with the output (like writing to stdout or reading from stdin would interfere with communication of the client/server).

Wouldn't it be better to add the feature to the clients directly.  Each client has a concept of tasks, and for example for vscode_deno, there is a task provider API which allows tasks to be expressed and made available in the editor.  The biggest thing would be the "auto discovery" of the config file.  We could either mirror the logic in the extension or we could have the lsp notify the client of the discovered config file if any.

Having that one custom notification is a lot better than a handful of requests/responses and notifications for managing it.

Following it this way, the extensions would be responsible for launching and managing the `deno task` as a subprocess.  The API in vscode is pretty rich.  It already has integrations to auto-discover npm scripts, and would be a good pattern for how to deal with Deno tasks.
