### ISSUE TITLE
Improve footer in `deno test`

### ISSUE THREAD

**Issue by lucsoft** [denoland/deno#13913]
The current footer is a bit noisy and not easy to identify

A improved footer could look something like this:
<img width="253" alt="image" src="https://user-images.githubusercontent.com/11093382/157891863-08ac8440-af4a-4178-b7bc-8e2392c407d4.png">

Compared to the current one:
<img width="350" alt="image" src="https://user-images.githubusercontent.com/11093382/157891882-db296d5e-05a3-475d-983a-48df48edb0d8.png">

Backstory to this issue:
[vitest on twitter](https://twitter.com/alexlafroscia/status/1501204689278443530)
[discord chat](https://canary.discord.com/channels/684898665143206084/684911491035430919/951840231383007302)

**Comment by nayeemrmn** [comment]
After playing around with the output more, I liked it better as less vertical space was taken up by the summary on an integrated terminal when scrolling up to see failures. It would be nice if we could reduce noise while keeping it to one line, maybe by omitting `ignored` and `filtered out` if they are 0 (what even is `measured`), considering a different delimiter than semicolon, etc.

![image](https://user-images.githubusercontent.com/29990554/166854505-6b94e11d-f230-47bc-b966-43c0d3b6fb9e.png)
->
![image](https://user-images.githubusercontent.com/29990554/166854550-549338d5-8930-466c-8f80-ead3b13a8461.png)

![image](https://user-images.githubusercontent.com/29990554/166854593-26d64ff2-eb99-4f2b-928a-003448b813bb.png)
->
![image](https://user-images.githubusercontent.com/29990554/166854631-505c3832-974d-40b7-86ce-61d17b185077.png)

**Comment by bartlomieju** [comment]
@nayeemrmn that looks good, I think this is better than vertical summary that I proposed in #14262

**Comment by mrkldshv** [comment]
Hey! Is this issue free to pick up? Or there were some work done by @nayeemrmn?

**Comment by nayeemrmn** [comment]
@mrkldshv It's free

**Comment by mrkldshv** [comment]
Right, I'd be happy to work on this issue.

**Comment by bartlomieju** [comment]
> Right, I'd be happy to work on this issue.

Please do!

**Comment by mrkldshv** [comment]
Do we want to keep horizontal summary, but make it easier to read?
