### ISSUE TITLE
Determine correct `moduleDetection` compiler option (TypeScript 4.7)

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#13924]
Ref: https://github.com/microsoft/TypeScript/pull/47495

The next minor release of TypeScript (4.7) should include a new `moduleDetection` option, which has to deal with how modules are detected by TypeScript when type checking.  The default is `"auto"`, which might be ok for us, but also there is `"force"` which is more the behaviour that we would expect for code running under Deno.  We need to do a bit of experiment and testing.

The issue mostly manifested itself around issues in the lsp when having a file open with no top level import or export statement being treated a global script for type checking purposes.  There were also some issues with emitting `@jsxImportSource` with modules that appeared to be scripts.

**Comment by kitsonk** [comment]
Ref #12631 and microsot/TypeScript#46723 which relate to the `@jsxImportSource` issue.

**Comment by nayeemrmn** [comment]
We definitely need `"force"` to finally fix #9593. The question is how that affects cts files run in `--compat`. We may need to continue running `"auto"` when `--compat` is used. Unfortunately that will expose #9593 for even the Deno-first segments of the module graph but it seems like a fine compromise.

**Comment by nayeemrmn** [comment]
> We may need to continue running `"auto"` when `--compat` is used.

Actually this makes perfect sense, the _execution_ semantics we have already align with using `"force"` without `--compat` and using `"auto"` with `--compat`. Those sources in the repro of `#9593` _are_ executed as scripts with `--compat` is used.

**Comment by nayeemrmn** [comment]
Thinking more,
- Without `--compat` we should invariably use `"moduleDetection": "force"`.
- With `--compat` we should use `"moduleDetection": "auto"` by default but allow it to be configured by a user tsconfig.

**Comment by nayeemrmn** [comment]
Disregard previous comments. We should just use `"moduleDetection": "force"` all the way, I misunderstood that modules refer to both esm and cjs, as opposed to old-fashioned browser scripts.
