### ISSUE TITLE
Add `deno check` subcommand

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#13920]
I couldn't find an issue for this. This sub command would only do type checking. I believe @kitsonk had most of this work done before. We could get this work done before 2.0.

I think this could just essentially be an alias for `deno cache` at the moment and in the future `deno cache` wouldn't type check.

**Comment by nayeemrmn** [comment]
#11786

**Comment by dsherret** [comment]
@nayeemrmn thank you!
