### ISSUE TITLE
ci: Rust 1.59.0-1.60.0 compiler error (ICE)

### ISSUE THREAD

**Issue by littledivy** [denoland/deno#13935]
https://github.com/denoland/deno/runs/5528879712?check_suite_focus=true#step:26:453
https://github.com/denoland/deno/runs/5519374644?check_suite_focus=true#step:26:121
https://github.com/denoland/deno/runs/5519410740?check_suite_focus=true#step:26:121
https://github.com/denoland/deno/runs/5477300819?check_suite_focus=true
https://github.com/denoland/deno/runs/5528912995?check_suite_focus=true#step:26:449

Looks like an issue with incremental compilation in `ext/` crates. Tweaking the cache key fixes it.

Related rustc issues:
https://github.com/rust-lang/rust/issues/93779
https://github.com/rust-lang/rust/issues/91704

**Comment by littledivy** [comment]
Still not fixed after updating rustc to 1.60.0 

https://github.com/denoland/deno/runs/6349212182?check_suite_focus=true

**Comment by crowlKats** [comment]
Closing as not the case anymore
