### ISSUE TITLE
Unclear error message when ouput path is a directory with `deno compile`

### ISSUE THREAD

**Issue by marc2332** [denoland/deno#13937]
Hey

Deno is unable to compile a local module using a relative path in Linux.

Linux: 
![imagen](https://user-images.githubusercontent.com/38158676/158074942-0c351b5b-eebf-4633-ae05-3b6fec03339b.png)

Expected (Windows):

![imagen](https://user-images.githubusercontent.com/38158676/158074971-aa418c61-b8de-47be-a139-2469da8ad79a.png)

I haven't tested on MacOS.

Both are using Deno `v1.19.3`

**Comment by sigmaSd** [comment]
In my testing it only fails if the file is named `main.ts` any other name works.

**Comment by marc2332** [comment]
> In my testing it only fails if the file is named `main.ts` any other name works.

![imagen](https://user-images.githubusercontent.com/38158676/158075515-95624d65-d47f-4da4-aad6-5ee09b297f7d.png)

Indeed, it seems to only affect certain file names, and with different errors.

**Comment by sigmaSd** [comment]
My guesses are :
- the error is due to https://github.com/denoland/deno/blob/main/cli/tools/installer.rs#L126
- when you name the file test, the error it produces is a different issue

**Comment by sigmaSd** [comment]
Hmm the behavior might be actually on purpose

it allows for something like:
```
mkdir hello
touch hello/main.ts
cd toSomOtherdirectory # example cd ..
deno compile originalDir/hello/main.ts
```
this gives you a binary named `hello` which might be actually a nice behavior

The original problem occurs because if you're on the same directory the binary name conflicts with the source name

**Comment by sigmaSd** [comment]
Does windows allows for files and directory with the same name to coexist?

**Comment by kitsonk** [comment]
As mentioned by @sigmaSd this is actually the desired behaviour.  When you compile a `/main.ts` it assumes the containing directory name for the name of the binary.

I am marking it as a bug though, as the error message is really poor.  It should be something, like:

```
Attempting to compile to an executable named `a`, which is a directory.  You can use the `--output` flag to provide an alternative name for the executable.
```
