### ISSUE TITLE
deno_core compiles fine for Android but crashes when trying to init runtime

### ISSUE THREAD

**Issue by rmst** [denoland/deno#13936]
Using `deno_core = "0.121.0"` the official [hello world example](https://github.com/denoland/deno/blob/main/core/examples/hello_world.rs) compiles fine for Android (arm64) but crashes on the following expression

```rust
let mut runtime = JsRuntime::new(RuntimeOptions {
    extensions: vec![ext],
    ..Default::default()
});
```

with

```
A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE)
```

Is there anything that could be done to make it work?

**Comment by littledivy** [comment]
Can you provide more logs from `logcat`? Also, are you cross-compiling it or directly on the device?

**Comment by littledivy** [comment]
<img src="https://user-images.githubusercontent.com/34997667/158134649-382cab5a-2d38-46ae-b7d3-6892ff9bf098.png" height=600> 

Seems to work as intended on my device. (The panic is expected since the JS files are missing from where I run it)

**Comment by rmst** [comment]
That error is all there is in logcat. I'm cross compiling via Mozilla's Rust Gradle plugin, i.e.

```gradle
plugins {
    // ...
    
    id "org.mozilla.rust-android-gradle.rust-android" version "0.9.0"  // Embed Rust
}
```

Otherwise standard Android boilerplate. You're using termux I assume which seems to be a very different story. Sorry for not clarifying that initially.

**Comment by elycheikhsmail** [comment]
> Oh, just figured it out: I was calling `runtime.execute_script` on the UI thread. Moving it into a separate thread resolved the issue

Is possible to use deno for capacitorjs pluging or to build something similar to capacitor and his pluging ?
