### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by mohsen1** [denoland/deno#14]
Building this on Mac was not very straightforward. I can work on a `Dockerfile` is that's inline with project goals 

This is being worked on here: https://github.com/ry/deno/pull/63

**Comment by ry** [comment]
Yes please!

**Comment by wbgbg** [comment]
The compile instructions works like a charm for me on Mac except the lack of pkg-config. After`brew install pkg-config` the compile success.

**Comment by hinell** [comment]
Yeah. Would like to try it on windows too.

**Comment by justjavab** [comment]
You should see the speech "Design Mistakes in Node" in the JS Conf. Berlin which is made by RY.

**Comment by beeman** [comment]
I made [a small playground with some examples](https://github.com/beeman/deno-examples) that allows you to run scripts with `deno` using Docker. 

It uses the [deno-docker](https://github.com/maxmcd/deno-docker) container created by @maxmcd.

**Comment by talcarl** [comment]
Yes please, that's good starting point for beginner like me who wants to get involved in the project.

**Comment by ry** [comment]
We decided not to use docker.

**Comment by mknet** [comment]
Hi @ry,  could explain in short why you decided to not use docker?

Thanks and regards
Marcel

**Comment by ry** [comment]
@mknet Yes, sorry for not doing it above. We want to support reproducible builds on major platforms: linux, windows, and mac. This necessitates a more sophisticated way of managing build dependencies than a Dockerfile - we use Chrome's build system gn for this. Although it wouldn't be much work to add a Dockerfile, it would be something we have to maintain in parallel to our normal build - which is unnecessary overhead at this stage. Our travis CI setup is relatively complicated, and would add Docker if it replaced that complication... but I don't think anyone has gotten it working in a way that satisfies our requirements. In particular, clean builds of Deno take on the order of 1 hour - we have a hard requirement on supporting fast incremental builds thru caching of some sort.

**Comment by mknet** [comment]
Thanks, @ry

**Comment by hayd** [comment]
I also have Docker files here https://github.com/hayd/deno-docker (hayd/deno).
