### ISSUE TITLE
Edge case: `bundle`'s output fails at runtime with a SyntaxError from `JSON.parse` if the original JSON includes backslash escapes.

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#14012]
Edge case: `bundle`'s output fails at runtime with a SyntaxError from `JSON.parse` if the original JSON includes backslash escapes.

Using the same `test.ts` as the original, but with `test.json` containing:

```
{"key":"a \"value\" with\nescapes"}
```

results in this console session:

```
$ deno --version
deno 1.20.1 (release, x86_64-pc-windows-msvc)
v8 10.0.139.6
typescript 4.6.2

$ deno run test.ts
{"key":"a \"value\" with\nescapes"}

$ deno bundle test.ts -- bundled.js && deno run bundled.js
Check file:///C:/.../test.ts
Bundle file:///C:/.../test.ts
Emit "bundled.js" (250B)
error: Uncaught SyntaxError: Unexpected token v in JSON at position 11
const __default = JSON.parse(`{"key":"a \"value\" with\nescapes"}
                       ^
    at JSON.parse (<anonymous>)
    at file:///C:/.../bundled.js:5:24
```

_Originally posted by @solarshado in https://github.com/denoland/deno/issues/13150#issuecomment-1070980012_

**Comment by kamilogorek** [comment]
Will be fixed once https://github.com/denoland/deno_emit/pull/84 is merged, released and `deno_emit` is updated in the CLI.
