### ISSUE TITLE
 Specifying `permissions: {}` seems to inherit all permissions

### ISSUE THREAD

**Issue by uki00a** [denoland/deno#14018]
**Summary:**

[Deno 1.20 Release Notes](https://deno.com/blog/v1.20#breaking-stricter-defaults-in-programatic-permissions-for-tests-and-workers) say that the deafult behavior of the `permissions` option has changed. However, it does not appear to have actually changed :thinking:

**Steps to reproduce:**

Suppose you have a file named `test.ts`:

```ts
Deno.test({
  name: "readTextFile",
  permissions: {},
  fn: async () => {
    await Deno.readTextFile("data.txt");
  },
});
```

Running this file with `--allow-read` causes the test to pass:

```shell
$ deno test --allow-read test.ts
running 1 test from file:///home/uki00a/ghq/github.com/uki00a/deno-sample/test.ts
test readTextFile ... ok (5ms)

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filte
red out (19ms)
```

**Expected behavior**: `test.ts` fails with a permission error

**Environment:**

```shell
$ deno --version
deno 1.20.1 (release, x86_64-unknown-linux-gnu)
v8 10.0.139.6
typescript 4.6.2
```

**Comment by lucacasonato** [comment]
@uki00a You are totally right, the old behaviour is still being used. It was landed without tests (very bad).
