### ISSUE TITLE
Deno 1.20 via Homebrew

### ISSUE THREAD

**Issue by harrysolovay** [denoland/deno#14021]
I see [the current version on brew.sh](https://formulae.brew.sh/formula/deno#default) is `1.19.3`. I would very much like to upgrade without uninstalling & re-installing via another package manager. Will 1.20 be accessible via Homebrew soon? Thanks!

**Comment by kitsonk** [comment]
deno on Homebrew is community maintained.  The PR is already open, but failing: https://github.com/Homebrew/homebrew-core/pull/97054.  Assisting in getting the PR to pass would likely be the quickest way to resolve the issue.
