### ISSUE TITLE
Limit time of context.execute_script?

### ISSUE THREAD

**Issue by gufoe** [denoland/deno#14031]
Hi, I'm considering to use `context.execute_script` this to run arbitrary (user) code on my servers.
I'd like to make sure the execution is not taking too much time though.
Is there any way I can achieve this? I can't find any way to achieve this.
Cheers, and thanks for the good work!

**Comment by bartlomieju** [comment]
There's no built-in functionality for this in `deno_core`, but this can be achieved by spawning a separate thread that acts as a "timeout watchdog". 

You can obtain a thread safe handle to the V8 isolate that allows you to terminate execution using:
```rust
let thread_safe_handle = js_runtime.v8_isolate().thread_safe_handle();
```

Then, if executing a script takes too much time, you can "kill" the isolate with:
```rust
thread_safe_handle.terminate_execution();
```

**Comment by gufoe** [comment]
Exaclty what I needed, thanks!
