### ISSUE TITLE
can I use gdb, to debug my .ts files with deno?

### ISSUE THREAD

**Issue by George35mk** [denoland/deno#1404]
Can I use **gdb**, to debug my **.ts** files with deno? I have windows 10 x64 and I dont know anything about Linux and Mac, LLDB on windows is only for x32 and the x64 is not stable.

Basically, it is possible to debug a **deno** app on Windows Os and if yes, can someone guide me? 

Thanks.

**Comment by ry** [comment]
@George35mk You can use gdb to debug deno itself, but not the typescript files... You can also use visual code or visual studio to debug.
