### ISSUE TITLE
Using deps directory to avoid unused imports

### ISSUE THREAD

**Issue by LuizzAugusto** [denoland/deno#14047]
Hey. I suggest using deps directory with every deps in a separate file to deno and create something like `deno gendeps=deps.ts` to create deps.ts. The intention it's using the deps folder to avoid unused imports and deps file for developers cache deno dependencies.

**Comment by kitsonk** [comment]
I am not totally clear on what you are proposing, or what problem it is solving.

What does the current `DENO_DIR` caching mechanism coupled with an opt-in of something like `deno vendor` not solve that this would solve?

**Comment by LuizzAugusto** [comment]
It's change the standard, instead of recommending create the deps.ts file for imports, but just for internal use (development, to make a fast way to cache), and use a file per dependencies in the real project. I don't known deno vendor yet.

**Comment by crowlKats** [comment]
This seems very odd with quite bad DX with no benefit, so closing
