### ISSUE TITLE
lsp: migrate from `lspower` back to `tower-lsp`

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#14056]
`lspower` was a fork that fixed a lot of things with `tower-lsp`, but not `lspower` has been remerged back into `tower-lsp` and deprecated. [`tower-lsp`](https://crates.io/crates/tower-lsp) is being maintained going forward, so we should/need to remigrate back.

**Comment by kitsonk** [comment]
(thanks @sno2 for [pointing it out](https://github.com/denoland/vscode_deno/issues/509#issuecomment-1073409917))

**Comment by AbhijithGanesh** [comment]
is this a good first issue for a new contributor?

**Comment by kitsonk** [comment]
Not entirely sure... It could be very straight forward, but it could get quite tricky if it doesn't work. If someone were to try to do it and the tests didn't pass, it could get quite complicated to figure out, but would be glad to try to help if someone wanted to try.

**Comment by AbhijithGanesh** [comment]
Does this have a pre-commit script with which I can locally test the changes? I am up for trying it and I can reach out on discord if I have doubts. Would that work?

**Comment by AbhijithGanesh** [comment]
@CGQAQ If I want to add in my changes, can I push it  to your PR?

**Comment by CGQAQ** [comment]
@AbhijithGanesh Sorry but I am almost done the refactoring, just lack of tests fix 😢

**Comment by AbhijithGanesh** [comment]
No issues , just wanted to know. :)
