### ISSUE TITLE
WebSocketStream reading not reliable

### ISSUE THREAD

**Issue by Officialstrike** [denoland/deno#14050]
### Issue Details

* **Deno Version:**
  * deno 1.19.3 (release, x86_64-pc-windows-msvc)
  * v8 9.9.115.8
  * typescript 4.5.2
* **Operating System:**
  * Windows 10 21H1

### Expected Behavior
While using async/await there should never be an error claiming module eval is still pending.

### Actual Behavior

While using async/await, it will return a module eval error after a while `error: Module evaluation is still pending but there are no pending ops or dynamic imports. This situation is often caused by unresolved promises.`

### To Reproduce

 - Copy the [Async/await](https://gist.github.com/Officialstrike/1fb2ece6c011b82ed123c5c42cc13603)  code
 - run the file using `$ deno run --unstable --allow-net  <file name here> `
- Wait a couple of seconds, and then it will produce an error.

**Comment by lucacasonato** [comment]
In the `.then` based code, you are creating an infinite amount of promises by calling `reader.read` inside of an infinite loop. You never pause to let the networking do anything, you just create a promise, then jump back to the start of the loop, then create another promise etc.

The `async/await` based code not working is an actual bug in Deno. cc @crowlKats

**Comment by Officialstrike** [comment]
> In the `.then` based code, you are creating an infinite amount of promises by calling `reader.read` inside of an infinite loop. You never pause to let the networking do anything, you just create a promise, then jump back to the start of the loop, then create another promise etc.
> 
> The `async/await` based code not working is an actual bug in Deno. cc @crowlKats

for the first one Ye, I was taking a shower and realized it lmao, was gonna update it but you've already done it.

**Comment by Officialstrike** [comment]
After debugging in the WebSocket stream file, it seems to lie somewhere at the pull function, specifically when a ping happens. now I implemented my own patch, (hold on cuz it's really dumb. I added `controller.enqueue("ping")` under https://github.com/denoland/deno/blob/main/ext/websocket/02_websocketstream.js#L272 now on reader, I get the value "ping" and I respond with a generic json object just writing `await writer.write(JSON.stringify({ type: "ping" }));`. Maybe sending a message is keeping the socket alive?

**Comment by Officialstrike** [comment]
Update: seems like just doing `controller.enqueue();` [02_websocketstream.js#L272](https://github.com/denoland/deno/blob/main/ext/websocket/02_websocketstream.js#L272) without any handling on the client-side also fixes it.

**Comment by Officialstrike** [comment]
Update, using the same code with the patch applied above I'm getting this error: `error: Uncaught (in promise) Error: IO error: unexpected end of file
    at Object.pull (deno:ext/websocket/02_websocketstream.js:283:35)`

**Comment by Officialstrike** [comment]
Fixed per #15235
