### ISSUE TITLE
node compat checker

### ISSUE THREAD

**Issue by elycheikhsmail** [denoland/deno#14061]
I request for command like this
deno utiles checkcompat {pkg name or url }
that fetch and analyse given pkg and tel if it deno compat or not if not compat it will list node api used in this pkg and not supported by deno compat

**Comment by UltiRequiem** [comment]
The idea sounds cool, but IMO  it would be better on the userland.

Kinda like https://github.com/hayd/deno-udd

**Comment by dsherret** [comment]
Probably better to just make deno compat work where it doesn't?

**Comment by elycheikhsmail** [comment]
> Probably better to just make deno compat work where it doesn't?

Yes but I think it will take sometime ( may be long time) and I think node compatibily will never be 100% with actual approach.

**Comment by UltiRequiem** [comment]
> I think node compatibily will never be 100% with actual approach.

Could you elaborate please?

**Comment by elycheikhsmail** [comment]
> 
I think some of node compatibilty goals are: 
1- give dev possibility to use existing js pkg in npm registrary in deno
2- easy migrate code writen for nodeFirst to be denoFirst and use it in both runtime
for js pkg not compatible with deno we
can write his equivalent in denojs but instead we can change or add small peace of this code to make it deno compat.
actual deno --compat approach ( maybe forever ) is to run code as it even this code use some node (supported) api, I think this approach can't be universal because it will always depend on supported node api by deno compatibility and question is npm pkg x is supported by deno compatibility will be always asked?  If no the next question why ? will be asked too.

**Comment by lucacasonato** [comment]
I don't think this is technically possible. We aim to have full node compatibility. Try run the program in Deno to see whether it works - a separate tool is not necessary.
