### ISSUE TITLE
`deno check`

### ISSUE THREAD

**Issue by ry** [denoland/deno#14071]
- Add `deno check`. It should be exactly the same thing as `deno cache`. 
- Add `deno run --check` for forward compatibility. (It will be required in the future for type-checking.)
- Print warning during `deno run` if `--check` is not provided. "Warning: In future releases deno run will not automatically type check without the --check flag."

**Comment by lucacasonato** [comment]
I am not super happy with the way the warning is proposed to work. I think we should have a `DENO_FUTURE_TYPECHECKING_BEHAVIOUR=1` flag or similar that will switch Deno into the "new" no type checking by default behaviour completely right now. The `deno run` message should be updated to say: "Warning: In future releases deno run will not automatically type check without the --check flag. To opt into this new behaviour now, specify DENO_FUTURE_TYPECHECKING_BEHAVIOUR=1."

In a couple of releases we can then turn this from a warning into an error, and then subsequently from an opt in to an opt out, and then finally fully switch.

This is very similar to how the `go.mod` adoption in the Go ecosystem worked (through the `GO111MODULE=1` env var).

**Comment by ry** [comment]
Duplicate of https://github.com/denoland/deno/issues/11786
