### ISSUE TITLE
deno vendor with importMap fails to resolve modules

### ISSUE THREAD

**Issue by cdaringe** [denoland/deno#14077]
# Problem

`deno run --import-map=vendor/import_map.json mod.ts` fails to resolve dependencies after dependencies vendor'd via `deno vendor --import_map=...`.

Error: `# error: Relative import path "oak/mod.ts" not prefixed with / or ./ or ../`

# Discussion

**works**:

```
$ deno run --import-map import_map.json  -A --unstable /app/src/bin.ts
```

**doesn't work**:

```
# vendor the deps, using the ~same flags as above
$ deno vendor --import-map=import_map.json /app/src/bin.ts

# run with vendored
$ deno run --import-map=/app/vendor/import_map.json --unstable --allow-env --allow-net /app/src/bin.ts
# yields:
# error: Relative import path "oak/mod.ts" not prefixed with / or ./ or ../
```

# Reproduction

Easy!

- `git clone https://github.com/cdaringe/deno-emit-esm-server.git`
- `cd deno-emit-esm-server`
- `git checkout b23071be397a2d2e7e7ca53b9df0832de3241bb9`
- (optional) Prove that the server works
    - run it:`deno run --import-map=import_map.json --unstable --allow-env --allow-net ./src/bin.ts` (no output)
    - access it: `curl http://localhost:7777/github/denoland/deno_std/main/uuid/mod.ts` (observe JS emitted to stdout)
- `deno vendor --import-map=import_map.json ./src/bin.ts`
- `deno run --import-map=vendor/import_map.json --unstable --allow-env --allow-net ./src/bin.ts`
  - Observe the module resolution failure

**Comment by dsherret** [comment]
Looks like https://github.com/denoland/deno/issues/13697
