### ISSUE TITLE
Proposal: Cancel the deprecation of FsWatcher.return method

### ISSUE THREAD

**Issue by kt3k** [denoland/deno#14086]
We added `.close` method, and deprecated `.return` method in #10577. While `.close` is fine as a way for users to explicitly close the watcher, there were some inputs from the community that `.return` method is also useful for automatically closing the watcher when you break from the async iterable loop. (Thanks @mitranim and @connorlogin for the suggestions)

```js
const watcher = Deno.watchFs(".");
for await (const event of watcher) {
  if (event.kind === "remove") {
    break;
  }
}
// Here you still need to call watcher.close(), if we removed `.return` in 2.0
```

So I suggest we should cancel the deprecation of `.return` and keep it as is (with the clarification of the purpose of each method.)

**Comment by kt3k** [comment]
Discussed this internally. `.return` method could be convenient for the case of FsWatcher, but all other async iterable APIs don't provide `.return` method. So we make FsWatcher not providing it either for consistency

**Comment by mitranim** [comment]
```js
async function* blah() {}
const iter = blah()
console.log(`iter.return:`, iter.return)
// iter.return: [Function: return]
```

Async iterators in general by default provide `.return`. Removing it from _some_ of them "for consistency"?..

**Comment by kt3k** [comment]
"other async iterators" here means other Deno async iterator APIs like `Deno.listen()`, `Deno.serveHttp()`, `Deno.signal()`, etc

**Comment by connorlogin** [comment]
Just to clarify, does this mean when Deno 2 lands we'll need to start manually closing FsWatchers after breaking from the for-await loop?

**Comment by kt3k** [comment]
> Just to clarify, does this mean when Deno 2 lands we'll need to start manually closing FsWatchers after breaking from the for-await loop?

I'm not 100% sure about this. We're now implementing [garbage collectable resource](https://github.com/denoland/deno/pull/14237). File watcher might be garbage collected automatically after breaking the async loop. I'll update this issue if we understand the situation in more details.
