### ISSUE TITLE
`deno.cwd` return the wrong function name `cwd$1`

### ISSUE THREAD

**Issue by justjavac** [denoland/deno#1409]
```js
> deno.cwd
[Function: cwd$1]

> deno.cwd.name
cwd$1
```

Rollup outputs js files in `iife` format, rollup will rename the identifier when an identifier conflict occurs. `rollup-plugin-node-globals` depends on process-es6, which also [exports the `cwd` function](https://github.com/calvinmetcalf/node-process-es6/blob/master/browser.js#L158).

`chdir` too.

A simple solution is to rewrite `export function cwd()` to `export const cwd = function cwd()`. However, we don't know which functions will conflict in the future (maybe now), so we should start from rollup to solve this problem once and for all.

**Comment by kevinkassimo** [comment]
`setTimeout` too: 
```
> setTimeout
[Function: setTimeout$1]
```

**Comment by monkingxue** [comment]
@justjavac Maybe we should remove rollup-plugin-node-globals gradually because we are implementing these global methods, so we don't need code shim like these.

**Comment by bartlomieju** [comment]
This issue no longer occurs:
```ts
$ deno
> deno.cwd
[Function: cwd]
> deno.cwd.name
cwd
```

@justjavac can we close this issue?
