### ISSUE TITLE
Deno has panicked issue

### ISSUE THREAD

**Issue by tru9** [denoland/deno#14100]
This randomly popped up on my screen and I'm unsure of what to do
![image](https://user-images.githubusercontent.com/71397571/159812710-1a266a91-6145-43db-9e76-c61eef9f7cb7.png)

**Comment by kitsonk** [comment]
Had this previously worked?  Did you recently upgrade to Deno 1.20.1?

Can you try to remove your DENO_DIR cache and try again?

@dsherret this is the same thing we saw in another context today.

**Comment by tru9** [comment]
Yeah, I updated Deno before that. I forgot what I did, but I tried changing things within the code and that fixed it..

**Comment by kitsonk** [comment]
ok, because there isn't a clear reproduction, closing.  If you can reproduce it again, we can re-open the issue.
