### ISSUE TITLE
Remove `fetch(input: URL, ...)` signature from lib.deno_fetch for 2.0

### ISSUE THREAD

**Issue by kt3k** [denoland/deno#14116]
We deprecated `fetch(input: URL, ...)` signature in #14113. We should remove this in 2.0.

**Comment by ayame113** [comment]
#14113 was reverted in #15219, so should this issue be closed? (should it also be removed from v2 milestones?)

**Comment by kt3k** [comment]
Right. This isn't relevant anymore. Closing

ref. This issue is also related https://github.com/denoland/deno/pull/14769
