### ISSUE TITLE
 Dynamically imported module evaluation is still pending but there are no pending ops. 

### ISSUE THREAD

**Issue by tru9** [denoland/deno#14110]
I'm currently trying to import a map from `./mods.ts`, and for some reason whenever I try accessing a property from the file. I end up getting this error: 
![image](https://user-images.githubusercontent.com/71397571/160026627-0882fa77-1fa5-4d1e-ad20-1803d01ec343.png)

I don't even know where I went wrong, anything I try to access & import from `./mod.ts` returns me this error.

**Comment by bartlomieju** [comment]
This error means that there's a top level promise that is being awaited and never resolves. The error is bad and doesn't provide much info, however there's no way to obtain more information from V8 about it.

I suggest to paste your code here

**Comment by tru9** [comment]
Alright, I added the `interaction.ts` code because that's the file I created before getting that error & contains the import.

`command.ts`
https://pastebin.com/kTDjPw1a

`mod.ts`
https://pastebin.com/erFfPgQK

`interaction.ts`
https://pastebin.com/H1J4ijvw

**Comment by tru9** [comment]
I found out this code was the reason the error was being thrown. I'm just unsure of how to fix it.

```ts
for await (const dirEntry of Deno.readDirSync("./src/cmd")) {
	if (dirEntry.isDirectory) {
		for (const file of Deno.readDirSync(`./src/cmd/${dirEntry.name}`)) {
			const path = await import(`./cmd/${dirEntry.name}/${file.name}`);
			SlashCommands.set(file.name.split(".ts")[0], { info: path.command, func: path.exe });
		}
	}
}
```

**Comment by alevroub** [comment]
@tru9 I believe this happens when the file you're importing dynamically (``./cmd/${dirEntry.name}/${file.name}``) itself imports other modules. Just hit the same issue.
