### ISSUE TITLE
Proposal: import permissions

### ISSUE THREAD

**Issue by Im-Beast** [denoland/deno#14127]
## Why
Recent controversy about `node-ipc` showcased node's security weakness. People would think that deno is bulletproof for this kind of issues, but it isn't.

## Let me elaborate:
Even if you'd import non-malicious module with semver – you're fine until its time to update. You're mostly probably just updating those numbers in imports and maybe refactoring code, you don't check whether module has became dangerous.

## Idea
Here comes my idea – import permissions.
By default you could take two directions:
 - Inherit permissions from the entry module, fully backwards compatible
 - Allow none of the permissions by default, breaking change
That way, we would be 100% safe that modules imported by us wouldn't do what we need them to do.

## Syntax
Syntax is debatable, however I see this coming closely to import assertions, e.g.:
```ts
// static imports
import * as malicious from "https://deno.land/x/some-random-module/mod.ts" allow { read: true } // when allowing none by default
import * as malicious from "https://deno.land/x/some-random-module/mod.ts" allow { read: true, write: false, run: false } // when inheriting permissions
import * as malicious "https://deno.land/x/some-random-module/mod.ts" allow { read: "/tmp" } // allow reading only specific directory

// dynamic imports
const malicious = await import("https://deno.land/x/some-random-module/mod.ts", {
  allow: {
    read: true,
  },
})
```

**Comment by crowlKats** [comment]
Duplicate of https://github.com/denoland/deno/issues/1639.
Also, we can't just add new syntax
