### ISSUE TITLE
Support vendoring modules which read "static" files, like `.wasm`

### ISSUE THREAD

**Issue by GJZwiers** [denoland/deno#14123]
I would like to `deno vendor` a module that uses WebAssembly (WASM). It is compiled using `wasm-bindgen` so there is a directory structure like this:

```
pkg/
├── file.js
├── file_bg.wasm
├── file.d.ts
```

The `.js` file contains glue code that calls into the `.wasm` file. It is vendored successfully but tries to fetch the WASM from a URL like this:

```js
input = new URL('file_bg.wasm', import.meta.url);
```

Unfortunately, after vendoring the URL points to a path in the local filesystem, but nothing is there because the `.wasm` file isn't brought over. So it is not possible to run the module locally after vendoring.

**Comment by kitsonk** [comment]
Hmmm... vendoring remote modules that read "static" files would be complex, but I can see the need.

@dsherret thoughts?

**Comment by mlafeldt** [comment]
Noticed this problem today when trying to vendor eszip:

```
❯ deno vendor https://deno.land/x/eszip@v0.18.0/mod.ts
Vendored 3 modules into vendor/ directory.

To use vendored modules, specify the `--import-map` flag when invoking deno subcommands:
  deno run -A --import-map vendor/import_map.json main.ts

❯ tree vendor/
vendor/
├── deno.land
│   └── x
│       └── eszip@v0.18.0
│           ├── eszip_wasm.generated.js
│           ├── loader.ts
│           └── mod.ts
└── import_map.json

3 directories, 4 files
```

Since https://deno.land/x/eszip@v0.18.0/eszip_wasm_bg.wasm isn't downloaded, the vendored version of eszip is broken.

**Comment by bartlomieju** [comment]
I believe this will have to wait for https://github.com/denoland/deno/issues/2552

**Comment by petamoriken** [comment]
I believe we need to wait for [Import Attributions (a.k.a Import Assertions)](https://github.com/tc39/proposal-import-assertions).

**Comment by dsherret** [comment]
Actually, yeah this would be supported by #2552. For now, this can be solved by manually running a custom post-vendoring step to download the necessary .wasm files.

**Comment by serhalp** [comment]
@dsherret now that https://github.com/denoland/deno/pull/26668 has landed, can we reopen this issue? 👀

**Comment by dsherret** [comment]
I don't think there's anything actionable in this issue. With Wasm modules this now works, but they need to be imported using Wasm imports.

For static files, follow https://github.com/denoland/deno/issues/25354

**Comment by serhalp** [comment]
@dsherret Ah, my bad — you're saying that when WASM support landed, WASM vendoring support landed too? In that case, carry on :)
