### ISSUE TITLE
Make help clearer about log level

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#14145]
People new to Deno might assume that the `-L` and `--log-level` flags affect _all_ logging including `console.*` (see: #14143).  Current help is certainly ambiguous:

```
    -L, --log-level <log-level>
            Set log level
            
            [possible values: debug, info]

```

We should make it clear that it only applies to internal bugging.  Something like:

> Set log level for internal logging. Does not impact logging via `console`.

**Comment by ry** [comment]
We could probably hide this option entirely from the `--help` since it's really only useful for internal debugging.

**Comment by kxxt** [comment]
I could work on this. Should we hide it entirely or make it clear?

**Comment by kxxt** [comment]
Maybe we can make it clear and hide it at the same time.

**Comment by GJZwiers** [comment]
With #14249 landed this could be closed
