### ISSUE TITLE
cannot send Sec-WebSocket-Protocol using Deno.upgradeWebSocket

### ISSUE THREAD

**Issue by halparn** [denoland/deno#14169]
Normally i was use old ws handle methods of Deno std, but after upgrade the modules and ws get deprecated i try to use, 
Deno.upgradeWebSocket. when i try to send  Sec-WebSocket-Protocol header from client to deno server it's gives me that exception: 

"WebSocket protocol error: Connection reset without closing handshake"

I didn't get any similar error both i was using deprecated ws or wasn't send Sec-WebSocket-Protocol header from client. but i use it for Authentication and i cannot verify ws request anymore.

**Comment by crowlKats** [comment]
Could you share some code to reproduce?

**Comment by halparn** [comment]
`
                if (route.method === 'WS') {
                        const {socket, response} = Deno.upgradeWebSocket(req)
                        route.handler(socket, req)
                        return response
                    }
`
This is where i upgrade incoming request if its WebSocket request.  It's a part of application router and works fine, 

`
      async function startscan(socket, req) {
             //.....
    socket.onmessage = async (e) => {
    const msg = e.data;
    cnt += 1;
    offset += msg.byteLength || 0;
    if (typeof msg === "string") {
      await oncmd(msg);
    } else if (msg instanceof ArrayBuffer) {
      await ondata(msg);
    } else {
      raise(400, `Unknown message type. ${cnt} offset ${offset}`);
    }
  };

  socket.onclose = () => console.log("WebSocket has been closed.");
  socket.onerror = async (e) => {
    console.log(e);
    await socket.send(JSON.stringify(e));
    // if (socket.OPEN) await socket.close();
  };

`
A socket handler written for file upload. It perfectly works when I don't send the header I mentioned above.

Here is the client code i send the protocol: 

`
       const socket = new WebSocket(url, token);
`

when i delete the token parameter it's works fine.

**Comment by halparn** [comment]
```javascript
                if (route.method === 'WS') {
                        const {socket, response} = Deno.upgradeWebSocket(req)
                        route.handler(socket, req)
                        return response
                    }
```
This is where i upgrade incoming request if its WebSocket request.  It's a part of application router and works fine, 


```javascript
async function startscan(socket, req) {
             //.....
    socket.onmessage = async (e) => {
    const msg = e.data;
    cnt += 1;
    offset += msg.byteLength || 0;
    if (typeof msg === "string") {
      await oncmd(msg);
    } else if (msg instanceof ArrayBuffer) {
      await ondata(msg);
    } else {
      raise(400, `Unknown message type. ${cnt} offset ${offset}`);
    }
  };

  socket.onclose = () => console.log("WebSocket has been closed.");
  socket.onerror = async (e) => {
    console.log(e);
    await socket.send(JSON.stringify(e));
    // if (socket.OPEN) await socket.close();
  };
```

A socket handler written for file upload. It perfectly works when I don't send the header I mentioned above.

Here is the client code i send the protocol: 

```javascript
     const socket = new WebSocket(url, token);
```

when i delete the token parameter, it's works fine.

**Comment by crowlKats** [comment]
@halparn I have tried to reproduce, but I am not encountering any issue as you describe

**Comment by halparn** [comment]
oh write then. thank you for helping. could you give me some information for what's that mean, "Connection reset without closing handshake", so i can figure how could i produce it with my case. 

For example is that any related with a mismatch between incoming request  headers and response header's send it to client.

**Comment by crowlKats** [comment]
just to be sure: you are saying this is not working for you?
```ts
const server = Deno.listen({ port: 8080 });

for await (const conn of server) {
  (async () => {
    for await (const http of Deno.serveHttp(conn)) {
      const { socket, response } = Deno.upgradeWebSocket(http.request);
      socket.onmessage = () => console.log("message");
      socket.onclose = () => console.log("WebSocket has been closed.");
      socket.onerror = console.log;
      http.respondWith(response);
    }
  })();
}
```
```ts
const socket = new WebSocket("ws://localhost:8080", "foobar");
socket.onerror = console.log;
socket.onopen = () => socket.send("foo");
```

**Comment by halparn** [comment]
i have tried it this script's in deno it's works, but i try send it from browser for that copy that second script and request it from the browser, then it gives me same error, then i delete protocol argument "foobar" and its send it and didnt give me any error. 

If I'm not mistaken, it's an error generated when the request is made from the browser.
just to keep it unclear, in my scenario client is reactjs dev server.

**Comment by crowlKats** [comment]
Ok so, this is only in chrome (ff and safari dont have this issue). the problem is that chrome is expecting the same `protocol` to be returned by the server, else it will fail the connection. This can be set with the `protocol` field in the options bag for `Deno.upgradeWebSocket`.

**Comment by halparn** [comment]
yep it's solve my problem, thank a lot i'm closing this issue.
