### ISSUE TITLE
eventListener and signalEvents side effect

### ISSUE THREAD

**Issue by oscarotero** [denoland/deno#14176]
I have an event listener for "unload" event to run a code just before finishing the script. But this code is not executed if the process is closed with `Command+C`, so I've added a "SIGINT" event.

```js
Deno.addSignalListener("SIGINT", closeFn);
addEventListener("unload", closeFn);
```

Now, when the process is aborted with `Command+C` the closeFn is executed twice, because both event listeners are executed.

**Comment by nayeemrmn** [comment]
This is because an uncaught SIGINT will not trigger an `"unload"` event (#11752), but whatever method you are using to exit in your SIGINT handler does.

**Comment by oscarotero** [comment]
Ok, this does the trick:

```js
Deno.addSignalListener("SIGINT", () => {});
addEventListener("unload", closeFn);
```

**Comment by nayeemrmn** [comment]
> Ok, this does the trick:
> 
> ```js
> Deno.addSignalListener("SIGINT", () => {});
> addEventListener("unload", closeFn);
> ```

Won't this prevent the program from being closed on `Command+C` entirely? That's the behaviour on linux.

**Comment by oscarotero** [comment]
Not on macos.
I guess this only should happens if the function returns `false` (at least this is how it works on browsers).

**Comment by nayeemrmn** [comment]
Hmm... I think this is a good cross-platform workaround:
```ts
let closeFnRun = false;
function closeFn() {
  if (closeFnRun) {
    return;
  }
  closeFnRun = true;
  Deno.exit(0)
}

Deno.addSignalListener("SIGINT", closeFn);
addEventListener("unload", closeFn);
```

**Comment by oscarotero** [comment]
Okay. Thanks!
