### ISSUE TITLE
LSP should support organising imports

### ISSUE THREAD

**Issue by KnorpelSenf** [denoland/deno#14173]
# Feature request

It would be nice to be able to sort imports automatically.

It probably needs to be decided how they should be organised.

## Alphabetically

Simply sort everything alphabetically.

## By import type

First remote URLs, then imports from an import map, then absolute file paths, then relative paths. Imports of the same type are sorted alphabetically.

## By import type and domain

Sort by import type, but also parse URLs and sort by domain. That way, imports from `sub.domain.com` and `domain.com` could be next to each other.

**Comment by Soremwar** [comment]
Import order is significant for the execution of code, so this could break a lot of existing code

See https://github.com/denoland/deno/pull/8551

**Comment by KnorpelSenf** [comment]
I agree that this should not happen with `deno fmt`. I'm explicitly talking about the language server. VSCode has a shortcut exactly for organising imports. It can be used when one doesn't care about the order but rather wants to have a readable import section.

Personally, I think that side-effects during module loading is an anti-pattern and I generally try to avoid it as much as possible. Hence, a different order of imports almost never introduces bugs. It would be good to be able to use this feature when explicitly requested.

**Comment by thegaryroberts** [comment]
Typescript now has a pattern for this with specific ordering can be maintained via groups/comments: https://devblogs.microsoft.com/typescript/announcing-typescript-4-7-rc/#group-aware-organize-imports

New developers picking up Deno might be surprised if this feature does not propagate through to Typescript files being processed by Deno.

It does feel worthy of an addition to deno fmt, but with a flag to prevent breaking existing codebases.

**Comment by KnorpelSenf** [comment]
Related: https://github.com/denoland/deno/issues/12672

**Comment by KnorpelSenf** [comment]
It looks like this is working now, are there any updates on this?

**Comment by denizdogan** [comment]
Has any work been done on this? Let me know, because I might give this a shot.

**Comment by nayeemrmn** [comment]
This seems to be working
