### ISSUE TITLE
lsp: testing api doesn't work without a configuration file set.

### ISSUE THREAD

**Issue by jespertheend** [denoland/deno#14185]
**To Reproduce**

1. Create a file with a test in it
2. Run the test using the new testing api (https://github.com/denoland/deno/pull/13798)

[here's a reduced test case](https://github.com/denoland/vscode_deno/files/8402690/error_reading_config.zip) but the two steps above should suffice. If you uncomment the `"deno.config": "deno.json"` from `.vscode/settings.json`, the tests run fine.

**Expected behavior**

The tests run

**Screenshots**

![image](https://user-images.githubusercontent.com/2737650/161387275-35c5cf57-8928-4f2f-9ecb-62ffdf5b057e.png)
![image](https://user-images.githubusercontent.com/2737650/161387296-98b9d2cf-2762-4b0e-b2ad-edcabbd7cdbf.png)

**Versions**

vscode: `1.65.2` deno: `1.20.4+13b9fc9` extension: `3.12.0`

**Comment by bartlomieju** [comment]
I cannot repeat this problem anymore with latest Deno and extension. @jespertheend can we close this issue now?

**Comment by jespertheend** [comment]
I’m not able to verify the fix myself any time soon, and since you can’t reproduce it anymore I’ll go ahead and close this. I rarely use the extension without a config file nowadays anyway.
