### ISSUE TITLE
test: Print file paths with a separate color

### ISSUE THREAD

**Issue by jespertheend** [denoland/deno#14186]
from https://github.com/denoland/deno/discussions/14156:
> In the list of test results, print the `running n tests from file:///path/to/file.test.js` with a different color. That way when you scroll up you can immediately distinguish tests that come from one specific file.

![image](https://user-images.githubusercontent.com/2737650/161396870-066655f6-f152-4955-82a9-16ba97b6bd88.png)

If this is added, maybe https://github.com/denoland/deno/pull/13930 isn't even needed. With lots of tests it would make the output slightly longer but that's not a huge issue.

**Comment by bartlomieju** [comment]
I'm willing to consider this instead of https://github.com/denoland/deno/pull/13930 as it poses some challenges in formatting output for "test steps" API. This would be a very quick change. @dsherret thoughts?
