### ISSUE TITLE
Install directly after ./tools/build.py

### ISSUE THREAD

**Issue by djKooks** [denoland/deno#1418]
Is there a way to install with objects generated after `./tools/build.py` completed?
I've installed `deno` with installer, and want to work with newest version, but cannot find installer from source code.

Thanks.

**Comment by bartlomieju** [comment]
You can find instructions here: https://github.com/denoland/deno/blob/master/Docs.md#build-instructions-for-advanced-users-only

**Comment by djKooks** [comment]
@bartlomieju oh, sorry. My actual problem is:
1. I installed deno with installer, its version is 0.2.1
2. Now I follow build instruction
3. It causes failure in `./tools/tests.py`

Test failure seems there are some removed module compare 0.2.1 with 0.2.4.
How can I run tests.py with build version?

Thanks.

**Comment by bartlomieju** [comment]
@djKooks installing Deno with installer shouldn't have any impact on building the project - it's just a single binary. 

That said you should be able to run the tests with `./tools/test.py target/debug/deno`. If you encounter errors, please provide output so we can pinpoint the issue. Also make sure that you update git submodules when building from source - `git submodule update --recursive` should do the trick.

**Comment by ry** [comment]
What’s the failure? The test.py program shouldn’t reference an installed Deno - but maybe it does

**Comment by djKooks** [comment]
@bartlomieju @ry sorry for late.
I tested again with newest version. Issue has been changed, but there are still problem:
```
test resources::test_table_entries ... ok
test isolate::tests::execute_mod ... ok
test js_errors::tests::js_error_apply_source_map_2 ... ok

test result: ok. 56 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

Compiling /Users/jung/workspace/etc/deno/js/unit_tests.ts
NotFound: Cannot resolve module "./deps/https/deno.land/x/std/testing/mod.ts" from "/Users/jung/workspace/etc/deno/js/test_util.ts"
    at DenoError (deno/js/errors.ts:19:5)
    at maybeError (deno/js/errors.ts:38:12)
    at maybeThrowError (deno/js/errors.ts:26:15)
    at sendSync (deno/js/dispatch.ts:67:5)
    at codeFetch (deno/js/os.ts:38:19)
    at _resolveModule (deno/js/compiler.ts:235:38)
    at moduleNames.map.name (deno/js/compiler.ts:513:31)
    at resolveModuleNames (deno/js/compiler.ts:505:24)
    at compilerHost.resolveModuleNames (deno/third_party/node_modules/typescript/lib/typescript.js:32750:71)
    at resolveModuleNamesWorker (deno/third_party/node_modules/typescript/lib/typescript.js:20688:69)
```

Thanks.
Also, is there some kind of command to 'update' current deno version via source?

**Comment by bartlomieju** [comment]
@djKooks can we close this in favor of #1399?

**Comment by djKooks** [comment]
@bartlomieju you're right. Thanks for following up.
