### ISSUE TITLE
test: print error messages with a red color

### ISSUE THREAD

**Issue by jespertheend** [denoland/deno#14189]
When a test fails, there's two things I want to know first:
1. **Which** test failed
2. **Why** the test failed

So I think it makes sense to put some extra emphasis on the error message.

from https://github.com/denoland/deno/discussions/14156:
> I think it's a lot easier to visually parse like this. Not sure how feasible it would be to print error messages in red though. Since error messages might have custom color formatting. Maybe they should only be printed in red if the error message does not contain any ansi codes.

![image](https://user-images.githubusercontent.com/2737650/161397135-a6379f34-239e-48ca-8fd9-21c930b0dfd6.png)

**Comment by bartlomieju** [comment]
Ref https://github.com/denoland/deno/pull/14287 which is a prerequisite for this feature
