### ISSUE TITLE
lsp: codelens does not render when using backticks for test name

### ISSUE THREAD

**Issue by cdaringe** [denoland/deno#14195]
**Describe the bug**

Using backtick strings prevents codelens from popping up:

![codelens_not_respecting_backticks mov](https://user-images.githubusercontent.com/1003261/161442115-30792479-bc55-458c-8e6d-bd19e84a7a9a.gif)

Using normal quotes works

**To Reproduce**

1. author a test
2. use backticks to render the fn name
3. observe codelens not pop up
4. use normal quotes
5. observe codelens pop up

**Expected behavior**

codelens should render with all valid strings

**Screenshots**

See GIF above

**Versions**

vscode: 1.66 deno: 1.20.3 extension: 3.12.0

**Comment by kitsonk** [comment]
This issue was discovered when doing the testing API. We planned to refactor the code to share the same collectors in a follow up PR.

**Comment by nayeemrmn** [comment]
This is fixed
