### ISSUE TITLE
deno.json exclude certain filetypes doesn't work

### ISSUE THREAD

**Issue by felixsanz** [denoland/deno#14193]
```
  "fmt": {
    "files": {
      "exclude": ["build/", "dist/", "static/", "*.md"]
    },
```
Folders work fine, but `*.md` doesn't. Also `**/*.md`doesn't work, fmt fixes markdown files no matter what. So... there is no way to ignore markdown files from fmt? If not, any plan to include the option? It's messing up my text files

**Comment by ah-yu** [comment]
Currently deno does not support glob patterns.

You can ignore formatting by adding a `<!-- deno-fmt-ignore-file -->`comment  in markdown files. See https://deno.land/manual@v1.20.4/tools/formatter

**Comment by felixsanz** [comment]
> Currently deno does not support glob patterns.
> 
> You can ignore formatting by adding a `<!-- deno-fmt-ignore-file -->`comment in markdown files. See https://deno.land/manual@v1.20.4/tools/formatter

Yes but if you have 89 markdown files that's insane. Can be added the option to use "*.md" at least?
