### ISSUE TITLE
test: Better headers for the three `deno test` sections

### ISSUE THREAD

**Issue by jespertheend** [denoland/deno#14190]
Right now `deno test` gets printed with three sections, but it's not immediately clear where one ends and the other starts. And the last two sections both have `failures:` as header.

I think it could be nice to make them a bit more distinguishable and name them `results`, `errors` and `failures` respectively.

Giving them a separate color would also help I think.

![image](https://user-images.githubusercontent.com/2737650/160925198-9b11111b-465b-4574-b4b4-ecf17d31bbd2.png)

**Comment by bartlomieju** [comment]
Ooops, this is actually not fixed...
