### ISSUE TITLE
test: `console.log` calls get printed in between the test results

### ISSUE THREAD

**Issue by jespertheend** [denoland/deno#14192]
Consider the following test:
```js
Deno.test({
  name: "logs a message",
  fn() {
    console.log({bool: true, num: 5})
    console.log("hello");
  }
})
```

When you run it, it shows up with the console messages in between `test logs a message ...` and `ok (8ms)`:

![image](https://user-images.githubusercontent.com/2737650/161397622-ac214aa9-5bfe-42a9-acce-1b94a2f881b7.png)

And also, multiple `console.log` calls have two new lines in between them. If you were to do this with `deno run`, they are printed with only a single new line in between:

![image](https://user-images.githubusercontent.com/2737650/161397703-e5a4ed0f-0066-420c-8fbf-377b043a941b.png)

Not sure what the right behaviour is here, but some things I can think of:
- keep it almost like it is right now, except add a new line before the first `console.log()` call, and then only a single new line between every two calls, rather than the double new lines it currently prints.
- print the `console.log()` messages above/below the test result, and then print `ok (8ms)` retroactively in the right position once the test finishes. Not sure how difficult this would be, or if it even would be possible at all.
- Disable printing `console.log()` messages during tests altogether.

All in all I don't think this issue needs to have a very high priority imo, tests generally shouldn't run code that call `console.log` without mocking it first. But I do have a lot of tests that dynamically import blob urls, which looks kind of weird:

![image](https://user-images.githubusercontent.com/2737650/160927670-d88a76d2-c298-4094-a301-80a5ac80a09c.png)

**Comment by luk3skyw4lker** [comment]
I'm gonna take a look at it and open a PR as soon as I can.

**Comment by luk3skyw4lker** [comment]
I guess I'll go with the first idea of keeping it as it is, but adding a new line before the first console.log call and only a single line break for subsequent calls.

I don't think that disabling the console.log messages during tests is the best way, the messages could be useful to someone. Maybe the case could be adding a flag like "--no-console" to the test options, but I'm not sure of how hard this is.
