### ISSUE TITLE
Out of memory issue with large amount of parallel `setTimeout`

### ISSUE THREAD

**Issue by jwanner83** [denoland/deno#14203]
Hey guys. First of all: This issue is not critical by any means because the steps to produce the OOM are not really realistic in real world applications.

While I was playing around with the new `bench` functionality, I encountered an OOM when there are a lot (~5'000'000) of parallel `setTimeout`. I tested the same code in node to see if it behaves the same, which wasn't the case.

Is this behavior expected, or shouldn't it be the case? 

## Reproduction steps
<details>
  <summary>Full code</summary>

```js
const a = []
for (let i = 0; i < 5000; i++) {
  a.push(Math.floor(Math.random() * 10000))
}
const s = []
for (let i = 0; i < 1000; i++) {
  a.forEach((e) => { setTimeout(() => s.push(e), e) })
}
```  
</details>

1. Create a js file `script.js`
2. Create an array with 5000 random, 4 digit numbers
```js
const a = []
for (let i = 0; i < 5000; i++) {
  a.push(Math.floor(Math.random() * 10000))
}
```
3. Initialize timeouts for every elements in array a thousand times with the number as time amount.
```js
const s = []
for (let i = 0; i < 1000; i++) {
  a.forEach((e) => { setTimeout(() => s.push(e), e) })
}
```
4. Run the script
`deno run ./script.js` - *fails*
`node ./script.js` - *works*

<details>
  <summary>Exception</summary>

```
<--- Last few GCs --->

[11596:0x148200000]     7180 ms: Scavenge 1368.1 (1417.3) -> 1367.8 (1429.8) MB, 4.6 / 0.0 ms  (average mu = 0.390, current mu = 0.272) allocation failure; 
[11596:0x148200000]     7212 ms: Scavenge 1377.3 (1430.5) -> 1377.6 (1432.3) MB, 4.1 / 0.0 ms  (average mu = 0.390, current mu = 0.272) allocation failure; 
[11596:0x148200000]     7604 ms: Scavenge 1377.6 (1432.3) -> 1376.9 (1454.3) MB, 392.1 / 0.0 ms  (average mu = 0.390, current mu = 0.272) allocation failure; 


<--- JS stacktrace --->


#
# Fatal javascript OOM in Reached heap limit
#

[1]    11596 trace trap  deno run sort.js
```  
</details>

## Environment
**Computer:** Macbook Pro M1 Late 2020, 16 GB Ram
**deno:** 1.20.4 (release, aarch64-apple-darwin)
**V8:** 10.0.139.6

**Comment by andreubotella** [comment]
This is likely due to the scheduled timers list. This list is necessary for correctness according to the spec, but maybe it could be optimized.

**Comment by bartlomieju** [comment]
I'm gonna close this issue now as we did a full rewrite of timer infrastructure in Deno v1.42 - https://deno.com/blog/v1.42#performance
