### ISSUE TITLE
lsp - Caching dependencies requires restarting language server to reset diagnostics

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#14207]
Recently I've noticed I have to reset the language server when caching dependencies. I investigated this a bit and seems to be an issue in the CLI. It seems to occur in deno all the way back to 1.17 (min version I can use vscode with).

To reproduce:

1. Delete your DENO_DIR
1. Open the tswhy repo.
1. Open the main.ts and deps.ts file.
1. Run the "Cache dependencies" command on the deps.ts file.
1. Type errors still occur in the main.ts file. Restart the language server to fix.

This doesn't seem to be a diagnostics invalidation issue... probably some state elsewhere that's not being cleared.

vscode: 1.66.0 deno: 1.20.4 extension: 3.12.0

**Comment by sgwilym** [comment]
I’m seeing this too using the LSP with my Nova + Deno extension.

**Comment by aslilac** [comment]
@dsherret have you done any work on this yet? @bartlomieju and I are thinking of pairing on this tomorrow

**Comment by dsherret** [comment]
Nope, please do!
