### ISSUE TITLE
`--watch` can corrupt cache

### ISSUE THREAD

**Issue by KnorpelSenf** [denoland/deno#14206]
Recently, I've been using watch mode increasingly, i.e. `deno run --watch`. This corrupted something with the cache.

In particular, `deno cache` would always check the types, even if no files were changed in between. Terminating all other programs (no LSP running and so on), this happened:
```bash
$ for i in {1..5}; do deno cache src/main.ts; done
Check file:///home/steffen/git/dtapp/backend/src/main.ts
Check file:///home/steffen/git/dtapp/backend/src/main.ts
Check file:///home/steffen/git/dtapp/backend/src/main.ts
Check file:///home/steffen/git/dtapp/backend/src/main.ts
Check file:///home/steffen/git/dtapp/backend/src/main.ts
```

The same applied for `deno run`. I could run first `deno cache` and then `deno run` and both operations would type-check the project. I expect only the former one to do so.

The problem was local for the directory. When I `cp -r`ed the directory to `/tmp`, everything worked fine there. In other words, it was remembered that type-checking had been performed, so it was only done once. Subsequent `deno cache` commands completed instantly, exactly as expected.

The problem could be solved by `rm -rf ~/.cache`. (I'm reporting the bug anyway here so it can be fixed.)

I do not know how to reproduce this reliably. However, my suspicion is that the watch mode with its frequent recompilations broke something, perhaps due to partial file writes or other things caused by race conditions and starting and stopping a process repeatedly.

I'm using Deno 1.20.4.

**Comment by dsherret** [comment]
I believe this would be fixed by #13462. Wish we would implement that one because it's very frustrating. I'm waiting for that one to have an initial thumbs up or down.

**Comment by KnorpelSenf** [comment]
#13462 looks promising!

**Comment by bartlomieju** [comment]
@dsherret can we close this issue now?

**Comment by bartlomieju** [comment]
I'm going to tentatively close this issue. Please report if the problem persists.
