### ISSUE TITLE
Closing an already closed file results in a `BadResource` error

### ISSUE THREAD

**Issue by jaydenseric** [denoland/deno#14210]
With a opened file:

```js
const file = await Deno.open(fileUrl);
```

Closing it twice in a row like this:

```js
file.close();
file.close();
```

Or this:

```js
Deno.close(file.rid);
Deno.close(file.rid);
```

Results in this error:

```
BadResource: Bad resource ID
```

This is problematic because as far as I can tell, there is no way to tell if a given file has already been closed before attempting to close it.

My situation is a try catch around code that's using an opened file, that closes the file in the catch. Trouble is there is a chance the file has already been closed at that point so it's not 100% safe to attempt to close it.

We need a way to tell if a file is closed (perhaps via a boolean property on the `Deno.FsFile` class, or a `Deno.isClosed(rid)` utility?), or it could just be made to be safe to close an already closed file; successive calls could be a no-op.

Here is a link to a question about this I asked in the Deno Discord `#help` channel:

https://discord.com/channels/684898665143206084/689420767620104201/960710988334760046

**Comment by jaydenseric** [comment]
Is this a safe way to workaround the issue?

```js
if (file.rid in Deno.resources()) Deno.close(file.rid);
```

**Comment by bartlomieju** [comment]
@jaydenseric yes, this is a good around. But I would suggest this pattern:
```js
try {
  Deno.close(file.rid)
} catch (_) {
 // pass
}
```

**Comment by jaydenseric** [comment]
This issue isn’t stale.

The Deno APIs used in the workaround explained in https://github.com/denoland/deno/issues/14210#issuecomment-1088223213 are deprecated.

A new workaround is this:

```js
file[Symbol.dispose]();
```

It closes the file if it’s still open, and is safe to call after the file has already been closed.

Once Deno supports the syntax `using file = ` in JavaScript (when it's available in V8; currently the syntax only works in TypeScript), then maybe there will no longer be a need to manually dispose of the file i.e. after catching an error.
