### ISSUE TITLE
ReadableStream in bring-your-own-buffer mode doesn't handle EOF

### ISSUE THREAD

**Issue by Macil** [denoland/deno#14219]
`ReadableStreamBYOBReader.read()` should return a Promise that resolves to `{done: true, value: undefined}` when the stream hits EOF, but instead the returned Promise never resolves.

```ts
const req = await fetch("http://example.com");
const reader = req.body!.getReader({ mode: "byob" });

let buf = new Uint8Array(4096);
const result = await reader.read(buf);
console.log(result);

buf = new Uint8Array(result.value!.buffer);
const result2 = await reader.read(buf);
console.log(result2);
```

```
% deno run --allow-net byob_fail.ts
Check file:///Users/macil/Coding/streaming-zip/byob_fail.ts
{
  value: Uint8Array(1256) [
     60,  33, 100, 111,  99, 116, 121, 112, 101,  32, 104, 116, 109, 108,
     62,  10,  60, 104, 116, 109, 108,  62,  10,  60, 104, 101,  97, 100,
     62,  10,  32,  32,  32,  32,  60, 116, 105, 116, 108, 101,  62,  69,
    120,  97, 109, 112, 108, 101,  32,  68, 111, 109,  97, 105, 110,  60,
     47, 116, 105, 116, 108, 101,  62,  10,  10,  32,  32,  32,  32,  60,
    109, 101, 116,  97,  32,  99, 104,  97, 114, 115, 101, 116,  61,  34,
    117, 116, 102,  45,  56,  34,  32,  47,  62,  10,  32,  32,  32,  32,
     60, 109,
    ... 1156 more items
  ],
  done: false
}
error: Module evaluation is still pending but there are no pending ops or dynamic imports. This situation is often caused by unresolved promises.
```

Every read() call works except for the final one that's supposed to resolve to `done: true`. (If you adjust the buffer size to be smaller here so that the first read doesn't reach EOF, then the second read() works fine.)

**Comment by lucacasonato** [comment]
cc @crowlKats

**Comment by crowlKats** [comment]
I am quite surprised this hasnt been caught by streams wpt tests

**Comment by crowlKats** [comment]
Here a simplified replicable test:
```ts
const buf = new Uint8Array(1256);
let first = true;
const readable = new ReadableStream({
  type: "bytes",
  pull(controller) {
    if (first) {
      first = false;
      controller.enqueue(buf);
    } else {
      controller.close();
    }
  }
});

const reader = readable.getReader({ mode: "byob" });

console.log(await reader.read(new Uint8Array(4096)));
console.log(await reader.read(new Uint8Array(4096)));
```

**Comment by crowlKats** [comment]
Huh, so chrome behaves the same. I am not sure if this is intended behaviour or not...

**Comment by Macil** [comment]
If a `type: "bytes"` ReadableStream is in bring-your-own-buffer mode (can detect this by seeing that `controller.byobRequest` is non-null), then the `controller.close()` call must be followed by a call to `controller.byobRequest.respond(0)` (or `controller.byobRequest.respondWithNewView(view)` if the original `controller.byobRequest.view` has been detached), or else the read call will not resolve. (This is by the standard from my understanding of [ReadableByteStreamControllerRespondInClosedState](https://streams.spec.whatwg.org/#readable-byte-stream-controller-respond-in-closed-state), and that the two examples of `type: "bytes"` ReadableStreams in the standard ([1](https://streams.spec.whatwg.org/#example-rbs-push), [2](https://streams.spec.whatwg.org/#example-rbs-pull)) both make sure to have a respond call after controller.close() when used in byob-mode.)

Adding `controller.byobRequest?.respond(0);` after the `controller.close();` call in the https://github.com/denoland/deno/issues/14219#issuecomment-1090153325 example fixes it, and that works consistently in Deno, Chrome, and Node.

---

Given this, I think the fetch Response.body ReadableStream implementation in Deno is missing the byobRequest.respond/respondWithNewView call after the controller.close() call.

I searched for `type: "bytes"` in the Deno repo and I found 4 places where a `type: "bytes"` ReadableStream is created, and 3 of them have this issue.

[The implementation of Blob.stream()](https://github.com/denoland/deno/blob/57f7e07c13a1a692602022af4fc32c6ac352bb72/ext/web/09_file.js#L322) is an example of this issue. This could be solved by adding a `controller.byobRequest?.respond(0);` call after the close call, but since it's not making any use of user-provided buffers, it's probably better to just drop the `type: "bytes"` property instead so it doesn't have to work around bytes mode for no benefit.

The `readableStreamForRid` function at [ext/web/06_streams.js line 647](https://github.com/denoland/deno/blob/57f7e07c13a1a692602022af4fc32c6ac352bb72/ext/web/06_streams.js#L647) seems like a good correct example. Besides using respond(0) after `controller.close()`, it makes use of the user-provided buffer in `controller.byobRequest.view`, and it specifies the `autoAllocateChunkSize` property so that it always acts in byob mode (with `controller.byobRequest` non-null) and only needs one code path.

[ext/fetch/26_fetch.js#L101](https://github.com/denoland/deno/blob/57f7e07c13a1a692602022af4fc32c6ac352bb72/ext/fetch/26_fetch.js#L101) and [ext/http/01_http.js#L394](https://github.com/denoland/deno/blob/57f7e07c13a1a692602022af4fc32c6ac352bb72/ext/http/01_http.js#L394) both have the issue where they don't call respond(0) after close. But also they don't make use of any user-provided buffer, so they don't currently benefit from having `type: "bytes"` set. They could be made more consistent with `readableStreamForRid` in order to directly support user-provided buffers.

**Comment by crowlKats** [comment]
> in order to directly support user-provided buffers.
The reason why fetch & blob doesnt use user-provided buffers is because the spec doesnt use bytes readablestream yet

**Comment by Macil** [comment]
In that case, it seems like `type: "bytes"` should be removed from these three problem spots since the function of having it is to allow byob-mode readers. (Removing this would be consistent with Chrome which doesn't make fetch bodies be bytes type streams. `(await fetch("/")).body.getReader({ mode: "byob" })` in Chrome reveals this with a TypeError, and this change in Deno would make it act the same way.)

**Comment by Macil** [comment]
Just tested in 1.30.0 and it looks like this was solved for streams returned by `fetch`. I can see that they're now proper `type: "bytes"` streams that correctly handled byob-mode readers. (In ext/web/06_streams.js, in both places that `type: "bytes"` is used, the associated `pull` function now correctly uses the `controller.byobRequest` object as required by `type: "bytes"` streams.)

However, there are still two implementations of `type: "bytes"` streams where the `pull` function does not use the `controller.byobRequest` object at all, meaning that this bug still exists for those ReadableStreams and they will behave incorrectly if opened with a byob-mode reader. These two spots are in ext/flash/01_http.js and ext/web/09_file.js (in the implementation of `Blob.stream`). These spots could be fixed either by removing `type: "bytes"`, so they no longer incorrectly identify themselves as supporting byob-readers (this would be consistent with Chrome for `Blob.stream`), or by making them support byob-readers by using the `controller.byobRequest` object.

Here's some new sample code that shows this issue still existing in the Blob.stream method:

```ts
const blob = new Blob([new Uint8Array(12)]);
const reader = blob.stream().getReader({ mode: "byob" });

let buf = new Uint8Array(4096);
const result = await reader.read(buf);
console.log(result);

buf = new Uint8Array(result.value!.buffer);
const result2 = await reader.read(buf);
console.log(result2);
```

```
$ deno run blob_byob_fail.ts 
{
  value: Uint8Array(12) [
    0, 0, 0, 0, 0,
    0, 0, 0, 0, 0,
    0, 0
  ],
  done: false
}
error: Top-level await promise never resolved
const result2 = await reader.read(buf);
                ^
    at <anonymous> (file:///tmp/foo/blob_byob_fail.ts:9:17)
```

**Comment by bartlomieju** [comment]
@crowlKats please take a look

**Comment by mmastrac** [comment]
Appears to be working, feel free to re-open if it is still reproducible.
