### ISSUE TITLE
Add global `clear` function to the REPL?

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#14226]
Browsers have `console.clear()` available in the dev tools as `clear()`. Perhaps we should do the same as it's a bit more accessible?

Related to #12896 and I think this would be a bit nicer because it aligns with chrome and firefox.

https://discord.com/channels/684898665143206084/684911491035430919/961241552217325639

**Comment by bartlomieju** [comment]
Somewhat related to https://github.com/denoland/deno/issues/12896 ?
