### ISSUE TITLE
Deno.stdout.write does not write more than 16384 chars of a Uint8Array

### ISSUE THREAD

**Issue by dshick-nydig** [denoland/deno#14227]
## latest deno version in use

output `deno --version`:
```
deno 1.20.4 (release, aarch64-apple-darwin)
v8 10.0.139.6
typescript 4.6.2
```

---

## truncated output (THE BUG)

```typescript
// test-deno-stdout-write.ts
const test = "a".repeat(33000);
Deno.stdout.write(new TextEncoder().encode(test));
```
output `deno run test-deno-stdout-write.ts | wc -c`:
```
   16384
```

---

## TextEncoder.encode holds the full value

```typescript
// test-text-encoder.ts
const test = "a".repeat(33000);
console.log(new TextEncoder().encode(test));
```
output `deno run test-text-encoder.ts`:
```
Uint8Array(33000) [
  97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97,
  97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97,
  97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97,
  97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97,
  97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97,
  97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97,
  97, 97, 97, 97, 97, 97, 97, 97, 97, 97,
  ... 32900 more items
]
```

---

## console.log has no problem

```typescript
# test-console-log.ts
const test = "a".repeat(33000);
console.log(test)
```
output `deno run test-console-log.ts | wc -c`:
```
   33001
```

---

## node lts attempt

output `node --version`:
```
v16.14.0
```

---

## node process.stdout.write doesn't truncate

```javascript
// node-test.js
const test = "a".repeat(33000);
process.stdout.write(new TextEncoder().encode(test))
```
output `node node-test.js | wc -c`:
```
   33000
```

---

## Deno.writeAll(...) is fine (WORKAROUND)

```typescript
# test-deno-writeall.ts
const test = "a".repeat(33000);
await Deno.writeAll(Deno.stdout, new TextEncoder().encode(test))
```
output `deno run test-deno-writeall.ts | wc -c`:
```
   33000
```

**Comment by lucacasonato** [comment]
This is not a bug. `Writer#write` is a low level API that does not guarantee the entire passed buffer is written. `Writer#write` returns an integer `n` that specifies how many bytes were written (`0` <= `n` <= `buffer.byteLength`). To write the entire buffer, use `writeAll`.

**Comment by dshick-nydig** [comment]
Ah, fair enough. Thanks for the pointer! I completely missed the [notes in the docs mentioning as much](https://doc.deno.land/deno/stable/~/Deno.write). I guess at some point I saw an [example in the manual](https://deno.land/manual/examples/subprocess#communicating-with-subprocesses) and just ran with it, thinking it similar to what is available in node.

Seems even `writeAll` is deprecated in favor of https://deno.land/std/streams/conversion.ts

Thanks again.
