### ISSUE TITLE
AppVeyor does not recompile libdeno

### ISSUE THREAD

**Issue by kevinkassimo** [denoland/deno#1424]
This happens with #1407, #1411, and #1420 which blocks all of them from passing Windows CI (while travis tests all passed)

Added as an issue so that someone familiar with windows might want to take a look...

**Comment by ry** [comment]
Actually @piscisaureus is investigating this now. There appears to be a problem with sccache.  I'm not sure if it was the same issue you were experiencing.

**Comment by kevinkassimo** [comment]
@ry Likely. Okay I'll leave it open.
