### ISSUE TITLE
lsp: support per workspace folder deno.jsonc

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#14245]
There are several scenarios where being able to have one workspace in the editor, but a different deno.jsonc apply is becoming increasingly necessary. When combining front-end and back end code as part of the same project for example.

The challenge is a couple fold, mostly with resolving config files on a workspace folder perspective and managing those config files depending on what specifier is being queried. In addition the TS language server has the plumbing for type checking on a "project" basis, but our communication with it does not currently account for that, which means we would need to re-plumb that.

It us a non-trivial piece of work but I have ideas on an approach.

Ref: https://github.com/denoland/vscode_deno/issues/787

**Comment by swandir** [comment]
Would it support config auto-discovery?

And could it be made to work without needing an explicit multi-root workspace? From the user's perspective it'd be awesome to just open a directory and see that everything works with no additional config.

**Comment by kitsonk** [comment]
I'm not totally sure at this point.  We have to figure out a few things first, like how to juggle it.  It maybe something that gets delivered incrementally, enhancing as we go along.
