### ISSUE TITLE
deno compile ignores import_map.json specified in deno.json

### ISSUE THREAD

**Issue by redxtech** [denoland/deno#14246]
Hey! I have a smallish project that I'm working on, and when I compile the command to make a binary, it seems to ignore the `import_map.json`. I have an `"importMap"` key in my `deno.json`, but it doesn't pick it up. When I use `--import-map ./import_map.json` it works, but it then gives me a warning that the `"importMap"` key is being ignored. It also works completely fine when I run with `deno run`, and I don't have to use the `--import-map` option.

Here are the commands I used:

Compile: `deno compile --allow-env --allow-net --allow-read ./src/main.ts`
The compilation succeeds, but when I try to run the binary with `./main` I get this result: `error: Relative import path "dotenv/mod.ts" not prefixed with / or ./ or ../ from "file:///home/redxtech/Code/project/src/main.ts"`

Compile with args: `deno compile --allow-env --allow-net --allow-read --import-map ./import_map.json ./src/main.ts`
Warning: `Warning the configuration file "file:///home/redxtech/Code/project/deno.json" contains an entry for "importMap" that is being ignored.`

Run: `deno run --allow-env --allow-net --allow-read ./src/main.ts`
Result: works as expected.

Output of `deno --version`:
```
deno 1.20.5 (release, x86_64-unknown-linux-gnu)
v8 10.0.139.6
typescript 4.6.2
```

Here's my `./deno.json` (`lint` & `fmt` fields removed):
```json
{
  "compilerOptions": {
    "allowJs": false,
    "lib": ["deno.window", "es2021"],
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "strict": true
  },
  "importMap": "./import_map.json"
}
```
and my `./import_map.json`:
```json
{
   "imports": {
      "dotenv/": "https://deno.land/x/dotenv@v1.0.1/",
      "kall/": "https://denopkg.com/olaven/kall@v1.0.8/",
      "std/": "https://deno.land/std@0.133.0/"
   }
}

```

Here's the relevant part of `./src/main.ts` file where the imports are used:
```ts
import { config as dotEnvConfig } from 'dotenv/mod.ts';
```

If you need any more info I would be happy to provide it.

**Comment by marcosadriano05** [comment]
With me, when i run: `deno compile --unstable --allow-net --allow-read --allow-write ./src/main/server.ts`, the project compiles to `server` file.
But when i run `./server`, the output is: `error: Module not found`.

In `deno.json`:
`{ "importMap": "./import_map.json" }`

My import_map.json:
`{
  "imports": {
    "/": "./",
    "./": "./"
  }
}`

How i use the imports (exemple): `import { app } from "/src/main/app.ts";`

The `test` and `run` commands work fine.

Deno version: 1.21.1

**Comment by peanutbother** [comment]
I could observe that running `deno compile -c deno.json --import-map=import_map.json main.ts` creates a working binary However deno warns about `importMap` being overridden by the command.
The config works for `deno task start` like it should so the issue might have to do with deno not applying `importMap` of `deno.json`.

deno.json: 
```json
{
  "tasks": {
    "start": "deno run -A --watch main.ts",
    "build": "deno compile -c deno.json --import-map=import_map.json main.ts"
  },
  "importMap": "./import_map.json"
}
```

shell: 
>$> deno task build
>
> Warning deno task is unstable and may drastically change in the future
> Task build deno compile -c deno.json --import-map=import_map.json main.ts
> Warning the configuration file "file:///home/peanutbother/workspace/denotest/deno.json" contains an entry for "importMap" that is being ignored.
> Check file:///home/peanutbother/workspace/denotest/main.ts
> Compile file:///home/peanutbother/workspace/denotest/main.ts
> Emit denotest

**Comment by liquiddandruff** [comment]
I can confirm the above that `deno compile` is not respecting the import_map in `deno.json`, despite it reporting it is being ignored.

Can be reproduced with the sample project https://fresh.deno.dev/

```
$ deno --version
deno 1.23.1 (release, x86_64-apple-darwin)
v8 10.4.132.8
typescript 4.7.2
```

## Does not work

```
$ deno compile -A -c deno.json main.ts
Check file:///Users/variant23/repos/deno-app/main.ts
Compile file:///Users/variant23/repos/deno-app/main.ts
Emit deno-app
$ ./deno-app
error: Relative import path "$fresh/server.ts" not prefixed with / or ./ or ../ from "file:///Users/variant23/repos/deno-app/main.ts"
```

## Works

```
$ deno compile -A --import-map=./import_map.json main.ts
Warning the configuration file "file:///<blah>/repos/deno-app/deno.json" contains an entry for "importMap" that is being ignored.
Check file:///<blah>/repos/deno-app/main.ts
Compile file:///<blah>/repos/deno-app/main.ts
Emit deno-app
$ ./deno-app
Server listening on http://localhost:8000

```
