### ISSUE TITLE
All manual links in help text should include version number

### ISSUE THREAD

**Issue by ry** [denoland/deno#14250]
For example, the `--config` help text includes the link https://deno.land/manual/getting_started/configuration_file but ought to specify the current version: https://deno.land/manual@v1.20.5/getting_started/configuration_file

hint use `crate::version::deno()`

Examples of where it should be updated:
https://github.com/denoland/deno/blob/a4eee007ef28f918db9165c52a19bc30bd65bad3/cli/flags.rs#L457
https://github.com/denoland/deno/blob/a4eee007ef28f918db9165c52a19bc30bd65bad3/cli/flags.rs#L1205
https://github.com/denoland/deno/blob/a4eee007ef28f918db9165c52a19bc30bd65bad3/cli/flags.rs#L1764

**Comment by mrkldshv** [comment]
I'd like to work on this!

**Comment by bartlomieju** [comment]
> I'd like to work on this!

Please do!
