### ISSUE TITLE
Consider adding config for `deno test` to deno.jsonc

### ISSUE THREAD

**Issue by johnspurlock** [denoland/deno#14263]
Wanted to encode my `--ignore` paths into a config file yesterday when I noticed that configuring `deno test` in the configuration file is not supported yet!

Would be great to have a new top-level `"test"` config object alongside `"lint"` and `"fmt"`.

Thanks!

**Comment by dsherret** [comment]
I've wanted this feature too for ignoring tests. Right now I've been creating a `deno task test`, but it's not ideal because then I have to remember to run that instead.

**Comment by bartlomieju** [comment]
I think it makes sense and opens up a lot of interesting possibilities in the future. 

Which options from the CLI should we support in the first pass?
