### ISSUE TITLE
Add support for 'Trust on First Use' for TLS certificates

### ISSUE THREAD

**Issue by andre4ik3** [denoland/deno#14277]
Currently, connecting to hosts with certificates that are not signed (but otherwise valid) will throw an error, and require the `--unsafely-treat-insecure-origin-as-secure`. I think there should be an option, in `Deno.connectTls()` function, called `tofu` or `trustOnFirstUse`. It will be a boolean that is by default `false`. If `true`, the request will be made, and the certificate will still be checked, except for the signed by CA requirement. It should then be cached in some sort of long-term storage, where any subsequent connections to this domain will require that specific certificate that was received on first connection. If there is a mismatch, an error is thrown.

**Comment by SyrupThinker** [comment]
Alternatively this could also be solved in a more general way by taking inspiration from .NET's `RemoteCertificateValidationCallback`[^1], Java's `TrustManager`[^2] and Go's `VerifyPeerCertificate`+`InsecureSkipVerify`[^3].
They allow the caller to define a callback that verifies the peer's provided certificate chain.
This can then be used to implement, for example, the TOFU mechanism.

[^1]: https://docs.microsoft.com/en-us/dotnet/api/system.net.security.sslstream.-ctor?view=net-6.0#system-net-security-sslstream-ctor(system-io-stream-system-boolean-system-net-security-remotecertificatevalidationcallback-system-net-security-localcertificateselectioncallback)
[^2]: https://docs.oracle.com/en/java/javase/17/docs/api/java.base/javax/net/ssl/SSLContext.html#init(javax.net.ssl.KeyManager%5B%5D,javax.net.ssl.TrustManager%5B%5D,java.security.SecureRandom)
[^3]: https://pkg.go.dev/crypto/tls#Config

**Comment by andre4ik3** [comment]
Yeah, that would be better and more customizable, although wouldn't work out of the box.
My use case here is for domains on a local network over HTTPS (with self-signed certs) or [Gemini protocol](https://gemini.circumlunar.space) servers.
