### ISSUE TITLE
Add support for `compilerOptions.paths`

### ISSUE THREAD

**Issue by Industrial** [denoland/deno#14275]
Hi.

I would like to have support for the `paths` options in the `compilerOptions` in Deno. This option allows you to make all imports absolute instead of relative and you'll never have to think about howmany levels of `../../../` again.

https://www.typescriptlang.org/tsconfig#paths

gr,

Tom

**Comment by AnInternetTroll** [comment]
Check out import maps https://deno.land/manual@v1.20.5/linking_to_external_code/import_maps

**Comment by Industrial** [comment]
Ah, I didn't understand that I could end them with slashes for namespacing and that it worked for local paths as well. Thanks!
