### ISSUE TITLE
`deno upgrade` overwrites the old executable path, regardless of filetype (e.g. symlink)

### ISSUE THREAD

**Issue by filmaj** [denoland/deno#14272]
First: thank you to all `deno` maintainers for the excellent runtime! What a fantastic project, delightful to work with, appreciate everything you all do.

I had a relatively custom setup on my machine, due to some specific permissions configuration that my corporate overlords set up on my work laptop. Essentially the `deno` available on my `$PATH` was a symlink that pointed to the `deno` I installed using the `curl install script | bash` method described on deno.land, with the addition of using the [`DENO_INSTALL` environment variable](https://deno.land/x/install/install.sh#L28) to customize the location of where the binary is placed.

After installing `deno` using the above method, if I, at a later date when a new `deno` version is released, run `deno upgrade`, it looks like the [upgrade will overwrite the location of the existing `deno` entry available on the `$PATH`](https://github.com/denoland/deno/blob/1c37ac33526dc45ad0b3f83ca8294dbb55548096/cli/tools/upgrade.rs#L129-L137) - regardless of if that `deno` is a symlink or not.

It would be swell if the `deno upgrade` command followed symlinks in order to determine what the "old path" is for the `deno` executable. I am a total Rust noob so not sure where to start, but if someone more knowledgeable than I can offer tips / guidance, I can try my hand at writing up a pull request for this.

Cheers!

**Comment by GJZwiers** [comment]
Can you share a bit more about your setup? I would be open to work on this, but I'm having some trouble reproducing the issue.

I'm taking the following steps right now:

- install deno at a custom path: `curl -fsSL https://deno.land/install.sh | DENO_INSTALL=/home/gjzwiers/target/ sh`
- create a symlink from the default Deno exec path to the custom path: `ln -s /home/gjzwiers/target/bin/deno /home/gjzwiers/.deno/bin/deno`
- add symlink to $PATH in `/home/gjzwiers/.bashrc`:  `export PATH="/home/gjzwiers/.deno/bin:$PATH"`
- run `deno upgrade`

Afterwards, the symlink is still on $PATH and pointing to the custom installation path. `deno --version` shows the upgraded version as well. Is this somewhat similar to what you are doing on your machine?
