### ISSUE TITLE
Uncaught websocket error - bad resource ID

### ISSUE THREAD

**Issue by jakeg** [denoland/deno#14280]
```
error: Uncaught (in promise) BadResource: Bad resource ID
    at async deno:ext/websocket/01_websocket.js:465:11
```

Running on latest deno, version 1.20.5 so it's coming from this line:

https://github.com/denoland/deno/blob/d2c09408380191721ba7dfd971f802f5639eb1f7/ext/websocket/01_websocket.js#L465

I'm assuming maybe I'm trying to send a message to a websocket that's just closed?

**Comment by crowlKats** [comment]
@jakeg do you have reproducible code?

**Comment by jakeg** [comment]
Afraid not easily. I managed to get it to happen twice while doing some throttling via Chrome's dev tools. Assume it's related to a timeout.

I assume related to #14283 ?

**Comment by crowlKats** [comment]
It might be related, though not fully sure yet. will look into it once I am back

**Comment by jtoppine** [comment]
Are you sure you are catching all socket send() calls? This happened to me a lot, especially on "production" (demo) servers. I just made sure to `try { await ws.send(...); } catch(er) { ... };` everywhere, and it seems to have solved those issues. (tbh not even sure if send is async, the await may not be needed).

Indeed it appears to happen when sending to a socket that is already closed or maybe not yet acknowledged to be closed, but in unresponsive state - like when the client internet connection is dropped or unstable. It can often be triggered by repeatedly, aggressively refreshing a client browser, or detaching a physical cable connection. I might be wrong but I suspect it may happen also when a client machine goes standby, which may briefly leave the connection in limbo, unlike when a browser or tab is closed, which may result in more graceful connection closure.  Just some observations and guesses I have made trying to track down these very undeterministic issues for some time.

**Comment by crowlKats** [comment]
> tbh not even sure if send is async, the await may not be needed

It isn't, the `WebSocket` API isn't promise based, but event based. Any errors caused asynchronously should be emitted through the `error` event.

**Comment by jakeg** [comment]
This is now a recurring problem for me in production. Yes, I'm doing a `try { ... } catch { ...}` around any `socket.send()`.

**Comment by crowlKats** [comment]
@jakeg sorry about this, I am currently looking into the stockpile of websocket issues. I just merged a PR that fixes a bunch of issues, could you check against a canary build, and tell me if it still persists?

**Comment by jakeg** [comment]
On Saturday I removed my usage of Oak to just using my own basic router instead, and I haven't had any crashes since. I guess the issue is probably in Oak rather than Deno core.

**Comment by crowlKats** [comment]
@jakeg I see. would there be any chance to get a reproducible case with your previous oak setup?

**Comment by jakeg** [comment]
Spoke too soon. Still getting the same exact error while using Deno without Oak. I'm not really sure how to provide reproducible code though, and I'd prefer not to use a non-released version of Deno in production (I haven't been able to reproduce the crashes in development).

**Comment by crowlKats** [comment]
tomorrow a new version will be out, so hopefully that will fix this issue

**Comment by jakeg** [comment]
I've just put `v1.22.1` live in production and will let you know on here if I see any more crashes. Fingers crossed! The other one I was getting today was `error: Uncaught (in promise) Error: IO error: Broken pipe (os error 32)` so hopefully it fixes that too.

**Comment by jakeg** [comment]
I'm still getting this error (bad resource ID) with v1.22.1

**Comment by crowlKats** [comment]
dammit... i will investigate this once again

**Comment by jakeg** [comment]
I've been looking at the code in `01_websocket.js`...

```js
[_serverHandleIdleTimeout]() {
  if (this[_idleTimeoutDuration]) {
    clearTimeout(this[_idleTimeoutTimeout]);
    this[_idleTimeoutTimeout] = setTimeout(async () => {
      await core.opAsync("op_ws_send", this[_rid], {
        kind: "ping",
      });
      // ...
    }, (this[_idleTimeoutDuration] / 2) * 1000);
  }
}
```

I'm thinking what if before doing the rust call to `op_ws_send` we first check `if (this[_readyState] === OPEN)` ? The problem here is surely that the connection has been lost between setting the timeout and when we're trying to send a new ping frame.

And/or is there a way to edit the `op_ws_send` rust function in `lib.rs` to not fatally error in  if the connection is closed/there's a bad resource ID?

**Comment by crowlKats** [comment]
That part of the code is only if you use the websocket server, not the client. 



> And/or is there a way to edit the `op_ws_send` rust function in `lib.rs` to not fatally error in if the connection is closed/there's a bad resource ID?

It would be possible, but thats definitively not the right solution

**Comment by jakeg** [comment]
Yes, that's what I am doing, using Deno as a websocket server with `Deno.UpgradeWebSocket()`

**Comment by crowlKats** [comment]
Ah i see

**Comment by jakeg** [comment]
I was getting this error again a lot today. I'm at the stage where I may have to switch to Node soon if there's not a resolution, as it crashes the server every time it happens. Any progress at all?

**Comment by crowlKats** [comment]
yes, next release will have a fix. will open PR in the next hour

**Comment by jakeg** [comment]
Thanks @crowlKats . Have just upgraded to `v1.22.3` and will report if I experience any further crashing.

**Comment by jakeg** [comment]
Haven't had a single crash since upgrading so am assuming this has fixed this issue. Thanks @crowlKats !
