### ISSUE TITLE
websocket_server_idletimeout test is broken

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#14283]
`websocket_server_idletimeout` is a Rust integration test, that uses `deno test` subcommand even though there is no test registered there. The test passed fine in this case, but if we change subcommand to `deno run` it hangs. This is caused by the fact that `op_ws_next_event` op never resolves:
```
        "op_ws_next_event": {
            "opsDispatched": 1,
            "opsDispatchedSync": 0,
            "opsDispatchedAsync": 1,
            "opsDispatchedAsyncUnref": 0,
            "opsCompleted": 0,
            "opsCompletedSync": 0,
            "opsCompletedAsync": 0,
            "opsCompletedAsyncUnref": 0,
            "bytesSentControl": 0,
            "bytesSentData": 0,
            "bytesReceived": 0
        },
```

CC @crowlKats

**Comment by bartlomieju** [comment]
Disabled this test in https://github.com/denoland/deno/pull/14271

**Comment by crowlKats** [comment]
stuck on #283

**Comment by littledivy** [comment]
@crowlKats `fastwebsockets` supports disabling auto-pongs https://docs.rs/fastwebsockets/latest/fastwebsockets/struct.WebSocket.html#method.set_auto_pong

**Comment by littledivy** [comment]
Test was enabled: https://github.com/denoland/deno/blob/33dc5d262288f4efae3077978f37f22338568b35/cli/tests/integration/run_tests.rs#L4283
