### ISSUE TITLE
It's wrong to transform all exceptions thrown during structured cloning to `DataCloneError` exceptions

### ISSUE THREAD

**Issue by andreubotella** [denoland/deno#14296]
Deno's implementation of the structured clone algorithm is divided into a JS part, and a native part which doesn't have access to `DOMException`. Since serialization errors must be represented by throwing a `DataCloneError` `DOMException`, the native part [throws a `TypeError` with the required message](https://github.com/denoland/deno/blob/main/core/bindings.rs#L958), and the JS part [rethrows any exception thrown by the serialization as a `DataCloneError`](https://github.com/denoland/deno/blob/main/ext/web/13_message_port.js#L278).

As shown by web-platform-tests/wpt#33663, however, this behavior is wrong, because exceptions thrown from an object's property getters should be surfaced without changes:

```js
const testObject = {
  get testProperty() {
    throw new Error();
  }
};
try {
  structuredClone(testObject);
} catch(err) {
  console.log(err instanceof DOMException);  // should be false; Deno prints true
}
```

One way to fix this would be to have an optional third parameter to the internal API `Deno.core.serialize` that would be a `(string) => any` callback, returning the exception to throw. Or possibly `(string) => never`, having the callback itself throw the exception.

**Comment by karol-janik** [comment]
I'd like to work on this!

**Comment by mrkldshv** [comment]
Hey @andreubotella! Are you working on this issue? Is it available for grabs?

**Comment by andreubotella** [comment]
> Hey @andreubotella! Are you working on this issue? Is it available for grabs?

@karol-janik said they'd like to work on it, but that was almost a month ago, so feel free to take it I guess.

**Comment by mrkldshv** [comment]
Right, sorry. I've tagged you by mistake. Meant to tag @karol-janik.
