### ISSUE TITLE
Writing results of `Deno.bench` / checking against previous runs

### ISSUE THREAD

**Issue by harrysolovay** [denoland/deno#14295]
Is there a standard approach to utilizing `Deno.bench` to safeguard against performance degradation without manually comparing output with that of previous runs?

Currently, I execute `deno bench bench.ts > bench_results` and pipe its stdout into a file, which I then commit. Upon making changes, I re-run this command. I then manually compare changes to `bench_results` (in a given PR). Ideally, I would automate this process / turn it into a GH workflow / check. I could not find mention of a solution [in the manual's Benchmarking section](https://deno.land/manual@v1.20.6/tools/benchmarker)... and I'd rather not parse the bencher's output, as I'd imagine it may change in future versions of Deno. Any suggestions?

**Comment by bartlomieju** [comment]
> Is there a standard approach to utilizing Deno.bench to safeguard against performance degradation without manually comparing output with that of previous runs?

Not yet, it was proposed by @evanwashere who wanted to provide a solution to this problem. But I'm not sure what's the status of that work.

**Comment by harrysolovay** [comment]
Related note for posterity: I see that [the previous std approach to benching](https://deno.land/std@0.135.0/testing/bench.ts#L151) is deprecated. This approach allowed for in-memory access to the bench data (simplifies serializing that data and then checking against future runs). Anyways, I'm very excited to see how this API progresses!

**Comment by evanwashere** [comment]
There is a mock design for it, but it will likely only be implemented as a follow-up to #14305 
![](https://cdn.discordapp.com/attachments/684911491035430919/951927309877788733/unknown.png)

**Comment by bartlomieju** [comment]
Does https://github.com/denoland/deno/pull/14305 solve this issue @harrysolovay?

**Comment by harrysolovay** [comment]
Somewhat. I was hoping for an API comparable to that of snapshot testing. I could imagine something along the lines of...

```ts
import { assertBenchGte } from "...";

Deno.test("Benchmarks are as good or better", (t) => {
  assertBenchGte(t, () => doTheThing());
});
```

**Comment by harrysolovay** [comment]
Pinging this issue to stave off the stale bot.

**Comment by harrysolovay** [comment]
<warding off the stale bot>

**Comment by Morantron** [comment]
I think a `--reporter` flag that allows you to chose between `console` (the current one) and `json` would be ideal.

**Comment by bartlomieju** [comment]
`deno bench` now supports the `--json` option which seems to be enough to solve the issue at hand.
