### ISSUE TITLE
python install script does not add '.exe' to windows binary - "'deno' is not recognized as an internal or external command"

### ISSUE THREAD

**Issue by matt1** [denoland/deno#1429]
First time user - clean install on Windows 10 (1803) using python command:

`curl -L https://deno.land/x/install/install.py | python`

Install script installed into `c:\Users\<user>\.deno` with a `deno` binary in `c:\Users\<user>\.deno\bin`.  Note that the `deno` binary was not called `deno.exe` - i.e. it was missing the `.exe` extension.

I set up the PATH environment entry and tried running deno but get the following error:

```
C:\Users\<user>\.deno\bin>deno
'deno' is not recognized as an internal or external command,
operable program or batch file.
```

If I add the `.exe` extension, windows finds and runs deno without any problems.   I do not know if there is a `chmod +x` equivalent for Windows 10 (is it really still relying on file extensions?) that should be done during the install process.

**Comment by kt3k** [comment]
I think python install script doesn't support windows. Windows users should use the following commnad:

```
iex (iwr https://deno.land/x/install/install.ps1)
```

Refs: https://github.com/denoland/deno_install

**Comment by kt3k** [comment]
I found the document at deno.land doesn't mention about windows install command. Probably that's a problem?

**Comment by hayd** [comment]
It should be supported, I think the fix is that [this line](https://github.com/denoland/deno_install/blob/b6b938f7446b2656f59f6526deb35fe87bbf3f84/install.py#L84) should be deno.exe on windows.

**Comment by bartlomieju** [comment]
Hey @matt1 if you still experience problems, please report issue in [deno_install repo](https://github.com/denoland/deno_install).

CC @ry

**Comment by ry** [comment]
python install deprecated. see deno_install linked above.
