### ISSUE TITLE
Prefix module paths in test output with `./`

### ISSUE THREAD

**Issue by nayeemrmn** [denoland/deno#14300]
This makes the ctrl+click behaviour on VSCode more consistent for single-component paths, e.g. if I ctrl+click `temp.ts` in the terminal, it opens a dropdown menu but `./temp.ts` goes straight to the file.

**Comment by bartlomieju** [comment]
> This makes the ctrl+click behaviour on VSCode more consistent for single-component paths, e.g. if I ctrl+click temp.ts in the terminal, it opens a dropdown menu but ./temp.ts goes straight to the file.

Interesting, that works fine in my terminal, but let's apply your suggestion to make it consistent

**Comment by nayeemrmn** [comment]
Yeah I get this 
![image](https://user-images.githubusercontent.com/29990554/163687016-9389532f-48fb-4431-b28e-3c13da4106e2.png) vs 
![image](https://user-images.githubusercontent.com/29990554/163687052-648f57a1-0a99-4a50-a217-fdd731a4bd38.png)
