### ISSUE TITLE
Gray color of file names in tests is barely readable on dark backgrounds

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#14303]
![image](https://user-images.githubusercontent.com/7829205/163691725-ccf2de3e-0c8c-4fd6-9bf3-e0f929350633.png)

**Comment by bartlomieju** [comment]
This is very subjective IMO - in your terminal settings the regular font is very dim too, which makes it hard to read as well. I believe there should be visual distinction between output with different importance, but the truth is that everyone can tweak their terminal to whatever colors they want. Or in other words can't make everyone happy.

**Comment by lucacasonato** [comment]
This screenshot is from GH Actions output when GH is in regular dark mode (very common thus). Also we have a written precedent somewhere that we want all CLI output should be readable on both light and dark background - I unfortunately can not find the note right now though. Maybe @ry remembers?

**Comment by bartlomieju** [comment]
> This screenshot is from GH Actions output when GH is in regular dark mode (very common thus). Also we have a written precedent somewhere that we want all CLI output should be readable on both light and dark background - I unfortunately can not find the note right now though. Maybe @ry remembers?

Okay, this is a valid point. Let's change `colors::gray` to be some kind of "lighter" gray, but still different that regular color?

**Comment by bartlomieju** [comment]
Would this color work better?

![Screenshot 2022-04-17 at 22 54 06](https://user-images.githubusercontent.com/13602871/163731752-15459980-1fa8-4e0f-9ca9-05c50e769f46.png)
<img width="399" alt="Screenshot 2022-04-17 at 22 54 10" src="https://user-images.githubusercontent.com/13602871/163731754-28ddde0f-3522-4ed5-9dfe-31b3ddbb74c5.png">
![Screenshot 2022-04-17 at 22 57 52](https://user-images.githubusercontent.com/13602871/163731776-981f2bf3-d582-4a6e-9ba5-8a9ac6c36ae1.png)

**Comment by lucacasonato** [comment]
Looks much better!
