### ISSUE TITLE
Should "deno test" capture user output by default?

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#14308]
With https://github.com/denoland/deno/commit/244926e83c7d3cae3c3ae3fc14e996e3066da43e `deno test` is able to discern that output comes the user code and thus potentially capture it.

In https://github.com/denoland/deno/pull/14262#issuecomment-1100753401 @lucacasonato suggests that we should capture the output by default (similar to Rust) and disable this capturing if `--nocapture` flag is present. When @dsherret and I worked on the above commit, we did consider it, but both of us prefer the output is not captured by default, so we just left it as is.

This warrants some discussion and getting feedback from community.

**Comment by dsherret** [comment]
I think the default should be to display it and then the user can do `--quiet` to not display it. I think the majority of code does not output to stdout or stderr and if it does it's often a bug (that the test runner hides from being seen when capturing) or most often done so the developer can do "print debugging". It can be confusing when nothing outputs in these cases when capturing especially as a beginner (I very often add a `eprintln` statement and then forget to run with `-- --nocapture`... I wish `--nocapture` was the default).

**Comment by bartlomieju** [comment]
I agree, I think `deno test` should respect `--quiet` flag and in such case hide and buffer the output only printing it if the test case errors.

**Comment by bcheidemann** [comment]
I agree it should output by default and respect the --quiet flag. It would be nice if this could be specified on a per test basis e.g.

```ts
Deno.test(
  "quiet test",
  { quiet: true },
  () = {
    // --snip--
  }
);
```

This is because sometimes it is not possible to avoid your test polluting stdout or stderr - like when relying on 3rd party dependencies.

Is this possible?

**Comment by codehz** [comment]
More thought: what about log outside of Deno.test

**Comment by andykais** [comment]
one more thought, itd be great to have a redirect for user output. Something like `deno test --console-output=my-file.txt`. Ideally I want all the output from a test in one place, I find delineated output hard to read. An added benefit is that I could open a file descriptor for user output, in a new terminal, or `tail -F` the file being written to, and have both deno output and user output happening simultaneously in two terminals. I can imagine vscode could handle something like this very nicely too, like a tab for deno test output, and a tab for user test output.

**Comment by bcheidemann** [comment]
> More thought: what about log outside of Deno.test, I think it should be hide by default

That raises an interesting question... What happens to the output of `assertSnapshot`. Currently, when a test file finishes running in update mode, it logs:

```
 > X snapshots updated.
```

I would think that we'd want to preserve this and capturing logs could break this. 🤔

**Comment by haikyuu** [comment]
Here are some ideas that would be nice to have
- show the file and line responsible fornthe output
- The ability to navigate output on a test by test basis in the vscode extension
- Actually display the output as rich interactive Javascript objects yhe user can play with in a repl like the browser console or the debugger mode. (also in the extension)

**Comment by aaronhuggins** [comment]
> especially as a beginner (In Rust, I very often add a `eprintln` statement and then forget to run with `-- --nocapture`... I wish `--nocapture` was the default).

I concur that `--nocapture` should be the default. In most test runners I've used (in .NET, Java, JS/TS), it's been expected that output was either a bug or part of the required test behavior. In either case, output was a useful indicator to the developer.

Given this, I was really confused when Rust was not printing my lines in a test a week ago. I'm absolutely with @dsherret on this one.

**Comment by dsherret** [comment]
Oh, this was essentially implemented already. The test output is captured and displayed nicely now.
