### ISSUE TITLE
Avoid using primordials `JSONStringify`

### ISSUE THREAD

**Issue by petamoriken** [denoland/deno#14310]
It is easy to interrupt the process if the value given to `JSON.stringify` is an object.

```js
Object.prototype.toJSON = () => "foo";

JSON.stringify({ bar: "bar" }); // '"foo"';
```

FYI: https://tc39.es/ecma262/#sec-serializejsonproperty

**Comment by CGQAQ** [comment]
![image](https://user-images.githubusercontent.com/15936231/164625212-a65da5c2-b9ce-4b68-86c5-a9b915781edb.png)

but the output is correct

**Comment by bartlomieju** [comment]
@petamoriken what are you suggesting here?

**Comment by petamoriken** [comment]
I think that using `JSONStringify` in primordials is affected if `Object.prototype` is changed by the user, so we need to work around this by using V8's API.

**Comment by petamoriken** [comment]
I tried the following impl, but it does not work if a non-writable `toJSON` method is added to `Object.prototype`.

```js
// Ignoring Object.prototype.toJSON if it is given.
primordials.SafeJSONStringify = (value, replacer, space) => {
  if (
    value === null ||
    typeof value !== "object" ||
    !ReflectHas(ObjectPrototype, "toJSON")
  ) {
    return JSONStringify(value, replacer, space);
  }

  const toJSON = ObjectPrototype.toJSON;
   ObjectPrototype.toJSON = null;
  try {
    return JSONStringify(value, replacer, space);
  } finally {
    ObjectPrototype.toJSON = toJSON;
  }
};
```

Perhaps an impl by `ShadowRealm` is needed, but it is not there yet.

**Comment by petamoriken** [comment]
It seems that this is not a issue for Deno, because the parts of Deno's internal code using `JSONStringify` are basically **in compliance with the specification**, For example, [the Fetch Standard specifies the use of `%JSON.stringify%`](https://infra.spec.whatwg.org/#serialize-a-javascript-value-to-a-json-string).

In other words, the result of the following code is strange, but it is in compliance with the specification.

```ts
Object.prototype.toJSON = () => ({ foo: "foo" });

const response = Response.json({ bar: "bar" });
console.log(await response.json()); // { foo: "foo" }
```

I close this issue.
