### ISSUE TITLE
Feature Request: Auto path import update

### ISSUE THREAD

**Issue by pouyakary** [denoland/deno#14316]
TypeScript &mdash; for a very long time now &mdash; has this feature, which; once you rename a file or directory, all the other files referring to it will be updated and you no longer have to fix a ton of broken import path errors. I think it could be really awesome to have this within deno. I wish I could implemented it but I have no idea where to start and where to implement it.

**Comment by elliothimmelfarb** [comment]
I'm encountering this missing feature as well and would like to bump this issue.

**Comment by CalvinWilkinson** [comment]
I agree.   It would be fantastic to have the imports auto-updated!! 😀

**Comment by nayeemrmn** [comment]
Addressed by #20245. Will release with 1.37 next Tuesday.

**Comment by CalvinWilkinson** [comment]
Yippy!!
