### ISSUE TITLE
Deno.test with output: Show ok on the same line as the test name

### ISSUE THREAD

**Issue by AnInternetTroll** [denoland/deno#14315]
It would be nice for the "ok" to be shown on the same line as the test name. Here it feels like the "ok" is disconnected from the test, and the test name is incomplete
![image](https://user-images.githubusercontent.com/40470127/163869166-1df09ab0-e024-4c6b-86e6-3d0684cc3675.png)

**Comment by nayeemrmn** [comment]
We should apply this if there is anything in between the test start and result, including sub-steps as well.
