### ISSUE TITLE
Windows build failed with lld-link error

### ISSUE THREAD

**Issue by prathameshnetake** [denoland/deno#1433]
<img width="833" alt="error" src="https://user-images.githubusercontent.com/4309729/50557513-f227b280-0d0b-11e9-85a8-e510038b1295.png">
 
lld-link error while building in windows with tools\build.py

system has

- python running 2.7.15
- windows sdk installed 10.0.17763.132 and debug tool is enabled
- ccache is in the system path
- node 11.4.0 installed

**Comment by bartlomieju** [comment]
@prathameshnetake do you still experience this issue with newest release?

**Comment by bartlomieju** [comment]
CC @ry this issue is stale

**Comment by prathameshnetake** [comment]
Sorry for late reply @bartlomieju. Yes this issue is solved and no longer replicating.
