### ISSUE TITLE
Deno panicked with Deno.resolveDns trying to resolve NameServer(NS)

### ISSUE THREAD

**Issue by Antonio476587** [denoland/deno#14355]
Command to reproduce the problem:
await Deno.resolveDns("deno.land","NS")

=========================Message Error===================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 1.19.3
Args: ["deno"]

thread 'main' panicked at 'not yet implemented', /home/runner/work/deno/deno/ext/net/ops.rs:736:12
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by dsherret** [comment]
Looks like it's not implemented.

https://github.com/denoland/deno/blob/2724235ec798f1fbf8fb5bd291615987ac4b919e/ext/net/ops.rs#L754

It panicking instead of giving a descriptive error seems like a bug.

**Comment by randomicon00** [comment]
So, for the additional `RecordType` variants that are not supported should we simply print an error instead of panicking?
