### ISSUE TITLE
Add `navigator.userAgent`

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#14362]
Cloudflare Workers has it.

**Comment by bartlomieju** [comment]
This seems like a good first issue too

**Comment by randomicon00** [comment]
Hi @lucacasonato, can I work on it if it is available?

**Comment by lucacasonato** [comment]
@randomicon00 Sure! To do this, you will want to
1. plumb the user agent from Rust https://github.com/denoland/deno/blob/a64e63c3614b98aa2b51fb6b7ef4e30251e03111/cli/version.rs#L17-L19
2. through the runtime bootstrap function https://github.com/denoland/deno/blob/a64e63c3614b98aa2b51fb6b7ef4e30251e03111/runtime/js/99_main.js#L532 invoked from rust here https://github.com/denoland/deno/blob/a64e63c3614b98aa2b51fb6b7ef4e30251e03111/runtime/worker.rs#L184-L189
3. onto `navigator` which is defined here https://github.com/denoland/deno/blob/a64e63c3614b98aa2b51fb6b7ef4e30251e03111/runtime/js/99_main.js#L295

**Comment by jesselawson** [comment]
I think we can close this now that #14415 has been merged.

**Comment by cjihrig** [comment]
Thanks @jesselawson. I'll close this out.

**Comment by jimmywarting** [comment]
i tried relying on globalThis.navigator.userAgent, but it was undefined in WorkerNavigator scope.
is it expected or just missing?

**Comment by bartlomieju** [comment]
> i tried relying on globalThis.navigator.userAgent, but it was undefined in WorkerNavigator scope.
> 
> is it expected or just missing?

It's been fixed recently and will be released tonight in V1.37.0
