### ISSUE TITLE
Should `Deno.resolveDns` handle error instead of panicked?

### ISSUE THREAD

**Issue by PatrickChoDev** [denoland/deno#14373]
From #14355. For others invalid or typo in code, should Deno fall to `_ => {_}` case instead of panicking the application? The way to implements `_` case I thought is..

1. Print info as missing typo in code?
2. Print info as this is unsupported DNS record type and link to opening issue on this repo.

After that `_` case would return for `None` instead of `Some`.

**Comment by bartlomieju** [comment]
That sounds good. Any panic should be fixed to return a meaningful error.

**Comment by bartlomieju** [comment]
@PatrickChoDev are you looking into this issue?

**Comment by PatrickChoDev** [comment]
Absolutely, I am but maybe back committing next week.
