### ISSUE TITLE
Permission prompt on installed scripts

### ISSUE THREAD

**Issue by 0kku** [denoland/deno#14370]
![image](https://user-images.githubusercontent.com/40242277/164790392-dcf31518-e26c-4a93-87ef-1491d19e8474.png)
A clearer permission prompt that doesn't give misleading advice would be nice. It should suggest that the package should be installed with those flags, instead of being ran with them.

**Comment by crowlKats** [comment]
This could be done with a hidden flag (or env var?), and if present, have a different message for perm requests
