### ISSUE TITLE
Docker Images for arm64

### ISSUE THREAD

**Issue by desk467** [denoland/deno#14379]
Currently there is [denoland/deno](https://hub.docker.com/r/denoland/deno) repository on Dockerhub, which contains official Docker images for Deno. However, there are only images available for intel/amd architectures and there is no support for arm64 images (although Deno has official support for Apple Silicon for example). Are there any plans to create docker images for arm devices such as apple silicon via the official Deno repository?

**Comment by dsherret** [comment]
See https://github.com/denoland/deno_docker/issues/100
