### ISSUE TITLE
`ReadableStream` doesn't detach array buffers correctly

### ISSUE THREAD

**Issue by Macil** [denoland/deno#14382]
Two small issues in Deno with detached ArrayBuffers:

1. Creating a typed array from a detached ArrayBuffer fails to throw an error. (Standardized as step 5 of [InitializeTypedArrayFromArrayBuffer](https://tc39.es/ecma262/multipage/indexed-collections.html#sec-initializetypedarrayfromarraybuffer).)
2. TypedArrays with detached ArrayBuffers don't have their length shown as 0. (Standardized as step 5 of [get %TypedArray%.prototype.byteLength](https://tc39.es/ecma262/multipage/indexed-collections.html#sec-get-%typedarray%.prototype.bytelength).)

(Background: ArrayBuffer detaching occurs when an ArrayBuffer is given to a bring-your-own-buffer reader or an ArrayBuffer is transferred to a web worker. This is done in order to give the receiver of the ArrayBuffer exclusive control of it.)

I ran into these issues when I was writing some stream-handling code for Deno and then tried to run my code in Node.js where it failed. It turned out I had reused some detached ArrayBuffers in an incorrect way that Deno didn't complain about.

Here's some example code that shows the issues:

```js
async function main() {
  const readable = new ReadableStream({
    type: "bytes",
    autoAllocateChunkSize: 128,
    pull(controller) {
      for (let i = 0; i < controller.byobRequest.view.length; i++) {
        controller.byobRequest.view[i] = i;
      }
      controller.byobRequest.respond(controller.byobRequest.view.byteLength);
    },
  });

  const reader = readable.getReader({ mode: "byob" });

  const view = new Uint8Array(3);
  const readPromise = reader.read(view);
  console.log("read", await readPromise);
  console.log("view", view);
  console.log("view.byteLength", view.byteLength);
  console.log("view.buffer", view.buffer);
  console.log("view.buffer.byteLength", view.buffer.byteLength);
  console.log("new view", new Uint8Array(view.buffer));
}

main();
```

Node.js results (good, also consistent with Chrome):

```
read { value: Uint8Array(3) [ 0, 1, 2 ], done: false }
view Uint8Array(0) []
view.byteLength 0
view.buffer ArrayBuffer { (detached), byteLength: 0 }
view.buffer.byteLength 0
.../detached_test.js:22
  console.log("new view", new Uint8Array(view.buffer));
                          ^

TypeError: Cannot perform Construct on a detached ArrayBuffer
    at new Uint8Array (<anonymous>)
    at main (.../detached_test.js:22:27)

Node.js v18.0.0
```

Deno results (bad because detached view still shows a length of 3, and creating a new Uint8Array from it doesn't throw an error):

```
read { value: Uint8Array(3) [ 0, 1, 2 ], done: false }
view Uint8Array(3) [ 0, 0, 0 ]
view.byteLength 3
view.buffer ArrayBuffer { [Symbol("<<detached>>")]: true }
view.buffer.byteLength 0
new view Uint8Array(3) [ 0, 0, 0 ]
```

**Comment by lucacasonato** [comment]
Ah yeah, known issue. We'll get to it soon. Thanks for reporting!

**Comment by lucacasonato** [comment]
This is now fixed.
