### ISSUE TITLE
Stabilize "Deno.bench()" API

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#14386]
I'd like to stabilize `Deno.bench()` API in Deno v1.22. Since introduction in v1.20 we received positive feedback about this feature and with https://github.com/denoland/deno/pull/14305 landed, I think we could go ahead with stabilization.

**Comment by DrSensor** [comment]
no stale

**Comment by DrSensor** [comment]
Is it really stabilize in v1.24? I didn't see it in the release notes 🤔
Also, the manual say it still require `--unstable` flag.

**Comment by crowlKats** [comment]
No, the issue was reopened and only got closed because of stalebot; it is still unstable.
