### ISSUE TITLE
`deno test` user code output is displaced in GitHub Actions

### ISSUE THREAD

**Issue by GJZwiers** [denoland/deno#14409]
I have a test with some user code output. On a local terminal the output is displayed like this in 1.21.0:

``` 
should warn when file already exists ...
------- output -------
Warning: file ./foo.ts already exists. Use --force if you want to overwrite an existing file.
----- output end -----
```

However, in the GitHub Actions runners for Ubuntu, MacOS and Windows, the output is printed outside of the lines:
```
Warning: file ./foo.ts already exists. Use --force if you want to overwrite an existing file.
  should warn when file already exists ...
------- output -------
----- output end -----
```

**Comment by bartlomieju** [comment]
@GJZwiers any chance you could verify this with a canary version?

**Comment by GJZwiers** [comment]
Looks like it's working on the canary now!

**Comment by bartlomieju** [comment]
Okay, closing the issue for now then.
