### ISSUE TITLE
Deno.resolveDns do not have timeout option

### ISSUE THREAD

**Issue by lygstate** [denoland/deno#14406]

**Comment by bartlomieju** [comment]
They way to go, would probably be to add `AbortController` handle to `Deno.resolveDns` API and use https://deno.land/std@0.136.0/async/deadline.ts to provide a timeout.

**Comment by lygstate** [comment]
> They way to go, would probably be to add `AbortController` handle to `Deno.resolveDns` API and use https://deno.land/std@0.136.0/async/deadline.ts to provide a timeout.

The issue with this is the memory cleanup with Deno.resolveDns

**Comment by bartlomieju** [comment]
Please elaborate. If `Deno.resolveDns` had `abortSignal` property for `AbortController` it would stop the operation in Rust when abort signal is fired.
