### ISSUE TITLE
 `deno coverage` includes `.ts.snap` files increasing coverage %

### ISSUE THREAD

**Issue by GJZwiers** [denoland/deno#14408]
`deno coverage` is including `.ts.snap` files, which increases the total file count and causes a higher total coverage percentage to be reported:

```
C:\Users\GJZwiers\repos\deno-init [main ≡ +1 ~0 -1 !]> deno coverage cov
cover file:///C:/Users/GJZwiers/repos/deno-init/__snapshots__/writeConfigFile.test.ts.snap ... 100.000% (174/174)
cover file:///C:/Users/GJZwiers/repos/deno-init/deps.ts ... 100.000% (6/6)
cover file:///C:/Users/GJZwiers/repos/deno-init/dev_deps.ts ... 100.000% (7/7)
cover file:///C:/Users/GJZwiers/repos/deno-init/schema.ts ... 100.000% (84/84)
cover file:///C:/Users/GJZwiers/repos/deno-init/writeConfigFile.ts ... 94.048% (79/84)
 123 |   if (settings.name && !/\.jsonc?$/.test(settings.name)) {
 124 |     throw new Error(
 125 |       `Chosen filename has an unsupported file extension: ${settings.name}`,
 126 |     );
 127 |   }
cover file:///C:/Users/GJZwiers/repos/deno-init/writeFileSec.ts ... 83.333% (15/18)
  10 |   if (options?.force) {
  11 |     return await Deno.writeFile(path, data, options);
  12 |   }
```

The Coveralls report shows total coverage went up by about 2% after adding just the snapshot files (with no other changes to `.ts` files):

<html><body>

2228836761 | main | 97.59 | feat(testing): add snapshot tests | GitHub | push | 26 Apr 2022 07:12PM UTC | github
-- | -- | -- | -- | -- | -- | -- | --
2215596563 | main | 95.76 | chore(ci): remove nest land publish | GitHub | push | 24 Apr 2022 12:38PM UTC | github

**Comment by bartlomieju** [comment]
@GJZwiers do you want to tackle this issue? It should quite a simple fix, by adding another exclusion in `cli/tools/coverage/mod.rs` around line 586

**Comment by GJZwiers** [comment]
Sure, I will make a PR
