### ISSUE TITLE
`deno test` throws error in PowerShell when using `-- --update`

### ISSUE THREAD

**Issue by GJZwiers** [denoland/deno#14405]
`deno test --allow-read --allow-write -- --update` throws:

```
error: Found argument '--update' which wasn't expected, or isn't valid in this context

        If you tried to supply `--update` as a value rather than a flag, use `-- --update`

USAGE:
    deno test --allow-read[=<allow-read>...] --allow-write[=<allow-write>...]
```

`deno --version`

```
deno 1.21.0+f07f246 (canary, x86_64-pc-windows-msvc)
v8 10.0.139.17
typescript 4.6.2
```

Same happens on `1.21.0`

**Comment by bartlomieju** [comment]
What shell are you using? I can execute this command on macOS in fish shell.

**Comment by bartlomieju** [comment]
@dsherret could you advise here?

**Comment by GJZwiers** [comment]
I got it working by adding either single or double quotes to `--`: `deno test --allow-read --allow-write "--" --update`, though I believe this should normally work in powershell the same way as in unix shells

**Comment by dsherret** [comment]
I think in Powershell you need to quote the double dashes :/

> A double hyphen instructs PowerShell to treat everything coming after as literal arguments rather than options

https://stackoverflow.com/a/15788023/188246

**Comment by GJZwiers** [comment]
Maybe it just needs to be mentioned in [deno_std](https://github.com/denoland/deno_std/tree/main/testing#updating-snapshots)? This seems to happen only on Powershell while WSL and CMD run the command just fine.

**Comment by dsherret** [comment]
@GJZwiers yeah, I think so. It's unfortunate this behaviour exists in powershell.

**Comment by dsherret** [comment]
Opened https://github.com/denoland/deno_std/issues/2407
