### ISSUE TITLE
data url line breaks are removed

### ISSUE THREAD

**Issue by ayame113** [denoland/deno#14411]
Parsing the data url in Deno seems to remove the line breaks, unlike the behavior of chrome.

![image](https://user-images.githubusercontent.com/40050810/165418391-96ecce39-a351-491f-ac5c-773ecebb7ae0.png)
![image](https://user-images.githubusercontent.com/40050810/165418453-29e614ce-1c0a-4b95-8024-6df54cf74af6.png)

I am trying to combine dynamic import and data url to run code, but it removes line breaks, so places that should not be treated as comments are treated as comments.

```ts
await import(`data:text/javascript,//aaa \n console.log(0)`);
// ↓
await import(`data:text/javascript,//aaa  console.log(0)`);
```

Do you think this is a bug? Or is it behavior according to specifications?

**Comment by kitsonk** [comment]
The string value needs to be URL encoded. See: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURI.
