### ISSUE TITLE
os error 13 when running deno on mounted hdd

### ISSUE THREAD

**Issue by MrKleeblatt** [denoland/deno#14426]
Hey there, I face an issue with Deno when I try to run a basic script on a mounted HDD on ZorinOS (based on Ubuntu Linux).
If I try to run a basic js file:
```js
console.log("Hallooo")
console.log("xD")
```
I get two different results in my root partition and a separate HDD. The script saved on my root partition can be executed as expected, but I get
```
error: Permission denied (os error 13)
```
 when running the same script with the same permissions on the other partition.

You can see more information like the mount options and permissions on the following screenshot:
[Picture of what I mean](https://mrkleeblatt.github.io/DenoError.png)

Am I doing something wrong?

**Comment by randomicon00** [comment]
Can you try the `deno run` command with `-Ldebug` flag and post the output here?

**Comment by MrKleeblatt** [comment]
Running it with `deno run -Ldebug ./main.js`
```
DEBUG RS - deno_runtime::js:32 - Deno isolate init with snapshots.
DEBUG JS - args []
DEBUG RS - deno:1228 - main_module file:///mnt/HDD/Programmieren/JS/main.js
DEBUG RS - deno::file_fetcher:648 - FileFetcher::fetch() - specifier: file:///mnt/HDD/Programmieren/JS/main.js
DEBUG RS - deno_runtime::permissions:51 - ⚠️️  Granted read access to "/mnt/HDD/Programmieren/JS/main.js"
error: Permission denied (os error 13)
```

**Comment by randomicon00** [comment]
Pretty sure it is an os issue and has to do with permissions. I think you should give your mounted drive the right permissions and then try again. I doubt this is a deno specific issue.

**Comment by MrKleeblatt** [comment]
Everything else is working, even python scripts and binary executables, and like you can see in the picture, the permissions are alright. Does it have to do with the mount options? Could be, but why does it ONLY happen with deno then?
So yes, I think it is a deno specific issue

**Comment by kitsonk** [comment]
What is the output of?

```
> deno info ./main.js
```

**Comment by MrKleeblatt** [comment]
@kitsonk 
```
> deno info ./main.js
error: Permission denied (os error 13)
```

**Comment by kitsonk** [comment]
@ry could it be the auto probing for the config file be causing this problem? That is the only thing I can think of, as it ascends the directory structure.

**Comment by MrKleeblatt** [comment]
Hey. I solved the issue. It just had to do with my younger me's way of mounting the HDD. I mounted it on /mnt/HDD and made a symbolic link to that directory in ~/HDD
That actually caused the problem I think, or maybe it was just resolved in the new Deno version.
