### ISSUE TITLE
Deno task should resolve the Deno executable path

### ISSUE THREAD

**Issue by oscarotero** [denoland/deno#14427]
Hi. Let's say I have a task that executes a deno script like this:

```json
{
  "tasks": {
    "my-task": "deno run script.ts"
  }
}
```

I'd like `deno task my-task` to work in all environments, even if `deno` command doesn't exist. For example, netlify doesn't have Deno installed by default, so it's needed to install it before run it:

```
curl -fsSL https://deno.land/x/install/install.sh | sh && /opt/buildhome/.deno/bin/deno task my-task
```

But due `deno` doesn't exist in the `PATH`, this commands returns an error. I think `deno` keyword should be replaced by `Deno.execPath()` value.

**Comment by dsherret** [comment]
Even though it's special behaviour, I think it's more desirable for it to use the current executable path too. For example, we've had the problem that when testing out deno_std with new deno releases, we can't use deno task because it will use the deno version on the path. Thoughts @bartlomieju?
