### ISSUE TITLE
Consider a new std lib readAll(stream: ReadableStream): Uint8Array

### ISSUE THREAD

**Issue by johnspurlock** [denoland/deno#14420]
Now that everything is moving to web standard streams, it would be great to have a one-liner in the std lib to read a stream fully into a byte array.

Maybe in std io or streams

So far I've found `await readAll(readerFromIterable(stream))` using std/streams/conversion.ts, but it seems excessive

**Comment by lucsoft** [comment]
Workaround:

new uint8Array(await (new Reponse(stream)).arrayBuffer())
