### ISSUE TITLE
Errors in tests still contain internal stack frames

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#14449]
```
error: Uncaught (in promise) AddrInUse: Address already in use (os error 48)
    const listener = Deno.listen({
                          ^
    at Object.opSync (deno:core/01_core.js:172:12)
    at opListen (deno:ext/net/01_net.js:45:17)
    at Object.listen (deno:ext/net/01_net.js:318:17)
    at Object.listen (deno:ext/net/04_net_unstable.js:12:18)
    at Server.listenAndServe (file:///Users/ib/dev/deno_std/http/server.ts:181:27)
    at serve (file:///Users/ib/dev/deno_std/http/server.ts:565:20)
    at file:///Users/ib/dev/deno_std/http/server_test.ts:680:24
    at testStepSanitizer (deno:runtime/js/40_testing.js:449:13)
    at asyncOpSanitizer (deno:runtime/js/40_testing.js:149:15)
    at resourceSanitizer (deno:runtime/js/40_testing.js:375:13)

```

Bottom three frames should have been filtered out. This was supposed to be fixed by https://github.com/denoland/deno/pull/14302 but seems that's not the case.

CC @nayeemrmn

**Comment by nayeemrmn** [comment]
That's because it's a floating promise rejection, which we don't support this for. https://deno.land/std@0.137.0/http/server_test.ts#L680 This happens because there is another awaited async operation before `servePromise` is eventually awaited. We fix that in the test with
```diff
  Deno.test(`serve listens on the port 8000 by default`, async () => {
    const url = "http://localhost:8000";
    const body = "Hello from port 8000";

    const handler = () => new Response(body);
    const abortController = new AbortController();

    const servePromise = serve(handler, {
      signal: abortController.signal,
    });
+   servePromise.catch(() => {});

    try {
      const response = await fetch(url);
      assertEquals(await response.text(), body);
    } finally {
      abortController.abort();
      await servePromise;
    }
  });
```

**Comment by bartlomieju** [comment]
Doh, of course it's floating promise 🤦 while the solution to the test is fine, it's really a band-aid and won't fix it for other cases...

**Comment by nayeemrmn** [comment]
So is the issue that we want to similarly filter frames of floating rejections when in `deno test`? The test is technically miswritten either way, though it's not a big deal.

**Comment by bartlomieju** [comment]
> So is the issue that we want to similarly filter frames of floating rejections when in `deno test`? The test is technically miswritten either way, though it's not a big deal.

Yes, I think we should filter stack frames for all errors raised and not handled by user. Good point about a test, I will open a PR to fix that.
