### ISSUE TITLE
`deno compile` fails to compile a file that is in a directory

### ISSUE THREAD

**Issue by LeoDog896** [denoland/deno#14445]
## To reproduce

Currently on linux, and haven't tested it on other machines.

Make a file in a directory (such as `src/file.ts`), add `console.log(1)` to it, and do `deno compile src/file.ts`.

**Comment by hironichu** [comment]
What is the error your getting?

It's working perfectly fine on my machines (Linux/MacOS/Windows)

**Comment by lucacasonato** [comment]
@LeoDog896 is it `src/mod.ts` (note the `mod.ts` instead of `file.ts`) here in your case?
