### ISSUE TITLE
repl redeclare variable bug

### ISSUE THREAD

**Issue by xiaoxigua-1** [denoland/deno#14441]
![image](https://user-images.githubusercontent.com/60529600/166110296-dc325294-9a0f-4987-bd3c-bb5f852ad402.png)
![image](https://user-images.githubusercontent.com/60529600/166110407-cc627cf7-f846-45d3-8943-d7db6947b1af.png)

Deno version: 1.21.1

**Comment by dsherret** [comment]
This is expected behaviour in order to make the repl easier to use. The same thing occurs in the chrome dev tools.
