### ISSUE TITLE
Compiled Deno script does not run on AWS Lambda

### ISSUE THREAD

**Issue by FalkWoldmann6232** [denoland/deno#14440]
Hi,

I've tried to run the following Deno script as a binary (`deno compile`) on AWS Lambda (Custom runtime on Amazon Linux 2):

```typescript
export async function handler() {
    return {
        statusCode: 200,
        headers: { "content-type": "text/html;charset=utf8" },
        body: `Welcome to deno ${Deno.version.deno} 🦕`,
    };
}
```

When running the function I get the following error:
```
Could not create TypeScript compiler cache location: "/home/user/.cache/deno/gen" 
Check the permission of the directory.
```

**Comment by gm112** [comment]
This doesn't really seem like a bug per-say, but more of the environment. I would recommend changing the env var DENO_DIR to a writeable directory by the context of the lambda function, or modifying the AMI image you're using to support the default behavior
