### ISSUE TITLE
Keep numbers in scientific notation format after bundling

### ISSUE THREAD

**Issue by wrnrlr** [denoland/deno#14468]
When bundling a JS module Deno will format number written in scientific forms in their full form.

```
// for example:
Algebra(2, 0, 1, ()=>!(1e0 + 1e1 + 1e2))
// results in:
Algebra(2, 0, 1, ()=>!(1 + 10 + 100))
```
Now that is perfectly fine was it not that the Algebra[1] function here is a JS to JS transpiler that interpret numbers in scientific form, not as scalar values, but as a tensor products where `1e0` is a vectors, `1e12` a bivectors and `1e012` a trivectors.

Admittedly this is sort of a neat thing todo and allows one to write JS for scientific computation and 3D development[2] that looks very close to the math on paper as is quick to experiment with.

My proposal would be to keep numbers in their original form.

[1] https://github.com/enkimute/ganja.js
[2] https://enkimute.github.io/ganja.js/examples/coffeeshop.html#pga3d_points_and_lines

**Comment by dsherret** [comment]
This is beyond our control, but it just so happens that swc recently changed its behaviour to keep the number literals in their original form: https://github.com/swc-project/swc/pull/4245

**Comment by nayeemrmn** [comment]
This is fixed

**Comment by cjihrig** [comment]
Thanks @nayeemrmn. Confirmed. I'll close this out.
