### ISSUE TITLE
Remove unstable `Deno.applySourceMap()`

### ISSUE THREAD

**Issue by nayeemrmn** [denoland/deno#14469]
We have `Deno.core.applySourceMap()` now which is the same thing, if we're using this for something in denoland (looks like just some very old broken and ignored [test](https://github.com/denoland/deno/blob/256dcb058ac2dd2a935076922265278c56264050/cli/tests/unit/error_stack_test.ts#L59)). This function is not fit for public API because it requires the target module to be `deno cache`d and that the input module specifier refers to the typescript file that was transpiled. A good but still rarely used API would work for any module by fetching it independently of the cache and be like:
```ts
Deno.applySourceMap({ fileName: "code_with_source_map_at_the_bottom.js", lineNumber: 3, columnNumber: 4 });
// { fileName: "filename_referenced_in_map.ts", lineNumber: 2, columnNumber: 2 }
```

**Comment by dsherret** [comment]
It also looks like nobody uses this on github except forks of deno: https://cs.github.com/?scopeName=All+repos&scope=&q=Deno.applySourceMap
