### ISSUE TITLE
feat: Support high-precision timestamp

### ISSUE THREAD

**Issue by idanran** [denoland/deno#14470]
It looks like 1632847927.599013

**Comment by bartlomieju** [comment]
Deno already support high precision timing using [`performance.now()`](https://developer.mozilla.org/en-US/docs/Web/API/Performance/now) API.

**Comment by bartlomieju** [comment]
> > Deno already support high precision timing using [`performance.now()`](https://developer.mozilla.org/en-US/docs/Web/API/Performance/now) API.
> 
> This is not a UNIX timestamp

You didn't write that you are interested in UNIX timestamp. What is the actual feature request here?

**Comment by idanran** [comment]
> > > Deno already support high precision timing using [`performance.now()`](https://developer.mozilla.org/en-US/docs/Web/API/Performance/now) API.
> > 
> > This is not a UNIX timestamp
> 
> You didn't write that you are interested in UNIX timestamp. What is the actual feature request here?

Then I'll open a new issue
