### ISSUE TITLE
feat: Support UNIX timestamp

### ISSUE THREAD

**Issue by idanran** [denoland/deno#14476]
Hi, there, it would be better if we supported it

example:
```js
Deno.unixTimestamp() \\ 1632847927.599013
```

**Comment by lucacasonato** [comment]
No, we should instead implement `performance.timeOrigin`, because you can get a high precision unix timestamp with `performance.timeOrigin + performance.now()`. Thus duplicate of #10837.

**Comment by idanran** [comment]
> No, we should instead implement `performance.timeOrigin`, because you can get a high precision unix timestamp with `performance.timeOrigin + performance.now()`. Thus duplicate of #10837.

thanks
