### ISSUE TITLE
steps_output_within is flaky

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#14478]
The test output capturing at the moment is flaky by design unfortunately. Essentially, the JS code is logging to stdout and stderr, which is piped via pipes to two threads that do blocking reads on the output pipes of stdout and stderr. This test output data is then sent across a channel to the test reporter.

What can occurr (especially on the CI), is the data is written to a stdout or stderror pipe, but the threads reading do not read and send the output message in time before the other thread sends the "test complete" notification message.

https://github.com/denoland/deno/runs/6277042335?check_suite_focus=true

To fix this, I believe we'll need a way to unblock the stdout and stderr reader threads and have them to signal back that they don't have any more data to read. I haven't figured out a way to wake up these reader threads though... initially I thought sending zero bytes over would work, but it seems like on Windows doing `WriteFile` on the anonymous pipe write handle with zero bytes does not wake up the read end even when flushing (I'm using all low level win api for testing purposes).

**Comment by dsherret** [comment]
Resolved in #14479

**Comment by cjihrig** [comment]
@dsherret I'm not sure that the flakiness is gone. While working on the release, I just had this test fail for me locally and then it passed on a second run.

**Comment by dsherret** [comment]
That makes me sad.
