### ISSUE TITLE
`Deno.test()` call location in test failures

### ISSUE THREAD

**Issue by nayeemrmn** [denoland/deno#14481]
```ts
// temp1_test.ts
Deno.test("foo", () => {
  throw new Error("foo message");
});
```
```ts
// temp2_test.ts
if (true) {
  Deno.test("bar", () => {
    throw new Error("bar message");
  });
}
```
### Current:

![image](https://user-images.githubusercontent.com/29990554/166666991-bfebb5fb-757a-495a-a3b2-1d1d051d3afe.png)
### Suggested:

![image](https://user-images.githubusercontent.com/29990554/166667891-9980d516-ab6d-46bb-ba2d-a9f1506825d9.png)

(Or the same concept applied above #14262)

@bartlomieju @lucacasonato wdyt?

**Comment by bartlomieju** [comment]
Yeah, looks good. I wanted to do the same thing actually. One thing I'd ask is to remove that tab in the second `failures` section. I thought I fixed that before landing, but it seems not...
