### ISSUE TITLE
--no-check=remote on by default for all subcommands

### ISSUE THREAD

**Issue by ry** [denoland/deno#14498]
like `deno test`

`--check` to enable

**Comment by nayeemrmn** [comment]
> `--check` to enable

Currently it's:
- `deno run main.ts` - Check all
- `deno run --check main.ts` - Check all
- `deno run --check=all main.ts` - Check all

I think 1.22 was supposed to be:
- `deno run main.ts` - Check with no remote
- `deno run --check main.ts` - Check with no remote
- `deno run --check=all main.ts` - Check all

(+ deprecate `--no-check=remote`)

And at 1.23 or currently with `DENO_FUTURE_CHECK`:
- `deno run main.ts` - No check
- `deno run --check main.ts` - Check with no remote
- `deno run --check=all main.ts` - Check all

(+ deprecate `--no-check`)

Is this correct?

**Comment by lucacasonato** [comment]
@nayeemrmn  that looks right!
