### ISSUE TITLE
Is there any options to ignore `deno.json` in current directory?

### ISSUE THREAD

**Issue by stackinspector** [denoland/deno#14509]
The current version of deno seems to read `deno.json` from the current directory by default without `--config` parameter specified. This default is certainly convenient, but if there is a special case where I need to run deno **without config** when there is `deno.json` in the current directory, how should I do it? If there is no way to do this, is it considered to add an option or some way to achieve it?

**Comment by nayeemrmn** [comment]
This is tracked in #13452.

**Comment by lucacasonato** [comment]
Closing as duplicate.
