### ISSUE TITLE
deno task error passing values

### ISSUE THREAD

**Issue by oscarotero** [denoland/deno#14514]
Hi, I have the following task in `deno.json`:

```json
{
  "tasks": {
    "build": "deno run -A https://deno.land/x/lume@v1.8.0/ci.ts"
  }
}
```

So I can run `deno task build` to build a website with Lume.

I want to pass options to the build task, for example `-s` (to start a local server): `deno task build -s` works fine.

But if I pass a value to change the output url with `deno task build --location="https://example.com"` I get the following error:
```
error: Found argument '--location' which wasn't expected, or isn't valid in this context

        If you tried to supply `--location` as a value rather than a flag, use `-- --location`

USAGE:
    deno task <task>

For more information try --help
```

If the argument `-s` is passed before `--location`:
```
deno task build -s --location="https://example.com"
```
it works fine, but if it's passed after:
```
deno task build --location="https://example.com" -s
```
I get that error. Maybe there's an issue parsing the double dash `--`.

**Comment by dsherret** [comment]
Looks like https://github.com/clap-rs/clap/issues/1538 and https://github.com/clap-rs/clap/pull/3389 :(
