### ISSUE TITLE
Add `Error.captureStackTrace` to "dom.extras"

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#14512]

**Comment by mrkldshv** [comment]
Is this one matter of adding definition of `ErrorConstructor` with `captureStackTrace` method to "dom.extras"? Should we do anything else?

**Comment by lucacasonato** [comment]
@mrkldshv Yup, that's it!

**Comment by mrkldshv** [comment]
@lucacasonato right, I see. I'd like to take this issue.
