### ISSUE TITLE
TypeError when importing from URLs in the repl

### ISSUE THREAD

**Issue by QmelZ** [denoland/deno#14522]
When importing from URLs in the repl, the following error is thrown:
```Uncaught TypeError: Relative import path "<path>" not prefixed with / or ./ or ../ from "<location>"```

Example:
```js
> import {readerFromStreamReader, readAll} from "https://deno.land/std/streams/conversion.ts";
Uncaught TypeError: Relative import path "https://deno.land/std/streams/conversion.ts" not prefixed with / or ./
or ../ from "file:///home/qmelz/$deno$repl.ts"
```
Same thing also happens with dynamic imports.

**Comment by bartlomieju** [comment]
Which version of Deno are you using? I cannot reproduce it on latest canary and v1.21.2.

**Comment by QmelZ** [comment]
I've tried with both 1.21.1 and 1.21.2, it seems to happen on both versions for me.

**Comment by dsherret** [comment]
It works fine for me in 1.21.1 and 1.21.2.

**Comment by QmelZ** [comment]
> how are you launching the repl?

i'm using `deno repl`

**Comment by dsherret** [comment]
@QmelZ I think maybe try clearing your deno dir. Maybe the deno dir is broken (which could happen due to #13302) or it's just an old broken deno std (since an unversioned import is used).

To clear it, run `deno info` and then manually delete the directory listed as the DENO_DIR location.

**Comment by QmelZ** [comment]
Thanks, that worked! Closing the issue.
