### ISSUE TITLE
`deno test --jobs` flag should require equals when passing a value

### ISSUE THREAD

**Issue by nayeemrmn** [denoland/deno#14533]
The `--jobs` flag optionally doesn't take a number value to default to the number of available cpus. So it should require an equal sign. Currently `deno test --jobs tests/` doesn't work because `tests/` is parsed as the number of threads. Unfortunately this is a breaking change, so this was a bad oversight.

**Comment by dsherret** [comment]
When fixing this (aka, doing this breaking change) we should consider whether we should just deprecate it in favour of the DENO_JOBS env variable. See discussion in https://github.com/denoland/deno/pull/14929#discussion_r919079601

**Comment by nayeemrmn** [comment]
Note that we also wanted _some_ binary flag to activate `DENO_JOBS` so that the test runner remained single-threaded by default. Other than retracting that expectation, a sound option would be to still deprecate `--jobs` and replace it with `--parallel` which does the same thing. It's a slightly better name for a binary flag and wouldn't have this bug.

**Comment by dsherret** [comment]
I think replacing it with `--parallel` makes sense given that fixing `--jobs` is a breaking change and it's not a great name. Also, `"parallel": true` in the configuration file might be a nice option in the future.
