### ISSUE TITLE
`deno test --filter <filter>`  equivalent for `deno bench`

### ISSUE THREAD

**Issue by Im-Beast** [denoland/deno#14542]
It'd be nice to be able to run selection of benchmarks without needing to split benchmarks into multiple files.

**Comment by MierenManz** [comment]
a nice addition would also maybe be the `only` property of `Deno.test` definitions

**Comment by GJZwiers** [comment]
Fortunately it is possible to do both of these things already, you can filter benchmarks by name with `deno bench --filter`. For example, if you had these benches:

```js
Deno.bench({
  name: "[stringify] bench",
  fn: () => {
    JSON.stringify({ foo: "bar" });
  },
});

Deno.bench({
  name: "[parse] bench",
  fn: () => {
    JSON.parse('{ "foo": "bar" }');
  },
});

```

you could run `deno bench --unstable --filter parse`. Or, if you want to focus on a single one, you can add `only: true` to the `Deno.BenchDefinition` object:

```js
Deno.bench({
  name: "[parse] bench",
  only: true,
  fn: () => {
    JSON.parse('{ "foo": "bar" }');
  },
});
```

**Comment by Im-Beast** [comment]
I could swear that it didn't work and there was no information about it in `deno bench -h` when I tried it before posting this issue. Was it added after it?

Nontheless, it works just as I would expect right now, so I'm closing this issue.
