### ISSUE TITLE
`Deno.consoleSize(Deno.stdout.rid)` doesn't work with `deno test --unstable`

### ISSUE THREAD

**Issue by ydcjeff** [denoland/deno#14543]
### Version

Deno 1.21.2

### Reproduction

Run the below code with `deno run --unstable main.js` and it prints with an object with `column` and `row`
```js
// main.js
console.log(Deno.consoleSize(Deno.stdout.rid))
```

Run the below code with `deno test --unstable test.js` and it throws an error `Error: Inappropriate ioctl for device (os error 25)`
```js
// test.js
Deno.test('test', () => {
  console.log(Deno.consoleSize(Deno.stdout.rid))
})
```

I am on Intel based macOS Monterey 12.3.1.

**Comment by bartlomieju** [comment]
I'm not sure if there's anything we can do. When running in `deno test`, `Deno.stdout` and `Deno.stderr` are replaced with pipes which are not a TTY. 

CC @dsherret any ideas?

**Comment by ydcjeff** [comment]
I understand `Deno.consoleSize` can't be used in CI, but at least I want to run the tests locally.

> `Deno.stdout` and `Deno.stderr` are replaced with pipes which are not a TTY.

In which minor did this change happen as I am sure the tests are passing locally prior to 1.20?

**Comment by bartlomieju** [comment]
It landed in 1.21 in "user output markers" PR

**Comment by dsherret** [comment]
@imjamesb how would `deno test`'s stdout/stderr capturing work with a pty?

@bartlomieju maybe we could have a flag to disable capturing output? (maybe `--no-capture`) Alternatively, people could test with a pty by using #14535 or a "humble object pattern" could be used that returns a dummy value for the console size while testing.

**Comment by bartlomieju** [comment]
> @bartlomieju maybe we could have a flag to disable capturing output? (maybe --no-capture) 

We're not really capturing any output, so I'm not sure it's a good idea.

> Alternatively, people could test with a pty by using https://github.com/denoland/deno/pull/14535 or a "humble object pattern" could be used that returns a dummy value for the console size while testing.

I think #14535 should be a preferred solution to this problem.

**Comment by imjamesb** [comment]
> @imjamesb how would `deno test`'s stdout/stderr capturing work with a pty?
> @dsherret 

I believe that the Deno.std(out,err,in) streams can be replaced to a PTYs interface streams for the `deno test` environment.

**Comment by ydcjeff** [comment]
Not stale yet.

**Comment by Im-Beast** [comment]
Is there any workaround around this (or preferably progress to make it work)?

**Comment by lucacasonato** [comment]
We removed `Deno.consoleSize(Deno.stdout.rid)` and replaced it with `Deno.consoleSize()` before stabilizing. This version also works in `deno test` (tested in latest canary).
