### ISSUE TITLE
`deno test` doesn't use the specified `compilerOptions.lib`

### ISSUE THREAD

**Issue by RobertAKARobin** [denoland/deno#14565]
Tiny example repo:

https://github.com/RobertAKARobin/deno-test-err

It consists of:

```ts
// index.ts
export const div = document.createElement('div');
```

```ts
// index.test.ts
import { div } from './index.ts';
console.log(div);
```

```ts
// deno.jsonc
{
  "compilerOptions": {
    "lib": [
      "deno.ns",
      "dom"
    ]
  }
}
```

# Steps to reproduce

1. Run `deno bundle index.ts`. Observe it compiles and completes successfully.
2. Run `deno test index.test.ts`

# Expected result

`deno test` completes successfully, just like `deno bundle`.

# Actual result

`deno test` fails with a fatal error:

```
test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out (13ms)

error: Uncaught ReferenceError: document is not defined
export const div = document.createElement('div');
                   ^
    at file:///Users/robertthomas/Programming/web/deno-test-err/index.ts:1:20
```

`deno test` doesn't "know" about `document`, which indicates it is not respecting that the configuration file's `compilerOptions.lib` includes `"dom"`.

If I add the `--compat` option...:

```
$ deno test --allow-all --config deno.jsonc --compat  --unstable --no-check index.test.ts 
```

...then the error changes:

```
test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out (214ms)

error: Uncaught (in promise) SyntaxError: Cannot use import statement outside a module
  const [f, err] = core.evalContext(wrapper, filename);
                        ^
    at wrapSafe (https://deno.land/std@0.138.0/node/module.ts:1315:25)
    at Module._compile (https://deno.land/std@0.138.0/node/module.ts:251:29)
    at Object.Module._extensions..js (https://deno.land/std@0.138.0/node/module.ts:1334:10)
    at Module.load (https://deno.land/std@0.138.0/node/module.ts:239:34)
    at Function._load (https://deno.land/std@0.138.0/node/module.ts:558:14)
    at loadCjsModule ([deno:cli/compat/mod.rs:120:30]:3:22)
```

How can I write unit tests that include the DOM API?

**Comment by bartlomieju** [comment]
```
test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out (13ms)

error: Uncaught ReferenceError: document is not defined
export const div = document.createElement('div');
                   ^
    at file:///Users/robertthomas/Programming/web/deno-test-err/index.ts:1:20
```

This is an actual runtime error and not TypeScript error. If you configure `compilerOptions` and pass "dom" it tells built-in TypeScript compiler that these types are available but it doesn't actually make `document` available in Deno.

**Comment by RobertAKARobin** [comment]
Thanks @dsherret . Is there a workaround? It would be nice if I could unit test front-end code without needing to import a vendor library.

**Comment by bartlomieju** [comment]
@RobertAKARobin see https://deno.land/manual/jsx_dom/linkedom#using-linkedom-with-deno
