### ISSUE TITLE
How do I use my own import map while vendoring?

### ISSUE THREAD

**Issue by jimisaacs** [denoland/deno#14576]
As far as I can tell, there's only one import map allowed as input in every command.

Would if you could pass `--import-map` to `deno vendor`, so that the generated import map output is merged the one specified as input?

**Comment by jimisaacs** [comment]
It would be nice if it did this, but also walked the input import map to still vendor remote modules specified in the input import map. Though the entries of the input import map remain unchanged, though merged with the vendor import map.

This means that if the input import map just so happened to specify every remote module it could, then the final generated import map would look the same as the source one.

**Comment by jimisaacs** [comment]
I might have spoke too soon.

I have this import map at `src/import_map.json`:
```json
{
	"imports": {
		"oak": "https://deno.land/x/oak@v10.5.1/mod.ts",
		"react": "https://esm.sh/react@18",
		"react-dom/server": "https://esm.sh/react-dom@18/server"
	}
}

```
and `deno vendor main.ts --import_map=src/import_map.json` generated this:
```
{
  "imports": {
    "https://cdn.esm.sh/": "./cdn.esm.sh/",
    "https://deno.land/": "./deno.land/",
    "https://esm.sh/": "./esm.sh/",
    "https://raw.githubusercontent.com/": "./raw.githubusercontent.com/"
  },
  "scopes": {
    "./cdn.esm.sh/": {
      "/v78/react@18.1.0/deno/react.js": "./cdn.esm.sh/v78/react@18.1.0/deno/react.js"
    },
    "./deno.land/": {
      "oak": "./deno.land/x/oak@v10.5.1/mod.ts"
    },
    "./esm.sh/": {
      "react": "./esm.sh/react@18.js",
      "react-dom/server": "./esm.sh/react-dom@18/server.js"
    }
  }
}

```

Then when I run:
```
deno run --allow-net --allow-read --import-map ./vendor/import_map.json --cached-only main.ts
```

I get:
```
...
error: Relative import path "oak" not prefixed with / or ./ or ../ and not in import map from ...
...
```

**Comment by jimisaacs** [comment]
Ok, from the previous example, I would expect the generated import_map.json to look like this:
```
{
  "imports": {
    "oak": "https://deno.land/x/oak@v10.5.1/mod.ts",
    "react": "https://esm.sh/react@18",
    "react-dom/server": "https://esm.sh/react-dom@18/server",
    "https://cdn.esm.sh/": "./cdn.esm.sh/",
    "https://deno.land/": "./deno.land/",
    "https://esm.sh/": "./esm.sh/",
    "https://raw.githubusercontent.com/": "./raw.githubusercontent.com/"
  },
  "scopes": {
    "./cdn.esm.sh/": {
      "/v78/react@18.1.0/deno/react.js": "./cdn.esm.sh/v78/react@18.1.0/deno/react.js"
    }
  }
}
```
This feels like actually a pretty easy transformation to be honest. It just keeps the existing mappings in the source input map, and resolves and adds to it to keep it local, as if the value of those mappings were what are actually used in source.

**Comment by jimisaacs** [comment]
Found https://github.com/denoland/deno/issues/13697, so this feels like a dupe

**Comment by jimisaacs** [comment]
Hmm, seems my last through is broken with `--no-remote`, which seems odd. I guess it makes sense if it is determining whether to to continue based on the shape of the strings in the `imports` section, versus how they resolve with an import_map 🤔

**Comment by jimisaacs** [comment]
still it's close, as I think it might just need to walk the vendor generated map to get a the value starting with the origin.

**Comment by jimisaacs** [comment]
I ended up writing this for now:
https://github.com/jimisaacs/source_vendor_import_map_fix_up

**Comment by dsherret** [comment]
This is essentially #13697. Follow there for updates.
