### ISSUE TITLE
error trying to connect: Connection reset by peer (os error 104)

### ISSUE THREAD

**Issue by Sn0wAlice** [denoland/deno#14579]
Hello ! just reporting this strange issue,

Got error `error trying to connect: Connection reset by peer (os error 104)` on fetch,

__Fun facts:__ 
1. request working on nodejs with `node-fetch@2` (exactly same code)
2. working with firecamps & postman
3. working with firefox & chrome

this is why i suspect Deno to be the error source.

Deno version tested: 1.19 / 1.20 / 1.21 (error for each)

Code: 
```ts
let name = "aaa"
let req = await fetch('https://abipco.gov.ag/api/1.0/services/loadInfoProc', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json;charset=utf-8',
                'Accept': 'application/json, text/plain, */*',
                "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36"
            },
            body: JSON.stringify({
                "input":"key=0,query="+name,
                "name":"EntitySearch"
            })
        })
let data = await req.json()
let t = data.rows

```

**Comment by lucacasonato** [comment]
It seems like `rustls` is unable to establish a TLS connection with this site. Noteworthy: the leaf certificate is supposedly valid for > 2 years. This is rather long.

Other than that, it looks mostly fine.

Minimal reproduction:

```js
const c = await Deno.connectTls({ hostname: "abipco.gov.ag", port: 443 });
await c.handshake();
```

**Comment by lucacasonato** [comment]
> May i report this issue to the Antigua gov ?

I don't have a concrete known solution, but I suspect that using Let's Encrypt TLS certificates would solve the situation :)

**Comment by lucacasonato** [comment]
> strange but also got the warning message Received a ServerHelloDone handshake message while expecting [CertificateRequest] on github page website

This warning message is unrelated to the error. It is an unrelated bug that will hopefully be fixed soon.

**Comment by dector** [comment]
Hi! Any updates for this? Still reproducible on
```
$ deno --version
deno 1.25.1 (release, x86_64-unknown-linux-gnu)
v8 10.6.194.5
typescript 4.7.4
```

This works:
```
deno eval "console.log(await fetch('https://google.com'))"
```

This doesn't:
```
deno eval "console.log(await fetch('https://conjugator.reverso.net/conjugation-english.html'))"
```

**Comment by Sn0wAlice** [comment]
For the moment, use a proxy,
for example: `https://thingproxy.freeboard.io/fetch/https://google.com` idk how to patch this for the moment
