### ISSUE TITLE
Questions on duplicate ES modules

### ISSUE THREAD

**Issue by kevinkassimo** [denoland/deno#1458]
I know ES Module support is WIP, just having a few questions when quickly going through the code (I'll later do more experiments myself):

With `isolate::execute_mod`, seems that it is fetching source code every single time even with the same source file
https://github.com/denoland/deno/blob/4f62a56f9071b0541b6be9b8e9c40fdcc2a3da22/src/isolate.rs#L239-L240
and repeatedly compile
https://github.com/denoland/deno/blob/4f62a56f9071b0541b6be9b8e9c40fdcc2a3da22/libdeno/binding.cc#L464
and repeatedly register
https://github.com/denoland/deno/blob/4f62a56f9071b0541b6be9b8e9c40fdcc2a3da22/libdeno/binding.cc#L395
Given the assumption that IdentityHash is unique, I'm not quite sure if this is considered unnecessary overhead if a previously compiled module is already available? (or possibly such action is deliberate?)

(As to IdentityHash, it seems Node is using a [multimap](https://github.com/nodejs/node/blob/ca9c0c90c28ed012cdd5be4e94a974ad07fd9b9a/src/env.h#L700) when working with it, so I would assume it still has quite a chance of collision... Probably we could use a similar design (that keeps a reference of the module along with the filename as map value) to circumvent the problem)

Also, similar things happens with `ResolveOk`, with which we pass in the source code every time but might not be even used:
https://github.com/denoland/deno/blob/4f62a56f9071b0541b6be9b8e9c40fdcc2a3da22/libdeno/binding.cc#L431-L437

**Comment by ry** [comment]
I think it will not repeated do these things... but rather than guess we should have a test which demonstrates that it doesn't get called more than once. Not exactly sure how to do that right now but i just dropped a bunch of code in https://github.com/denoland/deno/pull/1460 so check it out.
