### ISSUE TITLE
Support `"deflate-raw"` in `CompressionStream`

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#14591]
Spec change: https://github.com/WICG/compression/pull/43
Tests: https://github.com/web-platform-tests/wpt/commit/c6f680016180bc5c8b21c3956f7ac01c7dbf85ac

**Comment by cjihrig** [comment]
I think this was fixed in https://github.com/denoland/deno/pull/14863. Please reopen if I'm wrong.
