### ISSUE TITLE
error: Unexpected token Some(Word(name)) at https://deno.land/std@0.138.0/io/buffer.ts:257:11

### ISSUE THREAD

**Issue by LjubomirS** [denoland/deno#14598]
I have this error message: error: Unexpected token Some(Word(name)) at https://deno.land/std@0.138.0/io/buffer.ts:257:11
The code worked until today. Screenshot attached
![Screenshot_5](https://user-images.githubusercontent.com/67682718/168341732-bc5f51a5-abd7-437e-a351-c3a4c685ad28.png)

This is what it shows 
![Screenshot_6](https://user-images.githubusercontent.com/67682718/168342054-440c865b-8db1-423d-bfba-46ee37f0704a.png)

**Comment by dsherret** [comment]
@LjubomirS what version of deno are you using?

**Comment by LjubomirS** [comment]
deno 1.1.3
v8 8.5.216
typescript 3.9.2

**Comment by LjubomirS** [comment]
> deno 1.1.3 v8 8.5.216 typescript 3.9.2

**Comment by dsherret** [comment]
@LjubomirS try upgrading to the latest (v1.21.3). It doesn't happen for me there.

**Comment by LjubomirS** [comment]
@dsherret Thank you! Problem solved.
