### ISSUE TITLE
`Deno.test` does not render POJO errors nicely

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#14596]
```js
Deno.test("foo", async () => {
  throw { foo: "bar" };
})
```

prints as the error message:

```
./test.ts > foo
#<Object>
```

`#<Object>` is not a helpful serialization of the thrown value.

**Comment by bartlomieju** [comment]
I didn't think about such case where non-`Error` values are thrown, and we're just assuming everything can be turned into an error. I believe we need to alter this code:
```
pub enum TestResult {
  Ok,
  Ignored,
  Failed(Box<JsError>),
}
```
to have an enum in `TestResult::Failed` variant:
```
TestFailure {
   error: Option<Box<JsError>>,
   object: Option<Value>
}
```

CC @nayeemrmn

**Comment by bartlomieju** [comment]
Hah, perfect! Thanks for looking into this. It's unfortunate with uncaught errors, I really need to get into rewriting test runner to do more stuff from Rust (ie. triggering running a test case), which should help with this problem.
