### ISSUE TITLE
Leading slashes in paths on Windows

### ISSUE THREAD

**Issue by 0kku** [denoland/deno#14605]
Running the following will log the strings described in the comments: 
```ts
console.log(
  import.meta.url, // "file:///D:/test/testing.ts"
  new URL(import.meta.url).pathname, // "/D:/test/testing.ts"
);
```
This is spec-compliant behaviour and not a bug. 

However, this causes some cross-platform issues with code like: 
```ts
console.log(await Deno.readTextFile(new URL(import.meta.url).pathname)); // path has the leading slash
```
(reading the file itself as text). Obviously, this is a contrived example, but I would expect it to work. And [it _does_ work on Mac](https://media.discordapp.net/attachments/726004202878533682/975002689584902164/Screenshot_2022-05-14_at_13.52.22.png). A more reasonable example might look like this: 
```ts
import { dirname, join } from "https://deno.land/std@0.139.0/path/win32.ts";

const path = join(dirname(new URL(import.meta.url).pathname), "units.txt"); // path has the leading slash
console.log(await Deno.readTextFile(path));
```
I would expect this to work on all platforms, but on Windows, both of the above examples result in `error: Uncaught (in promise) NotFound: The system cannot find the file specified. (os error 2)`.

---

Since leaving the leading slash in is spec-compliant behaviour for URL.pathname, I propose that Deno ought to ignore the leading slash in file paths to ensure that code is portable.

**Comment by bartlomieju** [comment]
Instead of:
```js
console.log(await Deno.readTextFile(new URL(import.meta.url).pathname)); // path has the leading slash
```
do:
```
console.log(await Deno.readTextFile(new URL(import.meta.url)));
```

Most of Deno APIs that support filepaths, will also handle URLs.

**Comment by crowlKats** [comment]
@bartlomieju the problem is that any needed modification with `dirname` & `join` isnt doable

**Comment by andreubotella** [comment]
`new URL(...).pathname` returns the first slash [per the spec](https://url.spec.whatwg.org/#url-path-serializer). If you need to turn a URL into a OS-valid path, why not use [https://deno.land/std@0.139.0/path/mod.ts](`fromFileUrl` from https://deno.land/std@0.139.0/path/mod.ts)

**Comment by bartlomieju** [comment]
> @bartlomieju the problem with that is that any needed modification with that `dirname` & `join` isnt doable. maybe dirname & join (and others) should maybe support accepting a `URL`?

Depends, you can always use `fromFileUrl()` first

**Comment by nayeemrmn** [comment]
> @bartlomieju the problem with that is that any needed modification with that `dirname` & `join` isnt doable

Correct, that's why instead of those you have to use the URL constructor (e.g. `new URL(".", url)` for `dirname`) otherwise you have to go full paths with `fromFileUrl()`. `Url::pathname` don't substitute FS paths

**Comment by crowlKats** [comment]
you three are right, completely forgot about `fromFileUrl` was a thing

**Comment by 0kku** [comment]
```ts
join(dirname(new URL(fromFileUrl(import.meta.url)).pathname), "units.txt")
```
does work, yes, but I think it's a bit concerning that it's possible to so trivially write code that works on unix systems and doesn't work on Windows (and vice versa). I cloned a Deno project from GitHub, and tried to run it, but it didn't work on Windows. It's a bit disappointing if Deno promises cross-platform portable code, yet a project might fail to run on only some systems. This doesn't feel like something that ought to be OS-dependent imo, and the proposed solution feels more like a workaround.

**Comment by nayeemrmn** [comment]
> ```ts
> join(dirname(new URL(fromFileUrl(import.meta.url)).pathname), "units.txt")
> ```

The proper way of writing this is:
```ts
new URL("units.txt", import.meta.url)
```
The URL constructor will pretty much always satisfy these use cases. In fact, forget about `fromFileUrl()`.

**Comment by bartlomieju** [comment]
> I cloned a Deno project from GitHub, and tried to run it, but it didn't work on Windows. It's a bit disappointing if Deno promises cross-platform portable code, yet a project might fail to run on only some systems. This doesn't feel like something that ought to be OS-dependent imo, and the proposed solution feels more like a workaround.

Exactly for this reason the FS APIs accept URLs so you don't have to do the conversion yourself.

**Comment by 0kku** [comment]
In that case it might be nice if they _only_ accepted URLs so that people wouldn't accidentally write code that might or might not run depending on the OS it happens to be run on?

**Comment by andreubotella** [comment]
> To elaborate: the issue I'm reporting is that it's possible to accidentally write non-portable code, not that it isn't possible to get it to work on all OSs when written correctly. The compiler shouldn't let people write non-portable code in the first place in situations like these.

That would be a breaking change, and I don't think that would be changed until Deno 2.0 (if it ever really comes).

**Comment by lucacasonato** [comment]
URLs can not represent all valid UNIX file paths, as such we must support accepting both. This behavior is consistent with Node and the URL spec, so I think there is nothing actionable for us to do here, other than writing more docs.

**Comment by mb21** [comment]
> there is nothing actionable for us to do here, other than writing more docs.

That sounds reasonable. Is there now docs/guidance somewhere on how to write file-system related code that works on POSIX and Windows (as well as ideally also on Deno, Bun _and_ Node.js?)
