### ISSUE TITLE
`integration::repl::pty_emoji` fails locally on Linux

### ISSUE THREAD

**Issue by andreubotella** [denoland/deno#14615]
```
running 1 test
test integration::repl::pty_emoji ... FAILED

failures:

---- integration::repl::pty_emoji stdout ----
thread 'integration::repl::pty_emoji' panicked at 'assertion failed: `(left == right)`
  left: `6`,
 right: `2`', cli/tests/integration/repl_tests.rs:219:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    integration::repl::pty_emoji
```

I don't know if this is not the case on Windows, but on Linux `console.read_all_output()` seems to include partial writes as the console catches up to the existing input, adding to the number of dino emojis.

This test was introduced in #14559. cc @dsherret

**Comment by dsherret** [comment]
Yeah, I only ran it on Windows and assumed it would work the same on linux. Weird read_all_output works that way for linux.

**Comment by GJZwiers** [comment]
It also fails locally on Windows for me sometimes.

**Comment by espindola** [comment]
Just hit it locally. How is it passing on CI?

**Comment by andreubotella** [comment]
> Just hit it locally. How is it passing on CI?

I'm pretty sure PTY tests don't run on CI at all.
