### ISSUE TITLE
Undeprecate the URL parameter of fetch

### ISSUE THREAD

**Issue by saschanaz** [denoland/deno#14620]
https://github.com/microsoft/TypeScript-DOM-lib-generator/pull/1269 allows lib.dom to accept URL, so I think the reasoning in #14113 is now invalid:

>Deno's fetch and lib.dom's fetch have slightly different declarations. (Deno's fetch accept URL as the first arg, but lib.dom's fetch doesn't)

**Comment by mrkldshv** [comment]
Do we just want to revert this deprecated signature?
