### ISSUE TITLE
deno lsp and vuejs

### ISSUE THREAD

**Issue by elycheikhsmail** [denoland/deno#14625]
Deno lsp vuejs
deno lsp and vscode deno extension work well together.
the "js-node" tooling system for vue and vscode vue (v3) extension work well together.
when we want to replace the "js-node" tools for vue by "js-deno" like the alephjs framework doing the question: how to configure vscode to support deno lsp and .vue file?  arises.
the question does not only arise for vue, we can ask the same question for sveltejs or other but here we are essentially discussing the case of vue-deno.
what solution do you suggest?  do we need new vscode extension for deno-vue?
sorry if this not the right place for this but I don't see another good place.

**Comment by elycheikhsmail** [comment]
alephjs seems be  solution

**Comment by xuybin** [comment]
> alephjs似乎是解决方案

How to do
