### ISSUE TITLE
Treat `"deno.config": ""` as `"deno.config": null` in LSP

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#14630]
When editing the config in the VSCode settings UI, it is possible to set the setting to the empty string (which looks the same as having it set to `null` from the UI). The LSP should treat `null` and `""` the same.

**Comment by lucacasonato** [comment]
It does not seem to be working in 1.21.0 though. See this thread on Discord: https://ptb.discord.com/channels/684898665143206084/689420767620104201/975726085507547186

**Comment by kitsonk** [comment]
We probably need address the whole deserialization of options.  Also there is two paths that configuration gets applied.  It can be applied at startup and is part of the initialisation payload and then there is a configuration change where we query the client.

I suspect we are getting different results on the initial and updates for empty/undefined/null values.
