### ISSUE TITLE
Ignore or decline permissions?

### ISSUE THREAD

**Issue by NetOpWibby** [denoland/deno#14633]
I would like to decline access to `NODE_DEBUG` but haven't seen a way to do so. I just want to ignore the prompt when I run `deno run --allow-net --allow-read --allow-run --allow-write main.ts`.

A module I installed doesn't actually need more access.

**Comment by lucacasonato** [comment]
Specify `--no-prompt` to disable the prompt :)

**Comment by NetOpWibby** [comment]
Huzzah!
