### ISSUE TITLE
Migrate usage on V8's globalThis.console

### ISSUE THREAD

**Issue by legendecas** [denoland/deno#14658]
Since `globalThis.console` is not an ECMAScript defined builtin, V8's globally installed `console` implementation is been moved to the context's extra binding object: https://source.chromium.org/chromium/chromium/src/+/main:v8/src/init/bootstrapper.cc;l=4429?q=bootstrapper.cc

Deno is depending on this too: https://github.com/denoland/deno/blob/main/runtime/js/99_main.js#L542. We need to migrate to that one before the globally installed console object is removed in V8.

**Comment by bartlomieju** [comment]
I don't have full context for this, but maybe you could try to tackle this @legendecas? The APIs from your PR in rusty_v8 are now available to be used in `deno_core`
