### ISSUE TITLE
`Deno.permissions.request()` prompts even if `--no-prompt` set

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#14668]
Calling `Deno.permissions.request()` will prompt the user for the permission if not already granted even when `--no-prompt` or `NO_PROMPT` is set, which seems wrong.  In those cases, it should just deny un-granted permissions.

Ref: denoland/deno_emit#3 where deno_cache is using `Deno.permissions.request()` to ensure it has sufficient permissions to determine the `DENO_DIR`.

**Comment by tom-sherman** [comment]
Just want to clarify what should happen if `Deno.permissions.request()` is called when `--no-prompt` is set: the promise should reject with a `PermissionDenied` right?

**Comment by tom-sherman** [comment]
Ok I think I misunderstood, the linked PR instead just returns denied in this scenario.

**Comment by teleclimber** [comment]
Confirming this is still happening with Deno version 1.39.3. Note that this is problematic when the script is run unattended! Thanks.

**Comment by KaKi87** [comment]
Hi,

I was using `--no-prompt` because of Deno's Node compatibility turning a dependency's useless `process.env` calls into permission requests.

But now, I actually need to make a manual permission request, and I can't because of this issue having been fixed.

What can I do instead ?

Thanks

**Comment by jsejcksn** [comment]
@KaKi87 It would probably be more effective to open a new discussion or ask on Discord instead of commenting on this already-closed issue. You can link to this issue in order to refer to it.
