### ISSUE TITLE
`Response.text()` does not return correct body from ReadableStream

### ISSUE THREAD

**Issue by sntran** [denoland/deno#14674]
**Describe the bug**

When calling `.text()` on a `Response` constructed with a `ReadableStream` body, the resulting string is incorrect.

**Steps to Reproduce**

`deno run text_test.ts fixture.txt` using the attached [fixture.txt](https://github.com/denoland/deno/files/8733093/fixture.txt) and the following "text_test.ts"

```ts
import { BufReader } from "https://deno.land/std@0.140.0/io/mod.ts";

const TERMINATION = ".".charCodeAt(0); // 46
const LF = "\n".charCodeAt(0); // 10
const CR = "\r".charCodeAt(0); // 13

const TERMINATING_LINE = Uint8Array.from([TERMINATION, CR, LF]);
function isTerminatingLine(line: Uint8Array) {
  return line.every((value, index) => value === TERMINATING_LINE[index]);
}

const source = await Deno.open(Deno.args[0]);
const bufReader = BufReader.create(source);

const body = new ReadableStream({
  async pull(controller) {
    const line = await bufReader.readSlice(LF) || new Uint8Array();
    console.log(new TextDecoder().decode(line).trimEnd());

    if (isTerminatingLine(line)) {
      controller.close();
    }
    else {
      controller.enqueue(line);
    }
  }
});

const response = new Response(body);
console.log("----- OUTPUT FROM pull() -----");
const text = await response.text();
console.log("----- OUTPUT FROM .text() -----");
console.log(text);
```

Notes: The input was originated from TCP with CLRF line endings instead of just newlines, but I think the difference won't matter in this case.

**Expected behavior**

The output should contain two equal text blocks, whose content matches the source of "fixture.txt".

**Actual behavior**

The text block from calling `.text()` starts to be different at around 33 lines of input. If the input contains less than 32 lines, the text blocks are correct.

**Environment**

- OS: 12.3
- deno version: 1.21.0
- std version: 0.140.0

**Comment by lucacasonato** [comment]
```diff
-      controller.enqueue(line);
+      controller.enqueue(line.slice());
```

The documentation of `BufReader#readSlice()` states:

> readSlice() reads until the first occurrence of delim in the input, returning a slice pointing at the bytes in the buffer. **The bytes stop being valid at the next read.**

As such, you need to take a copy of the bytes.

**Comment by sntran** [comment]
Oops. Sorry I missed that part. Thanks for pointing it out!
