### ISSUE TITLE
[Feature] Add navigator.language and navigator.languages based on OS defaults.

### ISSUE THREAD

**Issue by tracker1** [denoland/deno#14677]
For better browser compatibility, it would be nice to have support for `navigator.language` and `navigator.languages` with defaults based on the OS environment.

Specifically to better support Intl.* parameters in practice.

**Comment by tracker1** [comment]
Not stale.

**Comment by bartlomieju** [comment]
These have shipped in Deno v1.27: https://deno.com/blog/v1.27
