### ISSUE TITLE
Expose CLI commands as library functions

### ISSUE THREAD

**Issue by ProofOfKeags** [denoland/deno#14679]
I specifically want to be able to run `deno bundle ...` from inside of another rust program. I looked into calling the swc_bundler::bundle function but upon seeing the volume of code needed to be able to take a module root and emit it into a single bundle it seems silly to try and do that rather than just exposing that functionality from deno itself.

I suppose the suggestion here would be, at minimum, to move the `emit` module into a library where it could be called, or alternatively making a version of `bundle_command` available albeit with possibly more specific types.

**Comment by dsherret** [comment]
@ProofOfKeags take a look at https://github.com/denoland/deno_emit as there's a bundle function in there.

**Comment by ProofOfKeags** [comment]
Oh cool! Looking at it I'm noticing theres little to no documentation in docs.rs. Is there another place I should look? I can't quite figure out how JsValue is supposed to become an actual string that can be written to a file which represents an actual javascript program. AFAICT it emits a JsValue which may strip certain properties if piped through serde.

**Comment by dsherret** [comment]
@ProofOfKeags it's incorrectly having wasm types in the rust api. It needs to be updated to separate those out. Anyway, that would be the place to make improvements and get a rust api for emit.

**Comment by ProofOfKeags** [comment]
Does that mean that it is *undesirable* to have them emit wasm types? If so I am understanding the task to be to *convert* the API in that module to use rust types only, where JsValue may be converted to a type from swc or something like that?

**Comment by dsherret** [comment]
We need to have functions specifically for Wasm that end up in the Wasm module and then other functions for the Rust API that doesn't use js_sys or wasm_bindgen that gets published on crates.io. I opened https://github.com/denoland/deno_emit/issues/33 -- let's continue the conversation there.
