### ISSUE TITLE
Atomics.waitAsync implementation

### ISSUE THREAD

**Issue by Eyal-Shalev** [denoland/deno#14687]
Hi,
What is the status of [`Atomics.waitAsync`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Atomics/waitAsync) implementation in Deno?

![current support table](https://user-images.githubusercontent.com/909954/169603171-da562318-9914-430a-ba47-c1c3c20192b7.png)

**Comment by cjihrig** [comment]
From what I can tell the API is there and the MDN page is wrong, but maybe I'm missing something.

**Comment by lucacasonato** [comment]
@cjihrig Yup, the MDN page is wrong.

**Comment by Eyal-Shalev** [comment]
Checked with the Deno REPL, and the function does exist.
Not sure why the autocomplete in VSCode didn't suggest it.
Do you guys know if I need to add something special in `deno.jsonc` `compilerOptions.lib`?

**Comment by Eyal-Shalev** [comment]
Found that the definition is missing in the official TypeScript repo.
So closing this issue.

**Comment by cjihrig** [comment]
I've opened https://github.com/mdn/browser-compat-data/pull/16384 to fix the MDN page.

**Comment by Eyal-Shalev** [comment]
the reopen button was clicked by mistake - closing again
