### ISSUE TITLE
`deno bundle`: Please provide a way to pass --config inline

### ISSUE THREAD

**Issue by johnspurlock** [denoland/deno#14682]
Hi there, I'd like to call `deno bundle` with special compilerOptions (setting the libs) at runtime.

Right now, I'm saving out a temp file as the config.json (which requires write access to `$TMPDIR`), running the process, then removing the file, but it would be fantastic if I could provide the configuation inline someway.  Either as inline json, or a data uri, etc

Thanks!

**Comment by johnspurlock** [comment]
This would still be nice

**Comment by joeldesante** [comment]
Can you provide an example of what this would look like? Based on your description I was imagining something like this:

```
deno bundle --config="<config stuff>" .
```

**Comment by johnspurlock** [comment]
I think `deno bundle --config` is already taken (points to a config file).

esbuild uses "raw" terminology (see [tsconfig-raw](https://esbuild.github.io/api/#tsconfig-raw)) to distinguish inline tsconfig json input vs file.

So maybe: `--config-raw` or `--raw-config` or `--inline-config`

Or maybe do some magic and allow json strings in the existing `--config` option.  Easy to tell json from a file-like path.

**Comment by joeldesante** [comment]
I like this idea.
> Or maybe do some magic and allow json strings in the existing `--config` option. Easy to tell json from a file-like path.

I'm going to take a stab at this. But I think we will need more input before a change like this is accepted.

**Comment by kitsonk** [comment]
Suggestions are suggestions. There is no consensus yet. We tag issues that are agreed to be useful as `feat`.  Just letting you know there is a risk that any implementation may not get accepted.

**Comment by joeldesante** [comment]
> Suggestions are suggestions. There is no consensus yet. We tag issues that are agreed to be useful as `feat`.  Just letting you know there is a risk that any implementation may not get accepted.

Right, I understand 🙂
If anything I'll at least learn more about open source development regardless of whether the changes are accepted.

Thanks for the heads-up.

**Comment by lucacasonato** [comment]
`deno bundle` has been deprecated and was removed in Deno 2.
