### ISSUE TITLE
Stabilize "Deno.sleepSync" API

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#14708]
It's been unstable long enough, there's really not much to it.

It would allow to refactor and remove some code from `deno_web` extension, namely `TimerPermissions` trait wouldn't need to have `check_unstable` method.

**Comment by lucacasonato** [comment]
@ry might have objections here. I know he didn't really like the API back when.

**Comment by lucacasonato** [comment]
Also, we should check that the same functionality isn't already possible with just `Atomics`.

**Comment by dsherret** [comment]
Apparently the issue with `Atomics.wait` is that it doesn't currently work in the main worker context?

We discussed this super briefly in the design meeting and if there's a way we could provide a helper in deno.land/std for doing this with `Atomics.wait`, we think that would be preferable.

I do really think we should have a way to sleep synchronously though as it can provide a more accurate sleep mechanism for some non-web server applications (ex. when using hardware).

**Comment by ry** [comment]
sleepSync has no utility - it's very easy to misuse - let's remove it not stabilize it.

**Comment by dsherret** [comment]
> sleepSync has no utility

...for web servers
