### ISSUE TITLE
console.clear is missing.

### ISSUE THREAD

**Issue by ahmedHusseinF** [denoland/deno#1470]
According to the [whatwg spec](https://console.spec.whatwg.org/#clear) for the console object.

I played with the code a little bit  but the stdout stream isn't available in js/console.ts
so any ideas on how to start dealing with this, I would like to contribute.

**Comment by kevinkassimo** [comment]
@ahmedHusseinF `deno.stdout`.
As to clearing the terminal, `console.log("\033[2J\033[1;1H")` is working and we can make it a short hand for `console.clear` (for now before `console.group` lands)

Wanna work on this? (otherwise I would take this task)

**Comment by ahmedHusseinF** [comment]
@kevinkassimo  
it seems that there is an issue with my python as running 
`python2 ./tools/setup.py`

yield python 3 `SyntaxError` print needs parentheses.

so do it and when I dig on the python errors, I will come for `console.group` family

**Comment by kevinkassimo** [comment]
@ahmedHusseinF All right. FYI `console.group` just entered master

**Comment by kevinkassimo** [comment]
@ry This issue could be closed.
