### ISSUE TITLE
 bcrypt is broken on canary version of deno

### ISSUE THREAD

**Issue by ralyodio** [denoland/deno#14700]
Use `deno upgrade --canary` and the `bcrypt.compare(pw, hashed_pw)` function no longer works on accounts created before upgrading. Accounts created using canary DO work.

If you downgrade back to 1.22 `deno upgrade` (remove --canary flag) older accounts can now login but newer accoutns created on --canary can NOT login anymore.

**Comment by neves** [comment]
Confirmed, 1.22.3 is the last working version

**Comment by cjihrig** [comment]
This may be related to https://github.com/denoland/deno/issues/14900

**Comment by neves** [comment]
It is, looks like bcrypt 0.4.0 got it fixed https://github.com/JamesBroadberry/deno-bcrypt/commit/fb6e55a3455520e2bb718ae3036b2b0c3757804e#diff-1e6ca9cef64c48c0a1b40625392ef7400279ef9a23d3ccd80e933c5ee51f2e1dR1196
