### ISSUE TITLE
Excessive garbage collection

### ISSUE THREAD

**Issue by diachedelic** [denoland/deno#14711]
I have just noticed a very odd thing. Node.js seems to be about 4 times faster than Deno or Chrome at running some arithmetic-heavy JavaScript (in my case, generating pseudo-random bytes using the [ISAAC PRNG](http://burtleburtle.net/bob/rand/isaacafa.html)). Upon profiling, I discovered that Node.js seems to run without stopping for garbage collection:

![image](https://user-images.githubusercontent.com/310464/169953459-b8109927-d8ba-4e18-9430-89d637c07947.png)

whereas Deno is stopping for garbage collection every few milliseconds:

![image](https://user-images.githubusercontent.com/310464/169953649-d6b607be-7302-4431-84c6-ae3fdf14c991.png)
![image](https://user-images.githubusercontent.com/310464/169953681-b324163b-d840-4e82-a397-36e26c691425.png)

I thought maybe Node.js had a larger heap limit than Deno by default, so I attempted to increase Deno's heap size and thereby avoid triggering GC

    deno run --v8-flags="--max-old-space-size=4096,--max-semi-space-size=2048" isaac_benchmark.js

but to no avail. Here are some version numbers:

MacBook Pro (13-inch, Mid 2012)
2.9 GHz Dual-Core Intel Core i7
16 GB 1600 MHz DDR3
MacOS Big Sur 11.4

Node.js v17.9.0
v8 9.6.180.15-node.16

deno 1.22.0 (release, x86_64-apple-darwin)
v8 10.0.139.17
typescript 4.6.2

Here is a link to the benchmark: https://gist.github.com/diachedelic/4917abc492457d5f417f1a6ba63703f3.

I am very curious as to why Node.js has such different performance characteristics to Deno when they both use V8.

Thank you all for such a great runtime!

**Comment by stabai** [comment]
I found this issue report while looking into a weird problem I'm noticing. There are times when my test program fails with an OOM, but then works if I do something that logically shouldn't fix it.

For example:
1. Run with `--max-old-space-size=32` (this will fail)
2. Run with `--max-old-space-size=128` (this will succeed)
3. Run with `--max-old-space-size=32` again (this will for some reason succeed)

The code I'm testing this out with is:
```typescript
Deno.test('handles large files', async () => {
  const sizeInMb = 64;
  const filename = await Deno.makeTempFile({ prefix: 'denotestfile' });
  try {
    const chunk = new Uint8Array(1024 * 1024);
    chunk.fill(170);
    for (let i = 0; i < sizeInMb; i++) {
      await Deno.writeFile(filename, chunk, { append: true });
    }
  } finally {
    await Deno.remove(filename);
  }
});

/*
Run via:
deno test -A this_test.ts --v8-flags=--max-old-space-size=32
*/
```

After step 3 above, I can get back into the error state by *increasing or decreasing* the program's `sizeInMb` value. The fact that even decreasing the file size causes the error to return is incredibly baffling to me.

Also, unless I'm missing something huge about the `Deno.writeFile` API, this program looks like it shouldn't be using much more than 1MB of memory anyways (enough to fit the one chunk that gets made). I'm confused about why that would ever fail with `--max-old-space-size=32`.

**Comment by littledivy** [comment]
It's been a long time so I tried out ISAAC PRNG the benchmark with Deno 1.37.0:

```
divy@divy:~/gh/littledivy/deno$ deno run test.mjs
3.102
divy@divy:~/gh/littledivy/deno$ node test.mjs
3.196
```

I think this was a V8 bug that got fixed sometime?
