### ISSUE TITLE
Dynamic import blocked after create a worker

### ISSUE THREAD

**Issue by xiazhang7** [denoland/deno#14726]
Here's an example:

main.ts
```typescript
new Worker(new URL('./worker.ts', import.meta.url), { type: 'module' })
await import('./sub1.ts')
console.log('ok')
```
worker.ts
```typescript
console.log('worker')
```
sub1.ts
```typescript
await import('./sub2.ts')
console.log('sub1')
```
sub2.ts
```typescript
console.log('sub2')
```

Run `main.ts` using `deno run --allow-read main.ts`, it will print
```
sub2
worker
sub1
```
but never print `ok`.

Deno version `1.22.0`

**Comment by bartlomieju** [comment]
I am able to reproduce the hang; it looks like event loop enters "pending" state after evaluating dynamic import and worker instance and is never woken up again.
