### ISSUE TITLE
deno cache produces unusable files

### ISSUE THREAD

**Issue by kyeotic** [denoland/deno#14724]
The `deno cache` command on version `1.22.0` (and possibly earlier ones as well) is converting TS files to `.ts.js` files, but it does not update the imports in the transpiled files. If you attempt to execute one of these files you get a "module not found" error, as it tries to load an import for a file the cache renamed.

Example output (note the double extension)
<img width="255" alt="image" src="https://user-images.githubusercontent.com/1187432/170369971-28ece0be-70d4-4189-905c-fb9f054a870b.png">

And here is the `lambda.ts.js` transpiled file, notice the imports for `.ts` files
<img width="536" alt="image" src="https://user-images.githubusercontent.com/1187432/170370079-e9cef4d1-4725-46fc-8184-7e6ac8b6070c.png">

**Comment by dsherret** [comment]
@kyeotic how are you creating these files? Files cached by `deno cache` end up in the `DENO_DIR` and aren't intended to be executed.

**Comment by kyeotic** [comment]
@dsherret  I am using [these steps from](https://github.com/hayd/deno-lambda#deno_dir-remapping) `deno-lambda`. I don't understand why these files are generated if they are not intended to be used. I want to get compiled JS so that the runtime doesn't need to to any TS overhead once deployed.

**Comment by dsherret** [comment]
@kyeotic if you do `deno cache hello.ts`, it will cache the files that you see above to the DENO_DIR. That will make it so if you run `deno run --no-check hello.ts` there won't be any ts or caching overhead once deployed (not so you can run the files in the cache directory on their own). The files in the DENO_DIR are internal to Deno.

Alternatively, you can use `deno bundle hello.ts` to create a bundled js file or `deno compile hello.ts` to create a self contained executable.

**Comment by kitsonk** [comment]
> I think it would be helpful if this was documented.

What sort of documentation do you suggest?  The format of the `DENO_DIR` is not documented because we don't want people to couple to what is _internal_ behaviour of Deno which doesn't form part of the public API. We have changed the format before, and will likely need to change it again in the future.

**Comment by kyeotic** [comment]
That's that I would suggest documenting: that `deno cache` produces files that are not meant to be consumed directly. As far as I can tell there is no documentation on the `deno cache` command beyond the help text in the cli. It doesn't mentioned transpiling to JS. I ran the command, saw that it produced javascript files, and assumed that I could use them. I can't, but perhaps documentation would have saved me the effort.

**Comment by kitsonk** [comment]
`deno cache` no longer emits code. It is only emitted on execution and no longer cached. Therefore there is nothing to document.
