### ISSUE TITLE
Log on use of deprecated APIs for Deno 2.0

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#14745]
We should start logging on use of these deprecated APIs: https://github.com/denoland/deno/pull/14733

1. Maybe this should log a stack trace in order to make it easy for people to understand where the deprecated API use is occuring.
2. Maybe this should only log once per application run so it doesn't spam users (or maybe once per stack trace?)

**Comment by bartlomieju** [comment]
I guess we need something like [`process.emitWarning`](https://nodejs.org/api/process.html#processemitwarningwarning-options) in Nde

**Comment by ry** [comment]
We should also add some examples to the JSDoc for these deprecated APIs telling people how to use the analogous std APIs.
