### ISSUE TITLE
option to setup/build only use native

### ISSUE THREAD

**Issue by hayd** [denoland/deno#1474]
i.e. without using any prebuilts.
Examples: rust, cargo, rustfmt, v8(?), etc.

This comes up when repos are wanting to build deno from scratch e.g. brew (who are loathe to add binary deps).
Also with Alpine docker to use native musl I think it would have to build or apk each component itself (it can't use the prebuilt because it's not compatible).

Hopefully I'm explaining this correctly..

**Comment by ry** [comment]
The only bundled binaries that are involved in producing the deno executable is chrome's clang toolchain. (We don't bundle rust, so that's out of our hands.) We ought to have some documentation on how to use a system clang installation.

The way it's done is by appending the following line to `target/release/args.gn` 
```
clang_base_path = "/usr/"
```

**Comment by hayd** [comment]
Is this also required for ARM support?

**Comment by anxiousmodernman** [comment]
This flag now exists on **./tools/setup.py**

```
  --no-binary-download  Do not download binaries, must use depot_tools
                        manually
```

**Comment by hayd** [comment]
Is there still some feedback here, the home-brew formula uses this to install https://github.com/Homebrew/homebrew-core/pull/35645/files

Specifically, optionally env look up/pass locations for gn (and sccache)? Also not to use sccache (I think that might be using gn and not setup+build).

**Comment by chrmoritz** [comment]
I think there is still room for improvements here.

Here is [an even simpler homebrew formula](https://gist.github.com/chrmoritz/3dfc9fa7acc720cf5e1289e51662f69c#file-deno-rb) which requires 2 small patches to denos build `./tools` to make it work [using your `setup.py` and `build.py` scripts](https://gist.github.com/chrmoritz/3dfc9fa7acc720cf5e1289e51662f69c#file-deno-rb-L42-L43) by passing [all required options in through environment variables](https://gist.github.com/chrmoritz/3dfc9fa7acc720cf5e1289e51662f69c#file-deno-rb-L37-L40).

* [The first patch to `./tools/third_party.py`](https://gist.github.com/chrmoritz/3dfc9fa7acc720cf5e1289e51662f69c#file-deno-patch-L55-L77) simply adds the option to override the default `gn_path` and `ninja_path` by setting the `DENO_GN_PATH` and `DENO_NINJA_PATH` environment variables. (Not sure if adding 2 new environment variables is the best solution here, but they have to persist to subprocess spawned by `gn`.)
* [The second patch to `./tools/setup.py`](https://gist.github.com/chrmoritz/3dfc9fa7acc720cf5e1289e51662f69c#file-deno-patch-L1-L54) fixes `setup.py`'s `--no-binary-download` option to also disable the download of the `sccache` binary.

Would something like this be acceptable here?

**Comment by hayd** [comment]
@chrmoritz looks great to me!

**Comment by hayd** [comment]
@chrmoritz Please can you make a PR from that branch, this would be really useful outside of brew.
