### ISSUE TITLE
`deno compile --target`: add support for URL targets

### ISSUE THREAD

**Issue by kunring** [denoland/deno#14749]
Currently `deno compile --target` only supports the officially built architectures available on https://dl.deno.land/. For example `aarch64-unknown-linux-gnu` isn't available in the officially maintained builds, but there are community maintained unofficial builds of it.

The suggestion is that a URL target such as `deno compile --target "https://deno.toaxl.com/v1.21.3/deno-aarch64-unknown-linux-gnu.zip"` would download the given file and treat it as a release zip, unzipping and creating a standalone executable.

**Comment by kitsonk** [comment]
I would personally not be supportive of this.  My opinion is that `deno compile` should only support the platforms the Deno officially supports.  Randomly appending other binaries with a bundle (which is what compile effectively does) seems like a bad idea and when it goes wrong or someone uses it as an attack vector, it would be the Deno project that would get the blame.

**Comment by crowlKats** [comment]
Completely agree with Kitson; will close this as we do not want to do this.
