### ISSUE TITLE
deno tasks combined with import maps (feat request)

### ISSUE THREAD

**Issue by oscarotero** [denoland/deno#14760]
Hi.
To run Lume in a project I have this `import_map.json` file:

```json
{
  "imports": {
    "lume/": "https://deno.land/x/lume@v1.9.1/"
  }
}
```

And this `deno.json` file:

```json
{
  "importMap": "import_map.json",
  "tasks": {
    "build": "deno run -A https://deno.land/x/lume@v1.9.1/ci.ts"
  }
}
```

So everytime I want to upgrade the version of Lume I have to edit both files. It would be great if the `build` task could use the import map file to resolve the lume version. I can think of several ways to do this, but not sure what's the best:

## deno run

`deno run` has a broken support for import maps, because it doesn't work for bare imports, only url-like imports. I've opened this issue some time ago #14066

The idea is that `deno run -A lume/ci.ts` could use the actual import map file to resolve to the full url.

## deno eval

The problem of the previous idea is it doesn't comply with the specs, that say that import maps cannot be used for root modules https://github.com/WICG/import-maps#remapping-doesnt-work-for-script.
But the specs say that import maps could work with inlined scripts (`<script type="module">...</script>`), that's is the equivalent of `deno eval`. So the idea is to be able to do the following:

```
deno eval -A "import 'lume/ci.ts';"
```

This doesn't work actually in Deno.

## variable substitution

Another idea is to provide a way to substitute variables similar to GitHub Actions. For example:

```
deno run -A ${{ importMap["lume/"] }}ci.ts
```

`importMap` variable should contain the entries of the import map being used.

**Comment by lucacasonato** [comment]
@oscarotero The `deno eval` works for me. What is not working for y ou?

**Comment by oscarotero** [comment]
@lucacasonato sorry again 😄. I was too fast.
I just changed the build task to the following:

```json
{
  "importMap": "import_map.json",
  "tasks": {
    "build": "deno eval -A \"import 'lume/ci.ts'\""
  }
}
```

But `deno eval` doesn't allow to set permissions:

```
deno task build                                                   
Warning deno task is unstable and may drastically change in the future
Task build deno eval -A "import 'lume/ci.ts'"
error: Found argument '-A' which wasn't expected, or isn't valid in this context

        If you tried to supply `-A` as a value rather than a flag, use `-- -A`

USAGE:
    deno eval [OPTIONS] <CODE_ARG>...

For more information try --help
```

Removing the `-A` flag, the script doesn't fail but do nothing. Maybe I'm doing something wrong?

**Comment by lucacasonato** [comment]
See the last line of the help message.

```
~ ❯❯❯ deno eval --help
deno-eval 
Evaluate JavaScript from the command line.

  deno eval "console.log('hello world')"

To evaluate as TypeScript:

  deno eval --ext=ts "const v: string = 'hello'; console.log(v)"

This command has implicit access to all permissions (--allow-all).
```

To pass arguments:

```
deno eval "import 'lume/ci.ts';" -- -s
```

**Comment by oscarotero** [comment]
Ok, understood. Now it works fine. Thanks!!
