### ISSUE TITLE
Deno panic on resolving a url path

### ISSUE THREAD

**Issue by randallb** [denoland/deno#14762]
I've managed to trigger a panic. Originally i thought it was my insane setup, but now I think it's with recent changes to the path module, or something similar. I reverted my dependency changes and it seems to work now.

https://gist.github.com/randallb/c744fbed7872c92480fab410872a167e

**Comment by dsherret** [comment]
I believe this should be fixed as of #15220 (so 1.24 and above, but try the latest 1.28) since files are now emitted on demand (I can't run the gist because it's missing some files to check). Please let me know if not though.

**Comment by randallb** [comment]
Yeah looks good to go. Thanks!
