### ISSUE TITLE
WebCrypto support for P-521

### ISSUE THREAD

**Issue by diachedelic** [denoland/deno#14766]
It is said that a P-521 key gives the equivalent security of a 256-bit AES key. However, Deno's WebCrypto implementation currently only supports P-256 and P-384 keys.

The WebCrypto roadmap indicates that P-521 support is planned. Are we waiting on P-521 support in dependencies like RustCrypto, or can we proceed?

**Comment by lucacasonato** [comment]
> Are we waiting on P-521 support in dependencies like RustCrypto

Yes, this is the current holdup.

**Comment by littledivy** [comment]
There is already an issue for this (had a typo in the title) https://github.com/denoland/deno/issues/13449

**Comment by lucacasonato** [comment]
I had thought so too, but I couldn't find it because of the typo 😅 

Closing as duplicate #13449
