### ISSUE TITLE
Deno panic when running lots of child processes

### ISSUE THREAD

**Issue by wvbe** [denoland/deno#14778]
Dear Deno maintainer, I got the following request via my terminal;

```
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos aarch64
Version: 1.22.1
Args: ["deno", "run", "--import-map", "../import-map.json", "--allow-all", "../executables/sandbox.ts"]

thread 'main' panicked at 'internal error: entered unreachable code', runtime/errors.rs:61:19
stack backtrace:
   0:        0x104e93788 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h10cf06316d33e2a9
   1:        0x104780804 - core::fmt::write::h1faf18c959c3a8df
   2:        0x104e8e520 - std::io::Write::write_fmt::h86ab231360bc97d2
   3:        0x104e983d0 - std::panicking::default_hook::{{closure}}::h36e628ffaf3cd44f
   4:        0x104e9809c - std::panicking::default_hook::h3ee1564a7544e58f
   5:        0x1046bb538 - deno::setup_panic_hook::{{closure}}::h28567ebc70677265
   6:        0x104e98ec0 - std::panicking::rust_panic_with_hook::h191339fbd2fe2360
   7:        0x104e98c14 - std::panicking::begin_panic_handler::{{closure}}::h91c230befd9929e3
   8:        0x104e98bac - std::sys_common::backtrace::__rust_end_short_backtrace::haaaeebb1d37476b3
   9:        0x104e98b78 - _rust_begin_unwind
  10:        0x10477ebf8 - core::panicking::panic_fmt::h4fe1013b011ef602
  11:        0x1047804d4 - core::panicking::panic::he60bb304466ccbaf
  12:        0x1049d3bb0 - deno_runtime::errors::get_io_error_class::he1030a14b8b0d726
  13:        0x1049d33ec - deno_runtime::errors::get_error_class_name::h182febce679b3e92
  14:        0x1044c4100 - deno::errors::get_error_class_name::hfabafe9efa9657bd
  15:        0x104822aec - deno_core::ops::OpError::new::h9d14d9669cdb3905
  16:        0x104aacc80 - <extern "C" fn(A0) .> R as v8::support::CFnFrom<F>>::mapping::c_fn::h3081f66b6dcbd808
```

This happens consistently when I add a line to my code that runs an order of magnitude _more_ child processes. I'm trying to use Deno to 1) download a lot of bare Git repositories, then 2) retrieve a list of tags for each of them, then 3) run `git log -1` on each of those tags to discover which commit hash they belong to, then 4) get a list of all commits with all info, and combine it with the results from step 3. Adding steps 2 and 3 will cause a panic, presumably because there are now _a lot_ more child processes. Without steps 2 and 3 the script runs beautifully.

Running more of these child processes serially, instead of in parallel, will avoid the panic.

Unfortunately I cannot easily share my code, but at your request I could put in a few hours to make public minimal repro case. Love your work in Deno, please let me know if/how I could help :)

**Comment by mxcl** [comment]
Pretty sure this was happening for us because you have to call `close` on the return from `run` and we weren’t doing that, so eventually we used all the fds or something like that.

**Comment by bartlomieju** [comment]
@mxcl FYI `Deno.run` will get deprecated in Deno 1.31 (though there are no plans to remove it for now). I strongly suggest to migrate to `Deno.Command` API instead at first convenience.

**Comment by mxcl** [comment]
Thanks for the heads up, I'll create a ticket.
