### ISSUE TITLE
Please make it easier to return undefined from an op

### ISSUE THREAD

**Issue by espindola** [denoland/deno#14779]
`None` and `()` are mapped by serde_v8 to `null`, which is reasonable since JSON has `null` but not `undefined`.

I was able to code an op that returns undefined by bypassing the `op` macro:

```
fn foo(scope: &mut v8::HandleScope, _args: v8::FunctionCallbackArguments, mut rv: v8::ReturnValue) {
    let v = v8::undefined(scope).into();
    rv.set(v);
}
...
  let ext = Extension::builder()
        .ops(vec![
            OpDecl {
                is_v8: false,
                name: "foo",
                v8_fn_ptr: foo.map_fn_to(),
                enabled: true,
                is_async: false,
                is_unstable: false,
            },
        ])
        .build();
```

But that is fairly verbose and, if `foo` also needs `op_state`, it needs unsafe code to get it.

Using `#[op(v8)]` I can construct an undefined value, I just cannot return it:

```

#[op(v8)]
fn bar(scope: &mut v8::HandleScope) -> v8::Global<v8::Value> {
    let v: v8::Local<v8::Value> = v8::undefined(scope).into();
    v8::Global::new(scope, v)
}
```

Doesn't compile because it tries to serialize the `v8::Global`. Maybe the `op` macro could bypass serde for functions that return a `v8::Global`?

**Comment by lucacasonato** [comment]
@AaronO Should we just map the unit type `()` to `undefined` instead of `null`? If someone wants `null` they can use `Option::None`.

**Comment by AaronO** [comment]
> @AaronO Should we just map the unit type `()` to `undefined` instead of `null`? If someone wants `null` they can use `Option::None`.

This is already the case for ops (as an "optimization" to skip `ReturnValue::set()`), void functions or `Result<(), ...>` will return undefined, here it appears that @espindola wants conditionally undefined returns, which can be achieved with `core.opSync("op_foo") ?? undefined` JS-side

I get their thinking, if they're doing a key/map lookup it's natural to imitate JS obj/map lookups which return values or `undefined`

**Comment by lucacasonato** [comment]
Right, but if all `()` values in serde_v8 were serialized to `undefined`, one could do:

```rs
#[derive(Serialize)]
#[serde(untagged)]
enum MaybeUndefined<T> {
  Some(T),
  None(()),
}
```

**Comment by espindola** [comment]
> > @AaronO Should we just map the unit type `()` to `undefined` instead of `null`? If someone wants `null` they can use `Option::None`.
> 
> This is already the case for ops (as an "optimization" to skip `ReturnValue::set()`), void functions or `Result<(), ...>` will return undefined, here it appears that @espindola wants conditionally undefined returns, which can be achieved with `core.opSync("op_foo") ?? undefined` JS-side
> 
> I get their thinking, if they're doing a key/map lookup it's natural to imitate JS obj/map lookups which return values or `undefined`

I probably over reduced the example. I want to conditionally return undefined. I have a user defined JSON value (so can be null), and I want to return undefined if no value was set.

**Comment by nayeemrmn** [comment]
Actually I wouldn't call it a workaround, `serde_v8::Value` is precisely for when you want to return a wildcard non-JSON js type such as `MyStructure | undefined`. It just looks a little weird with the `from_v8(to_v8(my_value))` naming but it's meaningful.

**Comment by nayeemrmn** [comment]
Okay, I have it working in a local branch so I forgot but returning `serde_v8::Value<'a>` doesn't work with `#[op(v8)]` at the moment

**Comment by espindola** [comment]
> @espindola As a workaround I think you can make your return type `serde_v8::Value` and return:
> 
> ```rust
> if let Some(my_value) = my_value {
>   let my_value = serde_v8::to_v8(scope, my_value).unwrap();
>   serde_v8::from_v8(scope, my_value).unwrap()
> } else {
>   let undefined = v8::undefined(scope);
>   serde_v8::from_v8(scope, undefined.into()).unwrap()
> }
> ```

I am OK with something like this, but there is still the problem that if a `#[op(v8)]` also needs op_state, it needs unsafe code to get it.

**Comment by littledivy** [comment]
> if a #[op(v8)] also needs op_state

`deno_core::OpState` is optional with `#[op(v8)]`

**Comment by espindola** [comment]
> > if a #[op(v8)] also needs op_state
> 
> `deno_core::OpState` is optional with `#[op(v8)]`

Thanks, I am pretty sure I got a compilation error originally, but it works for me now.

What I have now is

```
#[op(v8)]
fn bar(scope: &mut v8::HandleScope, _op_state: &mut OpState) -> serde_v8::Value<'static> {
    let my_value: Option<()> = Some(());
    if let Some(my_value) = my_value {
        let my_value = serde_v8::to_v8(scope, my_value).unwrap();
        serde_v8::from_v8(scope, my_value).unwrap()
    } else {
        let u: v8::Local<v8::Value> = v8::undefined(scope).into();
        serde_v8::from_v8(scope, u.into()).unwrap()
    }
}
```

So I guess everything is in place as long as the returned value is `'static'.  Cool :-)

**Comment by espindola** [comment]
> ```rust
> fn bar<'a>(scope: &mut v8::HandleScope<'a>, _op_state: &mut OpState) -> serde_v8::Value<'a> { ... }
> ```

Thanks! I had tried putting the lifetime in the `scope: &'a mut`!

**Comment by espindola** [comment]
OK. I guess I will close this as it is now possible to do what I wanted.
