### ISSUE TITLE
Add more platforms to `Deno.build.os`

### ISSUE THREAD

**Issue by AnInternetTroll** [denoland/deno#14799]
Deno runs on FreeBSD [with the help of some patches](https://cgit.freebsd.org/ports/tree/www/deno)
![image](https://user-images.githubusercontent.com/40470127/172024739-27dd1fc8-d9c4-4419-83ac-1828d95695cb.png)

On that build `Deno.build.os` returns `freebsd` but type checking will fail given `Deno.build.os`'s definiton only mentions windows, darwin, and linux.

While deno is officially supported on windows, darwin, and linux, it would be best to add all feasible platforms. [Node includes even more](https://nodejs.org/api/process.html#process_process_platform)

It would be preferable to add all of these platforms at once, as this would be a breaking change

**Comment by nayeemrmn** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/f9987054d73189982e531aecc8105355c74fee26/types/node/process.d.ts#L51 has:
```ts
type Platform = 'aix' | 'android' | 'darwin' | 'freebsd' | 'haiku' | 'linux' | 'openbsd' | 'sunos' | 'win32' | 'cygwin' | 'netbsd';
```
I think we should add the difference to `Deno.build.os`'s type all at once, to avoid breaking on each new platform supported. With the side-effect of being nicer to unsupported platform builds.
```ts
  export const build: {
    os: "aix" | "android" | "cygwin" | "darwin" | "freebsd" | "haiku" | "linux" | "netbsd" | "openbsd" | "sunos" | "windows";
    // ...
  };
```

**Comment by cjihrig** [comment]
> It would be preferable to add all of these platforms at once, as this would be a breaking change

Why is it a breaking change? Adding new platform support should be semver minor.

> Deno runs on FreeBSD [with the help of some patches](https://cgit.freebsd.org/ports/tree/www/deno)

Why don't the patches also update the types?

Also, is there a reason not to try upstreaming the patches so that the support is more official? If the only blocker is having a platform in the CI, you can get pretty far (not necessarily 100% though) with QEMU in GitHub Actions.

**Comment by nayeemrmn** [comment]
> Why is it a breaking change?

Code like this will break: https://github.com/denosaurs/plug/blob/e7763a13a70be136bab389b39313e7043f26d6d5/plug.ts#L35-L44.

Of course, we allow ourselves to e.g. add new optional fields to input interfaces and new mandatory fields to returned interfaces, even though these can break some awkwardly written user code with the way TS works. But this one breaks common and idiomatic code.

**Comment by cjihrig** [comment]
For what it's worth, I've seen other projects (Node.js and libuv) add support for new platforms in non-major releases. I think the reasoning has been that you won't be breaking something that was previously supported.

**Comment by nayeemrmn** [comment]
This issue is about adding entries to the type definition for `Deno.build.os` _despite_ not having official support for those platforms, not about adding support for new platforms.

**Comment by cjihrig** [comment]
I understand what the issue is about 😄. But you're asserting that adding new platforms would be a breaking change without this change, and I'm trying to understand why that is because I don't agree.

I do agree with supporting more values in `Deno.build.os`.

**Comment by nayeemrmn** [comment]
> > Why is it a breaking change?
> 
> Code like this will break: https://github.com/denosaurs/plug/blob/e7763a13a70be136bab389b39313e7043f26d6d5/plug.ts#L35-L44.

when we extend the type of `Deno.build.os` to `"darwin" | "linux" | "windows" | "new_os"`

**Comment by cjihrig** [comment]
Ah, I see what you mean. Sorry for the noise.
