### ISSUE TITLE
Remove ErrorEventInit's error default

### ISSUE THREAD

**Issue by annevk** [denoland/deno#14791]
See https://github.com/whatwg/html/pull/7983 and https://github.com/web-platform-tests/wpt/pull/34297.

**Comment by mrkldshv** [comment]
I'd like to work on this issue!

**Comment by lucacasonato** [comment]
@mrkldshv That sounds good, but please wait until the web platform test changes have actually been merged.

**Comment by annevk** [comment]
Tests landed.
