### ISSUE TITLE
suggestion: lsp support tcp

### ISSUE THREAD

**Issue by linbingquan** [denoland/deno#14802]
I saw `tower-lsp` has tcp example in https://github.com/ebkalderon/tower-lsp/blob/master/examples/tcp.rs

**Comment by kitsonk** [comment]
What would be the use case?

As far as I am aware, all editors currently only support communication over stdin/stdout.

**Comment by linbingquan** [comment]
Thank you for your reply.

TBH, I have no experience with lsp, I studing to how to use `deno lsp`. I don't know how to send jsonrpc request to work with deno, but I can saw some simple response with https://github.com/qualified/lsp-ws-proxy

> What would be the use case?

I am not sure it is really necessary, I saw https://github.com/qualified/lsp-ws-proxy#why

**Comment by kitsonk** [comment]
We should wait until there is an actual use case. Just because something is technically possible doesn't mean we should ship.

Closing as any potential client integration would be considered in context.
