### ISSUE TITLE
Support BundleType::Classic in deno bundle

### ISSUE THREAD

**Issue by dgreensp** [denoland/deno#14805]
Feature request:  It would be very useful IMO for `deno bundle` to have a `--type` or `--bundle-type` flag, which would change the type of bundling (as passed to underlying code here: https://github.com/denoland/deno/blob/0cfdf5cedefe827cd28d9cef006fc78e1c054e98/cli/main.rs#L778).  Especially with `Deno.emit` being removed.

**Comment by kitsonk** [comment]
`deno bundle` is not a general purpose bundle. It's intent it to make single file JavaScript files for Deno to consume. The fact that they also sometimes work in a browser is a side effect. Adding features that are not needed for running code under Deno are out of scope for this feature.

Best to use esbuild (which supports Deno) for bundling for other platforms or consumption.

**Comment by dgreensp** [comment]
I ended up literally just wrapping the output in an IIFE, and that worked for me.
