### ISSUE TITLE
`Deno compile` M1  XHR2 Issue

### ISSUE THREAD

**Issue by About7Sharks** [denoland/deno#14801]
I am unable run the compiled version of [this script](https://gist.github.com/About7Sharks/09b61ce9373fc2ac81bd20de523ea01d) on my mac M1. I am able to compile this on my linux and it runs without any issues. I have tried to set the target flag but that didn't help. 

<img width="566" alt="image" src="https://user-images.githubusercontent.com/30053857/172064808-dd39a89b-457c-46fb-8d90-5116fe90e576.png">

**Comment by kitsonk** [comment]
Can you please provide the output of `deno --version`?

Also you would need to provide a full reproduction.  The file you link to imports two other files that are not part of the gist.

**Comment by About7Sharks** [comment]
@kitsonk After running `deno upgrade` the error is gone. Thanks for the suggestions and I should have thought of that. It would be nice if there was a better error message if anything can be learned from this.
