### ISSUE TITLE
Move `Deno.emit` issues to denoland/deno_emit

### ISSUE THREAD

**Issue by GJZwiers** [denoland/deno#14817]
There are still a number of open issues for `Deno.emit`, which was removed from Deno recently. They should probably be moved to https://github.com/denoland/deno_emit

- denoland/deno_emit#41
- denoland/deno_emit#42
- denoland/deno_emit#43
- denoland/deno_emit#44
- denoland/deno_emit#45
- denoland/deno_emit#46
- denoland/deno_emit#47
- denoland/deno_emit#48
- denoland/deno_emit#49
- denoland/deno_emit#50
- denoland/deno_emit#51
- denoland/deno_emit#52
- denoland/deno_emit#53
- denoland/deno_emit#54
- denoland/deno_emit#55
- denoland/deno_emit#56

**Comment by bartlomieju** [comment]
Thanks, I transferred all issues.
