### ISSUE TITLE
Disallow "Deno.exit()" inside web worker context

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#14818]
@lucacasonato proposed we disallow `Deno.exit()` API in web worker context, or more precisely throw on call to that API to keep backward compatibility by not removing the API. One of the reasons is that in browsers there's no way to close main window from within the worker. Users could still achieve that by sending a message to main worker that could handle it and call `Deno.exit()`, example:
```js
// worker.js

self.onmessage = (e) => {
   // something going on here...
   if (someCondition) {
      self.postMessage("exit");
   }
};
```

```js
// main.js

const worker = new Worker("./worker.js", { type: "module" });

// something going on here

worker.onmessage = (e) => {
  if (e.data == "exit") {
    Deno.exit(10);
  }
};
```

If user tries to call `Deno.exit()` in worker context we would then throw an error like: `Deno.exit() is not allowed in worker context`.

This change would greatly simplify implementing following issues:
- https://github.com/denoland/deno/pull/14814
- https://github.com/denoland/deno/issues/7590
- https://github.com/denoland/deno/issues/13093
- https://github.com/denoland/deno/issues/8713
- https://github.com/denoland/deno/issues/12653
- https://github.com/denoland/deno/issues/14795

**Comment by cjihrig** [comment]
In Node.js, `process.exit()` does not exit the whole process, only that worker thread. I'm +1 to either doing what Node does or throwing an error as suggested here.
