### ISSUE TITLE
Virus warning when compiling with --target=x86_64-pc-windows-msvc

### ISSUE THREAD

**Issue by gerhardmeyer** [denoland/deno#14825]
Hi,

Kaspersky is giving me a virus warning when I compile my application with the --target parameter for windows.  If I remove the target parameter on windows it does not complain. I am just raising this as I do have a work around for now by just excluding the target for windows. I don't get any issues when compiling for linux.

![Capture](https://user-images.githubusercontent.com/39289960/172786010-b72fb819-f6c6-482c-9b21-286149d12e33.PNG)

**Comment by dsherret** [comment]
I don't think there's anything actionable we can do here unless you're actually encountering a virus?

**Comment by cjihrig** [comment]
No followup and likely nothing actionable, so I'll close this out.
