### ISSUE TITLE
deno fmt cannot format cjs

### ISSUE THREAD

**Issue by ayame113** [denoland/deno#14831]
deno fmt doesn't seem to detect files with the extension `cjs`, `cts` or `mts`.

![image](https://user-images.githubusercontent.com/40050810/172880578-8bc40053-9505-4f3e-a844-c1e27e408654.png)

I'm not sure this is a bug, but maybe we need to add an extension to `is_supported_ext_fmt`?

https://github.com/denoland/deno/blob/2c33293f665c4d86a2196c3b2c0aa45b15b533c3/cli/tools/fmt.rs#L702-L720

**Comment by bartlomieju** [comment]
@dsherret what do you think?
