### ISSUE TITLE
cli/lsp/completions.rs - make_relative - Combine with new fs_util function?

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#14840]
I wanted to replace the `make_relative` implementation in the LSP with a new one in fs_util (adding in a deno vendor pr by extracting out from the vendor sub directory that mostly uses the url crate's `make_relative`), but it has a test that I'm not sure why it does this:

https://github.com/denoland/deno/blob/3dd981e199a66b09af072d550514ed2fe300df63/cli/lsp/completions.rs#L691-L695

That can't be made relative so shouldn't that instead return something like an `Err` or `None`?

(Just assign this back to me after if you'd like and I can work on consolidating this code)

This is the new fs_util function: https://github.com/denoland/deno/pull/14836/files#diff-8853aacd3eead79b8e8a49a4dc93deb4262a469d8dbcb190c4dcbb4361e9c877R367

**Comment by kitsonk** [comment]
Possibly. I don't know if the rest of the code properly handles and `Err` or `None`.  The assumption was to always return a value.
