### ISSUE TITLE
Can't import modules with the % character in their names

### ISSUE THREAD

**Issue by brundonsmith** [denoland/deno#14857]
Best I can tell, if a Deno module tries to import another module and that module has a % in its name, the module import fails with `error: Module not found`. Removing the character causes the import to succeed. Behavior is the same for both regular and dynamic imports.

Use-case is that I'm generating some module names from URLs, so I want to `encodeURIComponent()` those URLs in their names so that they don't get misinterpreted as part of the local file path.

Confirmed on the latest release (v1.22.3)

**Comment by nayeemrmn** [comment]
Could you give an example of what the filename/URL is and what your import statement looks like? This is probably a case of a percent encoding `%XY` being decoded and you're not expecting it to.

**Comment by brundonsmith** [comment]
It is an actual character escape, yeah (`%20` was the specific one I used for minimal-repro)

I'm definitely not doing any decoding on my end though, and it doesn't seem like Deno should be doing any decoding either?

**Comment by nayeemrmn** [comment]
If your module URL is `./%20.ts`, it must be imported as:
```ts
import "./%2520.ts";
```
so that it percent decodes to your actual resource name. If your write an import like:
```ts
import "./%20.ts";
```
That will import the resource at `<space>.ts`.

**Comment by nayeemrmn** [comment]
Would base64 encoding work for your use case? Percent encoding doesn't seem like a great idea, as URLs can already contain that.

**Comment by brundonsmith** [comment]
The above solution worked. Thanks for the base64 suggestion, that might work better. Readability here is a nice-to-have but not essential, and the stacking is definitely really unfortunate. Basically I'm caching a bunch of remote modules and then importing them from disk, so it sounds like URI-encoding would require the write path and import path to be different (with the latter's basename double-encoded)
