### ISSUE TITLE
USER deno not working in docker image

### ISSUE THREAD

**Issue by BMogetta** [denoland/deno#14861]
Hello there, i'm building an application with docker, i'm using deno in the backend.  This is my current dockerfile:

FROM denoland/deno:alpine-1.22.1 as base
RUN deno install -qAf --unstable https://deno.land/x/denon@2.5.0/denon.ts
EXPOSE 8000
WORKDIR /usr/app
USER deno
COPY ./config ./config
COPY deps.ts denon.yml mod.ts ./
RUN denon cache
COPY ./src ./src
CMD [ "denon", "start" ]

I'm trying to run the container with a non root user, i tried the sugested USER by the oficial docker repository, but IT WONT execuse neither "denon" or "deno" commands, not in /usr/app/" folder or "/deno-dir/" folder. It allways says: 

#0 1.234 error: Permission denied (os error 13)
#0 1.234     at file:///usr/app/deps.ts:25:8

I explain i also try without denon, but in case someone is wonder why i'm using it in a container without volumes it is for clean code in the dockerfile, i dont want the run cache or cmd line to be extra long.

Also if i run this container with #USER deno (using root user) there is no problem at all

**Comment by hayd** [comment]
Is this breaking on `denon cache` or `denon start` ?
I would usually move the USER deno to the line immediately above CMD.

You could also try adding write permissions to the specific file/directory to the deno user.

**Comment by BMogetta** [comment]
Hello there. i tried different combinations, in every case the container run w/o problems if i comment the user =>

WORKDIR /usr/app
...
USER deno
CMD [ "denon", "start" ]
the error: backend       | error: Permission denied (os error 13) (for '"/deno-dir/gen/file/usr/app/mod.ts.buildinfo"')

----------

WORKDIR /usr/app
...
USER deno
CMD deno run --allow-net --allow-env --allow-read --allow-write --import-map config/import_map.json --lock config/lock.json --cached-only mod.ts
backend       | error: Permission denied (os error 13) (for '"/deno-dir/gen/file/usr/app/mod.ts.buildinfo"')

------------

WORKDIR /deno-dir
..
USER deno
CMD [ "denon", "start" ]
backend       | error: Permission denied (os error 13) (for '"/deno-dir/gen/file/deno-dir/mod.ts.buildinfo"')

-----------

WORKDIR /deno-dir
..
USER deno
CMD deno run ...... mod.ts
backend       | error: Permission denied (os error 13) (for '"/deno-dir/gen/file/deno-dir/mod.ts.buildinfo"')

**Comment by BMogetta** [comment]
i tried this as my last 3 lines, still crash
RUN chown -R deno:deno /usr/app
USER deno
CMD [ "denon", "start" ]

the weird part is that if i remove de "USER deno" let the container run, and bash "ls -l":
/usr/app # ls -l
total 28
drwxr-xr-x    1 deno     deno          4096 Jun 17 02:10 config   
-rwxr-xr-x    1 deno     deno           614 Jun 19 15:39 denon.yml
-rwxr-xr-x    1 deno     deno           557 Jun 16 15:13 deps.ts  
-rwxr-xr-x    1 deno     deno           710 Jun 16 15:13 mod.ts   
drwxr-xr-x    1 deno     deno          4096 Jun 19 16:27 src

**Comment by BMogetta** [comment]
The only solution i found is:
WORKDIR /deno-dir/
RUN chown -R deno:deno /deno-dir
if i try to use de /app folder of the image still gives me error, so i chown to the entire folder

**Comment by DrzwiPercepcji** [comment]
Looks like deno user does not have enough permissions to /app or any another workdir used in Dockerfile, so it is necessary to run `RUN chown -R deno:deno /<workdir>` before running anything. Thanks @BMogetta, I think at least docs on https://hub.docker.com/r/denoland/deno should be updated.
