### ISSUE TITLE
Can i use the compiled file to run my application in production?

### ISSUE THREAD

**Issue by Theryston** [denoland/deno#14872]
I was studying a bit about deno and hosting it somewhere when I saw something in common, it's always said to run `deno run...` but recently I found the [deno compiler](https://deno.land/manual/tools/compiler)

I found the idea of deno to return an already compiled file that can be executed by the computer incredible, in the end this can increase the code's performance a lot, since it is in machine code. so I was in doubt which is really recommended by the community for production, to compile the code into an executable and run it like this running my api with higher performance or run directly with the deno `deno run...`

**Comment by JOTSR** [comment]
Deno does not compile js/ts to machine code. ```deno compile``` merge the deno executable and the bundled script in a self-contained standalone binary. It does not improve performance but allow to obfuscate source and share only a standalone executable, in return the package size is bigger. Compiling is mainly for delilver a signle executable for the client, I think you should prefere ```deno run``` for local or server use as ```deno bundle``` provide the same with lighter file (if deno executable is already aviable) and whitout obfuscation.

**Comment by Theryston** [comment]
> Deno does not compile js/ts to machine code. `deno compile` merge the deno executable and the bundled script in a self-contained standalone binary. It does not improve performance but allow to obfuscate source and share only a standalone executable, in return the package size is bigger. Compiling is mainly for delilver a signle executable for the client, I think you should prefere `deno run` for local or server use as `deno bundle` provide the same with lighter file (if deno executable is already aviable) and whitout obfuscation.

I understand, but this compiled file (.exe) is understood by all operating systems and without the need for this operating system to have deno installed?

**Comment by Theryston** [comment]
> Yes, it's like a zip containing the deno runtime and a obfuscated js bundle. When you run it, it execute internally `deno run some_bundle.js args..`. If you want to increase performance you can take a look to [Deno.dlopen](https://deno.land/manual/runtime/ffi_api) (platform dependent) or use wasm (platform independent). It is also possible to use [V8 snapshot with deno core](https://denolib.gitbook.io/guide/advanced/interaction-with-v8) (AOT js compiling), it's reduce startup time but increase execution time because code can't be reoptimized, and it's complex to use and platform dependent.

Thank you you help me a lot!
