### ISSUE TITLE
lsp: detect import map changes automatically

### ISSUE THREAD

**Issue by kidonng** [denoland/deno#14884]
It seems import map changes require restarting the LSP (e.g. via "Deno: Restart Language Server" in [vscode_deno](https://github.com/denoland/vscode_deno)) in order to take effect, which does not align with the experience of using TypeScript with Node.js (vanilla or even with [PnP](https://yarnpkg.com/features/pnp)), which detect package changes in a few seconds.

This may be eased if editor extensions instruct the LSP restart if changes are made to import maps, but does not fix the fundamental issue. The LSP is expected to detect these changes automatically.

**Comment by bartlomieju** [comment]
This was specifically fixed in v1.23 (https://github.com/denoland/deno/pull/14828), please upgrade and try again.
