### ISSUE TITLE
Cannot update the vendored modules when import map is in output directory

### ISSUE THREAD

**Issue by binyamin** [denoland/deno#14899]
As of Deno v1.23.0, the vendor command modifies the configuration file, to the import-map to `vendor/import_map.json`. Deno will then complain if the user tries to update the vendored modules.

```console
$ deno vendor ./_config.js -f
error: Specifying an import map file (vendor/import_map.json) in the deno vendor output directory is not supported. Please specify no import map or one located outside this directory.
```

This isn't a problem in v1.22.3, since the `deno.json` config file isn't modified.

**Notes**
- Yes, I tested this on both v1.23.0 and v1.22.3
- I have a hunch that this comes from https://github.com/denoland/deno/pull/14836

**Comment by dsherret** [comment]
This behaviour has always existed, but #14836 changed it to automatically add an "importMap" entry to the the deno.json file. If you want to get around this behaviour then you need to specify a different import map file or manually remove the "importMap" entry from the deno.json file. To help make this less annoying, I've opened #14998 which will ignore the import map instead of erroring in the future.

**Comment by binyamin** [comment]
@dsherret What if Deno didn't modify the `deno.json` at all? I feel setting the import-map automatically is  trading a feature for a bug. It's not _expected behavior_ per se; the user won't necessarily _assume_ it will happen.

**Comment by dsherret** [comment]
It gives a message after vendoring that it updated the deno.json and it only does this if a deno.json exists. Some people might like it and others who don't can manually remove the import map from the deno.json. I don't have strong feelings on this though, but I think if someone is vendoring then they would want to then use the vendored files so I think updating the deno.json makes sense. Perhaps though it should prompt instead asking the user if they want to do this. Maybe @lucacasonato has some thoughts.
