### ISSUE TITLE
Configure deno fmt?

### ISSUE THREAD

**Issue by WilliamBehrens** [denoland/deno#14901]
I'm using `deno fmt` in a project and I'm finding the default line length to be way to short for what I want. Is there a way to configure the formatter? I can't seem to find any info in the wiki

**Comment by debarchito** [comment]
Take a look here: https://deno.land/manual/tools/formatter

**Comment by adifyr** [comment]
Is there a way to configure the formatter globally? I'm using the formatter for some of my old node projects as well and would like a line length of 120.
