### ISSUE TITLE
Get files directly from Deno cache

### ISSUE THREAD

**Issue by caramboleyo** [denoland/deno#14904]
Hello,

it would be nice to have a feature to get files from deno cache in plain text.

The more i use deno, the more my code becomes hybrid. Meaning i use a lot of classes 1:1 on the server and in the browser. Right now i have to cache them myself in plain text and send them with the http requests, meaning i have a second cache doing completely the same as the deno cache. It would be nice to have a function like Deno.fromCache() that gets the same file from the cache that import would use, just without executing it (maybe even puts it there if its not present yet).

Regards

**Comment by dsherret** [comment]
See https://github.com/denoland/deno_cache

**Comment by bartlomieju** [comment]
Solution described by David is preferred one.

**Comment by caramboleyo** [comment]
That is just faking a custom cache into the same directory. Thats not a solution, its the same problem like with my redundant cache. The maintainer of that plugin has to monitor all changes to the deno cache forever and keep their fork in sync with it. That will never work out for long.
Also that extensions concept is only working if the location of DENO_DIR is correctly determined (which is not always the case) and writable from your deno app. For example this does not work on denos own [deploy](https://deno.com/deploy).

**Comment by bartlomieju** [comment]
> That is just faking a custom cache into the same directory. Thats not a solution, its the same problem like with my redundant cache. The maintainer of that plugin has to monitor all changes to the deno cache forever and keep their fork in sync with it. That will never work out for long.

That library is maintained by the Deno team and is a preferred solution to interacting with Deno cache. We do update that library if there are changes to the API.

> Also that extensions concept is only working if the location of DENO_DIR is correctly determined (which is not always the case) and writable from your deno app. For example this does not work on denos own [deploy](https://deno.com/deploy).

Why wouldn't it work on Deploy? If you only want to read it should be fine

**Comment by caramboleyo** [comment]
Because it does not use the deno cache files, it tries to create its own folder inside DENO_DIR and then caches its files there. So its a separate cache within its own folders created inside DENO_DIR.

**Comment by dsherret** [comment]
@caramboleyo the /x/cache should use the same cache as the deno cli uses. Would you be able to open an issue in https://github.com/denoland/deno_cache if it does that, showing how it differs?
