### ISSUE TITLE
Deno 1.23.0 parses bin expr as instantiation expr leading to incorrect output

### ISSUE THREAD

**Issue by JamesBroadberry** [denoland/deno#14900]
The following code example outputs "3" on Deno 1.22.3 but outputs "0" on Deno 1.23.0
```ts
let testVariable = 6;
let callCount = 0;
for (let i = 0; i < testVariable >> 1; i++) 
{
    callCount++;
}

console.log(callCount);
```

Adding brackets around the bit shifting gets this problem to be resolved (both version of Deno printing "3"), like so:
```ts
let testVariable = 6;
let callCount = 0;
for (let i = 0; i < (testVariable >> 1); i++) 
{
    callCount++;
}

console.log(callCount);
```

Not sure if it's a problem in Deno or not but thought it'd be worth reporting since it's a breaking change and has caused issues in the bcrypt library.

Also, I'm not sure why but this doesn't seem to apply when running deno test (https://deno.land/std@0.144.0/testing/asserts.ts) and I can't get a test case to produce the same behavior, only when running through `deno run` or the REPL

**Comment by cjihrig** [comment]
I can't reproduce this (see below). Do you have any more details?

```
$ deno --version
deno 1.23.0 (release, x86_64-apple-darwin)
v8 10.4.132.5
typescript 4.7.2
$ cat foo.js 
let testVariable = 6;
let callCount = 0;
for (let i = 0; i < testVariable >> 1; i++)
{
    callCount++;
}

console.log(callCount);
$ deno run foo.js 
3
```

**Comment by cjihrig** [comment]
Actually I can reproduce this with a TypeScript file instead of a JS file.

**Comment by JamesBroadberry** [comment]
Thanks for the quick response.

I should have mentioned that I'm running a `.ts` file directly using Deno, sorry.
Is there an issue with the JS transpiler for v.1.23.0? I wouldn't expect `testVariable >> 1` to transpile to `1`.

**Comment by nayeemrmn** [comment]
This is a bug with swc transpilation, newly the default.

@kdy1 The `i < testVariable >> 1` in the for loop predicate gets wrongly transpiled to `i > 1`, generics?

**Comment by kdy1** [comment]
Can you file an issue?

**Comment by nayeemrmn** [comment]
https://github.com/swc-project/swc/issues/4990
