### ISSUE TITLE
Function to kill a running process

### ISSUE THREAD

**Issue by hayd** [denoland/deno#1494]
There doesn't seem to be a way to kill a process initiated by `run`.
`close` only removes it from the resources list.
A running process continues after the original deno application is complete.

A few options:
1. Kill all running/open processes when deno is exited
2. Close should kill the process.
3. There should be a new function to kill a process.

I favor 1+2.

**Comment by ry** [comment]
Close ought to kill it. And #1 should be true too. I think these are expected behavior.
Thanks for reporting.

**Comment by hayd** [comment]
1. Doesn't appear to be the case, example:
```ts
import { run } from "deno";

const justAMinute = run({
  args: ["python", "-c", "from time import sleep; sleep(60);"]
});

(async () => {
  // 5 seconds
  await new Promise(res => setTimeout(res, 5000));
  // justAMinute.close();
})();

// python is still running
```
This stemmed from [this close](https://github.com/denoland/deno_std/blob/c42686dc36ba888137fe734c59318466f41d7dfa/test.ts#L34) in the deno_std test not cleaning up the file_server. Which I can also still replicate.... Could this be that the .close is not waiting for the response? It's weird as in the example above adding the close does work as expected.
If I add an await for a second after this line (in test.ts) it does clean up for me.

Note/Aside: If you `kill -9` an application, e.g. python, they usually won't kill of their child processes (I assume this is a unix standard)...

**Comment by hayd** [comment]
I wonder if [std::process::exit](https://doc.rust-lang.org/std/process/fn.exit.html) is the issue and we're not calling all the destructors.

> Note that because this function never returns, and that it terminates the process, no destructors on the current stack or any other thread's stack will be run. If a clean shutdown is needed it is recommended to only call this function at a known point where there are no more destructors left to run.

From the documentation it reads like this ought to be dropped (and closed).

---

This seems similar to #1517  cc @kevinkassimo ....

**Comment by kevinkassimo** [comment]
@hayd I'll also investigate. Thanks for pinging me

**Comment by bartlomieju** [comment]
@hayd any update on this?

**Comment by kevinkassimo** [comment]
Sorry... Working on this (seems easy enough to fix)

**Comment by kevinkassimo** [comment]
Hmm I have just tested, it seems that the example @hayd provides is working now with latest release...
