### ISSUE TITLE
Support `$DENO_PROXY` for deno registry mirror

### ISSUE THREAD

**Issue by ahuigo** [denoland/deno#14948]
As far as I know, **deno** supports `export HTTPS_PROXY ` and we could use it to redirect all DENO's network traffic to DENO registry mirror.

Since the DENO mirror server doesn't have proxied server's certificate, it can't provide ability to cache packages.

I think it would be better to provide a variable `$DENO_PROXY` like `$GOPROXY` to support registry mirror.

**Comment by kitsonk** [comment]
Deno is not designed to be tied to `deno.land/x` and treats any HTTP/HTTPS server as a potential source of code. We would want to preserve that. So there is no single registry to proxy.

The easiest way to proxy `deno.land/x` would be to use an import map like:

```json
{
  "imports": {
    "https://deno.land/x/": "https://some.other.host/"
  }
}
```

Respectfully declined.
