### ISSUE TITLE
Preloading modules

### ISSUE THREAD

**Issue by mfulton26** [denoland/deno#14956]
I want to be able to start up Deno scripts fast even for deep dependency trees and/or an empty Deno cache.

I was originally thinking server push but today I learned that [HTTP/2 Push is dead](https://evertpot.com/http-2-push-is-dead/) (thank you @lucacasonato).

This could be done via `Link: rel=preload` response headers so that Deno is able to be informed of transitive dependencies/modules long before its even fetched a module that imports them so that the cache can be populated faster and lower overall perceived latency, etc.

See also https://github.com/denoland/dotland/issues/2205.

**Comment by kitsonk** [comment]
This is complex and impractical to implement, with likely little value. If you want to ensure all dependencies are cached before attempting to run a workload `deno cache` is the way to go.

Respectfully declined.

**Comment by mfulton26** [comment]
> This is complex and impractical to implement, with likely little value. If you want to ensure all dependencies are cached before attempting to run a workload `deno cache` is the way to go.
> 
> Respectfully declined.

Understood. Thank you for the consideration.
