### ISSUE TITLE
🙏🏻 `Deno.inspect()` should conform to NodeJS quoting behavior (or allow customization)

### ISSUE THREAD

**Issue by rivy** [denoland/deno#14969]
`Deno.inspect()` varies from the NodeJS implementation by giving double quotes priority for formatting strings. The only note about this is that "we prefer double quotes as the default" without further explanation.

https://github.com/denoland/deno/blob/eadf943e594a5ebf95ddf7e007cfb7d2dcff130e/ext/console/02_console.js#L698-L719

This choice is unfortunate as it varies from NodeJS, making simple output comparisons for testing impossible.

It's also known to be a much worse reading environment for accessibility, adding unneeded visual clutter.

Changing this back to the NodeJS behavior is simple and, IMO, desirable. Alternatively, adding an option such as a `quotePriority` array to `Deno.InspectOptions` would be an alternative which preserves current behavior but allows reversion to the NodeJS behavior.

Thanks for the consideration.

**Comment by lucacasonato** [comment]
I am in favour of keeping the current default, because it matches the quote default for strings in `deno fmt`.

**Comment by dsherret** [comment]
I don't think we need to add another option here. For testing purposes it seems easy enough to add a reusable function to do the comparison that handles the difference between the runtimes.

**Comment by rivy** [comment]
Thank you both for commenting on this issue.

I do understand the appeal of keeping the default as is, in correspondence with the `deno fmt` choice.

But the choice of quote priority is quite variant across code bases (and languages). There are large JS code bases (Google, Angular, ...) which state that "good practice" is using single quotes when possible (while avoiding internal escapes). Given the different priorities in the wild, I believe that being able to choose would be beneficial. 

Visual accessibility would also trend toward using single quotes as double quotes are more visibly noisy than single quotes, especially in large batches, like you would see when inspecting variables.

I also think it would be much easier to add a customization option to `Deno.InspectOptions` than to design a function that normalized the output of `Deno.inspect()` and NodeJS `inspect()`. Just dealing with the corner cases seems like a significant complexity jump over the, IMO, simple addition of a `quotePriority` array. And I don't think that adding that option would impact the complexity of the Deno `inspect()` function much at all. It could be implemented quite simply and clearly from the current implementation with just a few lines of code.

Thanks for the consideration.
