### ISSUE TITLE
Revoke permissions is not working

### ISSUE THREAD

**Issue by onepseudoxy** [denoland/deno#14966]
I tried to run the last code snippet in the section 'Revoke permissions' present in your web page 'https://deno.land/manual/runtime/permission_apis', using the command line "deno run --allow-read=/foo main.ts": but, I don't get expected output. Following is what I get:

> D:\vsc\tools\runtimes\deno\deno-aio-ot\src>deno run --allow-read=/foo main.ts
PermissionStatus { state: "prompt", onchange: null }
PermissionStatus { state: "prompt", onchange: null }

I'm ran the code on windows 10 (uefi without csm) besides Ubuntu and in both cases it's not working.
In case of Windows, The folder D:\vsc\tools\runtimes\deno\deno-aio-ot\src contain the file "main.ts" and the folder "foo", and the later contains "bar" folder.

Following is the output of running "deno --version" command

> deno --version
deno 1.23.0 (release, x86_64-pc-windows-msvc)
v8 10.4.132.5
typescript 4.7.2

**Comment by lucacasonato** [comment]
This docs page was written assuming UNIX file paths, not Windows ones. On Windows you probably need to update the file paths to be a proper Windows style path.

**Comment by nayeemrmn** [comment]
Oh those docs are out of date as of #12159, I forgot to update them

**Comment by onepseudoxy** [comment]
I just noticed that revoking the weak permission desc, revoke also the strong one strongDesc, look at the output of the following code snippet

> // deno run --allow-read=/foo main.ts
const desc = { name: 'read', path: '/foo/bar' } as const;
const strongDesc = { name: 'read', path: '/foo' } as const;
console.log(await Deno.permissions.query(desc));
console.log(await Deno.permissions.revoke(desc)); // Insufficient.
console.log(await Deno.permissions.query(strongDesc));
// PermissionStatus { state: "granted" }
await Deno.permissions.revoke(strongDesc); // Good.
console.log(await Deno.permissions.query(desc));
// PermissionStatus { state: "prompt" }


The output is:

> deno run --allow-read=/foo main.ts
PermissionStatus { state: "granted", onchange: null }
PermissionStatus { state: "prompt", onchange: null }
PermissionStatus { state: "prompt", onchange: null }
PermissionStatus { state: "prompt", onchange: null }
