### ISSUE TITLE
bundled file cannot serve

### ISSUE THREAD

**Issue by jiawei397** [denoland/deno#14974]
Here is my project：https://deno.land/x/oak_nest@v1.11.0 and my Deno version is 1.23.1.

Here is how to reproduce my question.

Be sure current dir has one tsconfig.json like this:
```json
{
  "compilerOptions": {
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "strictPropertyInitialization": false
  }
}
```
Then run :
```shell
deno run --allow-net --allow-env --allow-write --allow-read --config tsconfig.json --unstable https://deno.land/x/oak_nest@v1.11.0/example/main.ts
```
This will normal serve
![image](https://user-images.githubusercontent.com/19886374/175888249-91279b3a-b29c-484a-8b55-5b97c9b686db.png)

But when I bundle this file to js:
```shell
deno bundle https://deno.land/x/oak_nest@v1.11.0/example/main.ts  main.js
```
Then run this js:
```shell
deno run --allow-net --allow-env --allow-write --allow-read --config tsconfig.json --unstable main.js
```
It called error:
```
error: Uncaught SyntaxError: Identifier 'mod' has already been declared
const mod = {
      ^
    at <anonymous> (file:///C:/wk/deno/deno-oak-nest/main.js:2037:7)
```
I know that packaging and merging is a complex thing, but I hope deal with the same name orders of parameters such as rollup or webpack.

**Comment by lucacasonato** [comment]
`deno bundle` was deprecated and has been removed in Deno 2.
