### ISSUE TITLE
why tls rejectUnauthorized is always true in Deno?

### ISSUE THREAD

**Issue by masx200** [denoland/deno#14972]
why tls rejectUnauthorized is always true in Deno?

**Comment by masx200** [comment]
https://deno.land/std@0.145.0/node/_tls_wrap.ts?codeview=#L280

**Comment by masx200** [comment]
https://doc.deno.land/deno/stable/~/Deno.connectTls

**Comment by masx200** [comment]
https://doc.deno.land/deno/unstable/~/Deno.connectTls

**Comment by masx200** [comment]
Since the unencrypted http/2 protocol is not supported, if you want to use http/2 in the local area network, you can only use the self-signed certificate to open the http/2 service. This requires the client not to check certificate validity.

**Comment by lucacasonato** [comment]
Because there is no point to using TLS without verification. You can just use plain text then and save yourself some CPU cycles.

**Comment by masx200** [comment]
Local testing https is also one of the common application scenarios.
