### ISSUE TITLE
No apparent use case for `deno task --no-config`

### ISSUE THREAD

**Issue by GJZwiers** [denoland/deno#14971]
There seems to be no scenario for using `--no-config` together with `deno task`, because the command always needs a config file to work with. Currently running `deno task --no-config` just throws:

```
Warning deno task is unstable and may drastically change in the future
error: No config file found
```

If there is a config file with a non-default name, then using just `--config` works without any need for `--no-config` as well.

**Comment by bartlomieju** [comment]
Yes, this seems like an actual bug.
