### ISSUE TITLE
Private Types Leaking via Default Namespace Type Visibility Behavior

### ISSUE THREAD

**Issue by sno2** [denoland/deno#14976]
Hello, I realized in #14968 that our private types in the Deno unstable namespace were leaking because of the default export behavior of types in namespaces.  Here's an example:

```ts
declare namespace NoExport {
  type b = 23;
}

type a = NoExport.b; // works fine 😯
```

The same behavior applies to all of the utility types in `deno.unstable.d.ts` such as `NativeNumberType`, `ToNativeParameterTypes`, ect.  Adding `export {}` is the solution to this unexpected behavior:

```ts
declare namespace InclExport {
  export {};

  type b = 23;
}

type b = InclExport.b; // error: Namespace 'InclExport' has no exported member 'b'.(2694)
```

There is one instance of this in the `lib.deno.ns.d.ts` for `ResourceMap` however it should be explicitly exported as it is returned from a function.

**Comment by lino-levan** [comment]
I may be wrong but this looks like it's been resolved?
