### ISSUE TITLE
Suggestion: Code lens for bdd tests

### ISSUE THREAD

**Issue by JorchRL** [denoland/deno#15011]
Currently the LSP does not provide code lens for tests written in the BDD style using the `std/testing/bdd` module from the standard library. Is this something that may be planned? Or that would be possible to implement? :sweat_smile: 

Here's a screenshot on how to reproduce:

![Screenshot from 2022-06-29 12-34-16](https://user-images.githubusercontent.com/27286509/176500319-c21b73d4-32ed-4a88-a286-3aed81c6b8c8.png)

Versions I'm using:
- Deno: 1.23.1
- Deno extension: 3.13.0
- std: 0.145.0

**Comment by dsherret** [comment]
I think this is #14804?

**Comment by JorchRL** [comment]
Ohh sorry about that then. I searched the issues for "codelens" and couldn't find it. 

Thank you!
