### ISSUE TITLE
Respect Microsoft Policy for locations of configuration and data files

### ISSUE THREAD

**Issue by wmstack** [denoland/deno#15038]
[From Microsoft Desktop App Requirements](https://docs.microsoft.com/en-gb/windows/win32/win_cert/certification-requirements-for-windows-desktop-apps) (Edited)
> 10.3 Your app data, which must be shared among users on the computer, should be stored within ProgramData 
> 10.4 Your app's data that is exclusive to a specific user and that is not to be shared with other users of the computer, must be stored in `Users\<username>\AppData `
> 10.5 Your app must never write directly to the "Windows" directory and or subdirectories

I am not asking that `.deno/` directory becomes optionally movable to a different location. I am asking that the default location should comply with Windows Policies so that the user experience is optimal. It should be somewhere in `%appdata%`

Windows is not Linux. The home directory is no place for binary apps or any apps at all. Neither is something as audacious as the xdg_spec the appropriate lens through which to store configuration data in Windows. The home directory should just contain my documents, desktop, downloads, favourites and so on. It doesn't need to contain `.bin/`, `.deno/`, `.config/` or the sort. It looks **odd** when you see such files lingering around. Those should be where they are supposed to be, without having to configure a `DENO_PATH` or whatnot. Of course, I am not amused.

If they were so common as to warrant keeping them in the home directory, I would've added them to quick access if I so needed. If every app did the same as Deno does right now, our home directories would be filled with dotfiles and dotdirectories according to everyone's opinionated tastes, instead of following an established organizational structure.

Kind regards.
p.s. Same style as in https://github.com/microsoft/vscode/issues/111446

**Comment by dsherret** [comment]
We're storing all of deno's app data in app data:

```
> deno info
DENO_DIR location: C:\Users\david\AppData\Local\deno
Remote modules cache: C:\Users\david\AppData\Local\deno\deps
Emitted modules cache: C:\Users\david\AppData\Local\deno\gen
Language server registries cache: C:\Users\david\AppData\Local\deno\registries
Origin storage: C:\Users\david\AppData\Local\deno\location_data
```

I don't see anything in those policies that suggests a program's executable files should be in `ProgramData` or `AppData`.

Many binaries on Windows go to `~/.<app-name>` and my home directory is full of them. If you want a different install directory you can set `DENO_INSTALL` environment variable.

**Comment by dsherret** [comment]
I'm going to close this one. As mentioned, we're storing all of deno's app data in local app data already. Also, we're not part of the Win 10 Desktop App Certification Program.

It's nice how we install our app the same way on every operating system ($HOME/.deno) so we can tell people to go there without having to say some operating specific thing. There are also many tools such as rust that install to a dot folder in the home directory.
