### ISSUE TITLE
Ubuntu20.04.1  Can't compile from source. 

### ISSUE THREAD

**Issue by luhuaipei** [denoland/deno#15030]
Linux hlu 5.13.0-51-generic #58~20.04.1-Ubuntu SMP Tue Jun 14 11:29:12 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

   Compiling swc_ecma_transforms_base v0.89.6
   Compiling swc_ecma_transforms_optimization v0.131.0
   Compiling swc_ecma_transforms_classes v0.77.0
   Compiling swc_ecma_transforms_react v0.120.0
   Compiling swc_ecma_transforms_proposal v0.112.0
   Compiling swc_ecma_transforms_typescript v0.124.0
   Compiling deno_ast v0.16.0
   Compiling deno_lint v0.31.0
   Compiling zstd v0.11.1+zstd.1.5.2
   Compiling deno_snapshots v0.1.0
   Compiling deno v1.23.2
error: failed to run custom build command for `deno_snapshots v0.1.0`

Caused by:
  process didn't exit successfully: `/tmp/cargo-installfeINgm/release/build/deno_snapshots-dd3e17cea3726ddb/build-script-build` (exit status: 101)
  --- stdout
  Snapshot size: 2148688
  Snapshot compressed size: 548605
  Snapshot written to: /tmp/cargo-installfeINgm/release/build/deno_snapshots-237d1d0711b24327/out/CLI_SNAPSHOT.bin 
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.deno_webgpu.d.ts
  cargo:rerun-if-changed=/home/huaipei/.cargo/registry/src/github.com-1ecc6299db9ec823/deno_url-0.59.0/lib.deno_url.d.ts
  cargo:rerun-if-changed=/home/huaipei/.cargo/registry/src/github.com-1ecc6299db9ec823/deno_crypto-0.73.0/lib.deno_crypto.d.ts
  cargo:rerun-if-changed=/home/huaipei/.cargo/registry/src/github.com-1ecc6299db9ec823/deno_webstorage-0.54.0/lib.deno_webstorage.d.ts
  cargo:rerun-if-changed=/home/huaipei/.cargo/registry/src/github.com-1ecc6299db9ec823/deno_web-0.90.0/lib.deno_web.d.ts
  cargo:rerun-if-changed=/home/huaipei/.cargo/registry/src/github.com-1ecc6299db9ec823/deno_broadcast_channel-0.53.0/lib.deno_broadcast_channel.d.ts
  cargo:rerun-if-changed=/home/huaipei/.cargo/registry/src/github.com-1ecc6299db9ec823/deno_fetch-0.82.0/lib.deno_fetch.d.ts
  cargo:rerun-if-changed=/home/huaipei/.cargo/registry/src/github.com-1ecc6299db9ec823/deno_websocket-0.64.0/lib.deno_websocket.d.ts
  cargo:rerun-if-changed=/home/huaipei/.cargo/registry/src/github.com-1ecc6299db9ec823/deno_console-0.59.0/lib.deno_console.d.ts
  cargo:rerun-if-changed=/home/huaipei/.cargo/registry/src/github.com-1ecc6299db9ec823/deno_net-0.51.0/lib.deno_net.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.deno.window.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.deno.worker.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.deno.shared_globals.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.deno.ns.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.deno.unstable.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es5.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2015.collection.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2015.core.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2015.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2015.generator.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2015.iterable.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2015.promise.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2015.proxy.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2015.reflect.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2015.symbol.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2015.symbol.wellknown.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2016.array.include.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2016.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2017.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2017.intl.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2017.object.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2017.sharedmemory.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2017.string.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2017.typedarrays.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2018.asyncgenerator.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2018.asynciterable.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2018.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2018.intl.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2018.promise.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2018.regexp.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2019.array.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2019.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2019.object.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2019.string.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2019.symbol.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2020.bigint.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2020.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2020.date.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2020.intl.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2020.number.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2020.promise.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2020.sharedmemory.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2020.string.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2020.symbol.wellknown.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2021.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2021.intl.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2021.promise.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2021.string.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2021.weakref.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2022.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2022.array.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2022.error.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2022.intl.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2022.object.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2022.string.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.esnext.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.esnext.array.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.esnext.intl.d.ts

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /home/huaipei/.cargo/registry/src/github.com-1ecc6299db9ec823/deno_snapshots-0.1.0/build_tsc.rs:316:6
  stack backtrace:
     0:     0x55b2f4c626cd - std::backtrace_rs::backtrace::libunwind::trace::hee598835bc88d35b
                                 at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
     1:     0x55b2f4c626cd - std::backtrace_rs::backtrace::trace_unsynchronized::h9cdc730ba5cf5d72
                                 at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:     0x55b2f4c626cd - std::sys_common::backtrace::_print_fmt::h75aeaf7ed30e43fa
                                 at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:66:5
     3:     0x55b2f4c626cd - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h606862f787600875
                                 at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:45:22
     4:     0x55b2f4c8897c - core::fmt::write::he803f0f418caf762
                                 at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/fmt/mod.rs:1190:17
     5:     0x55b2f4c5aaa8 - std::io::Write::write_fmt::h70bc45872f37e7bb
                                 at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/io/mod.rs:1657:15
     6:     0x55b2f4c64ba7 - std::sys_common::backtrace::_print::h64d038cf8ac3e13e
                                 at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:48:5
     7:     0x55b2f4c64ba7 - std::sys_common::backtrace::print::h359300b4a7fccf65
                                 at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:35:9
     8:     0x55b2f4c64ba7 - std::panicking::default_hook::{{closure}}::hf51be35e2f510149
                                 at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:295:22
     9:     0x55b2f4c64870 - std::panicking::default_hook::h03ca0f22e1d2d25e
                                 at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:314:9
    10:     0x55b2f4c652f9 - std::panicking::rust_panic_with_hook::h3b7380e99b825b63
                                 at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:698:17
    11:     0x55b2f4c64fe7 - std::panicking::begin_panic_handler::{{closure}}::h8e849d0710154ce0
                                 at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:588:13
    12:     0x55b2f4c62b94 - std::sys_common::backtrace::__rust_end_short_backtrace::hedcdaddbd4c46cc5
                                 at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:138:18
    13:     0x55b2f4c64cf9 - rust_begin_unwind
                                 at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
    14:     0x55b2f1f73cf3 - core::panicking::panic_fmt::he1bbc7336d49a357
                                 at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
    15:     0x55b2f1f73de3 - core::result::unwrap_failed::h719f957ed74f93fd
                                 at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/result.rs:1749:5
    16:     0x55b2f1fda97d - core::result::Result<T,E>::unwrap::hd6b9a7244b89197b
    17:     0x55b2f1fa4594 - build_script_build::build_tsc::get_js_files::h83ac82d944752ead
    18:     0x55b2f1fa3c71 - build_script_build::build_tsc::load_js_files::habce16afe8634d28
    19:     0x55b2f1fa20cc - build_script_build::build_tsc::create_tsc_snapshot::h619ce5a1d24bb487
    20:     0x55b2f1fdfbe2 - build_script_build::main::h1cad9a260acbf19c
    21:     0x55b2f1fc5b83 - core::ops::function::FnOnce::call_once::h67761f58ccea8482
    22:     0x55b2f1fe2169 - std::sys_common::backtrace::__rust_begin_short_backtrace::hd4588ca608196a74
    23:     0x55b2f1fdacf9 - std::rt::lang_start::{{closure}}::haa29586824a827b1
    24:     0x55b2f4c61db1 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hb7014f43484a8b4e
                                 at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:259:13
    25:     0x55b2f4c61db1 - std::panicking::try::do_call::h7bc9dc436daeb8c7
                                 at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:492:40
    26:     0x55b2f4c61db1 - std::panicking::try::h653d68a27ff5f175
                                 at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:456:19
    27:     0x55b2f4c61db1 - std::panic::catch_unwind::h9d739f9f59895e68
                                 at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panic.rs:137:14
    28:     0x55b2f4c61db1 - std::rt::lang_start_internal::{{closure}}::hf006f2bc7ce22bbe
                                 at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/rt.rs:128:48
    29:     0x55b2f4c61db1 - std::panicking::try::do_call::hfb39d6df61a2e69f
                                 at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:492:40
    30:     0x55b2f4c61db1 - std::panicking::try::h13e2d225134958ac
                                 at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:456:19
    31:     0x55b2f4c61db1 - std::panic::catch_unwind::h3bd49b5a5dfb1a50
                                 at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panic.rs:137:14
    32:     0x55b2f4c61db1 - std::rt::lang_start_internal::h2ba92edce36c035e
                                 at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/rt.rs:128:20
    33:     0x55b2f1fdace1 - std::rt::lang_start::hbbe04814228b9be1
    34:     0x55b2f1fe2823 - main
    35:     0x7f8f344ad083 - __libc_start_main
                                 at /build/glibc-SzIz7B/glibc-2.31/csu/../csu/libc-start.c:308:16
    36:     0x55b2f1f74b5e - _start
    37:                0x0 - <unknown>
warning: build failed, waiting for other jobs to finish...
error: failed to compile `deno v1.23.2`, intermediate artifacts can be found at `/tmp/cargo-installfeINgm`

Caused by:
  build failed

**Comment by ctronp** [comment]
same error, can't compile on fedora 36

**Comment by dee-sea** [comment]
Same error on Void Linux

**Comment by kentor** [comment]
Same here, on ubuntu 20.04 on an ARM vm

**Comment by westernwontons** [comment]
Same error on MacOS 12.4

**Comment by josiah-roberts** [comment]
+1, facing this on Pop!_OS 22.04 LTS.

**Comment by immutable-pro** [comment]
Same, Ubuntu 22.04 LTS

**Comment by bartlomieju** [comment]
Thanks for reports, I'm fixing this problem right now.

**Comment by luhuaipei** [comment]
I'm still got errors using using updated code.

My code status:
![Uploading image.png…]()


**ERROR**
`error: failed to run custom build command for `deno_snapshots v0.1.0`

Caused by:
  process didn't exit successfully: `/tmp/cargo-install30zTqN/release/build/deno_snapshots-5d2af0c0924ae010/build-script-build` (exit status: 101)
  --- stdout
  Snapshot size: 2148688
  Snapshot compressed size: 548605
  Snapshot written to: /tmp/cargo-install30zTqN/release/build/deno_snapshots-5c8bb8085c9667c4/out/CLI_SNAPSHOT.bin 
  cargo:rerun-if-changed=/home/huaipei/.cargo/registry/src/github.com-1ecc6299db9ec823/deno_fetch-0.82.0/lib.deno_fetch.d.ts
  cargo:rerun-if-changed=/home/huaipei/.cargo/registry/src/github.com-1ecc6299db9ec823/deno_url-0.59.0/lib.deno_url.d.ts
  cargo:rerun-if-changed=/home/huaipei/.cargo/registry/src/github.com-1ecc6299db9ec823/deno_websocket-0.64.0/lib.deno_websocket.d.ts
  cargo:rerun-if-changed=/home/huaipei/.cargo/registry/src/github.com-1ecc6299db9ec823/deno_webstorage-0.54.0/lib.deno_webstorage.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.deno_webgpu.d.ts
  cargo:rerun-if-changed=/home/huaipei/.cargo/registry/src/github.com-1ecc6299db9ec823/deno_net-0.51.0/lib.deno_net.d.ts
  cargo:rerun-if-changed=/home/huaipei/.cargo/registry/src/github.com-1ecc6299db9ec823/deno_broadcast_channel-0.53.0/lib.deno_broadcast_channel.d.ts
  cargo:rerun-if-changed=/home/huaipei/.cargo/registry/src/github.com-1ecc6299db9ec823/deno_console-0.59.0/lib.deno_console.d.ts
  cargo:rerun-if-changed=/home/huaipei/.cargo/registry/src/github.com-1ecc6299db9ec823/deno_web-0.90.0/lib.deno_web.d.ts
  cargo:rerun-if-changed=/home/huaipei/.cargo/registry/src/github.com-1ecc6299db9ec823/deno_crypto-0.73.0/lib.deno_crypto.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.deno.window.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.deno.worker.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.deno.shared_globals.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.deno.ns.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.deno.unstable.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es5.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2015.collection.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2015.core.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2015.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2015.generator.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2015.iterable.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2015.promise.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2015.proxy.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2015.reflect.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2015.symbol.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2015.symbol.wellknown.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2016.array.include.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2016.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2017.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2017.intl.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2017.object.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2017.sharedmemory.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2017.string.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2017.typedarrays.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2018.asyncgenerator.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2018.asynciterable.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2018.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2018.intl.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2018.promise.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2018.regexp.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2019.array.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2019.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2019.object.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2019.string.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2019.symbol.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2020.bigint.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2020.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2020.date.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2020.intl.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2020.number.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2020.promise.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2020.sharedmemory.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2020.string.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2020.symbol.wellknown.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2021.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2021.intl.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2021.promise.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2021.string.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2021.weakref.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2022.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2022.array.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2022.error.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2022.intl.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2022.object.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2022.string.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.esnext.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.esnext.array.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.esnext.intl.d.ts

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /home/huaipei/.cargo/registry/src/github.com-1ecc6299db9ec823/deno_snapshots-0.1.0/build_tsc.rs:316:6
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:584:5
     1: core::panicking::panic_fmt
               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/panicking.rs:142:14
     2: core::result::unwrap_failed
               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/result.rs:1785:5
     3: core::result::Result<T,E>::unwrap
     4: build_script_build::build_tsc::get_js_files
     5: build_script_build::build_tsc::load_js_files
     6: build_script_build::build_tsc::create_tsc_snapshot
     7: build_script_build::main
     8: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `deno v1.23.2`, intermediate artifacts can be found at `/tmp/cargo-install30zTqN`
`

**Comment by dsherret** [comment]
Should be fixed now in 1.23.3.

**Comment by luhuaipei** [comment]
Verified. Thx.
