### ISSUE TITLE
Dynamic local import always tries to get fetched from URL when running from deno.land package install

### ISSUE THREAD

**Issue by jukefr** [denoland/deno#15035]
Hello,

I have this scenario:
`a.ts` file creates a `b.ts` file and dynamically imports it later inside `a.ts`.

Locally it works as expected.

However, once the package is pulled through deno.land (`deno install --name readme-manager --reload --allow-all https://deno.land/x/readme_manager@v1.4.2/mod.ts` and run locally I get an error telling me that the `b.ts` file it is tried to resolve is a URL.

```bash
Download https://deno.land/home/user/.config/readme-manager/mod.ts
error: Uncaught (in promise) TypeError: Module not found "https://deno.land/home/user/.config/readme-manager/mod.ts".
    at async mod (https://deno.land/x/readme_manager@v1.4.2/mod.ts:122:31)
    at async https://deno.land/x/readme_manager@v1.4.2/mod.ts:164:1
```

Is this intended or a bug and is there anything I can do to make this work 

note: I tried with absolute and relative paths to see if it was to do with that but same outcome with both pathing formats.

**Comment by nayeemrmn** [comment]
https://deno.land/x/readme_manager@v1.4.2/mod.ts#L122 Is this the import in question? Change it to:
```ts
import { toFileUrl } from "https://deno.land/std@0.146.0/path/mod.ts";
// ...
  const { default: render } = await import(
    new URL("templates/mod.ts", toFileUrl(Deno.cwd()).href + "/").href
  );
```
It's because you were using an absolute FS path which happens to be an origin relative URL.

**Comment by jukefr** [comment]
Thanks !
