### ISSUE TITLE
What determines which fmt features are configurable?

### ISSUE THREAD

**Issue by callumlocke** [denoland/deno#15044]
Two classic bikeshed debates have been dealt with in very different ways in Deno fmt:

1. "Tabs vs. spaces" – give the people a config boolean to end the bikeshedding
2. "Semicolons vs. ASI" – just pick a side, and lock issues if people try to discuss it

These seem like philosophically opposite approaches to addressing the problem of bikeshedding. Is there any reason why it's this way round?

**Comment by lucacasonato** [comment]
I wish we would have not made tabs vs spaces configurable, but I was overruled. There is no contention internally about semicolons vs ASI, which is why it does not have a config flag. There is also no plan for a config flag for ASI, as ASI is objectively terrible.

**Comment by AnInternetTroll** [comment]
A bit of a self plug, but if you really really want semicolons you can use my patch that adds them to `deno fmt`.
I hope it's simple enough to understand in case you may want to add other options that dprint supports but deno refuses to

https://gist.github.com/AnInternetTroll/81ed97db853dc3628effed4157782509?permalink_comment_id=4211780#gistcomment-4211780
