### ISSUE TITLE
is it possible to grant access for only one-time use when running without flags

### ISSUE THREAD

**Issue by yilmazdurmaz** [denoland/deno#15048]
I have v1.23.1 installed.

When running a script without access flags, it prompts me to allow/deny access but does so only once and grants access to any part of the script afterward.

I would like to grant access only for that line that needs an operation and prompted again when another line (whether separate or called by that last line) wants the same access. It may be exhausting but this may come useful when debugging the script with outside libraries. And when everything is seemingly fine, I could then use access flags to run the script.

By the way, current prompting only says it needs access but does not show where that happens. It would be nice to see the path and line number encountered.

**Comment by seanghay** [comment]
Check this out https://deno.land/manual/tools/task_runner

**Comment by yilmazdurmaz** [comment]
> Check this out https://deno.land/manual/tools/task_runner

Tasks seem pretty much the scripts section of Node.js' package.json file and I don't think that will help in this case

**Comment by yilmazdurmaz** [comment]
At this point, I take it that Deno's security is just a simple toy added to make programmer life a bit more miserable.
