### ISSUE TITLE
watcher: When deno is running as a daemon process with watching enabled, some ANSI escape sequences are printed even though stdout/stderr are not a TTY

### ISSUE THREAD

**Issue by frou** [denoland/deno#15041]
(deno 1.23.1)

Here's a screenshot from a log viewer (deno is running as a system daemon/background process, not in a terminal). Watching can also be useful in atypical situations like this.

<img width="450" alt="Screenshot 2022-07-02 at 12 54 32" src="https://user-images.githubusercontent.com/172663/176999738-72bb5ddb-1650-4ac3-879b-a7f51ffa2cc9.png">

I think [printing](https://github.com/denoland/deno/blob/2769d602506af1953312b28580506fca3fcbe030/cli/file_watcher.rs#L121) of [the ANSI escape sequence](https://github.com/denoland/deno/blob/2769d602506af1953312b28580506fca3fcbe030/cli/file_watcher.rs#L25) should be automatically gated using `atty::is`, similar to how an [`is_tty` boolean is already being used elsewhere in the codebase](https://github.com/denoland/deno/search?q=is_tty).

**Comment by frou** [comment]
It's a valid issue. Still present in deno 1.25.1

**Comment by sigmaSd** [comment]
@frou   maybe you should open a PR , since it seems a simple fix and you can reproduce the issue
