### ISSUE TITLE
why Deno runs a typescript file while there are problems with (at least) private/protected access violations

### ISSUE THREAD

**Issue by yilmazdurmaz** [denoland/deno#15042]
I thought Deno would refuse to run this content or at least show me the same problems I see in VSCode, deno-ts(2445) and deno-ts(2341); Property is private / protected and only accessible within class / and its subclasses".

Instead, it just goes ahead and runs the file as if no problem exists.

````ts
abstract class A {
  protected a1: number;
  private a2: number;
  constructor() {
    this.a1 = 0;
    this.a2 = 0;
  }
}
class B extends A {
  protected b1:number
  private b2:number
  constructor() {
    super();
    this.a1=1
    this.a2=1
    this.b1=2
    this.b2=2
  }
}

const c = new B()
c.a1=11; c.a2=22; c.b1=33; c.b2=44;
console.log(c.a1)
console.log(c.a2)
console.log(c.b1)
console.log(c.b2)
````

**Comment by dsherret** [comment]
@yilmazdurmaz how are you running it and what version of deno? Try `deno run --check <file-name-here>`.

See: https://deno.com/blog/v1.23#no-type-checking-by-default

**Comment by yilmazdurmaz** [comment]
I was reading a book about Deno and the author was using error messages pretty naturally. So when I tried codes, it was naturally awkward not seeing any error messages.

@dsherret  I have checked the link and seems Deno seems to have changed the default behavior pretty recently (as of now not even 2 months old)

Though my question is answered, I would expect similar questions in the future :)
