### ISSUE TITLE
How to create a pointer to a const char*

### ISSUE THREAD

**Issue by blu3beri** [denoland/deno#15047]
I am currently messing around with the FFI layer from deno and I have the following code:

TypeScript code:
```ts
const lib = Deno.dlopen("/usr/local/lib/LIB.dylib", {
  func: {parameters: ["pointer"], result: "void"}
})
```

Rust code:
```rust
#[no_mangle]
pub extern fn func(str: *mut *const c_char) {
    unsafe { *error_json_p = "Some C_STR" };
}
```

The Rust side is out of my control so I cannot simply return the string, but I have to pass a pointer to which the Rust library writes.

**My question is**: how can I call this method with an empty pointer where a string can be written to? 

I hava tried the following already:

```typescript

const ptr = new Uint8Array(1000)
lib.symbols.func(ptr)
const error = new Deno.UnsafePointerView(Deno.UnsafePointer.of(ptr)).getCString()
console.log(error)
```

**Comment by blu3beri** [comment]
@aapoalas I saw that you are doing some currently on the FFI side of Deno. Do you, by any chance, know how to solve my issue?

**Comment by 0f-0b** [comment]
The pointer could be stored in a `BigUint64Array`. See #13460.

```ts
const ptr = new BigUint64Array(1);
lib.symbols.func(ptr);
const error = new Deno.UnsafePointerView(ptr[0]).getCString();
console.log(error);
```

**Comment by blu3beri** [comment]
@0f-0b 

> The pointer could be stored in a `BigUint64Array`. See #13460.
> 
> ```ts
> const ptr = new BigUint64Array(1);
> lib.symbols.func(ptr);
> const error = new Deno.UnsafePointerView(ptr[0]).getCString();
> console.log(error);
> ```

Awesome that works!

Might be a good utility method somewhere as this IMO is not the cleanest and intuitive way to do it.
