### ISSUE TITLE
https://deno.land/x/net/file_server.ts... NOT FOUND

### ISSUE THREAD

**Issue by chenjianxin** [denoland/deno#1506]
`deno https://deno.land/x/net/file_server.ts --allow-net`
Downloading  https://deno.land/x/net/file_server.ts... NOT FOUND

**Comment by kevinkassimo** [comment]
It is now replaced with https://deno.land/x/std/http/file_server.ts
We are currently doing some refactoring with standard module structures, sorry about the confusion... please submit PRs if you find anywhere else still uses the old url, thanks!

**Comment by akircher** [comment]
If the `net` module is being renamed to `http` does it makes sense to also rename the `--allow-net` flag to `--allow-http`

**Comment by kevinkassimo** [comment]
@akircher there are many other network operations besides http

**Comment by shreeve** [comment]
Yikes! What's the reason to change from `net` to `http`?

**Comment by kevinkassimo** [comment]
@shreeve A few components has been moved out of `net`, for example
`net/bufio.ts -> io/bufio.ts`
`net/textproto.ts -> textproto/mod.ts`
So currently `http` is just http, for better granularity of functionalities.

**Comment by bartlomieju** [comment]
I think we can close this now CC @ry
