### ISSUE TITLE
TypeScript/JavaScript code fixes should have higher priority than linting code fixes

### ISSUE THREAD

**Issue by Im-Beast** [denoland/deno#15069]
**Is your feature request related to a problem? Please describe.**

Quick fix actions (`CTRL+.` keyboard shortcut) are ordered in inefficient way which force me to do unnecessary keypresses.

**Screenshot**

![image](https://user-images.githubusercontent.com/47059999/177151435-57a4cdee-2758-4813-9e34-464bc2f8275f.png)

**Describe the solution you'd like**

I see two possible solutions for that:
 - "Update import" action place should be before lint actions as it's used more often.
 - Quick fix actions order could be configured in `settings.json`

**Comment by kitsonk** [comment]
Is this customisable with the built in TypeScript/JavaScript plugin in vscode?

**Comment by Im-Beast** [comment]
I don't think it is customizable in built in typescript/javascript plugin.
ESLint vscode plugin does allow to enable/disable individual quick fix actions though.

Worth noting is that order of quick actions with Typescript + ESLint on node is as I described it should be.

![image](https://user-images.githubusercontent.com/47059999/177255614-cc32cde4-8869-431f-854f-775ba8bd6a64.png)

**Comment by kitsonk** [comment]
I think introducing configuration just complicates things unnecessarily.  Giving TypeScript/JavaScript language server quick fixes a higher priority than linting quick fixes though makes sense.
