### ISSUE TITLE
Suggestion: allow ignoring `import-prefix-missing` errors

### ISSUE THREAD

**Issue by GJZwiers** [denoland/deno#15089]
I have a project that runs with `--compat` and contains a  `.ts` file with both a deno- and node-style import:

```ts
import * as log from "https://deno.land/std@0.145.0/log/mod.ts";
import * as Sentry from "@sentry/node";
```

In VS Code and with `deno check` it throws the error `Relative import path "@sentry/node" not prefixed with / or ./ or ../ deno(import-prefix-missing)`. The code runs fine in compat mode though, so I would like to be able to ignore this type of error, but adding `deno-lint-ignore import-prefix-missing` does not work and neither does `@ts-nocheck`. Can this rule be added to the deno linting rules, or is there another way to get rid of the error in this situation?

**Comment by monokrome** [comment]
This has got to be a pretty common issue. Although it's unfortunate, I'm not sure if Deno intends to make these things work based on [the documentation][dcmn]. Would be nice if they did, though, or if the documentation was more clear on this maybe?

[dcmn]: https://deno.land/manual/node

**Comment by GJZwiers** [comment]
With the introduction of npm: specifiers and removal of compat mode I am not sure this suggestion makes sense anymore. Feel free to close this.

**Comment by lino-levan** [comment]
I agree with @GJZwiers, I think this issue is no longer relevant

**Comment by verikono** [comment]
I'm using yarn... no workspace specifier for me ?

**Comment by eevleevs** [comment]
Still relevant if you are serving files with intended to be run on node elsewhere. There should be a way to ignore this error. Please advise.

**Comment by CAYdenberg** [comment]
I agree with @eevleevs  - there doesn't seem to be any way to have code that is intended for node or browser execution and to have the Deno linter just ignore it.

**Comment by bartlomieju** [comment]
@CAYdenberg can you open a new issue with reproduction for your problem?

**Comment by CAYdenberg** [comment]
Sure thing: https://github.com/denoland/deno/issues/23384
