### ISSUE TITLE
deno cache invalid after git clone

### ISSUE THREAD

**Issue by andreas-wagner** [denoland/deno#15082]
I am using deno v1.23.2.

In order to run offline and have everything preloaded (also to be protected from vanishing dependencies) I am adding a project-local deno cache to version control.

In the CI Pipeline I am running:
```sh
DENO_DIR=.deno_cache deno test --allow-net --cached-only --check --lock=lock.json --no-prompt --unstable
```

Sadly my pipeline fails with `error: The source code is invalid, as it does not match the expected hash in the lock file.`.

Steps to reproduce:
```sh
DENO_DIR=.deno_cache deno cache --lock=lock.json --lock-write --unstable deps.ts
git add -A
git commit -m "my commit"
git push
``` 
```sh
mkdir new_dir
cd new_dir
git clone ...
DENO_DIR=.deno_cache deno test --allow-net --cached-only --check --lock=lock.json --no-prompt --unstable
```

Because I found this to also happen locally, it cannot be the difference between Ubuntu and Alpine Linux.\
A `deno cache --reload` does fix the problem, but this goes against doing things offline.

I also have a `.gitattributes` file containing `* text=auto eol=lf`.

And I compared the cache before and after doing a reload, and it was exactly the same (apart from the metadata files).

**Comment by zachauten** [comment]
FWIW, I tried to reproduce with the steps you provided and wasn't able to. I wasn't using the .gitattributes though. Did you try to reproduce without it?

**Comment by andreas-wagner** [comment]
Intriguing. I just tested an older project using deno v1.18.1 living on gitlab with the same checked-in cache.
The Pipeline ran through successfully and `DENO_DIR=.deno_cache deno test --cached-only --lock=lock.json --unstable` did not complain about invalid source code because of a hash.

**Comment by andreas-wagner** [comment]
Hmmm... currently I am anly checking in `.deno_cache/deps`, but I noticed there are more folders now.

The folder `gen` is generated, so no value in checking it in.

The folder `registries` must be new, most of what I can see are intellisense files.
There is also a new sqlite file named `fmt_incremental_cache_v1`.

Can somebody shed some light on what to check-in and what not?
Maybe a general future-proof rule-of-thumb to only exclude the `gen` folder?

**Comment by andreas-wagner** [comment]
Next try, using deno 1.23.2 to reload the cache and generate the lockfile, then committing, pushing and running the pipeline succeeds.

**Comment by andreas-wagner** [comment]
Updated the image for the pipeline to `denoland/deno:alpine-1.23.2` and all is well, so it must be a missing folder from the `.deno_cache` I did not check-in in on the other project.

**Comment by andreas-wagner** [comment]
For anyone running into this issue as well, here's the fix:
```sh
> cat .gitattributes
# Use Unix line endings in all text files.
* text=auto eol=lf

# Never touch the cache, otherwise the hashes won't match anymore.
.deno_cache/** -text
```
