### ISSUE TITLE
Support for upcoming ECMAScript proposal: Type Annotations

### ISSUE THREAD

**Issue by identor** [denoland/deno#15134]
# Proposal
Support running valid TypeScript even with ".js" extension, just ignore the extension.  With upcoming Type Annotations proposal for JavaScript ".ts" files might now be indistinguishable with ".js" files. 

Also noticed that running a file without an extension or without an extension for that matter they are treated as JavaScript files. I understand that there might be performance reasons for this since there will be transpile step when enabling TypeScript by default. By just ignoring types as in the proposal there might be a performance gain.

# Current state

Using deno 1.23.1, running valid TypeScript code when file has a ".js" extension errors out. 

```sh
error: Uncaught SyntaxError: Missing initializer in const declaration
const foo: string = 'bar';
      ^
    at <anonymous> (file:///tmp/test.js:1:7)
```

Sample error from VSCode below (with deno extension installed):

![image](https://user-images.githubusercontent.com/3519612/178105363-2fc0f847-3be3-4cf9-a8d0-3b3d2a8163c7.png)

# Links

 - https://github.com/tc39/proposal-type-annotations
 - https://tc39.es/proposal-type-annotations/
 - https://devblogs.microsoft.com/typescript/a-proposal-for-type-syntax-in-javascript/

**Comment by AnInternetTroll** [comment]
It's worth noting that it's not as easy as treating every javascript file as typescript. See https://github.com/tc39/proposal-type-annotations#omitted-typescript-specific-features-that-generate-code 

> Omitted: TypeScript-specific features that generate code 
> [...]
> - [Enums](https://www.typescriptlang.org/docs/handbook/enums.html)
> - [Namespaces](https://www.typescriptlang.org/docs/handbook/namespaces.html)
> - [Parameter properties](https://www.typescriptlang.org/docs/handbook/classes.html#parameter-properties)

**Comment by identor** [comment]
> It's worth noting that it's not as easy as treating every javascript file as typescript. See https://github.com/tc39/proposal-type-annotations#omitted-typescript-specific-features-that-generate-code 
> 
> > Omitted: TypeScript-specific features that generate code 
> > [...]
> > - [Enums](https://www.typescriptlang.org/docs/handbook/enums.html)
> > - [Namespaces](https://www.typescriptlang.org/docs/handbook/namespaces.html)
> > - [Parameter properties](https://www.typescriptlang.org/docs/handbook/classes.html#parameter-properties)

Yeah but my understanding is tha deno is a TypeScript engine. I also mentioned when there's no extension. Files are treated as JavaScript. I'm questioning this default as well.

One way to support this proposal is to enable TypeScript engine by default. Other way is to just cover what's in the spec when extension is .js

**Comment by nayeemrmn** [comment]
The type annotations proposal applies to the JS spec and would be enabled by default for `.js` files when it exists. TS is a different language, it doesn't make sense to apply it to `.js` files and the type annotations proposal has no bearing on that.

**Comment by dsherret** [comment]
I'm going to close this one because it's not worth tracking at the moment since that proposal is very early in its development and only stage 1. Let's reopen this once it's further along and implemented in v8.
