### ISSUE TITLE
Performance issues with importing 25K line file

### ISSUE THREAD

**Issue by SheetJSDev** [denoland/deno#15158]
Setup:

```bash
$ echo -n > blank.mjs
$ curl -LO https://cdn.sheetjs.com/xlsx-0.18.9/package/xlsx.mjs
$ echo "import * as XLSX from './xlsx.mjs'; console.log(XLSX.version);" >> import.mjs
```

Baseline is comparable to node / bun:

```
$ hyperfine -w 3 'deno run blank.mjs' 'bun blank.mjs' 'node blank.mjs'
```

<img width="547" alt="baseline" src="https://user-images.githubusercontent.com/6070939/178360226-2aa56502-fcff-414b-a6c8-b288ecc7b600.png">

With the import, deno is unexpectedly slow:

```
$ hyperfine -w 3 'deno run import.mjs' 'bun import.mjs' 'node import.mjs'
```

<img width="561" alt="import" src="https://user-images.githubusercontent.com/6070939/178360315-d34d7e15-d476-44c8-9f56-49ff8399240a.png">

**Comment by nayeemrmn** [comment]
I guess it's because `https://cdn.sheetjs.com/xlsx-0.18.9/package/xlsx.mjs` is 25690 lines, and Deno additionally parses all sources with swc even if they aren't typescript, besides the parsing that V8 does.

**Comment by mikrosystheme** [comment]
Is there any flag to use to avoid the swc pass? In my case, I just use javascript and don't need/want any transformation of my code.

**Comment by nayeemrmn** [comment]
No such flag, the parsing is done to detect dependencies ahead of time and scan for directives etc. @mikrosystheme Did you have a use case (like rapidly spawning lots of processes) which was impacted by this delay?

There may be improvements we can make in this area wrt doing 'prepare module load' stuff more lazily and avoiding unnecessary static analyses in JS-only cases. Like traditional JS runtimes.

**Comment by mikrosystheme** [comment]
@nayeemrmn  Thank you. Startup time is not important in my case. I just tend to avoid as many layers of complexity/bugs as possible, since writing JS is already a huge black box I choose to accept. If I got it right, even if providing Deno with a javascript entry point, it will process the source as if it were typescript?

**Comment by dsherret** [comment]
@mikrosystheme it's done by [deno_graph](https://github.com/denoland/deno_graph) to analyze dependencies even for JS files -- for example, there could be an https import in a file and we download those upfront. Overall, an extra 130ms of startup time here for a massive file doesn't seem that bad though I'm sure there's always improvements we could make.

**Comment by tmikaeld** [comment]
Try with the `--no-check flag` maybe it lowers startup time at least.

**Comment by jimmywarting** [comment]
Dito. I too experiences some bottleneck with the typescript parser. like you i prefer plain vanilla javascript over typescript and i write cross compatible code that can be imported by NodeJS, browsers.  Using typescript is like trying to fit a square into a circle, javascript is a dynamic language, and i don't need another interpreter or any obfuscated code to debug. yea, i know that there is sourcemaps but i like vanilla JS. for types i use JSDoc instead. and if i really want a strongly typed language then i would write it in a such language that do actually support types and then compile it to web assembly instead.

**Comment by dsherret** [comment]
This has nothing to do with TypeScript. The file is an mjs file.

**Comment by dsherret** [comment]
By the way, in 1.25 this should now be considerably faster on runs after the first since the dependency analysis is now cached after the first run. I'm going to close this now as it should be much better.
