### ISSUE TITLE
Sort registry completions in the repl

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#15160]
Not sure where the sorting should occur, but it would be nice if this was sorted in the REPL:

![image](https://user-images.githubusercontent.com/1609021/178405631-2f10ed0f-ef66-4874-9f46-c7764d4210fd.png)

**Comment by kitsonk** [comment]
@dsherret the lsp client is responsible for sorting.  There is an optional `sortText` in the completion item as well as the `label` (see: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_completion).  Vscode sorts first by `sortText` if present and then `label`.

**Comment by 2shiori17** [comment]
I'd like to work on this issue.
