### ISSUE TITLE
Different output in console.timeEnd between engines

### ISSUE THREAD

**Issue by sant123** [denoland/deno#15175]
``` js
let obj = {}, map = new Map(), n = 1000000;

for (let i = 0; i < n; i++) {
  obj[i] = i;
  map.set(i, i);
}

let result;
console.time("Object");
result = obj.hasOwnProperty("999999");
console.timeEnd("Object");

console.time("Map");
result = map.has(999999);
console.timeEnd("Map");

```

This is what Deno prints:
![image](https://user-images.githubusercontent.com/7959437/178603577-b8112eb2-09c1-41a3-8060-ca96e23c2345.png)

This is what Node.js prints:
![image](https://user-images.githubusercontent.com/7959437/178603671-0692e20f-848f-454c-ae51-ff9c1da05810.png)

This is what Google Chrome prints:
![image](https://user-images.githubusercontent.com/7959437/178603794-cff30819-c51f-40f4-8bca-211bd7c65cad.png)

What I see is Node.js and Google Chrome print the result in decimal but Deno is rounding the number. I'm curious if this is expected?

Thanks.

Source - https://bretcameron.medium.com/how-javascript-maps-can-make-your-code-faster-90f56bf61d9d

**Comment by kitsonk** [comment]
It should be noted that high resolution time is not available by default in Deno due to security issues and requires a permission flag. But console should log the partial ms if available, IMO.
