### ISSUE TITLE
support config flag in `info` subcommand

### ISSUE THREAD

**Issue by crowlKats** [denoland/deno#15179]

**Comment by kitsonk** [comment]
Well, that and automatic config detection.

**Comment by bartlomieju** [comment]
I believe that was added in https://github.com/denoland/deno/pull/14706 ?

**Comment by kitsonk** [comment]
then what is missing is auto detection and/or resolving the supplied module specifier via the import map via the graph

**Comment by lucacasonato** [comment]
This is all done now.
