### ISSUE TITLE
Fix bundle type checking benchmark

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#15178]
I think now the type checking cache is a bit better after #15118 and so it knows it doesn't need to type check again. Locally type checking does work for me when bundling:

![image](https://user-images.githubusercontent.com/1609021/178620744-958c0924-fff0-4f12-8efc-2f7050d6f70b.png)

https://deno.land/benchmarks

**Comment by lucacasonato** [comment]
`deno bundle` has been deprecated and removed in Deno 2.
