### ISSUE TITLE
Can acquire file locks for SQLite 

### ISSUE THREAD

**Issue by ralyodio** [denoland/deno#15188]
https://sqlite.org/forum/forumpost/e2afc0ca78

Is there anyway to fix this?

**Comment by mikrosystheme** [comment]
I would wait for the [native bindings](https://github.com/denoland/deno/pull/14627) to land in core.

**Comment by ralyodio** [comment]
Any sort of timeframe for this? We talking weeks or months

**Comment by lucacasonato** [comment]
Deno has APIs for [flock](https://doc.deno.land/deno/unstable/~/Deno.flockSync) and [funlock](https://doc.deno.land/deno/unstable/~/Deno.funlockSync).
