### ISSUE TITLE
Deno bundle doesn't rename declared identifiers since v1.23.1

### ISSUE THREAD

**Issue by uchuhimo** [denoland/deno#15187]
Since v1.23.1, I get the following error when I run the bundled file:

```
error: Uncaught SyntaxError: Identifier 'createCommonjsModule' has already been declared
function createCommonjsModule(fn, basedir, module) {
^
    at <anonymous> (file:///home/yxqiu/workspace/test_deno/test_deno.bundle.js:248:1)
```

I compare the bundled file produced by v1.23.0 and v1.23.1:

- in v1.23.0, multiple `createCommonjsModule` functions will be renamed to `createCommonjsModule1`, `createCommonjsModule2`, `createCommonjsModule3` and so on.
-  in v1.23.1, all `createCommonjsModule` functions will still be `createCommonjsModule` after bundled.

I guess the PR "fix: upgrade swc via deno_ast 0.16 (https://github.com/denoland/deno/pull/14930)" in v1.23.1 introduces this issue since it is the most related PR in v1.23.1.

**Comment by uchuhimo** [comment]
I think this issue is also related to https://github.com/denoland/deno/issues/14974.

**Comment by crowlKats** [comment]
@uchuhimo do you still encounter this?

**Comment by lucacasonato** [comment]
`deno bundle` was deprecated and has been removed in Deno 2.
