### ISSUE TITLE
Unexpected test failure without stack details

### ISSUE THREAD

**Issue by HPaulson** [denoland/deno#15199]
I ran into a fairly specific bug where a Deno test will fail unexpectedly, then reproduce no details in its error message.

I wasn't able to reproduce the bug in a "simpler" way than I caused it, however, my test file & code can be found at [this](https://github.com/lydo-lang/lydo-bootstrap/blob/d2b417ac2c96243460bf1cbd18ad7148dc0bde85/tests/lexer.test.ts) commit. In this file, you'll notice two tests: `Lexer tokens` & `Lexer syntax err`. When running `deno test -A`, both of these pass as expected. However, when rearranging the file such that `Lexer syntax err` comes first and `Lexer tokens` comes second, the latter test fails without any stack details:
```
running 2 tests from file:///Users/hpaulson/Development/Lydo/lydo-bootstrap/tests/lexer.test.ts
test Lexer syntax err ... ok (4ms)
test Lexer tokens ... FAILED (3ms)

failures:

Lexer tokens


failures:

        Lexer tokens

test result: FAILED. 1 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out (24ms)

error: Test failed
```

Of course, these tests should be absolutely independent of each other, and there shouldn't be a reason why switching their order would cause one to fail. In addition, I think this bug has something to do with the call to `lexer(src)` in the `Lexer tokens` test; When replacing this call with the actual array of tokens (which we expect to receive as an output from the function), the test passes as expected. Even if the function call isn't providing back the expected output (which likely isn't the case considering it works fine when the order of tests is swapped), the test should still send back some details about why it failed; Here it simply says it failed with no additional information. 

If there's any additional reproduction info I could provide that may be helpful, please let me know!

**Comment by bartlomieju** [comment]
Can you still repeat this problem on latest version of Deno @HPaulson ?

**Comment by HPaulson** [comment]
@bartlomieju Unfortunately I lost that original codebase and am unable to reproduce. If this comes up again, I'll reopen the issue. Thanks!
