### ISSUE TITLE
Uncaught SyntaxError: The requested module './Reflect.ts' does not provide an export named 'Reflect'

### ISSUE THREAD

**Issue by slim-hmidi** [denoland/deno#15197]
I use deno v1.23.4 and  [inject module](https://github.com/cmd-johnson/deno-dependency-injector).
While I run the server I got this error:
```
error: Uncaught SyntaxError: The requested module './Reflect.ts' does not provide an export named 'Reflect'
export { Reflect } from "./Reflect.ts";
```
It seems like deno accepts only `declare namescpace` and `export type`.
https://deno.land/manual/typescript/faqs#why-are-you-forcing-me-to-use-isolated-modules-why-cant-i-use-const-enums-with-deno-why-do-i-need-to-do-export-type

Reproduction:
```
import { Reflect } from "https://deno.land/x/reflect_metadata@v0.1.12-2/mod.ts";
console.log(Reflect);
```

**Comment by nayeemrmn** [comment]
This is an swc-only bug, opened https://github.com/swc-project/swc/issues/5197.

**Comment by jiawei397** [comment]
I encountered this problem after upgrading the Deno version, so I modified the original code myself. You can use this package first: https://deno.land/x/deno_reflect@v0.2.1

**Comment by divyavanmahajan** [comment]
Any fix to this - ?

**Comment by ralcorta** [comment]
I ran into the same problem. I couldn't fix it, but instead used this version:

```ts
import "https://deno.land/x/reflect_metadata@v0.1.12/mod.ts";
```

I hope it helps someone.

**Comment by K0rmir** [comment]
> I ran into the same problem. I couldn't fix it, but instead used this version:
> 
> ```ts
> import "https://deno.land/x/reflect_metadata@v0.1.12/mod.ts";
> ```
> 
> I hope it helps someone.

Where do you import this?
