### ISSUE TITLE
Deno namespace inconsistency

### ISSUE THREAD

**Issue by timreichen** [denoland/deno#15207]
`Deno.SOARecord`, `Deno.SRVRecord`, `Deno.NAPTRRecord`, `Deno.MXRecord`, and `Deno.CAARecord` seem to be inconsistent names in deno namespace as it does not generally use uppercase on acronyms ([Deno.HttpConn](https://doc.deno.land/deno/stable/~/Deno.HttpConn), [Deno.TlsConn](https://doc.deno.land/deno/stable/~/Deno.TlsConn) etc.)

I propose to rename them to PascalCase and deprecate the old ones as they can be removed in v2.

**Comment by timreichen** [comment]
@bartlomieju This issue was marked stale but probably is relevant again for v2. Could you take a look?

**Comment by kt3k** [comment]
FYI `denoland/std` replaced all these patterns of names a while ago. https://github.com/denoland/std/pull/2582
