### ISSUE TITLE
Deno panics when vendoring `"https://esm.sh/rollup@2.75.7?pin=v87"`

### ISSUE THREAD

**Issue by jespertheend** [denoland/deno#15215]
I have a file `test.js`:
```js
import {rollup} from "https://esm.sh/rollup@2.75.7?pin=v87";
console.log("done");
```

and if I run `deno vendor test.js` deno panics with the following stack trace:
```
Platform: macos x86_64
Version: 1.23.4+635eed9
Args: ["deno", "vendor", "test.js"]

thread 'main' panicked at 'Could not find local path for https://esm.sh/v87/fsevents@2.3.2/deno/fsevents.js', cli/tools/vendor/mappings.rs:138:11
stack backtrace:
   0:        0x104f25599 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6ab6a4b798848da1
   1:        0x104571e7b - core::fmt::write::h3cfeb2e4a41b5943
   2:        0x104ef6478 - std::io::Write::write_fmt::h207c490a0e714424
   3:        0x104f2a46d - std::panicking::default_hook::{{closure}}::h2dad0ca14a5f6fb3
   4:        0x104f2a16a - std::panicking::default_hook::he28ca1b524a71648
   5:        0x1045022d7 - deno::setup_panic_hook::{{closure}}::he8024f67c013d490
   6:        0x104f2af90 - std::panicking::rust_panic_with_hook::hc50fd680dab3e13f
   7:        0x104f2adf4 - std::panicking::begin_panic_handler::{{closure}}::h73da24fc37eba97b
   8:        0x104f2ad69 - std::sys_common::backtrace::__rust_end_short_backtrace::hff104f8fa804dc90
   9:        0x104f2ad25 - _rust_begin_unwind
  10:        0x10622f4d3 - core::panicking::panic_fmt::hf5e95a7953f70bca
  11:        0x10443df12 - deno::tools::vendor::mappings::Mappings::local_path::h5919da71c72a4b61
  12:        0x10443fa49 - deno::tools::vendor::mappings::Mappings::local_uri::ha6a12c2d9c3c472e
  13:        0x10443ec29 - deno::tools::vendor::mappings::Mappings::relative_specifier_text::h740e17e051f349c8
  14:        0x10443e56b - deno::tools::vendor::import_map::visit_maybe_resolved::hae6ba9302eb48b01
  15:        0x10443a8b0 - deno::tools::vendor::build::build::hedba2e9c83a428e4
  16:        0x104435f82 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hb0e699d5f44bfb4d
  17:        0x1041d335e - deno::main::{{closure}}::ha10932b0dab64839
  18:        0x1041c6c75 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h75517a8166f7f072
  19:        0x1041c40af - deno_runtime::tokio_util::run_local::h725d4437ffae34cd
  20:        0x1041c350d - deno::main::hb9f7125e60480e76
  21:        0x1041c2b4e - std::sys_common::backtrace::__rust_begin_short_backtrace::had83fdd2d04aa992
  22:        0x1041c2ef9 - _main
```

I've also found that deno very frequently prints `Download https://esm.sh/v87/fsevents@2.3.2/deno/fsevents.js` even though that should definitely have been cached by now. Sometimes it doesn't panic but it keeps hanging on `Download https://esm.sh/v87/fsevents@2.3.2/deno/fsevents.js`.

I wouldn't be surprised if this is exclusive to my machine, maybe my cache is simply corrupt.

**Comment by dsherret** [comment]
Huh, when browsing to that file I get:

```ts
/* esm.sh - error */
throw new Error("[esm.sh] " + "parseCJSModuleExports: ns timeout");
export default null;
```

**Comment by jespertheend** [comment]
I think esm.sh is having issues, I've been seeing that same error for several packages today and yesterday. And the esm.sh bug tracker contains a bunch of recent issues mentioning 500 errors.

**Comment by jespertheend** [comment]
Fwiw, when I browse `https://esm.sh/rollup@2.75.7?pin=v87` I'm getting
```js
/* esm.sh - rollup@2.75.7 */
export * from "https://esm.sh/v87/rollup@2.75.7/deno/rollup.js";
```

I think the esm.sh cdn might give a different response based on your location.

**Comment by dsherret** [comment]
Sorry, I meant https://esm.sh/v87/fsevents@2.3.2/deno/fsevents.js

**Comment by jespertheend** [comment]
Ah yeah, that one is failing for me also.
Not sure if this was also the case two weeks ago, it's not printing `Download https://esm.sh/v87/fsevents@2.3.2/deno/fsevents.js` a ton of times anymore.
But either way, I can still reproduce the panic with the script above.

**Comment by jespertheend** [comment]
@dsherret Would it be possible to provide an option that prevents Deno from erroring on dynamic imports?
I'm trying to vendor the above url so that the generated files can be imported in the browser via a local server.

With the panic, the files are still placed in the vendor directory. Importing these files in a browser works just fine.
But if Deno errors, no files are placed in the vendor directory so they can't be used.

**Comment by dsherret** [comment]
Please open a separate issue. I think so.
