### ISSUE TITLE
Not available @types/prettier version on package.json

### ISSUE THREAD

**Issue by gbahamondezc** [denoland/deno#1521]
Hi!, 

Running  `npm install`  on the project throws an error  with `@types/prettier` version.

<img width="608" alt="screen shot 2019-01-14 at 7 38 39 am" src="https://user-images.githubusercontent.com/22915623/51108073-a545e080-17cf-11e9-9fba-c164e8ca05c9.png">
<img width="834" alt="screen shot 2019-01-14 at 7 38 45 am" src="https://user-images.githubusercontent.com/22915623/51108076-a971fe00-17cf-11e9-8029-e8d1a2f2c6f6.png">

branch: master (currently in 7d08db2)
```
MacOS Mojave 10.14
NodeJS 10.14.2 & Nodejs 8.15
```

**Comment by ry** [comment]
You probably don’t need to run “npm install”
We mange our deps a bit differently - everything is included in the  submodule https://github.com/denoland/deno_third_party

That said- this is a minor config error in our package.json

**Comment by gbahamondezc** [comment]
@ry ok thanks for the clarification.
