### ISSUE TITLE
The requested module does not provide an export named 'loadWASM'

### ISSUE THREAD

**Issue by jrson83** [denoland/deno#15216]
I tried using [rehype-pretty-code](https://github.com/atomiks/rehype-pretty-code) from esm.sh with [Lume](https://lume.land/):

```js
import rehypePrettyCode from "https://esm.sh/rehype-pretty-code@0.3.2";
```

I'm getting the following error on build/serve:

```shell
SyntaxError: The requested module '/v87/vscode-oniguruma@1.6.2/deno/vscode-oniguruma.js' does not provide an export named 'loadWASM'
    at async createSite (https://deno.land/x/lume@v1.10.0/cli/utils.ts:15:17)
    at async build (https://deno.land/x/lume@v1.10.0/cli/build.ts:29:16)
    at async Command.execute (https://deno.land/x/cliffy@v0.24.2/command/command.ts:1275:7)
    at async (https://deno.land/x/lume@v1.10.0/cli.ts:173:3)
```

I tried adding the [shiki](https://esm.sh/shiki@0.10.1) esm.sh module to my `import_map.json`. When I run `deno cache --reload _config.ts` I see it is downloading the required module from [vscode-oniguruma](https://esm.sh/v87/vscode-oniguruma@1.6.2/deno/vscode-oniguruma.js), but I still get the same error.

My `deno.json`:

```json
"compilerOptions": {
  "lib": [
    "dom",
    "dom.iterable",
    "dom.asynciterable",
    "deno.ns",
    "deno.unstable"
  ],
}
```

**Comment by kitsonk** [comment]
Why do you believe this is an issue with Deno

**Comment by jrson83** [comment]
I was not sure, if it related to deno. I will open up an issue at Lume and close this one.
