### ISSUE TITLE
deno not yet in termux packages

### ISSUE THREAD

**Issue by sebastianjnuwu** [denoland/deno#15250]
Hello, I tried to install deno through termux and realized that it is not in termux packages ( pkg install and apt install) will it be in termux packages?

**Comment by kitsonk** [comment]
Support for android for Deno would be a pre-requisite (see: #4862).  Closing in favour of #4862. Once it is officially supported, then we can discuss package distribution.

**Comment by jamesliu96** [comment]
perhaps discussable now https://github.com/denoland/deno/pull/22298

**Comment by kLiHz** [comment]
Glad to see official ARM64 support landed! By the way, I fround #19759 that might be useful. 😇

**Comment by CodeIter** [comment]
I made a shell script [termux-pacman-glibc-setup.sh](https://gist.github.com/CodeIter/ccdcc840e432288ef1e01cc15d66c048#file-termux-pacman-glibc-setup-sh) to setup `glibc-runner` with pacman on Termux and install Deno.JS and Bun.JS  as a demo.

**Comment by rahulgupta0-dev** [comment]
but we want smoth download instead of downloading extra library etc. like nodejs, python,etc in termux.

**Comment by mattalxndr** [comment]
Perhaps the status of this ticket could be changed to "Open", considering the new architecture support?

**Comment by steve02081504** [comment]
https://github.com/steve02081504/fount/blob/cb7135830942c256b803b02cd9c531b0224a22ea/path/fount.sh#L458
maybe help
