### ISSUE TITLE
Deno v1.24 `consoleSize` throws because Resource is busy when previous versions don't

### ISSUE THREAD

**Issue by Im-Beast** [denoland/deno#15268]
**Description**
If you run following code snippet on version `1.24` it throws with following error:
```
error: Uncaught (in promise) Busy: Resource is unavailable because it is in use by a promise
```

However on previous versions it works just fine without crashing.

**Reproduction**
```ts
Deno.addSignalListener("SIGWINCH", () => {
  Deno.write(Deno.stdout.rid, new TextEncoder().encode("hi"));
  console.log(Deno.consoleSize(Deno.stdout.rid));
});

const sleep = () => new Promise((r) => setTimeout(r, 64));

while (true) {
  await sleep();
}
```

**Comment by dsherret** [comment]
There was a temporary regression in Deno that allowed accessing a resource synchronously while it's being used asynchronously. This is now fixed and is causing this behaviour. In this case, you can fix the issue by awaiting the `Deno.write` promise (`await Deno.write`) or use `Deno.writeSync` instead.

**Comment by Im-Beast** [comment]
Oh, so it's now working as expected, good to know. `Deno.writeSync` worked for my usecase however this limits ability to run `Deno.write` asynchronously (even when awaited) and use `consoleSize` in other asynchronous function or event callback simultaneously, is there a way around that?

**Comment by dsherret** [comment]
I think maybe just always use synchronous writes when dealing with stdout or stderr (it's what console.log/error do).

The following code would also error with the same one you mentioned:

```ts
const results = [];
for (let i = 0; i < 100; i++) {
  results.push(Deno.write(Deno.stdout.rid, new TextEncoder().encode("hi")));
  console.log("test");
}

await Promise.all(results);
```

Thoughts @lucacasonato?

**Comment by Im-Beast** [comment]
Thats a bummer, anyhow I think we can safely close this issue as it's how it should work by design.

**Comment by dsherret** [comment]
I opened #15747, which should resolve this.
