### ISSUE TITLE
(blog) 1.24 release notes: Subprocess API change description language is unclear/misleading

### ISSUE THREAD

**Issue by jsejcksn** [denoland/deno#15273]
(Bartek [said that blog issues belong in this repo](https://github.com/denoland/deno/pull/14536#issuecomment-1159682833), so I'm posting here.)

The [Updates to new subprocess API](https://deno.com/blog/v1.24#updates-to-new-subprocess-api) section begins with:

> First, we changed types of stdio streams; instead of complicated generic types describing which streams are available, they are now simple, always available streams. If you try to access these streams, but didn't specify that they should be `piped`, a `TypeError` will be thrown.

and it goes on to show a code example with a "before" and "after". This is the code example in the section:

```ts
// spawn.ts
const child = Deno.spawnChild("echo", {
  args: ["hello"],
  stdout: "piped",
  stderr: "null",
});
const readableStdout = child.stdout.pipeThrough(new TextDecoderStream());
const readableStderr = child.stderr.pipeThrough(new TextDecoderStream());
```

What I find potentially misleading about the description is the last sentence:

> If you try to access these streams, but didn't specify that they should be `piped`, a `TypeError` will be thrown.

The verb "specify" ([Google](https://www.google.com/search?q=define+specify)/[Lexico](https://www.lexico.com/en/definition/specify)) means that it must be explicitly written in the options by the programmer, but that doesn't acknowledge the [defaults](https://doc.deno.land/deno/unstable@v1.24.0/~/Deno.SpawnOptions) for these streams, which are already set to `"piped"` (except for `stdin`).

I'm going to add one more line at the end of the example code to provide a visual sign of a successful run in the `stdout` of the parent process (rather than nothing) to demonstrate what I mean:

```ts
// spawn.ts
const child = Deno.spawnChild("echo", {
  args: ["hello"],
  stdout: "piped",
  stderr: "null",
});
const readableStdout = child.stdout.pipeThrough(new TextDecoderStream());
const readableStderr = child.stderr.pipeThrough(new TextDecoderStream());
console.log(await child.status);
```

Running it:

```
% deno --version                               
deno 1.24.0 (release, x86_64-apple-darwin)
v8 10.4.132.20
typescript 4.7.4

% deno run --unstable --allow-run=echo spawn.ts
error: Uncaught TypeError: stderr is not piped
const readableStderr = child.stderr.pipeThrough(new TextDecoderStream());
                             ^
    at Child.get stderr (deno:runtime/js/40_spawn.js:107:15)
    at file:///Users/deno/spawn.ts:8:30
```

And if I modify the file, removing the stdio options so that they're no longer specified:

```ts
// spawn.ts
const child = Deno.spawnChild("echo", {
  args: ["hello"],
  // The stdio options are no longer "specified"
});
const readableStdout = child.stdout.pipeThrough(new TextDecoderStream());
const readableStderr = child.stderr.pipeThrough(new TextDecoderStream());
console.log(await child.status);
```

I can run it again:

```
% deno run --unstable --allow-run=echo spawn.ts
{ success: true, code: 0, signal: null }
```

and everything succeeds. I hope this demo justifies why I think readers might find the description language confusing or even misleading (especially when paired with the example code). Therefore, I think the last sentence should be reworded so that it:

- borrows the word "set" from the JSDoc description for [`Deno.spawnChild`](https://doc.deno.land/deno/unstable@v1.24.0/~/Deno.spawnChild):
- links to the typedocs (which specify the defaults) for the stdio options

Here's my suggested edit:

> If you try to access one of these streams and it's not set to `"piped"`, a `TypeError` will be thrown. (The defaults are documented [here](https://doc.deno.land/deno/unstable@v1.24.0/~/Deno.SpawnOptions).)

**Comment by bartlomieju** [comment]
Thanks, updated.
