### ISSUE TITLE
lsp: return value for completion item flag field does not match type definition, causing panic

### ISSUE THREAD

**Issue by amoreaulemay** [denoland/deno#15287]
**Describe the bug**

The deno language server crashes constantly, especially when trying to import from other files. If it helps I'm working on a "fresh" project.

**To Reproduce**

I don't know how to reproduce it specifically, but it happens every 15 minutes.

**Console Output**

```
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos x86_64
Version: 1.23.4
Args: ["/Users/alexandremoreau-lemay/.deno/bin/deno", "lsp"]

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("invalid value: 3, expected one of: 0, 1, 2, 4, 8, 16, 32", line: 0, column: 0)', cli/lsp/tsc.rs:153:54
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Error - 12:41:47 PM] The Deno Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
```

**Versions**

- vscode: 1.69.2
- deno: 1.23.4 (release, x86_64-apple-darwin)
- v8: 10.4.132.8
- typescript: 4.7.4
- extension: v3.13.1

**Comment by kitsonk** [comment]
The issue appears to be with decoding a value returning from the built in TypeScript. The type definitions are clear on what values should be returned, and 3 is not one of them, but it is being returned.  The "good" thing is we don't use the information, it is used for Microsoft telemetrics, which we don't use in Deno.

I will remove the field, which should fix the issue.
