### ISSUE TITLE
[ext/ffi] non-deterministic `getCString` on `JSON.stringify()`

### ISSUE THREAD

**Issue by blu3beri** [denoland/deno#15289]
- Deno: `1.24.0` (and `1.23.4`)
- Arch: `aarch64-apple-darwin`

I am trying to:
- stringify some JSON
- encode into a Uint8Array
- Get the pointer to the value
- Create a view of the pointer
- Read the string from the pointer

Code example:

```ts
const foo = { a: "b" }

const serialized = new TextEncoder().encode(JSON.stringify(foo))

const ptr = Deno.UnsafePointer.of(serialized)
const view = new Deno.UnsafePointerView(ptr)

console.log(serialized)
console.log(view.getCString())
```

Sometimes this results in the correct output:

```console
tmp λ deno run --allow-ffi --unstable mod.ts
Uint8Array(9) [
  123, 34, 97, 34,
   58, 34, 98, 34,
  125
]
{"a":"b"}
```

However, sometimes it results in this output:

```console
tmp λ deno run --allow-ffi --unstable mod.ts
Uint8Array(9) [
  123, 34, 97, 34,
   58, 34, 98, 34,
  125
]
Error 'invalid utf-8 sequence of 1 bytes from index 10' contains boxed error of unknown type:
  Utf8Error { valid_up_to: 10, error_len: Some(1) }
error: Uncaught Error: invalid utf-8 sequence of 1 bytes from index 10
console.log(view.getCString())
                 ^
    at Object.opSync (deno:core/01_core.js:170:12)
    at UnsafePointerView.getCString (deno:ext/ffi/00_ffi.js:103:19)
    at file:///tmp/mod.ts:9:18
```

This happened more to me with Deno version `1.23.3` and quite a bit less on `1.24.0`, it is still occuring however.

On Deno `1.23.3` this also sometimes happened:

```console
tmp λ /opt/homebrew/bin/deno run --allow-ffi --unstable mod.ts
Uint8Array(9) [
  123, 34, 97, 34,
   58, 34, 98, 34,
  125
]
{"a":"b"}+ // notice the +, can be any char, here
```

~~but this seems to be resolved in 1.24.0.~~ 
(Tested within my actual project it did occur, random chars at the end, just does not really occur in the example project on `1.24.0`)

Is something wrong in my code, is the detection for end-of-string wrong in Deno or something else?

edit:

The issue seems to be related only to `JSON.stringify` and not when calling `encode()` on a normal string.

**Comment by littledivy** [comment]
Your encoded JSON is not a C String. It must be ('\0') null-terminated.

**Comment by blu3beri** [comment]
> Your encoded JSON is not a C String. It must be ('\0') null-terminated. 

Ah yeah that makes sense. I thought it would be done under-the-hood. So just appending \0 would fix the issue I assume.
