### ISSUE TITLE
[TypeDefs] `Deno.core.heapStats()` Function Does Not Exist

### ISSUE THREAD

**Issue by zicklag** [denoland/deno#15284]
https://github.com/denoland/deno/blob/72199303d899b8ddf2ff46ed11bd513ed9cc47e2/core/lib.deno_core.d.ts#L71-L72

I might be missing something, but it appears that the `heapStats()` function documented here doesn't exist. I've attempted to run the function in a script with `deno_core`, but it wasn't found. Also, I can't seem to find an implementation of the operation in the Deno source.

**Comment by kitsonk** [comment]
It was removed, but the type definitions not updated, but should be removed from the definitions.
