### ISSUE TITLE
`-q` option position is inconsistent for the `task` subcommand

### ISSUE THREAD

**Issue by niedzielski** [denoland/deno#15290]
There is a tiny consistency bug in the CLI's `-q` option position for the `task` subcommand specifically. The Deno CLI itself (`deno [OPTIONS] [SUBCOMMAND]`) supports `-q` for most (all?) subcommands except `task`.

Consider the following:

```
$ echo '{"tasks": {"echo": "echo"}}' > deno.json
$ deno -q task echo
Task not found: task
Available tasks:
- echo
    echo
```

Instead, the `-q` option must appear _after_ the subcommand:

```
$ deno task -q echo

```

This is inconsistent with most other subcommands and the the CLI help documentation. Eg, `fmt` works as expected:

```
$ deno -q fmt
```

The expected supported format is always `deno [OPTIONS] [SUBCOMMAND]`. `deno -q task`, in this case.

**Comment by Cre3per** [comment]
After a first look, this seems to have been introduced by #14567  

`log_level` is set correctly, but `task_parse()` always uses `argv[2]` as the task name. This can be seen in the output

```
Task not found: task
```

There is code to get the index of the task name in `argv` (or `raw_args`), but it isn't working as intended.

I'd like to work on this issue
