### ISSUE TITLE
Can't use FFI on distros using SELinux

### ISSUE THREAD

**Issue by ThalusA** [denoland/deno#15306]
I'm using Fedora 36 which is using SELinux.
I'm running `deno run -A --unstable deno.js`.
I'm getting this error: `tcc: error: mprotect failed: did you mean to configure --with-selinux?`.

See discussion related to this issue on Discord: https://discord.com/channels/684898665143206084/956626010248478720/1001133693357789285

**Comment by Symbitic** [comment]
I'm also getting this problem after upgrading to Deno 1.25

FFI just instantly stopped working. Is there any workaround, or do we have to wait for #15305?

**Comment by ThalusA** [comment]
@Symbitic For now, the best workaround for me was to use docker ubuntu container to run deno programs.
