### ISSUE TITLE
[feature request] Add top-level `files` deno.json config to replace `fmt.files` + `lint.files` + `test.files`

### ISSUE THREAD

**Issue by niedzielski** [denoland/deno#15300]
I have a JavaScript monorepo wherein some sub-projects do not comply to Deno. To fully ignore them, I have to add three `files.exclude` configs to my deno.json:

```jsonc
{
  "fmt": {
    "files": { "exclude": ["modules/tools"] },
    // More options.
  },
  "lint": {
    "files": { "exclude": ["modules/tools"] },
    // More options.
  },
  "test": {
    "files": { "exclude": ["modules/tools"] },
    // More options.
  },
  // More options.
}
```

I'd like a single top-level `files` config that had the same effect:

```jsonc
{
  "files": { "exclude": ["modules/tools"] },
  "fmt": {
    // More options.
  },
  "lint": {
    // More options.
  },
  "test": {
    // More options.
  },
  // More options.
}
```

This DRYs up the config at the expense of increasing the complexity. It feels more natural to me than updating three places to effectively fully ignore a directory.

## References
* [Mixed Deno workspaces in the VS Code extension](https://github.com/denoland/vscode_deno/blob/main/docs/workspaceFolders.md#mixed-deno-projects)
* [deno.json schema](https://raw.githubusercontent.com/denoland/deno/main/cli/schemas/config-file.v1.json)

**Comment by Haider-Ali-Dev** [comment]
Interesting I’ll look into the code later.

**Comment by scarf005** [comment]
# Summary

there's 4 possible combination for global `"files"` and local config:

1. **no** global `"files"` + config w/wo local `"files"`
2. global `"files"` + config w/wo local `"files"`
3. **no** global `"files"` + **no** config
4. global `"files"` + **no** config

while case 1, 2 and 3 is unambigous, i'm unsure how  to handle case 4.

## The four cases

### **no** global `"files"` + config w/wo local `"files"`
same as before.

### global `"files"` + config w/wo local `"files"`
```jsonc
{
  "files": { "exclude": ["npm/"] },
  "fmt": { "files": { "exclude": ["cov/"] } },
  "lint": {}
}
```
would be resolved to
```jsonc
{
  "fmt": { "files": { "exclude": ["cov/", "npm/"] } },
  "lint": { "exclude": ["npm/"] }
}
```
### **no** global `"files"` + **no** config
same as before.

### global `"files"` + **no** config
```jsonc
{
  "files": { "exclude": ["npm/"] }
}
```
how should this case be handled?

## Possible implementation

### Include `"files"` regardless local config
above case will be resolved as
```jsonc
{
  "files": { "exclude": ["npm/"] },
  "fmt": { "files": { "exclude": [ "npm/"] } }
}
```
### Only Include `"files"` if local config exists
above case will be resolved as
```jsonc
{}
```

**Comment by dsherret** [comment]
A problem about this, is that it creates some confusion around what this applies to (ex. it creates the question: do the cache, vendor, compile, doc subcommands grab from the "files" array?) and I wonder if this will cause issues in the future with future subcommands. It seems like the predominant usecase is to "exclude" so maybe this should be exclude only?

**Comment by Im-Beast** [comment]
what about `tooling.files`?

**Comment by scarf005** [comment]
some possible solutions:
### [only allow exclude array](https://github.com/denoland/deno/issues/15300#issuecomment-1429900723)
```jsonc
{
  "exclude": ["npm/"]
  "fmt": {}
}
```
### [use `"tooling"` scope](https://github.com/denoland/deno/issues/15300#issuecomment-1429981007)
```jsonc
{
  "tooling": {
    "apply": ["fmt", "lint", "bench"]
    "files": { "exclude": ["npm/"] }
  },
  "fmt": {}
}
```

**Comment by selurvedu** [comment]
#17778 doesn't seem to work with `deno check`.

**Comment by dsherret** [comment]
@selurvedu the excludes is not for `deno check`. If say a.ts is in the excludes and you do `deno check a.ts`, then it will still type check a.ts. Similarly, if mod.ts imports a.ts and a.ts it will still type check a.ts because a.ts is part of that module graph.

**Comment by selurvedu** [comment]
@dsherret thanks for clarifying. I guess I could use this for now:
```
--- deno.json
+++ deno.json
@@ -1,7 +1,7 @@
 {
   "lock": true,
   "tasks": {
-    "check": "deno fmt --check && deno lint && deno check **/*.ts && deno check **/*.tsx",
+    "check": "deno fmt --check && deno lint && find . -type d -name _ignored -prune -o -type f -iname '*.ts' -o -iname '*.tsx' -print | xargs deno check",
     "start": "deno run -A --watch=routes/,components/,islands/ dev.ts",
     "build": "deno run -A dev.ts build && deno cache main.ts",
     "update": "deno run -A -r https://fresh.deno.dev/update .",
```

This was supposed to include `find . -type d -name _ignored -prune -o -type f -iname '*.ts' -o -iname '*.tsx' -exec deno check {} +`, but I don't know how to escase `{}`.

**Comment by kuboon** [comment]
@selurvedu 's code lists only tsx files because '*.ts` has no `-print` before `-o`

This was worked for me:
```
"check": "deno fmt --check && deno lint && find . -type d -name node_modules -prune -o -type f \\( -iname '*.ts' -o -iname '*.tsx' \\) -print | xargs deno check",
```
