### ISSUE TITLE
Stable APIs listed on doc.deno.land/deno/unstable

### ISSUE THREAD

**Issue by GJZwiers** [denoland/deno#15327]
There are some Deno APIs that have been stabilized that show up on https://doc.deno.land/deno/unstable, for example `Deno.run`, `Deno.listen` and `fetch`. These no longer require the `--unstable` flag so they should probably not be listed in the unstable section anymore.

**Comment by crowlKats** [comment]
The apis listed there are partially unstable, including `Deno.run`, `Deno.listen` & `fetch`. if you click on them, you will see they are different from the stable ones.
