### ISSUE TITLE
lsp: quick fixes using full URLs for new imports

### ISSUE THREAD

**Issue by iugo** [denoland/deno#15330]
**Is your feature request related to a problem? Please describe.**

When using import map, quick fix's add import from still tries to write the full URL instead of using import map.

**Describe the solution you'd like**

When the add import from function of quick fix is triggered, it will be automatically matched according to the import map, and an additional option will be given after matching.

**Comment by kitsonk** [comment]
Technically this shouldn't be happening, it should be coming in with the import completion already remapped.
