### ISSUE TITLE
WebSocket instance properties have invalid values

### ISSUE THREAD

**Issue by sgwilym** [denoland/deno#15340]
I've been trying to access the `bufferedAmount` property of a `WebSocket` instance. Things weren't behaving as expected, and when I logged a socket to the console, I got this:

```
WebSocket {
  url: undefined,
  readyState: 1,
  extensions: undefined,
  protocol: null,
  binaryType: undefined,
  bufferedAmount: NaN
}
```

This is within the context of a test which sets up a client and server running on the same machine, with many connections being created in a small span of time.

I'm running Deno 1.24.

**Comment by jespertheend** [comment]
I got a reduce test case that replicates this:
```js
import {Server} from "https://deno.land/std@0.158.0/http/server.ts";

const server = new Server({
	handler: req => {
		const {socket, response} = Deno.upgradeWebSocket(req);
		console.log("server", socket);
		socket.addEventListener("open", () => {
			console.log("open", socket);
		});
		return response;
	},
	port: 0,
});
server.listenAndServe();
const addr = server.addrs[0];
const socket = new WebSocket(`ws://${addr.hostname}:${addr.port}`);
console.log("client", socket);
```
This logs the following:
```
client WebSocket {
  url: "ws://0.0.0.0:62051/",
  readyState: 0,
  extensions: "",
  protocol: "",
  binaryType: "blob",
  bufferedAmount: 0
}
server WebSocket {
  url: undefined,
  readyState: undefined,
  extensions: undefined,
  protocol: undefined,
  binaryType: undefined,
  bufferedAmount: undefined
}
open WebSocket {
  url: undefined,
  readyState: 1,
  extensions: undefined,
  protocol: null,
  binaryType: undefined,
  bufferedAmount: undefined
}
```
The socket returned by `Deno.upgradeWebSocket()` has all properties set to undefined.
In this case it is the same process that is connecting to itself, but I'm also seeing this behaviour when other clients are connecting.

**Comment by zizifn** [comment]
same issue here, `bufferedAmount` return `NaN` below is my code
```TS
import { serve } from 'https://deno.land/std@0.170.0/http/server.ts';

const handler = async (req: Request): Promise<Response> => {
  const upgrade = req.headers.get('upgrade') || '';
  const { socket, response } = Deno.upgradeWebSocket(req);
  socket.addEventListener('open', () => {});
  console.log('----begin -', socket.bufferedAmount);
  socket.addEventListener('message', async (e) => {
    socket.send(new TextEncoder().encode('11111111'));
    console.log(socket);
  });

  return response;
};

serve(handler, { port: 8080, hostname: '0.0.0.0' });
```

output this
```
WebSocket {
  url: undefined,
  readyState: 1,
  extensions: undefined,
  protocol: null,
  binaryType: undefined,
  bufferedAmount: NaN
}
```

**Comment by littledivy** [comment]
The bufferedAmount issue has been fixed in a rewrite of the ext/websocket crate. 

The other bug is simple, rest of the fields are not initialized when upgrading server requests: https://github.com/denoland/deno/blob/main/ext/http/01_http.js#L460

**Comment by bartlomieju** [comment]
@littledivy could you fill in these missing values?

**Comment by benStre** [comment]
Unfortunately, the fix (https://github.com/denoland/deno/pull/21433) breaks backwards compatibility in v1.39.0 as the onmessage event now returns a `Blob` per default. Before this fix, it returned an `ArrayBuffer` when the `binaryType` was not explicitly set (https://github.com/denoland/deno/blob/fa3a12a8056836e7ab337c4af1eabcb0e8edade2/ext/websocket/01_websocket.js#L439)
Is it possible to mention this in the release notes or somewhere to avoid confusion?

**Comment by bartlomieju** [comment]
@littledivy was that done on purpose? Shouldn't there be a WPT that covers it. It seems like a really obnoxious change and maybe we should revert it back?

**Comment by jespertheend** [comment]
I noticed the same thing, but I assumed it was intentional because this is how it's been spec'ed I believe.

**Comment by littledivy** [comment]
It followed the spec but I agree to revert back to using arraybuffer for server websockets.
