### ISSUE TITLE
`deno upgrade` should properly cleanup

### ISSUE THREAD

**Issue by kidonng** [denoland/deno#15342]
Currently, `deno upgrade` doesn't remove the downloaded zip (and uncompressed Deno binary if `--dry-run` is specified) when finished. This is bad practice and occupies space:

- On macOS, temporary directory is on disk and only cleaned on next boot;
- On Windows, temporary directory is on disk and (I believe) only occasionally cleaned;
- On Linux, temporary directory is (usually) in memory

**Comment by dsherret** [comment]
Fixed by https://github.com/denoland/deno/pull/16930
