### ISSUE TITLE
m1 mac ```cargo install deno```  error: linking with `cc` failed: exit status: 1 

### ISSUE THREAD

**Issue by hyeonLewis** [denoland/deno#15357]
Hi, I'm new to deno and trying to do ```cargo install deno --locked``` on my m1 mac.

But, I faced the following error: linking with `cc` failed: exit status: 1 when compiling deno_runtime.

Detail errors : 
```
note: ld: warning: directory not found for option '-L/var/folders/8d/ghvn9k417bzbswypjt9bygjw0000gn/T/cargo-installXZjGIQ/release/build/libffi-sys-41d632e011112856/out/libffi-root/lib64'

ld: in /private/var/folders/8d/ghvn9k417bzbswypjt9bygjw0000gn/T/cargo-installXZjGIQ/release/deps/libdeno_ffi-958ea6bcb4b3c055.rlib(libtcc.o), archive member 'libtcc.o' with length 120496 is not mach-o or llvm bitcode for architecture x86_64

clang: error: linker command failed with exit code 1 (use -v to see invocation) 
```

I actually met this error before and solved it when compiling other libraries, so I tried to solve this with the following solution: https://newbedev.com/error-linking-with-cc-failed-exit-code-1, but all solutions didn't work.

Is there any way to solve this error?

Thank you for any support.

**Comment by crowlKats** [comment]
@hyeonLewis are you still encountering this?

**Comment by ericlery** [comment]
@crowlKats @hyeonLewis I had the same thing while building `deno v1.39.0`, and following https://docs.deno.com/runtime/manual/references/contributing/building_from_source. 

The thing is, I had VS Code open with the extension `rust-analyzer`, presumably building/checking in the background while also building in my external terminal? I've noticed that my CPU cores were active even after the building command was exited on my external terminal. 

I closed VS Code, and my CPU idled, the extension stopped its work I guess.

Retried the build in my external terminal, and it worked.

I ensured that I have the latest `main` branch with:
```sh
git fetch origin # This upstream (git@github.com:denoland/deno.git)
git reset origin/main
```
The building was with: 
```sh
# Build errors?  Ensure you have latest main and try building again, or if that doesn't work try:
cargo clean && cargo build -vv
```

I have also disabled `rust-analyzer.cargo.buildScripts.enable` on the extension config. While I don't know if it's the right thing to do, my CPU is no longer being monopolized by unsolicited builds while already building or coding.

**Comment by littledivy** [comment]
This should be fixed because we got rid of tinycc dependency
