### ISSUE TITLE
Have a unique pause reason for `--inspect-brk`

### ISSUE THREAD

**Issue by connor4312** [denoland/deno#15360]
This weekend I was looking at making Deno nicer to use in the VS Code debugger.

One initial challenge is that we'd want to run Deno programs with `--inspect-brk`. However, this then causes the debugger to start paused in an arbitrary location. We do have an option for `continueOnAttach`, which works for Node, but not for Deno. This is because Node has a unique pause `reason`, ["Break on start"](https://github.com/microsoft/vscode-js-debug/blob/95d772b31e87ed4069e0d9242f424925792e96e9/src/adapter/threads.ts#L787-L789), that we use to determine when the pause is a result of `--inspect-brk`. 

It would be helpful if Deno similarly had a unique `reason` as a result of `--inspect-brk`. Currently, Deno simply calls `break_on_next_statement`

https://github.com/denoland/deno/blob/2703996dea73c496d79fcedf165886a1659622d1/core/inspector.rs#L317-L320

which pauses with a hardcoded `debugCommand` reason.

https://github.com/denoland/deno/blob/2703996dea73c496d79fcedf165886a1659622d1/core/inspector.rs#L571

Perhaps there could be a `break_on_next_statement_with_reason` method to give us a unique reason?

**Comment by bartlomieju** [comment]
Thanks for looking into this @connor4312, any improvements to inspector integration are much appreciated.

Is another method really required? I'm fine with changing `debugCommand` to any other value that would be more useful.

**Comment by bartlomieju** [comment]
Sounds good, thanks again for looking into it!
