### ISSUE TITLE
Deno.kill(pid, 'SIGINT') not work.

### ISSUE THREAD

**Issue by Bzvwf16WSDKoSZd8** [denoland/deno#15374]
OS: Windows 10 Home 21H2
The "pid" is an pid of external process which not open by Deno / Node.js

The Deno code
```ts
Deno.kill(pid, 'SIGINT')
```
Throwing Error: Uncaught TypeError: Invalid signal: SIGINT

The Node.js code
```ts
import process from 'node:process'
process.kill(pid, 'SIGINT')
```
This is work.

Is this a BUG?

**Comment by Soremwar** [comment]
Sigint is not implemented for Windows yet

See
https://github.com/denoland/deno/pull/14694
https://github.com/denoland/deno/pull/14865
