### ISSUE TITLE
Supports imports in REPL

### ISSUE THREAD

**Issue by Ayc0** [denoland/deno#1538]
When I run this code in the deno REPL, I've got:

```js
import * as deno from "deno"
```
```
SyntaxError: Unexpected token *
```

But the same code works in a js/ts file

**Comment by caijw** [comment]
how did you run `import * as deno from "deno"` ? 
a.ts: `import * as deno from "deno"`
`deno ./a.ts` goes well.

**Comment by Ayc0** [comment]
directly within the deno REPL, not within a file executed by deno:
```
deno
> import * as deno from "deno"
SyntaxError: Unexpected token *
```
