### ISSUE TITLE
ffi or ffi tests are flaky

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#15385]
https://github.com/denoland/deno/runs/7621476808?check_suite_focus=true#step:34:3120

```
error: test failed, to rerun pass '-p deno_ffi --lib'

Caused by:
  process didn't exit successfully: `/home/runner/work/deno/deno/target/release/deps/deno_ffi-bdfc7f2c6c67e2a1` (signal: 11, SIGSEGV: invalid memory reference)
Error: Process completed with exit code 101.
```

**Comment by aapoalas** [comment]
The failing test is doing relatively interesting things. It creates C callbacks on the main thread and a worker thread and sends the pointer values to one-another, calling each in turn on the receiver side.

This should work but obviously causes this flake so something's not quite right. I couldn't reproduce this locally when I tried the other day.

**Comment by kitsonk** [comment]
More examples from @dsherret :

https://github.com/denoland/deno/runs/7653539930?check_suite_focus=true
https://github.com/denoland/deno/runs/7601081851?check_suite_focus=true
https://github.com/denoland/deno/runs/7578966741?check_suite_focus=true

**Comment by dsherret** [comment]
I seem to hit this one almost every PR run.
