### ISSUE TITLE
Support `deno bench` in the config file

### ISSUE THREAD

**Issue by GJZwiers** [denoland/deno#15408]
Having the ability to `include/exclude` fields for `deno bench` in the configuration file would be helpful at times. For example, I had a project in compat mode where a `node_modules` folder contained a number of `bench.js` files which were picked up by `deno bench`. While it is possible to use `--ignore` on the terminal, there are no options for deno bench in the config file unlike `deno test/lint/fmt`.

Example:

```json
{
  "bench": {
    "files": {
      "exclude": "node_modules/"
    }
  }
}
```

**Comment by bartlomieju** [comment]
It's a good idea, PRs are most welcome!
