### ISSUE TITLE
Add a flag for allowing requests to fail during `deno vendor`.

### ISSUE THREAD

**Issue by jespertheend** [denoland/deno#15401]
#15391 makes Deno error when a dynamic import fails to load. This causes no files to get vendored.
However, there might be cases where vendoring modules is still desirable, even when some files fail to load.
Would it be possible to add a flag to `deno vendor` to continue vendoring even though a request fails?

My current use case is that I'm trying to download https://esm.sh/rollup@2.75.7?pin=v87&target=es2022 to disk, so that it can be loaded from a local server during development. At the moment this fails because one of its dynamic imports responds with a 500 status code, but  the vendored module still load fine in a browser even though some files are missing.

Admittedly this might be a bit out of scope. I suppose `deno vendor` wasn't really intended for this use case, and maybe esm.sh is at fault for responding with a 500 status code.
But I reckon there might be other instances where an invalid status code is returned that are not exclusive to this use case.

**Comment by jespertheend** [comment]
What would be the best way to implement this?
- Should the flag simply cause all failed requests to be ignored?
- Should the user be able to specify which requests are allowed to fail?
- Should only dynamic imports be ignored? (In the case above fsevents.js is dynamically imported)

**Comment by jespertheend** [comment]
I just realised working around this issue is somewhat straight forward by simply adding any offending imports to the import map. Not sure why I didn't think of this sooner.

**Comment by dsherret** [comment]
In the next release, deno vendor will warn instead of fail for dynamic imports that don't load.

We may want to change deno_graph to warn on all load errors instead of failing when vendoring, but it adds additional complexity that I'm not sure is worth it given there is the workaround that you mentioned. I'm going to close this one.
