### ISSUE TITLE
`Deno[Deno.internal].runTests` is writable

### ISSUE THREAD

**Issue by nayeemrmn** [denoland/deno#15419]
```ts
// @ts-ignore
delete Deno[Deno.internal].runTests;
Deno.test("asdf", () => {});
```
Rather than just making this namespace immutable, we should clean this up by using `JsRuntime::grab_global()` to store such callbacks, as we do in core, between runtime init and bootstrap.

**Comment by nayeemrmn** [comment]
This is a problem again as of #16597 if you can reopen @bartlomieju

**Comment by bartlomieju** [comment]
No longer relevant.
