### ISSUE TITLE
Question: Node.js Native Addons

### ISSUE THREAD

**Issue by mtmulch1** [denoland/deno#15417]
Hello, had a question regarding compatibility with Node.js addons. Was reading about this years ago. I've seen some compatibility articles and issues regarding the subject.  I can see that deno_std is not currently 100% stable. It is possible to load a Node.js addon written in TypeScript that utilities Node.js C/C++ addons either via CommonJS or the URL caching? 

https://github.com/denoland/deno_std/blob/main/node/README.md
https://github.com/denoland/deno/issues/2644

**Comment by bartlomieju** [comment]
No, it's currently not possible We have a PR going to add support for it in #13633

**Comment by mtmulch1** [comment]
Excellent. Thank you.
