### ISSUE TITLE
`deno_core::resolve_import` is CWD dependant

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#15436]
`deno_core::resolve_import("", "<unknown>")` causes an `std::fs::cwd` call to be made. This is highly unexpected and possibly a hazard, considering that `deno_core` is otherwise completely oblivious to the underlying module loading system. As far as I am aware this cwd can not leak into the isolate, so the hazard is restricted to only Rust embedders. Regardless, `resolve_import` should not treat `<unknown>` as a special base URL that results in a `std::fs::cwd` call.

**Comment by bartlomieju** [comment]
Already done, see the linked PR above.
