### ISSUE TITLE
Error: Algorithm "sha1"  not supported

### ISSUE THREAD

**Issue by ash-hashtag** [denoland/deno#15431]
`
Uncaught (in promise) Error: Algorithm "sha1"  not supported. supported values: BLAKE2B-256, BLAKE2B-384, BLAKE2B, BLAKE2S, BLAKE3, KECCAK-224, KECCAK-256, KECCAK-384, KECCAK-512, SHA-384, SHA3-224, SHA3-256, SHA3-384, SHA3-512, SHAKE128, SHAKE256, TIGER, RIPEMD-160, SHA-224, SHA-256, SHA-512, MD4, MD5, SHA-1, passthrough
`

I'm trying to use some node modules(maybe shouldn't), which requires sha1, it says it supports SHA-1 tho, but not sha1. What can I do to tell deno it's just SHA-1

**Comment by kitsonk** [comment]
Use `SHA-1` instead of `sha1` which us not valid.
