### ISSUE TITLE
`deno test` errors when using project root for absolute imports

### ISSUE THREAD

**Issue by mentoc3000** [denoland/deno#15435]
Steps to reproduce:

1. Create file `a_test.ts` containing

```ts
import { assertEquals } from "https://deno.land/std@0.151.0/testing/asserts.ts";

Deno.test("test1", () => {
  assertEquals(1, 1);
});
```

2. Create file `imports.json` containing

```json
{
    "imports": {}
}
```

3. Run `deno test --import-map=imports.json`. Observe that the test passes:

```
> deno test --import-map=imports.json
running 1 test from ./a_test.ts
test1 ... ok (7ms)

ok | 1 passed | 0 failed (46ms)
```

5. Update `imports.json` to use [project root for absolute imports](https://deno.land/manual/linking_to_external_code/import_maps#:~:text=To%20use%20your%20project%20root%20for%20absolute%20imports):

```json
{
    "imports": {
        "/": "./"
    }
}
```

6. Run `deno test --import-map=imports.json` again. Observe error:

```
> deno test --import-map=imports.json

ok | 0 passed | 0 failed (27ms)

error: Module not found "file:///C:/path/to/repo/a_test.ts".
```

Version information:

```
> deno --version
deno 1.24.2 (release, x86_64-pc-windows-msvc)
v8 10.4.132.20
typescript 4.7.4
```

**Comment by nayeemrmn** [comment]
> 9\. Update `imports.json` to use [project root for absolute imports](https://deno.land/manual/linking_to_external_code/import_maps#:~:text=To%20use%20your%20project%20root%20for%20absolute%20imports):
> 
> ```json
> {
>     "imports": {
>         "/": "./"
>     }
> }
> ```

The link says to use:
```json
{
  "imports": {
    "/": "./",
    "./": "./"
  }
}
```

**Comment by mentoc3000** [comment]
Thanks! Yes, I see that both lines need to be there. I would like to use `./src/` as my root directory for relative imports, but I get the same error as described in the original post when using this `imports.json` file:

```json
{
  "imports": {
    "/": "./src/",
    "./": "./src/"
  }
}
```

Why is that happening?

**Comment by nayeemrmn** [comment]
@mentoc3000 The correct augmentation for that is
```json
{
  "imports": {
    "/": "./src/",
    "./": "./"
  }
}
```
You basically want add a second entry to reset the affect of the first entry for imports which are not supposed to be mapped, since `./src/` would otherwise fall under `/`.
