### ISSUE TITLE
`await Promise.any([])` in REPL crashes with `Fatal javascript OOM in Ineffective mark-compacts near heap limit`

### ISSUE THREAD

**Issue by hyp3rflow** [denoland/deno#15443]
1. Run `await Promise.any([])` in REPL mode.
2. It stucks and `Fatal javascript OOM in Ineffective mark-compacts near heap limit` error occurs.

**Comment by hyp3rflow** [comment]
I've just got an error in `deno run -A --unstable --watch=.`, not in REPL. but I can't repro it :(

**Comment by masx200** [comment]
https://github.com/denoland/deno/issues/14496

**Comment by hyp3rflow** [comment]
It seems that this bug is started occurring after version 1.21.0.
