### ISSUE TITLE
Can not import JSON config file if the config file specifies jsxImportSource

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#15440]
```js
// main.ts
import config from "./deno.json" assert { type: "json" };
const obj = { config };
export default obj;
```

```json
// deno.json
{
  "compilerOptions": {
    "jsx": "react-jsx",
    "jsxImportSource": "preact"
  },
  "importMap": "./import_map.json"
}
```

```json
// import_map.json
{
  "imports": {
    "preact/": "https://esm.sh/preact@10.8.2/"
  }
}
```

```
$ deno run -A main.ts
error: Loading unprepared module: file:///tmp/jsx_config_issue/deno.json
```

I think what is happening is that the config file is stored in the module graph as some sort of special entry, which is causing this weird behaviour.

**Comment by lucacasonato** [comment]
Transferring back to denoland/deno and re-opening because the issue is not yet resolved.

**Comment by sebringrose** [comment]
Not sure if relevant to this but I have started receiving the following error when running a local test now: 

`error: Loading unprepared module: [filesystem]/peko/middleware/logger.ts`

As you can see the file is not a .json file. I have not changed the test file and it was previously working with no errors. Tests are still running fine in GitHub actions too so I suspect this may be part of a module graphing bug?

**Comment by nayeemrmn** [comment]
@sebringrose If it still works in CI try `--reload` or deleting your cache
