### ISSUE TITLE
Including `eval()` in a source file causes bundling to generate broken output

### ISSUE THREAD

**Issue by ascorbic** [denoland/deno#15450]
~~Certain emscripten files~~ **Any file that includes `eval()`** causes the bundler to generate files with syntax errors, due to duplicate identifiers. There is no wasm loaded: simply importing the module wrapper is enough to cause it. The same code runs fine via `deno run`, but when bundled it does not dedupe identifiers. The following is a minimal repro:

```typescript
// index.ts
import { hello as hello1 } from "./hello.ts";
import { hello as hello2 } from "./hello2.ts";
function doEval() {
  eval("console.log('hello');");
}
console.log(hello1, hello2, doEval);
```

```typescript
// hello.ts
export const hello = "Hello World";
```

```typescript
// hello2.ts
export const hello = "Hello World 2";
```

Executing `deno run index.ts` runs correctly, logging `Hello World Hello World 2 [Function: doEval]`. 

Running `deno bundle index.ts` generates the following:

```javascript
// deno-fmt-ignore-file
// deno-lint-ignore-file
// This code was bundled using `deno bundle` and it's not recommended to edit it manually

const hello = "Hello World";
const hello = "Hello World";
function doEval() {
    eval("console.log('hello');");
}
console.log(hello, hello, doEval);

```
This of course fails because of duplicate identifier.

**Comment by kitsonk** [comment]
Can you provide the output of `deno --version` please.

**Comment by ascorbic** [comment]
```
deno 1.24.2 (release, aarch64-apple-darwin)
v8 10.4.132.20
typescript 4.7.4
```

**Comment by ascorbic** [comment]
I isolated the actual problem. The file included a function that used `eval()`. I've updated the name and description.

**Comment by kitsonk** [comment]
Oh wow, that is really strange that was a _magic bullet_ that breaks the symbol renaming.

**Comment by ascorbic** [comment]
The best kind of weird bug! I had some fun isolating that one.

**Comment by brenelz** [comment]
I was able to reproduce. I'm thinking maybe upgrading `swc_ecma_codegen` might do the trick or its a bug in that crate

https://github.com/denoland/deno_ast/blob/main/Cargo.toml#L49

**Comment by lucacasonato** [comment]
`deno bundle` was deprecated and has been removed in Deno 2.
