### ISSUE TITLE
Supports TypeScript while also browser compatible?

### ISSUE THREAD

**Issue by davidbarratt** [denoland/deno#1547]
"Supports TypeScript out of the box."
and
"Aims to be browser compatible."

seem mutually exclusive, or am I missing something? How can deno support TypeScript out of the box, but also be browser compatible? Or is the compatibility in one direction (i.e. it supports everything the browser does but not the other way 'round)?

It might be worth clarifying this in the docs maybe?

**Comment by ry** [comment]
Browser compatible means that where we overlap in functionality with the browser, EG `fetch()` that we use the browser APIs. There are many things you can do in deno that will not run in the web browser - typescript is one of them - starting a TCP server is another. But if you use javascript and don't import the built-in "deno" module, the script should be browser compatible.

**Comment by davidbarratt** [comment]
Thanks for the clarification!

**Comment by rsp** [comment]
@davidbarratt There are projects like:
- [typescript-script](https://github.com/basarat/typescript-script)
- [typescript-compile](https://github.com/niutech/typescript-compile)

that allow you to use TS directly in `<script>` tags in the browser.
(Not that it's efficient but it's possible.)
