### ISSUE TITLE
`deno test` coverage doesn't handle code run in workers

### ISSUE THREAD

**Issue by jespertheend** [denoland/deno#15473]
Here is a reduced test case: [workercoverage.zip](https://github.com/denoland/deno/files/9333788/workercoverage.zip)
Run `./runTest.sh` and observe the result in `html/index.html` folder.
You need to have genhtml installed, but otherwise you can also check the result of `lcov.info` to see that it only contains coverage of the `startWorker.js` file.

**Comment by kitsonk** [comment]
Duplicate of #13206
