### ISSUE TITLE
lsp: cannot disable Deno auto import or auto discovery

### ISSUE THREAD

**Issue by waynebloss** [denoland/deno#15488]
**Describe the bug**

When I type text into a `ts` file in a project where the Deno extension is enabled, I get autocomplete suggestions for symbols that have not been imported. When I choose one of them, a import is added at the top of my module even though I have the following settings all set to `false`:

```jsonc
{
  "deno.suggest.autoImports": false,
  "deno.suggest.imports.autoDiscover": false,
  "typescript.suggest.autoImports": false,
  "javascript.suggest.autoImports": false,
}
```

**To Reproduce**

1. Set the settings mentioned above.
2. Reference an un-imported symbol in a `ts` file.
3. Observe that a new import for the symbol is added to the top of the file, after you trigger autocomplete the symbol.

**Expected behavior**

No imports should automatically be added to my files please. I also would not like suggestions for symbols that aren't already imported or global.

**Versions**

vscode: 1.69.2 deno: 1.24.3 extension: 3.13.1

**Comment by cuobiezi** [comment]
@waynebloss Would you provide keyword you input before get auto suggestion symbols?

**Comment by waynebloss** [comment]
@cuobiezi If I type any symbol that exists in my project or in a dependency of my project, it shows up in the auto-complete list.

With a dependency for example, I have referenced [sqlite3](https://deno.land/x/sqlite3@0.4.3/mod.ts) in my `deps.ts`, but I only re-export certain symbols from it. However, whenever I type the letters `sql` I get this huge autocomplete list of things that I don't use directly...

![image](https://user-images.githubusercontent.com/623736/185689905-7d0dff12-d9ab-44b0-8887-18a2dc733d39.png)

and if I choose any of the completions, the following is added to the top of my current file (when `sqlite3_blob_read_async` is the chosen completion):

```ts
import { sqlite3_blob_read_async } from "https://deno.land/x/sqlite3@0.4.3/src/ffi.ts";
```

In the case of a local symbol, I have a function named `openUrl` defined in a file `src/lib/openUrl.ts` and exported from `src/lib/mod.ts`.

When I type the letters `open`, I see `openUrl` in the list, even though I have not imported `openUrl` into the file that I'm typing into. When I choose it, the following is added to the top of the file:

```ts
import { openUrl } from "./lib/openUrl.ts";
```

On other piece of important info that may have some bearing: I have an importMap defined which points the path `$/` to `./src/` and the automatic import should  have used that as well. (But, I don't really care about this sub-issue because I don't want to see un-imported symbols in the autocomplete list or use auto imports.)

**Comment by kyoh86** [comment]
According to below, the `sugget. auto_imports` is passed to another option `include_completions_for_import_statement`.
https://github.com/denoland/deno/blob/306b51d7728a6e28461171d3332a0b3aa8545a6e/cli/lsp/language_server.rs#L2308-L2310

I understand that this option tells tsc to do autocomplete for the `import` statement or not.
However, from the comment below, deno ls should resolve the autocomplete of imports by deno itself.
https://github.com/denoland/deno/blob/306b51d7728a6e28461171d3332a0b3aa8545a6e/cli/lsp/language_server.rs#L2262-L2265

If the `sugget.auto_imports` is really appropriate for what we intend, that is simply passing to the wrong option.
Passing it to `include_completions_for_module_exports` would solve the problem.
I tried passing `false` to `include_completions_for_module_exports`, I don't get autocomplete suggestions for symbols that have not been imported

**Comment by kyoh86** [comment]
I will begin to fix this.
