### ISSUE TITLE
Snapshot global handle not serialized

### ISSUE THREAD

**Issue by bakjos** [denoland/deno#15490]
When using the runtime and trying to create a snapshot it fails with the following error:

```global handle not serialized: 0x291600516ccd <JSFunction promiseRejectCallback (sfi = 0x29160047b331)>
global handle not serialized: 0x29160046e5a9 <JSFunction handleTimerMacrotask (sfi = 0x29160047d25d)>
global handle not serialized: 0x291600516ced <JSFunction promiseRejectMacrotaskCallback (sfi = 0x29160047b365)>
global handle not serialized: 0x291600567ea9 <JSFunction handleWasmStreaming (sfi = 0x2916005627e5)>
global handle not serialized: 0x291600516c6d <JSFunction formatException (sfi = 0x29160047b251)>```

**Comment by bartlomieju** [comment]
Please provide a reproduction that causes this panic. I'm skeptical about cleaning these fields unconditionally since snapshotting works fine in Deno.

**Comment by bakjos** [comment]
@bartlomieju  I added a test on the PR, if you run it in the current version you'll get the panic https://github.com/denoland/deno/blob/5c9958351241322164a6496ead049f9139ec7eb7/core/runtime.rs#L2685-L2720
