### ISSUE TITLE
Don't cache localhost imports (or give an option to turn it off)

### ISSUE THREAD

**Issue by mimbrown** [denoland/deno#15509]
The reason Deno caches remote imports, in my understanding, is (a) so that subsequent runs will be faster, and (b) so that previously imported modules can be imported even offline. Caching can be done without causing problems because we assume the content delivered by the server is (mostly) not going to keep changing on us.

None of this is true when the "remote" is localhost. The content isn't actually remote, so the speedup is probably negligible. Localhost works fine offline. And, most importantly, the assumption that the content being served is not changing is often wrong (i.e. in an active development context, which is what localhost is normally used for).

There's plenty of precedent for treating localhost differently, for example, Chromium treats localhost as a secure context even over http.

I propose that the default behavior be for Deno to *not* cache imports from localhost. Possibly it would be worth adding a flag to force even localhost files to be cached as well, though I'm stumped to come up with a legitimate use case for that.

**Comment by bartlomieju** [comment]
You can achieve that by specifying `--reload=http://localhost`

**Comment by mimbrown** [comment]
> You can achieve that by specifying `--reload=http://localhost`

Yes that fixes some problems, but not all. First, that doesn't prevent Deno from caching, just forces it to ignore the cache. I don't actually want the increased cache size that comes from caching all imports that come through `localhost`. With that, if I'm developing a site with 500 modules, I don't want to see 500 `Download http://localhost:8080/whatever` messages on my console every time I refresh.

But on principle, I would argue I shouldn't have to pass a flag to get behavior that should be the default. It doesn't make any sense, IMO, for localhost imports to be cached. What happens if I forget the flag? Suddenly the file I'm importing could actually be serving up a pre-cached file from a separate project on the same machine that happens to have the same name and was imported earlier using the same `localhost` port. That could lead to some hair pulling bug hunts.

**Comment by swwind** [comment]
Adding a reload option does not prevent deno from panicking when localhost import updates and failed to match lock file.

![image](https://github.com/denoland/deno/assets/26316494/6a718b2a-7243-4538-aba3-03fd84700cee)

**Comment by asyncanup** [comment]
How can we un-stale this issue?

**Comment by bartlomieju** [comment]
> How can we un-stale this issue?

I suggest to open a new issue with description of your use case.
