### ISSUE TITLE
Property 'entries' does not exist on type 'URLSearchParams'. deno-ts(2339)

### ISSUE THREAD

**Issue by roj1512** [denoland/deno#15517]
But it is defined:

```shell
 $ deno  
Deno 1.24.3
exit using ctrl+d or close()
> new URLSearchParams().entries()
URLSearchParams Iterator {}
> 
```

**Comment by kitsonk** [comment]
This is not a complete reproduction. What is the configuration of the project you are using?

Likely you are setting `lib` to `dom` but forgetting to add `dom.iterable`.

**Comment by roj1512** [comment]
There's no custom configuration afaik. It's just from a Fresh project.

**Comment by roj1512** [comment]
This was a problem with Fresh and should be fixed by https://github.com/denoland/fresh/pull/641. Thanks for your help, @kitsonk!
