### ISSUE TITLE
`deno vendor` doesn't work when vendoring module at url without a path

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#15510]
If you try to vendor a module at a url without a path it will fail.

**Comment by dsherret** [comment]
Investigated this with Luca today and it's a little complicated because there is no distinction between an import map entry key without a path with or without a trailing slash (in other words "https://localhost" and "https://localhost/" are treated as the same by both deno and chrome).

To make this work, we'll have to add import map entries for the entry without a path and all the children. For example:

https://github.com/denoland/deno/commit/710c15dd787fd48ec5d16baa2f00b0b36fc84582

**Comment by lucacasonato** [comment]
`deno vendor` was deprecated and has been removed in Deno 2.
