### ISSUE TITLE
Compatibility with WHATWG at URL and URLSearchParams

### ISSUE THREAD

**Issue by watilde** [denoland/deno#1551]
Hello 👋

As I mentioned at https://github.com/denoland/deno/pull/1549, we need to add more things to have compatibility with URL specification in WHATWG and make sure if it's correct by running all [WPT tests](https://github.com/web-platform-tests/wpt/tree/master/url).

I'm wondering if it's ok to just use [jsdom/whatwg-url](https://github.com/jsdom/whatwg-url) instead of having full implementation and running all tests in WPT.

**Comment by kitsonk** [comment]
As mentioned in the original PR for `URL` it wasn't intended to follow the spec exactly: #1359 . The `jsdom/whatwg-url` has a lot of logic, following the specification exactly, that really is a bit overkill.  My opinion is we should just fix issues when we find them.

**Comment by watilde** [comment]
I'm not quite sure which part can be exactly overkilled in WHATWG URL yet, but I'm sure they really cover almost all edge cases. For me, one more big plus here is that we can update the spec itself if there is any useless process which also updates `whatwg-url` :)

For this part,
> we should just fix issues when we find them.

One of the effecient ways to find _them_ is running [WPT tests](https://github.com/web-platform-tests/wpt/tree/master/url) and I could find a lot already. That was the original reason why I started writing a patch.

**Comment by piscisaureus** [comment]
Fixed in #853
