### ISSUE TITLE
`reportError()` segfaults in the repl

### ISSUE THREAD

**Issue by QmelZ** [denoland/deno#15528]
**reproduction**: run `reportError()` with any argument in repl

**expected behavior**: argument gets printed and repl exits

**what actually happens**: process exits with SIGSEGV

**Comment by bartlomieju** [comment]
@nayeemrmn can you take a look?

**Comment by nayeemrmn** [comment]
Nah it's not addressed. I think we have to cancel termination in the repl case somewhere

**Comment by bartlomieju** [comment]
Ah, that makes sense, REPL shouldn't ever cancel termination completely
