### ISSUE TITLE
Unable to create --help option in the user's script.

### ISSUE THREAD

**Issue by kt3k** [denoland/deno#1554]
I started creating a CLI tool in deno like the below:
```ts
#!/usr/bin/env deno --allow-run
import { parse } from "https://deno.land/x/flags@v0.2.6/mod.ts"
import { exit, args } from "deno"

const main = async (opts) => {
  if (opts.help) {
    console.log(`Usage: my-command`)
    exit(0)
  }

  console.log('something')
}

main(parse(args.slice(1)))
```

When I pass `--help` option to this script, deno's help message was printed like the below:
```
$ deno example.ts 
something
$ deno example.ts --help
Usage: deno script.ts 

Options:
        --allow-write   Allow file system write access.
        --allow-net     Allow network access.
        --allow-env     Allow environment access.
        --allow-run     Allow running subprocesses.
    -A, --allow-all     Allow all permissions
...
```

This means my tool is unable to have `--help` option and this is inconvenient.

**Comment by kevinkassimo** [comment]
@kitsonk @kt3k I believe this is what we are expecting here: https://docs.rs/getopts/0.2.18/getopts/enum.ParsingStyle.html#variant.StopAtFirstFree

**Comment by kevinkassimo** [comment]
A proposal about flags:
Mixing deno and v8 flags is quite confusing. Since v8 flags are used less often than other deno flags, we could choose to prefix all v8 flags with `v8`, e.g. `--expose-gc` becomes `--v8-expose-gc`.

**Comment by sholladay** [comment]
In Node, any flags/arguments that come after the user's script _belong_ to the user's script.
```console
# foo's help is shown, assuming foo.js handles `--help` in some way
$ node foo.js --help
```
```console
# Node's help is shown and foo.js is ignored
$ node --help foo.js
```

That works pretty well in my experience and I would say Deno should behave the same.

**Comment by kevinkassimo** [comment]
@sholladay Yeah that corresponds to StopAtFirstFree parsing style. Other flags at this moment follows this design well, only that `--help` is processed in a slightly different and problematic way: there is a collision between deno's help flag and that of v8.

**Comment by bartlomieju** [comment]
Please check out this PR: https://github.com/denoland/deno/pull/1199/files

**Comment by ry** [comment]
> In Node, any flags/arguments that come after the user's script belong to the user's script.

I'm against this for the following reasons:
1. I think knowing that flags after the script belong to the script is just an extra thing people need to know. It's simpler if all flags are passed through.
2. It's an ergonomic issue. I want to be able to type "[up key] -A" in the shell. That is append to the _end_ of the shell invocation flags.

I think we can satisfy my desires and support `--help` in user scripts with some one-off logic: a script is specified in the args, pass the --help through.
Maybe this custom logic ends up being more complex for users than just doing things as Node does them (or using `--`). I'm willing to concede that if we continue to run into issues - but at the moment I'd like to try a bit harder to support CLI args in any position.

@kevinkassimo regarding V8 flags - I think it's a separate issue?

**Comment by kevinkassimo** [comment]
@ry My only concern about this design is that it would render attempts to use shebang that hides away `deno` broken... considering especially flags like `-A`, `-D`, etc. common.
(sidenote: we can currently allow extensionless script with shebang run just fine with deno using .mime files)

V8 flags sound indeed like a separate issue. I brought it up here simply because our current logic of handling it seems "weird" and causes troubles if I want to change the flag code even a little bit.

**Comment by ry** [comment]
> My only concern about this design is that it would render attempts to use shebang that hides away deno broken... considering especially flags like -A, -D, etc. common. Breaks transparency.

@kevinkassimo I don't think I follow. Can you give an example?

**Comment by kevinkassimo** [comment]
@ry consider a script `shebang` (no extension):
```ts
#!/usr/bin/env deno
import * as deno from "deno";
console.log(deno.args)
```
with `shebang.mime`:
```
text/typescript
```

Run `./shebang -A`, emits:
```
[ "./shebang" ]
```
`-A` is gone due to our flag processing logic. Would surprise users.

**Comment by lucascaro** [comment]
how about using `--`? that would potentially solve the issue when it matters (i.e. shebang case)

```bash
#!/usr/bin/env deno --allow-all --
```

the above shebang would pass specific arguments to deno while passing everything else to the program, and it's optional so users wanting to add deno arguments at the end would be able to do so.

**Comment by ry** [comment]
This should be possible now with the clap-based flag parsing.
