### ISSUE TITLE
`Deno.serve` issues

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#15551]
Quick list of things I think we need to address with the new `--unstable` `Deno.serve` API.

- [ ] Rename the API. `Deno.serve` does not clearly communicate the relation to HTTP. Strawman: `Deno.listenAndServeHttp`. Anyone else have other ideas?
- [x] Change signature to `(handler: (Request, ConnInfo) => Response, opts?: ListenAndServeHttpOptions) => Promise<void>` (move handler out of options bag).
- [ ] Rename `cert` and `key` options to `certFile` and `keyFile`.
- [ ] Add `certData` and `keyData` options that don't require reading these files from disk.
- [ ] Errors returned from `server.serve()` should not be swallowed with a `.catch(console.error);`.
- [ ] <s>Errors occuring in `server.serve` should clean up server resources</s>
- [ ] <s>Each server should have it's own date interval, otherwise each invocation to the API creates a different number of resources, which is confusing to users when using the test resource sanitizer.</s>
- [x] #15574
- [x] #15572
- [ ] <s>Remove all of the unwraps when handing values from JS.</s>
- [ ] <s>Flash does not handle socket write failures at all. If a write fails, or only writes partial data, we completely ignore this and just go onto the next write... </s>
- [ ] <s>The safety comments very often don't explain why something is safe. They just say "it's safe".</s>
- [ ] <s>Flash can not handle arbitrary methods.</s>
- [x] #15573

**Comment by kitsonk** [comment]
These are the 3 things that are keeping me from making flash enabled by default for oak:

- There currently isn't a way to obtain the remote connection IP address, meaning `ctx.request.ip` and `ctx.request.ips` do not work properly.
- There appears to be an issue with streaming large files with flash.
- Some of the exception handling with flash isn't as flexible as the "native" implementation, meaning that certain errors result in a hard coded 500 internal server error as well as "invalid" responses result in a server hang.

**Comment by kt3k** [comment]
> Rename cert and key options to certFile and keyFile.
> Add certData and keyData options that don't require reading these files from disk.

Should we support both `certData/keyData` and `certFile/keyFile`?

We've already deprecated certFile/keyFile options in `ListenOptions` #13740, removed `certFile` in `StartTlsOption` when stabilizing (#12581). `certFile` in `ConnectTlsOption` is also deprecated #12219

**Comment by billywhizz** [comment]
it would be nice to have access to the lower level socket options in some way also. failing that, some configurable options in api to set tcp keepAlive, noDelay, reusePort, reuseAddress etc. would be good. currently, i have no way to spin up multiple instances and have the kernel do load balancing across them easily, which [reusePort](https://lwn.net/Articles/542629/) would enable.

**Comment by littledivy** [comment]
@billywhizz There is `Deno.upgradeHttp(request)` to get the tcp stream (but not for the tcp listener). I think we should enable reuse port by default.

**Comment by lucacasonato** [comment]
> Should we support both certData/keyData and certFile/keyFile?

@kt3k Sure.

**Comment by st0le** [comment]
Minor thing.

When using npm:imports, I noticed 1.25 prints an error asking the user to run with --unstable flag.

The same doesn't happen for Deno.serve(), but it only works behind the unstable flag. Instead just throws, "Deno.serve is not a function".

**Comment by bartlomieju** [comment]
Since rewrite in https://github.com/denoland/deno/commit/2846bbe0a3de0cc366006f97023ce146112c40c9 I updated the original description, removing no longer relevant issues.
