### ISSUE TITLE
suggestion: `Deno.permissions.querySync`

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno#15576]
`Deno.permissions.query` is currently async. A sync version would be useful in contexts where top-level await would otherwise break node. Refs:
* denoland/deno_std#2446
* denoland/deno_std#1495
* denoland/deno_std#1396 (possibly)

In denoland/deno_std#1495 in particular, @bartlomieju mentions that a sync version of this API might not be a good idea. Is this still the case? If so, is there a decent workaround for the above-mentioned refs?

**Comment by iuioiua** [comment]
@bartlomieju, do you have any thoughts?

**Comment by iuioiua** [comment]
@bartlomieju, just following up. Would love to hear your thoughts.

**Comment by lino-levan** [comment]
I remember reading somewhere that this was planned and then scrapped by the core team but I can't seem to find that discussion right now. @bartlomieju did that happen or am I misremembering it?

**Comment by martin-braun** [comment]
Solving this would help to finish https://github.com/denoland/deno_std/pull/2785, context here: https://github.com/denoland/deno_std/issues/2594#issuecomment-1317913272

**Comment by iuioiua** [comment]
@bartlomieju, are you able to elaborate?

**Comment by bartlomieju** [comment]
We have recently discussed it and @kt3k suggested that it might be needed in `deno_std`. I'm still in favor of adding sync version of permission APIs, if you want to give it a crack a PR would be good to discuss it further 👍
