### ISSUE TITLE
Segmentation fault (core dumped) on Manjaro

### ISSUE THREAD

**Issue by Valerioageno** [denoland/deno#15575]
Hey everybody, simply scaffolding a new project I receive a segmentation fault error on Manjaro `Segmentation fault (core dumped)`. I've tried also on my MacOS machine but everything looks fine (same deno version). 
By the network tab I saw that it returns a 200 code for the first ALIVE request and then fails. The server doesn't return the counter client side JS but just display the DOM elements (same with or without twind).
The error occur on both dev and prod environments. 
I'm not sure if the issue is about fresh or the entire deno runtime.

Following my specs.
Deno: 1.24.3
OS: Manjaro Linux x86_64
Kernel: 5.15.48-1-MANJARO

**Comment by kkiyama117** [comment]
The above error is from my work environment, but I did not get the error in another environment using manjaro Linux. I will check what happened later, but for now, I would like to share the information on the environment that worked well.

```
# deno --version
deno 1.24.3 (release, x86_64-unknown-linux-gnu)
v8 10.4.132.20
typescript 4.7.4

# cat /etc/lsb-release
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=21.3.7
DISTRIB_CODENAME=Ruah
DISTRIB_DESCRIPTION="Manjaro Linux"

# uname -r
5.19.1-3-MANJARO

# cat import_map.json
{
  "imports": {
    "$fresh/": "https://raw.githubusercontent.com/lucacasonato/fresh/main/",
    "preact": "https://esm.sh/preact@10.10.0",
    "preact/": "https://esm.sh/preact@10.10.0/",
    "preact-render-to-string": "https://esm.sh/preact-render-to-string@5.2.1?external=preact",
    "twind": "https://esm.sh/twind@0.16.17",
    "twind/": "https://esm.sh/twind@0.16.17/"
  }
}
```

**Comment by kkiyama117** [comment]
I deleted the cache after aligning the import_map with the one that gave me the error, and it worked fine there too. The only difference (except for hardware such as CPU) is the version of Manjaro.

**Comment by Valerioageno** [comment]
I'm try to debug it. Interesting stuff is that using `curl http://localhost:8000` the runtime doesn't brake. Seems like the issue comes from the refresh.js that is not being executed with curl which should try to perform the following function
```typescipt
new EventSource("/_frsh/alive").addEventListener("message", function listener(e) { if (e.data !== "2fdffb7d-6529-47b9-8193-73a77a885ea4") { this.removeEventListener('message', listener); location.reload(); } })
```

**Comment by kkiyama117** [comment]
@Valerioageno I got the same log
```
curl http://localhost:8000/_frsh/alive

data: 47f88bda-fdd9-43cb-b4b8-a3fad1df1f03
retry: 100

curl: (18) transfer closed with outstanding read data remaining
```
