### ISSUE TITLE
flash should set sendfile `count` to size returned by `stat`

### ISSUE THREAD

**Issue by littledivy** [denoland/deno#15573]
A user could change the size of the file after the stat call, while the send is still ongoing.

**Comment by kamilogorek** [comment]
Partially resolved via https://github.com/denoland/deno/pull/15615 which got closed, so this should be probably reworded somehow.

**Comment by bartlomieju** [comment]
This appears to be resolved by https://github.com/denoland/deno/commit/2846bbe0a3de0cc366006f97023ce146112c40c9. I'm gonna close this for now, but happy the revisit if someone can hit this problem again.
