### ISSUE TITLE
Add a lint step that ensures Rust crates in the repo don't have circular dependencies

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#15586]
Using https://github.com/denoland/automation we should add another lint step to `tools/lint.js` that ensures that Rust crates have no circular dependencies. One dependency snuck and caused a problem in https://github.com/denoland/deno/pull/15585.

Potentially we should also have a lint that verifies that dependencies in `Cargo.toml` files always have `version` specified.

CC @dsherret

**Comment by bartlomieju** [comment]
@dsherret do we actually want to do that given that automation scripts can now handle such cases?

**Comment by dsherret** [comment]
Let's close.
