### ISSUE TITLE
deno_ffi crate source is missing tinycc files

### ISSUE THREAD

**Issue by g2p** [denoland/deno#15596]
There seems to be an error with the publishing process, a submodule wasn't included and that makes deno 1.25.0 impossible to install from crates.io (tested on Linux).

The deno_ffi build script breaks because tinycc isn't included in the crate source tarball.

```
CARGO_TARGET_DIR=/tmp/cargo-installhXwaLD cargo install -j1 deno
    Updating crates.io index
  Installing deno v1.25.0
   Compiling deno_ffi v0.53.0
error: failed to run custom build command for `deno_ffi v0.53.0`

Caused by:
  process didn't exit successfully: `/tmp/cargo-installhXwaLD/release/build/deno_ffi-4402470cd9da2f6a/build-script-build` (exit status: 101)
  --- stderr
  [/home/g2p/.cargo/registry/src/github.com-1ecc6299db9ec823/deno_ffi-0.53.0/build.rs:29] &tcc_src = "/home/g2p/.cargo/registry/src/github.com-1ecc6299db9ec823/deno_ffi-0.53.0/tinycc"
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /home/g2p/.cargo/registry/src/github.com-1ecc6299db9ec823/deno_ffi-0.53.0/build.rs:34:37
  ```
  
Confirmed that https://crates.io/api/v1/crates/deno_ffi/0.53.0/download doesn't contain a tinycc folder.

**Comment by dsherret** [comment]
@littledivy do you think this might be because I published from Windows?

**Comment by littledivy** [comment]
@dsherret Did you have the submodule present? AFAIK there is no compile time conditional check to include/exlude a submodule.

**Comment by Eason0729** [comment]
I encountered the same problem.
In addition, I am using arm64 computer, so I usually install(update) it from cargo. How can I solve it?

[log.log](https://github.com/denoland/deno/files/9444724/log.log)

**Comment by g2p** [comment]
Workaround for now is to check out deno with submodules (git clone --recursive), copy the tinycc files into your crate cache, and resume installation

    cp -rt ~/.cargo/registry/src/github.com-1ecc6299db9ec823/deno_ffi-0.53.0/tinycc ext/ffi/tinycc/
    # See the last lines from the failed install for the exact temp directory
    CARGO_TARGET_DIR=/tmp/cargo-install… cargo install deno

**Comment by dsherret** [comment]
Yeah, looks like I didn't have the submodule. We should have it error in such a case.

**Comment by g2p** [comment]
I think it's worth automating, maybe by having `git submodule update --init` in your release script.
Also, have some kind of automated check that releases can be installed via cargo on supported platforms.

**Comment by dsherret** [comment]
It is automated in the release script. The automation just broke last week and had to be done manually which broke this. Anyway, should be resolved now.
