### ISSUE TITLE
segfault deserializing snapshot in tests

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#15590]
Seems like a segfault in v8 related to deserializing the snapshot.

![image](https://user-images.githubusercontent.com/1609021/186565819-7904545e-3c0f-4383-b43a-a69a2bc5a9ae.png)

```
error: test failed, to rerun pass '-p deno_runtime --lib'

Caused by:
  process didn't exit successfully: `C:\actions-runner\work\deno\deno\target\release\deps\deno_runtime-413c758822cbc9f4.exe` (exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)
```

https://github.com/denoland/deno/runs/7941098188?check_suite_focus=true

**Comment by littledivy** [comment]
https://github.com/denoland/deno/pull/15527 might fix it - we can get rid of ObjectTemplates.

**Comment by dsherret** [comment]
It seems to happen a lot:

https://github.com/denoland/deno/actions/runs/3046346801/jobs/4909043911

**Comment by dsherret** [comment]
Let's close this one and re-open if it happens again. Maybe fixed by #15527.

**Comment by dsherret** [comment]
This is still occurring https://github.com/denoland/deno/actions/runs/3106872198/jobs/5034292262

**Comment by dsherret** [comment]
Still failing https://github.com/denoland/deno/actions/runs/3322425538/jobs/5491428487 (and there have been others, of course)

**Comment by dsherret** [comment]
Still failing https://github.com/denoland/deno/actions/runs/3903822790/jobs/6668730830

**Comment by bartlomieju** [comment]
@piscisaureus and I will look into it next week

**Comment by aapoalas** [comment]
Still failing: https://github.com/denoland/deno/actions/runs/4157500019/jobs/7192035069

**Comment by dsherret** [comment]
I get this constantly locally now (same segfault when deserializing the snapshot). I need to run my tests with one thread to get it to work.

**Comment by dsherret** [comment]
This has gotten a lot worse recently.

**Comment by mmastrac** [comment]
I believe this was fixed by removing the cli_snapshot test which had some issues. @dsherret can we close this?
