### ISSUE TITLE
Deno compile results in panic

### ISSUE THREAD

**Issue by Gers2017** [denoland/deno#15612]
### Description
Working on a deno cli, using the **flags** module from the standard library.
The following commands fail:
- `deno compile main.ts`
- `deno compile --allow-read main.ts`
- `deno compile -A main.ts`

```sh
$ deno --version                                                                                                                                                              

deno 1.25.0 (release, x86_64-unknown-linux-gnu)
v8 10.6.194.5
typescript 4.7.4
```
### Deno compile output
```sh
$ export RUST_BACKTRACE=full; deno compile --allow-read main.ts

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 1.25.0
Args: ["deno", "compile", "--allow-read", "main.ts"]

thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /build/.cargo/registry/src/github.com-1ecc6299db9ec823/eszip-0.25.0/src/v2.rs:512:60
stack backtrace:
   0:     0x55ac4008a490 - <unknown>
   1:     0x55ac3f629bfc - <unknown>
   2:     0x55ac4005a570 - <unknown>
   3:     0x55ac4008cb05 - <unknown>
   4:     0x55ac4008c7cc - <unknown>
   5:     0x55ac3f5ba4aa - <unknown>
   6:     0x55ac4008d6cc - <unknown>
   7:     0x55ac4008d4eb - <unknown>
   8:     0x55ac4008d486 - <unknown>
   9:     0x55ac4008d442 - <unknown>
  10:     0x55ac3f1df142 - <unknown>
  11:     0x55ac3f1df23c - <unknown>
  12:     0x55ac3fe1cc24 - <unknown>
  13:     0x55ac3f58a540 - <unknown>
  14:     0x55ac3f588b5b - <unknown>
  15:     0x55ac3f26d0b2 - <unknown>
  16:     0x55ac3f2614a8 - <unknown>
  17:     0x55ac3f25ea56 - <unknown>
  18:     0x55ac3f25df76 - <unknown>
  19:     0x55ac3f25d67b - <unknown>
  20:     0x55ac3f25daa2 - <unknown>
  21:     0x7fa90dde12d0 - <unknown>
  22:     0x7fa90dde138a - __libc_start_main
  23:     0x55ac3f224ed5 - <unknown>
  24:                0x0 - <unknown>
```

**Comment by Gers2017** [comment]
Adding the [main.ts file](https://raw.githubusercontent.com/Gers2017/iansays/main/main.ts) for debugging purposes

**Comment by Gers2017** [comment]
After some testing I can confirm that Deno compile works on `Deno 1.24.3` but not in `Deno 1.25.0`

I think this [commit](https://github.com/denoland/eszip/commit/bba2a940e095a72630b551085b0efe735930df99#diff-ff42aba765ab96f68cb209933964efa01404f135126af4e1cfe45d5e7c1fd0e9R512) has to do with this issue.

**Comment by albnnc** [comment]
Can confirm this for

```
deno 1.25.0 (release, aarch64-apple-darwin)
v8 10.6.194.5
typescript 4.7.4
```

The backtrace is the same.

**Comment by kitsonk** [comment]
Ping @dsherret some strange interaction with sources, the graph and eszip.

**Comment by shevernitskiy** [comment]
Confirm compile issue. 1.24.3 works fine, 1.25.0 fails with the same output

**Comment by yaroslavkrutiak** [comment]
Same issue but it would be useful to leave the code that fails

```
$ deno --version
deno 1.25.0 (release, x86_64-unknown-linux-gnu)
v8 10.6.194.5
typescript 4.7.4
```

OS: 
```
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy
```


`index.js`:

```
#!/usr/bin/env -S deno run --allow-env --allow-read --allow-net
import figlet from 'https://x.nest.land/deno-figlet@0.0.5/mod.js'
import chalk from 'https://deno.land/x/chalk_deno@v4.1.1-deno/source/index.js'

const rawText = await Deno.readTextFile("./config.json");
const config = JSON.parse(rawText);

while (true) {
    const p = new Promise(resolve => setTimeout(()=> {console.clear(); resolve()}, 1000));

    await p
    console.log('ubuntu 22.04 is sad')
}
```

$`RUST_BACKTRACE=full`

$`deno compile index.js`

<details>
<summary>Output</summary>
<pre>
============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 1.25.0
Args: ["deno", "compile", "./index.js"]

thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/eszip-0.25.0/src/v2.rs:512:60
stack backtrace:
   0:     0x55dbde4de3bd - std::backtrace_rs::backtrace::libunwind::trace::h8217d0a8f3fd2f41
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55dbde4de3bd - std::backtrace_rs::backtrace::trace_unsynchronized::h308103876b3af410
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55dbde4de3bd - std::sys_common::backtrace::_print_fmt::hc208018c6153605e
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x55dbde4de3bd - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf89a7ed694dfb585
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x55dbde50949c - core::fmt::write::h21038c1382fe4264
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/fmt/mod.rs:1197:17
   5:     0x55dbde4d5981 - std::io::Write::write_fmt::h7dbb1c9a3c254aef
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/io/mod.rs:1672:15
   6:     0x55dbde4e00c5 - std::sys_common::backtrace::_print::h4e8889719c9ddeb8
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x55dbde4e00c5 - std::sys_common::backtrace::print::h1506fe2cb3022667
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x55dbde4e00c5 - std::panicking::default_hook::{{closure}}::hd9d7ce2a8a782440
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:295:22
   9:     0x55dbde4dfde6 - std::panicking::default_hook::h5b16ec25444b1b5d
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:314:9
  10:     0x55dbde85aed4 - deno::setup_panic_hook::{{closure}}::h341d5a693a381a24
  11:     0x55dbde4e076a - std::panicking::rust_panic_with_hook::hb0138cb6e6fea3e4
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:702:17
  12:     0x55dbde4e0569 - std::panicking::begin_panic_handler::{{closure}}::h4cb67095557cd1aa
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:586:13
  13:     0x55dbde4de874 - std::sys_common::backtrace::__rust_end_short_backtrace::h2bfcac279dcdc911
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:138:18
  14:     0x55dbde4e02d9 - rust_begin_unwind
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
  15:     0x55dbde5068e3 - core::panicking::panic_fmt::h1de71520faaa17d3
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
  16:     0x55dbde50672d - core::panicking::panic::h467ee1bf554babeb
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:48:5
  17:     0x55dbde9b79c5 - eszip::v2::EszipV2::from_graph::visit_module::hf8cde778538d759c
  18:     0x55dbde9b7922 - eszip::v2::EszipV2::from_graph::visit_module::hf8cde778538d759c
  19:     0x55dbde9b7922 - eszip::v2::EszipV2::from_graph::visit_module::hf8cde778538d759c
  20:     0x55dbde9b7922 - eszip::v2::EszipV2::from_graph::visit_module::hf8cde778538d759c
  21:     0x55dbde9b7922 - eszip::v2::EszipV2::from_graph::visit_module::hf8cde778538d759c
  22:     0x55dbde9b7100 - eszip::v2::EszipV2::from_graph::h6f0b31198b05afbe
  23:     0x55dbde84db18 - deno::compile_command::{{closure}}::hfc19cadbb984a73a
  24:     0x55dbde6f345a - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::ha891be8286511a5f
  25:     0x55dbde85e1db - deno::main::{{closure}}::h31e232cb60ae3fda
  26:     0x55dbde6d252f - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h6f5ae49f0f985a84
  27:     0x55dbde53809f - deno_runtime::tokio_util::run_local::hf92ebef368c4d8de
  28:     0x55dbde85b0f9 - deno::main::h3e6f490f5e940ede
  29:     0x55dbde56cb5d - std::sys_common::backtrace::__rust_begin_short_backtrace::hf665e2180d8d8a39
  30:     0x55dbde570a4b - std::rt::lang_start::{{closure}}::hc15c712b31ddab75
  31:     0x55dbde4cba9e - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h4937aaa125c8d4b2
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/ops/function.rs:280:13
  32:     0x55dbde4cba9e - std::panicking::try::do_call::h6f5c70e8b0a34f92
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:492:40
  33:     0x55dbde4cba9e - std::panicking::try::h68766ba264ecf2e2
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:456:19
  34:     0x55dbde4cba9e - std::panic::catch_unwind::hc36033d2f9cc04af
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panic.rs:137:14
  35:     0x55dbde4cba9e - std::rt::lang_start_internal::{{closure}}::h78c037f4a1a28ded
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/rt.rs:128:48
  36:     0x55dbde4cba9e - std::panicking::try::do_call::he6e1fffda4c750ee
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:492:40
  37:     0x55dbde4cba9e - std::panicking::try::h48a77ddbb2f4c87a
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:456:19
  38:     0x55dbde4cba9e - std::panic::catch_unwind::hfa809b06a550a9e7
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panic.rs:137:14
  39:     0x55dbde4cba9e - std::rt::lang_start_internal::h4db69ed48eaca005
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/rt.rs:128:20
  40:     0x55dbde874182 - main
  41:     0x7fad78f99d90 - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  42:     0x7fad78f99e40 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:392:3
  43:     0x55dbdd4c8029 - _start
  44:                0x0 - <unknown>
</pre>
</details>

**Comment by dsherret** [comment]
The bug is that the analyzer used to create the graph should not use the module analysis cache so that the source files get created. I have a fix, but I ran out of time and need to go somewhere so I will fix this tomorrow.
