### ISSUE TITLE
Stuck unresolved promises in WebSocketStream preventing it from ever aborting / closing

### ISSUE THREAD

**Issue by israelidanny** [denoland/deno#15616]
It seems that WebSocketStream refuses to close / abort if there are pending incoming messages from a server. The `closed` promise will never resolve.

I have created a minimal example, tested on deno v1.25.0.

To replicate, simply create a `server.ts` and `client.ts` with the following contents.
1. Run the command provided below for `server.ts`
2. Then run `client.ts`

### client.ts
```bash
deno run --allow-all --unstable client.ts
```
Will produce the following output:
```
received #1 Counter: 1
received #2 Counter: 2
error: Module evaluation is still pending but there are no pending ops or dynamic imports. This situation is often caused by unresolved promises.
```

```typescript
const url = "ws://127.0.0.1:8080";

// this is optional
const abortController = new AbortController();
const wss = new WebSocketStream(url, { signal: abortController.signal });

const { readable } = await wss.connection;
const reader = readable.getReader();

// we only consume two events from the reader asynchronously
(async () => {
  console.log(`received #1 ${(await reader.read())?.value}`);
  console.log(`received #2 ${(await reader.read())?.value}`);
})();

// we wait a few seconds, allowing the server to create some more events
await new Promise((resolve) => setTimeout(resolve, 3000));

wss.close({ code: 1000 });
// the result is same, abort controller or not. I just put it here to try to show that even abort doesn't work :) 
abortController.abort(); 
await wss.closed; // this will never resolve

// unreachable code
console.log("everything is done");
```

### server.ts
```bash
deno run --allow-all server.ts
```
```typescript
import { serve } from "https://deno.land/std@0.153.0/http/server.ts";

const port = 8080;

// this is a simple server that starts sending a counter every 250ms to any client that connects to it via websockets
await serve(
  (req: Request) => {
    if (req.headers.get("upgrade") != "websocket") {
      return new Response(null, { status: 501 });
    }

    const { socket, response } = Deno.upgradeWebSocket(req);
    let counter = 1;

    console.log(`Client connected`);

    const interval = setInterval(() => {
      socket.send(`Counter: ${counter++}`);
    }, 250);

    socket.onclose = () => {
      clearInterval(interval);
      console.log(`Client disconnected`);
    };

    return response;
  },
  {
    port,
    onListen: () => {
      console.log(`Server listening on ${port}`);
    },
    onError: (e: unknown) => {
      console.error("Server error", e);
      return new Response(
        JSON.stringify({ message: "Server error" }),
        { status: 500 },
      );
    },
  },
);

```

**Comment by crowlKats** [comment]
to clarify, that `abort` option isnt meant for closing the connection, it only works before the connection is established. as per one of the spec documents:

> This is specifically intended to make it easy to implement connection timeouts. As such, it does nothing after the connection is established.

**Comment by israelidanny** [comment]
@crowlKats makes sense. But with or without it, the bug remains. `close()` is supposed to terminate any promises and cleanly wrap everything up, yes?

**Comment by crowlKats** [comment]
Yes, that is correct.

**Comment by israelidanny** [comment]
By the way @crowlKats , where is that quote from? 

[The web.dev documentation](https://web.dev/websocketstream/#closing-a-websocketstream-connection) seems to directly contradict it

**Comment by crowlKats** [comment]
@israelidanny https://docs.google.com/document/d/1La1ehXw76HP6n1uUeks-WJGFgAnpX2tCjKts7QFJ57Y/edit#heading=h.1rnaapkkf160

**Comment by israelidanny** [comment]
So, from a quick debug session what I noticed is that the whole closing mechanism depends on `op_ws_close` sending a message to the ReadableStream:
https://github.com/denoland/deno/blob/main/ext/websocket/lib.rs#L443

We then only actually `tryClose()` if we reached this message in `pull()`, however if there is one other pending pulled message, this will never happen and we won't ever `pull()`:
https://github.com/denoland/deno/blob/main/ext/websocket/02_websocketstream.js#L236

Right here, we only resolve close if there was an error:
https://github.com/denoland/deno/blob/main/ext/websocket/02_websocketstream.js#L372

**Comment by israelidanny** [comment]
Should't then this:
https://github.com/denoland/deno/blob/main/ext/websocket/02_websocketstream.js#L372

Be more like:
```javascript
        PromisePrototypeThen(
          core.opAsync("op_ws_close", this[_rid], code, closeInfo.reason),
          () => {
            this[_rid] && core.tryClose(this[_rid]);
            this[_closed].resolve(closeInfo);
          },
          (err) => {
            this[_rid] && core.tryClose(this[_rid]);
            this[_closed].reject(err);
          },
        );
```

**Comment by crowlKats** [comment]
closing is a handshake: you send a close and receive a close, and only then can it be considered closed. considering it closed before receiving a close frame is wrong

**Comment by israelidanny** [comment]
In that case we would want to fast forward pull() until we see the close? Assuming `op_ws_close` didn't error out, we should have relatively high confidence that we will reach it.

**Comment by israelidanny** [comment]
@crowlKats would you mind reviewing this? 
https://github.com/denoland/deno/pull/15632

I will add tests if you think this makes sense and they're required.
