### ISSUE TITLE
npm URL throws: `Identifier '__esModule' has already been declared`

### ISSUE THREAD

**Issue by GJZwiers** [denoland/deno#15618]
Happens with e.g. `redis` and `random`:

`import { createClient } from 'npm:redis';`

`import random from 'npm:random'`

```
deno run --unstable -A main.js
   
error: Uncaught SyntaxError: Identifier '__esModule' has already been declared
    at <anonymous> (file:///C:/Users/GJZwiers/AppData/Local/deno/npm/registry.npmjs.org/random/3.0.6/dist/cjs/index.js:8:14)
```

```
deno --version

deno 1.25.0+da10c9c (canary, x86_64-pc-windows-msvc)
v8 10.6.194.5
typescript 4.7.4
```

**Comment by vladfrangu** [comment]
We've also encountered a similar issue by importing Buffer from node:buffer, process from node:process and the clear/set methods from node:timers! I don't know if its the same issue or a separate one but thought I'd let you know!

**Comment by dsherret** [comment]
@vladfrangu that's fixed already. Will be in the next release. See #15604.
