### ISSUE TITLE
`npm:node-fetch@2` doesn't work because of missing `global.Promise`

### ISSUE THREAD

**Issue by kt3k** [denoland/deno#15617]
The following script fails with `Uncaught Error: native promise missing, set fetch.Promise to your favorite alternative`

```ts
import fetch from "npm:node-fetch@2.6.7";
await fetch("https://example.com");
```

It seems caused by missing `global.Promise` object. If I modify the line below (in downloaded node-fetch source):

```js
fetch.Promise = global.Promise;
```
to
```js
fetch.Promise = globalThis.Promise;
```
then it works.

**Comment by bartlomieju** [comment]
Similarly for `prisma`

```
Error: native promise missing, set fetch.Promise to your favorite alternative
```
