### ISSUE TITLE
optimize read/write perms check

### ISSUE THREAD

**Issue by littledivy** [denoland/deno#15627]
![image](https://user-images.githubusercontent.com/34997667/186949202-2b54151a-bcb0-477b-892e-71deedeaed71.png)

In the file server benchmark, about ~5% of time is spent in the `--allow-read` check.

**Comment by bartlomieju** [comment]
As an additional data point - throwing PermissionDenied is very expensive

**Comment by littledivy** [comment]
Some initial observations:

* Redundant allocation even when we don't need to prompt. https://github.com/denoland/deno/blob/9b324b1cf4a8ee4159abb041e72a8885a28e92a3/runtime/permissions.rs#L374-L376

* 2 calls to `resolved_and_display_path` and reallocation of `PathBuf`. https://github.com/denoland/deno/blob/9b324b1cf4a8ee4159abb041e72a8885a28e92a3/runtime/permissions.rs#L371

**Comment by lucacasonato** [comment]
After David's last changes, the permission checks should be mostly imperceptible with `--allow-all`.
