### ISSUE TITLE
Deno.serve usage should be made fully unstable.

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#15637]
Minor thing.

When using npm:imports, I noticed 1.25 prints an error asking the user to run with --unstable flag.

The same doesn't happen for Deno.serve(), but it only works behind the unstable flag. Instead just throws, "Deno.serve is not a function".

_Originally posted by @st0le in https://github.com/denoland/deno/issues/15551#issuecomment-1228735370_

**Comment by bartlomieju** [comment]
I'm not sure what else is to do here? We got checks for missing TS props, using this API requires `--unstable`. I don't think we do anything else for other unstable APIs.

**Comment by kitsonk** [comment]
Sorry, I thought it was omitted from `UNSTABLE_DENO_PROPS` but it isn't.

@st0le you are getting a runtime error which is appropriate.  If you were to type check the code, it would inform you that you have to use `--unstable`.
