### ISSUE TITLE
It's been a good run boys and gals

### ISSUE THREAD

**Issue by imjamesb** [denoland/deno#15641]
I wanna give a big thank you to all of the Deno community, a thank for you the 3 years I have been able to be a part of this fun community! I also want to thank all of the contributors who's made Deno stand out compared to Node and Bun, it's been a good run. Unfortunately it seems that the core team has shifted its focus for Deno towards Node, which in my own opinion is very disappointing. I always thought Deno was special because it challenged one of the most used and liked projects in the world, specifically Node. Almost every single developer has heard of Node, now almost every developer has heard of Deno, they've maybe not thought of using it in big productions or for anything at all but most have heard of it. That's an achievement.

I am announcing my leave from the Deno community due to coming changes to the runtime. I know no one probably cares about this and a lot of people will disagree with my opinions, I hold nothing against that. But I will say this, Deno has been my go to ever since 0.18.0. It's going to be difficult to find something else that will be even half as useful as Deno has been. It's been a hell of a run guys.

Now let me have it, all the "this isn't an airport" memes!

**Comment by dsherret** [comment]
Sorry you feel that way, but the npm support is experimental and unstable. It's also not required as the npm specifiers offer a portal into the npm ecosystem. You don't have to use it if you don't want to, but these portals into the npm ecosystem will open a lot of doors for developers. Anyway, locking as this is off topic.
