### ISSUE TITLE
the import path cannot end with'. ts'extension

### ISSUE THREAD

**Issue by iwe7** [denoland/deno#1564]
Hello, everyone. I am a new denoer. When I use import to load something, vscode often reminds me that ` @the import path cannot end with'. ts'extension'. I don't know how you can solve it.

大家好，我是一个deno新人，当我使用import加载一些东西时，vscode经常提示`导入路径不能以“.ts”扩展名结束`,不知道你们怎么解决的。

**Comment by kevinkassimo** [comment]
@iwe7 Hey. So @kitsonk has created [deno_ls_plugin](https://github.com/kitsonk/deno_ls_plugin) which you might want to take a look.

(This issue reminds me that I should probably also establish a Chinese deno community. 这个issue倒是提醒了我或许应该创建一个deno的中文社区）

**Comment by iwe7** [comment]
A headache
```ts
import { some } from "/mod.ts";
[ts] declared "some" but never read its value. [6133]
[ts] 已声明“some”，但从未读取其值。 [6133]
[ts] The import path cannot end with the ".ts" extension. Consider importing "/ mod". [2691]
[ts] 导入路径不能以“.ts”扩展名结束。考虑改为导入“/mod”。 [2691]
```

**Comment by iwe7** [comment]
When I changed the document to
```
import { some } from "/mod";
```
deno ./index.ts

Compiling /Volumes/meepo/ims-deno/index.ts
NotFound: Cannot resolve module "./mode" from "/Volumes/meepo/ims-deno/index.ts"

**Comment by iwe7** [comment]
我按照您说的方法测试了一下，不起作用，感觉是deno内部系统的模块解析后缀名处理问题，类似webpack里默认后缀名，deno应该是没有默认的

I tested it according to what you said. It doesn't work. It feels like module parsing suffix name processing in deno internal system. Like default extension name in webpack, deno should not have default extension name.

**Comment by monkingxue** [comment]
@iwe7 I agree with U and we will make Chinese starter documentation. And you can join wechat group  to get more information. 
![wechatimg30](https://user-images.githubusercontent.com/16385790/51577259-2e59c780-1ef4-11e9-893f-d418eefcde0f.jpeg)

**Comment by iwe7** [comment]
非常感谢大家的帮助，在大家的帮助下，我已经把这个问题解决了，并只做了一个vscode中的deno starter

Thank you very much for your help. With your help, I have solved this problem and only made a  starter in vscode.

[deno-starter](https://github.com/iwe7/deno-starter)

**Comment by kitsonk** [comment]
@iwe7 there are a few things you are missing, feel free to adapt any of this into Chinese as well: [deno_example](https://github.com/kitsonk/deno_example) and I wrote up an blog post about it and why things are the way they are: https://medium.com/@kitsonk/develop-with-deno-and-visual-studio-code-225ce7c5b1ba and would have no problem someone translating it to Chinese.

**Comment by iwe7** [comment]
@kitsonk Thanks very much

**Comment by bartlomieju** [comment]
@iwe7 can this issue be closed?

**Comment by bartlomieju** [comment]
CC @ry this is stale

**Comment by runnerSnail** [comment]
> @kitsonk Thanks very much

微信群请拉一下我 谢啦

**Comment by runnerSnail** [comment]
> 非常感谢大家的帮助，在大家的帮助下，我已经把这个问题解决了，并只做了一个vscode中的deno starter
> 
> Thank you very much for your help. With your help, I have solved this problem and only made a starter in vscode.
> 
> [deno-starter](https://github.com/iwe7/deno-starter)
微信群拉一下我，谢啦哈
