### ISSUE TITLE
deno npm node less confuse

### ISSUE THREAD

**Issue by elycheikhsmail** [denoland/deno#15647]
Deno npm support suggestions
for deno community better understand npm support by deno runtime i suggest:
1- add npm subcommand which is similar to npm with certain exceptions in particular does not create the node_modules folder but hides the imported mdolules/packages, as described in the article https://deno.com/blog/v1.25
2- add a node subcommand that tells deno cli to "prepare" to run a file (js module) written for node first.
Let's imagine we have an example.js file:
```
// example.js
import express from "express";
// I don't write 'npm:express' will explain why later
const app = express();

app. get("/", function (req, res) {
  res.send("Hello World");
});

app. listen(3000);
console.log("listening on http://localhost:3000/");

```

the command :
```
deno node example.js

```
will do the following things
 
 2-a) treat all imports as if they are prefixed by npm because there is no risk of confusion, the node subcommand confirms that the js code that we want to execute is written first for node
2-b) download and cache the latest version of express from npm registry (without creating node_modules)
2-c) inject node api needed
2-d) execute the code
as you can see this approach will allow you to launch some js project written for node first with the deno runtime without any change in the existing code, which is wonderful.
3- add the npm_analyse subcommand which downloads the pkgs listed in the packages.json file in the current folder then say if they are supported in deno, in the case there is one or more pkgs which are not supported, we display the name of the pkg followed by node api used in this package and which are not supported by deno (std/node).

4- for later

**Comment by kitsonk** [comment]
This is unactionable in its current form. Thanks for the feedback, but keeping this issue open will serve no purpose. The experimental support has its own design.
