### ISSUE TITLE
Deno formatter can break a switch's previously satisfied `no-fallthrough` linter rule

### ISSUE THREAD

**Issue by Quezler** [denoland/deno#15669]
```
$ deno --version
> deno 1.24.3 (release, aarch64-apple-darwin)
> v8 10.4.132.20
> typescript 4.7.4
```

given this source, `deno lint --rules-include="no-fallthrough"` wants you to mark each line (or file) as fallthrough allowed:
```
const unit = 's';
let seconds = 10;

switch (unit) {
  case 'd': seconds *= 24;
  case 'h': seconds *= 60;
  case 'm': seconds *= 60;
}
```

adding this (instead of the longer `deno-lint-ignore no-fallthrough`) conveniently shuts it up:
```
const unit = 's';
let seconds = 10;

switch (unit) {
  case 'd': seconds *= 24; // fallthrough
  case 'h': seconds *= 60; // fallthrough
  case 'm': seconds *= 60; // fallthrough
}
```

but when you then run `deno fmt` the comments stay on the case's line:
```
const unit = "s";
let seconds = 10;

switch (unit) {
  case "d": // fallthrough
    seconds *= 24;
  case "h": // fallthrough
    seconds *= 60;
  case "m": // fallthrough
    seconds *= 60;
}
```

which in turn results in the `no-fallthrough` rule to fail (since it expects it to be on the last line before a new case starts)

**Comment by dsherret** [comment]
Thanks for reporting this. For now, just add a `// deno-fmt-ignore` above the switch statement.
