### ISSUE TITLE
allow import map to be a javascript file

### ISSUE THREAD

**Issue by masx200** [denoland/deno#15679]
allow import map to be a javascript file

**Comment by masx200** [comment]
https://deno.land/manual@v1.25.0/linking_to_external_code/import_maps

**Comment by masx200** [comment]
https://github.com/WICG/import-maps/issues/235

**Comment by masx200** [comment]
Since import maps not support importing external.
If project a depends on project b, and both projects a and b use import maps, it will be troublesome to merge import maps.

**Comment by kitsonk** [comment]
We won't deviate from the specification.  The specification dictates they are JSON files. If the spec changes, we will align to the changed spec.

Respectfully declined.
