### ISSUE TITLE
Importing https://esm.sh/react-dom@17.0.2 hangs Deno

### ISSUE THREAD

**Issue by jaydenseric** [denoland/deno#15683]
With Deno v1.25.0, and this `demo.mjs` file:

```js
import "https://esm.sh/react-dom@17.0.2";

console.log("here");
```

Run:

```sh
deno run demo.mjs
```

And the terminal output is:

```
This browser doesn't support requestAnimationFrame. Make sure that you load a polyfill in older browsers. https://reactjs.org/link/react-polyfills
This browser doesn't support cancelAnimationFrame. Make sure that you load a polyfill in older browsers. https://reactjs.org/link/react-polyfills
here
```

But the process hangs forever and doesn't exit. I can't figure out why; it seems to be a Deno bug.

**Comment by kitsonk** [comment]
Why do you think this is a Deno issue and not an issue with `react-dom` not holding open some resource or leaving a hanging promise, meaning it won't exit?

Module evaluation completed, otherwise you would not have logged `"here"`.

**Comment by deckchairlabs** [comment]
```ts
import * as ReactDOM from "https://esm.sh/react-dom@17.0.2";

console.log("here");
```

This works, why are you importing the file like that?

**Comment by 0f-0b** [comment]
Here is a minimal reproduction:

```js
new MessageChannel().port1.onmessage = () => {};
```

**Comment by 0f-0b** [comment]
Here is a minimal reproduction:

```js
new MessageChannel().port1.onmessage = () => {};
```

**Comment by kitsonk** [comment]
> Here is a minimal reproduction:
> 
> ```js
> new MessageChannel().port1.onmessage = () => {};
> ```

Opening a message channel and not closing it prevents Deno from exiting. This is expected.

**Comment by jaydenseric** [comment]
@kitsonk

> Why do you think this is a Deno issue and not an issue with `react-dom` not holding open some resource or leaving a hanging promise, meaning it won't exit?

Because that same version of `react-dom` didn't used to hang Deno; I'm not sure what changed. I would also find it surprising if `react-dom` indefinitely kept resources hanging just by importing it. Interestingly, importing `https://esm.sh/react-dom@18.2.0` doesn't cause Deno to hang.

I've also found that certain combinations of imports in a module seem to cause deno to hang, but commenting out random ones out seems to "fix" it. I've managed to find that particular `react-dom` import as described in the issue reliably reproduces the problem though.

I've experienced other Deno weirdness, which causes me to be skeptical when something strange like this happens:

https://github.com/denoland/deno/issues/15425

@deckchairlabs I just tried adding ` * as ReactDOM from` to the import and unsurprisingly it doesn't change the behavior, Deno still hangs, so I'm not sure why you say "This works".

@0f-0b there doesn't seem to be any occurrence of `Messagechannel` or `onmessage` in the code though:

https://esm.sh/v92/react-dom@17.0.2/es2021/react-dom.js

The context for why I would be importing `react-dom` which is intended for the client in Deno, is I have a test like this:

https://github.com/jaydenseric/ruck/blob/9f04bb5bf6a8c00cc1f4fba9778c5991f63dca4a/hydrate.test.mjs#L12-L24

Which uses this module:

https://github.com/jaydenseric/ruck/blob/9f04bb5bf6a8c00cc1f4fba9778c5991f63dca4a/hydrate.test.mjs#L9

Which in turn imports from `react-dom`, causing the problem:

https://github.com/jaydenseric/ruck/blob/9f04bb5bf6a8c00cc1f4fba9778c5991f63dca4a/hydrate.mjs#L6

**Comment by jaydenseric** [comment]
Is there a recommended technique or tool to debug why a Deno process doesn't exit, i.e. what code is causing that?

**Comment by deckchairlabs** [comment]
@jaydenseric esm.sh may have changed the compiled output? Without pinning the version that would be possible cause?
https://esm.sh/#:~:text=%23%20remove%20packages-,Pin%20the%20build%20version,-Since%20we%20update

**Comment by deckchairlabs** [comment]
@jaydenseric and I just ran the code sample you provided, with 1.25, and it worked... without that warning output, or hanging the Deno process, so not sure what your issue could to be honest.

**Comment by jaydenseric** [comment]
@deckchairlabs very strange that it works for you. My `deno --version`:

```
deno 1.25.0 (release, aarch64-apple-darwin)
v8 10.6.194.5
typescript 4.7.4
```

My system is macOS Monterey v12.5.1 (21G83), Apple M1 Max chip.

I've tried importing from `https://esm.sh/v87/react-dom@17.0.2/es2021/react-dom.js`, which I ***think*** is an old version that used to work, and it hangs Deno.

I've tried deleting the contents of my Deno dir, so it's not a Deno cache corruption issue or something like that.

**Comment by deckchairlabs** [comment]
@jaydenseric to be fair, I ran it as a TypeScript module, and that works. I used `.mjs` and `.js` extensions and the issue did occur, something weird going on there.

**Comment by deckchairlabs** [comment]
Those console warnings are coming from `https://esm.sh/v87/scheduler@0.20.2/es2021/scheduler.js` by the way

**Comment by deckchairlabs** [comment]
I'd recommend importing with `?target=deno` if you're running tests

**Comment by jaydenseric** [comment]
Wow, so if you do in `demo.ts`:

```ts
import * as ReactDOM from "https://esm.sh/v87/react-dom@17.0.2/es2021/react-dom.js";
```

And run `deno run demo.ts`, it doesn't hang.

But if in `demo.ts`:

```ts
import "https://esm.sh/v87/react-dom@17.0.2/es2021/react-dom.js";
```

And run `deno run demo.ts` exactly the same, it DOES hang. 100% this is some kind of Deno bug.

**Comment by deckchairlabs** [comment]
My guess it Deno is compiling away usage of window when it encounters a `.ts` file? I could be wrong, but that seems to be whats happening. If you use `import * as ReactDOM from "https://esm.sh/v87/react-dom@17.0.2/deno/react-dom.js";` do you have the same issue?

**Comment by jaydenseric** [comment]
In `demo.ts`:

```ts
import * as ReactDOM from "https://esm.sh/v87/react-dom@17.0.2/deno/react-dom.js";
```

Doesn't hang.

```ts
import "https://esm.sh/v87/react-dom@17.0.2/deno/react-dom.js";
```

Does hang.

**Comment by deckchairlabs** [comment]
Interesting, definitely something Deno is doing when emitting TypeScript to JavaScript.

`test.ts`
```ts
import * as ReactDOM from "https://esm.sh/v87/react-dom@17.0.2/es2021/react-dom.js";

console.log("here");
```

```sh
$ deno info test.ts
local: /test.ts
emit: /deno/.cache/deno/gen/file/test.ts.js
type: TypeScript
dependencies: 3 unique (total 132.56KB)

file:///test.ts (105B)
└─┬ https://esm.sh/v87/react-dom@17.0.2/deno/react-dom.js (118.21KB)
  ├── https://esm.sh/v87/react@17.0.2/deno/react.js (8.02KB)
  └── https://esm.sh/v87/scheduler@0.20.2/deno/scheduler.js (6.22KB
```

The ouput of the emit

```js
console.log("here");
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbImZpbGU6Ly8vd29ya3NwYWNlcy9idWlsZGVyL3Rlc3QudHMiXSwic291cmNlc0NvbnRlbnQiOlsiaW1wb3J0IFJlYWN0RE9NIGZyb20gXCJodHRwczovL2VzbS5zaC92ODcvcmVhY3QtZG9tQDE3LjAuMj90YXJnZXQ9ZGVub1wiO1xuXG5jb25zb2xlLmxvZyhcImhlcmVcIik7XG4iXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IkFBRUEsT0FBTyxDQUFDLEdBQUcsQ0FBQyxNQUFNLENBQUMsQ0FBQyJ9
```

Renaming the file to `test.js`

```sh
$ deno info test.js
local: /test.js
type: JavaScript
dependencies: 3 unique (total 132.57KB)

file:///test.js (107B)
└─┬ https://esm.sh/v87/react-dom@17.0.2/es2021/react-dom.js (118.22KB)
  ├── https://esm.sh/v87/react@17.0.2/es2021/react.js (8.02KB)
  └── https://esm.sh/v87/scheduler@0.20.2/es2021/scheduler.js (6.22KB)
```

Wouldn't produce any emitted output, so would run as is loaded from the remote source.

**Comment by deckchairlabs** [comment]
Removing the emitted file `/deno/.cache/deno/gen/file/test.ts.js` from the deno cache and re-running the `test.ts` case above produces no emitted file...

```sh
$ deno info -r test.ts
Download https://esm.sh/v87/react-dom@17.0.2/es2021/react-dom.js
Download https://esm.sh/v87/react@17.0.2/es2021/react.js
Download https://esm.sh/v87/scheduler@0.20.2/es2021/scheduler.js
local: /test.ts
type: TypeScript
dependencies: 3 unique (total 132.61KB)

file:///test.ts (145B)
└─┬ https://esm.sh/v87/react-dom@17.0.2/es2021/react-dom.js (118.22KB)
  ├── https://esm.sh/v87/react@17.0.2/es2021/react.js (8.02KB)
  └── https://esm.sh/v87/scheduler@0.20.2/es2021/scheduler.js (6.22KB)
```

**Comment by kitsonk** [comment]
A few things here, it isn't specifically Deno.  Both tsc and swc elide imports from TypeScript files that have no function purpose.  If you don't want the import elided, use:

```ts
import * as ReactDOM from "https://esm.sh/v87/react-dom@17.0.2/es2021/react-dom.js";

console.log(ReactDOM);
```

or use the side-effect import like the original case.

Second, as of Deno 1.25 we no longer maintain an emit cache and emit files as needed.  This is part of the performance improvement when dealing with TypeScript.  Counter intuitively, not caching is more performant we have found.

**Comment by deckchairlabs** [comment]
> A few things here, it isn't specifically Deno. Both tsc and swc elide imports from TypeScript files that have no function purpose. If you don't want the import elided, use:
> 
> ```ts
> import * as ReactDOM from "https://esm.sh/v87/react-dom@17.0.2/es2021/react-dom.js";
> 
> console.log(ReactDOM);
> ```
> 
> or use the side-effect import like the original case.
> 
> Second, as of Deno 1.25 we no longer maintain an emit cache and emit files as needed. This is part of the performance improvement when dealing with TypeScript. Counter intuitively, not caching is more performant we have found.

I see, but does it use the cached file if it exists?

**Comment by kitsonk** [comment]
> I see, but does it use the cached file if it exists?

As of 1.25, the gen cache is not used.

**Comment by jaydenseric** [comment]
This issue really needs to be triaged and investigated/resolved, my productivity is getting smashed here and I'm losing confidence in the Deno platform seeing more developer attention going to new features like `npm:` over investigating issues with the current runtime.

Importing these separately don't hang:

```js
import "https://deno.land/x/puppeteer@16.2.0/mod.ts";
```

**Comment by jaydenseric** [comment]
Sorry for the above comment submitting before it was fully written; edited it to completion. GitHub glitched and submitted it early for some reason.

**Comment by dsherret** [comment]
> As of 1.25, the gen cache is not used.

@kitsonk no, it's still used. It's just deno graph caches module analysis so parsing is no longer always necessary.

> Removing the emitted file /deno/.cache/deno/gen/file/test.ts.js from the deno cache and re-running the test.ts case above produces no emitted file...

@deckchairlabs it works fine for me. Are you sure you are running `deno cache <filename>` or `deno run <filename>`? `deno info` doesn't emit TypeScript files. If not, please open a reproducible bug outlining your steps. Also, this is not a TypeScript issue. If you `deno bundle <filename> > file.js` the behaviour still occurs.

> @0f-0b there doesn't seem to be any occurrence of Messagechannel or onmessage in the code though:

@jaydenseric the minimal reproduction that @0f-0b provided seems to be correct. Try doing `deno bundle <filename> > file.js` on the code and inspecting it. When I comment out the code:

```
, F.port1.onmessage = function() {
        if (w !== null) {
            var e = r.unstable_now();
            E = e + j;
            try {
                w(!0, e) ? P.postMessage(null) : (v = !1, w = null);
            } catch (n) {
                throw P.postMessage(null), n;
            }
        } else v = !1;
    }
```

...the hang no longer occurs. Overall, I don't believe this is an issue with Deno.

**Comment by jaydenseric** [comment]
@dsherret 

Thanks for looking into this.

> Also, Kitson is right that imports like `import * as something from "..."` will be removed in TS when not used. This is standard behaviour so you need to use the import for it to stay in the emitted code or remove the namespace part.

That might be how tsc works, but it is absolutely incorrect behavior for the Deno runtime to do that. How does Deno know if there were side effects you were counting on running in the imported module? A browser doesn't eliminate imports like that so neither should Deno.

What is the explanation for https://github.com/denoland/deno/issues/15683#issuecomment-1234973193 ?

**Comment by dsherret** [comment]
> That might be how tsc works, but it is absolutely incorrect behavior for the Deno runtime to do that.

Technically it's the correct behaviour because it was the chosen behaviour. There could be arguments made either way. Browsers don't transpile TypeScript.

> What is the explanation for https://github.com/denoland/deno/issues/15683#issuecomment-1234973193 ?

It hangs for me when importing `import "https://esm.sh/react-test-renderer@17.0.2?dev";` on its own. Seems like for the same reason.

**Comment by jaydenseric** [comment]
Something must be wrong or at least inconsistent with `deno test`, because I am definitely importing `https://esm.sh/react-test-renderer@17.0.2?dev` in my tests and it's not hanging:

<img width="850" alt="Screen Shot 2022-09-02 at 1 55 21 pm" src="https://user-images.githubusercontent.com/1754873/188056053-0e23573c-1b90-4007-a1c7-0aa2277aff46.png">

And I definitely experienced https://github.com/denoland/deno/issues/15683#issuecomment-1234973193 , it was in a `.test.` module so I'm not sure how to minimally reproduce it exactly yet.

**Comment by jaydenseric** [comment]
Minimal reproduction...

First:

```
deno run \
  --allow-env \
  --allow-net \
  --allow-read \
  --allow-write \
  https://deno.land/x/puppeteer@16.2.0/install.ts
```

Then, in `demo.mjs`:

```js
import "https://deno.land/x/puppeteer@16.2.0/mod.ts";
import "https://esm.sh/react-test-renderer@17.0.2?dev";
```

Run:

```
deno test --allow-env demo.mjs
```

Note that it hangs.

Then, try commenting out one:

```js
import "https://deno.land/x/puppeteer@16.2.0/mod.ts";
// import "https://esm.sh/react-test-renderer@17.0.2?dev";
```

Run again:

```
deno test --allow-env demo.mjs
```

It doesn't hang.

Comment out the other one:

```js
// import "https://deno.land/x/puppeteer@16.2.0/mod.ts";
import "https://esm.sh/react-test-renderer@17.0.2?dev";
```

It doesn't hang.

With the exact same module, just using `deno run` instead of `deno test`:

```
deno run --allow-env demo.mjs
```

It does hang. This inconsistency is what has confused the heck out of me, and I don't understand why they would behave differently.

**Comment by bartlomieju** [comment]
Dumping open resources shows:
```
┌───────┬───────────────┐
│ (idx) │ Values        │
├───────┼───────────────┤
│     0 │ "stdin"       │
│     1 │ "stdout"      │
│     2 │ "stderr"      │
│     3 │ "messagePort" │
│     4 │ "messagePort" │
└───────┴───────────────┘
```

Dumping never completed ops:
```
for (const [key, value] of Object.entries(Deno.metrics().ops)) {
    if (value.opsDispatched !== value.opsCompleted) {
        console.log("never resolved op", key);
    }
}
```

```
op_message_port_recv_message
``` 



It's an async op that never completes. Need to dig more why that's happening.

**Comment by ayame113** [comment]
The cause of the hang is line 575 of react/Scheduler.js.
https://github.com/facebook/react/blob/8ef3a7c08c55c13995267902859381da8b5985ac/packages/scheduler/src/forks/Scheduler.js#L575

The code I used to find this was:

```shell
> deno test -A --trace-ops ./test.ts
```

```ts
// test.ts
// const targetModule = "https://esm.sh/v87/react-dom@17.0.2/es2021/react-dom.js"
const targetModule = "https://esm.sh/react-test-renderer@17.0.2?dev";
Deno.test(async function test() {
  const mod = await import(targetModule);
  console.log(mod);
});
```

```
test => ./test.ts:3:6
error: AssertionError: Test case is leaking async ops.

 - 1 async operation to receive a message from a MessagePort was started in this test, but never completed. This is often caused by not awaiting the result of not closing a `MessagePort`. The operation was started here:
    at Object.opAsync (deno:core/01_core.js:170:42)
    at deno:ext/web/13_message_port.js:143:31
    at MessagePort.start (deno:ext/web/13_message_port.js:172:9)
    at deno:ext/web/13_message_port.js:185:10
    at MessagePort.set [as onmessage] (deno:ext/web/02_event.js:1407:17)
    at https://esm.sh/v92/scheduler@0.20.2/deno/scheduler.development.js:144:35
    at esm-build-172d5bc50cb5a1a5a351093d4366a49c8033ab50-e63be43f/node_modules/scheduler/cjs/scheduler.development.js (https://esm.sh/v92/scheduler@0.20.2/deno/scheduler.development.js:495:9)
    at __require (https://esm.sh/v92/scheduler@0.20.2/deno/scheduler.development.js:9:50)
    at esm-build-172d5bc50cb5a1a5a351093d4366a49c8033ab50-e63be43f/node_modules/scheduler/index.js (https://esm.sh/v92/scheduler@0.20.2/deno/scheduler.development.js:507:24)
    at __require (https://esm.sh/v92/scheduler@0.20.2/deno/scheduler.development.js:9:50)

    at assert (deno:ext/web/00_infra.js:295:13)
    at asyncOpSanitizer (deno:runtime/js/40_testing.js:224:13)
    at async resourceSanitizer (deno:runtime/js/40_testing.js:369:7)
    at async Object.exitSanitizer [as fn] (deno:runtime/js/40_testing.js:426:9)
    at async runTest (deno:runtime/js/40_testing.js:831:7)
    at async Object.runTests (deno:runtime/js/40_testing.js:1084:22)
```

To fix the hang issue, I think we just need to add one line at the beginning:
(I haven't tried it properly)

```ts
import "data:application/javascript,globalThis.MessageChannel = undefined"; // Add this line and everything should be fine
import "https://esm.sh/react-test-renderer@17.0.2?dev";
```

**Comment by bartlomieju** [comment]
One might argue that ops associated with "MessagePort" should be "unref" by default (ie. they don't keep event loop alive if there's no more work to be done).

**Comment by ayame113** [comment]
FYI, I had the same issue with firebase-js-sdk. (hangs because setTimeout keeps event loop)
https://github.com/firebase/firebase-js-sdk/pull/6560

That said, they shouldn't hang if the Node.js API is properly polyfilled. So it might be an easy workaround using the experimental npm specifier support.
