### ISSUE TITLE
Add pprof back

### ISSUE THREAD

**Issue by kevinkassimo** [denoland/deno#1569]
In #193 , pprof was added to profile the event loop.
This is gone after the Rust rewrite. Would be a nice thing to add back ([cpuprofiler](https://docs.rs/cpuprofiler/0.0.3/cpuprofiler/)).
(I'm having troubles adding this myself as I'm not quite familiar with build)

**Comment by ry** [comment]
Have you tried V8's profiler? 
https://github.com/denoland/deno/blob/master/Docs.md#how-to-profile-deno

**Comment by ry** [comment]
@kevinkassimo Ya - it may be the the "C++" profile that the V8 profiler provides is only what is happening on the V8 thread - and not in the tokio thread pool.

**Comment by kitsonk** [comment]
@kevinkassimo with the debugger support, is there more to do here specific to this issue?

**Comment by bartlomieju** [comment]
I think we can close this issue now. We can use flamegraps for profiling Rust code and inspector for JS code.
