### ISSUE TITLE
npm URL throws: `No such file or directory (os error 2)`

### ISSUE THREAD

**Issue by GJZwiers** [denoland/deno#15695]
Happens with e.g. `crypto-js`:

```js
import hmacSHA512 from 'npm:crypto-js/hmac-sha512';
```

```
deno run --unstable -A main.mjs

error: No such file or directory (os error 2)
```

Also with `core-js`:

```js
import group from 'npm:core-js-pure/actual/array/group';
```

```
deno --version

deno 1.25.0+79fe8ff (canary, x86_64-unknown-linux-gnu)
v8 10.6.194.5
typescript 4.7.4
```

Edit: This does work: `import hmacSHA512 from 'npm:crypto-js';`, though the package uses 'crypto-js/hmac-sha512'; in their docs. Not sure if this is an actual issue

**Comment by oq-x** [comment]
add the file extension

**Comment by bartlomieju** [comment]
Adding file extension might fix the problem at hand but we need to improve error message returned anyway.
