### ISSUE TITLE
[deno_webgpu] WebGPU GPUSupportedFeatures object doesn't include `has` method

### ISSUE THREAD

**Issue by haoyunfeix** [denoland/deno#15702]
Code:
```
const adapter = await navigator.gpu.requestAdapter();
const device = await adapter?.requestDevice();

console.log(device.features.has('timestamp-query'));
```
Output:
```
error: Uncaught (in promise) TypeError: device.features.has is not a function
console.log(device.features.has('timestamp-query'));
```
Expected output:
True or False

Due to  [WebGPU spec](https://www.w3.org/TR/webgpu/#gpu-supportedfeatures) and webidl spec, `device.features` is a [setlike](https://webidl.spec.whatwg.org/#dfn-set-entries) Object and should includes `has` method, but there is not.

**Comment by vicary** [comment]
Gently ping @crowlKats from #7977, is the current array implementation intentional?

**Comment by crowlKats** [comment]
No, this seems to be something that was missed in the implementation

**Comment by vicary** [comment]
I want to make my first PR, I'm really not sure what I'm doing.

https://github.com/denoland/deno/blob/a3df6bb344c97c13e7df3d89cb0aa52d6fa9d207/ext/webgpu/src/01_webgpu.js#L347-L348

Is it a simple change like this?

```diff
-        features: ObjectFreeze(features),
-        limits: ObjectFreeze(limits),
+        features: createGPUSupportedFeatures(features),
+        limits: createGPUSupportedFeatures(limits),
```
