### ISSUE TITLE
`deno compile`: `if(Map.has(x))` does not mark `Map.get(x)` as non-null

### ISSUE THREAD

**Issue by jasopolis** [denoland/deno#15722]
Apologies if this is marked incorrectly, this is my first issue here! I noticed that the Deno TypeScript compiler was not using a `Map.prototype.has()` "guard" to mark a subsequent `Map.prototype.get()` call with the same key as non-null (instead giving TS2532 Object is possibly 'undefined'). `tsc` doesn't do this, so this seemed like a bug in `deno compile`.

### Code Snippet

```ts
// reprex.ts
const myMap = new Map([
  [1, "one"],
  [2, "two"],
]);

if (myMap.has(1)) {
  myMap.set(1, myMap.get(1).toUpperCase());
} else {
  myMap.set(1, "ONE");
}
```

### Expected Result

(note, the `-t es6` flag is used to mark native Map support)
```bash
$ tsc -t es6 reprex.ts 
# [no error]
```

### Actual Result

```bash
$ deno compile reprex.ts
Check file:///[...]/reprex.ts
error: TS2532 [ERROR]: Object is possibly 'undefined'.
  myMap.set(1, myMap.get(1).toUpperCase());
               ~~~~~~~~~~~~
    at file:///[...]/reprex.ts
```

### Version
deno 1.25.0 (release, x86_64-unknown-linux-gnu)
v8 10.6.194.5
typescript 4.7.4

**Comment by kitsonk** [comment]
`tsc -t es6 reprex.ts` does not set strict mode to true, Deno interprets TypeScript in strict mode.

When [setting strict mode to `true`](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAtgTwLIEMAOMC8MwFMDuMqaAFANoBQMMZAjADQwBE4uTAuvVTQEyNNR8IDl3YBKANwUKASwBmMEomIA6ABYoIJWmLEwA3t2XoVEXFG2NjaFQHNz2sSqggAqmjS4ATgGFNuEl0pAF8YXAAbMwMjZBMzCwZmAHkAOQBRJkkKYIogA) TypeScript reports the same error (as well if you were to use `tsc -t es6 --strict reprex.ts`.

**Comment by jasopolis** [comment]
I see, thanks! Apologies for the false flag.
