### ISSUE TITLE
Are there any examples of setting up an http server like express?

### ISSUE THREAD

**Issue by alshdavid** [denoland/deno#1572]
Having difficulty finding code examples around

**Comment by sholladay** [comment]
I made [pogo](https://github.com/sholladay/pogo), a server framework for Deno. It is inspired by hapi, which IMO has a much better API than Express. It is a young project, but it works. If you need any help or more examples, ping me. Contributions welcome.

**Comment by ry** [comment]
@sholladay Nice! consider adding it to the registry https://github.com/denoland/registry/blob/master/src/database.json and https://github.com/denolib/awesome-deno so it's more discoverable.

**Comment by NMathar** [comment]
Another try https://github.com/NMathar/deno-express feel free to give some feedback

**Comment by bartlomieju** [comment]
CC @ry this is stale
