### ISSUE TITLE
Feature Request: Enable Third Party Subcommands

### ISSUE THREAD

**Issue by aunyks** [denoland/deno#15757]
Hi! I’d love to have the ability to create and install third party subcommands.

I’m imagining functionality like Git or Cargo, where if I have an executable `deno-foo` in my PATH, then running `deno foo —my —flags` will invoke `deno-foo` with `—my —flags` as arguments.

Does something like this already exist within Deno? If not, I’d love to help implement.

**Comment by aunyks** [comment]
@littledivy Is this request formatted properly?

**Comment by bartlomieju** [comment]
While this is an interesting feature request, there are many questions to answer on how this could be implemented. 

@aunyks could you provide some prior art how this feature is implemented in cargo?

**Comment by aunyks** [comment]
@bartlomieju Of course. Here’s some Cargo documentation on custom subcommands: https://doc.rust-lang.org/cargo/reference/external-tools.html#custom-subcommands. I couldn’t find official Git documentation for the same feature, but this article conveys the idea: https://www.atlassian.com/git/articles/extending-git.

**Comment by dsherret** [comment]
I think `deno install` covers the usecase of global commands? We also have `deno task` for repo-specific commands.

**Comment by kidonng** [comment]
If this is only for yourself, it shouldn't be too hard to write a shell function. Fish example:

```fish
function deno --argument-names command
    if command --query deno-$command
        deno-$command $argv[2..]
    else
        deno $argv
    end
end
```

**Comment by lucacasonato** [comment]
We are not going to do this.
