### ISSUE TITLE
`self` should be a getter

### ISSUE THREAD

**Issue by zloirock** [denoland/deno#15765]
But now it's a usual property.

https://html.spec.whatwg.org/multipage/window-object.html#dom-self

![image](https://user-images.githubusercontent.com/2213682/188333901-92b534ce-3d6f-4484-99b9-2ad8ebc76a1b.png)

Chromium:
![image](https://user-images.githubusercontent.com/2213682/188334029-7eaa5f44-4421-4e9a-b0d2-7e21c216b987.png)

Safari:
![image](https://user-images.githubusercontent.com/2213682/188334044-31957595-7400-48e7-920a-278560a0654c.png)

FF:
![image](https://user-images.githubusercontent.com/2213682/188333969-a6b19048-8983-4beb-9fcb-1d99fa0f19cd.png)

Deno:
![image](https://user-images.githubusercontent.com/2213682/188333997-2ab4a6d3-a7c2-40f6-a937-580bf8a758ab.png)

**Comment by kitsonk** [comment]
Is there a specific issue this is causing for you?

**Comment by zloirock** [comment]
@kitsonk sure, and it will cause problems for thousands of users.

`self` now is a part of [Minimum Common Web Platform API](https://common-min-api.proposal.wintercg.org/#index). I wanted to add a **proper** polyfill of this (not just `globalThis.self ??= globalThis`) to `core-js`. This polyfill contains a  proper descriptor detection and in case of incorrect descriptor overwrites incorrect implementation - like Deno. Babel and SWC inject `core-js` polyfills for unsupported features - by the `core-js` compat data - and for bundling / loading it's an extra couple of KB.

**Comment by kitsonk** [comment]
Yup, thanks, that makes a lot of sense.
