### ISSUE TITLE
main branch build fails

### ISSUE THREAD

**Issue by yanovich** [denoland/deno#15779]
`cargo build --locked` fails from a clean `HEAD`.
<details>
<summary>Logs</summary>
<pre><code>
$ git log -n1 --pretty=oneline --abbrev-commit 
264ad49e1 (HEAD -> main, origin/main, origin/HEAD) refactor: cleanup Node compatibility code (#15766)
$ cargo build --locked 
   Compiling cfg-if v1.0.0
   Compiling proc-macro2 v1.0.39
   Compiling unicode-ident v1.0.1
   Compiling syn v1.0.96
   Compiling libc v0.2.126
   Compiling version_check v0.9.4
   Compiling autocfg v1.1.0
   Compiling serde_derive v1.0.141
   Compiling once_cell v1.12.0
   Compiling smallvec v1.8.0
   Compiling memchr v2.5.0
   Compiling spin v0.5.2
   Compiling parking_lot_core v0.9.3
   Compiling scopeguard v1.1.0
   Compiling serde v1.0.141
   Compiling pin-project-lite v0.2.9
   Compiling bitflags v1.3.2
   Compiling itoa v1.0.2
   Compiling matches v0.1.9
   Compiling percent-encoding v2.1.0
   Compiling tinyvec_macros v0.1.0
   Compiling unicode-bidi v0.3.8
   Compiling ryu v1.0.10
   Compiling either v1.6.1
   Compiling regex-syntax v0.6.27
   Compiling bytes v1.2.1
   Compiling futures-core v0.3.21
   Compiling serde_json v1.0.82
   Compiling futures-sink v0.3.21
   Compiling futures-task v0.3.21
   Compiling futures-channel v0.3.21
   Compiling typenum v1.15.0
   Compiling futures-util v0.3.21
   Compiling futures-io v0.3.21
   Compiling slab v0.4.6
   Compiling pin-utils v0.1.0
   Compiling base64 v0.11.0
   Compiling if_chain v1.0.2
   Compiling ppv-lite86 v0.2.16
   Compiling anyhow v1.0.58
   Compiling fnv v1.0.7
   Compiling libm v0.2.2
   Compiling log v0.4.17
   Compiling convert_case v0.4.0
   Compiling subtle v2.4.1
   Compiling untrusted v0.7.1
   Compiling base64 v0.13.0
   Compiling rustc-hash v1.1.0
   Compiling cpufeatures v0.2.2
   Compiling unicode-width v0.1.9
   Compiling siphasher v0.3.10
   Compiling strsim v0.10.0
   Compiling rustls v0.20.6
   Compiling byteorder v1.4.3
   Compiling ident_case v1.0.1
   Compiling httparse v1.8.0
   Compiling zeroize v1.5.5
   Compiling new_debug_unreachable v1.0.4
   Compiling void v1.0.2
   Compiling precomputed-hash v0.1.1
   Compiling scoped-tls v1.0.0
   Compiling static_assertions v1.1.0
   Compiling crc32fast v1.3.2
   Compiling base64ct v1.5.0
   Compiling opaque-debug v0.3.0
   Compiling termcolor v1.1.3
   Compiling proc-macro-hack v0.5.19
   Compiling try-lock v0.2.3
   Compiling tower-service v0.3.1
   Compiling adler v1.0.2
   Compiling async-trait v0.1.56
   Compiling const-oid v0.9.0
   Compiling unicode-id v0.3.2
   Compiling httpdate v1.0.2
   Compiling encoding_rs v0.8.31
   Compiling alloc-no-stdlib v2.0.3
   Compiling openssl-probe v0.1.5
   Compiling ipnet v2.5.0
   Compiling utf-8 v0.7.6
   Compiling typed-arena v2.0.1
   Compiling base16ct v0.1.1
   Compiling bit-vec v0.6.3
   Compiling khronos-egl v4.1.0
   Compiling hexf-parse v0.2.1
   Compiling mime v0.3.16
   Compiling unicode-xid v0.2.3
   Compiling match_cfg v0.1.0
   Compiling ash v0.37.0+1.3.209
   Compiling pkg-config v0.3.25
   Compiling vcpkg v0.2.15
   Compiling heck v0.4.0
   Compiling proc-macro2 v0.4.30
   Compiling num-bigint-dig v0.8.1
   Compiling cty v0.2.2
   Compiling simd-abstraction v0.6.2
error[E0433]: failed to resolve: could not find `is_x86_feature_detected` in `arch`
 --> /home/s/.cargo/registry/src/github.com-1ecc6299db9ec823/simd-abstraction-0.6.2/src/arch/x86.rs:9:30
  |
9 | define_isa!(SSE41, "sse4.1", is_x86_feature_detected);
  |                              ^^^^^^^^^^^^^^^^^^^^^^^ could not find `is_x86_feature_detected` in `arch`

error[E0433]: failed to resolve: could not find `is_x86_feature_detected` in `arch`
  --> /home/s/.cargo/registry/src/github.com-1ecc6299db9ec823/simd-abstraction-0.6.2/src/arch/x86.rs:10:30
   |
10 | define_isa!(SSE42, "sse4.2", is_x86_feature_detected);
   |                              ^^^^^^^^^^^^^^^^^^^^^^^ could not find `is_x86_feature_detected` in `arch`

error[E0433]: failed to resolve: could not find `is_x86_feature_detected` in `arch`
  --> /home/s/.cargo/registry/src/github.com-1ecc6299db9ec823/simd-abstraction-0.6.2/src/arch/x86.rs:11:27
   |
11 | define_isa!(AVX2, "avx2", is_x86_feature_detected);
   |                           ^^^^^^^^^^^^^^^^^^^^^^^ could not find `is_x86_feature_detected` in `arch`

   Compiling fixedbitset v0.4.1
For more information about this error, try `rustc --explain E0433`.
error: could not compile `simd-abstraction` due to 3 previous errors
warning: build failed, waiting for other jobs to finish...
error: build failed
</code></pre>
</details>

Versions:
```
Linux host2 5.15.0-46-generic #49-Ubuntu SMP Thu Aug 4 18:03:25 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
rustc 1.59.0
cargo 1.59.0
```

**Comment by littledivy** [comment]
use rust 1.63.0 https://github.com/denoland/deno/blob/264ad49e18161a29cf8831dff2e4bcbcea59d086/rust-toolchain.toml#L2
