### ISSUE TITLE
[bug] Missing bytes in response when there is some non-ascii character (Deno.serve)

### ISSUE THREAD

**Issue by rsc1975** [denoland/deno#15781]
When the response body contains non ascii chars the output is cut, It seems that the content length is not correctly calculated.

```typescript
Deno.serve((_: Request): Response => {
 const body = JSON.stringify({"name": "Na Ūžien", "name2": "Ramón Sánchez"});
  return new Response(body, { status: 200 });
}, { port: 3003 });
```

In that example, if I call:

```
curl http://localhost:3003/
```

The output is: `{"name":"Na Ūžien","name2":"Ramón Sánch` instead of: `{"name":"Na Ūžien","name2":"Ramón Sánchez"}` The last 4 bytes are missing. There are 4 non-ascii chars, so It seems an encoding related issue.

This works fine with @std/http/server

**Comment by israelidanny** [comment]
This seems to be also causing bugs downstream with WebStorm:

**Comment by makovkins** [comment]
I tried it with different deno versions. It works properly in deno 1.12.1 and it looks like that it's broken in 1.12.2.

**Comment by rsc1975** [comment]
The `JSON.stringify()` is working fine (in that code), the problem is the response output generation.

```js
console.log(body); // Works fine, shows: '{"name":"Na Ūžien","name2":"Ramón Sánchez"}'
```

**Comment by makovkins** [comment]
Ok, that's fine but knowing that it's not JSON.Strngify() doesn't solve the actual problem :)
