### ISSUE TITLE
main branch build fails in tinycc

### ISSUE THREAD

**Issue by yanovich** [denoland/deno#15780]
`cargo build --locked` fails from a clean `HEAD`.
<details>
<summary>Logs</summary>
<pre><code>
$ git log -n1 --pretty=oneline --abbrev-commit 
264ad49e1 (HEAD -> main, origin/main, origin/HEAD) refactor: cleanup Node compatibility code (#15766)
$ cargo build --locked 
   Compiling cfg-if v1.0.0
   Compiling proc-macro2 v1.0.39
   Compiling unicode-ident v1.0.1
   Compiling syn v1.0.96
   Compiling libc v0.2.126
   Compiling version_check v0.9.4
   Compiling autocfg v1.1.0
   Compiling serde_derive v1.0.141
   Compiling once_cell v1.12.0
   Compiling smallvec v1.8.0
   Compiling memchr v2.5.0
   Compiling spin v0.5.2
   Compiling parking_lot_core v0.9.3
   Compiling scopeguard v1.1.0
   Compiling serde v1.0.141
   Compiling pin-project-lite v0.2.9
   Compiling bitflags v1.3.2
   Compiling itoa v1.0.2
   Compiling matches v0.1.9
   Compiling percent-encoding v2.1.0
   Compiling tinyvec_macros v0.1.0
   Compiling unicode-bidi v0.3.8
   Compiling ryu v1.0.10
   Compiling either v1.6.1
   Compiling regex-syntax v0.6.27
   Compiling futures-core v0.3.21
   Compiling serde_json v1.0.82
   Compiling bytes v1.2.1
   Compiling futures-sink v0.3.21
   Compiling typenum v1.15.0
   Compiling futures-channel v0.3.21
   Compiling futures-task v0.3.21
   Compiling futures-util v0.3.21
   Compiling futures-io v0.3.21
   Compiling slab v0.4.6
   Compiling pin-utils v0.1.0
   Compiling if_chain v1.0.2
   Compiling base64 v0.11.0
   Compiling ppv-lite86 v0.2.16
   Compiling anyhow v1.0.58
   Compiling fnv v1.0.7
   Compiling libm v0.2.2
   Compiling log v0.4.17
   Compiling convert_case v0.4.0
   Compiling subtle v2.4.1
   Compiling base64 v0.13.0
   Compiling untrusted v0.7.1
   Compiling rustc-hash v1.1.0
   Compiling cpufeatures v0.2.2
   Compiling unicode-width v0.1.9
   Compiling siphasher v0.3.10
   Compiling strsim v0.10.0
   Compiling rustls v0.20.6
   Compiling byteorder v1.4.3
   Compiling ident_case v1.0.1
   Compiling httparse v1.8.0
   Compiling zeroize v1.5.5
   Compiling precomputed-hash v0.1.1
   Compiling new_debug_unreachable v1.0.4
   Compiling void v1.0.2
   Compiling scoped-tls v1.0.0
   Compiling static_assertions v1.1.0
   Compiling crc32fast v1.3.2
   Compiling termcolor v1.1.3
   Compiling adler v1.0.2
   Compiling tower-service v0.3.1
   Compiling try-lock v0.2.3
   Compiling base64ct v1.5.0
   Compiling opaque-debug v0.3.0
   Compiling proc-macro-hack v0.5.19
   Compiling async-trait v0.1.56
   Compiling const-oid v0.9.0
   Compiling httpdate v1.0.2
   Compiling unicode-id v0.3.2
   Compiling encoding_rs v0.8.31
   Compiling openssl-probe v0.1.5
   Compiling alloc-no-stdlib v2.0.3
   Compiling utf-8 v0.7.6
   Compiling ipnet v2.5.0
   Compiling typed-arena v2.0.1
   Compiling base16ct v0.1.1
   Compiling bit-vec v0.6.3
   Compiling khronos-egl v4.1.0
   Compiling unicode-xid v0.2.3
   Compiling mime v0.3.16
   Compiling hexf-parse v0.2.1
   Compiling ash v0.37.0+1.3.209
   Compiling match_cfg v0.1.0
   Compiling pkg-config v0.3.25
   Compiling vcpkg v0.2.15
   Compiling heck v0.4.0
   Compiling cty v0.2.2
   Compiling num-bigint-dig v0.8.1
   Compiling proc-macro2 v0.4.30
   Compiling simd-abstraction v0.6.2
   Compiling glow v0.11.2
   Compiling fixedbitset v0.4.1
   Compiling renderdoc-sys v0.7.1
   Compiling unic-common v0.9.0
   Compiling unic-char-range v0.9.0
   Compiling profiling v1.0.6
   Compiling inplace_it v0.3.3
   Compiling cfg_aliases v0.1.1
   Compiling quick-error v1.2.3
   Compiling data-encoding v2.3.2
   Compiling unicode-xid v0.1.0
   Compiling bumpalo v3.10.0
   Compiling linked-hash-map v0.5.4
   Compiling syn v0.15.44
   Compiling swc_bundler v0.169.0
   Compiling copyless v0.1.5
   Compiling pathdiff v0.2.1
   Compiling fallible-streaming-iterator v0.1.9
   Compiling crc-catalog v1.1.1
   Compiling fallible-iterator v0.2.0
   Compiling relative-path v1.7.0
   Compiling radix_fmt v1.0.0
   Compiling retain_mut v0.1.9
   Compiling dyn-clone v1.0.5
   Compiling zstd-safe v5.0.1+zstd.1.5.2
   Compiling path-clean v0.1.0
   Compiling abort_on_panic v2.0.0
   Compiling block-modes v0.9.1
   Compiling deno_ffi v0.54.0 (/home/s/src/nodejs/deno/ext/ffi)
   Compiling semver-parser v0.7.0
   Compiling cache_control v0.2.0
   Compiling io-lifetimes v0.6.1
   Compiling crossbeam-utils v0.8.8
   Compiling os_str_bytes v6.1.0
   Compiling parking_lot_core v0.8.5
   Compiling semver v1.0.13
   Compiling textwrap v0.15.0
   Compiling rustix v0.34.8
   Compiling linux-raw-sys v0.0.46
   Compiling same-file v1.0.6
   Compiling pulldown-cmark v0.9.2
   Compiling endian-type v0.1.2
   Compiling ansi_term v0.12.1
   Compiling mitata v0.0.7
   Compiling tower-layer v0.3.1
   Compiling diff v0.1.12
   Compiling monch v0.2.0
   Compiling humantime v2.1.0
   Compiling unicode-segmentation v1.9.0
   Compiling remove_dir_all v0.5.3
   Compiling utf8parse v0.2.0
   Compiling fastrand v1.7.0
   Compiling dissimilar v1.0.3
   Compiling text_lines v0.6.0
   Compiling text-size v1.1.0
   Compiling bencher v0.1.5
   Compiling shell-escape v0.1.5
   Compiling test_ffi v0.1.0 (/home/s/src/nodejs/deno/test_ffi)
   Compiling libloading v0.7.3
   Compiling instant v0.1.12
   Compiling tracing-core v0.1.27
   Compiling path-dedot v3.0.17
   Compiling nibble_vec v0.1.0
   Compiling ahash v0.7.6
   Compiling generic-array v0.14.5
   Compiling proc-macro-error-attr v1.0.4
   Compiling proc-macro-error v1.0.4
   Compiling unicase v2.6.0
   Compiling lazy_static v1.4.0
   Compiling lock_api v0.4.7
   Compiling indexmap v1.9.1
   Compiling num-traits v0.2.15
   Compiling num-integer v0.1.45
   Compiling num-bigint v0.4.3
   Compiling num-iter v0.1.43
   Compiling memoffset v0.6.5
   Compiling gpu-descriptor-types v0.1.1
   Compiling gpu-alloc-types v0.2.0
   Compiling data-url v0.1.1
   Compiling tinyvec v1.6.0
   Compiling form_urlencoded v1.0.1
   Compiling itertools v0.10.3
   Compiling http v0.2.6
   Compiling rustls-pemfile v1.0.0
   Compiling rustls-pemfile v0.2.1
   Compiling phf_shared v0.10.0
   Compiling fxhash v0.2.1
   Compiling unreachable v0.1.1
   Compiling better_scoped_tls v0.1.0
   Compiling lexical-util v0.8.5
   Compiling miniz_oxide v0.5.3
   Compiling codespan-reporting v0.11.1
   Compiling pem-rfc7468 v0.6.0
   Compiling alloc-stdlib v0.2.1
   Compiling bit-set v0.5.2
   Compiling raw-window-handle v0.4.3
   Compiling base64-simd v0.6.2
   Compiling unic-ucd-version v0.9.0
   Compiling unic-char-property v0.9.0
   Compiling wgpu-core v0.13.1
   Compiling lru-cache v0.1.2
   Compiling crc v2.1.0
   Compiling semver v0.9.0
   Compiling clap_lex v0.1.1
   Compiling walkdir v2.3.2
error: failed to run custom build command for `deno_ffi v0.54.0 (/home/s/src/nodejs/deno/ext/ffi)`

Caused by:
  process didn't exit successfully: `/home/s/src/nodejs/deno/target/debug/build/deno_ffi-da547a793a144bc2/build-script-build` (exit status: 101)
  --- stderr
  [ext/ffi/build.rs:29] &tcc_src = "/home/s/src/nodejs/deno/ext/ffi/tinycc"
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', ext/ffi/build.rs:34:37
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
</code></pre>
</details>

Versions:
```
Linux host2 5.15.0-46-generic #49-Ubuntu SMP Thu Aug 4 18:03:25 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
cargo 1.63.0 (fd9c4297c 2022-07-01)
rustc 1.63.0 (4b91a6ea7 2022-08-08)
```

**Comment by littledivy** [comment]
Did you cloned with submodules? `git submodule update --init --recursive`

**Comment by yanovich** [comment]
nope
