### ISSUE TITLE
lsp: make deno scheme easier to parse

### ISSUE THREAD

**Issue by sigmaSd** [denoland/deno#15786]
Deno scheme sometimes uses `deno:path` this is valid according to the url spec, but for editors it can cause ambiguity because for example `a:b.ts`  is a valid filename in linux

There is a pr to handle this in neovim https://github.com/neovim/neovim/pull/19967, but it seems to be tricky as it might causes subtle breaking changes.

It would be great if deno changed is usage from `deno:path` to `deno://path` to make it easier to parse and resolve the ambiguity.

**Comment by kitsonk** [comment]
Note, this specifically refers to offering "virtual documents" via the lsp, we we provide read-only versions remote modules and built-in libraries via the language server protocol.

**Comment by manateelazycat** [comment]
I add DenoUriResolver in lsp-bridge to make Emacs can parse Deno define path: https://github.com/manateelazycat/lsp-bridge/commit/5536c198e0c367ebd870613dc9fa3f1ded2c1d10
