### ISSUE TITLE
PermissionDenied error when using npm package

### ISSUE THREAD

**Issue by bardouni** [denoland/deno#15798]
I'm trying to use the [The official MongoDB driver for Node](https://www.npmjs.com/package/mongodb) in deno and it throws this error:

<img width="1001" alt="image" src="https://user-images.githubusercontent.com/11160251/188852327-2f99c0f5-e623-4d6b-b972-261ec2dabbe7.png">

Deno version: deno 1.25.1
Command: deno run -A --compat --unstable --watch=static/,routes/ dev.ts

Thank you

**Comment by bfkss** [comment]
I get an different but maybe related error: `error: Uncaught (in promise) Error: Cannot find module 'crypto'`

I am importing with the new experimental npm support
`import { MongoClient } from 'npm:mongodb'`
and executing with
`deno run --unstable -A --watch=static/,routes/ dev.ts`
with the fresh-framework.

Deno version 1.25.1

**Comment by bartlomieju** [comment]
@bfkss `npm:` specifiers are currently not supported in fresh, so it's not related to this issue.

**Comment by bardouni** [comment]
@bartlomieju  right
I move the code to a standalone file and got this error now, which i think it related to the package itself
<img width="1019" alt="image" src="https://user-images.githubusercontent.com/11160251/188917689-4151d29a-57b0-4fb0-83b0-c376f6d2091a.png">
Thank you
