### ISSUE TITLE
npm: handle the entrypoint as if it's in npm modules when certain ENV var is given

### ISSUE THREAD

**Issue by kt3k** [denoland/deno#15817]
We need to handle the entrypoint as if it's in npm modules (similar to `--compat` mode) when certain ENV var is given in order to support `child_process.fork` in `std/node` https://github.com/denoland/deno_std/issues/2636

```
DENO_NODE_FORK=1 deno run script.js # script.js works like node.js script
```

**Comment by dsherret** [comment]
Will be fixed in https://github.com/denoland/deno/pull/15806

**Comment by kt3k** [comment]
I don't see how #15806 resolved this. What is the command to start a script in node.js environment?
