### ISSUE TITLE
perf: #[op] should ban serde_v8 deserialization

### ISSUE THREAD

**Issue by littledivy** [denoland/deno#15834]
serde_v8 is great. we use it for passing arguments and returning structures from Rust... but maybe we use it too much:

- there is an obvious overhead serializing object keys for structs. We end up flattening arguments in an op. eg: #15723 #15776 
- simple enums are represented as strings in JS, bad for performance.
- for extremely critical ops, we want to inline arguments. eg: #15681 #15731 

The `#[op]` macro should not allow serde arguments unless `#[op(serde)]` is used (which is useful sometimes). This will force developers working on Deno to not fall off this performance cliff.

**Comment by bartlomieju** [comment]
I think this is reasonable and we should do it.

**Comment by bartlomieju** [comment]
Closing for now as current working in https://github.com/denoland/deno_core achieves this.
