### ISSUE TITLE
Cannot read properties of undefined (reading 'deno'). Only on DenoDeploy not happening locally

### ISSUE THREAD

**Issue by fpmirabile** [denoland/deno#15835]
Hello everyone, sorry if this is a dumb question but I couldn't find answer and the issue is not that clear to me.
We've decided to test Deno with Oak for a college project. Everything was working fine with Deno deploy... Until this error starting appearing:

```
TypeError: Cannot read properties of undefined (reading 'deno')
    at https://deno.land/std@0.106.0/node/process.ts:93:108
```

I can't find what is it. I tried removed every dependency from our project and still appears, I don't know where to look to be honest. Also I noticed that library is quite old, and none of my libraries seems to be using it.
Btw, this error only appears on DenoDeploy console, not on my end or my friend's pc.

Thanks
if it helps, you can take a look to the code here: https://github.com/fpmirabile/restaurant-backend-deno

**Comment by cjihrig** [comment]
Can you try updating? `std@0.106.0` is pretty old (September 2021). We are now up to 0.155.0.

**Comment by fpmirabile** [comment]
@cjihrig I'm not using it in my code, and as far as I saw libraries aren't either. Is there any way i can check that on my end?

**Comment by kitsonk** [comment]
`deno info` followed by the root module of your project will give you a dependency tree of what is bringing it in that is seriously out of date.

**Comment by cjihrig** [comment]
@fpmirabile did you get this sorted out?

**Comment by fpmirabile** [comment]
@cjihrig not on deno deploy. 
But I sorted out where it is coming from. It seems denodb is using some outdated library too, and std is from there.
Unfortunately I had to jump into other deploy service but couldn't fix it (not willing to fork repositories to be honest)
Thanks anyway to everyone, I will close this
