### ISSUE TITLE
Deno.test 1.25.1 NotFound: No such file or directory (os error 2)

### ISSUE THREAD

**Issue by iugo** [denoland/deno#15833]
This code (https://gist.github.com/iugo/66cf24ad826734d611e4b348f4308adf) can be run directly with `deno run`, but once run with `Deno.test`, it will throw `NotFound: No such file or directory (os error 2)`.

expected: `Deno.test` and `deno run` have the same result.

deno: 1.25.1 (macOS) / 1.25.2 (macOS)

**Comment by kitsonk** [comment]
Why do you think this is an error with Deno, and not with `onlyRun`?

**Comment by iugo** [comment]
> Why do you think this is an error with Deno, and not with `onlyRun`?

Because for the same code, deno run can execute successfully.

I removed unnecessary dependencies: https://gist.github.com/iugo/66cf24ad826734d611e4b348f4308adf/4d6b0f17e566c75b36daa3efe56a0942f7143a8c

**Comment by iugo** [comment]
@kitsonk I removed unnecessary dependencies: https://gist.github.com/iugo/66cf24ad826734d611e4b348f4308adf/4d6b0f17e566c75b36daa3efe56a0942f7143a8c

Even if I changed test-mod.ts to an absolute path, still have this error.

**Comment by lino-levan** [comment]
Your reproc example seems to work perfectly for me in Deno `1.25.2`. Am I missing something?
<img width="1048" alt="Screen Shot 2022-09-13 at 8 16 41 PM" src="https://user-images.githubusercontent.com/11367844/190051720-8faa7d4d-2302-4123-bba3-b3946e4dcd2c.png">

**Comment by iugo** [comment]
Could be a problem with the environment:

- `Deno.run({cmd: ['someapp']})`: NotFound: No such file or directory (os error 2)
- sh `someapp`: `command not found: someapp`

In some cases no `someapp` is not in the PATH.

**Comment by iugo** [comment]
The problem I was having at the time was probably an environment variable issue.

```ts
Deno.test("test", async () => {
  const p = Deno.run({
    cmd: ["deno", "--version"],
    env: { PATH: "" },
  });
  await p.status();
  p.close();
});
```

or:

```ts
// PATH error
Deno.test("test", async () => {
  const p = Deno.run({
    cmd: ["deno", "--version"],
  });
  await p.status();
  p.close();
});
```
