### ISSUE TITLE
Unable to resolve "npm:@use-gesture/react"

### ISSUE THREAD

**Issue by B3nten** [denoland/deno#15840]
`error: could not find npm package '@use' referenced by '@use-gesture/react@10.2.19'`

I'm assuming it's choking on the dash.

**Comment by dsherret** [comment]
When submitting bug reports please remember to test with the latest version of Deno by running `deno upgrade`, especially for npm specifiers because they're under active development.

That said, there is another bug here and I have opened #15851

**Comment by dsherret** [comment]
Super ironic because I was using an old version of Deno and can now reproduce. My apologies.
