### ISSUE TITLE
Unable to import `npm:eslint-plugin-jsdoc@39.3.6`

### ISSUE THREAD

**Issue by jespertheend** [denoland/deno#15865]
Running the following file:
```js
import "npm:eslint@8.23.0";
import jsdoc from "npm:eslint-plugin-jsdoc@39.3.6";
console.log(jsdoc);
```
results in `undefined` being logged.
When running with the inspector, it seems like index.js.deno_cjs_to_esm.mjs is trying to `export default mod["default"];`, but 'mod' is already the default so this should `export default mod;` 

I'm using Deno 1.25.2+ffffa2f

**Comment by brenelz** [comment]
I think deno relies on the `package.json` of `eslint-plugin-jsdoc` and it should have type="module".

I got a different error when I manually updated that which seems strange tho:

> Uncaught SyntaxError: The requested module 'npm:eslint-plugin-jsdoc' does not provide an export named 'default'

**Comment by brenelz** [comment]
It has something to do with this code but not sure what the fix is

```
if export.as_str() == "default" {
      if translate_kind == CjsToEsmTranslateKind::Deno
        && root_exports.contains("__esModule")
      {
        source.push(format!("export default mod[\"{}\"];", export));
        had_default = true;
      }
    }
```

**Comment by brenelz** [comment]
Changing this https://github.com/denoland/deno/pull/15838/files#diff-b2149263799e8c0f2bec17d01616a245cc8342ee19041a6b569504c625be7474R460 to `CJS_TO_ESM_NODE_SUFFIX` worked in this case but @dsherret probably knows more than me

**Comment by dsherret** [comment]
The issue is the code in eslint-plugin-jsdoc does:

```
Object.defineProperty(exports, "__esModule", {
  value: true
});
var _default = {
  ...
};
exports.default = _default;
module.exports = exports.default;
```

So the final `module.exports` actually cancels out all the previous exports defined on `exports`, but the cjs export analysis doesn't take that into account and it should. This will require an update in deno_ast to make the cjs export analysis a little smarter.

**Comment by brenelz** [comment]
Oh wow nice your on top of things. Your explanation makes sense
