### ISSUE TITLE
Unable to use import pipedrive from 'npm:pipedrive';

### ISSUE THREAD

**Issue by estevanjantsk** [denoland/deno#15877]
Pipedrive lib uses superagent to do http requests and this is what I get when I import the lib to my project:

<img width="966" alt="image" src="https://user-images.githubusercontent.com/461342/189692798-a598e507-e4a1-43e3-8652-4ec9f72d6130.png">

**Comment by dsherret** [comment]
@estevanjantsk could you post reproduction steps and what version you're using? I'm unable to reproduce:

```shellsession
> deno -V    
deno 1.25.2
> cat main.ts
import * as test from "npm:pipedrive";

console.log(test);
> deno run --unstable --allow-env --allow-read main.ts
{
  // outputs object here
}
```

**Comment by dsherret** [comment]
By the way, it looks like you're using Fresh. Npm specifiers don't work with Fresh atm as they're too experimental.

**Comment by estevanjantsk** [comment]
@dsherret I ran the code as you requested 
![image](https://user-images.githubusercontent.com/461342/189856729-3103083d-c01b-4c25-aad2-4958ffcdb8fa.png)
the code throws this res.setNoDelay is not a function error. So under the hood pipedrive uses superagent to handle the requests...doing a quick "google search" I found this setNoDelay comes from (https://www.geeksforgeeks.org/node-js-http-clientrequest-setnodelay-method/) HTTP from Node. 🤔

**Comment by estevanjantsk** [comment]
this is the lib Pipedrive uses https://www.npmjs.com/package/superagent to do the requests

**Comment by dsherret** [comment]
@estevanjantsk thanks. If you get a chance would you be able to add the text from the screenshot to your comment? That will make it easier for someone to copy and paste the example to reproduce the behaviour instead of having to retype it out.
