### ISSUE TITLE
`Deno.spawnSync()` doesn't support `signal` input

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno#15887]
According to [documentation](https://doc.deno.land/deno/unstable/~/Deno.SpawnOptions#signal), `Deno.spawnSync()` supports the `signal` property in its input argument. However, @crowlKats has clarified that it doesn't. Documentation should be corrected.

**Comment by iuioiua** [comment]
I can try this as my first contribution to this repo. Is this literally just a matter of modifying `lib.deno.unstable.d.ts`?

**Comment by crowlKats** [comment]
@iuioiua yes

**Comment by iuioiua** [comment]
@crowlKats, do `spawn` and `spawnChild` support `signal`?

**Comment by bartlomieju** [comment]
How would it work? Since it's a sync API it will block execution of other JS until it returns so there's no way to actually send a signal.

**Comment by bartlomieju** [comment]
Yes, only in `spawnSync`. I'd expect it to work with other two APIs.
