### ISSUE TITLE
Deno.env preserves setted values after application restart using --watch

### ISSUE THREAD

**Issue by sant123** [denoland/deno#15883]
From https://github.com/denoland/deno_std/issues/2490

Please create a file with these contents:

``` ts
// mod.ts
if (Deno.env.get("FOO") === undefined) {
  Deno.env.set("FOO", "BAR");
  console.log("Setted env var.");
} else {
  console.log("Should never be called after restart?");
  console.log(Deno.env.get("FOO"));
}
```

Run this code with `deno run --watch --allow-env mod.ts`

You should see this output:

![image](https://user-images.githubusercontent.com/7959437/189797145-47b38d95-e1d1-424d-9c77-c694fd0d68d6.png)

Now save the file and see the output:

![image](https://user-images.githubusercontent.com/7959437/189797209-4bdf1b71-c0ed-4185-af30-be8d46c6fbcd.png)

Thanks!

**Comment by sant123** [comment]
Curious, is this expected behavior?

**Comment by denizdogan** [comment]
For what it's worth, it's happening because you are setting the variable in the process environment on the first run. On the second run, you're still using the same process – only the main worker is recreated.

There is no option in Deno to --watch and run the program in a child process today. You might want to look into [denon](https://deno.land/x/denon@2.5.0) instead.

**Comment by bartlomieju** [comment]
We could fix this issue quite easily - take a snapshot of whole env when we start with `--watch` flag and on restart restore the environment to that snapshot. It will require a little munching with `std::env` API, but it's quite straightforward to do. I'll be happy to accept a PR that does that. Feel free to ping me for pointers.

**Comment by denizdogan** [comment]
> We could fix this issue quite easily - take a snapshot of whole env when we start with `--watch` flag and on restart restore the environment to that snapshot. It will require a little munching with `std::env` API, but it's quite straightforward to do. I'll be happy to accept a PR that does that. Feel free to ping me for pointers.

I've actually already started working on it. :) I'll make a PR soon.

**Comment by LeonnardoVerol** [comment]
I also would like to see this behavior

**Comment by lucacasonato** [comment]
This is intended behaviour. This is like saying "`deno run --watch` preserves files I wrote to disk between application restarts". This happens because you are calling I/O APIs, like environment variables (and those changes persist in the process).
