### ISSUE TITLE
Different resolution behavior between `deno repl --eval` and `deno repl --eval-file` with relative paths

### ISSUE THREAD

**Issue by curtislarson** [denoland/deno#15903]
Specifying `--eval-file` vs a dynamic import in `--eval` with a relative path leads to different resolution behavior (`--eval-file` fails but `--eval` succeeds).

Repro with full explanation is here: https://github.com/curtislarson/deno-repl-import-repro

I imagine the `--eval` behavior is the correct of the two?

**Comment by dsherret** [comment]
This is expected behaviour. The file will be evaluated as-is from the current directory as a string and not imported as a module, so the relative imports will be evaluated from the cwd. The eval with dynamic import works because it’s importing the other module from the cwd.
