### ISSUE TITLE
Stabilize `Deno.osRelease()`

### ISSUE THREAD

**Issue by piscisaureus** [denoland/deno#15928]
Required for Mongoose support.

ref #15824

**Comment by bartlomieju** [comment]
I think we should move it to `Deno.build.osRelease` which would imply that `--allow-env` permission is not required. Thoughts?

**Comment by Im-Beast** [comment]
But `Deno.osRelease()` requires `--allow-env` permission 🤔

**Comment by lucacasonato** [comment]
> I think we should move it to Deno.build.osRelease which would imply that --allow-env permission is not required. Thoughts?

It is not related to the build though. `Deno.build` contains info about the Deno build, not about the current system.

**Comment by bartlomieju** [comment]
Right... good point. Alright, I'll just open a PR to stabilize it.
