### ISSUE TITLE
[Language Service Error] Exported types not detected correctly when using `export * from "npm:rxjs@7.5.6"`

### ISSUE THREAD

**Issue by bjesuiter** [denoland/deno#15947]
I found another node_compat bug. 

Here is a small demo repo (look at tasks rxjs-02 to rxjs-05) : https://github.com/jbscratch/rxjs-in-deno

## The Problem 

When importing `npm:rxjs@7.5.6` directly in a file, the linter seems happy and finds the exported types. 
But when I try to re-export like this: 

```
// in /deps/rxjs.ts
export * from "npm:rxjs@7.5.6";
```

and try to import it as: 

```
// in top-level main.ts 
import { Subject } from "./deps/rxjs.ts";
```

VSCode will complain that there is no exported member called "Subject" available

**Comment by bjesuiter** [comment]
Thanks for the info! 
I'll keep the issue open so that i can keep track of it until it's implemented :)

**Comment by nayeemrmn** [comment]
This works now
