### ISSUE TITLE
[Bug] | Bundling Enums when not imported

### ISSUE THREAD

**Issue by BlackAsLight** [denoland/deno#15942]
So Deno seems to be bundling enums into my js when I'm not importing it into it, nor it being required for anything in the code to run.
![Screen Shot 2022-09-18 at 16 45 21](https://user-images.githubusercontent.com/44320105/190889428-79c0866f-743c-44ae-9556-0a6c6bc6d36c.png)

**Comment by kitsonk** [comment]
swc does not appear to be tree shaking enums.

**Comment by BlackAsLight** [comment]
With `deno bundle` being removed in Deno 2.0, this issue no longer seems relevant.
