### ISSUE TITLE
How to import express and have typing?

### ISSUE THREAD

**Issue by MatthD** [denoland/deno#15955]
Hello, 

Just following the documentation I tried to 

```typescript
/// <reference path="https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/master/types/express/index.d.ts" />
import express from "npm:express";

const app = express();
```

but no luck, app is of `any` types, 

**More generally I do not understand how to deal with types coming from npm modules.**

**Comment by kitsonk** [comment]
This is not currently supported with experimental npm specifiers, but is on the roadmap.

**Comment by kitsonk** [comment]
#15960 has been opened to track progress of support. Closing in favour of that.

**Comment by loynoir** [comment]
Not tested, but you may try `https://esm.sh/{{package}}@{{version}}`.

Plus, you can get `https://esm.sh` self hosted.
