### ISSUE TITLE
Ignored "experimentalDecorators" compiler option

### ISSUE THREAD

**Issue by harrytruong** [denoland/deno#15968]
The [Configuration File](https://deno.land/manual@v1.25.3/getting_started/configuration_file#json-schema) docs link to the following JSON schema file: https://deno.land/x/deno/cli/schemas/config-file.v1.json

Disabling the `experimentalDecorators` compiler option seems to have no effect? Is there no way to disable this behavior?
```js
// deno.json
{
  "compilerOptions": {
    "experimentalDecorators": false // default: true
  }
}
```

It actually warns about the `experimentalDecorators` option being ignored:
```
$ deno run --config deno.json main.ts
Unsupported compiler options in "file:///path/to/deno.json".
  The following options were ignored:
    experimentalDecorators
```

**Comment by kitsonk** [comment]
We have tried to minimise the variability of TypeScript code used by Deno.  Forcing experimental decorators on was a decision we made as if you don't use them they have no impact.

It is an omission in `config-file.v1.json` to list it as a possible option, when we hard-coded it `enabled` some time ago.

Was there a reason, outside it being listed as something that could be configured but isn't, to want to disable the feature?

**Comment by harrytruong** [comment]
I wanted to disable the feature to discourage my team from using it (since it is technically still experimental, and may still change). I understand the Deno team has decided to enable it by default, but I'm surprised it's explicitly not possible to disable. Is there documentation how the team came to that decision?

The inclusion in `config-file.v1.json` is useful, so it's documented that the compiler option is enabled by default.

Can we improve on this behavior by:
- changing on the warning message to clarify that the feature is hard-coded `enabled`, and/or
- changing the `config-file.v1.json` to something like
  ```json
  {
        "experimentalDecorators": {
          "description": "Experimental support for TC39 stage 2 draft decorators is hard-coded as enabled.",
          "default": true,
          "enum": [true],
          "markdownDescription": "Enables experimental support for TC39 stage 2 draft decorators.\n\nSee more: https://www.typescriptlang.org/tsconfig#experimentalDecorators"
        },
  }
  ```

?

**Comment by ntkoopman** [comment]
Since typescript 5 decorators are enabled by default, but setting `experimentalDecorators` will enable the old legacy decorators instead of the new implementation.

**Comment by lucacasonato** [comment]
The issue has been resolved.

No `experimentalDecorators`, or `experimentalDecorators: false` -> standard ES decorators (but only in TS files for now)

`experimentalDecorators: true` -> legacy TS decorators (and only in TS files)

The latter are deprecated and will be removed in some future release. You should migrate to standard decorators.

**Comment by henryleu** [comment]
The new standard decorators does not support Parameter Decorators, as of now. so all my project will still depend on the old decorators standard. Please treat them kindly until the new decorators standard are full-pledged.

**Comment by petamoriken** [comment]
Although not recommended, you can handle non-standard legacy decorators in your project by setting `experimentalDecorators: true`.
