### ISSUE TITLE
Got an error on map-source downloading

### ISSUE THREAD

**Issue by rdmitrievsky** [denoland/deno#15977]
Hi, ima kinda new to Deno, so question might be a bit wierd, anyways, while deploying new commit with no any changes in dependencies, there pops an error:

│ Download https://dev.jspm.io/npm:source-map@0.6?dew
│ error: Import '[https://dev.jspm.io/npm:source-map@0.6?dew'](https://dev.jspm.io/npm:source-map@0.6?dew%27) failed: 500 Internal Server Error
│     at https://dev.jspm.io/handlebars@4.7.6:36:0

Any help would be much appreciated )

**Comment by dsherret** [comment]
It seems that url is returning a 500 status code. Probably your local machine cached it while it was working and now the server is erroring. If you run with `--reload` it will probably start erroring locally now. There's not much you can do other than try out a different url or wait for jspm to be fixed.

FYI @guybedford it seems all these urls are erroring now on jspm https://cs.github.com/?q=https%3A%2F%2Fdev.jspm.io%2Fnpm%3A&p=1&pt=54fc432f24dcfb050a9609c5bc506cab6b57cc614e0a9df550d765783b82dc7b9d7a34aceae9ac1a7c69c8388da8c488ebf94d8aab0c9b4194bb66a1a883415cb364170e57a85e99c29edca1abc88426a3a1b04b04a316b8c6469e5343478cfbc20e52376519199805845067feee56e4ecea71413bc387d928513cb2ae4aa64055a66a40efd95f769704cf0a5d5105952020597364391e1e4f80fc30&scope=&scopeName=All+repos
