### ISSUE TITLE
Automatic PR forwarding patch release commit back to main is broken

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#16000]
See how this contains way too much code and not just the commit that's cherry picked: https://github.com/denoland/deno/pull/15999

What works locally for me does not work on the CI. I don't know enough about git. It's probably a setting somewhere that needs to be set.

https://github.com/denoland/deno/blob/9bf4ec2eac6f30f962fa71914e6be4518d1561de/tools/release/04_post_publish.ts#L47-L61

**Comment by lucacasonato** [comment]
We've given up on this.
