### ISSUE TITLE
Local node_modules - Use junctions instead of symlinks on Windows

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#16006]
Edit: Use junctions instead like pnpm does (see comments below)

~~Users on Windows need to enable developer mode to get the local node_modules working because it uses symlinks.~~

https://learn.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development

~~I think though that some users might not be able to enable this, but I'm not sure how widespread of an issue this is.. so for now, let's add some instructions about enabling developer mode then maybe in the future have a warning then fallback solution for those users.~~

---

See error from: https://github.com/denoland/deno/issues/15427#issuecomment-1255657707

```
PS C:\Users\rekke\Documents\vite-deno-example> deno task dev
Warning deno task is unstable and may drastically change in the future
Task dev deno run -A --unstable --node-modules-dir npm:vite
error: A required privilege is not held by the client. (os error 1314), symlink 'C:\Users\rekke\Documents\vite-deno-example\node_modules\.deno\esbuild-freebsd-arm64@0.15.8\node_modules\esbuild-freebsd-arm64' -> 'C:\Users\rekke\Documents\vite-deno-example\node_modules\.deno\esbuild@0.15.8\node_modules\esbuild-freebsd-arm64'
```

**Comment by DefinitelyMaybe** [comment]
brilliant! thank you @dsherret

**Comment by brc-dd** [comment]
You can just use junction mode to create symlinks in Windows. Junctions don't need elevation or developer mode to be enabled. That's what pnpm do.

**Comment by dsherret** [comment]
Huh, good to know. Thanks @brc-dd! I found this crate for doing that https://docs.rs/junction/latest/junction/
