### ISSUE TITLE
lsp: "Add all missing imports" VSCode quick fix produces invalid import specifiers

### ISSUE THREAD

**Issue by curtislarson** [denoland/deno#16016]
Running "Add all missing imports" causes the `.ts` extension to be appended before the end of the actual filename in some conditions (possibly due to multiple `-` in filename, or the fact that the filenames share a common substring).

E.g it inserts `./duck-config.ts-options` instead of `./duck-config-options.ts`

Repro repo with full explanation: https://github.com/curtislarson/deno-add-all-missing-imports-repro

**Comment by kitsonk** [comment]
When the TypeScript language server is returning a fix, we are not properly identifying that it contains a module specifier and not replacing it.  There are a few other situations where this is occurring as well.
