### ISSUE TITLE
Weird behavior with let and const

### ISSUE THREAD

**Issue by Lonniebiz** [denoland/deno#1602]
deno: 0.2.8
v8: 7.2.502.16
typescript: 3.2.1

Look at this command line session with deno. let and const didn't work but var did.

$ deno
> let a=1, b=2, c=3
undefined
> a
ReferenceError: a is not defined
> ;
undefined
> a
ReferenceError: a is not defined
> let a =1;
undefined
> a
ReferenceError: a is not defined
> var a = 1;
undefined
> a
1
> let b = 2;
undefined
> b
ReferenceError: b is not defined
> const c = 3
undefined
> c
ReferenceError: c is not defined
> let c = 3;
undefined
> c
ReferenceError: c is not defined

BTW, Deno is fast! I ran a few script with node and with deno. Deno was noticeably faster.

**Comment by kitsonk** [comment]
We still have quite a few challenges with the REPL that we need to work out.

**Comment by ry** [comment]
I believe this is fixed in https://github.com/denoland/deno/pull/1407
... which is on my queue to look at.
