### ISSUE TITLE
Possibility to expose local environment variables unintendedly

### ISSUE THREAD

**Issue by JabSYsEmb** [denoland/deno#16024]
I am not sure if this is an issue or not but I am submitting since it might be a vulnerability issue.

`VARIABLE_NAME=${VARIABLE_ENV}` could be used to exposes local variables on a machine, which these variables may be  secrets.
 
```Javscript
//index.ts
import * as mod from "https://deno.land/std@0.157.0/dotenv/mod.ts";

console.log(await mod.config());
```

```bash
// .env
EXPOSE_LOCAL_ENV=${PATH}
EXPOSE_LOCAL_PWD=${PWD}
```

```command
$ deno run --allow-env --allow-read index.ts
```

<img width="1414" alt="Example" src="https://user-images.githubusercontent.com/32222578/192254099-716f2332-f59c-4124-9d43-50a7a715416f.png">

**Comment by lucsoft** [comment]
.env just loads to the normal variables and does variable resoultion all these envs variables are already exposed in Deno.env
