### ISSUE TITLE
What am i doing wrong (deno run)

### ISSUE THREAD

**Issue by cwpwd** [denoland/deno#16021]
Just installed Deno (on Linux) and then `deno run` on a file containing the following:

```ts
function add(a: number, b: number): number {
	return a + b
}

console.log(add(2, "5"));
```

And the output was `25`

Can't say that something wrong with TS, [Playground Link](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAQwCaoBTIFyLCAWwCMBTAJwBpEjd9jyBKWw0sxAbwCgBIMkqEGSTJEAamqcAvp04QEAZzgAbEgDolcAOZZ0GAExUARAFZDDBgG5OQA)

**Comment by cjihrig** [comment]
If you run `deno run --check`, you'll see a TypeScript error. Without running the type checker, you're basically getting plain JavaScript behavior and 2 + "5" yields "25".

Closing as working as intended.

**Comment by cwpwd** [comment]
The file had a `.ts` extension (`deno run add.ts`).

Doesn't that clearly specify that TypeScript features should be enabled?
