### ISSUE TITLE
error: Uncaught SyntaxError: The requested module 'https://googleapis.deno.dev/v1/spanner:v1.ts' does not provide an export named 'ServiceAccount'

### ISSUE THREAD

**Issue by Daiki48** [denoland/deno#16033]
I would like to use googleapi with deno.  

https://googleapis.deno.dev

```typescript
// Import the client
import { ServiceAccount, Spanner } from "https://googleapis.deno.dev/v1/spanner:v1.ts";

// Read the service account key.
const file = Deno.readTextFileSync("service-account.json");
const auth = ServiceAccount.fromJson(JSON.parse(file));

// Instantiate the client.
const spanner = new Spanner(auth);

// List Spanner instances.
const instances = await spanner.listInstances("projects/my-project");
console.log(instances);
```

After implementing this Example, I got the same error as the title.
As per the error message, the `ServiceAccount` did not exist.

https://doc.deno.land/https://googleapis.deno.dev/v1/spanner:v1.ts

In this case, which module should replace `ServiceAccount`?

If you would like, please share the documentation with me.

**Comment by dsherret** [comment]
I'm not sure who created the googleapis.deno.dev or where issues should be reported for it, but this doesn't look like an issue with Deno's CLI as there's no `ServiceAccount` export from that module. Also, see the documentation for `Spanner` and how it doesn't take a `ServiceAccount`.

**Comment by kitsonk** [comment]
@lucacasonato did, and the repo is private... maybe @lucacasonato can give guidance on how to report issues with it.

**Comment by Daiki48** [comment]
Thanks for the confirmation.

There is a class called `GoogleAuth`. I am investigating this class as a replacement for `ServiceAccount`.
