### ISSUE TITLE
How to programmable  set fetch proxy ?

### ISSUE THREAD

**Issue by kaneruan** [denoland/deno#16031]
`HTTP_PROXY` and `HTTPS_PROXY` is stiff.

**Comment by 0f-0b** [comment]
[`Deno.createHttpClient`](https://deno.land/api@v1.25.4?unstable&s=Deno.createHttpClient) has been accepting the `proxy` option [since 1.12](https://deno.com/blog/v1.12#add-custom-proxy-support-to-fetch). This feature is still behind `--unstable` though.
