### ISSUE TITLE
Wrong buffer length from deriveBits

### ISSUE THREAD

**Issue by diachedelic** [denoland/deno#16047]
It appears that `deriveBits` always returns a buffer the length of the key, rather than the requested length. The following code yields the expected results in the browser, but not Deno v1.25.4.

```javascript
crypto.subtle.generateKey(
    {
        name: "ECDH",
        namedCurve: "P-384"
    },
    true,
    ["deriveKey", "deriveBits"]
).then(function (keypair) {
    return crypto.subtle.deriveBits(
        {
            name: "ECDH",
            public: keypair.publicKey
        },
        keypair.privateKey,
        256
    );
}).then(function (derived_bits) {
    console.log(derived_bits.byteLength * 8); // 384, should be 256
});
```

**Comment by Nautigsam** [comment]
Does the length passed to `deriveBits` has to be inferior or equal to the length of the key? I couldn't find much information regarding WebCrypto implementation.

**Comment by diachedelic** [comment]
I suspect the Web Platform Tests would have picked this up, but many of its WebCrypto suites are disabled due to Deno's current lack of P-521 support.

**Comment by Nautigsam** [comment]
I put your example in a unit test. I did not touch Web Platform Tests. As you said, the whole ECDH suite is disabled.

**Comment by diachedelic** [comment]
Thank you all.
