### ISSUE TITLE
Mac ci times out

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#16043]
The mac CI now often times out. For example:

https://github.com/denoland/deno/actions/runs/3129588366/jobs/5078866651
https://github.com/denoland/deno/actions/runs/3115783842/jobs/5053019234

**Comment by kt3k** [comment]
The build time takes significant amount (like 80 min) when it's timed out.

**Comment by kt3k** [comment]
Might be resolved by https://github.com/denoland/deno/pull/16053 ?

**Comment by dsherret** [comment]
Yup! We can close this now.
