### ISSUE TITLE
Fetch response bodyUsed is writeable and doesn't work

### ISSUE THREAD

**Issue by sh7dm** [denoland/deno#1605]
deno: 0.2.8
v8: 7.2.502.16
typescript: 3.2.1

We can set Response.bodyUsed, but specs say different:
```
> res.bodyUsed
false
> res.bodyUsed = true
true
> res.bodyUsed
true
```
https://developer.mozilla.org/en-US/docs/Web/API/Body#Properties
I want to work on this issue.

**Comment by sh7dm** [comment]
Looks like `bodyUsed` doesn't work at all. If I write a unit test like this and run it, it'll fail:
```typescript
testPerm({ net: true }, async function fetchJsonSuccess() {
  const response = await fetch("http://localhost:4545/package.json");
  assertEqual(response.bodyUsed, false);
  await response.text();
  assertEqual(response.bodyUsed, true);
});
```
Second assert fails.

**Comment by ry** [comment]
Closing because this is old - please let me know if this is still an issue.

**Comment by kt3k** [comment]
It seems still an issue.

deno
```
$ deno
> (async () => { res = await fetch('https://example.com') })()
Promise {}
> res.bodyUsed
false
> res.bodyUsed = true
true
> res.bodyUsed
true
```

chrome
<img width="717" alt="スクリーンショット 2019-09-07 13 05 00" src="https://user-images.githubusercontent.com/613956/64469629-2cd1cc80-d170-11e9-8d0d-656ef022c321.png">
