### ISSUE TITLE
deno test --coverage doesn't work with --allow-* flag

### ISSUE THREAD

**Issue by danielr1996** [denoland/deno#16063]
When running `deno test --coverage=cov --allow-all` or any other --allow flag, the coverage report doesn't work for those files that need those permissions. I haven't still figured out excatly how and when it doesn't work, e.g. sometimes files are completely missing from the v8 coverage report, sometimes `deno coverage` show the files, but reports all lines as uncovered. Will create a repo to reproduce tommorow. 

Tested on 
```
$ deno --version
deno 1.25.4 (release, x86_64-pc-windows-msvc)
v8 10.7.193.3
typescript 4.7.4
``` 

and

```
$ deno --version
deno 1.25.4 (release, aarch64-apple-darwin)
v8 10.7.193.3
typescript 4.7.4
```

**Comment by extremelylatebound** [comment]
Currently running into this - @danielr1996 did you find a root cause?
