### ISSUE TITLE
Support checking if in a TTY

### ISSUE THREAD

**Issue by luvies** [denoland/deno#1607]
As far as I can tell, there doesn't seem to be a good way to check if you are running in an interactive session or not. In node, you have `process.stdout.isTTY`, but I can't find anything related to doing something similar in the standard lib. It would be useful in cases like if you want to simplify the text output, like disabling colours when being piped somewhere (e.g. a CI/CD pipeline).

**Comment by sh7dm** [comment]
I'm implementing this now
