### ISSUE TITLE
lsp: quickfix: cache all

### ISSUE THREAD

**Issue by loynoir** [denoland/deno#16082]
### Current
current `quickfix: cache` is only cache one import within current file

### Request
`quickfix: cache all` cache all import within current file

### Scenario
Devcontainer

**Comment by kitsonk** [comment]
We currently offer _Deno: Cache Dependencies_ in the command pallet in vscode_deno, but we do not issue a quick fix for caching all dependencies when there is > 1 uncached dependency, and we could/should do that.

**Comment by kitsonk** [comment]
This basically would need to be an update to the grouping logic applied to code fixes, which already exists.

**Comment by bartlomieju** [comment]
This would be added to `code_action` function in `cli/lsp/language_server.rs`. Logic should be as follow: if there is more than 1 fixable diagnostics, originating from `"deno"` source, and their code is one of `"no-cache" | "no-cache-data" | "no-cache-npm"` then a new "deno.cache" action should be added without any arguments.

I might take a stab at it myself later, want to do some cleanups first.
