### ISSUE TITLE
npm imports don't work in repl

### ISSUE THREAD

**Issue by oscarotero** [denoland/deno#16088]
When I want to import a npm module dynamically, I get the following error:

```ts
const react = await import("npm:react");

// Uncaught TypeError: Loading unprepared module: npm:react
//     at async <anonymous>:2:15
```

**Comment by dsherret** [comment]
Works for me. Can you provide some reproduction steps? Maybe this is #15826?

**Comment by oscarotero** [comment]
The example above fails in repl:
<img width="417" alt="imaxe" src="https://user-images.githubusercontent.com/377873/193152729-1eee5d0e-7be3-4963-9f68-0e3c0e209173.png">

but it works if it's in a file.

Other weird examples:

```js
// This works
const react = await import("npm:react");

// This doesn't work
const react = await import(`npm:react`);

// This doesn't work
const react = await import("npm:" + "react");
```

Other example, not sure if it's a bug:

```js
// error: Uncaught (in promise) Error: Cannot find module 'react'
const server = await import("npm:react-dom@18.2.0/server");
```

```js
// This works
const react = await import("npm:react");
const dom = await import("npm:react-dom@18.2.0/server");
```

**Comment by dsherret** [comment]
We haven't implemented npm specifiers in the repl yet. I've renamed this issue and added it to the roadmap.

The non-analyzable specifiers example is probably #15826 and the react-dom one is peer dependency support, which we don't have yet either.

**Comment by oscarotero** [comment]
okay, thx

**Comment by roj1512** [comment]
Would be cool.
