### ISSUE TITLE
lsp: respect fmt configuration

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#16083]
We allow configuration of a few options with `deno fmt` in a configuration file:

```json
{
  "fmt": {
    "options": {
      "lineWidth": 80,
      "proseWrap": "always",
      "singleQuote": false,
      "useTabs": false,
      "indentWidth": 2
    }
  }
}
```

And those applied when formatting is run though the lsp format request, but are not being applied for things like auto-imports and other TypeScript language server provided APIs.  There are a set of "user options" that get sent on language server requests, and we should update those to be in line with the formatting preferences here, so completions and quick fixes work as expected.

In addition there are some internally generated quick fixes and completions that should respect these settings too.

This is sort of a bug and a feature at the same time.

**Comment by dsherret** [comment]
It seems this was fixed in https://github.com/denoland/deno/pull/12338/files#diff-a3c3076fba005cef6d6924ad59c39e84c1bf005aafae2a37295682dd8c8a6138 but no test was added. We should add a test then we can close this out.
