### ISSUE TITLE
`import.meta.resolve` doesn't work with npm specifiers.

### ISSUE THREAD

**Issue by oscarotero** [denoland/deno#16089]
The following code returns the same npm specifier instead of the url of the resolved file:

```ts
const reactLocation = import.meta.resolve("npm:react");

// npm:react
```

**Comment by bartlomieju** [comment]
I believe this is correct. If you do `console.log(import.meta.resolve("https://deno.land/std@0.158.0/http/file_server.ts"));` you will get `"https://deno.land/std@0.158.0/http/file_server.ts"`, not the path to Deno cache.

**Comment by oscarotero** [comment]
@bartlomieju Is there any way to get the path of the cached file? I'm using it with `esbuild` to resolve and load dependencies for bundling.

**Comment by bartlomieju** [comment]
Not currently, no. You can do that, if you know the exact version you want to use though - `deno info` gives you information where a cache for npm packages resides and with that you can construct the path yourself.

It is something I also encountered when trying to write a plugin for `rollup`; so we will probably look into some more ergonomic way.

**Comment by deckchairlabs** [comment]
@oscarotero @bartlomieju Adding an import before the `import.meta.resolve` returns the path of the cached file.

```ts
import React from "npm:react";

console.log(import.meta.resolve("npm:react"));
```

**Comment by oscarotero** [comment]
This is a inconsistency and it doesn't work in all cases. This code returns an error 

```js
const specifier = "npm:react";
await import(specifier);

console.log(import.meta.resolve(specifier));
/* error: Uncaught (in promise) TypeError: Loading unprepared module: npm:react, imported from: file:///Users/oscarotero/www/test/deno/main.js */
```

For now, I'm using esm.sh to get the content of the npm packages: https://github.com/lumeland/lume/blob/6cca5823609ee3c036e7e51d918a304067bc9066/plugins/esbuild.ts#L82-L85

**Comment by guybedford** [comment]
Thinking in terms of a request URL / response URL may offer a little more flexibility here in in trying to reconcile any differences between `import.meta.url` and `import.meta.resolve`. Redirects allow the response URL (as `import.meta.url` represents) to be different to the request URL. `import.meta.resolve` then corresponds to the request URL as it is the client side resolver, before redirects are applied.

**Comment by oscarotero** [comment]
There's a casuistry that must be taken into account: the `npm` package that is not cached (because it wasn't imported previously). If it's decided that `import.meta.resolve("npm:react")` must return the cached file, but it isn't already cached, this means Deno must download and cache the package before return the filename.

**Comment by guybedford** [comment]
@oscarotero `import.meta.resolve` is synchronous uses the _current resolver cache_. This can be distinct from what the tracing loader is doing asynchronously. It is possible for `import.meta.resolve` to fail where dynamic `import()` would pass due to this distinction.

**Comment by bartlomieju** [comment]
Closed in https://github.com/denoland/deno/pull/21716.
