### ISSUE TITLE
Not enough test case in cli/display.rs

### ISSUE THREAD

**Issue by skanehira** [denoland/deno#16090]
Since `size < 1_f64 ` determines whether the value is negative or not, `let negative = ...` does not seem to be necessary.

https://github.com/denoland/deno/blob/927f4e2e83719aac3dcc4d9ae422cbbf76bd7bcd/cli/display.rs#L6-L11

**Comment by cjihrig** [comment]
> Since size < 1_f64 determines whether the value is negative or not

It looks like `size` is an absolute value in that comparison, so it wouldn't be used to determine if the value is negative or not.

**Comment by skanehira** [comment]
My understanding was wrong 😅
Also, test cases seems like not enough (e.g -10GB)
I'll revert and add tests in this PR
