### ISSUE TITLE
cache.put fails for Unix-socket-originated request.url

### ISSUE THREAD

**Issue by wwoast** [denoland/deno#16094]
I was very excited for the new Deno web cache feature! However if I try and use the new Deno cache for request URIs (`http+unix://%2Ftmp%2Fserver%2Esock/images/logo.png`) from the Unix socket http listener, I get an error:

```
Error serving request: TypeError: Request url protocol must be 'http:' or 'https:'
    at Cache.put (deno:ext/cache/01_cache.js:96:15)
    at Object./images/logo.png (file:///tmp/server/router.ts:450:29)
    at async handleRequest (file:///tmp/server/router.ts:213:24)
    at async handleConnection (file:///tmp/server/router.ts:121:11)
```

Cheers,
Justin

**Comment by wwoast** [comment]
Just locally-tested the trivial fix for this by modifying `ext/cache/01_cache.js` so will submit a PR shortly!

**Comment by satyarohith** [comment]
Closing this issue as we're not ready to deviate from the spec yet.

https://github.com/denoland/deno/pull/16127#pullrequestreview-1127659789

**Comment by wwoast** [comment]
@satyarohith yeah, I understand that Unix socket HTTP listeners are a fringe area, away from web standards. I've invested a decent amount of time using them, but given the [surprises](https://github.com/denoland/deno/issues/15640) I run into, I might shift my energy to normal network sockets.

Is Deno's goal to make Unix socket requests "appear more similar to" http/https sockets, to eventually agree that "http+unix:" is some kind of standard, or are Unix sockets not considered useful enough to "gently extend" standards to?

Ironically, my use case involved starting with the [Sift router code](https://github.com/satyarohith/sift/blob/main/mod.ts) and adding a Unix socket listener to it. So my use of `ext/cache` is literally replacing the `inMemoryCache` in Sift. My choosing Unix sockets was a way to run a local web server on an external interface of my laptop, without having a `localhost` service that could be targeted by malicious external sites.
