### ISSUE TITLE
Failed to resolve JSON files when using npm specifiers

### ISSUE THREAD

**Issue by kidonng** [denoland/deno#16118]
Deno version: 1.26.0

```shellsession
$ deno run -A --unstable npm:xo --help
error: Expected ';', '}' or <eof> at file:///home/codespace/.cache/deno/npm/registry.npmjs.org/globals/13.17.0/globals.json:2:12
```

According to [the README](https://github.com/sindresorhus/globals#readme), the `globals` package contains a plain JSON file and is used by ESLint. The issue seems to be related to JSON resolution (it seems like the resolver treats the JSON as a ES module), but it's just my best guess.

The `xo` package has a lot of dependencies so it's definitely not a minimal reproduction. Pardon me for not having a better one.

**Comment by bartlomieju** [comment]
Simpler reproduction:

```
import globals from "npm:globals";
```

```
deno run -A --unstable test.js
error: Expected ';', '}' or <eof> at file:///Users/ib/Library/Caches/deno/npm/registry.npmjs.org/globals/13.17.0/globals.json:2:12
```

**Comment by okikio** [comment]
I'm also running into this issue in Deno 1.31.1
