### ISSUE TITLE
CacheStorage API ignores Accept-Encoding in cache matching

### ISSUE THREAD

**Issue by FergoTheGreat** [denoland/deno#16122]
Deno 1.26 adds the CacheStorage Web API. I wrote a little test that seems to fail.

    import { serve } from "https://deno.land/std@0.156.0/http/server.ts"

    function delay(ms: number) {
        return new Promise(resolve => setTimeout(resolve, ms))
    }

    function compress(str: string, encoding: string) {
        const data = new TextEncoder().encode(str)
        const cs = new CompressionStream(encoding)
        const writer = cs.writable.getWriter()
        writer.write(data)
        writer.close()
        return new Response(cs.readable).arrayBuffer()
    }

    async function compressResponseBody(body: string, encodings: string[]): Promise<[string | null, ArrayBuffer]> {
        if (encodings.includes("gzip")) {
            return ["gzip", await compress(body, "gzip")]
        } else if (encodings.includes("deflate")) {
            return ["deflate", await compress(body, "deflate")]
        } else {
            return [null, new TextEncoder().encode(body)]
        }
    }

    const cache = await caches.open("test")
    cache.delete(new URL("http://localhost/"))

    serve(async function(request: Request) {
        const response = await cache.match(request)
        if (response) {
            console.log("Cache hit.")
            return response
        } else {
            console.log("Cache miss.")
            const encodings = request.headers.get("Accept-Encoding")?.split(",") ?? []
            const [encoding, body] = await compressResponseBody("Hello, World!", encodings)
            const headers = new Headers()
            if (encoding) {
                headers.set("Content-Encoding", encoding)
            }
            const response = new Response(body, { status: 200, headers })
            cache.put(request, response.clone())
            return response
        }
    }, { port: 80 })

    await fetch("http://localhost/", { headers: { "Accept-Encoding": "gzip" }})
    await delay(1000)
    await fetch("http://localhost/", { headers: { "Accept-Encoding": "deflate, br" }})

Expected output would be that "Cache miss." is printed twice since the two requests have incompatible values for `Accept-Encoding`. Instead the second response is found in the cache because Deno appears to ignore `Accept-Encoding` and only look at the URL despite the fact that the response contains `Vary: Accept-Encoding`.

**Comment by satyarohith** [comment]
@FergoTheGreat, from your code, the only header that's set for the response is "Content-Encoding". If also set `Vary: Accept-Encoding` header for the response, then you will see two cache misses.

```
➜  deno git:(main) ✗ cat t.ts | grep headers.set
      headers.set("Content-Encoding", encoding);
      headers.set("Vary", "Accept-Encoding");
➜  deno git:(main) ✗ deno run -A t.ts
Listening on http://localhost:80/
Cache miss.
Cache miss.
```

**Comment by FergoTheGreat** [comment]
@satyarohith You are correct, my mistake. I had noticed that responses from a Deno server always included `Vary: Accept-Encoding`. No doubt this is added by the automatic body compression code which happens *after* the response has been cached, not before.
