### ISSUE TITLE
Abstract Class Field Leaves Initializer on Class

### ISSUE THREAD

**Issue by alexlafroscia** [denoland/deno#16124]
I've noticed an issue with Deno 1.26 that I don't believe was in previous versions of Deno

If you have an abstract class that declares some properties that the implementer should define, Deno seems to be leaving a property initializer behind on that abstract class:

```ts
export abstract class Shape {
  abstract height: number;
  abstract width: number;
}
```

If I run this through the TypeScript Playground, the fields are stripped completely:

```ts
export class Shape {
}
```

However, running the same code snippet through `deno bundle` results in different output:

```ts
// deno-fmt-ignore-file
// deno-lint-ignore-file
// This code was bundled using `deno bundle` and it's not recommended to edit it manually

class Shape {
    height;
    width;
}
export { Shape as Shape };
```

These initializers result in issues when the subclass of the abstract class implement those abstract properties as getters. Take the following source code, for example:

```ts
abstract class Shape {
  abstract height: number;
  abstract width: number;
}

class Dot extends Shape {
  get height() {
    return 1;
  }

  get width() {
    return 1;
  }
}

const dot = new Dot();
console.log({ height: dot.height, width: dot.width });
```

I would expect that this prints the following

```ts
{ height: 1, width: 1 }
```

but what it actually prints is this

```ts
{ height: undefined, width: undefined }
```

Indeed, the behavior of running `deno` directly seems to differ from running the same source code through TypeScript directly (through the playground) which results in this code:

```ts
"use strict";
class Shape {
}
class Dot extends Shape {
    get height() {
        return 1;
    }
    get width() {
        return 1;
    }
}
const dot = new Dot();
console.log({ height: dot.height, width: dot.width });
```

When executing that with `deno run`, you get the output I would have expected from the original example:

```ts
{ height: 1, width: 1 }
```

**Comment by dsherret** [comment]
I opened https://github.com/swc-project/swc/issues/6023
