### ISSUE TITLE
lsp: cached diagnostics display, even when file is opened in editor

### ISSUE THREAD

**Issue by KyleJune** [denoland/deno#16135]
**Describe the bug**

**To Reproduce**

No clear reproduction path. This is in a large private code base. Warning shows whenever I first open the file and goes away after I make any change near the lines affected. For example if I add a new line, it will fix it, and it will stay fixed if I remove the new line, returning it to how it was originally but without any warning.

**Expected behavior**

There should be no warning.

**Screenshots**

In this example, I show one of these false warnings. The test before it correctly recognizes the type of this. In the video I update the test with the warning to have a new line and the warning disappears. If I remove the new line, the error doesn't return. There are 2 tests in this file where this warning happens. Both warnings resolve when the first one resolves, even though I don't touch the second spot where this warning occurs in the file. There are many similar tests that have no warnings.

https://user-images.githubusercontent.com/3241653/193434797-1912e75e-bd44-4582-9d8e-703704a1a2ac.mp4

**Versions**

vscode: 1.71.2 deno: 1.25.4 extension: v3.13.1

**Comment by nayeemrmn** [comment]
I think we send diagnostic updates more now, @KyleJune please say if it's still an issue. Closing for now.
