### ISSUE TITLE
[feat] deno bundle --minify

### ISSUE THREAD

**Issue by loynoir** [denoland/deno#16149]
Also options like esbuild

https://esbuild.github.io/api/#minify

**Comment by kitsonk** [comment]
`deno bundle` is not designed to be a general purpose bundler.  In it current form it is likely not to exist into the future (see: #15463).  We are not really considering new features for it at this point.  If you want a general purpose bundler, use `esbuild` which supports Deno natively.

Also duplicate of #6900.  Please search issues before opening new ones.
