### ISSUE TITLE
Repl exit bug

### ISSUE THREAD

**Issue by sigmaSd** [denoland/deno#16147]
This pr https://github.com/denoland/deno/pull/15981 have a bug

If you do the sequence:
- a
- ctrl-r
- a
- ctrl-c
- ctrl-r
- a
- ctrlc

The repl will exit on the second invokation of ctrlc, its because ctrl-r doesn't reset should-break flag, and I think you will need to hook into rustyline internal to this correctly

node does this correctly

My personal++ opinion is to revert that pr until this is fixed because it makes the user easily quits the repl unintentionally , or not added it at all because all mainstream repls except node don't quit on ctrlc

![image](https://user-images.githubusercontent.com/22427111/193756346-18bb3125-f7be-4a9f-a1e4-6b65a70d5689.png)

**Comment by bartlomieju** [comment]
CC @dsherret

**Comment by sigmaSd** [comment]
I guess I just need to get used to stop the search with Escape instead of ctrl-c

**Comment by bartlomieju** [comment]
@sigmaSd maybe you could try to fix it?

**Comment by sigmaSd** [comment]
The problem is that ctrl-r (to call history) calls code inside rustyline, so you can not reset should_break flag https://github.com/denoland/deno/blob/main/cli/tools/repl/mod.rs#L94

I don't think this is a big deal, I can close the issue if you agree, otherwise I need to first figure out how should I approach this, I'll try to peek at rustlyine code again to see if there is something to do

**Comment by sigmaSd** [comment]
Maybe its possible to use custom key bindings since it would give a place to reset the flag, this might work but I'm not sure if rustyline allows overriding default one though

**Comment by sigmaSd** [comment]
Yep its possible to override, I'll try open a pr with this idea later
