### ISSUE TITLE
Implement new Writable Files API

### ISSUE THREAD

**Issue by ry** [denoland/deno#1615]
https://wicg.github.io/writable-files/

**Comment by nayeem-rahman** [comment]
I think this was replaced by https://wicg.github.io/native-file-system/

**Comment by nayeemrmn** [comment]
@ry Close in favour of #2456?

**Comment by lucacasonato** [comment]
@ry Just pinging this again. Close in favour of #2456? The writable files API was renamed to the native file system API.
