### ISSUE TITLE
[feat] deno bundle --only-pattern

### ISSUE THREAD

**Issue by loynoir** [denoland/deno#16150]
For example, `deno bundle --only-pattern '^file:\/\/.*foobar'` will not bundle
- `import.meta.url` like 'https://xxx'
- `import.meta.url` on local filesystem without `foobar`

Also below maybe handy.
```
$ cd /path/to/foo/

# this only bundle file path start with /path/to/foo/
# things like `https://esm.sh/xxx' are excluded
$ deno bundle --dev
```

**Comment by kitsonk** [comment]
`deno bundle` is not designed to be a general purpose bundler.  In it current form it is likely not to exist into the future (see: #15463).  We are not really considering new features for it at this point.  If you want a general purpose bundler, use `esbuild` which supports Deno natively.
