### ISSUE TITLE
(question) is possible copy/transfer a Deno.Conn from a main.ts to a worker.ts?

### ISSUE THREAD

**Issue by danieagle** [denoland/deno#16159]
Hi!

I'm trying copy/transfer a Deno.Conn from a main.ts to worker.ts.
this is possible ?
i tried but unsuccess... are there some means to do this ?

from main.ts postMessage(connection_accepted);
connection_accept var in worker arrive without be serialized or copied
just a blank object...

my doubt is: is possible transfer/serialize a Deno.Conn from a main.ts to  worker.ts ?

Very Very Very Thanks!
GrateFull, Dani.

obs.: worker.ts is a Web Worker  started by main.ts.

**Comment by bartlomieju** [comment]
No, it's not possible to transfer a connection to a worker.
