### ISSUE TITLE
Running DB migration using npm: import throws `module evaluation is still pending`

### ISSUE THREAD

**Issue by GJZwiers** [denoland/deno#16156]
I want to apply a Postgres database migration using a package from npm that is imported with an `npm:` specifier. When I try to run the program, Deno hangs for about a minute and then throws: `error: Module evaluation is still pending but there are no pending ops or dynamic imports. This situation is often caused by unresolved promises.` In Node the same program works and applies the migration.

`migrate.mjs`:
```js
import { migrate } from "npm:postgres-migrations";

async function apply() {
  const dbConfig = {
    database: "deno",
    user: "postgres",
    password: "yes",
    host: "localhost",
    port: 5432,
    ensureDatabaseExists: true,
    defaultDatabase: "deno",
  };

  await migrate(dbConfig, "migrations");
}

await apply();
```

Aside from this I have a `1_testmigration.sql` file  in a `migrations` folder that contains a create table statement, and a Postgres 14 server running on localhost port 5432.

```sql
CREATE TABLE users(ID INT PRIMARY KEY NOT NULL);
```

```
deno --version

deno 1.26.0 (release, x86_64-pc-windows-msvc)
v8 10.7.193.3
typescript 4.8.3
```

**Comment by GJZwiers** [comment]
It looks like this might be caused by the `pg` package dependency because running that in isolation also hangs and then throws an error

```js
import pg from 'npm:pg';
const client = new pg.Client()
await client.connect();
```

```
error: Uncaught Error: Connection terminated unexpectedly
    at Connection.<anonymous> (file:///C:/Users/GJZwiers/AppData/Local/deno/npm/registry.npmjs.org/pg/8.8.0/lib/client.js:132:73)ib/client.js:132:73)
    at Object.onceWrapper (https://deno.land/std@0.159.0/node/_events.mjs:502:28)
    at Connection.emit (https://deno.land/std@0.159.0/node/_events.mjs:379:28)
    at Socket.<anonymous> (file:///C:/Users/GJZwiers/AppData/Local/deno/npm/registry.npmjs.org/pg/8.8.0/lib/connection.js:57:12)
    at Socket.emit (https://deno.land/std@0.159.0/node/_events.mjs:379:28)
    at https://deno.land/std@0.159.0/node/net.ts:1424:14
    at deno:core/01_core.js:240:9
```

**Comment by bartlomieju** [comment]
@GJZwiers could you try again? You should get a better error message this time pointing to the problematic promise.

**Comment by GJZwiers** [comment]
Now I got:
```
error: Top-level await promise never resolved
await apply();
^
    at <anonymous> (file:///C:/Users/GJZwiers/repos/deno_pg/migrate.mjs:17:1)
```

Which is true but the real issue is a Promise not resolving that is deeper in the code. I debugged with `--node-modules-dir` and found that the reason for not resolving is because of a call to `pg.Client.connect` on [this line](https://github.com/ThomWright/postgres-migrations/blob/master/src/with-connection.ts#L12). So I guess the issue is definitely with the `pg` package.

**Comment by GJZwiers** [comment]
So the `pg` module actually works but I did not call `await client.end()` :/ this just returns `Hello world!` for example:

```js
import pg from 'npm:pg';
const client = new pg.Client({
    user: 'postgres',
    password: '<mypassword>',
});
await client.connect();

const res = await client.query('SELECT $1::text as message', ['Hello world!'])
console.log(res.rows[0].message) // Hello world!

await client.end();
```


`postgres-migrations` also works after I dropped and recreated my test database. I'm not sure what I did to break it the last time.
