### ISSUE TITLE
Failed to run deno if module is under `/tmp`

### ISSUE THREAD

**Issue by IWANABETHATGUY** [denoland/deno#16186]
1. If I use absolute path in `home` dir, entry thing goes fine
![image](https://user-images.githubusercontent.com/17974631/194463885-135072ec-feb3-4f6a-9d56-015b80491acd.png)
 
here is the shell history 
```
deno run --no-check --allow-net /home/victor/Documents/test-dir/test.js
cat test.js
deno run --no-check --allow-net test.js
vim test.js
touch test.js
```

2. If I try to run a module in `/tmp` dir, it goes failed.

![image](https://user-images.githubusercontent.com/17974631/194464067-2e2b5be6-23aa-492e-8002-49f3f1f99c42.png)

```
deno run --no-check --allow-net /tmp/test.js
cat /tmp/test.js
vim /tmp/test.js
vim /tmp/test.jsw
touch /tmp/test.js
```

**Comment by IWANABETHATGUY** [comment]
OS: Linux 
ubuntu22.04

**Comment by magurotuna** [comment]
@IWANABETHATGUY
I followed what you did on Ubuntu 20.04 but mine just worked fine.
Could you show the output of `deno --version`?

**Comment by magurotuna** [comment]
thank you for the additiona info. Hmm it is weird. I'll try the procedure on the completely same environment (i.e. ubuntu 22.04)

**Comment by magurotuna** [comment]
I checked on my ubuntu 22.04 LTS environment and can confirm that it works with no problem. Here's a capture:

<img width="803" alt="image" src="https://user-images.githubusercontent.com/23649474/195579561-bcdacfb5-882e-4c93-a7ed-c0685fb587d1.png">

Could you show me the output of `ls -l /tmp | grep test.js` and `ls -l $(which deno)`? @IWANABETHATGUY

**Comment by lucacasonato** [comment]
Closing as this is due to snap. We recommend you install using the recommended installation instructions on the website.
