### ISSUE TITLE
resolution for relative import inside a npm packages is not compatible with node

### ISSUE THREAD

**Issue by khuongduybui** [denoland/deno#16185]
Let's say we have an npm package `foo` with the following structure:

```
foo/
  lib/
    index.js
  index.js
  package.json
  util.js
```

And let's say `index.js` starts with the following imports:

```js
import "./util"; // should resolve to ./util.js
import "./lib"; // should resolve to ./lib/index.js
```

When importing that package into deno via `import "npm:foo"`, the two imports from `foo/index.js` will throw errors.

**Comment by khuongduybui** [comment]
Thanks @dsherret for the clarification. I'll contact the package maintainer.

**Comment by dsherret** [comment]
Maybe there is something else wrong here. Does that package work in Node?

**Comment by khuongduybui** [comment]
Yes it works fine in nodes. The package I'm talking about in particular is `@cloudscape-design/components`
