### ISSUE TITLE
Deno.stdin.read() fails with OS error 6 on Windows 7

### ISSUE THREAD

**Issue by jmoalves** [denoland/deno#16195]
This issue is related to https://github.com/denoland/deno/issues/5943.

This issue happens only on Windows 7.
The problem **does not** happen on Windows 10+.

![deno-read-osError6-win7](https://user-images.githubusercontent.com/15057966/194584455-b90ed25d-24b7-436d-96d0-7aa5563190a1.png)

----

The easiest way to reproduce this:

## Deno 1.26.1+
```
deno run --unstable https://deno.land/x/cliffy@v0.25.2/examples/prompt/prompt_list.ts
```

## Deno 1.23.3+
```
deno run --unstable https://deno.land/x/cliffy@v0.25.1/examples/prompt/prompt_list.ts
```

## Deno 1.23.2

Using Deno 1.23.2 the problem does not happen:
```
deno run --unstable https://deno.land/x/cliffy@v0.25.1/examples/prompt/prompt_list.ts
```

**Comment by dsherret** [comment]
FWIW, Windows 7 has been end of life since January 2020. Additionally, people can only purchase extended security updates until 2023. People shouldn't be using Windows 7 or at least really shouldn't after 2023 and they can no longer purchase security updates.

**Comment by jmoalves** [comment]
Yeah, I know. However, we need to support Windows 7 for a while.

We've opened the issue because something changed from Deno 1.23.2 to 1.23.3 that broke the `setRaw` (or `read`) code.

Perhaps "broke" is not the right word since everything works with Windows 10+.

**Comment by jmoalves** [comment]
Abandoning Windows 7 and this issue
