### ISSUE TITLE
Support importMap from remote URL

### ISSUE THREAD

**Issue by jollytoad** [denoland/deno#16193]
There appears to be an inconsistency between the `importMap` in `deno.json` and the `--import-map` cli arg.

`--import-map` allows a remote URL to be specified, but the `importMap` option does not.

Setting `importMap` gives an error similar to the following:

```
error: Unable to load 'file:///Users/xxx/xxx/https:/example.com/import_map.json' import map
```

but `--import-map` with the same URL work fine.

I'd expect the `importMap` to also accept a URL, and for the Deno VSCode extension and other tooling to respect the URL too.

**Comment by jollytoad** [comment]
I get the impression from #12800 that URLs were intended to be supported in `importMap`, and even the initial PR seems to support that, but I'm struggling to follow from that point in time. I can't find in the codebase where `importMap` and `--import-map` are actually used to read the import map itself.

**Comment by dsherret** [comment]
It seems to not handle it here https://github.com/denoland/deno/blob/cc3e2b9b1a7ccd6c671bc0b3813cf7e2b0d88b5c/cli/args/mod.rs#L422-L446

**Comment by jollytoad** [comment]
Thanks @dsherret, I might have a bash as fixing this then, as my first foray into rust!
I've installed rust, built deno from source, and managed to create a failing test for the bug, so looking good so far 👍

**Comment by jollytoad** [comment]
So I'm thinking the logic should be, if the `import_map_path` looks like an absolute URL, use it as, otherwise fallback to the existing logic (at 429)?

**Comment by dsherret** [comment]
@jollytoad yup. I think `ModuleSpecifier::parse(import_map_path)` returns `Ok(url)` then you can return that.

**Comment by jollytoad** [comment]
I've noticed there is an inconsistency here though.

If you have `"importMap": "import_map.json"` in a local config it works, but if you have that in a remote config it will fail.

I think either `importMap` should be treated purely as URL, ie. so it must be specified with `./` (like a module specifier), or the same special case is applied if it appear to be 'bare' (ie. not a valid absolute URL).

So the logic (for both local and remote configs) could be:

If it's not a valid URL (relative or absolute), then just prefix it with `./` and use `deno_core::resolve_import`.

Or, should it just fail?

**Comment by jollytoad** [comment]
Anyway, I've gone for the simplest, most backward compatible fix for now, of just checking if its an absolute URL, and then falling back to the original file path resolution.
