### ISSUE TITLE
error: Uncaught (in promise) TypeError: Unsupported scheme "node" for module "node:XXX"

### ISSUE THREAD

**Issue by Kycermann** [denoland/deno#16223]
**Single step to reproduce**

Run this command (revised command courtesy of AnInternetTroll):
```bash
deno eval --unstable 'import "npm:assemblyscript/asc"'
```

Error output:
```
error: Uncaught (in promise) TypeError: Unsupported scheme "node" for module "node:module". Supported schemes: [
    "data",
    "blob",
    "file",
    "http",
    "https",
]
    at async file:///home/codespace/.cache/deno/npm/registry.npmjs.org/assemblyscript/0.21.6/dist/asc.js:7:6221
```

This is because the module in question does `import 'module'` which I believe Deno translates to `import 'node:module'` ("module" being an actual Node module- confusing haha).

I've tried this in Github Codespaces (`deno 1.26.1+a622c5d (canary, x86_64-unknown-linux-gnu)`)

**Comment by AnInternetTroll** [comment]
Same error on `linux 5.15.59` and `deno 1.26.1+a622c5d`

**Comment by kedicesur** [comment]
I met this error with the `deno test` command while working on an AssemblyScript project. Obviously I had forgotten the `--allow-read` flag. Have you tried?

     deno eval --unstable --allow-read 'import "npm:assemblyscript/asc"'

**Comment by AnInternetTroll** [comment]
`deno eval` doesn't accept any `--allow-*` flags.
And if you put `import "npm:assemblyscript/asc"` in a file and run the file with `deno run --allow-read --unstable` then you should get the same error. At least I do on 1.28.1

**Comment by dotandimet** [comment]
Hi, I'm seeing the same sort of error messages when trying out deno's npm support (specifically, I'm trying to see how well it can do running [mojo.js](https://mojojs.org/)). The npm packages get parsed, but it chokes on imports with the `node:` specifier.

Even something as simple as this:

```
import { Stream } from 'node:stream';
```
 Causes `deno run` to throw the Unsupported scheme error
```
error: Unsupported scheme "node" for module "node:stream". Supported schemes: [
    "data",
    "blob",
    "file",
    "http",
    "https",
]
    at file....
```
The `node:` prefix is explicit in the file, not added while processing an npm package. I think deno should always try to handle that by loading its node API compatibility layer and not let it fall through to the module loader.

**Comment by bartlomieju** [comment]
@dotandimet could you please provide a minimal reproduction to that error you're getting?

**Comment by JonathonRP** [comment]
I am getting this error using vite and demo with --node-modules-dir flag

**Comment by bartlomieju** [comment]
@JonathonRP can you share your project with commands to run it? This is still on our radar, but is blocked by https://github.com/denoland/deno/pull/16748.

**Comment by JonathonRP** [comment]
@bartlomieju, https://github.com/JonathonRP/JonathonRP.github.io/tree/Feature/SvelteKit.
Please use codespaces and run the command - 'deno task dev' in the terminal of codespace.
- let me know if you can't use codespace; I haven't done this before.

**Comment by JonathonRP** [comment]
@bartlomieju, this is still a problem please check the repo I provided and let me know. This is a big blocker for me to use deno with vite

**Comment by bartlomieju** [comment]
> @bartlomieju, this is still a problem please check the repo I provided and let me know. This is a big blocker for me to use deno with vite

As pointed before, this is blocked by #16748. Without I'm not sure we can support it. I might take a stab it after New Year.
