### ISSUE TITLE
Can not install canary on aarch64 macOS

### ISSUE THREAD

**Issue by Kycermann** [denoland/deno#16221]
Version: macOS Monterey 12.6

```
ME ~ % deno upgrade --canary
Looking up latest version
Found latest version a622c5df27e908bff152ce7374c47dabfdba0bba
Checking https://dl.deno.land/canary/a622c5df27e908bff152ce7374c47dabfdba0bba/deno-aarch64-apple-darwin.zip
Download could not be found, aborting
```

**Comment by crowlKats** [comment]
We currently don't support canary builds on M1

**Comment by crowlKats** [comment]
we probably should display an error in this scenario

**Comment by crowlKats** [comment]
M1 release builds are build manually as there are no M1 github runners, so having someone build M1 canary builds wouldnt really be feasible

**Comment by ydoi** [comment]
https://github.com/denoland/deno/blob/main/cli/tools/upgrade.rs#L20
To display error, will it check if TARGET is M1 and bail?

**Comment by crowlKats** [comment]
> To display error, will it check if TARGET is M1 and bail?

yes

**Comment by crowlKats** [comment]
> Ah, looks like this might mean some support? [github/roadmap#528](https://github.com/github/roadmap/issues/528)

probably, however unsure how long it will take to get such runners, so for now adding an error would be favourable

**Comment by ydoi** [comment]
Thanks, Can I take this one?

**Comment by crowlKats** [comment]
sure
