### ISSUE TITLE
bug: `console.log` does not print all elements of sparse arrays

### ISSUE THREAD

**Issue by KnorpelSenf** [denoland/deno#16226]
It seems that as soon as a sparse array contains more than a single consecutive hole, all subsequent values and holes are omitted.

```sh
$ deno
Deno 1.26.1
exit using ctrl+d, ctrl+c, or close()
> [1, 2, 3, , 5]
[ 1, 2, 3, <1 empty item>, 5 ]
> [1, 2, 3, , , 6]
[ 1, 2, 3, <2 empty items> ]
> console.log(_)
[ 1, 2, 3, <2 empty items> ]
undefined
> 
```

This not only happens in the repl but also when doing `console.log` from a script.

**Comment by cjihrig** [comment]
Do the changes in https://github.com/denoland/deno/pull/16204 fix the issue for you? Note, you'd have to build Deno from source with that change to try it out.

**Comment by KnorpelSenf** [comment]
I'm currently not able to build the entire runtime on my machine, I'm afraid I'll have to leave the review to someone else.
