### ISSUE TITLE
Panics on deno test

### ISSUE THREAD

**Issue by vladrose** [denoland/deno#16257]
Test should throw simple error, but it panics right before
<img width="704" alt="image" src="https://user-images.githubusercontent.com/24589019/195510337-614a7c22-7cf3-46e0-be32-13b308bcafc3.png">
<img width="682" alt="image" src="https://user-images.githubusercontent.com/24589019/195510893-ec74bc62-0ac8-45d0-b7fe-8b12e649d0a8.png">

Platform: macos x86_64
Version: 1.25.1
Args: ["/usr/local/bin/deno", "test", "--allow-read", "--allow-write", "--allow-net", "--allow-env", "--unstable", "--trace-ops", "./test/index.test.ts"]

thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Bad resource ID', ext/websocket/lib.rs:486:52
stack backtrace:
   0:        0x10c1e9149 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h85521558a183f368
   1:        0x10b790d8b - core::fmt::write::h01631fae0d2b98bc
   2:        0x10c1b9f68 - std::io::Write::write_fmt::h675dde99a2999169
   3:        0x10c1edf3d - std::panicking::default_hook::{{closure}}::h5e5df492d229fd65
   4:        0x10c1edc24 - std::panicking::default_hook::h18647b59f1a84ee2
   5:        0x10b70326b - deno::setup_panic_hook::{{closure}}::h92c4da2c5f40e0fc
   6:        0x10c1eea8b - std::panicking::rust_panic_with_hook::hd9ead35a68ccc55e
   7:        0x10c1ee904 - std::panicking::begin_panic_handler::{{closure}}::h6fca91c5e1dc2f30
   8:        0x10c1ee879 - std::sys_common::backtrace::__rust_end_short_backtrace::h4ff3025d9a0a0490
   9:        0x10c1ee835 - _rust_begin_unwind
  10:        0x10d5e7893 - core::panicking::panic_fmt::h3d9f795ee387ef8d
  11:        0x10d5e7af5 - core::result::unwrap_failed::haca1aa19e4c34aab
  12:        0x10becd30f - deno_websocket::op_ws_next_event::call::{{closure}}::he25cd7f44e393a7a
  13:        0x10bec6c23 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::ha47ff1ff5c8370a6
  14:        0x10b8bcbf1 - deno_core::runtime::JsRuntime::poll_event_loop::h41d91a8b6c0d895e
  15:        0x10b5b95db - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hef0811c1f73b85e2
  16:        0x10b54484d - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h27dc7e9a2d669a5e
  17:        0x10b496afd - tokio::runtime::task::raw::poll::h031e6bc97b8e5794
  18:        0x10c357412 - std::sys_common::backtrace::__rust_begin_short_backtrace::hf7b87415bd7eb7dc
  19:        0x10c3571c2 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h77859be565d69a2a
  20:        0x10c1f1489 - std::sys::unix::thread::Thread::new::thread_start::hf7c5ae502e9a7ed8
  21:     0x7ff8199c74e1 - __pthread_start

**Comment by dsherret** [comment]
Could you please try in the latest version? Also, could you provide reproduction steps?

**Comment by bartlomieju** [comment]
I'm gonna close this issue for now. Feel free to reopen if you can still repeat the problem.
