### ISSUE TITLE
Port-state-related Utilities

### ISSUE THREAD

**Issue by harrysolovay** [denoland/deno#16261]
I'm in need of two utilities:

1. to return whether a given port is available
2. to returns an open port

Open source implementations of a `isAvailablePort` and `getAvailablePort` look similar to the following:

```ts
function isAvailablePort(port: number): boolean {
  try {
    const listener = Deno.listen({
      transport: "tcp",
      hostname: "127.0.0.1",
      port,
    });
    listener.close();
    return true;
  } catch (_e) {
    return false;
  }
}


const MIN_PORT = 49152;
const MAX_PORT = 65534;
export function getAvailablePort(): number {
  let randomPort: number;
  do {
    randomPort = Math.floor(Math.random() * (MIN_PORT - MAX_PORT + 1) + MIN_PORT);
  } while (!isAvailablePort(randomPort));
  return randomPort;
}
```

Both of these approaches are less than ideal. `isAvailablePort` try/catches on an attempted `Deno.listen`... not sure why the port's state wouldn't be accessible without such a measure. Meanwhile `getAvailablePort` uses `Math.random` and a while loop; this code brushes off the (albeit very low) likelihood of repeat numbers and all ports within the range being occupied. While this may work, it's not exactly *clean code*.

Is there a better way to implement these utilities?

**Comment by littledivy** [comment]
Pass `0` as port to `Deno.listen` and it will allot you one.

**Comment by harrysolovay** [comment]
You are the absolute best! Thank you @littledivy.
