### ISSUE TITLE
Deno bench is flaky due to usage of same HTTP ports

### ISSUE THREAD

**Issue by aapoalas** [denoland/deno#16275]
CI bench run may flake out from using the same HTTP ports for different tests. At least port 4544 seems to be used for these two tests:
1. `cli/bench/http/deno_http_flash_ops_spawn.js `
2. `core/examples/http_bench_json_ops.rs`

Failed actions include at least:
* https://github.com/denoland/deno/actions/runs/3248010142/jobs/5328727229
* https://github.com/denoland/deno/actions/runs/3244266366/jobs/5320207896
* https://github.com/denoland/deno/actions/runs/3248913923/jobs/5331028242
* https://github.com/denoland/deno/actions/runs/3251439769/jobs/5336428668

Additionally: When bench fails like this it dumps out the entire `deno bundle` output to the log which is blatantly unhelpful and makes the log too large for GitHub log browser. Only viewing the raw logs makes it possible to find the actual error.

**Comment by lucacasonato** [comment]
We shouldn't be running two benches at the same time, so how can this result in flakyness?

**Comment by aapoalas** [comment]
I don't know, but it does. That port is used by two benches whereas all the other HTTP ports (used ports seem to be 4544-4567) are only used by a single bench.

This may possibly be related to https://github.com/denoland/deno/issues/16267
