### ISSUE TITLE
deno lint >log.txt is not work.

### ISSUE THREAD

**Issue by edu-sonya-cc** [denoland/deno#16270]
I want to use deno lint and output to text file, but it's not work.

In Windows 10, I created a bat file names "lint.bat" and type these statements:
@ECHO OFF

set timestamp=%date:~0,4%%date:~5,2%%date:~8,2%_%time:~0,2%%time:~3,2%%time:~6,2%
set timestamp=%timestamp: =0%
set log=lint_log_%timestamp%.txt

cd src
deno lint >..\%log%

PAUSE

**Comment by magurotuna** [comment]
`deno lint` outputs to stderr, instead of stdout. I'm not familiar with windows, but could you try this one and see if it works?

```
deno lint 2> ..%log%
```

**Comment by edu-sonya-cc** [comment]
> `deno lint` outputs to stderr, instead of stdout. I'm not familiar with windows, but could you try this one and see if it works?
> 
> ```
> deno lint 2> ..%log%
> ```

It's ok. Thanks!
