### ISSUE TITLE
Unable to run `rollup` as `rollup.config.js` doesn't resolve

### ISSUE THREAD

**Issue by MarkBennett** [denoland/deno#16280]
# Background
I'm working through the list of popular npm dependencies and trying to get each of their unit tests working. As part of that, I'm trying to get [mocha tests to run in deno using the steps here](https://github.com/mochajs/mocha/blob/master/.github/CONTRIBUTING.md). They're currently failing though, as I can't run rollup to build `mocha.js` for testing.

# Env
```bash
% deno --version
deno 1.26.1 (release, aarch64-apple-darwin)
v8 10.7.193.3
typescript 4.8.3
```

# Steps to reproduce
1. Clone [mocha](https://github.com/mochajs/mocha)

```bash
git clone https://github.com/mochajs/mocha.git
cd mocha
```

2. Inspect the `package-scripts.js` to see how the build works

```js
// package-scripts.js
module.exports = {
  scripts: {
    build: {
      script: `rollup -c ./rollup.config.js`,
      description: 'Build browser bundle'
    },
```

3. Try to run `rollup`

```bash
deno run  -A --unstable npm:rollup -c ./rollup.config.js
```

4. See the error:

```bash
% deno run  -A --unstable npm:rollup -c ./rollup.config.js                           
[!] TypeError: Could not resolve 'file:///Users/mark/sandbox/mocha/rollup.config.js' from 'file:///Users/mark/Library/Caches/deno/npm/registry.npmjs.org/rollup/3.1.0/dist/shared/loadConfigFile.js'.
TypeError: Could not resolve 'file:///Users/mark/sandbox/mocha/rollup.config.js' from 'file:///Users/mark/Library/Caches/deno/npm/registry.npmjs.org/rollup/3.1.0/dist/shared/loadConfigFile.js'.
    at async getConfigFileExport (file:///Users/mark/Library/Caches/deno/npm/registry.npmjs.org/rollup/3.1.0/dist/shared/loadConfigFile.js:587:17)
    at async Object.loadConfigFile (file:///Users/mark/Library/Caches/deno/npm/registry.npmjs.org/rollup/3.1.0/dist/shared/loadConfigFile.js:546:59)
    at async getConfigs (file:///Users/mark/Library/Caches/deno/npm/registry.npmjs.org/rollup/3.1.0/dist/bin/rollup:1678:39)
    at async runRollup (file:///Users/mark/Library/Caches/deno/npm/registry.npmjs.org/rollup/3.1.0/dist/bin/rollup:1655:43)
```

# Expected Behaviour

I would expect deno to handle this the same as `npx` does:

```bash
% npx rollup -c ./rollup.config.js                        

./browser-entry.js → ./mocha.js...
created ./mocha.js in 1.1s
```

**Comment by bartlomieju** [comment]
It seems rollup expect config file to be next to the local `node_modules` directory. Try specifying `--node-modules-dir` flag which will replicate default npm behavior

**Comment by MarkBennett** [comment]
> It seems rollup expect config file to be next to the local `node_modules` directory. Try specifying `--node-modules-dir` flag which will replicate default npm behavior

Good suggestion, thanks @bartlomieju! I tried it, but still no dice. :(

```bash
% rm -rf node_modules                                                                 
% deno run  -A --unstable --reload --node-modules-dir npm:rollup -c ./rollup.config.js
Download ⠹ https://deno.land/std@0.159.0/node/_crypto/crypto_browserify/asn1.js/encoders/pem.js                                                                                                                                                                                                                              [!] TypeError: Could not resolve 'file:///Users/mark/sandbox/mocha/rollup.config.js' from 'file:///Users/mark/sandbox/mocha/node_modules/.deno/rollup@3.1.0/node_modules/rollup/dist/shared/loadConfigFile.js'.
TypeError: Could not resolve 'file:///Users/mark/sandbox/mocha/rollup.config.js' from 'file:///Users/mark/sandbox/mocha/node_modules/.deno/rollup@3.1.0/node_modules/rollup/dist/shared/loadConfigFile.js'.
    at async getConfigFileExport (file:///Users/mark/sandbox/mocha/node_modules/.deno/rollup@3.1.0/node_modules/rollup/dist/shared/loadConfigFile.js:587:17)
    at async Object.loadConfigFile (file:///Users/mark/sandbox/mocha/node_modules/.deno/rollup@3.1.0/node_modules/rollup/dist/shared/loadConfigFile.js:546:59)
    at async getConfigs (file:///Users/mark/sandbox/mocha/node_modules/.deno/rollup@3.1.0/node_modules/rollup/dist/bin/rollup:1678:39)
    at async runRollup (file:///Users/mark/sandbox/mocha/node_modules/.deno/rollup@3.1.0/node_modules/rollup/dist/bin/rollup:1655:43)
```

**Comment by bartlomieju** [comment]
After some debugging it appears the problem is that there are insufficient permissions to load `package.json`, which suggests that it's the same problem as https://github.com/denoland/deno/issues/15845 (though the error could be better and show what's the problem).

**Comment by bartlomieju** [comment]
After more debugging - the first issue is the same as #15845, but there are still some quirks that when the file is loaded it's not treated as if it was a Node module, but rather imported as plain ES module (which means it will require `npm:` specifiers). I will check if that's desired behavior of should it actually be handled automatically by Deno.

**Comment by birkskyum** [comment]
With this resolved, I thought it was time to try this again:
- #15845

I used `--node-modules-dir` as recommended and the result appear to be success :)

```rust
➜ deno run  -A --node-modules-dir --unstable npm:rollup -c ./rollup.config.js

./browser-entry.js → ./mocha.js...
created ./mocha.js in 1.1s
```

**Comment by MarkBennett** [comment]
> With this resolved, I thought it was time to try this again:
> 
> * [npm: PermissionDenied: Reading package.json is not allowed when using npm:mocha@10.0.0 #15845](https://github.com/denoland/deno/issues/15845)
> 
> I used `--node-modules-dir` as recommended and the result appear to be success :)
> 
> ```rust
> ➜ deno run  -A --node-modules-dir --unstable npm:rollup -c ./rollup.config.js
> 
> ./browser-entry.js → ./mocha.js...
> created ./mocha.js in 1.1s
> ```

I can confirm this is also working for me on deno latest:

```
(base) mark@Marks-MacBook-Pro-2 mocha % deno --version
deno 1.39.1 (release, aarch64-apple-darwin)
v8 12.0.267.8
typescript 5.3.3
(base) mark@Marks-MacBook-Pro-2 mocha % deno run  -A --node-modules-dir --unstable npm:rollup -c ./rollup.config.js

./browser-entry.js → ./mocha.js...
created ./mocha.js in 1.1s
```

I'm good to confirm this is fixed if you want to close the issue @bartlomieju @birkskyum. Thanks for getting this working! :)

**Comment by bartlomieju** [comment]
Great, thanks for verifying!
