### ISSUE TITLE
Flags for subcommands are read together when scripting

### ISSUE THREAD

**Issue by ArchieSW** [denoland/deno#16311]
Hello, I have a simple executable script file:
```javascript
#!/home/archie/.deno/bin/deno run --allow-net

const link = /* here is some link */

fetch(link)
	.then(data => console.log(data));
```
**Expected:**
Correctly working program
**Actually:**
```bash
error: The subcommand 'run --allow-net' wasn't recognized

	Did you mean 'run'?

If you believe you received this message in error, try re-running with 'deno -- run --allow-net'

USAGE:
    deno [OPTIONS] [SUBCOMMAND]

For more information try --help
```
What am I doing wrong?

**Comment by AnInternetTroll** [comment]
[Check out the manual's example on how to use shebangs](https://deno.land/manual@v1.26.1/examples/shebang)

Basically anything after the space is treated as a single argument. So it's like typing `"deno" "run --allow-net" "file.ts"`. If you are on a GNU/Linux system or FreeBSD then you can use `#!/usr/bin/env -S deno run --allow-net` as your shebang as long as `deno` is in your PATH

**Comment by ArchieSW** [comment]
Thank you! It works!

> [Check out the manual's example on how to use shebangs](https://deno.land/manual@v1.26.1/examples/shebang)
> 
> Basically anything after the space is treated as a single argument. So it's like typing `"deno" "run --allow-net" "file.ts"`. If you are on a GNU/Linux system or FreeBSD or MacOS then you can use `#!/usr/bin/env -S deno run --allow-net` as your shebang as long as `deno` is in your PATH
