### ISSUE TITLE
`Deno.Reader` faster than `ReadableStream`

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno#16314]
I'm experimenting with interfacing with web streams to read data from a Redis server over `Deno.Reader`. I've found that web streams can be up to 90% slower, which surprised me. I initially assumed web streams would be far faster.

I'm aware that streams aren't yet optimised. However, @littledivy told me that streams should at least be at the same level as `Deno.Reader`/`Deno.Writer` in terms of performance. I'm opening this issue to study what performance improvements can be made around this and similar use cases.

Note: one must [install Redis](https://redis.io/docs/getting-started/installation/) for the snippet to work.

```ts
import { writeAll } from "https://deno.land/std@0.159.0/streams/conversion.ts";
import { BufReader } from "https://deno.land/std@0.159.0/io/buffer.ts";
import { TextLineStream } from "https://deno.land/std@0.159.0/streams/mod.ts";

await Deno.spawn("redis-server", { args: ["--daemonize", "yes"] });

const port = 6379;
const encoder = new TextEncoder();
const decoder = new TextDecoder();

/** Deno.Reader */
const redisConn1 = await Deno.connect({ port });
const bufReader = new BufReader(redisConn1);

Deno.bench({
  name: "buffer",
  group: "read",
  async fn() {
    await writeAll(redisConn1, encoder.encode("PING\r\n"));
    const { line } = (await bufReader.readLine())!;
    decoder.decode(line!);
  },
});

/** Web streams */
const redisConn2 = await Deno.connect({ port });
const streamReader = redisConn2.readable
  .pipeThrough(new TextDecoderStream())
  .pipeThrough(new TextLineStream())
  .getReader();

Deno.bench({
  name: "web streams",
  group: "read",
  async fn() {
    await writeAll(redisConn2, encoder.encode("PING\r\n"));
    await streamReader.read();
  },
});

addEventListener("unload", async () => {
  await writeAll(redisConn1, encoder.encode("SHUTDOWN\r\n"));
  redisConn1.close();
  redisConn2.close();
});
```

CC @littledivy

**Comment by crowlKats** [comment]
web streams are inherently slower than Deno.Reader, as Deno.Reader is just an interface with a read function, nothing more. Web streams on the other hand do all kind of handling, so as soon as you arent using optimized piping (by going to js for ie `TextLineStream` which is from std), you unsurprisingly will get a massive slowdown

**Comment by iuioiua** [comment]
Thanks, @crowlKats. That makes sense. Nevertheless, this is still a good study if Deno moves away from reader/writer-based I/O.

**Comment by littledivy** [comment]
piping through `TextDecoderStream` can be optimized by the 'fast web streams' project -> #16046

**Comment by iuioiua** [comment]
To be clear, can we ever expect the web streams implementation to surpass the `Deno.Reader` performance in the example I provided? Honest question.

**Comment by crowlKats** [comment]
Closing in favour of #16046
