### ISSUE TITLE
List of things to refactor

### ISSUE THREAD

**Issue by piscisaureus** [denoland/deno#1634]
* [ ] Rust resource table
    * Maybe make the type generic like `Resource<TcpScream>` 
    * Store box references in resource table instead of actual structs
  * [ ] Verify that async file ops are actually async
  * [ ] In deno_dir the difference between `code_fetch` and `get_source_code` is not obvious - they both return similar types.

**Comment by bartlomieju** [comment]
I think this is no longer relevant

CC @ry

**Comment by ry** [comment]
Closing - but the resource table still needs to be revisited
