### ISSUE TITLE
Deno bundle is hanging

### ISSUE THREAD

**Issue by soundstep** [denoland/deno#16341]
Hi,
I've created an issue there: https://github.com/ije/esm.sh/issues/434
I don't know if that's an issue with `deno bundle` or something else, `deno run` works just fine.
This command hangs:
```sh
deno bundle --reload https://gist.githubusercontent.com/soundstep/e8d70d979f6a0152a07ed215fe457c87/raw/c2013a79e12b57786fbc4a2966026aaee438f540/deno-pem-issue.ts mod.ts
```
Any advice?

**Comment by GJZwiers** [comment]
Are you still experiencing this issue on the latest version of Deno? I cannot reproduce it locally.

**Comment by jjoynson-iw** [comment]
Works for me now on Deno 1.29.3 🎉

**Comment by lino-levan** [comment]
Not only does this now work, `deno bundle` is deprecated. I believe this should be closed @kt3k.
