### ISSUE TITLE
Error outputs `errors` property

### ISSUE THREAD

**Issue by TomokiMiyauci** [denoland/deno#16340]
If the `Error` object has the `errors` property as an array and is thrown, it will output `errors` in the error message.

```ts
const e = Error()
e.errors = ["xxx"].
throw e
```

out:

```ts
error: Uncaught Error
    xxx
const e = Error()
          ^
```

This seems to have occurred since v1.21.0.
Probably related PR #14285

**Comment by bartlomieju** [comment]
If anyone wants to give it a try then here's roughly what should be done: `JsError::inner_from_v8_exception` should be changed to look for `errors` property on the object only if it is an `AggregateError` (or a subclass of it)
