### ISSUE TITLE
`CloseEvent` sometimes missing reason when using `WebSocket.close()`

### ISSUE THREAD

**Issue by apacheli** [denoland/deno#16358]
Sometimes the close reason is not included. This behavior is consistent given the two examples and the images included. Not sure if this has anything to do with the server as these are client disconnects.

### Example 1

```js
const w = new WebSocket("wss://gateway.discord.gg");

w.addEventListener("message", (event) => {
  console.log(event.data);
});

w.addEventListener("close", (event) => {
  console.log(event.code, event.reason);
});

setTimeout(() => w.close(3456, "manual close"), 5000);
```

![image](https://user-images.githubusercontent.com/43933794/196852460-92af0e97-264f-4c40-8439-0b8d2cd95f24.png)

### Example 2

```js
const w = new WebSocket("wss://demo.piesocket.com/v3/channel_1?api_key=VCXCEuvhGcBDP7XhiJJUDvR1e1D3eiVjgZ9VRiaV&notify_self");

w.addEventListener("message", (event) => {
  console.log(event.data);
});

w.addEventListener("close", (event) => {
  console.log(event.code, event.reason);
});

setTimeout(() => w.close(3456, "manual close"), 5000);
```

![image](https://user-images.githubusercontent.com/43933794/196852653-03106b5f-b2e9-45db-8756-46e9c1b1c709.png)

```
$ deno --version
deno 1.26.2 (release, x86_64-pc-windows-msvc)
v8 10.7.193.16
typescript 4.8.3
```

**Comment by crowlKats** [comment]
This is behaving correctly (you can try it in your browser). 
Discord is just deciding not to echo back the close reason, whereas the other service is.
