### ISSUE TITLE
lsp: should work with local node_modules directory

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#16373]
From https://github.com/denoland/deno/pull/16332

> LSP doesn't work with local node_modules directory since there's no configuration for this at the moment. I think we should consider making this an option in the deno.json file or perhaps it should detect if there's a node_modules folder and prefer to use that?

When we add suport for this we'll need to ensure it initializes the npm snapshot from the lockfile to ensure it resolves the same as on the command line (otherwise there will be a lot of churn in the node_modules folder).

**Comment by bartlomieju** [comment]
@dsherret is this issue still relevant?
