### ISSUE TITLE
Deno REPL imports stuck for wrong url

### ISSUE THREAD

**Issue by JOTSR** [denoland/deno#16381]
In REPL, importing a wrong url normally throw an error then indefinitely show download loader without possibility to continue.
![image](https://user-images.githubusercontent.com/58234376/197238329-d76cb08e-2a18-4603-bddf-cb26426be218.png)
New loader seem to disapeer only after dowloading and parsing comletion and don't correctly clear on error.
Same for dynamic imports
![image](https://user-images.githubusercontent.com/58234376/197239194-20b6b7dc-0b6e-44c9-958b-0d4839131660.png)
Correctly works after caching the url
![image](https://user-images.githubusercontent.com/58234376/197239459-d7009c15-c1ac-468a-a57a-8596a9e18d65.png)
Tested on deno (windows and linux) 1.26 and earlier

**Comment by magurotuna** [comment]
Go ahead 🚀
