### ISSUE TITLE
Error retrieving current directory

### ISSUE THREAD

**Issue by nwstetson** [denoland/deno#16393]
I am new to coding and have never reported a bug here before, but here is the data I got in the terminal for RStudio when trying to render a Quarto document. I have been having a lot if issues with getting R to work with directories leading up to this.

============================================================
'Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos x86_64
Version: 1.22.0
Args: ["/Applications/RStudio.app/Contents/MacOS/quarto/bin/tools/deno", "run", "--unstable", "--no-config", "--cached-only", "--allow-read", "--allow-write", "--allow-run", "--allow-env", "--allow-net", "--allow-ffi", "--no-check", "--importmap=/Applications/RStudio.app/Contents/MacOS/quarto/bin/vendor/import_map.json", "/Applications/RStudio.app/Contents/MacOS/quarto/bin/quarto.js", "preview", "Analyses.qmd", "--to", "html", "--no-watch-inputs", "--no-browse"]

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" }', core/module_specifier.rs:141:28
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace'

**Comment by magurotuna** [comment]
Could you upgrade to the latest version of Deno (v1.26.2) and try again?

**Comment by nwstetson** [comment]
I updated Deno and I believe it worked! Thank you!
