### ISSUE TITLE
 Uncaught SyntaxError: The requested module 'https://deno.land/std@0.53.0/http/server.ts' does not provide an export named 'Response'

### ISSUE THREAD

**Issue by gisborne** [denoland/deno#16404]
This suddenly is happening. I assume because of an automatic deno upgrade?

```
error: Uncaught SyntaxError: The requested module 'https://deno.land/std@0.53.0/http/server.ts' does not provide an export named 'Response'
  Response,
  ^
    at <anonymous> (https://deno.land/x/oak@v5.0.0/deps.ts:9:3)

Process finished with exit code 1
```

**Comment by cjihrig** [comment]
Which versions did you upgrade from and to? `std@0.53.0` is very old (May of 2020). I think the issue may be that `Response` is an interface in that old version of the file. In newer versions, `Response` is an available global.

**Comment by gisborne** [comment]
Turns out it was importing from an old version of oak.
