### ISSUE TITLE
sqlite ffi segmentation fault

### ISSUE THREAD

**Issue by exe-dealer** [denoland/deno#16413]
<img width="639" alt="image" src="https://user-images.githubusercontent.com/3988889/197800273-30c51bbc-ab55-4867-a044-031db0dcf7b1.png">

```javascript
import { Database } from "https://deno.land/x/sqlite3@0.6.1/mod.ts";
new Database(':memory:');
```

previous deno v1.26.1 works ok, but v1.26.2 causes segfault on linux

**Comment by DjDeveloperr** [comment]
Related: https://github.com/denoland/deno/issues/16348

**Comment by DjDeveloperr** [comment]
This has already been fixed btw
