### ISSUE TITLE
error: Module not found

### ISSUE THREAD

**Issue by fortheworld2017** [denoland/deno#16427]
```
import express from "npm:express";
const app = express();
app.get("/", (req: any, res:any) => {
  res.send("hello");
});

app.listen(3000);
```
I created simple deno application with npm package 
It's working with 
`deno run --unstable -A app.ts`
Also I compiled this application 
`deno compile --unstable -A app.ts`
But when I run app.exe, I got error "error: Module not found".

Here is my environment
```
deno 1.26.2 (release, x86_64-pc-windows-msvc)
v8 10.7.193.16
typescript 4.8.3
```
Please help me what is the best solution 
Thanks so much

**Comment by dsherret** [comment]
npm specifiers haven't been implemented for `deno compile` yet. I opened #16430 to show an error for now.
