### ISSUE TITLE
Deno cotton module problem

### ISSUE THREAD

**Issue by strannic123** [denoland/deno#16448]
Hello. I'm trying to install cotton in the project - according to the documentation, but an error is falling. I don't understand how to fix it. 
Windows 10
Deno 1.26.2 
=>  _deno install --allow-net --allow-read --allow-write -n cotton https://deno.land/x/cotton@v0.7.2/cli.ts_

Error
error: Uncaught SyntaxError: The requested module './levels.ts' does not provide an export named 'LevelName'
export { LogLevels, LevelName } from "./levels.ts";
                    ^
    at <anonymous> (https://deno.land/std@0.63.0/log/mod.ts:13:21)
I would appreciate any advice

**Comment by kitsonk** [comment]
You would need to raise an issue with the author of the tool (https://github.com/rahmanfadhil/cotton), not Deno itself.
