### ISSUE TITLE
Deno.UnstableRunOptions missing JSDoc Category

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#16453]
https://deno.land/api@v1.27.0?unstable=&s=Deno.UnstableRunOptions is missing a JSDoc category, meaning it gets listed as an orphan in the documentation.

**Comment by shogohida** [comment]
@kitsonk @dsherret 
Hi guys, can I work on this issue? I'm not sure what to write in the documentation so it would be nice if you can give me some advice too!

**Comment by dsherret** [comment]
@shogohida sure! These files...

- https://github.com/denoland/deno/blob/main/cli/dts/lib.deno.ns.d.ts
- https://github.com/denoland/deno/blob/main/cli/dts/lib.deno.unstable.d.ts

...have `@category` jsdoc tags on interfaces and functions. The `UnstableRunOptions` (found here https://github.com/denoland/deno/blob/5dea510b021d78a2c9b6aef9462ae6f4e0fd527a/cli/dts/lib.deno.unstable.d.ts#L980) is missing a `@category` jsdoc tag. It should probably have the same category as `RunOptions` (https://github.com/denoland/deno/blob/5dea510b021d78a2c9b6aef9462ae6f4e0fd527a/cli/dts/lib.deno.ns.d.ts#L3300)

**Comment by shogohida** [comment]
Thanks for your quick reply! I will try to make a pull request as soon as possible!

**Comment by shogohida** [comment]
There was a failure in tests but it seems it's not related to the change I made.... I made a pull request anyway

https://github.com/denoland/deno/actions/runs/3387314315/jobs/5627901054

**Comment by shogohida** [comment]
Hi @dsherret, I think my pull request is ready for review so please have a look when you have time!

**Comment by dsherret** [comment]
Sorry I missed it and thanks for the PR! I will merge it in a few hours after I'm done the current release.
