### ISSUE TITLE
Type 'typeof import("file://[...]/registry.npmjs.org/object-sizeof/1.6.3/index.d.ts")' has no call signatures.

### ISSUE THREAD

**Issue by Lesiuk** [denoland/deno#16458]
```
import sizeof from 'npm:object-sizeof';
console.log(sizeof({}))
```

Executing code above with typechecking enabled gives me
```
error: TS2349 [ERROR]: This expression is not callable.
  Type 'typeof import("file:///[...]/npm/registry.npmjs.org/object-sizeof/1.6.3/index.d.ts")' has no call signatures.
console.log(sizeof({}))
            ~~~~~~

```
index.d.ts contains 
`export default function sizeof<T>(object: T): number;`

**Comment by dsherret** [comment]
This is actually not a bug in Deno and the library is distributing incorrect types. For example, in Node with TypeScript the same thing happens:

![image](https://user-images.githubusercontent.com/1609021/198609150-d797898d-2c87-4b7d-a087-4006b0b0a9ff.png)

To fix this issue and be compatible with Node ESM and Deno ESM, the types for that library should change from:

```ts
export default function sizeof<T>(object: T): number;
```

To...

```ts
declare function sizeof<T>(object: T): number;

export = sizeof;
```

https://github.com/miktam/sizeof/blob/master/index.d.ts

Unfortunately until that's fixed you will need to do the following:

```ts
import sizeofImport from "npm:object-sizeof";

const sizeof = (sizeofImport as any);

console.log(sizeof({}));
```

**Comment by Lesiuk** [comment]
Thank you for explanation.
