### ISSUE TITLE
napi_get_typedarray_info takes wrong arguments

### ISSUE THREAD

**Issue by kriszyp** [denoland/deno#16452]
NAPI has landed! This is so awesome! Congratulations on getting this out, I know @littledivy and @bartlomieju put a ton of effort into this! It is really looking nice!

Ok, there are some bugs, of course :). The most definite and pronounced one I noticed is that the arguments for `napi_get_typedarray_info` are wrong. I think it was implemented roughly the same as `napi_get_buffer_info`, but it actually takes a completely different set of (and far more) arguments:
https://nodejs.org/dist/latest-v18.x/docs/api/n-api.html#napi_get_typedarray_info
And it is important to note that almost all the arguments to `napi_get_typedarray_info` are supposed to be optional; supplying a null to any of them should be properly handled and should just not attempt to output any data to the reference. I believe that may also be an issue with `napi_get_buffer_info`/`napi_get_arraybuffer_info` (should be able to supply null for the length reference).

There also seems to be an additional issue with `napi_get_buffer_info` (which maybe afflicts `napi_get_typedarray_info` too, but hard to know if it is wrong with the wrong args) in that I don't think it is returning the address of the view's offset, it just returns the address of the underlying `ArrayBuffer`. That is, if the buffer's view of the `ArrayBuffer` has a `byteOffset` of 1024, it should return an address/pointer that is 1024 greater than the address of the underlying `ArrayBuffer`'s address.

**Comment by bartlomieju** [comment]
Thanks for report @kriszyp, this should be released in Deno v1.29.4 or v1.30
