### ISSUE TITLE
lsp: Inlay hints option `suppressWhenArgumentMatchesName` meaning flipped

### ISSUE THREAD

**Issue by Seally** [denoland/deno#16468]
Deno version: 1.27.0
OS: Windows 10

With this VS Code configuration:

```json
{
    "deno.enable": true,
    "deno.inlayHints.parameterNames.enabled": "all",
    "deno.inlayHints.parameterNames.suppressWhenArgumentMatchesName": true
}
```

VS Code displays:
![image](https://user-images.githubusercontent.com/507710/198653849-d450801d-8523-4cff-996a-26d1e150d3fd.png)

But with the configuration:
```json
{
    "deno.enable": true,
    "deno.inlayHints.parameterNames.enabled": "all",
    "deno.inlayHints.parameterNames.suppressWhenArgumentMatchesName": false
}
```

It displays:
![image](https://user-images.githubusercontent.com/507710/198654351-c4594b0a-b8ee-4901-8423-9dd2078f8415.png)

I expect that when `suppressWhenArgumentMatchesName` is true that inlay hints when names match are suppressed, not the other way around.

I can't tell if this is a `vscode_deno` issue or an LSP issue, but since the related commit in the VS Code extension doesn't seem to do much except add preset entries, I'm posting it here.

**Comment by dsherret** [comment]
Looks like typescript uses the wording "includeInlayParameterNameHintsWhenArgumentMatchesName" so we need to flip these
