### ISSUE TITLE
bug: `deno bench` fails when importing `npm:ioredis` on v1.27.0

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno#16475]
The following script worked fine in v1.26.2. However, it fails since upgrading v1.27.0.

Script:
```ts
// deno bench -A --unstable x.ts
import Redis from "npm:ioredis";

const redis = new Redis();

Deno.bench({
  name: "test",
  async fn() {
    await redis.ping();
  },
});

addEventListener("beforeunload", () => {
  redis.disconnect();
});
```

Error:
```
asher@Ashers-MacBook-Air r2d2 % deno bench -A --unstable x.ts
Check file:///Users/asher/Documents/GitHub/r2d2/x.ts
error: TS2351 [ERROR]: This expression is not constructable.
  Type 'typeof import("file:///Users/asher/Library/Caches/deno/npm/registry.npmjs.org/ioredis/5.2.3/built/index.d.ts")' has no construct signatures.
const redis = new Redis();
                  ~~~~~
    at file:///Users/asher/Documents/GitHub/r2d2/x.ts:3:19
```

Platform:
```
deno 1.27.0 (release, aarch64-apple-darwin)
v8 10.8.168.4
typescript 4.8.3
```

**Comment by dsherret** [comment]
This is a case of ioredis not defining its types correctly. The same issue also occurs when using es modules in node when using this package:

![image](https://user-images.githubusercontent.com/1609021/198838191-4fad5c23-5b69-4f78-aba3-424bdf89c2f7.png)

There's an issue open in the repo here: https://github.com/luin/ioredis/issues/1642

A workaround is:

```ts
import RedisImport from "npm:ioredis";
const Redis = (RedisImport as any as typeof RedisImport["default"]);
```

It's a fairly common issue in typescript projects unfortunately (see https://github.com/denoland/deno/issues/16458 for another example).

**Comment by iuioiua** [comment]
Thank you, @dsherret! Very informative. To clarify, the fix was actually:
```ts
import RedisImport from "npm:ioredis";
const Redis = new (RedisImport as any as typeof RedisImport["default"]);
```
