### ISSUE TITLE
Deno Deploy not working, please check. 

### ISSUE THREAD

**Issue by ps6067966** [denoland/deno#16481]
![image](https://user-images.githubusercontent.com/26248740/198864566-68a5d74b-0513-4889-baee-1feb2c6e8f49.png)

**Comment by crowlKats** [comment]
std/hash doesnt exist anymore in 0.161.0, as it has been deprecated in previous std releases.

**Comment by ps6067966** [comment]
@crowlKats  

I know it is removed from 0.161.0 but why this deployment process is looking for the hash module? 
I just want to deploy a simple hello world program with deno deploy but it's not working.

**Comment by crowlKats** [comment]
> but why this deployment process is looking for the hash module?

either you are importing it directly, or a dependency of yours is.

**Comment by ayame113** [comment]
For anyone else running into this: the solution is in https://github.com/denoland/deno_std/pull/2818#issuecomment-1293395750
