### ISSUE TITLE
Benchmark page: execution time should be log-scale 

### ISSUE THREAD

**Issue by ry** [denoland/deno#1649]
[We recently had a major improvement in warm startup time](https://github.com/denoland/deno/commit/ee9c627cc5f92898d104e9359059b57354c9f83c) but because cold start up is displayed on the same benchmark plot, it's hard to see:

<img width="405" alt="screen shot 2019-01-30 at 12 11 16 pm" src="https://user-images.githubusercontent.com/80/52157736-4e5d5980-265f-11e9-9c96-3f5f933edec2.png">

This plot should be log-scale. I've made a start at it (diff here https://gist.github.com/ry/c4614c2fccc4d74a4292ce84addd111f) but needs more work.

**Comment by kt3k** [comment]
Seems resolved in #1694

**Comment by ry** [comment]
Yes, thanks.
