### ISSUE TITLE
Node Compat for WebTorrent in Deno

### ISSUE THREAD

**Issue by x7NFKCgJ** [denoland/deno#16490]
Deno v1.27.0 on Ubuntu 22.04.1 LTS

I am trying to run WebTorrent in Deno using the following command:
`deno run --allow-env --allow-ffi --allow-net --allow-read --allow-sys --unstable ./wt.js download 0E876CE2A1A504F849CA72A5E2BC07347B3BC957`

Content of wt.js:
`import "npm:webtorrent-cli/bin/cmd.js";`

It produces the following error:
`deno: symbol lookup error: /home/user/.cache/deno/npm/registry.npmjs.org/utp-native/2.5.3/prebuilds/linux-x64/node.napi.node: undefined symbol: uv_timer_init`

`uv_timer_init` appears to be from `libuv`, which Node uses: https://docs.libuv.org/en/v1.x/timer.html

It works on the same system using Node. Is it currently possible to make this work with Deno?

**Comment by littledivy** [comment]
libuv API won't work with Deno. libuv is in Node.js event loop implementation. Node-API already provides async_work and thread_safe_functions that work with Deno. I'd recommend creating an issue to remove libuv usage from webtorrent-cli.

**Comment by krishna-kush** [comment]
deno: symbol lookup error: /home/kay/Desktop/temp/ws/simple/node_modules/.deno/wrtc@0.4.7/node_modules/wrtc/build/Release/wrtc.node: undefined symbol: uv_is_closing

same error on wrtc module.
