### ISSUE TITLE
Bug: npm resolvers default export not working as expected

### ISSUE THREAD

**Issue by apollo79** [denoland/deno#16506]
Using the following code: 
```ts
import Ajv from "npm:ajv@8.11.0";

const ajv = new Ajv();
```

An error occurs:
```
This expression is not constructable.
Type 'typeof import("file:///<user>/deno/npm/registry.npmjs.org/ajv/8.11.0/dist/ajv")' has no construct signatures. deno-ts(2351)
```

Strangely enough Ajv has a property `default` which is the default export, so the following works:
```ts
import Ajv from "npm:ajv@8.11.0";

const ajv = new Ajv.default();
```

The same happens with `ajv-formats`:
This throws:
```ts
import Ajv from "npm:ajv";
import addFormats from "npm:ajv-formats";

const ajv = new Ajv.default();

addFormats.default(ajv);
```
But this works:
```ts
import Ajv from "npm:ajv";
import addFormats from "npm:ajv-formats";

const ajv = new Ajv.default();

addFormats.default(ajv);
```

**Comment by dsherret** [comment]
The same thing occurs with Node ESM importing this package, so this is not an issue in Deno. See here: https://github.com/ajv-validator/ajv/issues/2132

Related issues:

https://github.com/denoland/deno/issues/16458
https://github.com/denoland/deno/issues/16475
