### ISSUE TITLE
lsp - support autodiscovery of the lockfile

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#16510]

**Comment by bartlomieju** [comment]
Ref https://github.com/denoland/deno/pull/16498

**Comment by lino-levan** [comment]
https://github.com/denoland/deno/pull/16498 was merged, is there anything else that needs to be done for this issue to be resolved?

**Comment by bartlomieju** [comment]
Yes, it needs to be implemented in the LSP, that PR only affects other CLI command, but not the LSP.
