### ISSUE TITLE
Deno.hostname() returns empty string on some situation on windows

### ISSUE THREAD

**Issue by kt3k** [denoland/deno#16527]
On windows the following script prints an empty string (with canary):
```ts
console.log(Deno.hostname());
```

But the following script prints the correct hostname:

```ts
await fetch("https://example.com");
console.log(Deno.hostname());
```

There seems existing some precondition for `GetHostNameW` to working correctly ref: https://github.com/retep998/winapi-rs/issues/296

**Comment by dsherret** [comment]
Same thing happens to me.
