### ISSUE TITLE
Import/Cache non-ts files...

### ISSUE THREAD

**Issue by tracker1** [denoland/deno#16521]
Just thinking it could be useful to be able to do something like...

```typescript
import localFilePath from "cache+https://server/path/to/file.ext";
```

Where the file will be downloaded to the local cache directory, and the import statement will in effect have the local path to that cached file.  This could be useful for being able to download/store/cache wasm or dynamic libraries.

Not sure about build outputs, or other features... just thought it would be useful for creating localized bundles, or container images with the resource in place.  Also, not sure about the protocol itself, I know that npm is using an `npm;` protocol... again, just wanting to maybe get a discussion started.

If this if it's a dupe, feel free to reference any existing issue and close, I did a cursory search but didn't find one.

---

Edit: Thinking, may need to be somehow deterministic on usage of a platform/architecture specific instance... The usage above, definitely good for wasm, and if one doesn't mind pulling multiple versions of a library.  In the case of a .so/.dll/.dylib for linux/windows/mac would be potentially excessive... that said, still better than no solution at all.

```
cache[,platform[,arch]]+url

cache,linux,x86_64+https://some.server/path/to/file.so
```

If no match on the cache params for platform/arch, the value will be `undefined` ... this way the references for all can be imported, but only the actual one necessary will be loaded.

**Comment by bradenmacdonald** [comment]
I would love this. I use a wasm-based dependency from deno.land ([wasm_image_decoder](https://deno.land/x/wasm_image_decoder)) and have found two problems with using it in a Deno project: (1) it doesn't work offline, and (2) sometimes it causes a delay or even a random failure when starting to run the application or its test suite. In both cases, the reason is that deno doesn't cache the `.wasm` file like it does other dependencies.

Example from a recently flaky test failure that I saw:
```
error: (in promise) TypeError: error sending request for url (https://deno.land/x/wasm_image_decoder@v0.0.5/wasm/wasm_image_decoder_bg.wasm): connection error: unexpected end of file
    const { instance, module } = await load(await input, imports);
                                            ^
    at async mainFetch (deno:ext/fetch/26_fetch.js:247:14)
    at async fetch (deno:ext/fetch/26_fetch.js:464:9)
    at async init (https://deno.land/x/wasm_image_decoder@v0.0.5/wasm/wasm_image_decoder.js:292:45)
    at async https://deno.land/x/wasm_image_decoder@v0.0.5/mod.js:2:1
```

**Comment by bradenmacdonald** [comment]
Ah, there is actually a related discussion taking place at https://github.com/denoland/deno/issues/11918

**Comment by tracker1** [comment]
@bradenmacdonald cool, thanks... it's related, and this could cover both use cases, roughly.  But this is also for getting dll/so/dylib binary modules for ffi/deno/napi usage.  Though would probably mean it would need/download several different versions, when only the host os/arch is needed in practice.

**Comment by lucacasonato** [comment]
We are working on standardizing [import reflections](https://github.com/tc39/proposal-import-reflection) to allow things like this.
