### ISSUE TITLE
Maybe an error in webstream memory management? 

### ISSUE THREAD

**Issue by bjesuiter** [denoland/deno#16544]
Hi there, 
 
I want to write a library which is able to start a file download and return two readable streams, one for the files content and one for the download progress. 

## The context

The important function here is that `downstream` function in this file:  
https://github.com/codemonument/downstream/blob/main/lib/downstream.ts

For completeness: Here are the key parts: 

1. I get the fileResponse from fetch: `const fileResponse = await fetch(input, options);`
2. I get the readable Stream from the body: ` const responseStream = fileResponse.body;`
3. I clone the responseStream: `const [fileStream, fileStreamClone] = responseStream.tee();`
4. I transform the cloned stream into a progress stream via a `progressTransformer`: 

    ```ts
    const progressStream = fileStreamClone.pipeThrough(
        progressTransformer({ maxBytes: contentLength }),
     );
    ```

The progressTransformer is implemented like this:
https://github.com/codemonument/downstream/blob/main/lib/progressTransformer.ts
     
```
export function progressTransformer(
  { maxBytes, precision = 2 }: ProgressTransformerOptions,
) {
  let writtenBytes = new Big("0");
  const progressTransformer = new TransformStream<Uint8Array, string>({
    start() {},
    transform(chunk, controller) {
      writtenBytes = writtenBytes.plus(chunk.length);
      const progressPercent = writtenBytes
        .div(maxBytes)
        .times("100");
      controller.enqueue(progressPercent.round(precision).toString());
    },
    flush(controller) {
      controller.terminate();
    },
  });

  return progressTransformer;
}    
```

## The Problem 

My test looks like this: 

```ts
 await tc.step(`Reports Progress on big file (1GB) correctly`, async () => {
    const { progressStream, fileStream } = await downstream(File1GB);
    const progressEvents: string[] = [];
    const progressBar = new ProgressBar({ title: "downloading: ", total: 100 });

    for await (const progress of progressStream) {
      progressBar.render(Number.parseFloat(progress));
      progressEvents.push(progress);
    }

    await assertSnapshot(tc, progressEvents.length);
    // needs to be done to not crash deno test
    await drainStream(fileStream);
  });
```

This works like a charm, **but it has one problem: The whole 1 GB file will be held in memory!** 
I tried to avoid this by implementing drainStream(fileStream) like this: 

```ts
export async function drainStream(stream: ReadableStream): Promise<void> {
  await drainStreamToTempFile(stream);
}


export async function drainStreamToTempFile(
  stream: ReadableStream,
): Promise<void> {
  const tempFilePath = await Deno.makeTempFile();
  const tempFile = await Deno.open(tempFilePath, { write: true });

  // Draining a stream to a temp file tries to reduce memory usage on the deno test runner!
  await stream.pipeTo(tempFile.writable);

  // file closing not necessary, since pipeTo already closes the file
  // tempFile.close();
  await Deno.remove(tempFilePath);
}
```

**But when I observe the memory usage of my deno process, it still goes up to > 1 GB.**
This is probably due to the handling of the chunks inside the progress transformer, 
but at this point i'm a little stuck with how to test this and how to optimize :/

**Comment by lucacasonato** [comment]
You need to call `drainStream(fileStream)` in parallel with `for await (const progress of progressStream) {`. Right now the chunks get queued into `fileStream` until the progress stream is done, and only then do they get drained. I think you want to do this:

```ts
 await tc.step(`Reports Progress on big file (1GB) correctly`, async () => {
    const { progressStream, fileStream } = await downstream(File1GB);
    const progressEvents: string[] = [];
    const progressBar = new ProgressBar({ title: "downloading: ", total: 100 });

    // needs to be done to not crash deno test
    const promise = drainStream(fileStream);
    for await (const progress of progressStream) {
      progressBar.render(Number.parseFloat(progress));
      progressEvents.push(progress);
    }

    await assertSnapshot(tc, progressEvents.length);
    await promise;
  });

**Comment by IJsLauw** [comment]
@bjesuiter Did the above suggestion work for you? If so can you update your code?

If the downloading of larger files (larger then 4 gb) isn't supported as of yet, I don't see an advantage in swapping the regular download module for yours, since I won't be showing a progress bar, but do see a need in supporting of large download without letting the memory usage go up to much.

**Comment by bjesuiter** [comment]
Thank you for your reminder! 

Yes, downloading of more than 4 GB should work now, I'll elaborate further on your issue in my repo :)
