### ISSUE TITLE
[feat] more prettier and predictable name for `Deno.makeTempFile`

### ISSUE THREAD

**Issue by loynoir** [denoland/deno#16549]
```
$ deno
> await Deno.makeTempFile()
"/tmp/f471f8e7"
```

---
By the way, below code may not working correctly under deno due to related https://github.com/denoland/deno_std/issues/2841

```
$ node
> var{file}=require('tmp-promise')
undefined
> xx=await file()
{
  path: '/tmp/tmp-73616-zyXVcgekBDNq',
  fd: 22,
  cleanup: [Function: _cleanupCallback]
}
```

```js
import { withFile } from 'tmp-promise'

withFile(async ({path, fd}) => {
  // when this function returns or throws - release the file 
  await doSomethingWithFile(db);
});
```

**Comment by iuioiua** [comment]
@loynoir, could you elaborate on your suggestion?

**Comment by lucacasonato** [comment]
There is no concrete suggestion here. Feel free to re-open the issue if you can make your suggestion more concrete.

**Comment by loynoir** [comment]
@lucacasonato
@iuioiua 

### Expected
- `npm:tmp-promise` style
`/tmp/tmp-73616-zyXVcgekBDNq`

- linux command `mktemp` style
`/tmp/tmp.pfYVbaosFS`


### Actual
`Deno.makeTempFile` style
- `/tmp/f471f8e7`

### Suggestion
At least have something like `/tmp/tmp.f471f8e7` or `/tmp/tmp-f471f8e7`

**Comment by iuioiua** [comment]
Why?

**Comment by loynoir** [comment]
@iuioiua 

- Both `npm:tmp-promise` and linux `mktemp` use this pattern.
- Without predictable pattern, how should user cleanup tmpfile if deno exit accidentally before executing deletion?

**Comment by iuioiua** [comment]
Check out the API documentation [here](https://deno.land/api?s=Deno.makeTempFile). All you need to do is set the `prefix` option.

**Comment by loynoir** [comment]
Is there a good reason, by default, not using existing popular predictable pattern, which is good for sysadmin?
- `npm:tmp` weekly download 31,023,400
- AFAIK, every popular linux distro have `mktemp` by default

**Comment by iuioiua** [comment]
Frankly, there's no real need to do so by default, and a predictable pattern doesn't add any value. Again, the functionality you desire exists by setting the `prefix` option.
