### ISSUE TITLE
Error while building deno by cargo on termux

### ISSUE THREAD

**Issue by mahmood601** [denoland/deno#16543]
This error appeared after download deno 
error[E0308]: mismatched types
   --> /data/data/com.termux/files/home/.cargo/registry/src/github.com-1ecc6299db9ec823/v8-0.54.0/build.rs:251:18
    |
251 | fn platform() -> &'static str {
    |    --------      ^^^^^^^^^^^^ expected `&str`, found `()`
    |    |
    |    implicitly returns `()` as its body has no tail or `return` expression

For more information about this error, try `rustc --explain E0308`.
error: could not compile `v8` due to previous error
warning: build failed, waiting for other jobs to finish...
^[[23~    Building [============>            ] 492/895: broerror: failed to compile `deno v1.27.1`, intermediate artifacts can be found at `/data/data/com.termux/files/usr/tmp/cargo-installIcw9T8`
Any help, please! 🥺

**Comment by sigmaSd** [comment]
I think you need https://github.com/LukeChannings/deno-arm64

**Comment by mahmood601** [comment]
Thanks! But that not work it asks me to install deno from termux repo:
pkg install deno

**Comment by dsherret** [comment]
What operating system and architecture do you have? Looks like you are not using linux, mac, or windows? That's all we support https://github.com/denoland/rusty_v8/blob/cc7183d09f9ae94a167e2dad1190bb9ea500c883/build.rs#L251
