### ISSUE TITLE
deno-gyp

### ISSUE THREAD

**Issue by sh7dm** [denoland/deno#1654]
Idea: add something like `node-gyp` for native modules.

**Comment by kyranet** [comment]
You mean GN, right? We don't use GYP here.

There was a discussion about native modules during September-November or so but turned out unconclusive, but I definitely would like this support, the question is: how?

**Comment by benjamingr** [comment]
I personally think a big selling point is message-passing FFI like Ryan talked about in JSConf rather than having deno deal with the whole toolchain like Node has to

**Comment by kitsonk** [comment]
WASM would be ideal for some use cases, it certainly would be secure.  Additional external bindings though would be a problem, but that is the security problem with native extensions.

**Comment by benjamingr** [comment]
wasm sounds like an excellent extension point except for where additional system APIs are required.

**Comment by sh7dm** [comment]
@benjamingr ye, but my issue was especially for system apis such as OpenCL, CUDA, TensorFlow etc

**Comment by sh7dm** [comment]
@ry how soon #1325 will be done?

**Comment by bartlomieju** [comment]
With #2385 in progress can we close this issue? It seems to be a duplicate of #296.

CC @ry

**Comment by ry** [comment]
indeed - let's move the discussion to #296

**Comment by wenjoy** [comment]
#654 is also related. Just want to link them together.
