### ISSUE TITLE
Feature Proposal: Handling file permissions

### ISSUE THREAD

**Issue by omar2205** [denoland/deno#16548]
It's pointless if we have a security system and end up adding too many permissions because a single file (or library) wants a "read permission".

1. deno.json / import_map.json
```json
{
  "imports": {
    "dotenv": "https://deno.land/x/dotenv@v3.2.0/mod.ts"
  },
  "permissions": {
    "dotenv": ["allow-read"]
  }
}
```
2. Using the URL to give permissions
```ts
import { serve } from 'https://deno.land/std@0.140.0/http/server.ts?allow-net'
```
3. Using comments
```ts
import { config } from 'https://deno.land/x/dotenv/mod.ts'

// @deno-perm-allow-read loading .env file
config({ export: true })

// or

// @deno-perm-allow-net=10.0.0.13 only access this network
serve((_req) => {
  return new Response('Hello World!', {
    headers: { 'content-type': 'text/plain' }
  })
})
```

**Comment by sigmaSd** [comment]
I asked this question before, it's something that the maintainers want but its a huge amount of work if even possible

There is a new language that have something like this feature https://github.com/roc-lang/roc 
The permissions can be given even by function but it's all at compile time , so I think it's not as practical as deno runtime system but it's just very early to tell

**Comment by lucacasonato** [comment]
Duplicate of #12763
