### ISSUE TITLE
Do not ignore `noErrorTruncation` compiler option

### ISSUE THREAD

**Issue by filmaj** [denoland/deno#16568]
Thanks for a fantastic runtime 😄 

Did a quick search and found that the `noErrorTruncation` TS compiler option is ignored:

https://github.com/denoland/deno/blob/a189c5393e1b106687736635fea0b8aeca283826/cli/args/config_file.rs#L134

For more complex projects this makes life hard 😞 

Thoughts?

**Comment by dsherret** [comment]
Seems reasonable to allow this.
