### ISSUE TITLE
[feat] Deno LSP: support textDocument/declaration

### ISSUE THREAD

**Issue by andykais** [denoland/deno#16569]
I am using the deno lsp within neovim. Currently deno lsp implements
- `textDocument/definition`
- `textDocument/references`
- `textDocument/executeCommand`

All of these are useful commands, but deno currently lacks the api to tell you where a variable is declared. This is very handy for jumping around code. I am curious if there are blockers to implementing this functionality, or if it is just a fairly time consuming feature to add. In any case, this issue should at least serve as a means to measure how important this feature is to the community

**Comment by nayeemrmn** [comment]
@andykais Could you give a code example of where `textDocument/declaration` would expectedly give a different position then `textDocument/definition` and `textDocument/typeDefinition`? The embedded ts-server doesn't seem to have a corresponding API.

**Comment by lucacasonato** [comment]
Closing because no response from OP.
