### ISSUE TITLE
streaming doesn't work with Deno.serve

### ISSUE THREAD

**Issue by kt3k** [denoland/deno#16567]
Streaming response of large (>1MB) file doesn't seem working with `Deno.serve`.

If I put "data.txt" (>1MB) and run the following script, the response hangs in the middle.

```js
Deno.serve((_) => new Response(Deno.openSync("data.txt").readable));
```

**Comment by kt3k** [comment]
Another example (without fs involved):
```js
Deno.serve((_) => new Response(new ReadableStream({
  start(c) {
    for (const _ of Array(40)) {
      c.enqueue(new Uint8Array(50000).fill(97));
    }
    c.close();
  }
})));
```

If you curl `localhost:9000`, it hangs or shows `Malformed encoding found` error

**Comment by kt3k** [comment]
This seems like a regression. It didn't happen with 36307c45e95b599eb01bf53df161973a7ef8b58e, and started happening with 743fcc0668f553c7902c44b1f6a484db42c1cfd0

**Comment by kt3k** [comment]
reverting https://github.com/denoland/deno/pull/16284 looks solving the issue. @littledivy Do you think of any reason?

**Comment by littledivy** [comment]
@kt3k let's revert it, im not sure whats the reason.

**Comment by kt3k** [comment]
Ok. I'll make a revert PR with some test cases.
