### ISSUE TITLE
deno upgrade attempts to fetch non-existent version

### ISSUE THREAD

**Issue by cknight** [denoland/deno#16573]
While upgrading Fresh, I noticed a new version of Deno was out, so I attempted to upgrade that too, however this fails attempting to download 1.27.2 which doesn't appear to exist yet.
```
chris@chris-desktop:~/dev/deno/dev-tools$ deno task update
Task update deno run -A -r https://fresh.deno.dev/update .
A new release of Deno is available: 1.27.0 → 1.27.1 Run `deno upgrade` to install it.
The manifest has been generated for 4 routes and 5 islands.

chris@chris-desktop:~/dev/deno/dev-tools$ deno upgrade
Looking up latest version
Found latest version 1.27.2
Checking https://github.com/denoland/deno/releases/download/v1.27.2/deno-x86_64-unknown-linux-gnu.zip
Download could not be found, aborting
```

**Comment by bartlomieju** [comment]
Thanks for reporting, we just noticed this too. It's a timing issue between when the _all_ files are uploaded and available and when we bump information about latest version. We'll get it fixed for v1.28
