### ISSUE TITLE
JSON imports not strictly typed

### ISSUE THREAD

**Issue by aapoalas** [denoland/deno#16583]
JSON file imports are currently not strictly typed but are instead given loose types, mainly with arrays being typed as eg. `string[]` instead of `["param"]`.

The use case for a strict typing is two fold:
1. Going to a less-strict typing is always possible and relatively easy, as any such lesser type (interface or other) will necessarily already exist and can thus be referenced to, whereas going to a stricter type requires repeating the same data that was already in the JSON file.
2. Deno FFI's symbols API requires strict typing. For large-scale FFI projects the symbols object becomes unwieldy, and individual JSON files matching eg. source header files would make sense as a symbol declaration language.

**Comment by dsherret** [comment]
I'm not sure there's anything we can do here. Is there a typescript compiler option to make it more strict?

**Comment by aapoalas** [comment]
Ah yeah, sorry I only realised this after filing the issue as well. If Deno purely relies on TSC then there's nothing that can be done.

However, if there's a step where Deno gives the files to TSC, then it would be possible to change the files from plain JSON to equivalent .d.ts files. An NPM package named ts-json-as-const apparently works this way.

**Comment by ayame113** [comment]
FYI, it looks like https://github.com/microsoft/TypeScript/issues/32063 is related to this issue.

**Comment by dsherret** [comment]
> However, if there's a step where Deno gives the files to TSC, then it would be possible to change the files from plain JSON to equivalent .d.ts files. An NPM package named ts-json-as-const apparently works this way.

That will get tricky to do that in the runtime because some people might prefer the loose typings, so it's probably best to stay aligned with TypeScript.

It seems like https://github.com/microsoft/TypeScript/issues/32063 will be the way to go in the future if ever merged. Until then, I think the types for these could be code generated strict then you could assert the imported object to be those types.

I'm going to close this one for now because I don't think it's actionable since we should align with TypeScript.

**Comment by aapoalas** [comment]
> That will get tricky to do that in the runtime because some people might prefer the loose typings, so it's probably best to stay aligned with TypeScript.

Yup, definitely true.

> It seems like [microsoft/TypeScript#32063](https://github.com/microsoft/TypeScript/issues/32063) will be the way to go in the future if ever merged. Until then, I think the types for these could be code generated strict then you could assert the imported object to be those types.
> 
> I'm going to close this one for now because I don't think it's actionable since we should align with TypeScript.

Agreed.

**Comment by alexgleason** [comment]
I was so close to being able to do something truly magical, but "string is not assignable to 'one' | 'two' | 'three'"

```ts
import jsonSchema from 'https://raw.githubusercontent.com/jhass/nodeinfo/main/schemas/2.1/schema.json' assert { type: 'json'};
import { FromSchema } from 'npm:json-schema-to-ts';

type NodeInfo = FromSchema<typeof jsonSchema>; // TypeError because json import is not const

const nodeInfo: NodeInfo = {
  //
};
```

It would leverage Deno's strengths SO GOOD to be able to import a JSON Schema by its URL and use it directly as a TypeScript type with no other conversions. I hope TypeScript adds support for importing json as const.
