### ISSUE TITLE
Node compatibility mode documentation out of date

### ISSUE THREAD

**Issue by jonasb** [denoland/deno#16586]
I find the Node compatibility situation quite confusing. According to [Node Compatibility Mode](https://deno.land/manual@v1.27.1/node/compatibility_mode) it's still in v 1.27.1.

However, in the [release notes for v1.25.2](https://github.com/denoland/deno/releases/tag/v1.25.2) `--compat` has been removed. From what I understand that implies that the whole Node compatibility mode is removed.

If I try to run with `--compat` on v 1.27.1 I get an error:

```
deno run --compat --unstable test.ts
error: Found argument '--compat' which wasn't expected, or isn't valid in this context

	If you tried to supply `--compat` as a value rather than a flag, use `-- --compat`

USAGE:
    deno run [OPTIONS] <SCRIPT_ARG>...

For more information try --help
```

**Comment by lino-levan** [comment]
You're on outdated documentation, it was recently overhauled. `--compat` was removed in `v1.25.2` in favor of npm specifiers.

You can find the current version here: https://deno.land/manual@v1.27.2/node/npm_specifiers

**Comment by dsherret** [comment]
We did a complete manual rewrite lately. As noted in the previous comment, that information is now updated and will be updated further for v1.28.
