### ISSUE TITLE
run `python -u ./build.py --use_ccache` got error may be caused by gsutil do not respect proxy settings

### ISSUE THREAD

**Issue by V-Tom** [denoland/deno#166]
Sorry for open this issues.

>  I install it according to this [docker file](https://github.com/maxmcd/deno-docker/blob/master/Dockerfile) same as ry's [compile instructions](https://github.com/ry/deno#compile-instructions)

> I had already set `http_proxy` and `https_proxy` in my terminal environment

When i exec this command : `python -u ./build.py --use_ccache` got such error:

```
You have PROXY values set in your environment, but gsutil in depot_tools does not (yet) obey them. Also, --no_auth prevents the normal BOTO_CONFIG environment variable from being used. To use a proxy in this situation, please supply those settings in a .boto file pointed to by the NO_AUTH_BOTO_CONFIG environment var.
```

According to :

- [depot_tools and gsutil do not respect proxy settings #241](https://github.com/GoogleCloudPlatform/gsutil/issues/241)
- [[chromium-packagers] Re: gsutil and proxy settings](https://groups.google.com/a/chromium.org/forum/#!topic/chromium-packagers/0eE3oC3lBFw)

I create a `Boto configuration` file somewhere with the following contents

```
 [Boto] 
 proxy = http://127.0.0.1
 proxy_port = 10241
 debug = 2
```

After that, I point the `NO_AUTH_BOTO_CONFIG` environment variable to the file i had created

```
 export NO_AUTH_BOTO_CONFIG=/path/to/proxy_webrtc.boto  && python -u ./build.py --use_ccache
```

But i still got error like

```
Failed to fetch file gs://chromium-clang-format/0679b295e2ce2fce7919d1e8d003e497475f24a3 for v8/buildtools/mac/clang-format, skipping.
```

Which is wrong ?

Thanks for read my issues.

**Comment by FrankFang** [comment]
Proxy is not enough. Use vpn.

**Comment by ry** [comment]
Probably fixed now. There's been many changes to the build system.
