### ISSUE TITLE
Deno.run can not echo environment variables

### ISSUE THREAD

**Issue by zhangbobo131415** [denoland/deno#16615]
![image](https://user-images.githubusercontent.com/26828921/201512748-7bff9cb5-fb7c-4853-ac8e-135ba8427229.png)
the shell is "echo $PATH", the ouput of Deno.run is "$PATH". it should output "/usr/bin:/xxx/bin"

**Comment by 0f-0b** [comment]
`Deno.run` does not spawn a shell by default. To execute a command inside a shell you have to explicitly specify which shell to use.

```ts
const decoder = new TextDecoder();
const process = Deno.run({
  cmd: ["sh", "-c", 'echo "$PATH"'],
  stdout: "piped",
});
const output = decoder.decode(await process.output());
console.log(output);
```

The straightforward way to get the value of an environment variable is to use [`Deno.env.get`](https://deno.land/api@v1.27.2?s=Deno.Env#method_get_0) though.

**Comment by zhangbobo131415** [comment]
@0f-0b  thank you,i got it
