### ISSUE TITLE
Deno doesn't show Error message on debugging when scripts have npm import

### ISSUE THREAD

**Issue by amgm-masamune** [denoland/deno#16628]
First of all, I am a Japanese student, so please forgive my poor English.

When I tried to run the following code in Deno using the VSCode debugger, only "start" was displayed in the output, and then nothing was displayed (no "Runtime Error").

# Code
```TypeScript
import _express from "npm:express";

console.log("start");

throw new Error("Runtime Error");
```

```
$ deno run --inspect --inspect-brk --allow-all .\main.ts
```

The following code, with the first line commented out, outputs "start" and displays "Runtime Error" as expected.

```TypeScript
// import _express from "npm:express";

console.log("start");

throw new Error("Runtime Error");
```

Execution environment
> deno: 1.28.0
> OS: Windows 11

**Comment by bartlomieju** [comment]
I can confirm that it doesn't work with the inspector. Interestingly if I set a break point on the line with error it is being hit. This will be rather difficult to debug, I'll try to make time to do so ASAP

**Comment by bartlomieju** [comment]
I'm still debugging this problem

**Comment by bartlomieju** [comment]
Might be related to https://github.com/denoland/deno/issues/8858

**Comment by bartlomieju** [comment]
I drilled down the root cause of this problem. I will try to fix the problem this week.
