### ISSUE TITLE
bug: `deno doc --json` prints incorrect output

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno#16623]
The following outputs `false None false` in the first 132 lines of the `out.json` file:
```
deno doc --json https://deno.land/x/redis@v0.27.3/mod.ts > out.json
```

My machine:
```
deno 1.28.0 (release, aarch64-apple-darwin)
v8 10.9.194.1
typescript 4.8.3
```

**Comment by zhmushan** [comment]
Is the log in the dev stage not deleted in time?
Anyway, this is a Deno Doc issue and it should be moved to https://github.com/denoland/deno_doc

**Comment by iuioiua** [comment]
Yes, you're right. This is a `deno_doc` issue. Whoops. Thanks for the fix!
