### ISSUE TITLE
`deno compile` cannot resolve npm modules

### ISSUE THREAD

**Issue by cb-fred** [denoland/deno#16632]
It seems that `deno compile` has trouble compiling scripts using npm modules.

Given the following script:

```
// main.ts
import express from "npm:express@4.18";
const app = express();

app.get("/", function (req, res) {
  res.send("Hello World");
});

app.listen(3000);
console.log("listening on http://localhost:3000/");
```

When I do
```
deno compile main.ts
```

I get the following error:
```
Check file:///Users/fred/Code/Own/deno/main.ts
error: Uncaught Error: could not find npm package directory for 'express@4.18'
    at <anonymous> (deno:cli/tsc/99_main_compiler.js:616:28)
```

I use the following deno version:
```
deno 1.28.0 (release, aarch64-apple-darwin)
v8 10.9.194.1
typescript 4.8.3
```
On OSX version 12.6

Using `deno run` on the same script works, as does `deno compile` for scripts that do not use npm packages.

The error also happens when using npm packages other than express

**Comment by bartlomieju** [comment]
As per https://github.com/denoland/deno/issues/15960 it's not yet supported

**Comment by cb-fred** [comment]
Ah, indeed, seems I overlooked that part in the release notes 😅

**Comment by dsherret** [comment]
It was a bug that it didn't give you a nice error message explaining this. That will be fixed in #16637.

**Comment by NetOpWibby** [comment]
Hijacking this because while I'm not having issues _compiling_, my app doesn't run.

```sh
deno compile --allow-env --allow-net --allow-read --unstable main.ts

# output
Check file:///~/main.ts
Compile file:///~/main.ts
Emit pastry-server
```

And then

```sh
./pastry-server

# output
error: Module not found
```

The error message is not helpful, so I searched the Deno Discord, which led me to this issue. I do have an npm module in my project.

```sh
import * as packet from "npm:dns-packet@5.4.0";
```

Guess I'll just keep an eye on this issue and pause that aspect of my project for now.

**Comment by royalknight56** [comment]
Hope this issue will be resolved

**Comment by chrisbrocklesby** [comment]
+1 for npm support in Deno compile.

**Comment by dingiyan** [comment]
+1 I'm looking forward to this feature.

**Comment by sshwy** [comment]
+1 looking forward to this feature.

**Comment by bartlomieju** [comment]
@dsherret is working on this feature.

**Comment by lino-levan** [comment]
@bartlomieju considering `deno compile` is now (or soon to be?) deprecated, should this issue remain open?

**Comment by dsherret** [comment]
@lino-levan no, `deno compile` is not going anywhere. I think you’re thinking of `deno bundle`.

**Comment by lino-levan** [comment]
Ah, sorry I misread this issue 😅

**Comment by johnstonmatt** [comment]
this one is a priority for my team working on [polyseam/cndi](https://github.com/polyseam/cndi), thanks for looking into this

**Comment by johnstonmatt** [comment]
this one is important for my team working on [polyseam/cndi](https://github.com/polyseam/cndi), thanks for looking into this!

**Comment by dsherret** [comment]
I started actual work on this one yesterday. Just doing the preliminary refactors to make it easier.

**Comment by Hillsie** [comment]
@cb-fred I was a hanging out for this feature until  trying out esm.sh for the imports and was glad to see that it compiles. The compile feature being very useful for a project I'm doing.  Deno :heart:

**Comment by Hillsie** [comment]
Okay, need to eat my hat. I've want to get @apollo/server@4.6.0 up and running with express. Easy port for my knowledge level. Can't find apollo server on esm.sh.  It's only on npm :disappointed: .  Back to hanging out for this feature.
esm.sh :broken_heart:  but still :heart:  Just a little challenging. The compile feature is awesome to ship code in a docker container.

**Comment by Creative-Difficulty** [comment]
@Hillsie same

**Comment by nabil-mansouri** [comment]
+1 looking for this feature! thank you very much guys
