### ISSUE TITLE
cli args - Show warning when putting permission flag after module name

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#16630]
Suggestion from @lucacasonato. It might be useful to show a warning when someone puts a permission flag after the module name. For example:

```
deno run main.js --allow-all
```

...that is incorrect and should be `deno run --allow-all main.js` because in the above it will instead provide `--allow-all` as an argument for `Deno.args` in main.js.

An issue with doing this might be that some apps expect having an argument like this though.

**Comment by lucacasonato** [comment]
Part of my suggestion was also to only do this if there are no permission flags before the file name. I think that remedies the concern about apps that actually have flags with the same name in 99% of cases while still helping beginners.

**Comment by iuioiua** [comment]
I’m happy to do this!
