### ISSUE TITLE
Dynamically importing a file that exports `then`, calls function

### ISSUE THREAD

**Issue by reggi** [denoland/deno#16645]
I don't know if this is a known issue, feel free to close. Seems problematic? But also kinda cool?

then.ts
```ts
export const then = () => {
  console.log('hello')
}
```

call.ts
```
const x = await import('./then.ts')
```

> deno run call.ts
hello

--- 

in one line

```
 deno eval 'import("data:application/typescript;base64,ZXhwb3J0IGNvbnN0IHRoZW4gPSAoKSA9PiAgIGNvbnNvbGUubG9nKCdoZWxsbycp")'
```

**Comment by bartlomieju** [comment]
Does the same happen in browser?

**Comment by reggi** [comment]
hah! yes it does, when in doubt ask if the browser does it! thanks @bartlomieju
