### ISSUE TITLE
Support user-defined functions in sqlite3

### ISSUE THREAD

**Issue by spiffytech** [denoland/deno#16657]
SQLite's regex syntax [errors out](https://www.sqlite.org/lang_expr.html#regexp) unless a user-defined regex function is defined.

User-defined functions are also useful for compensating for SQLite's poor datetime logic.

They can also be used with triggers to mimic Postgres' `LISTEN`/`NOTIFY` behavior.

I'd expect an implementation to resemble `better-sqlite3`'s [support for user-defined functions](https://github.com/WiseLibs/better-sqlite3/blob/master/docs/api.md#functionname-options-function---this).

**Comment by dsherret** [comment]
This doesn't seem actionable because we don't have sqlite built in? Maybe discuss in #11657?

**Comment by spiffytech** [comment]
Ah sorry, didn't see than [sqlite3](https://github.com/denodrivers/sqlite3) was a separate repo.

**Comment by dsherret** [comment]
No problem!
