### ISSUE TITLE
Question: Is Deno limited to a single thread per OS Process?

### ISSUE THREAD

**Issue by akircher** [denoland/deno#1665]
Apologies if this out of scope. I am also out of my technical depth.

As background, CouchDB currently uses [their own C/C++ bindings to Spidermonkey](https://github.com/apache/couchdb/issues/1875) in order provide the JS runtime for its maps, views, validation, etc.  As this is burdensome, their JS runtime is quite old and they seem to be [looking for an alternative](https://github.com/apache/couchdb/issues/1884) to maintaining their own bindings.

I [suggested using Deno](https://github.com/apache/couchdb/issues/1884#issuecomment-460003716) but their feedback was that because (of v8?) deno can only one be single threaded per OS Process. And therefore not NIF-able in Erlang.  Is this true?  If so, are there other use cases outside of CouchDB where this limitation would be problematic to adoption?  Would it be hard to overcome this limitation?

**Comment by kevinkassimo** [comment]
I believe workers are essentially separate threads. Deno has basic worker implemented but have not yet exposed to the userland. In the meantime Deno, like Node, uses a thread pool internally for async io tasks.

**Comment by akircher** [comment]
Somewhat related to #1666

**Comment by bartlomieju** [comment]
FYI @akircher Web Workers were released with Deno v0.3.6

**Comment by akircher** [comment]
Thanks @bartlomieju I will update the thread in couchdb!

**Comment by bartlomieju** [comment]
@akircher can we close this issue now?

**Comment by akircher** [comment]
Yes, my mission was accomplished by getting Deno on the CouchDB team's radar.
