### ISSUE TITLE
--lock-write does not write npm dependencies to deno.lock

### ISSUE THREAD

**Issue by mechanoid** [denoland/deno#16666]
Having a `deps.ts` file, like: 

```
export { config } from "https://deno.land/std@0.164.0/dotenv/mod.ts";
// ...
export { default as express } from "npm:express@4.18.2";
```

Running `deno cache --lock --unstable deps.ts` writes a deno.lock file including an `npm` key and the respective dependencies. When adding the `--lock-write` argument the lock is rewritten, but the `npm` deps are missing. 

This part is solved: (see https://deno.com/blog/v1.28#auto-discovery-of-the-lock-file) ~~~ T.b.h. I'm surprised that the statement without `--lock-write` writes a lock file. I thought that `--lock-write` was meant for that in the first place. ~~~

**Comment by bartlomieju** [comment]
Thanks for reporting, I'll take a look as this is unexpected.

> T.b.h. I'm surprised that the statement without --lock-write writes a lock file. I thought that --lock-write was meant for that in the first place.

That was the case before v1.28, see more explanation in https://deno.com/blog/v1.28#auto-discovery-of-the-lock-file

**Comment by mechanoid** [comment]
thanks for looking into that @bartlomieju. I'm really confused that nobody else reported that already. I have this issue I think since the beginning of the `npm` support, I think 1.26 and thought all the time, that I was doing something wrong or that it is just not final enought. But with the announcement that the npm support is no longer unstable, I thought that this needs somebody to look at.

**Comment by mechanoid** [comment]
I provided a "minimal test case"  - repository that showcases the issue, if that helps: https://github.com/mechanoid/deno-issue-16666-npm-missing-in-lock-file

**Comment by mechanoid** [comment]
Ah I missed the part of your message on my phone:

> That was the case before v1.28, see more explanation in https://deno.com/blog/v1.28#auto-discovery-of-the-lock-file

So only the missing npm deps is the PRoblem 👍

**Comment by bartlomieju** [comment]
Thanks for the reproduction! I can reproduce this problem, I'll look into fixing it.
