### ISSUE TITLE
Error: Argument list too long when using npm:prisma

### ISSUE THREAD

**Issue by daniellionel01** [denoland/deno#16675]
I'm trying to use Prisma in my deno repo. I followed the instructions from the recent blog post https://deno.com/blog/persistent-data-npm

I can run the "db push" command no problem, but as soon as it gets to generating the client, it gives the error below.

My OS is Pop!_OS 22.04 LTS x86_64 (Basically Ubuntu) and I'm on the latest deno version (1.28.0).

Here's my command and the output.

```
$ deno task db:gen
Task db:gen deno run --unstable -A npm:prisma@^4.5 generate --schema ./packages/db/schema.prisma
Prisma schema loaded from packages/db/schema.prisma
napi_add_env_cleanup_hook is currently not supported
Error: Argument list too long (os error 7)
```

I know this isn't much information to go on, but then again, I'm not getting much else from Deno to work with.

**Comment by bartlomieju** [comment]
According to [this comment](https://stackoverflow.com/a/42403051) it's not a problem with Deno but rather with the shell that you are using. Could you try and see if you can modify this on your side to resolve the problem?

**Comment by daniellionel01** [comment]
So I just tried it out, following the same steps as I did previously, with the new Deno 1.29.1 and everything worked out fine. So I'm not sure what the root cause was, I was using the same shell as I always do

**Comment by SushiWaUmai** [comment]
Having the same problem with Deno 1.31.1 on arch linux

**Comment by devsnek** [comment]
I've been able to run prisma locally as of https://github.com/denoland/deno/pull/24101. Let us know if you run into any additional issues.

**Comment by LeoMartinDev** [comment]
Same issue with `import { LlamaChatSession, getLlama } from 'npm:node-llama-cpp@beta';` on `deno@1.44.2`

**Comment by devsnek** [comment]
@LeoMartinDev i'm not able to reproduce this.

**Comment by LeoMartinDev** [comment]
Even with this most complete example?

```typescript
import { LlamaChatSession, getLlama } from 'npm:node-llama-cpp@3.0.0-beta.32';
import * as path from "https://deno.land/std@0.224.0/path/mod.ts";

const __dirname = path.dirname(path.fromFileUrl(import.meta.url));

const llama = await getLlama();
```
