### ISSUE TITLE
Connecting to database that requires SSL doesn't work in Deno

### ISSUE THREAD

**Issue by samaybar** [denoland/deno#16670]
I'm trying to connect to a database that requires SSL using https://deno.land/x/mysql2/mod.ts
My connection string looks like:
```
{
    host: hostname,
    port: 3306,
    user: username,
    password: password,
    database: database,
    ssl: {rejectUnauthorized: true}
}
```

and I get an error that says
`server does not allow insecure connections, client must use SSL/TLS`

Does anyone know how to solve this? (Connection works fine using mysql2 in Node) -- I can't seem to get Deno to actually use SSL. Is there another library that would work or is this an issue with Deno and SSL?

**Comment by dsherret** [comment]
Best to ask in that repo I think as this doesn't seem like a Deno specific question

Related:

* https://github.com/sail-sail/mysql2/issues/5
* https://github.com/denodrivers/mysql/issues/118#issuecomment-965858588

FWIW, that repo seems it has all its ssl code commented out. I don't believe it works.

**Comment by webdev3301** [comment]
Here for completion. `connectTls` upgrades an existing insecure connection to Tls.

[function Deno.connectTls](https://deno.land/api?s=Deno.connectTls)
