### ISSUE TITLE
`CommandOuput` type should extend `CommandStatus` (not `ChildStatus`)

### ISSUE THREAD

**Issue by jsejcksn** [denoland/deno#16680]
I noticed that the recently introduced type

<details>
<summary><a href="https://github.com/denoland/deno/blob/v1.28.1/cli/dts/lib.deno.unstable.d.ts#L1800-L1813"><code>CommandOutput</code></a></summary>

```ts
  /** **UNSTABLE**: New API, yet to be vetted.
   *
   * The interface returned from calling {@linkcode Command.output} or
   * {@linkcode Command.outputSync} which represents the result of spawning the
   * child process.
   *
   * @category Sub Process
   */
  export interface CommandOutput extends ChildStatus {
    /** The buffered output from the child process' `stdout`. */
    readonly stdout: Uint8Array;
    /** The buffered output from the child process' `stderr`. */
    readonly stderr: Uint8Array;
  }
```
</details>

currently extends

<details>
<summary><a href="https://github.com/denoland/deno/blob/v1.28.1/cli/dts/lib.deno.unstable.d.ts#L1590-L1605"><code>ChildStatus</code></a></summary>

```ts
  /** **UNSTABLE**: New API, yet to be vetted.
   *
   * @deprecated Use the Deno.Command API instead.
   *
   * @category Sub Process
   */
  export interface ChildStatus {
    /** If the child process exits with a 0 status code, `success` will be set
     * to `true`, otherwise `false`. */
    success: boolean;
    /** The exit code of the child process. */
    code: number;
    /** The signal associated with the child process, present if
     * {@linkcode Deno.spawn} was called. */
    signal: Signal | null;
  }
```
</details>

(which is marked as deprecated). It should instead extend

<details>
<summary><a href="https://github.com/denoland/deno/blob/v1.28.1/cli/dts/lib.deno.unstable.d.ts#L1786-L1798"><code>CommandStatus</code></a></summary>

```ts
  /** **UNSTABLE**: New API, yet to be vetted.
   *
   * @category Sub Process
   */
  export interface CommandStatus {
    /** If the child process exits with a 0 status code, `success` will be set
     * to `true`, otherwise `false`. */
    success: boolean;
    /** The exit code of the child process. */
    code: number;
    /** The signal associated with the child process. */
    signal: Signal | null;
  }
```
</details>

Because the two are structurally identical, it looks like a typo/bug to me. `CommandStatus` is the interface included with the rest of the related "Command" API.

I would have already created a PR to fix it, but I have a feeling that this type declaration file is generated — and so I'm not sure how to make the amendment. If someone wants to inform me of where to make the actual change, I'd be happy to create the PR.

**Comment by dsherret** [comment]
I think you're right (cc @crowlKats)

> I would have already created a PR to fix it, but I have a feeling that this type declaration file is generated — and so I'm not sure how to make the amendment. If someone wants to inform me of where to make the actual change, I'd be happy to create the PR.

The file is not auto-generated. Feel free to create a PR.

**Comment by crowlKats** [comment]
Yea, an oversight on my end
