### ISSUE TITLE
Website: Hate the anchors

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#1669]
I really hate the current anchors on the website.  I find them very distracting.  Looks like Deno is named #Deno.

<img width="470" alt="deno" src="https://user-images.githubusercontent.com/1282577/52187856-d3c15380-2883-11e9-893e-b451028529ca.png">

Why can't we style them out of the flow of the text and only have them visible on hover, just like GitHub:

![target hover](https://user-images.githubusercontent.com/1282577/52187881-efc4f500-2883-11e9-8dcb-87a3e4a22504.gif)

**Comment by hayd** [comment]
see #1664 for their removal, though 👍 for on-hover.

**Comment by kitsonk** [comment]
@hayd that just removes some of them

**Comment by sh7dm** [comment]
@kitsonk yes, now I think your solution is better!

**Comment by sh7dm** [comment]
@kitsonk fixed! :tada:

**Comment by Maxim-Mazurok** [comment]
Since now website uses other approach for anchors (after the title instead of having anchor before the title), this issue seems to be not relevant anymore.
@kitsonk, do you mind closing it?

**Comment by kitsonk** [comment]
#1728 is not merged

**Comment by kitsonk** [comment]
Addressed in a4dec944bc821d114bfd82debb72d60bd04f836d
