### ISSUE TITLE
Deno bundled file doesn't permit top level await

### ISSUE THREAD

**Issue by fprijate** [denoland/deno#16701]
Very simple bundled program using top level await  breaks with:
` SyntaxError: await is only valid in async functions and the top level bodies of modules.`

The same program , run directly or compiled works fine

**Comment by dsherret** [comment]
Could you provide reproduction steps? I can't reproduce. Thanks!

**Comment by fprijate** [comment]
Sory

My fault. 
First I haven't menthioned that I execute bundled program with nodejs.
I bundled it with **"deno bundle test.ts test.js"**
After I bundle to .mjs file instead of .js and run it with node everything  works fine.

**Comment by lucacasonato** [comment]
`deno bundle` is deprecated, and this will not be fixed.
