### ISSUE TITLE
Not emitting "design:returntype" decorator metadata

### ISSUE THREAD

**Issue by Sorikairox** [denoland/deno#16712]
I have this simple code that when transpiled with tsc 4.8.4, emit "design:returntype" metadata : 

```ts
import { Reflect } from 'https://deno.land/x/deno_reflect@v0.2.1/mod.ts';

export const PrintIt = () => (
  target: Object,
  propertyKey: string | symbol,
  descriptor: any
) => {
  console.log(target, propertyKey);
  console.log(Reflect.getMetadataKeys(target, propertyKey));
}

class MyController {

  @PrintIt()
  getSomething(): boolean {
    return true;
  }

  @PrintIt()
  postSomething(): number {
    return 1;
  }
}
```

The relevant part get transpiled as : 

```js
__decorate([
    PrintIt(),
    __metadata("design:type", Function),
    __metadata("design:paramtypes", []),
    __metadata("design:returntype", Boolean)
], MyController.prototype, "getSomething", null);
__decorate([
    PrintIt(),
    __metadata("design:type", Function),
    __metadata("design:paramtypes", []),
    __metadata("design:returntype", Number)
], MyController.prototype, "postSomething", null);
```

Here is a [Playground Link](https://www.typescriptlang.org/play?target=9&ts=4.8.4#code/MYewdgzgLgBACgJwJZigSVgXhgCgJQyYB8uAUDDFAIYIDmAplAFwwDyARgFb3BQA05GAAcEIIfQRQAngGl6UltGRhaMAD4wIUgLbsQAGwEUAJvQjBkQqCAQsqYKaQLEYAb0GhIB+gDp9IWhxqOkY+YVFxSVl5PABuD3AIbz8AnAAlegAzfR4oHwYoAFlGKmMqajkpCCCaArCRMQlpSrw40gBfUi7gfSoICBhCqQBhcChRfRyENy6KAAFEFHQofEECgGUQbUYACxRAvBY9b3sZigoERgBXBDBKBCv6eIpOwQXlZdWKIRBoTe2oHsVPgWGArroJGdzpcoDc7gBGZ4wTrtIA) to see it with your own eyes.

However, with Deno, it is transpiled to :
```js
__decorate([
    PrintIt(),
    __metadata("design:type", Function),
    __metadata("design:paramtypes", [])
], MyController.prototype, "getSomething", null);
__decorate([
    PrintIt(),
    __metadata("design:type", Function),
    __metadata("design:paramtypes", [])
], MyController.prototype, "postSomething", null);
```

Is it a Deno problem or a deno_reflect (the third party library used to get Reflect object in Deno) ?

**Comment by dsherret** [comment]
See https://github.com/swc-project/swc/issues/3319

**Comment by Sorikairox** [comment]
Fixed in https://github.com/swc-project/swc/pull/8303
