### ISSUE TITLE
`Deno.Command` API needs better documentation

### ISSUE THREAD

**Issue by jsejcksn** [denoland/deno#16719]
#16516 introduced a consolidated replacement for the "spawn" API. This is an ergonomic improvement, but usage is not documented clearly enough.

Link to current documentation: https://deno.land/api@v1.28.1?unstable=&s=Deno.Command

For example, given a command instance:

```ts
const c = new Deno.Command("ls");
```

Are `c.output()` and `c.outputSync()` and `c.spawn()` the only methods which **don't throw**?

The documentation for the [`spawn`](https://deno.land/api@v1.28.1?unstable=&s=Deno.Command#method_spawn_0) method says:

> Spawns a streamable subprocess, allowing to use the other methods.

But it doesn't define what the "other methods" are. Are they "all other methods other than `output` and `outputSync`"?

Further, all of the previous subprocess APIs had behaviors which created an actual subprocess as part of the initial function invocation (e.g. `Deno.run()`, `Deno.spawn()`, etc.).

This new API seems to create an inert command instance (e.g. `new Deno.Command()`) but doesn't actually create a subprocess until another action is taken. Which methods actually create the subprocess? (It appears to be `spawn`, `output` and `outputSync`.)

Can `command.pid` be used with `output`? (It appears not.) However, it also appears that `command.pid` can be used on a command that was spawned but also already terminated.

Which methods can be used after the `spawn` method? Which methods can be used after the `output`/`outputSync` methods?

I think all of these behaviors, interactions, etc. need to be documented and explained.

**Comment by lucacasonato** [comment]
I think the new `Deno.Command` API is confusing because it tries to combine both configuration and state into a single struct. This means that `Deno.Command` can represent both a "to-be-spawned" and an "already-spawned" subprocess.

I propose we split these to make this less confusing: https://github.com/denoland/deno/issues/16799

**Comment by dsherret** [comment]
Let's close this now that #16812 is merged.
