### ISSUE TITLE
allow one to specify lock behavior in `deno.json`

### ISSUE THREAD

**Issue by harrysolovay** [denoland/deno#16717]
Otherwise one needs to specify with every run / task

**Comment by bartlomieju** [comment]
What behavior do you want to specify? Please add an example

**Comment by harrysolovay** [comment]
In the following tasks, I need to re-specify the `--no-lock` flag.

```jsonc
// ...
  "tasks": {
    "run_something": "deno run -A --no-lock",
    "test": "deno test -A --no-lock -L=info --ignore=target --parallel",
    "bench": "deno bench -A --no-lock"
  },
// ...
```

Ideally I could do this once within the `deno.json`

```diff
// ...
+ "lock": false,
  "tasks": {
-   "run_something": "deno run -A --no-lock",
+   "run_something": "deno run -A",
-   "test": "deno test -A --no-lock -L=info --ignore=target --parallel",
+   "test": "deno test -A -L=info --ignore=target --parallel",
-   "bench": "deno bench -A --no-lock"
+   "bench": "deno bench -A"
  },
// ...
```

**Comment by bartlomieju** [comment]
@dsherret do you have opinion on this one?

**Comment by dsherret** [comment]
It might be nice for when people want to opt out of a lockfile completely.

**Comment by KnorpelSenf** [comment]
I think lock files are great for applications, but they serve no purpose for libraries. The lock file will be disregarded when the library is consumed, so there's little point in maintaining it in the first place.

Hence, virtually every project that backs a module on /x (as well as all other competing sites) will want to not have any lock file. Being able to set `"lock": false` in `deno.jsonc` would be of great help for all of us library devs :)

**Comment by roj1512** [comment]
Just letting you know that I am working on this.
