### ISSUE TITLE
Undici doesn't work with npm specifiers

### ISSUE THREAD

**Issue by khrj** [denoland/deno#16710]
Undici returns a ConnectTimeoutError when attempting any request.

Many npm modules depend on undici, node's fetch api implementation used as a module.

Reproducible example:

```js
import { request } from "npm:undici"
await request("https://www.example.com")
```

fails with

```
error: Uncaught (in promise) ConnectTimeoutError: Connect Timeout Error
    at onConnectTimeout (file:///home/khushraj/.cache/deno/npm/registry.npmjs.org/undici/5.12.0/lib/core/connect.js:133:24)
    at file:///home/khushraj/.cache/deno/npm/registry.npmjs.org/undici/5.12.0/lib/core/connect.js:80:46
    at Timeout.<anonymous> (file:///home/khushraj/.cache/deno/npm/registry.npmjs.org/undici/5.12.0/lib/core/connect.js:121:9)
    at https://deno.land/std@0.164.0/node/timers.ts:21:15
    at Object.action (deno:ext/web/02_timers.js:147:13)
    at handleTimerMacrotask (deno:ext/web/02_timers.js:64:12)
```

Example of module broken: #16684

**Comment by kt3k** [comment]
I found 3 issues for this:
- [ ] `Timeout.prototype.refresh` method is missing https://github.com/denoland/deno_std/pull/2919
- [ ] `TCP.unref` is not available (We need Deno.TcpConn.unref first, and then need to shim TCP.unref using it.)
  - ref: https://github.com/nodejs/undici/blob/80700c6287ef5fbb0eb2b669192ac7109ec01f57/lib/client.js#L1175
- [ ] There's somethig wrong with TLS handling (not sure about details yet)

**Comment by bartlomieju** [comment]
Seems like there's another problem: https://github.com/denoland/deno/issues/15427#issuecomment-1329945670

**Comment by khrj** [comment]
Any progress on Deno.TcpConn.unref / is there something blocking it?

**Comment by bartlomieju** [comment]
> Any progress on Deno.TcpConn.unref / is there something blocking it?

No progress, no one has picked it up yet. PRs are most welcome!

**Comment by bartlomieju** [comment]
FYI I'm working on the ref/unref functionality in #17170

**Comment by bartlomieju** [comment]
@kt3k could you take over this issue now that unref API for connection is implemented?

**Comment by kt3k** [comment]
Sure!

**Comment by khrj** [comment]
@kt3k as of 1.29.2, this seems to be completely functional now? Is there something that is still pending, or should I close this issue? The example in the original post works now. Thanks!

**Comment by Jakob5358** [comment]
@khrj It still seems to time out for me, both on 1.29.2 and on latest canary.
```ts
import { request } from 'npm:undici';

const res = await request('https://jsonplaceholder.typicode.com/todos/1');
console.log(res.statusCode);
```

**Comment by khrj** [comment]
Apart from being rather slow, it works for me:

![image](https://user-images.githubusercontent.com/44947946/211352201-bcdef311-6829-418c-8cac-7f88c4767d8e.png)

Running deno from master

**Comment by khrj** [comment]
In comparison:

![image](https://user-images.githubusercontent.com/44947946/211356421-3cfffbc7-7d61-4688-a572-f7ce651c0254.png)

**Comment by Jakob5358** [comment]
> Apart from being rather slow, it works for me:
> 
> ![image](https://user-images.githubusercontent.com/44947946/211352201-bcdef311-6829-418c-8cac-7f88c4767d8e.png)
> 
> Running deno from master

Weird, this is what happens for me running deno... not from master but from latest canary.
![image](https://user-images.githubusercontent.com/75086936/211371944-54e41e4a-b48f-43b1-9a4e-747ad903d7f8.png)
Maybe I'm not using the latest deno_std version for node compat and you need to set that manually idk-

**Comment by kt3k** [comment]
@Jakob5358 Is `https://jsonplaceholder.typicode.com/todos/1` accessible from your environment?

**Comment by Jakob5358** [comment]
> @Jakob5358 Is `https://jsonplaceholder.typicode.com/todos/1` accessible from your environment?

Yes but it now works in the latest version thanks y'all
