### ISSUE TITLE
bug: cannot select a template when creating a vue project

### ISSUE THREAD

**Issue by idanran** [denoland/deno#16720]
![image](https://user-images.githubusercontent.com/96647698/202740949-2e91203c-571a-46b6-89be-aababf82b2b5.png)
Unable to move up and down.
OS version: Windows 11 22H2

For more information see bluwy/create-vite-extra#15

**Comment by bartlomieju** [comment]
This is the same problem as https://github.com/denoland/deno/issues/5945. I'll look into it this week.

**Comment by idanran** [comment]
> This is the same problem as #5945. I'll look into it this week.

ok
