### ISSUE TITLE
npm specifier on binary command doesn't default to use latest version

### ISSUE THREAD

**Issue by EdJoPaTo** [denoland/deno#16721]
For some reason Deno does not seem to default to the current `latest` version. Instead it uses some other version.

```bash
$ deno --version
deno 1.28.1 (release, x86_64-unknown-linux-gnu)
v8 10.9.194.1
typescript 4.8.3

$ npm view xo version
0.53.1

$ deno run -A npm:xo --version
0.52.3

$ deno run -A npm:xo@0.53 --version
error: Could not find npm package 'xo' matching 0.53. Try retrieving the latest npm package information by running with --reload

$ deno run --reload -A npm:xo@0.53 --version
0.53.1

$ deno run -A npm:xo@0.53 --version
0.53.1

$ deno run -A npm:xo --version
0.52.3

$ deno run --reload -A npm:xo --version
0.52.3

$ rm -rf ~/.cache/deno

$ deno run -A npm:xo --version
0.52.3
```

(Run on Arch Linux with Deno installed from the repositories)

**Comment by dsherret** [comment]
Do you have a lockfile in your current working directory? If so, it has already locked `npm:xo` to `0.52.3` and you'll need to recreate the lockfile.

**Comment by EdJoPaTo** [comment]
Yes, the lock file is the reason here which makes sense now but somehow felt counterintuitive.

Basically `deno run` is equivalent to a `dependency` or `devDependency` of a Node.js project.
Global scripts would either use `--no-lock or be installed (`deno install` which use some global lock file location). This confused me as "I am only running some command independent from the files in the current directory, it shouldnt have side effects".

Interestingly this is also what I tried in my command history when submitting the issue: delete the `~/.cache/deno` as running some independent command felt global, not local.

I'm not sure whether that's something "to be learned" or "to be improved".
Currently I don't have good ideas to improve this other than somehow promoting `deno install` better? Maybe `--reload` could hint that the lock file is still in place? (But that also doesn't really seem like a good place to do so)

**Comment by dsherret** [comment]
It’s done for security reasons and reproducibility within a project (project meaning when a deno.json exists). Commands run on the command line are one of the biggest attack vectors, so if someone for example had a deno task with `deno run -A npm:xo` in it, then we’d want to ensure it always resolves to the same version within that project especially on the CI. That way it’s not fetching the latest the latest version, which could become compromised or break the command.

> Maybe --reload could hint that the lock file is still in place? (But that also doesn't really seem like a good place to do so)

I think something along those lines might be reasonable when a version requirement doesn't resolve to the latest version. I opened https://github.com/denoland/deno/issues/16736
