### ISSUE TITLE
feature request: publish `@types/deno` package to npm

### ISSUE THREAD

**Issue by idanran** [denoland/deno#16742]

**Comment by dsherret** [comment]
We can't because somebody else owns the `deno` package on npm.

**Comment by idanran** [comment]
> We can't because somebody else owns the `deno` package on npm.

I want to use the deno type in node.

**Comment by idanran** [comment]
> We can't because somebody else owns the `deno` package on npm.

Publish "@deno/types-deno" package to npm should be fine.

**Comment by dsherret** [comment]
I just remembered this, but does using https://www.npmjs.com/package/@deno/shim-deno work? You should be able to import it in node.js like:

```ts
import type { Deno } from "@deno/shim-deno";
```

**Comment by idanran** [comment]
> I just remembered this, but does using https://www.npmjs.com/package/@deno/shim-deno work? You should be able to import it in node.js like:
> 
> ```ts
> import type { Deno } from "@deno/shim-deno";
> ```


This one is older. I hope the type will follow the version release.

**Comment by dsherret** [comment]
I'm going to update it soon. If you need up to date types then I recommend using the output of `deno types`.

**Comment by idanran** [comment]
> I'm going to update it soon. If you need up to date types then I recommend using the output of `deno types`.

It's not just about the type, I want to use deno's interface.

**Comment by dsherret** [comment]
> `deno types` has not been updated for a long time

That command contains the latest types. There's also a declaration file released in the github releases https://github.com/denoland/deno/releases/tag/v1.28.1

**Comment by idanran** [comment]
> deno types

Thanks

**Comment by idanran** [comment]
> > `deno types` has not been updated for a long time
> 
> That command contains the latest types. There's also a declaration file released in the github releases https://github.com/denoland/deno/releases/tag/v1.28.1

Thanks
