### ISSUE TITLE
bug: vscode's import's address auto-completion does not work properly

### ISSUE THREAD

**Issue by idanran** [denoland/deno#16740]
Deno version: 1.28.1
OS version: Windows 11 22H2
```ts
// a.ts
export interface a{
}
```
```ts
// test.ts

```
Reproduction steps:
1.
![image](https://user-images.githubusercontent.com/96647698/203036596-901ee7f2-aa55-419b-b4be-54efadbcdbec.png)
enter
2.
![image](https://user-images.githubusercontent.com/96647698/203036666-63fb6518-0aea-420d-bebf-377467cdc577.png)
It does not contain the file extension.

**Comment by bartlomieju** [comment]
Can you still reproduce the problem with latest Deno?

**Comment by idanran** [comment]
> Can you still reproduce the problem with latest Deno?

Unable to reproduce when using the latest version.

**Comment by bartlomieju** [comment]
Great, I'm gonna close this issue for now. Let me know if you encounter this problem again.

**Comment by idanran** [comment]
> Great, I'm gonna close this issue for now. Let me know if you encounter this problem again.

No problem.
