### ISSUE TITLE
Deno User Manual missing page (404 - Not Found) for Cache API

### ISSUE THREAD

**Issue by lukepuplett** [denoland/deno#16768]
Hey all, just learning Deno. Nice docs so far, clear, concise, consistent.

Anyway, this page is a 404.

https://deno.land/manual@v1.28.1/runtime/cache_api

**Comment by voizlav** [comment]
I believe this is out of scope for deno core, it would be suited to transfer the issue to the [manual](/denoland/manual/) repository.

**Comment by crowlKats** [comment]
Duplicate of denoland/manual#436
