### ISSUE TITLE
How to solve VSCode Code Intelligence?

### ISSUE THREAD

**Issue by MonsterPi13** [denoland/deno#16761]
When i import npm modules, the intelligence tips `Cannot find module 'npm:express@^4.18' or its corresponding type declarations.`, how to solve this error?

``` ts
// main.ts
import express from "npm:express@^4.18";
const app = express();

app.get("/", function (req, res) {
  res.send("Hello World");
});

app.listen(3000);
console.log("listening on http://localhost:3000/");
```
![image](https://user-images.githubusercontent.com/43134418/203285996-a4831316-0726-4c48-87e0-9dfc713ee41d.png)

**Comment by khrj** [comment]
You need the [Deno extension for vscode](https://marketplace.visualstudio.com/items?itemName=denoland.vscode-deno).
Once you get that, open the command palette with <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>P</kbd> and run _Deno: Initialize Workspace Configuration_

**Comment by MonsterPi13** [comment]
> You need the [Deno extension for vscode](https://marketplace.visualstudio.com/items?itemName=denoland.vscode-deno). Once you get that, open the command palette with Ctrl + Shift + P and run _Deno: Initialize Workspace Configuration_

I have been installed deno plugin.
![image](https://user-images.githubusercontent.com/43134418/203288074-0423b848-fe70-453d-a67a-83b7cab025ec.png)

**Comment by khrj** [comment]
Could you share your workspace settings file (`.vscode/settings.json`)?

**Comment by MonsterPi13** [comment]
> 

I don't specify `.vscode/settings.json` in my current folder, but in my global vscode setting wrote as below.
```
{
  "workbench.colorTheme": "Valhalla Theme",

  "editor.fontSize": 16,
  "editor.fontLigatures": true,
  "editor.fontFamily": "'Fira Code', Menlo, Monaco, 'Courier New', monospace",
  "workbench.iconTheme": "material-icon-theme",
  "cSpell.userWords": [
    "composables",
    "csstype",
    "Fira",
    "formily",
    "Menlo",
    "Unocss"
  ],
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "editor.tabSize": 2,
  "explorer.confirmDelete": false,
  "security.workspace.trust.untrustedFiles": "newWindow",
  "explorer.confirmDragAndDrop": false,
  "workbench.startupEditor": "none",
  "git.confirmSync": false,
  "git.enableSmartCommit": true
}
```

**Comment by khrj** [comment]
To actually enable the Deno extension (and I believe this is to avoid conflicting with node project editing), you have to enable Deno for your workspace.

Open the command palette with <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>P</kbd> and run _Deno: Initialize Workspace Configuration_

Alternatively, add the following to your **workspace** `.vscode/settings.json`:

```json
{
    "deno.enable": true,
    "deno.unstable": true
}
```

**Comment by MonsterPi13** [comment]
> To actually enable the Deno extension (and I believe this is to avoid conflicting with node project editing), you have to enable Deno for your workspace.
> 
> Open the command palette with Ctrl + Shift + P and run _Deno: Initialize Workspace Configuration_
> 
> Alternatively, add the following to your **workspace** `.vscode/settings.json`:
> 
> ```json
> {
>     "deno.enable": true,
>     "deno.unstable": true
> }
> ```

Thanks for your help, this work for me.

**Comment by shinebayar-g** [comment]
Just ran into this. In case if above still not working make sure you've `enableProjectDiagnostics` disabled.

```json
{
    "deno.enable": true,
    "deno.lint": true,
    "editor.formatOnSave": true,
    "[typescript]": {
        "editor.defaultFormatter": "denoland.vscode-deno"
    },
    "typescript.tsserver.experimental.enableProjectDiagnostics": false
}
```
