### ISSUE TITLE
uninstall subcommand does not accept short flags

### ISSUE THREAD

**Issue by voizlav** [denoland/deno#16763]
I noticed that deno's subcommand for removing executable scripts from root's bin directory does not accept short flags.
In particular, the option for printing help information and the option for suppressing diagnostic output do not work as expected.

**help option**
```
$ deno uninstall -h
error: No installation found for -h
```

**quiet option**
```
$ deno uninstall -q
error: No installation found for -q
```
```
$ deno uninstall -q serve
error: Found argument 'serve' which wasn't expected, or isn't valid in this context
```
note that the long flag prints to the console
```
$ deno uninstall --quiet serve
deleted /home/user/.deno/bin/serve
✅ Successfully uninstalled serve
```
version: deno 1.28.1

**Comment by sigmaSd** [comment]
It seems like there is an explicit `allow_hyphen_values` https://github.com/denoland/deno/blob/f077c4f248ab96c1ba67dd24d6573cc9f9a0a1ad/cli/args/flags.rs#L1290 which means it considers flags as values

**Comment by rubiagatra** [comment]
Can I take a stab at this @sigmaSd @lucacasonato?

**Comment by rubiagatra** [comment]
I created the PR #17141 please take a look @sigmaSd @lucacasonato

**Comment by rubiagatra** [comment]
moved to #17259
