### ISSUE TITLE
Compile Error but outputs no useful error message, only this: "error: Module not found"

### ISSUE THREAD

**Issue by Revolution1** [denoland/deno#16760]
please go to this issue: https://github.com/polkadot-js/api/issues/5350

**Comment by bartlomieju** [comment]
Please provide a minimal reproduction.

**Comment by Revolution1** [comment]
@bartlomieju I only found this problem when I'm using polkadot lib.

But it looks like a deno issue.

I saw there is a issue says that current compile does not support NPM package

But looking into the deno.lock file of polkadot js, it has no npm dependency.

The point is, this error message is too vague, cannot debug.

Is there any option or envvar that enables debug log of compiled deno?

**Comment by bartlomieju** [comment]
> Is there any option or envvar that enables debug log of compiled deno?

No, it most likely is a bug in Deno. If you can provide a list of steps to reproduce the problem then it will be easier for us to debug. Please boil down the example to a few bash commands, it's really hard for maintainers to read through whole issues in different repos to come up with reproduction.

**Comment by Revolution1** [comment]
I tought this was already quite simple
I'll dig down more when I got time to ~
```bash
for v in {11..17}; do
    file="polkadot.0.2.$v.ts"
    cat <<EOF >$file
import { WsProvider } from "https://deno.land/x/polkadot@0.2.$v/api/mod.ts";
await (new WsProvider("wss://rpc.polkadot.io")).disconnect();
console.log("OK");
EOF
    echo "try running 'deno run -A $file'"
    deno run -A $file

    echo "try compile and run with 'deno compile -A -o test.0.2.$v $file && ./test.0.2.$v'"
    deno compile -A -o "test.0.2.$v" $file && ./"test.0.2.$v"
    echo
done
```
