### ISSUE TITLE
Permission prompt for dynamic imports asks for same domain over and over

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#16772]
```ts
// main.ts
const importUrl = "https://deno.land/x/ts_morph/mod.ts";
const test = await import(importUrl);
console.log(test);
```

```
deno run main.ts
```

![image](https://user-images.githubusercontent.com/1609021/203444408-8b6ce6f7-7d75-40c6-b2a0-0a8237df2caf.png)

It should be more specific about what it's asking or only ask once.

**Comment by sigmaSd** [comment]
The issue is here https://github.com/denoland/deno/blob/main/cli/cache/mod.rs#L99 we're just modifying a clone of the permissions, so no permission changes will be saved.
