### ISSUE TITLE
No support for webextensions/add-ons

### ISSUE THREAD

**Issue by danielbWork** [denoland/deno#16779]
Currently deno doesn't support (or at least has no documentation) for bundling/creating web extensions

**Comment by lucacasonato** [comment]
This is not actionable. Please elaborate on what you'd like to see added / changed in Deno to support your usecase.

**Comment by danielbWork** [comment]
@lucacasonato  To run a web extension bundled javascript (or just plain javascript) is required, so typescript won't work as deno bundle crates a bundle for deno (unless the documentation is wrong). 
Web extensions also must include a manifest which points to these javascript files and to some image files so bundling might cause a problem with pathing for these files.

To compare who it's done today in node:
you build a typescript project with the manifest pointing to the various files and the bundle you are using (usually webpack or parcel) read the manifest and output to the dist folder a new version of the manifest pointing at the bundled js files also included in the dist folder
