### ISSUE TITLE
Deno vendor doesn't work when lockfile contains npm specifiers

### ISSUE THREAD

**Issue by sigmaSd** [denoland/deno#16778]
```a.ts
import {} from "https://deno.land/std/path/mod.ts";
```
`deno vendor a.ts`
`deno run -A --import-map vendor/import_map.json a.ts`

```
error: Uncaught TypeError: Module not found "file:///home/mrcool/dev/deno/lab/qsdq/vendor/deno.land/std@0.165.0/node/module_all.ts".
    at async loadBuiltinNodeModules ([deno:cli/node/mod.rs:415:32]:2:25)
```

**Comment by dsherret** [comment]
Do you have a lockfile with npm specifiers in it?

**Comment by dsherret** [comment]
I investigated and am able to reproduce when there are npm specifiers in the lockfile. In some respects this is just `deno vendor` not having npm specifier support yet.

**Comment by sigmaSd** [comment]
Ok, so I have a structure like this:
```
--../deno/----deno.json
         |--deno-projects
```
This makes my editor automatically detects that it should use deno lsp whenever I'm in any path under deno,  but now running any deno file under deno projects actually creates the lock in the root directory adjacent to deno.json

I guess if all this is intended, I can just use another marker file to trigger my editor
