### ISSUE TITLE
Ability to create global modules

### ISSUE THREAD

**Issue by ameerthehacker** [denoland/deno#1678]
I would like to suggest a deno builtin module that would abstract out the development of global modules with deno.

executing deno -g url should make that module available globally by

* Creating a script for it
* Add permissions for it
* Export the path

**Comment by kitsonk** [comment]
Globals are bad.  What is the use case?

**Comment by ameerthehacker** [comment]
@kitsonk something like ng and nodemon in node...

**Comment by kyranet** [comment]
You can install them via npm or yarn, though, same for `windows-build-tools` and `pm2` (which I use, and require global installation)

**Comment by sholladay** [comment]
Part of the beauty of Deno is that it's based on more generic standards. In this case, a "global command" could just be a plain old shell [alias](https://shapeshed.com/unix-alias/) or executable in your [PATH](https://en.wikipedia.org/wiki/PATH_(variable)).

Let's pretend `denomon` is a thing and its source code is:

```js
#!/usr/bin/env deno

console.log('I am denomon');
```
Now when we want to use it as a global command...

**Solution 1: Use a shell alias**
```sh
# In your bash profile
alias denomon='deno https://deno.land/x/denomon'
```

**Solution 2: Put the executable in PATH**
```console
$ curl https://deno.land/x/denomon -s -o /usr/local/bin/denomon
$ chmod +x /usr/local/bin/denomon
```

And that's it. Using those techniques, you can then run `denomon` from anywhere as a global command.

Solution 2 is actually what `npm install -g` does, basically. Except `npm` uses a lot Node-specific shenanigans in the processes of doing it, whereas Deno doesn't need to. That said, you could totally `npm install -g denomon` and use it with Deno! You'd just have to include a superfluous `package.json` to make npm happy.

I agree it would be nice if Deno had a built-in command for convenience and to make Deno more familiar for folks who are used to Node. My point is just that, even without a built-in command, this is still very easy thanks to Deno's design.
