### ISSUE TITLE
Emojis on Windows not displayed correctly in deno task `echo`

### ISSUE THREAD

**Issue by oscarotero** [denoland/deno#16792]
I'm having some issues on Windows (powershell). Let's see the following tasks:

```json
{
  "tasks": {
    "eval": "deno eval \"console.log('🔥');\"",
    "echo": "deno echo \"🔥\"",
    "run-pipeline": "echo \"console.log('🔥');\" | deno run -",
    "run-pipeline-2": "echo import \"./fire.ts\" | deno run -",
    "run": "deno run ./fire.ts",
  }
}
```

some of them run this script:

```ts
// fire.ts
console.log("🔥");
```

```sh
deno task eval
>🔥
deno task echo
>ƒöÑ
deno task run-pipeline
>ƒöÑ
deno task run-pipeline-2
>ƒöÑ
deno task run
>🔥
```

It seems that the `echo` implementation in deno has issues with emojis because all task containing a echo don't display the emojis.

**Comment by dsherret** [comment]
We encountered this same problem on Windows before with console.log. I opened https://github.com/denoland/deno_task_shell/pull/63 to fix this.
