### ISSUE TITLE
Add CLI flag to disable internal writes to stdio streams

### ISSUE THREAD

**Issue by jsejcksn** [denoland/deno#16804]
Over time, quite a few features have been developed into Deno which provide informational messaging output to standard I/O streams: either `stderr` or `stdout`.

Some of these have corresponding environment variables to control them — for example: [version updates](https://github.com/denoland/deno/pull/16375)

while others do not — for example: [runtime argument checking for specific strings](https://github.com/denoland/deno/pull/16734)

Those examples represent just two of many cases, and — while all of these can be very helpful messages in certain cases — there are also scenarios where the user needs to have complete control over the stdio streams and ensure that Deno won't hijack them under any circumstance — for example: in programs where `stderr` and `stdout` are both used for different, specific communication data — and where any writes to those streams would corrupt that communication.

I would like to see a flag that prevents Deno from using those streams **entirely, for any reason** — except, of course, for uses by the user in the runtime script itself.

Such a flag would also necessarily opt in to other behavior — for example: `--no-prompt`, as otherwise the process would just hang on an attempt to use a feature behind an ungranted permission.

**Comment by sigmaSd** [comment]
Does `--quiet` flag not acheive that?

**Comment by sigmaSd** [comment]
But maybe it doesn't catch all cases, I think your request is very valid

**Comment by jsejcksn** [comment]
> Does `--quiet` flag not acheive that?

The only documentation that I find for that argument is from `deno help`, which prints:

> ```
>     -q, --quiet
>             Suppress diagnostic output
> ```

This terse information doesn't really inform me about what the argument does. I have no idea what the phrase "diagnostic output" covers. There are also no search results for "quiet" in the manual:

<img width="461" alt="Screen Shot 2022-11-25 at 06 16 09" src="https://user-images.githubusercontent.com/868251/203984202-e9370a20-d1a0-4326-9c21-4bfd6a10067a.png">

Is there a more comprehensive source of documentation? If so, I'm not sure how I'd discover it.

That said, it doesn't appear to enable the behavior that I described. Here's a test I did:

```
% echo "await Deno.lstat(import.meta.url);" > abc.ts

% deno run --quiet abc.ts
⚠️  ┌ Deno requests read access to "file:///Users/deno/abc.ts".
   ├ Requested by `Deno.stat()` API
   ├ Run again with --allow-read to bypass this prompt.
   └ Allow? [y/n] (y = yes, allow; n = no, deny) >
```

If I repeat the test, but redirect `stderr` and `stdout` to separate files, it becomes evident that a message is written to `stderr`:

```
% deno run --quiet abc.ts > abc_out 2> abc_err

% echo $?
1

% cat abc_out 

% cat abc_err
error: Uncaught PermissionDenied: Requires read access to "file:///Users/deno/abc.ts", run again with the --allow-read flag
await Deno.lstat(import.meta.url);
^
    at async Object.lstat (deno:runtime/js/30_fs.js:297:17)
    at async file:///Users/deno/abc.ts:1:1
```

So — no — it appears not. But I am curious: what is the comprehensive definition of "diagnostic output" from `deno help`?

**Comment by bartlomieju** [comment]
`--quiet` is the flag to do that. PRs are much welcome to improve documentation of the `--quiet` flag. 

Both [information about new version available](https://github.com/denoland/deno/pull/16375) and the [information about potentially incorrect flags](https://github.com/denoland/deno/pull/16734) respect this setting. If they do not then it's a bug that needs to be fixed. 

> If I repeat the test, but redirect stderr and stdout to separate files, it becomes evident that a message is written to stderr:

I'm not sure what's suggested here? That error message shouldn't be printed?

**Comment by jsejcksn** [comment]
> I'm not sure what's suggested here? That error message shouldn't be printed?

@bartlomieju Yes — you're correct — per my original message:

> Such a flag would also necessarily opt in to other behavior — for example: `--no-prompt`, as otherwise the process would just hang on an attempt to use a feature behind an ungranted permission.

As seen in the test case I shared: currently, when using the `--quiet` argument, attempts to use features behind permissions still print a permission prompt (or a terminal diagnostic to `stderr` when those descriptors are piped away from the TTY): I definitely think this is one example of violating the "quiet" instruction — I would expect the program to simply terminate silently in this state.

If the `--quiet` argument is supposed to suppress all internal writes to `stderr` and `stdout` like I described in the initial message, **then consider this a bug report and a request for review of the feature and its behavior**.

The permission prompt, upgrade prompt, and info about incorrect flag positions are just three specific case examples: What I'm asking about is a feature that actually **prevents** Deno from writing **anything** to `stderr` or `stdout` **no matter the circumstance** — unless explicitly instructed to do so by the code in the module graph that's being run.

If the scope of what I'm trying to describe is still not clear, please continue to ask pointed questions — I'm trying my best to be descriptive.

**Comment by jsejcksn** [comment]
> `--quiet` is the flag to do that. PRs are much welcome to improve documentation of the `--quiet` flag.

I would happily contribute, but I have no idea what to write — where can I learn about what it's _supposed_ to do? Clearly its behavior isn't currently aligned with what I'm asking about.

**Comment by dsherret** [comment]
This sounds like something that should be done on a case by case basis and I believe we essentially have this already.

> The permission prompt, upgrade prompt, and info about incorrect flag positions are just three specific case examples

1. Use `--no-prompt` to disabble permission prompts.
2. Use `--quiet` to disable upgrade message, downloading messages, and the message about incorrect flag positions. The `--quiet` flag is to set the logging level and not to disable permission prompts. It still shows the output of very serious errors, which in this case is the one that caused an application exit.

> As seen in the test case I shared: currently, when using the --quiet argument, attempts to use features behind permissions still print a permission prompt (**or a terminal diagnostic to stderr when those descriptors are piped away from the TTY**)

It's printing to stderr because it's throwing an error and exiting. You'll have to surround the code in a try/catch like so:

```
try {
  await main();
} catch {
  // do not show the error on exit for some reason
  Deno.exit(1);
}
```

**Comment by jsejcksn** [comment]
> Is there any prior art in other runtimes/languages that allows such behavior?

I haven't worked with many other interpreted languages, so I can't say — but with every compiled language that I've used (e.g. C, Rust, etc.) and with shell scripts (e.g. bash, zsh, etc.) what I'm describing is the default behavior — the compilers don't automatically insert any code that prints messages when my program runs unless I explicitly write program code to do so (and it's the same with shell scripts). In those environments, I (as the runtime code author) have exclusive control over what is written to `stderr` and `stdout` when my programs run, and I can rely on that fact when I am piping processes together.

**Comment by dsherret** [comment]
> I can't be positive that Deno won't inadvertently hijack my inter-process communication

The permission prompts don't prompt if not a tty, the update checker does not output if not a tty, and the logging messages are sent over stderr. For IPC, receive on stdin, send on stdout, then use stderr for diagnostics (logging messages). All of Deno's logging should be done on stderr so you shouldn't have any issues.

**Comment by jsejcksn** [comment]
> > I can't be positive that Deno won't inadvertently hijack my inter-process communication
> 
> The permission prompts don't prompt if not a tty, the update checker does not output if not a tty, and the deno logging messages (like downloading) are sent over stderr. For IPC, receive on stdin, send on stdout, then use stderr for diagnostics (logging messages). All of Deno's logging should be done on stderr so you shouldn't have any issues. Open a bug if you find something with `deno run` outputting to stdout.

@dsherret First — thank you for that information: very useful!

I understand that you are prescribing to only use `stdout` for IPC, but that wouldn't be necessary if Deno didn't take the liberty of writing to `stderr`. I would like a mode that prevents that behavior so I can reserve the stream for my own use (like I can in [the other environments I described above](https://github.com/denoland/deno/issues/16804#issuecomment-1327572783)). Even if I choose to use `stderr` exclusively for error-related diagnostic logging, I might want to use a specific machine-readable streaming format for future automated analysis of problems, and Deno's writing to that descriptor would corrupt my data stream.

**Comment by sigmaSd** [comment]
Is `--no-prompt --quiet`  still not enough ? the error you're showing is a result of an exception which seems reasonable, rust also has its own messages on panic

**Comment by dsherret** [comment]
I believe using `--quiet` should handle that case. Then you'll need to ensure none of the code you use does any `console.log/error/warn` calls and surround your top level code in a `try/catch` to catch fatal errors and handle them another way.

**Comment by jsejcksn** [comment]
> Is `--no-prompt --quiet` still not enough ? the error you're showing is a result of an exception which seems reasonable, rust also has its own messages on panic

@sigmaSd Good point — that's true, but [even panic behavior can be silenced/modified in Rust](https://users.rust-lang.org/t/suppress-panic-message/6303).

**Comment by dsherret** [comment]
Use `try/catch` in Deno then:

```
addEventListener("unhandledrejection", (e) => {
  e.preventDefault();
});
```

**Comment by lucacasonato** [comment]
I am going to close this. To summarize:

- `--quiet` suppressed all diagnostic/info/warn messages
- `--no-prompt` (and output not being a TTY) supresses permission prompts
- There is no flag to disable printing of errors and stack traces when an application crashes. You can do this from user code using the `"error"` and `"unhandledrejection"` events.
- Panics always print output, there is no way to disable this.

And we are not going to add any other flags for this, because I think this is enough to satisfy your usecase.
