### ISSUE TITLE
lsp: Deno lsp does not support clients without the `workspaceConfiguration` setting.

### ISSUE THREAD

**Issue by lino-levan** [denoland/deno#16824]
Close if a duplicate or already discussed somewhere.

[The Deno docs](https://deno.land/manual@v1.28.2/advanced/language_server/overview#settings) strongly imply that the Deno LSP works with clients that don't implement the `workspaceConfiguration` call.

> When the language server receives a workspace/didChangeConfiguration notification, it will assess if the client has indicated if it has a workspaceConfiguration capability. If it does, it will send a workspace/configuration request which will include a request for the workspace configuration as well as the configuration of all URIs that the language server is currently tracking.

> If the client has the workspaceConfiguration capability, the language server will send a configuration request for the URI when it received the textDocument/didOpen notification in order to get the resources specific settings.

> If the client does not have the workspaceConfiguration capability, the language server will assume the workspace setting applies to all resources.

According to the good folks over at lapce, they cannot support Deno (presumably without significant dev work), with this being the case.

> [We can't support deno] because deno lsp doesn't work without workspaceConfiguration

They also claim to say that this is already known by the team at Deno, but I can't find any discussions/issues on GitHub or any discussion in the discord related to this. There is [this issue](https://github.com/denoland/deno/issues/14455) that seems to mention this being an issue on some roadmap but there has not been much attention to it.

To get to the concrete issue one of the following is true: 
1. the docs are poorly worded, #14455 is still relevant, and editors like lapce can't support deno
2. #14455 was changed/fixed at some point and editors like lapce have not gotten the memo yet

I'm hoping that either the docs can be updated for clarity or for some clarification on where the lsp workspace rework is on the roadmap.

**Comment by nayeemrmn** [comment]
Fixed by #20358.
