### ISSUE TITLE
Some npm package doesn't work after upgrade to 1.28.2

### ISSUE THREAD

**Issue by zuisong** [denoland/deno#16832]
demo code
```ts
// fileName hello.ts
import "npm:fflate"
// deno run -A  hello.ts
```
it rise a error at deno 1.28.2, and it works at deno 1.28.1 .

1.28.2 ci log,  does not work  https://github.com/zuisong/notion-kroki/actions/runs/3547282827

1.28.1 ci log , works ok  https://github.com/zuisong/notion-kroki/actions/runs/3538171725

error log
```
error during build:
Error: The argument 'filename' must be a file URL object, file URL string, or absolute path string. Received /
    at createRequire (deno:ext/node/02_require.js:832:15)
    at file://node_modules/.deno/fflate@0.7.4/node_modules/fflate/esm/index.mjs:2:15
```

error line
```js
import { createRequire } from 'module';
var require = createRequire('/');  <-- this line error
```

**Comment by zuisong** [comment]
Maybe it is related to this PR? 
https://github.com/denoland/deno/pull/16682

**Comment by bartlomieju** [comment]
@kt3k can you take a look?

**Comment by kt3k** [comment]
Sure
