### ISSUE TITLE
bug: `__proto__` behaves differently from Chrome, Node, and Firefox

### ISSUE THREAD

**Issue by KnorpelSenf** [denoland/deno#16833]
For some reason, Deno 1.28.2 behaves differently regarding the `__proto__` property.

### Deno
```bash
$ deno
Deno 1.28.2
exit using ctrl+d, ctrl+c, or close()
> let p = '__proto__'
undefined
> let o = {}
undefined
> o
{}
> o[p] = 3
3
> o
{ __proto__: 3 }
>
```
### Node
```bash
$ node
Welcome to Node.js v18.9.0.
Type ".help" for more information.
> let p = '__proto__'
undefined
> let o = {}
undefined
> o
{}
> o[p] = 3
3
> o
{}
>
```
### Google Chrome 107.0.5304.110
![image](https://user-images.githubusercontent.com/12952387/204101121-ef5763be-75e6-4c51-b209-29161e190ec8.png)

### Firefox 102.5.0esr
![image](https://user-images.githubusercontent.com/12952387/204101171-2362aab7-d8d7-45a9-88dc-8b9983922757.png)

**Comment by KnorpelSenf** [comment]
Before anyone asks: no, this is not related to having a newer version of V8. Here is the same bug with a much older version:

```bash
$ deno
Deno 1.12.0
exit using ctrl+d or close()
> let p = '__proto__'
undefined
> let o = {}
undefined
> o
{}
> o[p] = 3
3
> o
{ __proto__: 3 }
> 
```

```bash
$ deno --version 
deno 1.12.0 (release, x86_64-unknown-linux-gnu)
v8 9.2.230.14
typescript 4.3.2
```

**Comment by bartlomieju** [comment]
It's not a bug, Deno explicitly doesn't have support `__proto__`, see compat table in https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/proto.

Related https://github.com/denoland/deno/pull/16775

**Comment by KnorpelSenf** [comment]
Fascinating. The background of this issue is that `assertEquals` from /std fails on Node when compiled by dnt, but it works on Deno. It seems like that is the case because `assertEquals` converts objects to strings and then compares strings.

This issue will be fixed by #16775. I have opened https://github.com/denoland/dnt/issues/235 on the dnt repo.

**Comment by khrj** [comment]
Note that #16775 won't completely fix this: The setter will simply warn and fail. `Object.setPrototypeOf` should be used instead

**Comment by dsherret** [comment]
See https://github.com/denoland/deno/issues/4324 for more details.
