### ISSUE TITLE
bug: polyfill will request unnecessary permissions

### ISSUE THREAD

**Issue by idanran** [denoland/deno#16848]
```ts
import sc from 'npm:supports-color@latest'

console.log(sc)
```
![image](https://user-images.githubusercontent.com/96647698/203900560-7af35a3b-c23f-41c3-83fa-4f197e6d8b11.png)
![image](https://user-images.githubusercontent.com/96647698/203900639-66f50271-ef43-4fab-90ea-f742322c8aad.png)
supports-color/9.2.3/index.js:8:24
![image](https://user-images.githubusercontent.com/96647698/204203749-07572d5c-cfe4-4bdd-8ad9-4abadf6fa6a2.png)
supports-color/9.2.3/index.js:17:2
![image](https://user-images.githubusercontent.com/96647698/204204000-ae13b572-52b8-42f4-97e5-0b0cbd246995.png)

**Comment by bartlomieju** [comment]
`process.argv` consists of path to the current binary and main module - both of them require read permissions. There seems nothing wrong
