### ISSUE TITLE
Detect disconnection by `Deno.Conn` remote client

### ISSUE THREAD

**Issue by shevernitskiy** [denoland/deno#16844]
It is easy to handle incoming connections of the listener with async iterator (we get Deno.Conn and do the stuff)
But how can I detect remote client disconnection?

**Comment by sigmaSd** [comment]
Its seems like when `await conn.read() === null` the remote client has disconnected, not sure if this is guaranteed though

**Comment by shevernitskiy** [comment]
I got the same `os error 10053` on read as on while i'm trying use write (like i did before). So is there only polling approach?
No chance to catch kinda event?

**Comment by sigmaSd** [comment]
I don't think tcp has such feature , maybe some other network protocol has it

**Comment by shevernitskiy** [comment]
Ok, thanks
