### ISSUE TITLE
Fetch allow modifying Host header

### ISSUE THREAD

**Issue by Tc-001** [denoland/deno#16840]
Currently it is impossible to modify the Host header when calling `fetch()`.

This is *not* a duplicate of #11017 , because that asked to disallow the header to be modified, while I am requesting for a way to allow modifying it.

It is needed for us to communicate with an internal system that only ever expects the `Host` header to be an external-facing domain. (a reverse proxy or changing the machines `/etc/hosts` seems a bit overkill)

It could be part of `Deno.createHttpClient` (`{allowCustomHost: true}` or similar) as described in https://github.com/denoland/deno/issues/6868#issuecomment-762013710

**Comment by gbrlmtrz** [comment]
I am also facing similar issues when trying to reach a service on kubernetes, is there any way to set this header on Deno?
