### ISSUE TITLE
Property 'xxx' does not exist on type 'object'.

### ISSUE THREAD

**Issue by Lesiuk** [denoland/deno#16851]
Deno version: 1.18.2

Deno code:
```
import caseInsensitive from 'npm:case-insensitive';
import {assert} from "https://deno.land/std@0.165.0/testing/asserts.ts";

assert(caseInsensitive('TeSt').includes('test'))
```

Result:
```
error: TS2339 [ERROR]: Property 'includes' does not exist on type 'object'.
assert(caseInsensitive('TeSt').includes('test'))
                               ~~~~~~~~
    at file:///Users/xxx/WebstormProjects/xxx/test.ts:4:32
```

I checked the repository of this package, and it only contains a single index.js file. There are no types, so why this import is an object instead of any?

https://github.com/lamansky/case-insensitive/blob/master/index.js

**Comment by Lesiuk** [comment]
I don't know if I should report next issue but there is also something fishy with leaky-bucket package.

Deno:
```
import LeakyBucket from 'npm:leaky-bucket';

const bucket = new LeakyBucket({
    capacity: 10,
    interval: 60,
    timeout: 120,
});
```
```
error: TS2345 [ERROR]: Argument of type '{ capacity: number; interval: number; timeout: number; }' is not assignable to parameter of type 'number'.
const bucket = new LeakyBucket({
```

leaky-bucket does not have types, but its constructor is definitely valid. 
https://github.com/linaGirl/leaky-bucket/blob/master/src/LeakyBucket.js

Where deno gets this 'number' from?

**Comment by Iuriiiii** [comment]
I tested it and you are right, the compilation of that code within a .ts file generates that error. I suggest you to make your own .d.ts file for that npm library, that should fix the error.

The same for the first error example.

Whetever, the compiler should throw a better error if the declaration are not found.
