### ISSUE TITLE
Run deno repl with Deno banner line suppressed (or changed)

### ISSUE THREAD

**Issue by lem0nify** [denoland/deno#16868]
Is it possible to run the Deno REPL, preventing the first line from being output like "Deno 1.28.2"?

I tried `deno repl | tail -n +2`, but this makes the output line-by-line and breaks interactivity: I can't see the command I'm typing.

Use case: I am writing a large toolkit consisting of many independent functions and I want to allow the user to use them interactively from within the REPL. At the same time, I would like my own banner to be displayed on the first line, instead of (or, at least, in addition to) Deno's banner. Of course, I could write my own REPL for this, but why, when the Deno REPL fits perfectly?

In Python, for example, we can write the following script:
```python
from code import interact

def hello():
    print('Hello, world!')

# locals to inject:
_locals = {
    'hello': hello
    # ...
}

interact(banner='Our own fantastic banner message', local=_locals)
```
and run the program through it.

It would be great to have the same functionality in Deno, or at least the ability to replace the default banner via an environment variable or command line option.

**Comment by bartlomieju** [comment]
I guess we can respect `--quiet` option here. Related PRs that are more output https://github.com/denoland/deno/pull/16800 and https://github.com/denoland/deno/pull/16795. @dsherret thoughts?

**Comment by dsherret** [comment]
Yeah, seems reasonable.
