### ISSUE TITLE
Failed on update on Windows due to access denied error

### ISSUE THREAD

**Issue by shevernitskiy** [denoland/deno#16886]
Got this issue even with Administrator rights. 

```ps1
PS C:\Users\mahah> deno upgrade
Looking up latest version
Found latest version 1.28.3
Checking https://github.com/denoland/deno/releases/download/v1.28.3/deno-x86_64-pc-windows-msvc.zip
28.6 MiB / 28.6 MiB (100.0%)
Deno is upgrading to version 1.28.3
error: Отказано в доступе. (os error 5)
PS C:\Users\mahah>
```

Error text - Access denied.
This is first time since ~v1.10

**Comment by Seally** [comment]
> Does the same error occur when you run this? (beware this will kill any running deno processes)
> 
> ```
> Stop-Process -Name deno ; deno upgrade
> ```

Having a Deno instance running was my first thought too, but I just tried it on my end (1.28.2 -> 1.28.3) with all instances stopped and the same error happens too. Downloading the executable manually and replacing it using a file manager works fine.

**Comment by Seally** [comment]
None of them were running when I tried it.

**Comment by shevernitskiy** [comment]
> Does the same error occur when you run this? (beware this will kill any running deno processes)
> 
> ```
> Stop-Process -Name deno ; deno upgrade
> ```

Yep, found hanging deno procces. Successful upgrade after killing.
