### ISSUE TITLE
How is the stability of deno at present?

### ISSUE THREAD

**Issue by shubulan** [denoland/deno#16897]
I'm going to use deno to develop some software. This software may be used by many people.

I noticed that many companies are paying attention to the project of deno https://github.com/denoland/deno/wiki # companies-interested-in-deno. 
But I want to know, at present, how is the stability of deno? Are there mature commercial projects using deno?
In addition, my software may run on mobile platforms, including android and ios. I see that deno can cross linux, windows and mac platforms. I would like to ask, is it feasible to migrate deno to a mobile platform?

**Comment by dsherret** [comment]
> But I want to know, at present, how is the stability of deno?

Just don't use `--unstable` if you need stability. https://deno.land/manual@v1.28.3/runtime/stability

> Are there mature commercial projects using deno?

Yes.

> In addition, my software may run on mobile platforms, including android and ios. I see that deno can cross linux, windows and mac platforms. I would like to ask, is it feasible to migrate deno to a mobile platform?

No, it doesn't run on mobile platforms at this time.
