### ISSUE TITLE
Deno.Command#spawn stdout/err pipes should be `inherit` by default?

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#16891]
This was surprising to me:

```ts
const command = new Deno.Command(Deno.execPath(), {
  args: [
    "eval",
    "--unstable",
    "--no-check",
    code,
  ],
  stdout: "piped",
});

const child = command.spawn();
// etc...
```

Then in the test output:

```ts
error: AssertionError: Test case is leaking 1 resource:

 - A child process stderr (rid 90) was opened during the test, but not closed during the test. Close the child process stderr by calling `proc.stderr.close()` or `await child.stderr.cancel()`.

    at assert (deno:ext/web/00_infra.js:295:13)
    at resourceSanitizer (deno:cli/js/40_testing.js:413:7)
    at async exitSanitizer (deno:cli/js/40_testing.js:431:9)
    at async Object.applyPermissions [as fn] (deno:cli/js/40_testing.js:533:9)
    at async runTest (deno:cli/js/40_testing.js:836:7)
    at async runTests (deno:cli/js/40_testing.js:1091:22)
```

I would have expected that if I don't set `stderr` to `"piped"` explicitly, then it would be "inherit". I don't think "piped" should be the default in this case because I believe it could lead to a deadlock if `stderr`'s buffer fills up since nothing is reading from it. Plus, in this case it means I have to explicitly handle it.

cc @crowlKats, what is the correct behaviour here?

**Comment by crowlKats** [comment]
"piped" was picked as default after various discussion in the original proposal as it is the most likely case someone wanting the option to be

**Comment by dsherret** [comment]
It seems quiet dangerous for us to have it as the default for `.spawn()` since someone might forget to actively read the pipes leading to a potential deadlock. I think we should change it. For `output()` and `outputSync()` I think it makes sense for it to be "piped" by default.

**Comment by sigmaSd** [comment]
What about `stdin: "inherit"` in spawn by default? I run on a couple of cases where I expected that

**Comment by dsherret** [comment]
I’m not sure and haven’t really thought about it (for readers, current default is “null”). Maybe open a new issue outlining some reasons why? One point might be that Rust’s `Command` api defaults to “inherit” for stdin when using spawn (https://doc.rust-lang.org/std/process/struct.Command.html#method.stdin)

**Comment by dsherret** [comment]
I opened https://github.com/denoland/deno/issues/17230
