### ISSUE TITLE
Global promise rejection handling

### ISSUE THREAD

**Issue by frdel** [denoland/deno#16907]
Hello. Is there way to handle promise rejections/throws globally?
This little code snippet bellow will crash the server, which is very unfortunate, because it is just a forgotten await on one of the promises.

Thank you.

`let a = new Promise((resolve, reject) => {
  throw "errA";
});
let b = new Promise((resolve, reject) => {
  throw "errB";
});
let c = new Promise((resolve, reject) => {
  throw "errC";
});

//this will work
try {
  const W = await Promise.all([a, b, c]);
} catch (e) {
  console.error(e);
}

a = new Promise((resolve, reject) => {
  throw "errA";
});
b = new Promise((resolve, reject) => {
  throw "errB";
});
c = new Promise((resolve, reject) => {
  throw "errC";
});

//this will crash
try {
  const W = await Promise.all([a, c]);
} catch (e) {
  console.error(e);
}

while (true) {
  await new Promise((resolve) => setTimeout(resolve, 100));
}`

**Comment by bartlomieju** [comment]
See https://deno.land/manual@v1.28.3/runtime/program_lifecycle#unhandledrejection-event-example

**Comment by frdel** [comment]
Thans for the reply,unfortunately it does not help.
Even with adding this handler the process still exits.

globalThis.addEventListener("unhandledrejection", (e) => {
  console.log("unhandled rejection");//, e.promise, "reason:", e.reason);
  e.preventDefault();
});

let a = new Promise((resolve, reject) => {
  throw "errA";
});
let b = new Promise((resolve, reject) => {
  throw "errB";
});
let c = new Promise((resolve, reject) => {
  throw "errC";
});

//this will work
try {
  const W = await Promise.all([a, b, c]);
} catch (e) {
  console.error(e);
}

a = new Promise((resolve, reject) => {
  throw "errA";
});
b = new Promise((resolve, reject) => {
  throw "errB";
});
c = new Promise((resolve, reject) => {
  throw "errC";
});

//this will crash
try {
  const W = await Promise.all([a, c]);
} catch (e) {
  console.error(e);
}

while (true) {
  await new Promise((resolve) => setTimeout(resolve, 100));
}

**Comment by bartlomieju** [comment]
That's expected behavior - once the timeout fires after 100ms, there's nothing keeping event loop alive

**Comment by frdel** [comment]
I have to disagree. If you comment out the second set of promises, the process keeps running. This is a simplified script to simulate the situation, this crashes my oak server.

**Comment by bartlomieju** [comment]
I missed the `while (true)` there. Here's the code I'm running:
```js
globalThis.addEventListener("unhandledrejection", (e) => {
    console.log("unhandled rejection");//, e.promise, "reason:", e.reason);
    e.preventDefault();
});

let a = new Promise((resolve, reject) => {
  throw "errA";
});
let b = new Promise((resolve, reject) => {
  throw "errB";
});
let c = new Promise((resolve, reject) => {
  throw "errC";
});

//this will work
try {
  const W = await Promise.all([a, b, c]);
} catch (e) {
  console.error(e);
}

a = new Promise((resolve, reject) => {
  throw "errA";
});
b = new Promise((resolve, reject) => {
  throw "errB";
});
c = new Promise((resolve, reject) => {
  throw "errC";
});

//this will crash
try {
  const W = await Promise.all([a, c]);
} catch (e) {
  console.error(e);
}

while (true) {
  await new Promise((resolve) => setTimeout(resolve, 100));
}

```

```
$ deno run foo.js
errA
errA
unhandled rejection
```

The process doesn't end, I have to stop it manually. Which version of Deno are you using?

**Comment by frdel** [comment]
You are correct, it is a version issue. Now I am sorry to waste your time. Thank you very much.

My version was:
deno 1.20.6 (release, x86_64-apple-darwin)
v8 10.0.139.6
typescript 4.6.2

I can confirm that this code is working as expected on:
deno 1.28.3 (release, x86_64-apple-darwin)
v8 10.9.194.5
typescript 4.8.3

**Comment by bartlomieju** [comment]
No problem, good to know it's working as expected. [We added this functionality in v1.24](https://deno.com/blog/v1.24#unhandledrejection-event)
