### ISSUE TITLE
Cache bust npm specifiers more aggressively

### ISSUE THREAD

**Issue by oscarotero** [denoland/deno#16901]
Everytime I want to update any NPM package to the latest version, I get the following error:

```
Could not find npm package 'lightningcss-wasm' matching 1.17.1. Try retrieving the latest npm package information by running with --reload
```

Is there any way to update it without need to add the `--reload` flag? It's very unconvenient for Lume users.

**Comment by dsherret** [comment]
We've talked about cache busting when someone uses a new npm specifier. Would that work in this scenario?

**Comment by oscarotero** [comment]
If I understand correctly, if I'm using `npm:lightningcss-wasm@1.17.0` and then change it to `npm:lightningcss-wasm@1.17.1`, it's considered a new npm specifier, so it doesn't use the old cache, right? In that case, I guess it shoud work.

**Comment by dsherret** [comment]
Yeah, in that scenario it would requery npm for the latest package information for everything (just package information and would not redownload package tarballs).

**Comment by dsherret** [comment]
https://github.com/denoland/deno/pull/18622 should help a lot with this, but it doesn't fully solve the problem.
