### ISSUE TITLE
Dynamic import prevents unhandled rejection handling

### ISSUE THREAD

**Issue by frdel** [denoland/deno#16909]
This issue is very peculiar, I have narrowed it down as much as possible.
If I use dynamic import via `import()`, global `unhandledrejection` event stops working. If I comment the `dummyImport` line out, it works as expected. It does not matter what's inside the imported module, in my case it is a dummy object.
Thank you.

Main code:
```typescript
globalThis.addEventListener("unhandledrejection", (e) => {
  console.log("unhandled rejection"); //, e.promise, "reason:", e.reason);
  e.preventDefault();
});

const dummyImport = (await import("./import.ts")).default;

let a = new Promise((resolve, reject) => {
  throw "errA";
});

while (true) {
  await new Promise((resolve) => setTimeout(resolve, 1000));
  console.log("running...");
}
```

And the `./import.ts` file:
```typescript
export default {
  a: "a",
};
```

Output with dynamic import: 
```
error: Uncaught (in promise) "errA"
Process exited with code 1
```

and without dynamic import line:
```
unhandled rejection
running...
```

Deno version:
```
deno 1.28.3 (release, x86_64-apple-darwin)
v8 10.9.194.5
typescript 4.8.3
```

**Comment by bartlomieju** [comment]
@cjihrig seems we forgot to handle dynamic imports when implementing `unhandledrejection` :)

**Comment by bartlomieju** [comment]
I've been testing this in the browser and I can't get it to work in any way - the `unhandledrejection` event is never fired in this case.

**Comment by bartlomieju** [comment]
Possibly related https://github.com/denoland/deno/issues/15661
