### ISSUE TITLE
http2 error: stream error detected: unspecific protocol error detected

### ISSUE THREAD

**Issue by ndaidong** [denoland/deno#16923]
This is a strange error, occurred while sending requests from Deno to a HTTPS endpoint with [Caddy server](https://caddyserver.com/).

Although I have found the broken point to fix, but still don't understand the root cause. So I share the problem here, maybe it makes sense to someone, such as the experts behind this project.

Let's start with this simple script to test request:

```js
const url = 'https://bongnguoi.one'

const res = await fetch(url)
const content = await res.text()
console.log(content)
```

In which, the target `https://bongnguoi.one` just contains a simple static content as below:

![Screenshot from 2022-12-04 13-46-07](https://user-images.githubusercontent.com/1809619/205478277-7b2abd22-fd90-4173-8a4c-70691d74bd51.png)

This is relevant Caddyfile on server:

```
{
  debug
}

www.bongnguoi.one {
    redir https://bongnguoi.one{uri}
}

bongnguoi.one {
    root * /workspace/html/default
    file_server

    header X-Forwarded-For $proxy_add_x_forwarded_for
    header Host $host
    header Upgrade $http_upgrade
    header Connection "upgrade"
}
```

When I run above script with Deno:

```sh
deno run --allow-net run.js
```
It throws error :

![Result 1: `Failure`](https://user-images.githubusercontent.com/1809619/205477846-6c0b738e-ea2b-4fab-84a7-043e444d6f2d.png)

In order to avoid error, I can choose on of 2 options to modify Caddyfile.

### 1. Remove header upgrade config

```diff
{
  debug
}

www.bongnguoi.one {
    redir https://bongnguoi.one{uri}
}

bongnguoi.one {
    root * /workspace/html/default
    file_server

    header X-Forwarded-For $proxy_add_x_forwarded_for
    header Host $host
-    header Upgrade $http_upgrade
    header Connection "upgrade"
}
```

Now the script works:

![Result 2: `Success`](https://user-images.githubusercontent.com/1809619/205477857-9e4f870e-e679-406f-ba1a-7e02f81fad9f.png)

### 2. Keep header upgrade, but remore `h2` support

```diff
{
  debug
  
+  servers :443 {
+   protocols h1 h2c h3
+  }
}

www.bongnguoi.one {
    redir https://bongnguoi.one{uri}
}

bongnguoi.one {
    root * /workspace/html/default
    file_server

    header X-Forwarded-For $proxy_add_x_forwarded_for
    header Host $host
+    header Upgrade $http_upgrade
    header Connection "upgrade"
}
```

After changing, the script works well too.

What are `h1`, `h2`, `h3`? They are options to specify which HTTP protocols to support, as you can [refer this link](https://caddyserver.com/docs/caddyfile/options#protocols).

![Screenshot from 2022-12-04 14-47-57](https://user-images.githubusercontent.com/1809619/205480010-65644a6a-cd4b-4383-a6b2-76570901c09a.png)

### Provisional conclusion

Deno `fetch` denies to keep connection to server when it discovers `upgrade` header from a HTTP/2 response. According to  [MDN docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Upgrade), `upgrade` header is specific to HTTP 1.1 only.

That's all what I want to share. 

Why I don't think it's Caddy's problem? Because the same script works as normal with Node.js and Bun, without modifying Caddy config.

**Comment by NovqiGarrix** [comment]
Got the same issue while I'm trying to upload a file using Axios to Google Drive. I also use Caddy, and I deploy them to Digital Ocean.

Caddyfile
`example.com {
    reverse_proxy web:4000 {
        header_down Strict-Transport-Security max-age=31536000;
    }
}`

Upload function
`async uploadFile(params: UploadFileParams): Promise<DriveItem> {
        const {
            accessToken,
            buffer,
            filename,
            onUploadProgress,
            parentId,
            signal,
        } = params;

        const formData = new FormData();

        const metadata = {
            name: filename,
            parents: parentId ? [parentId] : undefined,
            mimeType: mime.lookup(filename) || "application/octet-stream",
        };

        formData.append(
            "metadata",
            new Blob([JSON.stringify(metadata)], {
                type: "application/json; charset=UTF-8",
            }),
        );

        formData.append(
            "file",
            new Blob([buffer], {
                type: metadata.mimeType,
            }),
        );

        const { data, status, statusText } = await axios.post(
            `https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart`,
            formData,
            {
                signal,
                onUploadProgress,
                headers: {
                    "Content-Type": "multipart/form-data",
                    "Authorization": `Bearer ${accessToken}`,
                },
                validateStatus: () => true,
            },
        );

        return data;
    }`

Error message:
`error sending request for url (https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart?uploadType=multipart): http2 error: stream error received: unspecific protocol error detected`

Deno Version: deno 1.33.3 (release, x86_64-unknown-linux-gnu)
v8 11.4.183.2
typescript 5.0.4

**Comment by pvillaverde** [comment]
Hey there! I upgraded an app to Deno 1.33 today and with this version I'm getting this error while fetching a simple RSS url from Youtube:
```
[TypeError: error sending request for url (https://www.youtube.com/feeds/videos.xml?channel_id=XXXX): http2 error: stream error received: unspecific protocol error detected]
```
Going back to 1.32.5 fixed the issue for now. I've checked the changelog but didn't see any breaking change announced regarding requests... Any idea what can be the issue?

**Comment by bartlomieju** [comment]
@pvillaverde could you show your full code? It's hard hard to say what's going on without seeing a full reproduction.

**Comment by tian-sheng-low** [comment]
@bartlomieju 
Hi, I have a project that uses [rollbar.js](https://github.com/rollbar/rollbar.js/) and it works perfectly before Deno v1.33.4
Deno v1.33.4 & v1.34.0(current version), this `http2 error: stream error detected: unspecific protocol error detected` occurs whenever I try to send an item to rollbar via [rollbar.js](https://github.com/rollbar/rollbar.js/)

However, when I use Deno built-in http request to send an item to rollbar, it works even after Deno v1.33.4
Maybe they is some compatibility issues in the recent releases.
Any resolution will be appreciated.

The code used in Deno.
```typescript
import Rollbar from 'rollbar'

const rb = new Rollbar(...)
rb.error("error")
```

For more details, I debug and found that the error occurs around here.
https://github.com/rollbar/rollbar.js/blob/e964ecbdb16a4d2b8b5feaa8b70a2ec327648ed0/src/server/transport.js#L57-L95

**Comment by pvillaverde** [comment]
> @pvillaverde could you show your full code? It's hard hard to say what's going on without seeing a full reproduction.

Apologies, I thought I had sent the answer to this but it seems I forgot to press the comment button... I had written a test file but it's gone now... however the problem in this case I believe it was either with the axios library I was using for the queries or perhaps related with the issue I reported in https://github.com/denoland/deno/issues/19274. I removed axios and replace the queries with the default "fetch" and it worked perfectly, and one less dependency for the app, so win-win

**Comment by bartlomieju** [comment]
> @bartlomieju Hi, I have a project that uses [rollbar.js](https://github.com/rollbar/rollbar.js/) and it works perfectly before Deno v1.33.4 Deno v1.33.4 & v1.34.0(current version), this `http2 error: stream error detected: unspecific protocol error detected` occurs whenever I try to send an item to rollbar via [rollbar.js](https://github.com/rollbar/rollbar.js/)
> 
> However, when I use Deno built-in http request to send an item to rollbar, it works even after Deno v1.33.4 Maybe they are some compatibility issues in the recent releases. Any resolution will be appreciated.
> 
> The code used in Deno.
> 
> ```ts
> import Rollbar from 'rollbar'
> 
> const rb = new Rollbar(...)
> rb.error("error")
> ```
> 
> For more details, I debug and found that the error might be occurring around here. https://github.com/rollbar/rollbar.js/blob/e964ecbdb16a4d2b8b5feaa8b70a2ec327648ed0/src/server/transport.js#L57-L95

Thanks, this is useful. We'll debug and fix it.

**Comment by tian-sheng-low** [comment]
@bartlomieju 
As additional information, rollbar.js works only when using package.json or npm specifier.
CDN import such as esm.sh does not work even under Deno v1.33.3.

**Comment by bartlomieju** [comment]
> @bartlomieju As additional information, rollbar.js works only when using package.json or npm specifier. CDN import such as esm.sh does not work even under Deno v1.33.3.

Thanks for the info, but that's unrelated to the problem at hand. We don't control esm.sh so I can't really say what's going on in there (though I suspect it's because esm.sh uses an old version of compatibility layer that is now built into the runtime itself).

**Comment by sylc** [comment]
I came across this as well. Another example that can maybe help

```
#!/usr/bin/env -S deno run -A
import axios from "npm:axios"

await axios.get('https://google.com')
  .then(function (response) {
    // handle success
    console.log('success');
  }).catch(err => {
    console.log('error', err.cause)
  })
```

<img width="1142" alt="image" src="https://github.com/denoland/deno/assets/10268458/2cb2b408-dd22-46e6-a98b-ae725b114d0f">
