### ISSUE TITLE
Node: Sending chunked responses

### ISSUE THREAD

**Issue by gffuma** [denoland/deno#16929]
When using node req/res seems that responses are not chunked.
An example:

```js
import express from 'express'

const app = express()

app.use('*', (req, res) => {
  res.header('transfer-encoding', 'chunked')
  res.write('<html><h1>Hello...</h1></html>')
  setTimeout(() => {
    res.write('...World')
    res.end()
  }, 1000)
})

app.listen(4000)
```

When running on NodeJS response is chunked correctly ... If you open `http://localhost:4000` in a browser you will see:

**Hello** 
one second passed
...World

From the example above replace the import with:
```import express from 'npm:express'```

Then run:
```sh
deno run -A  --unstable server.js
```

Now the response isn't chunked if your open `http://localhost:4000` you have to wait 1 seconds then see all output.

**Comment by exside** [comment]
This issue jumped into my eyes when i wanted to open a new one, my problem/question goes kind of in the same direction. I'm re-implementing features I had with an old (dev) server for node that I'm rewriting/replacing in deno, there is this part for chunked responses / `headers.range` requests (particularly important when serving/streaming video/audio files that should support scrubbing back and forth within the file trough the playbar in the frontend):

```
					if (req.headers.range) {
						var parts = req.headers.range.replace(/bytes=/, "").split("-");
						
						var start = +parts[0];
						var end = parts[1] ? +parts[1] : stats.size - 1;
						console.log('"' + path + '" SERVED! RANGE: ' + start + ' - ' + end);
						
						res.writeHead(206, {
							'accept-ranges': 'bytes',
							'access-control-allow-origin': '*',
							'content-length': (end - start) + 1,
							'content-range': 'bytes ' + start + '-' + end + '/' + stats.size,
							'content-type': contentType,
							'last-modified': stats.mtime.toUTCString(),
						});
						return _fs.createReadStream(`${process.cwd()}${path}`, { start: start, end: end }).pipe(res);
					}
```

the critical part is this:

`return _fs.createReadStream(`${process.cwd()}${path}`, { start: start, end: end }).pipe(res);`

and the little detail i'm struggling with is finding the equivalent for that `{ start: start, end: end }` config, currently i'm using this on the deno side:

`ctx.res.body = readableStreamFromReader(file);`

setting the response body to a readable stream that gets its data form a file (serving static files), but looking at the docs (maybe i'm looking in the wrong place), i can't see it accepting such a `{ start: start, end: end }` object as a parameter? Is there any way of creating the same chunked response with Deno? Thanks in advance for pointing me in the right direction!

**Comment by gffuma** [comment]
Hey @exside from my tests if you using native Deno API streamed responses works.
For your use case i suggest you to look at https://github.com/denoland/deno_std/blob/main/http/file_server.ts#L83 that supports ranges headers and streamed responses.
I hope this can help you 😃

**Comment by bartlomieju** [comment]
@kt3k please take a look

**Comment by kt3k** [comment]
Sure
