### ISSUE TITLE
napi_add_env_cleanup_hook is not implemented

### ISSUE THREAD

**Issue by oscarotero** [denoland/deno#16925]
Hi. I have been trying to use [lighningcss](https://github.com/parcel-bundler/lightningcss) in Deno and it seems to work fine but I got some warnings in the terminal:

```
napi_add_env_cleanup_hook is currently not supported
napi_add_env_cleanup_hook is currently not supported
napi_add_env_cleanup_hook is currently not supported
napi_add_env_cleanup_hook is currently not supported
napi_add_finalizer is not yet supported.
napi_add_finalizer is not yet supported.
napi_add_finalizer is not yet supported.
napi_add_finalizer is not yet supported.
napi_add_finalizer is not yet supported.
napi_add_finalizer is not yet supported.
napi_add_finalizer is not yet supported.
napi_add_finalizer is not yet supported.
```

Node API support is marked as done in the [NPM roadmap](https://github.com/denoland/deno/issues/15960), but the [referrer issue](https://github.com/denoland/deno/pull/13633) has some Functions unmarked, like `napi_add_env_cleanup_hook` and `napi_add_finalizer`.

Is there any plans to implement them?

**Comment by bartlomieju** [comment]
CC @littledivy

**Comment by bartlomieju** [comment]
These still exist, but can be silenced with `--quiet` flag. We will finally implement them, but can't give any time horizon for it.

**Comment by oscarotero** [comment]
Ok. Is it ok to silence them? I'm not familiarized with Node API and what these functions do, but if they are not implemented, I guess the package won't work properly.

**Comment by bartlomieju** [comment]
To be honest I'm unsure about it, @littledivy can you take a look and lt us know?

**Comment by janpio** [comment]
Note: Prisma also is experiencing these `napi_add_env_cleanup_hook is currently not supported` outputs:

```
C:\Users\Jan\Documents\throwaway\denoRegression>deno run -A --unstable npm:prisma@4.9.0-dev.16 generate --data-proxy
  prisma:engines  binaries to download libquery-engine, migration-engine, introspection-engine, prisma-fmt +0ms
napi_add_env_cleanup_hook is currently not supported
  prisma:tryLoadEnv  Environment variables not found at null +0ms
  prisma:tryLoadEnv  Environment variables loaded from ./.env +0ms
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
napi_add_env_cleanup_hook is currently not supported
  prisma:getConfig  Using getConfig Wasm +0ms
  prisma:getConfig  config data retrieved without errors in getConfig Wasm +2ms
  ...
```

**Comment by bartlomieju** [comment]
Note to self: discussed this with Divy, there are no more blockers to implement these functions - `napi_add_env_cleanup_hook` should be straight-forward to implement, while `napi_add_finalizer` requires integration with `FinalizationRegistry` which was not available in `rusty_v8` at the time when we added Node-API support. I will look into implementing these.

**Comment by bartlomieju** [comment]
Let's track `napi_add_finalizer` in https://github.com/denoland/deno/issues/17325 and keep this issue for `napi_add_env_cleanup_hook`
