### ISSUE TITLE
Suppress unimplemented napi logs

### ISSUE THREAD

**Issue by sebmck** [denoland/deno#16932]
Hi! I'm currently experimenting with importing existing napi modules in Deno and am getting error messages such as:

```
napi_add_env_cleanup_hook is currently not supported
```

This is fine, I'm willing to tolerate whatever brokenness I encounter. But there doesn't appear to be a way to suppress these logs and they present as significant noise in the console. eg. from [`cli/napi/env.rs`](https://github.com/denoland/deno/blob/a2488ae79200abfcbad0f0f8b084a3ff8e183880/cli/napi/env.rs#L62):

```
#[napi_sym::napi_sym]
fn napi_add_env_cleanup_hook(
  _env: *mut Env,
  _hook: extern "C" fn(*const c_void),
  _data: *const c_void,
) -> Result {
  eprintln!("napi_add_env_cleanup_hook is currently not supported");
  Ok(())
}
```

### 1. Do nothing. Wait for support for the NAPI APIs

I'm sure they aren't implemented for a reason. We can tolerate the log noise if they will be in the short-term though.

### 2. Add a way to ignore them with an environment variable

This doesn't seem to warrant a dedicated CLI option so an environment variable would make the most sense. Suggestions are:

```
# Suppress all
DENO_SUPPRESS_NAPI=1

# Suppress particular method
DENO_SUPPRESS_NAPI=napi_add_env_cleanup_hook
```

There's precedent for this sort of environment variable in Node.

### 3. Suppress them automatically when `--quiet` is used

As the title implies. `--quiet` is currently described as "Suppress diagnostic output". Unsure if this would fit within the scope of that flag.

**Comment by bartlomieju** [comment]
I think going with `--quiet` is reasonable here. If that works for you I'll look into that in a moment.

**Comment by bartlomieju** [comment]
Related issue https://github.com/denoland/deno/issues/16925
