### ISSUE TITLE
[QUESTION] Can we use Deno in production? (plus Deno Deploy)

### ISSUE THREAD

**Issue by silvioprog** [denoland/deno#16946]
Hi.

I'm planning to write a REST API to provide data to a small React application, so I'm wondering about writing it in Deno. However, after reading [this](https://deno.land/manual@v1.28.3/runtime/stability), I'm not sure if we can use Deno in production. 😕

Basically, the application goal will be to handle expenses and invoices, containing some CRUD, authentication, swagger, tests etc., and maybe hosted in [Deno Deploy](https://deno.com/deploy) (free option).

Can we use Deno in such a kind of application?

TIA for any help!

**Comment by markthree** [comment]
I prefer to use [Deno Deploy](https://deno.com/deploy) to deploy static services and BFF。if the content required by the business is certain, I will also use it。Of course， all dependencies will be versioned and only use stable APIs (in Deno namespace 👀)

**Comment by dsherret** [comment]
> However, after reading [this](https://deno.land/manual@v1.28.3/runtime/stability), I'm not sure if we can use Deno in production. 😕

You can. That just says the apis under the `--unstable` flag (found here https://doc.deno.land/https://raw.githubusercontent.com/denoland/deno/main/cli/tsc/dts/lib.deno.unstable.d.ts) are subject to change in future releases, so just beware of that.
