### ISSUE TITLE
Idea: Support for NPM relative modules

### ISSUE THREAD

**Issue by oscarotero** [denoland/deno#16954]
Hi. I would like to have something like this to load relative modules in the context of a NPM package:

```js
import foo from "npm:./foo";
```

This would be useful to load npm packages that need some tweaks to work in Deno. I think it's not possible right now.

**Comment by bartlomieju** [comment]
Duplicate of https://github.com/denoland/deno/issues/15624

**Comment by dsherret** [comment]
This is the syntax we've been discussing possibly doing. Also being able to do `deno run npm:./foo`
