### ISSUE TITLE
Raw/gzipped files distribution (?)

### ISSUE THREAD

**Issue by RB-Lab** [denoland/deno#16960]
Hi, Deno folks! Not sure if this is a right place for this issue, of if it is an issue at all, or is it how it is intended to be (although I believe that at least the error messages should look differently and, probably, appear earlier (see below)). 

### Background
For some reason I started my journey in Deno Land from a bit weird place: I wanted to make the MNIST dataset package which will allow TS-lovers to try machine learning essentials with Deno. My first intent was to load datset from original [Yann LeCun's page][1] over the network and cache it in `tmp`. However I decided that that will be unnecessary external dependency: in unlikely case if Yann LeCun's page go down, user's still could download the package but it won't work. So I decided to pack gzipped versions of the data files inside the package. 

[1]: http://yann.lecun.com/exdb/mnist/

### The problem
I [was requesting the gzipped files][2] with
```ts
  const zipFile = new URL(`../data/${filename}.gz`, import.meta.url).pathname;
```
That worked well locally. However when published the package to `deno.land/x/` I got an error:
```
deno run --allow-read ./show.ts
error: Uncaught (in promise) NotFound: No such file or directory (os error 2), open '/x/mnist@v1.0.0/data/train-images-idx3-ubyte.gz'
  const reader = await Deno.open(src, {
                 ^
    at async Object.open (deno:runtime/js/40_files.js:55:17)
    at async gunzipFile (https://deno.land/x/compress@v0.4.4/gzip/gzip_file.ts:22:18)
    at async getContent (https://deno.land/x/mnist@v1.0.0/lib/load_mnist.ts:66:5)
    at async readImages (https://deno.land/x/mnist@v1.0.0/lib/load_mnist.ts:31:19)
    at async Promise.all (index 0)
    at async loadMnist (https://deno.land/x/mnist@v1.0.0/lib/load_mnist.ts:12:62)
    at async file:///home/user/tests/mnist-test/test.ts::7:15
```
Although, apparently, [the file **is** actually there][3].
I've tried to load the library from `raw.githubusercontent`, to use [`path.dirname()`][4] [dirname][5] and [deno-dirname][6] – all with the same result. Then I had an idea that I could try to load the file directly as `https://deno.land/x/mnist@v1.0.0/data/t10k-images-idx3-ubyte.gz` and see if it caches the files locally. When I tried to do this through VSCodes I got an error `invalid utf-8 sequence of 1 bytes from index 1`. And when I tried to run script from CLI, I got **many** pages of integers with the following error at the end:

```
...
229, 163, 153, 110, 217, 215, 240, 136, 136, 136, 241, 172, 239, 168, 90, 163, 79, 253, 201, 
142, 110, 244, 254, 162, 92, 237, 65, 124, 48, 78, 108, 203, 51, 70, 83, 145, 103, 123, 238, 
131, 134, 67, 115, 230, 204, 153, 32, 37, 95, 252, 149, 229, 127, 0, 223, 59, 55, 145, 16, 161, 
119, 0], error: Utf8Error { valid_up_to: 1, error_len: Some(1) } }
error: invalid utf-8 sequence of 1 bytes from index 1
    at file:///home/user/tests/mnist-test/test.ts:5:8
```

[2]: https://github.com/RB-Lab/deno-mnist/blob/6c8fa066f96790414405dc1a764b9fc248a36213/lib/load_mnist.ts#L59
[3]: https://deno.land/x/mnist@v1.0.0/data/t10k-labels-idx1-ubyte.gz?source=
[4]: https://github.com/RB-Lab/deno-mnist/blob/ceada07a2ab681ccba8d5e2201dec3d632ed174d/lib/load_mnist.ts#L61
[5]: https://deno.land/x/dirname@1.1.2
[6]: https://github.com/rsp/deno-dirname

### Expected behavior (?)
I would expect that Deno would either
1. Cache and load raw/gzip file normally, or
2. Forbid to publish packages with such files, or at least
3. Not print tons of integers in the output 😄 

--
Thanks!

**Comment by RB-Lab** [comment]
Hmm.. that works. Although it fetches the data from the remote _each time_ (i.e. doesn't work if the network is down). I guess it is acceptable for my case, since I want to store unzipped files somewhere on the user's machine anyway. But it seems not to be a good solution in general: if your distribution includes non-TS files, you end up with half of the package being cached and half not. 
I'll leave it to you folks, to decide if this is OK in general and if this issue should be closed.

**Comment by ayame113** [comment]
> if your distribution includes non-TS files, you end up with half of the package being cached and half not.

I think this is exactly the main purpose of the [asset references proposal](https://github.com/tc39/proposal-asset-references).

> ### Deno Resource Caching
> Remote third-party modules are imported with URLs and cached in the filesystem at compile-time. However, these modules cannot include non-code assets in the dependency graph. Such assets must instead be downloaded at runtime. This harms startup performance and requires granting [net permission](https://deno.land/manual/getting_started/permissions) to the program, or necessitates an extra build step to do these things.
>
> This proposal allows remote modules to declare static dependencies on relatively located non-code assets, which means they can be fetched and cached at compile-time just like JS/TS modules.
> https://github.com/tc39/proposal-asset-references#deno-resource-caching

Also the https://github.com/denoland/deno/issues/5987 discussion is helpful.

**Comment by sigmaSd** [comment]
Nice but these things takes a lot of time aperently

For now I think you can just use https://deno.land/x/cache@0.2.13

**Comment by RB-Lab** [comment]
@ayame113, yeah, looks like exactly that. I think it's good to close than.
