### ISSUE TITLE
Nightly needed to compile v.1.25.2 because of sourcemap 6.0.1, does it work ?

### ISSUE THREAD

**Issue by reyman** [denoland/deno#16964]
Hi,

I'm trying to package Deno v1.25.2 for Guix using rust 1.60, and actually i encounter these errors with deno crypto.

Sourcemap 6.0.1 (https://crates.io/crates/sourcemap/6.0.1) is needed by deno core 0.150.0 (https://crates.io/crates/deno_core/0.150.0/dependencies) crate use Nightly rust option.

Is ther a combination that doesn't need these Nightly rust option to compile the Deno v1.25.2 because i read somewhere in the doc that deno support this Nightly thing.

Ps : I use this version v1.25.2 because this is the packaged needed by Quarto software, see configuration into latest release : https://github.com/quarto-dev/quarto-cli/releases/tag/v1.2.269

**Comment by bartlomieju** [comment]
Deno doesn't require any nightly options, where did you find this info?

**Comment by reyman** [comment]
I'm agree with that, but, when i try to compile v1.25.2 with rust 1.60 not nightly, i have an error because of sourcemap 6.0.1 (needed by deno-core) need a nighly option ... 

I will regen/recompile the error and update this post when it's done.

**Comment by reyman** [comment]
ok, so the best was to update the version of rust i suppose ?

**Comment by reyman** [comment]
> It's probably not nightly in Rust 1.65.

Even with Rust 1.65 i have this @dsherret 

```
   Compiling sourcemap v6.0.1
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> /tmp/guix-build-rust-deno-1.25.2.drv-0/deno-1.25.2/guix-vendor/rust-sourcemap-6.0.1.tar.xz/src/lib.rs:1:12
  |
1 | #![feature(inner_deref)]
  |            ^^^^^^^^^^^

For more information about this error, try `rustc --explain E0554`.
error: could not compile `sourcemap` due to previous error
warning: build failed, waiting for other jobs to finish...
```

**Comment by reyman** [comment]
> 

Hum there is something strange, i don't find this feature into the git lib.rs of rust sourcemap : https://github.com/getsentry/rust-sourcemap/tree/6.0.1/src

In investigate on my side what happen with this crate download.

**Comment by reyman** [comment]
Found the problem, guix crates repository patch this crate before running, don't know why : 
https://git.savannah.gnu.org/cgit/guix.git/tree/gnu/packages/crates-io.scm#n54342

I'am going to create my proper version without this patch.

Sorry for the false path.
