### ISSUE TITLE
Wrong source map line and column number with block statements

### ISSUE THREAD

**Issue by janispritzkau** [denoland/deno#16987]
Standalone block statements seem to be causing some issues with source mapping.

```ts
// three

// empty lines

// before function

function printStack() {
  console.log(new Error().stack);
}

{
  printStack();
  // should print:
  // Error
  //     at printStack (.../file.ts:8:15)
  //     at .../file.ts:12:3
  // but prints: (offset by three lines)
  // Error
  //     at printStack (.../file.ts:5:17)
  //     at .../file.ts:8:5
}
// adding a comment or statement here results in the correct source map again
```

In some cases this causes a warning to be logged to the console:

![Source line formatting error](https://cdn.discordapp.com/attachments/684911491035430919/1048568938050629653/Screenshot_from_2022-12-03_12-50-03.png)

**Comment by xnsua** [comment]
#13812
I have similar problem

**Comment by marvinhagemeister** [comment]
Just tried this in Deno `1.42.4` and the line numbers are correct.
