### ISSUE TITLE
Deno panic on edge function

### ISSUE THREAD

**Issue by S0Etherington** [denoland/deno#16983]
Panic issue occurs after running ntl dev to run dev environment.

"_Platform: windows x86_64
Version: 1.28.2
Args: ["deno", "run", "--allow-all", "--unstable", "--import-map=data:application/json;base64,eyJpbXBvcnRzIjp7Im5ldGxpZnk6ZWRnZSI6Imh0dHBzOi8vZWRnZS5uZXRsaWZ5LmNvbS92MS9pbmRleC50cyJ9fQ==", "--v8-flags=--disallow-code-generation-from-strings", "--no-config", "--quiet", "C:\\Users\\summe\\AppData\\Local\\Temp\\tmp-4796-h7JNyCbbBMfP\\dev.js", "--port", "51175"]

thread 'main' panicked at 'Failed to execute bootstrap script: EvalError: Code generation from strings disallowed for this context
    at new Function (<anonymous>)
    at genAsyncOp (deno:core/01_core.js:169:14)
    at Object.initializeAsyncOps (deno:core/01_core.js:213:19)
    at Object.bootstrapMainRuntime [as mainRuntime] (deno:runtime/js/99_main.js:396:10)
    at [deno:runtime\worker.rs:264:24]:1:11', runtime\worker.rs:265:8_"

Window says that there is an issue with an edge function. There is currently one edge function being used as middleware, but even on branches where this function does not exist, the issue persists.
Have downgraded Deno and Netlify CLI to previous versions, as well as using the current Netlify CLI with a downgraded version of Deno and using the current version of Deno and a downgraded version of the Netlify CLI. 
Wasn't able to get the rust backtrace command to work.

**Comment by bartlomieju** [comment]
`--disallow-code-generation-from-strings` arg should be removed - you create a JIT version of various ops for performance reasons.
