### ISSUE TITLE
use `Deno.test` test `Promise.any` has an error result.

### ISSUE THREAD

**Issue by tohsaka888** [denoland/deno#16997]
here is the code:

```ts
import { assertEquals } from "https://deno.land/std@0.167.0/testing/asserts.ts"

Deno.test("Promise.any", () => {

    const promise1 = new Promise<number>((resolve, reject) => {
      setTimeout(() => reject(1), 1000);
    });
    const promise2 = new Promise<number>((resolve, reject) => {
      setTimeout(() => reject(2), 2000);
    });
    const promise3 = new Promise<number>((resolve, reject) => {
      setTimeout(() => reject(3), 3000);
    });
    const promise4 = new Promise<number>((resolve, reject) => {
      setTimeout(() => resolve(4), 4000);
    });

    Promise.any([promise1, promise2, promise3, promise4])
      .then((val: number) => {
        assertEquals(val, 123123);
      })
      .catch((error) => {
        assertEquals(error, [])
      });
});
```

## expected result

an error

## actural result

```bash
ok | 1 passed | 0 failed (27ms)
```

i am a beginner in deno, and i hope someone can help me.

**Comment by dsherret** [comment]
What version are you on? For me that gives an error about it leaking async ops.

What you should do there is return or await the promise (ex. `return Promise.any([promise1, ....`) so that the test function will wait on the promise. In that code it completes without waiting on it.

**Comment by tohsaka888** [comment]
> What version are you on? For me that gives an error about it leaking async ops.
> 
> What you should do there is return or await the promise (ex. `return Promise.any([promise1, ....`) so that the test function will wait on the promise. In that code it completes without waiting on it.

Thanks for your help, i have known what the error is.
