### ISSUE TITLE
can run deno in crontab

### ISSUE THREAD

**Issue by BriCo84** [denoland/deno#16999]
I am able to run deno task in a regular terminal.  I do have to sudo su as root user to run it, but it runs with no problem.

However when i use crontab -e to schedule the code to run daily, it does not work.  Sending to an output log it seems to say the following....

"/bin/sh: 1: deno: not found"

I can't for the life of me figure out how to resolve this.  

Does deno not work in crontab?

**Comment by bartlomieju** [comment]
Yes, it's a problem with your shell - make sure that the user you run crontab with has access to the `deno` binary.
