### ISSUE TITLE
[fmt] Option to remove semicolons (please)

### ISSUE THREAD

**Issue by TodePond** [denoland/deno#17009]
hello friends I would greatly appreciate it if I could turn off semicolons when I use `deno fmt`;
thanks for your understanding;

**Comment by lilnasy** [comment]
The same issue was previously closed as not planned in #13616. The stance then was that consistency of formatting across projects is more important than configurability.

**Comment by TodePond** [comment]
I would like to humbly request for it to be reconsidered as deno fmt is the only thing stopping me from using the whole deno stack :)

if it gets added I also promise that I will stop mispronouncing 'deeno' as 'denno' ✋

**Comment by dsherret** [comment]
See https://github.com/denoland/deno/issues/13616

**Comment by dsherret** [comment]
Since people felt so strongly about this, Deno 1.30 has semicolon configuration https://deno.com/blog/v1.30#deno-fmt-supports-configuring-semicolons

**Comment by TodePond** [comment]
Thank you David, that's very kind of you :)

as promised I will no longer refer to Deeno as Denno 🫡
