### ISSUE TITLE
Deno.run() with stdout="piped" does not work when output exceeds 65536 bytes

### ISSUE THREAD

**Issue by quentinadam** [denoland/deno#17016]
Example code:

```
let string1 = '';
for (let i = 0; i < 6000; i++) {
  string1 += '0123456789';
}

let string2 = '';
for (let i = 0; i < 7000; i++) {
  string2 += '0123456789';
}

// WORKS
const process1 = Deno.run({
  cmd: ['echo', string1],
  stdout: 'piped',
  cwd: new URL('.', import.meta.url).pathname,
});
console.log('status1', await process1.status());
console.log('output1', await process1.output());

// DOES NOT WORK
const process2 = Deno.run({
  cmd: ['echo', string2],
  stdout: 'piped',
  cwd: new URL('.', import.meta.url).pathname,
});
// HANGS ON await process2.status()
console.log('status2', await process2.status());
console.log('output2', await process2.output());
```

To make it work you need to manually drain the read buffer (`await process2.stdout?.read(buffer)`) before calling status which seems kind of wrong/awkward.

**Comment by jeiea** [comment]
I didn't tested your code, but I think process2 blocked by not consumed output. How about trying

- change stdout of process2 to `'inherit'`
- or exchange console.log lines. e.g.: console.log('output2: ...'); console.log('status2: ...')

If it is resolved, I think it is expected behavior.

**Comment by quentinadam** [comment]
Thanks. Inverting the console.log lines did work.

Maybe it would be worth mentioning something about this on the documentation (https://deno.land/manual@v1.26.0/examples/subprocess), or inverting the lines in the documentation as well ?

**Comment by bartlomieju** [comment]
We're migrating users to new `Deno.Command` API and intend to deprecate `Deno.run()` API after stabilizing the former. I strongly suggest to migrate to new API.

**Comment by quentinadam** [comment]
Great, thanks for pointing out the upcoming API. I will use that going forward.
