### ISSUE TITLE
command line tool proposal

### ISSUE THREAD

**Issue by axetroy** [denoland/deno#1702]
something like `npm install xxx -g`

we need to write a command line tool for deno to do something job. eg. `pm2`

Like npm, there is a bin directory that place the `syslink` of the executable file. eg. `.deno/bin`

**Design goals:**

Since deno does not have `package.json`, we don't know which file is executable.

So we set a rule： **Executable files are only stored in the `bin` directory**

**deno install xxx**

```sh
# download pm2
deno install https://deno.land/x/pm2
# download completed
# then find all executable files in https://deno.land/x/pm2/bin/ directory
# add link to the ``.deno/bin`` directory
pm2 --help # https://deno.land/x/pm2/bin/pm2.ts
pm2-runtime --help # https://deno.land/x/pm2/bin/pm2-runtime.ts
```

**denox**

or like `npx pm2`
or make be it can be third-party library

```sh
# download in a temp directory and run
denox https://deno.land/x/pm2/pm2
# when process exit. remove the dependence file
```

**Comment by bartlomieju** [comment]
> So we set a rule： **Executable files are only stored in the `bin` directory**

This introduces another "rule" which is somewhat magical. Right now the same effect can be achieved using simple bash aliases:
```
alias pm2='deno https://deno.land/x/pm2'
```

**Comment by ry** [comment]
discussion moved here https://github.com/denoland/deno_std/issues/471

**Comment by runnerSnail** [comment]
I tried but `deno https://deno.land/x/pm2` not found. I want to deploy deno project by pm2, and deno can't provide pm2 modules.

**Comment by OnlyFlyer** [comment]
> I tried but `deno https://deno.land/x/pm2` not found. I want to deploy deno project by pm2, and deno can't provide pm2 modules.

I have too

**Comment by axetroy** [comment]
@runnerSnail it just an example.

Deno does not have this module

**Comment by OnlyFlyer** [comment]
> @runnerSnail it just an example.
> 
> Deno does not have this module


How did you solve it? @axetroy
