### ISSUE TITLE
Deno.Command is not a constructor

### ISSUE THREAD

**Issue by quentinadam** [denoland/deno#17022]
The example code on the (currently unstable) [Deno.Command API page](https://deno.land/api@v1.28.3?s=Deno.Command&unstable=) is not working and throws the following error :

```
error: Uncaught TypeError: Deno.Command is not a constructor
const command = new Deno.Command(Deno.execPath(), {
```

```
> deno --version
deno 1.28.3 (release, x86_64-apple-darwin)
v8 10.9.194.5
typescript 4.8.3
```

**Comment by magurotuna** [comment]
Most likely it seems like you forgot to pass `--unstable` option. Could you try `deno run --unstable path/to/yours.ts`?

**Comment by quentinadam** [comment]
Indeed, that was the sorry. Sorry for the hassle.
