### ISSUE TITLE
Expose Deno's internal types in DefinitelyTyped or similar

### ISSUE THREAD

**Issue by RobertAKARobin** [denoland/deno#17028]
This would let people write Typescript programs that interact with Deno without the programs themselves being dependent on Deno. (My use-case is writing an ESLint plugin that makes ESLint work on Deno projects.) The relevant types all seem to be in here:

https://github.com/denoland/deno/blob/main/cli/tsc/dts/lib.deno.ns.d.ts

Maybe add to https://github.com/DefinitelyTyped/DefinitelyTyped?

**Comment by dsherret** [comment]
We can't publish to definitely typed because that's for npm packages only. I'd recommend storing the output of `deno types` in your project or download that file from the releases. More details in #16742.

**Comment by RobertAKARobin** [comment]
Oh, that's handy. Thanks!

**Comment by crowlKats** [comment]
Closing as it a solution has been given
