### ISSUE TITLE
Potential security issues with shebang script with flags 

### ISSUE THREAD

**Issue by kevinkassimo** [denoland/deno#1704]
Assume we have a file `./gotcha` with `gotcha.mime` set to `text/typescript`:
```ts
#!/usr/bin/env deno -A
import * as deno from "deno";
deno.writeFileSync("test.txt", new TextEncoder().encode("Gotcha"));
```
Potentially problematic since users would run `./gotcha` without knowing that it is granted all permissions.

To alleviate the problem, we might need flags to cancel permissions, so that
```
./gotcha --no-all
```
would cancel the effect of `-A` in the shebang.

This also has implications with flag parsing mechanism (as discussed in #1554). To achieve this, we must be able to put flags that Deno understands AFTER the filename to run, which might also cause flag name collision problems.

Therefore, a proposal is to allow intercepting flags after filenames, but only if they have format like with `--deno-*`. Under this proposal,
```
deno --allow-all somefile.ts
```
is equivalent to 
```
deno somefile.ts --deno-allow-all
```
and in our example before, would look like
```
./gotcha --deno-no-all
# equivalent to `deno -A ./gotcha --deno-no-all`
# and equivalent to `deno ./gotcha`
```

**Comment by bartlomieju** [comment]
@kevinkassimo FYI, with new CLI parsing flags passed after script name, are forwarded to `Deno.args`, so `./gotcha --no-all` would not work. This issue still holds, but we need a different solution.

**Comment by brandonkal** [comment]
I don't see any security issue here. In fact, adding such a "feature" word worsen the security posture.

1. The shebang is not portable. It works fine on macOS but Linux will pass "deno -A" to the env program so it is unlikely you will come across scripts that use that shebang.
2. If you can't trust a file's shebang you should just call the executor directly. Why write `./gotcha --deno-no-all` when `deno ./gotcha` is much shorter?
3. It's not very secure. You can easily get around such a flag by having the shebang exec deno via bash and completely ignoring any flags passed.
4. Therefore, it's better to say "look at the shebang" and change it if needed then "always remember to pass `--deno-no-all` when running a script. Forget just one time and you are compromised."

**Comment by brandonkal** [comment]
To play devil's advocate, here is an example:
```ts
#!/usr/bin/env bash
//# comment; exec /usr/bin/env deno -A "$0"
const s = Deno.env('secret')
console.log(s)
console.log(Deno.args)
```
Execute as a script and Deno.args will be empty and the environment variable can be read. As you can see, this simple shebang ensures deno only ever sees one arg, the `-A`. All others are ignored. It's just not safe to assume it will be there.

Execute directly by calling `deno ./gotcha` and things are safe. Therefore, this issue should be closed.

**Comment by nayeemrmn** [comment]
I agree with @brandonkal. I can't relate to this issue.

1. If reference to the `deno` executable is not included in the command, I naturally wouldn't (not just shouldn't) assume anything about what permissions have been passed -- the imagery doesn't fit. I would instinctively think of it like an unsandboxed shell script, since I've run it like one.

2. I don't like the solution of creating a convention which requires passing interpreter args to a shebang'd script. Besides being really unintuitive, it's no where near passive enough to protect an unsuspecting user...

**Comment by nayeemrmn** [comment]
But regarding the CLI issue of maybe needing a way of putting deno flags after the main module name, see my suggestion here https://github.com/denoland/deno/issues/3469#issuecomment-576763441.

**Comment by kevinkassimo** [comment]
@brandonkal Yeah I agree that your example is a good point.

**Comment by solson** [comment]
I'm going through inactive issues doing some triage — it looks like this issue can be closed?

**Comment by kitsonk** [comment]
Agreed.  If there is still some sort of concern here we should address it, but it feels like there is no sensible action at this point.
