### ISSUE TITLE
LSP test runner doesn't detect `Deno.test` calls that don't have statically analyzable names

### ISSUE THREAD

**Issue by justinmchase** [denoland/deno#17054]
**Describe the bug**
If I use `Deno.test({ name, fn })` then it works as expected but if I use a function to create the object passed into Deno.test it seems to not work.

**To Reproduce**

1. create a function such as
```ts
const example = () => ({ name: 'example', fn: () => {} })
```
2. Pass it into `Deno.test(example())`
4. Look in vscode test panel

**Expected behavior**
I expect the test to appear in the test panel and for it to be runnable via vscode test integration

**Actual Behavior**

The test is not found in the list and cannot be run via vscode test integration

**Screenshots**

#### The test `huh` is found but the test on line 15 is not found.

![Capture](https://user-images.githubusercontent.com/10974/204855062-a70b48f4-e617-476e-9412-dec5d15a17fe.JPG)

**Versions**

vscode: `1.73.1` deno: `1.28.2` extension: `3.14.1`

**Comment by justinmchase** [comment]
Its super common for me to make an array of data, then in a loop call `Deno.test(...)` where the name and contents of the function are predicated on each row in the test data (aka a test Theory) and this also seems to trip up the static analyzer.

**Comment by dsherret** [comment]
You may want to consider using test steps for that kind of stuff so that the main test case remains statically analyzable.

For example:

```ts
Deno.test("should do something", async (t) => {
  const cases = [[1, 1, 2], [2, 2, 4]] as const;
  for (const [a, b, expected] of cases) {
    await t.step(`${a} + ${b} = ${expected}`, () => {
      assertEquals(add(a, b), expected);
    });
  }
});
```

**Comment by justinmchase** [comment]
_interesting_ I will definitely do that, thanks.
