### ISSUE TITLE
Overly aggressive autocomplete with arrow function parameter names

### ISSUE THREAD

**Issue by danvk** [denoland/deno#17055]
**Describe the bug**

Typing a `,` in this context adds the top autocomplete suggestion and auto-imports it:

<img width="656" alt="image" src="https://user-images.githubusercontent.com/98301/206064915-e78da6d0-062d-4e74-8042-35a22c39ffb6.png">

This is the result after I hit the `,` key:
<img width="808" alt="image" src="https://user-images.githubusercontent.com/98301/206064959-dfbed06a-e7e8-4357-a821-a67ef9307b91.png">

This is bad on a few levels:

1. There's no reason for Deno to think I want to name my function parameter `xor` instead of `x`, which is what I typed.
2. That auto-import is crazy and breaks at runtime.

**To Reproduce**

1. Write an arrow function that takes multiple parameters.
2. Type `,` after the first parameter
3. Observe that the first autocomplete suggestion is used.

**Expected behavior**

If I type `(x, i) =>` to define an arrow function, I expect it to come out as `(x, i) =>` rather than `(xor, i) =>`.

**Screenshots**

<img width="656" alt="image" src="https://user-images.githubusercontent.com/98301/206064915-e78da6d0-062d-4e74-8042-35a22c39ffb6.png">

<img width="808" alt="image" src="https://user-images.githubusercontent.com/98301/206064959-dfbed06a-e7e8-4357-a821-a67ef9307b91.png">

Here's the code from the screenshots:

```ts
declare let num: number[];

const squares = num.map((x
```

The `xor` symbol is coming from lodash, which I've imported in a `deps.ts` file:

```ts
// deps.ts

// @deno-types="npm:@types/lodash"
import {default as ld} from "npm:lodash";
export const _ = ld;
```

TypeScript alone doesn't seem to have this issue -- I can't reproduce it on the TypeScript playground and have never run into this in non-Deno TypeScript in VS Code.

**Versions**

- vscode: 1.72.1
- deno: deno 1.28.3 (release, aarch64-apple-darwin) / v8 10.9.194.5 / typescript 4.8.3
- extension: v3.14.1

**Comment by dsherret** [comment]
Small reproduction:

```ts
const xor = () => {};

const squares = num.map((
```

Then type `x,` at the end of that.

Two issues here:

1. We shouldn't be doing auto-import suggestions using a relative path to the npm cache.
2. The deno language server does seem super aggressive compared to the regular typescript lanuage server. The above doesn't fill in `xor` when using typescript's.

As a sidenote, the reason it does completions in this case, is because typescript thinks that's a parenthesized expression rather than an arrow function parameter list.
