### ISSUE TITLE
deno compile ignores importMap in the config file

### ISSUE THREAD

**Issue by mohsen1** [denoland/deno#17053]
I had to provide `--import-map` flag to `deno compile` for it to work even though `importMap` is specified in `deno.json`. Following what's described [here](https://github.com/denoland/deno/issues/14246#issuecomment-1169509823) works for me but I am getting a warning

**Comment by bartlomieju** [comment]
I believe this was fixed in https://github.com/denoland/deno/commit/91443bbc0b3e5420d8a0b3506f1b18a88d48560a and will be released in Deno v1.29.0 tomorrow.
