### ISSUE TITLE
Add `experimental.enableProjectDiagnostics` setting.

### ISSUE THREAD

**Issue by TheCymaera** [denoland/deno#17060]
**Is your feature request related to a problem? Please describe.**

TypeScript has a setting for enabling project wide diagnostics. It gives us error messages and refactoring capabilities for files that are not open in the editor.
```
typescript.tsserver.experimental.enableProjectDiagnostics
```

**Describe the solution you'd like**

Add an equivalent setting for Deno.
```
deno.tsserver.experimental.enableProjectDiagnostics
```

**Comment by Wolverin-e** [comment]
This is one of the functionalities I love about typescript while working with VSCode, It would be great to have this working with Deno as well.
