### ISSUE TITLE
support NO_COLOR env var 

### ISSUE THREAD

**Issue by ry** [denoland/deno#1706]
https://no-color.org/

**Comment by ry** [comment]
first pass in https://github.com/denoland/deno/pull/1698 but need to be able to filter typescript color messages too. Maybe should add `deno.NO_COLOR` for user code to check without requiring --allow-env

**Comment by kitsonk** [comment]
Instead of trying to filter messages in TypeScript, we should just have the compiler set `pretty: false` on the TypeScript compiler options when `NO_COLOR` is present (I checked and TypeScript doesn't check this itself, it just assumes that no one would pass the `--pretty` flag).

**Comment by hayd** [comment]
You also want to be able to support this in the front-end e.g. if adding color to `console.error` (or a user function).

**Comment by ry** [comment]
I've added `deno.noColor` in https://github.com/denoland/deno/pull/1716

**Comment by ry** [comment]
NO_COLOR works for the most part now.
