### ISSUE TITLE
`deno install` with NPM specifier puts lockfile in PATH

### ISSUE THREAD

**Issue by andrewbrey** [denoland/deno#17083]
This is not _detrimental_, just a minor paper-cut with the newly released ability to `deno install` with `npm` specifiers. Assuming you have your `deno bin dir` on your system `PATH`, when you install an `npm` specifier module, the generated `lockfile` will now show up in tab completion for the installed module:

![image](https://user-images.githubusercontent.com/34140052/208158160-7e41f666-ec22-4049-86d0-9e132681f646.png)

> pictured above, the result of running `ls -lah` in a default `deno bin` dir, then again after running `deno install npm:cowsay`, then the result of typing `cowsay [Tab]` showing that both the `cowsay` binary and its `lockfile` show up as part of the tab completion.

For context, this is on `Ubuntu` with `zsh` as the shell, and my `PATH` includes  the `deno bin` directory. Here's my `deno --version` output:

```sh
deno 1.29.1 (release, x86_64-unknown-linux-gnu)
v8 10.9.194.5
typescript 4.9.4
``` 

and here's the relevant bit of my `PATH`: `/home/vscode/.deno/bin:/bin:/usr/local....`

Perhaps the lockfile could be a dotfile (e.g. `.cowsay.lock.json`)? This would make it so the lock doesn't sort directly next to the script, but maybe that's less annoying than having tab completion contain an unexpected result?

Thanks as always for y'alls work on Deno!

**Comment by dsherret** [comment]
Thanks for letting us know! This also affects the `--config` option.

> Perhaps the lockfile could be a dotfile (e.g. .cowsay.lock.json)? This would make it so the lock doesn't sort directly next to the script, but maybe that's less annoying than having tab completion contain an unexpected result?

Seems like an easy fix. I opened #17084
