### ISSUE TITLE
I NEED SUPPORT

### ISSUE THREAD

**Issue by PoochampBR** [denoland/deno#17090]
Good evening, fellow developers. I need you to shed some light on a question I'm having. As a novice developer who used to program in Node and is currently loving Deno, it's clear that this is different from its "competitor". When trying to use a very famous NPM module, apparently my code editor is having trouble recognizing its types. The module in question is the famous Express. Even using `@deno-types="npm:express"`, it isn't even showing methods, constants, absolutely nothing. If you can help me with this problem, the newbie thanks :smile:

**Comment by OnielN14** [comment]
Hi @PoochampBR, I guess you need to import `@deno-types="npm:@types/express"` instead of `@deno-types="npm:express"`.

**Comment by PoochampBR** [comment]
> Hi @PoochampBR, I guess you need to import `@deno-types="npm:@types/express"` instead of `@deno-types="npm:express"`.

Oops, thank you very much!

**Comment by magurotuna** [comment]
I'm going to close as resolved. Please reopen if you still have trouble.
