### ISSUE TITLE
How to exclude a directory/file from lint

### ISSUE THREAD

**Issue by vixalien** [denoland/deno#17100]
I use VS Code, and I have an abysmally large JSON that I import in my code. I already have a `.d.ts` for the JSON so I don't need Deno to try infer the typings of that JSON.

I tried using `/// ts-ignore` and all the other flags on the file where I import the JSON but it still tries to load it.

Is there a way I can instruct deno not to load the JSON as the embedded `tsc` takes a very long time to parse it.

**Comment by bartlomieju** [comment]
If you use configuration file you can specify it like so:
```
{
  "lint": {
    "files": {
      "exclude": ["path/to/file"]
    }
  }
}
```

**Comment by vixalien** [comment]
thanks. it works!

kinda weird I couldn't find relevant docs though.

**Comment by bartlomieju** [comment]
Here's a link to the docs about config file: https://deno.land/manual@v1.29.1/getting_started/configuration_file

**Comment by vixalien** [comment]
thanks
