### ISSUE TITLE
feat: partial `v8` module support for `npm:` imports

### ISSUE THREAD

**Issue by KnorpelSenf** [denoland/deno#17115]
I understand that supporting Node's `v8` module is undesirable because of how funky it is.

However, there are a few things inside of it that already have Deno equivalents. I'd love to see these things be mapped, hence giving us partial support of the `v8` module when using `npm:` packages.

Concretely speaking, I am thinkg of `v8.getHeapSpaceStatistics()` which could be implemented via https://deno.land/api@v1.29.1?s=Deno.memoryUsage.

**Comment by bartlomieju** [comment]
> Concretely speaking, I am thinkg of v8.getHeapSpaceStatistics() which could be implemented via https://deno.land/api@v1.29.1?s=Deno.memoryUsage.

Not really - `v8.getHeapSpaceStatistics()` gives information about various "spaces" controlled by V8's garbage collector, while `Deno.memoryUsage()` gives overview of all memory used by the process, without separation for various spaces.

**Comment by KnorpelSenf** [comment]
Is it desirable to add the missing functionality then? I'm coming from https://github.com/denoland/deno/issues/15960#issuecomment-1317819990, so the above statistics stand between me and using nextjs on Deno.

**Comment by bartlomieju** [comment]
@KnorpelSenf if that's a blocker for nextjs (and I assume more programs) then we should consider it. There would probably be back and forth on where this API should live (`Deno.v8.getHeapSpaceStatics()`, `Deno.getHeapSpaceStatistics()`), but if you are interested in working on it an initial implementation for whichever option would be very helpful to push the discussion forward. Let me know if you'd be interested in working on it, I can provide some pointers how to handle that.

**Comment by KnorpelSenf** [comment]
I'll have to update my machine before it'll be able to build Deno from source, but I'm going to do that soon anyway. This means I won't be able to work on it anytime soon, but if no one gets started within a few months, I might pick it up.
