### ISSUE TITLE
How would you independently version invdividual subdirectories to deno.land/x via Github tags?

### ISSUE THREAD

**Issue by itsdouges** [denoland/deno#17137]
Hi there! A few things work well today when versioning (tagging) a repository:

1. A single module in a single repository
2. Multiple modules in a single repository that should be versioned together

But one thing that I'm scratching my head at currently is how best to handle independent versioning. If I only change module a, and module b has no changes, ideally I should be able to version module a by itself and module b remains untouched. 

As versioning on https://deno.land/x/ is done via git tags, I'm not sure how this could be possible, unless we could have granular control over the web hook to say only publish for xyz change 🤔. Not sure.

For context I'm interested in making a Deno native version of [changesets](https://github.com/changesets/changesets), I have a working version here https://deno.land/x/deno_changesets for top level modules only. 

Any thoughts?

**Comment by crowlKats** [comment]
Closing in favour of https://github.com/denoland/deno_registry2/issues/321
