### ISSUE TITLE
Express cannot receive new incoming request

### ISSUE THREAD

**Issue by OnielN14** [denoland/deno#17142]
Hi, I try to run sample code to run expressjs in deno that I got from https://deno.land/manual@v1.29.1/node/how_to_with_npm/express, with some modification.

I encounter an issue when I refresh the page or open the same route in different tab/window, the request stuck indefinitely.

here is the codes
```ts
// @deno-types="@types/express"
import express from "npm:express@4.18.2";

const app = express();

app.get("/", (req, res) => {
  res.status(200);
  res.send("Welcome to the Dinosaur API!");
});

app.listen(8000);
```
it is also happens when I use `res.sendStatus(200)`.

But, the issue is not occurs when I use another code other than 200, or when I use `.send()` without calling `.status()` first.

Is there anything I missed?

Here is my `deno --version`:
```sh
deno 1.29.1 (release, x86_64-pc-windows-msvc)
v8 10.9.194.5
typescript 4.9.4
```

Thanks

**Comment by bartlomieju** [comment]
@kt3k could you check if this is related to your recent change in std that we reverted?

**Comment by kt3k** [comment]
Doesn't look related to #3013 by the quick check (this still happens with deno_std@main). I'll look into more details tommorrow
