### ISSUE TITLE
Match TypeScript & JavaScript error colors

### ISSUE THREAD

**Issue by ry** [denoland/deno#1714]
I've attempted in my first pass to match the colors for file names and line numbers with the color outputted by typescript, but it's slightly off:

<img width="641" alt="screen shot 2019-02-08 at 11 35 09 am" src="https://user-images.githubusercontent.com/80/52491787-e1cde780-2b95-11e9-8280-434cab38eabd.png">

Additionally we should do the line numbers with white background as TypeScript does when displaying `source_line`

This code is here: 
https://github.com/denoland/deno/blob/3abaf9edb6877c328402b94fa0bcb6a9e0bbe86d/src/js_errors.rs#L78-L88

(More generally I invite people to iterate and improve these error messages.)

**Comment by hayd** [comment]
The line number issue is also reported in #1717.
