### ISSUE TITLE
Reland "fast zero copy string arguments"

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#17159]
It would be nice to reland the fast zero copy string arguments. We reverted it initially due to instability: https://github.com/denoland/deno/pull/17063

Reproduction was found in: https://github.com/denoland/deno/issues/16979#issue-1482413720

**Comment by bartlomieju** [comment]
This is blocked by upstream bug in V8

**Comment by littledivy** [comment]
https://github.com/littledivy/v8-fast-call-exception-repro

https://bugs.chromium.org/p/v8/issues/detail?id=13600

**Comment by littledivy** [comment]
Done https://github.com/denoland/deno/pull/17996
