### ISSUE TITLE
Source map not applied to caught errors (and peculiarities with uncaught errors)

### ISSUE THREAD

**Issue by kevinkassimo** [denoland/deno#1717]
Example:
`caught_error.ts`:
```ts
interface A {
  a: number;
}

try {
  throw new Error("HELLO")
} catch (e) {
  console.log(e);
}
```
compiled code:
```js
try {
    throw new Error("HELLO");
}
catch (e) {
    console.log(e);
}
//# sourceMappingURL=caught_error.js.map
//# sourceURL=/Users/kevinqian/Desktop/Programming/Deno/test/caught_error.ts
```
Output:
```
Error: HELLO
    at /Users/kevinqian/Desktop/Programming/Deno/test/caught_error.ts:2:11
```
Notice the error message follows the location of compiled JS code, instead of the TS source.

In comparison,
`uncaught_error.ts`:
```ts
interface A {
  a: number;
}

throw new Error("HELLO")
```
compiled code:
```js
throw new Error("HELLO");
//# sourceMappingURL=uncaught_error.js.map
//# sourceURL=/Users/kevinqian/Desktop/Programming/Deno/test/uncaught_error.ts
```
output:
```
/Users/kevinqian/Desktop/Programming/Deno/test/uncaught_error.ts:1:6
throw new Error("HELLO");

Uncaught Error: HELLO
    at file:///Users/kevinqian/Desktop/Programming/Deno/test/uncaught_error.ts:5:7
```
Notice that the first line points to compiled JS code, yet the error string points to the source TS code.

**Comment by kevinkassimo** [comment]
This is primarily caused by the fact that caught error is never forwarded to the Rust side by libdeno: `last_exception()` is never called.

**Comment by ry** [comment]
Right... I wonder how we can get a hook into that. One option is to use [`Error.captureStackTrace()`](https://v8.dev/docs/stack-trace-api#stack-trace-collection-for-custom-exceptions) in JS to forward the error to Rust for processing...  but that seems like a lot of machinery. It would be better if we could get a hook in libdeno.

**Comment by kitsonk** [comment]
Yeah, you would think V8 has some sort of internals to generate the stack trace that can be hooked.  It might be a better way to deal with it all together when our current higher level catching of errors.

**Comment by hayd** [comment]
Is this the same issue?

```
$ cat foo.ts

throw Error("line2")
$ deno foo.ts 
/Users/hayd/tmp/foo.ts:1:6
throw Error("line2");
      ^
Uncaught Error: line2
    at file:///Users/hayd/tmp/foo.ts:2:7
```
Notice: foo.ts:1:6 vs foo.ts:2:7

**Comment by kevinkassimo** [comment]
@hayd Yes. This issue is due to that we currently only apply sourcemap to stack traces instead of the error location...
