### ISSUE TITLE
Cannot use ":" in import maps for packages

### ISSUE THREAD

**Issue by KyleJune** [denoland/deno#17188]
I started making an import map today and was using the syntax "esm:npm-module-name". That worked for other modules too but when I tried adding packages via trailing slashes like (https://github.com/WICG/import-maps#packages-via-trailing-slashes), I started getting errors.

```json
{
  "imports": {
    "x:oak": "https://deno.land/x/oak@v11.1.0/mod.ts",
    "x:oak/": "https://deno.land/x/oak@v11.1.0/"
  }
}
```

If I try importing from the `x:oak/` directory, I get an error at runtime.

```
error: Unsupported scheme "x" for module "x:oak/mod.ts". Supported schemes: [
    "data",
    "blob",
    "file",
    "http",
    "https",
]
```

In vs code, I get a warning saying `Uncached or missing remote URL: "x:oak/mod.ts".deno(no-cache)`. If I try the quick fix, that fails. It probably fails for the same reason it fails at runtime.

To work around this issue, I decided to change to using "$esm/" and "$x/" as my prefix instead of "esm:" and "x:".

@bartlomieju suggested I open this issue and said that deno should provide an error or warning in such situation.

**Comment by arnim279** [comment]
This is the defined behavior according to the [spec](https://github.com/WICG/import-maps#general-url-like-specifier-remapping):
> Note that this trailing-slash variant of URL-like specifier mapping only works if the URL-like specifier has a [special scheme](https://url.spec.whatwg.org/#special-scheme): e.g., a mapping of "data:text/": "/foo" will not impact the meaning of import "data:text/javascript,console.log('test')", but instead will only impact import "data:text/".

In your example `x:oak/mod.ts`, `x` is parsed as an URL scheme but isn't supported for remapping an import, so you get an error.

**Comment by bartlomieju** [comment]
I believe @arnim279 is right here - `x:` is considered to be a "scheme" when parsing URL. I'm not sure there's anything actionable here for us, just a limitation of an import map.

**Comment by KyleJune** [comment]
Yes, I believe the only action would be to show a better error or warning message in this situation to make it more clear why it isn't working.
