### ISSUE TITLE
Logging a class constructor logs a function rather than a class

### ISSUE THREAD

**Issue by KnorpelSenf** [denoland/deno#17197]
When logging a class constructor, Deno prints `Function` but I expect `class`.

Create the following file `test.js`:

```js
class Foo {}
class Bar extends Foo {}
console.log(Foo, Bar);
```

Run it with Deno:

```sh
$ deno run test.js 
[Function: Foo] [Function: Bar]
```

This is unexpected. IMO Node does it better:

```sh
$ node test.js 
[class Foo] [class Bar extends Foo]
```

Is this intentional?

**Comment by bartlomieju** [comment]
Good catch, we should fix this. It seems to me that the problem lies in `inspectFunction` in `ext/console/02_console.js`. @KnorpelSenf would you be interested in trying to fix this?

**Comment by KnorpelSenf** [comment]
Also here, I'd generally be interested in working on this. However, as mentioned [previously](https://github.com/denoland/deno/issues/17115#issuecomment-1361675629), I don't have beefy enough hardware to work on the runtime itself yet. This means that it makes sense if someone else can start—but if no one does, I might get to it eventually :)

**Comment by bartlomieju** [comment]
> Also here, I'd generally be interested in working on this. However, as mentioned [previously](https://github.com/denoland/deno/issues/17115#issuecomment-1361675629), I don't have beefy enough hardware to work on the runtime itself yet. This means that it makes sense if someone else can start—but if no one does, I might get to it eventually :)

Have you tried using GH Codespaces? IIRC some contributors were using them to build Deno

**Comment by KnorpelSenf** [comment]
Nope, I haven't yet. Seems pretty cool, but I prefer finally spending a lot of money on some fancy computer. This is overdue anyway :D
