### ISSUE TITLE
When I run `deno init`, `import_map.json` is not automatically loaded.

### ISSUE THREAD

**Issue by err931** [denoland/deno#17217]
## Overview

Running `deno init` creates `deno.jsonc` at the same time.
However, this doesn't load `import_map.json` by default, so I wasted a lot of time before realizing the problem...

## Proposal

1. Add `importMap` line and create an empty `import_map.json`.

```diff
--- a/deno.jsonc
+++ b/deno.jsonc
@@ -1,4 +1,5 @@
 {
+  "importMap": "import_map.json", // <= HERE!!
   "tasks": {
     "dev": "deno run --watch main.ts"
   }
```

2. Generate the above with optional arguments.
ex: `deno init --import-map`

It's a minor issue, but please take care of this.

**Comment by dsherret** [comment]
`deno init` doesn't create an import_map.json file at the moment so that's why it doesn't include it in the deno.jsonc.

https://github.com/denoland/deno/blob/218d7ab7780d5e44d3badd1102a65a1be2afd00a/cli/tools/init/mod.rs#L37-L46

**Comment by err931** [comment]
Thank you.
