### ISSUE TITLE
[Feature Request] Link npm package

### ISSUE THREAD

**Issue by brillout** [denoland/deno#17214]
Is it on Deno's roadmap to allow library authors to install `npm:my-library` from disk instead of from the npm registry?

Akin to `npm link`.

Context: I'm the author of vite-plugin-ssr and I'd like to develop/debug a Deno + vite-plugin-ssr bug.

**Comment by brillout** [comment]
(FYI searching for `link` on https://deno.land points to https://deno.land/manual@v1.29.1/linking_to_external_code#linking-to-third-party-code but that URL is a 404.)

**Comment by bartlomieju** [comment]
> Is it on Deno's roadmap to allow library authors to install `npm:my-library` from disk instead of from the npm registry?
> 
> Akin to `npm link`.
> 
> Context: I'm the author of vite-plugin-ssr and I'd like to develop/debug a Deno + vite-plugin-ssr bug.

Yes, we plan to add support for that, it's being tracked in https://github.com/denoland/deno/issues/15624.

**Comment by bartlomieju** [comment]
> (FYI searching for `link` on https://deno.land points to https://deno.land/manual@v1.29.1/linking_to_external_code#linking-to-third-party-code but that URL is a 404.)

CC @crowlKats please take a look

**Comment by brillout** [comment]
Wonderful. Thanks for the swift response.
