### ISSUE TITLE
How to import `*.mjs` files that are actually have `*.mts` extension? 

### ISSUE THREAD

**Issue by gfx** [denoland/deno#17224]
The standard TypeScript compiler (`tsc`), [since v4.7](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-7.html), recognizes `import "./foo.mjs"` as a TypeScript + ESM file, but Deno does not. How can I write a TypeScript + ESM file that both `tsc` and `deno` compile?

## Details

File `./foo.mts`:

```typescript
export function hello() {
    console.log("hello");
}
```

File `./index.mts`:

```typescript
import { hello } from './foo.mjs';

hello();
```

The above two files are perfectly valid in TypeScript 4.7, as `ts-node` does:
```
$ npx ts-node --esm src/index.mts
hello
```

but Deno cannot run:
```
$ deno --version
deno 1.29.1 (release, aarch64-apple-darwin)
v8 10.9.194.5
typescript 4.9.4
$ deno run src/index.mts
error: Module not found "file:///path/to/ts-import-mjs/src/foo.mjs".
    at file:///path/to/ts-import-mjs/src/index.mts:1:23
```

Demo repo: https://github.com/gfx/ts-import-mjs

**Comment by petamoriken** [comment]
It seems to be a `tsc`-side issue rather than a `deno` issue. [TypeScript 5.0 will be able to resolve modules with the `.ts` (`.mts`) extension](https://github.com/microsoft/TypeScript/issues/51362), so waiting for that will make it possible to write codes that works with both `tsc` and `deno`.

**Comment by gfx** [comment]
@petamoriken 

Thanks. That's an interesting decision in TypeScript, as `tsc` has kept runtime code as is for a long time. Anyway, I'll wait for TypeScript 5.0.
