### ISSUE TITLE
Add deno.executable to find out the path to the current executable.

### ISSUE THREAD

**Issue by ry** [denoland/deno#1723]
To avoid things like this: 
https://github.com/denoland/deno/blob/4c869dc8851527756b774e3ea202529aa2b3ae1e/tools/util.ts#L55-L71

**Comment by kitsonk** [comment]
Prior art:

- Node.js `process.execPath`
- Python `sys.executable`
- PHP `PHP_BINARY`
- Perl _doesn't really exist_

**Comment by sh7dm** [comment]
I want to work on this one
