### ISSUE TITLE
lsp - Import specifier auto-completes to first registry in drop down after typing `https:/` then `/`

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#17235]
We probably have an issue for this somewhere, but couldn't find it. Essentially typing the following:

```ts
import something from "https:/"
```

Will annoyingly autocomplete like so:

```ts
import something from "https://crux.land/"
```

deno 1.29.1+f729576

**Comment by sigmaSd** [comment]
This doesn't happen in nvim, maybe its a vscode-deno issue ? , also an easy improvement of the situation is maybe to make deno.land the first in the list in suggest.import.hosts

**Comment by nayeemrmn** [comment]
@dsherret Could you elaborate on this issue (if it's still applicable)? Autocompletes shouldn't happen until you select one, maybe I'm misunderstanding.

**Comment by nayeemrmn** [comment]
@dsherret I'm still not sure what the expected behaviour is. What import specifier are you intending to write? Or is the auto-complete happening without selecting it? That might be caused by a local setting.

**Comment by dsherret** [comment]
It seems to be a bit finicky to reproduce (maybe because my internet is bad atm). I think maybe `/` is a completion character somewhere so doing `https:/` then `/` causes the suggestion to `https://deno.land/` to be accepted. I don't seem to have any special local settings for this.

**Comment by nayeemrmn** [comment]
Okay looks like I'm the one who had a setting disabling suggestion commits in general, if you're interested:
```json
{
  "editor.acceptSuggestionOnCommitCharacter": false,
}
```
And yeah we have `/` as a commit character, let's remove it.
