### ISSUE TITLE
lsp import completion issue

### ISSUE THREAD

**Issue by sigmaSd** [denoland/deno#17237]
writing `assert`,  lsp suggest importing this url `import { assert } from "https://deno.land/std@0.167.0/_util/asserts"` which doesn't exist

**Comment by GJZwiers** [comment]
I can reach https://deno.land/std@0.167.0/_util/asserts.ts nowadays, maybe there was an issue at the time?

**Comment by sigmaSd** [comment]
yep that's true it works now

though the other issue is that the given completion is an internal api, writing assert should import this instead `import { assert, } from "https://deno.land/std@0.172.0/testing/asserts.ts";`

**Comment by sigmaSd** [comment]
assert seems to trigger no completion these days, maybe thats better
