### ISSUE TITLE
CLI: Box-drawing characters in the permission prompt is broken

### ISSUE THREAD

**Issue by nsfisis** [denoland/deno#17244]
# Environment

```
$ deno --version
deno 1.29.1 (release, x86_64-unknown-linux-gnu)
v8 10.9.194.5
typescript 4.9.4
```

* OS: Ubuntu 22.04
* Terminal: Alacritty v0.11.0 or Ubuntu's bundled Terminal app
* Font: Ubuntu Mono 13

# Problem

Box-drawing characters in the permission prompt is broken.

## Screenshot

![image](https://user-images.githubusercontent.com/54318333/210249694-8cf7da65-6865-4adc-bd28-b8a40cf714cb.png)

# Cause

The box-drawing character is printed in italic style.

[runtime/permissions/prompter.rs](https://github.com/denoland/deno/blob/f729576b2db2aa6ce000a598ad2e45533f686213/runtime/permissions/prompter.rs#L204-L208)

```rust
    let msg = format!(
      "   ├ Run again with --allow-{} to bypass this prompt.",
      name
    );
    eprintln!("{}", colors::italic(&msg));
```

This code should be like:

```rust
    let msg = format!(
      "Run again with --allow-{} to bypass this prompt.",
      name
    );
    eprintln!("   ├ {}", colors::italic(&msg));
```

(not tested)

**Comment by bartlomieju** [comment]
Thanks for the report, fixed in #17249
