### ISSUE TITLE
Retry downloading module on failure

### ISSUE THREAD

**Issue by piscisaureus** [denoland/deno#17251]
When a transient error (e.g. 5xx status code or `connection reset` error) is encountered while downloading a module, give it another shot.

This avoids annoyances like below, and I can't think of any downsides.

![image](https://user-images.githubusercontent.com/218257/210290167-338add30-dc36-44a7-b0b3-34c022548b23.png)

**Comment by bombillazo** [comment]
Was this solved? we are getting this frequently during our GH actions deno compile...
