### ISSUE TITLE
Attempts while getting deno installed on Windows / git bash

### ISSUE THREAD

**Issue by BolnayaTPrincessa** [denoland/deno#17267]
I'm trying to install deno on git bash, and I failed after multiply attempts and researching.

First, I tried to run `curl -fsSL https://deno.land/x/install/install.sh | sh` directly in git bash, and this is what I got:
```
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```
I asked a friend who is using Linux at this point to check if the site's certificate is really valid, and soon we confirmed that **the certificate problem is actually originated from Microsoft's library**, not from deno's side.

And then I tried something like `curl -k` and `curl --insecure` , but git bash's curl ignores these parameters.

After some researching, I tried using `winpty -Xallow-non-tty curl -kfsSL https://deno.land/x/install/install.sh | sh` instead and this time I got:
```
sh: line 1: #!/bin/sh: No such file or directory
sh: line 4: $'\E[0K': command not found
sh: line 5: set: - invalid option
set: usage: set [-abefhkmnptuvxBCEHPT] [-o option-name] [--] [-] [arg ...]
```
And after more researching, I found someone said I should try installing deno on the Windows system itself, and git bash will be able to access it, then I tried `irm https://deno.land/install.ps1 | iex` on PowerShell, and I got:
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (35) schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - 撤銷功能無法檢查憑證的撤銷。
tar.exe: Error opening archive: Failed to open 'C:\Users\user\.deno\bin\deno.zip'
Remove-Item : 找不到 'C:\Users\user\.deno\bin\deno.zip' 路徑，因為它不存在。
位於 線路:39 字元:1
+ Remove-Item $DenoZip
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\user\.deno\bin\deno.zip:String) [Remove-Item], ItemNotFoundExc
   eption
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand
```
After some researching, I realized that there's no easy way to make PowerShell to bypass the "certificate problem", and maybe because I'm not very familiar with PowerShell, I couldn't find a solution by myself and decided to just start asking others for support.

**Comment by lucacasonato** [comment]
Are you behind a corporate firewall that rewrites certificates? If so, is that certificate installed on your Windows machine?

**Comment by BolnayaTPrincessa** [comment]
So I will have to learn how to debug Windows certificate settings from scratch for a totally unrelated purpose, and may have to come back several month or years later...

**Comment by jtoppine** [comment]
> So I will have to learn how to debug Windows certificate settings from scratch for a totally unrelated purpose, and may have to come back several months or even years later...

You can bypass the installer script and simply manually download the deno binary from https://github.com/denoland/deno/releases . No need for installation, just drop it in a location of choice. Add to PATH if necessary.

**Comment by lucacasonato** [comment]
Yes, or use `choco` or `scoop` - very non standard corporate firewall setups are very hard for us to cater to, because they are usually unique to a single organization, and thus not reproducible by us.
