### ISSUE TITLE
[regression] cannot import from esm modules when "types" is incorrectly not first entry in exports object

### ISSUE THREAD

**Issue by Lesiuk** [denoland/deno#17279]
```javascript
import { random } from 'npm:radash';
console.log(random(1,1));
```
Output Deno 1.29.2 run --check
```
error: TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'random'.
import { random } from 'npm:radash';
         ~~~~~~
    at file:///Users/xxx/Library/Application%20Support/JetBrains/WebStorm2022.3/scratches/deno.ts:1:10
```

Output Deno 1.29.1 run --check
```
1
```

**Comment by Lesiuk** [comment]
It looks like type checking is working correctly for this package in 1.29.2

```javascript
import { random } from 'npm:radash';
console.log(random('qwe', 5));
```

Output Deno 1.29.2
```
Check file:///Users/xxx/Library/Application%20Support/JetBrains/WebStorm2022.3/scratches/deno.ts
error: TS2345 [ERROR]: Argument of type 'string' is not assignable to parameter of type 'number'.
console.log(random('qwe', 5));
                   ~~~~~
    at file:///Users/xxx/Library/Application%20Support/JetBrains/WebStorm2022.3/scratches/deno.ts:2:20
```

**Comment by dsherret** [comment]
I was just talking to @bartlomieju about this one yesterday. Essentially we improved the TypeScript support, but that broke this scenario where people incorrectly define their exports object.

![image](https://user-images.githubusercontent.com/1609021/210895834-35df7483-1b2b-4253-9db2-4ed46de62d96.png)

https://publint.dev/radash@10.3.2

**Comment by rayepps** [comment]
Hey @Lesiuk just fyi, radash should work without error in the latest version `10.5.0`

https://publint.dev/radash@10.5.0
