### ISSUE TITLE
How to set NPM_CONFIG_REGISTRY ?

### ISSUE THREAD

**Issue by fufuuuu** [denoland/deno#17273]
There is no docs and I have no idea about this question? Somebody help me plz.....

**Comment by fufuuuu** [comment]
os: windows 10

**Comment by dsherret** [comment]
Either, in cmd:

```cmd
set NPM_CONFIG_REGISTRY=https://registry.npmjs.org/
```

Or in powershell:

```ps
$env:NPM_CONFIG_REGISTRY=https://registry.npmjs.org/
```

Then provide your own value. If you want to do it system wide, then follow https://superuser.com/questions/949560/how-do-i-set-system-environment-variables-in-windows-10

**Comment by fufuuuu** [comment]
Tks,it worked! But there comes out a new error: `npm packages with no integrity are not implemented.` while I run `deno run -r hello.ts`.

**Comment by dsherret** [comment]
@fufuuuu I opened #17281. We haven't implemented that yet. I think your custom registry is not serving an "integrity" with the package, but maybe just a shasum.
