### ISSUE TITLE
hang after importing node-api module

### ISSUE THREAD

**Issue by littledivy** [denoland/deno#17288]
_Originally reported by Prisma folks_

### Repro

Clone and follow steps in this repo: https://github.com/SevInf/deno-hang-repro.

```js
const { ops } = Deno.core;
const module = ops.op_napi_open("./minimal-napi/minimal-napi.darwin-arm64.node");

console.log(module.sum(1, 2)) // 3
// hangs indefinitely
```

same case with `createRequire`:
```js
import { createRequire } from "https://deno.land/std/node/module.ts";

const require = createRequire(import.meta.url);
require("./minimal-napi");
// hangs indefinitely
```

Seems like a bug in event loop preventing exiting the process.

**Comment by bartlomieju** [comment]
After initial look, this is not related to "ops" as number of dispatched and completed ops is the same, however CPU is spinning at 100%. I think this might be related to event loop middleware constantly telling that there's more work to be done.

I'll look into a fix.

**Comment by aapoalas** [comment]
In that case this is probably the same problem that I faced with FFI callbacks earlier: https://github.com/denoland/deno/issues/15136

You can find the linked fix that I eventually implemented for FFI callbacks to ref/unref them without relying on the event loop middleware.

**Comment by bartlomieju** [comment]
@aapoalas you're right, I was just debugging it and found that `napi_unref_threadsafe_function` is indeed called, but it's a noop. Thanks for the pointer that should be helpful 👍
