### ISSUE TITLE
Cache::put() behavior

### ISSUE THREAD

**Issue by ghost** [denoland/deno#17299]
I tested Cache API and noticed that behavior of the ```cache.put()``` changes with different launches of the program.
On the first run, the responses are successfully overwritten, but at the second run and beyond overwriting is not happening.

```js
// test.js - first run

const req = new Request( 'http://localhost/' );
const res1 = new Response( 'test1' );
const res2 = new Response( 'test2' );

let cache = await caches.open( 'test' );

await cache.put( req, res1 );
await cache.put( req, res2 );

let res = await cache.match( req ).then( res => res?.text() );

console.log( res ); // logs "test2"
```

```js
// test.js - second run

await cache.put( req, res2 ); // swap puts order
await cache.put( req, res1 );
// ...
console.log( res ); // also logs "test2"
```

It can be fixed by calling ```caches.delete( 'test' )``` or ```cache.delete( req )``` before puts

Is it right ```cache.put()``` behavior?

**Comment by bartlomieju** [comment]
CC @satyarohith
