### ISSUE TITLE
[Windows] Powershell installation broken on new computer

### ISSUE THREAD

**Issue by loic-sharma** [denoland/deno#1729]
The website's Windows installation instructions is to run:

```ps1
ex (iwr https://deno.land/x/install/install.ps1)
```

This fails on my computer with:

```
iwr : The request was aborted: Could not create SSL/TLS secure channel.
At line:1 char:1
+ iwr https://deno.land/x/install/install.ps1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
```

The fix is to run this statement first:

```
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
```

For more information, refer to [this StackOverflow post](https://stackoverflow.com/questions/41618766/powershell-invoke-webrequest-fails-with-ssl-tls-secure-channel). Should this line be added to the instructions?

**Comment by Maxim-Mazurok** [comment]
The problem is that by default, PowerShell uses TLS 1.0, but the site security requires TLS 1.2.
I think that we should consider allowing TLS 1.0 on the deno.land server as an alternative solution. It might bring some security vulnerabilities, though.

**Comment by MarkTiedemann** [comment]
This is documented in the Known Issues section of `deno_install`: https://github.com/denoland/deno_install#could-not-create-ssltls-secure-channel

Also, this is fixed in PowerShell v6.

@ry Is it possible to allow TLS 1.0 specifically for `https://deno.land/x/install/install.ps1`? Otherwise, I think this is a "won't fix".

**Comment by ry** [comment]
@MarkTiedemann It's a redirect to github anyway, so probably not.
won't fix is fine.

**Comment by VovaSv** [comment]
If you have PowerShell V5 then upgrade it to V7 and run install again via PowerShell V7.
