### ISSUE TITLE
`Module.getUid` requires unstable, but does not even work with `--unstable`

### ISSUE THREAD

**Issue by hasezoey** [denoland/deno#17297]
Error:
```txt
error: Uncaught TypeError: Requires --unstable
    throw new TypeError("Requires --unstable");
          ^
    at Module.getUid (https://deno.land/std@0.154.0/_deno_unstable.ts:86:11)
    at Object.accessSync (https://deno.land/std@0.154.0/node/_fs/_fs_access.ts:75:66)
    at file:///mnt/projects/nodejs/mongoose/deno-test.js:8:16
```

script:
```ts
'use strict';

import { createRequire } from "https://deno.land/std/node/module.ts";
const require = createRequire(import.meta.url);

const fs = require('fs');

console.log(fs.accessSync('/'));
```

deno command:
```sh   
deno run --allow-read --unstable ./deno-test.js
```

deno version:
```sh
$ deno --version
deno 1.29.2 (release, x86_64-unknown-linux-gnu)
v8 10.9.194.5
typescript 4.9.4
```

installed via `cargo install deno`

PS: the error `Uncaught TypeError: Requires --unstable` is not very helpful if not listing *what* requires unstable in the message itself, instead of just relying on the stack-trace

**Comment by kamilogorek** [comment]
You are using the very old `deno_std` version `std@0.154.0`. It has been fixed ever since.

**Comment by hasezoey** [comment]
> You are using the very old deno_std version std@0.154.0.

how do i fix this, is there some cache to clean globally? i just before running that script did a `cargo install deno`, which installed `deno 1.29.2` and the only import from deno is from what i know version independent and should use the latest version as `https://deno.land/std/node/module.ts`

**Comment by kamilogorek** [comment]
```
$ deno run --allow-read --allow-sys --reload=https://deno.land/std deno-test.js
```

`---allow-read` i required for `accessSync` and `allow-sys` is required for `uid`.
You can either `--reload=https://deno.land/std` or `--reload` for everything.
It's also recommended to specify package versions your code will use, so it'll be:

```js
import { createRequire } from "https://deno.land/std@0.171.0/node/module.ts";
```

**Comment by hasezoey** [comment]
thanks, used `--reload`, i personally understood it as when not specifying a version it would mean that it would always use the latest version automatically (though i have not read up on the docs or anything, i "assumed" it to be the case because of how it would work with npm / yarn (without a lockfile))

**Comment by hasezoey** [comment]
closing as fixed (user error?) required `--reload` to get newer versions of unspecified version imports
