### ISSUE TITLE
Add command-line arguments `--no-console`

### ISSUE THREAD

**Issue by tianxiadys** [denoland/deno#17319]
On Windows systems (I don't know what happened with Linux and OS X), running Deno automatically activates a console window. If I want to release a GUI program via `deno compile`, this causes problems

I can implement a GUI program by calling the `win32 API` via `FFI`, which is low feasibility, but at least a possibility

**Comment by Xernisfy** [comment]
Related to https://github.com/denoland/deno/discussions/11638#discussioncomment-1225046 and https://github.com/denoland/deno/discussions/12941 for possible solutions

**Comment by lino-levan** [comment]
@dsherret This should probably be closed since `--no-terminal` landed in https://github.com/denoland/deno/pull/17991.
