### ISSUE TITLE
WebSocket messages are not being sent (again)

### ISSUE THREAD

**Issue by sgwilym** [denoland/deno#17332]
It looks like Deno's WebSocket implementation is dropping messages (again), much like #16511.

I have created a limited reproduction, along with a description of the problem: https://github.com/sgwilym/deno-ws-bug-repro.

In this reproduction, a file's contents are sent in pieces over a WebSocket using a readable stream from `Deno.open`. A server logs the size and SHA-256 hash of each piece it receives.

If the reproduction is run locally, no messages are dropped.

However, when the same server is deployed to Fly.io using the Dockerfile in the reproduction case, or to Deno Deploy ([playground here](https://dash.deno.com/playground/useful-dog-20)), only the first four of eight expected messages come through, stopping when the total size of messages reaches 256kb.

`socket.onerror` is never triggered by either side.

This error seems to happen with all 1.29 releases.

**Comment by sgwilym** [comment]
And if you run the same reproduction with Deno 1.28.3, the server receives _too many_ messages. 🙃

**Comment by aaaaargZombies** [comment]
Just adding a comment to say I'd be interested to see this resolved and so I get notifications on any updates.

**Comment by Lesiuk** [comment]
There is also, a bug where web sockets crash server with broken pipe message when client do not disconnect correctly.

**Comment by sgwilym** [comment]
After more testing, the last version of Deno which sends the correct number of WebSocket messages is 1.26.2. So the underlying issue raised in #16511 is still not resolved.

@Lesiuk There are several existing issues about the broken pipe thing already. I'd like to keep this focused on the dropped messages.

**Comment by sgwilym** [comment]
I've added another script to the reproduction repo which uses `WebSocketStream` (`client_stream.ts`), which exhibits the same problem.

**Comment by bartlomieju** [comment]
@littledivy is this issue still relevant?

**Comment by littledivy** [comment]
This should no longer be happening. Feel free to open a new one if the issue persists.
