### ISSUE TITLE
Deno does not enforce `const`

### ISSUE THREAD

**Issue by sgammon** [denoland/deno#17376]
Hello esteemed Deno authors,

I was playing around in Deno today and caught this:
<img width="578" alt="Screenshot 2023-01-12 at 11 07 06 AM" src="https://user-images.githubusercontent.com/171897/212158551-a0dd8ad5-33b9-43d4-ae80-a1d7c914a53e.png">

Is this intended behavior? Am I missing a flag?

**Comment by sgammon** [comment]
i had invoked with `deno` (on macOS Ventura M1, version of `deno` depicted)

**Comment by DjDeveloperr** [comment]
It is the intended behavior, only for the REPL. It also works in Chrome DevTools:

![image](https://user-images.githubusercontent.com/43033058/212159115-74b25297-de64-4885-8cd2-fde1ae86d161.png)

**Comment by sgammon** [comment]
@DjDeveloperr i see, thank you 👍🏻
