### ISSUE TITLE
`deno install` does infer executable name from redirect

### ISSUE THREAD

**Issue by cowboyd** [denoland/deno#17409]
If you access an install behind a link shortener at `https://tinyurl.com/get-started`, but the redirect target is `https://deno.land/x/mymod/bin/my-cmd.ts` It will use `get-started` as the bin name, not `my-cmd`.

Also, in a related case, if you have a vanity install domain like `https://get-my-cmd.com` where there is no path at all in the initial url, and it redirects to `https://deno.land/x/mymod/bin/my-cmd.ts` it throws:

```
error: An executable name was not provided. One could not be inferred from the URL. Aborting.
```

**Comment by crowlKats** [comment]
I think what should be done is that the first case is correct, however the second case it should fallback to follow the redirect for the name

**Comment by cowboyd** [comment]
Thanks @crowlKats, makes sense 👍
