### ISSUE TITLE
test file_fetcher_preserves_permissions, pty_multiline, and stdio_streams_are_locked_in_permission_prompt hang

### ISSUE THREAD

**Issue by GJZwiers** [denoland/deno#17415]
`test integration::run::file_fetcher_preserves_permissions has been running for over 60 seconds`  happens during  `cargo test -p deno --test integration_tests` when building from source, on Windows. The test seems to hang indefinitely.

**Comment by bartlomieju** [comment]
@dsherret discovered the same problem yesterday. We're still investigating what's the problem here.

**Comment by GJZwiers** [comment]
Closing in favor of https://github.com/denoland/deno/issues/18129 as it seems to be the same issue.
