### ISSUE TITLE
deno hangs when npm package has itself as a dependency

### ISSUE THREAD

**Issue by jeiea** [denoland/deno#17420]
## Steps to reproduce

**Environment**
```
> deno --version
deno 1.29.3 (release, x86_64-pc-windows-msvc)
v8 10.9.194.5
typescript 4.9.4
> systeminfo
...
Microsoft Windows 11 Pro 10.0.22621 N/A Build 22621
...
```

**Command**
```
git clone https://github.com/jeiea/deno_report.git -b oci
code deno_report
```

## Expected behavior
<img width="432" alt="image" src="https://user-images.githubusercontent.com/4188984/212477826-8c12613d-6178-463f-aeae-dfbc3ef4a82b.png">

<img width="241" alt="image" src="https://user-images.githubusercontent.com/4188984/212477754-5d6b6a12-edf2-402f-9145-bb1fa2001bf2.png">

## Actual behavior
LSP doesn't work at all.
<img width="453" alt="image" src="https://user-images.githubusercontent.com/4188984/212477674-860425e1-d63d-4128-9ddf-529a46ca9cea.png">
It doesn't run, just hangs.
<img width="254" alt="image" src="https://user-images.githubusercontent.com/4188984/212477779-f79c06da-23a4-4c7e-8279-729711d7eb6c.png">

## Additional context
The following is Deno Language Server output when problem occurs.
```
Starting Deno language server...
  version: 1.29.3 (release, x86_64-pc-windows-msvc)
  executable: C:\ProgramData\chocolatey\lib\deno\deno.EXE
Connected to "Visual Studio Code" 1.74.3
{"type":"mark","name":"update_cache"},
{"type":"measure","name":"update_cache","count":1,"duration":0},
{"type":"mark","name":"update_tsconfig"},
{"type":"mark","name":"request","count":1,"args":{"id":2,"method":"configure","compilerOptions":{"allowJs":true,"esModuleInterop":true,"experimentalDecorators":true,"isolatedModules":true,"jsx":"react","lib":["deno.ns","deno.window"],"module":"esnext","moduleDetection":"force","noEmit":true,"resolveJsonModule":true,"strict":true,"target":"esnext","useDefineForClassFields":true,"useUnknownInCatchVariables":false}}},
{"type":"measure","name":"request","count":1,"duration":1},
{"type":"measure","name":"update_tsconfig","count":1,"duration":125},
{"type":"mark","name":"request","count":2,"args":{"id":3,"method":"getSupportedCodeFixes"}},
{"type":"measure","name":"request","count":2,"duration":0},
{"type":"mark","name":"update_import_map"},
{"type":"measure","name":"update_import_map","count":1,"duration":0},
{"type":"mark","name":"update_registries"},
Enabling import suggestions for: https://deno.land
Enabling import suggestions for: https://x.nest.land
Download https://x.nest.land/.well-known/deno-import-intellisense.json
Download https://intellisense.nest.land/deno-import-intellisense.json
Enabling import suggestions for: https://crux.land
{"type":"measure","name":"update_registries","count":1,"duration":1120},
{"type":"mark","name":"request","count":3,"args":{"id":4,"method":"getAssets"}},
{"type":"measure","name":"request","count":3,"duration":1},
{"type":"measure","name":"initialize","count":1,"duration":1253},
Server ready.
{"type":"mark","name":"did_open","count":1,"args":{"textDocument":{"uri":"file:///d%3A/Repos/jeiea/2023/01/deno_report/main.ts","languageId":"typescript","version":1,"text":"import { IdentityClient } from \"npm:oci-identity@2.50.1\";\n// import { IdentityClient } from \"https://esm.sh/oci-identity@2.50.1?dev\";\n\nconsole.log(\"hello\");\nlet a: number = \"a\";\n"}}},
{"type":"measure","name":"did_open","count":1,"duration":0},
```

**Comment by dsherret** [comment]
Does this only occur when using the lsp and deno run at the same time? Does it occur when only running `deno run ...etc..`? Does the deno and vscode process have access to `%LOCALAPPDATA%\deno` (usually `C:\Users\<your-username>\AppData\Local\deno`/`)? Do you have some special setup for your AppData directory?

Maybe related: #16577

**Comment by jeiea** [comment]
`deno run` hangs always with the script regardless of the LSP. Debugging and formatting also hang.
It seems that deno and vscode have access to %LOCALAPPDATA%\deno, as the only difference between the two scripts test is editing and reloading the window.

I have no issue with #16577. I could run the command without problem so it may not be related.

**Comment by dsherret** [comment]
Sorry, I should have tried this out as well. It also hangs for me with that specific npm specifier.

**Comment by bartlomieju** [comment]
This `oci-identity` package is suspicious - if I check my cache folder there's no files there besides `registry.json`

**Comment by dsherret** [comment]
@bartlomieju it's a deadlock. Basically this assertion would occur if it weren't for the locks on the previous line, which causes a deadlock:

https://github.com/denoland/deno/blob/1712a88e6998d058c11ee213dcf15cccc563a9b0/cli/npm/resolution/graph.rs#L314

**Comment by dsherret** [comment]
It seems this package has itself as a dependency lol:

```json
    "2.50.1": {
      "name": "oci-workrequests",
      "version": "2.50.1",
      "description": "OCI NodeJS client for WorkRequests",
      "repository": {
        "type": "git",
        "url": "git+https://github.com/oracle/oci-typescript-sdk.git"
      },
      "main": "./index.js",
      "typings": "./index",
      "scripts": {},
      "author": { "name": "Oracle Cloud Infrastructure" },
      "license": "(UPL-1.0 OR Apache-2.0)",
      "dependencies": { "oci-common": "2.50.1", "oci-workrequests": "2.50.1" },
```
