### ISSUE TITLE
Add timeout to `wait_contains()` in watcher tests

### ISSUE THREAD

**Issue by Cre3per** [denoland/deno#17438]
## Problem

A common failure indicator of `watcher_tests.rs` is that a test case gets stuck.  
Affected test cases can be debugged by rerunning tests with `--nocapture` and carefully comparing output to expected output.  
This is not possible in CI, and inefficient on developer machines.

## Steps to reproduce

Change the `s` argument of any `wait_contains()` call and run the relevant test case.

## Suggested solution

Add a timeout, say 60 seconds.  
When the timeout expires, abort the test case and log `s` (The text being waited for).

Bonus points if `stdout` and `stderr` can be logged, this would be especially useful for failures that only occur in CI.

**Comment by bartlomieju** [comment]
Seems reasonable. PR for this is welcome.
