### ISSUE TITLE
A remote module which imports npm modules requires `--unstable`.

### ISSUE THREAD

**Issue by dajiaji** [denoland/deno#17455]
Hi there.

Is there any plan to allow to use the remote module without `--unstable`?

**Comment by bartlomieju** [comment]
Currently there are no plans, we are still evaluating if this is actually desired.

**Comment by dajiaji** [comment]
I'm very glad if I can use the remote module importing npms without `--unstable`.

I've heard that Deno now supports npm modules, so I switched the primitive crypto library used in [my E2E crypto module](https://github.com/dajiaji/hpke-js) to an audited and fast npm module. As the result, using my module requires `--unstable`. This was not expected behavior at all. The biggest problem is that I cannot recognize this behavior on the local development environment.

I hope this behavior will be fixed.

**Comment by bartlomieju** [comment]
@dsherret will work on that.

**Comment by dsherret** [comment]
Tasks:

- [ ] Fix the npm specifier implementation to store and resolve based on referrer information.
- [ ] Review https://github.com/denoland/deno/blob/c230a955518eef34af04fffad92ec915f29a58bd/cli/npm/resolution/specifier.rs#L171
