### ISSUE TITLE
`deno run` doesn't support disabling colors

### ISSUE THREAD

**Issue by naltun** [denoland/deno#17471]
Here's a screenshot of my text editor (Neovim):
![image](https://user-images.githubusercontent.com/7507990/213555164-8edabb5e-12e5-4ae8-8b60-32e74b31e8a9.png)

What you're seeing is me running `:!deno run -A %` in Neovim, which runs the current file (via `%`) within the editor. This is useful for immediate, quick feedback, but I'm unable to use this because `deno run` doesn't have a `--disable-colors` option. As a result, the color escape sequences are embedded in standard output.

I think it would be useful to add a `--disable-colors` option.

**Comment by crowlKats** [comment]
You can use the `NO_COLOR` env var to achieve this.
