### ISSUE TITLE
Supabase Client errors out

### ISSUE THREAD

**Issue by willopez** [denoland/deno#17472]
Deno errors out with the following output when attempting to use use the supabase js client.

```
Assertion failed: (status == napi_ok), function Init, file bufferutil.c, line 157.
```

Steps to reproduce: 
```
// in deps.ts
export { createClient } from "npm:@supabase/supabase-js";
```

```
// in main.ts
import { createClient } from "./deps.ts";
```

And attempt to run with: `deno --unstable run -A  ./main.ts`

**Comment by Mehrbod2002** [comment]
@bartlomieju 
Can I work on it?

**Comment by bartlomieju** [comment]
> @bartlomieju Can I work on it?

You are free to try @Mehrbod2002, but keep in mind that it appears to be a bug in Node-API implementation which is on harder side of the spectrum in terms of potential fixes. Give it a go anyway if you're interested!
