### ISSUE TITLE
Crash when FFi involves variables for nested structures 

### ISSUE THREAD

**Issue by AntoninRousset** [denoland/deno#17482]
I like to use variables to define types in my symbols definition, but it makes Deno crash when used in nested structures:
```js
const a_t = {
  struct: ["i32"]
}

const lib = Deno.dlopen(
  "./lib.so",
  {
    f: {
      parameters: [],
      result: {struct: [a_t, a_t]}
    }
  }
)

lib.symbols.f()
```
However, it does not crash for these result definitions:
```js
{struct: [a_t]}
{struct: [{...a_t}, {...a_t}]}
{struct: [{struct: ["i32"]}, {struct: ["i32"]}]}
```

The lib source is irrelevant, but I past it here for reference:
```C
typedef struct {
  int value;
} a_t;

typedef struct {
  a_t a1;
  a_t a2;
} b_t;

b_t f() {
  b_t s = {{},{}};
  return s;
}
```

[backtrace.txt](https://github.com/denoland/deno/files/10468543/backtrace.txt)

**Comment by aapoalas** [comment]
Hmm. Good find. I know from personal experience that nested structs do work but I'm guessing that having the same struct in two positions causes some unforeseen issue to emerge.
