### ISSUE TITLE
Crash when FFI involves empty structure

### ISSUE THREAD

**Issue by AntoninRousset** [denoland/deno#17481]
The question is not whether empty structures are valid or not, but reporting that Deno will crash with
```js
Deno.dlopen(
  "./lib.so",
  {
    f: {
      parameters: [],
      result: {struct: []},
    }
  }
)

```

The lib source is irrelevant, but I past it here for reference:
```c
typedef struct {} a_t;

a_t f() {
  a_t s = {};
  return s;
}
```

[backtrace.txt](https://github.com/denoland/deno/files/10468189/backtrace.txt)

**Comment by aapoalas** [comment]
Nice find!
