### ISSUE TITLE
Friendly error message when importing node built-in modules without a `node:` prefix

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#17493]
*This depends on support for `node:` modules in #16223*

When built-in Node.js modules are imported without `node:` prefix a friendly error message is shown:

```js
import { readFile } from "fs";
```

```
Add a "node:" prefix to the following import:
  import { readFile } from "fs";
Like this:
  import { readFile } from "node:fs";
```

This is only relevant to the user code - dependencies imported with `npm:` specifiers will have these modules available in both forms.

**Comment by aapoalas** [comment]
This should probably be an LSP FixIt as well.

**Comment by albnnc** [comment]
Continuing roadmap discussion, is this going to support searching in different URI scopes like `deno:` or `custom:` (in case they are going to be implemented)?

<hr />

Currently, we have the following behaviour:

<details>
<pre>
➜  ~ deno repl -A
Deno 1.29.4
exit using ctrl+d, ctrl+c, or close()
> import * as fs from "fs"
Uncaught TypeError: Relative import path "fs" not prefixed with / or ./ or ../ from "file:///Users/albnnc/$deno$repl.ts"
    at async <anonymous>:2:12
>
</pre>
</details>

What about unbiased message like "Hey, we got bare specifier, do you want to add import map entry?"? This would advocate Node less, which is good, in my opinion.

**Comment by dsherret** [comment]
> Continuing roadmap discussion, is this going to support searching in different URI scopes like deno: or custom: (in case they are going to be implemented)?

Not for this issue. This is just for known node built-in modules like "fs" -> "node:fs" in order to help guide people on how to run Node code in Deno. This is instead of supporting bare specifiers like "fs", which would not be great IMO.

> What about unbiased message like "Hey, we got bare specifier, do you want to add import map entry?"? This would advocate Node less, which is good, in my opinion.

I think this should be more explanatory for any import that matches a node built-in module's bare specifier since it would be more helpful to give Node users a clear path to getting their existing code running in Deno. Obviously we'd like users not to use `node:` imports, but some people might have a lot of existing code using that.
