### ISSUE TITLE
When global Node.js objects are referenced, Deno should error out with a friendly error message

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#17494]
*Extracted from https://github.com/denoland/deno/issues/17475*

Objects that will be handled: ~~`process`~~, `global`, `Buffer`, `setImmediate`, `clearImmediate`, `module`, `exports`.

```
Uncaught ReferenceError: process is not defined. 
    To use Node's process object in Deno, add this to `<filename>`:
        import process from "node:process";
```

For `global` the hint in the error should be `globalThis.global = globalThis`.

**Comment by aapoalas** [comment]
These should probably be LSP FixIts as well.

**Comment by calebegg** [comment]
I think this may now be obsolete, as deno appears to create an import for node:process automatically

**Comment by dmint789** [comment]
I'm not sure if this belongs here, but I find it annoying that Deno LSP always highlights the process object as a warning, even with the lint rule `no-process-globals` disabled. It wants me to do the `node:process` import, but I can't use that in a Next JS application.

**Comment by bartlomieju** [comment]
@dmint789 could you please open a new issue for that? This seems like a bug

**Comment by dmint789** [comment]
> @dmint789 could you please open a new issue for that? This seems like a bug

Sure
