### ISSUE TITLE
Syntax warning when using "import-map": "deno(import-prefix-missing)"

### ISSUE THREAD

**Issue by dong-lufei** [denoland/deno#17490]
```js
/*
* import_map.json
*/
{
  "imports": {
    "fmt/": "https://deno.land/std@0.173.0/fmt/"
  }
}
```

The import path of the following file has syntax warnings for wavy lines:
Relative import path "fmt/colors.ts" not prefixed with / or ./ or ../deno(import-prefix-missing)
```js
/*
* color.ts
*/
import { red } from "fmt/colors.ts";

console.log(red("hello world"));
```
deno run --import-map=import_map.json color.ts

**Comment by bartlomieju** [comment]
You need to specify a path for import map file in `deno.json` or use `deno.importMap` setting in the `.vscode/settings.json`. Import map files are not auto discovered by the extension.

**Comment by dong-lufei** [comment]
Well now, no warnings

**Comment by bartlomieju** [comment]
Okay cool, I'm gonna close this issue now then.

**Comment by dong-lufei** [comment]
@bartlomieju 
deno.json or deno.jsonc 
{
 "imports": {
    "std/": "https://deno.land/std@0.174.0/"
  }
  //"importMap": "import_map.json",
}
Does the imports option of this configuration file replace the previous importMap option?

**Comment by dong-lufei** [comment]
Can both import_map.json and deps.ts be discarded, only use the imports of deno.json
