### ISSUE TITLE
Misleading error message when trying to use Deno.spawn

### ISSUE THREAD

**Issue by rherrmann** [denoland/deno#17521]
When trying to compile old code that invokes `Deno.spawn` with the latest version (1.29.4) the following error is printed:

```
$> deno compile -A --unstable src/main.ts
Check file:///src/main.ts
error: TS2339 [ERROR]: Property 'spawn' does not exist on type 'typeof Deno'. 'Deno.spawn' is an unstable API. Did you forget to run with the '--unstable' flag?
      const { success, stdout, stderr } = await Deno.spawn(program, {
                                                     ~~~~~
```

The hint to the unstable API seems misleading (even more so as `--unstable` was given) or am I missing something here?

**Comment by dsherret** [comment]
It shouldn't have been giving that error. That unstable API doesn't exist in newer versions of Deno.
