### ISSUE TITLE
🐛 POSIX: `deno upgrade` leaves temporary directory with large files in */tmp*

### ISSUE THREAD

**Issue by rivy** [denoland/deno#17533]
When upgrading from Deno v1.29.4 to v1.30.0, the upgrade failed because of tmpfs exhaustion. In tracking the issue, it was apparent that when using `deno upgrade`, Deno leaves a temporary directory in */tmp* with the downloaded zip file and its expansion. At least one prior version left the same residual files. As it didn't fail at the time, I can't determine which earlier versions are affected (maybe all of them).

```shell
$ ls -Al .tmpQ2GQJW
total 141460
-rwxr-x--x 1 root administrators 105538456 2023-01-16 16:42 deno
-rw-r----- 1 root administrators  39309948 2023-01-25 18:42 deno.zip
```
Obviously, these files are relatively large and this can exhaust the */tmp* storage quite quickly if not removed promptly. Please clean up after the upgrade is completed.

**Comment by dsherret** [comment]
I think this was fixed by https://github.com/denoland/deno/pull/16930

**Comment by rivy** [comment]
@dsherret , thanks for the quick response!
