### ISSUE TITLE
deno no quickfix for npm packages imported without vite.config.mjs file?

### ISSUE THREAD

**Issue by dong-lufei** [denoland/deno#17539]
deno has syntax hints and quick fixes in these files. After the fix, the syntax wavy line is gone, and the version number is automatically added
```
import { Application, Router } from "https://deno.land/x/oak/mod.ts";
import { Application, Router } from "https://deno.land/x/oak@v11.1.0/mod.ts";
```
But the packages imported in the vite.config.mjs file don't have the functionality of this quick-fix version
```
import { defineConfig } from "npm:vite"
import vue from "npm:@vitejs/plugin-vue"
import "npm:vue"
import "npm:vue-router"

export default defineConfig({
  plugins: [vue()],
})

```

**Comment by dsherret** [comment]
This is #16479. Follow that issue for updates. #15811 might also be of interest.
