### ISSUE TITLE
Make `deno fmt` options CLI args less verbose

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#17546]
Related to #17529

The `deno fmt` options are too verbose. We should alias flags like `--options-indent-width 4` to without `options-` like `--indent-width 4` then deprecate the options flags in 2.0.

1. This change requires only modifying https://github.com/denoland/deno/blob/main/cli/args/flags.rs 
1. The `--options-indent-width`-like args should not show up in the help anymore (be hidden), but should still work if used

**Comment by miikkuu** [comment]
@dsherret Want to work on this . Is this already fixed.Newbie here!

**Comment by bartlomieju** [comment]
Sorry @miikkuu there is already a PR open for this change

**Comment by aapoalas** [comment]
Fixed by #17550
