### ISSUE TITLE
Deno FFI crash

### ISSUE THREAD

**Issue by haraldkubota** [denoland/deno#17569]
I am trying to adopt an existing Dart FFI library I created to adopt to Deno: it's simple C sending out data out the Ethernet link. No receiving. Super-simple. Opening sockets and closing works. But when I tried to get the MAC address of the used interface, I got a crash.

System used:

1. Linux t621 5.15.0-58-generic #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux, Deno version 1.29.3, 1.30.0
2. Linux vim3l 5.9.0-rc2 #0.9.4 SMP PREEMPT Mon Sep 28 16:51:38 CST 2020 aarch64 GNU/Linux, Deno version 1.29.4

`
❯ sudo RUST_BACKTRACE=1 ~/.deno/bin/deno run --unstable --allow-ffi ffi.ts
12

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 1.30.0
Args: ["/home/harald/.deno/bin/deno", "run", "--unstable", "--allow-ffi", "ffi.ts"]

thread 'main' panicked at 'internal error: entered unreachable code', ext/ffi/call.rs:116:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panicking.rs:65:14
   2: core::panicking::panic
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panicking.rs:115:5
   3: <extern "C" fn(A0) .> R as v8::support::CFnFrom<F>>::mapping::c_fn
   4: _ZN2v88internal12_GLOBAL__N_119HandleApiCallHelperILb0EEENS0_11MaybeHandleINS0_6ObjectEEEPNS0_7IsolateENS0_6HandleINS0_10HeapObjectEEENS8_INS0_20FunctionTemplateInfoEEENS8_IS4_EEPmi
             at ./../../../../v8/src/builtins/builtins-api.cc:112:36
   5: _ZN2v88internal21Builtin_HandleApiCallEiPmPNS0_7IsolateE
             at ./../../../../v8/src/builtins/builtins-api.cc:130:1
   6: Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
`

Same happens when not running as root, but I cannot open the socket in raw mode.

(Almost) Minimal sample code to reproduce: https://github.com/haraldkubota/bugreports/tree/main/deno_ffi

**Comment by aapoalas** [comment]
`"void"` is not a valid parameter type (C's void parameter type just means "no parameters" and is a tad bit stronger than leaving the parameters empty). I think that should be throwing an error at least... Not sure if that's related to this throw though.

**Comment by haraldkubota** [comment]
Oops...ok, works after updating
```
        "get_mac_addr": {parameters: [], result: "u64"},
```
