### ISSUE TITLE
Suggestion: update shell completions during `deno upgrade`

### ISSUE THREAD

**Issue by GJZwiers** [denoland/deno#17560]
When Deno adds a new CLI flag the `deno completions` command needs to be run again to enable auto-completion for it on the terminal. It would be nice if this could somehow be done automatically as part of running `deno upgrade`.

**Comment by crowlKats** [comment]
This is quite unfeasible to implement, for same reasons we dont automatically add deno during install to your shell file or have a command to uninstall deno; there are too many places it possibly could be for each different shell.
