### ISSUE TITLE
Run works but bundle issues an error

### ISSUE THREAD

**Issue by zeritonius** [denoland/deno#17576]
This is the full contents of the file test.ts
```
const myname: string[] = [];
myname.push(7);
console.log(myname);
```

Here's what I get when I try to run | bundle test.ts
```
D:\deno>deno run test.ts
[ 7 ]

D:\deno>deno bundle test.ts out.js
Check file:///D:/deno/test.ts
error: TS2345 [ERROR]: Argument of type 'number' is not assignable to parameter of type 'string'.
myname.push(7);
            ^
at file:///D:/deno/test.ts:2:13
```
Here are the details about the versions I use:
```
D:\deno>deno --version
deno 1.30.0 (release, x86_64-pc-windows-msvc)
v8 10.9.194.5
typescript 4.9.4

D:\deno>ver
Microsoft Windows [Version 10.0.19045.2486]
```

What am I doing wrong, please?
Thank you.

**Comment by bartlomieju** [comment]
You would get the same error if running `deno check` or `deno run --check test.ts` - you have a mistmatch in your types - the array expects strings but you're pushing a number.

**Comment by zeritonius** [comment]
I'm sorry, but I'm missing something here. If I just run the "deno run test.ts", having a mistmatch in the types, what file is actually run? That is, where did the result ['7'] that was displayed come from? 

If I run tsc:
```
tsc test.ts
test.ts(2,13): error TS2345: Argument of type 'number' is not assignable to parameter of type 'string'.
```
I receive an error, not ['7']. Shouldn't have happen the same when I run 'deno run test.ts", without the --check? I don't understand why I don't receive an error when running "deno run test.ts" and I get a wrong result.

**Comment by bartlomieju** [comment]
> I'm sorry, but I'm missing something here. If I just run the "deno run test.ts", having a mistmatch in the types, what file is actually run? That is, where did the result ['7'] that was displayed come from?
> 
> If I run tsc:
> 
> ```
> tsc test.ts
> test.ts(2,13): error TS2345: Argument of type 'number' is not assignable to parameter of type 'string'.
> ```
> 
> I receive an error, not ['7']. Shouldn't have happen the same when I run 'deno run test.ts", without the --check? I don't understand why I don't receive an error when running "deno run test.ts" and I get a wrong result.

If you transpile this code (ie. transform TypeScript to JavaScript), it's perfectly fine code - you can push to your array whatever you want. The error is returned from the TypeScript compiler complaining about incompatible types - but for JavaScript you can't "require" that array contains only certain types. Deno doesn't type check by default in `deno run` any more, see: https://deno.com/blog/v1.24#type-checking-and-emitting-performance-improvements.

**Comment by zeritonius** [comment]
It makes perfect sense now. Thank you so much for your explanation.
