### ISSUE TITLE
Use name of config file in `deno install`

### ISSUE THREAD

**Issue by vwkd** [denoland/deno#17571]
It seems `deno install` generates a `.my-module.tsconfig.json` regardless of what config file is passed by `--config`. It would be clearer if it used the name of the config file instead, e.g. `.my-module.deno.jsonc`.

This is a purely cosmetic issue. The functionality works as expected.

## Steps To Reproduce

```
deno install -n my-module --config=deno.jsonc src/main.ts
```

Note: It seems the config file is not auto-discovered yet, see https://github.com/denoland/deno/issues/17572

## Expected Result

```
#!/bin/sh
# generated by deno install
exec deno run --config /Users/foo/.deno/bin/.my-module.deno.jsonc 'file:///Users/bar/baz/src/main.ts' "$@"
```

## Actual Result

```
#!/bin/sh
# generated by deno install
exec deno run --config /Users/foo/.deno/bin/.my-module.tsconfig.json 'file:///Users/bar/baz/src/main.ts' "$@"
```

**Comment by dsherret** [comment]
It would introduce a lot of complexity. For `deno uninstall` we clean up and delete files based on their filename only so figuring out what files to remove on uninstall if they had variable names would be complex.

That said, we should change this default name from `tsconfig.json` to `deno.json`. The tsconfig.json is legacy when we only supported tsconfig. I will open a PR.
