### ISSUE TITLE
deno fmt `export { build, type IConfig, publish }`

### ISSUE THREAD

**Issue by loynoir** [denoland/deno#17577]
### Actual
```ts
export { build, type IConfig, publish }
```

### Expected
```ts
export { type IConfig, build, publish }
```

or maybe 
```ts
export { build, publish, type IConfig }
```

**Comment by miikkuu** [comment]
@loynoir Would like to solve this ...Should I continue?

**Comment by dsherret** [comment]
Why should these be sorted this way? Some people might want the actual output. Seems kind of arbitrary how this is sorted.
