### ISSUE TITLE
Update wgpu for TersorflowJS WebGPU support

### ISSUE THREAD

**Issue by vicary** [denoland/deno#17580]
In mid 2022, I wanted to migrate my tensorflow.js projects into Deno, only to find that their WebGPU backend is mysteriously failing https://github.com/tensorflow/tfjs/issues/6842.

It turns out `naga` was interpreting wgsl in lexical order https://github.com/gfx-rs/naga/pull/2075, luckily the new module level scoping has been released in `naga` 0.11 and `wgpu` 0.15.

Is it possible for Deno to update `wgpu` to 0.15?

**Comment by crowlKats** [comment]
There is a PR open for this: #17534

**Comment by vicary** [comment]
@crowlKats Out of curiosity, will this be released as a patch or the next minor?

**Comment by crowlKats** [comment]
@vicary patch

**Comment by vicary** [comment]
@crowlKats Thanks!
