### ISSUE TITLE
`deno install` doesn't recoginze remote import_maps in `deno.json`

### ISSUE THREAD

**Issue by timharek** [denoland/deno#17598]
I started using `imports` in `deno.json` since it was announced for Deno 1.30, but I realized today that when you install something with `deno install` the runner won't recoginze the import.

Example running this ([repo](https://github.com/timharek/wcarbon):
```sh
deno install --allow-net=api.websitecarbon.com \
   -n wcarbon https://deno.land/x/wcarbon/src/cli.ts
```

Will tell you something like this:
```sh
$ wcarbon netlife.com
error: Relative import path "std/flags/mod.ts" not prefixed with / or ./ or ../
    at https://deno.land/x/wcarbon@v1.4.0/deps.ts:1:2
```

Even though the project has specified the import in its [`deno.json`](https://github.com/timharek/wcarbon/blob/main/deno.json#L29)

**Comment by dsherret** [comment]
`deno install` (and deno run) doesn't work or pick up remote configuration files. In the future there will be support for this scenario on the deno.land/x registry via #2650 and it will just work, but for now you will need to change the code published on deno.land/x to not use an import map. Sorry about that, but it will be better soon.
