### ISSUE TITLE
error: Unexpected token Some(AssignOp("=")) at https://deno.land/std@0.175.0/node/internal/validators.mjs:41:10

### ISSUE THREAD

**Issue by Avratz** [denoland/deno#17594]
I'm trying to run the example from [https://deno.land/x/puppeteer@16.2.0](https://deno.land/x/puppeteer@16.2.0)

```
import puppeteer from 'https://deno.land/x/puppeteer@16.2.0/mod.ts'

const browser = await puppeteer.launch()
const page = await browser.newPage()
await page.goto('https://deno.land/')
await page.screenshot({ path: 'example.png' })

await browser.close()
```

$ deno run -A --unstable example.ts
Download https://esm.sh/v106/node.ns.d.ts
Download https://deno.land/std@0.175.0/node/process.ts
Download https://deno.land/std@0.175.0/node/string_decoder.ts
Download https://esm.sh/v106/isarray@1.0.0/deno/isarray.js
Download https://esm.sh/v106/safe-buffer@5.1.2/deno/safe-buffer.js
Download https://esm.sh/v106/util-deprecate@1.0.2/deno/util-deprecate.js
Download https://deno.land/std@0.175.0/node/util.ts
Download https://deno.land/std@0.175.0/node/events.ts
Download https://esm.sh/v106/process-nextick-args@2.0.1/deno/process-nextick-args.js
Download https://esm.sh/v106/inherits@2.0.4/deno/inherits.js
Download https://esm.sh/v106/core-util-is@1.0.3/deno/core-util-is.js
Download https://esm.sh/v106/immediate@3.0.6/deno/immediate.js
**error: Unexpected token Some(AssignOp("=")) at https://deno.land/std@0.175.0/node/internal/validators.mjs:41:10**

**Comment by dsherret** [comment]
What version of Deno are you using?

**Comment by Avratz** [comment]
**deno --version**
```
deno 1.1.0
v8 8.4.300
typescript 3.9.2
```

I tried to upgrade to the latest version but when I run _deno upgrade_ I get the following error: 

```
Checking for latest version
error: Cannot read latest tag version
```

**Comment by dsherret** [comment]
Your version is super old. Maybe try manually updating, which is just doing an install: https://deno.land/manual@v1.30.0/getting_started/installation

I think your version of Deno just doesn't know how to parse `??=`.

**Comment by Avratz** [comment]
I Tried installing it again, and nothing happened. Any idea?

```
PS C:\WINDOWS\system32> irm https://deno.land/install.ps1 | iex
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 28.9M  100 28.9M    0     0  5866k      0  0:00:05  0:00:05 --:--:-- 7197k
Deno was installed successfully to C:\Users\Avratz\.deno\bin\deno.exe
Run 'deno --help' to get started
Stuck? Join our Discord https://discord.gg/deno

PS C:\WINDOWS\system32> deno --version
deno 1.1.0
v8 8.4.300
typescript 3.9.2
```

**Comment by dsherret** [comment]
Try using `Get-Command -name deno` to see where it's getting the deno executable from.

**Comment by Avratz** [comment]
I replaced the older .exe in the directory with the new one, and all works now.

Thank you for your time!

```
PS C:\WINDOWS\system32> deno --version
deno 1.30.0 (release, x86_64-pc-windows-msvc)
v8 10.9.194.5
typescript 4.9.4
```
