### ISSUE TITLE
Error when deploying script globally - locally works. puppeteer

### ISSUE THREAD

**Issue by pixelkoduje** [denoland/deno#17597]
Locally, the script works without any problems. When I upload it globally, I get a permission error.

![image](https://user-images.githubusercontent.com/102321542/215585978-dda7b298-6b7c-49dd-8677-154b36f945db.png)

![image](https://user-images.githubusercontent.com/102321542/215585873-67b9fbb7-4b04-4159-b905-048188707c86.png)

**Comment by pixelkoduje** [comment]
I am asking for help to make the puppeteer work on your servers. thank you

**Comment by lino-levan** [comment]
A few things that make this infeasible afaik:
- I'm pretty sure this is against deploy's TOS against scraping
- Puppeteer requires a huge amount of memory, which deploy will not provide
- Puppeteer requires installing a whole browser, you can't do this step in deploy
- It looks like puppeteer attempts to use APIs that are not allowed in deploy, not much that can be done to get around that

**Comment by crowlKats** [comment]
In addition to the previously provided answer, the specific error you are getting is regarding writing to disk, which is not possible on deploy.
