### ISSUE TITLE
`deno fmt` should inherit `.editorconfig` style

### ISSUE THREAD

**Issue by loynoir** [denoland/deno#17612]
### Background
Just give a try to no-nester style indent,  aka linux kernel style.
Found `denoland.vscode-deno` not inherit .editorconfig style, which `esbenp.prettier-vscode` inherit it by default.

### Actual
- `esbenp.prettier-vscode` inherit .editorconfig style
- commandline `prettier ./reproduce.ts` inherit .editorconfig style
- `denoland.vscode-deno` **not** inherit .editorconfig style
- commandline `deno fmt ./reproduce.ts` **not** inherit .editorconfig style

### Expected
- `esbenp.prettier-vscode` inherit .editorconfig style
- commandline `prettier ./reproduce.ts` inherit .editorconfig style
- `denoland.vscode-deno` not inherit .editorconfig style
- commandline `deno fmt ./reproduce.ts` not inherit .editorconfig style

### Reproduce
- Adjust `.editorconfig` with
```
indent_size = 8
```

- Run `prettier -w reproduce.ts`
- Expect indent_size is 8, and actual indent_size is 8.
- Run `deno fmt reproduce.ts`.
- Expect indent_size is 8, but actual indent_size is 2.

### Related
https://github.com/denoland/vscode_deno/issues/803

**Comment by dsherret** [comment]
@loynoir Sorry, I'm not sure what this issue is saying. Could you clarify and give it a descriptive title? Thanks!
