### ISSUE TITLE
deno version 1.30.1 large cpu increase

### ISSUE THREAD

**Issue by xeaone** [denoland/deno#17629]
I am getting a large cpu usage increase. Is this a known issue? 

- Deno version 1.30.1
- WSL2 Debian

**Comment by bartlomieju** [comment]
Can you show your workload that shows CPU usage increase?

**Comment by bartlomieju** [comment]
It's probably caused by https://github.com/denoland/deno/commit/e85ca8be0dafdab28e6283aed64c8ee0eb3a338d but I want to verify that before reverting.

**Comment by xeaone** [comment]
Yes. Is a screen shot of windows task manager showing cpu usage on 1.30.0 and then another screen shot on 1.30.1? Or is there a more ideal way to show the CPU use?

**Comment by PiotrKieltyka** [comment]
> I am getting a large cpu usage increase. Is this a known issue?

same here..

Deno 1.30.0 @ sha256:8a287de2bea72037974dc021c94f783142d6cdea1d738b571104a242af364200

![deno1300](https://user-images.githubusercontent.com/8939646/216559186-799923e3-31e5-45b2-8d3f-5eb1fdc40898.png)

Deno 1.30.1 @ sha256:497b8149633dcc360158eac73d226d37712918a05d29674ce4771de04a054ce9

![deno1301](https://user-images.githubusercontent.com/8939646/216559232-01c6fdc8-022b-44d0-b763-48f9ddf6d0c3.png)

**Comment by bartlomieju** [comment]
@xeaone thanks, not needed after all. I confirmed that the linked PR was indeed problematic. We'll release 1.30.2 release that fixes the problem.
