### ISSUE TITLE
lsp: Quick fix for redirected imports always adds double quotes

### ISSUE THREAD

**Issue by relrelb** [denoland/deno#17645]
## Steps to reproduce behavior

Consider the following code:

```ts
// @deno-types='https://esm.sh/@types/node'
import 'https://esm.sh/colors';
```

Deno's LSP suggests (justifiably) that both URLs are redirected, and provides a quick fix to "update specifier to its redirected specifier".

However, when applying the fixes, the following code is received:

```ts
// @deno-types='"https://esm.sh/v106/@types/node@18.11.18/index.d.ts"'
import "https://esm.sh/colors@1.4.0";
```

Which is invalid, due to the two pairs of quotes enclosing the `@deno-types` URL.
Also note that the `import` statement changed from single quotes to double quotes.

A similar error happens with triple-slash reference `types` directive:

```ts
/// <reference types=""https://esm.sh/v106/@types/node@18.11.18/index.d.ts"" />
import "https://esm.sh/colors";
```

## Expected behavior

Applying the quick fix doesn't add an extra `"`, and the original quotes are preserved.

## Version

Deno v1.30.0

## Suggested fix

It seems like the extra `"` are added here:

https://github.com/denoland/deno/blob/a635c9700c0b99c3ad128c21727fdcfb23bad72f/cli/lsp/diagnostics.rs#L757

I suggest removing them completely:

```diff
-                  new_text: format!("\"{}\"", data.redirect),
+                  new_text: data.redirect.into(),
```

This should fix the case of `@deno-types` and triple-slash directives (as their `diagnostic.range` includes just the URL without its enclosing quotes), but should regress the case of `import` statements (as their `diagnostic.range` includes the URL and its enclosing quotes). Therefore I suggest excluding the quotes from `specifier_range` of `import`/`exports` statements:

https://github.com/denoland/deno_graph/blob/ffc6fca09466b07d8e37e560b6546acb6cbd5a48/src/ast.rs#L322

However this might have some far-reaching consequences that I'm not sure about.

**Comment by dsherret** [comment]
Yeah, the range should not include the quote.

**Comment by dsherret** [comment]
@relrelb since you diagnosed the problem, would you be interested in contributing the fix?

**Comment by nayeemrmn** [comment]
Fixed by https://github.com/denoland/deno_graph/pull/220.
