### ISSUE TITLE
Suggestion: stabilize remaining unstable flags of `deno test`

### ISSUE THREAD

**Issue by GJZwiers** [denoland/deno#17659]
The CLI docs for `deno test` show three flags still listed as unstable: `--coverage`, `--doc`, and `--shuffle`. All of these have been around for quite some time and they seem to be working well, so perhaps they could be stabilized?

**Comment by bartlomieju** [comment]
Yes, that sounds reasonable. PRs are welcome

**Comment by Antonio476587** [comment]
#17664

**Comment by GJZwiers** [comment]
@Antonio476587 While `deno coverage` still has a few bugs, in Deno going from unstable to stable does not mean there are no more issues, only that the API will not change anymore, except potentially on a new major version or in case of a security hazard. AFAIK there are no plans to remove or alter `deno test --coverage`, which is why I made the suggestion to stabilize it.
