### ISSUE TITLE
Dynamic imports require net access even when they are unused

### ISSUE THREAD

**Issue by jespertheend** [denoland/deno#17658]
```js
if (false) {
	await import("https://deno.land/std@0.176.0/node/module.ts")
}
```
```
> % deno run foo.js
⚠️  ┌ Deno requests net access to "deno.land".
   ├ Requested by `import()` API
   ├ Run again with --allow-net to bypass this prompt.
   └ Allow? [y/n] (y = yes, allow; n = no, deny) > 
```

I feel like it's only supposed to request access the moment the `await import()` is called, or am I missing something?

For the moment a workaround is to keep the import specifier in a separate variable:
```js
if (false) {
	const str = "https://deno.land/std@0.176.0/node/module.ts";
	const mod = await import(str);
}
```
But this removes type safety and turns `mod` into `any`.

**Comment by jespertheend** [comment]
It also seems like imports to large module graphs cause a significantly longer startup time, for instance:

```js
console.log(performance.now());

if (false) {
	const mod = await import("https://deno.land/x/puppeteer@16.2.0/mod.ts");
}
```

logs about 270ms for me, whereas without the import it logs about 220ms. I have a more severe example in a local project where startup time takes about a second as opposed to 220ms.

**Comment by dsherret** [comment]
Would be solved by https://github.com/denoland/deno/issues/17697
