### ISSUE TITLE
lsp: when resolving local imports with deno-types or reference, extra dot added at the beginning

### ISSUE THREAD

**Issue by Antonio476587** [denoland/deno#17689]
https://user-images.githubusercontent.com/93491383/217404366-f3dd6ae8-e242-4ca7-9b6f-45f1d15e60e8.mp4

https://user-images.githubusercontent.com/93491383/217404374-3fb244fd-717b-437a-a23d-45c40d3d171d.mp4

**Comment by nayeemrmn** [comment]
Look fixed
