### ISSUE TITLE
Disallow relative module specifies that don't start with "./", "../", "/"

### ISSUE THREAD

**Issue by ry** [denoland/deno#1769]
Apparently web browsers don't allow this:
```js
import 'bar.js'
```
Chrome: `Uncaught TypeError: Failed to resolve module specifier "bar.js". Relative references must start with either "/", "./", or "../".`
Firefox: `TypeError: Error resolving module specifier: bar.js`
Safari: `TypeError: Module specifier does not start with "/", "./", or "../".`

Thanks to @thgh [for reporting this](https://github.com/denoland/deno/issues/1750#issuecomment-463129189).

Does anyone have a reference to the standard spec that states this?

We should also error on this. We're currently doing this all over the place.

**Comment by thgh** [comment]
Spec: https://html.spec.whatwg.org/multipage/webappapis.html#resolve-a-module-specifier

**Comment by manyuanrong** [comment]
I want to work here, before I start, I want to know that I need to detect when I use `--prefetch` ?

**Comment by ry** [comment]
@manyuanrong `--prefetch` shouldn't be related to this?

**Comment by manyuanrong** [comment]
@ry Okey, I understand, but this check need to bypass the Deno command line?
For example, keep using `deno test.ts` instead of forcing `deno ./test.ts`

**Comment by kitsonk** [comment]
It should be the reverse, when parsing the argument module art, if it does not start with a protocol, or `./`, `../`, or `/` then it should have `./` prepended irrespective of any other flags.

**Comment by zekth** [comment]
@ry this can be closed.
