### ISSUE TITLE
valid usage of napi_ref_threadsafe_function can cause 100% cpu usage

### ISSUE THREAD

**Issue by littledivy** [denoland/deno#17691]
Simple example like this causes a hot loop in Deno's implementation. The module continues to function, see below:
```c
// from fsevents ...
CHECK(napi_create_threadsafe_function(env, argv[3], asyncResource, asyncName, 0, 2, NULL, NULL, NULL, fse_dispatch_event, &instance->callback) == napi_ok);
CHECK(napi_ref_threadsafe_function(env, instance->callback) == napi_ok);
```

![image](https://user-images.githubusercontent.com/34997667/217431456-25261646-5c1f-425f-a9a3-18b5143d64bf.png)

We need to rethink use of event loop middleware. I think each tsfn should get a waker to the main thread instead.

**Comment by bartlomieju** [comment]
I believe this is no longer the case after rewrite of N-API in https://github.com/denoland/deno/pull/24101
