### ISSUE TITLE
Remove "emit" and "map" from `deno info --json` output

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#17703]
We should remove both "emit" and "map" from the output of `deno info --json`.

```jsonc
{
      "dependencies": [
        // etc...
      ],
      "kind": "esm",
      "local": "C:\\Users\\david\\AppData\\Local\\deno\\deps\\https\\deno.land\\08d9a8e609cf8dd460c936bbd31868d54b9fce2740085096564b2fada923e719",
      "emit": "C:\\Users\\david\\AppData\\Local\\deno\\gen\\https\\deno.land\\08d9a8e609cf8dd460c936bbd31868d54b9fce2740085096564b2fada923e719.js",
      "map": null,
      "size": 14342,
      "mediaType": "TypeScript",
      "specifier": "https://deno.land/x/oak@v11.1.0/util.ts"
    }
```

**Reason to remove "map"**

It is not used at all. This is always `null`.

**Reason to remove "emit"**

1. It is extremely unreliable to depend on the emit file and nobody should be doing this. It might be out of date from the source and be completely wrong. Instead, people should get the local file then use deno_emit to get the emit https://github.com/denoland/deno_emit
2. How we store the emit should be private data only known to the CLI. This will allow us to make performance optimizations.

Getting the emit meta-data with cache could be a single file read instead of multiple for example:

![image](https://user-images.githubusercontent.com/1609021/217916168-253a81c4-2075-4923-9ef3-31d8d0c85bd7.png)

**Comment by bartlomieju** [comment]
Check with https://github.com/lucacasonato/esbuild_deno_loader which changes are needed

**Comment by ry** [comment]
text output of `deno info` should be shell parsable instead of 
```
DENO_DIR location: /Users/ry/Library/Caches/deno
Remote modules cache: /Users/ry/Library/Caches/deno/deps
npm modules cache: /Users/ry/Library/Caches/deno/npm
Emitted modules cache: /Users/ry/Library/Caches/deno/gen
Language server registries cache: /Users/ry/Library/Caches/deno/registries
Origin storage: /Users/ry/Library/Caches/deno/location_data
```
it should be
```
DENO_DIR="/Users/ry/Library/Caches/deno"
DENO_REMOTE_CACHE="/Users/ry/Library/Caches/deno/deps"
DENO_NPM_CACHE="/Users/ry/Library/Caches/deno/npm"
DENO_EMITTED_CACHE="/Users/ry/Library/Caches/deno/gen"
DENO_LSP_REGISTRIES_CACHE="Users/ry/Library/Caches/deno/registries"
DENO_ORIGIN_STORAGE="/Users/ry/Library/Caches/deno/location_data"
```
