### ISSUE TITLE
Failed detection of symlinks with `Deno.stat[Sync]` as well as `Deno.lstat[Sync]`

### ISSUE THREAD

**Issue by andrewbrey** [denoland/deno#17723]
Thank you all for your hard and excellent work on Deno and the related ecosystem!

The `Deno.stat` and `Deno.statSync` api's, when provided both hard and soft file links, produce `Deno.FileInfo` objects where `isSymlink` is `false`. This is unexpected and _probably not right_ (unless I'm missing something).

I have not tested this on Windows or Mac, so it may be a Linux only issue for all I know.

**Minimal Reproduction Repository**

https://github.com/andrewbrey/deno_symlink_stat_issue

![image](https://user-images.githubusercontent.com/34140052/218174160-1e47b3d4-a012-48e7-aa91-6e16a53e0c63.png)

**Expected behavior**

The `Deno.FileInfo` object produced by `Deno.stat[Sync]` should indicate that `isSymlink` is `true` for a link.

**Notes / Environment**

```
deno --version
deno 1.30.3 (release, x86_64-unknown-linux-gnu)
v8 10.9.194.5
typescript 4.9.4

OS: Pop!_OS 22.04 LTS x86_64 (Linux)

VS Code Version: 1.75.1
```

**Comment by crowlKats** [comment]
You need to use `lstat` instead of `stat` for symlinks

**Comment by andrewbrey** [comment]
@crowlKats I just tested this with `lstat` as well, and it still produces `isSymlink: false` - I have updated the reproduction repository I linked in the issue to demonstrate this.

**Comment by andrewbrey** [comment]
@crowlKats I indicate this in the readme of the linked reproduction, but an actual symlink (not a hard link) is correctly identified as a `symlink` by `lstat`. I guess this may come down to just a lack of understanding on my part, although, it's a bit odd that `isSymlink` is part of the object returned by `stat[Sync]` when it seems you can only _actually_ identify a symlink when using `lstat[Sync]` (and only when you have a symlink and not a hard link)

```
ln -sf $PWD/example.ts $PWD/symlink.ts
deno eval "console.log(Deno.lstatSync('symlink.ts').isSymlink)"
```

**Comment by sigmaSd** [comment]
The behavior seems correct ,  and it matches rust behavior, in rust there is https://doc.rust-lang.org/std/fs/fn.symlink_metadata.html (lstat on linux so it dosen't follow symlink) and https://doc.rust-lang.org/std/fs/fn.metadata.html (stat on linux) 
Also hardlinks are not considered symlinks by  rust as well

Personally I don't like the deno naming (which are taken from go) the rust ones are way more clear and the name doesn't make you think that they're platform specific

**Comment by andrewbrey** [comment]
To clarify, @sigmaSd I didn't think the "l" in "lstat" stood for Linux, I only brought up the platform because there are differences in how different platforms treat links and thought it might be relevant if there was a code issue.

I now think there is no code issue, but perhaps there _is_ an opportunity to clearer documentation in the jsdoc comments on the `Deno.FileInfo` object to explicitly say that `isSymlink` will only be true for actual symbolic links, and _not_ for hard links, like those created by `Deno.link`.

I'll close this issue as I believe my issue was 99.9% operator error and .1% imprecision of language :)

**Comment by sigmaSd** [comment]
I meant that lstat and stat are Linux terminology and apis windows has its own api, which is why it's weird to choose one platform name as the general function name 

I doubt deno should add documentation for this, it's how links work , hardlink is no different then a regular file (there is no is_hardlink)

**Comment by sigmaSd** [comment]
Btw why I dislike go std https://fasterthanli.me/articles/i-want-off-mr-golangs-wild-ride#simple-is-a-lie

**Comment by andrewbrey** [comment]
@sigmaSd Thanks for sharing, that was a fascinating read!
