### ISSUE TITLE
NPM compatibility cannot find module 'lightningcss'

### ISSUE THREAD

**Issue by oscarotero** [denoland/deno#17720]
I have created this version of TailwindCSS to make it work on Deno https://www.npmjs.com/package/@lumeland/tailwindcss

The version [3.2.5](https://www.npmjs.com/package/@lumeland/tailwindcss/v/3.2.5) works fine but when I tried to update it with the latest version of Tailwind I got a weird error. The succesive versions (3.2.6 ... 3.2.10) are different attempts to fix the error without lucky (I don't know how to test a local NPM package in Deno, so I had to publish it in NPM).

The error is that it doesn't find the module "lightningcss". But the module exists (https://www.npmjs.com/package/lightningcss) and even I can import it directly in deno with `import lighningcss from "npm:lightningcss";`. But it seems like it cannot find the package if it's imported as a dependency inside tailwindcss.

I've even modified the package in the local cache of Deno and `postcss` and `browserlist` are required without problems but `lightningcss` fails:

<img width="1456" alt="imaxe" src="https://user-images.githubusercontent.com/377873/218156270-31d46240-8417-4ee5-a97f-e20a692943e4.png">

**Comment by aapoalas** [comment]
I was just able to successfully run the following:

```ts
import * as ls from "npm:@lumeland/tailwindcss";

console.log(ls);
```

Perhaps try the `--reload` flag to make sure NPM packages are redownloaded?

**Comment by oscarotero** [comment]
@aapoalas Yeah, it doesn't fail when it's only imported, but if it's used. The following code fails:

```ts
import tailwind from "npm:@lumeland/tailwindcss@3.2.10";
import postcss from "npm:postcss@8.4.21";

const tw = tailwind({
  content: [
    { raw: '<div class="font-bold">Hello</div>', extension: 'html' },
  ]
});

const css = `
@tailwind base;
`;

const result = await postcss([tw]).process(css, { from: undefined });

console.log(result);
```

**Comment by aapoalas** [comment]
Hmm, seems like this might be related to "dynamic require". I was able to run the module by adding the following lines in the beginning:

```ts
import "npm:lightningcss";
import "npm:browserslist";
```

**Comment by oscarotero** [comment]
This bug was fixed. I'm closing it.
