### ISSUE TITLE
Problems with TypeScript 3.3

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#1772]
I tried to upgrade Deno to TypeScript 3.3.1 but ran into an issue where it isn't properly working with `noLib` but including the library in the `files` array in the `tsconfig.json`.  It causes the build of the bundles to fail, claiming it cannot find JavaScript builtins.

Because we have a custom runtime, it is unsafe to build Deno without using the `noLib` option, as the code would not be type safe.

It also affects current versions of VSCode which defaults to using TypeScript 3.3 (which @piscisaureus has run into).  To work around you would have to use the workspace version of TypeScript (3.2.1):

<img width="604" alt="metrics_ts_ _deno" src="https://user-images.githubusercontent.com/1282577/52755014-a0837f00-3050-11e9-81fd-b5372e75b35f.png">

**Comment by bartlomieju** [comment]
@kitsonk it this issue still happening with latest release that uses TypeScript 3.4.1?

**Comment by kitsonk** [comment]
This is all resolved now.
