### ISSUE TITLE
`new Date('YYYY-MM-DD HH:mm:ss')` is `Invalid Date`

### ISSUE THREAD

**Issue by scarf005** [denoland/deno#17738]
### Deno
```ts
$ deno
Deno 1.30.0
exit using ctrl+d, ctrl+c, or close()
REPL is running with all permissions allowed.
To specify permissions, run `deno repl` with allow flags.
> new Date('2023-01-25 13:13:47')
Invalid Date
```

### Node
```sh
$ node
Welcome to Node.js v19.5.0.
Type ".help" for more information.
>  new Date('2023-01-25 13:13:47')
2023-01-25T04:13:47.000Z
```
### Firefox
![image](https://user-images.githubusercontent.com/54838975/218264164-cbb41977-17fc-4ba0-bbbe-37bcad989131.png)

i know it's not correct ISO 8601 format, but is this behavior documentated?

**Comment by magurotuna** [comment]
In my environments (macOS and Ubuntu), that works fine in Deno both in 1.30.0 and 1.30.3 (latest).

```
❯ deno
Deno 1.30.0
exit using ctrl+d, ctrl+c, or close()
REPL is running with all permissions allowed.
To specify permissions, run `deno repl` with allow flags.
> new Date('2023-01-25 13:13:47')
2023-01-25T04:13:47.000Z
```

It's so weird... what happens if you run the following snippet via `deno run`?

```ts
const d = new Date('2023-01-25 13:13:47');
console.log(d);

const invalid = new Date('invalid');
console.log(invalid);
```

**Comment by scarf005** [comment]
```ts
deno run test.ts
A new release of Deno is available: 1.30.0 → 1.30.3 Run `deno upgrade` to install it.
2023-01-25T04:13:47.000Z
Invalid Date
```
i'll try again after upgrading to 1.30.3

**Comment by magurotuna** [comment]
Your output seems fine - the first line shows `2023-01-25T04:13:47.000Z` (which corresponds to `d` in the snippet) and the second line `Invalid Date` (corresponds to `invalid`), right?
In that case, I believe executing `new Date('2023-01-25 13:13:47')` on REPL should also be working.

**Comment by scarf005** [comment]
very strange, upgrading to 1.30.3 indeed fixed the issue. maybe it was because of me installing deno from asdf?
anyways, thanks for the help!
