### ISSUE TITLE
denols fails to restart in nvim

### ISSUE THREAD

**Issue by alarbada** [denoland/deno#17747]
Good morning everyone.

I'm using nvim in linux with lspconfig. It provides useful commands like `:LspRestart`.

The thing is, if I do an `:LspStop` or an `:LspRestart`, `:LspStart` doesn't work anymore. Here are the logs.

```
Output of :LspRestart

[ERROR][2023-02-12 11:52:10] .../vim/lsp/rpc.lua:733	"rpc"	"deno"	"stderr"	"shutdown request received, shutting down\n"
[ERROR][2023-02-12 11:52:10] .../vim/lsp/rpc.lua:733	"rpc"	"deno"	"stderr"	"exit notification received, stopping\n"
```

If I interact with the lsp I get this log:

```
[ERROR][2023-02-12 11:52:46] .../vim/lsp/rpc.lua:733	"rpc"	"deno"	"stderr"	"language server has exited\n"
```

If I try to manually start denols, I get no logs.

I'm sorry if I'm reporting this to the wrong repo. If so, should I report it to the lspconfig repo?

Thanks for the deno runtime, I'm really liking it :smile:

**Comment by not-rusty** [comment]
I must also say, if I source my init.vim file again (I guess that means running the `require'lspconfig'.denols.setup{}` thing again), the lsp starts without problem.

**Comment by sigmaSd** [comment]
This issue belongs to https://github.com/neovim/nvim-lspconfig repo, you should mention there if this is spcific to denols or other lsp behave the same

**Comment by sigmaSd** [comment]
LspStop sends shutdown message to deno lsp server, the lsp spec says 
```
If a server receives requests after a shutdown request those requests should error with InvalidRequest.
```
 
so its not possible to reactivate the lsp after its been shutdown, I'm not sure whats LspStart is supposed to do, but it won't reactivate the server in anycase

**Comment by sigmaSd** [comment]
> I must also say, if I source my init.vim file again (I guess that means running the `require'lspconfig'.denols.setup{}` thing again), the lsp starts without problem.

That's because it starts a second lsp server

**Comment by nayeemrmn** [comment]
> LspStop sends shutdown message to deno lsp server, the lsp spec says
> 
> ```
> If a server receives requests after a shutdown request those requests should error with InvalidRequest.
> ```
> 
> so its not possible to reactivate the lsp after its been shutdown, I'm not sure whats LspStart is supposed to do, but it won't reactivate the server in anycase

Thanks for the info, sounds like it's behaving as expected.
