### ISSUE TITLE
Binaries output by `deno compile` don't pass strict MachO validation on macOS

### ISSUE THREAD

**Issue by jhheider** [denoland/deno#17753]
Apple even warns in the manpage that `--strict` is a moving target; however, other major language binaries don't exhibit this issue:

```sh
$ echo 'console.log("hello")' >foo.js
$ deno compile -o foo foo.js
Compile file:///Users/jacob/foo/foo.js
Emit foo
$ ./foo
hello
$ codesign -fv -s - foo
foo: replacing existing signature
foo: main executable failed strict validation
```

Google searching, but no actual exploration of the header, suggests that having the [wrong segment last](https://alexomara.com/blog/adding-a-segment-to-an-existing-macos-mach-o-binary/) is one of the common issues. I'm not sure I have the deep knowledge to dig further into this, but I'll look into as my time permits.

**Comment by aapoalas** [comment]
This may be related to https://github.com/denoland/deno/issues/575

**Comment by mxcl** [comment]
From [Apple docs](https://developer.apple.com/library/archive/technotes/tn2206/_index.html#//apple_ref/doc/uid/DTS40007919-CH1-TNTAG404):

> # codesign says my main executable failed strict validation.
> * Your Mach-O executable does not conform to modern Mach-O layout rules.
> * You may be using a third party development product that hasn't been brought up to date, or post-processed your file in unsupported ways.

**Comment by mxcl** [comment]
Confirmed this is fixed with deno^2
