### ISSUE TITLE
Deno upgrade error: program not found

### ISSUE THREAD

**Issue by mlindsten** [denoland/deno#17756]
I recently started using Deno and it's been working fine, but today I tried to run `deno upgrade` and got this error.

![deno_upgrade_error](https://user-images.githubusercontent.com/7278260/218411803-38ad0b5b-8d82-47af-b57e-b40b45c55bef.png)

I'm on Windows 10 and I've tried the upgrade command with two different Deno versions and get the same error. I don't know if this is a Deno issue or if there's a problem with my setup. In the latter case, I apologize, but how do I find/fix the problem?

**Comment by kamilogorek** [comment]
It's caused by PowerShell (`powershell.exe`) not being available for some reason. However, how to exactly fix this, is very env specific so you'll have to look around for your specific solution.

**Comment by mlindsten** [comment]
Thanks!

I didn't have the PowerShell folder in my Path variable. Adding it solved the problem!

Is there a way to run Deno commands with more verbose output or some other way I could've told what program the error message is referring to?

**Comment by kamilogorek** [comment]
Not yet, but sounds like a good addition :)
