### ISSUE TITLE
lsp does not know about imports from the deno config

### ISSUE THREAD

**Issue by jespertheend** [denoland/deno#17763]
For instance

**deno.json**
```json
{
	"importMap": "./importmap.json"
}
```
**importmap.json**
```json
{
	"imports": {
		"$std/": "https://deno.land/std@0.177.0/"
	}
}
```

works fine, but

**deno.json**
```json
{
	"imports": {
		"$std/": "https://deno.land/std@0.177.0/"
	}
}
```

causes an error when importing `"$std/path/mod.ts"`

![image](https://user-images.githubusercontent.com/2737650/218488051-89a8348d-a97d-4364-8241-a05a6aff0342.png)

In either case `deno run main.ts` works without any issues.

**Comment by dsherret** [comment]
What deno version are you using?

![image](https://user-images.githubusercontent.com/1609021/218493392-0d7ec055-5aef-4e96-bc38-97a3a85f8e09.png)

**Comment by jespertheend** [comment]
I'm on 1.30.3

**Comment by jespertheend** [comment]
Hmm the toolbar in vscode reports Deno 1.28.2, let me try and fix that

**Comment by jespertheend** [comment]
Seems like vscode_deno was picking a different version from my path compared to `deno -V` in my terminal.
Making sure vscode uses the latest version fixed my issue.
