### ISSUE TITLE
Problem with .mime files for modules imported without extension

### ISSUE THREAD

**Issue by kevinkassimo** [denoland/deno#1776]
`.mime` files have been used in some way to instruct TS compiler how to resolve a file.
For example, for a file `no_ext`:
```ts
console.log("NO_EXT");
```
Creating a file `no_ext.mime` with content type
```
application/javascript
```
allows `deno no_ext` to run the file as if it is a JavaScript file.

However, this does not work if `no_ext` is imported. Suppose we have a file `import_no_ext.ts`:
```ts
import "./no_ext";
```
Running `deno import_no_ext.ts` would instead crash with error:
```
Uncaught Error: Debug Failure. File /Users/kevinqian/Desktop/Programming/Deno/test/no_ext has unknown extension.
    at fail (deno/third_party/node_modules/typescript/lib/typescript.js:1462:23)
    at extensionFromPath (deno/third_party/node_modules/typescript/lib/typescript.js:15845:48)
    at deno/third_party/node_modules/typescript/lib/typescript.js:20696:30
    at resolveModuleNamesWorker (deno/third_party/node_modules/typescript/lib/typescript.js:20688:69)
    at resolveModuleNamesReusingOldState (deno/third_party/node_modules/typescript/lib/typescript.js:20909:20)
    at processImportedModules (deno/third_party/node_modules/typescript/lib/typescript.js:22242:29)
    at findSourceFile (deno/third_party/node_modules/typescript/lib/typescript.js:22050:47)
    at deno/third_party/node_modules/typescript/lib/typescript.js:21903:75
    at getSourceFileFromReferenceWorker (deno/third_party/node_modules/typescript/lib/typescript.js:21876:34)
    at processSourceFile (deno/third_party/node_modules/typescript/lib/typescript.js:21903:75)
```

One thing to note is that `codeFetch` does successfully grab `MediaType.JavaScript` correctly for `no_ext`. This error is emitted somewhere inside of the TS compiler that our current compiler instance code does not control.

/to @kitsonk

**Comment by kevinkassimo** [comment]
Cause:
See https://github.com/Microsoft/TypeScript/blob/26e546aeaadf30cbd6cd42a3c55f718b3f337a8c/src/compiler/program.ts#L762-L772

```
if (!resolved || (resolved as ResolvedModuleFull).extension !== undefined) {
  return resolved as ResolvedModuleFull;
}
const withExtension = clone(resolved) as ResolvedModuleFull;
withExtension.extension = extensionFromPath(resolved.resolvedFileName);
```
If we don't provide `.extension` in `ModuleMetaData`, TS compiler would try to resolve and crash with the above error.

**Comment by kevinkassimo** [comment]
It's due to Rollup config problem:
```ts
[typescriptPath]: [
            "createLanguageService",
            "formatDiagnostics",
            "formatDiagnosticsWithColorAndContext",
            "ModuleKind",
            "ScriptKind",
            "ScriptSnapshot",
            "ScriptTarget",
            "Extension", // Need to add this
            "version"
          ]
```
There is still one more problem related to this that I am investigating...

**Comment by kitsonk** [comment]
That explains a few things. Good catch.

**Comment by kevinkassimo** [comment]
@kitsonk After this fix there is another problem. The error message now becomes
```
Uncaught Error: Could not find file: '/Users/kevinqian/Desktop/Programming/Deno/test/no_ext'.
    at getValidSourceFile (deno/third_party/node_modules/typescript/lib/typescript.js:32750:71)
    at getEmitOutput (deno/third_party/node_modules/typescript/lib/typescript.js:32750:71)
    at compile (deno/js/compiler.ts:331:30)
    at window$2.onmessage (deno/js/compiler.ts:538:37)
    at workerMain (deno/js/workers.ts:68:14)
```
From debug output I found
```
DEBUG TS - getScriptSnapshot() /Users/kevinqian/Desktop/Programming/Deno/test/no_ext.ts
DEBUG TS - getScriptSnapshot() /Users/kevinqian/Desktop/Programming/Deno/test/no_ext.tsx
DEBUG TS - getScriptSnapshot() /Users/kevinqian/Desktop/Programming/Deno/test/no_ext.d.ts
DEBUG TS - getScriptSnapshot() /Users/kevinqian/Desktop/Programming/Deno/test/no_ext.js
DEBUG TS - getScriptSnapshot() /Users/kevinqian/Desktop/Programming/Deno/test/no_ext.jsx
```
Looks like the compiler for some reason is trying out all the extensions blindly. Investigating.

**Comment by kitsonk** [comment]
@kevinkassimo it isn't the Deno compiler, it is TypeScript.  I thought it was still an issue, the same as #1226, but @bartlomieju said it wasn't occurring anymore.  I think that might be because the initial modules name isn't being resolved by TypeScript, it is only modules that are imported, and TypeScript doesn't like modules without extensions.

I think the only fix is to make sure module meta data cache uses a filename with an extension in the map: https://github.com/denoland/deno/blob/master/js/compiler.ts#L281, we might have to have a dual entry, one with the "real" filename and one with the proper extension added.

**Comment by kevinkassimo** [comment]
@kitsonk It's confirmed in #1779 that it could be fixed by using the option `allowNonTsExtensions`
