### ISSUE TITLE
Return floating point number from performance.now()

### ISSUE THREAD

**Issue by luvies** [denoland/deno#1777]
(Following from #1630) Currently `performance.now()` returns an integer in milliseconds, however the [spec](https://developer.mozilla.org/en-US/docs/Web/API/DOMHighResTimeStamp) says that we need to return a double that is precise to around 5µ (microseconds).

We need to consider the security that browsers currently enforce to mitigate things like spectre (mentioned [here](https://developer.mozilla.org/en-US/docs/Web/API/Performance/now)). There is also discussion on providing a flag to deno that disables this security feature in favour of higher-precision benchmarks (something akin to `--allow-high-precision`). This would mostly line up with browser behaviour, since Firefox supports disabling the rounding via preferences.

**Comment by zekth** [comment]
As i mentionned in #1871 we could use nanoseconds in hrtime but in the case you describe we can polyfill it in the browser side, still returning nanoseconds but not precise and prompting a warning in the console?

Also adding an argument to disable the polyfill could be nice.

**Comment by hayd** [comment]
I think you want to return (rounded unless --allow-high-precision) int64 nanos in the op. Then performance.now() and hrtime etc. both use this. As you suggest, `Instant` seems good approach.

**Comment by zekth** [comment]
Does something like this is ok for you guys?
https://github.com/zekth/deno/blob/high_precision/src/ops.rs#L201

**Comment by hayd** [comment]
@zekth I think Instant is going to be higher precision that system time? I _think_ that means the start Instant is going to be needed on IsolateState.

**Comment by zekth** [comment]
Right, forgot to change from `SystemTime::now()` to `Instant::now()` (and i'm the one who purposed it haha)

You mean adding start property to the `IsolateState` struct and instanciate it with `instant::now()`? To avoid using `UNIX_EPOCH`? Seems legit.

About the round and the permissions is it ok?

**Comment by hayd** [comment]
I think it should link to https://developer.mozilla.org/en-US/docs/Web/API/DOMHighResTimeStamp#Reduced_time_precision 

otherwise all that you say sounds good.

**Comment by zekth** [comment]
doing polishing, ensuring everything is fine and will PR.

**Comment by zekth** [comment]
@hayd could you implement it (based on what we discussed) if it's needed for other tasks? I have issues with my env ATM.

**Comment by hayd** [comment]
Do up have a wip branch/commit?
I can do but likely not this week.

**Comment by zekth** [comment]
I have started something here: https://github.com/zekth/deno/tree/high_precision But have to clean a bit. You get the whole idea there in fact. Will clean it tonight.
