### ISSUE TITLE
Deno.makeTemp* do not appear to be checking for file existence

### ISSUE THREAD

**Issue by cscheid** [denoland/deno#17781]
I've run this on Deno 1.28.2, but it doesn't look like it's a recent regression from a cursory look at`git log` and `git blame`. Simple repro:

```
$ mkdir out
$ cat repro.ts
while (true) { console.log(Deno.makeTempFileSync({dir: "out"})); }
$ deno run --allow-all repro.ts # this will generate ~100k files, beware!
...
out/017f5cd8
out/b9d7898a
out/c2c8ca65
out/ea05084a
out/1b342639
out/671325db
out/9703a9d5
out/28d6be21
error: Uncaught AlreadyExists: File exists (os error 17)
while (true) { console.log(Deno.makeTempFileSync({dir: "out"})); }
                                ^
    at Object.makeTempFileSync (deno:runtime/js/30_fs.js:88:16)
    at file:///Users/cscheid/Desktop/daily-log/2023/02/14/deno-temp-file-stress/main.ts:1:33
$ cd out
$ ls | wc
   77678   77678  699102
```

So, although `make_temp` [has code that attempts to detect AlreadyExists](https://github.com/denoland/deno/blame/main/runtime/ops/fs.rs#L1778-L1782), that code does not appear to be executing.

We have seen this actually happen in the wild at least once. It's not as rare as one would naively expect because of the birthday paradox. We saw it when generating on the order of a few thousand files in the same directory. That was particularly unlucky but the point still stands.

**Comment by sigmaSd** [comment]
There seem to be an unintended early return here https://github.com/denoland/deno/blame/main/runtime/ops/fs.rs#L1775
