### ISSUE TITLE
Will there be support for Next.js?

### ISSUE THREAD

**Issue by katsuki-yuri** [denoland/deno#17807]
As a long time next user, I was curious whether will there be an option to run nextjs on denoland after 1.30 update. I do understand that it's quite illogical to ask it from RE creators instead of framework maintainers. However, I was interested that will deno support create-x thingies, so we can bootstrap npm create-apps via deno or it's not planned yet?

**Comment by bartlomieju** [comment]
Yes, Next.js support is planned as part of [Q1 roadmap](https://github.com/denoland/deno/issues/17475), we are actively working on adding support for it (eg. https://github.com/denoland/deno/pull/17806).

Please follow the Q1 roadmap issue for updates.

**Comment by katsuki-yuri** [comment]
Thank you for your kind answer. Really appreciated! 🙏🏻☺️
