### ISSUE TITLE
Rewrite some of JavaScript API in "ext/node" to Rust

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#17809]
An example PR that shows how it can be done: https://github.com/denoland/deno/pull/17792

TODO:

- [ ] ext/node/polyfills/internal/buffer.mjs (https://github.com/denoland/deno/pull/17815)
- [x] ext/node/polyfills/zlib.js (@littledivy) https://github.com/denoland/deno/pull/18291
- [x] ext/node/polyfills/url.ts (this should be using the web standard `URL` implementation  - slight incompatibilities are OK ) (@crowlKats) (https://github.com/denoland/deno/pull/17817)
- [ ] <s>ext/node/polyfills/path https://github.com/denoland/deno/issues/17976</s>
- [x] ext/node/polyfills/internal/util/inspect.mjs https://github.com/denoland/deno/pull/17960
- [x] ext/node/polyfills/_crypto/crypto_browserify/ )(@littledivy)

**Comment by kt3k** [comment]
I don't think we need to replace `crypto-browserify` file by file basis. What we use from `crypto-browserify` is mainly the 4 APIs `publicEncrypt` `publicDecrypt` `privateEndrypt` `privateDecrypt`, but `crypto-browserify` includes way more than that. I think we can implement these 4 APIs more directly by using some convenient crates from crates.io

**Comment by bartlomieju** [comment]
Sounds good, thanks for investigating @kt3k!

**Comment by iuioiua** [comment]
I want to implement `crypto.Sign` and `crypto.Verify` based on the work done in denoland/deno_std#3190. However, it'd require bringing back some [`browserify-sign`](https://github.com/crypto-browserify/browserify-sign) code deleted in #17792. Is that ok?

**Comment by kt3k** [comment]
@Antonio476587 
We are planning to replace `util.inspect` (of Node) by `Deno.inspect` first because they contain too much similar code (ref https://github.com/denoland/deno/pull/17960). So it's not good time to do that now. (When that transition is finished, maybe it's worth it to rewrite `Deno.inspect` in Rust in the future)

**Comment by bartlomieju** [comment]
@iuioiua it would be preferable to use a Rust crate to implement required APIs via ops. Since we already supported most of the required algorithms it seems it's not necessary to bring `browserify-sign` to implement it. @littledivy could you provide some pointers here?

**Comment by ry** [comment]
Most of these issues are solved now. We'll open a new one if necessary.
