### ISSUE TITLE
The `--inspect-brk` flag of `deno run` is order-dependent, and fails silently with the wrong order

### ISSUE THREAD

**Issue by PoignardAzur** [denoland/deno#17812]
When trying deno, at one point I tried to run the debugger with this command:

```sh
deno run my_script.ts --inspect-brk
```

That command didn't start a debugger session, which I found odd since I had managed to make it work earlier. It turns out that this flag is order-dependent, and must be specified *before* the source file:

```sh
deno run --inspect-brk my_script.ts    # Now it works!
```

I'm not sure if this is a bug or intended behavior. I suspect bug.

If it's intended, some problems:

- The `basics/debugging_your_code` tutorial doesn't mention that the argument is order-dependent.
- With a command like the above, where you end up issuing an "empty" `--inspect-brk`, the runtime could at least issue a warning that the user is likely passing the arguments incorrectly.

**Comment by GJZwiers** [comment]
It is intentional and described in [the getting started chapter](https://deno.land/manual@v1.30.3/getting_started/command_line_interface#script-arguments). All the runtime flags should go before the script argument, anything after is considered a script argument.
