### ISSUE TITLE
[BUG] lsp dts importmap

### ISSUE THREAD

**Issue by loynoir** [denoland/deno#17829]
### Brief
~~Within importmap context, dts should resolve to dts of target file, instead of dts of source file.~~

Edit: Not sure what happend, but I guess it's dts problem on lsp side.

### Reproduce
import_map.json

```json
{
  "imports": {
    "comment-json": "npm:comment-json@4.2.3",
    "fs/promises": "https://deno.land/std@0.177.0/node/fs/promises.ts",
    "node:fs/promises": "https://deno.land/std@0.177.0/node/fs/promises.ts"
  }
}
```

### Actual
Within vscode, below code type error on importId `comment-json`
```ts
import { parse, stringify } from 'comment-json'
console.log({ parse, stringify })
import { readFile, writeFile } from 'node:fs/promises'
console.log({ readFile, writeFile })
```

```txt
Resolved Dependency

Code: npm​:comment-json​@4.2.3

Uncached or missing npm package: "comment-json@4.2.3".deno(no-cache-npm)
```

`denoland.vscode-deno` deno language server log have many repeated same error, `@types/node` not found
```txt
Could not set npm package requirements.  \
Error getting response at https://registry.npmjs.org/@types/node: \
An npm specifier not found in cache: "@types/node", --cached-only is specified.
```

### Expected
Within vscode, below code types are OK
```ts
import { parse, stringify } from 'comment-json'
console.log({ parse, stringify })
import { readFile, writeFile } from 'node:fs/promises'
console.log({ readFile, writeFile })
```

### Workaround

Within vscode, below code types are OK
```ts
import { parse, stringify } from 'comment-json'
console.log({ parse, stringify })
import { readFile, writeFile } from 'fs/promises'
console.log({ readFile, writeFile })
```

### Edit
Above workaround, offen works, sometimes still got type error on `comment-json`

**Comment by bartlomieju** [comment]
Run `Cache dependencies` from the command pallete and the error should go away.

**Comment by loynoir** [comment]
@bartlomieju  I cache them, and lsp don't work, then I open the issue.

**Comment by loynoir** [comment]
The errors are gone.
