### ISSUE TITLE
`Deno.FsFile#readable` example code is broken

### ISSUE THREAD

**Issue by xBZZZZ** [denoland/deno#17828]
https://deno.land/api@v1.30.3?s=Deno.FsFile#prop_readable:<blockquote cite="https://deno.land/api@v1.30.3?s=Deno.FsFile#prop_readable"><p>A <a href="https://deno.land/api?s=ReadableStream"><code>ReadableStream</code></a> instance representing to the byte contents of the file. This makes it easy to interoperate with other web streams based APIs.</p><pre lang="javascript">const file = await Deno.open("my_file.txt", { read: true });&#10;const decoder = new TextDecoder();&#10;for await (const chunk of file.readable) {&#10;  console.log(decoder.decode(chunk));&#10;}&#10;file.close();</pre></blockquote><hr/>I have this shell script:<pre lang="sh">cd /tmp&#10;echo -n 'test data' > my_file.txt&#10;deno eval 'const file = await Deno.open("my_file.txt", { read: true });&#10;const decoder = new TextDecoder();&#10;for await (const chunk of file.readable) {&#10;  console.log(decoder.decode(chunk));&#10;}&#10;file.close();'</pre>I run it:<pre>test data&#10;error: Uncaught (in promise) BadResource: Bad resource ID&#10;file.close();&#10;     ^&#10;    at Object.close (internal:core/01_core.js:387:25)&#10;    at FsFile.close (internal:runtime/js/40_files.js:138:12)&#10;    at file:///tmp/$deno$eval.js:6:6</pre>It read data from <code>my_file.txt</code> correctly but errored closing file.

**Comment by kamilogorek** [comment]
@crowlKats what should be the behavior here? Currently the cause of such behavior is that `FsFile.readable` is implemented using `readableStreamForRid`, which has `autoClose = true` as the default, thus the `rid` is already gone once whole stream is drained, making `file.close()` trying to remove `rid=3` for the second time.

**Comment by zombiezen** [comment]
This makes it pretty difficult to use a `Deno.FsFile` for multiple operations. For example, if you want to read in a file, process its contents, and write it back out with a single file descriptor. The workaround I came up with was to use `readableStreamFromReader` and no-op the `close` method:

```typescript
import { readableStreamFromReader } from "https://deno.land/std@0.179.0/streams/mod.ts";

function nopCloser(r: Deno.Reader): Deno.Reader & Deno.Closer {
  return {
    read(p) { return r.read(p); },
    close() {},
  };
}

const f = await Deno.open("file.txt", { read: true });
const stream = readableStreamFromReader(nopCloser(f));
```

**Comment by crowlKats** [comment]
> @crowlKats what should be the behavior here? Currently the cause of such behavior is that `FsFile.readable` is implemented using `readableStreamForRid`, which has `autoClose = true` as the default, thus the `rid` is already gone once whole stream is drained, making `file.close()` trying to remove `rid=3` for the second time.

The call to file.close() should be removed

**Comment by crowlKats** [comment]
> For example, if you want to read in a file, process its contents, and write it back out with a single file descriptor

If you use web streams' piping capabilities, you can disable autoclose.

**Comment by zombiezen** [comment]
I couldn't figure out how to do that from docs. Can you provide an example?

**Comment by crowlKats** [comment]
I guess something like this should work:
```ts
const file = await Deno.open("./foo.txt");

file.readable.pipeThrough(new TransformStream({
	transform(chunk, controller) {
		// Do something with the chunks
	}
}), { preventClose: true }).pipeTo(file.writable);
```

**Comment by zombiezen** [comment]
I don't believe so. From the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream/pipeThrough) for `preventClose`:

> If this is set to true, the source ReadableStream closing will no longer cause the destination WritableStream to be closed. The method will return a fulfilled promise once this process completes, unless an error is encountered while closing the destination, in which case it will be rejected with that error.

Here is a Deno program running under Deno 1.31.1 that tries that:

```typescript
const lowerAPoint = 'a'.codePointAt(0)!;
const upperAPoint = 'A'.codePointAt(0)!;

const f = await Deno.open(Deno.args[0], { read: true });
f.readable.pipeThrough(new TransformStream({
  transform(chunk, controller) {
    for (let i = 0; i < chunk.length; i++) {
      const c = String.fromCodePoint(chunk[i]);
      if ('a' <= c && c <= 'z') {
        chunk[i] = (chunk[i] - lowerAPoint + 13) % 26 + lowerAPoint;
      } else if ('A' <= c && c <= 'Z') {
        chunk[i] = (chunk[i] - upperAPoint + 13) % 26 + upperAPoint;
      }
    }
    controller.enqueue(chunk);
  }
}), { preventClose: true }).pipeTo(f.writable);
```

But that aside, the problem that as @kamilogorek says, it is the act of reading to the end of the stream that closes the file descriptor, which is pretty unexpected IMO. Even if you proxy the `f.readable` stream so that cancel is never called, hitting EOF will close the file descriptor.

**Comment by ayame113** [comment]
My understanding is that there should be a concept like cursor (file pointer) inside Deno.FsFile.
- Reading a file with `ReadableStream` moves the file pointer by the amount read.
- When writing a file with `WritableStream`, write from the current file pointer position.
- You can use the `f.seek()` method to advance the file pointer position or get the current file pointer position.

If you write while reading one file, I think you need to advance and reverse the position of the file pointer to write to the correct location. This is probably difficult inside an asynchronous process.

I hope for your reference.

**Comment by zombiezen** [comment]
I understand that reading moves the cursor, but the surprising behavior here is that reading using the stream interface closes the file if you read all the way to EOF, thus leading to the close failing in the original post. IMO this is a bug.

**Comment by ayame113** [comment]
I think there are two main problems with this issue.

According to https://github.com/denoland/deno/issues/15442, it seems to be an intentional behavior that the stream is closed when it reaches EOF. (I think it's debatable whether the second call to close() throws or not.)

Apart from that, `file.readable.pipeThrough(...).pipe(file.writable)` fails because of the file pointer issue I mentioned.<br>
If we change the write destination from `f.writable` to `stdout.writable`, we can see that `{ preventClose: true }` works correctly.

```ts
const f = await Deno.open(new URL(import.meta.resolve("./tmp.txt")));

await f.readable
  .pipeThrough(new TransformStream())
  .pipeTo(Deno.stdout.writable, { preventClose: true });
```
