### ISSUE TITLE
REPL tab completion is enumerating all indices of an array

### ISSUE THREAD

**Issue by milaz** [denoland/deno#17831]
```
> let a = new Array(1024).fill(1)
undefined
> a.<Tab>
Display all 1072 possibilities? (y or n)
0                     358                   716
1                     359                   717
<...>
--More--
```

I believe, there is no point in tab-completing any of the numerical indices in arrays.
Should they be excluded from the completion suggestions?

**Comment by RuyiLi** [comment]
IMO they should be excluded. The useful completion suggestions (i.e. fields, methods) are being hidden and elements aren't accessible using the indices directly through dot notation anyways (by which I mean something like `a.0`, not `a.at(0)`). Also lags a lot for large arrays. 

I'd like to give this a shot, unless someone else is already working on it? 🙂
