### ISSUE TITLE
`URLPattern` pattern matching regression

### ISSUE THREAD

**Issue by gothammm** [denoland/deno#17845]
Partial pathname pattern match does not seem to work as expected.

**Deno version**: 1.30.3

**Doc Reference**: https://deno.land/api@v1.30.3?s=URLPattern
**From the doc (expected behavior):**
```
// Specify the pattern as structured data.
const pattern = new URLPattern({ pathname: "/users/:user" });
const match = pattern.exec("/users/joe");
console.log(match.pathname.groups.user); // joe
```

**Actual behavior**:

Returns `null` on `pattern.exec("/users/joe");` call.

![image](https://user-images.githubusercontent.com/2852392/220326476-294f2119-7f7d-44ca-afc1-280ca022259a.png)

**Comment by kamilogorek** [comment]
This is a docs issue, implementation is correct - https://wicg.github.io/urlpattern/
`URLPattern` can accept two different inputs for it's constructor, `exec` and `test` methods.
Either `URLPattern` itself, or URL string. When URL is provided, it can be in form of relative URL (like you do here), which then requires an additional `BaseURL` as the 2nd argument, or it needs to be a fully qualified absolute URL.

Either of those will work:

```
const pattern = new URLPattern({ pathname: "/users/:user" });
console.log(pattern.exec("http://example.com/users/joe"));
console.log(pattern.exec("/users/joe", "http://example.com"));
console.log(pattern.exec({ pathname: "/users/joe" }));
```

**Comment by gothammm** [comment]
@kamilogorek Ah gotcha, thank you very much for the clarification.
