### ISSUE TITLE
Deno ignoring `fmt` options for formatting in vscode

### ISSUE THREAD

**Issue by nikitavoloboev** [denoland/deno#17873]
my deno project: https://github.com/nikitavoloboev/ts/tree/main/deno
with deno.json: https://github.com/nikitavoloboev/ts/blob/main/deno/deno.json

when I press save on this file in my vscode: https://github.com/nikitavoloboev/ts/blob/main/deno/run.ts

no semicolons get removed but they should be as I specified:

```
 "fmt": {
    "options": {
      "semiColons": false
    }
  }
```

I am running latest deno version: 

```
deno --version
deno 1.30.3 (release, aarch64-apple-darwin)
v8 10.9.194.5
typescript 4.9.4
```

also deno is enabled in vscode as can be seen here:

https://github.com/nikitavoloboev/ts/blob/main/deno/.vscode/settings.json

I first asked on Discord but received no reply to fix this, not sure what I am doing wrong, perhaps its bug with deno.

**Comment by dsherret** [comment]
In vscode, what formatter settings do you have? If you hit the `F1` key then select "Format document with..." then select "Deno", does it then work? If so, then you probably have to update your formating settings. See this section on "Formatting": https://github.com/denoland/vscode_deno#formatting

**Comment by nikitavoloboev** [comment]
> In vscode, what formatter settings do you have?

I went to my global vscode settings and found this line:

```
  "[typescriptreact]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
```

I deleted it and pressed save on `run.ts` file again but no semicolon was changed.

The thing though is that my .vscode for `deno` says formatter should be deno.

<img width="589" alt="image" src="https://user-images.githubusercontent.com/6391776/220707330-74764d32-fe1c-46ef-a880-c15ac23b0425.png">

**Comment by dsherret** [comment]
Hmmm... that's strange. I just tried it out and it works for me. In the bottom of the vscode window does it say "1.30.3". Also, if you go to "View -> Output" and in the output window's dropdown select "Deno Language Server", do you see any errors?

**Comment by nikitavoloboev** [comment]
Ok thanks for that. I had activity bar hidden, enabling I saw `prettier` was being the formatter still. Even though I had this in .vscode/settings.json locally

<img width="553" alt="image" src="https://user-images.githubusercontent.com/6391776/220711217-c90a16a6-9a34-44c2-bc4c-db2bdb73cfa2.png">

I went to global vscode settings of mine and found and deleted this line:

```
  "[typescript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  ```
  
  Now things work.

**Comment by nikitavoloboev** [comment]
I am surprised that this did not apply:

```
  "editor.defaultFormatter": "denoland.vscode-deno",
 ```

Probably bug with vscode itself?

**Comment by dsherret** [comment]
Cool. I think it used that setting because it was specific for typescript. Probably to override the global setting you would need to do something in the local .vscode file as well (with `"[typescript]"`).

**Comment by nikitavoloboev** [comment]
Worked perfectly. Thank you.
