### ISSUE TITLE
Build process requires openssl@1.1

### ISSUE THREAD

**Issue by djKooks** [denoland/deno#1787]
Hello,

This is an issue while debugging on #1399 , working on `./tools/build.py`:
```
...
dyld: Library not loaded: /usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib
  Referenced from: /Users/jung/workspace/etc/deno/prebuilt/mac/sccache
  Reason: image not found
```
Current build process forces to use openssl 1.1 version, and I couldn't figure out why.
I think there should be a guide about installing `openssl v1.1` if deno must use this version.

Thanks.

**Comment by manyuanrong** [comment]
There are already hints on the manual document that additional openssl v1.1 installation may be required in the Mac environment.

**Comment by hayd** [comment]
Potentially, #1474 would address this too - by allowing users to use system sccache.
