### ISSUE TITLE
Bug: Deno.serveHttp doesn't correctly hook up abort signal

### ISSUE THREAD

**Issue by Skn0tt** [denoland/deno#17919]
From my understanding of `Request.signal`, this test should pass:

```ts
import { assert } from "https://deno.land/std@0.178.0/testing/asserts.ts";
import { serve } from "https://deno.land/std@0.178.0/http/server.ts";

const sleep = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));

Deno.test("AbortSignal", async () => {
  let requestReceivedAbortSignal = false;
  serve((req) =>
    new Promise<Response>(() => { // promise that never resolves
      req.signal.onabort = () => {
        requestReceivedAbortSignal = true;
      };
    }), {
    port: 5678,
  });

  const requestController = new AbortController();
  fetch("http://localhost:5678", {
    signal: requestController.signal,
  });

  // give the request time to be received
  await sleep(100);

  // we don't need it anymore
  requestController.abort();

  // the server should be notified that it doesn't need to continue working
  assert(requestReceivedAbortSignal);
});
```

It fails, and from a quick look through the codebase I'm assuming it's because in `Deno.serveHttp`, a signal is added onto the request, but it's never hooked into the underlying request cycle:

https://github.com/denoland/deno/blob/b6ac54815c1bcfa44a45b3f2c1c982829482477f/ext/http/01_http.js#L138-L144

**Comment by bartlomieju** [comment]
Hey @Skn0tt we're looking to fix this problem, though I'm not sure what's the desired behavior here? Since the response promise never resolves then the `fetch` would be stuck as well. Should we just automatically reject the response promise when request is aborted?

**Comment by Skn0tt** [comment]
Thanks for looking into it! I'm unsure what the desired behaviour of `fetch` should be, my point is that `req.signal` (in the `serve` call) isn't aborted when the `fetch` call is aborted.

**Comment by Skn0tt** [comment]
For `fetch`, the spec's behaviour is that the `fetch` promise should be rejected once it's aborted: https://fetch.spec.whatwg.org/#fetch-method, 11.

**Comment by mmastrac** [comment]
This is fixed in Deno.serve in https://github.com/denoland/deno/pull/23425, but will not be fixed in Deno.serveHttp until we fully deprecate that code -- it will end up being implemented on Deno.serve internally. We recommend migrating to the new API.

Closing this issue as the API is deprecated but we have a replacement. Please let us know if that newer API works for you.
