### ISSUE TITLE
Add option to skip package.json auto discovery

### ISSUE THREAD

**Issue by cyco130** [denoland/deno#17916]
I use Deno in the CI of some of my projects, using the pnpm monorepo system. They all started failing because Deno now discovers the `package.json` file and tries to parse it and fails on `workspace:` specifiers. Adding `--no-npm` doesn't help.

- Is it possible to skip `package.json` discovery when `--no-npm` is specified?
- If not, is it possible to add a new option for it?
- If not, is it possible for Deno to just ignore unknown specifier syntax unless it has to use that dependency?

**Comment by MKRhere** [comment]
Node-compat mode should be opt-in imo; Deno assuming it's supposed to run in Node projects by default breaks a lot of existing workflows for no tangible benefit.

**Comment by dsherret** [comment]
Thanks for this feedback. We're going to release a patch release (1.31.1) this weekend that addresses a few things:

1. In 1.30.0, the "npm install" is being done if a package.json was auto-discovered. This is too greedy. We're going to instead lazily do this only if a requested package matches what's found in the package.json file. This should solve most issues people are having.
2. When using either `--no-config` or `--no-npm` it won't auto-discover the package.json.
3. Setting `DENO_NO_PACKAGE_JSON=1` will auto-disable package.json completely. If you don't want this feature at all then you can set that.
4. "workspace:" specifiers will be skipped for now.

**Comment by barbados-clemens** [comment]
Apart of the auto discovery/ignoring specifiers, could deno also ignore file: specififers in the package.json as well for deno v1.30.1?

Current have [CI erroring out](https://github.com/nrwl/nx-labs/actions/runs/4265972598/jobs/7426783227) testing some integrations [we are building with Deno + Nx ](https://github.com/nrwl/nx-labs/tree/main/packages/deno)

as the project is written with node and Deno is wanting to read the package.json for our e2e suite. 

```shell
error: Parsing version constraints in the application-level package.json is more strict at the moment
Caused by:
    Invalid npm specifier version requirement. Unexpected character.
      file:/Users/caleb/Work/nrwl/nx-labs/dist/packages/deno
```

**Comment by dsherret** [comment]
@barbados-clemens I opened https://github.com/denoland/deno/pull/17938

**Comment by barbados-clemens** [comment]
thank you so much @dsherret! 🎉

**Comment by dsherret** [comment]
Please upgrade to 1.31.1. The situation will be much better now as described in https://github.com/denoland/deno/issues/17916#issuecomment-1444647248

**Comment by ChuckJonas** [comment]
How do you deal with this in vscode?  There doesn't seem to be any user setting to disable `package.json`

**Comment by dsherret** [comment]
@ChuckJonas can you open an issue for exactly what scenario you’re encountering and why there needs to be a setting to disable it? As of the latest patch, it should be very lazy at loading it so it’s not clear that it needs to be configurable.

**Comment by sergeysolovev** [comment]
@dsherret 

>In 1.30.0, the "npm install" is being done if a package.json was auto-discovered. This is too greedy. We're going to instead lazily do this only if a requested package matches what's found in the package.json file. This should solve most issues people are having.

Running a script which simply prints “Hello” makes deno installing all dependencies from package.json workspaces (nested packages) which is quite unexpected.

```
$ deno --version
deno 1.32.5 (release, aarch64-apple-darwin)
v8 11.2.214.9
typescript 5.0.3

$ cat hello.js
console.log('hello');

$ deno run hello.js
hello
```

It would be also nice to have some way to disable package.json altogether with some parameter in deno.json. The env variable `DENO_NO_PACKAGE_JSON` is better than nothing but I have to set it everywhere.

**Comment by dsherret** [comment]
@sergeysolovev can you open a bug that reproduces that problem? It shouldn’t be doing that. Maybe you have a lockfile (deno.lock) that’s autodiscovered and has npm packages in it.

**Comment by sergeysolovev** [comment]
@dsherret Yes I have deno.lock with npm deps in it. What do you mean by “initializing from the lockfile”?

**Comment by dsherret** [comment]
@sergeysolovev when the lockfile has npm dependencies in it and it's auto-discovered, then the internal npm resolution state will be initialized from it eagerly. We should try to reduce the scenarios this happens (I opened #18801), but I believe it's a separate issue from this package.json auto-discovery because it shouldn't be doing that in this case. You can use `--no-lock` in your scenario to not auto-discover the lockfile.

**Comment by sergeysolovev** [comment]
@dsherret I’ve made a minimal repro here: https://github.com/sergeysolovev/deno-package-json-repro

All that you say makes sense, but to me dumping the deps to node_modules folder just because they are in deno.lock – is unexpected side-effect. 

1) The script `hello.js` just prints to stdout, why running it should affect the file system?
2) Yes I have package.json there, but it doesn’t have dependencies which end up in node_modules.

**Comment by sergeysolovev** [comment]
@dsherret Also the fact that I have package.json in the same folder with deno code doesn’t mean that I expect deno to make any changes to `node_modules` unless or until I explicitly say so. I think it’s not uncommon to have both deno and node in the same folder during partial migration or for some other reason.

**Comment by dsherret** [comment]
@sergeysolovev

* `--node-modules-dir=false` disables this
* https://github.com/denoland/deno/issues/17930 will disable it via the config file in the future 


> The script hello.js just prints to stdout, why running it should affect the file system?

Again, see https://github.com/denoland/deno/issues/18801

**Comment by sergeysolovev** [comment]
@dsherret Thank you, appreciate that! For now I set `DENO_NO_PACKAGE_JSON=1` in my bash profile dot-file.

**Comment by bodograumann** [comment]
Is there a way to set `DENO_NO_PACKAGE_JSON=1` or an equivalent option in `deno.jsonc`? Currently I have to add it to all my tasks.

**Comment by jsejcksn** [comment]
> Is there a way to set `DENO_NO_PACKAGE_JSON=1` or an equivalent option in `deno.jsonc`? Currently I have to add it to all my tasks.

@bodograumann Environment variables aren't currently included in the [configuration file schema](https://deno.land/x/deno/cli/schemas/config-file.v1.json), but you can configure environment variables in a file (e.g. `.env`) and load them using the `--env-file` CLI argument in your tasks (e.g. `deno run --env-file=.env entrypoint.ts`) — see documentation for more info: [permalink](https://github.com/denoland/docs/blob/4c157384017bd16bbeaea5bc74f24cdf02551676/runtime/manual/basics/env_variables.md).

<details>

<summary>From the CLI help:</summary>

```txt
% deno help run
--- snip ---
Options:
--- snip ---
      --env-file[=<FILE>]         Load environment variables from local file
                                    Only the first environment variable with a given key is used.
                                    Existing process environment variables are not overwritten.
--- snip ---
```

```txt
% deno --version
deno 1.46.2 (stable, release, aarch64-apple-darwin)
v8 12.9.202.5-rusty
typescript 5.5.2
```

</details>

**Comment by balupton** [comment]
> Please upgrade to 1.31.1 (now released). The situation will be much better now as described in [#17916 (comment)](https://github.com/denoland/deno/issues/17916#issuecomment-1444647248)

What exactly was the fix to prevent Deno from looking for package.json, was it specifying the `--no-npm` flag?

**Comment by jsejcksn** [comment]
> What exactly was the fix to prevent Deno from looking for package.json, was it specifying the `--no-npm` flag?

@balupton There's an environment variable [`DENO_NO_PACKAGE_JSON`](https://docs.deno.com/go/env-vars#:~:text=DENO_NO_PACKAGE_JSON) which is described this way:

> Disables auto-resolution of `package.json`

You can set its value to `1` to enable it. (Perhaps it's slightly confusing to enable an option to disable another option 😅) In the case of the code you showed:

```sh
DENO_NO_PACKAGE_JSON=1 deno run --quiet ...
```
