### ISSUE TITLE
Deno 1.31.0 fails to compile on GH actions

### ISSUE THREAD

**Issue by brianleroux** [denoland/deno#17925]
been working for along time so this was a surprising error; hoping there's a simple fix!

this is the failing command:

```
git clone -b v1.31.0 --recurse-submodules https://github.com/denoland/deno.git
[3](https://github.com/beginner-corp/begin-deno-runtime/actions/runs/4263798655/jobs/7421351710#step:7:3)
  cd deno
[4](https://github.com/beginner-corp/begin-deno-runtime/actions/runs/4263798655/jobs/7421351710#step:7:4)
  cargo build --release
```

you can see all the output herein:

https://github.com/beginner-corp/begin-deno-runtime/actions/runs/4263798655/jobs/7421351710

**Comment by brianleroux** [comment]
FYI same issue in `v1.31.3`

https://github.com/beginner-corp/begin-deno-runtime/actions/runs/4669908505/jobs/8268975694

**Comment by bartlomieju** [comment]
Does the issue persist on 1.32.x versions?

**Comment by brianleroux** [comment]
Same issue on 1.35

https://github.com/beginner-corp/begin-deno-runtime/actions/runs/5483606768/jobs/9990127705

**Comment by bartlomieju** [comment]
@mmastrac please take a look

**Comment by mmastrac** [comment]
Hey @brianleroux! Good to see you around here. Do you happen to know if you can upgrade `binutils` in that image?

This suggests that `binutils` is too old: `unrecognized relocation (0x2a) in section`

Alternatively, you could try `V8_FROM_SOURCE=1 cargo build` which will use your system binutils to produce a less-futuristic binary using the system `binutils` that may work.

**Comment by brianleroux** [comment]
hey @mmastrac thx for having a look! the image used in the build is the official aws thing so it not really up to me what gets included in there. I could build against a different image but that seems like a bad idea.

adding the `V8_FROM_SOURCE` did yield a new error but idk if this is helpful either

```
using Chromiums clang
[677](https://github.com/beginner-corp/begin-deno-runtime/actions/runs/5580281088/jobs/10196969083#step:7:678)
  clang_base_path /__w/begin-deno-runtime/begin-deno-runtime/deno/target/release/clang
[678](https://github.com/beginner-corp/begin-deno-runtime/actions/runs/5580281088/jobs/10196969083#step:7:679)
  Downloading https://commondatastorage.googleapis.com/chromium-browser-clang/Linux_x64/clang-llvmorg-16-init-13328-g110fe4f4-1.tar.xz .......... Done.
[679](https://github.com/beginner-corp/begin-deno-runtime/actions/runs/5580281088/jobs/10196969083#step:7:680)
  cargo:warning=Not using sccache or ccache
[680](https://github.com/beginner-corp/begin-deno-runtime/actions/runs/5580281088/jobs/10196969083#step:7:681)
  The current directory is /github/home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/v8-0.74.1
[681](https://github.com/beginner-corp/begin-deno-runtime/actions/runs/5580281088/jobs/10196969083#step:7:682)
  gn gen --root=/github/home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/v8-0.74.1 /__w/begin-deno-runtime/begin-deno-runtime/deno/target/release/gn_out
[682](https://github.com/beginner-corp/begin-deno-runtime/actions/runs/5580281088/jobs/10196969083#step:7:683)

[683](https://github.com/beginner-corp/begin-deno-runtime/actions/runs/5580281088/jobs/10196969083#step:7:684)
  --- stderr
[684](https://github.com/beginner-corp/begin-deno-runtime/actions/runs/5580281088/jobs/10196969083#step:7:685)
  /__w/begin-deno-runtime/begin-deno-runtime/deno/target/release/ninja_gn_binaries-20221218/linux-amd64/gn: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /__w/begin-deno-runtime/begin-deno-runtime/deno/target/release/ninja_gn_binaries-20221218/linux-amd64/gn)
[685](https://github.com/beginner-corp/begin-deno-runtime/actions/runs/5580281088/jobs/10196969083#step:7:686)
  thread 'main' panicked at 'assertion failed: Command::new(gn()).arg(format!(\"--root={}\",\n                                                dirs.root.display())).arg(format!(\"--script-executable={}\",\n                                            python())).arg(\"gen\").arg(&gn_out_dir).arg(\"--args=\".to_owned()\n                                +\n                                &args).stdout(Stdio::inherit()).stderr(Stdio::inherit()).envs(env::vars()).status().expect(\"Coud not run `gn`\").success()',
```

**Comment by ryanblock** [comment]
Update: I work with @brianleroux and while looking at some related stuff I dropped into this Deno / AWS Linux 2 (AL2) compile issue. I have some good news and bad news. The bad news is I couldn't get it to compile either. The good news is the pre-built `x86_64-unknown-linux-gnu` version _does work_ in AL2, so compilation is not required for us to continue maintaining the Deno Lambda layer.

Up to you whether to leave this issue open; I'd say ensuring Deno can compile in AL2 is probably a solid goal, regardless of whether Deno does currently run in AL2. 💕

**Comment by mmastrac** [comment]
I dug into this a bit more and unfortunately while we can run on the earlier glibc/bintool version envrionments, it's a pretty big struggle to actually build on them due to various constraints (mostly the pre-linked v8 library and the gn binary required to build from v8 source).

I think for now using pre-built images is ideal for now. We don't have any plans to bump the minimum glibc version in any of our builds.

**Comment by brianleroux** [comment]
works for us; we trust you. idk that everyone out there would (or should) though. aws linux is a pretty common deployment operating system !
