### ISSUE TITLE
Add option to disable `node_modules` in `deno.json`

### ISSUE THREAD

**Issue by Guerteltier** [denoland/deno#17930]
I would like to be able to disable using a `node_modules` directory in `deno.json` like this:
```diff
diff --git a/deno.json b/deno.json
index 68129410..e4305023 100644
--- a/deno.json
+++ b/deno.json
@@ -6,12 +6,16 @@
     "clean": "deno task clean:css && deno task clean:js",
     "clean:css": "rm -rf an_website/static/css",
     "clean:js": "rm -rf an_website/static/js",
-    "esbuild": "deno run -A https://deno.land/x/esbuild@v0.17.8/mod.js --log-override:unsupported-regexp=error --target=$(deno task target) --charset=utf8",
+    "esbuild": "deno run -A https://deno.land/x/esbuild@v0.17.10/mod.js --log-override:unsupported-regexp=error --target=$(deno task target) --charset=utf8",
     "find:css": "find style -type f -name '*.css'",
     "find:ts": "find an_website -type f -name '*.ts'",
     "target": "echo es$(python3 -c 'from datetime import datetime; print((now := datetime.utcnow()).year - (5 + (now.month < 7)))')",
     "watch": "deno task find:ts -exec deno task esbuild --outbase=an_website --outdir=an_website/static/js --minify --sourcemap --watch '{}' +"
   },
+  "imports": {
+    "std/": "https://deno.land/std@0.178.0/"
+  },
+  "nodeModulesDir": false,
   "lint": {
     "files": {
       "include": [
```

**Comment by Guerteltier** [comment]
(The `esbuild` and `imports` changes in the diff are unrelated to this feature request.

**Comment by dsherret** [comment]
Did you want this option because of Deno 1.31.0 and you have a package.json file? If so, please upgrade to 1.31.1 and it should no longer create a local node_modules directory unless there is a package.json and you use a bare specifier from it. Report back if you still need this option and explain why it's necessary.

**Comment by Guerteltier** [comment]
Some NPM packages cause Deno to create/modify `node_modules` even in 1.31.1.
One example is `npm:core-js-builder@3.28.0`.
I'd like to be able to completely disable it.
This is already possible with `--node-modules-dir=false`, but there is no option for it in the config file.
Also it might be a good idea to not modify existing `node_modules` directories not containing `.deno`.
```ts
#!/usr/bin/env -S deno run --no-prompt --allow-env=TEMP,TMP,TMPDIR --allow-read=.,/tmp --allow-write=.,/tmp
import builder from "npm:core-js-builder@3.28.0";

await builder({
    targets: "defaults",
    summary: {
        console: { size: true, modules: false },
        comment: { size: false, modules: true },
    },
    format: "bundle",
    filename: Deno.args[0],
});
```

**Comment by Guerteltier** [comment]
On an unrelated side note: Is it intended that this fails?
```
# deno run --node-modules-dir=false --no-prompt --allow-read=.,/tmp --allow-write=.,/tmp scripts/core-js-builder.ts
error: Uncaught PermissionDenied: Requires env access to "TMPDIR", run again with the --allow-env flag
    at Object.getEnv [as get] (internal:runtime/js/30_os.js:84:14)
    at Object.tmpdir (internal:deno_node/polyfills/os.ts:183:31)
    at Object.<anonymous> (file:///root/.cache/deno/npm/registry.npmjs.org/core-js-builder/3.28.0/index.js:10:30)
    at Object.<anonymous> (file:///root/.cache/deno/npm/registry.npmjs.org/core-js-builder/3.28.0/index.js:106:4)
    at Module._compile (internal:deno_node_loading/02_require.js:745:34)
    at Object.Module._extensions..js (internal:deno_node_loading/02_require.js:778:10)
    at Module.load (internal:deno_node_loading/02_require.js:656:32)
    at Function.Module._load (internal:deno_node_loading/02_require.js:513:12)
    at Module.require (internal:deno_node_loading/02_require.js:678:19)
    at require (internal:deno_node_loading/02_require.js:818:16)
```

**Comment by dsherret** [comment]
Yes, that's attempting to read the `TEMPDIR` environment variable, which that script hasn't been given permission to (needs `--allow-env=TMPDIR`)

**Comment by dsherret** [comment]
Ah, I see what you mean. Yes, you can use `--node-modules-dir=false` for now.

We could possibly have it so when there's a package.json it won't use the local node_modules directory until a bare specifier matches an entry in the package.json. That maybe might create some confusion or weird bugs though.

I think the ability to enable or disable this in the deno.json would be useful and would help out the LSP too (#16373).

**Comment by Guerteltier** [comment]
> Yes, that's attempting to read the `TEMPDIR` environment variable, which that script hasn't been given permission to (needs `--allow-env=TMPDIR`)

I think the `os` polyfill should behave like `process.env`:
https://github.com/denoland/deno_std/pull/3178

`TEMP`, `TMP`, and `TMPDIR` are also all unset in my case.

**Comment by dsherret** [comment]
@Guerteltier at the moment, it still needs permission to know if they're unset. Maybe that should change. That said, maybe an improvement could be made since this code is now in the Deno binary. Anyway, please open a separate issue to discuss this one as it's unrelated to this issue.

**Comment by zingmane** [comment]
I have a similar problem since upgrading deno from 1.30.3 to 1.31.1.
I'm using deno in a monorepo with following structure.

```txt
./packages
├── backend
│   ├── database
│   └── server
├── client
│   ├── node_modules
│   ├── public
│   ├── <...>
│   └── src
└── models
    ├── node_modules
    ├── <...>
    └── src
```

In order for the task distribution to work from the root level, there is also a `package.json` in each package, which in the case of the backend only refers to `deno.json`. I deactivated the new package.json support with `DENO_NO_PACKAGE_JSON` but that's not enough. When I call `deno test` a local `node_modules` dir is created, which I don't want. 
The bigger problem is that the LSP (or together with deno vscode extension) can't resolve the dependencies (`deno(no-cache-npm)`), probably because the cache dir doesn't match.
