### ISSUE TITLE
Remote modules are not allowed to import local modules defined by import maps

### ISSUE THREAD

**Issue by ije** [denoland/deno#17932]
i have a `import_map.json` like:

```json
{
  "imports": {
    "fast-deep-equal": "./deep-eq.js"
  }
}
```

then i try to import "https://esm.sh/ajv@8.12.0?external=fast-deep-equal" which includes the `import equal from "fast-deep-equal"` expr, then i got the error.

I agree that remote modules should not include `import "file:///..."` specifier for security, but i think we can allow some defined in import maps by users.

_

This happens in **Deno 1.31.0**

**Comment by ije** [comment]
thanks

**Comment by dsherret** [comment]
@ije and sorry! Just doing a patch release in a few hours.
