### ISSUE TITLE
Release script should automatically format Releases.md

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#17937]
https://github.com/denoland/deno/actions/runs/4267692370/jobs/7429560978

**Comment by yardenshoham** [comment]
I thought this already happens
https://github.com/yardenshoham/deno/blob/6728ad4203d731e555dabf89ec6157f113454ce6/tools/release/01_bump_crate_versions.ts#L55

**Comment by dsherret** [comment]
Yup. Not sure why this occurred, but I haven't seen it happen.
