### ISSUE TITLE
Terminal is unresponsive after running Vite

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#17933]
> running deno task dev in a vite project and stopping the devserver with ctrl-c the terminal does not accept keyboard input afterwards for me (manjaro linux, bash)

Reported on Discord by @dominikg

**Comment by Pronian** [comment]
I'm using Manjaro Linux with zsh and I can confirm this issue as well.

Steps to reproduce:
1. run `deno run npm:create-vite test` and when prompted accept all permissions
2. `cd test && deno task dev`
3. run  `deno run npm:create-vite test`  again, this time when prompted for permissions Ctrl-C will print in the console instead of stopping the process.

**Comment by danielgek** [comment]
Same problem here on mac m1 Ventura 13.1, can't control c to exit the process

**Comment by rgripper** [comment]
I have the same issue in WSL2 Ubuntu 22 bash

**Comment by bartlomieju** [comment]
I'm pretty sure this is the same problem as https://github.com/denoland/deno/issues/16928

**Comment by bartlomieju** [comment]
I found test cases in Node that check for this behavior:
- `test/pseudo-tty/test-set-raw-mode-reset.js`
- `test/pseudo-tty/test-set-raw-mode-reset-signal.js`
- `test/pseudo-tty/test-set-raw-mode-reset-process-exit.js`
We should match this behavior in both Node polyfills and Deno APIs.

**Comment by wryfi** [comment]
Any updates on this? #16928 seems to have been merged (and presumably released?) but I am experiencing this behavior with deno 1.37.1 on macOS 13.6, arm64, macports, bash 5.2. 

Interestingly if I switch my shell from `bash` to `zsh` the shell will continue to echo after exiting the dev server, but the `stty` configuration has still subtly changed.

bash:

```bash
> deno run -A npm:create-vite-extra vite
✔ Select a template: › deno-svelte
✔ Select a variant: › TypeScript

Scaffolding project in /Users/wryfi/tmp/deno-test/vite...

Done. Now run:

  cd vite
  deno task dev

> cd vite
> stty
speed 38400 baud;
iutf8
-iexten
> deno task dev
> # `stty` again but nothing echoes
speed 38400 baud;
min = 1; time = 0;
-brkint -icrnl iutf8
-isig -icanon -iexten -echo
```

zsh:
```zsh
> stty
speed 38400 baud;
iutf8
-iexten
> deno task dev
> stty
speed 38400 baud;
-brkint -icrnl iutf8
-isig -iexten
```

**Comment by bartlomieju** [comment]
I believe this is now fixed thanks to https://github.com/denoland/deno/pull/20892
