### ISSUE TITLE
Unable to import json

### ISSUE THREAD

**Issue by comunidadio** [denoland/deno#17942]
According to https://examples.deno.land/importing-json it should be possible to import JSON with the following snippet:

$ cat jsontest.js
```javascript
import IUniswapV3PoolABI from 'npm:@uniswap/v3-core/artifacts/contracts/interfaces/IUniswapV3Pool.sol/IUniswapV3Pool.json' assert { type: "json" }

console.log(IUniswapV3PoolABI)
```

Getting 
```
$ deno run jsontest.js 
error: Expected ';', '}' or <eof> at file:///Users/XXX/Library/Caches/deno/npm/registry.npmjs.org/@uniswap/v3-core/1.0.1/artifacts/contracts/interfaces/IUniswapV3Pool.sol/IUniswapV3Pool.json:2:12

    "_format": "hh-sol-artifact-1",
             ~
```

Same result with both deno v1.30 and v1.31.

Even double-checked the file in the deno cache (at location seen above) and it is definitely valid json.

Am I doing it wrong or it's a possible regression?

**Comment by GJZwiers** [comment]
Not sure if `npm:` specifiers support JSON imports at this time?
