### ISSUE TITLE
tokio-util version-lock preventing integration along-side updated crates

### ISSUE THREAD

**Issue by luketpeterson** [denoland/deno#17943]
Deno 1.31.1 requires exactly tokio-util version "=0.7.4", but that crate is over 5 months old and several newer versions have been released.  Integrating the deno runtime along-side newer crates that use the latest tokio-util is not possible.

I believe a semver minimum bound would be adequate in this case as the tokio team is unlikely to break compatibility in a patch release.

I have submitted this PR, awaiting approval:  https://github.com/denoland/deno/pull/17863

Thank you.

**Comment by dsherret** [comment]
tokio-util is no longer pinned and the PR is merged.
