### ISSUE TITLE
Dino extinct on Windows

### ISSUE THREAD

**Issue by MarkTiedemann** [denoland/deno#1795]
`cmd.exe` doesn't properly render the 🦕 from [welcome.js](https://github.com/denoland/deno/blob/a4dec944bc821d114bfd82debb72d60bd04f836d/website/welcome.js).

```
C:\>deno https://deno.land/welcome.js
Welcome to Deno ≡ƒªò
```

This is potentially confusing to newcomers.

**Comment by kitsonk** [comment]
cmd.exe doesn't support unicode...  In theory we should have some information in the `Deno` namespace the provides information about the support of the console it is running under and be able to then allow code to feature switch.

**Comment by ry** [comment]
Not sure about cmd.exe but I believe https://github.com/denoland/deno/pull/1485 will fix powershell.

**Comment by piscisaureus** [comment]
The windows console doesn't support emoji at the moment, although supposedly msft people are working on that.

(Note that whether you're using cmd.exe or powershell is irrelevant, much like you wouldn't say that bash/zsh does or doesn't support emoji. Displaying characters is a feature of the terminal application, not the shell.)

**Comment by isAdrisal** [comment]
The new (beta) Windows Terminal correctly displays emojis and resolves this issue (screenshot attached).

Project: [https://github.com/microsoft/terminal](https://github.com/microsoft/terminal)
Store link: [https://www.microsoft.com/en-us/p/windows-terminal-preview](https://www.microsoft.com/en-us/p/windows-terminal-preview)

![welcome ts](https://user-images.githubusercontent.com/29012873/72208340-b49c5e80-34f5-11ea-954f-272cece79381.jpg)
