### ISSUE TITLE
Deno.loadavg() aways returning 0 on Windows

### ISSUE THREAD

**Issue by lviggiani** [denoland/deno#17969]
On Windows `Deno.loadavg()` always returns 0 even if there is an actual CPU usage:

```javascript
setInterval(() => printf(`\rLoad ${Deno.loadavg()}`));
```

![image](https://user-images.githubusercontent.com/139040/221594105-17894103-d1be-43d1-b90c-4180b5cd21e6.png)

I've read on [StackOverflow](https://stackoverflow.com/q/32284440/645854) that the same issue happens on node with `os.loadavg()`
so perhaps it's the same issue?

**Comment by bartlomieju** [comment]
Yes, it the same situation as with Node.js; AFAIK there's no API available on Windows to get this data.
