### ISSUE TITLE
TLS verification for certificate with IP address not supported

### ISSUE THREAD

**Issue by Eeemil** [denoland/deno#17967]
Using [@kubernetes/client-node](https://www.npmjs.com/package/@kubernetes/client-node), connecting to clusters presenting with an IP-address is not working, even though it uses a valid certificate with a custom CA. 

The following code example 
```typescript
import * as k8s from 'npm:@kubernetes/client-node@^0.18.1';
const kc = new k8s.KubeConfig();
kc.loadFromDefault();
const k8sApi = kc.makeApiClient(k8s.CoreV1Api);
console.log(await k8sApi.listNode());
```
Produces the following error:
```
# Note: IP-adress redacted to xxx.xxx.xxx.xxx
error: Uncaught TypeError: error sending request for url (https://xxx.xxx.xxx.xxx/api/v1/nodes): error trying to connect: presented server name type wasn't supported
```

For now I've circumvented this issue by creating a custom entry in `/etc/hosts` to the IP-adress and provisioning the custom CA in a file read by `deno run --cert ...`

I believe this is a limitation in rustls tracked here: https://github.com/rustls/rustls/issues/184 and seems like it's going to be fixed in rustls 0.21.0, which is not released yet. However I thought I should create an issue in case others stumble upon the same problem.

**Comment by reedHam** [comment]
Same problem here trying to connect to Kubernetes localhost address https://127.0.0.1.

**Comment by Eeemil** [comment]
I think (not 100% sure) that I did verify at a later stage that this PR indeed did fix the issue.
I might find some time to test this again in the coming days, it should be quite straightforward.

However, the connection refused error suggests that the error is not with TLS verification
