### ISSUE TITLE
Implement node:path in Rust

### ISSUE THREAD

**Issue by ry** [denoland/deno#17976]
Currently the node:path module is implemented in JavaScript: https://github.com/denoland/deno/tree/main/ext/node/polyfills/path

We would like to implement this in Rust and reduce the amount of JavaScript. This should be done incrementally as much as possible, with benchmarks showing that the new Rust implementation out performs the previous JavaScript one. 

- [ ] join
- [ ] basename
- [ ] dirname
- [ ] extname
- [ ] delimiter
- [ ] format
- [ ] fromFileUrl
- [ ] isAbsolute
- [ ] normalize
- [ ] parse
- [ ] relative
- [ ] resolve
- [ ] sep
- [ ] toFileUrl
- [ ] toNamespacedPath

**Comment by 20k-ultra** [comment]
I'm working on porting dirname, join, and basename.

**Comment by 20k-ultra** [comment]
Would we want to do a direct port of the existing Javascript into Rust or is there enough test coverage we can use Rust std functions ?

example join -> https://doc.rust-lang.org/std/path/struct.Path.html#method.join

**Comment by Hrushi20** [comment]
I've ported the isAbsolute method.

**Comment by RyanClementsHax** [comment]
Is this still desired?

**Comment by ry** [comment]
closing this as maybe not faster
