### ISSUE TITLE
disable `package.json` auto-discovery

### ISSUE THREAD

**Issue by mfulton26** [denoland/deno#17970]
I have some Deno scripts inside an NPM project and with the latest version of `deno` they now fail. Auto-discovering `package.json` is a breaking change. Is there any way to disable?

```
error: Parsing version constraints in the application-level package.json is more strict at the moment

Caused by:
    Invalid npm specifier version requirement. Unexpected character.
      link:./eslint
      ~
```

**Comment by bartlomieju** [comment]
In v1.31.1 you can use `--no-config` to disable it (https://github.com/denoland/deno/commit/7ad64283a16cb0bfc9671ed482890d005eed9dcc) or `DENO_NO_PACKAGE_JSON=1` env var (https://github.com/denoland/deno/pull/17926).

**Comment by bartlomieju** [comment]
I'm gonna close this issue for now.
