### ISSUE TITLE
Unneeded path segments in `Deno.execPath`

### ISSUE THREAD

**Issue by kevinkassimo** [denoland/deno#1798]
```
$ ./target/debug/deno
> Deno.execPath
/Users/kevinqian/Desktop/Programming/Deno/deno/./target/debug/deno
```
Confusing to have an extra `/./` in the path
/cc @sh7dm

**Comment by ry** [comment]
Yes I noticed this too. This is what comes from Rust directly. We can probably apply `deno_fs::normalize_path` to it for a fix.
