### ISSUE TITLE
How to tell if a project is a Deno project?

### ISSUE THREAD

**Issue by snobu** [denoland/deno#17988]
Let's say i have a build service that's trying to detect language and runtime, to maybe generate a Dockerfile and do some other things.

Is there a high confidence method of telling apart a Deno project from any other TypeScript project? I say _project_, but you get me, i mean repo or directory structure.

I know there's a `deno.jsonc` file now generated by deno init, but there's no guarantee that it exists.

**Comment by elycheikhsmail** [comment]
maybe by analyzing deps graph from entry point, in my opinion we must three type of js project or more:
- js universal project for server: this mean the code can runned using deno, node
- js deno project only: can be with deno only
- js node project...
by the way I suggess adding isdeno subcommand to deno cli something like this:
deno isdeno main.ts
the out will be true or false that if this use some api not support in deno or not.

**Comment by dsherret** [comment]
No, there's not really any surefire way. A deno.json or deno.jsonc file existing might be an indication or analyzing the files to find https imports for `deno.land/x` might be an indication.

**Comment by snobu** [comment]
I would suggest implementing a surefire way to tell if it's a Deno project or not. It's preety much a basic requirement for building CI pipelines.
