### ISSUE TITLE
Feature request: Option to prevent terminal from opening after compile (on windows)

### ISSUE THREAD

**Issue by JasperVanEsveld** [denoland/deno#17990]
Windows applications differ from Linux and MacOS in that they can either be a console or GUI application.
Currently Deno is a console application by default, which carries over when using `deno compile`

However there are use cases for which you would not want a terminal window to open, see [this discussion](https://github.com/denoland/deno/discussions/11638). In the comments a user provides a script to change the relevant entry in the PE header to make any application a GUI application.

Another use case being possible webview support, for which it would not be a good user experience to see a terminal pop up.
[See latest comments in this discussion](https://github.com/denoland/deno/discussions/3234?sort=new#discussioncomment-5149598)

So I propose to add a flag, like `--no-terminal`, to `deno compile` which changes the header so it won't open the terminal.

**Comment by lino-levan** [comment]
For anyone looking for this functionality without hacking something together, deno windowing has an excellent cli tool called [wpack](https://github.com/deno-windowing/wpack) that packages this nicely.

**Comment by svefro** [comment]
does not work. application exits right away if compiled with --no-terminal

**Comment by svefro** [comment]
could not get --no-terminal to work so i made this https://jsr.io/@svefro/win-console-window-state

**Comment by joaogabrielti** [comment]
thanks @svefro
