### ISSUE TITLE
Feature request: Add `--asset` flag to compile

### ISSUE THREAD

**Issue by JasperVanEsveld** [denoland/deno#17994]
Currently only TS/JS files get added to the binary on `deno compile`, while other files might be needed as well.
This is related too #9574, but instead of having to manually change the binary I propose to add a flag, like `--asset <dir|file>`.
With the flag said directory or file gets included into the binary and is accessible in the runtime.

Making apps portable will be the main use case.
Even small `css` or `html` files now force you to either wrap it into a string export from a  JS/TS file or use the binary hack proposed in #9574.

This would also be useful for a possible webview API.
[See latest comments in this discussion](https://github.com/denoland/deno/discussions/3234?sort=new#discussioncomment-5149598)

As for the final API, I could see something like this as an option:
# Proposal
Given `deno compile --asset ./assets ./example.ts`
With `example.ts`:
```ts
// Returns path to a temp dir or temp file with the resources
// Or undefined if `--asset` was not used
const path = await Deno.asset()
```

So on `deno run` it needs to copy the contents of `./assets` to a temp dir.
And on running an executable from `deno compile` it needs to extract the resources into a temp dir.

One thing that I am not sure of with this approach is what happens when you write to the temp dir/file in `example.ts`.
I think there are two options to handle this:
- Somehow make the temp dir readonly (not sure how)
- Just allow it but overwrite all changes when rerunning

Option 1 is more restrictive but clearer
Option 2 might be confusing but simple to implement

**Comment by idanran** [comment]
interesting

**Comment by maekoos** [comment]
This may be a simple way to implement compile-time assets, however, it feels kind of redundant to write all of the files to disk when they are all stored in the binary anyway...

Wouldn't it be better to modify the file reading/writing functions built into Deno to check if the specified path is included in the binary? Then it would be easy to make those file paths readonly as well.

**Comment by andrewthauer** [comment]
As an alternative ...

I doubt this would work well for webapps, etc. but for a CLI, I came up with a pattern of creating an `embeds.json` file. This file contains keys for each file as base64 encoded strings. I then use `imports` & `with: { type: "json" }` to load the embeds.json file into code.

However, this requires a couple things to work. First I needed to create a build script that creates embeds.json file, which also needs to be run before running, compiling, testing, etc. Secondly I needed to create an `EmbedReader` class that abstracts the decoding of the strings to be used within the rest of TS code. Since the import with is deterministic at compile this works well. However, it required some thought and tooling to put together. I do wish there was a more native way to do this though. I've found `goembeds` very useful and this was my attempt to do something similar.

**Comment by ansarizafar** [comment]
Is there an update on this proposal?

**Comment by bartlomieju** [comment]
We are working on alternative solution that would allow to import files directly in code:
```js
import text from "./file.txt" with { type: "text }';
import bytes from "./file.txt" with { type: "bytes};
```

We might ship it in v1.40

**Comment by MohsinDev369** [comment]
Deno is now v1.42.0 is this supported?

**Comment by i-api** [comment]
this would be an amazing feature!

**Comment by i-api** [comment]
also would like to add regarding: --asset <FILE|DIR>

DIR would be especially useful, if say, you had lots of assets and didn't want to manually import all of them one line at a time

**Comment by petamoriken** [comment]
Text/Bytes Modules are in the process of being standardized, so we should wait for that.
https://github.com/whatwg/html/issues/9444

**Comment by terrablue** [comment]
Perhaps as an alternative, [similar to how Bun does it](https://bun.sh/docs/bundler/executables#embed-assets-files), would you be able to support the import attribute "file"?

When compiling apps with Bun, the semantics of using `with { type: "file" }` is that the import is converted to an internal path that points to a copy of the original file, allowing inclusion of any sort of file, that can then be read in during runtime.

**Comment by marcomow** [comment]
> We are working on alternative solution that would allow to import files directly in code:
> 
> ```js
> import text from "./file.txt" with { type: "text" }; // returns string of the code
> import bytes from "./file.txt" with { type: "bytes" }; // returns Uint8Array of code
> ```
> 
> We might ship it in v1.40

@bartlomieju I couldn't find any reference, any update on this - as it's still not working in Deno 2.0 ? thanks!

**Comment by dsherret** [comment]
The ability to include assets was implemented in Deno 2.1:

* https://github.com/denoland/deno/pull/26934
* https://github.com/denoland/deno/pull/26939

https://docs.deno.com/runtime/reference/cli/compile/#including-data-files-or-directories

**Comment by babakfp** [comment]
Using `--include` didn't work for me. So, I did it this way instead:

1. Installed https://jsr.io/@nfnitloop/deno-embedder

So much with (you don't need to install a dependency, and Deno handles it all).

2. Created `embed.ts`:

```ts
import * as embedder from "jsr:@nfnitloop/deno-embedder"

const options = {
    importMeta: import.meta,

    mappings: [
        {
            sourceDir: "public",
            destDir: "embed/public",
        },
    ],
}

if (import.meta.main) {
    await embedder.main({ options })
}
```

3. Tasks in `deno.json`:

```json
{
    "tasks": {
        "dev": "deno run -A --watch src/index.tsx",
        "compile": "deno task embed && deno compile -A --icon public/icon.ico -o vscode-pretty-styles src/index.tsx -p",
        "embed": "deno run -A embed.ts build"
    },
}
```

> [!IMPORTANT]
> You must use the below config in `deno.json` to get this working.
> ```json
> {
>    "fmt": {
>        "indentWidth": 4,
>        "semiColons": false
>    }
> }
> ```

4. Ran `deno task embed`.

5. In `src/index.ts`:

```ts
import embed from "../embed/public/dir.ts"

const PRODUCTION_FLAG = "-p"

if (Deno.args.includes(PRODUCTION_FLAG)) {
    app.get("**", async (c) => {
        const url = new URL(c.req.url)
        for (const path of embed.list()) {
            if (url.pathname === `/${path}`) {
                const file = await embed.get(path)
                const bytes = await file!.bytes()
                return c.newResponse(bytes)
            }
        }
        return c.notFound()
    })
} else {
    app.use("*", serveStatic({ root: "public" }))
}
```

That's it. Now you can run the `deno task compile` and move the EXE into a different file and check to see if it works or not.

> [!NOTE]
> You can do this too instead:
> ```ts
> app.get("**", async (c) => {
>     const url = new URL(c.req.url)
>     for (const path of embed.list()) {
>         if (url.pathname === `/${path}`) {
>             const file = await embed.get(path)
>             const bytes = await file!.bytes()
>             return c.newResponse(bytes)
>         }
>     }
>     return c.notFound()
> })
> ```

After years, Deno still can't get this right!

---

> [!TIP]
> If you are using `.ico` files. Just know that f*cking windows caches them. Meaning, if you use an icon and compile, then change the icon and compile, you will get the same icon. The EXE file will use the new icon, but windows will show the old one.

**Comment by dsherret** [comment]
> After years, Deno still can't get this right!

Probably you're doing something wrong or you're using an old version. Ensure you're using Deno 2.1.4 as there were some bugs in the first release.

**Comment by babakfp** [comment]
> > After years, Deno still can't get this right!
> 
> Probably you're doing something wrong or you're using an old version. Ensure you're using Deno 2.1.4 as there were some bugs in the first release.
> 
> Also, please read the documentation here: https://docs.deno.com/runtime/reference/cli/compile/#including-data-files-or-directories
> 
> If there is indeed a bug, then please open an issue.

It's `v2.1.4`.

Here is the result:

```
 deno task compile                                                   
Task compile deno compile -A --include public/**/* -o vscode-pretty-styles src/index.tsx -p                                                 
error: Expected a JavaScript or TypeScript module, but identified a Css module. Importing these types of modules is currently not supported.
  Specifier: file:///C:/Users/Babak/Documents/Code/vscode-pretty-styles/public/css/index.css
```

I'm not interested in wasting more of my time with this anymore.

**Comment by dsherret** [comment]
@babakfp I opened https://github.com/denoland/deno/issues/27505 for you.
