### ISSUE TITLE
Add support for Junctions

### ISSUE THREAD

**Issue by jessiejs** [denoland/deno#18007]
Recently, I was working on a project that would have to run on windows, and create a link.
Unfortunately, on windows, symlinks require administrator privleges, so if you want to get around this, you need to use junctions.
Please add some sort of junction support to Deno, perhaps add a ```useJunctions``` flag to [SymlinkOptions](https://deno.land/api@v1.31.1?s=Deno.SymlinkOptions), that would create a junction instead of a link, if you are running on windows.

**Comment by littledivy** [comment]
Deno support junctions now: https://docs.deno.com/api/deno/~/Deno.SymlinkOptions
