### ISSUE TITLE
`deno.jsonc` task nesting

### ISSUE THREAD

**Issue by harrysolovay** [denoland/deno#18013]
I find myself often prefixing tasks in order to signify grouping.

```json
{
  "tasks": {
    "test:js": "deno test -A -L=info",
    "test:rust": "cargo test",
    "test:update": "deno test -A -L=info -- --update"
  }
}
```

I believe this grouping would be better-expressed through a tree.

```json
{
  "tasks": {
    "test": {
      "js": "deno test -A -L=info",
      "rust": "cargo test",
      "update": "deno test -A -L=info -- --update"
    }
  }
}
```

The leaves of which could be executed like so:

```
deno task test js
deno task test rust
deno task test update
```

Thoughts?

**Comment by bartlomieju** [comment]
@dsherret any thoughts on this? Seems somewhat reasonable for me.

**Comment by dsherret** [comment]
I don’t think this is worth the extra complexity.

**Comment by harrysolovay** [comment]
Very good points. I agree. Thank you for the diligent consideration.
