### ISSUE TITLE
Add environment variable to change REPL history file path

### ISSUE THREAD

**Issue by njhanley** [denoland/deno#18010]
A fairly common practice with REPL interfaces is to allow the location of the history file to be changed with an environment variable. This allows users to put their history in tmpfs to be cleared on shutdown or disable saving between sessions entirely by pointing towards `/dev/null` or an empty path. This kind of configuration is particularly useful when experimenting with API tokens or other secrets interactively, where ideally they should never touch the disk. I suggest adding an environment variable named `DENO_REPL_HISTORY` (based on Node's own feature) or similar to specify a custom history file path.

**Comment by bartlomieju** [comment]
Could you give examples of other REPLs that allow to do that? 

Seems like a reasonable feature; would you be interested in implementing it yourself?

**Comment by njhanley** [comment]
Most notably, [Node (`NODE_REPL_HISTORY`)](https://nodejs.org/api/cli.html#node_repl_historyfile).

Other examples:
[GDB (`GDBHISTFILE`)](https://sourceware.org/gdb/onlinedocs/gdb/Command-History.html)
[SQLite (`SQLITE_HISTORY`)](https://www.sqlite.org/src/info/696e82f7c82d1720)
[POSIX shell(s) (`HISTFILE`)](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/sh.html) (i.e. [Bash](https://www.gnu.org/software/bash/manual/bash.html#index-HISTFILE), [Zsh](https://zsh.sourceforge.io/Doc/Release/Parameters.html#index-HISTFILE), [mksh](http://www.mirbsd.org/htman/i386/man1/mksh.htm), etc.)
[tcsh (`history`)](https://web.archive.org/web/20160401090002/http://www.tcsh.org/tcsh.html/Special_shell_variables.html#histfile)

There's been talk of adding a similar feature to Python for years <sup>[1], [2]</sup>, though `PYTHONSTARTUP` allows a workaround.

I'd be happy write it myself! To be specific, `DENO_REPL_HISTORY`, if set, would specify the  absolute path to the history file, or disable writing if set to the empty string (`DENO_REPL_HISTORY=`). Sound good?

[1]: https://bugs.python.org/issue29779
[2]: https://github.com/python/cpython/pull/13208

**Comment by bartlomieju** [comment]
Seems reasonable, PRs are welcome!
