### ISSUE TITLE
npm start compatibility

### ISSUE THREAD

**Issue by farsightsoftware** [denoland/deno#18027]
(Loving Deno so far.) I noticed a minor thing in the new `package.json` support (very cool!) I thought I should flag up if it's not already on the list: `deno task start` doesn't implement `npm start`'s / `npm run start`'s fallbacks. Currently it looks like it purely looks for a `start` task in `scripts` and says there's no task if it doesn't find one. In contrast, `npm start` has a [two-level fallback](https://docs.npmjs.com/cli/v6/commands/npm-start):

* If there's no `start` task in `scripts`, it looks for a `start` package property.
* If there's no `start` package property, it runs `node server.js`.

I suspect some number of folks don't even realize they're relying on those fallbacks (I didn't). It may be worth either:

1. Implementing the same fallbacks,
    or
3. Adding a specific message if the task requested is `start`, something like:
    > `deno task start` requires a `start` entry in `scripts`, it doesn't support the fallbacks `npm start` uses (https://docs.npmjs.com/cli/v6/commands/npm-start). To use `deno task start`, add an explicit `start` task to `scripts`.

Again, great stuff on Deno and related, thanks.

**Comment by dsherret** [comment]
Generally Deno prefers explicitness so I don't think we should support `deno task start` doing `deno run -A server.js` even when there's a package.json.

> If there's no start task in scripts, it looks for a start package property.

Is this true? I don't see that in the documentation and I tried it out and got `Missing script: "start"`

**Comment by farsightsoftware** [comment]
@dsherret 

> > If there's no start task in scripts, it looks for a start package property.
>
> Is this true? I don't see that in the documentation and I tried it out and got Missing script: "start"

What was I smoking? I was sure I saw that. Clearly not, I misread something.

> Generally Deno prefers explicitness so I don't think we should support deno task start doing deno run -A server.js even when there's a package.json.

Frankly, I don't much care for `npm start` doing that, either. It was really the `start` package property that I'd magically invented I thought should be supported. Since it doesn't exist, and adding a note after the usual "Task not found" would saying "`npm start` would do `node server.js` in this situation" would seem frankly odd, this issue is pointless.

Sorry about that!
