### ISSUE TITLE
Add test for `deno cache --node-modules-dir file_with_no_npm_specifiers.ts` creating no `node_modules` dir

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#18038]

**Comment by AbhinavMir** [comment]
hey!
new to deno
would you want me to add a new test file and add this test? I'm not sure where to hunt for this specific case? pretty sure I could get to the bottom of this! cheers, thanks.

**Comment by dsherret** [comment]
Sorry @AbhinavMir, I missed this comment. We had a regression related to this so I fixed this in https://github.com/denoland/deno/pull/18134/files (this shows where the test would be created for next time)

**Comment by AbhinavMir** [comment]
no problem and thanks for ur service to the community @dsherret
