### ISSUE TITLE
Implement `mode` field of `Deno.FileInfo` on Windows

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#18053]
Right now the `mode` field is completely un-populated on Windows.

On Node, it is always `0` ([libuv todo](https://github.com/libuv/libuv/blob/460accf9be077f376baebd93a39c214644442674/src/win/fs.c#L1769-L1788), hey @piscisaureus!)

On Go, it is reasonably populated. The mode very realistically emulates Unix. [Code here](https://cs.opensource.google/go/go/+/master:src/os/types_windows.go;l=144-166;drc=1951857ec07c1d491e1836770a647d3902934a67)

I think we should populate them like Go does.

**Comment by lucacasonato** [comment]
I'm running into [some Node compat issues](https://github.com/evanw/esbuild/pull/2968) because of this. Can we populate it as 0 in `node:fs` for now also?

**Comment by piscisaureus** [comment]
Yes let's do 0.

There is a tradeoff here - we can emulate unix more diligently but you end up making a lot more syscalls (slow!) and it's still probably not very useful.
