### ISSUE TITLE
Double Pointer?

### ISSUE THREAD

**Issue by AlbertShown** [denoland/deno#18054]
I'm just wondering if there is a way to copy a TypeScript buffer to a C `char**`?
[Here](https://github.com/AlbertShown/webui/blob/a446188f17205c7cdca5e4b2edecaaa6b5a48615/examples/TypeScript/Deno/dynamic/webui.ts#L175), I tried to do it, but, I'm sure I missed something.

1. C call Deno callback with `char**` as parameter
2. Deno creates a buffer and updates it with some string
3. Deno set the buffer address to the `char**`
4. C reads back the Deno string

https://github.com/AlbertShown/webui/blob/a446188f17205c7cdca5e4b2edecaaa6b5a48615/examples/TypeScript/Deno/dynamic/webui.ts#L175

```
deno 1.31.1 (release, x86_64-pc-windows-msvc)
v8 11.0.226.13
typescript 4.9.4
```

**Comment by AlbertShown** [comment]
```
export function bind(win, element, func) : number {

    const callbackResource = new Deno.UnsafeCallback(
        {
            parameters: [
                   'pointer' // <------ This is char**
                   ],
            result: 'void',
        } as const,
        (
            param_response: Deno.Pointer,
        ) => {

            const result = String("Hello");

            // `result`         : The callback result in string
            // `param_response` : It's a non initialized (null) `char**`

            // Now, we should create a non-garbage colleted buffer, fill it with `result`
            // and set it to `param_response`.

            // Create A Buffer
            // This code is by ChatGPT (AI)
            const encoder = new TextEncoder(); // Create a TextEncoder instance
            const resultBytes = encoder.encode(result); // Convert the string to bytes
            const buf = new Uint8Array(resultBytes.length + 1); // Allocate a buffer to hold the string
            buf.set(resultBytes); // Copy the bytes of the string into the buffer
            buf[resultBytes.length] = 0; // Set the null terminator

            // Set our buffer `buf` to `char**`
            param_response = buf; // <---------- This is not working
        },
);

```

**Comment by AlbertShown** [comment]
Any idea?

**Comment by aapoalas** [comment]
Sorry about the delay. You're trying to assign to a variable in JS, hoping that it corresponds with a native reference. That is not the case.

You'll need to use `Deno.UnsafePointerView.getArrayBuffer` to get 8 bytes worth of memory from the pointer. Then you write your `buf`'s pointer value (`Deno.UnsafePointer.value()`) into that using eg. BigUint64Array view of the buffer.

**Comment by aapoalas** [comment]
You won't be risking a memory leak: Returning a buffer from a callback doesn't keep the buffer from being garbage collected, so it'll eventually be collected and become a dangling pointer.

If you only need the buffer synchronously in C then it's probably safe to do as you suggest and just return the buffer as a pointer. You may also want to set up a static return buffer that you reuse for the callback returning, thus avoiding multiple allocations.

**Comment by AlbertShown** [comment]
Thank you for your suggestions.

The `static buffer` is a good idea, but unfortunately, the C code is multi-thread, so the simultaneous calls can override responses in this one `static buffer`. And, making the callback return the buffer as a pointer also won't work for me, as the C code expects a `void` return.

```c
void test() {
    char* Buffer;
    call_deno_function((char**)&Buffer);
    printf("The Deno response is %s", Buffer); // We should print "Hello"
}
```

```javascript
export function bind(win, element, func) : number {
    const callbackResource = new Deno.UnsafeCallback(
        {
            parameters: [
                   'pointer' // char**
                   ],
            result: 'void', // Void
        } as const,
        (
            param_response: Deno.Pointer,
        ) => {

            const result = String("Hello");
            // How to create a buffer, and makes `param_response` point to our buffer
            // I know that TypeScript is not pass-by-reference, so is this even possible?
            
            // Value of `param_response` = address of `our_buffer`;
            // Keeping the buffer alive is another issue...
        },
);
```

I work multiple hours daily to find the best way to do this. I hope you can help me.

**Comment by AlbertShown** [comment]
There is no way to do this in Deno FFI. It's just the JS language limitation.

**Comment by AlbertShown** [comment]
I should change the C code and makes the Deno callback return a `static buffer`.

**Comment by aapoalas** [comment]
So there is definitely a way to do this. As I said in my original response, you'll need to get a writable AB from the pointer you're passed, follow it to the `char*` pointer and write your buffer there.

Like this:

```ts
// Just the JS callback given to Deno.UnsafeCallback
(param_response: Deno.PointerValue) => {
  // param response is a pointer to a memory slot large enough to keep a pointer
  const target = new BigUint64Array(Deno.UnsafePointerView.getArrayBuffer(param_response, 8); // 8 bytes ie. pointer size on a 64 bit machine, use BigUin64Array to get a writable and suitable view into it.
  const stringBuffer = new TextEncoder().encode("Hello\0");
  target[0] = BigInt(Deno.UnsafePointer.of(stringBuffer)); // Write our string response buffer address into the `param_response` memory slot.
}
```

The only thing you need to worry about is the lifetime of the `stringBuffer` since from JS point of view it's not needed after the `Deno.UnsafePointer.of(stringBuffer)` call and can thus be garbage collected at any time. You should bind its lifetime to something so that it is guaranteed to stay alive for as long as the C code uses the pointer you just wrote into `param_response`.

**Comment by aapoalas** [comment]
Oops, sorry. I forgot that you'll need a `Deno.UnsafePointer.value()` to get the numeric value of the pointer. My apologies :(

**Comment by AlbertShown** [comment]
It's working perfectly now 👍 
This was the last puzzle to fully support Deno in [WebUI](https://github.com/alifcommunity/webui/blob/main/examples/TypeScript/Deno/dynamic/webui.ts)
Thank you so much @aapoalas, I appreciate it.
