### ISSUE TITLE
Uncaught Error: Deno.core.runMicrotasks() is not supported in this environment

### ISSUE THREAD

**Issue by harvestcore** [denoland/deno#18052]
Hey y'all.

I'm trying to write some benchmarks for my Deno app. At first I was using Deno version `1.29.4`, but wanted to upgrade to Deno version >= 1.30.0 since starting from that version the `--json` flag for the `deno bench` is available.

I'm getting the following error:
```
error: Uncaught Error: Deno.core.runMicrotasks() is not supported in this environment
      throw new Error(
            ^
    at Object.runMicrotasks (https://deno.land/std@0.170.0/node/_core.ts:22:13)
    at processTicksAndRejections (https://deno.land/std@0.170.0/node/_next_tick.ts:62:10)
    at https://deno.land/std@0.170.0/node/process.ts:375:7
    at innerInvokeEventListeners (internal:deno_web/02_event.js:783:7)
    at invokeEventListeners (internal:deno_web/02_event.js:823:5)
    at dispatch (internal:deno_web/02_event.js:692:9)
    at dispatchEvent (internal:deno_web/02_event.js:1073:12)
    at [internal:cli/worker.rs:268:39]:1:1
```

Here's a screenshot of the benchmark passing when using Deno v1.29.4 and failing when using v1.31.1. The error is thrown starting from version 1.30.0 to 1.31.1 (latest version at the moment of creating this issue).

The code executed in the benchmark just loads an XML and does some basic transformations to it.

![Captura de pantalla 2023-03-06 a las 16 16 20](https://user-images.githubusercontent.com/22531231/223152371-63528fc2-4eb9-4781-b654-1ec65bcd9639.png)

**Expected behavior:** The benchmark runs fine and returns no errors.

**Actual behavior:** The benchmark fails.

Does this error trigger any alarm? Am I missing something? Please let me know if you need more information from my side.

**Comment by lucacasonato** [comment]
Update your Deno standard library import (deno.land/std). If you are not importing std directly, you can find the package that is using `deno info <entrypoint>`. Either pull an updated version of that package, or use an import map to replace the std version with a later one, or `node:` specifiers (if it is importing `deno.land/std/node`)

**Comment by harvestcore** [comment]
@lucacasonato That worked! Thank you very much!
