### ISSUE TITLE
Http - connection closed before message completed

### ISSUE THREAD

**Issue by tvortsa** [denoland/deno#18064]
today i got this error :
[uncaught application error]: Http - connection closed before message completed at async Object.respondWith (deno:ext/http/01_http.js:211:11).
What is it ? :(

**Comment by AlbertShown** [comment]
Any more details or a complete code?

**Comment by tvortsa** [comment]
ahh, I myself pressed the reset connection! 
Im stupid, sorry :)

**Comment by AlbertShown** [comment]
> ahh, I myself pressed the reset connection! Im stupid, sorry :)

Don't worry, this happens to everybody 👍
