### ISSUE TITLE
deno check: Add a option to exclude specific files from type checking

### ISSUE THREAD

**Issue by magurotuna** [denoland/deno#18089]
Now `deno check` command provides two options in terms of how many modules it's going to typecheck.

- no option: only local modules are typechecked
- `--all`: all modules including remote are typechecked

This suffices in almost all use cases, but it's going to be complicated if we want to perform typecheck within the project that vendors external dependencies using `deno vendor`. Vendored dependencies are considered "local" so `deno check` will check for vendored ones as well. This is sometimes troublesome if vendored dependencies have type errors that are known and acceptable.

So it would be great if we could have a new option, let's say `--ignore=<ignore>`, that make the type checker ignore type errors happening in the specified files. This way, specifying `--ignore=vendor/` will allow us to ignore vendored dependencies.

**Comment by dsherret** [comment]
I think this is a duplicate of #14797 or at least related to?

**Comment by magurotuna** [comment]
Yes this PR is a complete duplicate of  #14797 - I'm going to close this in favor of #14797
