### ISSUE TITLE
[Discussion] Other lang support (Dart)

### ISSUE THREAD

**Issue by daniele-orlando** [denoland/deno#1808]
Hi dear all.

First of all I really want to congratulate with you for the awesome Deno project; you took the best ideas and technology out there packaging everything in one piece of art. ^_^

I want to post a question for the mere curiosity and, in case, start a discussion.

Have you evaluated the idea of extending the supported programming languages to other languages that can be effectively translated to JavaScript?

Given the Deno platform and its way of resolving dependencies, translating them just-in-time to JavaScript, I think it would be awesome to expand the supported languages to others than JavaScript and TypeScript.

I take as example **Dart** because it is a good language and a translator is already available, but the same arguments can be extended to any other language that can be easily translated to JavaScript, for example **Elm**.

**Comment by ry** [comment]
Let's discuss in this issue: https://github.com/denoland/deno/issues/1739

Generally we want to have a better API for plugging in compilers. I doubt we will include any of these by default like we do TypeScript (we consider it special) ... but it would be nice to have a way for 3rd party compilers to plug in.
