### ISSUE TITLE
`package.json` support breaks on `git+<url>`

### ISSUE THREAD

**Issue by ryanblock** [denoland/deno#18101]
Deno v1.31+ breaks our project's CI because a `package.json` file is present on the filesystem that includes a `git+<url>` dependency. That `package.json` file has nothing to do with the context in which Deno is being executed, and we can't currently work around this (other than to prevent v1.31 from being used in this project).

There are two separate things going on here:

### Blowing up on `git+<url>`

Deno currently blows up on a totally legal `package.json` file that contains a [`git+<url>` dependency](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#git-urls-as-dependencies). This appears to be known behavior, but is not ideal, and doesn't appear to be able to be worked around. The error:

```
    Invalid npm specifier version requirement. Unexpected character.
      git+https://github.com/...
```

Ideally (to me) this would be a (suppressible) warning, not an error that exits the process.

### Unnecessarily(?) exploring the filesystem for `package.json`

The other issue here we encountered was that Deno was exploring the filesystem for a `package.json` file when that really wasn't necessary (from our side). Perhaps that is necessary for Deno, but we don't want or need that, and it cannot be worked around.

Project layout in question:
```
src/lambda/index.ts   # folder to run Deno within
package.json          # contains the offending git+<url> dep   
```

In the project above, we run Deno within `./src/lambda/`; everything related to Deno's execution context is contained within `./src/lambda/`, and Deno does not need to know anything about `./src/`, or `./`.

### Repro steps

Create a project like the above where the `package.json` contains a git url dep, run `deno eval "console.log('hi')"` from within `src/lambda/`, see error. `--node-modules-dir=false` has no impact.

Add an empty `package.json` to `src/lambda/`, and it will no longer fail.

**Comment by dsherret** [comment]
It should be fixed in the deno 1.31.2 release happening tonight via #17974.

**Comment by ryanblock** [comment]
Thanks, @dsherret!

**Comment by Gabryx64** [comment]
On Arch Linux using the Arch Communty Repository deno, even when upgrading to canary it does not work.

**Comment by dsherret** [comment]
See https://github.com/denoland/deno/issues/18557#issuecomment-1493150812 -- this is a slightly different issue than that.
