### ISSUE TITLE
`integration::repl` tests hang on local machine

### ISSUE THREAD

**Issue by GJZwiers** [denoland/deno#18129]
Source: https://discord.com/channels/684898665143206084/684911491035430919/1083922631268503622

Repro (main branch):

```bash
cargo test integration::repl
...
test integration::repl::variable ... ok
test integration::repl::pty_assign_global_this has been running for over 60 seconds
test integration::repl::pty_bad_input has been running for over 60 seconds
test integration::repl::pty_clear_function has been running for over 60 seconds
test integration::repl::pty_complete_declarations has been running for over 60 seconds
test integration::repl::pty_complete_expression has been running for over 60 seconds
test integration::repl::pty_complete_imports has been running for over 60 seconds
test integration::repl::pty_complete_imports_no_panic_empty_specifier has been running for over 60 seconds
test integration::repl::pty_complete_primitives has been running for over 60 seconds
test integration::repl::pty_complete_symbol has been running for over 60 seconds
test integration::repl::pty_emoji has been running for over 60 seconds
test integration::repl::pty_ignore_symbols has been running for over 60 seconds
test integration::repl::pty_null has been running for over 60 seconds
test integration::repl::pty_syntax_error_input has been running for over 60 seconds
test integration::repl::pty_tab_handler has been running for over 60 seconds
test integration::repl::pty_unpaired_braces has been running for over 60 seconds
```

**Comment by GJZwiers** [comment]
I found that these tests hang on calling to `std::io::Read::read_to_string`:
https://github.com/denoland/deno/blob/8db853514caae431a0ce91360d854c1b7f3c405f/test_util/src/pty.rs#L17

So it may be an upstream issue.

**Comment by mmastrac** [comment]
@GJZwiers Taking a look at this now as I'm seeing the same thing on my Ventura mac.

As a temporarily workaround, this allows the tests to proceed:

```
echo | cargo test integration::repl
```

**Comment by bartlomieju** [comment]
Nice investigation @mmastrac! @dsherret recently suggested that we should maybe replace `rustyline` with our own custom solution (that would eg. support async interface). Maybe it's a good reason to do it (though if we could switch to using a different way to runnign tests that would also work and be faster to implement).

**Comment by GJZwiers** [comment]
There are also some `repl` calls in `cli/tests/integration/run_tests.rs` that may be affected by the same issue:

- `file_fetcher_preserves_permissions`
- `stdio_streams_are_locked_in_permission_prompt`
- `permission_prompt_strips_ansi_codes_and_control_chars`

**Comment by dsherret** [comment]
I found that we need to read the output buffer after every "write line" call or else it will just hang indefinitely for some strange reason. I found https://crates.io/crates/expectrl which seems to also work on windows. I'm switching over to it in https://github.com/denoland/deno/pull/18424/
