### ISSUE TITLE
`deno fmt` should have an easy way of exiting with non-zero in CI 

### ISSUE THREAD

**Issue by mohsen1** [denoland/deno#18126]
I want to make sure code is well formatted in CI (for a PR for instance). I can rely on Git to see if `deno fmt` makes changes to the code but a command like `deno fmt --check` would be more ideal

**Comment by dsherret** [comment]
> but a command like `deno fmt --check` would be more ideal

This should work today 🙂

**Comment by mohsen1** [comment]
Ahh.... I totally missed this flag. Thanks for quick respond!
