### ISSUE TITLE
Type checking does an excessive amount of fs::exists calls that don't apply to Deno when a config file exists

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#18121]
On startup, type checking does about 12,000 `fs::exists` calls looking for `node_modules/<lib...>` paths (ex. `file:///V:/deno/cli/tests/node_modules/@typescript/lib-esnext/index.jsx`).

We should investigate how to disable this.

Edit: It's about 12,000 nested one directory deep from the file system root with a config file, and fast without a config file because then it doesn't have a cwd for some reason.

**Comment by bartlomieju** [comment]
The easiest solution seems to provide `fileExists` method on our TSC host. It would not go from JS to Rust is a path contains `node_modules/` segment

**Comment by dsherret** [comment]
Sometimes we want to go into node_modules though because of node compat so it would need to be a bit smarter. I wonder if we just have typescript misconfigured.

**Comment by dsherret** [comment]
The problem lines of code are here: https://github.com/microsoft/TypeScript/blob/46d70d79cd0dd00d19e4c617d6ebb25e9f3fc7de/src/compiler/program.ts#L3819-L3823

We need to upstream a change to typescript to be able to disable this.

**Comment by dsherret** [comment]
This will be fixed by the changes made in https://github.com/denoland/deno/pull/18124/commits/980cee92d4c16b694326177ff8cdb71f11b0b65e which reverts some of https://github.com/denoland/deno/pull/10999 -- so this should be fast enough that we don't need to make any changes in typescript and it consolidates the behaviour between having a config and not having one.
