### ISSUE TITLE
[bug] [uncaught application error]: Error - Not implemented: crypto.generateKeyPair

### ISSUE THREAD

**Issue by dogukanakkaya** [denoland/deno#18138]
Below code throwing the error `Error - Not implemented: crypto.generateKeyPair`
```ts
import Arweave from 'npm:arweave';

const key = await arweave.wallets.generate();
```
I see that arweave uses `crypto` module to generate wallet but it's causing errors. I assume it's because `generateKeyPair` function is not implemented in Deno's `crypto` module yet?

Update: same for `[uncaught application error]: Error - Not implemented: crypto.Sign`

**Comment by bartlomieju** [comment]
Thanks for the report @dogukanakkaya. It appears this API is now implemented. When I try your reproduction I get following error:

```js
error: Uncaught ReferenceError: arweave is not defined
const key = await arweave.wallets.generate();
            ^
    at file:///Users/ib/dev/deno/ar.js:3:13

```

Could you try it on your side and let me know if that's the correct reproduction?

**Comment by littledivy** [comment]
generateKeyPair is not implemented. We're tracking all missing APIs of node:crypto in https://github.com/denoland/deno/issues/18455. Closing.

**Comment by dogukanakkaya** [comment]
Issue still persists.
<img width="1209" alt="Screenshot 2023-03-28 at 11 00 44" src="https://user-images.githubusercontent.com/51231605/228169258-56a933be-2a84-46db-9bbf-6653fddc8ad0.png">
