### ISSUE TITLE
deno workspace/symbol with an empty query returns nothing

### ISSUE THREAD

**Issue by sigmaSd** [denoland/deno#18145]
According to the spec it should return the full list
```
/**
 * The parameters of a Workspace Symbol Request.
 */
interface [WorkspaceSymbolParams](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspaceSymbolParams) extends [WorkDoneProgressParams](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workDoneProgressParams),
	[PartialResultParams](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#partialResultParams) {
	/**
	 * A query string to filter symbols by. Clients may send an empty
	 * string here to request all symbols.
	 */
	query: string;
}
```

deno lsp uses this https://github.com/denoland/deno/blob/8db853514caae431a0ce91360d854c1b7f3c405f/cli/lsp/tsc.rs#L3308 which seems that it returns an empty array, it seems that there are other functions that can return the items https://github.com/Microsoft/TypeScript/issues/2500

**Comment by nayeemrmn** [comment]
It looks like TS server for node intentionally doesn't implement this. (Though maybe it did at one point https://github.com/sourcegraph/javascript-typescript-langserver/pull/19?) We're probably going to do the same. It's not good to search through the entirety of the dependency graph when the user presses CTRL+T.

**Comment by sigmaSd** [comment]
If I want to see all the symbols how do I do it then?when I use this in helix for example I get an empty list because of the current behavior.

**Comment by nayeemrmn** [comment]
Is it possible to do it with the TS server for Node, if that's usable on helix?

**Comment by sigmaSd** [comment]
Same behavior, it shows an empty list until I send a query
