### ISSUE TITLE
FFI: Need a way to distinguish PointerObject from other objects

### ISSUE THREAD

**Issue by djfos** [denoland/deno#18146]
Let's see the code,
``` ts
interface A {
}

const buffer = Uint32Array.of(1, 2, 3);
const pointer = Deno.UnsafePointer.of(buffer);
const object = {} as A;

console.log(typeof buffer);
// object
console.log(typeof pointer);
// object
console.log(typeof object);
// object
console.log(Object.prototype.toString.call(buffer));
// [object Uint32Array]
console.log(Object.prototype.toString.call(pointer));
// [object Object]
console.log(Object.prototype.toString.call(object));
// [object Object]

// error, PointerObject is only a type and not exposed!!
console.log(pointer instanceof Deno.PointerObject);

function foo(value: A | Deno.PointerValue){
    if(isPointerObject(value)){ // How ??
        ...
    }
}
```
How to check a value is a `PointerObject`? 
The PR that introduce `PointerObject`, #16889

**Comment by aapoalas** [comment]
It's not (by V8 engine design) possible to distinguish a pointer object (`v8::External`) from other objects. I expect that in your use case you'd want to go by the method of elimination:

Is this value a number or bigint? If so, then presumably this is meant to be a pointer integer and `Deno.UnsafePointer.create()` should be called to create a pointer object.

Is this value a `Uint8Array` (equivalently for other typed arrays and ArrayBuffer)? Then presumably we should call `Deno.UnsafePointer.of()` to get the pointer object of the buffer.

Is this value null? Then it's a null pointer.

Is this value an object? Then presumably it is a pointer object.

If you really must know if an object is a pointer object, you may do `try { Deno.UnsafePointer.value(object); return true } catch { return false; }`, as only pointer objects (and null) will pass through that call without throwing. However, this shouldn't really be necessary normally as elimination is a better way of getting where you want to be. Furthermore, if you're about to pass a non-pointer object into an FFI call, the FFI call will throw an equivalent error for the non-pointer object as `Deno.UnsafePointer.value()` does, so you're not really gaining any information. Finally, the above try-catch code might run into a nasty V8 bug that we're currently trying to get fixed.

**Comment by djfos** [comment]
@aapoalas
Thank you for the reply, I appreciate this.
The duck type check seems the only way to work around.
And `Object.keys(x).length == 0 && Object.getPrototypeOf(x) === null && Object.isExtensible(x) == false ` is enough to use in most situations.
