### ISSUE TITLE
`workspace:` specifier not supported for `package.json` dependency

### ISSUE THREAD

**Issue by jonasb** [denoland/deno#18192]
I'm using Deno in a monorepo where I use `pnpm` as the package manager (through [rush](https://rushjs.io/)).

To refer to other packages in the same monorepo, I use the version specifier `"workspace:*"`, which is not supported by Deno's `package.json` functionality.

My [`package.json`](https://github.com/dossierhq/dossierhq/blob/main/libraries/deno-postgres/package.json) file looks like this:

```json
{
  "devDependencies": {
    "@dossierhq/core": "workspace:*"
  }
}
```

I get this warning when `deno task test`:

```
Warning Ignoring dependency '@dossierhq/core' in package.json because its version requirement failed to parse: Not implemented scheme: @dossierhq/core
```

It would be great if Deno could support `"workspace:*"` in `package.json` so I don't need to use import maps to support monorepo setups.

**Comment by ericallam** [comment]
We also need this for running tests in a pnpm monorepo (https://github.com/triggerdotdev/trigger.dev)

**Comment by himself65** [comment]
I want to have this feature. I'm a library maintainer. I want to support both deno, nodejs and bunjs. So I need to run build and `node --test ./node/*.test.ts` & `deno test ./deno/*.test.ts` & `bun test ./bun/*.test.ts` in one time

**Comment by castarco** [comment]
Our use case is a little bit different, but also monorepo-related:

We have internal automation tools written in TypeScript, and it we'd like to skip the compilation step and run them directly with Deno instead of Node. That would help us a lot to simplify our internal automations.

**Comment by ssadler** [comment]
Im running all my code this way and ts-node is a disaster plz halp 🥺

**Comment by birkskyum** [comment]
Hit the "Not implemented scheme 'workspace'" as well, using pnpm for workspaces but wanted to run one of the packages with deno

**Comment by bartlomieju** [comment]
Support for npm workspace is something @dsherret is gonna look into in a few weeks, once we finalize Deno workspace support (to avoid code conflicts).

**Comment by dsherret** [comment]
Will start working with an npm workspace in 1.45.
