### ISSUE TITLE
When I use a self-signed certificate to start an HTTPS service, an error is reported

### ISSUE THREAD

**Issue by jiawei397** [denoland/deno#18217]
When I use a self-signed certificate to start an HTTPS service, an error is reported:
```bash
TLS alert received: AlertMessagePayload {
    level: Fatal,
    description: CertificateUnknown,
}
```
I know that this behavior is right, but it is also annoying to keep such prompt during local development. Is there a way to turn off the prompt, or just prompt once?

The test sample is as follows:
```ts
import { serveTls } from "https://deno.land/std@0.179.0/http/server.ts";
const certFile = "ca/cert.pem";
const keyFile = "ca/key.pem";
serveTls((_req) => new Response("Hello, world"), {
  certFile,
  keyFile,
  onListen: () => {
    console.log("stated");
  },
  port: 443,
});
```

When I request different interfaces at the same time, I will report an error every time:
```bash
TLS alert received: AlertMessagePayload {
    level: Fatal,
    description: CertificateUnknown,
}
TLS alert received: AlertMessagePayload {
    level: Fatal,
    description: CertificateUnknown,
}
TLS alert received: AlertMessagePayload {
    level: Fatal,
    description: CertificateUnknown,
}
TLS alert received: AlertMessagePayload {
    level: Fatal,
    description: CertificateUnknown,
}
```
I requested this in my browser:
```ts
Promise.all([1,2,3,4].map(key => fetch("https://localhost/" + key)))
```

**Comment by bartlomieju** [comment]
I believe you should be able to disable it with `--unsafely-ignore-certificate-errors`

**Comment by jiawei397** [comment]
> I believe you should be able to disable it with `--unsafely-ignore-certificate-errors`

Unfortunately, I still use the same prompt. My Deno version information:
```bash
deno 1.31.1 (release, aarch64-apple-darwin)
v8 11.0.226.13
typescript 4.9.4
```

One thing to note is that I only signed and issued the certificate myself, but did not import it into my CA.

**Comment by bartlomieju** [comment]
The crate we use for TLS (rustls) is rather picky about which certificates it supports. I think you might have to import it into your CA to make it happy.

**Comment by jiawei397** [comment]
I understand the need for prompt information, but my current situation is just that I am not comfortable looking at the prompt information on the console during local development.

My team members are currently sharing the certificate files used in the test. If they import the CA again, it may be more troublesome. Now we can only find a way to reduce these tips.

**Comment by jiawei397** [comment]
Local development uses [mkcert](https://github.com/FiloSottile/mkcert) to solve this problem, so close it. Everyone who need it can also use it , very good.
