### ISSUE TITLE
Migrate to ESLint

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#1824]
The TypeScript team announced a couple months ago that they were focusing internally on migrating to ESLint from tslint and then earlier this week tslint mentioned that they were deprecating tslint and joining forces with ESLint.

Therefore I think it only makes sense we migrate to ESLint.  It would also be a good point to re-evaluate our linting rules and ensure that we extend our rules based on ignoring anything that Prettier handles (currently there are a couple conflicts between Prettier and tslint we have to add ignore comments for).

**Comment by ry** [comment]
Do you have a link to that announcement ?

**Comment by kitsonk** [comment]
@ry https://medium.com/palantir/tslint-in-2019-1a144c2317a9

**Comment by ry** [comment]
Thanks. Yes I'm all for this.

**Comment by kitsonk** [comment]
cc/ @JamesHenry

Any thoughts on migration approach appreciated.

**Comment by j-f1** [comment]
Check out [our docs](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/ROADMAP.md) on equivalents for TSLint rules for some guidance.

**Comment by kitsonk** [comment]
@j-f1 any good standard configs you can recommend. I am not totally a fan of our current rules.

**Comment by j-f1** [comment]
We’ve got a `recommended` config (`plugin:@typescript-eslint/recommended`, rules are marked with a ✔️ [here](https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin#supported-rules)) for TypeScript-specific linting, and for general JS support, [Airbnb](https://github.com/airbnb/javascript) or the default `eslint:recommended` config are common options. I strongly recommend [Prettier](https://prettier.io) for linting formatting, and using [`eslint-plugin-prettier`](https://github.com/prettier/eslint-plugin-prettier) to disable any formatting rules in the other configs.

**Comment by balupton** [comment]
Perhaps https://discuss.bevry.me/t/how-bevry-automates-maintenance-of-its-prolific-open-source-portfolio/693?u=balupton and https://github.com/bevry/bevry-eslint-config would be useful as it detects the needs of the project and adapts the linting accordingly

**Comment by ry** [comment]
This was completed in #1905

**Comment by romainPrignon** [comment]
Hello :)
Is there any doc about eslint-typescript integration ?
I search on https://deno.land/manual.html and https://deno.land/manual.html and https://deno.land/style_guide.html but I found nothing :(

**Comment by JustFly1984** [comment]
Eslint plugin deno, and VSCode extension could be amazing!
