### ISSUE TITLE
Request: console.log without newline, prompt without extra space

### ISSUE THREAD

**Issue by nupanick** [denoland/deno#18254]
For creating console apps, most of the time `prompt` for input and `console.log` for output are perfectly fine, but it does feel like a sharp corner that there's no way to disable the automatic newlines and spaces at the end. In python you can pass an option argument to `print` to suppress the implicit newline, could we do that too? Something like

```deno
console.log("[status: ok] ", { newline: false });
const text = prompt(">", { space: false });
```

Currently the alternative is to either re-implement prompt and log via char-counting and buffers, or import a library that does.

**Comment by petamoriken** [comment]
Since `console.log` is defined in the [Console Standard](https://console.spec.whatwg.org/#log) and `prompt` is defined in the [HTML Standard](https://html.spec.whatwg.org/multipage/timers-and-user-prompts.html#dom-prompt), changing their interfaces would not be allowed.

**Comment by sigmaSd** [comment]
I think re-implementing prompt/log is not that bad
```js
const prompt2 = (promptString) => {
  Deno.stdout.writeSync(new TextEncoder().encode(promptString + " "));
  const b = new Uint8Array(512);
  const n = Deno.stdin.readSync(b);
  Deno.stdout.writeSync(b.slice(0, n));
};

prompt2("hello");
```

**Comment by dsherret** [comment]
We can't extend or change these interfaces in Deno because it would go against the standard.

> Currently the alternative is to either re-implement prompt and log via char-counting and buffers, or import a library that does.

This is what you'll need to do.
