### ISSUE TITLE
WIN11 Trunk Powershell Administrator Cargo Build Compile Issue (^^^^^^^ could not find `winuser` in `um`)

### ISSUE THREAD

**Issue by WingZer0o** [denoland/deno#18297]
As of this evening with the current Trunk version synced to my fork and a fresh clone and performing a `cargo build`, I was receiving the following error. 

```shell
PS C:\Code\Deno\deno> cargo build
   Compiling deno_runtime v0.101.0 (C:\Code\Deno\deno\runtime)
error[E0432]: unresolved import `winapi::um::winuser`
   --> runtime\permissions\prompter.rs:110:23
    |
110 |       use winapi::um::winuser::MapVirtualKeyW;
    |                       ^^^^^^^ could not find `winuser` in `um`

error[E0432]: unresolved import `winapi::um::winuser`
   --> runtime\permissions\prompter.rs:111:23
    |
111 |       use winapi::um::winuser::MAPVK_VK_TO_VSC;
    |                       ^^^^^^^ could not find `winuser` in `um`

error[E0432]: unresolved import `winapi::um::winuser`
   --> runtime\permissions\prompter.rs:112:23
    |
112 |       use winapi::um::winuser::VK_RETURN;
    |                       ^^^^^^^ could not find `winuser` in `um`
```

I was able to successfully compile after adding "winuser" to the features of winapi in `runtime/cargo.toml`. I'd be happy to submit a PR if this is an issue that is occurring outside of my enviroment.

![image](https://user-images.githubusercontent.com/114699222/226488902-8eb963cb-a905-446e-9be9-69069612cf89.png)

**Comment by dsherret** [comment]
I noticed this too. I have a fix for it here in an unrelated PR: https://github.com/denoland/deno/pull/18294/files#diff-6431a3eec6e102bbcffb94387cda89efbe02002649745273fb575234c0018de4R107
