### ISSUE TITLE
Deno needs a flag for Import not to error-check modules

### ISSUE THREAD

**Issue by backspaces** [denoland/deno#18295]
JavaScript in the browser does not check imports for environmental (ex: dom use in workers) errors. Deno, however, by default does. This creates problems for browser based code running in deno. We need a flag to skip this checking so that deno behaves like the browser.

Example: I have a large utilities file which includes both vanilla JS exports and dom exports. Many of the"apps" using this run in both workers and in the main thread even tho the utilities library uses the dom. This is possible because imports are not error-checked at load time, but naturally fail at run-time if a worker asks for a dom utility. 

Load-time checking would require duplicating the apps, one for workers, another for main thread browser apps.

I believe run-time failure is the standard, thus making this worker/main-thread sharing possible.

So when I run an app in deno that uses no dom utility, I still get:

```
error: Uncaught ReferenceError: document is not defined
       const can = document.createElement('canvas')
```
.. i.e. is  a load-time error rather than a run-time error.

I believe this may be common for devs wishing to run their modern JS apps in places other than the browser such as node, deno, bun and others.

Thus the need for an option for run-time errors rather than load-time pre-checking.

**Comment by nayeemrmn** [comment]
> ```
> error: Uncaught ReferenceError: document is not defined
>        const can = document.createElement('canvas')
> ```
> 
> 
>     
>   
> 
> .. i.e. is  a load-time error rather than a run-time error.

This is a runtime error, it's encountered when that line of code is executed. You would get the same error in a browser worker:
![image](https://user-images.githubusercontent.com/29990554/226484138-9c39c33f-4266-4773-a96b-7be33dd78fee.png)

**Comment by backspaces** [comment]
Wow, thanks for the fast response, very nice.

Maybe I wasn't detailed enough. 

First of all, the repo uses a Model/View split .. i.e. the Models never draw or use colors and so on, they are just data in/out

The utils.js file contains both vanilla JS exports as well as dom related ones like:
```
export function createCanvas(width, height) {
    const can = document.createElement('canvas')
    can.width = width
    can.height = height
    return can
}
```

.. and usually imported all together like: 
```
import * as util from '../src/utils.js'
```

And it is only called in the main thread by a View:
```
    const can = util.createCanvas(width, height)
```

.. If it was ever called in the worker, it would cause an error.

I know this works because my testing runs all the Models in workers for performance sake.

And I want to do a similar thing with deno: run just the Models in deno, not the Views, initially just outputting the data to the console or file after calling the Models 500 steps. Great for testing!

Thanks again for the response!

**Comment by nayeemrmn** [comment]
If you're seeing that error, the line of code shown in the error is definitely being executed in Deno's main thread meaning `util.createCanvas()` is being called somewhere. Can you show the stack trace beneath it?

**Comment by backspaces** [comment]
Hi! And thanks again.

Here's a deno test usage I have testing the 3D geometry of AgentScript, the repo I'm working on. If I swap out the complete utils.js (js & dom mixed) with a version that is js only, it works fine.

Is there a way for me to call deno to get a more complete stack trace?

I could build a simpler example to help dig further if you'd like.

```
master: deno test test/geom.js
Uncaught error from ./test/geom.js FAILED

 ERRORS 

./test/geom.js (uncaught error)
error: ReferenceError: document is not defined
    const can = document.createElement('canvas')
                ^
    at createCanvas (file:///Users/owen/Dropbox/src/agentscript/src/utils.js:225:17)
    at createCtx (file:///Users/owen/Dropbox/src/agentscript/src/utils.js:246:17)
    at file:///Users/owen/Dropbox/src/agentscript/src/utils.js:311:17
This error was not caught from a test and caused the test runner to fail on the referenced module.
It most likely originated from a dangling promise, event/timeout handler or top-level code.

 FAILURES 

./test/geom.js (uncaught error)

FAILED | 0 passed | 1 failed (38ms)

error: Test failed
```

Here's a run with the utils.js file with JS utils only, none of the dom utils:

```
master: deno test test/geom.js
running 6 tests from ./test/geom.js
reset ... ok (8ms)
heading pitch roll ... ok (6ms)
left & right ... ok (6ms)
tilt up & down ... ok (6ms)
roll right & left ... ok (5ms)
facexyz ... ok (7ms)

ok | 6 passed | 0 failed (89ms)
```

**Comment by backspaces** [comment]
I just proved Deno does indeed import without testing. So my-bad, sigh. Let me fix the problem the stack trace shows then I'll close this. And THANKS a LOT!

Here's the code proving deno is correctly importing etc:

test.js:
```
import * as util from './utils.js'

console.log('add', util.add(1, 2))
console.log(util)
const can = util.createCanvas(10, 10)
console.log(can)
```

utils.js:
```
export function createCanvas(width, height) {
    const can = document.createElement('canvas')
    can.width = width
    can.height = height
    return can
}

export function add(a, b) {
    return a + b
}
```

Running test.js shows the error occurs only when util.createCanvas is called. It even console logs the whole utils.js with no errors, i.e. it does not check the utils when logged.

> deno run test.js 
> add 3
> Module { add: [Function: add], createCanvas: [Function: createCanvas] }
> error: Uncaught ReferenceError: document is not defined
>     const can = document.createElement('canvas')
>                 ^
>     at Module.createCanvas (file:///Users/owen/Dropbox/src/agentscript/tests/denoimports/utils.js:2:17)
>     at file:///Users/owen/Dropbox/src/agentscript/tests/denoimports/test.js:5:18
>

**Comment by backspaces** [comment]
Sorry, wanted to comment: thanks a bunch and the lovely ??= stunt indeed was usefuil.
