### ISSUE TITLE
node: Deno.mainModule is not available in worker context, making "process.argv" throw

### ISSUE THREAD

**Issue by pasha-bolokhov** [denoland/deno#18305]
**Describe the bug**
Exporting "require()" or "createRequire()" stalls a child worker

**Steps to Reproduce**
Prepare the main program, and a child worker — use the sample from [Deno Workers](https://dotland-fresh.deno.dev/manual@v1.20.6/runtime/workers).
Then, add `import { createRequire } from "https://deno.land/std@0.133.0/node/module.ts";`
at the top of the child worker

Doing one of the following makes a child worker stall:
1. `export { createRequire };`
2. `export const require = createRequire(import.meta.url);`

**Comment by ayame113** [comment]
In the process of moving the node compatibility layer from std to CLI, I'm assuming this problem no longer exists because the way the `process` variable is initialized has changed?

```ts
// std@0.177.0
const code1 = `
import process from 'https://deno.land/std@0.177.0/node/process.ts';
console.log(process.argv[1]);
`;
new Worker(`data:text/javascript,${code1}`, { type: "module" }); // TypeError: Cannot read properties of undefined (reading 'startsWith')

// Deno 1.32.1 canary
const code2 = `
import process from 'node:process';
console.log(process.argv[1]);
`;
new Worker(`data:text/javascript,${code2}`, { type: "module" }); // output: undefined
```

Inside deno deploy you'll get an error because the import from `node:` isn't implemented yet, just wait for it to be available.

Personally, I feel like it's a bug that `process.argv` is `[]` in Worker, but it might be fine.

**Comment by pasha-bolokhov** [comment]
The code referenced by @ayame113
```typescript
const code = `import Knex from "npm:knex";`
new  Worker(`data:text/javascript,${code}`, { type: "module" });
```
still fails,
```
error: Uncaught (in worker "") TypeError: Cannot read properties of undefined (reading 'startsWith')
    at Array.get (ext:deno_node/process.ts:479:33)
    at Array.includes (<anonymous>)
    at Object.<anonymous> (file:///home/XXXXXXXX/.cache/deno/npm/registry.npmjs.org/colorette/2.0.19/index.cjs:33:46)
    at Object.<anonymous> (file:///home/XXXXXXXX/.cache/deno/npm/registry.npmjs.org/colorette/2.0.19/index.cjs:220:4)
    at Module._compile (ext:deno_node/01_require.js:958:34)
    at Object.Module._extensions..js (ext:deno_node/01_require.js:991:10)
    at Module.load (ext:deno_node/01_require.js:869:32)
    at Function.Module._load (ext:deno_node/01_require.js:705:12)
    at Module.require (ext:deno_node/01_require.js:891:19)
    at require (ext:deno_node/01_require.js:1031:16)
```
as per Deno 1.32.3

**Comment by voluntadpear** [comment]
Facing the same issue when trying to import a library that accesses a WebAssembly module through glue code emitted by Emscripten, also done through a Worker. I'm on Deno v1.36.2.
