### ISSUE TITLE
node: crypto.getCurves is missing

### ISSUE THREAD

**Issue by mdunisch** [denoland/deno#18302]
I want to use firebase admin with deno. So i startet with:

```javascript
import { getAuth } from "npm:firebase-admin/auth";
getAuth();
```
unfortunately that leads to this error:
`error: Uncaught Error: Not implemented: crypto.getCurves`.

The documentation dont give any hint that about a missing implementation: https://deno.land/std@0.166.0/node/crypto.ts?s=getCurves

**Steps to Reproduce**
`deno run --unstable --allow-env  --allow-read https://gist.githubusercontent.com/mdunisch/8824ad41948b7e2d4147503b11dbcd27/raw/0bc3c355ae279284f5cd46538b4635d450f60943/gistfile1.txt`

**Expected behavior**
I would love to use Deno but without having the node crypto functions it's impossible. Also please make it obvious in the documentation what is still missing

**Environment**
- OS: MacOS 13
- deno version: 1.28.2

**Comment by littledivy** [comment]
We're tracking all missing APIs from `node:crypto` in https://github.com/denoland/deno/issues/18455. Closing.
