### ISSUE TITLE
callback for `tls.connect` is bound to event which is never emitted

### ISSUE THREAD

**Issue by chaorace** [denoland/deno#18317]
Note how this callback is being bound to an event which is emitted nowhere else in the polyfill:
https://github.com/denoland/deno_std/blob/6f9e33341826821ba73593238bf0da7c515c30aa/node/_tls_wrap.ts#L332

In the baseline implementation, this event is emitted by the `onConnectSecure` function:
https://github.com/nodejs/node/blob/c3770536bcfb79fd2b562a861831eed369576b58/lib/_tls_wrap.js#L1524-L1586

It seems that the side-effects introduced by this function were overlooked when polyfilling the file due to differences in the underlying plumbing. For now (until the implementation becomes more accurate) we can probably get away with inserting the baseline's happy-path code as-is starting at line 367 in the `_tls_wrap.ts` polyfill:
```
this.authorized = true;
debug('client emit secureConnect. authorized:', this.authorized);
this.secureConnecting = false;
this.emit('secureConnect');
```

**Comment by satyarohith** [comment]
The secureConnect event is emitted since https://github.com/denoland/deno/issues/17724
 https://github.com/denoland/deno/blob/5e2a747685490b31efa778241fccf938bd33722d/ext/node/polyfills/_tls_wrap.ts#L311-L314
