### ISSUE TITLE
node: http(s).globalAgent is missing

### ISSUE THREAD

**Issue by Tyrone** [denoland/deno#18312]
When I quote npm inclusion as below:
var useSSL = endpoint.protocol === 'https:';
     var http = require('https');
     if (httpOptions.maxSockets) {
       http.globalAgent.maxSockets = httpOptions.maxSockets;
     } else {
       http.globalAgent.maxSockets = 300;
     }

Show: Cannot set properties of undefined (setting 'maxSockets')

I have seen: https://deno.land/std@0.166.0/node/https.ts?source
Legal definition: export const globalAgent = undefined;

Not this: export const globalAgent = new Agent();

**Comment by jcbhmr** [comment]
This notably prevents https://www.npmjs.com/package/@actions/http-client from working due to https://github.com/actions/toolkit/blob/c5c786523e095ca3fabfc4d345e16242da34e108/packages/http-client/src/index.ts#L651 causing a "cannot read property of undefined" error.
