### ISSUE TITLE
node polyfill for vm.runInContext using web workers

### ISSUE THREAD

**Issue by JumpLink** [denoland/deno#18319]
**Is your feature request related to a problem? Please describe.**

I would like to use JSDom for SSR on Deno. I can't use JSDom directly without its own global context, because I want to run a browser script on it. For that it needs to have an environment for the script where all global browser methods are available, for example window, dom, etc and for security.

**Describe the solution you'd like**

A polyfill for `runInContext` or a Deno native API for running a script file or script string in a sandbox with it's own context and executing it.

I can try to implement this, my approach would be to use the web worker for this, but I would have liked to hear your opinion beforehand. Do you think using web workers for that would be a possible and clean solution?

**Describe alternatives you've considered**

An alternative I tried was to run the script using `Deno.run({ cmd: ['deno', ...] })`, but that had too long loading times and it is difficult to pass the context to it or to communicate with the script. With web workers you could at least use postMessage

**Comment by birkskyum** [comment]
there was an update on this in discord
<img width="737" alt="Screenshot 2023-12-30 at 11 04 31" src="https://github.com/denoland/deno/assets/74932975/87a18156-1115-4c64-9dd0-abe176abc40b">
