### ISSUE TITLE
compat: tracking issue for `npm:json-server`

### ISSUE THREAD

**Issue by kt3k** [denoland/deno#18325]
Running [json-server](https://www.npmjs.com/package/json-server) cli doesn't work now.
```
deno run -A --unstable npm:json-server --host 0.0.0.0 --port 8000 db.json
```

The above command needs db.json, for example:

```json
{
  "posts": [
    { "id": 1, "title": "json-server", "author": "typicode" }
  ],  
  "comments": [
    { "id": 1, "body": "some comment", "postId": 1 } 
  ],  
  "profile": { "name": "typicode" }
}
```

Issues:
- [ ] `TypeError: Cannot read properties of undefined (reading 'remoteAddress')` at `forwarded/0.2.0/index.js:49:22` (when accessing `http://localhost:8000/posts`)
- [ ] `TypeError: this._implicitHeader is not a function` at `compression/1.7.4/index.js:84:14` (when accessing `http://localhost:8000/`)

**Comment by bartlomieju** [comment]
@kt3k is this issue still relevant?

**Comment by kt3k** [comment]
Looks like both issues still existing. I'll work on them.
