### ISSUE TITLE
Panic in deno fmt

### ISSUE THREAD

**Issue by langston-barrett** [denoland/deno#18338]
This is a fuzzed bug. Please feel free to close if you're not interested in bugs found by fuzzers. If you would like me to report more such bugs, please let me know.

Built from 7e61e8f0e0abbf8cbd1a8c2ea21cee9ff11403c2
```
Platform: linux x86_64
Version: 1.31.3
Args: ["/work/target/release/deno", "fmt", "test.js"]
```
```js
try {

                } catch (e) {
  with({}) {  // With scope inside catch scope.


  }
}
```

**Comment by dsherret** [comment]
This is a debug only panic that doesn't occur in release mode. I'm going to close this one here and track it in dprint-plugin-typescript.
