### ISSUE TITLE
Add import.meta.main

### ISSUE THREAD

**Issue by ry** [denoland/deno#1834]
Currently we can use `import.meta.url == window.location.toString()` to test if a given script is the main script... Similar to `require.main == module` in Node.

But `import.meta.url == window.location.toString()` is quite a bit to type, and `import.meta` is allowed to be extended... https://github.com/tc39/proposal-import-meta

I'd like to add `import.meta.main`, a boolean, as a short hand to decide if a module is the main.

**Comment by bartlomieju** [comment]
I'm in, to be honest `runIfMain` from `deno_std` is kinda superfluous...
```ts
if (import.meta.main) {
    doSomething();
}
```
Super clean and simple. 

Can I work on that?

**Comment by ry** [comment]
Yes - here are some references to get started:
import.meta is primearally defined in libdeno:
https://github.com/denoland/deno/blob/e109941bd256b276ea3a68717bf519a5b3a08ff1/libdeno/binding.cc#L507-L524
The typescript declarations are (inappropriately) in js/lib.web_assembly.d.ts
https://github.com/denoland/deno/blob/e109941bd256b276ea3a68717bf519a5b3a08ff1/js/lib.web_assembly.d.ts#L165-L168
