### ISSUE TITLE
BrokenPipe during piping to subprocces stdin

### ISSUE THREAD

**Issue by shevernitskiy** [denoland/deno#18389]
I got an error during piping to subprocces stdin.
Here is an example
```ts
function encodeFile(source: ReadableStream<Uint8Array>, dest: string, ffmpeg_bin: string): Promise<void> {
  const cmd = new Deno.Command(ffmpeg_bin, {
    args: ["-i", "pipe:0", "-loglevel", "panic", "-c", "copy", "-t", "00:00:09", "-y", "-an", dest],
    stdin: "piped",
  });
  const proc = cmd.spawn();
  await source.pipeTo(proc.stdin);
  await proc.stdin.close();
  await proc.status;
}

const file = Deno.openSync("./out.mp4", { read: true });
await encodeFile(file.readable, "./enc.mp4", "./bin/ffmpeg.exe");
file.close()
```

I had destination file `enc.mp4` in the end, but deno emit an error.
```sh
error: Uncaught (in promise) BrokenPipe: Идет закрытие канала. (os error 232)
    at async Object.write (internal:deno_web/06_streams.js:906:9)
```

deno 1.31.1 (release, x86_64-pc-windows-msvc)
v8 11.0.226.13
typescript 4.9.4

**Comment by sigmaSd** [comment]
it seems like pipeTo closes automatically both the source and the destination, so in you example file and proc.stdin are already closed after pipeTo, so you can't close them again

This is my guess though, I didn't check the code

**Comment by sigmaSd** [comment]
You can make it not close the destination with preventClose option `source.pipeTo(proc.stdin,  { preventClose: true, preventCancel });`

**Comment by shevernitskiy** [comment]
> You can make it not close the destination with preventClose option `source.pipeTo(proc.stdin, { preventClose: true, preventCancel });`

yeah, i though about it as well.. tried all prevent options, but t didn't help

**Comment by sigmaSd** [comment]
preventClose does fix the error you mention

But wont stop the file from being closed automaticly so the next error you'll hit is in file.close()

**Comment by shevernitskiy** [comment]
It's seem so.. thanks for the answer!
