### ISSUE TITLE
Typescript not working on type imported from module imported with npm: specifier

### ISSUE THREAD

**Issue by martinjeromelouis** [denoland/deno#18380]
I work under vscode version 1.76.2.

I have the following simple essai.ts file. I know this code does not work but I tried to isolate the issue and made the code as small as possible.

```
// @deno-types="npm:@types/imapflow@^1.0.11"
import { ImapFlow } from 'npm:imapflow@1.0.121';

const client = new ImapFlow({
    host: 'imap.gmail.com',
    port: 993,
    secure: true,
    auth: {
        user: 'xxxx@gmail.com',
        pass: 'yyy',
    },
});

const { meta: { filename }, content } = await client.download(
    '*',
    '2.2',
);
```

If I now hover over the variable 'content', it says:'const content : any' (see attached picture) whereas content should be of type ReadableStream:

![image](https://user-images.githubusercontent.com/32217468/227139491-1940e047-bfda-41fb-90f8-9b53c6081b1a.png)

To solve that issue, I now hover over the 'client' variable and right-click to 'Go to type definition'.
In the start of the file that opens in the cache, there is this line:

`export type Readable = import('stream').Readable;`

If I hover over the Readable type, it says: 'type Readable = any'.

Now I replace that line by :

`export type Readable = import('node:stream').Readable;`

I don't even save the file. I just hover over the type 'Readable'. It now says: 'type Readable = internal.Readable'.
I close this file without saving it.

If I now return to my essai.ts file and hover over the 'content' variable, it says:''const content : internal.Readable' which is correct.

It looks as if Typescript didn't know the IMapFlow library has been imported with the npm:specifier.

**Comment by dsherret** [comment]
You can fix this by adding the following to the top of your code:

```ts
/// <reference types="npm:@types/node" />
```

When you see something like this, try running it through `deno check` with the `--all` flag to surface diagnostics within the npm package.

```
> deno check --all main.ts
Check file:///V:/scratch/main.ts
error: TS2580 [ERROR]: Cannot find name 'Buffer'.
        content: string | Buffer,
                          ~~~~~~
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/@types/imapflow/1.0.12/index.d.ts:29:27

TS2580 [ERROR]: Cannot find name 'Buffer'.
    source: Buffer;
            ~~~~~~
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/@types/imapflow/1.0.12/index.d.ts:203:13

TS2580 [ERROR]: Cannot find name 'Buffer'.
    bodyParts: Map<string, Buffer>;
                           ~~~~~~
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/@types/imapflow/1.0.12/index.d.ts:213:28

TS2580 [ERROR]: Cannot find name 'Buffer'.
    headers: Buffer;
             ~~~~~~
    at file:///C:/Users/david/AppData/Local/deno/npm/registry.npmjs.org/@types/imapflow/1.0.12/index.d.ts:214:14

Found 4 errors.
```

In this case, it's not finding the `Buffer` global is not found, which is a type found in the `@types/node` package.

I've opened up two issues to help improve this in the future:

1. https://github.com/denoland/deno/issues/18385 - This would cause this to automatically work in the future
2. https://github.com/denoland/deno/issues/18386

**Comment by martinjeromelouis** [comment]
Hi,

thanks again for your precious help. It does solve my problem.
