### ISSUE TITLE
Add support for "Deno.upgradeHttpRaw" in "Deno.serveHttp" API

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#18397]
Currently the unstable `Deno.upgradeHttpRaw` only works with unstable `Deno.serve` API. Because of that, our polyfill for `node:http` relies on the unstable `Deno.serve` API, which has many stability issues related to it.

If we were able to add support for `Deno.upgradeHttpRaw` with `Deno.serveHttp` API, we could replace implementation of `node:http` to use more stable `Deno.serveHttp` API - and in the future we might even remove Flash server completely and make `Deno.serve` a convenient wrapper around `Deno.serveHttp`.

The problem is that `hyper` that we use for `Deno.serveHttp` API, doesn't have a public API to do "raw upgrades" - ie. Hyper only has [`OnUpgrade`](https://docs.rs/hyper/latest/hyper/upgrade/struct.OnUpgrade.html), which returns a future that resolves after we return a proper response. 

However, in case of `node:http` API, we need a way to let the user code construct the response and return it at some point in the future:

https://github.com/denoland/deno/blob/09ddb35265f67a89383a8bd614224adb455d1e0c/ext/node/polyfills/http.ts#L755-L763

Docs for `upgrade` event:
https://nodejs.org/api/http.html#event-upgrade

**Comment by lucacasonato** [comment]
This shouldn't be insurmountable - one needs to add a replay wrapper around the underlying I/O. We must additionally ensure that `Deno.upgradeHttpRaw` can only be called on H1 connections.

**Comment by bartlomieju** [comment]
Done in https://github.com/denoland/deno/commit/3cd7abf73fa104526508984daef54bbb8e120310
