### ISSUE TITLE
TypeScript: Set `useUnknownInCatchVariables` to `true` by default (like in vanilla TS)

### ISSUE THREAD

**Issue by jsejcksn** [denoland/deno#18398]
[According to the manual](https://deno.land/manual@v1.32.0/advanced/typescript/configuration#how-deno-uses-a-configuration-file) — by default — the compiler option [`strict`](https://www.typescriptlang.org/tsconfig#strict) is [set to `true`](https://deno.land/manual@v1.32.0/advanced/typescript/configuration#how-deno-uses-a-configuration-file:~:text=strict,-true), and the option [`useUnknownInCatchVariables`](https://www.typescriptlang.org/tsconfig#useUnknownInCatchVariables) is currently [set to `false`](https://deno.land/manual@v1.32.0/advanced/typescript/configuration#how-deno-uses-a-configuration-file:~:text=useUnknownInCatchVariables,-false).

That manual page also shows an example of [what an implied `tsconfig.json` looks like](https://deno.land/manual@v1.32.0/advanced/typescript/configuration#what-an-implied-tsconfigjson-looks-like) — which doesn't currently depict the state of this relationship, but that's not the focus of this issue...

The TSConfig reference includes this documentation:

> ## [`useUnknownInCatchVariables`](https://www.typescriptlang.org/tsconfig#useUnknownInCatchVariables)
> 
> In TypeScript 4.0, support was added to allow changing the type of the variable in a catch clause from `any` to `unknown`. Allowing for code like:
> 
> ```ts
> try {
>   // ...
> } catch (err) {
>   // We have to verify err is an
>   // error before using it as one.
>   if (err instanceof Error) {
>     console.log(err.message);
>   }
> }
> ```
>
> This pattern ensures that error handling code becomes more comprehensive because you cannot guarantee that the object being thrown is a Error subclass ahead of time. With the flag `useUnknownInCatchVariables` enabled, then you do not need the additional syntax (`: unknown`) nor a linter rule to try enforce this behavior.
> 
> ---
>
> **Default:**
> `true` if [`strict`](https://www.typescriptlang.org/tsconfig#strict), `false` otherwise.
> 
> Related:
> [`strict`](https://www.typescriptlang.org/tsconfig#strict)
> 
> Released:
> [4.4](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-4.html)

Here are two links to the TS playground comparing the two behaviors (based on the code above):

- [enabled (`true`)](https://www.typescriptlang.org/play?useUnknownInCatchVariables=true#code/C4JwngBA3gUBEGMD2A7AzsCSBGArCAvNHPBAOYCmmAthWmgIaUAUAlMaacABYhIDuEFBUEBREHxDMARADkkmHhQgUJSEBDBIArgHIQygDZIkAawCWKMhABm66awDcJeAF8ANCVfP4PPoJxcZ1dEBmAEbghmBAZtNAp2WE5SAHoUgD0AfhgSNIgAdWVuBgA3ZWAkCDKQcxtIGLjlczQIBhQVNQ1sCjsDCDjLa3NMBhbUCgA6ElqohviISww2hAokGwhxSUSXRFQ0JENJ4zJo2PiJ2nomBJ8IEIpDeaTSZHQDo6QTuQUING0+-jFTD8ZQNMjcTBgKgALgct3gr32hwmx1OjQudEYlCcEDyABUAMqhcLcOgQHjNCDUZrABimCheGCuGBAA)
- [disabled (`false`)](https://www.typescriptlang.org/play?useUnknownInCatchVariables=false#code/C4JwngBA3gUBEGMD2A7AzsCSBGArCAvNHPBAOYCmmAthWmgIaUAUAlMaacABYhIDuEFBUEBREHxDMARADkkmHhQgUJSEBDBIArgHIQygDZIkAawCWKMhABm66awDcJeAF8ANCVfP4PPoJxcZ1dEBmAEbghmBAZtNAp2WE5SAHoUgD0AfhgSNIgAdWVuBgA3ZWAkCDKQcxtIGLjlczQIBhQVNQ1sCjsDCDjLa3NMBhbUCgA6ElqohviISww2hAokGwhxSUSXRFQ0JENJ4zJo2PiJ2nomBJ8IEIpDeaTSZHQDo6QTuQUING0+-jFTD8ZQNMjcTBgKgALgct3gr32hwmx1OjQudEYlCcEDyABUAMoQAAmSDoKF0mBi4UiPGaEGozWADFMFGhAAK2gpuKoVAAPFYAB2A5lQCxafgE7R5BgAhF4YK4YEA)

As the documentation describes: this feature is enabled by default when `strict` is enabled, but **that's not currently the case in Deno** — and, as the code in the playground links demonstrate, this feature is useful in providing better type safety in `catch` blocks — helping prevent further potential exceptions.

I would like to see Deno set this compiler option to `true` by default, just like vanilla TS does — and have better type safety in `catch` blocks.

**Comment by nayeemrmn** [comment]
Duplicate of #11826. It was implemented once in #12547 but reverted in #12643. There's a strong argument for enabling it again since we no longer report type checking errors in dependencies, as was referenced in the reverting PR. Would have been nice to time with the TS 5.0 upgrade... but I think any minor version is acceptable.

**Comment by jsejcksn** [comment]
Thanks @nayeemrmn — I didn't find that one before posting, so I'll close this issue.
