### ISSUE TITLE
Feature Request: Importing a `js` file could fall back to `ts` file in a `ts` file

### ISSUE THREAD

**Issue by Conaclos** [denoland/deno#18390]
### Discussed in https://github.com/denoland/deno/discussions/18293

<div type='discussions-op-text'>

<sup>Originally posted by **Conaclos** March 20, 2023</sup>
Hi!

One thing that prevents me from using _Deno_ for my TypeScript projects is the incompatibility of Deno with other tools. in particular _ESbuild_ and _TSC_.

I use _ESbuild_ and _TSC_ to transpile my projects for npm and the browser. ESbuild and TSC do not change the extension of import paths. That's mean we have to use js extension to import a TypeScript file.

It could be nice to implement a very simple resolution strategy for _Deno_: in a TypeScript file (file ending with ts extension): an import path ending with a _js_ extension is resolved to the same file, but ending with a ts extension if the _js_ file does not exist.

```ts
// a.ts
import * as b from "./b.js" // resolves to "./b.js" or "./b.ts" if "./b.js" does not exist
...
```

</div>

**Comment by dsherret** [comment]
TypeScript now allows `.ts` extensions:

https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#allowarbitraryextensions

Also, please see https://github.com/lucacasonato/esbuild_deno_loader for Deno's esbuild loader.

**Comment by kibertoad** [comment]
@dsherret That doesn't seem to help at all for cases when you are using .js extension in a TS project (which is the only supported way of doing ESM in a Node TS project). Maybe this issue could be reopened to discuss a proper solution for this case?

**Comment by BlackAsLight** [comment]
> That doesn't seem to help at all for cases when you are using .js extension in a TS project (which is the only supported way of doing ESM in a Node TS project). Maybe this issue could be reopened to discuss a proper solution for this case?

@kibertoad but this isn't a Node TS project. It would be a Deno TS project, where using .ts file extensions is supported with ESM, so why would you be using .js?

**Comment by kibertoad** [comment]
@BlackAsLight For backwards compatibility reasons. If same code could be executed both in Node and in Deno, it's a win for the Deno ecosystem, as it smoothes the migration/adoption curve.

**Comment by BlackAsLight** [comment]
> For backwards compatibility reasons. If same code could be executed both in Node and in Deno, it's a win for the Deno ecosystem, as it smoothes the migration/adoption curve.

Personally not a fan. I think it would be better for something like JSR to handle (don't know if it does). Switching the file extensions when migrating your code from node to Deno, at least with vscode, is quite fast. 

Your same argument could be used to "why not make Deno exactly like node, it would make the adoption so much easier and the backwards compatibility would be great". Many things about node are not desirable and I'd argue this is one of them. While I do support the idea of a smooth transition from node to Deno, I think this would add unnecessary junk into the Deno runtime.

**Comment by dsherret** [comment]
Some people in here maybe looking for the non-standard `--unstable-sloppy-imports` flag.

https://docs.deno.com/runtime/manual/tools/unstable_flags#--unstable-sloppy-imports

**Comment by kibertoad** [comment]
@dsherret Nice, this is super helpful! Performance impact warning is also useful, as it gently nudges people switching from Node to migrate to proper Deno syntax

**Comment by mb21** [comment]
`tsc` 5.7 also finally has the [`--rewriteRelativeImportExtensions` option](https://www.typescriptlang.org/tsconfig/#rewriteRelativeImportExtensions)
