### ISSUE TITLE
[feat] builtin version management

### ISSUE THREAD

**Issue by loynoir** [denoland/deno#18406]
### Description
- `deno --version 1.30.3 run -A reproduce.mjs` means run reproduce.mjs with deno version1.30.3 
- `deno --version 1.32.1 run -A reproduce.mjs` means run reproduce.mjs with deno version1.32.1

### Why
- Good for repdroducing work
- Good for repdroducing issue
https://github.com/denoland/deno/issues/18405

**Comment by ry** [comment]
We have “deno upgrade —version”
I don’t think it needs to be further baked in.
