### ISSUE TITLE
`deno upgrade` permission check should check cliOptionOutput

### ISSUE THREAD

**Issue by loynoir** [denoland/deno#18411]
### Actual
```sh
$ deno upgrade --version 1.30.3 --output ./deno_1_30_3
error: You don't have write permission to /usr/bin/deno because it's owned by root.
Consider updating deno through your package manager if its installed from it.
Otherwise run `deno upgrade` as root.
```

Workaround
```shj
$ sudo deno upgrade --version 1.30.3 --output ./deno_1_30_3
Downloading https://github.com/denoland/deno/releases/download/v1.30.3/deno-x86_64-unknown-linux-gnu.zip
...
```

### Expected
deno upgrade should permission check `./deno_1_30_3` instead of `/usr/bin/deno`

### Related
https://github.com/denoland/deno/issues/18405
https://github.com/denoland/deno/issues/18406
https://github.com/denoland/deno/issues/18438
https://github.com/denoland/deno/issues/18440

**Comment by dsherret** [comment]
Thanks! The incorrect code is here:

https://github.com/denoland/deno/blob/d740a9e43dad5b3824c3ff2f4aa66cc57a1db185/cli/tools/upgrade.rs#L267-L286

**Comment by dsherret** [comment]
Reopining because the fix was reverted in #18467. We need to not error when the output path doesn't exists.

**Comment by RyanClementsHax** [comment]
Is this still a good first issue? I'm looking to help out somewhere

**Comment by itsajay1029** [comment]
Can I work on this @dsherret ? Pls assign it to me
