### ISSUE TITLE
fetch failure in a dynamically moduled module

### ISSUE THREAD

**Issue by backspaces** [denoland/deno#18422]
Background: I have a models/ dir in my repo's top level containing 23 models/modules. 
I want to import them into deno to run 500 steps then report the model state. 
This would replace the current test as a far simpler one, a Good Thing!
The test program first gets the names of all the modules then dynamically imports them, one at a time, for testing.

This works brilliantly, except when one of the models uses fetch for data that it needs.
Here is a very simplified test of this approach, run in the repo top level, after a deno upgrade

```
// deno run -A models/denotest.js
const modelsDir = 'models/'

console.log('cwd', Deno.cwd())
Deno.chdir(modelsDir)
console.log('cwd', Deno.cwd())

// const model = await import('./AntsModel.js') // works, no use of fetch
const model = await import('./CountiesModel.js') // fails in fetch
console.log(model)
```

It produces:
```
// deno run -A models/denotest.js
cwd /Users/owen/Dropbox/src/agentscript
cwd /Users/owen/Dropbox/src/agentscript/models
error: Uncaught (in promise) TypeError: Invalid URL: './data/nmcounties.json'
const counties = await fetch('./data/nmcounties.json').then(resp => resp.json())
                       ^
    at getSerialization (ext:deno_url/00_url.js:74:11)
    at opUrlParse (ext:deno_url/00_url.js:65:10)
    at new URL (ext:deno_url/00_url.js:368:27)
    at new Request (ext:deno_fetch/23_request.js:323:25)
    at ext:deno_fetch/26_fetch.js:418:27
    at new Promise (<anonymous>)
    at fetch (ext:deno_fetch/26_fetch.js:414:18)
    at file:///Users/owen/Dropbox/src/agentscript
```

.. the ./data/nmcounties.json file is in the models/ dir and is correctly used elsewhere.

This also gets the same error: simply importing the model within the models/ dir:
```
// deno run -A models/denotest.js
// import model from './AntsModel.js' // works
import model from './CountiesModel.js' // fails
console.log(model)
error: Uncaught TypeError: Invalid URL: './data/nmcounties.json'
const counties = await fetch('./data/nmcounties.json').then(resp => resp.json())
                       ^
    at getSerialization (ext:deno_url/00_url.js:74:11)
    at opUrlParse (ext:deno_url/00_url.js:65:10)
    at new URL (ext:deno_url/00_url.js:368:27)
    at new Request (ext:deno_fetch/23_request.js:323:25)
    at ext:deno_fetch/26_fetch.js:418:27
    at new Promise (<anonymous>)
    at fetch (ext:deno_fetch/26_fetch.js:414:18)
    at file:///Users/owen/Dropbox/src/agentscript/models/CountiesModel.js:5:24

```

**Comment by bartlomieju** [comment]
You can use `import.meta.resolve()` to resolve path relative to the module you are calling from.

**Comment by backspaces** [comment]
Hi, thanks for responding!

So we're assuming deno couldn't find the fetch data due to an ambiguous url? It works in node I believe. But that's OK as long as it doesn't need to be in the repo's modules, just the workflow.

Er..but how do I use this??

And then should this issue become a documentation issue?

Tnx!

**Comment by backspaces** [comment]
OK, after several tests with import.meta, if I edit the model module to use:
```
const dataurl = import.meta.resolve('./data/nmcounties.json')
const counties = await fetch(dataurl).then(resp => resp.json())
```
..I no longer get the error from deno, i.e. it works .. in deno and hopefully everyplace else.

And we don't know why it doesn't work in deno when it runs in the browser, workers, and node.

Is there a way to fix the problem? I suspect it has to do with deno's implementation of fetch?

And when do I use it? Every place there is a relative url other than top level imports i.e. dynamic imports and fetch? Or possibly a reasonable bias towards absolute urls. BTW: Did you know import.meta is not an ecmascript feature?

Anyway, let's discuss this further and see if there is a sweet-spot for a fix in deno, and I'll look at integrating import.meta. I spoke to our dev team and they're interested too.

Thanks!

Background: I have a code base that works:
- in browsers
- in workers
- in scripts using Node
- in tests using Puppeteer
- in Leaflet and maplibre (GIS)
- in Three,js
.. and so on. 

They are part of a carefully designed Model/View split.  I.e. the models know nothing about the browser, that's for the views. By doing this, our team is able to integrate models in a huge number of frameworks. It's working on cell towers in California for goodness sake!

And so I wanted to add Deno to the list. But it looks like I first need to look into relative urls and find a universal fix working with all the above.

**Comment by aapoalas** [comment]
`import.meta` is definitely in the ECMAScript spec:
* [ECMAScript](https://tc39.es/ecma262/multipage/ecmascript-language-expressions.html#prod-ImportMeta)
* [HTML Standard](https://html.spec.whatwg.org/multipage/webappapis.html#hostgetimportmetaproperties)
* [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import.meta)

That being said, you can avoid using `import.meta.resolve()` by using the "more manual" `new URL("./relative", import.meta.url)`, which I believe should work everywhere.

However, I'm wondering if `fetch("./relative")` not working in Deno is still fully a bug. Since it works in the browser etc, it definitely sounds like it should work here as well.

**Comment by bartlomieju** [comment]
Sorry @backspaces I misunderstood the problem. This is actually expected behavior - that would work fine if you were running remote files, but since they are local files, there is no default "location" to resolve the relative URL passed to `fetch`. You can use `--location` flag to specify the "base URL" for all relative fetch calls.

**Comment by backspaces** [comment]
Hi! And Interesting. And scary too?

So *any* relative url is at risk? And we face these primarily with fetch() and import() .. and workers too. Sigh.

This has driven me to reading Deno's docs more deeply. God! Extraordinarily well written and clean architecture. I bow to the team!

**Comment by bartlomieju** [comment]
> Hi! And Interesting. And scary too?
> 
> So _any_ relative url is at risk? And we face these primarily with fetch() and import() .. and workers too. Sigh.

Dynamic `import()`s don't have this limitation - they are always imported from some module which becomes the "referrer" and the relative URLs are resolver relative to that module.

> This has driven me to reading Deno's docs more deeply. God! Extraordinarily well written and clean architecture. I bow to the team!

Thank you!

**Comment by backspaces** [comment]
I guess the key issue here is compatibility: does Deno wish to be 100% compatible with browsers? .. or would it be fine to not be fully browser compatible?

I rather like use of import.meta and the team I work with agree that it is an issue with their code and feel that being more precise with relative urls is a good thing.

I've recently done more work with the meta.import feature, running in workers, both browser and Deno. 

I'll close this now, the fix does not break any of my extensive testing and seems reasonable.

**Comment by backspaces** [comment]
Oh, and thank you all for all the help!
