### ISSUE TITLE
Node compat: Not implemented: crypto.hkdf

### ISSUE THREAD

**Issue by Jakob5358** [denoland/deno#18423]
Now that crypto.createSecretKey is implemented (Thanks littledivy 👍), I tried running my sveltekit project again using deno. This time I'm getting another error from the authjs npm package:
`Error: Not implemented: crypto.hkdf`
It seems to stem from `ext/node/polyfills/internal/crypto/hkdf.ts` file.

I don't know alot about crypto algorithms, but it seems some kind of hdkf is already implemented for deno, perhaps that could be used under the hood? You'll have to decide.

**Comment by littledivy** [comment]
We're tracking all missing APIs of node:crypto in https://github.com/denoland/deno/issues/18455. Closing.
