### ISSUE TITLE
`Deno.inspect` option `showHidden: true` seems to be ignored

### ISSUE THREAD

**Issue by jsejcksn** [denoland/deno#18435]
- Incidentally discovered in: https://github.com/denoland/deno/issues/16408#issuecomment-1290150199
- Potentially related: https://github.com/denoland/deno/issues/11486

[`Deno.inspect`](https://deno.land/api@v1.32.1?s=Deno.inspect) can be used to serialize a value for display (e.g. in the console).

There is an option [`Deno.InspectOptions.showHidden`](https://deno.land/api@v1.32.1?s=Deno.InspectOptions#prop_showHidden) which is described by the documentation this way:

> Show an object's non-enumerable properties.

Given an object with non-enumerable properties, I expected that I could invoke the function like this:

```ts
Deno.inspect(obj, { showHidden: true })
```

and see the non-enumerable property entries serialized in the resulting string. However, that option seems to be ignored.

Here's an example for reproduction in Deno and Node.js, with outputs from `console.log`'s built-in serializer for comparison:

`inspect_hidden.mjs`:
```js
const inspectorMap = {
  deno: () => ({
    serializer: "Deno.inspect",
    inspectHidden: (value) =>
      Deno.inspect(value, { colors: true, showHidden: true }),
  }),
  node: async () => {
    const { inspect } = await import("node:util");
    return {
      serializer: "node:util.inspect",
      inspectHidden: (value) =>
        inspect(value, { colors: true, showHidden: true }),
    };
  },
  unknown: () => ({
    serializer: "String",
    inspectHidden: (value) => String(value),
  }),
};

const runtime = typeof globalThis?.Deno?.inspect === "function"
  ? "deno"
  : typeof globalThis?.process?.versions?.node === "string"
  ? "node"
  : "unknown";

const { serializer, inspectHidden } = await inspectorMap[runtime]();

for (
  const descriptor of [
    { value: "bar" },
    { enumerable: true, value: "bar" },
  ]
) {
  const obj = {};
  const prop = "foo";
  Object.defineProperty(obj, prop, descriptor);

  console.log();
  console.log(
    `${prop} is enumerable:`,
    Object.getOwnPropertyDescriptor(obj, prop).enumerable,
  );

  console.log("serializer:", "console.log");
  console.log(obj);

  console.log("serializer:", serializer);
  console.log(inspectHidden(obj));
}

```

Here's the output when running in Deno:
```
% deno --version
deno 1.32.1 (release, aarch64-apple-darwin)
v8 11.2.214.9
typescript 5.0.2

% deno run inspect_hidden.mjs

foo is enumerable: false
serializer: console.log
{}
serializer: Deno.inspect
{}

foo is enumerable: true
serializer: console.log
{ foo: "bar" }
serializer: Deno.inspect
{ foo: "bar" }

```

Here's the output when running in Node:
```
% node --version
v18.15.0

% node inspect_hidden.mjs

foo is enumerable: false
serializer: console.log
{}
serializer: node:util.inspect
{ [foo]: 'bar' }

foo is enumerable: true
serializer: console.log
{ foo: 'bar' }
serializer: node:util.inspect
{ foo: 'bar' }

```

As can be seen in the outputs:

- Deno does not serialize the non-enumerable property `foo` when using `{ showHiden: true }`

- Node.js does — although I think it's odd that it prints the property name surrounded by brackets because — in source code — that indicates a [computed property name](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer#computed_property_names), so it suggests that `foo` is a variable and not a string

This seems like a bug to me.

**Comment by jsejcksn** [comment]
I could be off-base (I only did a quick search into the source), but I think one issue could be the use of the `ObjectKeys` function here:

https://github.com/denoland/deno/blob/fe88b53e50034e185246e03be586c470ca4fbf78/ext/console/02_console.js#L1186

which GitHub's symbols panel shows to be defined here:

https://github.com/denoland/deno/blob/fe88b53e50034e185246e03be586c470ca4fbf78/ext/node/polyfills/_stream.mjs#L10

specifically:
```js
ObjectKeys(e){return Object.keys(e)}
```

Ref: [`Object.keys()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/keys), which:

> returns an array of a given object's **own**, **enumerable** string-keyed property names

**Comment by jsejcksn** [comment]
Also, I didn't explicitly mention _own_ vs _inherited_ properties — but neither does the option description.

If "own" is currently implied, I think the description should revised to explicitly include it:

Current:
> Show an object's non-enumerable properties.

Proposed:
> Show an object's **own**, non-enumerable properties.


However, I recognize that it might make sense to intentionally omit it — in the case that another option should control display of inherited properties (e.g. `showInherited`), but I don't currently find anything like that.

Is there any way to output all inherited properties for a value using `Deno.inspect`?

**Comment by crowlKats** [comment]
Closing as solved by #18691

**Comment by jsejcksn** [comment]
@crowlKats Can we somehow address the second list item in my original post, at the end of the message?

> - … it prints the property name surrounded by brackets because — in source code — that indicates a [computed property name](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer#computed_property_names), so it suggests that `foo` is a variable and not a string

**Comment by crowlKats** [comment]
Oh my bad, I missed that. could you open a separate issue? I'll look into it, though probably has to wait for after the 1.39 release
