### ISSUE TITLE
language server errors on go-to-definition for localhost url

### ISSUE THREAD

**Issue by tjjfvi** [denoland/deno#18460]
```ts
// server.ts

import { serve } from "https://deno.land/std@0.181.0/http/mod.ts";

serve(() =>
  new Response("export const x = 5;", {
    headers: { "Content-Type": "application/typescript" },
  })
);
```
```
$ deno run -A server.ts
Listening on http://localhost:8000/
```
```ts
// consumer.ts

import { x } from "http://localhost:8000/mod.ts";

console.log(x);
```
```
$ deno run consumer.ts
Download http://localhost:8000/mod.ts
5
```

In editor, go-to-definition on `x`:
> The editor could not be opened due to an unexpected error: Unable to resolve text model content for resource `deno:/http/localhost%3A8000/mod.ts`

Versions:
- VSCode 1.76.2
- `denoland.vscode-deno` 3.17.0
- `deno` 1.32.1

**Comment by harrysolovay** [comment]
Politely pinging this issue, as it's causing friction for developers using [Capi](https://github.com/paritytech/capi) (a Deno-first tool for which we're trying to ensure an extraordinary experience).
