### ISSUE TITLE
Align Deno.inspect to be exactly the same as Node inspect

### ISSUE THREAD

**Issue by ry** [denoland/deno#18492]
https://github.com/denoland/deno/pull/18491

Then deduplicate the inspect implementation

**Comment by dsherret** [comment]
@nayeemrmn I think the default settings of `Deno.inspect` will be maintained, but the underlying implementation will be shared.

**Comment by kt3k** [comment]
We can now override quote preference by `quotes` option https://github.com/denoland/deno/pull/18183/files and we can keep that difference by using it
