### ISSUE TITLE
Feature: Give `deno install` parity with `deno compile`'s new dynamic import handling.

### ISSUE THREAD

**Issue by NfNitLoop** [denoland/deno#18514]
Deno 1.31 and 1.32 add support for `deno compile` to analyze dynamic imports and include them in the built binary. Those imports do not require the `--allow-net` or `--allow-read` permission when running the binary.
<https://deno.com/blog/v1.32#deno-compile-support-for-web-workers-and-dynamic-import>

But no such support was added to `install`, so if I try to `deno install` the same codebase, I have quite different functionality.

My preference would be for `deno compile`, `deno install`, and `deno run` to operate similarly w.r.t. statically-analyzable dynamic imports. 

I believe #17697 will will likely bring `deno run` into alignment, but I didn't see a similar ticket for `deno install`, so this is that ticket.  

My preference would be for `deno install` to do the same kind of bundling and/or caching that `deno compile` is doing.  i.e.:

 * `deno install` should analyze dynamic imports, and install them into the(/some) cache.
 * Running a `deno install`ed program shouldn't need extra disk permissions to load those cached imports.
 * It **definitely** shouldn't reach out to the network and re-load those resources every time an application runs. 

---

## Related Issues ##

 * My use case for wanting this: https://github.com/NfNitLoop/deno-embedder/issues/6
 * https://github.com/denoland/deno/issues/8109 -- I believe that is a different request than this one. I'm not sure permissions requirements should change between application executions depending on the state of the cache. I'd rather `deno install` just "do the thing I mean" and remove permissions from the equation.

**Comment by nayeemrmn** [comment]
> I believe #17697 will will likely bring `deno run` into alignment, but I didn't see a similar ticket for `deno install`, so this is that ticket.

It will, `deno install` just saves a `deno run` command to a shell script. So this is covered by #17697.

**Comment by NfNitLoop** [comment]
@nayeemrmn If that's all `deno install` does, then #17697 as currently described wouldn't be enough to reach parity with `deno compile`'s new behavior.

If #17697 *only* relaxes permissions for statically-analyzable dynamic imports (SADIs), then if I `deno install` a program with SADIs, `deno run` is still going to try to fetch them from the network each time.  

1. That would mean that `deno run`ning the program can fail if the network is unreliable.  (but a `deno compile` wouldn't. And a `deno install`ed program without SADIs wouldn't.)
2. It also means a malicious actor could change the code of the dynamic import after I've done a `deno install`.

My preference would be for `deno install` to somehow cache/intern/bundle the SADIs to make behavior more like `deno compile`.  Otherwise you make `deno install`ed apps second class to (more bloated) `deno compile`d ones.

**Comment by NfNitLoop** [comment]
This all works as I hoped it would nowadays. All of run/install/compile:

* Download SADIs before running.
* Don't dynamically (re)download SADIs at runtime.
* Don't need `--allow-net` or other permissions to download SADIs at runtime.

We can close this ticket.  Thanks, y'all!  🦕 ❤️
