### ISSUE TITLE
would deno can't supports typescript's `const enums` ?

### ISSUE THREAD

**Issue by HairyRabbit** [denoland/deno#1853]
```ts
export enum E { A, B }
```

works fine, but 

```ts
export const enum E { A, B }
```

throw the SyntaxError

would this hehave was a bug or feature ?

**Comment by kitsonk** [comment]
Can you provide a bit more of a complete reproduction.  `const enum`s are erased from the emitted code and the usage sites are rewritten with the emitted values.  So if all you had in a file was the `export const enum E { A, B }` it is likely that it would not produce anything, so there is nothing to run.  You can see in the [playground](https://www.typescriptlang.org/play/#src=export%20const%20enum%20E%20%7B%20A%2C%20B%20%7D), that it creates a module that doesn't export anything.

**Comment by HairyRabbit** [comment]
Yeah, I understand the enum members will inlined. because I try to run my old code with deno. If deno not supports this, I will change to normal enum.

**Comment by kitsonk** [comment]
@HairyRabbit can you please provide a more complete reproduction, because it _should_ support it, but if you have some sort of functional code.  The case you suggested, just a `const enum` by itself would never work, because it would emit nothing.

**Comment by HairyRabbit** [comment]
oh, my bad, I think I found the problem. the `const enums` works but the file must have the `.ts` extension.

I write a entry script with shebang header, so it's throw.

```ts
/// main (no `.ts`)
#!/bin/env deno
import { E } from './a.ts'

/// a.ts
export const enum E { A, B }
```

throws:

```
Uncaught SyntaxError: The requested module './a.ts' does not provide an export named 'E'
```

![image](https://user-images.githubusercontent.com/5752902/53613882-95b11880-3c12-11e9-9beb-da7d1e1559c9.png)

thanks for answer.
