### ISSUE TITLE
`deno repl` hangs with excessive memory usage running from certain CWDs

### ISSUE THREAD

**Issue by sepehrst** [denoland/deno#18538]
OS: Windows 10 Version 10.0.19045.2728

From `deno 1.32.1+7722014` and up, running `deno repl` or just `deno` from certain directories causes the deno process to hang with no repl prompt and with excessive memory usage.

The bug is reproducible if running deno from `C:\`, `C:\Windows`, `C:\Users`, `C:\Users\<current_user>`, `C:\Windows\System32`, `C:\Windows\SysWow64`. At the same time runinng `deno repl` from `C:\Users\<current_user>\Desktop` or `C:\Windows\System32\wbem` proceeds as normal. These are the directories that I've tested which reproduced the bug 100% of the times. Other directories and drives seems unaffected.

The last unaffected canary version with available binaries to download is `deno 1.32.1+e888c3f`

Edit:
Just checked with the 1.32.2 release. It's still affected.

Edit2:
Checked 1.32.2 Linux under Windows WSL, it hangs when executing with the root dir (`/`) as the current directory.

**Comment by roj1512** [comment]
Note that this occurs not only on Windows or WSL, but on Linux as well. #18540.

**Comment by dsherret** [comment]
Resolved by #18543 -- I'm going to do a release later today.
