### ISSUE TITLE
node: missing `node_modules/.bin` directory causes npm scripts to fail

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/deno#18545]
During our installation process we don't create a `node_modules/.bin` folder. That causes existing scripts in `package.json` to fail when referencing other package managers (`npm`, `yarn`, `pnpm`,...). Typically the `node_modules/.bin` folder contains symlinks to the binary path of packages which have the `"bin"` field in their `package.json` file.

Steps to reproduce:

1. `mkdir deno-bin && cd deno-bin`
2. `echo '{"name":"foo","scripts":{"test": "npm run other", "other": "mh-yes"},"dependencies": {"@marvinh/yes": "1.0.1"}}' >> package.json`
3. `deno task test`

Error:

```sh
Warning Currently only basic package.json `scripts` are supported. Programs like `rimraf` or `cross-env` will not work correctly. This will be fixed in the upcoming release.
Task test npm run other

> other
> mh-yes

sh: mh-yes: command not found
```

**Comment by dsherret** [comment]
See https://github.com/denoland/deno/issues/17901
