### ISSUE TITLE
npm workspace support

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/deno#18546]
Noticed that we're not able to resolve local workspace module in a monorepo setup.

Steps to reproduce:

1. Clone https://github.com/marvinhagemeister/deno-workspaces
2. cd into cloned repository
3. Run `deno run packages/a/index.js`

Error:

```sh
error: npm package '@marvinh/test-b' does not exist
    at file:///deno-workspaces/packages/a/index.js:1:28
```

**Comment by alshdavid** [comment]
I am also encountering this, it's a pretty substantial blocked for adopting Deno in my case

**Comment by dsherret** [comment]
It might work with `"unstable": ["byonm"]` (bring your own node_modules), which will be the default in Deno 2.0

**Comment by alshdavid** [comment]
Currently it doesn't seem to with byonm. I couldn't find where Deno decides to enable `require`/`module` but in the files above the `ByonmCliNpmResolver` seems to identify if a file is an npm package by looking for `node_modules` in the filepath.

In the case of workspaces, local packages are symlinked into node_modules but if you follow the link it will be a local file.

So

```
/node_modules
  /a    -> /packages/a (symlink)
  /b    -> /packages/b (symlink)
/packages
  /a
    index.js
    package.json
  /b
    index.js
    package.json
```

If `a` depends on `b` the raw path should be `/node_modules/b/package.json`, however if you follow/resolve the symlink it will be `/packages/b/package.json`

The Byonm resolver looks at the latter path, which does not have `node_modules` in it, resulting in it returning false on [`NpmResolver.in_npm_package`](https://github.com/denoland/deno/blob/main/cli/npm/byonm.rs#L152).

I don't know if Deno uses the result of this to decide if the import should have Node.js support

**Comment by alshdavid** [comment]
This might resolve the issues a lot of people are complaining about in this discussion - which centers around not being able to use Supabase + Deno within a symlinked workspace

https://github.com/orgs/supabase/discussions/7742

**Comment by pixeleet** [comment]
This is also a major blocker for implementing anything in a node monorepo that is purely targeted at deno e.g. `@effect/platform-deno` https://github.com/Effect-TS/effect/issues/1806
