### ISSUE TITLE
import module in github

### ISSUE THREAD

**Issue by reinaldoreizao** [denoland/deno#18555]
I'm wanting to import a module of a particular release from github, I want that when changing the release the module stays updated with the change within the deno, can you help?
example:
`import { calculos } from "https://raw.githubusercontent.com/reinaldoreizao/modules/release_ts/release_ts/calculos/math.ts";`

*but this way when changing the release in git there is no effect on the code inside the deno*

**Comment by dsherret** [comment]
I think you want to include the tag in the url:

```
https://raw.githubusercontent.com/reinaldoreizao/modules/1.0.2/release_ts/release_ts/calculos/math.ts
```
