### ISSUE TITLE
deno vendor doesn't update/remove imports in deno.json

### ISSUE THREAD

**Issue by JaegerMa** [denoland/deno#18567]
Suppose a project with the two files `main.ts` and `deno.json`:

```ts
//main.ts
import * as path from 'std/path/mod.ts';
console.log(path.SEP);
```

```jsonc
//deno.json
{
	"imports":
	{
		"std/": "https://deno.land/std@0.182.0/"
	}
}
```

After vendoring with `deno vendor --config ./deno.json ./main.ts`, the new import map `vendor/import_map.json` has been created and added to `deno.json` as `"importMap"`:

```jsonc
//deno.json
{
  "imports": {
    "std/": "https://deno.land/std@0.182.0/"
  },
  "importMap": "./vendor/import_map.json"
}
```

However, as you can see, the original `"imports"` property hasn't been removed. And since deno prefers imports directly in `deno.json` over `"importMap"`, the vendored files aren't used.

Therefore, when run with `--no-remote`, despite seemingly vendored, deno tries to use remote modules:

```
$ deno run --no-remote --config ./deno.json ./main.ts 
Warning "importMap" setting is ignored when "imports" or "scopes" are specified in the config file.
error: A remote specifier was requested: "https://deno.land/std@0.182.0/path/mod.ts", but --no-remote is specified.
    at file:///tmp/deno-vendor-importMap-bug/main.ts:1:23
```

Deno version: `deno 1.32.3 (release, x86_64-unknown-linux-gnu)`

**Comment by adamgreg** [comment]
I'm being caught out by this too (Deno 1.39.0).

I guess it would be harmful for `deno vendor` to remove the `imports:` section, but could Deno prefer `importMap` to `imports`? If that's too much of a breaking change, perhaps `deno vendor` could set a different higher-priority key instead?

**Comment by lucacasonato** [comment]
`deno vendor` was removed in Deno 2. Use `--vendor` / `vendor: true` instead.
