### ISSUE TITLE
`*.d.ts` file not cached

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/deno#18583]
Whenever I run the `deno task start` command in the `fresh` repo it seems to re-download two typing files.

<img width="776" alt="Screenshot 2023-04-04 at 01 31 10" src="https://user-images.githubusercontent.com/1062408/229648998-b1728e5b-51a5-4901-968b-8dc488982681.png">

Steps to reproduce:

1. `git clone git@github.com:denoland/fresh.git`
2. `cd fresh`
3. `deno task www`
4. Press `cmd+c` or `ctrl+c`
5. Run the same task again

**Comment by bartlomieju** [comment]
@marvinhagemeister I have trouble reproduction the problem - after running 1. and 2. I get an error about ask not existing:
```
fresh on  main via 🦕 v1.32.3 via  v19.6.0 on ☁️  bartek@deno.com
❯ deno task start
Task not found: start
Available tasks:
- test
    deno test -A && deno check --config=www/deno.json www/main.ts www/dev.ts && deno check init.ts
- fixture
    deno run -A --watch=static/,routes/ tests/fixture/dev.ts
- www
    deno run -A --watch=www/static/,www/routes/,docs/ www/dev.ts
- screenshot
    deno run -A www/utils/screenshot.ts

```

**Comment by bartlomieju** [comment]
I assume you meant `deno task www`. With that task I can see that these deps are downloaded on each run.

**Comment by ayame113** [comment]
I think these issues are related:

- https://github.com/denoland/deno-gfm/issues/47
- https://github.com/denoland/deno-gfm/issues/59

**Comment by iuioiua** [comment]
Likely related:
* https://github.com/esm-dev/esm.sh/issues/572

**Comment by marvinhagemeister** [comment]
@bartlomieju Whoops, you're correct. Meant the `www` task instead of `start`. Corrected the original post.

**Comment by marvinhagemeister** [comment]
Some more hints:

We try to cache this URL `https://esm.sh/v113/@types/katex@~0.16/dist/katex.mjs~.d.ts`, but when reading from the cache we look up this URL `https://esm.sh/v113/@types/katex@0.16.0/dist/katex.mjs~.d.ts`. There is a very minor difference around the version string: `katex@~0.16` vs `katex@0.16`. This mismatch means that the cached file is never found on disk.

**Comment by marvinhagemeister** [comment]
Looks like the `x-typescript-types` header is correct when I don't access the resolved main entry point myself, but let `esm.sh` do it. If I go to `https://esm.sh/katex@0.16.4` the header is correct, but as soon as I access a file directly it's wrong.

**Comment by marvinhagemeister** [comment]
Filed an issue over at the `esm.sh` repo. I think the bug lies there, but the fact that we have no concept of a package in deno doesn't make this easy for them.

**Comment by marvinhagemeister** [comment]
Alright, PR'ed a fix for this to `esm.sh` https://github.com/esm-dev/esm.sh/pull/579
