### ISSUE TITLE
Create specialized versions of "core.opAsync" that have proper arity

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#18589]
There are two problems with "core.opAsync":
1. It uses spread operator that is not cheap (we can see it even on coarse flamegraphs):

https://github.com/denoland/deno/blob/c341dbee5d8924988533b88d5a7900b63baf27d3/core/01_core.js#L210-L224

2. It's megamorphic - there are many call sites that pass different value types as arguments, essentially causing a deopt from V8.

Addressing the first problem is rather simple - we need to create specialized versions of `opAsync` with proper number of arguments (eg. `opAsync1`, `opAsync2`, `opAsync3`, `opAsync4`). If we need more than 4-5 of these versions that might indicate we have some problem with our ops that are exchanging too many arguments with Rust. Addressing no 2. might be a bit harder - we probably want to have highly optimized versions for passing numbers and strings, but if we need to pass more complex objects we might have to resort to non-optimized version.

**Comment by littledivy** [comment]
No longer needed with https://github.com/denoland/deno/pull/18887
