### ISSUE TITLE
Per-import permissions?

### ISSUE THREAD

**Issue by natevw** [denoland/deno#1860]
I was originally excited about the security-consciousness of deno, but I am now struggling to see the benefit.

It strikes me that the security is too broad-grained in two ways:

1. It tries to make do with [± five flags](https://deno.land/manual.html#flags) something that other approaches need a much more elaborate vocabulary to pull off (e.g. [Apple's sandboxing](https://developer.apple.com/library/archive/documentation/Miscellaneous/Reference/EntitlementKeyReference/Chapters/EnablingAppSandbox.html#//apple_ref/doc/uid/TP40011195-CH4-SW1) or [SELinux](http://web.mit.edu/rhel-doc/5/RHEL-5-manual/Deployment_Guide-en-US/ch-selinux.html)). And with the current flags it seems there has already been discovered some uncomfortable overlap between e.g. "file" access vs. all other access under many OSes.
2. It is process-level. I guess it's handy to not trust someone else's executable as much, but honestly how much "other people's code" we use these days *doesn't* semi-legitimately need `--allow-write` and `--allow-net` access? That's usually been the point of most tools we have to use, `git` and `heroku` and `kubectl` and `certbot` not to mention `webpack` with `@babel/preset-env`…

Putting the two together… isn't it the operating system's job to privilege processes? With some googling and platform-specific shell-fu, couldn't I already prevent pretty much anything I launch from gaining net access if I cared to?

What would seem a lot more useful problem to solve, if deno could, is per-import privileges. My process as a whole needs a lot of access. But the helper libraries it imports often don't. (`left-pad`, `event-stream`… the current --allow flags actually seem more appropriate at that level… my server needs everything but some parser it uses needs nothing.)

**Comment by hayd** [comment]
Duplicate of https://github.com/denoland/deno/issues/1639

**Comment by natevw** [comment]
Ah, yes indeed…sorry, I had not seen that thread.

**Comment by ry** [comment]
> Putting the two together… isn't it the operating system's job to privilege processes? With some googling and platform-specific shell-fu, couldn't I already prevent pretty much anything I launch from gaining net access if I cared to?

But it's not default.

Why does the browser bother with security? Shouldn't people just configure their OS properly?

The point is that it's restricted by default. Yes, our security is very coarse. Maybe that will get better over time, but the main feature is the ability to run code fearlessly, just as you can in browsers.

**Comment by natevw** [comment]
@ry I can see value in that, but seems that ship has already sailed? Browsers started by giving code access to ± naught but the DOM, and gradually adding careful APIs that were largely sandboxed. Any APIs that went beyond a separate "page origin" container and granted access to the users system as a whole seem to have been fraught with peril though IMO largely salvageable so far. (See the Yubikey vs. WebUSB troubles, WebMIDI sysex concerns, WebRTC [privacy concerns](https://net.ipcalf.com/)…)

deno has started by `--allow-write` to the entire filesystem, and `--allow-net` to any protocol. At what point could/would you walk that back? And how much of LXC and/or SELinux (or simply [ChromeOS](https://developer.chrome.com/apps/fileSystem)) will need to be re-invented to do so?

**Comment by hayd** [comment]
You can "walk back" --allow-write by having an optional value that restricts access to dirs. This is discussed quite a bit in the other issue.

Some things you can't protect against however, for example if you have --allow-run you're pretty much going to be able to run anything...
(Perhaps you could similarly restrict, say only run "git", but still you're still by definition breaking out of the deno permissions).
