### ISSUE TITLE
Uncaught SyntaxError: The requested module './deno.json' does not provide an export named 'version' import { version } from "./deno.json" with { type: "json" };

### ISSUE THREAD

**Issue by sant123** [denoland/deno#18614]
Hi, I'm really curious about this behavior; when importing a json in this way:

![image](https://user-images.githubusercontent.com/7959437/230442781-4ee63881-00ee-40ec-a3ba-fb6d39abb19f.png)

Works good. However this way:

![image](https://user-images.githubusercontent.com/7959437/230442894-b29c02f4-b642-47c5-b9d6-fd235c088510.png)

It breaks. 

I'm not sure about the standard about this but if the latest is not supported, the Deno lsp should inform this is an error.

Thanks.

**Comment by dsherret** [comment]
You need to use the default export.

> but if the latest is not supported, the Deno lsp should inform this is an error.

Import assertions was moved from Stage 3 to Stage 2 and is being replaced with import attributes (see https://github.com/tc39/proposal-import-attributes#import-attributes), so I don't think it's worth the effort to fix any issues with the lsp related to import assertions. The change is going to be very disruptive.

**Comment by sant123** [comment]
Makes sense, thanks a lot @dsherret 😁

**Comment by sant123** [comment]
> Import assertions was moved from Stage 3 to Stage 2 and is being replaced with import attributes (see https://github.com/tc39/proposal-import-attributes#import-attributes), so I don't think it's worth the effort to fix any issues with the lsp related to import assertions. The change is going to be very disruptive.

Now that [import attributes](https://github.com/tc39/proposal-import-attributes#import-attributes) have landed to Deno, should the LSP be configured to mark this as an error in VS Code or any IDE?

``` ts
import { imports } from "./deno.json" with { type: "json" };

console.log(imports);
```

![image](https://github.com/denoland/deno/assets/7959437/2acf3a25-df7c-4c8b-b7f0-d5b22211c48a)

**Comment by dsherret** [comment]
Let's wait and see if this is still an issue once TypeScript 5.3 is released which will have support for import attributes. At that time, I'd recommend opening an issue instead of using this one which is related, but different.
