### ISSUE TITLE
Merge microtask callback with "Deno.core.opresolve"

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#18620]
Currently we're crossing Rust->V8 boundary at least 3 times during each event loop tick:
1. resolve async ops -> calls `Deno.core.opsresolve`
2. callback to `timers.handleTimerMacrotask`
3. callback to `promiseRejectMacrotaskCallback`

No 2. and no 3. can actually be called multiple times per event loop tick increasing the number of times we have to cross the boundary.

We should merge calling back from Rust to V8 to a single call that handles both resolving async ops and calling macrotask callbacks.

To do that, we need:
1. Change how we store and call macrotask callbacks. Instead of `Deno.core.setMacrotaskCallback` calling `op_set_macrotask_callback` and storing them in a vector on `JsRuntimeState`, store them in an array somewhere in `01_core.js`.
2. Remove `op_set_macrotask_callback` and `JsRuntimeState::js_macrotask_cb_handles` (this gets rid of a bunch of clones and setting up multiple `TryCatch` scopes, yay!)
3. Change `Deno.core.opresolve` to call macrotask callbacks (after the ops are resolved) in the same fashion as `JsRuntime::drain_macrotask` is doing - iterate over them and call the current callback as many times as needed until the callback returns `true`.
4. `JsRuntime::drain_macrotask` is useless at this point, but we need to merge what's it doing to `JsRuntime::resolve_single_realm_async_ops` and `JsRuntime::resolve_async_ops` - mainly after calling back to JS check if `tc_scope.has_terminated()` or `tc_scope.is_execution_terminating()` and return `Ok(())` in such case.
5. Remove `JsRuntime::drain_macrotask`
6. Profit, HTTP server and timers implementation should be somewhat faster.

After we address this issue we might want to do the same for `drain_nexttick`.

**Comment by andreubotella** [comment]
This can't be done in one call in total, unless the global realm gains some way to call into other realms. It would have to be one call to V8 per realm. But that would solve some of the pending work related to making macrotasks work in realms.

**Comment by bartlomieju** [comment]
> This can't be done in one call in total, unless the global realm gains some way to call into the other existing realms. It would have to be one call to V8 per realm. But that would solve some of the pending work related to making macrotasks work in realms.

That's true - we're mainly trying to optimize the path with 1 realm (using `JsRuntime::resolve_single_realm_async_ops`), but it that helps in multiple realms then that's great. Am I correct in assuming that each realm has its own instance of `Deno.core`?

**Comment by andreubotella** [comment]
> That's true - we're mainly trying to optimize the path with 1 realm (using `JsRuntime::resolve_single_realm_async_ops`), but it that helps in multiple realms then that's great. If there are multiple realms then we'll have to call to each of them anyway to resolve ops. Am I correct in assuming that each realm has its own instance of `Deno.core`?

That's right.

**Comment by bartlomieju** [comment]
Then it should be all good - we just need to make sure that the callback is called for each existing realm 👍
