### ISSUE TITLE
Import map scopes doesn't work as expected

### ISSUE THREAD

**Issue by MariusVatasoiu** [denoland/deno#18626]
The `scopes` option from import_map.json or deno.json doesn't work in the following scenario:

```js
// test.js
import { Marked } from 'https://deno.land/x/markdown@v2.0.0/mod.ts';
console.log(Marked);
```

```bash
deno run test.js
```

I get the following error:

```bash
Warning Implicitly using latest version (0.182.0) for https://deno.land/std/encoding/_yaml/loader/loader.ts
error: Module not found "https://deno.land/std/encoding/_yaml/loader/loader.ts".
    at https://deno.land/x/markdown@v2.0.0/src/block-lexer.ts:25:22
```

The `markdown` module is using the latest std and there was a change in the path.

This should be solved easily by using scopes. My deno.json (tried with import_map.json also) looks like this:

```json
"scopes": {
    "https://deno.land/x/markdown": {
      "https://deno.land/std/": "https://deno.land/std@0.179.0/"
    }
  }
```

But nothing happens. If I use `"imports"` option, it works, but then all the /std/ imports are redirected to a specific version.

**Comment by dsherret** [comment]
Change it to:

```
  "scopes": {
    "https://deno.land/x/markdown@v2.0.0/": {
      "https://deno.land/std/": "https://deno.land/std@0.179.0/"
    }
  }
```

**Comment by MariusVatasoiu** [comment]
Huh! It works, thanks a lot! I thought I tried this variant, but I guess not. 

Then I have one more question, is the trailing `/` required? I checked and it only works with `https://deno.land/x/markdown@v2.0.0/`, but not with `https://deno.land/x/markdown@v2.0.0` or `https://deno.land/x/markdown`.

I followed the [docs](https://deno.land/manual@v1.31.3/basics/import_maps), and there is no trailing /.

```json
"scopes": {
    "https://deno.land/x/example": {
      "https://deno.land/std@0.177.0/": "./patched/"
    }
}
```

**Comment by dsherret** [comment]
I believe the docs are wrong there. Sorry about that! I opened https://github.com/denoland/manual/pull/607

**Comment by MariusVatasoiu** [comment]
Great, then we can close this issue.
Thanks again for clarifications! 🍺
