### ISSUE TITLE
Add a type param to `Listener` interface

### ISSUE THREAD

**Issue by jodinathan** [denoland/deno#18635]
Today the `TlsListener` extends `Listener` and `AsyncIterable<TlsConn>`.  
The problem is that `Listener` already extends `AsyncIterable<Conn>`:

`export interface TlsListener extends Listener, AsyncIterable<TlsConn> { }`
`export interface Listener extends AsyncIterable<Conn> { }`

Can we change the `Listener` so it has a type param so then we can remove the `AsyncIterable<TlsConn>` from `TlsListener`?

ie: 

```
export interface Listener<T extends Conn = Conn> extends AsyncIterable<T> {}

export interface TlsListener extends Listener<TlsConn> {}
```

I would PR this but I couldn't find it in any `d.ts` file

**Comment by petamoriken** [comment]
Here!
https://github.com/denoland/deno/blob/25aac6c7a8e015c24966168d0e3897849fefc68a/ext/net/lib.deno_net.d.ts
