### ISSUE TITLE
bug(run): `deno run x -- args` are passed to deno and not x

### ISSUE THREAD

**Issue by vegerot** [denoland/deno#18631]
(please see https://github.com/teaxyz/cli/issues/503 for more information)

tea reports a bug with developing tea using `deno run` https://github.com/teaxyz/cli/tree/main#hacking-on-teacli

Reproduction steps (thanks to @mxcl)

1. clone https://github.com/teaxyz/cli
> 
> ```shell
> $ cd tea/cli
> $ deno task run --sync   # should be equivalent of `tea --sync` with local sources checkout
> Task run deno run --unstable --allow-all src/app.ts "--sync"
> error: unexpected argument '--sync' found
> 
> Usage: deno [OPTIONS] [COMMAND]
> 
> For more information, try '--help'.
> ```
> 
> The args are going to deno and not to tea itself. Doing it without the `task` runner doesn’t help:
> 
> ```
> $ deno run --unstable --allow-all src/app.ts --version
> deno 1.32.3 (release, aarch64-apple-darwin)
> v8 11.2.214.9
> typescript 5.0.3
> 
> $ deno run --unstable --allow-all src/app.ts -- --version
> error: unrecognized subcommand '--version'
> 
> Usage: deno [OPTIONS] [COMMAND]
> 
> For more information, try '--help'.
> ```
> 
> Though it's interesting the behavior varies based on if we use `--` or not.

**Comment by nayeemrmn** [comment]
Tracked in #11547

**Comment by vegerot** [comment]
thanks @nayeemrmn

**Comment by mxcl** [comment]
This seems to actually be a tea bug. Somewhat unique since we use deno to write tea and tea to run deno. Sorry for the noise.

**Comment by vegerot** [comment]
This is actually a bug in tea
