### ISSUE TITLE
--watch fails under libvirt on linux

### ISSUE THREAD

**Issue by greergan** [denoland/deno#18637]
I am running Ubuntu 22.04.2 LTS in a Virtual Manager guest. The host system is Ubuntu 20.10.
I am also running the latest version of Deno.

deno run --watch file.ts  <= fails in the guest but works correctly on the host
When I run this command on the guest I see that Watcher starts the process and claims that it will restart on file change but it doesn't.

I am wondering if there are known issues?

**Comment by greergan** [comment]
Deno.watchFs also has issues. It will only watch a single directory regardless of the recursive flag.  It seems like it will only work for files in the current working directory.

And again, when I run things on the host computer file watching works.

**Comment by sigmaSd** [comment]
I would guess its probably a limitation on notify syscall on the guest system, you can test with this program (this should show recursive events) 
```c
#include <stdio.h>
#include <stdlib.h>
#include <errno.h>
#include <sys/inotify.h>

int main(int argc, char **argv) {
    int fd = inotify_init();
    if (fd == -1) {
        perror("inotify_init");
        exit(EXIT_FAILURE);
    }

    int wd = inotify_add_watch(fd, ".", IN_ALL_EVENTS);
    if (wd == -1) {
        perror("inotify_add_watch");
        exit(EXIT_FAILURE);
    }

    char buf[4096] __attribute__((aligned(__alignof__(struct inotify_event))));
    const struct inotify_event *event;
    ssize_t len;

    while (1) {
        len = read(fd, buf, sizeof buf);
        if (len == -1 && errno != EAGAIN) {
            perror("read");
            exit(EXIT_FAILURE);
        }

        if (len <= 0)
            break;

        for (char *ptr = buf; ptr < buf + len; ptr += sizeof(struct inotify_event) + event->len) {
            event = (const struct inotify_event *) ptr;
            printf("wd=%d; mask=%u; cookie=%u; len=%u; name=%s\n",
                    event->wd, event->mask,
                    event->cookie, event->len,
                    event->len > 0 ? event->name : "");
        }
    }

    exit(EXIT_SUCCESS);
}
```

**Comment by greergan** [comment]
It turns out that the issue is probably with the filesystem shared from host to guest.

I tried running things on the guest's filesystem instead of the shared file system and things work.

Thanks for your reply. I am going to close the issue.

**Comment by greergan** [comment]
BTW: I played around with the mount options but didn't come across a working solution. It's a 9p filesystem.
These are the options I am using. I tried 9p2000.u and was quickly reminded why it wasn't a good idea to use that version.
trans=virtio,version=9p2000.L,rwx,_netdev,cache=none
I have also tried both passthrough and mapped options in the guest configuration
