### ISSUE TITLE
Combine Deno.versions and Deno.platform into Deno.build

### ISSUE THREAD

**Issue by ry** [denoland/deno#1865]
```
Deno.build.denoVersion
Deno.build.v8Version
Deno.build.typescriptVersion
Deno.build.arch
Deno.build.os
Deno.build.gnArgs
```
Something like this. Alternative suggestions welcome. Maybe`Deno.buildInfo` ?

**Comment by hayd** [comment]
I don't think version should hide in build, the current top level version API is really nice.

It also seems like os isn't really a property of the build.

**Comment by bartlomieju** [comment]
@hayd actually `os` (or `platform` as it's called now) is injected during build via `rollup`.

`Deno.meta`?

**Comment by ry** [comment]
The reason for this is that all of these are injected during the build - and are essentially build parameters.

Deno.meta is kind of cute. Although perhaps confusing.

**Comment by bartlomieju** [comment]
`import.meta` was my initial thought, but since all of params are build parameters it makes most sense to use `Deno.build` IMHO.

**Comment by hayd** [comment]
> is injected during build via rollup.

Implementation-wise I get it and os is clearly used in the build, but semantically os is not a build property. Other statement stands too.

**Comment by kevinkassimo** [comment]
How about
```
Deno.version.deno
Deno.version.v8
Deno.version.typescript
Deno.build.arch
Deno.build.os
Deno.build.gnArgs
```
?

**Comment by ry** [comment]
@kevinkassimo that’s what I was going to suggest too. I think meta is cute but probably your suggestion is more obvious.

**Comment by zekth** [comment]
Agree with @kevinkassimo proposal
