### ISSUE TITLE
Disable version checking

### ISSUE THREAD

**Issue by tjconcept** [denoland/deno#18663]
I've installed Deno using Brew and keep it updated that way as well. I update through Brew on a regular basis, but not really in any relation to whether there's a new version available of a particular program I use. For that reason, I'd like to disable the version check that happens on arbitrary script invocations resulting in printing the message:
> A new release of Deno is available

**Comment by crowlKats** [comment]
you can set the `DENO_NO_UPDATE_CHECK` env var on your system to disable the update checker

**Comment by dsherret** [comment]
It's in `deno help` and was missing from the manual https://github.com/denoland/manual/pull/611
