### ISSUE TITLE
Bug with ```deno upgrade```

### ISSUE THREAD

**Issue by fjmduran** [denoland/deno#18682]
PS C:\Users\fjmartinez> deno upgrade
Looking up latest version
Found latest version 1.32.4
Checking https://github.com/denoland/deno/releases/download/v1.32.4/deno-x86_64-pc-windows-msvc.zip
28.2 MiB / 28.2 MiB (100.0%)
Deno is upgrading to version 1.32.4

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: windows x86_64
Version: 1.21.0
Args: ["C:\\Users\\fjmartinez\\.deno\\bin\\deno.exe", "upgrade"]

thread 'main' panicked at 'assertion failed: exe_path.exists()', cli\tools\upgrade.rs:289:3
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by bartlomieju** [comment]
It appears you are on a very old version (1.21.0) and I'm pretty sure that this problem has been fixed on newer versions. There's really nothing we can do about it now - I would suggest to remove Deno from the system manually and install it again.
