### ISSUE TITLE
cli/tsc crashes with Uncaught TypeError

### ISSUE THREAD

**Issue by patreeceeo** [denoland/deno#18694]
[Copying this over from [the help post I made](https://discord.com/channels/684898665143206084/1096199117589463161/1096199117589463161) in the discord server, since this actually seems like a bug]

Using latest Deno (1.32.4), this only happens on certain files, but it effectively means that I cannot do type checking with Deno. The error: 
```
error: Uncaught TypeError: Cannot read properties of undefined (reading 'kind')
    at <anonymous> (internal:deno_tsc/tsc/00_typescript.js:19111:18)
```
Steps to reproduce:
- Write a function with a parameter of type `Parameters<typeof someValue["someProperty"]>[1]`
- run `deno check file.ts`

Workarounds:
- Create a type alias for `Parameters<typeof someValue["someProperty"]>[1]` and use that in the function instead.

**Comment by aapoalas** [comment]
Hello and thank you for the report. Could you include a complete (and fairly minimal) reproduction code in the issue?

**Comment by patreeceeo** [comment]
Well now the code where it was happening has changed a lot, didn't save a copy or commit when it was happening, and I can't seem to reproduce it. 

I know it's there, but it must be a very edgy edge case. I'll close this for now.
