### ISSUE TITLE
References to package.ts in manual

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#1869]
I've stumbled across manual fragment that tells:
> **It seems unwieldy to import URLs everywhere. What if one of the URLs links to
a subtly different version of a library? Isn't it error prone to maintain URLs
everywhere in a large project?** The solution is to import and re-export your
external libraries in a central `package.ts` file (which serves the same purpose
as Node's `package.json` file). For example, let's say you were using the above
testing library across a large project. Rather than importing
`"https://deno.land/x/testing/mod.ts"` everywhere, you could create a
`package.ts` file the exports the third-party code:

@ry have you changed your mind regarding usage of `package`? IIRC there was some discussion about using `deps.ts` (eg. @kitsonk's oak uses it). Maybe we should ambiguate this paragraph to convey idea of single file with imports but not necessarily using `package.ts` name.

**Comment by kitsonk** [comment]
I thought we ran away from the term _package_.  I distinctly remember talking about that before!  It would seem some people have short term memory loss. 😛 The public [conversation is here](https://gitter.im/denolife/Lobby?at=5c330f834ed182787770607b).

**Comment by ry** [comment]
Yeah, I think this was written before that. I would be happy to change this to `deps.ts`.
