### ISSUE TITLE
Buffers are different in a npm library and the one used in deno, leading to compatibility issues and invalid library logic

### ISSUE THREAD

**Issue by kazeens** [denoland/deno#18716]
Hello.

In my deno code I create something like
`const data = new Buffer()`;
And I use npm library which validates the object I pass to its method like this
```
if(data instanceof Buffer) {
// should go into this if branch
} else {
// goes to this branch
}
```

On my main code base Buffer obviously globally is not defined until I import 
`import { Buffer } from "npm:buffer@^6.0.3";` 

const data = Buffer.from(somestuff);

I use this object to pass to library method and Buffer used by library can't make `if` branch in the code above correctly.

I used Deno buffer and package Buffer but IT can't meet the comparison because those buffer and buffer used by npm library during runtime are different.

I can't even override it using globalThis.Buffer = [my deno buffer].

This does not have any effect on Buffer used in the library, though if you declare any other variable using `globalThis` like `globalThis.random`, it is going to be visible in the library (I checked)

How can I make library work correctly?

**Comment by bartlomieju** [comment]
Instead of:
```
import { Buffer } from "npm:buffer@^6.0.3";
```
try to do:
```
import { Buffer } from 'node:buffer';
```

That will make your code and the library code use the same `Buffer` class.

**Comment by kazeens** [comment]
@bartlomieju Thanks man. You've made my day

**Comment by bartlomieju** [comment]
Great. I'm going to close the issue then.
