### ISSUE TITLE
Performance.ts hrtime

### ISSUE THREAD

**Issue by zekth** [denoland/deno#1871]
It would be very nice to add hrtime function like in nodejs: https://nodejs.org/api/process.html#process_process_hrtime_time

It's really usefull in optimizations measurements and debugging.

Using rust std functions:
```rust
use std::time::Instant
let now = Instant::now();
now.elapsed().as_nanos()
```

Used as_nanos per default and then add formatters on the Ts side. Your thoughts?

**Comment by hayd** [comment]
👍 See https://github.com/denoland/deno/issues/1777

**Comment by zekth** [comment]
Closing following into #1777
