### ISSUE TITLE
websocket don't send msg after timeout in deno 1.32.4

### ISSUE THREAD

**Issue by anilkumarum** [denoland/deno#18715]
Today, I upgrade deno to 1.32.4.  Websocket break in deno 1.32.4. 
First message successfully send but cannot send message after timeout.
It work fine in deno 1.32.3. 

```js
	const { socket, response } = Deno.upgradeWebSocket(reqEvent.request);
	socket.onopen = () => {
		console.log("socket opened");
		socket.send("Hello World!");
	};
	socket.onmessage = (e) => {
		socket.send("message from client received");//this work
		setTimeout(() => {
			socket.send("message send after some time");//this doesn't work
			// socket.close();
		}, 2000);
	};
	socket.onclose = () => console.log("WebSocket has been closed.");
	socket.onerror = (e) => console.error("WebSocket error:", e);
	reqEvent.respondWith(response);
```

please fix this issue.

**Comment by aapoalas** [comment]
It is likely that this is the same issue as https://github.com/denoland/deno/issues/18700

If you can check the canary version (`deno upgrade --canary`) to see if the issue is already resolved, that'd be lovely.

**Comment by pagoru** [comment]
Same problem with Windows 11, but not with macos

**Comment by bartlomieju** [comment]
@littledivy please take a look

**Comment by littledivy** [comment]
This is fixed in canary. Try it out: `deno upgrade --canary`

**Comment by anilkumarum** [comment]
okay, I wait for next stable update.
