### ISSUE TITLE
deno size

### ISSUE THREAD

**Issue by cup** [denoland/deno#1872]
the Node executable is pretty sizable, currently at 21.3 MB

however i noticed that the current Deno is 38.4 MB, nearly double the size

what is the reason for this discrepancy?

**Comment by kitsonk** [comment]
It includes the TypeScript compiler and it includes snapshots which increase startup speed.  Neither of these are true of Node.js.

**Comment by bartlomieju** [comment]
Can we close this one now?

**Comment by cup** [comment]
@bartlomieju I just tested again. Current Node executable is 21.0 MB vs
Deno 41.8 MB.

There seems to be no desire to improve the situation, and in fact the issue
seems to be getting worse.

So maybe the best thing to do is close as "wont fix".

**Comment by kitsonk** [comment]
> desire to improve the situation

You are comparing apples to oranges.  We track the size the binary in the stats and do care about it, but the two things I mentioned above are significant differences to Node.js.

**Comment by cup** [comment]
@kitsonk i think its more like apples versus larger apples.

**Comment by ry** [comment]
[We track binary size](https://deno.land/benchmarks.html#size) and want to keep it as small as possible - but Deno includes the typescript compiler which is going to inflate the binary size. It will probably never be smaller than Node.

If you want a very minimal environment check out the Deno crate: https://crates.io/crates/deno
A minimal example clocks in at 16 megabytes: 
```
> ls -lh target/release/deno_core_http_bench
-rwxr-xr-x  1 rld  staff    16M Apr 13 15:46 target/release/deno_core_http_bench
```

**Comment by cup** [comment]
I found a workaround:

https://bellard.org/quickjs

Built size on my system is 3.49 MB

**Comment by nayeemrmn** [comment]
@cup See https://github.com/denoland/deno/issues/2716.

**Comment by cup** [comment]
I found a workaround:

https://github.com/svaarala/duktape

Built size on my system is 1.96 MB. Also:

https://bellard.org/quickjs

Built size on my system is 3.49 MB

**Comment by kevinkassimo** [comment]
@cup different JS engines suits different needs. It's definitely great to find an engine that suits, as there are always tradeoffs between performance, size, etc.

Since you mentioned about QuickJS, it you need some bindings like the ones provided by Node, check out [qjsuv](https://github.com/saghul/qjsuv) (beware that both QuickJS and qjsuv seems not yet robust enough at this moment though)
