### ISSUE TITLE
lsp: deno:/status.md doesn't work anymore

### ISSUE THREAD

**Issue by sigmaSd** [denoland/deno#18724]
It just returns {} now

I suspect `normalize_url` https://github.com/denoland/deno/blob/main/cli/lsp/language_server.rs#L3356 , since its recently changed https://github.com/denoland/deno/commit/7070b8ed50f13d95d926b19ed7d7ce9fc0d6d4f3#diff-20db93e8dfbff58c3024a4e247e639bf84fd5e8d2a447e8bbed9ee8942d688afR3275

![image](https://user-images.githubusercontent.com/22427111/232323638-bfc91cbc-8bdf-4db7-9fbc-dd95fe711f05.png)

**Comment by dsherret** [comment]
Works for me. I remember testing this one after that change:

![image](https://user-images.githubusercontent.com/1609021/232330238-75d624bb-160f-46a8-ac3e-b8f98f87930a.png)

**Comment by sigmaSd** [comment]
I get this error 
```
The source was not found: file:///status.md
```
deno 1.32.4 (release, x86_64-unknown-linux-gnu)
vscode-deno 3.17.0

**Comment by dsherret** [comment]
How are you requesting it?

**Comment by dsherret** [comment]
Same thing happens for me on linux only.
