### ISSUE TITLE
[feat] fetchOptions.dispatcher

### ISSUE THREAD

**Issue by loynoir** [denoland/deno#18739]
```sh
$ npm add undici
$ node
Welcome to Node.js v18.15.0.
Type ".help" for more information.
> {Agent}=require('undici')
...
> await fetch('http://localhost/version', {dispatcher:new Agent({connect:{lookup:console.log}})})
localhost ...
> await (await fetch('http://localhost/version', {dispatcher:new Agent({socketPath: '/var/run/docker.sock'})})).json()
{
  Platform: 
```

**Comment by loynoir** [comment]
Related

https://github.com/denoland/deno/issues/8821

https://github.com/denoland/deno/issues/17910

https://github.com/nodejs/undici#undicifetchinput-init-promise

**Comment by lucacasonato** [comment]
Please see `Deno.createHttpClient`

**Comment by loynoir** [comment]
@lucacasonato

But `Deno.createHttpClient` don't have `socketPath` and `dnsLookup`.

Don't know about rust.

But I guess, `reqwest` should have option for `socketPath` and `dnsLookup`, right?

**Comment by denizdogan** [comment]
@lucacasonato I don't think this has been implemented in Deno, has it? I can only find `Deno.listen({ path: "...", transport: "unix" })`, but that's not what this is about. I don't think you can do this with `fetch` currently.
