### ISSUE TITLE
error: Loading unprepared module npm:<pkg@version>

### ISSUE THREAD

**Issue by shinebayar-g** [denoland/deno#18744]
After v1.32.4 we no longer have to pass `--reload` flag to update npm dependencies. It's a great improvement. However there is a little bug on the first run.
For example, this script `deno run --allow-env --allow-write --allow-read main.ts` gives the following error on the first run.

```sh
error: Loading unprepared module: npm:cdk8s@2.7.55, imported from: file:///Users/home/myapp/main.ts
Error: command "deno run --allow-env --allow-write --allow-read main.ts " at /Users/home/myapp returned a non-zero exit code 1
    at ChildProcess.<anonymous> (/Users/home/.nvm/versions/node/v18.15.0/lib/node_modules/cdk8s-cli/lib/util.js:51:27)
    at Object.onceWrapper (node:events:628:26)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
```

If I call the command again it works.

Deno version: 1.32.4

**Comment by dsherret** [comment]
What are the contents of main.ts?

**Comment by shinebayar-g** [comment]
```ts
import * as fs from 'node:fs';
import { App, YamlOutputType } from 'cdk8s';
import { generate } from './src/lib/generate.ts';

const rootApp = new App({
    yamlOutputType: YamlOutputType.FOLDER_PER_CHART_FILE_PER_RESOURCE,
    recordConstructMetadata: false,
    outputFileExtension: '.yaml',
});

async function main() {
    const teams = await generate(rootApp);
    rootApp.synth();
}

await main();
```

**Comment by dsherret** [comment]
Thanks!

**Comment by shinebayar-g** [comment]
Hmm I can no longer reproduce the issue. I thought I was able to reproduce the issue whenever I bump my dependencies.
I'm cleaning `npm modules cache` folder, removing `deno.lock` and bumping dependency in the imports map. But it just works..
If you don't have a strong suspicion feel free to close this.

**Comment by nakasyou** [comment]
I got a similar error too.

`npm:` Happened when I dynamically imported a schema.

**Comment by bartlomieju** [comment]
Can you folks still repeat the problem on latest Deno version?

**Comment by loynoir** [comment]
For mixed errors report, `SuppressedError` might be useful.

https://github.com/tc39/proposal-explicit-resource-management

**Comment by birkskyum** [comment]
@loynoir , it seems like at least the #20914  -  does it change your  output?

**Comment by loynoir** [comment]
Yes and no.

Below command often success.

```sh
$ deno test -A -c deno.json --parallel --no-check --coverage=xxx ./foo.test.ts
```

Still **sometime** fail with error `Loading unprepared module: npm:X@Y` using archlinux with deno 1.41.1.

Guess there is race condition in deno code.
