### ISSUE TITLE
importDenoMap

### ISSUE THREAD

**Issue by elycheikhsmail** [denoland/deno#18751]
I suggess superset of importMap, I call it importDenoMap by default in file import_deno_map.json do the same thing as import_map.json plus the possibility to map npm: specifier, this file content should be something like:
{
  "imports": {
    "preact": "https://esm.sh/preact@10.10.0",
    "preact/": "https://esm.sh/preact@10.10.0/",
    "express": "npm:express",
  }
}
in deno.json we can refere to it via "importDenoMap" key word to avoid confusion with "importMap", under the hood deno cli resolve npm package and es module and execute the code. this feature will improve DX and code quality.

**Comment by bartlomieju** [comment]
I believe you can already do `npm:` specifiers inside the currently supported import map.

**Comment by elycheikhsmail** [comment]
> I believe you can already do `npm:` specifiers inside the currently supported import map.

thank you, I didn't get good DX when importing npm pkg via importmap befor using --node-modules-dir flag.
after adding --node-modules-dir flag I get comlete IDE support.
you can close this issue.
