### ISSUE TITLE
single character CLI option for --no-prompt

### ISSUE THREAD

**Issue by benatkin** [denoland/deno#18761]
How about a single character CLI option for `--no-prompt`?

It seems like it could be a counterpart to `-A` which is easy to type and does the opposite of what `--no-prompt` does.

I would use it for `deno repl`.

**Comment by benatkin** [comment]
I already know about it and was thinking of putting a shorter `deno repl --no-prompt` in tutorials, to show off stuff that doesn't require additional permissions. As it is, I'll use the longer `deno repl --no-prompt`.

**Comment by dsherret** [comment]
> I already know about it and was thinking of putting a shorter deno repl --no-prompt in tutorials

Probably `--no-prompt` is more descriptive than a short undescriptive flag for tutorials. I'm not sure there should be a short flag for this because we don't have short flags for any other of the `--no-x` flags.

**Comment by benatkin** [comment]
With *allow* getting `-A`, `--no-prompt` feels like syntactic vinegar in comparison when it's actually making things simpler and safer in a lot of cases. Perhaps a new mode that includes `--no-prompt` could be added that wouldn't be `--no-x` and could be shortened.

**Comment by KnorpelSenf** [comment]
Related: #19530

**Comment by benatkin** [comment]
I'm -1 on #19530 because it makes it harder to see what security features have been disabled.

**Comment by benatkin** [comment]
I think it's better to encourage readability than it is to make sure they're curated carefully, so I'm closing this, after reading a comment on #19530. `-A` is good for convenience and also good to leave in because it has already been there a long time. `--no-prompt` is concise enough.
