### ISSUE TITLE
thread 'main' panicked at 'failed to determine top-level Id for jsx expression'

### ISSUE THREAD

**Issue by NotWoods** [denoland/deno#18779]
```sh
Platform: windows x86_64
Version: 1.32.0
Args: ["C:\\Users\\tiger\\.deno\\bin\\deno.exe", "run", ".\\src\\generate.ts"]

thread 'main' panicked at 'failed to determine top-level Id for jsx expression', C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\swc_ecma_transforms_typescript-0.171.4\src\strip.rs:252:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

# How to reproduce:

Use a deno.json with the following:
```json
{
  "compilerOptions": {
    "jsxFactory": "h",
    "jsxFragmentFactory": "null"
  }
}
```

## Why u do this?

To use fragments with [vhtml](https://github.com/developit/vhtml/issues/31), null is used rather than a special helper function. (`h(null, {}, ...children)`)

Using `undefined` as the jsxFragmentFactory works fine.

**Comment by lucacasonato** [comment]
Does this work in TSC?

**Comment by NotWoods** [comment]
I was able to run TSC with this config (and setting `jsx` to `react`)

**Comment by marvinhagemeister** [comment]
Just tried this out with Deno `1.42.4` and the `null` value is inserted as expected 🎉
