### ISSUE TITLE
bug(regression/websocket): server sends double close frames

### ISSUE THREAD

**Issue by lucsoft** [denoland/deno#18775]
# Affected versions
broken in 1.32.4 (could be also in 1.32.3, but i didn't check). works in 1.32.3.

# Reports 
<https://canary.discord.com/channels/684898665143206084/684911491035430919/1098305174289793166>

i hope its all the information you awesome people need :D

**Comment by littledivy** [comment]
Is it consistently sending double close frames? Can you provide a reproduction?

**Comment by lucsoft** [comment]
@littledivy Here
1. WebSocket Server
```ts
Deno.serve((req) => {
    const { response, socket } = Deno.upgradeWebSocket(req);

    socket.onopen = () => socket.send("Hello");
    socket.onmessage = () => {
        socket.send("bye");
        socket.close();
    };

    return response;
})
```
2. Run Browser Code (ideally open just the url and then do into dev tools and run the following code)
```ts
const ws = new WebSocket("ws://localhost:9000");
ws.onmessage = () => ws.send("Hi");
// Or: ws.onopen = () => ws.send("Hi");
```

**Comment by hazae41** [comment]
Still happens on 1.33.3

```
deno 1.33.3 (release, aarch64-apple-darwin)
v8 11.4.183.2
typescript 5.0.4
```

I set up a TCP proxy to log it, it sends a TCP packet containing two close frames `136, 2, 3, 232`

![Capture d’écran 2023-05-15 à 18 18 14](https://github.com/denoland/deno/assets/4405263/d22032f4-9c11-44c6-9cce-0968cef60edb)

**Comment by hazae41** [comment]
Doesn't happen on Node v18.12.1

![Capture d’écran 2023-05-15 à 18 22 50](https://github.com/denoland/deno/assets/4405263/bc842f91-8d45-493a-9f0f-20ecb28894a5)

**Comment by bartlomieju** [comment]
@hazae41 could you provide a reproduction code?

**Comment by hazae41** [comment]
@bartlomieju

https://github.com/hazae41/fleche/tree/main/tools/deno

> deno run -A ws_server.ts

> deno run -A tcp_tcp_proxy.ts

> deno run -A ws_client.ts

You will see `<- Uint8Array(6) [ 136, 0, 136, 2, 3, 237 ]` in the proxy logs

`136, 0` is one close frame, `136, 2, 3, 237` is another

**Comment by mmastrac** [comment]
I checked with the latest version of deno after some work we've done and this appears to be fixed. 

Wireshark dump shows just one close frame:

```
    000000A0  4d 54 0d 0a 0d 0a                                  MT....
    000000A6  81 05 48 65 6c 6c 6f                               ..Hello
00000228  81 82 dc 26 59 9f 94 4f                            ...&Y..O 
    000000AD  81 03 62 79 65                                     ..bye
    000000B2  88 00                                              ..
00000230  81 82 d7 65 fc 4a 9f 0c                            ...e.J.. 
00000238  88 80 8a 03 d5 b7                                  ......
```
