### ISSUE TITLE
Using npm:prisma init fails

### ISSUE THREAD

**Issue by jakewies** [denoland/deno#18785]
I am following this [document](https://www.prisma.io/docs/guides/deployment/deployment-guides/deploying-to-deno-deploy).

I'm running this command:

```
deno run -A --unstable npm:prisma init
```

And receiving this error:

```
Downloading Prisma engines for Node-API for darwin-arm64 [...] error: Uncaught (in promise) TypeError: context.digest is not a function
```

If I try to run prisma init outside of deno:

```
npx prisma init
```

It succeeds just fine:

![Screenshot 2023-04-20 at 11 41 22](https://user-images.githubusercontent.com/12075916/233418148-766af0e8-41e7-473e-ac9e-e70740da23d3.png)

I'm not sure if this is a `deno` issue, or a `prisma` issue, however I am able to get this working outside of `deno`.

**Comment by kawadumax** [comment]
Looking at this, it seems to be a function correctly, so it appears to be more of a problem on the caller's side.
https://github.com/denoland/deno/blob/main/ext/node/polyfills/internal/crypto/hash.ts#L112

When I check _stream.mjs, I see a large number of minified strings near the line `/* esm.sh - esbuild bundle(readable-stream@4.2.0) es2022 production */ `. I suspect this might be the cause.
https://github.com/denoland/deno/blob/main/ext/node/polyfills/_stream.mjs#L11

**Comment by kawadumax** [comment]
As shown below, I have confirmed that 1.32.4 does not cause problems in my environment.

https://github.com/denoland/examples/issues/15#issuecomment-1517385397

**Comment by yagop** [comment]
Same here, 1.32.4 works while 1.32.5 crash


```
❯ docker run -it --rm  -w /app  denoland/deno:1.32.4 deno run --allow-all  npm:prisma@^4.5 init

✔ Your Prisma schema was created at prisma/schema.prisma
  You can now open it in your favorite editor.
```

```
❯ docker run -it --rm  -w /app  denoland/deno:1.32.5 deno run --allow-all  npm:prisma@^4.5 init

> Downloading Prisma engines for Node-API for debian-openssl-1.1.x [==================  ] 91%error: Uncaught (in promise) TypeError: context.digest is not a function
    at Hash.flush [as _flush] (ext:deno_node/internal/crypto/hash.ts:47:35)
    at Hash.Ot [as _final] (ext:deno_node/_stream.mjs:11:59823)
    at Fa (ext:deno_node/_stream.mjs:11:51130)
    at Ua (ext:deno_node/_stream.mjs:11:51274)
    at mt (ext:deno_node/_stream.mjs:11:51350)
    at Hash.S.end (ext:deno_node/_stream.mjs:11:50523)
    at he.u (ext:deno_node/_stream.mjs:11:36397)
    at Object.onceWrapper (ext:deno_node/_events.mjs:502:28)
    at he.emit (ext:deno_node/_events.mjs:391:35)
    at Ea (ext:deno_node/_stream.mjs:11:43461)
  ```

**Comment by kt3k** [comment]
Sorry for the delay in response (was busy at deploy work). I'll take a look.
