### ISSUE TITLE
Consider not using node_modules directory whenever node_modules dir exists and it does not contain a `.deno` directory

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#18803]
Right now, Deno will use a node_modules directory when a package.json exists. This can be disabled in a variety of ways, but a common complaint is someone having an existing node_modules directory, then Deno starts using it. Perhaps we should change it so it doesn't use the node_modules directory if the `node_modules` folder exists and the `node_modules/.deno` directory does not exist.

**Comment by wojpawlik** [comment]
Only _modifying_ foregin `node_modules/` leads to heisenbugs that (dis)appear on `npm ci`.

**Comment by rajsite** [comment]
An alternative option may be a new flag to use the current node_modules hierarchy as-is without modifying it when resolving the `npm:` specifier https://github.com/denoland/deno/issues/18967

**Comment by dsherret** [comment]
This seems too complex and error prone. Going to implement #17930 instead in addition to all the other ways we have for disabling the node_modules directory.
