### ISSUE TITLE
Use `String#toWellFormed` in ext/webidl and ext/node

### ISSUE THREAD

**Issue by petamoriken** [denoland/deno#18802]
Deno 1.32 uses V8 11.2, so we can use [Stage 3 Well-Formed Unicode Strings (a.k.a USVString)](https://github.com/tc39/proposal-is-usv-string) now. Maybe using `String#toWellFormed` in Deno internal improves performance and I think it makes sense, however `String#toWellFormed` is not available at the time of the snapshot. Should this issue be reported towards V8?

**Comment by bartlomieju** [comment]
IIRC APIs that are not Stage 4 are not available during snapshotting, so we'll have to wait until it's stabilized.

**Comment by lino-levan** [comment]
@petamoriken this is now a stage 4 proposal, perhaps now would be a good time to add `toWellFormed` to primordials?

**Comment by petamoriken** [comment]
`--harmony-string-is-well-formed` flag was removed
https://chromium.googlesource.com/v8/v8/+/0f9ebbc672c77594feb9176cf52601116aa7c34c
