### ISSUE TITLE
Better JSX formatting.

### ISSUE THREAD

**Issue by vikaskaliramna** [denoland/deno#18805]
I love `deno fmt` because of it's minimal configuration and proper code formatting without any issues but when I format JSX code, it looks something like this:

```tsx
function jsxComponent() {
    return (
        <div>
	</div>
    );
}
```

But it would be better if it is formatted like this:

```tsx
function jsxComponent() {
    return <div>
    </div>;
}
```

This type of option is provided in JetBrains ide, is not enabled by default.

# Benefits:
- 2 less characters :/
- Less WhiteSpace
- Looks nicehttps://docs.github.com/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax
- compact, but readable.

**Comment by lucacasonato** [comment]
This diverges significantly from prettier. We try to stick to prettier formatting. Thanks for the suggestion, but we'll stick with the current behaviour.
