### ISSUE TITLE
Using Luma and Deno serve generates � between each letter in the md file

### ISSUE THREAD

**Issue by TonyKnibb-MakaraHealth** [denoland/deno#18825]
I ran `echo 'Hello world' > index.md` which created the file, and populated it with _Hello world_. 

Running `deno task serve` results in an html file that's like this: 

`< !DOCTYPE html > 
< p>��H�e�l�l�o� �w�o�r�l�d�< /p>`

[spaces in tags added for formatting here]

Adding anything additional to the md file results in the same thing happening to that too.

**Comment by bartlomieju** [comment]
Please provide full reproduction code

**Comment by lucacasonato** [comment]
Your file is being stored in UTF-16, but you are reading it as UTF-8. Are you on Windows, and populated the file using "cmd.exe"?

**Comment by TonyKnibb-MakaraHealth** [comment]
> Your file is being stored in UTF-16, but you are reading it as UTF-8. Are you on Windows, and populated the file using "cmd.exe"?

The file was created via the cmd window in PhpStorm, on Windows 10.

**Comment by lucacasonato** [comment]
This is not a bug in Deno, it is unfortunately just how Windows works (legacy parts of it use UTF-16 instead of UTF-8 like the rest of the world). If you create this file via the PhpStorm editor, it likely won't have this issue. cmd.exe is one of these legacy things that use UTF-16

**Comment by TonyKnibb-MakaraHealth** [comment]
That seems to have fixed my issue. 

Thanks!
