### ISSUE TITLE
Move I/O interfaces into deno_std

### ISSUE THREAD

**Issue by ry** [denoland/deno#1882]
Like Reader, Writer  - everything in https://github.com/denoland/deno/blob/master/js/io.ts

**Comment by zekth** [comment]
I'll do it.

Into `/std/io/??.ts` ? There is no mod.ts, do i create one which just expose interfaces? Or do interface.ts ? Or maybe ioutil.ts?

**Comment by bartlomieju** [comment]
@ry do you still want to do it?

**Comment by ry** [comment]
@bartlomieju We need to solve the problem of importing stuff from deno_std first. When I created this issue I had forgotten it wasn't passible yet.

**Comment by bartlomieju** [comment]
Update Feb 24, 2020; closing as it will come up when vetting `std`
