### ISSUE TITLE
bug - TypeError: Deno.openPlugin is not a function

### ISSUE THREAD

**Issue by FridayCandour** [denoland/deno#18835]
return Deno.openPlugin(file.path);
              ^
    at Module.prepare (https://deno.land/x/plug@0.3.1/plug.ts:81:15)
    at eventLoopTick (ext:core/01_core.js:165:11)
    at async https://deno.land/x/pane@0.2.1/plugin.ts:10:1

(main)> deno --version
deno 1.32.5 (release, x86_64-unknown-linux-gnu)
v8 11.2.214.9
typescript 5.0.3

**Comment by crowlKats** [comment]
Pane is an old module that relied on the plugin system that doesnt exist anymore.

**Comment by FridayCandour** [comment]
What can I do

**Comment by crowlKats** [comment]
well the pane module wont work, and there isnt anything that can be done about that. I am not too familiar with alternatives for it either
