### ISSUE TITLE
npm incompatibility due to process.release.name

### ISSUE THREAD

**Issue by rajsite** [denoland/deno#18870]
## Description

When loading a CommonJS module from npm in deno I'm finding that `process.release.name` is not defined on the process object.

A minimal reproduction that I think represents the same issue is creating a `main.mjs` with contents:
```js
import process from 'node:process';
console.log(`process release name: ${process.release?.name}`);
```

And running it via node vs deno:
```
C:\>node main.mjs     
process release name: node

C:\>deno run main.mjs
process release name: undefined

C:\>deno --version
deno 1.32.5 (release, x86_64-pc-windows-msvc)
v8 11.2.214.9
typescript 5.0.3

C:\>node --version
v18.16.0
```

The [`process.release`](https://nodejs.org/api/process.html#processrelease) docs.

## Context

Trying to load the pyodide npm package as a CommonJS module. I believe when this issue is fixed loading pyodide could be validated with:

```js
import {loadPyodide} from "npm:pyodide/pyodide.js";

const pyodide = await loadPyodide();
await pyodide.loadPackage('micropip');
const micropip = pyodide.pyimport("micropip");
await micropip.install('snowballstemmer');
const result = await pyodide.runPythonAsync(`
import snowballstemmer
stemmer = snowballstemmer.stemmer('english')
stemmer.stemWords('go goes going gone'.split())
`);

console.log(result.toString());
```

Resulting in:

```
C:\>deno run --node-modules-dir -A main.ts
Loading micropip, packaging
Loaded packaging, micropip
['go', 'goe', 'go', 'gone']
```

The issue is that a [heuristic for pyodide to check for execution in node](https://github.com/pyodide/pyodide/blob/24957acc139208a0a8113d185ae55dc9288f75f9/src/js/compat.ts#L4-L9) uses `process.release.name` and is failing due to this issue.

**Comment by fms12** [comment]
@bartlomieju  can I work on this one

**Comment by bartlomieju** [comment]
Sorry @fms12 I didn't notice your ping. It appears there's already a PR open for that feature in #18923.
