### ISSUE TITLE
`URL.canParse()` should throw an error

### ISSUE THREAD

**Issue by zloirock** [denoland/deno#18893]
### Version

1.33.0

### What is the expected behavior? Why is that the expected behavior?

```js
URL.canParse() // => TypeError: at least 1 argument required, but 0 present.
```

### What do you see instead?

```js
URL.canParse() // => false
```

### Additional information

See the signature https://url.spec.whatwg.org/#url-class

Similar to https://github.com/nodejs/node/issues/47505

**Comment by petamoriken** [comment]
Sorry I missed it, I'll fix it.
