### ISSUE TITLE
vscode errors: Deno.open, Deno.read, Deno.close: Property 'open' does not exist on type 'typeof Deno'.

### ISSUE THREAD

**Issue by sspilleman** [denoland/deno#18907]
Hi,

Recently (as of today, after installing the latest deno version using Homebrew on my mac) Im getting errors in the "problems" tab.
These are new and didn't get them before.  The program runs fine without errors and/or warnings....

Any idea what is wrong?

Thank you!

Sander

---

Versions:
```
deno 1.32.5 (release, aarch64-apple-darwin)
v8 11.2.214.9
typescript 5.0.3
```

Testfile:
```typescript
const file = await Deno.open("8360.json");
const buf = new Uint8Array(100);
const numberOfBytesRead = await Deno.read(file.rid, buf); // 11 bytes
const text = new TextDecoder().decode(buf); // "hello world"
Deno.close(file.rid);
console.log(numberOfBytesRead, text.length);
```

Errors:
```
Property 'open' does not exist on type 'typeof Deno'.
Property 'read' does not exist on type 'typeof Deno'.
Property 'close' does not exist on type 'typeof Deno'.
```

**Comment by sspilleman** [comment]
Did some investigation:

- Revering back to latest 1.32 release (v1.32.5) issue is "already" there
- Revering back to latest 1.31 release (v1.31.3) issue is NOT there

So the issue as introduced "somewhere" after v1.31.3 and before v1.32.5.

Then looking at the release log, I see the following (breaking) changes, which *might* be related, but I also can't judge too much:
- v1.32.0: BREAKING(unstable): remove WebGPU (https://github.com/denoland/deno/pull/18094)
- v1.32.2: fix: upgrade to TypeScript 5.0.3 (https://github.com/denoland/deno/pull/18532)
- v1.32.5: fix(path): Remove non node symbols (https://github.com/denoland/deno/pull/18630)

 Can somebody help? Ok to stick with v1.31.3 for now... but obviously I do prefer to upgrade

**Comment by dsherret** [comment]
Is there any errors in View > Output, then select "Deno Language Server" in the output window's dropdown?

**Comment by dsherret** [comment]
Also, maybe try adding this to one of your files:

```ts
/// <reference lib="deno.ns" />
```

Perhaps you have a dependency that does `/// <reference no-default-lib="true" />` (Related: https://github.com/denoland/deno/issues/19035#issuecomment-1537520965)

**Comment by sspilleman** [comment]
I indeed had a dependency that specified indeed exactly that!
Removed it, and working perfectly fine again!
