### ISSUE TITLE
Granting a permission prompt in `deno test` should persist across the entire run

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#18917]
Here I ran `deno test` and got many permission prompts. Deno didn't remember that I granted access to this file.

```
> deno test --filter "streaming api errors while streaming"
✅ Granted read access to "V:\dax\src\lib\rs_lib_bg.wasm".
running 1 test from ./mod.test.ts       
streaming api errors while streaming ... FAILED (35ms)
running 0 tests from ./src/commands/args.test.ts
✅ Granted read access to "V:\dax\src\lib\rs_lib_bg.wasm".
running 0 tests from ./src/commands/mkdir.test.ts
running 0 tests from ./src/commands/pwd.test.ts
✅ Granted read access to "V:\dax\src\lib\rs_lib_bg.wasm".
running 0 tests from ./src/commands/rm.test.ts
✅ Granted read access to "V:\dax\src\lib\rs_lib_bg.wasm".
running 0 tests from ./src/commands/test.ts
...etc...
```

This is because it's creating a `PermissionsContainer` per specifier: https://github.com/denoland/deno/blob/10664908474c262192aa7951cc1b54ee43a9c249/cli/tools/test.rs#L933

I think we should instead create a `PermissionsContainer` per run then encourage people to use `Deno.TestDefinition.permissions` if they are ever testing permissions.

**Comment by TalhaAbid** [comment]
I would like to work on this? any pointers to start?

**Comment by bartlomieju** [comment]
You would need to update `test_specifiers` to create `PermissionsContainer` there instead of directly cloning `permissions` variable. Then change `test_specifier` to accept `PermissionsContainer` instead of `Permissions`.

**Comment by muddlebee** [comment]
@dsherret @bartlomieju I am not able to reproduce this anymore. maybe it is fixed?

**Comment by dsherret** [comment]
Yeah, it's sharing the permissions now.
