### ISSUE TITLE
NPM with aws-sdk: Uncaught TimeoutError: Connection timed out after 0 ms (deno 1.33.1 regression)

### ISSUE THREAD

**Issue by andrewthauer** [denoland/deno#18932]
This seems to be a regression in Deno `>= 1.33` as I don't get this error in `1.32.5` with the exact same code.

I'm started seeing the following error when using `npm:@aws-sdk/client-s3` to list items from an s3 bucket in the latest version of Deno `1.33.1`:

```
error: Uncaught TimeoutError: Connection timed out after 0 ms
    at file:///Users/<foo>/.cache/deno/npm/registry.npmjs.org/@aws-sdk/node-http-handler/3.321.1/dist-cjs/set-socket-timeout.js:7:30
    at ext:deno_node/http.ts:237:17
    at Object.action (ext:deno_web/02_timers.js:147:11)
    at handleTimerMacrotask (ext:deno_web/02_timers.js:64:10)
    at eventLoopTick (ext:core/01_core.js:172:21)
```    

The problematic file is https://github.com/aws/aws-sdk-js-v3/blob/main/packages/node-http-handler/src/set-connection-timeout.ts. The Deno 1.33.0 changlog does list some changes to timeouts in Deno, but these do not stick out as obviously related to this.

**Comment by bartlomieju** [comment]
CC @levex

**Comment by bryanrcampbell** [comment]
I'm running into the same thing here with those particular versions - rolled back for now and it's working

PR: https://github.com/denoland/deno/pull/18783

I don't have much context here but I would think zero [the default] would indicate there is no timeout: https://github.com/aws/aws-sdk-js-v3/blob/main/packages/node-http-handler/src/set-socket-timeout.ts#L4

The connection timeout is implemented that way which seems a bit odd: https://github.com/aws/aws-sdk-js-v3/blob/main/packages/node-http-handler/src/set-connection-timeout.ts#L5-L7

**Comment by levex** [comment]
Looks like the Node side expects a `0` to disable the existing timeout. Oops!

```
If timeout is 0, then the existing idle timeout is disabled.
```

from https://nodejs.org/api/net.html#socketsettimeouttimeout-callback

Expect a PR soon!

**Comment by bryanrcampbell** [comment]
Nice - thanks for the quick fix!
