### ISSUE TITLE
Implement AbortSignal.any()

### ISSUE THREAD

**Issue by shaseley** [denoland/deno#18944]
Explainer: https://github.com/shaseley/abort-signal-any

Spec PR: https://github.com/whatwg/dom/pull/1152

Web platform tests PR (landed): https://github.com/web-platform-tests/wpt/pull/37434 ( renamed to remove 'tentative' in https://github.com/web-platform-tests/wpt/pull/39785)

**Comment by petamoriken** [comment]
I will work on this issue
