### ISSUE TITLE
`Deno.serve` doesn't run as expected in `--watch` mode

### ISSUE THREAD

**Issue by gothammm** [denoland/deno#18960]
`Deno.serve` doesn't run as expected in `--watch` mode.

>**Note**: Not sure if this issue was captured already (did search through the issue list), please feel free to close it if its a duplicate. 

### Version details:
```
deno 1.33.1 (release, aarch64-apple-darwin)
v8 11.4.183.1
typescript 5.0.3
```
### Details to reproduce:
```
// main.ts
await Deno.serve(() => new Response("Hello World!"));
```

```sh
deno run --watch --unstable --allow-net main.ts
```

On file edits, and server restart, it doesn't seem to kill the previous process, and throws the `AddrInUse` error.

### Actual:
```
Watcher File change detected! Restarting!
error: Uncaught AddrInUse: Address already in use (os error 48)
await Deno.serve(() => new Response("Hello World!"));
           ^
    at Object.listen (ext:deno_net/01_net.js:414:39)
    at Object.serve (ext:deno_http/00_serve.js:598:27)
    at file:///Users/<path/to/workspace>/main.ts:3:12
Watcher Process finished. Restarting on file change...
```

### Expected:

It should gracefully restart server

**Comment by K0IN** [comment]
Hei, i still got the same issue on deno 2.4

> deno --version
deno 2.4.0 (stable, release, x86_64-pc-windows-msvc)
v8 13.7.152.6-rusty
typescript 5.8.3


<img width="1086" height="148" alt="Image" src="https://github.com/user-attachments/assets/a802e41e-a181-4a7f-8c9b-d8edd75e3bf4" />

with this file

```typescript
import { Hono } from "hono";

const app = new Hono();

Deno.serve(app.fetch);
```
