### ISSUE TITLE
[Windows] Wrong path on deno.platform

### ISSUE THREAD

**Issue by zekth** [denoland/deno#1896]
While running on windows env the property `rustc_wrapper` in `deno.plaform` shows a wrong path:
`rustc_wrapper = "C:denoprebuilt/win/sccache.exe"`

Runing on Deno 0.3.2

**Comment by ry** [comment]
@piscisaureus Can you check the value of your `Deno.build.gnArgs` ? Is rustc_wrapper correct?

**Comment by zekth** [comment]
Note: It's maybe only the printing of the value. I don't encounter any issue ATM.

**Comment by bartlomieju** [comment]
@zekth is this still the issue with `Deno.build`?

**Comment by zekth** [comment]
@bartlomieju on this build:
```
deno: 0.3.8
v8: 7.4.238
typescript: 3.4.1
```
it ouputs:
```
{ arch: "x64", os: "win", args: "cc_wrapper = \"C:denoprebuilt/win/sccache.exe\"\nclang_use_chrome_plugins = false\nis_cfi =
false\nis_com..." }
```

**Comment by bartlomieju** [comment]
`Deno.build.args` was removed in #2728, is this issue still relevant?

**Comment by zekth** [comment]
If so, closing. Thanks for reminder.
