### ISSUE TITLE
Using self-signed certs with TLS WebSockets causes "No response from ping frame." error event after a short period connectivity.

### ISSUE THREAD

**Issue by alexnygren** [denoland/deno#18977]
Using self signed certificates with Deno.listenTls() results in an error event being received "No response from ping frame". 
 This timeout error occurs after a short time (< 1 minute or so), after the initial connection.  The problem seems to be in the switch to fastwebsockets crate in Rust as far as I can tell.  Prior to 1.31 Deno websockets using self-signed certs seemed to work.  

See:
[chore(ext/websocket): remove ping frame handling (https://github.com/denoland/deno/pull/18847)](https://github.com/denoland/deno/commit/9d7e3f84c852a538937399e542fe4fecb9d52f08)

Example using the deno_std websocket chat example converted to using wss and TLS, and some sample self-signed certs.
[example_reproduction.zip](https://github.com/denoland/deno/files/11389669/example_reproduction.zip)

**Comment by caramboleyo** [comment]
I just saw this issue with a cloudflare certificate, then switched it off anf again have it with the servers own letsencrypt certificate. Also again the websockets do not work. They make some initial pushes, receive initial data from the server and then the client socket is just dead, still having readyState 1, after some time the “No response from ping frame” occurs. When i reconnect the socket same game: i can make some inital sends, then it goes numb.

**Comment by caramboleyo** [comment]
@alexnygren i think it was solved by now, i just tried 1.34.1 and this does not happen anymore.

**Comment by caramboleyo** [comment]
I made a complex testcase now:
https://github.com/caramboleyo/deno-websocket-bug

**Comment by jespertheend** [comment]
@caramboleyo Do you need 90 seconds with the script from https://github.com/denoland/deno/issues/18977#issuecomment-1668085786 as well? For me it happens immediately, but I wonder if it differs per system.

**Comment by caramboleyo** [comment]
At the end of the readme i mentioned that in case of my browser game it also happens immediately.
Yes when i run this script it needs 90 seconds.
And because of that at first i thought the reason might just be some internal timeout.
the script from the op shows the exact same behavior: it works first but after some time it just stops working.
Interestingly with Deno 1.36.0 the "No response from ping frame." error does not appear anymore. It just stops.

**Comment by mmastrac** [comment]
I'll see if I can get this fixed as part of https://github.com/denoland/deno/pull/20518

**Comment by mmastrac** [comment]
Should be fixed with #20518
