### ISSUE TITLE
deno.json: Change to disallow top-level unknown keys?

### ISSUE THREAD

**Issue by ayame113** [denoland/deno#18970]
deno.json currently allows unknown keys only at the top level.

```jsonc
// deno.jsonc
{
  "lint": {
    "unknown key": "hello" // <- disallowed
  },
  "bench": {
    "unknown key": "hello" // <- disallowed
  },
  "fmt": {
    "unknown key": "hello" // <- disallowed
  },
  "unknown key": "hello" // <- allowed
}
```

Personally I find this strange. I also think this may not have been intended in the original design. (https://github.com/denoland/deno/issues/14241)

How about changing the behavior to disallow unknown top-level keys?
The advantage of doing this seems to be that it can detect key's typos (e.g. `import`->`imports`).

**Comment by dsherret** [comment]
I wanted this previously. You can see the discussion here: https://github.com/denoland/deno/pull/15649

**Comment by dsherret** [comment]
Going to close this one. Would be nice, but we need backwards compatibility with tsconfig.json (that said, perhaps in the future we could add warnings for extraneous properties or common mispellings)
