### ISSUE TITLE
Chinese pathnames are not displayed correctly

### ISSUE THREAD

**Issue by wangzishi** [denoland/deno#18983]
deno test:
![image](https://user-images.githubusercontent.com/8288105/236153781-d997d475-fe1d-456c-b988-43faa69bed17.png)

deno import path:

![image](https://user-images.githubusercontent.com/8288105/236153132-d6161e62-336d-431f-867f-7827528d1730.png)

![image](https://user-images.githubusercontent.com/8288105/236154290-63704e5a-01f1-4389-85cb-b45bdd6238a4.png)

The file path is displayed as a percent code resulting in a very poor development experience.

In contrast, tsc looks like everything is fine:
![image](https://user-images.githubusercontent.com/8288105/236154457-6339db14-119f-431c-bbff-91a6a72eda63.png)

**Comment by akirarika** [comment]
6
