### ISSUE TITLE
[Windows] Compiling from sources issue

### ISSUE THREAD

**Issue by zekth** [denoland/deno#1898]
I've followed the manual : https://deno.land/manual.html#buildfromsource

And i've the error:
```
 GetWinSDKDir
    import vs_toolchain
ImportError: No module named vs_toolchain
```
After checking in https://github.com/denoland/deno/blob/master/.appveyor.yml i have updated my PYTHONPATH to `C:\temp\deno\third_party\python_packages`
then i got:
`Exception: Visual Studio version 2015 (from GYP_MSVS_VERSION) not supported. Supported versions are: 2017, 2019`
Problem is i have already installed nodejs before and it sets this env variable. After changing it to :
`GYP_MSVS_VERSION=2017`
It works!
Maybe the documentation needs to be updated or i got a weird configuration?

**Comment by ry** [comment]
Sounds like our python scripts should be updating `sys.path` ... that would take care of the first problem.

Not sure about the other problems - @piscisaureus thoughts?

**Comment by zekth** [comment]
So i found something. Maybe @piscisaureus could confirm:
instead of doing this:
```
git clone --recurse-submodules https://github.com/denoland/deno.git
```
I've done this (with Admin permissions with CMD)
```
git clone -c core.symlinks=true --recurse-submodules https://github.com/zekth/deno.git
```
Because doing the prompt of the config in the repo it appears that symlinks are disabled in the .git/config
```PS
PS C:\temp\deno> git config --get-all --show-origin core.symlinks
file:"C:\\ProgramData/Git/config"       true
file:C:/Users/Zekth/.gitconfig  true
file:.git/config        false
```
So a solution would be to update the git config of the repo i guess? I think the Windows CI is still working due to the cache no?

**Comment by zekth** [comment]
Another issue now is build.py which gives me : 
```
[176/552] COPY ../../third_party/flatbuffers/js/flatbuffers.js gen/flatbuffers.js
FAILED: gen/flatbuffers.js
C:/python27/python.exe ../../build/toolchain/win/tool_wrapper.py recursive-mirror ../../third_party/flatbuffers/js/flatbuffers.js gen/flatbuffers.js
Traceback (most recent call last):
  File "../../build/toolchain/win/tool_wrapper.py", line 29, in <module>
    import win32file    # pylint: disable=import-error
ImportError: DLL load failed: %1 nÆest pas une application Win32 valide.
[181/552] CXX obj/third_party/v8/torque_base/torque_base_jumbo_1.obj
ninja: build stopped: subcommand failed.
```

I've tried to tweak my env variables but can't make it work. Any idea?

**Comment by zekth** [comment]
In addition have to comment this line to make it work:
https://github.com/denoland/chromium_build/blob/89b12c46424e9d18499ebecda24cfc5fad0c2c4f/toolchain/win/tool_wrapper.py#L29

maybe it's due to my env

**Comment by piscisaureus** [comment]
What version of git are you running?

**Comment by zekth** [comment]
I was up to date when i wrote it, so 2.21

**Comment by cybor0** [comment]
Same behavior on 2.17

**Comment by zekth** [comment]
After few updates on Deno repository, seems like the error do not show up anymore. Closing it.

**Comment by prathameshnetake** [comment]
Make sure you select "sysmlinks=true" while installing git to make symlinks work
or you can set this in the config file for git for windows. By default, this is located at `C:\ProgramData\Git\config`.  

Find the `[core]` section and add `symlinks = true` to turn it on.

**Comment by xx1124961758** [comment]
> After few updates on Deno repository, seems like the error do not show up anymore. Closing it.

hi, the error still exists.

**Comment by 95th** [comment]
The issue occurred for me as well on windows 10. It occurs because the symlinks such as build_overrides, buildtools, node_modules etc. are checked out as text files instead of actual links.

I resolved it by following [zekth's suggestion](https://github.com/denoland/deno/issues/1898#issuecomment-471343753) to run following in with admin privileges:

```
git clone -c core.symlinks=true --recurse-submodules https://github.com/zekth/deno.git
```

Perhaps this should be mentioned in the "build from source" manual.

**Comment by zekth** [comment]
I'll update the documentation for the windows user so.

**Comment by ry** [comment]
This is an issue for me still. I followed the above instructions...

**Comment by zekth** [comment]
Just done with a fresh env. Seems to work properly as `setup.py` and `test.py` works. What's the deal with `build_overrides` ?

**Comment by ry** [comment]
After some investigation, I found that `third_party/v8/build` was not a proper symlink. It should be linking to `//build`. Using MINGW bash shell, I did `cd third_party/v8; ln -s ../../build .` and that allowed setup.py to get further.

**Comment by ry** [comment]
Actually the problem was not having `core.symlinks=true` set before checking out the repo. I've update the manual #2601.
