### ISSUE TITLE
All exceptions/errors should exit through the same routine

### ISSUE THREAD

**Issue by ry** [denoland/deno#19]
Currently there are multiple paths:

## Unhandled Promise Exceptions
https://github.com/ry/deno/blob/e401d9e21bd3803d7d329ed8b7c831127f12832f/runtime.ts#L33-L43

## Normal Exceptions 
This is for normal exceptions, which rise up during the `worker.SendBytes()` call. 
https://github.com/ry/deno/blob/e401d9e21bd3803d7d329ed8b7c831127f12832f/util.go#L49-L54
Not that the exception is formatted by V8Worker2's `ExceptionString()`. 
https://github.com/ry/v8worker2/blob/d2017b36edb8429471b08b27123981f1abd5fcb0/binding.cc#L93-L151
Ideally the `ExceptionString` code path would go away and everything would go through `window.onerror`.

**Comment by benjamingr** [comment]
Note that web browsers have a onunhandledrejection and a onrejectionhandled hooks rather than just onerror for promises.

**Comment by bartlomieju** [comment]
Is this still relevant with current implementation?

**Comment by ry** [comment]
I think this is largely dealt with these days - I think there might be some cases where we handle certain exceptions exceptionally.... but this old issue isn't very helpful. Open a new issue if there's something specific.
