### ISSUE TITLE
Build creating unnecessary path

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#1900]
I noticed the `./tools/build.py` is creating `js/deps/https/deno.land/x/` which is no longer the location of the appropriate submodule and then shows up as untracked in git.  I haven't been able to narrow it down where it is coming from though.

**Comment by hayd** [comment]
It seems like you have to delete that directory explicitly, it doesn't reappear when running `test.py` subsequently. I'm not sure whether or not I did something wrong to cause this in https://github.com/denoland/deno/pull/1890/files ...

**Comment by ry** [comment]
Yeah as @hayd said - the behavior of git is to leave the directory when submodules move. Just delete it.

**Comment by kitsonk** [comment]
Yeah, ok, I thought I had removed it and it kept popping up, but I can't reproduce now.
