### ISSUE TITLE
how to import webgpu?

### ISSUE THREAD

**Issue by nczsl** [denoland/deno#19012]
deno 1.33.2 (release, x86_64-pc-windows-msvc)
v8 11.4.183.1
typescript 5.0.3

![image](https://user-images.githubusercontent.com/5241693/236636580-44023544-c5a2-4c2a-86b4-f8402f0ee6a5.png)

**Comment by aapoalas** [comment]
WebGPU has been temporarily removed from the Deno CLI due to performance complications due to its presence: https://github.com/denoland/deno/pull/18094

**Comment by xubaiw** [comment]
I have created a FFI binding for wgpu-native, which exports most of the features of the underlying implementation.

Though the polyfill part has not been implemented yet, a collatz example can be runned with this binding.

repo: https://github.com/xubaiw/deno-wgpu
example: https://github.com/xubaiw/deno-wgpu/blob/main/examples/compute.ts
