### ISSUE TITLE
how to run a include dom 's ts file

### ISSUE THREAD

**Issue by nczsl** [denoland/deno#19015]
![image](https://user-images.githubusercontent.com/5241693/236643892-a452d447-dddd-4714-b3ba-6b69e89da255.png)

**Comment by nczsl** [comment]
the command is  :
deno run --config ./deno.json testport.ts

**Comment by bartlomieju** [comment]
`document` is not available in Deno (because we don't have a DOM). If you want to use `document` with Deno you will need to use something like https://deno.land/x/deno_dom@v0.1.38.
