### ISSUE TITLE
unexpected argument '--unsafely-treat-insecure-origin-as-secure'

### ISSUE THREAD

**Issue by melonchucker** [denoland/deno#19013]
deno run --unsafely-treat-insecure-origin-as-secure='https://example.com' gives an error saying it get's an unexpected argument.

I tried different variations and various hostnames but it still fails.  There is nothing in the permissions section of the docs that mentions this feature.

[https://github.com/denoland/deno/issues/1371] and [https://github.com/denoland/deno/pull/11324] says this was merged

deno --version
deno 1.32.4 (release, x86_64-unknown-linux-gnu)
v8 11.2.214.9
typescript 5.0.3

**Comment by sant123** [comment]
@aapoalas I can no longer find this flag in `deno run --help`. Do you know why it may be removed?

**Comment by aapoalas** [comment]
Uuuh, not sure. It might just be hidden from the help output to avoid bloating it with every single possible flag under the sun.
