### ISSUE TITLE
Limitation: Prompts limit input to 255 characters

### ISSUE THREAD

**Issue by Lenni009** [denoland/deno#19010]
Description:
The `prompt()` interface cuts off anything after 255 characters.

How to reproduce:
1. Open CMD
2. Type `deno` to run the interpreter
3. Type `prompt()` to get a prompt interface
4. Type a very long message
5. Notice it accepting no more than 255 characters.

Expected result:
Don't limit the prompt input. I have a usecase where I need to put in a ~350 character string, which is simply not possible currently.

I'm running Deno 1.33.2 on Windows 10 22H2. CMD and PowerShell both showed this issue.
I could put that whole string in while not in a prompt, so it's isolated to just the prompt.

A workaround is to put the string as CLI arg instead of dynamic prompt input.

Edit: It seems this is not directly related to Deno, but to the web platform in general.

Also here's an actual workaround, but it feels extremely hacky:
```js
async function prompt(promptText) {
	const text = new TextEncoder().encode(`${promptText} `);
	Deno.writeAllSync(Deno.stdout, text);
	const { value: input } = await readLines(Deno.stdin).next();
	return input;
}
```

**Comment by bartlomieju** [comment]
I believe this could be fixed by https://github.com/denoland/deno/pull/18453

**Comment by lino-levan** [comment]
This issue is no longer present in the latest version of Deno.

<img width="1438" alt="image" src="https://github.com/denoland/deno/assets/11367844/f7d1bf20-2bd5-45e5-9cdf-3f2ef55bb37c">

**Comment by Lenni009** [comment]
Can confirm, works!
