### ISSUE TITLE
[node]: `MessageChannel` not exported from `worker_threads`

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/deno#19028]
Node exports the `MessageChannel` class from the [`worker_threads` module](https://nodejs.org/api/worker_threads.html#class-messagechannel). In deno the property exists on the moduel record, but the value is `undefined`. This results in an error when trying to transpile code with `esbuild`.

```js
import * as esbuild from "esbuild";

const res = esbuild.transformSync("console.log('it works')"); // <- this line fails
console.log(res);
```

## Steps to reproduce

1. Clone this repo https://github.com/marvinhagemeister/deno-esbuild-worker-bug
2. Run `deno run -A foo.js`

## Error

```sh
error: Uncaught TypeError: worker_threads2.MessageChannel is not a constructor
    at startWorkerThreadService (file:///project/node_modules/.deno/esbuild@0.17.18/node_modules/esbuild/lib/main.js:2238:48)
    at Module.transformSync (file:///project/node_modules/.deno/esbuild@0.17.18/node_modules/esbuild/lib/main.js:2040:29)
    at file:///project/foo.js:3:21
```

**Comment by marvinhagemeister** [comment]
Did a little digging and the global is there inside the `esbuild` module, but it's not in `node:worker_threads`. My theory is that there is some sort of ordering issue at play. Not sure how to confirm that as I haven't found a way to log something to the console in either our internal js code or from the node compat layer.

**Comment by bartlomieju** [comment]
@marvinhagemeister the property is created and exported here: https://github.com/denoland/deno/blob/ec67e96a124398a2eb12ed8721076ad0147be113/ext/node/polyfills/worker_threads.ts#L209-L211

As for logging - this is internal runtime code, so you need to rely on 
```
Deno.core.print(`${someVar}\n`);
``` 
to print messages as the console is not yet bootstrapped when this code executes.

**Comment by bartlomieju** [comment]
Also a note - currently `worker_threads` is quite broken - ie. you can't really spawn a worker thread using that module.

**Comment by bartlomieju** [comment]
Oh - the fix is actually quite easy - instead of doing `const _MessageChannel = (globalThis as any).MessageChannel` (and similarly `MessagePort` these two should be imported like so:
```
import { MessageChannel, MessagePort } from "ext:deno_web/13_message_port.js";
```
This is because at the time the `ext/node/polyfill/worker_threads.ts` executes these are not yet assigned to global scope (and thus `globalThis.MessageChannel` is undefined). I believe the same thing should be done for `BroadcastChannel`.

**Comment by marvinhagemeister** [comment]
@bartlomieju thanks for sharing. I didn't know about `Deno.core.print()`. These are great findings! I had feeling it had something to do with the global not being defined yet.
