### ISSUE TITLE
perf: Reduce the size of OpCall

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#19020]
Currently the `deno_core::OpCall` looks like this:
```rust
#[pin_project]
pub struct OpCall {
  realm_idx: RealmIdx,
  op_id: OpId,
  promise_id: PromiseId,
  /// Future is not necessarily Unpin, so we need to pin_project.
  #[pin]
  fut: MaybeDone<Pin<Box<dyn Future<Output = OpResult>>>>,
}
```

We can check the size of the struct like so:
```rust
#[test]
fn test_op_call_size() {
  assert_eq!(std::mem::size_of::<OpCall>(), 72);
  assert_eq!(
    std::mem::size_of::<MaybeDone<Pin<Box<dyn Future<Output = OpResult>>>>>(),
    64
  );
}
```

It turns out that using `MaybeDone<>` here adds a whopping 48 bytes to the size:
```rust
#[test]
fn test_op_call_size() {
  assert_eq!(std::mem::size_of::<OpCall>(), 72);
  assert_eq!(
    std::mem::size_of::<MaybeDone<Pin<Box<dyn Future<Output = OpResult>>>>>(),
    64
  );
  assert_eq!(
    std::mem::size_of::<Pin<Box<dyn Future<Output = OpResult>>>>(),
    16
  );
}
```

It's probably worthwhile to get rid of `MaybeDone` in favor of using a custom solution - in case of `OpCall` we should never have a need for `MaybeDone::Gone` variant. (This will probably require bringing back `impl FusedFuture for OpCall`)

**Comment by bartlomieju** [comment]
There are two more things we can optimize for `OpCall`:
- don't store `RealmIdx` on the `OpCall` - instead we can have multiple `FuturesUnordered` (or `JoinSet`) in the `JsRuntimeState` that are "per-realm". That way we don't need to carry around `realm_idx` to now which realm op belongs to.
- Optimize `OpResult` - it can store either `Box<dyn serde_v8::Serializable>` or `serde_v8::Primitive`. The `Primitive` has actually the size of 40 bytes:
```rust
#[test]
fn primitive_size() {
  assert_eq!(std::mem::size_of::<Primitive>(), 40);
}
```
Maybe we should be optimizing it instead of looking into removing `MaybeDone`

**Comment by littledivy** [comment]
For `ZeroCopyBuf` (40)
```rust
  // 16
size_of::<Range<usize>>()
   // 16
  + size_of::<[usize; 2]>() 
   // 8 (discriminant (1) + padding (7))
  + size_of::<usize>()
```

**Comment by k-nasa** [comment]
I'm interested in this issue and considering tackling it. However, I'm not very familiar with the runtime area and I can't fully grasp the specific problem caused by the total struct size of 72 bytes. Could you please explain the concrete impacts and the specific benefits of performance improvement by reducing the size of the struct?

**Comment by bartlomieju** [comment]
@k-nasa thanks for the interest, but we actually don't need to change anything here. We did some experiments and changing `OpCall` (and reducing its size) had no impact whatsoever. Let's not pursue this.
