### ISSUE TITLE
[node]: Missing `.send()` method on child process

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/deno#19029]
# Deno missing `.send()` method on child process

A child process in node has a [`send()`](https://nodejs.org/api/child_process.html#subprocesssendmessage-sendhandle-options-callback) method that is missing in deno. Ran into this error when trying to run a `jest` test. The `jest-worker` module uses this internally to communicate which each test process.

## Steps to reproduce

1. Clone https://github.com/marvinhagemeister/deno-child-process-send-bug
2. Run `deno run -A foo.js`

## Error

```sh
error: Uncaught TypeError: child.send is not a function
  child.send({ hello: "world" }); // <- Throws missing methods
        ^
      at file:///project/foo.js:13:7
```

**Comment by bartlomieju** [comment]
Related https://github.com/denoland/deno/issues/18265 and https://github.com/denoland/deno/issues/17265

**Comment by littledivy** [comment]
Fixed in https://github.com/denoland/deno/pull/21490
