### ISSUE TITLE
[node] unable to resolve index files

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/deno#19023]
Tried running deno on some existing node projects and noticed that it doesn't seem to resolve index files in relative path imports.

```js
import { foo } from "./src"; // <- This fails, should resolve to `./src/index.js`.

console.log(foo);
```

Changing the import manually to `./src/index.js` works.

## Steps to reproduce

1. Clone https://github.com/marvinhagemeister/deno-node-resolve-bug
2. Run `deno run -A foo.js`

## Error

```sh
error: Is a directory (os error 21)
    at file:///projects/node-resolve/foo.js:1:21
```

**Comment by bartlomieju** [comment]
This is actually expected - we don't allow executing CommonJS so when you `deno run -A foo.js` then `foo.js` is treated as an ESM file and obviously in ESM one needs to specify a full path :)

**Comment by dsherret** [comment]
Closing as this is expected behaviour. The same behaviour also occurs in Node ESM.

There is an issue about improving the error message here: https://github.com/denoland/deno/issues/19366
