### ISSUE TITLE
[npm]: Globs are not supported

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/deno#19030]
There is already a warning that it will be supported soon, but I cannot find an existing issue. Opening this one to ensure that this doesn't fall under the radar.

```json
{
  // ...
  "scripts": {
    "test": "mocha test/*.test.js"
  }
}
```

## Steps to reproduce

1. Clone https://github.com/marvinhagemeister/deno-npm-script-glob
2. Run `deno task test`

## Error

```sh
error: Error parsing script 'test'.

Caused by:
    Globs are currently not supported, but will be soon.
      *.test.js
      ~
```

**Comment by dsherret** [comment]
That's also not supported on Windows with `npm run`. Follow https://github.com/denoland/deno_task_shell/issues/6 for updates on this one.

**Comment by marvinhagemeister** [comment]
After doing more testing I'm not so sure if it's really about glob support in the context of npm scripts. From what I can tell the `*` isn't expanded.

foo.js:
```js
#!/usr/bin/env node
console.log(process.argv);
```
package.json
```json
{
  "scripts": {
    "test": "./foo.js *.test.js"
  }
}
```

Output of `npm t`:

```sh
$ npm t

> test
> ./foo.js *.test.js

[
  '/Users/marvinhagemeister/.nvm/versions/node/v18.15.0/bin/node',
  '/Users/marvinhagemeister/dev/test/foo.js',
  '*.test.js'
]
```

Which leads me to conclude that there is no expansion happening. All arguments seem to be treated as strings.

When I run `./foo.js *.test.js` directly in my terminal (zsh), then it tries to expand the glob pattern:

```sh
$ ./foo.js *.test.js 
zsh: no matches found: *.test.js
```

But for npm scripts that doesn't seem to be the case.

**Comment by marvinhagemeister** [comment]
@dsherret Oh I stand corrected! that makes a lot of sense. I didn't know about that. Once I add a couple of files that match the glob pattern it's expanded. Thanks for clearing this up!
