### ISSUE TITLE
WebSocket dropping messages when many are sent

### ISSUE THREAD

**Issue by sgwilym** [denoland/deno#19041]
Since v1.34 I noticed some previously succeeding test cases involving WebSockets fail. I investigated and it seems that Deno's WebSocket implementation now drops messages if many are sent in a short timeframe.

It's easy for me to reproduce this locally. Here's a reproduction repo: https://github.com/sgwilym/deno-ws-bug-repro-2

Basically you send something like 1000 messages, and some number under 1000 will be received (I consistently see only 988 received by the local server).

**Comment by nhrones** [comment]
I think you were correct - dropped messages!

There seems to be messages that are dropped by the server
// server.ts
```ts
  socket.onmessage = (e) => {
    console.log(`message number:${e.data}, messagesReceived:${messagesReceived}`)
    messagesReceived++
  };
```

// message 253 and 254 missing?
message number:252, messagesReceived:252
message number:255, messagesReceived:253


// all missing messages (exactly 130 apart)
// missing messages
253 254
383 384
513 514
643 644
773 774
903 904

**Comment by nhrones** [comment]
Looks like a buffer issue!

Client sends 1 to 254  Server receives  1 to 254
Client sends 255 Server receives  253

**Comment by bartlomieju** [comment]
Thanks for debugging it @nhrones, we'll make sure this is fixed.

CC @littledivy
