### ISSUE TITLE
Req/Sec benchmark is missing `node_http`

### ISSUE THREAD

**Issue by zaynv** [denoland/deno#1907]
The [req/sec benchmark](https://deno.land/benchmarks.html#req-per-sec) mentions that:

> deno is a fake http server that doesn't parse HTTP. It is comparable to node_tcp .
deno_net_http is a web server written in TypeScript. It is comparable to node_http .
hyper is a Rust HTTP server and represents an upper bound.

I was confused by this line: 

> deno_net_http is a web server written in TypeScript. It is comparable to node_http. 

There doesn't seem to be a `node_http` in the graph, so what are we supposed to be comparing `deno_net_http` with?

**Comment by kevinkassimo** [comment]
`node`: node HTTP
`node_tcp`: node TCP
`deno`: deno TCP
`deno_net_http`: deno using `std/http/server.ts`

The benchmark is not very satisfactory at this moment, but a major internal design update and performance boost is coming pretty soon (`deno_core_single` and `deno_core_multi` are experimental benchmarks for the pending new design)

**Comment by zaynv** [comment]
Oh I see looking forward to seeing with new design. If I understand correctly `node_http` is referring to `node` in the graph? Thanks, and feel free to close this.

**Comment by bartlomieju** [comment]
Can be closed CC @ry

**Comment by ry** [comment]
Thanks
