### ISSUE TITLE
Upgrade thiserror crate?

### ISSUE THREAD

**Issue by MrMarble** [denoland/deno#19081]
[thiserror crate](https://crates.io/crates/thiserror) has fixed version `=1.0.38` on workspace https://github.com/denoland/deno/blob/3e1cc5dbf59618f22218ba7698922adbb26f16ec/Cargo.toml#L135

Could this be updated to latest `1.0.40`? Or at least use a less restricting semantic verion, `^1.0.38`

**Comment by bartlomieju** [comment]
Already covered by https://github.com/denoland/deno/pull/19073
