### ISSUE TITLE
LS reaches heap limit, high CPU and memory usage

### ISSUE THREAD

**Issue by albnnc** [denoland/deno#19088]
When workspace document preload landed (which idea is loved actually), language server became almost unusable for big projects.

<details>
<summary>High resources usage when anything is done within the project (e.g. symbol is getting hovered)</summary>

Screenshots are made on Apple Silicon machine, but this behaviour occurs on both MacOS and Linux. Windows wasn't tested.

![telegram-cloud-document-2-5379610077709740255](https://github.com/denoland/deno/assets/20284259/17116ff7-ddc9-4c80-bcf7-32b0bf1284c5)

![telegram-cloud-document-2-5379610077709740257](https://github.com/denoland/deno/assets/20284259/a6448545-1347-43d5-a7f0-daf04111c5f7)
</details>

I'm not sure wether LS failures were present on the first Deno version with document preload feature, or they've came after some patches. However, now Deno LS fails multiple times, then VSCode stops getting Deno LS up.

<details>
<summary>Sample log</summary>

```
Starting Deno language server...
  version: 1.33.2 (release, aarch64-apple-darwin)
  executable: /Users/albnnc/.deno/bin/deno
Connected to "Visual Studio Code" 1.78.0
  Auto-resolved configuration file: "file:///<...>/deno.json"
Warning: "files" configuration is deprecated. Please use "include" and "exclude" instead.
Warning: "files" configuration is deprecated. Please use "include" and "exclude" instead.
Setting import map from configuration file: "./import_map.json"
  Resolved import map: "file:///<...>/import_map.json"
Enabling import suggestions for: https://crux.land
Enabling import suggestions for: https://deno.land
Enabling import suggestions for: https://x.nest.land
Download https://x.nest.land/.well-known/deno-import-intellisense.json
Download https://intellisense.nest.land/deno-import-intellisense.json
Hit the language server document preload limit of 1000 file system entries. You may want to use the "deno.enablePaths" configuration setting to only have Deno partially enable a workspace.
Server ready.

<--- Last few GCs --->

[11073:0x140008000]    12592 ms: Mark-Compact (reduce) 1400.1 (1427.1) -> 1399.5 (1425.6) MB, 40.54 / 0.00 ms  (+ 100.7 ms in 25 steps since start of marking, biggest step 6.8 ms, walltime since start of marking 152 ms) (average mu = 0.322, current mu = 0

<--- JS stacktrace --->


#
# Fatal JavaScript out of memory: Reached heap limit
#

[Error - 18:00:40] The Deno Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
```
</details> 

The temporary workaround is to use older version of Deno.

Most likely, related: https://github.com/denoland/deno/issues/18955

**Comment by dsherret** [comment]
This is probably because of https://github.com/denoland/deno/issues/18935 (pointers are temporarily no longer compressed due to a bug in v8) in addition to the preload change.

In vscode_deno 3.18.0 with Deno 1.33.3 you can disable the document preload limit by specifying `"deno.documentPreloadLimit": 0` in the vscode workspace configuration.

**Comment by dsherret** [comment]
Does this still occur in Deno 1.33.4? We increased the default language server memory limit to match what tsserver does. Also, you can configure the maximum memory as of vscode_deno 3.19.0 by setting the `deno.maxTsServerMemory` property:

```json
{
  "deno.enable": true,
  "deno.maxTsServerMemory": 3072
}
```

**Comment by albnnc** [comment]
Didn't test this problem with 1.33.4 + 3.19.0 pair, but the 1.34.0 + 3.19.1 one seems to work pretty well. Tested it for the half of a day, Deno LS didn't crash a single time.

It looks like this particular issue is resolved. I will close it and re-open in case of any new similar logs. Thanks!
