### ISSUE TITLE
Deno repl fails with variable undefined but only for divisions

### ISSUE THREAD

**Issue by MarcCoquand** [denoland/deno#19094]
Hi! I'm trying to run the following function within the deno repl

```
const calculateSplit = (paymentAmount: number, fee: { relative: number, fixed: number }): { commiss
ion: number, diff: number } => {
   const commission = Math.round(((paymentAmount) / 100) * fee.relative / 100) + fee.fixed;
   const diff = paymentAmount - commission;
   return {
     commission,
     diff,
   }
}
```

Which fails with

```
parse error: Expected '}', got '<eof>' at 2:90
Uncaught ReferenceError: paymentAmount is not defined
    at <anonymous>:2:21
Uncaught SyntaxError: Illegal return statement
parse error: Expression expected at 1:1
```

However, changing it to 
```
 const calculateSplit = (paymentAmount: number, fee: { relative: number, fixed: number }): { commission: number, diff: number } => {
  const commission = Math.round((paymentAmount) * fee.relative) + fee.fixed;
  const diff = paymentAmount - commission;

  return {
    commission,
    diff,
  }
}
```
and it works without fail. 

**EXPECTED BEHAVIOUR**: I would assume that it'd be possible to do division on input variables within the repl.
**WORKAROUND**: Breaking out paymentAmount /100 a separate variable solves the issue and makes it work.

**Comment by bartlomieju** [comment]
What version of Deno are you on? I just tried it with v1.33.2 and it works fine.

**Comment by dsherret** [comment]
It's when copy and pasting it will insert a newline before one of the final `}`. It's because it's hard to detect if a `/` is a regex literal or not when tokenizing, so right now if there's two forward slashes then it will have trouble figuring that out.
