### ISSUE TITLE
Add FAQ section to deno.land

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#1910]
It came up in Gitter discussion that there's no FAQ section on the website and IMHO it's a good idea to have one. 

Please provide questions you're curious about below so we can compile some list.

**Comment by bartlomieju** [comment]
- What is Deno?
- How is Deno different that node.js?
- Should I switch from node to Deno?

**Comment by ry** [comment]
Sure, but rather than FAQ, let's carefully work it into the manual. I don't like there to be multiple sources of documentation. This seems like good information for the introduction section.

**Comment by kevinkassimo** [comment]
Or an alternative is linking to Stackoverflow. We can create self-answered questions I believe

**Comment by zekth** [comment]
I agree with @ry on this point. Multiple sources is a pain IMO.

**Comment by bartlomieju** [comment]
I'm revisiting this because lately there's been again a lot of repeating question on gitter about Deno. @ry would you reconsider to have FAQ section on website?

**Comment by ry** [comment]
Happy to have the questions added to the manual - I want to avoid bifurcating the docs.
