### ISSUE TITLE
EPERM: Operation not permitted when using Deno.Command with pkexec

### ISSUE THREAD

**Issue by sant123** [denoland/deno#19112]
Consider this example, the `pkexec` command will try to run `ping` with sudo asking the user's password.

After 8 seconds, it will try to abort it but it can't. So it throws an exception. But after 12 seconds it will try to abort it but no exception occurs and the process is still running.

I tested with `ChildProcess.kill` and throws in both cases.

```ts
const controller = new AbortController();

const command = new Deno.Command("pkexec", {
  args: ["ping", "::1"],
  signal: controller.signal,
});

command.spawn();

// At here, you should see a screen from your desktop (Gnome, KDE) asking for your root's password. 
// Enter it before the 8 seconds.

setTimeout(() => {
  try {
    controller.abort();
    console.log("Not expected to log");
  } catch (error) {
    console.error(error);
  }
}, 8000);

setTimeout(() => {
  try {
    controller.abort();
    console.log("Not expected to log, but it logs!!!");
  } catch (error) {
    console.error(error);
  }
}, 12000);

```

My questions are:

+ Both `ChildProcess.kill` and `AbortController.abort` should have the same behavior right? Throwing in both cases.
+ Why the process can't be aborted/killed? Deno spawned the process so in some way would have some ownership in it right? Also hitting Ctrl + C stops the Deno process and the `pkexec` command with `ping` so in some way could be stopped inside Deno?

This has been tested in Fedora 38, but the case may be related to other operative systems.

Thanks!

**Comment by sigmaSd** [comment]
the fact that it can't abort is expected, you spawned the process with pkexec, the only way to kill it in is with pkexec kill, -> the parent process don't actually have some special permission even if its the one who invoked it

for the second part of your question, (the second abort behaviour is different)  seems its just like abort is assumed to only be called once, calling it twice probably breaks some internal assumptions, if this was in rust it abort should consume the controller probably, but you can't model the same thing in js

**Comment by sant123** [comment]
@sigmaSd thanks. However I’m curious why works with `sudo` instead of `pkexec`?

**Comment by sigmaSd** [comment]
I'm guessing pkexec uses fine grained control, and requires permissions to be setup through policykit

Its unclear in my mind though so I can't explain more

**Comment by sant123** [comment]
Don't worry @sigmaSd 😉 I played with Policy Kit and finally could make it run for my needs. At the end I run `pkexec` for spawning and killing the process; also with _polkit_ actions I can set additional config for them.

Thank you for your response.

**Comment by sigmaSd** [comment]
It would be great if you share what you did so wee can learn from this

**Comment by sant123** [comment]
Basically I'm developing a VPN Client for AWS. Currently exists support for Ubuntu, but for other flavors (Fedora in my case) most people use this project https://github.com/samm-git/aws-vpn-client

The solution is good, but had to open two terminals and enter my sudo password in there. So wanted to create a web application where I click connect and the program handles everything for me until I type my sudo password, but in this case won't be in a terminal but in an authentication dialog provided from my Gnome desktop. Therefore I don't need to return to the terminal where I started the process, I just handle everything from the web 😄 

So polkit looks good for this approach using `pkexec`, this is the code I'm using for creating the URL redirect for SAML authentication, authenticate with the SAML response and disconnect from the VPN:

```ts
const HOST = "SET_YOUR_HOST_HERE";

const BIN = "openvpn/openvpn";
const CONF = "vpn.conf";
const PORT = 443;
const PROTO = "udp";
const RAND = crypto.randomUUID();

const SRVN = await Deno.resolveDns(`${RAND}.${HOST}`, "A");
const SRV = SRVN.at(0) ?? "";

const decoder = new TextDecoder();

export async function beginSAML() {
  const command = new Deno.Command("openvpn/begin-aws.sh", {
    args: [BIN, CONF, PROTO, SRV, PORT.toString()],
  });

  const output = await command.output();
  const raw = decoder.decode(output.stdout);

  const tokens = raw.split(/:(?!\/)/);

  const url = tokens[8];
  const sid = tokens[6];

  return { url, sid };
}

export function authenticate({ sid, SAML }: { sid: string; SAML: string }) {
  const command = new Deno.Command("pkexec", {
    args: [
      "--keep-cwd",
      "openvpn/connect-aws.sh",
      BIN,
      CONF,
      PROTO,
      SRV,
      PORT.toString(),
      sid,
      SAML,
    ],
  });

  const process = command.spawn();

  return { pid: process.pid.toString() };
}

export async function disconnect(pid: string) {
  const command = new Deno.Command("pkexec", {
    args: ["openvpn/disconnect-aws.sh", pid],
  });

  const output = await command.output();

  return output.code;
}

```

Having each task in a shell file offers me to apply specific configuration to the actions in the policy kit. e.g: description for why authentication is needed, store sudo password for a brief time to make future connections/disconnections faster and grant permissions to other actions if one has them already for a short period.

This is my policy file for that:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE policyconfig PUBLIC
 "-//freedesktop//DTD PolicyKit Policy Configuration 1.0//EN"
 "http://www.freedesktop.org/standards/PolicyKit/1.0/policyconfig.dtd">

<policyconfig>
    <action id="com.ferrums.aws-client-vpn.connect">
      <description>AWS Client VPN Connect</description>
      <message>Connect with AWS Client VPN</message>
      <defaults>
        <allow_any>auth_admin</allow_any>
        <allow_inactive>auth_admin</allow_inactive>
        <allow_active>auth_admin_keep</allow_active>
      </defaults>
      <annotate key="org.freedesktop.policykit.exec.path">/home/the-user/aws-client-vpn/openvpn/connect-aws.sh</annotate>
      <annotate key="org.freedesktop.policykit.imply">com.ferrums.aws-client-vpn.disconnect</annotate>
    </action>
    <action id="com.ferrums.aws-client-vpn.disconnect">
      <description>AWS Client VPN Connect</description>
      <message>Disconnect from AWS Client VPN</message>
      <defaults>
        <allow_any>auth_admin</allow_any>
        <allow_inactive>auth_admin</allow_inactive>
        <allow_active>auth_admin_keep</allow_active>
      </defaults>
      <annotate key="org.freedesktop.policykit.exec.path">/home/the-user/aws-client-vpn/openvpn/disconnect-aws.sh</annotate>
    </action>
</policyconfig>

```

These are the contents from the 3 file shells:

#### begin-aws.sh

```sh
#!/bin/sh

BIN=$1
CONF=$2
PROTO=$3
SRV=$4
PORT=$5

OVPN_OUT=$($BIN --config "${CONF}" --verb 3 \
     --proto "$PROTO" --remote "${SRV}" "${PORT}" \
     --auth-user-pass <( printf "%s\n%s\n" "N/A" "ACS::35001" ) \
    2>&1 | grep AUTH_FAILED,CRV1)

echo $OVPN_OUT

```

#### connect-aws.sh

```sh
#!/bin/sh

BIN=$1
CONF=$2
PROTO=$3
SRV=$4
PORT=$5
SID=$6
SAML=$7

exec sudo bash -c "$BIN --config "${CONF}" \
    --verb 3 --auth-nocache --inactive 3600 \
    --proto "$PROTO" --remote $SRV $PORT \
    --script-security 2 \
    --auth-user-pass <( printf \"%s\n%s\n\" \"N/A\" \"CRV1::${SID}::${SAML}\" )"

```

#### disconnect-aws-sh

```sh
#!/bin/sh

PID=$1

kill $1

```

There is more behind this, but this is the core for establishing connections with AWS in a more highly level way.

**Comment by sigmaSd** [comment]
thanks a lot @sant123  for taking the time to share this!
