### ISSUE TITLE
Colors capability detection

### ISSUE THREAD

**Issue by zekth** [denoland/deno#1911]
I've started an issue / PR in deno_std. Moving in to Deno itself.
ref: https://github.com/denoland/deno_std/pull/244

**TLDR**
We can detect color capabilities in some cases based on env var / platform.
For example on W7 only TTY with `TERM` env variable = `xterm` are capable of parsing colors.
On W10, TERM is not defined but colors are available.

In the deno,platform there is no information about the version of the Operating System. Could we have it in a future build?
@kevinkassimo  ?

**Comment by kitsonk** [comment]
Based on experiences with browser "sniffing" (e.g. "if IE then...") is folly and ideally we should find some way to detect support by other means.  Colour support is not determined by a version of an operating system.

For example, I assume Bash running under Windows 7 in Cygwin would support ANSI colours, even if it was the Deno binary.

For [reference](https://nodejs.org/api/os.html#os_os_release), Node.js calls uname on POSIX systems and `GetVersionExW()` on Windows systems.  While it is potentially useful for other reasons, I don't think it is a good way to do ANSI colour support.

**Comment by afinch7** [comment]
Not really a fan of "sniffing" either. One of the primary benefits of javascript is it can be abstracted from the host. This should really be abstracted out in rust or the deno js libs.

**Comment by ry** [comment]
It is abstracted out into Rust. We provide the boolean `Deno.noColor` which looks at the NO_COLOR env var. This prevents every color user to allow access to environment vars. I think it's not unreasonable to make `Deno.noColor` a bit smarter.

**Comment by zekth** [comment]
ref for the chalk color detection: https://github.com/chalk/supports-color/blob/master/index.js

> Colour support is not determined by a version of an operating system

As i said it's a combination of variables. But only for w7. Others seems ok.

>  I assume Bash running under Windows 7 in Cygwin would support ANSI colours

Wrong. On W7 with cygwin it won't work. But on W7 with git bash it works. Gitbash using XTERM
And as we discussed on the referenced issue, everything happens on the Rust side like @ry suggested.

**Comment by zekth** [comment]
For example on W7:
![2019-03-12 09_22_31-MINGW64__c_projects_deno_std](https://user-images.githubusercontent.com/6959636/54185070-7040cc00-44a8-11e9-9a57-78a5f8ded417.png)
![2019-03-12 09_22_42-foo ts - deno_std - Visual Studio Code  Administrator](https://user-images.githubusercontent.com/6959636/54185074-720a8f80-44a8-11e9-83cb-af96e5f3ff85.png)

**Comment by zekth** [comment]
After few reflections, it may be easier to just check if is TTY like @ry purposed:

> so we should have some function like fn stdoutCanHandleColors() -> bool { atty::is(atty::Stream::Stdout) && env()["TERM"] == "xterm" }

Checking TERM env var is really specific, like shown in chalk source code. At first we can add check for "xterm" and we implement case after we encounter problems? Or we simply admit the terminal have to handle colors like `atty::is(atty::Stream::Stdout) && !Some(env()["NO_COLORS"])`

**Comment by zekth** [comment]
> After few reflections, it may be easier to just check if is TTY like @ry purposed:
> 
> > so we should have some function like fn stdoutCanHandleColors() -> bool { atty::is(atty::Stream::Stdout) && env()["TERM"] == "xterm" }
> 
> Checking TERM env var is really specific, like shown in chalk source code. At first we can add check for "NO_COLORS" and we implement case after we encounter problems? Or we simply admit the terminal have to handle colors like `atty::is(atty::Stream::Stdout) && !Some(env()["NO_COLORS"])`

**Comment by ry** [comment]
Deno.noColor and Deno.isTTY() exist now.
