### ISSUE TITLE
[bug] type display doesn't work correctly with deno.json imports

### ISSUE THREAD

**Issue by Lenni009** [denoland/deno#19121]
Let's say we're importing `parse` from https://deno.land/std/flags/mod.ts.
If we do that at the top of the file with `import { parse } from <url>`, everything works fine. If I do the `parse(Deno.args)`, and hover over it, I get the correct interface displayed:
![grafik](https://github.com/denoland/deno/assets/91371655/2e3d9e60-ca1f-4c09-9ce3-39137a356d2f)

If I import it via deno.json, and then just do `import { parse } from 'flags'`, it has the `any` type.

deno.json:
```json
{
  "imports": {
    "flags": "https://deno.land/std@0.186.0/flags/mod.ts",
  }
}
```
![grafik](https://github.com/denoland/deno/assets/91371655/a891320f-3660-4b8d-9919-85f8c6c79196)

Just copying the URL to the main TS file instead of the json immediately brings back the type.

Expected:
Always display the proper type information, like it does when importing directly from the URL, without import map.

**Comment by bartlomieju** [comment]
@dsherret could you take a look at this problem?

**Comment by nayeemrmn** [comment]
Looks fixed

**Comment by nayeemrmn** [comment]
> ![grafik](https://user-images.githubusercontent.com/91371655/238138034-a891320f-3660-4b8d-9919-85f8c6c79196.png)

Actually looking at this it seems the `flags` import is unresolved. So the LSP is probably not detecting the import map. Maybe your `deno.json` is not in the root directory? If so, that's tracked in #14245 and https://github.com/denoland/vscode_deno/issues/787.

**Comment by Lenni009** [comment]
Just tested again, and it worked as expected. Now that you mention it, the import really does look unresolved. I wasn't very experienced back when I opened this issue 😅
