### ISSUE TITLE
Possible TCP/TLS connection leak

### ISSUE THREAD

**Issue by sergeysolovev** [denoland/deno#19120]
@dsherret 

Run this script with `deno run --allow-net repro.ts`

```ts
import { delay } from "https://deno.land/std@0.187.0/async/mod.ts";

const REPLY_DELAY = 5000;

async function runServer() {
  const tcpServer = Deno.listen({ port: 8000 });
  console.log("Listening at *:8000");

  for await (const conn of tcpServer) {
    const httpConn = Deno.serveHttp(conn);
    console.log("New #", httpConn.rid);
    for await (const requestEvent of httpConn) {
      await delay(REPLY_DELAY);
      requestEvent.respondWith(
        new Response(Date.now().toString(), { status: 200 }),
      );
    }
    httpConn.close();
    console.log("Closed #", httpConn.rid);
  }
}

runServer();

setInterval(async () => {
  const res = await fetch("http://localhost:8000");
  console.log("res", await res.text());
}, 2500);

```

Check tcp connections, I use `lsof` on macos. They keep growing. Now set `REPLY_DELAY` value to `0` and it keeps 1 pooled connection as expected.

<img width="1375" alt="Screenshot 2023-05-13 at 9 42 58 PM" src="https://github.com/denoland/deno/assets/5831301/8a401a25-720d-47e4-81e2-6c9205cef500">

**Comment by bartlomieju** [comment]
I believe this is not a leak but rather an expected behavior.

In your reproduction all requests (and connections) are handled serially (and not concurrently) because you got two nested `for await` loops and a delay there - so a new connection/request is not getting responded before the delay you provided finishes.

If you change your code like so:
```ts
import { delay } from "https://deno.land/std@0.187.0/async/mod.ts";

const REPLY_DELAY = 5000;

async function runServer() {
  const tcpServer = Deno.listen({ port: 8000 });
  console.log("Listening at *:8000");

  for await (const conn of tcpServer) {
    (async () => {
      const httpConn = Deno.serveHttp(conn);
      console.log("New #", httpConn.rid);
      (async () => {
        for await (const requestEvent of httpConn) {
          await delay(REPLY_DELAY);
          requestEvent.respondWith(
            new Response(Date.now().toString(), { status: 200 }),
          );
        }
        httpConn.close();
        console.log("Closed #", httpConn.rid);
      })();
    })();
  }
}

runServer();

setInterval(async () => {
  const res = await fetch("http://localhost:8000");
  console.log("res", await res.text());
}, 2500);

```

Then the issue goes away and there are 2 or 3 open connections at the same time. Please noticed the two "async IIFEs" there - using them allows the server to handle connections/requests concurrently.

**Comment by sergeysolovev** [comment]
@bartlomieju

Thank you for your suggestion, but my point was a bit different. Something that I called the “connection leak” is coming from the client-side of the script. I put them into the same script just for sake of simplicity. Imagine that the server piece code is a black box we can’t control but have to use for some reason. Polling with `fetch` from the client script causes opening more and more TCP connections from the client-side. I expected the client to either reuse a single (or a few) connection(s) or to close the connection after the request is complete. Please feel free to correct me if I’m wrong as my knowledge of TCP and networking is very limited.

Another issue which is less important but it’s still there – your suggested solution doesn’t lint with `require-await` warning.

**Comment by sergeysolovev** [comment]
@bartlomieju same here

```
deno 1.33.3 (release, aarch64-apple-darwin)
v8 11.4.183.2
typescript 5.0.4
```

To me the number of open TCP connection is 120 after ~10 minutes of running that script and keep growing.

<img width="1473" alt="Screenshot 2023-05-15 at 3 03 48 PM" src="https://github.com/denoland/deno/assets/5831301/ed4ea12f-a6fc-40af-8de4-677603450c8d">

**Comment by levex** [comment]
I have not ran this on my laptop but TCP keepalives are known to cause weird and confusing behavior:

https://blog.cloudflare.com/when-tcp-sockets-refuse-to-die/

http://codearcana.com/posts/2015/08/28/tcp-keepalive-is-a-lie.html?ref=blog.cloudflare.com

@sergeysolovev how long do you keep running this code and does the lsof output just keep growing or does it max out at some point?

**Comment by sergeysolovev** [comment]
@levex 

~10 minutes, the number of open TCP connections had only been growing during that period of time. Also please notice from the code, that I don’t explicitly set `keepalive`.

**Comment by levex** [comment]
Can you run `sw_vers` so that we can see what macOS you're running?

I'm on `22E261` and my connection count stays the same.

**Comment by levex** [comment]
I am unable to reproduce this @sergeysolovev :-(

**Comment by bartlomieju** [comment]
@sergeysolovev are you able to reproduce it anymore on latest version?

**Comment by sergeysolovev** [comment]
@bartlomieju makes sense to close it as fetch is rewritten to use hyper anyway
