### ISSUE TITLE
Github releases have debug symbols

### ISSUE THREAD

**Issue by curtisallen** [denoland/deno#19136]
The Deno binaries produced by the release process have debug symbols. 
Can we change the releases to ship release versions without debug symbols? 
In deno 1.33.3 stripping debug symbols result in a 30% reduction in file size.

```console
root@1de9ce6941f5:/# ls -tlraph deno
-rwxr-xr-x 1 root root 108M May 12 11:53 deno
root@1de9ce6941f5:/# strip -s deno -o deno.strip
root@1de9ce6941f5:/# ls -tlraph deno.strip
-rwxr-xr-x 1 root root 75M May 15 20:23 deno.strip
```

**Comment by levex** [comment]
At this point I think it's a valid tradeoff - we need those symbols to be able to debug panics which can happen with Deno.

You should always be able to strip them yourself, however.
