### ISSUE TITLE
Deno 1.33.3 lsp has crashed 5 times in last 3 minutes (whenever it runs)

### ISSUE THREAD

**Issue by cacilhas** [denoland/deno#19148]
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 1.33.3
Args: ["/home/.../.cargo/bin/deno", "lsp"]

thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /home/.../.cargo/registry/src/index.crates.io-6f17d22bba15001f/dprint-swc-ext-0.9.0/src/view/generated.rs:14469:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Error - 11:23:00] The Deno Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information

**Comment by dsherret** [comment]
I see this only occurs when building with the latest rust. You may want to install Deno using a pre-built binary.
