### ISSUE TITLE
`Request#formData` corrupts non-ASCII file names

### ISSUE THREAD

**Issue by lionel-rowe** [denoland/deno#19142]
The form data returned from `await req.formData()` on a `Request` object corrupts non-ASCII file names. For example, `"'文字.txt"` becomes `"æ\x96\x87å­\x97.txt"`. Based on a [mojibake decoder tool I made a while back](https://ioiw9.csb.app/diagnose?mojibake=%C3%A6%C2%96%C2%87%C3%A5%C2%AD%C2%97), it looks to be one of either iso88591, iso88594, iso88599, iso885910, iso885914, or iso885915 encodings.

File content and text inputs are unaffected.

The issue affects `Deno.serveHttp`, as well as [deno_std http/server](https://deno.land/std@0.187.0/http/server.ts?s=serve) and [denoland/fresh](https://github.com/denoland/fresh) (the latter two presumably because they use `Deno.serve` under the hood).

## Repro

https://dash.deno.com/playground/non-ascii-file-name-repro

Upon submitting the form, the results are as follows:

```json
{
    "file": {
        "name": "æå­.txt",
        "contents": "文字"
    },
    "text": "文字"
}
```

## Code for repro

```ts
async function serveHttp(conn: Deno.Conn) {
    for await (const requestEvent of Deno.serveHttp(conn)) {
        const req = requestEvent.request

        let data

        if (req.method === 'POST') {
            const formData = await req.formData()

            const file = formData.get('file')
            const text = formData.get('text')
            const name = file.name
            const contents = new TextDecoder().decode(new Uint8Array(await file.arrayBuffer()))

            data = { file: { name, contents }, text }

            console.info(data)
        }

        const res = new Response(
            `<!DOCTYPE html>
            <html lang="en">
            <head>
                <meta charset="utf-8">
                <title>repro</title>
            </head>
            <body>
                <form method="post" action="" enctype="multipart/form-data">
                    <p><input type="file" required name="file"></p>
                    <p><input type="text" name="text" placeholder="text" value="文字"></p>
                    <p><input type="submit"></p>
                </form>
                ${data
                    ? `<pre>${
                        JSON.stringify(data, null, 4).replaceAll(/[&<>'"]/g, (m) => `&#${m.codePointAt(0)!};`)
                    }</pre>`
                    : ''
                }
            </body>
            <script>
                const file = new File(['文字'], '文字.txt')
                const dt = new DataTransfer()
                dt.items.add(file)

                document.querySelector('[name=file]').files = dt.files
            </script>
            </html>`,
            { headers: { 'Content-Type': 'text/html' } }
        )

        requestEvent.respondWith(res)
    }
}

for await (const conn of Deno.listen({ port: 443 })) serveHttp(conn)
```

**Comment by lionel-rowe** [comment]
As a workaround, looks like it's trivial to convert iso8859 to utf8 with the help of `TextDecoder`, and can be done idempotently if you special-case codepoints that are already over 0xff:

```ts
function iso8859OrUtf8ToUtf8(isoOrUtf8Str: string) {
	const d = new TextDecoder()
	const spans: (string | number[])[] = []

	for (const char of [...isoOrUtf8Str]) {
		const cp = char.codePointAt(0)!

		if (cp > 0xff) {
			spans.push(char)
		} else {
			if (!Array.isArray(spans.at(-1))) {
				spans.push([])
			}

			;(spans.at(-1) as number[]).push(cp)
		}
	}

	return spans
		.map((x) => typeof x === 'string' ? x : d.decode(Uint8Array.from(x)))
		.join('')
}

iso8859OrUtf8ToUtf8("文字.txt, æ\x96\x87å\xad\x97.txt")
// => "文字.txt, 文字.txt"
```

**Comment by andreubotella** [comment]
It seems like the issue here is that Deno is parsing each `multipart/form-data` header block with `Headers`. HTTP headers are always Latin-1 (or well, they are probably pure byte octets in the spec, but a bunch of legacy applications interpret them as Latin-1), but the various strings in `multipart/form-data` are encoded with the form page's encoding (and servers should parse them as UTF-8).

> As a workaround, looks like it's trivial to convert iso8859 to utf8 with the help of `TextDecoder`, and can be done idempotently if you special-case codepoints that are already over 0xff:
> 
> ```ts
> function iso8859OrUtf8ToUtf8(isoOrUtf8Str: string) {
> 	const d = new TextDecoder()
> 	const spans: (string | number[])[] = []
> 
> 	for (const char of [...isoOrUtf8Str]) {
> 		const cp = char.codePointAt(0)!
> 
> 		if (cp > 0xff) {
> 			spans.push(char)
> 		} else {
> 			if (!Array.isArray(spans.at(-1))) {
> 				spans.push([])
> 			}
> 
> 			;(spans.at(-1) as number[]).push(cp)
> 		}
> 	}
> 
> 	return spans
> 		.map((x) => typeof x === 'string' ? x : d.decode(Uint8Array.from(x)))
> 		.join('')
> }
> 
> iso8859OrUtf8ToUtf8("文字.txt, æ\x96\x87å\xad\x97.txt")
> // => "文字.txt, 文字.txt"
> ```

I'm pretty sure this doesn't work for every UTF-8 input. But it will work as a workaround if you only use it for multipart/form-data file names.
