### ISSUE TITLE
Cannot implement JSX Factory with a simple local module

### ISSUE THREAD

**Issue by cowboyd** [denoland/deno#19161]
I'm trying to implement a JSX factory from a local module. Here is an example that implements a html5-boilerplate starter. https://github.com/cowboyd/html/blob/17eace726750333358090a371fed48319f349065/examples/html5-boilerplate-icremental-dom.tsx

While the language server seems to find everything ok, and the code compiles on the TypeScript playground, if I try to run it, I get the following error:

```
$ deno --version
deno 1.33.2 (release, aarch64-apple-darwin)
v8 11.4.183.1
typescript 5.0.3
$ deno run examples/html5-boilerplate-icremental-dom.tsx
error: The module's source code could not be parsed: Unexpected token `html`. Expected jsx identifier at examples/html5-boilerplate-icremental-dom.tsx:6:4

    <html class="no-js" lang="en-US">
     ~~~~
```

**Comment by ayame113** [comment]
The problem seems to be an unnecessary comma in the middle of the JSX. (I think the error message should be improved.)

```diff
-      <meta property="og:url", content=""/>
-      <meta property="og:image", content=""/>
+      <meta property="og:url" content=""/>
+      <meta property="og:image" content=""/>
```

**Comment by cowboyd** [comment]
Welp that was it!🤦🏻 

Thanks @ayame113! You're right, the error message could have been better, and actually when I went back, the language server did highlight the comma. I was just focused on the `<html` token
