### ISSUE TITLE
False positive unintentional comparison on array modification

### ISSUE THREAD

**Issue by jbu4github** [denoland/deno#19169]
There is an issue with deno-ts throwing an error when an array modification is made, incorrectly assuming that the length of an array has not been modified.

```
Deno.test("Test Array Length", () => {

        const array = [];
        
        assert(array.length === 0);
        
        array.push({});
        
        //Typescript Error `This comparison appears to be unintentional because the types '0' and '1' have no overlap.deno-ts(2367)`
        assert(array.length === 1);
});
```

**Comment by dsherret** [comment]
This isn't a Deno issue. It also occurs in the TypeScript playground:

https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXygGdCQYMAKEADwAcYAueNAa1RwHdUAaeAW0IDmAfkaEMMLKgEBKRkRJlC8anQDcAKHVg8YgjBhQAnvAC88ANoBdDfFt3b6+aQqwDhgHQQQUjAAtTJmYADNIajvpG7jTIhL7kAN4AvqGaTmTkrpFePv6BZgCMoUA

What you want to do in this scenario is use `assertEquals`. That will work and give a better failure message when it fails:

```
assertEquals(array.length, 1);
```
