### ISSUE TITLE
No way to read Location header of 3xx response

### ISSUE THREAD

**Issue by dancojocaru2000** [denoland/deno#19172]
When `fetch`ing something and the response is a HTTP 3xx redirect, the only options seem to be to either follow the redirect, or have an error. There seems to be no way to actually get the redirect response itself.

**Comment by crowlKats** [comment]
You can set the `redirect` option of `manual` to manually handle redirects

**Comment by dancojocaru2000** [comment]
Oh, my bad, I was used to the browser behaviour where `manual` is a misnomer and the returned response is empty, and, since I saw nothing different in the Deno params or documentation, I assumed Deno does the same.
