### ISSUE TITLE
WalkError NotFound: No such file or directory (os error 2): readdir

### ISSUE THREAD

**Issue by n8jadams** [denoland/deno#19170]
I'm writing a script that syncs some files between some volumes on my MacOs system, essentially it looks like this:

```typescript
import { walk } from "https://deno.land/std@0.187.0/fs/walk.ts";

for await (const { path } of walk("/Volumes/source-directory", {
    includeFiles: true,
    includeDirs: false,
    skip: [/((?<=\/)\.)|(^[\.])/], // dotfiles...
  })) {
  // do some stuff... throws here
}
```

It seems to break when it starts walking through a directory with russian alphabet characters. It just gives an error:

```
$ deno run -A ./src/main.ts

return new WalkError(err, root);
         ^
    at wrapErrorWithPath (https://deno.land/std@0.185.0/fs/walk.ts:48:10)
    at walk (https://deno.land/std@0.185.0/fs/walk.ts:134:11)
    at eventLoopTick (ext:core/01_core.js:181:11)
    at async walk (https://deno.land/std@0.185.0/fs/walk.ts:120:9)
    at async main (file:///Users/nadams/personal/jellyfin-to-mp3-sync-script/src/main.ts:43:26)
    at async file:///Users/nadams/personal/jellyfin-to-mp3-sync-script/src/main.ts:134:1
Caused by: NotFound: No such file or directory (os error 2): readdir '/Volumes/source-directory/Константин Никольский'
    at async Object.[Symbol.asyncIterator] (ext:deno_fs/30_fs.js:169:19)
    at async walk (https://deno.land/std@0.185.0/fs/walk.ts:104:22)
    at async walk (https://deno.land/std@0.185.0/fs/walk.ts:120:9)
    at async main (file:///Users/myscript/src/main.ts:43:26)
    at async file:///Users/nadams/myscript/src/main.ts:134:1
```

Makes me think there's some filename encoding error.

**Comment by sigmaSd** [comment]
I can't reproduce

```ts
import { walk } from "https://deno.land/std@0.187.0/fs/walk.ts";

for await (
  const { path } of walk(".", {})
) {
  console.log(path);
}
```
```
/d/d/l/t/tRZ> deno run -A a.ts
.
a.ts
Константин Никольский
denonvim.tag
```

**Comment by sigmaSd** [comment]
can you provide a minimal example

**Comment by n8jadams** [comment]
This is a bit tricky to reproduce because it involves mounting an SMB share (my unraid server) on a mac filesystem.

I suppose that's an important detail I left out.

Trying to reproduce on the local filesystem worked perfectly, as it looks like it did for you too.

I'll need to look into the walk source code and try to reproduce. Is that possible? How can I debug this?

**Comment by sigmaSd** [comment]
from the backtrace you're showing it seems that Deno.readDir its the one that failing `NotFound: No such file or directory (os error 2): readdir '/Volumes/source-directory/Константин Никольский'`

You should probably try a simple script that just runs `Deno.readDir(location_on_smb_share)`

**Comment by n8jadams** [comment]
Ah, interestingly I reproduced it in the terminal:

```
$ file /Volumes/source-directory/Константин Никольский - Мне только снится жизнь моя
/Volumes/source-directory/Константин Никольский: cannot open `/Volumes/source-directory/Константин Никольский' (No such file or directory)
```

It's an operating system level issue. Maybe I need to play with default character sets or something.
