### ISSUE TITLE
Missing type definition related to resizable ArrayBuffer.

### ISSUE THREAD

**Issue by dojyorin** [denoland/deno#19191]
The resizable ArrayBuffer seems to be re-enabled, but the type definition are missing.
Is it the effect of being temporarily disabled...?

### Environment
- Windows 10 x64
- VSCode v1.78.2
- Deno v1.33.4
- Deno VSCode Extension v3.18.0

![deno-rab-issue-1](https://github.com/denoland/deno/assets/1251857/f6921168-e7ce-4aa5-a98d-31763f8b1453)
![deno-rab-issue-2](https://github.com/denoland/deno/assets/1251857/2684f896-07b7-494b-a2a8-f28809252969)
![deno-rab-issue-3](https://github.com/denoland/deno/assets/1251857/600af2ed-617a-473d-9a6d-f340428b58ae)
![deno-rab-issue-4](https://github.com/denoland/deno/assets/1251857/9d92486d-269a-46ac-84fb-95debbd7aa59)

**Comment by indrajitbnikam** [comment]
Can I work on this issue? Also, @dsherret  Can you guide me a bit since this is my first OSS contribution?

**Comment by indrajitbnikam** [comment]
How can I generate types?

**Comment by petamoriken** [comment]
@indrajitbnikam Maybe you can try to contribute to [upstream](https://github.com/microsoft/TypeScript). There are d.ts files in `/src/lib` directory.

**Comment by dsherret** [comment]
Ah, right. I forgot this would probably be updating TypeScript.

**Comment by indrajitbnikam** [comment]
Yes, I'm working on it.

**Comment by indrajitbnikam** [comment]
I've created an Issue and have also raised the PR for the same in [upstream](https://github.com/microsoft/TypeScript). Can somebody please check and let me know what more needs to be done?

**Comment by indrajitbnikam** [comment]
Hi, Can someone tell me what I need to put here in **Configuration Check** section for [this](https://github.com/microsoft/TypeScript/issues/54636) issue? I did not change it while creating the issue.

![image](https://github.com/denoland/deno/assets/24988127/e7a8f353-ead8-44a3-baa2-78281d976962)

Sorry, This is my first contribution so a lot of things are new for me.

**Comment by petamoriken** [comment]
Upstream: https://github.com/microsoft/TypeScript/pull/58573

**Comment by petamoriken** [comment]
Tracking in #26950

**Comment by dsherret** [comment]
Yeah, let's track this in https://github.com/denoland/deno/issues/26950
