### ISSUE TITLE
FFI how to get a `char **`?

### ISSUE THREAD

**Issue by Heziode** [denoland/deno#19200]
Hi,

I am tring to use FFI in order to call this C function:

```c
#include <stdio.h>
#include <stdlib.h>

// I want to use this function, defined in another lib
int gpr2_request (int fun_id, char *request, char **answer);

// It is used like this
int main() {
    char* ptr;

    gpr2_request(1, "{ \"filename\": \"utilada_base.gpr\" }", &ptr);
    printf("Result: %s", ptr);
}
```

For deno, I do that:

```ts
const lib = Deno.dlopen(libName, {
    gpr2_request: {
      parameters: ["i32", "buffer", "buffer"],
      result: "i32",
    }
});

const gpr2RequestC = lib.symbols.gpr2_request;
const request = '{ "filename": "utilada_base.gpr" }';
  const ptr = new BigUint64Array(1);

const result = gpr2RequestC(1, 
    new TextEncoder().encode(request + "\0"), 
    ptr);

  return new Deno.UnsafePointerView(ptr[0]).getCString();
```

But I got this error:

```
error: Uncaught TypeError: Expected External at position 0
  return new Deno.UnsafePointerView(ptr[0]).getCString();
```

I don't know how to manage `char **` when used like a ref (`& char *`).

**Comment by aapoalas** [comment]
TypeScript should help you out here quite significantly: The constructor of `Deno.UnsafePointerView` takes a non-nullable pointer: https://deno.land/api@v1.33.4?unstable=&s=Deno.UnsafePointerView#ctor_0

The value you get out of `ptr[0]` is a BigInt which will indeed, so far as I can tell from a quick glance, contain the pointer value you're looking for. But, it's numeric and not a pointer yet.

You can create a pointer from a numeric value using the `Deno.UnsafePointer.create` API: https://deno.land/api@v1.33.4?unstable=&s=Deno.UnsafePointer#method_create_0

I believe that should then give you the string value you seek.

**Comment by Heziode** [comment]
Ok, its work, thank you,

Here is the solution for other people that can encounter this problem:

```ts
const lib = Deno.dlopen(libName, {
    gpr2_request: {
      parameters: ["i32", "buffer", "buffer"],
      result: "i32",
    }
});

const gpr2RequestC = lib.symbols.gpr2_request;
const request = '{ "filename": "utilada_base.gpr" }';
  const ptr = new BigUint64Array(1);

const result = gpr2RequestC(1, 
    new TextEncoder().encode(request + "\0"), 
    ptr);

  return new Deno.UnsafePointerView(Deno.UnsafePointer.create(ptr[0])).getCString();
```

---

I close the issue, but just one question about this issue:

error: Uncaught TypeError: Expected **External** at position 0.

I do not find this error message clear. What does "External" means here?

**Comment by aapoalas** [comment]
It's a V8 engine special type meant for representing external pointers in JavaScript
