### ISSUE TITLE
Implement import-maps

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#1921]
We should consider finding a way to implement [import-maps](https://github.com/WICG/import-maps).  The WICG proposal has started to be implemented.  While it is still an early stage, it would solve several problems we have had with remote modules.

It is implemented in [Chromium 74](https://www.chromestatus.com/feature/5315286962012160).

In browsers, it is a `<script type="importmap">...</script>` or `<script type="importmap" src="import-map.json"></script>`.  I would suggest for Deno, that the map is passed as a parameter.  For example:

```
$ deno --importmap import-map.json main.ts
```

**Comment by ry** [comment]
I have been waffling on this issue for a while but (after some technical debates with people) am convinced. Let's do it. The way you proposed, via command-line argument, is how I think it should work too. Unfortunately our flag parsing is quite bespoke at the moment and doesn't support argument, so before anything can be done we need to fix https://github.com/denoland/deno/issues/1987

**Comment by kitsonk** [comment]
That is needed for `tscconfig.json` too...

**Comment by bartlomieju** [comment]
FYI I'm working on this. I'll put up PR for review shortly

**Comment by bartlomieju** [comment]
Support for import maps landed in #2360 :tada:
