### ISSUE TITLE
Return opaque origin for blob: URL containing inner non-http(s): URL

### ISSUE THREAD

**Issue by annevk** [denoland/deno#19241]
See https://github.com/whatwg/url/pull/771 for the URL Standard change and https://github.com/web-platform-tests/wpt/pull/40133 for tests.

**Comment by annevk** [comment]
Note the small proposed change in https://github.com/whatwg/url/pull/780 to safelist the "file" scheme as well.

**Comment by crowlKats** [comment]
Closing as this was fixed upstream in the URL crate at some point.
