### ISSUE TITLE
Idea: add something like TS's --module and --moduleResolution for `deno run`

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/deno#19245]
This is more of a random idea than an issue.

I keep running into scenarios where a project uses a couple of hand written scripts to generate some files or other things. An example of that is the `scripts/create-plugin-list.js` file in the https://github.com/tailwindlabs/tailwindcss repository.

For simple scripts it's easy enough to convert them to ESM with `npm:` specifiers to make them work with deno. In this particular case this it would require changing nearly all the imports in the project. Luckily, it's already written in ESM syntax, but the module resolution is still node-specific with no extensions in the import specifier.

 ```js
import { corePlugins } from '../src/corePlugins' // <- missing extension (cjs style resolution)
import fs from 'fs'
import path from 'path'

// ...
```

For similar reasons TypeScript has the [`module`](https://www.typescriptlang.org/tsconfig#module) and [`moduleResolution`](https://www.typescriptlang.org/tsconfig#moduleResolution) settings respectively. I wonder if it would make sense to support something like that for the `deno run` command. We already have the `npm:` specifier and it works well for binaries, but there seems to be something missing for plain js files.

```sh
# maybe a bit too verbose, but you get the idea
deno run -A --module commonjs --module-resolution node16 my-script.js

# or maybe a shorter variant in the form of -m <module>,<resolution>
deno run -A -m cjs,node16 my-script.js
```

**Comment by bartlomieju** [comment]
This is now supported with `--unstable-sloppy-imports`.
