### ISSUE TITLE
Running compiled script fails on read-only volume

### ISSUE THREAD

**Issue by rwiskerke** [denoland/deno#19253]
On 1.32.5 (denoland/deno:centos-1.32.5) running a compiled script works fine, but using 1.33.0 (and newer) that is no longer the case and it crashed with this error:

```
error: Could not create TypeScript compiler cache location: /home/deno/.cache/deno/gen                                                                   

Check the permission of the directory.                                                                                                                  
Read-only file system (os error 30)
```

Having the ability to run a compiled script on a read-only container is very appealing (mostly for security reasons). 
The documentation is not clear on whether I can expect this to work, but it used to, but not anymore.

I see no reason for deno to try and create a compiler cache when running an already compiled script, but of course there might actually be a good reason for that. If not, then it's probably a bug?

By the way, I already looked at https://github.com/denoland/deno/issues/14440 but it doesn't really offer much information except for suggesting to use a writeable directory, which I would like to avoid.

**Comment by abustany** [comment]
exporting `HOME` seems to do the trick though

**Comment by rwiskerke** [comment]
@dsherret I didn't expect it to be solved this fast, thanks!

**Comment by rwiskerke** [comment]
I just updated to 1.34.1 and (as expected) it now works with a read-only volume. Nice!
