### ISSUE TITLE
socket.io Connection bandwidth

### ISSUE THREAD

**Issue by KULTI1995** [denoland/deno#19260]
https://github.com/socketio/socket.io-deno

Hello, I would like to ask what socket.io server placed on deno platform has the maximum throughput? Because I'm wondering if it will self-scale and be ok, or if it will work for a few users without any problem. Because it works on longpolling.

**Comment by bartlomieju** [comment]
You'll need to do some benchmarking yourself, but Deno provides very good performance: https://deno.com/blog/v2.0#deno-is-fast so I don't think you'll run into problems.
