### ISSUE TITLE
404 Requests with NPM module and Deno 1.34

### ISSUE THREAD

**Issue by pvillaverde** [denoland/deno#19274]
Hey there!

I was having the same problem while publishing twitter messages as in https://github.com/denoland/deno/issues/19209.
I've just upgraded to Deno 1.34.0 and now I have 404, while using NodeJS it sends the tweet.

Steps to reproduce 
- Have a Twitter Api credentials (yup, that might be a problem, but I think it's some problem with Deno Node, so it could be reproduced some other way...)
- Snippet is the same for NodeJS or Deno, just alternate between the 2 first lines for NodeJS and the third(import one) for Deno

```js
const Library = require('twitter-api-v2'); // Uncomment for NodeJS
const TwitterApi = Library.TwitterApi // Uncomment for NodeJS
// import { TwitterApi } from 'npm:twitter-api-v2@1.13'; // Uncomment for Deno
const messageStatus = "test";
const credentials = {/*redacted for obvious reasons*/};

const twitter = new TwitterApi(credentials);
twitter.v2.tweet(messageStatus).then(console.log).catch(console.error);
```

Output on Deno:
```
deno --version
deno 1.34.0 (release, x86_64-unknown-linux-gnu)
v8 11.5.150.1
typescript 5.0.4

deno run --allow-net --allow-env src/test.ts 

Error: Request failed with code 404
    at RequestHandlerHelper.createResponseError (file:///home/user/.cache/deno/npm/registry.npmjs.org/twitter-api-v2/1.13.0/dist/cjs/client-mixins/request-handler.helper.js:103:16)
    at RequestHandlerHelper.onResponseEndHandler (file:///home/user/.cache/deno/npm/registry.npmjs.org/twitter-api-v2/1.13.0/dist/cjs/client-mixins/request-handler.helper.js:252:25)
    at IncomingMessageForClient.emit (ext:deno_node/_stream.mjs:1852:9)
    at endReadableNT (ext:deno_node/_stream.mjs:3646:16)
    at processTicksAndRejections (ext:deno_node/_next_tick.ts:31:29)
    at runNextTicks (ext:deno_node/_next_tick.ts:69:5)
    at eventLoopTick (ext:core/01_core.js:188:21) {
  error: true,
  type: "response",
  code: 404,
  headers: {
    perf: "7626143928",
    "cache-control": "no-cache, no-store, max-age=0",
    "content-length": "0",
    "x-transaction-id": "7c56a5e422beb03a",
    "x-response-time": "103",
    "x-connection-hash": "bb088e1f7d91a299500a2ed8e879afe9d0696645d18f8311e1db6483a58540de",
    date: "Fri, 26 May 2023 09:17:01 GMT",
    server: "tsa_f"
  },
  rateLimit: undefined,
  data: ""
}
```

Output on NodeJS:

```
node --version
v19.9.0
npm --version
9.6.7
node src/test.ts 

{
  data: {
    edit_history_tweet_ids: [ '1662025593322459137' ],
    id: '1662025593322459137',
    text: 'test'
  }
}
```

Let me know if you need any more information!

**Comment by bartlomieju** [comment]
@pvillaverde I assume you hadn't found any simpler way to reproduce it without using Twitter API?

**Comment by pvillaverde** [comment]
Hey @bartlomieju, nope. I've tried running other queries, even with axios, but had no problem at all. I've been trying to debug the query but host and path seem to be ok..

This is requestData on file:///~/.cache/deno/npm/registry.npmjs.org/twitter-api-v2/1.13.0/dist/cjs/client-mixins/request-handler.helper.js:355:16
```

{
  url: URL {
    href: "https://api.twitter.com/2/tweets",
    origin: "https://api.twitter.com",
    protocol: "https:",
    username: "",
    password: "",
    host: "api.twitter.com",
    hostname: "api.twitter.com",
    port: "",
    pathname: "/2/tweets",
    hash: "",
    search: ""
  },
  options: {
    method: "POST",
    headers: {
      "x-user-agent": "Node.twitter-api-v2",
      Authorization: '--------------------',
      "content-type": "application/json;charset=UTF-8",
      "content-length": 15,
      "accept-encoding": "br;q=1.0, gzip;q=0.8, deflate;q=0.5, *;q=0.1"
    },
    timeout: undefined,
    agent: undefined
  },
  body: '{"text":"test"}',
  rateLimitSaver: [Function: bound saveRateLimit],
  requestEventDebugHandler: undefined,
  compression: true,
  forceParseMode: undefined
}
```

I've tracked it down in the twitter-api code to the use of the "node:https" module... I've tried running a few queries directly like this beyond, but it returns 200. So there seems to be something it does on twitter library itself that got broken with one of the latest deno updates.
```

import * as https from 'node:https';
const options = {
   hostname: 'httpbin.org',
   port: 443,
   path: '/anything',
   method: 'POST',
   body: '{"text":"test"}',
 };

 const req = https.request(options, (res) => {
   console.log('statusCode:', res.statusCode);
   console.log('headers:', res.headers);

   res.on('data', (d) => {
     console.log(d);
   });
 });

 req.on('error', (e) => {
   console.error(e);
 });
 req.end();
```

For now I'm staying at 1.32.5 and it seems to work fine... I have no clue where to look right now, but if I can help somehow let me know!

**Comment by bartlomieju** [comment]
@pvillaverde do you still experience this problem with Deno v1.35.2?

**Comment by pvillaverde** [comment]
Hey there @bartlomieju ! I forgot to post it here, but the last I built was with 1.34.1 and it was already fixed. I do not remember the details now but I think it was something related  with this other issue solution https://github.com/denoland/deno/issues/16923

**Comment by bartlomieju** [comment]
Got it, thanks for checking in. I'm gonna close the issue for know - feel free to open a new one if you hit another problem.
