### ISSUE TITLE
Uploding files through deno streams causing content length error

### ISSUE THREAD

**Issue by divyam234** [denoland/deno#19276]
```js
  const name=''
  const filePath=''
  const file = await Deno.stat(filePath);
  const body = (await Deno.open(filePath, { read: true })).readable;
  
  const res = await fetch ("https://uploads.github.com/*", {
   method: 'POST',
    headers: {
      'content-type': 'application/octet-stream',
      'content-length': file.size
    },
    body
  })
```
This piece of code is throwing bad content length error. Although this is working in nodejs with remix fetch and node fetch implementations ,it only happens when I am passing body as readable stream in deno. I recon it has something to do with fetch client of deno

**Comment by bartlomieju** [comment]
Can you provide the exact output when running the program?

**Comment by ecochard** [comment]
I get the same problem, here is the result:

Github API Error myfilename.ext: {"message":"Bad Content-Length","request_id":"xxxx:xxxxx:xxxx:xxxxxx:xxxx"}
