### ISSUE TITLE
FR: Syntax highlighting in REPL

### ISSUE THREAD

**Issue by andykais** [denoland/deno#1928]
It would be awesome if the deno repl could include syntax highlighting of expressions _as you type_.
This is not something we have in either the node repl or ts-node repl, but nonetheless would make for a much more enjoyable repl experience. 

Coming from scala-land, [dotty](https://dotty.epfl.ch/) (the next gen compiler for scala) for example, includes a colored repl by default
<img width="295" alt="Screen Shot 2019-03-13 at 4 55 43 PM" src="https://user-images.githubusercontent.com/6627147/54314011-e7fa1e00-45b0-11e9-8263-9e0806a7a24b.png">

some other examples include:
- [ammonite](http://ammonite.io/#Ammonite-REPL) (improved scala repl)
- [zdharma/fast-syntax-highlighting](https://github.com/zdharma/fast-syntax-highlighting) zsh plugin that highlights valid commands
- [bpython](https://bpython-interpreter.org) (fancy python shell)

**Comment by pedropaulosuzuki** [comment]
That would be nice indeed!

**Comment by andykais** [comment]
I just upgraded to 1.5.0 and I see this syntax highlighting on the repl! Awesome work guys
