### ISSUE TITLE
npm: imports not needing allow-net to make request

### ISSUE THREAD

**Issue by sylc** [denoland/deno#19301]
Hi, 

Running the below does not ask me for an `allow-net` permission to access github.com.
```
#!/usr/bin/env -S deno run --allow-read --allow-env
import axios from "npm:axios"

await axios.get('https://github.com')
  .then(function (response) {
    // handle success
    console.log(response);
  }).catch(err => {
    console.log('error', err.cause)
  })

```

The same occur if I use for example `npm:@aws-sdk/client-s3` and try to access a bucket or using `npm:node-fetch`. 
No net access is requested.

I'm not sure if this is intended or not, but I was expecting to be asked for `--allow-net`. 
If intended, maybe this should be mentioned in `npm:` specifier section manual.

thanks

also mentioned at https://discord.com/channels/684898665143206084/1112316817671716954/1112316817671716954

deno 1.34.0

**Comment by bartlomieju** [comment]
Fixed by https://github.com/denoland/deno/pull/19282
