### ISSUE TITLE
Error when using jsxImportSource and JSX transform falls back to createElement

### ISSUE THREAD

**Issue by swandir** [denoland/deno#19300]
This code

```tsx
/* @jsxImportSource https://esm.sh/react@18.2.0 */

<div {...{}} key={1} />
```

produces an error:

```shell
$ deno run main.tsx
error: Loading unprepared module: https://esm.sh/react@18.2.0, imported from: file:///main.tsx
```

Adding an explicit import like this fixes the error:

```ts
/* @jsxImportSource https://esm.sh/react@18.2.0 */

import "https://esm.sh/react@18.2.0";

<div {...{}} key={1} />
```

**Comment by vedant-pandey** [comment]
@swandir it looks like you're using incorrect syntax as per [typescript's doc](https://www.typescriptlang.org/tsconfig#jsxImportSource) this should be something like this

```typescript
/** @jsxImportSource https://esm.sh/react@18.2.0 */

<div {...{}} key={1} />
```
Notice 2 `*` implying js-doc comments.

Can you make this change and confirm if this issue persists?

**Comment by swandir** [comment]
@vedant-pandey yeah, I tried, no difference.

**Comment by vedant-pandey** [comment]
Would you mind sharing a code repo for me to test and try this?

**Comment by swandir** [comment]
The code in issue description is a whole repro. Just put it in a file and run it.

```shell
cat <<EOT > main.tsx
/* @jsxImportSource https://esm.sh/react@18.2.0 */

<div {...{}} key={1} />
EOT

deno run main.tsx
```

**Comment by lucacasonato** [comment]
Closing as dupe of #21068
