### ISSUE TITLE
Feature Request: Define a protocol for `--watch`ing files served remotely

### ISSUE THREAD

**Issue by mimbrown** [denoland/deno#19314]
# Feature Request
Deno has first class support for `--watch`ing changes to local files, but there's no option to watch remote files. This is a request to define a protocol (probably web socket based?) that servers could implement to support watching for changes to remote files.

# Use Cases
The immediate use case in my mind is local development: by running a local server and mapping a local folder to that local server in an import map, developers can write whatever custom loaders/transformers they want to support infinite use cases. The best part is that things like typings/intellisense work automatically, because Deno has first class support for "remote" files. By supporting watching these files, this could become a truly viable path for great DX and rapid prototyping, which is one of Deno's original goals.

This is not the only possibility, however. This could potentially enable new kinds of shared development, where multiple devs are working off of files on the same server simultaneously and seeing each other's changes in real time. I don't really know where that could go, but the possibilities are pretty interesting to think about.

# Considerations
There would need to be support for specifying which remotes should be watched and which shouldn't. I'm assuming that any remotes that are specified as watched would bypass the cache entirely and always go to the server.

# Possible Example
Multiple `--watch` flags could be supported, and each could have an optional argument. The argument would be the remote location/local directory whose files should be watched for changes. Leaving off the argument would default to the entire local filesystem, so this would be backwards compatible. So for example, running the following:
```
deno run --watch --watch=http://localhost:8080 my-file.ts
```
would "watch" both all local files *and* remote files served from `http://localhost:8080`. By passing (via header?) a token that uniquely specifies each "run", the server can handle the logic of watching for changes to any files it controls, then notify any processes that imported the changed file that they need to reload.

**Comment by bartlomieju** [comment]
Thanks for the suggestion, but I think this is out of scope for Deno. Providing a protocol for such a niche use case is gonna be a big undertaking that we sadly don't have bandwidth to do.
