### ISSUE TITLE
`e.preventDefault()` on unhandledrejection/error events doesn't work

### ISSUE THREAD

**Issue by jespertheend** [denoland/deno#19334]
When I saw that #16928 was fixed I wanted to try it out for my use case, but it seems like I can still reproduce it under certain conditions. Specifically when importing `std/node/process.ts`.

```js
import "https://deno.land/std@0.177.0/node/process.ts";
import {delay} from "std/async/delay.ts";

/**
 * @typedef FailedTestsData
 * @property {string} path
 * @property {string[]} failedTestNames
 */

globalThis.addEventListener("unhandledrejection", e => {
	console.log("unhandled!");
	e.preventDefault();
});
globalThis.addEventListener("error", e => {
	console.log("caught!");
	e.preventDefault();
});

(async () => {
    throw 'failed';
})();

await delay(5_000);

console.log("done");
```

**Comment by jespertheend** [comment]
Ah hmm, seems like this issue is exactly what was fixed in #19235, I'm simply importing an old std version which still has this issue.
Unfortunately a third party is importing this version :/

**Comment by bartlomieju** [comment]
@jespertheend yeah, there's not much we can do with old version of `deno_std`. The issue at hand is fixed when using `node:process` import, but I won't be able to fix it for old code.

**Comment by jespertheend** [comment]
Yeah makes sense, sorry I thought I closed this.
I have forked `deno-puppeteer` and manually replaced `https://esm.sh/jszip@3.5.0` with `npm:jszip@3.5.0`.
Seems to work so far.
