### ISSUE TITLE
Improve directory import error

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#19366]
We currently give a confusing error message:

```
error: Unable to load C:\Users\Alexander\AppData\Local\deno\npm\registry.npmjs.org\lostjs\1.1.14\common imported from file:///D:/Alexander/Documents/vsc-workspace/LostJS.page/test.ts

Caused by:
    Access is denied. (os error 5)
```

We should do something like what node does:

```
Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import 'C:\Users\WDAGUtilityAccount\test\node_modules\lostjs\common' is not supported resolving ES modules imported from C:\Users\WDAGUtilityAccount\test\index.mjs
Did you mean to import lostjs/common/index.js?
```

Ref #19365 and some other issues.

**Comment by ElianCordoba** [comment]
HI @dsherret, I'm working on this, I got part of the error message done but I don't know where to get the npm package name so I can compose this part of the error message:

```
Did you mean to import lostjs/common/index.js?
```

[This](https://github.com/denoland/deno/blob/0733943fe7de30fa54d6cd8ee34f7393e8bb7482/cli/module_loader.rs#L739) is the function I'm updating

I could extract it from the `specifier` but I was wondering if there is a cleaner way to do it

**Comment by dsherret** [comment]
@ElianCordoba I just looked into it and it seems there's no easy way at the moment. Probably a new method would need to be added to the `NpmPackageFsResolver` like `resolve_package_nv_from_specifier(&self, specifier: &ModuleSpecifier) -> Result<NpmPackageNv, AnyError>` (or something like that). For the `GlobalNpmPackageResolver` it's easy to get by doing `self.cache.resolve_package_folder_id_from_specifier(specifier, &self.registry_url)`. For `LocalNpmPackageResolver`, it would be a bit more complicated because I believe something would need to be written to do this. For example, there would need to be an inverse of `get_package_folder_id_folder_name` in `npm/resolvers/local.rs`.

In case it's too complex, as a first pass implementing this without the `Did you mean to import lostjs/common/index.js?` suggestion would be good enough and then we can circle back to add the suggestion later.
