### ISSUE TITLE
re-enable arm64 test 

### ISSUE THREAD

**Issue by ry** [denoland/deno#1937]
disabled here 1e3509df42e996ea092ae7e8b5a61aef51c92c2b due to this failure in CI:
```
$CARGO_TARGET_DIR/aarch64-unknown-linux-gnu/release/deno tests/002_hello.ts
qemu: Unsupported syscall: 278
qemu: Unsupported syscall: 278
```

cc @afinch7

**Comment by afinch7** [comment]
Looking at the core integration it looks like you dropped script init. The important information about this error is below:
```
<anonymous>:1:0
denoMain()
^
Uncaught ReferenceError: denoMain is not defined
    at <anonymous>:1:1
```
I can start working on a patch for #1938 to refactor init data to better fit with core.

**Comment by ry** [comment]
@afinch7 I expect #1938 to land today. Not sure where the init script could have been dropped? But in any case, yes patch on top of that branch are welcome.

**Comment by afinch7** [comment]
I have a working fix. It's dependent on #1938. I will create a PR as soon as you land it.
