### ISSUE TITLE
Lazy load ext/node source code on first use

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#19398]
Current we are snapshotting all internal code. One idea to improve the startup
time is to exclude "ext/node" code from the snapshot and instead load it on first
use. 

The theory is that it would help us save about half of the size of the startup snapshot
and about half of the startup time.

This might require more involved changes in "core/extensions.rs" and the build
scripts.

**Comment by bartlomieju** [comment]
I'm gonna close this one for now. The trade-off between complexity and potential gains is currently not worth it to spend time on it.

**Comment by petamoriken** [comment]
In my understanding, WebGPU is temporarily disabled due to the lack of lazy load, are there any plans to bring it back?
https://github.com/denoland/deno/pull/18094#pullrequestreview-1344898730

**Comment by bartlomieju** [comment]
> In my understanding, WebGPU is temporarily disabled due to the lack of lazy load, are there any plans to bring it back? [#18094 (review)](https://github.com/denoland/deno/pull/18094#pullrequestreview-1344898730)

These are not the same problem - for WebGPU it's about lazy loading the Rust code (there's a startup cost related to linking system libraries on startup), while this issue was about lazy loading JavaScript code for ext/node.
