### ISSUE TITLE
Show tokio-minihttp in the req/sec benchmark

### ISSUE THREAD

**Issue by ry** [denoland/deno#1939]
Something like this https://github.com/tokio-rs/tokio-minihttp/blob/master/examples/hello-world.rs

It should be faster than https://github.com/denoland/deno/blob/master/tools/hyper_hello.rs and it's a fairer comparison. If it's faster, I think it would make sense to eventually remove the hyper_hello bench.

(suggestion from @SergioBenitez)

**Comment by kevinkassimo** [comment]
tokio-minihttp is [not published on crates.io](https://github.com/tokio-rs/tokio-minihttp/issues/35) and claimed to be just a demo project. If we really want to add this benchmark we need to copy all the source code from there (not a lot though).

(Sidenote: I'm not so sure if we should leave http still implemented on the TS side in the future, especially considering HTTP/2. Hyper seems to already support HTTP/2 through h2 crate created by the maintainers of Tokio)

**Comment by ry** [comment]
You can just link to it [here](https://github.com/denoland/deno_third_party/blob/master/rust_crates/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.15/examples/tinyhttp.rs) with a bit of GN:

```
rust_executable("tinyhttp") {
  source_root = "//third_party/blob/master/rust_crates/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.15/examples/tinyhttp.rs"
  deps = deno_core_deps
  extern = [ "$rust_build:tokio" ]
}
```
