### ISSUE TITLE
Ability to create and load a snapshot without rebuilding the whole binary

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#19399]
In an effort to improve iteration time when working **only** on JavaScript code,
we should consider having a way to rebuild and load the startup snapshot without
having to rebuild the whole binary.

This would be done by a combination of a Cargo feature flag (or env variable) to
instruct the `cargo build` process to not include the snapshot in the binary, and
a separate script that would be able to build the snapshot on demand.

This might require building a separate binary that would have a sole purpose of
building the snapshot (akin to V8's `mksnapshot` binary used to produce initial
snapshot with JS built-ins).

There is a challenge related to the fact that we currently snapshot "ops" that are
included in the binary, but it doesn't seem insurmountable.

**Comment by k-nasa** [comment]
Last week, I faced this issue while working on the code for ext/node/polyfills. Each change required a lengthy build time. It would be tremendously helpful and significantly increase our development efficiency if we could reduce this time to just a few seconds. I fully support this proposal 😄
