### ISSUE TITLE
Support Docusaurus

### ISSUE THREAD

**Issue by hashrock** [denoland/deno#19395]
Tracking issue for supporting [Docusaurus](https://docusaurus.io/)

with `docusaurus build` :

- `error: Uncaught Error: Not implemented: Script.prototype.runInNewContext`

**Comment by valpackett** [comment]
TiddlyWiki also uses `runInNewContext`…

**Comment by bartlomieju** [comment]
Sorry for a late reply. Getting `Script.runInNewContext` requires lots of work that entails porting https://github.com/nodejs/node/blob/main/src/node_contextify.cc using Rust APIs. This is a very non-trivial undertaking and the Deno team is planning to address this in Q4 2023.

**Comment by bartlomieju** [comment]
https://github.com/denoland/deno/pull/21527 will be a step towards supporting this, but most likely not enough (as the PR doesn't support any options).

**Comment by littledivy** [comment]
`runInNewContext` is not an error anymore. These are the next blockers:
- https://github.com/denoland/deno/issues/22731
- https://github.com/denoland/deno/issues/22732

**Comment by littledivy** [comment]
`docusaurus serve` works now. Let's track the remaining CLI and `docusaurus build` issues seperately.

https://github.com/denoland/deno/issues/22732
https://github.com/denoland/deno/issues/23297
