### ISSUE TITLE
[UX]: Spawn error on invalid command doesn't show the command

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/deno#19400]
When you try to spawn a non-existing command the error message is a bit bare bones. It doesn't show you which command you tried to run and only gives you the following error:

```sh
Uncaught NotFound: No such file or directory (os error 2)
```

The trace itself attempts to show the spawn location via a one-liner code frame which shows the command that was used:

<img width="481" alt="Screenshot 2023-06-07 at 12 58 28" src="https://github.com/denoland/deno/assets/1062408/63e6c039-1bf1-4f78-a015-d31c8a84a5a2">

But if you're passing options to `Deno.Command()` then that code frame isn't useful to deduce the command anymore:

<img width="462" alt="Screenshot 2023-06-07 at 12 59 11" src="https://github.com/denoland/deno/assets/1062408/1a1507ee-cf50-4b84-9e33-761b490ddcf6">

## Steps to reproduce

1. Create a file `foo.js` with the content:
  ```js
  const child = new Deno.Command("does-not-exist", {
    asd1: 1,
    asd2: 1,
    asd3: 1,
    asd4: 1,
    asd5: 1,
  }).spawn();
  ```
2. Run `deno run -A foo.js`

## Expected result

A better error message that prints the command.

**Comment by sigmaSd** [comment]
Its possible to add anyhow context here https://github.com/denoland/deno/blob/da9db887e34f0075e1433ee93854267aec0ef468/runtime/ops/process.rs#L288

but maybe its left out on purpose for performance?

**Comment by bartlomieju** [comment]
> Its possible to add anyhow context here
> 
> https://github.com/denoland/deno/blob/da9db887e34f0075e1433ee93854267aec0ef468/runtime/ops/process.rs#L288
> 
> but maybe its left out on purpose for performance?

It's an omission. Context can be created lazily, when needed using `.with_context(|| ...)`: 
```
let mut child = command.spawn().with_context(|| {
  format!("Failed to spawn: {}", <program_name>);  
})?; 
```
