### ISSUE TITLE
Add error classes for common errors

### ISSUE THREAD

**Issue by piscisaureus** [denoland/deno#19408]
These [unmapped errors](https://github.com/denoland/deno/blob/da9db887e34f0075e1433ee93854267aec0ef468/runtime/errors.rs#L44-L64) errors are commonly seen in Deploy. I think it'd be valuable to add error classes for them:

* `FilesystemLoop`
* `IsADirectory`
* `NetworkUnreachable`
* `NotADirectory`

**Comment by piscisaureus** [comment]
@bartlomieju bump, would you be able to assign someone to this?

**Comment by bartlomieju** [comment]
@piscisaureus do you just want them available on the `Deno.errors` namespace? Or should they also be used for various existing `Deno` namespace APIs?
