### ISSUE TITLE
node:worker_threads: Worker constructor doesn't check `type: module` of `package.json`

### ISSUE THREAD

**Issue by kt3k** [denoland/deno#19440]
Currently we only checks the file extension for detecting esm/cjs in `node:worker_threads`'s `Worker` constructor. ref. https://github.com/denoland/deno/blob/1b26f3c726d4835a403765f42a4f760b29b9f57d/ext/node/polyfills/worker_threads.ts#L56

But it also needs to check `type` property of `package.json` which the worker script belongs to.

This affects `build` task of svelte kit project. Svelte kit creates worker for [`analyze.js`](https://github.com/sveltejs/kit/blob/5ff4f919331b10ca82fcf692ea29ca2af4c7cd69/packages/kit/src/core/postbuild/analyse.js#L17), [`prerender.js`](https://github.com/sveltejs/kit/blob/5ff4f919331b10ca82fcf692ea29ca2af4c7cd69/packages/kit/src/core/postbuild/prerender.js#L17), etc and also it sets `type: module` in [`package.json`](https://github.com/sveltejs/kit/blob/5ff4f919331b10ca82fcf692ea29ca2af4c7cd69/packages/kit/package.json#L12). So these scripts need to be handled as ESM worker scripts, but currently handled as CJS.

Steps to reproduce:

```shellsession
$ npx create-svelte@latest svelte-example
$ cd svelte-example
$ deno task build
```

The last `deno task build` fails with the error `error: Uncaught (in worker "$DENO_STD_NODE_WORKER_THREAD") SyntaxError: Cannot use import statement outside a module`.

`deno run -A -Ldebug npm:vite build` gives more info about the above error and you can see the below script is generated and dynamically imporeted:

```
data:text/javascript,(async function() {const { createRequire } = await import("node:module");const require = createRequire("file:///Users/kt3k/tmp/svelte-example");require("/Users/kt3k/tmp/svelte-example/node_modules/.deno/@sveltejs+kit@1.20.2/node_modules/@sveltejs/kit/src/core/postbuild/analyse.js");})();
```

**Comment by vedant-pandey** [comment]
@bartlomieju can i work on this?

**Comment by bartlomieju** [comment]
@vedant-pandey sure, feel free to ping me if you need pointers.

**Comment by vedant-pandey** [comment]
Thanks to @bartlomieju's help I was able to get the `package.json` data to the worker thread, and added verification if the file should be treated as `esm` or `cjs` based on the extension as well as the `type` value in `package.json` . Now the error is gone but the build process gets stuck. Upon closer inspection after stopping the build, the build generated by npm vs deno has a main difference in the `.svelte-kit/output/server/manifest-full.js` file, where the `client` key is set to `null` in deno's version. As per sveltekit's code [mentioned here](https://github.com/sveltejs/kit/blob/d2f7bc8355fbe5ff960b4d8f2767faf10f5c7bd1/packages/kit/src/exports/vite/index.js#L657-L675) this `manifest-full.js` is used to generate more assets, which is where it appears to be getting stuck. 

_Vite builds a single bundle. We need three bundles: client, server, and service worker. The user's package.json scripts will invoke the Vite CLI to execute the server build. We then use this hook to kick off builds for the client and service worker._

Will continue looking into this, but putting this comment in case someone else might have a clue as per why this might be happening

**Comment by bartlomieju** [comment]
@vedant-pandey have you had time to check progress on this one?

**Comment by vedant-pandey** [comment]
Not yet @bartlomieju, will look into this by end of this week.

**Comment by satyarohith** [comment]
This is fixed in https://github.com/denoland/deno/pull/19480
