### ISSUE TITLE
HTTP server optimizations low-hanging fruit

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#19451]
@marvinhagemeister  and I did an investigation based on latest benchy results, are here are some thoughts:

Preact SRR benchmark low hanging fruit:
- [x] mapToCallback performs callback.length > 0 checks on every call, this can
be hoisted out of the returned function, and returned function can be optimized
depending on arity of callback. (https://github.com/denoland/deno/pull/19449)
- [x] `converters.ByteString` is spending most of the time in the IS_BYTE_STRING regex (https://github.com/denoland/deno/pull/19452)
- [ ] `appendHeader` spends a lot of time in regex checks
- [x] `serve is assigning `const rid = context.serverRid` on each iteration - can be hoisted out (https://github.com/denoland/deno/pull/19452)
- [ ] `Response` constructor is spending a lot of time in:
- [ ] webidl.converters.BodyInit_DOMString? (at least hoist the converter lookup)
- [ ] webidl.converters.ResponseInit_fastDictionary
- [ ] headersFromHeaderList
- [ ] initializeAResponse

Express benchmark revealed low hanging fruit in `ext/node/polyfills/http.ts`:
- [ ] `this.url = req.url.slice(req.url.indexOf("/", 8));` - takes 24ms
- [ ] `this.listenerCount("upgrade") > 0` - takes 10ms
- [ ] `class ServerResponse` assigning values to fields takes a very long time,
try to move these fields initializers to the constructor and verify that it helps in any way

All benchmarks suggest that we need to:
- [ ] optimize calling `op_run_microtasks()`- don’t call it, if macrotask callback did no work, Bartek had a WIP PR for this. (https://github.com/denoland/deno/pull/19492)

**Comment by Gustrb** [comment]
May I look into the optimizations in ext/node/polyfills/http.ts ?

**Comment by bartlomieju** [comment]
@Gustrb, sure, feel free to pick it up!

**Comment by bartlomieju** [comment]
@Gustrb FYI I believe that from the `ext/node/` parts the only actionable item is actually

>  `this.url = req.url.slice(req.url.indexOf("/", 8));` - takes 24ms

**Comment by bartlomieju** [comment]
There's a lot of work going on in https://github.com/denoland/deno_core these days which should yield improvements across the board. I will close this issue for now and we'll revisit and collect new profiles after that work is done.
