### ISSUE TITLE
fmt is not compatible with some front matters in markdown files

### ISSUE THREAD

**Issue by oscarotero** [denoland/deno#19458]
The [front matter std](https://deno.land/std@0.190.0/front_matter/mod.ts) library supports different formats of frontmatters, but these formats are not recognized by fmt. For example, let's say I have the following markdown file with a TOML front matter:

```md
+++
title = 'First page'
+++

Hello world
```

After running `deno fmt`, the file is changed to:

```md
+++ title = 'First page' +++

Hello world
```

Now the front matter is no longer detected by the std library.

**Comment by vedant-pandey** [comment]
Can I take this issue?

**Comment by vedant-pandey** [comment]
Fmt relies on the package [dprint-plugin-markdown](https://github.com/dprint/dprint-plugin-markdown) which in turn uses [pulldown-cmark](https://github.com/raphlinus/pulldown-cmark). Right now metadata tags are not yet supported, but the required changes are already created, [source here](https://github.com/raphlinus/pulldown-cmark/pull/641). As per the project specs it would get supported in `pulldown-cmark` in version [0.10](https://github.com/users/raphlinus/projects/1) while the latest release is `0.9.3` which is the one supported in `dprint-plugin-markdown`.

**Comment by evanleck** [comment]
Just ran into this problem while building out a site using Lume and it looks like `pulldown-cmark` has released 0.10+ now https://github.com/pulldown-cmark/pulldown-cmark/releases

**Comment by evanleck** [comment]
Until this resolved, I'm using Prettier via `deno eval`, in case anyone wants a stop gap:

```
deno eval 'import "npm:prettier@3/bin/prettier.cjs";' -- --parser markdown
```

**Comment by KorigamiK** [comment]
Also related to formatting markdown files. Deno fmt cannot format file that have pandoc syntax also. 
For example, formatting fails to happen in such cases which work fine with pandoc.
`![Sandbox](./images/image.png){ width=80% }`

**Comment by dsherret** [comment]
This works now in 1.46 https://dprint.dev/playground/#code/NQiwCgBcEtIGwKYAIC8SDkAxaAnAzpEgA4CGA5guhCMBBABIJxwD2SA7iznACZA/plugin/markdown
