### ISSUE TITLE
Deno.remove() can not remove symlink file

### ISSUE THREAD

**Issue by axetroy** [denoland/deno#1947]
I found `Deno.remove()` cannot remove symlink file

This should be abnormal

Or we should need a `Deno.unlink()`?

**Comment by zekth** [comment]
Is there any error? i've experienced it with another program while running with non administrator permissions.

**Comment by kevinkassimo** [comment]
Hmm I cannot reproduce this issue on my machine... is it on windows?

**Comment by axetroy** [comment]
reproduce step.

```bash
echo "hello world" >> test.md
ln -s test.md test-link.md
echo 'Deno.remove("./test-link.md");' >> test.ts
deno test.ts --allow-all
```

I test again. it works in ``Deno@0.3.6``
