### ISSUE TITLE
Feature Request: Deno.utimes() api

### ISSUE THREAD

**Issue by axetroy** [denoland/deno#1948]
`Deno.utimes()` change the file system timestamps of the object referenced by path.

**Comment by ATheCoder** [comment]
Rust standard library does not implement utimes, However there is a crate that does: https://docs.rs/utime/0.2.2/utime/
Go does implement it: https://golang.org/pkg/os/ (search for `func Chtimes`)
Ruby does: https://ruby-doc.org/core-2.2.0/File.html#method-c-utime
Python has it on it's `os` module: https://docs.python.org/2/library/os.html (search for `utime`)

**Comment by ry** [comment]
Cool, so it looks like we had done the reasonable thing in Node back then. I'd say the interface should be:
```
namespace Deno {
  function utime(filename: string, atime: number, mtime: number): Promise<void>;
  function utimeSync(filename: string, atime: number, mtime: number): void;
}
```
Any objections?

**Comment by kevinkassimo** [comment]
Probably also allow changing just one of the 2 timestamps? (similar to what [utimensat](http://man7.org/linux/man-pages/man2/utimensat.2.html) does)
