### ISSUE TITLE
Lock files do not track enough for reproducibility

### ISSUE THREAD

**Issue by emilazy** [denoland/deno#19512]
I ran into this issue while trying to integrate a Deno build with Nix (a reproducible, hash-addressed build system that forbids unrestricted network access).

Firstly, the `deno.lock` file is missing URLs for dependencies that are HTTP redirects. For instance, if you import `https://esm.sh/cowsay2@^2.0`, only `https://esm.sh/cowsay2@2.0.4` is present in the lock file. This means that the lock file does not fully track all URLs relevant to reproducibility; if the redirect changes then the program's behaviour will change but you can't tell that from the lock file. It also means that you cannot compute all the required `$DENO_DIR/deps` cache entries from the lock file alone; if the cache is missing an entry for `https://esm.sh/cowsay2@^2.0` then `deno run --cached-only` will fail, even if it is pre-filled with all the URLs from the lock file. Apart from the general reproducibility issues, this makes it impossible to recreate dependency environments from the lock file alone, which is a shame as it limits the ability to integrate Deno with other reproducibility-focused tooling.

Secondly, and relatedly, the integrity hash that deno uses for the `remote` dependencies is computed solely over the HTTP response body without including any headers. I understand the reasons for this – you don't want dependencies getting invalidated constantly because of `Date` headers – but it leads to another reproducibility issue: deno treats URLs differently depending on some headers. I don't know the complete list, but at least `Content-Type` is relevant; `import test from "https://..."` fails with `Uncaught TypeError: Expected a "JavaScriptOrWasm" module but loaded a "JSON" module.` if that URL has `Content-Type: application/json`. This means that dependencies can change in a backwards-incompatible way without the integrity hash changing: there are multiple dependency sets with different behaviour but the same integrity hashes. (Interestingly, if there is no recorded `Content-Type` then it works fine; I guess this means Deno is doing sniffing of some kind? `X-Content-Type-Options: nosniff` doesn't stop it either. Seems potentially dangerous.)

To solve the first problem, all that is required is that the lock file mention *all* URLs that were requested during dependency resolution, rather than only the final URL. I think this would be a good change and make integrating Deno builds into other systems much easier, as well as fixing reproducibility bugs. However, this runs straight into the second problem: since hashes are over response bodies and don't include any headers, the integrity hashes of redirects wouldn't change with the `Location` header. Therefore, both must be addressed in tandem.

For the second problem, my first idea to solve this was to have files in the `deps` tree contain not just the body but the entire HTTP response. Unfortunately this wouldn't work well for the `Date` reason I mentioned; we only want the integrity hash to change with headers that are actually important. My best current idea is for Deno to enumerate the list of relevant headers (e.g. HTTP status, `Location`, `Content-Type`, `Content-Length`, `Vary`, `Cache-Control`, ...) and include those in the cache file that the hash is calculated over; the `headers` field could presumably then be removed from the cache metadata files.

Whatever solution is chosen, it would be helpful if attention is paid to making it easy to reproduce hashes without invoking Deno directly; for instance, a fix along the lines of "include only the relevant headers and the hash of the body in the metadata files, take the integrity hash over that JSON" is appealing on the face of it, but it runs into the issues of defining a canonical JSON serialization that have plagued many signing schemes. Something like "cache files match the output of `curl -i`, with the header filtered to contain only those that Deno cares about in ASCII order (or the original response order), and the hash is taken over the entire file" would be comparatively simple to integrate into other tools.

I would be happy to try and implement a fix along these lines if it would be acceptable. I can also show code to reproduce these issues if that would help.

**Comment by emilazy** [comment]
Looks like `X-TypeScript-Types` is another relevant header. I am probably not qualified to track them all down myself :)

(Another option to only including specific headers would be to exclude particularly volatile and irrelevant ones, but that's more fragile in terms of both caching and flagging up when a header is relevant to Deno.)

**Comment by hsjobeki** [comment]
+1 On this issue. I just ran into the same issue:

`deno.jsonc`
```
{
  "tasks": {
    "run": "deno run main.ts",
  },
  "imports": {
    "chroma-js": "https://esm.run/chroma-js@2.4.2"
  }
}
```

`deno.lock`
```json
{
  "version": "2",
  "remote": {
    "https://cdn.jsdelivr.net/npm/chroma-js@2.4.2/+esm": "f4c50a3ee656c302187f2dd0237d50cedceaa306637e538fea772cb35a98e368"
  }
}
```

There is no way to reproduce the cache structure when locking at the provided lockfile:
(emilazy already explains in depth why so i skip that)

```
.deno/
├── deps
│   └── https
│       ├── cdn.jsdelivr.net
│       │   ├── 884ea30f739c805f55262ce99f1db26138025f6797831bc0f37aaddde72b5f3c
│       │   └── 884ea30f739c805f55262ce99f1db26138025f6797831bc0f37aaddde72b5f3c.metadata.json
│       └── esm.run
│           ├── c932f29874c1e569dd9c9f55f34b6847112e844cd51a61cdd7337fd17c17e8f6 
│           └── c932f29874c1e569dd9c9f55f34b6847112e844cd51a61cdd7337fd17c17e8f6.metadata.json
```

It is an important property when it comes to reproducability, that you can reproduce the same dependency cache in your build pipelines. As @emilazy already mentioned;
i can confirm those action points, before I can start using deno in production.

**Comment by hsjobeki** [comment]
@bartlomieju do you have any suggestions?
I saw you discussed #16296 earlier. Deno Lockfile incompleteness is hindering me to use it in production (i must still use node :( )
I'd also be happy to write a PR that adds redirect entries to the lockfile, but i am not sure if this is rather a workaround, than a real fix of the problem.

I think this needs an architectural solution.

**Comment by emilazy** [comment]
I don't think it'd be a hack to add redirects to the lock file as long as the hash closes over important headers like I suggested. (Happy to work on this too, of course; I dove in to the source shortly after reporting the original issue but sadly ran into complexities of the redirect handling that made it more difficult than I expected.)

**Comment by dsherret** [comment]
Redirects are being added in https://github.com/denoland/deno/pull/20262

I'd recommend checking out the new experimental vendor feature by adding `"vendor": true` to your config file. It will create a `./vendor` folder in your project that makes it way easier to do reproducible builds. Currently, it's undocumented and will be announced in the next minor release, but I doubt it will change much.

As for adding X-TypeScript-Types to the lockfile, we currently don't store files that aren't used for execution in the lockfile, so parts of the graph like TypeScript types won't be included there. For other headers, I don't believe it's necessary to store them in the lockfile. It might seem like the Content-Type header should also be stored, but any changes from something like JSON to JavaScript will cause a runtime error because the type is asserted in the code via `assert { type: "json" }`.
