### ISSUE TITLE
Regression in `node:zlib` polyfill in Deno v1.32.3

### ISSUE THREAD

**Issue by danopia** [denoland/deno#19540]
* The `dictionary` parameter is not accepted anymore when setting up zlib.
* I saw the regression with both `createDeflate` and `createInflate`.
* Last working in Deno v1.32.2 and is still failing on the latest release.
* Perhaps introduced by https://github.com/denoland/deno/pull/18291
* My usecase is implementing SPDY which has a predefined zlib dictionary for header compression.

Minimal reproduction, with zero-length dictionary:

```js
import { Buffer } from 'node:buffer';
import { createDeflate } from 'node:zlib';

createDeflate({
  dictionary: Buffer.alloc(0),
});
console.log('All good!');
```

```sh
# nodejs runs the script fine:
$ node repro.js
All good!

# deno v1.34.2 throws:
$ deno run repro.js
error: Uncaught TypeError: Error parsing args at position 5: invalid type: byte array, expected a borrowed byte array
createInflate({
^
    at Zlib.init (ext:deno_node/_zlib_binding.mjs:146:21)
    at Inflate.Zlib (ext:deno_node/_zlib.mjs:352:16)
    at new Inflate (ext:deno_node/_zlib.mjs:214:8)
    at createInflate (ext:deno_node/_zlib.mjs:45:10)
    at file:///Users/daniellamando/Code/tmp.Rn9UISKm/repro.js:4:1

# last working deno version via a docker container:
$ podman run --rm -v (pwd):/src denoland/deno:alpine-1.32.2 run /src/repro.js
All good!
```

Also I noticed that Deno only allows `Buffer` instances for `dictionary`. [As per nodejs docs](https://nodejs.org/api/zlib.html#class-options), `Uint8Array` is accepted since node v8.0 and `ArrayBuffer` since node v9.4. So perhaps the polyfill should accept them too.

**Comment by danopia** [comment]
I just verified with the latest canary and zlib dictionaries are working again. Thanks a lot! <3

**Comment by bartlomieju** [comment]
> I just verified with the latest canary and zlib dictionaries are working again. Thanks a lot! <3

No problem, and sorry for breaking it 😓
