### ISSUE TITLE
Really long URLs make Deno panic

### ISSUE THREAD

**Issue by eikooc** [denoland/deno#19542]
This error happens when I made a really long URL and tried to test if it existed in azure blob storage with this function `getBlockBlobClient`.

---

Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 1.34.3
Args: ["/home/user/.deno/bin/deno", "run", "--cached-only", "--watch", "--allow-all", "src/main.ts"]

thread 'main' panicked at 'a parsed Url should always be a valid Uri: InvalidUri(TooLong)', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/reqwest-0.11.18/src/into_url.rs:80:14
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/result.rs:1790:5
   3: reqwest::into_url::expect_uri
   4: reqwest::async_impl::client::Client::execute_request
   5: deno_node::ops::http::op_node_http_request::call::{{closure}}
   6: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
   7: deno_fetch::op_fetch_send::v8_fn_ptr
   8: _ZN2v88internal12_GLOBAL__N_119HandleApiCallHelperILb0EEENS0_11MaybeHandleINS0_6ObjectEEEPNS0_7IsolateENS0_6HandleINS0_10HeapObjectEEENS8_INS0_20FunctionTemplateInfoEEENS8_IS4_EEPmi
             at ./../../../../v8/src/builtins/builtins-api.cc:113:36
   9: _ZN2v88internal21Builtin_HandleApiCallEiPmPNS0_7IsolateE
             at ./../../../../v8/src/builtins/builtins-api.cc:135:1
  10: Builtins_CEntry_Return1_ArgvOnStack_BuiltinExit
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by kamilogorek** [comment]
Eh, it's this thing again https://github.com/seanmonstar/reqwest/pull/1707

**Comment by bartlomieju** [comment]
We've migrated to `hyper` instead of using `reqwest`. I believe this is now fixed.
