### ISSUE TITLE
re-enable REPL tests

### ISSUE THREAD

**Issue by ry** [denoland/deno#1955]
"core" is a major API refactor that significantly simplified and sped up the code base. However not all issues have been worked out - it was landed with some tests disabled.
See https://github.com/denoland/deno/pull/1938/commits/b672c12ba684477ac62896e02fe3b57ca4ae904d

These are tests that need to be turned back on:
- [x] tests/error_004_missing_module.test
- [x] tests/error_005_missing_dynamic_import.test
- [x] tests/error_006_import_ext_failure.test
- [ ] repl_test test_set_timeout
- [ ] repl_test test_async_op
- [ ] repl_test test_set_timeout_interlaced
- [x] all of permission_prompt_test https://github.com/denoland/deno/pull/1957

**Comment by bartlomieju** [comment]
FYI `tests/error_*` are enabled and passing, only `repl_test` are disabled.

**Comment by bartlomieju** [comment]
REPL tests were rewritten to Rust, this issue is no longer relevant
