### ISSUE TITLE
Broken help text / command descriptions

### ISSUE THREAD

**Issue by avindra** [denoland/deno#19554]
`deno help` is missing command descriptions (likely after #19467 )

broken (1.34.3) ❌ : 

![scrot-L3Rc](https://github.com/denoland/deno/assets/126848/e4247742-09e8-4324-a84d-ada3840ef45c)

working (1.34.2) ✅  

![scrot-tgay](https://github.com/denoland/deno/assets/126848/b3b74c55-5cf4-4c6b-bdcc-2ad7a4a9abfa)

**Comment by AMMAR-62** [comment]
May I work on this issue??
