### ISSUE TITLE
[node:crypto] Reconcile `getHashes` and `createHash`

### ISSUE THREAD

**Issue by fbaltor** [denoland/deno#19576]
While `getHashes` seems to be generating an hash algorithm list from a hardcoded list in [`ext/node/polyfills/internal/crypto/utils.ts`](https://github.com/denoland/deno/blob/c3d670dbc992ffaff02cd8df82335ee41e88596e/ext/node/polyfills/internal/crypto/util.ts#L154-L156), the `createHash` ultimately creates a hash function from another hardcoded "list" in [`ext/node/ops/crypto/digest.rs`](https://github.com/denoland/deno/blob/1f0360c07382dbd86066d1aa8aa4bae34aff18c5/ext/node/ops/crypto/digest.rs#L63-L75). The problem is that several algorithms from `getHashes` aren't implemented yet in the `createHash` source.

**Comment by fbaltor** [comment]
What about adding a rust `getHashes` to [`ext/node/ops/crypto/digest.rs`](https://github.com/denoland/deno/blob/1f0360c07382dbd86066d1aa8aa4bae34aff18c5/ext/node/ops/crypto/digest.rs#L11-L20), creating the correspondent part in the [`ext/node/polyfills/internal/crypto/hash.ts`](https://github.com/denoland/deno/blob/63befe9377fcf688415633df76184fac5fe4ef73/ext/node/polyfills/internal/crypto/hash.ts#L56) and removing the hardcoded implementation from [`ext/node/polyfills/internal/crypto/utils.ts`](https://github.com/denoland/deno/blob/c3d670dbc992ffaff02cd8df82335ee41e88596e/ext/node/polyfills/internal/crypto/util.ts#L154-L156)?

**Comment by fbaltor** [comment]
There is a TODO about generating the hash list from [`std/crypto_wasm/mod.ts`](https://github.com/denoland/deno/blob/c3d670dbc992ffaff02cd8df82335ee41e88596e/ext/node/polyfills/internal/crypto/util.ts#L20-L47) but _I think_ it was "ported" from the deno_std implementation. @kt3k

**Comment by kt3k** [comment]
> What about adding a rust getHashes to [ext/node/ops/crypto/digest.rs](https://github.com/denoland/deno/blob/1f0360c07382dbd86066d1aa8aa4bae34aff18c5/ext/node/ops/crypto/digest.rs#L11-L20), creating the correspondent part in the [ext/node/polyfills/internal/crypto/hash.ts](https://github.com/denoland/deno/blob/63befe9377fcf688415633df76184fac5fe4ef73/ext/node/polyfills/internal/crypto/hash.ts#L56) and removing the hardcoded implementation from [ext/node/polyfills/internal/crypto/utils.ts](https://github.com/denoland/deno/blob/c3d670dbc992ffaff02cd8df82335ee41e88596e/ext/node/polyfills/internal/crypto/util.ts#L154-L156)?

sounds good to me

**Comment by fbaltor** [comment]
Issue resolved in #19561.
