### ISSUE TITLE
Node socket polyfill is missing destroy method

### ISSUE THREAD

**Issue by abrgr** [denoland/deno#19571]
I am using the aws-sdk via an npm: specifier and they use the following pattern:
```
req = http.request(...);
req.on("timeout", () => { req.destroy(); })
```

This fails when running under deno because `FakeSocket` (https://github.com/denoland/deno/blob/2ec366f54423dc577379b9245e498681fccf3050/ext/node/polyfills/http.ts#L273) doesn't implement a `destroy` method.

Destroy is called from deno's node http polyfill here (https://github.com/denoland/deno/blob/2ec366f54423dc577379b9245e498681fccf3050/ext/node/polyfills/http.ts#L754).

Happy to put up a PR to add a dummy destroy method to FakeSocket (or test that destroy is a function before calling it) if that would be helpful.

Running deno 1.34.3 in the denoland/deno:ubuntu-1.34.3 docker image.

**Comment by bartlomieju** [comment]
Looks like this method is now available.
