### ISSUE TITLE
vite for bundle ts-npm-deno code

### ISSUE THREAD

**Issue by elycheikhsmail** [denoland/deno#19596]
Is it possible to use Vite to bundle TS, JS, and npm for Deno? (Deno is often referred to as the "browser" of the server.)
the use case: use npm modules without restriction for web hosted on deno deploy (I know esm.sh exists ).

**Comment by bartlomieju** [comment]
Vite doesn't support `npm:` specifier so the short answer will be no.

**Comment by elycheikhsmail** [comment]
vite pluging for :npm can solve this issue ? isn't ?

**Comment by bartlomieju** [comment]
This is now solved with https://www.npmjs.com/package/@deno/vite-plugin.
