### ISSUE TITLE
Using cURL to request headers only from HTTP/2 results in PROTOCOL_ERROR

### ISSUE THREAD

**Issue by ychin** [denoland/deno#19605]
When I initialize an HTTP/2 server, and then use cURL to issue a request, it works. But if I request the headers only using `curl -I`, it seems to throw a protocol error, as follows:

```
% curl -k https://localhost:8080
Hello world!
% curl -k https://localhost:8080 -I   
curl: (92) HTTP/2 stream 1 was not closed cleanly: PROTOCOL_ERROR (err 1)
```

Below is the verbose result:

```
% curl -k https://localhost:8080 -v -I
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
* ALPN: offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
* (304) (IN), TLS handshake, Server hello (2):
* (304) (IN), TLS handshake, Unknown (8):
* (304) (IN), TLS handshake, Certificate (11):
* (304) (IN), TLS handshake, CERT verify (15):
* (304) (IN), TLS handshake, Finished (20):
* (304) (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / AEAD-CHACHA20-POLY1305-SHA256
* ALPN: server accepted h2
* Server certificate:
*  <omitted certificate details>
*  SSL certificate verify result: self signed certificate (18), continuing anyway.
* using HTTP/2
* h2h3 [:method: HEAD]
* h2h3 [:path: /]
* h2h3 [:scheme: https]
* h2h3 [:authority: localhost:8080]
* h2h3 [user-agent: curl/7.88.1]
* h2h3 [accept: */*]
* Using Stream ID: 1 (easy handle 0x140814800)
> HEAD / HTTP/2
> Host: localhost:8080
> user-agent: curl/7.88.1
> accept: */*
> 
* HTTP/2 stream 1 was not closed cleanly: PROTOCOL_ERROR (err 1)
* Connection #0 to host localhost left intact
curl: (92) HTTP/2 stream 1 was not closed cleanly: PROTOCOL_ERROR (err 1)
```

For reference, here is the server code (run using `deno run --unstable --allow-net --allow-read server.ts`):

````js
const certFile='./servert.crt', keyFile='./server.key';
for await (
  const conn of Deno.listenTls({
    port: 8080, certFile, keyFile,
    alpnProtocols: [ "h2", "http/1.1" ],
  })
) {
  for await (const { request: req, respondWith: res } of Deno.serveHttp(conn)) {
    res(new Response("Hello world!\n"));
  }
}
````

I tried to look around and didn't see any similar issue being filed and this does seem like a bug to me as it doesn't happen in http/1 and generally cURL shouldn't result in a protocol error. There is a similar issue in deno_std but I think it's not exactly the same: https://github.com/denoland/deno_std/issues/3198.

I'm new to Deno though so I could be missing something.

Also note that I found similar issues with using Oak with HTTP/2 turned on as well but the error looks a little different.

---

I'm using deno 1.34.3, installed via Homebrew on macOS 13.4.1.

**Comment by ychin** [comment]
Just for reference the Oak error that I mentioned looks like this:

```
[uncaught application error]: Http - connection error: broken pipe: broken pipe

    at async HttpConn.nextRequest (ext:deno_http/01_http.js:101:21)
    at async serve (https://deno.land/x/oak@v12.5.0/http_server_native.ts:112:34)
```

This error happens on the server side, but the client side (cURL) actually doesn't report any errors somethow.

**Comment by lucacasonato** [comment]
`curl -I` makes a `HEAD` request rather than a `GET` request.

In Deno, if the request has `req.method === "HEAD"`, the `Response`'s body should be `null`.

**Comment by ychin** [comment]
Ah ok right that seems to fix it. Thanks.
