### ISSUE TITLE
Key Part Ordering Incomplete

### ISSUE THREAD

**Issue by anywhichway** [denoland/deno#19607]
Unless I am missing something, the key ordering as documented makes it impossible to select a key using `db.list` with start and end when that key has as its final element a boolean with the value `true`. 

Assume these keys:

```
["a"]
[1]
[false]
[true]
```

This call would get all the keys except [true].

```
db.list({start:[new UInt8array([])],end:[true])
```

The options to resolve the issue seem to be:

1. Provide a flag to make the list inclusive of the end
2. Allow 'undefined' or 'null' as the highest value in find but not as key parts
3. Allow making the end one element shorter than the start

Or, if I am missing something, documentation saying how to do this would be useful.

Here is the online documentation:

```
Key Part Ordering
Key parts are ordered lexicographically by their type, and within a given type, they are ordered by their value. The ordering of types is as follows:

Uint8Array
string
number
bigint
boolean
Within a given type, the ordering is:

Uint8Array: byte ordering of the array
string: byte ordering of the UTF-8 encoding of the string
number: -NaN < -Infinity < -1.0 < -0.5 < -0.0 < 0.0 < 0.5 < 1.0 < Infinity < NaN
bigint: mathematical ordering, largest negative number first, largest positive number last
boolean: false < true
```

**Comment by losfair** [comment]
You can use an empty Uint8Array suffix. For your example:

```
["a"]
[1]
[false]
[true]
```

You can list all of them with:

```
db.list({ start: [], end: [true, new Uint8Array()] });
```

**Comment by anywhichway** [comment]
Aha! Thank you.


________________________________
