### ISSUE TITLE
Correctly formatting transpiled JS errors

### ISSUE THREAD

**Issue by cd-work** [denoland/deno#19617]
I'm using `deno_runtime` to execute TypeScript code and am struggling a bit with `JsError` line numbers being incorrect. This isn't very unexpected considering I do no source mapping myself, but looking into this I've found myself confused with the "correct" way to source map errors in Deno.

The comment on `JsError` does mention source mapping and says there's a `JsError` struct in `cli` that does it all for CLI anyway. I was trying to find this struct so see if it could maybe be moved into `deno_runtime` but I cannot find any other `JsError` definitions:

https://github.com/denoland/deno/blob/fa935e553a9ec37d39d2274432a00f1b465cef0f/core/error.rs#L136-L143

The `deno_core/source_map.rs` module seems to provide everything you'd need to remap a `JsError` and it should be possible to make use of it to convert an error by hand. But I'm somewhat surprised that there's no function that just takes in a source map and a `JsError` and automatically maps that error for me, considering the documentation suggests that's one of its primary purposes:

https://github.com/denoland/deno/blob/fa935e553a9ec37d39d2274432a00f1b465cef0f/core/source_map.rs#L3C1-L3C1

So while I think I should be able to get this fixed without any changes to `deno`, I'm not entirely sure about the "correct" way to go about it. Is manually mapping the way to go and if so, would you maybe be interested in providing a function on `JsError` or in `source_map.rs` that does it for you?

**Comment by cd-work** [comment]
I hate to necrobump issues like this but I'd love to know why answering this question seems to provide some difficulties.

Is this generally supposed to "just work"? Or are there different possible scenarios that might cause this source mapping to break, making it difficult to troubleshoot without more details and time invested?

Looking at the startup snapshot, it seems like `Error.prepareStackTrace` is the same as with the `deno` CLI, so I'd assume it's not related to the startup snapshot at least?

**Comment by bartlomieju** [comment]
@cd-work the documentation seems to be outdated. The source mapping needs to happen in `deno_core` because what actually source maps errors is accessing the `.stack` property on the `Error` instance - there's a fairly involved machinery that ping-pings between Rust and JS to achieve this (`prepareStackTrace` + `sourceMapCallSiteEval` + `formatCallSiteEval`). 

It's hard to know what exactly goes wrong without seeing your exact setup. Do you have some reproduction code that you could share?

**Comment by cd-work** [comment]
> @cd-work the documentation seems to be outdated. The source mapping needs to happen in deno_core because what actually source maps errors is accessing the .stack property on the Error instance - there's a fairly involved machinery that ping-pings between Rust and JS to achieve this (prepareStackTrace + sourceMapCallSiteEval + formatCallSiteEval).

It seems like that is done automatically when a `JsError` is constructed, right? I've looked for the things you said and it seems like [this code](https://github.com/denoland/deno_core/blob/93f62f0fa2b58d781c3bd80a5abb2d94de26233b/core/error.rs#L388-L399) is what you're talking about.

I think that code should be run by us, since we just print the `JsError` (so it has to be created by core):
https://github.com/phylum-dev/cli/blob/2348dd34bab82028bf44798cbb06f38bea39c884/cli/src/deno.rs#L85-L101

However I did notice that we do not set `source_map_getter` on the `WorkerOptions`, so I'll try to get that setup and report back if it fixes things.

**Comment by bartlomieju** [comment]
> > @cd-work the documentation seems to be outdated. The source mapping needs to happen in deno_core because what actually source maps errors is accessing the .stack property on the Error instance - there's a fairly involved machinery that ping-pings between Rust and JS to achieve this (prepareStackTrace + sourceMapCallSiteEval + formatCallSiteEval).
> 
> It seems like that is done automatically when a `JsError` is constructed, right? I've looked for the things you said and it seems like [this code](https://github.com/denoland/deno_core/blob/93f62f0fa2b58d781c3bd80a5abb2d94de26233b/core/error.rs#L388-L399) is what you're talking about.
> 

Ah good point, I forgot that we access this prop unconditionally.

> I think that code should be run by us, since we just print the `JsError` (so it has to be created by core): https://github.com/phylum-dev/cli/blob/2348dd34bab82028bf44798cbb06f38bea39c884/cli/src/deno.rs#L85-L101
> 
> However I did notice that we do not set `source_map_getter` on the `WorkerOptions`, so I'll try to get that setup and report back if it fixes things.

That might be the problem indeed, once you set `source_map_getter` then `JsError` should actually do source mapping for you. Let me know if that works!

**Comment by cd-work** [comment]
I've managed to fix this error by adding a `source_map_getter`. Here's the code in case anyone else runs into this:
https://github.com/phylum-dev/cli/pull/1187

One last question I do have is about `inline_source_map` in the transpilation options. I had to set that to `false` to ensure `source_map` is actually populated when transpiling, which makes sense of course. But considering that the default is `true` I'd be curious how you get the sourcemap when it is inlined.

I would assume that the inlined source would have to be extracted from the actual source code, making this a rather cumbersome operation? This would mean that `false` is probably the correct choice here.

If there's an "easier" way to do this, I'm curious how it would work. I wasn't able to just specify the code itself as source map for example, which I originally thought might work.

**Comment by bartlomieju** [comment]
> One last question I do have is about inline_source_map in the transpilation options. I had to set that to false to ensure source_map is actually populated when transpiling, which makes sense of course. But considering that the default is true I'd be curious how you get the sourcemap when it is inlined.
>
> I would assume that the inlined source would have to be extracted from the actual source code, making this a rather cumbersome operation? This would mean that false is probably the correct choice here.

I believe this is then handled auto-magically by V8 if the source map is inlined and not referenced via an URL.

**Comment by cd-work** [comment]
> I believe this is then handled auto-magically by V8 if the source map is inlined and not referenced via an URL.

Interesting, though I guess that doesn't really help since many modules are referenced via URL.
