### ISSUE TITLE
NPM import of Babylon.js fails

### ISSUE THREAD

**Issue by fazil47** [denoland/deno#19623]
I'm trying to use Babylon.js in a Fresh project (not sure if it's a problem specific to Fresh), but I'm getting the following error when I run the app: 

```PowerShell
error: Uncaught (in promise) TypeError: Could not resolve '../../Misc/logger.js' from 'file:///C:/Users/fazil/AppData/Local/deno/npm/registry.npmjs.org/@babylonjs/core/6.9.0/Physics/v1//physicsImpostor.js'.
  Caused by:
    [ERR_MODULE_NOT_FOUND] Cannot find module "file:///C:/Users/fazil/AppData/Local/deno/npm/registry.npmjs.org/@babylonjs/core/6.9.0/Physics/Misc/logger.js" imported from "file:///C:/Users/fazil/AppData/Local/deno/npm/registry.npmjs.org/@babylonjs/core/6.9.0/Physics/v1//physicsImpostor.js" 
  await import(entrypoint);
  ^
    at async dev (https://deno.land/x/fresh@1.2.0/src/dev/mod.ts:140:3)
    at async file:///C:/Users/fazil/temp/babylon-fresh/dev.ts:5:1
Watcher Process failed. Restarting on file change...
```

`physicsImposter.js` is trying to import `@babylonjs/core/6.9.0/Misc/logger.js` but instead gets `@babylonjs/core/6.9.0/Physics/Misc/logger.js`.

**Comment by mahlm** [comment]
Workaround is to use full npm module: https://www.npmjs.com/package/babylonjs

eg
``` typescript
import BABYLON from "npm:babylonjs";
import SERIALIZERS from "npm:babylonjs-serializers";
```

**Comment by fazil47** [comment]
Gets rid of the errors but nothing gets rendered and I'm getting these warnings:

```Powershell
▲ [WARNING] Non-relative path "lts/core/generated/*" is not allowed when "baseUrl" is not set (did you forget a leading "./"?) [plugin deno-loader] [tsconfig.json]

    ../../AppData/Local/deno/deno_esbuild/babylonjs@6.10.0/node_modules/babylonjs/tsconfig.json:6:23:
      6 │             "core/*": ["lts/core/generated/*"],
        ╵                        ~~~~~~~~~~~~~~~~~~~~~~

  The plugin "deno-resolver" was triggered by this import

    components/babylon/app.ts:1:20:
      1 │ import BABYLON from "babylonjs";
        ╵                     ~~~~~~~~~~~

▲ [WARNING] Non-relative path "lts/gui/generated/*" is not allowed when "baseUrl" is not set (did you forget a leading "./"?) [plugin deno-loader] [tsconfig.json]

    ../../AppData/Local/deno/deno_esbuild/babylonjs-gui@6.10.0/node_modules/babylonjs-gui/tsconfig.json:6:22:
      6 │             "gui/*": ["lts/gui/generated/*"],
        ╵                       ~~~~~~~~~~~~~~~~~~~~~

  The plugin "deno-resolver" was triggered by this import

    components/babylon/app.ts:2:24:
      2 │ import BABYLON_GUI from "babylonjs-gui";
        ╵                         ~~~~~~~~~~~~~~~

▲ [WARNING] Non-relative path "lts/loaders/generated/*" is not allowed when "baseUrl" is not set (did you forget a leading "./"?) [plugin deno-loader] [tsconfig.json]

    ../../AppData/Local/deno/deno_esbuild/babylonjs-loaders@6.10.0/node_modules/babylonjs-loaders/tsconfig.json:6:26:
      6 │             "loaders/*": ["lts/loaders/generated/*"],
        ╵                           ~~~~~~~~~~~~~~~~~~~~~~~~~

  The plugin "deno-resolver" was triggered by this import

    components/babylon/app.ts:4:7:
      4 │ import "babylonjs-loaders";
        ╵        ~~~~~~~~~~~~~~~~~~~

▲ [WARNING] Non-relative path "lts/core/generated/*" is not allowed when "baseUrl" is not set (did you forget a leading "./"?) [plugin deno-loader] [tsconfig.json]

    ../../AppData/Local/deno/deno_esbuild/babylonjs@6.10.0/node_modules/babylonjs/tsconfig.json:6:23:
      6 │             "core/*": ["lts/core/generated/*"],
        ╵                        ~~~~~~~~~~~~~~~~~~~~~~

  The plugin "deno-resolver" was triggered by this import

    ../../AppData/Local/deno/deno_esbuild/babylonjs-loaders@6.10.0/node_modules/babylonjs-loaders/babylonjs.loaders.js:3:35:
      3 │     module.exports = factory(require("babylonjs"));
        ╵                                      ~~~~~~~~~~~

▲ [WARNING] Non-relative path "lts/core/generated/*" is not allowed when "baseUrl" is not set (did you forget a leading "./"?) [plugin deno-loader] [tsconfig.json]

    ../../AppData/Local/deno/deno_esbuild/babylonjs@6.10.0/node_modules/babylonjs/tsconfig.json:6:23:
      6 │             "core/*": ["lts/core/generated/*"],
        ╵                        ~~~~~~~~~~~~~~~~~~~~~~

  The plugin "deno-resolver" was triggered by this import

    ../../AppData/Local/deno/deno_esbuild/babylonjs-gui@6.10.0/node_modules/babylonjs-gui/babylon.gui.js:3:35:
      3 │     module.exports = factory(require("babylonjs"));
```

**Comment by nicu-chiciuc** [comment]
If the point is making babylon work in a fresh island it's possible to import it from the [cdn babylon docs](https://doc.babylonjs.com/setup/frameworkPackages/CDN):

```tsx
import * as BABYLONu from "https://cdn.babylonjs.com/babylon.max.js";
const BABYLON = BABYLONu as any;
```

I managed to copy their default setup script:
<details><summary>full file content</summary>
<p>
import type { Signal } from "@preact/signals";

import * as BABYLONu from "https://cdn.babylonjs.com/babylon.max.js";
const BABYLON = BABYLONu as any;

import { useEffect } from "preact/hooks";

function mainScript() {
  const canvas = document.getElementById("renderCanvas"); // Get the canvas element
  const engine = new BABYLON.Engine(canvas, true); // Generate the BABYLON 3D engine
  const createScene = function () {
    // Creates a basic Babylon Scene object
    const scene = new BABYLON.Scene(engine);
    // Creates and positions a free camera
    const camera = new BABYLON.FreeCamera(
      "camera1",
      new BABYLON.Vector3(0, 5, -10),
      scene
    );
    // Targets the camera to scene origin
    camera.setTarget(BABYLON.Vector3.Zero());
    // This attaches the camera to the canvas
    camera.attachControl(canvas, true);
    // Creates a light, aiming 0,1,0 - to the sky
    const light = new BABYLON.HemisphericLight(
      "light",
      new BABYLON.Vector3(0, 1, 0),
      scene
    );
    // Dim the light a small amount - 0 to 1
    light.intensity = 0.7;
    // Built-in 'sphere' shape.
    const sphere = BABYLON.MeshBuilder.CreateSphere(
      "sphere",
      { diameter: 2, segments: 32 },
      scene
    );
    // Move the sphere upward 1/2 its height
    sphere.position.y = 1;
    // Built-in 'ground' shape.
    const ground = BABYLON.MeshBuilder.CreateGround(
      "ground",
      { width: 6, height: 6 },
      scene
    );
    return scene;
  };
  const scene = createScene(); //Call the createScene function
  // Register a render loop to repeatedly render the scene
  engine.runRenderLoop(function () {
    scene.render();
  });
  // Watch for browser/canvas resize events
  window.addEventListener("resize", function () {
    engine.resize();
  });
}

interface CounterProps {
  count: Signal<number>;
}

export default function Counter(props: CounterProps) {
  useEffect(() => {
    mainScript();
  }, []);

  return <canvas class="w-screen h-screen" id="renderCanvas"></canvas>;
}
</p>
</details> 

the drawback is that there aren't typings, but I'm sure they can be added

**Comment by crowlKats** [comment]
Clsoing as this is working now.
