### ISSUE TITLE
Issue when using execute_script

### ISSUE THREAD

**Issue by juli1** [denoland/deno#19638]
When I use the `execute_script` function, I get the error below.

I am using the following version of the crate:

```
deno_core = "0.191.0"
```

According to the traceback, this is the line in `deno` that fails:

```
    let source = Self::string_from_code(scope, &source_code).unwrap();
```

Error:
```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /Users/julien.delange/.cargo/registry/src/github.com-1ecc6299db9ec823/deno_core-0.191.0/runtime/jsrealm.rs:316:62
stack backtrace:
   0: rust_begin_unwind
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
   2: core::panicking::panic
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:114:5
   3: deno_core::runtime::jsrealm::JsRealm::execute_script
   4: deno_core::runtime::jsruntime::JsRuntime::execute_script
   5: core::analysis::javascript::execute_rule
   6: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
   7: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
   8: core::analysis::analyze::analyze
   9: datadog_static_analyzer::main::{{closure}}
  10: rayon::iter::plumbing::Folder::consume_iter
  11: rayon::iter::plumbing::bridge_producer_consumer::helper
  12: rayon_core::join::join_context::{{closure}}
  13: rayon_core::registry::in_worker
  14: rayon::iter::plumbing::bridge_producer_consumer::helper
  15: rayon_core::job::StackJob<L,F,R>::run_inline
  16: rayon_core::join::join_context::{{closure}}
  17: rayon_core::registry::in_worker
  18: rayon::iter::plumbing::bridge_producer_consumer::helper
  19: rayon_core::join::join_context::{{closure}}
  20: rayon_core::registry::in_worker
  21: rayon::iter::plumbing::bridge_producer_consumer::helper
  22: rayon_core::job::StackJob<L,F,R>::run_inline
  23: rayon_core::join::join_context::{{closure}}
  24: rayon_core::registry::in_worker
  25: rayon::iter::plumbing::bridge_producer_consumer::helper
  26: rayon_core::join::join_context::{{closure}}
  27: rayon_core::registry::in_worker
  28: rayon::iter::plumbing::bridge_producer_consumer::helper
  29: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
  30: rayon_core::registry::WorkerThread::wait_until_cold
  31: rayon_core::registry::ThreadBuilder::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by bartlomieju** [comment]
@juli1 can you provide the script you're trying to execute?

@mmastrac please take a look.

**Comment by mmastrac** [comment]
Strange. The only reason I can think of that this might happen is if you are trying to execute a string that is larger than `v8::String::max_length`. 

Can you provide the string you are trying to execute? It's possible we might have a bug w/ASCII detection as well.

**Comment by juli1** [comment]
I cannot share the string because it contains customer data. But basically, we read source files and pass the content of each source file as a string in the script. I doubt we go to the max size, but I think it may be a bug with ASCII detection (the string may contain emoji, etc).

Regardless, we should return an error rather than fail here on `.unwrap()`. Probably check the result of `string_from_code`

**Comment by mmastrac** [comment]
How are you creating the `ModuleCode` that you are passing into `execute_script`?

**Comment by juli1** [comment]
Using `let code: FastString = js_code.into();` where `js_code` is created with `format!`.

**Comment by mmastrac** [comment]
Thanks for the info...  From what I can see digging into v8, the only way that these string routines can fail is if it's too long. Would you mind double-checking the length of the string (specifically `FastString::as_bytes().len()`)? 

Given that this is a common API, we definitely should be returning errors rather than panicking, but I'd like to make sure there isn't something strange going on as well.

**Comment by mmastrac** [comment]
I'm not able to check right now but it might be ~512MB. I believe the current number is always available at `v8::String::max_length()`.

I would recommend chunking the data smaller, or perhaps feeding it in via JSON or direct function execution (`v8::Function`)

**Comment by bartlomieju** [comment]
@juli1 I'm gonna close this one for now, if you still have problem with `deno_core`, I'd appreciate a new issue at https://github.com/denoland/deno_core/issues/new
