### ISSUE TITLE
Web platform tests randomly fail in CI on ubuntu-x86_64

### ISSUE THREAD

**Issue by not-my-profile** [denoland/deno#19652]
Examples:

* f372688f2285ee1a97128b718ec3d9f090752c36 https://github.com/denoland/deno/actions/runs/5387608336/jobs/9779155798#step:43:13332
* 8d6dbda90ec0593f3f6e10c6696e320bdff7daa9 https://github.com/denoland/deno/actions/runs/5363833903/jobs/9731666308#step:43:13336
* 76bff33a193c12389f7c99f2eb3efa1deacc5bf7 https://github.com/denoland/deno/actions/runs/5363224567/jobs/9730648633#step:43:13339
* 76f85a783e3ba4064027f581eb1fecf2ecba9de0 https://github.com/denoland/deno/actions/runs/5353386235/jobs/9709221617#step:43:13345

And the step is also consistently failing in my PR #19573.

**Comment by mmastrac** [comment]
I just pushed a fix for some of these (websockets-releated) in #19642 but this one seems new:

```
        "/hr-time/window-worker-timeOrigin.window.html - timeOrigin and now() should be correctly ordered between window and worker"
```

**Comment by mmastrac** [comment]
Closing this one -- we can reopen with newer failures.
