### ISSUE TITLE
Windows installation error IE

### ISSUE THREAD

**Issue by Maxim-Mazurok** [denoland/deno#1965]
I'm getting the following error on the Windows 10 PC:
```
iwr : The response content cannot be parsed because the Internet Explorer engine is not available, or Internet Explorer's first-launch configuration is not complete. Specify the UseBasicParsing parameter and try again.
At line:1 char:1
+ iwr https://deno.land/x/install/install.ps1 | iex
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotImplemented: (:) [Invoke-WebRequest], NotSupportedException
    + FullyQualifiedErrorId : WebCmdletIEDomNotSupportedException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
```

**Solution**
Just run IE for the first time and finish initial setup (click OK on [this](https://i2.wp.com/wahlnetwork.com/wp-content/uploads/2015/11/ie-first-launch.jpg) screen).

**Proposal**
For whatever reasons, I've never even started IE on my PC. I've used only Edge (which is the new default browser on Windows now).
So, I think that it might be a common error for newcomers. 
[There are](https://stackoverflow.com/a/38054505) some workarounds, involving `-UseBasicParsing` option for `Invoke-WebRequest`.

**Comment by zekth** [comment]
Experienced that too. Could you submit a PR to update the Manual for this?

**Comment by Maxim-Mazurok** [comment]
Well... I would like to solve it in the way that will resolve this issue without the Manual update.
But I'm not good at Windows scripting, so I don't think that I'm the right person to make a PR with the fix.
So, probably you're right about adding a note to the Manual. I would also add a note about TLS issue, which should be very popular on Windows.
But I feel like we should ask @ry first, should we wait for the install script fixes, or go ahead and add notes of possible issues during installation on Windows?
Originally, I thought that in the meantime, the "googlable" issue on the GitHub should be enough for now. But that's only true if somebody is willing to work on that issue in the future. And I have no clue about that.

**Comment by zekth** [comment]
Atm the installation on windows is just a script to download deno binary and add deno path to PATH env var: https://github.com/denoland/deno_install/blob/master/install.ps1
Not really complicated, i think adding this to the ps1 might be an idea too. I can take a look. Adding the support for chocolatey would be cool too.

**Comment by Maxim-Mazurok** [comment]
Actually, I think that the issue is more complicated. We're using `iwr` for downloading. And that's the source of all problems. It's defaulting to TLS 1.0 and also uses parsing method which uses IE engine.
So, if I understand that correctly, then we'll need to dive deeper and replace `iwr` with some more low-level calls, where we can customize their exact behavior. Or, if `iwr` is customizable enough though flags, we can also do it this way.
And, about chocolatey, I agree that it may be better way. Because if we'll go the path of doing low-level calls, the script might get bigger then one line.

**Comment by Maxim-Mazurok** [comment]
Hm, or maybe you're right, because I see `Invoke-WebRequest` in the script, so it might be a weak point, actually..

**Comment by zekth** [comment]
ATM for the `ps1` solution, updating the manual is the only way to solve the problem. Once you got all the commands; just copy paste and VOILA.

**Comment by Maxim-Mazurok** [comment]
So, your idea is to avoid downloading `.ps1` script with `iwr` by just letting the user copy paste contents of it with all commands manually to the PowerShell? That's what you are saying?

**Comment by zekth** [comment]
No. Just add the fixes with : 
`[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12` in the manual, and check the `UseBasicParsing ` flag in the deno_install

**Comment by MarkTiedemann** [comment]
> And, about chocolatey, I agree that it may be better way.

On Windows, you can install `deno` via `scoop` already: https://github.com/denoland/deno_install#install-via-package-manager

In regards to `-UseBasicParsing`, I believe we should add a note to the Known Issues section (https://github.com/denoland/deno_install#known-issues) as well as use the flag in the script internally.
