### ISSUE TITLE
[BUG] Module name parsing is broken with some modules.

### ISSUE THREAD

**Issue by andriejs** [denoland/deno#19656]
Some modules, Such as `socket.io` or `socket.io-client` contain `.` (dot) which the parser thinks it's referring to a file, Instead of a module.

**Comment by dsherret** [comment]
Are you talking about npm support? The following works for me:

```ts
import * as test from "npm:socket.io";

console.log(test);
```

**Comment by andriejs** [comment]
ohhh. Yeah, The issue was I had "socket.io" in my import map which didn't go well with that soo yeah.

**Comment by dsherret** [comment]
@andriejs could you explain a bit more? Otherwise I can close this issue. It also works fine in import maps from my testing:

```
// mod.ts
import * as test from "socket.io";

console.log(test);

// deno.json
{
  "imports": {
    "socket.io": "npm:socket.io"
  }
}
```

**Comment by andriejs** [comment]
I was using `--node-modules-dir` cause a vscode extension i had needed it, maybe that was the issue

**Comment by dsherret** [comment]
That also works for me.

**Comment by andriejs** [comment]
@dsherret what? I don't know what happened. It thought I was referring to a file instead of a module but okay.
