### ISSUE TITLE
Console not cleared properly

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/deno#19668]
This is a pretty weird bug. Noticed that whilst working on fresh that sometimes the background color style spans the full width of the terminal instead of just the text width. It seems like sometimes the console is not cleared properly or maybe the reset ansi codes are not sent. Running the `clear` binary seems to resolve the issue monumentally, until it pops up again.

## Steps to reproduce

1. Create a file `foo.js` with these contents:
  ```js
  import * as colors from "https://deno.land/std@0.192.0/fmt/colors.ts";
  console.log(
    colors.bgRgb8(colors.black(colors.bold("\n 🍋 Fresh ready ")), 121)
  );
  ```
2. Run `deno run foo.js` repeatedly until the console glitches out

Video of the issue:

https://github.com/denoland/deno/assets/1062408/340f4d9f-76da-44de-969f-f9e3e342c446

**Comment by sigmaSd** [comment]
I think you should close this issue and open it against deno_std

Its either how ansi works, or there is a subtlety in the reset sequence that can be improved (though I inspected the generated ansi and not much jumps to me), also it seems to trigger only when there is new line inside the string

minimal code to reproduce
```js
import * as colors from "https://deno.land/std@0.192.0/fmt/colors.ts";
console.log(
  colors.bgRgb8("a\n", 121), // the newline is required to trigger the bug
);
```

and you can reproduce the same in rust
```rs
struct Code {
    open: String,
    close: String,
}

fn create_code(open: &[u8], close: u8) -> Code {
    let open_sequence = format!(
        "\x1b[{}m",
        open.iter()
            .map(|&n| n.to_string())
            .collect::<Vec<String>>()
            .join(";")
    );
    let close_sequence = format!("\x1b[{}m", close);

    Code {
        open: open_sequence,
        close: close_sequence,
    }
}

fn clamp_and_truncate(value: u8) -> u8 {
    value.min(255)
}

fn run(str: &str, code: Code) -> String {
    format!("{}{}{}", code.open, str, code.close)
}

fn bg_rgb8(str: &str, color: u8) -> String {
    let open_code = create_code(&[48, 5, clamp_and_truncate(color)], 49);
    run(str, open_code)
}

fn main() {
    let str = "Hello, world!\n";
    let color = 121;

    let result = bg_rgb8(str, color);
    println!("{}", result);
}
```

Note: you can use this to help debugging
```fish
while true
 deno run a.js | tee -a log
end
```

**Comment by marvinhagemeister** [comment]
@sigmaSd this is super interesting, thanks for sharing! It didn't occur to me that this was caused by the newline being in the same string. Can confirm your findings that this is not a deno issue and can be reproduced with your snippet.
