### ISSUE TITLE
bug(cli,repl): private class members available outside of their parent class

### ISSUE THREAD

**Issue by nberlette** [denoland/deno#19662]
Is this behavior intentional? I've just discovered that private class members (with the `#` prefix), both static and instance-level, are available **_outside_** of the class that they were defined in.

The only plausible explanation I can think of is this behavior is purposely allowed for the purpose of inspecting / debugging classes? I haven't had the time to delve into it any further, but here's a simple screenshot to show the behavior I'm talking about:

<img width="825" alt="Screenshot 2023-06-29 at 3 34 07 PM" src="https://github.com/denoland/deno/assets/11234104/f2b6a47c-26f4-428f-a2ce-e0bde18ae8d2">

Maybe I'm crazy, but this seems a bit cocerning to me. If this _is_ indeed intentional behavior, please disregard this issue. Also, let me know if that is the case so I can close it out. 

Thanks,
Nick

**Comment by sigmaSd** [comment]
I'm gonna guess its because code in the repl, is like running inside a class, `this` seems to be set to `globalThis`

you can `console.log(this)` in the repl and see its *not* undefined 

I doubt that this is easy to workaround, also I think the motivation is not strong in my opinion (its just the repl)

**Comment by 0f-0b** [comment]
[This feature was introduced in V8 11.1](https://chromiumdash.appspot.com/commit/4d0d31f41b8b4ff35ccbb1d0b5a1f4b51e270d8f).

**Comment by bartlomieju** [comment]
This is expected behavior coming from V8 "repl mode" as pointed by 0f-0b.
