### ISSUE TITLE
deno check fails with npm: import: Invalid "exports" target; target must start with "./"

### ISSUE THREAD

**Issue by not-my-profile** [denoland/deno#19666]
```ts
import renderMathEl from 'npm:katex@0.16.7/contrib/auto-render';
```

When checked with `deno check` I get the following error message:

> error: Uncaught Error: Error resolving package config for 'npm:katex@0.16.7/contrib/auto-render': [ERR_INVALID_PACKAGE_TARGET] Invalid "exports" target {"require":"./dist/contrib/auto-render.js","import":"./dist/contrib/auto-render.mjs"} defined for './contrib/auto-render' in the package config /home/martin/.cache/deno/npm/registry.npmjs.org/katex/0.16.7/package.json imported from file:///home/martin/.cache/deno/npm/registry.npmjs.org/katex/0.16.7/; target must start with "./"
>    at <anonymous> (ext:deno_tsc/99_main_compiler.js:600:28)

(using the latest deno 1.34.3)

**Comment by tv42** [comment]
This also triggers with `react-dom`:

```console
$ echo 'import ReactDOMServer from "npm:react-dom@18.2.0/server";' >foo.ts
$ deno check ./foo.ts
Check file:///home/tv/tmp/z/foo.ts
error: Uncaught Error: Error resolving package config for 'npm:react-dom@18.2.0/server': [ERR_INVALID_PACKAGE_TARGET] Invalid "exports" target {"deno":"./server.browser.js","worker":"./server.browser.js","browser":"./server.browser.js","default":"./server.node.js"} defined for './server' in the package config /home/tv/.cache/deno/npm/registry.npmjs.org/react-dom/18.2.0/package.json imported from file:///home/tv/.cache/deno/npm/registry.npmjs.org/react-dom/18.2.0/; target must start with "./"
    at <anonymous> (ext:deno_tsc/99_main_compiler.js:600:28)
```

**Comment by bartlomieju** [comment]
I just tried it on Deno v2.1.2 and it works fine 👍 gonna close this one.
