### ISSUE TITLE
missing alpnProtocols

### ISSUE THREAD

**Issue by rwillsonAxiom** [denoland/deno#19685]
Is this missing `alpnProtocols`?

https://github.com/denoland/deno/blob/0f4051a37ad23377091043206e64126003caa480/ext/net/lib.deno_net.d.ts#L143-L164

I'll go through my thought process of how I came to think this is an issue that belongs here, since I'm not sure. I've only spent a few minutes being confused at this point.

I wanted to add HTTP2 support to a deno web server. The manual tells me to use `Deno.listenTls` with `alpnProtocols`. I go to try this in visual studio and am told 

> Argument of type '{ port: number; key: string; cert: string; alpnProtocols: string[]; }' is not assignable to parameter of type 'ListenTlsOptions'.
>  Object literal may only specify known properties, and 'alpnProtocols' does not exist in type 'ListenTlsOptions'.deno-ts(2345)

I quickly checked the type information found in `lib.deno.net.d.ts` and I don't find `alpnProtocols`. I did some googling and found no results related to this, then I come to this repo. I found this file that looks like mine does and also doesn't have the right type, so I'm opening this issue.

**Comment by rwillsonAxiom** [comment]
With a little more time spent digging into the history I have discovered that `alpnProtocols` is actually unstable. It's not clear enough in the manual nor Runtime API documentation, but I'm not going to bother making that into an issue. Hopefully this existing will help another poor soul skip the confusion I've just had.

**Comment by bartlomieju** [comment]
I've opened #19704 to stabilize the API
