### ISSUE TITLE
Deno's HTTP server doesn't use "best compression option" (Brotli) for some browsers

### ISSUE THREAD

**Issue by marc-barry** [denoland/deno#19690]
We have opted to implement a proxy with Deno and Oak to replace some legacy NGINX configurations. We have observed that depending on the order of the `Accept-Encoding` header, Deno doesn't always select the most optimal `Content-Encoding` option. There is no way within the server itself to set a preference.

The default `Accept-Encoding` headers for Google Chrome are `Accept-Encoding: gzip, deflate, br` and when requests are made to the Deno HTTP server for compressible content it will prefer `gzip`. It has been shown and through our own evidence that Brotli can result in significantly smaller content sizes and thus when present with the above option we'd prefer to have the `Content-Encoding` be `br`. The `Accept-Encoding` by browsers isn't easily changeable by users and thus we need to find a way to select the most optimal for our use case on the server side. It is our understanding that Firefox, Brave and quite possibly a few others use the same value of `Accept-Encoding: gzip, deflate, br` for their request headers.

When using https://chrome.google.com/webstore/detail/modheader-modify-http-hea/idgpnmonknjnojddfkpgkljpfnnfcklj on Google Chrome and setting the request header to `Accept-Encoding: br, gzip, deflate` then Deno responds with `Content-Encoding: br`. This leads me to believe it is purely an ordering situation when selecting the compression for the content.

Ideally, we'd be able to set `br` as the preferred, if present in `Accept-Encoding` header. I did attempt to modify the header on the request to see if I could dynamically do that in the handler but the request headers are immutable.

Is it possible to tell Deno to prefer `br` over `gzip` when both are present regardless of order? I cannot seem to find a way to do so. Below is the version of Deno I'm using with a minimal code example to illustrate what I'm reporting.

```console
deno --version
deno 1.34.3 (release, aarch64-apple-darwin)
v8 11.5.150.2
typescript 5.0.4
```

```typescript
import { serve } from "https://deno.land/std@0.192.0/http/server.ts";

const port = 3000;

const handler = (request: Request): Response => {
  const body = `User-Agent: ${
    request.headers.get("user-agent") ?? "Unknown"
  }\nAccept-Encoding: ${request.headers.get("accept-encoding") ?? "Unknown"}`;

  return new Response(body, { status: 200 });
};

console.log(`HTTP webserver running. Access it at: http://localhost:3000/`);
await serve(handler, { port });
```

```console
deno run --allow-net webserver.ts
HTTP webserver running. Access it at: http://localhost:3000/
Listening on http://localhost:3000/
```

Then simply test with different browsers for output which will look like the following:
```console
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Accept-Encoding: br, gzip, deflate
```

In Google Chrome you can leverage the **Network** tab in the **Developer Tools** to see the response headers and confirm the `Content-Encoding` values.

**Comment by marc-barry** [comment]
Based on my limited understanding of the code the line https://github.com/denoland/deno/blob/de630b9b78ad09d3092e6fff4629d8503693bdff/ext/http/http_next.rs#L450 should return `Compression::Brotli`. The `Accept-Encoding` values match `"gzip, deflate, br"` exactly. I'm not strong in Rust nor in the control flow for Deno and so I'm not 100% sure where the compression gets changed to `gzip` along the way.

**Comment by mmastrac** [comment]
Thanks for the excellent report. I was able to see this locally.

Note that I suspect this might be a bug in `deno_std` which IIRC might be based on our older and less-reliable `serveHttp` API. If I port the above testcase to use raw `Deno.serve`, it works as expected:

```
Deno.serve(
  async (request) => {
    const file = await Deno.open("/tmp/out.txt", { read: true });
    const body = `User-Agent: ${
      request.headers.get("user-agent") ?? "Unknown"
    }\nAccept-Encoding: ${
      request.headers.get("accept-encoding") ??
        "Unknown"
    }`;

    return new Response(body, { status: 200 });
  },
  { port: 8000 },
);
```

Would you mind re-testing? If it works for you, I'd suggest migrating from the `deno_std` server to `Deno.serve` and we can move this issue there.

**Comment by marc-barry** [comment]
I made the change in https://github.com/marc-barry/deno-spa-proxy/pull/3 and confirmed it works with the `Deno.serve` switch.

**Comment by marc-barry** [comment]
I created https://github.com/denoland/deno_std/issues/3503 and am closing this as the issue is within the `deno_std` modules.
