### ISSUE TITLE
`performance.timeOrigin` is undefined while evaluating `npm:` module

### ISSUE THREAD

**Issue by alexlafroscia** [denoland/deno#19708]
I have been playing around with the [Effect](https://effect.website) library in Deno lately, and [a recent update on their end](https://github.com/Effect-TS/io/pull/480) started using the `performance.timeOrigin` API. Since that update, the packages don't seem to work in Deno!

<img width="1070" alt="CleanShot 2023-07-04 at 00 37 31@2x" src="https://github.com/denoland/deno/assets/1645881/ef6516ba-8c45-4bd9-97ec-bac0610e12d5">

As far as I can tell, while the code within the package is being executed, the global `Performance` instance's `.timeOrigin` property is `undefined`. I was able to log that by opening up Deno's cached version of the package and adding a `console.log` before the property is accessed, which resulted in this being printed

<img width="455" alt="CleanShot 2023-07-04 at 00 36 31@2x" src="https://github.com/denoland/deno/assets/1645881/a3187a3b-f86f-426c-882a-e6150b01d0c0">

What's especially strange is that logging the value at the beginning of my tests, if I exclude their code, prints a real value for `performance.timeOrigin`; it's just not available while the dependency is being evaluated.

To demonstrate the bug, I created a repository that can be found here:

https://github.com/alexlafroscia/__deno-bug-performanace-timeOrigin-npm-modules

To see the bug, clone it and run `deno test`; you'll see the same error that I screen-shotted above.

**Comment by lucacasonato** [comment]
@bartlomieju Looks like we are only setting the time origin on the web standard "performance", but not on the `npm:` version
