### ISSUE TITLE
What does "$" (dollar sign) mean in import?

### ISSUE THREAD

**Issue by wtchen** [denoland/deno#19709]
I'm a Deno newb and have been enjoying using Deno and its ecosystem. I just have a question I'm curious about as I'm learning.

Consider, `import "$std/dotenv/load.ts";`

From my Deno WebStorm extension, I see it's referencing files in my local Deno installation (some kind of cache, perhaps?). 

I'm wondering what this `$` convention means more specifically. A cursory Google search and look-over of the documentation doesn't seem to bring anything up for me.

**Comment by Seally** [comment]
It doesn't mean anything in Deno in and of itself.

I'm assuming you saw this while using Fresh, which uses `$std/` to map to the Deno standard library's URL. This is done by using import maps, and Fresh uses `deno.json` as the import map file.

**Comment by tjcrowder** [comment]
@wtchen - 

As @Seally pointed out above, assuming you're using Fresh (or something similar), if you look in `deno.json`/`deno.jsonc` you'll see something like:

```jsonc
    "imports": {
        // ...
        "$std/": "https://deno.land/std@0.192.0/",
        // ...
    },
```



That's an [import map](https://deno.land/manual@v1.35.0/basics/import_maps#import-maps) (see also [the spec](https://html.spec.whatwg.org/multipage/webappapis.html#import-maps)). Deno sees the `$std/` entry in that map and uses it to expand `import "$std/dotenv/load.ts";` into:

```ts
import "https://deno.land/std@0.192.0/dotenv/load.ts";
```

The import map may not necessarily be directly in `deno.json`/`deno.jsonc` like that, it may be a separate file referenced via an `"importMap"` top-level configuration entry in the `deno.json`/`deno.jsonc` file instead.

> I see it's referencing files in my local Deno installation (some kind of cache, perhaps?)

Yes, Deno caches remote modules locally the first time you use them (or when you explicitly tell it to via `deno cache`). That's not related to the import map, it's just how Deno works. (If you want to see where Deno's cache is on your system, you can use [`deno info`](https://deno.land/manual@v1.35.0/tools/dependency_inspector#cache-location).)
