### ISSUE TITLE
Leaking async ops. npm:winston

### ISSUE THREAD

**Issue by Mr-Arthur-White** [denoland/deno#19713]
I'm trying to use winston with datadog transport as a logger for my application and during tests I'm facing with this error

![image](https://github.com/denoland/deno/assets/33233554/7fd7acca-c15f-41ab-b584-67583d027980)
![image](https://github.com/denoland/deno/assets/33233554/671e886c-07e8-4b61-b298-904996562800)
![image](https://github.com/denoland/deno/assets/33233554/3b381d16-6431-4578-a72a-f37a8da523b3)

**Comment by bartlomieju** [comment]
@Mr-Arthur-White is this still a problem in latest Deno?

**Comment by Mr-Arthur-White** [comment]
Can't help with that anymore, unfortunately. It was one of the many reasons to stop using deno.
I may try deno 2.0 in the future.
