### ISSUE TITLE
deno test --watch does not clear screen

### ISSUE THREAD

**Issue by andykais** [denoland/deno#19725]
I noticed that running `deno run --watch <script>` will clear the terminal when files change, while `deno test --watch <script>` will not clear the screen on file changes. `deno test --help` still shows the `--no-clear-screen` option, so it appears that it is supposed to clear the screen by default. Poking around at a few other commands, they also seem to be missing the cleared screen by default (`deno lint --watch` for instance)

**Comment by andykais** [comment]
another inconsistency found between `deno run --watch` and `deno test --watch`. Under the run command I can pass in additional files to watch (`deno run --watch ./src/worker.ts <script>`). Compare that to `deno test --watch ./src/worker.ts <script>` and deno will assume that these are other test entrypoints.

**Comment by totallynotmark6** [comment]
After doing some testing, I've found that, sometime between `1.34.2` and `1.34.3` was when the `--no-clear-screen`'s functionality was inverted. (Meaning that running `deno test --watch --no-clear-screen` in 1.34.3 and above will clear the screen.)

**Comment by bartlomieju** [comment]
I believe it might have been caused by https://github.com/denoland/deno/pull/19516

**Comment by andykais** [comment]
@bartlomieju fwiw this fixes my issue but the pr that closes this appears to only affect `deno test` commands. I know at least `deno lint` also had this inconsistency (noted in the original issue)

**Comment by bartlomieju** [comment]
Thanks for pointing this out @andykais

**Comment by bartlomieju** [comment]
@liruifengv any chance you can look into fixing other subcommands as well?

**Comment by liruifengv** [comment]
I tested `deno lint` and had no problems. My deno version is 1.35.1. Can you describe it more? @andykais

**Comment by andykais** [comment]
hmm. I must have been mistaken. Thanks for point that out @liruifengv. The screen seems to be clearing correctly on `deno lint`. I am closing this issue
