### ISSUE TITLE
op_node_create_hash returning potentially valid ResourceId is treated as error

### ISSUE THREAD

**Issue by sido378** [denoland/deno#19722]
## Description

Some `op`s return `0` to signal an error. In success cases, these ops return a `ResourceId`, which incidentally could also have the value `0` if it is the first resource being added. Therefore when calling these ops, it is not possible to differentiate whether the returned `0` represents a valid ResourceId, or an error.

E.g.:
For [`op_node_create_hash`](https://github.com/denoland/deno/blob/11dd5a0ae73b4d3612de6422893a25232f930b84/ext/node/ops/crypto/mod.rs#L86), the `Hash` constructor also checks against the return value `0` to throw an error (See the [`Hash` constructor](https://github.com/denoland/deno/blob/11dd5a0ae73b4d3612de6422893a25232f930b84/ext/node/polyfills/internal/crypto/hash.ts#LL78C7-L78C7))

Other instances of ops returning `0` to signal an error are `op_node_create_cipheriv` and `op_node_create_decipheriv` - but their return value is not checked for the value `0`.

## Suggested Fix

To allow proper handling of error and success cases, the mentioned operations (`op_node_create_hash`, `op_node_create_cipheriv` and `op_node_create_decipheriv`) should be changed from 
`-> u32` to `-> Result<ResourceId, AnyError`.

```
pub fn op_node_create_hash(state: &mut OpState, algorithm: &str) -> Result<ResourceId, AnyError>

pub fn op_node_create_decipheriv(state: &mut OpState, algorithm: &str, key: &[u8], iv: &[u8]) -> Result<ResourceId, AnyError>

pub fn op_node_create_cipheriv(state: &mut OpState, algorithm: &str, key: &[u8], iv: &[u8]) -> Result<ResourceId, AnyError>
```

If the suggested fix sounds reasonable, I'm happy to submit a PR changing the mentioned ops and their call sites accordingly

**Comment by bartlomieju** [comment]
Appears these ops now correctly return an error type in Rust. Thanks!
