### ISSUE TITLE
npm:firebase-admin printing cryptic error

### ISSUE THREAD

**Issue by zzaba** [denoland/deno#19720]
**MRE**

```typescript
import admin, { ServiceAccount } from "npm:firebase-admin";
import serviceKey from "./service-key.json" assert { type: "json" };

admin.initializeApp({
  credential: admin.credential.cert(serviceKey as ServiceAccount),
  databaseURL: "[REDACTED]",
});

const db = admin.database()

db.ref("path").get()
```

**Output**

```
[2023-07-05T05:42:54.558Z]  @firebase/database: FIREBASE WARNING: {}
...
```

¯\\\_(ツ)\_/¯

**Comment by gustavomaltez** [comment]
I'm having the same issue. Is there any working solution to use Firebase Admin SDK on Deno?

**Comment by bartlomieju** [comment]
@zzaba @gustavomaltez have you folks tried it recently? We made great strides in improving `node:http2` and `@grpc/grpc-js` support in the recent releases and I think this issue might be no more now.

**Comment by bartlomieju** [comment]
I'm gonna close this one for now due to inactivity, please reopen if the problem persists.
