### ISSUE TITLE
Import module is sometimes broken 

### ISSUE THREAD

**Issue by rickyraz** [denoland/deno#19731]
**the tools that i use** 

Version: 1.79.2 (user setup)
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
Date: 2023-06-14T08:57:04.379Z
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621

deno 1.35.0 (release, x86_64-pc-windows-msvc)
v8 11.6.189.7
typescript 5.1.6

**This problem is annoying**

This error can sometimes be resolved and sometimes it appears again, I assume there may be a bug in the LSP

![Untitled](https://github.com/denoland/deno/assets/91396978/50af5e40-f5d1-47a1-9ac6-af7f21aa8087)

![Untitled2](https://github.com/denoland/deno/assets/91396978/6052ef17-c4a0-4dda-ad98-89c09c1827bf)

**Comment by bartlomieju** [comment]
Does it go away if you restart the language server in VSCode?

**Comment by rickyraz** [comment]
i have reinstalled LSP, it will fix it but it will show up again

**Comment by bartlomieju** [comment]
I really can't reproduce it anymore. Please open a new issue it happens again.
