### ISSUE TITLE
how to exclude file from watching

### ISSUE THREAD

**Issue by hemedani** [denoland/deno#19734]
how can I exclude a file or directory from watching with the `--watch` command?
is there any way to add a command to `deno.json`?

**Comment by hemedani** [comment]
I just want to exclude some files in local dependencies.
for example, I have auto-generated declaration files with deno on some applications. and whenever the application is restarted these files are automatically created, so because of that the `watcher` falls into the infinite loop.
- application started.
- declaration files generated.
- watcher detects changes is the declaration folder and restarts the application.
- after restart is finished, declaration files are generated.
- and again watcher detects changes in the declaration folder and restarts the application. 
- ...

**Comment by sjc5** [comment]
Same issue here, an ignore option would be lovely

**Comment by bartlomieju** [comment]
@dsherret thoughts on adding `--watch-exclude` or `--watch-ignore` flag? Seems like a valid use case here.

**Comment by dsherret** [comment]
Yeah, seems reasonable.

**Comment by marvinhagemeister** [comment]
+1 on adding something like that. I ran into this with Fresh the other day too.

**Comment by RioChndr** [comment]
Hello, I'm new here. Nice to meet you all. I want to contribute and help community from this issue. I'll see what I can do from here. ✋

**Comment by bartlomieju** [comment]
Hey @RioChndr sounds good! Let me know if you need any pointers

**Comment by RioChndr** [comment]
Thank you. I will add flag with name `--watch-ignore`.

**Comment by lczerniawski** [comment]
Hello, may I take this one? Some time passed and there was no movement on that topic and I would love to pick it up :)

**Comment by bartlomieju** [comment]
This is now possible with `--watch-exclude` flag available in Deno v1.42.
