### ISSUE TITLE
`deno info` should respect import map

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/deno#19742]
When running `deno info` it doesn't seem to respect the paths specified in the import map.

- `deno info preact/debug` -> doesn't work
- `deno info https://esm.sh/preact@10.15.1/debug` -> works

## Steps to reproduce

1. Add `deno.json` with the following content:
  ```json
  {
    "imports": {
      "preact": "https://esm.sh/preact@10.15.1",
      "preact/": "https://esm.sh/preact@10.15.1/"
    }
  }
  ```
2. Create a `main.tsx` file with the following content:
  ```jsx
  import { render } from "preact";
  console.log(render);
  ```
3. Run `deno run main.tsx` to force deno to download dependencies
4. Run `deno info preact/debug` -> module not found

**Comment by vedant-pandey** [comment]
Hi @marvinhagemeister can I take this issue?

**Comment by bartlomieju** [comment]
@vedant-pandey sure, feel free to ping me or David for pointers if you get stuck.
