### ISSUE TITLE
`deno vendor` support for npm: specifiers

### ISSUE THREAD

**Issue by not-my-profile** [denoland/deno#19740]
`deno vendor` currently doesn't support npm: specifiers:

```
$ deno vendor npm:example
Vendored 0 modules into vendor/ directory.
```

**Comment by nayeemrmn** [comment]
I think `--node-modules-dir` is the proper way of vendoring `npm:` imports, and it seems to already work.

**Comment by StarLederer** [comment]
I believe it does now, should this issue be closed?

**Comment by adamgreg** [comment]
I think there is a problem if the project's import map uses both `npm:` and `https:` specifiers.

`deno vendor` creates an import map for the https imports only. If you later try to use the vendored dependencies with `deno run --import-map=vendor/import_map.json ...` any imports that resolve to `npm:` specifiers in the original import map are not found, and the imports fail. Having those npm imports "vendored" in a `node_modules` dir does not seem to help.

I've been experimenting with `deno run --vendor` as an alternative to `deno vendor`, but running into other difficulties, which I'll raise a separate issue about.

**Comment by marvinhagemeister** [comment]
Closing as the `deno vendor` command was removed in Deno 2. Instead add this to your `deno.json`:

```json
{
  "vendor": true
}
```
