### ISSUE TITLE
`HeadersInit` cannot be `Headers` object

### ISSUE THREAD

**Issue by kylewillmon** [denoland/deno#19746]
The `HeadersInit` type was changed in d632cce1 and the `Headers` interface was removed from the type union. This can be see in the docs by comparing `HeadersInit` from [1.35.0](https://deno.land/api@v1.35.0?s=HeadersInit) against [1.34.3](https://deno.land/api@v1.34.3?s=HeadersInit).

This causes existing code to fail type checking. For example, this code:
```ts
function makeHeaders(h?: HeadersInit): Headers {
  h = new Headers(h);
  h.set('Content-Type', 'application/json');
  return h;
}
console.log(makeHeaders({}));
```

Running `deno check` on the above code causes this error:
```
error: TS2339 [ERROR]: Property 'set' does not exist on type 'Iterable<string[]>'.
```

Using deno v1.34.3, the code type checks successfully

**Comment by 0f-0b** [comment]
The purpose of this change is to support using any iterable object yielding name-value pairs as a `HeadersInit`, which might become a more significant use case as [V8's implementation of iterator helpers](https://crbug.com/v8/13558) is just around the corner. I thought it would not break existing code because `Headers` is a subtype of `Iterable<string[]>`… Should the change be reverted?

**Comment by kylewillmon** [comment]
It makes sense that the `HeadersInit` type should track the types accepted by the `Headers` constructor. So if that constructor is going to accept any `Iterable<string[]>`, then this change makes sense.

Looking at this further, I may actually open an issue on TypeScript itself. It feels like they are missing an opportunity for narrowing here...

```ts
// Immediately narrows to Headers because of assignment
const x: Headers | Record<string, string> = new Headers();
x.append("Foo", "Bar");

// This assignment does not narrow to Headers
const y: Iterable<string[]> = new Headers();

// This would error
//y.append("Foo", "Bar");

// But this still narrows to Headers...
if(y instanceof Headers) {
  y.append("Foo", "Bar");
}
```

**Comment by kylewillmon** [comment]
This behavior of TypeScript is explained [in this comment](https://github.com/microsoft/TypeScript/issues/46489#issuecomment-966743552). Specifically:

> only union types narrow on assignment

Since `Iterable<string[]>` is not a union, assignment narrowing does not occur.

It's a bit of a bummer to lose assignment narrowing on `HeadersInit`, but this is a design limitation on TypeScript and not an issue with deno.

Closing this issue since there is nothing that deno can/should do here.
