### ISSUE TITLE
Uncaught Error: Deno.serve no longer returns a promise.

### ISSUE THREAD

**Issue by natea11** [denoland/deno#19775]
I am trying to rewrite the old websockify-js into Deno.  I have it working in node, but want to use Deno for production.  When I run the code I get an error.  I will paste all the information below.  Please let me know if you need anything else.  Thank you for your help.

My code:
`#!/usr/bin/env node

// A WebSocket to TCP socket proxy
// Copyright 2012 Joel Martin
// Licensed under LGPL version 3 (see docs/LICENSE.LGPL-3)

// Trying to update to Typescript and Deno

  const argv = Deno.args;
  // Won't work with node
  import * as net from "https://deno.land/std@0.173.0/node/net.ts";
  //const net = require('node:net');
  import { createServer } from "https://deno.land/std@0.173.0/node/http.ts";
  //const http = require('node:http');
  //const https = require('node:https');
  /*let url = require('url'),
    path = require('path'),
    fs = require('fs'),
    mime = require('mime-types'),*/

    /*Buffer = require('buffer').Buffer,*/
    //let WebSocketServer = require('ws').Server,
    import { WebSocketServer } from "https://deno.land/x/websocket@v0.1.4/mod.ts";

    let webServer, wsServer,
    source_host, source_port, target_host, target_port;
    let web_path = null;

// Handle new WebSocket client
function new_client (client, req) {
    const clientAddr = client._socket.remoteAddress;
    const start_time = new Date().getTime();

    console.log(`New client ${ req ? req.url : client.upgradeReq.url }`);
    const log = function (msg) {
        console.log(' ' + clientAddr + ': '+ msg);
    };
    log('WebSocket connection');
    log('Version ' + client.protocolVersion + ', subprotocol: ' + client.protocol);

    // const target = net.createConnection(target_port, target_host, function() {
    const target = net.createConnection(target_port, target_host, () => {
      // 'connect' listener.
      log('connected to target');
      //target.write('world!\r\n');
    });
    target.on('data', (data) => {
        //log("sending message: " + data);

        try {
            client.send(data);
        } catch(e) {
            log("Client closed, cleaning up target");
            target.end();
        }
    });
    target.on('end', () => {
        log('target disconnected');
        client.close();
    });
    target.on('error', () => {
        log('target connection error');
        target.end();
        client.close();
    });

    client.on('message', function(msg) {
        //log('got message: ' + msg);
        target.write(msg);
    });
    client.on('close', function(code, reason) {
        log('WebSocket client disconnected: ' + code + ' [' + reason + ']');
        target.end();
    });
    client.on('error', function(a) {
        log('WebSocket client error: ' + a);
        target.end();
    });
};

function decodeBuffer(buf) {
  let returnString = '';
  for (let i = 0; i < buf.length; i++) {
    if (buf[i] >= 48 && buf[i] <= 90) {
      returnString += String.fromCharCode(buf[i]);
    } else if (buf[i] === 95) {
      returnString += String.fromCharCode(buf[i]);
    } else if (buf[i] >= 97 && buf[i] <= 122) {
      returnString += String.fromCharCode(buf[i]);
    } else {
      let charToConvert = buf[i].toString(16);
      if (charToConvert.length === 0) {
        returnString += '\\x00';
      } else if (charToConvert.length === 1) {
        returnString += '\\x0' + charToConvert;
      } else {
        returnString += '\\x' + charToConvert;
      }
    }
  }
  return returnString;
}

// Send an HTTP error response
function http_error (response, code, msg) {
    response.writeHead(code, {"Content-Type": "text/plain"});
    response.write(msg + "\n");
    response.end();
    return;
}

// Process an HTTP static file request
function http_request  (request, response) {
//    console.log("pathname: " + url.parse(req.url).pathname);
//    res.writeHead(200, {'Content-Type': 'text/plain'});
//    res.end('okay');

    /*if (! argv.web) {
      console.log("No argv.web");
      return http_error(response, 403, "403 Permission Denied");
    }
    else {
      console.log(`argv.web = ${ argv.web }`);
    }

    const uri = url.parse(request.url).pathname;
    let filename = path.join(argv.web, uri);*/

    /*fs.exists(filename, function(exists) {
        if(!exists) {
            return http_error(response, 404, "404 Not Found");
        }

        if (fs.statSync(filename).isDirectory()) {
            filename += '/index.html';
        }

        fs.readFile(filename, "binary", function(err, file) {
            if(err) {
                return http_error(response, 500, err);
            }

            let headers = {};
            const contentType = mime.contentType(path.extname(filename));
            if (contentType !== false) {
              headers['Content-Type'] = contentType;
            }

            response.writeHead(200, headers);
            response.write(file, "binary");
            response.end();
        });
    });*/
};

// parse source and target arguments into parts
try {
    const source_arg = argv[0].toString();
    const target_arg = argv[1].toString();

    let idx;
    idx = source_arg.indexOf(":");
    if (idx >= 0) {
        source_host = source_arg.slice(0, idx);
        source_port = parseInt(source_arg.slice(idx+1), 10);
    } else {
        source_host = "";
        source_port = parseInt(source_arg, 10);
    }

    idx = target_arg.indexOf(":");
    if (idx < 0) {
        throw("target must be host:port");
    }
    target_host = target_arg.slice(0, idx);
    target_port = parseInt(target_arg.slice(idx+1), 10);

    if (isNaN(source_port) || isNaN(target_port)) {
        throw("illegal port");
    }
} catch(e) {
    console.error("websockify.js [--web web_dir] [--cert cert.pem [--key key.pem]] [--record dir] [source_addr:]source_port target_addr:target_port");
}

console.log("WebSocket settings: ");
console.log("    - proxying from " + source_host + ":" + source_port +
            " to " + target_host + ":" + target_port);

/*if (argv.cert) {
    argv.key = argv.key || argv.cert;
    const cert = fs.readFileSync(argv.cert),
        key = fs.readFileSync(argv.key);
    console.log("    - Running in encrypted HTTPS (wss://) mode using: " + argv.cert + ", " + argv.key);
    webServer = https.createServer({cert: cert, key: key}, http_request);
} else {*/
    console.log("    - Running in unencrypted HTTP (ws://) mode");
    //webServer = http.createServer(); //http_request
    webServer = createServer();
//}
webServer.listen(source_port, function() {
    wsServer = new WebSocketServer({server: webServer});
    wsServer.on('connection', new_client);
});
`
The command I'm using to run:
deno run --allow-net .\websockify.ts 127.0.0.1:6080 127.0.0.1:8081

Deno version:
deno 1.35.0 (release, x86_64-pc-windows-msvc)
v8 11.6.189.7
typescript 5.1.6

The output and error:
WebSocket settings:
    - proxying from 127.0.0.1:6080 to 127.0.0.1:8081
    - Running in unencrypted HTTP (ws://) mode
error: Uncaught Error: Deno.serve no longer returns a promise. await server.finished instead of server.
    ).then(() => this.#servePromise!.resolve());
      ^
    at Object.then (ext:deno_http/00_serve.js:741:13)
    at ServerImpl.#serve (https://deno.land/std@0.173.0/node/http.ts:654:7)
    at https://deno.land/std@0.173.0/node/http.ts:561:33
    at Array.processTicksAndRejections (https://deno.land/std@0.173.0/node/_next_tick.ts:33:11)
    at eventLoopTick (ext:core/01_core.js:180:29)

**Comment by bartlomieju** [comment]
You are using a very old version of `std/node` that used an unstable API that was changed in v1.34 (https://deno.com/blog/v1.34#denoserve).

Good thing is, you can now directly importing built-in Node.js modules like so:
```
import * as net from "node:net";
import { createServer } from "node:http";
```

That should be enough to fix the error on your side.

**Comment by natea11** [comment]
Yes that worked.  I will close this.  Thank you.
