### ISSUE TITLE
npm compat: bug running polars

### ISSUE THREAD

**Issue by sigmaSd** [denoland/deno#19785]
```ts
import pl from 'npm:nodejs-polars';
let df = pl.DataFrame({
  integer: [1, 2, 3, 4, 5],
  date: [
    new Date(2022, 1, 1, 0, 0),
    new Date(2022, 1, 2, 0, 0),
    new Date(2022, 1, 3, 0, 0),
    new Date(2022, 1, 4, 0, 0),
    new Date(2022, 1, 5, 0, 0),
  ],
  float: [4.0, 5.0, 6.0, 7.0, 8.0],
});
console.log(df) // error here
```
error
```
Error: not found: constructor
    at Object.getColumn (file:///home/mrcool/.cache/deno/npm/registry.npmjs.org/nodejs-polars/0.8.0/bin/dataframe.js:172:46)
    at Object.getOwnPropertyDescriptor (file:///home/mrcool/.cache/deno/npm/registry.npmjs.org/nodejs-polars/0.8.0/bin/dataframe.js:617:31)
    at getOwnPropertyDescriptor (<anonymous>)
    at getConstructorName (ext:deno_console/01_console.js:1205:24)
    at formatRaw (ext:deno_console/01_console.js:810:23)
    at formatValue (ext:deno_console/01_console.js:721:10)
    at Object.inspectArgs (ext:deno_console/01_console.js:3114:28)
    at <anonymous>:3:55 {
  code: "GenericFailure"
}
```

linux deno 1.35.0

**Comment by sigmaSd** [comment]
The workaround is to use  `console.log(df.toString());` 

This will skip deno log machinery for objects

**Comment by rgbkrk** [comment]
Would it be worth creating a deno package that builds on top of polars in rust directly? Now that https://github.com/denoland/deno/pull/20337 is getting close, I'd love to make sure we can work with tabular data interactively.

**Comment by sigmaSd** [comment]
I personally don't see the benefit, there is a lot of work done in polar-js, and it would be a big duplication of effort for no obvious gain

The polars-js package does work on deno albeit this small issue , one can use the manpower instead to improve the quality if life of deno-polarjs relation, for example making it not use `node child process exec` somehow since its shells out to `sh` so you need to give it the permission to run it (though we already need --allow-ffi=pathToLib)

**Comment by rgbkrk** [comment]
Maybe it would be smart for us to add deno as a test target like in https://github.com/pola-rs/nodejs-polars/pull/115 with a little deno script.

**Comment by rgbkrk** [comment]
This code runs for me in 1.37.0+

Could you verify too?

**Comment by sigmaSd** [comment]
Thanks it works indeed
