### ISSUE TITLE
Deno LSP does not recognize Deno.openKv 

### ISSUE THREAD

**Issue by tristan-nsg** [denoland/deno#19801]
My error: `Property 'openKv' does not exist on type 'typeof Deno'. Did you mean 'open'? deno-ts(2551)`
I'm on Deno 1.35. The API still works, it just doesn't appear to exist according to the LSP. I have the `--unstable` flag passed to the command, and set to true for the Deno VSCode extension.

```js
{
  "deno.enable": true,
  "deno.lint": true,
  "editor.defaultFormatter": "denoland.vscode-deno",
  "deno.unstable": true
}
```

**Comment by dsherret** [comment]
See https://github.com/denoland/deno/issues/19035#issuecomment-1539076450

**Comment by tristan-nsg** [comment]
Thanks, David.
________________________________
