### ISSUE TITLE
LSP enablePaths option not working in non-VSCode editor 

### ISSUE THREAD

**Issue by sgwilym** [denoland/deno#19802]
I'm trying to add support for the `enablePaths` option to my Deno extension for Nova.

But it doesn't seem to matter how I pass the paths to the LSP upon initialisation — `src`, `./src`, `/Users/me/project/src`, `file://Users/me/project/src` — the LSP keeps working on files outside of these paths.

[Here's a gist with the initialisation RPC call](https://gist.github.com/sgwilym/02f8787b39d4b6d0e580482ef0a14802#file-initialisation_rcp-json-L194). As far as I can tell, this should work. Could some other option be messing with it?

Could this be something to do with Nova? I can see that its built-in LSP client is sending RPC calls like this for files outside of the enabled paths: 

```json
{
  "jsonrpc" : "2.0",
  "id" : 10,
  "method" : "textDocument\/hover",
  "params" : {
    "textDocument" : {
      "uri" : "file:\/\/\/Users\/gwil\/Projects\/nova-deno\/build.ts"
    },
    "position" : {
      "line" : 7,
      "character" : 12
    }
  }
}
```

And even though this file is outside the enabledPaths, the Deno LSP server will send back a result:

```json
{
  "id" : 11,
  "jsonrpc" : "2.0",
  "result" : {
    "range" : {
      "start" : {
        "line" : 8,
        "character" : 16
      },
      "end" : {
        "line" : 8,
        "character" : 20
      }
    },
    "contents" : [
      {
        "value" : "const code: string",
        "language" : "typescript"
      },
      "The bundles code as a single JavaScript module."
    ]
  }
}
```

Should it do that? Should it send back nothing?

**Comment by dsherret** [comment]
There is a test for this exact scenario here: https://github.com/denoland/deno/blob/9d5f6f67d612bcf6d5edfec3e6a442f499dab9bd/cli/tests/integration/lsp_tests.rs#L1084-L1093

Why are all the forward slashes escaped in these values? Maybe it has something to do with that?

https://gist.github.com/sgwilym/02f8787b39d4b6d0e580482ef0a14802#file-initialisation_rcp-json-L195

**Comment by sgwilym** [comment]
Yeah, I noticed that too, but as there was escaping in other parts of the initialisation options I assumed it was okay. Maybe it's not?! Which would be a pain, as the IDE's built-in client is escaping the values I pass through it whether I want that or not.

**Comment by dsherret** [comment]
It might not be an issue. I'm unsure and still looking into this.

**Comment by dsherret** [comment]
It seems like enablePaths doesn't work with absolute paths. Try providing just `./src`

**Comment by dsherret** [comment]
Oh, actually that looks to be a vscode_deno behaviour with not working with absolute paths: https://github.com/denoland/vscode_deno/blob/db25171806abe8d8807ca41f8d8237b68dd708a8/client/src/extension.ts#L105

I'm not sure what the issue here is with nova, but there is a passing test in the deno repo. Does Deno output any logs to stderr like "Unable to resolve a file path for `deno.enablePath`"?

**Comment by sgwilym** [comment]
Not that I can see. I get back a response indicating a successful initialisation. 

The form of the path doesn't seem to affect what happens. `src`, `./src`, `/User/project/src` all seem to have no effect.

**Comment by sgwilym** [comment]
Interestingly, after the introduction of 1.36 and https://github.com/denoland/deno/pull/19791 I can get this behaviour using the `exclude` option in deno.json.

But this is exclusive, rather than the inclusive `enablePaths` option. But on the other hand, this can be more easily checked into a repo. Still, I would like to be able to support `enablePaths` in my extension, maybe `exclude` working provides a clue?

**Comment by sigmaSd** [comment]
Same issue with helix, only exclude worked for me as well

**Comment by nayeemrmn** [comment]
> [Here's a gist with the initialisation RPC call](https://gist.github.com/sgwilym/02f8787b39d4b6d0e580482ef0a14802#file-initialisation_rcp-json-L194).

https://github.com/denoland/deno/blob/a74554987af17b09aeb2d113fad6998f465132d6/cli/lsp/config.rs#L702-L724

@sgwilym It might work if you don't specify `workspaceFolders`. If that's specified we appear to acquire `enablePaths()` for each folder by using the `workspace/configuration` request, and you probably haven't implemented that client capability.

But I don't think we should ignore the root workspace settings if `workspaceFolders` is there. So the above `else if` is a problem. I'll see if I can reproduce and that fixes it.

**Comment by sgwilym** [comment]
Thank you @nayeemrmn, looking forward to using this feature at last!

**Comment by nayeemrmn** [comment]
@sgwilym Can you confirm on the `--canary` version that this fix works for you?

**Comment by sigmaSd** [comment]
I can confirm this works in helix now.

**Comment by sgwilym** [comment]
@nayeemrmn Unfortunately I still seem to have the same problem. Sorry!

[Here is the initialisation request](https://gist.github.com/sgwilym/438321f70b7d308a9977dcea70f0d0ef), with many variants of `src` included in `enablePaths`. Unfortunately files outside of `src` still are processed by the LSP, and show tooltips, code actions, etc.

How the LSP is initialised is a bit out of my control, as my Deno extension uses Nova's built-in LSP client. So I may have to communicate with the devs for that editor to change how the LSP server is initialised.

**Comment by sgwilym** [comment]
My extension is responsible for providing the values of `enablePaths`, yes.

I went looking for `workspace/configuration` requests, and see these logged:

```json
{
  "jsonrpc" : "2.0",
  "id" : 8,
  "method" : "workspace\/configuration",
  "params" : {
    "items" : [
      {
        "section" : "deno",
        "scopeUri" : "file:\/\/\/Users\/gwil\/Projects\/nova-deno\/build.ts"
      }
    ]
  }
}
```

So it seems like Nova is sending workspace/configuration requests for each file that's open, and this is overriding the `enablePaths` options I'm providing to Deno's LSP server?

**Comment by nayeemrmn** [comment]
> So it seems like Nova is sending workspace/configuration requests for each file that's open, and this is overriding the `enablePaths` options I'm providing to Deno's LSP server?

Correct. You can disable that by turning off this capability, i.e. switching https://gist.github.com/sgwilym/02f8787b39d4b6d0e580482ef0a14802#file-initialisation_rcp-json-L20 to false.
