### ISSUE TITLE
Add chocolatey support

### ISSUE THREAD

**Issue by zekth** [denoland/deno#1981]
As MacOs has Homebrew, it would be a good idea to add support for the window package manager [Chocolatey](https://chocolatey.org/)

We can just ship the compiled `.exe` file from the CI directly to chocolatey.

Ref: [Create Package](https://chocolatey.org/docs/create-packages)

**Comment by ry** [comment]
We are already in Scoop - is that sufficient or do people want chocolatey too? 

https://github.com/denoland/deno_install/tree/9a086b54a56553b98d15748750d6794e1f079477#install-via-package-manager

**Comment by zekth** [comment]
As Deno is already supported in Scoop and at the current latest version, i think the support of Chocolatey is not revelant anymore. Closing it.

Ref: 
![2019-04-01 23_01_06-Windows PowerShell](https://user-images.githubusercontent.com/6959636/55359908-4a20b180-54d3-11e9-9819-6f4d40ba10fa.png)
