### ISSUE TITLE
Regression: Top-level await hangs starting with version 1.30.0

### ISSUE THREAD

**Issue by evanw** [denoland/deno#19823]
Someone reported this as a bug in esbuild: https://github.com/evanw/esbuild/issues/3223. However, I believe this is a bug with Deno itself. Repro:

1. Create a file called `main.ts` like this:

    ```ts
    import * as esbuild from "https://deno.land/x/esbuild@v0.18.11/mod.js";

    console.log("build start");
    await esbuild.build({
        entryPoints: [],
        plugins: [{
            name: "test",
            setup(build) {
                build.onEnd(async () => {
                    console.log("onEnd start");
                    await import("./await.ts");
                    console.log("onEnd done");
                });
            },
        }],
    });
    console.log("build done");

    esbuild.stop();
    ```

2. Create a file called `async.ts` like this:

    ```ts
    console.log("await start");
    await new Promise((res) => setTimeout(res, 100));
    console.log("await done");
    ```

3. Run ` deno run -A main.ts`

    This should print the following:

    ```
    build start
    onEnd start
    await start
    await done
    onEnd done
    build done
    ```

This works in Deno version 1.29.0 and fails in Deno version 1.30.0:

```
$ deno upgrade --version 1.29.0
$ deno run -A main.ts
build start
onEnd start
await start
await done
onEnd done
build done

$ deno upgrade --version 1.30.0
$ deno run -A main.ts
build start
onEnd start
await start
await done
(hangs)
```

I believe this to be a Deno bug both because it behaves differently in different versions of Deno and because the control flow from `onEnd start` to `onEnd done` doesn't involve anything related to esbuild.

**Comment by nathanwhit** [comment]
Testing this again, it seems this is now fixed.

Looks like it was actually fixed back in 1.44.2, by https://github.com/denoland/deno_core/pull/769 (merged into deno in https://github.com/denoland/deno/pull/24128).

Feel free to reopen if you find it isn't actually resolved!
