### ISSUE TITLE
Feature Request: deno lint rule `no-floating-promises`

### ISSUE THREAD

**Issue by RichardRobertson** [denoland/deno#19832]
From [https://typescript-eslint.io/rules/no-floating-promises/](https://typescript-eslint.io/rules/no-floating-promises/)

> A "floating" Promise is one that is created without any code set up to handle any errors it might throw. Floating Promises can cause several issues, such as improperly sequenced operations, ignored Promise rejections, and more.
> 
> This rule reports when a Promise is created and not properly handled. Valid ways of handling a Promise-valued statement include:
> 
> - `await`ing it
> - `return`ing it
> - Calling its `.then()` with two arguments
> - Calling its `.catch()` with one argument

**Comment by dsherret** [comment]
See https://github.com/denoland/deno_lint/issues/303

I really want this too. It might be added to TypeScript: https://github.com/microsoft/TypeScript/issues/13376#issuecomment-1609812642

**Comment by RichardRobertson** [comment]
Whoops. I didn't realize there was a deno lint specific repository. That explains why I couldn't find a existing issue when I searched. Thank you!
