### ISSUE TITLE
Inaccurate results for `Deno.bench` due to JIT

### ISSUE THREAD

**Issue by boywithkeyboard** [denoland/deno#19839]
As of now, it matters in which order you put your `Deno.bench`es (the first tends to run faster).

This behavior can be fixed by adding the following to the top:

```ts
for (let i = 0; i < 10; ++i) {
  Deno.bench('noop', () => {})
}
```

Related messages on Discord:
- https://discord.com/channels/684898665143206084/684898665151594506/1129442105547296819
- https://discord.com/channels/684898665143206084/684898665151594506/1129436766835847199

**Comment by dsherret** [comment]
See https://github.com/denoland/deno/issues/15277

**Comment by dsherret** [comment]
Sounds good. #15277 is the issue for this
