### ISSUE TITLE
graphql and graphql-tools are not compatible with npm specifier when using loadFilesSync

### ISSUE THREAD

**Issue by dogukanakkaya** [denoland/deno#19838]
`deno.jsonc`
```json
"graphql-tools/merge": "npm:@graphql-tools/merge@9.0.0",
"graphql-tools/load-files": "npm:@graphql-tools/load-files@9.0.0"
```

`script.ts`
```ts
import { mergeResolvers, mergeTypeDefs } from 'graphql-tools/merge'
import { loadFilesSync } from 'graphql-tools/load-files'
```

> error: npm package '@protobufjs/utf8' does not exist.

But the package exists: https://www.npmjs.com/package/@protobufjs/utf8

**Comment by dsherret** [comment]
@dogukanakkaya what version of Deno are you using? I'm unable to reproduce. Also, what's the correct `@graphql-tools/load-files` version range? Version 9 does not exist.

**Comment by dogukanakkaya** [comment]
`1.35.1` which is latest for now.

**Comment by dsherret** [comment]
@dogukanakkaya ok, would you be able to provide a full working reproduction? Version 9.0.0 does not exist for https://www.npmjs.com/package/@graphql-tools/load-files?activeTab=versions

**Comment by dogukanakkaya** [comment]
Yeah I also saw that latest of that is `7.0.0`.

### Additional context
It was not related with the version but this succeeded after few retries. I forced server to restart it threw error few more times and then I saw that installation again expecting to throw but it succeeded. I have no idea why maybe npm registry was not responding at that moment. I only could saw that version `9.0.0` error after protobuf installation succeded.

I also faced with same kind of issue before: https://github.com/denoland/deno/issues/19634
And I remember that I tried to resolve that issue by clearing cache, restarting etc. None of them worked.

**Comment by dogukanakkaya** [comment]
Nontheless, GraphQL packages installations are still not compatible. Hence edited the issue title to be more general for graphql packages usage in Deno.

# More Context
```ts
import { loadFilesSync } from 'graphql-tools/load-files'
import { mergeResolvers, mergeTypeDefs } from 'graphql-tools/merge'
import { makeExecutableSchema } from 'graphql-tools/schema'

const __dirname = path.dirname(path.fromFileUrl(import.meta.url));

const typeDefFiles = loadFilesSync(path.join(__dirname, 'modules/**/types.graphql'));
const resolverFiles = loadFilesSync(path.join(__dirname, 'modules/**/resolvers.ts'));
```

Throws error
```
error: Uncaught SyntaxError: Unexpected token 'export'
    at Object.evalContext (ext:core/01_core.js:842:14)
    at wrapSafe (node:module:695:27)
    at Module._compile (node:module:705:29)
    at Object.Module._extensions..js (node:module:737:12)
    at Module.load (node:module:652:34)
    at Function.Module._load (node:module:534:16)
    at Module.require (node:module:671:23)
    at require (node:module:771:20)
    at file:///.../deno/npm/registry.npmjs.org/@graphql-tools/load-files/7.0.0/esm/index.js:103:33
    at Array.map (<anonymous>)
```
I checked the esm exported file but seems like nothing wrong with it.

**Comment by dsherret** [comment]
That's strange. Are you using a custom registry or proxy to npm? Maybe npm did indeed respond with not found for some reason. I just looked through the npm code and it should only give that error if the registry returns back a 404.

> I also faced with same kind of issue before: https://github.com/denoland/deno/issues/19634

I just looked into that and it seems like a separate resolution bug.

**Comment by dogukanakkaya** [comment]
No I don't use custom registry nor proxy. But it happened, i am not sure either.

**Comment by dsherret** [comment]
@dogukanakkaya would you be able to provide full reproductions to make this easier to reproduce? I just tried out that code and it works fine for me presumably because I don't have any types.graphql and resolver.ts files and `path` doesn't exist, which I assume is deno_std/path.

**Comment by dsherret** [comment]
Also, do you have any other dependencies or a deno lockfile? Are you using a node_modules directory? What does your full deno.json and directory structure look like?

**Comment by dogukanakkaya** [comment]
Prepared a repo for it :https://github.com/dogukanakkaya/deno-graphql-issue

Btw, i tried to jump that step and tried static definition for resolvers to go forward for now. You can uncomment that in `graphql.ts` file and it'll work that way.

After that i use `graphql-tools/schema` and it occurs other compatibility issues. But it might not be related with Deno exactly. Not sure if we can use npm resolutions in Deno but the problem for that is basically:

> Duplicate "graphql" modules cannot be used at the same time since different
versions may have different capabilities and behavior.

I can prepare the repo to reproduce this after the first issue if needed.

**Comment by dogukanakkaya** [comment]
Prepared a repo for it :https://github.com/dogukanakkaya/deno-graphql-issue

Btw, i tried to jump that step and tried static definition for resolvers to go forward for now. You can uncomment that in graphql.ts file and it'll work that way.

**Comment by dsherret** [comment]
Thanks! The repo was helpful.

I took a look into this and it's failing because it is using `require` to require the typescript in resolvers.ts. I opened #19842 to help make this more obvious.

Looking into this more, this is actually not a Deno issue. A similar thing happens in Node because CommonJS code is trying to import ESM. The error that Node gives is the following:

```
Error [ERR_REQUIRE_ESM]: require() of ES Module /home/david/dev/deno-graphql-issue/modules/m1/graphql/resolvers.js from /home/david/dev/deno-graphql-issue/noop.js not supported.
Instead change the require of resolvers.js in /home/david/dev/deno-graphql-issue/noop.js to a dynamic import() which is available in all CommonJS modules.
    at file:///home/david/dev/deno-graphql-issue/node_modules/@graphql-tools/load-files/esm/index.js:103:33
    at Array.map (<anonymous>)
    at loadFilesSync (file:///home/david/dev/deno-graphql-issue/node_modules/@graphql-tools/load-files/esm/index.js:94:10)
    at file:///home/david/dev/deno-graphql-issue/asdf.js:5:23 {
  code: 'ERR_REQUIRE_ESM'
}
```

I opened #19842 to help improve the Deno error.

**Solution**

The solution you should do in this case is not use `loadFilesSync` (which uses `require`) and instead use `loadFiles`, which is asynchronous and will use a dynamic import to load the files:

```ts
import { loadFiles } from 'graphql-tools/load-files'
```

Hope it helps!

**Comment by dogukanakkaya** [comment]
Yeah I understood the issue. Have you tried that solution? Probably still not related with Deno but i am having error.

```ts
error: Uncaught TypeError: Could not resolve '.../graphql/resolvers.ts' from 'file:///.../deno/npm/registry.npmjs.org/@graphql-tools/load-files/7.0.0/esm/index.js'.
  Caused by:
    TypeScript files are not supported in npm packages: file:///.../graphql/resolvers.ts
```

Docs are saying that ts files are allowed but still somehow it errors. Just wondering if you could make it work with the above solution. If not, I'll figure it out somehow, seems like this is not related with Deno indeed.

**Comment by dogukanakkaya** [comment]
Yeah I understood the issue, thank you. Also I faced with another issue after that solution.

error: Uncaught TypeError: Could not resolve '.../graphql/resolvers.ts' from 'file:///.../deno/npm/registry.npmjs.org/@graphql-tools/load-files/7.0.0/esm/index.js'.
  Caused by:
    TypeScript files are not supported in npm packages: file:///.../graphql/resolvers.ts
    
For anyone having the same issue solution is dynamic import the resolver files as well with `requireMethod` property in second argument.
```ts
const resolverFiles = await loadFiles(path.join(__dirname, 'modules/**/resolvers.*'), {
  requireMethod: async (path: string) => {
    const module = await import(path);
    return module.default
  },
  recursive: true,
});
```

**Comment by dsherret** [comment]
Sorry, I must have made a bunch of changes while investigating that I probably made a silly mistake that made it load, but not work. Yeah, requireMethod works for me too.

I opened https://github.com/denoland/deno/issues/19843
