### ISSUE TITLE
Calling WebSocket.send() twice with large binary data never sends queued data

### ISSUE THREAD

**Issue by chromakode** [denoland/deno#19851]
Hi! I've been puzzling tonight over this odd behavior I'm seeing in a Deno WebSocket server:

When I call `WebSocket.send()` twice with a large enough arraybuffer, the data never seems to be flushed from the send buffer.

Here's a minimal repro:

```ts
Deno.serve({ port: 8000 }, (req) => {
  if (req.headers.get("upgrade") != "websocket") {
    return new Response(null, { status: 501 });
  }
  const { socket, response } = Deno.upgradeWebSocket(req);

  socket.addEventListener("open", () => {
    socket.binaryType = "arraybuffer";
    setInterval(() => {
      console.log("buffer length:", socket.bufferedAmount);
    }, 500);
    socket.send(new ArrayBuffer(200000));
    socket.send(new ArrayBuffer(100));
  });

  return response;
});
```

When I open a client connection in the Chrome JS console with `new WebSocket('ws://localhost:8000')`, the network inspector never shows the messages arriving. I observed similar in Firefox. The Deno server prints `buffer length: 200000` in the logs (which in itself is interesting, since it's missing the 100 bytes from the second call)

If I change the send code to:

```ts
    socket.send(new ArrayBuffer(200000));
    setTimeout(() => {
      socket.send(new ArrayBuffer(100))
    }, 500)
```

Then both messages arrive in the Chrome network inspector as expected.

Similarly, shortening the first message works fine: 

```ts
    socket.send(new ArrayBuffer(100000));
    socket.send(new ArrayBuffer(100))
```

Earlier tonight I was seeing websocket connections fail in Chrome with an "Invalid Frame Header" error, which adds to my suspicion there's some kind of race condition or buffering bug here.

```
$ deno --version
deno 1.35.1 (release, x86_64-unknown-linux-gnu)
v8 11.6.189.7
typescript 5.1.6
```

I tried Deno's own WebSocket client, and could not repro; the client receives both messages immediately. I only saw this hanging behavior when Chrome and Firefox were clients.

I was curious if I was misunderstanding some browser behavior, so I tested a minimal node equivalent server with Chrome, and did not repro (both messages received):

```ts
const { WebSocketServer } = require("ws");

const wss = new WebSocketServer({ port: 8000 });

wss.on("connection", function connection(ws) {
  setInterval(() => {
    console.log("buffer length:", ws.bufferedAmount);
  }, 500);
  ws.send(new ArrayBuffer(200000));
  ws.send(new ArrayBuffer(100));
});
```

**Comment by littledivy** [comment]
Thanks for the bug report. This has been fixed on `main`. 

I tried your reproduction on `main` and Chrome recieves the messages:

![image](https://github.com/denoland/deno/assets/34997667/1de69cf5-5433-4ebf-84c6-1bc5ee3dfa22)
