### ISSUE TITLE
bug: errors during `deno test --parallel`

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno#19852]
In https://github.com/denoland/deno_std/pull/3446, I aim to parallelize testing for the Standard Library. The latest tests pass. However, in the latest CI run on Windows, [errors are occurring](https://github.com/denoland/deno_std/actions/runs/5471376452/jobs/9962446435?pr=3446). Frankly, I don't know what's causing this.
```
error: The system cannot find the path specified. (os error 3)
Error: Process completed with exit code 1.
```

**Comment by bartlomieju** [comment]
I believe it's not a bug, but rather it uncovered that some tests depend on output from other test cases (in this case it's a missing file). Let's try to chase it down in `deno_std`.
