### ISSUE TITLE
😳 `setTimeout` sometimes (extremely rarely) doesn't fire in Deno versions >= v1.34.3

### ISSUE THREAD

**Issue by josephrocca** [denoland/deno#19866]
After a pretty painful half-day of debugging a weird issue on one of my servers, below is the code that reproduces a problem where `setTimeout` doesn't seem to fire. You may have to run it for up to 5 minutes to reproduce.

```js
async function start(n) {
  await new Promise(r => setTimeout(r, 10000*Math.random()));

  let lastLogTime = Date.now();
  setInterval(() => {
    console.log(n, ((Date.now()-lastLogTime)/1000).toFixed(1));
  }, 1000*10);

  let i = 0;
  while(1) {
    await new Promise(r => setTimeout(r, 1 + 5*Math.random()));
    if(++i % 1000 === 0) lastLogTime = Date.now();
  }
}

for(let n = 0; n < 200; n++) {
  start(n);
}
```

You'll eventually see large numbers being logged, indicating that one of the concurrent loops has stopped:

![image](https://github.com/denoland/deno/assets/1167575/38619c17-de2f-499d-a981-24ad1ca9b65d)

I ran the above code on PopOS/Ubuntu 22.04 with:
```
deno 1.35.1 (release, x86_64-unknown-linux-gnu)
v8 11.6.189.7
typescript 5.1.6
```

Based on my testing:

 * 1.35.1 - ⚠️ bug definitely exists
 * 1.35.0 - ⚠️ bug definitely exists
 * 1.34.3 - ⚠️ bug definitely exists
 * 1.34.2 - ✅ ran for a long time with no issues
 * 1.34.1 - ✅ ran for a long time with no issues
 * 1.34.0 - ✅ ran for a long time with no issues
 * 1.33.4 - ✅ ran for a long time with no issues

I guess it's also possible that `setTimeout` is in fact firing, but something is going wrong with the `Promise` or `await` stuff.

**EDIT:** Code was originally `let n = 0; n < 100; n++` but I just changed it to `200` because that reproduces the bug much faster - with `100` concurrent instances of `start` it was taking between 10 minutes and an hour to reproduce, whereas with `200` it reproduces in a few minutes at most.

**Comment by josephrocca** [comment]
Wondering whether it's related to this: https://github.com/denoland/deno/pull/19492

**Comment by bartlomieju** [comment]
Thanks for the report, we'll look into it ASAP.

**Comment by bartlomieju** [comment]
I've been running the reproduction code for almost an hour with Deno v1.36.0 and I can't get a single log that had value exceeding 1000. We'll dig in more, but so far no luck.

**Comment by josephrocca** [comment]
@bartlomieju How high are they getting for you? They should never exceed roughly `5` (seconds since `lastLogTime = Date.now()` was executed - i.e. seconds since the while loop stalled) . I just upgraded to `1.36.0` and ran the script, and immediately got a bunch of stalls:

![image](https://github.com/denoland/deno/assets/1167575/7601fecd-0a26-44fe-ae36-8983f4b38770)

It keeps climbing to 1000 seconds and beyond. I'm running this on PopOS 22.04 (which is basically Ubuntu 22.04) - my dev machine. The production machine that this bug first occurred on was a DigitalOcean Ubuntu 18.04 machine.

Note that I encountered this bug on a long-running server (several days). I figure it's worth mentioning this because it indicates that this bug occurs even if the event loop isn't being "spammed" as much as in this reproduction example - it just takes a lot longer for `setTimeout` to 'fail' if I'm making fewer calls to it per second.

Here's some slightly more clear, trimmed-down code that reproduces the issue:
```js
async function start(n) {
  let lastLogTime = Date.now();
  setInterval(() => {
    console.log(`loop id: ${n}, stopped for: ${Date.now()-lastLogTime}ms`);
  }, 1000*5);

  let i = 0;
  while(1) {
    await new Promise(r => setTimeout(r, 3));
    if(++i % 1000 === 0) lastLogTime = Date.now();
  }
}

for(let n = 0; n < 200; n++) {
  start(n);
}
```

**Comment by milaz** [comment]
Running on Ubuntu 23.04, the reproduction is almost immediate:

```
loop id: 162, stopped for: 6995ms
loop id: 128, stopped for: 2966ms
loop id: 162, stopped for: 11998ms
loop id: 163, stopped for: 4982ms
loop id: 128, stopped for: 7970ms
loop id: 143, stopped for: 6968ms
loop id: 146, stopped for: 4961ms
loop id: 162, stopped for: 17002ms
loop id: 163, stopped for: 9986ms
loop id: 184, stopped for: 5964ms
loop id: 128, stopped for: 12971ms
loop id: 143, stopped for: 11969ms
loop id: 146, stopped for: 9962ms
```

It happens with the code further simplified:

```
async function start(n) {
  let lastLogTime = Date.now();
  setInterval(() => {
    let diff = Date.now()-lastLogTime;
    if (diff > 2000) console.log(`loop id: ${n}, stopped for: ${diff}ms`);
  }, 1000*5);
  setInterval(() => lastLogTime = Date.now(), 1000);
}

for(let n = 0; n < 200; n++) {
  start(n);
}
```

**Comment by bartlomieju** [comment]
@josephrocca @milaz thanks, now I can repeat it and see that a lot of the timers keep increasing without ever clearing "stopped for".

**Comment by bartlomieju** [comment]
Okay, this problem is definitely caused by https://github.com/denoland/deno/pull/19493.
