### ISSUE TITLE
[Discussion] Website Platform

### ISSUE THREAD

**Issue by zugende** [denoland/deno#1986]
As Deno is getting more mature I would like to throw in the question if Ryan and the team is ready to improve the website structure. My vision is creating a modern looking PWA which helps interested people to quickly get the concept of Deno, learn more about Deno and its api as well as get more information about third party modules.

Would love to do this in VueJS but open to your sugesstions.
If this discussion is still to early you can close this issue. :)

Quick scribble in Figma:
<img width="1440" alt="Desktop" src="https://user-images.githubusercontent.com/7976502/54868744-1b4a6300-4d90-11e9-9c87-274d8df8dc54.png">

**Comment by Maxim-Mazurok** [comment]
While this design looks nice and fancy, I'd prefer keeping deno website simple.
There's a beauty in current minimalistic design. Also, less fancy design means less potential bugs and more accessibility.
There's no need to make a complex SPA or PWA out of website with documentation, there's no complex logic that should be handled on the client side.
Still, some features of PWA could be used as long as they will not increase complexity, like custom theme color, etc.

I vote for keeping it simple.

And please, don't use barely visible grey colors, they are killing accessibility ([ref](https://www.w3.org/TR/WCAG20-TECHS/G18.html)).

**Comment by zekth** [comment]
Personnaly design has to be kept simple, with accessibility to binaries and documentations. Colors and so on are tied to the Deno graphic chart (atm there is none i think).

But why making it with VueJs for just a static website? A bit overkill for me. Also PWA app i overkill, as a side project why not.

**Comment by ry** [comment]
@zugende Looks nice, but I prefer to have small incremental improvements. Also I'm going to for a minimalist design where we can manage most of our text in markdown. The Deno software itself is still an "alpha version", so a pretty and graphical site might suggest otherwise.

If you wanted to help out with the site, some incremental improvements to the syntax highlighting colors would be a welcome improvement.
