### ISSUE TITLE
Proposal: Allow deno to support JSX out of the box

### ISSUE THREAD

**Issue by roberto-morado** [denoland/deno#19874]

**Comment by bartlomieju** [comment]
Deno supports JSX out-of-the-box - https://deno.land/manual@v1.35.1/advanced/jsx_dom/overview#jsx. Could you explain what your are asking for?

**Comment by roberto-morado** [comment]
There's a lot of configuration going on in there; why can't we...?

```ts
// server.tsx

function App() {
   return <h1>Hello!</h1>
}

Deno.serve((_req: Request): Response => {
   return new Response(App(), {
      headers: {
         "content-type": "text/html; charset=utf-8"
      }
   })
})
```

#### 🎉 Out-Of-The-Box 🚀

**Comment by marvinhagemeister** [comment]
@roberto-morado Right now deno merely transpiles it similar to the babel or TypeScript JSX transforms. Converting JSX directly to strings would be indeed awesome. It would need to account for a couple of edge cases though to prevent XSS vulnerabilities which can become a little tricky.

Right now you can get pretty close to that with Preact and that's how current frameworks for Deno do it. It's not as nice as requiring zero dependencies, but is close.

**Comment by roberto-morado** [comment]
Thank you.
