### ISSUE TITLE
Rewrite Deno.readFile and Deno.writeFile to use more primitive ops

### ISSUE THREAD

**Issue by ry** [denoland/deno#1989]
Should be a simple fix - perhaps using Buffer for readFile.

Sync versions should be done too.

At the end the readFile and writeFile ops should be removed completely from cli/msg.fbs

**Comment by bartlomieju** [comment]
I'm working on that

**Comment by bartlomieju** [comment]
@ry just so we're on the same page, we want to rework `readFile` and `writeFile` to use shared queue rather than old way with flatbuffers?

**Comment by ry** [comment]
@bartlomieju No - implement them as a series of read and write ops. This should be a pure TS patch.
