### ISSUE TITLE
thoughts on http* API

### ISSUE THREAD

**Issue by idiomatic** [denoland/deno#199]
For many of us, our first exposure to Node.js was the trivial HTTP server example.  It succinctly demonstrated the API conventions one would experience throughout the standard library.

How would you like the Deno HTTP* API to look?

## NODEISH

Analagous to `readFileSync()` and Node.js.

```javascript
import { createServer, createTLSServer, createSecureServer } from "deno";
const options = {key: KEY, cert: CERT};
const s = createServer((req, res) => { });
const stls = createTLSServer(options, (req, res) => { });
const s2 = createSecureServer(options, (req, res) => { });
s.listen(PORT, ADDRESS);
stls.listen(PORT_TLS, ADDRESS);
s2.listen(PORT_HTTP2, ADDRESS);
```

## MANYLISTENS

Distinct `listen()` methods.

```javascript
import { createServer } from "deno";
const options = {key: KEY, cert: CERT};
const s = createServer(options, (req, res) => { });
s.listen(PORT, ADDRESS);
s.listenTLS(PORT_TLS, ADDRESS);
s.listen2(PORT_HTTP2, ADDRESS);
```

## MANYCREATES

Explicit constructors and flat namespace.

```javascript
import { createHTTPServer, createTLSServer, createHTTP2Server } from "deno";
const options = {key: KEY, cert: CERT};
const s = createHTTPServer((req, res) => { });
const stls = createTLSServer(options, (req, res) => { });
const s2 = createHTTP2Server(options, (req, res) => { });
s.listen(PORT, ADDRESS);
stls.listen(PORT_TLS, ADDRESS);
s2.listen(PORT_HTTP2, ADDRESS);
```

## NAMESPACES

Node.js-like namespaces to disambiguate `createServer()`.

```javascript
import { http, https, http2 } from "deno";
const options = {key: KEY, cert: CERT};
const s = http.createServer((req, res) => { });
const stls = https.createServer(options, (req, res) => { });
const s2 = http2.createServer(options, (req, res) => { });
s.listen(PORT, ADDRESS);
stls.listen(PORT_TLS, ADDRESS);
s2.listen(PORT_HTTP2, ADDRESS);
```

## CREATEOPT

`createServer()` attribute.

```javascript
import { createServer } from "deno";
const options = {key: KEY, cert: CERT};
const s = createServer((req, res) => { });
const stls = createServer({...options, protocol: "https"}, (req, res) => { });
const s2 = createServer({...options, protocol: "http/2"}, (req, res) => { });
s.listen(PORT, ADDRESS)
stls.listen(PORT_TLS, ADDRESS)
s2.listen(PORT_HTTP2, ADDRESS)
```

## LISTENARG

`listen()` method argument.

```javascript
import { createServer } from "deno";
const options = {key: KEY, cert: CERT};
const s = createServer(options, (req, res) => { });
s.listen(PORT, ADDRESS, "http");
s.listen({protocol: "https"}, PORT_TLS, ADDRESS);
s.listen({protocol: "http/2"}, PORT_HTTP2, ADDRESS);
```

## LISTENMAP

`listen()` port map

```javascript
import { createServer } from "deno";
const options = {key: KEY, cert: CERT};
const s = createServer(options, (req, res) => { });
const portMap = {80:"http", 443:["https", "http/2"]};
s.listen(portMap, ADDRESS);
```

## Legacy Node.js

```javascript
const http = require('http');
const https = require('https');
const http2 = require('http2');
const s = http.createServer((req, res) => { });
s.listen(PORT, ADDRESS);
const options = {key: KEY, cert: CERT};
const stls = https.createServer(options, (req, res) => { });
stls.listen(PORT_TLS, ADDRESS);
const s2 = http2.createSecureServer(options, (req, res) => { });
s2.listen(PORT_HTTP2, ADDRESS);
```

## Go

```go
package main

import "net/http"

func main() {
    s := &http.Server{Addr:"ADDRESS:PORT"}
    s.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) { })
    go func() {
        s.ListenAndServe()
    }()

    stls := &http.Server{Addr:"ADDRESS:PORT_TLS"}
    stls.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) { })
    go func() {
        stls.ListenAndServeTLS()
    }()

    // wait forever
    select{ }
}
```

**Comment by Janpot** [comment]
I'd love to see some sort of inverse `fetch`;

```js
import { serve, Response } from 'http'

serve(80, async ({ request }) => {
  const body = JSON.stringify({ hello: 'world' });
  return new Response(body, {
    status: 200,
    headers: new Headers({
      'content-type': 'application/json'
    })
  });
});
```

**Comment by Jusys** [comment]
why not "MANYLISTENS" or "LISTENMAP"? For me they're shortest and cleanest - for newcomers with less experience of deno or typescript it would be easier to understand what's happening.

**Comment by cmbkla** [comment]
I like "MANYLISTENS", with the assumption that I would have a  way to access the same instance of `s` in another file, and would then get events like OnRequest and OnResponse that I could hook into with middleware or a router.

**Comment by nicolasparada** [comment]
@Janpot Such a nice API 👏👏👏👏👏

**Comment by EliHeller** [comment]
what about this...

## service-workerish

```js
import { HttpServer, Routes } from 'http';

const routes = new Routes;

routes.add({
    route: '/',
    method: 'GET',
    body: 'hello world'
});

const server = new HttpServer(event => {
    routes.match(event.request, response => {
        event.respontWith(response);
    }
})

server.listen(80);
```

**Comment by Roshan931** [comment]
I think `MANYLISTENS` are clean and understandable for beginners. There is one server and it can listen on different protocols. Maybe just use a different name for http/2, `.listen2` is a bit unclear.

What about something like this...

```js
import { createServer } from "deno"

const options = { key: KEY, cert: CERT }
const s = createServer(options, (req, res) => { })

s.listen(PORT, ADDRESS) // or s.http.listen
s.tls.listen(PORT, ADDRESS)
s.http2.listen(PORT, ADDRESS)
```

**Comment by Janpot** [comment]
I think http2 is going to require a little more API than just `listen`

**Comment by EliHeller** [comment]
@Janpot either way with your proposed API i think it is more simple to do routing

**Comment by quasis** [comment]
In node.js you always need a wrapper (even for trivial tasks). Otherwise, the code becomes too complicated. No wonder express.js became so popular.

Anything that will remove the need in wrappers will be excellent. For example:

```JS
import {HTTP} from "deno";

const server = new HTTP();

server.get('/:var1/:var2', (request, var1, var2, queries) =>
{
    return Response.json({});
});

await server.listen(8080);
```

**Comment by Lizhooh** [comment]
Hope similar to [Koa](https://koajs.com/).

**Comment by asosnovsky** [comment]
What about a semi-java semi-express way of
```
import { Server, Router, Request, Response } from "http";

const router = new Router();
const server = new Server({
    port: 443,
    ssl: "path-to-ssl",
});

router.route("/", (req: Request): Response => {
    if( req.method === Request.GET ) {
        return new Response("hello world");
    }
    return Response.NotFound();
}):

server.route("/", router);
server.listen();
```

**Comment by drawm** [comment]
@idiomatic > How would you like the Deno HTTP* API to look?

**Comment by ccravens** [comment]
While not directly addressing the original topic author's question, I thought it important to discuss. I'm of the opinion that a language API should provide a VERY basic, non-opinionated interface to raw services, for example http. It really should only provide the ability to start a VERY lightweight service, create a request, and respond to requests with request/response objects. But it looks like we are discussing how to handle router configuration. This all should be the responsibility of the framework, not the language API.

IMO, this is what the HTTP language API should offer:
- Create a very lightweight HTTP service
- Provide a request callback with a Response object to respond to valid requests, error callback for invalid requests
- Make raw HTTP calls by creating a raw HTTP request object
- Provide a response callback with the Response object

What the deno HTTP API should NOT offer:
- Router configuration (how do you configure routers? Config file? Declarative in the source code? XML? Decorators?) How do you format your routes for get parameters? What should those get parameters looks like (regex)? All of these are used by a variety of frameworks and should be left to the framework
- Managing views
- Managing connections to a database (connection pooling), Models and ORM

By staying non-opinionated and only focusing on the very basics of the service, this gives the open source community the freedom to offer a variety of web frameworks that can use all sorts of different styles and architectures based on the needs / desires of the individual developer.

```javascript

```

**Comment by NewLunarFire** [comment]
Ryan's talk mentionned how he thought the Node library has grown huge and wanted to keep a simple native interface for deno. You could even argue that you might not need an HTTP api but only a network api and build an HTTP library in userspace.

**Comment by idiomatic** [comment]
@NewLunarFire and @ccravens, I was thinking similarly with this functional-programming mock-up:

```typescript
/* wrap connections with TLS.  usable for HTTPS or other TLS protocols */
export function tls(key, cert: string, cx: ConnectionHandler): ConnectionHandler { … }

/* groks HTTP and HTTP/2; could offshore to a third-party module */
export function http(h: RequestHandler): ConnectionHandler { … }
```

```typescript
import { listen, tls, http, open } from "deno";
// import { route, redirect, static, hterror } from "… third-party ...";

const server = http((req) => {
	if (req.path === "/") {
		return "hello world\n";
	else if (req.path[:8] === "/static/" && req.path.index("/.") == -1) {
		return open(req.path[8:], 'r')
	} else {
		return new Response({statusCode: 302, body: "moved", location: "/"})
	}
});
listen(PORT, server);
listen(TLS_PORT, tls(KEY, CERT, server));
```

**Comment by idiomatic** [comment]
## GENERATORSTACK

Contemporary language syntax features rather than callbacks, object-oriented, or declarative patterns.

```typescript
import { listen, tls, http } from "deno";
for (let req of http(tls(listen(TLS_PORT)))) {
	return "hello world\n"
}
```

And to merge multiple connection generators under the same protocol transgenerator, give `http()` a varargs signature.

**Comment by AgentME** [comment]
>GENERATORSTACK

Unless there's some radical javascript proposals I'm behind the times on, you can't return to a loop and you need async iteration, so I'm going to respond as if your example were the following:

```js
import { listen, tls, http } from "deno";
for await (let connection of http(tls(listen(TLS_PORT)))) {
	connection.respondWith("hello world\n");
}
```

Something awkward about the strategy is what happens if you need to await a promise while handling a request. Consider the naive approach:

```js
import { listen, tls, http } from "deno";
for await (let connection of http(tls(listen(TLS_PORT)))) {
	const result = await mySlowDatabaseCall();
	connection.respondWith("hello world\n" + result);
}
```

Several problems:
* Only one request can be handled at a time. If mySlowDatabaseCall() takes one second to resolve, then new requests to the server have to queue up during that time.
* The req object has to wait until respondWith is called before responding. If mySlowDatabaseCall() throws an exception, or if there's a code path that accidentally never calls req.respondWith(), then the server will hold the connection open forever without responding.
* If there's an uncaught exception while processing requests, then the for-loop entirely stops and the server stops responding to requests. There's no way for the http() module to have any built-in error handling (like give a 500 response to the user and then keep serving requests).

You could address these issues by making req.respondWith() take a promise:

```js
import { listen, tls, http } from "deno";
for await (let connection of http(tls(listen(TLS_PORT)))) {
	connection.respondWith((async () => {
		const result = await mySlowDatabaseCall();
		return "hello world\n" + result;
	})());
}
```

But that's pretty verbose and I don't think it has any advantages over a more classic async callback strategy, which could look like this to use the same composition strategy you were going for:

```js
import { listen, tls, http } from "deno";
http(tls(listen(TLS_PORT))).use(async connection => {
	const result = await mySlowDatabaseCall();
	return "hello world\n" + result;
});
```

**Comment by CanRau** [comment]
some thoughts (might be mentioned already?!)

I like [koa](https://github.com/koajs/koa)s middlewares, as mentioned in the 2. comment https://github.com/denoland/deno/issues/199#issuecomment-395532608 by @matiasinsaurralde 
but I also really like the "less hidden magic" approach of Zeits [micro](https://github.com/zeit/micro)

**Comment by trylovetom** [comment]
Hope api similar to [Micro JS](https://zeit.co/blog/micro-8). To being lean and explicit.

**Comment by MichaelJGW** [comment]
I have no idea what I'm doing but I thought it would be fun to pitch in. This is what I got.

What do we need to do?
* Declare what the server is
* Give the server what it needs
* respond to the users of the server

```javascript

// Declare what the server is
// Give the server what it needs

const server = new HttpServer ({
  // Anything the connection needs goes here.
  // If it was a Socket or a HttpsServer this would change accordingly.
  address: 'localhost',
  port: 8080
})

// HttpServer emits events like GET, POST, PUT, ...

// respond to the users of the http server
server.addEventListener('GET', (state) => {
  // As this is a HttpServer the state of the event has request and response.
  // If it was something like a Socket the state of the event can be different.
  state.response('Hello World')
})
```

With this going from Sockets, HTTPS, HTTP the only changes from this pattern.
* Config given to the server.
* Event emitted
* State Structure

Without comments

```javascript
import {HttpServer} from "deno"

const server = new HttpServer ({
  address: 'localhost',
  port: 8080
})

server.addEventListener('GET', (state) => {
  state.response('Hello World')
})

```

**Comment by Qard** [comment]
I like the idea of just layering async iterators to apply protocol logic in isolation. It's easy to layer the Node.js-like abstractions on top of that. For example, `http.createServer` could naively be implemented like this:

```js
async function createServer (interface, handler) {
  for await (let connection of interface) {
    handler(connection)
  }
}

class Response {
  constructor (request, status, body, headers = {}) {
    this.request = request
    this.status = status
    this.body = body
    this.headers = headers
  }

  *renderHead () {
    const { method, path } = this.request
    yield `${method} ${path} HTTP/1.1\n`

    yield Object.keys(this.headers)
      .map(header => `${header}: ${this.headers[header]}`)
      .join('\n')

    yield "\n\n"
  }

  async *[Symbol.asyncIterator]() {
    for (let chunk of this.renderHead()) yield chunk
    for await (let chunk of this.body) yield chunk
  }
}

createServer(http(tls(tcp(PORT))), async request => {
  return new Response(request, status, body)
})
```

**Comment by kevinkassimo** [comment]
For those who are interested, Ryan is implementing `http` as an importable module [here](https://github.com/denoland/net) and is using async iterator to accept requests.

**Comment by bartlomieju** [comment]
[HTTP module](https://github.com/denoland/deno_std/blob/master/http/README.md) is available in standard library. 

CC @ry

**Comment by ry** [comment]
Move HTTP API discussions to https://github.com/denoland/deno_std
