### ISSUE TITLE
Debugger not working in v1.35.2: "Fatal error in v8::Context::GetMicrotaskQueue # Must be called on a native context"

### ISSUE THREAD

**Issue by Leokuma** [denoland/deno#19907]
As soon as I upgraded to v1.35.2, it started giving me the error below in VSCode after setting a breakpoint and then clicking on _Step Over_, _Step Into_ or _Step Out_ (screenshot below), and the debugging session gets aborted. The Play/Run button works fine.

![image](https://github.com/denoland/deno/assets/9329952/1fa5ce23-bf24-4c04-ae3c-4273cf6d9785)

```
C:\Users\ZPT\.deno\bin\deno.EXE run --unstable --inspect-wait --allow-all .\main.ts
Debugger listening on ws://127.0.0.1:9229/ws/844e7a64-9dfd-46df-8035-6b6e695c759d
Visit chrome://inspect to connect to the debugger.
Deno is waiting for debugger to connect.
Debugger session started.

#
# Fatal error in v8::Context::GetMicrotaskQueue
# Must be called on a native context
#

Process exited with code 2147483651
```

After I switched between Deno versions a couple of times to verify that behavior, it's now giving me that error as soon as I start debugging, before hitting any breakpoints.

In v1.35.1 it still works perfectly.

I'm on Win11.

**Comment by farsightsoftware** [comment]
I get the same thing on Linux Mint v20. And as above, downgrading to 1.35.1 fixes it.

**Comment by bartlomieju** [comment]
Between v1.32.1 and v1.32.2 I see only one commit that could have caused that: https://github.com/denoland/deno/pull/19307

I will need to debug it and see if I can reliably repeat it.

**Comment by bartlomieju** [comment]
Where do you folks get this output? If I try to "step next"/"step in" I do get message "Unable to step in" but no log whatsoever.

**Comment by farsightsoftware** [comment]
@bartlomieju That was my symptom initially too. To get the actual message, I had to start Deno in a terminal window (I used `deno run -A --inspect-wait test.ts`) then attach to the process. The error happens when the debugger attaches.

**Comment by bartlomieju** [comment]
I can confirm that #19307 breaks this.

**Comment by lucacasonato** [comment]
Do you know what is calling `v8::Context::GetMicrotaskQueue`?

**Comment by bartlomieju** [comment]
@lucacasonato I assume it's one of the three function in `v8/src/inspector/v8-debugger.cc`
- `V8Debugger::reportTermination`
- `V8Debugger::installTerminateExecutionCallbacks`
- `V8Debugger::~V8Debugger`
