### ISSUE TITLE
LSP badly resolves relative imports between cached modules

### ISSUE THREAD

**Issue by adamgreg** [denoland/deno#19908]
I think the LSP / VS Code has started resolving relative imports between cached modules badly.

I'm running under a devcontainer, with the project root in `/workspace/` and `$DENO_DIR` is `/deno/.cache/deno`. I can run my unit tests from a terminal ok, but if I try to run them in VS Code I get a "Module Not Found" error popup that shows an attempt to import a module from `/workspace/deno/.cache/deno/...`.

If I open the (cached) module containing the failing import and hover the import statement I see a popup with the "Resolved Dependency" in the wrong place, outside the cache. Screenshots attached.

It seems to be linked to an entry in the import map - `"/": "./"`, copied from [the "Using project root for absolute imports" example in the manual](https://deno.land/manual@v1.35.2/basics/import_maps#example---using-project-root-for-absolute-imports) . If I comment that out, the problem goes away. I think there must be some bug at play here.

![image](https://github.com/denoland/deno/assets/24409856/8f517d5e-08c1-493e-be07-01ef84a8927e)
![image](https://github.com/denoland/deno/assets/24409856/bc828c95-5bba-4d07-b528-2138d46c2be6)

**Comment by adamgreg** [comment]
I now have "absolute" imports and cache-relative imports both working properly after moving the "absolute" entries in the import map (`deno.jsonc`) into a project-relative scope:

```json
  "scopes": {
    "./": {
      "/": "./",
      "./": "./"
    }
```

**Comment by cosmoswafer** [comment]
I personally strongly recommend revising the official documentation to include this as an example.

**Comment by adamgreg** [comment]
Hi @cosmoswafer I later switched the import map entry so I could prefix project-relative imports with "@/" instead of "/". Then I didn't need to use scopes any more. I don't know if the original issue I reported is still a problem.

**Comment by cosmoswafer** [comment]
@adamgreg, I understand. I’ve conducted another test on Deno 1.44.2, and it appears that the scoped import map is not functioning as expected. While prefixes like “@/”, “@root/”, and “@baba/” seem to work, following the example from the official documentation leads to annoying suggestions. I think most users will read the documentation first, so it would be beneficial to provide an idiomatic example there.

**Comment by nayeemrmn** [comment]
I recall this being fixed this year, please comment if you find it's still an issue.
