### ISSUE TITLE
Package compatibility problem with `light-my-request`

### ISSUE THREAD

**Issue by kwhinnery** [denoland/deno#19901]
A Node/npm compatibility issue was reported by a Discord user with the [`light-my-request`](https://github.com/fastify/light-my-request) module. The following code should theoretically work in Deno, but produces an error.

```ts
import http from "node:http";
import inject from "npm:light-my-request";

const dispatch = function (_req, res) {
  const reply = "Hello World";
  res.writeHead(200, {
    "Content-Type": "text/plain",
    "Content-Length": reply.length,
  });
  res.end(reply);
};

const server = http.createServer(dispatch);

inject(dispatch, { method: "get", url: "/" }, (err, res) => {
  console.log(err);
  console.log(res.payload);
});
```

Error:

```
kevin@kevin-deno deno-support % deno run -A test.ts 
error: Uncaught TypeError: Class constructor ServerResponse cannot be invoked without 'new'
    at new Response (file:///Users/kevin/Library/Caches/deno/npm/registry.npmjs.org/light-my-request/5.10.0/lib/response.js:10:23)
    at doInject (file:///Users/kevin/Library/Caches/deno/npm/registry.npmjs.org/light-my-request/5.10.0/index.js:56:17)
    at inject (file:///Users/kevin/Library/Caches/deno/npm/registry.npmjs.org/light-my-request/5.10.0/index.js:15:12)
    at file:///Users/kevin/dev/deno-support/test.ts:15:1
```

**Comment by sigmaSd** [comment]
In deno ServerResponse is written as a class but in node its written as a function
The npm package uses `ServerResponse.call`  which only works with function

I wonder if there is a trick to fix this (other then rewriting ServerResponse as a function)

**Comment by bartlomieju** [comment]
I don't think so. We should rewrite it to use a function.

**Comment by KaKi87** [comment]
Hello,
Is there an ETA on this ?
Thanks

**Comment by bartlomieju** [comment]
I discussed it with @crowlKats and we're eyeballing a solution. We expect this will be fixed some time this month.

**Comment by stevefan1999-personal** [comment]
Also check out here: https://github.com/stevefan1999-personal/nestjs-deno-test/blob/2dc5cc2de2ed04ce441e31cbe1f37e69dfc185f1/fastify-test.ts#L28-L34

It is blocking Fastify test in Deno too

**Comment by nicolabovolato** [comment]
@bartlomieju Can I submit a PR for this? I'm thinking of refactoring ServerResponse into a functional class

**Comment by bartlomieju** [comment]
Sure, feel free to do it.
