### ISSUE TITLE
Prepare a list of ops to rewrite to "deno_core::op2" macro

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#19915]
Once https://github.com/denoland/deno/pull/19897 lands we can start rewriting ops in extension crates to use `op2` macro which should provide performance improvements in many situations.

We need to come up with a list of ops with priority of rewrite, probably HTTP and WS server ops should be tackled first to measure and realize the performance improvements.

**Comment by mmastrac** [comment]
Done :)
