### ISSUE TITLE
Doesn’t load symlinks properly

### ISSUE THREAD

**Issue by rojvv** [denoland/deno#19916]
## What

Currently, if you try running a symbolic link which is linking to an actual module, the relative imports made by the actual module are resolved to the directory of the symbolic link instead of the actual module which makes them link to possibly non-existent files.

## Reproduction

https://github.com/roj1512/deno_issue-19916

**Comment by bartlomieju** [comment]
@roj1512 done!

**Comment by dsherret** [comment]
This would be a breaking change. I'm not sure we should do this because of the performance implications.

**Comment by dsherret** [comment]
Going to close this one because it would be a breaking change.
