### ISSUE TITLE
Error resolving package after cleaning the Deno cache

### ISSUE THREAD

**Issue by oscarotero** [denoland/deno#19928]
I'm having some strange issues with Deno and I suspect they are related with the cache. I'm using Deno v1.35.2 under macOS 12.6.7.

After cloning [Lume repo, (v2 branch)](https://github.com/lumeland/lume/tree/v2) and run the tests with `deno task test`, I get the following error:

```
TypeError: Error: Error resolving package config for 'npm:react@18.2.0/jsx-runtime': [ERR_PACKAGE_PATH_NOT_EXPORTED] Package subpath './jsx-runtime' is not defined by "exports" in '/Users/oscarotero/Library/Caches/deno/npm/registry.npmjs.org/react/18.2.0/package.json' imported from '/Users/oscarotero/Library/Caches/deno/npm/registry.npmjs.org/react/18.2.0/'
```

You can see the error in GitHub Actions: https://github.com/lumeland/lume/actions/runs/5644472919/job/15288428075

If I run again the tests, the error is gone, so I guess it only happens if the package is not cached.

---

Additionally, the first time (with clean cache) the tests are stopped when running `lightningcss` plugin. The second time, the tests are executed entirely. I had strange issues in the past running [`ligthningcss`](https://github.com/parcel-bundler/lightningcss) on Deno after any upgrade, so probably it's also related with cache.

**Comment by bartlomieju** [comment]
@dsherret could you take a look?
