### ISSUE TITLE
npm:send hangs

### ISSUE THREAD

**Issue by akosma** [denoland/deno#19927]
I have found the weirdest bug in an application using Express.js running under Deno: In short, **static files aren't returned. This works under Node.js but not under Deno.**

I've created a sample project containing a "witness" project running the same code under Node.js without any problems. I actually don't know whether this is an Express.js issue, or a Deno problem, or something wrong with my application.

[https://gitlab.com/akosma/express_node_deno](https://gitlab.com/akosma/express_node_deno/)

If this issue is related to Express.js, feel free to close it.

Related issue: https://github.com/expressjs/express/issues/5232

**Comment by akosma** [comment]
If this is a problem related to Express.js, feel free to close this issue.

**Comment by kwhinnery** [comment]
Both examples in your GitLab project work as expected for me (macOS 13.4.1):

- In the `test_ts` folder, if I run `deno run -A index.ts`, the demo app runs and the CSS in the public folder is served. Currently running Deno 1.35.2.
- In the `test_js` folder, if I run `node index.js`, the demo app runs and the CSS in the public folder is served. Currently running Node 20.2.0.

Under what conditions and reproduction steps are you able to see this issue?

**Comment by akosma** [comment]
Thanks for your reply! I'm running them on Fedora 38. That's the only special thing about my setup.

**Comment by akosma** [comment]
Versions:

- Node.js v18.16.1
- deno 1.35.2 (release, x86_64-unknown-linux-gnu)
- v8 11.6.189.7
- typescript 5.1.6

**Comment by kwhinnery** [comment]
I just ran this again and I am now seeing the issue, where I did not the first time (which is also quite strange...) - the behavior I am seeing with the Deno example is that the GET request for the CSS file hangs indefinitely.

**Comment by akosma** [comment]
Yes, that's exactly the issue I have.

**Comment by akosma** [comment]
Here's an interesting thing; I've just run the code on FreeBSD 13.2 (Deno 1.34.3) and now the CSS file is returned BUT the following message appears on the console:

Uncaught Error: Assertion failed

**Comment by akosma** [comment]
![Screenshot from 2023-07-24 21-15-06](https://github.com/denoland/deno/assets/55348/d18e6738-8782-4664-9388-e38b78aa301e)

**Comment by akosma** [comment]
FreeBSD screenshots: Node.js

![Screenshot from 2023-07-24 21-23-51](https://github.com/denoland/deno/assets/55348/823f8175-fd44-4d88-bd85-3e9ec81027f0)

Deno:

![Screenshot from 2023-07-24 21-24-02](https://github.com/denoland/deno/assets/55348/e0d6c9dc-6c6b-4afc-8a2d-0a57c0bf97b2)

**Comment by kwhinnery** [comment]
@mmastrac explicit steps to repro (to save you a a few seconds):

```
git clone https://gitlab.com/akosma/express_node_deno.git
cd express_node_deno/test_ts
deno run -A index.ts
```

Now try to `GET http://localhost:3001/static/css/test.css` - it should hang indefinitely

**Comment by mmastrac** [comment]
I managed to trace it down into the node `send` module where it appears to be failing:

```
TypeScript app listening on port 3001
HTTP id=0 total=1: slab_insert
HTTP id=0 total=1: slab_get
1
HTTP id=0 total=1: slab_get
HTTP id=0 total=1: slab_get
  express:router dispatching GET /static/test.css +2s
  express:router query  : /static/test.css +0ms
  express:router expressInit  : /static/test.css +0ms
  express:router trim prefix (/static) from url /static/test.css +0ms
  express:router serveStatic /static : /static/test.css +0ms
  send stat "/Users/matt/Documents/scripts/http/public/test.css" +1ms
/Users/matt/Documents/scripts/http/public/test.css
  send pipe "/Users/matt/Documents/scripts/http/public/test.css" +1ms
  send accept ranges +0ms
  send cache-control public, max-age=0 +0ms
  send modified Mon, 24 Jul 2023 20:00:13 GMT +0ms
  send etag W/"1a-189897cee63" +1ms
  send content-type text/css +0ms
```

Using `curl -I` to make a HEAD request _does_ appear to work, suggesting it's likely in the `stream` method of the `send` module: https://github.com/pillarjs/send/blob/master/index.js#L703

**Comment by bartlomieju** [comment]
I took at stab at reproducing it and I managed to as well. It appears the problem is that the `end` event is never emitted.

**Comment by bartlomieju** [comment]
Simpler reproduction:
```
import http from 'node:http';
import send  from 'npm:send';

var server = http.createServer(function onRequest (req, res) {
  send(req, "./public/css/test.css")
    .pipe(res)
})

server.listen(3000)

```
`"./public/css/test.css"` can be replaced with any path on the file system. So the problem is definitely within `send` package - most likely caused by bad interaction with out `node:` polyfill.

**Comment by bartlomieju** [comment]
Okay I got to the bottom of the problem - the root cause is that we don't properly polyfill `socket` event in both server and client side of `http` module. In this particular case, the problem is that `socket.writable` is not defined which makes `!socket.writable` condition true. That makes the read stream of the file be immediately destroyed.

**Comment by akosma** [comment]
Just tried on Windows 11 (PowerShell) and got this error when requesting the CSS:

```
PS C:\Users\User\Documents\express_node_deno\test_ts> deno run -A index.ts
TypeScript app listening on port 3001
error: Uncaught TypeError: argument entity must be string, Buffer, or fs.Stats
    at etag (file:///C:/Users/User/AppData/Local/deno/npm/registry.npmjs.org/etag/1.8.1/index.js:83:11)
    at SendStream.setHeader (file:///C:/Users/User/AppData/Local/deno/npm/registry.npmjs.org/send/0.18.0/index.js:880:15)
    at SendStream.send (file:///C:/Users/User/AppData/Local/deno/npm/registry.npmjs.org/send/0.18.0/index.js:620:8)
    at onstat (file:///C:/Users/User/AppData/Local/deno/npm/registry.npmjs.org/send/0.18.0/index.js:725:10)
    at Deno.stat.then.denoErrorToNodeError.syscall (ext:deno_node/_fs/_fs_stat.ts:85:34)
    at eventLoopTick (ext:core/01_core.js:183:11)
PS C:\Users\User\Documents\express_node_deno\test_ts>
```

**Comment by bartlomieju** [comment]
@akosma that appears to be a completely different problem - let's track it in a separate issue.

**Comment by akosma** [comment]
Thanks everyone involved for the fix. Any idea when it will be released to production?

**Comment by bartlomieju** [comment]
It was release in Deno v1.36.0 two weeks ago.

**Comment by akosma** [comment]
Thanks! I missed that release. Much appreciated.
