### ISSUE TITLE
deno task in 1.34.0 and above no longer allows for --inspect=[::0] due to glob-expansion

### ISSUE THREAD

**Issue by vazexqi** [denoland/deno#19942]
This used to work in Deno 1.33. 

```
deno task debug-fly
Task debug-fly deno run --unstable --inspect=[::0]:3366 --allow-env --allow-net --allow-read --allow-write --cached-only --v8-flags=--disallow-code-generation-from-strings ./remote-dev-impl/main.ts
```

It stopped working in Deno 1.34 and 1.35.

```
deno task debug-fly
Task debug-fly deno run --unstable --inspect=[::0]:3366 --allow-env --allow-net --allow-read --allow-write --cached-only --v8-flags=--disallow-code-generation-from-strings ./remote-dev-impl/main.ts
glob: no matches found '/Users/xxx/--inspect=[::0]:3366'
```

I suspect this is due to glob expansion in 1.34 which takes over the [] characters. See https://deno.land/manual@v1.35.2/tools/task_runner#glob-expansion

My use case is that I am running Deno on fly.io. And the suggested way to enable debugging is using --inspect=[::0]:3366 per https://community.fly.io/t/cannot-remote-debug-node-js-app/8306

**Comment by dsherret** [comment]
Sorry, I didn't realize that was previously allowed and it shouldn't have been. You can fix this by adding single quotes around the value like so:

```
deno run --unstable --inspect='[::0]:3366'
```

But actually this is broken atm in Deno < 1.35.2. A workaround is to put single quotes around the entire argument instead: `'--inspect=[::0]:3366'`. I've opened #19944 which will solve this and close this issue (will be released in Deno 1.35.3 this week)
