### ISSUE TITLE
Flaky windows tests

### ISSUE THREAD

**Issue by ry** [denoland/deno#1996]
experienced on windows (mostly?) 

* tests/010_set_interval.test ([example log](https://ci.appveyor.com/project/deno/deno/builds/23312397))
* intervalCancelSuccess ([example](https://ci.appveyor.com/project/deno/deno/builds/23891891))
* intervalOrdering ([example](https://ci.appveyor.com/project/deno/deno/builds/23894120))

**Comment by zekth** [comment]
As i work on win env i can take a look.
