### ISSUE TITLE
Importing a type from google's schema-dts utility types bundles the TS compiler (38.24MB)

### ISSUE THREAD

**Issue by guy-borderless** [denoland/deno#19980]
create a file.ts with:
import type { Accommodation } from "npm:schema-dts"
run: deno info file.ts

file.ts
└─┬ npm:schema-dts@1.1.2 (857.9KB)
  └── npm:typescript@5.1.3 (38.24MB)

the [package.json](https://github.com/google/schema-dts/blob/main/package.json) has only devDependencies.

**Comment by dsherret** [comment]
See the package.json of the published 1.1.2 package (https://www.npmjs.com/package/schema-dts?activeTab=code):

```
"peerDependencies": {
    "typescript": ">=4.1.0"
  },
```

They removed it here, but have not done a release yet: https://github.com/google/schema-dts/commit/a04e43ca245250ad6ed3c9697a31554a3615674a#diff-bde1fda07e99ef7010a134ecda032628b0539e9871f4ddbe3e6b50a6d859d75f
