### ISSUE TITLE
ServerResponse#appendHeader not implemented

### ISSUE THREAD

**Issue by cyco130** [denoland/deno#19993]
The [`appendHeader`](https://nodejs.org/api/http.html#outgoingmessageappendheadername-value) method of `ServerResponse` from the `node:http` module doesn't seem to have been implemented. This makes it impossible to return multiple `Set-Cookie` headers from the server when using `node:http` (I tried a few other ways like passing an array to `setHeader` or calling `writeHead` with an array value for `set-cookie` but none seemed to work).

## System Info
```
Deno version: 1.35.3
OS: macOS 13.4.1
CPU: (10) arm64 Apple M1 Max
```

**Comment by cyco130** [comment]
Temporary workaround (forces `Headers#set` to accept an array, probably not standards-compliant):

```ts
const oldSet = Headers.prototype.set;
Headers.prototype.set = function set(
  this: Headers,
  key: string,
  value: string | string[]
) {
  if (Array.isArray(value)) {
    this.delete(key);
    value.forEach((v) => this.append(key, v));
  } else {
    oldSet.call(this, key, value);
  }
};
```

**Comment by bartlomieju** [comment]
@cyco130 do you have some reproduction code? We have this method implemented here:
https://github.com/denoland/deno/blob/02865cb5a270b9a2229863e83582f2a8b5115b78/ext/node/polyfills/_http_outgoing.ts#L257

**Comment by cyco130** [comment]
The problem is that [`ServerResponse` is not extending `OutgoingMessage`](https://github.com/denoland/deno/blob/02865cb5a270b9a2229863e83582f2a8b5115b78/ext/node/polyfills/http.ts#L1286) as it does on Node (it extends `Writable` instead).

Reproduction is simply:

```ts
import { ServerResponse } from "node:http";
console.assert(new ServerResponse({}).appendHeader !== undefined);
```
