### ISSUE TITLE
Deno is taking a lot of ram

### ISSUE THREAD

**Issue by rahul0x00** [denoland/deno#19991]
OS: Kali Linux
Deno version: v1.35.3

Deno is taking too much memory 
Earlier it was taking around 600mbs of memory(which is relatively high) but I thought upgrading deno will fix it but after upgrading the memory usage increased to around 750mbs 

![Screenshot from 2023-07-31 10-36-12](https://github.com/denoland/deno/assets/104289350/5fea3b70-4210-4200-b852-6f298d8ad59b)

**Comment by bartlomieju** [comment]
What code are you running? It's impossible for us to determine the problem unless we can get a reproduction.

**Comment by bartlomieju** [comment]
The code you write actually has a very big impact on the amount of RAM consumed. With an example program on my machine it's nowhere near 500Mb. Can you share the actual code you are running?

**Comment by rahul0x00** [comment]
Hi, I'm giving another code for your reference which is of total 34 lines and it takes around 264mbs ram 

![image](https://github.com/denoland/deno/assets/104289350/afab99c2-f9f6-4e37-8323-cabd15dd948a)

```javascript
"use strict";


const modal = document.querySelector(".modal");
const overlay = document.querySelector(".overlay");
const btnCloseModal = document.querySelector(".btn--close-modal");
const btnsOpenModal = document.querySelectorAll(".btn--show-modal");

const openModal = function (e) {
  e.preventDefault();
  modal.classList.remove("hidden");
  overlay.classList.remove("hidden");
};

const closeModal = function () {
  modal.classList.add("hidden");
  overlay.classList.add("hidden");
};

btnsOpenModal.forEach((btn) => btn.addEventListener("click", openModal));
// for (let i = 0; i < btnsOpenModal.length; i++) {
//   btnsOpenModal[i].addEventListener("click", openModal);
// }

btnCloseModal.addEventListener("click", closeModal);
overlay.addEventListener("click", closeModal);

document.addEventListener("keydown", function (e) {
  if (e.key === "Escape" && !modal.classList.contains("hidden")) {
    closeModal();
  }
});

```

**Comment by bartlomieju** [comment]
@rahul0x00 this code is using `document` which suggests it's using DOM. Deno doesn't provide DOM API, so I assume you are using some kind of library like https://deno.land/x/deno_dom@v0.1.38. Is that correct?

**Comment by rahul0x00** [comment]
No,I'm using deno plugin for nvim

**Comment by rahul0x00** [comment]
I used [mason.nvim extension](https://github.com/williamboman/mason-lspconfig.nvim)  to install the denols

**Comment by i11010520** [comment]
denols in Nixvim actually eat too much memory, holding nearly 2GB memory even after `lspstop deno`, and there are multiple `deno` processes with not little memory serving.
