### ISSUE TITLE
std/fs/walk has a proposal to skip directories?

### ISSUE THREAD

**Issue by yi-huan** [denoland/deno#20004]
I found that walk only has the option to skip files.
Perhaps add a way to exclude/include directories to improve traversal performance.
Exclude all files/directories under that directory, or include only certain directories.

**Comment by Seally** [comment]
`std` issues should be posted in [denoland/deno_std](https://github.com/denoland/deno_std/issues).

Also, if the directory in question matches something in the skip list, wouldn't it be effectively skipped? My reading of the code is that it checks if the current directory is skipped _before_ calling `Deno.readDir()` on that directory.

**Comment by yi-huan** [comment]
> `std`问题应发布在[denoland/deno_std](https://github.com/denoland/deno_std/issues)中。
> 
> 另外，如果有问题的目录与跳过列表中的某些内容匹配，那么它不会被有效地跳过吗？我对代码的解读是，它在调用该目录_之前_`Deno.readDir()`检查当前目录是否被跳过。

Thanks, that's true, I didn't pay attention to the matching path.
