### ISSUE TITLE
Transpiling deno-flavored-typescript  

### ISSUE THREAD

**Issue by mhanuszh** [denoland/deno#20011]
There is no easy to use, zero config way to transpile deno-flavored-typescript to Javascript.

From the TS side:
The typescript that Deno uses is not compatible with the official version (`.ts` extension, URL imports, etc), so the official `tsc` is out of the question.

On the Deno side:
Deno has an official tool called `deno bundle` which works flawlessly. I only have one problem with it: it bundles. Also, its going away in the near future.

My question is:
Are there any plans on adding a built in method for transpiling Typescript (or even JSX :eyes:) to Javascript? Someting like `deno transpile` that, unlike `deno bundle`, would only have one responsibility.

I believe that this is one of the last components that Deno needs to be completely Batteries Includedᵀᴹ

**Comment by dsherret** [comment]
> Are there any plans on adding a built in method for transpiling Typescript (or even JSX 👀) to Javascript? Someting like deno transpile that, unlike deno bundle, would only have one responsibility.

See https://github.com/denoland/deno_emit/blob/main/js/README.md#transpiling

> The typescript that Deno uses is not compatible with the official version (.ts extension, URL imports, etc), so the official tsc is out of the question.

For just transpiling a single module, that doesn't involve module resolution, so you can use tsc. There is the `ts.transpileModule` function in the ts compiler api. That accepts some transforms which could potentially be used to even modify the module specifiers.

**Comment by bartlomieju** [comment]
I suggested to add `deno transpile` subcommand in internal discussions several times, but there was no support from the team. It's about 100 lines of Rust code to add, since we just need to pipe a few existing pieces together. Keep in mind that besides stripping types and performing JSX transforms there would be no changes to the source code (eg. the import specifiers would still reference `.ts` files).

**Comment by dsherret** [comment]
This one has been discussed
