### ISSUE TITLE
ext/http: Empty reply from serve if null response is provided

### ISSUE THREAD

**Issue by mmastrac** [denoland/deno#20013]
This code currently throws an error and terminates the `Deno.serve` loop, but we should instead be calling the `onerror` handler:

```
Deno.serve(() => null)
```

# Current behaviour

```
Terminating Deno.serve loop due to unexpected error TypeError: Cannot read properties of null (reading 'Symbol(response)')
    at toInnerResponse (ext:deno_fetch/23_response.js:483:18)
    at ext:deno_http/00_serve.js:556:19
    at eventLoopTick (ext:core/01_core.js:183:11)
```

# Expected behaviour 

This should call the `onError` handler, and by default should return 500 errors. The exception passed to `onError` should be a `TypeError` with this message:

```
Deno.serve return value must be a Response or a promise resolving to a Response
```

**Comment by fbaltor** [comment]
Where is this expected behavior defined? In this case the problem is that the [we are trying to access a property of `null`](https://github.com/denoland/deno/blob/21c2c01ebed902c70763bb9319c3ec48c4cb5284/ext/fetch/23_response.js#L483).

**Comment by fbaltor** [comment]
Just complementing the above question: I understand that it is a very sensible, but I would like to improve my understanding of the spec. Is it defined [in the HTTP](https://www.rfc-editor.org/rfc/rfc9110.html#name-error-handling)?

**Comment by mmastrac** [comment]
@fbaltor This particular bug doesn't show up in the spec -- we mainly just want to ensure that Deno.serve doesn't terminate abnormally if someone neglects to return a response from a certain code path.

**Comment by mmastrac** [comment]
Closing as duplicate of https://github.com/denoland/deno/issues/20947 and will be fixed by https://github.com/denoland/deno/pull/21099
