### ISSUE TITLE
Language server - deno_modules - Map remote specifiers to local file paths

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#20015]
The language server should map remote specifiers to local file paths when using `--deno-modules-dir`. This would allow people to do stuff to like "go to definition", end up in a remote module, and start editing right away. At the moment, it shows up as a remote module and is "readonly" in vscode. I believe a way we could do this in the lsp is to map the remote specifiers to the local file paths when dealing with the client, but internally it would still be represented as the remote specifier (so I think we could add this to `LspUrlMap`).

**Comment by bartlomieju** [comment]
I recently investigated https://github.com/denoland/vscode_deno/issues/850 and concluded that if we don't use `deno:/` specifier for "magic mappings" and instead return a `file:/` URL then VSCode will handle it nicely and will allow editing by default.
