### ISSUE TITLE
`deno test` should have options or flags to ignore `Leaking async ops`

### ISSUE THREAD

**Issue by loynoir** [denoland/deno#20021]
`deno test` should have options or flags to ignore `Leaking async ops`

Given 

- I know `npm:undici@5.22.1` `Leaking async ops`

How let below test pass?

```ts
import { describe, it } from "https://deno.land/std@0.196.0/testing/bdd.ts";
import { fetch as undiciFetch } from "npm:undici@5.22.1";

describe("reproduce", () => {
  it("reproduce", async () => {
    await undiciFetch("https://unpkg.com");
    console.log("RESP OK");
  });
});
```

Related

https://github.com/nodejs/undici/issues/2206

**Comment by bartlomieju** [comment]
`Deno.test()` API supports disabling sanitizers: https://deno.land/api@v1.35.3?s=Deno.TestDefinition#prop_sanitizeOps

Is there a specific reason you use `undici` instead of built-in `fetch()` API in Deno?

**Comment by loynoir** [comment]
> Is there a specific reason you use `undici` instead of built-in `fetch()` API in Deno?

Yes, I need `socketPath` and `dnsLookup`.

https://github.com/denoland/deno/issues/17910

https://github.com/denoland/deno/issues/19828

Maybe there is still one or two unit test deno not passed, I forgot accurate number.
