### ISSUE TITLE
--allow-read=DENO_DIR

### ISSUE THREAD

**Issue by alexgleason** [denoland/deno#20061]
There doesn't seem to be a good way to whitelist the DENO_DIR in permissions, which is necessary for remote modules to work.

Even `--allow-read=~/.cache/deno` doesn't work because of the tilde. It wants an absolute path. Best I've found is `--allow-read=/home`, but if the user configures a different `DENO_DIR` even that wouldn't work.

I am using a `deno task start` command that looks like this:

```json5
{
  "tasks": {
    "start": "deno run --allow-read=.,/home --allow-write=data --allow-env --allow-net --unstable --watch src/server.ts"
  },
  // ...
}
```

Users will be self-hosting my software, so I want to make it as easy as possible. For now `--allow-read=/home` seems like the best option, or maybe even just `--allow-read`

I think maybe the DENO_DIR should be exempt from this check.

**Comment by alexgleason** [comment]
I figured out `deno run --allow-read=$HOME/.cache/deno`

It resulted in another problem, `Deno requests read access to <exec_path>.`, which for some reason is resolved by: `deno run --allow-read=$HOME/.cache/deno,$(which deno)` https://github.com/denoland/deno/issues/19864#issuecomment-1641223343

I think this issue is related to https://github.com/denoland/deno/issues/16766

**Comment by alexgleason** [comment]
Deno writes to the tmp directory at `/tmp/deno_cache` without write permissions to it. I believe that's also the correct thing to do for DENO_DIR

**Comment by dandv** [comment]
I've also run into [Deno requesting read access to `node_modules` when using certain NPM packages](https://github.com/denoland/deno/issues/20484) (#20484). 

> Best I've found is `--allow-read=/home`

Allowing blanket read access to all users' home directories is a recipe for data exfiltration. :warning: 

I think we need a better solution here.

**Comment by NiklasRosenstein** [comment]
I've also just run into `Deno requests read access to <exec_path>`. The error suggested I use `--allow-read=<exec_path>`; alas that did not work. It would be nice if it did though to explicitly enable `Deno.execPath()`.

**Comment by bartlomieju** [comment]
@NiklasRosenstein see https://github.com/denoland/deno/pull/29620
