### ISSUE TITLE
`node:http` incorrectly send `Transfer-Encoding: chunked` even if no body is written

### ISSUE THREAD

**Issue by osddeitf** [denoland/deno#20063]
Original issue: #20033.

After debugging for a while, I found out that the HTTP `PUT` request was sent with `Transfer-Encoding: chunked` header, although the body is empty.

Which is different from Nodejs behavior:
The header is only added by the first calling [request.write(chunk)](https://nodejs.org/dist/latest-v18.x/docs/api/http.html#requestwritechunk-encoding-callback):
> If no Content-Length is set, data will automatically be encoded in HTTP Chunked transfer encoding, so that server knows when the data ends. The Transfer-Encoding: chunked header is added.

These are the headers Nodejs would send (`PUT` with no body):
```
Headers {
  connection: "close",
  "content-length": "0",
  "content-type": "text/plain",
  host: "127.0.0.1:8001"
}
```
And these are the headers by Deno:
```
Headers {
  accept: "*/*",
  "accept-encoding": "gzip, br",
  "content-type": "text/plain",
  host: "127.0.0.1:8001",
  "transfer-encoding": "chunked",
  "user-agent": "Deno/1.36.0"
}
```

I tried digging into Deno source code to investigate the issue, and found that currently all `POST`, `PATCH` and `PUT` requests will be considered to have body:
- ext/node/polyfills/http.ts
```typescript
    this._req = core.ops.op_node_http_request(
      this.method,
      url,
      headers,
      client.rid,
      this.method === "POST" || this.method === "PATCH" ||
        this.method === "PUT",
    )
```
- ext/node/ops/http.rs (these lines are useless as a result)
```rust
    // POST and PUT requests should always have a 0 length content-length,
    // if there is no body. https://fetch.spec.whatwg.org/#http-network-or-cache-fetch
    if matches!(method, Method::POST | Method::PUT) {
      request = request.header(CONTENT_LENGTH, HeaderValue::from(0));
    }
```

I don't know how to change the code to fix the issue yet. But I think of 2 ways:
- Add `hasBody` and `hasContentTypeHeader` flags then check them in `request.write` function to add `Transfer-Encoding: chunked` (but I don't know whether the `reqwest` crate supports adding header after started).
- Only start sending `reqwest` after the first call to `request.write`.

I'd appreciate any help to implement this.

**Comment by bartlomieju** [comment]
CC @crowlKats can you take a look and provide some pointers for @osddeitf to fix it?

**Comment by osddeitf** [comment]
The current behavior in nodejs is waiting for the first body chunk, or socket `close()`, until then the headers would be sent:
- lib/_http_outgoing.js
```javascript
  this._header = header + '\r\n';
  this._headerSent = false;

  // Wait until the first body chunk, or close(), is sent to flush,
  // UNLESS we're sending Expect: 100-continue.
  if (state.expect) this._send('');
```
