### ISSUE TITLE
lint and fmt disagree about semicolon when line starts with a bracket

### ISSUE THREAD

**Issue by rotu** [denoland/deno#20078]
Deno fmt and Deno lint get into a fight near statements beginning with a `[` or `(` when semicolons are disabled.[^1]

In each of the below code snippets, the semicolon is not strictly necessary, but `deno fmt` adds it, and `deno lint` flags it as "(no-extra-semi) Unnecessary semicolon.".

```js
;[window.a] = [1]
```

```js
;[1,2,3].forEach(console.log)
```

```js
;({a:window.a} = {a:1})
```

```js
;((x) => {
  console.log(x)
})(1)
```

```js
;({}).toString().forEach(console.log)
```

Here's the `deno.json`:
```jsonc
{ "fmt": { "semiColons": false } }
```

I'm in favor of the semicolon to prevent semantic changes when the preceding line is edited to be an [expression statement](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/Expression_statement), but either `deno lint` should not add it, or `deno fmt` should not complain about it!

Deno version 1.36 on macOS.

[^1]: Unmatched brackets hurt my soul, so here you go: `)`, `]`. You're welcome.

**Comment by dsherret** [comment]
We need to remove no-extra-semi: https://github.com/denoland/deno_lint/issues/1033

**Comment by rotu** [comment]
The `deno fmt` logic seems mostly sound, but I did find a corner case where the empty statement it inserts causes a problem #20089
