### ISSUE TITLE
Is this `navigator.userAgent` expected?

### ISSUE THREAD

**Issue by loynoir** [denoland/deno#20079]
Within Deno Worker

```js
  self.postMessage([null, typeof navigator])
  self.postMessage([null, typeof navigator.userAgent])
```

```js
[ null, "object" ]
[ null, "undefined" ]
```

This breaks the `browser-or-node` assumption

https://github.com/flexdinesh/browser-or-node/blob/master/src/index.js#L20-L21

What does the spec say about Worker `navigator.userAgent`?

Is this expected?

Related https://github.com/flexdinesh/browser-or-node/issues/26

**Comment by bartlomieju** [comment]
According to https://developer.mozilla.org/en-US/docs/Web/API/WorkerNavigator it should be available, so it's a bug on our side.
