### ISSUE TITLE
Relative file paths when remotely fetching files from Azure DevOps

### ISSUE THREAD

**Issue by michieltebraake** [denoland/deno#20088]
I am trying to move my repository from GitHub to Azure DevOps, and have run into the problem that Deno can no longer fetch all my files correctly from remote.

For example, if I have an index.ts file containing `import { client } from './client.ts'`

Then for GitHub we can run:
`deno cache https://raw.githubusercontent.com/organisation/repo/main/index.ts`
And deno will load this next file from `https://raw.githubusercontent.com/organisation/repo/main/client.ts`

Unfortunately, Azure DevOps uses a different [REST API URL format](https://learn.microsoft.com/en-us/rest/api/azure/devops/?view=azure-devops-rest-7.1), so the deno cache command turns into:
 `deno cache https://dev.azure.com/organisation/project/_apis/sourceProviders/TfsGit/filecontents?repository=repo&api-version=7.0&commitOrBranch=main&path=/index.ts"`
But deno then tries to fetch the next file from `https://dev.azure.com/organisation/project/_apis/sourceProviders/TfsGit/client.ts`, which is the incorrect URL.

Is there a way to make Deno only change the path parameter of the URL?

**Comment by lucacasonato** [comment]
No, this is not possible. I suggest you run a small proxy server in front of Azure DevOps to rewrite the paths
