### ISSUE TITLE
Remote `--inspect` doesn't work if remote port != local port

### ISSUE THREAD

**Issue by josephrocca** [denoland/deno#20087]
To reproduce:

1. Spin up an Ubuntu 22.04 machine on DigitalOcean
2. Install Deno: `curl -fsSL https://deno.land/x/install/install.sh | sh`
3. Create a `main.js` file: `setInterval(() => { console.log("hello"); }, 1000);`
4. Run `/root/.deno/bin/deno run --inspect=127.0.0.1:9487 main.js` on the machine
5. Run this on your local machine: `ssh -N -L 9229:127.0.0.1:9487 root@xxx.xxx.xxx.xxx`
6. Go to `chrome://inspect` on your local machine, and click "inspect" on the Deno remote target
7. Observe that there are no "hello" logs, or ability to see source code / debugger / etc.
8. Install Node.js to confirm it's specifically a Deno issue: `curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash - && sudo apt-get install -y nodejs`
9. Run `node --inspect=127.0.0.1:9487 main.js`
10. Go to  `chrome://inspect`, inspect the Node.js remote target and you'll see the "hello" logs.

**Comment by josephrocca** [comment]
@bartlomieju Apologies for the ping - just wondering if there's any hope of this working some time soon? Use case: Need to find performance bottleneck in my production server. Very hard to simulate real load locally in my case.

**Comment by bartlomieju** [comment]
Hey @josephrocca, I actually bookmarked this issue but I haven't had time yet to investigate. We can certainly fix it, but I can't promise an ETA right now. I need to replicate your setup and see where the problem lies.

**Comment by bartlomieju** [comment]
@josephrocca if you connect to the debugger and put some statements in the console are they evaluated at all?

**Comment by josephrocca** [comment]
@bartlomieju No - when I press enter, the command just disappears and the console remains completely blank.

Also, RE:

> I need to replicate your setup

I was guessing that this problem would happen with any setup - have you managed to get remote inspect working at all with the latest Deno version? My local machine is PopOS/Ubuntu 22.04, fwiw. If it's working for you with a particular local or remote OS combination, please let me know so I can try to help investigate.

I've also just tried `--inspect-brk` and I observe the same problem. It's definitely "detecting" the connection, since it appears in `chrome://inspect` after running the `ssh` command, but it seems that no data is being transferred, unlike in the exactly-the-same-except-using-Node.js case.

**Comment by mmastrac** [comment]
I reproduced this with a Raspberry Pi running https://github.com/LukeChannings/deno-arm64.

It appears that Deno is not a fan of the local/remote port mismatch and it returns what it believes the local port is rather than the port in the `Host` header:

```
[{"description":"deno","devtoolsFrontendUrl":"devtools://devtools/bundled/js_app.html?ws=127.0.0.1:9487/ws/3dc267a9-6afc-432c-befc-c39365f5994a&experiments=true&v8only=true","faviconUrl":"https://deno.land/favicon.ico","id":"3dc267a9-6afc-432c-befc-c39365f5994a","title":"deno - main [pid: 125577]","type":"node","url":"file:///tmp/main.ts","webSocketDebuggerUrl":"ws://127.0.0.1:9487/ws/3dc267a9-6afc-432c-befc-c39365f5994a"}]
```

**Comment by mmastrac** [comment]
@josephrocca as a workaround until this PR lands, just ensure that the remote and local port numbers match.

**Comment by josephrocca** [comment]
Thank you! :pray:
