### ISSUE TITLE
`userInfo()` from `node:os` fails on Windows

### ISSUE THREAD

**Issue by ubdjshdb** [denoland/deno#20106]
Can be reproduced on Deno 1.36.0:

```
> import { userInfo } from "node:os";
undefined
> userInfo()
Uncaught TypeError: Assignment to constant variable.
    at userInfo (node:os:218:13)
    at <anonymous>:2:1
```

Looks like variables `uid` and `gid` are marked as const but then reassigned: https://github.com/denoland/deno/blob/03e963f57831367a39996c7d88bc9875e97d52d7/ext/node/polyfills/os.ts#L323-L329

**Comment by mmastrac** [comment]
Fixed by #20165
