### ISSUE TITLE
npm: package import wont resolve files without extensions

### ISSUE THREAD

**Issue by jsyme222** [denoland/deno#20105]
**Issue**
Importing the package `@indigo-labs/dexter` with the npm specifier leads to error:

```
Uncaught TypeError: Could not resolve './constants' from 'file:///home/<user>/.cache/deno/npm/registry.npmjs.org/@indigo-labs/dexter/4.0.1/build/index.js'.
```

Upon examination the package clearly has the `. /constants.js` but it won't resolve as it's being imported as `./constants` without the extension. 

**Reproduce**
By opening a deno console and importing the package:
```js
import { Dexter } from "npm:@indigo-labs/dexter"
console.log(Dexter)
```

**Comment by sigmaSd** [comment]
There is `constant.js` the library is importing like `import './constant'` (without extension) 
It have `type="module"` in package.json so I guess deno maybe still doesn't handle this

**Comment by jsyme222** [comment]
> There is `constant.js` the library is importing like `import './constant'` (without extension) 
> It have `type="module"` in package.json so I guess deno maybe still doesn't handle this

Exactly. Is this a known issue? Or am I missing something?

**Comment by lucacasonato** [comment]
This also doesn't work in Node. ESM in NPM packages requires fully qualified specifiers. 

https://nodejs.org/api/esm.html#mandatory-file-extensions
