### ISSUE TITLE
 language server errors on go-to-definition for `esm.sh` url

### ISSUE THREAD

**Issue by scarf005** [denoland/deno#20113]
related: #18460

https://github.com/denoland/deno/assets/54838975/730a7a6f-616f-4da0-97bc-8c58b7db8e2a

while first go-to-definition to `d.ts` works (ts -> d.ts), nested go-to-definition will not work with following error (ts -> d.ts -> d.ts):

> The editor could not be opened due to an unexpected error: Unable to resolve text model content for resource `deno:/https/esm.sh/v130/kysely%400.26.1/dist/cjs/parser/reference-parser.d.ts`

Versions:
- vscode: 1.81.0
- deno 1.36.0 (release, x86_64-unknown-linux-gnu)
- v8 11.6.189.12
- typescript 5.1.6

**Comment by nayeemrmn** [comment]
I think this was fixed by #20867. @scarf005 If it still occurs in Deno canary or the upcoming 1.37.2, please let me know here.
