### ISSUE TITLE
`--unstable` flag does not propagate to workers during `deno test`

### ISSUE THREAD

**Issue by israelidanny** [denoland/deno#20118]
This is a new issue, I'm not 100% from which version onwards. I have a worker that uses `WebSocketStream`. In this worker, I have as recommended by docs:
```
/// <reference no-default-lib="true" />
/// <reference lib="deno.worker" />
```

I just updated deno to v1.36.0, and my tests started failing with errors like:
```
my test ... FAILED (9ms)
error: Uncaught (in worker "") TS2304 [ERROR]: Cannot find name 'WebSocketStream'.
const wss = new WebSocketStream(url, { signal: abortController.signal });
                ~~~~~~~~~~~~~~~
    at file:///Users/danny/src/caveworld-deno-bug/mod.ts:11:17

TS2304 [ERROR]: Cannot find name 'WebSocketStream'.
const createClose = (wss: WebSocketStream) => (options?: WebSocketCloseInfo) => wss.close(options);
                          ~~~~~~~~~~~~~~~
    at file:///Users/danny/src/caveworld-deno-bug/src/utils.ts:6:27

TS2304 [ERROR]: Cannot find name 'WebSocketCloseInfo'.
const createClose = (wss: WebSocketStream) => (options?: WebSocketCloseInfo) => wss.close(options);
                                                         ~~~~~~~~~~~~~~~~~~
    at file:///Users/danny/src/caveworld-deno-bug/src/utils.ts:6:58

TS2304 [ERROR]: Cannot find name 'WebSocketStream'.
  const wss = new WebSocketStream(url, { signal: abortController.signal });
                  ~~~~~~~~~~~~~~~
    at file:///Users/danny/src/caveworld-deno-bug/src/utils.ts:10:19
```

Upon some investigation, I found that removing the above triple slash reference lines "fixes" the errors. This happens specifically only inside of a test. The unstable flag does not propagate to the worker if the reference triple-slash comment directives are used.

Here is an elementary reproduction.

mod.ts:
```deno
/// <reference no-default-lib="true" />
/// <reference lib="deno.worker" />
 
const url = "ws://127.0.0.1:8080";
const wss = new WebSocketStream(url);

```

mod.test.ts:
```deno
Deno.test("my test", async () => {
  new Worker(
    new URL("./mod.ts", import.meta.url).href,
    {
      type: "module",
    },
  );
})
```

Running `deno run --unstable mod.ts` on the above will work.

Running `deno test --unstable --allow-read --allow-net` will yield:
```
running 1 test from ./mod.test.ts
my test ...Check file:///Users/danny/src/caveworld-deno-bug/mod.ts
 FAILED (23ms)
error: Uncaught (in worker "") TS2304 [ERROR]: Cannot find name 'WebSocketStream'.
const wss = new WebSocketStream(url);
                ~~~~~~~~~~~~~~~
    at file:///Users/danny/src/caveworld-deno-bug/mod.ts:5:17
```

However, if you remove the triple-slash directives in `mod.ts`, the test will work.

**Comment by dsherret** [comment]
You'll need to add the unstable types since they've been removed by "no-default-lib":

```ts
/// <reference lib="deno.unstable" />
```

**Comment by israelidanny** [comment]
@dsherret Hmm, alright. This is new behavior? Because I've had an app run in production for half a year now and all tests always passed.

**Comment by bartlomieju** [comment]
> @dsherret Hmm, alright. This is new behavior? Because I've had an app run in production for half a year now and all tests always passed.
> 
> P.S Thanks, it does work!

Type-checking by default in `deno run` has been disabled for about 10 months now.
