### ISSUE TITLE
Deno test resource ops leak into other tests

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/deno#20146]
Just ran into this error [on the Fresh CI](https://github.com/denoland/fresh/actions/runs/5846877575/job/15852522770?pr=1631):

```sh
 rendering custom _500.tsx page for default handlers => ./tests/main_test.ts:857:6
error: Leaking resources:
  - A fetch response body (rid 109) was created before the test started, but was consumed during the test. Do not close resources in a test that were not created during that test.
```

[The test](https://github.com/denoland/fresh/blob/4a314b02f085a3d76ccda389e78834f4ca38f4ef/tests/main_test.ts#L857) starts a server and does two fetches.

```tsx
Deno.test("rendering custom _500.tsx page for default handlers", async (t) => {
  await withFresh("./tests/fixture_custom_500/main.ts", async (address) => {
    await t.step("SSR error is shown", async () => {
      const resp = await fetch(address);
      assertEquals(resp.status, Status.InternalServerError);
      const text = await resp.text();
      assertStringIncludes(text, "Custom 500: Pickle Rick!");
    });

    await t.step("error page is shown with error message", async () => {
      const doc = await fetchHtml(address);
      const text = doc.querySelector(".custom-500")?.textContent!;
      assertStringIncludes(text, "Custom 500: Pickle Rick!");
    });
  });
});
```

Both of these fetches are done within the test. The sever startup code is a pretty bare bones `Deno.serve` call with `port=0` which opens on a random port.

```tsx
const server = Deno.serve({
  port: 0,
  signal: abort.signal,
  onListen: (info) => {
    def.resolve(`http://${info.hostname}:${info.port}`);
  },
}, ctx.handler());
```

This makes me a bit confused as to where the response body was consumed from an unrelated test and why `deno --test` threw that error.

**Comment by lino-levan** [comment]
I've been experiencing a lot of weird behavior around test steps and ops leaking recently. If I have time I'll go check if there was a regression from a previous version.

**Comment by lucacasonato** [comment]
This was an issue in Fresh
