### ISSUE TITLE
Ignore type imports when trying to fetch the module graph.

### ISSUE THREAD

**Issue by jespertheend** [denoland/deno#20149]
Deno attempts to fetch or parse modules that are only pointed at via either an `import type` statement or via an import statement in a JSDoc comment.

For example:
```ts
import type {Foo} from "https://responder.deno.dev/?status=404&delay=3000";

const message : Foo = "This file runs just fine, but it takes long before execution starts.";
console.log(message);
```

This example is a bit forced, but I'm frequently running into issues like these.
Some more real world examples are:
- esm.sh frequently points to 500 status codes when node functionality is not implemented yet.
- Right now, I'm trying to `import {Vec2} from "https://deno.land/x/renda@v0.1.0/src/mod.js";`, resulting in a request to `https://deno.land/x/renda@v0.1.0/studio/deps/rollup-plugin-resolve-url-objects.js` every time I run the script.

On top of this, files might import a single type from somewhere, which then in turn imports a huge amount of files. Renda is a good example of this. Renda itself doesn't import any third party modules, so it's pretty small. But there's a handful of type imports which in turn use types from TypeScript, Rollup and a bunch of other stuff. So the amount of downloaded and parsed files is significantly larger than the amount of code that is actually needed.

There are a few other issues that could potentially get solved from this as well. Or at the very least they are related:
#16551
#15788
#17658
There's another that I can't seem to find right now, but I remember trying to improve the speed of one of my scripts, only to conclude that 500ms of startup time was wasted on trying to parse unused modules.

**Comment by dsherret** [comment]
@jespertheend I believe we are already doing this. That file will execute immediately for me with `deno run`. Perhaps you are using a sub command with type checking?

```
> deno run asdf.ts
This file runs just fine, but it takes long before execution starts.
V:\scratch
> deno run --check asdf.ts
error: Module not found "https://responder.deno.dev/?status=404&delay=5000".
    at file:///V:/scratch/asdf.ts:1:24
```

**Comment by jespertheend** [comment]
Huh, that's strange. I could swear I was able to reproduce it with those exact steps.
I think I may have been on an older version, because I can only reproduce it when downgrading now. Sorry about that!

On another note #15788 seems fixed now too!
