### ISSUE TITLE
Cannot read properties of undefined (reading 'Promise')

### ISSUE THREAD

**Issue by custompro98** [denoland/deno#20142]
node-fetch v2.6.12 re-exports `global.Promise` in its [underlying code](https://github.com/node-fetch/node-fetch/blob/8bc3a7c85f67fb81bb3d71c8254e68f3b88e9169/src/index.js#L400).

This causes `Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'Promise')` when running `deno task start` in a Fresh (v1.3.1) application.

This is in the context of trying to import `npm:@libsql/kysely-libsql` (https://github.com/libsql/kysely-libsql) to use [Kysely](https://github.com/kysely-org/kysely) and [Turso](https://turso.tech/) together as the database for a Deno Fresh application.

**Comment by marvinhagemeister** [comment]
Transfering this issue to the deno repository as it's an issue with the npm compatibility layer and not with Fresh itself.

**Comment by custompro98** [comment]
@lucacasonato This does NOT reproduce if I run `main.ts` instead of `dev.ts`.

Thank you for the response and for linking the issues together. Apologies for not realizing they were related. Happy to close in favor of #20028.
