### ISSUE TITLE
JUnit: Include full test location

### ISSUE THREAD

**Issue by skycoop** [denoland/deno#20156]
The JUnit `testcase` attribute supports providing the file path and line number of a test which can help with debugging by taking developers to the exact test. 
```xml
<testcase name="testCase1" classname="Tests.Registration" assertions="2" time="2.436" file="tests/registration.code" line="24" />
```

**Comment by bartlomieju** [comment]
I believe this needs to use `quick_junit::TestCase.add_properties` and add `file` and `line` properties that can be taken from `TestDescription.location`. This should be a really easy fix.

**Comment by lucacasonato** [comment]
Make sure to check whether line and column numbers are 0 or 1 aligned.

**Comment by armichaud** [comment]
Hey Deno! I'm new to open source contributing, found this while looking for `good first issues`. I'm putting together a PR now. 

@lucacasonato , from what I can tell the col / line numbers are 1 aligned.
