### ISSUE TITLE
Optimize events implementation

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#20167]
While working on https://github.com/denoland/deno/pull/20153 @mmastrac discovered that our implementation of `Event` and related APIs is very slow:
![image (4)](https://github.com/denoland/deno/assets/13602871/dd00c15f-9532-4552-9685-d0d02a7c3dbc)

We should do some benchmarks to see what is the cost of:
- creating an instance of `Event` class
- adding event listener using `addEventListener` API
- dispatching an event using `dispatchEvent`

Once we have baseline measurements we should figure out where we are losing time and fix each case one-by-one.

**Comment by bartlomieju** [comment]
@marcosc90 would this be something you'd be interested to take a look at? :)

**Comment by marcosc90** [comment]
Sure I'll take a look @bartlomieju!

**Comment by bartlomieju** [comment]
@marcosc90 you can get these results if you build off of https://github.com/denoland/deno/commit/41cad2179fb36c2371ab84ce587d3460af64b5fb commit, create `empty.js` (which is an empty file :D) and run:
```
./target/release/deno run --v8-flags='--prof,--prof-sampling-interval=10' ./empty.js
```
You can then process this file like so:
```
node --prof-process --preprocess isolate-0x158050000-48087-v8.log | grep -v "Testing v8 version different from logging version" > /tmp/prof.json
```
And view the file at https://v8.github.io/tools/head/profview/.

That was a pretty exotic setup and I believe if you just have something like
```
Deno.bench(function eventListener() {
  foo.addEventListener("foo", () => {});
});
```
that should give a pretty good result as well.

**Comment by marcosc90** [comment]
Getting `Segmentation fault (core dumped)` with that command. I'll use `Deno.bench` for now

**Comment by bartlomieju** [comment]
> Getting `Segmentation fault (core dumped)` with that command. I'll use `Deno.bench` for now

Ouch, that's concerning :/

**Comment by bartlomieju** [comment]
We had several PRs that improved the performance of Event class. I'm gonna close this issue for now and open a new one if we spot any more problems.
