### ISSUE TITLE
Puppeteer issues

### ISSUE THREAD

**Issue by oscarotero** [denoland/deno#20179]
The post to [announce the release of Deno 1.35](https://deno.com/blog/v1.35) says that `npm:puppeteer` is now supported.

I've been doing some tests and found a couple of issues with this package. This is the code I'm using:

```js
import puppeteer from "npm:puppeteer@21.0.3";
import { Cache } from "npm:@puppeteer/browsers@1.6.0";

const options = {
  browser: "chrome",
  cacheDirectory: Deno.cwd() + "/_puppeteer",
};

// Install the binary if it's not already installed
try {
  await Deno.stat(options.cacheDirectory);
} catch (error) {
  if (error instanceof Deno.errors.NotFound) {
    const command = new Deno.Command(Deno.execPath(), {
      args: ["run", "-A", "npm:puppeteer@21.0.3/install.js"],
      stdout: "inherit",
      env: {
        PUPPETEER_CACHE_DIR: options.cacheDirectory,
        PUPPETEER_PRODUCT: options.browser,
      },
    });

    await command.output();
  } else {
    throw error;
  }
}

// Search the binary path
const cache = new Cache(options.cacheDirectory);

const installedBrowser = cache.getInstalledBrowsers().find((info) => {
  return info.browser === options.browser;
});

if (!installedBrowser) {
  throw new Error(`Browser ${options.browser} not installed`);
}

// Launch a browser
const browser = await puppeteer.launch({
  product: options.product,
  headless: "new",
  executablePath: installedBrowser.executablePath,
});

// Open a page
const page = await browser.newPage();
await page.setContent(`
<html>
  <head>
    <title>Testing</title>
  </head>
  <body>
    <h1>Title</h1>
  </body>
</html>
`);

// Evaluate some code
const result = await page.evaluate(() => {
  return Array.from(document.querySelectorAll("title, h1")).map((el) =>
    el.outerHTML
  );
});
console.log(result);

// Close everything
page.close();
await browser.close();
```

After running this code, I see the following:

```sh
➜  puppeteer deno run -A main.js
Warning: Not implemented: ClientRequest.options.createConnection
[ "<title>Testing</title>", "<h1>Title</h1>" ]
```

and the script keeps running for 30 seconds or so and cannot be closed, even with `Ctrl + C`. I'm not sure if the missing support for `ClientRequest.options.createConnection` makes the script to keep alive for 30 seconds after finishing.

I've tried the same script in Node (with some modifications) and it everything run smoothly:

```js
// main.mjs

import { cwd } from "node:process";
import puppeteer from "puppeteer";
import { Cache } from "@puppeteer/browsers";

const options = {
  browser: "chrome",
  cacheDirectory: cwd() + "/_puppeteer",
};

const cache = new Cache(options.cacheDirectory);

const installedBrowser = cache.getInstalledBrowsers().find((info) => {
  return info.browser === options.browser;
});

if (!installedBrowser) {
  throw new Error(`Browser ${options.browser} not installed`);
}

const browser = await puppeteer.launch({
  product: options.product,
  headless: "new",
  executablePath: installedBrowser.executablePath,
});


const page = await browser.newPage();
await page.setContent(`
<html>
  <head>
    <title>Testing</title>
  </head>
  <body>
    <h1>Title</h1>
  </body>
</html>
`);

const result = await page.evaluate(() => {
  return Array.from(document.querySelectorAll("title, h1")).map((el) =>
    el.outerHTML
  );
});
console.log(result);

await page.close();

await browser.close();
```

**Comment by guillaume86** [comment]
I noticed the same issues, the warning is not preventing puppeteer to work, but the 30s delay in finishing the process is annoying.

**Comment by guillaume86** [comment]
Thanks to https://github.com/denoland/deno/issues/20868#issuecomment-1919952052 ,
I can confirm that the issue originates from the npm `ws` package, and just replacing it with the Deno standard WebSocket fixes the issues (both the warning and exit delay).

Now what would be the proper way to get this fixed upstream? Is there a mecanism for Deno specific overrides? Or the only solution is a fork? @dsherret

**Comment by marvinhagemeister** [comment]
Related https://github.com/denoland/deno/issues/19507

**Comment by kt3k** [comment]
Also seems related to https://github.com/puppeteer/puppeteer/issues/11839

The snippet given in the above issue (which patches `NodeWebSocketTransport.create`) seems working around this issue.

**Comment by kt3k** [comment]
The below script reproduces the situation where `ws.close()` takes 30 seconds before finishing only using `ws` package.

```js
import WebSocket from "npm:ws@8.13.0";

const server = `
  Deno.serve({ port: 3000 }, (req) => {
    if (req.headers.get("upgrade") != "websocket") {
      return new Response(null, { status: 501 });
    }
    const { socket, response } = Deno.upgradeWebSocket(req);
    socket.addEventListener("message", (event) => {
      socket.send("pong");
    });
    return response;
  });
`;

const cmd = new Deno.Command("deno", { args: ["eval", server] });

const p = cmd.spawn();

setTimeout(() => {
  const ws = new WebSocket("ws://localhost:3000");
  ws.addEventListener("message", async (ev) => {
    console.log("received", ev.data);
    console.log("killing the server");
    p.kill();
    setTimeout(() => {
      console.log("closing client websocket");
      ws.close();
    }, 1000);
  });
  ws.addEventListener("open", () => {
    console.log("sending ping")
    ws.send("ping");
  });
}, 2000);
```

`ws.close()` tries to send some data to the peer, but if the peer is already gone, that request seems stuck (the resource used is `fetchUpgradedStream`).

`ws` package set 30 seconds timeout for that call here https://github.com/websockets/ws/blob/019f28ff1ffddfcdc428d1de5ecd98648057a2ab/lib/websocket.js#L332
That finishes the stalled write request after 30 sec

**Comment by kt3k** [comment]
Looks like we don't propagate the closed state of `hyper::upgrade::Upgraded` to the paired `tokio::io::DuplexStream` in `op_node_http_fetch_response_upgrade`, and that seems causing the `Deno.TcpConn`/`net.Socket` writable even after the actual websocket connection is closed. I think I found a fix for it. I'll send a PR soon.
