### ISSUE TITLE
feat: `deno fmt` and `deno lint` should ignore files set in `.gitignore`

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/deno#20185]
Would be nice if `deno fmt` and `deno lint` were aware of `.gitignore` and would ignore files/paths listed in there. Currently, we have to duplicate those paths in the exclude rules for `deno fmt` and `deno lint`.

Related https://github.com/denoland/fresh/issues/1652

**Comment by marvinhagemeister** [comment]
Just checked with `prettier` and `eslint` and both respect `.gitignore` automatically.

**Comment by bartlomieju** [comment]
If we decide to do it, we should probably use [ignore](https://github.com/BurntSushi/ripgrep/tree/master/crates/ignore) crate.

**Comment by dsherret** [comment]
I think we shouldn't introduce additional config files. Although it's convient, it really ups the complexity of things. Also, although git is now more widespread there are still other version control systems.

**Comment by bartlomieju** [comment]
Done in Deno v2.1: https://github.com/denoland/deno/pull/26897

https://deno.com/blog/v2.1#formatting-and-linting-improvements
