### ISSUE TITLE
`deno fmt` line ending behaviour

### ISSUE THREAD

**Issue by JakeOShannessy** [denoland/deno#20194]
Running `deno fmt` will convert CRLF to LF, even if the file is otherwise fine. This may be the intended behaviour (#4709 and #11359 seem to suggest that). As points of comparison `cargo fmt` preserves line endings and I believe `go fmt` also changes CRLF to LF.

The most immediate pain is with git. To make this work with git we'd have to turn off line ending conversion which risks committing CRLF endings into a repo.

Is this a conscious decision or simply default? If it is conscious decision is it something that could be configured?

When formatting via the VS Code extension this doesn't seem to occur.

**Comment by dsherret** [comment]
> The most immediate pain is with git. To make this work with git we'd have to turn off line ending conversion which risks committing CRLF endings into a repo.

I suggest adding the following to the `.gitattributes` file:

```
* eol=lf
```

This will force everyone to check out the code with `lf` line endings. That said, ideally Windows users should have `core.autocrlf` turned off. I believe they can do that globally by running `git config --global core.autocrlf false`

> Is this a conscious decision or simply default? If it is conscious decision is it something that could be configured?

It's much simpler to use the same line ending on all platforms as it works fine on Windows (I'm a Windows user). It's a better world when everyone uses the same character for line endings.

**Comment by JakeOShannessy** [comment]
The problem is that `git config --global core.autocrlf false` means that files won't be normalised and potentially CRLF files could be committed (resulting in a mix, the worst case).

It would be much nicer if everything was LF only, but we still keep ending up with CRLF files.

Taking another look at `cargo fmt`, turns out it does convert to LF, but only when modifying files. Those that don't need changes are left untouched, it doesn't do line ending conversion only.

**Comment by JakeOShannessy** [comment]
Looks like deno's behaviour is fairly standard (except for touch all files) so this can be closed.

**Comment by sherviniv** [comment]
I am having an issue with the source because the end of the line is CRLF. When I run deno fmt, it changes all of the eol to LF. I added * eol=crlf to .gitattributes, but it's not working.

**Comment by canhbk** [comment]
> I am having the same issue because the end of the line is CRLF in my source code(I'm using Windows). When I run deno fmt, it changes all of the eol to LF. I added * eol=crlf to .gitattributes, but it's not working.

me too

**Comment by dsherret** [comment]
You need to set the eolf to lf and not crlf. Then I think you need to run `git add --renormalize .` to update the local files based on the new changes to the .gitattributes.

**Comment by PopovMP** [comment]
|  You need to set the eolf to lf and not crlf. 
 
 Actually, we need CRLF. The Deno formatter must obey the users' settings.

**Comment by dsherret** [comment]
Why?

**Comment by PopovMP** [comment]
CRLF is the standard line ending under Windows. If Deno claims Windows support, it should allow us to use the Windows' standard line ending.

The fact I'm writing here means I'm already frustrated enough.

See what ChatGPT tells on the subject:

Yes, deno fmt respects the settings specified in the [.editorconfig](vscode-file://vscode-app/c:/Users/miros/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html) file. If you have configured your [.editorconfig](vscode-file://vscode-app/c:/Users/miros/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html) file to use CRLF line endings, deno fmt will format your files accordingly.

**Comment by dsherret** [comment]
I use Windows and only program with LF. CRLF is an unnecessary complication that should be phased out. LF only works everywhere nowadays so there’s no reason to program with CRLF.

Make the switch to using LF only and things will be better. No need to be frustrated.

**Comment by gewoonwoutje** [comment]
Though I'm 100% in favor of phasing out CRLF, the commonly recommended setting for git on windows is to set `core.autocrlf` to `true`. There's currently not a great way to configure `deno fmt` to work well with that setting. Setting it to `auto` or `system` seems not to make any difference (and the difference between `system` and `auto` is not clear to me).

How would you recommend setting the formatter when `core.autocrlf = true` is a given?
