### ISSUE TITLE
How can I detect if my deno shell script is running through a pipe?

### ISSUE THREAD

**Issue by jerrygreen** [denoland/deno#20207]
Similar question to this one, except the guy there asks about bash:

- https://stackoverflow.com/questions/911168/how-can-i-detect-if-my-shell-script-is-running-through-a-pipe

In bash, it is possible to tell if output goes to pipe with `if [ -t 1 ]` like this:

```bash
if [ -t 1 ] ; then echo terminal; else echo "not a terminal"; fi # produces "terminal"
(if [ -t 1 ] ; then echo terminal; else echo "not a terminal"; fi) | cat # produces "not terminal"
```

Is it possible to determine if the output of Deno script being piped, like this, in Deno?

So I could write additional logic around this. For example, colorize output when displayed directly to terminal. But when piped into file for example, or to another command, – display raw output as it is, no shinnies involved. Or other cases, where by default this cli-util writes to file, but if piped, – only writes to stdout so user himself can tell where he wants to save his output. Etc.

**Comment by nayeemrmn** [comment]
`Deno.isatty(Deno.stdout.rid)`

**Comment by jerrygreen** [comment]
Indeed! Thank you.
