### ISSUE TITLE
Nessie's `rollback all` stopped working after upgrading Deno to 1.36.1

### ISSUE THREAD

**Issue by bakasmarius** [denoland/deno#20209]
After upgrading Deno to 1.36.1, Nessie's `rollback all` command does not work anymore, it throws this error:
```
deno run --allow-net --allow-read --unstable --allow-env https://deno.land/x/nessie@2.0.10/cli.ts rollback all
error: missing field `now` at line 21 column 1
    at https://deno.land/x/mysql@v2.10.3/deps.ts:2:33 
```

Downgrading Deno to 1.36.0 solves this issue and everything works as before:
```
deno upgrade --version 1.36.0
Downloading https://github.com/denoland/deno/releases/download/v1.36.0/deno-x86_64-pc-windows-msvc.zip
Deno is upgrading to version 1.36.0
Upgraded successfully

deno run --allow-net --allow-read --unstable --allow-env https://deno.land/x/nessie@2.0.10/cli.ts rollback all
...
Rollback completed in 0.08 seconds
```

**Comment by tilemanrenovations** [comment]
Allow me a different word for allow Grant. Grant will work. If you can come up with a better word go for it but it's not understanding what allow is and I don't want to use a big word like approve.

**Comment by tilemanrenovations** [comment]
I was that the only problem today everything else going good?

**Comment by dsherret** [comment]
This is the same issue as https://github.com/denoland/deno/issues/20211

A release will go out tomorrow. You might be able to get around it by running with `--reload` once.
