### ISSUE TITLE
Bug in dependency inspector

### ISSUE THREAD

**Issue by mathiasbynens** [denoland/deno#2021]
@cdata [reported](https://twitter.com/0xcda7a/status/1112108089568722944) the following resolution error for a module graph that fully resolves in Chrome:

```
$ deno --info https://unpkg.com/@google/model-viewer@0.1.2/lib/model-viewer.js?module
Downloading https://unpkg.com/@google/model-viewer@0.1.2/lib/model-viewer.js?module
Downloading https://unpkg.com/@google/model-viewer@0.1.2/lib/features/animation.js?module
Downloading https://unpkg.com/lit-element@^2.0.0?module
Downloading https://unpkg.com/lit-html@^1.0.0?module
Downloading https://unpkg.com/lib/default-template-processor.js?module
Cannot resolve module "./lib/default-template-processor.js?module" from "https://unpkg.com/lit-html@^1.0.0?module"
```

**Comment by cdata** [comment]
This was tested on a Mac, if it helps.

**Comment by kt3k** [comment]
This seems like the same bug as [this one](https://github.com/denoland/deno/issues/1742).

`https://unpkg.com/lit-html@^1.0.0?module` redirects to `https://unpkg.com/lit-html@1.0.0/lit-html.js?module`, but deno tries to resolve `./lib/default-template-processor.js?module` from `https://unpkg.com/`, not `https://unpkg.com/lit-html@1.0.0/`.

**Comment by ry** [comment]
Unfortunately still broken
```
> ./target/debug/deno https://unpkg.com/@google/model-viewer@0.1.2/lib/model-viewer.js?module
https://unpkg.com/lit-element@2.1.0/lib/updating-element.js?module:74:37
export class UpdatingElement extends HTMLElement {
                                     ^
Uncaught ReferenceError: HTMLElement is not defined
    at https://unpkg.com/lit-element@2.1.0/lib/updating-element.js?module:74:38
```
But it's no longer the redirect error - we just don't have HTMLElement in there...

**Comment by kt3k** [comment]
I think this issue can be closed because `--info` option now works for the given url `https://unpkg.com/@google/model-viewer@0.1.2/lib/model-viewer.js?module` and the entire dependency tree is visible. ( [log](https://gist.github.com/kt3k/0491bc4b52ad100a02e58aeee06906ac) )

**Comment by ry** [comment]
Ok closing. Not sure why I was hitting that.
