### ISSUE TITLE
`Deno.WriteFileOptions` option `create` not working when set to `false`

### ISSUE THREAD

**Issue by timharek** [denoland/deno#20226]
Using Deno ` 1.36.2` I can't get the [`Deno.WriteFileOptions`](https://deno.land/api@v1.36.2?s=Deno.WriteFileOptions#prop_create) prop `create` to work as intended.

The way I'm reading it is that either an error should be thrown or the file should remain untouched when `create` is set to `false`.

How to reproduce:
```typescript
// main.ts
export async function writeNewNote()) {
  try {
    const filename = `./filename.md`;
    const path = new URL(filename, import.meta.url);
    await Deno.writeTextFile(path, "", { create: false });
  } catch (error) {
    throw new Error(error);
  }
}

// Learn more at https://deno.land/manual/examples/module_metadata#concepts
if (import.meta.main) {
  await writeNewNote();
}
```

1. I then run `deno run -A main.ts` and the file is created as intended.
1. I update the `filename.md` with some content.
1. Re-run `deno run -A main.ts`.
1. The `filename.md`-file is now empty, because it has been overwritten.

**Comment by 0f-0b** [comment]
Setting the `create` option to `false` means that an error should be thrown if the file does not exist. There is also a `createNew` option which when set to `true` means that an error should be thrown if the file already exists.

**Comment by timharek** [comment]
Aha, I understand! Then I misunderstood. Should the options be called something different then? Because `create` and `createNew` doesn't really tell me that it would throw an error. Both in the docs and in the name of the properties.

**Comment by lucacasonato** [comment]
This is working as intended for me:

```
~/p/g/d/deno ❯❯❯ deno                                                                                                                       11:35:12
Deno 1.37.1
exit using ctrl+d, ctrl+c, or close()
REPL is running with all permissions allowed.
To specify permissions, run `deno repl` with allow flags.
> await Deno.writeTextFile("foo.txt", "", { create: false });
Uncaught NotFound: No such file or directory (os error 2): writefile 'foo.txt'
    at async writeFile (ext:deno_fs/30_fs.js:805:7)
    at async <anonymous>:2:1
> await Deno.writeTextFile("foo.txt", "", { create: true });
undefined
> await Deno.writeTextFile("foo.txt", "", { create: false });
undefined
>
```
