### ISSUE TITLE
Idea: When prompted for permission on CLI, offer option to quit

### ISSUE THREAD

**Issue by cknight** [denoland/deno#20227]
If I run a deno module without the appropriate permissions I am presented for example with the following:

```sh
┌ ⚠️  Deno requests env access to "DATA_KEY".
├ Run again with --allow-env to bypass this prompt.
└ Allow? [y/n/A] (y = yes, allow; n = no, deny; A = allow all env permissions) >
```
Usually when I get this, it's because I know I've made a mistake on the command line and want to fix it there rather than proceed with interactive prompts.  It would be nice to have the option to quit instead, e.g. 
```sh
└ Allow? [y/n/A/q] (y = yes, allow; n = no, deny; A = allow all env permissions; q=quit)
```
Yes, this can easily be achieved with Ctrl-C or some such, but I imagine many folk fall into two categories:

1. I know what I did wrong, let me quit, fix and try that again
2. Panic!  I don't understand and want out

For both use cases, quit is the right option.

**Comment by lucacasonato** [comment]
@bartlomieju wdyt?

**Comment by bartlomieju** [comment]
Seems easy to implement and potentially useful. I'm open to it.

**Comment by yazan-abdalrahman** [comment]
@bartlomieju , @lucacasonato , 
Do we still need to provide a quit option?

**Comment by dsherret** [comment]
I think this is too much to display. Additionally, just seeing "quit" I'm not sure what it means without looking at the description in this PR (ex. does it mean that it exits the process, exits the worker, denies the permission prompt?)

**Comment by yazan-abdalrahman** [comment]
> I think this is too much to display. Additionally, just seeing "quit" I'm not sure what it means without looking at the description in this PR (ex. does it mean that it exits the process, exits the worker, denies the permission prompt?). I think using `ctrl+c` is very common and fine?

@dsherret  
@bartlomieju 

Exiting the worker to allow for a safe quit is more user-friendly than relying on Ctrl-C. It makes sense to offer a straightforward option for users to quit if they realize they’ve made a mistake and want to fix it. This approach avoids the need to deny permissions and then re-run the script. Adding a "quit" option is a small change—just a single word in the prompt itself—and is preferable to the potential confusion of denial and re-running the script.

**Comment by yazan-abdalrahman** [comment]
> I think this is too much to display. Additionally, just seeing "quit" I'm not sure what it means without looking at the description in this PR (ex. does it mean that it exits the process, exits the worker, denies the permission prompt?). I think using `ctrl+c` is very common and fine?

we can add update message to be `q = quit and exit the process)`

**Comment by marvinhagemeister** [comment]
Agree, I feel like `CTRL+C` is enough for quitting.
