### ISSUE TITLE
deno.land being inaccessible breaks application

### ISSUE THREAD

**Issue by adamatat** [denoland/deno#20233]
For some reason, deno.land being down breaks my application; this is a big problem.

```typescript
error: Uncaught CompileError: WebAssembly.Module(): expected magic word 00 61 73 6d, found 35 30 30 3a @+0
  wasm_mod = new WebAssembly.Module(await ('file:' === path.protocol ? Deno.readFile(path) : fetch(path).then(r => r.arrayBuffer())));
             ^
    at https://deno.land/x/imagescript@1.2.15/utils/wasm/png.js:6:14
    at eventLoopTick (ext:core/01_core.js:181:11)
```

The import that triggers this:

```typescript
import {decode, Image} from "https://deno.land/x/imagescript@1.2.15/mod.ts";
```

When I visit `https://deno.land/x/imagescript@1.2.15/utils/wasm/png.js`, I get a 500 error:

<img width="669" alt="Screen Shot 2023-08-22 at 4 40 50 PM" src="https://github.com/denoland/deno/assets/134008627/656b377a-c98a-43b6-928a-6bff11629d6e">

How can I prevent this from being a problem in the future?

**Comment by sigmaSd** [comment]
Its a remote import so the server failing will always be show stopper, so I think the only to prevent this is to vendor your dependencies

**Comment by lucacasonato** [comment]
#2552
