### ISSUE TITLE
Optimize platform compatibility

### ISSUE THREAD

**Issue by ityspace** [denoland/deno#20232]
I want to use Deno with Termux on an Android phone. But it's not in the package list. I hope Deno can be used on more platforms.

**Comment by romanovj** [comment]
I installed deno with
`cargo install deno --locked`
Not with standart rustc, but with glibc linked (on device compiled inside termux-pacman glibc environent).
You can try

**Comment by lucacasonato** [comment]
Closing as this is not a bug with Deno itself.
