### ISSUE TITLE
bug?: `deno check need --unstable flags but already include` 

### ISSUE THREAD

**Issue by afifurrohman-id** [denoland/deno#20248]
# Description
> When i using **fresh** from project template and i run `deno task start` will got error need `--unstable` flags, but i already include

### In Deno json

```json
{
"tasks"{
    "check": "deno lint --unstable . && deno check --unstable **/*.ts && deno check --unstable **/*.tsx"
  }
}
```
### Error

```
error: TS2551 [ERROR]: Property 'openKv' does not exist on type 'typeof Deno'. Did you mean 'open'? 'Deno.openKv' is an unstable API. Did you forget to run with the '--unstable' flag, or did you mean 'open'? If not, try changing the 'lib' compiler option to include 'deno.unstable' or add a triple-slash directive to the top of your entrypoint (main file): /// <reference lib="deno.unstable" />
export const kvDb = await Deno.openKv()
                               ~~~~~~
    at file:///D:/path/to/ptoject/db.ts:4:32

    'open' is declared here.
      export function open(
                      ~~~~
        at asset:///lib.deno.ns.d.ts:1709:19
```

But When i run command immediately **no problem**
```sh
deno lint --unstable . && deno check --unstable **/*.ts && deno check --unstable **/*.tsx
```

**Comment by dsherret** [comment]
Follow this step on the error message:

```
or add a triple-slash directive to the top of your entrypoint (main file): /// <reference lib="deno.unstable" />
```

It's necessary in Fresh because it adds `/// <reference no-default-lib="true" />` to the entrypoint, which will erase the unstable types, but adding `/// <reference lib="deno.unstable" />` will add them back.

https://github.com/denoland/fresh/blob/fb6d11747b0f0e17af0e43be2331db35946c6900/www/main.ts#L1

**Comment by sigmaSd** [comment]
related https://github.com/denoland/fresh/issues/822

**Comment by afifurrohman-id** [comment]
> Follow this step on the error message:
> 
> ```
> or add a triple-slash directive to the top of your entrypoint (main file): /// <reference lib="deno.unstable" />
> ```
> 
> It's necessary in Fresh because it adds `/// <reference no-default-lib="true" />` to the entrypoint, which will erase the unstable types, but adding `/// <reference lib="deno.unstable" />` will add them back.
> 
> https://github.com/denoland/fresh/blob/fb6d11747b0f0e17af0e43be2331db35946c6900/www/main.ts#L1

I have already added

**Comment by dsherret** [comment]
Follow updates on this in https://github.com/denoland/deno/issues/20420
