### ISSUE TITLE
deno 1.36.2  cause oom (out of memory)

### ISSUE THREAD

**Issue by blessbygod** [denoland/deno#20257]
use [https://deno.land/x/redis@v0.31.0/mod.ts, 0.29.2 the same] 

code:  
      await redisInstance.get(key)

Will result in a very noticeable oom。

1.36.2 init memory is low,  but increase memory so quick.
1.36.1 init memory is high, but memory is ok.

**Comment by bartlomieju** [comment]
Fixed by https://github.com/denoland/deno/pull/20253. Should be released today in v1.36.3.

**Comment by blessbygod** [comment]
3ks~
