### ISSUE TITLE
Want to use ReadableStream as response body to enable SSE

### ISSUE THREAD

**Issue by bjesuiter** [denoland/deno#20259]
I imagine doing the following: 

```ts routes/streaming.tsx

import { simpleCallbackTarget, timerSource } from "rx_webstreams";
import { SSEStream } from "sse_codec";

export default async function StreamingResponseTest() {
  const timer = timerSource({
    intervalInMilliseconds: 1000,
    maxEventCount: 1000,
  });

  const sseStream = new SSEStream();

  await timer.pipeTo(simpleCallbackTarget((timerTick) => {
    console.log(timerTick);
    sseStream.emit({
      eventName: "tick",
      id: Math.random() + "",
      data: timerTick + "",
    });
  }));

  return new Response(sseStream.readableStream, {
    headers: {
      "Content-Type": "text/event-stream",
    },
  });
}

```

This should send a bunch of text per each second to the client (which gets interpreted as an SSE event when formatted correctly). 

However, it seems that nothing arrives in the browser (the "Preview" tab is empty and no response headers are there): 
<img width="1792" alt="Bildschirmfoto 2023-08-20 um 02 06 50" src="https://github.com/denoland/fresh/assets/2365676/26c4c641-e4eb-4aad-9451-c9493a702182">

I call this endpoint via this Island: 
```ts islands/sse-test.tsx
import { IS_BROWSER } from "$fresh/runtime.ts";

export function SSEDebug() {
  if (!IS_BROWSER) return <div></div>;

  const source = new EventSource("/streaming");

  source.onopen = () => console.log(`SSE Stream Opened!`);
  source.onmessage = (msg) => console.log(`SSE Stream received message`, msg);
  source.onerror = (err) => console.error(`SSE Stream had error`, err);

  return <div></div>;
}
```

Does Fresh do some caching for the Response when I return a "raw response" instead of JSX?
Or, more generally: Is it even supposed to work, sending back a Response with a ReadableStream in initialization?

**Comment by lucacasonato** [comment]
@bjesuiter It seems the `sse_codec` library creates a `ReadableStream<string>`, but `Response` only supports `ReadableStream<Uint8Array>`. You want to do `sseStream.readableStream.pipeThrough(new TextEncoderStream())`.

I'll close this issue, but if you need more help, feel free to ask on Discord (https://discord.gg/deno) or GitHub Discussions!

**Comment by ashah888** [comment]
> Fresh does support SSE. I did some testing and Fresh seems to interpret `StreamingResponseTest()` as an component. The following works (tested with Postman):
> 
> import { defineRoute } from "$fresh/server.ts";
> 
> export default defineRoute((_req, _ctx) => {
>   let timer: number;
>   const stream = new ReadableStream({
>     start(controller) {
>       timer = setInterval(() => {
>         const body = `data: ${new Date()}\n\n`;
>         controller.enqueue(body);
>       }, 1000);
>     },
>     cancel() {
>       clearInterval(timer);
>     },
>   });
> 
>   const body = stream.pipeThrough(new TextEncoderStream());
> 
>   return new Response(body, {
>     headers: { "content-type": "text/event-stream" },
>   });
> });
> However this does not work and the response type is html:
> 
> import { RouteContext } from "$fresh/server.ts";
> 
> export default function Stream(_req: Request, _ctx: RouteContext) {
>   // Omitted for brevity
> }
> This also works:
> 
> import { Handlers } from "$fresh/server.ts";
> 
> export const handler: Handlers = {
>   GET(_req, _ctx) {
>     // Omitted for brevity
>   },
> };
> ~There thus seem to be some inconsistencies with how fresh determines what a JSX component is and what's not.~ I hope this helps.

@smitssjors do you know why this exact code might work in local development but not in production url?

**Comment by smitssjors** [comment]
@ashah888 There is no real way for me to know. If it works in dev but not prod it might be you proxy (`caddy`, `nginx`, `treafik`, ...). It could for example try to buffer the whole response from your deno server but since it is infinitely long it never returns/times out.
