### ISSUE TITLE
Fresh + Deno 1.36.2 + Transfer-Encoding Chunked is broken

### ISSUE THREAD

**Issue by mcandeia** [denoland/deno#20252]
Hope you're well. I wanted to flag an issue we've encountered with Deno version 1.36.2 in a fresh project. It seems that copied response bodies are now being transferred as chunked, leading to partial page rendering and hampering user navigation.

To replicate:

1. We've set up a sample repo: [https://github.com/tlgimenes/fresh-serve](https://github.com/tlgimenes/fresh-serve)
2. In `_middleware.ts`, copying responses triggers chunked transfer. [here](https://github.com/tlgimenes/fresh-serve/blob/main/routes/_middleware.ts#L4)
3. Included a large HTML file for demonstration.
4. Running the sample shows partial rendering.

> Run with `deno task start`

A quick fix we found: Commenting out `Deno.serve = undefined` in `main.ts` reverts to the standard server and resolves the problem (because it forces fresh to fallback to std serve implementation [here](https://github.com/denoland/fresh/blob/fb6d11747b0f0e17af0e43be2331db35946c6900/src/server/mod.ts#L170)). [here](https://github.com/tlgimenes/fresh-serve/blob/main/main.ts#L14)

This seems to be related to this change: https://github.com/denoland/deno/pull/20180

cc: @marvinhagemeister @mmastrac

**Comment by mcandeia** [comment]
Thanks @marvinhagemeister

**Comment by mmastrac** [comment]
Found the issue: https://github.com/denoland/deno_core/pull/155

**Comment by mcandeia** [comment]
Thanks @mmastrac and @marvinhagemeister

**Comment by mmastrac** [comment]
Thanks for the easy repro! That made it easy to track down

**Comment by mmastrac** [comment]
Fixed by #20254

**Comment by marvinhagemeister** [comment]
@mmastrac Is that the correct PR you linked to? It is marked as closed and not merged.
