### ISSUE TITLE
deno run some.ts, how to allow imports in some.ts without .ts endings？

### ISSUE THREAD

**Issue by Silentdoer** [denoland/deno#20261]
like title

**Comment by d-gubert** [comment]
Apparently not possible, as the docs point out:

> It adopts browser-like module resolution, meaning that file names must be specified in full. You may not omit the file extension and there is no special handling of index.js.

https://deno.land/manual@v1.36.2/basics/modules#overview

**Comment by lucacasonato** [comment]
This is not possible, you have to specify explicit specifiers on all imports.
