### ISSUE TITLE
Fmt: allow collapsing blank lines like prettier

### ISSUE THREAD

**Issue by guy-borderless** [denoland/deno#20264]
Prettier collapses multiple blank lines into a single blank line, this results in code that has fewer meaningless noise, is easier to diff, less to scroll and nicer to look at.

**Comment by dsherret** [comment]
Can you clarify what you mean? deno fmt should collapse multiple blank lines into one.

**Comment by lucacasonato** [comment]
Have gotten no response, so closing as not actionable.
