### ISSUE TITLE
Async function that named `using` does not work properly from Deno v1.36.2

### ISSUE THREAD

**Issue by lambdalisue** [denoland/deno#20271]
It is difficult to explain the phenomenon, but at any rate, after [this commit](https://github.com/denoland/deno/commit/5834d282d4de5d0b5cacb9bf068f3896bef0a48a), using a function named `using` behaves strangely. Specifically, assertRejects cannot catch errors thrown without the internal async function, or it cannot wait for the internal async function to complete (I have tried everything, but the behavior does not seem consistent).

![image](https://github.com/denoland/deno/assets/546312/b46b8ef6-6122-4372-a31a-68295ce83bc6)

The contents of the using function are not related to the phenomenon (because the behavior is fixed if I renamed `using` to `usingA` or whatever), but they are as follows.

```ts
export async function using<T extends Disposable, R = unknown>(
  resource: T,
  fn: (resource: T) => R | Promise<R>,
): Promise<R> {
  try {
    return await fn(resource);
  } finally {
    await resource.dispose();
  }
}
```

If this function is used in the form of "await using" as shown below, the behavior will suddenly become strange.

```ts
Deno.test("using ensure asynchronous disposable is disposed even on error", async () => {
  const calls = [];

  calls.push("enter");
  await assertRejects(async () => {
    await using(
      new AsynchronousDisposable(() => calls.push("dispose")),
      (r) => {
        assert(r instanceof AsynchronousDisposable);
        calls.push("fn");
        throw new Error("Error");
      },
    );
  });
  calls.push("leave");

  assertEquals(calls, [
    "enter",
    "fn",
    "dispose",
    "leave",
  ]);
});

```

You can find all codes in the following library (it's small enough to check I think)

https://github.com/lambdalisue/deno-disposable

I'm thinking that perhaps the `await using` part of the behavior has changed since TypeScirpt 5.2 due to the increase in the `using` keyword, but I honestly don't know.

- https://github.com/vim-denops/denops.vim/issues/272

**Comment by lucacasonato** [comment]
Sorry about that! It's a regression from the introduction of [`using` declarations](https://github.com/tc39/proposal-explicit-resource-management).

Upstream parser bug: https://github.com/swc-project/swc/issues/8096

**Comment by dsherret** [comment]
Seems fixed for a while now.
