### ISSUE TITLE
Reproducible Deno panic

### ISSUE THREAD

**Issue by AtomicGamer9523** [denoland/deno#20291]
I was able to consistently make Deno panic. File: [File affected](https://github.com/AtomicGamer9523/darkts/blob/62c76420757be3bd3e5f5e59f72da726fb7b8f4f/threader/mod.test.ts), [Project](https://github.com/AtomicGamer9523/darkts/tree/62c76420757be3bd3e5f5e59f72da726fb7b8f4f).

Stdout (first run):

```powershell
Task test deno --unstable run -A mod.test.ts
Sleeping for 1 second...
Done sleeping!
```

Stdout (all after that):

```powershell
============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: windows x86_64
Version: 1.36.3
Args: ["C:
```
(I didn't miss anything STDOUT just ends there)

Debug info:

```powershell
> deno -V
deno 1.36.3

> rustc -Vv
rustc 1.70.0 (90c541806 2023-05-31)
binary: rustc
commit-hash: 90c541806f23a127002de5b4038be731ba1458ca
commit-date: 2023-05-31
host: x86_64-pc-windows-msvc
release: 1.70.0
LLVM version: 16.0.2

**Comment by bartlomieju** [comment]
@aapoalas this looks like an FFI bug. Can you take a look?

**Comment by aapoalas** [comment]
I'll take a look at what exactly is causing the panic but I can already say that the provided code is unfortunately not going to work no matter what.

The `block_on` function is trying to block on an async function: FFI does not allow transcending normal JavaScript limits, in this case foremost that JavaScript is single threaded. Additionally, FFI callbacks cannot be asynchronous. This means that the code could in plain JavaScript be written more or less like this:

```js
const block_on = cb => {
  let isReady = false;
  const spawnedThreadGoesFirst = Math.random() > 0.5;
  if (spawnedThreadGoesFirst) {
    cb();
    isReady = true;
  }
  while (true) {
    if (isReady) {
      break;
    }
    if (!spawnedThreadGoesFirst) {
      cb();
      isReady = true;
    }
  }
};

block_on(async () => {
  console.log("Sleeping for 1 second...");
  await sleep(1000);
  console.log("Done sleeping!");
});
```

Note that when `cb()` is called it is not awaited: This is from the FFI callbacks not supporting asynchronous callbacks. The main problem however is the randomness with which we decide who gets to go first, which here stands for the question of if the spawned thread runs before we get into the `while` loop... Though now that I think about it I have no idea how the callback gets picked up from the incoming thread safe callbacks queue when all of the call-side code is synchronous...

Anyway, I'll get back to you with more details but mostly this will be a "wont fix" and to some degree perhaps making Deno eagerly panic when Promise returns from FFI callbacks are detected.

Note: Not supporting Promises in FFI callbacks wouldn't theoretically be impossible for cases where the callback is coming from a foreign thread. But, if the callback happens to come in on the same thread then we have no way of blocking the thread while still doing work in the JavaScript event loop. This would then be a case where we'd have no recourse to guarantee a correct continuation of the program and would likely have to panic. Furthermore, supporting "awaiting" of JavaScript Promises on the Rust side for FFI callbacks is definitely not trivial even when the call is coming from a foreign thread that is blocked for the duration of the work. So far I've really not seen it as a feature that would make sense to add given the complexity and the very limited use case (callbacks that are only ever called from foreign threads and can never be called from the JS thread in response to some action).

**Comment by aapoalas** [comment]
Alright, looking into this I uncovered the answer to how the callback gets picked from the incoming thread through the `while(true)` loop: It doesn't. The while loop is exited after one iteration because the task is never pushed into the static `TASKS` vector on the Rust side, so the list of ongoing tasks is always empty and the check for "is ready" is always true. So we exit the while loop immediately, after which the incoming callback then gets picked up and run.

I am unable to reproduce the crash on Linux but I expect the reason for the crash is that Deno sees that there is no work to be done on the event loop and starts exiting the process which destructures the UnsafeCallback, but the spawned thread is still accessing its memory, thus leading to a segfault. You can tell Deno that it should not exit while the UnsafeCallback still lives by either `.ref()`'ing it or creating the `UnsafeCallback` using the `threadSafe` static method on the class: These two methods are exactly equivalent.

When you know all your work is done, use `.unref()` on your UnsafeCallback to tell Deno that you no longer expect the callback to be called and thus that Deno is free to exit.

**Comment by AtomicGamer9523** [comment]
I am running on windows, but that is in fact very interesting...

**Comment by aapoalas** [comment]
@AtomicGamer9523 I am leaning towards closing this issue as I am not sure if there's anything we can do in Deno to help in this case: If the issue indeed is that a thread created on the Rust side still holds and accesses the C callback pointer while Deno is shutting down then it's kind of unclear if anything we do can really fix the issue.

One thing we could do is to make sure that we drain incoming callbacks before closing callbacks on close, but it's possible that draining a callback simply brings in more of them. We also likely cannot allow those calls to call into JavaScript anymore, so the calls would end up being essentially unhandled. We could just return without handling the calls and hope for the best but that may well lead to the caller panicking.

Do you consider this issue to be resolved or rather something that we should still look further into?

**Comment by AtomicGamer9523** [comment]
It would be nice to add a `block` function to Deno, to allow "awaiting" in a sync function. It is essential for what my project requires, but sadly isn't a feature, I tried making it myself but hit this roadblock. How would I go about making a proposal, to add this feature, and if this were to get implemented, will this require some internal v8 changes ?

**Comment by aapoalas** [comment]
Synchronizing an asynchronous function would, indeed, require more changes than Deno can make as it would require changing JavaScript itself, so both the spec and engines.

FFI callbacks could be separately made to work with `await` but as said above I'm just quite afraid that it will end up being a terrible footgun.

**Comment by AtomicGamer9523** [comment]
Understood, thank you very much
