### ISSUE TITLE
error: Unsupported scheme "npm" for module "npm:prisma"

### ISSUE THREAD

**Issue by emirom** [denoland/deno#20292]
**How to reproduce**
<br />
according to the [deno doc for prisma](https://deno.land/manual/node/how_to_with_npm/prisma) consider having this schema.prisma file:

```
datasource db {
  provider = "postgresql"
  url      = env("DENO_PRISMA_DB_URL")
}

generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["deno"]
  output          = "../generated/client"
}

model Country {
  id          Int        @default(autoincrement()) @id
  name        String     
  abb         String?
  population  Int
}
```
**Bug description**

when this command is entered: ` deno run -A npm:prisma@^4.5 db push`
This error is thrown:
```
 error: Unsupported scheme "npm" for module "npm:prisma@^4.5". Supported schemes: [
    "data",
    "file",
    "http",
    "https",
]
```

**Environment & setup**
ubuntu 20.04

result of `deno --version:`
```
deno 1.7.5 (release, x86_64-unknown-linux-gnu)
v8 9.0.123
typescript 4.1.4
```
Node.js version:
same results for node v14, v16, v18 using fnm

**Comment by sigmaSd** [comment]
You need to update deno version, run deno upgrade
