### ISSUE TITLE
Bug: Unable to format vendored files

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/deno#20308]
Formatting a file that is vendored via `vendor: true` in the deno config file leads to an error.

<img width="311" alt="Screenshot 2023-08-28 at 12 35 06" src="https://github.com/denoland/deno/assets/1062408/cb00124a-3bf5-4415-b7bb-fec4535a25bb">

## Steps to reproduce

1. Clone https://github.com/marvinhagemeister/deno-format-vendor
2. Open `vendor/esm.sh/v124/@twind/core@1.1.3/deno/core.mjs`
3. Open command palette (CMD+Shift+P on macOS or CTRL+Shift+P on other OS'es) and select `Format document with...` -> `Deno`

Alternatively run `deno fmt ./vendor/esm.sh/v124/@twind/core@1.1.3/deno/core.mjs`.

## Output

```sh
Invalid file path.
  Specifier: https://esm.sh/v124/@twind/core@1.1.3/deno/core.mjs
```

**Comment by nayeemrmn** [comment]
Ideally `Format Document` via the command palette would work but `formatOnSave` wouldn't apply to these files, but it seems there's no way of differentiating.
