### ISSUE TITLE
ext/http: panic on "already borrowed" (BorrowMutError)

### ISSUE THREAD

**Issue by lucab** [denoland/deno#20315]
After upgrading the deno HTTP library to 1.36.3 (`deno_http 0.112.0`), we've started seeing some occurences of the following panic:
```
thread 'main' panicked at 'already borrowed: BorrowMutError',
~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/deno_http-0.112.0/slab.rs:45:16
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Unfortunately I don't have any more details about the triggering condition for this, but it seems to be a race which occurs quite infrequently.

Panicking logic:
https://github.com/denoland/deno/blob/539e5032d372679869dcee4e2e63f2116288b435/ext/http/slab.rs#L43-L47

@mmastrac I think https://github.com/denoland/deno/pull/20206 introduced this as a regression.

**Comment by mmastrac** [comment]
Yeah, it looks like if a request is dropped before the response body is set this gets triggered. I need to write some tests for HTTP connections being dropped.
