### ISSUE TITLE
Version mismatch between V8 binary and snapshot.

### ISSUE THREAD

**Issue by seogrady** [denoland/deno#20318]
While playing around with deno_runtime, updating to the latest version causes this snapshot error. Is there a way to clear snapshots or tell V8 to recreate snapshot?

```
#
# Fatal error in , line 0
# Version mismatch between V8 binary and snapshot.
#   V8 binary version: 11.7.439.6
#    Snapshot version: 11.6.189.12
# The snapshot consists of 5734556 bytes and contains 1 context(s).
#
#
#
#FailureMessage Object: 0x3121eb830
==== C stack trace ===============================
```

**Comment by bartlomieju** [comment]
We create snapshots as part of `build.rs` scripts which automatically rebuild them if anything changes. Other than that I'm not sure if that's possible since the format is not stable across V8 release so it would be hard to sniff out the version mismatch.

**Comment by bartlomieju** [comment]
Sounds good, good luck!
