### ISSUE TITLE
using localStorage leads to "Uncaught Error: no such table: dbstat: Error code 1: SQL error or missing database"

### ISSUE THREAD

**Issue by davepeck** [denoland/deno#20319]
I installed deno via [Homebrew](https://github.com/Homebrew/homebrew-core/blob/master/Formula/d/deno.rb) on my Apple Silicon Mac.

```
> deno --version
deno 1.36.3 (release, aarch64-apple-darwin)
v8 11.6.189.12
typescript 5.1.6
```

Then I tried:

```
> deno repl --allow-all
Deno 1.36.3
exit using ctrl+d, ctrl+c, or close()
> localStorage.setItem("hello", 42)
Uncaught Error: no such table: dbstat: Error code 1: SQL error or missing database
    at Proxy.setItem (ext:deno_webstorage/01_webstorage.js:51:9)
    at <anonymous>:2:14
```

I am unable to reproduce this behavior when using deno via docker:

```
>  docker run -it --init denoland/deno:1.36.3 repl --allow-all
Deno 1.36.3
exit using ctrl+d, ctrl+c, or close()
> localStorage.setItem("hello", 42)
undefined
```

This issue _may_ be related to [another recently filed Deno issue](https://github.com/denoland/deno/issues/20196).

**Comment by davepeck** [comment]
Update: I built `deno` from source and was unable to reproduce the issue. Might be a homebrew specific issue, I'm not sure.

```
> ./target/debug/deno --version
deno 1.36.3 (debug, aarch64-apple-darwin)
v8 11.6.189.12
typescript 5.1.6
> ./target/debug/deno repl --allow-all
Deno 1.36.3
exit using ctrl+d, ctrl+c, or close()
> localStorage.setItem("hello", 42)
undefined
```

**Comment by davepeck** [comment]
Okay, this _is_ a Homebrew issue. Homebrew does not currently enable `SQLITE_ENABLE_DBSTAT_VTAB`, which `deno` appears to require.

Is there documentation on the specific SQLite extensions needed? I wasn’t able to find any.

I’ll close this bug but want to leave it open long enough for someone to hopefully point me toward documentation.

**Comment by bartlomieju** [comment]
CC @losfair @igorzi please take a look

**Comment by davepeck** [comment]
Closing this; if y'all are able to provide more details on the expected `sqlite` flag, that would be much appreciated.

For now, [homebrew will selectively enable](https://github.com/Homebrew/homebrew-core/pull/141120) new `SQLite` features based on `rusqulite`'s defaults. Seems like that should probably match `deno`'s expectations.
