### ISSUE TITLE
Installing Error

### ISSUE THREAD

**Issue by Gapostigo** [denoland/deno#20322]
I was installing Deno following the documentation available step by step and used the irm command in PowerShell. I got an error that is shown on the screenshot below. I would appreciate any help you guys can lend me. 

![hola](https://github.com/denoland/deno/assets/92795249/10c86075-1c80-49be-927c-06dcb788c4d6)

Thanks.

**Comment by markthree** [comment]
> PowerShell

This may be a permission issue with PowerShell. You can try opening PowerShell as an administrator for installation。

A more recommended approach is to directly download the distribution bin and set the environment variables。

**Comment by lucacasonato** [comment]
Please ask on Discord (https://discord.gg/deno) for specific installation help, thanks!
