### ISSUE TITLE
Uncaught Error: Expecting promise in table. 0

### ISSUE THREAD

**Issue by keroxp** [denoland/deno#2033]
## env
- OS: macOS 10.14.3
- deno: v0.3.5

## description

```
$ deno -A https://deno.land/std/http/http_bench.ts
```

```
$ wrk -t12 -c400 -d30s http://127.0.0.1:4500
```

got 

```
Uncaught Error: Expecting promise in table. 0
    at assert (js/util.ts:28:11)
    at handleAsyncMsgFromRust (js/dispatch.ts:16:3)
    at handleAsyncMsgFromRust (shared_queue.js:117:9)
```
`cmdId` on [here](https://github.com/denoland/deno/blob/master/js/dispatch.ts#L14) get 0. I tried to set `let nextCmdId = 1` and got the same error. Maybe `handleAsyncMsgFromRust` had been called with invalid argument.

**Comment by kevinkassimo** [comment]
When printing out `innerType` of this msg received, I got `0` (aka `msg.Any.NONE`) which should never have happened if fired by any well-defined defined op... Something might have gone terribly wrong

**Comment by jorsi** [comment]
I've been poking into the typescript api with flatbuffers. Not sure if I understand enough of it yet to give any feedback, but it seems like some of the flatbuffers created in the api are missing some fields. 

E.g. https://github.com/denoland/deno/blob/master/js/fetch.ts#L327
The generated msg.HttpHeader in "gen/cli/msg_generated" has a createHttpHeader() function which seems to add a status field that isn't included here. Could this be shifting the buffers around? A few of the other ts apis with flatbuffers also seem to miss adding some fields.
