### ISSUE TITLE
Out of memory crash with large number of timers

### ISSUE THREAD

**Issue by milaz** [denoland/deno#20356]
When a large, but entirely reasonable number of timers is in use, Deno will consume an excessive amount of memory and crash.

Timers are not some fringe JavaScript curiosity to run animations in a browser. They are a crucial tool to coordinate tasks running in event loop. For example, every socket (and WebSocket on top of it) will likely have a timer to check whether the other end is alive, and ping it periodically if there was no other traffic. Deno is being extensively used to write server software. The performant server software needs to handle multiple connections efficiently.

This bug resulted in a crash in version 1.36.1, some fixes in 1.36.2 prevented it from crashing but the amount of memory taken was still unreasonable, version 1.36.4 is crashing again.

The code to reproduce follows. Node.js runs this code without consuming any noticeable amount of CPU time or memory.

```js
let v = 0;
for (let i = 0; i < 1e6; i++) {
  setInterval(() => v++, 5000);
}

setInterval(() => console.log(v), 5000);
```

Crash message:

```
<--- Last few GCs --->

[407756:0x56079b88cd20]    22029 ms: Scavenge 1352.4 (1384.5) -> 1352.0 (1392.5) MB, 8.27 / 0.00 ms  (average mu = 0.323, current mu = 0.305) task; 
[407756:0x56079b88cd20]    22066 ms: Scavenge 1358.5 (1392.5) -> 1357.9 (1392.5) MB, 14.52 / 0.00 ms  (average mu = 0.323, current mu = 0.305) task; 
[407756:0x56079b88cd20]    22094 ms: Scavenge 1359.6 (1392.7) -> 1358.9 (1413.5) MB, 21.55 / 0.00 ms  (average mu = 0.323, current mu = 0.305) task; 


<--- JS stacktrace --->


#
# Fatal JavaScript out of memory: Ineffective mark-compacts near heap limit
#

Trace/breakpoint trap (core dumped)
```

**Comment by bartlomieju** [comment]
Thanks for the report 👍 we'll dig into it

**Comment by bartlomieju** [comment]
@milaz can you provide some info regarding the system you are running on? I tried a quick reproduction and seem to be able to run this code without any crashes on somewhat beefy MacBook M1 Max.
