### ISSUE TITLE
`Deno.Command` error message for non-existent `cwd` is misleading

### ISSUE THREAD

**Issue by solson** [denoland/deno#20351]
Deno 1.36.3

```
> new Deno.Command("/bin/sh", { cwd: "/nonexistent" }).spawn()
Uncaught NotFound: Failed to spawn: /bin/sh: No such file or directory (os error 2)
    at spawnChildInner (ext:runtime/40_process.js:162:17)
    at spawnChild (ext:runtime/40_process.js:182:10)
    at Command.spawn (ext:runtime/40_process.js:440:12)
    at <anonymous>:4:4
```

To a naive reading, the error message seems to imply that `/bin/sh` doesn't exist, and either way it has no indication that the `cwd` is the problem.

**Comment by sigmaSd** [comment]
Its a bit annoying to fix because rust will return the same error for both cases
```rs
In: std::process::Command::new("lsezzz").spawn()
Out: Err(Os { code: 2, kind: NotFound, message: "No such file or directory" })

In: std::process::Command::new("ls").current_dir("edqsqdsq").spawn()
Out: Err(Os { code: 2, kind: NotFound, message: "No such file or directory" })
```

**Comment by bartlomieju** [comment]
We could perform a `stat` of `cwd` arg to verify that it's a directory.

**Comment by castarco** [comment]
Is this one up for grab? Would it be Ok if I pick it to work on?

**Comment by sigmaSd** [comment]
Yes 👍

**Comment by shivam-jainn** [comment]
Can you provide more information on how to trace an error message in Rust? I cannot find anything. Where are the error messages stored or built?

**Comment by strawsnoceans** [comment]
Hey @castarco, 
been working on this issue too, think we can discuss approaches? Sorry hadn't dropped a message here, but I'm just figuring out to whether drop an error in the `create_command` or the `spawn_child` function

**Comment by castarco** [comment]
@shreyass-ranganatha  all good, but gotta be honest, I find that a bit rude.

**Comment by shreyass-ranganatha** [comment]
@castarco 
I'm really sorry man, kinda new to OSS, missed out on mentioning I've been working on this! 

If you'd like we could share a collaborative contribution on this

**Comment by castarco** [comment]
@shreyass-ranganatha don't worry about attribution. You worked on this, it's yours. My grumble was more about lack of coordination and wasted time and effort. Anyway, we're good 👍🏻 .
