### ISSUE TITLE
`fmt --check` diff displayed incorrectly

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/deno#20364]
When `deno fmt --check` founds an incorrectly formatted file it displays a code frame with a diff of the formatting changes. The formatting issues are detected correctly, so the fact that this is shown is not the issue. The problem is that the displayed diff is wrong. It seems to ignore white space of some lines vs others:

<img width="690" alt="Screenshot 2023-09-03 at 13 49 37" src="https://github.com/denoland/deno/assets/1062408/595152fc-cab0-4bfa-918b-59689790de5d">

In line `61` of the diff where the line starts with `<li>` it has preceding white space that is somehow missing in the diff.

<img width="443" alt="Screenshot 2023-09-03 at 13 50 08" src="https://github.com/denoland/deno/assets/1062408/14bfd462-5bb4-479b-977c-813cebb5c133">

Input code (markdown):

```tsx
import { Handlers, PageProps } from "$fresh/server.ts";

const NAMES = ["Alice", "Bob", "Charlie", "Dave", "Eve", "Frank"];

interface Data {
  results: string[];
  query: string;
}

export const handler: Handlers<Data> = {
  GET(req, ctx) {
    const url = new URL(req.url);
    const query = url.searchParams.get("q") || "";
    const results = NAMES.filter((name) => name.includes(query));
    return ctx.render({ results, query });
  },
};

export default function Page({ data }: PageProps<Data>) {
  const { results, query } = data;
  return (
    <div>
      <form>
        <input type="text" name="q" value={query} />
        <button type="submit">Search</button>
      </form>
      <ul>
        {results.map((name) => (
          <li key={name}>{name}</li>
        ))}
      </ul>
    </div>
  );
}
```

**Comment by HasanAlrimawi** [comment]
This is no more the case with `deno 1.46.1 (stable, debug, x86_64-pc-windows-msvc)`. (It's unreproducible)
I believe it's fixed.
