### ISSUE TITLE
Question: Do we have plan to support unix domain socket with `Deno.serve`?

### ISSUE THREAD

**Issue by kt3k** [denoland/deno#20369]
If we support unix domain socket transport with `Deno.serve`, we probably can deprecate the entire `std/http/server.ts`. Do we have a plan for it?

**Comment by kt3k** [comment]
Bun seems to have added unix domain socket support to Bun.serve in v0.8.1 https://bun.sh/blog/bun-v0.8.1#start-an-http-server-on-a-unix-domain-socket-with-bun-serve

**Comment by bartlomieju** [comment]
From what I can tell there are technical roadblocks to support it. @mmastrac any objections?

**Comment by mmastrac** [comment]
No objections. I suspect it should be pretty straightforward to implement as the Unix socket is plumbed through on the rust side. It just needs some JS support IIRC
