### ISSUE TITLE
Timer fires too soon

### ISSUE THREAD

**Issue by 0f-0b** [denoland/deno#20367]
```shellsession
$ cat a.js
const start = performance.now();
setTimeout(() => {
  const end = performance.now();
  console.log(end - start);
}, 1000);
clearTimeout(setTimeout(() => {}, 1000));
$ deno run a.js
2
$ deno --version
deno 1.36.4+83426be (canary, x86_64-apple-darwin)
v8 11.7.439.6
typescript 5.1.6
```

This program should print a value of at least 1000, but it prints a much smaller value when run with recent canary versions of Deno.

**Comment by jcabezasp2** [comment]
It seems that the problem is caused by the implementation of clearTimeout

The error occurs when the time set in the clearTimeOut is greater than or equal to the time set in the SetTimeOut.
