### ISSUE TITLE
`EventTarget` dispatch behavior differs from Chrome when handler throws error

### ISSUE THREAD

**Issue by linhub15** [denoland/deno#20406]
When creating an `EventTarget` with multiple listeners, Chrome is able to invoke all handlers even if one of them throws an error.
Deno does not output the results of the next handler when an earlier registered handler throws an error.

Original source: https://twitter.com/BenLesh/status/1699490548535484605

## Reproduction steps
```ts
// main.ts
const emitter = new EventTarget();
emitter.addEventListener("test", () => console.log("one"));
emitter.addEventListener("test", () => {
  throw new Error("two");
});
emitter.addEventListener("test", () => console.log("three"));

emitter.dispatchEvent(new Event("test"));
```
### Output from `deno run main.ts`
Notice that "three" is not outputted to the console.

![image](https://github.com/denoland/deno/assets/10420994/fef3cc0f-c7e9-4363-9e19-b01839ff12f9)

<details>
<summary><code>deno --version</code></summary>
<pre><code>deno 1.36.4 (release, x86_64-pc-windows-msvc)
v8 11.6.189.12
typescript 5.1.6
</code></pre>
</details>

### Chrome console
Notice that "three" is outputted to the console.

![image](https://github.com/denoland/deno/assets/10420994/8235113b-1003-404a-b231-e7d8296a7cb1)

**Comment by lucacasonato** [comment]
This is correct - in browsers the `"error"` event on `globalThis` (uncaught exceptions) do not terminate the process. In Deno, uncaught exceptions terminate the process. Because of the termination, the second handler is never invoked.

If you'd like to emulate the Chrome behaviour, add this snippet to your code:

```js
addEventListener("error", e => {
  console.log(e);
  e.preventDefault(); // this prevents the error event from terminating the process
});
```
