### ISSUE TITLE
`deno compile` does not take additional arguments like documentation says

### ISSUE THREAD

**Issue by jryom** [denoland/deno#20413]
According to https://deno.land/manual@v1.36.4/tools/compiler#compiling-executables, it should be possible to run:

```
deno compile --allow-read --allow-net https://deno.land/std/http/file_server.ts -p 8080
```

However I am getting the following error:

```
error: unexpected argument '-p' found

  tip: to pass '-p' as a value, use '-- -p'

Usage: deno compile [OPTIONS] [SCRIPT_ARG]...

For more information, try '--help'.
```

Output from `deno --version`:
```
deno 1.36.4 (release, aarch64-apple-darwin)
v8 11.6.189.12
typescript 5.1.6
```

**Comment by aapoalas** [comment]
As said in the error message, add `--` between the script name and the parameters you intend to pass to it.

**Comment by aapoalas** [comment]
Oh oops, indeed seems like the manual is faulty.
