### ISSUE TITLE
Deno on Windows with Typescript obscures errors

### ISSUE THREAD

**Issue by Erisfiregamer1** [denoland/deno#20441]
<img width="445" alt="image" src="https://github.com/denoland/deno/assets/54373833/cd152255-37f9-4f1f-93af-ea35edb1b080">

The actual error here was that I didn't set the fetch method, but this happens with EVERY error. You have to use a try-catch block to get the error you need.

This is making it REALLY hard to work with Deno for new projects :(

**Comment by bartlomieju** [comment]
Can you provide your reproduction code?

**Comment by Erisfiregamer1** [comment]
const res = await fetch("https://api.openai.com/v1/chat/completions", {
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${Deno.env.get("OPENAI_API_KEY")}`
    }, 
    body: JSON.stringify({
      model: "gpt-3.5-turbo-16k",
      messages: messages,
      user: userid
    })
  })
  
  That's it. A single fetch. You probably don't even notice what's wrong- and the error it throws sure doesn't help until you use a trycatch.

**Comment by Erisfiregamer1** [comment]
If you need the full code I'll commit to the source repo and send the link- snippet should be fine though

**Comment by bartlomieju** [comment]
Yes, please provide a full repo.

**Comment by Erisfiregamer1** [comment]
https://github.com/Erisfiregamer1/llm-bot
