### ISSUE TITLE
Vite example in Deno Deploy docs no longer works

### ISSUE THREAD

**Issue by farsightsoftware** [denoland/deno#20453]
I'm not sure if I'm reporting a documentation error, a Deno node-compat bug, or a Vite bug (in the wrong place :-D) but https://deno.com/deploy/docs/vite says you can scaffold a new Vite app with Deno by using:

```bash
deno run --allow-read --allow-write --allow-env npm:create-vite-extra@latest
```

But doing that fails with this error:

> error: package 'create-vite-extra' did not have a bin property in its package.json

Apologies in advance if I'm posting this in the wrong place.

**Comment by dsherret** [comment]
@farsightsoftware that's strange. The `create-vite-extra` package seems to have always had a "bin" entry for "create-vite-extra" (https://www.npmjs.com/package/create-vite-extra/v/1.1.0?activeTab=code)

```jsonc
{
  "name": "create-vite-extra",
  // ...
  "bin": {
    "create-vite-extra": "index.js"
  },
  // ...
}
```

Are you by chance using an old version of Deno? Maybe try `deno upgrade` and if that doesn't work, perhaps try running with the `--reload` flag: `deno run --allow-read --allow-write --allow-env npm:create-vite-extra@latest`. If that still doesn't work, what's the output of `deno info npm:create-vite-extra@latest`?

**Comment by farsightsoftware** [comment]
@dsherret - Thanks! I'm using the latest Deno. Oddly (to me), `--reload` did the trick, it ran successfully and created a project. I can build the project (both client and server), though it'll take some editing to *run* the project with Deno. There are also some TypeScript errors relating to paths that are unfamiliar. I'll have to play with it.

But `--reload` solved this problem, thanks!
