### ISSUE TITLE
deno\buildtools\win\clang-format.exe: invalid argument

### ISSUE THREAD

**Issue by jorsi** [denoland/deno#2045]
![clang_format_error](https://user-images.githubusercontent.com/7156655/55521311-51b89580-564e-11e9-8a58-7f739acebf93.PNG)

This is on Windows 10, in both Powershell and command prompt shell. I have no problem running build.py, test.py, or lint.py.

**Comment by piscisaureus** [comment]
This is too little information to say something meaningful about it.
Maybe you have another version of clang-format installed that's being invoked due to a bug?

**Comment by jorsi** [comment]
Would this have been installed with the Visual Studio C/C++ tools when setting up rust? I’ll try reinstalling those and see what happens.

**Comment by ry** [comment]
@jorsi no, it's downloaded when you run tools/setup.py ... Look at `third_party/depot_tools/clang_format` in the Deno source code.

**Comment by jorsi** [comment]
Hmm, still stuck. I pulled all the sub-modules agin, ran setup.py, and then set quiet=False. Gives a bit more information but still invalid arguments:

![image](https://user-images.githubusercontent.com/7156655/55589494-59377780-56fe-11e9-84e6-4872f6803470.png)

I'll keep poking around and see what I can do.

**Comment by ry** [comment]
Very odd. You'll have to poke at it. But I would copy and paste that last command back into the terminal - and try modifying the arguments. What if you remove the "-i". What if you remove the "-style Google"... See if you can get it to work somehow.

**Comment by jorsi** [comment]
So I eventually got format.py to work by installing LLVM 3.7.0 onto my machine and changing the default clang-format from ./buildtools/win/clang-format.exe to my local machine installed version.

Not exactly sure what is wrong with the ./buildtools/win/clang-format.exe -- it gives invalid argument no matter what arguments are if there are none (e.g. --help, removing -i, removing -style Google, etc. all give the same message).

**Comment by ry** [comment]
stale
