### ISSUE TITLE
[feature-request] `node:util`'s parseArgs

### ISSUE THREAD

**Issue by mizchi** [denoland/deno#20452]
I would like to have node:util parseArgs for Deno as well.

https://nodejs.org/api/util.html#utilparseargsconfig

```ts
import { parseArgs } from "node:util";
const args = parseArgs({
  args: Deno.args,
  options: {
    flag: {
      type: "boolean",
      alias: "f",
    }
  },
  allowPositionals: true,
});

// @ts-expect-error
const f: string = args.values.flag;
```

## Why

- Standard since node 18.3
- It has a good interface for TypeScript inference

I often use deno to make my own little CLI tools, and I tried to use the parseArgs I'm familiar with in deno, but it doesn't exist in deno's node:util.

Of course, I understand that there is a flags module in deno.land/std and the interface is just a matter of preference. But if deno claims to be compatible with node, it would be nice to have it.

**Comment by kt3k** [comment]
Memo: Node.js PR which added util.parseArgs https://github.com/nodejs/node/pull/42675/files

**Comment by jcbhmr** [comment]
for anyone who ends up here from google, there exists a ponyfill for parseargs https://github.com/pkgjs/parseargs#readme

```js
import { inspect, format, ... } from "node:util"
import { parseArgs } from "npm:@pkgjs/parseargs"

const options = {
  help: { type: "boolean" }
}
const { values } = parseArgs({ options })
// ...
```

**Comment by mizchi** [comment]
@kt3k thx!
