### ISSUE TITLE
How to import other extension file with Deno.

### ISSUE THREAD

**Issue by BoltDoggy** [denoland/deno#20469]
```
import config from 'config.yaml'
```

Like: https://bun.sh/docs/runtime/plugins

I need a loader at preload step.

**Comment by markthree** [comment]
> ```
> import config from 'config.yaml'
> ```
> 
> Like: https://bun.sh/docs/runtime/plugins
> 
> I need a loader at preload step.

As far as I know, loader is not currently supported for preloading. You can try using the above code to load yaml

```ts
import { parse } from "https://deno.land/std@0.201.0/yaml/mod.ts";

const configText = await Deno.readTextFile("./config.yaml");

const config = parse(configText);

console.log(config);
```

**Comment by markthree** [comment]
> @markthree 目的不太一样, 因为 deno 支持 bundle, 使用 readTextFile 不能将 config.yaml 也加入到 bundle 中, 而 preload 的插件可以将 config.yaml 处理成 ts 可执行的代码并加入到 bundle, 类似 webpack 可以把 png 等文件变成 base64 加入到 js 产物.
> 
> deno 支持直接 run 一个远程 js 链接来启动 server, 但是大多数 server 都是包含 static file 的, 所以 deno deploy 只能靠支持 github 仓库整个 clone 来实现.
> 
> 如果支持了 preload, 那么 bundle 后的产物就可以完全的做到 run 一个远程 js 路径.

嗯嗯，deno 并不支持这种 `preload`，据我了解 [deno bundle 已被弃用](https://deno.land/manual@v1.36.4/tools/bundler#:~:text=WARNING%3A%20deno%20bundle%20has%20been%20deprecated%20and%20will,which%20includes%20all%20dependencies%20of%20the%20specified%20input.)，未来可能会被直接移除，所以未来可能加入 `loader` 的机率也是比较小的。

可以试试用 `esbuild`，`rollup` 或 `deno_emit` 来实现这一点。

---

Hmm, Deno does not support this type of `preload`. As far as I know, the [Deno bundle has been deprecated](https://deno.land/manual@v1.36.4/tools/bundler#:~:text=WARNING%3A%20deno%20bundle%20has%20been%20deprecated%20and%20will,which%20includes%20all%20dependencies%20of%20the%20specified%20input.) and may be directly removed in the future, so the probability of adding `loader` in the future is also relatively low. You can try using `esbuild`, `rollup`, or `deno_emit` to achieve this.

**Comment by lucacasonato** [comment]
This is not currently supported. https://github.com/denoland/deno/issues/1739
