### ISSUE TITLE
suggestion: `deno upgrade --deps` (to keep dependencies up-to-date)

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno#20487]
Deno is a batteries-included runtime. One common task for maintenance is keeping dependencies up-to-date while ensuring tests are passing. Having this functionality in a module might be cool, but it might be of greater value if included in the runtime itself. I'll outline this idea in greater detail once I get a chance.

**Comment by Malix-Labs** [comment]
Can this be escalated ?

**Comment by Malix-Labs** [comment]
Also see https://pnpm.io/cli/update

**Comment by Malix-Labs** [comment]
Hey @nathanwhit,

>Also, running a similar workflow than pnpm dedup would be nice

Has it been implemented / documented?
