### ISSUE TITLE
compiling issue with  >> import { WebSocketServer } from "npm:ws@^8.14.1" <<

### ISSUE THREAD

**Issue by RandomTimeLP** [denoland/deno#20496]
Using this impot in a "deno run --unstable [etc...]" environment works flawless / as intended but trying to compile it, all of a sudden i get 

'"internal:///missing_dependency.d.ts"' has no exported member 'WebSocketServer'

**Comment by dsherret** [comment]
Do you mean with `deno compile`? You can do `deno compile --no-check ...` or add the following on top of the import:

```ts
// @deno-types="npm:@types/ws@^8.5"
import { WebSocketServer } from "npm:ws@^8.14.1";
```

...that will import the library. We need to improve that error message to be more explanatory.
