### ISSUE TITLE
"this" is undefined inside a function

### ISSUE THREAD

**Issue by microtactical** [denoland/deno#20492]
The keyword "this" is undefined inside a function in Deno. NodeJS returns the reference to the object.

```
function Factory() {
  const testvar = 100
  
  function echo(message) {
    console.log(message)
  }
  console.log(`this=`, this)

  return {
    echo
  }
}

// Should log "this" to the console, but this is undefined. 
const f = Factory()
```

**Comment by nayeemrmn** [comment]
This is the correct behaviour in ESM files. If you run the same code in a `.mjs` file with Node, you'll see `this= undefined`.
