### ISSUE TITLE
`deno test --fail-fast` does not work with multiple test entrypoints

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#20512]
In a folder with `./foo_test.ts` and `./bar_test.ts`:

`deno test --fail-fast ./foo_test.ts` works as expected, but `deno test --fail-fast ./` does not (it waits for both files to be done.

**Comment by bartlomieju** [comment]
@nayeemrmn please take a look

**Comment by nayeemrmn** [comment]
Regression from #17309, fixing
