### ISSUE TITLE
When I use NPM_ CONFIG_ REGISTRY, still requested the original resources

### ISSUE THREAD

**Issue by jiawei397** [denoland/deno#20519]
First, delete cache in Deno dir, which is `deno/npm/registry.npmjs.org`.

The following is a test js file:
```js
import chalk from "npm:chalk@4";
console.log(chalk);
```
When I run ` NPM_CONFIG_REGISTRY=https://registry.npmmirror.com/ deno run test.ts`, it still need to request the original resources in `registry.npmjs.org`. I looked at the registry.json files one by one.
This is unfavorable to guarantee my job in the CI/CD pipeline.

Can I fully access the registry image?

**Comment by kwhinnery** [comment]
Transferred from manual, as this looks like a compat question versus a docs question

**Comment by dsherret** [comment]
@jiawei397 what operating system are you using? Are you using Windows?

When you run with `--log-level=debug` do you see anything like "Invalid NPM_CONFIG_REGISTRY environment variable: ..."?

What you're doing should work. The code is here: https://github.com/denoland/deno/blob/5a1505db67d0326bf37b765c8a566584b44a2c1a/cli/npm/registry.rs#L35

**Comment by jiawei397** [comment]
I'm sorry that I didn't record the version number and operating system when I asked the question. I used Mac and Linux. 
I haven't paid attention to this issue for a while, but now it seems to have been fixed. Thank you.
