### ISSUE TITLE
Allow using `--watch` and `--inspect` at the same time.

### ISSUE THREAD

**Issue by jespertheend** [denoland/deno#20525]
During development I frequently make use of `--watch` for auto reloading. But occasionally I might want to inspect the code that is running. Right now I have to change up the arguments in my deno.json and restart the process, which is somewhat tedious.

It seems like this was intentional (#7610), but I think the current situation is arguably worse. After all, right now if I make a change, I still have to restart the inspector in order to reconnect it. The only difference is that I now have to restart Deno manually as well.

Note though that using the 'dedicated DevTools for Node' option in Chrome does automatically reconnect a closed inspector. I'm not sure which use case #7610 was addressing. But maybe Deno could print a console message informing the user that they might have to reconnect their inspector.

**Comment by dmoebius** [comment]
:+1: Right now I only have the choice between two sub-par options:
1. Use `--watch` and be forced to console logging for debugging
2. Use `--inspect/inspect-brk` and have the full comfort of IDE debugging (VSCode or IntelliJ/Webstorm), but have to restart for every fix

Maybe the Deno runtime can disconnect any inspector on any file change when the watcher is active. As @jespertheend said, Chrome automatically reconnects. 

At the least, Deno should allow `--watch` and `--inspect[-brk]` at the same time, print a big warning about it's deficiencies and leave it up to the user to work around it.

**Comment by bartlomieju** [comment]
This seems reasonable and we can certainly implement that - if I'm not mistaken this should be as easy and removing the restriction in `cli/args/flags.rs` to get it working. PRs are welcome and I'll be happy to provide pointers to the person fixing this.
