### ISSUE TITLE
[jupyter kernel] fetch requests show `BadResource: Bad resource ID`

### ISSUE THREAD

**Issue by shouples** [denoland/deno#20534]
Hello deno crew! :wave:

I've really enjoyed testing out deno with the new `jupyter` kernel subcommand with @rgbkrk, but I'm a bit stumped on one thing: after cloning `main` (as recent as e995ba66cd7400e0c87af6e530e74a6aa7c7c934), I'm seeing consistent odd errors with fetch requests: 
![image](https://github.com/denoland/deno/assets/7707189/8626362a-77a4-49cc-80ab-50a9e123d368)

I've tried running the following on WSL with Ubuntu 22.04:
```bash
deno on  main [?] via 🦀 v1.72.0
❯ deno jupyter --unstable --install
[InstallKernelSpec] Removing existing kernelspec in <home>/.local/share/jupyter/kernels/deno
[InstallKernelSpec] Installed kernelspec deno in <home>/.local/share/jupyter/kernels/deno
✅ Deno kernelspec installed successfully.
```
```bash
deno on  main [?] via 🦀 v1.72.0
❯ cargo run -- jupyter --unstable --install
   Compiling deno_runtime v0.126.0 (<home>/dev/deno/runtime)
   Compiling deno v1.36.4 (<home>/dev/deno/cli)
    Finished dev [unoptimized + debuginfo] target(s) in 2m 10s
     Running `target/debug/deno jupyter --unstable --install`
[InstallKernelSpec] Removing existing kernelspec in <home>/.local/share/jupyter/kernels/deno
[InstallKernelSpec] Installed kernelspec deno in <home>/.local/share/jupyter/kernels/deno
✅ Deno kernelspec installed successfully.
```
Then, followed by `jupyter notebook` with Jupyter Notebook 7.0.3 (also seen with Jupyter Lab 4.0.6)
![image](https://github.com/denoland/deno/assets/7707189/e7fdd69a-91db-4e2a-ad00-000e6147daf9)

Re-running the cell, executing a "Run All" from the notebook UI, and/or waiting multiple seconds between cell executions don't have any effect that I've seen.

_However_, when I `cargo run` with `--features __runtime_js_sources`, shut down my existing kernel, restart local jupyter (probably overkill), and start a new kernel, the issue mysteriously disappears altogether.
```bash
deno on  main [?] via 🦀 v1.72.0
❯ cargo run --features __runtime_js_sources -- jupyter --unstable --install
    Finished dev [unoptimized + debuginfo] target(s) in 0.29s
     Running `target/debug/deno jupyter --unstable --install`
[InstallKernelSpec] Removing existing kernelspec in <home>/.local/share/jupyter/kernels/deno
[InstallKernelSpec] Installed kernelspec deno in <home>/.local/share/jupyter/kernels/deno
✅ Deno kernelspec installed successfully.
```
![image](https://github.com/denoland/deno/assets/7707189/f39be8d0-5d01-49b3-a4ef-53c66fa92b1e)

(And then, if I go back to `cargo run -- jupyter --unstable --install`, shut down my existing kernel, restart local jupyter, start a new kernel, the `BadResource` issue consistently reappears.)

❔ I have _no_ idea why that would fix things based on the feature flag description and @bartlomieju's explanation in https://github.com/denoland/deno/issues/20524#issuecomment-1722286670, but it's the only thing I've found that makes these errors seem to go away.

I couldn't tell if this overlapped at all with https://github.com/denoland/deno/issues/19255 or a couple other issues mentioning the BadResource issue, but this was the most minimal example I could provide specifically running with the jupyter subcommand.

---

Similarly, I saw issues with `Deno.mkdir` and `Deno.writeFile` after using `cargo run -- jupyter --unstable --install`:
![image](https://github.com/denoland/deno/assets/7707189/7197b773-4464-4f3d-bd26-ad9603ae21dd)

...but not with `cargo run --features __runtime_js_sources -- jupyter --unstable --install`:
![image](https://github.com/denoland/deno/assets/7707189/6aff9289-eb91-497a-9679-8269231e3d8b)

Hopefully these examples help - let me know if there's any other information I can provide!

**Comment by bartlomieju** [comment]
Hey @shouples thabks for trying it our. Do you have the same problem if you first `cargo build` and then `target/debug/Deno jupyter --unstable --install`? I might have did a wrong thing for installing kernelspec, I'm saving a path to "current exe" that is doing the install (to make it easier to debug and iterate) but that might be wrong here. Maybe we should add additional arg to `--install` to specify which binary we want to use?

**Comment by shouples** [comment]
@bartlomieju same issue with the debug build, unfortunately:

```bash
deno on  main [?] via 🦀 v1.72.0
❯ cargo build
   Compiling semver v1.0.14
   Compiling test_util v0.1.0 (<home>/dev/deno/test_util)
   Compiling async-stream-impl v0.3.5
   Compiling napi_sym v0.48.0 (<home>/dev/deno/cli/napi/sym)
   Compiling bencher v0.1.5
   Compiling napi-sys v2.2.3
   Compiling test_ffi v0.1.0 (<home>/dev/deno/test_ffi)
   Compiling test_napi v0.1.0 (<home>/dev/deno/test_napi)
   Compiling rustc_version v0.4.0
   Compiling deno_bench_util v0.112.0 (<home>/dev/deno/bench_util)
   Compiling curve25519-dalek v4.1.0
   Compiling async-stream v0.3.5
   Compiling x25519-dalek v2.0.0
   Compiling deno_node v0.55.0 (<home>/dev/deno/ext/node)
   Compiling deno_crypto v0.132.0 (<home>/dev/deno/ext/crypto)
   Compiling deno_runtime v0.126.0 (<home>/dev/deno/runtime)
   Compiling deno v1.36.4 (<home>/dev/deno/cli)
    Finished dev [unoptimized + debuginfo] target(s) in 3m 58s

deno on  main [?] via 🦀 v1.72.0 took 3m58s
❯ ./target/debug/deno jupyter --unstable --install
[InstallKernelSpec] Removing existing kernelspec in <home>/.local/share/jupyter/kernels/deno
[InstallKernelSpec] Installed kernelspec deno in <home>/.local/share/jupyter/kernels/deno
✅ Deno kernelspec installed successfully.
```
![image](https://github.com/denoland/deno/assets/7707189/9769cc4f-891e-4c3c-ac14-bcb941eaef67)

Running `cargo build --features __runtime_js_sources` and  `./target/debug/deno jupyter --unstable --install` makes fetch work as expected again though. 🤔

**Comment by shouples** [comment]
I had a thought earlier that maybe something was going awry with permissions, but it looks like they're the same in both builds. Hmmmm.

![image](https://github.com/denoland/deno/assets/7707189/6705a085-8d80-4488-b20a-d02fe6482cb4)
