### ISSUE TITLE
KV Connect: Please document key serialization format

### ISSUE THREAD

**Issue by johnspurlock** [denoland/deno#20559]
Thanks for producing [public docs](https://github.com/denoland/deno/tree/main/ext/kv#kv-connect) for KV Connect!

It mostly makes sense without having to dive into the rust codebase - but one thing that is opaque is how `KvKey`s are represented as byte arrays.

I'm able to reverse engineer some of it from production key data, appears to be concatenation of key parts according to the following:
 - for string parts: [ 2, ...utf8bytes, 0 ]
 - for byte array parts: [ 1, ...bytes, 0 ]
 - for `false`, `true`, `0n`, known magic single byte values
 - for number parts: [ 33, 8-bytes-of-what? ]
 - for bigint parts: appears to differ whether it's positive or negative.
 

Anyway, including this byte encoding layout in the public doc would be very helpful.

Thanks,
\- John

**Comment by andreubotella** [comment]
This encoding is not something handled by Deno, it's instead produced by the V8 JS engine as part of structured serialization. This format, while backwards-compatible, could change in newer versions of V8, so you might be better off not relying on the current serialization format staying constant.

That said, @MierenManz has a description of this format on her repo https://github.com/MierenManz/v8_format.

**Comment by MierenManz** [comment]
Keys seem to be encoded with a slightly different format. Iirc Arsh & nhrones on discord were working on a port of the kv key codec. That's found here https://github.com/nhrones/kv-key-codec

**Comment by johnspurlock** [comment]
Thanks @andreubotella but I'm not talking about the values, which I understand are v8 encoded due to the nature of the Deno KV product, but rather the _keys_, which appear to use another method.

@MierenManz this is exactly what I was looking for, I see this links to a [FDB doc](https://github.com/apple/foundationdb/blob/main/design/tuple.md) on this too!

Would be nice to include at least a pointer to this key encoding approach in the public KV Connect docs as a hint for implementers.

**Comment by MierenManz** [comment]
You should thank the author of that repo. They figured that out. I just knew it existed.

**Comment by nhrones** [comment]
@johnspurlock   I've also used a copy of @MierenManz  v8-Format, to produce a valid KvValue codec.  I haven't completed my testing against DenoKv-SQLite blobs, But so far it is correct.  It's in a private repo now, but after more examination and documantation, I'll make it public.  It's Not much changed from the original, so perhaps you might have a look there. https://github.com/MierenManz/v8_format/tree/main

**Comment by nhrones** [comment]
@johnspurlock   The key codec is also documented in the Deno source:
https://github.com/denoland/deno/blob/main/ext/kv/codec.rs

**Comment by nhrones** [comment]
@andreubotella  -- v8 serialization returns a two byte Version header - the VERSION flag 0xff followed by the current serialization version number; currently at 0x0f (15).  Any major change would need to be handled by all concerned.

**Comment by nhrones** [comment]
Perhaps this could be closed as the codec is not part of the public API, and the source code does a decent job of exposing the codec details.

**Comment by nhrones** [comment]
https://discord.com/channels/684898665143206084/1138852815725395978/1138852815725395978

**Comment by nhrones** [comment]
@losfair You're welcome.  I started that by looking in the Deno-codec source.  Saw the FDB comment there and followed that,  I've used your test-cases to confirm my codec.

**Comment by nhrones** [comment]
@johnspurlock If you have a use case for my codecs, perhaps you could publish a documented copy to x.  I'll make the value codec repo public.  It is not yet completely vetted.

**Comment by nhrones** [comment]
@johnspurlock  see:
https://github.com/nhrones/kv-value-codec

**Comment by lucacasonato** [comment]
I'll close this as there is nothing actionable left here I think
