### ISSUE TITLE
KV Connect: is `expireIn` available?

### ISSUE THREAD

**Issue by johnspurlock** [denoland/deno#20560]
Is the `expireIn` functionality of `set` (and the `set` mutation in `AtomicOperation`) available over the [KV Connect](https://github.com/denoland/deno/tree/main/ext/kv#kv-connect) protocol?

I don't see it in the `AtomicWrite` area of the protobuf definition.

Thanks,
\- John

**Comment by lucacasonato** [comment]
Not yet, but it is coming soon.

**Comment by johnspurlock** [comment]
excellent, thanks

**Comment by lucacasonato** [comment]
Fixed by #20688

**Comment by johnspurlock** [comment]
Thanks!  Implemented in [kv-connect-kit v0.0.4](https://github.com/skymethod/kv-connect-kit/releases/tag/v0.0.4) - expiration seems to work with an existing Deno Deploy KV db
