### ISSUE TITLE
this._socket.removeListener is not a function

### ISSUE THREAD

**Issue by ry** [denoland/deno#20571]
This has come up with `npm:nodemailer`. See this comment https://github.com/denoland/deno/issues/18303#issuecomment-1699288092

**Comment by littledivy** [comment]
I get the same error in Node.js as well, cc @dehrhard 

```
/Users/divy/gh/node_modules/.deno/nodemailer@6.9.4/node_modules/nodemailer/lib/smtp-connection/index.js:896
        this._socket.removeListener('data', this._onSocketData); // incoming data is going to be gibberish from this point onwards
                     ^

TypeError: this._socket.removeListener is not a function
    at SMTPConnection._upgradeConnection (/Users/divy/gh/node_modules/.deno/nodemailer@6.9.4/node_modules/nodemailer/lib/smtp-connection/index.js:896:22)
    at Immediate.<anonymous> (/Users/divy/gh/node_modules/.deno/nodemailer@6.9.4/node_modules/nodemailer/lib/smtp-connection/index.js:246:26)
    at process.processImmediate (node:internal/timers:478:21)

```

**Comment by dehrhard** [comment]
Hmm why do you think it's a bug in nodemailer? Isn't `removeListener` a method of `socket` and shouldn't that be provided by the deno compatibility layer?

**Comment by littledivy** [comment]
`this._socket` is not the net.Socket object when this code path is executed. You can try the exam same code in Node.js and it still errors.

**Comment by littledivy** [comment]
Oh, the code your reproduction code does not pass the connection option correctly, the error is gone with this change:

```diff
const connection = {
  from: "test@test.com",
  host: "host.host.com",
  port: 587,
  auth: {
    user: "123",
    pass: "456",
  },
};

const smtpClient = createTransport({
- connection,
+ ...connection,
  secure: true,
});
```

**Comment by dehrhard** [comment]
Oh dang, you're right. Looks like I have been misinterpreting the property. Looks like it is actually used for socket configuration which explains a lot 
![image](https://github.com/denoland/deno/assets/48784121/3f713c35-d136-4e43-b50d-3d1e3a0323bc)
I'll try it out and see if it works.

**Comment by dehrhard** [comment]
Hey, I can conform this works now. I knew it was something stupid :smile:  Thanks, and again. Great work.
