### ISSUE TITLE
1.36.4 Win64 - Deno.cwd() is incorrect when Drag & Drop is performed on a Compiled Deno project.

### ISSUE THREAD

**Issue by AlexAnimateMp4** [denoland/deno#20573]
**_Tested on Windows 11 Professional [22621.2134]_**
Here's an example of code to reproduce the problem:
```js
console.log("Args[0]:", Deno.args[0]);
console.log("CWD:", Deno.cwd());
Deno.write(Deno.stdout.rid, new TextEncoder().encode("Press any key to exit."));
Deno.stdin.setRaw(true);
await Deno.stdin.read(new Uint8Array(1));
```
I compile the above example in the **denoland** folder at the **root** of my **C** _drive_. [`C:\denoland`]

I run the example **without** _dragging and dropping_ a folder onto it, I get the **denoland** folder as the **current working directory**. [`C:\denoland`]

When I run the example by _dragging and dropping_ the **nodeland** folder [`C:\nodeland`] onto it, I get the path to the **nodeland** folder as the _first argument_ and the **root** of my **C** drive as the **current working directory**. [`C:\nodeland` - `C:\`]

_**Too bad Node :)**_

**Comment by Seally** [comment]
I wrote this in C++ (okay, C++ using C libraries) with this code and the same thing happens:

```cpp
#include <cstdlib>

int main(int argc, char* argv[]) {
	std::system("echo %CD%");
	std::system("pause");
	
	return 0;
}
```

I don't think this is a Deno bug. Just that Windows Explorer (or whatever the underlying system is called) sets the current working directory of the program to the path that contains the object you dragged onto the executable.

**Comment by bartlomieju** [comment]
As pointed out by @Seally this is the correct behavior - `Deno.cwd()` always returns a current working directory. What are you trying to achieve @AlexAnimateMp4?

**Comment by AlexAnimateMp4** [comment]
@Seally:
> I don't think this is a Deno bug. Just that Windows Explorer (or whatever the underlying system is called) sets the current working directory of the program to the path that contains the object you dragged onto the executable.

I agree with you.
I **solved** my _problem_ by replacing `Deno.cwd()` with `Deno.execPath()` if `Deno.args[0]` is a **correct** _path_.
If anyone can _report_ the **problem** to @microsoft, _I'd be grateful_ ;)
