### ISSUE TITLE
Deploy: KV Viewer crashes with 'String contains an invalid character' when KV value is `new Uint8Array()`

### ISSUE THREAD

**Issue by johnspurlock** [denoland/deno#20586]
To repro: add an entry to your project's KV db with the value: `new Uint8Array()`

Select the "KV" tab in the project dashboard:

Entire tab crashes:
<img width="992" alt="image" src="https://github.com/denoland/deno/assets/528937/88545954-6c5b-45bc-bbc7-336874d66b25">

**Comment by nhrones** [comment]
Are you trying to set value to an empty Uint8Array?

**Comment by johnspurlock** [comment]
Re-filed in deploy feedback repo: https://github.com/denoland/deploy_feedback/issues/507
