### ISSUE TITLE
JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists. When using Preact v10.16.0

### ISSUE THREAD

**Issue by sant123** [denoland/deno#20582]
![image](https://github.com/denoland/fresh/assets/7959437/6c8b65fa-f03b-46f2-9eba-88471b314850)

This is my deno.json

```json
{
  "compilerOptions": {
    "jsx": "react-jsx",
    "jsxImportSource": "preact"
  },
  "tasks": {
    "start": "deno run -A --watch=static/,routes/ dev.ts",
    "vpn": "DENO_DEPLOYMENT_ID=\"$(git rev-parse HEAD)\" deno run -A main.ts"
  },
  "imports": {
    "$fresh/": "https://deno.land/x/fresh@1.3.0/",
    "preact": "https://esm.sh/preact@10.16.0",
    "preact/": "https://esm.sh/preact@10.16.0/",
    "preact-render-to-string": "https://esm.sh/*preact-render-to-string@6.2.0",
    "@preact/signals": "https://esm.sh/*@preact/signals@1.1.5",
    "@preact/signals-core": "https://esm.sh/@preact/signals-core@1.3.1"
  }
}

```

Thanks!

**Comment by guy-borderless** [comment]
for me restarting the LSP / vscode didn't do it, but running `deno check main.ts` and then restarting the LSP did.

**Comment by fhucko** [comment]
I found that adding this import helped, even though VSC shows it is unused:
`import * as JSX from "https://esm.sh/react@18.2.0/jsx-runtime";`
Without this, deno check returns errors.

**Comment by ooker777** [comment]
In my case, I have a core program, and from that I have auxiliary components¹: test, web app, cli app. Initially I worked on the core + cli app + test, then recently I work on the web app with Fresh. At first I separated the project to learn the framework easier. Then I joined them together so that I could debug the core easier. My code works fine when it's in a separate project; all I do is to copy it to the bigger one. Now every component has this problem:
```
JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.deno-ts(7026)
```

Reload VS Code doesn't help.

It turns out that VS Code can recognize the `deno.json` file in the root folder, not the component¹ folder (i.e. `./aux/web/deno.json`). The file also have to have at least these line:
```json
  "compilerOptions": {
    "jsx": "react-jsx",
    "jsxImportSource": "preact"
  },
  "imports": {
    "preact/": "https://esm.sh/preact@10.19.2/"
  }
```

**Comment by adamzerner** [comment]
`deno check main.ts` didn't work for me in my Fresh project.

**Comment by nayeemrmn** [comment]
@adamzerner There was a regression that was fixed recently, try with `deno upgrade --canary`.

**Comment by adamzerner** [comment]
@nayeemrmn Looks like that did the trick. Thanks.

**Comment by phoenisx** [comment]
I am not sure why, but this could be because of typescript typings that the following deno config works and fixes the issue present here:

```json
{
  "compilerOptions": {
    "jsx": "react-jsx",
    "jsxImportSource": "https://esm.sh/react@^18.3.1",
  }
}
```

while the following is broken:

```json
{
  "compilerOptions": {
    "jsx": "react-jsx",
    "jsxImportSource": "react",
    "lib": ["dom", "dom.iterable", "dom.asynciterable", "deno.ns"]
  },
  "nodeModulesDir": "auto",
  "imports": {
    "react": "npm:react@^18.3.1",
    "react-dom": "npm:react-dom@^18.3.1"
  }
}
```

**Comment by nayeemrmn** [comment]
@phoenisx The types for `npm:react` are in `npm:@types/react`, you have to link it:
```json
{
  "compilerOptions": {
    "jsx": "react-jsx",
    "jsxImportSource": "react",
    "jsxImportSourceTypes": "@types/react",
    "lib": ["dom", "dom.iterable", "dom.asynciterable", "deno.ns"]
  },
  "nodeModulesDir": "auto",
  "imports": {
    "react": "npm:react@^18.3.1",
    "react-dom": "npm:react-dom@^18.3.1",
    "@types/react": "npm:@types/react@^18.3.11"
  }
}
```
https://docs.deno.com/runtime/reference/jsx/#jsximportsourcetypes

**Comment by sant123** [comment]
@nayeemrmn do you know if there is a way for a module set a certain `@types` in deno.json? For example this is how I get types from both `react` and `react-dom/server` in code:

```tsx
// @deno-types="@types/react"
import { version } from "react";

// @deno-types="npm:@types/react-dom@^18.3.1/server"
import { renderToStaticMarkup } from "react-dom/server";

const html = renderToStaticMarkup(<h1>Hello world!</h1>);

console.log(html, version);

```

It would be nice to not type `@deno-types...` for each `react` import.

**Comment by sant123** [comment]
Just found what I mentioned https://github.com/denoland/deno/issues/25633
