### ISSUE TITLE
How can I use Deno now?

### ISSUE THREAD

**Issue by amiteshore** [denoland/deno#2058]
How can I use the Deno API now?

Like importing `fs`, `path` or `os` modules and then using in node, 
how can I explore the Deno API now?

I looked at the official Deno API documentation in [here](https://deno.land/typedoc/).

I did installed Deno on my computer and It perfectly running all .ts files.

**Comment by bartlomieju** [comment]
Check out [deno's standard library](https://github.com/denoland/deno_std) and [module registry](https://deno.land/x/). 

You can import modules referencing them by url:
```ts
// script.ts
import * as log from "https://deno.land/std/log/mod.ts";

log.debug("Hello world");
```
```bash
$ deno script.ts
Hello world!
```

If you have any questions feel free to join [gitter chat](https://gitter.im/denolife/Lobby)

**Comment by amiteshore** [comment]
Yeah, thanks. I got it.
Closing...
