### ISSUE TITLE
feat(lsp): cacheOnSave

### ISSUE THREAD

**Issue by sigmaSd** [denoland/deno#20587]
cache on save is currently implemented on vscode, but I think it makes sense to transfer it to the lsp server, so all editors benefit from this, I think it should be straightforward to add:

- listen to `textDocument/didSave` notification from client
- if the user has sent `settings.deno.cacheOnSave = true` in the init request:
  - look for uncached imports and if there is run cache command

**Comment by nayeemrmn** [comment]
Seems like the difficult part is short-circuiting if there's no `no-cache` diagnostics. While it's easy on the client, our server needs a bit of rearchitecting to know that information since we don't save published diagnostics.
