### ISSUE TITLE
Deno Userland Jupyter Messaging library: `display_data`

### ISSUE THREAD

**Issue by rgbkrk** [denoland/deno#20591]
# The `display` protocol

## Overview

The kernel needs support for the display protocol to allow for rich (and updatable) outputs, similar to what IPython offers. This involves implementing the [`display_data`](https://jupyter-client.readthedocs.io/en/latest/messaging.html#display-data) and [`update_display_data`](https://jupyter-client.readthedocs.io/en/latest/messaging.html#update-display-data) Jupyter message types, and exposing a user-friendly interface for them.

## Goals

* Allow users to display rich media types.
* Provide asynchronous display updates.
* Implement a TypeScript-based API similar to IPython's `display`

## Formatting

The `Symbol.for("Jupyter.display")` standard is working really well for formatting objects for the `execute_result` message. For those who haven't touched the Jupyter bits yet, the `execute_result` is the result of a REPL run -- the final expression in a cell.

```typescript
let x = 2
x + 1
```

Here `x + 1` is the final expression.

Sometimes people want to be able to display an object asynchronously or even display a sequence of them, just like with `console.log`. That's where the `display_data` and `update_display_data` messages come in handy via Jupyter.

How we choose to automatically format objects should be a separate issue from creating this ability to send these messages. In fact, there's probably room for us to have a userland API for sending raw messages so that new libraries can be built around some basic primitives. There are probably JS-centric ways of writing and thinking about this so I don't wish to impart too much Python in how I describe this (other than by example).

## Proposed Interface

```typescript
type DisplayOptions = {
  display_id?: string;
  update?: boolean;
};

function display(obj: unknown, options?: DisplayOptions);
```

### Example messages

Calling `display("hi")` will create an iopub message like this:

```json
{
  "header": {
    "msg_id": "<uuid>",
    "username": "kyle",
    "session": "<session_id>",
    "msg_type": "display_data",
    "version": "5.3"
  },
  "parent_header": {},
  "metadata": {},
  "content": {
    "data": {
      "text/plain": "hi"
    },
    "metadata": {},
    "transient": {}
  },
  "buffers": [],
  "channel": "iopub"
}
```

whereas running `display("hi", { display_id: "1234" })` will create the following message:

```json
{
  "header": {
    "msg_id": "<uuid>",
    "username": "kyle",
    "session": "<session_id>",
    "msg_type": "display_data",
    "version": "5.3"
  },
  "parent_header": {},
  "metadata": {},
  "content": {
    "data": {
      "text/plain": "hi"
    },
    "metadata": {},
    "transient": {
      "display_id": "1234"
    }
  },
  "buffers": [],
  "channel": "iopub"
}
```

When `display("hi", { display_id: "1234", update: true })` is run, the message will be 

```json
{
  "header": {
    "msg_id": "<uuid>",
    "username": "kyle",
    "session": "<session_id>",
    "msg_type": "update_display_data",
    "version": "5.3"
  },
  "parent_header": {},
  "metadata": {},
  "content": {
    "data": {
      "text/plain": "hi"
    },
    "metadata": {},
    "transient": {
      "display_id": "1234"
    }
  },
  "buffers": [],
  "channel": "iopub"
}
```

## Prior art (`IPython.display`)

In IPython there's a display interface that works much the same, though with a few more niceties of creating the `display_id` for the user.

```python
df = pd.read_csv("food.csv")
display(df)
```

Which you can also use to update a previous output:

```python
df = pd.read_csv("food.csv")

handle = display(df.sample(3), display_id=True)

time.sleep(1)

handle.update(df.sample(3), display_id=True)
```

**Comment by rgbkrk** [comment]
cc @bartlomieju @mmastrac

**Comment by ellisonbg** [comment]
Thanks for opening this @rgbkrk - great to see this work. A few questions related to this. Is there (or should there be) a typed interface that is equivalent to the MIME bundle of Jupyter, with the keys as MIME types and the values are the data? Should there be a way to extract a MIME bundle from an object? I think the `display` API you are working through makes sense, wondering how people building objects declare "here is how to display me". In Python this is done through all of the special display methods `_repr_html_`, wondering what the JavaScripty way of doing that is.

**Comment by rgbkrk** [comment]
The way that we started off with this for the formatting side is including a callable property on `Symbol.for("Jupyter.display")` that returns a MIME bundle.

```typescript
class Example {
    [Symbol.for("Jupyter.display")]() {
        return {
            "text/html": "We are the 🦕<b>saurs</b>"
        }
    }
}

new Example()
```

<img width="432" alt="image" src="https://github.com/denoland/deno/assets/836375/b3dcda27-cab8-46ab-aec7-993c753a6187">

It does look a little strange, but the `Symbol.for` is a builtin that's used in node for similar practices. From MDN:

> The `Symbol.for()` static method searches for existing symbols in a runtime-wide symbol registry with the given key and returns it if found. Otherwise a new symbol gets created in the global symbol registry with this key.

You can set this property on any class or object, including arrays (not that one should...).

**Comment by rgbkrk** [comment]
I'd prefer to keep the object a mimebundle to keep the interface simple. That would also limit the ability to replace previous content.

However, this is all separate from our current `execute_result` handling. The main ask is to get some sort of primitive way to send any iopub message asynchronously. Maybe we could start on it in a branch and then I can build on top of that. I can show you some really neat ways to use these primitives that'll be easier to understand with code.

**Comment by bartlomieju** [comment]
The only way of doing that that I can think of is adding an API like `Deno.jupyter.sendIo()` - would that work in this case?

**Comment by rgbkrk** [comment]
I'm realizing that we'll somehow need the `parent_header` so that any new outputs created via `sendIo` will match the original `execute_request`. You'll have to bake that into the `sendIo` call.

For prior art to look at, I'd check out `publish` from the IPython ZMQ Display Publisher: https://github.com/ipython/ipykernel/blob/main/ipykernel/zmqshell.py#L80

Example you can run in an IPython notebook session:

```python
ip = get_ipython()

session = ip.display_pub.session

message = session.msg(
    'display_data',
    content={
        'data': {
            'text/plain': 'Here it is!'
        },
        'metadata': {
            'text/plain': { "good": True }
        }
    },
    parent=ip.parent_header
)

_ = session.send(ip.display_pub.pub_socket, message, 'display_data')
```

**Comment by bartlomieju** [comment]
@rgbkrk am I correct in assuming that this message should always be associated with previous evaluation request? If so that's easy to handle as we store the previously received message as `JupyterServer.last_execution_request`.

**Comment by rgbkrk** [comment]
Nice, yes that works!

When we have comms situated we'll have to take into account any comm that would trigger messages. For today, totally spec compliant to just go with that last execution request.
