### ISSUE TITLE
invoking deno jupyter from the cli ouputs "Deno kernel already installed" and does nothing

### ISSUE THREAD

**Issue by guy-borderless** [denoland/deno#20599]
![image](https://github.com/denoland/deno/assets/100129659/3ede2b87-4071-4332-97e7-3eb89f2a6fdc)
Opening with the deno kernel from jupyter notebooks works

**Comment by guy-borderless** [comment]
@rgbkrk

**Comment by bartlomieju** [comment]
When Deno installs the kernelspec it calls out to `jupyter kernelspec --install`. Do you see `deno` in `jupyter kernelspec --list`?

**Comment by guy-borderless** [comment]
yes
`jupyter kernelspec list`
```
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
Available kernels:
  deno       /home/guy/.local/share/jupyter/kernels/deno
  python3    /usr/share/jupyter/kernels/python3
                                                                                                                   
```

**Comment by bartlomieju** [comment]
@rgbkrk could you advise here? Is it possible there are multiple Jupyter installations and the one Deno uses is not used by the editor?

**Comment by rgbkrk** [comment]
While multiple Jupyter installations can exist, the kernelspecs are more broadly available to all. This looks like VS Code is not seeing this kernel when installed in `~/.local/share`. I'm tempted to suggest copying the kernel spec from there to the `/usr/share` directory.

I'll see if there's more we can run to figure out why VS Code isn't seeing that.

**Comment by huix11** [comment]
3

**Comment by bartlomieju** [comment]
Given that #20600 is resolved, should we close this issue now?

**Comment by guy-borderless** [comment]
> Given that #20600 is resolved, should we close this issue now?

are those connected?

**Comment by bartlomieju** [comment]
It appears so - the situation from this issue is not really a bug - since you see `deno` installed when running `jupyter kernelspec --list` I think it's working correctly. I can improve printed information in a follow up PR.

**Comment by guy-borderless** [comment]
Ah, so `deno jupyter --unstable` should output `Deno kernel already installed`

**Comment by bartlomieju** [comment]
That's correct - it will either tell you that it's already installed and you're ready to go or that you should install it; with #20601 we can add a prompt to this subcommand.

**Comment by guy-borderless** [comment]
> That's correct - it will either tell you that it's already installed and you're ready to go or that you should install it; with #20601 we can add a prompt to this subcommand.

Ah I see, I thought it would launch Jupyter with the deno kernel selected or something

**Comment by rgbkrk** [comment]
Should we have called it `deno kernel`?

```
deno kernel --install
```

```
deno kernel --connection-file=somewhere.json
```
