### ISSUE TITLE
Deno kernel not found in vscode jupyter notebooks extension

### ISSUE THREAD

**Issue by guy-borderless** [denoland/deno#20600]
[Screencast from 2023-09-21 07-57-22.webm](https://github.com/denoland/deno/assets/100129659/f1421b10-2e10-4fef-9285-6488501c6c61)
(also kernel can be added to the vscode marketplace with @tag:notebookKernelJupyterNotebook )

**Comment by bartlomieju** [comment]
@guy-borderless what is the output you get from `jupyter kernelspec --list`?

**Comment by guy-borderless** [comment]
`jupyter kernelspec list`
```
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
Available kernels:
  deno       /home/guy/.local/share/jupyter/kernels/deno
  python3    /usr/share/jupyter/kernels/python3
                                                                                                                   
```

**Comment by rgbkrk** [comment]
What do you see in the settings for `jupyter.kernels`:

<img width="582" alt="image" src="https://github.com/denoland/deno/assets/836375/06fa6e2b-b16d-4ff9-a17e-e7da0eb61a14">

Possibly related -- VS Code may have a bug where it's not picking up kernels in those locations. https://github.com/microsoft/vscode-jupyter/issues/3918

However, it looks like it's looking at that directory just fine:

https://github.com/microsoft/vscode-jupyter/blob/79dc9b1027a47df91fd9d7aa2272855b21b26f76/src/kernels/raw/finder/jupyterPaths.node.ts#L31

@DonJayamanne -- any tips? We just launched a Deno kernel (TypeScript and JavaScript) and some users are reporting not being able to see the kernel in VS Code. Only reported on Linux. Windows and Mac users seem to be doing alright anecdotally.

**Comment by guy-borderless** [comment]
![image](https://github.com/denoland/deno/assets/100129659/8278ecbf-f4fc-4fd5-a23f-0e96fa9dea8f)
maybe you're using some extension? I'm using the built in support

**Comment by guy-borderless** [comment]
I installed the Jupyter pack, still no deno though
[Screencast from 2023-09-21 17-25-49.webm](https://github.com/denoland/deno/assets/100129659/99576b1f-3a19-4218-ac31-a083c2f5d0af)

**Comment by rgbkrk** [comment]
Ok, now that the jupyter package is installed, fully restart VS Code. Then run "Start new Jupyter Notebook" from the command palette.

**Comment by guy-borderless** [comment]
installed
![image](https://github.com/denoland/deno/assets/100129659/e89b2f50-bff5-434c-adc8-24935d467915)
restarted,
"Create: New Jupyter Notebook" 
no deno

**Comment by rgbkrk** [comment]
Darn. Thanks for trying. It shows both "Python Environments" and "Jupyter kernels" from the dropdown right?

**Comment by guy-borderless** [comment]
> Darn. Thanks for trying. It shows both "Python Environments" and "Jupyter kernels" from the dropdown right?

yes

**Comment by guy-borderless** [comment]
Oh when clicking "jupyter Kernel" it has deno ha :)
![image](https://github.com/denoland/deno/assets/100129659/29d2012a-0ad2-4d38-8564-133942283e00)
haha all good

**Comment by rgbkrk** [comment]
I think you've now helped create some great documentation for the next person needing this. We need this in the new deno docs.

**Comment by DonJayamanne** [comment]
> Available kernels:
  deno       /home/guy/.local/share/jupyter/kernels/deno


First, I'm sorry you guys are running into this issue in linux
To better help you, please can you enable verbose logging as follows and share the logs
* I'm looking for the message `Getting Jupyter KernelSpec Root Path` along with the value where kernelspecs are searched
* & possibly some messages as to why a kernelspec may have been hidden/ignored in the logs


Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by DonJayamanne** [comment]
Note: the fact taht Jupyter extension isn't finding the kernel means its a problem with Jupyter extension
Just wanted to make that clear to everyone looking at this issue.

**Comment by DonJayamanne** [comment]
@guy-borderless given that you got it working, i think this issue can be closed 
Or is Jupyter extension still not detecting your deno kernel on linux?

**Comment by huix11** [comment]
1

**Comment by rgbkrk** [comment]
We figured it out. Had to look in Jupyter Kernels section from a notebook after backing out through the kernels menu from the Python envs.

Thanks for responding!

**Comment by KarlMeierMattern** [comment]
> Darn. Thanks for trying. It shows both "Python Environments" and "Jupyter kernels" from the dropdown right?

Hi there! I am having the issue where "Jupyter kernels" does not show from the dropdown. Only shows "Python environments" and "Existing jupyter server"

**Comment by valVk** [comment]
The same issue here

**Comment by optain-robert** [comment]
For those that just see Python environments" and "Existing jupyter server", make sure you run the command deno jupyter --install and restart VS Code
