### ISSUE TITLE
Support Jiti (unjs)

### ISSUE THREAD

**Issue by birkskyum** [denoland/deno#20607]
Jiti - [GitHub](https://github.com/unjs/jiti)

**Platform**

Darwin 22.6.0 arm64 arm

**Version**

deno 1.37.0

**Repro**

```ts
// import console from "node:console";
let sum = 2+2;
console.log(`2+2 = ${sum}`);
console.log("Print this");
```

**Expected**

This output:

```sh
2+2 = 4
Print this
```

**Actual**

```rust
➜ deno run -A npm:jiti index.ts
error: Uncaught TypeError: Cannot read properties of undefined (reading 'log')
    at data::3:9
    at data::5:4
    at evalModule (file:///Users/admin/Library/Caches/deno/npm/registry.npmjs.org/jiti/1.19.3/dist/jiti.js:1:255456)
    at jiti (file:///Users/admin/Library/Caches/deno/npm/registry.npmjs.org/jiti/1.19.3/dist/jiti.js:1:253384)
    at Object.<anonymous> (file:///Users/admin/Library/Caches/deno/npm/registry.npmjs.org/jiti/1.19.3/bin/jiti.js:15:1)
    at Object.<anonymous> (file:///Users/admin/Library/Caches/deno/npm/registry.npmjs.org/jiti/1.19.3/bin/jiti.js:17:4)
    at Module._compile (node:module:733:34)
    at Object.Module._extensions..js (node:module:747:10)
    at Module.load (node:module:658:32)
    at Function.Module._load (node:module:539:12)
    at Object.loadCjsModule (ext:deno_node/02_init.js:52:22)
    at loadCjsModule ([ext:ext/node/lib.rs:595:29]:2:32)
    at [ext:ext/node/lib.rs:595:29]:3:7
```

**Additional info**

This works if importing `node:console`

**Comment by bartlomieju** [comment]
Did some digging into it - what Jiti is doing is wrapping the provided code using `Module.wrapSafe`, resulting in:
```
(function (exports, require, module, __filename, __dirname, Buffer, clearImmediate, clearInterval, clearTimeout, console, global, process, setImmediate, setInterval, setTimeout, performance) { (function (exports, require, module, __filename, __dirname) {"use strict";
let sum = 2 + 2;
console.log(`2+2 = ${sum}`);
console.log("Print this"); /* v7-ff3385c374396619 */
}).call(this, exports, require, module, __filename, __dirname); })
```

The problem is that after this wrapping, this function is evaluated directly and that causes the wrapper to miss some variables (everything after `Buffer`). We need to explicitly provide these variables somehow.

**Comment by birkskyum** [comment]
As @pi0 mentioned [here](https://github.com/unjs/jiti/issues/168#issuecomment-1729581658), it might be necessary with an adapter to get this working, since Deno doesn't support the .cjs and thus can't skip jiti entirely the same way Bun does.

**Comment by bartlomieju** [comment]
That's for floating the link @birkskyum, I will try to fix it (need to refresh my memory on the details of `vm` module); maybe we don't need to change anything in `jiti` after all. We have mechanisms to execute CommonJS, it's just they are not exposed to user code (but `npm` packages can use these mechanisms).

**Comment by birkskyum** [comment]
Ah, interesting. If possible, that does sound like the better approach, because I doubt people would adopt Deno for Nuxt development if the transformer solution made the dx slower.

**Comment by pi0** [comment]
Thanks for following up on this @bartlomieju @birkskyum ❤️  Please let me know if could help on this (i am reachable via `pi0` in discord as well).

**Comment by birkskyum** [comment]
@littledivy , just tried this with the latest canary (after the vm PR). I still see the same error:

`error: Uncaught TypeError: Cannot read properties of undefined (reading 'log')`

**Comment by birkskyum** [comment]
I was curious to see if BYONM helped here, so I tried running this with latest deno and `DENO_FUTURE=1 deno task dev` which executed `jiti index.ts` in package.json, but it gives the same output.

**Comment by birkskyum** [comment]
This appear to work with the deno 2.0.0-rc.2+aaf2bf4

**Comment by pi0** [comment]
Right before jiti v2 release, we will use a fast path for Deno, still impressive how Deno Node.js compatibility had been improved. ❤️
