### ISSUE TITLE
ext/node: panic on "already borrowed" (BorrowMutError) on 1.36.4

### ISSUE THREAD

**Issue by lucab** [denoland/deno#20615]
On one of our services we observed a panic when using `node:async_hooks`:
```
thread 'main' panicked at 'already mutably borrowed: BorrowError',
~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/deno_node-0.55.0/lib.rs:142:1
```

This seems to panicking around `op_node_is_promise_rejected`, but it isn't immediately clear to me what's going on:
https://github.com/denoland/deno/blob/c0617d11f6391f1b1b3afffe0152c73b5989ab80/ext/node/lib.rs#L142-L149

This was observed on some JS logic using `AsyncLocalStorage.run()` in the following way:
```ts
import { HTMLRewriter } from "https://ghuc.cc/worker-tools/html-rewriter/index.ts";
import { AsyncLocalStorage } from "node:async_hooks";

const storage = new AsyncLocalStorage<string>();

export reproducer () => {
  // works
  return new HTMLRewriter().transform(new Response("Hello World"));

  // doesn't work
  return storage.run("foo", () => {
    return new HTMLRewriter().transform(new Response("Hello World"));
  });
};
```

**Comment by Skn0tt** [comment]
Blcoked on https://github.com/denoland/deno/issues/20615.

**Comment by lucab** [comment]
This portion of  `deno_node` got recently reworked in 1.37.0 at https://github.com/denoland/deno/pull/20489, we suspect that may have fixed the issues as a side-effect.
I'll re-check this as soon as we move to the new version, and report back here.

**Comment by lucab** [comment]
We upgraded to 1.37.0 internally and can confirm that this issue was already fixed there. Closing.
