### ISSUE TITLE
deno fmt: option to leave jsonc keys unquoted

### ISSUE THREAD

**Issue by akriegman** [denoland/deno#20623]
First off, there's several formats called jsonc, so I want to clarify that the one deno uses is [this one](https://github.com/komkom/jsonc/tree/master). This format allows the keys to be unquoted, and if I put this in my `deno.jsonc`:
```jsonc
{
  tasks: {
    dev: "deno run --watch main.ts"
  }
}
```
then `deno task dev` works as expected. It even works if I rename the file to `deno.json`. However, if I `deno fmt` the file, it puts the quotes back. I think not quoting the keys is a great boost for readability and writability since `deno.jsonc` is meant to be read and written by humans, and it would be nice to be able to edit `deno.jsonc` in my editor while using `deno lsp` without having this reverted. So could we add a `deno fmt` option to leave jsonc keys unquoted? I would even argue that this should be the default behavior. (Or maybe the default behavior should be to preserve, and `deno init` should make a `deno.jsonc` with unquoted keys.)

**Comment by dsherret** [comment]
This is beyond the scope of the configuration options for `deno fmt` and prettier does not support such an option. I'd recommend just using quotes because it will work better with other tooling and you won't run into any unhandled behaviour doing this. The deno.jsonc file is seldomly edited.
