### ISSUE TITLE
Do no/de have to be coupled with V8?

### ISSUE THREAD

**Issue by zzz6519003** [denoland/deno#2063]

**Comment by zzz6519003** [comment]
:beer:

**Comment by hayd** [comment]
Theoretically no, practically/for the moment yes. Libdeno could be written for spidermonkey etc but there's no reason to do this atm. One day, perhaps, there could be alternative backends.

**Comment by galkowskit** [comment]
https://github.com/nodejs/node-chakracore
No, it doesn't have to be on V8. Here is an example of Node.js based on Chakra (Edge). But I think it's out of the scope for Deno project ATM.
