### ISSUE TITLE
`deno fmt` should use same symbol for unordered lists

### ISSUE THREAD

**Issue by scarf005** [denoland/deno#20638]
like how `deno fmt` converts alternate heading syntax(`=`) to primary syntax(`#`), the same should also be done for [unordered lists](https://www.markdownguide.org/basic-syntax/#unordered-lists), which has two alternate syntax (`*`, `+`).

## Before `deno fmt`

```md
Alternate Syntax for H1
=======================

Alternate Syntax for H2
-----------------------

- a
* b
+ c
```

## Expected output

```md
# Alternate Syntax for H1

## Alternate Syntax for H2

- a
- b
- c
```

## Actual output

```md
# Alternate Syntax for H1

## Alternate Syntax for H2

- a

* b

- c
```

**Comment by dsherret** [comment]
This is expected. See the commonmark spec (https://spec.commonmark.org/0.30/#lists):

> Changing the bullet or ordered list delimiter starts a new list:

https://spec.commonmark.org/0.30/#example-301
