### ISSUE TITLE
Autocompletion doesn't work in VSCode jupyter notebooks + deno kernel

### ISSUE THREAD

**Issue by btwiuse** [denoland/deno#20657]
To reproduce:

- Create a new Jupyter Notebook in VS Code.
- Set the kernel to Deno.
- Enter a cell: `let x = 42`
- Execute the cell
- Enter another cell: `x.`

Autocompletion doesn't show up when I press tabs. It currently works only in jupyterlab.

Is there any way to get it working in VSCode?

**Comment by btwiuse** [comment]
Update: I discovered by accident that if you change the language from "typescript" to "python", autocompletion works immediately when `.` is pressed

<img width="621" alt="image" src="https://github.com/denoland/deno/assets/54848194/07806d67-9270-4bc1-a729-15568c06c037">

**Comment by bartlomieju** [comment]
Thanks for reporting, that's quite strange! I'll take a look at the extension and see if that's the problem with how it treats TS cells or problem on the Deno side.

**Comment by bartlomieju** [comment]
CC @rgbkrk

**Comment by DonJayamanne** [comment]
Hi, I’m one of the engineers working on vscode and support for Jupyter notebooks in vscode
I’ll take a look and see what’s going on at our end

**Comment by DonJayamanne** [comment]
@rgbkrk @bartlomieju 
Perhaps you can help me, I didn't want to create a new issue and sorry for highjacking this issue.
I've installed the latest versin of deno 1.37
regular stuff works, but not wirdgets.
I'm assuming thats because widgets are still a WIP 
Or do I need to do something different

This is the error message I'm getting
```
Stack trace:
Error: Deno.jupyter is only available in `deno jupyter` subcommand.
    at Object.get (ext:cli/runtime/js/99_main.js:550:15)
    at hasJupyterBroadcast (https://deno.land/x/display@v1.1.1/mod.ts:69:5)
    at display (https://deno.land/x/display@v1.1.1/mod.ts:189:8)
    at <anonymous>:3:7
```

**Comment by rgbkrk** [comment]
The last patch release was missing this hardening of the `jupyter` namespace: https://github.com/denoland/deno/pull/20710

If you want to try out widgets (really only anywidget), you'll need to build from source or install the canary:

```
deno upgrade --canary
```

You can also target a specific commit like:

```
deno upgrade --canary --version=6cb5d8eb86fe205ad4f4411e20c206246ff25682
```

One other note on widget support -- there is only sending, no receiving.

**Comment by karelklima** [comment]
Autocompletion does not work for me **on Windows** if Deno and Python are installed **via scoop**. I uninstalled everything and installed Deno using the recommended PowerShell command and Python using Windows installer, which fixed the problem.
