### ISSUE TITLE
`Response.redirect` throws when providing relative paths.

### ISSUE THREAD

**Issue by jespertheend** [denoland/deno#20674]
The following code works when running in my browser console:
```js
Response.redirect("/test").headers.get("Location") // 'https://github.com/test'
```

But when running it in Deno:
```
deno eval 'Response.redirect("/test")'
error: Uncaught TypeError: Invalid URL: '/test'
Response.redirect("/test")
         ^
    at getSerialization (ext:deno_url/00_url.js:89:11)
    at new URL (ext:deno_url/00_url.js:380:27)
    at Function.redirect (ext:deno_fetch/23_response.js:264:23)
    at file:///home/jesper/repositories/driftwood-island/$deno$eval:1:10
```

Not sure to what extent this is intentional. [The spec states](https://fetch.spec.whatwg.org/#dom-response-redirect):
> The static redirect(url, status) method steps are:
> 1. Let parsedURL be the result of [parsing](https://url.spec.whatwg.org/#concept-url-parser) url with [current settings object](https://html.spec.whatwg.org/multipage/webappapis.html#current-settings-object)’s [API base URL](https://html.spec.whatwg.org/multipage/webappapis.html#api-base-url).

And I suppose Deno doesn't really have a 'current settings object'. But it seems strange that I can't make it use a relative path, since the `Location` header supports relative paths already.

**Comment by andreubotella** [comment]
In browsers, `Response.redirect()` parses relative paths against the API base URL (that is, the webpage's URL, unless you have a `<base>` element somewhere in the page), and then sets the host and location headers to the hostname and pathname+search of the resulting absolute URL. In browsers, this base URL is set per-page, and always has the same value until you navigate the page.

What you probably want is that, if you're calling `Response.redirect()` from the callback you pass to `Deno.serve`, it would use the request's URL as the base URL. However, this would mean calling `Response.redirect()` from the same Deno process but from different places would get different results, and it wouldn't be clear what to do if you're not calling it from a server callback. And that's not even getting into how Deno would detect that you're inside such a callback, given that you'd probably expect it to work across await points...

Deno *does* let you pass in the `--location` flag to set a base URL for the entire process, though: https://docs.deno.com/runtime/manual/runtime/location_api

**Comment by lucsoft** [comment]
How should a Response know a request exists? that sounds really like magic

**Comment by jespertheend** [comment]
@lucsoft You can already do the following:
```js
new Response(null, {
    status: 302,
    headers: {
        Location: "/relative/path",
    }
})
```
I was simply trying to find a shorthand for this, and I was hoping `Response.redirect()` was that shorthand.
