### ISSUE TITLE
JupyterLite (a browser version of JupyterLab) kernel wanted

### ISSUE THREAD

**Issue by MRYingLEE** [denoland/deno#20671]
It is great that Deno provides a JupyterLab Kernel.

JupyterLite (https://github.com/jupyterlite/jupyterlite) is a browser version of JupyterLab.

Can you bring a similar kernel to it?

**Comment by lucacasonato** [comment]
This would require running Deno in the browser in a web worker (likely via compilation to WASM). This is not something we will support in the near future, or ever, as V8 (our JS engine) does not compile to WASM. If you'd like to use Jupyter with Deno from nothing but a browser, consider checking out a hosted version of Jupyter, like with [notable.io](https://platform.noteable.io/blog/experimenting-with-deno-notebooks/).
