### ISSUE TITLE
[jupyter] Allow running unit tests in a notebook

### ISSUE THREAD

**Issue by cdoremus** [denoland/deno#20677]
This issue is a request to add the ability to run unit tests using `Deno.test` and the `std/testing/bdd` module in a Jupyter notebook.

I think that having a Jupyter notebook would aid the learning of new Deno concepts and coupling examples with tests would allow for learning reinforcement. In my case, I'd like to provide a notebook to go along with blog posts I write about Deno topics and include unit tests in those notebooks. I also think it would be nice to have a notebook link on Deno manual pages, so that readers could try out things they are learning with tests to reinforce their learning. In addition, I think that unit tests would aid data analysis to make sure that data manipulation routines are correct before they are run on real data.

**Comment by bartlomieju** [comment]
@nayeemrmn you had an idea how this could be done. Can you share in more detail what that would entail?

**Comment by nayeemrmn** [comment]
Closed by #20778.
