### ISSUE TITLE
Map.prototype.entries shows "TypeError: Cannot read properties of undefined (reading 'length')"

### ISSUE THREAD

**Issue by rendaardy** [denoland/deno#20676]
## Step to reproduce

Here's the snippet code
```js
const map = new Map()
map.set("a", 1)
map.set("b", 2)
console.log(map.entries())
```

And running the code using `deno run` gives the output
![Screenshot from 2023-09-25 22-29-41](https://github.com/denoland/deno/assets/20860625/d6e08653-5e89-4bb3-9ec1-6393e541740d)

## Expected behavior

It should not throw an error and show the correct result
![Screenshot from 2023-09-25 22-36-50](https://github.com/denoland/deno/assets/20860625/7d91444c-0cd4-4bd2-a058-c693da0fd1c6)

Deno version I'm currently using
```
deno 1.37.0 (release, x86_64-unknown-linux-gnu)
v8 11.8.172.3
typescript 5.2.2
```

Related issue #19776

**Comment by crowlKats** [comment]
Closing as this is fixed.
