### ISSUE TITLE
Deno Getting started - add information to avoid error 5097 import path can only end with a '.ts' extension 

### ISSUE THREAD

**Issue by surfmuggle** [denoland/deno#20708]
In [manage dependencies](https://docs.deno.com/runtime/tutorials/manage_dependencies) the follwing code is given:

```ts
/**   example.ts  */
import { add, multiply } from "./deps.ts";

function totalCost(outbound: number, inbound: number, tax: number): number {
  return multiply(add(outbound, inbound), tax);
}

console.log(totalCost(19, 31, 1.2));
```
The line `import { add, multiply } from "./deps.ts";` results in the error

> An import path can only end with a '.ts' extension when 'allowImportingTsExtensions' is  enabled.ts(5097)

[This answer](https://stackoverflow.com/a/63289023/819887) suggested to add `@ts-ignore` above the import

```ts
// @ts-ignore
import { add, multiply } from "./deps.ts";
``` 
Which did work for me; problem solved. 

I suggest do add some information to the [basic examples](https://docs.deno.com/runtime/tutorials/#basic) how to configure a deno project or to add the ignore hint as above.

**Comment by sigmaSd** [comment]
You're not using deno lsp, make sure to enable it , you can check the editors section of the docs.

**Comment by surfmuggle** [comment]
I assume that [this section using and editor / ide](https://docs.deno.com/runtime/manual/getting_started/setup_your_environment#using-an-editoride) is meant?

My intent is to improve the [tutorials](https://docs.deno.com/runtime/tutorials). This could be done by either adding a recommendation to first setup the environment or by adding other pointers. 

For example  [Manual - Built in web APIs](https://docs.deno.com/runtime/manual/#built-in-web-apis-and-the-deno-namespace) has this code

```ts
const site = await fetch("https://www.deno.com");
console.log(await site.text());
```

And does not mention anything that the environment must be configured before. Running the above script with `deno run -A HelloDeno\helloFetch.ts`  results in 

> C:\Apps\Deno>deno run -A HelloDeno\helloFetch.ts
> error: Uncaught (in promise) TypeError: error sending request for url  (https://www.deno.com/): error trying to connect: received corrupt message of type  InvalidContentType
> const site = await fetch("https://www.deno.com");
>             ^
>    at async mainFetch (ext:deno_fetch/26_fetch.js:277:12)
>    at async fetch (ext:deno_fetch/26_fetch.js:504:7)
>    at async file:///C:/Apps/Deno/HelloDeno/helloFetch.ts:2:14

Installing the [vscode deno extension](https://marketplace.visualstudio.com/items?itemName=denoland.vscode-deno) had no effect. Both issues still remain:

 - `error trying to connect: received corrupt message of type InvalidContentType` 
 - Without `// @ts-ignore` vs-code still reports an error. 

![image](https://github.com/denoland/deno/assets/1271555/1047428f-a4ac-4275-95ab-c9be24214b45)

Changing the code to this

```ts
export {}
const site = await fetch("https://www.deno.com");
console.log(await site.text());
```
resolved the ide warning / ide error message. But `fetch` still fails with the same error (see #20709)

**Comment by lucacasonato** [comment]
@surfmuggle Are you running within a corporate VPN protected network?

**Comment by surfmuggle** [comment]
Yes i am behind a corporate VPN with a dedicated proxy that reuqires user authentication.  Uservariables for the proxy are set 

```shell
C:\Users\myuser>SET HTT
HTTPS_PROXY=https://myuser:mypass@myproxy.some.company:8080
HTTP_PROXY=http://myuser:mypass@myproxy.some.company:8080
```

**Comment by sigmaSd** [comment]
Those workarounds are not needed it's an issue with your setup.

I suspect that those warnings are coming from tsserver lsp, but the deno extension should have disable it if you did the initialize workspace command from the commands menu.

I don't know if the VPN usage can cause such behavior though.

**Comment by lucacasonato** [comment]
The VPN problem is for the second issue that was also included here. I agree that this error comes from not setting up your editor (correctly). Please make sure you actually enable the extension for your editor: https://docs.deno.com/runtime/manual/getting_started/setup_your_environment#visual-studio-code

**Comment by surfmuggle** [comment]
@sigmaSd you wrote that there is an issues with my setup. This is indeed the case. The point i am trying to make was that it would helpfull if [the first chapter of basics](https://docs.deno.com/runtime/tutorials/hello_world) would have a remark that tells a user to set up his environment before trying out the code.

**Comment by surfmuggle** [comment]
@lucacasonato as advised i did the following

1. deno.exe was added to path
2. extension for vs code was installed

The next step to open the [command pallete](https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette) (<kbd>CTRL+SHIFT+P</kbd>) and typing `Deno: Initialize Workspace Configuration` resulted in this error


![image](https://github.com/denoland/deno/assets/1271555/480f864e-cab7-4b5c-8e8e-52fc0c1f7960)

And this error messages

> Starting Deno language server...
>   version: 1.37.1 (release, x86_64-pc-windows-msvc)
>   executable: C:\Apps\Deno\deno.EXE
> Connected to "Visual Studio Code" 1.78.1
>   Auto-resolved package.json: "file:///C:/package.json"
> 
> ============================================================
> Deno has panicked. This is a bug in Deno. Please report this
> at https://github.com/denoland/deno/issues/new.
> If you can reliably reproduce this panic, include the
> reproduction steps and re-run with the RUST_BACKTRACE=1 env
> var set and include the backtrace in your report.
> 
> Platform: windows x86_64
> Version: 1.37.1
> Args: ["C:\\Apps\\Deno\\deno.EXE", "lsp"]
> 
> thread 'main' panicked at 'Failed to add platform cert to root cert store: InvalidCertificate(BadEncoding)', cli\args\mod.rs:504:14
> stack backtrace:
> note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
> [Info  - 9:23:48 PM] Connection to server got closed. Server will restart.
> [Error - 9:23:48 PM] Server initialization failed.
>   Message: Pending response rejected since connection got disposed
>   Code: -32097 
> [Error - 9:23:48 PM] Deno Language Server client: couldn't create connection to server.
>   Message: Pending response rejected since connection got disposed
>   Code: -32097 
> Starting Deno language server...
>   version: 1.37.1 (release, x86_64-pc-windows-msvc)
>   executable: C:\Apps\Deno\deno.EXE
> Connected to "Visual Studio Code" 1.78.1
>   Auto-resolved package.json: "file:///C:/package.json"
> 
> ============================================================
> Deno has panicked. This is a bug in Deno. Please report this ....
