### ISSUE TITLE
Documentation: writeSync suggests deprecated function

### ISSUE THREAD

**Issue by Reububble** [denoland/deno#20701]
`Deno.writeSync` suggests users
> use [writeAllSync()](https://deno.land/std/streams/write_all.ts?s=writeAllSync) from [std/streams/write_all.ts](https://deno.land/std/streams/write_all.ts) instead

but that is deprecated.

**Comment by Reububble** [comment]
Similar is true for `Deno.write`.
> use [writeAll()](https://deno.land/std/streams/write_all.ts?s=writeAll) from [std/streams/write_all.ts](https://deno.land/std/streams/write_all.ts) instead

**Comment by lucacasonato** [comment]
The deprecation comment from https://deno.land/std@0.202.0/streams/write_all.ts?s=writeAll should be adapted to these.

**Comment by iuioiua** [comment]
I'll do this.
