### ISSUE TITLE
Environment Variables in Test

### ISSUE THREAD

**Issue by mcgear** [denoland/deno#20717]
Hey, I am curious as to if deno test supports the environment variables?  It seems that maybe it doesn't as my tests do not work when they rely on environment variables.  Variables are just set in a .env file, should this work with tests?

**Comment by bartlomieju** [comment]
Yes, you can access env vars in test using `Deno.env` APIs. How are you setting up these env vars from `.env` when running the tests?

**Comment by mcgear** [comment]
I just have the .env file in a format like

ENV_VARIABLE=the-value
...

What i did to get it working was create a .env.ts file and use the `Deno.env.set("ENV_VARIABLE", "the-value")`.  And then in the test that needs the env variables, i just do an `import '../../.env.ts'`.

I was unable to get it working by simply having the .env file at the root (as does work in a `deno run`) context.

**Comment by mcgear** [comment]
I should also note this is the command i had tried at one point to try and register the .env file:

```
    "test": "deno test -A --unstable --allow-env .env tests/tests.ts --coverage=cov"
```

**Comment by dsherret** [comment]
I think you're wanting the `--env` feature. That will be coming hopefully in the next release: https://github.com/denoland/deno/pull/20300

For now, there's the deno_std module: https://deno.land/std@0.203.0/dotenv/mod.ts

```ts
// add this to your code
import "https://deno.land/std@0.203.0/dotenv/load.ts";
```

**Comment by mcgear** [comment]
Perfect, thank you, this was exactly what i needed. Thanks again for the help.
