### ISSUE TITLE
Worker messages are not received under some circumstances

### ISSUE THREAD

**Issue by jespertheend** [denoland/deno#20727]
```js
const workerUrl = URL.createObjectURL(new Blob([`
	globalThis.addEventListener("message", (e) => {
		const data = {
			array1: new Uint32Array([]),
			array2: new Float32Array([]),
		};

		const transfer = [
			data.array1.buffer,
			data.array2.buffer,
		];

		globalThis.postMessage({ id: 1, data });
		globalThis.postMessage({ id: 2, data }, transfer);
	});
`]));
const worker = new Worker(workerUrl, { type: "module" });

worker.addEventListener("message", (e) => {
	console.log("received response", e.data.id);
});

const buffer = new ArrayBuffer(10);
worker.postMessage({ buffer }, [buffer]);
```

- Save the above file
- run with `deno run foo.js`.
- Observe how "received response 1" is printed, but "received response 2" is missing.

Some things to note:
- Removing either `array1` or `array2` from the `data` object and the `transfer` array fixes the issue
- Removing the `[buffer]` transfer array that is send to the worker in the very last line also fixes the issue

I ran into this when trying to parse a glb file with draco compression using threejs, which [apparently uses this pattern](https://github.com/mrdoob/three.js/blob/f8863302d7200f02b50dbd3d0014ede46f134e37/examples/jsm/loaders/DRACOLoader.js#L451).

**Comment by dsherret** [comment]
The second parameter is `targetOrigin` and not `transfer`: https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage

**Comment by jespertheend** [comment]
Oh wow, I can't believe I've been debugging this for an hour 😅
I wonder why this is not an issue in browsers though.
And I suppose removing the `[buffer]` argument on the last line shouldn't affect the behaviour like that either?

**Comment by jespertheend** [comment]
@dsherret It seems like [the correct signature](https://html.spec.whatwg.org/multipage/workers.html#dedicated-workers-and-the-dedicatedworkerglobalscope-interface) for `DedicatedWorkerGlobalScope` is:

- `postMessage(any message, sequence<object> transfer);`
- `postMessage(any message, optional StructuredSerializeOptions options = {});`

Mdn also has a [page for `DedicatedWorkerGlobalScope`](https://developer.mozilla.org/en-US/docs/Web/API/DedicatedWorkerGlobalScope/postMessage), but the signatures on that page seem to be incorrect.

**Comment by dsherret** [comment]
Oh yeah, you're right: https://github.com/denoland/deno/blob/d43e48c4e96b02289d505cd2558ba85d7d6cb57b/cli/tsc/dts/lib.deno.worker.d.ts#L146-L151

**Comment by dsherret** [comment]
I don't know enough about workers. It seems an error occurs sending back the message:

```ts
worker.addEventListener("messageerror", e => {
  console.log(e);
})
```

```
TypeError: transferred array buffer not present in shared_array_buffer_store
```
