### ISSUE TITLE
`deno upgrade` fails if lockfile cannot be parsed

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#20729]
We shouldn't surface lockfile errors for `deno upgrade`. I'm not sure how difficult this is to fix though (probably we should resolve the lockfile lazily).

```
$ deno upgrade
 error: Unable to parse contents of lockfile: "/.../deno.lock"
```

**Comment by ihasq** [comment]
Have you ever tried ```--no-lock``` option?

**Comment by KnorpelSenf** [comment]
Are there any plans to fix this?
