### ISSUE TITLE
(Explained) Unexpected behavior in `deno info --json`

### ISSUE THREAD

**Issue by StarLederer** [denoland/deno#20726]
Two weeks ago I posted #20493 asking about, in all intents and purposes, `deno info`, that I wanted to use to configure Rollup to bundle Deno code. I have made significant process but I encountered a problem caused by unexpected behavior in `deno info --json`.

The info command unexpectedly resolves importMap aliases to `file://` paths making them useless when trying to resolve aliases in the source code.

Given the code,

```js
export foo from "@foo";
```

the info command produces the following json (unrelated stuff removed):

```json
{
  "modules": [
    {
      "local": "/absolute/path/to/foo.js",
      "specifier": "file:///absolute/path/to/foo.js"
    }
  ]
}
```

but I expected

```json
{
  "modules": [
    {
      "local": "/absolute/path/to/foo.js",
      "specifier": "@foo"
    }
  ]
}
```

This behavior prevents me from being able to resolve `@foo` to `/absolute/path/to/foo.js` during bundling. I have to read the import map myself if I want this to work.

This behavior is also inconsistent with how modules dependencies are treated because they do get to keep the original alias as the specifier.

I think it would be more useful if `specifier` remained how it is in the code so that it is possible to resolve any module by just reading the code and the result of `deno input`

**Comment by dsherret** [comment]
That's expected because the specifier on the module is the resolved specifier and not what it was referenced as and then mapped to in another module.

> This behavior prevents me from being able to resolve @foo to /absolute/path/to/foo.js during bundling. I have to read the import map myself if I want this to work.

Where `@foo` is found, you should see a `dependencies` array, which will have the specifier and what the "code" path resolves to:

```jsonc
    {
      "kind": "esm",
      "dependencies": [
        {
          "specifier": "@foo",
          "code": {
            "specifier": "file:///V:/scratch/foo.ts",
            "span": {
              "start": {
                "line": 0,
                "character": 16
              },
              "end": {
                "line": 0,
                "character": 22
              }
            }
          }
        }
      ],
      // ...etc...
      "specifier": "file:///V:/scratch/main.ts"
    }
```

**Comment by StarLederer** [comment]
That you so much! This json output is a bit difficult to comprehend (skill issue), I was actually working on it now and decided to write an update saying that I suspect I might be wrong. I let this sit for about a week and couldn't figure it out so I decided to post this issue... sometimes things click too late.

What threw me off here was that I was not using `deno info` for everything that I should have. I was not treating my entry point as a Deno file which, confusingly, almost worked, because http imports do not change and local imports are successfully resolved by Rollup, leaving us only the importMap aliases, I now figured out that I should resolve the entry point to the first entry of `roots` from `deno info --json`, which lets my resolver know  that the entry point is also a Deno file and allows all dependencies (including importMap aliases) to be handled properly as a result. Rollup is not even resolving local paths now.

But since I am on the topic now, I would like to ask why `roots` is an array. I am unable to find any documentation of the output of `deno info --json` so could you please explain why `roots` needs to be an array and in what situations there might be multiple roots.

**Comment by dsherret** [comment]
> I would like to ask why roots is an array

The graph can have multiple roots for things like `deno check` (ex. `deno check file1.ts file2.ts`). Right now, `deno info` only supports one argument though so you can assume the `roots` array will always have one value (in the future if it ever supported multiple arguments then there could be multiple roots).
