### ISSUE TITLE
Command 'deno' not found in ubuntu 18.04 ( a guide to solve this )

### ISSUE THREAD

**Issue by nimahkh** [denoland/deno#2072]
Thanks for your great job @ry  . 
i do installation like this :<br/>

```
curl -fsSL https://deno.land/x/install/install.sh | sh
```
when i run <br/>

```
deno hello.ts
```
i get command 'deno' not found error <br/>
im using ubuntu 18.04 .

<br/>

as you say in shell script , we have to add 

```
export PATH="/home/username/.deno/bin:$PATH"
```

after this , in new instance of terminal , again we have to add it again . 

<br/>

to solve this , please add this guide in installation , 

<br/>

```
vim ~/.zshrc 
or
vim ~/.bashrc
```
after that command , please add this line end of file and save and exit 

```
export PATH="/home/username/.deno/bin:$PATH"
```
thanks for your jobs :heart:

**Comment by zekth** [comment]
From manual:
```
Once it's installed and in your $PATH, try it:

$ deno https://deno.land/welcome.ts
```

**Comment by nimahkh** [comment]
> From manual:
> 
> ```
> Once it's installed and in your $PATH, try it:
> 
> $ deno https://deno.land/welcome.ts
> ```

it will not do anything , cause i have zsh , so i need to set it inside of bashrc or zshrc , if you read my issue , you will see i give an opinion to others , and solved it . <br/>
thanks bro  :heart:

**Comment by zekth** [comment]
The mandatory thing is to have it in your `$PATH` the way you do it is related to your usage, so describing all usages is not really revelant to add it in the documentation.

**Comment by nimahkh** [comment]
> The mandatory thing is to have it in your `$PATH` the way you do it is related to your usage, so describing all usages is not really revelant to add it in the documentation.

your right , i think somebody maybe need this to

**Comment by ry** [comment]
Once we're integrated with package managers this will be less confusing for people.

**Comment by AndresManuelArias** [comment]
Thanks nimahkh for your contribution

**Comment by tinyweasel** [comment]
I had this issue too in Ubuntu 18.04 but adding it to .bashrc fixed it although I still cannot use the command in the VS Code terminal, is there a fix for that?

**Comment by lucacasonato** [comment]
> I had this issue too in Ubuntu 18.04 but adding it to .bashrc fixed it although I still cannot use the command in the VS Code terminal, is there a fix for that?

Restart VS Code

**Comment by sengarsameer** [comment]
> I had this issue too in Ubuntu 18.04 but adding it to .bashrc fixed it although I still cannot use the command in the VS Code terminal, is there a fix for that?

After adding, execute this command.
. ~/.bashrc

**Comment by tinyweasel** [comment]
I restarted VS Code and sourced bashrc, and deno is on the PATH, still doesn't work.

**Comment by offline-pixel** [comment]
Also, can be installed via 

> curl -fsSL https://deno.land/x/install/install.sh | sudo DENO_INSTALL=/usr/local sh

**Comment by tinyweasel** [comment]
It's installed and it works in my main terminal, it only doesn't work in the VS Code terminal.

**Comment by zhitomir-oreshenski-mm** [comment]
Hi,
As per nimahkh's recommendation above, everything is working propertly on Ubuntu 18.04. In the documentation is missing the bashrc part where you need to open "/home/username/.bashrc" (nano ~/.bashrc) file and export the path to deno executable:

export PATH="/home/username/.deno/bin:$PATH"

Once it is done, you can easily check if "deno" command has been recognized by typing:
deno -h

Br,
Zhi

**Comment by radheysm** [comment]
> Again, I have done that, it works in my main terminal, it only does not work in VS Code.

Restart VS Code after updating ./bashrc

**Comment by tinyweasel** [comment]
I did.

**Comment by zhitomir-oreshenski-mm** [comment]
I can confirm that with bash terminal is working properly. I've not tested it with others.

**Comment by tinyweasel** [comment]
Working in bash terminal for me too, just not the one in VS Code.

**Comment by ahrasel** [comment]
> export PATH="/home/username/.deno/bin:$PATH"

but it's required always. when I open the terminal need to run this again. is there any permanent solution?

**Comment by ahrasel** [comment]
> > Again, I have done that, it works in my main terminal, it only does not work in VS Code.
> 
> Restart VS Code after updating ./bashrc

it's working after adding **export PATH="/home/username/.deno/bin:$PATH"** this on .bashrc

**Comment by zhitomir-oreshenski-mm** [comment]
@ahrasel you have to only set the path in 'bashrc' file in order the terminal to recognize deno command. From there on deno executable can be run.

**Comment by randal923** [comment]
> Also, can be installed via
> 
> > curl -fsSL https://deno.land/x/install/install.sh | sudo DENO_INSTALL=/usr/local sh

This should be in the documentation!

**Comment by khaki32** [comment]
It was working for me and just stopped working for some reason.

Installed it again using:

```bash
curl -fsSL https://deno.land/x/install/install.sh | sudo DENO_INSTALL=/usr/local sh
```

Which is working for me now.
