### ISSUE TITLE
Deno Jupyter REPL does not pretty print DataFrame

### ISSUE THREAD

**Issue by acrodrig** [denoland/deno#20739]
First all, thanks so much for Jupyter support. I hope I have to jump less between Python and TS for data science.

Second, I am trying the following example from the [Modern JavaScript in Jupyter Notebooks](https://deno.com/blog/v1.37).

```ts
let df = pl.DataFrame({
  A: [1, 2, 3, 4, 5],
  fruits: ["banana", "banana", "apple", "apple", "banana"],
  B: [5, 4, 3, 2, 1],
  cars: ["beetle", "audi", "beetle", "beetle", "beetle"],
})
df = df.sort("fruits");
```

The data frames do not pretty print as a table (see screenshot below). Any special magic I need to be aware of? Can I redefine the printing of the REPL loop?

Thanks.

![image](https://github.com/denoland/deno/assets/959336/a1da5915-ef64-4419-8f1e-5a397afba0c7)

**Comment by bartlomieju** [comment]
@acrodrig you might want to check out https://github.com/rgbkrk/display.js by @rgbkrk who's been pushing rich displays in Deno's Jupyter kernel :)

**Comment by rgbkrk** [comment]
For now you'll need to run:

```
import { display } from "https://deno.land/x/display/mod.ts";

display(df)
```

Follow up work for me is to make a PR to the Polars folks including the `Symbol.for("Jupyter.display")` on their DataFrame class. Otherwise we have to do a bit of 🦆  typing like is done in `display` to detect and display Polars DataFrames as part of Deno.

**Comment by acrodrig** [comment]
Display looks great @rgbkrk. Looking forward to trying it out. Maybe we can even do Spark in Deno and then I can start unlearning Python and Scala :) Thanks for great work.
