### ISSUE TITLE
Should host and port get parsed for strange URL schemes?

### ISSUE THREAD

**Issue by rotu** [denoland/deno#20733]
Trying to parse a nonstandard URL protocol is very different between Deno and browsers. In particular whether the `host` and `port` get parsed out or whether everything is treated as part of the `pathname`.

```javascript
console.log(new URL("wtf://127.0.0.1:8000/baz"))
```

Deno, Node, Safari, Bun give something like:
```
URL {
  href: "wtf://127.0.0.1:8000/baz",
  protocol: "wtf:",
  host: "127.0.0.1:8000",
  hostname: "127.0.0.1",
  port: "8000",
  pathname: "/baz"
}
```

Chrome, Firefox give something like:
```
URL {
  href: "wtf://127.0.0.1:8000/baz",
  protocol: "wtf:",
  hostname: "",
  port: "",
  pathname: "//127.0.0.1:8000/baz"
}
```

**Comment by rotu** [comment]
Hmm... I *think* Deno implements the standard correctly here and that both Chrome and Firefox are in error. see e.g. the "Parsing: <gopher://foo:443/> without base" case in [web platform tests](https://wpt.fyi/results/url/url-constructor.any.html%3Fexclude%3D(file%7Cjavascript%7Cmailto)?label=master&label=experimental&aligned)

**Comment by lucacasonato** [comment]
Chrome and Firefox are wrong.
