### ISSUE TITLE
Support Tauri

### ISSUE THREAD

**Issue by birkskyum** [denoland/deno#20738]
Tauri - [Website](https://tauri.app) - [GitHub](https://github.com/tauri-apps/tauri)

**Platform**

Darwin 23.0.0 arm64 arm

**Version**

deno 1.37.1

**Repro**

* `deno run -A npm:create-tauri-app`
  - Select i.e. Typescript, Solid
* `deno run -A npm:tauri dev`

**Expected**

I.e. `npx tauri dev` gives:

```sh
➜ npx tauri dev     
     Running BeforeDevCommand (`npm run dev`)

> create-tauri-app@0.0.0 dev
> vite
  VITE v4.4.9  ready in 227 ms

  ➜  Local:   http://localhost:1420/
  ➜  Network: use --host to expose
        Info Watching /Users/admin/repos/tauri-test/create-tauri-app/src-tauri for changes...
   Compiling create-tauri-app v0.0.0 (/Users/admin/repos/tauri-test/create-tauri-app/src-tauri)

    Finished dev [unoptimized + debuginfo] target(s) in 0.68s
```

**Actual**

```sh
➜ deno run -A npm:tauri dev
error: package 'tauri' did not have a bin property in its package.json
```

**Comment by denyncrawford** [comment]
Any update?

**Comment by ninjadev64** [comment]
I'm in a Tauri setup with a SvelteKit frontend. Deno is panicking with this backtrace.
```
============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 1.43.6
Args: ["/home/aman/.deno/bin/deno", "run", "-A", "npm:vite@5.2.11", "dev"]

thread 'main' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/notify-5.0.0/src/inotify.rs:596:32:
called `Result::unwrap()` on an `Err` value: "SendError(..)"
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: <notify::inotify::INotifyWatcher as notify::Watcher>::watch
   4: deno_runtime::ops::fs_events::op_fs_events_open::op_fs_events_open::v8_fn_ptr
   5: Builtins_CallApiCallbackOptimizedNoProfiling
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Deno v1.43.6
Rustc v1.78.0
Tauri v1.6.6
Vite v5.2.11

**Comment by birkskyum** [comment]
I upgraded to Deno 1.44, because this is one of the tickets relying on binaries and hoped this would help:

- https://github.com/denoland/deno/pull/23496

I might be doing something wrong, but this is what I get

```sh
➜ DENO_FUTURE=1 deno install npm:tauri
⚠️ `deno install` behavior will change in Deno 2. To preserve the current behavior use the `-g` or `--global` flag.
Add tauri - npm:tauri@^0.15.0
error: Can't set up 'vite' bin at ../.deno/vite@5.2.11/node_modules/vite/bin/vite.js

Caused by:
    File exists (os error 17)
```

and

```sh
➜ DENO_FUTURE=1 deno run npm:tauri dev
error: '/Users/admin/repos/deno-kitchensink/create-tauri-app/node_modules/.deno/tauri@0.15.0/node_modules/tauri/package.json' did not have a bin property
```

@bartlomieju , I to use this new support for node_modules/.bin

**Comment by birkskyum** [comment]
With the binary install resolved, this seems to mainly be a matter of confusion/mess with the DENO_FUTURE=1 and the npm:tauri. For instance, the package scripts has an entry called `"tauri": "tauri"`, and it doesn't work well with `DENO_FUTURE=1 deno task tauri dev`, and `DENO_FUTURE=1 deno run npm:tauri`.

**Comment by birkskyum** [comment]
For Deno 2, rc.2, things run as expected, except the "Greet" button in the demo, it'll give this console error:

```sh
@tauri-apps_api_tauri.js?v=152d049d:30 Uncaught (in promise) TypeError: window.__TAURI_IPC__ is not a function
    at @tauri-apps_api_tauri.js?v=152d049d:30:12
    at new Promise (<anonymous>)
    at invoke (@tauri-apps_api_tauri.js?v=152d049d:21:10)
    at greet (main.ts:9:36)
    at HTMLFormElement.<anonymous> (main.ts:20:5)
```

**Comment by birkskyum** [comment]
- #25649

**Comment by birkskyum** [comment]
See now, with the deno2/tauri2 repro here:

```sh
npm create tauri-app@latest -- --rc
cd tauri2-app
deno install
deno task dev
```

Error in console
```sh
@tauri-apps_api_core.js?v=1934d98c:89 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'invoke')
    at invoke (@tauri-apps_api_core.js?v=1934d98c:89:37)
    at greet (App.tsx:12:23)
    at HTMLFormElement.<anonymous> (App.tsx:37:11)
```

**Comment by adminy** [comment]
Does it work now? Sounds like tauri apps is not deno compatible from the error message. The rust bindings is probably specific to node.

What are the benefits of using deno for this? Can I still use pnpm as the package manager?

**Comment by ninjadev64** [comment]
> Does it work now? Sounds like tauri apps is not deno compatible from the error message. The rust bindings is probably specific to node.

I use it just fine. There are no Rust bindings in Tauri (apart from the CLI), it is all IPC.

> What are the benefits of using deno for this? Can I still use pnpm as the package manager?

You can see the benefits of Deno on its website. You shouldn't use pnpm with Deno.

**Comment by phoenisx** [comment]
@ninjadev64 how is it working for u?

> I use it just fine.
For me `deno task dev` still doesn't work, and failing because of the `tauri` cli/bin script

**Comment by phoenisx** [comment]
The only way I see to make `deno` work with tauri is to write custom `dev` script to run `tauri` cli or start the vite dev server using a custom deno script.

I've never tried building the app yet, so not sure if above custom script will be sufficient to make things work with Tauri builds.

**Comment by ninjadev64** [comment]
In my package.json I have the normal vite dev, build and preview scripts. In my tauri.conf.json I have the beforeDevCommand or whatever it is as `deno task dev`.

**Comment by phoenisx** [comment]
Thanks for sharing.
I think it should work with `cargo tauri dev` with the changes u described above, but I am not able to run `cargo tauri dev` on my linux machine. It keeps on throwing `no such command: tauri` error
I couldn't find any details in the documentation either

**Comment by ninjadev64** [comment]
I believe this issue can be closed.

**Comment by birkskyum** [comment]
@ninjadev64 , when I made this ticket, it was all Tauri 1 + Deno 1. Now both Tauri and Deno are stable in v2, I'll have a go at running that forward-looking combination, and close if it works as expected.

**Comment by xiaoas** [comment]
I gave Tauri 2 + Deno 2 a try:

There's a `deno` template when running `create-tauri-app`, which contains a valid `tauri.conf.json`. The artifacts are bundled with `vite`, which is invoked by deno task.

Linting does not seem to work out of the box despite there's `tsconfig.json` in the project root. You'll have to manually create a `deno.jsonc` which replicates the `compilerOptions.lib` specified:
```json
{
  "compilerOptions": {
    "lib": [
      "ES2021",
      "DOM",
      "DOM.Iterable"
    ]
  }
}
```
Deno specific features won't work. For example
```js
// https://docs.deno.com/runtime/fundamentals/node/#using-npm-packages
import * as emoji from "npm:node-emoji";
console.log(emoji.emojify(`:sauropod: :heart:  npm`));
```
will result in an error. From my understanding you are running the js part of tauri & vite cli in deno but that's all.

deno does not play that well with tauri currently. In all of the js examples vite is used, and vite uses it's own `esbuild`.

I can see some reasoning to choose deno in this setop:
- You prefer the deno cli to the node cli
- You prefer some of the tools built into deno. For example `deno fmt`

**Comment by birkskyum** [comment]
@xiaoas , awesome, sounds like the deno template just need a few tweaks!

**Comment by raine-works** [comment]
I was also able to get it working. Here is my example repository. 

https://github.com/raine-works/tauri-deno/tree/master

**Comment by PTPhongKMF** [comment]
Im new to all of this so i wanna ask, by implementing this you essentially are replacing rust with deno for backend?

**Comment by bignikescar** [comment]
> Im new to all of this so i wanna ask, by implementing this you essentially are replacing rust with deno for backend?

probably in tauri project, it could adds an option to replacing nodejs binary to deno binary when tauri project builds. before these efforts will only limits to deno typescript project run on tauri environment using nodejs binary.

**Comment by tredondo** [comment]
Mid-2026 update:
- there's a "Tauri plugin to run deno javascript code in the backend instead of rust" at https://github.com/marcomq/tauri-plugin-deno
- [deno desktop](https://docs.deno.com/runtime/desktop/) is available in Canary
