### ISSUE TITLE
[Bug]: Discrepancy in Intellij Type Evaluation with Enum Values between Deno and Node.js Environments

### ISSUE THREAD

**Issue by alita-moore** [denoland/deno#20731]
**Description:**

I've observed a discrepancy in how a type expression involving an enum and a type intersection is evaluated in Deno compared to a standard Node.js environment, using the same TypeScript version. Below is the simplified reproducible code snippet:

```typescript
enum Values {
    APPLE = "APPLE",
    ORANGE = "ORANGE",
}
type Differentiator =
    | { type: Values.APPLE; a: number }
    | { type: Values.ORANGE };

type A = Differentiator & { type: Values.APPLE }
const a: A = {} as any;
a.type // evaluates to (Values.ORANGE & Values.APPLE) | Values.APPLE in Deno but Values.APPLE in a Node.js project
```

**Steps to Reproduce:**

1. Create a TypeScript file with the provided code snippet.
2. Check the evaluated type of `a.type` in both a Node.js environment and a Deno environment using the same version of TypeScript.

**Expected Behavior:**

The type of `a.type` should evaluate to `Values.APPLE` in both environments.

**Actual Behavior:**

In the Deno environment, the type of `a.type` evaluates to `(Values.ORANGE & Values.APPLE) | Values.APPLE`.

**Environment:**

deno 1.35.3 (release, aarch64-apple-darwin)
v8 11.6.189.12
typescript 5.1.6

**Additional Context:**

This type evaluation discrepancy makes it difficult to utilize a strategy pattern with type and property differentiation occurring using a key property.

**Comment by alita-moore** [comment]
I checked my typescript version in the node instance, it seems it's using `5.3.0-dev.20230909` so this may be related to typscript

**Comment by dsherret** [comment]
For me that evaluates to `Values.APPLE` in both Deno 1.35.3 and 1.37.1.

```shellsession
> deno -V
deno 1.37.1
> cat main.ts
enum Values {
  APPLE = "APPLE",
  ORANGE = "ORANGE",
}
type Differentiator =
  | { type: Values.APPLE; a: number }
  | { type: Values.ORANGE };

type A = Differentiator & { type: Values.APPLE }
const a: A = {};
> deno check main.ts
Check file:///V:/scratch/main.ts
error: TS2322 [ERROR]: Type '{}' is not assignable to type '{ type: Values.APPLE; a: number; } & { type: Values.APPLE; }'.
  Type '{}' is missing the following properties from type '{ type: Values.APPLE; a: number; }': type, a
const a: A = {};
      ^
    at file:///V:/scratch/main.ts:10:7
```

Do you happen to have any typescript compiler options set?

**Comment by Seally** [comment]
I cannot reproduce this either (Deno 1.37.1, Windows 10).

Aside note, wouldn't `(Values.ORANGE & Values.APPLE) | Values.APPLE` effectively resolve to `never | Values.APPLE` then just `Values.APPLE`, so they're basically the same type except the last one is a lot more readable?

**Comment by alita-moore** [comment]
Yes, here's the tsconfig.json:
{
  "compilerOptions": {
    "outDir": "dist",
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "skipLibCheck": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": false,
    "forceConsistentCasingInFileNames": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "removeComments": true,
    "noFallthroughCasesInSwitch": true,
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "incremental": false,
    "strict": true
  }
}

**Comment by alita-moore** [comment]
@Seally it causes problems with the inferred types and will mess up intellisense

**Comment by dsherret** [comment]
Thanks, I'm still not able to reproduce this. If you do `const a: A = {};` and hover over where the error is showing, do you see `deno-ts` at the end of the error message?

If you get a chance, would you be able to run `deno upgrade` to get the latest Deno then try in a new empty project in vscode with a deno.json with this config to see if it still reproduces there?

**Comment by Seally** [comment]
Is this occurring in Webstorm? I grabbed the latest EAP (since I unfortunately no longer have access to any JetBrains license) and it's the only way I can get the "issue" to show up.

![image](https://github.com/denoland/deno/assets/507710/c30f66cb-5138-4f4b-a634-a5ac7569407f)

> @Seally it causes problems with the inferred types and will mess up IntelliSense

I'm afraid I don't completely understand what "problems with inferred types" means here. I did try this though:

```typescript
import {
  type IsExact,
  assertType
} from "https://deno.land/std@0.203.0/testing/types.ts";

enum Values {
  APPLE = "APPLE",
  ORANGE = "ORANGE",
}
type Differentiator =
  | { type: Values.APPLE; a: number }
  | { type: Values.ORANGE };

type A = Differentiator & { type: Values.APPLE };
const a: A = {} as any;

function foo(_input: { type: Values.APPLE, a: number }) {}

function bar(_input: Differentiator) {}

function baz(_input: { type: Values.ORANGE }) {}

foo(a);
bar(a);
baz(a); // Errors as expected

if (a.type === Values.APPLE) {
  console.log(a.a);
}

if (a.type === Values.ORANGE) {
  // In VS Code, a.type in tooltip is never
  // In Webstorm 2023.3 EAP, a.type in tooltip is (Values.ORANGE & Values.APPLE) | Values.APPLE
  console.log(a.type);
  // Typechecks correctly everywhere, suggesting the actual resolved type is correct.
  assertType<IsExact<typeof a.type, never>>(true);
}
```

Is the last bit the problem you've mentioned? I've noticed Intellisense still allows you to `a.a` inside the conditional. However, this is also the case in the TypeScript playground and Deno VS Code, so it doesn't seem to be the issue. Only the tooltip display is, which I'll interpret as "no practical difference to type inference".

**Comment by alita-moore** [comment]
@Seally yes that's exactly it. It's happening in Intellij. I suppose I should have mentioned that, my bad.

Regarding your example, the issue I'm referring to would be shown in the following code extract
```ts
if (a.type === Values.APPLE) {
  console.log(a.a);
}
```

In my IDE this works as expected, but that's because the `if (a.type === Values.APPLE)` isolates the type. However, the definition of a.type at this point is ` Values.APPLE | (Values.ORANGE & Values.APPLE)`. Which is equivalent. However, intellisense does not work the same when you index `a` from outside and within the `if` statement.

i.e.
```ts
a.a
if (a.type === Values.APPLE) {
  console.log(a.a);
}
```
![Screenshot 2023-09-29 at 3 12 05 PM](https://github.com/denoland/deno/assets/26529820/e460e863-8aee-4aab-9f89-dcaaaba4ec5c)

As you can see, the indexed `a` attribute outside of the if statement is white while the one inside is red. This indicates that the sensed value of a outside of the if statement is ambiguous. And indeed when you index it you see the following:
![Screenshot 2023-09-29 at 3 13 59 PM](https://github.com/denoland/deno/assets/26529820/e8332f22-dbaa-424c-91a3-9bd505e0949d)

In other use cases that I have it will also show the available properties for all the possible variation so the object with any type.

Thanks for looking into this!

**Comment by alita-moore** [comment]
@dsherret I upgraded to
```
deno 1.37.1 (release, aarch64-apple-darwin)
v8 11.8.172.6
typescript 5.2.2
```
with no changes in behavior

**Comment by lucacasonato** [comment]
Can you report this to IntelliJ? We are unable to reproduce this - so I assume this is an issue with IntelliJ itself.

**Comment by alita-moore** [comment]
for reference: https://youtrack.jetbrains.com/issue/PY-73239/Discrepancy-in-Intellij-Type-Evaluation-with-Enum-Values-between-Deno-and-Node.js-Environments
