### ISSUE TITLE
Add option to print stack trace of where permission is being requested

### ISSUE THREAD

**Issue by leighmcculloch** [denoland/deno#20756]
It would be helpful if the deno CLI provided the option to display where a permission request is coming from. In situations where a permission request is unexpected it'd help the developer understand whether the permission request is legit or not. Or in the case that a developer needs to debug where the permission request is coming from, it would assist with that.

Today when a permission request is encountered the following is output:
```
┌ ⚠️  Deno requests env access.
├ Run again with --allow-env to bypass this prompt.
└ Allow? [y/n/A] (y = yes, allow; n = no, deny; A = allow all env permissions) > 
```

This prompt could be modified to include an option to output the current stack trace:
```
┌ ⚠️  Deno requests env access.
├ Run again with --allow-env to bypass this prompt.
└ Allow? [y/n/t/A] (y = yes, allow; n = no, deny; t = trace, A = allow all env permissions) > 
```

Choosing `t` would output a stack trace of where the permission is being requested, including the filename, line numbers, etc. After outputting the trace, the same prompt would display so the developer could then choose one of the other option.

**Comment by KaKi87** [comment]
@bartlomieju Could we please have some feedback on this request ? :pray:

**Comment by crummy** [comment]
Looks like this was initially planned in https://github.com/denoland/deno/issues/1008 but didn't make it in. 

I think this would be very useful. (One of my dependencies is trying to `fetch` from github?? Which one???)

**Comment by bartlomieju** [comment]
This is being worked on in https://github.com/denoland/deno/pull/25502 and we want to land it in Deno v2.1 next month.
