### ISSUE TITLE
Add global `name`

### ISSUE THREAD

**Issue by jimmywarting** [denoland/deno#20750]
When i created a Worker using:
```js
new Worker(url, {
  type: 'module',
  name: 'name'
})
```

Then i did kind of expect `globalThis.name` to be available in the worker thread.

( heck could we even add it to all context? even on the main thread... )

**Comment by bartlomieju** [comment]
This is already supported in worker context as per https://developer.mozilla.org/en-US/docs/Web/API/DedicatedWorkerGlobalScope/name:

```
// main.js
new Worker(import.meta.resolve("./worker.js", {
  type: "module",
  name: "myWorker",
});
```

```
// worker.js
console.log(globalThis.name);
```

```
$ deno run --allow-read main.js
In worker myWorker
```

**Comment by jimmywarting** [comment]
Oh, crap... you are right! it dose work.

i was a bit stupid... i was executing the worker directly.
```
error: Uncaught ReferenceError: name is not defined
console.log(name);
            ^
    at file:///<path>/worker.js:1:13
```

i just didn't use the `globalThis.` prefix. 
hence why i reported this b/c i was seeing this error.



> > ( heck could we even add it to all context? even on the main thread... )
> 
> What would you suggest for the main thread name?

just set it to empty string like browser do... 
```js
console.log(window.name) // ""
```
