### ISSUE TITLE
Any speedup possible in `deno_web/02_timers.js` `runAfterTimeout`?

### ISSUE THREAD

**Issue by josephrocca** [denoland/deno#20775]
After `op_http_set_response_body_text`, which I've already made an issue about, [here](https://github.com/denoland/deno/issues/20409), `runAfterTimeout` seems to be the next most important performance hog on my production server:

![image](https://github.com/denoland/deno/assets/1167575/c5c0009a-a125-486d-8e66-8caa2055b6d0)

This seems to be almost entirely due to the `while` loop here:

![image](https://github.com/denoland/deno/assets/1167575/39ecccb0-b0e3-4f14-bd31-daa48b70d61f)

I'm guessing this is due to code like `await new Promise(r => setTimeout(r, ms))` which I use a lot.

No minimal reproduction at the moment, so please feel free to close, but I figured I'd post this early in case anyone can see some obvious/easy optimization wins in the above code. I figure it might have been written with the perspective that this wouldn't be a bottleneck - but just guessing/hoping.

**Comment by bartlomieju** [comment]
Yes, we're already working on timer reimplementation based on https://github.com/denoland/deno/issues/20356

**Comment by josephrocca** [comment]
Ah, that's great! I'll close this then, and subscribe to that one.
