### ISSUE TITLE
How to access `__dirname` or `__filename` with Deno?

### ISSUE THREAD

**Issue by felipecrs** [denoland/deno#20784]
According to https://docs.deno.com/runtime/manual/node/compatibility#globals, `__dirname` and `__filename` are supported. But there is no mention on how it can be done.

According to the docs on that very same page:

> This is the list of Node globals that Deno supports. These globals are only available in the npm package scope. In your own code you can use them by importing them from the relevant node: module.

For example, I can access `process.env` by doing:

```ts
import process from 'node:process'

console.log(process.env.TEST_VAR)
```

But what is the "relevant node: module" to access `__filename` or `__dirname`? If there is none, shouldn't one be created?

```ts
import __filename from 'node:__filename'
```

I known there are plenty of libraries, and I know there is the `import.meta.url` trick which I can use, but I believe there must be a better way.

As for the example:

```ts
// test.ts

console.log(__dirname)
```

```console
❯ deno run -A test.ts
error: Uncaught ReferenceError: __dirname is not defined
console.log(__dirname)
            ^
    at file:///tmp/tmp.Qq2z9kWPKd/test.ts:1:13
```

**Comment by dsherret** [comment]
Those aren't supported in ES Modules in Node (https://nodejs.org/api/esm.html#no-__filename-or-__dirname):

```shellsession
> cat example.mjs
console.log(__dirname);
> node example.mjs
file:///.../example.mjs:1
console.log(__dirname);
            ^

ReferenceError: __dirname is not defined in ES module scope
    at file:///.../example.mjs:1:13
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)     
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)  
```

...and Deno is ESM except within npm packages (where cjs is supported and `__dirname` and `__filename` works), so `import.meta.url` needs to be used, which is the standard way of figuring this out.

For example, the following code works in both Node and Deno when the current executing module is on the file system:

```ts
// https://github.com/nodejs/help/issues/2907#issuecomment-757446568
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
```

Again, this only works if the current module is on the file system. For example, that same code doesn't work once the module is remote:

```ts
> deno run https://gist.githubusercontent.com/dsherret/88876b1f94847e6eef054d21d9d8b070/raw/18a9c7297518b95e8e7bbbd8ea9563c40eb4eb7c/example.js
error: Uncaught TypeError: The URL must be of scheme file
    at fileURLToPath (node:url:1160:11)
    at https://gist.githubusercontent.com/dsherret/88876b1f94847e6eef054d21d9d8b070/raw/18a9c7297518b95e8e7bbbd8ea9563c40eb4eb7c/example.js:4:20
```

**Comment by felipecrs** [comment]
I pushed a PR for the docs btw: https://river.internal.ericsson.com/jenkins/blue/organizations/jenkins/coc-umi%2Fdevelop%2Fqualify%2Fecm-ft/detail/ecm-ft/4924/pipeline

**Comment by dsherret** [comment]
`import.meta.filename` and `import.meta.dirname` are now supported in Deno 1.40. It's important to note that these return undefined when used in https modules

https://deno.com/blog/v1.40#importmetafilename-and-importmetadirname

**Comment by felipecrs** [comment]
That's awesome. Now I just wonder if there should not be a flag like `--unstable-underscore-dirname` for wider compatibility.
