### ISSUE TITLE
Turso LibsqlError: URL_SCHEME_NOT_SUPPORTED when trying "file:local.db"

### ISSUE THREAD

**Issue by fightbulc** [denoland/deno#20786]
Hey, I wanted to try out Turso's syncURL feature and for that it creates a local db file to read from and syncs any written data remote first before it writes it locally.

**Error**

However, I am not getting that far due to the following issue:
`LibsqlError: URL_SCHEME_NOT_SUPPORTED: The client that uses Web standard APIs supports only "libsql:", "wss:", "ws:", "https:" and "http:" URLs, got "file:". For more information, please read https://github.com/libsql/libsql-client-ts#supported-urls`

**Deno code:**

```ts
// main.ts
createClient({
  url: "file:local.db",
  syncUrl: Deno.env.get("URL"),
  authToken: Deno.env.get("TOKEN")
});
```
The script has all permissions by `deno run -A main.ts`.

Based on the error `file:` is simply not supported since Deno is allowing only web standard APIs?
Any other way to allow this? I am just suprised this isn't working since the use case seems acceptable.

**Comment by tstachl** [comment]
This is an error coming from `libsql`: https://docs.turso.tech/libsql/client-access/javascript-typescript-sdk#choose-the-correct-import-for-your-environment

**Comment by penberg** [comment]
Yes, this is not a Deno bug, please close this.
