### ISSUE TITLE
Bug: Importing non text files breaks LSP

### ISSUE THREAD

**Issue by lucsoft** [denoland/deno#20798]
This is more of a Feature request than a bug report, but for Frontend-Dev you currently are required to abuse the import for asset references (used via esbuild or other bundlers). It would be great if the LSP can accept binaries files even tho they are not valid for Deno. 

Common use-case:
```ts
import './styles.css';
import imageURL from "./image.png";

$image.src = imageURL;
```

- Deno compile? Embeds? Would be awesome
- Deno check? Should ignore it
- Deno lint? Should ignore it

Ideal solution would be [asset references](https://github.com/tc39/proposal-asset-references) but that's sadly not advancing

**Comment by maekoos** [comment]
Related to #17994

**Comment by nayeemrmn** [comment]
Let's continue in #5987 and #17994. It's unlikely we would add a way to suppress these diagnostics for esbuil-ers without supporting it
