### ISSUE TITLE
use lock file version 2 rather than 3 in latest deno version?

### ISSUE THREAD

**Issue by alita-moore** [denoland/deno#20795]
As is described here: https://github.com/supabase/supabase/issues/17901 the recent upgrade in lockfile version seems to be blocking me. Is there a way to tell deno to use version 2 instead for now? Downgrading deno seems to be more trouble than its worth.

**Comment by nayeemrmn** [comment]
It should auto update if you `deno cache` your project entrypoint.

**Comment by alita-moore** [comment]
I mean to use lockfile 2 instead of lockfile version 3. Is that possible?

**Comment by dsherret** [comment]
> There's one related to stale npm dependencies that we know of: https://github.com/denoland/deno/issues/20868#issuecomment-1756811576

That is unrelated to lockfile v3.
