### ISSUE TITLE
Discussion: using BigInt for certain fs related values

### ISSUE THREAD

**Issue by kevinkassimo** [denoland/deno#2079]
Seeking to polish file system calls to comply better with POSIX spec recently. One thing I noticed is that many values could theoretically exceed `Number.MAX_SAFE_INTEGER`.

However, we have mostly treated them still as if they are all with values smaller than `2**31-1` (similarly in formats of flatbuffers). There are actually cases where we might get/use value larger than this (e.g. seeking on a file of a few Gigs)

Therefore I'm thinking whether a refactoring that uses `BigInt` for these values. (We also need to change our flatbuffers table declaration accordingly).

**Comment by ry** [comment]
I'm slightly worried that using BigInt will kick us out of V8 optimizations. That said, we don't measure it, so I don't particularly care.

I think the proper thing to do here would be to get a benchmark that ran Deno.stat a bunch of times, so we could ensure it doesn't regress.

**Comment by hayd** [comment]
If we use i64/u64 and Number, but assert < Number.MAX_SAFE_INTEGER would that suffice?
This could be coerced prior to sending via the new core dispatcher (e.g. a SafeInteger type in rust).

**Comment by ry** [comment]
Yes @hayd, I think that's a better solution.

**Comment by hayd** [comment]
AtomicU64 is stabilized in rust 1.34, so should be able to define AtomicSafeInteger too.
(So is try_from.)

**Comment by kitsonk** [comment]
This would be very difficult now since we generally use JSON for op messages and JSON doesn't support bigint.

#6169 is more directly actionable, so going to close in favour of that, though the problem still exists about the JSON support.
