### ISSUE TITLE
format jupyter notebook files

### ISSUE THREAD

**Issue by scarf005** [denoland/deno#20810]
while first-class [jupyter notebook integration](https://docs.deno.com/runtime/manual/tools/jupyter) is on, it's not possible to format markdown and typescript content inside `.ipynb` file at the moment.

```sh
$ deno fmt js.ipynb
error: No target files found.
```

being able to format jupyter notebook files will improve QOL greatly.

**Comment by bartlomieju** [comment]
Do you want to format the code within cells or the whole `.ipynb` file?

**Comment by scarf005** [comment]
preferably the whole `.ipynb` file. since `.ipynb` file is internally JSON, i think it could be done by traversing and formatting markdown and ts/js block?

**Comment by bartlomieju** [comment]
Yeah, that makes sense. @dsherret could you provide some pointers here?

**Comment by dsherret** [comment]
I was just looking at ipynb files this weekend. Yeah, I think it would just traverse the json (maybe even just with serde_json), replace the string values for the cells that match typescript/javascript/markdown/json with the result of calling https://github.com/denoland/deno/blob/bf42467e215b20b36ec6b4bf30212e4beb2dd01f/cli/tools/fmt.rs#L227C8-L227C19, then just do serde::to_string_pretty to output the final result (https://docs.rs/serde_json/latest/serde_json/fn.to_string_pretty.html).

**Comment by scarf005** [comment]
would it make sense to parse `.ipynb` in deno fmt or create `.ipynb` plugin for dprint?
