### ISSUE TITLE
`Deno.UnsafePointer` interface change on `main`

### ISSUE THREAD

**Issue by rgbkrk** [denoland/deno#20817]
In my run through of notebooks to make sure `display` is working well I've run into an issue using `skia_canvas` (https://github.com/DjDeveloperr/skia_canvas/issues/61) on `main`. The smallest reproduction I've come up with is:

```typescript
Deno.UnsafePointer.of(new Float32Array(1))
```

It looks like https://github.com/denoland/deno/pull/20509 was when the interface changed (found via `git bisect`). Since I'm unsure of the direction, I don't know if `skia_canvas` needs to update to a new API, given this is on `--unstable`, or if that was just an oversight.

```typescript
deno on   (git)-[bisect/bad|bisect]- [$?] via 🦀 v1.72.1 took 9s
➜ ./target/debug/deno --unstable
Deno 1.37.1
exit using ctrl+d, ctrl+c, or close()
REPL is running with all permissions allowed.
To specify permissions, run `deno repl` with allow flags.
> Deno.UnsafePointer.of(new Float32Array(1))
Uncaught TypeError: expected typed ArrayBufferView
    at Function.of (ext:deno_ffi/00_ffi.js:230:23)
    at <anonymous>:2:20
>

deno on   (git)-[bisect/bad|bisect]- [$?] via 🦀 v1.72.1 took 7s
➜ deno --unstable
Deno 1.37.0
exit using ctrl+d, ctrl+c, or close()
REPL is running with all permissions allowed.
To specify permissions, run `deno repl` with allow flags.
> Deno.UnsafePointer.of(new Float32Array(1))
[Object: null prototype] {}
```

**Comment by mmastrac** [comment]
I suspect we need to use `#[anybuffer]` for `op_ffi_ptr_of`

**Comment by rgbkrk** [comment]
Sweet, thanks.
