### ISSUE TITLE
Can Deno / Does Deno invalidate import caches based on headers?

### ISSUE THREAD

**Issue by tmcw** [denoland/deno#20828]
I asked this on Discord but I think it slipped by:

I've seen via an issue ( https://github.com/denoland/deno/issues/16296 ) that Deno stores its metadata.json files in its cache directory so that it has response headers from when the dependency was downloaded, for cache invalidation. Is there cache invalidation based on these headers? Like if I have a dependency via HTTP that has Cache-Control: no-cache, can it be re-downloaded each time it's requested?

**Comment by lino-levan** [comment]
This would be quite cool, but currently it does not respect any `Cache-Control` headers. I think it should? Thoughts, @bartlomieju?

**Comment by lucacasonato** [comment]
Deno does not respect `Cache-Control` headers. Doing so would break our security model where you can audit what modules will be loaded by calling `deno info`, and then run with `deno run`, knowing that the files you audited are the same ones that will be executed.

**Comment by lino-levan** [comment]
I think it would be cool to respect `Cache-Control` headers because sometimes there are scripts which you want to reload every time. I think it should be behind a flag though (`--unsafely-respect-cache-control`).

**Comment by lucacasonato** [comment]
I think --reload=<filter> already covers this case.

**Comment by lucacasonato** [comment]
I'm going to close this, because the question in the OP is answered.
