### ISSUE TITLE
Support of importing files as `.json5`

### ISSUE THREAD

**Issue by pubmikeb** [denoland/deno#20833]
JSON is a great (de-)serialization format for apps' configs and data.
However, it doesn't support comments. Luckly, there are two formats, which support comments in JSON: `.jsonc` and `.json5`.

As a modern application environment, it would be great to be able to use `.jsonc` and `.json5` instead of classical `.json` in projects.

Following https://github.com/denoland/deno/issues/20374, please add support importing files as `.json5`.

**Comment by lucacasonato** [comment]
I'll fold this into https://github.com/denoland/deno/issues/20374
