### ISSUE TITLE
deno1.37.1 compile --output invalid

### ISSUE THREAD

**Issue by xuybin** [denoland/deno#20837]
deno1.37.1 compile --output invalid on windows
![image](https://github.com/denoland/deno/assets/10354549/ae294f19-5a82-438d-92af-f3402290a3ff)

**Comment by dsherret** [comment]
The `--output` and `-o` are being provided as arguments to the script because they come after the script name. If you write `console.log(Deno.args)` in main.ts you will observe that occurring.

To fix this, provide the `--output` flag before the script argument (before `main.ts`).

**Comment by xuybin** [comment]
> The and are being provided as arguments to the script because they come after the script name. If you write in main.ts you will observe that occurring.`--output``-o``console.log(Deno.args)`
> 
> To fix this, provide the flag before the script argument (before ).`--output``main.ts`

it ok
