### ISSUE TITLE
Unknown import attributes should not be supported

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#20843]
Example: `import "https://examples.deno.land/hello-world.ts" with { asd: "asd" };`

This should throw a `TypeError`. See step 11.f) of https://tc39.es/proposal-import-attributes/#sec-evaluate-import-call

cc @dsherret

**Comment by lucacasonato** [comment]
Two related WPTs are failing:

```
        “/html/semantics/scripting-1/the-script-element/import-assertions/dynamic-import-with-assertion-argument.any.html - Dynamic import with an unsupported import assertion should fail”
        “/html/semantics/scripting-1/the-script-element/import-assertions/dynamic-import-with-assertion-argument.any.worker.html - Dynamic import with an unsupported import assertion should fail”
```

**Comment by bartlomieju** [comment]
This should probably be implemented in `deno_core` in `validate_import_assertions` functions (`core/modules/mod.rs`).

**Comment by bartlomieju** [comment]
When we upgrade `deno_core` these tests should now start working correctly.

**Comment by bartlomieju** [comment]
Done in https://github.com/denoland/deno/pull/21242.
