### ISSUE TITLE
Confusing warning for benchmark start() and end() calls under 0.01s

### ISSUE THREAD

**Issue by sgwilym** [denoland/deno#20853]
```
Warning: start() and end() calls in "<benchmark>" are ignored because it averages less
than 0.01s per iteration. Remove them for better results.
```

This came up when I was trying to benchmark the 1000th insert into a data structure. Something like this:

```ts
Deno.bench(
	"1000th Insert",
	(bench) => {
		const tree = new FancyTree();

		// Here I set up things up...
		for (let i = 0; i < 1000; i++) {
			tree.insert(i);
		}

		bench.start();

		// And here is the bit I actually want to measure.
		// But I'm being told I shouldn't.
		tree.insert(1000);

		bench.end();
	},
);
```

I don't want to remove `bench.start()` and `bench.end()` because then I'll be measuring the duration of the 999 other inserts. So this warning doesn't really help me (nor does it help me understand why this 0.01s limitation is in place when it doesn't seem to apply elsewhere).

Related to #20272.

**Comment by lino-levan** [comment]
Well the issue with this is that the benchmark ends so fast that most of the benchmark is spent in not doing your operation. It's essentially just noise. This is a warning to say "hey, this data is going to be super inaccurate, make your test longer!". I think it good be better worded.

**Comment by nayeemrmn** [comment]
Specifically the part between the start and end is really short so using start and end will give a higher time than is accurate. But without accounting for the stuff outside maybe it shouldn't blindly suggest removing them. And maybe it shouldn't ignore them, just output a warning that results might be inaccurate.

Also the message is wrong about the time, it should be 0.01ms or 10µs.

**Comment by nayeemrmn** [comment]
Actually we should measure the total time (not between start/end) when deciding if the test is too short or not.

**Comment by sgwilym** [comment]
It's also a bit confusing as benchmarks which don't use `start` and `stop` seem perfectly content to measure things below 10µs.
