### ISSUE TITLE
napi_{ref,unref}_threadsafe_function are not idempotent

### ISSUE THREAD

**Issue by Bannerets** [denoland/deno#20861]
As per the Node.js [doc](https://nodejs.org/api/n-api.html#napi_ref_threadsafe_function), these functions should be idempotent. That is, `ref(); ref(); unref()` should keep the TSFN in the unref state, however in deno that keeps the process running, since ref/unref are implemented using a counter (`ref_counter`) and a `> 0` check instead of a boolean.

https://github.com/denoland/deno/pull/17304 related

P.S. Looking at the implementation, acquire/release seem not to be thread-safe, though the Node.js doc states "This API may be called from any thread". ref and unref, on the other hand, are not required to be thread-safe.

deno v1.37.1.

**Comment by devsnek** [comment]
Fixed in https://github.com/denoland/deno/pull/24101
