### ISSUE TITLE
Missing variable declaration for encoder in deno manual entry

### ISSUE THREAD

**Issue by johnsonjo4531** [denoland/deno#2086]
Hello, this is my first deno issue. I feel like tons of progress has been made on this project over the last couple of months, so great job so far to all the people making this project happen! Anyways, in the deno manual in the ["Inspecting and revoking permissions" section](https://deno.land/manual.html#inspectingandrevokingpermissions) the code block is missing the `encoder` variable declaration. I assume it just needs to use the [`TextEncoder`](https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder/TextEncoder) browser api like so `const encoder = new TextEncoder();` on the line before creating the encoder like in [`Deno.write()`](https://deno.land/typedoc/index.html#write). I could submit a pull request to fix the docs I assume I do not have to run the test, formatter, or linter on the example code as outlined in the [contributing section of the manual](https://deno.land/manual.html#contributing), but let me know if this is wrong. Maybe I should read the style guide though (I've only briefly viewed it). I have 3 options I thought of for fixing this:

First of all it currently looks like this:

```js
const { permissions, revokePermission, open, remove } = Deno;

(async () => {
  // lookup a permission
  if (!permissions().write) {
    throw new Error("need write permission");
  }

  const log = await open("request.log", "a+");

  // revoke some permissions
  revokePermission("read");
  revokePermission("write");

  // use the log file
  await log.write(encoder.encode("hello\n"));

  // this will prompt for the write permission or fail.
  await remove("request.log");
})();
```

Option 1 - I assume this could work without a comment. This could be good as it isn't as necessary to highlight and explain the TextEncoder api to them in a permissions example.

```js
  ...
  revokePermission("write");

  const encoder = new TextEncoder();
  
  // use the log file
  await log.write(encoder.encode("hello\n"));
  ...
```

Option 2 - maybe with a comment.

```js
  ...
  revokePermission("write");

  // create a utf-8 text encoder
  const encoder = new TextEncoder();
  
  // use the log file
  await log.write(encoder.encode("hello\n"));
  ...
```

Option 3 - possibly inline, although the other docs always call the encoder `encoder` and do not do inline for example [`Deno.write()`](https://deno.land/typedoc/index.html#write).

```js
  await log.write(new TextEncoder().encode("hello\n"));
```

Option 4 - similar to option 1 with no comment, but pair the encoder with the writing of the file.

```js
  ...
  revokePermission("write");
  
  // use the log file
  const encoder = new TextEncoder();
  await log.write(encoder.encode("hello\n"));
  ...
```

**Comment by bartlomieju** [comment]
Options 1 and 4 looks like a way to go, feel free to raise a PR for that

**Comment by bartlomieju** [comment]
Closing as stale
