### ISSUE TITLE
Type checks for web worker

### ISSUE THREAD

**Issue by sergeysolovev** [denoland/deno#20888]
I created a file for web worker. VSCode highlights errors and also `deno check worker.ts` doesn’t pass with the same errors.

<img width="465" alt="Screenshot 2023-10-12 at 5 38 09 PM" src="https://github.com/denoland/deno/assets/5831301/798cfcf9-6168-45c9-8fed-843f3560ac03">

Is is expected behaviour?

**Comment by sigmaSd** [comment]
I think its a good idea if that part was reference here https://docs.deno.com/runtime/manual/runtime/workers

**Comment by sergeysolovev** [comment]
@sigmaSd Thank you, that’s amazing!

> I think its a good idea if that part was reference here https://docs.deno.com/runtime/manual/runtime/workers

Yes I was looking for it there
