### ISSUE TITLE
`deno check .`

### ISSUE THREAD

**Issue by harrysolovay** [denoland/deno#20889]
I often want to type-check my entire project (not just members of an entry-point-specified module graph). I created [star](https://github.com/crosshatch/star), a utility to solve this... but this adds boilerplate. I believe this feature should be possible via the Deno CLI's `check` command. Perhaps one could specify a directory instead of an entry point?

```sh
deno check .
```

**Comment by crowlKats** [comment]
Duplicate of #20813

**Comment by harrysolovay** [comment]
Whoops, sorry!
