### ISSUE TITLE
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', cli\npm\resolvers\local.rs:100:29

### ISSUE THREAD

**Issue by eavidy** [denoland/deno#20883]
**Reproduction steps**

On Windows, execute the following commands in order:
`git clone git@github.com:ieavid/example.git`  (This repository simply creates an example:  https://github.com/ieavid/example)
`cd example`
` pnpm install`
` cd packages/mod-a`

Then execute ` deno run src/a2.ts` to print:
```
============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: windows x86_64
Version: 1.37.1
Args: ["A:\\back-end\\deno\\deno.exe", "run", "src/a2.ts"]

thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', cli\npm\resolvers\local.rs:100:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
**Other Notes:**
pnpm version: 8.7.4

**Comment by tannal** [comment]
Delete package.json in packages/mod-a, the problem will disappear.
It has something to do with package json dependencies resolution in deno.

The idea of monorepo doesn't fit in deno.
see denoland/deno/discussions/9126 and denoland/deno/discussions/18143

Import map in deno.json and deps.ts can help you manage your dependencies.
https://docs.deno.com/runtime/manual/basics/import_maps
https://docs.deno.com/runtime/tutorials/manage_dependencies
https://docs.deno.com/runtime/manual/basics/modules/

**Comment by kt3k** [comment]
hmm the example repository doesn't seem existing now..

**Comment by eavidy** [comment]
> hmm the example repository doesn't seem existing now..

I seem to have accidentally deleted the repository. Now I can't remember how the bug was reproduced. deno didn't support workspaces back then, so I used some weird imports that caused bugs. Now that deno supports workspaces, I think we can close the issue
