### ISSUE TITLE
Deno doesn't provide Node globals for files dynamically imported from npm package

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#20886]
Following issues are affected:
- https://github.com/denoland/deno/issues/20852 - tries to read `process.env` from `process`
- https://github.com/denoland/deno/issues/20339 - tries to read `process.env` from `process` in `.nitro/dev/index.mjs`
- https://github.com/denoland/deno/issues/20609 - tries to read `globalThis.location`, because `window` variable is defined in `.vitepress/.temp/app.js` - this file should be most likely served with "Node" globals

**Comment by birkskyum** [comment]
- #23474
