### ISSUE TITLE
Embed files when using deno compile 

### ISSUE THREAD

**Issue by maekoos** [denoland/deno#20885]
Is there a way to embed static files when compiling a deno project using `deno compile`?

I have not found any good solution to do this when I'm not in charge of accessing the filesystem. For context, I'd like to embed all of my SSR-templates and static files in the binary itself to make my web server easier to distribute. All of the solutions I have found so far (e.g. [leaf](https://deno.land/x/leaf@v1.0.4)) requires control over how files are accessed - which I don't have (nor want to have) when using a library such as Nunjucks.

**Comment by maekoos** [comment]
I may be interested in having a try at implementing this... However, I haven't contributed or even modified deno internals before. Is there anything I should know, other than what the instructions say?

I started reading the source code for the compile command and I noticed the whole module is serialized as eszip before it is embedded. Now, if I were to add this functionality, would it be appropriate to modify the eszip library to include assets as well? Or should I go for a more separate implementation, maybe appending the embedded files directly after the eszip? I also assume I would have to modify some fs ops to direct some operations to the embedded files?

**Comment by eseiker** [comment]
I also want that feature badly...
and seems related to https://github.com/denoland/deno/issues/17994

**Comment by MohsinDev369** [comment]
Node now supports embedding assets, Can we use "node sea" with "Deno compile" to solve this problem?

**Comment by i-api** [comment]
this would be an amazing feature!

**Comment by BlackAsLight** [comment]
With a little build script and fiddling, you could embed them as a base64 string
