### ISSUE TITLE
make deno xx.ts --fmt print output to stdout

### ISSUE THREAD

**Issue by axetroy** [denoland/deno#2090]
### Why print output to stdout?

For better integration by third parties.

Such as the IDE's formatting tool.

ref: https://github.com/denoland/deno_std/pull/332

This is my proposal, I hope it helps.

**Proposal 1:**

```bash
deno fmt xxx.ts # print formatted code to stdout
deno fmt xxx.ts --write # write formatted code to file
```

**~Proposal 2:~**

~add a new flags `--fmt-stdout` for `deno`~

**Comment by justjavac** [comment]
**gofmt**: by default, prints the reformatted sources to stdout, output to files using `-w`

**rustfmt**: by default, prints the reformatted sources to file, output to stdout using `--emit stdout`.

**Comment by zaynv** [comment]
For most users, the use case will be to just run it on files? Wouldn't it make more sense to make the default user-friendly by making `--write` default and then make a flag to print it to stdout like `--stdout` so editors and such can use it.

**Comment by kt3k** [comment]
gofmt outputs the formatted contents to stdout, but `go fmt` subcommand formats the contents and writes into files.

I think `deno fmt` is modeled after `go fmt`, so I prefer writing by default, stdout with options.

@ry
How do you think?

**Comment by ry** [comment]
I agree @kt3k

**Comment by kt3k** [comment]
I'm going to send a PR, implementing the following design:

- `deno fmt` formats and writes to the files
  - It maps to `deno run .../std/prettier/main.ts --write`
- `deno fmt --emit` formats and write to stdout
  - It maps to `deno run ../std/prettier/main.ts`

**Comment by kt3k** [comment]
I think we need to perform some steps to achieve the above without breaking the latest version of deno.

1. First, make `deno fmt` maps to `deno run .../std/prettier/main.ts --write`, this doesn't make any effect, but it prepares for the change of deno_std, https://github.com/denoland/deno_std/pull/332

2. Release deno including the above. At this point merging https://github.com/denoland/deno_std/pull/332 doesn't break `deno fmt`. So we can merge it.

3. Merge https://github.com/denoland/deno_std/pull/332.

4. Implement `deno fmt --emit` using the above std's change.

**Comment by ry** [comment]
@kt3k Thanks for handling this! SGTM

**Comment by axetroy** [comment]
@kt3k

Don't consider adding a flag to make `deno fmt` output to stdout?

eg `deno fmt xxx.ts --emit-stdout`

**Comment by kt3k** [comment]
@axetroy 
Yes, I'm planning it. That's step 4 in the above plans. We need to do that after merging https://github.com/denoland/deno_std/pull/332 (because that needs the function the PR includes.)

`--emit-stdout` would be ok. I think `--emit` or `--stdout` also possible.
