### ISSUE TITLE
[Docs]: LICENSE Section is missing in README.md File

### ISSUE THREAD

**Issue by malivinayak** [denoland/deno#20912]
LICENSE Section is missing in README.md File

I can add the LICENSE section in the README file with enhanced presentation. Also I will add a MIT logo, license badge and update text with a cleaner format, including a hyperlink to the LICENSE file.

### example screenshots

![image](https://github.com/shyamtawli/devFind/assets/66154908/f26ee346-74b9-4aa9-8912-d2de23f02e4e)

**Comment by dsherret** [comment]
Thanks, but the license is already in the repository at LICENSE.md, in the docs, and displayed prominently on GitHub

![License displayed on GitHub](https://github.com/denoland/deno/assets/1609021/a50342e4-78d6-4f68-9b31-8f439f606fae)
