### ISSUE TITLE
Deno fmt incorrectly formats GitHub Markdown alerts 

### ISSUE THREAD

**Issue by benStre** [denoland/deno#20917]
GitHub supports [Alerts](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts) in Markdown files. Alerts are created with the following syntax:

```md
> [!NOTE]
> Highlights information that users should take into account, even when skimming.
```

When running `deno fmt`, this gets converted to 

```md
> [!NOTE] Highlights information that users should take into account, even when skimming.
```

Because of the missing newline, GitHub does not interpret this as a "NOTE" alert anymore.

It would be great if `deno fmt` would keep the newline in this case so that alerts keep working in Markdown files.

**Comment by dsherret** [comment]
For now you can do:

``````
<!-- deno-fmt-ignore -->
> [!NOTE]
> Highlights information that users should take into account, even when skimming.
``````

**Comment by ngdangtu-vn** [comment]
I have better solution for your case:

```md
> [!NOTE]\
> Highlights information that users should take into account, even when skimming.
```
