### ISSUE TITLE
[feat] Make backend js ecosystem future better

### ISSUE THREAD

**Issue by loynoir** [denoland/deno#20919]
### Feature Request

Make backend js ecosystem future better.

### What changed?

Program language like `rust` and `zig`, leads to new backend js/ts runtime like `deno` and `bun`.

### What is the problem?

`npm` is awesome.

To use awesome `npm` package for **backend**, usually need `Node.js` core module.

But, currently, because three runtime not able to share same `Node.js` core module, when use `deno` or `bun` with `npm` packages, there are compatibility issues.

Because `Node.js` `deno` `bun` does not able to share same `Node.js` core module and spec and test, `deno` `bun` reinvent the not-fully-compact wheel individually, and not reinvent-once-use-forever.

### What maybe the solution?

`Node.js` `deno` `bun` all support `napi`.

- `deno` napi since [pull/13633](https://github.com/denoland/deno/pull/13633), stable at [v1.31](https://deno.com/blog/v1.31#stabilization-of-node-api)

- `bun` is also [implementing](https://github.com/oven-sh/bun/issues/158) napi

<details>
  <summary markdown="span">Extra</summary>

I don't know if override core module is needed for solution. 

If it does, I guess `Node.js` loader and `deno` importmap should works.

</details>

### What is the feature request?

- Rewrite `Node.js` core module using `napi`

- Rewrite `Node.js` core module test using `javascript`, so `Node.js` `deno` `bun` `browserify-XXX` can share **SAME** test

- Publish `napi` version of `Node.js` core module to `npm`

- Maybe publish to `npm` under a new organization `@backend-javascript-core-module-standard-committee/http`

### Related

- https://github.com/nodejs/node/issues/50195

**Comment by loynoir** [comment]
As `Node.js` close the feat, another idea is, create a maybe-non-node-js-style core library using napi.

So, `Node.js` `deno` `bun` can use this isomorphic backend core library.

**Comment by lucacasonato** [comment]
Not something we are going to work on. Out of scope.
