### ISSUE TITLE
error: Uncaught TypeError: os.machine is not a function, import * as os from 'node:os'

### ISSUE THREAD

**Issue by lauer3912** [denoland/deno#20915]
![image](https://github.com/denoland/deno/assets/1635018/1ac2d9ac-6c6c-46e6-b987-261affc3f8e9)

**Comment by MarybethGasman** [comment]
We need a function in ext/node/polyfills/os.ts.

```ts
// ext/node/polyfills/os.ts
export function machine(): string {
  // call some rust/js code to get some system info
  return type;
}
```
To implement this, we might need to add an ops in runtime/ops/os/sys_info.rs,
 or we already have some utils to do this in js
 
I'm unfamiliar with the Rust part of Deno and how to call Rust code within a JavaScript script in Deno.
I'm willing to work on this issue with some help.

**Comment by littledivy** [comment]
Fixed by https://github.com/denoland/deno/pull/21751
