### ISSUE TITLE
Jupyter language server considers cells separately - regression in v1.37.2

### ISSUE THREAD

**Issue by mrgrain** [denoland/deno#20920]
Consider the following simple notebook:
<img width="468" alt="image" src="https://github.com/denoland/deno/assets/379814/b15adcd7-ddb2-4f78-ac76-97c5cb19dace">

This notebook works as expected. It defines the variable `hello` in cell 1 and has no problem printing it from cell 2.
The issue is that the language server incorrectly evaluates the context of each cell separately and fails to find the `hello` variable in cell 2 (red squiggly line, see screenshot below). This used to work correctly in v1.37.1.

<img width="563" alt="image" src="https://github.com/denoland/deno/assets/379814/6c0108c5-fbff-4de8-b844-3a7701713464">

There is a variation of this issue involving `globalThis`. Also used to work in v1.37.1.
<img width="345" alt="image" src="https://github.com/denoland/deno/assets/379814/c13761d9-d61e-4919-86cd-79e6498eb7d5">
With `stuff.ts` being:
```ts
globalThis.hello2 = 'also world';
```

Full notebook source:

```jupyter
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "const hello = \"world\";"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "world\n"
     ]
    }
   ],
   "source": [
    "console.log(hello);"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Deno",
   "language": "typescript",
   "name": "deno"
  },
  "language_info": {
   "file_extension": ".ts",
   "mimetype": "text/x.typescript",
   "name": "typescript",
   "nb_converter": "script",
   "pygments_lexer": "typescript",
   "version": "5.2.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
```

**Comment by nayeemrmn** [comment]
Tracked in https://github.com/denoland/vscode_deno/issues/932.

I believed it worked in previous versions because the Deno LSP wasn't being used at all, and it wouldn't have worked for cells containing imports. Correct me if I'm wrong.

**Comment by mrgrain** [comment]
Ah apologies for the duplicate. 🙏🏻 

> I believed it worked in previous versions because the Deno LSP wasn't being used at all, and it wouldn't have worked for cells containing imports. Correct me if I'm wrong.

This might well be the case, but I don't know for sure 😅
