### ISSUE TITLE
deno native os api enhancements

### ISSUE THREAD

**Issue by markthree** [denoland/deno#20933]
Ref context: https://discord.com/channels/684898665143206084/1164090264852369458

deno native os api seems to be missing a lot of node compatibility layers

for example 👇

```ts
import os from "node:os"

os.cpus().length // normal output

Deno.cpus().length // throw error, Missing api
```

```ts
import { homedir } from "node:os"

homedir() // normal output

Deno.homedir() // throw error, Missing api
```

Of course this is not a priority as there are node compatibility layers that can be used instead

**Comment by marvinhagemeister** [comment]
The number of CPUs is available under `navigator.hardwareConcurrency`, see https://developer.mozilla.org/en-US/docs/Web/API/Navigator/hardwareConcurrency

Not sure about a deno native way to get the home dir.

**Comment by markthree** [comment]
> The number of CPUs is available under `navigator.hardwareConcurrency`, see https://developer.mozilla.org/en-US/docs/Web/API/Navigator/hardwareConcurrency
> 
> Not sure about a deno native way to get the home dir.

Thanks, but I think it would be better to have a clearer API。The vast majority of developers are not familiar with `navigator.hardwareConcurrency` 🤣

**Comment by markthree** [comment]
> The number of CPUs is available under `navigator.hardwareConcurrency`, see https://developer.mozilla.org/en-US/docs/Web/API/Navigator/hardwareConcurrency
> 
> Not sure about a deno native way to get the home dir.

Thanks, but I think it would be better to have a clearer API。The vast majority of developers are not familiar with `navigator.hardwareConcurrency` 🤣

**Comment by lucacasonato** [comment]
@markthree A lot of web developers are familiar with `navigator.hardwareConcurrency`. It is the way to get this info in the browser. Searching for "get thread count javascript" gives you this API as the first and second result: https://www.google.com/search?q=get+thread+count+javascript

If you want to open a more focussed issue for adding a `Deno` API to get home dir / photos dir etc, please do.

**Comment by markthree** [comment]
> @markthree A lot of web developers are familiar with `navigator.hardwareConcurrency`. It is the way to get this info in the browser. Searching for "get thread count javascript" gives you this API as the first and second result: https://www.google.com/search?q=get+thread+count+javascript
> 
> If you want to open a more focussed issue for adding a `Deno` API to get home dir / photos dir etc, please do.

nice，This is a perspective that I have never thought of before, web standards can unify everything。
