### ISSUE TITLE
Deno.serve crashes if nothing is returned

### ISSUE THREAD

**Issue by zadeviggers** [denoland/deno#20947]
Something that I just had to spend a while debugging was this error: ![image](https://github.com/denoland/deno/assets/74938858/585d51aa-6b73-454f-9960-cdf66b5aa4de)

It turns out that the whole `Deno.serve` sever crashes if nothing is retuned from a request handler, which happens when my route matching code doesn't find anything, but I wasn't returning a custom 404 error.

Even if this is intended behaviour (which I don't think is great), it would be nice to have a more helpful error message.

To reproduce:
```ts
Deno.serve(() => {});
```

**Comment by codesculpture** [comment]
Hi all, is anyone working on this. Because i tried to fix this and i got the part where it needs to be fixed. If no one working on this i can help.

**Comment by mmastrac** [comment]
@codesculpture This is on my list of things to fix in the new few weeks or so but if you have a PR ready to go I'm happy to review it for the next patch release

**Comment by codesculpture** [comment]
The problem is that we are not giving fallback if no response is provided (i.e when handler return undefined). So can we add a fallback Response or what we can do in such a situation ? @mmastrac

**Comment by mmastrac** [comment]
I think we could safely call the error handler in the case of an Invalid or null return value.

**Comment by codesculpture** [comment]
I believe here we are strictly expecting only Response class as return value from the handler or we are gonna tolerate other than this (ex: strings, numbers)  Deno.serve(() => "Welcome") or Deno.serve(() => 12) ?

**Comment by bartlomieju** [comment]
Correct, only `Response` is expected as a return type.

**Comment by codesculpture** [comment]
https://github.com/denoland/deno/pull/21099 @mmastrac here i raised a PR, kindly look at it

**Comment by zadeviggers** [comment]
@codesculpture thanks for fixing this!
