### ISSUE TITLE
I think Deno.PointerObject should support Null Pointer.

### ISSUE THREAD

**Issue by KatsutoshiOtogawa** [denoland/deno#20940]
For example, there are a large number of functions in win32api that assume the use of NULL pointers,
When executing functions of win32api via deno_ffi, it is inevitably necessary to pass a NULL pointer.

No source code changes are required on the deno_core side,
Just pass 0 (address of C null pointer) to UnsafePointer.create as shown below to create a C null pointer.

```ts
const NullPtr = Deno.UnsafePointer.create(0);
```

[Deno.UnsafePointer](https://deno.land/api@v1.37.2?s=Deno.UnsafePointer&unstable=&p=create)
[Deno.PointerObject](https://deno.land/api@v1.37.2?s=Deno.PointerObject&unstable=)

If Deno want to support null pointers in Deno.PointerObject, just add that null pointers are supported and how to create a null pointer on the document side here.

If Deno do not support null pointers in Deno.PointerObject, Deno need to implement an object in ffi that supports being a null pointer, such as Deno.NullPtr.

**Comment by aapoalas** [comment]
A null pointer is represented as a JavaScript `null` directly.

**Comment by aapoalas** [comment]
Also see the normal maybe-null pointer value type:
https://deno.land/api@v1.37.2?s=Deno.PointerValue&unstable=
