### ISSUE TITLE
[jupyter-kernel] Deno enabled in VScode breaks notebooks

### ISSUE THREAD

**Issue by karelklima** [denoland/deno#20955]
**Deno language features within Jupyter notebooks do not work in VScode if Deno is enabled in the workspace.**

**System:**
- Windows 10
- Deno 1.37.2
- Python 3.12.0
- VS Code: 1.83.1
- Deno vscode extension: 3.26.0
- Jupyter vscode extension: 2023.9.1102792234

**Steps to reproduce:**
- create an empty folder and open it in VS Code
- create a Jupyter Notebook file, select Deno kernel and TypeScript language
- in the Notebook, create a variable in one code block and reference it in a second code block - at this point everything works
- create deno.json file
- go to the Jupyter Notebook file - at this point the deno autocomplete is broken, the variable reference does not work anymore

![image](https://github.com/denoland/deno/assets/141302/c50d122f-4d3b-4b91-b184-7a2c300d3fe2)

**Comment by nayeemrmn** [comment]
This is tracked in https://github.com/denoland/vscode_deno/issues/932. The same thing would happen with Deno disabled if you used imports in one of the cells, it's just that Deno is always in ESM mode.

**Comment by karelklima** [comment]
@nayeemrmn Thanks for referencing and closing this issue, I didn't find that before posting this one.
