### ISSUE TITLE
LSP does not know about lockfile version 3

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#20964]
![image](https://github.com/denoland/deno/assets/7829205/eeb81cdc-755b-468f-a86e-f21fc1ed4e2d)

**Comment by nayeemrmn** [comment]
This was fixed by https://github.com/denoland/vscode_deno/pull/965, are you on vscode_deno 3.26.0?

**Comment by dsherret** [comment]
I also can't reproduce.
