### ISSUE TITLE
calling `monitorEventLoopDelay` causes Not implemented error

### ISSUE THREAD

**Issue by 5d-jh** [denoland/deno#20961]
Throwing `Not implemented` in `perf_hooks. monitorEventLoopDelay` breaks  prom-client's `eventLoopLag` function. Since prom-client provides workaround logic when it's not exist on older nodejs runtime, set monitorEventLoopDelay to undefined instead would work seamlessly.

Aside from `prom-client`, setting undefined instead of placeholder function seems more intuitive.

**Comment by SebastienGllmt** [comment]
There are multiple things in `perf_hooks` not implemented. For example, `createHistogram` is used by [piscina](https://github.com/piscinajs/piscina) but it's not implemented in deno which leads to a crash

Notably, (more generally than the piscina issue), I believe the current list of missing APIs at the time of posting are

From the `performance` object
- clearMeasures
- clearMeasures
- clearResourceTimings
- getEntries
- setResourceTimingBufferSize

Top-level functions:
- createHistogram

The following classes:
- PerformanceMark
- PerformanceMeasure
- PerformanceNodeEntry
- PerformanceNodeTiming
- PerformanceResourceTiming
- PerformanceObserverEntryList
- Histogram
- IntervalHistogram
- RecordableHistogram
