### ISSUE TITLE
Bug: Missing file tree in DevTools session

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/deno#20960]
Following the steps on https://docs.deno.com/runtime/manual/basics/debugging_your_code there should be a file tree in the left pane of DevTools like shown in the screenshots. But it's not there.

<img width="707" alt="Screenshot 2023-10-24 at 01 30 59" src="https://github.com/denoland/deno/assets/1062408/fe925650-6688-4736-bb65-f38fb4a59423">

## Steps to reproduce

1. Run `deno run --inspect-brk --allow-read --allow-net https://deno.land/std@0.204.0/http/file_server.ts` in any folder
2. Go to `chrome://inspect` and click on the deno entry.

Maybe they changed the protocol?

**Comment by alexgleason** [comment]
I'm seeing the file tree in Deno v1.39.0 and Brave v1.61.104 (Chromium 120.0.6099.115)

![Screenshot from 2023-12-17 13-04-31](https://github.com/denoland/deno/assets/3639540/cb73c738-adea-4242-95de-98952ca1d047)
