### ISSUE TITLE
Local KV: `.listenQueue` should throw once `.close` is called

### ISSUE THREAD

**Issue by johnspurlock-skymethod** [denoland/deno#20991]
To reproduce:

```ts
const kv = await Deno.openKv();
kv.close();
await kv.listenQueue(v => console.log(v)); // should throw like the others
```

```sh
$ deno --version
deno 1.37.2 (release, aarch64-apple-darwin)
v8 11.8.172.13
typescript 5.2.2
```

**Comment by raashidanwar** [comment]
Sure, please assign me the task @igorzi

**Comment by raashidanwar** [comment]
My approach:
I am considering adding a boolean private field, `isClosed`, which will be set to `false` in the constructor and `true` when the `close()` method gets called.
Whenever `listenQueue` gets called, it will check if `isClosed === true and throw an error.

@igorzi Do let me know your thoughts.

**Comment by igorzi** [comment]
@raashidanwar - yes, that sounds good. I think the `isClosed` field can be added in JS-land: https://github.com/denoland/deno/blob/main/ext/kv/01_db.ts.

**Comment by raashidanwar** [comment]
Raised a PR 👉 https://github.com/denoland/deno/pull/21459, @igorzi please review.
