### ISSUE TITLE
stacktrace is affected by an eval statement just existing later in the script

### ISSUE THREAD

**Issue by jbsiddall** [denoland/deno#20993]
run this code:
```
(function hello() {
  console.log('outer stack', new Error().stack)
})();

eval("")
```

Expected Output:
```
outer stack Error
    at hello (file:///....ts:2:30)
    at file:///....ts:3:2
```

Actual Output:
```
outer stack Error
    at hello1 (file:///....ts:2:30)
    at file:///....ts:3:2
```

stacktrace should have function "hello" but instead has "hello1". 

If you remove the eval statement, then the stack trace becomes the expected output.
Deno Version:
```
$ deno --version
deno 1.37.1 (release, x86_64-apple-darwin)
v8 11.8.172.6
typescript 5.2.2
```

Me reproducing the issue in a deno terminal:

https://github.com/denoland/deno/assets/1850562/0a9e0250-a355-4000-97dc-0d8dcca7db39

**Comment by nayeemrmn** [comment]
This is an swc issue, I've opened https://github.com/swc-project/swc/issues/8185.
