### ISSUE TITLE
Update test_util/std/ submodule

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#21002]
We haven't updated `test_util/std/` in a while. It's a git submodule pointing to https://github.com/denoland/deno_std.

I tried doing that in https://github.com/denoland/deno/pull/20994 but I had to revert it in https://github.com/denoland/deno/pull/21001 due to some benchmarks failures.

Turns out we have quite a few links pointing to `https://deno.land/std/examples/*` files. There's also several examples in our CLI help output that point to these files.

We need to update all these invocations to not depend on `https://deno.land/std/examples/*` anymore.

**Comment by iuioiua** [comment]
I'll do this. It'll allow me to come in contact with any possible pain points with std.
