### ISSUE TITLE
Avoid printing JUnit report to the console when `junit-path` is specified

### ISSUE THREAD

**Issue by x80486** [denoland/deno#21021]
I see that generating a JUnit report will always print the same to the console.

Would it make sense to avoid this if `--junit-path` is specified?

**Comment by dsherret** [comment]
It does not print the junit report to the console for me.

```
> deno test --junit-path test.xml
Check file:///V:/scratch/sub.test.ts
running 1 test from ./sub.test.ts
example ... ok (0ms)

ok | 1 passed | 0 failed (1ms)
```

**Comment by x80486** [comment]
Ah! Looks like `--reporter=junit` is what does that. I was going with the assumption I had to use it when `--junit-path` was present as well :roll_eyes:
