### ISSUE TITLE
Support for `create-svelte`

### ISSUE THREAD

**Issue by littledivy** [denoland/deno#21024]
_Originally reported in https://github.com/denoland/deno/issues/17248_

> I built deno from main branch and this gave the below error
> 
> ```
> h7kanna@Harshas-MBP ~ % ./Repos/crates/deno/target/release/deno run -A --unstable --reload npm:create-svelte@latest sveltekit-deno
> 
> create-svelte version 5.1.1
> 
> ┌  Welcome to SvelteKit!
> │
> ◆  Which Svelte app template?
> │  ● Skeleton project (Barebones scaffolding for your new SvelteKit app)
> │  ○ SvelteKit demo app
> │  ○ Library project
> └
> error: Uncaught Error: The _read() method is not implemented
>     at ReadStream.Readable._read (ext:deno_node/_stream.mjs:3101:13)
>     at ReadStream.Readable.read (ext:deno_node/_stream.mjs:2997:16)
>     at resume_ (ext:deno_node/_stream.mjs:3347:16)
>     at Array.processTicksAndRejections (ext:deno_node/_next_tick.ts:33:15)
>     at eventLoopTick (ext:core/01_core.js:180:29)
> ```

During the implementation of `node:tty` we had to make a tradeoff wherein `tty.ReadStream` and `tty.WriteStream` were made to extend a `Duplex` instead of a `net.Socket` because it introduced circular dependencies at snapshot-time. In Node.js, this problem is solved by using a require at runtime:

```js
switch (getHandleType(fd)) {
  // ...
  case "TTY": {
    const tty = require("tty");
    return tty.ReadStream(fd);
  }
}
```

**Comment by benmccann** [comment]
Thanks! The usage of these APIs in `create-svelte` comes from `@clack/prompts`, so I'd guess that there's going to be a number of other frameworks affected, which use that library as well. I just had a quick look, so there easily could be more, but I found a few that just got closed and I wonder if they're actually fixed. These look to me like they could potentially be affected as well:
- https://github.com/denoland/deno/issues/20890
- https://github.com/denoland/deno/issues/20611 (https://github.com/BuilderIO/qwik/blob/ab67f91f707ad3baa6e15499d11753e84f7b9a9b/packages/create-qwik/src/run-create-interactive-cli.ts#L3C1-L3C1)
- https://github.com/denoland/deno/issues/20336 (https://github.com/unjs/consola/blob/a440c4d4bbc39135a1514bcd78fcbaba2c571285/package.json#L78)

**Comment by littledivy** [comment]
Thanks, re-opened them
