### ISSUE TITLE
Max Header Size

### ISSUE THREAD

**Issue by mcgear** [denoland/deno#21047]
Is there a max header size for deno requests/responses?

**Comment by littledivy** [comment]
Deno uses `hyper`'s default limits for headers size:
- Max headers is 100 https://github.com/hyperium/hyper/blob/0eb1b6cf4d914ce9c3f8e92a8b43754eba27a327/src/proto/h1/role.rs#L31
- Max buffer size is 800Kb. If the headers haven't finished by that limit, the response will be canceled. https://github.com/hyperium/hyper/blob/0eb1b6cf4d914ce9c3f8e92a8b43754eba27a327/src/proto/h1/io.rs#L23

Ref https://github.com/hyperium/hyper/issues/1748#issuecomment-455383383
