### ISSUE TITLE
Migrate tests to use "Promise.withResolvers()"

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#21041]
When https://github.com/denoland/deno/pull/21036 lands the new `Promise.withResolvers()` API will be available. We should migrate `cli/tests/` to use this new API instead of `deferred` from `std/async/mod.ts`.

**Comment by tmdh** [comment]
I am working on this issue. Should I submit all my changes in one commit?

**Comment by iuioiua** [comment]
Seems like this issue can be closed now.

**Comment by bartlomieju** [comment]
There's still multiple tests in `cli/tests/testdata/run/` that use `deferred()`.
