### ISSUE TITLE
`new Response()` does not accept Node.js stream

### ISSUE THREAD

**Issue by jcbhmr** [denoland/deno#21063]
The `Response` constructor is a very easy way to convert a stream to text via `.text()` or JSON via `.json()`. The following behaviour seems to differ in Node.js and Deno:

```js
console.log(await new Response(process.stdin).text())
```

Node.js:

```sh
echo hi | node -e 'new Response(process.stdin).text().then(console.log)'
```
```
hi
```

Deno:

```sh
echo hi | deno eval 'import process from "node:process";new Response(process.stdin).text().then(console.log)'
```

```
[object Object]
```

**Comment by jcbhmr** [comment]
I can also confirm that this **also happens when inside the Node.js compat layer**. So if an `npm:mypackage` uses this trick to read from stdin, it will fail.

```sh
jcbhmr@PIG-2016:~/Documents/deno-response-test$ tree -a
.
├── deno.json
├── deno.lock
├── main.ts
├── main_test.ts
├── node_modules
│   ├── .deno
│   │   ├── .deno.lock
│   │   ├── .deno.lock.poll
│   │   ├── .setup-cache.bin
│   │   ├── nocode@1.0.0
│   │   │   ├── .initialized
│   │   │   └── node_modules
│   │   │       └── nocode
│   │   │           ├── nocode.js
│   │   │           └── package.json
│   │   └── node_modules
│   ├── .package-lock.json
│   └── nocode -> /home/jcbhmr/Documents/deno-response-test/node_modules/.deno/nocode@1.0.0/node_modules/nocode
├── package-lock.json
└── package.json

7 directories, 13 files
```
```js
jcbhmr@PIG-2016:~/Documents/deno-response-test$ cat node_modules/.deno/nocode@1.0.0/node_modules/nocode/nocode.js
new Response(process.stdin).text().then(console.log)
```
```sh
jcbhmr@PIG-2016:~/Documents/deno-response-test$ echo hi | deno run main.ts
[object Object]
```

**Comment by lucacasonato** [comment]
Node is spec incompatible here and supports a behavior that is not standard. You can do `new Response(ReadableStream.from(...)).text()` instead.

**Comment by petamoriken** [comment]
Node.js's `Response` seems to have extension to convert from `AsyncIterable`.

https://github.com/nodejs/node/blob/a450eedffade72d31624dbbd9171ac87b28c436a/deps/undici/src/lib/fetch/response.js#L542-L546

**Comment by jcbhmr** [comment]
Would this be possible to do only in `npm:` scopes similar to the `setTimeout` and `setInterval` shadowing? Or is this too niche and likely to be removed from nodejs that this is a no-go?
