### ISSUE TITLE
Deno panics when --html --name=index.html

### ISSUE THREAD

**Issue by chrisbobek** [denoland/deno#21088]
After upgrading to v1.38.0, I ran deno doc --html --name=index.html from Windows Terminal.

Deno panics whenever this is run.

**Comment by crowlKats** [comment]
What is the panic?

**Comment by dsherret** [comment]
Duplicate of https://github.com/denoland/deno/issues/21067

Will be fixed in the next patch release. Try running `deno doc --html --name=YourLibraryName mod.ts` instead.
