### ISSUE TITLE
Explanation on why the process fully restarted with --unstable-hmr

### ISSUE THREAD

**Issue by nestarz** [denoland/deno#21101]
Hello ! Thanks for your work.

During the development phase, in an instance of utilizing the --unstable-hrm command, it was observed that the entire process restarts. This occurrence was contrary to the expectation that --unstable-hmr would only restart the parts that had been modified. 

Thus, it seems that there might be a potential issue in the Hot Module Replacement (HMR) feature. Moreover, there isn't a clear documentation or explanation regarding this particular behavior. This issue arises a need for a more thorough explanation in the documentation about why the whole process restarts in spite of using --unstable-hmr flag, aimed to ease the development process and understanding of its execution. 

Please provide more insight or fix if it's a bug.

**Comment by bartlomieju** [comment]
An information is printed if HMR can't be performed with the reason - try running with `--no-clear-screen`. It should be more visible then.

**Comment by nestarz** [comment]
@bartlomieju Thanks for your answer, unfortunately it doesn't seems to help with this argument. I have `HMR File change detected! Restarting!` displayed, and nothing more about HMR, I don't have any code that clear my console.

**Comment by bartlomieju** [comment]
Could you provide the code you are running?

**Comment by nestarz** [comment]
My initial code is a bit long but it does not work neither with the following:

```
let a = 1;
addEventListener("hmr", (e) => {
  console.log("HMR triggered", a, e.detail.path);
});
console.log(a++);
```

And then I run `deno run --unstable-hmr main.tsx`

**Comment by nestarz** [comment]
Another example not working is the following:

```ts
import { router } from "rutt";

addEventListener("hmr", (e) => {
  console.log("HMR triggered ok", e.detail.path);
});

let a = 0;
setInterval(() => console.log(a++), 100);

await Deno.serve(
  { port: 8025 },
  router({
    "/": () => new Response(a++)
  }),
).finished;
```

**Comment by bartlomieju** [comment]
> My initial code is a bit long but it does not work neither with the following:
> 
> ```tsx
> // main.tsx
> let a = 1;
> addEventListener("hmr", (e) => {
>   console.log("HMR triggered", a, e.detail.path);
> });
> console.log(a++);
> ```
> 
> And then I run `deno run --unstable --unstable-hmr main.tsx`
> 
> `HMR triggered` log is never called, even if I modify main.tsx. And no explanation is given.

This is what I get when I run that file:
```
deno run --unstable-hmr foo.js
HMR Process started.
1
HMR Process finished. Restarting on file change...
```

Which is correct - your program has finished and JavaScript engine stopped execution. There's nothing to hot replace anymore. 

Which line are you changing in the second example?

**Comment by nestarz** [comment]
Ok, I understand for the first example. For the second example, I tried to replace for example the text in the console.log, or add something to the response.

**Comment by bartlomieju** [comment]
I'll try to dig into the other example later this week. If you change something at the top level you should get a reason for HMR not being possible because of top-level symbol change in ES module. But maybe there's a bug there after all?

**Comment by devsnek** [comment]
For modules, HMR generally only supports live patching of function bodies. Modifying code at the "top level" of the module will cause the process to restart.
