### ISSUE TITLE
`import.meta.resolve` for browsers

### ISSUE THREAD

**Issue by Reububble** [denoland/deno#21107]
It appears that there's no way to use `import.meta.resolve` unless `deno.window` is in `compilerOptions.lib`.

I'm writing client side code and using `DOM` and `ESNext` in `compilerOptions.lib`, and definitely won't want to include `deno.window`.

I understand that the properties of `import.meta` are technically not defined by ES but Deno allows `import.meta.url` in the same code, so I don't see why I wouldn't be able to use `import.meta.resolve` too.

**Comment by lucacasonato** [comment]
We should also add it to `lib.dom`.

**Comment by lucacasonato** [comment]
Opened an upstream issue: https://github.com/microsoft/TypeScript/issues/58828
