### ISSUE TITLE
`deno task` with `package.json` launches Node

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#21110]
```
$ deno run -A npm:create-next-app@latest next-app
$ cd next-app
$ cat '{ "unstable": ["byonm"] }' > deno.json
$ deno task dev
Task dev next dev
   ▲ Next.js 14.0.1
   - Local:        http://localhost:3000

 ✓ Ready in 2.2s
 ○ Compiling / ...
 ✓ Compiled / in 1284ms (232 modules)
```

This works because `./node_modules/.bin/next` has a shebang: `#!/usr/bin/env node` which launches Node interpreter. We should probably handle it in a way that overrides it and launches Deno instead.

**Comment by birkskyum** [comment]
It would be great to be able to overwrite use of node with deno. Bun has an opt-in called `bun --bun` which force use of bun instead of node, and it eventually will become default behavior. For deno having an opt-out to stop overwriting would arguably be the better choice, so the behaviour doesn't have to be flipped down the line.

**Comment by dsherret** [comment]
@bartlomieju I think it's actually launching deno nowadays?

**Comment by birkskyum** [comment]
It seems like it's using deno. I tried opening a standard express.js project with a package.json and no deno.jsonc, and it gives me this error which I'm quite sure wouldn't be hit if it was running with node.

```sh
➜ deno task start
Task start tsx ./src/app.ts
error: Uncaught (in promise) TypeError: Bn.WriteStream.prototype.hasColors is not a function
    at file:///Users/admin/repos/regenworks-backend/node_modules/.deno/tsx@4.7.2/node_modules/tsx/dist/cli.mjs:18:332

```

**Comment by dsherret** [comment]
Cool. Ref your issue https://github.com/denoland/deno/issues/20625 for that one.

**Comment by alexgleason** [comment]
I am still seeing the issue in postinstall scripts. I read through https://github.com/denoland/deno/issues/20609#issuecomment-2058180304 and set my CI to use `DENO_FUTURE=1` to build my vitepress project:

```yml
image: denoland/deno:1.45.5

stages:
  - build

build:
  stage: build
  variables:
    DENO_FUTURE: 1
  script:
    - deno i --allow-scripts
    - deno task build
    - rm -rf public
    - mv .vitepress/dist public
```

It results in this error:

```
Error launching 'node': No such file or directory (os error 2)
error: script 'postinstall' in 'vue-demi@0.14.7' failed with exit code 1
Cleaning up project directory and file based variables
00:01
ERROR: Job failed: exit code 1
```

Here's the full log: https://gitlab.com/soapbox-pub/nostrify-docs/-/jobs/7519436321

Without passing `--allow-scripts`, I get a [different error](https://gitlab.com/soapbox-pub/nostrify-docs/-/jobs/7519415763) which makes me think vitepress still cannot work in Deno without node.

**Comment by marvinhagemeister** [comment]
@alexgleason Can you open a new issue for that? The CI log you linked to failed at `deno i --allow-scripts` which is different from `deno task`. It's easier for us if we track things separate.

**Comment by felipecrs** [comment]
I'm "solving" this in my case with:

```
RUN echo '#!/usr/bin/env -S deno run --allow-all' | tee /usr/local/bin/node \
  && chmod +x /usr/local/bin/node
```
