### ISSUE TITLE
Snapshots: remove cli/js/40_testing.js and cli/js/40_jupyter.js from the snapshot

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#21136]
We have this awkward set up that `runtime/js/99_main.js` is imported in `cli/js/99_main.js` along with `cli/js/40_testing.js` and `cli/js/40_jupyter.js`.

This causes a lot of complication in the build setup where we first create a snapshot in "runtime/" crate, that is later used as a base for building a snapshot in "cli/" crate. After discussion with @crowlKats and @littledivy we decided that it makes little sense to include these two files in a snapshot given the complexity it entails.

Instead, these two files should be embedded in the binary (using `include_str!` macro) and execute when needed (`40_testing.js` for `deno bench`, `deno test`, `deno repl` and `deno jupyter` subcommands, while `40_jupyter.js` only for `deno jupyter` subcommand).

This will be the first step to unwinding and removing dedicated CLI snapshot. To do that we need to make some concessions, namely:
- [x] remove usage of "primordials" from `40_testing.js` 
- [x] assign `serializePermissions` and `setExitHandler` APIs to `internal` namespace
- [x] remove usage of `assert`

**Comment by lucacasonato** [comment]
Can't we still execute them as internal code somehow? It seems unfortunate to un-primordialize `Deno.test` specifically
