### ISSUE TITLE
Ability to support CheckJS

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#2114]
After #2089 lands, we will be able to add back support for "CheckJS".  This feature can solve a couple problems:

- It can statically analyse JavaScript code, leveraging JSDoc annotations, for any type violations without the code having to be authored in TypeScript.
- It can in many cases transpile other module formats (e.g. CommonJS) to ESM for use in Deno without needing other pre-processing.

**Comment by bartlomieju** [comment]
This issue was resolved in #2686
