### ISSUE TITLE
lsp doesn't respect deno.unstable

### ISSUE THREAD

**Issue by sigmaSd** [denoland/deno#21159]
This seems to be a recent regression, I don't get unstable types anymore

```ts
Deno.dlopen // type error here
```

settings.json
```json
{
    "deno.enable": true,
    "deno.lint": true,
    "deno.unstable": true,
}
```

deno 1.38.0

**Comment by irbull** [comment]
I pulled down the latest VSCode Extension and self hosted from source (commit https://github.com/denoland/vscode_deno/commit/5c13d5f6f55f72c032c0d02f8b2ba54808954d60) and it's not happening here. It's happening 3.26.0 too, so maybe it was fixed recently. I can't see a commit that explicitly calls this out though.

<img width="950" alt="Screenshot 2023-11-10 at 6 33 23 PM" src="https://github.com/denoland/deno/assets/196883/e3d3defa-554f-4ffa-9516-4426373483ee">

**Comment by irbull** [comment]
Sorry, I take that back. I can reproduce this with the latest from `main` as well. Seems that it happens as soon as you initialize the Deno Workspace. However, if you change the unstable setting to `false` and then change it back to `true` it works. Could be something in how the notification for the settings is propagated.

**Comment by bartlomieju** [comment]
CC @nayeemrmn please take a look

**Comment by irbull** [comment]
Small update, this appears to only happen if the VSCode plugin is not yet activated, and the act of initializing the workspace activates the plugin. By the time last call to: `extensionContext.client?.sendNotification("workspace/didChangeConfiguration",...);` is made, the settings have the correct values, so it _appears_ the VS Code Extension is setting and propagating things correctly. They're may be an timing issue between the plugin and the LSP Server on startup or maybe an cached setting in the LSP that's not being cleared.

I'd be happy to look into this further as I'm curious about the LSP Protocol; although I don't want to step on anyones toes. I'd have to try and self host an LSP Server too.

**Comment by nayeemrmn** [comment]
@sigmaSd 
1. Are you on vscode?
2. Do you have any files in your project which have `/// <reference no-default-lib="true" />`?

**Comment by nayeemrmn** [comment]
Oh, it looks like 3.27 had failed to publish
![image](https://github.com/denoland/deno/assets/29990554/f5c991c8-7f3a-4272-906b-538427d2adea)

Looking into it

**Comment by sigmaSd** [comment]
I had this issue in helix but I tried with vscode just to confirm, the issue is this
>Do you have any files in your project which have /// <reference no-default-lib="true" />?

Yes turns out that's the issue, its a bit surprising, since the file that have that is a nested folder inside the project and I didn't event open it, but I guess its because of the lsp preload

**Comment by nayeemrmn** [comment]
@sigmaSd In that case you need to add `/// <reference lib="deno.unstable" />` below that directive. We're working on better ways of partitioning type spaces in a project.

@irbull Is this also what's happening in your case? If not, please open a new issue thanks.

**Comment by dsherret** [comment]
Note that https://github.com/denoland/deno/issues/20420 might prevent `no-default-lib` from removing the types for the Deno global in the future
