### ISSUE TITLE
Dynamic import paths are not type checked

### ISSUE THREAD

**Issue by andrewthauer** [denoland/deno#21168]
Invalid dynamic import paths are not caught by either `deno check` or `deno compile`, and only fail at runtime. However, the Deno LSP indicates the path is not resolvable in the editor.

```typescript
// deno check and deno compile will raise an error
import { someFunc } from "../some_invalid_path.ts"; 

async function useDynamicImport() {
  // deno check / deno compile will not raise an error for this, but the LSP says
  // file path is not resolvable in editor
  const { someFunc } = await import("../some_invalid_path.ts");
  // ...
}
```

```
deno 1.38.1 (release, aarch64-apple-darwin)
v8 12.0.267.1
typescript 5.2.2
```

I want to say this used to work in previous versions, but I'm not 100% if it did or not.

**Comment by irbull** [comment]
I downgraded to Deno 1.21 (one of the first versions of Deno that supported `deno check`) and it's not failing there either.

I think import can take an arbitrary string, so I doubt `deno check` or `deno compile` could determine the validity in a general way. If it's a string constant, then I guess it could handle those cases.

**Comment by nayeemrmn** [comment]
This is intended -- we don't statically report module graph errors from dynamically imported modules because of when for example the file is intended to be written at runtime

**Comment by andrewthauer** [comment]
Deno compile is able to modules for valid paths into the executable for distribution + the LSP clearly knows there is an issue. Is there any other way to validate dynamic imports for correctness? It would be nice if there was some way of knowing if the code being imported is valid as part of a lint/test pass.

For context, I've been relying on dynamic imports as a pattern in a CLI to defer importing large chucks of code until a command is executed. This has proven to be quite effective at decreasing the overall startup time of the CLI as it avoids pulling in the entire module path of the CLI.

**Comment by andrewthauer** [comment]
For example is it possible to somehow programatically check for any `deno(no-local)` errors the LSP indicates. I thought this might be a lint rule, but I can't find it in https://lint.deno.land.

For example the LSP will show the following problem:

```
[{
	"resource": "/path/to/some_invalid_path.ts",
	"owner": "deno",
	"code": "no-local",
	"severity": 8,
	"message": "Unable to load a local module: file:///path/to/some_invalid_path.ts\n  Please check the file path.",
	"source": "deno",
	"startLineNumber": 123,
	"startColumn": 123,
	"endLineNumber": 123,
	"endColumn": 123
}]
```

**Comment by andrewthauer** [comment]
@nayeemrmn - Although I'm not proficient in rust, I had a look through the deno code to see how the LSP tracks this and it doesn't appear to be this is exposed in any way. Not sure about the compiler, etc. though.

I feel like there should be some way of validating dynamic imports statically even if it's not built into `deno check`, etc. I have node projects that use a similar pattern and the build process will catch these errors. Should I open a different issue related to this?
