### ISSUE TITLE
deno install - Panic installing when specifying non-existent relative root

### ISSUE THREAD

**Issue by ben-laird** [denoland/deno#21160]
# Panic from None Unwrap when Installing NPM Package as Script

Hello!

I'm using Deno for the first time in a simple parser script, and I wanted to set up [Biome JS](https://biomejs.dev) for extra code quality checks; I also wanted to see if their language server extension was good at all. I thought that the extension wouldn't work without a traditional installation of Biome, so I wanted to install the script with Deno so I didn't have to use a plethora of tools for the same thing, ironic I know considering Deno's capabilities. I'm trying to explore Rust and Deno in a practical application of wrangling my emails into something actually readable and storable in a database.

Thanks in advance for any help you could provide!

## Reproducing

1. Create a new Deno project via `deno init`
2. Replace/add `deno.json` with the following:

```json
{
  "tasks": {
    "dev": "deno run -A src/bin.ts",
    "check": "deno run -A npm:@biomejs/biome check src/**/*.ts"
  },
  "compilerOptions": {
    "strict": true
  }
}
```

3. Add `biome.json` with the following:

```json
{
  "$schema": "https://biomejs.dev/schemas/1.3.3/schema.json",
  "organizeImports": {
    "enabled": true
  },
  "linter": {
    "enabled": true,
    "rules": {
      "recommended": true
    }
  }
}
```

4. Run `deno install -A --name biome --root ./scripts nom:@biomejs/biome`

I have not created a GitHub repository yet, as the project is incredibly new and also contains other subprojects in a monorepo format.

## Backtrace

```sh
============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macOS aarch64
Version: 1.38.0
Args: ["deno", "install", "-A", "--name", "biome", "--root", "./scripts", "npm:@biomejs/biome"]

thread 'main' panicked at cli/util/fs.rs:209:43:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: core::option::Option<T>::unwrap
   4: deno::util::fs::canonicalize_path_maybe_not_exists
   5: deno::tools::installer::resolve_shim_data::{{closure}}
   6: deno::spawn_subcommand::{{closure}}
   7: <deno_unsync::task::MaskFutureAsSend<F> as core::future::future::Future>::poll
   8: tokio::runtime::task::raw::poll
   9: deno::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by dsherret** [comment]
As a temporary workaround, ensure the "scripts" folder exists.
