### ISSUE TITLE
.npmrc file

### ISSUE THREAD

**Issue by BSN4** [denoland/deno#21166]
right now there is no support for [.npmrc file](https://docs.npmjs.com/cli/v7/configuring-npm/npmrc#per-project-config-file)

**Comment by irbull** [comment]
Could be a dup of https://github.com/denoland/deno/issues/18616#issuecomment-1791308945

**Comment by dsherret** [comment]
Let's keep these two issues separate even though it's related.

FWIW, you can use an .npmrc file with the new unstable byonm feature ("bring your own node_modules"): https://deno.com/blog/v1.38#nodejs-compatibility-improvements

**Comment by BSN4** [comment]
@dsherret thanks, I didn't knew I could do that, it works now but I have new issue my imports are esm modules where files must end with `.js` even though the files are actually `.ts` extension , this is the way in `node` and `bun`

**Comment by dsherret** [comment]
npmrc support is in the latest version of Deno (1.44)
