### ISSUE TITLE
Why does deno limit executable names to start from lowercase letter?

### ISSUE THREAD

**Issue by bolatuly** [denoland/deno#21175]
This [regex](https://github.com/denoland/deno/blob/1ef617e8f3d48098e69e222b6eb6fe981aeca1c3/cli/tools/installer.rs#L34) limits executable names to start from lowercase letter.  What if i want to use a name which start with number? e.g. _3dupgrade_. This kind of bin name seems to be totally valid.

**Comment by bartlomieju** [comment]
That sounds reasonable, probably there was no concrete reason for that. PRs to change it are welcome!

**Comment by irbull** [comment]
I took a brief trip through the commit history to track where this restriction came from. (https://github.com/denoland/deno/commit/de5c099b47bd1d2e528f1a10179f130a02f26f86#diff-79aad3133d75ac3dbe31730db010639f4be5baac4132b2aae4b5be0bc1f30069R17). Nothing specific in the commit message or PR about this (https://github.com/denoland/deno/pull/3806). (January 2020).

The restriction says that the exe must start with a lowercase character and not contain whitespace. The whitespace makes sense. I'd be happy to put together a PR for this to allow for a numbers (like `3dupgrade`) and add a few test cases here too. What about uppercase characters as first characters? It seems like an odd restriction too. I could understand having no uppercase characters at all, as it probably limits cross platform problems. However, making such a change now may break existing users.
