### ISSUE TITLE
FFI dlopen() should use `LOAD_WITH_ALTERED_SEARCH_PATH` on Windows for absolute path

### ISSUE THREAD

**Issue by littledivy** [denoland/deno#21172]
Absolute path for shared libraries require a different search strategy on Windows. This example does not work without `LOAD_WITH_ALTERED_SEARCH_PATH` set:

```typescript
const { symbols } = dlopen('D:\a\deno_bindgen\deno_bindgen\e2e_test\target\debug\deno_bindgen_e2e.dll', {
 //. ..
});
```

**Comment by littledivy** [comment]
Instead of relying on dlopen2 to support these options, we should be using dlopen() and LoadLibrary() directly.

**Comment by codesculpture** [comment]
Where we need to set this LOAD_WITH_ALTERED_SEARCH_PATH, is this a flag or something ?? And also just letting u know that, dlopen accepts absolute path if it seperated with backslash we need to escape the slash to work (D:\\Deno\\some.dll) and also accepts if seperate with forward slash (without escaping ) (D:/Deno/some.dll) in windows

**Comment by gumpt** [comment]
Is anyone working on this? If not I'd like to take it.

**Comment by littledivy** [comment]
hey, sorry I misjuged the issue, as @codesculpture pointed out I was not using escaped backslash for the path. The resolution works fine, closing.
