### ISSUE TITLE
New test added to expectations.json is not discovered by wpt test runner

### ISSUE THREAD

**Issue by jamsinclair** [denoland/deno#21177]
I was trying to add the [html/semantics/embedded-content/the-canvas-element/imagedata.html](https://github.com/web-platform-tests/wpt/blob/360d99ddc756540791ed1e1e97df51fa950aa38d/html/semantics/embedded-content/the-canvas-element/imagedata.html) test while playing around with  #19288. I noticed when I added the wpt test it was not discovered by deno's test runner.

**Reproduction Steps:**
1. Checkout the forked branch https://github.com/denoland/deno/compare/main...jamsinclair:deno:wpt-image-data-test-issue
2. Run `./tools/wpt.ts setup` 
3. Run `./tools/wpt.ts run -- html/semantics/embedded-content/the-canvas-element` and observe no tests are found.

I might have a misconfiguration or be misunderstanding the setup, so if anyone can reproduce that would be a good first thing to check 🙇

**Comment by lucacasonato** [comment]
The test should be named `.any.html` for Deno to run it.

**Comment by jamsinclair** [comment]
Ah I see that now in the walk method's checks. It needs to end with `.any.html`, `.window.html`, `.worker.html` or `.worker-module.html` for it to run.

I'll close this as it seems to be expected.
