### ISSUE TITLE
deno compile - How to embed files in the executable? import.meta.url and Deno.mainModule are useless in this scenario

### ISSUE THREAD

**Issue by jmoalves** [denoland/deno#21173]
I am porting a utility I wrote to use `deno compile`.

However, I need to embed some config files inside the binary.
Or at least be able to read them aside from the binary file.

I've tried to use `import.meta.url` or `Deno.mainModule` to discover the binary location, trying to put the config files in the same directory as the binary.

But `deno compile` fixes these properties with the value discovered at compilation time (inside a GitHub action, in my case).

Do you have any clues?

I would appreciate any help.

**Comment by jmoalves** [comment]
This issue looks like https://github.com/denoland/deno/issues/18327.

However, discovering the binary location at runtime will be a good alternative.

**Comment by jmoalves** [comment]
Leaf is a workaround.
https://github.com/mandarineorg/leaf

But I prefer a native `deno compile` solution as it looks like a common scenario.

**Comment by dsherret** [comment]
There is no built in way at the moment. I'd recommend https://github.com/NfNitLoop/deno-embedder in the meantime

Duplicate of https://github.com/denoland/deno/issues/20885

**Comment by Leokuma** [comment]
> discovering the binary location at runtime will be a good alternative.
```ts
Deno.execPath()
```

**Comment by jmoalves** [comment]
> > discovering the binary location at runtime will be a good alternative.
> 
> ```ts
> Deno.execPath()
> ```

Thanks! 
I'm using this workaround as well

https://stackoverflow.com/questions/76647896/determine-if-running-uncompiled-ts-script-or-compiled-deno-executable
