### ISSUE TITLE
NPM Scoped packages make LSP to emit wrong errors when registered in importMap

### ISSUE THREAD

**Issue by sant123** [denoland/deno#21197]
Hi, consider this deno.json file

```json
{
  "imports": {
    "unocss": "https://esm.sh/@unocss/core@0.57.3",
    "unocssv2": "npm:@unocss/core@0.57.3"
  }
}
```

This code for LSP is fine:

```ts
import { UnoGenerator } from "unocss";

const uno = new UnoGenerator({
  rules: [
    ["m-1", { margin: "1px" }],
  ],
});

const { css } = await uno.generate(["m-1"]);

console.log(css);

```

And runs good

![image](https://github.com/denoland/deno/assets/7959437/265162ae-4f03-4363-ade5-d434ed5f36e9)

Now change the import from `unocss` to `unocssv2`:

![image](https://github.com/denoland/deno/assets/7959437/2fcd684b-bcaf-4a33-88bd-f4397a225c31)

But running the code works as expected.

Thanks!

**Comment by nayeemrmn** [comment]
I can't reproduce any issue, it works when you cache the dependency. Run `Deno: Cache Dependencies` in the command palette.

**Comment by sant123** [comment]
Unfortunately that does not work 😞 

[Screencast from 2023-11-14 00-22-16.webm](https://github.com/denoland/deno/assets/7959437/31982579-50f6-46a9-87b5-2a6dde92073f)

**Comment by nayeemrmn** [comment]
Hmm it works for me. Try restarting the LSP after that. If it doesn't work, I wonder what typings the module is getting then. You can check it like this:
```ts
import * as unocss from "unocssv2";

// Look at the autocomplete options after typing this:
unocss.
```

**Comment by sant123** [comment]
This is what I get:

![image](https://github.com/denoland/deno/assets/7959437/8d2e7743-90c2-4f60-8360-bb4bc57a054d)

**Comment by nayeemrmn** [comment]
After caching it I mean

**Comment by sant123** [comment]
I did it, I cached it but still get that error 😭

**Comment by nayeemrmn** [comment]
What does the extension output say after caching it? You can open it by clicking on the `Deno 1.38.1` on the bottom status bar.

**Comment by sant123** [comment]
![image](https://github.com/denoland/deno/assets/7959437/5472da2d-433a-4e52-be55-1767d2905ae6)

I don't get it 🤔

**Comment by sant123** [comment]
I think I have a reproducible example, create a new TS file and set this content:

```ts
import chalk from 'npm:chalk';
```

You will see both saying to cache their dependencies:

![image](https://github.com/denoland/deno/assets/7959437/936ce691-009e-433d-8a5b-3f4271982c0d)

Try to resolve them:

[Screencast from 2023-11-14 01-23-07.webm](https://github.com/denoland/deno/assets/7959437/2f7293c6-bcf7-4068-9071-9f840fafd664)

Now close and open again VS and magically the error disappears: 

![Screenshot from 2023-11-14 01-23-55](https://github.com/denoland/deno/assets/7959437/ef1289ad-4795-41fe-b73d-dd0be34ab582)

What I see is that while other files inside the Deno project have not resolved their dependencies, will affect others in there?

**Comment by nayeemrmn** [comment]
@sant123 Is this still an issue?

**Comment by sant123** [comment]
Not anymore, although it takes some time to resolve the modules; it works good.

https://github.com/denoland/deno/assets/7959437/345c9f82-31a3-4bc9-bb91-a3483978e537

Thank you @nayeemrmn !!!
