### ISSUE TITLE
Deprecation notices about Buffers

### ISSUE THREAD

**Issue by Danielduel** [denoland/deno#21193]
Deprecated `https://deno.land/api@v1.38.1?s=Deno.Buffer`
points to deprecated `https://deno.land/std@0.206.0/io/buffer.ts?s=Buffer`
In which you have a notice that you have to copypaste (please use links) into docs search Web Streams which is not a term in deno's documentation.
Then you look for it online, you find some random deno blog post that actually links MDN docs - in my opionion it (mdn docs) should've been linked in (both buffers) docs 👀

**Comment by iuioiua** [comment]
FYI, we merged https://github.com/denoland/deno_std/pull/3804 which takes care of the `deno_std` side of things. I'll do the runtime side of things soon.

**Comment by Danielduel** [comment]
Hello @iuioiua 
Let me be a QA here:

`Deno.Buffer` doesn't lead to Web Streams API.
`Buffer` from std/io has a malformed markdown link (it doesn't properly render).
