### ISSUE TITLE
Issue with imports

### ISSUE THREAD

**Issue by kakashi-69-xd** [denoland/deno#21202]
I'm having an error at runtime...
```sh
error: Uncaught ReferenceError: Cannot access 'IterTrait' before initialization
export class Skip<T> extends IterTrait<T> {
```

even though everything is fine there's no syntax error or missing import...

![Annotation 2023-11-14 222029.png](https://github.com/denoland/deno/assets/133514647/e54ec494-46bf-414f-9ae9-26b5a9f3a012)

**Comment by lucacasonato** [comment]
The `iter_trait.ts` file probably circularly references `skip.ts`?

**Comment by kakashi-69-xd** [comment]
> The `iter_trait.ts` file probably circularly references `skip.ts`? This error is occuring because of some circular modules in your module graph.

Yes you're right... Is there any way to solve this?

**Comment by kakashi-69-xd** [comment]
> The `iter_trait.ts` file probably circularly references `skip.ts`? This error is occuring because of some circular modules in your module graph.

> The `iter_trait.ts` file probably circularly references `skip.ts`? This error is occuring because of some circular modules in your module graph.

Yes you're right... Is there any way to solve this?
`IterTrait` has a method:
```ts
public skip(skip: number): Skip<T> {..}
```

**Comment by kakashi-69-xd** [comment]
> The `iter_trait.ts` file probably circularly references `skip.ts`? This error is occuring because of some circular modules in your module graph.

Yes you're right... Is there any way to solve this?
`IterTrait` has a method:
```ts
public skip(skip: number): Skip<T> {..}
```

**Comment by lucacasonato** [comment]
Put the two classes in the same file

**Comment by kakashi-69-xd** [comment]
> Put the two classes in the same file

I've already figured out something but thanks..
