### ISSUE TITLE
bug: `Deno.noColor` returns `true` in canary

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno#21207]
Yesterday, CI in the Standard Library for Deno canary [started failing](https://github.com/denoland/deno_std/actions/runs/6857682600/job/18647205432?pr=3796) because of failing tests in [std/fmt/colors_test.ts](https://github.com/denoland/deno_std/blob/main/fmt/colors_test.ts). After [some troubleshooting](https://github.com/denoland/deno_std/actions/runs/6871126465?pr=3802), it appears they're failing because `Deno.noColor` is now returning `true` for some reason. However, in stable, `Deno.noColor` returns `false`, and the tests pass fine.

I believe this behaviour was changed in either #20720 or #21191. This issue arose around the same time as these PRs being merged, and they both touch [ext/console/01_console.js](https://github.com/denoland/deno/blob/4913274a6508a5e5ad6c8babf2e90a4a84bf98ec/ext/console/01_console.js), which contains some of the code that implements `Deno.noColor`. However, the revert has not fixed the issue.

**Comment by bartlomieju** [comment]
CC @littledivy I think this might be related to lazy loading of this value?

**Comment by kt3k** [comment]
Maybe related to this issue, but `cli/tests/unit/tty_color_test.ts` doesn't seem passing in main.

```
$ deno test -A cli/tests/unit/tty_color_test.ts               
running 1 test from ./cli/tests/unit/tty_color_test.ts
noColorIfNotTty ... ok (26ms)

ok | 1 passed | 0 failed (27ms)

$ ./target/debug/deno test -A cli/tests/unit/tty_color_test.ts
running 1 test from ./cli/tests/unit/tty_color_test.ts
noColorIfNotTty ... FAILED (69ms)
...
```

**Comment by kt3k** [comment]
I think there was confusing between `noColor` for console log coloring and `Deno.noColor` variables in https://github.com/denoland/deno/pull/21164. It looks the former is based on NO_COLOR env var and terminal state of stdout, but the latter is only based on NO_COLOR env var. I'll work on the fix
