### ISSUE TITLE
__dirname / __filename Polyfill

### ISSUE THREAD

**Issue by zekth** [denoland/deno#2125]
Just an idea to facilitate migrations is to polyfill `__dirname` and `__filename`
`__dirname` can already be polyfilled by using `import.meta.url`

Edited like @rsp corrected

**Comment by rsp** [comment]
`Deno.cwd()` is like `process.cwd()` in Node, not like `__dirname`.
It prints the current working directory, not the directory where the script is in.

**Comment by zekth** [comment]
Right my test case was wrong but anyway the addition would be nice.

**Comment by rsp** [comment]
Using something like this will make the same output as Node:
```
const __filename = new URL(import.meta.url).pathname;
console.log(__filename);
```
but with Deno the modules doesn't have to have local filenames so it would work only if:
`new URL(import.meta.url).protocol === 'file:'`
In other cases you might want to leave the full URL.

**Comment by rsp** [comment]
@zekth inspired by this issue I wrote a simple polyfill and put it on GitHub:
- https://github.com/rsp/deno-dirname

You can use it as:
```
import { __ } from 'https://raw.githubusercontent.com/rsp/deno-dirname/master/mod.ts';
const { __filename, __dirname } = __(import.meta);

console.log(__dirname);
console.log(__filename);
```

**Comment by ry** [comment]
Seems like @rsp has the solution. Closing.

**Comment by balupton** [comment]
would be nice for this to be added to https://github.com/denoland/deno/blob/master/std/node/global.ts so that https://github.com/bevry/make-deno-edition can easily add support for __filename and __dirname

**Comment by JumpLink** [comment]
I have also [built a cross platform solution](https://github.com/JumpLink/cross-dirname) for `_dirname` and `__filename` which does not require `import.meta.url`.

I tested them in Node.js, Gjs, Deno and in the Browser.
