### ISSUE TITLE
Markdown Formatter breaks quote blocks

### ISSUE THREAD

**Issue by ngdangtu-vn** [denoland/deno#21285]
### Reproducing the Bug

The fmt misunderstand the syntax of quote block therefore it changes completely the style and meaning of the block.

```md
> - parent item
>   - child item
```

There was a similar issue in #20917 but that case can be fixed with `\`. This case, however is not possible.

Temporary solution for now is put on ignore comment, suggested by dsherret in the same above result. Yet I still prefer to have this case is treated as a special case.

### Expected Result

A nesting list inside quote block is what I expect.

```md
> - parent item
>   - child item
```

### Actual Result

First save:

```md
> - parent item
  > - child item
```

Second attempt:

```md
> - parent item
> - child item
```

### Additional Info

I used it in Deno vscode `v3.28.0`.

### Version

```
deno 1.38.2 (release, x86_64-unknown-linux-gnu)
v8 12.0.267.1
typescript 5.2.2
```

**Comment by justinlovinger** [comment]
Probably related, nested quote-blocks are squashed, so

```markdown
> Foo.
>
> > Bar.
```

becomes

```markdown
> Foo.
>
> Bar.
```
