### ISSUE TITLE
Add std version to Deno.version

### ISSUE THREAD

**Issue by suchislife801** [denoland/deno#21286]
**Is your feature request related to a problem? Please describe.**

Currently, Deno's API provides version details through `Deno.version` (https://deno.land/api@v1.38.2?s=Deno.version). However, this does not include version information from `https://deno.land/std/version.ts`, which can be crucial for developers to manage compatibility and dependencies accurately.

**Describe the solution you'd like**

I propose integrating the version information from `https://deno.land/std/version.ts` into the `Deno.version` API. This integration will provide a more comprehensive view of the Deno environment, including both the Deno runtime and standard library versions, aiding developers in troubleshooting and maintaining their applications.

**Describe alternatives you've considered**

An alternative is to continue using separate version details for the runtime and standard library. However, this approach can lead to confusion and potential inconsistencies when developers are required to cross-reference multiple sources for version information. Integrating these details into a single `Deno.version` API endpoint would streamline the process and reduce potential errors.

**Comment by kt3k** [comment]
@suchislife801 
TypeScript and V8 is embedded to CLI, but std is not. Also you can use any specific past version of std. It doesn't make much sense to me to add `std` version to `Deno.version`.

**Comment by dsherret** [comment]
There could be multiple std versions in the graph as well.
