### ISSUE TITLE
Deno has panicked. This is a bug in Deno. Please report this

### ISSUE THREAD

**Issue by drag0n-app** [denoland/deno#21293]
============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 1.38.2
run", "--allow-all", "--unstable", "/home/www/dist/main.js"]

thread 'main' panicked at ext/http/service.rs:255:5:
HTTP state error: Expected to be last strong reference
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by mmastrac** [comment]
Fixed by https://github.com/denoland/deno/pull/21252, also reported in https://github.com/denoland/deno/issues/21250

Will be fixed in 1.38.3. Thanks for the report!
