### ISSUE TITLE
integration tests affected by top level `deno.json`

### ISSUE THREAD

**Issue by scarf005** [denoland/deno#21311]
## Summary

config file outside repository (`deno.jsonc`) shouldn't affect result of integration tests, however it doesn't.
found while testing #21310.

## To reproduce

```sh
$ cargo test --features __runtime_js_sources integration::fmt
# ...
test result: ok. 22 passed; 0 failed; 0 ignored; 0 measured; 1420 filtered out; finished in 0.13s

$ cat ~/deno.jsonc 
{
  "fmt": { "semiColons": false, "proseWrap": "never" }
}

$ cargo test --features __runtime_js_sources integration::fmt
# ...
test result: FAILED. 14 passed; 8 failed; 0 ignored; 0 measured; 1420 filtered out; finished in 0.12s
```

**Comment by dsherret** [comment]
As mentioned here. This is expected: https://github.com/denoland/deno/pull/21312#pullrequestreview-1746728381

That said, it would be nice if there was a way of telling a developer working on Deno that they need to not have a deno.json in their cwd or ancestor directory.
