### ISSUE TITLE
Regression: Iterators (Map/Set) throw upon inspect

### ISSUE THREAD

**Issue by jeff-hykin** [denoland/deno#21352]
Looks like the regression occured somewhere between deno `1.33` (<-working) and `1.36`, and causes an error on latest (1.38.3)
This is on MacOS Monterey, M1:

<img width="925" alt="Screen Shot 2023-11-27 at 12 03 51 PM" src="https://github.com/denoland/deno/assets/17692058/aaf4ff8c-b912-4ee0-b89d-80a993d773ef">

Should look like:
<img width="608" alt="Screen Shot 2023-11-27 at 12 06 12 PM" src="https://github.com/denoland/deno/assets/17692058/6adbc19c-dc53-4d4f-aa75-9abf57b958c5">

**Comment by justjavac** [comment]
https://github.com/denoland/deno/blob/45fe3ccccfc2db9a969d2e6d258011ae96ee7d1e/ext/console/01_console.js#L1495-L1498

**Comment by crowlKats** [comment]
Fixed by #21370
