### ISSUE TITLE
node: `process.report` is missing

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/deno#21355]
Reported [on discord](https://discord.com/channels/684898665143206084/1178761408444371055/1178761408444371055):

> Earlier today I was happy because everything worked on my m1 macbook.
When I've returned home (arch) I got errors from latest deno...
(I am running deno on the metal, but I will provide a way to reproduce it with docker:)
> ```docer
> FROM denoland/deno:1.38.3
> 
> WORKDIR /app
> 
> RUN deno run --allow-read --allow-write --allow-env npm:create-vite-extra@latest vite-project --template deno-react
> 
> WORKDIR /app/vite-project
> RUN deno task build
> ```
> ```
> error: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getReport')
>     at isMusl (file:///app/vite-project/node_modules/.deno/rollup@4.6.0/node_modules/rollup/dist/native.js:5:30)
>     at getPackageBase (file:///app/vite-project/node_modules/.deno/rollup@4.6.0/node_modules/rollup/dist/native.js:53:28)
>     at Object.<anonymous> (file:///app/vite-project/node_modules/.deno/rollup@4.6.0/node_modules/rollup/dist/native.js:28:21)
>     at Object.<anonymous> (file:///app/vite-project/node_modules/.deno/rollup@4.6.0/node_modules/rollup/dist/native.js:81:4)
>     at Module._compile (node:module:733:34)
>     at Object.Module._extensions..js (node:module:747:10)
>     at Module.load (node:module:658:32)
>     at Function.Module._load (node:module:539:12)
>     at Module.require (node:module:677:19)
>     at require (node:module:791:16)
> ```

> (metal, interactive shell)
> 
> `import { join } from "node:path"`
> `join` works like expected
> 
> (rollup native.js uses `const { platform, arch, report } = require('node:process');`
> so in interactive shell I did `import { report } from "node:report"`
> report is `undefined`

**Comment by Danielduel** [comment]
I am the person who posted this on Discord and after seeing docs - I think... I could implement this.
Can I get this assigned to me? @marvinhagemeister

**Comment by bartlomieju** [comment]
Sure. Feel free to skip the harder bits for the first pass (eg. capturing native stack trace), I bet this will work again as soon as `report.getReport()` returns something.

**Comment by Danielduel** [comment]
Merged, latest main should be fixed.

**Comment by Danielduel** [comment]
@bartlomieju could you mark this one as resolved too?
