### ISSUE TITLE
automatic resource management for `Deno.dlopen`

### ISSUE THREAD

**Issue by kakashi-69-xd** [denoland/deno#21375]
impl `[Symbol.dispose]` for `Deno.DynamicLibrary<S>` so we can use easily with `using` keyword..

```ts
using lib=Deno.dlopen(...);

console.log(lib.symbols.sum(69,0));
//lib.close();
```

**Comment by aapoalas** [comment]
Thank you for the suggestion. I don't see why this couldn't be implemented but I'm wondering where you'd be using this: Do you have a use case where dynamic libraries are open and closed within a single function scope?

Usually I've seen dynamic libraries being opened and then used continually without end until the program itself halts.

**Comment by kakashi-69-xd** [comment]
> Thank you for the suggestion. I don't see why this couldn't be implemented but I'm wondering where you'd be using this: Do you have a use case where dynamic libraries are open and closed within a single function scope?
> 
> Usually I've seen dynamic libraries being opened and then used continually without end until the program itself halts.

Not a function scope but class
class holds a instance of the dylib and I'm not willing trust the user that he/she will always create an instance of that class using `using` keyword..
 # For Example
```ts
class XD {
  private lib;
  constructor() {
    using _lib=Deno.dlopen(...);// assume Symbol.dispatch is implemented..
    this.lib=_lib;//only passing a reference so ownership of the dylib is still held by _lib
  }
  ......
}

const xd=new XD();
await xd.spawn();

// lib is cleared here

``
