### ISSUE TITLE
Stabilize `Deno.upgradeHttp`?

### ISSUE THREAD

**Issue by imcotton** [denoland/deno#21384]
It was introduced on **1.20.1** / **2022.03.16** [^1], any stories left from moving it into stable?

Thanks.

[^1]: https://github.com/denoland/deno/blob/ae327d0a83be3ad56d42cad7db0b15ae8e853f06/Releases.md?plain=1#L2197

**Comment by crowlKats** [comment]
Since we have [`Deno.serve`](https://deno.land/api@v1.38.3?s=Deno.serve), whats the usecase you have for `Deno.upgradeHttp`?

**Comment by imcotton** [comment]
My [use case](caldera) is for standard **CONNECT** proxy server along with [Deno.listen](http) / [Deno.listenTls](https), learnt from #11744.

Haven't tried **Deno.serve** for the same task yet, not sure it's sufficient for this job tho.



[http]: https://deno.land/api@v1.38.3?s=Deno.listen
[https]: https://deno.land/api@v1.38.3?s=Deno.listenTls
[caldera]: https://github.com/stableness/caldera/blob/4f7fb4af43a490da1a7106a49f1cabab4d247191/mod.ts#L207

**Comment by mmastrac** [comment]
I looked into this briefly and I believe the `upgradeHttp` and `upgradeHttpRaw` API is not currently suitable for CONNECT. These are designed for use with websockets and node.js emulation as they assume an HTTP transaction is completed by whoever writes to the returned connection.

I think it is probably more suitable if we develop a `Deno.upgradeConnect` method that works for HTTP/1 and HTTP/2.

**Comment by mmastrac** [comment]
This API was never really designed for use with anything other than node.js compatibility, so we're likely just going to make it internal only.

Closing this in favour of a dedicated CONNECT API RFC -- please feel free to comment on it: #21870
