### ISSUE TITLE
bug: `deno doc --lint` reports missing explicit type for constants

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno#21404]
To reproduce, run `deno doc --lint https://deno.land/std/datetime/constants.ts`. Is this intentional?

**Comment by dsherret** [comment]
Yes, run:

```
deno doc https://deno.land/std@0.208.0/datetime/constants.ts
```

...and see how it's missing the types for that doc.

This is because it would be very complicated for deno doc to figure out the type in cases like this:

```ts
export const HOUR = MINUTE * 60;
```

The fix is to add an explicit `: number` type.

**Comment by iuioiua** [comment]
Fair enough. Thanks!
