### ISSUE TITLE
bug: `deno doc --lint` reports error when class constructor is missing JSDoc comment

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno#21405]
To reproduce, run `deno doc --lint https://deno.land/std/async/deadline.ts`. The following will be printed:
```
Missing JSDoc comment.
    at file:///Users/asher/GitHub/deno_std/async/deadline.ts:14:3
```
The line is the constructor for the `DeadlineError` class. Is this intentional?

**Comment by dsherret** [comment]
It's intentional, but debatable whether a jsdoc should be required for constructors.

**Comment by iuioiua** [comment]
If the class is documented, I think it's fine for the constructor not to be documented.
