### ISSUE TITLE
LSP debug logs should skip printing arguments?

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#21412]
I'm doubtful that print all arguments is very useful in the LSP - it's definitely not very useful for "op_load" which would print out whole contents of the file, which makes it hard to see other messages.

Given that "op_load" is 95% of all requests coming through the LSP, and most of the time it doesn't return anything (duration 0ms)  maybe we should make the output more concise for this particular request type.

**Comment by nayeemrmn** [comment]
Was this addressed by #21413?

**Comment by bartlomieju** [comment]
Yeah I think we can close it now.
