### ISSUE TITLE
%f should use parseFloat()

### ISSUE THREAD

**Issue by jcbhmr** [denoland/deno#21428]
if im not mistaken, this

https://github.com/denoland/deno/blob/a1d823e27d1b605b5658fddc1c9273667f0e9e84/ext/console/01_console.js#L3120-L3127

should be

```js
// Format as a floating point value.
const value = args[a++];
if (typeof value == "symbol") {
  formattedArg = "NaN";
} else {
  formattedArg = `${NumberParseFloat(value)}`;
}
```

according to the spec:

> 1.  If *specifier* is `%f`:
> 
>     1.  If [Type](https://tc39.github.io/ecma262/#sec-ecmascript-data-types-and-values)(*current*) is Symbol, let *converted* be `NaN`
> 
>     2.  Otherwise, let *converted* be the result of [Call](https://tc39.github.io/ecma262/#sec-call)([%parseFloat%](https://tc39.github.io/ecma262/#sec-parsefloat-string), **undefined**, « *current* »).

https://console.spec.whatwg.org/#formatter

example of bug:

```js
class Frac {
  constructor(num, den) {
    this.num = num
    this.den = den
  }
  [Symbol.toPrimitive]() {
    return this.num / this.den
  }
}
console.log("%f", new Frac(1, 2))
```

should print: `0.5`

In Chrome:

```js
class Frac {
  constructor(num, den) {
    this.num = num
    this.den = den
  }
  [Symbol.toPrimitive]() {
    return this.num / this.den
  }
}
console.log("%f", new Frac(1, 2))
VM382:10 0.5
```

Firefox:

```js
class Frac {
  constructor(num, den) {
    this.num = num
    this.den = den
  }…
0.500000
```
https://bugzilla.mozilla.org/show_bug.cgi?id=1846606

current Deno:
```js
jcbhmr@PIG-2016:~/Documents$ deno
Deno 1.38.3
exit using ctrl+d, ctrl+c, or close()
REPL is running with all permissions allowed.
To specify permissions, run `deno repl` with allow flags.
> class Frac {
  constructor(num, den) {
    this.num = num
    this.den = den
  }
  [Symbol.toPrimitive]() {
    return this.num / this.den
  }
}
> console.log("%f", new Frac(1, 2))
NaN
undefined
```

**Comment by nsh58** [comment]
May I work on it?
