### ISSUE TITLE
wrong behavior with extends URLSearchParams

### ISSUE THREAD

**Issue by Fenzland** [denoland/deno#2142]
# The code
```javascipt
class Foo extends URLSearchParams
{
    set( name, value, )
    {
        console.log( `setting ${name}`, );
        super.set( name, value, );
    }
    
    append( name, value, )
    {
        console.log( `appending ${name}`, );
        super.append( name, value, );
    }
}
new Foo().set( 'foo', 'bar', );
```

Run in browsers:
```bash
setting foo
```

Run in deno:
```bash
setting foo
appending foo
```

Step further, if we call `super.set` in Foo.prototype.append, nothing wrong in browsers, but a infinite loop caused in deno.

**Comment by zekth** [comment]
This seem really weird. How have you transpiled the ts code for the browser test? Using esnext?

**Comment by Fenzland** [comment]
@zekth Just run the raw code at F12 console.

I've tried with Chrome 73 and FireFox 66. Both don't call append, but deno does.

**Comment by Janpot** [comment]
Looks like `.append` [is called in `.set`](https://github.com/denoland/deno/blob/034e2cc02829c9244b32232074c7a48af827a2fb/js/url_search_params.ts#L151) when the property doesn't exist yet (`found === false`).
Should be solved by adding some sort of "internal" `._append` that is used by both `.set` and `.append`.
