### ISSUE TITLE
npm import works with `run` but not with `test`

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/deno#21461]
Version: Deno 1.38.4

Npm imports that work with `deno run` fail with `deno test`. It seems like the commands don't share the same resolution behaviour.

This only seems to happen when the entry test file has the `.ts` extension. When I convert it to `.js` it works too.

## Steps to reproduce

1. Create `deno.json` with contents:
  ```json
  {
    "imports": {
      "svelte":"npm:svelte@4.2.8",
      "svelte/":"npm:/svelte@4.2.8/"
    }
  }
  ```
2. Create file `foo.ts` with contents:
  ```ts
  import * as sv from "svelte/internal";
  console.log(sv);
  ```
3. Run `deno test -A foo.ts` -> Error

Error:

> error: Uncaught Error: Failed resolving package subpath './internal' for '/Users/marvinh/Library/Caches/deno/npm/registry.npmjs.org/svelte/4.2.8/package.json': ERR_INVALID_PACKAGE_TARGET] Invalid "exports" target {"default":"./src/runtime/internal/index.js"} defined for './internal' in the package config /Users/marvinh/Library/Caches/deno/npm/registry.npmjs.org/svelte/4.2.8/package.json imported from file:///Users/marvinh/dev/test/deno-import-internal/foo.ts; target must start with "./"

**Comment by marvinhagemeister** [comment]
A little more info: This seems about the `test` command per se, but rather about the difference that the `test` command runs type checking by default. The error is reproducible via `deno check foo.ts` in the provided reproduction as well.

**Comment by kt3k** [comment]
Looks like this is now resolved

```shellsession
$ cat deno.json
{
  "imports": {
    "svelte":"npm:svelte@4.2.8"
  }
}
$ cat a.js     
import * as sv from "svelte/internal";
console.log(typeof sv);
$ deno a.js    
object
$ deno test a.js 
------- pre-test output -------
object
----- pre-test output end -----
running 0 tests from ./a.js

ok | 0 passed | 0 failed (1ms)
```


```
