### ISSUE TITLE
`noImplicitAny` option still displays warnings in IDE (LSP issue?)

### ISSUE THREAD

**Issue by sobanieca** [denoland/deno#21505]
Version: Deno 1.38.5

I'm playing around with different approach to Typescript, where instead of using .ts files and compiling them, I use JSDoc comments. In this approach I don't want to define types for all components, but stick to old good Javascript for some smaller internal components. For this, I'm setting `noImplicitAny: false` in my `compilerOptions`. This works fine and `deno check` command doesn't complain about implicit `any` if it finds one. However, inside my editor (Neovim), I'm getting editor complaining/presenting warning that function parameters contain implicit `any`. This is distracting and I'm trying to get rid of it. It's possible that it's an issue with my Neovim configuration (can someone double check in VS Code or other?), but I'm suspecting that Deno LSP may not fully respect `noImplicitAny`. I've prepared repro code here: https://github.com/sobanieca/deno-implicit-any-warning

![Screenshot_20231207_231032_Termux](https://github.com/denoland/deno/assets/2606245/36b56faf-44fc-4c7d-94b6-c682c573c845)

**Comment by dsherret** [comment]
This is just how TypeScript is. You can see it in the TypeScript playground by hoving over `d` in this example where `noImplicitAny` is disabled:

https://www.typescriptlang.org/play?noImplicitAny=false#code/MYewdgzgLgBApgDwIYFsAOAbOMC8MAUAJgJS4B8MA3gLABQMMdAvkA

```
Parameter 'd' implicitly has an 'any' type, but a better type may be inferred from usage. (7044)
```

Once `noImplicitAny` is enabled, then the TS compiler gives the following error:

```
Parameter 'd' implicitly has an 'any' type. (7006)
```

**Comment by dsherret** [comment]
Right now Deno just forwards all warnings from TypeScript. Is there a way to suppress this warning (not error) when using TypeScript on its own? If so, then we should expose that in Deno if it's not already exposed. You may also want to look into whether there's a way to disable diagnostic code `7044` in your editor.

**Comment by sobanieca** [comment]
Thanks, yes it seems that I need to try to suppress it directly in my editor, which will work as long as I'm. AFAIK Typescript LSP doesn't allow to supress this kind of warnings (actually, they are 'suggestions' I think...).

I will close this issue then, since there is no way to setup Deno config to get rid of these warnings/suggestions.

**Comment by nhrones** [comment]
Have you tried:
```ts
{
  "compilerOptions": {
    "noImplicitAny": false
  }
}
```

**Comment by dsherret** [comment]
@nhrones have you read the text of this issue? 😉

**Comment by mogur** [comment]
In regards to the inability to setup Deno configuration to suppress warnings/suggestions 7044 or 7006 (when hovering over the three little dots under the first letter of a parameter) , is this a bug or by design?   It sure would be nice to toggle this off when using JS files in a Deno project.  

Has anyone found a fix or work-around other than setting  "deno.enabled" to false?

**Comment by sobanieca** [comment]
In my case - I don't have workaround. I still see those suggestions in editor...
