### ISSUE TITLE
node:http ServerResponse.flushHeaders is missing

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#21509]
Version: Deno 1.38.5

In `node:http` module the `ClientRequest.flushHeaders` method is misisng. It would be beneficial to go through https://nodejs.org/api/http.html and see what other APIs are missing.

This is a blocker for Next.js support.

**Comment by littledivy** [comment]
It's actually `ServerResponse.flushHeaders` missing for Next.js support
