### ISSUE TITLE
Throws exception for declared package.json import '#async_hooks' referencing `node:async_hooks`

### ISSUE THREAD

**Issue by JonathonRP** [denoland/deno#21501]
Version: Deno canary
Package.Json in node_modules declares a subpath with imports but deno throws exception.
this is for p-limit, #async-hooks.

**Comment by dsherret** [comment]
Could you provide a reproduction? We have tests for package.json imports so maybe there's something going wrong in your specific scenario.

**Comment by dsherret** [comment]
Ok thanks, I was able to reproduce with the following:

```
> cat example.ts
import pLimit from "npm:p-limit@5";
console.log(pLimit);
> deno run example.ts
error: Could not resolve '#async_hooks' from 'file:///V:/scratch/node_modules/.deno/p-limit@5.0.0/node_modules/p-limit/index.js'.

Caused by:
    could not find package 'async_hooks' from referrer 'file:///V:/scratch/node_modules/.deno/p-limit@5.0.0/node_modules/p-limit/package.json'.
```

Thanks for reporting! That said, in bug reports providing a reproduction can help reduce back and forth. I had no clue what `p-limit` was.

**Comment by Ayfri** [comment]
Any update ? This issue is really problematic for me.

**Comment by dsherret** [comment]
It will be in the patch release next week or `deno upgrade --canary` in a few hours.
