### ISSUE TITLE
Reintroduce WebGPU API

### ISSUE THREAD

**Issue by KnorpelSenf** [denoland/deno#21514]
The WebGPU API was removed "temporarily" for 1.32.0 in https://github.com/denoland/deno/pull/18094. We are stuck on version 1.31.3 of Deno until then.

What are your plans to reintroduce this feature? Is there anything that blocks you from adding WebGPU support again? It is an amazing feature and it enables a wealth of new applications that no other runtime offers.

**Comment by crowlKats** [comment]
I am literraly working on it, #20812. hopefully, if nothing goes wrong, the next release will have it (next week).

**Comment by KnorpelSenf** [comment]
Omg that is so awesome, holy moly

**Comment by KnorpelSenf** [comment]
I did not expect this lol, thanks!!!
