### ISSUE TITLE
Coverage HTML does not escape HTML entities

### ISSUE THREAD

**Issue by hildjj** [denoland/deno#21529]
Version: Deno 1.39.0 (pre)

I'm looking at  #21325 before it ships, and noticed that the Typescript source in the HTML output is not being escaped, which leads to some invalid-looking code, particularly with Typescript generics.

Example:

```ts
type Foo<B> = B[];
```

gets output as `type Foo = B[];` with everything after `Foo` in bold.

There is a TODO at https://github.com/denoland/deno/blob/393abed3873d83019feb5bcebb10a6929133862a/cli/tools/coverage/mod.rs#L921 that says:

which will probably fix this problem when it gets to-done, but syntax highlighting likely is not release-blocking.

Escaping SHOULD be release-blocking however.

It's probably enough to escape `"<"`to `"&lt;"` and `"&"` to `"&amp;"`.

**Comment by kt3k** [comment]
@hildjj Thanks for catching this!
