### ISSUE TITLE
Deno.createHttpClient fails to accept poolIdleTimeout parameter

### ISSUE THREAD

**Issue by sergeysolovev** [denoland/deno#21546]
Version: Deno 1.38.5

I expect this code to work without any issues

```
Deno.createHttpClient({
  // reqwest default is 90 seconds
  // lets try to change it to 60 seconds
  poolIdleTimeout: 60000,
});
```

But it crashes with the following error:

```
Uncaught TypeError: serde_v8 error: invalid type; expected: enum, got: Number
```

**Comment by raashidanwar** [comment]
Hey @bartlomieju,

Can I pick this up?

**Comment by littledivy** [comment]
@raashidanwar Sure!

**Comment by raashidanwar** [comment]
@littledivy please assign this issue to me.

**Comment by raashidanwar** [comment]
Hi @littledivy, raised fix PR: https://github.com/denoland/deno/pull/21603, please review.

**Comment by raashidanwar** [comment]
@bartlomieju can you please merge the PR?
