### ISSUE TITLE
Support for WebR (WASM R)

### ISSUE THREAD

**Issue by hrbrmstr** [denoland/deno#21573]
Version: Deno  1.39.0 (release, aarch64-apple-darwin)

My setup to try to work with WebR (https://docs.r-wasm.org/webr/latest/) in Deno uses this `deno.json` configuration:

```json
{  "imports": {    "webr": "npm:webr@^0.2.2"  }}
```

and this `test.ts`:

```javascript
import { WebR } from 'webr';

const webR = new WebR();
```

This is the backtrace that is generated:

```
Platform: macos aarch64
Version: 1.39.0
Args: ["deno", "run", "-A", "test.ts"]

thread 'main' panicked at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/deno_core-0.238.0/error.rs:132:7:
Custom error class must have a builder registered: Uncaught Error: Unable to build custom error for "Error"
  Maximum call stack size exceeded
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: deno_core::error::to_v8_error
   3: deno_node::ops::require::op_require_read_closest_package_json<P>::v8_fn_ptr
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

I do realize that V8's WASM support is not comprehensive, but this does work in Node (and, browsers)

**Comment by littledivy** [comment]
Cannot reproduce the panic. Does this still happen with 1.44.2?

**Comment by cbowdon** [comment]
In case it helps, the example works for me with 1.45.5 (aarch64-apple-darwin).

**Comment by marvinhagemeister** [comment]
Can confirm the panic is gone and running some snippets from https://docs.r-wasm.org/webr/latest/examples.html works as expected.
