### ISSUE TITLE
deno coverage html report importvements

### ISSUE THREAD

**Issue by sigmaSd** [denoland/deno#21582]
Version: Deno 1.39.0

- The contrast is week 
![image](https://github.com/denoland/deno/assets/22427111/793697ea-edf5-4773-98a4-f2a707065394)

- Needs some docs for the different symbols or a legend or maybe just a tool tip when the cursor is hovering it (like `I` `x40 x24`)

**Comment by kt3k** [comment]
@sigmaSd Do you suggest we should add some tooltip text at `x40` part?

**Comment by sigmaSd** [comment]
I still can tell what it means ?
Maybe just documenting it in deno.land is enough

**Comment by bartlomieju** [comment]
@kt3k seems like a tooltip for both `x40` and `I` could solve the issue

**Comment by kt3k** [comment]
`I` already has tooltip text:

<img width="386" alt="Screenshot 2023-12-18 at 19 50 31" src="https://github.com/denoland/deno/assets/613956/0c595c77-9722-4fe1-ada7-6cdd695fe4cb">

I'll add tooltip text to `xN` part
