### ISSUE TITLE
Writing to non-existent directories does not throw error

### ISSUE THREAD

**Issue by orsi** [denoland/deno#2159]
![image](https://user-images.githubusercontent.com/7156655/56459725-e406ac00-6365-11e9-8bb5-a53917bbb7b5.png)

Failing:
- makeTempDirSyncSuccess_permR0W1N0E0U0H0
- makeTempDirSuccess_permR0W1N0E0U0H0
- writeFileSyncFail_permR0W1N0E0U0H0

Tests expect an error to be thrown because of writing to a bad directory, but no error is thrown. This is on Windows 10, latest master - c8db224.

**Comment by zekth** [comment]
Could you provide your code please? I'll take a look at it.

**Comment by jorsi** [comment]
This was on master - c8db224 - with no code changes after running setup.py/build.py. These are standard tests from unit_tests.ts.

**Comment by zekth** [comment]
I used to have some flaky tests like this on my windows env, only on Unit Tests but the CI does not seem to be impacted. i'll do a couple runs to monitor this.

**Comment by jorsi** [comment]
I'll run them again later this evening with a more recent build and see if there's any change. I do know the tests were running perfectly a week or so ago though.

**Comment by bartlomieju** [comment]
@jorsi are you still experiencing this problem?

**Comment by jorsi** [comment]
Still failing on the same tests with most recent master @ ec9080

**Comment by zekth** [comment]
@jorsi could you try runing it in c:/temp for example and not in the USERS path? Also could you try using prompt with admin perm? i think it might be related.

**Comment by jorsi** [comment]
Just pulled and built up to 2edee33.

- running in Users dir - failed
- running in C:\temp - failed

Powershell is running in Administrator perms.

Output seems jumbled in some of these images:

--allow-read --allow-write 
utimeSyncNotFound
utimeNotFound
writeFileNotFound
linkSyncExists
linkSyncNotFound

![image](https://user-images.githubusercontent.com/7156655/57415110-e4f26700-71c8-11e9-8d88-c5cec5264acd.png)

--allow-write
makeTempDirSyncSuccess
makeTempDirSuccess
writeFileSyncFail

![image](https://user-images.githubusercontent.com/7156655/57415127-f0de2900-71c8-11e9-90e5-3a9da05e8c5e.png)

**Comment by lucacasonato** [comment]
@orsi Is this still failing?

**Comment by orsi** [comment]
I moved over to a macbook so I cannot confirm if this is still an issue :P

**Comment by nayeemrmn** [comment]
@orsi Can you give me a test case? I'll check.

**Comment by orsi** [comment]
There wasn't a lot to setup other than just running the tests on a Windows 10 laptop.

**Comment by nayeemrmn** [comment]
Okay it passes for me. Well, it always passed on CI so probably an environmental fluke. This can be be closed.
