### ISSUE TITLE
Testing in Deno 1.39 get stuck with Sharp

### ISSUE THREAD

**Issue by oscarotero** [denoland/deno#21601]
I have this code:

```js
import sharp from "npm:sharp@0.33.0";

Deno.test("testing", async () => {
  const content = Deno.readFileSync("./img.jpg");
  
  console.log(1);

  await sharp(content)
    .toBuffer();
  
  console.log(2);
  
  await sharp(content)
    .toBuffer();
  
  console.log(3);
});
```
Running with Deno v1.38.5 works fine. It outputs:

```
running 1 test from ./testing.ts
testing ...
------- output -------
1
2
3
----- output end -----
testing ... ok (133ms)

ok | 1 passed | 0 failed (136ms)
```

But in Deno 1.39.0:

```
running 1 test from ./testing.ts
testing ...
------- output -------
1
2
```

It get stuck in the second promise that never resolves. I think it's an issue in `Deno.test` because this same code executed out of `Deno.test` works fine in Deno 1.39.

**Comment by marcatatem** [comment]
I can confirm that it's _not only_ when using `deno test`, for example:

```typescript
const image = sharp(imageBuffer);
const stats = await image.stats(); // stuck with Deno 1.3.9
```

Never resolves with Deno 1.3.9.

**Comment by bartlomieju** [comment]
Most likely caused by https://github.com/denoland/deno/pull/21406. @mmastrac could you take a look at it?

**Comment by mmastrac** [comment]
From a quick `git bisect` with the following testcase, I believe this was introduced in 5ab7c702bb5d83c294f0e68fe751e3ee6283e0a7

```
import sharp from "npm:sharp";
try {
  await sharp(new TextEncoder().encode(atob('R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs='))).stats()
} catch {
  console.log("Expected error");
}
```
