### ISSUE TITLE
`confirm`, `alert` and `prompt` no longer respect quit signals since updating to Deno v1.39.0

### ISSUE THREAD

**Issue by toebeann** [denoland/deno#21602]
Version: Deno 1.39.0

I'm working on a CLI tool. The primary target for my CLI tool is presently macOS.

Ever since upgrading to deno 1.39.0 I have noticed that neither Ctrl+C nor Ctrl+D work to quit my CLI tool when the runtime is waiting for input at a `confirm`, `alert` or `prompt`. Instead, it merely skips the current prompt, leading to unexpected behaviour.

When downgrading back to deno 1.38.5 with `deno upgrade --version 1.38.5`, Ctrl+C and Ctrl+D immediately work as expected to quit my CLI from a built-in input prompt.

This seems to affect deno 1.39.0 on both Windows 11 and macOS Sonoma. I have not tested on other operating systems.

Steps to reproduce:
1. Run the following script in deno 1.39.0 on Windows or macOS and try to use Ctrl+C or Ctrl+D to quit the CLI at the prompt:
```js
while (true) {
  alert();
}
```
2. Get super frustrated that it is impossible to gracefully quit the CLI.

It also seems impossible to workaround this with `Deno.addSignalListener`:
```js
Deno.addSignalListener("SIGINT", Deno.exit); // Ctrl+C on Windows
if (Deno.build.os !== "windows") Deno.addSignalListener("SIGTERM", Deno.exit); // Ctrl+C on macOS

while (true) {
  prompt();
}
```
The above code still results in it being impossible to quit the CLI with Ctrl+C at a `confirm`, `alert` or `prompt` call.

The only way to workaround this I have found is with `prompt`; I can check for `null` and then quit, as Ctrl+C and Ctrl+D return `null` from `prompt` in v1.39.0. However, the `Esc` key now also returns `null`, and there's no way to discern the difference, and quitting the CLI from an `Esc` keypress is undesirable. And this still leaves the problem with it being impossible to quit the CLI from `alert` or `confirm` inputs.

Looking through [the release notes for 1.39.0](https://github.com/denoland/deno/releases/tag/v1.39.0), I have a feeling this new behaviour was introduced in https://github.com/denoland/deno/pull/18453.

I would personally consider this a breaking change for CLIs relying on the `confirm`, `prompt` or `alert` APIs, and if I want the old functionality I have to check the runtime Deno version and quit early with a message warning the user to downgrade to deno v1.38.5, or I need to consider migrating to a third-party input library, which is more complexity than I need for my simple CLI tool.

Thanks for your time.

**Comment by bartlomieju** [comment]
Caused by https://github.com/denoland/deno/commit/346d8127095f46bd5c58667f860521690ddd9cd7

**Comment by toebeann** [comment]
Thanks for getting this fixed 😃
