### ISSUE TITLE
Optional default to "npm" for package-like paths

### ISSUE THREAD

**Issue by malthe** [denoland/deno#21614]
While Deno supports importing packages from NPM, the [npm specifier](https://docs.deno.com/runtime/manual/node/npm_specifiers) is required, e.g.
```javascript
import { emojify } from "npm:node-emoji@2";
```
For source compatibility with Node, it would be convenient to allow the configuring of a default specifier, e.g. `--default-import-specifier npm` which would allow:
```javascript
import { emojify } from "node-emoji@2";
```
This would be fully compatible with the current import behavior since a package is neither a URI or a relative import path (names can't start with a period or a forward slash character).

**Comment by dsherret** [comment]
This is already possible with an import map:

```json
// deno.json
{
  "imports": {
    "node-emoji": "npm:node-emoji@2"
  }
}
```

Which allows you to do (recommended to store the version constraint just in the import map):

```
import { emojify } from "node-emoji";
```

Additionally, you can also use a package.json to accomplish the same thing.
