### ISSUE TITLE
Cannot import `@datastructures-js/priority-queue` from npm

### ISSUE THREAD

**Issue by chengr4** [denoland/deno#21627]
Version: Deno 1.37.2

When I tried to import instance by `npm:@datastructures-js/priority-queue`, it showed following error

```ts
import { MaxPriorityQueue } from "npm:@datastructures-js/priority-queue";
```

```
error: TS2305 [ERROR]: Module '"internal:///missing_dependency.d.ts"' has no exported member 'MaxPriorityQueue'.
import { MaxPriorityQueue } from "npm:@datastructures-js/priority-queue";
         ~~~~~~~~~~~~~~~~
    at file:///Users/chengr4/Devs/my-coding-QA/deno/heap/leetcode1887.ts:1:10
```

Here is the `index.d.ts` from the package: https://github.com/datastructures-js/priority-queue/blob/master/index.d.ts

```ts
import { PriorityQueue } from './src/priorityQueue';
import { MinPriorityQueue } from './src/minPriorityQueue';
import { MaxPriorityQueue } from './src/maxPriorityQueue';
import { ICompare, IGetCompareValue } from '@datastructures-js/heap';

export { PriorityQueue }
export { MinPriorityQueue }
export { MaxPriorityQueue }
export { ICompare }
export { IGetCompareValue }
```

Simultaneously, another `Queue` package from the same organization worked pretty fine.

Is this an issue from Deno or the package 🤔?

I try to find the solution but I am too bad..😓

---

Similar issue: #20854, #20231

**Comment by dsherret** [comment]
Works fine for me:

```shellsession
> cat main.ts
import { MaxPriorityQueue } from "npm:@datastructures-js/priority-queue";

console.log(MaxPriorityQueue);
> deno check --all main.ts
Check file:///V:/scratch/main.ts
> deno -V
deno 1.38.5
```

@chengr4 would you be able to provide a reproduction in the latest version of Deno? Do you have a lockfile or any other configuration?

**Comment by chengr4** [comment]
@dsherret OMG it works in ver 1.39.0

Sorry for wasting your time for testing

**Comment by dsherret** [comment]
That's ok. Glad it works now.
