### ISSUE TITLE
FFI: Allow invoking a function given it's pointer

### ISSUE THREAD

**Issue by vixalien** [denoland/deno#21636]
I don't even know if it's possible, but it would be nice to allow executing a C (or rust, etc..) function, given its pointer.

This is useful in some cases, but I believe it can be very unsafe.

**Comment by 0f-0b** [comment]
There is [`Deno.UnsafeFnPointer`](https://deno.land/api@v1.39.0?unstable&s=Deno.UnsafeFnPointer).

**Comment by vixalien** [comment]
Thanks!! This is precisely what I was looking for. Maybe the docs could use some love!!
