### ISSUE TITLE
node:crypto.pseudoRandomBytes function is missing

### ISSUE THREAD

**Issue by jacob-shuman** [denoland/deno#21632]
I'm currently trying to get the Slack Bolt js sdk running on Deno and have noticed that the `crypto.pseudoRandomBytes` is missing the actual implementation. This would be great to have added!

I also noticed this particular function is missing from the partial support list in the documentation: https://docs.deno.com/runtime/manual/node/compatibility.

**Comment by littledivy** [comment]
`pseudoRandomBytes` is a long deprecated in favour of `randomBytes` and should not be used. https://github.com/nodejs/node/pull/22519

**Comment by littledivy** [comment]
@jacob-shuman Can you share the stack trace? It would be useful to know which module is still using this API

**Comment by jacob-shuman** [comment]
> @jacob-shuman Can you share the stack trace? It would be useful to know which module is still using this API

Thank you for getting this added so quickly! I've tried setting bolt's log level to DEBUG but i'm not getting anything other than a single warning:

```bash
> deno --version && deno run --allow-env --allow-sys --allow-read --allow-net mod.ts

deno 1.39.0 (release, x86_64-apple-darwin)
v8 12.0.267.8
typescript 5.3.3
⚡️ Bolt app is running!
[WARN]   Parsing request body failed (error: TypeError: crypto.pseudoRandomBytes is not a function)
```
