### ISSUE TITLE
Latest changes to prompt() break Ctrl + C

### ISSUE THREAD

**Issue by uncenter** [denoland/deno#21631]
Version: Deno 1.39.0

I believe the [most recent change to the `prompt()` function](https://github.com/denoland/deno/commit/346d8127095f46bd5c58667f860521690ddd9cd7#diff-b75bdf1fea370fb05620f585464044855a0ce3addee67c341bcc18cc0f99d00c) is preventing me from using Control + C to exit the prompt while in a loop on macOS. I used to be able to do:

```ts
while (true) {
	prompt(">");
}
```

...and pressing Control + C would exit, but that no longer works. Is this intentional behavior?

**Comment by mmastrac** [comment]
Possibly caused by #18453

**Comment by mmastrac** [comment]
I believe this was intentional -- if you are looking to break out of the loop, you will need to check for a `null` return.

**Comment by bartlomieju** [comment]
Duplicate of https://github.com/denoland/deno/issues/21602, let's keep the discussion there.

**Comment by uncenter** [comment]
Ah sorry, don't know I missed that.
