### ISSUE TITLE
LSP injects imports to the `node_modules` folder rather than to the specifier in the import map

### ISSUE THREAD

**Issue by nicolo-ribaudo** [denoland/deno#21643]
I have an empty fresh project, and I replaced `preact` in `deno.json` to use `npm` rather than `esm.sh`:
```json
    "preact": "npm:preact@10.19.2",
    "preact/": "npm:/preact@10.19.2/",
```

When using the `JSX` type in a file, the auto-import is to `../node_modules/preact/src/index.d.ts` rather than `"preact"`.

**Comment by bartlomieju** [comment]
@nayeemrmn please take a look

**Comment by nayeemrmn** [comment]
This is fixed
