### ISSUE TITLE
Deno.HttpServer missing Symbol.dispose()

### ISSUE THREAD

**Issue by andykais** [denoland/deno#21659]
```
deno 1.39.0 (release, x86_64-unknown-linux-gnu)
v8 12.0.267.8
typescript 5.3.3
```

The Deno [1.38 blog post](https://deno.com/blog/v1.38#using-with-deno-apis) stated Explicit Resource Management was implemented for a number of deno apis, including `Deno.HttpServer`. However, the following snippet fails to run on deno v1.39.0.

repro:
```ts
// repro.ts
using server = Deno.serve(req => {
  return Response('hello world')
})
```

<details>
<summary>`deno run --unstable repro.ts` output:</summary>
<pre>
✅ Granted net access to "0.0.0.0:8000".
Listening on http://localhost:8000/
error: Uncaught (in promise) TypeError: Property [Symbol.dispose] is not a function.
Warning Couldn't format source line: Line 52 is out of bounds (source may have changed at runtime)
    at _using (file:///home/andrew/Code/scratchwork/deno-thumbnail-sqlite-benchmark/repro.ts:52:11)
    at file:///home/andrew/Code/scratchwork/deno-thumbnail-sqlite-benchmark/repro.ts:1:1
</pre>
</details>

<details>
<summary>`deno run --check --unstable repro.ts` output:</summary>
<pre>
Check file:///home/andrew/Code/scratchwork/deno-thumbnail-sqlite-benchmark/repro.ts
error: TS2850 [ERROR]: The initializer of a 'using' declaration must be either an object with a '[Symbol.dispose]()' method, or be 'null' or 'undefined'.
  Property '[Symbol.dispose]' is missing in type 'HttpServer' but required in type 'Disposable'.
using server = Deno.serve(req => {
               ^
    at file:///home/andrew/Code/scratchwork/deno-thumbnail-sqlite-benchmark/repro.ts:1:16

    '[Symbol.dispose]' is declared here.
        [Symbol.dispose](): void;
        ~~~~~~~~~~~~~~~~~~~~~~~~~
        at asset:///lib.esnext.disposable.d.ts:34:5

TS2348 [ERROR]: Value of type '{ new (body?: BodyInit | null | undefined, init?: ResponseInit | undefined): Response; readonly prototype: Response; json(data: unknown, init?: ResponseInit | undefined): Response; error(): Response; redirect(url: string | URL, status?: number | undefined): Response; }' is not callable. Did you mean to include 'new'?
  return Response('hello world')
         ~~~~~~~~~~~~~~~~~~~~~~~
    at file:///home/andrew/Code/scratchwork/deno-thumbnail-sqlite-benchmark/repro.ts:2:10

Found 2 errors.
</pre>
</details>

**Comment by andykais** [comment]
It should be noted that some deno apis do still implement explicit resource management. E.g. this example from the blog post still works on 1.39.0:
```ts
using kv = await Deno.openKv(":memory:");
const res = await kv.get(["a"]);
```

**Comment by mmastrac** [comment]
You need to use `await using` in this case:

```
await using server = Deno.serve(req => {
  return Response('hello world')
})
```

**Comment by andykais** [comment]
huh. I guess I missed the "AsyncDisposableStack" part of the proposal. Is there a good way to discover what objects implement which symbol (e.g. `Symbol.dispose` vs `Symbol.asyncDispose`)? I suppose thats probably a question upstream for the typescript repo. Thanks for helping me find this though!

**Comment by magurotuna** [comment]
> Is there a good way to discover what objects implement which symbol (e.g. Symbol.dispose vs Symbol.asyncDispose)?

The Deno's runtime API doc shows `implements Disposable` if the object you're looking at implements it. For instance, [`Deno.Kv` page](https://deno.land/api@v1.39.1?s=Deno.Kv&unstable=) looks like:

![Pasted_Image_2023_12_30_16_30](https://github.com/denoland/deno/assets/23649474/4896abd2-da8b-458b-9231-d74ebc363f4e)

and for [`Deno.HttpServer`](https://deno.land/api@v1.39.1?s=Deno.HttpServer):

![Pasted_Image_2023_12_30_16_32](https://github.com/denoland/deno/assets/23649474/08140037-c70c-4c1e-a3ab-36c86c1bb1d3)
