### ISSUE TITLE
`deno check` command doesn't respect `exclude` option in `deno.json(c)`

### ISSUE THREAD

**Issue by nokazn** [denoland/deno#21658]
Version: Deno 1.39.0 (release, x86_64-unknown-linux-gnu)
(Arch Linux on WSL)

## Summary

Even if `exclude` option is set in deno.json(c), `deno check` command attempts to check directories listed in `exclude` option.
I've created a minimum reproduction on https://github.com/nokazn/deno-mini-sample.

## Example

When directory structure is like below,

```
├- deno.json
└- ignored
    └- index.ts
```

and `deno.jsonc` and `ignored/index.ts` is like below,

```jsonc
// deno.jsonc
{
  "exclude": [
    "ignored"
  ]
}
```

```ts
// ignored/index.ts
export default  NotDefined
```

and then you run the following command.

```sh
deno check **/*.ts
```

## Expected behavior

`ignored/index.ts` is ignored, and no error is reported.

## Actual behavior

`ignored/index.ts` is checked, and an error is reported.

```sh
error: TS2552 [ERROR]: Cannot find name 'NotDefined'. Did you mean 'undefined'?
export default  NotDefined
                ~~~~~~~~~~
    at file:///home/nokazn/playgroud/deno-mini-sample/ignored/index.ts:1:17
```

## Appendix

The VSCode extension seems to work correctly with `exclude` option.

**Comment by dsherret** [comment]
What should be the output of the following in this scenario?

```shellsession
deno check ignored/index.ts
```

**Comment by nokazn** [comment]
@dsherret 

> 
> ```
> deno check ignored/index.ts
> ```

The above command seems to result in the same behavior.
`deno fmt` and `deno lint` work right, but `deno check` does not.

```sh
└❯ cat ignored/index.ts
export default  NotDefined

└❯ deno fmt ignored/index.ts
error: No target files found.

└❯ deno lint ignored/index.ts
error: No target files found.

└❯ deno check ignored/index.ts
Check file:///home/nokazn/playgroud/deno-mini-sample/ignored/index.ts
error: TS2552 [ERROR]: Cannot find name 'NotDefined'. Did you mean 'undefined'?
export default  NotDefined
                ~~~~~~~~~~
    at file:///home/nokazn/playgroud/deno-mini-sample/ignored/index.ts:1:17
```

**Comment by nokazn** [comment]
Can I try to work on this issue?
I am unfamiliar with Rust codebase, but able to take a look this weekend.

**Comment by dsherret** [comment]
@nokazn sure! Yeah, aligning with deno fmt/lint seems good.
