### ISSUE TITLE
Deno v1.39 lsp no longer works with lsp-mode in emacs 29.1

### ISSUE THREAD

**Issue by DinoChiesa** [denoland/deno#21650]
When I use 
deno 1.39.0 (release, x86_64-pc-windows-msvc)
v8 12.0.267.8
typescript 5.3.3

...I get no visual indication of lint problems or warnings in my simple JavaScript file.  I get the "breadcrumbs" thing at the top of the buffer, but unused variables and the use of the `var` keyword go unflagged. Also I get a warning in emacs: `Warning (lsp-mode): Unknown notification: deno/didUpgradeCheck` when first opening a JavaScript file in the editor.
![lsp-with-deno-v1 39 0](https://github.com/denoland/deno/assets/253266/74d120ae-44a5-4264-8822-13e0365bc59b)

Conversely, when I use
deno 1.36.3 (release, x86_64-pc-windows-msvc)
v8 11.6.189.12
typescript 5.1.6

...on the same machine, same emacs, same emacs init file, I get the visual indication of problems as expected.
![lsp-with-deno-v1 36 3](https://github.com/denoland/deno/assets/253266/acf205c3-4c34-429a-a010-5f6618e30c55)

...although I am not sure why the breadcrumbs at the top get yellow squigglies. 

Other details
- Windows 10 22H2
- GNU Emacs 29.1
- within emacs, lsp-mode-8.0.0
- I installed the different versions of deno via `choco install deno --version VERSION`. 
- I don't have a deno configuration file, or at least not an explicitly specified one. There may be a default configuration file, but I don't know where I would find that.
- brief logs from `lsp-workspace-show-log` (inside emacs) are attached.
- if I run `deno lint` from the command line, with either version, I see the expected warnings.
- the reason I tested v1.36.3 and not 1.37 or 1.38 is because there was a prior issue #21146 that reported that v1.37 and 1.38 also no longer work with emacs, and I think that issue wasn't presumptively closed without confirmation.
 
[lsp-log--with-deno-v1.36.3.txt](https://github.com/denoland/deno/files/13719682/lsp-log--with-deno-v1.36.3.txt)
[lsp-log--with-deno-v1.39.0.txt](https://github.com/denoland/deno/files/13719684/lsp-log--with-deno-v1.39.0.txt)
[deno-lint-cli-v1.39.0.txt](https://github.com/denoland/deno/files/13719784/deno-lint-cli-v1.39.0.txt)
[deno-lint-cli-v1.36.3.txt](https://github.com/denoland/deno/files/13719785/deno-lint-cli-v1.36.3.txt)

It would really be nice if 
- v1.39.0 just worked
- when it doesn't work, there is some additional transparency or diagnostic information available.

**Comment by DinoChiesa** [comment]
Maybe this is caused by #21609

**Comment by bartlomieju** [comment]
This appears to be a problem with Emacs, not Deno LSP. I don't understand why it would hard crash on unknown notification - AFAIK LSPs are free to add any notifications they want. 

> Maybe this is caused by https://github.com/denoland/deno/issues/21609

This is definitely not the problem, LSP doesn't use UDP in any capacity.

@nayeemrmn is there a workaround to disable this notification being sent?

**Comment by nayeemrmn** [comment]
I think the warning isn't doing anything, and the lack of lints is a separate issue. @DinoChiesa Can you show your workspace settings?

**Comment by DinoChiesa** [comment]
@nayeemrmn 
As I said in my original post, I don't have any workspace settings. or at least I have no explicitly specified settings. There may be a default configuration file, but I don't know where I would find that. I'm new to deno. As you can see, this is just a test JS file, there's no project. I just installed deno (`choco install deno`) and tried using it on a toy file. 

@bartlomieju
I didn't see evidence of "hard crash". The issue I wanted to report is the lack of lints; I mentioned the warning because it is co-incident with lack of lints. I don't see the warning with deno v1.36.3 .

**Comment by nayeemrmn** [comment]
@DinoChiesa You need to enable the extension by either explicitly specifying `:deno.enable t` in settings or having a `deno.json` in the root directory.

**Comment by DinoChiesa** [comment]
Thanks. Is that true for both v1.36.3 and for v1.39.0 ?

**Comment by nayeemrmn** [comment]
AFAIK we always required `"deno.enable": true` to enable the language server, but recently we added support for having a `deno.json` instead of that. Not sure why it worked without either before but the current behaviour is expected

**Comment by isamert** [comment]
Unfortunately starting deno lsp with  `enable: true` initialization option is not enough. Here is the problem (I'll use Emacs specific terms but you can follow):

- Assume that you have the following in your configuration:
```elisp
(add-to-list
 'eglot-server-programs
 '(typescript-ts-mode
   .
   ("deno" "lsp" :initializationOptions (:enable t))))
```
- Start `eglot` (the LSP client). With the configuration above, eglot sends the right `initializationOptions`.
- Deno LSP sends the right diagnostic data.
- Then eglot sends `workspace/didChangeConfiguration` signal.
- LSP sends `workspace/configuration` request.
- Eglot responds with `[null,null,null,null,null,null]`.
- Now Deno LSP thinks that it should disable Deno support.

I believe there is a mismatch here. I think eglot is doing the right thing as there is no workspace specific configuration it has. So it responds with null's. But I don't understand why deno lsp disables itself after seeing those null's. Maybe I don't understand what a workspace configuration means. I believe situation is similar in `lsp-mode` too.

Anyway, if you'd like to not have `deno.json` and have deno lsp run, you need the following in your .dir-locals.el:

```
((typescript-ts-mode . ((eglot-workspace-configuration . (:deno (:enable t))))))
```

@nayeemrmn What do you think? Is deno lsp's behaviour correct here?
