### ISSUE TITLE
Publish should exclude `node_modules`, `.git`, and any folder excluded in a deno.json

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#21672]
The publish command should ignore special folders like `node_modules` and `.git` as well as anything excluded in a deno.json

Probably it should also ignore from .gitignore

**Comment by muddlebee** [comment]
picking this up :eyes: I dont see anyone working on this yet

**Comment by dsherret** [comment]
Oh sorry, this was already done quite some time ago.

https://github.com/denoland/deno/blob/ef43d51497dec1298d2104701c9a222efae9d69f/cli/tools/registry/tar.rs#L56-L69

**Comment by muddlebee** [comment]
awesome. thank you
