### ISSUE TITLE
Deno does not support `transfer`, `transferToFixedLength` methods and `detached` property for ArrayBuffer

### ISSUE THREAD

**Issue by fwqaaq** [denoland/deno#21677]
Version: Deno latest

<img width="351" alt="image" src="https://github.com/denoland/deno/assets/82551626/b8fdb866-8c77-43c0-87f4-197a1d320392">

* MDN: <https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer/transfer>
* tc39: <https://tc39.es/proposal-arraybuffer-transfer/#sec-arraybuffer.prototype.transfer>

**Comment by littledivy** [comment]
All of these are prototype methods on ArrayBuffer, Deno (V8) supports them:

```
> ArrayBuffer.prototype.transfer
[Function: transfer]
> ArrayBuffer.prototype.transferToFixedLength
[Function: transferToFixedLength]

> const ab = new ArrayBuffer(10);
undefined
> ab.transfer()
ArrayBuffer {
  [Uint8Contents]: <00 00 00 00 00 00 00 00 00 00>,
  byteLength: 10
}
> ab.detached
true
```
