### ISSUE TITLE
Deno 1.39.1 still getting stuck with Sharp

### ISSUE THREAD

**Issue by oscarotero** [denoland/deno#21686]
This issue https://github.com/denoland/deno/issues/21601 is marked as fixed in Deno 1.39.1, but after upgrading Deno and testing again the same code:

```js
import sharp from "npm:sharp@0.33.0";

Deno.test("testing", async () => {
  const content = Deno.readFileSync("./img.jpg");
  console.log(1);

  await sharp(content)
    .toBuffer();
  console.log(2);
  
  await sharp(content)
    .toBuffer();
  console.log(3);
});
```

The second promise is never resolved:

```
deno test -A testing.ts
running 1 test from ./testing.ts
testing ...
------- output -------
1
2
```

Version: Deno 1.39.1 (macOS)

**Comment by marcatatem** [comment]
Confirming Oscar's findings. Works until Deno 1.38.5 then gets stuck indefinitely.

**Comment by bartlomieju** [comment]
Thanks, I'll look into that after holiday break.

**Comment by ni-max** [comment]
I believe this is related to https://github.com/denoland/deno/pull/21406

As I mentioned [here](https://github.com/prisma/prisma/issues/2452#issuecomment-1859089736) you could try just the commit before that.

**Comment by mmastrac** [comment]
@oscarotero This is on our radar right now. No timeline right this moment, but we hope to nail down what's going on here.

**Comment by oscarotero** [comment]
Thanks @mmastrac for the quick answer.
I hope it is easy to fix.

**Comment by marcatatem** [comment]
Following up of this; interestingly, with Deno > v1.40, the second promise in @oscarotero initial test gets resolved. If you add a third `await sharp(content).toBuffer();` though, the runner hangs and the promise never gets resolved.

To summarize, until v1.38.5, sharp works beautifully. After v1.38.5 and until v1.4.0, two successive calls to `toBuffer()` hang. After v1.4.0, two successive calls to `toBuffer()` work, but add a third and we're back to pre-v1.4.0 situation.

**Comment by mmastrac** [comment]
This should be fixed when we bump deno_core. :)

**Comment by oscarotero** [comment]
@mmastrac Thanks so much!

**Comment by mmastrac** [comment]
Confirmed that #23497 fixes this test:

```
import sharp from "npm:sharp@0.33.0";

Deno.test("testing", async () => {
  const content = Deno.readFileSync("./img.jpg");
  console.log(1);

  await sharp(content)
    .toBuffer();
  console.log(2);
  
  await sharp(content)
    .toBuffer();
  console.log(3);

  await sharp(content)
    .toBuffer();
  console.log(4);
});
```

```
# /tmp/deno test -A /tmp/test.ts 
Check file:///tmp/test.ts
running 1 test from ./tmp/test.ts
testing ...
------- output -------
1
2
3
4
----- output end -----
testing ... ok (27ms)

ok | 1 passed | 0 failed (37ms)
```
