### ISSUE TITLE
deno compile doesn't support `cjs`

### ISSUE THREAD

**Issue by sigmaSd** [denoland/deno#21683]
Version: Deno 1.39.1

a.ts
```ts
import Backend from "https://deno.land/x/i18next_fs_backend/index.js";
```

`deno compile a.ts`

error
```
error: unsupported media type Cjs for https://deno.land/x/i18next_fs_backend@v2.3.1/lib/fs.cjs
```

**Comment by dsherret** [comment]
That's expected. That deno.land/x module shouldn't be using .cjs files. You might want to import it from npm instead or submit a fix to that repo to not use cjs files:

```ts
import Backend from "npm:i18next-fs-backend@^2.3";
```

The current way that Deno treats CJS files as ESM with `deno run` is bad: https://github.com/denoland/deno/issues/17650
