### ISSUE TITLE
Embedding deno in rust

### ISSUE THREAD

**Issue by kakashi-69-xd** [denoland/deno#21692]
Can I embed the whole `deno` runtime in a rust app?.. not only `deno_core` which'll need all sorts of configurations like permission passing and things like command line arguments..

# NOTE: Making a build tool

**Comment by bartlomieju** [comment]
No, we do not ship `deno` as a library crate, only as a binary target. You can use parts of the runtime by pulling `deno_runtime` crate and IIRC there are some 3rd party forks that expose CLI as a library.4

**Comment by kakashi-69-xd** [comment]
> No, we do not ship `deno` as a library crate, only as a binary target. You can use parts of the runtime by pulling `deno_runtime` crate and IIRC there are some 3rd party forks that expose CLI as a library.

Can you name some of them?

**Comment by bartlomieju** [comment]
Probably this one is most up to date https://crates.io/crates/deno_cli_lib_windmill
