### ISSUE TITLE
`deno types` does not export `EventSource`

### ISSUE THREAD

**Issue by xnuk** [denoland/deno#21691]
May related: #14730

```sh
$ ./deno --version
deno 1.39.1 (release, x86_64-unknown-linux-gnu)
v8 12.0.267.8
typescript 5.3.3

$ ./deno types | grep EventSource -i   ## shows nothing

$ ./deno eval 'console.log(EventSource)'
[class EventSource extends EventTarget]
```

**Comment by bartlomieju** [comment]
CC @crowlKats

**Comment by lkwr** [comment]
The types are also not working with the vscode extension.

<img width="661" alt="Screenshot 2024-01-07 at 03 01 03" src="https://github.com/denoland/deno/assets/49527534/ff3e865e-efd1-4971-87ac-3e048ad97fe0">
