### ISSUE TITLE
Better error message when missing `--unstable`

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/deno#21712]
From [Discord](https://discord.com/channels/684898665143206084/991511118524715139/1189485907804430467)

> I run the command deno task build on a fresh project and i get the error
>  ```txt
>  error: Uncaught (in promise) TypeError: Deno.openKv is not a function
>  ```
>  I have like saas boilerplate the line
>  ```ts
>  export const kv = await Deno.openKv(path);
>  ```
>
> Why do i have this error ? 

We should print a hint that this is gated behind `--unstable` in the error message.

**Comment by bartlomieju** [comment]
We now provide hints for missing unstable APIs: https://deno.com/blog/v2.0-release-candidate#api-changes
