### ISSUE TITLE
Using web components in Deno with JSX

### ISSUE THREAD

**Issue by dkolba** [denoland/deno#21724]
Version: Deno 1.39.1

When using a 3rd party `<stop-watch>` web component (custom element), Deno/Typescript complains in VSCode with:
> Property 'stop-watch' does not exist on type 'JSX.IntrinsicElements'.deno-ts(2339)

Which is expected but would normally be mitigated in a regular Preact app by providing the needed type via Typescript Module Augmentation:

```
declare module "preact" {
  namespace JSX {
    interface IntrinsicElements {
      "stop-watch": StopWatchAttributes;
    }
  }
}

interface StopWatchAttributes extends preact.JSX.HTMLAttributes<HTMLElement> {
  kind?: string;
}
```

![Screenshot 2023-12-28 at 16 14 49](https://github.com/denoland/deno/assets/335483/5dc9fb7f-e472-494d-9193-474d800d87d5)

However, Deno (using Fresh as framework) will render a working web component but seems not to recognize the above and complains in VSCode with: 
> Invalid module name in augmentation, module 'preact' cannot be found.deno-ts(2664)

![Screenshot 2023-12-28 at 11 42 44](https://github.com/denoland/deno/assets/335483/0efcb893-2e45-4d90-95a3-937b8cf0d3bc)

Here is a minimal repro. containing both, a plain Preact version, which works as expected and a Deno/Fresh version, which renders but shows errors in VSCode: https://github.com/dkolba/deno-preact-webcomponent

**Comment by cdoremus** [comment]
I fixed your errors in this PR: https://github.com/dkolba/deno-preact-webcomponent/pull/2

I am also working on a blog post on the use of web components with Fresh using example code that can be found here: https://github.com/cdoremus/deno-fresh-webcomponents

**Comment by dkolba** [comment]
Works with @cdoremus fix (thx).
