### ISSUE TITLE
JSX errors in LSP in VSCode

### ISSUE THREAD

**Issue by jcpsimmons** [denoland/deno#21725]
Version:
```
deno 1.39.0 (release, aarch64-apple-darwin)
v8 12.0.267.8
typescript 5.3.3
```

This was already reported and solved in https://github.com/denoland/deno/issues/8993 but I am seeing it again.

<img width="593" alt="image" src="https://github.com/denoland/deno/assets/6600962/56ce9ffd-d156-48de-8a4e-cc7f1878e210">

I checked to see if it was just an issue with my project but I'm seeing it in others, https://github.com/LePichu/fs-routing-deno for example (open any file in the `routes` folder)

**Comment by bartlomieju** [comment]
This will be fixed by https://github.com/denoland/deno/pull/21687
