### ISSUE TITLE
ReadableStream.from not in documentation or types

### ISSUE THREAD

**Issue by mdekstrand** [denoland/deno#21733]
#19417 added the `ReadableStream.from` method, and various functions in `std` are marked as deprecated, but this method appears in neither the documentation nor the type definitions. It works, but code using it fails `deno check`.

**Comment by kt3k** [comment]
What is your deno version? Do you modify the type settings? `ReadableStream.from` is defined in https://github.com/dsherret/deno/blob/26cf06ed9f5c0ffa42afff3dbe29533ddcb2fbf7/ext/web/lib.deno_web.d.ts#L815-L817 and it should pass type check with `deno check` with the default type settings.

**Comment by mdekstrand** [comment]
I'm on Deno 1.39.1 with `lib` set to `deno.window`; if I remove the `lib` entirely from `deno.json`, it still fails to typecheck.

I do now see the `from` method displayed in the [type in the documentation](https://deno.land/api@v1.39.1?s=ReadableStream).

Here's the Deno error:

```
error: TS2339 [ERROR]: Property 'from' does not exist on type '{ new (underlyingSource: UnderlyingByteSource, strategy?: { highWaterMark?: number | undefined; } | undefined): ReadableStream<Uint8Array>; new <R = any>(underlyingSource: UnderlyingDefaultSource<...>, strategy?: QueuingStrategy<...> | undefined): ReadableStream<...>; new <R = any>(underlyingSource?: UnderlyingSourc...'.
let reader = ReadableStream.from(
                            ~~~~
    at file:///Users/michael/Documents/web/md.ekstrandom.net/tools/render.ts:43:29
```

However, when I try to create a minimal reproducing example, it does pass the typechecker, so it looks like something else is going on here. (Interestingly, my MRE typechecks with `deno check` at the CLI, but *not* in VSCode.)

<details>
<summary>Attempted MRE</summary>

```typescript
import { CsvStringifyStream } from "std/csv/mod.ts";

let perfOut = await Deno.open("build/performance.csv", {
  create: true,
  write: true,
  truncate: true,
});
let recOut = new CsvStringifyStream({
  columns: ["name", "startTime", "duration", "detail"],
});
let reader = ReadableStream.from(
  performance.getEntriesByType("measure") as unknown as Record<string, unknown>[],
);
await reader.pipeThrough(recOut).pipeThrough(new TextEncoderStream()).pipeTo(perfOut.writable);
```
</details>

**Comment by BlackAsLight** [comment]
While it does seem to have type checking for the `deno.window` lib. Try literally any other lib, like `deno.ns` and it no longer exists.
```ts
ReadableStream.from(example())

function* example() {

}
```
```
{
	"compilerOptions": {
		"lib": [
			"dom",
			"deno.ns"
		]
	}
}
```

**Comment by crowlKats** [comment]
Seems the `dom` library doesnt have the typings for `ReadableStream.from`: https://github.com/denoland/deno/blob/main/cli/tsc/dts/lib.dom.d.ts#L18507-L18512
