### ISSUE TITLE
TS: child field type is not recognized

### ISSUE THREAD

**Issue by matart15** [denoland/deno#21752]
Version: Deno 1.39.1

using VSCODE 

in this code
```ts
import Stripe from "https://esm.sh/stripe@14.10.0?target=deno";

...

  const subscriptions = await stripe.subscriptions.list({
    customer: customer.id,
  });

...
```

type of stripe is recognized as `Stripe` 
![Screenshot 2024-01-01 at 18 52 34](https://github.com/denoland/deno/assets/17027219/9a5424b7-d026-4241-8fab-f26a5d4ff42c)

but stripe.subscriptions is `any`
![Screenshot 2024-01-01 at 18 57 40](https://github.com/denoland/deno/assets/17027219/875ff340-f73f-4118-bbf5-d2f78145b8a8)

But if I `cmd + click` on `https://esm.sh/stripe@14.10.0?target=deno` there is `subsriptions` field with `Stripe.SubscriptionsResource` type.
![Screenshot 2024-01-01 at 18 58 31](https://github.com/denoland/deno/assets/17027219/67d15401-2940-403b-8af2-5876aff74e11)

Is this bug or is my setup is wrong?

**Comment by kt3k** [comment]
I'm not sure about `target=deno` option of `esm.sh`. Is that option absolutely necessary?

If I do the following, I could make VSCode recognize `.subscriptions` property.

```ts
import Stripe from "https://esm.sh/stripe@14.10.0";

const a: Stripe.Stripe = {} as any;

a.subscriptions.list();
```

<img width="694" alt="Screenshot 2024-01-01 at 20 21 48" src="https://github.com/denoland/deno/assets/613956/373bbbc0-da1d-40f1-a34e-1f4a906f8010">

**Comment by matart15** [comment]
@kt3k 
Thank you. It worked.

I copied `target=deno` part somewhere on internet. 

Without `target=deno` it gives me proper ts error for using namespace as type. 

![image](https://github.com/denoland/deno/assets/17027219/3e3e7d06-ca11-4444-86af-22ee316cc4fa)
