### ISSUE TITLE
`npm:signal-exit` package not working

### ISSUE THREAD

**Issue by littledivy** [denoland/deno#21757]
```js
import {onExit} from 'npm:signal-exit';

onExit(function (code, signal) {
  console.log('process exited!');
}, {alwaysLast: true});
```

This is used by `ora` (popular CLI spinner package) to restore terminal cursor.

```
$> deno run test.mjs
$> node test.mjs
process exited!
```

**Comment by satyarohith** [comment]
It looks like this TODO needs to be resolved to fix this issue: https://github.com/denoland/deno/blob/47dee65e4ad20847108d2f7e590c001ca9b93204/ext/node/polyfills/process.ts#L87-L90
