### ISSUE TITLE
LSP can't resolve import_maps in workspaces when using --unstable-workspaces

### ISSUE THREAD

**Issue by igl** [denoland/deno#21769]
Versions:
- Deno 1.39.1
- vscode_deno 3.31.0

**Description:**

When using vscode with the latest vscode_deno extension, the LSP can not resolve my import_map defined in the workspaces individual deno.json files. 

The Editor will show: `Relative import path "std/uuid/mod.ts" not prefixed with / or ./ or ../deno(import-prefix-missing)`
Executing the code using `deno run -A --unstable-workspaces src/api/main.ts` works as intended.

**Code for Repro:**  https://github.com/igl/deno-workspace-playground/tree/lsp-bug

**Screenshot:**
<img width="1270" alt="image" src="https://github.com/denoland/deno/assets/293519/2de85cdd-55ba-4b4a-a5ee-7745589767ab">

**Comment by bartlomieju** [comment]
@nayeemrmn is this something you could look at?

**Comment by Hajime-san** [comment]
The `--unstable-workspaces` flag removed, isn’t it?

#21891

**Comment by igl** [comment]
Just tested in 1.45.1 and it works! :D
