### ISSUE TITLE
Node compat crypto prime256v1 named curve not found

### ISSUE THREAD

**Issue by HadaIonut** [denoland/deno#21761]
Version: Deno 1.39.1

I am trying to get the node module `werift` working but i think i am having problems with the crypto symetric key generation.
The module throws (TypeError) Unsupported named curve when trying to execute:
```ts
import { generateKeyPairSync } from "node:crypto";

generateKeyPairSync("ec", {
  namedCurve: "prime256v1",
  publicKeyEncoding: {
    format: "der",
    type: "spki",
  },
  privateKeyEncoding: {
    format: "der",
    type: "pkcs8",
  },
});
```
This seems to work fine in node.

**Comment by iuioiua** [comment]
I'll have a crack at this one.

**Comment by iuioiua** [comment]
Once #22882 is merged, this issue will be blocked on `KeyObject.export()` not being implemented.

**Comment by lucacasonato** [comment]
This is working in the latest canary.

**Comment by studiowebux** [comment]
Hello @lucacasonato 

**Bundle**
 
```bash
deno 2.2.4 (stable, release, aarch64-apple-darwin)
v8 13.4.114.11-rusty
typescript 5.7.3
```

I am using `npm:@apple/app-store-server-library@1.5.0`

And I get this error when trying to verify an `appReceipt`:

```bash
error: Uncaught (in promise) Error: "alg" parameter "ES256" requires curve "prime256v1".
```

Was wondering if it is a regression ?
let me know if you need more details

And works ok with NodeJS v20.12.2
