### ISSUE TITLE
`deno run --env` fails when no `.env` file is present.

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/deno#21788]
In Fresh we recently switched from using std's `dotenv` module to Deno's `--env` in https://github.com/denoland/fresh/pull/2204 .  But we noticed that passing `--env` when no `.env` file is present will exit the current process with an error message.

```txt
error: Unable to load '.env' environment variable file
```

With the `dotenv` module it didn't error when no `.env` file was present.

## Steps to reproduce

1. Create a file `foo.ts` (can be empty)
2. Run `deno run -A --env foo.ts`

Version: Deno 1.39.1

**Comment by bartlomieju** [comment]
I think we did this on purpose when landing `--env` flag. @dsherret do you happen to remember this?

**Comment by dsherret** [comment]
Nope. I feel like it shouldn't error.

**Comment by iuioiua** [comment]
This was done on purpose. Should we instead print a gentle message saying that no `.env` file was detected?

https://github.com/denoland/deno/blob/aadcd640651383d606678928c10b637345b57beb/cli/args/mod.rs#L723-L727

**Comment by bartlomieju** [comment]
@iuioiua that makes sense. Any chance you could fix it and open a PR?
