### ISSUE TITLE
[node-compat] deduplicate same (exact) dependency

### ISSUE THREAD

**Issue by malthe** [denoland/deno#21799]
Version: Deno 1.39.1

If I have an NPM-dependency on `A` which has a dependency on `C`, and similar to `B` which _also_ depends on `C` – same exact version (or unspecified which is the same thing in this case) – it would seem that Deno loads `C` twice.

At least, that's what I am getting from trying to use the [Japa test runner](https://japa.dev/) in Deno (see [reported issue](https://github.com/japa/runner/issues/35) there).

Basically, in Japa, there's a main runner library which you import and invoke:
```typescript
import { configure, processCLIArgs, run } from '@japa/runner';

import { argv } from 'node:process';

processCLIArgs(argv.splice(2));

configure({
  files: ['tests/**/*.test.ts'],
});

run();
```

In addition, you can extend the `TestContext` class using plugins such as [@japa/assert](https://www.npmjs.com/package/@japa/assert). In Japa, each test gets such a test context instance.

The trouble is that in Deno, the plugins have no effect – presumably because the dependency to the test framework seen from @japa/assert is not the same as the test framework itself.

On the filesystem, the dependency appears as a symlink to the root `node_modules/.deno` folder, but I don't think this prevents Deno from loading a new copy of the dependency.

I believe this is perhaps intentional to some extent – but it breaks expectations in Japa and also, how does something like `instanceof` work for such symbols which are exported from different pathways?

**Comment by kt3k** [comment]
Can you try to set up `package.json` (with required dependencies), run `npm install`, and run it with `--unstable-byonm` flag? That gives more compatibility

**Comment by malthe** [comment]
This solved the issue!
