### ISSUE TITLE
node:fs incompatibility with readFile() breaks isomorphic-git

### ISSUE THREAD

**Issue by mdekstrand** [denoland/deno#21795]
Version: Deno 1.39.2

`isomorphic-git` takes an `fs` object as a parameter, and uses the function [`isPromiseFs()`](https://github.com/isomorphic-git/isomorphic-git/blob/main/src/models/FileSystem.js#L8) to determine whether an FS module supports a promise-based API. When run on Deno with `import * as fs from node:fs`, this fails: the `isPromiseFs()` function throws an exception which is caught by neither the `Promise.catch()` call or the surrounding try-catch block.

This can be reproduced in the REPL:

```js
import * as fs from "node:fs"
try {
    console.log('result: %o', fs.promises.readFile().catch((x) => x))
} catch (e) {
    console.log("error: %o", e);
}
```

I would expect this to either log the error with the console log message, or have it absorbed in the promise. Instead, executing that code in the repl results in:

```
result: Promise { <pending> }
undefined
Uncaught NotFound: No such file or directory (os error 2): readfile ''
    at async Object.readFile (ext:deno_fs/30_fs.js:719:18)
```

While calling `readFile()` without any arguments is odd and perhaps illegal, this throwing of an error that escapes both attempts to catch it also breaks expectations, and apparently isomorphic-git. I've reported isomorphic-git/isomorphic-git#1851 regarding possible workarounds, but I suspect an uncatchable error is more likely to actually be a bug in Deno.

**Comment by mdekstrand** [comment]
I've been doing a little more exploring, and this goes beyond just isomorphic-git's weird case.

This session demonstrates the problem:

```
> import { promises as fsp } from 'node:fs'
undefined
> let p = fsp.readFile('foo.txt')
undefined
Uncaught NotFound: No such file or directory (os error 2): readfile 'foo.txt'
    at async Object.readFile (ext:deno_fs/30_fs.js:771:18)
> p
Promise {
  <rejected> NotFound: No such file or directory (os error 2): readfile 'foo.txt'
    at async Object.readFile (ext:deno_fs/30_fs.js:771:18) {
    name: "NotFound",
    code: "ENOENT"
  }
}
```

When the Node Promise API encounters an error, it both returns the error in the promise (correct) *and* it gets flagged as an uncaught error (incorrect).

**Comment by mdekstrand** [comment]
This is not just a problem in the Node API — it looks like it affects the core Deno functions as well.

```
> let p = Deno.readFile('foo.txt')
undefined
Uncaught NotFound: No such file or directory (os error 2): readfile 'foo.txt'
    at async Object.readFile (ext:deno_fs/30_fs.js:771:18)
> p
Promise {
  <rejected> NotFound: No such file or directory (os error 2): readfile 'foo.txt'
    at async Object.readFile (ext:deno_fs/30_fs.js:771:18) {
    name: "NotFound",
    code: "ENOENT"
  }
}
>
```

And when I try to catch that error:

```
> let p2;
undefined
> try {
p2 = Deno.readFile('foo.txt')
} catch (e) {
console.log('error: %s', e)
}
Promise {
  <rejected> NotFound: No such file or directory (os error 2): readfile 'foo.txt'
    at async Object.readFile (ext:deno_fs/30_fs.js:771:18) {
    name: "NotFound",
    code: "ENOENT"
  }
}
Uncaught NotFound: No such file or directory (os error 2): readfile 'foo.txt'
    at async Object.readFile (ext:deno_fs/30_fs.js:771:18)
>
```

**Comment by mdekstrand** [comment]
Trying a few more versions to make better sense of what I'm seeing.

Returning correctly with Deno core:

```
> try {
console.log('result: %o', Deno.readFile('foo.txt').catch((e) => {
console.log('reject: %o', e);
return e;
}));
} catch (e) {
console.log('caught: %o', e);
}
result: Promise { <pending> }
reject: NotFound: No such file or directory (os error 2): readfile 'foo.txt'
    at async Object.readFile (ext:deno_fs/30_fs.js:771:18) {
  name: "NotFound",
  code: "ENOENT"
}
undefined
```

Catching with Node compat, also working with this code:

```
> import { promises as fsp } from 'node:fs'
undefined
> try {
console.log('result: %o', fsp.readFile('foo.txt').catch((e) => {
console.log('reject: %o', e);
return e;
}));
} catch (e) {
console.log('caught: %o', e);
}
result: Promise { <pending> }
reject: NotFound: No such file or directory (os error 2): readfile 'foo.txt'
    at async Object.readFile (ext:deno_fs/30_fs.js:771:18) {
  name: "NotFound",
  code: "ENOENT"
}
undefined
>
```

At this point, this has me mostly confused.

**Comment by kt3k** [comment]
Looks like this issue is specific to no argument call of `fs.promises.readFile`

The below works fine (the error is swallowed as expected):
```js
import * as fs from "node:fs";
fs.promises.readFile(undefined).catch((e) => {});
```

But the below terminates with uncaught (the error is not unhadled):
```js
import * as fs from "node:fs";
fs.promises.readFile().catch((e) => {});
```

**Comment by kt3k** [comment]
Because we use `promisify(readFile)` for defining `fs.promises.readFile`, `fs.promises.readFile()` call seems to be mapped to `fs.readFile(callback)` internally, which causes invalid `fs.readFile` call without `callback` parameter (and we can't catch that error).

Node.js doesn't use `promisify` for defining these promise utils, but uses bespoke utils for `fs.promises` https://github.com/nodejs/node/blob/aef9d4ea7ba6fd683b3f0f10007cbd3da954812a/lib/internal/fs/promises.js#L1234

**Comment by kt3k** [comment]
@mdekstrand Thanks, but I already started working on it. Also thanks for sending a fix to isomorphic-git!

**Comment by mdekstrand** [comment]
@kt3k Thanks!
