### ISSUE TITLE
[node-compat] `process.stdin.unref` should warn instead of throwing unreachable

### ISSUE THREAD

**Issue by brc-dd** [denoland/deno#21796]
Example code:

```ts
import process from 'node:process'
import readline from 'node:readline'

const input = readline.createInterface({
  input: process.stdin
})

process.stdin.unref()
```

In node, this immediately exits the process. In deno, it throws:

```
error: Uncaught (in promise) NodeCompatAssertionError: unreachable
    at unreachable (ext:deno_node/_util/asserts.ts:16:9)
    at TTY.unref (ext:deno_node/internal_binding/handle_wrap.ts:41:5)
    at ReadStream.unref (node:net:643:20)
```

I believe this is currently not supported, but it should just `warnNotImplemented` instead of throwing?

Corresponding Node docs - https://nodejs.org/api/readline.html#readlinecreateinterfaceoptions (Also here in polyfill comments:)

https://github.com/denoland/deno/blob/aadcd640651383d606678928c10b637345b57beb/ext/node/polyfills/_readline.d.ts#L350-L358

Version:

```
deno 1.39.1 (release, aarch64-apple-darwin)
v8 12.0.267.8
typescript 5.3.3
```

**Comment by kt3k** [comment]
Sounds reasonable to me. Can you send a PR?
