### ISSUE TITLE
Implement `crypto.diffieHellman()`

### ISSUE THREAD

**Issue by littledivy** [denoland/deno#21806]

**Comment by iuioiua** [comment]
I'll aim to have this done for 1.41.

**Comment by birkskyum** [comment]
Maybe https://crates.io/crates/x25519-dalek could be helpful here?

**Comment by birkskyum** [comment]
@littledivy is this and  #13451 resolved after #24463  ?

**Comment by iuioiua** [comment]
Completed in #24463.

**Comment by birkskyum** [comment]
Related to:
- https://github.com/denoland/deno/pull/24938
