### ISSUE TITLE
Implement `Cipheriv.setAutoPadding`

### ISSUE THREAD

**Issue by littledivy** [denoland/deno#21804]
https://github.com/denoland/deno/issues/18455#issuecomment-1789444851

@mllnd stumbled upon missing method when using `npm:ethereum-cryptography`.
https://github.com/ethereum/js-ethereum-cryptography/blob/cbb283febc4641bf1c5c365a2a16037032f2d23e/src/aes.ts#L69-L71
  ```
  Error: Not implemented: crypto.Cipheriv.prototype.setAutoPadding
      at notImplemented (ext:deno_node/_utils.ts:9:11)
      at Cipheriv.setAutoPadding (ext:deno_node/internal/crypto/cipher.ts:46:9)
  ```

**Comment by barthuijgen** [comment]
This method is definitely not just used by crypto libraries. I've had a project that I needed to implement a specific decryption logic to work with a 3rd party and this method was needed, so I was forced to switch to nodejs.

I couldn't find any other way to implement this in Deno either, the web subtle crypto api that Deno uses has no support for this.

Please prioritize the issue! 🙏

**Comment by littledivy** [comment]
Rough outline on how to implement this:

- Add a `autoPadding: boolean = true` default field to the class Cipher in `ext/node/polyfills/internal/crypto/cipher.ts`.
- During `final()`, pass this flag to Rust.
- https://github.com/denoland/deno/blob/3f4639c330a31741b0efda2f93ebbb833f4f95bc/ext/node/ops/crypto/cipher.rs#L212
When auto padding is disabled, divide final data into blocks of cipher's block size and call [encrypt_blocks_b2b_mut](https://docs.rs/cipher/latest/cipher/trait.BlockEncryptMut.html#method.encrypt_blocks_b2b_mut).

Similar logic can be applied for `Decipher`
