### ISSUE TITLE
Unable to run a compiled binary when using the Deno.Kv feature

### ISSUE THREAD

**Issue by DeeGeeMan** [denoland/deno#21814]
Version: Deno 1.39.2

## File `demo.ts`:
```
const client = await Deno.openKv("demo.db")

await client.set(["settings"], { type: "deno" })
```

## Compile:
```
deno compile --allow-env --allow-read --allow-net --allow-write --unstable-kv --unstable-cron ./demo.ts
```

## Run:
```
./demo 
```

## Error:
```
error: Uncaught (in promise) TypeError: Deno.openKv is not a function
const client = await Deno.openKv("demo.db");
                          ^
    at file:///.../demo.ts:1:27
```

_Note: if I use `--unstable` instead of `--unstable-kv` and  `--unstable-cron`, it works (see example below)..._

## Example:
```
deno compile --allow-env --allow-read --allow-net --allow-write --unstable ./demo.ts
```

## [unstable](https://docs.deno.com/runtime/manual/tools/unstable_flags#--unstable)
<img width="816" alt="image" src="https://github.com/denoland/deno/assets/21670040/564cb16e-1162-459e-a5d1-6ae472f4abe8">

**Comment by bartlomieju** [comment]
Granular unstable features are not threaded through the "standalone binary" system correctly. I will fix it.
