### ISSUE TITLE
core: Clean up return type of Dispatch function

### ISSUE THREAD

**Issue by ry** [denoland/deno#2182]
Rather than returning a `(bool, Box<dyn Future<Item = Buf, Error = ()> + Send>)` from the dispatch function, I think we should make the async/sync split into an enum

```rust
enum Op {
  Sync(Buf),
  Async(Box<dyn Future<Item = Buf, Error = ()> + Send>),
}
```
That is, you either get the response immediately, or you get a future. Currently we return a future that evaluates synchronously - which a little odd.

**Comment by bartlomieju** [comment]
Done in #2255
