### ISSUE TITLE
Doc for `deno run --import-map` does not exist

### ISSUE THREAD

**Issue by stevencrader** [denoland/deno#21822]
The help for `deno run --help` lists a link to the `--import-map` argument that doesn't exist.

I created a matching Bug in the doc repo: https://github.com/denoland/deno-docs/issues/260

```
--import-map <FILE>
    Load import map file from local file or remote URL.
    Docs: https://deno.land/manual@v1.39.2/linking_to_external_code/import_maps
    Specification: https://wicg.github.io/import-maps/
    Examples: https://github.com/WICG/import-maps#the-import-map
```

Version:

```
deno 1.39.2 (release, x86_64-unknown-linux-gnu)
v8 12.0.267.8
typescript 5.3.3
```

**Comment by dsherret** [comment]
Can you show an example of not working? Here's an example of it working:

```shellsession
> cat import_map.json
{
  "imports": {
    "example": "https://deno.land/x/dax/mod.ts"
  }
}
> cat mod.ts
import $ from "example";
console.log($.path(".").resolve());
> deno run --import-map import_map.json mod.ts
✅ Granted read access to <CWD>.
PathRef("V:\scratch")
```

Make sure to specify the `--import-map` argument before the script argument (ex. `mod.ts` in the example above).

**Comment by stevencrader** [comment]
Sorry. I wasn't clear enough. The Docs URL doesn't exist. Try to load https://deno.land/manual@v1.39.2/linking_to_external_code/import_maps in the browser.

**Comment by stevencrader** [comment]
I guess once the docs are updated, the URL should be updated too (unless the docs uses a redirect).

**Comment by dsherret** [comment]
Ah, ok sorry I misread the first sentence.
