### ISSUE TITLE
Syntax error with valid JS code

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/deno#21836]
## Steps to reproduce

Run this code

```ts
import Plotly from "npm:plotly.js-dist@2.27.1"
console.log(Plotly)
```

Error:

```sh
Uncaught SyntaxError: Invalid or unexpected token at file:///Users/marvinh/Library/Caches/deno/npm/registry.npmjs.org/plotly.js-dist/2.27.1/plotly.js:245:14
```

Looks like something breaks in SWC

Version: Deno 1.39.1

**Comment by marvinhagemeister** [comment]
I managed to narrow it down to a small [reproduction case](https://github.com/marvinhagemeister/deno-cjs2)

Steps to reproduce:

1. Clone https://github.com/marvinhagemeister/deno-cjs2
2. Run `deno run -A main.ts`

Error:

```txt
error: Uncaught SyntaxError: Invalid or unexpected token
```

The heart of the issue is a commonjs export which starts with a number.

```js
module.exports = {
  "123_foo": "it works"
}
```

We seem to try to convert this module to an ESM module somewhere but fail to check if the object key would be a valid JS identifier. JS identifiers must not start with a number at which point we run into a syntax error.

**Comment by bartlomieju** [comment]
Good find, I think we should see what Node.js does in translation cases like this and adjust accordingly.

**Comment by marvinhagemeister** [comment]
Can confirm that we apply an invalid transform.

```ts
// input
module.exports = {
  "3d": "it works"
}

// output
import {createRequire as __internalCreateRequire} from "node:module";
const require = __internalCreateRequire(import.meta.url);
const mod = require("/Users/marvinh/dev/test/deno-cjs2/node_modules/foo/index.js");
export const 3d = mod["3d"];
export default mod;
```

**Comment by marvinhagemeister** [comment]
Looks like node prints a warning when a cjs export cannot be turned into an esm export:

```txt
SyntaxError: Named export '3d' not found. The requested module 'foo' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'foo';
```

**Comment by dsherret** [comment]
@marvinhagemeister fix just needs to be done here:

https://github.com/denoland/deno/blob/43d2ecd4f056bf38fe5f5656e550061c68c717f0/ext/node/analyze.rs#L393-L398

**Comment by marvinhagemeister** [comment]
@dsherret Neat! For some reason I completely missed that function and was working on my own. We're skipping a bunch of admittedly very rare cases in our validation logic, but it should be fine.

**Comment by dsherret** [comment]
Yeah, that function is purposefully greedy for simplicitly because in this case false positives aren't a big deal.
