### ISSUE TITLE
feature-request: Expose the same API in node.js

### ISSUE THREAD

**Issue by WillAvudim** [denoland/deno#2184]
Would it be possible to get access to exactly the same API in Node.js?

I found the API surface overall to be exquisitely neatly designed, and I like it a lot. I'd like to be able to seamlessly switch between Deno and Node.js without memorizing strikingly different OS/file APIs.

**Comment by GrosSacASac** [comment]
That is a non goal

from https://deno.land/manual.html#introduction
> Non-goals
> 
>     Not explicitly compatible with Node.

**Comment by zekth** [comment]
Some polyfills are available as third-party modules but it will not be implementend in `deno` or `deno_std`.

**Comment by ry** [comment]
As @zekth suggests, we could have an API in deno_std that acts as a polyfill. Something like this:
```js
import { readFileSync } from "https://deno.land/std/node/fs"
```

**Comment by zekth** [comment]
Having it in `deno_std` is not good for me. I'd better create an official polyfill repo, like `deno_polyfills`

**Comment by WillAvudim** [comment]
Thank you for not killing this proposal outright on spot :-)

Node.js API surface is enormous with lots of legacy pre-async-await artifacts. Bringing it into Deno is indeed undesirable. If we could bring Deno API to Node.js, one way or another, it would make way to write libraries that support both Deno and Node.js.

**Comment by zekth** [comment]
The only thing we need to focus on is the CI checking the polyfills on different versions of node. That's my concern about adding it to `deno_std`

**Comment by kevinkassimo** [comment]
I agree that we might want to dedicate another repo instead of deno_std for the node-compat modules, since we are likely to need two different kind of issue trackers

**Comment by ry** [comment]
@kevinkassimo I'm not opposed to doing it in a separate repo - but why do they need to different kind of issue trackers?

**Comment by kevinkassimo** [comment]
@ry Since I believe most of the issues will be about incompatibilities with Node API instead of proposing new functionalities

**Comment by ry** [comment]
@kevinkassimo Ok sure. Does anyone want to start a repo outside of denoland for this? We can point people to it in the manual as the semi-official binding layer. I feel like things might move faster if I'm not in the loop. If it works out and is useful we can consider moving it into deno_std later.

**Comment by zekth** [comment]
@kevinkassimo Creating https://github.com/denolib/node so ?

**Comment by kevinkassimo** [comment]
@zekth Yeah I think this works

**Comment by kevinkassimo** [comment]
@zekth @ry Inited project in https://github.com/denolib/node

**Comment by MarkTiedemann** [comment]
There's also https://www.npmjs.com/package/deno which tries to bring the Deno API to Node (see: https://github.com/denoland/deno_install/issues/6).

**Comment by ozjd** [comment]
Following... I might be able to assist with this.

**Comment by bartlomieju** [comment]
Closing in favor of #2644
