### ISSUE TITLE
deno task auto-installs package.json even when nodeModulesDir: false

### ISSUE THREAD

**Issue by scarf005** [denoland/deno#21850]
Version: Deno 1.39.2

## Summary

- `deno task` ignores `--node-modules-dir=false`, `nodeModulesDir: false` and lists tasks from `package.json`.
- `deno task` respects `DENO_NO_PACKAGE_JSON=1` environment variable, but it's impossible to disable `package.json` usage in `deno.json`.

## Reproduction

`package.json`:
```json
{
	"name": "test",
	"version": "1.0.0",
	"description": "test",
	"scripts": {
		"node-task": "echo this should not be visible"
	}
}
```

`deno.json`:
```json
{
    "nodeModulesDir": false,
	"tasks": {
		"info": "deno info"
	}
}
```

## Expected

```sh
$ deno task
Available tasks:
- info
    deno info
```

## Actual Result

```sh
$ deno task
Available tasks:
- info
    deno info
- node-task (package.json)
    echo this should not be visible

$ deno task --node-modules-dir=false
error: unexpected argument '--node-modules-dir' found

Usage: deno task [OPTIONS] [TASK]

For more information, try '--help'.

$ DENO_NO_PACKAGE_JSON=1 deno task
Available tasks:
- info
    deno info
```

**Comment by dsherret** [comment]
This is expected behaviour. It's not using a node_modules directory in this case and is just executing the task in a package.json.

**Comment by scarf005** [comment]
- the project i'm working on uses yarn pnp
  - which means no node_module
  - thus `deno task dev` (defined in package.json) tries reinstall all npm packages.
  - and deno installs npm packages much slower than npm
- `deno run -A npm:sanity` freezes and cannot be used

therefore, i need to make sure people doesnt run task defined in package.json by accident.

**Comment by dsherret** [comment]
The issue originally described is not an issue, but that is indeed an issue.

**Comment by dsherret** [comment]
By the way, you may want to enable deno's unstable byonm:

```
{
  "unstable": [
    "byonm"
  ]
}
```

That will cause Deno to never auto-install.
