### ISSUE TITLE
refactor: Linter instance should be created only once

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#21876]
https://github.com/denoland/deno/pull/21718#discussion_r1437212647

**Comment by wooseok123** [comment]
I think this issue is resolved in current version? 

https://github.com/denoland/deno/blob/main/cli/tools/lint/mod.rs#L221

**Comment by bartlomieju** [comment]
No really - in here a linter instance is created for each future. We can use a single linter instance across all futures.

**Comment by wooseok123** [comment]
> No really - in here a linter instance is created for each future. We can use a single linter instance across all futures.

I tried to resolve the issue that you mentioned before but i'm not sure if it's a right direction :(
