### ISSUE TITLE
Windows Terminal adds `"` at the end if a folder contains `\` at the end

### ISSUE THREAD

**Issue by deadcoder0904** [denoland/deno#21883]
Version: Deno v1.39.2

I faced this bug in `deno` using Windows 11 & thought it was a [Windows Terminal bug](https://github.com/microsoft/terminal/issues/16536) but others didn't think so it must be a bug with deno on Windows. Copy-pasting the same linked issue below:

### Windows Terminal version

Version: 1.18.3181.0

### Windows build number

Microsoft Windows [Version 10.0.22621.2861]

### Other Software

deno 1.39.2 (release, x86_64-pc-windows-msvc)
v8 12.0.267.8
typescript 5.3.3

### Steps to reproduce

Install [deno](https://deno.com/)

Paste the following script in a folder that has a subfolder.

### doublequote-bug.ts

```ts
// Get folder path from Deno.args
const [folderPath] = Deno.args

// Check if folderPath is provided
if (!folderPath) {
	console.error('Please provide the folder path as an argument.')
	Deno.exit(1)
}

const root = folderPath.replace(/"/g, '') // terminal bug that adds " if foldername contains / at the end

console.log({
	folderPath,
	root,
})
```

Now run it using deno.

### Expected Behavior

`folderPath` shouldn't have `"` at the end & it should look like `root`

This only happens when you have `\` at the end while calling `deno run`.

If I remove `\` manually after pressing `Tab` after typing `how<Tab>`, then both `folderPath` & `root` looks same.

```ts
PS D:\$$ Tuts> deno run .\doublequote-bug.ts '.\How to make $10k a month on Reddit'
{
  folderPath: ".\\How to make $10k a month on Reddit",
  root: ".\\How to make $10k a month on Reddit"
}
```

This is a source of many bugs that I faced in python as well as deno so I think it's actually a Terminal bug.

### Actual Behavior

Here's what I run & the output I get:

```ts
PS D:\$$ Tuts> deno run .\doublequote-bug.ts '.\How to make $10k a month on Reddit\'
{
  folderPath: '.\\How to make $10k a month on Reddit"',
  root: ".\\How to make $10k a month on Reddit"
}
```

Notice the extra double quote near the end of `folderPath`

**Comment by jabed-dev** [comment]
This problem is not Deno or Windows Terminal. This problem is PowerShell 2. This is not exactly a problem in the system of PowerShell 2. You can use [PowerShell 7](https://apps.microsoft.com/detail/9MZ1SNWT0N5D?launch=true&mode=full&hl=en-us&gl=bd&referrer=bingwebsearch&ocid=bingwebsearch).

Here you use first `'.\How ...` it is no problem because PowerShell 2 is using it as a path.
The last `'... Reddit\'` so PowerShell 2 converts to `"`.
When you use `\` in PowerShell 2 you must use `\\`.
`'.\How to make $10k a month on Reddit\'` => `'.\How to make $10k a month on Reddit\\'`

**Comment by deadcoder0904** [comment]
@jabed-dev i'm not adding `\` on my own... just tabbing my way-through. in any case, tabbing should give the correct path.

do you think it is a powershell 2 bug bcz i'm confused? one place you say it is powershell 2 bug & then next statement is its not a bug in powershell 2.

i just use the built-in windows terminal. idk if its built-in but i downloaded it from windows app store or probably winget.

**Comment by jabed-dev** [comment]
> @jabed-dev i'm not adding `\` on my own... just tabbing my way-through. in any case, tabbing should give the correct path.
> 
> do you think it is a powershell 2 bug bcz i'm confused? one place you say it is powershell 2 bug & then next statement is its not a bug in powershell 2.
> 
> i just use the built-in windows terminal. idk if its built-in but i downloaded it from windows app store or probably winget.


I mean the problem is with PowerShell, but it's not its problem, it's the way PowerShell works.

**Comment by jabed-dev** [comment]
I mean the problem is with PowerShell, but it's not its problem, it's the way PowerShell works.

**Comment by deadcoder0904** [comment]
> it's the way PowerShell works.

that is a bug imo.

> You need to remove the last ‌‌‌\.

yeah, i do that & even wrote code for that use-case but it is unnecessary.

powershell guys should fix it. i'll open the issue there i suppose.

**Comment by deadcoder0904** [comment]
so the solution is to use powershell 7 because powershell 5 has halted development since 8 years (2016) as mentioned [here](https://github.com/orgs/PowerShell/discussions/21065)
