### ISSUE TITLE
Add run subcommand: "deno run script.ts" instead of "deno script.ts"

### ISSUE THREAD

**Issue by ry** [denoland/deno#2189]
It's becoming clear that Deno is going to have several distinct tools as subcommands, like "info" and "prefetch" each with (potentially) their own options. I suggest we not have a default command, as it introduces complexity at the flag parsing layer and makes it unclear what flags belong to "run" vs other subcommands.

What do people think? It's slightly less ergonomic, but I think we can address that in other ways.

cc @bartlomieju

**Comment by bartlomieju** [comment]
> I suggest we not have a default command, as it introduces complexity at the flag parsing layer and makes it unclear what flags belong to "run" vs other subcommands.

I'm all in for that :+1: sooner or later `deno <script_name>` is gonna bite us on some edge case in clap and using `deno run <script_name>` eliminates some of issue pointed out by @kevinkassimo in #2102:

> Just for disambiguation, I believe something like `deno run main.ts` could also be introduced: for `deno <subcommand> <script-name>`, if `<subcommand>` does not match any existing subcommands, treat `<subcommand>` as `<script-name>`.

> E.g.
+ `deno run main.ts`: Runs script of name `main.ts`
+ `deno main.ts`: Equivalent to `deno run main.ts`
+ `deno eval "console.log('Hi');"`: evaluate code `console.log('Hi');`
+ `deno run eval`: Runs script of name `./eval`
+ `deno run run`: Runs script of name `./run`

> (Since we have `*.headers.json` (previously `*.mime`) files, it is totally valid to have a file named `eval` without `.ts` extension but still treated as a TypeScript file due to `content-type`)


> I also agree that we should promote `prefetch` and `types` as subcommands and no longer just flags. Actually, I'm not so sure if we could go even further (fully separating subcommands with flags, and no longer allow prefixing `--` to subcommands):
+ subcommands: `help`, `prefetch`, `version`, `types`, `info`, `run`, `fmt`
+ flags: `--allow-*`, `--log-debug`, `--reload`, and others.

> Personally believe this would make the functionalities much clearer. In this case, flags are more or less *modifiers*, which do not change the general behavior that subcommands dictate but *decorate* how to run and what to display.

> E.g. The following seems very clear to me about what kind of output to expect:
+ `deno run --allow-all main.ts`
+ `deno info main.ts`
+ `deno info --log-debug main.ts` (we still want to show `info`, but we also want to show some Deno debug messages`

_Originally posted by @kevinkassimo in https://github.com/denoland/deno/pull/2102#issuecomment-482781130_

Naturally, I'll work on that :)

**Comment by hayd** [comment]
Should repl also be a subcommand?

**Comment by Fenzland** [comment]
That's not a good idea. Before 0.4, we can write shell script like this:
```javascript
#!/usr/bin/env deno

console.log( 'Hello World.', );
```
After 0.4, it throws:
```bash
error: Found argument './test.js' which wasn't expected, or isn't valid in this context

USAGE:
    deno [FLAGS] [OPTIONS] [SUBCOMMAND]

For more information try --help
```

I try to edit my first line to this:
```javascript
#!/usr/bin/env deno run
```
But it throws that:
```bash
/usr/bin/env: ‘deno run’: No such file or directory
```

**Comment by bartlomieju** [comment]
@Fenzland I just checked your example and it works under `v0.5.0`
```
// example.ts
#!/usr/bin/env deno run
console.log('hello world!');
```

```
$ chmod +x example.ts
$ ./example.ts
[1/1] Compiling file:///Users/biwanczuk/dev/foo.ts
hello world!
```

**Comment by Fenzland** [comment]
> @Fenzland I just checked your example and it works under `v0.5.0`
> 
> ```
> // example.ts
> #!/usr/bin/env deno run
> console.log('hello world!');
> ```
> 
> ```
> $ chmod +x example.ts
> $ ./example.ts
> [1/1] Compiling file:///Users/biwanczuk/dev/foo.ts
> hello world!
> ```
> 
> Make sure you're running on latest Deno

What's your environment?
Mine:
Ubuntu 18.04,
Deno version: 0.5.0

**Comment by bartlomieju** [comment]
I was running latest macOS with Deno v0.5.0

**Comment by wsengir** [comment]
This is because Linux's shebang only passes a single argument, while FreeBSD's (macOS's) accepts more. Removing ```run``` as the default subcommand effectively kills shebanging ```deno```. Regardless, the inability to ```--allow-net``` on Linux is crippling, but that could be defended from a security point of view. The novelty of shebanging ```deno``` is alluring, but the lack of portability (the whole purpose of using ```/usr/bin/env```) is a bit more important IMO.

**Comment by bertvanbrakel** [comment]
I just use

`
#!/usr/bin/env deno-shell
`

where 'deno-shell' is a script in $HOME/bin (or wherever you want to put it) with

`#!/usr/bin/env sh
deno run "$@"
`
You can also make a windows deno-shell version

Maybe deno could install a deno-shell script for this usecase?

**Comment by d9k** [comment]
Another option:

https://unix.stackexchange.com/a/551025/48167

```
#!/usr/bin/awk BEGIN{system("deno run "ARGV[1])}
```
