### ISSUE TITLE
hope: XMLHttpRequest in deno

### ISSUE THREAD

**Issue by runnerSnail** [denoland/deno#2191]

**Comment by MarkTiedemann** [comment]
`XMLHttpRequest` is needed for upload [`progress`](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/progress_event) events.

**Comment by kitsonk** [comment]
I really think `XMLHttpRequest` is a big ole can of worms.  It is a really old API with a load of crap to try to make it compatible with the browsers.  IMO we really have to draw the line of "browser compatibility" somewhere.

The best thing is that is someone desired, to use the built in Deno bindings to create a polyfill in `std` and bring it into core if it actually worked well.

**Comment by ry** [comment]
I agree with @kitsonk - it would be great if we didn't support XHR.

@MarkTiedemann I believe that "progress events" are available through fetch streaming?

**Comment by ry** [comment]
Won’t implement

**Comment by ruifortes** [comment]
https://forum.rescript-lang.org/t/current-recommendations-on-fetching-data-and-promises/888/2

**Comment by Ciantic** [comment]
I'm having problems with WASM files generated with emscripten because it uses in JS wrapper `XMLHttpRequest`.

https://github.com/denoland/deno/issues/2191
