### ISSUE TITLE
[Bug test] deno test: error: No test modules found

### ISSUE THREAD

**Issue by jerome-benoit** [denoland/deno#21916]
Version: Deno 1.39.3: https://github.com/poolifier/poolifier-deno/actions/runs/7506348228/job/20437633353 =>  error: No test modules found
Version: Deno 1.39.2: https://github.com/poolifier/poolifier-deno/actions/runs/7506478378/job/20437982957 => no error

100% reproducible in GitHub CI.

**Comment by bartlomieju** [comment]
Hey @jerome-benoit, thanks for the report and sorry for the problem.

I think this problem might be caused by https://github.com/denoland/deno/pull/21817. Any chance you could try running against canary version of `43d2ecd4f056bf38fe5f5656e550061c68c717f0`?

**Comment by jerome-benoit** [comment]
> Hey @jerome-benoit, thanks for the report and sorry for the problem.
> 
> I think this problem might be caused by #21817. Any chance you could try running against canary version of `43d2ecd4f056bf38fe5f5656e550061c68c717f0`?

If the GitHub action to setup deno supports canary version, I will do it and post the link to the run here.

**Comment by bartlomieju** [comment]
> > Hey @jerome-benoit, thanks for the report and sorry for the problem.
> > I think this problem might be caused by #21817. Any chance you could try running against canary version of `43d2ecd4f056bf38fe5f5656e550061c68c717f0`?
> 
> If the GitHub action to setup deno supports canary version, I will do it and post the link to the run here.

Yes, it certainly does: https://github.com/denoland/setup-deno?tab=readme-ov-file#specific-canary

Thanks!

**Comment by jerome-benoit** [comment]
The canary version works at launching `deno test ...` from a task: https://github.com/poolifier/poolifier-deno/actions/runs/7507978417/job/20442608617

**Comment by bartlomieju** [comment]
Thanks for checking, and just to be absolutely sure; does it fail against `e212e1fc35ddae63f457f0f2a2e95154e008941f`?

**Comment by jerome-benoit** [comment]
The canary version e212e1fc35ddae63f457f0f2a2e95154e008941f fails: https://github.com/poolifier/poolifier-deno/actions/runs/7508080559/job/20442877378

The manual `git bisect` pointpoint the guilty commit is guess ;)

**Comment by bartlomieju** [comment]
Thanks, we'll look into it ASAP and might release v1.39.4 to fix it.

**Comment by dsherret** [comment]
Temp workaround is to remove the leading `./` in the config file. Sorry about that! I'm surprised there were no tests for this scenario.

**Comment by jerome-benoit** [comment]
> Temp workaround is to remove the leading `./` in the config file. Sorry about that! I'm surprised there were no tests for this scenario.

I can live with it but I think a bunch of similar issues will be opened in the next days.

**Comment by dsherret** [comment]
I'll do a release for this one at the end of the day. I can confirm it fixes the issue in the repo.

**Comment by dsherret** [comment]
Fixed now in deno 1.39.4
