### ISSUE TITLE
Should `deno compile` warn of unsupported bare-node-builtins?

### ISSUE THREAD

**Issue by sgvictorino** [denoland/deno#21920]
Version: Deno 1.39.3

[Like sloppy imports](https://github.com/denoland/deno/blob/7471587d29096a8de95a530f2132214ab9c08afa/cli/tools/compile.rs#L40-L50), I think the compiler should warn that `--unstable-bare-node-builtins` is unsupported.

`test.ts`:
```ts
import("os")
```

```bash
deno compile --unstable-bare-node-builtins test.ts
# ...
# Warning: Resolving "os" as "node:os" at file:///tmp/test.ts:1:8. If you want to use a built-in Node module, add a "node:" prefix.
# Compile file:///tmp/test.ts to test
./test # error: Uncaught (in promise) TypeError: Relative import path "os" not prefixed with / or ./ or ../ from "file:///tmp/test.ts"
```

**Comment by dsherret** [comment]
I think that's just a bug. It should work with `deno compile`. I thought https://github.com/denoland/deno/pull/21827/ would have fixed it, but seems not completely (cc @bartlomieju)

**Comment by bartlomieju** [comment]
Nice catch! I didn't handle other `unstable-` features. This seems like an easy fix that I can do tomorrow.
