### ISSUE TITLE
benchmarks: Update nodeJs

### ISSUE THREAD

**Issue by zekth** [denoland/deno#2192]
As NodeJs 12 has been released it would be nice to have it in the benchmarks.

ref: https://nodejs.org/en/blog/release/v12.0.0/

**Comment by j-f1** [comment]
Was this done in https://github.com/denoland/deno/pull/2193?

**Comment by ry** [comment]
Yes. And note that node_tcp with v12 has overtaken deno_core_single ... we have more work to do.
