### ISSUE TITLE
deno check panicked when "exclude" contains folder with d.ts file in compilerOptions.types (in deno.json)

### ISSUE THREAD

**Issue by rkulinsky** [denoland/deno#21926]
Version: Deno 1.39.3 (issue found in 1.39.2)

The command
```bash
deno check lib/utils.ts
```
causes error:
> ============================================================
> Deno has panicked. This is a bug in Deno. Please report this
> at https://github.com/denoland/deno/issues/new.
> If you can reliably reproduce this panic, include the
> reproduction steps and re-run with the RUST_BACKTRACE=1 env
> var set and include the backtrace in your report.
> 
> Platform: macos aarch64
> Version: 1.39.3
> Args: ["deno", "check", "lib/utils.ts"]
> 
> thread 'main' panicked at cli/tools/check.rs:150:41:
> index out of bounds: the len is 0 but the index is 0
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Folders structure:
```
lib
  - index.d.ts
  - utils.ts
deno.json
```
deno.json:
```json
{
  "compilerOptions": {
    "types": ["./lib/index.d.ts"]
  },
  "exclude": ["lib"]
}
```

index.d.ts
```typescript
interface ISample {
  value: number;
}
```

utils.ts
```typescript
export function calc(data: ISample) {
  return data.value + 3;
}
```

Expected behavior:
`deno check lib/utils.ts` does not result in deno panick.

Proposed behavior:
As the "lib" folder is in the "exclude" list and we are trying to check files in this folder, the provided deno.json configuration makes no sense (but stays syntactically correct). 
But deno runtime could give some meaningful message about that or just standard "no matches found:" without panicking.

**Comment by jerome-benoit** [comment]
It's related to the fix https://github.com/denoland/deno/pull/21922. 

In the meantime, you can remove the `./` from the paths you use in deno.json to workaround the issue.

**Comment by rkulinsky** [comment]
> It's related to the fix #21922.
> 
> In the meantime, you can remove the `./` from the paths you use in deno.json to workaround the issue.

Thanks! It worked.

**Comment by rkulinsky** [comment]
> > It's related to the fix #21922.
> > In the meantime, you can remove the `./` from the paths you use in deno.json to workaround the issue.
> 
> Thanks! It worked.

@jerome-benoit I guess I was in too much of a hurry :). After removing ./ from the paths in "types" deno check can`t find the types declared in the d.ts files.

**Comment by jerome-benoit** [comment]
> > > It's related to the fix #21922.
> > > In the meantime, you can remove the `./` from the paths you use in deno.json to workaround the issue.
> > 
> > 
> > Thanks! It worked.
> 
> @jerome-benoit I guess I was in too much of a hurry :). After removing ./ from the paths in "types" deno check can`t find the types declared in the d.ts files.

Then it's unrelated to the quoted issue. 
I guess you should follow the hint, rerun, post the result and also gives the content of the .d.ts file that trigger the issue.

**Comment by rkulinsky** [comment]
Here is modified example - I removed "./" from the beginning of the path "./lib/index.d.ts".

Now `deno check lib/*.ts` causes no error.
But `deno check src/*.ts` can`t find the types declared in index.d.ts

> error: TS2304 [ERROR]: Cannot find name 'ISample'.
> export function calc(data: ISample) {
> at file:///<...>/src/utils.ts:1:28

Folders structure:
```
lib
  - index.d.ts
  - helpers.ts
src
  - utils.ts
deno.json
```
deno.json:
```json
{
  "compilerOptions": {
    "types": ["lib/index.d.ts"]
  },
  "exclude": ["lib"]
}
```

lib/index.d.ts
```typescript
interface ISample {
  value: number;
}
```

src/utils.ts
```typescript
export function calc(data: ISample) {
  return data.value + 3;
}
```

lib/helpers.ts
```typescript
export function calculate() {
  return 1 + 2;
}
```

**Comment by jerome-benoit** [comment]
Well, 
+ you exclude the path where types are
+ utils.ts is not explicitly importing the type

deno behave proprely given its configuration, and its configuration is correct.

**Comment by rkulinsky** [comment]
If I move index.d.ts to a different (not excluded) folder (eg "types") the issue persists.

deno.json:
```json
{
  "compilerOptions": {
    "types": ["types/index.d.ts"]
  },
  "exclude": ["lib"]
}
```
`deno check src/*.ts` gives the same error:

> error: TS2304 [ERROR]: Cannot find name 'ISample'.
> export function calc(data: ISample) {
> at file:///<...>/src/utils.ts:1:28

So I guess this is because "types"-paths with no "./" at the beginning don't work as expected or are just ignored.

**Comment by jerome-benoit** [comment]
It's not a Deno bug. And Deno GitHub issues are not targeted to JS usage end user support with Deno. 

Please close that issue, read documentation about module/interface import/export in JS and ask for support on the Deno discord dedicated channel for support.

**Comment by rkulinsky** [comment]
The original issue is not about JS usage but about deno panick while checking ts-files, right ? Or am I missing something ?

**Comment by jerome-benoit** [comment]
> The original issue is not about JS usage but about deno panick while checking ts-files, right ? Or am I missing something ?

You're right. 

But 

+ Does a correct deno.json configuration and interface import makes `deno check` work?
+ Does `deno run` executes the code with and without the import, proper deno.json configuration? 
+ Does `deno check` output match `deno run` one with and without the import, proper deno.json configuration? 

Could you please test all that use cases to pointpoint the minimum repro case and tool impacted? 
And update the main description issue to clearly state that a panic should not happen with `deno check` under the minimum conditions identified?

**Comment by rkulinsky** [comment]
OK, no problem.

But ;)
> * Does a correct deno.json configuration and interface import makes `deno check` work?
> * Does `deno run` executes the code with and without the import, proper deno.json configuration?
> * Does `deno check` output match `deno run` one with and without the import, proper deno.json configuration?

May I ask what is "correct" (and "proper") deno.json configuration ? With "./" at the beginning of paths in "compilerOptions.types" property values or without ?

**Comment by jerome-benoit** [comment]
> OK, no problem.
> 
> But ;)
> 
> > * Does a correct deno.json configuration and interface import makes `deno check` work?
> > * Does `deno run` executes the code with and without the import, proper deno.json configuration?
> > * Does `deno check` output match `deno run` one with and without the import, proper deno.json configuration?
> 
> May I ask what is "correct" (and "proper") deno.json configuration ? With "./" at the beginning of paths in "compilerOptions.types" property values or without ?

The latest one you were using looks correct: types are found.

**Comment by dsherret** [comment]
Just a note that this is unrelated to https://github.com/denoland/deno/pull/21922

**Comment by jerome-benoit** [comment]
> This is just a panic that occurs when a file is specified that's excluded.
> 
> > As the "lib" folder is in the "exclude" list and we are trying to check files in this folder, the provided deno.json configuration makes no sense (but stays syntactically correct).
> > But deno runtime could give some meaningful message about that or just standard "no matches found:" without panicking.
> 
> I will open a PR.

Yes, it's just about not panic for semantically incorrect deno.json file, at least for some 'trivial' semantic checks.

**Comment by rkulinsky** [comment]
> This is just a panic that occurs when a file is specified that's excluded.
Specified where ? in "paths" or in `deno check` args ?
Removing "paths" option from compilerOptions makes panick to disappear.
