### ISSUE TITLE
use stc to improve deno lint

### ISSUE THREAD

**Issue by KnorpelSenf** [denoland/deno#21946]
`deno lint` is awesome because it's super fast. However, there are things I really wish it could do, but it can't. The prime example for this is `no-floating promises`.
```ts
function foo() { return Promise.resolve() }

foo() // forgot to use await!
```
The reason why Deno isn't able to lint such things properly is because it doesn't run tsc. Thus, there's no way to infer the return type of `foo`, so the promise is floating without a warning. Using `tsc` is not really an option due to the performance cost.

I suggest to use https://github.com/dudykr/stc which lets us do most of these things correctly. It isn't mature enough to replace tsc inside `deno check` IMO, but it could serve as the basis for much better linting as it would enable `deno lint` to access type information.

What's your opinion on this?

**Comment by dsherret** [comment]
stc is not being worked on anymore.

> stc: Donny confirmed the article direction and mentioned no longer working on stc.

https://www.joshuakgoldberg.com/blog/rust-based-javascript-linters-fast-but-no-typed-linting-right-now/

**Comment by dsherret** [comment]
I also want no-floating-promises. It would be great if TypeScript would just add it https://github.com/microsoft/TypeScript/issues/13376#issuecomment-1609812642

**Comment by KnorpelSenf** [comment]
Oh no. I was not aware.

Would that mean that Deno would start running tsc during lint?

**Comment by dsherret** [comment]
The TypeScript issue would probably mean another compiler option where it points out unawaited promises. So it would be pointed out with `deno check`.

**Comment by KnorpelSenf** [comment]
Smart!

**Comment by KnorpelSenf** [comment]
@dsherret have you considered to add opt-in type-based linting, such as `deno lint --check` or perhaps `deno lint --types`, which supports more rules at the expense of worse perf?

**Comment by bartlomieju** [comment]
@KnorpelSenf weve considered it and it's possible, but we don't have bandwidth to work on it now. Contributions are welcome though :)

**Comment by dsherret** [comment]
> Contributions are welcome though :)

There should be agreement on something so large before it's implemented. It will be a lot of work.

**Comment by bartlomieju** [comment]
> > Contributions are welcome though :)
> 
> There should be agreement on something so large before it's implemented. It will be a lot of work.

Yes, for sure. A proposal would be a good contribution first.

**Comment by dsherret** [comment]
Btw, there is a list of type aware lints here: https://github.com/denoland/deno_lint/issues/1138

**Comment by KnorpelSenf** [comment]
Thanks for explaining! I currently also have too much on my list to work on this, but it's good to know that we can push in that direction if someone finds the time.
