### ISSUE TITLE
suggestion: add a warning to readDir doc that no specific ordering of files should be expected

### ISSUE THREAD

**Issue by king8fisher** [denoland/deno#21943]
readDir might be not expected to return lexically unordered list of files on macOS or Linux (and AFAIK not guaranteed on Windows either). A hint in the doc could remind of that "Reads the directory given by path and returns an async iterable of Deno.DirEntry without any guaranteed order".

See https://pkg.go.dev/path/filepath#WalkDir for background.

**Comment by kt3k** [comment]
readDir API is documented here. Can you send a PR to implement the above suggestion? https://github.com/denoland/deno/blob/bc8d00c880756a46b0ce4c8bf0c89407a2de669c/cli/tsc/dts/lib.deno.ns.d.ts#L3417-L3433

**Comment by king8fisher** [comment]
Thank you for the honor! Will do!
