### ISSUE TITLE
Move away from `value_parser!(PathBuf)` in clap

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#21954]
It gives the false impression that what's in the `PathBuf` is an absolute path, when often it's not (sometimes it's even been urls and file patterns). If it is a path, we should join it on the initial_cwd(). Otherwise we should convert it to the appropriate type.

**Comment by lczerniawski** [comment]
Hi @dsherret do you mind if I pick that up? When I recently been working on an issue to add a new flag, I saw a lot of PathBuf usage that was confusing. It made me happy to see that there is a plan to redo that and it is not actually on purpose, and I would love to fix it :)

**Comment by dsherret** [comment]
@lczerniawski definitely! Go for it. I think most of these should just be `String` and then if they need to be converted to a pathbuf they can be joined on `cli_options.initial_cwd()`

**Comment by lczerniawski** [comment]
@dsherret I opened PR, please take a look when you have a moment, and let me know if that looks good to you :)
Thanks!

**Comment by dsherret** [comment]
Done via https://github.com/denoland/deno/pull/22036
