### ISSUE TITLE
"Deno.serve()" panics on Windows when using trying to use Unix socket

### ISSUE THREAD

**Issue by vince-deno** [denoland/deno#21967]
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: windows x86_64
Version: 1.39.4
Args: ["deno", "run", "-A", "test.ts"]

thread 'main' panicked at ext\net\lib.rs:135:1:
Unsupported on non-unix platforms
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

the i used=>```
const ac = new AbortController();

const server = Deno.serve({
  path: "path/to/socket",
  handler: (_req) => new Response("Hello, world"),
  signal: ac.signal,
  onListen({ path }) {
    console.log(`Server started at ${path}`);
  },
});
server.finished.then(() => console.log("Server closed"));

console.log("Closing server...");
ac.abort();
```

**Comment by lucacasonato** [comment]
This should be changed to a thrown error rather than a panic.
