### ISSUE TITLE
regression: 1.39.3 and 1.39.4 breaks the denoland.vscode-deno vscode formatter on windows

### ISSUE THREAD

**Issue by king8fisher** [denoland/deno#21971]
Version: Deno 1.39.3, 1.39.4
Seems to be affecting Windows only. Mac works fine. Can't reproduce on Linux.

Neither the formatting on save nor manual request to format work on the affected versions.

`deno upgrade --version 1.39.2` restores the formatter (after rebooting VSCode), no need to downgrade the vscode extension which is [3.31.0](https://github.com/denoland/vscode_deno/compare/3.30.0...3.31.0) / 2023.12.28
Formatting on save or manual request to format works as expected.

My local `.vscode` `settings.json` settings are:

```json
  "javascript.format.enable": false,
  "typescript.format.enable": false,
  "editor.defaultFormatter": "denoland.vscode-deno",
  "editor.formatOnSave": true,
  "[typescriptreact]": {
    "editor.defaultFormatter": "denoland.vscode-deno"
  },
  "[typescript]": {
    "editor.defaultFormatter": "denoland.vscode-deno"
  },
  "[javascriptreact]": {
    "editor.defaultFormatter": "denoland.vscode-deno"
  },
  "[javascript]": {
    "editor.defaultFormatter": "denoland.vscode-deno"
  },
  "[json]": {
    "editor.defaultFormatter": "denoland.vscode-deno"
  },
  "[jsonc]": {
    "editor.defaultFormatter": "denoland.vscode-deno"
  },
  "editor.codeActionsOnSave": {
    "source.organizeImports": "never",
    "source.fixAll": "never"
  },
  "[css]": {
    "editor.defaultFormatter": "vscode.css-language-features"
  }
```

My global settings has nothing regarding formatting.

**Comment by dsherret** [comment]
This should be fixed in canary now (`deno upgrade --canary`). Please let me know if not.

**Comment by king8fisher** [comment]
It works! Excellent! You are so fast it's pretty amazing! Thank you!!!
