### ISSUE TITLE
`next-contentlayer` with Next.js not working

### ISSUE THREAD

**Issue by littledivy** [denoland/deno#21976]
To reproduce:

1. `mkdir repro && cd repro`
1. `deno run -A --unstable npm:degit 'timlrx/tailwind-nextjs-starter-blog'`
2. Convert `next.config.js` to ESM 
3. `npm i`
4. `deno run -A --unstable-byonm ./node_modules/.bin/next dev`

In the wall of errors, you'll find:
```
ConfigReadError (/Users/divy/gh/demo/contentlayer.config.ts): TypeError: Cannot read properties of undefined (reading 'env') at file:///Users/divy/gh/demo/.contentlayer/.cache/v0.3.4/compiled-contentlayer-config-V47B5E7I.mjs?x=1705550689002:58:35
ConfigReadError (/Users/divy/gh/demo/contentlayer.config.ts): TypeError: Cannot read properties of undefined (reading 'env') at file:///Users/divy/gh/demo/.contentlayer/.cache/v0.3.4/compiled-contentlayer-config-V47B5E7I.mjs?x=1705550689011:58:35
```

**Comment by littledivy** [comment]
Adding an `import process from "node:process"` in `data/siteMetadata.js`  fixes the issue

**Comment by kt3k** [comment]
Looks like this has been fixed by https://github.com/denoland/deno/pull/25291 (I was able to run `deno task start` in the above setup)
