### ISSUE TITLE
The `dom` lib is missing typings for `ReadableStream.from`

### ISSUE THREAD

**Issue by BlackAsLight** [denoland/deno#21981]
Version: Deno 1.39.4

Really just forwarding this comment since that issue is closed and therefore seems to not be on anyone's radar.
https://github.com/denoland/deno/issues/21733#issuecomment-1880315355 

## Example
This code runs successfully, but throws a typing error on `.from`
```ts
function* example() {
	yield 1
}

const stream = ReadableStream.from(example())

for await (const value of stream)
	console.log(value)
```
```json
{
	"compilerOptions": {
		"lib": [
			"dom",
			"deno.ns"
		]
	}
}

**Comment by kt3k** [comment]
We usually don't update `lib.dom.d.ts` with our own modification, but directly follow the updates from TypeScript repository. Should this case be considered as an exception? cc @dsherret @bartlomieju

**Comment by kt3k** [comment]
> A feature needs to be supported by two or more major browser engines to be included here, to make sure there is a good consensus among vendors: Gecko (Firefox), Blink (Chrome/Edge), and WebKit (Safari).

https://github.com/microsoft/TypeScript-DOM-lib-generator

lib.dom has the above criteria to include new APIs and `ReadableStream.from` doesn't meet it yet (ReadableStream.from is only supported by firefox)

**Comment by Hajime-san** [comment]
It's a temporary measures that overwriting `deno.web` next in `dom` to `lib` array.
But, there is a possibility to cause other typing issues...

``` jsonc
{
  "compilerOptions": {
    "lib": [
      "dom",
      "deno.web"
    ]
  }
}
```

BTW, it's not only `Readable.from` problem but other APIs that is not implementing commonly?
