### ISSUE TITLE
how can i load the .env 

### ISSUE THREAD

**Issue by fengyunzaidushi** [denoland/deno#21982]
{ deno: "1.39.4", v8: "12.0.267.8", typescript: "5.3.3" }
import { load } from "https://deno.land/std@0.212.0/dotenv/mod.ts";

const env = await load();
const OPENAI_API_KEY = env["OPENAI_API_KEY"];

**Comment by lucacasonato** [comment]
Deno has .env loading built in. You just need to pass the `--env` flag to `deno run`: `deno run --env ...`. You do not need to import any packages or run any specific code for this to work.
