### ISSUE TITLE
Lint diagnostics are offset on the line when prefixed by emojis

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#21983]
![Screenshot from 2024-01-18 12-08-03](https://github.com/denoland/deno/assets/7829205/91f1ae41-ca38-40be-88dd-fc8adea756a0)

```ts
"🎄🎄🎄🎄🎄🎄";	function test() {}
```

**Comment by nayeemrmn** [comment]
This affects the cli too:
```
$ deno lint - <<< '"🎄🎄🎄🎄🎄🎄"; function test() {}'
(no-unused-vars) `test` is never used
"🎄🎄🎄🎄🎄🎄"; function test() {}
                   ^^^^
    at _stdin.ts:1:20

    hint: If this is intentional, prefix it with an underscore like `_test`
    help: for further information visit https://lint.deno.land/#no-unused-vars

Found 1 problem
Checked 1 file
```

@dsherret

**Comment by lucacasonato** [comment]
@nayeemrmn I am fixing the CLI bug right now actually :)

**Comment by lucacasonato** [comment]
The bug is how we convert between the `byte_index` in `deno_lint::Position` to LSP data.

**Comment by dsherret** [comment]
I see why I got confused by this earlier. I actually had a patch to change this in text_lines, but then saw VS Code incorrectly displaying the column index for the identifier as 20 in the bottom right rather than 26. Anyway, this is fixed now.
