### ISSUE TITLE
Dear all ,please allow me to leave a comment about Nodejs community management because I was blocked by nodejs (just because I mentioned a bug that they all admit to) 

### ISSUE THREAD

**Issue by introspection3** [denoland/deno#22005]
Version: Deno 1.x.x

There is such a person in this world: covering his ears and stealing the bell. FORCE A BUG TO CLOSE AND ASSUME THAT THE BUG DOES NOT EXIST. This is the attitude towards bugs. First of all, I would like to state that it is not for them to fix the bug, but to raise the bug so that at least the community will know what the problem is, not hide the truth

LINK: [https://github.com/nodejs/node/issues/51507](https://github.com/nodejs/node/issues/51507)

**Comment by introspection3** [comment]
![image](https://github.com/denoland/deno/assets/12368358/b7fe3a05-c575-47f7-b7b2-d48ce3014510)

**Comment by introspection3** [comment]
![image](https://github.com/denoland/deno/assets/12368358/825f6abc-c77e-4591-9c76-e9492742c296)

**Comment by introspection3** [comment]
[html.zip](https://github.com/denoland/deno/files/13997873/html.zip)

**Comment by ovflowd** [comment]
Just for clarification, the person you're so eagerly shaming, had nothing to do with your block. I blocked you from the Node org. Have a good day.

**Comment by littledivy** [comment]
Unrelated to Deno.

Please stop wasting people's time.
