### ISSUE TITLE
Deno install progress is currently useless, because total keeps updating

### ISSUE THREAD

**Issue by birkskyum** [denoland/deno#22000]
Version: Deno 1.39.4

When I use deno task dev, and it installs a ton of packages it'll be like:

(1 / 3)
(3 / 4)
(5 / 8)
...
(127 / 129)

Is it possible to calculate the total number from the start so this progress becomes somewhat useful?

**Comment by marvinhagemeister** [comment]
The way Deno fetches dependencies at the moment is on a file-by-file basis. Because of that the total amount of dependencies is not known upfront and the number increases as Deno walks the module graph and discovers dependencies that haven't been downloaded yet.

**Comment by dsherret** [comment]
It's the same issue with `npm install` because the total number of packages is not known until the graph is fully walked and resolved. You can see a visualization of this progression here and how the "remaining packages" number fluctuates over time: https://npm.anvaka.com/#/view/2d/parcel
