### ISSUE TITLE
deno.land/x not incrementing version of my module

### ISSUE THREAD

**Issue by adamzerner** [denoland/deno#22014]
I am working on [`rfui`](https://deno.land/x/rfui). I have followed the instructions on ["Adding a module"](https://deno.com/add_module) to publish it to deno.land/x. Up until v0.1.0, it has worked. However, since v0.1.0, it has not worked.

As seen in the [tags](https://github.com/adamzerner/rfui/tags) and [releases](https://github.com/adamzerner/rfui/releases) pages, I have released v0.1.1, v0.1.2, and v0.1.3. And the webhook is [still set](https://github.com/adamzerner/rfui/settings/hooks).

Why do I say it hasn't worked?
- If you go to https://deno.land/x/rfui, it redirects to https://deno.land/x/rfui@v0.1.0, not v0.1.3.
- On https://deno.land/x/rfui, it indicates that v0.1.0 is the latest version.
- https://deno.land/x/rfui@v0.1.1 displays a 404 error.
- Having `"rfui": "https://deno.land/x/rfui@v0.1.1/mod.ts"` in a [Fresh](https://fresh.deno.dev/) project leads to me having a `"Module not found "https://deno.land/x/rfui@v0.1.1/mod.ts".` error

**Comment by crowlKats** [comment]
The issue is that you went over the module size limit (you can see that in your github webhook deliveries).

**Comment by adamzerner** [comment]
@crowlKats Where are you seeing this? I am seeing a bunch of `{"success":false,"info":"created ref is not tag"}` responses but nothing about a module size limit.

<img width="1440" alt="Screenshot 2024-01-20 at 10 18 03 PM" src="https://github.com/denoland/deno/assets/3144254/cdc294a3-c151-4f6f-ba4b-595026b30252">

Also, I am not seeing a module size limit documented anywhere. Can you point me to a place where I can read more about it?

It seems odd to me that I would reach such a limit. I have only been working on this project for a few months and am at about 15k lines of code. Surely other projects are much larger.

**Comment by crowlKats** [comment]
that is extremely weird. The error would make me think that the webhook might be misconfigured, though I have never seen that kind of error. Internally, that error is not even attributed with any of your releases. what happens if you redeliver one of those failed webhooks?

That weird behaviour aside, for reference, here is a status of one of the versions that failed: https://deno.com/status/19a30a63-3257-48e0-84ae-af309d29cd05 (usually this link would show up in the webhook response body).

**Comment by adamzerner** [comment]
> that is extremely weird.

Yeah, it does seem weird. Especially since I haven't changed anything about the webhook since initially creating it.

> The error would make me think that the webhook might be misconfigured, though I have never seen that kind of error.

The fact that the webhook had been working up to and including v0.1.0 makes me think that it isn't misconfigured.

> what happens if you redeliver one of those failed webhooks?

After redelivering I get the same error:

<img width="820" alt="Screenshot 2024-01-20 at 11 33 29 PM" src="https://github.com/denoland/deno/assets/3144254/831017aa-b378-447a-b0aa-a29a8dd92cba">

> That weird behaviour aside, for reference, here is a status of one of the versions that failed: https://deno.com/status/19a30a63-3257-48e0-84ae-af309d29cd05 (usually this link would show up in the webhook response body).

Hm, I see. I wonder why my module is large given that it's only 15k LOC.

**Comment by adamzerner** [comment]
I just realized that I had a large 45MB `tailwindcss` executable in this repo. I removed it in [this commit](https://github.com/adamzerner/rfui/commit/a8da48ec27aeba2a30ddec644e8ab26c894cb7ea) and then [released v0.1.4](https://github.com/adamzerner/rfui/releases/tag/v0.1.4). It looks like it still isn't working though.

**Comment by adamzerner** [comment]
I think the module size issue should be resolved now.
- Looking at the [link](https://deno.com/status/19a30a63-3257-48e0-84ae-af309d29cd05) you [provided](https://github.com/denoland/deno/issues/22014#issuecomment-1902537542), I was at 48 MB and the limit is 21 MB.
- After removing that `tailwindcss` executable that was taking up 45MB I should be back down to 3 MB, which is way under 21 MB.
- Looking on my local machine, my `rfui` directory is 61.5MB, but `node_modules` is 36.9 MB and `.git` is 24.1 MB, which leaves only 0.5 MB remaining. I'm not sure why there's the discrepancy between the 0.5 MB here and the 3 MB I predicted in the second bullet point, but it also doesn't seem like an issue since both are way below the 21 MB limit.

However, my module is still not being incremented.

Also, my most recent two webhooks are getting the original `{"success":false,"info":"created ref is not tag"}` response.

**Comment by adamzerner** [comment]
I was thinking about that error message `{"success":false,"info":"created ref is not tag"}`. I realized that my process is to go to https://github.com/adamzerner/rfui/releases/new, click "Choose a tag", and then create a new tag. It says:

>  Choose an existing tag, or create a new tag when you publish this release. 

I figured that might be the issue, so I tried creating the new tag _first_ and _then_ just using the tag for my release. But it turned out that just creating the tag fixed stuff. Which makes sense given that the webhook is on tag creation.

So I have figured out a workaround for my issue, but it still might be worth improving various things associated with this for the sake of others.

**Comment by crowlKats** [comment]
apologies for the delay, as I was sick during last week. This is quite odd, since I'd assume that GitHub just creates a tag and would fire the tag creation event with it.

**Comment by adamzerner** [comment]
@crowlKats No worries on the delay. I hope you are feeling better.

**Comment by crowlKats** [comment]
Yes, thanks.
I just published https://deno.land/x/gfm@0.6.0 via a creating a tag by doing a github release, and it worked without problem. something odd is happening for sure.

**Comment by lucacasonato** [comment]
It seems like this is working again? I see the last release is up to date with the repo tag? https://deno.land/x/rfui@v0.1.21


Pleas re-open if this is still an issue.
