### ISSUE TITLE
tracking: Deno 2 subcommand, flag and symbol removals

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno#22079]
The following table contains all of the subcommands, flags and symbols to be removed in Deno 2.0.0. Some symbols will be soft removed, meaning that their types will be removed, but their functionality will live on, as to not break too much code. Maintainers, please update as needed.

Migration documentation can be found here: https://docs.deno.com/runtime/manual/advanced/migrate_deprecations/

| Subcommand/flag/symbol            | Docs | Removed | Removal PR |
|-----------------------------------|------|---------|------------|
| `deno bundle`                       | ✅    | ✅       | #25339     |
| `deno vendor`                       | ✅    | ✅       | #25343     |
| `--allow-none`                      | ✅    | ✅       | #25337     |
| `--jobs`                            | ✅    | ✅       | #25336     |
| `--ts`                              | ✅    | ✅       | #25338     |
| `--trace-ops`                       | ✅    | ✅       | #25344     |
| `--unstable`                        | ✅    | ✅        | #25522           |
| `Deno.Buffer`                       | ✅    | ✅       | #25441     |
| `Deno.close()`                      | ✅    | ✅       | #25347     |
| `Deno.Closer`                       | ✅    | ✅        | #25524     |
| `Deno.Conn.prototype.rid`           | ✅    | ✅       | #25446     |
| `Deno.ConnectTlsOptions.certChain`  | ✅    | ✅        | #25525     |
| `Deno.ConnectTlsOptions.certFile`   | ✅    | ✅        | #25525     |
| `Deno.ConnectTlsOptions.privateKey` | ✅    | ✅        | #25525     |
| `Deno.copy()`                       | ✅    | ✅       | #25345     |
| `Deno.customInspect`                | ✅    | ✅       | #25348     |
| `Deno.fdatasync[Sync]()`            | ✅     | ✅       | #25520     |
| `Deno.File`                         | ✅    | ✅       | #25447     |
| `Deno.flock[Sync]()`                | ✅    | ✅       | #25350     |
| `Deno.FsFile.prototype.rid`                | ✅    | ✅       | #25499     |
| `Deno.fstat[Sync]()`                | ✅    | ✅       | #25351     |
| `Deno.FsWatcher.prototype.rid`      | ✅    | ✅       | #25444     |
| `Deno.fsync[Sync]()`                | ✅     | ✅        | #25448     |
| `Deno.ftruncate[Sync]()`            | ✅    | ✅       | #25412     |
| `Deno.funlock[Sync]()`              | ✅    | ✅       | #25442     |
| `Deno.futime[Sync]()`               | ✅    | ✅       | #25252     |
| `Deno.isatty()` (soft)              | ✅    | ✅       | #25410     |
| `Deno.iter[Sync]()`                 | ✅    | ✅       | #25346     |
| `Deno.Listener.prototype.rid`     | ✅    | ✅        | #25556     |
| `Deno.ListenTlsOptions.certChain`   | ✅    | ✅        | #25525     |
| `Deno.ListenTlsOptions.certFile`    | ✅    | ✅        | #25525     |
| `Deno.ListenTlsOptions.keyFile`     | ✅    |  ✅       | #25525     |
| `Deno.metrics()`                    | ✅    | ✅       | #25167     |
| `Deno.read[Sync]()`                 | ✅    | ✅       | #25409     |
| `Deno.readAll[Sync]()`              | ✅    | ✅       | #25386     |
| `Deno.Reader[Sync]()`               | ✅    | ✅        | #25524     |
| `Deno.resources()`                  | ✅    | ✅       | #25251     |
| `Deno.run()` (soft)                 | ✅    | ✅       | #25403     |
| `Deno.Seeker[Sync]`                       | ✅    | ✅       | #25551    |
| `Deno.seek[Sync]()`                 | ✅    | ✅       | #25449     |
| `Deno.serveHttp()` (soft)           | ✅    | ✅       | #25451     |
| `Deno.Server`                       | ✅    | ✅       | #25369     |
| `Deno.shutdown()`                   | ✅    | ✅       | #25253     |
| `Deno.stderr.prototype.rid` (soft)  | ✅    | ✅       | #25479     |
| `Deno.stdin.prototype.rid` (soft)   | ✅    | ✅       | #25479     |
| `Deno.stdout.prototype.rid` (soft)  | ✅    | ✅       | #25479     |
| `Deno.TcpConn.prototype.rid`        | ✅    | ✅       | #25446     |
| `Deno.TlsConn.prototype.rid`        | ✅    | ✅       | #25446     |
| `Deno.TlsListener.prototype.rid`        | ✅    | ✅       | #25556    |
| `Deno.UnixConn.prototype.rid`       | ✅    | ✅       | #25446     |
| `Deno.write[Sync]()`                | ✅    | ✅       | #25408     |
| `Deno.writeAll[Sync]()`             | ✅    | ✅       | #25407     |
| `Deno.Writer[Sync]`                 | ✅    | ✅        | #25524     |
| `new Deno.FsFile()`                 | ✅    | ✅       | #25478     |
| `window`                            | ✅    | ✅       | #25213     |

**Comment by Leokuma** [comment]
Should we track `deno.json` options here too?

**Comment by iuioiua** [comment]
Remind me, which ones?

**Comment by Leokuma** [comment]
Luca proposed to "deprecate `exclude` and `include` in `deno.json` in favor of a unified `files` key". Issue 22482.

**Comment by petamoriken** [comment]
How about actually turning them off when the DENO_FUTURE env is enabled? #22318

**Comment by iuioiua** [comment]
> How about actually turning them off when the DENO_FUTURE env is enabled? #22318

Yes, that is the current plan 🙂

**Comment by iuioiua** [comment]
Update: `Deno.run()` and `Deno.serveHttp()` will no longer be removed in Deno v2. I've updated the list accordingly.

**Comment by iuioiua** [comment]
According to [Deno Deploy's API reference](https://docs.deno.com/deploy/api/), none of these APIs exist on Deno Deploy. I suggest we proceed with these removals, starting with being included in Deno 2 RC.

**Comment by lucacasonato** [comment]
For `--unstable`: keep the flag, change it to do nothing at all and print out a warning that it's not doing anything.

**Comment by iuioiua** [comment]
All done now 🙂
