### ISSUE TITLE
"deno upgrade" should check if it was installed using "homebrew"

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#22095]
Calling `deno upgrade` is notoriously problematic for people who have installed `deno` using `homebrew`.

It often results in "Permission denied" errors when `deno upgrade` tries to replace binary in `/opt/homebrew`.

We should check `std::env::current_exe()` and print a helpful message if Deno was installed using `homebrew`. Something along the lines of:
```
deno was installed using homebrew.

You can upgrade to never version using homebrew:
  brew upgrade deno

Alternatively you can reinstall deno without homebrew:
  brew uninstall deno
  // on Unix
  curl -fsSL https://deno.land/install.sh | sh
  // on Windows
  irm https://deno.land/install.ps1 | iex
```

**Comment by Sparkenstein** [comment]
brew deno formulae is build without the `upgrade` feature but. If you try to upgrade, you will get the following error

![image](https://github.com/denoland/deno/assets/24642451/690d1ee4-2d4a-48b9-a0c6-f4ae33492277)

I am on the latest CLI not sure if what you are describing is some older behavior.
