### ISSUE TITLE
[docs] a few broken links on both website and wiki

### ISSUE THREAD

**Issue by Sparkenstein** [denoland/deno#22098]
The wiki section on deno github has a few broken links:
 - API section redirects to https://deno.land/api but it doesn't show anything. Error: "This version does not exist."
 - Same error even if you go from deno.land -> Docs -> API reference
 - Wiki -> Product has a link "[Read more about what makes Deploy incredibly fast](https://deno.com/blog/anatomy-of-a-cloud)."  which should go to https://deno.com/blog/anatomy-isolate-cloud I believe but it points to /blog/anatomy-of-a-cloud
 - Wiki -> Contributing is broken. it takes to https://docs.deno.com/runtime/manual/contributing. But it should point to  https://docs.deno.com/runtime/manual/references/contributing/

**Comment by kt3k** [comment]
Thanks for reporting! These issues should be fixed now.
