### ISSUE TITLE
Cryptic _computedKey & out of bounds error after upgrading to 1.40.0

### ISSUE THREAD

**Issue by RobertCraigie** [denoland/deno#22109]
Hi! I'm a maintainer of [openai-node](https://github.com/openai/openai-node), which uses a build script to automate converting the TypeScript source to deno-specific code, the output of which can be found here: https://github.com/openai/openai-deno-build.

Starting with Deno v1.40.0, running `deno run mod.ts` produces this error:

```
error: Uncaught (in promise) ReferenceError: _computedKey is not defined
Warning Couldn't format source line: Column 42 is out of bounds (source may have changed at runtime)
    at file://openai-node/deno/lib/ChatCompletionStream.ts:15:42
```

The mentioned line only has 41 columns and nowhere in the codebase do we reference a `_computedKey` symbol.

Downgrading to `v1.35.1` (I haven't tested other versions) fixes the error.

I don't see anywhere that we would be modifying the source at runtime, any ideas?

### Steps to reproduce

```sh
$ deno upgrade --version=1.40.0
$ git clone https://github.com/openai/openai-deno-build
$ cd openai-deno-build
$ deno run mod.ts
```

**Comment by bartlomieju** [comment]
CC @littledivy

**Comment by jollytoad** [comment]
This is also happening to me as a user of openai-deno. (https://deno.land/x/openai@v4.26.0/)
I can definitely confirm this is just happening since the 1.40.x upgrade, was using 1.39.4 yesterday fine, and have now had to downgrade, which btw is pretty easy using the `upgrade` cmd if you get stung by this too...

`deno upgrade --version 1.39.4`

**Comment by littledivy** [comment]
Interesting :thinking: 

We don't have any symbol named `_computedKey` in Deno internals. This seems like something generated by SWC for the Decorators proposal. Ref https://github.com/swc-project/swc/issues/8551

cc @dsherret

**Comment by nberlette** [comment]
This error has made the Deno v1.40+ CLI complete unusable for me. I've had to downgrade back to 1.39.4 just to run some benchmarks.

**Comment by david-crespo** [comment]
Not fixed in 1.40.3 despite [SWC bump](https://github.com/denoland/deno/pull/21718).

**Comment by dsherret** [comment]
We probably just need to upgrade swc (https://github.com/swc-project/swc/issues/8551). I'll do that sometime this week

**Comment by jollytoad** [comment]
This seems to have been fixed in Deno CLI 1.40.5, but is now manifesting in Deno Deploy.

**Comment by simon-archer** [comment]
Experiencing a similar issue, but different error message. Not able to deploy my deno site using deno deploy, just receiving this error: 

`{"type":"error","code":"deploymentFailed","ctx":"The deployment failed: UNCAUGHT_EXCEPTION\n\nReferenceError: _computedKey is not defined\n    at https://deno.land/x/openai@v4.25.0/lib/ChatCompletionStream.ts:4:14"}`

Does not work on latest CLI 1.41.0, nor version 1.39.4 as suggested above.

**Comment by nberlette** [comment]
Yup, I've ran into the same roadblock with Deno Deploy this morning and can't seem to get it resolved. I don't get the error when I run the code locally on  v1.41.0, however. But as soon as I try to deploy it the entire deployment fails, currently causing it to be stuck in a broken state. Really frustrating.

**Comment by jollytoad** [comment]
If yout problem is specifically with OpenAI, I found I could work-around by switching to "npm:openai", although I'd very much like to switch back to all Deno native packages once the root issue is fixed across CLI and Deploy.

**Comment by nberlette** [comment]
Nice, that's a clever workaround for the time being. Unfortunately I'm encountering this problem with a different module that I published to deno.land myself... and it's a deno-only project so I can't use the npm: alternative 😖

**Comment by bartlomieju** [comment]
The fix is now deployed to production and available on Deploy. Sorry for the problems.

**Comment by nberlette** [comment]
Thank you guys for prioritizing this fix. Getting this notification just made my night
