### ISSUE TITLE
`deno compile --env` does not work

### ISSUE THREAD

**Issue by littledivy** [denoland/deno#22105]
According to https://github.com/denoland/deno/commit/f8f4e776325efe0d8dd50207beecb425f0875999

> This change adds the `--env=[FILE]` flag to the `run`, `compile`,
`eval`, `install` and `repl` subcommands.

but running `deno compile --env main.ts && ./main` prints `undefined`:

```ts
console.log(Deno.env.get('TEST'))
```

The behaviour should be either:
1. `deno compile --env` loads env variables from host and restores it when the binary is started.
2. `deno compile --env` loads the env variables from the user when the binary is started.

I'd personally prefer 1

**Comment by HasanAlrimawi** [comment]
Hello @littledivy ,
I'd like to investigate this issue if it has not been resolved yet....

**Comment by lino-levan** [comment]
@dsherret this should probably be closed now

**Comment by littledivy** [comment]
Fixed with https://github.com/denoland/deno/pull/24166. Thanks @HasanAlrimawi
