### ISSUE TITLE
Ability to suppress deprecation warnings in remote modules

### ISSUE THREAD

**Issue by jtoppine** [denoland/deno#22119]
Starting from Deno 1.40 we started getting hundreds warnings from the use of deprecated API's. While the warnings are a good feature to have, users can't really expect third party libraries to release updated versions right away - it might take weeks or more. 

Meanwhile, the flood of messages can make unit test output really hard to read, or cause them to overflow the console scrollback buffer. Some users redirect output to log databases etc, which can now grow uncontrollably. 

I think we need a way to specifically suppress the deprecation warnings that originate from third party (remote) libraries. `--quiet` might work to disable the warnings altogether, but that would suppress also the useful warnings about first party code the user does have direct control over (as well as other possibly useful messages unrelated to deprecation warnings).

**Comment by bartlomieju** [comment]
Does https://github.com/denoland/deno/pull/22128 solve this problem for you?
