### ISSUE TITLE
Symbol.metadata is undefined

### ISSUE THREAD

**Issue by sant123** [denoland/deno#22111]
Version: Deno 1.40.1

![image](https://github.com/denoland/deno/assets/7959437/d8a21f0d-cb06-4b84-9451-1312f64ab330)

Thanks.

**Comment by crowlKats** [comment]
What are you expecting this would do? No browser, nor node, implement a `Symbol.metadata`.

**Comment by sant123** [comment]
Consider this example:

```ts
function bind(_: unknown, ctx: ClassMethodDecoratorContext<any>) {
  ctx.addInitializer(function () {
    this[ctx.name] = this[ctx.name].bind(this);
  });
}

class Person {
  constructor(private firstName: string, private lastName: string) {}

  @bind
  greet() {
    console.log(`Hellou ${this.firstName} ${this.lastName}`);
  }

  @bind
  static start() {
    console.log("Hello World!", this);
  }
}

Person.start();
```

It prints: 

![image](https://github.com/denoland/deno/assets/7959437/80514748-6fe6-4baf-812b-5505aae026ba)

Perhaps it should print the empty object shown in the console meanwhile?

**Comment by bartlomieju** [comment]
I also don't understand what's the problem here. Where is the `Symbol(Symbol.metadata)` coming from in your example?

**Comment by sant123** [comment]
It comes directly from the runtime, so the metadata exists but is not exposed? I got curious about that data in the console.

**Comment by Jamesernator** [comment]
> I also don't understand what's the problem here. Where is the `Symbol(Symbol.metadata)` coming from in your example?

`Symbol.metadata` is part of [decorator metadata](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-2.html#decorator-metadata), the use of any decorators on a class add the object.

> What are you expecting this would do? No browser, nor node, implement a Symbol.metadata.

Given Deno supports decorators in TypeScript it should expose the symbol, Deno already supports `Symbol.dispose`/`Symbol.asyncDispose` which are from another proposal not implemented in browsers either.

**Comment by lucacasonato** [comment]
Yeah, I checked and SWC does transpile decorator metadata. We should polyfill `Symbol.metadata` like we do for `Symbol.dispose`
