### ISSUE TITLE
bug: cannot determine if a file is a file

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#22115]
Version: Deno 1.40.0

This has broken oak (when attempting to calculate etags) and I suspect it will break a lot of other code:

```
❯ deno
Deno 1.40.0
exit using ctrl+d, ctrl+c, or close()
REPL is running with all permissions allowed.
To specify permissions, run `deno repl` with allow flags.
> const file = await Deno.open("./fixtures/test.jpg");
undefined
> file
FsFile {}
> file instanceof Deno.FsFile;
false
```

**Comment by bartlomieju** [comment]
Sorry for that, I opened https://github.com/denoland/deno/pull/22121 that will fix this problem. It will be released in v1.40.2.
