### ISSUE TITLE
`temporal` doesn't work in `deno.json`'s `unstable` field

### ISSUE THREAD

**Issue by RuiNtD** [denoland/deno#22123]
Version: Deno 1.40.1

Despite having `temporal` set in the `unstable` field in my `deno.json`, `Temporal` is undefined and requires me to provide `--unstable-temporal`.

```json
{
  "unstable": ["temporal"]
}
```
```ansi
error: Uncaught (in promise) ReferenceError: Temporal is not defined
  return Temporal.Duration.from(ttl).total({
  ^
```

**Comment by bartlomieju** [comment]
Thanks for reporting. You hit a jackpot of complexity here! I didn't test this scenario explicitly and it turns out it's really hard to fix. That said, I'll think of a solution to fix it in v1.40.2.

**Comment by RuiNtD** [comment]
You might want to see about refactoring the code a bit so that config.json unstable flags and CLI unstable flags are always defined in the same place.

**Comment by bartlomieju** [comment]
> You might want to see about refactoring the code a bit so that config.json unstable flags and CLI unstable flags are always defined in the same place.

That would be ideal, but various unstable features need to be initialized at different stages of the program lifetime - eg. `temporal` needs to be initialized at the very beginning, when we tell V8 that we're gonna start up. Sadly at the moment figuring out which features are enabled in config file happens way later, than initialization of V8.

**Comment by irbull** [comment]
I had a bit of time this evening so I thought I'd take a look, and you're right this is pretty complex. The `feature_checker` does have the right flags set, whether you use `--unstable-temporal` or a `deno.json` file. 

What I'm unclear about is why is this particular flag different from `cron` or any of the other APIs. It seems to be configured in a different way than the other unstable APIs: https://github.com/denoland/deno/blob/main/runtime/lib.rs#L92.

**Comment by bartlomieju** [comment]
> > That's because we need to pass a proper CLI flag to V8 to make this API available. All the other unstable APIs are our own APIs that we can enable/disable when we bootstrap the runtime. For temporal, this needs to happen before we even create a first V8 instance.
> 
> So this is more of a V8 Flag then? I guess none of the other V8 flags can be specified in a `deno.json` file, right?

`--unstable-temporal` is a Deno flag. To activate `Temporal` API we need to pass `--harmony-temporal` flag to V8 on startup. That's correct, other V8 flags can be specified only using `--v8-flags=...` CLI flag.

> If that's the case, is there a reason why we can't process the `deno.json` file early in the startup process? Is it a performance thing or does the processing of the file require V8 (it seems to be done in Rust, but there could be calls into V8 that I'm not seeing).

We can do that, but it requires some bigger refactor that I'm working on right now.

**Comment by RuiNtD** [comment]
> We can do that, but it requires some bigger refactor that I'm working on right now.

It also requires processing JSONC in Rust, btw.

**Comment by bartlomieju** [comment]
> > We can do that, but it requires some bigger refactor that I'm working on right now.
> 
> It also requires processing JSONC in Rust, btw.

I'm not sure what you mean. Configuration files already support JSONC.

**Comment by RuiNtD** [comment]
> > > We can do that, but it requires some bigger refactor that I'm working on right now.
> > 
> > 
> > It also requires processing JSONC in Rust, btw.
> 
> I'm not sure what you mean. Configuration files already support JSONC.

Sorry, I just assumed JSONC was handled [in JavaScript](https://deno.land/std/jsonc/mod.ts) and not in Rust.
