### ISSUE TITLE
WebGPU errors are not reported

### ISSUE THREAD

**Issue by littledivy** [denoland/deno#22146]
Failures are not reported to the user and lets the program sliently proceed. This is true for shader creation, pipeline and pipeline layout creation as well as device queue submission.

It's not possible to debug without re compiling Deno with a println in `gfx_put!` and `gfx_ok!` macros.

**Comment by crowlKats** [comment]
no, thats not a viable solution. errors are mostly handled correctly, however the API sucks, and `pushErrorScope` & `popErrorScope` should be used for error handling

**Comment by littledivy** [comment]
Ok, I think we still need to implement `getCompilationInfo` for shader errors

**Comment by crowlKats** [comment]
shader errors should already show up in error scopes.

**Comment by crowlKats** [comment]
also, `getCompilationInfo` is blocked by upstream wgpu.

**Comment by sudokit** [comment]
Anything?

**Comment by crowlKats** [comment]
@sudokit are you using the `pushErrorScope` & `popErrorScope` APIs and not getting any errors? if so, could you share the code?

**Comment by sudokit** [comment]
I had no idea those existsed!? No idea on how to use them either :p. I assume something like `device.pushErrorScope("validation");` for example, and then it should error on invalid shader code when calling `device.createShaderModule` for example? Might have understood it wrongly. Something like this, i guess?
```typescript
async getModule(device: GPUDevice): Promise<Result<GPUShaderModule, Error>> {
  let code;
  code = await this.getCode();
  if (code.isErr()) return Err(code.unwrapErr());
  code = code.unwrap();
  device.pushErrorScope("validation");
  const shaderModule = device.createShaderModule({ code: code });
  device.popErrorScope(); // would error?

  return Ok(shaderModule);
  }
```

**Comment by crowlKats** [comment]
ok so this is something I dont 100% understand either, but i believe it is as follows:

> can you just push it once and then pop errors as they come?

yes

> And do you need to pop errors after every operation, or else they stack up

they stack up

however, you need to a scope for every time you might pop an error scope

**Comment by sudokit** [comment]
Ah so everytime you might want to check for an potential error, you need to push a scope... And do they stack up even if you dont push a scope?
And yeah figured that it returned the error. So changed it to `const err = await device.popErrorScope();`

**Comment by yudshj** [comment]
Wrapping my code within an error scope solves the issue for me. Here's how I did it:

```rust
await device.pushErrorScope("validation");
const shaderModule = device.createShaderModule({
  code: "<foo bar>",
});
const error = await device.popErrorScope();
console.log(error);
```

**Comment by littledivy** [comment]
Closing the issue because the (awkward) error management is intended as per spec
