### ISSUE TITLE
AbortController + Deno.cron on v1.40.0 = Impossible to kill with Cmd + C

### ISSUE THREAD

**Issue by BlackAsLight** [denoland/deno#22142]
Version: Deno 1.40.0

v1.40.0 of Deno removed the overload to pass an abort signal to `Deno.cron` https://github.com/denoland/deno/pull/22035 and in doing so when listening for the 'SIGINT' event to call `controller.abort()` to implement a graceful shutdown, the `Deno.cron` now never shuts down. 
```ts
const controller = new AbortController()
Deno.addSignalListener('SIGINT', () => controller.abort())
Deno.cron('ABC', '* * * * *', () => console.log('Hello World'))
```
In my main project I am also using Oak and when starting it up it seems to create three instances of Deno. Instead of the terminal hanging like you'd see with the above example code, it would gracefully exit two of the three instances and leaving one instance abandoned and alone, existing in the background.

Is there another way I am meant to remove these `Deno.cron` for a graceful shutdown? I am able to simply call `Deno.exit()` in the example code event listener, but in doing so remove the word graceful from graceful shutdown.

**Comment by kt3k** [comment]
#22035 removed an overload `cron(name, schedule, handler, options)`, but there is still `cron(name, schedule, options, handler)`. You can still do the below:

```js
const controller = new AbortController()
Deno.addSignalListener('SIGINT', () => controller.abort())
Deno.cron('ABC', '* * * * *', { signal: controller.signal }, () => console.log('Hello World'))
```

**Comment by BlackAsLight** [comment]
Oh. I didn't realise it was essentially just switched around.
