### ISSUE TITLE
deno install --unstable-kv don't work

### ISSUE THREAD

**Issue by thomas3577** [denoland/deno#22154]
Version: Deno 1.40.2

When I try to install an app that uses Deno.KV and then run it, I get the following error message:

`Uncaught (in promise) TypeError: Deno.openKv is not a function.`

**Minimal example (main.ts):**
```TypeScript
await Deno.openKv();
```

**Install**
```bash
deno install --unstable-kv -n mycli ./main.ts
```

**Run**
```bash
mycli
error: Uncaught (in promise) TypeError: Deno.openKv is not a function
await Deno.openKv();
           ^
```

**Comment by zefhemel** [comment]
Yep, just noticed the same. Falling back to use `--unstable` for now (with a warning, but at least it works).
