### ISSUE TITLE
question: should `Deno.ChildProcess` have `read()` and `write()` methods?

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno#22159]
`Deno.FsFile` and `Deno.Conn` have `read()` and other such I/O methods. However, for some reason, `Deno.ChildProcess` doesn't. Is there a reason why this is the case? I know that `Deno.ChildProcess` was implemented later and is not bound to backward compatibility concerns. I think that these I/O APIs should be consistent in this regard.

**Comment by crowlKats** [comment]
This was a conscious decision because we wanted to move away from the deno streams

**Comment by iuioiua** [comment]
Why move away from Deno streams in some APIs but not others? Genuine question. Also, is there a means for sync read/write for `Deno.ChildProcess`?

**Comment by iuioiua** [comment]
Closing as we don't want to proliferate the use of Deno streams.
