### ISSUE TITLE
--unstable-net doesn't enable createHttpClient

### ISSUE THREAD

**Issue by Joel-PeakMetrics** [denoland/deno#22155]
Version: Deno 1.40.2

Using this method fails with --unstable-net. It does work with --unstable though. Is there a different unstable flag for this method?
https://deno.land/api@v1.40.2?unstable=&s=Deno.createHttpClient

**Comment by bartlomieju** [comment]
`--unstable-http` enables it. We need to update the docs.

**Comment by Joel-PeakMetrics** [comment]
Confirmed, that worked! Thanks!
