### ISSUE TITLE
console.log({ a: string }) only prints 100 characters

### ISSUE THREAD

**Issue by e3dio** [denoland/deno#22160]
Version: Deno 1.40.2

Logging an object only prints the first 100 characters of any strings in the object. This default needs to be higher. I see there is [Deno.inspect](https://deno.land/api@v1.40.2?s=Deno.inspect) but I'd rather not call `console.log(Deno.inspect(value, { colors: true, strAbbreviateSize: 1000 }))` every time I need to log to console. Node.js displays 10,000 characters. 1,000 would be better than 100.

```js
console.log({ a: 'x'.repeat(150) });

{
  a: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"... 50 more characters
}
```

```js
console.log(Deno.inspect({ a: 'x'.repeat(150) }, { colors: true, strAbbreviateSize: 1000 }));

{
  a: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
}
```

**Comment by e3dio** [comment]
Guys... this is terrible. Only printing 100 characters of a string that you explicitly told the console to log is incomprehensibly bad.

I have a question.. does ANYONE here actually support the idea of only printing 100 characters with console.log ? Please speak up if you do. I'd love to hear your reasoning. Please explain to me why I only deserve to see 100 characters of a string I just told the console to log. PLEASE explain this to me. Thank You.

**Comment by littledivy** [comment]
A max length is set to prevent large string output from being too overwhelming. 

I agree, let's update `maxStringLength` to 10_000. Ref: https://github.com/nodejs/node/pull/32744

**Comment by e3dio** [comment]
Here are screenshots of 1,000 and 10,000 characters. 1,000 takes up only a couple lines of terminal. 10,000 takes up a little bit more. At the very least I'd be happy with 1,000 which is about 10 times better than the current 100 lines! I'd probably take 10,000 too just to display all the information as default

**1,000:**

![image](https://github.com/denoland/deno/assets/85405955/6cddf464-0be6-4229-9b34-0e1279567437)

**10,000:**

![image](https://github.com/denoland/deno/assets/85405955/b88b4573-2cce-4218-a5ef-ae5331e4e552)

**Comment by e3dio** [comment]
I have a lot of different code running, 10 terminals on a 4k monitor, all of them logging various things, very often objects with strings, and EVERY SINGLE TIME I have an object with string that I NEED TO SEE I get the dread "x more characters" message and I wonder what exactly these people were thinking to only allow 100 characters in a string. These people must not work with console output or do anything serious

**Comment by littledivy** [comment]
> what exactly these people were thinking

> These people must not work with console output or do anything serious

@e3dio You are violating our [Code of Conduct](https://github.com/denoland/deno/blob/main/.github/CODE_OF_CONDUCT.md):

- Please be kind and courteous. There’s no need to be mean or rude.
- Respect that people have differences of opinion and that every design or implementation choice carries a trade-off and numerous costs. There is seldom a right answer.
- We will exclude you from interaction if you insult, demean or harass anyone. That is not welcome behavior.

@jtoppine provided meaningful answers to why "x more characters" is useful and logging full objects should use `JSON.stringify`.

That said, we will accept PRs that bump the current default limit to `10_000`.

**Comment by oles** [comment]
I also experienced this issue right now.

![Screenshot from 2024-05-04 19-26-22](https://github.com/denoland/deno/assets/7634050/e8b444ef-db01-4616-90f6-57677f4213bf)

This is part of the object logged from a `console.warn`, and I found it both unexpected and strange that it cut off that early.

Luckily the search term "deno prevent console.log truncation" returned this issue as the second result!

I'd really like to see the `maxStringLength` increased, as I'd like to keep my logging utility both simple and portable.

@littledivy I'm not sure what happened with the PRs, but it seems the newest opened one is ready to go?
If it isn't, please let me know - and I'll look into creating a PR myself :v:
