### ISSUE TITLE
suggestion: move `Deno.flock()` and friends

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno#22178]
I suggest we remove the following APIs in favour of new `Deno.FsFile` methods:
1. `Deno.flock()` > `Deno.FsFile.lock()`
2. `Deno.flockSync()` > `Deno.FsFile.lockSync()`
3. `Deno.funlock()` > `Deno.FsFile.unlock()`
4. `Deno.funlockSync()` > `Deno.FsFile.unlockSync()`

The reasoning is the same as other recent deprecations; they accept `rid` parameters, and we want to make these private.

Alternatively, if these aren't seen as useful, we can remove them. We should be fine to move or remove them, as they are part of the unstable API.

**Comment by bartlomieju** [comment]
This seems reasonable 👍 we should add new methods to `Deno.FsFile` and mark them unstable; in the next minor release mark the new APIs as stable, and the old APIs as deprecated.

**Comment by iuioiua** [comment]
Cool. Please assign this issue to me.
