### ISSUE TITLE
`deno coverage` should have a built-in file output option

### ISSUE THREAD

**Issue by vadimvera** [denoland/deno#22215]
Currently, `deno coverage` lacks a built-in option to specify the output file. As a result, we resort on using output redirection via shell commands to save the output to a file — leading to inconsistencies across platforms and making scripting more cumbersome.

```shell
$ deno coverage reports/coverage/ --lcov > reports/coverage/lcov.info
```

Adding a built-in file output option to `deno coverage` will remove this inconvenience, making it truly portable because the command will handle the file writing internally, providing users with a standardized and convenient way to specify the output file directly within the command itself, without relying on shell redirection.

```shell
$ deno coverage reports/coverage/ --lcov --output=reports/coverage/lcov.info
```

**Comment by bavoco** [comment]
What you are suggesting already exists, check:
```shell
deno coverage --help
```
