### ISSUE TITLE
Possible to define globals?

### ISSUE THREAD

**Issue by mrkurt** [denoland/deno#2222]
I'm using some external libraries that expect certain globals (related to #2108). Can I define new globals in my `main` somehow?

**Comment by kitsonk** [comment]
Either reference `globalThis` or `window`, or indirect `eval` to access the global scope.  To define additional globals in TypeScript you have to utilise the global namespace to add the types, for example:

```ts
declare global {
  something: string;
}
```

**Comment by mrkurt** [comment]
Ah `globalThis` did it! Thanks.

**Comment by ry** [comment]
@mrkurt do you have a patch for exposing Request/Response? I spent a moment trying to to expose these but got hung up...

**Comment by mrkurt** [comment]
@ry I don't! I also looked for a bit, and realized there's more missing than I thought. I'm working on running the ones we use for fly.io to see how they are, it's possible they'd be good options to include in deno — although your `FormData` is better: 

https://github.com/superfly/fly/blob/master/packages/v8env/src/body_mixin.ts
https://github.com/superfly/fly/blob/master/packages/v8env/src/request.ts
https://github.com/superfly/fly/blob/master/packages/v8env/src/response.ts
