### ISSUE TITLE
suggestion: implement `Deno.FsFile.isTerminal()`

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno#22229]
In the case that someone does something like `Deno.open("/dev/tty6")`.

**Comment by bartlomieju** [comment]
Seems reasonable, we should implement for the sake of libraries like `cliffy` 👍

**Comment by iuioiua** [comment]
Cool. Please assign this issue to me.

**Comment by dsherret** [comment]
Maybe also `setRaw`?

**Comment by iuioiua** [comment]
Ah, good catch. I'll do that too.
