### ISSUE TITLE
suggestion: finalize replacements for `Deno.fdatasync[Sync]()` and `Deno.fsync[Sync]()`

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno#22230]
The following I/O APIs should be replaced with `Deno.FsFile` methods. This has partially been done already. However, we haven't been able to finalize the new API names, as indicated in #22085.
1. `Deno.fdatasync[Sync]()` (currently `Deno.FsFile.syncData[Sync]()`)
2. `Deno.fsync[Sync]()` (currently `Deno.FsFile.sync[Sync]`)

**Comment by dyedgreen** [comment]
Are there any plans for stabilizing these (and the file locking) APIs?

This is blocking deno sqlite from upgrading to the new API: https://github.com/dyedgreen/deno-sqlite/pull/259

**Comment by iuioiua** [comment]
We're stabilizing these APIs in the next minor release in #23733.
