### ISSUE TITLE
add `Deno.Transpiler`

### ISSUE THREAD

**Issue by terrablue** [denoland/deno#22249]
Hi, would it be possible to add a programmatic way to transpile ts/jsx files? Bun has `Bun.Transpiler`, but as far as I can see in the docs, Deno only supports CLI transpiling.

Would be great if it could be exposed!

**Comment by dsherret** [comment]
See https://github.com/denoland/deno_emit where you can depend on a versioned API.

**Comment by terrablue** [comment]
Thanks. I'm not entirely sure what's the benefit of using `deno_emit` over esbuild?

My concern is mostly about performance, as `Bun.Transpiler` is faster than esbuild. I'm looking for something in the order of magnitude of esbuild/SWC. In my understanding, running `deno run module.ts` uses SWC internally, would it not be faster to expose that? Or does deno plan to remove the ability to transpile TS/JSX/TSX files?
