### ISSUE TITLE
Formatting `Temporal` with `Intl.DateTimeFormat` should exclude `undefined` fields in formatting

### ISSUE THREAD

**Issue by bdevos** [denoland/deno#22256]
Version: Deno 1.40.2

When using `Intl.DateTimeFormat` with a Temporal value, the formatter is not working as expected by including fields that are left `undefined`.

With the following code:
```
const dfmt = new Intl.DateTimeFormat('en-US', {
    month: 'short',
    day: 'numeric',
  })

  const one = dfmt.format(new Date())
  const two = dfmt.format(Temporal.Now.plainDateISO())
  const three = dfmt.format(Temporal.Now.plainDateTimeISO())

  console.table({ one, two, three })
```

The output is:
```
┌───────┬────────────────────────────┐
│ (idx) │ Values                     │
├───────┼────────────────────────────┤
│ one   │ "Feb 4"                    │
│ two   │ "Feb 4, 2024"              │
│ three │ "Feb 4, 2024, 10:18:03 AM" │
└───────┴────────────────────────────┘
```

I would expect both `two` and `three` to equal the output of `one`.

The formatter does not seem to exclude any fields in the output that are `undefined`.

Maybe I shouldn't be posting issues here about `--unstable-temporal`, or this is already known. But could not find the issue yet, so hopefully this is helpful.

**Comment by bdevos** [comment]
Wanted to follow up that I can reproduce the issue with the latest version: 1.42.4

**Comment by petamoriken** [comment]
This is V8 issue

**Comment by bdevos** [comment]
Closing issue because it is not a Deno problem.
