### ISSUE TITLE
Return value of class decorator is ignored when executing line-by-line in the REPL

### ISSUE THREAD

**Issue by nicolo-ribaudo** [denoland/deno#22266]
Version: Deno 1.40.3

```js
@(() => class A { a() { console.log("OK") } }) class B {}

let x = new B(); x.a();
```

If you execute these two lines one-by-one in the REPL, the `x.a()` call should log "OK", but it throws. If you execute all of them at the same time, it works.

**Comment by nicolo-ribaudo** [comment]
I'm opening these issues here in Deno and not in SWC because I see different behavior. For example, when compiling this code in the SWC online playground and then execute it I get an error about `B` not being defined in `new B()`.

**Comment by lucacasonato** [comment]
This is too complex to fix - I'll close this for now. It'll be fixed when decorators ship in V8 proper.
