### ISSUE TITLE
Rewrite flags.rs::parse_flags

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#2227]
With recent numerous changes to CLI and more to come (#2213, #2215) I found myself in situation when it's harder and harder to properly test CLI parsing logic and not break anything.

That's why I'd like to propose yet another rewrite to:
https://github.com/denoland/deno/blob/40d8ef1ec9f5e50017c41af8bf3b9f8454f97544/cli/flags.rs#L134

Currently it only returns `DenoFlags` and choosing the actual subcommand and construction of argument array that is passed to script in done in `main.rs`. That's not elegant, and logic is split into multiple files and makes it impossible to properly test all entry points.

As previously suggested in [#2157](https://github.com/denoland/deno/pull/2157#discussion_r277167448) it should be `flags_from_vec` that is only public function in `flags.rs` that takes care of parsing of CLI flags and choosing appropriate action.

So my proposition is to change what's returned from this function to:
```rust
enum DenoSubcommand {
   Fmt = "fmt",
   Info = "info",
   Types = "types",
   Fetch = "fetch",
   Repl = "repl",
   Run = "run",
}

// last parameter is `rest_argv` which is passed down 
// to script and available as Deno.args
fn flags_from_vec(args: Vec<String>) -> (DenoFlags, DenoSubcommand, Vec<String>)
```

Then we'll be able to nicely test everything:
```rust
  #[test]
  fn test_set_flags_x() {
    let cli_args = svec!["deno", "-r", "-D", "run", "script.ts", "--foo", "bar", "bazz"];
    let (flags, cmd, args) = flags_from_vec(cli_args);
    assert_eq!(cmd, DenoSubcommand::Run);
    assert_eq!(args, svec!["deno", "script.ts", "--foo", "bar", "bazz");
    assert_eq!(
      flags,
      DenoFlags {
        log_debug: true,
        reload: true,
        ..DenoFlags::default()
      }
    );
  }
```

With `DenoSubcommand` there will be simple `match` on it in `main.rs` that basically selects function to call, as `DenoFlags` and script `args` will be already parsed.

CC @ry

**Comment by ry** [comment]
SGTM
