### ISSUE TITLE
`deno init` should add name, version and exports fields to `deno.json`

### ISSUE THREAD

**Issue by littledivy** [denoland/deno#22287]

**Comment by muddlebee** [comment]
@littledivy would like to work on this 👀

**Comment by littledivy** [comment]
sure!

**Comment by muddlebee** [comment]
@littledivy 

so if I run the command `deno init test`
something like below should appear in deno.json. correct?

```
{
  "name" : "test",
  "version": "1.0.0",
  "imports": {},
  "tasks": {
    "dev": "deno run --watch main.ts"
  }
}
```

but if `deno init` only then the new fields(name) should be empty?
```
{
  "name" : "",
  "version": "1.0.0",
  "imports": {},
  "tasks": {
    "dev": "deno run --watch main.ts"
  }
}
```

**Comment by muddlebee** [comment]
I am thinking of the approach in codebase, to keep the deno init json template like below and overwrite with the `dir` option from the `deno init <dir>` command. original code [here](https://github.com/denoland/deno/blob/main/cli/tools/init/mod.rs#L52) 

```
{
  "name" : "{{name}}", 
  "version": "1.0.0",
  "imports": {},
  "tasks": {
    "dev": "deno run --watch main.ts"
  }
}
```

**Comment by littledivy** [comment]
Sounds good. This can be the template JSON:

```json
{
  "name": "{{name}}", 
  "version": "0.1.0",
  "exports": {},
  "tasks": {
    "dev": "deno run --watch main.ts"
  }
}
```

Also note that If `dir` is not provided it should use the current working directory name.

**Comment by dsherret** [comment]
Maybe we should only do this when running something like `deno init --lib`? Not everyone will be developing a library so probably `deno init` shouldn't do this by default. For example, when adding all threee of these fields then someone will get opted into library only lint rules like `no-slow-types`, which is not necessary for applications.

**Comment by bartlomieju** [comment]
> Maybe we should only do this when running something like `deno init --lib`? Not everyone will be developing a library so probably `deno init` shouldn't do this by default. For example, when adding all three of these fields then someone will get opted into library only lint rules like `no-slow-types`, which is not necessary for applications.

Exactly my thought, +1 for `--lib`.

**Comment by muddlebee** [comment]
I have done the changes as per comments above :point_up:  and added some unit tests.

**Comment by muddlebee** [comment]
added some changes to the `deno init` docs https://github.com/denoland/deno-docs/pull/345/files
