### ISSUE TITLE
suggestion: improve `deno publish --dry-run` success message

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno#22285]
Currently, when `deno publish --dry-run` is complete, "Warning Aborting due to --dry-run" is printed. I think this would be unclear to newcomers that the dry run has succeeded. Perhaps, we could instead print something like "Success Dry run has completed".

**Comment by bartlomieju** [comment]
But `--dry-run` should always exit with code 1, and the message matches what Cargo prints.

**Comment by dsherret** [comment]
I agree with @iuioiua. We can improve on cargo. Also, how would someone use this on a CI easily if it always returns exit code 1 on success and failure? Maybe we shouldn't exit with code 1?

**Comment by HasanAlrimawi** [comment]
I reproduced it, and the exit_code is 0 not 1.
I observed the exit code from `main.rs` `pub fn main()`.

So I think it's just a simple warning message update needed.
Is this the case?

**Comment by iuioiua** [comment]
> I reproduced it, and the exit_code is 0 not 1. I observed the exit code from `main.rs` `pub fn main()`.
> 
> So I think it's just a simple warning message update needed. Is this the case?

It completes successfully with exit code 0, and fails with exit code 1. I think this is correct, so yes, it seems we just need to improve the success message.
