### ISSUE TITLE
WebGPU working with shaders and errors

### ISSUE THREAD

**Issue by sudokit** [denoland/deno#22292]
Im not really sure what im exactly suggesting, but something to be able to work with sahders easier and clearer errors.
 
Currently if theres an error in the shaders, the program will just crash with an unclear error. ```Error: Invalid Surface Status``` or something like that. Could mean anything. 

So maybe something to be able to check shaders? Or better error handlig so you could check if there was an error and more clear errors. Could be that i just dont know how to handle errors :p (sorry this could also be the wrong place to suggest this)

EDIT: just found this issue related to the errors: #22146

**Comment by littledivy** [comment]
Yeah, its unfortunate we don't have error propogation set up yet. 

@crowlKats How about we add a `println` when an error occurs in the gfx_ok and gfx_put macros until this is solved?

**Comment by crowlKats** [comment]
Lets close in favour of #22146.
