### ISSUE TITLE
bug: Failed to publish @std/crypto@0.214.0

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno#22317]
When trying to publish `deno_std` to JSR, the process seems to stall towards the end when most of, if not all, the other sub-modules have been published besides `@std/crypto`. Then, I get the following error:
```
...
Successfully published @std/testing@0.214.0
Visit https://jsr.io/@std/testing@0.214.0 for details
error: Failed to publish @std/crypto@0.214.0

Caused by:
    0: Failed to publish @std/crypto at 0.214.0
    1: 413 Payload Too Large: 
       <html><head>
       <meta http-equiv="content-type" content="text/html;charset=utf-8">
       <title>413 Request Entity Too Large</title>
       </head>
       <body text=#000000 bgcolor=#ffffff>
       <h1>Error: Request Entity Too Large</h1>
       <h2>Your client issued a request that was too large.
       </h2>
       <h2></h2>
       </body></html>
        (unknown)
```
Could this be due to `std/crypto` being a Rust-based sub-module?

Platform:
```
deno 1.40.3+6c15dc3 (canary, aarch64-apple-darwin)
v8 12.1.285.6
typescript 5.3.3
```

Steps to reproduce:
1. Clone the main branch of the Deno Standard Library.
2. Go through the steps in https://github.com/denoland/deno_std/blob/main/.github/workflows/workspace_publish.yml

**Comment by lucacasonato** [comment]
How large is `@std/crypto`? Do you have a `target/` folder in there?

**Comment by iuioiua** [comment]
`crypto/_wasm/target` is 363.9 MB and constitutes almost 100% of the file size of `std/crypto`.

**Comment by lucacasonato** [comment]
Right - that folder should not be published. It is `.gitignore`'d

**Comment by iuioiua** [comment]
That worked! Thank you.
