### ISSUE TITLE
`deno publish` should fail if there are unstaged git changes

### ISSUE THREAD

**Issue by littledivy** [denoland/deno#22330]
And `--allow-dirty` to bypass this. Similar to `cargo publish`.

**Comment by muddlebee** [comment]
picking this up. :eyes:

**Comment by bartlomieju** [comment]
@muddlebee are you working on this issue?

**Comment by muddlebee** [comment]
> @muddlebee are you working on this issue?

@bartlomieju no. I was not able to figure out the use of `deno deploy`
