### ISSUE TITLE
[improve-typescript] Array `includes` method should have `unknown` type

### ISSUE THREAD

**Issue by ngdangtu-vn** [denoland/deno#22342]
Version: Deno `1.40.3`

![image](https://github.com/denoland/deno/assets/68631458/15362013-eb81-464b-bbcf-3177f28f506e)

The point of `include()` method is to check whether the variable is a part of the array. So what is the point to set the type of the `searchElement` as an item of that array? I think this doesn't make sense. My suggestion is setting `searchElement` to `unknown` type because we couldn't know what dev want to check.

**Comment by littledivy** [comment]
This is a design decision in TypeScript https://github.com/microsoft/TypeScript/issues/53275. We don't want to deviate from or change TypeScript - this should be raised in the TypeScript repo.
