### ISSUE TITLE
How import package from unpkg?

### ISSUE THREAD

**Issue by sonickseven** [denoland/deno#22364]
I'm using deno from 6 month ago and I missing can call labraries from simple import but when I try to call from for example:

[unpkg](https://unpkg.com/turf@3.0.14/turf.js?module)

But always show me error.

Exists one page when I can import popularity libs without necesity that use `<script scr="https...."></script>` ?

**Comment by littledivy** [comment]
> But always show me error.

What error do you get? Please provide a reproduction

**Comment by nberlette** [comment]
It seems the module `shapefile` doesn't provide a default export.

Have you tried using [`esm.sh`](https://esm.sh) to import it instead? I've personally never had any issues using their service, it's a very Deno-friendly CDN.

This import works fine for me:

```ts
import * as shapefile from "https://esm.sh/shapefile@0.6.6";
```

The imported `shapefile` namespace has the following methods available on it:

```ts
[Module: null prototype] {
  open: [Function: Z],
  openDbf: [Function: Wt],
  openShp: [Function: Rt],
  read: [Function: Xt]
}
```

Side note: if you're like me and those minified function names bother you, you can append a `?keep-names` query parameter to preserve the originals:

```ts
import * as shapefile from "https://esm.sh/shapefile@0.6.6?keep-names";

shapefile
[Module: null prototype] {
  open: [Function: open],
  openDbf: [Function: openDbf],
  openShp: [Function: openShp],
  read: [Function: read]
}
```

**Comment by lucacasonato** [comment]
Closing as @nberlette's answer resolves the original OPs issue.
