### ISSUE TITLE
HttpServer.finished accept vs reject

### ISSUE THREAD

**Issue by pihentagy** [denoland/deno#22366]
Version: Deno 1.40.4

Even when you abort the server with a signal, it resolves:

```ts
const ac = new AbortController();
const server = Deno.serve({ signal: ac.signal }, () => {
  setTimeout(() => ac.abort(), 0);
  return new Response("Hello");
});
try {
  await server.finished;
  console.log("Resolved");
} catch (_e) {
  console.log("Rejected");
}
```

But if you do a `HttpServer.shutdown` it will throw Interrupted:

```ts
const server = Deno.serve({}, () => {
  server.shutdown();
  return new Response("Hello");
});
try {
  await server.finished;
  console.log("Resolved");
} catch (_e) {
  console.log("Rejected");
}
```

unless you put `server.shutdown()` to a `setTimeout`.

The doc does not say the promise of `finished` could reject.
And `HttpServer.shutdown()` should shut down the server gracefully, right?

**Comment by mmastrac** [comment]
This definitely seems like a bug, and I wonder if we should specify that calling `abort()` will resolve the server with no exception, while calling `abort(reason)` will resolve the server with an exception.

I don't think we have sufficient testing around shutting the server down inside the handler closure.

**Comment by pihentagy** [comment]
Maybe related: https://github.com/denoland/deno/issues/22387

**Comment by iuioiua** [comment]
Both examples resolve successfully on my machine. @pihentagy, can you please upgrade and try again?
```
deno 1.44.4 (release, aarch64-apple-darwin)
v8 12.6.228.9
typescript 5.4.5
```

**Comment by pihentagy** [comment]
Thanks for the update.

Indeed, on 1.44.0 it throws the error.

But on 1.44.4 both are resolved successfully. :tada:
