### ISSUE TITLE
Temporal.PlainDate.prototype.add fails when providing a negative value

### ISSUE THREAD

**Issue by sant123** [denoland/deno#22373]
Version: Deno 1.40.4

Reading the [spec](https://tc39.es/proposal-temporal/docs/plaindate.html#add) the add method should support negative values.

> Adding a negative duration is equivalent to subtracting the absolute value of that duration.

Instead an error is thrown:

```ts
const birthday = Temporal.PlainDate.from({ year: 1995, month: 1, day: 27 });
console.log(birthday.add({ months: 3, days: -20 }));

```

![image](https://github.com/denoland/deno/assets/7959437/2a6f35b4-68d3-4ebe-9f4c-686ba49ff346)

Thanks!

**Comment by F3n67u** [comment]
Mixed-sign values not allowed as duration fields

Here is how [spec](https://tc39.es/proposal-temporal/#sec-temporal-isvalidduration) validate `Temporal.PlainDate.prototype.add`'s parameter:

> 7.5.16 IsValidDuration ( years, months, weeks, days, hours, minutes, seconds, milliseconds, microseconds, nanoseconds )
> 1. Let sign be 0.
> 2. For each value v of « years, months, weeks, days, hours, minutes, seconds, milliseconds, microseconds, nanoseconds », do
>    a. If [𝔽](https://tc39.es/ecma262/#%F0%9D%94%BD)(v) is not [finite](https://tc39.es/ecma262/#finite), return false.
>    b. If v < 0, then
>         i. If sign > 0, return false.
>         ii. Set sign to -1.
>    c. Else if v > 0, then
>         i. If sign < 0, return false.
>         ii. Set sign to 1

https://tc39.es/proposal-temporal/#sec-temporal-isvalidduration

**Comment by sant123** [comment]
Thanks @F3n67u for the link it makes sense now, also the error message should be different but certainly that will change when the Temporal API is stable.
