### ISSUE TITLE
doc html gen: broken documentation links for built-in runtime symbols 

### ISSUE THREAD

**Issue by nberlette** [denoland/deno#22370]
I'm running the latest canary build of v1.40.4. When I click on a built-in symbol such as `WritableStream`, the link that _should_ take me to [the correct page](https://deno.land/api@v1.40.4?s=WritableStream) in the Deno manual is broken. Instead it takes me to [this page](https://deno.land/api@1.40.4?s=WritableStream), which gives a nasty little error:

![image](https://github.com/denoland/deno_doc/assets/11234104/3ee11b52-8084-4e4e-8279-4fe649ee5900)

Notice that the cause of this issue is simply a missing `v` in the version identifier.

**Comment by nberlette** [comment]
Strange. I **know** that I posted this in denoland/deno_doc, yet somehow it ended up here. If you're a maintainer reading this, please feel free to relocate this issue over to the deno_doc repository (or I could re-create it manually). 

Sorry for cluttering up the primary issue tracker!

**Comment by crowlKats** [comment]
@nberlette i moved it here because its a bug in Deno cli itself with its configuration of the deno_doc's html generator
