### ISSUE TITLE
computed length property reports a constant length 1 to the lsp

### ISSUE THREAD

**Issue by king8fisher** [denoland/deno#22384]
Version: Deno 1.40.4

In a provided minimal example the `length` property shows a squiggly in the IDE anywhere where an attempt is made to assert the computed length with anything but 1.

The error popup notifies "This comparison appears to be unintentional because the types '1' and '2' have no overlap." and reports as if the `length` has a type of a single `1`: `(property) SetWithContentEquality<T extends object>.length: 1`

Strangely, an _editor-invoked test run_ completes the test with **no errors and succeeds**.

However, manual `deno test` will report an error instead:

```
error: TS2367 [ERROR]: This comparison appears to be unintentional because the types '1' and '2' have no overlap.
  assert(set.length == 2);
         ~~~~~~~~~~~~~~~
    at file:///deno-length-getter/main_test.ts:16:10
```
Minimal example to reproduce the bug: https://github.com/king8fisher/deno-bug-reports/tree/main/22384-deno-length-getter

**Comment by dsherret** [comment]
This occurs in the typescript playground ([see here](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBAYwDYEMDOa4GVgwOoCWMAFgMIQB2MwVAogI4CuKSRAngDwAqco1FAE0wQARgCtgCGAD44AbwBQcOGCgEAbimpwiwALZoAXHC4BtALpwAvHAsBuJSrWbtAc1wBpYG2MAKXXrGXACU1rJoMGoUrg6OCJQRUIxS0L7uMF4+cP7UgSahVuGRBNGhisrKJARoAHTpmdZw9d4OygC+CnFIlMC+ZY7K8RQRcOqNFMAA7ti4hCTkVDQwDMysMGy+VbXNbMGtFeo1AZg2pjXnW0e5aOb7ylC4jFAUo-sdjigCAjn6QcHG6ggBAE8gGiAS8AA1t5Gpcdj89HswUMRiUBKBYcRqld9LUAGZogCSglAvl86gKsjhnm85IKVhs0N2dx0eOyaIx0hsAAZ+hUKpdjqYOSBLDYAiy2rwkGhgKD+ZUsbVjjUwIw0MQEUj+R12p1lOlfEzjIkSq5-iY4AAfOCMEkEiYg8oVFHwEWY7Eqh0CYnokBkilhODUjK0wMMxnebUVAhs-wkkBwLlwXlwB4wJ4vQXXYUJ25g9OZ232krAARvfVwdFIXC9Y1wU2lILW4voh1l-bV2sIv7Nm12tul8uOLvUHsN4rRFshPut4Dtp1g2PZdZgYAQNkBawMuAAIkbrl3fIVheewaVNQA+qPegFo+1pbL5SfHmfLtfgDWxyHMlr73BdQAxxVA0LQ5Q-L8628E1J3NWcB3nIdn0GCEdATD1lWuGpvV9Uk6SDH8w3pSNmSXON3WTVNnX5V0q0-WsQRsbNcRqNAwFYBBbwTAAaOAAEZ-3uV8XhvARTG5fMdQLYS5wXCtHGIdBxxnOARAgCAaxQF5qLTGTmIMViID0XpfFAaoYDNSkwUVbF4TMiJLO3JiL3hO8wWjd5lG9XxVDLAgEDAvx1D+IM1I04AtOPISMzfC8vTRHyHgEfywI8yt0lGFhGGANA+iCCxkN0mKXjOC44uuSSgMcDKa2iEg8rgChGD0ERgCgQrTyzcqWNq1wSArd5QEgWA4DxO0pAISg4HQWVYFM8AoGMO1IQoCBJgoXiDFcRpdyPYwZramBMCG9rnWXXwAEITqi88oDWxqpjgWgoDuqBfC2tL3lo2V4BsCZphwfAiDISh+GWJgWHYDhHDkUa7ryA87GDCAYKiGJeAoFARBrARjDCzSXg6aQA0pUFOtGbD4bgABqPcrV3GmKZgCAHDaJEfpqT5vlhvF4eMXcel3Xjmf52UhgEIWMaxnHjDxFgnzZhwDrmjnepIbd+PZ3BOa+Xweb5vdBeFlG9zFygJd4mhpbLYxImygCkWVmBfFVmg+uIDWBIcDmub1uGjNFyRzclkW9yqKALal7GbeDJI5UVhQnZd7W1Y9ncACY9iAA)).

Maybe use `assertEquals` instead? (ex. `assertEquals(set.length, 1)`) You'll get better errors on failure when that happens too.

**Comment by king8fisher** [comment]
That's an interesting catch! I will certainly fix my assert, thanks @dsherret. I might be hitting just how the type system is designed when the `==` or `===` comparisons are utilized.
