### ISSUE TITLE
Align the return type of `crypto.randomUUID` to `lib.dom.d.ts`

### ISSUE THREAD

**Issue by babiabeo** [denoland/deno#22393]
Currently, the return type of `crypto.randomUUID` in `lib.deno_crypto.d.ts` is simply a `string`.

https://github.com/denoland/deno/blob/bd1358efab8ba7339a8e70034315fa7da840292e/ext/crypto/lib.deno_crypto.d.ts#L393

However, in TypeScript, the return type of `crypto.randomUUID` in `dom.generated.d.ts` (aka `lib.dom.d.ts`) is more specific: `${string}-${string}-${string}-${string}-${string}`.

https://github.com/microsoft/TypeScript/blob/ae27e55b027c66bf5b80f596da866f8485ac491d/src/lib/dom.generated.d.ts#L5880-L5885

```ts
/**
 * Available only in secure contexts.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/Crypto/randomUUID)
 */
randomUUID(): `${string}-${string}-${string}-${string}-${string}`;
```

I believe that it should be aligned to `lib.dom.d.ts` for compatibility with the DOM API.

Related: https://github.com/denoland/deno_std/pull/4301

**Comment by lino-levan** [comment]
I might be wrong, but it seems to already be aligned?
<img width="1088" alt="image" src="https://github.com/denoland/deno/assets/11367844/7b68e2e7-029f-4677-8ffb-4312704ffb37">
Was this issue already fixed or is there something deeper going on here?

**Comment by babiabeo** [comment]
> I might be wrong, but it seems to already be aligned?
> 
> <img width="1088" alt="image" src="https://github.com/denoland/deno/assets/11367844/7b68e2e7-029f-4677-8ffb-4312704ffb37">
> 
> Was this issue already fixed or is there something deeper going on here?

I mean `crypto.randomUUID` in [ext/crypto/lib.deno_crypto.d.ts](https://github.com/denoland/deno/blob/main/ext/crypto/lib.deno_crypto.d.ts), not in [cli/tsc/dts/lib.dom.d.ts](https://github.com/denoland/deno/blob/main/cli/tsc/dts/lib.dom.d.ts)

**Comment by lino-levan** [comment]
Ah right, of course.
