### ISSUE TITLE
025_high_precision.test is flaky on linux 

### ISSUE THREAD

**Issue by ry** [denoland/deno#2240]
```
tests/025_high_precision.test ... ... FAILED
Expected exit code 0 but got -11
Output:
true
true
```
example: https://travis-ci.com/denoland/deno/jobs/196184298

**Comment by GaryPWhite** [comment]
Trying to poke around here -- seems like that's not the job producing that output. Hard to repro on my linux box, is there an example travis build floating around?

**Comment by bartlomieju** [comment]
No longer relevant?

**Comment by ry** [comment]
I haven't seen this for a while. Closing.
