### ISSUE TITLE
KV: Nested Deno.KvU64 is not reconstructed on read

### ISSUE THREAD

**Issue by oliver-oloughlin** [denoland/deno#22415]
Version: Deno 1.40.4

When setting and getting a value of just Deno.KvU64, the value is properly reconstructed as a Deno.KvU64 instance. But when a Deno.KvU64 value is nested within an array, object, set or map, it is not reconstructed as a Deno.KvU64 instance, but instead a plain object with type: `{ value: bigint }`.

Example:
```ts
const kv = await Deno.openKv()
const val = { u64: new Deno.KvU64(100n) }
await kv.set(["u64"], val)
const { value } = await kv.get(["u64"])
console.log(value.u64, val.u64) // { value: 100n } [Deno.KvU64: 100n]
```

I would expect any stored Deno.KvU64 values to be restored as such, even though I understand that the purpose of this type is to be stored as a value directly to allow for operations like `atomic.max()`, `atomic.min()` and `atomic.sum()`. I believe it would still be more consistent if any nested Deno.KvU64 values were reconstructed with the proper class.

**Comment by lucacasonato** [comment]
This is documented in the docs:

> Values can be any structured-serializable JavaScript value (objects, arrays, strings, numbers, etc.). **The special value [Deno.KvU64](https://deno.land/api?s=Deno.KvU64&unstable=) can be used to store 64-bit unsigned integers in the database. This special value can not be nested within other objects or arrays.** In addition to the regular database mutation operations, the unsigned 64-bit integer value also supports sum, max, and min mutations.
