### ISSUE TITLE
Deno.UnsafePointerView.getUint32() seems to crash silently

### ISSUE THREAD

**Issue by FuriouZz** [denoland/deno#22428]
Version: Deno 1.40.5

I encountered an issue with `Deno.UnsafePointerView`.

I created a Rust library which send an enum to a callback function.

```rust
#[repr(C)]
pub enum Event {
    Moved(i32, i32),
}

#[no_mangle]
pub extern "C" fn poll_events(cb: Option<extern "C" fn(Event)>) {
    let callback = cb.expect("Callback is missing");
    callback(Event::Moved(10i32, 20i32));
}
```

I used `Deno.UnsafeCallback` to intercept the event.

```typescript
const onEvent = new Deno.UnsafeCallback(
  {
    parameters: ["pointer"],
    result: "void",
  },
  (e) => {
    if (e === null) return;

    const view = new Deno.UnsafePointerView(e);
    console.log("before type");
    const type = view.getUint32();
    console.log("after type");
    const x = view.getInt32(4 * 1);
    const y = view.getInt32(4 * 2);
    console.log(type, x, y);
  }
);

const lib = Deno.dlopen("./target/debug/libminimal.dylib", {
  poll_events: { parameters: ["function"], result: "void" },
});

lib.symbols.poll_events(onEvent.pointer);
```

The `before type` is logged but not `after type`.

I changed `Event::Moved(i32, i32)` to `Event::Moved(f64, f64)` and the `after type` is logged.

```rust
#[repr(C)]
pub enum Event {
    Moved(f64, f64),
}

#[no_mangle]
pub extern "C" fn poll_events(cb: Option<extern "C" fn(Event)>) {
    let callback = cb.expect("Callback is missing");
    callback(Event::Moved(10f64, 20f64));
}
```

**Comment by aapoalas** [comment]
Your `onEvent` function's definition is mistaken: Event isn't being passed as a pointer / reference but by value instead. And it so happens, I believe, that with two 32-bit integers the struct is small enough to pass through in a register according to the system C ABI. The "pointer" parameter you get as `e` is then a combination of two 32 bit numbers and essentially then points to random memory somewhere.

You should either change the Rust side `cb` type into `fn(*const Event)` or change the JS side to take as parameter a `{ struct: ["I32", "i32"] }`

**Comment by FuriouZz** [comment]
OK, I understand. Sorry for the issue.

I want the event to be dropped at the end of the `poll_events` scope, so I will prefer `fn(&Event)` and use a pointer.

Thank you for your insight.
