### ISSUE TITLE
JSR file_server package import error

### ISSUE THREAD

**Issue by dbushell** [denoland/deno#22434]
Trying to import the `file_server` from the [JSR package](https://jsr.io/@std/http/doc/file_server/~) throws an error:

```
Uncaught SyntaxError: The requested module './deno.json' does not provide an export named 'version' at https://jsr.io/@std/http/0.216.0/file_server.ts:52:10
    at async <anonymous>:1:34
```

**Steps to Reproduce**

```
import * as mod from "jsr:@std/http@0.216/file_server";
```

**Environment**

- OS: MacOS 14.2.1 (M2)
- deno version: 1.40.5
- std version: 0.216

**Comment by kt3k** [comment]
transferred from denoland/deno_std

**Comment by iuioiua** [comment]
This is a `deno_std` issue.

**Comment by kt3k** [comment]
Ah, the error is from the convert script.. I didn't realize it

**Comment by kt3k** [comment]
fixed by https://github.com/denoland/deno_std/pull/4342
