### ISSUE TITLE
ChildProcess.status kills event loop?

### ISSUE THREAD

**Issue by fserb** [denoland/deno#22438]
Version: deno 1.40.3 (release, aarch64-apple-darwin) v8 12.1.285.6 typescript 5.3.3

I'm having a hard time finding a no dependency repro for this. Sorry.

```
import * as esbuild from "https://deno.land/x/esbuild@v0.20.0/mod.js";

Deno.test("esbuild transform", async () => {
  const out = await esbuild.transform("let a = 1");
  // await esbuild.stop();
});
```

[deno-esbuild](https://github.com/esbuild/deno-esbuild/tree/main) uses `Deno.command()` [here](https://github.com/esbuild/deno-esbuild/blob/4f5a37d14bc626f3cc7ce7da2ae4f9048703f0da/mod.js#L1886) to spawn an esbuild binary and communicate with it.

When `stop()` is not called, `Deno test` catches an async operation that is leaking (not waiting for `Deno.Process#status` this is fair and I'm assuming a bug in deno-esbuild). 

If you uncomment the `await esbuild.stop()` line, this eventually will call `await ChildProcess.status` [here](https://github.com/esbuild/deno-esbuild/blob/4f5a37d14bc626f3cc7ce7da2ae4f9048703f0da/mod.js#L1898). This line seems to completely kill Deno and exit with an: `error: Promise resolution is still pending but the event loop has already resolved.`.

It's seems that deno-esbuild is doing something that puts the child process in a weird state, but it's also weird that `await ChildProcess.status` kills Deno without giving a reason. 

Is this WAI and just a bug in how deno-esbuild is doing _something_?

Is there a Deno flag that allows me to debug this further?

**Comment by bartlomieju** [comment]
@lucacasonato could you please take a look since you assisted with the update?

**Comment by mmastrac** [comment]
I think it's something other than the child process, as this test passes succesfully:

```ts
// sleep.ts
Deno.test("sleep", async () => {
  const process = new Deno.Command("/bin/sleep", {args:["1"]}).spawn();
  const out = await process.status;
});
```

Also, a dynamic module with a top-level await also seems to work:

```ts
// sleep_import.ts
Deno.test("sleep", async () => {
  const imported = await import('./sleep2.ts');
});
```

```ts
// sleep2.ts
const process = new Deno.Command("/bin/sleep", {args:["1"]}).spawn();
const out = await process.status;
```

**Comment by lucacasonato** [comment]
This was fixed in esbuild.
