### ISSUE TITLE
Deno tasks panel in VS Code only populated for project root

### ISSUE THREAD

**Issue by mpcref** [denoland/deno#22440]
Version: Deno 1.40.4

Normally, VS Code shows npm scripts defined in all `package.json` files leading up to the selected folder.
However, when the Deno extension takes over this behavior in order to show both npm scripts and deno tasks, only the npm scripts and deno tasks that are defined in `package.json` and `deno.json(c)` in the project's root are shown.

The Deno extension should follow VS Code's build-in behavior when overriding this functionality.

**Comment by nayeemrmn** [comment]
This is fixed
