### ISSUE TITLE
Support for 32-bit Linux (x86/ia32)

### ISSUE THREAD

**Issue by edwillard** [denoland/deno#22456]
I would like to use Deno in a 32-bit Linux environment for use in low-resource VMs. Is it possible to produce binaries for x86 Linux in addition to the current x64 and arm64? I currently use Node but would love to take advantage of the improvements Deno offers.

**Comment by lucacasonato** [comment]
No, we do not offer x86 builds officially. You can attempt to produce these builds yourself. But this is likely to not work.
