### ISSUE TITLE
URL imports with Node resolution

### ISSUE THREAD

**Issue by rracariu** [denoland/deno#22457]
When using external aliases with Vite: 
```js
resolve: {
    alias: {
            'cowsay': 'https://esm.sh/cowsay@1.6.0'
    }
}
``` 
I get this error message:
```sh
TypeError: Could not resolve 'https://esm.sh/cowsay@1.6.0' from 'file:///Users/deno/foo/node_modules/vite/dist/node/chunks/dep-stQc5rCc.js'.
  Caused by:
    [ERR_UNSUPPORTED_ESM_URL_SCHEME] Only file and data URLS are supported by the default ESM loader. Received protocol 'https'
```
Looks that this is explicitly forbitten in https://github.com/denoland/deno/blob/main/ext/node/resolution.rs#L179 

But Node allows this import types since v16

Version: `deno: "1.40.5", v8: "12.1.285.27", typescript: "5.3.3"`

**Comment by lucacasonato** [comment]
This is not an issue with Deno, but with Vite.
