### ISSUE TITLE
Unexpected Terminal output with ANSI escape code since 1.40.5

### ISSUE THREAD

**Issue by aotoriii** [denoland/deno#22450]
I use `Deno.stdout.write` and `TextEncoder.encode` to print with ANSI escape code.
And use `deno compile` to create an executable.
After upgrade to 1.40.5, the output behavior has changed.

The code to reproduce:
```ts
const print = async (str: string) => {
    const bytes = new TextEncoder().encode(str);
    await Deno.stdout.write(bytes);
}

const clear = async () => {
    await print("\x1B[2J");
}

const write = async (message: string) => {
    await print("\x1b[1;1H" + message + "\n");
}

await clear();
await write("Hello World");
alert("");
```

Result in 1.40.4:
```bash
$ deno --version
deno 1.40.4 (release, x86_64-pc-windows-msvc)
v8 12.1.285.6
typescript 5.3.3
```
![image](https://github.com/denoland/deno/assets/73811757/42bd91b6-8aaf-44f7-81ce-9a1a15e1c8da)

Result in 1.40.5:
```bash
$ deno --version
deno 1.40.5 (release, x86_64-pc-windows-msvc)
v8 12.1.285.27
typescript 5.3.3
```
![image](https://github.com/denoland/deno/assets/73811757/26256809-a1b1-4fbc-982c-acd12d31726f)

Maybe same problem with #22445.

**Comment by lucacasonato** [comment]
I think this was fixed by https://github.com/denoland/deno/pull/22507.

**Comment by littledivy** [comment]
![image](https://github.com/denoland/deno/assets/34997667/836c8648-d9f2-4aba-a5a5-17fc22d94278)

I think this is fixed. Open an issue if this still happens
