### ISSUE TITLE
Event loop issue

### ISSUE THREAD

**Issue by ScreamZ** [denoland/deno#22458]
Version: Deno 1.40.5 

Hi,

I'm making a mirror from the post I just published to Bun runtime. It seems that Deno has the same output that differs from NodeJS.

https://github.com/oven-sh/bun/issues/8972

Can you tell me if this is a bug or what? (Deno example at the post end)

Thanks

**Comment by architectureman** [comment]
You can explore it at https://denolib.gitbook.io/guide/advanced/process-lifecycle

**Comment by lucacasonato** [comment]
We consider this identical. Ordering of I/O completions in the macrotask queue is not guaranteed to be ordered in any specific way.

**Comment by KnorpelSenf** [comment]
Regarding macrotasks, it is indeed correct that you cannot rely on their order on the queue. It depends on how fast IO operations can be performed, which varies between runs.

However, the linked issue also describes that microtasks are ordered differently. It says that.
```ts
Promise.resolve().then(() => console.log("then"))
process.nextTick(() => console.log("nextTick"))
```
outputs
```sh
nextTick
then
```
on Node and
```sh
then
nextTick
```
on Deno.

I cannot reproduce this, but my library relies on microtasks being implemented identically in Deno and Node. @ScreamZ was this a mistake in your bug report? Am I missing something?

**Comment by ScreamZ** [comment]
> Regarding macrotasks, it is indeed correct that you cannot rely on their order on the queue. It depends on how fast IO operations can be performed, which varies between runs.
> 
> However, the linked issue also describes that microtasks are ordered differently. It says that
> 
> ```ts
> Promise.resolve().then(() => console.log("then"))
> process.nextTick(() => console.log("nextTick"))
> ```
> 
> outputs
> 
> ```shell
> nextTick
> then
> ```
> 
> on Node and
> 
> ```shell
> then
> nextTick
> ```
> 
> on Deno.
> 
> I cannot reproduce this, but my library relies on microtasks being implemented identically in Deno and Node. @ScreamZ was this a mistake in your bug report? Am I missing something?

Looks like on the latest version things looks as you said

```ts
✅ Granted read access to "/Users/screamz/dev-workspace/pro/supafriends/supafriends-app/test.mts".
this is Promise.resolve 1
this is process.nextTick 1
this is readFile 1
this is setTimeout 1
this is setImmediate 1   
```

**Comment by KnorpelSenf** [comment]
@ScreamZ that's the opposite of what I observe. On my machine, `nextTick` is evaluated first no matter if I use Node or Deno. Both runtimes behave identically for me and I think that this is actually the only correct behaviour given the docs.

**Comment by ScreamZ** [comment]
> @ScreamZ that's the opposite of what I observe. On my machine, `nextTick` is evaluated first no matter if I use Node or Deno. Both runtimes behave identically for me and I think that this is actually the only correct behaviour given the docs.

Im running on macOS

**Comment by KnorpelSenf** [comment]
Alright, I have actually found an issue here. Deno changes the order of microtasks depending on whether it runs in a REPL or in a file. I don't think this should ever be the case. Look:

```sh
$ # Create repro file
$ echo -e 'Promise.resolve().then(() => console.log("then"))\nprocess.nextTick(() => console.log("nextTick"))' > /tmp/file.js

# Run with Node and Deno
$ node /tmp/file.js
nextTick
then
$ deno /tmp/file.js
then
nextTick

# Do the same thing in a REPL and with eval
$ deno
Deno 2.1.1
exit using ctrl+d, ctrl+c, or close()
REPL is running with all permissions allowed.
To specify permissions, run `deno repl` with allow flags.
> import '/tmp/file.js'
then
nextTick
[Module: null prototype] {  }
> function repro() {
    Promise.resolve().then(() => console.log("then"))
    process.nextTick(() => console.log("nextTick"))
}
undefined
> repro()
nextTick
then
undefined
> > eval(Deno.readTextFileSync('/tmp/file.js'))
nextTick
then
undefined
> await eval(await Deno.readTextFile('/tmp/file.js'))
then
nextTick
undefined
> 
$
```
