### ISSUE TITLE
Request Allman style for `deno fmt`

### ISSUE THREAD

**Issue by ngdangtu-vn** [denoland/deno#22461]
Basically, allman style is something like this:

```ts
interface Fruit
{
    color: string
}

class Apple implement Fruit
{
    color: 'red'
}
```

It always my favourite style and hopefully it would get supoort in one day.

**Comment by lucacasonato** [comment]
We have no plans to support this - you can use a different formatter if you are interested in this style.

**Comment by ngdangtu-vn** [comment]
you guy could just deno fmt is an opinion formatter right from the start.
