### ISSUE TITLE
Does Deno support as a DOH client? How to use fetch with doh?

### ISSUE THREAD

**Issue by masx200** [denoland/deno#22472]
Does Deno support as a DOH client? How to use fetch with doh?

**Comment by lucacasonato** [comment]
What platform are you on? On Linux, we use `getaddrinfo`, which will use whatever DNS config is specified in your resolv.conf, which if DOH is enabled in your local DNS proxy, will use DOH, yes.

On macOS and Windows, this depends on the system configuration, and may work - you should try it :)

**Comment by masx200** [comment]
I'm not talking about system-level DOH, I'm talking about program-level DOH!

**Comment by masx200** [comment]
I'm not talking about system-level DOH, I'm talking about program-level DOH!

**Comment by lucacasonato** [comment]
Deno does not perform program level DNS resolution - it always calls out to the system (modulo `Deno.resolveDns` when specifying a custom nameserver). We do not support passing a custom DNS resolver to Deno itself, because we always use the system resolver through `getaddrinfo` for internal DNS resolution.

Please open another issue with a usecase if you are looking for custom resolver (with custom nameservers).

**Comment by kLiHz** [comment]
@masx200 I guess if the DoH supports JSON API, you could use it in a convenient way (without dealing with bytes) just by making a fetch request and await `.json()` on it.

For example [dns.google supports JSON API](https://developers.google.com/speed/public-dns/docs/doh), see also [its usage](https://developers.google.com/speed/public-dns/docs/doh/json).

By the way, I think using `fetch()` in Deno will also benefit from HTTP/2.

```ts
const q = 'www.deno.com';
const t = 'A';
const r = await fetch(`https://dns.google/resolve?name=${q}&rr_type=${t}`);
const d = await r.json();
```

The data should be like this:

```
{
  Status: 0,
  TC: false,
  RD: true,
  RA: true,
  AD: false,
  CD: false,
  Question: [ { name: "[www.deno.com](https://www.deno.com/).", type: 1 } ],
  Answer: [
    { name: "[www.deno.com](https://www.deno.com/).", type: 1, TTL: 3600, data: "34.120.54.55" }
  ],
  Comment: "Response from 216.239.36.108."
}
```
