### ISSUE TITLE
`Deno.inspect` ignores `colors: false`

### ISSUE THREAD

**Issue by scarf005** [denoland/deno#22496]
Version: Deno 1.40.5

## Summary

[`Deno.inspect`](https://deno.land/api@v1.40.5?s=Deno.inspect) ignores [`colors`](https://deno.land/api@v1.40.5?s=Deno.InspectOptions#prop_colors) option. 

This prevents `Deno.inspect` as an alternative serializer over `JSON.stringify` for use in [snapshot tests](https://docs.deno.com/runtime/manual/basics/testing/snapshot_testing) due to escape sequences.

## To Reproduce

```ts
$ deno

> Deno.inspect({ "foo": [1,2,3] })
"{ foo: [ \x1b[33m1\x1b[39m, \x1b[33m2\x1b[39m, \x1b[33m3\x1b[39m ] }"
> Deno.inspect({ "foo": [1,2,3] }, { colors: false })
"{ foo: [ \x1b[33m1\x1b[39m, \x1b[33m2\x1b[39m, \x1b[33m3\x1b[39m ] }"
> Deno.inspect({ "foo": [1,2,3] }, { colors: false, escapeSequences: false })
"{ foo: [ \x1b[33m1\x1b[39m, \x1b[33m2\x1b[39m, \x1b[33m3\x1b[39m ] }"
```

## Expected

```ts
> Deno.inspect({ "foo": [1,2,3] })
{ foo: [ 1, 2, 3 ] }
```

**Comment by bartlomieju** [comment]
CC @crowlKats I think this might be a regression from https://github.com/denoland/deno/pull/21910?

**Comment by rossholdway** [comment]
Can't reproduce this anymore now that 1.41.0 has been released. This could be closed.
