### ISSUE TITLE
npm import : class is not found but it is well declared in node_module

### ISSUE THREAD

**Issue by hapaxlife** [denoland/deno#22492]
Version: Deno 1.40.5

See https://discord.com/channels/684898665143206084/1209414858295087174/1209431742553915404

I try to use Tatum SDK in deno (https://github.com/tatumio/tatum-js). I pick up the easiest code example https://docs.tatum.io/

I try 2 ways of imports of tatum library but I have different errors in both ways.

1. **with npm**

don't recognize TatumSDK in import (but in node_modules it is exported in service/tatum).
How can I tell the owner to slighty modify his code in order that TatumSDK is recognize (Ethereum, Network are recognized) ?

```ts
import { Ethereum, Network, TatumSDK } from "npm:@tatumio/tatum";

const tatum = await TatumSDK.init<Ethereum>({ network: Network.ETHEREUM });
const latestBlock = await tatum.rpc.blockNumber();
console.log(`Latest block is ${latestBlock.result}`);
tatum.destroy();
```

2. **with esm** 

Library BigNumber.js has a version for deno !
error: Uncaught (in promise) TypeError: R.BigNumber is not a constructor

// BigNumber.js has a version for deno !
// error: Uncaught (in promise) TypeError: R.BigNumber is not a constructor

```ts
import { Ethereum, Network, TatumSDK } from "https://esm.sh/@tatumio/tatum";

// fake call to prevent error
window.location = { hostname: "fake" };

const tatum = await TatumSDK.init<Ethereum>({ network: Network.ETHEREUM });
const latestBlock = await tatum.rpc.blockNumber();
console.log(`Latest block is ${latestBlock.result}`);
tatum.destroy();
```

**Comment by hapaxlife** [comment]
Deno 1.42.0 improve the import for npm but we still need to import from rigth directory in node_modules

Following code works now :

```ts
import { Ethereum, Network } from "npm:@tatumio/tatum";
import { TatumSDK } from "./node_modules/@tatumio/tatum/dist/src/service/tatum/tatum.js";
// best import would be
import { Ethereum, Network, TatumSDK } from "npm:@tatumio/tatum";

const tatum = await TatumSDK.init<Ethereum>({ network: Network.ETHEREUM });
const latestBlock = await tatum.rpc.blockNumber();
console.log(`Latest block is ${latestBlock.result}`);
tatum.destroy();
```

**Comment by lucacasonato** [comment]
This is now fixed!

```
~/p/g/d/deno ❯❯❯ deno
Deno 1.44.2+8ad25e8
exit using ctrl+d, ctrl+c, or close()
REPL is running with all permissions allowed.
To specify permissions, run `deno repl` with allow flags.
> import { Ethereum, Network, TatumSDK } from "npm:@tatumio/tatum";

undefined
> TatumSDK
[class TatumSDK] {
  builtInExtensions: [ [class MetaMask extends TatumSdkWalletProvider] ]
}
> TatumSDK.init
[AsyncFunction: init]
> 
```
