### ISSUE TITLE
Replace `panic!`s with graceful errors for userland processing

### ISSUE THREAD

**Issue by kevinkassimo** [denoland/deno#2249]
Currently, we have many code simply panicking and hard crashing on invalid operations or input, e.g.
https://github.com/denoland/deno/blob/200bed9277182e40e4ee4bb08b237f1c2d1ae244/cli/resources.rs#L182-L195

Ideally we should instead wrap these conditions as errors and forward to TS side, such that users could provide code for handling.

However, there are challenges mainly from Tokio fs related problems: async io traits requires `std::io::Error` as error type, yet certain operations (e.g. `BadResource()`) does not exist in std and is hard to translate as one of the `std::io::ErrorKind` enum:
https://github.com/denoland/deno/blob/200bed9277182e40e4ee4bb08b237f1c2d1ae244/cli/resources.rs#L203-L220

One proposal was to merge things like `BadResource` into `NotFound`, yet this somehow violates `ENOENT` definition from the POSIX standard. Ideally we want to emit something similar to `EBADF`, yet such error is not present in `std::io::ErrorKind`.

Another possible (actually very ugly) solution is using `std::io::ErrorKind.Other` to mark special errors and create custom error message format, such that in `From` trait into `DenoError` we could parse the message and translate to our custom error types.

(`std::io::ErrorKind.InvalidInput` might be used to cover some of the other types of error)

**Comment by bartlomieju** [comment]
Ref #2406
