### ISSUE TITLE
Using cargo binstall to install deno results in an error (denort-related) in 1.40.5

### ISSUE THREAD

**Issue by nth10sd** [denoland/deno#22490]
Using `cargo binstall` to get `deno` now results in the following error:

```
ERROR resolve: When resolving deno bin denort is not found. This binary is not optional so it must be included in the archive, please contact with upstream to fix this issue.
```

Prior to 1.40.5, it seemed to work fine. Is this method no longer supported?

**Comment by littledivy** [comment]
`cargo-binstall` is likely not able to detect that `denort` is distributed as a seperate zip artifact in the releases. We don't want to ship it by default. 

Please open an issue with https://github.com/cargo-bins/cargo-binstall, I don't think Deno can solve it without shipping denort in the same artifact or adding extra feature flags.

**Comment by nth10sd** [comment]
I filed on their [issues page](https://github.com/cargo-bins/cargo-binstall/issues/1638).
