### ISSUE TITLE
`deno publish` doesn't support jsr.json

### ISSUE THREAD

**Issue by liruifengv** [denoland/deno#22491]
Version: Deno 1.40.5

when I want publish a package to jsr.io.

Created `jsr.json`，then run `deno publish`. Get a error:

```
error: Couldn't find a deno.json or a deno.jsonc configuration file in D:\opensource\isOdd.
```
![image](https://github.com/denoland/deno/assets/25167721/32cc81c7-658c-42ab-8d99-4f623bd9674b)

Create a `deno.json` instead of `jsr.json`, publish success.

## expectation

Support `jsr.json` configuration file

**Comment by MarkTiedemann** [comment]
Why do you expect `jsr.json` to be recognized as a configuration file? I did not find any documentation that says so.

**Comment by liruifengv** [comment]
> Why do you expect `jsr.json` to be recognized as a configuration file? I did not find any documentation that says so.

The documentation seems to have changed. I've definitely seen jsr.json in the documentation.

jsr supports all runtimes, so deno.json is not suitable

**Comment by bartlomieju** [comment]
FYI I'm already working on this.
