### ISSUE TITLE
Not implemented: ChildProcess.prototype.disconnect

### ISSUE THREAD

**Issue by birkskyum** [denoland/deno#22503]
Version: Deno 1.40.5

Repro:

```sh
 deno run -A npm:create-remix@latest --template remix-run/remix/templates/vite         

 remix   v2.4.0 💿 Let's build a better website...

   dir   Where should we create your new project?
         ./new-remix-4

      ◼  Template: Using remix-run/remix/templates/vite...
      ✔  Template copied

   git   Initialize a new git repository?
         Yes

  deps   Install dependencies with npm?
         Yes

Warning: Not implemented: ChildProcess.prototype.disconnect
```

After the ` Install dependencies with npm?` it'll hang, because it can't disconnect, and when I interrupt it with ctrl-c, then it'll prompt the warning.

**Comment by birkskyum** [comment]
Oh, this might be a duplicate of:
- #17265

**Comment by bartlomieju** [comment]
I believe this was fixed in https://github.com/denoland/deno/commit/8fdd65556299efa58512467b4d19d2612441d376

**Comment by birkskyum** [comment]
Fantastic! I'll validate when the next patch is would.

**Comment by bartlomieju** [comment]
@birkskyum you should be able to do it already using `deno upgrade --canary`
