### ISSUE TITLE
Restart server automatically when making changes

### ISSUE THREAD

**Issue by LaurenceM10** [denoland/deno#2251]
I created a basic server with Deno based on an example of: https://deno.land/

I added some changes and my feeling was that the server would restart with the new changes, but it was not like that.

Is there something integrated in Deno that allows it to be done, like nodemon in NodeJS?

**Comment by hayd** [comment]
After #1826 this can be added to the webserver / can write a nodemon-like deno application.

**Comment by bartlomieju** [comment]
Restarting server should be handled by higher level lib. Writing such lib will be possible after #1826
