### ISSUE TITLE
Cross compile to aarch64-unknown-linux-gnu

### ISSUE THREAD

**Issue by harvestcore** [denoland/deno#22527]
Hey there,

First of all, I've tried to find similar issues with no luck, my apologies if this is a duplicate issue.

My question is: Are there any plans to support cross compiling to `aarch64-unknown-linux-gnu`? It is great that now Deno is built for this architecture, but it would be even better if binaries could be compiled for this platform.

![image](https://github.com/denoland/deno/assets/22531231/59ff09ce-68d1-4633-a913-f99492619613)

---

Setup:
```
deno 1.41.0 (release, aarch64-apple-darwin)
v8 12.1.285.27
typescript 5.3.3
```

**Comment by littledivy** [comment]
We support cross compiling to `aarch64-unknown-linux-gnu`. The flag matches were not updated in the CLI :smile:

**Comment by harvestcore** [comment]
Thank you for the fix! 🚀
