### ISSUE TITLE
Support create-astro

### ISSUE THREAD

**Issue by birkskyum** [denoland/deno#22537]
Version: deno 1.41.0

**Repro:**

* `deno run -A npm:create-astro@latest`
Just step through it all, optionally disable the `install dependencies` step

**expected**

That the project is created

**current**

```sh
 ██████  Project initializing...
         ✔ Template copied
         ▶ TypeScript customizing...
         □ Git
      ▲  error Error: Unexpected end of JSON input
```

**Comment by bartlomieju** [comment]
@littledivy IIRC you hit similar problem a few days ago in another package.

**Comment by littledivy** [comment]
Yup, i hit this a few days ago with `npm:create-astro` itself.

**Comment by littledivy** [comment]
Did some debugging, it turns out `create-astro` is not waiting for files to be written before reading it in the Typescript initialization step.

https://github.com/withastro/astro/blob/7eac778cce4429059d433fa22bf8f44555e2965f/packages/create-astro/src/actions/template.ts#L62-L70
```diff
// Match first indent in the file or fallback to `\t`
const indent = /(^\s+)/m.exec(value)?.[1] ?? '\t';
-fs.promises.writeFile(
+return fs.promises.writeFile(
  file,
  JSON.stringify(
	Object.assign(JSON.parse(value), Object.assign(overrides, { private: undefined })),
	null,
	indent
  ),
  'utf-8'
);
```

**Comment by littledivy** [comment]
https://github.com/withastro/astro/pull/10487

**Comment by littledivy** [comment]
Works with Astro 4.5.8 and above!

```js
deno run -A -r npm:create-astro@latest
```
