### ISSUE TITLE
Deno Occasionally Panics on 1.41.0 When Caching Dependencies

### ISSUE THREAD

**Issue by catuhana** [denoland/deno#22558]
Cannot reproduce every time, but got it in my first run of [`deno compile discord-irc.ts`](https://github.com/aronson/discord-irc).

![image](https://github.com/denoland/deno/assets/108196023/0ea1b349-2d00-473d-ba72-a021be7d52cb)

**Comment by catuhana** [comment]
Apparently, that doesn't just happen with compile, but every time when Deno caches dependencies and shows their progress.

**Comment by bartlomieju** [comment]
Per `std::time::SystemTime::elapsed` docs:

> Returns the difference from this system time to the current clock time.
>
> This function may fail as the underlying system clock is susceptible to drift and updates (e.g., the system clock could go backwards), so this function might not always succeed. If successful, Ok(Duration) is returned where the duration represents the amount of time elapsed from this time measurement to the current time.

We should probably remove `.unwrap()` there and default to 0s duration there.

**Comment by catuhana** [comment]
> Per `std::time::SystemTime::elapsed` docs:
> 
> > Returns the difference from this system time to the current clock time.
> > This function may fail as the underlying system clock is susceptible to drift and updates (e.g., the system clock could go backwards), so this function might not always succeed. If successful, Ok(Duration) is returned where the duration represents the amount of time elapsed from this time measurement to the current time.
> 
> We should probably remove `.unwrap()` there and default to 0s duration there.

If defaulting to `0` is enough, I can create a PR for it!

**Comment by catuhana** [comment]
Also, it seems like docs are recommending to use `Instant` instead.

> To measure elapsed time reliably, use [Instant](https://doc.rust-lang.org/stable/std/time/struct.Instant.html) instead.

But `Instant` also has this note:

> Note, however, that instants are not guaranteed to be steady. In other words, each tick of the underlying clock might not be the same length (e.g. some seconds may be longer than others). An instant may jump forwards or experience time dilation (slow down or speed up), but it will never go backwards. As part of this non-guarantee it is also not specified whether system suspends count as elapsed time or not. The behavior varies across platforms and rust versions.

> Instants are opaque types that can only be compared to one another. There is no method to get “the number of seconds” from an instant. Instead, it only allows measuring the duration between two instants (or comparing two instants).

Would using `Instant` instead of `SystemTime` change the intended behaviour?

**Comment by bartlomieju** [comment]
@catuhana yes, that would work as well. This field is used for a very non-essential functionality that doesn't need to display very precise data, so anything that removes a potential panic is a good fix 👍

**Comment by catuhana** [comment]
Alright, thanks!
