### ISSUE TITLE
npm package node-xlsx can not work

### ISSUE THREAD

**Issue by wangfeng1994** [denoland/deno#22554]
Version: Deno 1.41.0

**Comment by wangfeng1994** [comment]
<img width="952" alt="无标题" src="https://github.com/denoland/deno/assets/17782895/04c6f694-2bc5-4f53-9886-e2a14016c81b">

**Comment by marvinhagemeister** [comment]
Took a quick look what's happening and the `node-xlsx` package has this in their dependencies:

```jsonc
// package.json
{
  "dependencies": {
     "xlsx": "https://cdn.sheetjs.com/xlsx-0.19.3/xlsx-0.19.3.tgz"
  }
}
```

The URL points to a standard npm tarball and checking with the npm docs they do allow specifying dependencies with tarball http urls https://docs.npmjs.com/cli/v10/configuring-npm/package-json#dependencies . It's something we seemingly haven't implemented yet.

**Comment by wangfeng1994** [comment]
thanks

**Comment by wangfeng1994** [comment]
please fix it

**Comment by OleksiiPylypcuk-cnic** [comment]
Any updates on this? 

I tried everything, including installing a recent version from JSR
`import * as mod from "@mirror/xlsx";`

But getting error 
> plugin:vite:import-analysis] Failed to resolve import "@ mirror/xlsx" from "src/utils/openXLSFile.ts". Does the file exist?

**Comment by OleksiiPylypcuk-cnic** [comment]
UPD: solved with 
https://docs.sheetjs.com/docs/getting-started/installation/deno/

**Comment by wangfeng1994** [comment]
thanks

**Comment by OleksiiPylypcuk-cnic** [comment]
import * as XLSX from 'https://cdn.sheetjs.com/xlsx-0.20.3/package/xlsx.mjs';    -> working 

// import * as XLSX from 'xlsx'.  -> not working, despite having 
```
  "imports": {
    "xlsx": "https://cdn.sheetjs.com/xlsx-0.20.3/package/xlsx.mjs"
  }
```
in deno.json

**Comment by kt3k** [comment]
Can this issue be closed now?

**Comment by wangfeng1994** [comment]
ok&nbsp;




反反复复
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "denoland/deno"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月27日(星期三) 下午2:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [denoland/deno] npm package node-xlsx can not work (Issue #22554)





 
Can this issue be closed now?
