### ISSUE TITLE
deno publish is not working after deno init 

### ISSUE THREAD

**Issue by muddlebee** [denoland/deno#22564]
Version: Latest

```
> deno init 

> cat deno.json 
{
  "tasks": {
    "dev": "deno run --watch main.ts"
  }
}

> deno publish
error: file:///home/muddles/Codes/denoland/test/t1/deno.json is missing 'name' field

```

![image](https://github.com/denoland/deno/assets/8139783/203663f6-e564-4ef9-a3c3-919d7c160fdb)

related #22499

**Comment by muddlebee** [comment]
also docs for `deno publish` is missing, opened an issue here https://github.com/denoland/deno-docs/issues/346

best is to add some info in docs I guess?

**Comment by dsherret** [comment]
See https://github.com/denoland/deno/pull/22499

**Comment by lucacasonato** [comment]
Closing in favor of https://github.com/denoland/deno/pull/22499
