### ISSUE TITLE
Unstable Temporal API disappeared from Deno Compile after DenoRT switch

### ISSUE THREAD

**Issue by Rocknerve** [denoland/deno#22560]
Version: Deno 1.41.0

Hello Deno Team!

Deno Compile’s CLI Help suggests that `--unstable-temporal` should be a valid feature:
```
bash$ deno compile --help | grep temporal -A 2
      --unstable-temporal
          Enable unstable Temporal API
```
It was indeed a working feature prior to Deno Compile’s DenoRT binary being reinstated a couple weeks ago. But now we see:
```
bash$ echo 'console.log(Temporal.Now.instant().epochNanoseconds);' > ttest.js
bash$ deno run --unstable-temporal ttest.js 
1708684274935905024n
bash$ deno compile --unstable-temporal ttest.js 
Compile file:///tmp/ttest.js to ttest
Archive:  /tmp/.tmpidbCrO/denort.zip
  inflating: denort          
bash$ ./ttest
error: Uncaught (in promise) ReferenceError: Temporal is not defined
console.log(Temporal.Now.instant().epochNanoseconds);
            ^
    at file:///tmp/ttest.js:1:13
```

I think it makes sense that Unstable APIs should still be included within DenoRT (under their respective flags), since permanently including those APIs in DenoRT is the future plan once those APIs stabilize. This policy has the benefit that _no sudden changes will happen to DenoRT once those APIs do stabilize_.

Is it possible to restore Unstable APIs (under their respective flags) to DenoRT?

Thanks again for building the best programming toolkit out there.

**Comment by bartlomieju** [comment]
@littledivy I think we need to store this data in the compiled binary's metadata and configure V8 on startup.

**Comment by Rocknerve** [comment]
I can confirm that the compiled binary’s Metadata JSON does still store eg. `"unstable_config":{"features":["temporal"]}` — It’s just that this `unstable_config` is not being honored by DenoRT for some reason.

**Comment by Rocknerve** [comment]
`Temporal` works great now in `deno compile` in version 1.41.2!
Thanks so much @bartlomieju for getting it working again!
