### ISSUE TITLE
deno xargs

### ISSUE THREAD

**Issue by ry** [denoland/deno#2257]
For quick processing on the command line, `deno xargs [code]` reads from stdin, line-by-line and execute the specified code for each line. The line is found in `$` (other suggestions welcome for this variable name)
Example:
```
> cat /etc/passwd | deno xargs "a = $.split(':'); if (a.length) console.log(a[0])"
```
maybe "deno xeval" ?

**Comment by kevinkassimo** [comment]
We can also allow user to potentially choose their own variable name (in some way similar to replstr for `xargs`): 

`deno xeval -I="myvar" "console.log(myvar)"`

This also seems to be implementable mostly on the TS side.

**Comment by bartlomieju** [comment]
Done in #2260 :) ?
