### ISSUE TITLE
VS Code integration is broken

### ISSUE THREAD

**Issue by Stokestack** [denoland/deno#22576]
I couldn't find a more appropriate place for this report, so...

This is deno 1.36.3 (release, x86_64-apple-darwin)
v8 11.6.189.12
typescript 5.1.6

Suddenly I'm getting the following upon opening my Deno project in VS Code:

Starting Deno language server...
  version: 1.36.3 (release, x86_64-apple-darwin)
  executable: /usr/local/bin/deno
Connected to "Visual Studio Code" 1.86.2
Cannot set workspace settings: invalid type: null, expected a sequence
[Error - 5:40:53 PM] Server initialization failed.
  Message: Internal error
  Code: -32603 
[Error - 5:40:53 PM] Deno Language Server client: couldn't create connection to server.
  Message: Internal error
  Code: -32603

`deno upgrade` isn't an option because Deno is managed by Homebrew. I've done `brew update` and `brew upgrade`, but the problem remains. I found a report of this that dates back at least three weeks, so I'm stumped at the moment.

**Comment by Stokestack** [comment]
I see that 1.36 isn't the latest version of Deno, so the question is why the Homebrew update didn't pull it.

**Comment by Stokestack** [comment]
Looking more closely at that page, I see that Big Sur is not listed among the supported OSes. This orphans a lot of Intel Macs, which are stuck at OS 11.7.10.

**Comment by Stokestack** [comment]
I just ran brew update/upgrade again, and this time it appears to be updating Deno to 1.41. It seems to be building it locally. I don't know why it took two or three attempts to get picked up.

**Comment by nayeemrmn** [comment]
From discord: If `deno upgrade` isn't an option, use an older version of the extension according to https://github.com/denoland/vscode_deno?tab=readme-ov-file#compatibility. https://code.visualstudio.com/updates/v1_30#_install-previous-versions

**Comment by Anutrix** [comment]
Facing exact same issue with Deno 2.0.

**Comment by Stokestack** [comment]
When do you see that? I have updated to 2.0 and opened my project, but I'm not seeing this error. I installed Deno with Homebrew.

**Comment by Anutrix** [comment]
I am on Windows 11 and I see that as soon as I open the VSCode.
![image](https://github.com/user-attachments/assets/caf87d8d-87f7-4631-8669-3173d51042af)

**Comment by bartlomieju** [comment]
@Anutrix can you click the "Go to output" button and paste the text here?

**Comment by Anutrix** [comment]
> @Anutrix can you click the "Go to output" button and paste the text here?

```
Starting Deno language server...
  version: 1.36.4 (release, x86_64-pc-windows-msvc)
  executable: C:\Users\Anutrix\.deno\bin\deno.EXE
Connected to "Visual Studio Code" 1.94.2
Cannot set workspace settings: invalid type: null, expected a boolean
[Error - 3:44:22 AM] Server initialization failed.
  Message: Internal error
  Code: -32603 
[Error - 3:44:22 AM] Deno Language Server client: couldn't create connection to server.
  Message: Internal error
  Code: -32603 
[Info  - 3:44:24 AM] Connection to server got closed. Server will restart.
Starting Deno language server...
  version: 1.36.4 (release, x86_64-pc-windows-msvc)
  executable: C:\Users\Anutrix\.deno\bin\deno.EXE
Connected to "Visual Studio Code" 1.94.2
Cannot set workspace settings: invalid type: null, expected a boolean
[Error - 3:44:24 AM] Server initialization failed.
  Message: Internal error
  Code: -32603 
[Error - 3:44:24 AM] Deno Language Server client: couldn't create connection to server.
  Message: Internal error
  Code: -32603 
[Error - 3:44:24 AM] Restarting server failed
  Message: Internal error
  Code: -32603 
[Info  - 3:44:26 AM] Connection to server got closed. Server will restart.
Starting Deno language server...
  version: 1.36.4 (release, x86_64-pc-windows-msvc)
  executable: C:\Users\Anutrix\.deno\bin\deno.EXE
Connected to "Visual Studio Code" 1.94.2
Cannot set workspace settings: invalid type: null, expected a boolean
[Error - 3:44:26 AM] Server initialization failed.
  Message: Internal error
  Code: -32603 
[Error - 3:44:26 AM] Deno Language Server client: couldn't create connection to server.
  Message: Internal error
  Code: -32603 
[Error - 3:44:26 AM] Restarting server failed
  Message: Internal error
  Code: -32603 
[Info  - 3:44:28 AM] Connection to server got closed. Server will restart.
Starting Deno language server...
  version: 1.36.4 (release, x86_64-pc-windows-msvc)
  executable: C:\Users\Anutrix\.deno\bin\deno.EXE
Connected to "Visual Studio Code" 1.94.2
Cannot set workspace settings: invalid type: null, expected a boolean
[Error - 3:44:28 AM] Server initialization failed.
  Message: Internal error
  Code: -32603 
[Error - 3:44:28 AM] Deno Language Server client: couldn't create connection to server.
  Message: Internal error
  Code: -32603 
[Error - 3:44:28 AM] Restarting server failed
  Message: Internal error
  Code: -32603 
[Info  - 3:44:30 AM] Connection to server got closed. Server will restart.
Starting Deno language server...
  version: 1.36.4 (release, x86_64-pc-windows-msvc)
  executable: C:\Users\Anutrix\.deno\bin\deno.EXE
Connected to "Visual Studio Code" 1.94.2
Cannot set workspace settings: invalid type: null, expected a boolean
[Error - 3:44:30 AM] Server initialization failed.
  Message: Internal error
  Code: -32603 
[Error - 3:44:30 AM] Deno Language Server client: couldn't create connection to server.
  Message: Internal error
  Code: -32603 
[Error - 3:44:30 AM] Restarting server failed
  Message: Internal error
  Code: -32603 
```

**Comment by nayeemrmn** [comment]
@Anutrix You're using 1.36.4. Ensure you've upgraded the right exe and your env is configured correctly.

**Comment by Anutrix** [comment]
![image](https://github.com/user-attachments/assets/c68147bf-e051-4f68-8282-ddeac77987c9)

![image](https://github.com/user-attachments/assets/4a6812cc-4da1-4f63-83cd-2c8852b446b3)
This is odd. It seems I have an old version of deno.exe too. I thought it would be overwritten correctly.

**Comment by nayeemrmn** [comment]
I suppose the default installation directory changed since the last time you installed, which had to have been a really long time ago
