### ISSUE TITLE
fmt with verbatimModuleSyntax?

### ISSUE THREAD

**Issue by vicary** [denoland/deno#22583]
Currently Deno fmt sorts *verbatim imports* alphabetically, this is conflicting with the *Organize Imports* in VS Code where it sorts `import { type ... }` entries individually at the end.

Example:
```ts
// VS Code
import {
  bar, 
  foo, 
  type Bar, 
  type Foo
} from "module";

// Deno fmt
import {
  type Bar, 
  bar, 
  type Foo, 
  foo
} from "module";
```

When combined with the following VS Code option, all of the files flashes between the two formats in random order depending on how `formatOnSave` is configured.
```json
"editor.codeActionsOnSave": {
    "source.organizeImports": "explicit"
}
```

Is it possible to add an option for Deno fmt, either disabling that part or expose an option to align with VS Code?

**Comment by jakebailey** [comment]
FWIW TS's organize imports should be able to handle this since TS 5.4: https://github.com/microsoft/TypeScript/pull/55269

**Comment by jakebailey** [comment]
Oh, no wonder... TS 5.4 came out in March, but this issue was from February...
