### ISSUE TITLE
VSCode extension: enablePaths not disabling TS language server

### ISSUE THREAD

**Issue by JorensM** [denoland/deno#22603]
Version: Deno extension v3.33.3

So I have a VScode workspace with 2 folders - `client` and `server`.

In my workspace settings, I have `deno.enablePaths` set to include only the `server` folder. This successfully enabled Deno in the `server` folder and disables it in the `client`. The problem is that in my `server` folder, TypeScript is still running so I'm getting errors such as `cannot find name 'Deno'` from TS.

Below are some screenshots:

![deno-enable-paths](https://github.com/denoland/deno/assets/17122123/02394bcb-aeeb-4b9a-8551-b94c4be85699)

![deno-undefined](https://github.com/denoland/deno/assets/17122123/4e244181-d8d5-4a74-bcc1-01f82160fb4e)

**Comment by nayeemrmn** [comment]
Fixed by https://github.com/denoland/vscode_deno/pull/1086, try 3.35.1.

**Comment by boomyao** [comment]
Is it truly fixed? Why am I still encountering the problem?
vscode_deno: v3.37.0
deno: 1.42.4 (release, aarch64-apple-darwin)
