### ISSUE TITLE
`nuxt dev` without BYONM fails at installations

### ISSUE THREAD

**Issue by littledivy** [denoland/deno#22606]
```
$ deno run -A npm:nuxi@latest init --packageManager npm --gitInit=false --no-install my-app
$ cd my-app/
$ deno task dev
error: npm package 'uWebSockets.js' does not exist.
```

**Comment by birkskyum** [comment]
works with DENO_FUTURE=1  and pnpm

**Comment by birkskyum** [comment]
@littledivy , it seems this can be closed - assuming that the ticket isn't limited to running without DENO_FUTURE

**Comment by Malix-off** [comment]
>pnpm

What about `deno add` ?

**Comment by birkskyum** [comment]
#25648

**Comment by littledivy** [comment]
Closing in favor of https://github.com/denoland/deno/issues/25648. This is more of a `deno install` bug now - works fine with `npm` and `pnpm`
