### ISSUE TITLE
Better website with Vuepress

### ISSUE THREAD

**Issue by sh7dm** [denoland/deno#2261]
Vuepress is an awesome static site generator we can use for Deno. We don't need to worry about design. I'd like to reefactor docs if you like Vuepress.
Ref: https://github.com/vuejs/vuepress

**Comment by sh7dm** [comment]
@ry do you approve that?

**Comment by ry** [comment]
@sh7dm Sorry for the delayed reply. Thanks for the offer but I don't want to introduce a complex website system right now.
