### ISSUE TITLE
`node:worker_threads` and WebAPI `Workers` don't terminate

### ISSUE THREAD

**Issue by mash-graz** [denoland/deno#22629]
Version: Deno 1.41.0

Take this very simple example script `t.mjs` as usually presented in typical [`worker_threads` introductory lectures](https://www.cs.unb.ca/~bremner/teaching/cs2613/books/nodejs-api/worker_threads/):

```js
import { Worker, isMainThread } from "node:worker_threads";

if (isMainThread) {
    // This re-loads the current file inside a Worker instance.
    const w = new Worker(import.meta.filename);
} else {
    console.log('Inside Worker!');
    console.log(isMainThread);  // Prints 'false'.
}
```

If you execute this script with `deno run -A t.mjs` it will output the expected lines but **doesn't stop anymore**.

The same script executed with `node t.mjs` will also print the expected output, but terminates correctly afterward.

This also affects more complicated real world applications and `node` compatibility in general.

**Comment by mmastrac** [comment]
Thanks for the concise report. Does this also happen w/Deno workers, or is it just node workers?

**Comment by mash-graz** [comment]
> Does this also happen w/Deno workers, or is it just node workers?

I'm not perfectly sure, but the `Workers` seem to hang in both cases in my very simple test scripts.

I stumbled over this issue while solving compatibility issues of `Jco` resp. this strange *hanging* behavior. (see: https://github.com/bytecodealliance/jco/issues/385 and https://github.com/bytecodealliance/jco/pull/387).

In this particular case I had to fix an existing solution for `node` and didn't have much freedom to write a more `deno` specific variant  -- although the latter could make some sense in the long run for performance reasons.

Unfortunately I'm no expert in this field and therefore hardly able to understand the real causes behind this flaw or more effective solutions to bypass the defect.

**Comment by satyarohith** [comment]
The following example doesn't terminate in Deno
```js
if (!globalThis.name) {
  // This re-loads the current file inside a Worker instance.
  new Worker(import.meta.filename, {
    type: "module",
    name: "worker",
  });
} else {
  console.log(`Inside ${globalThis.name}!`);
}
```

**Comment by mash-graz** [comment]
It can be reproduced by an even more trival example using two files:

task.mjs:
```js
console.log('Inside Worker!');
export {}
```

t2.mjs:
```js
console.log("Main Task");
const w = new Worker(import.meta.resolve("./task.mjs"), { type: "module" });
```

Executing `deno run -A t2.mjs` will *hang* again.

btw. I'm using `deno` 1.41.0 on debian linux intel amd64 architecture.

**Comment by guybedford** [comment]
Note Deno does not implement `.unref()` for worker threads here which is how Node.js avoids this issue.

**Comment by mash-graz** [comment]
I think, @guybedford is emphasizing an important detail by mentioning the role of `unref()`!

Workers should be able to stay idle waiting for messages from the main thread without automatically closing.

`node:worker_threads` use the `ref`/`unref` methods to configure this aspect of workers behavior:

> Opposite of unref(), calling ref() on a previously unref()ed worker does not let the program exit if it's the only active handle left (the default behavior). ...*(https://nodejs.org/api/worker_threads.html#workerref)*

As stated in this description `node:worker_threads` should close after proceeding the workers job if not explicitly set otherwise. That's not how `deno` works right now. Unfortunately we miss also the `ref` and `unref` methods in this implementation, to configure this particular behavior in a `node` compatible manner.

Deno/Web `Worker` should behave a slightly different in this respect. In contrast to `node:worker_threads` they should not close automatically by default. Similar to the `ref``/`unref` counterpart they use a specific `closing flag` to configure the termination request.

> Each [WorkerGlobalScope](https://html.spec.whatwg.org/multipage/workers.html#workerglobalscope) object has a closing flag, which must be initially false, but which can get set to true by the algorithms in the processing model section below. *(https://html.spec.whatwg.org/multipage/workers.html#worker-event-loop)*

In this case we can use the `close()` method within the worker instance to signal the end of processing.

see:
[MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/DedicatedWorkerGlobalScope/close)
[W3C docs](https://html.spec.whatwg.org/multipage/workers.html#dedicated-workers-and-the-dedicatedworkerglobalscope-interface)

Utilizing this `close()` or `self.close()` command we can simply avoid the *hanging* behavior:

```
if (!globalThis.name) {
    // This re-loads the current file inside a Worker instance.
    new Worker(import.meta.url, {
        type: "module",
        name: "worker",
    });
} else {
    console.log(`Inside ${globalThis.name}!`);
    close()
}
```

But this solution isn't provided in `node:worker_threads` -- or better: it shouldn't be available there --, but the actual implementation in `deno` seems to be so similar to the Web API variant, that the `close()`-call will work even there. But that's just a very questionable hack, which naturally doesn't work on `node` resp. in any compatible code.

Just as demonstration for this strange and unexpected use of `close()` in the context of denos `node:worker_threads` implementation (please don't use it!): 

```
import { isMainThread, Worker } from "node:worker_threads";

if (isMainThread) {
  // This re-loads the current file inside a Worker instance.
  const w = new Worker(import.meta.filename);
  //globalThis.Deno || w.terminate();
} else {
  console.log("Inside Worker!");
  console.log(isMainThread); // Prints 'false'.
  globalThis.Deno && close();
}
```

**Comment by mash-graz** [comment]
Just as small progress report about solving `deno` compatibility issues in `jco`, because this issue already got [linked](https://mastodon.social/@squillace@hachyderm.io/112038804987039862) in public social media debates:

There are still many grave issues of `deno` node compatibility blocking the utilization of `jco` on this runtime.

* https://github.com/denoland/deno/pull/22616 are trivial additions of missing functions in `deno` which are still not merged, but it's rather trivial to bypass them.
*  https://github.com/denoland/deno/issues/22629 is still open, but can be most likely bypassed if not solve in `deno`.
* https://github.com/denoland/deno/issues/22672 is another grave defect in `deno`, which affects the `SyncKit` code in `jco`. It's easy to work around by trivial code modifications, once you understand the cause of this issue.
* The `node:webworkers` API call `receiveMessageOnPort` is missing in `deno`. That's a rather critical obstacle, because there isn't any other `sync` alternative for message exchange available and every user level serialization/deserialization attempts to use shared memory arrays without such a dedicated call, would be horribly inefficient. I'm therefore preparing an implementation of this mechanism in the `deno` right now. But it could take some time before it works and gets finally integrated.

Well, there may be other hidden showstoppers still waiting on the road to success, but these are at least the main issues on the always growing list of patches, which I could identify and partially solve until now...
