### ISSUE TITLE
Deno executable doesn't run...

### ISSUE THREAD

**Issue by kakashi-69-xd** [denoland/deno#22650]
Deno executable doesn't run on Android device...
Version: Deno 1.41.1

```sh
u0_a605@localhost ~/.deno/bin$ ls                     deno
u0_a605@localhost ~/.deno/bin$ ./deno
zsh: no such file or directory: ./deno
u0_a605@localhost ~/.deno/bin$

```

**Comment by ar37-rs** [comment]
try:
```
chmod +x ./deno
```
then rerun.

**Comment by mmastrac** [comment]
The deno Linux executable requires a glibc environment and unfortunately will require a custom build.

Dupe of https://github.com/denoland/deno/issues/19759
