### ISSUE TITLE
Ability to publish with a version specified as a CLI flag

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#22663]
For `deno publish`, it would be really nice to override the version by providing a CLI flag. Maybe `--set-version`, `--version`, `--override-version` or something:

```
deno publish --set-version 1.0.1
```

Right now I'm manually editing the config file in the CI pipeline.

**Comment by ckrassow** [comment]
Is this issue still relevant? If so i'd like to give it a try as its labeled as a good first issue!

**Comment by dsherret** [comment]
Implemented in https://github.com/denoland/deno/pull/26141
