### ISSUE TITLE
jsr specifier resolves to local package when referencing itself

### ISSUE THREAD

**Issue by sigmaSd** [denoland/deno#22667]
Version: Deno 1.41.1

to reproduce
- git clone https://github.com/sigmaSd/deno-pty-ffi
- git checkout bug
- touch b.ts
- deno run -A example.ts b.ts 

Somehow the local `Pty` constructor gets called instead of the remote jsr one https://github.com/sigmaSd/deno-pty-ffi/compare/bug?expand=1

**Comment by sigmaSd** [comment]
The original repo bug, used a wasm file (which won't work in jsr) so I updated the example with one that doesn't

**Comment by dsherret** [comment]
This probably has to do with the upcoming workspace support and probably should not occur when not in a workspace.

Basically, the specifier `jsr:@sigma/pty-ffi` matches your local `@sigma/pty-ffi@0.20.4` package and so it uses that, but again, this probably should only occur in a workspace, but I'm not 100% sure.

**Comment by sigmaSd** [comment]
Personally I think its unexpected, I don't know another language that does this, I was debugging an issue with my module and this behavior confused me until I figure it out

**Comment by dsherret** [comment]
> Otherwise writing things like examples becomes very cumbersome, because you'd have to import local files locally, but full paths in production.

If a certain specifier is locked to a different version then it will import that other version. Probably example scripts should be written with relative paths.

**Comment by dsherret** [comment]
Discussed with Luca. The package is a workspace of one and it takes precedence over remote packages, so a specifier that matches the local package will resolve to the local package. This will make more sense once workspace support is better supported and lands.

If someone wishes to use the remote package, they'll need to use a constraint that doesn't match the local package's version. In the future, https imports should work, so you'll be able to import remote packages directly via the https import.

**Comment by sigmaSd** [comment]
When using go to definition the lsp goes to the deno cache instead of the local file, so I guess this should be fixed
