### ISSUE TITLE
networking tests not running?

### ISSUE THREAD

**Issue by mrkurt** [denoland/deno#2267]
I don't think `fetch_test.ts` is running properly, it seems like all the tests defined with `testPerm` are getting ignored. None of them even show up in the appveyor logs.

![image](https://user-images.githubusercontent.com/7724/57056645-65651500-6c69-11e9-98fd-15b5302ee22b.png)

**Comment by ry** [comment]
That's embarrassing. Yes, you're right. Somehow those got turned off - it's a massive oversight.

I'm started turning it on in this PR https://github.com/denoland/deno/pull/2268 but the unit tests hang. Needs more work still.
