### ISSUE TITLE
Deno should support structured clone for web APIs it supports

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#22675]
There are several [web APIs](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm#webapi_types) that should be structured cloneable, but while Deno supports some of the web APIs it doesn't support structured cloning on them.  For example, this works in Chrome:

```js
structuredClone(new Blob([]));
// Blob { size: 0, type: '' }
```

But in Deno you get:

```js
structuredClone(new Blob([]));
// {}
```

There are the web APIs that Deno supports that should be cloneable:

- [Blob](https://developer.mozilla.org/en-US/docs/Web/API/Blob)
- [CryptoKey](https://developer.mozilla.org/en-US/docs/Web/API/CryptoKey)
- [DOMException](https://developer.mozilla.org/en-US/docs/Web/API/DOMException): browsers must serialize the properties [name](https://developer.mozilla.org/en-US/docs/Web/API/DOMException/name) and [message](https://developer.mozilla.org/en-US/docs/Web/API/DOMException/message). Other attributes may also be serialized/cloned.
- [File](https://developer.mozilla.org/en-US/docs/Web/API/File)
- [ImageBitmap](https://developer.mozilla.org/en-US/docs/Web/API/ImageBitmap)
- [ImageData](https://developer.mozilla.org/en-US/docs/Web/API/ImageData)
- [RTCCertificate](https://developer.mozilla.org/en-US/docs/Web/API/RTCCertificate)

This also restricts these being stored in Deno KV, which they could be if structured cloning is supported for them.

**Comment by petamoriken** [comment]
duplicated with #12067

**Comment by kitsonk** [comment]
DOH! and I even contributed to that.
