### ISSUE TITLE
`workerData` isn't available in `node:worker_threads` before first message arrives.

### ISSUE THREAD

**Issue by mash-graz** [denoland/deno#22672]
Version:  deno 1.41.1 (release, x86_64-unknown-linux-gnu)

`workerData` isn't available in `node:worker_threads` before the first message arrives.

Although this implementation flaw is already known and [tagged with an old TODO remark in the source code](https://github.com/denoland/deno/blame/942b2aaca57880152877a34006b30d2e982dec00/ext/node/polyfills/worker_threads.ts#L239), it's still affecting node compatibility significantly.

Even the most simple examples as given in the [node documentation concerning `workerData`](https://nodejs.org/api/worker_threads.html#workerworkerdata) will not work as expected in `deno` because of this uncommon implementation detail:
```js
// example.mjs
import { Worker, isMainThread, workerData } from 'node:worker_threads';

if (isMainThread) {
  const worker = new Worker(import.meta.filename, { workerData: 'wake up, deno!'});
} else {
  console.log("WorkerData:", workerData); // should print...
}
```

But it also breaks more complex apps and multithread handling libs like e.g. [synckit](https://github.com/un-ts/synckit), [sync-threads](https://github.com/lambci/sync-threads), etc.

**Comment by bartlomieju** [comment]
This will be solved by https://github.com/denoland/deno/issues/22783.

**Comment by mash-graz** [comment]
Thanks for fixing!
