### ISSUE TITLE
KvKeyPart types lists `symbol` as valid, this is not supported

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#22674]
Version: Deno 1.41.0

The unstable types for `Deno.KvKeyPart` indicates that a `symbol` is a valid key part:

https://github.com/denoland/deno/blob/942b2aaca57880152877a34006b30d2e982dec00/cli/tsc/dts/lib.deno.unstable.d.ts#L1318-L1324

But using a symbol as a key part results in the following error:

```
Uncaught TypeError: expected string, number, bigint, ArrayBufferView, boolean
    at doAtomicWriteInPlace (ext:deno_kv/01_db.ts:624:16)
    at Kv.set (ext:deno_kv/01_db.ts:97:32)
    at <anonymous>:1:31
```

**Comment by lucacasonato** [comment]
The bug is in the type - this should not be a valid type in the key.

**Comment by yazan-abdalrahman** [comment]
@lucacasonato 
Can you tell me how to reproduce it?

**Comment by lucacasonato** [comment]
Actually upon further inspection, this is not a bug. This is correct, to enable passing [`Deno.Kv.prototype.commitVersionstamp()`](https://docs.deno.com/api/deno/~/Deno.Kv.prototype.commitVersionstamp) as a key part:

```ts
await kv.set(["log", kv.commitVersionstamp()], { change: ... }); 
```
