### ISSUE TITLE
Cannot use async code in Jupyter notebooks with Deno kernel

### ISSUE THREAD

**Issue by sorenlouv** [denoland/deno#22689]
**Version**
deno 1.41.0 (release, aarch64-apple-darwin)
v8 12.1.285.27
typescript 5.3.3

Previously created as a bug in [vscode-jupyter](https://github.com/microsoft/vscode-jupyter/issues/15277) but I was asked to opening it for the Deno kernel instead.

**Problem**
I am using the Deno kernel with the [Jupyter Extension for VSCode](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter). I have noticed that async responses are not displayed correctly and it is often necessary to execute a cell multiple times before seeing the correct response. Instead of the correct response I often see a stale response (from a previous invocation) or no response at all (only `Promise { <pending> }`)

**Reproduce**

1. Install Deno  ([full instructions](https://docs.deno.com/runtime/manual/tools/jupyter)):

```
deno jupyter --unstable --install
```

2. Install [Jupyter Extension for VSCode](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter).

3. In VSCode, select Deno as Kernel

4. Execute the following notebook. After each execution try incrementing `/todos/1` to `/todos/2`, `/todos/3`, and see how the response does not always update reliably. 

```ts
fetch('https://jsonplaceholder.typicode.com/todos/1')
      .then(response => response.json())
      .then(json => console.log(json))     
```

**Screenshot**

<img width="1045" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/209966/8c96385e-ae07-4806-a67e-50285f828b0d">

**Comment by bartlomieju** [comment]
Does it work if you put `await` before your `fetch` call? The output you see is correct - you create a pending promise in this cell. That said, the `console.log` from `.then()` should be printed later.

**Comment by bartlomieju** [comment]
Unfortunately at the moment there isn't - Deno's LSP doesn't support notebooks nicely, but it's something we want to address in the short-to-medium term.

**Comment by sorenlouv** [comment]
Okay, makes sense. I'll close this issue.
