### ISSUE TITLE
JSR entrypoints are not resolved when using standard import maps

### ISSUE THREAD

**Issue by jsejcksn** [denoland/deno#22693]
JSR imports are resolved from a named [entrypoint](https://jsr.io/docs/using-packages#entrypoints) when using:

- a `jsr:` specifier, or
- a mapped specifier when using the config file field [`imports`](https://docs.deno.com/runtime/manual/getting_started/configuration_file#imports-and-scopes)

but not when using a standard import map (either as a CLI argument or via the config file field [`importMap`](https://deno.land/x/deno@v1.41.0/cli/schemas/config-file.v1.json?source=#L205)).

Here's an example to demonstrate:

```text
% deno --version
deno 1.41.1 (release, aarch64-apple-darwin)
v8 12.1.285.27
typescript 5.3.3
```

<details>
<summary>✅ <code>jsr:</code> specifier</summary>

`main.ts`:
```ts
import { TextLineStream } from "jsr:@std/streams@^0.218.2/text_line_stream";

console.log(TextLineStream.name);
```

Terminal:
```text
% deno run main.ts
TextLineStream
```
</details>

<details>
<summary>✅ <code>imports</code> config field</summary>

`deno.json`:
```json
{
  "imports": {
    "@std/streams": "jsr:@std/streams@^0.218.2"
  }
}
```

`main.ts`:
```ts
import { TextLineStream } from "@std/streams/text_line_stream";

console.log(TextLineStream.name);
```

Terminal:
```text
% deno run main.ts
TextLineStream
```
</details>

<details>
<summary>❌ import map (config)</summary>

`import_map.json`:
```json
{
  "imports": {
    "@std/streams": "jsr:@std/streams@^0.218.2",
    "@std/streams/": "jsr:@std/streams@^0.218.2/"
  }
}
```

`deno.json`:
```json
{
  "importMap": "./import_map.json"
}
```

`main.ts`:
```ts
import { TextLineStream } from "@std/streams/text_line_stream";

console.log(TextLineStream.name);
```

Terminal:
```text
% deno run main.ts
error: Failed to resolve the specifier ""@std/streams/text_line_stream"" as its after-prefix
            portion ""text_line_stream"" could not be URL-parsed relative to the URL prefix
            "jsr:@std/streams@^0.218.2/" mapped to by the prefix "@std/streams/"
    at file:///Users/deno/example/main.ts:1:32
```
</details>

<details>
<summary>❌ import map (CLI argument)</summary>

`import_map.json`:
```json
{
  "imports": {
    "@std/streams": "jsr:@std/streams@^0.218.2",
    "@std/streams/": "jsr:@std/streams@^0.218.2/"
  }
}
```

`main.ts`:
```ts
import { TextLineStream } from "@std/streams/text_line_stream";

console.log(TextLineStream.name);
```

Terminal:
```text
% deno run --import-map=import_map.json main.ts
error: Failed to resolve the specifier ""@std/streams/text_line_stream"" as its after-prefix
            portion ""text_line_stream"" could not be URL-parsed relative to the URL prefix
            "jsr:@std/streams@^0.218.2/" mapped to by the prefix "@std/streams/"
    at file:///Users/deno/example/main.ts:1:32
```
</details>

**Comment by lucacasonato** [comment]
You need to set the right hand side of the import map to `jsr:/@std/streams@^0.218.2/`. Otherwise the URL on the right is a "cannot-be-a-base" URL which you can not perform relative mappings with. See:

- Broken: https://jsdom.github.io/whatwg-url/#url=Li9mb28=&base=anNyOkBzdGQvc3RyZWFtc0BeMC4yMTguMi8=
- Working: https://jsdom.github.io/whatwg-url/#url=Li9mb28=&base=anNyOi9Ac3RkL3N0cmVhbXNAXjAuMjE4LjIv

This is unfortunately how the import map spec works - in `deno.json` we do some nice pre-processing on the import map to hide this detail, but when you pass `--import-map` we give you the standards compliant raw import map behaviour.

**Comment by jsejcksn** [comment]
> Otherwise the URL on the right is a "cannot-be-a-base" URL which you can not perform relative mappings with.

Ah, of course! Thanks for reminding me of that @lucacasonato — I missed it.

> nice pre-processing

While convenient, it feels like Deno is continuing to build more opaque magic into the runtime (which I remember to be very counter to its early philosophy of explicitness). 😕

**Comment by dsherret** [comment]
It's an extension of the import map standard in the deno.json. Going to close this one because I think it's resolved.
