### ISSUE TITLE
Import Data URL not working on Deno Deploy

### ISSUE THREAD

**Issue by mcgear** [denoland/deno#22695]
Version: Deno 1.41.0

I am trying to use code similar to this:
https://github.com/denoland/deno/blob/902a1137ea6021af8c56b82fa38b8084a89a4bb1/tests/testdata/dynamic_import/permissions_data_local.ts#L3

Just loads in a simple typescript class. This works fine locally, but isn't working on Deno Deploy. 

Would be great if this works on deno deploy as well. Wondering what i might be missing.

**Comment by piscisaureus** [comment]
This works in Deno Deploy *if* you use `application/javascript`. So the example you just linked to does actually work in Deploy. 
However dynamically importing a *typescript* class won't work currently, because in Deploy the typescript compiler isn't available at run-time.

**Comment by mcgear** [comment]
ahh, thank you. So i just need to transpile it first in theory? Is their any plan to support Deno Deploy typescript compiling at run time?

**Comment by mcgear** [comment]
What would be the best way to transpile at runtime?  esbuild wasm? Or is there something else?

**Comment by mcgear** [comment]
I thought a bit of my code might be useful. This is what works locally, but not in Deno Deploy:


  const fileContents = await toText(file.Contents);

  const enc = base64.encodeBase64(fileContents);

  const apiUrl = `data:application/typescript;base64,${enc}`;

  const apiModule = await import(apiUrl);

  const api = apiModule.default;

**Comment by mcgear** [comment]
Alright, i was able to get this working with esbuild.

I imported the WASM module:
```
import * as esbuild from 'https://deno.land/x/esbuild@v0.20.1/wasm.js';
```

Then, due to issues with using workers on deno deploy, had to add a call to:
```
await esbuild
    .initialize({
      worker: false,
    })
```

Then, i was able to update my code to use transpiled TS and a javascript data url:
```
  const fileContents = await toText(file.Contents);

  const result = await esbuild.transform(fileContents, { loader: 'ts' });

  const enc = base64.encodeBase64(result.code);

  const apiUrl = `data:application/javascript;base64,${enc}`;

  const apiModule = await import(apiUrl);

  const api = apiModule.default
```

**Comment by mcgear** [comment]
I opened this back up, to see if i could get some additional help on this.
