### ISSUE TITLE
Feature Request: import xxx.mjs file

### ISSUE THREAD

**Issue by axetroy** [denoland/deno#2270]
Some Javascript modules support exporting to .mjs

If Deno can support it, then we can reuse the existing modules in the community.

```typescript
import xxx from './xxx.mjs';
```

**Comment by ry** [comment]
I think this should work already? I don't think we examine the file extensions?

**Comment by axetroy** [comment]
@ry Currently not supported

```bash
> echo "console.log('hello world')" >> test.mjs
> echo "import './test.mjs'" >> test.ts
> deno test.ts
Uncaught Error: Unknown media type for: "./test.mjs" from "***".
```

**Comment by ry** [comment]
@axetroy Ah - it should be quite easy to fix - first add it here
https://github.com/denoland/deno/blob/e4354ce73984668d7a057e1b6f591dd566209369/cli/deno_dir.rs#L29-L37
maybe adjust a few asserts (only as necessary)
https://github.com/denoland/deno/blob/e4354ce73984668d7a057e1b6f591dd566209369/js/compiler.ts#L455-L458
And add a new test file: `tests/030_mjs.test`

You can run the test doing this:
```
./tools/build.py && ./tools/integration_test --filter 030_mjs
```
