### ISSUE TITLE
Print weird behavior with negative zeros

### ISSUE THREAD

**Issue by axetroy** [denoland/deno#2276]
I am writing a test case and found the weird behavior of printing `-0`.

It caused my test case to fail

### Test code

```typescript
console.log(-0);
```

### Print in the chrome

![屏幕快照 2019-05-03 15 06 11](https://user-images.githubusercontent.com/9758711/57123619-057b8500-6db5-11e9-9fab-ff77d8b69a4a.png)

### Print in Node.js

![屏幕快照 2019-05-03 15 07 01](https://user-images.githubusercontent.com/9758711/57123653-2217bd00-6db5-11e9-8926-ff431a9317c5.png)

### Print in Deno

![屏幕快照 2019-05-03 15 04 41](https://user-images.githubusercontent.com/9758711/57123635-0f9d8380-6db5-11e9-8eaf-bfd971aca610.png)

**Comment by kevinkassimo** [comment]
Node.js has a special handling of this in `lib/internal/util/inspect`:

```js
function formatNumber(fn, value) {
  // Format -0 as '-0'. Checking `value === -0` won't distinguish 0 from -0.
  return fn(Object.is(value, -0) ? '-0' : `${value}`, 'number');
}
```

We could do exactly the same.
