### ISSUE TITLE
test: timer firing in the next event loop triggers sanitizers

### ISSUE THREAD

**Issue by satyarohith** [denoland/deno#22764]
From https://github.com/denoland/deno/pull/22708#discussion_r1515250815
> Do you mind filing a bug against the sanitizers for this? We should not trigger the sanitizers if a timer fires in the next event loop.

To reproduce, remove last await in `[node/http2.createServer()]` unit test and run the test for several times until you get a timers leak error message.

**Comment by lucacasonato** [comment]
This is now done.
