### ISSUE TITLE
`promise` never resolve with `npm:util`

### ISSUE THREAD

**Issue by JOTSR** [denoland/deno#22781]
Version: Deno 1.41.1

# Summary

Promise produced by `promisify` from `npm:util` package never resolves (but reject works fine).

It block usage of `npm:usb` on windows (but works on linux) when calling async methods, however `promisify` seems to don't work on both platforms.

# Examples

## Resolve

```ts
Deno 1.41.1
exit using ctrl+d, ctrl+c, or close()
> import { promisify } from 'npm:util'
undefined
> await promisify(() => "resolve")()

//never resolved -> ctrl+c
[processus terminé avec le code 3221225786 (0xc000013a)]
```

## Reject

```ts
Deno 1.41.1
exit using ctrl+d, ctrl+c, or close()
> import { promisify } from 'npm:util'
undefined
> await promisify(() => { throw "reject" })()
Uncaught "reject"
>
```

**Comment by xBZZZZ** [comment]
node downloaded from https://nodejs.org/dist/v21.7.1/node-v21.7.1-linux-x64.tar.xz behaves similar:
```
Welcome to Node.js v21.7.1.
Type ".help" for more information.
> const { promisify } = require("util")
undefined
> await promisify(() => { throw "reject" })()
Uncaught 'reject'
> await promisify(() => "resolve")()
```
*ctrl+c*
```
Uncaught:
[Error [ERR_SCRIPT_EXECUTION_INTERRUPTED]: Script execution was interrupted by `SIGINT`] {
  code: 'ERR_SCRIPT_EXECUTION_INTERRUPTED'
}
> 
```

**Comment by lucacasonato** [comment]
This is not what `promisify` does. Please take a look at the docs: https://nodejs.org/api/util.html#utilpromisifyoriginal.

We behave the same as Node here.
