### ISSUE TITLE
Disable eval() as an option --disallow-code-generation-from-strings

### ISSUE THREAD

**Issue by base698** [denoland/deno#2279]
Node has a command line option to disable `eval`.  It was a v8-option implemented in 2011: https://bugs.chromium.org/p/v8/issues/detail?id=1258

Is this currently supported, or could it be enabled?

**Comment by kevinkassimo** [comment]
Yes. You can enable with `deno --v8-flags=--disallow-code-generation-from-strings`.

There was a bug with `--v8-flags` not correctly forwarding v8 specific flags to v8. This has since been resolved on the master branch in #2277 and will be available in the next release.

**Comment by base698** [comment]
Thanks!  Just built from source and it worked.
