### ISSUE TITLE
[regression-1.41.2] error: 'import', and 'export' cannot be used outside of module code

### ISSUE THREAD

**Issue by rracariu** [denoland/deno#22811]
Importing a `.js` file from `node_modules` is automatically treated as common js.
In `Deno 1.42.1` this was not the case.

Something like:
```
import * as foo from 'node_modules/my_package/my_module.js'
```
Will result in:
```
error: 'import', and 'export' cannot be used outside of module code
```
This error goes away if you rename that module to `my_module.mjs`

Note: Deno is configured with the unstable "byonm" flag.

```
deno 1.41.2 (release, aarch64-apple-darwin)
v8 12.1.285.27
typescript 5.3.3
```

**Comment by dsherret** [comment]
Can you show a concrete example? The module is maybe indeed a common.js module.

**Comment by rracariu** [comment]
The module is ES, it has the export clause that is where it actually errors out.
```
export function myFunction(args)...
```
The `package.json` contains a `"module": "index.js"` clause but is not marked as `{ "type": "module" }`

What I want here to happen is to manually load a specific file from that package. I'm explicitly importing that file and I don't expect Deno to treat it in a special way. This works with Vite and Deno prior to recent update.

**Comment by dsherret** [comment]
I think Deno is now just correctly erroring the same way that Node errors with that package. Hard to tell without a concrete example, but here is the behaviour you're describing happening in Node:

```
> node main.js
(node:11392) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
V:\scratch\node_modules\package\index.js:1
export function myFunction() {}
^^^^^^

SyntaxError: Unexpected token 'export'
    at internalCompileFunction (node:internal/vm:77:18)
    at wrapSafe (node:internal/modules/cjs/loader:1290:20)
    at Module._compile (node:internal/modules/cjs/loader:1342:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1437:10)
    at Module.load (node:internal/modules/cjs/loader:1212:32)
    at Module._load (node:internal/modules/cjs/loader:1028:12)
    at cjsLoader (node:internal/modules/esm/translators:359:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:308:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)

Node.js v21.6.1
```

**Comment by rracariu** [comment]
```sh
node_modules/test/foo.js
node_modules/test/foo.mjs
```
`foo.[m]js`:
```javascript
export function test() {}
```

`test.js`
```js
import {test} from `node_modules/test/foo.js`
```

Node will not work because it defaults to commonjs, changing the extension of the import and test file to `mjs` will work. I'm not sure what are you saying here? Are you saying that Deno must follow Node's behavior in only loading `.mjs` files as modules? I don't think it is right to have this special casing for `node_modules` folder.

For reference, Bun does what I expect to do, it just loads the `js` file, same as prior Deno versions did.

**Comment by dsherret** [comment]
Can you share the package name please? It's hard to tell without the concrete example. It's sounding like Deno is now properly resolving the .js file in the npm package as CommonJS the same way as Node.js does, which is very important for Node compatiblity.

**Comment by rracariu** [comment]
What I want here is just to import a file. I don't want to import a package, and I don't want Deno to automatically assume that I want Node's behavior if the import path contains `node_modules`.

So, it is really not important what is the package I want to work with, it is just a path with some file in them.
But to entertain this, let's use `@clerk/backend: "0.38.3"`

`test.js`
```js
import { AuthStatus } from './node_modules/@clerk/backend/dist/esm/index.js'
console.log(AuthStatus.SignedIn)
```

`Deno 1.41.1`
```sh
deno run test.js
signed-in
```

`Bun 1.0.30`
```sh
bun run test.js
signed-in
```

`Node 21.7.0`
```sh
node --experimental-detect-module test.js
signed-in
```

**Comment by dsherret** [comment]
> What I want here is just to import a file. I don't want to import a package, and I don't want Deno to automatically assume that I want Node's behavior if the import path contains node_modules.

When using the unstable byonm feature or when not `"nodeModulesDir": false` with a package.json, Deno will use Node's rules for CJS and ESM detection. In this case, it is sounding like it is correctly determining that the .js file is considered a commonjs module.

> So, it is really not important what is the package I want to work with, it is just a path with some file in them.
But to entertain this, let's use @clerk/backend: "0.38.3"

`@clerk/backend` exports `./dist/index.js` for Node and Deno resolves that when importing that package as well (though it seems there is a bug related to package imports. I'm getting an incorrect `Cannot find module '#crypto'` and will fix that).

I've opened https://github.com/denoland/deno/issues/22818 to add an unstable flag for resolving CJS modules like `--experimental-detect-module`, but overall it not treating that CJS defined module as CJS with BYONM was a bug that seems fixed and is now correctly raising the error you're encountering similar to Node by default.

**Comment by dsherret** [comment]
FWIW, `@clerk/backend` will load correctly in the next patch release of Deno once https://github.com/denoland/deno/pull/22821 lands.

```
> cat main.js
import { Clerk } from '@clerk/backend';
console.log(Clerk);
> deno run main.js 
error: Uncaught (in promise) Error: Cannot find module '#crypto'
Require stack:
- V:\scratch\node_modules\@clerk\backend\dist\index.js
- V:\scratch\node_modules\@clerk\backend\dist\index.js
    at Function.Module._resolveFilename (node:module:622:15)
    at Function.Module._load (node:module:500:27)
    at Module.require (node:module:675:19)
    at require (node:module:789:16)
    at Object.<anonymous> (file:///V:/scratch/node_modules/@clerk/backend/dist/index.js:270:29)
    at Object.<anonymous> (file:///V:/scratch/node_modules/@clerk/backend/dist/index.js:3126:4)
    at Module._compile (node:module:731:34)
    at Object.Module._extensions..js (node:module:745:10)
    at Module.load (node:module:656:32)
    at Function.Module._load (node:module:537:12)
```

Next Deno patch:

```
> ../deno/target/debug/deno run main.js
[Function: Clerk]
```

**Comment by dsherret** [comment]
Yes, it appears working. Also, I will try to get https://github.com/denoland/deno/issues/22818 in as soon as possible (hopefully next week) in order to get this original issue working.

**Comment by rracariu** [comment]
> Yes, it appears it loads now. Also, I will try to get #22818 in as soon as possible (hopefully next week) in order to get this original issue working.

Sounds good, thanks!
