### ISSUE TITLE
Compiled binary support for typescript

### ISSUE THREAD

**Issue by itsfuad** [denoland/deno#22828]
As we know typescript has a typesystem. We can improve our optimization based on that. Also **Deno** uses **Rust** which is meant to be fast. 

So why not compile the typecript code to a near native code then run it?

If its not possible then at least we should have performace raise for typescriot rather than just type safety.

**Comment by xBZZZZ** [comment]
> As we know typescript has a typesystem.

yes, but type that is written in code is not guaranteed to be same as type at runtime:
```typescript
class MyArray extends Array<number>{
	get [""+"0"]():string{
		return "a string"
	}
}
const ma:MyArray=new MyArray(1)
const ma0:number=ma[0]
console.log(typeof ma0)//logs string
```

**Comment by bartlomieju** [comment]
We have no way to compile TypeScript to native code. If such a solution comes around we might evaluate it and act on it. Right now there's nothing actionable for us to do here.
