### ISSUE TITLE
`deno publish --dry-run` do not check specifier `jsr:` version constraint

### ISSUE THREAD

**Issue by hugoalh** [denoland/deno#22835]
Happened on Deno v1.41.2, not tested on other versions.

For example, at the script:

```ts
import { escape } from "https://deno.land/std@0.219.1/regexp/escape.ts";
```

And at the config (look at the missing version constraint at the right side):

```jsonc
{
  "imports": {
    "https://deno.land/std@0.219.1/regexp/escape.ts": "jsr:@std/regexp/escape"
  }
}
```

Then run `deno publish --dry-run`, and it is success.

However, run `deno publish` and it is fail:

```
error: Failed to publish @XXXX/XXXX@XXXX

Caused by:
    Failed to publish @XXXX/XXXX at XXXX: specifier 'jsr:@std/regexp/escape' is missing a version constraint
```

`deno publish --dry-run` should also check specifier `jsr:` version constraint.

**Comment by NfNitLoop** [comment]
Just ran into this myself as well.
