### ISSUE TITLE
Missing basic event listener on request - response

### ISSUE THREAD

**Issue by itsfuad** [denoland/deno#22836]
Nodejs has,
```js
req.on("data", (data) => console.log(`on data: ${data.length}`));
req.on("close", () => console.log("req closed"));
req.on("aborted", () => console.log("req aborted"));
req.on("error", (err) => console.log("req error", err));
```

These events are very useful when server is doing a heavy task for the user. But it continues to do the work even the client is disconnected.

This is a serious issue in Deno. It doesn't have any way to know these things.

For response, node has,
```js
res.on('end', () => console.log('Streaming is done'));
```
This way we know that the server has done the file or any kind of data streaming. Which is also missing in Deno. 

It has a lot own methods. So why not implement those what developers need?

**Comment by lucacasonato** [comment]
You can do `req.body` to get the body.

You can use `req.body.getReader().closed` to figure out when the request body is fully received (you probably do not need to use this though, when you are using the idiomatic `ReadableStream<Uint8Array>` APIs)

You can get notified about abort through `req.signal`, which is an `AbortSignal`.

You can get notified on `res.end` by looking at the `finished` promise passed in the second argument to the `Deno.serve()` callback.
