### ISSUE TITLE
Update type declarations for new Set methods

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#22851]

**Comment by bartlomieju** [comment]
PR to TypeScript that adds these methods: https://github.com/microsoft/TypeScript/pull/57230

I'm thinking we should fork these (adding appropriate attribution) and then remove them in TypeScript 5.5 (when this PR is expected to land).

**Comment by dsherret** [comment]
Not sure we should do this yet when it seems like they haven't agreed upon the names in the TS PR.

**Comment by bartlomieju** [comment]
@dsherret I think the names of APIs are fixed and we already natively support these new APIs in both TS and JS - they've been added in V8 12.3 that we now use. IMO it's better to add any type declarations and improve them over time than not expose these APIs for TS users.

**Comment by dsherret** [comment]
Discussed in chat: going to use that PR, but use the `Set` type instead of `ReadonlySetLike`. Then we can restrict it further to readonly once it lands in typescript.
