### ISSUE TITLE
Type checking fails to find type in npm package

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/deno#22867]
Steps to reproduce:

1. Clone https://github.com/denoland/fresh
2. Run `deno task check:types`

Error:

```sh
$ deno task check:types
Task check:types deno check **/*.ts && deno check **/*.tsx
error: Failed resolving types. Relative import path "@jridgewell/trace-mapping" not prefixed with / or ./ or ../ and not in import map from "file:///Users/marvinh/dev/denoland/fresh-2/www/node_modules/.deno/@jridgewell+gen-mapping@0.3.4/node_modules/@jridgewell/gen-mapping/dist/types/gen-mapping.d.ts"
    at file:///Users/marvinh/dev/denoland/fresh-2/www/node_modules/.deno/@jridgewell+gen-mapping@0.3.4/node_modules/@jridgewell/gen-mapping/dist/types/gen-mapping.d.ts:1:37
```

Looking at the structure in `node_modules` the package `@jridgewell/trace-mapping` is at the right place and has appropriate typings. It's for some reason not found anymore.

Version: Deno 1.41.2

**Comment by HasanAlrimawi** [comment]
That's not re-producible using `deno 1.46.1 (stable, debug, x86_64-pc-windows-msvc)` & `fresh v1.7.1`
