### ISSUE TITLE
Switch `chrono` to use `now` feature and remove custom `now` implementations

### ISSUE THREAD

**Issue by mmastrac** [denoland/deno#22864]
This will allow us to remove the `utc_now` function.

Feature landed in:

https://github.com/chronotope/chrono/pull/1343

**Comment by muddlebee** [comment]
taking this up as well :eyes:

**Comment by anukulrathore** [comment]
@muddlebee are you working on this, can i start working on it?

**Comment by fbaltor** [comment]
I guess my PR fixes the issue. But there is an error in the `test debug macos-x86_64` and I don't know how to better investigate it.
