### ISSUE TITLE
Deno failed to run with WasmGC

### ISSUE THREAD

**Issue by magic-akari** [denoland/deno#22861]
Version: 
```
deno 1.41.2 (release, aarch64-apple-darwin)
v8 12.1.285.27
typescript 5.3.3
```

Search words:
- WasmGC
- WASM Reference types

Minimal reproducible code:

```TypeScript
import init, { format } from "npm:@wasm-fmt/dart_fmt";

await init();

const input = `void main() { print('Hello, World!'); }`;

const formatted = format(input, "main.dart");
console.log(formatted);
```

Expected output:
```
void main() {
  print('Hello, World!');
}
```

Actual output:
```
error: Uncaught (in promise) Exception [WebAssembly.Exception] {}
```

Note: as WasmGC will introduced and enabled in Node@22, which has not been released yet, I am unable to verify its proper functioning within Node. 
However, the following code has been confirmed to run successfully in Chrome.

```html
<!DOCTYPE html>
<html lang="en">

<body>
    <script type="module">
        import init, { format } from "https://cdn.jsdelivr.net/npm/@wasm-fmt/dart_fmt/+esm";

        await init();

        const input = `void main() { print('Hello, World!'); }`;

        const formatted = format(input, "main.dart");
        console.log(formatted);
    </script>
</body>

</html>
```

**Comment by bartlomieju** [comment]
Try running with `--experimental-wasm-gc` V8 flag:
```
deno run --v8-flags=--experimental-wasm-gc ./your/file.ts`
```

Do you have a link to the Node issue that enables it?

**Comment by magic-akari** [comment]
> Try running with `--experimental-wasm-gc` V8 flag:
> 
> ```
> deno run --v8-flags=--experimental-wasm-gc ./your/file.ts`
> ```

Still no luck, I get the same error.

---

And I tried `--experimental-wasm-gc` in node and get a new error:

```
CompileError: WebAssembly.Module(): supertype count of 1542 exceeds internal limit of 1 @+14
```

**Comment by lucacasonato** [comment]
@magic-akari Have you tried this again recently?

**Comment by magic-akari** [comment]
> @magic-akari Have you tried this again recently?

Nothing has changed, the problem is still there.

version:

```
deno 1.44.1 (release, aarch64-apple-darwin)
v8 12.6.228.3
typescript 5.4.5
```

**Comment by lucacasonato** [comment]
@devsnek tells me this also fails in Node. It looks like the Wasm is incorrect?

I'll close this for now - please reopen if you can provide an example that works anywhere else (Chrome, Firefox, Safari, Node) - but does not work in Deno.

**Comment by magic-akari** [comment]
I will update this table if things change.

| runtime | result |
| ------- | ------ |
| Chrome  | ✅ 120 |
| Firefox | ✅ 126 |
| Safari  | ❌     |
| node    | ❌     |
| Deno    | ❌     |
| bun     | ❌     |

<summary>Some error messages maybe helpful
<details>
node@22 reports error without details.
node@20 requires `--experimental-wasm-gc` flag and then report the following error with the flag enabled:

```
❯ node --experimental-wasm-gc main.js
file:///Users/akari/Developer/test_wasm/node_modules/@wasm-fmt/dart_fmt/dart_fmt.js:22
                return new WebAssembly.Module(module);
                       ^

CompileError: WebAssembly.Module(): supertype count of 1679 exceeds internal limit of 1 @+14
    at normalize (file:///Users/akari/Developer/test_wasm/node_modules/@wasm-fmt/dart_fmt/dart_fmt.js:22:10)
    at async default (file:///Users/akari/Developer/test_wasm/node_modules/@wasm-fmt/dart_fmt/dart_fmt.js:45:17)
    at async file:///Users/akari/Developer/test_wasm/main.js:3:1

Node.js v20.14.0
```

bun reports the following error:

```
❯ bun main.js
17 | //         return (wasm = instantiate(module));
18 | // }
19 |
20 | function normalize(module) {
21 |    if (!(module instanceof WebAssembly.Module)) {
22 |            return new WebAssembly.Module(module);
              ^
CompileError: WebAssembly.Module doesn't parse at byte 14: 0th type failed to parse because rec types are not enabled (evaluating 'new WebAssembly.Module(module)')
      at normalize (/Users/akari/Developer/test_wasm/node_modules/@wasm-fmt/dart_fmt/dart_fmt.js:22:10)
```

</details>
</summary>
