### ISSUE TITLE
Announce: change in versioning scheme

### ISSUE THREAD

**Issue by ry** [denoland/deno#2288]
We've been incrementing the patch number in the releases each week, while introducing large changes. (This is actually allowed inside of semver, as it's v0.y.z still.) However, moving forward I would like to start incrementing the minor version each week, starting this week.

So very soon we will release "v0.4.0", and next week "v0.5.0". If there are small fixes made to a release, we'll increment the patch number ([an example of this would have been the v0.3.10 release](https://github.com/denoland/deno/releases/tag/v0.3.10)).

I will migrate all the issues tagged with "v0.4" to "v1.0".

The CLI API has changed radically in the last few weeks, so this seems as good a time as any to make this change.

I just want to forewarn people that "v0.4.0" doesn't mean that we've reached a new level of stability. We're still under heavy development and I expect that to continue throughout the summer.

**Comment by zekth** [comment]
Is `deno_std` concerned with this change?

**Comment by ry** [comment]
@zekth Not really. It will continued to be tagged and versioned along with Deno. Which btw, I've just pushed the tag for v0.4.0
https://github.com/denoland/deno_std/tree/v0.4.0
