### ISSUE TITLE
[node-compat] Lack of `AsyncLocalStorage.disable()` implementation

### ISSUE THREAD

**Issue by yasaichi** [denoland/deno#22886]
Version: Deno 1.41.1

When I was using [MSW](https://mswjs.io/), one of the most popular HTTP mocking libraries, I faced an error caused by a lack of `AsyncLocalStorage.disable()` of `node:async_hooks` module. Here is the minimum code to reproduce the issue:

```shell
$ node
Welcome to Node.js v20.5.0.
Type ".help" for more information.
> new (await import('node:async_hooks')).AsyncLocalStorage().disable()
undefined
```

```shell
$ deno
Deno 1.41.1
exit using ctrl+d, ctrl+c, or close()
REPL is running with all permissions allowed.
To specify permissions, run `deno repl` with allow flags.
> new (await import('node:async_hooks')).AsyncLocalStorage().disable()
Uncaught TypeError: (intermediate value).disable is not a function
    at <anonymous>:1:81
```

This would help MSW work in Deno and more people adopt this great runtime. Thanks!

**Comment by yasaichi** [comment]
@bartlomieju 
Could you reopen the issue? Because #24402 was reverted and has not been re-merged yet.

**Comment by devsnek** [comment]
Thanks for reminding me... https://github.com/denoland/deno/pull/25140
