### ISSUE TITLE
deno vendor fails for recent versions of the std library

### ISSUE THREAD

**Issue by boywithkeyboard** [denoland/deno#22889]
**Describe the bug**

I tried to `deno vendor` a module which imports a submodule of the std library and received the following error.

```
error: Expected a JavaScript or TypeScript module, but identified a Unknown module. Importing these types of modules is currently not supported.
  Specifier: https://deno.land/std@0.219.0/crypto/_wasm/lib/deno_std_wasm_crypto.generated.d.mts
    at https://deno.land/std@0.219.0/crypto/_wasm/lib/deno_std_wasm_crypto.generated.mjs:5:22
```

The console error redirects me to the following line of code:

```js
/// <reference types="./deno_std_wasm_crypto.generated.d.mts" />
```

So I assume it's an issue with the `.d.mts` extension or something?

**Expected behavior**

Should throw no error.

**Environment**

- deno version: 1.41.2
- std version: 0.219.0

**Comment by iuioiua** [comment]
@boywithkeyboard, does the same issue occur when you use `jsr:@std/crypto@0.224.0` as the import specifier instead of `https://deno.land/std@0.219.0/crypto/mod.ts` in the module you're trying to vendor?
