### ISSUE TITLE
Deno.serve request halting due to mismatch content-length header value (v1.41.2)

### ISSUE THREAD

**Issue by DSergiu** [denoland/deno#22888]
Issue: mismatch `content-length` header value results in request halting.

Version:
```sh
$ deno --version
deno 1.41.2 (release, x86_64-unknown-linux-gnu)
v8 12.1.285.27
typescript 5.3.3
```

Steps to reproduce:
1. Start the following server: 
```sh
deno run --allow-net server.ts
```

```ts
Deno.serve({ port: 8001 }, async (req: Request) => {
    const st = performance.now();
    const contentLength = req.headers.get("content-length");
    console.log({ contentLength });

    const ab = await req.arrayBuffer();
    const abLength = ab.byteLength;
    console.log({ abLength });

    console.log({ time: `${performance.now() - st}ms`, contentLength, abLength });

    return new Response(JSON.stringify({ contentLength, abLength }));
});
```

2. Curl with valid and invalid `content-length` header
```sh
curl -X POST http://0.0.0.0:8001 -H "content-length: 2" -d '{}'
```
 * produces following log:
```
{ contentLength: "2" }
{ abLength: 2 }                                 
{ time: "4ms", contentLength: "2", abLength: 2 }
```

```sh
curl -X POST http://0.0.0.0:8001 -H "content-length: 3" -d '{}'
```
  * produces following log:
```
{ contentLength: "3" }
```
  * never responds, code execution halts at ` const ab = await req.arrayBuffer();` - not expected!
  * canceling the curl execution makes `req.arrayBuffer()` to throw the following error, could be expected:
```
Error: error reading a body from connection: end of file before message length reached
    at async readableStreamCollectIntoUint8Array (ext:deno_web/06_streams.js:1074:19)
    at async consumeBody (ext:deno_fetch/22_body.js:241:9)
```

**Comment by mmastrac** [comment]
This is by design: if you send a content-length header, you _must_ send that many bytes to the endpoint. If you don't know the size you're sending upfront, you should use chunked encoding.

**Comment by DSergiu** [comment]
What is a good strategy to prevent an attacker from sending such malformed requests and thus resulting in server resource locking? I would expect `req.arrayBuffer()` to immediately throw / return in the case `content-length` does not match the actual payload size. Currently, in this case,  `req.arrayBuffer()` halts indefinitely. @mmastrac

**Comment by littledivy** [comment]
Use timeouts to cancel reading the body if the client cannot be trusted.
