### ISSUE TITLE
Regression: make worker setup synchronous (#22815) may lead to freeze

### ISSUE THREAD

**Issue by mash-graz** [denoland/deno#22911]
Version: from d69aab6 on (#22815)

The freeze happens while calling `op_message_port_post_message` in `ext/web/13_message_port.js`  https://github.com/denoland/deno/blob/d69aab62b0789dd54b8c09b54af022a38f060b5b/ext/web/13_message_port.js#L146 and then in `message_port.rs` while getting the MessagePort resource handler https://github.com/denoland/deno/blob/d69aab62b0789dd54b8c09b54af022a38f060b5b/ext/web/message_port.rs#L210

It can be reproduced by a setup described in https://github.com/denoland/deno/pull/22841#issuecomment-1989716601 and merging the upstream changes till d69aab6 or later.

**Comment by bartlomieju** [comment]
Is there a chance you could boil down the reproduction? I'm having trouble reproducing a hang with the `jco` example.

**Comment by mash-graz** [comment]
Your output is exactly the same as on my machine!

When your commit is added, the worker stops at the already mentioned position and you do not get more results. :(

I don't know if I can produce a more simple demonstration example.
The simple ones all run fine. Therefore, we don't see any errors in the integration tests.

**Comment by bartlomieju** [comment]
How did you establish that it stops on getting the handle from the resource table? I added some prints but they appear to be swallowed by mocha

**Comment by mash-graz** [comment]
I could enter simple `console.log()` messages all the time and saw the output. 

These are the last ones, still on my terminal: ;)

```
❯ ../../deno/target/debug/deno run -A npm:mocha -u tdd ./packages/preview2-shim/test/test.js

  Node.js Preview2
test stdouttest stderr    ✔ Stdio
MASH1
M3-4
```

The MASH2 after the `postMessage` doesn't appear anymore...

But I also examined the issue with two debugger windows. 
Analyzing this kind of cross thread happenings is always rather painful.

**Comment by mash-graz** [comment]
when using the debugger the whole app sometimes cashed an left this report:

```
Platform: linux x86_64
Version: 1.41.2
Args: ["../../deno/target/debug/deno", "run", "--inspect-brk", "-A", "npm:mocha", "-u", "tdd", "./packages/preview2-shim/test/test.js"]

thread 'worker-0' panicked at /home/mash/.cargo/registry/src/index.crates.io-6f17d22bba15001f/deno_core-0.269.0/ops.rs:52:5:
op op_message_port_post_message was not marked as #[op2(reentrant)], but re-entrantly invoked op op_apply_source_map
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
But this could also be just a side effect of the debugger interception...

**Comment by bartlomieju** [comment]
I did more debugging and it appears the problem is in this line:
```
const status = Atomics.wait(sharedBufferView, 0, 0, CALL_TIMEOUT);
```
from `preview2-shim/lib/synckit/index.js`. The `Atomics.wait` never finishes. This might require some changes in `deno_core`. CC @mmastrac have you played with Atomics in `deno_core` yet?

**Comment by mash-graz** [comment]
yes -- but this worked without troubles before.

This wait will be triggered from the worker side by `preview2-shim/lib/synckit/index.js` L122-123 utilizing:

```
      Atomics.add(sharedBufferView, 0, 1);
      Atomics.notify(sharedBufferView, 0);
```

But this passage is very likely not reached anymore...

**Comment by aapoalas** [comment]
Oh this is then probably a repeat of https://github.com/denoland/deno/issues/15358

**Comment by mash-graz** [comment]
@aapoalas: That's an interesting hint!

Do you have an idea/explanation, why it worked before, but not after this changes, by looking at the modified code?

**Comment by bartlomieju** [comment]
Er, I did some more debugging and it appears that `parentPort.on("message", ()...);` is not called in the worker thread. I'll keep debugging this tonight.

**Comment by aapoalas** [comment]
> @aapoalas: That's an interesting hint!
> 
> Do you have an idea/explanation, why it worked before, but not after this changes, by looking at the modified code?

If something else is triggering the event loop of the main worker it will kick this code to move again. Presumably that something isn't calling anymore.

**Comment by bartlomieju** [comment]
I found the first problem, it introduced in https://github.com/denoland/deno/pull/22647. 

The worker thread's event loop exits before the first message is even sent. 

Once I revert that I indeed get a hang in `state.resource_Table.get::<MessagePortResource>()`.

**Comment by mash-graz** [comment]
@aapoalas:  yes -- the worker is broken...

@bartlomieju: thanks for all your help!

And just as a small hint to avoid unnecessary efforts:

This whole `jco` code is still not compatible with `deno`. It's therefore important to ignore a few other obstacles. The main blocking issue is related to the fact, that some filesystem related operations share file descriptor numbers over the border between main instance and worker resp. ignore their operating context. This doesn't seem to have fatal consequences under `node`, but it clearly violates the rules of `deno`...

and about exiting the main loop:

before this most recent changes, there was no `unref()` present inside the worker when running on `deno`, so I left it in the code after checking its existence at runtime for use in node. But now, where this function is available, it may also interfere...

**Comment by bartlomieju** [comment]
Another update: what you're seeing is not a hang in `state.resource_Table.get::<MessagePortResource>()` but rather a "Bar resource ID" error:
```
after get  in op_message_port_message CustomError {
    class: "BadResource",
    message: "Bad resource ID",
}
```
which means the error is bubbled up and the worker thread exits or errors. I will keep pounding at it as it seems like a legit failure. The code in `jco` seems reasonable in what it tries to do. I wonder if we should aim to try and run `jco` directly without any changes for Deno.

**Comment by mash-graz** [comment]
Thanks for this new insight! :)

I'm really happy about your help in this case, because it would definitely need lots of time, before I understand this low level mysteries of `deno` and `tokio`.

Fixing the cause of this particular error, would indeed make a lot of sense, because it's the rather popular `SyncKit` library, which seems to be affected. A software component, which seems to have more than 7.5 mil. downloads per week.

And yes, I'm rather optimistic, that `jco` will run fine under `deno`after fixing a few problems. The file related faults in the test runs are definitely justified and require code changes. All other incompatibilities, that I found up to now, are of more or less negligible nature. `deno` does not support real network `bind` operations and often reports wrong values for autoconfigured ports or interface IPs. But that's not very important in practice.

**Comment by bartlomieju** [comment]
Okay, I think I found the root cause of the problem - let's skip the problem of event loop exiting for now (we might revert https://github.com/denoland/deno/pull/22647 for the time being).

The root cause is that you pass a `MessagePort` instance in `workerData` field. This data undergoes the same structured clone algorithm as if you used `worker.postMessage()` however in this case transferring the `MessagePort` instance doesn't work correctly.

I don't yet understand why that's the case and I will need more time to figure it out, but I'm confident that I pinpointed the root cause of the problem.

**Comment by mash-graz** [comment]
Whoow! That's an astounding finding!

But in fact it looks surprisingly similar to the troubles with the communicated file descriptors.
`deno` resp. `tokio` seems to divide the active realms and validity of RIDs very strictly.

Nevertheless, its interesting, that it didn't affect the version without this commit.

Thanks!

**Comment by bartlomieju** [comment]
@mash-graz can you open a separate issues about FDs? This is another problem that we'll have to tackle because Deno doesn't really operate on raw FDs and our Node compat layer that touches on them is really lacking.

**Comment by bartlomieju** [comment]
@mash-graz I fixed both problems. You can use `deno upgrade --canary` in about an hour to get latest version with fixes included. Let me know if you hit any more problems, but I think we can now close this particular issue.

**Comment by mash-graz** [comment]
Thanks for all your work!
I'm eagerly looking forward to testing it and study your code changes.

But right now I'm laying with a cold in bed and everything runs more slowly.
That's also the reason, why this other promised PR rewrite will take slightly longer.

**Comment by bartlomieju** [comment]
@mash-graz have you had a chance to test it? Can this issue be now closed?

**Comment by mash-graz** [comment]
In my recent tests everything runs exceptional well -- THANKS! :)

I just found another way to freeze `node:worker_threads` whenever I use async functions/timers/etc. in CSJ script content.

It's easily reproducible by enabling L13 in one of the unit-test files:
https://github.com/denoland/deno/blob/d263c632e3d5a91fd6f9fffc598128d87c5621cd/tests/unit_node/testdata/worker_module/cjs-file.cjs#L3-L14

This could be caused by a completely different flaw, but very likely also have similar roots as fixed here by you in this context.

But perhaps we should better close this ticket and open another one for this other much less important application context.

**Comment by bartlomieju** [comment]
@mash-graz I agree, a separate issue for this particular problem would be better suited. I think we'll be able to fix it this week.

**Comment by mash-graz** [comment]
O.k. I'll open one...

**Comment by mash-graz** [comment]
This one can be closed now.
Thanks for all your efforts!
