### ISSUE TITLE
suggestion: check for uncommitted changes in `deno publish --dry-run`

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno#22936]
Currently, a dry run can succeed with uncommitted changes. However, the same codebase, in the same state, will fail when trying actually to publish. I suggest checking uncommitted changes in `deno publish --dry-run`. Furthermore, I think `deno publish --dry-run --allow-dirty` should behave as expected.

Example from the Standard Library:
- [Dry run succeeds](https://github.com/denoland/deno_std/actions/runs/8285917384/job/22674672886)
- [Real run fails](https://github.com/denoland/deno_std/actions/runs/8285101246) due to uncommitted changes

**Comment by bartlomieju** [comment]
Yes, we should totally do it. @iuioiua do you want to tackle that one? Seems very approachable.

**Comment by iuioiua** [comment]
Yep. I'll do it 👍🏾
