### ISSUE TITLE
Caching quick fix should appear before remove

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#22949]
I often write an import statement that I haven't used yet or cached, and Deno will suggest that I remove the import first before caching it.

![image](https://github.com/denoland/deno/assets/1609021/e42740a8-82dd-4b29-88bb-77b417343bc9)

**Comment by bartlomieju** [comment]
I already asked @nayeemrmn to enable cache on save for the upcoming minor release.

**Comment by dsherret** [comment]
Would be good to do both
