### ISSUE TITLE
missing `node` related docs

### ISSUE THREAD

**Issue by mash-graz** [denoland/deno#22943]
Although I really like the progress and the massive efforts to improve denos `node` compatibility, but I also have to state, that all this integration into the default runtime, has somehow weakened the transparency and especially the availability of API documentation.

Whenever you google for a `node` related API documentation for use in deno, you will get links to old `https://deno.land/std/node (< @0.177.0)` pages, because since this move of the node compatibility into the runtime repo there isn't any more actual API docu available. There are just these more general chapters about node compatibility and ported module lists to find, but nothing more satisfying. 

That's ok for all those `node` libs, where you can get the canonical interface description on the `node` website. But if you are looking for more specific stuff, which very likely will look a little bit different in case of `deno` -- for example the `node:module` section and its  `createRequire` function in particular -- it would be really helpful to find the necessary docs on the `deno` homepage, just like any other API documentation.

**Comment by ry** [comment]
I agree this is a big problem. We’re planning to introduce much improved node docs in the coming months

**Comment by lucacasonato** [comment]
Closing as this is not actionable right now - we're going to address this soon, but tracking it here is not useful.
