### ISSUE TITLE
The type of a structuredClone result is `any`

### ISSUE THREAD

**Issue by sylc** [denoland/deno#22958]
Version: deno 1.41.3 (release, x86_64-pc-windows-msvc)
v8 12.3.219.9
typescript 5.3.3

The type of a structuredClone object is `any`. See the below example. deno check things a2 is `any`. 
In node (`npm i typescript@5.3.3; npx tsc --noImplictAny ./test.ts`) or in the typescript playground, the example does not report any error.

```ts
const a1 = [{ id: 1 }, { id: 2 }];
const a2 = structuredClone(a1);
a2.sort((a, b) => a.id - b.id);
console.log(a2);
```
```txt
deno check ./test.ts       
Check file:///C:/Users/.../test.ts
error: TS7006 [ERROR]: Parameter 'a' implicitly has an 'any' type.
a2.sort((a, b) => a.id - b.id);
         ^
    at file:///C:/.../test.ts:3:10    

TS7006 [ERROR]: Parameter 'b' implicitly has an 'any' type.
a2.sort((a, b) => a.id - b.id);
            ^
    at file:///.../test.ts:3:13    

Found 2 errors.
```

in vscode with deno enabled
<img width="806" alt="image" src="https://github.com/denoland/deno/assets/10268458/967e3aa9-ea49-4822-a7c3-39b46aba2df8">

with deno disabled, a2 is correctly inferred to be the same type as a1.
<img width="662" alt="image" src="https://github.com/denoland/deno/assets/10268458/99e7d168-4777-4500-9670-962d254b7b0d">

**Comment by Hajime-san** [comment]
The `structuredClone` in `dom` is defined like below.
```ts
declare function structuredClone<T = any>(value: T, options?: StructuredSerializeOptions): T;
```
https://github.com/denoland/deno/blob/9c5ddf7c69f0d3ddaa93b194f0020944569e0e3e/cli/tsc/dts/lib.dom.d.ts#L27951-L27952

But it's in `deno_web` as follows.

https://github.com/denoland/deno/blob/9c5ddf7c69f0d3ddaa93b194f0020944569e0e3e/ext/web/lib.deno_web.d.ts#L1127-L1130
