### ISSUE TITLE
`deno publish` fails with `noUnusedParameters`

### ISSUE THREAD

**Issue by EdJoPaTo** [denoland/deno#22959]
There are a bunch of Typescript compiler options which ensure better code quality. Therefore, I enable the ones that are not enabled by default (See https://docs.deno.com/runtime/manual/advanced/typescript/configuration). (Yes I know compiler options are discouraged in the docs, but they are better than nothing and don't all exist as lints. When I shouldn't use them provide me a good alternative. But that's a different issue.)

Running `deno publish --dry-run` seems to use them which errors on `noUnusedParameters`.

`deno.jsonc`:

```json
{
	…,
	"compilerOptions": {
		"noUnusedParameters": true,
	}
}
```

```plaintext
$ deno publish --dry-run
Check file://…/mod.ts
Checking for slow types in the public API...
Check file://…/mod.ts
error: Failed ensuring public API type output is valid.

TS6133 [ERROR]: 'text' is declared but its value is never read.
export function example(argument: string): string {
                        ~~~~~~~~
    at file://…/mod.ts:3:25

[…]

Found 42 errors.

You may have discovered a bug in Deno. Please open an issue at: https://github.com/denoland/deno/issues/
```

```plaintext
$ deno --version
deno 1.41.3 (release, x86_64-unknown-linux-gnu)
v8 12.3.219.9
typescript 5.3.3
```

**Comment by dsherret** [comment]
This diagnostic should be suppressed for fast checked modules.
