### ISSUE TITLE
jsx precompile: another double escape bug

### ISSUE THREAD

**Issue by c-antin** [denoland/deno#22965]
Version: Deno 1.41.3

If a jsx function component accepts a fragment as prop the precompiled jsx template string is escaped twice.

Steps to reproduce: see repo https://github.com/c-antin/jsx_precompile_bugs (last block in `main.tsx`)

This is related to #22577. Thanks for fixing it so fast, btw :)

**Comment by c-antin** [comment]
Don't know if it's any help, but how about wrapping the escaped Fragment(s) in `_jsxTemplate("&quot;false&quot;")`. The *jsx-runtime* could then detect if it's already a marked `JSXTemplate` and not escape it again.
This would further ensure that Fragments are not plain strings, but rather marked `JSXTemplate extends String`.
cons: breaks backwards compat

**Comment by marvinhagemeister** [comment]
Yeah, the solution is likely either that or keep Fragments as being Fragments.
