### ISSUE TITLE
ArrayBuffer missing typings for Options argument

### ISSUE THREAD

**Issue by BlackAsLight** [denoland/deno#22986]
Version: Deno 1.41.3
According to the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer/ArrayBuffer), the `ArrayBuffer` constructor takes an `options` argument, but those typings don't seem to exist.
```ts
const buffer = new ArrayBuffer(0, { maxByteLength: 3 }) // Expected 1 arguments, but got 2. deno-ts(2554)
buffefr.resize(1)
```
The `.resize` function should also be visible when the `maxByteLength` is provided.

**Comment by petamoriken** [comment]
upstream issue: https://github.com/microsoft/TypeScript/pull/57858

**Comment by BlackAsLight** [comment]
Looks like it was merged. Just gotta wait for it to bubble up here. 🎉

**Comment by BlackAsLight** [comment]
https://github.com/denoland/deno/issues/19191
