### ISSUE TITLE
windows tar doesn't exist

### ISSUE THREAD

**Issue by Reububble** [denoland/deno#22983]
Version: Deno 1.41.3

#20711 assumes the windows tar exists, but that was only added in Insider Build 17063 ([see more](https://learn.microsoft.com/en-us/virtualization/community/team-blog/2017/20171219-tar-and-curl-come-to-windows)) which happens to be more recent than the build on the machine this issue is happening on. This manifests as the following error whenever trying to use deno compile (GNU tar exists here so it's using that)

```
tar: Cannot connect to C: resolve failed
error: Writing *.exe
Caused by:
    Failed to unpack archive.
```

**Comment by lucacasonato** [comment]
That is a Windows build from 7 years ago. We only support recent Windows 10 and Windows 11 builds for Deno.
