### ISSUE TITLE
Reorganize `use` statements in Rust files

### ISSUE THREAD

**Issue by kevinkassimo** [denoland/deno#2299]
`use` statements in e.g. files like `cli/ops.rs` have grown a bit unnecessarily long. We should try to reduce these statements and reorganize them.

For example in `ops.rs`,
```rust
use futures;
use futures::Async;
use futures::Poll;
use futures::Sink;
use futures::Stream;
```
could be combined to simply
```rust
use futures::{self, Async, Poll, Sink, Stream};
```
Also for some other files, when we already do `use crate::errors::DenoError;`, we no longer need to write `errors::DenoError` and instead `DenoError` is good enough.

We also need to sort the imports. For example, imports in `cli/repl.rs` is not sorted.

This should be a good first issue.

**Comment by Janpot** [comment]
Could this be done automatically by a code formatter?

**Comment by kevinkassimo** [comment]
@Janpot seems that our current settings with rustfmt does not format these. If people can find a way to tweak the formatter settings it also works.

**Comment by ry** [comment]
I’d love if we could configure rustfmt to not allow multiple symbols to be imported per line. (The curly brace syntax.) 

Rebasing and merging is much easier if each import is on its own line.

**Comment by bartlomieju** [comment]
@ry we can wait for [`imports_layout`](imports_layout) option for `rustfmt` to reach stable to achieve that

**Comment by ry** [comment]
@bartlomieju Thanks for the pointer. I've created an issue to track it: https://github.com/denoland/deno/issues/2347

Let's just close this one, since it is less exactly specified.
