### ISSUE TITLE
Flaky tests runner

### ISSUE THREAD

**Issue by wrnrlr** [denoland/deno#22991]
Version: Deno 1.41.3

Here are 3 screenshots I took one after the other where for exactly the same test Deno responded with 3 different behaviours only one  of which is correct.

![Screenshot 2024-03-19 at 22 46 26](https://github.com/denoland/deno/assets/24570434/4ed8af55-5694-473f-a92b-e03be99f12bd)
![Screenshot 2024-03-19 at 22 46 35](https://github.com/denoland/deno/assets/24570434/2380002a-8b43-4dfd-a2cf-c23eca2f4593)
![Screenshot 2024-03-19 at 22 47 17](https://github.com/denoland/deno/assets/24570434/568f1823-9d11-4f3c-a91c-f39f6c6ea079)

This is not the only way in which Deno is broken. Another behaviour that I see it simply won't run the code inside the tests:

![Screenshot 2024-03-19 at 23 29 51](https://github.com/denoland/deno/assets/24570434/044d2e8a-871e-417f-8deb-0fd0ca663ec5)
![Screenshot 2024-03-19 at 23 29 58](https://github.com/denoland/deno/assets/24570434/b397eec2-4d72-42d7-ada4-88a271f8f632)

**Comment by mash-graz** [comment]
yes -- as long as the progress indicators are still circling around the yellow dots, you feel excited like in an online casino ;)

Just use `git commit --amend --no-edit` and `git push -f` to get another chance if the error looks utterly unbelievable.

**Comment by wrnrlr** [comment]
Sorry I don't understand your riddle or how or why this is solving my issue.

**Comment by mash-graz** [comment]
sorry -- I was writing about very similar experiences while contributing PRs to the github repo and getting similar confusing and always changing error reports back from the CI system, but you are talking about the behavior on your own local hardware.

So it's definitely not an issue related to your local setup but happening also in other execution contexts. But I have to say, that I did not see any of those flaky error reports during many local test runs her on my machine recently.

**Comment by 0f-0b** [comment]
`describe` is used to group related tests. Actual test code should be put in an `it` block or a `before*`/`after*` hook. For example, you can initialize `node` in a `beforeAll` hook:

```js
import { beforeAll, describe, it } from "jsr:@std/testing@^0.220.1/bdd";
import { assertEquals } from "jsr:@std/assert@^0.220.1/assert_equals";

describe("DOMNode", () => {
  let node;

  beforeAll(async () => {
    node = await xmlFromString(…);
  });

  it("in root namespace", () => assertEquals(…));
  it("in leaf namespace", () => assertEquals(…));
});
```

<details><summary><code>Deno.test</code> equivalent</summary>

```js
import { assertEquals } from "jsr:@std/assert@^0.220.1/assert_equals";

Deno.test("DOMNode", async (t) => {
  let node = await xmlFromString(…);

  await t.step("in root namespace", () => assertEquals(…));
  await t.step("in leaf namespace", () => assertEquals(…));
});
```

</details>

The error message could definitely be improved. [Jest throws a helpful error](https://github.com/jestjs/jest/blob/d4d1f2b8004b1eb4bf0cf862698dd1142e13278f/packages/jest-circus/src/index.ts#L72-L82) if the callback passed to `describe` returns a promise or anything other than `undefined`.

**Comment by lucacasonato** [comment]
@0f-0b is right. I am closing this and have opened a follow up in std to add an error message when one passes an async function to describe: https://github.com/denoland/deno_std/issues/5034
