### ISSUE TITLE
Use a separate file for source maps in ~/.deno/cache

### ISSUE THREAD

**Issue by ry** [denoland/deno#23]
Currently we use inlineSourceMaps: https://github.com/ry/deno/blob/c0cc240810f9280ca458c54b4cb69acc30e47e27/runtime.ts#L187
However this makes examining the cache files difficult.

To make this change happen, the CodeFetchRes message must also return a separate source map. So to start, a new entry `string code_fetch_res_source_map` would be added to `msg.proto` here 
https://github.com/ry/deno/blob/c0cc240810f9280ca458c54b4cb69acc30e47e27/msg.proto#L51-L58
and probably add `string code_cache_source_map` here
https://github.com/ry/deno/blob/c0cc240810f9280ca458c54b4cb69acc30e47e27/msg.proto#L60-L63

**Comment by darxtrix** [comment]
Apart from adding this, we also need to change the functions `HandleCodeCache`https://github.com/ry/deno/blob/master/os.go#L156 & `codeCache` https://github.com/ry/deno/blob/78124cd45f5b5efe1f06e82554ff09273b75b050/os.ts#L33 for handling the **source maps.**

Similary, we need to add support to functions `HandleCodeFetch` https://github.com/ry/deno/blob/master/os.go#L100 & `codeFetch` too ?https://github.com/ry/deno/blob/78124cd45f5b5efe1f06e82554ff09273b75b050/os.ts#L15

**Comment by geraldatbadawy** [comment]
Follow

**Comment by kitsonk** [comment]
And we need to address dealing with pulling this information out of the emit from the TypeScript compiler.

**Comment by kitsonk** [comment]
I am going to work on this.

As discussed above, `codeFetch` and `codeCache` need to treat the source maps separately.  On thought, is that source maps are only needed when unwrapping a stack trace, it might also be great if they were only lazily loaded from the cache when needed.

**Comment by ry** [comment]
fixed in 8b39d2c99ef41736bb1d5b74ccda2f3aa6223e84
