### ISSUE TITLE
lsp: import suggestion imports `.d.ts` file as `.js`

### ISSUE THREAD

**Issue by scarf005** [denoland/deno#23017]
## Summary

![image](https://github.com/denoland/deno/assets/54838975/2d1bb3e1-96c9-48af-aee1-a884ac5c3fc1)

when applying auto import, LSP imports `.d.ts` file as `.js`, causing error. there is no `.js` file in project.

Version: Deno 1.41.3+2ce6451 (canary, x86_64-unknown-linux-gnu)

**Comment by Mqxx** [comment]
I have the same problem, importing files with extension. VS-Code only allows:

`"javascript.preferences.importModuleSpecifierEnding"`
`"typescript.preferences.importModuleSpecifierEnding"`
- `auto`: Use project settings to select a default.
- `index`: Shorten `./component/index.js` to `./component/index`.
- `js`: Do not shorten path endings; include the `.js` or `.ts` extension.
- `minimal`: Shorten `./component/index.js` to `./component`.
