### ISSUE TITLE
blob slice should not throw

### ISSUE THREAD

**Issue by jimmywarting** [denoland/deno#2302]
Haven't read the spec lately but this did look strange to me...

https://github.com/denoland/deno/blob/1f7ad17152c03b140c997590c897b89fbfea7cea/js/blob.ts#L98-L101

Tested this in the browser

```js
type = new TextDecoder().decode(crypto.getRandomValues(new Uint8Array(5)))
blob = new Blob([])
blob.slice(0,0,type)
```

it just sets the type to empty string `""`

**Comment by crowlKats** [comment]
indeed the implementation we have is deviated from the spec. The spec states, [under section 3.1 of the FileAPI, under step 1.3.1 that if `type` is not valid ASCII, the `type` should be set to an empty string.](https://www.w3.org/TR/FileAPI/#constructorBlob)
The thing is, Deno is not 100% conformant to spec, so this might as well be left as is.

**Comment by ry** [comment]
Deviations from spec are bugs
