### ISSUE TITLE
Deno has panicked in resolvers/local.rs while resolving npm package

### ISSUE THREAD

**Issue by BlowaterNostr** [denoland/deno#23029]
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos aarch64
Version: 1.41.0
Args: ["/opt/homebrew/bin/deno", "lsp"]

thread '<unnamed>' panicked at cli/npm/managed/resolvers/local.rs:172:48:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Info  - 3:24:19 PM] Connection to server got closed. Server will restart.
Starting Deno language server...
  version: 1.41.0 (release, aarch64-apple-darwin)
  executable: /opt/homebrew/bin/deno
Connected to "Visual Studio Code" 1.87.2
  Auto-resolved configuration file: "*****/deno.json"
Setting import map defined in configuration file: "*****/deno.json"
  Resolved import map: "*****/deno.json"
Enabling import suggestions for: https://deno.land
  Error fetching registry config for "https://deno.land": EOF while parsing a value at line 1 column 0
Server ready.

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos aarch64
Version: 1.41.0
Args: ["/opt/homebrew/bin/deno", "lsp"]

thread '<unnamed>' panicked at cli/npm/managed/resolvers/local.rs:172:48:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Error - 3:24:23 PM] The Deno Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.

**Comment by bitsnaps** [comment]
I get the same message when running `deno upgrade` to upgrade from `deno 1.42.1` to `deno 1.42.4`,  here is the log:
```
Looking up latest version
Found latest version 1.42.4
Downloading https://github.com/denoland/deno/releases/download/v1.42.4/deno-x86_64-apple-darwin.zip
Deno is upgrading to version 1.42.4
Archive:  /var/folders/qp/cd4kbj9d0_g03l5_cmtj44xw0000gn/T/.tmpVRAlt0/deno.zip
  inflating: deno                    
dyld: cannot load 'deno' (load command 0x80000034 is unknown)

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos x86_64
Version: 1.42.1
Args: ["deno", "upgrade"]

thread 'main' panicked at cli/tools/upgrade.rs:660:3:
assertion failed: output.status.success()
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Tested on: MacOS Mojave 10.14.6.

**Comment by marvinhagemeister** [comment]
@bitsnaps Can you open a new issue for that?

**Comment by bitsnaps** [comment]
@marvinhagemeister Done #23555 .
