### ISSUE TITLE
Precompiled JSX shouldn't preserve spaces

### ISSUE THREAD

**Issue by mary-ext** [denoland/deno#23030]
Version: Deno 1.41.3

Using this example code, with [`jsr:@mary/jsx`](https://jsr.io/@mary/jsx) to do JSX serialization...

```tsx
const result = (
	<div>
		<h1>Hello world</h1>
	</div>
);

console.log(result.value);
```

When the `precompile` JSX option is used, the resulting serialization retains the whitespace information from the source code:

```html
<div>           <h1>Hello world</h1>    </div>
```

It should match what `react-jsx` has:

```html
<div><h1>Hello world</h1></div>
```

Not just for stylistic reasons but also because it means that switching between the two transforms could lead to broken website styling due to unexpected whitespace.

**Comment by marvinhagemeister** [comment]
Wanted to take a stab at this, but I'm unable to reproduce this issue. The spaces are not present for me and everything works as expected with the provided reproduction. Tested on my mac, linux and windows machine.

**Comment by mary-ext** [comment]
Ooh, I think I know what's happening, this seems to be only happening with *tabs* specifically, not when spaces are being used.

**Comment by marvinhagemeister** [comment]
Good catch, I missed that with the tabs. Only tried spaces. Can confirm that using tabs for indentation reproduces the issue.

**Comment by marvinhagemeister** [comment]
@mary-ext FYI you can see the emitted output from Deno by running `deno info path/to/file.tsx`. It will print the path to the emitted code.
