### ISSUE TITLE
and new blob reading methods

### ISSUE THREAD

**Issue by jimmywarting** [denoland/deno#2303]
- [ ] `blob.text()` - `promise<String>`
- [ ] `blob.arrayBuffer()` - `promise<ArrayBuffer>`
- [ ] `blob.stream()` - `Dom.ReadableStream`

**Comment by kitsonk** [comment]
Unlikely, largely sugar like that is done in `deno_std`, not in the Deno core.

**Comment by crowlKats** [comment]
> Unlikely, largely sugar like that is done in `deno_std`, not in the Deno core.

@kitsonk i oppose this statement, as there is no other way to read content from a blob except the old FileReader API (which isnt implemented either), but it would be more appropriate to use those methods.

**Comment by jimmywarting** [comment]
i would rather have this method than the FileReader

**Comment by crowlKats** [comment]
I completely agree. i am currently looking into implementing those methods

**Comment by crowlKats** [comment]
This should be closed as #4581 took care of this
