### ISSUE TITLE
Bug: LSP inserts duplicate `async` keyword when accepting suggestion

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/deno#23046]
The LSP inserts a duplicate `async` keyword when the user has typed it out themselves and accepts a method signature suggestion. Best explained via video:

https://github.com/denoland/deno/assets/1062408/45a51f2c-9940-477a-bb33-20923ff69221

Snippet used in the video:

```ts
export interface Foo {
  render(value: number, other: string): Promise<string>;
}

class FooImpl implements Foo {
  // Type "async render" here and accept suggestion
}
```

Version: Deno 1.41.3

**Comment by nayeemrmn** [comment]
This is directly a problem with tsc, observable on the Node TS server. It would be better to open an issue on https://github.com/microsoft/TypeScript.  Let's close this since there wouldn't be any integration work for us.

**Comment by marvinhagemeister** [comment]
Good point, can confirm that this happens with the default tsc lsp too. I'll open an issue on the TS repo.
