### ISSUE TITLE
npm-compat: biome lsp-proxy not working

### ISSUE THREAD

**Issue by sigmaSd** [denoland/deno#23051]
Version: Deno 1.41.3

`deno run -A npm:@biomejs/biome@1.6.2 lsp-proxy` exits immediately with no error

bunx works as expected `bunx @biomejs/biome@1.6.2 lsp-proxy`

**Comment by sigmaSd** [comment]
```
✅ Granted run access to "/bin/sh".
✅ Granted run access to "/home/mrcool/.cache/deno/npm/registry.npmjs.org/@biomejs/cli-linux-x64/1.6.2/biome".
```

I'm suspecting its not forwarding cli args (lsp-proxy) to the biome executable

**Comment by sigmaSd** [comment]
I think this is incorrect https://github.com/denoland/deno/blob/e1e1da2a04f627f058dc33355a31d67abb1616b6/ext/node/polyfills/internal/child_process.ts#L887

I think it should be spawn instead of outputSync

**Comment by littledivy** [comment]
Simpler reproduction:

```js
import { spawnSync } from "node:child_process";

const biome = "/home/divy/.cache/deno/npm/registry.npmjs.org/@biomejs/cli-linux-x64/1.6.2/biome";
const output = spawnSync(biome,
  ["lsp-proxy"],
  { shell: false, stdio: "inherit" }
);
console.log(output);
```
