### ISSUE TITLE
Regression when using relative import map in deno.json

### ISSUE THREAD

**Issue by NeKzor** [denoland/deno#23057]
Version: Deno 1.41.3

A single `../` in the path value for `"importMap"` inside `deno.json` config file will output `error: Loading unprepared module` when using `deno run`.

Minimal reproducible example:
```bash
$ cat main.ts
import '~/shared/models.ts';

$ cat deno.json 
{
  "importMap": "../import_map.json"
}

$ cat ../import_map.json 
{
    "imports": {
        "~/shared/": "./shared/"
    }
}

$ cat ../shared/models.ts 
export class Model {}
```

This happens since 1.41.1 but I decided to build Deno from source to find the exact commit that caused this: 6567dc94a901aaae1b4e5b8e84d48bc72d46ee2e

Running the debug build will trigger a panic at this location: https://github.com/denoland/deno/blob/ae52b49dd6edcfbb88ea39c3fcf0c0cc4b59eee7/cli/args/import_map.rs#L77-L81

The current workaround is to use `"imports"` in the config file or to use the `--import-map` flag.

**Comment by k-paxian** [comment]
Thank you so much @NeKzor  for workaround 🎉 ❤️ 
It saved me literally hours 🍺

**Comment by dsherret** [comment]
Fixed a couple weeks ago in https://github.com/denoland/deno/pull/23602
