### ISSUE TITLE
Async calls and timers do not work in `node:worker_threads` CJS scripts

### ISSUE THREAD

**Issue by mash-graz** [denoland/deno#23061]
Version: upstream (f96f167d)

When we use CJS scripts as file input for `node:worker_threads`, most of the basic JS and `require()` calls work fine, but as soon as timers or `async await` comes into play, it will not work as expected.

There is a simple demonstration example already prepared in the unit-tests:

https://github.com/denoland/deno/blob/d263c632e3d5a91fd6f9fffc598128d87c5621cd/tests/unit_node/testdata/worker_module/cjs-file.cjs#L1-L23

If you move the line 20 up to the timer callback section after line 5 you'll see that timer callbacks never get called resp. `await`s will never be resolved.

This maybe happen because the worker simply doesn't run anymore resp. didn't wait for timers...

Perhaps we need more preparation in CJS wrapper to support this kind of operations, but it could be also caused by a `node:worker_thread` specific limitation.

Although `deno` usually advocates ESM instead of CJS, it's still a matter of compatibility to provide at least basic CJS legacy support, especially in case of worker or VM scripts, where ESM wasn't an available choice in `nodejs` for a long period of time.

**Comment by bartlomieju** [comment]
@satyarohith please try to reproduce this problem - ideally turning it into a standalone test case.

**Comment by josephrocca** [comment]
This is not just a problem for CJS - `setTimeout` and `setInterval` don't work for module scripts either. E.g.
```js
import worker_threads from 'node:worker_threads';
const worker = new worker_threads.Worker(new URL("./worker.mjs", import.meta.url));
```
And `./worker.mjs`:
```js
import { resourceLimits } from 'node:worker_threads';
console.log("test1");
setTimeout(() => {
  console.log("test2");
}, 100);
```
In Node.js it logs `test1` and `test2`, but in Deno it only logs `test1`.

Tested in Deno v2.0.0

**Comment by josephrocca** [comment]
Ah, the change that broke this was introduced in [v1.42.0](https://github.com/denoland/deno/releases/tag/v1.42.0). It works fine in `v1.41.3`. Possibly related changes in v1.42.0:

* https://github.com/denoland/deno/pull/22944
* https://github.com/denoland/deno/pull/22841
* https://github.com/denoland/deno/pull/22945

**Comment by satyarohith** [comment]
Tested with `v2.0.5` and it's still an issue
```
➜  deno --version
deno 2.0.5 (stable, release, aarch64-apple-darwin)
v8 12.9.202.13-rusty
typescript 5.6.2
➜  deno -R main.mjs
test1
```

**Comment by kt3k** [comment]
Looks like this started from #22944 (Its parent commit ( e40f9a5c14c51b6d05812e48fa072148fe79c74d ) doesn't have this issue)

https://github.com/denoland/deno/pull/22944/files#diff-d79583d80aaeb5ef9a59ecdd138bfd64ac89793f594321f1fce5d8625c1e07e2R800-R808

In these lines, we consider child workers, but we don't take pending async ops (other than op_worker_recv_message) into account. That seems causing the premature exit of worker threads to me.

I'll work on a fix based on that idea
