### ISSUE TITLE
v1.43.3 node_worker:threads worker thread exits where thread would remain open on node

### ISSUE THREAD

**Issue by chrisdickinson** [denoland/deno#23070]
Version: Deno v1.43.3

When testing the [Extism js-sdk](https://github.com/extism/js-sdk) we noticed a regression between Deno v1.43.2 and v1.43.3: namely, the tests started failing with a ["Promise resolution is still pending" error](https://github.com/extism/js-sdk/actions/runs/8414045967/job/23037306936#step:7:3005). On closer inspection it appeared that one test was being skipped compared to runs on previous versions of Deno.

Digging into this further: the Extism JS-SDK spawns a long-lived `node:worker_thread` to run Wasm plugins on. This worker thread is kept alive automatically by adding an [`parentPort.on('message')` handler](https://github.com/extism/js-sdk/blob/main/src/worker.ts#L25); Node and Bun keep this worker thread alive. [As of this PR](https://github.com/denoland/deno/pull/22647), Deno no longer keeps the worker thread alive.

I worked around this bug for the time being adding a `setInterval(() => {}, 10000)` in the worker to fix tests running on Deno, but it seems like there might be a bug in keeping Node-polyfill Worker threads alive on `v1.43.3`.

**Comment by chrisdickinson** [comment]
(This is a bit lazyweb of me, but would you happen to have a link to a canary build download? I'm not using a `deno` built with `upgrade`, and I didn't see an artifact in github releases. Apologies!)

**Comment by bartlomieju** [comment]
You can grab it from https://console.cloud.google.com/storage/browser/dl.deno.land/canary/64e8c36805dab0362ed274a977bb9d0638b55b2a;tab=objects?prefix=&forceOnObjectsSortingFiltering=false

**Comment by chrisdickinson** [comment]
Yep! It is indeed fixed on the canary. Thanks!

**Comment by bartlomieju** [comment]
Great, I'm gonna close the issue then. This fix will be available in Deno v1.42 that will be released later this week.
