### ISSUE TITLE
todo: remove APIs using `DENO_FUTURE=1`

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno#23089]
The following symbols need to be made inaccessible/undefined when `DENO_FUTURE=1` is set:
- [x] #23219
- [x] #23270
- [x] #23453
- [x] #23234
- [x] #23271
- [x] #23235
- [x] #23087
- [ ] `--unstable`
- [ ] `--jobs`
- [ ] `--ts/T`

Related #22079

**Comment by iuioiua** [comment]
The solution to most of these is to read the `DENO_FUTURE` environment variable somehow and disable the symbols where they're implemented.

**Comment by bartlomieju** [comment]
> The solution to most of these is to read the `DENO_FUTURE` environment variable somehow and disable the symbols where they're implemented.

Which is problematic, because we only have information if the env var is present after the code in relevant extensions has been evaluated. I'll try to come up with a solution.

**Comment by iuioiua** [comment]
Talked with Bartek. This can now be considered completed as flags cannot be easily targeted with `DENO_FUTURE=1`.
