### ISSUE TITLE
Support extending denofmt

### ISSUE THREAD

**Issue by daalfox** [denoland/deno#23098]
I would like to re-open [this](https://github.com/denoland/deno/issues/19806) issue because for deno to be a successor of node, it needs to be able to be more flexible around formatting

denofmt is too restrictive. It's not possible for frameworks to extend it with their own official packages and It can hold a lot of library authors back.

E.g. tailwindcss can't add it's class sorting support in TSX. Isn't it better to expose dprint's options or maybe even use dprint entirely to allow use of its' plugins.

This approach of being opinionated formatter is not possible with all kinds of  needs every user has.

**Comment by dsherret** [comment]
Going to close this one because it's too open ended. We'd like to add tailwind sorting in the future though.

**Comment by wderezin** [comment]
This request isn't overly open-ended; it's specifically about exposing the dprint configuration.

While I'm a strong supporter of opinionated formatters, there are inevitably edge cases that the Deno team may not have anticipated. My biggest concern with the decision not to support dprint configuration is the slow response time to such requests. For example, it took three months just to receive a "no" on this.

The community is what drives Deno's growth and success — please prioritize supporting it. Exposing the dprint configuration would empower developers to address those edge cases effectively and improve adoption.

**Comment by dsherret** [comment]
It is too open ended. A lot of the config in dprint is not stable. See https://github.com/denoland/deno_config/pull/162 for how more specific config is being added.
