### ISSUE TITLE
Linter does not warn about namespaces in `.d.ts` file

### ISSUE THREAD

**Issue by CobyPear** [denoland/deno#23106]
Version: Deno 1.40.3

The following lint warning appears in a `.ts` file when trying to use a namespace, but not a `.d.ts` file:

> TypeScript's `module` and `namespace` are discouraged to
>use
>Use ES2015 module syntax (`import`/`export`) to organize
>the code instead deno-lint(no-namespace)

Minimal reproduction here: https://github.com/CobyPear/deno-namespace-reproduction
Change the `.d.ts` file to `.ts` and you will see the warning.

**Comment by CobyPear** [comment]
If you try running the test in the reproduction you will see that it does not work, maybe I'm missing something. If it worked I wouldn't have a problem but this was a bit confusing to learn that namespaces aren't supported and it only tells you that in a `.ts` file.

**Comment by dsherret** [comment]
Are you talking about the separate error mentioned in the README?

**Comment by lucacasonato** [comment]
Closing as there has been no response from the OP.
