### ISSUE TITLE
`Deno.Command` fails to pipe I/O transparently with interactive tools

### ISSUE THREAD

**Issue by mattvr** [denoland/deno#23116]
Version: Deno 1.41.3

There's various cases I've encountered where piping the I/O of `Deno.Command` (or `Deno.run(...)`) does not result in the same result as if the command was run in a shell. 

This prevents various CLI/TUI use cases. One example is [`gum`](https://github.com/charmbracelet/gum) and related libraries, which helps with making pleasant interactive steps in the terminal.

Not sure if I'm understanding Deno's intent, inherent limitations, and the exact issue here. I suppose it could be stripping escape sequences or other special characters. TL;DR I think the below repro ought to be supported:

## Repro

This example requires `gum` to be installed (e.g. `brew install gum`), though it reproduces with other libraries. We'll simply wrap it as a Deno subprocess, inherit stdin, and pipe stdout/stderr.

```ts
const cmd = new Deno.Command("gum", {
  args: [
    "confirm"
  ],
  stdout: 'piped',
  stderr: 'piped'
})
const process = cmd.spawn()
process.stdout.pipeTo(Deno.stdout.writable)
process.stderr.pipeTo(Deno.stderr.writable)
```

### Expected
A confirmation modal should display, be interactive, and output the final selection to stdout.

![CleanShot 2024-03-28 at 09 56 59@2x](https://github.com/denoland/deno/assets/4052466/f7fe0ee2-a151-4733-a6bc-288553694fb0)

### Observed
A confirmation modal displays, but does not visually update, and upon selection outputs empty characters.

![CleanShot 2024-03-28 at 09 57 22@2x](https://github.com/denoland/deno/assets/4052466/495ec5bd-9215-4dd6-9614-455e03b7c1db)

**Comment by sigmaSd** [comment]
seems to work as expected to me
- visually don't update: that most likely becase gum is detecting its being run as child process and deactivating color
- outputs empty characters: that's the same thing if I run `gum confirm` on the shell, because gum confirm doesn't output anything, it just sets the exist status code

**Comment by mattvr** [comment]
@sigmaSd I don't think so. I compared with Python, Go, and Bun/Node and `Deno.Command` is the only one that doesn't handle this correctly.

> visually don't update: that most likely becase gum is detecting its being run as child process and deactivating color

If run as a subprocess 

### Python
```py
import subprocess

result = subprocess.run(
        ['gum', 'confirm']
)
```

### Bun/Node 
```js
const {spawn} = require('child_process')

// spawn a child process to run `gum confirm`
const gum = spawn('gum', ['confirm'])
```

In both cases everything works as expected:
![python](https://github.com/denoland/deno/assets/4052466/ea786019-5195-401f-ad47-62770b0e0738)

> outputs empty characters: that's the same thing if I run gum confirm on the shell, because gum confirm doesn't output anything, it just sets the exist status code

You're right, but this was just an artifact of the example. If you use `gum input` the output is the user input, and the issue with formatting is much clearer.

![CleanShot 2024-03-29 at 15 08 44](https://github.com/denoland/deno/assets/4052466/1f35da8a-739b-4cf4-9646-6368c93a1bc2)

**Comment by sigmaSd** [comment]
But you're only piping the output in the Deno example, if you don't use 
```
  stdout: 'piped',
  stderr: 'piped'
```
like the other examples it will work the same

**Comment by sigmaSd** [comment]
You can run you original example with `CLICOLOR_FORCE=1` to get the behavior you want

**Comment by mattvr** [comment]
@sigmaSd Thank you so much for the help with this.

I was able to modify the example a bit and achieve what I was looking for (which is to be able to use `gum` in deno projects). 

### Changes
- Use `CLICOLOR_FORCE=1`
- `tee()` the stdout`, so we can read the result and still pass through to `Deno.stdout`
- Don't pipe stderr, because it conflicts with the terminal refreshing [to figure out later]

### Working example

```ts
Deno.env.set("CLICOLOR_FORCE", "1")

const cmd = new Deno.Command("gum", {
  args: [
    "file"
  ],
  stdout: 'piped',
})
const process = await cmd.spawn()

process.stdout?.tee().map((x, i) => {
  if (i === 0) {
    x.pipeTo(Deno.stdout.writable)
  } else {
    x.pipeTo(new WritableStream({
      write(chunk) {
        console.log('got', new TextDecoder().decode(chunk))
      },
    }))
  }
})
```

**Comment by sigmaSd** [comment]
You're welcome, I think its better to pass the env inside Commad instead of setting it like that
