### ISSUE TITLE
Issue new release blog post only after succesfull deployment to HomeBrew

### ISSUE THREAD

**Issue by kuchta** [denoland/deno#23120]
Hi guys,

I know HomeBrew isn't the only release channel and from your standpoint maybe even not the primary one, but I believe most of the devs use it so it's quite frustrating when new release info comes out, but we are unable to test it...

**Comment by bartlomieju** [comment]
Homebrew often is slow to release a new Deno version (sometimes it takes a few days after the Deno release), therefore it is not reasonable for us to wait that long given that majority of users use `deno upgrade` to get a new version.

**Comment by bartlomieju** [comment]
I would suggest to switch to https://docs.deno.com/runtime/manual/getting_started/installation and using `deno upgrade` if you don't want to wait until Homebrew publishes a new version :)

**Comment by kuchta** [comment]
Hi @bartlomieju

Thank you for your response.

I thought that Homebrew is OpenSource project that allows "anyone" to take care of package maintanance, isn't that true?

Regarding that majority of users using `deno upgrade`. Do you have some numbers to support that, or is that just your presumption?

**Comment by bartlomieju** [comment]
> I thought that Homebrew is OpenSource project that allows "anyone" to take care of package maintanance, isn't that true?

TBH I am not sure, I'm not very familiar with inner workings of Homebrew. From what I can see in this PR: https://github.com/Homebrew/homebrew-core/pull/167360 Homebrew has an automated system for providing new versions. It looks like the PR was opened very shortly after I finished the Deno release and posted it on GitHub and it needed a manual approve before it was landed.

> Regarding that majority of users using deno upgrade. Do you have some numbers to support that, or is that just your presumption?

Yes we do keep track of these numbers, they show that Homebrew downloads are much smaller compared to other means like `deno upgrade` or downloading directly from GitHub.

**Comment by marvinhagemeister** [comment]
Closing this, as there is nothing left for us to do here.

We don't have any control over how quickly the hombrew maintainers merge a PR, which causes homebrew a few days to be behind when a new version of Deno is released. Withholding the release blog post until that's done is not desirable from our end and would be unfair to non-homebrew users which make up the majority of Deno users.
