### ISSUE TITLE
`deno add npm:express` not work as expected

### ISSUE THREAD

**Issue by liigo** [denoland/deno#23124]
Version: Deno 1.42.0

the blog https://deno.com/blog/v1.42 said:
> Note that deno add also supports adding npm packages with the npm: prefix.

but it doesn't work:
> `deno add npm:express`
> error: npm:express was not found.

**Comment by marvinhagemeister** [comment]
Hm I can't reproduce it on my end. It works as expected with `1.42.0`. Could it be that you're on an older Deno version?

**Comment by nayeemrmn** [comment]
This might be a network ban thing, try `NPM_CONFIG_REGISTRY=https://r.cnpmjs.org/ deno add npm:express`

**Comment by liigo** [comment]
@nayeemrmn Thank you, you're right. I was using `https://registry.npm.taobao.org/`, which is down. Closing with not a bug.

**Comment by tiansiyuan** [comment]
```
% NPM_CONFIG_REGISTRY=https://r.cnpmjs.org/ deno add npm:express
error: npm:express was not found.
% deno -V
deno 2.9.0
```
