### ISSUE TITLE
jsr: Readme rendering does not support Github Callouts

### ISSUE THREAD

**Issue by bjesuiter** [denoland/deno#23129]
In my package [zod-semver](https://jsr.io/@codemonument/zod-semver) i have a WARNING Callout in my readme, looking like this: 

> [!WARNING] Not published to [deno.land/x/zod_semver](https://deno.land/x/zod_semver) anymore! Use the jsr package instead:
jsr:@codemonument/zod-semver!

Unfortunately, it does not get rendered pretty like this on github: 

<img width="726" alt="Bildschirmfoto 2024-03-29 um 14 33 11" src="https://github.com/denoland/deno/assets/2365676/88422c8e-b8d5-4555-af91-37310e21437c">

but simply as text: 
<img width="594" alt="Bildschirmfoto 2024-03-29 um 14 33 44" src="https://github.com/denoland/deno/assets/2365676/96c20999-7dfc-4007-856d-11300136af06">

It would be nice if github callouts where supported! :)

**Comment by crowlKats** [comment]
Closed by jsr-io/jsr#334
