### ISSUE TITLE
Rename xeval?

### ISSUE THREAD

**Issue by ry** [denoland/deno#2312]
"deno xeval" is a new command that evaluates a script for each line of stdin (it also supports other delimiters other than \n)

It is named after xargs, the unix command. But I suspect many users will not know xargs, or even if they do not make the connection. So maybe "xeval" is confusing.

1. Is xeval a good name?
2. If not what is? Alternative suggestions include "deno each" and "deno foreach"

**Comment by hayd** [comment]
I propose `eval-lines`, I know this doen't relay alternative delimiters but seems a lot clearer. Otherwise `eval-each` would also be good: more explicit than `each`.

**Comment by bartlomieju** [comment]
IMHO `xeval` is fine - it's short and actually resembles `xargs`. Though it's probably a good idea to add a note to docs to suggest similarities between `xeval` and `xargs`

**Comment by bartlomieju** [comment]
Any update on this issue @ry?

**Comment by zxqfox** [comment]
How to use it? ;-(

**Comment by NotWearingPants** [comment]
I vote for `eval-each`
