### ISSUE TITLE
local Deno KV database lost after renaming deno.json to deno.jsonc

### ISSUE THREAD

**Issue by skybrian** [denoland/deno#23122]
After upgrading to 1.42.0, my local KV database disappeared. It's just test data, but it's concerning.

I guessed that perhaps the path within  ~/Library/Caches/deno/location_data changed. The timestamps are consistent with that:

```
% ls -l ~/Library/Caches/deno/location_data
total 0
drwxr-xr-x@ 5 skybrian  staff  160 Mar 27 22:11 03e2d4f4b5ff7f96ae6751cddcfd778a2a7b3461397b48ef487f94409fe9ae56
drwxr-xr-x@ 5 skybrian  staff  160 Mar 28 18:41 4eadd92610d78d34135b83c12386bde76f07695e9b768744ab8d2b728c16338c
```

However, renaming directories didn't get back the old data, so it seems that's not it.

The other change I made was, after reading the release notes, to rename deno.json to deno.jsonc. It seems this changes the hash code? If so, it's an unexpected side effect. I had thought that the hash depended only on the directory name.

**Comment by skybrian** [comment]
Incidentally, it seems like putting the local KV database in a subfolder (similar to .git or .vscode) would have less surprising results and be less likely to break due to a renaming.

**Comment by lucacasonato** [comment]
The key we used to index your KV database, and how we derive it, is listed here: https://docs.deno.com/runtime/manual/runtime/web_storage_api

**Comment by skybrian** [comment]
Thanks! It seems like the [documentation for Deno.openKv](https://deno.land/api@v1.44.1?unstable=true&s=Deno.openKv) should link to that page? It does explain it, but.only gives a vague reference for where to go for further information:

> When no path is provided, the database will be opened in a default path for the current script. This location is persistent across script runs and is keyed on the origin storage key (the same key that is used to determine localStorage persistence). More information about the origin storage key can be found in the Deno Manual.

The [quick start guide](https://docs.deno.com/deploy/kv/manual) is incorrect, or at least incomplete:

> You may pass in an optional file system path to where you'd like to store your database, otherwise one will be created for you based on the current working directory of your script.
