### ISSUE TITLE
Import map entries are not resolved in the editor

### ISSUE THREAD

**Issue by roj1512** [denoland/deno#23121]
## Reproduction

Project structure

```
.vscode/
    settings.json
main.ts
deno.json
```

Filename: .vscode/settings.json

```json
{
  "deno.enable": true
}
```

Filename: main.ts

```ts
import "$std/dotenv/load.ts";
```

Filename: deno.json

```json
{
  "imports": {
    "$std/": "https://deno.land/std@0.216.0/"
  }
}
```

Open VS Code in the project's directory, and see if there is an error on the $std import.

## Notes

- Reproduces since 1.42.0, can’t reproduce with 1.41.3.
- Doesn’t matter if the file name is deno.jsonc or even if a standalone import_map.json is used.
- The code runs properly, and `deno check` passes on main.ts.
- OS: Fedora 39
- VS Code version: 1.87.2
- Deno extension version: 3.36.0

**Comment by nayeemrmn** [comment]
This happens when the document preload limit is zero. Fix coming.

**Comment by Sembiance** [comment]
I just upgraded to 1.42.0 and I'm seeing something similar (worked fine with 1.41.3)

Code:
```js
import {xu} from "xu";
```

Error: `Relative import path "xu" not prefixed with / or ./ or ../`

I have an importMap:
```json
{
    "imports" :
    {
        "xu" : "/path/to/xu.js"
    }
}
```

In my VSCode  project.code-workspace:
```json
{
	"settings" : {
		"deno.enable"    : true,
		"deno.lint"      : true,
		"deno.unstable"  : true,
		"deno.cache"     : "/path/to/.deno/",
		"deno.importMap" : "/path/to/importMap.json",
		"deno.config": "/path/to/lintConfig.jsonc",
	}
}
```

Running from CLI works fine: `deno check --import-map /path/to/importMap.json myFile.js`

It's as if it's ignoring my deno.importMap directive entirely. Changing the value to a non-existant file, no errors or warnings show up in the `output` of `Deno Language Server` at all.

If I revert back to `deno 1.41.3` then I properly see in my `output`:
```
Using import map from workspace settings: "/mnt/compendium/DevLab/deno/importMap.json"
  Resolved import map: "file:///mnt/compendium/DevLab/deno/importMap.json"
```

This is entirely missing when running deno 1.42.0

**Comment by nayeemrmn** [comment]
@Sembiance I opened #23141, will add the fix to the same PR.
