### ISSUE TITLE
Server Side Events (SSE) that don't have data are not notified to the event listener

### ISSUE THREAD

**Issue by aricart** [denoland/deno#23135]
Version: Deno 1.42.0

Thanks for fixing the issue with data truncation when a `:` was found.

Another issue that I am seeing is that if you have an event that does NOT have a `data` field, the event listener in the javascript code will never get notified. Data is just one attribute, and it is possible to send an event that has no `data`, no `type`, no `id`, etc. In the particular issue, the `type` is set, but there's no more details.

```javascript
  // this simply returns an EventSource
  const es = await kvm.watch("A", {include: "lastValue"});

  es.addEventListener("update", (e) => {
    console.log(JSON.parse(e.data));
  })

 // The wire information for the ping event is just:
 // event: ping\n\n

  es.addEventListener("ping", (e) => {
     // this is not getting called.
    console.log(e);
  })
```

**Comment by lucacasonato** [comment]
This is expected. Events without `data: ` fields are ignored entirely.

> 2. If the data buffer is an empty string, set the data buffer and the event type buffer to the empty string and return.


https://html.spec.whatwg.org/multipage/server-sent-events.html#dispatchMessage
