### ISSUE TITLE
Importing from multiple modules of a JSR package causes the compiled binary to hang

### ISSUE THREAD

**Issue by jackfiszr** [denoland/deno#23139]
Tested on Deno 1.41.3 and 1.42.0, Windows and Ubuntu.

When I import from a JSR package, from two different modules, like this:

```
import { expandGlob } from "jsr:@std/fs@0.221.0/expand-glob";
import { walk } from "jsr:@std/fs@0.221.0/walk";
```
and compile this using `deno compile`, then the resulting binary hangs forever on the first import.

This affects Oak: https://github.com/oakserver/oak/issues/648

**Comment by nktpro** [comment]
Confirmed this issue still persists in `1.42.1` as well on all platforms, which unfortunately makes utilizing JSR impossible with `deno compile`

**Comment by johnstonmatt** [comment]
there is still an issue with `jsr:` specifiers and hanging compiled binaries in `v1.42.3`

**Comment by johnstonmatt** [comment]
I have an open source repo which is pretty simple that demonstrates an issue with hanging compiled binaries:

https://github.com/polyseam/cliffy-ghr-demo

this workflow and its results show how builds compile successfully, but hang when called:

https://github.com/polyseam/cliffy-ghr-demo/blob/main/.github/workflows/build-bin.yaml

**Comment by marvinhagemeister** [comment]
> I have an open source repo which is pretty simple that demonstrates an issue with hanging compiled binaries:
> 
> [polyseam/cliffy-ghr-demo](https://github.com/polyseam/cliffy-ghr-demo)
> 
> this workflow and its results show how builds compile successfully, but hang when called:
> 
> [polyseam/cliffy-ghr-demo@`main`/.github/workflows/build-bin.yaml](https://github.com/polyseam/cliffy-ghr-demo/blob/main/.github/workflows/build-bin.yaml?rgh-link-date=2024-04-16T06%3A24%3A42Z)

Spent a bit of time debugging this, but it's super weird. It seems as if the number of `jsr:` imports present influence whether it works or not. When I vendor all dependencies manually and use relative file imports it works. Something strange is going on with `jsr:` specifiers. It really seems related to the number of them.

**Comment by GabrielVGuedes** [comment]
hi

i've been trying to create a very simple app using Oak and i've stumbled on the same problem
the thing is i am not using the `jsr:` imports, i am using the standard imports in a deps file like this

`export { Application, Router } from "https://deno.land/x/oak@14.2.0/mod.ts";`

i then have a routes file that specifies a route

```
import {Router} from "./deps.ts";

const router = new Router();

router.get("/api", () => {});

export default router;

```

and my main file tries to listen to the requests using the routes

```
import {Application} from "./deps.ts";
import router from "./routes.ts";

const PORT = 3000;

const app = new Application();

app.use(router.routes());
app.use(router.allowedMethods());

console.log(`Server listening on port ${PORT}`);
await app.listen({ port: PORT });

```

this has been tested using 1.42.4 and as you can see in the imports, oak 14.2.0

it runs normally using deno run, and also when running from a resulting file from deno install, just when using deno compile that makes the app hangs, nothing is logged
i've tried --allow-all, tried --allow-net, --unstable, everything i could find and understand

i've also tried using just 1 import, i have removed Router from Oak, and it also didn't work
and also tried importing the Application directly in the main file
and also tried adding hostname: '0.0.0.0' in the listen() params

so, i don't know if i'm doing something wrong here, or if it could be the same problem as the jsr imports

thanks in advance
