### ISSUE TITLE
[bug] windows : deno.run.status

### ISSUE THREAD

**Issue by zekth** [denoland/deno#2315]
As seen in : https://github.com/denoland/deno/pull/2294

There is a moment when the promise of `deno.run.status()` is never resolved. On a bare script works like a charm with 0 or 1 output. Seems like the problem might be in the test runner of `deno` or the one of `deno_std`

ref: https://github.com/denoland/deno/pull/2294#pullrequestreview-235035105

cc @bartlomieju

**Comment by ry** [comment]
Is there a standalone example of this?

**Comment by zekth** [comment]
> Is there a standalone example of this?

I've tried to find a way to reproduce but not at the moment. If i find a way to reproduce i'll post it for sure.

**Comment by bartlomieju** [comment]
After extensive debugging with @zekth we haven't been able to conclude what's the problem, it only appeared in same situation as in #2294. 

Let's close this issue for now to avoid noise.

**Comment by rok-star** [comment]
Ran into the same problem, that's what I Deno.run:
```
clang -std=c++2a -g -IC:\Users\rs\***\***\*** -c -fno-exceptions -Wall -Wextra -Wpedantic -Wno-unused-parameter -Wno-c99-extensions -fsanitize=address C:\Users\rs\***\Projects\***\***\src\node.cc -o C:\Temp\***\temp\src\node.cc.o
```
```
deno --version
deno 1.4.1
v8 8.7.75
typescript 4.0.2
```

code: https://deno.land/x/buildsystem@0.1.3/mod.ts#L411
