### ISSUE TITLE
deno install shows warnings while using deno.json as importmap

### ISSUE THREAD

**Issue by shivajivarma** [denoland/deno#23160]
Version: Deno 1.42.0
> deno install -g -f --importmap deno.json -A -n version mod.ts

Import map diagnostics:
  - Invalid top-level key "name". Only "imports" and "scopes" can be present.
  - Invalid top-level key "version". Only "imports" and "scopes" can be present.
  - Invalid top-level key "tasks". Only "imports" and "scopes" can be present.
  - Invalid top-level key "exports". Only "imports" and "scopes" can be present.
  - Invalid top-level key "publish". Only "imports" and "scopes" can be present.
  - Invalid top-level key "exclude". Only "imports" and "scopes" can be present.

deno.json is will be having all there params, so install is not expected to show warning, while using deno.json for imports

**Comment by bartlomieju** [comment]
You should be able to specify `--config deno.json` instead of `--importmap` to make it work.

**Comment by martin-braun** [comment]
@bartlomieju This was a bit confusing. Apparently the config and import map aren't the same thing, but the config can include the import map.

**Comment by mb21** [comment]
@bartlomieju What about the following `deno.json` file:

```json
{
  "tasks": {
    "start": "deno serve -A --import-map=deno.json mastro/server"
  },
  "imports": {
    "mastro": "jsr:@mastrojs/mastro@0.0.3"
  }
}
```

Running `deno task start` prints:

    Import map: Invalid top-level key "tasks". Only "imports" and "scopes" can be present.

and your workaround with `--config deno.json` doesn't work.

Any way to make this work without duplicating the version number? Thanks!
