### ISSUE TITLE
Bug: `process.platform` is `undefined` compiled with `__runtime_js_sources` flag

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/deno#23164]
Just noticed that `process.platform` is `undefined` when the `__runtime_js_sources` flag is set.

```ts
import process from "node:process";
// Logs: undefined
console.log(process.platform);
```

## Steps to reproduce:

1. Run
  ```sh
   $ cargo run --features __runtime_js_sources -- eval "import process from 'node:process';console.log(process.platform)"
   undefined
   ```
2. Logs `undefined` instead of the machines platform string

## Expected:

The `process.platform` should contain the running platform string. The same works when the `__runtime_js_sources` is not passed:

```sh
$ cargo run -- eval "import process from 'node:process';console.log(process.platform)"
darwin
```

Version: Deno 1.42.0 (git)

**Comment by marvinhagemeister** [comment]
Took a look into this, but I'm not familiar enough to make an adequate fix. It seems like something broke the `__runtime_js_sources` flag entirely as I'm always getting a panic from `deno_core` from the `.unwrap()` call here https://github.com/denoland/deno_core/blob/87e5ab284db05fdfc6712f8019dd550c321f73d1/core/runtime/jsruntime.rs#L1203

```rs
    let module_map = realm.0.module_map();
    *module_map.loader.borrow_mut() = loader;
    Rc::try_unwrap(ext_loader)
      .map_err(drop)
      .unwrap()
      .finalize()?;
```

My Rust knowledge is limited and I haven't worked with `Rc` yet. I've worked around this by ignoring the error, but I doubt that this is the appropriate action. I need help here from someone more experienced with Rust than me.

Once the panic is gone, we still need to set the appropriate platform values. Since we're not creating a snapshot with these flags, the snapshot options will fall back to the defaults. Those defaults have an incorrect string for `target` which is later split in JS into the `platform`, `arch` and `os` parts. Setting proper defaults resolves this.

```patch
diff --git a/runtime/ops/bootstrap.rs b/runtime/ops/bootstrap.rs
index eb9dbc6e8..efedaee49 100644
--- a/runtime/ops/bootstrap.rs
+++ b/runtime/ops/bootstrap.rs
@@ -42,11 +42,20 @@ pub struct SnapshotOptions {
 
 impl Default for SnapshotOptions {
   fn default() -> Self {
+    let arch = std::env::consts::ARCH.to_owned();
+    let platform = std::env::consts::OS.to_owned();
+    let target = match platform.as_str() {
+      "macos" => format!("{}-apple-darwin", arch),
+      "linux" => format!("{}-unknown-linux-gnu", arch),
+      "windows" => format!("{}-pc-windows-msvc", arch),
+      rest => format!("{}-{}", arch, rest),
+    };
+
     Self {
       deno_version: "dev".to_owned(),
       ts_version: "n/a".to_owned(),
       v8_version: deno_core::v8_version(),
-      target: std::env::consts::ARCH.to_owned(),
+      target,
     }
   }
 }
```

**Comment by bartlomieju** [comment]
@marvinhagemeister I just tried on latest `main` and I can't reproduce the panic. I can change the internal JS sources without recompiling and the changes are reflected properly. Can you try it out on your side and let me know if it works too?

**Comment by marvinhagemeister** [comment]
@bartlomieju sweet, can confirm that the panic is gone!
