### ISSUE TITLE
Bug: `node:vm` not setting object property

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/deno#23186]
Came across this in the Redux test suite: https://github.com/reduxjs/redux/blob/5455b8d54cd188b2d4b15f7dba055a66125f09b3/test/utils/isPlainObject.spec.ts#L6-L9

## Steps to reproduce

```ts
import vm from "node:vm";
const sandbox = { fromAnotherRealm: false };
vm.runInNewContext("fromAnotherRealm = {}", sandbox);

// Should log `{}`, but logs `false`
console.log(sandbox.fromAnotherRealm);
```

Version: Deno 1.42.1

**Comment by bartlomieju** [comment]
@littledivy got it working earlier today in https://github.com/denoland/deno_core/pull/664. We will be upstreaming it to Deno in the next few days.

**Comment by birkskyum** [comment]
Can confirm this now logs `{}` as expected
