### ISSUE TITLE
node compat: cannot start docusaurus

### ISSUE THREAD

**Issue by cknight** [denoland/deno#23183]
Version: Deno 1.42.0

I'm attempting to run Docusaurus locally, replacing `npm start` with `deno task start`.  I get the following error message:

```sh
Unstable API 'Deno.FsFile.syncSync'. The `--unstable-fs` flag must be provided.
```

I am unable to specify the `--unstable-fs` flag in the deno command at any position which makes it take affect.

Related: #19395

**Comment by bartlomieju** [comment]
@littledivy does https://github.com/denoland/deno/pull/23202 fix this issue too?

**Comment by littledivy** [comment]
Yes but the --unstable-fs is still required. It can be fixed by adding this to `deno.json`:
```jsonc
// deno.jsonc
{ 
  unstable: ["fs"]
}
```
