### ISSUE TITLE
[Bug] conditional import failure from JSR

### ISSUE THREAD

**Issue by jerome-benoit** [denoland/deno#23180]
Version: Deno 1.42.1

To reproduce: 

```shell
deno add @std/cli
```

```ts
import { parseArgs } from '@std/cli/parse-args'
```
=> works

```ts
const { parseArgs } = await import('@std/cli/parse_args')
```
=> error: `error: Uncaught (in promise) TypeError: Unknown export './parse_args' for '@std/cli@0.221.0'.`

It was working on 1.42.0, but I've not retried by downgrading Deno to isolate the cause: JSR or Deno regression.

**Comment by marvinhagemeister** [comment]
The import entry changed from `./parse_args` to `./parse-args`. This should resolve it:

```diff
- const { parseArgs } = await import('@std/cli/parse_args')
+ const { parseArgs } = await import('@std/cli/parse-args')
```

**Comment by jerome-benoit** [comment]
I

> The import entry changed from `./parse_args` to `./parse-args`. This should resolve it:
> 
> ```diff
> - const { parseArgs } = await import('@std/cli/parse_args')
> + const { parseArgs } = await import('@std/cli/parse-args')
> ```

I need to have some rest :D 

Thanks.
