### ISSUE TITLE
Fmt destroys GitHub Blockquote highlights (TIP, WARNING) etc

### ISSUE THREAD

**Issue by Hexagon** [denoland/deno#23189]
Version: Deno 1.42.0

Feature: https://github.com/orgs/community/discussions/16925

```
> [!NOTE]  
> Highlights information that users should take into account, even when skimming.
```

> [!NOTE]  
> Highlights information that users should take into account, even when skimming.

... becomes ...

```
> [!NOTE] Highlights information that users should take into account, even when skimming.
```

> [!NOTE] Highlights information that users should take into account, even when skimming.

... after `deno fmt`

Destroying the feature

**Comment by dsherret** [comment]
Duplicate of #21905
