### ISSUE TITLE
Add Crypto​.get​Random​Values()

### ISSUE THREAD

**Issue by chiefbiiko** [denoland/deno#2321]
Discourage users from rolling their own dice by exposing a robust CSPRNG. How ya'll think about that?

**Comment by zekth** [comment]
Sounds like a good idea. So we may add the rand crate?

ref: https://docs.rs/rand/0.5.0/rand/
ref: https://docs.rs/rand/0.5.0/rand/prng/index.html

**Comment by ry** [comment]
Is Math.random() not secure?

A related feature I want: --seed for specifying a RNG seed.

**Comment by hayd** [comment]
https://medium.com/@betable/tifu-by-using-math-random-f1c308c4fd9d

**Comment by ry** [comment]
V8 provides [v8::V8::SetEntropySource()](https://github.com/denoland/deno_third_party/blob/b9286ced4a1ee9d8c9e58088803aa3c0d60011c7/v8/include/v8.h#L8662-L8666) which (presumably) would solve this problem for Math.random().

**Comment by chiefbiiko** [comment]
Probly not really, V8 uses [`v8::V8::XorShift128()`](https://github.com/denoland/deno_third_party/blob/b9286ced4a1ee9d8c9e58088803aa3c0d60011c7/v8/src/base/utils/random-number-generator.h#L119) ([fast, but not CS](https://en.wikipedia.org/wiki/Xorshift)) as PRNG. Thus, even with high entropy seeds, its outputs have biases. Also, (re)seeding is a quite difficult task for itself. IMHO leveraging what Rust offers is the way to go.

**Comment by ry** [comment]
Thanks for the explanation.

I’m all for exposing Crypto​.get​Random​Values() using the rand crate (already built in to Deno)

**Comment by bartlomieju** [comment]
Done in #2327?
