### ISSUE TITLE
DENO_FUTURE=1 should remove deprecated TypeScript types

### ISSUE THREAD

**Issue by teleclimber** [denoland/deno#23211]
Version: Deno 1.41.3

The new `DENO_FUTURE=1` env var is a great idea, thank you. I think for completeness it should also remove TypeScript types that are deprecated. Example:

```ts
export function f(r:Deno.RequestEvent) {
	console.log(r);
}
```

```
$ DENO_FUTURE=1 deno check mod.ts
```

`Deno.RequestEvent` is deprecated therefore this should result in a TypeScript error.

https://deno.land/api@v1.42.1?s=Deno.RequestEvent

Thanks!

**Comment by bartlomieju** [comment]
I discussed it with @dsherret earlier and for now we don't plan to rewrite TS types. We might want to reconsider that closer to the actual Deno 2 release.

**Comment by dsherret** [comment]
The reason is that it would be really complicated to do.

**Comment by lucacasonato** [comment]
`DENO_FUTURE=1` is not present in Deno 2 anymore. So in Deno 2 RCs we will remove deprecated TypeScript types.
