### ISSUE TITLE
Add --seed for setting Math.random's RNG seed

### ISSUE THREAD

**Issue by ry** [denoland/deno#2322]

**Comment by mtharrison** [comment]
I'd like to have a go at this, unless someone is already working on it? 🙂

**Comment by mtharrison** [comment]
Seems like a reasonable way to do this is to call [`v8::V8::SetEntropySource(EntropySource);`](https://v8docs.nodesource.com/node-10.6/df/d43/classv8_1_1_v8.html#ad0b5012283deb7a3d1ae1c952cb8dc80). Does this sound like a good approach?

**Comment by ry** [comment]
@mtharrison Yes, I think so. But do have a look in https://github.com/denoland/deno_third_party/tree/master/v8/test/cctest and see if there is some usage (also `grep -iR seed cctest`)

**Comment by mtharrison** [comment]
Thanks for the pointer. I noticed that it's actually possible to set the seed already by passing a v8 flag:

```
$ deno --v8-flags="--random_seed=100" eval "for(let i=0;i<10;++i){console.log(Math.random())}"
0.858562739044346
0.8973397944553141
0.15335012655691727
0.36867387434349963
0.3591039342838782
0.7044499748617652
0.7461423057751548
0.3824611207183364
0.5950178237266042
0.22440633214343908

$ deno --v8-flags="--random_seed=100" eval "for(let i=0;i<10;++i){console.log(Math.random())}"
0.858562739044346
0.8973397944553141
0.15335012655691727
0.36867387434349963
0.3591039342838782
0.7044499748617652
0.7461423057751548
0.3824611207183364
0.5950178237266042
0.22440633214343908
```

Were you aware of this and wanted a direct flag in Deno?

**Comment by ry** [comment]
> Were you aware of this and wanted a direct flag in Deno?

Great! I was not. I think an alias to --seed is the nicest interface?

**Comment by mtharrison** [comment]
Sounds good to me! I'll put together a PR.
