### ISSUE TITLE
SSE no events sent when server is running

### ISSUE THREAD

**Issue by EduM22** [denoland/deno#23227]
Version: deno 1.42.1 (release, aarch64-apple-darwin)
v8 12.3.219.9
typescript 5.4.3

I'm trying to test some SSE in deno and when I start the server and call it in in postman nothing is happening no events are sent, but when I close down the server all the messages seem to be sent to postman in one go. 

I do not know if this is a possible regression in Deno.serve streaming or if I'm doing something wrong.

```
function handler(_req: Request): Response {
  let timer: number | undefined = undefined;

  const body = new ReadableStream({
    start(controller) {
      timer = setInterval(() => {
        const message = `It is ${new Date().toISOString()}\n`;
        controller.enqueue(new TextEncoder().encode(message));
      }, 1000);
    },
    cancel() {
      if (timer !== undefined) {
        clearInterval(timer);
      }
    },
  });

  return new Response(body, {
    headers: {
      "Content-Type": "text/event-stream",
    },
  });
}

Deno.serve(handler);
```

**Comment by mmastrac** [comment]
If you run `curl` against your local server, you'll see the messages being streamed correctly. I think you might have the wrong format for `text/event-stream`. Note the format of the lines described by this page:

https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events#event_stream_format
