### ISSUE TITLE
suggestion: undeprecate `--unstable` flag

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno#23237]
I don't see why the `--unstable` and `--unstable-*` flags can't coexist similarly to the `--allow-all` and `--allow-*` flags. The `--unstable` flag is great for quick prototyping in environments with loose restrictions. Removing this flag in Deno 2 could break many people's projects, seemingly without good reason.

Preparing this codebase for the removal of the `--unstable` flag, I realise how cumbersome this could be for users. The only reasonable justification for removing this flag is if it's a blocker for something technically significant.

**Comment by iuioiua** [comment]
For anyone against this idea, I welcome to port this codebase from the use of `--unstable` to `--unstable-*`.

**Comment by bartlomieju** [comment]
I think it becomes less of an issue with https://github.com/denoland/deno/pull/25519.
