### ISSUE TITLE
Deno read and write permission flags not work on Deno compile with Deno KV

### ISSUE THREAD

**Issue by h76oeI6pMxU9g4p8aCpc6Q** [denoland/deno#23241]
Version: Deno 1.42.1

test.js content
```ts
const kv = await Deno.openKv("./my_local_db");
await kv.set(["key"], "value");
kv.close();
```
deno run --unstable-kv --allow-read=./my_local_db --allow-write=./my_local_db test.js
This is work and don't ask permissions again when running.

deno compile --unstable-kv --allow-read=./my_local_db --allow-write=./my_local_db test.js
./test
This will ask read and write permissions again when executing output binary file.

This is look like Deno not passing some permission flags when deno compile.

**Comment by lucacasonato** [comment]
I think what is happening here is that the `./my_local_db` is being canonicalized to `/home/foo/bar/my_local_db` (or whatever your path is), before compiling. This is probably wrong and we should not normalize the path before compiling.

**Comment by lucacasonato** [comment]
This was fixed by https://github.com/denoland/deno/pull/23719
