### ISSUE TITLE
Add "deno runa" as an alias to "deno run -A"

### ISSUE THREAD

**Issue by ry** [denoland/deno#2325]
maybe

**Comment by bartlomieju** [comment]
-1 from me. It's just 2 less keystrokes but it's magical and yet another thing that users will have to remember...

**Comment by kevinkassimo** [comment]
`runa` sounds super confusing to me also...

**Comment by ry** [comment]
:)

**Comment by hayd** [comment]
ry: we need better security, let's require explicit permissions for js programs.
also ry: runs everything with -A.

😂
