### ISSUE TITLE
Misleading recommendation for permissions when using compiled binary

### ISSUE THREAD

**Issue by Almenon** [denoland/deno#23250]
see https://github.com/denoland/deno/discussions/18728

When I compile a program like the below

```
const file = await Deno.open("C:\\dev\\misc\\candel\\a.ts");
await file.readable.pipeTo(Deno.stdout.writable, { preventClose: true });
```

and run it (./cat.exe) I get the following:
```
┌ ⚠️  Deno requests read access to "C:\dev\misc\candel\a.ts".
├ Requested by `Deno.open()` API.
├ Run again with --allow-read to bypass this prompt.
└ Allow? [y/n/A] (y = yes, allow; n = no, deny; A = allow all read permissions) >
```
However, specifying ./cat.exe --allow-read results in the same prompt.

@mmastrac says the message should be changed

**Comment by yazan-nidal** [comment]
@Almenon 
@mmastrac 

Hello,

I tested the scenario and obtained these results.

PS D:\deno\forks\deno> .\target\debug\deno.exe compile  D:\\deno\\forks\\deno\\target\\sc.ts             
Compile file:///D:/deno/forks/deno/target/sc.ts to sc.exe
PS D:\deno\forks\deno> .\sc.exe
thread 'main' panicked at cli\standalone\binary.rs:286:66:
called `Result::unwrap()` on an `Err` value: Error("missing field `prompt`", line: 1, column: 352)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at C:\a\deno\deno\runtime\tokio_util.rs:102:36:
called `Result::unwrap()` on an `Err` value: JoinError::Panic(Id(1), ...)
PS D:\deno\forks\deno> .\sc.exe --allow-read                                                
thread 'main' panicked at cli\standalone\binary.rs:286:66:
called `Result::unwrap()` on an `Err` value: Error("missing field `prompt`", line: 1, column: 352)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at C:\a\deno\deno\runtime\tokio_util.rs:102:36:
called `Result::unwrap()` on an `Err` value: JoinError::Panic(Id(1), ...)
PS D:\deno\forks\deno> 


 Should this message be changed? If so, what is the expected message?

 && I think this incorrect reproducing for issue. Could you confirm if that is correct?
