### ISSUE TITLE
Bug: `asyncResource.asyncId` is not a function

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/deno#23263]
## Steps to reproduce

1. Create file `foo.ts` with these contents:
  ```ts
  import Tinypool from "npm:tinypool";

  const pool = new Tinypool({
    filename: new URL("./worker.mjs", import.meta.url).href,
  });
  const result = await pool.run({ a: 4, b: 6 });
  console.log(result); // Prints 10

  await pool.destroy();
  ```
2. Create file `worker.mjs` with these contents:
  ```ts
  export default ({ a, b }) =>  a + b;
  ```
3. Run `deno run -A foo.ts`

## Error

```sh
error: Uncaught (in promise) TypeError: this.publicInterface.asyncResource.asyncId is not a function
    at ThreadPool.runTask (file:///Users/marvinh/Library/Caches/deno/npm/registry.npmjs.org/tinypool/0.8.3/dist/esm/index.js:823:51)
    at Tinypool.run (file:///Users/marvinh/Library/Caches/deno/npm/registry.npmjs.org/tinypool/0.8.3/dist/esm/index.js:954:38)
    at file:///Users/marvinh/dev/test/deno-worker-2/main.ts:6:27
```

Version: Deno 1.42.1 (9b34b7ed1, 7th April 2024)

**Comment by bartlomieju** [comment]
Since we don't really polyfill `AsyncResource` (due to technical limitation) we might want to return any number from `asyncId()` method and ensure that other functions that accept it return some meaningful stubs.

**Comment by littledivy** [comment]
Fixed in https://github.com/denoland/deno/pull/23372

`tinypool` is now blocked on https://github.com/denoland/deno/issues/23362 along with Angular
