### ISSUE TITLE
Unable to use npm imports when BYONM is enabled

### ISSUE THREAD

**Issue by redabacha** [denoland/deno#23267]
Version: Deno 1.42.1

There are many times where I have one-off dependencies that are used in scripts that would not make sense to include as part of the main project package.json. However when BYONM is enabled, you are unable to use `npm:` imports anymore and will receive this error message like this if attempting to do so:
```
error: Could not find a matching package for '...' in '.../package.json'. You must specify this as a package.json dependency when the node_modules folder is not managed by Deno.
```

This is not the case for JSR and HTTPS imports which continue to work as normal which feels very inconsistent. Having NPM imports continue to function while BYONM is enabled would make mode 3 described in [this issue](https://github.com/denoland/deno/issues/23151) a much more effective and realistic option.

**Comment by lucacasonato** [comment]
There are 3 possible solutions for this as a user:

1. add the npm specifier to `deno.json` or `package.json` and install into the `node_modules`.
1. run the tools script with `--node-modules-dir=none`. This will cause Deno to use the global resolver for this script, disabling BYONM entirely
1. install the package by running `deno install` with your script as an `"entrypoint"`, which will cause it to install any packages that script depends on: `deno install -e ./main.ts` (this is not yet implemented, but will be before Deno 2.0.

**Comment by algoflows** [comment]
Hey @lucacasonato any idea when this might be resolved? I can't run any of my projects at the moment due to this issue. Will this be resolved in a week or so, or is will this get kicked further out a couple of months?

**Comment by lucacasonato** [comment]
@algoflows Why not? Do you have a package.json?

**Comment by algoflows** [comment]
@lucacasonato the ticket that was closed today https://github.com/denoland/deno/issues/25355 contains my monorepo, at somepoint nothing is building and using deno add to add npm:rxdb doesnt' resolve. There's also a thread in discord.

Here is the link to my monorepo - I keep getting this error when I try to run any of my projects.

```console
seanknowles@ip-192-168-40-254 ‹ main ↑● › : ~/Projects/Zemili/moonrepoV3/apps/zemili/backend
[0] % deno run dev
Task dev deno run -A --watch main.ts
Watcher Process started.
error: Could not find a matching package for 'npm:path-to-regexp@6.2.1' in a package.json file. You must specify this as a package.json dependency when the node_modules folder is not managed by Deno.
    at https://jsr.io/@oak/oak/16.1.0/deps.ts:87:8
Watcher Process failed. Restarting on file change...
```

My monorepo is public, try running the backend projects after running Deno Install, they don't work.

**Comment by lucacasonato** [comment]
@algoflows Your issue is #25355 which is now fixed. This is a different issue.

**Comment by dsherret** [comment]
After https://github.com/denoland/deno/pull/25399 , it will now be possible to put these jsr dependencies in the deno.json and run `deno install`. After that, the npm deps of the JSR dependencies will resolve. There's no way to make this work with other package managers without putting these missing dependencies in a package.json though.

Going to close this one because it's basically done other than https://github.com/denoland/deno/pull/25411 which can be handled there.
