### ISSUE TITLE
Implement IDL Float16Array

### ISSUE THREAD

**Issue by annevk** [denoland/deno#23277]
As per https://github.com/whatwg/webidl/pull/1398.

**Comment by bartlomieju** [comment]
We probably need to update `op2` macro to support these as well. CC @mmastrac

**Comment by mmastrac** [comment]
Do we have a v8 implementation CL to follow? We'll need to ship in rusty_v8 as well.

**Comment by bakkot** [comment]
V8 issue is [here](https://bugs.chromium.org/p/v8/issues/detail?id=14012).

**Comment by petamoriken** [comment]
I'll work on this after #23490 is merged

**Comment by marvinhagemeister** [comment]
Resolved by #23512
