### ISSUE TITLE
vsCode language server/service breaks

### ISSUE THREAD

**Issue by babakfp** [denoland/deno#23287]
Hi 👋

https://discord.com/channels/684898665143206084/688040863313428503/1226613049033490442

https://github.com/denoland/deno/assets/44144724/a81277ef-5599-461c-b894-13576e71c34a

Deno:

```
deno 1.42.1 (release, x86_64-pc-windows-msvc)
v8 12.3.219.9
typescript 5.4.3
```

vsCode:

```
Version: 1.88.0 (user setup)
Commit: 5c3e652f63e798a5ac2f31ffd0d863669328dc4c
Date: 2024-04-03T13:26:18.741Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.22631
```

**Comment by lucacasonato** [comment]
Are you still seeing this with the latest Deno release?

**Comment by babakfp** [comment]
I don't know. I'll close the issue and if it happened again, I'll reopen it.
