### ISSUE TITLE
Panic when deno coverage called with --include regex that returns no matches.

### ISSUE THREAD

**Issue by thisisjofrank** [denoland/deno#23282]
Version: Deno 1.14.3

Crash caused when deno coverage called with --include regex that returns no matches.

This works:

 `deno coverage --include="^file:"`

Because we're using the same as the default condition, and files are returned.

 `deno coverage --include="^file:|foo:"`

This works, because while we've added an invalid URI, "foo:", the "file:" element still matches and returns files.

 `deno coverage --include="^foo:"`

This fails, as no files have the URL protocol of foo:

When this fails, https://github.com/denoland/deno/blob/main/cli/tools/coverage/reporter.rs#L54 calls super utils:find_root

Which has a guard condition that returns None: https://github.com/denoland/deno/blob/2670c1d580320ed01d3a7add27bc5db2a23ac80b/cli/tools/coverage/util.rs#L7

Which blows up when mapping back to a concrete file system file.

Output:

```============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: windows x86_64
Version: 1.41.3
Args: ["C:\\ProgramData\\chocolatey\\lib\\deno\\deno.exe", "coverage", "--include=^foo:"]

thread 'main' panicked at cli\tools\coverage\reporter.rs:55:38:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by 0xIchigo** [comment]
Note this issue has been address in #23353 and should be considered resolved
