### ISSUE TITLE
thread 'main' panicked at runtime/permissions/lib.rs:695:19

### ISSUE THREAD

**Issue by ladauze** [denoland/deno#23294]
Platform: linux x86_64
Version: 1.42.1
Args: ["deno", "run", "icallersa.js"]

thread 'main' panicked at runtime/permissions/lib.rs:695:19:
called `Result::unwrap()` on an `Err` value: InvalidLabelChar
stack backtrace:
   0: rust_begin_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/result.rs:1649:5
   3: core::result::Result<T,E>::unwrap
   4: deno_permissions::UnaryPermission<deno_permissions::NetDescriptor>::check_url
   5: deno_fetch::op_fetch<FP>::v8_fn_ptr
   6: Builtins_CallApiCallbackGeneric

**Comment by littledivy** [comment]
Please provide a reproducible example

**Comment by mmastrac** [comment]
Repro:

```
08:31 $ target/debug/deno repl
Deno 1.42.1
exit using ctrl+d, ctrl+c, or close()
> Deno.connect({hostname:'foo@bar.com.', port: 1})

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos aarch64
Version: 1.42.1
Args: ["target/debug/deno", "repl"]

thread 'main' panicked at runtime/permissions/lib.rs:695:19:
called `Result::unwrap()` on an `Err` value: InvalidLabelChar
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by 0f-0b** [comment]
This bug was introduced in #23084 and makes it impossible to listen on an IPv6 address (`Deno.listen({ hostname: "::", port: 0 })`) without full net permission.

**Comment by bartlomieju** [comment]
> so, what the expected outcome?

1. Deno is not panicking
2. We either need to be able to parse domains ending with a dot `.` or error gracefully

**Comment by yazan-nidal** [comment]
> > so, what the expected outcome?
> 
> 1. Deno is not panicking
> 2. We either need to be able to parse domains ending with a dot `.` or error gracefully

@bartlomieju 

I am trying to push code for fix but don't have permissions for pushing. 

**remote: Permission to denoland/deno.git denied to yazan-nidal.
fatal: unable to access 'https://github.com/denoland/deno.git/': The requested URL returned error: 403**

**Comment by bartlomieju** [comment]
> what did u mean with error gracefully?
> application should print an error and exit? 

Yes, it should print the error and exit. That means you just need to return an `Err` variant from relevant function call.

**Comment by yazan-abdalrahman** [comment]
Hello all, It's the same pull request, but I'm pushing it with an Exalt account. 
https://github.com/denoland/deno/pull/23590
https://github.com/denoland/deno/pull/24080
