### ISSUE TITLE
toAsyncIterator and "for await" loop

### ISSUE THREAD

**Issue by arcatdmz** [denoland/deno#2330]
**Question**

With Deno v0.4.0, given a StringReader instance `r`, the following code prints (potentially part of) the string:

```typescript
Deno.toAsyncIterator(r).next()
  .then(v => {
    console.log(new TextDecoder().decode(v.value));
  });
```

and the following code prints nothing:

```typescript
writeChunks(r);

async function writeChunks(r: Deno.Reader) {
  const it = Deno.toAsyncIterator(r);
  for await (const chunk of it) {
    console.log(decoder.decode(chunk));
  }
}
```

Is this behavior intended? I suspect that the behavior of "for await" loop is unintended.

**Code**

The complete test code is available at https://danoweb.site/async_iterator_test.ts?mode=edit and can be executed by `deno run http://danoweb.site/async_iterator_test.ts`.

**Context**

I found this when I was writing a web server. The above behavior can also be observed by passing a StringReader to the request handler like this: `req.respond({ body: stringReader })`

The complete test code of the HTTP server is available at https://danoweb.site/http_test.ts?mode=edit and can be executed by `deno run --allow-net http://danoweb.site/http_test.ts`.

**Comment by bartlomieju** [comment]
It looks like in your example `toAsyncIterator` returns `done` on first run, but still that should run `for await` loop exactly once. I'll investigate further and get back.

**Comment by arcatdmz** [comment]
Hi @bartlomieju, thanks for your quick response!
Now I understand the issue.

I think there are some `Reader` implementations that return the actual content after returning `{ nread: 0, eof: false }`, such as `MultiReader` defined in [deno_std/io/readers.ts](https://github.com/denoland/deno_std/blob/master/io/readers.ts#L22). (consider combining multiple file readers, each of which returns `{ nread: 0, eof: true }` in its end, triggering the `MultiReader` to return `{ nread: 0, eof: false }`.)

When dealing with such `Reader` implementations, `done: result.nread === 0` in your fix would cut off the rest of the readable content. How about always returning `done: false` in the last statement? ... like this:

```typescript
export function toAsyncIterator(r: Deno.Reader): AsyncIterableIterator<Uint8Array> {
  const b = new Uint8Array(100);
  let sawEof = false;

  return {
    [Symbol.asyncIterator](): AsyncIterableIterator<Uint8Array> {
      return this;
    },

    async next(): Promise<IteratorResult<Uint8Array>> {
      if (sawEof) {
          return { value: null, done: true };
      }

      const result = await r.read(b);
      sawEof = result.eof;

      return {
        value: b.subarray(0, result.nread),
        done: false,
      };
    }
  };
}
```

**Comment by arcatdmz** [comment]
for convenience, the definition of `toAsyncIterator` is here: https://github.com/denoland/deno/blob/9dfebbc9496138efbeedc431068f41662c780f3e/js/io.ts#L145

**Comment by bartlomieju** [comment]
You're right @arcatdmz, only downside if users have to chunk if chunk is empty, but I guess we can't help that.

**Comment by arcatdmz** [comment]
Even in the original implementation, the iterator sometimes returns empty chunks (e.g., when used for `MultiReader` that returns `{ nread: 0, eof: false }` every time it switches to a new reader).

As such, it seems to be the end user's responsibility to check that ... and I've added a fix for the `deno_std/http` module as denoland/deno_std#387.

**Comment by bartlomieju** [comment]
With #2335 merged we can close this issue
