### ISSUE TITLE
cargo install fails

### ISSUE THREAD

**Issue by reubenfirmin** [denoland/deno#23309]
Version: Deno 1.42.1

On Ubuntu 23.10, cargo install deno --locked fails with:

```
...

   Compiling dissimilar v1.0.4
   Compiling shell-escape v0.1.5
   Compiling dprint-plugin-typescript v0.89.3
   Compiling deno_doc v0.119.0
error[E0658]: use of unstable library feature 'arc_unwrap_or_clone'
   --> /home/rfirmin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/deno_doc-0.119.0/src/lib.rs:116:14
    |
116 |         .map(std::sync::Arc::unwrap_or_clone)
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #93610 <https://github.com/rust-lang/rust/issues/93610> for more information

For more information about this error, try `rustc --explain E0658`.
error: could not compile `deno_doc` (lib) due to previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `deno v1.42.1`, intermediate artifacts can be found at `/tmp/cargo-installGRH70L`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

```

**Comment by bartlomieju** [comment]
Which version of rust are you using (`rustc --version`)?

**Comment by reubenfirmin** [comment]
rustc 1.75.0 (82e1608df 2023-12-21) (built from a source tarball)

**Comment by bartlomieju** [comment]
`Arc::unwrap_or_clone` was stabilized in 1.76. Deno usually requires latest available Rust compiler (though at the moment we're still at 1.76 and not 1.77).

**Comment by reubenfirmin** [comment]
Bummer - looks like ubuntu is still on 1.75 even in the upcoming version (24.04). I don't use rust often enough to patch it systemwide.

**Comment by bartlomieju** [comment]
It should be fairly simple using Rust's installer: https://www.rust-lang.org/tools/install

**Comment by reubenfirmin** [comment]
Yeah I know @bartlomieju, but I like using the security audited packages through official sources. My short experiment with deno ends here, for now. I'll come back to it in a year.
