### ISSUE TITLE
Remapping dependencies of npm dependencies not working as expected

### ISSUE THREAD

**Issue by nestarz** [denoland/deno#23310]
I'm facing an issue when using `npm:` packages and react that is not the same target as the npm dep. Even after mapping the `react` stuff in the user's import map, I'm still getting the following errors:

```
Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons: 3. You might have more than one copy of React in the same app
TypeError: Cannot read properties of null (reading 'useRef') at useRef (file:///Users/Library/Caches/deno/npm/registry.npmjs.org/react/18.2.0/cjs/react.development.js:1630:21) at useEmblaCarousel (file:///Users/Library/Caches/deno/npm/registry.npmjs.org/embla-carousel-react/8.0.1/esm/embla-carousel-react.esm.js:6:25)
```

My imports map looks like this:

```json
{
  "react": "https://esm.sh/react",
  "react/": "https://esm.sh/react/",
  "react-dom": "https://esm.sh/react-dom/",
  "react-dom/": "https://esm.sh/react-dom/",
  "npm:react": "https://esm.sh/react",
  "npm:react/": "https://esm.sh/react/",
  "npm:react-dom": "https://esm.sh/react-dom/",
  "npm:react-dom/": "https://esm.sh/react-dom/",
  "embla-carousel-react": "npm:embla-carousel-react"
}
```

Is this a bug in deno, or am I missing something in the way I'm remapping the dependencies? I would expect the remapping to work, but it seems that the `npm:embla-carousel-react` packages are still using the `npm:/react` version instead of the one I've mapped.

Deno: 1.42

**Comment by nestarz** [comment]
Thanks @dsherret, so there is no way to map let's say react to preact ?

**Comment by dsherret** [comment]
Only if using the experimental byonm ("bring your own node_modules") feature (https://docs.deno.com/runtime/manual/tools/unstable_flags#--unstable-byonm -- ex. adding `{ "unstable": ["byonm"] }` to a deno.json), which will be the default in Deno 2.0. It requires running `npm install` to set up a node_modules folder before running.

Yes, #18191 would allow remapping dependencies within npm packages.

**Comment by nestarz** [comment]
Ok thanks @dsherret , you mean using byonm it let us do the mapping inside the package.json, or manually editing the node_modules ? And this leads to two configuration files (deno.json + package.json) right ?

**Comment by dsherret** [comment]
> you mean using byonm it let us do the mapping inside the package.json

Yes.

> And this leads to two configuration files (deno.json + package.json) right ?

Yes.

**Comment by nestarz** [comment]
> Yes, due to needing to set the unstable flag for the project (though it could be provided via the command line or via an env var).
Thanks, but package.json and deno.json might conflict ? 
Also, why not include a nodeModule specific field inside the deno.json that handle the npm dependencies and other npm specific fields. Because we don't need two json to maintain if they share some informations (linting etc...).

**Comment by dsherret** [comment]
> Thanks, but package.json and deno.json might conflict ?

No, because npm dependencies need to be setup via an explicit install command that only uses the package.json.

> Also, why not include a nodeModule specific field inside the deno.json that handle the npm dependencies and other npm specific fields. 

Tools like npm/pnpm and the node ecosystem would not understand that unfortunately.

**Comment by dsherret** [comment]
Let's track this one in https://github.com/denoland/deno/issues/18191
