### ISSUE TITLE
Stream request bodies to fetch

### ISSUE THREAD

**Issue by mrkurt** [denoland/deno#2332]
This was discussed/planned in #522.

We need this (and related http stuff) because we work with proxies quite a lot. A common pattern is:

* `fetch` a file of some kind
* `clone` response
* `fetch` to post one of the clones to a cache
* Send other clone to end user

We also get people doing things like multiplexing s3 uploads, similar problem there.

**Comment by bartlomieju** [comment]
I think this issue has been resolved in 1.7.0?

https://deno.land/posts/v1.7#support-for-codefetchcode-request-body-streaming

CC @lucacasonato

**Comment by mrkurt** [comment]
Oh that is great, I'll go play around with it but it definitely looks resolved.
