### ISSUE TITLE
Support import maps for libraries

### ISSUE THREAD

**Issue by Yohe-Am** [denoland/deno#23336]
The official [proposal](https://github.com/WICG/import-maps#scope) outlines that "it doesn't make sense for libraries to use import maps" but with the introduction to JSR, I expect most Deno based libraries will be using `deno.json` or `import_map.json` going forward. Such a repository makes it impossible to import and use such libraries directly, from `raw.github` for example, without a) having published to JSR directly or b) re-creating the library's import map locally.

Despite the proposal, supporting import maps when resolving the imports of...a specific import  (maybe an opt-in feature with an import assertion) might provide a solution here.

Run into this because I wrote this fix PR for a library my app using. I want to use my fork until upstream merges and releases my changes. I don't want to publish to JSR just to do that.

**Comment by lucacasonato** [comment]
Duplicate of #23412
