### ISSUE TITLE
`Iterator` proposal type declarations are missing

### ISSUE THREAD

**Issue by ben-laird** [denoland/deno#23357]
Version: Deno 1.42.3

## Explanation

Hello! I'm using Deno in experiments with TypeScript to learn more about the language, especially surrounding iterators and bleeding-edge ECMAScript proposals. As of `1.42` I had read that Deno has support for the `Temporal` API as well as the new `Iterator` API. When I went to use them in my own code, the language server didn't even recognize the `Iterator` namespace, and running any code with the `Temporal` namespace with Deno throws a `ReferenceError`. [Here](https://github.com/bug-squashing/denoland-deno-u1) is a link to a minimal reproduction of the issue.

## Reproduction

1. Clone the `main` branch of [this repository](https://github.com/bug-squashing/denoland-deno-u1)
2. Run `deno test` at the root of the project
3. Observe thrown errors:
  - `TS2693 [ERROR]: 'Iterator' only refers to a type, but is being used as a value here.`
  - When the offending code of the previous error is commented out, `error: ReferenceError: Temporal is not defined`

## Details

Output of `deno --version`:

```sh
deno 1.42.3 (release, aarch64-apple-darwin)
v8 12.3.219.9
typescript 5.4.3
```

**Comment by ben-laird** [comment]
Thanks for the fix with `Temporal`, wish the error was a bit more helpful.

**Comment by petamoriken** [comment]
Upstream: https://github.com/microsoft/TypeScript/pull/58222

**Comment by adamgreg** [comment]
I get a lot of type errors like `Property 'map' does not exist on type 'IterableIterator<[x, y]>` . Is that the same issue?

Is it likely to be resolved soon, now that https://github.com/microsoft/TypeScript/pull/58222 is merged?

**Comment by petamoriken** [comment]
[TypeScript 5.6 supports Stage 3 Iterator Helpers types](https://devblogs.microsoft.com/typescript/announcing-typescript-5-6/), so just wait for it to be imported to Deno. That will probably take at least a month, as TypeScript code needs to be bundled and patched.

**Comment by petamoriken** [comment]
> I get a lot of type errors like Property 'map' does not exist on type 'IterableIterator<x>' . Is that the same issue?

Yes, an `IteratorObject<T, TReturn = unknown, TNext = unknown>` interface is introduced and a `map` method is defined for it.

**Comment by adamgreg** [comment]
OK, that's great news thanks!
