### ISSUE TITLE
bug: `A rest parameter cannot be optional.` error in `deno publish --dry-run`

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno#23367]
This is happening on canary in `std`.

See https://github.com/denoland/deno_std/actions/runs/8657917253/job/23740841039

**Comment by marvinhagemeister** [comment]
I think this was resolved by https://github.com/denoland/deno/pull/23340

**Comment by iuioiua** [comment]
This appears to still be an issue: https://github.com/denoland/deno_std/actions/runs/8697486862/job/23852811118

**Comment by bartlomieju** [comment]
> This appears to still be an issue: https://github.com/denoland/deno_std/actions/runs/8697486862/job/23852811118

This is a bug in CI workflow. The workflow uses latests release and this was broken in the previous release. We should update CI script to use `canary` version instead.

**Comment by iuioiua** [comment]
My bad. I thought we did use canary.
