### ISSUE TITLE
cannot publish packages that depend on asterisk (*) imports

### ISSUE THREAD

**Issue by teidesu** [denoland/deno#23363]
### mcve

deno.json:
```json
{
    "name": "@foo/bar",
    "version": "1.0.0",
    "exports": "./mod.ts",
    "imports": {
        "@std/bytes": "jsr:@std/bytes@*"
    }
}
```

mod.ts
```ts
import { concat } from '@std/bytes/concat'

export function concatReversed(a: Uint8Array, b: Uint8Array): Uint8Array {
  return concat([b, a])
}
```

and run `deno publish`

### expected behavior

the package publishes succesfully

### actual behavior

errors out with:

```log
error: Failed to publish @foo/bar@1.0.0

Caused by:
    Failed to publish @foo/bar at 1.0.0 specifier 'jsr:@std/bytes/concat' is missing a version constraint
```

### additional notes

- the code works fine when run with `deno run`
- `--dry-run` doesn't find any issues
- it doesn't matter if there is a path or not (i.e. `from '@std/bytes'` doesn't work either)
- putting a fully specified import doesn't help (i.e. `from 'jsr:@std/bytes@*'` doesn't work either)
- more specific versions (e.g. `@0.*`) work fine

### version
```
deno 1.42.3+76df7d7 (canary, aarch64-apple-darwin)
v8 12.3.219.9
typescript 5.4.3
```

**Comment by dsherret** [comment]
This is by design. It's to prevent packages being publish that depends on any version of another package. If the interface of that package ever changes in a new package, then that package will break. For packages that are `0.x` you should at least specify a major and minor version number like: `"@std/bytes@0.222"`

**Comment by teidesu** [comment]
> This is by design.

some packages may choose to not follow semver, so this decision feels weird.
in any case, a more descriptive error and a `--dry-run` error would be nice

**Comment by dsherret** [comment]
> some packages may choose to not follow semver, so this decision feels weird.

For packages that don't follow semver, you'll want to depend on an exact version since you can't have semver guarantees.

> in any case, a more descriptive error and a `--dry-run` error would be nice

I opened https://github.com/denoland/deno/issues/23364
