### ISSUE TITLE
Request: a way to ignore import-prefix-missing errors

### ISSUE THREAD

**Issue by CAYdenberg** [denoland/deno#23384]
I have a project running a deno/oak server and some client javascript. 

There is a minimal reproduction repo here: https://github.com/CAYdenberg/import-prefix-missing

If you run `deno task dev` and visit `localhost:8000` in your browser, `Hello world` should appear in the browser js console.

The problem is in the file `clientA.js`:

```js
// deno-lint-ignore-file
// @ts-nocheck

// deno-lint-ignore import-prefix-missing
import("clientB").then(({ doIt }) => {
  doIt();
});
```

There seems to be no way to get rid of the warning 
```
Relative import path "clientB" not prefixed with / or ./ or ../deno(import-prefix-missing)
```

It seems to me that there should be a way for a repository which is _ostensibly_ Deno to contain code that is intended to be executed elsewhere.

**Comment by lucacasonato** [comment]
You can tell deno about the import map from the index.html file by specifying it inline in `deno.json`, or passing the path to it in `importMap` field in `deno.json`. That will cause these files to resolve correctly.

Disabling resolution errors in the LSP is not supported, and likely will not be supported in the future.

**Comment by CAYdenberg** [comment]
Thank you for noting the possible workaround. I will try that.

But what you're saying is that any Deno repository which also contains client javascript/typescript (code not intended to be executed in Deno runtime) must follow Deno's linting rules. And is not possible to disable those rules either at the file or line-by-line level?

I can understand why there might be implementation barriers to this particular ignore, but as this means the linter doesn't work as expected, a note should be added to the documentation for this rule.

**Comment by lucacasonato** [comment]
I think your confusion stems from the fact that you are thinking that these are linting rules. These are not linting rules. These are module resolution rules that are also present at runtime. For all Deno knows, you will execute these files in Deno, and with the configuration you told Deno about, this program will error. You can not prevent these errors at runtime with a comment (only by fixing the cause), so you can also not silence them at development time.

What it sounds to me like you want is a way to tell Deno "hey, ignore these files - they will not be executed according to Deno's rules". You can do that using the `deno.disablePaths` option in the VS Code extension. That will disable the Deno LSP entirely for these files, which will also mean that you will not get resolution errors for these imports from Deno.

**Comment by CAYdenberg** [comment]
Ok, I get it. I think because Deno is not a language per se, I was confused about the difference between "language errors" according to the LSP and linting errors, which are merely an expression of preferences in coding style.
