### ISSUE TITLE
LSP: Error on property `class` with preact

### ISSUE THREAD

**Issue by igorbrasileiro** [denoland/deno#23381]
Version: Deno 1.42.3

In my fresh projects, the Deno Language Server (LS) client is mistakenly identifying JSX files as React components rather than Preact components. 

<img width="1104" alt="image" src="https://github.com/denoland/deno/assets/15680320/ef332b53-ac8b-4398-80b0-b64185a4781b">

Diagnostics:
Type '{ children: string; class: string; }' is not assignable to type 'DetailedHTMLProps<HTMLAttributes<HTMLSpanElement>, HTMLSpanElement>'.
  Property 'class' does not exist on type 'DetailedHTMLProps<HTMLAttributes<HTMLSpanElement>, HTMLSpanElement>'. Did you mean 'className'? [2322]

my deno.json:

```json
 {
  // ...
  "compilerOptions": {
    "jsx": "react-jsx",
    "jsxImportSource": "preact",
    "lib": [
      "deno.unstable"
    ],
    "experimentalDecorators": true
  }

 }
```

**Comment by bartlomieju** [comment]
Can you reproduce this problem in latest canary (`deno upgrade --canary`)? We had a fix done last night that should fix this problem.

**Comment by igorbrasileiro** [comment]
Yeah, it's fixed. Thank you.

**Comment by bartlomieju** [comment]
Great, I'm gonna close this issue now. We're gonna release v1.42.4 later tonight.
