### ISSUE TITLE
Confusing error message with missing `node_modules` dir and BYONM

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/deno#23399]
## Steps to reproduce:

1. Create an empty `package.json` file
2. Run `DENO_FUTURE=1 deno run -A npm:jest` for example

Error:

```sh
error: '/Users/marvinh/dev/test/deno-bin-error/node_modules/jest/package.json' did not have a bin property
```

This is confusing to me, because the `jest` package _has_ a `bin` property. The problem is rather that there is no `node_modules` directory present in the first place. It should've thrown a `missing node_modules directory` error or something like that.

Version: Deno 1.42.4

**Comment by ry** [comment]
Additionally it would be great if errors like this used project relative file paths...

**Comment by eliphazb** [comment]
@marvinhagemeister this issue is still relevant ?

**Comment by marvinhagemeister** [comment]
Not anymore, the current error message is much better:

```sh
$ deno run -A npm:jest 
error: Could not find a matching package for 'npm:jest' in the node_modules directory. Ensure you have all your JSR and npm dependencies listed in your deno.json or package.json, then run `deno install`. Alternatively, turn on auto-install by specifying `"nodeModulesDir": "auto"` in your deno.json file.
```
