### ISSUE TITLE
File system paths in stack traces shouldn't be `file:` URLs

### ISSUE THREAD

**Issue by ry** [denoland/deno#23400]
Version: Deno 1.42.3

Currently when deno throws an error we get a stack trace that shows `file:` URLs instead of normal file system paths. Although this is more weby, it is less developer friendly when it comes to clicking links in VS Code and is more verbose.

**Comment by ry** [comment]
ref https://github.com/denoland/deno/issues/22671

**Comment by bartlomieju** [comment]
This was done in Deno 2.0.0.
