### ISSUE TITLE
deno v0.5.0 prints additional new line

### ISSUE THREAD

**Issue by MarkTiedemann** [denoland/deno#2345]
```
~/dev/test
❯ curl -fsSL https://deno.land/x/install/install.sh | sh -s v0.4.0
######################################################################## 100.0%
Deno was installed successfully to /Users/<redacted>/.deno/bin/deno
Run 'deno --help' to get started

~/dev/test 17s
❯ touch empty.js

~/dev/test
❯ echo "console.log('test')" > test.js

~/dev/test
❯ deno run empty.js

~/dev/test
❯ deno run test.js
test

~/dev/test
❯ curl -fsSL https://deno.land/x/install/install.sh | sh -s v0.5.0
######################################################################## 100.0%
Deno was installed successfully to /Users/<redacted>/.deno/bin/deno
Run 'deno --help' to get started

~/dev/test 12s
❯ deno run empty.js


~/dev/test
❯ deno run test.js

test

~/dev/test
❯
```

**Comment by bartlomieju** [comment]
Related to #2309

**Comment by hayd** [comment]
I wonder if should be three things here:
- No progress "bar" if not atty.
- scrub the last line [n/n], which would also fix the above (no need for the final eprintln!).
- verbose option to show every line (-D?)

cc @ry

**Comment by ry** [comment]
We should research and follow closely how ninja does this.

https://github.com/ninja-build/ninja/blob/20b30dac6698d119e7797b34d6ed2c4ed8f48417/src/line_printer.cc#L33

**Comment by hayd** [comment]
One difference with ninja is: ninja does the build, and the build only. Deno is building and then executing. I think it's quite surprising to not have idempotence here* (running `deno run foo.ts` outputs the compile output the first time, the second time it doesn't)... that said perhaps we're doing the same as rustc (what does `cargo run` do)?

*This has always been the case for deno.
