### ISSUE TITLE
Crashed when docker compose 

### ISSUE THREAD

**Issue by KunkaiLin1205** [denoland/deno#23489]
Hi, I am trying to deploy deno myself on jump server, the image looks fine when I test it locally, but it crashed when I try it remotely. 

Version: Deno 1.39.1
# 
#Fatal error in , line 0 
#Check failed: Start(). 
# 
#
# 
#FailureMessage Object: 0x7ffc56a45e30

**Comment by marvinhagemeister** [comment]
@KunkaiLin1205 Thanks for reporting an issue. Based on the information shared we know _that_ an error happened but I'm not sure if that's enough to be able to reproduce it on our end and fix it. Can you share more details of your setup? Like what does your code do? What does the code look like that triggers the error. Does upgrading to the latest Deno version resolve this?

**Comment by KunkaiLin1205** [comment]
Thanks for replying! My case might be a little bit complicated, but I try it with the example provided in deno-docker and get the same error. I produced the image by docker build in M1 machine but setting the platform appropriately (the jump server is x86, but as I set platform, I believe it's not a compatibility problem). On jump server, I just docker run the image I pushed.

**Comment by KunkaiLin1205** [comment]
Hi, is there any follow ups :)

**Comment by KunkaiLin1205** [comment]
I probably find the main reason, I try to run  docker run  denoland/deno:1.42.1  bash -c 'deno' on jump server, and it gets the same error. The version on jump server is: 
deno 1.42.4 (release, x86_64-unknown-linux-gnu)
v8 12.3.219.9
typescript 5.4.3

**Comment by oyzhen** [comment]
You can try `--security-opt seccomp=unconfined` on docker version below 20.0

**Comment by lucacasonato** [comment]
Sorry, we can't debug this unless you provide a reproduction of some sort (a repo with a script + docker + docker-compose file we can run). Feel free to reopen this issue once you have created such a reproduction :)
