### ISSUE TITLE
FsWatcher.close() error : BadResource (Bad resource ID)

### ISSUE THREAD

**Issue by pierreglibert** [denoland/deno#23488]
Hi community 🙂
I have an error when i try to close watcher after it throw remove event on directory.
Error : Bad resource ID
```
error: Uncaught (in promise) BadResource: Bad resource ID
        this._watcher.close()

```
My goal is to close watcher on specific directory when it is removed.
Perhaps Deno closes automaticaly it when path is removed and send me this error ...
Can you help me please ? 

Thank you 😄

**Comment by marvinhagemeister** [comment]
@pierreglibert How can we reproduce the issue? Can you share the code that led to this error?

**Comment by pierreglibert** [comment]
@marvinhagemeister  I'm investigating on it. I will get back to you later :)

**Comment by pierreglibert** [comment]
It wasn't a bug. I forgot "return" instead "continue" in "for ... await ... of" loop on watcher.
