### ISSUE TITLE
Support task concatenating/expanding

### ISSUE THREAD

**Issue by grafluxe** [denoland/deno#23494]
Is there (or can there be) a way to concatenate tasks? This would allow for more DRY task scripts.

Something like this:

```ts
"tasks": {
  "start": "deno run --allow-x --allow-y --allow-z mod.ts",
  "dev": "deno task --watch start
}
```

`deno task dev` ===  `deno run --allow-x --allow-y --allow-z --watch mod.ts` 
^ Run `start` task with all it's flags, plus add --watch

**Comment by dsherret** [comment]
```json
{
  "tasks": {
    "start": "echo run --allow-x --allow-y --allow-z $START_TASK_FLAGS mod.ts",
    "dev": "START_TASK_FLAGS=--watch deno task start"
  }
}
```

**Comment by iuioiua** [comment]
To add to David's reply, shell variables are documented [here](https://docs.deno.com/runtime/manual/tools/task_runner#shell-variables).

**Comment by grafluxe** [comment]
Thanks!
