### ISSUE TITLE
WebGPU: Deno's GPUCanvasConfiguration is not standard

### ISSUE THREAD

**Issue by chirsz-ever** [denoland/deno#23508]
Version: Deno 1.42.4

Now the argument of `GPUCanvasContext.configure` require `width` and `height` members, but the standard do not.

reference

- [GPUCanvasConfiguration of Deno 1.42.4](https://deno.land/api@v1.42.4?s=GPUCanvasConfiguration)
- [MDN - GPUCanvasContext.configure](https://developer.mozilla.org/en-US/docs/Web/API/GPUCanvasContext/configure)
- https://www.w3.org/TR/webgpu/#canvas-configuration

**Comment by lucacasonato** [comment]
I talked to @littledivy, and I think we should remove `width` and `height` from this method, and add them as required arguments for `Deno.UnsafeWindowSurface`.
