### ISSUE TITLE
Deno panic with --inspect-wait

### ISSUE THREAD

**Issue by TopchetoEU** [denoland/deno#23528]
Version: Deno 1.42.1

When trying to launch Deno in debug mode with the --inspect-wait flag, while the '9229' port is used by another process, Deno straight away panics with a "AddrInUse" error.

I believe the Deno CLI should instead handle this error and print it in a more readable manner.

**Comment by marvinhagemeister** [comment]
@TopchetoEU Are you using the latest Deno version? Asking because an issue just like that was resolved in [v1.42.3](https://github.com/denoland/deno/releases/tag/v1.42.3) .

**Comment by TopchetoEU** [comment]
My bad, I didn't check for newer versions, Deno seems to give a proper error message on 1.42.4
