### ISSUE TITLE
IPv6 forbidden on deno.land, deno.com and jsr.io

### ISSUE THREAD

**Issue by Maluscat** [denoland/deno#23530]
This is more of a meta issue regarding websites managed by the Deno team; I haven't found a better place to report it.

For quite some time now, my server's IPv6 has been unable to reach `deno.land`, `deno.com` and `jsr.io`, practically rendering Deno useless. I cannot pinpoint a date, but I know for sure that it did work at least two years ago (very helpful, I know). I also haven't done anything in my knowledge that would trigger any IP blocks or malicious flagging. Any available credibility checks for the IPv6 come out clean.

Curiously, the returned error messages vary between websites:
```sh
curl -L -6 https://deno.land  # Or https://deno.com since they seem to be aliases of each other
# curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to deno.land:443
```
```sh
curl -L -6 https://jsr.io
# 403 Forbidden
```
```sh
curl -L -6 https://google.com
# Unaddressed abuse complaints; Please solve the captcha.
```

In the former case it looks like the TLS handshake is being rejected somewhere along the way. My server's certificates are up to date and even trusting the `deno.com`/`deno.land` certificate explicitly does not help.

The only other domains I could find that also seem to block my IPv6 are the Google search pages (`google.com`, `google.de`, etc.) as seen above, but not other Google services like `youtube.com`. Thus I'm wondering whether the mentioned Deno websites are using some Google protection layer other than its DNS. Any help would be greatly appreciated, since my hoster is not willing to swap my IPv6.

If you need my IP, I can DM it to you on Discord.

Thanks!

**Comment by lucacasonato** [comment]
Can you email support@deno.com with your IP address and the region you are in?

**Comment by Maluscat** [comment]
I've written a mail (subject "Deno issue 23530: IPv6"), in case it went under (no pressure)

**Comment by lucacasonato** [comment]
Closing as this is being handled via email.

**Comment by Maluscat** [comment]
Fair, however I have not yet received a reply regarding my problem. I don't want to be pushy, but I would appreciate at least something for me to be able to decide whether I should start moving my Deno projects to Node.
