### ISSUE TITLE
release v.1.43.0 missing assets

### ISSUE THREAD

**Issue by andreial** [denoland/deno#23557]
Version: Deno 1.43.0

The new release is missing assets, such as `deno-x86_64-unknown-linux-gnu.zip`:
https://github.com/denoland/deno/releases/tag/v1.43.0

![Screenshot 2024-04-25 at 17 13 27](https://github.com/denoland/deno/assets/43535493/2178c646-80df-4745-8a20-63aaaeae92c4)

**Comment by bartlomieju** [comment]
The v1.43.0 has been postponed, I've removed the tag for now.
