### ISSUE TITLE
Add serde_derive crate

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#2359]
@ry regarding our discussion on Gitter - let's use `serde_derive` for import map deserialization. Could you add it?

**Comment by kevinkassimo** [comment]
I tried in the past once and failed due to some complications with proc2-macro... hopefully we can have it done this time

**Comment by piscisaureus** [comment]
I'm working on it, but indeed we currently lack support for proc_macro crates in our gn build system so that needs to be fixed first.

**Comment by ry** [comment]
ref https://github.com/denoland/deno/pull/2362

**Comment by piscisaureus** [comment]
Done: https://github.com/denoland/deno/commit/3ff240b963de8422e6c2567572dbc551aafb0797
