### ISSUE TITLE
deno lint no-undef dont fully implement, it is not support comment declare

### ISSUE THREAD

**Issue by samegek** [denoland/deno#23611]
windows deno 1.42.4
```js
/*global a*/
/*eslint no-undef: ["error", { "typeof": true }] */

if(typeof a === "string"){}
```
deno dont recognize a
background: i develop a chrome extension with js, using deno as linter

**Comment by lucacasonato** [comment]
`deno lint` does not complain about this. Please add information about what is failing (re-open this issue, or create a new one).

**Comment by samegek** [comment]
@lucacasonato 
it should ok, because gloabl decalre, but error
`deno lint --rules-include=no-undef a.js`
```js
/* global a */
let b = 1
let c = a + b
```
output error[no-undef]: a is not defined

it should output error, a is not defined, but ok
use deno lint --rules-include=no-undef a.js
```js
if(typeof a === "string"){console.log("hello")}
```

**Comment by lucacasonato** [comment]
Can you open an issue in `denoland/deno_lint` to add a feature to handle `/* global a */` comments in the `no-undef` rule? The reason I initially closed this, is because `no-undef` is disabled by default.
