### ISSUE TITLE
Scoping a Specifier for All Dependencies in Import Maps

### ISSUE THREAD

**Issue by nestarz** [denoland/deno#23612]
I would like to know if import maps can scope a specifier for all its dependencies.

Consider the following example:

```json
...
  "compilerOptions": {
    "jsx": "react-jsx",
    "jsxImportSource": "react"
  },
  "scopes": {
    "https://jsr.io/@scope/my-package/0.0.0/": {
      "react/jsx-runtime": "jsr:@scope/my-package/0.0.0/react/jsx-runtime"
    }
  }
```

This configuration only scopes the specifier for modules that start with "https://jsr.io/@scope/my-package/0.0.0/". However, if my package at "https://jsr.io/@scope/my-package/0.0.0" imports an another JSR package, which needs the same jsx-runtime, it doesn't remap the "react/jsx-runtime" specifier for that package. I would need to add a separate scope for each dependency, which becomes cumbersome, and even so, I can't add a scope inside a scope.

Is there a way to apply the mapping for "react/jsx-runtime" not only to "@scope/my-package/0.0.0" but also to all its dependencies, without having to explicitly define a scope for each dependency? either from the deno.json, or via an app script ?

**Comment by lucacasonato** [comment]
You can use the `"imports"` field.

**Comment by nestarz** [comment]
@lucacasonato I know about the imports field thanks.
It doesn’t address my issue though, I was looking for a way to apply a mapping for a file and all it’s nested dependencies in an isolated fashion.
Scopes only works at one depth, and imports do it for all. I was looking for a a way to « do it for all » solution but starting a certain specific scope.

For example my use case is the following, I would like all files that have a **use client** directive to import the client version of react, but also all it’s dependencies without explicitly adding every single of them, also because some dependencies are shared so they also can be imported with a different resolution (server or client).

Let me know if that’s not clear and also I understand if that’s not possible at all or is a goal for Deno to support that usecase.
