### ISSUE TITLE
Use "URL.canParse()" rather than "URL.parse()"

### ISSUE THREAD

**Issue by h76oeI6pMxU9g4p8aCpc6Q** [denoland/deno#23639]
I just read the Deno 1.43 product update blog,

I saw it mentioned the new Web API "URL.parse()", but I can't found this on MDN web doc.
https://deno.com/blog/v1.43#urlparse-web-api

I found the Web API "URL.canParse()" which have similar function but return only true/false value (Boolean type)
https://developer.mozilla.org/en-US/docs/Web/API/URL/canParse_static

So, there is NOT exist a Web API named "URL.parse()" which is return null for invalid urls / return same values of URL() constructor for valid urls.

I think Deno need to replace "URL.parse()" by "URL.canParse()" on next release to meet the web standard.
This also avoid the Web API (Global scope) incompatibility of different JavaScript runtime / browser.

**Comment by crowlKats** [comment]
The URL specification does have a static parse function: https://url.spec.whatwg.org/#dom-url-parse, so it is spec compiant. MDN might just not have added it yet.

**Comment by dsherret** [comment]
This is standard, see https://github.com/whatwg/url/pull/825
