### ISSUE TITLE
feat: `deno serve` pick random free port

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/deno#23649]
When working on multiple projects, I don't in particular care which port they are running on. With the default port of `deno serve` being `8000` I'd need to remember to pick a different port whenever I start a new project next to an already running one. Would be cool if we had a way to pick a free port.

**Comment by Hasan-Alrimawi** [comment]
Hello @marvinhagemeister 

I'd like to try solving this issue.

**Comment by bartlomieju** [comment]
I believe this issue has now been solved by https://github.com/denoland/deno/pull/23846. This will be released in Deno v1.44 next week.
