### ISSUE TITLE
wrong tag with 1.43.1

### ISSUE THREAD

**Issue by chenrui333** [denoland/deno#23640]
👋 looks like both 1.43.1 and 1.43.0 are tagging the same commit

![image](https://github.com/denoland/deno/assets/1580956/b9edfa0b-1b6e-4b7b-a6b5-eebb5efe4a23)

cc @littledivy

**Comment by dsherret** [comment]
Yeah, should have been just v1.43.1. v1.43.0 was never released. Not sure what we should do here other than delete the wrong v1.43.0 tag.

**Comment by dsherret** [comment]
Oh no, the release says v1.43.0, but actually that should be v1.43.1 https://github.com/denoland/deno/releases/tag/v1.43.0

**Comment by bartlomieju** [comment]
We had a small problem with the release. I made sure that both `v1.43.0` and `v1.43.1` are now available, though they are still pointing to the same commit. I suggest for Homebrew to just skip v1.43.0 and release v1.43.1 instead.

**Comment by chenrui333** [comment]
oh ok, sounds good then. Can you also mark 1.43.1 as latest release as well? 🙏

**Comment by chenrui333** [comment]
oh, you already did, nice!! <3

<img width="1131" alt="image" src="https://github.com/denoland/deno/assets/1580956/b8a63d73-00ee-488d-b830-49bc017b97ef">
