### ISSUE TITLE
Using DuckDB with Deno

### ISSUE THREAD

**Issue by nshiab** [denoland/deno#23656]
Version: Deno 1.41.3

Hi!

I tried to use [duckdb-node](https://github.com/duckdb/duckdb-node) with Deno by running this `index.ts`.

```ts
import duckdb from "npm:duckdb";

const db = new duckdb.Database(":memory:");
```

But when running `deno run -A index.ts`, I get this error:

```sh
naelshiab test  $ deno run -A index.ts   
error: Uncaught (in promise) Error: Cannot find module '/Users/naelshiab/Library/Caches/deno/npm/registry.npmjs.org/duckdb/0.10.1/lib/binding/duckdb.node'
Require stack:
- /Users/naelshiab/Library/Caches/deno/npm/registry.npmjs.org/duckdb/0.10.1/lib/duckdb-binding.js
- /Users/naelshiab/Library/Caches/deno/npm/registry.npmjs.org/duckdb/0.10.1/lib/duckdb.js
- /Users/naelshiab/Library/Caches/deno/npm/registry.npmjs.org/duckdb/0.10.1/lib/duckdb.js
    at Function.Module._resolveFilename (node:module:609:15)
    at Function.Module._load (node:module:487:27)
    at Module.require (node:module:662:19)
    at require (node:module:776:16)
    at Object.<anonymous> (file:///Users/naelshiab/Library/Caches/deno/npm/registry.npmjs.org/duckdb/0.10.1/lib/duckdb-binding.js:4:15)
    at Object.<anonymous> (file:///Users/naelshiab/Library/Caches/deno/npm/registry.npmjs.org/duckdb/0.10.1/lib/duckdb-binding.js:7:4)
    at Module._compile (node:module:718:34)
    at Object.Module._extensions..js (node:module:732:10)
    at Module.load (node:module:643:32)
    at Function.Module._load (node:module:524:12)
```

Is it possible to use DuckDB with Deno?

Thank you very much for your great work.

**Comment by bartlomieju** [comment]
This is because we currently don't support "lifecycle hooks" when installing npm dependencies (eg. `postinstall` script). We have a PR that implements that that's WIP: https://github.com/denoland/deno/pull/23558.

You can work around this for now if you use "bring your own node modules" - by installing using `npm/yarn/pnpm`.

**Comment by nshiab** [comment]
Thank you!

**Comment by MaximePawlakFr** [comment]
Hi @nshiab , have you succeeded?

I tried but I got this error: 
```
============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos aarch64
Version: 1.40.4
Args: ["deno", "run", "--allow-all", "data/index.ts"]

thread 'main' panicked at cli/napi/js_native_api.rs:2508:56:
called `Result::unwrap()` on an `Err` value: BadType { actual: "v8::data::Value", expected: "v8::data::Array" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
My data/index.ts contains:
```
import duckdb from "duckdb";
console.log(duckdb)
const db = new duckdb.Database(":memory:");
console.log(db)
```
The steps are: 
- setup the project with npm: `npm init`
- `npm install duckdb`
- try to run: `deno run --allow-all   ./data/index.ts`
```
error: Uncaught (in promise) Error: Cannot find module 'MY_PATH/node_modules/.deno/duckdb@0.10.2/node_modules/duckdb/lib/binding/duckdb.node'
Require stack:
- MY_PATH/node_modules/.deno/duckdb@0.10.2/node_modules/duckdb/lib/duckdb-binding.js
- MY_PATH/node_modules/.deno/duckdb@0.10.2/node_modules/duckdb/lib/duckdb.js
- MY_PATH/node_modules/.deno/duckdb@0.10.2/node_modules/duckdb/lib/duckdb.js
    at Function.Module._resolveFilename (node:module:622:15)
    at Function.Module._load (node:module:500:27)
    at Module.require (node:module:675:19)
    at require (node:module:789:16)
    at Object.<anonymous> (file://MY_PATH/node_modules/.deno/duckdb@0.10.2/node_modules/duckdb/lib/duckdb-binding.js:4:15)
    at Object.<anonymous> (file://MY_PATH/node_modules/.deno/duckdb@0.10.2/node_modules/duckdb/lib/duckdb-binding.js:7:4)
    at Module._compile (node:module:731:34)
    at Object.Module._extensions..js (node:module:745:10)
    at Module.load (node:module:656:32)
    at Function.Module._load (node:module:537:12)
```
- then move to duckdb: `cd node_modules/duckdb`
- install it: `npm install`
- I can see the missing `duckdb.node` under node_modules > duckdb > lib > binding > duckdb.node
- run again: `deno run --allow-all   ./data/index.ts `
- and finally get:
```

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos aarch64
Version: 1.40.4
Args: ["deno", "run", "--allow-all", "./data/index.ts"]

thread 'main' panicked at cli/napi/js_native_api.rs:2508:56:
called `Result::unwrap()` on an `Err` value: BadType { actual: "v8::data::Value", expected: "v8::data::Array" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Have you managed to use duckdb in Deno? 
What could I do?

Best

**Comment by nshiab** [comment]
Hi @MaximePawlakFr!

For now, I am using node/npm. But @bartlomieju is working on it https://github.com/denoland/deno/pull/23558.

**Comment by bartlomieju** [comment]
It's an internal bug in Deno, but it seems easy enough to fix it to make example from DuckDB's page work. I'll try to have it done tonight.

**Comment by bartlomieju** [comment]
I merged a fix that makes DuckDB work. It should be available in canary in ~2h - you can then use `deno upgrade --canary` to try it out.

**Comment by MaximePawlakFr** [comment]
Thank you Bartek.

I've just updated deno to `deno 1.43.1+cbb78e1`.

I tried again. I can load duckdb without the previous error.

But I can not run any request to duckdb. I get a `segmentation fault`.

Here is my code: 
```ts

import duckdb from "duckdb";
const db = new duckdb.Database(":memory:"); 
console.log(db);

Deno.serve(async (req) => {

    const request =
      "SELECT * FROM 'https://shell.duckdb.org/data/tpch/0_01/parquet/orders.parquet' LIMIT 1000;";
    console.log(request);

    const result = await new Promise((resolve, reject) => {
      db.all(request, function (err, res) {
        console.log(res);
        if (err) {
          console.warn(err);
          reject(err);
        }
        resolve(res);
      });
    });

    const res = JSON.stringify(
      result,
      (key, value) => typeof value === "bigint" ? value.toString() : value, // return everything else unchanged
    );

    return new Response(
      res,
      {
        headers: { "Content-Type": "application/json" },
      },
    );
});

```

I run `deno run --allow-all index.ts `

I see in my terminal:
```
Database {}
Listening on http://localhost:8000/
SELECT * FROM 'https://shell.duckdb.org/data/tpch/0_01/parquet/orders.parquet' LIMIT 1000;
zsh: segmentation fault  deno run --allow-all index.ts
```

It looks like something went wrong with duckdb. Any idea what?

Regards

**Comment by bartlomieju** [comment]
So far I'm not able to reproduce this segmentation fault on my end - I get results as expected. Can you update once again to latest canary and try again?

**Comment by bartlomieju** [comment]
@nshiab you can, we've been shipping canary version for ARM Macs for a couple months now :)

**Comment by nshiab** [comment]
@bartlomieju What am I doing wrong? 😢 

<img width="1236" alt="Screenshot 2024-05-07 at 9 04 47 AM" src="https://github.com/denoland/deno/assets/11160343/f427c724-a3e1-4259-9d3e-ff86e4a119ed">

Thank you so much for your help!

**Comment by nshiab** [comment]
You are right. Stupid mistake on my end. Sorry.

Unfortunately, it doesn't seem to work on my laptop. Should I do something differently?

<img width="1279" alt="Screenshot 2024-05-07 at 10 32 33 AM" src="https://github.com/denoland/deno/assets/11160343/f0154dde-9ca3-4c6a-9ff1-01a89c7824c4">

**Comment by bartlomieju** [comment]
@nshiab the problem with `postinstall` scripts is not solved - you still need to use `npm install` and use `DENO_FUTURE=1` env var, I fixed the problem related to actual execution of DuckDB.

**Comment by nshiab** [comment]
Hmmm. I tried again but I am still doing something wrong I guess. It's probably best if I wait for `postinstall` scripts to work.

<img width="1436" alt="Screenshot 2024-05-07 at 4 00 46 PM" src="https://github.com/denoland/deno/assets/11160343/df2c4cd3-e912-4106-86dc-c4c5c81f42f7">

**Comment by bartlomieju** [comment]
@nshiab you need to specify `DENO_FUTURE` env var in your terminal when you run the `deno` command:
```
# bash 
DENO_FUTURE=1 deno run -A index.ts
# fish
env DENO_DUTURE=1 deno run -A index.ts
```

**Comment by nshiab** [comment]
IT WORKS! Amazing! Thanks for your patience @bartlomieju!

But... if I actually run a query, it fails. This is an example from the [duckdb repo](https://github.com/duckdb/duckdb-node).

<img width="2506" alt="Screenshot 2024-05-07 at 4 33 24 PM" src="https://github.com/denoland/deno/assets/11160343/fbc78487-4f96-4477-b6c5-8f12f0131657">

**Comment by bartlomieju** [comment]
Thanks! I don't get a segfault, but I'm getting a panic like so:
```js
import duckdb from "duckdb";
const db = new duckdb.Database(":memory:"); 


const con = db.connect();

con.all("SELECT 42 AS fortytwo", function (err, res) {
  if (err) {
    console.warn(err);
  }
  console.log(res[0].fortytwo);
})

```

```
env DENO_FUTURE=1 deno run -A index.ts

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos aarch64
Version: 1.43.1+998036b
Args: ["deno", "run", "-A", "index.ts"]

thread 'main' panicked at cli/napi/js_native_api.rs:2348:63:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

I'll try to debug this one as well.

**Comment by MaximePawlakFr** [comment]
> So far I'm not able to reproduce this segmentation fault on my end - I get results as expected. Can you update once again to latest canary and try again?

I've just did: `deno 1.43.1+998036b`
I still get the same `segmentation fault`.

**Comment by devsnek** [comment]
duckdb seems to be working as of https://github.com/denoland/deno/pull/24101.

**Comment by bartlomieju** [comment]
@nshiab you can use it with canary today (`deno upgrade --canary`) or wait for v1.44.2 that will be released later this week.

**Comment by nshiab** [comment]
Awesome! It works! Thanks a lot for your work @devsnek @bartlomieju!

Do you have an idea of when the `postinstall` issue would be fixed?

I have a library that I would love to put on jsr.io but it's using DuckDB.
https://github.com/nshiab/simple-data-analysis

And what does FUTURE=1 stand for?

Again, thank you!

**Comment by bartlomieju** [comment]
> Do you have an idea of when the postinstall issue would be fixed?

You can track #23558 for progress.

> And what does FUTURE=1 stand for?

I think you meant `DENO_FUTURE=1`. In essence it enabled the "Deno 2" mode that makes Deno v1.4x behave as if it was Deno 2.

**Comment by nshiab** [comment]
Again, thank you for taking the time to answer my questions @bartlomieju 🙏 

I checked the dev blog. Fingers crossed for a v2 this year!

https://deno.com/blog/2024-survey-results-and-roadmap

Take care. 🙂

**Comment by localhosted** [comment]
Is duckdb still working? I'm still getting the same error:

> error: Uncaught (in promise) Error: Cannot find module 'C:\Users\Usuario\AppData\Local\deno\npm\registry.npmjs.org\duckdb\1.0.0\lib\binding\duckdb.node'

> deno 2.0.0-rc.2+3f15e30 (canary, release, x86_64-pc-windows-msvc)
v8 12.9.202.13-rusty
typescript 5.5.2

I can't get duckdb from node to work, nor the wasm version

**Comment by bartlomieju** [comment]
@localhosted how did you install DuckDB in your project? Do you have a code you can share?

**Comment by localhosted** [comment]
I just did `deno init --serve ` , then in main.ts:
```

import duckdb from "npm:duckdb"
const db = new duckdb.Database(':memory:'); 
db.all('SELECT 42 AS fortytwo', function(err, res) {
  if (err) {
    console.warn(err);
    return;
  }
  console.log(res[0].fortytwo)
});
```

**Comment by bartlomieju** [comment]
Add this line to your `deno.json`: `"nodeModulesDir": "auto"`. Remove `npm:` prefix from your import statement. Run `deno install --allow-scripts=npm:duckdb npm:duckdb`.

`duckdb` depends on native addon that are currently not supported when using `npm:` specifiers.

**Comment by localhosted** [comment]
Thanks, it works 

Is it compatible with `deno compile`? I tried running the compiled .exe but got a ` LoadLibraryExW failed`

**Comment by bartlomieju** [comment]
No, native add-ons are currently not supported in `deno compile`

**Comment by plutonium-239** [comment]
I face the same error, although only while deploying through `deployctl` - it runs fine locally.

<details><summary>Traceback:</summary>

```
error: The deployment failed: UNCAUGHT_EXCEPTION

Error: Cannot find module '@duckdb/node-bindings-linux-x64/duckdb.node'
Require stack:
- /node_modules/.deno/@duckdb+node-bindings@1.3.1-alpha.22/node_modules/@duckdb/node-bindings/duckdb.js
- /node_modules/.deno/@duckdb+node-api@1.3.1-alpha.22/node_modules/@duckdb/node-api/lib/duckdb.js
- /node_modules/.deno/@duckdb+node-api@1.3.1-alpha.22/node_modules/@duckdb/node-api/lib/index.js
- /node_modules/.deno/@duckdb+node-api@1.3.1-alpha.22/node_modules/@duckdb/node-api/lib/index.js
    at Module._resolveFilename (node:module:619:15)
    at Module._load (node:module:497:27)
    at Module.require (node:module:681:19)
    at require (node:module:816:16)
    at getNativeNodeBinding (file:///node_modules/.deno/@duckdb+node-bindings@1.3.1-alpha.22/node_modules/@duckdb/node-bindings/duckdb.js:9:20)
    at Object.<anonymous> (file:///node_modules/.deno/@duckdb+node-bindings@1.3.1-alpha.22/node_modules/@duckdb/node-bindings/duckdb.js:24:18)
    at Object.<anonymous> (file:///node_modules/.deno/@duckdb+node-bindings@1.3.1-alpha.22/node_modules/@duckdb/node-bindings/duckdb.js:26:4)
    at Module._compile (node:module:745:34)
    at loadMaybeCjs (node:module:770:10)
```
</details>

I've tried installing through both `deno` and `npm`, same error.

**Comment by bartlomieju** [comment]
@plutonium-239 Deno Deploy does not support native Node addons

**Comment by plutonium-239** [comment]
@bartlomieju that's unfortunate

I tried to work with `@duckdb/duckdb-wasm`, but that fails to run locally. 
The initial errors come up because of `global` not being defined, and if we workaround that with `--unstable-node-globals`, it goes past that and an error emerges on `Buffer.from` with `Buffer` not being defined:

```js
error: Uncaught (in worker "") (in promise) TypeError: Cannot read properties of undefined (reading 'from')
    at b (https://cdn.jsdelivr.net/npm/@duckdb/duckdb-wasm@1.29.1-dev132.0/dist/duckdb-browser-eh.worker.js:1:516993)
    at h (https://cdn.jsdelivr.net/npm/@duckdb/duckdb-wasm@1.29.1-dev132.0/dist/duckdb-browser-eh.worker.js:1:516770)
    at https://cdn.jsdelivr.net/npm/@duckdb/duckdb-wasm@1.29.1-dev132.0/dist/duckdb-browser-eh.worker.js:1:524028
    at https://cdn.jsdelivr.net/npm/@duckdb/duckdb-wasm@1.29.1-dev132.0/dist/duckdb-browser-eh.worker.js:1:524182
    at https://cdn.jsdelivr.net/npm/@duckdb/duckdb-wasm@1.29.1-dev132.0/dist/duckdb-browser-eh.worker.js:1:634
    at https://cdn.jsdelivr.net/npm/@duckdb/duckdb-wasm@1.29.1-dev132.0/dist/duckdb-browser-eh.worker.js:1:748915
    at https://cdn.jsdelivr.net/npm/@duckdb/duckdb-wasm@1.29.1-dev132.0/dist/duckdb-browser-eh.worker.js:1:765065
ErrorEvent {
  bubbles: false,
  cancelable: true,
  composed: false,
  currentTarget: Worker { onerror: null, onmessage: null, onmessageerror: null },
  defaultPrevented: false,
  eventPhase: 2,
  srcElement: null,
  target: Worker { onerror: null, onmessage: null, onmessageerror: null },
  returnValue: true,
  timeStamp: 0,
  type: "error",
  message: "Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'from')",
  filename: "https://cdn.jsdelivr.net/npm/@duckdb/duckdb-wasm@1.29.1-dev132.0/dist/duckdb-browser-eh.worker.js",
  lineno: 1,
  colno: 516993,
  error: null
}
error in duckdb worker: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'from')
error: Uncaught (in promise) Error: Unhandled error in child worker.
    at Worker.#pollControl (ext:runtime/11_workers.js:204:19)
    at eventLoopTick (ext:core/01_core.js:178:7)
```

I saw that you had worked quite a bit on the `--unstable-node-globals`, and that this flag is supposedly also adding `Buffer`, so you might be the best person for this tbh 😅

**Comment by bartlomieju** [comment]
@plutonium-239 could you please open a new issue with the repro code there? I'm sure there's an easy fix here.
