### ISSUE TITLE
Bug: `deno serve --host localhost` prints invalid URL

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/deno#23650]
When passing `--host localhost` to `deno serve`, the CLI will print an invalid URL: `http://::1:8000/`

## Steps to reproduce

```ts
// main.ts
export default {
  fetch(_req) {
    return new Response("it works");
  },
};
```

Then run `deno serve --host localhost main.ts`

## CLI output

```sh
$ deno serve --host localhost main.ts 
deno serve: Listening on http://::1:8000/
```

Version: Deno 1.43.1

**Comment by mmastrac** [comment]
@marvinhagemeister is this Linux or Mac? It looks like the socket address is being resolved here which is a bit strange.

**Comment by marvinhagemeister** [comment]
@mmastrac I'm on macOS

**Comment by marvinhagemeister** [comment]
Turns out that the issue can be reproduced with `Deno.serve` alone:

```ts
Deno.serve({ hostname: "localhost" }, () => new Response("foo"));
```

Output:

```sh
$ deno run -A foo.ts
Listening on http://::1:8000/
```

**Comment by mmastrac** [comment]
@marvinhagemeister What do you have in `/etc/hosts` (`cat /etc/hosts | grep "localhost"`)? Also, do you have IPv6 configured under your network settings? 

I wonder if this is a weird IPv6 resolution thing.

**Comment by marvinhagemeister** [comment]
The default host file on macOS looks like this:

```sh
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1	localhost
255.255.255.255	broadcasthost
::1             localhost
```

**Comment by dsherret** [comment]
Just ran into this on Windows. In v1.42.3 it prints localhost and in 1.43.1 it prints "::1"

```
Deno.serve({
  hostname: "localhost",
  onListen(details) {
    console.log(details);
  },
}, (request) => {
  return new Response(null);
})
```

**Comment by dsherret** [comment]
It also occurs on Linux and Mac: https://github.com/dsherret/dax/actions/runs/8951547585/job/24587971522

**Comment by AverageHelper** [comment]
Seems to also occur with `Deno.serve` in macOS and Deno 1.43.1:

```ts
Deno.serve({ hostname: "localhost" }, /* handler */);
```

Prints `http://::1:8000/`

As an aside, pasting the given URL into Firefox results in a web search, rather than an attempt to connect to the local webserver as expected. According to [RFC2732](http://www.ietf.org/rfc/rfc2732.txt), the URL should instead be rendered as `http://[::1]:8000/`. Adding these brackets around the IPv6 address causes browsers to behave as expected.
