### ISSUE TITLE
deno publish requires base classes to be exported or else "Failed ensuring public API type output is valid."

### ISSUE THREAD

**Issue by andykais** [denoland/deno#23658]
Version: Deno 1.43.1

```
Checking for slow types in the public API...
Check file:///Users/andrew/Code/andykais/ts-rpc/client.ts
Check file:///Users/andrew/Code/andykais/ts-rpc/adapters/oak.ts
error: Failed ensuring public API type output is valid.

TS2304 [ERROR]: Cannot find name 'adapter_base'.
class ServerAdapter extends adapter_base.ServerAdapter {
                            ~~~~~~~~~~~~
    at file:///Users/andrew/Code/andykais/ts-rpc/adapters/oak.ts:36:29

You may have discovered a bug in Deno. Please open an issue at: https://github.com/denoland/deno/issues/
```

<details>
<summary>source code</summary>
<pre>
import * as oak from 'jsr:@oak/oak'
import * as contracts from '../src/contracts.ts'
import * as adapter_base from './mod.ts'
import {ClientRealtimeEmitter, ApiController, ClientRequest} from '../server.ts'

type OakRouterContext = oak.RouterContext<string, Record<string | number, string>, Record<string, any>>
type OakRouterFunction = (ctx: OakRouterContext) => Promise<void>

class ServerSentEventsAdapter<Events> extends adapter_base.ServerSentEventsAdapter<Events> {
  #status_resolved: PromiseWithResolvers<void>
  #target: oak.ServerSentEventTarget

  constructor(target: oak.ServerSentEventTarget) {
    super()
    this.#target = target
    this.#status_resolved = Promise.withResolvers()
    target.addEventListener('close', e => {
      this.#status_resolved.resolve()
    })
  }

  get status() {
    return this.#status_resolved.promise
  }

  send(contract: contracts.EventContract) {
    const success = this.#target.dispatchMessage(JSON.stringify(contract))
    if (!success) {
      throw new Error(`Failed to dispatch message over server sent events adapter ${this.#target}`)
    }
  }
}

class ServerAdapter extends adapter_base.ServerAdapter {
  async handle_server_sent_events_request(ctx: OakRouterContext) {
    // TODO error out if x-rpc-connection-id is already present?
    const target = await ctx.sendEvents()
    const sse_adapter = new ServerSentEventsAdapter<any>(target)

    this.add_realtime_client(sse_adapter)

  }

  async handle_rpc_request(ctx: OakRouterContext) {
    const request_contract: contracts.RequestContract = await ctx.request.body.json()
    const connection_id = ctx.request.headers.get('x-rpc-connection-id')
    const rpc_controller = this.load_controller(request_contract.namespace, connection_id)
    const response_contract = await this.handle_request(rpc_controller, request_contract)
    ctx.response.body = response_contract
  }

  static adapt<C, E>(rpc_class: typeof ApiController<C, E, any>, context: C): OakRouterFunction {
    const adapter = new ServerAdapter(rpc_class, context)

    return async (ctx: OakRouterContext) => {
      if (ctx.request.headers.get('accept') === 'text/event-stream') {
        await adapter.handle_server_sent_events_request(ctx)
      } else {
        await adapter.handle_rpc_request(ctx)
      }
    }
  }
}

export const adapt = ServerAdapter.adapt
export * from '../server.ts'
</pre>
</details>

I can solve this issue by exporting `adapter_base` in this module. This is just a bit confusing for users to see this exported when using the library. Can someone confirm if this is an expected error?
```ts
export { adapter_base }
```

## additional information
the source code is here https://github.com/andykais/ts-rpc/blob/deno-to-node-experiment/adapters/oak.ts (and this is the repo at the point in time that this issue was created https://github.com/andykais/ts-rpc/tree/dcff52451eacc06328153c74926acfe2e072ac2c)

**Comment by andykais** [comment]
holy crap that was a fast turnaround! I do think this may still be busted based on my github action (which appears to have used 1.43.1) https://github.com/andykais/ts-rpc/actions/runs/8931583359/job/24533936758

**Comment by dsherret** [comment]
I've been wanting to ensure bugs of this kind of fixed asap because they're quite painful.

It will be fixed in `deno upgrade --canary` once https://github.com/denoland/deno/pull/23661 lands in the CLI and a full CI run occurs (and passes) on main.

**Comment by andykais** [comment]
👍 well thanks for the support. For now I can unblock myself with additional exports, Ill keep an eye on that pr though and close this issue out if my issue is fixed once that is released

**Comment by andykais** [comment]
just following up that my issue is solved here. Thanks!
