### ISSUE TITLE
Internal: Add "tests" to spec tests in addition to "steps"

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#23660]
Note: This is for Deno's internal testing infrastructure.

These would be defined similar to `steps`, but you could name them:

```jsonc
{
  "tests": {
    "does_something": {
      "args": "run main.ts",
      "output": "main.out"
    },
    "some_other_test": {
      "args": "check main.ts",
      "output": "main.out"
    }
  }
}
```

These would run with fresh deno_dirs and possibly run in parallel. Ideally there should be a way to filter them.

**Comment by satyarohith** [comment]
Implemented in https://github.com/denoland/deno/pull/23667
