### ISSUE TITLE
Fixed by #23425 — how to use req.signal to check that the response was delivered to the client?

### ISSUE THREAD

**Issue by leonbakadorov** [denoland/deno#23678]
How can you make sure that the response is guaranteed to be delivered to the client?

Previously I suggested something like this:

```js
// my idea
if (res.done) {
    // code
}
```

Now I guess it works somehow through req.onabort?

```js
// your implementation
if (!req.onabort) {
    // code
}
```

Explain how this should work, because I didn't find it in the API.

**Comment by leonbakadorov** [comment]
I get the feeling that req.onabort does not contribute at all to this task.

**Comment by mmastrac** [comment]
You can use the signal like so:

```
Deno.serve((req) => {
  req.signal.onabort = () => console.log("done");
  return new Response("ok");
});
```

It'll be triggered when the response has been fully delivered to the http layer.

**Comment by mmastrac** [comment]
It also works with a stream like so:

```
Deno.serve((req) => {
  req.signal.onabort = () => console.log("done");
  return new Response(
    new ReadableStream({
      start(c) {
        c.enqueue(new TextEncoder().encode('ok\n'));
      },
    }),
  );
});
```

**Comment by leonbakadorov** [comment]
[mmastrac](https://github.com/mmastrac),
And if the client’s Internet or device simply disconnects at the time of the request, in this case the connection will be disconnected and “done” will be displayed in the console?

**Comment by leonbakadorov** [comment]
Oh, you have a great example on your blog on Deno 1.43:

```js
Deno.serve((req, info) => {
 info.completed.then(() => {
 console.log("Response sent successfuly!");
 }).catch(() => {
 console.error("Failed sending the response.");
 });
 return new Response("Hello world");
});
```

I think this is what I was looking for, right?

**Comment by mmastrac** [comment]
Correct on both counts. The completed signal will also work.
