### ISSUE TITLE
LSP cannot get completion info when file has `using` or `await using` declaration

### ISSUE THREAD

**Issue by ben-laird** [denoland/deno#23688]
Version: Deno 1.43.1

Hello! I'm using the new explicit resource management proposals in tests, and the language server returns an error whenever a `using` or `await using` declaration is made.

Error from VSCode:

```
Unable to get completion info from TypeScript: unknown variant `using`, expected one of ``, `warning`, `keyword`, `script`, `module`, `class`, `local class`, `interface`, `type`, `enum`, `enum member`, `var`, `local var`, `function`, `local function`, `method`, `getter`, `setter`, `property`, `constructor`, `call`, `index`, `construct`, `parameter`, `type parameter`, `primitive type`, `label`, `alias`, `const`, `let`, `directory`, `external module name`, `JSX attribute`, `string`, `link`, `link name`, `link text` at line 1 column 438
```

Minimal example:

```ts
Deno.test("LSP cannot load completions with using declarations", () => {
  function makeResource() {
    return {
      execute() {
        console.log("Stuff happens...");
      },

      [Symbol.dispose]() {
        console.log("All done!");
      },
    };
  }

  using resource = makeResource();

  resource.execute();
});
```

Requesting completions from the LSP in the code above will silently fail and will only succeed when automatically called; for example, completion fails when typing "resource" inside the test function, but completions load properly for "resource." (ie when trying to access a property). Tests still pass as expected, this seems to only be an LSP issue.

EDIT: Possibly a duplicate of #22392

**Comment by dsherret** [comment]
Key point:

> Requesting completions from the LSP in the code above will silently fail and will only succeed when automatically called; for example, completion fails when typing "resource" inside the test function, but completions load properly for "resource."
