### ISSUE TITLE
Crash in deno_io due to dependency issue

### ISSUE THREAD

**Issue by rscarson** [denoland/deno#23692]
One of my users is reporting a crash in the deno_io extension since the update:

```
thread 'main' panicked at /Users/z/.cargo/registry/src/index.crates.io-6f17d22bba15001f/deno_core-0.278.0/runtime/jsruntime.rs:619:9:
Failed to initialize a JsRuntime: Uncaught SyntaxError: The requested module 'ext:core/ops' does not provide an export named 'op_set_raw'
    at ext:deno_io/12_io.js:8:10
```

Linking the downstream issues for tracking:

https://github.com/rscarson/rustyscript/issues/85

**Comment by lucacasonato** [comment]
You need to implement `op_set_raw` https://github.com/denoland/deno/blob/22d34f7012c48a25435b38c0c306085c614bbea7/runtime/ops/tty.rs#L88 yourself, it does not come from `deno_io`.

**Comment by rscarson** [comment]
> any details on how to "implement this yourself"? I'm confused why I can't use the implementation in `deno/rutime/ops/tty`? I just need node emulation to work 😢 

My implementation is in the files in this directory:

https://github.com/rscarson/rustyscript/blob/master/src%2Fext%2Fio%2Fmod.rs
