### ISSUE TITLE
npm:web-push not working

### ISSUE THREAD

**Issue by Octo8080X** [denoland/deno#23693]
Version: Deno 1.43.1

[web-push](https://www.npmjs.com/package/web-push) is not work Deno.

AES-GCM decryption in Chrome fails and causes an error.
This prevents us from receiving messages sent from the server.

We have prepared a verified repository for your reference.

https://github.com/Octo8080X/verification-web-push-on-Deno

**Comment by Octo8080X** [comment]
Deno 1.44.1 was used to check again, but the situation remained the same and failed.

**Comment by ktn1234** [comment]
I am seeing this same issue too. I have a Supabase Edge Function that runs on the Deno runtime that uses web-push to my subscribed devices for notifications. 

When my devices receive a push notifications I get the `AES-GCM decryption failed` log in the `Message Decryption Failure Log` section when using `brave://gcm-internals/` to debug

**Comment by ktn1234** [comment]
I am seeing this same issue too. I have a Supabase Edge Function that runs on the Deno runtime that uses web-push to my subscribed devices for notifications. 

When my devices receive push notifications I receive the `AES-GCM decryption failed` log in the `Message Decryption Failure Log` section when using `brave://gcm-internals/` to debug

**Comment by cotyhamilton** [comment]
It's almost useless, but if your payload is undefined you can at least receive the event

**Comment by Razikus** [comment]
Same issue

**Comment by negrel** [comment]
Hello guys, I have no solution for the web-push package but i've built a deno compatible package,  checkout https://jsr.io/@negrel/webpush

**Comment by marvinhagemeister** [comment]
Just tried out the original reproduction and it works in Deno 1.45.2. I don't get the described permission error anymore 🎉

**Comment by cotyhamilton** [comment]
It doesn't seem to be resolved. I have my own repo I'm testing with, but also using the repo above I'm getting the same decryption errors

<img width="960" alt="Screenshot 2024-07-15 at 11 45 14 AM" src="https://github.com/user-attachments/assets/d249952a-fc70-45eb-a735-166f9b71f651">

```sh
deno 1.45.2 (release, aarch64-apple-darwin)
v8 12.7.224.12
typescript 5.5.2
```

**Comment by marvinhagemeister** [comment]
@cotyhamilton How can this be reproduced. I'm not sure how to get to that view that is visible in the screenshot. With the reproduction posted in the original message I see no errors in chrome's console.

**Comment by marvinhagemeister** [comment]
I stand corrected. I mistakenly only checked the logs in Chrome DevTools and didn't look at `chrome://gcm-internals/`

**Comment by littledivy** [comment]
We did a rewrite of the crypto code recently. This seems to be working now.
```
deno serve --port 1234 --unstable -A ./main_deno.ts
```

![image](https://github.com/user-attachments/assets/e79e8aa4-cd56-4038-a0b0-c18ad8ec8118)

**Comment by jrmann100** [comment]
@littledivy, I'm pretty sure this is still unresolved - you need to test on `localhost` as `0.0.0.0` is not considered a secure context. Were you receiving notifications?

**Comment by jrmann100** [comment]
<img width="716" alt="Screenshot 2024-08-27 at 8 46 43 PM" src="https://github.com/user-attachments/assets/014bc590-322e-4a7e-90ec-ceaa756e2b6c">
<img width="720" alt="Screenshot 2024-08-27 at 8 47 34 PM" src="https://github.com/user-attachments/assets/692efe64-3127-4016-8a07-b9c46e06a15f">

**Comment by littledivy** [comment]
Merged a fix and the push messages are now being deliverer and decrypted. 

Try it out with `deno upgrade --canary` - it will be available in an hour or two.

**Comment by jrmann100** [comment]
Amazing, thank you! Will hope to see this in production soon.
