### ISSUE TITLE
undefined symbol: node_module_register

### ISSUE THREAD

**Issue by terrablue** [denoland/deno#23700]
### What version of Deno is running?

1.42.2

### What platform is your computer?

Linux 6.8.9-arch1-1 x86_64 unknown

### What steps can reproduce the bug?

1. Put `import gi from "node-gtk";` into a JS file `app.js`
2. Run `deno run --allow-all app.js`

### What is the expected behavior?

Deno should run without an error.

### What do you see instead?

`deno: symbol lookup error: /home/blue/test-native/node_modules/.deno/node-gtk@0.14.0/node_modules/node-gtk/lib/binding/node-v108-linux-x64/node_gtk.node: undefined symbol: node_module_register`

**Comment by ralyodio** [comment]
I'm also seeing this issue.

**Comment by devsnek** [comment]
`node-gtk` is using APIs which are not supported as part of the Node-API: https://nodejs.org/api/n-api.html#implications-of-abi-stability

**Comment by bricefriha** [comment]
You could try your luck with this Deno port of GTK https://github.com/ahgilak/deno_gi

**Comment by astralstriker** [comment]
having the same issue with canvas (node-canvas) package.

**Comment by marvinhagemeister** [comment]
@astralstriker Can you share the steps to reproduce the error?
