### ISSUE TITLE
[Question] Is the incompatibility of allow-net between flags and options intentionally?

### ISSUE THREAD

**Issue by sasurau4** [denoland/deno#2371]
## Overview

Is the incompatibility of allow-net between flags and options intentionally?

## Details
I found the incompatiblity behavior of `--allow-net`.

When using `--allow-net` as flag, we need no additional permission.

```
deno run --allow-net https://deno.land/std/examples/echo_server.ts
```

The other hand, using `--allow-net` as options, we need additional permission about "listen" and "accept".

```
deno run --allow-net=0.0.0.0 https://deno.land/std/examples/echo_server.ts
⚠️  Deno requests network access to "listen". Grant? [a/y/n/d (a = allow always, y = allow once, n = deny once, d = deny always)]
⚠️  Deno requests network access to "accept". Grant? [a/y/n/d (a = allow always, y = allow once, n = deny once, d = deny always)]
```

Is the behavior is intentionally?
Does whitelist permission of `--allow-net` affect only `fetch`?

## environment
deno: 0.5.0
v8: 7.6.53
typescript: 3.4.1

**Comment by bartlomieju** [comment]
Definitely looks like a bug. This line should check address instead of "listen"?
https://github.com/denoland/deno/blob/e02d8bcf18f8170a41439f4ffa416d26c5846b6e/cli/ops.rs#L1625
Same applies to "accept".

CC @afinch7

**Comment by bartlomieju** [comment]
I'm working on a fix
