### ISSUE TITLE
crypto std

### ISSUE THREAD

**Issue by cllty** [denoland/deno#2372]
Is there a crypto std for Deno? Is there one in the roadmap?

**Comment by Smithx10** [comment]
I'm curious what Deno's approach to crypto is going to be.  Perhaps this should be reopened?  Or will crypto be outside std?

**Comment by kitsonk** [comment]
@Smithx10 see #1891

**Comment by 89z** [comment]
https://github.com/denoland/deno/issues/1891

https://github.com/denoland/deno/issues/2372
https://github.com/denoland/deno/issues/6712
https://github.com/denoland/deno/issues/8006
https://github.com/denoland/deno_std/issues/48
