### ISSUE TITLE
npx fails to resolve 'esbuild' after updating to Deno 1.43.0

### ISSUE THREAD

**Issue by gazerro** [denoland/deno#23724]
Version: Deno 1.43.0

After updating to Deno 1.43.0, I am experiencing an issue where the `npx` command fails to resolve the 'esbuild' binary, which was working fine in previous versions up to Deno 1.42.4. This issue occurs when I attempt to run the `npx esbuild ...` task.

How to reproduce:

1. `mkdir test-deno`
2. `cd test-deno`
3. `npm init`
4. `npm install esbuild`
5. `deno init`
6. Add  the task `"minify": "npx esbuild --version"`
7. `deno upgrade --version 1.42.4`
8. `deno task minify`, it prints: **0.21.0**
9. `deno upgrade --version 1.43.0`
10. `deno task minify`, it prints: **npx: could not resolve command 'esbuild'**

**Comment by bartlomieju** [comment]
CC @dsherret please take a look
