### ISSUE TITLE
deno test --exclude

### ISSUE THREAD

**Issue by alexgleason** [denoland/deno#23731]
I would like to exclude some files with the command line, so I can skip certain tests in my CI.

It's possible to exclude certain tests with deno.json by adding a `test.exclude` property, but this applies to all invocations of `deno test`, even when you specify an excluded file directly by filename. So, I have to delete it from deno.json when I want to run those tests manually.

I couldn't find any `--exclude` option in deno test, but it seems like it should exist.

EDIT: It is also possible to set `{ ignore: true }` in the test options, and even `{ ignore: Deno.env.get('CI') === 'true' }`, eg:

```ts
Deno.test('NDatabase.query with postgres fts', { ignore: !Deno.env.get('DATABASE_URL') }, async (t) => {
```

This is a little better than using `text.exclude` in deno.json, but it only works on individual tests, not entire files. So it becomes a maintenance problem when you have a lot of tests.

**Comment by bartlomieju** [comment]
Seems reasonable. PRs are welcome!

**Comment by alexgleason** [comment]
Confirmed `--ignore` solves my problem. I just couldn't find it. Thank you for figuring this out @Hasan-Alrimawi!
