### ISSUE TITLE
[Bug] Segmentation fault with @poolifier/poolifier-web-worker Deno example

### ISSUE THREAD

**Issue by jerome-benoit** [denoland/deno#23758]
Version: Deno 1.43.2

The code in https://github.com/poolifier/poolifier-web-worker/tree/master/examples/deno/typescript segfault with Deno version  1.43.2: 

`[1]    30111 segmentation fault  deno run -A pool.ts`

All UTs instantiating a pool are also triggering a segfault. 

No backtrace is generated. No clue on what is exactly going on yet.  

Deno 1.43.1 worked fine.

**Comment by bartlomieju** [comment]
I can't reproduce it after cloning the repo. Which OS are you observing the problem on?

**Comment by jerome-benoit** [comment]
GNU/Linux and OS X Deno from Homebrew. I need now to test with the official Deno binaries to ensure the issue is with the Homebrew binaries.

**Comment by bartlomieju** [comment]
Please do and let me know if the problem persists.

**Comment by jerome-benoit** [comment]
Homebrew Deno build issue. Issue will to be created on Homebrew.

**Comment by bartlomieju** [comment]
Thanks!

**Comment by jerome-benoit** [comment]
Homebrew issue: https://github.com/Homebrew/homebrew-core/issues/171317
