### ISSUE TITLE
Homebrew segementation fault when creating Fresh project

### ISSUE THREAD

**Issue by gtothesquare** [denoland/deno#23766]
New to deno here and wanted to try fresh out. 

When running the project creator script I get a segmentation fault error at the end. (see image below)

```sh
deno run -A -r https://fresh.deno.dev
```

The folder is created with the project name and has partial content:

```
components 
islands    
routes    
 static
```

The script will work in another mac with Sonoma `14.3.1` (not sure if it is related)

Any ideas?

## System info

Deno version

```
deno 1.43.2 (release, aarch64-apple-darwin)
v8 12.4.254.12
typescript 5.4.5
```

Mac OS `14.4.1`
Deno installed via `brew`

## Error screen grab
<img width="670" alt="image" src="https://github.com/denoland/fresh/assets/370567/2563f32c-9df9-4f37-9b1f-157f7057ee9b">

**Comment by brendonboshell** [comment]
There's an equivalent issue on the homebrew repo, just an FYI https://github.com/Homebrew/homebrew-core/issues/171317

**Comment by gtothesquare** [comment]
Wow thanks for the quick update. Yeah using the  `install.sh` fixes the issue.  So, is it better to just do it via the official install script?

Should I close this given that is a homebrew issue ? 

```
curl -fsSL https://deno.land/install.sh | sh
```

**Comment by mmastrac** [comment]
Collecting all of these under #23763
