### ISSUE TITLE
Error getting `process.uptime` when called without bound `this`

### ISSUE THREAD

**Issue by beetcb** [denoland/deno#23761]
Version: Deno 1.42.4
Issue: When using npm specifiers, the bundled process.uptime reference appears to be lost.
To reproduce: Run deno repl and compare with node.
<img width="666" alt="image" src="https://github.com/denoland/deno/assets/63141491/e488c26e-b55d-47b3-afff-8040b9cd1fbb">

Please take a look at this issue, thank you.

**Comment by beetcb** [comment]
Here is the bundled code:

<img width="315" alt="image" src="https://github.com/denoland/deno/assets/63141491/850ea93b-5875-4404-97f3-d54b7645a07a">

<img width="386" alt="image" src="https://github.com/denoland/deno/assets/63141491/5d27e8bf-4cb2-4498-baaa-d10534889764">

**Comment by satyarohith** [comment]
> Thank you for fixing that issue.
> 
> Just curious, how does Node.js work without this? @satyarohith

Even though the API exposed is the same, the implementation is different in Node.js and Deno.
