### ISSUE TITLE
[Rust 1.78/Homebrew] Deno 1.43.2 on MacOS crashes: segfaults, "already borrowed: BorrowMutError"

### ISSUE THREAD

**Issue by nleck** [denoland/deno#23763]
Version: Deno 1.43.2
============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos aarch64
Version: 1.43.2
Args: ["deno", "run", "--v8-flags=--max-old-space-size=8192", "--allow-read", "--allow-write", "--allow-net", "src/Learn.ts", "--timeout=45", "--populationSize=20", "--elitism=3", "--log=1", "--trainingSampleRate=0.001", "--verbose=true"]

thread 'main' panicked at /private/tmp/deno-20240509-7177-1nc96g/deno_core/serde_v8/ser.rs:267:34:
already borrowed: BorrowMutError
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::cell::panic_already_borrowed
   3: <serde_v8::ser::StructSerializers as serde::ser::SerializeStruct>::end
   4: <serde_v8::magic::buffer::ToJsBuffer as serde::ser::Serialize>::serialize
   5: core::ops::function::FnOnce::call_once
   6: deno_core::runtime::jsruntime::JsRuntime::do_js_event_loop_tick_realm
   7: deno_core::runtime::jsruntime::JsRuntime::poll_event_loop
   8: deno_core::runtime::jsruntime::JsRuntime::run_event_loop::{{closure}}
   9: deno_runtime::worker::MainWorker::run_event_loop::{{closure}}
  10: deno::worker::CliMainWorker::evaluate_module_possibly_with_npm::{{closure}}
  11: deno::worker::CliMainWorker::execute_main_module_possibly_with_npm::{{closure}}
  12: deno::worker::CliMainWorker::run::{{closure}}
  13: deno::tools::run::run_script::{{closure}}
  14: deno::spawn_subcommand::{{closure}}
  15: <deno_unsync::task::MaskFutureAsSend<F> as core::future::future::Future>::poll
  16: tokio::runtime::task::raw::poll
  17: deno::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
================ Clean up START ================

**Comment by nleck** [comment]
Downgrading fixed the problem. 
curl -fsSL https://deno.land/install.sh | sh -s v1.42.0

**Comment by bebraw** [comment]
Same. If you execute `deno task start` against https://github.com/survivejs/website-v3, the project crashes in a similar way. Here's the trace:

```
Task start deno run -A --unstable --no-check https://deno.land/x/gustwind@v0.77.4/gustwind-cli/mod.ts -d -p 3000
⚠️  The `--unstable` flag is deprecated and will be removed in Deno 2.0. Use granular `--unstable-*` flags instead.
Learn more at: https://docs.deno.com/runtime/manual/tools/unstable_flags
Starting development server

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos x86_64
Version: 1.43.2
Args: ["/usr/local/bin/deno", "run", "-A", "--unstable", "--no-check", "https://deno.land/x/gustwind@v0.77.4/gustwind-cli/mod.ts", "-d", "-p", "3000"]

thread 'main' panicked at /private/tmp/deno-20240509-7188-obss62/deno_core/serde_v8/de.rs:628:53:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0:        0x10479f2ed - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he776435ce16d6b78
   1:        0x1037527cb - core::fmt::write::h2b9e9c9b9d578e83
   2:        0x10478f598 - std::io::Write::write_fmt::had83bf0751478941
   3:        0x10479f0f1 - std::sys_common::backtrace::print::h913402da03d152a3
   4:        0x104786660 - std::panicking::default_hook::{{closure}}::h8fcea87a808389ab
   5:        0x1047863d5 - std::panicking::default_hook::he41a4726e0362119
   6:        0x1036136bc - deno::setup_panic_hook::{{closure}}::h5c1fcd1506d370d3
   7:        0x1047873e0 - std::panicking::rust_panic_with_hook::hfa1925e6750edf2f
   8:        0x10479f5fc - std::panicking::begin_panic_handler::{{closure}}::h80d66d31b1376759
   9:        0x10479f589 - std::sys_common::backtrace::__rust_end_short_backtrace::h7584da9a2fe80106
  10:        0x104786966 - _rust_begin_unwind
  11:        0x105fbf2c5 - core::panicking::panic_fmt::hf8bb0516a37cf723
  12:        0x105fbf3ce - core::panicking::panic::hefc6f8942d8c556c
  13:        0x105fbf7a8 - core::option::unwrap_failed::h5ce22982ddb6c26b
  14:        0x103e1b742 - serde::de::SeqAccess::next_element::h022e05636cbafbd9
  15:        0x103f6af33 - serde_v8::de::from_v8::h7d0d37910e34ec3e
  16:        0x103f741f0 - deno_runtime::ops::process::op_spawn_child::op_spawn_child::v8_fn_ptr::hdf9b7af7281414cc
```

It worked without problems in the previous version (1.42.1).

**Comment by bebraw** [comment]
This might be related to #23753 and you can find more related issues there.

**Comment by brc-dd** [comment]
I'm seeing this only with homebrew version of deno. The latest official binary works fine.

Related issues - https://github.com/Homebrew/homebrew-core/issues/171317, https://github.com/denoland/deno/issues/23758

**Comment by 0f-0b** [comment]
Running this program with `RUST_BACKTRACE=1 cargo +1.78.0 run -r` results in the same panic message.

`Cargo.toml`:

```toml
[package]
name = "repro"
edition = "2021"

[dependencies]
deno_core = "0.279.0"

[profile.release]
lto = true
```

`src/main.rs`:

```rust
use deno_core::{op2, JsRuntime, RuntimeOptions, ToJsBuffer};

#[op2]
#[serde]
fn op_test() -> ToJsBuffer {
    "foo".to_owned().into_bytes().into()
}

deno_core::extension!(
    test,
    ops = [op_test],
    esm_entry_point = "ext:test",
    esm = ["ext:test" = {
        source = r#"
            import { op_test } from "ext:core/ops";
            op_test();
        "#
    }],
);

fn main() {
    JsRuntime::new(RuntimeOptions {
        extensions: vec![test::init_ops_and_esm()],
        ..Default::default()
    });
}
```

**Comment by mmastrac** [comment]
Fixing upstream in deno_core: https://github.com/denoland/deno_core/pull/735
