### ISSUE TITLE
Ref-count of an object 

### ISSUE THREAD

**Issue by kakashi-69-xd** [denoland/deno#23772]
I need to obtain the reference count of an object..
I'm trying to make a callback function invoke on ref-count change..

I just need to know where the javascript objects are stored and the memory layout of them..

* I'm using rust to achieve memory manipulation and pointer-math..

**Comment by marvinhagemeister** [comment]
I'm afraid that's not possible with a dynamic JIT engine like v8. Closing as this isn't something we have control over in Deno, given that use v8 internally.
