### ISSUE TITLE
Can't ignore `no-slow-types` diagnostics

### ISSUE THREAD

**Issue by timharek** [denoland/deno#23788]
I'm trying to publish to JSR and I have issue with [Zod](https://zod.dev) and slow-types, but I want to not have my lint and type-checking fail all the time. I can only ignore the `no-slow-types` with `deno publish --allow-slow-types`, not on a file- or line-level.

### Lint Name

`no-slow-types`

### Code Snippet

```ts
// deno-lint-ignore no-slow-types
export const Example = z.object({
  url: z.string().url(),
});
```

### Expected Result

No error

### Actual Result

```error
error[ban-unknown-rule-code]: Unknown rule for code "no-slow-types"
  --> /some/path/file.ts:18:1
   |
18 | // deno-lint-ignore no-slow-types
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  docs: https://lint.deno.land/rules/ban-unknown-rule-code


error[no-slow-types]: missing explicit type in the public API
 --> /some/path/file.ts:3:7
  |
3 | export const Example = z.object({
  |       ^^^^^^^^^^ this symbol is missing an explicit type
  = hint: add an explicit type annotation to the symbol

  info: all symbols in the public API must have an explicit type
  docs: https://jsr.io/go/slow-type-missing-explicit-type
```

### Version

```
deno 1.43.3 (release, aarch64-apple-darwin)
v8 12.4.254.13
typescript 5.4.5
```

**Comment by dsherret** [comment]
This is by design. See #22683

Duplicates #22683

**Comment by timharek** [comment]
Alright, thanks!

Maybe update the docs with this somewhere, on https://lint.deno.land/ and https://jsr.io/docs/about-slow-types?

**Comment by dsherret** [comment]
I opened https://github.com/jsr-io/jsr/issues/505
