### ISSUE TITLE
I have a bug

### ISSUE THREAD

**Issue by bluezip** [denoland/deno#23781]
============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: windows x86_64
Version: 1.43.3
Args: ["C:\\Users\\serin\\.deno\\bin\\deno.exe", "run", "-A", "--watch=static/,routes/", "dev.ts"]

thread '<unnamed>' panicked at C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\v8-0.91.1\src\handle.rs:513:32:
attempt to access disposed Isolate
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

================================================================================
I thank bug from
import { openKv } from "npm:@deno/kv";

export const kv = await Deno.openKv(".tmp/kv/kv.sqlite3");

**Comment by marvinhagemeister** [comment]
I tried running the example snippet provided, but didn't see an error. Can you share the steps to reproduce it?

**Comment by marvinhagemeister** [comment]
Closing as we haven't heard back. Happy to re-open if the issue still exists.
