### ISSUE TITLE
Import private module from npm registiry

### ISSUE THREAD

**Issue by Horki** [denoland/deno#23800]
What is a proper way to include private module that I own on private npm registry?

Is there a way to integrate my npm account with deno? I couldn't find in documentation how to do that

package.json
```
{
  "name": "deno_run",
  "version": "1.0.0",
  "description": "using private npm reg",
  "scripts": {
    "dev": "deno run --allow-env --allow-sys main.ts"
  },
  "dependencies": {
    "@ivan/my-private-module": "42.0.1",
    "uuid": "9.0.1"
  }
}
```

I receive response
`npm package '@ivan/my-private-module' does not exist.`

**Comment by bartlomieju** [comment]
Are you using `.npmrc` to define your registry configuration?

**Comment by Horki** [comment]
@bartlomieju 
Hi, I have copied `.npmrc` with registry info into root of project, and still nothing

**Comment by bartlomieju** [comment]
@Horki `.npmrc` is not yet supported, but we are working on it in https://github.com/denoland/deno/pull/23560.

Please follow https://github.com/denoland/deno/issues/16105 for updates.

**Comment by Horki** [comment]
@bartlomieju Hi, is there any way to include npm private modules? ... and how?

**Comment by bartlomieju** [comment]
@Horki not currently no, please follow the linked issue and PR above. Once they land it will be supported just like with npm - using `.npmrc` file.

**Comment by jtibble** [comment]
> @bartlomieju Hi, I have copied `.npmrc` with registry info into root of project, and still nothing EDIT: I have also tried, with same effect NPM_CONFIG_REGISTRY=https://registry.npmjs.org/:_authToken=npm_myPrivateToken deno run main.ts

This now works correctly in the canary builds @Horki !

**Comment by Horki** [comment]
Hi @jtibble I have tried with `deno 1.43.6+a947c6f` built, and it is not working

**Comment by jtibble** [comment]
> Hi @jtibble I have tried with `deno 1.43.6+a947c6f` built, and it is not working

Make sure you run like `DENO_FUTURE=1 deno run main.ts` to enable the .npmrc feature

**Comment by bartlomieju** [comment]
That's correct. `DENO_FUTURE=1` is required to enable .npmrc support.
