### ISSUE TITLE
LSP incorrectly formatted JSDoc in code completions

### ISSUE THREAD

**Issue by Hajime-san** [denoland/deno#23820]
Version: Deno 1.43.3

## reproduce

To type `add` on any other `add.ts` typescript files.

- add.ts
```ts
/**
 *
 * @example
 * ```ts
 * const result = add(1, 2);
 * console.log(result); // 3
 * ```
 *
 * @param {number} a - The first number
 * @param {number} b - The second number
 */
export function add(a: number, b: number) {
  return a + b;
}
```

## actual behaviour

<img width="800" alt="2024-05-15-actual" src="https://github.com/denoland/deno/assets/41257923/824bfbac-2d81-41e4-8738-eb81e2000246">

### Note

But it seems to be ok the `MarkupContent` when I `hover` over it.

## expected behaviour

```bash
% node --version
v20.12.0

% cat package.json    
{
  "name": "test",
  "type": "module",
  "devDependencies": {
    "@types/node": "20.11.17",
    "typescript": "5.3.3"
  }
}
```

<img width="800" alt="2024-05-15-02-expected" src="https://github.com/denoland/deno/assets/41257923/ea954b78-28e0-4acc-9597-1a809d81110b">

## Tracking issue

- [ ] Lacks the tail newline of [Fenced Code Block](https://www.markdownguide.org/extended-syntax/#fenced-code-blocks) when processing JSDoc text.
       https://github.com/denoland/deno/pull/23822
- [ ] And there is also a difference in the type `a` and `b` of `@param` is surrounded by code block about the expected behaviour screenshot, if you look carefully.

**Comment by lucacasonato** [comment]
This is fixed now.
