### ISSUE TITLE
`Deno.serve`: If there is an error processing the response body the server crashes.

### ISSUE THREAD

**Issue by maxmcd** [denoland/deno#23849]
Version: Deno 1.43.3

Server:
```ts
Deno.serve(
  {
    port: 8080,
    onError: (e) => {
      Response.json(e);
    },
  },
  (req) => {
    const body = new ReadableStream({
      start(controller) {
        setTimeout(() => {
          // Intentionally crash the server
          controller.enqueue(1);
        }, 10);
      },
      cancel() {},
    });
    return new Response(body);
  }
);
```

Run it (send a request to the running server in another shell): 
```
$ deno run --allow-net ./crash.ts
Listening on http://localhost:8080/
error: Uncaught TypeError: expected typed ArrayBufferView
          controller.enqueue(1);
                     ^
    at readableStreamWriteChunkFn (ext:deno_web/06_streams.js:794:15)
    at Object.chunkSteps (ext:deno_web/06_streams.js:836:9)
    at readableStreamFulfillReadRequest (ext:deno_web/06_streams.js:2589:17)
    at readableStreamDefaultControllerEnqueue (ext:deno_web/06_streams.js:1764:5)
    at ReadableStreamDefaultController.enqueue (ext:deno_web/06_streams.js:6059:5)
    at file:///Users/maxm/go/src/github.com/val-town/deno-http-worker/src/test/crash.ts:13:22
    at eventLoopTick (ext:core/01_core.js:203:13)
```

Is there a way to catch errors like this generally? I can understand why a partially processed body can't really trigger the onError handler, but not having recourse to catch and handle the error makes things tricky.

**Comment by bartlomieju** [comment]
You can use [`unhandledrejection`](https://developer.mozilla.org/en-US/docs/Web/API/Window/unhandledrejection_event) or [`error`](https://developer.mozilla.org/en-US/docs/Web/API/Window/error_event) events to catch these.

**Comment by maxmcd** [comment]
got it working with `onerror`. `unhandledrejection` alone seems to do nothing.
```
// added to bottom of previous file
globalThis.addEventListener("unhandledrejection", (e) => {
  console.log("unhandled rejection at:", e.promise, "reason:", e.reason);
  e.preventDefault();
});
```
Running it behaves the same as before.

With `onerror` it works:
```
globalThis.onerror = (e) => {
  console.log("onerror:", e);
  e.preventDefault();
};
```
Although no way to connect the error to a specific request, but definitely nice to be saved from the crash.

**Comment by maxmcd** [comment]
I will close this for now as my question has been answered. Would be nice if there was something on the Deno.serve interface to handle this, feel free to re-open if that is desired and this is a worthwhile place to track that.
