### ISSUE TITLE
Diagnostic-languageserver stopped working in Deno >= 1.43

### ISSUE THREAD

**Issue by akhilman** [denoland/deno#23889]
### Discussed in https://github.com/denoland/deno/discussions/23886

[Diagnostic-languageserver](https://github.com/iamcco/diagnostic-languageserver) stopped working in Deno >= 1.43.
I have no errors, no tracebacks, it just shuts down gracefully after a second and first linter's warning shown in the editor. Everything works fine with Deno 1.42.2 and older.

I ran bisect and found the exact commit that brakes the diagnostic-languageserver. It is c0f40ed81a1c932f804ba62e635249cd43c31273.

Diagnostic-languageserver is the LSP server built on top of Microsoft's vscode-languageserver library.

I would be happy to help solve this issue if I have instructions on what to do.

**Comment by akhilman** [comment]
The language server periodically sends the `0` signal to the editor via [this `kill` function](https://github.com/denoland/deno/blob/a2dbcf9e0aa1f70056ccc6ecdd4c813d30af768c/ext/node/polyfills/process.ts#L280). In 04c6785 everything works fine, but in c0f40ed this function throws an error with the value `-22`.
https://github.com/denoland/deno/blob/a2dbcf9e0aa1f70056ccc6ecdd4c813d30af768c/ext/node/polyfills/process.ts#L298 ,

**Comment by akhilman** [comment]
Here we go! 
In 04c6785 there was a [special treatment](https://github.com/denoland/deno/blob/50223c5c532332f4a296b12b027f85429f529690/ext/node/polyfills/process.ts#L259) for signal 0, but in c0f40ed [it has been removed](https://github.com/denoland/deno/blob/c0f40ed81a1c932f804ba62e635249cd43c31273/ext/node/polyfills/process.ts#L260). Also, signal 0 is not listed in [constants](https://github.com/denoland/deno/blob/a2dbcf9e0aa1f70056ccc6ecdd4c813d30af768c/ext/node/polyfills/internal_binding/constants.ts#L426). 
So `maybeSignal` becomes `undefined` and function returns error.
https://github.com/denoland/deno/blob/c0f40ed81a1c932f804ba62e635249cd43c31273/ext/node/polyfills/process.ts#L266

**Comment by sigmaSd** [comment]
I have sent a pr already for this https://github.com/denoland/deno/pull/23473

**Comment by akhilman** [comment]
> I have sent a pr already for this #23473

With this PR the language server works as expected.
Thank you.

**Comment by dsherret** [comment]
Thanks @sigmaSd. Merged. Will be in the next release this week.
