### ISSUE TITLE
Deno v1.43.4 on Windows: WinGet installation or upgrade fails

### ISSUE THREAD

**Issue by noseratio** [denoland/deno#23885]
Version: Deno v1.43.5

```text
winget install denoLand.Deno --force
```

Or:

```text
winget upgrade denoLand.Deno
```

Fails:

```text
An unexpected error occurred while executing the command:
Download request status is not success.
0x80190194 : Not found (404).
```

**Comment by dsherret** [comment]
Is the install command supposed to be `winget install deno`? https://docs.deno.com/runtime/manual/getting_started/installation

**Comment by noseratio** [comment]
@dsherret both refer to the same thing:

<img width="419" alt="image" src="https://github.com/denoland/deno/assets/4774875/5734587b-c580-4272-b3d5-d55f90b3a1ff">

I've also just tried it under [Windows Sandbox](https://learn.microsoft.com/en-us/windows/package-manager/winget/#install-winget-on-windows-sandbox), with the same results.

**Comment by rfulwell** [comment]
This seems to be a more general problem, perhaps at the Windows level. I am seeing this running a simple upgrade on Debian under WSL2:
```
> deno upgrade                                                                                                                      ░▒▓ ✔ ▓▒░
Looking up latest version
Found latest version 1.43.5
Downloading https://github.com/denoland/deno/releases/download/v1.43.5/deno-x86_64-unknown-linux-gnu.zip
error: Failed downloading https://github.com/denoland/deno/releases/download/v1.43.5/deno-x86_64-unknown-linux-gnu.zip. The version you requested may not have been built for the current architecture.

Caused by:
    0: request or response body error: error reading a body from connection: cannot decrypt peer's message
    1: error reading a body from connection: cannot decrypt peer's message
    2: cannot decrypt peer's message
> cat /etc/os-release                                                                                                             ░▒▓ 1 ✘ ▓▒░
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
```

**Comment by dsherret** [comment]
@rfulwell could you open a separate issue for that one? Not sure why it says "cannot decrypt peer's message", but for me it works fine in WSL. You may want to try manually upgrading Deno via the install script (https://docs.deno.com/runtime/manual)

**Comment by rfulwell** [comment]
> @rfulwell could you open a separate issue for that one? Not sure why it says "cannot decrypt peer's message", but for me it works fine in WSL. You may want to try manually upgrading Deno via the install script (https://docs.deno.com/runtime/manual)

Well, I changed nothing and now the usual `deno upgrade` is working fine for me.

**Comment by dsherret** [comment]
It looks like Winget is failing downloading its manifest for 1.43.4:

```
2024-05-19 17:17:58.967 [REPO] Downloading manifest
2024-05-19 17:17:58.967 [CORE] WinINet downloading from url: https://cdn.winget.microsoft.com/cache/manifests/d/DenoLand/Deno/1.43.4/4044
2024-05-19 17:17:59.109 [CORE] Download request failed. Returned status: 404
```

In 1.43.3 it works fine:

```
2024-05-19 17:18:10.034 [REPO] Downloading manifest
2024-05-19 17:18:10.034 [CORE] WinINet downloading from url: https://cdn.winget.microsoft.com/cache/manifests/d/DenoLand/Deno/1.43.3/890f
2024-05-19 17:18:10.046 [CORE] Download hash: 31ed02d22db26556f8b3c1da19b01deebe374f556973f1758dbb7d5abd6de0d5
2024-05-19 17:18:10.046 [CORE] Download completed.
```

This seems to be an issue with winget's system.

**Comment by dsherret** [comment]
@rfulwell might have been a transient error (ex. github not reachable for a bit)

**Comment by lucacasonato** [comment]
is this resolved?

**Comment by noseratio** [comment]
Back on track! Whoever fixed it, thanks folks! ❤️

<img width="749" alt="image" src="https://github.com/denoland/deno/assets/4774875/971106a0-87c2-40e6-9859-15634d5a3117">
