### ISSUE TITLE
LSP bug: starting with 1.43.4 deno doesn't load types from drizzle-orm correctly

### ISSUE THREAD

**Issue by guy-borderless** [denoland/deno#23895]
Version: Deno 1.43.4 & 1.43.5
with 1.43.4 deno stopped inferring drizzle-orm's types correctly
![1716144771](https://github.com/denoland/deno/assets/100129659/f4b433ad-d69d-4607-abe0-796d00b6349f)
![1716144715](https://github.com/denoland/deno/assets/100129659/c9963051-5841-4de2-a749-74d411a9fb9a)

[here is an example repo](https://github.com/guy-borderless/deno-drizzle-lsp-bug)

**Comment by bombillazo** [comment]
This is happening to us as well with when importing `npm:knex-schema-inspector@3.1.0`
