### ISSUE TITLE
How does typescript run on deno? 

### ISSUE THREAD

**Issue by catastrop** [denoland/deno#2389]

**Comment by kitsonk** [comment]
That is a broad question.

The [Deno manual](https://deno.land/manual.html) gives a general high level overview.  Reviewing the source code gives the real detail.

At a very high level, the Deno binary includes a bundle of the TypeScript compiler code, along with a lightweight wrapper which runs in a web worker and receives requests to transpile modules.  The Deno privileged environment coordinates what modules need to be transpiled and caches the result of those modules.  The transpiled modules then are injected into the the runtime of Deno to be executed.

**Comment by J2P** [comment]
https://deno.land/style_guide.html#usetypescript
Please refer to this document.
