### ISSUE TITLE
`URL.parse()` is missing from `lib.dom.d.ts`

### ISSUE THREAD

**Issue by nayeemrmn** [denoland/deno#23891]
Version: Deno 1.43.5

This affects when you have `dom` explicitly in your libs, or if you're using a JSX import source which includes dom types. You'll get a type checking error for using `URL.parse()`.

Refs:
- #23318.
- https://github.com/denoland/vscode_deno/issues/1116.

cc @petamoriken

**Comment by petamoriken** [comment]
[microsoft/TypeScript-DOM-lib-generator](https://github.com/microsoft/TypeScript-DOM-lib-generator) (`lib.dom.d.ts`) will automatically add the types when [browser-compat-data](https://github.com/mdn/browser-compat-data) confirms that two or more browsers have implemented them. I believe we will have to wait for `URL.parse` to become available in browsers other than Firefox.

**Comment by nayeemrmn** [comment]
There is plenty precedent for us updating this [file](https://github.com/iuioiua/deno/blob/main/cli/tsc/dts/lib.dom.d.ts) in advance of the upstream, e.g. #20244.

**Comment by petamoriken** [comment]
I get it, I'll do it.
