### ISSUE TITLE
V8 code cache: node_modules cache doesn't work on Lambda

### ISSUE THREAD

**Issue by igorzi** [denoland/deno#23904]
For node_modules we use timestamps instead of hashes, and on Lambda fs the timestamp resolution is seconds (not milliseconds). If the docker image has time resolution of milliseconds that will always cause cache misses.

**Comment by dsherret** [comment]
We might want to consider just computing a hash of the source file instead of using timestamps. It's super fast to do.

**Comment by dsherret** [comment]
Also, the current reading from the sqlite cache might be racy now after https://github.com/denoland/deno/pull/23634 -- we probably just want to compute a hash all the time

**Comment by igorzi** [comment]
Will benchmark with computed hashes
