### ISSUE TITLE
CustomEvent is not generic

### ISSUE THREAD

**Issue by motss** [denoland/deno#2391]
Not sure if this is intentional but `CustomEvent` should accept a type parameter.

https://github.com/denoland/deno/blob/880265275fd49b1dad9a5643e2ad299292901e89/js/dom_types.ts#L147-L149

Correct me if I'm wrong.

**Comment by kitsonk** [comment]
Are you suggesting that the detail can by constrained by a generic?

**Comment by acconrad** [comment]
[The spec requires this be of type `any`](https://dom.spec.whatwg.org/#customevent)

**Comment by motss** [comment]
@kitsonk @acconrad This is what `TypeScript` has been doing instead hardcoding it to `any` by allowing `CustomEvent` to accept type parameter.

The following code shows how it is done in `TypeScript`'s `dom` lib:

https://github.com/microsoft/TypeScript/blob/master/lib/lib.dom.d.ts#L274-L276

**Comment by nayeemrmn** [comment]
This is fixed.
