### ISSUE TITLE
Memory leak in `node:vm`

### ISSUE THREAD

**Issue by uriva** [denoland/deno#23913]
using this package, deno causes a memory leak where node does not

https://github.com/sindresorhus/get-urls/issues/89#issuecomment-2120647508

```ts
import {range} from "gamla";
import getUrls from "get-urls";

for (const x of range(0, 1000)) {
  getUrls("hello");
}
console.log("all done");
```

deno 1.43.5 (release, x86_64-unknown-linux-gnu)
v8 12.4.254.13
typescript 5.4.5

**Comment by marvinhagemeister** [comment]
Can confirm this leaks memory. It seems to be caused by something in our implementation of `node:vm`. I see lots of bootstrap objects in heap dumps.

**Comment by marvinhagemeister** [comment]
Smaller reproduction:

```ts
import vm from "node:vm";

const script = new vm.Script("returnValue = 2+2");

for (let i = 0; i < 1000; i++) {
  script.runInNewContext({}, { timeout: 10000 });
}
```
