### ISSUE TITLE
Cannot execute: required file not found when trying to run in termux

### ISSUE THREAD

**Issue by Xeononyum** [denoland/deno#23922]
Using termux
Got this error after installation with
`
curl -fsSL https://deno.land/install.sh | sh
`
and trying to run it, also tried installing this file from release from github 
`deno-aarch64-unknown-linux-gnu.zip`
same error when trying to run executable

The error:
![Screenshot_2024-05-21-18-00-42-419-edit_com termux](https://github.com/denoland/deno/assets/90855565/8fba0c2d-c5f2-4fca-9066-34cb8300cc62)

I think problem probably are in this
![Screenshot_2024-05-21-18-26-45-831-edit_com termux](https://github.com/denoland/deno/assets/90855565/e5da38f5-d244-4ee3-a366-14590ba63262)
![Screenshot_2024-05-21-18-24-59-465-edit_com termux](https://github.com/denoland/deno/assets/90855565/0de317b7-9d5a-4d14-a440-e61834dd1c14)

It can't find needed libraries, because termux have different paths than linux

**Comment by Leokuma** [comment]
I don't think that executable is supposed to work in Termux.

Try this one: https://github.com/cions/termux-deno

You may have to build it yourself if your phone is an older model.

**Comment by lucacasonato** [comment]
@Leokuma is correct - you need to have these dependencies installed, otherwise Deno can not run.
