### ISSUE TITLE
LSP: Regression in resolving Typescript Dependencies of included Typing files 

### ISSUE THREAD

**Issue by mechanoid** [denoland/deno#23925]
Version: Deno 1.43.4

The mentioned behaviour can for example be seen, when trying to include express types.

```
import type { NextFunction, Request, Response } from "npm:@types/express";
import express from "npm:express";
```

Same is true for type assignment like:

```
// @deno-types="npm:@types/express"
import express, { Request, Response } from "npm:express"
```

The types include references to type dependencies:

```
/// <reference types="express-serve-static-core" />
/// <reference types="serve-static" />
```

LSP fails to resolve them, while that worked in beforehand. Also `deno check` does work in 1.43.3 still,
which leads to the assumption that this is not working as expected.

An example app is described here: https://github.com/mechanoid/deno-ts-dependency-refs-bug/blob/main/main.ts

**Comment by nayeemrmn** [comment]
This is likely fixed by #23902.

**Comment by mechanoid** [comment]
That sounds great, I will give it a try, once it is released 👍 Thanks for your fast response!

**Comment by mechanoid** [comment]
works like charm, thanks a lot @nayeemrmn !
