### ISSUE TITLE
tabler icon import failing

### ISSUE THREAD

**Issue by crowlsyong** [denoland/deno#23948]
**Version: Deno 1.43.5 (release, aarch64-apple-darwin)
v8 12.4.254.13
typescript 5.4.5
Fresh Framework
Deno KV**

### Issue
cannot import IconCopyCheck with `https://deno.land/x/tabler_icons_tsx@0.0.5/tsx/copy-check.tsx`
Visiting that url appears to show a 404 not found inside the area where the data should be. I My have run into other Icons which don't import, but I forgot to write them down. I will comment on this if I find another one. 

Tell me what else you need from me and I will get you the info as best I can. If this is a Fresh Framework issue, let me know and I'll post this there instead.

I am using other icons that work though, for example, these all work for me:
`import IconQrcode from "https://deno.land/x/tabler_icons_tsx@0.0.5/tsx/qrcode.tsx";`

`import IconHttpDelete from "https://deno.land/x/tabler_icons_tsx@0.0.5/tsx/http-delete.tsx";`

`import IconCopy from "https://deno.land/x/tabler_icons_tsx@0.0.5/tsx/copy.tsx";`

`import IconEdit from "https://deno.land/x/tabler_icons_tsx@0.0.5/tsx/edit.tsx";`

`import IconDeviceFloppy from "https://deno.land/x/tabler_icons_tsx@0.0.5/tsx/device-floppy.tsx"; `

**Comment by crowlsyong** [comment]
`import IconCopyPlus from "https://deno.land/x/tabler_icons_tsx@0.0.5/tsx/copy-plus.tsx"`
also fails

**Comment by marvinhagemeister** [comment]
I don't think that's something that needs to be addressed inside the Deno runtime. Deno hits that URL, sees that it doesn't exist because it returns a 404 and rightfully throws an error.

Browsing through the code confirms that the library doesn't have a copy-plus icon anywhere in the code.

**Comment by crowlsyong** [comment]
Marvin thank you for looking into this. What do you suggest I do to get this issue noticed by the right folks?

**Comment by lucacasonato** [comment]
You can file an issue here: https://github.com/hashrock/tabler-icons-tsx

**Comment by crowlsyong** [comment]
> You can file an issue here: https://github.com/hashrock/tabler-icons-tsx

Thank you, will do.
