### ISSUE TITLE
Node imports don't have LSP autocompletion / suggestion

### ISSUE THREAD

**Issue by szmarczak** [denoland/deno#23944]
Version: Deno 1.43.6

![image](https://github.com/denoland/deno/assets/36894700/c2688108-2413-48a0-92b9-e36ef75d8b6e)

**Comment by marvinhagemeister** [comment]
Just tried that out in a new project and the autocompletion shows up as expected.

**Comment by lucacasonato** [comment]
Closing because the OP has not provided any further info.
