### ISSUE TITLE
Going to jsr specifier immediately after restarting the language server leads to incorrect path

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#23967]
https://github.com/denoland/deno/assets/1609021/b2ba2cf3-ae52-46c5-91a2-3c1d585da988

Version: Deno 1.43.6

**Comment by nayeemrmn** [comment]
I can't reproduce this, is it still an issue? Could have been fixed by #23998.

**Comment by dsherret** [comment]
It's much more reliable now. Thanks!
