### ISSUE TITLE
`--quiet` does nothing for `deno test`

### ISSUE THREAD

**Issue by Ettapp** [denoland/deno#23964]
Version: Deno 1.43.6

The output of the commands `deno test foo.test.ts` and `deno test --quiet foo.test.ts` are identical.

## Reproduction steps

1. Create a file, for example `foo.test.ts`, containing some tests:
```typescript
Deno.test('name', () => {
  throw new Error();
});
```

2. Run the command `deno test foo.test.ts`
3. Run the command `deno test --quiet foo.test.ts` or `deno test -q foo.test.ts`
4. Outputs are the same (not quiet)

## Comment

I tried with some successful tests as well, the result is the same.
I also tried `deno --quiet test ...` in case it was a documentation issue but the result is still the same.

I'd love to check Deno's code to check if this is the intended behaviour but I don't know Rust... so if this is not an bug please forgive me for opening this issue :slightly_smiling_face:

**Comment by bartlomieju** [comment]
This is expected behavior - we don't want to silence errors thrown. The `--quiet` flag has impact on "output" generated by tests, eg:
```
Deno.test("name", () => {
  console.log("foobar");
});
```

```
$ deno test foo.js
running 1 test from ./foo.js
name ...
------- output -------
foobar
----- output end -----
name ... ok (0ms)

ok | 1 passed | 0 failed (1ms)

```

```
deno test --quiet foo.js
running 1 test from ./foo.js
name ... ok (0ms)

ok | 1 passed | 0 failed (1ms)

```

**Comment by Ettapp** [comment]
Thank you for the rapid response, and sorry for the useless issue x)
