### ISSUE TITLE
Cannot dynamically import uncached JSR module: "TypeError: Could not find constraint in the list of versions"

### ISSUE THREAD

**Issue by alexgleason** [denoland/deno#23965]
Version: Deno 1.43.4

I'm using a dynamic import to import a module based on an environment variable:

```ts
const Policy = (await import(Deno.env.get('DITTO_POLICY'))).default;
const policy = new Policy();
```

This allows users to have `DITTO_POLICY=jsr:@gleasonator/policy@0.2.0`, and it dynamically imports the module.

When I do that, I get this error:

```
TypeError: Could not find constraint in the list of versions: @gleasonator/policy@0.2.0
```

I am able to **resolve** that error by manually running `deno cache jsr:@gleasonator/policy@0.2.0`

Then it works. Because the module is available now. The error disappears. But I would like it to be automatic.

To solve this, I wondered if some sort of `Deno.cache` runtime API exists (it doesn't?). The other option is to run a Deno subcommand that calls the `deno cache` API.

It made me wonder, how does Deno resolve dynamic imports? Shouldn't we expect it to download and cache the module automatically like other imports? So it got me thinking that maybe this is a bug in Deno.

**Comment by dsherret** [comment]
There's code for it to cache bust and just work. It seems like it's not working with dynamic imports though.

**Comment by nandorojo** [comment]
I’m facing the same thing. Let me confirm that it’s due to dynamic imports (I believe it is).

**Comment by dsherret** [comment]
Just a note that you can get around this by running with `--reload`

**Comment by alexgleason** [comment]
I've still been manually running `deno cache jsr:<package>` for each of my new dynamic imports.

If there was even a `Deno.cache` runtime API that would let me cache the modules I need at startup that would be a big improvement.

I also don't necessarily want them in deno.lock.

**Comment by pomdtr** [comment]
I found out that if the dynamic imports are statically analysable, the issue does not occur.
