### ISSUE TITLE
Re-land "Fix permissions for dial and listen (#2373)"

### ISSUE THREAD

**Issue by piscisaureus** [denoland/deno#2397]
Reverted due to Mac CI breakage.

**Comment by ry** [comment]
I'm unable to repeat the hang locally...

Ref: 7d03a63dedac6c0509655248107dcfb8b3142442 
Ref: 7219787894f13b1920b3b6b49203cdcb8f672c00

**Comment by bartlomieju** [comment]
I'm also unable to repeat the failure locally. 

Interestingly CI was successful in PR but only failed on `master`.

I'll investigate it further
