### ISSUE TITLE
Debug test in Visual Studio Code & deno.jsonc

### ISSUE THREAD

**Issue by hapaxlife** [denoland/deno#23975]
Version: Deno 1.43.6
Deno for Visual Studio Code : 3.37.1
Mac Os:  14.4.1 (23E224)

Debug test can't launch because I use a `deno.jsonc` with comment inside (ex : `// a comment`).
It works when I delete comments in the file.

<img width="266" alt="Capture d’écran 2024-05-24 à 10 38 46" src="https://github.com/denoland/deno/assets/97401010/b48f5fea-fc78-4403-bb39-ac59d9f800c8">

```ts
⚠️  The `--unstable` flag is deprecated and will be removed in Deno 2.0. Use granular `--unstable-*` flags instead.
Learn more at: https://docs.deno.com/runtime/manual/tools/unstable_flags
error: Unable to load 'file:///Users/xxx/xx-api/deno.jsonc' import map

Caused by:
    key must be a string at line 21 column 5

 *  Échec du lancement du processus de terminal "/opt/homebrew/bin/deno 'test', '--allow-all', '--no-check', '--unstable', '--inspect-wait', '--import-map', './deno.jsonc', '--filter', '/^data identical$/', '/Users/xxx/xx-api/xx/routes/xxx.test.ts'" (code de sortie : 1). 
 ```

**Comment by dsherret** [comment]
Do you have a `"deno.importMap"` setting set to a `deno.jsonc`? If so, remove that and use `"deno.config"` instead.

**Comment by hapaxlife** [comment]
Thanks, it works.

I have deleted `"deno.importMap": "./deno.jsonc"` from my `".vscode/setting.json"` file
