### ISSUE TITLE
OS X Mavericks, deno command throws 0x80000034

### ISSUE THREAD

**Issue by theokeist** [denoland/deno#23973]
Version: Deno @1.43.6_0

Hello trying to run deno on OS X Mavericks 10.9.5 , installed from MacPorts

dyld: cannot load 'deno' (load command 0x80000034 is unknown)
fish: Job 1, 'deno' terminated by signal SIGTRAP (Trace or breakpoint trap)

**Comment by littledivy** [comment]
OSX Mavericks is not supported. Deno releases are compiled on Github actions with recent macOS and dyld versions. PRs accepted if there is a trivial fix to make it work.
