### ISSUE TITLE
unzip not found on PATH on Ubuntu 22.04 when using 'deno compile', although unzip has been installed and can be executed on command line

### ISSUE THREAD

**Issue by flo-jan** [denoland/deno#23988]
deno 1.43.6 (release, x86_64-unknown-linux-gnu)
 Ubuntu 22.04

When I give the command 'deno compile' it gives the error:  "unzip was not found in your PATH, please install unzip".

But unzip is installed. I can use unzip commands in the same terminal as where I try to execute the deno compile command.

Could this be a bug?

**Comment by jerome-benoit** [comment]
Outputs of
```shell
echo $PATH
which unzip
```

**Comment by flo-jan** [comment]
output of echo $SHELL is '/bin/bash'

other outputs can be seen in screenshot:
![deno and unzip](https://github.com/denoland/deno/assets/143704628/a0ca9f57-1930-4ca1-90c7-7a031683d8e5)

**Comment by littledivy** [comment]
Maybe the temp directory Deno created got deleted before unzip was called. @flo-jan Do you have any background service that deletes `/tmp/`?

The error message can be improved.

**Comment by flo-jan** [comment]
Deno runs as Snap application.

There is a `/tmp/snap-private-tmp/snap.deno/tmp/ ` folder. It is empty and remains empty after running `deno compile`, but I can see something happens with it, because the modified date of that folder updates each time I run `deno compile`.

**Comment by flo-jan** [comment]
I would be interested if someone is able to reproduce this issue

**Comment by flo-jan** [comment]
I tried another way of installing deno, not with Snap but with this command:
 ```curl -fsSL https://deno.land/x/install/install.sh | sudo DENO_INSTALL=/usr/local sh```

I still encounter the same problem when trying to run deno compile but with a different error message:

```
Archive:  /tmp/.tmpPoaYid/denort.zip
  inflating: denort                  
error: Writing write

Caused by:
    No such file or directory (os error 2)
```

I checked the /tmp folder. I can create folders and files in it and they are not removed automatically. 


I also tried another laptop with Ubuntu 22.04 installed and on that laptop deno compile works without problems.

**Comment by jerome-benoit** [comment]
Since an Ubuntu clean install of the same version does not trigger any issue, it looks more like an issue with the OS and/or the user env setup.

**Comment by flo-jan** [comment]
Deno.makeTempFile() works correctlty however, on the same computer

**Comment by flo-jan** [comment]
it creates files in the /tmp folder

**Comment by flo-jan** [comment]
It would be helpful if would know the exact location in deno's source code where this

```
Archive:  /tmp/.tmpPoaYid/denort.zip
  inflating: denort                  
error: Writing write

Caused by:
    No such file or directory (os error 2)
```
happens. Could someone point me to that?

**Comment by sakars** [comment]
I seem to be having a similar issue, `unzip` is located in PATH and at least the help page is displayed for it from the terminal, but `deno compile` fails. I will note that I am launching this from a VirtualBox VM
