### ISSUE TITLE
Added API to change file creation date/time

### ISSUE THREAD

**Issue by fushihara** [denoland/deno#23993]
Deno.utime changes the modification date and access date, but there is no API to change the file creation date and time.
In node.js, you need to use a third-party native add-on, but no similar one exists for Deno.
https://stackoverflow.com/questions/25484175/nodejs-how-to-change-creation-time-of-file

It seems inconsistent that you can edit the modification date and time but not the creation date and time.

**Comment by lucacasonato** [comment]
Linux has no API to set birth time of a file. As such we can't implement this - what Node addon would give you this functionality?

And what is your usecase?

**Comment by fushihara** [comment]
I did not know that birth time is not mandatory on linux but depends on the file system.
I use windows and was not aware of it because the creation date and time is an attribute that is always present in windows.
Close the request.
Thank you very much.
