### ISSUE TITLE
Use unittest in python tests

### ISSUE THREAD

**Issue by ry** [denoland/deno#2399]
Originally we didn't have many tests in python. Deno is mostly TypeScript and Rust, so that makes sense. Why do we have python at all?

Python is used during build time for miscellaneous tasks and to run the deno and rust tests.

We use Python because V8/GN/Chrome uses Python. (Specifically Python 2.7 - we do not have the possibility of using Python 3 until Chromium makes the switch.)

Over time the Python code base has grown. We should try to be more sanitary in our testing of this internal code by using a real test framework: https://docs.python.org/2/library/unittest.html

A few places where unittest should be applied:
- [ ] [tools/util_test.py](https://github.com/denoland/deno/blob/1386b6ead586da15d0285941f2d980acc1d75eee/tools/util_test.py)
- [ ] [tools/setup_test.py](https://github.com/denoland/deno/blob/1386b6ead586da15d0285941f2d980acc1d75eee/tools/setup_test.py)
- [ ] [tools/permission_prompt_test.py](https://github.com/denoland/deno/blob/1386b6ead586da15d0285941f2d980acc1d75eee/tools/permission_prompt_test.py)
- [ ] [tools/complex_permissions_test.py](https://github.com/denoland/deno/blob/1386b6ead586da15d0285941f2d980acc1d75eee/tools/complex_permissions_test.py)

**Comment by bartlomieju** [comment]
I'll work on that
