### ISSUE TITLE
Show more explicit message when `deno task` cannot find a config file

### ISSUE THREAD

**Issue by magurotuna** [denoland/deno#23990]
## Issue

Currently, when we run `deno task foo` in a project that doesn't have `deno.json(c)` file, Deno just emits a message like this:

```console
$ deno task foo
error: No config file found
```

If you are working in a project that has a few number of files, then it'd be very clear that what this message means that you don't have deno.json(c) file. However, if your project is using some framework that has its own configuration file, you would be very confused with what this message indicates and from where it is emitted.

## Solution

Changing this message to something more explicit, for instance `deno task error: No config file found. See https://deno.land/manual@v${DENO_VERSION}/getting_started/configuration_file`, would be helpful

**Comment by 520Book** [comment]
非常开心，我提的一个小建议能够被`Deno`采纳，祝愿`Deno`越来越好。
