### ISSUE TITLE
add --hide-traces flag to deno test to ignore the stack trace completely

### ISSUE THREAD

**Issue by carafelix** [denoland/deno#24002]
I been using deno test in the simple `describe` > `it` fashion, and it's alright. The only downside I've encounter is when multiple test's are failing, it gets cluttered real quickly with long stack traces. When writing good describe-it combinations I already now where and what failed, so it's not necessary that whole stack trace. Adding -q flag won't help it.
Current:
```md
describe it description yara yara
error: AssertionError: Values are not equal.


    [Diff] Actual / Expected


-   undefined
+   "poussar"                   <-- up to here would be okay some times :) 

  throw new AssertionError(message);
        ^
    at assertEquals (https://deno.land/std@0.203.0/assert/assert_equals.ts:53:9)
    at Object.<anonymous> (file:///media/martincito/freedom/repos/grammy/commands/test/jaroWrinkler.test.ts:169:21)
    at Function.runTest (https://deno.land/std@0.203.0/testing/_test_suite.ts:358:16)
    at Function.runTest (https://deno.land/std@0.203.0/testing/_test_suite.ts:346:33)
    at Function.runTest (https://deno.land/std@0.203.0/testing/_test_suite.ts:346:33)
    at Function.runTest (https://deno.land/std@0.203.0/testing/_test_suite.ts:346:33)
    at Function.runTest (https://deno.land/std@0.203.0/testing/_test_suite.ts:346:33)
    at fn (https://deno.land/std@0.203.0/testing/_test_suite.ts:316:37)
```
#13586 and #14921 mention shortening the stack trace. I would like a flag to completely remove it. 
Desired:
```md
describe it description yara yara
error: AssertionError: Values are not equal.


    [Diff] Actual / Expected


-   undefined
+   "poussar"
```

Call it --hide-traces or --hide-stack-trace or whatever you wanna call it, but as of rn its too much visual noise. Thanks

**Comment by safaa-mojahed** [comment]
@carafelix 
This suggestion seems incredibly beneficial for developers. I'll begin investigating it and will keep you updated. Thanks!

**Comment by dandv** [comment]
@dsherret @Hajime-san @marvinhagemeister 

I've also run into this issue with assert stack traces being overly verbose. But I think we threw the baby with the bath water by getting rid of the stack traces completely.

Without `--hide-stacktraces`, the output is clearly noisy, but it does include the actual line of code that triggered the assertion failure:

```
error: AssertionError
    throw new AssertionError(msg);
          ^
    at assert (https://jsr.io/@std/assert/1.0.10/assert.ts:21:11)
    at Object.<anonymous> (file:///home/dandv/THIS/IS/MY/CODE/THAT/I/CARE/ABOUT/foo.test.ts:372:28)
    at eventLoopTick (ext:core/01_core.js:175:7)
    at async Function.runTest (https://jsr.io/@std/testing/1.0.8/_test_suite.ts:428:7)
    at async Function.runTest (https://jsr.io/@std/testing/1.0.8/_test_suite.ts:416:9)
    at async fn (https://jsr.io/@std/testing/1.0.8/_test_suite.ts:377:13)
```

Out of all the stack trace items above, I don't see much (any?) utility for the lines pertaining to Deno (eventLoopTick) or the standard libs, but I DO want to see which line in *my code* had the failing assertion.

This is extra important:
1. For IDEs in being able to jump to that point in the code. The `--hide-stack-traces` hides the stack traces completely, so this cripples the IDE and I have to guess which of the several asserts in a test failed.
2. For generic `assert` statements, which don't (can't) output anything specific about what assertion failed. Given the code below,

```ts
import { assert } from '@std/assert';

const foo = 1;

Deno.test('assert foo', () => {
  assert(foo < 4);
  assert(foo > 2);
});
```

Running `deno test --hide-stacktraces deno-bug.test.ts` produces just `error: AssertionError`, not which of the two:

```
running 1 test from ./deno-bug.test.ts
assert foo ... FAILED (1ms)

 ERRORS 

assert foo => ./deno-bug.test.ts:5:6
error: AssertionError

 FAILURES 

assert foo => ./deno-bug.test.ts:5:6

FAILED | 0 passed | 1 failed (3ms)

error: Test failed
```

(contrived example, but with the exception of the test line (`5`), this output is *purely* noise)

Can we revisit stack traces? Perhaps we don't need the flag at all, just to hide by default stack trace lines from the standard testing libraries, continuing the efforts from #13586 and  #14921.

**Comment by dandv** [comment]
Also, should the flag by hyphenated to `--hide-stack-traces`, as other compound word flags are, e.g. `--permit-no-files` or `--no-clear-screen`?

**Comment by bartlomieju** [comment]
@dandv I suggest to open a new issue about this problem, rather than reviving an issue that was closed several months ago. 

> Also, should the flag by hyphenated to --hide-stack-traces, as other compound word flags are, e.g. --permit-no-files or --no-clear-screen?

Probably, but at this point we'd still have to keep `--hide-stacktraces` working to not incur churn on users relying on this flag already.

**Comment by dandv** [comment]
@bartlomieju: good point, I've created #27553.
