### ISSUE TITLE
Bug: `deno install` doesn't print package deprecation warnings

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/deno#24013]
Installing npm packages via `deno install` doesn't print any package deprecation messages.

## Steps to reproduce

1. Run `npm init -y`
2. Run `npm i uuid@3.4.0` -> prints deprecation messages
3. Run `rm -rf node_modules/`
4. Run `deno i` -> no deprecation messages

## Output

npm: 
```sh
$l npm i uuid@3.4.0
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

added 1 package, and audited 2 packages in 579ms

found 0 vulnerabilities
```

Deno:
```
$ DENO_FUTURE=1 deno i
⚠️ `deno install` behavior will change in Deno 2. To preserve the current behavior use the `-g` or `--global` flag. 
```

Version: Deno 1.43.6

**Comment by bartlomieju** [comment]
Some more info:
- we can pull this data from the version manifest, available in `deprecated` field - eg. https://registry.npmjs.org/lucia-auth/1.8.0
- it needs to be captured in relevant structs in the https://github.com/denoland/deno_npm repo
- during installation, the message should be printed if it's defined

**Comment by HasanAlrimawi** [comment]
could you clarify how to produce some case where we need to show deprecation warning message

**Comment by bartlomieju** [comment]
This function would need to be updated to provide `deprecated` field for some packages: https://github.com/denoland/deno/blob/1ba88a7892fa1b0d7cf229b0cd5709575901ebd0/tests/util/server/src/npm.rs#L191-L271
