### ISSUE TITLE
Prisma `library` using N-API hangs often

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#24010]
The Prisma CLI/binary works fine in Deno these days, but the "library" or the engine often hangs.

The library uses N-API under the hood and it's very likely that the problem originates in the "threadsafe functions" - the hang suggests that a waker for a threadsafe function might get lost, but it's just a theory that needs to be confirmed. https://github.com/denoland/deno/issues/23995 will greatly help debugging this problem.

The reproduction repo is here: https://github.com/janpio/prisma-deno-library-hang-repro

One can use `DEBUG=*` env var to get verbose logging that should show something like:
```
prisma:client:libraryEngine library starting +5ms
prisma:info Starting a postgresql pool with 17 connections.
prisma:client:libraryEngine library started +552ms
```

@janpio suggests that the problematic line is (this line calls the N-API interface):
```json
await this.engine?.connect(JSON.stringify(headers))
```

Additional Jan reports that in some cases the library successfully starts and errors with:
```
prisma:client:libraryEngine library starting +5ms
prisma:info Starting a sqlite pool with 9 connections.
error: Top-level await promise never resolved
const users = await prisma.user.findFirst();
              ^
    at <anonymous> 
```

Which further strengthens my suspicion that it's the threadsafe functions in N-API layer that misbehave.

**Comment by devsnek** [comment]
This should be fixed in https://github.com/denoland/deno/pull/24101, let us know if you encounter more issues.
