### ISSUE TITLE
fails to import a module because of invalid utf8 sequence from npm packages

### ISSUE THREAD

**Issue by sigmaSd** [denoland/deno#24027]
Original issue https://github.com/denoland/deno/issues/23911

The original issue was not fixed by the pr https://github.com/denoland/deno_graph/pull/483

```js
import {} from "npm:js-clipper@1.0.1";
```

the minimal reproduction was fixed, I'm suspecting that when importing from npm packages there is another decode path at play that still doesn't handle utf8

**Comment by sigmaSd** [comment]
deno 1.43.6+a892353 (canary, x86_64-unknown-linux-gnu)

**Comment by sigmaSd** [comment]
The last debug message is coming from here https://github.com/denoland/deno/blob/a8923534ed02e9e4ba3bb277db6e61a208c64125/cli/npm/managed/mod.rs#L302

so the error is not in deno graph anymore, maybe its in deno npm

**Comment by dsherret** [comment]
> so the error is not in deno graph anymore, maybe its in deno npm

No, at this point it would be node execution. It's probably in https://github.com/denoland/deno/tree/main/ext/node

**Comment by sigmaSd** [comment]
Seems like there are a couple of places that have this wrong assumption:

https://github.com/denoland/deno/blob/main/ext/fs/interface.rs#L303 which is called from https://github.com/denoland/deno/blob/main/cli/resolver.rs#L296

changing that to utf8_lossy, gets through that point, but now there is another error which seems coming from node module

```
error: Uncaught (in promise) InvalidData: invalid utf-8 sequence of 1 bytes from index 165105
    at Object.Module._extensions..js (node:module:1053:19)
    at Module.load (node:module:912:32)
    at Function.Module._load (node:module:721:12)
    at Module.require (node:module:934:19)
    at require (node:module:1119:16)
    at file:///home/gitpod/.cache/deno/npm/registry.npmjs.org/js-clipper/1.0.1/clipper.js:3:13
```

**Comment by sigmaSd** [comment]
Everything works if I change https://github.com/denoland/deno/blob/main/ext/fs/interface.rs#L293 and https://github.com/denoland/deno/blob/main/ext/fs/interface.rs#L303 to utf8_lossy

One is called from https://github.com/denoland/deno/blob/main/cli/resolver.rs#L296 and the other from https://github.com/denoland/deno/blob/main/ext/node/polyfills/01_require.js#L1053

@dsherret is it an ok fix to make them utf8lossy ? would be great if someone picks this up, I don't have time to figure out tests
