### ISSUE TITLE
Bare specifier resolution error message should include a hint to `deno add` the specifier

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#24033]
`import "@std/fs"` without `@std/fs` in package.json or deno.json raises an error about an invalid bare specifier (specifier not prefixed with `./`, `../`, or `/`).

We should include a hint about adding the package using `deno add` from either npm or JSR. This should also be an LSP quickfix.

**Comment by HasanAlrimawi** [comment]
I'd like to investigate this issue if it's still available.

**Comment by nayeemrmn** [comment]
Closed in #24524.
