### ISSUE TITLE
Extremely high memory usage

### ISSUE THREAD

**Issue by saeho** [denoland/deno#24055]
Version: Deno 1.43.5
<img width="642" alt="image" src="https://github.com/denoland/deno/assets/9645145/bc06f47a-90ba-4dc3-a1e2-f12d2fabe7c6">

After a little bit of use (2 running deno instances, 1 fresh app and 1 deno server) my memory usage has sky rocketed. Unsure what the cause is other than a lot of rapid development.

<img width="667" alt="image" src="https://github.com/denoland/deno/assets/9645145/0309cbee-91ed-4cc3-b702-767b63520173">

After force-quitting both deno apps, I waited few seconds ony to see a new instance of deno pop up, at which point I realized this is the VS Code deno plugin.

Is this much memory usage normal? I might as well not use the deno plugin if that's the case. If I was doing mobile development, it'd be nearly impossible to use Deno with this much memory footprint. (My computer has 32gb ram, Mac Studio M1)

**Comment by lucacasonato** [comment]
Could you run the `Deno: Language Server Status` command from the VS Code command palette and paste the output here?

**Comment by saeho** [comment]
I would, but this is no longer a problem.

2 days after I uninstalled the plugin, I reinstalled it and the problem was gone. On this day when I posted this report however, reinstalling VS Code didn't work at that time.

**Comment by lucacasonato** [comment]
Ok, that's great to hear. We made some improvements to the LSP in the last weeks - maybe one of them  fixed things for you. 😀

**Comment by jsb188** [comment]
Back to this problem. I wasn't observing my task manager so I didn't realize how bad the RAM usage for this was.

When I use VS Code with Deno extension, VS Code runs a Deno server running in the background-- and when it does, it uses 50 GB+ memory every single time.

Because of this, I can't use the Deno extension. Is there anything I can do prevent this?
