### ISSUE TITLE
Uncaught SyntaxError: Unexpected reserved word

### ISSUE THREAD

**Issue by laurencebedford** [denoland/deno#24064]
Version: Deno v1.40.3

I am using a Deno stream:

```
const transformedBody = response.body
      .pipeThrough(new TextDecoderStream())
      .pipeThrough(
        new TransformStream({
          transform: (chunk, controller) => {
            const lines = chunk.split("\n");
            const newLines = lines.map(line => {
```

I would like to use an await in the stream to insert data to a table as it comes in - my issue is that when I use an async function in the transformed body - I get the following error:

> Uncaught SyntaxError: Unexpected reserved word

I thought Top-level for-await not working in bundles was patched - if not whats the work around?

I am directly returning this stream via an edge function to my client - ideally is I would insert the data from the stream on the server just not sure the work around here...:

```
return new Response(transformedBody, {
      headers: {
        'Access-Control-Allow-Origin': '*',
        'Content-Type': 'text/event-stream',
      },
    });
```

**Comment by laurencebedford** [comment]
- fixed this via the use of a wrapper function:

```
// executeQuery.js
function executeQuery(cb) {  
  cb()  
}

// usage
const insert = async () = await //[insert logic depending on db here]

executeQuery(insert); // don't await here
```

**Comment by BlackAsLight** [comment]
Why not show us how you were making the transform body async since that is when you got the unexpected syntax error? I also don't see how making it async would have anything to do with a top level await.
