### ISSUE TITLE
`Napi::Buffer<uint8_t>` produces a Uint8Array instead of a NodeJs `Buffer`

### ISSUE THREAD

**Issue by BAKFR** [denoland/deno#24083]
Version: Deno 1.44.0

Using the npm package `argon2`, I got this error:
```ts
import { hash } from "npm:argon2"
await hash('password');

Uncaught TypeError: hash must be a Buffer
    at serialize (file:///home/bak/.cache/deno/npm/registry.npmjs.org/@phc/format/1.0.0/index.js:123:15)
    at hash (file:///home/bak/.cache/deno/npm/registry.npmjs.org/argon2/0.40.3/argon2.cjs:120:10)
    at async <anonymous>:1:22
```

This is caused by a difference of behavior between Deno and Node.Js
 A [call to the function `bindingsHash()`](https://github.com/ranisalt/node-argon2/blob/master/argon2.cjs#L104), returns an `UInt8Array` instead of the expected NodeJs `Buffer`.

This function is defined in cpp using a `binding.gyp` file, under the name `hash`.
Its code use a `Napi::AsyncWorker` in order to return a `Napi::Buffer<uint8_t>`, [here](https://github.com/ranisalt/node-argon2/blob/c20e64ac258721e26223dc6401b1eb414ddfc71d/argon2_node.cpp#L60).

**Comment by devsnek** [comment]
This was fixed in 1.44.1.
