### ISSUE TITLE
`deno serve` doesn't support the second connInfo parameter

### ISSUE THREAD

**Issue by bendechrai** [denoland/deno#24099]
Version: Deno 1.44.0

I'm trying to get the IP address of the client when running declarative scripts through `deno serve`.

It seems the fetch method only accepts the first `request` parameter, and if I expect and address the `connInfo` parameter, I get an Internal Server Error and a console output of `TypeError: Cannot read properties of undefined (reading 'remoteAddr')`.

Are declarative scripts intended to not have access to this additional information? Or have I overlooked something?

```js
export default {
  async fetch(request, connInfo) {
    const clientIP = connInfo.remoteAddr.hostname;
    return new Response(`Hello world! Your IP address is ${clientIP}`);
  },
};
```

Cheers,
Ben

(As [reported on discord](https://discord.com/channels/684898665143206084/1247586550322298910/1247586550322298910) and added here on request)

**Comment by ArmaanAS** [comment]
I was trying to switch over from `Deno.serve()` to `deno serve --parallel` but the lack of IP Address support is a blocker.
