### ISSUE TITLE
Astro can't access `process` global

### ISSUE THREAD

**Issue by EdamAme-x** [denoland/deno#24096]
It can create compatibility with many frameworks.

Ex.

```ts
Deno.env.get("NODE_ENV") === process.env.NODE_ENV
```

**Comment by EdamAme-x** [comment]
ref
https://github.com/denoland/deno/blob/3341c50b6ae676cdc8f7b1c44221aa633f2bde68/ext/node/polyfills/_process/process.ts#L38

**Comment by bartlomieju** [comment]
Can you elaborate what's the ask here?

**Comment by EdamAme-x** [comment]
hi @bartlomieju 
Thanks for your reply.

I think `node:process` should be the standard global object.
This should allow Astro to work fully with the Deno itself, including the hydrate process.

Astro is using `node:process` in global

**Comment by bartlomieju** [comment]
We are not going to expose `process` as a global object in user code, but the NPM packages should have it available. If it doesn't work with Astro it's a bug. Do you have a reproduction that currently doesn't work correctly?

**Comment by EdamAme-x** [comment]
thanks for the reply.
It can be reproduced by creating a normal Astro app with bun and running `astro dev` with deno. Normally this does not happen, but if you add an integration such as react, you will get a reference error in `component-render.js` that the `process` does not exist.

**Comment by bartlomieju** [comment]
@littledivy can you check this one?

**Comment by EdamAme-x** [comment]
it works! thanks bro!!! @bartlomieju
