### ISSUE TITLE
WebSocket `MessageEvent` has `CloseEvent` as its symbol.

### ISSUE THREAD

**Issue by thesmart** [denoland/deno#24103]
Version: Deno 1.44.0

I noticed in the debugger I was getting `CloseEvent` for the first argument in my message event handler even though `e instanceof MessageEvent` is true. I looked up source code and you can see that the symbol is labeled incorrectly.

https://github.com/denoland/deno/blob/main/ext/web/02_event.js#L1198

**Comment by sossost** [comment]
@bartlomieju 
Hello, I am sossost, a new contributor. Can I help you fix this issue?

**Comment by bartlomieju** [comment]
@sossost please do
