### ISSUE TITLE
feature request: add a `--no-deno-namespace` mode

### ISSUE THREAD

**Issue by lowlighter** [denoland/deno#24105]
It'd be nice to have a mode where it's possible to "disable" the `Deno` namespace entirely so it can acts like as a regular TS interpreter without any "unstandard" apis.

Use-case could be, along with the already implemented permissions system, to create small sandboxes by spawning new processes where untrusted ts code could be run and also without leaking server info (through `Deno.build`) for example or limit capabilities (like preventing `Deno.exit`).

This would also helps in testing to simulate a non-deno environment where there is code branched on it

If this gets implemented, consider to also add this option back web workers (it was removed when `Deno` namespace was enabled by default in them, but it used to be optional in older versions of deno)

**Comment by bartlomieju** [comment]
You can do it yourself without a flag by calling `delete globalThis.Deno` before importing user code.

**Comment by lucacasonato** [comment]
I agree with Bartek, you can run `delete globalThis.Deno`. Adding flags for this doesn't make sense - someone will then ask us to add `--no-fetch`, `--no-worker`, and `--no-websocket` flag :)

**Comment by lowlighter** [comment]
I guess that's a workaround indeed.

I still think it's a different case that other flags taken as example in the sense that technically `Deno` namespace is not standard (as in not in the web spec) and if I'm not mistaken that's why all "non-standard" features are stored in this namespace

Maybe the flag I suggested was misnamed and should be something  more like `--standard-only`

**Comment by josephrocca** [comment]
Just a warning to anyone using the `delete globalThis.Deno` approach: You'll probably want to put that inside a static import, and then import that at the top of your script. Otherwise IIUC, static imports will "see" the Deno global, since they're hoisted and run before the the actual code in your `main.js`. (Someone please correct me if I'm wrong here - I haven't actually tested it.)
