### ISSUE TITLE
Add Error.cause to all Deno.errors instances

### ISSUE THREAD

**Issue by oles** [denoland/deno#24114]
I'm trying to improve the error handling in my code, and I'd like to provide some more specific error messages.

More specific, I'd like to show a message that there's likely an issue with the database connection, rather than just a generic connection error.

I could wrap all the `sql` calls in a try catch (which would be quite repetitive and error prone), or create a wrapper function (hard to do, as the `sql` function is quite advanced, especially to make it play nice with TypeScript).

I could also try to parse the `Error.stack`, but that also would be error prone.

Then it occurred to me that the `Error.cause` feature would be perfect for this, as I could likely just do an `instanceof` of it or just check its name/code and have what I need!

But currently the `Error.cause` is `undefined` on at least `ConnectionRefused`, and it seems to be the case on the other Deno error types too.

---

Example error output:

```
ConnectionRefused: Connection refused (os error 111)
    at async Object.connect (ext:deno_net/01_net.js:587:55)
    at cachedError (https://deno.land/x/postgresjs@v3.4.3/src/query.js:170:23)
    at new Query (https://deno.land/x/postgresjs@v3.4.3/src/query.js:36:24)
    at sql (https://deno.land/x/postgresjs@v3.4.3/src/index.js:113:11)
    at file:///home/<...>/postgres.test.ts:13:19 {
  name: "ConnectionRefused",
  code: "ECONNREFUSED"
}
```

```
$ deno --version
deno 1.44.0 (release, x86_64-unknown-linux-gnu)
v8 12.6.228.3
typescript 5.4.5
```

**Comment by bartlomieju** [comment]
What would the `cause` be set it?

**Comment by oles** [comment]
Based on the stack trace, I think it should be the `cachedError` - the error just before `ConnectionRefused` is thrown - but I'm not fully sure.

I've at least written code before that was similar to the currently first [MDN example](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/cause#rethrowing_an_error_with_a_cause), which would result in what I think - it seems.

```
try {
  connectToDatabase();
} catch (err) {
  throw new Error("Connecting to database failed.", { cause: err });
}
```

**Comment by bartlomieju** [comment]
Sorry I'm a bit confused here. Is this issue about adding `cause` field to all instance of `Deno.errors.*` classes? Or is it about the fact that if you pass one of these instances to `{ cause: err}` it doesn't work properly?

**Comment by oles** [comment]
Sorry for the confusion! I could likely have been clearer.

Adding a `clause` field to all instances of the `Deno.errors.*` is what I mean, yes :)

**Comment by bartlomieju** [comment]
@oles I'm still not sure how that would work - the error you see above is an instance of `Deno.errors.ConnectionRefused`. The way it is constructed is that when a relevant native (Rust) API raises it, it's translated to that instance. There's no underlying "cause" or other error that could be "linked". 

I think I'm missing a point here, so any further explanation would be helpful 😅

**Comment by oles** [comment]
I see, I may be thinking about this wrong.

I'd like to see what caused the error, as I think the `ConnectionRefused` is too vague. Perhaps it's better to add some details to it instead.

The more I think about it, the more it makes sense for Postgres.js to instead add a `cause` to its error(s) instead to wrap the `ConnectionRefused` 🤔
