### ISSUE TITLE
Invalid root certificates cause Deno to panic

### ISSUE THREAD

**Issue by Pii-USD** [denoland/deno#24137]
Version: Deno 1.37.2

Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: windows x86_64
Version: 1.37.2
Args: ["C:\\Program Files\\RStudio\\resources\\app\\bin\\quarto\\bin\\tools\\x86_64\\deno", "run", "--unstable", "--no-config", "--cached-only", "--allow-read", "--allow-write", "--allow-run", "--allow-env", "--allow-net", "--allow-ffi", "--importmap", "C:\\Program Files\\RStudio\\resources\\app\\bin\\quarto\\bin\\vendor\\import_map.json", "C:\\Program Files\\RStudio\\resources\\app\\bin\\quarto\\bin\\quarto.js", "install", "tinytex"]

thread 'main' panicked at cli\args\mod.rs:525:14:
Failed to add platform cert to root cert store: InvalidCertificate(BadEncoding)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by yazan-abdalrahman** [comment]
Hello @littledivy , @Pii-USD 
, could you clarify how I may re-produce the issue?

**Comment by bartlomieju** [comment]
We're no longer panicking, but instead return an error. We are discussing if we should just print a warning and skip loading such certificates

**Comment by Obscrts** [comment]
So is there a temproary work around for the problem?

**Comment by bartlomieju** [comment]
No, there is no workaround at the moment. Do you happen to use some very old certificate encoding?

**Comment by Obscrts** [comment]
I dont really know, how can I check this. Just installed VSCode and Quarto for my university project

**Comment by Obscrts** [comment]
Does [#25bb](https://github.com/denoland/deno/commit/25bb59d2ce83b03356a86013bb80107d29737b52) work as solution and if so how can I use the newer version of deno in my quarto project?

**Comment by littledivy** [comment]
@Obscrts you can try it with `deno upgrade --canary`
