### ISSUE TITLE
crypto.subtle.importKey with verify raises "Invalid key usages"

### ISSUE THREAD

**Issue by TheCarpetMerchant** [denoland/deno#24141]
deno 1.44.1 (release, x86_64-pc-windows-msvc)
v8 12.6.228.3
typescript 5.4.5

Calling this results in an error "Invalid key usages"
`crypto.subtle.importKey('pkcs8', buffer, {name: "RSASSA-PKCS1-v1_5", hash: "SHA-256"}, true, ["verify"]);`

Looking at https://github.com/denoland/deno/blob/9dc0e33e67d331c7d95b95d5a6eb380d4b9c732e/ext/crypto/00_crypto.js#L3346 it seems we need to provide "sign". But "verify" is marked in the docs as a valid value.

**Comment by lucacasonato** [comment]
Are you trying to import a private key instead of a public key?

**Comment by lucacasonato** [comment]
No response from OP, so closing. For future readers: if you are seeing this error: you are trying to import a private key in an API that can only import public keys, or a public key in an API that can only import private keys. Specifically, `"sign"` can only be used with a private key, and `"verify"` can only be used with a public key.
