### ISSUE TITLE
xattr API

### ISSUE THREAD

**Issue by MarkTiedemann** [denoland/deno#2415]
Would love to have an API for extended file attributes.

My use case is speeding up code formatting by making it incremental: Save the last time a file was formatted in an extended file attribute, then only re-format files which were modified again after having been formatted (instead of unnecessarily re-formatting all files).

API would be along the lines of:

```typescript
setFileAttr(filename: string, key: string, value: string): Promise<void>
getFileAttr(filename: string, key: string): Promise<string>
```

Permissions would be set -> write, get -> read.

**Comment by MarkTiedemann** [comment]
On Windows, you can easily use NTFS Alternate Data Streams to store meta data on files.

```typescript
function setFileAttr(filename: string, key: string, value: Uint8Array) {
  return Deno.writeFile(filename + ":" + key, value);
}

function getFileAttr(filename: string, key: string) {
  return Deno.readFile(filename + ":" + key);
}

function uint8ArrayEquals(a: Uint8Array, b: Uint8Array) {
  return a.length === b.length && a.every((val, idx) => val === b[idx]);
}

(async function test() {
  let a = new TextEncoder().encode(Date.now().toString());
  await setFileAttr(Deno.args[0], "LastTestRun", a);
  let b = await getFileAttr(Deno.args[0], "LastTestRun");
  if (!uint8ArrayEquals(a, b)) {
    console.error(a, "!==", b);
    Deno.exit(1);
  }
})();
```

Haven't found an easy way to do this on MacOS and Linux without native code yet.

**Comment by bartlomieju** [comment]
@MarkTiedemann this suggestion did not gained much traction; in an effort to reduce unwieldy number of open issues in the repo I'm going to close this one. I'd still be happy to merge a PR with implementation and tests, but this is not something core team will be working on.
