### ISSUE TITLE
[node] deasync package doesn't work in Deno CLI

### ISSUE THREAD

**Issue by nberlette** [denoland/deno#24158]
Version: Deno 1.44.1+22d34f7

Before I get started: I know, using a package like deasync is, well, not exactly best practice. However, there are still numerous packages on npm that rely on this package, and it does serve somewhat of a purpose. Somewhere.

Anyway, I would've thought `deasync` would be compatible with late models of Deno, considering it has support for napi and what not. After sorting out an issue with the bindings file not resolving, I got everything to import without any problem. But when I try to actually _use_ the exports of the package, Deno spits out a "Missing symbol" dylib error and immediately exits the process.

I'm running macOS 14.5 on an M1 Pro.

**Comment by devsnek** [comment]
There is documentation regarding the ABI stability of Node-API: https://nodejs.org/api/n-api.html#implications-of-abi-stability

`node.h`, `uv.h`, and `v8.h`, which seem to be used by that module, are not considered part of the stable ABI.
