### ISSUE TITLE
`Deno.open` successfully opens folders on linux

### ISSUE THREAD

**Issue by Reububble** [denoland/deno#24177]
Version: Deno 1.44.1
OS: Ubuntu 22.04 LTS
Pretty sure I've encountered this on rpi debian too.

Calling `Deno.open` on a folder returns `FsFile`. I expect it to throw. If my memory serves me correctly, it throws on windows.

I don't _think_ `Deno.open` is supposed to work on folders, regardless of operating system.

This causes code that works on windows to not work on linux. I'm okay to rewrite my code to always check that the file I'm opening is a file and not a folder, if this is in fact desired behaviour, but it is a pain.

**Comment by lucacasonato** [comment]
This is intentional behaviour. It follows the behaviour other programming languages and environments (like Rust and Node).
