### ISSUE TITLE
Way to resolve npm file imports like npm:lib/bin.wasm

### ISSUE THREAD

**Issue by utenma** [denoland/deno#24173]
Loading skia in the standard [ESM way ](https://www.npmjs.com/package/canvaskit-wasm#browser)
```ts
import CanvasKitInit, { CanvasKit } from 'npm:canvaskit-wasm/bin/canvaskit.js'

const canvasKit: CanvasKit = await CanvasKitInit({
  locateFile: (file) => Deno.env.get("HOME") + '/.cache/deno/npm/registry.npmjs.org/canvaskit-wasm/0.39.1/bin/' + file,
})
```

that's because the node library location has to be resolved for manuall import

is there a way to resolve the  absolute import path like `npm:canvaskit-wasm`  which in node would be `/node_modules/canvaskit-wasm`

the issue is that deno prefixes the version  the `0.39.1` which will change on new updates, so deno needs to tell which version it resolved

**Comment by lucacasonato** [comment]
So in theory you should be able to do.

```js
import CanvasKitInit, { CanvasKit } from "npm:canvaskit-wasm/bin/canvaskit.js";
import { fileURLToPath } from "node:url";

const canvasKit: CanvasKit = await CanvasKitInit({
  locateFile: (file) => fileURLToPath(import.meta.resolve(`npm:canvaskit-wasm/bin/${file}`)),
});
```

However, this is currently broken (https://github.com/denoland/deno/issues/24174).

So for now, you can do this workaround that is a bit more wordy:

```js
import CanvasKitInit, { CanvasKit } from "npm:canvaskit-wasm/bin/canvaskit.js";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const canvasKit: CanvasKit = await CanvasKitInit({
  locateFile: (file) => {
    const url = import.meta.resolve(`npm:canvaskit-wasm/bin/canvaskit.js`);
    const path = fileURLToPath(url);
    const dir = dirname(path);
    return join(dir, file);
  },
});
```

**Comment by lucacasonato** [comment]
I'll close this and continue tracking the underlying issue in https://github.com/denoland/deno/issues/24174.
