### ISSUE TITLE
Thoughts on native Deno build system? (npm alternative)

### ISSUE THREAD

**Issue by jbcpollak** [denoland/deno#242]
This might be a bit premature, but I'm wondering if you have thoughts on a Deno-native build system or if one is even needed. 

I realize package.json is no longer needed for dependency management, but what about for script running and other forms of production-ready tooling? One thing that has been a major pain in the Node/npm ecosystem has been maintaining configuration across multiple (many) projects and keeping them in sync. 

This might not be something deno itself would address, but do you have any thoughts on how you'd like to see that sort of tooling built out?

**Comment by vandie** [comment]
As part of [this](https://www.youtube.com/watch?v=M3BM9TB-8yA) talk. It's explained that Deno will include dependencies directly from a url, using symantic versioning, on first execution before being cached indefiniatly. As such I don't think that a NPM equivelent is needed. If I remember correctly though Ryan's example used unpkg.com as the include location and I'm sure NPM will probably try add url include locations for Deno users in future anyway.

**Comment by gillchristian** [comment]
Makefiles would be a good choice. It's an already existing tool that works well and is widely used.

**Comment by vandie** [comment]
@gillchristian if we used makefiles, we may have to manually write stuff for a makefile for each module we use as pulling it with the include could cause trouble with the secure nature of Deno. Am I wrong?

**Comment by ry** [comment]
If deno is still making progress in a few months we will start scoping out a plan for native modules. Right now it's too soon. Thanks for the discussion.
