### ISSUE TITLE
Some node api  may be broken in 1.44.2 ?

### ISSUE THREAD

**Issue by Xuhv** [denoland/deno#24209]
Version: Deno 1.44.2

I have some code like this
```ts
import { Features, transform } from "npm:lightningcss@1.24.1";

console.log(transform({
    filename: "x.ts",
    cssModules: true,
    code: new TextEncoder().encode(`.X { color: red; }`),
    include: Features.Nesting,
}));
```
With deno 1.44.1 and before, it works fine. but with 1.44.2, it throws an error
```
error: Uncaught (in promise) Error
console.log(transform({
            ^
```

lightningcss is a native library written in rust, so I guess the problem is related to node api.

**Comment by devsnek** [comment]
@Xuhv it looks like you'll need to use Buffer.from() for the code data you're passing.
