### ISSUE TITLE
Execute JS in "blocking" 

### ISSUE THREAD

**Issue by ry** [denoland/deno#2421]
https://docs.rs/tokio-threadpool/0.1.14/tokio_threadpool/fn.blocking.html
related:
https://github.com/denoland/deno/blob/856c44213b7faf507d4b481cfc170b2fd08f971a/cli/ops.rs#L525-L533
https://github.com/denoland/deno/blob/856c44213b7faf507d4b481cfc170b2fd08f971a/cli/tokio_util.rs#L29-L51

**Comment by bartlomieju** [comment]
@ry this is very outdated, with upcoming switch to new Tokio I deem it obsolete
