### ISSUE TITLE
 Ability to set start cwd of deno run

### ISSUE THREAD

**Issue by scarf005** [denoland/deno#24217]
like #14820, but for `deno run`. oftentimes being able to run script anywhere is useful. however, deno does not support setting cwd for deno run yet.

## Rationale

1. many existing scripts break when ran on different cwd as many tends to use relative path instead of `import.meta.dirname`.
2. to fix this issue. user has to use `deno task --cwd $TARGET_PATH $TASK_NAME`, however 
2-1. this forces user to add `deno.json` to target script
2-2. it breaks vscode_deno formatting (https://github.com/denoland/vscode_deno/issues/1123).

**Comment by lucacasonato** [comment]
You can also just `cd $new_cwd` to the directory you want to use as your CWD, and then run `deno run`?

```shell
(cd $new_cwd && deno run /home/user/my_script.ts)
```

**Comment by scarf005** [comment]
will it work on deno task?

**Comment by lucacasonato** [comment]
Yes.
