### ISSUE TITLE
Node streams hang when using `@aws-sdk/client-s3`

### ISSUE THREAD

**Issue by thesmart** [denoland/deno#24215]
Version: Deno 1.44.1

I am authoring a Deno library that will write a stream to an S3 bucket. It will write a few chunks, but then hangs. When I write the exact same code in Node, everything works as expected. There must be a major difference in how the streams implementations works.

I created a super simple test repository to demonstrate the issue:
https://github.com/thesmart/deno-streams-hang

Run the node version of the app:
```
$ node main.js
done:  1718409332487.jpg
```
This succeeds.

Run the deno version of the app:
```
$ deno run --allow-all main.ts
```
This hangs indefinitely, never writing more than three chunks. If I try sending a small file of only one chunk, it will succeed in Deno.

The script looks like this:
```typescript
import { PutObjectCommand, S3Client } from '@aws-sdk/client-s3';
import { createReadStream, statSync } from 'node:fs';

const S3_REGION = 'us-west-2';
const S3_BUCKET = 'my-bucket';
const client = new S3Client({ region: S3_REGION });

const fileStat = statSync("../test.jpg");
const readStream = createReadStream("../test.jpg");
const key = Date.now() + '.jpg';

// setup the command to write the file to S3
const cmd = new PutObjectCommand({
  Bucket: S3_BUCKET,
  Key: key,
  CacheControl: 'max-age=315360000, immutable',
  ContentLength: fileStat.size,
  ContentType: 'image/jpeg',
  Body: readStream,
});

client.send(cmd).then(() => {
  console.info("done: ", key);
}).catch((err) => {
  console.error(err);
});
```

**Comment by fushihara** [comment]
I was also writing a program to putObject to aws s3 and was having trouble with small files succeeding, but failing with 1MB files.
I ran deno upgrade --canary and it worked perfectly.
Thanks!

By the way, the way I create the readstream for Body is as follows.
I need the node functionality after all, so the difference may be minimal!

```
import { Readable } from "node:stream";
const fromFile= "any-file.txt"
const bucket = "any-bucket"
const fileHandler = await Deno.open(fromFile, { read: true });
const rs = Readable.from(fileHandler.readable);
const fileStat = await Deno.stat(fromFile);
const cmd = new PutObjectCommand({
  Bucket: bucket,
  Key: "upload-test.txt",
  Body: rs,
  ContentLength: fileStat.size,
});
```

**Comment by amir-s** [comment]
After some googling I ended up here.
I still have this issue with `v2.0.3`. If I stream a small file, it'll work. Otherwise it just hangs.

```
import { createReadStream } from "node:fs";
import { S3Client } from "npm:@aws-sdk/client-s3";
import { Upload } from "npm:@aws-sdk/lib-storage";

const s3 = new S3Client({
  //...
});

const upload = new Upload({
  client: s3,
  params: {
    Bucket: "files",
    Key: "test",
    Body: createReadStream("./file.txt"),
  },
});

upload.on("httpUploadProgress", (progress) => {
  console.log(`Uploaded ${progress.loaded} bytes`);
});

await upload.done();
```
For small file the log actually shows up. For big files, no logs are written and `upload.done()` promise never resolves to anything.
Am I doing something wrong?

**Comment by satyarohith** [comment]
@amir-s, how big is the big file?

I uploaded a 1gb file and it worked fine with the latest Deno `v2.0.4` and `v2.0.3`:
```
➜  deno --version
deno 2.0.3 (stable, release, aarch64-apple-darwin)
v8 12.9.202.13-rusty
typescript 5.6.2
➜  deno run -A main.mjs
Uploaded 5242880 bytes
Uploaded 10485760 bytes
Uploaded 15728640 bytes
...
Uploaded 1053818880 bytes
Uploaded 1059061760 bytes
Uploaded 1064304640 bytes
Uploaded 1069547520 bytes
Uploaded 1073741824 bytes
```

**Comment by amir-s** [comment]
huh!
Funny how it wasn't working before and now the same code works for me! I guess my provider was out or something!

Thank you for looking into it @satyarohith

**Comment by taseenb** [comment]
This still fails in Deno 2.1.4 but works in Node:

```
import { PutObjectCommand, S3Client } from '@aws-sdk/client-s3'

const s3 = new S3Client({
  ...
})

const uploadObject = async () => {
  try {
    const command = new PutObjectCommand({
      Bucket: BUCKET_NAME,
      Key: OBJECT_KEY,
      Body: OBJECT_CONTENT,
    })
    console.log('Uploading object...')

    const response = await s3.send(command)

    console.log('Upload successful:', response)
  } catch (error) {
    console.error('Error uploading object:', error)
  }
}

uploadObject()
```

I spent an entire day debugging this issue, and it turns out the problem lies with Deno. Unfortunately, this was the last thing I thought could be causing it.
