### ISSUE TITLE
C++ Integration

### ISSUE THREAD

**Issue by DevScholar** [denoland/deno#24224]
There is a crate called [`cxx`](https://cxx.rs/) that allows Rust users to call C++ ABI without having to modify and recompile the C++ library. 
This means that any Rust application (including Deno) can call libraries written in C++ and use more complex C++ ABIs rather than C ABIs to interact with libraries written in C++. 
Will the developers of Deno integrate cxx with Deno, which will make it possible to call C++ libraries directly using JavaScript, which can solve problems such as #3234 and so on?

By the way, I created [a Rust tutorial for JavaScript developers](https://github.com/DevScholar/rust-for-js-devs).

**Comment by lucacasonato** [comment]
You can use [Deno FFI](https://docs.deno.com/runtime/manual/runtime/ffi_api) to call between JavaScript and Rust/C/C++.
