### ISSUE TITLE
cli: import map support for `deno add`

### ISSUE THREAD

**Issue by scarf005** [denoland/deno#24264]
## Status Quo

using `deno add` will break existing `importMap` section in `deno.json`.

```sh
$ deno add @std/fs
```
```diff
// deno.json
{
-  "importMap": "import_map.json"
+  "importMap": "import_map.json",
+  "imports: {
+    "@std/fs": "jsr:@std/fs@^0.229.3",
+  }
}
```

## Suggestion

if `importMap` exists, attempt to update import map instead.

```diff
// import_map.json
{
  "imports: {
+    "@std/fs": "jsr:@std/fs@^0.229.3",
  }
}
```

## Others

I'm interested in opening a PR (pointers on where to look at would be appreciated!)

**Comment by lucacasonato** [comment]
I'm not sure we should implement this feature. But if we did do it, yes that is how I imagine it would work.

**Comment by scarf005** [comment]
> I'm not sure we should implement this feature.

could you explain why? while `imports` section is non-standard import map is browser standard.

**Comment by HasanAlrimawi** [comment]
> I'm not sure we should implement this feature. But if we did do it, yes that is how I imagine it would work.


If it should be, then I'm interested in contributing to the implementation or sharing my insights with @scarf005 on an approach I have in mind to implement this.
