### ISSUE TITLE
frequent, random HTTP import failure

### ISSUE THREAD

**Issue by scarf005** [denoland/deno#24260]
Version: deno 1.44.3+f4eead6 (canary, x86_64-unknown-linux-gnu)

## Issue

deno cache/download for the first time (in CI) frequently fails, randomly, unexpectedly.

## Steps to reproduce

`test.ts`
```ts
import { z } from "https://deno.land/x/catjazz@v0.0.2/mod.ts"
import { Command } from "https://deno.land/x/catjazz@v0.0.2/deps/cliffy.ts"
import { cliOptions } from "https://deno.land/x/catjazz@v0.0.2/utils/cli.ts"
import { timeit } from "https://deno.land/x/catjazz@v0.0.2/utils/timeit.ts"
import {
  applyRecursively,
  schemaTransformer,
} from "https://deno.land/x/catjazz@v0.0.2/utils/transform.ts"
import {
  type CataEntry,
  Entry,
  parseCataJson,
  readRecursively,
} from "https://deno.land/x/catjazz@v0.0.2/utils/parse.ts"
import { fmtJsonRecursively } from "https://deno.land/x/catjazz@v0.0.2/utils/json_fmt.ts"
import { match, P } from "https://deno.land/x/catjazz@v0.0.2/deps/ts_pattern.ts"
import { id } from "https://deno.land/x/catjazz@v0.0.2/utils/id.ts"
```

```sh
deno cache --reload --lock=deno.lock --lock-write test.ts
```

[![asciicast](https://asciinema.org/a/hEOUE3zjAYRCoooQQwHTjj0yb.svg)](https://asciinema.org/a/hEOUE3zjAYRCoooQQwHTjj0yb)

---

tracing log: [error.log](https://github.com/user-attachments/files/15900310/error.log)

**Comment by dworzycp** [comment]
We've also noticed this in our CI - seems to be related to the latest `1.44.3` release.

Downgrading deno to `1.44.2` fixes the problem, can do this with `deno upgrade --version 1.44.2`

**Comment by lucacasonato** [comment]
We are also noticing this internally. It is likely caused by 22f277969edac6673841ae0719ad97a89c5d04b1. We will pull 1.44.3 while we are investigating. Sorry for the troubles.

**Comment by scarf005** [comment]
> UPDATE: 1.44.3 has been pulled - installing Deno in CI should now install 1.44.2 again.

![image](https://github.com/denoland/deno/assets/54838975/5bbe7d1e-5a30-4468-bb99-ebe608acab05)

https://github.com/cataclysmbnteam/Cataclysm-BN/actions/runs/9582298163/job/26422268220

it looks like CI still installs 1.44.3 given version range 1.x, should i trigger new CI using empty commits instead of `re-run failed jobs`?

![image](https://github.com/denoland/deno/assets/54838975/0e8226e2-f766-45a6-bc7d-85a03e7b976a)

**Comment by scarf005** [comment]
> This should now be fixed @scarf005 - please try again by just re-running

![image](https://github.com/denoland/deno/assets/54838975/092e3fdb-3816-4ba9-a69f-93ec2164d3df)

[it works now](https://github.com/cataclysmbnteam/Cataclysm-BN/actions/runs/9582298163/job/26422659515), thanks for the quick action @lucacasonato
