### ISSUE TITLE
URLPattern with search parameters and base url doesn't work

### ISSUE THREAD

**Issue by irustm** [denoland/deno#24266]
Version: Deno 1.41, 1.44

```
deno repl   
Deno 1.44.2

> const p = new URLPattern("/api/data/", "http://localhost:8000")
p.exec("http://localhost:8000/api/data/?w=1&g=2")

null
```

```
// Chrome 126.0.6478.62

const p = new URLPattern("/api/data/", "http://localhost:8000")
p.exec("http://localhost:8000/api/data/?w=1&g=2")

{Object}
```

-----

```
Deno 1.44.2
exit using ctrl+d, ctrl+c, or close()
> const pattern = new URLPattern("/books/:id(\\d+)", "https://example.com");
console.log(pattern.test("https://example.com/books/123"))
true
console.log(pattern.test("https://example.com/books/123?d=1"))
false

```

```
// Chrome 126.0.6478.62

const pattern = new URLPattern("/books/:id(\\d+)", "https://example.com");
console.log(pattern.test("https://example.com/books/123"))
true
console.log(pattern.test("https://example.com/books/123?d=1"))
true
```

**Comment by yazan-abdalrahman** [comment]
@irustm ,

Hi, I'm new to Deno. Could you give me more information on this issue, including how to reproduce it and what is expected result?

**Comment by yazan-abdalrahman** [comment]
the issue when  exec query  in deno its return null ?
![image](https://github.com/user-attachments/assets/eed5cf28-6a5f-464f-9e86-7f0926616c27)
![image](https://github.com/user-attachments/assets/43312f75-9a35-4046-9d46-885e2bbd61ad)
but it works in chrome right?

**Comment by yazan-abdalrahman** [comment]
@lucacasonato @bartlomieju ,
I found the issue in building the URLPattern in deno it set the default value of search as None and in another fields, it put empty string, and I founded in chrome it but wildcard (*) so I added a code to add wildcard (*) when defaults None or empty.


![image](https://github.com/user-attachments/assets/258678e8-becd-481c-9463-1a6cd9b4fbcb)
![image](https://github.com/user-attachments/assets/4649eef8-e75e-43e6-942e-05cb9260ebe5)


![image](https://github.com/user-attachments/assets/fdcdc62b-95c3-444b-b575-8a2731ad4357)



But I still don't know where I can add tests for the code that I pushed. Please let me know where I can add tests for it.
