### ISSUE TITLE
Changing proxy server at runtime

### ISSUE THREAD

**Issue by josephrocca** [denoland/deno#24283]
For a current project, I need the ability to switch proxies at runtime for use with the Web standard fetch API. I'm assuming that this is not currently possible, since the docs only mention setting proxy servers via environment variables:

https://docs.deno.com/runtime/manual/basics/modules/proxies

> Deno supports proxies for module downloads and the Web standard fetch API.
> Proxy configuration is read from environmental variables: `HTTP_PROXY`, `HTTPS_PROXY` and `NO_PROXY`.

**Edit**: Oh, perhaps it's already possible via `Deno.env.set("foo", "bar")`? Or are those environment variables read only when the runtime initializes? I'll test this soon and report back.

**Comment by lucacasonato** [comment]
You can't do it with env vars, but you can do it with `Deno.createHttpClient`: https://deno.land/api@v1.44.4?s=Deno.createHttpClient&unstable=

**Comment by lucacasonato** [comment]
Closing as issue is resolved
