### ISSUE TITLE
can local module imported like this "vendor/colors/mod" ?

### ISSUE THREAD

**Issue by satishbabariya** [denoland/deno#2431]
```ts
import { bold, red, italic, bgBlue } from "vendor/colors/mod";

console.log(bgBlue(italic(red(bold("Hello world!")))));
```

output: 
```log
Uncaught NotFound: Cannot resolve module "vendor/colors/mod" from "/Users/satishbabariya/Downloads/deno_std-master/main.ts"
```

**Comment by ry** [comment]
```
import { bold, red, italic, bgBlue } from "vendor/colors/mod.ts";
```
you forgot the filename extension

**Comment by hayd** [comment]
Maybe the error output could suggest using .ts or .js as a compromise here.

**Comment by satishbabariya** [comment]
@ry yes I know, but is it possible to import local files without using extensions

**Comment by satishbabariya** [comment]
@ry also is there any future plan for dependency Vendoring, like making your own copy of the 3rd party packages your project, and use those packages from vendor folder. something like **godep**

**Comment by hayd** [comment]
You can already do this: specify DENO_DIR in the repo and commit the cached files.

**Comment by bartlomieju** [comment]
> @ry yes I know, but is it possible to import local files without using extensions

You can if file has no extension, otherwise specifying file extension is mandatory. That is one of main goals of Deno - not to introduce module resolving magic like in Node.

**Comment by Fenzland** [comment]
> @ry yes I know, but is it possible to import local files without using extensions
test.js
```javascript
import foo from './foo.js';
```
Is this a local import? If you just store this file and run with `deno run test.js`, this is a local import. But once you host this file on the internet and run with `deno run http://deno.land/test.js`, it's become a remote import. It's not a good idea to make difference between files run at local or remote on syntax level.
