### ISSUE TITLE
Subscription to an empty stream with the watch([]) method often causes a panic

### ISSUE THREAD

**Issue by chabanov** [denoland/deno#24327]
```
async function logs(engine: Deno.Kv, connector: Connector){
    try {
        const stream = engine.watch([]);
        for await (const entries of stream) {
            console.log(entries)
        }
    } catch (e) {
        console.log(e);
    }
}
```

Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos aarch64
Version: 1.42.4
Args: ["deno", "run", "-A", "--unstable-kv", "--watch", "main.ts"]

thread 'main' panicked

**Comment by yazan-abdalrahman** [comment]
@chabanov 
Hello, I attempted to reproduce it, but it works.
![image](https://github.com/denoland/deno/assets/145254650/085ea80c-24cf-4bb9-8a4b-c821c0296815)

**Comment by littledivy** [comment]
Cannot reproduce with latest Deno. Feel free to open another issue with the full backtrace if it still happens
