### ISSUE TITLE
bug: shebang line causes module docs to be omitted

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno#24339]
To reproduce:
1. Clone and `cd` into [`deno_std`](https://github.com/denoland/deno_std).
2. Generate docs for `@std/http/file-server` using `deno doc --html http/file_server.ts`. Note: `http/file_server.ts` starts contains a shebang line (see [here](https://github.com/denoland/deno_std/blob/fa330f69c34f5cd0148af191272561be76983779/http/file_server.ts#L1)).
3. Open docs using `open docs/index.html` and observe there is no module documentation, even though `http/file_server.ts` contains it (see [here](https://github.com/denoland/deno_std/blob/fa330f69c34f5cd0148af191272561be76983779/http/file_server.ts#L8-L33)).
4. Remove the shebang line from `http/file_server.ts`.
5. Generate and open docs again and observe there is now module documentation.

```
deno 1.44.4+09cc473 (canary, aarch64-apple-darwin)
v8 12.6.228.9
typescript 5.4.5
```

**Comment by MujahedSafaa** [comment]
I will take a look at this issue
