### ISSUE TITLE
Bug: TS "Infer return type" inserts file specifier

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/deno#24344]
When running the `Infer function return type` command on a function returning JSX we get the file specifier instead of  `import("preact/jsx-runtime").JSX.Element`:

```tsx
export function Foo(): import("file:///Users/marvinh/Library/Caches/deno/npm/registry.npmjs.org/preact/10.22.0/src/jsx").JSXInternal.Element {
  return <h1>hello world</h1>;
}
```

https://github.com/denoland/deno/assets/1062408/3b5cb706-9598-4e19-aad6-733af2435e41

## Steps to reproduce

1. Clone https://github.com/marvinhagemeister/deno-infer-type-repro
2. Open `mod.tsx` in vscode
3. Put the cursor inside the `Foo` identifier
4. Run the `infer function return type` quick fix

Version: Deno 1.44.4

**Comment by nayeemrmn** [comment]
Similar issue to #21643.
