### ISSUE TITLE
Deno.run() cannot get status when we run a invalid command

### ISSUE THREAD

**Issue by Fenzland** [denoland/deno#2434]
```javascript
(async ()=> {
	const process= Deno.run( { cmd: [ 'invalid-command', ], }, );
	
	console.log( await process.status(), );
})();
```

It should log { code: 127, success: false }. But in fact, an error thrown.

**Comment by Fenzland** [comment]
> `cmd` does not have a default value and crashes if `undefined` or not an array.

This issue is open before parameter name `args` breaking change to `cmd`. And I've forgot to update it. That's two different issues: 
* a non-exist command should give exit code 127.
* when user forget to pass cmd, should give a better error.

**Comment by barronwei** [comment]
@Fenzland Appreciate the distinction. I will keep this in mind!

**Comment by barronwei** [comment]
@Fenzland I believe exit code 127 is Bash specific. If the command dos not exist, Tokio does not successfully spawn a new process through `Command::spawn`, and results in an error. Anything to keep in mind when handling this, @ry?

**Comment by ry** [comment]
```
~/src/deno> cat x.js
(async ()=> {
	const process= Deno.run( { cmd: [ 'invalid-command', ], }, );

	console.log( await process.status(), );
})();
~/src/deno> deno run --allow-run x.js
error: Uncaught NotFound: No such file or directory (os error 2)
    at Object.jsonOpSync (core.js:247:13)
    at opRun (deno:cli/rt/40_process.js:19:17)
    at Object.run (deno:cli/rt/40_process.js:103:17)
    at file:///Users/rld/src/deno/x.js:2:22
    at file:///Users/rld/src/deno/x.js:5:3
```

This seems correct

**Comment by vegerot** [comment]
@ry 
1. imo it should return a `127` status code
2. How do we handle this?  Should we try/catch Deno.run?  Is there a command I can use to test whether the `cmd` exists _before_ calling `Deno.run`?
