### ISSUE TITLE
React helmet async breaking in 1.44.3

### ISSUE THREAD

**Issue by KyleJune** [denoland/deno#24342]
Version: Deno 1.44.3

I have the following import.

```ts
import reactHelmetAsync from "react-helmet-async";
const { HelmetProvider } = reactHelmetAsync;
```

Then when I try using the HelmetProvider as a react component, I get the following error.

![image](https://github.com/denoland/deno/assets/3241653/b8e7cd27-15c5-43c9-bb80-3d9c606f634b)

In my deno.json, here is the most relevant imports entries.

```
"react": "npm:react@18.3.1",
"@types/react": "npm:@types/react@18.3.1",
"react-helmet-async": "npm:react-helmet-async@2",
```

I also tried changing the react version to be less specific (react@18) but that didn't resolve the issue.

And here are my compiler options.

```
"compilerOptions": {
  "lib": ["esnext", "dom", "dom.iterable", "dom.asynciterable", "deno.ns"],
  "jsx": "react-jsx",
  "jsxImportSource": "react",
  "jsxImportSourceTypes": "@types/react"
}
```

I don't have the issue in 1.44.2 but do in 1.44.3 and 1.44.4. I found https://github.com/denoland/deno/issues/24293 when looking through the commits for the release that broke my code. It sounded like it might be related since the issue is with JSX. But I don't have multiple deno.json files.

I tried checking out each commit using `deno upgrade --canary --version`, I found the commit that introduces this issue I'm having is the same one for that other issue I linked to. So they seem to be related.

https://github.com/denoland/deno/commit/5dec3fd4b75a59574e5aeed4e927d8e3e0c1c683

**Comment by KyleJune** [comment]
In case it is relevant, here is my `.vscode/settings.json` file.

```json
{
  "deno.enable": true,
  "deno.lint": true,
  "deno.unstable": false,
  "deno.config": "./deno.jsonc",
  "deno.suggest.imports.hosts": {
    "https://deno.land": true
  },
  "files.associations": {
    "*.css": "tailwindcss"
  },
  "editor.formatOnSave": true,
  "editor.defaultFormatter": "denoland.vscode-deno",
  "editor.quickSuggestions": {
    "strings": true
  }
}

```

**Comment by bartlomieju** [comment]
CC @nayeemrmn please take a look

**Comment by KyleJune** [comment]
I just checked out the latest commit https://github.com/denoland/deno/commit/67dcd6db518446574d3a1e33f4ce536fcdc4fd25 for the other issue I linked to. I've verified that it doesn't resolve this issue. I used the following command: `deno upgrade --canary --version 67dcd6db518446574d3a1e33f4ce536fcdc4fd25` to check it out then reloaded my window.

I'm going to stick with 1.44.2 until this issue is resolved.

**Comment by nayeemrmn** [comment]
I reproduced this, it's because the `react-helmet-async` package as used here is depending on the import map entry for `react`, but the scope tracking I wrote for remote libs doesn't work for globally cached npm packages (it would work if you had `"nodeModulesDir": true`). Looking into it.

**Comment by KyleJune** [comment]
> I reproduced this, it's because the `react-helmet-async` package as used here is depending on the import map entry for `react`, but the scope tracking I wrote for remote libs doesn't work for globally cached npm packages (it would work if you had `"nodeModulesDir": true`). Looking into it.

Just asking because I'm not sure the reasons to or not to use the nodeModulesDir setting.

**Comment by nayeemrmn** [comment]
You should use it if you find that a package you're using depends on `node_modules` being there, and doesn't work otherwise. In this case though it's a mendable regression in the LSP.
