### ISSUE TITLE
workflow is failing with Deno

### ISSUE THREAD

**Issue by Boby900** [denoland/deno#24362]
Currently, I have just configured Deno for my Worflows/GH Actions and I am getting this TypeScript error.

PFA

minimal reproduction = https://github.com/Boby900/react-todo

![Screenshot (578)](https://github.com/denoland/deno/assets/111265239/2d21d673-8876-4a76-8bea-1ed5dc260b67)

**Comment by marvinhagemeister** [comment]
Please paste the contents of your `deno.json` file. Do you have something in there that maps `@/` to something?

**Comment by Boby900** [comment]
I don't have the deno.json file, I have only one .yml file for my GH
actions.

**Comment by Boby900** [comment]
https://github.com/Boby900/react-todo/blob/f177587d570c1b98eacab44773627a060b0f1a0b/.github/workflows/deno.yml#L1

**Comment by lucacasonato** [comment]
This `@/` mapping is coming from `paths` in `tsconfig.json`: https://github.com/Boby900/react-todo/blob/main/tsconfig.json. We do not support `tsconfig.json`'s path. @dsherret should we support this with sloppy imports?

**Comment by Boby900** [comment]
Okay, thanks for sharing this.
I will try to find any work around if I can get it working.
