### ISSUE TITLE
AsyncLocalStorage behaves differently from node

### ISSUE THREAD

**Issue by Corei13** [denoland/deno#24368]
The following code shows different output in deno vs node

```js
import { AsyncLocalStorage } from 'node:async_hooks'
import { nextTick } from 'node:process'

const store = new AsyncLocalStorage()

const test = n => console.log(n, "=>", store.getStore())

await store.run("data", async () => {
    test(9)
    queueMicrotask(() => test(10))
    nextTick(() => test(11))
    setTimeout(() => test(12), 0)

    await new Promise(r => setTimeout(r, 50))
    test(13)
})
```

```
➜ deno run test.mjs
9 => data
10 => undefined
11 => undefined
12 => undefined
13 => data

➜ node test.mjs    
9 => data
10 => data
11 => data
12 => data
13 => data
```

Looks like deno loses async context in `queueMicrotask` / `nextTick` / `setTimeout`.

**Comment by Corei13** [comment]
@devsnek should this be re-opened since #24402 was reverted?

**Comment by devsnek** [comment]
No I will reland it in the next couple days, it just needs a slight tweak.

**Comment by benbuzbee** [comment]
Not to zombie this 🧟🧟🧟🧟 but there is still a behavior difference with unhandledRejections (#30135) 

Shared here for future explorers and in case the same people (@devsnek) are passionate about this
