### ISSUE TITLE
`await promise` does not guarantee the yield of control flow

### ISSUE THREAD

**Issue by BlowaterNostr** [denoland/deno#24360]
```
deno 1.44.0 (release, aarch64-apple-darwin)
v8 12.6.228.3
typescript 5.4.5
```

Consider
```js
(async ()=>{
    for(;;) {
        await new Promise(res => {
            res(undefined)
        })
    }
})();

await new Promise(res => {
    setTimeout(() => {
        res(undefined)
    }, 0)
})
console.log("done")
```
`done` will never be printed because the infinite loop is never yielded despite there is an `await promise`

If I change it to
```js
(async ()=>{
    for(;;) {
        await new Promise(res => {
            setTimeout(() => {
                res(undefined)
            }, 0)
        })
    }
})();

await new Promise(res => {
    setTimeout(() => {
        res(undefined)
    }, 0)
})
console.log("done")
```
`done` is printed because by sleeping for 0 milisecond, 1 tick of the event loop is yielded.

Is this a bug or the desired behavior of JavaScript?

If so, the type `Promise` is not reliable to implement many async control flows.

For example, if I have
```js
async function f(a) {
    if(a > 10) {
        return true
    } else {
        return some_async_call()
    }
}
```
It's possible for `f` to have synchronized runtime behavior in the `true` branch despite that it returns a `Promise<true>`

**Comment by 0f-0b** [comment]
In browsers, an `await` operation queues a _microtask_ when the promise resolves to continue execution, while a `setTimeout` call queues a _task_ after some time to invoke the callback. Microtasks have a higher priority than tasks. That is, the event loop first runs every microtask before moving on to the next task. You can [read more about the event loop on MDN](https://developer.mozilla.org/docs/Web/API/HTML_DOM_API/Microtask_guide).

Deno tries to follow browser behavior as far as possible. In your code, the microtask enqueued by every `await` operation immediately executes another `await` operation, so there is always a microtask in the queue, and the next task is never visited.

**Comment by BlowaterNostr** [comment]
@0f-0b You are amazing! It helped me a lot!

**Comment by marvinhagemeister** [comment]
Yup, @0f-0b answered this perfectly. This is the way Promises work in JS.
