### ISSUE TITLE
Compiler refactor allows caching of "invalid" modules

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#2436]
Since the compiler refactor (856c44213b7faf507d4b481cfc170b2fd08f971a), modules get cached before the compiler completes and returns and diagnostics.  This can cause some strange behaviours.  For example:

```
$ deno run tests/error_003_typescript.ts
[0/1] Compiling file:///Users/kkelly/github/deno/tests/error_003_typescript.tsfile:///Users/kkelly/github/deno/tests/error_003_typescript.ts:2:1 - error TS2552: Cannot find name 'consol'. Did you mean 'console'?

2 consol.log("hello world!");
  ~~~~~~

  $asset$/lib.deno_runtime.d.ts:1248:15
    1248 declare const console: consoleTypes.Console;
                       ~~~~~~~
    'console' is declared here.

$ deno run tests/error_003_typescript.ts
file:///Users/kkelly/github/deno/tests/error_003_typescript.ts:2:0
consol.log("hello world!");
^
Uncaught ReferenceError: consol is not defined
    at file:///Users/kkelly/github/deno/tests/error_003_typescript.ts:2:1
```

Previously, the compiler would exit the process before the modules would cache, providing consistent behaviour.

**Comment by ry** [comment]
That’s odd . Do that mean the compiler is emitting code even on failure? Maybe it’s because I removed the “emitSkipped” check. In any case - good catch!

**Comment by kitsonk** [comment]
The compiler by default emits on failure yes, `--noEmitOnError` changes the behaviour.  Of course that would still be a problem, because we have those errors we are ignoring though.  So it is more complex issue to try to figure out.
