### ISSUE TITLE
Support shebang line (ES14)

### ISSUE THREAD

**Issue by fzn0x** [denoland/deno#24379]
Shebang line caused several packages issue, the reason is Deno couldn't support running with executable script.

Working in other runtimes:

```js
#!/usr/bin/env bun

console.log("Hello, world!");
```

```js
#!/usr/bin/env node

console.log("Hello, world!");
```

In Deno:

```js
#!/usr/bin/env deno

console.log("Hello, world!");
```

You will receive:

```sh
$ ./index.js
error: unrecognized subcommand './index.js'

Usage: deno [OPTIONS] [COMMAND]

For more information, try '--help'.
```

**Comment by fzn0x** [comment]
> Deno supports shebangs, see docs for details: https://docs.deno.com/runtime/tutorials/hashbang

Thanks, could we shorthand `#!/usr/bin/env -S deno run --allow-env` to `#!/usr/bin/env -S deno` ?

**Comment by bartlomieju** [comment]
> After shorthand you could handle more permissions if needed
> 
> ```js
> #!/usr/bin/env deno --allow-net
> 
> console.log("Hello, world!");
> ```

This doesn't work, you need to use `-S` to pass argument to the interpreter, so the only shortcut would be the removal of `run` subcommand from the shebang invocation.
