### ISSUE TITLE
Deno task "sh -c" doesn't pass args to command

### ISSUE THREAD

**Issue by Justiceleeg** [denoland/deno#24370]
Version: Deno 1.44.4

deno.json
```
{
	"tasks": {
		"test-echo": "sh -c echo hi"
	}
}
```

Expected: 
Running the above task should print 'hi' to the console but it only appears to be running `echo` without args. `pwd` works (as it has no args).

Actual:
<img width="408" alt="Screenshot 2024-06-29 at 19 42 34" src="https://github.com/denoland/deno/assets/24969444/2c9efe93-7a2d-44bd-9af1-0f6a360497c9">
All commands will run as if submitted with no args.

Related Documentation:
[https://docs.deno.com/runtime/manual/tools/task_runner#built-in-commands](https://docs.deno.com/runtime/manual/tools/task_runner#built-in-commands)

**Comment by dsherret** [comment]
I get the following output in a regular shell:

```
~$ sh -c echo hi

$ sh -c 'echo hi'
hi
```

I believe you're intending to surround the argument in quotes:

```json
{
	"tasks": {
		"test-echo": "sh -c 'echo hi'"
	}
}
```
