### ISSUE TITLE
`deno install` should install NPM dependencies that are contained in JSR packages you depend on

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#24394]
```ts
// main.ts

import "jsr:@reexport/chalk";
```

```jsonc
// package.json
{
  "dependencies": {
    "cowsay": "*"
  }
}
```

The JSR package `@reexport/chalk` contains the line `import "npm:chalk@5"`.

With `DENO_FUTURE=1` you can run `deno install` in this folder, and we'll create a `node_modules/` folder that contains just `cowsay`.

I think we should also install `chalk` in `node_modules/`.

**Comment by dsherret** [comment]
On `deno install`, we should:

1. Ensure that jsr packages in a deno.json are analyzed and npm deps installed
2. Follow `exports` in packages and ensure all jsr packages are analyzed and npm deps installed

**Comment by lucacasonato** [comment]
This was already fixed.
