### ISSUE TITLE
npm:moment's typings not working since Deno 1.44.3.

### ISSUE THREAD

**Issue by J053Fabi0** [denoland/deno#24446]
1.44.2:
![image](https://github.com/denoland/deno/assets/12930717/00b0513d-05f7-49c9-8767-d260b0717c04)

1.44.3 and 1.44.4:
![image](https://github.com/denoland/deno/assets/12930717/d9c16329-6630-4c19-9a43-15d9ab94873c)

**Comment by guy-borderless** [comment]
I see I probably just [filed a duplicate](https://github.com/denoland/deno/issues/24451)

**Comment by dsherret** [comment]
@guy-borderless I believe they're distinct issues.

**Comment by dsherret** [comment]
It's working for me now in 1.45.4.

![image](https://github.com/user-attachments/assets/9728b7e9-dbb9-4726-96f1-81ad416e1230)
