### ISSUE TITLE
Bug: Type `URLPattern` cannot be found in canary builds

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/deno#24459]
All canary builds in the fresh repo are failing with an error that the `URLPattern` type cannot be found anymore. Did something change related to that?

See https://github.com/denoland/fresh/actions/runs/9832171319/job/27140579673?pr=2585

Version: Deno 1.44.4 (canary)

**Comment by bartlomieju** [comment]
I’m having trouble figuring out the problem here. 

Type declarations for `URLPattern` are present (see `cli/tsc/dts/lib.dom.extras.d.ts`) and we have unit tests that are type-checking it (`tests/unit/urlpattern_test.ts`).
