### ISSUE TITLE
ctime value differs from node in windows deno

### ISSUE THREAD

**Issue by fushihara** [denoland/deno#24453]
I am writing software to display timestamps of files.
I am porting a program that was running on node to deno, and I noticed that the ctime value is different between node and deno.
I think this is a windows NTFS specific problem.

The test code is as follows
Please specify a file that was created long ago and edited many times, not a new file.

```ts
import { format } from "jsr:@std/datetime@0.224.0/format"
import { stat, Stats } from "node:fs"
const fromFile = "ANYFILE";
const localFileStat = await Deno.stat(fromFile)
const nodeStat =await  new Promise<Stats>((resolve, reject) => {
  stat(fromFile, (err, stat) => {
    if (err) {
      reject(err);
    } else {
      resolve(stat);
    }
  });
});
console.log(`${format(nodeStat.ctime, "yyyy-MM-dd HH:mm:ss:SSS")} node:ctime`);
console.log(`${format(nodeStat.mtime, "yyyy-MM-dd HH:mm:ss:SSS")} node:mtime`);
console.log(`${format(nodeStat.atime, "yyyy-MM-dd HH:mm:ss:SSS")} node:atime`);
console.log(`${format(nodeStat.birthtime, "yyyy-MM-dd HH:mm:ss:SSS")} node:birthtime`);

console.log(`${format(localFileStat.atime!, "yyyy-MM-dd HH:mm:ss:SSS")} Deno:atime`);
console.log(`${format(localFileStat.birthtime!, "yyyy-MM-dd HH:mm:ss:SSS")} Deno:birthtime`);
console.log(`${format(localFileStat.mtime!, "yyyy-MM-dd HH:mm:ss:SSS")} Deno:mtime`);
```

The results are as follows.
I found it strange that the ctime and mtime of node are exactly the same value.

```
2024-07-06 17:52:28:857 node:ctime
2024-07-06 17:52:28:857 node:mtime
2024-07-06 21:27:15:750 node:atime
2024-07-06 17:52:21:438 node:birthtime

2024-07-06 21:27:15:750 Deno:atime
2024-07-06 17:52:21:438 Deno:birthtime
2024-07-06 17:52:28:857 Deno:mtime
```

Looking at the Deno source code, ctime refers to the exact same value as mtime.
https://github.com/denoland/deno/blob/main/ext/node/polyfills/_fs/_fs_stat.ts#L293

Here is the result of running the equivalent code in node
The mtime and ctime values are different.

```
2024-07-06 17:52:43:446 node:ctime
2024-07-06 17:52:28:857 node:mtime
2024-07-06 21:27:15:751 node:atime
2024-07-06 17:52:21:438 node:birthtime
```

The following is the result of displaying the timestamps with SetMace, a tool that displays Windows file system details.
The decimal point of milliseconds differs, but we consider this to be no problem within the range of rounding error.

```
$ SetMace.exe "ANYFILE" -d
STANDARD_INFORMATION
CreationTime: 2024-07-06 08:52:21:438:1243
LastWriteTime: 2024-07-06 08:52:28:857:4623
ChangeTime(MFT): 2024-07-06 08:52:43:445:7160
LastAccessTime: 2024-07-06 12:27:15:750:6429
```

The ctime value in nodejs refers to the date in ChangeTime (MFT).
We expect to get the equivalent value in deno's node:fs package.
I would also like to add ctime to the `FileInfo` type in the return value of `Deno.stat(fromFile)`.

Checking the official Deno compatibility list, there is no mention of stat in the fs section.
![image](https://github.com/denoland/deno/assets/1039534/efa37f62-d753-49e3-ab4c-c5e6acaf1831)
https://docs.deno.com/runtime/manual/node/compatibility/#:~:text=node%3Afs,-%E2%84%B9%EF%B8%8F

SetMace is the repository for
https://github.com/jschicht/SetMace

The versions of deno and node are as follows

```
>deno --version
deno 1.44.4 (release, x86_64-pc-windows-msvc)
v8 12.6.228.9
typescript 5.4.5

>node --version
v22.4.0
```

**Comment by fushihara** [comment]
In node, the last four constructors of the BigIntStats class each store a different timestamp value.
https://github.com/nodejs/node/blob/main/lib/internal/fs/utils.js#L565

I assume the process is called from the following location
I couldn't understand the code from c++.
https://github.com/nodejs/node/blob/main/lib/fs.js#L1661
https://github.com/nodejs/node/blob/main/src/node_file.cc#L1203

**Comment by lczerniawski** [comment]
I'm taking this one :)
