### ISSUE TITLE
Invalid Arg at eventLoopTick

### ISSUE THREAD

**Issue by rawkakani** [denoland/deno#24452]
Hi, I hope you're doing well 

I have been using 

`import { transform } from "npm:lightningcss"` 
quite well until i updated to 1.44.4
and got this error

```
 at eventLoopTick (ext:core/01_core.js:168:7) {
  code: "InvalidArg"
}
```

I tried the recommended way on the documentation using. 

`import init, { transform } from 'https://esm.run/lightningcss-wasm';` and got the below error

```
LinkError: WebAssembly.instantiate(): Import #19 "env" "__getrandom_custom": function import requires a callable
    at ext:deno_fetch/26_fetch.js:469:20
    at eventLoopTick (ext:core/01_core.js:168:7)
```

I have attemtped to downgrade to 1.44.3 and 1.44.2 and get the same error

Version: Deno 1.44.4

**Comment by marvinhagemeister** [comment]
Which operating system are you on? Tried to reproduce the described error on macOS but wasn't able to. It works as expected there.

**Comment by rawkakani** [comment]
currently working on macOS Sanoma 14.6 M2

**Comment by rawkakani** [comment]
all good, thank you, upgraded to 1.45.2
