### ISSUE TITLE
Feat: Support passing watch files to `deno test`

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/deno#24465]
The `deno test` command can currently only watch files that are part of the module graph. It would be great if we could also pass additional files/folders in the same way as `deno run --watch=some-dir/`. This would align both commands and would make developing on Deno's internal JS easier.

**Comment by lczerniawski** [comment]
I'm taking this one :)

**Comment by eliphazb** [comment]
@marvinhagemeister I think this issue can be closed because is already merged
