### ISSUE TITLE
Is Deno stable yet?

### ISSUE THREAD

**Issue by amiteshore** [denoland/deno#2447]
Should I use Deno before v1.0.0, on production?

**Comment by ry** [comment]
No - https://deno.land/manual.html#disclaimer

We'll stabilize some APIs when 1.0 is released (which I'm aiming to in a few months).

**Comment by cdbattags** [comment]
Status for 1.0? I think all that's left for adoption (at least for me) is that final trust marker and a halfway stable abi/stdlib/API.

**Comment by ry** [comment]
1.0 is still some weeks away. The major feature we’re missing is Chrome DevTools support for debugging. There are also a couple large ongoing refactors that ought to complete. I will post updates at the top of this issue:

https://github.com/denoland/deno/issues/2473
