### ISSUE TITLE
Add and use `assertRejects` for testing

### ISSUE THREAD

**Issue by kevinkassimo** [denoland/deno#2449]
Tests like the following is non-robust (if error does not even happen).
https://github.com/denoland/deno/blob/60d452264198adb3da4820236cf8ea35d33486cd/js/chown_test.ts#L45-L50

Instead, we can create a function like `assertRejects` that can be used like
```ts
const error = await assertRejects(opToFail);
```

This could be a good first issue

**Comment by kitsonk** [comment]
I would personally prefer `assertThrowsAsync` and follow the API pattern of `assertThrows()`. We have tried to abstract ourselves from Promises where possible to date.

**Comment by zekth** [comment]
Agree with @kitsonk

**Comment by kitsonk** [comment]
Also, `deno_std` already includes the assertion of [`assertThrowsAsync`](https://github.com/denoland/deno_std/blob/7daa887b09d4662710ad58e68de1a01a318455bb/testing/asserts.ts#L281-L286).

**Comment by bartlomieju** [comment]
Seems like `assertThrows` and `assertThrowsAsync` are working fine, closing
