### ISSUE TITLE
`deno upgrade` fails in broken workspace setting in v1.45

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#24517]
Version: Deno v1.45.0

```
$ deno upgrade
error: Could not find package.json for workspace member in 'file:///Users/ib/dev/deno_workspace_examples/buzz/'.
```

Reproduction: https://github.com/bartlomieju/broken_deno_upgrade_in_workspace

**Comment by dsherret** [comment]
This is essentially just https://github.com/denoland/deno/issues/20729
