### ISSUE TITLE
Valid Typescript Syntax Being Marked as Invalid (new bug introduced by v1.44.3)

### ISSUE THREAD

**Issue by johnstonmatt** [denoland/deno#24513]
Version: Deno `1.44.4`
Version where bug was introduced: Deno `1.44.3`
---

[**Demo Repo**](https://github.com/polyseam/deno-demo-obj-literal-error)

We've discovered a bug where valid typescript is being flagged as invalid. I am not entirely certain what about deno changed to introduce the bug, but it was definitely not present in `1.44.2` and definitely is present in `1.44.3`.

The issue relates to passing an object literal into a constructor where there are valid properties which are designated as invalid yielding the error:

```
Object literal may only specify known properties, and 'propertyName' does not exist in type 'ObjectLiteralArgument'.deno-ts(2353)
⚠ Error (TS2353)
```

Please visit this repo for more details and a guide for reproducing the error:
https://github.com/polyseam/deno-demo-obj-literal-error

**Comment by nathanwhit** [comment]
Hello, thanks for the report and reproducer! This should be fixed in `main` and will be in the next release (which is scheduled for today). So you can use a canary build right now (`deno upgrade --canary`), or wait for the release.

Let us know if it's still an issue in the new release!
