### ISSUE TITLE
cache --allow-scripts ? undocummented and is breaking examples such as deno react example

### ISSUE THREAD

**Issue by AddictArts** [denoland/deno#24518]
Version: Deno 1.45.0

The new, maybe., undocumented option for cache is breaking existing working code. It is fine to have a breaking change, but this is not listed anywhere and a `deno cache --help` does not have it listed.

```shell
warning: Packages contained npm lifecycle scripts (preinstall/install/postinstall) that were not executed.
    This may cause the packages to not work correctly. To run them, use the `--allow-scripts` flag with `deno cache`
    (e.g. `deno cache --allow-scripts=pkg1,pkg2 <entrypoint>`):
```

1. Clone the deno vite example at https://github.com/denoland/examples/tree/main/with-react
2. run `deno task dev` or `deno task build`

Why is there nothing listed about this, checked release notes, etc.

**Comment by nathanwhit** [comment]
Hello!

Yes the `--allow-scripts` flag is new in `1.45.0`.

> this is not listed anywhere

1.45.0 was just released (~an hour ago), but we haven't published the blog post yet. The blog post will explain more about the feature, once it's published. 

It is mentioned in the release notes on github indirectly in this line

> feat(node): Support executing npm package lifecycle scripts
(preinstall/install/postinstall)

which is where the flag was added.

> deno cache --help does not have it listed

It should be in there, I double checked on my machine and it is listed in the help:

```
      --allow-scripts[=<PACKAGE>...]
          Allow running npm lifecycle scripts for the given packages. Note: Scripts will only be executed when using a node_modules directory (`--node-modules-dir`)
```

Can you share your help output, if it's not there?

>  new, maybe., undocumented option for cache is breaking existing working code

It's only a warning message, so it shouldn't impact the behavior of any code. Does the react example function incorrectly or differently now, or is there just the extra warning messages? (it works properly on my machine, but your setup may be different).

---

The warning message definitely is more annoying than it should be, and (like in your case) it's not particularly helpful. I've already started working on making it less noisy and reducing how often it shows, so in the next patch release this should be resolved.

**Comment by AddictArts** [comment]
@AaronO I am working on more details, happened in a docker container using deno:latest. And what worked there on 1.44.4 stopped working when it picked up 1.45.0.

The tasks all use `--node-modules-dir` so the warning and behavior should be exempted right? These flag seems like it is for `import "npm:..." cases without `--node-modules-dir`?

**Comment by nathanwhit** [comment]
> The tasks all use --node-modules-dir so the warning and behavior should be exempted right? These flag seems like it is for import "npm:..." cases without --node-modules-dir`?

It actually sort of the opposite, `--allow-scripts` only works when `--node-modules-dir` (or the equivalent deno.json config) is true. So the warning isn't incorrect, but it's not helpful (and just noisy) because those packages happen to work fine without their scripts being run (which isn't always the case).

**Comment by dsherret** [comment]
What's breaking here? Previously it never ran the post install scripts, which is what it still does when the flag isn't specified and I don't believe a new warning is a breaking change.
