### ISSUE TITLE
Deno cache doesn't always list all deps in deno.lock

### ISSUE THREAD

**Issue by brc-dd** [denoland/deno#24536]
Version: deno 1.45.0+f950f59 (canary, aarch64-apple-darwin)

Minimal Reproducible Example

- https://github.com/brc-dd/deno-cache-not-stable
- Clone the repo, run:
   ```sh
   deno cache --reload --lock=deno.lock foo.ts bar.ts
   ```
- Notice that there is no change in deno.lock.
- Now run:
   ```sh
   deno cache --reload --lock=deno.lock bar.ts
   ```
- Now `jsr:@std/encoding@1.0.0-rc.2` is properly listed as dependency of `@cliffy/ansi@1.0.0-rc.5` in deno.lock

If I change `jsr:@std/http@0.224.5` in foo.ts to `jsr:@std/http@1.0.0-rc.3` then also the first command works fine. Not sure, but seems like a weird edge case.

---

Posting foo.ts/bar.ts here for completeness:

```ts
// foo.ts
import {} from 'jsr:@std/http@0.224.5'

export {}
```

```ts
// bar.ts
import {} from 'jsr:@cliffy/prompt@1.0.0-rc.5'

export {}
```

**Comment by dsherret** [comment]
```diff
> git diff
diff --git a/deno.lock b/deno.lock
index 8ce4f23..7e58a59 100644
--- a/deno.lock
+++ b/deno.lock
@@ -22,7 +22,10 @@
     },
     "jsr": {
       "@cliffy/ansi@1.0.0-rc.5": {
-        "integrity": "85a4dba4da5d8278dcdfeea98672cd15706c244833f82edc60c61f410d9fc1a9"
+        "integrity": "85a4dba4da5d8278dcdfeea98672cd15706c244833f82edc60c61f410d9fc1a9",
+        "dependencies": [
+          "jsr:@std/encoding@1.0.0-rc.2"
+        ]
       },
       "@cliffy/internal@1.0.0-rc.5": {
         "integrity": "1e8dca4fcfba1815bf1a899bb880e09f8b45284c352465ef8fb015887c1fc126"
```

**Comment by dsherret** [comment]
Seems like a bug in deno_graph where it doesn't report this as a dependency.

**Comment by dsherret** [comment]
Thanks for the great reproduction!
