### ISSUE TITLE
deno ffi regression (?) in 1.44.3 when running in docker

### ISSUE THREAD

**Issue by teidesu** [denoland/deno#24547]
the smallest repro i could make:
https://gist.github.com/teidesu/199abcd47a3fb494564a2c41965be5ad

on linux amd64 host, put these 2 files in the same directory, and run 
```bash
docker run --rm $(docker build -q .)
```

then, change deno version to 1.44.2 in dockerfile and run the same command again

on 1.44.3 the code fails with a random error from the library being ffi-ed (e.g. `pcre2_substitute_8 error: -8`. sometimes it's different error code, but always `PCRE2_ERROR_NULL` or `PCRE2_ERROR_UTF8_ERR` family)
and on 1.44.2 everything works fine and outputs `goodbye world` correctly

on the other hand, everything seems to work fine when running outside docker or on arm64 linux, so i'm not really sure what could be the issue here... could be that my bindings are wrong in some way that worked fine before some ffi improvements

the issue is also present in 1.44.4, 1.45.0, 1.45.1 and latest (as of writing) canary version

**Comment by 0f-0b** [comment]
These are the relevant function signatures copied from the [documentation](https://pcre2project.github.io/pcre2/doc/html/pcre2api.html). `PCRE2_SIZE` is defined as `size_t`.

```c
pcre2_code* pcre2_compile(
  PCRE2_SPTR pattern,
  PCRE2_SIZE length,
  uint32_t options,
  int* errorcode,
  PCRE2_SIZE* erroroffset,
  pcre2_compile_context* ccontext
);
int pcre2_substitute(
  const pcre2_code* code,
  PCRE2_SPTR subject,
  PCRE2_SIZE length,
  PCRE2_SIZE startoffset,
  uint32_t options,
  pcre2_match_data* match_data,
  pcre2_match_context* mcontext,
  PCRE2_SPTR replacement,
  PCRE2_SIZE rlength,
  PCRE2_UCHAR* outputbuffer,
  PCRE2_SIZE* outlengthptr
);
```

This patch to `main.ts` fixes the issue where `size_t` is confused with `uint32_t`.

```diff
@@ -7,13 +7,13 @@
       parameters: [
           'pointer',
           'buffer',
-          'u32',
-          'u32',
+          'usize',
+          'usize',
           'u32',
           'pointer',
           'pointer',
           'buffer',
-          'u32',
+          'usize',
           'buffer',
           'pointer',
       ],
@@ -25,11 +25,11 @@
 const PCRE2_SUBSTITUTE_EXTENDED = 0x00000200
 const PCRE2_SUBSTITUTE_OVERFLOW_LENGTH = 0x00001000
 
-const lastErr = new Uint32Array(1)
+const lastErr = new Int32Array(1)
 const lastErrPtr = Deno.UnsafePointer.of(lastErr)
-const lastErrOffset = new Uint32Array(1)
+const lastErrOffset = new BigUint64Array(1)
 const lastErrOffsetPtr = Deno.UnsafePointer.of(lastErrOffset)
-const outLen = new Uint32Array(1)
+const outLen = new BigUint64Array(1)
 const outLenPtr = Deno.UnsafePointer.of(outLen)
 
 export function compile(pattern: string): Deno.PointerValue {
@@ -68,17 +68,17 @@
       PCRE2_SUBSTITUTE_EXTENDED |
       PCRE2_SUBSTITUTE_OVERFLOW_LENGTH
 
-  outLen[0] = resultBuf.byteLength
+  outLen[0] = BigInt(resultBuf.byteLength)
   let res = library.symbols.pcre2_substitute_8(
       code,
       subjectBuf,
-      subjectBuf.byteLength,
-      0,
+      BigInt(subjectBuf.byteLength),
+      0n,
       flags,
       null,
       null,
       replacementBuf,
-      replacementBuf.byteLength,
+      BigInt(replacementBuf.byteLength),
       resultBuf,
       outLenPtr,
   )
@@ -87,7 +87,7 @@
       throw new Error(`pcre2_substitute_8 error: ${res}`)
   }
 
-  return new TextDecoder().decode(resultBuf.slice(0, outLen[0]))
+  return new TextDecoder().decode(resultBuf.slice(0, Number(outLen[0])))
 }
 
 const re = compile('hello')
```

**Comment by teidesu** [comment]
> `PCRE2_SIZE` is defined as `size_t`.

i swear i checked that it didn't work with `usize`-s either, but i guess i missed smth 🤦‍♀️
yeah, with your patch everything does seem to work, tysm!

idk if the issue should be closed though, as it's still kinda weird that it works fine without usize-s outside docker...

**Comment by littledivy** [comment]
Closing as this seems resolved. It's hard to say why `u32` worked on host machine; its UB to pass invalid type after all.
