### ISSUE TITLE
Angular never gets started

### ISSUE THREAD

**Issue by rroblf01** [denoland/deno#24549]
Version: Deno 1.45.1

When trying to run a deno task serve on an Angular project, it never starts.
![imagen](https://github.com/user-attachments/assets/cb5dd106-bc05-47b8-8422-a0880615d541)

Steps to reproduce the error:
(In the example I clone the repository I was working on, but the same thing happens with any Angular project.)
```
git clone https://github.com/rroblf01/ricardorobles.git && cd ricardorobles

DENO_FUTURE=1 deno install --allow-scripts
DENO_FUTURE=1 deno task start
```

It will stay in an infinite loop

**Comment by rroblf01** [comment]
This bug still occurs on Deno 2.0.0-rc.0

![imagen](https://github.com/user-attachments/assets/bf8dfd86-27a2-4214-8f5d-c5734f8072af)

**Comment by littledivy** [comment]
Closing as duplicate of #22995. Let's continue investigation there.
