### ISSUE TITLE
`Deno.readTextFileSync` (and other File system APIs) throws `NotFound` when using a relative path. Works with an absolute path. 

### ISSUE THREAD

**Issue by mikeyamato** [denoland/deno#24560]
Version: Deno `1.44.4`

I'm using a [file system api](https://docs.deno.com/deploy/api/runtime-fs/) and see in the documentation that the "path can be a relative or absolute." However, when using a relative path an error is thrown. No error is thrown when using an absolute path.

### Example

```js
Deno.readTextFileSync('./airport-schema.graphql') // <-- throws error (see image below)

Deno.readTextFileSync('/absolute/path/to/file/airport-schema.graphql') // <-- works
```

### Error
<img width="810" alt="Screenshot 2024-07-12 at 11 27 25" src="https://github.com/user-attachments/assets/5a2526b0-41a9-4461-a137-aa8b23cd4588">

**Comment by dsherret** [comment]
What happens if you do?

```ts
const filePath = Deno.cwd() + "./airport-schema.graphql";
console.log(filePath);
const fileText = Deno.readTextFileSync(filePath);
```

**Comment by mikeyamato** [comment]
`filePath` logs the following:
```js
/Users/yams/Documents/Repo/JavaScript/burbank-airport-flight-info-server./airport-schema.graphql
```
2 things I see
- The dot prefix to the file from the first line should be removed. This is a non-issue. 
- What returns isn't the full path to the file, `airport-schema.graphql`. It's nested in additional folders. This is the full path: `/Users/yams/Documents/Repo/JavaScript/burbank-airport-flight-info-server/src/api/graphql/schemas/airport-schema.graphql`. Running `Deno.cwd()` misses `src/api/graphql/schemas/`.

**Comment by dsherret** [comment]
> The dot prefix to the file from the first line should be removed. This is a non-issue.

Sorry, I forgot I wasn't doing path.join there, but yeah it shouldn't have a dot.

> What returns isn't the full path to the file, airport-schema.graphql. It's nested in additional folders. 

Ok, that gives the cwd of the process. Whatever is launching Deno isn't launching it in that directory.

**Comment by mikeyamato** [comment]
> Whatever is launching Deno isn't launching it in that directory.

Then most likely this isn't a bug but rather a local setup issue. I'll look into this on my end. Let me close this ticket. Thanks for the assistance.

**Comment by mikeyamato** [comment]
JFYI, since I'm not exactly sure how to resolve my setup (using zshrc so not sure if that's the cause) but I'm using an alternate solution to get the absolute path vs hard keying them. Got the idea from [SO](https://stackoverflow.com/a/61829368/8378893) and what @dsherret commented earlier. 

```js
const filePath = import.meta.dirname;
Deno.readTextFileSync(filePath + '/airport-schema.graphql')
```
