### ISSUE TITLE
Deno has panicked. brotliCompressSync

### ISSUE THREAD

**Issue by MrCarbone** [denoland/deno#24572]
Version: Deno 1.45.2
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

```sh
Platform: windows x86_64
Version: 1.45.2
Args: ["C:\\Deno\\deno.exe", "run", "-A", "--watch", "api.ts"]

thread 'main' panicked at C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\brotli-6.0.0\src\enc\encode.rs:1443:9:
Unimplemented: need to set 9.5 here
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

File: code
```ts
import { brotliCompressSync, constants } from "node:zlib";
const e = brotliCompressSync("abc", {
    params:{
        [constants.BROTLI_PARAM_QUALITY]: 10
    }
});
console.log(e);
```

( There is a problem with the value of 10 )

**Comment by marvinhagemeister** [comment]
The panic is caused by this line in the `brotli` crate: https://github.com/dropbox/rust-brotli/blob/37d403b437c3cbd1c686871a4167290aab401704/src/enc/encode.rs#L1469

```rs
if quality == 10 {
  unimplemented!("need to set 9.5 here");
}
```
