### ISSUE TITLE
`ChildProcess` kill causes "Uncaught (in promise) BrokenPipe: Broken pipe (os error 32)" error

### ISSUE THREAD

**Issue by lalalaleo** [denoland/deno#24590]
Version: Deno 1.45.2
OS: macOS 14.5 (m1)

The program can play streaming audio generated by TTS using ffplay correctly. However, when I call abort(), it triggers an Uncaught (in promise) BrokenPipe: Broken pipe (os error 32), and then the program crashes. I don't know how to fix or catch this.

```ts
class SpeakTask {
  #status: SpeakTaskStatus = "ready";
  #process: Deno.ChildProcess | null = null;
  #stdin: WritableStreamDefaultWriter<Uint8Array> | null = null;
  #organ: Speak;

  #cmd = new Deno.Command("ffplay", {
    args: ["-nodisp", "-autoexit", "-i", "pipe:0"],
    stdin: "piped",
    stdout: "null",
    stderr: "null",
  });

  get status() {
    return this.#status;
  }
  set status(value: SpeakTaskStatus) {
    this.#status = value;
    this.#organ.trigger("status", value);
  }

  constructor(organ: Speak) {
    this.#organ = organ;
  }
  async start() {
    if (this.status !== "ready") return;
    this.#process = this.#cmd.spawn();
    this.#stdin = this.#process.stdin.getWriter();
    this.status = "running";
    this.#process.status.then(() => {
      this.#process = null;
      this.#stdin = null;
      if (this.status === "aborting") {
        this.status = "aborted";
      } else {
        this.status = "done";
      }
    });
  }
  async write(chunk: Uint8Array) {
    if (this.status !== "running") return;
    this.#stdin?.write(chunk);
  }

  async abort() {
    if (this.status !== "running") return;
    this.status = "aborting";
    await this.#kill();
  }

  async #kill() {
    if (this.#process) {
      try {
        await this.#process.kill("SIGKILL");
      } catch (error) {
        logger.error(`[${this.#organ.prefix}] Error killing process: ${error}`);
      }

      this.#process = null;
      this.#stdin = null;
    }
  }
}
```

**Comment by marvinhagemeister** [comment]
How can we run the class shown in the snippet? It seems like there are things missing like the `Organ` type that needs to be passed into the constructor. The quickest way for us to resolve issues is when we can see the errors on our end. To do so, a script that can be run with `deno run` directly is most efficient and least ambiguous which helps us eliminate a lot of surface area to look at when investigating an issue.

**Comment by lalalaleo** [comment]
I've resolved it; it was my mistake. The output of the TTS is asynchronous. I used to trigger stdin.write immediately after receiving the TTS output data. Now I've added a queue to store the TTS output data first, and then trigger stdin.write again after stdin.write is completed. 😆
