### ISSUE TITLE
jsxImportSource freezes lsp when deno.json in nested directory is not listed as member of workspace

### ISSUE THREAD

**Issue by Reububble** [denoland/deno#24600]
Version: Deno 1.45.2

Using vscode, if a workspace is set up and there's a `deno.jsonc` with `jsxImportSource` that isn't a member of the workspace, deno language server is unresponsive.

Example directory:
- foo/
  - bar/
    - deno.jsonc
  - baz/
    - deno.jsonc
  - deno.jsonc

foo/deno.jsonc:
```json
{
  "workspace": ["./bar"]
}
```

foo/baz/deno.jsonc:
```json
{
  "compilerOptions": {
    "jsxImportSource": "jsx"
  }
}
```

From there, you can try to make a new typescript file and notice that there's no intellisense. Commenting out the `jsxImportSource` won't fix the issue until the language server is somehow restarted (which fails from the command palette).

<details>
<summary>
Output from Deno Language Server (anonymised)
</summary>

```
Starting Deno language server...
  version: 1.45.2 (release, x86_64-pc-windows-msvc)
  executable: ...\deno.EXE
Connected to "Visual Studio Code" 1.91.1
Enabling import suggestions for: https://deno.land
Refreshing configuration tree...
  Resolved Deno configuration file: "file:///.../foo/deno.jsonc"
  Resolved Deno configuration file: "file:///.../foo/bar/deno.jsonc"
  Resolved Deno configuration file: "file:///.../foo/baz/deno.jsonc"
Error preparing caching: Config file must be a member of the workspace.
  Config: file:///.../foo/baz/deno.jsonc
  Workspace: file:///.../foo
Server ready.
```
</details>

**Comment by dsherret** [comment]
You need to add the `baz` directory as a workspace member, but this shouldn't cause the lsp to stop functioning.

**Comment by Reububble** [comment]
> You need to add the `baz` directory as a workspace member

Can you expand on this point? For argument's sake, `baz` is full of arbitrary files, unrelated to the workspace. I am battling a new issue and I suspect the answer will determine whether it is a bug report or feature request.

**Comment by dsherret** [comment]
> For argument's sake, baz is full of arbitrary files, unrelated to the workspace.

That's fine. Workspace members are not just packages, but folders with distinct config. You should define it as a member in the root config so the root knows about that folder's config.

**Comment by Reububble** [comment]
I think I've miscommunicated what I meant. `baz/deno.jsonc` is an arbitrary file, which may or may not contain valid deno configuration JSON. I really don't think I should add it as a member, unless I'm supposed to add ALL sub folders?

**Comment by dsherret** [comment]
I'd recommend calling it something else. Deno auto discovers json files called that.

**Comment by Reububble** [comment]
> I think the lsp should continue functioning in this scenario though?

Yes, it functions, but I'm getting an unexpected error from the lsp. See #24666. I would like to avoid renaming that `deno.jsonc` file
