### ISSUE TITLE
Bug: Command `deno add` logs error for JSR package without default export

### ISSUE THREAD

**Issue by csvn** [denoland/deno#24607]
When using `deno add`, I get errors if there is any JSR package that has no default export (`.`). For instance, installing `@std/testing` will make it so errors are printed every time I run `deno add` command. The command itself seems to succeed anyway, but the CLI command fails with a non-zero exit code, and a pretty verbose error message is printed. Is it mandatory to have a default export? If so, perhaps `@std/testing` should be updated, since it currently only has named subpath exports.

## Reproduction steps

1. Create a new folder
2. Add JSR package via `deno add` with no `.` export (e.g. `@std/testing@0.225.3`)
   - ` deno add @std/testing@0.225.3`
3. Install any other JSR package (e.g. `@std/json`)

### Actual results

When installing `@std/testing@0.225.3` the following errors is printed:
```
Created deno.json configuration file.
Add @std/testing - jsr:@std/testing@^0.225.3
error: Unknown export '.' for '@std/testing@0.225.3'.
  Package exports:
 * ./asserts
 * ./bdd
 * ./mock
 * ./snapshot
 * ./time
 * ./types
```

Installing another package via `deno add` (e.g. `@std/json`) will print the same error again.
```
Add @std/json - jsr:@std/json@^0.224.1
error: Unknown export '.' for '@std/testing@0.225.3'.
  Package exports:
 * ./asserts
 * ./bdd
 * ./mock
 * ./snapshot
 * ./time
 * ./types
```

### Expected results

No errors

## Environment

OS: Windows 11
deno 1.45.2 (release, x86_64-pc-windows-msvc)
v8 12.7.224.12
typescript 5.5.2

**Comment by MujahedSafaa** [comment]
Hi @csvn 
I attempted to reproduce the bug, but I wasn't able to encounter the error you described. Did I miss something?
![image](https://github.com/user-attachments/assets/d162cfd5-d05b-4b34-a640-2067932b1303)

**Comment by sant123** [comment]
Pretty weird, I'm on Linux and I'm having the same issue:

![image](https://github.com/user-attachments/assets/3bdb1278-60a0-4526-b35c-4aea8b660ada)

Fedora 40
