### ISSUE TITLE
2019-06-05 benchmark page isn't being updated

### ISSUE THREAD

**Issue by ry** [denoland/deno#2460]
commit e152dae  seems to have pushed to the gh-pages branch: https://travis-ci.com/denoland/deno/jobs/205789155
```
commit 2ee2f3efe853e69a4d4913d490e7495a094f82e6
Author: Deployment Bot (from Travis CI) <deploy@travis-ci.org>
Date:   Wed Jun 5 20:48:40 2019 +0000
    Deploy denoland/deno to github.com/denoland/deno.git:gh-pages
 data.json   | 2 +-
 recent.json | 2 +-
 2 files changed, 2 insertions(+), 2 deletions(-)
```
and the benchmarks appear to have run correctly.

But it isn't displayed on the page 
<img width="732" alt="Screen Shot 2019-06-05 at 5 02 28 PM" src="https://user-images.githubusercontent.com/80/58990363-be1d5580-87b3-11e9-91e4-3b1d1b61516b.png">
the last change displayed is a71305b4febc3d8db95d3d144ae3a64c023718f0

The https://denoland.github.io/deno/recent.json file doesn't match what's in the gh-pages branch:
```
> curl -s https://denoland.github.io/deno/recent.json | shasum
391f0206020d2de2dc8cd1ec86f89a4a6325017e  -
> git checkout 2ee2f3efe853e69a4d4913d490e7495a094f82e6
HEAD is now at 2ee2f3ef Deploy denoland/deno to github.com/denoland/deno.git:gh-pages
> shasum recent.json
fd314de156174ec040da5f0040e0660f7ce2ea5e  recent.json
```

**Comment by ry** [comment]
I discovered a warning in the github settings for the project

<img width="804" alt="Screen Shot 2019-06-05 at 5 15 59 PM" src="https://user-images.githubusercontent.com/80/58991209-b199fc80-87b5-11e9-8c0d-d23fbb31a6ad.png">

I have pushed [some](https://github.com/denoland/deno/commit/f92a97276ccbbb321738bb647e3c4e8d09344a71) [commits](https://github.com/denoland/deno/commit/7053a28fd769813cee0d7bd188a5d9253ded1263) to the gh-pages branch to delete the rustdoc and typedoc symlinks. I'm not sure how they appeared.

This appears to have fixed things.

**Comment by ry** [comment]
This issue is recurring. I've pushed another "rm typedoc rustdoc" in 7c7b3b0b.

It's unclear to me why these directories are suddenly getting created in gh-pages.

**Comment by hayd** [comment]
I don't think `/tools/benchmark.py` was modified in tools/test.py change?
https://github.com/denoland/deno/commits/master/tools/benchmark.py

Ah, I wonder if it's there's no spawned server?

I wonder if it should be:
```
if __name__ == '__main__':
    with http_server.spawn():
        main(sys.argv)
```
Ooops, my bad for not spotting that!

**Comment by hayd** [comment]
Actually, I don't see how it can be that.

Perhaps we could add those two files to the .gitignore ? As it seems to still be an issue.

**Comment by bartlomieju** [comment]
Ooops, missed this issue, I'll check and get back to you

**Comment by ry** [comment]
Following @hayd's advice, I've added a gitignore in the gh-pages branch: adb02da
Hopefully that fixes it.

**Comment by ry** [comment]
Still broke

**Comment by bartlomieju** [comment]
FYI I just noticed that `rustdoc` and `typedoc` symlinks shown up on my local machine. I'll try to pin point the issue

**Comment by ry** [comment]
[it seems removing the trailing slash from the gitignore fixed it.](https://github.com/denoland/deno/commit/adb02dabe04afef1fec65b2a872dc0dc6b6f8ef7#commitcomment-33859661)
