### ISSUE TITLE
[complie] Importing node modules does not work with byonm flag when entrypoint in a sub dir

### ISSUE THREAD

**Issue by yasaichi** [denoland/deno#24654]
Version: Deno 1.45.0 to 1.45.2

From v1.45.0, compiling files __not in a root directory__ results in a runtime error: `Relative import path "module_name" not prefixed with / or ./ or ../`. Here is the minimum setup and commands to reproduce this bug.
I assume the point is that compiling files __in a root directory__ works fine even in the latest version.

# Setup
```ts
// <project-root>/src/main.ts
import { Option } from 'effect';
Option.isNone;
```

```jsonc
// <project-root>/deno.jsonc
{
  "unstable": ["byonm"]
}
```

# Commands
```sh
$ pwd
<project-root>
$ pnpm install
$ deno compile --output main ./src/main.ts
$ ./main
error: Relative import path "effect" not prefixed with / or ./ or ../
```

For further details, please see this repo: https://github.com/yasaichi/reproduce-deno-compile-bug-24654

**Comment by yazan-abdalrahman** [comment]
@dsherret 
I tried to reproduce the issue yesterday 'it exists', and once I updated the project to the last commit, it was fixed today. 

![image](https://github.com/user-attachments/assets/fedf8c18-589f-4902-9649-5972840e4162)
