### ISSUE TITLE
Type check fails on iterator helper methods

### ISSUE THREAD

**Issue by scarf005** [denoland/deno#24659]
![image](https://github.com/user-attachments/assets/894800c1-247f-4b00-9919-9bc33cc6242d)

despite the support for [iterator helper was added in 1.42.2](https://deno.com/blog/v1.42#v8-123-and-typescript-543), it fails to typecheck properly.

Version: Deno 1.45.2+bb1c6c4 (canary, x86_64-unknown-linux-gnu)

**Comment by dsherret** [comment]
We're waiting on TypeScript 5.6. https://devblogs.microsoft.com/typescript/announcing-typescript-5-6-beta/

Going to close this one because I don't think it's worth tracking here. We'll get these updates once TypeScript 5.6 is released and is integrated into Deno.
