### ISSUE TITLE
globbing support when type checking

### ISSUE THREAD

**Issue by FND** [denoland/deno#24668]
As far as I can tell, `deno check` expects a file as entry point; it does not support targeting directories (failing silently; i.e. this limitation isn't obvious). Globbing might be used instead, but appears to be unsupported - unlike with adjacent commands (cf. #19102), which seems like a confusing inconsistency.

Thus projects without an obvious entry point covering all code (e.g. libraries with independent modules) need an out-of-band solution for module discovery, often resulting in shell scripts with limited portability.

Ideally, `check` should work just like `lint`, `fmt` and `test`:

```shell
$ deno lint "./src/**/*.ts"
$ deno check "./src/**/*.ts"
```

Perhaps it should also support targeting directories, though that might be a separate issue.

(For additional context, I've started documenting the way I've come to appreciate [Deno as general-purpose tooling](https://prepitaph.org/wip/deno-testing/) even beyond Deno-as-runtime projects, notably for client-side code.)

Version: Deno 1.45.2

**Comment by yazan-abdalrahman** [comment]
@lucacasonato  @FND 
can you explain the problem more, I'm still not sure I understand the requirement.

**Comment by marvinhagemeister** [comment]
@yazan-abdalrahman The `deno check` command doesn't do glob expansion. The issue is asking for supporting glob expansion there. Right now it treats glob paths as a literal file argument, which is wrong.

```sh
deno check "**/*.ts"
error: Module not found "file:///Users/marvinh/dev/denoland/docs/**/*.ts".
```

Instead, it should type check all files that match the glob pattern. In this case that would be all files in the current directory and below that end with `.ts`.

**Comment by yazan-abdalrahman** [comment]
@marvinhagemeister 

ok I got it,
![image](https://github.com/user-attachments/assets/634ceca0-98d3-476c-ba66-bf87b3f03896)
But for "lint" I think this wrong?

it's another issue?

**Comment by marvinhagemeister** [comment]
That's odd, I'm not getting the error for `lint` on my mac. Maybe it's an OS issue?

**Comment by yazan-abdalrahman** [comment]
@marvinhagemeister 
@lucacasonato 

![image](https://github.com/user-attachments/assets/cebc0524-1f35-49ee-bd10-87bf2ccd765b)

that's correct  ?

**Comment by marvinhagemeister** [comment]
Lgtm. The error is expected as using JSX is only valid inside `.jsx/.tsx` files.

**Comment by FND** [comment]
Looking good with Deno 1.46 - thank you all!
