### ISSUE TITLE
`deno serve` prints that it listens on localhost instead of 0.0.0.0

### ISSUE THREAD

**Issue by sanderhahn** [denoland/deno#24687]
Version: Deno 1.45.3

```ts
// server.ts
export default {
  fetch(_request: Request) {
    return new Response("Hello, world!");
  },
};
```

```sh
$ deno serve --host 0.0.0.0 server.ts
deno serve: Listening on http://localhost:8000/
```

**Comment by ishon19** [comment]
Hey @bartlomieju, I'd love to work on this issue! 👋

**Comment by yazan-abdalrahman** [comment]
> ```ts
> // server.ts
> export default {
>   fetch(_request: Request) {
>     return new Response("Hello, world!");
>   },
> };
> ```

Hey, @ishon19 I founded the solution, and I will push PR
