### ISSUE TITLE
Will Tink/NPM 8 make Deno obsolete?

### ISSUE THREAD

**Issue by AlexLeung** [denoland/deno#2469]
Given the [announcement](https://www.youtube.com/watch?v=SHIci8-6_gs) of Tink at JS Conf EU yesterday, which is scheduled to be **the** NPM 8 release, I struggle to see what major advantages Deno will have anymore.

The features Tink will provide that make it on-par or better than Deno are:
- TypeScript built-in to the default node runtime itself like Deno, **plus** JSX support
- getting dependencies by filename / url like Deno, **plus** still being a module registry for library authors and consumers
- all dependency installation happens implicitly with caching like Deno
- retaining node.js compatibility unlike Deno

Forgive me for acting like a spoiled customer, but how will Deno compete with that?
Tell me why I'm being naive and why I should invest time in building for the Deno ecosystem with NPM 8 on the way.
One major superiority I can see Deno having is it not being tied to a private corp like NPM is, which could have disastrous consequences for NPM users down the line when the VC money dries up and the servers shut down.

If you feel this is better for Software Engineering or StackOverflow Stack Exchange I can move this there, but I wanted to hear from the insiders themselves, as I feel Tink is basically NPM's direct response to challenge what you're building. I have great reverence for Ryan Dahl and the Deno team.

**Comment by ry** [comment]
Deno is a new independent runtime. Tink is a node program. They aren’t really comparable pieces of software.

> why I should invest time in building for the Deno ecosystem 

You should not https://deno.land/manual.html#disclaimer
