### ISSUE TITLE
Improve error messages for naively used packages

### ISSUE THREAD

**Issue by rbetts** [denoland/deno#24699]
Examples like "https://jsr.io/@std/dotenv/doc/~/load#example_1..." don't work out of the box and give error messages with insufficient guidance:

```
 error: Relative import path "@std/dotenv/load" not prefixed with / or ./ or ../
    at file:///Users/rbetts/code/test-env/hello.ts:2:8
```

We should improve the CLI error message to tell people how to resolve the problem ("add the registry specifier or use `deno add`")?

Further, naively attempting `deno add @std/dotenv/load` produces a confusing error message that doesn't include guidance:

```
Created deno.json configuration file.
error: Failed to parse package required: @std/dotenv/load

Caused by:
    0: Invalid package requirement '@std/dotenv/load'. Invalid version requirement. Invalid specifier version requirement. Unexpected character '/'
         /load
         ~
    1: Invalid version requirement. Invalid specifier version requirement. Unexpected character '/'
         /load
         ~
    2: Invalid specifier version requirement. Unexpected character '/'
         /load
         ~
    3: Unexpected character '/'
         /load
         ~
```

**Comment by dsherret** [comment]
Moved out the second point to https://github.com/denoland/deno/issues/25385
