### ISSUE TITLE
1.45.3 breaks fetch with user:pass in URL

### ISSUE THREAD

**Issue by albnnc** [denoland/deno#24697]
Version: Deno 1.45.3

Found out that our tests which are using "http://user:pass@localhost..." connection strings broke with auth-related errors after 1.45.2–>1.45.3 upgrade.

To be specific, broken tests use docker.io/clickhouse/clickhouse-server:23.7.1-alpine.

**Comment by bartlomieju** [comment]
Do you have proxies involved? Are you using `fetch()` API? Is there any code you could share?

**Comment by albnnc** [comment]
<details>
<summary>Test code</summary>

```ts
Deno.serve({ port: 10_000 }, (req) => {
  console.log("req.url", req.url);
  console.log("req.headers", Array.from(req.headers));
  return new Response(null);
});

fetch("http://root:root@localhost:10000");
```
</details>

<details>
<summary>1.45.2</summary>

```
Listening on http://localhost:10000/
req.url http://localhost:10000/
req.headers [
  [ "accept", "*/*" ],
  [ "accept-encoding", "gzip, br" ],
  [ "accept-language", "*" ],
  [ "authorization", "Basic cm9vdDpyb290" ],
  [ "host", "localhost:10000" ],
  [ "user-agent", "Deno/1.45.2" ]
]
```
</details>

<details>
<summary>1.45.3</summary>

```
Listening on http://localhost:10000/
req.url http://localhost:10000/
req.headers [
  [ "accept", "*/*" ],
  [ "accept-encoding", "gzip,br" ],
  [ "accept-language", "*" ],
  [ "host", "localhost:10000" ],
  [ "user-agent", "Deno/1.45.3" ]
]
```
</details>

Looks like "authorization" header is missing on 1.45.3.
