### ISSUE TITLE
--watch flag doesn't restart on file creation

### ISSUE THREAD

**Issue by ArmaanAS** [denoland/deno#24701]
## Feature Request
The `deno run --watch ...` command only seems to trigger when a file is modified or deleted but not when a new file is created. My feature request is that the `--watch` flag be made to also restart the process when a new file is added.

## Use Case
My use case is for a dev mode for a Hono server. I have a simple script which enables file-based routing by generating a `routes.ts` file which imports all files within the `routes/` directory. I can then import that `routes.ts` file in my `main.ts` and preserve the types where doing dynamic imports wouldn't. The code generation script is run on start / restart, just before `main.ts`.

## Workaround
My workaround currently is to use `Deno.watchFs(".")` to detect file creation and then modify an existing file which triggers the process to restart. This isn't ideal and it would be great if `--watch` would also restart on file creation.

**Comment by lucacasonato** [comment]
`--watch` by default only watches files in your module graph (the file you passed to `run`, and all files it imports). If you create a new file, it by defintion will not be in your module graph yet, so Deno is not watching it.

You can however pass a list of files or directories to `--watch` (`--watch=routes`) which will cause Deno to _also_ (so in addition to the module graph), watch the specified files / directories.

So I suggest you do `deno run --watch=routes ...`
