### ISSUE TITLE
Do not surface permission denied errors for .npmrc in home directory

### ISSUE THREAD

**Issue by JLCarveth** [denoland/deno#24734]
Version: Deno 1.45.3

I don't think Deno should automatically search for a `~/.npmrc` file, as was mentioned in [the 1.45 blog post](https://deno.com/blog/v1.45):

> Deno will [discover .npmrc configuration file placed in your home directory](https://github.com/denoland/deno/pull/24021) for better private registry support

Personally, this causes my Fresh instances to cease working. I run them as systemd service units, which do not have access to directories outside of what I allow, so any attempts to read a file in for example the home directory will always fail. 

Ideally, I could disable this behaviour or modify the path to search with an environment variable.

Thanks for all the hard work on Deno and Fresh!

**Comment by dsherret** [comment]
> Personally, this causes my Fresh instances to cease working. I run them as systemd service units, which do not have access to directories outside of what I allow, so any attempts to read a file in for example the home directory will always fail.

Oh, is it causing the process to fail? Probably it should just ignore access denied errors?

**Comment by JLCarveth** [comment]
Yes, this would be a good solution
