### ISSUE TITLE
Session Ids returned in Jupyter Kernel responses are incorrect

### ISSUE THREAD

**Issue by DonJayamanne** [denoland/deno#24737]
Version: Deno x.x.x (latest version)

Steps to repro
* Install Jupyter Lab
* Install deno and the deno kernel for Jupyter
* Install the Kernel spy (to view kernel messages https://github.com/jupyterlab-contrib/jupyterlab-kernelspy)
* Create a new Notebook and open Kernel Spy
* Run some cells
* All kernel responses are expected to have the same session Id in the header.
However with deno, all of the responses contain different Session Ids.

This causes a few issues with Jupyter lab as well, fortunately it does work, but throws a few errors (that are ignored).
Here's where the session id is captured [this._kernelSession = reply.header.session;](https://github.com/jupyterlab/jupyterlab/blob/78cd6b60e5eb43b1278d825290ac81fd378faed6/packages/services/src/kernel/default.ts#L610)
& here's where the session id is validated and error thrown
https://github.com/jupyterlab/jupyterlab/blob/78cd6b60e5eb43b1278d825290ac81fd378faed6/packages/services/src/kernel/default.ts#L1145-L1153

Documentation on session id can be found here  https://jupyter-client.readthedocs.io/en/latest/messaging.html#message-header

<details>
  <summary>Here's a screenshot of Python kernel returning the same session id `a9afb6dc-2cd09f98a3940f3f1ba6b705` being returned by the kernel in all responses.
</summary>
  
![Image](https://github.com/user-attachments/assets/a764101c-c48d-417a-9450-d6059b12dbdc)

</details>

<details>
  <summary>In contrast the deno kernel always returns new/unique session ids. (supposed to use 2040024b-c6eb-4616-a930-a6343db2b4f5)
</summary>
  

![Image](https://github.com/user-attachments/assets/f9937c76-98d8-4538-ac5e-1c033c4bb2fa)

</details>

@rgbkrk /cc

FYI, this used to work in some older version of deno, unfortunately I didn't check the version of Deno i had installed before updating to the latest version.

**Comment by rgbkrk** [comment]
Alright, I'm on it to fix.
