### ISSUE TITLE
Rename confusing --allow-none flag in `deno test`

### ISSUE THREAD

**Issue by byvide** [denoland/deno#24752]
The `deno test` command currently includes an `--allow-none` flag, which prevents returning an error code if no test files are found. This flag name is misleading as it does not align with other `--allow-*` flags related to permissions and security.

Consider renaming this flag to a more intuitive and clear alternative that better reflects its function.

Possible name alternatives:
* `--no-error-on-missing` 
* `--proceed-if-none`

**Comment by dsherret** [comment]
I agree. That's confusing.
