### ISSUE TITLE
Incorrect typings with export default having no constructor

### ISSUE THREAD

**Issue by BlackAsLight** [denoland/deno#24769]
Version: Deno 1.45.4

The below code results in an incorrect typing error saying Pusher is not constructable, but running the code works perfectly fine. It stops complaining about the error if one does `new Pusher.default(...)`, but this causes a runtime error instead. 
```ts
import Pusher from 'npm:pusher-js@8.3.0'

new Pusher('abc', { cluster: 'abc' })
```
```
error: TS2351 [ERROR]: This expression is not constructable.
  Type 'typeof import("file:///Users/soul/Library/Caches/deno/npm/registry.npmjs.org/pusher-js/8.3.0/index.d.ts")' has no construct signatures.
new Pusher('abc', { cluster: 'abc' })
```

On another note, using pusher-js from this source `https://js.pusher.com/8.3.0/pusher.js` doesn't cause this error at all.

**Comment by dsherret** [comment]
The package is CJS, but it uses `export default` in its typings, which is incorrect because that's ESM only.

I get the exact same error in a non-Deno Node ESM project:

```
> npx tsc
main.mts:3:5 - error TS2351: This expression is not constructable.
  Type 'typeof import("V:/scratch/node_modules/pusher-js/index")' has no construct signatures.

3 new Pusher('abc', { cluster: 'abc' })
      ~~~~~~


Found 1 error in main.mts:3
```

**Comment by BlackAsLight** [comment]
Thanks
