### ISSUE TITLE
Deno.env.get("secretvalue") is saying undefined even if its defined in .env

### ISSUE THREAD

**Issue by Rajrup-TransEV** [denoland/deno#24773]
Version: Deno 1.45.4

Deno.env.get("secretvalue") is saying undefined even if its defined in .env
 deno runtime not able to get the data from .env variables and values .
 
example :

```
const secretvalue = Deno.env.get("SECRET_KEY")
console.log(secretvalue )

//undefined

```
as env reading now baked into Deno we don't require to use any packages , I tried the same by reading docs but not able to read the env data even if its defined in env

command used to ran for this case - 

```
{
  "tasks": {
    "dev": "deno run --allow-env --allow-net --allow-read  --watch  main.ts",
  }
}
```
tried to change the -allow-env position but it didnot worked

repo if you want to check the code in case 
 
I can able to read the env data if i use this method 

```
import { load } from "https://deno.land/std@0.224.0/dotenv/mod.ts";

`const env = await load();`
`const keyfromenv = env["KEY"];`
console.log(keyfromenv )

```
```
machine details

OS - PopOS Linux
cpu - AMD Ryzen 8 core
RAM -16 GB
```

#### which is a big problem because i wanna deploy my backend on deno deploy

**Comment by Rajrup-TransEV** [comment]
now while debugging i also able to see that ->
```
import { config } from "https://deno.land/x/dotenv@v3.2.2/mod.ts";

// Load environment variables from .env file
config();

// Access the environment variable
const envread = Deno.env.get("SECRET_KEY");
const envset  = Deno.env.set("hello","world")
console.log(envset,"envset")
console.log("Read env data:", envread);
```

get and set both is not working at all 

here is the response after running the script ->
```
Watcher File change detected! Restarting!
#### undefined envset
#### Read env data: undefined
Watcher Process finished. Restarting on file change...
```
problem also faced on windows-> script that is used to run on windows->

```
{
  "tasks": {
    "dev": "deno run --allow-net --allow-read --allow-env --watch  main.ts"
  },
  "imports": {
    "@std/assert": "jsr:@std/assert@1"
  }
}

```

**Comment by satyarohith** [comment]
@Rajrup-TransEV if you're defining environment variables in `.env` file, you need to load them using https://jsr.io/@std/dotenv. Deno doesn't do that automatically. On Deno Deploy, you need to set the environment variables in the dashboard (you can learn [more here](https://docs.deno.com/deploy/manual/environment-variables/)).

**Comment by Rajrup-TransEV** [comment]
i had set the variables on deno deploy using the dashboard i am not a fool that i don't do  the step? 
on my code you can clearly see that on my code that i have already set the package you're mentioned .
please tell me if it's working on your side or not?
