### ISSUE TITLE
Homebrew deno stuck at `1.45.2`

### ISSUE THREAD

**Issue by scarf005** [denoland/deno#24774]
![image](https://github.com/user-attachments/assets/dbe5d0b2-4e6e-43e6-93b6-71d372bf73f7)

despite [`1.45.4` being released at 07-27](https://github.com/denoland/deno/releases/tag/v1.45.4), there's only [`1.45.2` available on homebrew](https://formulae.brew.sh/formula/deno). Is homebrew deno released manually? if it's deployed via github actions, would there have been issues preventing it from being released?

**Comment by petamoriken** [comment]
The build has failed and seems to have stopped https://github.com/Homebrew/homebrew-core/pull/178635

**Comment by devsnek** [comment]
Been tracking in https://github.com/denoland/rusty_v8/issues/1541

**Comment by chenrui333** [comment]
we just shipped the new update with older rust_v8 :( 

https://github.com/Homebrew/homebrew-core/pull/179168

**Comment by lucacasonato** [comment]
@chenrui333 How does that work? What version of `rusty_v8` did that binary build with?

**Comment by chenrui333** [comment]
> @chenrui333 How does that work? What version of `rusty_v8` did that binary build with?

looks like the latest rusty_v8 works for us now (not quite sure if this is rust 1.80 upgrade related or not)

see https://github.com/Homebrew/homebrew-core/pull/179395
