### ISSUE TITLE
Deno compile - module not found on Windows in cjs pkg re-exporting relative path with parent component

### ISSUE THREAD

**Issue by spkier12** [denoland/deno#24785]
Version: Deno 1.45.0 (Latest)
Deno compile certain npm packages casues module not found when executing the .exe after compile

[ERR_MODULE_NOT_FOUND] Cannot find module "C:\Users\Ulrik\AppData\Local\Temp\deno-compile-Simconnect_test.exe\node_modules\localhost\node-simconnect\3.6.2\dist\dto../datastructures/VersionBaseType" imported from "C:\Users\Ulrik\AppData\Local\Temp\deno-compile-Simconnect_test.exe\node_modules\localhost\node-simconnect\3.6.2\dist\dto\index.js""

Command to compile: deno compile -A main.ts --Unstable npm:msfs-simconnect-api-wrapper@4.5.0

Here is my code:

```ts
import {SystemEvents, MSFS_API, loadAirportDB} from "npm:msfs-simconnect-api-wrapper@4.5.0"

const api = new MSFS_API();

let Ramp2TaxiState = true
let ClimbOrCruiseState = false
let DecendState = false
let LandingState = false


api.connect({
    retries: Infinity,
    retryInterval: 2,
    onRetry: (_: any, interval: Number) => {
      console.log(`Connection failed: retrying in ${interval} seconds.`);
    },
    onConnect: async() => await MSFSRun()
  });

// Get events continuerly every 1 second
async function MSFSRun() {
  console.log(`\n Connected to Simconnect`)
  while(true) {
    let x = await api.get("AIRSPEED INDICATED")
    let y = await api.get("PLANE ALTITUDE")
    let z = await api.get("VERTICAL SPEED")
    console.log(`Speed: ${String(x.AIRSPEED_INDICATED).split(".")[0]} ALT: ${String(y.PLANE_ALTITUDE).split(".")[0]} VS: ${String(z.VERTICAL_SPEED * 60).split(".")[0]}`)
    setInterval(() => {}, 800)
  }
}

**Comment by dsherret** [comment]
> Deno 1.45.0 (Latest)

Did you try in 1.45.4 (the latest)?

**Comment by spkier12** [comment]
> > Deno 1.45.0 (Latest)
> 
> 
> 
> Did you try in 1.45.4 (the actual latest)? It might be fixed there.

Yes i wrote wrong version in the post i am on latest.

Seems you cannit mix modules and commonjs in deno compile, makes me wonder why they announced npm support when it dosnt work. Seems to be a problem for 40% of npm packages that still uses cjs

**Comment by dsherret** [comment]
> Seems you cannit mix modules and commonjs in deno compile, makes me wonder why they announced npm support when it dosnt work. Seems to be a problem for 40% of npm packages that still uses cjs

It's seems to just a Windows thing and the internals of deno compile changed in 1.45.0 to not expose absolute file paths.

I was able to only reproduce this on Windows.

**Comment by spkier12** [comment]
> > Seems you cannit mix modules and commonjs in deno compile, makes me wonder why they announced npm support when it dosnt work. Seems to be a problem for 40% of npm packages that still uses cjs
> 
> It's seems to just a Windows thing and the internals of deno compile changed in 1.45.0 to not expose absolute file paths so there might be some bugs related to that.
> 
> I was able to only reproduce this on Windows.

so if i was to downgrade 1 version it would work?
Still worth making a bug report of and why does it noe resolve absolute path?
