### ISSUE TITLE
WASM might be broken ?

### ISSUE THREAD

**Issue by studiowebux** [denoland/deno#24799]
Version: Deno 1.45.3 and 1.45.4

Hello, 

sorry in advance for the more or less random issue, I will try to be concise

I'm using `cardano-serialization-lib` with deno + hono for about two weeks (everything was working fine since tonight)

the only thing I did out of usual is : `deno upgrade`
So I tested 3 different systems and all of them are "broken" (using the latest deno version)

CONTEXT: I try to create wallets, and CSL uses WASM (with rust) and the function always returns 0 (with the latest version).

so I spun a docker using deno 1.40.4 and it works as expected (i took randomly the 1.40.4 version)

Expected behaviour (works with 1.40.4): 
```bash
root@b5074cf9fae7:/# deno run /opt/index.ts 
┌ ⚠️  Deno requests read access to "/deno-dir/npm/registry.npmjs.org/@emurgo/cardano-serialization-lib-nodejs/11.3.0/cardano_serializatio✅ Granted all read access.
Generated Address: addr1v93sp88q4txx496fze7462w6903sms8xy3kc2pukrhxkgvg0ztqsa
Generated Address: addr1v9zjuzj6jy0zh5eqz293t0xlj36398n74qe2v54k4qlhzmsshj968
Generated Address: addr1vx04skcrjtda09xczxwt974xd9nl8ft2907p5nh33pgfq8ck9hamc
Generated Address: addr1v8cu7psrxs4ld4e2hehqq83en7wq27e08frkk94wz7x92qcscyz4c
Generated Address: addr1vx0cw9kya6z3nfmdrgwcxc07wgdcz2sk4ws0n0efcvjqu5qeh37c4
root@b5074cf9fae7:/# 
```

and with the latest deno version:

```bash
deno run -A __tests__/wallet.3.ts
privateKey 0000000000000000000000000000000000000000000000000000000000000000
Generated Address: addr_test1vr9exkzjnh6898pjg632qv7tnqs6h073dhjg3qq9jp9tcsg8d6n35
(base) REDACTED@un-ordi cardano % deno --version
deno 1.45.4 (release, aarch64-apple-darwin)
v8 12.7.224.13
typescript 5.5.2
```

tested with 1.45.2 and it works as expected

it also works as expected with NodeJS

Do you have any insight or things that I need to do ?

Thanks in advance !

**Comment by studiowebux** [comment]
@marvinhagemeister Morning !

__tests__/issue.test.ts
```ts
import { PrivateKey } from "@emurgo/cardano-serialization-lib-nodejs";

const privateKey = PrivateKey.generate_ed25519();

console.log(privateKey.to_hex());
```

```bash
deno run -A __tests__/isssue.test.ts
```

Expecting a non-zero HEX encoded private key, and unique (random) value everytime it is executed

Current output:
```bash
deno upgrade --version 1.45.4
deno run -A __tests__/isssue.test.ts
0000000000000000000000000000000000000000000000000000000000000000 # this is the issue
```

```bash
deno upgrade --version 1.45.2
deno run -A __tests__/isssue.test.ts
616b6eea59b12e19cbf9a7abd131cd4269186feed582b63c41efad4d761a5a40 # this is what is expected
```

NOTICE: it generates valid Private key for the blockchain.

Let me know if you need anything else 
thanks !

**Comment by lucacasonato** [comment]
Bisected, and this broke in https://github.com/denoland/deno/commit/76b8ecbb6d8c07d29c34fb0b301cc3bf3351e3aa.
