### ISSUE TITLE
Support wildcards in package.json imports

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#24790]
https://github.com/rcompat/rcompat/blob/f998fb7c408cd098b37d403109190f1633a4bb37/packages/fs/package.json#L32-L35

https://github.com/denoland/deno/issues/22772#issuecomment-2257156982

**Comment by dsherret** [comment]
I looked into this and we do support wildcards. Something specifically is not working here.

**Comment by dsherret** [comment]
I looked into it more and even though the code is there, it doesn't work, so renaming this back.

**Comment by terrablue** [comment]
I do think it's related to the wildcards: If I add a specific `#FileRef` import, it moves on to the next error, looking for `#parse`.

**Comment by dsherret** [comment]
Yeah, fix is here: https://github.com/denoland/deno/pull/24794/files#diff-7043bcb8cce9b05b263f33389d25addfa13cbd3ad1a6f68cbb395d6a27a281bd

**Comment by terrablue** [comment]
Awesome, thanks for moving so fast on this!
