### ISSUE TITLE
Read files relative to the dir where the script file located or the user current worked?

### ISSUE THREAD

**Issue by zhmushan** [denoland/deno#2479]
```
src/
  mod.ts
  file
  dir/
```
```ts
// mod.ts
Deno.readFileSync("./file");
```
We can execute `deno run mod.ts` under `src/`.
If we execute `deno run ../mod.ts` under `src/dir/`, `Deno` will throw an error.
Is this expected?

**Comment by kitsonk** [comment]
What error?

**Comment by zhmushan** [comment]
> What error?

```
Uncaught NotFound: No such file or directory (os error 2)
    at DenoError (js/errors.ts:22:5)
    at maybeError (js/errors.ts:33:12)
    at maybeThrowError (js/errors.ts:39:15)
    at sendSync (js/dispatch.ts:114:5)
    at openSync (js/files.ts:49:18)
    at readFileSync (js/read_file.ts:12:16)
    at file:///Users/zhmushan/Desktop/src/mod.ts:1:6
```

**Comment by bartlomieju** [comment]
`readFile` resolves files relative to current working directory

**Comment by zhmushan** [comment]
This is very confusing. I used to think it should be rooted where the script file is located.

**Comment by kitsonk** [comment]
It has always been the current working directory, which is normal for other runtimes and also wouldn't make sense if the root module was a remote URL.

**Comment by zhmushan** [comment]
Aaah! thanks!

**Comment by maliknajjar** [comment]
What's the solution for reading a file relative to a package in Deno? How can I access a file relative to the package itself?

I've created a Deno JSR package, and I want to read an HTML file that resides in the package directory. What would be the best way to achieve that?
