### ISSUE TITLE
deno intro example command doesn't work

### ISSUE THREAD

**Issue by johannes-climacus** [denoland/deno#2481]
on this page under example: https://deno.land/

> Try running a simple program:
> `deno https://deno.land/welcome.ts`

```
$ deno https://deno.land/welcome.ts
error: Found argument 'https://deno.land/welcome.ts' which wasn't expected, or isn't valid in this context

USAGE:
    deno [FLAGS] [OPTIONS] [SUBCOMMAND]
```

should be `deno run https://deno.land/welcome.ts`

**Comment by kitsonk** [comment]
You need to use the current released version of Deno.  You are using an older version.

**Comment by johannes-climacus** [comment]
thanks for pointing that out, looks like my package manager hadn't taken the update from 15 hours ago yet

**Comment by tiagolpadua** [comment]
same here 
deno 1.0.0
v8 8.4.300
typescript 3.9.2

**Comment by kitsonk** [comment]
The website makes it clear:

```shell
$ deno run https://deno.land/std/examples/welcome.ts
```

If you typed `deno https://deno.land/welcome.ts` you did not follow the directions on the website correctly.

**Comment by lucacasonato** [comment]
Although to be fair the website did say `$ deno https://deno.land/std/examples/welcome.ts` two hours ago. Sorry for that (https://github.com/denoland/deno_website2/pull/410)

**Comment by kitsonk** [comment]
Ah!
