### ISSUE TITLE
Lint tsx and jsx from stdin

### ISSUE THREAD

**Issue by galiazzi** [denoland/deno#24854]
Today is not possible lint a tsx or jsx file from stdin. Example:

```jsx
// test.jsx
function render() {
  return <View />;
}
```

```bash
deno lint test.jsx

# Result:
# error[no-unused-vars]: `render` is never used
```

With stdin:

```bash
cat test.jsx | deno lint -

# Error linting: /Users/dayangaliazzi/Projects/yanda/$deno$stdin.ts
#  Expression expected at file:///Users/dayangaliazzi/Projects/yanda/$deno$stdin.ts:2:17
#
#    return <View />;
#                  ~
# Checked 1 file
```

One suggestion is add a `--ext` argument like `fmt` to `lint`:

```
cat test.jsx | deno lint - --ext=jsx
```

**Comment by yazan-abdalrahman** [comment]
@galiazzi @lucacasonato 
`cat test.jsx | deno lint - --ext=jsx`
it should have the same result 
`deno lint test.jsx`
?

**Comment by lucacasonato** [comment]
Yes!

**Comment by yazan-abdalrahman** [comment]
> add a `--ext` argumen

that's  needs add 
add a --ext argument ?

**Comment by lucacasonato** [comment]
Yes

**Comment by yazan-abdalrahman** [comment]
@lucacasonato 
I passed the new  `ext `argument
I did it in this way the `ext` it should be the name of the file?
that's correct or need some modifications 
![image](https://github.com/user-attachments/assets/b0d734e3-9324-4060-9755-27e3e5c739fc)

**Comment by yazan-abdalrahman** [comment]
> @lucacasonato I passed the new `ext `argument I did it in this way the `ext` it should be the name of the file? that's correct or need some modifications ![image](https://private-user-images.githubusercontent.com/145254650/356224615-b0d734e3-9324-4060-9755-27e3e5c739fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMjEwNjQsIm5iZiI6MTcyMzEyMDc2NCwicGF0aCI6Ii8xNDUyNTQ2NTAvMzU2MjI0NjE1LWIwZDczNGUzLTkzMjQtNDA2MC05NzU1LTI3ZTNlNWM3MzlmYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQxMjM5MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kODYyYzlhOWY1NzhmZjQ5YWQxMzU1ODFmM2UzYmI5MGI0MjVmMjc3NzIyNzAyZTFhOTExZDRiY2M0M2U1ZjYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.l1u4kHN3u_hZ9WGYONVeXE2qVGu7PBGrNxakf-XgLV0)

i think no,

 i got the fix

**Comment by yazan-abdalrahman** [comment]
![image](https://github.com/user-attachments/assets/3fc815d4-bdd1-4446-81d3-69a492d5db5f)

**Comment by yazan-abdalrahman** [comment]
@lucacasonato 
Can you review my pull request #24955
?
