### ISSUE TITLE
website/style.css: Text gets cut off, even if the browser window is wide enough

### ISSUE THREAD

**Issue by ry** [denoland/deno#2485]
<img width="864" alt="Screen Shot 2019-06-09 at 5 14 25 PM" src="https://user-images.githubusercontent.com/80/59164397-2634aa00-8ada-11e9-970a-f8da43b9ce03.png">

https://github.com/denoland/deno/blob/master/website/style.css

**Comment by hayd** [comment]
You can scroll right on that pre, so I wouldn't fix this... (a fix is likely going to look ugly).
You can read the intent of, and copy and paste, the code which is the important thing...

**Comment by kt3k** [comment]
I tried `white-space: pre-wrap; word-break: break-all;`

<img width="702" alt="スクリーンショット 2019-06-10 10 22 05" src="https://user-images.githubusercontent.com/613956/59167741-cdaeec80-8b6d-11e9-94c5-89a381a32937.png">

Looks ok to me.

**Comment by ztplz** [comment]
No need to fix it because we can scroll to the right, the current style is good for me.
