### ISSUE TITLE
`this` is `undefined` 

### ISSUE THREAD

**Issue by vdata1** [denoland/deno#24861]
Hi, 

I would like to report a finding considering the code snippet below.  Using deno version 1.45.5, `this` gives undefined in both global scope and other scopes, e.g., function block. I ran the same code in Node.Js and I got different results: `{}` for the global scope and "global obj" for the other scopes.  Since both the runtimes use the same engine "v8", I am wondering if it is not a bug and why it is different.

```javascript 
console.log(this); //binds to {} in node, undefined in deno. 
(function () {
  console.log(this); //this binds to undefined in function block in deno, global object in node.     
})();
```

AH

**Comment by BlackAsLight** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this
> In non–strict mode, this is always a reference to an object. In strict mode, it can be any value. 

> If the function is called without being accessed on anything, this will be undefined — but only if the function is in strict mode.

My guess would be that Node isn't following the specification?

**Comment by lucacasonato** [comment]
Node REPL runs in non-strict mode by default, Deno always runs in strict mode. You get the same behaviour in both when you run this code:

```js
console.log(this); //binds to {} in node, undefined in deno.
(function () {
  "use strict";
  console.log(this); //this binds to undefined in function block in deno, global object in node.
})();
```

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode

**Comment by vdata1** [comment]
Thanks for the clarifications @BlackAsLight, @lucacasonato
