### ISSUE TITLE
Bug: "Sources" panel is empty in inspector

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/deno#24877]
The "Sources" panel in the Chrome DevTools inspector is empty. This makes it impossible to continue when running with `--inspect-brk`. Tried to do a bisect but it seems like all Deno versions are affected. Maybe Chrome changed something on there side?

<img width="1009" alt="Screenshot 2024-08-05 at 08 23 51" src="https://github.com/user-attachments/assets/8ff6dd79-3748-42db-956f-9bf998108275">

## Steps to reproduce

1. Run `deno init`
2. Run `deno run -A --inspect-brk main.ts`
3. In Chrome, go to `chrome://inspect`
4. Click on "Inspect" link

Version: Deno 1.45.5

**Comment by marvinhagemeister** [comment]
Can confirm that this is an upstream issue in DevTools, see https://issues.chromium.org/issues/342961829?pli=1

**Comment by bartlomieju** [comment]
@devsnek mentions that it might be because we set "opaque" origins for all scripts. Gus has a branch that is supposed to fix it.

**Comment by devsnek** [comment]
The upstream bug has been marked fixed and I verified that I can use `--inspect-brk` with a chromium 129 nightly build, so I think you just need to wait for that fix to be available in your chrome install.

**Comment by june07** [comment]
Another PSA about a solid workaround for this and other instances where DevTools on the current browser release is broken in some way...

Use [Node --inspector Manager](https://github.com/june07/NiMv3) the Chromium browser extension (I am the author)

I just resolved [a different DevTools issue](https://issues.chromium.org/issues/352496164) just a few days ago [(see here)](https://github.com/june07/nimv3/issues/10#issuecomment-2268321317).

[NiM](https://nim.june07.com) allows you to mix/match DevTools versions with whatever browser version you happen to be running, so when bugs become showstoppers, it's just a matter of selecting a different DevTools version from NiM's settings which can be hosted locally as shown in the example below or from any other endpoint:
* **NiM's** [https://devtools-frontend.june07.com/inspector.html](https://devtools-frontend.june07.com/inspector.html)
* **Google's Appspot** [https://chrome-devtools-frontend.appspot.com](https://chrome-devtools-frontend.appspot.com)
* Whatever other devtools-frontned endpoint you want

Quick change in the settings to swap DevTools vs needing to install Canary or wait:
![image](https://github.com/user-attachments/assets/6a95facf-bc9d-4a3f-a618-4deced2d0bca)

Showing me debugging Deno as per @marvinhagemeister steps
![Group](https://github.com/user-attachments/assets/70ef10a5-b368-412a-b297-c5701ca32614)

**Comment by marvinhagemeister** [comment]
With the recent Chrome 128.0.6613.114 update I cannot reproduce this issue anymore. Looks like they backported the fix.
