### ISSUE TITLE
JSR module not found after `compile`

### ISSUE THREAD

**Issue by Mutefish0** [denoland/deno#24871]
Version: deno 1.44.4

## Reproduce
create `main.ts`:
```ts
import { getGamepads } from "jsr:@mutefish/gamepad-api";

async function main() {
  while (true) {
    const gamepads = getGamepads();
    console.log(gamepads);
    await new Promise((resolve) => setTimeout(resolve, 100));
  }
}

main();
```
compile and execute:
```shell
deno compile --unstable-ffi -o main   main.ts && ./main
```
You will encounter a Module not found error, even though the imported module does exist: https://jsr.io/@mutefish/gamepad-api/0.0.2/libs/aarch64-apple-darwin.ts

```shell
error: Uncaught (in promise) TypeError: Module not found: https://jsr.io/@mutefish/gamepad-api/0.0.2/libs/aarch64-apple-darwin.ts
const buff = await import(`./libs/${Deno.build.target}.ts`);
             ^
    at async https://jsr.io/@mutefish/gamepad-api/0.0.2/ffi.ts:2:14
```

deno run works fine:
```shell
deno run --unstable-ffi  main.ts
```

**Comment by lucacasonato** [comment]
https://docs.deno.com/runtime/manual/tools/compiler/#dynamic-imports

You may have to manually include this file: `--include=https://jsr.io/@mutefish/gamepad-api/0.0.2/libs/aarch64-apple-darwin.ts`
