### ISSUE TITLE
M1 MacOS `--watch` slow to reload and/or never reloading

### ISSUE THREAD

**Issue by jordangarside** [denoland/deno#24876]
```
➜ deno --version                           
deno 1.45.5 (release, aarch64-apple-darwin)
v8 12.7.224.13
typescript 5.5.2
```
Apple M1 Pro 16GB on Sonoma 14.2

Just downloaded Deno and trying the hello world example with `--watch`. 
```ts
➜ cat hello.ts             
interface Person {
  firstName: string;
  lastName: string;
}

function sayHello(p: Person): string {
  return `Hello, ${p.firstName}!`;
}

const ada: Person = {
  firstName: "Jane",
  lastName: "Lovelace",
};

console.log(sayHello(ada));
```
```
➜ deno run --watch hello.ts
Watcher Process started.
Hello, Jane!
Watcher Process finished. Restarting on file change...
```
There's some weird behavior happening to me with the reloading.

If I simple change the first name:
- it seems like the first time it always takes ~2-5min before the first reload
- subsequent reloads it takes on the order of 5-30s
- eventually/sometimes (usually after just a handful of reloads) it seemingly never reloads even after waiting 5min+

**Comment by isAdrisal** [comment]
Might be the same issue as #24880

**Comment by marvinhagemeister** [comment]
@isAdrisal That's very unlikely as the `--watch` flag uses a different code path. The issue you linked to is about `rename` event being included in the `modify` event in `Deno.watchFs` only.

**Comment by jordangarside** [comment]
Not quite sure what was happening, but everything is working as expected/quickly now after restarting my MacBook.
