### ISSUE TITLE
[Feature Request] A way to respond to a `Deno.serve` request when you've only got a reference to the request object

### ISSUE THREAD

**Issue by josephrocca** [denoland/deno#24875]
I'm trying to find a way to prevent clients from hanging if the server happens to restart midway though their request. The moment before the server restarts, I'd like to respond to existing requests with an error.

I initially thought that `Deno.serve` would do this automatically when SIGINT was received, but it doesn't. So I tried to add an abort, thinking that this would fix it, but it doesn't:
```js
let ac = new AbortController();
Deno.addSignalListener("SIGINT", async () => {
  console.log("Aborting server in an attempt close pending requests, so clients receive error instead of hanging.");
  ac.abort();
  await new Promise(r => setTimeout(r, 1000)); // tried waiting a bit, but this doesn't help
  Deno.exit();
});

Deno.serve({port:3000, signal:ac.signal}, async request => {
  // my handler is a lot more complicated than this, but you get the idea
  await someOperation();
  await anotherOperation();
  // ...
  return new Response("success");
});
```
So my final fallback solution is to just keep track of active requests, and then when SIGINT is received, respond to them with an error before `Deno.exit()`. But then I realised that, AFAIK, there's no way to respond to a request using only the `Request` object.

**Comment by lucacasonato** [comment]
You could instead have a `Promise.race()` in your handler that races a "shutdown" future with your actual handler.

You could also cause the handler to reject, and then return a nice response in the error handler.

I am not sure there is a need for new API surface here.

**Comment by josephrocca** [comment]
Ohh, right, I forgot that a promise could be returned, so IIUC it's as simple as e.g.:

```js
Deno.addSignalListener("SIGINT", async () => {
  for(let resolve of pendingResolvers) {
    resolve(new Response("fail"));
  }
  Deno.exit();
});

let pendingResolvers = new Set();
Deno.serve({port:3000}, async request => {
  return new Promise(async resolve => {
    pendingResolvers.add(resolve);
    await someLongishOperation();
    pendingResolvers.delete(resolve);
    resolve(new Response("success"));
});
```
Or something roughly like that. Thanks!
