### ISSUE TITLE
Bug: `Deno.watchFs` doesn't detect a file rename/move

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/deno#24880]
Noticed that the `Deno.watchFs` watcher isn't able to differentiate file modifications from file moves. When moving or renaming a file it returns two `modify` events instead.

## Steps to reproduce

1. Run `deno init`
2. Run `mkdir files && echo "foo" >> files/foo.txt`
3. Update `main.ts` with these contents:
  ```ts
  const watcher = Deno.watchFs("./files", { recursive: true });
  
  for await (const event of watcher) {
    console.log("watch", event);
  }
  ```
4. Run `deno run -A main.ts`
5. Rename the file `files/foo.txt` to something else

Output:

```sh
watch [Object: null prototype] {
  kind: "modify",
  paths: [ "/Users/marvinh/dev/test/deno-watcher/files/foo.txt" ],
  flag: null
}
watch [Object: null prototype] {
  kind: "modify",
  paths: [ "/Users/marvinh/dev/test/deno-watcher/files/foo2.txt" ],
  flag: null
}
```

Version: Deno 1.45.5

**Comment by marvinhagemeister** [comment]
Looking a bit into this the rust watcher library we're using tracks this in the inner value of the `Modify` event which we ignore here:

https://github.com/denoland/deno/blob/27ea23ea69bc018f48abbd4ec0d0572b6d1beca4/runtime/ops/fs_events.rs#L70-L77

We should make use of that.

**Comment by marvinhagemeister** [comment]
Turns out this is also an issue with the node API where we're expected to forward a `rename` event, but we don't.

**Comment by johndeighan** [comment]
On Windows 11, I'm not getting any events at all when I delete a file. I thought it might have something to do with the fact that Windows moves the file to the Recycle Bin, but even after I empty the recycle bin, I get absolutely no events. If I follow that with re-creating the file, I do get a 'modify' event - not that that helps any.
