### ISSUE TITLE
Issues with lsp imports

### ISSUE THREAD

**Issue by ry** [denoland/deno#24889]
Version: Deno 1.45.5

No quickfix for installing npm dependencies

<img width="585" alt="Screenshot 2024-08-05 at 10 39 41 AM" src="https://github.com/user-attachments/assets/984b2e95-f021-4148-babc-3095d8b0b525">

No auto-complete for `node:fs/pro`
<img width="667" alt="Screenshot 2024-08-05 at 10 45 42 AM" src="https://github.com/user-attachments/assets/b44d7d2b-708e-476d-9b0e-63e42e1ed949">

Use "install" instead of "cache" everywhere. For example - change terminology from "Uncached or missing jsr dependency" to "Uninstalled". Or in the quickfix, instead of "Cache jsr:@std/fs/walk and its dependencies" say "Install jsr:@std/fs/walk and its dependencies"
<img width="602" alt="Screenshot 2024-08-05 at 10 42 10 AM" src="https://github.com/user-attachments/assets/b0a12ecd-b7c8-4cf3-87b5-bc96446a61a7">
<img width="652" alt="Screenshot 2024-08-05 at 10 42 27 AM" src="https://github.com/user-attachments/assets/88b6e134-bd9e-4de7-881b-82273cf1fa2a">

Uncached deps red squiggly should probably be a yellow squiggly. Red is too aggressive. 
![Screenshot 2024-08-05 at 6 05 56 AM](https://github.com/user-attachments/assets/88bd5a26-f1e9-4e43-a8e0-ae5500ef3029)

also https://github.com/denoland/deno/issues/24951

**Comment by lucacasonato** [comment]
I agree with everything here, except:
> Uncached deps red squiggly should probably be a yellow squiggly. Red is too aggressive.

It should be a red squiggly - it's the error for when you are importing something that does not exist. `import "./doesnotexist.ts"` should not be a yellow squiggly either.

**Comment by guy-borderless** [comment]
May be nice to also be able to `deno add` and have the name rewritten

**Comment by ry** [comment]
@lucacasonato 

> It should be a red squiggly - it's the error for when you are importing something that does not exist. import "./doesnotexist.ts" should not be a yellow squiggly either.

With auto-install common in deno, I don't think this matches the user's experience. `jsr:@std/fs/walk` does exist, unlike `./doesnotexist.ts`. The analogy doesn't hold.

**Comment by luizfilipe** [comment]
that would be nice to be on LSP, and also with things on `"imports"` section on `deno.json` conf

**Comment by nayeemrmn** [comment]
There is an npm install quick fix when using `"nodeModulesDir": "auto"`, which I think matches reasonable expectations. Let's close this.
