### ISSUE TITLE
Bug: LSP is missing "Convert to ESM" quick fix

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/deno#24925]
The default vscode's TypeScript server has a "Convert to ESM" quick fix that converts a CJS module to ESM. This is missing when the Deno LSP is enabled. We should enable it in our LSP too.

<img width="667" alt="Screenshot 2024-08-07 at 11 19 49" src="https://github.com/user-attachments/assets/e3e0c0ae-7ffb-409a-9912-fb3e373b9b98">

Before:

```js
const os = require("os");
console.log(os);
```

After:
```js
import os from "os";
console.log(os);
```

Version: Deno 1.45.5

**Comment by Hajime-san** [comment]
It seems that the Quick Fix appears when it's `.ts` file, but not `.js` file with Deno LSP.

The Node.js + TS outputs like below. The `foo.mjs` is same as example code above.

```bash
File is a CommonJS module; it may be converted to an ES module.ts(80001)
var require: NodeRequire
(id: string) => any
```

**Comment by HasanAlrimawi** [comment]
I believe it has been addressed.
Quick fix appears and done using deno 2.0.0-rc.1+39f2704 (canary, release, x86_64-pc-windows-msvc)

**Comment by marvinhagemeister** [comment]
I still don't see it on `v2.0.0-rc.1+ce1d668`

**Comment by HasanAlrimawi** [comment]
I believe I'm using deno LSP's this way, if yes then the intended is successfully done.
![Quick_fix](https://github.com/user-attachments/assets/ca95c831-e186-436e-a8ca-70b322d9cf97)

**Comment by marvinhagemeister** [comment]
ohh right, I accidentally used a `*.ts` file when trying it earlier today. Thanks for checking 👍
