### ISSUE TITLE
ERR_UNSUPPORTED_ESM_URL_SCHEME importing jsr package in npm package via `jsr:` scheme

### ISSUE THREAD

**Issue by terrablue** [denoland/deno#24935]
Version: Deno 1.45.5

Reproduce with:
`git clone -b sqlite https://github.com/rcompat/test-deno && cd test-deno && deno run app.js`

Error:
`error: [ERR_UNSUPPORTED_ESM_URL_SCHEME] Only file and data URLs are supported by the default ESM loader. Received protocol 'jsr'`

This uses an NPM package which, for Deno, imports `jsr:@db/sqlite@0.11`. Is this impossible?

**Comment by dsherret** [comment]
> This uses an NPM package which, for Deno, imports jsr:@db/sqlite@0.11. Is this impossible?

No, it's not currently possible to reference jsr packages from npm packages. I'm not sure it will ever be supported because it's quite challening and creates a lot of complexity.

**Comment by terrablue** [comment]
Thanks. Hm, that's too bad. I have packages that use runtime keys to diverge between runtimes, and I was also meaning to increasingly use JSR packages in Deno's case, especially given the fact that `"npm:better-sqlite3"` doesn't work on Deno.

The idea was:
* Node -> npm:better-sqlite3
* Deno -> jsr:@db/sqlite
* Bun -> bun:sqlite

While I understand it's complex, it would be awesome if there were interoperability between NPM and JSR. Would certainly make it easier to adopt JSR packages...

What would you say is the best way forward here? Try to bundle in packages from JSR during package buildtime?

**Comment by lucacasonato** [comment]
You can import JSR packages using JSR's npm compat: https://jsr.io/docs/npm-compatibility

**Comment by terrablue** [comment]
@lucacasonato hi, when I run `npx jsr add @db/sqlite` as per the link posted, I get:

```sh
Installing @db/sqlite...
$ npm install @db/sqlite@npm:@jsr/db__sqlite
npm error code E404
npm error 404 Not Found - GET https://registry.npmjs.org/@jsr%2fdb__sqlite - Not found
npm error 404
npm error 404  '@jsr/db__sqlite@*' is not in this registry.
npm error 404
npm error 404 Note that you can also install from a
npm error 404 tarball, folder, http url, or git url.
npm error A complete log of this run can be found in: /home/blue/.npm/_logs/2024-08-22T16_27_01_709Z-debug-0.log
```

Am I doing something wrong?
