### ISSUE TITLE
Using --allow-ffi leads to "unexpected argument" and --unstable-ffi leads to prompt

### ISSUE THREAD

**Issue by zzador** [denoland/deno#24933]
Version: Deno 1.45.5
deno 1.45.5 (release, x86_64-pc-windows-msvc)
v8 12.7.224.13
typescript 5.5.2

Using --allow-ffi leads to "unexpected argument" and --unstable-ffi leads to prompt. Is there currently a way to bypass the FFI prompt?

**Comment by aapoalas** [comment]
What is your full command? It sounds like you're misplacing the flags or missing eg. The "run" subcommand:
```
deno run --allow-ffi --unstable-ffi main.ts
```

**Comment by ry** [comment]
you have the argument in the wrong position - it should come after "run"

however we could do a better job here of either understanding the argument anyway or having a better error message.

**Comment by zzador** [comment]
Thank you.

It works now with:
`deno --unstable-ffi run --allow-ffi test.ts`
