### ISSUE TITLE
Receivers of piped io streams need to manually close stdin

### ISSUE THREAD

**Issue by anxiousmodernman** [denoland/deno#2494]
[Full example here](https://github.com/anxiousmodernman/deno-examples/tree/master/piped-output). Given this bash script *printer.sh*:

```sh

#!/bin/bash

echo "column1 first"
echo "column1 second"
echo "column1 third"
echo "column1 fourth"
echo "column1 fifth"
```

And this awk script *parser.awk*

```awk
#!/usr/bin/env awk

BEGIN { RS="\n" ; }
{     print $2    }
```
I want to write a Deno script that would behave like this interactive shell command

```
./printer.sh | awk -f parser.awk
```
It's easy to write, but I have to call `stdin.close()` on the reader, or else the reader will hang forever

```typescript

async function main(): Promise<void> {

    let p1 = Deno.run({
        args: ["./printer.sh"],
        stdout: "piped",
    });

    let p2 = Deno.run({
        args: ["awk", "-f", "parser.awk"],
        stdin: "piped",
    });

    let streamed = Deno.copy(p2.stdin, p1.stdout);
    let n = await streamed;
    console.log("bytes copied:", n);

    // hangs
    // await Promise.all([p1.status(), p2.status()]);
 
    // works
    // await Promise.all([p1.status()]);

    // hangs
    // await Promise.all([p2.status()]);

    // Can only await p1 until we call close on p2 stdin
    let code1 = await p1.status();
    p2.stdin.close();
    let code2 = await p2.status();
    console.log("codes:", code1, code2);

}

main();
```
And, presumably, if one has to do that, we ought to `await` the writer first to make sure it has written everything it needs to, e.g. it has exited. But that poses a problem for very long-running streams. Ideally, the reader/consumer should close its own stdin if it gets EOF.

**Comment by anxiousmodernman** [comment]
After digging into this. It seems difficult to support.

We spin off a child after registering its stdin/stdout/stderr streams, and once it's running we do not (?) have a mechanism that signals when a process has ended. If a reader child wanted to be notified when the writer to its stdin was done, we'd need to communicate that somehow.

Tokio itself offers a convenience method on the child that drops stdin, and seems aimed at the case where it is the parent writing to the child's stdin:
https://docs.rs/tokio-process/0.2.3/src/tokio_process/lib.rs.html#406

**Comment by dontlaugh** [comment]
Bumping this because it's linked to by https://github.com/denoland/deno/issues/8416

**Comment by crowlKats** [comment]
with the new [Command API](https://deno.land/api?s=Deno.Command&unstable), you do not need to close it manually anymore:

```ts
async function main(): Promise<void> {
  const command1 = new Deno.Command("./print-stuff.sh", {
    stdout: "piped",
  });
  const child1 = command1.spawn();

  const command2 = new Deno.Command("awk", {
    args: ["-f", "parse-stuff.awk"],
    stdin: "piped",
  });
  const child2 = command2.spawn();

  await child1.stdout.pipeTo(child2.stdin);

  const [code1, code2] = await Promise.all([child1.status, child2.status]);
  console.log("codes:", code1, code2);
}
```

**Comment by crowlKats** [comment]
Closing as Deno.Command has stabilized now.
