### ISSUE TITLE
thread 'main' panicked at cli/tools/upgrade.rs:657:3:

### ISSUE THREAD

**Issue by BriSeven** [denoland/deno#24971]
version of OSX is 10.14.6
(it's old, so I understand if this isn't suuuper high priority)

Version: Deno x.x.x
 RUST_BACKTRACE=1 deno upgrade 
Looking up latest version
Found latest version 1.45.5
Downloading https://github.com/denoland/deno/releases/download/v1.45.5/deno-x86_64-apple-darwin.zip
Deno is upgrading to version 1.45.5
Archive:  /var/folders/7n/sdzh61n954xd_fzlcm1fcwn00000gn/T/.tmplucw1x/deno.zip
  inflating: deno                    
dyld: cannot load 'deno' (load command 0x80000034 is unknown)

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos x86_64
Version: 1.41.3
Args: ["deno", "upgrade"]

thread 'main' panicked at cli/tools/upgrade.rs:657:3:
assertion failed: output.status.success()
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: deno::spawn_subcommand::{{closure}}
   4: <deno_unsync::task::MaskFutureAsSend<F> as core::future::future::Future>::poll
   5: tokio::runtime::task::raw::poll
   6: deno::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

I got the shell script installer to work but this now happens when I try to run deno

dyld: cannot load 'deno' (load command 0x80000034 is unknown)
Abort trap: 6

**Comment by BriSeven** [comment]
So, compiling it from source means it runs now! 

So, feature request: Perhaps instead of upgrade failing with mysterious messages, you can check for unsupported OS versions and display a message that compiling from source may work. 

it's annoying, but a bit less mysterious than just breaking my deno install.

**Comment by lucacasonato** [comment]
I don't think it's reasonable for us to do this. It would require us to be able to dynamically feature test every single feature we use before upgrading. That seems very unfortunate.

I think it is reasonable for users to have to jump through hoops if they want to use Deno from an OS that our official builds do not support.

**Comment by BriSeven** [comment]
i’m not asking you to featuretest! but maybe detect which operating system is running when invoking deno upgrade to warn if it is not supported

**Comment by BriSeven** [comment]
for example, homebrew displayed a message when they dropped support, telling me I was on my own. When deno failed here, I got a message telling me this was definitely a bug in deno and demanding i report it here
