### ISSUE TITLE
Please, add <secp256k1> :) For Web 3.0 🙏🙏🙏 Thanks

### ISSUE THREAD

**Issue by leonbakadorov** [denoland/deno#24989]
This is something that is sorely lacking in the Web 3.0 era. Let's fix it!))

**Comment by lucacasonato** [comment]
Deno supports `secp256k1` using `createECDH("secp256k1")` from `node:crypto`. https://docs.deno.com/api/node/crypto/~/createECDH

**Comment by mary-ext** [comment]
It seems that Node.js supports ECDSA secp256k1 as well, which Deno doesn't, should I file a new issue for this?
