### ISSUE TITLE
Feat: Support formatting sql files with deno fmt

### ISSUE THREAD

**Issue by M4RC3L05** [denoland/deno#25024]
As the title says, have deno fmt support sql files.
Would this be something to be considered?

**Comment by M4RC3L05** [comment]
Just noticed https://github.com/dprint/dprint-plugin-sql, would it be possible to add this to deno?

**Comment by bartlomieju** [comment]
Yes, we could potentially use https://github.com/shssoichiro/sqlformat-rs directly (which the plugin uses under the hood) to format SQL files. If a PR is opened to integrate it with `deno fmt` we can discuss it during the team meeting if we will merge it. I think if it started with requirement on `--unstable-sql` flag there's a good chance that would happen.
