### ISSUE TITLE
DENO_AUTH_TOKEN does not work, when it contains an extra \n at the end

### ISSUE THREAD

**Issue by pihentagy** [denoland/deno#25043]
Version: Deno 1.45.5

1. Create an otherwise valid bearer token, and set it as an env var, but with an extra newline at the end
   ```
   export DENO_AUTH_TOKENS=$'github_pat_xxxxxxxxxxxxxxxxxxx@raw.githubusercontent.com\n'
   ```
1. Do a `deno cache --reload https://raw.githubusercontent.com/pihentagy/some-private-repo/main/main.ts`
1. Watch it fail with a misleading error:
   ```
   error: Module not found "https://raw.githubusercontent.com/pihentagy/some-private-repo/main/main.ts".
   ```
   
Ran into that issue when setting the env var via gitlab variable btw.

**Comment by xiaoxiunique** [comment]
me too
