### ISSUE TITLE
Is there any JavaScript engine written in rust?

### ISSUE THREAD

**Issue by catastrop** [denoland/deno#2504]
Or any tool to transform c++ to rust?

**Comment by kitsonk** [comment]
Why ask that question here?  That has nothing to do with Deno.  Please keep conversation on topic and related to issues with Deno.

**Comment by catastrop** [comment]
because you are using rust. So why not use a JavaScript engine which is also written in **Rust**.

**Comment by CYBAI** [comment]
http://lmgtfy.com/?q=JS+engine+rust

**Comment by kitsonk** [comment]
@catastrop is that a question or a statement?

It was somewhat discussed in #237.  Deno is tied to V8 and that is not going to change.  V8 is highly optimised and proven in real world workloads.  Something that would be really difficult to replicate in another engine.  The language the engine is written in is largely immaterial in reality.  Servo is interesting, but someone making a secure TypeScript runtime with Servo isn't this project, it is some other project.

**Comment by EricEisaman** [comment]
Not active for 10 months, but this had been promising.
[](https://github.com/nbp/holyjit)

**Comment by kitsonk** [comment]
I am not sure what a Rust just in time compiler has anything to do with a JavaScript engine.

**Comment by catastrop** [comment]
When **V** become thing, things will change. It will support automatic translation from c(currently) and c++.

**Comment by ry** [comment]
There's also https://github.com/swc-project/swc
Closing this as it's not a deno issue.

**Comment by hayd** [comment]
Even Servo, the biggest rust project, uses SpiderMonkey (not written in rust\*).
V8 is amazing... deno is not going to use something else soley because it's written in rust.

\*HolyJIT was (is?) Mozilla's plan to create a new JS engine in rust. IMO this is still many years away.
https://blog.mozilla.org/javascript/2017/10/20/holyjit-a-new-hope/

**Comment by TomMarius** [comment]
The V8 Rust binding is severely outdated :-/

**Comment by ry** [comment]
https://crates.io/crates/deno is currently the best way to execute JS in Rust. It is a V8 binding.

It would be nice to have a lower-level binding that exposes V8 APIs directly, for people who don't buy into Deno's op model. But that doesn't exist. https://crates.io/crates/v8 does not work. https://github.com/IntrinsicLabs/osgood/tree/master/osgood-v8 is promising, but it's not yet a published crate, and there's a lot to do before it could be a dependency of Deno (but we're looking into it!)
