### ISSUE TITLE
Deno.run supports piped output only up to 65536 bytes

### ISSUE THREAD

**Issue by szhu** [denoland/deno#2505]
Deno version:

```
$ deno version
deno: 0.6.0
v8: 7.6.53
typescript: 3.4.1
```

The following script works:

```ts
async function main() {
  let p = Deno.run({
    args: ["python", "-c", 'import sys; sys.stdout.write("*" * 65536)'],
    stdout: "piped",
  })
  await p.status()
  console.log("Done")
}
main()
```

The following script doesn't:

```ts
async function main() {
  let p = Deno.run({
    args: ["python", "-c", 'import sys; sys.stdout.write("*" * 65537)'],
    stdout: "piped",
  })
  await p.status()
  console.log("Done")
}
main()
```

**Comment by mtharrison** [comment]
I think what's happening is the output is being buffered up to a max of `65536` and then blocking until some of it is read so the process does not exit. I notice it succeeds if you read some/all output before awaiting the status.

**Reading all**

```ts
async function main() {

  let p = Deno.run({
    args: ["python", "-c", 'import sys; sys.stdout.write("*" * 65537)'],
    stdout: "piped",
  });

  const rawOutput = await p.output();
  console.log(rawOutput.length);

  await p.status();
  console.log("Done");
}

main();

// 65537
// Done
```

**Reading some (and making some space in buffer)**

```ts
async function main() {

  let p = Deno.run({
    args: ["python", "-c", 'import sys; sys.stdout.write("*" * 65537)'],
    stdout: "piped",
  });

  const buff = new Uint8Array(10);
  await p.stdout.read(buff);
  console.log(new TextDecoder().decode(buff));

  await p.status();
  console.log("Done");
}

main();

// **********
// Done
```

You will see the same in Rust ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=563f446d34f6d12b0fa35b89211619be)) if you try to wait for the status without reading some of the output

```rust
#![allow(unused)]

use std::process::{Command, Stdio};

fn main() {
    
    let mut child = Command::new("python");
    
    child.args(&["-c", "import sys; sys.stdout.write(\"*\" * 65537)"]);
    child.stdout(Stdio::piped());
        
    println!("Child status was {}", child.status().unwrap());
}

```

**Comment by ry** [comment]
Thanks - this is a very good example - and clearly a bug. I will investigate soon.

**Comment by mtharrison** [comment]
Here's an analogous example in Node, the buffer though is [24kb for Node](https://github.com/nodejs/node/blob/master/lib/child_process.js#L52) before no completion events happen without reading some from the pipe:

```js
const ChildProcess = require('child_process');

const child = ChildProcess.spawn('python', ['-c', `import sys; sys.stdout.write("*" * 24577)`], {
	stdio: 'pipe'
});

child.on('exit', (code) => console.log(code));    // won't be called
```

I'm curious that you think it's a bug though.

**Comment by ry** [comment]
Actually after discussing with @piscisaureus, I think it's not a bug. 

I was mistaken before - Python isn't exiting, so the status promise shouldn't resolve.

Maybe we need some functionality of dumping stdout to null for subprocesses.

**Comment by bartlomieju** [comment]
Ref: #2013

**Comment by szhu** [comment]
> Python isn't exiting, so the status promise shouldn't resolve.

It makes sense that the `status()` promise shouldn't resolve because Python isn't exiting. What doesn't make sense is that Python is called in a way such that it doesn't exit.

> I'm curious that you think it's a bug though.

Why do I think it's a bug? Because having a promise never resolve is a important caveat, and this caveat is not mentioned at all in [the documentation](https://deno.land/typedoc/classes/deno.process.html#output).

---

For context, here's (a simplified version of) my use case. I'm trying to make a command that captures the output of `git ls-remote`. For repos on GitHub with a lot of branches or PRs, this output exceeds 64kb. I had to spent some time debugging why some commands in my tool would mysteriously hang even though no CPU was being used.

**Comment by ry** [comment]
Python is blocked on trying to write to stdout, that's why it doesn't exit.

**Comment by szhu** [comment]
That makes sense -- in Node, I would read stdout chunk by chunk. It looks like in Deno, I can do the same with `process.stdout.read(bytes)`.

In that case, I'm confused about the purpose of `process.output()`. What is its intended use case?

**Comment by ry** [comment]
`process.output()` buffers the output of a subprocess and returns it to you all at once.

**Comment by bartlomieju** [comment]
> In that case, I'm confused about the purpose of `process.output()`. What is its intended use case?

It reads everything from process' `stdout`- so it won't resolve until there is no more data to be read. Once it resolves you get complete output of subprocess.

**Comment by szhu** [comment]
I don't understand how both of these could be true:

> You have to read some of that input first.

> returns it to you all at once.

Do I need to read the partial output, or do I get all the output at once?

It might help if someone could give a demo of how to run sample Python program above and capture all of its output into a string.

btw, I'm aware that I might not be understanding something that's fairly obvious to the rest of you -- appreciating the quick responses and explanation in this thread.

**Comment by ry** [comment]
Read partial:
```js
let buf = new Uint8Array(1);
await process.stdout.read(buf)
```
Read complete:
```js
let buf = await process.output();
```

**Comment by szhu** [comment]
Okay, it finally makes sense now. Thanks everyone for explaining!

---

Some examples to help out other people in a similar situation:

This will hang forever:

```ts
async function main() {
  let p = Deno.run({
    args: ["python", "-c", 'import sys; sys.stdout.write("*" * 65537)'],
    stdout: "piped",
  })
  await p.status()
  doSomethingWith(await p.output())
  console.log("Done")
}
main()
```

But this works:

```ts
async function main() {
  let p = Deno.run({
    args: ["python", "-c", 'import sys; sys.stdout.write("*" * 65537)'],
    stdout: "piped",
  })
  let output = await p.output()
  await p.status()
  doSomethingWith(output)
  console.log("Done")
}
main()
```

**Comment by tch1121** [comment]
The file damaged, did I do something wrong?
```typescript
async function run() {
  const url = "http://test.mp4";
  const res = await fetch(url);
  if (res.body) {
    const ffmpeg = Deno.run({
      cmd: [
        "ffmpeg",
        "-y",
        "-i",
        "pipe:",
        "-c",
        "copy",
        "out.mp4",
      ],
      stdin: "piped",
    });

    for await (const chunk of res.body) {
      await ffmpeg.stdin?.write(chunk);
    }
  }
}
run();
```

**Comment by bartlomieju** [comment]
Replace: `await ffmpeg.stdin?.write(chunk);`
with `await writeAll(ffmpeg.stdin!, chunk);`

You can import `writeAll` from https://deno.land/std@0.106.0/io/util.ts#L170

**Comment by tch1121** [comment]
Still not working
deno quit too early
ffmpeg did not have time to write metadata
