### ISSUE TITLE
deno compile produces non deterministic build binary when there are npm dependencies

### ISSUE THREAD

**Issue by i-api** [denoland/deno#25084]
Version: Deno 1.45.5

deno compile produces non deterministic build binary - I suspect the issue has to do with the lockfile deno.lock

[deno.lock.txt](https://github.com/user-attachments/files/16651470/deno.lock.txt)
(renamed it to deno.lock.txt instead of deno.lock) because github doesn't allow .lock file extensions 

I never touch the lockfile, I just let deno generate the defaults.
want to document this issue for anyone that comes across it

for some reason, if you run "deno compile" the output binary can be completely different, from the previous run of "deno compile", even if you change nothing.

the way I "fixed" this was deleting the lockfile and running "deno compile" again, which made it so that the output binary was the same. No idea what was wrong with the internals of my deno.lock.

# Update
I dug further into this issue, and it appears that the deno.lock is being corrupted, by imports that uses "npm:" specifiers.
This doesn't produce any compiletime or runtime errors, but it does make it so that "deno compile" produces a different output binary even given the exact same inputs.

you can check this by running something like this twice:
```
git status; deno compile -A ./src/entry_point.ts; git status
```
git will tell you if the binary has been mutated

for example: 
import SpotifyWebApi from "npm:spotify-web-api-node";
will cause this error. It will cause the deno compile binary to differ each time you compile, even when you don't make any changes to the files at all.

**Comment by i-api** [comment]
I dug further into this issue, and it appears that the deno.lock is being corrupted, by imports that uses "npm:" specifiers.

**Comment by i-api** [comment]
did futher testing, and npm: specifiers are indeed the cause.

**Comment by i-api** [comment]
https://github.com/denoland/deno/issues/9244

**Comment by i-api** [comment]
I will also note, that once you "remove" the npm specifier, you need to delete the deno.lock as well in order to get deno compile to produce deterministic builds

**Comment by dsherret** [comment]
https://github.com/denoland/deno/issues/9244 is unrelated. You should probably be able to diff the executable and see what's being shifted around between compiles.

**Comment by i-api** [comment]
can confirm, I downloaded the latest canary release and tested it out. 
Deno compile now produces deterministic builds binaries with "npm:" specifiers

Thank you @dsherret!! ❤️
