### ISSUE TITLE
benchmark page spinner doesn't disappear on Edge

### ISSUE THREAD

**Issue by ry** [denoland/deno#2508]
![edge_benchmarks](https://user-images.githubusercontent.com/80/59380054-181a9f80-8d0d-11e9-851b-d2d7f75d6578.PNG)

**Comment by davidjamesstone** [comment]
@ry, I can pick this up.

**Comment by davidjamesstone** [comment]
I've tracked this issue down to Chakra-based versions of edge (pre-chromium) not supporting `Promise.prototype.finally`. I'll fix this tonight.

It works fine with new Chromium-based Edge version.
