### ISSUE TITLE
deno lsp and deno check produce different results depending on module graph

### ISSUE THREAD

**Issue by hesxenon** [denoland/deno#25093]
**Describe the bug**

When using a custom jsx runtime like `tsx-to-html` the lsp server produces no errors while `deno check` fails.

I've noticed this in a rather complex environment and I'm going to describe the most important points below until I have time to provide a minimal repro.

**Steps to Reproduce**

1. enrich the `JSX.IntrincisElements` interface e.g. by doing this
```ts
// foo.ts
declare global {
  namespace JSX {
    interface IntrinsicElements {
      "also-div": HTMLDivElement
    }
  }
}
```
2. use the declared element in another module, e.g.:
```tsx
// bar.tsx
const alsoDiv = <also-div />
```
3. the lsp server reports no problem
4. running `deno check bar.tsx` fails, presumably because `foo.ts` isn't in the module graph and thus `also-div` isn't defined.

**Expected behavior**

deno check should be consistent with lsp reports

**Environment**

- OS: Fedora 40
- deno version: 1.45.5
- std version: 1.0 (? added from jsr, no idea?)

**Comment by lucacasonato** [comment]
This is expected behaviour. In the LSP, all files in the server are considered part of the same module graph. In `deno check`, only files reachable from the entrypoint are included.

You should import `foo.ts` from `bar.tsx`.

**Comment by hesxenon** [comment]
this approach is missing several use cases, serving multiple target
environments from different entry points  among them.
