### ISSUE TITLE
error: Unsupported lockfile version '4'. 

### ISSUE THREAD

**Issue by hastebrot** [denoland/deno#25144]
Version: Deno 1.46.0

It seems `deno lint` (and other deno subcommands) does not support lockfile version 4 or ignores `DENO_FUTURE=1`.

Lockfile version 4 was introduced with https://github.com/denoland/deno/pull/25059.

```
❯ deno task main
Task main DENO_FUTURE=1 deno run main.ts

❯ deno task lint
error: Unsupported lockfile version '4'. Try upgrading Deno or recreating the lockfile at '[REDACTED]/deno.lock'.
```

`deno.jsonc`:
```jsonc
{
  "imports": {
    "nanoid": "npm:nanoid@5.0.7"
  },
  "tasks": {
    "main": "DENO_FUTURE=1 deno run main.ts",
    "lint": "DENO_FUTURE=1 deno lint"
  }
}
```

`main.ts`:
```ts
import { nanoid } from "nanoid";
nanoid();
```

**Comment by lucacasonato** [comment]
You have to run `deno task lint` and friends with `DENO_FUTURE=1`. Lockfile 4 is only supported with `DENO_FUTURE=1`.

**Comment by hastebrot** [comment]
Ahh thanks, now I understand. `deno task` accesses the lockfile and needs `DENO_FUTURE=1`.

**Comment by lucacasonato** [comment]
You can upgrade to the latest 2.0-rc (`deno upgrade rc`). It has future enabled by default
