### ISSUE TITLE
`NO_COLOR` with `deno bench` breaks spacing/layout

### ISSUE THREAD

**Issue by lionel-rowe** [denoland/deno#25157]
Version: Deno 1.46.0

Using the `NO_COLOR` environment variable with `deno bench` breaks the spacing/layout.

## Repro

**bench.ts**:
```ts
Deno.bench('...', () => {
   1 + 1
})
```

**report.ts**:
```ts
import { stripAnsiCode } from '@std/fmt/colors'

const x = await new Deno.Command(Deno.execPath(), {
	args: ['bench', './bench.ts'],
	stdout: 'piped',
}).spawn().output()

console.log('With colors:')
console.log(new TextDecoder().decode(x.stdout))

console.log('Stripped colors:')
console.log(stripAnsiCode(new TextDecoder().decode(x.stdout)))

const y = await new Deno.Command(Deno.execPath(), {
	args: ['bench', './bench.ts'],
	stdout: 'piped',
	env: { NO_COLOR: '1' },
}).spawn().output()

console.log('NO_COLOR=1:')
console.log(new TextDecoder().decode(y.stdout))
```

Output of `deno run --allow-read --allow-run report.ts`:
![image](https://github.com/user-attachments/assets/721957a7-1d4a-44dc-a474-c285a9f4ca54)

Expected result is that stripped colors gives same result as `NO_COLOR=1`; actual result is that stripped colors gives same visible spacing and layout as with colors, whereas `NO_COLOR=1` gives way more whitespace than expected.

**Comment by marvinhagemeister** [comment]
Looks like this issue was opened twice by accident. Let's combine them into https://github.com/denoland/deno/issues/25157
