### ISSUE TITLE
`NO_COLOR` with `deno bench` breaks spacing/layout

### ISSUE THREAD

**Issue by lionel-rowe** [denoland/deno#25156]
Version: Deno 1.46.0

Using the `NO_COLOR` environment variable with `deno bench` breaks the spacing/layout.

## Repro

**bench.ts**:
```ts
Deno.bench('...', () => {
     1 + 1
})
```

**report.ts**:
```ts
import { stripAnsiCode } from 'jsr:@std/fmt/colors'

const x = await new Deno.Command(Deno.execPath(), {
    args: ['bench', './bench.ts'],
    stdout: 'piped',
}).spawn().output()

console.log('With colors:')
console.log(new TextDecoder().decode(x.stdout))

console.log('Stripped colors:')
console.log(stripAnsiCode(new TextDecoder().decode(x.stdout)))

const y = await new Deno.Command(Deno.execPath(), {
    args: ['bench', './bench.ts'],
    stdout: 'piped',
    env: { NO_COLOR: '1' },
}).spawn().output()

console.log('NO_COLOR=1:')
console.log(new TextDecoder().decode(y.stdout))
```

Output of `deno run --allow-read --allow-run report.ts`:
![image](https://github.com/user-attachments/assets/721957a7-1d4a-44dc-a474-c285a9f4ca54)

Expected result is that stripped colors gives same result as `NO_COLOR=1`; actual result is that stripped colors gives same visible spacing and layout as with colors, whereas `NO_COLOR=1` gives way more whitespace than expected.

**Comment by marvinhagemeister** [comment]
The problem lies in the way the formatting is done here:

https://github.com/denoland/deno/blob/e7026c5ee8ac6780391b2169e338ca5fb5bbac70/cli/tools/bench/mitata.rs#L294-L318

The numbers seem to bit arbitrary and are based on the assumption that ansi codes are included.

**Comment by bartlomieju** [comment]
Fixed in https://github.com/denoland/deno/pull/25190
