### ISSUE TITLE
WebSocketStream not working under unstable flag

### ISSUE THREAD

**Issue by franz101** [denoland/deno#25150]
Version: Deno latest

Running into an issue that was working 2 days ago, maybe due to the latest version
```
curl -fsSL https://deno.land/install.sh | sh
export DENO_INSTALL="/root/.deno"
export PATH="$DENO_INSTALL/bin:$PATH"

deno  --unstable-net eval 'console.log("hi"); const wss = new WebSocketStream(`wss://a/ws/v2`);'```


Errors with:
```
error: Uncaught (in promise) ReferenceError: WebSocketStream is not defined
console.log("hi"); const wss = new WebSocketStream(`wss://a/ws/v2`);
```

I tried also the --unstable flag

**Comment by franz101** [comment]
confirming work with:
`curl -fsSL https://deno.land/install.sh | sh -s -- v1.45.5 `

**Comment by littledivy** [comment]
The flag needs to be after the subcommand:

```
deno eval  --unstable-net 'console.log("hi"); const wss = new WebSocketStream(`wss://a/ws/v2`);'
```
