### ISSUE TITLE
suggestion: `parallel: boolean` option for `Deno.serve()`

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno#25173]
Would work the same as [`deno serve --parallel`](https://deno.com/blog/v1.46#3-scale) and be `false` by default.

```diff
- Deno.serve((_req) => new Response("Hello, world"));
+ Deno.serve({ parallel: true }, (_req) => new Response("Hello, world"));
```

**Comment by lucacasonato** [comment]
I don't see how this works. We can't fork JS execution when we hit a `Deno.serve()` with `parellel: true`. It'd have to be `deno run --parallel`

**Comment by bartlomieju** [comment]
Closing as adding `parallel` option is not feasible here. I'd rather explore adding `deno run --parallel` as suggested by Luca.
