### ISSUE TITLE
`Windows` platform Deno.command `cwd` does not take effect

### ISSUE THREAD

**Issue by kingsword09** [denoland/deno#25171]
Version: Deno 1.46.0

I created the simplest project with `deno init` and then created an execution script x.bat in the src directory.

![image](https://github.com/user-attachments/assets/88c5841a-aa76-4183-865c-b0adbb5ffe40)

However, the following exception was thrown:
![image](https://github.com/user-attachments/assets/2ee226c5-d582-4c6d-ae91-f14e16585aff)

Anyway, modify this `cwd` as follows:
```ts
E:\github\test\windowsCommandCwdBug\src
E:\\github\test\windowsCommandCwdBug\src
E://github/test/windowsCommandCwdBug/src
```
But it still doesn't work, it just throws another exception.

Only the full path passed to the command parameter will take effect.

![image](https://github.com/user-attachments/assets/534bc492-4aed-4835-a1b0-e7d817c4aa72)
![image](https://github.com/user-attachments/assets/e7495c41-ccdc-4b69-930b-f753fcb91c47)

But running it on a `Mac`, `cwd` works!

**Comment by dsherret** [comment]
The path you pass to `Deno.Command` is independent of the provided `cwd`. It's relative to the current process' cwd and not the provided one. The code is saying is "execute this script at ./x.bat and use the cwd of E:\github\etc...".

To make it work, provide `./src/x.bat` instead.

**Comment by dsherret** [comment]
> But running it on a Mac, cwd works!

I just read this and confirm the behaviour seems different. This seems like a bug.

**Comment by dsherret** [comment]
I investigated this and we should probably align with `node:child_process` and make it work the same on Windows that it does on Mac (have relative paths resolved from the provided cwd)
