### ISSUE TITLE
deno --help spelling error

### ISSUE THREAD

**Issue by seansbox** [denoland/deno#2517]
Running "deno --help" with version 0.8.0 contains a spelling error.

    "Bundle module and *dependnecies* into single file"

Easiest issue of all to fix I'm sure! ;-)

Thanks for the incredible work!!

**Comment by mbyor** [comment]
That's already fixed ;)

https://github.com/denoland/deno/commit/163d60bf16b2c62192b5bf1763ebe6ee2b8c4406

**Comment by bartlomieju** [comment]
This issue can be closed CC @ry
