### ISSUE TITLE
deno serve --parallel=X [script] is not work?

### ISSUE THREAD

**Issue by Octo8080X** [denoland/deno#25195]
Version: Deno 1.46.0

`deno serve --parallel=X [script]` is not work?

I tried running `deno serve --parallel=X [script]` with reference to [Deno 1.46: The Last 1.x Release](https://deno.com/blog/v1.46#faster-deno-serve), but it does not seem to work.

```sh
$ deno -V

deno 1.46.0

$ deno serve main.ts
deno serve: Listening on http://0.0.0.0:8000/   <= OK

$ deno serve --parallel main.ts
deno serve: Listening on http://0.0.0.0:8000/ with 6 threads  <= OK

$ deno serve --parallel=4 main.ts
error: unexpected value '4' for '--parallel' found; no more were expected  <= ERROR

Usage: deno serve --parallel [SCRIPT_ARG]...
```

**Comment by uki00a** [comment]
Currently, it appears that `DENO_JOBS` is required to specify the number of workers :eyes:

```shell
$ DENO_JOBS=2 deno serve --parallel main.ts
```

**Comment by Octo8080X** [comment]
@uki00a 

Thank you.

I used `DENO_JOBS` env and I was able to confirm that it works too.
