### ISSUE TITLE
deno publish fails with 'unresolvable 'jsr:' dependency', for a package with self references

### ISSUE THREAD

**Issue by skybrian** [denoland/deno#25191]
Version: Deno 1.46.2

Using 'deno publish --dry-run' succeeds for a new version of my package, but when I try to publish for real, it fails with this output:

```
% deno publish          
Checking for slow types in the public API...
Visit https://jsr.io/auth?code=VCNJ-FJYZ to authorize publishing of @skybrian/repeat-test
Waiting...
Authorization successful. Authenticated as Brian Slesinsky
Publishing @skybrian/repeat-test@0.2.0 ...
error: Failed to publish @skybrian/repeat-test@0.2.0

Caused by:
    Failed to publish @skybrian/repeat-test at 0.2.0: unresolvable 'jsr:' dependency: '@skybrian/repeat-test@^0.2.0', no published version matches the constraint
```

This isn't really a jsr: dependency; it's a self-reference. I converted a bunch of imports from a relative path to starting with "@skybrian/repeat-test" and it seemed to work locally, so I assumed it was allowed.

I don't know whether this kind of self-reference should be allowed or not, but if they're not allowed, it would have been nice to get an error sooner.

Here is the commit I'm trying to publish: https://github.com/skybrian/repeat-test/commit/7b9d1b3273294ab30c5591792b7c8933e693ed02

**Comment by dsherret** [comment]
> I converted a bunch of imports from a relative path to starting with "@skybrian/repeat-test" and it seemed to work locally, so I assumed it was allowed.

I would highly recommend not doing this. It's just asking for trouble.

**Comment by dsherret** [comment]
I opened https://github.com/denoland/deno/issues/25196 -- Going to resolve this issue that way.

**Comment by skybrian** [comment]
Okay, thanks for the advice! It was an attempted workaround to #25188 but I was fooled by a nondeterministic bug.
