### ISSUE TITLE
Bug: windows cannot exit permission prompt with CTRL+C

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/deno#25209]
## Steps to reproduce

1. Run `deno run npm:create-next-app@latest my-next-app`
2. Press `CTRL+C` when the first permission prompt is shown.

Version: Deno 1.46.1+aebe894

**Comment by marvinhagemeister** [comment]
Wait I cannot consistently reproduce it. Something more seems to be at play here.

**Comment by yazan-abdalrahman** [comment]
https://github.com/user-attachments/assets/f5db9bf6-92e5-48bd-bf2c-cf8615ded7dc

**Comment by marvinhagemeister** [comment]
Closing, I'm not able to reproduce it.
