### ISSUE TITLE
Short flag for `--allow-run` (`-X`?)

### ISSUE THREAD

**Issue by lionel-rowe** [denoland/deno#25201]
The new [short permission flags](https://deno.com/blog/v1.46#short-hand-permission-flags) are a great addition to Deno! IMO it'd be useful to also have one for `--allow-run`.

`-X` seems the obvious choice, by analogy with `rwx` permissions: `deno run -RWX main.ts` would be equivalent to `deno run --allow-read --allow-write --allow-run main.ts`.

**Comment by yazan-abdalrahman** [comment]
Hi @bartlomieju   can provide me direction on where the place of codes relates to Short-hand permission flags, I will work on it.

**Comment by yazan-abdalrahman** [comment]
@bartlomieju 
Please review my change [#25206](https://github.com/denoland/deno/pull/25206)

**Comment by bartlomieju** [comment]
We had several discussions about this one in the past 2 weeks. After much deliberation we decided not to do it - we want to land https://github.com/denoland/deno/pull/25215 which will warn an allow list is not provided when using `--allow-run` and to that end we don't feel it's worth adding a short-hand flag for this particular permission.
