### ISSUE TITLE
[TypeScript] Add Console Interface

### ISSUE THREAD

**Issue by zekth** [denoland/deno#2521]
Following https://github.com/denoland/deno_std/pull/314

It would be nice to add the interface for the console, to manipulate it throught TypeScript.

**Comment by motss** [comment]
Do you mean exposing an interface `Console` like the following?

```ts
// Existing interface from TypeScript 
interface Console {
    memory: any;
    assert(condition?: boolean, message?: string, ...data: any[]): void;
    clear(): void;
    count(label?: string): void;
    debug(message?: any, ...optionalParams: any[]): void;
    dir(value?: any, ...optionalParams: any[]): void;
    dirxml(value: any): void;
    error(message?: any, ...optionalParams: any[]): void;
    exception(message?: string, ...optionalParams: any[]): void;
    group(groupTitle?: string, ...optionalParams: any[]): void;
    groupCollapsed(groupTitle?: string, ...optionalParams: any[]): void;
    groupEnd(): void;
    info(message?: any, ...optionalParams: any[]): void;
    log(message?: any, ...optionalParams: any[]): void;
    markTimeline(label?: string): void;
    profile(reportName?: string): void;
    profileEnd(reportName?: string): void;
    table(...tabularData: any[]): void;
    time(label?: string): void;
    timeEnd(label?: string): void;
    timeStamp(label?: string): void;
    timeline(label?: string): void;
    timelineEnd(label?: string): void;
    trace(message?: any, ...optionalParams: any[]): void;
    warn(message?: any, ...optionalParams: any[]): void;
}

declare var Console: {
    prototype: Console;
    new(): Console;
};
```

**Comment by bartlomieju** [comment]
Scope of this issue has changed and we'd actually prefer to expose `Console` class from Deno - this would allow to create custom console in denoland/deno_std testing module that captured all output.

CC @kitsonk what's your opinion?

**Comment by kitsonk** [comment]
I guess that would be better than someone messing with the global `console`, as just like messing with built-in global prototypes are a bad idea.  Would rather people extend `Console` and create localised instances of something special.

**Comment by bartlomieju** [comment]
> I guess that would be better than someone messing with the global `console`, as just like messing with built-in global prototypes are a bad idea. Would rather people extend `Console` and create localised instances of something special.

Well in `testing` case it is `window.console` that is replaced and restored per case basis, but having ability to create instances of `Console` is much better than [creating object without type check](https://github.com/denoland/deno_std/blame/02262c61612fdeda1ddd9e987f04f320d17b0c89/testing/mod.ts#L27-L52)

**Comment by kitsonk** [comment]
`Console` is exposed globally in Deno.  This can be closed.
