### ISSUE TITLE
Infinte loop in import resolver due to double slashes

### ISSUE THREAD

**Issue by Yohe-Am** [denoland/deno#25223]
Version: Deno 1.46.1

I accidentally introduced an import in the form of:
```ts
// note the double slash
import foo from "..//bar/foo.ts"
```
...in this large codebase I work on and this ended up with deno import resolver going on infinite loop. The number of slashes seem to increase every few milliseconds. I imagine it's due to it re-encountering this troublesome import file again.

I don't have time to create a repro right now but I imagine this happens due to a import cycle in the codebase.

Related to #9427.

**Comment by lucacasonato** [comment]
Closing in favor of https://github.com/denoland/deno/issues/9427.
