### ISSUE TITLE
`DENO_FUTURE` breaks `ssh2`

### ISSUE THREAD

**Issue by littledivy** [denoland/deno#25236]
```js
import { Client } from "ssh2";

const client = new Client();
const p = client
  .on("ready", () => {
    console.log("ready");
  })
  .on("error", (e) => {
    console.log(e);
  })
  .connect({ host: "192.168.1.4", username: "divy", password: "xxx" });
```

```
DENO_FUTURE=1 deno run -A index.mjs
deno: symbol lookup error: /home/divy/gh/deno-ssh/node_modules/cpu-features/build/Release/cpufeatures.node: undefined symbol: node_module_register
```

This works fine with `deno run -A index.mjs`

**Comment by littledivy** [comment]
https://github.com/mscdex/ssh2/blob/be9165bffd729fb52dac9393bafe1d2d6bf49053/lib/protocol/constants.js#L6-L8

```js
let cpuInfo;
try {
  cpuInfo = require('cpu-features')();
} catch {}
```

Without BYONM, `cpu-features` .node wasn't found and would throw an error but with it enabled it proceeds to the actual dlopen phase and crashes.

Maybe we should add explicit throw in `require()` for `cpu-features` like we did for `fsevents`?

**Comment by lucacasonato** [comment]
@littledivy Yes, that seems good.
