### ISSUE TITLE
deno run JSR library does not find packaged assets

### ISSUE THREAD

**Issue by andykais** [denoland/deno#25268]
Version: Deno 1.46.1

I have a package on jsr that is a web server including various build asset files that I want to serve. It seems like I need to do a bit of massaging to make those files visible when running the library when it is downloaded from jsr. Could I get a hand understanding how jsr downloads work? This is my deno.json file:
```json
{
  "name": "@forager/web",
  "version": "0.0.0",
  "license": "MIT",

  "imports": {
    "@andykais/ts-rpc": "jsr:@andykais/ts-rpc@^0.2.2",
    "@forager/core": "jsr:@forager/core@^0.2.1",
    "@std/http/file-server": "jsr:@std/http@0.224.5/file-server",
    "@std/path": "jsr:@std/path@1.0.2",
    "@std/yaml": "jsr:@std/yaml@^1.0.4",
    "cookie": "npm:cookie@^0.6.0",
    "devalue": "npm:devalue@^5.0.0",
    "set-cookie-parser": "npm:set-cookie-parser@^2.6.0"
  },

  "exports": "./mod.ts",

  "publish": {
    "include": [
      "README.md",
      "LICENSE",
      "mod.ts",
      "static/**/*",
      "server/**/*"
    ],
  }
}
```
When I run this package (`deno run -A --unstable-ffi jsr:@forager/web`) I see that any of the asset files respond with 404 Not Found from the server, so clearly its having trouble finding those files:

```
$ curl http://localhost:8000/_app/immutable/entry/start.DT6368wx.js
Not Found
```

Id like to start with even proving that the included files get downloaded with jsr. I am on mac, and a simple `find` operation doesn't see those files in the deno cache:
`find /Users/andrew/Library/Caches/deno/ -name start.DT6368wx.js`

The corresponding jsr file is here in the package: https://jsr.io/@forager/web/0.0.0/static/_app/immutable/entry/start.DT6368wx.js

**Comment by andykais** [comment]
to help debug, my current plan is to publish another version of the package with code like this at the entrypoint:
```ts
console.log(`package exists in dir: ${import.meta.dirname}`)
Deno.cwd(import.meta.dirname)
const files_downloaded = Array.fromAsync(await Deno.readDir('.'))
console.log('the files downloaded:', files_downloaded)
```

but this is pretty barbaric 😅. I just dont have another good way to know where a jsr file is downloaded, or how to edit it in place

**Comment by andykais** [comment]
ignoring the web server aspect of this issue, I think this is just a general question of how can I access assets in a jsr package when it is downloaded? After poking around here it unfortunately seems like deno doesnt download anything besides the required js modules in a package. This is unfortunate since I had a few use cases I was hoping `publish.includes` could help with
- packaging web server assets inside jsr libraries
- avoiding "fetch" steps on initial package runs to download native binaries like https://jsr.io/@db/sqlite ([prior discussion](https://github.com/denoland/deno/discussions/15674#discussioncomment-3503414))

**Comment by dsherret** [comment]
Deno only downloads the part of the package that are imported. This has its pros and cons. At the moment, some of the workarounds are similar to what is possible with deno compile (https://github.com/denoland/deno/issues/20885), but ideally in the future it should be possible to import static files directly via a package export and get them as bytes or whatever and that would cause Deno to download those files even before running the program. Another alternative at the moment is to store the assets on npm and then importing those will cause them to exist on the file system.

**Comment by andykais** [comment]
ok thanks for clarifying @dsherret. Fwiw, I have unblocked myself by handrolling this in an init method here https://jsr.io/@forager/web/0.0.4/mod.ts#L78 by reading the jsr.io package manifest file and fetching it. Like you said, downloading assets by default has its pros and cons. I can totally see someone being annoyed that a `README.md` download is taking up unnecessary network bytes every time they use a package. Perhaps some kind of import pattern would solve this (though I wouldnt want to wait on a tc39 proposal for general static asset imports).

Ill just add that in general what I built here works, but it has overhead that feels like a lot for anyone dealing with non-js package dependencies. Everyone has to:
- download files during runtime
  - since deno packages are designed without an "install" step, this becomes awkward to run implicitly during the first install
  - in a similar vein, this usually means additional permissions need to be included on a package `--allow-net=jsr`, `--allow-read`, `--allow-write`, `--allow-env=XDG_CACHE_DIR` or with some slightly confusing language around "you only need these during the first run"
 - come up with our own file system versioning system. I opted to do `<asset_folder>/<version>/<assets>` and a `<asset_folder>/manifest.json` which tells me the current version I have installed. If I wanted to maintain multiple versions of the package though, I would need to have a slightly different storage pattern.
 - Cleanup is also less clear, and a `deno uninstall` or `deno clean` certainly wont pick these up

**Comment by andykais** [comment]
Imo the best of both worlds would be if `publish.include` optionally had a more complex structure like:
```json
{
  "publish": {
    "include": [
      "README.md",
      {"path": "./static/**/*", "download": true}
    ]
}
```
 field that lets library devs define which files in the package need to be downloaded. Of course, this isnt an all-encompassing solution, since there are libraries like https://jsr.io/@db/sqlite which have binaries per-platform and they ideally want to just install a singular binary. I believe npm/napi/node-gyp 'solve' this by encoding rules into the metadata that chooses which files to retrieve on a particular OS, but that can balloon in complexity pretty fast, so I understand the hesitation to just start building something in deno here

**Comment by dsherret** [comment]
> Perhaps some kind of import pattern would solve this (though I wouldnt want to wait on a tc39 proposal for general static asset imports).

Yeah, most likely it's going to be:

```ts
import bytes from "./some_file.json" with { type: "json", as: "bytes" };
```

**Comment by lucacasonato** [comment]
Closing as #25354
