### ISSUE TITLE
Compressing tar files using CompressionStream broke in Deno 1.43.0

### ISSUE THREAD

**Issue by jespertheend** [denoland/deno#25276]
Version: Deno 1.43.0

This is a reduced test case of a script I'm using to archive and compress several files. In Deno 1.42.4 this creates the archive just fine, but in Deno 1.43.0 this always results in a file of 41 bytes.

To reproduce, store this in a file and run with `deno run -A compress.ts`
```ts
import { copy, readableStreamFromReader, readerFromStreamReader } from "https://deno.land/std@0.204.0/streams/mod.ts";
import { Tar } from "https://deno.land/std@0.204.0/archive/tar.ts";
import * as stdPath from "https://deno.land/std@0.221.0/path/mod.ts";

const selfPath = stdPath.fromFileUrl(import.meta.url);
const tar = new Tar();
tar.append("self.ts", {
	filePath: selfPath,
});
const tarPath = stdPath.resolve(stdPath.dirname(selfPath), "compressed.tar.gz");
const writer = await Deno.open(tarPath, {
	create: true,
	truncate: true,
	write: true,
});
const compressionReader = readableStreamFromReader(tar.getReader()).pipeThrough(new CompressionStream("gzip"))
	.getReader();
await copy(readerFromStreamReader(compressionReader), writer);
writer.close();
```

I think this may have regressed in #21199

**Comment by dsherret** [comment]
I don't think this one is a bug. `copy` doesn't guarantee it copies all the bytes—it returns back a number of bytes that it copies: https://deno.land/std@0.204.0/streams/mod.ts?s=copy

I think the code is just not handling that.

**Comment by dsherret** [comment]
Nevermind, I looked into the implementation of `copy` and it loops to write the whole reader to the writer. This does seem like a bug.

**Comment by 0f-0b** [comment]
`tar.append` returns a promise that isn't `await`ed, so the file might not have been added yet by the time `tar.getReader` is called.

**Comment by lucacasonato** [comment]
I can not reproduce this in Deno 1.46.2. Is there any particular reason you are still on Deno 1.43?

**Comment by dsherret** [comment]
@0f-0b that's the issue.

I'm able to reproduce on canary, but once I await the append the issue no longer occurs.

Still waiting for the day that TypeScript adds diagnostics to disallow floating promises so that we can all be saved from this.

**Comment by jespertheend** [comment]
> Is there any particular reason you are still on Deno 1.43?

Not really, that's just the first version where this started failing. I'd like to use the latest version but I can reproduce this in `1.46.2` as well.
