### ISSUE TITLE
Internal code inconsistency between throw and throw new

### ISSUE THREAD

**Issue by irbull** [denoland/deno#25270]
The JavaScript code that ships with the CLI uses a combination of `throw Error` and `throw new Error`. While `Error()` can be called without new (It will still create a new instance of Error [1]) we should try and be consistent.

[1] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/Error

We took a pass through the `std` and only found a handful of cases where they were not using `new`. It is probably worth the few minutes to do the same for the CLI.

**Comment by marvinhagemeister** [comment]
Took a quick peek: A lot of the minified code of third party libraries uses `throw Error()` instead of `throw new Error()`. It looks like it's a widespread minifaction technique to drop the `new` keyword. That said I'd welcome us only using `throw new Error()` in our own code.

**Comment by irbull** [comment]
I did a few clever greps in the `ext/` folder and there isn't too many that don't use the `new` keyword. Obviously re-throws, but that's fine. There are just a handful like this: https://github.com/denoland/deno/blob/main/ext/web/06_streams.js#L527.

I'll put together a refactor PR for these.
