### ISSUE TITLE
Why does `WebWorker::from_options` instantiate `JsRuntime` with no `SnapshotOptions`

### ISSUE THREAD

**Issue by yuhr** [denoland/deno#25277]
https://github.com/denoland/deno/blob/37501aa32357e75b9ddc92198da94d92fcdd0798/runtime/web_worker.rs#L509

I wonder why this line is always passing `None` for the `snapshot_options`. Is this correct behavior?

I'm creating a TypeScript runtime environment similar to Deno for my gamedev project, starting from [the example](https://github.com/denoland/deno/blob/37501aa32357e75b9ddc92198da94d92fcdd0798/runtime/examples/extension/main.rs) and mimicking the code in [`cli/worker.rs`](https://github.com/denoland/deno/blob/37501aa32357e75b9ddc92198da94d92fcdd0798/cli/worker.rs). As I'm not yet using snapshots, the `startup_snapshot` should be `None` for both `MainWorker` and `WebWorker`. Then when I create a `new Worker(...)` inside the TypeScript code specified by `main_module` of `MainWorker`, I get an error `required type deno_runtime::ops::bootstrap::SnapshotOptions is not present in GothamState container` and it panics. Thus I suspect the cause of the error is the line quoted above.

Shouldn't the line be like following?

https://github.com/denoland/deno/blob/37501aa32357e75b9ddc92198da94d92fcdd0798/runtime/worker.rs#L433-L439

**Comment by bartlomieju** [comment]
Yes, it should. We only ever build with snapshot so it was omitted. PRs are welcome
