### ISSUE TITLE
Homebrew is stuck on upgrading to 1.46

### ISSUE THREAD

**Issue by sspilleman** [denoland/deno#25298]
I see version 1.46 is already available for "a while" (blog post is from aug 22 announcing the new features), but is still not available through homebrew on macOS. 

How long should it normally take to hit homebrew? Im obviously asking because I like some of the new features and dying to try. I could use "deno upgrade", but I don't know how it would interfere with the homebrew installation. Would it be safe?

Thanks!

**Comment by marvinhagemeister** [comment]
Depends on the homebrew maintainers. The homebrew releases are not done by us.

**Comment by BlackAsLight** [comment]
> I could use "deno upgrade", but I don't know how it would interfere with the homebrew installation. Would it be safe?

If you installed Deno via homebrew then `deno upgrade` won't work. You'd need to uninstall Deno and reinstall it by another means.

**Comment by dsherret** [comment]
There's a pending PR here: https://github.com/Homebrew/homebrew-core/pull/181980

For some reason homebrew has a different build system and that leads to issues sometimes (I'm not super familiar with what's going on though).

**Comment by nathanwhit** [comment]
AFAIK it's blocked on https://github.com/denoland/rusty_v8/issues/1587

**Comment by sspilleman** [comment]
@nathanwhit I see you managed to find a workaround in the rusty thread, does that mean it will unblock the homebrew build / push?

**Comment by nathanwhit** [comment]
It _should_ unblock it, I'll follow up with the homebrew maintainers to try to get the PR landed

**Comment by nathanwhit** [comment]
I ended up opening my own PR to homebrew. That has been merged now and 1.46.3 is now available on homebrew

```
❯ brew info deno
==> deno: stable 1.46.3 (bottled), HEAD
```
