### ISSUE TITLE
`deno init --serve` is confusing

### ISSUE THREAD

**Issue by cotyhamilton** [denoland/deno#25305]
This route handler

```ts
{
  pattern: new URLPattern({ pathname: "/static/*" }),
  handler: (req) => serveDir(req, { urlRoot: "./" }),
},
```

paired with this test

```ts
Deno.test(async function serverFetchStatic() {
  const req = new Request("https://deno.land/static/main.ts");
  const res = await server.fetch(req);
  assertEquals(res.headers.get("content-type"), "text/plain;charset=UTF-8");
});
```

Makes it seem like the default template works and serves the main.ts file included in the template but that isn't the case and the response is a 404.

This makes it harder to get started IMO, and trying to figure out the correct folder path to place static files, the correct options to the file server, and wondering why the server doesn't work as expected after watching the tests pass

Possible improvements

- Comments in the files

- Remove the static server test

- Improve (less ambiguous) the static server test by asserting response status 404

- Rewrite the route and test to something like this that serves files from the root

```ts
// serves files from the root
{
  pattern: new URLPattern({ pathname: "/static/*" }),
  handler: (req: Request) => {
    return serveDir(req, { urlRoot: "static" });
  },
},
```

```ts
import denoJson from "./deno.json" with { type: "json" };

// ...

Deno.test(async function serverFetchStatic() {
  const req = new Request("https://deno.land/static/main.ts");
  const res = await server.fetch(req);
  assertEquals(await res.json(), denoJson);
});
```

versions:

```
deno 1.46.1 (stable, release, aarch64-apple-darwin)
v8 12.9.202.2-rusty
typescript 5.5.2
```

**Comment by iuioiua** [comment]
Ah, good catch. Firstly, I think we should test the response status code. Then maybe we should add a `/static` folder with a small/simple `hello.js` that does something super basic, like `console.log("Hello, world!")`. We should keep that folder and just make sure it's correctly served, as we want to showcase [`serveDir()`](https://jsr.io/@std/http/doc/file-server/~/serveDir) from the Standard Library. I'd happily take a look at PR that does these things.

**Comment by cotyhamilton** [comment]
I'll work on a PR for this
