### ISSUE TITLE
Update no-window lint rule for Deno 2.0

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#25323]
```
error[no-window]: window is deprecated and scheduled for removal in Deno 2.0
  --> /home/runner/work/ts-ast-viewer/ts-ast-viewer/src/utils/UrlSaver.ts:2[5](https://github.com/dsherret/ts-ast-viewer/actions/runs/10643356414/job/29506813679#step:5:6):7
   | 
25 |       window.history.replaceState(undefined, "", `#${locationHash}`);
   |       ^^^^^^
   = hint: Instead, use `globalThis`
```

**Comment by MujahedSafaa** [comment]
Hi @dsherret, could you please clarify the changes you're looking for in the rule? Are you referring to an update in the message or something else?

**Comment by marvinhagemeister** [comment]
The `window` global is not scheduled for removal anymore, it _is_ removed in Deno 2. The code in `main` is the Deno 2 code so the message should be adjusted.

**Comment by bartlomieju** [comment]
@MujahedSafaa are you working on this change?

**Comment by MujahedSafaa** [comment]
> @MujahedSafaa are you working on this change?

@bartlomieju Yes, I will open a PR now
