### ISSUE TITLE
Add option for deno add to update package.json for npm packages

### ISSUE THREAD

**Issue by redabacha** [denoland/deno#25321]
currently running `deno add` will only update the deno configuration `imports` field however this isn't always desirable. for example when using typescript directly for type checking in a project rather than deno's type checker, intellisense imports will not work unless they're specified in the package.json.

with npm packages in `deno.jsonc` `imports`:
<img width="822" alt="Screenshot 2024-08-31 at 11 15 35" src="https://github.com/user-attachments/assets/89922158-9e7e-42e7-9834-70930a086258">

with npm packages in `package.json` `dependencies`:
<img width="820" alt="Screenshot 2024-08-31 at 11 16 39" src="https://github.com/user-attachments/assets/aabfb598-131a-404d-b97e-28bc979eaebd">

**Comment by redabacha** [comment]
i've noticed that if the package.json is gone entirely, then it also seems to work as expected. i'm not familiar with typescript/vscode internals but i guess it's falling back to checking the node_modules folder if the package.json is missing?

**Comment by dsherret** [comment]
We're going to update it to add npm dependencies to the package.json if it exists. Otherwise it will continue to add to the deno.json.
