### ISSUE TITLE
Consider switching DENO_TLS_CA_STORE to mozilla,system by default for Deno 2

### ISSUE THREAD

**Issue by rajsite** [denoland/deno#25331]
As a Deno 2 change it would be helpful for enterprise users to have Deno configured to leverage the system cert store by default (based on the `DENO_TLS_CA_STORE` env config having the default be `mozilla,system`).

That seems to be the effective default config for [Firefox](https://support.mozilla.org/en-US/kb/automatically-trust-third-party-certificates) (where users can opt-out of trusting the system cert store) and would provide a better out of the box experience for users.

As-is the error messages that occur using deno directly or tools built with deno (i.e. `deployctl`) can have unclear error messages when used in an environment that requires leveraging the system store.

**Comment by lucacasonato** [comment]
We tried this, but `DENO_TLS_CA_STORE=mozilla,system` causes a ~7.5x startup slowdown for this case:

```ts
const resp = await fetch("https://example.com");
await resp.text();
```

So unfortunately we will not implement this, because it is too slow, especially for users that don't actually need this.

What we could do, is improve the error message to say "Run again with DENO_TLS_CA_STORE= mozilla,system" - tracking that in https://github.com/denoland/deno/issues/25366

**Comment by lucacasonato** [comment]
Node does not read certificates from system store at all. Do you have a `NODE_EXTRA_CA_CERTS` flag set?

We could consider just accepting the `NODE_EXTRA_CA_CERTS` flag if this is something that enterprise IT just has configured on all machines.

**Comment by rajsite** [comment]
> Node does not read certificates from system store at all. Do you have a `NODE_EXTRA_CA_CERTS` flag set?
> 
> We could consider just accepting the `NODE_EXTRA_CA_CERTS` flag if this is something that enterprise IT just has configured on all machines.

I appear to be mistaken. Running [your example](https://github.com/denoland/deno/issues/25331#issuecomment-2324983604) in node does fail on my system:

```
C:\Users\mraj\Desktop>node test.mjs
node:internal/deps/undici/undici:13179
      Error.captureStackTrace(err);
            ^

TypeError: fetch failed
    at node:internal/deps/undici/undici:13179:13
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async file:///C:/Users/mraj/Desktop/test.mjs:1:14 {
  [cause]: Error: unable to get local issuer certificate
      at TLSSocket.onConnectSecure (node:_tls_wrap:1679:34)
      at TLSSocket.emit (node:events:520:28)
      at TLSSocket._finishInit (node:_tls_wrap:1078:8)
      at ssl.onhandshakedone (node:_tls_wrap:864:12) {
    code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY'
  }
}

Node.js v22.7.0
```

I had extrapolated that because I seem to have no issues with `npm` and other tooling (like playwright package postinstall scripts that fetch browser downloads) that node must be well-configured. I'm not sure why `npm` does not have issues.

**Comment by lucacasonato** [comment]
Ah, that's unfortunate. We are working on some diagnostics that we can run during Deno installation, where we can probe for secure TLS connectivity, and if it fails point users to documentation on the topic. Hopefully that can help make people more aware of the possible issues here.

**Comment by rajsite** [comment]
Adding a note that recent versions of node do support system cert stores when [`NODE_USE_SYSTEM_CA=1`](https://nodejs.org/en/learn/http/enterprise-network-configuration#adding-ca-certificates-from-the-system-store) is set now.
