### ISSUE TITLE
Deno 2.0: BYONM should only be enabled when root folder has package.json

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/deno#25355]
For some reason it seems like having a `package.json` in a different workspace member affects resolution in a workspace member that doesn't have one. In this case the "Could not find matching package in `package.json` file" error is thrown in a workspace member that has no `package.json`.

## Steps to reproduce

1. Clone https://github.com/zemili-group/moonrepoV3
2. Run `cd apps/zemili/backend/`
3. Run `deno task dev`

Output:

```sh
error: Could not find a matching package for 'npm:path-to-regexp@6.2.1' in a package.json file. You must specify this as a package.json dependency when the node_modules folder is not managed by Deno.
    at https://jsr.io/@oak/oak/16.1.0/deps.ts:87:8
```

Version: Deno 2.0.0-rc.0+42cf762

**Comment by bartlomieju** [comment]
Duplicate https://github.com/denoland/deno/issues/23267

**Comment by marvinhagemeister** [comment]
Reopening, because this issue is not a duplicate of #23267 . That one isn't about workspaces but this one is.
