### ISSUE TITLE
`deno install --allow-*` should not work without `-g`

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#25362]
`deno install -A jsr:@std/fs` makes no sense.

**Comment by marvinhagemeister** [comment]
I don't understand why this should not work. Wouldn't that be essentially the same as `deno add jsr:@std/fs` ?

**Comment by lucacasonato** [comment]
yes, and we don't support `deno add -A jsr:@std/fs` either? `-A` does nothing for commands that don't spawn V8, and this subcommand does not spawn V8. Like we also support `deno install --allow-read jsr:@std/fs`, which also makes no sense

**Comment by marvinhagemeister** [comment]
Ah I see so it's about `-A` specifically.

**Comment by lucacasonato** [comment]
@marvinhagemeister I mean, not it's about all the permission flags - they should not be accepted without `-g`, because they make no sense outside of `-g` :)
