### ISSUE TITLE
DOCS - Benchmarks page missing app.bundle.js

### ISSUE THREAD

**Issue by isAdrisal** [denoland/deno#2536]
**Affected page:** [https://denoland.github.io/deno/benchmarks.html](https://denoland.github.io/deno/benchmarks.html)

**Issue:**
- Page shows errors in console, with missing app.bundle.js file
- Clicking on `recent data` and `all data` links does nothing

**Steps to reproduce**
- Navigate to page and click on `recent data` and `all data` benchmark links

![error](https://user-images.githubusercontent.com/29012873/59566409-5d3f2880-90a3-11e9-80bd-7881703aa852.jpg)

**Comment by bartlomieju** [comment]
Please access benchmarks via https://deno.land/benchmarks.html
