### ISSUE TITLE
`deno run` cannot run task names with `npm:` prefix

### ISSUE THREAD

**Issue by LitoMore** [denoland/deno#25373]
Version: Deno 1.46.2

This is related to #25232. We just found more edge cases.

Other prefixes (`jsr:`, `github:`, `file:`, ...) need to be checked as well.

**Comment by lucacasonato** [comment]
We've discussed this internally, and this is working as intended.

`deno run` always prioritizes running _code_, which means it first and foremost treats it's arguments as file paths. For example you also can not run a task named `./task.ts` with `deno run`, as it will attempt to load that file. Only if a task does not look like a file path or module specifier will we attempt to look for tasks and run them.

Instead you should use `deno task` to run tasks like this (or better, rename your task!).

**Comment by LitoMore** [comment]
@lucacasonato Ah, I see. I thought `deno task` would be removed in the Deno 2.

Thank you for your explanation.

**Comment by liigo** [comment]
from deno 1.46 blog:

> `deno` and `deno run` were changed to provide a more ergonomic way of doing common tasks.

so the new `deno` is the old `deno run`, and new `deno run` (i think) will be dedicated to run tasks.

**Comment by lucacasonato** [comment]
Everything is staying exactly as is for Deno 2 in this regard:

- deno: run / repl
- deno run: run (and as a fallback execute tasks)
- deno task: tasks
