### ISSUE TITLE
Create v2 JSON schema for `deno.json`

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#25380]
With changes to the `nodeModulesDir` setting, we should update the schema file (or create a new version), currently using `nodeModuleDir: "auto"` results in a warning:

<img width="1237" alt="Screenshot 2024-09-03 at 11 33 02" src="https://github.com/user-attachments/assets/e8e98377-d9c4-48b1-9a74-6f3f03400a7c">

**Comment by dsherret** [comment]
It looks like this is stored in the extension: https://github.com/denoland/vscode_deno/blob/8444e87de1f2657ea8bca7e79de2a6812207715d/package.json#L588

We might need to improve the extension to conditionally select based on the deno version installed.

**Comment by bartlomieju** [comment]
With #25653 this seems to be done, we elected not to provide two separate schemas.
