### ISSUE TITLE
Log more information when a postinstall script fails

### ISSUE THREAD

**Issue by redabacha** [denoland/deno#25396]
currently it seems deno will only report that a postinstall script has failed and not any reason why as such. other package managers like yarn will dump the stdout/stderr of the postinstall script process to a temporary file on disk which is useful for debugging and it would be great if deno did a similar thing, even if it's just logging directly to the terminal.

**Comment by redabacha** [comment]
actually with that said, sometimes i see error output but it doesn't always show when running locally. maybe it's related to the loading indicator?

**Comment by nathanwhit** [comment]
> maybe it's related to the loading indicator?

Yeah I think this is correct, it looks like the progress bar is writing over the postinstall script output. I'll look into this
