### ISSUE TITLE
suggestion: deprecate `Deno.kill()`

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno#25405]
IIUC, it has no other use case outside spawned processes. After Deno 2, one can just use [`Deno.ChildProcess.prototype.kill`](https://docs.deno.com/api/deno/~/Deno.ChildProcess.prototype.kill). At this point, the deprecation can happen at Deno 2, and the removal sometime after.

**Comment by lucacasonato** [comment]
`Deno.kill` is useful to kill process groups by passing in a negative process id. This is not possible with `ChildProcess.prototype.kill`.
