### ISSUE TITLE
WASM instantiation doesn't work properly

### ISSUE THREAD

**Issue by ry** [denoland/deno#2544]
Here's an example program:
```js
const global = new WebAssembly.Global({value:'i32', mutable:true}, 0);
const mem = new WebAssembly.Memory({initial:10, maximum:100});

let wasmImports = {
  js: { global, mem },
};

async function main() {
  console.log(" ok 1");
  let bytes = Deno.readFileSync('./global.wasm');
  console.log(" ok 2");
  window.wasm = await WebAssembly.instantiate(bytes, wasmImports)
  console.log(" ok 3");
}

main();
```
It will never reach "ok 3"

The file `global.wasm` is produced from the following file `global.wat`:
```wat
(module
  (global $g (import "js" "global") (mut i32))
  (import "js" "mem" (memory 1))
  (func (export "getGlobal") (result i32)
        (global.get $g))
  (func (export "incGlobal")
        (global.set $g
                    (i32.add (global.get $g) (i32.const 15))))
  (func (export "retSize") (result i32)
        (memory.size)
  )
)
```
by running `wat2wasm global.wat`

**Comment by kevinkassimo** [comment]
#1325 is also related to this: seems we currently do not wait for any async wasm operations.

**Comment by ry** [comment]
Debugging further reveals that setting the V8 flag `--no-wasm-async-compilation` will make this work properly.

I think that `v8::platform::PumpMessageLoop()` needs to be called in order to support async compilation.

**Comment by ry** [comment]
ref https://bugs.chromium.org/p/v8/issues/detail?id=6263
