### ISSUE TITLE
`deno install -g` should not type check by default

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#25456]
But it should respect the `--check` flag.

**Comment by sigmaSd** [comment]
I don't think its a good idea, the script installed is already not type-checked (its just `deno run url`) so at installation time is a great time to typecheck, also install runs only once and infrequently when the script needs to be updated.

**Comment by lucacasonato** [comment]
@sigmaSd I have two counter points:

- Type checking is something the code author should do, not end users - that's why we don't type check the dependencies you pull in.
- `deno install` doesn't just check the code of the program you are installing (like `deno check` does), but it type checks the program + all of it's dependencies (the equivalent of `deno check --all`). That however is very prone to giving you diagnostics that are not relevant to the final installed program anymore.

So a better default is to not check in install, and just have the code author type check the program before distributing. Also a user that really wanted type checking could still run with `--check`.

**Comment by nathanwhit** [comment]
It looks like this is already the case.

```ts
// main.ts
Deno.fake;
```

```
❯ deno install -gf ./main.ts
✅ Successfully installed global-install-no-typecheck
/home/.deno/bin/global-install-no-typecheck
```

```
❯ deno install -gf --check ./main.ts
Check file:///home/global-install-no-typecheck/main.ts
error: TS2339 [ERROR]: Property 'fake' does not exist on type 'typeof Deno'.
Deno.fake;
```

**Comment by bartlomieju** [comment]
@lucacasonato please take a look

**Comment by lucacasonato** [comment]
You are right, this is already the case - my bad.
