### ISSUE TITLE
error: unexpected argument '--unstable' found / Deno.dlopen is not a function

### ISSUE THREAD

**Issue by tiagosiebler** [denoland/deno#25463]
Version: Deno 1.46.3

Not sure if I'm missing something super obvious here... following this:
https://docs.deno.com/runtime/reference/cli/jupyter/

```
$ deno jupyter --unstable --install           
error: unexpected argument '--unstable' found

  tip: a similar argument exists: '--install'

Usage: deno jupyter --install
```

On macOS. I do actually have jupyter working with deno in vscode, after running install without the unstable flag, but I'm troubleshooting the "Deno.dlopen is not a function" error when running this import:
```typescript
import { createCanvas } from "https://deno.land/x/skia_canvas/mod.ts";
```

Googling doesn't give much other than deno isn't running with --unstable, so I'm wondering if this comes down to not being able to run the install command with the unstable flag. In case these suggestions come up, my deno kernel.json (added flags based on suggestions online):
```json
{
  "argv": [
    "/Users/ts/.deno/bin/deno",
    "--unstable",
    "--unstable-ffi",
    "jupyter",
    "--kernel",
    "--conn",
    "{connection_file}"
  ],
  "display_name": "Deno",
  "language": "typescript"
}
```

My settings.json in vscode:
```json
{
  ...,
  "deno.unstable": true,
  "deno.enable": true,
  "deno.lint": true
}
```

I've even tried editing the notebook ipynb file as plain text, in case there's hardcoded info overriding the flags to exclude unstable. I saw kernelspec under "metadata", so I modified that too, same issue:
```json
  ...,
  "metadata": {
    "kernelspec": {
      "argv": [
        "/Users/ts/.deno/bin/deno",
        "--unstable",
        "--unstable-ffi",
        "jupyter",
        "--kernel",
        "--conn",
        "{connection_file}"
      ],
      "display_name": "Deno",
      "language": "typescript",
      "name": "deno"
    },
    "language_info": {
      "codemirror_mode": "typescript",
      "file_extension": ".ts",
      "mimetype": "text/x.typescript",
      "name": "typescript",
      "nbconvert_exporter": "script",
      "pygments_lexer": "typescript",
      "version": "5.5.2"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 4
```

am I missing something obvious here?

**Comment by bartlomieju** [comment]
Try removing `--unstable` flag and everything should work as expected.

**Comment by tiagosiebler** [comment]
It installs without the unstable flag, but then I'm back at the  "Deno.dlopen is not a function" error, which Google suggests is due to the missing unstable flag

**Comment by bartlomieju** [comment]
Does it work if your kernelspec file looks like this?
```
{
  "argv": [
    "/Users/ts/.deno/bin/deno",
    "jupyter",
    "--unstable-ffi",
    "--kernel",
    "--conn",
    "{connection_file}"
  ],
  "display_name": "Deno",
  "language": "typescript"
}
```

**Comment by tiagosiebler** [comment]
Unfortunately not, I've tried both the `~/Library/Jupyter/kernels/deno/kernel.json` as well as the kernelspec object in the "metadata" object of the ipynb file, when edited in a plaintext editor.

The first json comes from the listed kernel location, so this should be the one used...
```
$ jupyter kernelspec list                     
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
Available kernels:
  deno       /Users/ts/Library/Jupyter/kernels/deno
  jslab      /Users/ts/Library/Jupyter/kernels/jslab
  tslab      /Users/ts/Library/Jupyter/kernels/tslab
  python3    /Library/Frameworks/Python.framework/Versions/3.11/share/jupyter/kernels/python3
```

Not sure it matters but I'm doing my testing here using VS Code. 


---

Further note, just realised I probably haven't upgraded jupyter in a long time (I don't really use it - trying it out now that I saw the TS support). Upgraded it via pip: `$ pip install -U jupyter`

Interestingly I get a new complaint now, if the unstable-ffi flag is _after_ the "jupyter" portion of the command (I've tried with and without the `--unstable` flag just in case as well):
<img width="1518" alt="Screenshot 2024-09-05 at 22 52 11" src="https://github.com/user-attachments/assets/50b7e6e5-da63-4f99-bd9a-4c7203e082e2">

If I move it before, it runs without complaint but the original error is back... Made a new notebook just in case that might interfere, issue persists there. Logs in VS Code show the flags being passed:
<img width="1195" alt="Screenshot 2024-09-05 at 22 48 13" src="https://github.com/user-attachments/assets/4ba2ef04-8de4-4ced-bdac-3577b76a8877">

**Comment by tiagosiebler** [comment]
Hey @crowlKats, thanks for merging a fix via #25483 

How can I use the latest version? Is the only option to pull and build deno from source? Or will a release happen soon?

**Comment by crowlKats** [comment]
@tiagosiebler you could use `deno upgrade canary`, which updates to the latest commit

**Comment by tiagosiebler** [comment]
Thanks for the quick reply! Will try that. Is that in the docs? If not, would be nice adding it somewhere like here, where I was digging around:
https://docs.deno.com/runtime/fundamentals/installation/

**Comment by tiagosiebler** [comment]
Fix confirmed! Thanks again @crowlKats
