### ISSUE TITLE
Bug: "No such file or directory" after `deno install`

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/deno#25493]
## Steps to reproduce

1. Install latest canary build via `deno upgrade --canary`
2. Clone https://github.com/zemili-group/moonrepoV3
3. Run `deno install`

Output:

```sh
$ deno install
error: No such file or directory (os error 2), symlink '../../../../../node_modules/.deno/svelte@4.2.12/node_modules/svelte' -> '/Users/marvinh/dev/test/moonrepoV3/apps/opsap/clients/mobile/node_modules/svelte'
```

Version: Deno 2.0.0-rc.1+f0a3d20

**Comment by algoflows** [comment]
@marvinhagemeister blocked again sorry guys trying to setup a second developer and deno install isn't working.
