### ISSUE TITLE
`.cjs` extension is supported, but not `.cts` in version 2 (rc)

### ISSUE THREAD

**Issue by wellwelwel** [denoland/deno#25498]
Version: Deno 2.0.0-rc.1

I noticed that, in version 2, I can run `.cjs` files, but not `.cts` files. Using any version from 1.x.x onwards, including the latest (1.46.3), both runs work fine.

I'd like to understand it better:

Is it intentional to accept `.cjs` but not `.cts` (not an issue), should both not be supported or should both work as in previous major version?

The message error:

```
Expected a JavaScript or TypeScript module, but identified a Cts module. Importing these types of modules is currently not supported.
```

- Perhaps "unrecognized" fits better than "not supported" for this report.
- This error doesn't occur during import, but with the `deno run` command.

---

For a brief context, these tests are totally empty files, just to make sure that a test runner is properly targeting each file by extension according to how each runtime (**Node.js**, **Bun** and **Deno**) handles them.

#### Before `v2` (1.46.3):

<img width="538" alt="Screenshot 2024-09-06 at 21 10 12" src="https://github.com/user-attachments/assets/fd928894-e858-40e6-952d-b00ae74d5c7a">

#### After `v2` (2.0.0-rc.1):

> <img width="1054" alt="Screenshot 2024-09-06 at 21 17 14" src="https://github.com/user-attachments/assets/74f3b547-c220-4cc5-afeb-a5d2b19107ad">

<img width="599" alt="Screenshot 2024-09-06 at 21 19 00" src="https://github.com/user-attachments/assets/740fd8e9-16a1-451d-bad2-29f3a1d6ea8a">

---

### Minimal Reproduction

`test.cts`

```ts
console.log(123);
```

```sh
deno run test.cts
```

Output:

```
error: Expected a JavaScript or TypeScript module, but identified a Cts module. Importing these types of modules is currently not supported.
  Specifier: file:///***/test.cts
```

---

Being my first issue here, thanks for **Deno** 🦕💙

**Comment by wesbos** [comment]
hitting this as well in an app where 1 file must be a commonJS file due to some limitations on ESM module cache, but I'd also like for it to be TypeScript. No way around this right now?

**Comment by dsherret** [comment]
Not at the moment. We put it off because the use of cts files seems low at the moment (https://github.com/search?type=code&q=path%3A*.cts), but we'd like to do it soon.

**Comment by wesbos** [comment]
Ah yeah, makes sense. I ended up just stripping the types from that file but it turns out I don't even need any of the weird cache stuff I'm doing in Node because of hmr in deno.

**Comment by dsherret** [comment]
I have a draft PR here: https://github.com/denoland/deno/pull/26558

![image](https://github.com/user-attachments/assets/df90b0dd-b37b-406b-995d-f8d2fdcd5d5e)
