### ISSUE TITLE
Formatting issues when tsconfig file has unsupported compiler options

### ISSUE THREAD

**Issue by KluVerKamp** [denoland/deno#2550]
The warning message "Unsupported compiler options ..." is written in yellow/gold but at the same line as the "Compiling" notice 
```
$ echo $BASH_VERSION 
5.0.2(1)-release
$ deno --config tsconfig.json examples/db/app.ts 
[0/1] Compiling file:///Users/user/Batcave/deno/alosaur/examples/db/app.tsUnsupported compiler options in "/Users/user/Batcave/deno/alosaur/tsconfig.json"
  The following options were ignored:
    baseUrl, moduleResolution, noEmit, pretty
```

**Comment by kitsonk** [comment]
There are a few issues when we exit compiling and start outputting something else we need to clean up. Not only this.

**Comment by bartlomieju** [comment]
This issue should no longer occur now, that 3a4d88475b40a17f2ce17b775a3f07c78be83d79 landed
