### ISSUE TITLE
Feat: Log out which file changed on HMR change or watch change

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/deno#25504]
Suggested on discord https://discord.com/channels/684898665143206084/684911491035430919/1281952471127687219

> Is there a deno cli flag to have more information on which file is changed when it log:
"HMR File change detected! Restarting!"

I think it would be a good idea to show.

**Comment by HasanAlrimawi** [comment]
I'd like to tackle this issue if not assigned...
