### ISSUE TITLE
support for JSDoc `@import`

### ISSUE THREAD

**Issue by mayank99** [denoland/deno#25516]
[TypeScript 5.5](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-5.html#the-jsdoc-import-tag) adds support for `@import` in JSDoc comments. It would be great if Deno could also support this.

```js
/** @import { SomeType } from "npm:some-module" */
```

**Comment by mayank99** [comment]
Actually I think this is automatically handled by VSCode (and maybe other IDEs) but only in JS files.

It's possible that Deno might still need to add support for this if someone wants to generate type declarations, but for now I'd say no action is needed.

**Comment by FND** [comment]
@mayank99, please allow me to pick this up again. I'm not quite sure what you're referring to when you say "this is automatically handled by VSCode": Am I correct in assuming your type checking only happens within VSCode?

As far as I can tell¹, Deno itself (via `deno check` on the command line) does not yet support `@import` though, as [confirmed by another user](https://questions.deno.com/m/1276039393773359148). This seems like a significant discrepancy vis-à-vis TypeScript's official tooling (including the language server used by IDEs), so I believe your original post remains an valid issue.

tested with Deno 2.0.1 / TypeScript 5.6.2

**Comment by FND** [comment]
Thanks, I appreciate that.

Just to confirm, and perhaps to simplify analysis, here's a minimal test case - starting with a single JS file to make sure type checking itself works as expected:

📄 `index.js`
```javascript
/** @typedef {string | null} Entry */

/** @type {Entry[]} */
const items = [];

items.push("hello");
items.push(null);
items.push(123); // 💥
```
📄 `tsconfig.json`
```json
{
    "compilerOptions": {
        "allowJs": true,
        "checkJs": true,
        "noEmit": true,
        "strict": true
    }
}
```
```shell
$ deno check --config ./tsconfig.json ./index.js
error: TS2345 [ERROR]: Argument of type '123' is not assignable to parameter of type 'Entry'.
```

After moving this type definition into a separate file, Deno *falsely* reports everything's fine:

📄 `index.js`
```javascript
/** @import { Entry } from "./util.js" */

/** @type {Entry[]} */
const items = [];

items.push("hello");
items.push(null);
items.push(123); // 💥
```
📄 `util.js`
```javascript
/** @typedef {string | null} Entry */
```
```shell
$ deno check --config ./tsconfig.json ./index.js && echo OK
OK
```

If we now replace that `@import` line with an old-style `@typedef` import, Deno correctly reports the type error again:
```
/** @typedef {import("./util.js").Entry} Entry */
```

(tested with both Deno 1.46.3 and 2.0.1)
