### ISSUE TITLE
npm:@blockly/field-multilineinput: exported function is TypeError when trying to call it as function

### ISSUE THREAD

**Issue by joeftiger** [denoland/deno#25531]
deno 1.46.3 (stable, release, x86_64-pc-windows-msvc)
v8 12.9.202.5-rusty
typescript 5.5.2

I am developing an application using Fresh to serve a Blockly workspace and run into compiler issues.
So far I have been able to use extensively Blockly and some of its plugins by defining the import map NPM-style:
```json
"imports": {
  "@blockly/field-date": "npm:@blockly/field-date@9.0.9",
>  "@blockly/field-multilineinput": "npm:@blockly/field-multilineinput@5.0.10",
  "@blockly/plugin-cross-tab-copy-paste": "npm:@blockly/plugin-cross-tab-copy-paste@6.0.9",
  "@blockly/shadow-block-converter": "npm:@blockly/shadow-block-converter@6.0.9",
  "blockly": "npm:blockly@11.1.1",
  "blockly/": "npm:blockly@11.1.1/"
}
```
While no other blockly plugin make any ruckus (theirexported functions work), the [`@blockly/field-multilineinput`](https://github.com/google/blockly-samples/tree/master/plugins/field-multilineinput) makes problems when trying to call its exported function:

```typescript
import * as MultilineInput from "@blockly/field-multilineinput";

MultilineInput.registerFieldMultilineInput();
```
Error:
```text
error: Uncaught (in promise) TypeError: MultilineInput.registerFieldMultilineInput is not a function
MultilineInput.registerFieldMultilineInput();
               ^
```
Try 2:
```typescript
import {registerFieldMultilineInput} from '@blockly/field-multilineinput';

registerFieldMultilineInput();
```
Error 2:
```text
error: Uncaught (in promise) SyntaxError: The requested module '@blockly/field-multilineinput' does not provide an export named 'registerFieldMultilineInput' at file:///....
  const manifest = (await import(toFileUrl(join(dir, "fresh.gen.ts")).href))
                    ^
    at async dev (https://deno.land/x/fresh@1.7.1/src/dev/dev_command.ts:38:21)
    at async file:///.../dev.ts:8:1
```

I have tried it in a completely empty Deno project with the same results. Changing the import statement to directly use the function does not work either.

Q1: Am I doing smth. wrong or is it actually supposed to work? Or is it actually a bug in fresh during imports?

**Comment by nicolo-ribaudo** [comment]
It's because that package is supposed to be used like this:
```js
import MultilineInput from "@blockly/field-multilineinput";

MultilineInput.registerFieldMultilineInput();
```

**Comment by joeftiger** [comment]
@nicolo-ribaudo Thank you very much for the fix!
It seems like Deno itself doesn't have a problem anymore and I can see the plugin's console print.

The Fresh webapp now makes problems though and renders a blank page with the following error in the console:
```text
index.ts:12 Uncaught TypeError: Cannot read properties of undefined (reading 'registerFieldMultilineInput')
```
I've checked and while the the watcher in the terminal can see `MultilineInput` as a module, the browser fails with it being `undefined`.
I can "fix" the page when I move these statements to my island of Fresh that initializes the page.
The effect, however, comes too late for my own library which initializes things too early.

It seems like my own library setup isn't that great and I have to refactor stuff 😅 .
