### ISSUE TITLE
Module resolution doesn't work correctly when the module specifier includes double slashes `//`

### ISSUE THREAD

**Issue by janispritzkau** [denoland/deno#25532]
Version: Deno 1.46.3

Deno REPL:

```
> import "npm:hono/streaming"
Uncaught TypeError: [ERR_MODULE_NOT_FOUND] Cannot find module 'file:///Users/x/Library/Caches/deno/npm/registry.npmjs.org/hono/4.5.11/dist/helper/utils/stream.js' imported from 'file:///Users/x/Library/Caches/deno/npm/registry.npmjs.org/hono/4.5.11/dist/helper/streaming//stream.js'
    at async <anonymous>:1:22
```

I'm not quite sure how this happens. I notice that there are two slashes in the "imported from" module.

**Comment by janispritzkau** [comment]
The JSR version works, though:

```
> import "jsr:@hono/hono/streaming"
[Module: null prototype] {
  SSEStreamingApi: [class SSEStreamingApi extends StreamingApi],
  stream: [Function: stream],
  streamSSE: [Function: streamSSE],
  streamText: [Function: streamText]
}
```

**Comment by janispritzkau** [comment]
It looks like `./` gets resolved to `.//index.js`.

```ts
import type { Context } from '../../context'
import { TEXT_PLAIN } from '../../context'
import type { StreamingApi } from '../../utils/stream'
import { stream } from './'
```

```js
import { TEXT_PLAIN } from "../../context.js";
import { stream } from ".//index.js";
```

**Comment by kt3k** [comment]
Thanks for the report.

> ```js
> import { TEXT_PLAIN } from "../../context.js";
> import { stream } from ".//index.js";
> // ...
> ```

I confirmed this specifier `".//index.js"` exists at `/dist/helper/streaming/text.js` in hono, and that seems causing the issue.

A more minimal reproduction is:

a.js
```js
import "./b//c.js";
```
b/c.js
```js
import "../d.js";
```
d.js
```js
console.log("hi");
```

When executing `a.js`, Deno throws:

```
$ deno a.js 
error: Module not found "file:///path/to/b/d.js".
    at file:///path/to/b//c.js:1:8
```

(Deno seems considering `dir//file` is 2 level deeper from `dir` without normalizing `//` part)

While Node executes this without problem.

**Comment by kt3k** [comment]
This looks fixed in Hono's side (https://github.com/honojs/hono/pull/3405 )

@janispritzkau Can you try again with the latest version of Hono?

```js
import "npm:hono@4.6.1/streaming";
```

**Comment by marvinhagemeister** [comment]
It's great that the hono team simplified the import, but we should be able to deal with `./` imports in npm packages regardless imo.

**Comment by janispritzkau** [comment]
@kt3k Yes, that works. Thank you.

I also think this should be fixed on Deno's end. It seems like extra slashes being ignored in path resolution is a common behavior.

**Comment by kt3k** [comment]
I agree that this should also be fixed on Deno's side. I updated the title to clarify the problem.
