### ISSUE TITLE
Fails importing module with basename `.ts`

### ISSUE THREAD

**Issue by yuhr** [denoland/deno#25541]
Version: Deno 1.45.2

Suppose in the current directory I have a module named `.ts` with the content being:

```typescript
console.log("hello")
```

`deno run .ts` can run this, while importing this module from another module named `hello.ts` emits an error.

```typescript
import "./.ts"
```

```
❯ deno run hello.ts
error: Expected a JavaScript or TypeScript module, but identified a Unknown module. Importing these types of modules is currently not supported.
  Specifier: <CWD omitted>/.ts
    at <CWD omitted>/hello.ts:1:8
```

**Comment by dsherret** [comment]
Just add a filename and don't do this.

**Comment by yuhr** [comment]
@dsherret But why? Is there any reason to ban this filename?

**Comment by dsherret** [comment]
It's not worth the engineering effort to fix this. Just give your files proper names.

**Comment by yuhr** [comment]
One of use cases of this is developing a filesystem-based routing framework. `https://localhost:8000/` should be handled by `routes/.ts`.

If the low engineering resource is the only blocker, I'm going to file a PR myself.

**Comment by dsherret** [comment]
Why not name the file `routes/index.ts`? This is going to cause a decent amount of edge case bugs because `PathBuf::from(".ts").extension()` in Rust is `None`. I don't think we would accept a PR for this change. The file is essentially a hidden file named `ts` with no extension.

**Comment by yuhr** [comment]
`index` special casing is a bad convention in my opinion, but I understand your decision. Thank you for the clarification.

Node.js can handle modules with `.js` basename, so I thought this could also work in Deno.
