### ISSUE TITLE
Deno is panicking no matter what I do.

### ISSUE THREAD

**Issue by Zartust** [denoland/deno#25560]
Version: Deno 1.41.0
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: windows x86_64
Version: 1.41.0
Args: ["C:\\Program Files\\Quarto\\bin\\tools\\x86_64\\deno", "run", "--unstable-ffi", "--no-config", "--cached-only", "--allow-read", "--allow-write", "--allow-run", "--allow-env", "--allow-net", "--allow-ffi", "--v8-flags=--enable-experimental-regexp-engine,--max-old-space-size=8192,--max-heap-size=8192", "--importmap", "C:\\Program Files\\Quarto\\bin\\vendor\\import_map.json", "C:\\Program Files\\Quarto\\bin\\quarto.js", "list", "tools"]

thread 'main' panicked at cli\args\mod.rs:596:14:
Failed to add platform cert to root cert store: InvalidCertificate(BadEncoding)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

I have tried to upgrade deno, tried to install tinytex each thing I do gets me a panick error

**Comment by dsherret** [comment]
I think this is fixed in the latest version of Deno. Try running the install script to get the latest version https://docs.deno.com/runtime/fundamentals/installation/
