### ISSUE TITLE
Empty Worker accessing jsr

### ISSUE THREAD

**Issue by notroid5** [denoland/deno#25562]
Version: Deno 1.46.3

`deno.json`
```typescript
{
  "tasks": {
    "dev": "deno run --allow-read=./ --watch main.ts"
  },
  "imports": {
    "@std/assert": "jsr:@std/assert@1"
  }
} 
```

`main.ts`
```typescript
new Worker(import.meta.resolve("./worker.ts"), { type: "module" }) 
```

`worker.ts`
```typescript
import {} from "@std/assert" 
```

Expected result: no access requests
Actual result:
```
Deno requests net access to "jsr.io:443".
Requested by `import()` API.
```
It does not seem to depend on what is cached or imported.

**Comment by lucacasonato** [comment]
This is working as intended and documented: https://docs.deno.com/runtime/reference/web_platform_apis/#instantiation-permissions.

You may be interested in https://github.com/denoland/deno/issues/8266
