### ISSUE TITLE
Move from package.json to deno.json -> All Vite projects complain about deprecated CJS mode

### ISSUE THREAD

**Issue by birkskyum** [denoland/deno#25574]
Any project that's built on top of vite in some form (and there's quite a lot now), will check if the package.json has a "type":"module", and otherwise complain with this:

> The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.

If a project only has a deno.json, it's thus necessary to make an extra package.json, just with `{ "type": "module" }` to remove this issue.

I assume it's somehow related to [this](https://github.com/vitejs/vite/blob/587ad7b17beba50279eaf46b06c5bf5559c4f36e/packages/vite/index.d.cts#L1-L6) code in Vite - but some adjustment is needed for deno.json to be fully standalone.

Repro steps here, but any vite project will do:
- https://github.com/denoland/deno/issues/23882#issuecomment-2340783437

**Comment by marvinhagemeister** [comment]
Resolved by https://github.com/vitejs/vite/pull/18081 . Fix will be released in the next vite release.

**Comment by birkskyum** [comment]
Patch released in [vite 5.4.7](https://github.com/vitejs/vite/blob/v5.4.7/packages/vite/CHANGELOG.md#547-2024-09-20)
