### ISSUE TITLE
Proposal: leave `deno run ...` for running scripts and `deno task ...` for running tasks (contrary to recent changes)

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#25575]
Personally I'm not a fan of the recent changes in Deno 1.46 to conflate `deno run` with `deno task`. I think `deno run` should be for running scripts and `deno task` should be for running tasks. For example, the recent changes to `deno run` have made it difficult to support running from an import map https://github.com/denoland/deno/issues/19955

To help people with this, I think we should instead have `deno run <task>` output ``Did you mean `deno task <task>`?``.

**Comment by birkskyum** [comment]
I find myself trying to avoid running tasks with deno run, because i don't want to spend unneeded time searching the file tree, which i know won't happen with deno task.

Is there actually a performance difference here for running tasks, or is it not to be concerned of?

**Comment by bartlomieju** [comment]
After much deliberation internally we decided not to do it; the error
handling was improved in https://github.com/denoland/deno/pull/25708 to
not suggest available tasks anymore.

**Comment by birkskyum** [comment]
@bartlomieju , just to be clear, after these back-and-forth changes, what is the final behavior of `run` and `task`, and to what extend will `run` be able to execute/suggest tasks?

**Comment by bartlomieju** [comment]
`deno run <task>` works - it's an alias for `deno task <task>`. `deno run` will work exactly like before, but if you try to run something like:
```
$ deno run dev
```
The Deno will look for `./dev` file, if it's not present it will look up `dev` task in either `deno.json` or `package.json` and it doesn't exist you will get an error saying that `./dev` file doesn't exist.
