### ISSUE TITLE
Guide users toward a working LSP/tsc setup with Next.js

### ISSUE THREAD

**Issue by nathanwhit** [denoland/deno#25607]
The project produced by create-next-app will, by default, result in deno LSP errors and fail to pass `deno check`.

While we have decided in https://github.com/denoland/deno/issues/25359 that this isn't our bug, the developer experience of trying to figure this out is very poor. I personally spent multiple hours trying to come up with a workaround to no avail, and I suspect many users will struggle as well.

Given that the out-of-the-box experience will not be ideal (due to us considering it not fixable on our end), we should guide users to a working setup more gracefully. This might be done through better error messages or LSP diagnostics, or perhaps an autofix to implement a workaround or change the config.

**Comment by nayeemrmn** [comment]
Tracking issue in next.js repo:
- https://github.com/vercel/next.js/issues/46078

**Comment by bartlomieju** [comment]
With https://github.com/denoland/vscode_deno/pull/1166 landed and released we now have a solution that guides users towards working code. There's still more work we can do in the future, but for now this is good enough.

**Comment by dmint789** [comment]
So should I use the tsc setup in VS Code or the Deno LSP for Next JS projects? I've been using the latter so far, although there is still that issue with imported Next JS components.
