### ISSUE TITLE
When running cjs files, it asks for read permissions.

### ISSUE THREAD

**Issue by sant123** [denoland/deno#25618]
Version: Deno v2.0.0-rc.2

```js
import http from "node:http";

console.log(http);
```
Running the code above works just fine. However I'm curious why cjs files request the `--allow-read` flag?

```js
const http = require("http");

console.log(http);
```

![image](https://github.com/user-attachments/assets/7c0b62c4-a962-41c0-b5d3-b6870a87cda4)
![image](https://github.com/user-attachments/assets/a91b4eb4-af59-4c3d-b8e3-1853f30388aa)

Thanks

**Comment by bartlomieju** [comment]
This is expected, when you run CommonJS files Deno needs to probe file system for `package.json` files to resolve the `require()` calls.

**Comment by sant123** [comment]
The behavior looks weird, for imports it may resolve from package.json or deno.json files and there is no need to include the `—allow-read` flag. Cjs files are just doing the same but using `require` but the operation is the same.

**Comment by bartlomieju** [comment]
> The behavior looks weird, for imports it may resolve from package.json or deno.json files and there is no need to include the `—allow-read` flag. Cjs files are just doing the same but using `require` but the operation is the same.

Correct, but you can do something like that:
```
const name = "ht" + `t` + 'p';
const http = require(name);
```
(it's a bit of overblown example, but using a variable when calling `require()` is common) while for import you need to use a string literal after the `from` keyword.

We can reliably statically analyze which module is getting imported and that's why you are prompted for permissions.

**Comment by sant123** [comment]
Fair enough. Thanks for the explanation 🙏🏼
