### ISSUE TITLE
Bug: Cannot find `vite`

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/deno#25616]
## Steps to reproduce

1. Create a `deno.json` with these contents:
  ```json
  {
    "imports": {
      "vite": "npm:vite@5.4.5"
    },
    "tasks": {
      "dev": "vite"
    }
  }
  ```
2. Create a `vite.config.ts` file with these contents:
  ```ts
  import { defineConfig } from "vite";
  export default defineConfig({});
  ```
3. Run `deno install`
4. Run `deno task dev`

Output:

```sh
$ deno task dev
Task dev vite
failed to load config from /Users/marvinh/dev/test/deno-vite-init/vite.config.ts
error when starting dev server:
Error: Cannot find module 'vite'
Require stack:
- /Users/marvinh/dev/test/deno-vite-init/vite.config.ts
- /Users/marvinh/Library/Caches/deno/npm/registry.npmjs.org/vite/5.4.5/dist/node/chunks/dep-CUvs3bbV.js
    at Function.Module._resolveFilename (node:module:616:15)
    at Function.Module._load (node:module:494:27)
    at Module.require (node:module:678:19)
    at require (node:module:802:16)
    at Object.<anonymous> (file:///Users/marvinh/dev/test/deno-vite-init/vite.config.ts:25:19)
    at Object.<anonymous> (file:///Users/marvinh/dev/test/deno-vite-init/vite.config.ts:31:4)
    at Module._compile (node:module:742:34)
    at Object._require.extensions.<computed> [as .js] (file:///Users/marvinh/Library/Caches/deno/npm/registry.npmjs.org/vite/5.4.5/dist/node/chunks/dep-CUvs3bbV.js:66642:16)
    at Module.load (node:module:659:32)
    at Function.Module._load (node:module:531:12)
```

Version: Deno 2.0.0-rc.2+606b7b1

**Comment by bartlomieju** [comment]
You need to do `nodeModulesDir: "auto"` in config file

**Comment by marvinhagemeister** [comment]
When I add `nodeModulesDir: "auto"` it doesn't find the `vite` command anymore:

```sh
$ deno task dev
Task dev vite
vite: command not found
```

**Comment by bartlomieju** [comment]
That looks like a regression, indeed.

**Comment by nathanwhit** [comment]
I'm fairly sure this never worked. We don't, in general, try to figure out what to autoinstall based just on a bin command

**Comment by birkskyum** [comment]
People who use vite are coming from node, and just talking for myself, I'm really not used to, or particularly interested in, anything related to package auto-installs. Especially not if it's at the cost of a worse manual package install flow (I have the `deno install` crash on me every other time i manually add a package), or if it's introducing avoidable slowdowns like running an "implicit `deno install` before running a task"

**Comment by nathanwhit** [comment]
>  at the cost of a worse manual package install flow (I have the deno install crash on me every other time i manually add a package)
Could you expand a bit on this? I'm not sure I follow

> implicit deno install before running a task

Nevermind about this part, that's not the right fix. I didn't think through it enough 😅

**Comment by birkskyum** [comment]
> Could you expand a bit on this? I'm not sure I follow

Sure, I can see it's not so clear what I meant. I don't see any technical blockers for having both great manual/autoinstall flows - but in the case of prioritization/limited engineering time+resources (and there often is) I'd personally lean far towards making the manual install / task execution flow absolutely stellar, before attempting to automate it.

**Comment by marvinhagemeister** [comment]
FYI: I opened this issue because it occurred _despite_ calling `deno install` manually.

**Comment by bartlomieju** [comment]
@marvinhagemeister does the issue persist for you after you call `deno install` after adding `nodeModulesDir` configuration?

**Comment by birkskyum** [comment]
@bartlomieju , it works if the `deno install` is called after the `nodeModulesDir: auto` is added

**Comment by bartlomieju** [comment]
> It works if the `deno install` is called after the `nodeModulesDir: auto` is added. (deno 2.0.0-rc.2)
> 
> If I set the `nodeModuleDir:true` I see a
> 
> ```shell
> Warning `"nodeModulesDir": true` is deprecated in Deno 2.0. Use `"nodeModulesDir": "auto"` instead`.
> ```
> 
> Instead of having to remember setting this, would it be possible to default `nodeModulesDir: auto` for deno 2, or even remove the nodeModulesDir, if the alternatives are deprecated and there's only the `auto` option left?

It's not the only option left, there's also `local` and `manual`. These will be visible once https://github.com/denoland/deno/issues/25380 is addressed.

**Comment by nathanwhit** [comment]
Oh I've just realized that @marvinhagemeister 's PR to vite (https://github.com/vitejs/vite/pull/18081) will actually fix this as well.

The issue is that vite thinks that the deno project is CJS (fake ESM), so it transpiles it to CJS with `require` – which doesn't respect import maps in deno. After that PR, it doesn't transpile to CJS so it just works

**Comment by marvinhagemeister** [comment]
Can confirm, updating to vite `5.4.7` which includes the fix resolves this.
