### ISSUE TITLE
Deno.openKv is not a function

### ISSUE THREAD

**Issue by Katze719** [denoland/deno#25638]
Version: deno 2.0.0-rc.2 (release candidate, release, x86_64-unknown-linux-gnu)
v8 12.9.202.13-rusty
typescript 5.5.2

using deno via docker container `denoland/deno:latest`

when i try to use `Deno.openKv()` it will spit out this error message: 
```txt
error: Uncaught (in promise) TypeError: Deno.openKv is not a function
const kv = await Deno.openKv()
```

is `/// <reference lib="deno.unstable" />` still required?

**Comment by marvinhagemeister** [comment]
Add the `--unstable-kv` flag to your command like:

```sh
deno run --unstable-kv my-script.ts
```
