### ISSUE TITLE
`performance.now()` and `hrtime` always return an integer-value

### ISSUE THREAD

**Issue by LitoMore** [denoland/deno#25639]
### How to reproduce

```js
import { hrtime } from "node:process";
import { performance } from "node:perf_hooks";
import { setTimeout } from "node:timers/promises";

const start1 = hrtime.bigint();
await setTimeout(10);
const end1 = hrtime.bigint();

console.log(end1 - start1, "ns");

const start2 = performance.now();
await setTimeout(10);
const end2 = performance.now();

console.log(end2 - start2, "ms");
```

```shell
❯ deno index.mjs
12000000n ns
12 ms

❯ bun index.mjs
12187667n ns
11.088624999999997 ms

❯ node index.mjs
10493333n ns
11.270082999999996 ms
```

**Comment by marvinhagemeister** [comment]
In Deno 1.x high precision timers are gated behind the `--allow-hrtime` permission flag. Passing this flag to your command will opt into high precision timers and return a float value.

We've removed this permission in the upcoming Deno 2 release and it will ship with high resolution timers always being enabled. So in Deno 2 you'll get the floats as expected out of the box. You can try a Deno 2 rc release by running `deno upgrade rc`. Use `deno upgrade` to downgrade back to the latest stable release.

Resolved by https://github.com/denoland/deno/pull/25367
