### ISSUE TITLE
@deno-types comment works incorrectly

### ISSUE THREAD

**Issue by happyhunter7** [denoland/deno#25644]
Version: Deno 1.46.3
Using latest version of VScode with latest version of Deno official extension for vscode

The bug:
When using a import that starts with 'type' word, then when you hover in vscode on that type "FC" it shows nothing, which means it could not resolve from where it should be imported or something like that, when ctrl+click on 'react' it also doesn't open the react types file.
```
// @deno-types="@types/react"
import type { FC } from 'react'
```

The Fix:
Move type inside {}, after that everything works as expected, on hover it shows the type definition, and clicking on 'react' word it opens in the editor the react type defs
```
// @deno-types="@types/react"
import { type  FC } from 'react'
```
But with this tow work I have to exclude linter rule 'verbatim-module-syntax'  from linter so that it doesn't complain

Expectation:
Well I expect that both import syntaxes works the same as it does in node, and I get the type definition when howering, and the autocomplition same as in the second scenario but without turning off linter rule verbatim-module-syntax

**Comment by nayeemrmn** [comment]
This occurs with `deno check` as well.

```ts
// @deno-types="npm:@types/react@^18.3.6"
import type { ShouldError as _ } from 'npm:react@^18.3.1';
```

**Comment by nayeemrmn** [comment]
I suppose you may as well write `import type { FC } from '@types/react'` which is kind of why it behaves this way, but it makes more sense to prioritise `@deno-types`. We'll fix it.

**Comment by nayeemrmn** [comment]
Fixed by https://github.com/denoland/deno_graph/pull/529, incorporated in #25469.
