### ISSUE TITLE
Digest method not supported: md4

### ISSUE THREAD

**Issue by littledivy** [denoland/deno#25646]
https://compat.deno.dev/#create-docusaurus-3.1.1

when running `docusaurus build` (`create-docusaurus@3.1.1`)

```
Error: Digest method not supported: md4
    at undefined
```

**Comment by lucacasonato** [comment]
Aahhhhhh why do people use stuff like this :cry:

**Comment by lucacasonato** [comment]
So Node 22 does not ship with md4 support anymore. So I am suspecting that there is some feature detection going on here, that is failing because the error code is not correct. I can't find it yet though.

**Comment by lucacasonato** [comment]
It looks like the Node world has just collectively decided to run with `--openssl-legacy-provider`? Maybe we should implement it by default?

https://github.com/webpack/webpack/issues/14532

**Comment by littledivy** [comment]
> It looks like the Node world has just collectively decided to run with --openssl-legacy-provider

lol
