### ISSUE TITLE
Run CI/CD with dagger to save tons of time on pipelines

### ISSUE THREAD

**Issue by beingminimal** [denoland/deno#25669]
Hi

Start using [dagger](https://dagger.io/) for CI/CD pipelines so we can save a ton of time in pipelines and so we dont need to wait for 2 to 3 hours.
it has many other benefits also please check [here](https://dagger.io/dagger-engine). 

Thank You.

**Comment by lucacasonato** [comment]
Thank you, but we are not planning to change our CI process in the very near future.
