### ISSUE TITLE
question: why doesn't Javascript have optional static typing ?

### ISSUE THREAD

**Issue by catastrop** [denoland/deno#2568]
tc39 is adding new things to JS. But why not optional static typing ?

If they do it, we don't have to use Typescript anymore and being able to pass type information to the engine.

We will have less dev dependency.

**Comment by mtharrison** [comment]
You've asked the same question in a bunch of other places too. Along with lots of other spammy issues. 

<img width="811" alt="Screenshot 2019-06-23 at 11 04 19" src="https://user-images.githubusercontent.com/916064/59974661-cdb7df00-95a6-11e9-927e-4748830b4813.png">

<img width="810" alt="Screenshot 2019-06-23 at 11 07 20" src="https://user-images.githubusercontent.com/916064/59974689-1ff90000-95a7-11e9-9eda-9d3957d1fd93.png">

This isn't really a productive way to take part in open-source, you're just wasting other people's time.

**Comment by zhmushan** [comment]
https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md#new-feature-proposals

**Comment by ry** [comment]
Off topic (discuss in the Gitter channel if you want)
