### ISSUE TITLE
Mongoose event not firing.

### ISSUE THREAD

**Issue by conor-fearon** [denoland/deno#25734]
### Deno Version 1.46.3

Hello all, I have been running some tests with Deno to prove viability of switching to it.

I want to use mongoose with mongo for ODM.

Most of the features seem to work well, except for opening event streams.

![Code_tzItBNlZvK](https://github.com/user-attachments/assets/b6ed53da-deae-42a2-80b1-27c93c35bdfc)

The image above shows the mongoose.on event, the console.log never fires. Looking into its type it is inheriting from Nodes EventEmitter class.

Are there any push to switch this to Deno's events?

**Comment by conor-fearon** [comment]
Hey thanks for the response. The snippet is the full file below. I hope it helps.

![image](https://github.com/user-attachments/assets/c67e5955-2965-4ee1-8383-940d77c55d1c)

**Comment by marvinhagemeister** [comment]
Thanks, that helps. I've put your screenshot into chatgpt so that we have it in text form here. That way any developer working on this issue can more easily copy & paste the code in their editor to run it.

```ts
import mongoose from 'npm:mongoose@8.6.3';

export const connectDB = async () => {
    try {
        // console.log('Hey');
        await mongoose.connect('mongodb://127.0.0.1:27017/type-test');

        mongoose.connection.on('connected', () => {
            console.log('Connected to db...');
        });
    } catch (error) {
        console.log(error);
    }
};
```

**Comment by nathanwhit** [comment]
Hello! I can reproduce this in both deno _and_ node actually. I believe that @marvinhagemeister is correct here

> Could it be that the connection already happened and the event was already fired when you start listening for it? Like you call mongoose.connect() before and await the call before you set up the event listener with mongoose.connection.on(). I'd try switching those two and set up the listener first.

Try

```ts
import mongoose from 'npm:mongoose@8.6.3';

export const connectDB = async () => {
    try {
        // make sure we set up event listener before we try to connect
        mongoose.connection.on('connected', () => {
            console.log('Connected to db...');
        });
        await mongoose.connect('mongodb://127.0.0.1:27017/type-test');
    } catch (error) {
        console.log(error);
    }
};

await connectDB()
```

**Comment by marvinhagemeister** [comment]
Closing as it's not an issue in Deno, but a usage error of the `mongoose` library.
