### ISSUE TITLE
Deno.watchFS not working for directories on MacOS

### ISSUE THREAD

**Issue by happyhunter7** [denoland/deno#25737]
Version: Deno 1.46.3
MacOs: Sonoma 14.6.1 , (Mac Pro M1 Max chip)

The bug: 

When using 
```
Deno.watchFS(absoluteDirPatj, { recursive: true })
```
It doesn't trigger the listeners, or better said the iterable doesn't produce a change
But at the same time it works on file, so is related only to directories
And Yes I'm using the recursive mode
and yes the path exists 100% , and is a absolute path which I can console log and click on that and brings me to the correct place

Expectation:
When something changes in that dir the itterable produces a change and the code inside get's called

Temporar Fix/ Or maybe permanent:
I replaced Deno.watchFS() with Node watch from the 'node:fs' and it works
the node one doesn't accept an array of paths, but at least it works in comparation to the Deno watcher

**Comment by marvinhagemeister** [comment]
I'm unable to reproduce that. It works as expected for me. It watches the folder and notifies of every event that occurred inside the folder like adding files, moving them etc.

**Comment by marvinhagemeister** [comment]
I'm also on macOS. What I've tried:

1. Add a file `watcher.ts` with these contents:
  ```ts
  import * as path from "jsr:@std/path";
  
  const dir = path.join(Deno.cwd(), "files");
  try {
    await Deno.mkdir(dir);
  } catch {}

  const watcher = Deno.watchFs(dir, { recursive: true });
  for await (const event of watcher) {
    console.log(event);
  }
  ```
2. Run `deno run -A watcher.ts`
3. Edit some files in the `./files` directory.

<img width="464" alt="Screenshot 2024-09-19 at 19 26 46" src="https://github.com/user-attachments/assets/cbae1bd8-c47a-4424-af3e-cf13ab4cc2d4">

**Comment by happyhunter7** [comment]
Hmm so your example worked on my machine
even tho is strange that the dir was created before you instantiated the watcher and watcher still logged the create event) even tho at the moment of instantiating the watcher the dir was already created))

But nevermind, I then tried manually to rename the folder and it worked it triggered a rename event

I have no idea why my implimentation then works with node watch but not deno watch ) that's super strange like exactly same code

I'll try to investigate

**Comment by happyhunter7** [comment]
Ohhh, I understood why it didn't work so aparently `for await` blocks the code
And I had 3 `for await` and only the first one worked) haahha
Thanks I'm going to close

And that's why the node one worked since it doesn't block the code but the deno one yes, since it uses itterables

**Comment by happyhunter7** [comment]
closing) Thanks
