### ISSUE TITLE
Missing `FormData entries() method` in `FormData` interface

### ISSUE THREAD

**Issue by timreichen** [denoland/deno#25741]
Version: Deno 1.46.3

The [FormData entries() method](https://developer.mozilla.org/en-US/docs/Web/API/FormData/entries) is missing in the `FormData` interface.
One gets a type error but it runs as expected.

```ts
const formData = new FormData();
formData.set("foo", "bar");
formData.entries(); // type error: Property 'entries' does not exist on type 'FormData'.

Object.fromEntries(formData.entries()); // { foo: "bar" }
```

**Comment by marvinhagemeister** [comment]
I'm not able to reproduce this with Deno 1.46.3. I get no type error in neither the LSP or with `deno check`. I cannot reproduce it in canary either.

**Comment by lucacasonato** [comment]
You are probably disabling `deno.window` lib and instead loading `dom`, but without loading `dom.iterable` (which is the one that contains `FormData.prototype.entries`).

**Comment by timreichen** [comment]
Oh, you are right! Looks like that is a bug not in deno but in fresh where `dom.iterable` is missing in `compilerOptions.lib`. Closing.
