### ISSUE TITLE
Using an import_map.json and a module with a JSR subpath results in an error

### ISSUE THREAD

**Issue by sant123** [denoland/deno#25773]
Version: Deno v2.0.0-rc.4

import_map.json

```json
{
  "imports": {
    "@std/fmt": "jsr:@std/fmt@^1.0.2",
    "@std/random": "jsr:@std/random@^0.1.0"
  }
}
```

mod.ts

```ts
import { bgBlue } from "@std/fmt/colors";
import { randomIntegerBetween } from "@std/random";
import { randomSeeded } from "@std/random";

const prng = randomSeeded(1n);

console.log(bgBlue(randomIntegerBetween(1, 10, { prng }).toString()));
```

Running this code errors with the following message:

`deno --no-config --import-map import_map.json mod.ts`

![image](https://github.com/user-attachments/assets/3c5577f0-f72a-4fe9-a4e8-cc7c60d1487f)

However if I remove the import module with the subpath in this case `@std/fmt/colors`:

```ts
import { randomIntegerBetween } from "@std/random";
import { randomSeeded } from "@std/random";

const prng = randomSeeded(1n);

console.log(randomIntegerBetween(1, 10, { prng }).toString());
```

It works:

![image](https://github.com/user-attachments/assets/50fca8a8-8bf8-457a-82db-8f290f4419d3)

Thanks 🙏🏼

**Comment by dsherret** [comment]
Use the following to make it work in an import map:

```
{
  "imports": {
    "@std/fmt": "jsr:/@std/fmt@^1.0.2",
    "@std/fmt/": "jsr:/@std/fmt@^1.0.2/",
    "@std/random": "jsr:/@std/random@^0.1.0"
  }
}
```

Or ideally just use a deno.json.

**Comment by sant123** [comment]
> Use the following to make it work in an import map:
> 
> ```
> {
>   "imports": {
>     "@std/fmt": "jsr:/@std/fmt@^1.0.2",
>     "@std/fmt/": "jsr:/@std/fmt@^1.0.2/",
>     "@std/random": "jsr:/@std/random@^0.1.0"
>   }
> }
> ```
> 
> Or ideally just use a deno.json.

Thanks @dsherret 🙏🏼
