### ISSUE TITLE
lsp suggests incorrect imports

### ISSUE THREAD

**Issue by sigmaSd** [denoland/deno#25775]
deno 2.0.0-rc.2+49a0b7a (canary, release, x86_64-unknown-linux-gnu)

```ts
// add an import from node, so lsp starts suggesting node functions
import {} from "node:buffer";

assert();
```

![image](https://github.com/user-attachments/assets/ba3f5d5d-2e77-4741-9e99-c150d1b96ceb)

the third and first options are incorrect because they don't have the node prefix

**Comment by nayeemrmn** [comment]
I can't reproduce this, can you give complete configuration details?

**Comment by sigmaSd** [comment]
I tried 2 different editors helix and zed and both show the same behavior

linux fedora 40, deno 2.0.0-rc.2+49a0b7a (canary, release, x86_64-unknown-linux-gnu)

copy this snippet 
```ts
// add an import from node, so lsp starts suggesting node functions
import {} from "node:buffer";

assert();
```
i have no deno.json or special lsp config

then on assert list code action

**Comment by nayeemrmn** [comment]
Okay I got it, I was checking autocomplete suggestions instead of quick fixes. Will investigate.
