### ISSUE TITLE
deno.json(workspace): allow wildcard ["packages/*"]

### ISSUE THREAD

**Issue by birkskyum** [denoland/deno#25783]
deno 2.0.0-rc.4+a92ebd9

It's pretty common to just add pnpm/npm workspace "packages/*", instead of each individual pacakge.

example [here](https://github.com/solidjs/solid/blob/main/pnpm-workspace.yaml)

deno will not understand the wildcard and err with:

```
➜ deno i 
error: Could not find config file for workspace member in 'file:///path/to/repo/packages/*/'.
```

Is it deliberate that wildcard isn't supported?

**Comment by birkskyum** [comment]
A good test for this functionality would this repo moving the repo below from pnpm workspace to npm workspace, building all the packages and running an example:
https://github.com/histoire-dev/histoire

**Comment by bartlomieju** [comment]
This requires a change in `deno_config`, it's already supported for `npm` workspaces there and similar handling should be done for Deno workspaces.

**Comment by bartlomieju** [comment]
#26568 will take care of wildcard workspace members but is not enough to fully support scenarios like the linked `histoire` repo. To support it we will need https://github.com/denoland/deno/issues/26726 and ability to run local npm packages as well.
