### ISSUE TITLE
`deno install` sometimes calls `sync_resolution_with_fs` multiple times

### ISSUE THREAD

**Issue by nathanwhit** [denoland/deno#25782]
It gets called from both graph resolution (`WorkerCliNpmGraphResolver::resolve_pkg_reqs`) and higher level functions (`ManagedCliNpmResolver::ensure_top_level_package_json_install`). This can result in the node_modules setup code running multiple times, which is wasteful.

**Comment by bartlomieju** [comment]
Ref to https://github.com/denoland/deno/issues/25771 where we spotted this happening by trying a naive implementation
