### ISSUE TITLE
Consider deprecating deno.jsonc auto-discovery (and just have deno.json) for a performance reasons

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#25793]
Probing for deno.jsonc is quite wasteful and comments are already supported in deno.json. Startup performace could be improved a lot on slow file systems by not bothering to probe for this file.

**Comment by petamoriken** [comment]
I would rather deprecate `.json` as I feel uncomfortable using comments with the `.json` extension.

**Comment by HasanAlrimawi** [comment]
I'm interested in deprecating deno.jsonc.
I suspect that I'll be ought to remove probing it, and as a result I'll have to update all tests and any findings of deno.jsonc to deno.json.
If the scope is wider please let me know...

**Comment by HasanAlrimawi** [comment]
I'm interested in deprecating deno.jsonc.
I suspect that I'll be ought to remove probing, and as a result I'll have to update all tests and any findings of deno.jsonc to deno.json.
If the scope is wider or there are any other considerations please let me know...

**Comment by rlidwka** [comment]
> Probing for deno.jsonc is quite wasteful and comments are already supported in deno.json.

Are comments supported in every other json file (including package.json and user imports) as well? If not, having files with the same extension but different semantics seems problematic.

On the other hand, `jsonc` extension is misleading as well, e.g. `deno.json` supports trailing commas, which not all jsonc implementations do.

I guess `deno.json` is better, and we'll have to live with the fact that "json for configuration" and "json for data" are two different formats (especially with bun now supporting comments in package.json since April).

**Comment by petamoriken** [comment]
JSON is the file format defined by [RFC 8259](https://www.rfc-editor.org/rfc/rfc8259.html) and [ECMA 404](https://ecma-international.org/publications-and-standards/standards/ecma-404/), and I strongly oppose the use of the `.json` extension for any other format, even if it's [Microsoft's JSONC](https://github.com/microsoft/node-jsonc-parser) format.

**Comment by dsherret** [comment]
It's already the case that deno.json supports JSONC fwiw (similar to tsconfig.json). It's been that way since the start.

**Comment by petamoriken** [comment]
> It's already the case that deno.json supports JSONC fwiw (similar to tsconfig.json). It's been that way since the start so there would be no change there. The change would be unifying to only deno.json for auto-discovery.

Then we should deprecate `deno.json` and move to the `deno.jsonc` instead of making any more non-standard decisions.

**Comment by dsherret** [comment]
The deno.json is a local file that isn't distributed (unlike a package.json, which is why comments there are bad). Additionally, a developer can choose to have comments in it or not, so the Deno runtime accepting comments in a file with a json extension is perfectly fine IMO ([also see](https://web.archive.org/web/20081022191657/http://tech.groups.yahoo.com/group/json/message/152)). There's lot of precedence for this and many tools do it for local configuration files.

**Comment by dsherret** [comment]
I'm going to close this suggestion because based on usages on GitHub this would be too disruptive
