### ISSUE TITLE
Permission flags do not work or error when placed before subcommand

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#25808]
![image](https://github.com/user-attachments/assets/b0e03b46-db0d-4780-a626-aa4449551b8b)

**Comment by yazan-abdalrahman** [comment]
@lucacasonato  @crowlKats  Can I work on this? What is the expected return error? Should it parse permission?

**Comment by crowlKats** [comment]
@yazan-abdalrahman I am working on this as we are speaking, will have a PR open in a couple of mintues

**Comment by yazan-abdalrahman** [comment]
> @yazan-abdalrahman I am working on this as we are speaking, will have a PR open in a couple of minutes

@crowlKats Ok, I could help with it, if needed.
