### ISSUE TITLE
Add more formats to markup_fmt

### ISSUE THREAD

**Issue by oscarotero** [denoland/deno#25802]
Deno's formatter allows to format HTML-like pages with `deno fmt --unstable-html`. But it only accepts HTML, Svelte and Astro files.
https://github.com/denoland/deno/blob/0cb00a6e89d83d4e16e6616f7af8819bd894b0da/cli/tools/fmt.rs#L294-L307 

The [markup_fmt plugin](https://github.com/g-plane/markup_fmt) that you're using can format more file extensions like Angular, Jinja, Twig, Nunjucks and Vento. Is there any reason to don't include these formats? If they are not included by default, at least I'd love to have an option to include them. For example: `deno fmt --unstable-html=vto,njk`

**Comment by lucacasonato** [comment]
@oscarotero We're happy to add those extensions with no config needed. Feel free to open a PR :)
