### ISSUE TITLE
`deno install` can't find package `npm:storybook-solidjs-vite`, unless version is specified

### ISSUE THREAD

**Issue by birkskyum** [denoland/deno#25813]
deno 2.0.0-rc.4+0cb00a6

https://www.npmjs.com/package/storybook-solidjs-vite

If a version isn't provided, it doesn't install `latest` like i'd expect it to, but says the module was not found.

```sh
➜ deno i npm:storybook-solidjs-vite
error: npm:storybook-solidjs-vite was not found.

➜ deno i npm:storybook-solidjs-vite@1.0.0-beta.2
Add npm:storybook-solidjs-vite@1.0.0-beta.2

➜ deno i npm:storybook-solidjs-vite@latest      
Add npm:storybook-solidjs-vite@1.0.0-beta.2
```

<img width="799" alt="Screenshot 2024-09-23 at 01 26 00" src="https://github.com/user-attachments/assets/5dfe513e-de6c-4b0a-9679-bc15cd305e8b">

**Comment by marvinhagemeister** [comment]
Spent a bit debugging this:

The registry data looks like this:

```jsonc
{
  "name": "storybook-solidjs-vite",
  "dist-tags": {
    "latest": "1.0.0-beta.2"
  },
  "versions": {
    "1.0.0-beta.1": {
      // ...
    },
    "1.0.0-beta.2": {
      // ...
    }
  },
  "time": {
    "created": "2023-02-07T00:42:30.776Z",
    "1.0.0-beta.1": "2023-02-07T00:42:31.050Z",
    "modified": "2023-03-25T00:35:53.536Z",
    "1.0.0-beta.2": "2023-03-25T00:35:53.380Z"
  },
  // ...
}
```
We parse the package requirement as `npm:storybook-solidjs-vite@*` and then fail the semver comparison check here https://github.com/denoland/deno/blob/37cedefb4dc4f582311d7478d414d59469e4af5e/cli/npm/mod.rs#L136

According to the npm docs the `npm install` command will always default to the `latest` tag if no version or tag requirement is specified, see https://docs.npmjs.com/cli/v10/commands/npm-install#description .  There apparently is an option to configure that in npm, but I've heard of anyone changing that, so we can probably ignore that.

But npm also allows you to do `npm install foo@*` which is different from `npm install foo` (= `npm install foo@latest`). 

I think this issue uncovers two different bugs in our npm installation logic:

1. Our semver version comparison seems to ignore pre-release version when matching with `*`
2. We don't default to adding `@latest` when no version or tag is specified for npm packages.
