### ISSUE TITLE
`jsx: precompile` converts props to lowercase

### ISSUE THREAD

**Issue by r-thomson** [denoland/deno#25810]
Version: Deno 1.45.5

When using JSX with the `precompile` mode, props are converted to lowercase. This is particularly problematic if you’re working with SVGs, which has case-sensitive attributes.

To test this, I set `jsxImportSource` to a file that replaces all the JSX functions with `console.log`. Given the following JSX:

```jsx
<div someProp="value" />;
```

With `"jsx": "react-jsx"`:

```js
div { someProp: "value" }
```

With `"jsx": “precompile"`

```js
[ '<div someprop="value"></div>' ]
```

**Comment by r-thomson** [comment]
From checking into the code, it looks like this function is responsible for lowercasing the attribute names, so this behavior seems to be intentional.

https://github.com/denoland/deno_ast/blob/e7027f4f7935016b706671ab1ee239c40a55c75e/src/transpiling/jsx_precompile.rs#L89

_However_, this behavior still absolutely breaks some case-sensitive attributes, like [`viewBox`](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/viewBox), so I think it would make sense to rethink this.

**Comment by marvinhagemeister** [comment]
Reopening until the updated crate is merged here.
