### ISSUE TITLE
support automatic migrations from lockfile v4 to v3

### ISSUE THREAD

**Issue by KnorpelSenf** [denoland/deno#25820]
When trying out a Deno 2.0 release candidate, the CLI automatically upgrades the lockfile to `"v4"`.

However, when you realise that you want to go back to Deno 1.x again, it cannot migrate back. You have to delete the lockfile and recreate it, which potentially updates all the deps.

It would be cool to have another 1.46.x patch release that adds forward compatibility. It could either directly support lockfile v4, or at least understand the v4 format and use it to restore the lockfile as it was present in v3.

**Comment by dsherret** [comment]
I'm not sure this is worth the effort. Once Deno 2.0 is released then people will migrate to it in a project and keep using it. If they need to downgrade for some reason then they can delete the lockfile.

**Comment by KnorpelSenf** [comment]
Fair enough, glad I asked
