### ISSUE TITLE
Workspace resolution doesn't work when `--config` option is explicitly specified

### ISSUE THREAD

**Issue by kt3k** [denoland/deno#25847]
### The steps to reproduce

Create the following directory setup:

```
├── deno.json
├── foo
│   ├── deno.json
│   └── main.ts
└── main.ts
```

`/deno.json`
```json
{
  "workspace": ["./foo"]
}
```

`/foo/deno.json`
```json
{
  "name": "@my-scope/my-package"
  "version": "0.1.0",
  "exports": "./main.ts"
}
```

`/foo/main.ts`
```ts
export function foo(): void {}
```

`/main.ts`
```ts
import { foo } from "@my-scope/my-package"
foo();
```

When executing the command `deno check main.ts`, it passes. However if I specify `deno.json` via `--config` option, the workspace settings are not recognized and it fails.

```shellsession
$ deno check main.ts # <= passes without an issue
$ deno check --config deno.json main.ts # <= fails
error: Relative import path "@my-scope/my-package" not prefixed with / or ./ or ../
  hint: If you want to use a JSR or npm package, try running `deno add jsr:@my-scope/my-package` or `deno add npm:@my-scope/my-package`
    at file:///Users/kt3k/tmp/deno-check-repro/main.ts:1:21
```

---

More context: In `denoland/std` repo, we want to specify a config file with the identical workspace settings with different typings (for checking browser compatibility in typing). This behavior prevents us doing that check.

**Comment by dsherret** [comment]
This issue is buried in this one (https://github.com/denoland/deno/issues/25309), but let's leave this issue open because it's more clear.

**Comment by dsherret** [comment]
Actually, I think maybe this isn't a bug? You'll need to specify the root workspace config rather than the sub config. Specifying `--config` can be a way to avoid the performance hit of traversing the directories for a workspace and if we were to fix this then we'd have to probe ancestor directories for the config.

**Comment by kt3k** [comment]
I suppose the workspace config is specified in `--config deno.json` (I suppose the discovered config and the specified config are the same in the above example), or am I missing something?

**Comment by dsherret** [comment]
Oh sorry. I got confused about what directory it was in because in https://github.com/denoland/deno/issues/25309 it was in the sub directory.
