### ISSUE TITLE
deno check configuration conflict

### ISSUE THREAD

**Issue by kuchta** [denoland/deno#25850]
Version: Deno 2.0.0-rc.4

`deno check` on node project doesn't implicitly load tsconfig.json and specifying `--config tsconfig.json` breaks import resolution with error `Relative import path "xyz" not prefixed with / or ./ or ../`

**Comment by dsherret** [comment]
You need to specify the compiler options for deno in the deno.json file. Deno supports a subset of tsconfig.json.

**Comment by kuchta** [comment]
Hi @dsherret . Sure, that's a solution, but I thought Deno v2 tries to be more compatible with Node than that. Is there a way how to tell Deno to use tsconfig.json without switching resolution algorithm?

**Comment by dsherret** [comment]
Node doesn't read tsconfig.json files. It would be introducing yet another configuration file to probe for and understand which would increase startup time and complicate Deno more.

> Is there a way how to tell Deno to use tsconfig.json without implicitly switching resolution algorithm?

I recommend copying the tsconfig compiler options that are relevant for Deno to the deno.json config file.

**Comment by kuchta** [comment]
Node doesn't read it, but Node projects have TS config there and copying it to deno.json would tell Deno it's a Deno projects, when in fact it's Node project with dependencies in package.json. Isn't that an antipattern to have both deno.json and package.json?

**Comment by dsherret** [comment]
> Isn't that an antipattern to have both deno.json and package.json?

No, it's not an antipattern.

**Comment by kuchta** [comment]
@dsherret Ok, thank you, David ❤️
