### ISSUE TITLE
Feature Request: Testable Examples in Deno, similar to Golang

### ISSUE THREAD

**Issue by niklasmtj** [denoland/deno#25889]
# Supporting testable examples in Deno
In Golang we have the possibility to write examples that are also tested when `go test` is run. This is something I learnt this week and I got the idea of suggesting enhancing the `deno test` command to also support this kind of behavior.

## How it looks in Go
```go
package reverse_test

import (
    "fmt"

    "golang.org/x/example/hello/reverse"
)

func ExampleString() {
    fmt.Println(reverse.String("hello"))
    // Output: olleh
}
```

What we can see here is that the function is prefixed with `Example*`, plus it has to be in a file suffixed with `_test.go`. Let's say `example_test.go`. Otherwise the test runner won't pick this up. The test result that will be checked while running is the one that follows the `// Output:` comment. Without adding the comment the test will also not be picked up.

The whole explanation can be found on the [Go blog](https://go.dev/blog/examples).

### Checking for `Example*` functions in `_test` files.
```ts
import { format } from "@std/fmt/bytes";

const ExampleFormat = () => {
  console.log(format(1337));
  // Output: "1.34 kB"
}
```

Here we would use a similar style to what Golang provides. We could look for `Example*` functions in the `_test.ts` files, run them and check what the `console.log` would write to `stdout` and check it against the `// Output:` comment given.

### Running code in JSDoc examples
```ts
/**
 * This function formats a number of bytes into a human-readable string.
 * @example
 * import { format } from "@std/fmt/bytes";
 *
 * console.log(format(1337))
 * // Output: "1.34 kB"
 */
const format = (
  num: number,
  options?: any,
): string => {...};
```

This uses the already included support of JSDoc and would run the code that is inside of the given examples in the doc string.

## Why?
Since we already have lots of example in the `std` library, that are picked up through JSDoc, those would make testing in my opinion even easier. We could provide simple tests as examples as well. 

What do you think? 

I'm pretty new to Rust but if this would be of interest to implement I would love to get my feed wet in Rust implementing this feature.

**Comment by bartlomieju** [comment]
Deno already supports running tests from JSDoc comments: https://docs.deno.com/runtime/fundamentals/testing/#documentation-tests

Make sure to upgrade to latest release candidate to try it out: `deno upgrade rc`

**Comment by niklasmtj** [comment]
Ai, we can then close this again. Sorry for missing that. Thanks a lot for the quick respose @bartlomieju!

**Comment by niklasmtj** [comment]
> Deno already supports running tests from JSDoc comments: https://docs.deno.com/runtime/fundamentals/testing/#documentation-tests
> 
> Make sure to upgrade to latest release candidate to try it out: `deno upgrade rc`

It works just flawlessly. Thanks for implementing it! Would you mind telling me where I can find the corresponding Rust files where this is handled? Would love to get to know how it is handled.

**Comment by bartlomieju** [comment]
You can check the PR that added it: https://github.com/denoland/deno/pull/25220

**Comment by niklasmtj** [comment]
> You can check the PR that added it: #25220

Thanks a lot, I'll take a look!
