### ISSUE TITLE
Support Wrangler, the CLI for Cloudflare Workers 

### ISSUE THREAD

**Issue by kensukesaito** [denoland/deno#25899]
Cloudflare Workers SDK
https://github.com/cloudflare/workers-sdk

```
$ deno run npm:wrangler

error: unexpected argument '--no-warnings' found

  tip: a similar argument exists: '--no-config'
  tip: to pass '--no-warnings' as a value, use '-- --no-warnings'

Usage: deno run --no-config [SCRIPT_ARG]...
```

```
$ deno --version

deno 2.0.0 (stable, release, aarch64-apple-darwin)
v8 12.9.202.13-rusty
typescript 5.6.2
```

They are not interested in supporting Deno.

Feature request: Support Deno
https://github.com/cloudflare/workers-sdk/issues/6049

**Comment by RickDT** [comment]
Same on Deno 2.

**Comment by bartlomieju** [comment]
Seems related to how subprocesses are spawned. @littledivy is it something you could look at?

**Comment by EdamAme-x** [comment]
same issue on deno v2.0.0

**Comment by bartlomieju** [comment]
This should be fixed by https://github.com/denoland/deno/pull/26288

**Comment by kensukesaito** [comment]
@bartlomieju @nathanwhit 
Thank you for your prompt response!

**Comment by bartlomieju** [comment]
FYI this fix will be available in Deno 2.0.1 that will come out in a few hours.

**Comment by kensukesaito** [comment]
@bartlomieju 
Great, Thanks!

**Comment by EdamAme-x** [comment]
Thanks for great works!
