### ISSUE TITLE
deno install --allow-scripts : Error launching 'deno': Argument list too long (os error 7)

### ISSUE THREAD

**Issue by birkskyum** [denoland/deno#25891]
deno 2.0.0-rc.6

- `deno run -A npm:create-analog@latest` (full stack, tailwind)
- `cd analog-project`
- `deno i`

will print:

```
┠─ This may cause the packages to not work correctly.
┖─ To run lifecycle scripts, use the `--allow-scripts` flag with `deno install`:
   deno install --allow-scripts=npm:esbuild@0.23.0,npm:esbuild@0.21.5,npm:lmdb@3.0.13,npm:nice-napi@1.0.2,npm:nx@19.8.0,npm:esbuild@0.20.2,npm:msgpackr-extract@3.0.3
```

try to run recommendation:

```
⇣6% ➜ deno install --allow-scripts=npm:esbuild@0.23.0,npm:esbuild@0.21.5,npm:lmdb@3.0.13,npm:nice-napi@1.0.2,npm:nx@19.8.0,npm:esbuild@0.20.2,npm:msgpackr-extract@3.0.3   

Error launching 'deno': Argument list too long (os error 7)
error: script 'postinstall' in 'esbuild@0.21.5' failed with exit code 1
Error launching 'deno': Argument list too long (os error 7)
error: script 'postinstall' in 'esbuild@0.23.0' failed with exit code 1
Error launching 'deno': Argument list too long (os error 7)
error: script 'postinstall' in 'nx@19.8.0' failed with exit code 1
Error launching 'deno': Argument list too long (os error 7)
error: script 'postinstall' in 'esbuild@0.20.2' failed with exit code 1
Error launching 'deno': Argument list too long (os error 7)
error: script 'install' in 'nice-napi@1.0.2' failed with exit code 1
Error launching 'deno': Argument list too long (os error 7)
error: script 'install' in 'lmdb@3.0.13' failed with exit code 1
Error launching 'deno': Argument list too long (os error 7)
error: script 'install' in 'msgpackr-extract@3.0.3' failed with exit code 1
error: failed to run scripts for packages: esbuild@0.21.5, esbuild@0.23.0, nx@19.8.0, esbuild@0.20.2, nice-napi@1.0.2, lmdb@3.0.13, msgpackr-extract@3.0.3
```

**Comment by zmila** [comment]
steps from the tutorial: tutorials/how_to_with_npm/next/

$ deno --version

> deno 1.46.3 (stable, release, x86_64-unknown-linux-gnu)
> v8 12.9.202.5-rusty
> typescript 5.5.2

$ deno run -A npm:create-next-app@latest 
enter myapp1
// select all defaluts

$ cd ./my-app1
$ deno task dev
// check localhost:3000 - ok

Ctrl+C in terminal, stopping the application. 
and run it again: 
$ deno task dev
error: 

> Task dev next dev
> error: Uncaught Error: Failed to spawn '/home/.../.deno/bin/deno': Argument list too long (os error 7)
>     at spawnChildInner (ext:runtime/40_process.js:186:17)
>     at spawnChild (ext:runtime/40_process.js:208:10)
>     at Command.spawn (ext:runtime/40_process.js:480:12)
>     at new ChildProcess (ext:deno_node/internal/child_process.ts:183:10)
>     at spawn (node:child_process:119:10)
>     at fork (node:child_process:110:10)
>     at file:///home/.../prg/deno/myapp1/node_modules/.deno/next@14.2.14/node_modules/next/dist/cli/next-dev.js:212:45
>     at new Promise (<anonymous>)
>     at startServer (file:///home/.../prg/deno/myapp1/node_modules/.deno/next@14.2.14/node_modules/next/dist/cli/next-dev.js:198:16)
>     at runDevServer (file:///home/.../prg/deno/myapp1/node_modules/.deno/next@14.2.14/node_modules/next/dist/cli/next-dev.js:279:23)

**Comment by marvinhagemeister** [comment]
@zmila Can you open a new issue for that? Despite getting a similar error message, you don't seem to be running the `deno install` command.

**Comment by zmila** [comment]
sorry, i already switched to other framework. 
you may update documentation or tutorial, indicating this command "deno install" for your future users
