### ISSUE TITLE
`deno run npm:package`  - Issue passing args to the npm package

### ISSUE THREAD

**Issue by birkskyum** [denoland/deno#25904]
deno 2.0.0-rc.6

I'd like to be able to pass the `--rc` / `--stable` flag and get what I expect, as demonstrated here with npm and pnpm:

### Release Candidate
- `npx create-tauri-app@latest --rc`
- `npm create tauri-app@latest -- --rc`
- `pnpx create-tauri-app@latest --rc`
- `pnpm create tauri-app@latest --rc`

Prints:
```
? Project name (tauri-app) ›
```

### Stable
- `npx create-tauri-app@latest --stable`
- `npm create tauri-app@latest -- --stable`
- `pnpx create-tauri-app@latest --stable`
- `pnpm create tauri-app@latest --stable`

Prints:
```
✔ Identifier · com.--stable.app
? Choose which language to use for your frontend ›
```

### Deno ignores the `--rc` flag:

- `deno run -A npm:create-tauri-app@latest --rc`
- `deno run -A npm:create-tauri-app@latest -- --rc`

Prints the `stable` output:
```
? Choose which language to use for your frontend ›
```
or 
```
create-tauri-app directory is not empty, do you want to overwrite?`
```

**Comment by marvinhagemeister** [comment]
This seems like a bug in the `create-tauri-app` npm package. Upon initialization they check for the package manager they were invoked with here https://github.com/tauri-apps/create-tauri-app/blob/bc3fd14f88646144bb56b5e374311b8f78defcfb/node/create-tauri-app.js#L21

```ts
const [bin, script, ...args] = process.argv;
const binStem = path.parse(bin).name.toLowerCase();

if (binStem.match(/(nodejs|node|bun)-*([0-9]*)*$/g)) {
  // ...
} else {
  // We don't know what started it, assume it's already stripped.
  args.unshift(bin); // <-- This line triggers the bug. This seems wrong
}
```

Essentially, when the runtime isn't Node or Bun, they mess with the arguments leading to an unexpected result. When I uncomment the `unshift()` line, everything works as expected.

**Comment by birkskyum** [comment]
Resolved upstream - haven't tried it, and now both deno / tauri are at 2.0 so the repro is obsolete anyway.
