### ISSUE TITLE
Panic with `deno info` in BYONM

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#25903]
```json
{
  "nodeModulesDir": "manual",
  "imports": {
    "chalk": "npm:chalk@^5.3.0"
  }
}
```

```
$ deno install
$ deno info npm:chalk --json
============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 2.0.0-rc.6+88a4f8d
Args: ["deno", "info", "npm:chalk", "--json"]

thread 'main' panicked at cli/resolver.rs:792:47:
internal error: entered unreachable code
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by yazan-abdalrahman** [comment]
@lucacasonato @bartlomieju 
It should work or return an error instead of being unreachable?

**Comment by yazan-abdalrahman** [comment]
@lucacasonato  

It should either provide an error stating "BYONM resolver is not supported in this context" or support it.

**Comment by dsherret** [comment]
@yazan-abdalrahman sorry, I should have assigned this one to me, but I'm going to do this one because it requires a bit of investigation and is in the hot path for 2.0.

**Comment by yazan-abdalrahman** [comment]
> @yazan-abdalrahman sorry, I should have assigned this one to me, but I'm going to do this one because it requires a bit of investigation and is in the hot path for 2.0.

I found something that I'm not sure if it's correct. I altered the condition to make `info` go through `CliNpmResolverCreateOptions::Managed` rather than  `CliNpmResolverCreateOptions::Byonm`, and it returned this result.



https://github.com/user-attachments/assets/ecb97621-4f66-4290-8973-a6748b6114fd

@dsherret

**Comment by dsherret** [comment]
It's not. We don't want to use the managed resolver when using byonm ("manual") resolution.
