### ISSUE TITLE
Quokka doesn't work I guess

### ISSUE THREAD

**Issue by yegwheel** [denoland/deno#25912]
Discovered that quokka won't work right off the bat. Tried adding some of my own tests but then ran into issues with imports import_maps and testing. With regret, going back to node.

**Comment by HeyITGuyFixIt** [comment]
See this issue here: https://github.com/wallabyjs/quokka/issues/456#issuecomment-754266262

**Comment by littledivy** [comment]
Duplicate of https://github.com/denoland/deno/issues/6694
