### ISSUE TITLE
Deno 2 - Different behavior between `deno install npm:` and `deno install jsr:` ?

### ISSUE THREAD

**Issue by nshiab** [denoland/deno#25910]
My version
- deno 2.0.0-rc.6+88a4f8d (canary, release, aarch64-apple-darwin)
- v8 12.9.202.13-rusty
- typescript 5.6.2

Hi!

If I install the simple-data-analysis library (which depends on DuckDB) from NPM with this command `deno install --node-modules-dir=auto --allow-scripts=npm:duckdb npm:simple-data-analysis`, I see the library installed in `node_modules`.

I can then code something and run the script with `deno run --node-modules-dir=auto -A main.ts`. It works great.

<img width="1465" alt="Screenshot 2024-09-27 at 10 56 18 AM" src="https://github.com/user-attachments/assets/450eef0e-6d0f-4480-bb60-076a0ea682b1">

I would like to try using Deno with JSR. So I published the library on [JSR](https://jsr.io/@nshiab/simple-data-analysis). I am the maintainer.

But when I run `deno install --node-modules-dir=auto --allow-scripts=npm:duckdb jsr:@nshiab/simple-data-analysis`, it doesn't install `simple-data-analysis` in the `node_modules`. VS Code is not able to find the library and the types.

And if I try to run the same code as before, I get an error.

<img width="1465" alt="Screenshot 2024-09-27 at 11 01 51 AM" src="https://github.com/user-attachments/assets/7335193c-d274-4ffe-8470-14a11da48451">

Based on the error message, I checked my `deno.json`.

```js
{
  "imports": {
    "@nshiab/simple-data-analysis": "jsr:@nshiab/simple-data-analysis@^3.9.3"
  }
}
```
I tried switching `import { SimpleDB } from "simple-data-analysis";` to `import { SimpleDB } from "@nshiab/simple-data-analysis";` but the result is the same.

Am I supposed to do things differently when installing a library from JSR?

Thanks a lot for your help.

**Comment by marvinhagemeister** [comment]
JSR packages are never installed into `node_modules`. It looks like the Deno extension isn't active in your vscode instance, otherwise the overlay would end with `deno-ts(...)` instead of `ts(...)`. Make sure to install the Deno extension. If it's already installed, you can force enable it for a project by running the `Deno: Enable` command in vscode.

**Comment by nshiab** [comment]
Ahhhh! You are right. The extension was installed, but it wasn't enabled for some reason. Thank you very much, @marvinhagemeister !
