### ISSUE TITLE
deno_runtime is introduced, deno_io  error on windows 

### ISSUE THREAD

**Issue by Cassielxd** [denoland/deno#25922]
Version: Deno 1.46.3
deno_runtime is introduced, which indicates that deno_io lacks feature Win32_Security
![image](https://github.com/user-attachments/assets/ec83075a-5a42-454a-9f99-7900b7d95c1e)

![image](https://github.com/user-attachments/assets/6c27d37a-c842-45f9-9165-1c14ac31bc44)

**Comment by Cassielxd** [comment]
windows system

**Comment by littledivy** [comment]
IIUC Workspace dependency features are supposed to be inherited by members.

**Comment by Cassielxd** [comment]
deno_io is not redistributed, and deno_runtime is not redistributed，deno_runtime refers to the older version of deno_io, and your changes should refer to the main branch and are not released to it
https://crates.io/

**Comment by Cassielxd** [comment]
![image](https://github.com/user-attachments/assets/429e7f97-6f9b-4579-b16e-d95d7d179e66)
The latest version of deno_io still lacks Win32_Security
