### ISSUE TITLE
Support for `bun:` import scheme (e.g. `bun:test`) within `deno check`

### ISSUE THREAD

**Issue by hamlim** [denoland/deno#25935]
Not sure if this is technically a feature request or a bug report.

I'm experimenting with getting my existing monorepo template to work with deno instead of Bun (and various other tools). However - since I'm approaching this incrementally I still have some files using Bun as the test runner - and bun recommends importing things like `test`, `expect`, etc from `bun:test` which is a custom scheme.

Example file:

```ts
import {test, expect} from 'bun:test'

test('example', () => {
  expect(true).toBe(true);
});
```

I'd expect this file to be able to be checked via `deno check` as-is.

Currently, I get the following error:

```sh
Task check deno check ./src/
error: Unsupported scheme "bun" for module "bun:test". Supported schemes: [
    "data",
    "blob",
    "file",
    "http",
    "https",
]
```

Deno version info:

```sh
deno 2.0.0-rc.7 (release candidate, release, aarch64-apple-darwin)
v8 12.9.202.13-rusty
typescript 5.6.2
```

**Comment by dsherret** [comment]
You can use an import map to map `bun:test` to another file:

```json
{
  "imports": {
    "bun:test": "./bun-test.ts"
  }
}
```

Then provide an implementation or just some dummy exports:

```ts
// bun-test.ts
export const test: any = {};
export const expect: any = {};
```

**Comment by hamlim** [comment]
That doesn't help too much - since it replaces the values that Bun would usually provide when running `bun test`

**Comment by dsherret** [comment]
> That doesn't help too much - since it replaces the values that Bun would usually provide when running `bun test`.

I don't understand. Does `bun test` respect deno's import map?

**Comment by hamlim** [comment]
Ah I see, kind of unfortunate that the workaround is needed.

If others stumble across this, here's the code I added to make `deno check` pass:

Within `deno.json`:
```json
{
  "imports": {
    "bun:test": "./bun-test-stub.ts"
  }
}
```

Within `bun-test-stub.ts`:
```ts
// bun-test-stub.ts
import { expect as _expect, test as _test } from "bun";

export const test: typeof _test = _test;
export const expect: typeof _expect = _expect;
// may need other exports here to match all the values you're importing from bun:test!
```

**Comment by marvinhagemeister** [comment]
There is also the `bun-types` package on npm which is published by the bun folks and contains the most up to date typings. Might be worth using that instead of manually creating types.

**Comment by hamlim** [comment]
Ah I had thought that types for bun had moved to `@types/bun`, but it looks like that just redirects / re-exports `bun-types` - I'll use that instead!

**Comment by lucacasonato** [comment]
I'll close this then.
