### ISSUE TITLE
[Deno KV] Inconsistent Watcher Firing Order in Atomic Operations

### ISSUE THREAD

**Issue by ycmjason** [denoland/deno#25943]
Hello,

I have noticed a behaviour that makes atomic operations hard to reason about. 

I have written a short script that would demonstrate the pain point:

```ts
const kv = await Deno.openKv(":memory:");

const key1Reader = kv.watch([["key1"]]).getReader();
const key2Reader = kv.watch([["key2"]]).getReader();

(async () => {
  let i = 0;
  while (true) {
    i++;
    console.log(
      `Race #${i}: `,
      await Promise.race([
        (async () => {
          await key1Reader.read();
          return "key1 wins!";
        })(),
        (async () => {
          await key2Reader.read();
          return "key2 wins!";
        })(),
      ]),
    );
  }
})();

for (let i = 0; i < 100; i++) {
  await kv.atomic().set(["key1"], i).set(["key2"], i).commit();
}
```

## Expected Behaviour
I would expect key1 to win in all 100 times it is set. As the doc laid out

> "The ordering of mutations is guaranteed to be the same as the ordering of the mutations specified in the operation."
[Link to docs](https://docs.deno.com/api/deno/~/Deno.AtomicOperation#:~:text=The%20ordering%20of%20mutations%20is%20guaranteed%20to%20be%20the%20same%20as%20the%20ordering%20of%20the%20mutations%20specified%20in%20the%20operation.)

## Actual Behaviour

The `key1` and `key2` watchers fire in a non-deterministic order. Sometimes `key1` wins, and other times `key2` does, even though both keys are updated in the same atomic operation.

## Environments Tested

System:
  OS: macOS 14.4.1
  CPU: (10) arm64 Apple M1 Max

Deno versions: 
- deno 2.0.0-rc.7
- deno 1.46.3

-------------

FWIW, If we change the script to use non-atomic operation, the firing order will be consistently `key1`:

```ts
const kv = await Deno.openKv(":memory:");

const key1Reader = kv.watch([["key1"]]).getReader();
const key2Reader = kv.watch([["key2"]]).getReader();

(async () => {
  let i = 0;
  while (true) {
    i++;
    console.log(
      `Race #${i}: `,
      await Promise.race([
        (async () => {
          await key1Reader.read();
          return "key1 wins!";
        })(),
        (async () => {
          await key2Reader.read();
          return "key2 wins!";
        })(),
      ]),
    );
  }
})();

for (let i = 0; i < 100; i++) {
  await Promise.all([
    kv.set(["key1"], i),
    kv.set(["key2"], i),
  ]);
}
```

**Comment by lucacasonato** [comment]
This is intended behaviour. When you watch both keys in a single watcher, the order will always be as you expect. Across two different watchers order is not guaranteed at all.

The ordering you are referring to is not related to watch at all anyway - it is about the inserts in the database (ie if you have an AO with a `set` and then a `remove`, the `remove` is guaranteed to win).

**Comment by ycmjason** [comment]
Ah I see. Good to know that it is an intended behaviour. I will figure a way to work around this going forward then 👍
