### ISSUE TITLE
JSR package manifest for '@std/collections' failed to load. trailing characters at line 53 column 1

### ISSUE THREAD

**Issue by scarf005** [denoland/deno#25967]
## Steps to reproduce

```sh
deno cache --reload 'jsr:@std/collections'
error: JSR package manifest for '@std/collections' failed to load. trailing characters at line 53 column 1
```

- seems to be similar to #24577 but this time `--reload` cache doesn't work.
- happened after downgrading from canary to stable 1.46.3
- can't reproduce after purging `~/.cache/deno`
- repo this happenned in: https://github.com/cataclysmbnteam/Cataclysm-BN/tree/415f721646243c2cbc442194b20050d2f9437e7c (only `scripts/`, `deno.jsonc` and `import_map.json` is relevant)

## Version

```
deno 1.46.3 (stable, release, x86_64-unknown-linux-gnu)
v8 12.9.202.5-rusty
typescript 5.5.2
```

**Comment by dsherret** [comment]
I opened https://github.com/denoland/deno_cache_dir/pull/62

In the meantime, you can run `deno clean` to fix the issue.

**Comment by scarf005** [comment]
yes, `deno clean` temporarily fixes it but happens again immediately after i edit some script.

```sh
$ deno clean
Removed /home/scarf/.cache/deno (1081 files, 50.57MB)
$ deno task changelog --since "1 week ago" --until 2024-09-30
# ...

# edit read_commits.ts for a bit

$ deno task changelog --since "1 week ago" --until 2024-09-30
Task changelog deno run -A scripts/changelog/changelog_reddit.ts "--since" "1 week ago" "--until" "2024-09-30"
error: JSR package manifest for '@david/dax' failed to load. trailing characters at line 13 column 1
$ deno clean
Removed /home/scarf/.cache/deno (1181 files, 51.38MB)
$ deno task changelog --since "1 week ago" --until 2024-09-30
# works
```

**Comment by dsherret** [comment]
Kill all running deno processes and try again. There's probably an lsp using the new version that's caching stuff.
