### ISSUE TITLE
Blob type set to empty string causing InvalidStateError

### ISSUE THREAD

**Issue by db213** [denoland/deno#25971]
Version:
deno 2.0.0-rc.9 (release candidate, release, aarch64-apple-darwin)
v8 12.9.202.13-rusty
typescript 5.6.2

Hi there,

I'm trying to use the `fetch` API to grab a locally saved file. I'm using `loadImageBitmap` with an absolute path to a JPG file passed in as the url, prefixed with `file:///`. I can see that the the `fetch` has succeeded, however the resulting blob from `const blob = await res.blob()` looks like `Blob { size: 695303, type: "" }` and the empty string value of `type` is causing the following error:

```
error: InvalidStateError: Unsupported type ''
    at ext:deno_canvas/01_image.js:236:15
    at eventLoopTick (ext:core/01_core.js:175:7)
    at async loadImageBitmap (file:///Users/daphnebogosian/Library/Caches/deno/npm/registry.npmjs.org/webgpu-utils/1.9.2/dist/1.x/webgpu-utils.module.js:5937:12)
    at async Promise.all (index 2)
    at async createTextureFromImages (file:///Users/daphnebogosian/Library/Caches/deno/npm/registry.npmjs.org/webgpu-utils/1.9.2/dist/1.x/webgpu-utils.module.js:5963:24)
    at async ResourceSetUnkeyed.<anonymous> (file:///Users/daphnebogosian/Documents/d2p-mk2/packages/engine/src/lib/resources/image-textures-async/index.ts:22:21)
```

I'm stumped on how to get around this, any tips or suggestions on what I'm doing wrong much appreciated ~~, but also it looks like to me that the `type` is probably erroneously being set to `''` based on the documentation for [ResponseType](https://docs.deno.com/api/web/~/ResponseType).~~

Edit: I've realised I was looking at the documentation for `Response` and not for `Blob`. `Blob::type` is typed as just a string so it can very validly be set to empty string.

Edit2: Looks like when `fetch` resolves to reading a blob out of the filesystem, the content-type of the response is not set. And then the mimetype becomes `null`/`''`.

Thanks so much for reading!

**Comment by Hajime-san** [comment]
I think you should use `Deno.readFile` instead `fetch` due to `file:///` scheme is not supported.

```ts
const imageData = new Blob(
  [await Deno.readFile('sample.png')],
  { type: 'image/png' },
);
await createImageBitmap(imageData);
```

- https://github.com/denoland/deno/issues/2150#issuecomment-693223287

**Comment by db213** [comment]
Thank you, that helped me get a little further! The type is now set correctly to image/jpeg, however it looks like jpegs simply [aren't supported](https://github.com/denoland/deno/blob/main/ext/canvas/01_image.js#L235) at the moment? (Though for now I should be able to get away with converting to pngs)

**Comment by Hajime-san** [comment]
The enhancement of `createImageBitmap` API is going here.
If this PR will shipped, basic jpeg will be available.

- https://github.com/denoland/deno/pull/25517

**Comment by lucacasonato** [comment]
We do not set `content-type` for local file fetches. This is documented here, and is expected behaviour: https://docs.deno.com/runtime/reference/web_platform_apis/#fetching-local-files

**Comment by Hajime-san** [comment]
@db213 
Hi, sorry for the delay in sharing, my guidance earlier was a mistake.
It seems that your code will work correctly  without `Blob.type` in the latest version of Deno.

Ref: https://github.com/denoland/deno/pull/28741
