### ISSUE TITLE
opening lib.deno.url.d.ts causes frequent LSP errors

### ISSUE THREAD

**Issue by jespertheend** [denoland/deno#25999]
Version: Deno `1.46.3`

Create a .ts file with the following contents:
```ts
type Foo = URLPatternInit;
```

then ctrl/cmd click `URLPatternInit`

<img width="426" alt="image" src="https://github.com/user-attachments/assets/395fa987-bb73-4fb8-a469-cbe7cd9d65b8">

But please prioritize #16439 over this one because error messages like these are probably the main reason why I leave the Deno extension disabled most of the time. Either a setting or just not showing notifications for errors like these in the first place would solve this issue and many future issues alike.

**Comment by nayeemrmn** [comment]
I'm struggling to reproduce. Is there a particular the way the workspace is setup or lack thereof?

**Comment by jespertheend** [comment]
Seems like I have to toggle the `typescript.tsserver.experimental.enableProjectDiagnostics` setting on and off to be able to reproduce this. I have no idea why 😅

**Comment by yazan-abdalrahman** [comment]
Can I work on it?
[nayeemrmn](https://github.com/nayeemrmn)

**Comment by jespertheend** [comment]
I'm also seeing this when toggling `typescript.enablePromptUseWorkspaceTsdk`, `typescript.format.enable` and many other settings on and off again, so I don't think this is caused by https://github.com/denoland/vscode_deno/issues/437 specifically.
