### ISSUE TITLE
Hidden chars in output of "deno info"?

### ISSUE THREAD

**Issue by jradxl** [denoland/deno#26017]
Deno version 2.0.0-rc.10

At the console, `deno info` looks quite normal, thus:

```
DENO_DIR location: /home/john/.cache/deno
Remote modules cache: /home/john/.cache/deno/deps
npm modules cache: /home/john/.cache/deno/npm
Emitted modules cache: /home/john/.cache/deno/gen
Language server registries cache: /home/john/.cache/deno/registries
Origin storage: /home/john/.cache/deno/location_data
```

If I run using Deno.command, and if I look at each char individually, (and showing first two lines for brevity), I get:
```
,0,m,,1,m,D,E,N,O,_,D,I,R, ,l,o,c,a,t,i,o,n,:,,0,m, ,/,h,o,m,e,/,j,o,h,n,/,.,c,a,c,h,e,/,d,e,n,o,
,,0,m,,1,m,R,e,m,o,t,e, ,m,o,d,u,l,e,s, ,c,a,c,h,e,:,,0,m, ,/,h,o,m,e,/,j,o,h,n,/,.,c,a,c,h,e,/,d,e,n,o,/,d,e,p,s,
```

What is the 0m1m (ie ,0,m,,1,m,) at start of line?
And the ,,0,m, after the colon
Should they be there?

`deno --version `doesn't
d,e,n,o, ,2,.,0,.,0,-,r,c,.,1,0, 

`deno clean` does on stderr
,0,m,,3,2,m,R,e,m,o,v,e,d,,0,m, ,/,h,o,m,e,

deno fmt doesn't on stderr
C,h,e,c,k,e,d, ,2, ,f,i,l,e,s,

**Comment by lucacasonato** [comment]
These are ANSI escape codes (they are used to make the text colored in your terminal). https://en.wikipedia.org/wiki/ANSI_escape_code

When you invoke Deno without `stdout` / `stderr` being a TTY, we will automatically disable color output and print pure text. But if you are running a subprocess from a process spawned in your terminal (which is a TTY), then the text will not be disabled.

You can manually disable color output though: either pass the `--no-color` flag to the `deno` invocation, or run with the `NO_COLOR=1` environment variable.

**Comment by jradxl** [comment]
Oh, thanks. I should have known that!
Does `NO_COLOR=1` apply to anything I might run with` deno.command/spawn`?

**Comment by lucacasonato** [comment]
Yes. Environment variables inherit from their parent process.
