### ISSUE TITLE
Repl allows redeclaring const

### ISSUE THREAD

**Issue by ashishkujoy** [denoland/deno#26026]
Version: Deno 1.46.3 (stable, release, x86_64-apple-darwin)
v8 12.9.202.5-rusty
typescript 5.5.2

Repl does not show error for redeclaring a const variable.

type
`const a = 34;`
again type
`const a = 45;`
type
`a` => 45.

Expected behaviour repl should show error, actual behaviour no error.

**Comment by lucacasonato** [comment]
This is intentional, to make it easier to run the same snippet of code multiple times. It matches Chrome's DevTools behaviour. https://developer.chrome.com/blog/new-in-devtools-92#const-redeclaration

**Comment by ashishkujoy** [comment]
Cool thanks.
