### ISSUE TITLE
[Windows/NT] 'await Deno.writeAll(Deno.stdout, bytes)' blocks code execution

### ISSUE THREAD

**Issue by pedropaulosuzuki** [denoland/deno#26035]
On Windows/NT systems, if you run either CMD or PowerShell, the script execution is paused. Execution resumes only after pressing arrow down on the keyboard.

```ts
for(let i = 0; i < 10000; i++) {
  for(let j = 0; j < 20000; j++) { for(let k = 0; k < 20000; k++) {} }
  await Deno.writeAll(Deno.stdout, new TextEncoder().encode('\r' + i));
}
```

This does not happen on GNU/Linux systems, where you can continue to pipe to stdout, click anywhere and the script continues running.

Version: Deno 1.42.1
Windows 10

**Comment by pedropaulosuzuki** [comment]
Obs: can't test newer versions on Windows/NT, as it was tested on a client machine which is subject to company policy and cannot be updated easily.

On my GNU/Linux machines, I'm running latest (Deno 1.46.3).

**Comment by yazan-abdalrahman** [comment]
@satyarohith  
It was fixed on the latest source.
https://github.com/user-attachments/assets/b166fd84-0882-4889-92bd-2e45dbcb37a0

**Comment by satyarohith** [comment]
Closing this issue as it's fixed on main. Thanks for testing it @yazan-abdalrahman!

**Comment by pedropaulosuzuki** [comment]
@satyarohith @yazan-abdalrahman could you guys test on CMD/PowerShell before closing? Testing on VSCode might be inconclusive because maybe it doesn't send a pause signal there.

**Comment by pedropaulosuzuki** [comment]
And I just realized I described the issue poorly.

The script pauses execution when you run the code, then you click on the text somewhere in the window. My bad.

**Comment by yazan-abdalrahman** [comment]
> @satyarohith @yazan-abdalrahman could you guys test on CMD/PowerShell before closing? Testing on VSCode might be inconclusive because maybe it doesn't send a pause signal there.

@pedropaulosuzuki 
Can provide me with complete steps and project files for reproducing it with vscode?

**Comment by pedropaulosuzuki** [comment]
> > @satyarohith @yazan-abdalrahman could you guys test on CMD/PowerShell before closing? Testing on VSCode might be inconclusive because maybe it doesn't send a pause signal there.
> 
> @pedropaulosuzuki Can provide me with complete steps and project files for reproducing it with vscode?

Sure!

1. Open Windows PowerShell
1. Type "deno repl"
1. Paste the code (the same from earlier)
1. Press enter
1. While running the code, click in any character inside the terminal

The code should be paused. It resumes when you press the down arrow key.

**Comment by pedropaulosuzuki** [comment]
Here's a recording. Mine works fine because it's running on GNU/Linux. Just do the same in Windows PowerShell (or CMD). The number stops increasing when you click. I cannot record the Windows version, unfortunately.

[Screencast from 09-10-2024 10:15:59.webm](https://github.com/user-attachments/assets/b9d27378-efcd-4aef-aa25-149e4aff4601)

**Comment by pedropaulosuzuki** [comment]
Upon further testing, it seems Windows CMD/Powershell defers any writes to after you release the click, and maybe that causes the .writeAll to pause (and as it was awaited, it won't continue).

If it was a console.log() instead, it wouldn't log until released, but the code wouldn't stop running in the background (it would just queue the outputs).

**Comment by yazan-abdalrahman** [comment]
@satyarohith  @pedropaulosuzuki  
It works on CMD and PowerShell.
https://github.com/user-attachments/assets/d80b0cb0-f288-430c-8401-8d7eb25bfa69

**Comment by yazan-abdalrahman** [comment]
@satyarohith  @pedropaulosuzuki 

It seems it is not a bug.  Maybe this issue is related to your Windows configuration because I test it in a some of window's devices and can't reproduce it.

**Comment by pedropaulosuzuki** [comment]
> @satyarohith @pedropaulosuzuki
> 
> It seems it is not a bug. Maybe this issue is related to your Windows configuration because I test it in a some of window's devices and can't reproduce it.

Hmm, interesting! Maybe it's a Windows 10 only issue? Or maybe it was indeed fixed on 2.0.0 Release Candidate. At least now we know it doesn't happen on Windows 11, latest Deno.

**Comment by yazan-abdalrahman** [comment]
> > @satyarohith @pedropaulosuzuki
> > It seems it is not a bug. Maybe this issue is related to your Windows configuration because I test it in a some of window's devices and can't reproduce it.
> 
> Hmm, interesting! Maybe it's a Windows 10 only issue? Or maybe it was indeed fixed on 2.0.0 Release Candidate. At least now we know it doesn't happen on Windows 11, latest Deno.


I don't sure it's related to the Windows version, and when I tried it on Deno 1.46.3, I didn't have this issue.

**Comment by yazan-abdalrahman** [comment]
> > > @satyarohith @pedropaulosuzuki
> > > It seems it is not a bug. Maybe this issue is related to your Windows configuration because I test it in a some of window's devices and can't reproduce it.
> > 
> > 
> > Hmm, interesting! Maybe it's a Windows 10 only issue? Or maybe it was indeed fixed on 2.0.0 Release Candidate. At least now we know it doesn't happen on Windows 11, latest Deno.
> 
> I don't sure it's related to the Windows version, and when I tried it on Deno 1.46.3, I didn't have this issue.

I will check it on Windows 10.

**Comment by yazan-abdalrahman** [comment]
Deno 1.46.3


https://github.com/user-attachments/assets/b86b03b6-193e-46c0-b4b9-88706d1243b7

**Comment by yazan-abdalrahman** [comment]
Yes, the issue is on Windows 10. 
https://github.com/user-attachments/assets/9d2ba13e-55e2-4abb-8a9c-996a5cfd5ff9

**Comment by pedropaulosuzuki** [comment]
I recorded with a phone, but the size was too big and I had to rerender both files in Blender in order for them to fit. It happens hehe


Here the problem in CMD:

https://github.com/user-attachments/assets/36a1ce19-7c2b-432d-a628-adacc7ee0b4a

Here the problem in Powershell:

https://github.com/user-attachments/assets/9302218b-ddeb-45b9-ba8e-42b7810bd633

**Comment by yazan-abdalrahman** [comment]
It seems it is not a bug.

**Comment by yazan-abdalrahman** [comment]
> I recorded with a phone, but the size was too big and I had to rerender both files in Blender in order for them to fit. It happens hehe
> 
> Here the problem in CMD:
> 
>  CMD.mp4 
> Here the problem in Powershell:
> 
>  Powershell.mp4

Yes, I pushed recorded, and it worked on Windows 11, but it stalled on Windows 10. 

hence, I suppose that depends on the OS itself, hence I guess we can't consider this bug from Deno.

**Comment by pedropaulosuzuki** [comment]
> > I recorded with a phone, but the size was too big and I had to rerender both files in Blender in order for them to fit. It happens hehe
> > Here the problem in CMD:
> > CMD.mp4
> > Here the problem in Powershell:
> > Powershell.mp4
> 
> Yes, I pushed recorded, and it worked on Windows 11, but it stalled on Windows 10.
> 
> hence, I suppose that depends on the OS itself, hence I guess we can't consider this bug from Deno.
> 
> @satyarohith

Clearly Windows 10 is doing something different from the rest here. I believe it needs more investigation before we can conclude if Windows 10 is just utterly broken or if it has a workaround that Deno can use.

**Comment by pedropaulosuzuki** [comment]
@yazan-abdalrahman, does this happen on Windows 10 + VSCode? I think it is worth a try.

**Comment by yazan-abdalrahman** [comment]
@pedropaulosuzuki 

This issue only occurs on Windows 10 and is tied to a configuration. It is not a bug or a deno issue as Windows 10 and Windows 11 are the same platform, unlike Linux, Windows, or MacOS.

**Comment by pedropaulosuzuki** [comment]
> This issue only occurs on Windows 10 and is tied to a configuration. It is not a bug or a deno issue as Windows 10 and Windows 11 are the same platform, unlike Linux, Windows, or MacOS.

The bug exists on Windows 10. Then either we consider Win10 unsuported (like we do with Windows 7) or it is an issue.

Windows 10 and Windows 11 are not the same platform. If they were, then the bug wouldn't be happening in only one of them.

**Comment by pedropaulosuzuki** [comment]
> This issue only occurs on Windows 10 and is tied to a configuration.

I'm a bit confused. The issue happens on Windows 10, yes. But what do you mean configuration? We saw that it happens in both cmd and powershell. It could be happening in other places (that's why I suggested we test Win10 + VSCode to see if it is also happening there or not). As far as we know, it is a general Windows 10 issue.

**Comment by lucacasonato** [comment]
@piscisaureus Any ideas?

**Comment by pedropaulosuzuki** [comment]
> [@piscisaureus](https://github.com/piscisaureus) Any ideas?

As Windows 10 is EOL, I'm not against closing this issue, if any of my clients complain I'll ask them to upgrade to ZorinOS or similar distros.
