### ISSUE TITLE
`deno install` failed with "the following required arguments were not provided"

### ISSUE THREAD

**Issue by danilkinkin** [denoland/deno#26048]
Deno failed when try to install all dependencies. In docs says that "[if no dependency is specified, installs all dependencies listed in the config file](https://docs.deno.com/runtime/reference/cli/install/)". So try to execute `deno install`.

Which arguments is required?

```bash
❯ deno install
error: the following required arguments were not provided:
  <cmd>...

Usage: deno install <cmd>...
```

Also why is there no indication of which version of deno the current documentation applies to?

Version: Deno 1.46.3

In Deno v2.0.0-rc.10 its work OK

**Comment by marvinhagemeister** [comment]
Running `deno install` to install all dependencies is a new behaviour in Deno 2 and not present in 1.x . Looks like we forgot to flag it as being Deno 2 only

**Comment by danilkinkin** [comment]
It is good practice in this case to indicate the version to which the documentation applies. Or add switcher

I mean there: https://docs.deno.com/

**Comment by marvinhagemeister** [comment]
We likely won't do a global switcher as maintaining two separate content branches is a lot of work. We'll likely go with annotating certain features new in Deno 2 instead.

**Comment by danilkinkin** [comment]
Not everyone can use only the latest version of deno. Projects on older versions of deno will need to be maintained as well and documentation should be preserved for older versions.

**Comment by marvinhagemeister** [comment]
The changes between Deno 1 and Deno 2 are not substantial enough to justify a complete different content branch. Most changes revolve around the installation commands being different and the removal of long deprecated APIs. We already had removed mentions of those deprecated APIs a few years back in our docs. The rest stays the same regardless of whether you're using Deno 1 or Deno 2.

To see the full list of difference, check out this page: https://docs.deno.com/runtime/reference/migration_guide/#api-changes
