### ISSUE TITLE
regression: console.log excludes properties named "cause"

### ISSUE THREAD

**Issue by tenkoverse** [denoland/deno#26047]
### Issue Overview

I found a weird logging issue in Deno ``2.0.0-rc.10`` that results in incomplete console output when handling some objects (at least in my experimenting). 

The logged output may omit sections of objects, that are present when serialized via `JSON.stringify()`.

I was able to find and reproduce through usage with the Effect library.

### Steps to reproduce

1. Set up a new deno project folder
2. Create a ``main.ts`` file.
3. Copy this code into ``main.ts``

```typescript
// ### Make sure NOT to use effect@3.9.0 ###
import { Effect } from "npm:effect@3.8.5";

const data = await Effect.runPromiseExit(Effect.fail("my error"))

console.log(data)
console.log(JSON.stringify(data))
```
5. Run using ``deno -A main.ts``
6. Using ``deno upgrade`` and ``deno upgrade rc`` switch back and forward between ``1.46.3`` and ``2.0.0-rc.10`` and observe correct outputs in ``1.46.6`` and incorrect outputs in ``2.0.0-rc.10``. Make sure to restart the deno language server after running upgrade.

### Expected outputs
See effect docs for this example https://effect.website/docs/guides/essentials/running-effects#runpromiseexit

### Observed Outputs
**Deno 1.46.3:**
- ``cause`` present in object and serialised logs.
```terminal
{
  _id: "Exit",
  _tag: "Failure",
  cause: { _id: "Cause", _tag: "Fail", failure: "my error" }
}
{"_id":"Exit","_tag":"Failure","cause":{"_id":"Cause","_tag":"Fail","failure":"my error"}}
```

**Deno 2.0.0-rc.10:**
- ``cause`` key not on the logged object, only in the serialised . 
```terminal
{ _id: "Exit", _tag: "Failure" }
{"_id":"Exit","_tag":"Failure","cause":{"_id":"Cause","_tag":"Fail","failure":"my error"}}
```

### Expected Behavior

Console logging should display all object properties, including nested details, across all Deno versions to ensure consistent debugging and output verification without relying on serialization functions like `JSON.stringify()`.

**Comment by nathanwhit** [comment]
This appears to be a regression from https://github.com/denoland/deno/pull/25327
