### ISSUE TITLE
Error: "Attempted to load JSON module without specifying 'type': 'json'" when importing JSON in Deno REPL

### ISSUE THREAD

**Issue by nestarz** [denoland/deno#26041]
#### Deno Version: 
`2.0.0-rc.10`

#### Environment:
- REPL is running with all permissions allowed.
- Attempted to import a JSON file using: 
  ```js
  import a from "./deno.json" with { "type":"json" };
  ```
  
#### Error Message:
```bash
Uncaught TypeError: Attempted to load JSON module without specifying "type": "json" attribute in the import statement.
    at async <anonymous>:1:47
```

#### Expected Behavior:
The JSON file should load correctly when specifying `"type": "json"` in the `import` statement in Deno REPL.

#### Actual Behavior:
The error occurs despite specifying the `"type": "json"` attribute in the `import` statement.

#### Steps to Reproduce:
1. Run Deno REPL with all permissions allowed.
2. Attempt to import a JSON file using the following statement:
   ```js
   import a from "./deno.json" with { "type": "json" };
   ```
3. Observe the TypeError.

#### Additional Information:
- This issue seems related to JSON module handling in Deno REPL for the specific version (`2.0.0-rc.10`).
- JSON import works as expected outside the REPL.

**Comment by bartlomieju** [comment]
Ref https://github.com/denoland/deno_ast/pull/279
