### ISSUE TITLE
`imports` are not resolved when running `deno run [package-name]`

### ISSUE THREAD

**Issue by mayank99** [denoland/deno#26046]
`deno run build` **works** when using the following `deno.json`:

```json
"tasks": {
  "build": "deno run -A npm:@11ty/eleventy@3"
}
```

but **fails** with the following:

```json
"tasks": {
  "build": "deno run -A @11ty/eleventy"
},
"imports": {
  "@11ty/eleventy": "npm:@11ty/eleventy@3"
}
```

Version: Deno `2.0.0-rc.10`

**Note**: I'm only using [`@11ty/eleventy`](https://www.npmjs.com/package/@11ty/eleventy) as an example. The issue can also be reproduced using a different package, such as [`serve`](https://www.npmjs.com/package/serve).

---

I would expect the imports to be considered by tasks. Using `npm:` specifiers directly in the tasks is not ideal, because it would diverge from the version of the package used in the user code. The CLI and the runtime code should use the same version.

The same issue also happens when using `package.json` instead of `deno.json`.

<details><summary>package.json</summary>

```json
{
  "type": "module",
  "scripts": {
    "build": "deno run -A @11ty/eleventy",
  },
  "dependencies": {
    "@11ty/eleventy": "^3.0.0",
  }
}

```

</details> 

In comparison, the following works correctly in Node:

<details><summary>package.json</summary>

```json
{
  "type": "module",
  "scripts": {
    "build": "@11ty/eleventy",
  },
  "dependencies": {
    "@11ty/eleventy": "^3.0.0",
  }
}

```

</details>

**Comment by mayank99** [comment]
A similar issue: `imports` are also not resolved inside `compilerOptions`. For example, I have to use `"jsxImportSource": "npm:preact"` instead of `"jsxImportSource": "preact"`.

I think both of these issues are related; in both cases, `deno.json` fields are unable to look for installed dependencies.

**Comment by dsherret** [comment]
`deno run -A [package-name]` is not supported, but follow https://github.com/denoland/deno/issues/19955 for updates on support for this. You need to specify `deno run -A npm:@11ty/eleventy` in the meantime.
