### ISSUE TITLE
Bug: `deno upgrade` cannot proceed due to lockfile version

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/deno#26060]
This error only happens when the commands are run in a project with a `deno.lock` v4 file.

1. Create a project with lockfile v4
2. Run `deno upgrade` to downgrade to latest release (1.46.3)
3. Run `deno upgrade canary` -> error

Output:

```sh
$ deno ugprade canary
error: Unsupported lockfile version '4'. Try upgrading Deno or recreating the lockfile at '/Users/marvinh/dev/denoland/fresh-2/deno.lock'.
```

Not sure if this is something we have fixed in newer Deno versions.

Version: Deno 1.46.3

**Comment by lucacasonato** [comment]
We have fixed this in newer versions.
