### ISSUE TITLE
Deno v2 crashes when installed on Windows but executed on WSL2 path

### ISSUE THREAD

**Issue by Xernisfy** [denoland/deno#26080]
Hi Deno devs,

Some change in commit https://github.com/denoland/deno_config/commit/59e578eaea0b720b4d79d5617b1f2a1c076b0d2b broke the ability to use deno (installed on Windows host) to be run on a WSL path.
Introduced to Deno in [18beb13f](https://github.com/denoland/deno/commit/18beb13f0ea750ba36b7f062f3cfdcc08c610431).

```text
PS Microsoft.PowerShell.Core\FileSystem::\\wsl.localhost\dev\home\dev\me> Get-Command deno

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     deno.exe                                           2.0.0.0    C:\Users\me\.deno\bin\deno.exe

```
```text
PS Microsoft.PowerShell.Core\FileSystem::\\wsl.localhost\dev\home\dev\me> $env:RUST_BACKTRACE = 'full'; deno

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: windows x86_64
Version: 2.0.0
Args: ["C:\\Users\\me\\.deno\\bin\\deno.exe"]

thread 'main' panicked at C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\deno_config-0.37.1\src\workspace\mod.rs:398:38:
called `Result::unwrap()` on an `Err` value: UrlToFilePathError(Url { scheme: "file", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("wsl.localhost")), port: None, path: "/dev/home/dev/me/", query: None, fragment: None })
```
<details>
<summary>RUST BACKTRACE</summary>
<code>stack backtrace:
   0:     0x7ff7928ba20d - node_api_get_module_file_name
   1:     0x7ff79109bee9 - node_api_get_module_file_name
   2:     0x7ff792897321 - node_api_get_module_file_name
   3:     0x7ff7928be0c6 - node_api_get_module_file_name
   4:     0x7ff7928bd98a - node_api_get_module_file_name
   5:     0x7ff7928bd541 - node_api_get_module_file_name
   6:     0x7ff790ef9a13 - uv_close
   7:     0x7ff7928be467 - node_api_get_module_file_name
   8:     0x7ff7928be307 - node_api_get_module_file_name
   9:     0x7ff7928be24f - node_api_get_module_file_name
  10:     0x7ff7928be238 - node_api_get_module_file_name
  11:     0x7ff7943f6dc4 - tree_sitter_javascript
  12:     0x7ff7943f7300 - tree_sitter_javascript
  13:     0x7ff79120d1d3 - node_api_get_module_file_name
  14:     0x7ff790bc65c5 - uv_mutex_destroy
  15:     0x7ff790bc399e - uv_mutex_destroy
  16:     0x7ff790e60704 - uv_close
  17:     0x7ff790ed213d - uv_close
  18:     0x7ff7908a5e0d - uv_mutex_destroy
  19:     0x7ff790fc67b5 - node_api_get_module_file_name
  20:     0x7ff7909f98df - uv_mutex_destroy
  21:     0x7ff790efc07c - uv_close
  22:     0x7ff79087221f - uv_mutex_destroy
  23:     0x7ff790fc6896 - node_api_get_module_file_name
  24:     0x7ff794398c8c - tree_sitter_javascript
  25:     0x7ffc5b9f7374 - <unknown>
  26:     0x7ffc5d93cc91 - RtlUserThreadStart</code>
</details>

Please let me know if you need more info or if this is a too-niche case!
Kind regards

**Comment by dsherret** [comment]
I think maybe this will be fixed in the next release (I'm not sure though because I don't have a windows machine atm--I usually program on a windows machine)

**Comment by Xernisfy** [comment]
No worries, I'll be using an older build until then.
Thanks a lot for the incredible fast fix!!!

**Comment by michaelvitello** [comment]
Hello, I started a Deno 2 setup + React (without Vite) from scratch yesteryda (still tweaking a few things as we speak) and all from my Windows 11 setup. It's absolutely flawless so far. Might have just been waiting for the next update.
