### ISSUE TITLE
poor error message when using bare `require` in a `.js`/`.ts` file

### ISSUE THREAD

**Issue by philipheinser** [denoland/deno#26097]
The website claims: 

> Backwards compatible with Node.js

but when I try to run my node website it errors:
```
deno task dev
Task dev deno server.js
error: Uncaught (in promise) ReferenceError: require is not defined
const express = **require('express');**
```

**Comment by natmfat** [comment]
have you seen the docs on this? you can only use `require` with a `cjs` file extension
https://docs.deno.com/runtime/fundamentals/node/

**Comment by vyshnavsdeepak** [comment]
Maybe a slightly misleading title.

Deno doesn't support the require syntax natively because it uses ECMAScript modules (import/export) instead of CommonJS (require)

But they have explained in detail here - [https://docs.deno.com/runtime/fundamentals/node/#commonjs-support](https://docs.deno.com/runtime/fundamentals/node/#commonjs-support)

For your case if server.js is renamed to server.cjs, it would work.

**Comment by nathanwhit** [comment]
Retitled as while I don't think we're likely to support CJS with the `.js` extension, we could have a better error message here suggesting you rename your file to `.cjs`

**Comment by bartlomieju** [comment]
@philipheinser can you please provide the content of your `server.js` file?

**Comment by philipheinser** [comment]
@bartlomieju @nathanwhit Ok I dint check the docs maybe not a real issue more of false marking. In nodejs I dont have to name my files `.cjs`. I just wanted to try Deno for our website but dont want to migrate code. 

<img width="1217" alt="Screenshot 2024-10-10 at 17 17 22" src="https://github.com/user-attachments/assets/0996930d-c73f-4bbe-81e9-2f9f8b7edb56">

**Comment by BlueHtml** [comment]
@bartlomieju @nathanwhit
Is it possible to run `.js` as `.cjs` through command line options or preloaded code? Unfortunately, after reviewing the Deno documentation, neither method is supported.

Renaming `.js` to `.cjs` is also a hindrance in transitioning from Node.js to Deno. I hope there is a better solution available.

**Comment by marvinhagemeister** [comment]
No, currently there is no way in Deno to run code as CommonJS outside of `.cjs` files or npm packages.

**Comment by bartlomieju** [comment]
We discussed support for `"type": "commons"` option in `package.json` and are planning to add it in the next few days.

**Comment by bartlomieju** [comment]
@philipheinser FYI if you upgrade to latest canary (`deno upgrade canary`), you can put `"type": "commonjs"` in your `package.json` and then use `--unstable-detect-cjs` CLI flag and your project should work fine. This will have no effect whatsoever on your existing Node.js app, but should make it possible to run the project in Deno too. We're looking for more ways to make it easier for our users to run their existing projects with minimal changes and PRs like https://github.com/denoland/deno/pull/26287 aid with that.

I'm gonna close this issue for now, but let me know if that satisfies your needs to not require changing file extensions. Thanks!

**Comment by BlueHtml** [comment]
@bartlomieju I tested it according to your steps, and it works fine.
