### ISSUE TITLE
Failed creating symlink in node_modules folder

### ISSUE THREAD

**Issue by wickedknock** [denoland/deno#26116]
Version: Deno 2.0.0

I have a node project running a simple express server. I deleted the node_modules folder and ran deno install and I keep getting this error. I saw ryan dhals new video on deno 2 and tried this but its not working I cannot convert my old projects to work with package.json. Guess its not really that simple. Really want to switch to deno.

Error: 

`error: Failed creating symlink in node_modules folder

Caused by:
    Incorrect function. (os error 1), symlink '..\..\semver@7.6.3\node_modules\semver' -> 'G:\deno\node_modules\.deno\ts-loader@9.5.1\node_modules\semver'`

**Comment by lucacasonato** [comment]
Is the first path and second path in the error message on the same drive, or two different drives? (like `C:\` and `G:\`)

**Comment by Dendrobyte** [comment]
Uncertain if helpful, but I can second this issue and recreate it consistently. Came looking for the same thing, and it does appear to be because of multiple drives.

As for @lucacasonato 's question above, I can confirm that the different drives is an issue. I'm on Windows, installed Deno this morning. Worked on C:/ drive (which I attempted after finding this thread) where the `deno` command resides in the path.
```
PS C:\Users\markb\Documents\infinite-game\frontend> deno --version
deno 2.0.2 (stable, release, x86_64-pc-windows-msvc)
v8 12.9.202.13-rusty
typescript 5.6.2
```

Full terminal output when on E:/ drive
```bash
PS C:\Users\markb> cd E:\infinite_game\infinite-game\
PS E:\infinite_game\infinite-game> deno run -A npm:create-vite
// This worked OK
PS E:\infinite_game\infinite-game> cd frontend
PS E:\infinite_game\infinite-game\frontend> deno task dev
Task dev vite
vite: command not found
PS E:\infinite_game\infinite-game\frontend> deno install
error: Failed creating symlink in node_modules folder

Caused by:
    Incorrect function. (os error 1), symlink '..\..\esbuild@0.21.5\node_modules\esbuild' -> 'E:\infinite_game\infinite-game\frontend\node_modules\.deno\vite@5.4.9\node_modules\esbuild'
```

When on C:/ drive, the steps were the same and on `deno install` it worked first try and then `deno task dev` worked as expected. This was all on a fresh clone of a near-empty repository.

**Comment by bartlomieju** [comment]
Thanks for more info @Dendrobyte, @nathanwhit is looking into this problem.

**Comment by Al00X** [comment]
I had the same problem; traced the error and found out that the symlinks Deno is trying to make, won't be created on non-NTFS drives.
My solution was to temporary move the project to drive C, run `deno install` and after it was successful, move node_modules back to its original place (the other drive).

**Comment by wickedknock** [comment]
> Is the first path and second path in the error message on the same drive, or two different drives? (like `C:\` and `G:\`)

Do not know which drive is the first one I Tried to find it but got nothing from it

**Comment by miaLDN** [comment]
All my projects and source code are on network drives.  Suggestion to move TB of data to C:\ is a non-starter.

deno just fails with:

``` ps1
error: Creating junction in node_modules folder

Caused by:
    The file or directory is not a reparse point. (os error 4390)
```
