### ISSUE TITLE
v2: Deno.ServeOptions type breakage / old docs

### ISSUE THREAD

**Issue by NfNitLoop** [denoland/deno#26118]
Version: Deno 2.0.0

Two problems here:
1. `Deno.ServeOptions["hostname"]` seems to have been moved into `Deno.ServeTcpOptions`.
2. That change is not reflected on the API docs page here: https://docs.deno.com/api/deno/~/Deno.ServeOptions

---

Just updated to v2 (🎉) and am trying it out w/ lots of my code. Had a simple little echo script that ran into type problems with `--check` (though *not* at runtime).

```ts
#!/usr/bin/env deno run --check --allow-net

const options: Deno.ServeOptions = {
    hostname: "[::]", // ipv6 please
}

Deno.serve(options, (req, info) => {
    console.log(`${info.remoteAddr.hostname} requested: ${req.url}`)
    return new Response("Hello, world!")
})
```

This now fails to type-check. But it runs just fine if I remove `--check`.  That seems like an OK breaking change for the v2 semver jump?

I can also fix it by updating my type to `Deno.ServeTcpOptions`. 👍 

… but the docs at https://docs.deno.com/api/deno/~/Deno.ServeOptions and https://docs.deno.com/api/deno/~/Deno.serve haven't been updated.

The language server is telling me this is the type of `Deno.serve()`:

<img width="689" alt="Screenshot 2024-10-10 at 9 12 20 AM" src="https://github.com/user-attachments/assets/d6c7b160-7f1a-42ed-9bae-b19c6cde3c5b">

**Comment by lucacasonato** [comment]
They are updated. You can see that the types on https://docs.deno.com/api/deno/~/Deno.serve show this as a possible type of `Deno.serve()`: 

![image](https://github.com/user-attachments/assets/ae495b8c-be2f-4a35-bb2c-5bb4f98c3307)
