### ISSUE TITLE
errors with auto completion

### ISSUE THREAD

**Issue by GiveMeFox** [denoland/deno#26122]
Version: deno 2.0.0

steps to reproduce:
`curl -fsSL https://deno.land/install.sh | sh`
![image](https://github.com/user-attachments/assets/ddfd30ba-168f-4d5c-9501-a21016d55492)

when having bash selected there's a warning
![image](https://github.com/user-attachments/assets/e2300812-80e1-43a2-832e-3470f4f82923)

but after restarting my console i get this error

```
~/.deno/env (line 4): “case” builtin not inside of switch block
case ":${PATH}:" in
^~~^
from sourcing file ~/.deno/env
	called on line 8 of file ~/.profile
from sourcing file ~/.profile
	called on line 23 of file ~/.config/fish/config.fish
from sourcing file ~/.config/fish/config.fish
	called during startup
.: Error while reading file '/home/givemefox/.deno/env'
```
this is the env file

```
#!/bin/sh
# deno shell setup; adapted from rustup
# affix colons on either side of $PATH to simplify matching
case ":${PATH}:" in
    *:"/home/givemefox/.deno/bin":*)
        ;;
    *)
        # Prepending path in case a system-installed deno executable needs to be overridden
        export PATH="/home/givemefox/.deno/bin:$PATH"
        ;;
esac
```

**Comment by marvinhagemeister** [comment]
Which shell are you running? Are you running `fish` by chance and installed the `bash` bindings? You can check which shell you are running with this command:

```sh
echo $0
```

**Comment by marvinhagemeister** [comment]
Are you on macOS? So far everything points to the `fish` shell being used, which is not compatible with all syntaxes of bash.

**Comment by nathanwhit** [comment]
What does your `config.fish` look like? From the looks of it you may be sourcing `.profile` in your `config.fish`.
