### ISSUE TITLE
bug(deno/add or deno/install): do not respect .npmrc

### ISSUE THREAD

**Issue by familyboat** [denoland/deno#26139]
deno 2.0.0 (stable, release, x86_64-unknown-linux-gnu)
v8 12.9.202.13-rusty
typescript 5.6.2

Here is my .npmrc:
```plain
registry=https://registry.npmmirror.com
```

I install dependency with `deno add --log-level trace npm:zustand &> log` or `deno install --log-level trace npm:zustand &> log`.

Here is part of log file:
```plain
DEBUG RS - deno_config::deno_json:779 - Config file found at '/root/test/deno-npmrc-test/deno.json'
DEBUG RS - deno::args:930 - Finished config loading.
DEBUG RS - deno::file_fetcher:622 - FileFetcher::fetch_no_follow_with_options - specifier: https://registry.npmjs.org/zustand
DEBUG RS - deno::file_fetcher:354 - FileFetcher::fetch_remote_no_follow - specifier: https://registry.npmjs.org/zustand
TRACE RS - deno::file_fetcher:380 - [0m[32mDownload[0m https://registry.npmjs.org/zustand
TRACE RS - hyper_util::client::legacy::pool:671 - checkout waiting for idle connection: ("https", registry.npmjs.org)
TRACE RS - hyper_util::client::legacy::connect::http:370 - Http::connect; scheme=Some("https"), host=Some("registry.npmjs.org"), port=None
DEBUG RS - hyper_util::client::legacy::connect::dns:122 - resolving host="registry.npmjs.org"
DEBUG RS - hyper_util::client::legacy::connect::http:643 - connecting to 104.16.24.34:443
TRACE RS - mio::poll:551 - registering event source with poller: token=Token(94784856624128), interests=READABLE | WRITABLE
DEBUG RS - hyper_util::client::legacy::connect::http:646 - connected to 104.16.24.34:443
TRACE RS - hyper_util::client::legacy::client:542 - ALPN negotiated h2, updating pool
```

Deno use `https://registry.npmjs.org` instead of `https://registry.npmmirror.com`. But npm does right thing. I can provide more information if you need it.

**Comment by lucacasonato** [comment]
Where is the `.npmrc` file? In the project dir or in your home directory?

**Comment by familyboat** [comment]
It is in my project dir.

**Comment by bartlomieju** [comment]
@familyboat do you still experience the same problem on Deno 2.0.2? We had a fix for `.npmrc` support and I wonder if that fixes your problem.

**Comment by familyboat** [comment]
@bartlomieju I try the latest version of deno. The problem still exists. I create a repository in [here](https://github.com/familyboat/bug-deno-npmrc), which contains some log files. You can check it.
During the test process, I find another problem - deno can not correctly handle colored text in file, but can correctly handle colored text in terminal. npm can correctly handle colored text in file or in terminal.

**Comment by familyboat** [comment]
By the way, I have a suggestion. You can print deno version information in log just like npm does.

**Comment by familyboat** [comment]
By the way, I have a suggestion. You can print deno version information in log just like npm does.

**Comment by marvinhagemeister** [comment]
Looking at the logs it seems like the internet connection is a bit flaky. Npm always retries it a couple of times in the logs whereas Deno at that time didn't. We added automatic retrying in https://github.com/denoland/deno/pull/26278 . You can try out that fix by upgrading to a canary build with `deno upgrade canary`.

**Comment by familyboat** [comment]
@marvinhagemeister I dont think network is the point. Because deno respects NPM_CONFIG_REGISTRY without network. But I will try it again with canary version.

**Comment by familyboat** [comment]
Here is the latest [log file](https://github.com/familyboat/bug-deno-npmrc/blob/main/log.deno) with canary version.

**Comment by bartlomieju** [comment]
FYI you can upgrade to `canary` version to get this fix immediately (`deno upgrade canary`) or wait until stable Deno v2.0.3 that should be released tonight.
