### ISSUE TITLE
Error parsing env file

### ISSUE THREAD

**Issue by edgeadjei** [denoland/deno#26143]
Version: Deno 2.0.0

Observation:
Receiving the following error when parsing an env file. 
```console
Task start deno run --allow-env --env .env --allow-sys --allow-net src/main.ts
error: The module's source code could not be parsed: Identifier cannot follow number at file:///Users/kwameadjei/Projects/@urskill/apps/api/.env:2:17

  JWT_SECRET=67016f54-5678-800d-x567-ab2252b55102
                  ~
```

Added quotes around the value(`JWT_SECRET="67016f54-5678-800d-x567-ab2252b55102"`) for testing purposes and it fail on the next key value.

```console
Task start deno run --allow-env --env .env --allow-sys --allow-net src/main.ts
error: The module's source code could not be parsed: Expected ';', '}' or <eof> at file:///Users/xxx/xxx/xxx/apps/api/.env:3:20

  POCKETBASE_URL=http://127.0.0.1:8000
                     ~
```

Looks like this is working as expected if you don't specify a value for the `--env`  flag.
The default `.env` is read as expected. Getting around the issue by moving my dev end config to the `.env` file but i
d like to use my `.env.local` during development.

Failed execution commands:
`deno run --allow-env --env .env --allow-sys --allow-net src/main.ts`
`deno run --allow-env --env .env.local --allow-sys --allow-net src/main.ts`

.env file
```env
PORT=10010
JWT_SECRET=67016f54-5678-800d-x567-ab2252b55102
POCKETBASE_URL=http://127.0.0.1:8000
```

**Comment by nathanwhit** [comment]
Ah, what's happening here is that `--env` needs an `=` delimiter. So instead it should be

```
--env=.env
```

The error you're seeing is because the missing `=` causes the argument parsing to interpret `.env` as the file to run, so it tries to run it as JS. It's an unfortunate error message though, I think we could handle this more gracefully.

**Comment by edgeadjei** [comment]
Got it. Works as expected after the change.
Classic 3am user error 🫠 

Thank you for the quick reply and the amazing work!
