### ISSUE TITLE
npmrc: Registry config without auth comment fails

### ISSUE THREAD

**Issue by saibotk** [denoland/deno#26152]
Version: Deno 2.0.0

Currently, when running any deno command, it fails with this message:
```
DENO_LOG=debug deno task
DEBUG RS - deno_config::workspace::discovery:266 - package.json file found at '/Users/saibotk/git/test/package.json'
error: Failed to resolve .npmrc options

Caused by:
    failed resolving .npmrc config for scope 'demo'

```

The `.npmrc` that is causing the issue:
```
# Force registry to be npmjs.org
@demo:registry=https://registry.npmjs.org/
```

Quick usage rationale: When using a custom internal company registry for some projects, which is globally defined for a company scope, we sometimes need to reset it to use the npm registry, e.g. when projects are shared with clients that also need access and all used packages from that scope are also published publicly. This then prevents pnpm or npm from resolving them via the internal registry.

## The workaround

The issue here seems that deno expects a registry definition to be followed by the auth credential definition. Sadly the error message here only tells me that some error happened but not what it expected.

The following works
```
# Force registry to be npmjs.org
@demo:registry=https://registry.npmjs.org/
//registry.npmjs.org/:_auth=
```

Thanks for the amazing project!

**Comment by wesleylhandy** [comment]
The workaround does not work for global npm config that is not sourced by an .npmrc

**Comment by bartlomieju** [comment]
FYI you can upgrade to `canary` version to get this fix immediately (`deno upgrade canary`) or wait until stable Deno v2.0.3 that should be released tonight.
