### ISSUE TITLE
request -> req.body returning true with no body?

### ISSUE THREAD

**Issue by avalero** [denoland/deno#26158]
Version: Deno 2.0.0

With a simple `Request` this code fails when no `body` is received

```js
if(req.body) {
   const body= await req.json();
   if (body.name) return new Response(`Hola ${body.name}`);
}
```
The Request has been made using Postman with body:none option checked

The error is

```
SyntaxError: Unexpected end of JSON input
    at parse (<anonymous>)
    at packageData (ext:deno_fetch/22_body.js:402:14)
    at consumeBody (ext:deno_fetch/22_body.js:260:12)
    at eventLoopTick (ext:core/01_core.js:175:7)
    at async handler (file:///C:/Users/ProfesorPR/deno/api1/main.ts:13:25)
    at async ext:deno_http/00_serve.ts:369:18
```

**Comment by avalero** [comment]
Thanks. 

I expressed myself wrongly. 

I intended to say that according Deno documentation, if the request has no body, the `req.body` should be `false`. Instead the `if` condition runs, giving this the error when you try to get a JSON.

**Comment by bartlomieju** [comment]
@avalero could you please point me to the bit of documentation that mentions that? I'll fix it

**Comment by avalero** [comment]
Hello @bartlomieju , here it is: https://docs.deno.com/runtime/fundamentals/http_server/#inspecting-the-incoming-request

This is the example:

```js
Deno.serve(async (req) => {
  console.log("Method:", req.method);

  const url = new URL(req.url);
  console.log("Path:", url.pathname);
  console.log("Query parameters:", url.searchParams);

  console.log("Headers:", req.headers);

  if (req.body) {
    const body = await req.text();
    console.log("Body:", body);
  }

  return new Response("Hello, World!");
});
```

One question, if it cannot be done like that, how would you check if the body is empty?

**Comment by marvinhagemeister** [comment]
The documentation is correct. `req.body` is typed as `ReadableStream<Uint8Array> | null`. We could do an explicit `req.body !== null` there, but either way is valid JS.

**Comment by lucacasonato** [comment]
`req.body` is `null` only if the request is a GET or HEAD request. For any POST/PUT/PATCH/DELETE request, regardless of if the request has bytes in the body (or the body is zero sized), `req.body` is set to a `ReadableStream`. If the body is zero sized, then the `ReadableStream` will immediately return `done: true` on the first read.

This is as per the Fetch specification.
