### ISSUE TITLE
node-postgres bench query slow

### ISSUE THREAD

**Issue by zhang-wenchao** [denoland/deno#26177]
Version: Deno 2.0.0

https://github.com/brianc/node-postgres/issues/2225

After extensive discussions, a more important library, hoping to improve the priority to start investigating the cause.

**Comment by bartlomieju** [comment]
@zhang-wenchao just to clarify - how many rows does your `Users` table contain and I assume you are using a remote database and not one on `localhost`, is that correct?

**Comment by zhang-wenchao** [comment]
I did encounter this problem. Whether it is local or remote, Deno has a magnitude of performance gaps than Node and Bun.

**Comment by bartlomieju** [comment]
FYI I can see difference on localhost with a table with 1 row. Just trying to get more info to get the same results as you to dig more.

**Comment by kamikazechaser** [comment]
I was able to reporoduce @morpig 's simple e2e benchmark with an updated query that doesn't rely on a seeded db. Environment is Linux.

![image](https://github.com/user-attachments/assets/b2d5f1ba-751d-4254-9d93-a9e05d606c24)

```js
import { Buffer } from "node:buffer";

import pg from 'pg'
const { Client } = pg
const client = new Client({
    connectionString: 'postgresql://postgres:postgres@127.0.0.1:5432/postgres'
})
await client.connect()

async function fetch() {
    const startPerf = performance.now();
    const res = await client.query(`select
        $1::int as int,
        $2 as string,
        $3::timestamp with time zone as timestamp,
        $4 as null,
        $5::bool as boolean,
        $6::bytea as bytea,
        $7::jsonb as json
      `, [
        1337,
        'wat',
        new Date().toISOString(),
        null,
        false,
        Buffer.from('awesome'),
        JSON.stringify([{ some: 'json' }, { array: 'object' }])
    ])
    console.log(`${new Date()}: ${Math.round(performance.now() - startPerf)}ms`)
}

setInterval(() => {
    fetch()
}, 1000)

```

**Comment by bartlomieju** [comment]
Thanks for a hint @kamikazechaser, but for me all three runtimes take 2ms to execute the query.

@zhang-wenchao did you have a chance to do the benchmark?

**Comment by kamikazechaser** [comment]
@bartlomieju I did around 10 runs, all consistent with the timings above. What OS/environment are you on?

**Comment by bartlomieju** [comment]
I'm on macOS. @littledivy says that they can reproduce on linux.
