### ISSUE TITLE
Cannot import styleText function from 'node:util'

### ISSUE THREAD

**Issue by fvsch** [denoland/deno#26184]
Version: Deno 2.0.0
Platform: macOS (verified with deno installed via Homebrew _and_ via the install script)

```js
import { styleText } from "node:util";
console.log(typeof styleText); // "undefined"
```

I expected the `styleText` function to be exported and to work, because:

- It's in the docs: https://docs.deno.com/api/node/util/~/styleText
- It was added in a PR 6 months ago: https://github.com/denoland/deno/pull/22758
- I can find it in the codebase: https://github.com/denoland/deno/blob/9117a9a43cba86d3112f86b10c5ea77baa2c6007/ext/node/polyfills/internal/util/inspect.mjs#L566-L573

And yet, when importing it, or importing the default export from `node:util`, it's not there.

Anyone knows what's happening?

**Comment by fvsch** [comment]
@crowlKats sorry to ping you, but since this is something you worked on, maybe you'll have an idea?

**Comment by nathanwhit** [comment]
It's missing an export, I'll fix in a second.
