### ISSUE TITLE
Module Import and Type Inference Issues with Deno in Convex + Svelte 5 Project

### ISSUE THREAD

**Issue by jakubdonovan** [denoland/deno#26204]
Version: Deno 2.0

I am encountering two issues while setting up a Svelte 5 project with Convex and Deno:
1.	Module import errors, prompting me to add a .js extension to the generated Convex files.
2.	Type inference issues, where types are not being inferred correctly even after resolving the .js extension error.

**Steps to Reproduce:**
1.	Create a new Svelte project using Deno with the following commands:
`deno run -A npm:create-svelte testApp`
 _Chose skeleton project, TypeScript syntax, and Svelte 5 preview_
`cd testApp`
`deno install --allow-scripts`
`deno install npm:convex npm:convex-svelte`

2.	Add convex.json according to the [Quickstart Guide](https://docs.convex.dev/quickstart/svelte):
```json
{
  "functions": "src/convex/"
}
```

3.	Run Convex:
`deno run npm:convex`

4.	I copied over my schema and relevant files from a working Svelte app that was running on Bun (file structure of src/convex/ is shown below).
```
├── _generated
│   ├── api.d.ts
│   ├── api.js
│   ├── dataModel.d.ts
│   ├── server.d.ts
│   └── server.js
├── addCompleteProperty.ts
├── addPropertyAssets.ts
├── bookings.ts
├── getProperties.ts
├── helpers.ts
└── schema.ts
```

**Expected Behavior:**
•	The Convex generated modules should load without requiring me to manually add the .js extension.
•	Types should be inferred properly as they are when using Bun.

**Actual Behavior:**

1.	Module Import Error: I get the following error when importing from _generated/server:

> Unable to load a local module: file:///Users/jakubdonovan/Documents/code/phuketkeyDeno/src/convex/_generated/server
> Maybe add a '.js' extension. [no-local]

When I add the .js extension to the import, the error goes away, but…
2.	Type Inference Issues: Despite resolving the import issue, type inference is broken, and types are being inferred as any. Here’s an example error:
> Parameter 'property' implicitly has an 'any' type. [7006]
![type](https://github.com/user-attachments/assets/85a4c4e1-886c-46da-a3a2-670166e42d1c)
![Screenshot 2024-10-13 at 14 27 42](https://github.com/user-attachments/assets/bd1dd740-9062-48aa-9afe-78ebea8699e9)

The same setup works perfectly in the Svelte app running on Bun.
![bun](https://github.com/user-attachments/assets/b2f9939d-160e-4ebd-a43c-deb0ab6bd9d5)

**LSP Configuration:**
I’ve confirmed that the issue isn’t specific to my Neovim setup. Here is the relevant extract from my lspconfig.lua configuration for denols:
```lua
denols = {
    root_dir = lspconfig.util.root_pattern("deno.json", "deno.jsonc"),
    single_file_support = false,
    flags = {
      debounce_text_changes = 150,
    },
    filetypes = {
      "javascript",
      "javascript.jsx",
      "javascriptreact",
      "typescript",
      "typescript.tsx",
      "typescriptreact",
      "markdown",
    },
    -- init_options = {
      -- config = "./deno.jsonc",
      -- format = true,
      -- lint = true,
    -- },
    settings = {
      javascript = {
        inlayHints = {
          parameterNames = { enabled = "all" },
          parameterTypes = { enabled = false },
          variableTypes = { enabled = true },
          propertyDeclarationTypes = { enabled = true },
          functionLikeReturnTypes = { enabled = false },
          enumMemberValues = { enabled = true },
        },
      },
      typescript = {
        inlayHints = {
          parameterNames = { enabled = "all" },
          parameterTypes = { enabled = false },
          variableTypes = { enabled = true },
          propertyDeclarationTypes = { enabled = true },
          functionLikeReturnTypes = { enabled = false },
          enumMemberValues = { enabled = true },
        },
      },
      deno = {
        enable = true,
        -- suggest = {
        --   imports = {
        --     hosts = {
        --       ["https://deno.land"] = true,
        --     },
        --   },
        -- },
      },
    },
  },
```
I also tested in Visual Studio Code, and the same issues persist. Therefore, the problem is not related to my editor setup.

**Comment by nayeemrmn** [comment]
Discussed on Discord, it's fixed by `{ "unstable": ["sloppy-imports"] }`. There were other strange issues specific to `denols` with vim that came up, let's discuss those in separate issues. Closing.

**Comment by jakubdonovan** [comment]
> Discussed on Discord, it's fixed by `{ "unstable": ["sloppy-imports"] }`. There were other strange issues specific to `denols` with vim that came up, let's discuss those in separate issues. Closing.

#26223
