### ISSUE TITLE
fmt option to allow consecutive blank lines

### ISSUE THREAD

**Issue by csvn** [denoland/deno#26208]
I know this issue may be closed, since Deno seems to have a similar opinionated philosophy as Prettier, but I'll give it a try since I could not find any docs discouraging feature requests for the formatter.

We have large amounts of code that often uses more than 1 blank line for separating content. Adding two instead of one blank line helps group content together visually (like having paragraphs in a book). They are not everywhere, but to our team they help improve readability of the code.

It would be awesome if there was a config option to allow multiple blank lines:

```jsonc
// deno.jsonc
{
  "fmt": {
    "maxConsecutiveLinebreaks": 2
  }
}
```

I agree with having great defaults for code formatting, but less flexibility also blocks adoption. This would be one of bigger blockers for formatting our code currently.

**Comment by dsherret** [comment]
I think this is too specific of a request to be in `deno fmt`.

> We have large amounts of code that often uses more than 1 blank line for separating content. Adding two instead of one blank line helps group content together visually (like having paragraphs in a book). They are not everywhere, but to our team they help improve readability of the code.

It might be better to use a comment or split up the code into smaller functions.

**Comment by csvn** [comment]
It doesn't always make sense to e.g. split Angular components into smaller parts. Having more than one blank line is sometimes very helpful to group interfaces together visually. So far for Deno code, it's not a big issue, even if we prefer to have 2 lines separating imports from code in modules.

If it's not a feature you want to support in `deno fmt`, I understand. [Oxc](https://github.com/oxc-project/oxc) seems to intend to create a more flexible formatter, but it's not ready yet. All formatters we've tried so far are too opinionated, so we've stuck with ESLint + style rules.

**Comment by lucacasonato** [comment]
We're not going to do this. `deno fmt` is opinionated - `prettier` also doesn't have this option.

**Comment by csvn** [comment]
Thanks for the consideration anyway. I'll put my hopes on [Oxc for formatting](https://oxc.rs/) our Angular codebase in the future. 🙂
