### ISSUE TITLE
core: add example of hyper web server handling requests in JS

### ISSUE THREAD

**Issue by ry** [denoland/deno#2622]
Currently we have [an example web server](https://github.com/denoland/deno/blob/72d9045528ad69ec32d7de9707cea65fab9f405e/core/examples/http_bench.rs) which we use for debugging performance in [the low-level deno core crate](https://crates.io/crates/deno). This web server accepts connections in Deno.

It would be useful / interesting to have a similar web server example which used the hyper web server to accept connections but handled the processing of them in Deno.

**Comment by ynwd** [comment]
Interesting.  @ry @lucacasonato  @bartlomieju
