### ISSUE TITLE
Deno LSP fails without a deno.json

### ISSUE THREAD

**Issue by leighmcculloch** [denoland/deno#26253]
Version: Deno 2.0.0

When a valid deno TypeScript file is loaded into an IDE, such as VSCode, without a deno.json file in the directory, the LSP fails to load dependencies.

For example, see below where this ts file is loaded and errors. Note on the right that there is only one file, the `main.ts`.

<img width="1220" alt="Screenshot 2024-10-15 at 8 54 17 AM" src="https://github.com/user-attachments/assets/338d7205-5df8-4ab1-a7d8-270637967fd1">

Even though the LSP complains of errors, deno can run the script just fine:
```
$ deno main.ts
9f4575e2831f674adf77bd1310d1b53385870a38eee224810043fdd3af1bf27f
```

When I add a `deno.json` file with only the contents `{}`, the LSP errors disappear:

<img width="1220" alt="Screenshot 2024-10-15 at 8 55 24 AM" src="https://github.com/user-attachments/assets/008bd32c-f684-4f9d-b75d-f1e290fdf723">

The ts file in the above two examples is the same:

```typescript
import { Networks, TransactionBuilder } from "npm:@stellar/stellar-sdk@12.3.0";
import { encodeHex } from "jsr:@std/encoding@1.0.5";

const tx = TransactionBuilder.fromXDR(
  "AAAAAgAAAAAGyCRPMMdlS/lg9LprBSuDdvX+LKKEUc5ad1/9G6ecCgAAAGQABr1QAAAAAQAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAACwAAAAAAAAAAAAAAAAAAAAA=",
  Networks.TESTNET,
);

console.log(encodeHex(tx.hash()));
```

The deno.json file added in the second screenshot is:
```json
{}
```

It appears that the deno LSP doesn't get any data from the deno.json, because even in the example where it is present it's empty of any meaningful data. It would be awesome if the LSP could work with .ts files as they are, because I find the fact that deno works for .ts alone is super powerful for scripting. It's inconvenient to open the scripts in an IDE and get errors and no auto-complete.

**Comment by bartlomieju** [comment]
You can do that, by going to `Command Pallete` and selecting `Deno: Enable`. This will add an entry to `.vscode/settings.json` to enable Deno LSP in a particular workspace. Deno automatically enables its LSP only if `deno.json` is present to not break existing workflows and projects using Node.js - that's because Deno LSP and built-in TSServer don't play nice (for now).

**Comment by leighmcculloch** [comment]
Oh! Thanks! TIL. I'm adding it to my IDE-wide settings, because deno 💪🏻.

**Comment by bartlomieju** [comment]
> I'm adding it to my IDE-wide settings, because deno 💪🏻.

Great, but keep in mind that it might cause clashes in other projects that used Node.js until now. I'd still recommend going with `.vscode/settings.json` or `deno.json` in each project, for the time being; to avoid confusing problems in legacy projects
