### ISSUE TITLE
deno check does not enforce noImplicitReturns

### ISSUE THREAD

**Issue by tainn** [denoland/deno#26265]
```
deno 2.0.0 (stable, release, x86_64-unknown-linux-gnu)
v8 12.9.202.13-rusty
typescript 5.6.2
```

`deno check` seemigly does not enforce the `noImplicitReturns` clause.

Having the following `deno.json` snippet:

```json
{
  "compilerOptions": {
    "strict": true,
    "noImplicitReturns": true
  }
}
```

And the following TS code snippet of the Hono handler:

```ts
const rootHandler = (ctx: Context) => {
  return ctx.json({ shade: "?", random: randomInt(0, 256) });
};
```

I would expect `deno check` to fail due to there being no `Response` return type specified in the function signature, but it does not fail.

**Comment by dsherret** [comment]
> I would expect deno check to fail due to there being no Response return type specified in the function signature, but it does not fail.

`noImplicitReturns` doesn't do that, it instead ensures that all code paths in a function return a value. See https://www.typescriptlang.org/tsconfig/#noImplicitReturns

**Comment by tainn** [comment]
Thank you for the explanation, @dsherret. So, is there any way I can enforce return types in function signatures using Deno?

**Comment by voltflake** [comment]
> Thank you for the explanation, @dsherret. So, is there any way I can enforce return types in function signatures using Deno?

As I know there's no such option in Deno for now. You can use Biome.js rule if you need this functionality right now in your project.
https://biomejs.dev/linter/rules/use-explicit-type/

**Comment by bartlomieju** [comment]
Or you could use a built-in rule in `deno lint`: https://lint.deno.land/rules/explicit-function-return-type
