### ISSUE TITLE
Issue with node:crypto.timingSafeEqual() in Deno

### ISSUE THREAD

**Issue by chrisveness** [denoland/deno#26276]
I am trying to use [npm:scrypt-kdf](https://www.npmjs.com/package/scrypt-kdf) in Deno, but it is failing.

This works in Node.js REPL:

````
$ npm install scrypt-kdf
$ node
Welcome to Node.js v22.8.0.
> const { Buffer } = await import('node:buffer');
> const { default: Scrypt } = await import('scrypt-kdf');
> const password = 'abcd';
> const key = (await Scrypt.kdf(password, { logN: 12 })).toString('base64');
> await Scrypt.verify(Buffer.from(key, 'base64'), password);
true
````

But the same fails in Deno REPL:

````
$ deno
Deno 2.0.0
> import { Buffer } from 'node:buffer';
> import Scrypt from 'npm:scrypt-kdf';
> const password = 'abcd';
> const key = (await Scrypt.kdf(password, { logN: 12 })).toString('base64');
> await Scrypt.verify(Buffer.from(key, 'base64'), password);
false
````

The problem lies with `crypto.timingSafeEqual()` ([scrypt.js#L152](https://github.com/chrisveness/scrypt-kdf/blob/335b5da29a77f4004a2d5cb1fa137bdf842d82ca/scrypt.js#L152)), which is returning false, despite the two arrays supplied as arguments being apparently identical.

The only difference I've been able to detect is that the `key.byteOffset` ([scrypt.js#L131](https://github.com/chrisveness/scrypt-kdf/blob/335b5da29a77f4004a2d5cb1fa137bdf842d82ca/scrypt.js#L131)) is different when running in Node.js or in Deno, but I cannot see why that would cause `timingSafeEqual()` to return false.

It would appear there is some incompatibility somewhere when using Node.js `Buffer` in Deno that is confusing `timingSafeEqual()`.

**Comment by chrisveness** [comment]
TypedArrays and their buffers are strange beasts.

It may or may not be a concern that Node.js and Deno produce different results from `crypto.timingSafeEqual()` with identical code (I imagine that the underlying buffer must be behaving differently in Node.js and Deno), but I have managed to sidestep the issue by adding extra `Array.slice()` calls before passing arrays to `crypto.timingSafeEqual()`.

**Comment by littledivy** [comment]
This is actually a bug in Deno. `timingSafeEqual` should take into account the byteOffset of the underlying array buffer.
