### ISSUE TITLE
Error.prepareStackTrace wrong stack line number

### ISSUE THREAD

**Issue by ayZagen** [denoland/deno#26273]
Version: Deno 2.0.0

Stacktrace contains invalid lineNumber (retrieved by `getLineNumber()`) while trying to use `Error.prepareStackTrace`

Reproduction:
https://dash.deno.com/playground/flat-pike-91

**Comment by lowlighter** [comment]
I think it's duplicate of #25794

I remember reading somewhere this was because the line/col were actually printing the ones of the transpiled js code rather than the ts code

**Comment by magurotuna** [comment]
@ayZagen thanks for reporting. Just to clarify, is it happening only on Deno Deploy? Or on CLI too?

**Comment by ayZagen** [comment]
@lowlighter yes, that is exactly the same issue, sorry I checked existing issues and saw some of them fixed, that one slipped from my eye. Closing in favor of #25794

@magurotuna it happens on cli too, Deno Deploy link was just for the reproduction. You can copy paste that code and run it locally to see the same result.
