### ISSUE TITLE
deno watch not working in Docker

### ISSUE THREAD

**Issue by und-miller** [denoland/deno#26279]
Version: Deno denoland/deno:2.0.0

Running a docker image with the `--watch` flag does not reload the server. 

This can be reproduced with the following:

dockerfile
```dockerfile
FROM denoland/deno:2.0.0

WORKDIR /app

USER deno

COPY . .
RUN deno cache main.ts

CMD ["run", "--allow-net", "--watch", "main.ts"]
```

main.ts
```typescript
Deno.serve(async (req) => {
    console.log("Method:", req.method);
  
    const url = new URL(req.url);
    console.log("Path:", url.pathname);
    console.log("Query parameters:", url.searchParams);
  
    console.log("Headers:", req.headers);
  
    if (req.body) {
      const body = await req.text();
      console.log("Body:", body);
    }
  
    return new Response("Hello, World!");
  });
```
Then execute with the following commands:

1. Build ` docker build -t app .`
2. run `docker run -it --init -p 8000:8000 -v ${PWD}:/app app` (where PWD would be your absolute path)

Finally make modifications to the `main.ts` file and notice how the server does not reload.

**Comment by brrock** [comment]
Watch is just not working
Homebrew on Arch btw

**Comment by lucacasonato** [comment]
Duplicate of #14244
