### ISSUE TITLE
`deno install <pkg>` doesn't update lockfile when only using package.json

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#26270]
Running `deno install <pkg>` doesn't update the lockfile. A separate `deno install` is necessary.

Version: Deno 2.0.0

Reproductions:

```
% touch package.json
% deno install npm:@react-router/dev@^7.0.0-pre.1
Add npm:@react-router/dev@7.0.0-pre.1
```

**Comment by madd86** [comment]
Have you done `deno add <package>`?
