### ISSUE TITLE
Deno check says i cant use "fmt" key in package.json

### ISSUE THREAD

**Issue by saint-james-fr** [denoland/deno#26281]
This command
```bash
deno check --unstable-sloppy-imports --import-map ./deno.json ./**/*.ts
```

returns this warning

```bash
@asap/supabase:check:ts:   - Invalid top-level key "fmt". Only "imports" and "scopes" can be present.
```

which is not coherent with [documentation](https://docs.deno.com/runtime/fundamentals/configuration/)

Deno version

```bash
deno --version
deno 1.46.3 (stable, release, aarch64-apple-darwin)
v8 12.9.202.5-rusty
typescript 5.5.2
```

**Comment by bartlomieju** [comment]
This is correct - you are using `--import-map` flag which makes the file passed to it be treated as an https://github.com/WICG/import-maps. Import maps only have two keys. You can get rid of this problem by passing `--config ./deno.json` (or omitting it altogether) which allows to have additional keys.
