### ISSUE TITLE
`deno add -D npm:daisyui@5.0.0-alpha.10` always installs the latest alpha version

### ISSUE THREAD

**Issue by kuchta** [denoland/deno#26299]
Version: Deno 2.0.0

`deno add` seems to always install the latest version even though it add correct version to `package.json`

**Comment by marvinhagemeister** [comment]
Steps to reproduce

1. Add an empty `package.json`:
  ```json
  {}
  ```
2. Run `deno add -D npm:daisyui@5.0.0-alpha.10`

Output:

```json
{
  "devDependencies": {
    "daisyui": "^5.0.0-alpha.10"
  }
}
```

Expected Output:

```diff
  {
    "devDependencies": {
-      "daisyui": "^5.0.0-alpha.10"
+      "daisyui": "5.0.0-alpha.10"
    }
  }
```

**Comment by kuchta** [comment]
Yes, the version in package.json will be correct, but the version of the actual package in node_modules folder will be wrong. Another issue is that `deno remove daisyui` doesn't remove the package from node_modules.

**Comment by marvinhagemeister** [comment]
The install bug is here: https://github.com/denoland/deno/blob/ea9c3ffaa240fc968832871000832eda1b92934a/cli/tools/registry/pm.rs#L640-L644

We ignore the fact that the command specified an exact version there.
