### ISSUE TITLE
deno commands should accept local package names without specifiers

### ISSUE THREAD

**Issue by kuchta** [denoland/deno#26303]
It would be more ergonomical and consistent with imports and the overall JS ecosystem if deno commands (`run`, `remove`, `info`..., except obviously non-applicable ones like `deno add`) accept package names without specifiers if those packages are stated in `deno.json/imports` (those resolved to `npm:` or `jsr:`) or `package.json/dependencies`.

**Comment by lucacasonato** [comment]
Duplicate of #19955
