### ISSUE TITLE
memory allocation of 17179869184 bytes failed

### ISSUE THREAD

**Issue by alexgleason** [denoland/deno#26315]
Version: Deno 2.0.0

Hi, I am running a big complicated Deno server. Yesterday the server crashed with this message:

```
Oct 15 15:30:58 ditto deno[560237]: memory allocation of 17179869184 bytes failed
Oct 15 15:30:59 ditto systemd[1]: ditto.service: Main process exited, code=exited, status=1/FAILURE
Oct 15 15:30:59 ditto systemd[1]: ditto.service: Failed with result 'exit-code'.
Oct 15 15:30:59 ditto systemd[1]: ditto.service: Consumed 2h 49min 44.858s CPU time.
Oct 15 15:30:59 ditto systemd[1]: ditto.service: Scheduled restart job, restart counter is at 1.
Oct 15 15:30:59 ditto systemd[1]: Stopped Ditto.
```

There is no traceback, but there are a few more [application logs](https://gitlab.com/soapbox-pub/ditto/-/issues/252). I also snapshotted a [Grafana dashboard](https://grafana.soapbox.pub/dashboard/snapshot/V2R9WdbU4HCLIqW1eaRbdCduWKElmihZ) a few seconds around the incident. 

I spent all morning yesterday digging into it. I can tell you all about the Nigerian man who was scrolling through another user's followers and following every single one, or the man in the Czech Republic whose malfunctioning browser extension was causing him to fetch nonsensical paths on my server. **In the end I still have no clue why this happened. It was probably a bug in my software and not in Deno**, but I wanted to report it to the issue tracker for posterity. It's not happening frequently from what I can tell.

What strikes me as especially odd is the 17179869184 number. First of all, that's an extraordinarily large 16GiB(!!!) number. And it's not just "approximately" 16 gigs, it's _exactly_ 16GiB. This is a very intentional number.

The machine only has 8 gigs of RAM. But where could this allocation be coming from? A network request, a file? What is 16GiB? Something is.

**Comment by lucacasonato** [comment]
Do you expose any endpoints that users can make `POST` requests to?

**Comment by alexgleason** [comment]
People can POST, send WebSocket data, and much more. But this problem only ever occurred once and then I never saw it again. So I'll close this unless I can provide more info. Thanks!
