### ISSUE TITLE
Undefined Symbol node_module_register with node-canvas

### ISSUE THREAD

**Issue by astralstriker** [denoland/deno#26347]
### What version of Deno is running?

2.0.0
### What platform is your computer?
x86_64-unknown-linux-gnu

### What steps can reproduce the bug?
install canvas using `deno install --allow-scripts npm:canvas`
Put  `import { createCanvas, loadImage } from 'canvas'` into any file 
Run `deno run --allow-all main.ts`

### What is the expected behavior?

Deno should run without an error.
### What do you see instead?

> deno: symbol lookup error: /home/jai/Projects/surety-seven-worker/node_modules/.deno/canvas@2.11.2/node_modules/canvas/build/Release/canvas.node: undefined symbol: node_module_register

**Comment by astralstriker** [comment]
Thanks for the update, I will ask there.

**Comment by lucacasonato** [comment]
Closing as this is an upstream issue.
