### ISSUE TITLE
Invalid top-level key "fmt". Only "imports" and "scopes" can be present.

### ISSUE THREAD

**Issue by saint-james-fr** [denoland/deno#26345]
Following Deno documentation, I added format rules on deno.json but running deno checks raises this error.
`Invalid top-level key "fmt". Only "imports" and "scopes" can be present.`

```bash
deno 2.0.0 (stable, release, aarch64-apple-darwin)
v8 12.9.202.13-rusty
typescript 5.6.2
```

Either the documentation or the checks should be consistent.

**Comment by marvinhagemeister** [comment]
I'm not able to reproduce the error. This `deno.json` gives me no errors:

```json
{
  "fmt": {
    "exclude": [],
    "include": []
  }
}
```

Can you share the steps to reproduce the error?

**Comment by bartlomieju** [comment]
What is the exact CLI invocation that you are using?

**Comment by saint-james-fr** [comment]
Hey,
the command I run is  ` deno check --unstable-sloppy-imports --import-map ./deno.json ./**/*.ts`
and I receive 
```plain
Import map diagnostics:
  - Invalid top-level key "fmt". Only "imports" and "scopes" can be present.
```

**Comment by marvinhagemeister** [comment]
Right, the `--import-map` flag should point to an import map, not the `deno.json` config. In general it's preferred to store the import map in `deno.json` instead of externalizing it.
