### ISSUE TITLE
Path-only redirects should work

### ISSUE THREAD

**Issue by pcarrier** [denoland/deno#26354]
```
> deno --allow-net eval 'const s=await Deno.serve(()=>Response.redirect("/demo")); await fetch(`http://${s.addr.hostname}:${s.addr.port}`); Deno.exit(0)'
Listening on http://0.0.0.0:8000/
TypeError: Invalid URL: '/demo'
    at getSerialization (ext:deno_url/00_url.js:98:11)
    at new URL (ext:deno_url/00_url.js:405:27)
    at Function.redirect (ext:deno_fetch/23_response.js:264:23)
    at file:///Users/pcarrier/src/mailin/$deno$eval:1:39
    at ext:deno_http/00_serve.ts:369:24
    at ext:deno_http/00_serve.ts:569:29
    at eventLoopTick (ext:core/01_core.js:175:7)
```

Should be fine as per https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Location :
> A relative (to the request URL) or absolute URL.

**Comment by marvinhagemeister** [comment]
This gets a bit tricky with runtimes on the server. A page in the browser has a very clear mapping to a specific location. On the server that doesn't really exist as one running Deno instance can listen on multiple addresses at the same time.

**Comment by lucacasonato** [comment]
In browsers it is relative to the current page (`window.location`). `Response.redirect` always produces an HTTP response with an absolute path in the `Location` header, as per the Fetch spec.

You can make relative paths work, but only when passing the `--location` flag to `deno run` - this then determines the URL the redirect should be relative to.

**Comment by pcarrier** [comment]
I don't understand why this is completed. The example I provide can simply return a redirect with a `Location: /demo` header, but deno 2.0.3 doesn't do that, right?
