### ISSUE TITLE
Reduce / clean up  ErrorKinds

### ISSUE THREAD

**Issue by ry** [denoland/deno#2635]
https://github.com/denoland/deno/blob/963d56fc5e5a410108dcdff083d64c0a762658c0/cli/msg.fbs#L87-L146

Before releasing v1.0 we should clean up this struct as much as possible.

for comparison here are the linux errnos http://man7.org/linux/man-pages/man3/errno.3.html

**Comment by bartlomieju** [comment]
@ry do we consider this issue resolved now that #3662, #3936 and #4058 landed?

**Comment by bartlomieju** [comment]
Number of `ErrorKind`s had been reduced significantly (https://github.com/denoland/deno/blob/a29343c7d6b5dad26c5d501eb6d21e9caf382a58/cli/op_error.rs#L33-L60)
