### ISSUE TITLE
JSError: error: Uncaught ReferenceError: self is not defined inside web worker

### ISSUE THREAD

**Issue by GrosSacASac** [denoland/deno#2639]
[example-deno/file_usage.js](https://github.com/GrosSacASac/worka/blob/master/example-deno/file_usage.js)
[example-deno/sort_worka.js](https://github.com/GrosSacASac/worka/blob/master/example-deno/sort_worka.js)

**Comment by nayeem-rahman** [comment]
Duplicate of #650. Not quite what it was originally about but this is being tracked there.

**Comment by nayeemrmn** [comment]
@GrosSacASac Can you close this?
