### ISSUE TITLE
Running `deno fmt --ext html` without a filename reformats every file

### ISSUE THREAD

**Issue by TristanCacqueray** [denoland/deno#26402]
Version: Deno 2.0.0

That's a surprising behavior, for example, running this command in your home directory will corrupt your `~/.config/git/config`. Here is a reproducer:

```ShellSession
mkdir -p .config/git
echo -e "[user]\n name = $USER" > .config/git/config
deno fmt --ext html
```

The config file now looks like `[user] name = ...` which is not valid.

**Comment by bartlomieju** [comment]
The `--ext` flag tells Deno which media type to use for files it discovers. In most cases you don't want to use it at all - Deno will automatically discover what media type the file is based on the file extension. This flag is really only useful if you want to format a file from stdin (`deno fmt --ext html -`)

**Comment by TristanCacqueray** [comment]
I was trying to format from stdin but I forgot to add the `-`. This mistake broke my system and I had to restore a backup.

**Comment by lucacasonato** [comment]
@bartlomieju I feel like the bug here is that `--ext` should not change the glob to `**/*`?

**Comment by yun520-1** [comment]
Re-opening this conceptual thread: `deno fmt --ext html` without a filename is a destructive global operation. The fact that it can rewrite `~/.config/git/config` without confirmation is a UX hazard, not a "user should know better" issue.

Two fixes worth keeping in the tracker:
1. Require either a filename or `--stdin` when `--ext` is used without a path; reject bare `deno fmt --ext <ext>` with exit code 2 and a clear message.
2. Add a `--dry-run` flag that prints the files that *would* be rewritten before touching them.

HeartFlow comment: this is a **scope-creep** bug — the tool's action scope silently expands from "format what I point at" to "format everything reachable from cwd". Formatters, linters, and migration tools should all default to file-scoped action unless explicitly given directory scope.
