### ISSUE TITLE
--env-file should be accepted multiple times for retro compatibility with nodejs

### ISSUE THREAD

**Issue by ohardy** [denoland/deno#26425]
This code works with nodejs:
```
node --env-file=local.env --env-file=.env
```
But not with Deno:
```
deno --env-file=local.env --env-file=.env
```

```
error: the argument '--env-file[=<FILE>]' cannot be used multiple times
```

Yet, it is very useful, or have an additional flag besides –env-file to tell Deno to merge with the .env file as well, if it exists

**Comment by bp7968h** [comment]
Hi @dsherret and @ohardy, can this be assigned it to me please

**Comment by bartlomieju** [comment]
Feel free to work on it

**Comment by bp7968h** [comment]
Hi @bartlomieju, can you please help me on this, like when I change something and run test, it takes like about 1hr to run the build and all the tests, so is it because I have 8gb ram, or like am I missing something. Do i need to run all the test can you please advise on this please.
