### ISSUE TITLE
Different URL parsing between Deno and browser

### ISSUE THREAD

**Issue by alexgleason** [denoland/deno#26440]
Version: Deno 2.0.2

This one surprised me.

Deno:

```ts
> new URL('bunker://79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798?relay=wss%3A%2F%2Fgleasonator.dev%2Frelay&secret=iMTgnrTdiKlF')
URL {
  href: "bunker://79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798?relay=wss%3A%2F%2Fgleasonator.dev%2Frelay&secret=iMTgnrTdiKlF",
  origin: "null",
  protocol: "bunker:",
  username: "",
  password: "",
  host: "79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798",
  hostname: "79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798",
  port: "",
  pathname: "",
  hash: "",
  search: "?relay=wss%3A%2F%2Fgleasonator.dev%2Frelay&secret=iMTgnrTdiKlF"
}
```

Brave / Chromium:

![image](https://github.com/user-attachments/assets/abfa21fe-8c51-42e2-b491-2423fed45fb0)

(`host`, `hostname`, and `pathname` are different)

FireFox:

![image](https://github.com/user-attachments/assets/81850d04-d61c-48c8-b7b4-dca04d97b803)

(same result as Chromium)

P.S. Don't worry about the secret URI, this is just for testing.

Deno's way makes more sense to me, but it creates incompatibilities with browser environments. :facepalm:

**Comment by petamoriken** [comment]
`URL` implementation in the stable releases of Chrome and Firefox does not yet appear to be sufficient. Their canary releases would probably return the same results as Deno.

FYI: https://wpt.fyi/results/url?label=master&label=stable&product=chrome&product=firefox&product=safari&product=deno&aligned&q=url-constructor

**Comment by alexgleason** [comment]
That's brutal. So there's no actual bug? The bug is on the Chromium/FireFox side? But changing it would break a lot of stuff wouldn't it? But they're going to do it?

**Comment by lucacasonato** [comment]
Yes the bug is in Chromium & Firefox. Safari is correct. The correct implementation (how the spec expects this to be parsed) can be found here: https://jsdom.github.io/whatwg-url/#url=YnVua2VyOi8vNzliZTY2N2VmOWRjYmJhYzU1YTA2Mjk1Y2U4NzBiMDcwMjliZmNkYjJkY2UyOGQ5NTlmMjgxNWIxNmY4MTc5OD9yZWxheT13c3MlM0ElMkYlMkZnbGVhc29uYXRvci5kZXYlMkZyZWxheSZzZWNyZXQ9aU1UZ25yVGRpS2xG&base=YWJvdXQ6Ymxhbms=
