### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by harrysolovay** [denoland/deno#2648]
Can there be some kind of escape character/word that gives access to the code being interpreted, during its own runtime? To be honest, I'm not sure what the use would be... other than being cool.

```ts
escape(node => {
  node.parent.statements[1].expression.arguments[0].text = 'Hi there.'
})
console.log('Hi.')
```

... would execute as if is was...

```ts
console.log('Hi there.')
```

**Comment by bartlomieju** [comment]
Closing as stale, potentially related: #3354
