### ISSUE TITLE
deno cli: --no-fetch broken/missing

### ISSUE THREAD

**Issue by teleclimber** [denoland/deno#2650]
I wanted to test out the `--no-fetch` flag however it doesn't seem to work.

```
$ deno --no-fetch test.js
error: Found argument '--no-fetch' which wasn't expected, or isn't valid in this context

USAGE:
    deno [FLAGS] [OPTIONS] [SUBCOMMAND]
```

test.js is a copy paste from the getting started docs:

```
import { serve } from "https://deno.land/std@v0.11/http/server.ts";

async function main() {
  const body = new TextEncoder().encode("Hello World\n");
  for await (const req of serve(":8000")) {
    req.respond({ body });
  }
}

main();
```

`$ deno test.js` works fine.

Furthermore there is no mention of `--no-fetch` in the CLI help, even though it was added in [0.4.0](https://github.com/denoland/deno/releases/tag/v0.4.0) and I do not see if/where it was removed.

Deno 0.12.0 on Mac via Homebrew.

Thank you!

**Comment by ry** [comment]
Yikes - that does appear to be a regression. Thanks for the report!

**Comment by kevinkassimo** [comment]
I reported this days ago in the Gitter chatroom. I believe we kind of forget to expose the flag

**Comment by ry** [comment]
It was working at some point... Apparently it was never in the integration tests tho.

**Comment by bartlomieju** [comment]
[self-assign]
