### ISSUE TITLE
failed to import .cjs module

### ISSUE THREAD

**Issue by NyaightHazard** [denoland/deno#26503]
Version: Deno 2.0.2

When try to import [i18next_fs_backend](https://deno.land/x/i18next_fs_backend@v2.3.2) like this:
```ts
import Backend from "https://deno.land/x/i18next_fs_backend@v2.3.2/index.js";
```
it causes
```
error: Expected a JavaScript or TypeScript module, but identified a Cjs module. Importing these types of modules is currently not supported.
  Specifier: https://deno.land/x/i18next_fs_backend@v2.3.2/lib/fs.cjs
    at https://deno.land/x/i18next_fs_backend@v2.3.2/lib/readFile.js:4:24
```
[/lib/readFile.js:4:24](https://deno.land/x/i18next_fs_backend@v2.3.2/lib/readFile.js?source#L4) is just `import * as fsMod from './fs.cjs'` and [/ilb/fs.cjs](https://deno.land/x/i18next_fs_backend@v2.3.2/lib/fs.cjs?source) is
```cjs
if (typeof require !== 'undefined') {
  var f = require('fs')
  if (f && f.default) f = f.default
  exports.default = f
  module.exports = exports.default
}
```

**Comment by lucacasonato** [comment]
This is correct, you can not import remove files in Deno 2 if they end with `.cjs`. You should rename the file to `.js`.

**Comment by NyaightHazard** [comment]
oopsy
thanks
