### ISSUE TITLE
NextJS 15's new next.config.ts breaks when using Deno

### ISSUE THREAD

**Issue by dityaaa** [denoland/deno#26505]
Version: Deno 2.0.2

Using NextJS 15, next.config.ts, and next-intl, I cannot run `deno task dev` with the following error:
```
➜  example-app git:(development) ✗ deno run dev
Task dev next dev --turbopack
error: Uncaught (in promise) Error: Cannot find module 'next-intl/plugin'
Require stack:
- /home/aditya/projects/example-app/next.config.compiled.js
- /home/aditya/projects/example-app/node_modules/next/dist/build/next-config-ts/transpile-config.js
- /home/aditya/projects/example-app/node_modules/next/dist/server/config.js
- /home/aditya/projects/example-app/node_modules/next/dist/cli/next-test.js
- /home/aditya/projects/example-app/node_modules/next/dist/bin/next
    at Function.Module._resolveFilename (node:module:622:15)
    at file:///home/aditya/projects/example-app/node_modules/next/dist/server/require-hook.js:55:36
    at Function.Module._load (node:module:500:27)
    at Module.require (node:module:684:19)
    at Module.mod.require (file:///home/aditya/projects/example-app/node_modules/next/dist/server/require-hook.js:65:28)
    at require (node:module:808:16)
    at Object.<anonymous> (file:///home/aditya/projects/example-app/next.config.compiled.js:11:54)
    at Object.<anonymous> (file:///home/aditya/projects/example-app/next.config.compiled.js:182:4)
    at Module._compile (node:module:748:34)
    at requireFromString (file:///home/aditya/projects/example-app/node_modules/next/dist/build/next-config-ts/require-hook.js:81:7)
```

But when I use Node 20.11.1, it's running perfectly
```
➜  example-app git:(development) ✗ npm run dev

> example-app@0.1.0 dev
> next dev --turbopack

  ▲ Next.js 15.0.1 (Turbopack)
  - Local:        http://localhost:3000
  - Environments: .env.local
  - Experiments (use with caution):
    · turbo

 ✓ Starting...
 ✓ Compiled in 297ms
 ✓ Ready in 1335ms
```

\* note that with or without turbopack results in the same error.
** only reproducable using next.config.ts. using next.config.mjs or next.config.js run perfectly fine.

**Comment by bartlomieju** [comment]
@dityaaa could you please provide commands to create a project like this so we can reproduce it?


On another note, we should add `info/hint` for error like this suggesting to check if the dependency is installed.

**Comment by dityaaa** [comment]
Also based on your suggestion, here is the truncated version of `deno add`, `deno info`, and `deno task dev` in listed order:

![image](https://github.com/user-attachments/assets/b1642e8a-c34b-4f3c-bea3-d22175e88680)
![image](https://github.com/user-attachments/assets/75934bff-1519-4900-aa24-6fc9b3e5c418)

**Comment by dityaaa** [comment]
** only reproducable using next.config.ts. using next.config.mjs or next.config.js run perfectly fine.

**Comment by dityaaa** [comment]
For my last note (only reproducable using next.config.ts. using next.config.mjs or next.config.js run perfectly fine), you can try to run the command below:

**Change next.config.ts to next.config.mjs**
```shell
rm next.config.ts && echo 'import createNextIntlPlugin from "next-intl/plugin";
const withNextIntl = createNextIntlPlugin();
const nextConfig = {};
export default withNextIntl(nextConfig);' > next.config.mjs
```

**Try to run the project again. This time it works**
```shell
deno task dev
```
