### ISSUE TITLE
Bug: DevTools sources panel is empty

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/deno#26512]
Looks like chrome changed something in relation to the DevTools bridge again.

## Steps to reproduce

1. Run `deno init`
2. Run `deno run --inspect-brk main.ts`
3. Go to `chrome://inspect` and click on "inspect"

<img width="1192" alt="Screenshot 2024-10-24 at 15 16 33" src="https://github.com/user-attachments/assets/5afa4104-fb21-443d-b0c7-b2790c1c20b7">

Chrome shows this new warning, but the fallback option doesn't work either.

<img width="547" alt="Screenshot 2024-10-24 at 15 16 42" src="https://github.com/user-attachments/assets/dd7f53d2-0cee-4fdd-ad54-1f31ca226d3f">

Version: Deno 2.0.2 and canary deno 2.0.2+ef53ce3

**Comment by lucacasonato** [comment]
What Chrome version are you on?

**Comment by marvinhagemeister** [comment]
This was on `130.0.6723.58` but it seems like a update is pending. It updated to `130.0.6723.70`. I can reproduce the problem with both versions though.

**Comment by lucacasonato** [comment]
It is completely broken for me too (including the console).

**Comment by bartlomieju** [comment]
It's because of https://github.com/denoland/deno/commit/194c453a272ca8859042f46f814f2d383738bc90. Opened a revert.
