### ISSUE TITLE
REPL Ctr-C

### ISSUE THREAD

**Issue by pistacchio** [denoland/deno#2653]
Tested on MacOsX Mojave with Deno

```
deno: 0.12.0
v8: 7.7.200
typescript: 3.5.1
```

When running the REPL, while `Ctrl-D` exits the program, `Ctrl-C` yields the following exception:

```
thread 'tokio-runtime-worker-0' panicked at 'not yet implemented', ../../cli/deno_error.rs:197:12
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread 'main' panicked at 'internal error: entered unreachable code', ../../third_party/rust_crates/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.21/src/runtime/threadpool/mod.rs:296:26
thread 'tokio-runtime-worker-2' panicked at 'unexpected state while aborting task: Complete', ../../third_party/rust_crates/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.14/src/task/mod.rs:216:21
```

As a reference, for instance, on `Ctrl-C` Node would say:

```
>
(To exit, press ^C again or ^D or type .exit)
```

**Comment by nayeem-rahman** [comment]
Linux, too. This was working on 0.11.0.

**Comment by al6x** [comment]
Not sure if an error. Ctrl+C doesn't exit the deno REPL but prints the message "exit using ctrl+d or close()".

Very inconvenient, I don't know much about Unix/Linux conventions and processes, but almost every program exit by "ctrl+c" so it's very unconvenient that every time you use deno REPL you need to close it differently.
