### ISSUE TITLE
Panic on deno install when config file contains \r\n newlines

### ISSUE THREAD

**Issue by lexuzieel** [denoland/deno#26543]
Hello again! Now that deno 2 has been released I'm trying to migrate from node to deno.

In the announce blog post I've read about `deno install` command, so I tried:

```
deno install lodash
```

This resulted in the following error:

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: windows x86_64
Version: 2.0.3
Args: ["C:\\Users\\Aleksei\\.deno\\bin\\deno.exe", "install", "lodash"]

thread 'main' panicked at C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\jsonc-parser-0.26.1\src\cst\mod.rs:2310:24:
begin <= end (2 <= 1) when slicing `
    `
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by lexuzieel** [comment]
After further research looks like it panics when `package.json` is present in the directory. Renaming it allowed the command to run

**Comment by lexuzieel** [comment]
I've been thinking maybe it's worth creating a migration path for people who try to migrate from node and have package.json? Something like `deno init` automatically running `deno install` for all `package.json` dependencies and notifying the user about this, possibly renaming it to `package.json.bak`?

**Comment by dsherret** [comment]
Can you show what's in your package.json? I think this is a problem in Deno 2.0.3 but not lower ones.

**Comment by dsherret** [comment]
I think this is only an issue on Windows when the file contains `\r\n` newlines.

**Comment by lexuzieel** [comment]
Looks like I managed to reproduce it — changing line endings of deno.json to LF fixed it, when switching back to CRLF the error occurs again.
