### ISSUE TITLE
Remove in Deno 2.0 support of `process` global and instead add `--sloppy-node-globals`

### ISSUE THREAD

**Issue by redradist** [denoland/deno#26549]
### Discussed in https://github.com/denoland/deno/discussions/26392

<div type='discussions-op-text'>

<sup>Originally posted by **redradist** October 18, 2024</sup>
Deno 2.0 delivers bunch of features, but also bunch of inconsistency ...

Why Deno 2.0 supports `process` global, but require to create `require` method manually ?!
See:
https://docs.deno.com/runtime/fundamentals/node/#node.js-global-objects
https://docs.deno.com/runtime/fundamentals/node/#commonjs-support

Personally I think support of `process` global by default is mistake, I think it should be only supported in imported modules using `npm:` or in `*.cjs` files like it done for `require` method ...

Such support of global `process`, broke detection of runtime. Also it make no sense why support one feature and not support other, and where is the boundary between `deno` and `node` runtime ...</div>

**Comment by dsherret** [comment]
This ship has sailed. The process global is here to stay.

> Why Deno 2.0 supports process global, but require to create require method manually ?!

`require` is only available in commonjs modules. You can use `require` globally in CJS files in Deno:

```js
// example.cjs
require("./other_file.cjs");

// other_file.cjs
console.log("Hello");
```

```
> deno run -A example.cjs
Hello
```
