### ISSUE TITLE
Show hint when trying to install a package globally without a `:npm`/`:jsr` prefix

### ISSUE THREAD

**Issue by dmint789** [denoland/deno#26545]
When I try to install a package globally without specifying the source (e.g. `deno install -g concurrently`), it throws this error: 'error: Module not found "/path/to/current/dir/package_name"'. Instead, it should show the same type of hint as `deno add [package without a source specifier]` (e.g. error: concurrently is missing a prefix. Did you mean `deno add npm:concurrently`?).

**Comment by bartlomieju** [comment]
Good idea, it's a "Good first issue" if someone is interested in implementing it. You can start by looking at `install_global` function in `cli/tools/installer.rs` and following what `install_local` is doing to figure out if a prefix should be added.

**Comment by SatanshuMishra** [comment]
This would be my first PR but I am happy to give it a try if that's alright!

**Comment by bartlomieju** [comment]
@SatanshuMishra please do
