### ISSUE TITLE
--inspect-wait flag stopped working in 2.0.2

### ISSUE THREAD

**Issue by skybrian** [denoland/deno#26556]
Version: Deno 2.0.2

To reproduce, create a file:

```ts
debugger;
```

Then run it like this:

```
deno --inspect-wait debugger.ts
```

I connect from Chrome, using "chrome://inspect". I'm using Chrome 130.0.6723.70. There are links for "inspect" and "inspect fallback" and neither one works with 2.0.2. (Also, profiling doesn't work either, which is what I'm actually trying to do.)

Workaround: downgrading to 2.0.1 fixes the problem.

**Comment by bartlomieju** [comment]
This has been fixed in https://github.com/denoland/deno/pull/26513 and you can upgrade to Deno v2.0.3 to get it working.
