### ISSUE TITLE
Quiet output when piping scripts into the deno CLI to make it similar to node

### ISSUE THREAD

**Issue by ndmekala** [denoland/deno#26550]
When you pipe a script into the node CLI, the console result is quiet, suppressing everything but explicit logs to the console. Comparatively, deno is very verbose, logging `undefined` for any line that doesn’t log and sending other messages.

The noisiness of the output makes it unideal for this use case, but it would be a great feature. I’d love to be able to, e.g., dynamically import a lodash-like library, test out some function, and cleanly log out the result from within neovim (e.g. `:w !deno`).

![Screenshot 2024-10-25 at 12 12 07 PM](https://github.com/user-attachments/assets/c3b14ddd-990a-4fc4-b8fa-b98aebe6726f)

**Comment by ndmekala** [comment]
macOS 15, `node` v22.6, `deno` 2.0.0

**Comment by nathanwhit** [comment]
`deno` with no arguments defaults to starting a REPL. Try adding a `-` to indicate deno should run from stdin:

```
deno - << EOF
let a = "hi";

console.log(a);
EOF
```
prints just `hi`

**Comment by ndmekala** [comment]
This works great thanks.
