### ISSUE TITLE
Deno fmt causes indentation problems in VSCode

### ISSUE THREAD

**Issue by Drakim** [denoland/deno#26564]
Version: Deno v2.0.3

This is a weird formatting interaction that happens between VSCode and Deno. It's not strictly Deno nor VSCode's fault in isolation, but it does create a bad experience for a user using Deno on VSCode, which is a fairly common combination.

If you run "deno fmt" on this code:

```ts
Deno.test('foo', () =>
    assertEquals(
        7,
        7,
        'foo test',
    )
);
```

It's formatted like this:

```ts
Deno.test('foo', () =>
    assertEquals(
        7,
        7,
        'foo test',
    ));
```

Now if you copypaste the test or start manually writing underneath to create more test, VSCode indents it like this:

```ts
Deno.test('foo', () =>
    assertEquals(
        7,
        7,
        'foo test',
    ));

    Deno.test('foo', () =>
        assertEquals(
            7,
            7,
            'foo test',
        ));

        Deno.test('foo', () =>
            assertEquals(
                7,
                7,
                'foo test',
            ));
```

This is obviously wrong since we are writing a new statement that is not hierarchically under the previous statement. Deno fmt places the ending parenthesis on a different indentation level than the starting parenthesis, and this confuses VSCode when you begin writing the next statement.

Some option to change fmt's behavior here to not "unbalance" the paranthesises would be nice.

Edit:
In fact, I'm starting to think this is actually an outright bug in fmt's behavior.

If you run deno fmt on some code like this it does not move the parenthesis up in the same way:

```ts
foo(
    1,
    2,
    3,
);
```

**Comment by dsherret** [comment]
This sounds like a vscode issue?

> In fact, I'm starting to think this is actually an outright bug in fmt's behavior. If you run deno fmt on some code like this it does not move the parenthesis up in the same way:

That's by design at the moment. Follow https://github.com/denoland/deno/issues/7868
