### ISSUE TITLE
Panic writing to global cache when cache is a readonly file system

### ISSUE THREAD

**Issue by chasm** [denoland/deno#26575]
This has been a consistent problem for me for months in VSCode. I am finally doing what it tells me to do by reporting it. Any idea why this is happening and how to fix it?

```sh
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos aarch64
Version: 2.0.2
Args: ["/opt/homebrew/bin/deno", "lsp"]

thread 'main' panicked at /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/index.crates.io-6f17d22bba15001f/deno_cache_dir-0.13.0/src/global/mod.rs:116:6:
called `Result::unwrap()` on an `Err` value: Custom { kind: ReadOnlyFilesystem, error: "Read-only file system (os error 30) (for '//.cache/registries/https/deno.land')\nCheck the permission of the directory." }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Error - 2:06:21 PM] The Deno Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
```

**Comment by dmint789** [comment]
@chasm it might be helpful if you give the steps to reproduce this bug

**Comment by chasm** [comment]
Every time I open VSCode I get this error after a few seconds. Project is an Astro project using Deno and Deno Deploy. Nothing special about it.

Could it be an extension? I could disable them all, restart, see if it happens. If not, I can turn them on one by one until it does. I'll do that tomorrow (it's after midnight here).

**Comment by chasm** [comment]
OK, I disabled all extensions and reinstalled the Deno extension and closed and reopened VSCode to the Welcome page. Within 10 seconds I got the above error again. The only extension is Deno and no file is open. The project is a simple Deno Astro app.

I also get an error "Failed to retrieve config tasks." Source: Deno.

Ideas? Are there VSCode settings I should set or unset?
