### ISSUE TITLE
Enable npm packages to work without the `node:` specifier

### ISSUE THREAD

**Issue by akku1139** [denoland/deno#26582]
Some npm packages import Node.js APIs without the `node:` specifier.
To enhance compatibility, Deno should allow npm packages to use the Node.js API without the `node:` specifier.

**Comment by dsherret** [comment]
Can you show an example? Deno should already allows npm packages to work without the `node:` specifier.

**Comment by akku1139** [comment]
Import error occurred on October 1st, but there is no problem now.
There is currently no problem, so I close the issue.
