### ISSUE TITLE
bug: `deno compile` creates a binary that doesn't properly handle HTTP redirects

### ISSUE THREAD

**Issue by KnorpelSenf** [denoland/deno#26583]
Version: Deno 2.0.3

## Repro

Create any script with an HTTP import, such as this one:

```ts
// /tmp/main.ts
import { Bot } from "https://deno.land/x/grammy/mod.ts";

const bot = new Bot("secret-token");
console.log(bot.token);
```

Compile it and run the binary.

```sh
# /tmp/repro.sh
set -e
deno install --reload --allow-import --entrypoint /tmp/main.ts
deno compile -Ao /tmp/app /tmp/main.ts
/tmp/app
```

You will see the following output.

```sh
error: Module not found: https://deno.land/x/grammy/bot.ts
```

Instead, it is expected that the script runs correctly and that the output is just `secret-token`.

## Cause

This works correctly with 2.0.2.

I used `git bisect` to narrow it down to #26494. /cc @dsherret

**Comment by KnorpelSenf** [comment]
Note that `https://deno.land/x/grammy/mod.ts` re-exports `Bot` ([src](https://github.com/grammyjs/grammY/blob/5aac3e654b164eb89aac6aaa77d3634a3e35f12a/src/mod.ts#L3)) so my guess is that the binary only contains the modules that are imported directly, but not those that get imported transitively.

**Comment by dsherret** [comment]
I think it’s missing redirects. If you import the resolved specifier it will probably work.

**Comment by KnorpelSenf** [comment]
> I think it’s missing redirects. If you import the resolved specifier it will probably work.

Can confirm that this fixed it.
