### ISSUE TITLE
DNS name resolution stopped working for IPv6-only Redis host

### ISSUE THREAD

**Issue by cy6erskunk** [denoland/deno#26588]
Version: Deno 2.0.3

Hostname resolution for IPv6-only Redis server started to throw `ENOTFOUND` after updating to Deno 2.0.x.
Rolling back to the latest Deno 1.x solves the problem.
```
Redis Client Error Error: getaddrinfo ENOTFOUND foo-bar.upstash.io
    at __node_internal_captureLargerStackTrace (ext:deno_node/internal/errors.ts:93:9)
    at __node_internal_ (ext:deno_node/internal/errors.ts:246:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:37:26)
    at ext:deno_node/internal_binding/cares_wrap.ts:85:9
    at eventLoopTick (ext:core/01_core.js:175:7) {
  errno: -3007,
  code: "ENOTFOUND",
  syscall: "getaddrinfo",
  hostname: "foo-bar.upstash.io"
}
```
I'm using `npm:redis@4.7.0`.

**Comment by kt3k** [comment]
Do you see the same error with Deno 2.0.2?

We changed dns.lookup a little bit in https://github.com/denoland/deno/pull/26264 , and that might have affected it.

Also how does the same code work in Node.js?

**Comment by cy6erskunk** [comment]
> Do you see the same error with Deno 2.0.2?

Yes
> Also how does the same code work in Node.js?

I don't know, It's been a Deno project since the very beginning, but it works with Deno 1.46.2

**Comment by kt3k** [comment]
> > Do you see the same error with Deno 2.0.2?
>
> Yes

Sorry, I made mistake in checking the shipped version of #26264 

Could you also check with Deno 2.0.0?

**Comment by cy6erskunk** [comment]
> Could you also check with Deno 2.0.0?

I can confirm that it works in Deno 2.0.0

Would you have any idea when #26621 will be released?

**Comment by bartlomieju** [comment]
@cy6erskunk later tonight, you can run `deno upgrade canary` to get a canary version with the fix included.

**Comment by cy6erskunk** [comment]
Seems to be working, thanks a lot!
