### ISSUE TITLE
Consider `SourceFileFetcher` as separate struct

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#2659]
In #2636 I introduced `SourceFileFetcher` trait that encapsulates logic for fetching local and remote files. It is implemented on `DenoDir` struct but IMHO it might as well be factored out as separate struct and use `DenoDir` only as caching directory. 

Proposed solution:
1. move `SourceFileFetcher` trait to `//cli/file_fetcher.rs` and implement it as struct
1. instantiate `SourceFileFetcher` in `ThreadSafeState::new` with `DenoDir.deps_cache` as an argument
1. pass created `SourceFileFetcher` to `TsCompiler` as an argument

I welcome suggestions for better name.

CC @ry

**Comment by kevinkassimo** [comment]
Personally I am more in favor factoring out a field DenoDir.remoteFetcher that does only "fetch" and no caching. The DenoDir coordinates interactions between fetcher and different caches and expose a transparent API that hides away the fact that the files might not present locally yet or the existence of a cache.

**Comment by bartlomieju** [comment]
> Personally I am more in favor factoring out a field DenoDir.remoteFetcher that does only "fetch" and no caching. The DenoDir coordinates interactions between fetcher and different caches and expose a transparent API that hides away the fact that the files might not present locally yet or the existence of a cache.

Yeah, but this gives `DenoDir` 2 responsibilities: provider of caches (instead of hard coding `gen_cache` and `deps_cache` it could be refactored to `DenoDir.create_cache()`) and file fetcher. 
I suggest we treat `DenoDir` only as provider of caches and move `SourceFileFetcher` to `ThreadSafeState`. That way it's pretty good decoupling and single responsibility for both `SourceFileFetcher` and `DenoDir`. 

Take for example `TsCompiler` and it's `new` method:
```rust
  pub fn new(
    deno_dir: DenoDir,
    use_disk_cache: bool,
    config_path: Option<String>,
  ) -> Self {
    let compiler_config = match load_config_file(config_path) {
      (Some(config_path), Some(config)) => Some((config_path, config.to_vec())),
      _ => None,
    };

    let config_bytes = match &compiler_config {
      Some((_, config)) => config.clone(),
      _ => b"".to_vec(),
    };

    Self {
      disk_cache: deno_dir.clone().gen_cache,
      deno_dir,
      config: compiler_config,
      config_hash: config_bytes,
      compiled: Mutex::new(HashSet::new()),
      use_disk_cache,
    }
  }
```

It could be rewritten as such:
```rust
  pub fn new(
    deno_dir: &DenoDir,
    file_fetcher: &SourceFileFetcher,
    use_disk_cache: bool,
    config_path: Option<String>,
  ) -> Self {
    ...
    let disk_cache = deno_dir.create_cache("gen");
    
    Self {
      disk_cache,
      file_fetcher,
      config: compiler_config,
      config_hash: config_bytes,
      compiled: Mutex::new(HashSet::new()),
      use_disk_cache,
    }
  }
```
