### ISSUE TITLE
"Publishing packages" docs talk about `deno bundle`

### ISSUE THREAD

**Issue by lgarron** [denoland/deno#26609]
deno 2.0.1 (stable, release, aarch64-apple-darwin)

I wanted to figure out what transformations publishing packages performs on TypeScript code. https://jsr.io/docs/publishing-packages mentions: 

> When using Deno, the `include` and `exclude` options in `deno.json` are used for many other Deno subcommands as well, such as `deno test` and `deno bundle`.

From what I can tell, `deno bundle` is completely removed in `deno` now, so I don't think it serves as a good examle.

**Comment by dsherret** [comment]
Moved to https://github.com/jsr-io/jsr/issues/797 (unfortunately gh doesn't allow transfering issues between orgs)
