### ISSUE TITLE
JsonC support with `.json` suffix

### ISSUE THREAD

**Issue by aprosail** [denoland/deno#26601]
Some important files, including `.vscode/settings.json` ends with `.json` prefix, but they are exactly JsonC (Json with Comments). Current `deno fmt` cannot format such json files when there are comments inside, which is really not convenient when using pure Deno and sharing VSCode workspace configurations. Can you enable JsonC support for those `*.json` files? Or this is designed by propose?

**Comment by dsherret** [comment]
> Current deno fmt cannot format such json files when there are comments inside, which is really not convenient when using pure Deno and sharing VSCode workspace configurations.

Can you show a reproduction? It works fine for me.

**Comment by brc-dd** [comment]
For me it works fine for all files inside the project. But if you open something like user preferences and have save to format there, it shows this:

<img width="323" alt="image" src="https://github.com/user-attachments/assets/df9411e3-33a0-4f49-a55a-73330e953ed2">

**Comment by aprosail** [comment]
I finally found out the reason 🥲: It's neither the matter about Deno, nor its VSCode extension, it's just a conflict with other extensions. I was using an AI assist extension like Copilot, which is called Tongyi Lingma (VSCode extension ID: `Alibaba-Cloud.tongyi-lingma`), that once format on save, such extension will stuck, and prevent all the formatting process. Once disable such extension, both `deno fmt` command and the VSCode extension works well.

It's exactly not caused by Deno or its VSCode extension, it's completely Tongyi Lingma's fault. Moreover, the Tongyi Lingma extension will also conflict with the Dart/Flutter extension on VSCode. Your code is prefect, their code contain bugs, and I'm really sorry for wasting your time.
