### ISSUE TITLE
Memory leak in Deno.serve?

### ISSUE THREAD

**Issue by pakastin** [denoland/deno#26640]
Version: Deno 2.0.4

I have just a simple reverse proxy server like this and it has memory leak issue (always runs out of memory). I have no idea how to tackle it: https://gist.github.com/pakastin/503dcbcd141e2895a3d863253483c831

**Comment by MathiasWP** [comment]
Could you try to create a minimal reproduction? Removing all the code that does not contribute to the memory leak

**Comment by pakastin** [comment]
Of course. I'll do that!

**Comment by bartlomieju** [comment]
@pakastin did you find the problem after all?

**Comment by pakastin** [comment]
I narrowed it down and even though memory usage slowly went up in spikes it seemed to stabilize eventually
