### ISSUE TITLE
Update to most updated version of a Major 

### ISSUE THREAD

**Issue by IncognitaDev** [denoland/deno#26650]
I'm working in a project that does not support Deno 2.0, but in some projects the Deno 2.0 is required, so I have to change the version sometimes. The upgrade command requires a full version to update, its require that I remember the last version of the 1 major ever. I was think about to allow the only major as argument

today: `deno upgrade 1.46.3`
suggestion: `deno upgrade 1`

In this way we can get the last version of the major of the argument and install it.

If you think its ok, I want to make this contribution.

**Comment by bartlomieju** [comment]
I think it's the same ask as in https://github.com/denoland/deno/issues/25035?

It makes sense and PRs are welcome, but let's continue it in https://github.com/denoland/deno/issues/25035.
