### ISSUE TITLE
There's no `Object.prototype.__proto__`

### ISSUE THREAD

**Issue by AFatNiBBa** [denoland/deno#26664]
Version: Deno 2.0.4

I'm working with legacy packages that make use of `Object.prototype.__proto__`, which is not defined in deno.
This polyfill is needed
```js
Object.defineProperty(Object.prototype, "__proto__", {
    enumerable: false,
    configurable: true,
    get() { return Object.getPrototypeOf(this); },
    set(v) { Object.setPrototypeOf(this, v); }
});
```

**Comment by bartlomieju** [comment]
It's disabled by default in Deno due to security reasons. You can enable it with `--unstable-unsafe-proto` flag.

**Comment by dsherret** [comment]
You can also specify:

```
{
  "unstable": ["unsafe-proto"]
}
```

in a deno.json file.

Read more:

* https://docs.deno.com/runtime/reference/cli/unstable_flags/#--unstable-unsafe-proto
* https://learn.snyk.io/lesson/prototype-pollution/
