### ISSUE TITLE
Installing a npm package with a bin populated by a postinstall script doesn't work

### ISSUE THREAD

**Issue by jgoux** [denoland/deno#26677]
Version: Deno 2.0.4

Hello folks,

I'm giving Deno a spin as my main development tool to replace node/npm. I'm trying to run [Supabase CLI](https://www.npmjs.com/package/supabase) with it and failing.

I have a package.json:
```json
{
  "devDependencies": {
    "supabase": "^1.207.9"
  }
}
```

Then doing :
```sh
deno install --allow-scripts
```

And here is the output:
```
Warning Trying to set up 'supabase' bin for "/Users/jgoux/Code/supabase-workflows/node_modules/.deno/supabase@1.207.9/node_modules/supabase", but the entry point "/Users/jgoux/Code/supabase-workflows/node_modules/.deno/supabase@1.207.9/node_modules/supabase/bin/supabase" doesn't exist.
```

I think the issue is that the symlinks get only created before the postinstall scripts run, which is an issue for CLI that get downloaded in postinstall scripts like Supabase one.

Another issue is that even if I create the symlink myself, `deno run` is failing:
```sh
ln -s /Users/jgoux/Code/supabase-workflows/node_modules/supabase/bin/supabase node_modules/.bin/supab
ase
deno run -A supabase --version
```

Output:
```
error: Is a directory (os error 21)
```

For this one I suppose it's because in a regular Supabase project, you create a `supabase` directory at the root of your project. And `deno run` is prioritizing this folder over the binary in `node_modules/.bin/supabase`. 
To resolve this it would be better to priorize binaries over folders, or have a dedicated `exec` subcommand to run binaries explicitly?

**Comment by nathanwhit** [comment]
Thanks for reporting! I can reproduce the issue and confirmed it's something we should handle. I've opened a PR that should resolve the issue.


With regards to this part:

> Another issue is that even if I create the symlink myself, deno run is failing:

It's not at all clear from the error message, but we don't currently support running binaries like that. You can run them directly like

```bash
./node_modules/.bin/supabase --version
```

or we support running binaries via scripts, so you can work around this with a script like

```json
{
   "scripts": {
      "supabase": "supabase"
    }
}
```

and then execute it with 

```
deno task supabase --version
```
or 
```
# note that this is running the script, which runs the binary
deno run supabase --version
```

Though I agree that it would be good to have something like `npm exec` for this
