### ISSUE TITLE
Panic when watching 90103 files for changes

### ISSUE THREAD

**Issue by liamdiprose** [denoland/deno#26670]
Version: Deno 2.0.2

Firstly I want to say how excited I am by the direction of the project; Supabase's adoption, Jupyter kernel built in, Sveltekit compatibility.

I encountered a showstopper this week using my usual NixOS-direnv environment for a Sveltekit project:

<details>
<summary>Panic after running <code>deno task dev</code></summary>
<pre><code>$ RUST_BACKTRACE=1 deno task dev
Task dev vite dev
Port 5173 is in use, trying another one...

  VITE v5.4.10  ready in 246 ms

  ➜  Local:   http://localhost:5174/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 2.0.2
Args: ["/nix/store/8sr95hpklk6d044jarjhccc28vicjpv6-deno-2.0.2/bin/deno", "run", "--ext=js", "-A", "/home/liam/work/farm/workstation/node_modules/.deno/vite@5.4.10/node_modules/vite/bin/vite.js", "dev"]

thread 'main' panicked at /build/deno-2.0.2-vendor.tar.gz/notify/src/inotify.rs:517:32:
called `Result::unwrap()` on an `Err` value: "SendError(..)"
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: <notify::inotify::INotifyWatcher as notify::Watcher>::watch
   4: deno_runtime::ops::fs_events::op_fs_events_open::op_fs_events_open::v8_fn_ptr
   5: Builtins_CallApiCallbackOptimizedNoProfiling
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
</code></pre>
</details>

It turns out my setup was creating a `.direnv/` directory that has 90103 total files if you ls recursively and follow symlinks.

**Workaround**: The addition to Sveltekit's default `vite.config.js` removes the problem:

```js
{
    server: {
        watch: {
            ignored: ["**/.direnv"]
        }
    }
}
```

I've posted this issue to help anyone else looking to solve this problem and note this panic for Deno's maintainers in case they think the handling of this case should be improved.

**Comment by bartlomieju** [comment]
@liamdiprose do you get the same problem on latest Deno (2.0.4)? We landed a fix to file watching last week, that might have fixed it already (https://github.com/denoland/deno/pull/26200).
