### ISSUE TITLE
Panic while downloading assets for compiling

### ISSUE THREAD

**Issue by ZakaHaceCosas** [denoland/deno#26672]
Version: Deno 2.0.4

Got this trying to compile my program (`deno compile ...`).
```txt
(...)
Download https://dl.deno.land/release/v2.0.4/denort-x86_64-unknown-linux-gnu.zip
unpacking via zip crate failed: invalid Zip archive: No valid central directory found

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the      
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: windows x86_64
Version: 2.0.4
Args: ["C:\\deno\\deno.exe", "compile", "--allow-read", "--allow-write", "--allow-net", "--allow-env", "--allow-run", "--unstable-cron", "--target", "x86_64-pc-windows-msvc", "--output", "dist/FN-win64", "src/main.ts"]

thread 'main' panicked at cli\util\archive.rs:116:3:
assertion failed: exe_path.exists()
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I tried running with `RUST_BACKTRACE=1` and it somehow worked as expected (and showing no backtrace).

**Comment by bartlomieju** [comment]
@ZakaHaceCosas are you able to reproduce it again if running without `RUST_BACKTRACE=1`?

**Comment by ZakaHaceCosas** [comment]
> @ZakaHaceCosas are you able to reproduce it again if running without `RUST_BACKTRACE=1`?

No, I tried again with and without `RUST_BACKTRACE=1`, and it works now. Might just be an edge case.

**Comment by bartlomieju** [comment]
@ZakaHaceCosas should we close this issue for now then? I'll be happy to reopen it if you ever hit it again.

**Comment by ZakaHaceCosas** [comment]
> @ZakaHaceCosas should we close this issue for now then? I'll be happy to reopen it if you ever hit it again.

Yeah, I'll close it. Thank you!
