### ISSUE TITLE
Deno `v2.0` cli panics when generating docs as HTML

### ISSUE THREAD

**Issue by mandy8055** [denoland/deno#26688]
- **Version: Deno 2.0.0**
- **v8 12.9.202.13-rusty** 
- **typescript 5.6.2**

This bug is caused when running the below command for **outputting docs locally in HTML format** on my mac machine(**MacOS Sequoia v15.0.1**):
```bash
deno doc --html --name="My library" ./src/mod.ts
```

Actual bug report:

```bash
============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos aarch64
Version: 2.0.0
Args: ["deno", "doc", "--html", "--name=My library", "./src/mod.ts"]

thread 'main' panicked at /<my_dir>/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/deno_doc-0.152.0/src/html/symbols/namespace.rs:131:47:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by bartlomieju** [comment]
I believe this is already fixed. Please upgrade to the latest release (2.0.4)

**Comment by mandy8055** [comment]
@bartlomieju,
thanks for a quick response. Yes after upgrading to latest deno version(2.0.4), the bug goes away and the docs are generated as HTML. Sorry for bothering I checked only the open issues to see if this has already been raised. Will close this issue. Thanks
