### ISSUE TITLE
deno fmt should keep line breaks for the html class attribute. 

### ISSUE THREAD

**Issue by sylc** [denoland/deno#26690]
I use tailwindcss and often end up sometimes with lots of classes in my either .svelte files or .html files.
To make them more readable and compact i structure them with linebreaks. However currently `deno fmt` will rearrange them in one long line that needs horizontal scrolling in VScode to review

input
```html
<div
  class="aclass aclass aclass aclass aclass 
aclass aclass aclass aclass aclass aclass aclass 
aclass aclass aclass aclass aclass aclass aclass 
aclass aclass aclass aclass aclass aclass aclass 
aclass aclass aclass aclass aclass aclass aclass 
aclass aclass aclass aclass aclass aclass"
>
  div with lost of tailwindcss classes
</div>
```

expected
```html
<div
  class="aclass aclass aclass aclass aclass 
    aclass aclass aclass aclass aclass aclass aclass 
    aclass aclass aclass aclass aclass aclass aclass 
    aclass aclass aclass aclass aclass aclass aclass 
    aclass aclass aclass aclass aclass aclass aclass 
    aclass aclass aclass aclass aclass aclass"
>
  div with lost of tailwindcss classes
</div>
```

actual (deno 2.0.4 (stable, release, x86_64-pc-windows-msvc)
```html
<div
  class="aclass aclass aclass aclass aclass aclass aclass aclass aclass aclass aclass aclass aclass aclass aclass aclass aclass aclass aclass aclass aclass aclass aclass aclass aclass aclass aclass aclass aclass aclass aclass aclass aclass aclass aclass aclass aclass aclass aclass"
>
  div with lost of tailwindcss classes
</div>
```

**Comment by MohammadSu1** [comment]
@bartlomieju I believe this issue is related to #26245 because the print_width attribute has been set to its maximum value. This means that Deno will treat the content associated with the same element as a single unit and format it all in one line. We need a more optimal solution to avoid this problem.

**Comment by bartlomieju** [comment]
Agreed, are you gonna look into that @MohammadSu1? I think we should try our best to respect the line-width there.

**Comment by MohammadSu1** [comment]
Yes, I will look it up, but I'm wondering about the best value for print_width to avoid causing another bug. What do you think about it? Perhaps using a value like 120 instead of 80?

**Comment by bartlomieju** [comment]
Yeah I guess we can try that. Usually 80 chars in HTML is too little to be useful.

**Comment by MohammadSu1** [comment]
I will try it now. I'm considering fixing that upstream in the markup_fmt itself because the previous solution was there
