### ISSUE TITLE
Types for `ArrayBuffer.transfer` and `ArrayBuffer.transferToFixedLength` are missing.

### ISSUE THREAD

**Issue by BlackAsLight** [denoland/deno#26705]
Version: Deno 2.0.4

According to MDN docs, Deno supports both `.transfer()` and `.transferToFixedLength()` while Node doesn't, and this is true when running the code, but the TypeScript linting doesn't display these options. Saying it doesn't exist.

- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer/transfer
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer/transferToFixedLength

**Comment by petamoriken** [comment]
TypeScript 5.7 will include ES2024 type definitions. Please wait a moment.
https://devblogs.microsoft.com/typescript/announcing-typescript-5-7-beta/#support-for---target-es2024-and---lib-es2024

**Comment by petamoriken** [comment]
Looks like a duplicate of #25993

**Comment by BlackAsLight** [comment]
Is there a scheduled date for when 5.7 will be released?

**Comment by petamoriken** [comment]
It will be released on 2024-11-21.
https://github.com/microsoft/TypeScript/issues/59905

**Comment by bartlomieju** [comment]
Oh this is gonna be a tight one, we are scheduled to release on Nov, 21st too. Maybe we'll delay by one day to include TS upgrade.

**Comment by petamoriken** [comment]
NOTE:

TypeScript 5.7 will bring a breaking change that will make TypedArray generics.

> In ECMAScript 2024, `SharedArrayBuffer` and `ArrayBuffer` have types that slightly diverge. To bridge the gap and preserve the underlying buffer type, all `TypedArrays` (like `Uint8Array` and others) [are now also generic](https://github.com/microsoft/TypeScript/pull/59417).
> 
> ```ts
> interface Uint8Array<TArrayBuffer extends ArrayBufferLike = ArrayBufferLike> {
>     // ...
> }
> ```

https://devblogs.microsoft.com/typescript/announcing-typescript-5-7-beta/#typedarrays-are-now-generic-over-arraybufferlike

Type definition files will need to be updated and [`@types/node` will need to be pinned to v22.7.4 or later](https://github.com/microsoft/TypeScript/pull/58573#issuecomment-2379880749).

https://github.com/denoland/deno/blob/2c8a0e791732ab00907ca11c3a4918ad26ead03f/cli/npm/managed/resolution.rs#L318-L323

**Comment by dsherret** [comment]
Tracking in https://github.com/denoland/deno/issues/26950
