### ISSUE TITLE
`pino` logger doesn't work in Deno

### ISSUE THREAD

**Issue by kt3k** [denoland/deno#26709]
The below pino script:
```js
import { pino } from "pino";
const transport = pino.transport({
  level: "trace",
  target: "pino/file",
  options: { destination: "log.txt" },
});
export const logger = pino(transport);
logger.info("abc");
```

should creates `log.txt` file with something like the below contents:

```
{"level":30,"time":1730727130896,"pid":12345,"hostname":"your-hostname","msg":"abc"}
```

But it doesn't seem working.

(This was pointed in https://github.com/denoland/std/issues/6124#issuecomment-2454687301 )

Note: [pino](https://github.com/pinojs/pino) is the logger for [fastify](https://github.com/fastify/fastify). It has relatively large number of github stars (14K) and weekly npm downloads (8M/week)

**Comment by nathanwhit** [comment]
maybe duplicate of https://github.com/denoland/deno/issues/26154?

**Comment by kt3k** [comment]
Ah, yes. Thanks!
