### ISSUE TITLE
Running `deno task dev` in my workspace directory runs scripts from the root deno.json

### ISSUE THREAD

**Issue by MarcelloPaiva** [denoland/deno#26702]
Version: Deno 2.0.3

I have a simple Deno project with a single directory, called "frontend", in its workspace configuration. When I use my terminal to run `deno task dev` from the "frontend" directory, it runs the dev script from the root deno.json file.

root deno.json:
```
{
  "tasks": {
    "dev": "deno run --watch main.ts"
  },
  "imports": {
    "@std/assert": "jsr:@std/assert@1"
  },
  "workspace": ["./frontend"]
}
```

frontend deno.json:
```
{
  "name": "@scope/frontend",
  "version": "0.0.1",
  "type": "module",
  "scripts": {
    "dev": "vite dev",
    "build": "vite build",
    "preview": "vite preview",
  },
  "devDependencies": {
    "@sveltejs/adapter-auto": "^3.0.0",
    "@sveltejs/kit": "^2.0.0",
    "@sveltejs/vite-plugin-svelte": "^4.0.0",
    "svelte": "^5.0.0",
    "svelte-check": "^4.0.0",
    "typescript": "^5.0.0",
    "vite": "^5.0.3"
  }
}
```

Terminal output:
<img width="606" alt="Screenshot 2024-11-03 at 10 00 24 AM" src="https://github.com/user-attachments/assets/44b752c4-4263-4bc1-9bac-078bd593f943">

**Comment by MarcelloPaiva** [comment]
If I then remove the `dev` task from the root deno.json and try running `deno task dev` from the frontend directory, I get the following error: 
```
Task not found: dev
Available tasks:
  No tasks found in configuration file
```

**Comment by MarcelloPaiva** [comment]
That would do it! Thank you!

**Comment by irbull** [comment]
No problem. Sometimes a second pair of eyes is all we need. Happy to help.
