### ISSUE TITLE
TypeError when running Nitro project with deno run dev

### ISSUE THREAD

**Issue by kotkifotki** [denoland/deno#26700]
## Description

After creating a new project with `deno run -A npm:giget@latest nitro nitro-app --install`, running it with `deno run dev` results in a TypeError.

## Reproduction Steps

1. Create a new project using `deno run -A npm:giget@latest nitro nitro-app --install`
2. Run the project with `deno run dev`

## Expected Behavior

The project should start without errors.

## Actual Behavior

The project fails to start throwing the following error:

```
error: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'pathname')
    at getPathname (ext:deno_node/_fs/_fs_stat.ts:177:49)
    at ext:deno_node/_fs/_fs_stat.ts:151:13
    at eventLoopTick (ext:core/01_core.js:175:7)
```

## Environment

Deno version: 2.1.1, 2.1.0, 2.0.6, 2.0.5, 2.0.4
Operating system: macOS 15.1
Architecture: Arm64 (M2)

**Comment by snakysnake** [comment]
Same error for me when using nuxt
