### ISSUE TITLE
Local Module Imports & Invalid Relative Path Errors

### ISSUE THREAD

**Issue by mitchtreece** [denoland/deno#26704]
Hey all, I'm not sure if I've found an issue - or if I'm misunderstanding how local imports are supposed to work with Deno.

Let's say I have a structure like this where `app` & `pkgs/logger` are separate scoped packages (i.e. `@app/core` & `@pkg/logger`) and not part of a monorepo:

```md
- app
  - src
  - deno.json
- pkgs
  - logger
    - src
    - mod.ts
    - deno.json
```

Now `app` imports the local (development) `@pkg/logger` package in it's `deno.json` (note that this is a development package - the intention would be for this import to eventually be migrated to an actual remote, i.e. `jsr:@pkgs/logger@^1.0.0`)

```json
"imports": {
  "@pkg/logger": "../pkgs/logger"
}
```

We get the following error: `error: Is a directory (os error 21)`. Okay, what if we directly reference the module file?

```json
"imports": {
  "@pkg/logger": "../pkgs/logger/mod.ts"
}
```

Well now we get errors regarding relative import path issues for packages that `@pkg/logger` imports. For example, the following `deno.json` configuration for `@pkg/logger`:

```json
{
    "name": "@pkg/logger",
    "version": "1.0.0",
    "exports": "./mod.ts",
    "imports": {
        "@dx/reflect": "jsr:@dx/reflect@^0.2.14"
    }
}

```

Would result in this error:

`Relative import path "@dx/reflect" not prefixed with / or ./ or ../ and not in import map from ...`

I would have expected imports like this to just work out of the box - however, I may be doing something completely wrong - I'm not sure. Keep in mind, doing a setup like this **within** a monorepo workspace seems to not have any import issues even when using different package scopes.

**Version: Deno 2.0.4**

**Comment by dsherret** [comment]
Can you try out the unstable patch feature? I think it will solve your issue: https://github.com/denoland/deno/issues/25110 / https://github.com/denoland/deno/pull/25068

```
{
  "patch": [
    "../pkgs/logger"
  ]
}
```

Sorry we haven't documented it yet. We still haven't figured out exactly how it will work (been busy on the Deno 2.0 launch and some other features)

**Comment by mitchtreece** [comment]
@dsherret Thanks for the quick response! Interesting I wasn't aware of the work on `patch` - don't even worry about it, I know how hectic major releases like this can be 😄. That definitely fixed the issue!

Is this the intended workflow moving forward for local package development / dependencies? In my opinion, supporting local paths directly from `imports` would be simpler. i.e. 

```json
"imports": [
    "@pkg/example": "./packages/example"
]
```

However, you know better than I about the complexity of supporting that / if it's even a good idea 😎

**Comment by dsherret** [comment]
> In my opinion, supporting local paths directly from imports would be simpler. i.e.

We can't do that because `imports` is an import map, which has a standard: https://html.spec.whatwg.org/multipage/webappapis.html#import-maps (technically, we extended it just a little bit to make working with npm and jsr specifeirs easier)

I added an item in https://github.com/denoland/deno/issues/25110 to improve the error messages to recommend using the patch feature.

Right now patch is modeled after cargo https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html

> though I do get this warning even though I'm not using workspaces: Warning "patch" field can only be specified in the workspace root deno.json file - everything works despite the warning though.

Can you open an issue with a reproduction?

**Comment by mitchtreece** [comment]
> We can't do that because `imports` is an import map, which has a standard: https://html.spec.whatwg.org/multipage/webappapis.html#import-maps (technically, we extended it just a little bit to make working with npm and jsr specifeirs easier)

Ah makes perfect sense.

> I added an item in https://github.com/denoland/deno/issues/25110 to improve the error messages to recommend using the patch feature.

Perfect!

> Can you open an issue with a reproduction?

Yup! Will do. Thanks again for the help 😄

**Comment by mitchtreece** [comment]
@dsherret Actually I think there way be more issues here, when nesting local imports via patching i.e.

`app` → `@pkg/a` → `@pkg/b`

Deno is unable to "find" the package: `JSR package not found: @pkg/b`. This happens in addition to the previously mentioned warning: `"patch" field can only be specified in the workspace root deno.json file`. I've prepared an example repo showcasing both issues [here](https://github.com/mitchtreece/deno-local-imports-issue).

Let me know if you want me to open a new issue, or if we should just re-open this one?

**Comment by ThinkingPlanely** [comment]
@mitchtreece Did you ever open a new issue about nesting local imports? If not, I can open one myself. It's been annoying me too. This would probably be considered a new feature.

**Comment by mitchtreece** [comment]
@ThinkingPlanely No I did not. Gave up on the project structure I was going for because of all the weirdness. Definitely a good addition though, so go ahead and open a new issue 😄

**Comment by ThinkingPlanely** [comment]
I've added the issue [Recursively Importing Local Packages via "links"](https://github.com/denoland/deno/issues/31710)
