### ISSUE TITLE
Any request body becomes [object Object] in next.js

### ISSUE THREAD

**Issue by szcharlesji** [denoland/deno#26716]
Version: Deno 2.0.4

When I run `deno run dev` for next.js, any request body becomes `[object Object]`

**Comment by littledivy** [comment]
It seems Next.js creates a a new undici `Request` using Node streams (clearly against the spec AFAICT). To fix this, we will have to add support for Node stream for request bodies.

**Comment by Shoukozumi** [comment]
Similar issue: #26667

**Comment by littledivy** [comment]
Closing as duplicate of https://github.com/denoland/deno/issues/26667. Let's track it there
