### ISSUE TITLE
Permission denied on running deno

### ISSUE THREAD

**Issue by Tembocs** [denoland/deno#2672]
I'm trying to run
```deno```
and get the following message
```bash: ~/deno/bin/deno: Permission denied```
this being the case I cannot do anything with deno, running
```deno types
deno info
deno --allow-run
deno --allow-read
```
gives the same message. What am I missing?
I am on Ubuntu 19.04 64x.

**Comment by bartlomieju** [comment]
Make sure you have proper permissions on Deno executable in `~/deno/bin/deno`

**Comment by Tembocs** [comment]
> Make sure you have proper permissions on Deno executable in `~/deno/bin/deno`

@bartlomieju, thanks. Did not think that could be the cause. Works!

**Comment by bartlomieju** [comment]
@Tembocs no problem, can we close this issue?

**Comment by ry** [comment]
The explicit command is
```
chmod u+x path/to/deno
```
closing...
