### ISSUE TITLE
Support other `workspace:` specifiers

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#26726]
Currently Deno supports `workspace:*` specifiers in `package.json`, but tools like pnpm also support
`workspace:^`, `workspace:~` and others.

See https://pnpm.io/workspaces#publishing-workspace-packages

Necessary changes would need to be applied around this code:
https://github.com/search?q=org%3Adenoland+PackageJsonDepValue%3A%3AWorkspace&type=code

**Comment by bartlomieju** [comment]
I did some digging into this and here's what I found:
1. Handling of `workspace:` specifiers in `package.json` is done here: https://github.com/denoland/deno_package_json/blob/bf59efc107b0d7191018e0d06ef1341f86fe6c1b/src/lib.rs#L346
2. The `workspace:` prefix is stripped and the remainder is passed to `VersionReq::parse_from_npm` from `deno_semver`: https://github.com/denoland/deno_semver/blob/6fba7fd973fc9cc77a54c1412d0e2a0fb357730f/src/npm.rs#L92
3. `*` or `x.y.z` are valid ranges in this context, but `~` and `^` are not
4. It appears that simply stripping `workspace:` is not good enough here and we should have a dedicated functionality in `deno_semver` to handle `workspace:` version constraints that will accept `~` and `^`, otherwise we'd have to alter the current parsing which would break other stuff, because `"mypackage": "^"` is not a valid range, but `"mypackage": "workspace:^"` is.

@dsherret do you agree here?

**Comment by dsherret** [comment]
It looks good, but I think we probably dont' need any changes in deno_semver. Probably it could just be handled in deno_package_json (I'm not sure though)
