### ISSUE TITLE
`deno doc --html` file `all_symbols.ts` - symbol descriptions are missing space when separated by newline

### ISSUE THREAD

**Issue by laurence-myers** [denoland/deno#26729]
Version: Deno 2.0.3

## Setup

File `example.ts`

```typescript
/**
 * Adds two numbers. Does not check if the numbers are NaN. Only
 * accurate if the numbers are integers less than Number.MAX_INTEGER.
 *
 * @example ```ts
 * import { add } from "./example.ts";
 *
 * add(1, 2);
 * ```
 */
export function add(first: number, second: number) {
  return first + second;
}
```

Run `deno docs --html --name="Example JSDoc wrapping issue" ./example.ts`

Example output:

[example_all_symbols_wrapping_issue.zip](https://github.com/user-attachments/files/17625280/example_all_symbols_wrapping_issue.zip)

## Expected

> Adds two numbers. Does not check if the numbers are NaN. **Only accurate** if the numbers are integers less than Number.MAX_INTEGER.

## Actual

> Adds two numbers. Does not check if the numbers are NaN. **Onlyaccurate** if the numbers are integers less than Number.MAX_INTEGER.

### JSDoc

![Screenshot 2024-11-05 110553](https://github.com/user-attachments/assets/709f44b4-7022-4d61-943b-801cfce0dcd3)

### `all_symbols.html`

Incorrect spacing:

![Screenshot 2024-11-05 110545](https://github.com/user-attachments/assets/a4d1c1f6-314f-4ace-b4d7-861542de532e)

### `~/add.html`

Correct spacing:

![Screenshot 2024-11-05 110827](https://github.com/user-attachments/assets/30a6980b-1e64-409f-bf5d-6c61fd037292)

**Comment by laurence-myers** [comment]
Looks like it also affects namespace docs.

![Screenshot 2024-11-05 113446](https://github.com/user-attachments/assets/0ee48b9c-2a0a-411a-8caa-e6540f70b874)

![Screenshot 2024-11-05 113400](https://github.com/user-attachments/assets/1a8c6474-1569-4215-8c65-175e69d62d5e)

![Screenshot 2024-11-05 113333](https://github.com/user-attachments/assets/90658959-8d1c-4779-bfe6-73b3e9c9676a)

**Comment by crowlKats** [comment]
This was fixed in the above linked PR, so closing
