### ISSUE TITLE
Nodemailer fails with Client network socket disconnected before secure TLS connection  was established

### ISSUE THREAD

**Issue by 0xkalle** [denoland/deno#26735]
Version: Deno 2.0.4

I am trying to use nodemailer within deno (2.0.4), and I am unable to figure out why it doesn't work. 

After my question on discord I assume, that there is a compatibility issue with node (https://discord.com/channels/684898665143206084/1301832635353530459)

I threw together the following small script to test:

```ts
import nodemailer from 'npm:nodemailer';

const testMail = async () => {
  const transporter = nodemailer.createTransport({
    host: "smtp.ethereal.email",
    port: 587,
    secure: false, // Use `true` for port 465, `false` for all other ports
    auth: {
      user: "tess3@ethereal.email",
      pass: "K9S6HKVEg8bDtVNnnr",
    },
    logger: true,
  });

  return transporter.verify();
}

testMail();
```

If you run this it will fail with `Client network socket disconnected before secure TLS connection 
was established` independent of the "secure" setting. If run with node, there is no problem.

Let me know if you need any further info.

Best,
Kalle

**Comment by bartlomieju** [comment]
This might be related to https://github.com/denoland/deno/pull/25470.

**Comment by 0xkalle** [comment]
This is fixed on canary.
