### ISSUE TITLE
Deno.env.toObject() fails in --allow-env=... run

### ISSUE THREAD

**Issue by behnam-oneschema** [denoland/deno#26738]
Version: Deno 2.0.4

It looks like a bug that when running a script with access to specific env-vars, the implementation for `Deno.env.toObject` fails to generate a mapping object for those specific keys.

And, if this behavior is intentional, then the error message is confusing, as it says `run again with the --allow-env flag` while the `--allow-env` flag is indeed set already.

## Repro

Having  `temp.ts`:
```
console.log(Deno.env.toObject())
```

We get:
```
≥ deno run --no-prompt --allow-env=KEY1,KEY2,KEY3 -- temp.ts
error: Uncaught (in promise) NotCapable: Requires env access, run again with the --allow-env flag
console.log(Deno.env.toObject())
                     ^
    at Object.toObject (ext:runtime/30_os.js:134:12)
    at file:///Users/behnam/code/.../temp.ts:1:22
```

**Comment by bartlomieju** [comment]
This is correct behavior - `Deno.env.toObject()` requires "full" env permission - ie. `--allow-env` without any arguments.

**Comment by behnam-oneschema** [comment]
Thanks, @bartlomieju. Quick follow up: is there any API to let the script see which env-vars it has access to?

**Comment by bartlomieju** [comment]
There's no API that will list env vars you have access to, but you can "query" for certain env vars using [`Deno.permissions.query`](https://docs.deno.com/api/deno/~/Deno.Permissions#method_query_0) or `querySync`.

**Comment by behnam-oneschema** [comment]
I see. Thanks again!

Fwiw, I think the query approach for specific env-vars is kind of equivalent to using `Deno.env.get(...)` in a try/catch block.

**Comment by bartlomieju** [comment]
That's correct
