### ISSUE TITLE
HTML formatter converts void elements to self closing tags

### ISSUE THREAD

**Issue by oscarotero** [denoland/deno#26748]
The HTML formatter of Deno converts HTML void elements (like `<br>`) to self closing tags (`<br />`). But self closing tags [don't exist in HTML](https://developer.mozilla.org/en-US/docs/Glossary/Void_element#self-closing_tags).

If I want to format this HTML code with `deno fmt`:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body>
    <p>Hello <br> world</p>
  </body>
</html>
```

The output code is:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  </head>
  <body>
    <p>Hello <br /> world</p>
  </body>
</html>
```

Is it possible to change this behavior and keep the void elements? I think it's cleaner and technically more correct.

cc @g-plane

**Comment by g-plane** [comment]
https://github.com/denoland/deno/blob/770ef1460085e1a1b706cc7f066e7b3ea5010eb0/cli/tools/fmt.rs#L1035
