### ISSUE TITLE
Relative imports with vite while using deno

### ISSUE THREAD

**Issue by josiahsrc** [denoland/deno#26773]
Version: Deno 2.0.5

I'm trying to set up a simple app that has three parts:

- react+vite frontend
- shared library
- backend

The shared library is intended to be imported by both the frontend and the backend. The backend works fine, but since the frontend is ran with vite, deno's import mapping doesn't resolve at runtime.

Here is a [simple project](https://github.com/josiahsrc/deno-vite-relative-imports) that replicates the issue. If you run `deno task vite` and open the web browser, you will see an import issue.

<img width="1130" alt="image" src="https://github.com/user-attachments/assets/80cdf87a-7a38-4a8f-9838-a47766763f89">

I am new to deno, is this sort of thing possible? Reporting this as a bug because it seems like an issue.

**Comment by nathanwhit** [comment]
Thanks for reporting! The issue is that you need to install the [deno vite plugin](https://github.com/denoland/deno-vite-plugin) to get vite to understand deno's imports.

To do that, in your vite-project run

```
deno install npm:@deno/vite-plugin
```

Then modify your `vite.config.ts` to add the plugin

```diff
  import { defineConfig } from "vite"
  import react from "@vitejs/plugin-react"
+ import deno from "@deno/vite-plugin"

  export default defineConfig({
+   plugins: [react(), deno()],
  })
```

Then the imports should work correctly

**Comment by josiahsrc** [comment]
That worked like a charm. This is so cool. Thank you!
