### ISSUE TITLE
`deno install` installs workspace members' npm dependencies, but not jsr dependencies?

### ISSUE THREAD

**Issue by kawmra** [denoland/deno#26772]
Version: Deno 2.0.4

In a monorepo setup, does `deno install` install the dependencies of workspace members?

I couldn't find any mention of this behavior in either the [`deno install` documentation](https://docs.deno.com/runtime/reference/cli/install/) or the [workspaces documentation](https://docs.deno.com/runtime/fundamentals/workspaces/), so I'm unsure if this is the expected behavior.

Consider the following monorepo structure:

```
.
├── deno.json
└── packages
    ├── bar
    │   └── deno.json
    └── foo
        └── deno.json
```

The contents of each file are as follows:

```
// deno.json
{
  "workspaces": ["packages/foo", "packages/bar"],
  "vendor": true,
  "nodeModulesDir": "auto"
}

// packages/foo/deno.json
{
  "imports": {
    "@std/encoding": "jsr:@std/encoding@^1.0.5"
  }
}

// packages/bar/deno.json
{
  "imports": {
    "chalk": "npm:chalk@^5.3.0"
  }
}
```

When I run `deno install` in the root directory, a `node_modules` folder is created there, and `chalk` is installed, but no `vendor` directory is created, and `@std/encoding` isn't installed.

Is this the expected behavior? In other words, is it by design that running `deno install` in the root directory installs npm dependencies from workspace members but does not install jsr dependencies?

**Comment by marvinhagemeister** [comment]
Yes, this is the expected behavior. By default, Deno uses a global cache directory where JSR + http dependencies are installed. That's why they are not showing up in your project folder. When you run code in your project, Deno will load those JSR dependencies from the global cache directory automatically.

If you want to have a project specific `vendor/` directory, you can set `"vendor": true` in your `deno.json`.

**Comment by kawmra** [comment]
@marvinhagemeister Thank you for your reply! Actually, I have already set "vendor": true in the deno.json configuration as shown above, but it looks like deno install only installs the npm modules.

After `deno install` in the root directory, it looks like:
```
.
├── deno.json
├── deno.lock
├── node_modules
│   └── chalk -> .deno/chalk@5.3.0/node_modules/chalk
└── packages
    ├── bar
    │   └── deno.json
    └── foo
        └── deno.json
```

**Comment by nathanwhit** [comment]
Thanks for reporting! I think I see the bug here.
