### ISSUE TITLE
Deno uses "node" condition instead of "deno" when "node" condition placed first in package.json exports resolution

### ISSUE THREAD

**Issue by panva** [denoland/deno#26789]
Refs: https://github.com/wintercg/runtime-keys/issues/5
Refs: https://github.com/wintercg/runtime-keys/issues/18

One can easily believe that the following exports condition examples mean "everything but node loads from the webapi dist".

```js
"exports": {
    "node": "./dist/node/index.js",
    "deno": "./dist/deno/index.js"
},
```

```js
"exports": {
    "node": "./dist/node/index.js",
    "default": "./dist/webapi/index.js"
},
```

Unfortunately Deno will load the "node" condition in both examples above despite there being a default or, even worse offense, an explicit "deno" one.

**Comment by panva** [comment]
This is not a https://github.com/denoland/deno/labels/question, I **know** how to work around this.

I am pointing out that this is bad and more importantly, not an expected, behaviour, especially in the first case when there is a Deno-specific export.

**Comment by panva** [comment]
As a module author I want to be able to write a module that exports "for node" and "for everything else" with two simple exports. And Deno (and also Bun's) behaviour is in the way of being able to do that.

**Comment by dsherret** [comment]
From my understanding of...

> Within the ["exports"](https://nodejs.org/api/packages.html#exports) object, key order is significant. During condition matching, earlier entries have higher priority and take precedence over later entries. The general rule is that conditions should be from most specific to least specific in object order.

...you need to do the following:

```
"exports": {
    "deno": "./dist/deno/index.js",
    "node": "./dist/node/index.js"
},
```

**Comment by dsherret** [comment]
> module that exports "for node" and "for everything else" with two simple exports

You can't do this without having a more specific exports condition above the "node" condition. The default conditions that Deno provides to the exports resolution algorithm is `["deno", "node", "imports"]`, so in order to not match the "node" condition you'll need to provide the "deno" condition first so that gets matched for Deno.
