### ISSUE TITLE
Type Declarations for `Iterator.from`

### ISSUE THREAD

**Issue by chances** [denoland/deno#26783]
The TypeScript team have resecently made some changes to the `Iterator` group of interfaces, protocols, and their related type definitions. For context, the TypeScript team is in the middle of making changes to the type declarations regarding iterators after TC39 recently landed changes for [iterator helpers](https://github.com/tc39/ecma262/pull/3395).

Either I'm confused and am using the types incorrectly, or the version of TypeScript being used by Deno is outdated.

My apologies if this is the incorrect repository.

## Reproduction

`index.ts`:

```ts
return Iterator.from([1, 2, 3]).map(x => x * 2);
```

`deno.json`:

```json
{
  "$schema": "https://raw.githubusercontent.com/denoland/deno/main/cli/schemas/config-file.v1.json",
  "exports": "./index.ts",
  "compilerOptions": {
    "lib": ["ESNext", "DOM.Iterable", "deno.window"]
  }
}
```

### Error reported by the Deno language server

```
ts: 'Iterator' only refers to a type, but is being used as a value here.
```

## Deno Runtime Versions

```
Deno 2.0.5 (stable, release, x86_64-pc-windows-msvc)
V8 12.9.202.13-rusty
TypeScript 5.6.2
```

## References

- https://github.com/microsoft/TypeScript/issues/54481
- https://github.com/microsoft/TypeScript/pull/58222
- https://github.com/microsoft/TypeScript/issues/59926

**Comment by petamoriken** [comment]
TypeScript 5.7 is in beta now and will be released on 2024-11-21.

Please see #26705

**Comment by dsherret** [comment]
Let's track this in https://github.com/denoland/deno/issues/26950
