### ISSUE TITLE
deno 2.0.5 compile executable almost 80 mb on windows 10

### ISSUE THREAD

**Issue by rahulmr** [denoland/deno#26792]
Below is the scenario 

deno version 2.0.5
cargo --version
cargo 1.79.0 (ffa9cf99a 2024-06-03)

1. `deno init hello`
2. `cd hello`
3. `deno compile main.ts`
4. `hello.exe` is created on windows and the file size is almost **80MB**
5. comparison with cargo - create a new app using `cargo new hello_cargo`
6. `cd hello_cargo`
7. `cargo build --release`
8. `hello_cargo.exe` is created file size is 140KB

![image](https://github.com/user-attachments/assets/41cf4e2a-72cf-494c-ae05-2d85fd7567fb)

Kindly suggest ways to reduce file size of single executable .exe size on windows.

**Comment by dsherret** [comment]
Follow https://github.com/denoland/deno/issues/22824 for work on reducing the binary size and we're slowly working on reducing the size of the binary.

> hello_cargo.exe is created file size is 140KB

That's a native app. It doesn't need to include a v8 runtime.

**Comment by rahulmr** [comment]
Thanks @dsherret , I had few queries on build windows GUI apps using Deno 2.0, where to get answers to such queries in general?

**Comment by dsherret** [comment]
Generally on discord https://discord.com/invite/deno or https://github.com/denoland/deno/discussions/categories/q-a
