### ISSUE TITLE
deno.json: Unsupported property 'target' in compilerOptions

### ISSUE THREAD

**Issue by BlasterM2A** [denoland/deno#26800]
Version: Deno 2.0.5

According to the doc [Configuring TypeScript](https://docs.deno.com/runtime/reference/ts_config_migration/), you can define the target property in compilerOptions, but neither the IDE nor Deno CLI recognize it as valid.

- #### IDE reports a warning indicating that it is not a valid property (since it is not defined in the [JSON schema](https://deno.land/x/deno/cli/schemas/config-file.v1.json)). 

<br>
<br>

<div align="center">
  <img width="500" alt="image" src="https://github.com/user-attachments/assets/572a96f2-215c-4d08-8203-243bcbb83a52">
  <p align="center"><i>JetBrains WebStorm</i></p>
</div>

<br>

<div align="center">
  <img width="400" alt="image" src="https://github.com/user-attachments/assets/56e8d676-280c-41c2-8346-568c88b7d458">
  <p align="center"><i>VSCode</i></p>
</div>

<br>
<br>

- #### Deno CLI says it's not supported and will be ignored

<div align="center">
  <img width="500" alt="image" src="https://github.com/user-attachments/assets/99c6b24a-c1fe-43a1-a57c-d806ab1b9cf8">
</div>

<br>
<br>
<br>

#### Note: deno.json config used in previous cases.
```json
{
  "$schema": "https://deno.land/x/deno/cli/schemas/config-file.v1.json",
  "vendor": true,
  "tasks": {
    "fmt": "deno task dprint fmt",
    "fmt:check": "deno task dprint check"
  },
  "nodeModulesDir": "auto",
  "lint": {
    "rules": {
      "tags": [
        "recommended"
      ],
      "include": [
        "no-non-null-assertion"
      ]
    }
  },
  "compilerOptions": {
    "target": "esnext",
    "jsx": "react-jsxdev",
    "jsxImportSource": "react"
  }
}
```

**Comment by BlackAsLight** [comment]
On that link you listed, it has the target property in a few examples, but it doesn't say a single word anywhere about it. Moreover on that page it has a table listing the valid compiler options and target isn't on that list.

**Comment by BlasterM2A** [comment]
> On that link you listed, it has the target property in a few examples, but it doesn't say a single word anywhere about it. Moreover on that page it has a table listing the valid compiler options and target isn't on that list.

The reference to "target" and "esnext" is by no means residual in that documentation, and the use of examples that aren't reproducible or banal causes confusion. The comment "For a complete list of compiler options and how they affect TypeScript, see the TypeScript Manual" also suggests that other properties are supported.

**Comment by BlackAsLight** [comment]
> The comment "For a complete list of compiler options and how they affect TypeScript, see the TypeScript Manual" also suggests that other properties are supported.

I can see how that comment can be confusing, but I believe it is essentially saying TypeScript supports more options, but Deno isn't exposing all those options in the version it ships.

**Comment by BlasterM2A** [comment]
> > The comment "For a complete list of compiler options and how they affect TypeScript, see the TypeScript Manual" also suggests that other properties are supported.
> 
> I can see how that comment can be confusing, but I believe it is essentially saying TypeScript supports more options, but Deno isn't exposing all those options in the version it ships.

Got it. I was having issues with a third-party library related to the use of import.meta, which led me to review the documentation and try to reproduce the examples.

I'm closing this ticket since the reported issue isn't a Deno CLI bug.

**Comment by BlasterM2A** [comment]
> > The comment "For a complete list of compiler options and how they affect TypeScript, see the TypeScript Manual" also suggests that other properties are supported.
> 
> I can see how that comment can be confusing, but I believe it is essentially saying TypeScript supports more options, but Deno isn't exposing all those options in the version it ships.

Got it. I was having issues with a third-party library related to the use of import.meta, which led me to review the documentation and try to reproduce the examples.

I'm closing this ticket since the reported issue isn't a Deno CLI bug.
