### ISSUE TITLE
White outline on deno the dino for dark mode

### ISSUE THREAD

**Issue by jorsi** [denoland/deno#2680]
Minor transparency issue on the deno gif when viewing deno.land with the Dark Mode preference on a Macbook.

<img width="373" alt="Screen Shot 2019-07-24 at 12 13 48 AM" src="https://user-images.githubusercontent.com/7156655/61764641-eedb3d80-ada7-11e9-914e-a26952d7775a.png">

**Comment by ry** [comment]
cc @hashrock

**Comment by kevinkassimo** [comment]
Can we move this issue to https://github.com/denolib/animated-deno-logo ?

**Comment by jorsi** [comment]
Done. https://github.com/denolib/animated-deno-logo/issues/2
