### ISSUE TITLE
Separate $DENO_CACHE environment variable

### ISSUE THREAD

**Issue by nayeemrmn** [denoland/deno#2681]
In #2630 there was some confusion about what $DENO_DIR is supposed to be set to. How about letting $DENO_DIR be exclusively deno's installation directory and have $DENO_CACHE point to the cache directory?

@ry expressed that he didn't want the cache in a different location, so $DENO_CACHE could fallback to $DENO_DIR. This would mean everything behaves the same way without $DENO_CACHE set.

It would _optionally_ be set in the user's profile to wherever they'd prefer, or manipulated at runtime (for bundling dependencies into source control or otherwise) like this:
```Makefile
fetch:
	DENO_CACHE=./deno_cache deno fetch ./src/main.ts

run:
	DENO_CACHE=./deno_cache deno ./src/main.ts
```
where ./deno_cache/deps could be checked in. This looks a lot more sane than if $DENO_DIR were used instead like it would need to be now.

**Comment by nayeem-rahman** [comment]
> $DENO_CACHE could fallback to $DENO_DIR.

I said this because because this would make for a small and backwards compatible change, but honestly I'm against the cache being put into the installation directory under any circumstances. If platform dependence was the problem then maybe something like ~/.deno_cache could be the default?

**Comment by severen** [comment]
*Please* do not default to shoving it in $HOME. Be a good citizen and store files under the appropriate platform specific locations (e.g. $XDG_CACHE_HOME on Linux for cache files).

Old software might do it, but it's incredibly sad and frustrating to have new programs continue the same pattern of behavior.

**Comment by nayeemrmn** [comment]
Upon delving further, I guess `$DENO_DIR` is intended for any per-invocation runtime data written by Deno (which happens to just be the cache at the moment). The name makes more sense to me now. The installation directory should use a different variable instead.

@severen FYI, `$DENO_DIR` does already fallback to a platform specific cache directory 👍. I was responding to something tangential from somewhere else and confusing the issue, it's not important.
