### ISSUE TITLE
deno fmt: Respect .editorconfig file

### ISSUE THREAD

**Issue by Aloso** [denoland/deno#26820]
EditorConfig is a standard to configure formatting options (like indentation and line endings), and is widely supported by editors.

Prettier [supports EditorConfig out of the box](https://prettier.io/docs/en/configuration.html#editorconfig): When prettier finds a .editorconfig file, it parses the file uses it as its defaults. `deno fmt` should do the same.

**Comment by dsherret** [comment]
Duplicates https://github.com/denoland/deno/issues/14717
