### ISSUE TITLE
how to set permissions for deno deploy?

### ISSUE THREAD

**Issue by gustawdaniel** [denoland/deno#26830]
After deployment I am getting

```
PermissionDenied: Requires write access to "./static/voice/pl/0.wav", run again with the --allow-write flag
```

of course locally i running by

```
  "tasks": {
    "dev": "deno serve --allow-write --allow-net --watch -R main.ts"
  },
```

and it works.

But what command is called when deno start in `deno deploy` cloud?

Docs of permissions do not mention about deno deploy, and in deno deploy web console I can't find permissions settings.

**Comment by bartlomieju** [comment]
Deno Deploy has a read-only file system and it's not possible to write files there. The permission in Deploy are implied - you have access to "read", "env" and "net" permissions as well as some "sys" permissions - though most of "sys" values are dummy values.

**Comment by gustawdaniel** [comment]
Thanks. I solved building 2 adapters:
- file system 
- S3

And on production just switching to S3.

I suggest you mention these constraints somewhere in docs but this issue can be closed.
