### ISSUE TITLE
Add --importmap flag to `deno fetch` command

### ISSUE THREAD

**Issue by johnsonjo4531** [denoland/deno#2685]
The `deno fetch` command should allow the `--importmap` flag. This will allow fetching dependencies for modules which use non-relative imports. 

As an example I was able to download the [lit-element](https://lit-element.polymer-project.org/)'s module (lit-element is a browser js framework which encourages es2015 module use and has only one dependency lit-html) and grab the dependency tree using `deno`, but was unable to do it with `deno fetch`. The following was what worked using the deno command (on platform Mac) although it threw a TypeError after it built it when it tried to run it:

```bash
DENO_DIR=`pwd`/deno-modules/ deno --importmap=importmap.json https://unpkg.com/lit-element@2.2.1/lit-element.js
```

with the following import map

```json
{
    "imports": {
        "lit-html": "https://unpkg.com/lit-html@1.1.1/lit-html.js",
        "lit-html/": "https://unpkg.com/lit-html@1.1.1/"
    }
}
```

Whereas the deno fetch doesn't seem to take import maps. So it fails when trying to get the dependency tree and hitting a non-relative import to `lit-html`.

**Comment by nayeem-rahman** [comment]
I see what happened. Okay `--importmap` is universal across all subcommands and is written before the subcommand as the help text suggests. This will work:
```
DENO_DIR=deno_modules deno --importmap=importmap.json fetch https://unpkg.com/lit-element@2.2.1/lit-element.js
```
The inconsistency here is that `deno run` also supports it as a subcommand-specific option while the other subcommands don't. This should be removed.

**Comment by bartlomieju** [comment]
> I see what happened. Okay `--importmap` is universal across all subcommands and is written before the subcommand as the help text suggests. This will work:

That's not true. `--importmap` is only exposed to `deno <script>` and `deno run <script>`. I just opened a PR that makes it a global flag.

**Comment by nayeem-rahman** [comment]
I just ran the code I snippeted and it does. You have to write it _before_ the subcommand.

**Comment by bartlomieju** [comment]
@nayeem-rahman I just double checked, you're right. 🤔 though it still makes sense to make this flag global so commands can be written as:
```
deno fetch -r --importmap importmap.json https://unpkg.com/lit-element@2.2.1/lit-element.js
```

**Comment by nayeem-rahman** [comment]
Makes sense. I guess removing it from run would be unnecessarily restrictive vs adding it to the others.
