### ISSUE TITLE
Import map is not used to lookup the entry point script

### ISSUE THREAD

**Issue by nayeem-rahman** [denoland/deno#2688]
Not important but I would expect this to work.

**Comment by bartlomieju** [comment]
We already discussed it a little bit in one of PRs. For reference here's an issue I opened in import maps repo: https://github.com/WICG/import-maps/issues/157

In Deno you specify entry point by providing URL or "relative" path to the script. It is less strict than specifiers in script (which require you to use `/`, `./` or `../` for relative scripts). So ultimately it is a URL, and import maps shouldn't be applied to URL, but to script specifiers. 

Still, this should be discussed.

**Comment by nayeem-rahman** [comment]
Ah, this is definitely a duplicate.
