### ISSUE TITLE
`deno install --allow-scripts` indefinitely stuck on `- esbuild@0.19.12: running 'postinstall' script`

### ISSUE THREAD

**Issue by Milner39** [denoland/deno#26904]
Version: Deno 2.0.6

Hello, i'm trying to migrate a SvelteKit project from Node to Deno but I've found some strange behaviour when installing dependencies that prevents `deno install` from completing. 

`deno.json`:
```json
{
    "tasks": {
        "web:dev": "vite dev --config ./vite.config.mts",
	"web:build": "vite build --config ./vite.config.mts",
	"web:preview": "vite preview --config ./vite.config.mts",
	"web:serve": "node -r dotenv/config ./build"
    },
    "imports": {
        "@std/fs": "jsr:@std/fs@1.0.5",
        "@std/path": "jsr:@std/path@1.0.8",

        "@sveltejs/adapter-node": "npm:@sveltejs/adapter-node@5.0.1",
	"@sveltejs/kit": "npm:@sveltejs/kit@2.0.0",
	"@sveltejs/vite-plugin-svelte": "npm:@sveltejs/vite-plugin-svelte@3.0.0",
	"svelte": "npm:svelte@4.2.7",
	"vite": "npm:vite@5.0.3",
        "dotenv": "npm:dotenv@16.4.5"
    },
    "nodeModulesDir": "auto"
}
```

output:
```bash
deno install --allow-scripts
Initialize ⢿ [05:33] 84/85
 - esbuild@0.19.12: running 'postinstall' script
```

No matter how long I leave it, is just gets stuck.
Sometimes closing the terminal and restarting the command works but very rarely.

**Comment by teddybee** [comment]
Same issue here. I stopped it after an hour.
 esbuild@0.19.12: running 'postinstall' script

**Comment by bartlomieju** [comment]
Does esbuild actually work correctly if you stop the install script? Running it for esbuild shouldn't really be necessary, because esbuild ships with prebuilt binaries.
