### ISSUE TITLE
`deno lint` shows information that `deno lint --json` does not

### ISSUE THREAD

**Issue by skeithtan** [denoland/deno#26930]
Here's what I get with `deno lint` when all files conform:
```
$ deno lint
Checked 73 files

```

Here's what I get with `deno lint --json`:
```
$ deno lint --json
{
  "version": 1,
  "diagnostics": [],
  "errors": []
}

```

It's missing the number of files checked. I need this information to feed it into our reporter. Now I have to run `deno lint` and make a custom parser to get this information.

The JSON output should have all the information that `deno lint` has.

**Comment by bartlomieju** [comment]
Sounds reasonable, would you like to open a PR? We can include it in Deno v2.1 going out tomorrow.

**Comment by skeithtan** [comment]
@bartlomieju I would have if it were in TS, but I'm not familiar with Rust at all. It would be nice to see it going out tomorrow, though :)

**Comment by dsherret** [comment]
Maybe it should output the files checked instead?

**Comment by skeithtan** [comment]
@bartlomieju @dsherret I created a PR here that outputs the files checked instead: https://github.com/denoland/deno/pull/26936

Does that work for you?
