### ISSUE TITLE
Official Arch Linux package out of date

### ISSUE THREAD

**Issue by tsndr** [denoland/deno#26933]
Version: Deno 1.46.3-2

Hi, I just wanted to let you know that the `deno` package in the official Arch Linux repository is outdated and still on version `1.46.3-2`.

https://archlinux.org/packages/extra/x86_64/deno/

**Comment by uncomfyhalomacro** [comment]
> Version: Deno 1.46.3-2
> 
> Hi, I just wanted to let you know that the `deno` package in the official Arch Linux repository is outdated and still on version `1.46.3-2`.
> 
> https://archlinux.org/packages/extra/x86_64/deno/

You should email the packager. I think it shouldn't be filed here since *I think* it is not the sole responsibility of the Deno team to update the versions for other distros.

**Comment by tsndr** [comment]
I never suggested that the deno team is responsible, my intention was just to make you aware that the official Arch Linux package is outdated, which is probably being used my more people than just me.

In the meantime I requested an account to their GitLab and nudged an outstanding PR so it get's merged, now we're up to version `2.0.0-1`, which still isn't the latest, but at least we're up to version 2 now.
