### ISSUE TITLE
Formatter messes up indentation, even its own

### ISSUE THREAD

**Issue by Stokestack** [denoland/deno#26956]
deno 2.0.6 (stable, release, aarch64-apple-darwin)
v8 12.9.202.13-rusty
typescript 5.6.2

I'm using the Deno plug-in for VS Code. When cutting and pasting code, something is messing up the indentation of function bodies, adding an extra level. Also, when pressing Return after a function signature, the first line is similarly indented an extra level... despite the "format selection" command previously having put the rest of the body at the correct position. Screen grab attached.

Here's what I have for formatting in deno.json:

```
  "fmt": {
    "useTabs": true,
    "lineWidth": 120,
    "indentWidth": 4,
    "semiColons": true,
    "proseWrap": "always"
  },
```

https://github.com/user-attachments/assets/14999ab5-bb15-4af2-aa56-02aa06a3a293

**Comment by dsherret** [comment]
Are you sure Deno is configured as your formatter? I don't think "format selection" is implemented. Do you have format on save implemented? What's causing the format to occur? It kind of looks like vscode from the video.

**Comment by Stokestack** [comment]
Thanks for the follow-up. It's not happening on saving, so I don't think that's related. "Format selection" is doing stuff, so I don't know what you mean by not implemented.

I'm using normal cut & paste keys. On Mac, that's Command-X, Command-V.

**Comment by dsherret** [comment]
I think that's just vscode then. It probably happens with the deno extension being disabled.

**Comment by Stokestack** [comment]
It's not disabled. What do you mean?

**Comment by dsherret** [comment]
I mean my guess is if you disable the deno vscode extension then you'll probably still see the behaviour you describe.

**Comment by Stokestack** [comment]
Thanks! And, in fact that's true. I wonder what is messing it up. I don't find any relevant option in the VS Code settings.

Anyway, closing this.
