### ISSUE TITLE
`deno fmt` removes trailing commas in function parameters and calls

### ISSUE THREAD

**Issue by greentore** [denoland/deno#26951]
Currently `deno fmt`  inserts / preserves trailing commas only where they were allowed in es5, but prettier has been adding them everywhere since [v3.0.0](https://prettier.io/docs/en/options#trailing-commas) by default. It's a bit troublesome for me as I'm trying to migrate some of my projects from node + prettier to deno and editing a file with long function calls results in unnecessary diffs.

**Comment by dsherret** [comment]
> Currently deno fmt inserts / preserves trailing commas only where they were allowed in es5, but prettier has been adding them everywhere since [v3.0.0](https://prettier.io/docs/en/options#trailing-commas) by default.

Can you provide an example? It's been leaving them there for many years.

**Comment by greentore** [comment]
Yes, it was misconfigured workspace. Sorry for opening a bogus issue.

**Comment by dsherret** [comment]
That's ok! It happens.
