### ISSUE TITLE
imports from dynamic import with static string are `any`

### ISSUE THREAD

**Issue by scarf005** [denoland/deno#26965]
## To Reproduce

```js
// @ts-check

const preact = "preact@10.24.3"
const { h, render } = await import(`https://esm.sh/${preact}`)
```

## Expected Behavior

dynamic import using constant string literals are fully typed because they can be statically inferred.

## Actual

![image](https://github.com/user-attachments/assets/9236a36c-a195-40bd-adb5-7f99c9be87d0)

Version: Deno 2.1.0

**Comment by dsherret** [comment]
This is TypeScript behaviour and I don't believe they inline constants into strings like this. Going to close this because it's out of scope for us.
