### ISSUE TITLE
rustfmt is not correctly wrapping at 80 columns

### ISSUE THREAD

**Issue by ry** [denoland/deno#2699]
https://github.com/denoland/deno/pull/2683/files#r309166774
https://github.com/denoland/deno/blob/695c4a22ede1a0448ba4c9193c1272070da1b5ab/cli/file_fetcher.rs#L33

Seems we need `wrap_comments = true` https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#wrap_comments

Additionally we need to upgrade our rustfmt binaries... We are using `rustfmt 0.99.1-stable (da17b689 2018-08-04)`

**Comment by bartlomieju** [comment]
Lines are also not wrapped for regular code:
https://github.com/denoland/deno/pull/2683/files/695c4a22ede1a0448ba4c9193c1272070da1b5ab#diff-650251ac2d73d4c1e65f0808a16e2539R47

**Comment by kitsonk** [comment]
Here is the issue tracking stability on `wrap_comments`: https://github.com/rust-lang/rustfmt/issues/3347  It hasn't changed in over a year.
