### ISSUE TITLE
`deno test --filter` doesn't seem working for step names

### ISSUE THREAD

**Issue by kt3k** [denoland/deno#26997]
Assume we have `a.js`, like:

```js
Deno.test("1", async (t) => {
  await t.step("2", () => {
  });
  await t.step("3", () => {
  });
});
```

If we filter with `2`, then it can't find any test case:

```
$ deno test --filter=2 a.js

ok | 0 passed | 0 failed | 1 filtered out (1ms)
```

Is this by design, or should this execute subtest of matching name?

related: https://github.com/denoland/std/issues/6063

**Comment by dsherret** [comment]
Yeah, it's by design. This was one of my main arguments against the test step API when we landed it 😅

**Comment by kt3k** [comment]
Ah, ok. It's by design because we don't know the step names before executing each test case.

I created this issue because of the issue in `std/testing/bdd` https://github.com/denoland/std/issues/6063, but that might be addressed by mapping all describe/it cases to `Deno.test`, not to `t.step`.
