### ISSUE TITLE
@std/http/file-server does not support --include in compile

### ISSUE THREAD

**Issue by begoon** [denoland/deno#27006]
Version: Deno 2.1.0

```typescript
import { serveDir } from "jsr:@std/http/file-server";
Deno.serve((req: Request) => serveDir(req, { fsRoot: "./files" }));
```

```console
deno compile -A --include files -o ./exe main.ts
```

When running `./exe`, if the `./files` is renamed/deleted/etc., the server cannot serve files anymore because it looks at the file system, not the embedded files (from `--include files`).

**Comment by dsherret** [comment]
Does it work with `import.meta.dirname`?

```
fsRoot: import.meta.dirname + "/files"
```

**Comment by dsherret** [comment]
Yeah, that's what I get. It gives 404 for non-existent files at least. There seems to be some small bug in the file system implementation.

**Comment by begoon** [comment]
It would be helpful to document how exactly or on what level of the API the embedded files are injected. What API calls support embedding?

**Comment by dsherret** [comment]
It's at the JS application's view of the file system. It creates a fake folder that points at the embedded data (the fake folder is seen via `import.meta.dirname`). All read operations should work, but not write within that folder. Also, passing these paths to other executables won't work.
