### ISSUE TITLE
lsp: suspicious unwrap on line 88 at `resolvers/node/package_json.rs`

### ISSUE THREAD

**Issue by uncomfyhalomacro** [denoland/deno#27002]
Version: Deno 2.1.0

The following line of code should be handled or given a default.
https://github.com/denoland/deno/blob/5ca47ee97a06c1b76bbdd58b50efd7016da2b020/resolvers/node/package_json.rs#L88

A user has reported in https://canary.discord.com/channels/684898665143206084/684898665151594506/1309468119009595534 and it seems that if a `package.json` does not have a parent directory even though it has as shown [here](https://canary.discord.com/channels/684898665143206084/684898665151594506/1309486843271839764).

I believe the solution for this is to `.canonicalize()` it first before calling `.parent()`.

My proposed code looks like this for line 88.

```rust
let file_path = file_path.canonicalize().unwrap_or(file_path);
let parent_dir = file_path.parent().unwrap_or(&Path::new("/"));
```

The reason for the `&Path::new("/")` is it's highly likely that if `.parent()` returns a `None` value, it might be the `/` root directory. We can always ensure as well by just using [`has_root`](https://doc.rust-lang.org/std/path/struct.Path.html#method.has_root) if we are wary with such an assumption.

**Comment by dsherret** [comment]
Thanks, but would you be able to update the issue or create a new issue that focuses on the actual bug? It's better to start from there then work towards a fix.

**Comment by uncomfyhalomacro** [comment]
Closing as I need more info before jumping to conclusions.
