### ISSUE TITLE
In TypeScript, private property can be accessible from outside

### ISSUE THREAD

**Issue by ACAlexChen** [denoland/deno#27019]
Version: Deno 2.1.1
```
class A {
  private a = 1
  public b = 2
}

const a = new A()
console.log(a.a) // 1
console.log(a.b) // 2
```
Property 'a' should be only accessible within class 'A'
But when I run this code with Deno, still can be accessible from outside

**Comment by nathanwhit** [comment]
Property privacy in typescript is enforced [only in typechecking](https://www.typescriptlang.org/docs/handbook/2/classes.html#caveats), it has no runtime effect. If you want truly private properties, you probably want [this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_properties). Those are enforced both when typechecking and on execution

**Comment by dsherret** [comment]
See right hand side of screenshot of JavaScript output.

![image](https://github.com/user-attachments/assets/21d63216-38ed-4faa-b635-cb6e08c4e0d0)

What you want to use is JS private properties (see `class B` above using `#`): https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_properties
