### ISSUE TITLE
Issues with `deno outdated`

### ISSUE THREAD

**Issue by kuchta** [denoland/deno#27025]
Version: Deno 2.1.0

`deno outdated` is very useful command, but either it's documentation could be improved or it's behavior, because right now, it's a bit confusing.

Running `deno outdated --latest` errors with
```
error: the following required arguments were not provided:
  --update
```
But my understanding is `--latest` is basically counterpart of `--compatible` flag that can be run without `--update` flag.

The documentation for --compatible is also a bit confusing, as it often expands the selection, not narrows it as the *only* word suggests.
`--compatible  Only output versions that satisfy semver requirements`

Running `outdated` with any selection modifier without `--update` flag is in it's current implementation quite important, because `--update` don't ask for any confirmation, which it probably should.

Anyway, I'd rather call this command `update` since users are used to it from other package managers and get rid of the `--update` flag and just ask the user for confirmation or introduce --print flag for just printing.

**Comment by nathanwhit** [comment]
> But my understanding is --latest is basically counterpart of --compatible flag that can be run without --update flag.

Ah this is a bit of a misunderstanding, `deno outdated` without `--update` already displays dependencies with new latest versions. In other words, adding `--latest` wouldn't do anything, as it's already the default behavior.

That being said, it's true that it doesn't need to be an error. I'll open a PR to allow it.

> The documentation for --compatible is also a bit confusing, as it often expands the selection, not narrows it as the only word suggests.

It _should_ only narrow the selection, if it expands the selection that's a bug. Do you have an example of where that happens? I'm aware of #27038 (where pre release versions are involved), but is there another case you've encountered?

> Running outdated with any selection modifier without --update flag is in it's current implementation quite important, because --update don't ask for any confirmation, which it probably should.

Most other tools I'm aware of don't ask for confirmation when updating. Instead, the plan is to add an `--interactive` flag in Deno 2.2 to allow interactively selecting which versions to update. This is also what most other tools do.

> Anyway, I'd rather call this command update since users are used to it from other package managers and get rid of the --update flag and just ask the user for confirmation or introduce --print flag for just printing.

That was an idea we had considered, but the consensus was that `deno update` would be confusing since it appears similar to `deno upgrade` (but would behave very differently). But I do understand that it may be different from what people are used to

**Comment by kuchta** [comment]
> Ah this is a bit of a misunderstanding, `deno outdated` without `--update` already displays dependencies with new latest versions. In other words, adding `--latest` wouldn't do anything, as it's already the default behavior.

Ah okay, makes sense...
 
> > The documentation for --compatible is also a bit confusing, as it often expands the selection, not narrows it as the only word suggests.
> 
> It _should_ only narrow the selection, if it expands the selection that's a bug. Do you have an example of where that happens? I'm aware of #27038 (where pre release versions are involved), but is there another case you've encountered?

Yes, it actually happens with pre-release versions...

> Most other tools I'm aware of don't ask for confirmation when updating. Instead, the plan is to add an `--interactive` flag in Deno 2.2 to allow interactively selecting which versions to update. This is also what most other tools do.

That would probably also do...
> 
> > Anyway, I'd rather call this command update since users are used to it from other package managers and get rid of the --update flag and just ask the user for confirmation or introduce --print flag for just printing.
> 
> That was an idea we had considered, but the consensus was that `deno update` would be confusing since it appears similar to `deno upgrade` (but would behave very differently). But I do understand that it may be different from what people are used to

Most other tools I'm aware of (apt-get, HomeBrew) also has this distinction, but I understand that you may not want to do that. It would probably be best if `deno upgrade` was changed to something that could manage multiple versions and call it that way...

**Comment by kuchta** [comment]
I've found another confusing behavior of `deno outdated`

```
: deno outdated                   
```
```
: deno outdated --compatible
┌─────────────┬────────────────┬────────────────┬─────────┐
│ Package     │ Current        │ Update         │ Latest  │
├─────────────┼────────────────┼────────────────┼─────────┤
│ npm:daisyui │ 5.0.0-alpha.47 │ 5.0.0-alpha.48 │ 4.12.22 │
└─────────────┴────────────────┴────────────────┴─────────┘

Run deno outdated --update to update to the latest compatible versions,
or deno outdated --help for more information.
```
```
: deno outdated --compatible -u
error: the argument '--compatible' cannot be used with '--update'

Usage: deno outdated --compatible [filters]...
```
```
: deno outdated  -u
Updated 1 dependency:
 - npm:daisyui 5.0.0-alpha.47 -> 5.0.0-alpha.48
```

I would expect `deno outdated -u` to do nothing if `deno outdated` outputs nothing and `deno outdated --compatible -u` to update daisyui to the update version outputed by `deno outdated --compatible` but `-u` doesn't work with `--compatible`
