### ISSUE TITLE
Deno compile – doesn't work with unstable sloppy imports

### ISSUE THREAD

**Issue by lino-levan** [denoland/deno#27031]
I think it would be helpful for adoption if deno compile could work with unstable sloppy imports. Right now it "compiles successfully" and then crashes are runtime, which isn't great.

**Comment by dsherret** [comment]
Duplicate of https://github.com/denoland/deno/issues/26102

> Right now it "compiles successfully" and then crashes are runtime, which isn't great.

There is a warning at the moment https://github.com/denoland/deno/blob/12b377247be2b74155ded3a678ff2996ef3d7c9f/cli/tools/compile.rs#L45-L51

**Comment by lino-levan** [comment]
Right, I missed that in my issue search. Thanks for pointing me in the right direction.
