### ISSUE TITLE
fmt(svelte): error with types in snippet 

### ISSUE THREAD

**Issue by sylc** [denoland/deno#27030]
Version: Deno 2.1.1

```svelte
{#snippet snip(num: number)}
  <div>Test {num}</div>
{/snippet}
```

```txt
deno fmt --unstable-component
Error formatting: C:\Temp\deno-init\test.svelte
   Expected ';', '}' or <eof> at file:///C:/Temp/deno-init/test.svelte.tsx:1:29

         <>{snip(num: number)}</>
                              ~
Checked 4 files
```

without the `: number ` it works fine.

**Comment by toodeluna** [comment]
I did some research and found that this is due an issue in a library used by Deno called `markup_fmt` so I made a [separate issue](https://github.com/g-plane/markup_fmt/issues/88) on their GitHub repo for this. Once this issue gets fixed, Deno can just upgrade the version and this issue should be fixed.
