### ISSUE TITLE
Internal - Lint rule for unused `.out` files in spec tests

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#27070]
Seems we have a bunch of `.out` files that aren't used in spec tests.

**Comment by crowlKats** [comment]
@dsherret do you know of any specific .out file that is unused?

**Comment by dsherret** [comment]
There's some examples of removals in this PR: https://github.com/denoland/deno/pull/27071/files

**Comment by crowlKats** [comment]
Fixed in #27078
