### ISSUE TITLE
Order of CLI flags

### ISSUE THREAD

**Issue by ConsoleTVs** [denoland/deno#2708]
The order of the CLI flags should not be of importance. Check this example

![image](https://user-images.githubusercontent.com/6124435/62263509-c9d87180-b41c-11e9-8da9-b683316e0ad7.png)

Shouldn't

```
 deno test.ts --config tsconfig.json
```

be the same as

```
deno --config tsconfig.json test.ts
```

or maybe I'm wrong?

**Comment by kitsonk** [comment]
We have to have some sort of demarkation between what is to be consumed by Deno, and what should be made available for the script.  Currently it is assumed anything after the main script is to be consumed by the script, anything before the main script is to be consumed by Deno.

The only other solution is to introduce something like `--` to make that demarkation, which just seems worse than the current solution.

**Comment by ConsoleTVs** [comment]
Uhh, I see, makes sense tbh, will close this.
