### ISSUE TITLE
Deno compile's all workspaces in monorepo

### ISSUE THREAD

**Issue by xpr0gamers** [denoland/deno#27142]
Hello, 

I have a monorepo with one root "deno.json" that includes:
`  "workspace": [
    "./packages/server",
    "./packages/installer-updater"
  ],` 

For test purpose, in the workspace "installer-updater" i have zero dependencies.
Only one statement `console.log('Deno is incredible')` in the main file.
Then i build one single executable for the workspace "installer-updater" via: 
"deno compile --allow-all --output=./build/installer-updater --node-modules-dir=none  ./src/program.ts"

The compiled size of executable is now over 100mb. 
Then i remove other workspaces in the root "deno.json" file or with the additon "--no config" in the deno compile statement, everything looks correct. 
Is this the desired behaviour?

Version: Deno 2.1.1

**Comment by marvinhagemeister** [comment]
> Is this the desired behaviour?

Can you clarify what you want to know? Are you wondering if the size is correct? Are you wondering if a `deno.json` can be omitted? Are you wondering about the behaviour of `--no-config? Or maybe something else? Adding more details as to what you want to know would be appreciated.

**Comment by xpr0gamers** [comment]
Thanks for the quick reply @marvinhagemeister. 
The behaviour is is no longer reproducible by me.
