### ISSUE TITLE
Cannot find namespace 'Temporal'.deno-ts(2503)

### ISSUE THREAD

**Issue by ooker777** [denoland/deno#27145]
My code:
```ts
const a: Temporal.PlainDate = new Temporal.PlainDate(2024, 2, 1)
```
This returns this error:
```
Cannot find namespace 'Temporal'.deno-ts(2503)
```
Version: Deno 2.1.2

**Comment by bartlomieju** [comment]
Do you have `deno.json` and customize `compilerOptions` settings?

**Comment by ooker777** [comment]
even delete the deno.json the error is still there

**Comment by bartlomieju** [comment]
Can you shot the output of the "Deno Language Server" pane in "Output" tab of VSCode?

**Comment by ooker777** [comment]
On my test project (no `deno.json`):
```
Warning: The Deno language server is explicitly disabled for every directory. If this is not intentional, check your user and workspace settings for entries like `"deno.enable": false` and `"deno.enablePaths": []`.
```
On my current project:
```
Starting Deno language server...
  version: 2.1.2 (release, x86_64-pc-windows-msvc)
  executable: C:\Users\ganuo\AppData\Local\Microsoft\WinGet\Links\deno.EXE
Connected to "Visual Studio Code" 1.95.1
Enabling import suggestions for: https://deno.land
Hit the language server document preload limit of 1000 file system entries. You may want to use the "deno.enablePaths" configuration setting to only have Deno partially enable a workspace or increase the limit via "deno.documentPreloadLimit". In cases where Deno ends up using too much memory, you may want to lower the limit.
Refreshing configuration tree...
  Resolved Deno configuration file: "file:///D:/QC%20supplements/Code/Apps/X%C3%A2y%20nh%C3%A2n%20hi%E1%BB%87u%20t%E1%BB%B1%20%C4%91%E1%BB%99ng/deno.json"
  Resolved lockfile: "file:///D:/QC%20supplements/Code/Apps/X%C3%A2y%20nh%C3%A2n%20hi%E1%BB%87u%20t%E1%BB%B1%20%C4%91%E1%BB%99ng/deno.lock"
Server ready.
successfully cancelled request with ID: 18
```

**Comment by bartlomieju** [comment]
The first message is the clue here - you have Deno extension disabled completely. Open command pallete (Cmd + Shift + P), select "Open User Settings (JSON)" and look for `deno.enable` - remove the line and everything should go back to normal.

**Comment by ooker777** [comment]
I'm not sure why `deno.enable` is set to `false`, but comment it out doesn't help. The new output:
```
Starting Deno language server...
  version: 2.1.2 (release, x86_64-pc-windows-msvc)
  executable: C:\Users\ganuo\AppData\Local\Microsoft\WinGet\Links\deno.EXE
Connected to "Visual Studio Code" 1.95.1
Enabling import suggestions for: https://deno.land
Refreshing configuration tree...
Server ready.
successfully cancelled request with ID: 7
```
I notice that the error now doesn't come from deno-ts any more:
```
Cannot find namespace 'Temporal'.ts(2503)
```

**Comment by bartlomieju** [comment]
That error means that Deno extension is still not enabled in your current workspace - make sure you see something like "Deno 2.1.2" in the bottom right corner on your VSCode window. You can force to enable Deno by going to command pallete and selecting "Deno: Enable".

**Comment by ooker777** [comment]
Hmm, what is the role of the [`lib` property](https://docs.deno.com/runtime/reference/ts_config_migration/#using-the- "Configuring TypeScript") in here? Even an empty string still make the error. And why is it possible that Deno isn't enable despite of the output of Deno language server?
