### ISSUE TITLE
Recursive Deno task with odd behaviour/race condition

### ISSUE THREAD

**Issue by krlwlfrt** [denoland/deno#27146]
Version: Deno 2.1.2

Spawning a command, which executes a Deno task, which itself runs Deno with a script that requests permissions results in an odd behavior/a race condition. See this Gist for the code: https://gist.github.com/krlwlfrt/7e3ba9baaaaa62059bd9bdb94f2fe936

Output of running `deno command.ts`:

```sh
❯ deno command.ts    
✅ Granted run access to "deno".
Task changelog deno read.ts

should only be logged, after the child is finished...


OUT 


ERR Task changelog deno read.ts
error: Uncaught (in promise) NotCapable: Requires read access to "read.ts", run again with the --allow-read flag
const file = await Deno.readTextFile('read.ts');
                        ^
    at Object.readTextFile (ext:deno_fs/30_fs.js:779:24)
    at file:///REDACTED/read.ts:1:25


✅ Granted read access to "/REDACTED/read.ts".
const file = await Deno.readTextFile('read.ts');
console.log(file);
```

This is at least somewhat confusing if not a bug? 

As I understand the documented behavior of `Deno.Command`, the output of the console.log statement should only appear after the child is finished.
This is not the case, because I have to grant permission to the `deno run` command in the the Deno task. The output of console.log appears first and the output of the child appears afterwards.

If I'm using `const child = command.spawn(); await child.output()` it works as expected.

**Comment by krlwlfrt** [comment]
I added 2 more variations of this to the Gist, which behave unexpected and inconsistent to this one...

**Comment by dsherret** [comment]
Change this:

```ts
command.spawn();

const output = await command.output();
```

To this:

```ts
const output = await command.output();
```

It's being spawned twice.

**Comment by krlwlfrt** [comment]
I see. I totally read that wrong. My bad. Thanks.
