### ISSUE TITLE
assert and CFA

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#2715]
Tracking issue.

After originally indicating it was a design limitation, the TypeScript team revisited allowing the ability to model type narrowing via `assert()`.  The `assert()` pattern is heavily used within Deno and once microsoft/TypeScript#32695 is landed is part of a TypeScript release we will be able to make all of our code more sound.

**Comment by hayd** [comment]
Update: This is merged to TS.

**Comment by kitsonk** [comment]
🎉 then that means it will be part of 3.7.  There is a lot of code we will want to update on the back of it!!!

**Comment by kitsonk** [comment]
Implemented in code base now.  Closing.
