### ISSUE TITLE
`fmt` doesn't recognize `deno.jsonc`

### ISSUE THREAD

**Issue by ooker777** [denoland/deno#27176]
`deno.jsonc`:
```json
{
  "fmt": {
    "lineWidth": 1500
  }
}
```
Main code:
```js
const aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa = 11111111111111111111111111111111111111111111111111111111;
```
It is formatted as if the config isn't there.

Version: Deno 2.1.2, VS Code LSP 3.42.0

**Comment by marvinhagemeister** [comment]
I'm not able to reproduce the described issue. The code stays exactly the same after running `deno fmt` for me.

**Comment by ooker777** [comment]
Can you set the `"editor.formatOnSave": true` on `.vscode/setting.json`? I have problem on autosave. `deno fmt` works fine for me as well.

**Comment by scarf005** [comment]
check your output of deno extension. it's likely the Deno extension hasn't found your `./deno.jsonc` because you specified without `c` at the end:
`  "deno.config": "./deno.json",`

**Comment by ooker777** [comment]
yeah. I don't know how I got that config. Where is the documentation for it?

**Comment by scarf005** [comment]
![image](https://github.com/user-attachments/assets/e9f61735-3b35-4e5f-861d-e784933e30de)

check https://github.com/denoland/vscode_deno/?tab=readme-ov-file#configuration
