### ISSUE TITLE
@mapbox/search-js-web `deno check .` error

### ISSUE THREAD

**Issue by invalidred** [denoland/deno#27186]
Version: 
- Deno 2.1.1
- Fresh 1.7.3
- mapbox/search-js-web 1.0.0-beta.24

I'm using `npm:@mapbox/search-js-web@^1.0.0-beta.24` in an island to render a TextBox that performs address lookup. Here is a gist of [the code ](https://github.com/invalidred/deno-fresh-mapbox-tesxt/blob/main/islands/LocationMap.tsx#L11).

I get the following error when doing `deno check .`

```
error: Uncaught Error: Unable to load /Users/abdulkhan/github/mapbox-test/fresh-site/node_modules/.deno/@mapbox+search-js-web@1.0.0-beta.24/node_modules/@mapbox/search-js-web/src/types/custom_elements.d.ts: No such file or directory (os error 2)
    at Object.getSourceFile (ext:deno_tsc/99_main_compiler.js:621:28)
    at findSourceFileWorker (ext:deno_tsc/00_typescript.js:126789:23)
    at findSourceFile (ext:deno_tsc/00_typescript.js:126705:20)
    at ext:deno_tsc/00_typescript.js:126654:22
    at getSourceFileFromReferenceWorker (ext:deno_tsc/00_typescript.js:126625:26)
    at processSourceFile (ext:deno_tsc/00_typescript.js:126652:5)
    at ext:deno_tsc/00_typescript.js:126946:7
    at forEach (ext:deno_tsc/00_typescript.js:2284:22)
    at processReferencedFiles (ext:deno_tsc/00_typescript.js:126945:5)
    at findSourceFileWorker (ext:deno_tsc/00_typescript.js:126848:9)
```

I've reproduce this in a brand new fresh app with 
1. deno add npm:@mapbox/search-js-web
2. adding a new [LocationMap.tsx island](https://github.com/invalidred/deno-fresh-mapbox-tesxt/blob/main/islands/LocationMap.tsx#L1-L40)

Note I had to include the modules in an async import as the module requires `document` and that fails to run server side.

```
const { MapboxGeocoder } = await import("@mapbox/search-js-web");
```

Note the code works great at runtime. It's only during the `deno check .` do I get TS errors.

Any help here in figuring out the issue would be great.

**Comment by dsherret** [comment]
It seems like a bug in the package. Inside `@mapbox/search-js-web` in dist/index.d.ts it references `../src/types/custom_elements.d.ts`, but those files don't exit.
![image](https://github.com/user-attachments/assets/b7bd8203-9ba8-4312-8739-67e7cb460cc0)

**Comment by dsherret** [comment]
Let's track this in a more general issue: https://github.com/denoland/deno/issues/27188
