### ISSUE TITLE
Running Prisma queries from a Deno repo

### ISSUE THREAD

**Issue by hammerlink** [denoland/deno#27195]
I'm currently working on migrating a Node.js project to Deno and have hit a wall with Prisma integration. Specifically, I'm having issues when trying to work with a local PostgreSQL database. 

 I've created a minimal reproduction repo here: https://github.com/hammerlink/deno-prisma-tsoa

Current Setup:
 -  Deno project with PostgreSQL running in Docker
-   Prisma dependencies installed via Deno
-   Using --no-engine flag (works fine with edge PostgreSQL but not with local instances, this produces the error below)

`Error validating datasource 'db': the URL must start with the protocol 'prisma://'`

I have omitted the --no-engine flag and this is the error I'm getting: 
`PrismaClientValidationError: Invalid client engine type, please use 'library' or 'binary'`

 Has anyone successfully integrated Prisma with a local PostgreSQL in Deno?
 Is there a specific configuration I'm missing for the engine type?
 Are there any alternative approaches you'd recommend?

**Comment by DanieleAurilio** [comment]
Hi @hammerlink ,
i've cloned the repo you provided and made few tests. Here what i did:
1) Modified prisma import as:
<img width="927" alt="image" src="https://github.com/user-attachments/assets/580e3845-3ae5-4114-97a3-9cca52a20b5e">


2) Added to task `quickstart` in the `deno.json` file the flag: `--unstable-detect-cjs`:

<img width="991" alt="image" src="https://github.com/user-attachments/assets/946d3cf6-f66c-4115-a3ee-42a97caf0d7e">

In this way seems to work in the local instance.

**Comment by hammerlink** [comment]
Super!  so my issues were:
-  I was using the client/deno/edge.js instead of the default client/index.js
- the files generated by prisma are .js files while they are using require and thus should be .cjs for Deno

thank you very much @DanieleAurilio 
this will allow me to migrate towards Deno

**Comment by caturandi-labs** [comment]
This also works.

```ts
import * as Prisma from "./generated/client/index.js";
import { type PrismaClient } from "./generated/client/index.d.ts";

export const prisma: PrismaClient = new Prisma.PrismaClient({
  log: ["query", "info", "warn", "error"],
});
