### ISSUE TITLE
REPL crashes on exit if cache directory doesn't exist

### ISSUE THREAD

**Issue by crabmusket** [denoland/deno#2719]
On the first run of Deno within a Docker container with `$HOME=/root`, this happens:

```
$ ./target/debug/deno
> let x = 5
undefined
> <Ctrl+D>
Unable to save REPL history: "/root/.cache/deno/deno_history.txt" No such file or directory (os error 2)
thread 'tokio-runtime-worker-0' panicked at 'called `Result::unwrap()` on an `Err` value: ErrBox(Io(Os { code: 2, kind: NotFound, message: "No such file or directory" }))', src/libcore/result.rs:999:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
fatal runtime error: failed to initiate panic, error 5
Aborted (core dumped)
```

It's reproducible if you delete the deno cache dir. [Dockerfile](https://gist.github.com/crabmusket/8b4c00d5bea8b2135275093a5418a51d) for reference.

**Comment by crabmusket** [comment]
Paging @bartlomieju

**Comment by bartlomieju** [comment]
So this can be solved two fold:
1. in `DenoDir::new` create the directory that has path of `root` - not so sure about it since we wanted to create directories lazily
2. in `//cli/repl.rs` before saving history ensure that directory is created: 
```
fn save_history() {
  ...
  match self.history_file.parent() {
      Some(ref parent) => fs::create_dir_all(parent),
      None => Ok(()),
    }?;
  ...
}
```

**Comment by crabmusket** [comment]
Solution 2 seems very sensible, as it maintains the laziness. I'll try to make this happen in the next day or two.
