### ISSUE TITLE
deno lint requires typescript file to have a .ts extension

### ISSUE THREAD

**Issue by jpravetz** [denoland/deno#27225]
Version: Deno 2.1.2

You are [permitted to have typescript scripts with no extrensions](https://docs.deno.com/runtime/tutorials/hashbang/#using-hashbang-in-files-with-no-extension). However it appears that you cannot lint these files.

In a folder setup using `deno init`, containing a _deno.json_ file and a _main.ts_ renamed to _myscript_ and that contains `#!/usr/bin/env -S deno run -RWESN --ext=ts` as the first line:

Running `deno lint myscript` does not work. You get a "No target files found" error. 

Ditto if you add `myscript` to your `deno.json` file using  `"lint": { "include": ["myscript"] }`.

**Comment by bartlomieju** [comment]
You should be able to run `deno lint --ext=ts myscript`.

**Comment by jpravetz** [comment]
This does work, thanks.  

I do note that if this script is the `main.ts` of your project, you cannot set "exports" to point to it (main) unless it has an extension (main.ts). But perhaps this isn't the intended use case for these scripts.

**Comment by dsherret** [comment]
If you're exporting a file from a package, then you need to provide an extension in order to prevent any ambiguity problems for users of the package (ex. npm allows no extensions and it creates bugs in the ecosystem where tools don't handle it).
