### ISSUE TITLE
Deno hangs for unknown reason after loading module

### ISSUE THREAD

**Issue by thenameisluk** [denoland/deno#27241]
```
deno 2.1.2 (stable, release, aarch64-unknown-linux-gnu)
v8 13.0.245.12-rusty
typescript 5.6.2
```

### The issue

so i have a project with a few files
but only 2 (maybe 3 are relevant to this issue)

entry point ```index.ts```
```ts
...
import { planTick } from "./plan.ts";
...
const services:service[] = [];

function registerService(s:service){
  console.log("registering "+s.name);
  if(s.init){
    s.init(sctx)
  }
  services.push(s)
}
...
registerService({
  name: "plan",
  longTick:planTick
})
```

and ```./plan.ts```
```ts
import { getCurrentPlan, getNextPlan } from "./usoss/plan.ts";
...
export async function planTick(sctx: serviceContext) {
...
  const cur = await getCurrentPlan(cred.usos.username, cred.usos.password);
  const next = await getNextPlan(cred.usos.username, cred.usos.password);
...
}
```

whenever i run the program with deno run -A index.ts
it hangs after loading the module files

### Attempt to diagnose the issue
after tinkering i discovered that if i

comment out
```ts
registerService({
  name: "plan",
  longTick:planTick
})
```
or
```ts
  const cur = await getCurrentPlan(cred.usos.username, cred.usos.password);
  const next = await getNextPlan(cred.usos.username, cred.usos.password);
```
the program runs in a normal way

**it should be noted that the issue also occurs even if ENTIRE content of get...plan functions gets commented out**

after running ```deno run --log-level=debug -A index.ts```
it gets stuck at this
```bash
DEBUG RS - deno::module_loader:932 - Updating V8 code cache for ES module: file:///home/luk/uwu/usoss/plan.ts, [3248053715730784532]
```

i've been able to use this part of code base for sometime without any issues but now it just doesn't work

thanks for any help ❤️

**Comment by marvinhagemeister** [comment]
How can we see the error on our end? Do you have a repo you can share where the error is reproducible?

**Comment by thenameisluk** [comment]
can't share the code sorry

i was working on mre but

it turned out some jsr library (that was freezing everything) from ./usoss/plan.ts was optimized out when the functions weren't callable

sorry for wasting ur time
