### ISSUE TITLE
Website: `margin-left: auto; margin-right: auto;` on body?

### ISSUE THREAD

**Issue by adrianhelvik** [denoland/deno#2724]
The title says it all. The site looks much nicer centered!

**Comment by nayeem-rahman** [comment]
Not to me... it does when I increase it's width as well but now it's hard to read 🤨

**Comment by adrianhelvik** [comment]
<img width="1680" alt="Screen Shot 2019-08-05 at 00 14 50" src="https://user-images.githubusercontent.com/7836058/62429939-45386c80-b716-11e9-899c-9cdc73d58833.png">

**Comment by adrianhelvik** [comment]
Vs

<img width="1680" alt="Screen Shot 2019-08-05 at 00 17 19" src="https://user-images.githubusercontent.com/7836058/62429946-68fbb280-b716-11e9-9709-c55911bc5dd6.png">

**Comment by adrianhelvik** [comment]
I dunno. It is not a big deal. It just irks me a bit .

**Comment by ry** [comment]
Thanks but I like it as is
