### ISSUE TITLE
fetch trying to read local file gives Deno Panic

### ISSUE THREAD

**Issue by EnixTV** [denoland/deno#27258]
Version: Deno 2.1.3 Platform: windows x86_64
Deno gives a ✅ Granted read access to "\\<anyPath>\". if u try to read a none existing local file if your fetch-link starts with "file://"
Deno will panic afterwards I don't want to see that cute dino panicing ;-;
probably just an uncaught error or something

**Comment by dsherret** [comment]
Can you provide a reproduction with the panic message?
