### ISSUE TITLE
Deno.build and Deno.platform require no permissions.

### ISSUE THREAD

**Issue by qwerasd205** [denoland/deno#2725]
`Deno.build` and `Deno.platform` seem like they should be behind `--allow-env`.

**Comment by nayeem-rahman** [comment]
I'm against.

I don't think Deno is aiming to be or needs to be any more sandboxed than browsers - which give this information to untrusted web scripts.

**Comment by qwerasd205** [comment]
> I'm against.
> 
> I don't think Deno is aiming to be or needs to be any more sandboxed than browsers - which give this information to untrusted web scripts.

That's a good point. Closing.
