### ISSUE TITLE
Support for data URLs and object URLs

### ISSUE THREAD

**Issue by qwerasd205** [denoland/deno#2726]
Data URLs and Object URLs (generally of blobs) [are frequently used to dynamically create Workers](https://stackoverflow.com/a/10372280) -- support for these is missing in Deno which presents a compatibility issue with existing web code, and is an issue when trying to create workers from strings in Deno.

What's missing:
- Support for the `data:` scheme for URLs
- ~~Support for object URLs and `URL.createObjectURL()`~~ (Solved by #2729)

**Comment by Fenzland** [comment]
This feature also need for importing.
The follow codes work in browsers but dosn't in deno yet.
```javascript
import value from 'data:application/javascript,export%20default%201%3B';

import (`data:application/javascript,${encodeURIComponent('export default 1;')}`).then(x=>console.log(x.default));
```

dynamic import with data-url is a good way to take place of eval(). So it's a essential feature.

**Comment by kitsonk** [comment]
Here is the relevant discussion in Node.js: https://github.com/nodejs/node/pull/28614. There are some security concerns with allowing this, but I guess the same applies for doing it with web workers.

**Comment by Fenzland** [comment]
@kitsonk It does not bring new security problems. We can write the code to a file and import it to do the same thing. The only difference is slowness. An --allow-*** flag will be OK.

**Comment by sh7dm** [comment]
I can try to implement this using https://docs.rs/data-url/0.1.0/data_url/

**Comment by EliteScientist** [comment]
My product is having the same issue. we need to dynamically create Workers and support dynamic imports from blob or object urls.

I'm using 1.4.5
