### ISSUE TITLE
otel: `"unstable": ["otel"]` in `deno.json` seems not to enable sending of signals

### ISSUE THREAD

**Issue by uki00a** [denoland/deno#27273]
### Problem

Specifying `"unstable": ["otel"]` in `deno.json` seems to enable `Deno.tracing` API but not the sending of signals. Specifying `--unstable-otel` option properly enables both.

### Expected behavior

`"unstable": ["otel"]` enables both `Deno.tracing` API and sending of signals.

### Actual behavior

`"unstable": ["otel"]` enables only `Deno.tracing` API.

### Environment
- Deno v2.1.3
- `jsr:@deno/otel@0.0.2`

**Comment by knotbin** [comment]
This still seems to be the case for me. @uki00a is this fixed for you?
