### ISSUE TITLE
Dynamic imports with TypeScript type-only imports fail when compiled into a binary

### ISSUE THREAD

**Issue by Renotje6** [denoland/deno#27270]
Version: Deno 2.1.2

## Description
When compiling my Deno project into a binary using deno compile, I encounter an issue with dynamically importing modules that include TypeScript `type` imports. Specifically, the dynamically loaded file throws a syntax error when it tries to import a type. This issue occurs even though the modules are available during compilation.

```
SyntaxError: Unexpected identifier 'Person' at file:///R:/github-repos/testing-projects/type-import-bug/src/modules/core/testing.ts:1:15
    at async importer (file:///C:/Users/Admin/AppData/Local/Temp/deno-compile-src.exe/type-import-bug/src/utils/functions/import.ts:16:9)
    at async file:///C:/Users/Admin/AppData/Local/Temp/deno-compile-src.exe/type-import-bug/src/main.ts:19:3 {
  code: "ERR_MODULE_NOT_FOUND"
}
```

## Steps to reproduce
1. Clone this [repo](https://github.com/Renotje6/type-import-bug)
2. Compile the project into a binary using `deno compile --allow-read --include src/modules --include src/types/index.d.ts src/main.ts`
3. Run the executable

## Expected behavior
The dynamically imported file (testing.ts) should be successfully executed without errors. The type-only import (type Person) should not result in a SyntaxError, as it is purely a compile-time construct and should not impact runtime behavior.

## Actual behavior
The following error is thrown during execution of the binary:

```
SyntaxError: Unexpected identifier 'Person' at file:///path/to/file/testing.ts:1:15
    at async importer (file:///path/to/file/import.ts:16:9)
    at async file:///path/to/file/main.ts:19:3 {
  code: "ERR_MODULE_NOT_FOUND"
}
```

## Additional information
- The `type` import ( `import { type Person }` ) works correctly when running the project with `deno run`.

**Comment by dsherret** [comment]
Does it work if you specify each file individually in `--include` instead of just a directory? I think this might be https://github.com/denoland/deno/issues/26941

**Comment by Renotje6** [comment]
No, it doesn't. It throws the same error.

**Comment by dsherret** [comment]
Ah, it looks like it's just taking this code path and importing from outside the binary?

```
for await (const file of expandGlob(globPath)) {
			if (file.isFile) {
				await import(`file://${file.path}`);
			}
		}
```

Notice how the file inside the binary is importing a file outside the binary:

```
SyntaxError: Unexpected identifier 'Person' at file:///R:/github-repos/testing-projects/type-import-bug/src/modules/core/testing.ts:1:15 <-- outside on the `R` drive
    at async importer (file:///C:/Users/Admin/AppData/Local/Temp/deno-compile-src.exe/type-import-bug/src/utils/functions/import.ts:16:9) <--- inside 
```

If so, this issue is https://github.com/denoland/deno/issues/18327

By the way, it's better to convert file paths to file urls using https://jsr.io/@std/path/doc/~/toFileUrl because taking a path and making it a file url won't always work

**Comment by dsherret** [comment]
Once I fix the issues in that repo with this patch:

```diff
diff --git a/src/utils/functions/import.ts b/src/utils/functions/import.ts
index 43e82a7..36f5892 100644
--- a/src/utils/functions/import.ts
+++ b/src/utils/functions/import.ts
@@ -1,22 +1,14 @@
 import { expandGlob } from '@std/fs';
-import { join } from '@std/path';
+import { join, toFileUrl } from '@std/path';
 
 /**
  * Dynamically import all files matching the glob pattern
  * @param globPath - The glob pattern to match files
  */
 export async function importer(globPath: string) {
-	if (Deno.args.includes('--is_compiled_binary')) {
-		for await (const file of Deno.readDir(join(import.meta.dirname!, '../../../src/modules/core'))) {
-			if (file.isFile) {
-				await import(`file://${join(import.meta.dirname!, '../../../src/modules/core')}/${file.name}`);
-			}
-		}
-	} else {
-		for await (const file of expandGlob(globPath)) {
-			if (file.isFile) {
-				await import(`file://${file.path}`);
-			}
+	for await (const file of Deno.readDir(join(import.meta.dirname!, '../../../src/modules/core'))) {
+		if (file.isFile) {
+			await import(toFileUrl(join(import.meta.dirname!, '../../../src/modules/core', file.name)).toString());
 		}
 	}
 }
```

And include the file directly:

```shellsession
> deno compile --include src/modules/core/testing.ts src/main.ts
Check file:///V:/type-import-bug/src/main.ts
Check file:///V:/type-import-bug/src/modules/core/testing.ts
Compile file:///V:/type-import-bug/src/main.ts to src.exe
V:\type-import-bug [main ≡ +1 ~1 -0 !]
> ./src.exe
{ name: "John", age: 30 }
```

It works. Let's track this in https://github.com/denoland/deno/issues/26941
