### ISSUE TITLE
Cannot use MSW.js

### ISSUE THREAD

**Issue by vladjerca** [denoland/deno#27289]
Version: Deno 2.1.3

```sh
TypeError: Could not find package '_http_common' from referrer '.../node_modules/.deno/@mswjs+interceptors@0.37.3/node_modules/@mswjs/interceptors/lib/node/chunk-3A47UESP.mjs'.
 ❯ src/mocks/server.ts:1:1
      1| import { setupServer } from 'msw/node';
       | ^
      2| import { handlers } from './handlers.ts';
      3| 
 ❯ vitest-setup.ts:5:1
 ```

Easily reproducible by following the basic setup guide:

https://mswjs.io/docs/getting-started

Works with: `bun` and `node`. I know that `_http_common` is exposed by `node` but I would expect deno to have some polyfill for it since it's supposed to offer backwards compatibility? 🤔  

LE: Link with repro https://github.com/vladjerca/deno-msw-repro

**Comment by vladjerca** [comment]
I've tried using the `canary` build, indeed the first issue is fixed. A new one seems to have materialized though:

```sh
ReferenceError: BroadcastChannel is not defined
 ❯ ../../node_modules/.deno/msw@2.6.8/node_modules/msw/src/core/ws.ts:20:26
 ```

**Comment by petamoriken** [comment]
Please try to use `--unstable-broadcast-channel` flag
https://docs.deno.com/runtime/reference/cli/unstable_flags/#--unstable-broadcast-channel

**Comment by vladjerca** [comment]
Yep, that was the missing piece! Thanks, you guys rock! 😀
