### ISSUE TITLE
Working directory `PWD` affects hash of output binary of `deno compile`

### ISSUE THREAD

**Issue by cjdell** [denoland/deno#27284]
I am trying to make a reproducible build of a Deno project using a Nix Flake. I don't know if this should be considered a bug or a feature request, but I think it's fair to say that having the project source working directory affect the contents of a standalone binary is surprising. It is particular problematic for us Nix users as the build directory is essentially random. Leaking this into the binary will of course break determinism.

For example:

```bash
cd ~/project-copy-1
deno compile --cached-only --no-code-cache -o main-bin main.ts
sha256sum main-bin # 5ce74fa4c5362265cbd5a31a955fdf2146e879a0bbf1d7e186bfc70fb91dc410

# Change to identical copy in another folder...
cd ../project-copy-2
deno compile --cached-only --no-code-cache -o main-bin main.ts
sha256sum main-bin # 3489c7ee676db118c774a346689c3966177819c39e7691af96ae7ccd3e984914 <== Different
```

Using a binary diffing tool (`dhex`) I think the main culprit is `sourceMappingURL` which contains base64 JSON with references to the `PWD` of the sources where the binary was originally built from, but there could be others too. Adding `no-code-cache` reduced the number of differences.

Perhaps turning off source maps would be the solution? I couldn't see anyway of doing this without a fork.

I'm happy to dive in deeper if that is helpful to anyone.

**Comment by cjdell** [comment]
My current workaround if anyone is interested is to move everything to a fixed build path in tmp. This makes the build deterministic on different machines. In my derivation's build script I have this before anything else:

```bash
mkdir /tmp/build-path
mv * /tmp/build-path/
cd /tmp/build-path

// Do build...

rm -rf /tmp/build-path
```

**Comment by dsherret** [comment]
I think this is actually fixed in the latest canary (`deno upgrade canary`)?

The sourceMappingURL is the next thing to fix, which would also fix the code cache I think (because the code cache includes the sourceMappingURL)

**Comment by dsherret** [comment]
Oh wait, we don't have a separate issue for `sourceMappingURL`. Will leave this one open until then.

**Comment by cjdell** [comment]
@dsherret Thanks for the info. I just tried canary and it is definitely an improvement. The binary byte length now only increases 29 bytes per extra character in the path. Before it was 350!

First reference to the working directory is at 0x5651915 and appears to be JSON text:
```json
{"n":"my-project1","e":[{"Dir":{"n":"backend","e":[{"Dir":{"n":"src","e":[
```

There's a number of base64 references later on. It appears to only be the directory itself not the fully qualified path. This means that I can probably workaround it by ensuring that just the last directory name is consistent across builds which is doable in Nix.

Ideally would still like to have no mention of the build directory in the binary. Thanks for your help so far.
