### ISSUE TITLE
TypeError in Deno.stat on Windows with exFAT-formatted drives

### ISSUE THREAD

**Issue by mono0x** [denoland/deno#27286]
- Deno Version: 2.1.3
- Operating System: Windows 11 Pro 24H2

Running a script using `Deno.stat` on a file located on an exFAT-formatted drive (e.g. SD card) causes a `TypeError: Cannot convert a BigInt value to a number`. The issue does not occur on NTFS-formatted drives. Additionally, the issue could not be reproduced on macOS Sequoia 15.1.1 when performing the same steps.

## Steps to Reproduce
1. Prepare an exFAT-formatted drive (e.g., G:\ drive).
2. Create a test file `test.txt` on the drive:
   ```
   touch G:\test.txt
   ```
3. Create a test script `test.ts` with the following content:
   ```typescript
   console.log(await Deno.stat("G:\\test.txt"));
   ```
4. Execute the script with the necessary permission:
   ```
   deno run --allow-read test.ts
   ```

## Actual Behavior
The following error occurs:

```
error: Uncaught (in promise) TypeError: Cannot convert a BigInt value to a number
console.log(await Deno.stat("G:\\test.txt"));
            ^
    at new Date (<anonymous>)
    at parseFileInfo (ext:deno_fs/30_fs.js:381:41)
    at Object.stat (ext:deno_fs/30_fs.js:410:10)
    at eventLoopTick (ext:core/01_core.js:175:7)
    at async file:///C:/path/to/test.ts:1:13
```

## Expected Behavior
The script should output the file information without throwing an error.

**Comment by matt1** [comment]
I did some investigation - this appears to have been introduced in https://github.com/denoland/deno/commit/7becd83a3828b35331d0fcb82c64146e520f154 to make deno compatible with node.

At this stage I don't know if this was intentional (i.e. to maintain like-for-like node compatibility) or not.
