### ISSUE TITLE
LSP actions use `@deno-types` instead pf `@ts-types`

### ISSUE THREAD

**Issue by kt3k** [denoland/deno#27309]
LSP code actions use `@deno-types` for adding types to the import statement. These should be replaced with `@ts-types` as `@ts-types` is now more recommended than `@deno-types`

```shellsession
$ git grep --line-number deno-types cli/lsp/
cli/lsp/analysis.rs:1390:        "{}// @deno-types=\"{}\"\n",
cli/lsp/analysis.rs:1403:          "Add @deno-types directive for \"{}\"",
cli/lsp/diagnostics.rs:1358:    // @deno-types and that's a bit complicated to explain
cli/lsp/diagnostics.rs:1526:  // TODO(nayeemrmn): This is a crude way of detecting `@deno-types` which has
cli/lsp/diagnostics.rs:1543:        // If not @deno-types, diagnose the types if the code errored because
cli/lsp/diagnostics.rs:1954:        // @deno-types="bad.d.ts"
cli/lsp/tsc.rs:3422:                  "// @deno-types=\"{}\"\n{}",
cli/lsp/tsc.rs:3598:            "// @deno-types=\"{}\"\n{}",
```

Version: Deno 2.1.3

**Comment by MohammadSu1** [comment]
I will pick this up

**Comment by skeithtan** [comment]
Where do I get more information about `@ts-types` being more recommended than `@ts-types`? 

Deno's documentation still references `@deno-types` for NPM's @types import:
https://docs.deno.com/runtime/fundamentals/node/#importing-types

**Comment by kt3k** [comment]
We used to have this note in the docs:

> ℹ️ _Note_: The directive `@deno-types` can be used as an alias for
> `@ts-types`. This is not recommended anymore.

https://github.com/denoland/docs/pull/502/files#diff-48be754e581d83d441f97da424c2ab4da89f3fdc61d9af9a493e7c610de73775R56-R57

But we accidentally removed it at some point. We are fixing it in https://github.com/denoland/docs/pull/1256

---

`@ts-types` was added in this PR in `deno_graph` https://github.com/denoland/deno_graph/pull/444

`deno_graph` crates was upgraded to the corresponding versioin in this PR https://github.com/denoland/deno/pull/23513

So this change happened at Deno v1.43.0 (but apparently we didn't communicate this very well...)

**Comment by jsejcksn** [comment]
> Where do I get more information about `@ts-types` being more recommended than `@ts-types`?

@skeithtan After https://github.com/denoland/docs/pull/1256 was merged, the docs page with the information is at the following URL:

https://docs.deno.com/runtime/reference/ts_config_migration/#providing-types-when-importing
