### ISSUE TITLE
I can't access JSR packages, Deno docs or anything from Iran until I turn on my VPN!

### ISSUE THREAD

**Issue by babakfp** [denoland/deno#27319]
https://github.com/denoland/deno/issues/14486

**Comment by dsherret** [comment]
I don't think there's anything we can do here. Also, the JSR issue tracker is here: https://github.com/jsr-io/jsr/issues

**Comment by crowlKats** [comment]
Basically all our servers are some form of GCP and/or AWS. There is not much we can do there

**Comment by BlackAsLight** [comment]
Sanctions are about preventing the funding of war. Anyone dealing with sanctioned countries wants to have experts in the field to comply with said sanctions. The penalties for breaking sanctions are harsh and rarely forgiving. Sanctions require businesses to know not only who their suppliers are, but who their suppliers' suppliers are; as you can be penalised for doing business with another business that supporting a sanctioned country.

**Comment by babakfp** [comment]
Sanctions are not about blocking information and content. No sanctions say documentation sites or registries like JSR should be restricted. This is not about asking Deno to prove paid services.

So much can be done here.

Just say you don't care. It's better than this BS.

**Comment by dsherret** [comment]
@babakfp there's nothing configured on JSR's end to block users in Iran.

> Just say you don't care. It's better than this BS.

Why would we go out of our way to help make things more convenient for you when you act this way? Even so, I'm not sure there's anything we can do here https://news.ycombinator.com/item?id=20494147
