### ISSUE TITLE
unexpected argument --allow-import found with deno lint

### ISSUE THREAD

**Issue by securesvet** [denoland/deno#27318]
Version: Deno 2.1.3

When trying to use `deno -I lint` in project of mine deno cli outputs the following:
```
 error: unexpected argument '--allow-import' found

  tip: 'lint --allow-import' exists

Usage: deno lint [OPTIONS] [files]...
```

But! When I try to use `deno lint --allow-import` this problem pops out:
 ```
error: unexpected argument '--allow-import' found

  tip: to pass '--allow-import' as a value, use '-- --allow-import'

Usage: deno lint [OPTIONS] [files]...
```

Needless to say, that passing flag as an argument doesn't fix the issue

This bug occurs on CI using ubuntu runner and on my local Ubuntu machine.
Couldn't find `--allow-import` mentioned as an available parameter on docs, so I'm confused

**Comment by dandv** [comment]
Similar issue with `--allow-all`. I left [a comment](https://github.com/denoland/deno/issues/27336#issuecomment-2676150271) on #27336.
