### ISSUE TITLE
not a result of an error when fetching same site fast

### ISSUE THREAD

**Issue by CyanChanges** [denoland/deno#27332]
Version: Deno 2.1.2

I'm trying to make create a mirror for about 2000 packages in npm.
For each package, it fetches `https://registry.npmjs.org/<package>` and the downloads (`https://api.npmjs.org/downloads/point/last-month/<package>`) with `Promise.all()`
But there is a few errors while fetching.
```
Error: connection error received: not a result of an error
        at mainFetch (ext:deno_fetch/26_fetch.js:182:43)
        at eventLoopTick (ext:core/01_core.js:164:35)
        at async fetch (ext:deno_fetch/26_fetch.js:392:7)
```
```
TypeError: error sending request from ***.***.***.***:38254 for https://api.npmjs.org/downloads/point/last-month/koishi-plugin-qsign (104.16.0.35:443): client error (SendRequest): http2 error: connection error received: not a result of an error
        at mainFetch (ext:deno_fetch/26_fetch.js:182:11)
        at eventLoopTick (ext:core/01_core.js:164:35)
        at async fetch (ext:deno_fetch/26_fetch.js:392:7)
```

These errors appears randomly. Unfortunately, I can't provide a stable repro.

**Comment by heypiotr** [comment]
I've seen the same issue in our Deno app which also makes a lot of network requests.

We're currently on Deno 1.30.0, and with that version, we mostly see occasional "conection reset" or "request has been canceled". After updating to Deno 2.1.2, we've started seeing this. (We had to revert the update for unrelated reasons, so I only have a small sample size for now.)

I'm yet to dig deeper into this, but I believe the issue might actually be upstream, in the hyperium library?
https://github.com/hyperium/h2/blob/3bce93e9b0dad742ffbf62d25f9607ef7651a70c/src/frame/reason.rs#L65
