### ISSUE TITLE
Disabling `deno-ts(80006)`

### ISSUE THREAD

**Issue by harrysolovay** [denoland/deno#27353]
I often see this diagnostic in functions that return a promise:

```
deno-ts(80006)
```

I believe this is a mistake / should be something end developers can disable.

For instance, the following JS is valid:

```ts
function completeText(messages: string[]): Promise<string> {
  return chat.completions.create({ messages }).then(unwrapChoice)
}
```

However, I still see the diagnostic. And it suggests the following refactor:

```ts
function completeText(messages: string[]): Promise<string> {
  const completion = await chat.completions.create({ messages })
  return unwrapChoice(completion)
}
```

I prefer the initial version. Can I / how might I get the Deno LS to stop including this diagnostic?

**Comment by dsherret** [comment]
Do you have a reproduction? It shouldn't error for the first one.

**Comment by harrysolovay** [comment]
Yes: the source code can be found [here](https://github.com/harrysolovay/structured-outputs/blob/8266cc3c8f61d94bbe7810819dd8655bb8a04233/liminal/client/openai/OpenAIAdapter.ts#L109).

**Comment by dsherret** [comment]
Ah, I didn't realize this was just a suggestion from TypeScript. I think we just need a way to disable or filter out certain typescript suggestions (related https://stackoverflow.com/a/77265400/188246). Thoughts, @nayeemrmn?

**Comment by nayeemrmn** [comment]
Seems like an upstream issue. Is there a way of disabling it with ts server that doesn't work here?

**Comment by nayeemrmn** [comment]
#27373 will implement `"typescript.suggestionActions.enabled": false` which is TypeScript's recommended solution to this: https://github.com/microsoft/vscode/issues/61326#issuecomment-431999046. It seems to work pretty well, but a more granular setting is requested upstream at https://github.com/microsoft/TypeScript/issues/28825. That doesn't exist yet.
