### ISSUE TITLE
Permissions aren't checked for symlink destinations

### ISSUE THREAD

**Issue by nayeem-rahman** [denoland/deno#2738]
With `--allow-read=. --allow-write=.`, execute:
```javascript
Deno.symlinkSync('/etc/passwd', 'passwd');
console.log(new TextDecoder().decode(Deno.readFileSync('passwd')));
```

**Comment by bartlomieju** [comment]
Reference (or maybe duplicate): #2318

**Comment by nayeem-rahman** [comment]
Yeah, definite duplicate. #2318 definitely needs more attention, though. Can't imagine 1.0 before that's fixed. cc @ry
