### ISSUE TITLE
How to include SDL2 files when compiling Deno?

### ISSUE THREAD

**Issue by jabed-web-dev** [denoland/deno#27388]
How to include SDL2 files when compiling Deno?

This only works with environment variables. I want to include this in the Deno compilation. I want my execution file to run without SDL2 later. SDL2 should be inside the execution file. SDL2.dll, SDL2_image.dll, SDL2_ttf.dll

**Comment by petamoriken** [comment]
`--include` flag would be the solution.
https://deno.com/blog/v2.1#embed-assets-files-in-deno-compile
