### ISSUE TITLE
Not specifying `nodeModulesDir` in deno.json not behaving as the default

### ISSUE THREAD

**Issue by bombillazo** [denoland/deno#27385]
Version: Deno 2.x.x

I am not sure if this is intentional, but if one does not specify the `nodeModulesDir` option in deno.json, you get a different behavior from setting it the default value to true(deprecated)/'auto'.

I am migrating from deno 1, where I did not set this option in my deno.json, so I assume it was using `true`, the default specified in the docs. When upgrading to deno 2, I had to explicitly set this value up in my config file for it to work, otherwise, deno run failed and got a cryptic error:

```sh
error: [ERR_MODULE_NOT_FOUND] Cannot find module 'file:///Users/app/node_modules/.deno/type-fest@4.30.1/node_modules/type-fest/index.js' imported from 'file:///Users/app/@types/date.types.ts'
```

**Comment by dsherret** [comment]
> you get a different behavior from setting it the default value to true(deprecated)/'auto'.

The default behaviour changed in Deno 2 to `"manual"` when there's a package.json for better node compatibility. To auto-isntall, you'll need to add:

```json
{
  "nodeModulesDir": "auto"
}
```

The migration guide was not clear about this, so I just updated it.

> so I assume it was using true, the default specified in the docs

Can you point to where it says this is the default in the docs? I can't find it. That should be changed.

**Comment by bombillazo** [comment]
sorry not the docs, the hinting for the option in VS Code
![image](https://github.com/user-attachments/assets/a794fa7c-22f4-40ea-99bf-e96880048ac5)

What I understood from this example was that true was the default, since I never found what was the default value anywhere for v1.

What is the appropriate migration process then for those 2 scenarios (with and w/o package.json file)

I suggested this PR from my initial understanding https://github.com/denoland/docs/pull/1272

**Comment by dsherret** [comment]
Without a package.json it's the same. With a package.json it changed to the new "manual", so to get the previous behaviour you need to set it to "auto"

**Comment by bombillazo** [comment]
Ok Ill make those changes to the docs, cause that was a stumper on our migration process :)

**Comment by bombillazo** [comment]
@dsherret does this make sense/look good?

<img width="1135" alt="image" src="https://github.com/user-attachments/assets/cb6b06aa-9e97-404e-9849-6f2693ce3a51" />

**Comment by bombillazo** [comment]
We can close this now :)
