### ISSUE TITLE
`deno publish --set-version` results in error `version specified during publish does not match version in config file '/deno.jsonc'`

### ISSUE THREAD

**Issue by NathanFlurry** [denoland/deno#27428]
Version: Deno 2.1.1

Steps to reproduce:

1. Create a Deno package with version `0.0.0`
2. Run `deno publish --set-version 1.2.3`
3. Results in this error:

```

Publishing @my/package@1.2.3 ...
error: Failed to publish @my/package@1.2.3

Caused by:
    Failed to publish @my/package at 1.2.3: version specified during publish does not match version in config file '/deno.jsonc', expected 1.2.3, got 0.0.0
```

Expected result:

Should update version in `deno.jsonc` automatically. Similar to `npm version` command.

**Comment by dsherret** [comment]
@NathanFlurry this is a JSR specific error and can be reported in the JSR repo. That said, this can be fixed by removing the version field from the deno.json before publishing.

**Comment by dsherret** [comment]
JSR code that raises this error is here: https://github.com/jsr-io/jsr/blob/627ac116fa625f6df2937a9952b5f8838174754b/api/src/tarball.rs#L574
