### ISSUE TITLE
CommonJS module import failure when `module.exports` has key containing escaped whitespace

### ISSUE THREAD

**Issue by jceb** [denoland/deno#27422]
Version: Deno 2.1.4

I ran into an issue related to CommonJS modules that hit me while working with https://daisyui.com via this package: [@matthiesenxyz/unocss-preset-daisyui](https://www.npmjs.com/package/@matthiesenxyz/unocss-preset-daisyui) / [github](https://github.com/MatthiesenXYZ/unocss-preset-daisyui). When I import a module that exports an object with a `\n` inside a key, an error is thrown. The same  is true for `\t` and `\r`. When I put the same code in an ESM module it works without issues.

Test script that imports two scripts, `works.js` is the ESM module, `bang.cjs` the CommonJS module.

`test.js`:

```js
const works = await import("./works.js");
console.log("imported:", works);
const bang = await import("./bang.cjs");
console.log("imported:", bang);
```

`works.js`:

```js
export default {
  "\nx": "test",
};
```

`bang.cjs`:

```js
module.exports = {
  "\nx": "test",
};
```

Result:

```sh
deno -A test.js
imported: [Module: null prototype] { default: { "\nx": "test" } }
error: Uncaught (in promise) SyntaxError: Invalid or unexpected token at file:///.../bang.cjs:9:31
const bang = await import("./bang.cjs");
          ^
    at async file:///.../bang.js:3:11
```

**Comment by dsherret** [comment]
Can you try out your reproduction code in a fresh empty folder with no configuration files? I'm not able to reproduce.

**Comment by jceb** [comment]
Oh, I'm sorry, `bang.cjs` contained the wrong content. I corrected the mistake and the error should now be reproducible.
