### ISSUE TITLE
Mod File Generation

### ISSUE THREAD

**Issue by harrysolovay** [denoland/deno#27451]
This may be out of scope, but I believe it's enough of a productivity boon that I'd like to propose it just incase.

I frequently utilize a tool called [moderate](http://github.com/tjjfvi/moderate) to regenerate `mod.ts` files. The workflow is very simple:

1. whenever I create a `mod.ts` that I'd like to "moderate", I add a `// moderate` comment at the very top.
2. whenever I wish to regenerate the file, I run a command `deno task mod`, which writes re-export statements for all files and `mod.ts`-containing subdirectories.

One can even specify excludes in the directive + add leading statements to be left untouched before the `// moderate` directive. Ie.

```ts
export { SomethingElse } from "./something_else.ts"

// moderate --exclude something_else.ts

export * from "./file.ts"
export * from "./dir/mod.ts"
```

This utility saves me significant time.

I was wondering if anyone thought a workflow such as this could make it into Deno toolchain, where it could be standardized and made to benefit the broader ecosystem. Dealing with mod/barrel files / and reexport statements is just such a pain for so many developers. I think we can do better by making this or a similar workflow a first class citizen.

**Comment by BlackAsLight** [comment]
So it just takes all your files and re-exports them in a mod.ts file? How does this save significant time? Why would you need to regenerate them and not update it whenever you create or delete a file? Since you've essentially switched it from manually including to manually excluding, I don't see how it saves any time.

**Comment by harrysolovay** [comment]
It's easy to forget to add/remove/update reexports. Consider projects that have dozens of files and many contributors.

Also: auto-import updates come to mind: they often result in mod files that contain undesirable reexports. For instance, let's say we have a `mod.ts` that looks as follows.

`a/b/mod.ts`

```ts
export * from "./c.ts
```

If we move `c.ts` into the parent directory (aka. it will be at `a/c.ts`), the `mod.ts` may auto-update to the following.

```ts
export * from "../c.ts"
```

Moderate ensures that this reexport is no longer in `a/b/mod.ts`, and ensures that it present in `a/mod.ts`.

"moderating" is a way to simplify managing exports in large projects. The Deno team already somewhat "moderates" [denoland/std](http://github.com/denoland/std). Although it's manual, there is an agreed upon convention for organizing and excluding files from different subpackages/mods.

I'm not suggesting a specific `// moderate` directive, nor approach to generating mod files, but rather that mod file generation / convention-checking is useful and may merit consideration in the Deno toolchain itself.

**Comment by marvinhagemeister** [comment]
This sounds like a useful features for certain projects, but I'm not sure if putting that into Deno itself is the ideal place. Personally, I haven't encountered projects where _everything_ of the sibling files should be exported. There is always an exception here or there which makes automating it more tricky. That said it's a perfect feature to put into a tool on `jsr.io` and share it across your projects that way. That's something you can do today and don't need to wait for Deno to add something.

**Comment by harrysolovay** [comment]
I would agree if not for the possibility that a proper solution may utilize the Deno module graph (to prevent issues such as used-before-initialization, misc).

**Comment by jaydenseric** [comment]
Index/mod/barrel modules are a serious anti pattern and should not be encouraged. Projects and packages should take steps to delete them from their codebase and move to optimal deep imports. To learn why, here is a detailed explanation:

https://jaydenseric.com/blog/optimal-javascript-module-design

**Comment by dsherret** [comment]
I think this is better left for a separate tool and too specific to have a command in Deno. For example, something could do this on the fly in the editor.

IIRC, I think someone proposed a general purpose code generator sub-command and that might be a better option, though it's something that can be easily achived with `deno task` (especially once it has stuff like cache busting support), so I'm not sure it's worth it.

**Comment by harrysolovay** [comment]
That's completely reasonable. Thank you @dsherret.

**Comment by dburles** [comment]
> "since people should use automated tools that distribute the code bundled"

This statement is indicative of the very strong paradigm that you both appear to be stuck within.  Please give deeper consideration and thought to environments where bundling is no longer required. There are no strong arguments on the side of barrel files. The majority of the counter arguments to @jaydenseric's article are weak or require some other solution to solving a problem created by barrel modules that simply doesn't need to exist.

**Comment by harrysolovay** [comment]
> This statement is indicative of the very strong paradigm that you both may be constrained by.

Apologies I really don't know what you mean by this. By "paradigm", do you mean the decision to occasionally use re-exports to organize code / improve legibility?

On another note, calling counterarguments "weak" without technical explanation is dismissive (as is suggesting a lack of "deeper consideration"). Not sure why this convo devolved... perhaps because of (what appears to be) baggage in [denoland/std#2321](https://github.com/denoland/std/pull/2321#issuecomment-1159603759).

Anyways, the issue's closed. Be well guys!
