### ISSUE TITLE
How to transpile typescript to javascript for web?

### ISSUE THREAD

**Issue by jabed-web-dev** [denoland/deno#27461]
**error: ⚠️ `deno bundle` was removed in Deno 2.**

**Comment by petamoriken** [comment]
> Atm, the best option for bundling is https://github.com/lucacasonato/esbuild_deno_loader

https://github.com/denoland/deno/issues/11073#issuecomment-2558725431

**Comment by kt3k** [comment]
See `deno bundle` section of the migration guide https://docs.deno.com/runtime/reference/migration_guide/#cli-changes

We recommend using esbuild with esbuild-deno-loader:

```js
import * as esbuild from "npm:esbuild";
import { denoPlugins } from "jsr:@luca/esbuild-deno-loader";

const result = await esbuild.build({
  plugins: [...denoPlugins()],
  entryPoints: ["your_script_here.ts"],
  outfile: "./dist/bytes.esm.js",
  bundle: true,
  format: "esm",
});

esbuild.stop();
```
