### ISSUE TITLE
Move //js to //cli/js

### ISSUE THREAD

**Issue by ry** [denoland/deno#2747]
All of the files in //js belong the the CLI crate. We should make this more apparent. There is the additional benefit of rebuilding-on-change when using 'cargo build'.

This should not be done until #2730 is complete.

This should maybe wait for https://github.com/denoland/deno/pull/2740 to be complete.

**Comment by bartlomieju** [comment]
Close in favor of #2852?

**Comment by ry** [comment]
Yes thanks
