### ISSUE TITLE
.d.ts prasing error: The module's source code could not be parsed

### ISSUE THREAD

**Issue by ije** [denoland/deno#27492]
```js
$ deno info -r  https://esm.sh/v135/@rollup/plugin-commonjs@11.1.0/types/index.d.ts
error: The module's source code could not be parsed: Expression expected at https://esm.sh/v135/@rollup/plugin-commonjs@11.1.0/types/index.d.ts:38:21

    namedExports?: { [package: string]: ReadonlyArray<string> };
```

Happens on **Deno 2.1.4**,  Deno 1.x.x is OK.

**Comment by marvinhagemeister** [comment]
The error is correct and can be reproduced in the [TypeScript playground directly](https://www.typescriptlang.org/play/?#code/JYOwLgpgTgZghgYwgAgGIHt3IN4ChnIDaADogNZwDmEAXMgM5hSiUC6dAShHACbogAbAJ4BBKFDhCAPI2YhKAPlwBfIA) .

> Identifier expected. 'package' is a reserved word in strict mode.(1212)

The word `package` is a reserved keyword in strict mode and cannot be used as an identifier. The list of reserved keywords is defined in [section 12.7.2 of the ECMAScript specification](https://tc39.es/ecma262/multipage/ecmascript-language-lexical-grammar.html#sec-keywords-and-reserved-words).

**Comment by ije** [comment]
@marvinhagemeister thanks for your explanation
