### ISSUE TITLE
Need a way to get the cache directory location

### ISSUE THREAD

**Issue by ry** [denoland/deno#2749]
`deno info https://deno.land/welcome.ts` will tell me the location of the cached files associated with that URL, but there's currently no way to just quickly print the location of the cache directory. I think `deno info` without arguments should do that.

**Comment by bartlomieju** [comment]
Additionally I'd suggest to display all redirections for a file if there are any

**Comment by bartlomieju** [comment]
> Additionally I'd suggest to display all redirections for a file if there are any

Nvm, redirections are included in deps
