### ISSUE TITLE
Support for custom console.log in objects and classes

### ISSUE THREAD

**Issue by galkowskit** [denoland/deno#2775]
In Node, there is a nice way to change the default output of `console.log` for any object, which is very handy for creating nice output for users without spewing the inner implementation.

https://nodejs.org/api/util.html#util_custom_inspection_functions_on_objects

Note that although my examples show only strings it is possible to return other types of stuff from that method.

It works like this:
```javascript
class Box {
    constructor(x) {
        this.x = x;
    }

    [util.inspect.custom](depth, opts) {
        return `Box(${this.x})`;
    }
}

console.log(new Box(5)); // => Box(5)
```

Or like this:
```javascript
const box = x => ({
    x,
    [util.inspect.custom]: (depth, opts) => `Box(${x})`,
})

console.log(box(5)); // => Box(5)
```

Maybe similarly to Node we could have API that looks kinda like this?
```javascript
class Box {
    constructor(x) {
        this.x = x;
    }

    [Deno.inspect.custom](depth, opts) {
        return `Box(${this.x})`;
    }
}

console.log(new Box(5)); // => Box(5)
```

AFAIK there is currently no way to do it in Deno, so I'm filing this feature as a backlog task.

**Comment by ry** [comment]
SGTM
