### ISSUE TITLE
Panic when handling errors for workers created from blobs.

### ISSUE THREAD

**Issue by qwerasd205** [denoland/deno#2797]
Reproduce with
```typescript
new Worker(URL.createObjectURL(new Blob(['throw 0'])));
```

```
thread 'tokio-runtime-worker-0' panicked at 'called `Result::unwrap()` on an `Err` value: ErrBox(JSError(V8Exception { message: "Uncaught 0", source_line: Some(""), script_resource_name: None, line_number: None, start_position: Some(-1), end_position: Some(-1), error_level: Some(8), start_column: None, end_column: None, frames: [] }))', src/libcore/result.rs:999:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
fatal runtime error: failed to initiate panic, error 5
Abort trap: 6
```

My guess is that it fails when resolving the source location because it's a blob.

**Comment by kitsonk** [comment]
Hmmm.  Yes, so there is a logic error.  Basically we incorrectly assume that essentially a worker that supplies it source code won't ever throw actually.  Not a good assumption.

https://github.com/denoland/deno/blob/045e74bb39d7743b774cfd2b889bc6ce1e1ad245/cli/ops/workers.rs#L136-L140

We need to properly handle errors returned from a worker, and not try to blindly unwrap them.

**Comment by kitsonk** [comment]
Actually looking, it feels like that might be a wider case.  A worker that throws synchronously as part of a main loop would also fail this way:

https://github.com/denoland/deno/blob/045e74bb39d7743b774cfd2b889bc6ce1e1ad245/cli/ops/workers.rs#L127-L128

**Comment by kitsonk** [comment]
Hmmm... the behaviour of errors in workers is a bit more complicated.  In Chrome, the following code:

```ts
const worker = new Worker(URL.createObjectURL(new Blob(['throw 0'])));

worker.onerror = (err) => {
  console.log(err);
  err.preventDefault();
}
```

Logs out an `ErrorEvent` and cancels its propagation.  If it isn't cancelled, then it bubbles up to window and triggers a call to `window.onerror` if it exists.

So ideally in Deno we would replicate that behaviour, where any totally uncaught errors are terminal.
