### ISSUE TITLE
re-enable request.body tests

### ISSUE THREAD

**Issue by ry** [denoland/deno#2828]
Tests removed here https://github.com/denoland/deno/commit/8f919465b09e0338148d22459fac70fd5d5c9089#diff-f61b1245115d8e0ef4d9f1149e37b642L18

Move @standardized/streams into //js. Solution outlined here: https://github.com/denoland/deno/pull/2826#issuecomment-525940737

**Comment by mattyclarkson** [comment]
> basically we just need to move it into //js rather than have it in node_modules... but the problem is I don't have support for `/// <reference types="..."/>`, so we need a streams.ts file which includes the TS and JS. Or, I need to add `/// <reference types="..."/>` support to https://github.com/ry/deno_typescript .... I think porting streams to typescript is the best route for now.

The code for @stardazed/streams is in [TypeScript](https://github.com/stardazed/sd-streams/tree/master/packages/streams/src).  What do we need to port?

Is there any chance we can get WHATWG streams enabled by default in `deno`? Happy to help out here: I have some transformers I'd like to use server side, in a CLI and in a service worker.

**Comment by mattyclarkson** [comment]
> What do we need to port?

Ah just saw that @mrkurt had already said that in [his comment](https://github.com/denoland/deno/pull/2826#issuecomment-525961475)

**Comment by nstott** [comment]
I'd like to give this a shot, 

just to clarify my understanding, what needs to be done is to 
- lift https://github.com/stardazed/sd-streams/tree/master/packages/streams/src into `cli/js/streams/` 
- undo most of https://github.com/denoland/deno/commit/8f919465b09e0338148d22459fac70fd5d5c9089
- make everything work again

is that it? anything I'm missing, or should pay attention to?

cc/ @mrkurt
