### ISSUE TITLE
Align inspect logic to classes

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#2849]
Now that we have a custom inspect symbol (#2791) we should as a default leverage that logic across the board instead of having a rather complex set of if statements:

https://github.com/denoland/deno/blob/0ce15f08c76f075948a132dd0f9f27855bd00a1d/js/console.ts#L325-L363

While all the logic here impacts built in classes, it would still be better the decorate the prototypes with the logic.  For example, to add this to `WeakMap` we would want to do something like this:

```ts
WeakMap.prototype[customInspect] = function inspect(): string {
  return "WeakMap { [items unknown] }";
};
```

**Comment by bartlomieju** [comment]
Console logic has received a few refactors since this issue was opened and we're pretty happy with the results. Closing as resolved.
