### ISSUE TITLE
GitHub app for deno modules

### ISSUE THREAD

**Issue by ry** [denoland/deno#2853]
It would be nice if we had an easy-to-use Github app which ran "deno test -A ." and reported green/red status.

It would also be cool to hook that up to the https://deno.land/x/ directory.

**Comment by axetroy** [comment]
How about `Github action`?

https://github.com/marketplace/actions/github-action-for-deno

**Comment by kevinkassimo** [comment]
@axetroy Did not see your comment 😅 I kind of also made something that seems to be working (though not elegant, currently on Glitch): https://github.com/denolib/test-bot

**Comment by axetroy** [comment]
@kevinkassimo 

This is part of the Deno eco-chain

Can we create a corresponding repository for the denolib organization to build the ecosystem chain?

`Docker`/`Github Action`/`Editor plugin`/`third-party providers(eg. heroku/now.sh)` and so on.

**Comment by kevinkassimo** [comment]
@axetroy Hmm sound good to me. I believe you also have the permission to create repos under @denolib?

**Comment by axetroy** [comment]
I have port repository to [denolib/deno-action](https://github.com/denolib/deno-action)

**Comment by hayd** [comment]
Can this be closed? should this be documented somewhere RE creating deno projects?
