### ISSUE TITLE
suggestion: Move CI to Github Actions

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#2863]
We should consider moving CI to GitHub Actions rather than maintaining both Travis and Appveyor for builds. GitHub Actions works with Linux, macOS and Windows and is free for open source projects (actually pretty similar to Azure Pipelines). It will be generally available starting November 13. Actions can also store artifacts for every build. This could be binaries, test results or other arbitrary files. It would also be very useful for contributors because forks would automatically have CI too. This means you don't need to open a PR on this repo to check if your commit/PR passes all of the tests on all platforms.

If this seems like a good idea I'll set this up now so once GitHub Actions is generally available we can move over right away. If this happens #1340 can be closed.

### References
https://github.com/features/actions
https://github.blog/2019-08-08-github-actions-now-supports-ci-cd/

**Comment by sholladay** [comment]
It might be a little simpler to just keep everything in Travis. They support Windows, macOS, and Linux now. So AppVeyor is unnecessary. Travis also allows forks to run CI if you want, but it is disabled by default due to the security implications.

**Comment by ry** [comment]
I would be interested in exploring this - especailly if someone wants to do the work to get it green :)

That said, we are in the middle of a major build system refactor (#2608), I think we should wait for that to complete before introducing any major CI changes.

**Comment by lucacasonato** [comment]
#2608 has landed so I'll try to get this to work. Building already works on win, macos and linux but tests are still failing. Ill try to get this working ASAP. https://github.com/lucacasonato/deno/runs/215070142

**Comment by lucacasonato** [comment]
#2968 adds this.

**Comment by ry** [comment]
moved to #2979
