### ISSUE TITLE
Upgrade to TypeScript 3.6

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#2869]
This is currently blocked by microsoft/TypeScript#33142 which a fix will be in 3.6.3, and while the fix will work, I still think it is not a full fix, but good enough for now.

Essentially they introduced code that assumes `process` is available in the runtime environment.

**Comment by bartlomieju** [comment]
Related issue #2789

**Comment by kitsonk** [comment]
So 3.6.3 is out, but there was a change in the format of diagnostics messages which is making the upgrade not super straight forward.  Basically the diagnostic message chain's property has changed from `DiagnosticMessageChain` to `DiagnosticMessageChain[]`.  Easy to change on TS and serialise, but a bit more complex to unwrap and restructure on the Rust side, because it is self-referential and deals with boxing.

I am working on it though.
