### ISSUE TITLE
new URL not working

### ISSUE THREAD

**Issue by timonson** [denoland/deno#2880]
let url = new URL("https://javascript.info/profile/admin")
let newUrl = new URL("tester", url)
console.log(newUrl.href)
//  https://javascript.infotester

When I use it in combination with import.meta the results are wrong, too. It cuts the whole dirpath there back to file://.

**Comment by nayeemrmn** [comment]
Hi! This was fixed in #2867 - I get `https://javascript.info/profile/tester`. It should be included in v0.18.0 when that's released. You can close this.

**Comment by timonson** [comment]
Oh thanks! I actually looked through the issues but couldn't find it.
