### ISSUE TITLE
Make integration tests rust unit tests

### ISSUE THREAD

**Issue by ry** [denoland/deno#2881]
I have some preliminary work here https://github.com/ry/deno/tree/itest

The idea is to remove all the `//tests/*.test` files and instead define a macro in Rust to declare a unit test for each. It would look something like this:

```rust
itest!(_001_hello {
  args: "run --reload 001_hello.js",
  output: "tests/001_hello.js.out",
});

itest!(_002_hello {
  args: "run --reload 002_hello.ts",
  output: "tests/002_hello.ts.out",
});

itest!(_003_relative_import {
  args: "run --reload 003_relative_import.ts",
  output: "tests/003_relative_import.ts.out",
});
```
See https://github.com/ry/deno/blob/itest/cli/integration_tests.rs for full code

The benefit of this is that they can be run in parallel and we will have less custom test infrastructure to maintain.

If someone is interested in finishing off my branch, let me know. I think it should be close to working - but needs some clean ups.

**Comment by bartlomieju** [comment]
> If someone is interested in finishing off my branch, let me know. I think it should be close to working - but needs some clean ups.

Yeah I can tackle that
