### ISSUE TITLE
Deno.isTTY() possibly reports incorrect value when running in GitHub Actions

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#2885]
This is a blocker for #2863.

In the `is_tty_test.TestIsTty` the `//tests/is_tty.ts` file gets run. This file logs the value of `Deno.isTTY().stdin`. Deno reports `true` in the Github Actions environment. The same check happens in python by calling `stdin.isatty()`. This reports false in the Github Actions environment. As these values do not equal the test fails.

Either python or deno are reporting an incorrect value here. What are the qualifications to return true in `Deno.isTTY()`? I am working on the Github Actions script in this repo: https://github.com/lucacasonato/deno/tree/github-ci.

**Comment by ry** [comment]
@lucacasonato I suggest just commenting out the tests for now... It may be that github actions actually is a tty.

**Comment by bartlomieju** [comment]
@lucacasonato still relevant?

**Comment by lucacasonato** [comment]
@bartlomieju Not sure. I'll try test it today.

**Comment by lucacasonato** [comment]
@bartlomieju  Just looked into it. The test seems to have been removed all together so this is not relevant anymore.
