### ISSUE TITLE
Build instructions in manual need updating

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#2886]
With the recent changes, the manual [build instructions](https://deno.land/manual.html#buildfromsource) are out of date.

**Comment by nayeemrmn** [comment]
They have been, unless I'm misunderstanding: https://github.com/denoland/deno/blob/master/website/manual.md#build-from-source
Does the website update with releases?

I guess build instructions need to be in sync with master unlike the rest of the docs, but is it worth doing anything about that? They won't change that often.

**Comment by kitsonk** [comment]
Hmmmm.. yeah, not sure, can't remember.  Yeah, likely part of the release process. Closing for now.
