### ISSUE TITLE
stack trace for 'Cannot resolve module'

### ISSUE THREAD

**Issue by Fenzland** [denoland/deno#2887]
If we give a wrong path for import, deno respond that:
#### sync improt
```javascript
import '/null';
```
```bash
> deno test.js
Cannot resolve module "file:///null"
```
#### dynamic improt
```javascript
import ('/null');
```
```bash
> deno test.js
error: Uncaught TypeError: Cannot resolve module "file:///null"
```

A stack trace can help us to find where we mess up.

**Comment by nayeemrmn** [comment]
For reference, here's node's:
```
Error: Cannot find module /mnt/c/Users/Nayeem/temp/b.mjs imported from /mnt/c/Users/Nayeem/temp/a.mjs
    at Loader.resolve [as _resolve] (internal/modules/esm/default_resolve.js:59:13)       
    at Loader.resolve (internal/modules/esm/loader.js:73:33)
    at Loader.getModuleJob (internal/modules/esm/loader.js:149:40)      
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:43:40)
    at link (internal/modules/esm/module_job.js:42:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```
We don't need a useless internal stack trace... but the `imported from` would be very helpful.

**Comment by kitsonk** [comment]
The way modules get resolve, there isn't necessarily a good stack trace, as this happens in the Rust side and can be during runtime or transpile time, though we should quote the module attempting to load the other module.

**Comment by kevinkassimo** [comment]
cc @bartlomieju as it relates to current `file_fetcher` design

**Comment by bartlomieju** [comment]
Thanks for ping @kevinkassimo I need to ponder on it for a while. It's easy when you run `.ts` file - TS compiler gives a nice error message. The problem is when running `.js` files - it's a "direct request" from V8 with not additional info, but I'm sure we can figure something out.

[self-assign]

**Comment by Fenzland** [comment]
> It's easy when you run `.ts` file - TS compiler gives a nice error message. 
That's not suit for dynamic imports. We may compile and import files at the different time.

for example
```typescript
// test.ts
import (Deno.args[1]);
```

```bash
> deno --allow-read test.ts ./exists_file.ts
Compile file:///tmp/test.ts
```

```bash
> deno --allow-read test.ts /null
error: Uncaught TypeError: Cannot resolve module "file:///null"
```
