### ISSUE TITLE
User agent fetch and import

### ISSUE THREAD

**Issue by Fenzland** [denoland/deno#2900]
[It looks like deno makes requests with a user agent of "reqwest/...", which seems to be the default coming from that Rust package.](https://github.com/pikapkg/web/issues/97#issuecomment-529621401) 
Maybe we need a standard compliant and Deno identified user agent when we import and run `deno fetch` with a url.

**Comment by FredKSchott** [comment]
+1, as mentioned in that issue we're able to detect `reqwest/*` in the user-agent for now, but it would be nice to get a more deno-specific user-agent so that we can more reliably serve Deno-specific transpilation/polyfills from the [Pika CDN](https://www.pika.dev/cdn/).

**Comment by kitsonk** [comment]
@FredKSchott awesome that folks are considering throwing some Pika CDN magic towards Deno!

(also, agree that we should provide a UA string... I suspect this is an easy fix though).  Feels like it should be a simple `Deno/{version}`)

**Comment by bartlomieju** [comment]
> (also, agree that we should provide a UA string... I suspect this is an easy fix though). 

Indeed it is. 

> Feels like it should be a simple `Deno/{version}`)

Agree, I'll add it later today :+1:

**Comment by FredKSchott** [comment]
Thanks y'all! I'll update the CDN check for both "reqwest/*" & "Deno/*".  

Looking forward to adding more Deno specific features to the Pika CDN in the coming months, but if you all have any ideas/requests feel free to shoot me a message / lmk! Better type def support via `@deno-types` is coming soon
