### ISSUE TITLE
is there any guideline to use npm modules within deno?

### ISSUE THREAD

**Issue by yrong** [denoland/deno#2904]

**Comment by bartlomieju** [comment]
Most of npm modules can't be used directly with Deno. 

Deno requires ES modules and imports with extensions. There is an issue for Node compatibility #2644 for tracking this

**Comment by ry** [comment]
@yrong  checkout this repo by @nzakas  https://github.com/humanwhocodes/env as an example.

**Comment by yrong** [comment]
@ry  Thanks for the example. Before I think since deno is based on V8 so is just a javascript runtime it is not a new language.  But from your demo seems there is some difference in the core api (Process.env vs Demo.env).  Is there any table of api comparison between the two. Say if  I want to migrate the elasticsearch javascript driver from node module  to demo module. What should I do?

**Comment by kitsonk** [comment]
V8 (and JavaScript language standard) do not address a lot of common functionality we expect in a runtime.  For example `console` is not part of JavaScript, nor is it provided by V8.  So any runtime has to provide this functionality.

The general design goal is that if a runtime feature is useful for a "server side" runtime and there is an existing web platform standard (or an emergent standard that is likely to be adopted) Deno will implement that.

When there isn't a standard, but there is a requirement to tightly bind to the host system, those APIs are exposed in the `Deno` namespace.  We try to deliver an API in that namespace that is logical, based on the best practices and common conventions of other languages, utilising modern JavaScript conventions and structures.

If that tight binding is not required, we try to deliver the API as part of the `deno_std` library, which should take strong design considerations from GoLang, but follow modern JavaScript conventions and structures.

So as stated, express interop with Node.js isn't a primary design consideration, but #2644 is designed to think about how we can make that easier.  A table of comparison, or scripts that help migration are certainly valid ideas about how to address it, though it hasn't yet been the focus of the "core" team.  Doesn't mean the wider community hasn't thought more about it though yet.

**Comment by FredKSchott** [comment]
If it helps your use-case, Pika CDN is a CDN for ESM npm packages. It will bundle up and serve any ESM package (/w dependencies) as a single JS file, with any internal common.js & node-isms removed. You can learn more here: https://www.pika.dev/cdn

packd-es is another option with a similar purpose: https://github.com/webcomponents-dev/packd-es

**Comment by Soremwar** [comment]
For future reference, I maintain a repository that lists available NPM libraries and their definition files for its use with TypeScript. Feel free to add suggestions for packages in the repo below.

https://deno.land/x/types/
https://github.com/Soremwar/deno_types

**Comment by lucacasonato** [comment]
I will close this as there are quite a few userland solutions to this:

- import through https://pika.dev, https://skypack.dev or https://jspm.dev
- importing npm modules directly through std/node
- projects like https://www.npmjs.com/package/denoify

If anyone wants to round these up as a page in the manual, that would be great.
