### ISSUE TITLE
bug: Type definitions not working with import "./a.d.ts" syntax

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#2909]
Trying to provide definitions to `prettier` I hit this bug.

Given following script:
```
// @deno-types="./vendor/standalone.d.ts"
import "./vendor/standalone.js";
// @deno-types="./vendor/parser_typescript.d.ts"
import "./vendor/parser_typescript.js";
// @deno-types="./vendor/parser_babylon.d.ts"
import "./vendor/parser_babylon.js";
// @deno-types="./vendor/parser_markdown.d.ts"
import "./vendor/parser_markdown.js";
```
Type definitions are not loaded. It is because of `importExportRegEx` in `//js/type_directives.ts` - it can't match `import "./foo.d.ts"` syntax.

I added second regex to match above syntax and it seems to work fine. I'll post a PR shortly.

CC @kitsonk

**Comment by kitsonk** [comment]
Ah, doh! I didn't cover that one.  Good catch.
