### ISSUE TITLE
Provide option to normalize benchmark graph for req/sec

### ISSUE THREAD

**Issue by ry** [denoland/deno#2914]
<img width="693" alt="Screen Shot 2019-09-11 at 12 36 47 AM" src="https://user-images.githubusercontent.com/80/64668628-456e0b00-d42c-11e9-8530-2140d2621e03.png">

We run our benchmarks on travis - this results in results with large variance in the HTTP benchmark. While there's no easy way to solve this without changing our setup, we can normalize the results.

We know that hyper is going to be the fastest server. If hyper say has a certain number of req/sec, say H, then we can normalize the other values by dividing thier throughput by H. This would extract the relative performance of each server.

This should be implemented as a purely client-side operation in [//website/app.ts](https://github.com/denoland/deno/blob/df5b6cdd7ff6ca3ee1814e5911fdae67b8b4fc60/website/app.ts). Ideally there'd be a toggle switch to view the raw results or the normalized results.

I think this only makes sense to apply to the req/sec benchmark and proxy req/sec benchmark.

**Comment by lucacasonato** [comment]
I'll take this on. `req_per_sec_proxy` doesn't have a hyper variant. What should I use as the baseline there?

**Comment by ry** [comment]
@lucacasonato the proxy throughputs should also be normalized to hyper

**Comment by lucacasonato** [comment]
Ah got it. I'll set that up in a minute then.
