### ISSUE TITLE
"cargo install deno"

### ISSUE THREAD

**Issue by ry** [denoland/deno#2942]
Currently the deno crate on crates.io is our "core" crate... which is essentially our binding to V8 without any of the ops, typescript, or other high-level functionality that makes up the deno CLI.

Now that we've switched to "cargo build" as our main build frontend (#2608), it's much easier for us to publish the cli crate to crates.io.

I suggest having [the deno crate](https://crates.io/crates/deno) be our cli crate, and have [deno_core](https://crates.io/crates/deno_core) be the core crate. This would allow people to "cargo install" the executable.

**Comment by kt3k** [comment]
ref: #3600
