### ISSUE TITLE
Shorthand for env variables

### ISSUE THREAD

**Issue by j-f1** [denoland/deno#2951]
I was reading through the `deno_std` codebase and noticed this pattern:

```js
const token = env()["GIST_TOKEN"]
```
http://deno.land/std/examples/gist.ts#L13

What do you think about making a shorthand for this?

```js
const token = env("GIST_TOKEN")
```

I’d be willing to open a PR to add this. However, if you feel like this pattern shouldn’t be encouraged, feel free to close this issue.

**Comment by ry** [comment]
SGTM
