### ISSUE TITLE
Importing a native module

### ISSUE THREAD

**Issue by robbym** [denoland/deno#296]
I know that using protobufs simplifies the writing of native modules, but how does importing them work?
What's the structure of it supposed to be?
How do we specify how the native module should be built?

**Comment by styfle** [comment]
Maybe the solution is to compile native modules to [wasm](https://webassembly.org/) files and import into deno?

I know that with Node.js you can use the [WebAssembly.compile()](https://github.com/nodejs/node/issues/16952#issuecomment-343666700) function just like you can in the [browser](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/compile) so maybe deno should support this.

**Comment by robbym** [comment]
I'm talking about importing libraries that talk to the underlying operating system.
Some examples would be:

- Serial Port
- USB
- WinAPI

**Comment by styfle** [comment]
Good point, for legacy software there would need to be a way to interface with it. 

But for new software, there are emerging standards like WebUSB that I think deno should adopt. 

https://developers.google.com/web/updates/2016/03/access-usb-devices-on-the-web

**Comment by ry** [comment]
Before we think about how to have native addons, I want to release a crate #1209  - that provides a way to link in native code (albeit only if you're building your own executable)

**Comment by nayeemrmn** [comment]
Closed in #3372.

**Comment by brandonros** [comment]
How would I implement something like a thin layer above `libusb` (or the existing `rusb` crate) with this if the return value for all plugin ops needs to be https://docs.rs/deno_core/0.48.1/deno_core/plugin_api/type.Buf.html?

I might be missing something obvious in terms of how to pass references as Box<[u8]>.

**Comment by jhg** [comment]
Hi, only to confirm my guess: the idea in Deno is lack of native modules and keep like a browser, interfacing with an standard js API, isn't?

Native modules are not only for "legacy"/"old" software, it is also to call things that are new but not web standards and maybe is not common in a web (interfacing the OS directly, etc).

I understand will not be allowed in Deno as that break the security that Deno wants.
