### ISSUE TITLE
Further work now that "cargo test" is the test runner

### ISSUE THREAD

**Issue by ry** [denoland/deno#2988]
As of 56ac638d93c96712d6c624e60dcfa4540d334b18, "cargo test" is the main and only test runner. test.py is gone.

Currently the "cargo test" test runner calls into python to launch the tests. See [//cli/tests/integration_tests.rs](https://github.com/denoland/deno/blob/56ac638d93c96712d6c624e60dcfa4540d334b18/cli/tests/integration_tests.rs)
- [x] Port TestFetch to Rust
- [x] Port TestRepl to Rust https://github.com/denoland/deno/pull/4096
- [ ] Port TestIsTty to Rust (These are currently in [//cli/tests/tty_tests.rs](https://github.com/denoland/deno/blob/56ac638d93c96712d6c624e60dcfa4540d334b18/cli/tests/tty_tests.rs), but should be merged into //cli/tests/integration_tests.rs)
- [x] Port permission_prompt_tests to Rust https://github.com/denoland/deno/pull/4129
- [ ] Port complex_permissions_tests to Rust
- [x] Port TestFmt to Rust
- [x] Additionally we also need should remove the top-level `//tests` symlink - which requires carefully updating many references in the code base.

**Comment by hayd** [comment]
Related port tools/http_server.py to rust #1453 .

**Comment by jsouto18** [comment]
@ry Hey, I would like to help porting TestRepl to Rust. How should I proceed to contribute for that task? Should I create a PR porting TestRepl only?

**Comment by ry** [comment]
@jsouto18 Go for it. Here's the python code https://github.com/denoland/deno/blob/master/tools/repl_test.py The Rust version should end up here https://github.com/denoland/deno/blob/master/cli/tests/integration_tests.rs
It should be a separate PR for TestRepl only.

**Comment by jsouto18** [comment]
@ry I'll try to close this issue by porting the remaining tests. Just one question, will it also resolve #3129?

**Comment by bartlomieju** [comment]
Remaining tests were ported in #4200
