### ISSUE TITLE
Consider enforcing dir-private modules starting with an underscore

### ISSUE THREAD

**Issue by gewoonwoutje** [denoland/deno#2990]
In the style guide, it says:
![image](https://user-images.githubusercontent.com/9407072/65288445-2a477d80-db47-11e9-8159-f8920f6949c8.png)

"By convention, only files [...]". I don't know if this style guide is for the internal deno files only, but have you considered enforcing this instead of maintaining the convention? Package privacy would not only be a nice convention, enforcing it would make it a nice feature also (I've certainly missed it in node). For instance, by throwing an error when a file is imported with an underscore outside of the current directory.

**Comment by kitsonk** [comment]
That is an internal style guide thing.  Enforcing it would break from standards, which might be useful for Deno, but would make it harder for others where that convention might be used for abstract classes or base classes which might have different scoping concerns.

It feels like things like these are best left up to linting tools, where it is a stylistic decision.

**Comment by ry** [comment]
I agree with @kitsonk. One of the major goals of Deno is to keep the module system very simple and web compatible. Underscores are a non-standard complexity - it should remain a convention.

Maybe we should just remove it from the style guide entirely...
