### ISSUE TITLE
WASI support for Webassembly

### ISSUE THREAD

**Issue by dnsco** [denoland/deno#3005]
I'd love to be able to use Deno as the glue for a bunch of backend wasm modules. The wasi interfaces is a systems interface for webassembly in non-web uses.

https://github.com/CraneStation/wasmtime  is a wasi-implementing wasm runtime in rust, though It has a different sandboxing model than v8's. 

I've seen WASI support mentioned in  a few other issues, so I wanted to centralize that part of the discussion.

related: #2552 #672 #1325

**Comment by kitsonk** [comment]
Yes, agreed, though [WASI](https://github.com/WebAssembly/WASI) is still real early in its development.  I think we would want to keep it quite experimental in Deno, even Deno being experimental, as I suspect there will be a lot of churn.  We might also want to consider getting involved in the working group as well.

**Comment by syrusakbary** [comment]
We will release soon a TypeScript package to run WASI modules very easily both in server-side and client-side. Perhaps Deno can be a great use case for integrating it!

Apart from this, the [Wasmer runtime can also embedded](https://github.com/wasmerio/wasmer-rust-example) easily in Rust. However it might make more sense to use v8 with a wrapper on top to be able to run WASI.

Either way, I'd love to help in any way!

**Comment by syrusakbary** [comment]
And here we go!

Here's the `@wasmer/wasi` package: https://github.com/wasmerio/wasmer-js/tree/master/packages/wasi ([npm package](https://www.npmjs.com/package/@wasmer/wasi))

The announcement is here: https://medium.com/wasmer/wasmer-js-9a53e837b80

Hope you can find it useful!!

**Comment by dnsco** [comment]
Rad!

**Comment by rsp** [comment]
Node already has an experimental WASI support in v13:

- https://nodejs.org/api/wasi.html

It may be useful to see how it is implemented and used. Example:

```js
const wasi = new WASI({
  args: process.argv,
  env: process.env,
  preopens: {
    '/sandbox': '/some/real/path/that/wasm/can/access'
  }
});
```

**Comment by caspervonb** [comment]
Published https://deno.land/x/wasi yesterday, it is still a work in progress as not every syscall can be mapped efficiently at the moment:

- `Deno.read` needs to be able to take an optional offset for a reasonable `fd_pread` implementation (https://github.com/denoland/deno/issues/3508).
- `Deno.write` needs to be able to take an optional offset for a reasonable `fd_pwrite` implementation (https://github.com/denoland/deno/issues/3508).

**Comment by caspervonb** [comment]
A little while later; this is the current implementation status looks something like this

| Name                      | Status  | Notes                                                                                  |
|---------------------------|:-------:|----------------------------------------------------------------------------------------|
| `args_get`                | &check; |                                                                                        |
| `args_sizes_get`          | &check; |                                                                                        |
| `environ_get`             | &check; |                                                                                        |
| `environ_sizes_get`       | &check; |                                                                                        |
| `clock_res_get`           | &check; |                                                                                        |
| `clock_time_get`          | &check; |                                                                                        |
| `fd_advise`               |         | This has no obvious path to implementation at this time.                               |
| `fd_allocate`             |         | This has no obvious path to implementation at this time.                               |
| `fd_close`                | &check; |                                                                                        |
| `fd_datasync`             |         | This is blocking on getting fdatasync(2) implemented upstream in Deno.                 |
| `fd_fdstat_get`           | &check; | This currently does not write flags and rights as we do not track those at the moment. |
| `fd_fdstat_set_flags`     |         | This has no obvious path to implementation at this time.                               |
| `fd_fdstat_set_rights`    |         |                                                                                        |
| `fd_filestat_get`         |         | This is blocking on getting fstat implemented upstream in Deno.                        |
| `fd_filestat_set_size`    |         | This is blocking on getting ftruncate implemented upstream in Deno.                    |
| `fd_filestat_set_times`   | &check; |                                                                                        |
| `fd_pread`                | &check; |                                                                                        |
| `fd_prestat_get`          | &check; |                                                                                        |
| `fd_prestat_dir_name`     | &check; |                                                                                        |
| `fd_pwrite`               | &check; |                                                                                        |
| `fd_read`                 | &check; |                                                                                        |
| `fd_readdir`              |         |                                                                                        |
| `fd_renumber`             | &check; |                                                                                        |
| `fd_seek`                 | &check; |                                                                                        |
| `fd_sync`                 | &check; | This is blocking on getting fsync(2) implemented upstream in Deno.                     |
| `fd_tell`                 | &check; |                                                                                        |
| `fd_write`                | &check; |                                                                                        |
| `path_create_directory`   | &check; |                                                                                        |
| `path_filestat_get`       | &check; |                                                                                        |
| `path_filestat_set_times` | &check; |                                                                                        |
| `path_link`               | &check; |                                                                                        |
| `path_open`               | &check; | Opening directories is not portable                                                    |
| `path_readlink`           | &check; |                                                                                        |
| `path_remove_directory`   | &check; |                                                                                        |
| `path_rename`             | &check; |                                                                                        |
| `path_symlink`            | &check; |                                                                                        |
| `path_unlink_file`        | &check; |                                                                                        |
| `poll_oneoff`             | &check; |                                                                                        |
| `proc_exit`               | &check; |                                                                                        |
| `proc_raise`              |         |                                                                                        |
| `sched_yield`             |         |                                                                                        |
| `random_get`              | &check; |                                                                                        |
| `sock_recv`               |         |                                                                                        |
| `sock_send`               |         |                                                                                        |
| `sock_shutdown`           |         |                                                                                        |

Most of these blockers are in master already so will be working moving this into std soon.

**Comment by banocean** [comment]
> A little while later (exactly one month of work to be precise); the current implementation status of snapshot_preview1 looks something like this
> Name 	Status 	Notes
> `args_get` 	✓ 	
> `args_sizes_get` 	✓ 	
> `environ_get` 	✓ 	
> `environ_sizes_get` 	✓ 	
> `clock_res_get` 	✓ 	
> `clock_time_get` 	✓ 	
> `fd_advise` 		This has no obvious path to implementation at this time.
> `fd_allocate` 		This has no obvious path to implementation at this time.
> `fd_close` 	✓ 	
> `fd_datasync` 		This is blocking on getting fdatasync(2) implemented upstream in Deno.
> `fd_fdstat_get` 	✓ 	This currently does not write flags and rights as we do not track those at the moment.
> `fd_fdstat_set_flags` 		This has no obvious path to implementation at this time.
> `fd_fdstat_set_rights` 		
> `fd_filestat_get` 		This is blocking on getting fstat implemented upstream in Deno.
> `fd_filestat_set_size` 		This is blocking on getting ftruncate implemented upstream in Deno.
> `fd_filestat_set_times` 	✓ 	
> `fd_pread` 	✓ 	
> `fd_prestat_get` 	✓ 	
> `fd_prestat_dir_name` 	✓ 	
> `fd_pwrite` 	✓ 	
> `fd_read` 	✓ 	
> `fd_readdir` 		
> `fd_renumber` 	✓ 	
> `fd_seek` 	✓ 	
> `fd_sync` 	✓ 	This is blocking on getting fsync(2) implemented upstream in Deno.
> `fd_tell` 	✓ 	
> `fd_write` 	✓ 	
> `path_create_directory` 	✓ 	
> `path_filestat_get` 	✓ 	
> `path_filestat_set_times` 	✓ 	
> `path_link` 	✓ 	
> `path_open` 	✓ 	Opening directories is not portable
> `path_readlink` 	✓ 	
> `path_remove_directory` 	✓ 	
> `path_rename` 	✓ 	
> `path_symlink` 	✓ 	
> `path_unlink_file` 	✓ 	
> `poll_oneoff` 	✓ 	
> `proc_exit` 	✓ 	
> `proc_raise` 		
> `sched_yield` 		
> `random_get` 	✓ 	
> `sock_recv` 		
> `sock_send` 		
> `sock_shutdown` 		
> 
> Most of these blockers are in master already so will be working moving this into std soon.

There us wasi preview 2 rn and it covers a more of apis
