### ISSUE TITLE
Better TLS support

### ISSUE THREAD

**Issue by ry** [denoland/deno#3009]
We've recently landed basic support for TLS in [Deno.dialTLS](https://github.com/denoland/deno/commit/045e74bb39d7743b774cfd2b889bc6ce1e1ad245). 

We're missing <s>listenTLS</s>, [better tests](https://github.com/denoland/deno/blob/045e74bb39d7743b774cfd2b889bc6ce1e1ad245/js/tls_test.ts#L4-L5), and [more configuration](https://github.com/denoland/deno/blob/045e74bb39d7743b774cfd2b889bc6ce1e1ad245/js/tls.ts#L6-L7).

(`fetch()` has supported HTTPS for a long time now, this issue is about raw TLS connections.)

**Comment by bartlomieju** [comment]
FYI I'll be working on it

**Comment by ry** [comment]
There are many small features for complete TLS support, but with `Deno.listenTLS()` landed, I think this can be closed. Many thanks to @bartlomieju and @jorsi for their work.
