### ISSUE TITLE
Want to uninstall deno and reinstall with brew.

### ISSUE THREAD

**Issue by evolify** [denoland/deno#3012]
How to uninstall deno?

**Comment by qwerasd205** [comment]
I would assume just remove `~/.deno` and remove whatever you have adding `~/.deno` to your path. I don't see any uninstall option in the install script, but it doesn't put any files anywhere else afaik so that should be sufficient.

**Comment by ry** [comment]
Just delete the binary - deno is a single file.

**Comment by evolify** [comment]
thanks
