### ISSUE TITLE
Can't build on master

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#3013]
I can't currently build on master (82dc1b8e59891a7ca0f1a5e67a3db952b918561c).  The build fails when running `./tools/setup.py` and trying to run it directly outside of the build also fails with the same error message which is:

```
$ ./tools/setup.py
binary download
/Users/kkelly/github/deno/third_party/depot_tools/cipd install gn/gn/mac-amd64 git_revision:152c5144ceed9592c20f0c8fd55769646077569b -root /Users/kkelly/github/deno/core/libdeno/buildtools/mac
Package gn/gn/mac-amd64 is up-to-date.
/usr/local/opt/python@2/bin/python2.7 /Users/kkelly/github/deno/third_party/depot_tools/download_from_google_storage.py --platform=darwin --no_auth --bucket=chromium-clang-format --sha1_file /Users/kkelly/github/deno/core/libdeno/buildtools/mac/clang-format.sha1
/usr/local/opt/python@2/bin/python2.7 /Users/kkelly/github/deno/core/libdeno/v8/tools/clang/scripts/update.py
/usr/local/opt/python@2/bin/python2.7 /Users/kkelly/github/deno/third_party/depot_tools/download_from_google_storage.py --platform=darwin --no_auth --bucket=denoland --sha1_file /Users/kkelly/github/deno/prebuilt/mac/sccache.sha1
release: Writing gn options to '/Users/kkelly/github/deno/target/release/args.gn'.
Traceback (most recent call last):
  File "./tools/setup.py", line 186, in <module>
    sys.exit(main())
  File "./tools/setup.py", line 41, in main
    gn_gen("release")
  File "./tools/setup.py", line 173, in gn_gen
    gn_args = generate_gn_args(mode)
  File "./tools/setup.py", line 131, in generate_gn_args
    if not os.path.exists(cacher):
  File "/usr/local/Cellar/python@2/2.7.16_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/genericpath.py", line 26, in exists
    os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

I have tried 1b1ae65a4a2acd55ead86c17e388f10a0e08938d which builds, but the commit after 56ac638d93c96712d6c624e60dcfa4540d334b18 breaks.  So it appears to be something in 56ac638d93c96712d6c624e60dcfa4540d334b18.

**Comment by hayd** [comment]
I think this may be a bug here:

https://github.com/denoland/deno/blob/045e74bb39d7743b774cfd2b889bc6ce1e1ad245/tools/setup.py#L130-L132

docs for find_executable say:

> Returns the complete filename or None if not found.

so perhaps should be `if not cacher:` ?

**Comment by nayeemrmn** [comment]
@kitsonk Did you try `cargo build`? You're not supposed to run `tools/setup.py` manually anymore: https://deno.land/manual.html#buildfromsource. I get that error too when I do.

Still looks like a bug, though. Probably doesn't have to be broken if it worked before `cargo test`.

**Comment by bartlomieju** [comment]
Hit the same problem yesterday, quick fix: `touch /Users/kkelly/github/deno/target/release/args.gn`

**Comment by ry** [comment]
The problem is that sccache isn't installed and it hits the error that @hayd pointed out?
