### ISSUE TITLE
bug: Windows hangs on double process.status()

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#3014]
Writing tests for HTTP proxy I hit this bug. Given such function:
```ts
async function testModuleDownload(): Promise<void> {
  const http = Deno.run({
    args: [
      Deno.execPath(),
      "--no-prompt",
      "--reload",
      "fetch",
      "http://deno.land/welcome.ts"
    ],
    stdout: "piped",
    env: {
      HTTP_PROXY: `http://${addr}`
    }
  });

  // notice await for status twice here
  await http.status();
  const httpStatus = await http.status();
  assertEquals(httpStatus.code, 0);
  http.close();
}
```

The tests passed fine on Linux/Mac but hang on Windows. This is definitely bad behavior, I can imagine situation where you await for status in two different places.

~~I imagine this issue can be easily solved like this:~~
```ts
// js/process.js
export class Process {
  private _runStatus
  ...
  async status(): Promise<ProcessStatus> {
    if (this._runStatus) {
      return Promise.resolve(this._runStatus)
    }
    this._runStatus = await runStatus(this.rid);
    return this._runStatus;
  }
  ...
}
```
Above solution probably won't work if status hasn't been resolved and two callers await the actual promise.

**Comment by c4spar** [comment]
I also hit this bug on Mac by calling 'Deno.status()` twice at the same time.
Here is a simple reproducible example:
```
const p = Deno.run({
  cmd: [
    Deno.execPath(),
    "-V",
  ],
});

const status = await Promise.all([
  p.status(),
  p.status(),
]);

// status never resolves
console.log("not printed");
```
The script hangs forever.

**Comment by Soremwar** [comment]
This is no longer reproducible on latest canary

**Comment by lino-levan** [comment]
I cannot reproduce this hang (on Mac OS or Windows). No idea when this got fixed.

I believe this issue should be closed.
