### ISSUE TITLE
Uncaught errors in workers should trigger onerror

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#3020]
Related to #2797 (fix in #3019)

Uncaught worker errors should trigger an `ErrorEvent` which can be handled by the `.onerror` handler.  For example this should work under Deno:

```ts
const worker = new Worker("./something.js");
worker.onerror = (evt) => {
  console.log(evt);
  evt.preventDefault();
};
```

If the error event isn't cancelled, it should bubble up to the `window.onerror` (as a normal `Error`).

**Comment by bartlomieju** [comment]
There's also related #2444. I took a try to fix that, but due to some quirks I decided to leave it for later. I can revisit this topic after your PR lands.
