### ISSUE TITLE
"deno doc lib.ts"

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#3021]
We should consider implementing a command that would essentially evaluate a script and its dependencies and output a JSON structure representing the important documentation information for that code.  This then could be used and ingested to generate static site documentation content for personal use or as part of a registry.

The TypeScript compiler API guide actually has a [nice little example of how to walk the TypeScript AST and write out types to a JSON structure](https://github.com/microsoft/TypeScript/wiki/Using-the-Compiler-API#using-the-type-checker).

For prior art or standards, I did a bit of research.  Looking at JSDoc3, it does not directly support a JSON structure, it emits HTML.  It has some plugins that allow you to change how it renders, but there is no good intermediary standard.  TypeDoc can produce an intermediary JSON blob, but it then can't ingest that for static site generation.  Even then the structure of the TypeDoc JSON still has some strong opinions about how code is done, which is not ideal way.  I really think we need to try to find something that meets our needs as there isn't really a good starting point that I can find.

Refs #2355 - `deno ast script.ts` the challenge I think is that there is there is a lot of information in there that is "useless" to the task of generating documentation, and some things are a bit hard to get to.  I think a structure that is more focused on documentation might be a better idea.

cc/ @j-f1

**Comment by crookse** [comment]
would something similar to the following suffice?

https://github.com/drashland/docable-ts-ast

disclaimer: i'm pretty amateur at generating TS ASTs

**Comment by kitsonk** [comment]
We should consider something derivative of what we use on the [website](https://github.com/denoland/deno_website2/blob/master/src/util/doc_parser.ts), and or something based off of [SWC](https://github.com/swc-project/swc) (more likely the latter to be honest).

**Comment by kdy1** [comment]
I'm going to write a `.d.ts` generator (with some simple type inference). Does it help?

**Comment by bartlomieju** [comment]
FYI I started work on this project in a separate repo: https://github.com/bartlomieju/deno_doc

@kdy1 in above linked project I intend to provide both JSON and text output (so one can run this to get text output in terminal or JSON to feed it to site generator). We could probably pool resources so we don't duplicate work.

**Comment by kdy1** [comment]
@bartlomieju If you need any help or have a question about swc, please feel free to ping me.

**Comment by obedm503** [comment]
Worth mentioning that MS is working on https://github.com/microsoft/tsdoc which seems like typescript's answer to `cargo doc`.
