### ISSUE TITLE
Deno.readFile wrong buffer byteLength

### ISSUE THREAD

**Issue by morille** [denoland/deno#3028]
The returned Uint8Array byteLength does not match its ArrayBuffer byteLength.

readFile.js
```
const bytes = await Deno.readFile("file.txt");
console.log(bytes.byteLength, "/", bytes.buffer.byteLength);
```
file.txt
```
Hello world
```
Command
```
deno readFile.js --allow-read
# output: 11 / 1536
```

**Comment by ry** [comment]
I think this is expected. The Unit8Array is a slice of a larger buffer - which is useful for performance.

**Comment by morille** [comment]
Have to `bytes.buffer.slice(0, bytes.length)` to have a "clean" buffer to work with... not painfull indeed but unexpected.
