### ISSUE TITLE
REPL issue with Top Level Await

### ISSUE THREAD

**Issue by kevinkassimo** [denoland/deno#3029]
Top level await has unexpected results in the repl:

```
> console.log(await Deno.stat("."));
// Waits forever...
```
The cause of this is that feeding the above line to `evalContext` (plainly a binding to create script and eval under the current context) yields the surprising error `SyntaxError: missing ) after argument list`, thus REPL assumes that there needs more input and waits.

This might be an upstream issue of V8.

**Comment by bartlomieju** [comment]
Fixed in https://github.com/denoland/deno/pull/7784
