### ISSUE TITLE
JSX support

### ISSUE THREAD

**Issue by keroxp** [denoland/deno#3037]
I'm happy if JSX is supported by default. JSX is useful template engine for the server side. TypeScript officially supports JSX and have its transformation options `--jsx` `--jsxFactory`. 

Currently Deno emits errors when compiling `.tsx` file even tough providing custom `tsconfig.json` file (It seems to be ignored 🤔). 

On the server side usage, we don't need `ReactDOM.render` function that is based on DOM and only `ReactDOMServer.renderToString` like function is needed.

So, how about adding basic jsx transformer to xml string in Deno?
Default compiler options will be like below:
```ts
"jsx": "react",
"jsxFactory": "Deno.h"
```

**Comment by ry** [comment]
fixed in #3038
