### ISSUE TITLE
CI: post benchmarks fails sometimes 

### ISSUE THREAD

**Issue by ry** [denoland/deno#3062]
https://github.com/denoland/deno/runs/248377571

```
Run # Note gh-pages branch is cloned into //gh-pages/ by
  # Note gh-pages branch is cloned into //gh-pages/ by
  # tools/benchmark.py, hence the following copy is ok:
  cp -r website/* gh-pages/
  cd gh-pages
  git remote add origin2 https://${DENOBOT_PAT}@github.com/denoland/deno.git
  git config user.email "propelml@gmail.com"
  git config user.name "denobot"
  git add .
  git commit --message "Update benchmarks"
  git push origin2 gh-pages
  shell: /bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/2.7.16/x64
    GH_ACTIONS: 1
    RUSTC_WRAPPER: sccache
    DENO_BUILD_MODE: release
    DENOBOT_PAT: ***
[gh-pages d610e14] Update benchmarks
 3 files changed, 3 insertions(+), 3 deletions(-)
 rewrite recent.json (98%)
To https://github.com/denoland/deno.git
 ! [rejected]        gh-pages -> gh-pages (fetch first)
error: failed to push some refs to 'https://***@github.com/denoland/deno.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
```

I suspect this is because two commits were landed in rapid succession - and gh-pages was posted to by the previous commit while tools/benchmarks.py was running. Note that `tools/benchmark.py` [does the checkout of gh-pages before it starts running the benchmarks](https://github.com/denoland/deno/blob/9049213867d30f7df090a83b6baf3e0717a4d2d2/tools/benchmark.py#L52-L55). This is confusing and undesirable - I'd rather it got checked out [after the benchmarks ran in the CI script](https://github.com/denoland/deno/blob/9049213867d30f7df090a83b6baf3e0717a4d2d2/.github/workflows/build.yml#L95-L104).

**Comment by chrmoritz** [comment]
A question: Can we assume here, that we only ever want to check out the `gh-pages` branch (for getting old benchmark result history) on CI and just show the current results (without history) if no CI is detected?

That way we could simplify the code a bit and prevent some issues like silently starting with a new data array, should the clone of the `gh-pages` branch fail.

**Comment by ry** [comment]
That assumption sounds reasonable to me.
