### ISSUE TITLE
perf: HTTP client should be shared

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#3068]
Some time ago we moved to `reqwest` for our internal HTTP client (#2822). Before that we were using shared `connector` to create new clients, that way connections were pooled and could be reused. Right now we're creating a new client instance for each request:

https://github.com/denoland/deno/blob/2a02107bba27685324e62bd099ccaaac9c3b08d5/cli/http_util.rs#L16-L30

Currently HTTP client is used for two tasks - implementing `fetch` API and downloading remote modules (in `file_fetcher`). As it is pointed in [`reqwest's` docs](https://docs.rs/reqwest/0.9.20/reqwest/async/struct.Client.html) we should change our implementation to use a single instance of client and share it. That should give another nice speed bump for TS compilation.

**Comment by GaryPWhite** [comment]
trying my hand here for hacktoberfest!
