### ISSUE TITLE
update `rand_core` version to remove dyn warning while building deno

### ISSUE THREAD

**Issue by trivikr** [denoland/deno#3073]
The following warning appears while trying to build deno with command `cargo build -vv`:
```
warning: trait objects without an explicit `dyn` are deprecated
  --> /home/trivikr/.cargo/registry/src/github.com-1ecc6299db9ec823/rand_core-0.4.2/src/error.rs:95:23
   |
95 |     cause: Option<Box<stdError + Send + Sync>>,
   |                       ^^^^^^^^^^^^^^^^^^^^^^ help: use `dyn`: `dyn stdError + Send + Sync`
   |
   = note: #[warn(bare_trait_objects)] on by default
```

Looks like this issue is fixed in rand_core in https://github.com/rust-random/rand/pull/813 and latest version needs to be imported

**Comment by hayd** [comment]
Thanks! Can you bump the version in a PR?

**Comment by ry** [comment]
I believe the version of rand is carefully chosen to avoid depending on multiple versions of the crate. If someone undertakes this, please ensure the executable does not grow.
cc @piscisaureus

**Comment by trivikr** [comment]
Output of running [cargo tree](https://github.com/sfackler/cargo-tree) in core: [cargo-tree.txt](https://github.com/denoland/deno/files/3694655/cargo-tree.txt)

Shortened version:
```
deno v0.19.0 (/home/trivikr/workspace/deno/core)
[dev-dependencies]
└── tokio v0.1.22
    ├── tokio-fs v0.1.6
    │   └── tokio-threadpool v0.1.15
    │       ├── crossbeam-deque v0.7.1
    │       ├── rand v0.6.5
    │       │   ├── rand_chacha v0.1.1
    │       │   │   └── rand_core v0.3.1
    │       │   │       └── rand_core v0.4.2
    │       │   │   [build-dependencies]
    │       │   │   └── autocfg v0.1.6
    │       │   ├── rand_core v0.4.2 (*)
    │       │   ├── rand_hc v0.1.0
    │       │   │   └── rand_core v0.3.1 (*)
    │       │   ├── rand_isaac v0.1.1
    │       │   │   └── rand_core v0.3.1 (*)
    │       │   ├── rand_jitter v0.1.4
    │       │   │   └── rand_core v0.4.2 (*)
    │       │   ├── rand_os v0.1.3
    │       │   │   ├── libc v0.2.62 (*)
    │       │   │   └── rand_core v0.4.2 (*)
    │       │   ├── rand_pcg v0.1.2
    │       │   │   └── rand_core v0.4.2 (*)
    │       │   │   [build-dependencies]
    │       │   │   └── autocfg v0.1.6 (*)
    │       │   └── rand_xorshift v0.1.1
    │       │       └── rand_core v0.3.1 (*)
```

**Comment by trivikr** [comment]
tokio 0.2.0 is currently in alpha and undergoing heavy development:
* GitHub: https://github.com/tokio-rs/tokio
* docs: https://docs.rs/tokio/0.2.0-alpha.6/tokio/

**Comment by trivikr** [comment]
tokio v0.2.0 is now stable https://github.com/tokio-rs/tokio/releases/tag/tokio-0.2.0
tokio upgrade task is being tracked in #3387

**Comment by trivikr** [comment]
Closing this issue, as these are just example warnings which would be resolved post tokio upgrade.

There are other warnings during the build which are not tracked in any issues.
