### ISSUE TITLE
Hashbang stripping language standard

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#3081]
It appears that a standard has finally emerged for stripping Hashbang's as part of the JavaScript language specification: https://github.com/tc39/proposal-hashbang.  It is allegedly shipped in Chromium 74, not sure if they implemented it in V8 (which they tend to do with all language spec stuff) or if they implemented it another way, but we should leverage it if it is in V8, as then we can stop dealing with it in our runtime.

**Comment by kitsonk** [comment]
This is stage 3 now, and implemented in both Chrome and Node.js 12+.  We should validate how this is implemented in V8 and use it.

**Comment by bartlomieju** [comment]
@kitsonk I think this issue is no longer relevant - before we hit V8 we're already stripping shebangs either during file load or AST parsing in SWC. Should we close it?
