### ISSUE TITLE
Add tab completion in REPL

### ISSUE THREAD

**Issue by sszczepa** [denoland/deno#3086]
One of the things that always bothers me about Node is that tab completion in the REPL doesn't work like PowerShell. I believe there is an opportunity to correct this with Deno.

In PowerShell, I can simply start the name of a command/file/etc... and cycle through of all the matches with tab (and in reverse order with shift + tab). For instance, typing in _Get-P_ and pressing shift will cycle through _Get-Package_, _Get-PackageProvider_, _Get-PackageSource_, etc... This is extremely helpful when searching for a command in the middle of writing some long pipeline, such as:

`Get-Process | Where cpu -gt 15 | Select name,cpu,description | ConvertTo-Json`

If for some reason I didn't remember _ConvertTo-Json_, which is the command for converting the objects in the pipeline to a JSON formatted string, all I would have to do is type in _convert_ and press shift a few times. This would quickly lead me to _ConvertTo-Json_ without having to stop mid-way through to look up the commandlet.

I see a properly implemented tab completion as extremely useful as it greatly speeds up the process of writing short scripts in the REPL. Wouldn't it be nice in Deno if you could type in any arbitrary string, like _con_, and then press tab (and shift+tab to reverse) to cycle through all matching objects/variables until you found _console_. From there you type the period, i.e.  _console._, and then again press tab to cycle through all of the available properties/methods (_console.log_, _console.warn_, _console.dir_, etc...).

**Comment by bitjson** [comment]
Just to note, the "cycling" style @sszczepa described is also how tab completion works in `zsh` and `fish` by default too.

The Node.js tab completion style matches the "tab-to-finish" completion style of default `bash` on most systems. E.g. if options  are `option-one` and `option-two`, completion will stop at `option-` until the user types a character to disambiguate between the remaining completion options. With `zsh`, the first tab will complete to `option-one`, and tabbing again will cycle to the next possible completion, `option-two`.

With `zsh` now the default for macOS users, I imagine even more systems will start defaulting to the "cycling" style as more users grow to expect it. It would be great if Deno did this from the start. 👍

**Comment by dubiousjim** [comment]
If we do implement this, please let it be something we can also turn off.

**Comment by bitjson** [comment]
> If we do implement this, please let it be something we can also turn off.

@dubiousjim if I'm understanding correctly, tab completion would only happen in places where you would be completing a word or selecting the property of an object (after typing a `.`). What is the use case for turning this off? (I guess if you regularly use the tab key to separate words in the REPL? Even for using the tab key to space the beginning of new lines, I don't think completion functionality would be triggered.)

**Comment by hayd** [comment]
This is a feature of rustyline, which is used by the repl.
(As is multiline editing!)

**Comment by dubiousjim** [comment]
I'd turn it off because I rely on the stopping-short to tell me that there's an ambiguity, because that's what bash does. I might not catch a beep or screen flash from the interface you're proposing.

**Comment by bitjson** [comment]
> I'd turn it off because I rely on the stopping-short to tell me that there's an ambiguity, because that's what bash does. I might not catch a beep or screen flash from the interface you're proposing.

Ah, that makes sense. After looking at it again, my earlier description was mistaken – the "cycling" is just an additional feature in `zsh`. The first tab only completes to the point of the ambiguity as with `bash`. It only differs in that pressing tab again in `bash` does nothing (just re-issues the warning sound), whereas `zsh` starts cycling through the available completions. So I think the `zsh` cycling feature wouldn't be a regression for you @dubiousjim. I just corrected my original comment above too, thanks. 👍
