### ISSUE TITLE
Invalid cross-device link (os error 18)

### ISSUE THREAD

**Issue by ilgazil** [denoland/deno#3092]
```typescript
const { makeTempDirSync, cwd, renameSync } = Deno;

const from = makeTempDirSync();
const to = `${cwd()}/foo`;

renameSync(from, to);
```

The code above results with this error:
`Uncaught Other: Invalid cross-device link (os error 18)`

It seems to be because of my device mount config. If rename is asked inside the same device, everything is fine.
```
$ df -h
Filesystem                  Size  Used Avail Use% Mounted on
tmpfs                       7.9G   53M  7.8G   1% /tmp
/dev/mapper/vg0-home        197G   59G  129G  32% /home
```

Any plan to implements `shutil.rename` instead or being complementary to `os.rename`?

**Comment by golavr** [comment]
same problem for me.
running deno inside docker container with volume mounted.

**Comment by jingkaimori** [comment]
The answer is given by TTTie in discord:
> You must copy the file from the first FS to the second FS and remove it from the original FS afterwards as it is the OS which does not allow rename() across devices.

but can we implement this procedure in `std/fs/move.ts` ?
