### ISSUE TITLE
Remove deno_std Github Action tasks 

### ISSUE THREAD

**Issue by ry** [denoland/deno#3093]
"cargo test" should run the deno_std tests. The only reason it is not is because the std tests are very slow due to https://github.com/denoland/deno/issues/2789.

https://github.com/denoland/deno/blob/e7562eed8c816cd0d97aab6b818d7c8453dbaa2b/.github/workflows/build.yml#L105-L112

To enable deno_std tests to run during "cargo test", simply uncomment the code in `cli/tests/std_tests.rs`:
https://github.com/denoland/deno/blob/e7562eed8c816cd0d97aab6b818d7c8453dbaa2b/cli/tests/std_tests.rs#L1-L25

**Comment by nayeemrmn** [comment]
Closed in #3344.
