### ISSUE TITLE
re-enable various deno_std tests

### ISSUE THREAD

**Issue by ry** [denoland/deno#3095]
In order to merge deno_std into the main repo, I had to disable a number of the unit tests.

This was done in  https://github.com/denoland/deno/commit/93f7f00c956c14620ef031626f124b57397ca867 

- [ ] std/installer/test.ts https://github.com/denoland/deno/blob/e7562eed8c816cd0d97aab6b818d7c8453dbaa2b/std/installer/test.ts
- [ ] std/http/file_server_test.ts  https://github.com/denoland/deno/commit/93f7f00c956c14620ef031626f124b57397ca867#diff-6ff9e92d2f44af75a25c5b52e71db0acR33
- [ ] std/prettier/main_test.ts https://github.com/denoland/deno/commit/93f7f00c956c14620ef031626f124b57397ca867#diff-06031867d731de4d26acc3831f7888a2R211

**Comment by nayeemrmn** [comment]
Closed in #3154 and #3159.
