### ISSUE TITLE
failure: start REPL without an existing DENO_DIR

### ISSUE THREAD

**Issue by CGQAQ** [denoland/deno#3104]
```
➜  try deno
> 
Unable to save REPL history: "/home/jason/.cache/deno/deno_history.txt" directory does not exist
```

**Comment by nayeemrmn** [comment]
ref #2727

It is intentional... but I believe it was a temporary solution as opposed to panicking. Obviously the directory should be created in this situation.

I don't think this has a tracking issue. Change the title to "DENO_DIR should be created if nonexistent when saving REPL history".

**Comment by ry** [comment]
I see, if you start the REPL without an existing DENO_DIR cache directory, it fails? Yes we should fix that.

**Comment by nayeemrmn** [comment]
@ry It seems to be when the REPL ends.

**Comment by bartlomieju** [comment]
@nayeemrmn can you fix it?

**Comment by CGQAQ** [comment]
> @ry It seems to be when the REPL ends.

Yes, it is, that error msg was showed up after I hit Ctrl+C to quit deno repl
