### ISSUE TITLE
Support @ts-check without config file

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#3107]
We should support `// @ts-check` if we load a `.js` file that contains the pragma but where we aren't using a custom `tsconfig.json`.

Currently it would only apply with `checkJs` true, which is actually redundant at that point.

**Comment by kitsonk** [comment]
Closed via #3114

**Comment by bartlomieju** [comment]
@kitsonk #3114 never landed

**Comment by bartlomieju** [comment]
@kitsonk is this issue still actionable after recent refactors?

**Comment by kitsonk** [comment]
I believe it is now working.
