### ISSUE TITLE
URL interface display

### ISSUE THREAD

**Issue by cup** [denoland/deno#3124]
Firefox can display the different parts of a URL:

~~~js
new URL('https://github.com')
URL { href: "https://github.com/", origin: "https://github.com", protocol:
"https:", username: "", password: "", host: "github.com", hostname:
"github.com", port: "", pathname: "/", search: "" }
~~~

However Deno looks like it would require you to view each property individually:

~~~js
> new URL('https://github.com')
URL { _parts: { protocol, username, password, hostname, port, path, query,
hash}, _searchParams: URLSearchParams { params: [], url: [Circular], append:
[Function], delete: [Function], set: [Function] } }
~~~

**Comment by kitsonk** [comment]
This feature request can be resolved by implementing a custom inspection method (see: #2791).

**Comment by cup** [comment]
Looks like Node works as expected:

~~~
> new URL('https://github.com')
URL {
  href: 'https://github.com/',
  origin: 'https://github.com',
  protocol: 'https:',
  username: '',
  password: '',
  host: 'github.com',
  hostname: 'github.com',
  port: '',
  pathname: '/',
  search: '',
  searchParams: URLSearchParams {},
  hash: '' }
~~~

**Comment by kitsonk** [comment]
Again, it just needs a custom inspection method.

**Comment by cup** [comment]
@kitsonk I dont understand what you are saying. Is this something the user needs to do - or is it something that needs to be fixed and/or improved with the software?

**Comment by kitsonk** [comment]
I am saying the resolution to this issue is straight forward.  The behaviour is not desirable.  It is any easy issue for someone to fix if they wanted to contribute to Deno.

**Comment by ry** [comment]
It might be simpler to just restructure our URL class to not have _parts but rather members? Is that how Node's is implemented?

**Comment by cup** [comment]
@ry I dont know

**Comment by kitsonk** [comment]
@ry IIRC there are quite a few magical things about some of the `_parts` which meant it wasn't super easy to just be first class properties and make it match the standard.  Also there are some hidden implementation details that we wouldn't want to leak even if the `_parts` were public properties.

**Comment by svnv** [comment]
I have been looking at this and, while it is trivial to make a custom inspection method for the URL class I think the best solution would be to make the `createRawObjectString()` function in [console.ts](https://github.com/denoland/deno/blob/b81e5db17aa8b3088d6034ddf86b79c69410f012/cli/js/console.ts#L276) ignore the private and protected properties, but I'm not sure if that is possible to do in typescript.

The `createRawObjectString()` function also only lists the keys and hides the values if there are more than 5 keys in the object being inspected, so we would also need to override that somehow, or change the current default of `OBJ_ABBREVIATE_SIZE`.

Also this is kind of related to issue: https://github.com/denoland/deno/issues/3165

**Comment by kitsonk** [comment]
@svnv the custom inspection symbol is very similar to the way Node.js accomplishes it.  So implimenting it for this would be very much in line with #3165.

There is insufficient type information at runtime to make the sort of modifications you are suggesting to `createRawObjectString()`.  Even then, that wouldn't necessarily be the right solution in all cases.

There _might_ be some value in exporting some functions from `console.ts` to keep things DRY, but the solution is still to implement the custom inspector.

**Comment by svnv** [comment]
I will work on a PR adding a custom  inspect method for the URL class.
