### ISSUE TITLE
wrong code example

### ISSUE THREAD

**Issue by shadowkun** [denoland/deno#3133]
**at** "https://deno.land/manual.html"
'''
that exports the third-party code:

export { test, assertEquals } from "https://deno.land/std/testing/mod.ts";
And throughout the same project, you can import from the deps.ts and avoid having many references to the same URL:

import { test, assertEquals } from "./deps.ts";
'''
**should modify to :**
'''
that exports the third-party code:

export { assertEquals } from "https://deno.land/std/testing/asserts.ts";
export { test, runIfMain} from "https://deno.land/std/testing/mod.ts";
And throughout the same project, you can import from the deps.ts and avoid having many references to the same URL:

import { test, assertEquals, runIfMain } from "./deps.ts";
'''

**Comment by kevinkassimo** [comment]
Do you mind submitting a PR for this? Thanks!

**Comment by galkowskit** [comment]
I believe this should be marked as a good first issue. If OP doesn't want it, I'll happily grab it.
