### ISSUE TITLE
refactor: Resource table

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#3134]
Before working on #2180 we need to address situation with resource table. Resource table is used to store resource ids with their corresponding representations. 

https://github.com/denoland/deno/blob/b1685ce0101f9ca16b0eeb6db7ff16ac81301545/cli/resources.rs#L56-L104

There are two problems with this approach:
- all resource related logic lives in `cli/resources.rs`, instead logic for each kind of resource should live alongside ops code that utilizes it
- all representations are hard coded which effectively prohibits splitting ops into separate crates - CLI would still have to be aware what kind of resource each op can use

We want `ResourceTable` to expose public API allowing op crates to register any resources they see fit to utilize (eg. `process` crate would implement resources analogous to `Repr::Child`, `Repr:ChildStdin`, `Repr:ChildStdout` and `Repr:ChildStderr`). 

That means that `ResourceTable` should be a struct mapping resource ids to boxed trait objects. The trait could be as simple as:
```rust
trait Resource {
  pub fn close(&self);
}

struct ResourceTable(HashMap<Rid, Box<dyn Resource>>);
```
Trait objects from `ResourceTable` would then be upcasted into concrete type inside the op.

New resource table should be a `core` concept. It should be first implemented for `deno_core_http_bench`, then we should refactor `cli::resources::RESOURCE_TABLE`.

I'll be working on it.

CC @ry @piscisaureus

**Comment by ry** [comment]
Good write up. There are a couple bits of machinery implicit in this that are worth mention explicitly:

1. There should be a way to register new resources at runtime, obtaining a new rid.
2. Resource objects should be up-casted inside the op implementations.
3. resource.close() removes a resource from the table.
