### ISSUE TITLE
Limited Permission for --allow-env

### ISSUE THREAD

**Issue by keroxp** [denoland/deno#3137]
Currently `--allow-env` gives program unlimited permission to access any environment variable. It's much strong privilege and there should be more limited permission control for them.

Like `--allow-net=:9999`, how about these? `--allow-env=DEBUG`, `--allow-env=DENO_DIR,DENO_INSTALL` 

`Deno.env()` should also be re-designed to get permitted variables.

I think even if full access to envars given to the process, It's dangerous to return key-value pair of all environment variables because malicious  attackers are able to  know  some secret informations if they don't know envar's name. So how about re-design `Deno.env` to immutable map-like object?

```
Deno.env.get("DENO_DIR")
Deno.env.set("DEBUG", "*")
Deno.env.has("PORT")
```

**Comment by kt3k** [comment]
FYI Deno.env now takes string as argument. See #2951 #2952

**Comment by keroxp** [comment]
@kt3k I never know! But setting environment variables should also be managed, shouldn't it?

**Comment by brandonkal** [comment]
Agree on this one. It feels odd requiring `--allow-env` just to do:
```ts
const cfg = path.join(Deno.dir('home'), '.myapprc')
await fs.readFileStr(cfg)
```

For a lot of applications I find Deno.dir() is the only method that requires `--allow-env`.

**Comment by keroxp** [comment]
I researched which op needs allow-env privilege and found that some ops actually don't touch any environment variables:

|  op  |  touch envars?  | method |
| ---- | ---- |  ---- |
|  op_get_dir  |  o  | dirs::xxx_dir()  |
|  op_exec_path  |  x | current_exe |
| op_set_env | o | env::set_var |
| op_env | o | env::vars() |
| op_get_env | o|  env::var(args.key) | 
| op_loadavg | x | sys_info::loadavg() |
| op_hostname | x | sys_info::hostname() |
| op_os_release | x| sys_info::os_release() |

I think we should separate `--allow-env`, privilege for access envars and `--allow-sys`,  for access sys_info. `op_get_dir` use some envars as return value but It seems strange to require `--allow-env`.

**Comment by keroxp** [comment]
RFC is here:

### Permission separation
| ops | privilege |
| ---- | ---- |
| `op_get_dir`, `op_exec_path`, `op_loadavg`, `op_hostname`, `op_os_release` |  `--allow-sys` |
| `op_env` , `op_get_env` , `op_set_env` |  `--allow-env` |

### syntax for `--allow-env`

| syntax | desc|
| ---- | ---- |
| `--allow-env=DENO_DIR` | Single |
|`--allow-env=DENO_DIR,DENO_INSTALL` | Multiple |
|`--allow-env=DENO_*` | With UNIX wild card |
|`--allow-env` | Unlimited |

### Deno.env() API

It may be possible to keep current API. `Deno.env()` will throw error if `--allow-env` (Unlimited) is not set.

**Comment by brandonkal** [comment]
I like the proposed `--allow-env` syntax but I am not sure about separating `op_hostname`. In many environments it is also available on the `HOSTNAME` environment variable.

**Comment by keroxp** [comment]
I've understood that`sys_info::hostname()` is just wrapper of `gethostname` systemcall. No value was assigned to `$HOSTNAME` in my machine (macOS). Does it get value from envar?

**Comment by brandonkal** [comment]
@keroxp Interesting.
I've always had a $HOSTNAME on my macOS machines (now 10.13.6).
```sh
$ echo $HOSTNAME
Mac-Pro.local
$ hostname
Mac-Pro.lan
```
And on Ubuntu
```sh
$ echo $HOSTNAME
dev
$ hostname
dev
```
Same for Ubuntu boxes.
I just checked and it is not in any of my personal bash profile files.

**Comment by brandonkal** [comment]
On my other point about, `Deno.dir('home')`. It is very easy to determine HOME just by looking at:
- import.meta.url
- Deno.build.os
So it is odd having this one behind a permission flag at all.

**Comment by jsejcksn** [comment]
@brandonkal That's generally true for default configurations, but not for customized environments. I think it's still useful to have behind a permission.

**Comment by caspervonb** [comment]
Prior art in WebAssembly runtimes like wasmtime is to provide a single env variable with `--env "foo=bar"` which can be repeated.

**Comment by brandonkal** [comment]
I would vote for the csv format to be consistent. Parsing = could be a nice convenience. But then the program is not actually reading an environment variable.

**Comment by ry** [comment]
@caspervonb How do you give env an existing value from the env? Would it just be `--env "foo=$foo"` ?

Seems elegant enough.

**Comment by SyrupThinker** [comment]
How about `--env "foo,bar,baz=1" `? With interpolation I need to ensure its properly escaped

**Comment by brandonkal** [comment]
Yes if `--allow-env` were to support manually setting environment variables something like
`--allow-env "foo,bar,baz=1"` would be more consistent.

So I could do something like this:
```
DEBUG=* deno run --allow-env=DEBUG,TEST main.tsx
```

Of course the current alternative is something like this:

But when you can already do
```
env -i HOME=$HOME PWD=$PWD PATH=$PATH DEBUG=* TEST=$TEST deno run --allow-env main.ts
```

it feels odd to have Deno parsing $ variables when the shell is as well.

**Comment by jsejcksn** [comment]
Escaped like this? `--allow-env=“FOO”,”BAR”,”BAZ=$QUX”`

**Comment by caspervonb** [comment]
> @caspervonb How do you give env an existing value from the env? Would it just be `--env "foo=$foo"` ?
> 
> Seems elegant enough.

Exactly that, existing values would have to be filled in by the caller, e.g shell.

Parsing is dead simple https://github.com/bytecodealliance/wasmtime/blob/main/src/commands/run.rs#L28, it just splits on the first equals sign.

Wasmer also does the same thing https://github.com/wasmerio/wasmer/blob/master/src/commands/run.rs#L291.

**Comment by jsejcksn** [comment]
If the format for `--allow-env` is changed to `--env`, it would break consistency with the other `--allow-*` permissions.

But keeping the comma-separated format doesn't preclude optional assignments using `=`.

**Comment by caspervonb** [comment]
It would be orthogonal, --allow-env gives blanket access to the host environment, --env fills in a single environment variable.

**Comment by jsejcksn** [comment]
> Comma separated list is easy to break, as its commonplace for env variables to contain comma seperated lists.

Related: https://github.com/denoland/deno/issues/6553

**Comment by SyrupThinker** [comment]
> existing values would have to be filled in by the caller

> commonplace for env variables to contain comma seperated lists

Exactly this makes string interpolation bad because:
`a="a,b,c=1" deno ... --env "a=$a"` ...` results in
`--env 'a=a,b,c=1'` which is obviously not what meant.

Quoting wouldn't help because `a="Secret'with,weird,chars" deno ... --env "a='$a'" ...` it'd break like `--env "a='Secret'with,weird,chars'".

And doing something like `--env "a=$(deno escape $a)" ` is plain ugly.

**Comment by caspervonb** [comment]
> --env 'a=a,b,c=1' which is obviously not what was meant.

Why is it obviously not what was meant? --env only allows a single variable to be set, so the value can be anything.

**Comment by SyrupThinker** [comment]
I misunderstood how you meant "a comma separated list is easy to break". I thought you meant breaking apart (aka splitting), sorry.

The last few comments didn't make that obvious to me.

**Comment by caspervonb** [comment]
> I misunderstood how you meant "a comma separated list is easy to break". I thought you meant breaking apart (aka splitting), sorry.

Ah no i meant break as in it's commonplace to have commas in environment variable values which then any attempts at a parser would be very likely to mangle.

**Comment by webdeb** [comment]
> If the format for --allow-env is changed to --env, it would break consistency with the other --allow-* permissions.

Thats, right. 

But if `--env` could just _provide_ the env values into the process memory, still not allowing access to the actual env. Most people are using environment variables during the init phase once and have them in a const anyway.

**Comment by jsejcksn** [comment]
Not stale
