### ISSUE TITLE
Documenting architecture decisions

### ISSUE THREAD

**Issue by andyfleming** [denoland/deno#3158]
While I don't think we need a formal process, I think it would be nice to document and discuss key decisions, especially early on in the project and before 1.0.

Some of this happens in GitHub issues and PRs naturally, but it would be nice to be able to aggregate it somehow. Maybe even just an issue label would be sufficient.

**Examples of existing decisions might include:**

* Deno uses V8 for its javascript runtime
* Deno builds in a TypeScript compiler
* Deno leverages Rust for its built-in functionality outside of V8
* Deno keeps compatible javascript with browsers
* Deno leverage web APIs where possible
* Deno disallows file access by default
* Deno disallows network access by default
* Deno disallows environment access by default
* Deno prompts the user to allow access when attempted
* Deno provides a built-in test-runner

**Some examples I'd want to discuss and document:**
* Deno should treat modules/files loaded from remote URLs as immutable and indefinitely cacheable
* Deno avoids leaking details of V8 to user scripts

**Ideas for other topics**
* Should Deno provide a clear workflow and tools for node package creators to export a deno-compatible package?

**Comment by rluvaton** [comment]
> **Ideas for other topics**
> 
> * Should Deno provide a clear workflow and tools for node package creators to export a deno-compatible package?

There is a GitHub repo that kind of do that https://github.com/garronej/denoify
