### ISSUE TITLE
console.log() should stringify objects exactly as Node does

### ISSUE THREAD

**Issue by ry** [denoland/deno#3165]
Match colors and semantics. 

node's stringify has been tweaked and optimized over many years, changing anything is likely surprising in a bad way.

**Comment by mhvsa** [comment]
I'll work on it

**Comment by Lonniebiz** [comment]
@mhvsa Did you notice that there seems to be a 5 property limit when it comes to displaying property values via `console.log`?
https://github.com/denoland/deno/issues/3213

**Comment by tisd** [comment]
Hey @mhvsa, i wanted to work on this, can you suggest where to start.
Thanks.

**Comment by mhvsa** [comment]
Sorry for being dead in Deno for quite a time.

Hey @tisd 

Node implementation: 
https://github.com/nodejs/node/blob/master/lib/internal/console/constructor.js

I would start with formatting and do colors later.

GL

**Comment by tisd** [comment]
Thanks @mhvsa.

**Comment by jsejcksn** [comment]
Can we presently override the behavior introduced in #1969 so that we can see values in the output, or do we need to use `JSON.stringify` until this issue is resolved?

**Comment by brandonkal** [comment]
Formatting logic to port starts here:
https://github.com/nodejs/node/blob/a751389a14ddb3571e3ade22ac472b9aeb912bc0/lib/internal/util/inspect.js#L1778

**Comment by fabrizzioalco** [comment]
Hey, i would like to check on this.

**Comment by bartlomieju** [comment]
With #6591 landed I believe this issue can now be closed.
