### ISSUE TITLE
Deno should have a lock file

### ISSUE THREAD

**Issue by andyfleming** [denoland/deno#3178]
Opening this issue to make it easier to find #200 

#### Search terms
- deno lock
- deno-lock.json
- deno.lock
- lock file
- package-lock.json
- security

**Comment by hayd** [comment]
deno.lock seems reasonable (and in line with Cargo/Bundler).

I suspect the issue will be looking it up: Does it have to be provided explicitly? or does deno search for it? In which directory (cwd or directory of file)? Any option seems a little magical...

OTOH this does seems a good way to be "secure by default".

**Comment by ry** [comment]
Let's move the discussion to #200

But I think we can ask people to explicitly specify if they want lockfile checking/writing.
