### ISSUE TITLE
welcome.ts not found

### ISSUE THREAD

**Issue by sidvishnoi** [denoland/deno#3189]
The introductory command `deno https://deno.land/welcome.ts` fails as https://deno.land/welcome.ts says "not found"

```
$ deno https://deno.land/welcome.ts
error: Uncaught SyntaxError: Unexpected token '<'
► https://deno.land/welcome.ts:1:1

1 <!doctype html><html lang="en"><head><meta charset="utf-8"/><link rel="icon" href="/favicon.ico"/><meta name="viewport" content="width=device-width,initial-scale=1"/><meta name="theme-color" content="#000000"/><meta name="description" ....
```

![image](https://user-images.githubusercontent.com/8426945/67387486-96892700-f5b4-11e9-9e4d-cf93a1f8c563.png)

**Comment by nayeemrmn** [comment]
This was _just_ moved to https://deno.land/std/examples/welcome.ts... The old one shouldn't have been removed yet but it appears it wasn't added to the new site.

cc @ry

**Comment by ry** [comment]
Fixed the link on the home page.

**Comment by nayeemrmn** [comment]
@ry There are references to it in the manual as well... we have two of those right now and they'll diverge.
