### ISSUE TITLE
//website is dead code

### ISSUE THREAD

**Issue by ry** [denoland/deno#3193]
Since https://github.com/denoland/deno_website2 the code in //website is dead. We need to figure out what to do with it.

Should website2 be merged into the main repo? Having netlify CI run for unrelated changes seems undesirable. 

Maybe denoland/deno should be a submodule of website? Then we can maintain manual.md and style_guide.md in the main repo...

**Comment by nayeemrmn** [comment]
+1 for the second option.

**Comment by lucacasonato** [comment]
> +1 for the second option.

I like this approach but afaik Netlify wont trigger on updates to the submodule. We would still have to manually update the submodule version in the website repo.

**Comment by chrmoritz** [comment]
Also the benchmark results are currently still published from within this repo. This could possibly be moved to be published to the new `deno_website2` repo via Netlify too.

**Comment by Janpot** [comment]
If I understand correctly you can run github actions [only when certain paths have changed](https://help.github.com/en/github/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#example-including-paths). Maybe that would solve your problem of CI?

**Comment by ry** [comment]
We've decided to keep deno_website2 as a separate repository. And rather than having deno be a submodule of website2, I'm going to simply move the manual.md and style_guide.md into //std so they can be accessed like other markdown files. Then there is no need for special handling of them.
