### ISSUE TITLE
Link to latest output of `deno types` in manual

### ISSUE THREAD

**Issue by trivikr** [denoland/deno#3207]
The [deno types section](https://deno.land/std/manual.md#deno-types) in website manual links to an outdated output of deno types https://gist.github.com/ry/46da4724168cdefa763e13207d27ede5

The latest output of `deno types` with v0.21.0 can be viewed at https://gist.github.com/trivikr/1d3f6d157b6b311dedd4661ffade6362

Can we link to the latest `deno types` output when a new release is out?

**Comment by josephsintum** [comment]
I think this issue should be on [deno website](https://github.com/denoland/deno_website2)
So I am going to fix that problem on the website

**Comment by josephsintum** [comment]
I'm going fix it

**Comment by josephsintum** [comment]
https://github.com/denoland/deno/pull/3220

**Comment by josephsintum** [comment]
#3225

**Comment by trivikr** [comment]
Fixed in #3225
