### ISSUE TITLE
TCP accept loop doesn't use for-await

### ISSUE THREAD

**Issue by ry** [denoland/deno#3216]
Currently to accept connections from TCP server the API is this:

```javascript
  const listener = Deno.listen({ port: 1234 });
  console.log("Listening on", addr);
  while (true) {
    const conn = await listener.accept();
    handle(conn);
  }
```
Would it be better to instead use a for-await loop? ([Especially since top-level-for-await is now supported](https://github.com/denoland/deno/pull/3212)).

If the API is changed, we should also make sure that `listenTCP` is similarly updated.

**Comment by nayeemrmn** [comment]
What do you mean by API change? `Listener`s already have `[Symbol.asyncIterator]()`.

**Comment by ry** [comment]
Oops I forgot about that :)
