### ISSUE TITLE
error trace miss full url when a .ts file imports from network

### ISSUE THREAD

**Issue by Fenzland** [denoland/deno#3219]
### /tmp/test.ts
```typescript
function foo()
{
	return new Error();
}

const bar= ()=> foo();

function main()
{
	console.log( bar(), );
}

main();
```

```sh
deno --allow-net test.ts
Error: 
    at foo (file:///tmp/test.ts:5:9)
    at bar (file:///tmp/test.ts:8:17)
    at main (file:///tmp/test.ts:12:15)
    at file:///tmp/test.ts:15:1
```
We can get the full url from the trace then locate the error.

Now let's just add a network import at the first of `test.ts`.
### /tmp/test.ts
```typescript
import 'https://deno.land/std/examples/welcome.ts';

function foo()
...
```
```sh
deno --allow-net test.ts
Welcome to Deno 🦕
Error: 
    at foo (test.ts:5:9)
    at bar (test.ts:8:17)
    at main (test.ts:12:15)
    at test.ts:15:1
```

The full url is missing now, we cannot know where is broken accurately.

The problem only happen to `.ts` files, `.js` file is okay.

**Comment by kitsonk** [comment]
What happens if you add `export {}` to `/tmp/test.ts`?  I'm wondering if it has to do with the source maps remapping going on and the difference between script and module when loading.

**Comment by Fenzland** [comment]
> What happens if you add `export {}` to `/tmp/test.ts`? 

There is no different with or without `export` in this case.

**Comment by kitsonk** [comment]
Ok, I know where this gets done and can look into it when I can, but there are a few things going on so anyone else can look at it.  My feeling is we should always do the fully qualified module name.

**Comment by bartlomieju** [comment]
This issue is outdated.
