### ISSUE TITLE
better http server API

### ISSUE THREAD

**Issue by ry** [denoland/deno#3228]
```js
import { serve } from "https://deno.land/std/http/server.ts";
const body = new TextEncoder().encode("Hello World\n");
const s = serve({ port: 8000 });
console.log(s.url);
for await (const req of s) {
  req.respond({ body });
}
```
two changes needed:
1. [`serve()`](https://deno.land/std/http/server.ts?doc#serve) needs to take `{ port: 8000 }` instead of `":8000"`.
2. `s.url` to return `"http://localhost:8000/"`

**Comment by rsp** [comment]
That's my luck 😄 an API change few days after I presented the old API in [my last talk](https://www.youtube.com/watch?v=aI5A9zvYSjk).
After [my first talk](https://www.youtube.com/watch?v=Aib1OZLy0_c) got recorded but before it got published, the `deno run` outdated my examples.
Both very good changes by the way 👍 it's just funny how my talks get outdated in a matter of days.

**Comment by kitsonk** [comment]
Why would `s.url` not return an instance of `URL`, which can be easily converted to a string, or otherwise used as seen fit?

**Comment by Fenzland** [comment]
Is there a plain to change for-await-of to a concurrent API?

**Comment by ry** [comment]
@Fenzland No - I'm happy with for-await-of API. It is concurrent (as long as you call an async function without await).

**Comment by rsp** [comment]
@ry I did a PR #3278 to implement this (and PR #3279 that is the same but uses URL objects instead of strings as suggested by @kitsonk so that `console.log(s.url.href)` would have to be used).

The CI currently fails on some systems, sorry for that, I'll have to see why it fails on some systems and not others.

**Comment by ManojBahuguna** [comment]
currentlfy (Deno v1.0.0) `url` in `ServerRequest` returns just the part after hostname (pathname and search-params)

I think there should be a property to get the whole url string or an instance of `URL`. (2nd point in issue)
