### ISSUE TITLE
move xeval to std/examples/xeval.ts

### ISSUE THREAD

**Issue by ry** [denoland/deno#3230]
Remove built-in subcommand. It's too niche for a subcommand.

**Comment by bartlomieju** [comment]
Ref #2312

**Comment by nayeemrmn** [comment]
Have we decided to keep `xeval`?

**Comment by ry** [comment]
No, I want to remove the subcommand.

**Comment by phil294** [comment]
I disagree that this is niche. It would be great to have a standard way to pipe something into Deno. Definitely an improvement compared to `awk`.

Before having seen the documentation, I assumed I could do something along the lines of

    cat /etc/passwd | deno eval "console.log(Deno.stdin.split(':')[0])"

But it seems the only way is to use a non-standard [script](https://deno.land/std@0.55.0/examples/xeval.ts) / import now.

Fortunately, Deno is awesome and allows for easy global installation of scripts like these :-)
