### ISSUE TITLE
Deno playground

### ISSUE THREAD

**Issue by motss** [denoland/deno#3245]
Is it a good time to have a Deno playground just like TypeScript playground?

**Comment by nayeemrmn** [comment]
https://deno-play.app/

https://replit.canny.io/languages-requests/p/deno

**Comment by kitsonk** [comment]
Also, IIRC @orta added some level of support for Deno to the TypeScript playground?  (at least we talked about it at one point)

**Comment by orta** [comment]
Yeah, the TypeScript playground does an _ok_ job at providing the types for Deno-style imports, but offers no runtime mechanisms - which makes it not the best playground for the runtime

**Comment by 7040934** [comment]
1. 

@- 

- 

  [ ] 

_1._

**Comment by rsp** [comment]
@motss @nayeemrmn Yeah, I've been looking into adding Deno to repl.it some time ago - certainly seems doable but I didn't have time to do it. Maybe I'll try to do it soon if there is some interest here.

**Comment by ratnadeep007** [comment]
You can try out [deno.town](https://deno.town/)

**Comment by axetroy** [comment]
In fact, as long as there is a server, it is not difficult to do this.

Just need to dynamically create Docker containers for environmental isolation

**Comment by maman** [comment]
I created one: https://deno-playground.now.sh

<img width="1240" alt="image" src="https://user-images.githubusercontent.com/491458/82195824-0e3ceb80-9923-11ea-8fb0-8a925c54de1c.png">
it's pretty barebones - no syntax-highlighting etc, but some of the highlights are the ability to format and share the snippets 🙂

the sources are available here: https://github.com/maman/deno-playground

**Comment by kitsonk** [comment]
Any further ideas or thoughts around this should take place in discussions: https://github.com/denoland/deno/discussions
