### ISSUE TITLE
Remove various tsconfig.json files

### ISSUE THREAD

**Issue by ry** [denoland/deno#3248]
/tsconfig.json
/std/tsconfig.json
/std/tsconfig.test.json

I believe these are related to eslint... hopefully a workaround can be found.

**Comment by bartlomieju** [comment]
> /tsconfig.json
> /std/tsconfig.json
> /std/tsconfig.test.json
> 
> I believe these are related to eslint... hopefully a workaround can be found.

`/std/tsconfig.json` - used for ESLint
`/std/tsconfig.test.json` - used to enforce `strict` mode in standard library
I don't know about `/tsconfig.json`

**Comment by kitsonk** [comment]
`/tsconfig.json` is largely there to make editors work reasonably well when editing internal Deno code (as well as ESlint for the core).

I suspect they can be rationalised in some fashion, and still used for running the tests, I suspect the only thing is that to make editors behave somewhat logically would require some things that Deno will shout about being ignored when running the std tests.
