### ISSUE TITLE
When opening "listen" function page in /typedoc says Not Found. /index.html

### ISSUE THREAD

**Issue by aalliikk** [denoland/deno#3252]
The website's address at https://deno.land/typedoc "listen" HTML page doesn't work and seems to be other related pages as well.

**Comment by chrmoritz** [comment]
All links seems to work if you use https://deno.land/typedoc/index.html, but if you use https://deno.land/typedoc directly all links are missing the `typedoc` prefix.

**Comment by aalliikk** [comment]
> All links seems to work if you use https://deno.land/typedoc/ (Note the trailing slash is important here) or https://deno.land/typedoc/index.html, but if you use https://deno.land/typedoc (without trailing slash) all links are missing the `typedoc` prefix.

It all works now! Thanks!
