### ISSUE TITLE
Console inspection doesn't show symbol keys in object

### ISSUE THREAD

**Issue by sh7dm** [denoland/deno#3253]
Node and browsers show it correct:
![image](https://user-images.githubusercontent.com/19504461/68005845-b214c180-fc87-11e9-9177-74867c1088e4.png)
![image](https://user-images.githubusercontent.com/19504461/68005915-f3a56c80-fc87-11e9-9dae-9aa5421f0bae.png)

Deno shows only string props:
![image](https://user-images.githubusercontent.com/19504461/68005823-99a4a700-fc87-11e9-81b6-6f435c774be7.png)

Problem is here (probably need to add `Object.getOwnPropertySymbols` here): https://github.com/denoland/deno/blob/master/cli/js/console.ts#L294 . Since it's located and simple to fix, it can be a good first issue for beginners.

/cc @sh7dm I'll probably fix myself

**Comment by bartlomieju** [comment]
Closing in favor of #3165
