### ISSUE TITLE
deno bundle piping

### ISSUE THREAD

**Issue by timreichen** [denoland/deno#3254]
I wonder if it is possible to pipe the `deno bundle <source_file>` instead of writing it to a file.
If I pipe the output now it is information about the bundling process:

```
Bundling "mod.bundle.js"
Emitting bundle to "mod.bundle.js"
14.5 kB emitted.
```

I am experimenting and want to create a deno-loader for webpack so deno modules could be bundled for the client side (e.g. EventEmitter).

Any thoughts on that?

**Comment by ry** [comment]
It would be possible to do with some hacks in cli/js/compiler.ts .. it seems like a reasonable feature to me.

**Comment by nayeemrmn** [comment]
`deno bundle mod.js /dev/stdout` works.

I guess it's common to allow `deno bundle mod.js -`.

**Comment by nayeemrmn** [comment]
Also, I'm pretty sure that's a bug that it says
```
Bundling <out file>
Emitting bundle to <out file>
```

**Comment by timreichen** [comment]
> `deno bundle mod.js /dev/stdout` works.
> 
> I guess it's common to allow `deno bundle mod.js -` platform independently.

Yes but it also returns the information text and if `-L debug` is added all debug logs.

Wouldn't it make sense to make the bundle command return the bundled code if no argument for <out file> is passed. Or even `deno bundle "https://somefile.ts" > bundle.ts` to write it to a file.

Also I would consider adding a `--eval -e` flag to be able to bundle code without any <source_file>. 

What are your thoughts on that?

**Comment by nayeemrmn** [comment]
Oh, for some reason I thought the info was written to stderr.

**Comment by nayeemrmn** [comment]
This is implemented now, omit the output file argument. @ry This can be closed.
