### ISSUE TITLE
response.Body stream behaviour

### ISSUE THREAD

**Issue by nstott** [denoland/deno#3256]
In `fetch`, the response body is a ReadableStream with the data being pumped into the stream via the `start` method here: https://github.com/denoland/deno/blob/master/cli/js/fetch.ts#L25-L38

This is fine, but it has certain behavioural implications.  we enqueue all the data as quickly as we can read it.  there's no queue mgmt.  this could cause memory problems if we have slow consumers of the data from these queues.

As an alternate implementation, we could `pull` the data by implementing 
```
pull(controller: ReadableStreamController): Promise<void> {
```
rather then the current `pump` implementation.  this means we get to apply a high watermark and have more queue management options
https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream/ReadableStream

I'm not sure which is preferred at this point

**Comment by ry** [comment]
Your alternative is preferable. As we stream data only a fixed amount of memory should ever be allocated - as is done with Deno.copy.
