### ISSUE TITLE
std should be checked with strict type checking

### ISSUE THREAD

**Issue by ry** [denoland/deno#3266]
Maybe by adding a "--strict" command line flag.

**Comment by kitsonk** [comment]
That was the purpose of the test tsconfig.json, so that the tests were run under strict mode, therefore having strict part of the CI process.

**Comment by ry** [comment]
It was actually dead code since the deno_std merger. It was also unclear which options of the tsconfig were being used and which were merely boilerplate. I'm happy to add this back, but when there are three tsconfig files, who's purpose is typically integral to the build process (but in our case is not at all) the safe thing is to remove them all and start fresh. Somehow we need a way of documenting that the config is only used for one particular option (unfortunately JSON doesn't allow comments).

**Comment by bartlomieju** [comment]
> (unfortunately JSON doesn't allow comments).

You can add comment to `tsconfig.json`. We added handling of that some time ago because that's standard in ts community

**Comment by kitsonk** [comment]
Correct tsconfig.json supports JSONC, which is why we still pass the string to the compiler instead of parsing it in Rust.

**Comment by nayeemrmn** [comment]
Can this be closed?

**Comment by kitsonk** [comment]
This should be closed.
