### ISSUE TITLE
cli option for toggle top-level-await 

### ISSUE THREAD

**Issue by Fenzland** [denoland/deno#3267]
abusing top-level-await often make code horribly slow. Maybe there need be a cli option such as `--allow-top-level-await` to open this feature.

**Comment by hayd** [comment]
@Fenzland Do you have an example of slow code with top level await? vs alternative

**Comment by kitsonk** [comment]
There are a lot of abuses that can make code horribly slow.  Most of those abuses related to TLA were debated _ad nauseam_ when the proposal was going through TC39.  It is part of the language standard (or actually well on track to be ratified into the language).  Implementing feature flags to turn off parts of the language standard doesn't make sense.
