### ISSUE TITLE
Workers can be better

### ISSUE THREAD

**Issue by Fenzland** [denoland/deno#3282]
* Support Worker.prototype.terminate(), for terminating workers in main thread;
* Worker extends EventTarget and support `.addEventListener( 'message' )`;
* Support `globalThis.addEventListener( 'message' )` in worker thread;
* Support `self` rather then `window` in worker thread as `globalThis`;
* Support naming:
    ```javascript
    // in main.js
    new Worker( './worker.js', { name:'the name' } );
    ```
    ```javascript
    // in worker.js
    globalThis.name === 'the name';
    ```
* Better support for TypeScript in worker:
    now we must use `window.onmessage`, `window.postMessage` but `globalThis.close` in the worker to prevent error from TypeScript. These APIs need to be unified;
* Support `SharedWorker`;
* ~Support `type: "classic"`~ module is better;
* ~Support `importScripts`~ import and import() are better;

ref: [https://html.spec.whatwg.org/multipage/workers.html](https://html.spec.whatwg.org/multipage/workers.html)

**Comment by base698** [comment]
Is terminate() on the roadmap?

**Comment by bartlomieju** [comment]
@base698 yes, it will be implemented; I'm held up by internal refactors ATM
