### ISSUE TITLE
Reusing bundled files in Deno .ts scripts

### ISSUE THREAD

**Issue by mrgrain** [denoland/deno#3283]
(This came out of [a discussion](https://gist.github.com/hayd/ce469e53b022e7a2360ec2ea950b4a2e#gistcomment-3075931)  between @hayd and me regarding a serverless lambda configuration for Deno. See the thread for more context)

**Given the following scenario:**
- I have received a bundled deno script `cool-stuff.bundle.js` (because it's great for distribution)
- I want to reuse parts of it in my new application

**Current Situation:**
- There is no way to use the output of the bundle in another Deno file - neither .ts nor .js

**Possible desired outcomes:**
- I can use an import statement (or similar) in my .ts scripts, e.g. `import { moduleName } from "./cool-stuff.bundle.js"`
- I can use `require` (or similar) in a .js file to use the bundle

**Options/Alternatives:**
The main issue for lambdas is that we need to ship a layer with a runtime. This runtime is responsible to call a module (which is the handler function) from a file.  Because performance matters, we should avoid compilation of anything. However for convenience, it's nicer to have the runtime as part of the layer, not the application.

- Uploading the `DENO_DIR` as part of the deployable does get us around compilation. However it seems a bit hacky to archive an internal directory as part of the distribution. Additionally the `runtime.ts` file still needs to be compiled.

- A creating a single executable including the deno core could solve the problem, if we can pass in multiple params.

- Ideally the runtime would be a .js file that can load a deno generated bundle so that no compilation needs to happen.

**Comment by kitsonk** [comment]
The best solution is that the exports of the main module specified for the bundle get re-exported as ESM exports. I am currently working on making the bundles self contained, and then a next iteration re-exporting the exports of the main module would be possible. Then the bundle could be imported in the future.

**Comment by ry** [comment]
> The best solution is that the exports of the main module specified for the bundle get re-exported as ESM exports

This would be cool

**Comment by kitsonk** [comment]
It would require analysis of the AST of the main module to look at all the exported top level nodes, and then writing that out, along with references to the the exports object of module, which should be available in from the loader. I think I can get it to work.

**Comment by kitsonk** [comment]
I've been working on this, and @ry mentioned in the effort to support `.wasm` imports, there was use of `export default` to re-export the wasm exports and he suggested we might use that for Deno bundle.

It certainly would make things simpler, but it does come with a consequence, where previously the root module you bundle might have been consumed this way:

```ts
import { foo, bar } from "./myModule.ts";
```

You would have to do something like this, to consume the bundled version:

```ts
import myModule from "./myModule.bundle.js";
const { foo, bar } = myModule;
```

And if there was a default export from `myModule.ts`:

```ts
import myModule from "./myModule.bundle.js";
const myModuleDefault = myModule.default;
```

**Comment by mrgrain** [comment]
I _think_ that would be okay. Importing a bundle is not a drop-in replacement anyway. I might be confusing for implementers, why there's a different syntax.

Is this standard ES and just a "quirky" way of export the module? If that's the case, good documentation should mitigate the confusion.

**Comment by kitsonk** [comment]
For those watching this issue, in the end it was actually straight forward to re-export the exports of the main module in the bundle.  So you can now just do `deno bundle whatever.ts whatever.bundle.js` and `whatever.bundle.js` exports will match `whatever.ts` exports.
