### ISSUE TITLE
Feature Request: Allow reading into a 0-length array

### ISSUE THREAD

**Issue by Aksamyt** [denoland/deno#3287]
Hello! I got this error while working with sockets implementing a low-level protocol:
```
error: Uncaught InvalidInput: no buffer specified
► $deno$/dispatch_minimal.ts:64:11
    at DenoError ($deno$/errors.ts:20:5)
    at unwrapResponse ($deno$/dispatch_minimal.ts:64:11)
    at sendAsyncMinimal ($deno$/dispatch_minimal.ts:106:10)
```

Turns out core’s implementation of `Deno.Conn.read` seems to have undefined behaviour when the buffer has no size.
Here’s an example to reproduce the error:
```ts
const PORT = 62394;

const server = new Promise(async resolve => {
  const listener = Deno.listen({ hostname: "127.0.0.1", port: PORT });
  const sock = await listener.accept();
  const rdbuf = new Uint8Array(12);
  await sock.read(rdbuf);
  console.log("SERVER", rdbuf);
  await sock.write(rdbuf);
  resolve();
});

const client = new Promise(async resolve => {
  await new Promise(resolve => setTimeout(resolve, 500));
  const sock = await Deno.dial({ hostname: "127.0.0.1", port: PORT });
  await sock.write(new Uint8Array(12).fill(12));
  const rdbuf = new Uint8Array(0);
  await sock.read(rdbuf);
  sock.close();
  resolve();
});
```
Giving a size other than 0 to the client’s `rdbuf` makes this piece of code work as expected.

Some solutions:
- Make it explicit in the JSDoc that `p.length` must be greater than 0.
- Mimic POSIX `read` behaviour: `In the absence of any errors, or if read() does not check for errors, a read() with a count of 0 returns zero and has no other effects.` (from the manpage). This requires adding a check to the following function (and `readSync`), and writing tests.<https://github.com/denoland/deno/blob/6c5a981fd2afad21af73a1345c4e30fb6b30b09a/cli/js/files.ts#L76-L85>

If you’re ok with the second solution, I can do the PR :)
I’m using Deno v0.22.0.

**Comment by zekth** [comment]
Second solution looks like a good one for me
