### ISSUE TITLE
use python2 instead of python

### ISSUE THREAD

**Issue by jihuayu** [denoland/deno#3294]
hello!
I have built deno in my **Manjaro**. But Manjaro use python3 for default python.So I get a error.
Can use python2 instead of python in the build script .

thank.

**Comment by ry** [comment]
No. Sorry - we follow what V8 does https://github.com/v8/v8/blob/5e514a969376dc63517d575b062758efd36cd757/tools/disasm.py#L1
We will switch when they do.
