### ISSUE TITLE
zsh completion is broken

### ISSUE THREAD

**Issue by KluVerKamp** [denoland/deno#3310]
Getting this error:

`/usr/local/etc/zsh_completion.d/deno.zsh:478: no matches found: _deno__[SCRIPT]_commands`

**Comment by hayd** [comment]
How did you install the deno / the completions?

**Comment by KluVerKamp** [comment]
@hayd exported `deno completions zsh` into `
/usr/local/etc/zsh_completion.d/deno.zsh`, then sourced 
`/usr/local/etc/zsh_completion.d/deno.zsh` in `~/.zshrc`

**Comment by KluVerKamp** [comment]
And I tried adding that folder to `fpath`, since I am using oh-my-zsh, I tried placing that file under ~/.oh-my-zsh/comletions and functions folders, even added the deno command output directly to .zshrc, still getting the same issue

**Comment by bartlomieju** [comment]
@KluVerKamp not long ago we had another CLI refactor, is this issue still persisting?

**Comment by KluVerKamp** [comment]
@bartlomieju I have just checked, it works now!

**Comment by alexandrestein** [comment]
FYI
On my installation (Debian 10) I solved the problem by running:
``` sh
deno completions zsh > /usr/local/share/zsh/site-functions/_deno
```

This solved the issue immediately. :partying_face:

**Comment by stefanpl** [comment]
I'm currently not able to get deno completions to work:
```zsh
deno completions zsh > /tmp/deno_zsh
source /tmp/deno_zsh
>>> _arguments:comparguments:312: can only be called from completion function
```
```zsh
deno completions bash > /tmp/deno_bash
source /tmp/deno_bash
>>> /tmp/deno_bash:649: command not found: complete
```

Both run with:
`zsh 5.1.1 (x86_64-ubuntu-linux-gnu)`
`deno 1.0.5`

It's working in bash, but I'm not terribly inclined to switch tbh =) 

@bartlomieju could this be some kind of regression bug? 

Any help much appreciated!

**Comment by meSingh** [comment]
Getting this error on :

deno 1.0.5
v8 8.4.300
typescript 3.9.2
zsh 5.4.2 (x86_64-apple-darwin17.3.0)


`➜ source ~/.oh-my-zsh/custom/plugins/deno.zsh
_arguments:comparguments:325: can only be called from completion function`

**Comment by nour-dev** [comment]
any change in this error for completions ?

**Comment by nour-dev** [comment]
@meSingh same error

**Comment by bartlomieju** [comment]
I'm not immediately sure what's the problem. Reopening the issue

**Comment by vinschess** [comment]
@meSingh try the following commands:

```
mkdir ~/.oh-my-zsh/custom/plugins/deno
deno completions zsh > ~/.oh-my-zsh/custom/plugins/deno/_deno
```

After this add `deno` plugin under plugins tag in `.zshrc` file.

**Comment by meSingh** [comment]
Thanks @vinschess, that worked for me!

**Comment by nour-dev** [comment]
@vinschess this is worked for me too. thank you .

**Comment by stefanpl** [comment]
@vinschess thanks a lot, this fixed my issue.

Any idea why this works, while the documented way (generate the file and `source` it) does not?!

**Comment by vinschess** [comment]
@stefanpl - I haven't tried the documented way, but this is how you put any completion function plugin in the `ZSH`. 
For more understanding check [this](https://askql.wordpress.com/2011/01/11/zsh-writing-own-completion/) blog.

**Comment by meSingh** [comment]
> @meSingh try the following commands:
> 
> ```
> mkdir ~/.oh-my-zsh/custom/plugins/deno
> deno completions zsh > ~/.oh-my-zsh/custom/plugins/deno/_deno
> ```
> 
> After this add `deno` plugin under plugins tag in `.zshrc` file.

Added a PR to update doc with this information: 
https://github.com/denoland/deno/pull/6298

**Comment by stefanpl** [comment]
@vinschess @meSingh please be aware that `oh-my-zsh` !== `zsh`. There are people (albeit few I assume) who are using `zsh` without the framework behind it. They won't have access to the `plugin` mechanism.
The documentation should imo:
- most importantly: provide a way to make it work in plain zsh (still unclear to me)
- optionally, provide a way for oh-my-zsh

**Comment by meSingh** [comment]
Thanks @stefanpl for pointing it out, I assumed almost everyone uses `zsh` with the framework. 

I will update the PR accordingly.

**Comment by vinschess** [comment]
@stefanpl have you tried in plain vanilla `zsh`? is it not working in that?

**Comment by Sparkenstein** [comment]
for people who are using `antigen` like I am, the process remains the same, just change the path to 
`~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins` instead of `~/.oh-my-zsh` and then add `antigen bundle deno` to the `.zshrc` to load the plugin. enjoy!

**Comment by spashii** [comment]
**if #6998 doesn't work for vanilla `zsh` users,**

- `mkdir -p ~/.zsh/completion`
- `deno completions zsh > ~/.zsh/completion/_deno`
- add `fpath+=(~/.zsh/completion)` at the top of `.zshrc`
- restart terminal or `source path/to/.zshrc`

**Comment by satyarohith** [comment]
zsh completions seem to be working as expected with `1.9.2`. Here are clear instructions to set up completions for modern shells (including zsh): https://deno.land/manual@v1.9.2/getting_started/setup_your_environment#shell-autocomplete.


I think we can close this issue.

**Comment by mparq** [comment]
> for people who are using `antigen` like I am, the process remains the same, just change the path to `~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins` instead of `~/.oh-my-zsh` and then add `antigen bundle deno` to the `.zshrc` to load the plugin. enjoy!

In case somebody comes across this issue from a search, I am using antigen and followed these instructions and was still getting the following error: "No such file or directory: .../.antigen/bundles/robbyrussell/oh-my-zsh/cache//completions/_deno". I needed to create the `$ZSH_CACHE_DIR/completions` directory manually as per https://github.com/ohmyzsh/ohmyzsh/issues/10728#issuecomment-1129786095 to get things working.
