### ISSUE TITLE
cannot post an Error, Map or Set between worker threads

### ISSUE THREAD

**Issue by Fenzland** [denoland/deno#3317]
```javascript
// index.js

const worker= new Worker( './worker.js', { name:'worker', type:'module', }, );

worker.onmessage= ( { data, }, )=> {
	console.assert( data.error instanceof Error, );
	console.assert( data.error.hasOwnProperty( 'stack', ), );
	console.assert( data.map instanceof Map, );
	console.assert( data.map.has( 'foo', ), );
	console.assert( data.map.get( 'foo', ) === 'bar', );
	console.assert( data.set instanceof Set, );
	console.assert( data.set.has( 'foo', ), );
};
worker.postMessage( {
	error: new Error(),
	map: new Map( [ [ 'foo', 'bar', ], ], ),
	set: new Set( [ 'foo', ], ),
}, );
```

```javascript
// worker.js

globalThis.onmessage= ( { data, }, )=> {
	console.assert( data.error instanceof Error, );
	console.assert( data.error.hasOwnProperty( 'stack', ), );
	console.assert( data.map instanceof Map, );
	console.assert( data.map.has( 'foo', ), );
	console.assert( data.map.get( 'foo', ) === 'bar', );
	console.assert( data.set instanceof Set, );
	console.assert( data.set.has( 'foo', ), );
	
	globalThis.postMessage( {
		error: new Error(),
		map: new Map( [ [ 'foo', 'bar', ], ], ),
		set: new Set( [ 'foo', ], ),
	}, );
	
	globalThis.close();
};
```
In Chrome, all the assert successful. But in deno (until 0.23.0), they fail. After post between threads, errors, maps and sets become empty objects.

**Comment by kitsonk** [comment]
Hmmmmm... it seems that the structure clone on `postMessage` shouldn't be handling `Error` or `Function` objects.  It feels like the browser must be filtering them out and cloning them in some other way: https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm

I will admit I don't know how we implemented cloning in Deno for workers...

**Comment by kevinkassimo** [comment]
@kitsonk we currently stringify data as JSON into some buffer that is passed directly to the Rust side and pushed as a message through a channel, where the receiving end polls and parses the JSON as `data`.

This is indeed not fully complying with structured clone requirements (e.g. transferables). But for `Error`s I would expect us to simply throw an error when attempted.

**Comment by Fenzland** [comment]
JSON.stringify not only lose errors, also miss maps and sets. They are both pass correctly in browsers too.

**Comment by kevinkassimo** [comment]
@Fenzland I agree we will need to fix this. /cc @bartlomieju for worker stuff

**Comment by kitsonk** [comment]
There is the value serialiser in V8 that does the structured cloning: https://v8docs.nodesource.com/node-7.10/df/d48/classv8_1_1_value_serializer.html

I am sure there must be APIs too for transferring as well, I just haven't found them yet.

**Comment by bartlomieju** [comment]
@kitsonk https://denolib.github.io/v8-docs/classv8_1_1ValueDeserializer.html ?

**Comment by kitsonk** [comment]
Well that and: https://denolib.github.io/v8-docs/classv8_1_1ValueSerializer.html so post should serialize the message and onmessage should be called with the deserialized message I think.  I am not so hot at the V8 APIs though.

**Comment by bartlomieju** [comment]
Makes sense. This issue (or more general workers) are in my backlog, but I don't know when I'll get to them. If someone wants to take a stab at it I'll be happy to provide support

**Comment by kevinkassimo** [comment]
@bartlomieju Oh I almost forgot I still have that v8 docs up... it has not been updated for a while. I mostly just refer to https://cs.chromium.org/chromium/src/v8/include/v8.h , which is well updated and, since it is using Google's CodeSearch, easy to look up references and usages than on Github.

**Comment by kitsonk** [comment]
@bartlomieju we should close in favour of #3557 as that solution would solve all of this properly.
