### ISSUE TITLE
Don't fail on ts compile when running a script ?

### ISSUE THREAD

**Issue by yhuang0** [denoland/deno#3321]
If I want to run my script via "deno run foo.js" and foo.js depends on a ts library that emits perfectly working js code but has a compiler error, deno shouldn't fail prematurely during the compile step and instead run my script with the emitted js file.

Typescript always emits code by default and you have to override that behavior with noEmitOnError. Shouldn't deno allow you to keep running your scripts?

**Comment by ry** [comment]
—no-type-check ?

**Comment by kitsonk** [comment]
@ry I would advise against that...  there is `// @ts-ignore` (which I know works) and `// @ts-nocheck` (which I am not sure about) pragmas which we should be able to adjust the cases.

Throwing out the whole type checking is like saying to the V8 runtime to ignore syntax errors... 😢

**Comment by yhuang0** [comment]
@ry That would fix my current use case, but I would also suggest an option to remove checks entirely (if the tsc emits valid js, that's what is run.) I can imagine using third party libs that don't pass the compiler 100% (maybe deno's typescript is a different version, idk). If I'm scripting I don't want my entire script to break because of a compiler error.

@kitsonk A V8 runtime with no errors... it would start assuming what you meant. Would that be bad? idk :)

**Comment by ry** [comment]
Is there a corresponding tsc option? I'd rather not invent names `--nocheck` ?

@kitsonk You might want this for starting up quickly.

**Comment by rsp** [comment]
@ry there are `// @ts-nocheck` comments (microsoft/TypeScript#33383) that should be [supported in 3.7](https://devblogs.microsoft.com/typescript/announcing-typescript-3-7-beta/) but there is no corresponding tsc option yet.

As for the option name, people are asking for `--transpileOnly` (microsoft/TypeScript#29651) and there is a [typescript-transpile-only](https://github.com/cspotcode/typescript-transpile-only) project which claims to be "a quick, 1 hour hack to write a tsc alternative that compiles your code just like tsc but skips typechecking" so this `transpileOnly` seems to be a popular name now, hard to tell if it's going to be the same when (if) it lands. To match the `// @ts-nocheck` the `--nocheck` or `--noCheck` would seem more consistent.

**Comment by kitsonk** [comment]
I agree, there is the concept of transpile only. There is a slightly loose version of the compiler that is the no default lib check.

I guess if there ends up being a transpile only on the compiler, we would want to support it, but we would want to support it through tsconfig if it becomes a compiler feature.

**Comment by kitsonk** [comment]
Wesley (TypeScript core team) pointed out that we can use `ts.transpile()` to do a transpile only.  While I still personally think it is a big 👣 🔫, it should be fairly easy to support.  The issue @rsp mentions is effectively integrating that into `tsc`, so it isn't supported in the Compiler Options, but would be easy to do for us, but then would make a Deno flag of `--transpile-only` the best way to add the functionality.

**Comment by ry** [comment]
ts.transpile might be useful for the REPL too /cc @kevinkassimo

**Comment by kitsonk** [comment]
yeah, still a bit more complicated, because you only want to run the changes between the last transpile (REPL command) and the current, but it could be a step in the right direction.

**Comment by rsp** [comment]
There is also a [TypeScript preset for Babel]( https://babeljs.io/docs/en/babel-preset-typescript) that I believe just erases the types without compiling (as opposed to tsc compiling and ignoring errors, as I understand it) which may be a much faster approach in getting JS out of known good TS (one possible use case) or even getting a try-at-your-own-risk JS out of known bad TS (for development, debugging, testing, quick hacks).

> Babel won't perform type-checking on TypeScript code; it will only be transforming your code, and it will compile regardless of whether type errors are present.

From https://devblogs.microsoft.com/typescript/typescript-and-babel-7/

There are actually two Babel preset and plugin, one is using the other:

- https://babeljs.io/docs/en/babel-preset-typescript
- https://babeljs.io/docs/en/babel-plugin-transform-typescript

They don’t have the ability to do any type checking so I guess they should have a potential to be much faster and simpler. Maybe a type-erasing fast path based on type erasing babel-style instead od using internal tsc would be a possible optimization for the future dor things like std modules etc.?

**Comment by bartlomieju** [comment]
@rsp this is interesting, I had another idea as well. TS can emit declaration files alongside JS, which we could cache as well along with compiled output and sourcemap. 

Then when you compile a script and you find a dependency that has declarations file in cache you substitute source file with declaration file (just like we do using `// @deno-types` pragma).

**Comment by rsp** [comment]
@ry @kitsonk is it possible to optimize the repl in a way that vscode is working? It uses [tsserver](https://github.com/Microsoft/TypeScript/wiki/Standalone-Server-%28tsserver%29) (which is tsc working in a different mode optimized for interactive work) and it can recompile on every keystroke, of course recompiling only what’s needed because of time constrains. 

Anders Hejlsberg explains it [in this part](https://youtu.be/wSdV1M7n4gQ?t=4m30s) od his video on modern compilers very well. Maybe a repl can use a similar approach?

**Comment by rsp** [comment]
@bartlomieju Interesting. Some time ago I was also thinking about services like deno.land/x serving (or redirecting to) a .js/.d.ts combo in addition to .ts source of files that are compiled and cached on the server (github, cdn, whatever).

Let’s say that a cli switch like —prebuilt or something adds a special header or query param in http requests and if that header/param is recognized by the server it returns a compiled version of js plus type definitions.

If the header/param is not recognized then you get a normal ts file and nothing changes, but if it is supported then it could speed up loading libraries even more than erasing types or compiler optimization.

**Comment by solson** [comment]
This should be closed due to https://github.com/denoland/deno/pull/6456. For example:

```console
$ cat foo.ts
export function f(x: string): number { return x; }

$ cat bar.js
import { f } from "./foo.ts";
console.log(f("test"));

$ deno run bar.js
Check file:///home/scott/tmp/bar.js
error: TS2322 [ERROR]: Type 'string' is not assignable to type 'number'.
export function f(x: string): number { return x; }
                                       ~~~~~~~~~
    at file:///home/scott/tmp/foo.ts:1:40

$ deno run --no-check bar.js
test
```

**Comment by moodmosaic** [comment]
Can this flag be used when [embedding deno](https://deno.land/manual/embedding_deno)?

**Comment by kitsonk** [comment]
`deno_core` has no ability to type check TypeScript. If you are referring to `deno compile`, it accepts the flag as the subcommand, and irrespective of it being enabled or not, will no longer type check code on the resulting binary.

**Comment by moodmosaic** [comment]
Thank you, @kitsonk. I guess all I need then is to pull the latest from upstream in https://github.com/hirosystems/clarinet/issues/282 since [it appears as they're using an older version of deno](https://github.com/hirosystems/clarinet/tree/develop/vendor) currently.
