### ISSUE TITLE
cli/tests/019_media_types.ts is flaky

### ISSUE THREAD

**Issue by ry** [denoland/deno#3332]
It seems to be because it has many HTTP imports. That suggests we have a bug in the module fetching. 

048_media_types_jsx.ts seems to have the same problem.

https://github.com/denoland/deno/blob/ee1b8dc883db1531d913f7b10a8d1160f3209d93/cli/tests/integration_tests.rs#L159

https://github.com/denoland/deno/blob/ee1b8dc883db1531d913f7b10a8d1160f3209d93/cli/tests/integration_tests.rs#L177

https://github.com/denoland/deno/blob/ee1b8dc883db1531d913f7b10a8d1160f3209d93/cli/tests/integration_tests.rs#L338

https://github.com/denoland/deno/blob/ee1b8dc883db1531d913f7b10a8d1160f3209d93/cli/tests/integration_tests.rs#L346

**Comment by ry** [comment]
@rsp has a good test 
```
for i in `seq 1 1000`; do echo "import {} from 'http://localhost:4545/$i';"; done > x.ts
```

**Comment by bartlomieju** [comment]
I believe I found a repro for this problem. With #3358 landed you can change `cli/file_fetcher.rs` like this:
```rust
  // before:

  /// Required for TS compiler.
  pub fn fetch_source_file(
    self: &Self,
    specifier: &ModuleSpecifier,
  ) -> Result<SourceFile, ErrBox> {
    tokio_util::block_on(self.fetch_source_file_async(specifier))
  }

  // after:

  /// Required for TS compiler.
  pub fn fetch_source_file(
    self: &Self,
    specifier: &ModuleSpecifier,
  ) -> Result<SourceFile, ErrBox> {
    futures::executor::block_on(self.fetch_source_file_async(specifier))
  }
```

And the problem described in this issue will pop up in `file_fetcher` tests (`Connection refused` even though the server is still running).
