### ISSUE TITLE
Too many imports crash Deno, possible DDoS vulnerability

### ISSUE THREAD

**Issue by rsp** [denoland/deno#3333]
For a TypeScript file:

```ts
import {} from 'http://localhost/1';
import {} from 'http://localhost/2';
// [...]
import {} from 'http://localhost/999';
import {} from 'http://localhost/1000';
```

Command to generate this file:
```sh
for i in `seq 1 1000`; do echo "import {} from 'http://localhost/$i';"; done > x.ts
```

Deno crashes with:

```
$ deno x.ts 
Compile file:///Users/rsp/deno/test/import-ddos/x.ts
Download http://localhost/1
Download http://localhost/2
[...]
Download http://localhost/509
Download http://localhost/510
Download http://localhost/511
thread 'tokio-runtime-worker-0' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 35, kind: WouldBlock, message: "Resource temporarily unavailable" }', src/libcore/result.rs:1084:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
fatal runtime error: failed to initiate panic, error 5
Abort trap: 6
```

It seems that it tries to makes all of those requests at the same time and crashes hitting a limit of 512.

If such a file is returned by server serving a popular library in the future, using a host that is going to be a target of a DDoS attack instead of localhost, then everyone running the program will hit the target with hundreds of requests at the same time.

1. Are there any plans to limit the number of concurrent connections on imports?
    - maybe 6 per host like in the browsers is too low but 512 may be too high, also queuing instead of crashing
2. Are there any plans to limit the hosts from which the imports are allowed?
    - an optional whitelist of trusted hosts would serve two purposes:
        - disallow DDoSing foreign hosts
        - control sources of imports for a program for security and performance

**Comment by ry** [comment]
I believe this is the same as https://github.com/denoland/deno/issues/3332 - let's move the discussion there.

```
for i in `seq 1 1000`; do echo "import {} from 'http://localhost/$i';"; done > x.ts
```

This is a good test we should add when we fix this.

**Comment by ry** [comment]
Sorry - I was too quick to close this. I don’t think it’s related now to the flaky test problem (but maybe)

**Comment by hayd** [comment]
[Docs](https://docs.rs/reqwest/0.8.4/reqwest/struct.Client.html) suggest:

> The Client holds a connection pool internally, so it is advised that you create one and reuse it.

But I think we're creating one every request?

https://github.com/denoland/deno/blob/4902a1cacb0348efde9ab342172f2706ac27e837/cli/http_util.rs#L18-L30

**Comment by bartlomieju** [comment]
> [Docs](https://docs.rs/reqwest/0.8.4/reqwest/struct.Client.html) suggest:
> 
> > The Client holds a connection pool internally, so it is advised that you create one and reuse it.
> 
> But I think we're creating one every request?
> 
> https://github.com/denoland/deno/blob/4902a1cacb0348efde9ab342172f2706ac27e837/cli/http_util.rs#L18-L30

Yes, there's pending issue: #3068 and PR: #3099

**Comment by GaryPWhite** [comment]
Also in those threads but going to note here that we're waiting on `tokio 2.0` to merge/close that issue
