### ISSUE TITLE
Support caching/emitting bytecode

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#3335]
@ry mentioned to me that V8 supports a way to transpile modules to byte code. In theory we could persist that in the cache instead of JavaScript. Different than snapshots, which are code running in memory, this would be more like `.pyc` in Python.

We could also potentially emit the bundles to that format as well.

**Comment by ry** [comment]
The feature I was referring to is here: https://github.com/v8/v8/blob/b4bfbce6f91fc2cc72178af42bb3172c5f5eaebb/include/v8.h#L1625-L1629

This will become more accessible after we replace libdeno with [rusty-v8](https://github.com/denoland/rusty_v8). We should also solve https://github.com/denoland/deno/issues/1692 before attempting this.

**Comment by bartlomieju** [comment]
@lucacasonato and I discussed this today. Besides required `rusty_v8` bindings, we might have to change some types passed to `deno_core`, but other than that there are no blockers for this feature.

**Comment by Ayfri** [comment]
Any update on that ?

**Comment by kitsonk** [comment]
It simply hasn't been a priority.  The investment is high and the likely improvement in performance is questionable.  While there are no blockers for it, there is a lot of other higher priority work for the core team.

**Comment by cunev** [comment]
Would be great to see some progress on this issue.

**Comment by lucacasonato** [comment]
Out of interest, what are your usecases @Ayfri and @cunev?

**Comment by Ayfri** [comment]
Just for curiousity in my case !

**Comment by teleclimber** [comment]
@lucacasonato  In my case anything that can reduce startup time is welcome. In Dropserver [1] I run one Deno instance per app instance, and it gets shut off when the app instance is not in use (to free up resources). This means sometimes I have to start up an instance on an incoming HTTP request. As a result, the faster the startup time, the better.

It's not clear from the comments above how much this feature might help startup time, but if it can, I'm all for it.

Thanks!

[1] https://github.com/teleclimber/Dropserver

**Comment by cunev** [comment]
@lucacasonato 
Code caching would significantly reduce the instantiation time of the "compiled" Deno projects, and act as a small layer of protection for production apps.

Even tho not a proper way of protecting the code, as long as there is no V8 bytecode disassembler - it's a great feature to have.
Projects that make use of this would be https://github.com/bytenode/bytenode.

**Comment by bermi** [comment]
@lucacasonato not having to unzip the js to the user cache directory would make it easy to install cli deno apps as root that can be used by regular users. Right now we have to define an explicit cache dir. 

Bundling the bytecode might also speed up thins for CLI apps.

**Comment by ForbiddenEra** [comment]
> as long as there is no public V8 bytecode disassembler

There is. But for V8, bytecode is internal and changes based on different versions, so you could potentially need to have unique disassemblers for every version.

**Comment by lucacasonato** [comment]
We automatically use V8 code cache since 1.43 now (https://deno.com/blog/v1.43#faster-es-and-commonjs-module-loading).
