### ISSUE TITLE
Import 'https://deno.land/std@v0.7.0/prettier/main.ts' failed: 404 Not Found

### ISSUE THREAD

**Issue by hufeng** [denoland/deno#3340]
```text
deno fmt hello.js
Download https://deno.land/std@v0.7.0/prettier/main.ts
Import 'https://deno.land/std@v0.7.0/prettier/main.ts' failed: 404 Not Found
```

![image](https://user-images.githubusercontent.com/533008/68860325-43724200-0724-11ea-996c-2f9777b93849.png)

**Comment by bartlomieju** [comment]
With recent changes to website there's an issue where old versions of standard library do not work properly. Try upgrading to newer version (v0.23.0).

CC @ry

**Comment by ry** [comment]
Should be fixed now. But yes, you should upgrade. You're using a very old version.
