### ISSUE TITLE
AbortController

### ISSUE THREAD

**Issue by zb0t** [denoland/deno#3345]
Are there plans to implement abortable fetch – i.e. AbortControllers?

**Comment by kitsonk** [comment]
We should support it.

MDN Reference: https://developer.mozilla.org/en-US/docs/Web/API/AbortController

It is part of the Living Standard and fully implemented in greenfield browsers.

**Comment by artisonian** [comment]
Im wondering about this too. Signals in v0.31.0 probably could have leveraged them for disposing the signal stream.

**Comment by kitsonk** [comment]
We should really support this.  It shouldn't be that difficult to implement and it really has [broad support in browsers](https://caniuse.com/#feat=abortcontroller).  Having abortable fetch is a pretty important feature.  I was just reminded about it, so I thought I would bring it up again.

Certainly a good candidate for someone to contribute to Deno that wouldn't be small, as it likely would require communication with Rust to abort the fetch.

**Comment by ry** [comment]
It’s a complex feature to add but I agree that it’s important.
