### ISSUE TITLE
bug: ModuleSpecifier parsing on Windows

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#3355]
It seems there are still problems with `ModuleSpecifier` parsing on Windows.

In #3344 I encountered problem on Windows CI where this path:
```
c:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\.tmpGMWvcR\\.deno.test.ts
```
was parsed as module specifier having `c:` scheme instead of `file://` and I had to manually add `file://` prefix doing dynamic import.

**Comment by axetroy** [comment]
Finally. I got this in #3346.

I am curious why CI failed under Windows.

I spent a lot of time exploring the problem.

**Comment by piscisaureus** [comment]
@bartlomieju 

There is already logic to deal with this case: https://github.com/denoland/deno/blob/b9e5e4c7ec9e044f014f2b8a5cfd469f92091ec2/core/module_specifier.rs#L172-L190

Can you figure out why it is not working?

**Comment by bartOssh** [comment]
If something goes wrong it is here [#L143](https://github.com/bartOssh/deno/blob/d4f2fda62331164b09290f2df1500b948f2647a7/core/module_specifier.rs#L143). `Url::from_file_path())` used here [#L157](https://github.com/bartOssh/deno/blob/d4f2fda62331164b09290f2df1500b948f2647a7/core/module_specifier.rs#L157) will panic if invalid path is passed. If this statement [#L143](https://github.com/bartOssh/deno/blob/d4f2fda62331164b09290f2df1500b948f2647a7/core/module_specifier.rs#L143) is not working as expected, We would be facing panic from this function: [L129](https://github.com/bartOssh/deno/blob/d4f2fda62331164b09290f2df1500b948f2647a7/core/module_specifier.rs#L129): `Url::parse()`.

I am not able to fix it reliably, as I don't have access to Windows running machine. On Unix/Linux OS path encoding works fine.

What do you think ?
