### ISSUE TITLE
Bundle: Uncaught ImportPrefixMissing: relative import path "require" not prefixed with / or ./ or ../

### ISSUE THREAD

**Issue by maxuuell** [denoland/deno#3362]
Did an experiment with `deno bundle` by writing the http server as shown in the readme of `http`

```
import { serve } from "https://deno.land/std/http/server.ts";
const server = serve({ port: 8000 });
const body = new TextEncoder().encode("Hello World\n");

for await (const req of server) {
  req.respond({ body });
}
```

When I ran the resulting bundle from `deno bundle server.ts server.bundle.ts`, the `sendAsync` method in `dispatch_json.ts` responded with the above error.

Not sure how to proceed.  Code runs fine before bundling, so I assume there is something wrong with how the dependencies are bundled 🤷‍♂

**Comment by nayeemrmn** [comment]
It bundles to JS, you're expected to write and run it with a JS extension.

But yeah, ideally it wouldn't break if you ran it as TypeScript...

**Comment by ry** [comment]
Try wrapping the async-await loop in a async function. Our support for top-level-await in typescript is not 100% yet.

**Comment by maxuuell** [comment]
Thank you for the prompt response.  

I wrapped the await in an async function, and the pre-bundled `.ts` file worked fine 👍 

After doing that, and bundling it into a `.js` extension file, the bundle ran as well. 👍
