### ISSUE TITLE
Need help porting uWS (C++) for fast HTTP/WebSocket server

### ISSUE THREAD

**Issue by uasan** [denoland/deno#3366]
Hi.

I used in Node.js [uWebSockets.js](https://github.com/uNetworking/uWebSockets.js) this vary fast HTTP/WebSocket server.

I would like to used him in Deno, but I did not find ready-made solutions how to port it to Deno, does anyone know how to do porting?

My result benchmark: `wrk -c 50 -d 30s -t 50 http://127.0.0.1`

Deno - **32 154** RPS
uWebSockets.js - **133 752** RPS

Thanks.

**Comment by rsp** [comment]
I remember that @alexhultman author of uWebSockets used to be active here helping with the benchmarks in #996, he would be the first person I'd ask about porting uWS to Deno.

**Comment by uasan** [comment]
Yes, i asked the author, he replied that Deno does not support native modules, so this will be difficult to do.
https://github.com/uNetworking/uWebSockets.js/issues/230#issuecomment-554779661

Any help is appreciated.

**Comment by rsp** [comment]
The native bindings have been discussed a number of times. Some references: #296 #1654 #2180 #2385 #2840 #3031 #3025 #3240 there were probably more issues/PRs.

Some time ago @afinch7 showed PRs #2386 and denoland/deno_std#475 but I don't know what was the result of that.

**Comment by ry** [comment]
We’re working towards native plugins - we’re trying to make it so they can be distributed as rust crates and their tests run independently using “cargo test” ... a lot of the refactors Bartek has been working on the past few weeks are towards this goal.

**Comment by bartlomieju** [comment]
Unstable plugin API has been available for some time now. Porting the library is outside of scope for deno. Question about porting existing libs are best suited for [Discord server](http://discord.gg/deno)

**Comment by Malix-Labs** [comment]
@bartlomieju I think you should close as not planned instead :)
