### ISSUE TITLE
Rust crates cannot be published to crates.io

### ISSUE THREAD

**Issue by ry** [denoland/deno#3367]
As of v0.24.0 the [deno-x86_64-pc-windows-msvc](https://crates.io/crates/deno-x86_64-pc-windows-msvc)  package for v0.24.0 is larger than the 10mb limit imposed by crates.io. This means we are unable to publish [deno](https://crates.io/crates/deno), [deno_typescript](https://crates.io/crates/deno_typescript), and [deno_cli](https://crates.io/crates/deno_cli).

We will take this opportunity to reorganize our crates. [The current setup](https://github.com/denoland/deno/blob/5671d38d8f0176c2828a242a79a856fcfae93c3e/tools/cargo_package.py) was built back before we had proper cargo integration, and its complexities largely arise from shoehorning the GN build into "cargo package".

**Comment by kevinkassimo** [comment]
Worth noting this makes building and publishing native plugins harder (have to clone the repository and use relative path to deno crate in `Cargo.toml`)

I'm planning to try building something that automatically download plugins using `cargo`, and this is a main blocking issue.

**Comment by ry** [comment]
The problem is only with the windows crate... as a short term solution we could remove support for windows crate and publish 0.26

**Comment by kevinkassimo** [comment]
Hmm I wonder if everything in the `deno` crate is needed to create a plugin. It might make sense to split out another crate that provides the minimal interface just for plugin message passing (but yeah this also means plugins using this minimal crate would not be able to create workers)
