### ISSUE TITLE
Tokio 0.2 upgrade

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#3387]
Opening for tracking purposes.

I'm trying to update Deno to Tokio `master` branch (pending 0.2 release). 

For know it seems we have two dependencies blocking the transition:
- `tokio-rustls` - resources: `clientTlsStream`, `serverTlsStream`
- `reqwest` - resource: `httpBody`

Problems are related to `AsyncRead`/`AsyncWrite` traits as well as fact that we create tls connections from `TcpStream` which is incompatible with `master` branch.

These two dependencies are in already in `alpha` (just like tokio) so I expect they should be release one after another in short period.

**Comment by bartlomieju** [comment]
Tokio has landed! https://github.com/tokio-rs/tokio/releases/tag/tokio-0.2.0

I'll be working on the upgrade

**Comment by bartlomieju** [comment]
`tokio-rustls` landed with Tokio 0.2 support. 

Still waiting on https://github.com/seanmonstar/reqwest/issues/721

**Comment by kellytk** [comment]
@bartlomieju Reqwest has been [updated](https://github.com/seanmonstar/reqwest/pull/731).

**Comment by bartlomieju** [comment]
> @bartlomieju Reqwest has been [updated](https://github.com/seanmonstar/reqwest/pull/731).

Yes, I'm still waiting on release, but I guess I can use git rev until then

**Comment by bartlomieju** [comment]
Done in #3418!
