### ISSUE TITLE
Issue with HTTP's close method

### ISSUE THREAD

**Issue by ry** [denoland/deno#3390]
via @sholladay 

When I use serve() from http/server.ts, and I pass it port 0 to get a random available port, is there a clean way to determine which port was assigned?

Also, server.close() seems to wait for another request to come in before actually closing. If I call server.close(), Deno won't quit until I reload the page in the browser.

**Comment by bartlomieju** [comment]
> Also, server.close() seems to wait for another request to come in before actually closing. If I call server.close(), Deno won't quit until I reload the page in the browser.

Most likely the same problem as described in #3593, closing in favor of
