### ISSUE TITLE
need a way to get deno_std version of current Deno

### ISSUE THREAD

**Issue by axetroy** [denoland/deno#3395]
```bash
$ deno --version
deno: 0.24.0
v8: 8.0.192
typescript: 3.7.2
std: 0.23.0
```

```typescript
console.log(Deno.versions);

/*
{
  "deno": "0.24.0",
  "v8": "8.0.192",
  "typescript": "3.7.2",
  "std": "0.23.0"
}
*/
```

https://github.com/denoland/deno/blob/c6bb3d5a10ba8acceadcaa66050abcaefb7bc0bb/cli/js/version.ts#L2-L6

https://github.com/denoland/deno/blob/c6bb3d5a10ba8acceadcaa66050abcaefb7bc0bb/cli/flags.rs#L15-L19

**Comment by ry** [comment]
I think std version is confusing to users...

 Also I will be removing the "v8" and "typescript" parts of the output in #3389.

**Comment by axetroy** [comment]
Even if it is not output on the command line, it should be exported in `Deno.versions`

This is to facilitate future tool integration.

This is to facilitate future tool integration.

eg. third-party tools use `deno install`

It can know the version of `std` for current Deno version, and download the dependencies in advance.

**Comment by nayeemrmn** [comment]
> Even if it is not output on the command line, it should be exported in `Deno.versions`

But it's only applicable on the command line... I think we just need to figure out how to make the versions align again.

**Comment by Fenzland** [comment]
You may both import std@0.12, std@0.18 in your file and run with deno 0.25. So I think a std version in `deno --version` output is meaningless.

**Comment by ry** [comment]
reopening. See https://github.com/denoland/deno/pull/3446

**Comment by rsp** [comment]
> You may both import std@0.12, std@0.18 in your file and run with deno 0.25. So I think a std version in `deno --version` output is meaningless.

@Fenzland, yes I can import old versions of std in newer runtimes, but is all of the Deno API that is used by all of std modules guaranteed to be backwards compatible? This is not a rhetorical question, it would be good to know if old std versions will continue working with all new versions of Deno, or the other way around, or none of the above. This is a strategic decision for @ry to consider, not a simple one, as I tried to explain in #3320.

**Comment by axetroy** [comment]
I think this item is outdated

close
