### ISSUE TITLE
Add Node.js native module polyfills to std/node

### ISSUE THREAD

**Issue by kevinkassimo** [denoland/deno#3403]
Many Node.js native module polyfills are needed in `std/node`, to support loading npm packages (such that we are able to leverage some of the tools while Deno specific versions are not available yet).

Note some of the modules might not yet have a corresponding Deno API available. In that case, adding a new native binding for Deno or adding a new module in `std` modules might be reasonable.

#3382 is an example how to inject a polyfill for `require()`.

Some of the polyfill tasks can be Good First Issue.

- [x] `buffer`
- [ ] `child_process`
- [ ] `cluster` (maybe low priority?)
- [ ] `crypto`
- [ ] `dns`
- [x] `events`
- [ ] `fs` (partially, high priority)
- [ ] `http`/`https`/`http2`/`dgram`/`net`/`tls` (maybe low priority?)
- [x] `modules`
- [x] `os` (more bindings needed, #3802)
- [x] `path`
- [x] `querystring`  #4370 
- [ ] `readline`
- [ ] `repl`
- [ ] `stream`
- [ ] `tty`
- [ ] `url`
- [ ] `util` (partially)

**Comment by cknight** [comment]
I'm working on the 'os' polyfill, though as discussed in #3802 there's a lot of functionality Deno is missing.

**Comment by cknight** [comment]
@kevinkassimo - That's the 'os' polyfill taken as far as I can, so please mark this as partly completed.  Now moving onto 'events'.

**Comment by kevinkassimo** [comment]
@cknight Thanks so much! Marked

**Comment by cknight** [comment]
@kevinkassimo - That's the 'events' polyfill complete now (#3944, #3960, #4016).  I'm going to attempt to pick up fs next, though will progress this in small chunks due to its large size.

**Comment by dubiousjim** [comment]
@cknight see #4017, will bring us closer to being able to polyfill Node's fs

**Comment by cknight** [comment]
Nice one @dubiousjim.  I've not yet looked at detail into what Deno can offer, but at a glance it looks like your pending PRs will get us a lot closer to a full polyfill.

**Comment by bnoordhuis** [comment]
Is there consensus on if or how much of node's crypto module to reimplement?

It's got a pretty big API surface and openssl-isms leak through in many places but it should be possible to make basic functionality (cipher/decipher/hash/hmac/sign/verify) work for the most common ciphers and hashes using RustCrypto.

**Comment by ecyrbe** [comment]
currently working on os stuff impl.

**Comment by crowlKats** [comment]
@kevinkassimo #4370 took care of `querystring`

**Comment by acconrad** [comment]
@kevinkassimo i'm diving back into Deno after not working on it for a while (and I've only really contributed to the TypeScript portion). Which of these would be a good first issues?

**Comment by Soremwar** [comment]
@acconrad Good for starters would be `url` or `dns`
Most useful would be probably crypto(though in my opinion better handler by the API implementation that's in development)

**Comment by acconrad** [comment]
@Soremwar cool! `url` is massive and feels a bit over my head for the first one. `dns` seems pretty reasonable as does `crypto` (though would I also need to build out all of the helper classes like `Hash`, `Sign`, and `Cipher`?) if so I could just start with `dns` and see how that goes.

**Comment by lygstate** [comment]
assert?

**Comment by Soremwar** [comment]
Assert will be there as well @lygstate https://github.com/denoland/deno_std/pull/705

**Comment by lygstate** [comment]
Good to see

**Comment by pavel-kolesnikov** [comment]
`net` is required by rethinkdb (via https://cdn.skypack.dev/rethinkdb)
