### ISSUE TITLE
deno panics on REPL when specifying e.g. `deno -A`

### ISSUE THREAD

**Issue by kevinkassimo** [denoland/deno#3407]
Based on stack trace, it seems `run_script()` is called instead of `run_repl()`, and panics since we do not have a main module

**Comment by nayeemrmn** [comment]
This should be a flag error now, e.g. `deno repl -A` correctly reports the invalid argument.

I guess the flag parsing assumes that `deno` without a subcommand is `deno run`, when actually it is `deno repl` when there is also no main module.

**Comment by kevinkassimo** [comment]
`deno run` without providing a main module name is also crashing. I am making a PR for this.
