### ISSUE TITLE
Supports execute Binary AST directly

### ISSUE THREAD

**Issue by hsiaosiyuan0** [denoland/deno#3411]
Hi,

I notice that Deno call itself as `A secure runtime for JavaScript and TypeScript`, so in the future do we have a plan to support executing Binary AST directly according to [proposal-binary-ast](https://github.com/tc39/proposal-binary-ast)?

**Comment by kitsonk** [comment]
If the proposal gets to Stage 3, absolutely.  Maybe earlier if it gets implemented in V8.  Really the feature being supported in V8 is the critical bit.

**Comment by hsiaosiyuan0** [comment]
@kitsonk get it, thank you
