### ISSUE TITLE
deno fmt --check throw error in ci

### ISSUE THREAD

**Issue by zhmushan** [denoland/deno#3412]
[red: ](https://github.com/zhmushan/abc/commit/f5632e635c3ec1f1ef99ce0298b5ab53d86ed7fd/checks?check_suite_id=331164830)`deno fmt --check */**`
[red: ](https://github.com/zhmushan/abc/commit/86ead9dbeac8c22086c33ef3198cc8cc532ff46a/checks?check_suite_id=331143561)`deno fmt --check */**`

[green: ](https://github.com/zhmushan/abc/commit/8747ae404cd7ac8f455d5b1f9e84ec0534c30ccc/checks?check_suite_id=331152892)`deno run --allow-read --allow-write https://deno.land/std/prettier/main.ts --check`

**Comment by axetroy** [comment]
From the CI log, execution is here.

The program should exit normally.

https://github.com/denoland/deno/blob/a611788834e40153ef27c8f1d6b7fd52c8a016b1/std/prettier/main.ts#L226-L229

The current problem is deno@0.25.0 using deno_std@0.23.0. it leads to uncertainty about what will happen.

Maybe wait #3415 land, the problem can be solved

**Comment by zhmushan** [comment]
> From the CI log, execution is here.
> 
> The program should exit normally.
> 
> https://github.com/denoland/deno/blob/a611788834e40153ef27c8f1d6b7fd52c8a016b1/std/prettier/main.ts#L226-L229
> 
> The current problem is deno@0.25.0 using deno_std@0.23.0. it leads to uncertainty about what will happen.
> 
> Maybe wait #3415 land, the problem can be solved

thx
