### ISSUE TITLE
Standard Modules: ID generators

### ISSUE THREAD

**Issue by kt3k** [denoland/deno#3419]
JavaScript community has a few of popular id generators like the following (other than uuid):

- shortid
  - https://github.com/dylang/shortid
- nanoid
  - https://github.com/ai/nanoid
- ulid
  - https://github.com/ulid/javascript

How about including these to the standard modules?

**Comment by kevinkassimo** [comment]
I'm supportive of moving `std/uuid` to `std/idgen/uuid.ts` and potentially adding other ID generators. Not so sure which other ones to include though, since adding a new module is basically adding extra maintenance cost. (I would expect as Deno matures each different std module would have a list of maintainer volunteers)

**Comment by kt3k** [comment]
Note: npmtrends link https://www.npmtrends.com/shortid-vs-nanoid-vs-ulid-vs-uuid-vs-uniqid-vs-cuid

`uuid` seems by far the most popular one. `nanoid` and `shortid` come next in regard with the download count. `ulid` and `cuid` are less downloaded, but these 2 are ported to many different languages and `ulid` seems having nice [spec](https://github.com/ulid/spec).

**Comment by axetroy** [comment]
@kevinkassimo 

Should We open an issue and pin it for looking long-term maintenance volunteers for Specific modules.

**Comment by tunnckoCore** [comment]
The `cuid` may be with less downloads but is pretty great, stable and robust. First time hearing about `shortid`.

Definitely `uuid`, `cuid` and `nanoid`.

**Comment by kevinkassimo** [comment]
@axetroy Might be a good idea, although I doubt a concrete list could be established before 1.0 release
