### ISSUE TITLE
[bug] windows: Deno.realpath

### ISSUE THREAD

**Issue by zhmushan** [denoland/deno#3424]
```ts
const { realpath } = Deno
console.log(await realpath("."))
```
expected:
```
C:/Users/xxx
```

actual:
```
//?/C:/Users/xxx
```

**Comment by kevinkassimo** [comment]
Hmm this is funny since it is directly from `std::fs::canonicalize_path` from Rust. I wonder why Rust adds that prefix on Windows...

**Comment by kevinkassimo** [comment]
Looks like libuv does remove this prefix: https://github.com/libuv/libuv/blob/076df64dbbda4320f93375913a728efc40e12d37/src/win/fs.c#L2483-L2499

**Comment by zhmushan** [comment]
@kevinkassimo I created a pr, remove the realpath prefix in windows
