### ISSUE TITLE
Built-in lock file for subcommand std modules

### ISSUE THREAD

**Issue by nayeemrmn** [denoland/deno#3427]
We obviously need SRI for the std modules used for some subcommands.

It won't suffice to just re-enable the lock flags for these subcommands and push this responsibility to users. The URLs (and the assumption of what they contain) are **fixed at build time and masked from users**. It only makes sense that the checksums should be built-in beside them and checked implicitly, IMO.

Related: #200.

**Comment by ry** [comment]
@nayeemrmn I agree. I would actually prefer we were able to include that source code in the binary - but there's the problem that prettier is quite big and would increase the executable size. I think your solution of having checksums at compile time is a good intermediate step.

**Comment by kitsonk** [comment]
Oooh... I like this idea! 👍

**Comment by bartlomieju** [comment]
No longer needed - deno <subcommand> does not download std modules anymore (ref #3818, #3850 and #3865(
