### ISSUE TITLE
windows: `deno install` installs to the wrong directory

### ISSUE THREAD

**Issue by piscisaureus** [denoland/deno#3443]
My user profile is in `c:\users\bert`.
When I run `deno install bla http://bla.com/bla.ts` while I'm on another drive (e.g. `d:\`) then `deno install` will place installed binaries in `d:\users\bert`.

**Comment by zhmushan** [comment]
This is caused by [`const HOME_PATH = HOME || HOMEPATH;`](https://github.com/denoland/deno/blob/f51dcc12d7a75a677529d63eb53d7a577d5b9289/std/installer/mod.ts#L84)
Maybe we should use USERPROFILE as degradation on Windows
