### ISSUE TITLE
Support of Clipboard API without `--allow-run`

### ISSUE THREAD

**Issue by rsp** [denoland/deno#3450]
Summary
-
Deno could implement operations for getting and setting the system clipboard (copy/paste).

I wrote [a library for Deno that does that](https://github.com/rsp/deno-clipboard) but it needs the all-powerful `--allow-run` that ruins the permission system.

The browsers implement it with a standard API that could be used.

We would need new permissions like `--allow-copy` and `--allow-paste` because this would be a security risk to give access to the clipboard with no restrictions (people often copy/paste personal data, passwords, API keys and other credentials). In the browsers there are separate permissions "clipboard-read" and "clipboard-write" in the standard Permissions API.

document.execCommand
-
The older API to use the clipboard in the browsers was `document.execCommand("copy")`, 
`document.execCommand("cut")` and `document.execCommand("paste")`, see:

- https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand

navigator.clipboard
-
The newer API to use the clipboard in the browsers is via the global `navigator.clipboard` object:

- https://developer.mozilla.org/en-US/docs/Web/API/Navigator/clipboard

From [MDN on Clipboard](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard):

> The Clipboard API adds to the Navigator interface the read-only clipboard property, which returns the Clipboard object used to read and write the clipboard's contents. The Clipboard API can be used to implement cut, copy, and paste features within a web application.
> 
> Use of the asynchronous clipboard read and write methods requires that the user grant the web site or app permission to access the clipboard. This permission must be obtained from the Permissions API using the "clipboard-read" and/or "clipboard-write" permissions.

The `clipboard` object has 4 methods: 

> read() Requests arbitrary data (such as images) from the clipboard, returning a Promise. When the data has been retrieved, the promise is resolved with a DataTransfer object that provides the data.

> readText() Requests text from the system clipboard; returns a Promise which is resolved with a DOMString containing the clipboard's text once it's available.

> write() Writes arbitrary data to the system clipboard. This asynchronous operation signals that it's finished by resolving the returned Promise.

> writeText() Writes text to the system clipboard, returning a Promise which is resolved once the text is fully copied into the clipboard.

deno.land/x/clipboard
-
I wrote a library for Deno that implements readText() and writeText() on Linux, Mac and Windows:

- https://github.com/rsp/deno-clipboard

The `navigator.clipboard` also implements the EventTarget interface which my library doesn't.

navigator.clipboard in Deno?
-
This seems like something that would be ideally exposed by Deno itself:

- so the libraries don't spawn external processes just to use the clipboard
- so that the permissions can be controlled
- so that it is maximally familiar to how the browsers work

It would be most optimal to use the standard `window.navigator`:

- https://developer.mozilla.org/en-US/docs/Web/API/Navigator

Or should it be exposed in some other non-standard place like `Deno.clipboard`?

References
-
- https://github.com/rsp/deno-clipboard
- denoland/deno_website2#132
- https://developer.mozilla.org/en-US/docs/Web/API/Clipboard
- https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API
- https://developer.mozilla.org/en-US/docs/Web/API/Permissions_API
- https://developer.mozilla.org/en-US/docs/Web/API/Navigator/clipboard
- https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Interact_with_the_clipboard

**Comment by timreichen** [comment]
I would be in favor of having ```navigator.clipboard``` according to the [clipboard API specs](https://w3c.github.io/clipboard-apis).

**Comment by ry** [comment]
I'm also in favor of having `navigator.clipboard`. [Tho we need to consider the security carefully.](https://hackaday.com/2020/06/18/copy-and-paste-deemed-insecure/)

**Comment by crowlKats** [comment]
after finishing localStorage, i was thinking of working on this. what about `--allow-clipboard-write` & `--allow-clipboard-read` for perms?

**Comment by nayeemrmn** [comment]
Also note that the runtime permissions API for this should be at `navigator.permissions`.

**Comment by crowlKats** [comment]
So a bit ago i tried working on this, but there is a major problem: there is no cross platform crate to do what we need. i am not knowledgeable enough to make one myself either, so not sure what we can do but wait for one to emerge

**Comment by l3afblow3r** [comment]
Still waiting for this to be implemented.
I write system commands in JavaScript and run them through deno.
#### One use case I have:

`urldecode -clip <someurl>`
which copies the URL to the clipboard instead of printing to the console.

```
This is currently not possible through native functions.
```

**Comment by aiotter** [comment]
> So a bit ago i tried working on this, but there is a major problem: there is no cross platform crate to do what we need. i am not knowledgeable enough to make one myself either, so not sure what we can do but wait for one to emerge

How about this one?
https://github.com/ArturKovacs/arboard

It seems being deprecated on README, but actually it is just processing the ownership transfer now (https://github.com/ArturKovacs/arboard/issues/26).

It seems the required work for navigator.clipboard is not yet finished (see their `any-format` branch), but it's worth checking this repo for possibility to be used as a means of implementing the API.

**Comment by crowlKats** [comment]
We have discussed this, and we will not implement this, as it ties us to windowing systems (same reasoning as the Notification API), which we do not want as we want to keep deno headless.

**Comment by aiotter** [comment]
I'm sorry to hear that, but it's reasonable.
How about GUI interfaces (#3234)? Won't implement either?

**Comment by MierenManz** [comment]
@aiotter I assume that the response would be the same for GUI but there are third party projects like [astrodon](https://deno.land/x/astrodon@0.1.0-alpha) and [webview](https://deno.land/x/webview@0.7.0-pre.0) for deno for gui's

**Comment by crowlKats** [comment]
Something by the deno team itself in terms of GUI wont happen anytime soon. In the context of GUI we might then implement this, but thats not set in stone.

**Comment by zadeviggers** [comment]
@crowlKats Given that Deno now supports windowing to a certain extent with WebGPU, it would be great if this could be reconsidered. Perhaps in an environment without windowing support, Deno could fall back to some kind of console output, similar to how it does for the `window.alert` and `window.confirm` APIs.

**Comment by 0f-0b** [comment]
XTerm and a few other terminal emulators recognize the [OSC 52](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h4-Operating-System-Commands:OSC-Ps;Pt-ST:Ps-=-5-2.101B) escape sequence. VS Code [just added support today](https://code.visualstudio.com/updates/v1_91#_support-for-copy-and-paste-escape-sequence-osc-52). When run in such a terminal emulator, this program writes text to the clipboard without any permissions.

```ts
import { encodeBase64 } from "jsr:@std/encoding@^1.0.0/base64";

const encoder = new TextEncoder();

async function writeText(data: string): Promise<undefined> {
  const osc = encoder.encode(`\x1b]52;c;${encodeBase64(`${data}`)}\x07`);
  const writer = Deno.stdout.writable.getWriter();
  const promise = writer.write(osc);
  writer.releaseLock();
  try {
    await promise;
  } catch {
    // ignored
  }
}

await writeText("hello world");
```

**Comment by zadeviggers** [comment]
@0f-0b Wonderful! Given that it can be implemented with JS and work in a fair number of environments, should I make a PR adding the `writeText` part of the clipboard API? It could be expanded later to support other parts of the API using platform-specific APIs, like reading from the clipboard using MacOS's `pbpaste`.
