### ISSUE TITLE
Hide internal use/test only APIs from direct Deno namespace

### ISSUE THREAD

**Issue by kevinkassimo** [denoland/deno#3451]
Typing `Deno` in REPL shows:
```
{ ... setPrepareStackTrace, Console, stringifyArgs, DomIterableMixin }
```
IMO they are for internal use or test only, and should not directly live under Deno namespace. Maybe we can move them to `Deno._internals` or `Deno[Deno.symbols.internal]`.

(Also think we should move `Deno.customInspect` to `Deno.symbols.customInspect`, as the name `customInspect` tells us nothing about it being a `Symbol` (its name actually sounds like a function) and we might need to add more symbols in the future.)

**Comment by kitsonk** [comment]
I like both suggestions.  Better to use `Deno.symbols` than the `_` as well.  I think also on the `Deno[Deno.symbols.internal]` we should set the properties to be non-enumerable as well.
