### ISSUE TITLE
Resource table for plugins

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#3453]
I think plugins should be able to use the resource table to some extent. If this is not the case every plugin will need to build their own resource management system, with extra ops to list and close resources. If plugins can just use the builtin resource table, they can just use Deno.close and Deno.resources to close and list resources.

**Comment by bartlomieju** [comment]
Yeah, that was done intentionally to not expose anything besides control buffer and zero copy buffer to ops in plugins. It definitely makes sense to give access to `ResourceTable` but I'd opt to defer it until we split ops into crates - that will require some refactors to ops signatures (probably).

**Comment by lucacasonato** [comment]
> that will require some refactors to ops signatures (probably)

Probably, unless we add a new context.register_stateful_op function (next to context.register_op) with a different op signature. These types of ops would then have access to the resource table and any other state that is exposed to plugins. That way this can be added without breaking compat (if this happens after 1.0).
