### ISSUE TITLE
tty rows / columns

### ISSUE THREAD

**Issue by lifeiscontent** [denoland/deno#3456]
is there a way to get the rows / columns of the current terminal? I'm trying to create a terminal app and it requires the knowledge of the width/height of the screen. to know where to draw.

**Comment by kevinkassimo** [comment]
We don't have that binding yet. It makes sense for us to implement it through crates like https://crates.io/crates/termion

**Comment by BrunnerLivio** [comment]
@kevinkassimo I would be interested in contributing! Any plans how this should be exposed in the public API? Node offers [`writeStream.columns`](https://nodejs.org/api/tty.html#tty_writestream_columns) (e.g. `process.stdout.columns`).

**Comment by Fenzland** [comment]
You can try these:
```
Deno.run( { args: [ 'tput', 'lines' ], stdout:'piped' } );
Deno.run( { args: [ 'tput', 'cols' ], stdout:'piped' } );
// or
Deno.run( { args: [ 'stty', 'size' ], stdout:'piped' } );
```

**Comment by sinclairzx81** [comment]
Does anyone have any thoughts on how this should look as an API?

```typescript
// current
Deno.isTTY()

// candidate 1: augmenting the Deno object
Deno.isTTY()
Deno.ttySize() // { columns: number, rows: number } 

// candidate 2: augmenting the stdout object
const { columns, rows } = Deno.stdout

// candidate 3: deprecating Deno.isTTY() in favor of 'tty' namespace.
Deno.tty.isTTY()
Deno.tty.columns
Deno.tty.rows
```
Or perhaps something else?

**Comment by ry** [comment]
> const { columns, rows } = Deno.ttySize()

I like this the best, but I think it’s not general enough. Correct me if I’m wrong but I believe it’s possible to have multiple TTYs open per process (like doesn’t screen do this?)

**Comment by sinclairzx81** [comment]
@ry Hi, 

I'm not familiar of with any particular functionality that's geared specifically towards managing multiple TTY per processes (I mean, there might be something, but Id assume cli tools like `screen`, `tmux` would just manage that at the application level....but im just guessing). The closest thing i could think of might be 'Alternate Screens' which `screen` probably makes liberal use of.

```bash
$ tput smcup # enter alternate screen.
$ echo hello
$ tput rmcup # leave alternate screen.
```
or with node | deno (via ansi)
```javascript
console.log('\x1b[?1049h') // enter alternate screen.
console.log('hello')
console.log('\x1b[?1049l')  // leave alternate screen.
```
of via `crossterm` [source](https://github.com/crossterm-rs/crossterm/blob/master/src/terminal.rs#L122-L198)
```rust
use crossterm::{execute, Result, terminal::{EnterAlternateScreen, LeaveAlternateScreen}};
...
execute!(stdout(), EnterAlternateScreen).unwrap();
println!("hello");
execute!(stdout(), LeaveAlternateScreen).unwrap();
```
I note the `crossterm` crate was mentioned by @kevinkassimo. I've had a quick look and there is quite a bit in there to assist with various terminal operations, but I expect most of those are just proxies for writing ANSI control codes so could be implemented in TS space. But it does provide a cross platform API to query the size of the current terminal, so it seems good.

Did you have something in mind to better generalize the API?
