### ISSUE TITLE
Give plugins access to json_op helpers

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#3460]
It would be nice if Deno would expose the json_op rust helpers fully and also expose the json_op ts helpers. These helpers are very useful as they do a lot of the work related to async ops for you. 

The Rust helpers are pretty much completly exposed, except for the `blocking_json` helper, which is not exposed in ops/mod.rs.

The TS helpers would probably have to go into some std/plugins package. The ts helpers require some some very minimal tweaks to make them work with plugin ops.

**Comment by bartlomieju** [comment]
This is part of https://github.com/denoland/deno/issues/2180

**Comment by ry** [comment]
I guess we could move those helper functions into the core deno crate - they would be easier to access there.

**Comment by lucacasonato** [comment]
Ref #7033

**Comment by bartlomieju** [comment]
Resolved in #7336
