### ISSUE TITLE
Uncaught BrokenPipe: Broken pipe (os error 32)

### ISSUE THREAD

**Issue by debianw** [denoland/deno#3463]
My first hello world deno server crashed after a benchmark

```
import { serve } from 'https://deno.land/std@v0.24.0/http/server.ts';
const body = new TextEncoder().encode("Hello World\n");
const s = serve({ port: 8000 });

console.log("Listening on port 8000");

for await (const req of s) {
  req.respond({ body });
}
```

Run a **benchmark**

```
autocannon -c 100 -d 5 -p 10 http://localhost:8000
```

![Screen Shot 2019-12-08 at 9 16 28 PM](https://user-images.githubusercontent.com/1002407/70405198-fa02d300-1a01-11ea-8b23-eeef134c18f7.png)

**Environment:**
- MacOS 10.13.6
- Deno 0.26.0

**Comment by kevinkassimo** [comment]
Hmm your code does not look like a Deno script...
Otherwise based on the error message, it seems to be the problem that connection is closed before your response. If you are running the example like the one in https://deno.land/std/http/http_bench.ts, you might want to wrap a `try-catch`:
```ts
import { serve } from "https://deno.land/std/http/server.ts";

const addr = Deno.args[1] || "127.0.0.1:4500";
const server = serve(addr);

const body = new TextEncoder().encode("Hello World");

async function main(): Promise<void> {
  for await (const request of server) {
    try {
      await request.respond({ status: 200, body });   
    } catch { console.log("Response failed, maybe connection closed") }
  }
}

main();
```

**Comment by debianw** [comment]
@kevinkassimo sorry my mistake. I updated the issue with `deno` code

**Comment by debianw** [comment]
![Screen Shot 2019-12-08 at 9 53 03 PM](https://user-images.githubusercontent.com/1002407/70406098-3126b380-1a05-11ea-90ae-6a4d98e9b9ca.png)

**Comment by debianw** [comment]
@kevinkassimo also your code crashed after running the benchmark with this error: `Response failed, maybe connection closed`

![Screen Shot 2019-12-08 at 9 59 57 PM](https://user-images.githubusercontent.com/1002407/70406378-20c30880-1a06-11ea-81dd-5ddbabd94b73.png)

**Comment by debianw** [comment]
Also process die after running benchmark a couple of times.

![Screen Shot 2019-12-08 at 10 19 21 PM](https://user-images.githubusercontent.com/1002407/70407248-3423a300-1a09-11ea-832a-8b7aafa99ed5.png)

**Comment by zhmushan** [comment]
@kevinkassimo Now it is 10053
```
error: Uncaught ConnectionAborted: An established connection was aborted by the software 
in your host machine. (os error 10053)
► $deno$/dispatch_minimal.ts:64:11
    at DenoError ($deno$/errors.ts:20:5)
    at unwrapResponse ($deno$/dispatch_minimal.ts:64:11)
    at sendAsyncMinimal ($deno$/dispatch_minimal.ts:107:10)
```
