### ISSUE TITLE
http/file_server broken

### ISSUE THREAD

**Issue by axetroy** [denoland/deno#3465]
/cc @zhmushan

```shell
$ deno --version
deno 0.26.0
$ deno --allow-net https://deno.land/std/http/file_server.ts
HTTP server listening on http://0.0.0.0:4500/
``` 

access server via `browser` or `curl` and got 500 error

```bash
$ curl http://0.0.0.0:4500/
Internal server error
```

**Comment by zhmushan** [comment]
You should run:
```
deno --allow-net --allow-read https://deno.land/std/http/file_server.ts
```
This is because we need permission to read files.

**Comment by axetroy** [comment]
haa. I forgot it and Thx. 😢

**Comment by kitsonk** [comment]
Is it swallowing permission error though? It should log them to the console if it is trapping them.

**Comment by zhmushan** [comment]
@kitsonk I agree with you.
@axetroy Could you reopen this issue?
