### ISSUE TITLE
deno 0.25.0 or later sometimes hangs up on single core processor.

### ISSUE THREAD

**Issue by horihiro** [denoland/deno#3466]
I tried to execute deno on Azure App Service on Linux also (PaaS service based on Linux).

I confirmed that deno 0.24.0 or before worked without any problem.
But when using 0.25.0 or later, the execution is hang up even if the following simple code.

```sh
# deno eval "import { serve } from 'https://deno.land/std/http/server.ts';"
Compile https://deno.land/std/http/server.ts
Download https://deno.land/std/io/bufio.ts
Download https://deno.land/std/textproto/mod.ts
Download https://deno.land/std/http/http_status.ts
Download https://deno.land/std/testing/asserts.ts
Download https://deno.land/std/util/async.ts
(hang up)
```

App Service on Linux is based on Docker, so I tried deno 0.25.0 on the container image (ex. `appsvc/php:5.6-apache_20191031.7`, which is used on the App Service on Linux) on local Docker, and I confirmed it worked.

I think this is compatibility issue between App Service on Linux and deno 0.25.0 or later.

Could you please let me know any other check points in order to make deno work if you know?

I would appreciate your help.

Best Regards,

**Comment by kitsonk** [comment]
Can you add `-L debug` to the command line please?

**Comment by horihiro** [comment]
Hi @kitsonk 

I attached log file generated by `deno eval "import { serve } from 'https://deno.land/std/http/server.ts';" -L debug > debug.log`
[debug.log](https://github.com/denoland/deno/files/3938783/debug.log)

Could you please look into it?

Regards,

**Comment by kitsonk** [comment]
How is this different than #3464?

**Comment by horihiro** [comment]
This issue is about Linux platform.
#3464 is about Windows platform.

**Comment by horihiro** [comment]
any comments?

**Comment by horihiro** [comment]
I found that this issue occurs on single core processor only.
This is similar to #2124 .

**Comment by horihiro** [comment]
I confirmed same behavior on local docker container (`appsvc/php:5.6-apache_20191031.7`) launched with cpu count restricted by `--cpuset-cpus=0` option.

**Comment by hayd** [comment]
potentially will be fixed by tokio 0.2 update (maybe it's due to one of the few `block_on`s).

once fixed, should add a test with taskset to restrict to one cpu.

**Comment by kevinkassimo** [comment]
cc @bartlomieju

**Comment by bartlomieju** [comment]
> cc @bartlomieju
> I wonder if it has something to do with #3381 ...

Yeah, that might be the problem, I'd wait a few more days, we're waiting only for `reqwest` at this point to move to Tokio 0.2 (already updated just waiting on release). It should be easier to reason about it then.

**Comment by bartlomieju** [comment]
@horihiro @kevinkassimo just tried it with tokio 0.2 - it seems to work even with single core available. Gonna keep this issue open until we cut a new release containing tokio upgrade.

**Comment by horihiro** [comment]
Thanks @bartlomieju !

v0.28.0 is working very well!

I close this issue.
