### ISSUE TITLE
apparent regression with timer handling in deno

### ISSUE THREAD

**Issue by alexjeffburke** [denoland/deno#3468]
Hi,

For some time now the Unexpected project (https://github.com/unexpectedjs/unexpected) has been maintaining an ESM build of the library that is compatible with deno.

After re-running the tests today, we seem to have hit an issue in the latest deno - it can be seen in one of our travis builds (https://travis-ci.org/unexpectedjs/unexpected/jobs/622641351#L753). The relevant chunk appears to be:

```
error: Uncaught Error: assert
754► $deno$/util.ts:31:11
755    at assert ($deno$/util.ts:31:11)
756    at setGlobalTimeout ($deno$/timers.ts:44:3)
757    at setOrClearGlobalTimeout ($deno$/timers.ts:58:5)
758    at firePendingTimers ($deno$/timers.ts:196:5)
759Makefile:101: recipe for target 'test-deno' failed
```

I'm relatively sure this is a platform issue because we've not seen this issue on any other JS engine and this previously worked without issue. The test that triggered this didn't seem to be related to timers itself so my guess would be something that only occurs under stress. That said, beyond the above though I'm unsure of other assistance I can provide in terms of debugging this.

Thanks.

**Comment by bartlomieju** [comment]
CC @kevinkassimo

**Comment by kevinkassimo** [comment]
Ah yes, based on a quick check I believe the offending line is this one:
https://github.com/denoland/deno/blob/90c5aadbca8b47fc43bd3ece80e007b1b546c402/cli/js/timers.ts#L195
It should have been `const due = nextDueNode && Math.max(nextDueNode.due, now);` to pass the assert.
I'll do a PR later today.

**Comment by kevinkassimo** [comment]
I opened #3477 which should be a fix for this. I cloned `unexpected` and ran your tests for quite a few times with the patched deno, and the error went away.

**Comment by alexjeffburke** [comment]
Really appreciate your taking a look at it :-)

Soon as that's out in a release I'll revert the temporary CI pinning so we're running against the latest version again.

**Comment by kevinkassimo** [comment]
@alexjeffburke Sorry about my oversight. Also it is really nice to know that `unexpected` supports Deno. We could probably add it to https://github.com/denolib/awesome-deno

**Comment by alexjeffburke** [comment]
@kevinkassimo oh no probs, I'm glad it has proved useful! And it'd be really great to be included on that list. We also did porting work in some of our own dependencies, so once I get around to smuggling in a few more ESM builds we should have some more things to offer for the registry :)

**Comment by alexjeffburke** [comment]
Unexpected tests are successfully executing against the latest (0.27.0) release - build available here: https://travis-ci.org/unexpectedjs/unexpected/builds/627287821

As such, I am closing this issue :)
