### ISSUE TITLE
Question: It is possible to use facebook/proxygen?

### ISSUE THREAD

**Issue by ecreeth** [denoland/deno#3476]
I would like to know if there is a way or is it possible to implement this [server](https://github.com/facebook/proxygen) with deno

**Comment by kitsonk** [comment]
From the repo...

> This project comprises the core C++ HTTP abstractions used at Facebook. Internally, it is used as the basis for building many HTTP servers, proxies, and clients. This release focuses on the common HTTP abstractions and our simple HTTPServer framework. Future releases will provide simple client APIs as well. The framework supports HTTP/1.1, SPDY/3, SPDY/3.1, HTTP/2, and HTTP/3. The goal is to provide a simple, performant, and modern C++ HTTP library.

It is a set of C++ library abstractions for building C++ web servers.  What do you mean by implement?

**Comment by ecreeth** [comment]
@kitsonk. This is a slightly crazy question, what I want to say is that if it is possible to use this type of web servers to embed deno files.
As an alternative to:
```js
import { serve } from "https://deno.land/std@v0.24.0/http/server.ts";
const body = new TextEncoder().encode("Hello World\n");
const s = serve({ port: 8000 });
console.log("http://localhost:8000/");
for await (const req of s) {
  req.respond({ body });
}
```
Thanks for your feedback!

**Comment by kitsonk** [comment]
Still not sure what you are asking.  As an alternative to what end?  What problem are you trying to solve?

If you want to use a C++ library to create your web server, you should do that.  If you want to use Deno, you should do that.  Deno provide runtime APIs for managing network connections that are built on Rust.  What you are implying is like saying "how can I use a hammer to remove my screws?"

**Comment by ecreeth** [comment]
😄 I'm so sorry, I had a wrong idea. Thanks for your feedback
