### ISSUE TITLE
question: custom method support

### ISSUE THREAD

**Issue by Oloompa** [denoland/deno#3482]
On node it is not possible to use custom method even if RFC 2616 allow it. It was due to hard code allowed method list on http parser. see https://github.com/nodejs/node-v0.x-archive/issues/3192

Does deno allow to use custom methods ?

**Comment by sholladay** [comment]
Why do people want to use HTTP but without following normal HTTP conventions? What is the use case?

**Comment by Oloompa** [comment]
To use an app protocol over HTTP. The use case is RPC using methods for procedure names.

RFC 2616 allow use of custom methods. Why do you want to block this standard feature ?

**Comment by sholladay** [comment]
I'm not a Deno maintainer, but personally I don't implement something just because a standard allows for it. It's important to show a concrete use case that doesn't have a cleaner solution.

I would be willing to implement this in [Pogo](https://GitHub.com/sholladay/pogo) if Deno supports it.

**Comment by Oloompa** [comment]
The problem in node.js was that http parser was blocking the ability to use other methods that listed ones. It was deliberately blocked.

The question here is "is the http parser rigidity same as nodejs" ?

**Comment by ry** [comment]
@Oloompa No, you can use any verb: https://github.com/denoland/deno/blob/fcae4a7c0dc74701f3b1919bfd76cfdc1a0321ed/std/http/server.ts#L312
But as the one who imposed that restriction in Node, I would strongly discourage the use of verbs outside of the spec.

**Comment by Oloompa** [comment]
@ry thanks for answer
