### ISSUE TITLE
permission errors are swallowed

### ISSUE THREAD

**Issue by zhmushan** [denoland/deno#3483]
It seems that some std modules' permission error is swallowed.
e.g.
```sh
import { exists } from "https://deno.land/std/fs/mod.ts";
const a = await exists("./a.json");
console.log(a)

# output "false" without `--allow-read`, although `a.json` exists.
```
As you can imagine, there must be many modules' permission error is swallowed.

related: #3465

**Comment by axetroy** [comment]
This is a legacy issue.

In earlier versions, if you want to read a file, Deno will prompt to asked if it is allowed

In the current version, it will not prompt

This leads to this problem

```bash
$ deno --version
deno: 0.15.0
v8: 7.7.200
typescript: 3.5.1

$ deno a.ts
Compile file:///Users/axetroy/go/src/github.com/axetroy/dvm/test/a.ts
️⚠️  Deno requests read access to "/Users/axetroy/go/src/github.com/axetroy/dvm/test/a.json". Grant? [a/y/n/d (a = allow always, y = allow once, n = deny once, d = deny always)] y
resolve:  true

$ deno a.ts
️⚠️  Deno requests read access to "/Users/axetroy/go/src/github.com/axetroy/dvm/test/a.json". Grant? [a/y/n/d (a = allow always, y = allow once, n = deny once, d = deny always)] n
resolve:  false

$ dvm use v0.26.0
Currently using Deno v0.26.0

$ deno a.ts
Compile file:///Users/axetroy/go/src/github.com/axetroy/dvm/test/a.ts
resolve:  false

$ deno --allow-read a.ts
resolve:  true
```

**Comment by axetroy** [comment]
We can try to ensure read permissions before reading the file, but permission permission is an asynchronous method, not work for synchronization method.

So this is not a solution

/cc @kt3k

```typescript
/**
 * Test whether or not the given path exists by checking with the file system
 */
export async function exists(filePath: string): Promise<boolean> {
  return Deno.permissions
    .request({
      name: "read",
      path: filePath
    })
    .then(({ state }) => {
      if (state === "granted") {
        return Deno.lstat(filePath)
          .then((): boolean => true)
          .catch((err): boolean => false);
      } else {
        throw new Error("No Permission");
      }
    });
}
```

**Comment by kt3k** [comment]
I think we don't need to ensure read permission before checking files. How about just throwing PermissionError from exists/existsSync when there's no permission. We can use e.name property for checking whether the error is permission error or not.

```js
e.name === "PermissionError"
```

**Comment by axetroy** [comment]
Count on similar situations

Then mark a TODO list to fix

- [ ] exists() #3493

https://github.com/denoland/deno/blob/df7d8288d984f703722fae161b7d32fae9ab3149/std/fs/exists.ts#L6-L10

- [ ] copy()

https://github.com/denoland/deno/blob/df7d8288d984f703722fae161b7d32fae9ab3149/std/fs/copy.ts#L20-L28

- [ ] emptyDir()

https://github.com/denoland/deno/blob/df7d8288d984f703722fae161b7d32fae9ab3149/std/fs/empty_dir.ts#L8-L16

**Comment by axetroy** [comment]
all done. 

Any other supplements? If not, I think this should be close now.

**Comment by zhmushan** [comment]
@axetroy thx!
