### ISSUE TITLE
want: add file.readAt() and file.writeAt()

### ISSUE THREAD

**Issue by axetroy** [denoland/deno#3508]
Offset operations can currently be performed with `seek`, but some concise APIs are missing

These APIs are more semantic and easier to understand

`Golang` also provides a similar API

```golang
import (
    "fmt"
    "os"
)

func main() {
    f, _ := os.OpenFile("1.go", os.O_RDWR, os.ModePerm)
    f.WriteAt([]byte("widuu"), 10) // write at offset = 10
    b := make([]byte, 20)
    d, _ := f.ReadAt(b, 10)    // read from offset = 10
    fmt.Println(string(b[:d])) //widuudhellowordhello
}
```

## file.readAt(bytes: Uint8Array, offset: number)

```ts
const file = Deno.open("./file.txt")

const bytes = new Uint8Array(10)

file.readAt(bytes, 20); // Read 10 bytes of data with an offset of 20
```

mock api

```ts
async function readAt(bytes: Uint8Array, offset: number) {
  await this.seek(offset, 0)
  await this.read(b)
  await this.seek(0, 0) // reset offset
  return b
}
```

## file.writeAt(bytes: Uint8Array, offset: number)

same as above

### Why

Should have the API to quickly read/write some data from file

Or maybe extend the `Deno.read(b: Uint8Array)` API to `Deno.read(b: Uint8Array, offset?: number)` will be better?

**Comment by kevinkassimo** [comment]
Worth noting libc posix implements offset-based [`pread`](https://github.com/bminor/glibc/blob/5cb226d7e4e710939cff7288bf9970cb52ec0dfa/sysdeps/posix/pread.c#L26-L57), [`pwrite`](https://github.com/bminor/glibc/blob/5cb226d7e4e710939cff7288bf9970cb52ec0dfa/sysdeps/posix/pwrite.c#L26-L57) simply as seek then write, so IMO we don't really need to extend Deno cli API on `Deno.read` for it.

Adding `readAt`/`writeAt` to `File` or to std both sounds okay to me.

**Comment by caspervonb** [comment]
Adding an optional offset is the way to go IMHO.

**Comment by fvkramer** [comment]
This issue has been open for a while - I'll work on it.

**Comment by Caryyon** [comment]
I'm jumping on this one.

**Comment by caspervonb** [comment]
Is anyone actively working on this?

**Comment by fvkramer** [comment]
Hey, I'm not. I assumed the person who posted after me was taking it. It doesn't look like anyone is working on it

**Comment by Caryyon** [comment]
@caspervonb @fvkramer i have something started but i'm also having a kid like with in 2 weeks.... so if you get this done just toss it out there.

**Comment by Paosder** [comment]
Any updates? I'm really looking forward to it.

**Comment by lucacasonato** [comment]
You can already do this with `Deno.seek`

**Comment by caspervonb** [comment]
It's a worth-while optimisation but I won't be getting around to it for a while.
In the meantime you can fake it with seek.

WASI does that and the performance hit is not that terrible.
https://deno.land/std@0.81.0/wasi/snapshot_preview1.ts#L795

**Comment by crowlKats** [comment]
The goal of built-ins is to have a reasonable set of APIs on which further capabilities can be abstracted on; this feature seems to me more like something that _could_ be done in std, and don't see the necessity to implement this for performance benefits. Especially with the various improvements to the op layer, performance concerns shouldn't be as bad anymore as when this issue was being discussed, so closing.
