### ISSUE TITLE
the same code may need to be reduced

### ISSUE THREAD

**Issue by xiaoxintang** [denoland/deno#3512]
### there are they
1. https://github.com/denoland/deno/blob/master/std/node/util.ts
2. https://github.com/denoland/deno/blob/master/std/encoding/yaml/utils.ts
> i think the second link's code maybe better for typescript

**Comment by ry** [comment]
Oops yes we should

**Comment by xiaoxintang** [comment]
I want to do it myself . but there are some question to  ask you , if i cloud do this
1. i will create  new named `/std/util/types.ts` & `/std/util/types_test.ts`
2. all the `isXXX` function will move to `/std/util/types.ts`
>>some import looks like `import {isNullOrUndefined} from '../../../util/types.ts'` ,so long...
3. remove the old file && test file if they are empty

**Comment by bartlomieju** [comment]
No longer relevant
