### ISSUE TITLE
prettier code error

### ISSUE THREAD

**Issue by xiaoxintang** [denoland/deno#3516]
when i run `deno --allow-read --allow-write https://deno.land/std/prettier/main.ts`
> deno 0.26.0
![image](https://user-images.githubusercontent.com/24927686/71049336-fa773880-217c-11ea-8575-2b212d6a8ab4.png)

**Comment by nayeemrmn** [comment]
This is equivalent to `deno --allow-read --allow-write https://deno.land/std/prettier/main.ts **/*`.

What happens when you run this on a known good module?

**Comment by xiaoxintang** [comment]
> This is equivalent to `deno --allow-read --allow-write https://deno.land/std/prettier/main.ts **/*`.
> 
> What happens when you run this on a known good module?

![image](https://user-images.githubusercontent.com/24927686/71050932-90ad5d80-2181-11ea-9302-2e7f14b1fbef.png)

**Comment by nayeemrmn** [comment]
Yes, where are you running it? You're currently feeding it everything in your CWD recursively. That probably includes some invalid file.

**Comment by xiaoxintang** [comment]
> Yes, where are you running it? You're currently feeding it everything in your CWD recursively. That probably includes some invalid file.

![image](https://user-images.githubusercontent.com/24927686/71051224-8b044780-2182-11ea-8b40-6e0fa0599910.png)

just inside the project

**Comment by nayeemrmn** [comment]
You have to specify the input modules at the end of your command or it'll try to format everything in there. Working as expected.

**Comment by xiaoxintang** [comment]
> You have to specify the input modules at the end of your command or it'll try to format everything in there. Working as expected.

sorry, my fault,i just follow the `/std/prettier/README.md`,by the way , can you tell me whay i can‘t pass the [ci](https://github.com/denoland/deno/pull/3517/checks?check_run_id=353767249)
