### ISSUE TITLE
Is it possible to provide a cli command to convert ts file to js file ?

### ISSUE THREAD

**Issue by wjw99830** [denoland/deno#3543]
Convert all `.ts` to `.js` including filenames and import urls. Make deno program run in both browser(type="module") and deno runtime without any modification and make `import()` work as expected.

Just like `tsc && convert-dot-ts-to-dot-js`.

**Comment by nayeemrmn** [comment]
I think any use case of this is intended to be satisfied by `deno bundle`.

Otherwise, such a tool would be easy to create as a user module once #3442 lands. I wouldn't expect a built-in `tsc` subcommand or anything like that: ref #3281.

**Comment by nayeemrmn** [comment]
@wjw99830 Can you close this?

**Comment by nayeemrmn** [comment]
@bartlomieju Satisfied by `deno bundle`. Can this be closed?
