### ISSUE TITLE
Sample demo from the official website  （https://deno.land/）

### ISSUE THREAD

**Issue by Topthinking** [denoland/deno#3549]
![image](https://user-images.githubusercontent.com/13382821/71433548-c969ab80-271a-11ea-87c0-8df08638aead.png)

```ts
import { serve } from "https://deno.land/std@v0.24.0/http/server.ts";
const body = new TextEncoder().encode("Hello World\n");
const s = serve({ port: 8000 });
console.log("http://localhost:8000/");
for await (const req of s) {
  req.respond({ body });
}
```

**Comment by kevinkassimo** [comment]
Hmm strange, I cannot reproduce this issue. Can you try reloading your dependency through `deno -r --allow-net server.ts`? (You might want to put the flags before the filename)

**Comment by kevinkassimo** [comment]
Oh wait. Based on your screenshot I saw Deno is trying to try on `.ts` and `.js` extensions. This looks like a fairly old release of Deno. Can you also try updating Deno to the latest version? (Notice that the installation location is also slightly changed)

**Comment by motss** [comment]
Try clearing the cache sometimes does help if it still using some old modules.

**Comment by Topthinking** [comment]
@kevinkassimo  I installed it with this command

```
curl -fsSL https://deno.land/x/install/install.sh | sh
```

**Comment by Topthinking** [comment]
@kevinkassimo I installed it with this command，but the version has not changed

![image](https://user-images.githubusercontent.com/13382821/71458131-4b6dd900-27dc-11ea-8819-9dec1618a8a4.png)

**Comment by Topthinking** [comment]
> Clearing the cache sometimes does help as it could still be using some old modules.
> 
> ```shell
> $ deno --reload --allow-net server.ts
> ```

Still can't work

![image](https://user-images.githubusercontent.com/13382821/71458202-9c7dcd00-27dc-11ea-89de-f4afc4ec0d87.png)

**Comment by kevinkassimo** [comment]
@Topthinking This is because the installation directory has changed. Try running `which deno`.

The updated installation location should be (based on your screenshot) `/Users/top/.local/bin/deno`

**Comment by Topthinking** [comment]
> @Topthinking这是因为安装目录已更改。尝试跑步`which deno`。
> 
> 更新的安装位置应为（基于您的屏幕截图） `/Users/top/.local/bin/deno`

successful

![image](https://user-images.githubusercontent.com/13382821/71458344-570dcf80-27dd-11ea-98f5-a81ac1338328.png)

**Comment by Topthinking** [comment]
🎉![image](https://user-images.githubusercontent.com/13382821/71458460-c4216500-27dd-11ea-9a9c-2d4dcc6a5e56.png)
