### ISSUE TITLE
Expose DENO_DIR

### ISSUE THREAD

**Issue by MarkTiedemann** [denoland/deno#3551]
I'm writing a script that needs to know the location of `DENO_DIR`. Of course, that's easy if `Deno.env().DENO_DIR` is not `undefined`. However, if it is, I'd have to replicate the logic in https://github.com/denoland/deno/blob/master/cli/deno_dir.rs, which uses https://docs.rs/dirs/2.0.2/dirs/, which unfortunately means it's pretty hard to replicate - not to mention brittle.

Do you think it makes sense to expose the `DENO_DIR` location via an API? For example, `Deno.denoDir`?

My current workaround is to use `Deno.execPath` to `Deno.run()` `deno info` and parse the output... which is slow and brittle and requires `--allow-run` permissions...

**Comment by bartlomieju** [comment]
@MarkTiedemann can you give an example use-case?

**Comment by MarkTiedemann** [comment]
I guess I'm not specifically looking for `DENO_DIR`; I'm looking for something like `import.meta.url`, but instead of returning the TS source path, it should return the path of the compiled JS.

The use case is for a custom build system.. so pretty niche.

**Comment by CGQAQ** [comment]
> it should return the local path of the compiled JS.
> The use case is for a custom build system.. so pretty niche.

But Deno will exposing ts compiler API in the userland, just use it for custom build system is enough IMO

**Comment by ry** [comment]
Exposing the info from “deno info” programmatically makes sense to me. Maybe we should take the opportunity to figure out how to also to access “Deno info” beyond the DENO_DIR. Like what if someone wants dependency info? They shouldn’t need to spawn a new Deno process for that.

**Comment by bartlomieju** [comment]
> Exposing the info from “deno info” programmatically makes sense to me. Maybe we should take the opportunity to figure out how to also to access “Deno info” beyond the DENO_DIR. Like what if someone wants dependency info? They shouldn’t need to spawn a new Deno process for that.

Ref https://github.com/denoland/deno/pull/3035

I'll write up more info in the evening about it.

**Comment by bartlomieju** [comment]
Okay so here are other related issues:
- #3069 
- #2096

Generally providing APIs as described above should be straight-forward, however @kitsonk asked to wait with it until compiler is refactored (which is a pending PR #3442).

As for the API itself I think something like `Deno.getModuleInfo(<module_url>)`; it could provide following info out-of-the-box (without any changes to current infra):
- cached file path (for remote modules only)
- compiled file path
- source map file path
- content type
- compilation hash
- dependency graph (either simplified - only url to dep, or detailed - including all the info described above)

**Comment by ry** [comment]
Maybe since this information is available from "deno info" and because we're trying to match APIs to subcommands where possible, we should have "Deno.info" which somehow could return DENO_DIR.

**Comment by bartlomieju** [comment]
> Maybe since this information is available from "deno info" and because we're trying to match APIs to subcommands where possible, we should have "Deno.info" which somehow could return DENO_DIR.

It would play nicely with JS deps API (which is exposed as `deno info <script>`). It's now feasible to that after landing compiler refactor.

Ref #2096

**Comment by MarkTiedemann** [comment]
Don't have this use-case anymore. Closing for now.
