### ISSUE TITLE
Blocked net requests still make requests to remote server

### ISSUE THREAD

**Issue by teleclimber** [denoland/deno#3552]
If you make a network request that Deno disallows because you don't have the right permissions you get an error. However the request is still sent to the remote server.

For example this will error if run without specifying `--allow-net` or `--allow-all`:

```
const dat = await fetch('https://some-remote.server/data/file.txt');
console.log(dat);
```

But the request is still sent to the server.

Same goes for dynamic imports:

```
import('https://some-remote.server/packages/target.ts').then( m => { m.default(); });
```

This errors but the request is still sent to the server.

It also does this for static imports with `--no-remote`.

The big danger here obviously is that dynamic requests can be used for data exfiltration. Blocked net access should not only error, they should not be allowed to go out at all.

It's hard to create a fully reproducible test case, but FWIW I uncovered this while building [deno-sandbox-tests](https://github.com/teleclimber/deno-sandbox-tests).

I should note that I have not been able to check this independently of deno-sandbox-tests (which runs its "remote" server locally and on HTTP). I don't have an actual remote server handy for this and I was not successful in using a proxy to snoop on Deno requests.

**Comment by nayeemrmn** [comment]
> It also does this for static imports with `--no-remote`.

Can you double check this particular case? I recently worked on the code around this I'm not sure how it could be the case.

Actually, how have you observed any of this? Why would a request only get sent out for a _physically_ remote server?

**Comment by teleclimber** [comment]
> Actually, how have you observed any of this? 

I am building [deno-sandbox-tests](https://github.com/teleclimber/deno-sandbox-tests) specifically for the purpose of testing Deno's ability to block things that I expect it to block. As such it runs a dummy remote server which serves remote requests, and also tracks whether something was requested.

> Can you double check this particular case?

I took another look at that test case in deno-sandbox-tests and I don't see a mistake. You can see it [here](https://github.com/teleclimber/deno-sandbox-tests/blob/5c269d01fca4a042f2f460a751a6c4279c9f61ae/deno-tests/remote.js#L20).

I'm surprised by the behavior as well. I'm hoping someone who is able to sniff Deno's requests can confirm or deny that this is happening. (I tried but failed to set this up in the limited time I have today).

Thanks.

**Comment by nayeemrmn** [comment]
https://github.com/teleclimber/deno-sandbox-tests/blob/5c269d01fca4a042f2f460a751a6c4279c9f61ae/lib/run-test.js#L100

There's your culprit :) Don't detect responses in your dummy server until after this or clear them afterwards.

The other `DANGER`s seem not to correctly specify Deno's currently intended behaviour but I understand you have issues open about those.

Is this okay?

**Comment by teleclimber** [comment]
D'oh! Thanks for your help! 

Clearly deno-sandbox-tests needs more work and better tests. I'm working on improving it, but when I tested a couple of scenarios independently I was unable to reproduce the result that it's showing.

So I'm closing this. Thanks and sorry for the trouble.
