### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by HaoBofei** [denoland/deno#3561]
thanks your reading at first,,
i'm a newcomer to golang, and  my english is poor, ,follows are my issues:
i use windows, and after i input "go get github.com/ry/v8worker2", vscode tips 
"
# pkg-config --cflags  -- v8.pc
Failed to open 'v8.pc': No such file or directory
No package 'v8.pc' found
pkg-config: exit status 1
" 

and when i execute build.py, powerShell tips 
"
out_path None
Rebuilding V8
"

i have already execute "git submodule update --init", but it doesn't work ,, so how can i solve issues and install v8worker2 successfully

**Comment by kevinkassimo** [comment]
Hi. Are you referring to the correct updated installation guide? Since Deno no longer uses v8worker (as we migrated to Rust).

(Also I assume you speak Chinese? In that case I'll also translate below):
你好。你用的是更新了的安装教程吗？Deno已经不再使用v8worker了（我们现在使用的是Rust）

**Comment by HaoBofei** [comment]
i just want to find a way to use javascript in golang, and v8worker2 looks more efficient than goja and otto, but i can't solve the problem. if there's a way to fix it, i really appreciate
by the way, i'm indeed chinese @kevinkassimo

**Comment by lucacasonato** [comment]
Hey @HaoBofei. Can you close this issue here and create one on https://github.com/ry/v8worker2? This issue belongs there.
