### ISSUE TITLE
Stream API for HTTP requests (Server implements ReadableStream<ServerRequest>)

### ISSUE THREAD

**Issue by rsp** [denoland/deno#3570]
Is this a completely crazy idea, or would it make sense for the `Server` class
(returned by the `serve()` function in `std/http/server.ts`) to be a proper `ReadableStream` of `ServerRequest` objects, instead of just `AsyncIterable<ServerRequest>`?

Commenting @ry's [comment](https://github.com/denoland/deno_std/issues/386#issuecomment-492666037) in denoland/deno_std#386 

> there are situations where a server becomes overloaded and should not try to get new requests. There should be some way of giving back pressure.

Since WHATWG Streams are likely to be implemented anyway (see: #3494) then maybe they could be used for things like this instead of reinventing the API (see: [Pipe chains and backpressure](https://streams.spec.whatwg.org/#pipe-chains) in the spec).

I like the current for-await loop API but it seems confusing (see: #3555) so there are already ideas to change it.
 
Having the HTTP server API provide a ReadableStream of requests, it could have a standardized way to handle things like backpressure while also having a `getIterator()` method to get an actual iterator object:

- https://streams.spec.whatwg.org/#rs-get-iterator

> The `getIterator` method returns an async iterator which can be used to consume the stream.

and since "The `@@asyncIterator` method is an alias of `getIterator()`" - see https://streams.spec.whatwg.org/#rs-asynciterator - then it already implements async iterable protocol and could be used in the for-await loop directly just like it is today.

(Would changing the current HTTP server API to a ReadableStream of requests be even backwards compatible? Or am I wrong here?)

Currently the `serve()` method returns a `Server` instance, and `Server` class is defined as:
```
export class Server implements AsyncIterable<ServerRequest> {
  // ...
}
```

If I read the WHATWG Streams spec correctly, then the ReadableStream **is** an AsyncIterable
(at least in the standard sense, see: https://tc39.es/proposal-async-iteration/#sec-asynciterable-interface) by the virtue of having a `[Symbol.asyncIterator]()` method (which is an alias of `getIterator()` for `ReadableStream`).

If so then changing the `Server` class to implement `ReadableStream` of `ServerRequest` instances seems like the most standard and browser-like way to get things like backpressure without inventing any new APIs, while still keeping the same AsyncIterable API that we have today, so for-await loops still work fine.

Has this already been considered?

**Comment by dd-pardal** [comment]
I don't think it would be a good idea. I don't think it makes sense to call the server a readable stream. From the [spec](https://streams.spec.whatwg.org/#readable-stream):
    
> A readable stream represents a source of data, from which you can read. In other words, data comes out of a readable stream.
    
Does it make sense to say data comes out of a web server/TCP listener? Maybe, but I don't think it's the best fit.

**Comment by jimmywarting** [comment]
Agree with @dd-pardal  adding streams on top will create overhead

I would like to see the `ReadableStream.from(iterable)` being implemented

then you could if you like just do: `stream = ReadableStream.from(serve({...}))`

**Comment by kitsonk** [comment]
@jimmywarting unless it gets [implemented in the standard](https://streams.spec.whatwg.org/), it won't get implemented in Deno.

**Comment by jimmywarting** [comment]
https://github.com/whatwg/streams/issues/1018
