### ISSUE TITLE
Question: using tsx / jsx

### ISSUE THREAD

**Issue by fakoua** [denoland/deno#3572]
Is there a way to use tsx with deno without the react lib?
I tried many way and test all failed, and I wasn't able to set the flag --jsx for typescript.
Thanks

**Comment by manyuanrong** [comment]
You can configure tsconfig.json to provide a jsxFactory
```json
{
  "compilerOptions": {
    "jsx": "react",
    "jsxFactory": "globalThis.jsxFactory"
  }
}
```

In your tsx file
```ts
// test.tsx

// you can provide yours
globalThis.jsxFactory = function() {};

export default (
  <div>
    <h1>JSX</h1>
    <span>Hello Deno</span>
  </div>
);
```

And run with tsconfig.json
```
deno run -c tsconfig.json test.tsx
```

**Comment by fakoua** [comment]
Many thanks, 
It works without error, but we need to implement the factory.

Thanks
