### ISSUE TITLE
How to use Koa in Deno?

### ISSUE THREAD

**Issue by pinghe** [denoland/deno#3590]
How to use Koa in Deno

**Comment by kt3k** [comment]
I think using koa in Deno is very difficult because it depends on lots of npm modules and Node APIs.

Instead, we have [oak](https://github.com/oakserver/oak) framework. It has similar APIs to koa.

**Comment by pinghe** [comment]
thanks!

**Comment by nusendra** [comment]
@pinghe use this instead

https://deno.land/x/oak
