### ISSUE TITLE
Deno.dial func can't connect socket as hostname('localhost')

### ISSUE THREAD

**Issue by magichim** [denoland/deno#3609]
Before 0.28.1 version, I use hostname('localhost') well in mysql lib.
However from now version, I can't connect and was refused. (Currently It's only possible using '127.0.0.1')

Is there plan that possible to connect as 'localhost'?

**Comment by manyuanrong** [comment]
localhost has always been a valid host name, and I tested it in v0.28.1 and found no issues. I think this might be a problem with your network, for example, it only listens on `127.0.0.1` and not `0.0.0.0`

**Comment by magichim** [comment]
@manyuanrong 
In my case, When I use deno_mysql's hostname: 'localhost', I got connect failed case.

Could you try this case?

**Comment by manyuanrong** [comment]
First you need to confirm if the connection cannot be successfully established or you receive a rejection response.
The former should use a tool like telnet to check your network. If it is the latter, there should be a problem with the mysql server authorization configuration.
I think this has nothing to do with Deno

I have tested：
```
INFO connecting localhost:3306
INFO connected to localhost
INFO close connection
running 12 tests
INFO connecting localhost:3306
INFO connected to localhost
OK     testCreateDb (4.14ms)
OK     testCreateTable (13.39ms)
```

**Comment by manyuanrong** [comment]
Still have questions? Can be closed if not
@magichim

**Comment by magichim** [comment]
@manyuanrong 
I'm sorry, I was treveling...It's too late to reply.
