### ISSUE TITLE
[feature] vm module

### ISSUE THREAD

**Issue by brandonkal** [denoland/deno#3622]
Deno provides a lot of useful objects in the runtime. It is also great to see a project that is solving many of the security problems of running JavaScript.

I'd like to lock things down even further so that I can use Deno for hermetic config generation.

Are there plans to offer something like the vm module available in node or some other way to provide a smaller environment (i.e. no Deno.pid etc etc)?

**Comment by kevinkassimo** [comment]
Worth noting we currently support Web Worker with `noDenoNamespace` option, which completely hides `window.Deno` and all privileged calls hosted under it.

**Comment by brandonkal** [comment]
Agreed that a worker-based isolation is much better than just context alone. I'm glad to see there is an option to hide the Deno namespace there.

**Comment by shivajivarma** [comment]
Hi @kevinkassimo,

Can i achieve something like below code?

```js
var vm = require('vm');
var myObj = { name: 'John', age: 38 };
vm.createContext(myObj);

vm.runInContext('age += 1;', myObj);

console.log(myObj);
```


Basically i want to capture code from end user and evaluate it inside a context. If so, can you please share sample code, it will be very helpful. Thanks.

**Comment by brandonkal** [comment]
The VM abstraction doesn't exist yet. The Worker would need to support Blob URLs so we can codegen module code. And workers would need to support limited permissions to run user code.

**Comment by lucacasonato** [comment]
Effectively a duplicate of #5683 and #4867

**Comment by brandonkal** [comment]
Not really a duplicate. Those issues are just requirements to make this possible.

**Comment by astro-nomize** [comment]
@lucacasonato Also, how is it a duplicate if those were made long after this issue?

**Comment by einicher** [comment]
Any progress on this?

**Comment by calebeaires** [comment]
Following this discussion thought all others I have noticed that none of then states when Deno VM module will be delivered or event placed at roadmap. Is there some workaround to achieve it?

**Comment by andreubotella** [comment]
There is currently a JS proposal called [`ShadowRealm`](https://github.com/tc39/proposal-shadowrealm) that will offer some of the capabilities that Node.js's `vm` module currently does, except with much better isolation guarantees. It's not clear when it will ship in Deno, since it's only just starting to be implemented in V8, but we hope to support it as soon as it ships upstream (although that will require refactoring a number of things in the Deno code base).

If there are significant gaps in the use cases of `ShadowRealm` compared to those of `vm`, once we have refactored the Deno internals to support the former, we will probably be in a much better position to tackle the latter.

**Comment by shivajivarma** [comment]
Hi everyone, 

I see `ShadowRealm` still in WIP. Any other ways to achieve this now with current state of deno? 

Any suggestion would really help.

Thanks in advance.


-- Shivaji

> Hi @kevinkassimo,
> 
> Can i achieve something like below code?
> 
> ```js
> var vm = require('vm');
> var myObj = { name: 'John', age: 38 };
> vm.createContext(myObj);
> 
> vm.runInContext('age += 1;', myObj);
> 
> console.log(myObj);
> ```
> 
> Basically i want to capture code from end user and evaluate it inside a context. If so, can you please share sample code, it will be very helpful. Thanks.

**Comment by Jobians** [comment]
No updates?
