### ISSUE TITLE
discussion: Deno.create

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#3627]
We have Deno.open, very similar to Go's os.Open. We do not have a os.Create equivalent. The easiest way to do that afaik is to call Deno.writeFile with an empty array buffer, then call os.Open. This is not great because between the Deno.writeFile and the Deno.open the file could be gone again.

I think it would be nice to have a Deno.create function which takes a filename and mode and  returns a Promise<File>. It should create a file if none exists and truncate any existing file, just like in Go.

What do you think?

Reference: https://golang.org/pkg/os/#Create

**Comment by ry** [comment]
Sure I'm for it.

> The easiest way to do that afaik is to call Deno.writeFile with an empty array buffer, then call os.Open.

Not sure what you mean by that. I think Create is just Open but using  O_RDWR|O_CREATE|O_TRUNC. See https://golang.org/src/os/file.go?s=8597:8636#L278

**Comment by lucacasonato** [comment]
> Not sure what you mean by that. I think Create is just Open but using O_RDWR|O_CREATE|O_TRUNC. See https://golang.org/src/os/file.go?s=8597:8636#L278

Your right, but I meant something else. Wanted to write "to call Deno.writeFile with an empty array buffer, then call Deno.open", as in that is the easiest way to do it in deno currently - sorry for not making that clearer.

---

I just realized tho that this might not even be needed - you can just call `Deno.open("foo", "w+")` and it will have the same behaviour as Go's os.Create. It's just not super obvious at first glance.

So `Deno.create("foo")` would just be an alias for `Deno.open("foo", "w+")`.

**Comment by lucacasonato** [comment]
Oh - we already have Deno.create but its marked as internal with `@internal` so its not part of the bundle... https://github.com/denoland/deno/blob/master/cli/js/files.ts#L227-L233
