### ISSUE TITLE
Make travis fail if ./tools/format.py changes something.

### ISSUE THREAD

**Issue by ry** [denoland/deno#363]
(Maybe by running git diff?)

**Comment by qti3e** [comment]
@ry `git diff` is not exactly what you're looking for but `git` works very well, here is script i use for this use case:
```bash
#!/bin/bash
git ls-files -m --error-unmatch . >/dev/null 2>&1; ec=$?
if test "$ec" = 0; then
  echo "Repository is dirty..."
  exit 1
fi
```

**Comment by ry** [comment]
@qti3e Works for me. It should be a single line in travis.yml, just after the lint.
