### ISSUE TITLE
Rename std/fmt and std/prettier

### ISSUE THREAD

**Issue by nayeemrmn** [denoland/deno#3639]
Suggested:
- `std/fmt/` -> `std/tty/`
- `std/fmt/sprintf.ts` -> `std/strings/sprintf.ts` (`printf` and other TODOs can go in `std/io` or wherever appropriate)
- `std/prettier/` -> `std/fmt/`
- `std/prettier/vendor/` -> `std/fmt/_prettier`

**Comment by bartlomieju** [comment]
`std/prettier` has been transferred to https://deno.land/x/prettier so no longer valid. Not sure about renaming `std/fmt/`

**Comment by kitsonk** [comment]
I'm also not sure about renaming fmt to tty either... I think fmt is appropriate.

**Comment by nayeemrmn** [comment]
What do `colors.ts` and `sprintf.ts` have to do with each other? Seems like these are very different types of formatting.
