### ISSUE TITLE
Support Brotli compression in fetch API

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#3650]
Follow-up to #3597.
 
Support for brotli compression in `fetch` API is still missing, tips for implementation can be found here:https://github.com/denoland/deno/pull/3597#issuecomment-572992184

CC @manyuanrong

**Comment by manyuanrong** [comment]
I will submit a PR on the `reqwest` to resolve it
https://github.com/seanmonstar/reqwest/issues/791

**Comment by bartlomieju** [comment]
`reqwest` has been released with Brotli support. 

https://github.com/seanmonstar/reqwest/releases/tag/v0.10.2
