### ISSUE TITLE
After 0.26.0, the program doesn't exit after calling fetch

### ISSUE THREAD

**Issue by kt3k** [denoland/deno#3656]
The following script doesn't seem exiting (after v0.26.0).
```
console.log(await fetch('https://example.com'))
```

With v0.25.0, the above script exits normally.

**Comment by bartlomieju** [comment]
> The following script doesn't seem exiting (after v0.26.0).
> 
> ```
> console.log(await fetch('https://example.com'))
> ```
> 
> With v0.25.0, the above script exits normally.

Just checked with `0.29.0` and works as expected.

**Comment by bartlomieju** [comment]
@kt3k what OS are you using?
