### ISSUE TITLE
Rename std/io/ modules

### ISSUE THREAD

**Issue by nayeemrmn** [denoland/deno#3663]
To hide package private modules, cleanup redundancy in names.

Suggested:
- `std/io/ioutil.ts` + `std/io/util.ts` -> `std/util/io.ts`
- `std/iotest.ts` -> `std/_test_util.ts`
- `std/bufio.ts` -> `std/buffers.ts`

**Comment by ry** [comment]
https://github.com/denoland/deno/pull/3673#issuecomment-574388316
