### ISSUE TITLE
Test for permissions actually required

### ISSUE THREAD

**Issue by brandonkal** [denoland/deno#3666]
Permissions are requested when a program needs it. I'd love to see the possibility to report after the program has run (probably somewhere in Deno var) a list of all permissions that were required. Then a test can assert that only certain permissions were required while still running `deno -A` in CI.

Related: #3655

**Comment by lucacasonato** [comment]
Maybe this could be added to Deno.metrics - it would report how often a certain permission was 'used' (checked) by Rust code.
