### ISSUE TITLE
`FileInfo` should include same stats as <sys/stat.h>

### ISSUE THREAD

**Issue by Alhadis** [denoland/deno#3668]
[Node](https://nodejs.org/api/fs.html#fs_class_fs_stats) and [QuickJS](https://bellard.org/quickjs/quickjs.html#os-module) both return an object representing a standard C [`stat(2)`](http://man7.org/linux/man-pages/man2/stat.2.html) `struct`:

~~~console
λ Desktop: qjs
QuickJS - Type "\h" for help
qjs > os.lstat(".")[0]
{ dev: 16777220, ino: 13535700, mode: 16832, nlink: 10, uid: 501, gid: 20, rdev: 0, size: 340, blocks: 0, atime: 1578914527000, mtime: 1578912489000, ctime: 1578914526000 }

λ Desktop: node
Welcome to Node.js v13.6.0.
Type ".help" for more information.
> fs.statSync(".")
Stats {
  dev: 16777220,
  mode: 16832,
  nlink: 10,
  uid: 501,
  gid: 20,
  rdev: 0,
  blksize: 4096,
  ino: 13535700,
  size: 340,
  blocks: 0,
  ︙
}
~~~

Deno, however, [does not](https://deno.land/typedoc/interfaces/deno.fileinfo.html#mode):

~~~console
λ Desktop: deno
> Deno.statSync(".")
FileInfoImpl { _res, _isFile, _isSymlink, len, modified, accessed, created, mode, name }
~~~

It'd be nice if Deno returned the same set of information. Also, I recommend renaming `len` to `size`, because the former name is rather confusing (not to mention inconsistent with other implementations).

**Comment by kevinkassimo** [comment]
The structure of current `FileInfo` reflects those of Rust [`Metadata`](https://doc.rust-lang.org/std/fs/struct.Metadata.html). This is the similar reason why Node or qjs reflects `struct stat` of libc.

I am not fully convinced that we should name exactly the way of `struct stat`, and I have seen a trend in Rust to ditch short libc names in favor of clearer ones. However I do think we might need to add more fields to `FileInfo` which are available on `struct stat` but not exposed in Deno so far.

**Comment by Alhadis** [comment]
> and I have seen a trend in Rust to ditch short libc names in favor of clearer ones

How is `len` clearer than `size`, though?

**Comment by kevinkassimo** [comment]
> > and I have seen a trend in Rust to ditch short libc names in favor of clearer ones
> 
> How is `len` clearer than `size`, though?

I did not imply `size`. I mean things like `rdev`.

**Comment by Alhadis** [comment]
Irrespective of name choices, the same filesystem information should be available in some form or another. A library can smooth out discrepancies between Deno and other implementions (like a function that "`stat`-ifies" Deno's `FileInfo` objects).

**Comment by kevinkassimo** [comment]
> Irrespective of name choices, the same filesystem information should be available in some form or another. A library can smooth out discrepancies between Deno and other implementions (like a function that "`stat`-ifies" Deno's `FileInfo` objects).

Fully agree on this.
