### ISSUE TITLE
Transpile JS Compiler Flag

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#3672]
While we have been working on more feature rich Node.js compatability, like all the built in modules and a fuller featured `require()`.  One of the common use cases is just simple conversion from CommonJS to ESM.

This is something that Deno supports, but the ability to get access to it is a bit complicated.  You have to use a `tsconfig.json` on the command line with the `"checkJs": true` compiler option set.  This also causes some side effects, because a lot of CommonJS modules aren't type safe, and then you get all sorts of random errors that aren't useful.

With the implementation of the userland `Deno.transpileOnly()` API, which accepts all sorts of stuff and outputs JS ESM, we don't quite have the equivilant on the command line.

I think it would make sense to have a flag, which would do a transpile only on JS modules, but a full compile on TS modules without the need of a `tsconfig.json`.  This would mean that we would be able to consume CommonJS JS modules and cache the results while throwing "caution to the wind" as far as ensuring the type safety of the files.  This means a whole eco-system of CommonJS modules could be supported in the runtime.  It also would mean that AMD JS modules would be consumable as well.

The biggest risks I would see is that it wouldn't be a magic wand, though end users might think it is.  For example if there is a dependency on a built in module in Node.js somewhere in the dependency chain. No good.  Also it wouldn't solve resolving other modules, where the specifier needs to be modified in order to resolve to a resource, which would be very common.  We don't want to go down the rabbit hole of magical module resolution.  The only thing we could possibly do is adjust the things that look like an extension-less specifier on transpile to a extensioned specifier.

**Comment by bartlomieju** [comment]
@kitsonk do you still want to pursue this issue?

**Comment by kitsonk** [comment]
I think we can leave it for now and see if a compelling use case re-emerges.
