### ISSUE TITLE
Deprecate and remove Deno.core.print

### ISSUE THREAD

**Issue by kevinkassimo** [denoland/deno#3676]
It seems to me that there is not really a strong reason to keep `Deno.core.print()` available. Instead prints should be done through `Deno.stdout` and `Deno.stderr`.

**Comment by ry** [comment]
Deno.core.print is a blocking print - which is pretty useful for debugging. Deno.stdout is non-blocking. I think we need to keep the blocking version for sanity. I'd be open to renaming it to Deno.printSync or something more obvious.

**Comment by bartlomieju** [comment]
Keep in mind that `Deno.core.print` is the only API available outside of `cli/` that allows to output to stdout/stderr. 

`console.log` implementation in `cli/` uses `Deno.core.print` underneath anyway.

**Comment by kitsonk** [comment]
Should `Deno.stderr` and `Deno.stderr` take an optional blocking parameter?

**Comment by echd** [comment]
As someone who writes command-line utility scripts in other languages and is evaluating Deno for that purpose, having a simple-to-use print function is both useful and follows prior art. All of the following languages have some variant of it: awk, bash, C, Go, Java, Perl, Python, Ruby, Rust and Tcl.

The `write()` function on `Deno.stdout` and `Deno.stderr` isn't quite as nice as what those other languages provide.

I think having such a function be public and visible in the documentation would make it easier to onboard folks like me who are coming from other languages and don't know about the JavaScript-specific `console.log()` function.

**Comment by bartlomieju** [comment]
Usage of `Deno.core.print()` is prevalent and it's the only debugging utility provided by `core/`. It's unlikely we'll remove it.
