### ISSUE TITLE
Need to exit the program even when certain async ops are still reamianing

### ISSUE THREAD

**Issue by kt3k** [denoland/deno#3694]
Deno now doesn't exit when it has unfinished async ops. However I think that's inconvenient (or inappropriate) for certain types of ops.

For example, in #3610, I want the program to exit even when the user is still listening to the signals, but that's impossible to implement with the current core structure because when the user is listening to signals, there're async ops remaining and that blocks the program to exit.

I suggest we should enhance deno_core::Op::Async struct to have the additional flag for expressing whether it blocks the program to exit or not, and make it possbile to choose to block or not for each op.

**Comment by kevinkassimo** [comment]
I think this goes back to the thing I did back in #2735 (`AsyncOptional`). TBH I still do not fully understand why the solution was considered a non-option...

**Comment by bartlomieju** [comment]
Closed in #3721
