### ISSUE TITLE
Inconsistency between types and code in new Compiler API

### ISSUE THREAD

**Issue by flachen** [denoland/deno#3702]
While testing out the new Compiler API https://github.com/denoland/deno/pull/3442 i ran into some inconsistency between the typings and the returned data for diagnostics.

`Deno.compile` is defined type wise to return `Diagnostic[]`(https://github.com/denoland/deno/blob/master/cli/js/compiler_api.ts#L331), but code implemented returns `DiagnosticItem[]` (https://github.com/denoland/deno/blob/master/cli/js/compiler.ts#L245)

**Comment by nayeemrmn** [comment]
Ref 3624. Technically not duplicate, looks like it's not just bundle.

cc @kitsonk
