### ISSUE TITLE
request.respond() should close Reader, if applicable

### ISSUE THREAD

**Issue by sholladay** [denoland/deno#3713]
Deno's `request.respond()` handles [`Reader`](https://deno.land/typedoc/interfaces/deno.reader.html) instances automatically, which makes streaming a file to the browser very convenient. This is awesome! However, the program below leaks resources because `file.close()` is never called.

```js
import { serve } from "https://deno.land/std@v0.30.0/http/server.ts";
const server = serve({ port: 3000 });
const handleRequest = async (request) => {
    const file = await Deno.open('./cat.jpg');
    request.respond({ body : file });
};
for await (const request of server) {
    handleRequest(request);
}
```

I propose that If the [`Reader`](https://deno.land/typedoc/interfaces/deno.reader.html) is also a [`Closer`](https://deno.land/typedoc/interfaces/deno.closer.html) (as is the case for [`File`](https://deno.land/typedoc/classes/deno.file.html)), then its `.close()` method should be called.

**Comment by kevinkassimo** [comment]
I am not quite sure if this is a good idea though, since it might be reasonable to simply keep the file open and seek to the beginning, and reuse the same descriptor.

Instead I think we can probably introduce another independent API `request.sendFile` or similar that opens the file internally and deals with closing automatically.

**Comment by sholladay** [comment]
That argument makes some sense to me. I would be happy with that solution. I do wonder, though, whether there is a simpler way to support that use case and mine at the same time.

Is there a concept of a [passthrough stream](https://nodejs.org/api/stream.html#stream_class_stream_passthrough) in Deno? If so, an implementation that wants to reuse a file descriptor could simply pipe its data to `request.respond()` vis a passthrough stream, in effect "hiding" the file descriptor so it doesn't get closed.

While it might be slightly less straightforward, having an API for passthrough streams seems more generically useful and interesting than `request.sendFile()`.
