### ISSUE TITLE
Support other libs in runtime compiler API 

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#3726]
Currently the runtime API would support the compiler option of `lib`, but it would fail in most scenarios where if a lib is included that isn't inlined into the TypeScript compiler.  For example `lib: [ "esnext", "dom" ]` would fail, because `lib.dom.d.ts` is not inlined into the compiler.

We should support attempting to externally fetch libs when requested by the runtime compiler APIs, so we don't have to bake these in, but end users would be able to compile against a different set of libs.

**Comment by PandawanFr** [comment]
As I mentioned in #3799, you can use [the triple slash directive](https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html) to reference libraries in a specific file.
```ts
/// <reference lib="https://raw.githubusercontent.com/microsoft/TypeScript/master/lib/lib.dom.d.ts" />
```
But perhaps allowing for simply `lib="dom"` like regular typescript would be nice.

In addition, some kind of option in the Deno.compile/bundle functions would be good (so that you don't have to reference the lib in every file).

**Comment by kitsonk** [comment]
Yeah, I think this should be pretty straight forward, and would allow `/// <reference lib="dom" />` to work as well.  I was going to work on something else next, but given there is demand for it from folks, I will start working on this now.

**Comment by cretz** [comment]
@kitsonk - Awesome! Ideally this work could also help #2633 where an embedder can programmatically determine which libs to include also.

**Comment by cztomsik** [comment]
FYI `/// <reference lib="dom" />` doesn't work, it has lots of conflicts with existing deno types.

**Comment by cj1128** [comment]
Any updates? 

I got a lot of ts errors when I used `@deno-types` to include type definitions for the [ky](https://github.com/sindresorhus/ky) libarry.

```
// @deno-types="https://deno.land/x/ky@v0.23.0/index.d.ts"
export { default as ky } from "https://deno.land/x/ky@v0.23.0/index.js
```

From the error message, it is the `lib.dom.d.ts` which causes conflicts with other definitions.

```
TS2300 [ERROR]: Duplicate identifier 'Event'.
declare class Event {
              ~~~~~
    at asset:///lib.deno.web.d.ts:21:15

    'Event' was also declared here.
    interface Event {
              ~~~~~
        at asset:///lib.dom.d.ts:5285:11    and here.
    declare var Event: {
                ~~~~~
        at asset:///lib.dom.d.ts:5353:13
...
```
