### ISSUE TITLE
treat warnings as errors

### ISSUE THREAD

**Issue by ry** [denoland/deno#374]
https://github.com/ry/deno/blob/ed9acaec7d438515271c1f2664780c0612f339da/.gn#L28
The task is to delete this line and deal with all the warnings that cause the build to fail. [There are a handful.](https://travis-ci.com/ry/deno/builds/79153409) Bonus points if you make rustc warnings also obey the `treat_warnings_as_errors` gn arg.

**Comment by robbym** [comment]
Just need to add `-Dwarnings` to rustc args. Not familiar enough with gn to do this. Something like this in rust.gni?
```gn
    if (defined(treat_warnings_as_errors) && treat_warnings_as_errors) {
      args += ["-Dwarnings"]
    }
```
Doesn't seem to work though.

**Comment by ry** [comment]
This was accidentally closed. We will have a number of warnings popping up.

#536 significantly reduces the number of rust warnings

**Comment by ry** [comment]
OSX and Linux builds are warning free now.

**Comment by ry** [comment]
Rust warnings have been made errors in 850fca8fcbad839c5b8a052517acee95851df321

Just need to deal with clang errors now.
