### ISSUE TITLE
Unable to run example provided in deno.land

### ISSUE THREAD

**Issue by aphsa** [denoland/deno#3745]
$ cat deno_server.ts
import { serve } from "https://deno.land/std@v0.30.0/http/server.ts";
const s = serve({ port: 8000 });
console.log("http://localhost:8000/");
for await (const req of s) {
  req.respond({ body: "Hello World\n" });
}

$ deno ./deno_server.ts
error: Uncaught PermissionDenied: run again with the --allow-net flag
► $deno$/dispatch_json.ts:40:11
    at DenoError ($deno$/errors.ts:20:5)
    at unwrapResponse ($deno$/dispatch_json.ts:40:11)
    at sendSync ($deno$/dispatch_json.ts:67:10)
    at listen ($deno$/net.ts:179:15)
    at serve (server.ts:492:20)
    at deno_server.ts:2:11

**Comment by trivikr** [comment]
Working as designed.

For security reasons, Deno does not allow programs to access the network without explicit permission. To allow accessing the network, use a command-line flag:
Documentation https://deno.land/std/manual.md#tcp-echo-server
