### ISSUE TITLE
Changes to API in `deno_core` crate causes `test_publish` to fail

### ISSUE THREAD

**Issue by afinch7** [denoland/deno#3749]
My PR #3637 fails `test_publish`, since the published version of `deno_core`(0.30.1) doesn't contain the changes to the API I made. In publish dry runs it builds from published versions of other crates in our repo. I.E. publishing `deno_typescript` uses the published version of `deno_core` found on crates.io not the version in the local repository. Unfortunately the only fix right now is to disable `test_publish`.

**Comment by ry** [comment]
see https://github.com/denoland/deno/pull/3750

**Comment by bartlomieju** [comment]
Fixed
