### ISSUE TITLE
Use filesystem-rs for all fs access in Rust

### ISSUE THREAD

**Issue by ry** [denoland/deno#375]
In Go, there is a very nice library, https://github.com/spf13/afero, that provides an abstraction layer for file system methods. The prototype of Deno used it to provide file system security:
https://github.com/ry/deno/blob/559453cf6cc88283bcf8fdeccd387458f5c63165/os.go#L20-L28

https://github.com/iredelmeier/filesystem-rs looks promising.
https://github.com/iredelmeier/filesystem-rs/blob/master/tests/fs.rs tests are robust. I think this will work as a replacement for afero.

All calls into the filesystem (std::io functions) should be replace with calls into filesystem-rs. For example: https://github.com/denoland/deno/blob/67d89ff692a88ae42145043eac1a5c58413ae110/src/fs.rs#L6-L12

This work should wait for #529 and #527 to land.

**Comment by sijad** [comment]
seems `filesystem-rs` needs a wrapper for security (disable non-readable operations).

**Comment by ry** [comment]
@sijad Yes - thanks - that looks good but it would be better if permission denied checked `deno.flags.allow_write` for every operation so that we have the possibility of changing permissions during runtime.

**Comment by sijad** [comment]
I was thinking about making a new crate (`safe-filesystem-rs`), it's what I think should be done:

1. create a new crate `safe-filesystem-rs`
2. add tests from `filesystem-rs` (to make sure everything works as before)
3. add new tests for readonly fs

do you think it's good idea?

**Comment by ry** [comment]
@sijad I'm glad you're interested. I'm in the process of making major refactors to handlers - I want to put off filesystem-rs migration until that's settled. They're orthogonal problems, but it just becomes difficult when too much stuff is changing. I'll ping you on this thread when it's ready for that.

As for safe-filesystem-rs - I'd rather not have an external crate that we'll probably have to change often. Do this inside src/... but let's wait a few days.
