### ISSUE TITLE
Issue with Deno bundle

### ISSUE THREAD

**Issue by fakoua** [denoland/deno#3751]
Consider the follow code:

```ts
//Cl1.ts
export const fn1 = function() {
    console.log("this is fn1");
}

export abstract class Cl1 {
    static fn2() {
        console.log("Cl1.fn2")
    }
}
```

Without bundle, fn1 and Cl1 are exported, however when I use the bundle cli or Deno.bundle, I can't access the Cl1 anymore:

```ts
import { Cl1, fn1} from "./Cl1_bundle.ts" //Cl1 gives error.
```

Please advice.
Thanks

**Comment by kitsonk** [comment]
Likely, the AST node of an abstract class does not look like an exportable node (because `abstract` is a type only concept, so we incorrectly expect no runtime emit), and we need to adjust the export detection criteria.
