### ISSUE TITLE
deno.exe - Application Error: The application was unable to start correctly (0xc000007b)

### ISSUE THREAD

**Issue by Qws** [denoland/deno#3754]
Installed deno.exe through Powershell and Windows Bash. The installation is successful but Deno doesn't work on my Windows 10 laptop.

Windows pop-up error message when I try to use deno command on CMD: 
```
deno.exe - Application Error
The application was unable to start correctly (0xc000007b). 
Click OK to close the application.
```
Image:
![afbeelding](https://user-images.githubusercontent.com/3944421/72942497-e920dd80-3d73-11ea-945b-2a279eb9435a.png)

I tried few things in PowerShell but nothing seems to work:

![afbeelding](https://user-images.githubusercontent.com/3944421/72943112-74e73980-3d75-11ea-9910-3ac642d8e4b2.png)

```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\deno> iwr https://deno.land/x/install/install.ps1 -useb | iex
Deno was installed successfully to C:\Users\deno\.deno\bin\deno.exe
Run 'deno --help' to get started
PS C:\Users\deno> deno --help
PS C:\Users\deno> deno https://deno.land/std/examples/welcome.ts
PS C:\Users\deno> Set-ExecutionPolicy RemoteSigned -Scope CurrentUser -Force
PS C:\Users\deno> iwr https://deno.land/x/install/install.ps1 -useb | iex
Deno was installed successfully to C:\Users\deno\.deno\bin\deno.exe
Run 'deno --help' to get started
PS C:\Users\deno> deno https://deno.land/std/examples/welcome.ts
PS C:\Users\deno> Set-ExecutionPolicy RemoteSigned -Scope CurrentUser -Force
```

As you can see:

 `deno --help` gives me nothing.
`deno https://deno.land/std/examples/welcome.ts` gives me nothing.

I tried using `Set-ExecutionPolicy RemoteSigned -Scope CurrentUser -Force` for Powershell, sadly no improvements. Also tried to install Deno with Bash for Windows. No changes...

I checked if deno.exe is located in the `.deno/bin` folder, and yes it is:
```
PS C:\Users\deno> cd .\.deno\bin\
PS C:\Users\deno\.deno\bin> ls

Directory: C:\Users\deno\.deno\bin

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        1/18/2020   1:40 PM       43868672 deno.exe
```

I wonder if this problem is because my Windows username? Which is also Deno...

**Comment by nayeemrmn** [comment]
Is your antivirus blocking and inspecting it?

**Comment by Qws** [comment]
I have only `Windows Security`:

![afbeelding](https://user-images.githubusercontent.com/3944421/72944068-25eed380-3d78-11ea-801b-d79a6ff96d71.png)

**Comment by Qws** [comment]
Oke.. I don't have this issue on my desktop, which has also Windows username "deno"

**Comment by bartlomieju** [comment]
Closing as stale, feel free to reopen if problem persists
