### ISSUE TITLE
flag parsing

### ISSUE THREAD

**Issue by ry** [denoland/deno#376]
1. Add most minimal flag parsing crate to `gclient_config.py`
1. Add flag parsing crate build parameters to `build_extra/rust/BUILD.gn`
1. Make `main()` return the V8 version on `deno --version` and `deno -v`. 
1. Allow for future flag parsing to happen in `js/main.ts` by calling `deno_set_flags()` after you've manipulated them.
1. set the max_log_level when `deno --debug testdata/001_hello.js` is run.

Start at branch code_fetch3 #371

**Comment by mreinstein** [comment]
I'll take a stab at this

**Comment by mreinstein** [comment]
a bit dated but maybe we could use one of the existing js argument parsers and add typescript. I like substack's stuff a lot, tight little modules that are pretty much done. minimist perhaps?

https://github.com/substack/minimist

**Comment by kitsonk** [comment]
I have always used [yargs](https://github.com/yargs/yargs) but it isn't minimalist and it isn't written in TypeScript, though the `@types` support is decent.

Of course the most TypeScripty command line parsers would be the [one in the compiler](https://github.com/Microsoft/TypeScript/blob/9706f1729e9c41c9af901c279367dec0ab1093d1/src/compiler/commandLineParser.ts#L852).  While it is hardwired for `tsc` it is a decent pattern.

I haven't used this, but if you want minimalist and TypeScript, [argumenty](https://www.npmjs.com/package/argumenty) fits the bill.

**Comment by ry** [comment]
Excellent. If the code's already there then let's use https://github.com/Microsoft/TypeScript/blob/9706f1729e9c41c9af901c279367dec0ab1093d1/src/compiler/commandLineParser.ts#L852

**Comment by ry** [comment]
I attempted to do flag parsing in JS - but I decided to back out of it https://github.com/denoland/deno/pull/441
Waiting on flatbuffer rust support to do proper communication of post-parsed argv
