### ISSUE TITLE
docs: Mime example

### ISSUE THREAD

**Issue by base698** [denoland/deno#3763]
Been trudging through a workflow of trying random things on a `ServerRequest` and reading code here: https://github.com/denoland/deno/tree/master/std/mime 

Would be nice to have a working example of getting a multipart file uploaded with curl in the server section.  I successfully copied the request to a file in one of my random guesses and it still had the boundaries and headers so alas, was corrupted.

Example of getting the bytes from the request, but it has the headers:
`console.log(decoder.decode(await Deno.readAll(body)));`

**Comment by artisonian** [comment]
Here's an example:

https://gist.github.com/artisonian/8297e5fe95f448ca98045f336bccf976

```sh
curl -F attachment=@someFile.txt "http://localhost:1447/upload"
```

**Comment by lucacasonato** [comment]
std/mime was removed and is now located at https://github.com/oakserver/media_types. This is not relevant anymore I think.
