### ISSUE TITLE
allow to override OBJ_ABBREVIATE_SIZE for object stringification (used by Deno.inspect and console.log)

### ISSUE THREAD

**Issue by kigiri** [denoland/deno#3766]
At the moment deno automatically decide to "abbreviate" *(only display keys)* of objects of more than 5 keys and ignore `opts.depth` parameters.

It is often useful to be able to see more than just the keys of even relatively big objects.

`JSON.stringify` is not that usefull when dealing with circular objects and non basic types.

I found that having a basic colorization of the output usefull for quick scaning the shape of my objects.

I would like to make using `Deno` more pleasing and work on this feature, for now if I would like to be able bypass `OBJ_ABBREVIATE_SIZE` and maybe start working on multi-line stringification of objects.

For now I've only seen this comment:
```js
  /** UNSTABLE: ConsoleOptions rename to InspectOptions. Also the exact form of
   * string output subject to change.
   *
   * `inspect()` converts input into string that has the same format
   * as printed by `console.log(...)`;
   */
```
Mentioning that the output is subject to change, from what I could tel reading the source, only the `depth` property is used in the code.

I went to read a bit what node is doing, it does a lot, too much in my opinion, I don't feel that we need to be that "smart" about printing at this point but this is what I offer to work on:

- [ ] option to override `OBJ_ABBREVIATE_SIZE`
- [ ] option to allow multi-lines output
- [ ] `breakLength` option to wrap output
- [ ] `collectionMaxLength` option to only display the first `x` elements of collections
- [ ] colors for primitive types, could match node default style:
	```js
	  special: 'cyan',
	  number: 'yellow',
	  bigint: 'yellow',
	  boolean: 'yellow',
	  undefined: 'grey',
	  null: 'bold',
	  string: 'green',
	  symbol: 'green',
	  date: 'magenta',
	  // "name": intentionally not styling
	  regexp: 'red',
	  module: 'underline'
	```

Any indication on what should I prioritize / avoid, where would you rather see the work start ?

---
Declaration of `OBJ_ABBREVIATE_SIZE`: https://github.com/denoland/deno/blob/702ff4283f06c83e5b68affdf39e7000eb91054c/cli/js/console.ts#L21

Declaration of `ConsoleOptions`: https://github.com/denoland/deno/blob/702ff4283f06c83e5b68affdf39e7000eb91054c/cli/js/console.ts#L9

Re-Declaration of `ConsoleOptions`: https://github.com/denoland/deno/blob/5e2fd183ff1fe240ddbd864dbf1e6a0941fb4582/cli/js/lib.deno_runtime.d.ts#L1675

**Comment by nayeemrmn** [comment]
This may be superseded #3165.

**Comment by kigiri** [comment]
Ah yes, I somehow failed to see this issue.
Closing in favor of #3165 thanks @nayeemrmn
