### ISSUE TITLE
Multiple Signal Handler

### ISSUE THREAD

**Issue by kt3k** [denoland/deno#3773]
PR #3757 tries to add the signal handler function `Deno.signal(signo)`. This only handles one kind of signals for each `Deno.signal` call.

If we add an API which handles multiple kinds of signals at once, what is the interface of that function? Where it belongs?

#### Option 1: Enhance Deno.signal()

Deno.signal takes multiple signals.

```ts
const sig = Deno.signal(Deno.Signal.SIGTERM, Deno.Signal.SIGINT);

for await (_ of sig) {
  console.log("SIGTERM or SIGINT received");
}
```

#### Option 2: Have a function for it in deno_std
```ts
import { signal } from "https://deno.land/std/signal/mod.ts";

const sig = signal(Deno.Signal.SIGTERM, Deno.Signal.SIGINT)

for await (_ of sig) {
  console.log("SIGTERM or SIGINT received");
}
```

#### Other: Please write in the comment

cc @axetroy

**Comment by axetroy** [comment]
I think the first option is better

If PR #3757 land.

Then only supports one signal, but it can be extended later to support multiple signals without BREAKING CHANGE.

**Comment by kevinkassimo** [comment]
I feel it is more of a general utility: combine and iterate 2 independent async iterators. It does not really need to be functionality built into just signal handlers.

We can implement this as a new util in std
