### ISSUE TITLE
Configuration file and module system

### ISSUE THREAD

**Issue by FedericoMorrone** [denoland/deno#3777]
Having a configuration file and polished module system, like having a deno init command that creates a configuration file 
For example, running
```shell
deno init awesome-project
```
would generate the following config.json
```json
{
    "name": "beatiful-project",
    "main": "index.ts",
    "dependencies": {}
}
```
This would enable to configure the workspace maybe with some flags option
```json
{
    "name": "beatiful-project",
    "main": "index.ts",
    "flags": "--allow-net",
    "dependencies": {}
}
```
Also this would enable adding depencies kinda the nodejs way while still adding them globally and also generate a lock file for added security
For example, runnning:
```shell
dino fetch dirname
```
would result in
```json
{
    "name": "beatiful-project",
    "main": "index.ts",
    "flags": "--allow-net",
    "dependencies": {
      "dirname": "https://deno.land/x/dirname/mod.ts"
    }
}
```
and generate a deno.lock file like so
```
dirname@1.0.0:
  version "1.0.0"
  resolved "https://deno.land/x/dirname/mod.ts"
  integrity "some integrity check"
  dependencies:
     some-depency@0.3.2
     other-depency@2.3.0
```
This is just my suggestion, maybe the configuration could be in xml the point is that a good module system would be very helpful and also help offline development
Maybe running
```shell
deno fetch
```
will install all needed dependencies

**Comment by yardenshoham** [comment]
So a `package.json`?

**Comment by ry** [comment]
IMHO "init" programs are anti-patterns. It's a poor way to abstract complexity. The boilerplate is too complex, so just have a program generate it for you. That might be an ok solution when you have no control over the system you're "initializing" but in Deno we do. Instead of generating boilerplate, I want to eliminate the boilerplate. Therefore there will not be a "deno init".
