### ISSUE TITLE
dependency graph broken

### ISSUE THREAD

**Issue by ry** [denoland/deno#3786]
```
> deno -V
deno 0.31.0
> deno info https://deno.land/std/http/file_server.ts
local: /Users/rld/Library/Caches/deno/deps/https/deno.land/std/http/file_server.ts
type: TypeScript
compiled: /Users/rld/Library/Caches/deno/gen/https/deno.land/std/http/file_server.ts.js
map: /Users/rld/Library/Caches/deno/gen/https/deno.land/std/http/file_server.ts.js.map
deps: cannot retrieve full dependency graph
```

**Comment by kitsonk** [comment]
Hmmm... surprised we don't have a test for that. :confused:

**Comment by bartlomieju** [comment]
Actually we have two integration tests for that command, both of them passed...

**Comment by bartlomieju** [comment]
Okay so it's caused by the fact that `Deps` get unresolved specifiers for child imports. Partially because some APIs in `core/modules.rs` take specifier argument that is of type `&str` instead of `ModuleSpecifier` - otherwise it would have been caught. I'll fix it.
