### ISSUE TITLE
Install command wrapper passes spurious "--" option to executable

### ISSUE THREAD

**Issue by srackham** [denoland/deno#3795]
Deno 0.31.0, Ubuntu 18.04, bash shell.

Wrapper scripts created by the Deno install command (`deno install [EXE_NAME] [URL] [FLAGS...]`) insert a spurious "--" argument after the `URL` instead of before it so the first command argument passed to the executable is always "--" e.g.

    "deno" "run" "--allow-read" "https://deno.land/std/examples/cat.ts" "--" "$@"

should be:

    "deno" "run" "--allow-read" "--" "https://deno.land/std/examples/cat.ts" "$@"

Demonstration using Deno's `cat` example:

```
$ echo foobar > test-file

$ deno --allow-read https://deno.land/std/examples/cat.ts test-file
foobar

$ deno install deno_cat https://deno.land/std/examples/cat.ts --allow-read
no dir
Download https://deno.land/std/examples/cat.ts
Compile https://deno.land/std/examples/cat.ts
✅ Successfully installed deno_cat
/home/srackham/.deno/bin/deno_cat

$ deno_cat test-file
error: Uncaught NotFound: No such file or directory (os error 2)
► $deno$/dispatch_json.ts:40:11
    at DenoError ($deno$/errors.ts:20:5)
    at unwrapResponse ($deno$/dispatch_json.ts:40:11)
    at sendAsync ($deno$/dispatch_json.ts:91:10)
```

Note that executables using Deno's flags module to process arguments don't have the problem because parse() processes the `--` option e.g.  https://deno.land/std/examples/catj.ts

**Comment by kevinkassimo** [comment]
This is due to https://github.com/denoland/deno/pull/3681 , unfortunately we are having some minor issues and debate over how to do user flag processing...

**Comment by srackham** [comment]
A workaround is simply to ignore any "--" options in CLI apps.

**Comment by nayeemrmn** [comment]
This can be closed. (It was an issue because the flag parsing was updated before the internal URL to `std/installer/mod.ts` was updated. Those days are gone.)
