### ISSUE TITLE
Should "dom" lib be added to the default tsonfig?

### ISSUE THREAD

**Issue by Dan503** [denoland/deno#3799]
After watching some conference talks on YouTube I thought I would try giving it a go.

I ran into this issue though when playing around with it:
https://github.com/denoland/deno/issues/3793#issuecomment-578533918

One of the core tenants of Deno is that Deno should be browser compatible:
https://youtu.be/z6JRlx5NC9E (11:55)

Currently by default the tsconfig will cause errors to be thrown if you use variables like `document` and `window`.

If being browser compatible is one of Deno's core tenants though, shouldn't it have the `"dom"` lib active in it's default tsconfig?

**Comment by ry** [comment]
Yea makes sense to me.

**Comment by nayeemrmn** [comment]
This is the reverse of what we mean by browser compatibility. Deno doesn't have a `document` and it compiles stuff it's supposed to be able to run.

Maybe you just meant the tsconfig used for `deno bundle`? See https://github.com/denoland/deno/issues/3793#issuecomment-578550811.

**Comment by Dan503** [comment]
> Maybe you just meant the tsconfig used for deno bundle?

That was what essentially inspired this issue. If I run `deno bundle` I believe it should be able bundle browser based code.

**Comment by Dan503** [comment]
If I use the `Deno.bundle()` API in a file that is run using `deno run` then that should be able to understand browser based code as well by default.

**Comment by PandawanFr** [comment]
As a temporary fix, I found that appending this at the top of the file works (though VSCode/non-deno-typescript will throw errors).
```ts
/// <reference lib="https://raw.githubusercontent.com/microsoft/TypeScript/master/lib/lib.dom.d.ts" />
```

**Comment by kitsonk** [comment]
@ry, no I would rather deliver #3726 and only have these apply to the runtime compiler APIs... Allowing other libs through that Deno doesn't support itself and typechecking against it erodes the value of TypeScript build into Deno IMO.

**Comment by ry** [comment]
@kitsonk You make a good point that Deno shouldn't accept code that it can't run. I retract my "makes sense" comment above. I think we all agree that we need to make a non-buggy workflow for users to have DOM APIs in their isomorphic apps.

@PandawanFr I actually think that solution is pretty cool....

**Comment by Dan503** [comment]
Ok so the answer to the question is:

No, Deno doesn't have a DOM so the DOM lib shouldn't be applied by default.

**Comment by kitsonk** [comment]
@Dan503, yes, but we should have a way to support including it in some fashion.  As mentioned in #3726, I am starting working on a solution.

**Comment by Dan503** [comment]
So does that mean this issue should be reopened?

**Comment by kitsonk** [comment]
No, as we don't want it to be defaulted to be on.  Closing #3726 should meet everyones use case in a way that is supportable the long term.

**Comment by jimboyeah** [comment]
> As a temporary fix, I found that appending this at the top of the file works (though VSCode/non-deno-typescript will throw errors).
> 
> ```ts
> /// <reference lib="https://raw.githubusercontent.com/microsoft/TypeScript/master/lib/lib.dom.d.ts" />
> ```

if that works, and also done this

https://raw.githubusercontent.com/denoland/deno/main/cli/dts/lib.dom.d.ts
