### ISSUE TITLE
No way to tell what your current installed script commands are or edit them

### ISSUE THREAD

**Issue by Dan503** [denoland/deno#3800]
One of Denos features is to define script aliases using the `deno install` command. 

For example

```
deno install start run deno-start.ts
```

And now you can run

```
deno start
```

This is great but the problem is that I don't think these aliases are able to be tracked.

You have to remember all the aliases you have set up. If you come back to an old project after 6 months, there is no way you will be able to remember all your old aliases for the project.

When you create an alias for the first time in a project, I think a `deno-scripts.json` file should be created at the root of the project. I imagine it should have this sort of format:

```json
{
    "alias-name" : "deno run full-command.ts --allow-net"
}
```
This gives you a reference point that holds all your script aliases so that you can come back and remind yourself what they were.

Manually editing this file should also be a method for adding/editing existing aliases.

Another benefit to this is that you can bring your aliases with you from project to project by just copying the file across.

At the moment, the `deno install` command is inferior to nodes "scripts" setting in package.json.

**Comment by nayeemrmn** [comment]
Hmm, that's not what `deno install` does. Have you checked that those commands work?
`deno install exe path/to/script.ts` in general creates an "executable" `exe` in `~/.deno/bin` (this should be in your path) so you can run the command `exe` and it would do as `deno run path/to/script.ts`. It's mostly meant for installing remote utilities as shown in the examples -- in which case it's more clearly comparable to `npm install -g`.

Let's say we did have a `deno alias` which did this. One of Deno's goals is to avoid config/boilerplate like that, so instead we'd look for a way to express those script declarations in code form and make it a userland convention. This is a minor issue. See https://github.com/denoland/deno/issues/2584#issuecomment-550473018.

**Comment by Dan503** [comment]
Sorry, I was confused about what install actually does based on what I saw on YouTube.

It looks like the register functionality in the comment you linked essentially solves the problem of wanting something akin to npm scripts.
