### ISSUE TITLE
std benchmarks should be able to return results to caller

### ISSUE THREAD

**Issue by dyedgreen** [denoland/deno#3801]
It would be useful, if the benchmark runner in the standard library could somehow return the benchmark results to the caller. This might e.g. be useful if you want to record previous benchmark results during CI.

**Comment by bartlomieju** [comment]
`std/bench` can return results:
https://github.com/denoland/deno/blob/b8872cd303584b28c0d6250184e4a1205bf2ad9b/std/testing/bench.ts#L180-L189

Closing as resolved
