### ISSUE TITLE
Should `deno bundle` be renamed?

### ISSUE THREAD

**Issue by Dan503** [denoland/deno#3807]
> > Everyone coming to Deno will think of this command in that way anyway
>
> Naming things is hard and everyone is a highly subjective term. This is what documentation is for.
>
> https://github.com/denoland/deno/issues/2475#issuecomment-533930372

While Deno is still in version 0.x, a name change away from `deno bundle` is still an option.

The word "bundle" is extremely loaded with developer expectation. Most developers will expect `deno bundle` to basically be an in-built version of Roll-Up.

You seem to be strongly opposed to the idea of `deno bundle` being used as a general purpose bundling service. Maybe it should not be called "bundle" then to help avoid developer confusion?

I was thinking maybe `deno package` would possibly be a better name.

**Comment by Dan503** [comment]
If the `Deno.bundle()` runtime API isn't intended to be a general purpose bundling service then that should maybe be renamed as well.

**Comment by ry** [comment]
> You seem to be strongly opposed to the idea of deno bundle being used as a general purpose bundling service.

General purpose is the intention. We don't have the infrastructure for a lot of it right now, like minification and tree shaking (so they can't easily be done) but maybe some day we will. I think the name is fine.

**Comment by Dan503** [comment]
Ok, if the intention is to have `bundle` be a general purpose bundling service at some point in the future then it is best to keep the name as is.
