### ISSUE TITLE
Dynamic import error has no stack trace

### ISSUE THREAD

**Issue by chris-carrington** [denoland/deno#3813]
Hi deno team! Amazing + inspirational product! Thank you all for creating + maintaining this beauty!

I run my program `deno --allow-net app.js`

And get this error `error: Uncaught TypeError: run again with the --allow-read flag`

Is there anyway to know **who's** reading, aka: what file + line in my code base is attempting to read. And/or **what's** trying to be read, aka: this directory or file. 

Knowing this will help me determine if or how I'd like to grant `allow-read` access!

Thank you!

**Comment by bartlomieju** [comment]
Hey @chris-carrington, thanks for opening the issue. Just yesterday we landed a patch that improves DX in this situation: https://github.com/denoland/deno/pull/3808

It will be included in the next release. Let me know if this solves your issue

**Comment by nayeemrmn** [comment]
@chris-carrington Are you not getting an error stack below that line? What does it say exactly?

**Comment by chris-carrington** [comment]
Holy smokes y'all are fast! Much respect thank you @bartlomieju & @nayeemrmn!

Very excited to hear about this patch @bartlomieju!

All I'm seeing today is a one line error @nayeemrmn!

```
Chriss-MacBook-Pro-2:deno cc$ deno --version
deno 0.31.0
v8 8.1.108
typescript 3.7.2
Chriss-MacBook-Pro-2:deno cc$ deno --allow-net app.js
deno oak app running @ http://localhost:4000 🚀
error: Uncaught TypeError: run again with the --allow-read flag
Chriss-MacBook-Pro-2:deno cc$

**Comment by bartlomieju** [comment]
@chris-carrington can you share your `app.js`? This seems like a bug

**Comment by chris-carrington** [comment]
Thank you @bartlomieju! I've attached my app.js. I'm building an open source project named hera which is all local atm. Without hera this file's kinda wtf lol

This is why I'm super excited about some detailed error messaging so we may identify who's reading files and/or what files are being read!

**app.js**
```
import $config from './hera.config.js'
import hera from '../../hera-deno/hera.js'
import { Application, Router } from 'https://deno.land/x/oak/mod.ts'

let router = new Router(),
    app = new Application()

// config + start application
hera.configCors({ $config, app })
hera.configEndpoints({ $config, app, router })
hera.startApp({ $config, app })

**Comment by bartlomieju** [comment]
@chris-carrington I have a hunch that this error originates from dynamic import of local file, do you have such in your code?

**Comment by chris-carrington** [comment]
I appreciate your assistance @bartlomieju!

I do have a dynamic import in my `hera.configEndpoints()` code, here's a condensed version!

```
async (ctx) => {
  $e = await import($config.endpointsPath + endpoint + '.js')
}
```

I just tried to allow-read to the endpointsPath but I'm still getting the error. The endpoints folder just has a bunch of js files in it, no folders
```
Chriss-MacBook-Pro-2:deno cc$ ls
app.js          endpoints       hera.config.js
Chriss-MacBook-Pro-2:deno cc$ deno --allow-net --allow-read=/endpoints app.js
deno oak app running @ http://localhost:4000 🚀
error: Uncaught TypeError: run again with the --allow-read flag

**Comment by bartlomieju** [comment]
> I appreciate your assistance @bartlomieju!
> 
> I do have a dynamic import in my `hera.configEndpoints()` code, here's a condensed version!
> 
> ```
> async (ctx) => {
>   $e = await import($config.endpointsPath + endpoint + '.js')
> }
> ```

Bingo! This is indeed bug, there should be stack trace supplied with error.

> I just tried to allow-read to the endpointsPath but I'm still getting the error. The endpoints folder just has a bunch of js files in it, no folders
> 
> ```
> Chriss-MacBook-Pro-2:deno cc$ ls
> app.js          endpoints       hera.config.js
> Chriss-MacBook-Pro-2:deno cc$ deno --allow-net --allow-read=/endpoints app.js
> deno oak app running @ http://localhost:4000 🚀
> error: Uncaught TypeError: run again with the --allow-read flag
> ```

@chris-carrington `--allow-read=/endpoints` means that you allow Deno to access `/endpoints` directory - is you `$config.endpointsPath === "/"`? Otherwise you need to adjust paths accordingly

**Comment by chris-carrington** [comment]
Thank you so much @bartlomieju, I'm learning a ton from you & you're speed boggles my mind!

`$config.endpointsPath` === `../../hera-olympus/deno/endpoints/`

I am currently running all deno commands @ `../../hera-olympus/deno/`

Which is why I'm thinking `--allow-read=/endpoints` should work

Because when I run `ls`, we're @ the `/endpoints` level

```
Chriss-MacBook-Pro-2:deno cc$ ls
app.js          endpoints       hera.config.js
```

I put a `console.log` above + below the inline import & only the above is logged so the inline import is our error. Impressive intuition you've got!

**Comment by bartlomieju** [comment]
Update: @piscisaureus suggested we could construct `v8::TryCatch` manually when `host_import_module_dynamically_callback` is called and store full stack trace.

Then in `dyn_import_error` it should be possible to construct new exception and attach stack trace from stored exception.

**Comment by bartlomieju** [comment]
This issue is stale. Stack traces are now shown for errors originating in dynamic imports.

**Comment by cawoodm** [comment]
I too am getting no stack traces with deno 1.21.1 - not sure if it's related to dynamic imports but the error shown is not my code and I'd like to know where my code is calling it:
```
error: TS2345 [ERROR]: Argument of type 'string | undefined' is not assignable to parameter of type 'string'.
  Type 'undefined' is not assignable to type 'string'.
          await server.listenAndServeTls(options.certFile, options.keyFile);
                                         ~~~~~~~~~~~~~~~~
    at https://deno.land/x/opine@2.1.4/src/application.ts:586:42
```

**Comment by bartlomieju** [comment]
This error comes from type-checking, I'm not sure if we could attach a stack trace to it, @kitsonk any ideas?
