### ISSUE TITLE
Deno runtime in headless browser

### ISSUE THREAD

**Issue by uasan** [denoland/deno#3815]
Hi.
Perhaps this has already been discussed, but I did not find.

IBM is already successfully experimenting with this.
https://github.com/IBM/browser-functions/blob/master/docs/index.md

There are a lot of advantages in this approach, native `Web API` from the browser manufacturer, `SSR` out of the box, only the I/O (fs, net) in the userland is missing, Deno can provide it.

How's the idea for you?

**Comment by kitsonk** [comment]
That would be a different project than Deno.

**Comment by uasan** [comment]
But with the same consumer qualities that Deno now declares, but there really is a single environment for the frontend and backend.
You can reuse ready-made solutions from browsers - Web Worker, fetch (HTTP cache), std: modules, ...

**Comment by rektide** [comment]
Maybe some day it might be possible to get Deno & rusty_v8 to compile & run in a WebAssembly atop something like WASI.

But in general, Deno is it's own platform, one that attempts to mirror the web platform. The code you run on Deno should often frequently work in the browser, & vice versa. Trying to make Deno itself work in the browser would result in a colossal massive chunk of code running in the browser that duplicates what much of the browser already does, but less fast, with a number of incompatibility issues for folks trying to use Deno in the browser from where the native platform Deno expects can not be polyfilled atop webassembly.

Sorry but Deno is for, for now, for native platforms, & that's a smart decision.

**Comment by uasan** [comment]
> Deno is it's own platform, one that attempts to mirror the web platform.

Ok.
I understand, my point - was why you write what is already in the browser and Chrome headless, can be run on the server.
