### ISSUE TITLE
Remove ansi_term dependency

### ISSUE THREAD

**Issue by ry** [denoland/deno#3817]
Unfortunately we depend on two crates which provide terminal colors: termcolor and ansi_term. They essentially do the same thing. I want to remove ansi_term.

I believe ansi_term is used only the cli/color.rs module: https://github.com/denoland/deno/blob/v0.31.0/cli/colors.rs

This is a good first issue - it's a purely Rust job.

**Comment by kumaran-14** [comment]
@ry I'd like to take this up. Seems straight forward. Replace these ansi_colors
```
Black
Fixed
Red
White
Style
```
with termcolor equivalent

**Comment by sepiropht** [comment]
Not so easy to replace `ansi term` as there is a two method `paint ` and `Fixed` which have no equivalent in crate  termcolor.
Or i missed something ?

**Comment by ry** [comment]
Yes might be not so trivial as just replacing the colors. But still I think it's not too difficult - some methods might need to be refactored.

**Comment by reznord** [comment]
Hi,

I am willing to work on this bug.

**Comment by kumaran-14** [comment]
@reznord Go ahead.

**Comment by jsouto18** [comment]
Hey, @ry I would like to take on this issue. I've been reading the documentation of both _ansi_term_ and _termcolor_ and I believe I can remove the ansi_term dependency.
