### ISSUE TITLE
Deno bundler circular imports error

### ISSUE THREAD

**Issue by srackham** [denoland/deno#3825]
[This minimal Gist](https://gist.github.com/srackham/dd1f86ece0c6e2166506de3de05c5607) contains a circular dependency. It is valid TypeScript and it executes fine with the Deno `run` command but the bundled JavaScript code throws an error:

m1.ts
``` typescript
import * as M2 from './m2.ts'

M2.f2()

export function f1() { }
```

m2.ts
``` typescript
import * as M1 from './m1.ts'

console.log("M1:",M1)
M1.f1()

export function f2() { }
```

Here's what happens when `m1.ts` is run and when `m1.ts` is bundled and run:

```
$ deno --version
deno 0.31.0
v8 8.1.108
typescript 3.7.2

$ deno run https://gist.githubusercontent.com/srackham/dd1f86ece0c6e2166506de3de05c5607/raw/8c3f483c5015aeaba7021f47129ab00225d298eb/m1.ts
M1: { f1: [Function: f1] }

$ deno bundle https://gist.githubusercontent.com/srackham/dd1f86ece0c6e2166506de3de05c5607/raw/8c3f483c5015aeaba7021f47129ab00225d298eb/m1.ts m1.js
Bundling "https://gist.githubusercontent.com/srackham/dd1f86ece0c6e2166506de3de05c5607/raw/8c3f483c5015aeaba7021f47129ab00225d298eb/m1.ts"
Emitting bundle to "m1.js"
4.2 kB emitted.

$ deno run m1.js 
M1: { default: {} }
error: Uncaught TypeError: M1.f1 is not a function
► file:///home/srackham/local/projects/rimu-deno/m1.js:135:8

135     M1.f1();
           ^
```

Issue [#653](https://github.com/denoland/deno/issues/653) suggests that circular dependencies should work.

See also [Bundling V2 #2475](https://github.com/denoland/deno/issues/2475).

**Comment by kitsonk** [comment]
Thanks for the test case... I will have to take a deeper look, but it is possible that we have a defect in the instantiation.

**Comment by srackham** [comment]
The error occurs because:

1. `getExports()` is called recursively a second time for module `M1` before the first call has completed.

2. Because the M1 `factory` property has been deleted the second call assumes that a previous call has resolved `M1` exports and returns the as yet unpopulated exports object.

3. So when the M2 factory function executes it fails to find `M1.f1()`.
