### ISSUE TITLE
want: Deno.seek/seekSync to return position in file

### ISSUE THREAD

**Issue by dubiousjim** [denoland/deno#3826]
As far as I can tell, there's no way to query what is the current position that a file descriptor is prepared to read from/write to. Normally that would be the return value of `seek(0, SEEK_CURRENT)`. But Deno's seek methods return void.

The [underlying Rust method](https://doc.rust-lang.org/std/io/trait.Seek.html) does give a return value. But I'm not conversant enough with Rust and the relevant parts of Deno's code to figure out how to expose this...

**Comment by ry** [comment]
Should be an easy fix for someone who wants to explore how we execute ops.

**Comment by caian-gums** [comment]
Can I take this issue? I just took a look at the repo and this seems a not so hard task 😄

**Comment by dubiousjim** [comment]
I was experimenting with this too, I think [this branch](https://github.com/dubiousjim/deno/commits/seek_return) has the core corrections. But we should add tests, make sure the docs are updated, &c.

**Comment by bartOssh** [comment]
If above PR of mine is satisfying, I can then link the issue according to recommend approach. I have limited and formatted the code according to contribution guide.

**Comment by bartlomieju** [comment]
Done in #4211
