### ISSUE TITLE
Deno.remove() cannot remove dangling symlink

### ISSUE THREAD

**Issue by dubiousjim** [denoland/deno#3832]
Suppose `valid_symlink` points to a real target file, and `invalid_symlink` points to a non-existing file. Then:

```
Deno.removeSync(valid_symlink)
```

works fine --- and deletes the symlink rather than its target. OK, then we would also expect:

```
Deno.removeSync(invalid_symlink)
```

to delete the symlink. But instead this fails with a `NotFound` error. (Same holds for `remove` rather than `removeSync`.)

Not only is this unexpected, it looks like then there's no way for Deno to remove a dangling symlink (short of running a subprocess).

Looking at the file `./cli/ops/fs.rs`, lines starting around 157 have:

```
fn op_remove(
   ...
    let metadata = fs::metadata(&path)?;
```

Perhaps if that's changed to [fs::symlink_metadata](https://doc.rust-lang.org/std/fs/fn.symlink_metadata.html) it'd fix the issue?

I can't build Deno on my own machine to test, though.

**Comment by rafaelvargas** [comment]
@dubiousjim @ry I'll work on this. It seems like the following changes would fix this bug:
```rust
fn op_remove(...) -> Result<JsonOp, ErrBox> {
  ...
    let metadata = fs::symlink_metadata(&path)?;
    let file_type = metadata.file_type();
    if file_type.is_file() || file_type.is_symlink() {
      fs::remove_file(&path)?;
    } else if recursive {
      remove_dir_all(&path)?;
    } else {
      fs::remove_dir(&path)?;
    }
  ...
}
```
I'll test it later and check if these changes resolve this issue.
