### ISSUE TITLE
/std/installer is deprecated and should be removed

### ISSUE THREAD

**Issue by ry** [denoland/deno#3836]
However when that is done, you'll find the tests fail:
```
cargo test --release std_tests
```

**Comment by nayeemrmn** [comment]
I think this is `std/http/server_test.ts`: https://github.com/nayeemrmn/deno/runs/418531255. It has actually always hung for me locally. Maybe the installer tests (which start and interact with a file server) cancelled the effect somehow?

**Comment by bartlomieju** [comment]
@nayeemrmn good lead! That was my suspicion as well, but had no luck to pin point it. That should be helpful, thanks!
