### ISSUE TITLE
RFE: Task priority/scheduling support

### ISSUE THREAD

**Issue by rektide** [denoland/deno#3840]
WIP but there's some interesting work afoot to add scheduling priority & control to JS tasks in [Main Thread Scheduling](https://github.com/WICG/main-thread-scheduling).

I feel like it'd be super useful & helpful to be able to better control & work with priority on the server too, and it'd be rad if Deno could leverage & perhaps even help shape some of these emerging APIs for orchestrating JavaScript tasks better.

I'm happy with whatever we want to do with this ticket in the meantime, as I have no particular current ask.

**Comment by kitsonk** [comment]
It is "In Development" on Chromium, but at the moment they seem to be standing on their own: https://chromestatus.com/feature/6031161734201344

To me, there should be broader consensus before we really consider it (plus it being delivered in Chromium).

**Comment by kitsonk** [comment]
This appears to have been abandoned at the prototype stage in Chromium sometime last year and has never shipped.  There is a lack of consensus (and apparently a lack of support) in the WICG.  I don't think we would consider it until it is shipped unflagged in some browser.
