### ISSUE TITLE
Is there a way to access past version of updated dependencies?

### ISSUE THREAD

**Issue by filipesmedeiros** [denoland/deno#3841]
So if I want to update my dependency's source, but it breaks my program, is there anyway to retrieve the old code? Because if the dependency is hosted somewhere with no version control, I can't access the file anymore.

Maybe a system for saving X old versions of a dependency would be cool?

**Comment by ry** [comment]
> Maybe a system for saving X old versions of a dependency would be cool?

I'm open to it, but it's a complex problem. If someone built a tool outside of the deno repo which did this and it proved to be useful to people we could integrate it. It isn't a priority right now.

**Comment by filipesmedeiros** [comment]
I might try to make that happen, I'll come back with something soon.

**Comment by filipesmedeiros** [comment]
Hey @ry (or anyone who can help), can you just point me to the relevant code? Like where you guys cache the dependencies, and maybe also when you compile them.

First time contributing to OS and this codebase is completely new to me also! Thanks.

**Comment by kevinkassimo** [comment]
@filipesmedeiros Related code should be in `cli/file_fetcher.rs`. You'll notice a bunch of mentioned about cache there.

**Comment by filipesmedeiros** [comment]
Is this something that's still of interest or can we close it?

**Comment by bartlomieju** [comment]
I think we can close this, thanks @filipesmedeiros
