### ISSUE TITLE
[plugin] How to return dynamic size result in op handler

### ISSUE THREAD

**Issue by keroxp** [denoland/deno#3853]
Currently result of plugin's op handler is defined as:

```rust
pub type Buf = Box<[u8]>;
pub type OpAsyncFuture<E> =
  Pin<Box<dyn Future<Output = Result<Buf, E>> + Send>>;
```

Simply, why is `Buf`, a result of op, defined as `Box<[u8]>`? How should it be used? 
I tried writing the handler that returns JSON string, but couldn't find way to cast JSON string (dynamic size)  to `[u8]`.

I found that `ZeroCopyBuf`  (a second argument of op handler) can be used for response with dynamic size but still there is no way to know the size of response before dispatching.

Is it possible to define op handler that returns response with arbitrary size?

**Comment by bartlomieju** [comment]
Sure!

```rust
fn some_op(control: &[u8], zero_copy: Option<ZeroCopyBuf>) -> CoreOp {
  // some json string
  let res = json!({ "ok": true });
  let mut vec = serde_json::to_vec(&value).unwrap();  
  let buf = vec.into_boxed_slice();
  CoreOp::Sync(buf);
}
```
When you have a json value you can turn it into a vector using `serde_json::to_vec(&value)`. Once you have a vector of bytes calling `into_boxed_slice()` will turn it into `Box<[u8]>`.

**Comment by keroxp** [comment]
`into_boxed_slice()` ! Thank you !
