### ISSUE TITLE
Seems impossible to extend String

### ISSUE THREAD

**Issue by brandonkal** [denoland/deno#3862]
Please don't comment here saying "don't do that". I want to see if it is possible in Deno for a DSL. So far I've been running into TS compiler issues.

1. If a file containing `interface String { b64enc(): string }` contains imports, the LSP complains and does not merge in the interface. This makes it hard to write the implementation of said interface in a safe manner.
2. Round Two: Move declarations to ambient `.d.ts` file. That works okay in the editor. But because the types are ambient, suggestions will exist before actually importing the implementation. Deno complains as well because it can't find it.
3. Rename implementation file from ts to js and use triple slash import to refer to the ambient type file. Deno still complains claiming the added methods don't exist on the string type.

I've tried many things here with no success getting editor + Deno compiler happy.

**Comment by kitsonk** [comment]
All TypeScript files in Deno are treated as modular files.  You need to augment the global interface, interfaces are open ended.

```ts
declare global {
  interface String {
    b64enc(): string;
  }
}

"foo".b64enc();
```

If that doesn't work, please provide the output from Deno.

**Comment by brandonkal** [comment]
Thank you! That's so simple! That works so long as the file has an `export {}` statement.

When I tried that I had `declare module global`. I did find that works which is interesting:
```ts
// entry.ts
import './string-extended.js'
const t = 'one'
console.log(t.b64enc())
```
```js
// string-extended.js
import './string-interface.ts'

String.prototype.b64enc = function() {
  //@ts-ignore -- compiler is wrong on this
  return btoa(this)
}
```
```ts
// string-interface.ts
interface String {
  /** base64 encode */
  b64enc(): string
}
```

Otherwise my editor complains "Augmentations for the global scope can only be directly nested in external modules or ambient module declarations." It seems VSCode doesn't consider a file to be a module unless an import/export statement exists in the file. Do you know if there is a way to fix that?

**Comment by kitsonk** [comment]
> That works so long as the file has an export {} statement.

Yes, sorry.  I forgot that the compiler determines if it is a module or script.  So even though we load them all as modules, always.  I think there is a TypeScript issue to force to be evaluated as modules always.
