### ISSUE TITLE
adopt env_logger

### ISSUE THREAD

**Issue by ry** [denoland/deno#3869]
It's very difficult to get debugger log output during the rust unit tests with our current setup.

**Comment by runnerSnail** [comment]
It seems that the rust end did not read the environment variables？
deno can   read the environment variables 
rust file
```rust
   #[macro_use] extern crate log;
    debug!("client_id = {}", client_id);
```
deno run
```shell
RUST_LOG=debug deno run --allow-all test.ts
```

**Comment by attliaLin** [comment]
Maybe we can use the [tracing](https://github.com/tokio-rs/tracing) which is supported by Tokio group. And really work well with async.

**Comment by bartlomieju** [comment]
Done in #7142
