### ISSUE TITLE
Response body will be empty when tried fetch specific pages

### ISSUE THREAD

**Issue by rokoucha** [denoland/deno#3871]
After update to v0.30.0 from v0.29.0, Body will be empty.
Example code is
```js
;(async () => {
  const response = await fetch('https://scrapbox.io/')
  console.log(await response.text()) // => ""
})()
```

I checked some websites which body will be empty.
The website which the problem occurred is

- https://scrapbox.io
- https://helpfeel.com

The affected website uses "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256" in the cipher suite and uses "P256" in the key exchange.
Also uses a certificate issued by Let's encrypt.

![affected website](https://user-images.githubusercontent.com/6058487/73657561-dabcb500-46d5-11ea-9855-015b9abc1c09.png)

https://cors-anywhere.herokuapp.com/ uses that cipher suite but uses a certificate issued by DigiCert.
I'm not sure if that's why, but no problem has occurred.

![not affected website](https://user-images.githubusercontent.com/6058487/73785487-b0a0eb00-47da-11ea-810f-50161f16ef88.png)

Rollback to v0.29.0, Body will not be empty.
```
$ deno --version
deno 0.29.0
v8 8.1.108
typescript 3.7.2
```

In v0.32.0, The body still will be empty.
```
$ deno --version
deno 0.32.0
v8 8.1.108
typescript 3.7.2
```

Reproduced in the following environment
  - `Arch Linux 5.4.15-arch1-1 #1 SMP PREEMPT Sun, 26 Jan 2020 09:48:50 +0000 x86_64 GNU/Linux`
  - `Windows 10 Pro 1909 (Build 18363.592)`

**Comment by rokoucha** [comment]
Reproduced in the following environment
  - `Arch Linux 5.4.15-arch1-1 #1 SMP PREEMPT Sun, 26 Jan 2020 09:48:50 +0000 x86_64 GNU/Linux`
  - `Windows 10 Pro 1909 (Build 18363.592)`

**Comment by rokoucha** [comment]
In v0.32.0, The body still will be empty.
```
$ deno --version
deno 0.32.0
v8 8.1.108
typescript 3.7.2
```

**Comment by bartlomieju** [comment]
@rokoucha does this problem still persist in 1.1.0?

**Comment by rokoucha** [comment]
@bardiarastin I tried it on Deno 1.1.0, but it didn't reproduce.
So I think this issue is solved.
