### ISSUE TITLE
crate deno = "0.32.0" breaks when docs.rs tries to generate docs

### ISSUE THREAD

**Issue by ry** [denoland/deno#3875]
https://docs.rs/crate/deno/0.32.0/builds/218188

sample from output:
```
[INFO] [stderr]   = note: /opt/rustwide/target/debug/deps/libdeno_core-39f39d3b842f5bef.rlib(deno_core-39f39d3b842f5bef.deno_core.wjpcw10m-cgu.11.rcgu.o): In function `rusty_v8::script::Script::run':
[INFO] [stderr]           /opt/rustwide/cargo-home/registry/src/github.com-1ecc6299db9ec823/rusty_v8-0.2.1/src/script.rs:74: undefined reference to `v8__Script__Run'
[INFO] [stderr]           /opt/rustwide/target/debug/deps/libdeno_core-39f39d3b842f5bef.rlib(deno_core-39f39d3b842f5bef.deno_core.wjpcw10m-cgu.11.rcgu.o): In function `rusty_v8::script::Script::run':
[INFO] [stderr]           /opt/rustwide/cargo-home/registry/src/github.com-1ecc6299db9ec823/rusty_v8-0.2.1/src/script.rs:74: undefined reference to `v8__Script__Run'
[INFO] [stderr]           /opt/rustwide/target/debug/deps/libdeno_core-39f39d3b842f5bef.rlib(deno_core-39f39d3b842f5bef.deno_core.wjpcw10m-cgu.11.rcgu.o): In function `rusty_v8::script::Script::compile':
[INFO] [stderr]           /opt/rustwide/cargo-home/registry/src/github.com-1ecc6299db9ec823/rusty_v8-0.2.1/src/script.rs:57: undefined reference to `v8__Script__Compile'
```

**Comment by jyn514** [comment]
Maybe this snippet is more helpful:

```
[INFO] [stderr]    Compiling deno v0.34.0 (/opt/rustwide/workdir)
[INFO] [stderr] error: linking with `cc` failed: exit code: 1
[INFO] [stderr]   |
[INFO] [stderr]   = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/opt/rustwide/rustup-home/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/opt/rustwide/target/debug/build/deno-cce063734481e029/build_script_build-cce063734481e029.11arg7v66054lc3a.rcgu.o"
... lots of .o files ...
[INFO] [stderr]           /opt/rustwide/cargo-home/registry/src/github.com-1ecc6299db9ec823/rusty_v8-0.2.1/src/platform/mod.rs:27: undefined reference to `v8__Platform__DELETE'
[INFO] [stderr]           /opt/rustwide/target/debug/deps/librusty_v8-a584a143427ad299.rlib(rusty_v8-a584a143427ad299.rusty_v8.41k89qp7-cgu.9.rcgu.o): In function `<rusty_v8::snapshot::OwnedStartupData as core::ops::drop::Drop>::drop':
[INFO] [stderr]           /opt/rustwide/cargo-home/registry/src/github.com-1ecc6299db9ec823/rusty_v8-0.2.1/src/snapshot.rs:80: undefined reference to `v8__StartupData__DESTRUCT'
[INFO] [stderr]           /opt/rustwide/target/debug/deps/librusty_v8-a584a143427ad299.rlib(rusty_v8-a584a143427ad299.rusty_v8.41k89qp7-cgu.9.rcgu.o): In function `rusty_v8::snapshot::SnapshotCreator::new':
[WARN] too much data in the log, truncating it
```

I'd like to help (I maintain docs.rs) but I'm not sure what's going wrong or how to fix it. Do you need updated v8 bindings? We have [`3.14.5`](https://github.com/rust-lang/crates-build-env/blob/master/packages.txt#L835) installed in the build environment.

**Comment by ry** [comment]
Hi jyn514 - I think the issue is that we cannot build our bindings in rusty_v8 on docs.rs and hence we cannot link in the Deno crate. See https://github.com/denoland/rusty_v8/blob/master/build.rs#L14
We are unable to build rusty_v8 because we rely on several binary downloads of tools which are unavailable in a standard environment.

**Comment by jyn514** [comment]
@ry would it be possible to have `rusty_v8` and your other tools in a submodule so they will be downloaded by docs.rs when it pulls your crate initially?

**Comment by ry** [comment]
@jyn514 The binary downloads are changing quite often and quite large. Each platform is probably around 86M:
```
> du -sh clang/
 86M	clang/
```
Basically we're bridging two build systems: chromium and cargo. It's very involved and complex - about 800k lines of C++ - which results in 1 hour build.

That said, the homebrew people have been able to build it independent of the binary downloads... Maybe @chrmoritz has some advise on how we could build in docs.rs?

**Comment by chrmoritz** [comment]
The main requirement for building `rusty_v8` (and hence `deno`) without using the Google binaries is having a recent version of `clang` / `llvm` installed. It looks like Ubuntu 18.04 (what doc.rs is using) still ships with clang 6, which is too old. The last time I've checked llvm 8.0 was the minimum requirement, but using the latest version 9.0 might be even better, because I'm not sure how long llvm 8.0 will still be supported. (BTW: we are using llvm 9.0 (or system `clang` on macOS Catalina) in homebrew for building `deno`.)

Other than that having `ninja` and `gn` installed is also required, but these tools are quite small and easy to build and shouldn't be a bigger issue to get (we are compiling `gn` on demand for every `deno` build for example). But getting at least ninja installed wouldn't hurt either.

But the 15min build time limit could also be an issue without network access and therefore without the ability to use `sccache` to speed up the build.

**Comment by ry** [comment]
> But the 15min build time limit could also be an issue without network access and therefore without the ability to use sccache to speed up the build.

Yikes, that that definitely will not do. @jyn514 we need at least 1 hour build limit to make this work - probably better to have a bit more tho.

**Comment by jyn514** [comment]
Ouch, an hour is a lot, especially since I presume this will be using a ton of CPU/IO/memory in the meantime. Our current memory limit is 3 GB, I assume you'll need that raised too? We only have 15 GB total on the build server ...

**Comment by bartlomieju** [comment]
No longer actionable as `deno` has only a binary target.
