### ISSUE TITLE
re-enable tests from tokio runtime refactor 

### ISSUE THREAD

**Issue by ry** [denoland/deno#3876]
https://github.com/denoland/deno/commit/161cf7cdfd44ace8937fb7940727984990742d18

- [x] installer_test_local_module_run #3882
- [x] installer_test_remote_module_run #3882
- [x] _015_duplicate_parallel_import https://github.com/denoland/deno/pull/3904
- [x] _026_workers

**Comment by bartlomieju** [comment]
Finished with #3828
