### ISSUE TITLE
Duplicate websocket replies?

### ISSUE THREAD

**Issue by ondras** [denoland/deno#3880]
If I call the `WebSocketImpl::send` twice, synchronously, four message frames will be delivered:

```js
ws.send("aaa");
ws.send("bbb");
// other party will receive aaa, bbb, aaa, bbb
```

Is this intentional? I know that `send` is async, but does this imply I have to await each send operation before sending more?

**Comment by ondras** [comment]
The complete code, for reference:

```ts
import { serve, ServerRequest } from "https://deno.land/std/http/server.ts";
import { acceptWebSocket } from "https://deno.land/std/ws/mod.ts";

async function processUpgradeRequest(req: ServerRequest) {
	try {
		let ws = await acceptWebSocket({
			conn: req.conn,
			headers: req.headers,
			bufReader: req.r,
			bufWriter: req.w
		});
		ws.send("aaa");
		ws.send("bbb");
	} catch (e) {
		console.error("failed to accept websocket", e);
	}
}

const port = Deno.args[0] || "8080";
console.log("websocket server is running on", port);
for await (const req of serve(`:${port}`)) {
	processUpgradeRequest(req);
}
```

**Comment by keroxp** [comment]
@ondras I've seen the case and found the reason. You misses to add `await` before send. Code below works fine:

```ts
await ws.send("aaa");
await ws.send("bbb");
```

However this is undesirable behaviour and must be fixed.

**Comment by ondras** [comment]
Hi @keroxp,

thanks for your reply. Your suggestion is consistent with the last part of my bugreport:

> I know that `send` is async, but does this imply I have to await each send operation before sending more?

As far as I know, Deno APIs are trying to be parallel with Browser APIs where possible and the client-side WebSocket does not have this limitation, so I agree that calling `send()` multiple times synchronously shall be considered okay.

**Comment by ondras** [comment]
Awesome, thanks! Seems to work flawlessly now. :+1:
