### ISSUE TITLE
Allow access to win32

### ISSUE THREAD

**Issue by Yu02** [denoland/deno#3892]
Allow programmers to import Windows core DLLs (win32) like user32 so more features can be used without turning to plugins (like changing the screen brightness for example).

Example:

```js
Deno.win32.Winuser.BringWindowToTop(...)
```

**Comment by caspervonb** [comment]
I don't think there is anything actionable here?

**Comment by bartlomieju** [comment]
@caspervonb agreed, it's highly unlikely that we'll ever add `Deno.win32`. Respectfully closing.

**Comment by rivy** [comment]
@bartlomieju , @caspervonb , for command line applications, parity between *nix and Windows versions for certain things like command line parsing (especially globs/wildcards) seems to require some lower-level access to OS APIs (eg, `GetCommandLine`). Is there a path or planned path to access that capability?

**Comment by bartlomieju** [comment]
@rivy if you have specific request regarding `GetCommandLine` I suggest to open a new issue, but as said previously it's unlikely that we'll add win32 specific APIs

**Comment by rivy** [comment]
I have (see #9871), just no response as of yet.

**Comment by Kreijstal** [comment]
You can just use dlopen can't you?
