### ISSUE TITLE
Discussion: Package manager inspired by pacman (Arch Linux)

### ISSUE THREAD

**Issue by EmilCataranciuc** [denoland/deno#3896]
I know this has been previously discussed already but at least I need some clarifications.
First of all, it is not yet clear to me how would deno manage dependencies in a clear, transparent way? So that a developer could open one file and see the dependency tree.
Second, in it's current form, pulling packages from URLs isn't very redundant. If the server goes down you are dead in the water. Why not implement a package management similar to packman on Arch Linux (of course there are other similar package managers). Which pulls the package from a list of repositories provided either by the distribution or by the user.

**Comment by kitsonk** [comment]
> First of all, it is not yet clear to me how would deno manage dependencies in a clear, transparent way?

[deps.ts](https://deno.land/std/manual.md#linking-to-third-party-code) is a good convention... but it should be a convention, to allow people to have different conventions.

> So that a developer could open one file and see the dependency tree.

You don't get a dependency tree with a `package.json`, but still the capability is already built into Deno

`deno info main.ts`

> Second, in it's current form, pulling packages from URLs isn't very redundant. If the server goes down you are dead in the water.

If the registry goes down, you're dead in the water.  What makes a formal priority package registry special to a web server?  Again it is [discussed in the manual](https://deno.land/std/manual.md#linking-to-third-party-code) as well.

> Which pulls the package from a list of repositories provided either by the distribution or by the user.

At the end of the day, those are URLs to servers.  Not any different from having that exist in code.

**Comment by EmilCataranciuc** [comment]
Cool. Thank you. Looks like the documentation actually addresses many things already. Will keep reading it.
