### ISSUE TITLE
Suggestion: Add an `--overwrite` option to Deno install command

### ISSUE THREAD

**Issue by srackham** [denoland/deno#3916]
Currently (Deno 0.32.0) manual intervention is required if you run the install command for a previously installed executable. This halts any build tasks that run Deno install until the user presses 'y'.

**Comment by ry** [comment]
Or —force ? I think it might be better if we remove the interactive prompt and have it fail - requiring the user to provide -f instead

**Comment by kevinkassimo** [comment]
+1 for `--force/-f`, common enough

**Comment by srackham** [comment]
Yeah, `--force/-f` is definitely more Unixy c.f. `mv`, `rm`, `git push` etc.
