### ISSUE TITLE
[bug] regression: `deno test` Cannot resolve module "<dir>/test"

### ISSUE THREAD

**Issue by brandonkal** [denoland/deno#3919]
I mentioned this on the Gitter earlier and do not see an open issue here to track this.

Deno is trying to find a file named "test" rather than using the test subcommand as specified.

**Comment by bartlomieju** [comment]
Just tried with `0.32.0` - it works just fine. 

Does this happen on master?

**Comment by brandonkal** [comment]
Weird. I'm using the 0.32.0 release on Linux.

**Comment by bartlomieju** [comment]
@brandonkal can you share terminal output?

**Comment by brandonkal** [comment]
Sure but there is no output beyond what is in the title
In a folder containing only this file:
```ts
// broken.test.ts
import { test as it } from 'https://deno.land/std@v0.32.0/testing/mod.ts'
import { assertEquals } from 'https://deno.land/std@v0.32.0/testing/asserts.ts'

it('works', () => {
	assertEquals(10, 10)
})
```
```
$ deno -A test
Cannot resolve module "file:///home/brandon/broken-deno-test/test"
```

**Comment by nayeemrmn** [comment]
You need to specify the perm flags _after_ the subcommand, since not every subcommand has them. The logic behind that should be clear. Thus `deno -A` is assumed to be the `deno -A <script>` usage.

**Comment by brandonkal** [comment]
Permission flag after subcommand is confusing.
I see `test` as shorthand for `https://deno.land/std@v0.32.0/testing/runner.ts`

It is still broken though
```
brandon@dev:~/broken-deno-test$ deno test -A
No matching test modules found.
brandon@dev:~/broken-deno-test$ deno test -A .
No matching test modules found.
brandon@dev:~/broken-deno-test$ deno test
No matching test modules found.
brandon@dev:~/broken-deno-test$ ls
broken.test.ts
```

**Comment by nayeemrmn** [comment]
> Permission flag after subcommand is confusing.

Subcommand-specific flags go after the subcommand.

> ```
> brandon@dev:~/broken-deno-test$ ls
> broken.test.ts
> ```
Run `deno https://deno.land/std@v0.32.0/testing/runner.ts --help` to see what filename patterns are detected -- that isn't one of them.

**Comment by brandonkal** [comment]
It should be one of them

**Comment by nayeemrmn** [comment]
Found it: #2947 :) You can close this if the other problems are okay.

**Comment by brandonkal** [comment]
"test" is never a valid module name because it is extensionless. Therefore,
a more helpful output must be provided ("Did you mean `deno test -A`?")

I have also seen the "Cannot resolve module" error with just `deno test` but I am fine ignoring that because I can't reproduce it reliably.

**Comment by nayeemrmn** [comment]
@brandonkal Yeah, "smart" flag error messages are commonly suggested. Another one is where a perm error occurs and the relevant perm flag is detected in the script args. Could you open a new issue?

**Comment by nayeemrmn** [comment]
@bartlomieju Can this be closed?
