### ISSUE TITLE
[Question] Use typings.d.ts of date-fns

### ISSUE THREAD

**Issue by kt3k** [denoland/deno#3923]
We can use date-fns with the following import statement.

```ts
import { format } from 'https://deno.land/x/date_fns/index.js'
```

date-fns publishes typings.d.ts at the root of their github repo, and we can reference it like the below.

```ts
/// <reference path="https://raw.githubusercontent.com/date-fns/date-fns/master/typings.d.ts" />
import { format } from 'https://deno.land/x/date_fns/index.js'
```

However the above doesn't work with the following error:

```
error: Uncaught ImportPrefixMissing: relative import path "date-fns" not prefixed with / or ./ or ../ Imported from "https://raw.githubusercontent.com/date-fns/date-fns/master/typings.d.ts"
► $deno$/dispatch_json.ts:40:11
```

Does anyone know how to fix the above error?

**Comment by kitsonk** [comment]
All the:

```ts
import { endOfSecond } from 'date-fns'
```

that are located in `typings.d.ts` are not compatible with Deno.

**Comment by axetroy** [comment]
already support in vscode extension

BTW. `typing.d.ts` 's namespace 'data-fns' is not compatible with Deno

```diff
- declare module 'data-fns' {
+ declare module 'https://deno.land/x/date_fns/index.js' {
  export type Interval = IntervalAliased

  export type Locale = LocaleAliased

  export type Duration = DurationAliased
}

```

![1](https://user-images.githubusercontent.com/9758711/74108634-52e41880-4bb7-11ea-952f-f5891c9ffd9c.gif)

**Comment by kitsonk** [comment]
Or if you want something that looks more portable:

```diff
- declare module 'data-fns' {
+ declare module './date_fns/index.js' {
  export type Interval = IntervalAliased

  export type Locale = LocaleAliased

  export type Duration = DurationAliased
}
```

We need to add the emitting of declarations to bundles in Deno as well, and then we would only emit module names in declarations that would work with Deno.

**Comment by kitsonk** [comment]
Can this be closed?
