### ISSUE TITLE
[plugin] Can't return response bytes that is not aligned to 32bit

### ISSUE THREAD

**Issue by keroxp** [denoland/deno#3925]
cc: @bartlomieju 

```rust
pub fn op_handler_sync(data: &[u8], zero_copy: Option<PinnedBuf>) -> CoreOp {
  let result = b"abc";
  let result_box = Box::new(*result);
  Op::Sync(result_box)
}
```

Plugin handler like above will throw error below:

```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `3`,
 right: `0`', core/shared_queue.rs:185:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

This is because boxed response is not aligned to 32bit: https://github.com/denoland/deno/blob/master/core/shared_queue.rs#L184

Is there any way to return string with original size? On returning json, this is not hard problem but sometime it can be undesirable. You commented:

> JS-side may cast `record` to Int32Array

Do you mean that we allow js-side handler to cast `Uint8Array` into `Int32Array` directly?
Or are there other reasons for this limitation?

**Comment by bartlomieju** [comment]
> Is there any way to return string with original size? On returning json, this is not hard problem but sometime it can be undesirable. You commented:
> 
> > JS-side may cast `record` to Int32Array
> 
> Do you mean that we allow js-side handler to cast `Uint8Array` into `Int32Array` directly?
> Or are there other reasons for this limitation?

That means that "dispatch minimal" gets a `Uint8Array` and then converts it to `Int32Array`:
```ts
  const header = ui8.slice(0, 12);
  const buf32 = new Int32Array(
    header.buffer,
    header.byteOffset,
    header.byteLength / 4
  );
```
`Int32Array` constructor requires that underlying buffer is aligned to 4-bytes. Can you just pad the string with spaces?
```rust
let result = b"abc";
result.resize((result.len() + 3usize) & !3usize, b' ');
result.into_boxed_slice()
```

**Comment by keroxp** [comment]
> That means that "dispatch minimal" gets a Uint8Array and then converts it to Int32Array:

Make sense.

> Can you just pad the string with spaces? Example:

It can be if response format is json as tail white-spaces can be trimmed.
However if js-side expects response being string or raw bytes, there seems to be no way to check original size by default, doesn't it?
In your example, you can't determine whether original response was "abc" or "abc ".

Is it acceptable design limitation for dynamic operation?

**Comment by piscisaureus** [comment]
I think this is a real bug. If there are alignment restrictions on op return values, they should either be expressed in the type system or lifted.

Note that @keroxp is not trying to return an unaligned int32, but an actual array of bytes.
