### ISSUE TITLE
`deno install` does not support import maps

### ISSUE THREAD

**Issue by eliassjogreen** [denoland/deno#3929]
The `deno install` command should support the `--importmap` flag so that you would be able to write:
```
deno install --importmap import_map.json asd asd.ts
```
without it complaining about `Found argument '--importmap' which wasn't expected, or isn't valid in this context`.

**Comment by ntedgi** [comment]
if this issue is still available il be happy  to try it

**Comment by bartlomieju** [comment]
@ntedgi please do

**Comment by ntedgi** [comment]
thanks!

**Comment by ntedgi** [comment]
@bartlomieju can you please review my PR
