### ISSUE TITLE
gist bundle size tripled after #3927

### ISSUE THREAD

**Issue by piscisaureus** [denoland/deno#3933]
#3927

**Comment by ry** [comment]
my guess is this import: https://github.com/keroxp/deno/blob/346d51748befe6a383db39f79e10be235e6b9d62/std/flags/mod.ts#L1

<img width="970" alt="Screen Shot 2020-02-11 at 11 42 50 AM" src="https://user-images.githubusercontent.com/80/74258151-dc810c80-4cc3-11ea-9f56-218b9a8bc24c.png">


cc @keroxp

**Comment by ry** [comment]
```
> deno info https://deno.land/std/examples/gist.ts
local: /Users/rld/Library/Caches/deno/deps/https/deno.land/std/examples/gist.ts
type: TypeScript
compiled: /Users/rld/Library/Caches/deno/gen/https/deno.land/std/examples/gist.ts.js
map: /Users/rld/Library/Caches/deno/gen/https/deno.land/std/examples/gist.ts.js.map
deps:
https://deno.land/std/examples/gist.ts
  └─┬ https://deno.land/std/flags/mod.ts
    └─┬ https://deno.land/std/testing/asserts.ts
      ├── https://deno.land/std/fmt/colors.ts
      ├── https://deno.land/std/testing/diff.ts
      └─┬ https://deno.land/std/testing/format.ts
        └── https://deno.land/std/testing/asserts.ts
```

**Comment by kitsonk** [comment]
Hmmm... It feels like we should have a more lightweight `assert()` that is actually part of Deno, that we could build on top of in `std`.  40k seems a bit heavy to just detect a flow (plus we really should try to avoid circular dependencies like that 😢 )

**Comment by ry** [comment]
If we had tree shaking on the bundle this wouldn't be a problem. I wonder if SWC could help us there?

**Comment by kitsonk** [comment]
I need to look more at the parsing of SWC, and a bit more research in how something like rollup tree-shakes as the logic gets really complex with things like namespace exports and detecting potential side effects. If swc produces an estree like AST then the logic should be adaptable from other projects. If it isn't then it really be from square one.

**Comment by bartlomieju** [comment]
> Hmmm... It feels like we should have a more lightweight `assert()` that is actually part of Deno, that we could build on top of in `std`. 40k seems a bit heavy to just detect a flow (plus we really should try to avoid circular dependencies like that 😢 )

That especially makes sense, after addition of `Deno.test()` API - seems silly to have to load assertion functions. I guess stripped down version without coloring and pretty print could do?
