### ISSUE TITLE
[Doc] https://deno.land/std/fs/README.md

### ISSUE THREAD

**Issue by saostad** [denoland/deno#3934]
in Doc https://deno.land/std/fs/README.md

### globToRegExp

Generate a regex based on glob pattern and options This was meant to be using the the fs.walk function but can be used anywhere else.
```ts
import { globToRegExp } from "https://deno.land/std/fs/mod.ts";

globToRegExp("foo/**/*.json", {
  flags: "g",
  extended: true,
  globstar: true
}); // returns the regex to find all .json files in the folder foo
```
globToRegExp does not exist in actual code.
Compiler Error:
```
error TS2305: Module '"https://deno.land/std/fs/mod"' has no exported member 'globToRegExp'.

► file:///C:/Users/xxx/tests/deno01/mod.ts:1:10

1 import { globToRegExp } from "https://deno.land/std/fs/mod.ts";
```

**Comment by nayeemrmn** [comment]
That's in the `path` module now. Sorry, those READMEs are often left outdated.

Honestly they're redundant doc for a random subset of functions that exist in that directory. We should instead use them to briefly summarise what the directory is for and how it might be extended with just one or two stable examples.

**Comment by bartlomieju** [comment]
Stale

**Comment by sant123** [comment]
Hi, I found a similar issue when importing a module that exports some remote modules. Please take a look:

![image](https://user-images.githubusercontent.com/7959437/84606282-6572a500-ae6a-11ea-89f4-8c6c963d75e5.png)

Also if a import the module with *

![image](https://user-images.githubusercontent.com/7959437/84606311-bbdfe380-ae6a-11ea-92a5-e6884204304c.png)

I just can see the method inside the object, but still can't access it.

![image](https://user-images.githubusercontent.com/7959437/84606330-ddd96600-ae6a-11ea-847b-a908530d8fcd.png)
