### ISSUE TITLE
Outdated paths in std/manual.md

### ISSUE THREAD

**Issue by seishun** [denoland/deno#3939]
For example:

- tests/http_bench.ts (moved to tools/deno_tcp.ts)
- third_party/wrk/linux/wrk (moved to third_party/prebuilt/linux64/wrk)
- tests/002_hello.ts (moved to cli/tests/002_hello.ts)

I'd be happy to update them myself but I don't know what to do with some of them. For example, ./third_party/v8/tools/linux-tick-processor was moved to v8_rusty and is no longer directly accessible.

**Comment by nayeemrmn** [comment]
`https://github.com/denoland/deno/blob/master/cli/js/lib.deno_runtime.d.ts` -> `https://github.com/denoland/deno/blob/master/cli/js/lib.deno.ns.d.ts`

**Comment by kitsonk** [comment]
@nayeemrmn I've got a better update for that one in #3863 as it is a bit more complex now.

**Comment by bartlomieju** [comment]
Manual had been overhauled for 1.0 release
