### ISSUE TITLE
Make ClojureScript A First Class Language?

### ISSUE THREAD

**Issue by JimLynchCodes** [denoland/deno#3941]
I think deno is an awesome project! I am a huge fan of TypeScript, but to be honest I prefer very functional TypeScript and hardly ever like to use the `class` keyword. ClojureScript is basically just referring to the fact that other people have already done the hard work of making Clojure's extremely beautiful and simple syntax integrate easily with JavaScript. It would be awesome if deno could somehow leverage the Clojure language, immutability, lazily evaluated seq's, etc. to be even faster than otherwise...

Just throwing it out there! 😁

**Comment by kitsonk** [comment]
Personal opinion, I don't think we should take that on.  Other scripting languages though could be supported via #1739.

**Comment by JimLynchCodes** [comment]
Thanks @kitsonk! 

That's understandable. Probably running my ClojureScript through the Google Closure compiler as I do for Node.js will be the best way for me to prepare it to run in deno. 🙂
