### ISSUE TITLE
Support UDP sockets

### ISSUE THREAD

**Issue by hazae41** [denoland/deno#3942]
I'm working on an software that needs to receive UDP packets. And since Deno only supports TCP, I'm using a node-js frontend that transmits UDP packets to my deno backend through websockets.

I was wondering if there are plans to add UDP support to Deno, and if so, what's the roadmap, what prevent us from adding it right now? 

I would be very happy to have positive answers, it would allow me to only use Deno for my project.

**Comment by ry** [comment]
UDP support would be a welcome addition and not too difficult. You’d basically look up Tokio’s API for it and use the TCP binding as a guide to add support.

**Comment by hazae41** [comment]
How to transfer a Rust "&mut [u8]" buffer to a JS "Uint8Array" buffer and vice-versa? I could not find how

**Comment by hazae41** [comment]
I found, [u8] becomes a JSON Array, then a JS Array, just convert the latter with `new Uint8Array(array)`. To convert it back to a JS Array, use `Array.from(buffer)`. Plus, `Vec<u8>` is preferred over `[u8]`

**Comment by hazae41** [comment]
PR is ready for review https://github.com/denoland/deno/pull/3946
