### ISSUE TITLE
[Codeing Style] for variable description use /** */ comment style over //

### ISSUE THREAD

**Issue by saostad** [denoland/deno#3943]
in [source code](https://github.com/denoland/deno/blob/master/std/io/bufio.ts#L41) I saw variable description in front of each with format `//description` which is not following [JSDocs](https://jsdoc.app/tags-type.html) and also it's not good in VSCode since in mouse pop up over the variable it shows description before variable in format `/**description*/` .
if that makes sense it will be the result :
Before:
```ts
private rd!: Reader; // Reader provided by caller.
private r = 0; // buf read position.
private w = 0; // buf write position.
```
After:
```ts
/**Reader provided by caller.*/
private rd!: Reader;
/**buf read position.*/
private r = 0;
/**buf write position.*/
private w = 0; 
```
if you agree I can take care of applying changes in [style guide](https://deno.land/std/style_guide.md) and std modules.

**Comment by kitsonk** [comment]
Only thought:

```ts
/**Reader provided by caller.*/
```

Should be like this:

```ts
/** Reader provided by caller. */
```

**Comment by David-Else** [comment]
...and the heading `Format code using prettier.` is now out of date too.

I really hope the new formatter produce identical output to Prettier, as the intent of Prettier was to create a new standard:

1. No more debates about what is best, just accept the new standard and get on with life
2. Diffs will be massively improved as different commits won't change the formatting (providing we all use the Prettier defaults)

**Comment by nayeemrmn** [comment]
@David-Else There's no `format.ts` anymore, but we still use prettier for Deno's source. That should probably change at some point but `deno` will become a dev dependency of Deno which it isn't already. No problem with that, though.

**Comment by saostad** [comment]
so should I consider the discussion as everyone agreed with my proposal? 
if yes I will start working on my pull to add it as a rule in style-guide and apply the changes to std modules.

**Comment by nayeemrmn** [comment]
Those are private fields... the current style guide is concerned about _exported_ machinery, that's probably intentional. You can change specific comments but the style guide shouldn't enforce anything more IMO.

**Comment by kitsonk** [comment]
I tend to disagree on that. While consuming private fields elsewhere in the class, a properly formed comment is provided in editors consuming the language services. While it certainly is less critical, we should still be consistent.

**Comment by saostad** [comment]
> I tend to disagree on that. While consuming private fields elsewhere in the class, a properly formed comment is provided in editors consuming the language services. While it certainly is less critical, we should still be consistent.

also if we don't have it in style-guide, eventually it will same again so what's the point of fixing it in the first place?

**Comment by nayeemrmn** [comment]
Sorry, I wasn't sure what change is being proposed. I meant that the style guide shouldn't say that private fields require JSDoc since we're already using TS and most things are self-explanatory.

Of course I agree if there _is_ a comment it should be written correctly... that much should be a given though, If not then maybe with small changes in wording.

**Comment by saostad** [comment]
ok, I will start work on it

**Comment by Hamish-Bassett** [comment]
Hi all,

Is this still open? I can't see any action after the 14th of Feb so nearly half a year ago at this point.
If @saostad is happy for the assistance, I can help out and work with them on this.

**Comment by bartlomieju** [comment]
@Hamish-Bassett thanks, but as far as I can see most of the code adheres to the style guide so this issue is no longer relevant.
