### ISSUE TITLE
Parallelize deno fmt?

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#3948]
I believe the performance of `deno fmt` could be improved by parallelizing across files the read, format, and write.

I'm not sure it will work out of the box with dprint or swc (I think it should), but if not then it's something I could look into.

**Comment by ry** [comment]
I'm open to it. I think it would be a good situation to use Tokio's threaded runtime. I think it's not so important tho (dprint is already so fast!) so I hope it would not introduce a lot of complexity.
