### ISSUE TITLE
Adopt a code of conduct

### ISSUE THREAD

**Issue by dplewis** [denoland/deno#3954]
A [code of conduct](https://robots.thoughtbot.com/adding-a-code-of-conduct-to-open-source-projects) is a common practice to foster a kind, inclusive, cooperative, and harassment-free community. Adopting a code of conduct would demonstrate that new contributors will be welcomed and respected.

**Comment by ry** [comment]
https://github.com/denoland/deno/pull/3956#issuecomment-584289644
