### ISSUE TITLE
deno install creates duplicate flags

### ISSUE THREAD

**Issue by brandonkal** [denoland/deno#3961]
There are a couple of bugs here:
1. `deno install -A ...` should not expand in the wrapper. If Deno introduces more permissions, wrappers may end up diverging.
2. `deno install -A ...` creates duplicate `--allow-env` flags. Fixing (1) will make this not an issue.

Also, looking at the shell wrapper it would be preferrable to call `exec` rather than saving the return code and exiting manually.

**Comment by ry** [comment]
> creates duplicate --allow-env flags. Fixing (1) will make this not an issue

fixed in #3906

> Also, looking at the shell wrapper it would be preferrable to call exec rather than saving the return code and exiting manually.

Yes definitely.
