### ISSUE TITLE
deno install path/to/target_exe <URL>

### ISSUE THREAD

**Issue by nayeemrmn** [denoland/deno#3969]
I think the syntax `deno install --dir /path/to target_exe` is annoying if you just want to create a local alias. It can be improved by detecting a path separator in the exe name and treating it as a path in that case, just like when running executables in the shell.

`deno install target_exe <URL>` -> `~/.deno/bin/target_exe`
`deno install ./target_exe <URL>` -> `$(pwd)/target_exe`
`deno install path/to/target_exe <URL>` -> `$(pwd)/path/to/target_exe`
`deno install /usr/local/bin/target_exe <URL>` -> `/usr/local/bin/target_exe`

**Comment by ry** [comment]
The difference between path and name is subtle... I wonder if we couldn't come up with a better idea?

What if when you don't specify the "name" but only the URL, you get the shell script printed to stdout. Then users can do `deno install $URL > /usr/local/bin/myprogram.sh` ... I like how this works with bundler.

**Comment by nayeemrmn** [comment]
> Then users can do `deno install $URL > /usr/local/bin/myprogram.sh`

`deno install` takes some args after the URL to pass to the script at runtime. I don't think that exact syntax would always work. Maybe with a `-` in place of the executable name.

But there is an issue with making an "install" command ever do something like that... it seems like it needs to hit the fs.

**Comment by nayeemrmn** [comment]
Closing, we should follow `cargo install`.
