### ISSUE TITLE
Let external modules define their own tsconfig options

### ISSUE THREAD

**Issue by dstaley** [denoland/deno#3975]
I'm one of the contributors to [kinto-http.js](https://github.com/Kinto/kinto-http.js) and would love to provide a version of the library that works with Deno. However, our TypeScript version uses decorators along with TypeScript's `experimentalDecorators` option.

I'd love the ability to somehow let Deno know that this module requires `experimentalDecorators` to be true, without the consuming user having to know this information.

**Comment by kitsonk** [comment]
TypeScript, in their unit test cases, have a lot of comment pragma for impacting the configuration, for example, stuff like this:

```ts
// @module: commonjs
// @skipLibCheck: true
// @includebuiltfile: typescriptServices.d.ts
// @noImplicitAny:true
// @strictNullChecks:true
```

I think a very strict subset of the compiler options would work here, like:

```ts
// @experimentalDecorators: true
```

It feels challenging to require it on a per module basis, so it feels as we analyse the dependencies, we would update the compiler options, and if something asserted a change, but then something else came along with a conflicting change, we would warn, but first pragma in the dependency chain would win.

**Comment by bartlomieju** [comment]
@kitsonk is this something we would consider to implement or is it out of scope?

**Comment by kitsonk** [comment]
In light of the long term direction is potentially eliminate the ability to "adjust" compilation settings, I think this would only cause more code in Deno to not work outside of Deno.  So I think it is something we would consider out of scope.  Respectfully declined.

**Comment by dstaley** [comment]
@kitsonk thank you for the explanation! Based on [these docs](https://deno.land/manual@main/typescript/configuration), am I correct in interpreting that `experimentalDecorators` is actually supported by Deno now? Meaning that third-party TypeScript libraries that use them should work in Deno.

**Comment by kitsonk** [comment]
Yes, it is on by default now. The logic is if you don't use them there is no impact on your code. If you do use them, they will work. We don't emit the decorator meta data by default.

We'll deal with the car crash that will occur when the TC39 Decorators arrives at Stage-3 when that occurs.
