### ISSUE TITLE
testing/mod.ts deletion from master generates testing module download failure

### ISSUE THREAD

**Issue by srackham** [denoland/deno#3976]
Recent repo `testing/mod.ts` deletion results in Deno download failure.

```
$ deno --version
deno 0.32.0
v8 8.1.108
typescript 3.7.2

$ deno test -A tests/
Compile file:///home/srackham/local/projects/drake/.deno.test.ts
Download https://deno.land/std/testing/mod.ts
error: Uncaught Other: Import 'https://deno.land/std/testing/mod.ts' failed: 404 Not Found
► $deno$/dispatch_json.ts:40:11
    at DenoError ($deno$/errors.ts:20:5)
    at unwrapResponse ($deno$/dispatch_json.ts:40:11)
    at sendAsync ($deno$/dispatch_json.ts:91:10)
```

Should Deno download from the repo tag version that matches the version of the Deno executable? e.g. deno 0.32.0 would download from repo tag v0.32.0

**Comment by srackham** [comment]
Dropping `testing/mod.ts` from imports and using the `Deno.test` method generates:

    error TS2339: Property 'test' does not exist on type 'typeof Deno'.

**Comment by bartlomieju** [comment]
Latest release of Deno uses `v0.29.0` of testing module if I'm not mistaken. You can always import specified version manually: `import { test } from "https://deno.land/std@v0.32.0/testing/mod.ts`
Generally it's a good practice to use tagged version

**Comment by srackham** [comment]
@bartlomieju: Thanks, and apologies for the noise, I should have used stackoverflow for this question.

**Comment by magichim** [comment]
@bartlomieju In v0.33, testing/mod.ts is not found.
