### ISSUE TITLE
File.writeSync(buf) - does not write buffer more than 16384 bytes

### ISSUE THREAD

**Issue by balajahe** [denoland/deno#3977]
When a buffer is writting to a file synchronously, a buffer larger than 16384 is truncated without warning and is not written to the file! 

deno 0.32.0
v8 8.1.108
typescript 3.7.2

Code Example:
`const buf_size = 40960 //4096 - standard value //16384 - max allowed value !!!
const buf = new Uint8Array(buf_size)
buf.fill(0x31)

const fn = './deno_file_write_bug.txt'
const f = Deno.openSync(fn, 'w')
f.writeSync(buf)
f.close()

const fi = Deno.lstatSync(fn)
console.log(fi.len === buf_size ? true : fi.len)`

https://gist.github.com/balajahe/d530a48e647cd00bc9cc05c5231b8846

**Comment by afinch7** [comment]
If this is considered a bug then should writeSync always write the entire buf no matter how long. This might cause issues if the length of the buf overflows the shared queue. This would also seem to make the return of number of bytes written kinda pointless. If we expect we may have to call write multiple times to write the entire buf implementations might look something like this instead:
```
const buf_size = 40960 //4096 - standard value //16384 - max allowed value !!!
const buf = new Uint8Array(buf_size)
buf.fill(0x31)

const fn = './deno_file_write_bug.txt'
const f = Deno.openSync(fn, 'w')
let bytesWritten = 0;
let bytesView = new Uint8Array(buf.buffer, bytesWritten, buf.buffer.byteLength - bytesWritten);
while (true) {
  console.log("Bytes left at cycle start: ", buf.byteLength - bytesWritten);
  const written = f.writeSync(bytesView)
  console.log("Write cycle written: ", written);
  bytesWritten = bytesWritten + written;
  if (bytesWritten == buf.byteLength) {
    break;
  }
  bytesView = new Uint8Array(buf.buffer, bytesWritten, buf.buffer.byteLength - bytesWritten);
}
console.log("Bytes written: ", bytesWritten);
f.close()

const fi = Deno.lstatSync(fn)
console.log(fi.len === buf_size ? true : fi.len)
```
I may be wrong, but I believe this is a limitation of the implementation of rust's `std::fs::File`.

**Comment by ry** [comment]
oops I thought this was about writeFileSync... You're right @afinch7.

@balajahe - write is a low-level I/O call and it does not guarantee the whole buffer will be written. Have a look at `Deno.writeAllSync()` https://deno.land/typedoc/index.html#writeallsync

**Comment by balajahe** [comment]
@ry - you are completely right, but then this feature should be reflected in the documentation !
https://deno.land/typedoc/index.html#writesync

**Comment by ry** [comment]
@balajahe Maybe it could be more explicit but doesn't "Resolves with the number of bytes written" suggest that it might not write the complete buffer? What would you have it say?

**Comment by balajahe** [comment]
I hope in the future the documentation will be written in more detail !
