### ISSUE TITLE
Deno.run clean environment

### ISSUE THREAD

**Issue by brandonkal** [denoland/deno#3981]
Deno.run inherits environment from the parent process. I'd love to see something like this:
```ts
Deno.run({
	args: ['printenv'],
	clean: true,
	env: {
		ENV_1: 'yes',
	},
})
```

This would mean only explicit environment variables would exist. Not unlike
```sh
$ env -i ENV_1=yes sh -c printenv
PWD=/path
ENV_1=yes
```
Doing the above is possible but not as elegant.

**Comment by bartlomieju** [comment]
Possibly: https://doc.rust-lang.org/std/process/struct.Command.html#method.env_clear
