### ISSUE TITLE
Use swc to expose an AST to the runtime

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#3983]
We include the swc crate as part of the dprint crate in order to power `deno fmt`.  We should consider exposing swc to provide a runtime AST for JavaScript and TypeScript files.  While we can't use the AST (yet) to drive the compiler, it would be a useful API to have in runtime to enable innovative solutions, like AST manipulation.

**Comment by axetroy** [comment]
This APIs should be helpful for `code Transform`/`style lint and more.

No need to rely on node.js

But I think it might be better to expose the typescript interface

**Comment by kitsonk** [comment]
> typescript provides a series of AST operations

But the AST is not serializeable (see: microsoft/TypeScript#33502)... it is highly self referential and it is not really that easy to work with compared to things like estree like ASTs.  I don't know what sort of AST swc generates, but it is worth looking at.  If it is easy to serialize to JSON, then it will be better, and longer term Ry and I have talked about taking that AST and feeding it to the compiler, because the parsing is orders of magnitude faster than the compiler.  So starting to work with it in the runtime helps us all start to move that direction.

**Comment by bartlomieju** [comment]
https://github.com/denoland/deno/issues/2355#issuecomment-719522155
