### ISSUE TITLE
BUG: Outdated types on script runtime

### ISSUE THREAD

**Issue by hazae41** [denoland/deno#3984]
Hello, I modified Deno for PR https://github.com/denoland/deno/pull/3946 and built it (in debug and release mode). Then I tried it with different runtimes: REPL, JS script, TS script.

The problem occurs on the updated type:

    type Transport = "tcp";

which is now

    type Transport = "tcp" | "udp";

And this is the line I tried to run on each runtime:

    Deno.listen({ port: 80, transport: "udp" })

Here are my results:
- When I try to use the new type on the REPL, it works well.
- Same when I try to use it on a JS script, it works fine too.
- But when I try to use it in a TS script, it seems the types are still those of the normal version of Deno, not the modified one. So using "udp" as a Transport throws the following error:
    `"udp" is not assignable to Transport`

Maybe I did something wrong? Or the TS runtime is not updating modified types?

**Comment by bartlomieju** [comment]
@hazae41 https://github.com/denoland/deno/pull/3946#discussion_r378537954
