### ISSUE TITLE
[Doc] Contributing instruction manual outdated

### ISSUE THREAD

**Issue by saostad** [denoland/deno#3986]
I saw some issues in contributing instruction in manual:
[contributing for windows users](https://github.com/denoland/deno/blob/master/std/manual.md#prerequisites) is outdated, we should update Prerequisites for windows users:
- [Visual Studio Community](https://visualstudio.microsoft.com/vs/community/) include (C++ tools needed for build [rusty_v8](https://github.com/denoland/rusty_v8)):
  - Visual C++ tools for CMake
  - Windows 10 SDK (10.0.17763.0)
  - Testing tools core features - Build Tools
  - Visual C++ ATL for x86 and x64
  - Visual C++ MFC for x86 and x64
  - C++/CLI support
  - VC++ 2015.3 v14.00 (v140) toolset for desktop
- Enable "Debugging Tools for Windows" [Debugging Tools for Windows](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/) (Notice: it will download the files, you should install `X64 Debuggers And Tools-x64_en-us.msi` file manualy.) 

Also test folders moved to cli folder so: 
`./target/debug/deno tests/002_hello.ts`
should change to: 
`./target/debug/deno cli/tests/002_hello.ts`

another problem: there is no guide for in-editor linting! should I remove VSCode Eslint plugin and just use `./tools/lint.py` ?

we should also mention it need to [install Deno in the system](https://github.com/denoland/deno_install)

**Comment by tokiedokie** [comment]
This seems done in #4027
