### ISSUE TITLE
Property 'test' does not exist on type 'typeof Deno'.ts(2339)

### ISSUE THREAD

**Issue by saostad** [denoland/deno#3987]
in test files everywhere `Deno.test()` exist. typescript errors: `Property 'test' does not exist on type 'typeof Deno'.ts(2339)`

Windows 10
VSCode: 1.42.0
Plugin Deno installed!

```
Found deno, version:
deno: 0.32.0
v8: 8.1.108
typescript: 3.7.2
```

I took a look at `lib.deno.runtime.d.ts` file and couldn't find function def for `test()` !

**Comment by bartlomieju** [comment]
Hey @saostad, `Deno.test()` will be available in the next release. The error is most likely caused by `std` import that is not pinned to specific version. 

Try using latest released `std`:
```
import { serve } from "https://deno.land/std@v0.32.0/http/server.ts
```

**Comment by bartlomieju** [comment]
Deno v0.33.0 was released so `Deno.test()` will be available in type declarations.

**Comment by metacoding** [comment]
The folowin example is copied from Deno.land website (Manual -> Assertions) and throws the same error.
Please update the document as well

```import { assert } from "https://deno.land/std/testing/asserts.ts";

Deno.test("Hello Test", () => {
    assert("Hello");
});

**Comment by bartlomieju** [comment]
@metacoding are you sure your Deno binary is up to date?
