### ISSUE TITLE
Server request error handling, is this correct?

### ISSUE THREAD

**Issue by nayeemrmn** [denoland/deno#3992]
https://github.com/denoland/deno/blob/621aeef8364fcbd2da93b208971c51a4fbf08903/std/http/server.ts#L442-L475

Let's say `readRequest()` fails, then the binding to `req` is not made and `err` is set. The loop breaks and we eventually reach the error handling. So which `req` are we sending `400` to? Isn't that the previous request, which was good and yielded to the user?

cc @bartlomieju

**Comment by nayeemrmn** [comment]
If `readRequest()` refuses to return a malformed request, it should be internally responsible for responding.

**Comment by bartlomieju** [comment]
@nayeemrmn I have a growing feeling that `std/http/server.ts` needs a rewrite - it doesn't handle server shutdown as well and that problem is also related to `readRequest`.
