### ISSUE TITLE
Support HTTP/2, HTTP/3 and QUIC in HTTP server

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#3995]
This was discussed over in denoland/deno_std#153 but was locked during the move.

While we still have concerns around the HTTP server, we should also consider supporting HTTP/2, HTTP/3 and QUIC.

**Comment by hazae41** [comment]
https://github.com/denoland/deno/issues/1558

**Comment by ry** [comment]
So it's quite likely that we will expose native HTTP server. 

Getting these protocols correct is very difficult - it's better to collaborate with other Rust users. We will probably use `warp`.

The reason why we have `std/http` and not a native HTTP server is because we're still working out the kinks in the "op model". In our benchmarks deno_tcp is still slower than node_tcp

![3c49cb](https://user-images.githubusercontent.com/80/75262634-ce021d00-57ba-11ea-8b1c-87a94fe15b06.png)

I want to fix that first before adding the native HTTP since it will be built on top of the same primitives.

**Comment by hcldan** [comment]
@ry Is there a ticket for those performance benchmarks or any schedule for when it might make it in?

**Comment by Justsnoopy30** [comment]
What's the status on http/2 support in Deno?

**Comment by kitsonk** [comment]
The issue is open. That indicates that it isn't resolved yet.

**Comment by Justsnoopy30** [comment]
> The issue is open. That indicates that it isn't resolved yet.

Well yes, I can see that. What I meant was, how much progress has been made on this?

**Comment by kitsonk** [comment]
Any progress would be mentioned in this issue.

**Comment by Dygear** [comment]
[Apple Push Notification Service](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/sending_notification_requests_to_apns) is going to require HTTP/2 starting April 1st 2021. Looking over their documentation, it's acceptable to keep a long standing connection to their servers, but requires a `PING FRAME` about every hour to be sent. So whomever does end up landing HTTP/2, can they please add to option to sending these frames manually, it would be of great help.

**Comment by lucacasonato** [comment]
@Dygear This is client to sever communication, right? The API for that is `fetch` and it already supports HTTP/2.

**Comment by ry** [comment]
We are working on hyper bindings and hope to have them complete for v1.9

**Comment by anonrig** [comment]
Hi! I'm a maintainer from mali (GRPC microservice framework) and wanted to stay in the loop. We're currently investigating supporting Deno in Mali. If you're interested in this support, please send us a message from https://github.com/malijs/mali/issues/241

**Comment by badsyntax** [comment]
@anonrig also refer to https://github.com/denoland/deno/issues/3326 for additional discussions about grpc in Deno

**Comment by rektide** [comment]
PR #9935 is (i believe) a start on those Hyper bindings @ry mentioned!

worth pointing out that Hyper itself is still [working on HTTP/3](https://github.com/hyperium/hyper/issues/1818), via a subproject. most of those efforts are currently going in to an [h3 library](https://github.com/hyperium/h3/), is my understanding.

**Comment by ynwd** [comment]
> We are working on hyper bindings and hope to have them complete for v1.9

@ry @kitsonk @lucacasonato 
is it possible to change these bindings dynamically - using the fastest rust framework?

<img width="1176" alt="Screen Shot 2021-04-07 at 11 15 55" src="https://user-images.githubusercontent.com/10122431/113809611-b3a6bb00-9792-11eb-862f-756a0f0f4fb5.png">

https://www.techempower.com/benchmarks/#section=data-r20&hw=ph&test=fortune&l=yyku7z-sf

**Comment by bartlomieju** [comment]
No, the bindings use `hyper` and it can't be changed.

**Comment by ry** [comment]
HTTP/2 shipped in v1.9.0 (see #9935)

HTTP/3 and QUIC can be discussed in a new issue.

**Comment by waldyrious** [comment]
> HTTP/3 and QUIC can be discussed in a new issue.

There is #1558 which was closed as a duplicate (subset) of this one. Maybe it should be reopened, @kitsonk?

**Comment by trivikr** [comment]
> There is #1558 which was closed as a duplicate (subset) of this one. Maybe it should be reopened

The issue https://github.com/denoland/deno/issues/1558 was opened.

**Comment by einicher** [comment]
Has someone implemented http2 yet?  As far is I understand [this](https://deno.com/blog/v1.9#native-http%2F2-web-server) release notes and the example below, someone needs to create something like https://deno.land/std@0.95.0/http/server.ts so we can use that. I guess conn needs to be listened to with read and write buffer? I read in an article http2 makes parallel requests possible, which makes bundlers mostly unnecessary for es imports in browser. Thats why I am interested.
```js
const body = new TextEncoder().encode("Hello World");
for await (const conn of Deno.listen({ port: 4500 })) {
  (async () => {
    for await (const { respondWith } of Deno.serveHttp(conn)) {
      respondWith(new Response(body));
    }
  })();
}
```
