### ISSUE TITLE
Dynamic import requires file access permissions 

### ISSUE THREAD

**Issue by fakoua** [denoland/deno#4003]
Hi,
Consider the following imports, 
`import t from "f.ts"`
And
`let t = await import("f.ts")`

Technically, both syntax access the file system, but the dynamic import requires the file access flag to be set. 

It confuses the backend user, while the application may not need that permission.

Please advise. 
Thanks

**Comment by nayeemrmn** [comment]
@fakoua See #2761. It definitely does need read permissions for local modules and especially net permissions for remote modules.

**Comment by fakoua** [comment]
Many thanks.
