### ISSUE TITLE
How should universal modules import dependencies?

### ISSUE THREAD

**Issue by YarivGilad** [denoland/deno#4008]
Hi all, quick question - any ideas on how to run universal modules with Deno on the server and typescript on the client? 
My use-case involves a universal/SSR react app with typescript.
Some of the modules are being run both on the server and the client so on the server, I'm supposed to reach out to a URL and get them, while the same module when built with tsc or babel, is expected to reach out to the local node_modules folder for modules... how can this conflict be resolved?

**Comment by lucacasonato** [comment]
Import maps can be a solution to this problem: https://deno.land/std/manual.md#import-maps

**Comment by lucacasonato** [comment]
Questions like these should be asked on Discord: https://discord.gg/deno. The issue tracker is for bugs and feature requests, not questions.
