### ISSUE TITLE
Deno resolves `require` at build time

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#4013]
```typescript
declare function require(mod: string): any;

const { serve } = require("https://deno.land/std@v0.33.0/http/server.ts");
const s = serve({ port: 8000 });
console.log("http://localhost:8000/");
for await (const req of s) {
  req.respond({ body: "Hello World\n" });
}
```

Placing this code in a **typescript** file called `xyz.ts` and running `deno --reload xyz.ts`, makes deno download `https://deno.land/std@v0.33.0/http/server.ts` and all of its dependencies. The code does crash during execution because `require` is not defined.

This seems to be caused by the typescript compiler resolving require() calls at build time. That should not happen.

/cc @kitsonk

**Comment by kitsonk** [comment]
@lucascaro are you working off master?  #4009 should have fixed that.

**Comment by lucascaro** [comment]
@lucacasonato ^ ;)

**Comment by kitsonk** [comment]
Apologies.  Darn auto-complete.

**Comment by lucacasonato** [comment]
Ahh no. I was using v0.33.0. Thanks!
