### ISSUE TITLE
Inconsistent camel case usage in Deno API

### ISSUE THREAD

**Issue by cknight** [denoland/deno#4021]
The Deno API seems to have inconsistent casing where multiple words are involved.  

One pattern (majority of the API) uses camel case:

> applySourceMap
copyFile
copyFileSync
execPath
makeTempDir
etc.

The other pattern does not strictly use camel case:

> readlink
realpath
realpathSync
readdir (proposed)
readdirSync (proposed)

My preference would be for consistent camel case usage throughout (top pattern above), but very open to discussion as well.  It feels odd to `readFile`, but then `readdir` for example.

**Comment by dubiousjim** [comment]
readdir is the name of the underlying libc call; and so it's what e.g. Node and Python also use. Same with readlink, realpath. I think the pattern is to use camelCase except when there's an existing well-known api that doesn't. Hence mkdir but makeTempDir.

**Comment by cknight** [comment]
Fair points, and as operating system commands `mkdir` and `shutdown` make sense to remain 'as is', but I wonder if Deno should conform to underlying libc naming conventions which most users won't be familiar with (though Node and Python familiarity are reasonable points to consider).  

Go uses Pascal case, but interestingly, they are also inconsistent.  For example, their read directory interface is not `Readdir` but [ReadDir](https://golang.org/pkg/io/ioutil/#ReadDir), however they also have [Readlink](https://golang.org/pkg/os/#Readlink) instead of `ReadLink`.

**Comment by cknight** [comment]
Researching this more, realpath and readlink are both common terms in the Unix space (in all lowercase) so this makes sense to keep as originally spec'd I guess.  Read directory is more mixed:

Deno:  readDir (current) and readdir (proposed)
Node:  readdir
Python: readdir
Go:  ReadDir
Rust: read_dir function and ReadDir struct

**Comment by kevinkassimo** [comment]
To be fair I kind of think `readdir/readDir` `readlink/readLink` is not that much an issue, but I indeed do not like the fact that `makeTempDir` and `mkdir` differs too much.

**Comment by lucacasonato** [comment]
> (Reminding me that we also don't have `mktemp` for files yet)

I think that should be called `createTemp` though as the call to create a non temp file is `Deno.create`

**Comment by cknight** [comment]
As this has had no traction in the last week I'm happy to close.  Feel free to reopen if this debate is useful.
