### ISSUE TITLE
std: is testing/format.ts needed?

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#4023]
It seems that `std/testing/format.ts` is only used to provide pretty-printed diffs for assertions. 

Does is really need to be a separate module or could it be handled just by "console" stringification?
Granted, current console stringification is half-baked (ref #3277), but once related PR lands we could get away without this module?

**Comment by bartlomieju** [comment]
Stale, still used in `std/testing/asserts.ts`

**Comment by nayeemrmn** [comment]
This should still be considered, i.e. replace `format()` calls in `std/testing/asserts.ts` with `Deno.inspect()`.

I wrote a little module comparing respective outputs for some primitives:
```js
import { format } from "https://deno.land/std@v0.40.0/testing/format.ts";

for (
  const v of [
    1,
    "abc",
    function def() {
      console.log("hello");
    },
    [1, 2, 3, 4, 5, 6, 7, 8],
    {
      aaaaaa: 1,
      bbbbbb: 1,
      ccccc: 2,
      dddddd: 1,
      eeeeeee: 2,
      fffffff: 1,
      gggg: 2,
      hhh: 1,
      iiiiiii: 2,
    },
  ]
) {
  console.log(format(v));
  console.log(Deno.inspect(v));
}
```
```
1
1
"abc"
abc
[Function def]
[Function: def]
Array [
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
]
[
  1, 2, 3, 4,
  5, 6, 7, 8
]
Object {
  "aaaaaa": 1,
  "bbbbbb": 1,
  "ccccc": 2,
  "dddddd": 1,
  "eeeeeee": 2,
  "fffffff": 1,
  "gggg": 2,
  "hhh": 1,
  "iiiiiii": 2,
}
{
 aaaaaa: 1,
 bbbbbb: 1,
 ccccc: 2,
 dddddd: 1,
 eeeeeee: 2,
 fffffff: 1,
 gggg: 2,
 hhh: 1,
 iiiiiii: 2
}
```
Nothing `format()` does clearly better since #3277 landed. We should get rid of it.

**Comment by bartlomieju** [comment]
@nayeemrmn thanks for clear comparison! @mhvsa did some updates to formatting recently as well. If we could remove `std/testing/format.ts` that would be great; if I'm not mistaken it causes `std/testing/assert.ts` to pull a lot of code.
