### ISSUE TITLE
[request]Can 0.34.0 be release now?

### ISSUE THREAD

**Issue by FedericoMorrone** [denoland/deno#4033]
I wouldn't want to ask this but can we get 0.34.0 or maybe 0.33.1 right now, because so many bugs have been fixed expecially #3852, without that bug fixed many machines mostly on Windows modules can't be imported there for making it impossible to use deno, I'm really looking forward to this project but I can't contribute if I can't even use it and compiling is not visible nor easy task

<em>pls forgive any grammar mistakes</em>

**Comment by Soremwar** [comment]
I would build it manually, since we can't actually say Deno is production ready.

And this bug was fixed like 2 hours ago, don't expect it to work right away, maybe some other bug that wasn't foreseen will pop up due to the complexity of the Deno ecosystem.

**Comment by bartlomieju** [comment]
We'll release `v0.34.0` after `rusty_v8` upgrade. Probably today/tomorrow
