### ISSUE TITLE
Deno.sh domain

### ISSUE THREAD

**Issue by JerryGreen** [denoland/deno#4044]
Isn't it your guys domain? I'm pretty much sure it was mentioned somewhere, maybe in youtube vids or something, at very starting point, but now it leads to some non-existing repo:

https://github.com/zhmushan/deno.sh

Funny fact: it has higher priority in my browser than deno.land lol (I know I may clear the history regarding deno.sh, so it's not what's the issue about).

Maybe it's good idea to setup redirection of deno.sh to deno.land.

Though I, personally, think deno.sh name is better than deno.land. Though "deno land" may sound quite funny, but deno.sh sounds more relevant since it's shell command (like [now.sh](https://now.sh)).

Btw, I don't want to force anyone to using it or whatever, I'm pretty much hate the situation of top level domains. Just asking...

**Comment by kitsonk** [comment]
I don't believe we ever controlled that domain, nor officially used it in any capacity.

**Comment by JerryGreen** [comment]
Well, maybe it's a good idea to ask this guy... @zhmushan, is that your domain? Wanna donate it to Deno?

**Comment by kevinkassimo** [comment]
@zhmushan has been a long time contributor to Deno and related projects (e.g. https://github.com/zhmushan/abc). I believe he is recently very busy with his personal stuff. I can contact him and see what he thinks, but I believe we should not force him.

Worth mentioning deno.dev is also owned by another Deno contributor.

**Comment by JerryGreen** [comment]
Yea, I don't mean to force anyone. We are not like some russian police here, to privatise some businesses.

What I'm saying that this domain is IMO cool, and much cooler than deno.land. And yet, it's not used for anything useful (wrongly redirects to non-existing page).

I mean, did you even know "land" domain even existed before Deno? I always forget what's there after the dot and have to google it, rather to make a direct hit.

If Mu Shan is okay to giveaway domain, then it makes sense to maybe ask Ryan: "Hey Ryan, what do you think about using deno.sh, isn't it cooler, huh?" and maybe to use it as main domain.

**Comment by kitsonk** [comment]
I personally like `deno.land`, I don't personally thing `.sh` domains are cooler.

**Comment by zhmushan** [comment]
Hi, i'm here, very sorry for being late. In the beginning, I used deno.sh to serve my personal private projects, without considering its impact. If the community needs this domain name, I am willing to transfer it for free.

**Comment by dplewis** [comment]
Speaking of domains, there is `deno.land`, `deno.town`, I have `demo.city`. It not used for anything but I’m planning my first deno project for it. Always open to suggestion

**Comment by JerryGreen** [comment]
Hey @ry, what do you think about using deno.sh, isn't it cooler, huh? Here’s person to donate this domain.

Maybe even consider it as main domain? You know, shell, sh, deno.sh.

**Comment by kitsonk** [comment]
Or some place in St. Helena I've never heard of.

**Comment by sholladay** [comment]
Unfortunately, with the web being the way it is, I think if you don't grab as many TLDs as possible, you may regret it later. `deno.sh` is shorter and gives a slight hint that it's a software project.

**Comment by ry** [comment]
deno.land will remain the official domain
