### ISSUE TITLE
Segmentation fault: 11 on websocket

### ISSUE THREAD

**Issue by clemens-tolboom** [denoland/deno#4047]
Following the client and server examples in https://deno.land/std/ws/README.md (from PR #4046) I created a 10 clients test.

Start server

```
deno --allow-net server.ts 9999
```

Start client

```
deno --allow-net client.ts ws://127.0.0.1:9999
```

Test file `client.txt` contains

```
hello from client.txt
line 2
line 3
line 4
line 5
line 6
line 7
line 8
line 9
close
```

then

```
cat client.txt | deno --allow-net client.ts ws://127.0.0.1:9999
```

When running `10clients.bash`

```
#!/usr/bin/env bash

(cat client.txt | deno --allow-net client.ts ws://127.0.0.1:9999) &
(cat client.txt | deno --allow-net client.ts ws://127.0.0.1:9999) &
(cat client.txt | deno --allow-net client.ts ws://127.0.0.1:9999) &
(cat client.txt | deno --allow-net client.ts ws://127.0.0.1:9999) &
(cat client.txt | deno --allow-net client.ts ws://127.0.0.1:9999) &
(cat client.txt | deno --allow-net client.ts ws://127.0.0.1:9999) &
(cat client.txt | deno --allow-net client.ts ws://127.0.0.1:9999) &
(cat client.txt | deno --allow-net client.ts ws://127.0.0.1:9999) &
(cat client.txt | deno --allow-net client.ts ws://127.0.0.1:9999) &
(cat client.txt | deno --allow-net client.ts ws://127.0.0.1:9999) &
```

everything is fine.

### segfaults

Repeating invocation of `10clients.bash` manually or Increasing the size of `client.txt` then server dies with `Segmentation fault: 11`

**Comment by clemens-tolboom** [comment]
Trying to manually flood I failed. But pressing `CTLR-C` in the client made the server say

> failed to receive frame: UnexpectedEOFError: Unexpected EOF

Not sure whether that indicated another issue with WS module?

**Comment by keroxp** [comment]
@clemens-tolboom That situation also occurred  in my machine (macOS). But there're no hints about what happened. I added `RUST_BACKTRACE=1` but no trace info shown after segfault. It means deno itself didn't panic. It seems to be thrown by OS? 

> failed to receive frame: UnexpectedEOFError: Unexpected EOF

This is undesirable behaviour of WebSocketImpl. It occurs when socket fails to read frame from client because sock may be closed without close frame.

**Comment by clemens-tolboom** [comment]
I'm on MacOS too. I did not manage to dtrace so cannot produce more info either :(

**Comment by bartlomieju** [comment]
In #4149 we fixed a segfault that was most likely the same root cause in this issue. @clemens-tolboom could you verify if you still get the segfault with `v0.35.0`?

**Comment by clemens-tolboom** [comment]
Hmmm ... I'm using HomeBrew ... when reporting I learned I was using `0.33.0`. Now `brew upgrade deno` gave me `0.34.0` which is not latest :-( ... I've to wait for homebrew to give me latest.

**Comment by bartlomieju** [comment]
@clemens-tolboom that might not be possible: https://github.com/denoland/deno_install/issues/93#issuecomment-592960983

Can you try with manual installation? https://github.com/denoland/deno_install

**Comment by clemens-tolboom** [comment]
I can confirm `v0.34.0` is working properly. Which is weird but I **failed to crash** the server.

The server logs loosing a client but that is another issue and still a `FIXME` in https://deno.land/std/ws/README.md

Guess we can close this now unless the relation with https://github.com/denoland/deno/issues/4047#issuecomment-592948874 still stands

**Comment by clemens-tolboom** [comment]
I'm on Mac ... guess https://github.com/denoland/deno_install/issues/93 is not applicable to Mac right?

**Comment by clemens-tolboom** [comment]
Hmmm ... I guess I didn't understand `LinuxBrew` equals `MacOs` as I never save the (new?) tagline of https://brew.sh

> The Missing Package Manager for macOS (or Linux)

Long story short .... v0.35.0 has no problems either.

Closing

**Comment by clemens-tolboom** [comment]
FWIW in did install 0.35 manually first which in a way was nice to know and helped versions test.

- grab the release from https://github.com/denoland/deno/releases
- Download the .gz or .zip
- Unpack and rename (I made it `deno`)
- Move it into your shell bin path (I have `~/lib/deno-0.35/deno` which was linked from `~/bin/deno`)
