### ISSUE TITLE
Add Deno.delay as promise version of setTimeout

### ISSUE THREAD

**Issue by ry** [denoland/deno#4052]
```
async function delay(ms: number): Promise<void> {
  const promise = createResolvable();
  setTimeout(() => {
    promise.resolve();
  }, ms);
  return promise;
}
```

**Comment by nayeemrmn** [comment]
Only slightly better than `new Promise(r => setTimeout(r, ms))`.

Is it okay to encourage something non-portable for a trivial high-level convenience? I don't know if this is a good idea, at least with what I understand to be Deno's current set of philosophies.

**Comment by hayd** [comment]
This is in std:

https://github.com/denoland/deno/blob/a0d3b4ebc509d9e5dfca555084fd1100e114664a/std/util/async.ts#L110-L117

**Comment by ry** [comment]
Yeah @nayeemrmn make a good point...

**Comment by UrielCh** [comment]
The up to date version:

```bash
deno add jsr:@std/async
```

```typescript
import { delay } from "@std/async/delay";

await delay(100); // waits for 100 milliseconds
```
[JSR](https://jsr.io/@std/async)
