### ISSUE TITLE
move close op to `io` ops

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#4059]

**Comment by ry** [comment]
it should be with the resources ops

**Comment by bartlomieju** [comment]
> it should be with the resources ops

Right, that's `ops/io.rs`. 

Also `ops/files.rs` makes no sense - `open` and `seek` are strictly for files - so they should be moved to `ops/fs.rs`

**Comment by ry** [comment]
Also cli/ops/resources.rs

**Comment by ecyrbe** [comment]
In the same kind of questions, as i'm making std/node/fs polyfill i need to add fchmod/fchown... 
They all take files descriptors... and rust op/fs.rs as none for the moment. Should i put these anyway in  fs.rs or in ops/io.rs or another one ?

**Comment by dubiousjim** [comment]
@ecyrbe, I've implemented fchmod/fchown already, will be posting PR probably tomorrow. See #4017

**Comment by dubiousjim** [comment]
Sorry, just did fchmod. fchown is not available in the nix Rust crate. You'd have to do `unsafe` calls into the libc crate.

**Comment by cknight** [comment]
> as i'm making std/node/fs polyfill

@ecyrbe which bit of the std/node/fs polyfill are you working on?  Sounds like we might both be working on it.  My progress to date can be seen in #4087

**Comment by ecyrbe** [comment]
oh! a chance i only made chown/fchown/fchmod. i'll let you advance before adding anything more for fs node module. i'll finish node/os module instead.

**Comment by cknight** [comment]
No worries.  I have no rust experience so am limited to implementing what is available already in Deno.  Any help is most welcome, just wanted to make sure we didn't both complete the same thing!
