### ISSUE TITLE
Fix UDP tests on Windows

### ISSUE THREAD

**Issue by ry** [denoland/deno#4066]
This shouldn't be too hard, the backend implementation (tokio) supports Windows. This just requires someone with a Windows machine to try disabling these TODOs and debugging what exactly is happening...

https://github.com/denoland/deno/blob/08686cbc3ae63008837ee45b2c4f41d6674c57dd/cli/js/net_test.ts#L13

https://github.com/denoland/deno/blob/08686cbc3ae63008837ee45b2c4f41d6674c57dd/cli/js/net_test.ts#L94

https://github.com/denoland/deno/blob/08686cbc3ae63008837ee45b2c4f41d6674c57dd/cli/js/net_test.ts#L133

**Comment by hazae41** [comment]
Everything works well on my virtualized Windows 10

Maybe it's a problem with the machine used in Github Actions?

**Comment by hazae41** [comment]
First bug

    FAIL netUdpListenClose
    PermissionDenied: Une tentative d’accès à un socket de manière interdite par ses autorisations d’accès a été tentée. (os error 10013)
    at Object.constructError ($deno$/errors.ts:39:13)
    at unwrapResponse ($deno$/dispatch_json.ts:41:12)
    at Object.sendSync ($deno$/dispatch_json.ts:70:10)
    at Object.listen ($deno$/net.ts:255:15)
    at Object.netUdpListenClose [as fn] ...

Translated 

    An attempt was made to access a socket in a manner prohibited by its access permissions.

The second one

    FAIL  netUdpSendReceive
    AddrInUse: Une seule utilisation de chaque adresse de socket (protocole/adresse réseau/port) est habituellement autorisée. (os error 10048)
    at Object.constructError ($deno$/errors.ts:49:13)
    at unwrapResponse ($deno$/dispatch_json.ts:41:12)
    at Object.sendSync ($deno$/dispatch_json.ts:70:10)
    at Object.listen ($deno$/net.ts:255:15)
    at Object.netUdpSendReceive [as fn] ...
    
Translated
   
    Only one use of each socket address (protocol/network address/port) is usually allowed.

**Comment by hazae41** [comment]
netUdpListenCloseWhileIterating works well

**Comment by hazae41** [comment]
I managed to not have errors by changing ports used.

	testPerm({ net: true }, function netUdpListenClose(): void {
	  //if (Deno.build.os === "win") return; // TODO

	  const socket = Deno.listen({
		hostname: "127.0.0.1",
		port: 4600,
		transport: "udp"
	  });
	  assertEquals(socket.addr.transport, "udp");
	  assertEquals(socket.addr.hostname, "127.0.0.1");
	  assertEquals(socket.addr.port, 4600);
	  socket.close();
	});

	testPerm({ net: true }, async function netUdpSendReceive(): Promise<void> {
	  if (Deno.build.os === "win") return; // TODO

	  const alice = Deno.listen({ port: 4601, transport: "udp" });
	  assertEquals(alice.addr.port, 4601);
	  assertEquals(alice.addr.hostname, "0.0.0.0");
	  assertEquals(alice.addr.transport, "udp");

	  const bob = Deno.listen({ port: 4602, transport: "udp" });
	  assertEquals(bob.addr.port, 4602);
	  assertEquals(bob.addr.hostname, "0.0.0.0");
	  assertEquals(bob.addr.transport, "udp");

	  const sent = new Uint8Array([1, 2, 3]);
	  await alice.send(sent, bob.addr);

	  const [recvd, remote] = await bob.receive();
	  assertEquals(remote.port, 4601);
	  assertEquals(recvd.length, 3);
	  assertEquals(1, recvd[0]);
	  assertEquals(2, recvd[1]);
	  assertEquals(3, recvd[2]);
	});

But netUdpSendReceive still freezes

**Comment by hazae41** [comment]
It seems that, on Windows, sending to a local port freezes when the port is not yet open.

Therefore, the following code:

    await send()
    await receive()

is blocking at `await send()`

Alternatively, the following code

    await receive()
    await send()

is blocking at receive() since the data is sent after

Thus, I think the only solutions would be:
- to disable netUdpSendReceive()
- to use another machine in order to send/receive

**Comment by piscisaureus** [comment]
What about simply:

await Promise.all([await receive(), await send()]);

**Comment by hazae41** [comment]
> What about simply:
> 
> `await Promise.all([receive(), send()]);`

This didn't work

**Comment by JerryGreen** [comment]
So basically there's no support for UDP on Windows yet?
