### ISSUE TITLE
Expose zlib ops

### ISSUE THREAD

**Issue by hazae41** [denoland/deno#4071]
How can I expose zlib ops from rusty_v8 to deno?

**Comment by kitsonk** [comment]
The path wouldn't be from rusty_v8.  zlib is available in the Rust side of the `deno` crate.  What needs to occur is an op from the runtime to a Rust function in the Deno crate that will handle the compression and decompression.

I think we need a bit of agreement on what the API should look like.  In Go, compression like zlib uses the `Reader` and `Writer` type of interfaces.  On the other hand, the web standards tend more towards the encoder/decoder type of concept, with no ability for back pressure (ref: `TextEncoder`).

Also, there is the consideration of actual use cases... lets say you have a file or a network connection that is encoded with a particular type of compression... you would want to op from Rust into JavaScript to just send it back via an op to Rust to be uncompressed... so how would we efficiently pipeline those activities?

**Comment by hazae41** [comment]
For the API, I propose to use ZlibEncoder/ZlibDecoder that takes an Uint8Array and some params, and ZlibWriter/ZlibReader classes that encapsulates a Writer/Reader and exposes read/write functions

    class ZlibEncoder(options)
        encode(Uint8Array): a new Uint8Array
    
    class ZlibDecoder(options)
        decode(Uint8Array): a new Uint8Array
    
    class ZlibReader(Reader, options)
        read(Uint8Array): number of bytes written

    class ZlibWriter(Writer, options)
        write(Uint8Array): number of bytes written

For the Rust<->Deno pipeline, we would just use ZeroCopyBufs

**Comment by ry** [comment]
zlib could come from rusty_v8. It's (perhaps surprisingly) a dependency of V8 https://github.com/denoland/rusty_v8/tree/master/third_party

https://github.com/v8/v8/blob/fc55d73343611998e5d816168f363bb18e365a1b/BUILD.gn#L3455-L3458

However it doesn't seem like we're getting any of the symbols exposed in the executable:
```
> nm target/debug/deno |  grep deflateInit
>
```

I see that we already have `brotli` as a dep crate in `deno` (`reqwest -> async-compression -> brotli`). So I guess we can just add that as a top-level dependency.

Before we discuss the JS API, I think we just need some basic ops. We need to be able to stream data through an enflat / deflate operation - so there should be a resource created (maybe `op_brotli_open`?) and then the `op_read` and `op_write` ops should be used to interface with inputs/outputs.

I suggest looking at the recent `Deno.fsEvents()` patch as an example of how to add ops: https://github.com/denoland/deno/commit/bd640bc7e6a946dec4477afc64d8083e372660f6#diff-1b7b1dd267c7dde02fa12421be0eb6d0

**Comment by hazae41** [comment]
How about https://github.com/image-rs/inflate or https://github.com/sile/libflate ?

**Comment by hazae41** [comment]
bump

**Comment by kitsonk** [comment]
@hazae41 why are you bumping... Ry expressed that anyone interested in this should use `zlib` from `rusty_v8` versus introducing a new crate.

**Comment by hazae41** [comment]
Let's do it

**Comment by hazae41** [comment]
For people wanting zlib-like functions, I made a WebAssembly module: https://deno.land/x/denoflate

As WebAssembly functions are preferable over native Rust ops, I'm closing this issue

**Comment by kitsonk** [comment]
Re-opening as having it as a WebAssembly module in `std` would be good, or exposing the ops, as the crates are already part of Deno.

**Comment by tyler338** [comment]
consider implementing it as Compression/Decompression Streams to be browser compatible https://chromestatus.com/feature/5855937971617792

**Comment by 101arrowz** [comment]
Any updates on this? Denoflate is still slower than true Zlib by quite a bit; even [pure JavaScript](https://github.com/101arrowz/fflate) outperforms it. See this test of the compression libraries I could find in Deno:

```js
import { gzipSync, gunzipSync } from "https://cdn.skypack.dev/fflate";
import { gzip, gunzip } from "https://deno.land/x/denoflate/mod.ts";
import {
  gzip as gzCompress,
  gunzip as gzDecompress
} from "https://deno.land/x/compress@v0.3.6/mod.ts";
import {
  gzipEncode,
  gzipDecode
} from "https://github.com/manyuanrong/wasm_gzip/raw/master/mod.ts";

// 50MB uncompressed image, replace link to test on another file
const FILE_URL = 'https://www.hlevkin.com/hlevkin/TestImages/new/Sunrise.bmp';

console.log('Downloading...');
const dat = new Uint8Array(await (await fetch(FILE_URL)).arrayBuffer());
console.log('Complete! Data length: ' + dat.length);

const test = (name, cmpr, dcmp) => {
  const ts = performance.now();
  const buf = cmpr(dat);
  const tc = performance.now();
  const src = dcmp(buf);
  const te = performance.now();
  if (src.length != dat.length || src.some((v, i) => dat[i] != v)) {
    throw new Error(name + ' failed to decompress');
  }
  console.log(name + ': compressed length = ' + buf.length +
    ', time taken = ' + (tc - ts) + 'ms, decompress time = ' +
    (te - tc) + 'ms'
  );
}

test('fflate', gzipSync, gunzipSync);
test('denoflate', gzip, gunzip);
test('compress', gzCompress, gzDecompress);
test('wasm_gzip', gzipEncode, gzipDecode);
```

Native Zlib tends to beat fflate by 20-25%, which is quite substantial. CompressionStream and DecompressionStream are indeed the best way to go about implementing it.

**Comment by hazae41** [comment]
@101arrowz  I couldn't reproduce the benchmark

> error: Uncaught (in promise) TypeError: WebAssembly.compile(): Argument 0 must be a buffer source

**Comment by 101arrowz** [comment]
I just ran `deno --allow-all test.js`, worked for me. Not sure why yours is broken.

**Comment by bartlomieju** [comment]
Engineering effort to expose `zlib` bindings from the V8/`rusty_v8` would be enormous and I don't think it is worth it; especially given that WASM bindings (https://github.com/emscripten-ports/zlib) are available.
