### ISSUE TITLE
TypeScript compilation hangs on large files

### ISSUE THREAD

**Issue by aduh95** [denoland/deno#4078]
When a TS module has a large JS file as a dependency, the compiler hangs for a long time; below is a shell script that generates a 27MiB JS file and measure the compile time:

```shell
$ echo "export default Uint16Array.from([" > randomBuffer.js
$ head -30000 /dev/urandom | hexdump -v -x | awk '$1=" "' OFS=",0x" >> randomBuffer.js
$ echo "]).buffer" >> randomBuffer.js

$ ls -ks randomBuffer.js
27652 randomBuffer.js

$ echo "import buf from './randomBuffer.js';\
console.log(buf);\
" > module.ts

$ time tsc -m es6 --target esnext module.ts
real    0m1.953s
user    0m3.666s
sys     0m0.125s

$ time deno run -r --allow-read ./module.js
ArrayBuffer {}

real    0m1.056s
user    0m0.928s
sys     0m0.130s

$ time deno run -r --allow-read ./module.ts
Compile file://…/module.ts
ArrayBuffer {}

real    0m30.653s
user    0m43.425s
sys     0m1.199s
```

As you can see, it takes less than 3s of real time when using `tsc`+`deno`, but it takes _more than 30s_ when `deno` takes care of the TS compilation. That's a **10x time ratio**, I wonder if there's a missed optimisation opportunity somewhere.

**Comment by bartlomieju** [comment]
CC @kitsonk

**Comment by kitsonk** [comment]
I haven't tried it yet, but the equivalent of Deno would be though:

```
tsc -m es6 --target esnext --allowJs --strict module.ts
```

I suspect you would get a different compile time there, as `tsc` would access the JavaScript file.  I think we need to consider the impact of having `allowJs` on by default while not having `checkJs` on by default, as it appears to be causing a few issues.  There are a couple other things we might be able to do too, to trick the compiler with JavaScript files.

**Comment by aduh95** [comment]
I am not able to reproduce on v0.35.0, it looks like #4040 fixed it. Closing for now, feel free to reopen if I am missing something.
