### ISSUE TITLE
Shouldn't std/node be a plugin ?

### ISSUE THREAD

**Issue by ecyrbe** [denoland/deno#4086]
As i'm going through std/node polyfill implementation, i'm adding more and more ops to Deno.
This feels kind of bizarre. Not all node exposed API are well suited for Deno/cli/ops. 

Sometimes they might profoundly differ from what deno wants to achieve. (ie: modules, policies)

Should't we make most of Node api only available on a plugin ? 
Meaning, only implement some desired API on Deno/cli/ops to expose them on both plugin/node and Deno ?

**Comment by ry** [comment]
@ecyrbe I don't think we need to achieve 100% API compatibility with Node. I'd rather focus on the 80% case first - like file system stuff, networking stuff. Once all that is working we can carefully discuss each of the remaining and decide if they make sense. I'm going to close this as it's quite general. I'd rather discuss each new op individually.
