### ISSUE TITLE
WebSockets Uncaught TypeError: Cannot read property 'reject' of undefined

### ISSUE THREAD

**Issue by pauschuu** [denoland/deno#4088]
https://github.com/denoland/deno/blob/7e49d96cbcde1e8eb89d0fdd499be473822b725b/std/ws/mod.ts#L283

This line throws a **TypeError** in **deno v0.34.0** under the following circumstances:
1) Client sends a message via a websocket connection to the server.
2) Client immediately exits after it send the first message (no `sock.close()` or anything).
3) Server handles the message and wants to reply to the same socket with another message. `(sock.send("foobar"))`

I couldn't figure out how to catch the exception at the `sock.send("foobar")` code itself.

**Comment by pauschuu** [comment]
Probably the code just needs to check if e.d is defined? I'm not deep enough within the code or TypeScript at all, sorry.

**Comment by bartlomieju** [comment]
CC @keroxp; wasn't this fixed in #4083 ?

**Comment by keroxp** [comment]
@bardiarastin  Ah yes. It was silly indeed.

@pauschuu Thank you for reporting. The reason is too simple. There are two variables named `e` 😫I pointed another one out of scope.
