### ISSUE TITLE
Deno.makeTempDir permissions check bug with relative paths

### ISSUE THREAD

**Issue by Acerbic** [denoland/deno#4103]
Related to #3810 (see https://github.com/denoland/deno/pull/3810#issuecomment-580076434)

makeTempDir fails if `dir` option is specified with a relative path, and --allow-write permission uses a whitelist.

I put together a [small example](https://github.com/Acerbic/deno_makedirtemp_bug_demo) of the buggy behavior.

**Comment by ry** [comment]
@Acerbic Thank you for the detailed report.  

cc @manyuanrong
