### ISSUE TITLE
CI fails on Windows

### ISSUE THREAD

**Issue by uki00a** [denoland/deno#4108]
```
test result:  FAIL  704 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out (30788.36ms)

There were 2 test failures.
 FAIL  GET / should serve html
Http: error sending request for url (http://127.0.0.1:8080/): connection error: An existing connection was forcibly closed by the remote host. (os error 10054)
    at Object.constructError ($deno$/errors.ts:69:13)
    at unwrapResponse ($deno$/dispatch_json.ts:40:12)
    at Object.sendAsync ($deno$/dispatch_json.ts:91:10)
    at async sendFetchReq ($deno$/fetch.ts:472:11)
    at async fetch ($deno$/fetch.ts:540:27)
    at async Object.fn (server_test.ts:31:16)
    at async Object.runTests ($deno$/testing.ts:157:7)
    at async runTestModules (runner.ts:234:3)
    at async main (runner.ts:276:5)
 FAIL  GET /ws should upgrade conn to ws
ConnectionRefused: No connection could be made because the target machine actively refused it. (os error 10061)
    at Object.constructError ($deno$/errors.ts:41:13)
    at unwrapResponse ($deno$/dispatch_json.ts:40:12)
    at Object.sendAsync ($deno$/dispatch_json.ts:91:10)
    at async Object.connect ($deno$/net.ts:292:15)
    at async connectWebSocket (file:///D:/a/deno/deno/std/ws/mod.ts:539:12)
    at async Object.fn (server_test.ts:40:8)
    at async Object.runTests ($deno$/testing.ts:157:7)
```

[/std/examples/chat/server_test.ts](https://github.com/denoland/deno/blob/master/std/examples/chat/server_test.ts) fails on Windows.

I don't have Windows PC, so it is difficult for me to test at hand...

Does anyone know the cause or solution for this?

Thanks.

**Comment by hazae41** [comment]
This works well for me on virtualized Windows 10

	// Copyright 2018-2020 the Deno authors. All rights reserved. MIT license.
	import { assert, assertEquals } from "../../testing/asserts.ts";
	import { TextProtoReader } from "../../textproto/mod.ts";
	import { BufReader } from "../../io/bufio.ts";
	import { connectWebSocket, WebSocket } from "../../ws/mod.ts";

	let server: Deno.Process | undefined;
	async function startServer(): Promise<void> {
	  server = Deno.run({
		args: [Deno.execPath(), "--allow-net", "--allow-read", "server.ts"],
		cwd: "examples/chat",
		stdout: "piped"
	  });
	  try {
		assert(server.stdout != null);
		const r = new TextProtoReader(new BufReader(server.stdout));
		const s = await r.readLine();
		assert(s !== Deno.EOF && s.includes("chat server starting"));
	  } catch {
		server.close();
	  }
	}

	const { test } = Deno;

	test("beforeAll", async () => {
	  await startServer();
	});

	test("GET / should serve html", async () => {
	  const resp = await fetch("http://127.0.0.1:8080/");
	  assertEquals(resp.status, 200);
	  assertEquals(resp.headers.get("content-type"), "text/html");
	  const html = await resp.body.text();
	  assert(html.includes("ws chat example"), "body is ok");
	});

	let ws: WebSocket | undefined;
	test("GET /ws should upgrade conn to ws", async () => {
	  ws = await connectWebSocket("http://127.0.0.1:8080/ws");
	  const it = ws.receive();
	  assertEquals((await it.next()).value, "Connected: [1]");
	  ws.send("Hello");
	  assertEquals((await it.next()).value, "[1]: Hello");
	});
	test("afterAll", () => {
	  server?.close();
	  ws?.conn.close();
	});
