### ISSUE TITLE
Odd behavior when using a function called "define" and checkJs together

### ISSUE THREAD

**Issue by ry** [denoland/deno#4110]
@seishun [reports](https://github.com/denoland/deno/pull/4010#issuecomment-590471108):

tsconfig.json
```json
{
  "compilerOptions": {
    "checkJs": true,
    "allowJs": true
  }
}
```
foo.ts
```ts
import "./test.js";
```
test.js
```js
function define(foo) {}
define(["long"]);
```
..\deno\target\debug\deno.exe --config tsconfig.json foo.ts
```
Compile file:///C:/Users/Nikolai/test-proj-delete/foo.ts
error: Uncaught URIError: relative import path "long" not prefixed with / or ./ or ../ Imported from "file:///C:/Users/Nikolai/test-proj-delete/test.js"
```

Ref https://github.com/denoland/deno/pull/4040 https://github.com/denoland/deno/pull/4010
cc @kitsonk

**Comment by kitsonk** [comment]
Yeah, there are a few things that I need to work through to get everything right.

**Comment by bartlomieju** [comment]
Works fine on v1.0.2
