### ISSUE TITLE
Windows terminal colors broken after removal of ansi_term

### ISSUE THREAD

**Issue by ry** [denoland/deno#4112]
We need to call `set_virtual_terminal_processing` 

see https://github.com/denoland/deno/pull/4106#pullrequestreview-363475270

**Comment by jsouto18** [comment]
@ry I’m on it!

**Comment by kevinkassimo** [comment]
On macOS, color also broken:
<img width="1100" alt="Screen Shot 2020-02-24 at 12 58 14 PM" src="https://user-images.githubusercontent.com/15007517/75190546-62aa4380-5705-11ea-9787-5f4a747288d0.png">

**Comment by jsouto18** [comment]
@kevinkassimo Found the reason that was happening! Thanks for the print!
