### ISSUE TITLE
Support unix domain sockets

### ISSUE THREAD

**Issue by teleclimber** [denoland/deno#4115]
Now that UDP support has been added in #3946 I'm wondering if Unix Domain sockets could be added in the same way.

Unix sockets are very handy when you need to communicate with another process without dealing with ports and whatnot.

I suppose the only question is whether connecting to a UDS from Deno requires a net permission or a file permission. My hunch is that it is a file permission, simply because that is how it is thought of in the underlying OS.

Thanks.

**Comment by hazae41** [comment]
Here is the API I propose

    Deno.listen({ transport: "unix", socket: "/var/run/mysocket" }): UnixConn

    Deno.connect({ transport: "unix", socket: "/var/run/mysocket" }): UnixConn

class UnixConn would be similar to UDPConn and Go's definition https://golang.org/pkg/net/#UnixConn

**Comment by jsouto18** [comment]
@hazae41 are you working on this? I would like to give this a try if you're not :)

**Comment by hazae41** [comment]
> @hazae41 are you working on this? I would like to give this a try if you're not :)

Not yet

**Comment by Juu-** [comment]
Hi everyone,

Would you please tell me where I could find the chosen solution.

Thanks,
Juu

**Comment by ertw** [comment]
@Juu- https://deno.land/x/sockets/

**Comment by chances** [comment]
> @Juu- https://deno.land/x/sockets/

https://docs.deno.com/api/web/~/WebSocket

**Comment by charles-dyfis-net** [comment]
> @Juu- https://deno.land/x/sockets/

websockets are a completely different thing from UNIX domain sockets
