### ISSUE TITLE
Expiring logs for GitHub Actions

### ISSUE THREAD

**Issue by joeltimothyoh** [denoland/deno#4121]
Older Github Actions build logs are beginning to expire. I discovered the same happening on several of my own projects that started using the service since launch last November.

Case in point: Looking through logs under [Checks](https://github.com/denoland/deno/pull/3352/checks) for #3352 of [v0.25.0](https://github.com/denoland/deno/releases/tag/v0.25.0) presents the message “*The logs for this run have expired and are no longer available.*”

Lack of access to logs mean the loss of traceability for changes, commits, and PRs in open source projects. Just a heads-up for folks here at Deno.

**Comment by lucacasonato** [comment]
GitHub expires logs and artifacts after 90 days. @ry WDYT? Does this matter in any way or can this be closed?

**Comment by ry** [comment]
Thanks for the info. Noted.
