### ISSUE TITLE
Permission denied on Deno.open() on Windows directories

### ISSUE THREAD

**Issue by cknight** [denoland/deno#4125]
The command `Deno.open()` and `Deno.openSync()` do not work on Windows directories.  Should they?  The node equivalent seems to work, but I'm not familiar with Deno's approach to the file system.

Example `test.ts` file:
```
console.log(Deno.openSync("."));
```

```
PS C:\tools> ./deno --version                                                                     
deno 0.34.0                                                                                       
v8 8.1.108                                                                                        
typescript 3.7.2        
                                                                          
PS C:\tools> ./deno test.ts                                                                       
Compile file:///C:/tools/test.ts                                                                  
error: Uncaught PermissionDenied: read access to "C:\tools", run again with the --allow-read flag 
► $deno$/dispatch_json.ts:40:11                                                                   
    at DenoError ($deno$/errors.ts:20:5)                                                          
    at unwrapResponse ($deno$/dispatch_json.ts:40:11)                                             
    at sendSync ($deno$/dispatch_json.ts:67:10)                                                   
    at openSync ($deno$/files.ts:47:15)                                                           
    at file:///C:/tools/test.ts:1:18   
                                                           
PS C:\tools> ./deno --allow-read test.ts                                                          
error: Uncaught PermissionDenied: Access is denied. (os error 5)                                  
► $deno$/dispatch_json.ts:40:11                                                                   
    at DenoError ($deno$/errors.ts:20:5)                                                          
    at unwrapResponse ($deno$/dispatch_json.ts:40:11)                                             
    at sendSync ($deno$/dispatch_json.ts:67:10)                                                   
    at openSync ($deno$/files.ts:47:15)                                                           
    at file:///C:/tools/test.ts:1:18   
                                                           
PS C:\tools> ./deno -A test.ts                                                                    
error: Uncaught PermissionDenied: Access is denied. (os error 5)                                  
► $deno$/dispatch_json.ts:40:11                                                                   
    at DenoError ($deno$/errors.ts:20:5)                                                          
    at unwrapResponse ($deno$/dispatch_json.ts:40:11)                                             
    at sendSync ($deno$/dispatch_json.ts:67:10)                                                   
    at openSync ($deno$/files.ts:47:15)                                                           
    at file:///C:/tools/test.ts:1:18                                                              
PS C:\tools>                                                                                      
```

See also PR #4087 where the CI is failing due to the above.  I've also added a number of test cases to try different options of open() vs openSync() with and without dirOptions in this commit (for temporary testing purposes only): https://github.com/denoland/deno/pull/4087/commits/201b24e962fc227b36e418be8092ed036931df7c.  All of these tests fail with the permission denied error (except for the "Program Files" test which is likely a mistake in the path name).  This fails even if run as administrator.

**Comment by hazae41** [comment]
Try running it with an admin terminal

**Comment by cknight** [comment]
Fails with same error in admin console.

**Comment by hazae41** [comment]
It work well for me

    cd /test
    deno --allow-read --allow-write ./test.ts

Content of "test.ts":
    
    await Deno.open("test", "x+")

Maybe the fold you work with has OS restriction or is open by another process

**Comment by cknight** [comment]
Interesting.  What does 'test' in your `test.ts` refer to, seeing as you are already in the test directory and the file you are executing is `test.ts`?  I think this is a reference to a brand new file.  Exploring this further
```
 console.log(Deno.openSync("test.ts", {read:true, write:false}));
```
works, so opening an existing file in the current directory works.  However, reading a directory itself does not:
```
console.log(Deno.openSync(".", {read:true, write:false}));
```
or (after creating a subdirectory testDir in my current directory):
```
console.log(Deno.openSync("testDir", {read:true, write:false}));
```
Reading directories, as per above code, works on my Linux machine.  Is `Deno.open()` mean to work with directories and therefore this is a bug with Windows, or is it not meant for directories and the fact it works on Linux is a unintentional side effect?

**Comment by cknight** [comment]
@bartlomieju - reading the code base, it looks like you were possibly involved (amongst others) in writing the OP_OPEN, which is at the root of this question.  Are you able to confirm if `Deno.open()` or `Deno.openSync()` makes sense for directories in Deno?

**Comment by hazae41** [comment]
I don't think open() can work with a folder since it opens the resource for read/write.

If you want to work with folders you can use mkdir() (IIRC) to create one and list its files with other functions

**Comment by cknight** [comment]
Yes, I'm increasingly thinking `open()` isn't meant for directories.  I'm implementing some of the fs API into a node polyfill and Node uses the equivalent of `open()` to get a handle to the directory before reading from it.  It seems more and more likely to me that Deno handles this differently, and there isn't a need for a resource id for directories in Deno.

**Comment by bartlomieju** [comment]
@cknight `Deno.open` was meant for files and as described by @hazae41 to be used with `Deno.read()`/`Deno.write()`. Take a look at [`OpenOptions::open`](https://doc.rust-lang.org/std/fs/struct.OpenOptions.html#method.open) for it depth look what errors can be returned (besides Deno-specific ones).

I am not sure how can you "open a directory", can you elaborate on that?

**Comment by cknight** [comment]
So, I'm trying to port the Node fs API to the Deno polyfill. Reading this API, Node uses, for directories, file id's which are opened and closed.  The file id's (resource ids in Deno speak I think) are handled under the covers by the looks of it.  Node exposes a [Dir.close()](https://nodejs.org/api/fs.html#fs_dir_close) method for example which will close the relevant file id.

It looks like Deno doesn't use or expose resource id's for directories, and therefore the polyfill for `Dir.close()` would be an empty function since Deno doesn't need to close Directories.

Thanks very much for the clarification and the link to the Rust op.  I'll proceed with the polyfill on the basis that Deno doesn't have or need to keep track of resource id's for reading from directories.

**Comment by CompeyDev** [comment]
Maybe found something related to this issue. Deno child processes do not seem to be able to access directories for some odd reason. Below is some example code that will error with an OS Error 5 (Permission Denied).

```ts
console.log(path.resolve('.', 'test'))
const r = new Deno.Command("ls", {
    args: [ path.resolve('.', 'test') ],
    stdout: 'piped',
    stdin: 'piped'
})

const child = r.spawn()

child.stdout.pipeTo(Deno.openSync("output").writable);

child.stdin.close();
const status = await child.status;

console.log(status)
```

**Comment by 0f-0b** [comment]
@CompeyDev `Deno.openSync("output")` attempts to open `output` for reading. To create the file for writing, you could use `Deno.openSync("output", { write: true, create: true })` instead.

**Comment by CompeyDev** [comment]
> @CompeyDev `Deno.openSync("output")` attempts to open `output` for reading. To create the file for writing, you could use `Deno.openSync("output", { write: true, create: true })` instead.

That is not the error I am referring to, I already have it set as writable. The error I am referring to is regarding the Child Process, which seems to not have access to the directory. The `ls` command in that process returns a access denied as a result. I've tried this with various other commands as well and it seems to display similar behavior.
