### ISSUE TITLE
Get timers working in Rust rewrite

### ISSUE THREAD

**Issue by ry** [denoland/deno#413]
Using Tokio

**Comment by benjamingr** [comment]
As an idea - we can ship timers that are `await`able out of the box. 

We can implement `Symbol.asyncIterator` on `setInterval` and `then` on setTimeout directly.

Cons: 
 - Isn't what browsers do

Pros:
 - Much nicer API for use with `async/await`

**Comment by ry** [comment]
@benjamingr is there a spec for that? We've used `await delay(milliseconds)` in the past.

**Comment by benjamingr** [comment]
@ry there is no standard for that as far as I know - just half-baked proposals and discussions in the Node.js repo and whatwg list.

Node also provides a `util.promisify` compatible setTimeout which basically does `delay`.
