### ISSUE TITLE
Recommended in documentation "file_server" compiles with error

### ISSUE THREAD

**Issue by balajahe** [denoland/deno#4139]
https://deno.land/std/manual.md#file-server

I updated Deno, but server installation still fails :(

`user@pc:~$ deno install --allow-net --allow-read file_server https://deno.land/std/http/file_server.ts
Download https://deno.land/std/http/file_server.ts
Compile https://deno.land/std/http/file_server.ts
Download https://deno.land/std/path/mod.ts
Download https://deno.land/std/http/server.ts
Download https://deno.land/std/flags/mod.ts
Download https://deno.land/std/testing/asserts.ts
Download https://deno.land/std/path/win32.ts
Download https://deno.land/std/path/posix.ts
Download https://deno.land/std/path/constants.ts
Download https://deno.land/std/path/constants.ts
Download https://deno.land/std/path/interface.ts
Download https://deno.land/std/path/glob.ts
Download https://deno.land/std/path/globrex.ts
Download https://deno.land/std/path/utils.ts
Download https://deno.land/std/fmt/colors.ts
Download https://deno.land/std/testing/diff.ts
Download https://deno.land/std/testing/format.ts
Download https://deno.land/std/io/bufio.ts
Download https://deno.land/std/textproto/mod.ts
Download https://deno.land/std/http/http_status.ts
Download https://deno.land/std/util/async.ts
Download https://deno.land/std/http/io.ts
Download https://deno.land/std/io/util.ts
Download https://deno.land/std/strings/mod.ts
Download https://deno.land/std/strings/encode.ts
Download https://deno.land/std/strings/decode.ts
Download https://deno.land/std/strings/pad.ts
error TS2339: Property 'errors' does not exist on type 'typeof Deno'.

► https://deno.land/std/http/file_server.ts:166:25

166   if (e instanceof Deno.errors.NotFound) {
                            ~~~~~~
`

**Comment by axetroy** [comment]
Please use a locked version of std module

```diff
- deno install --allow-net --allow-read file_server deno.land/std/http/file_server.ts
+ deno install --allow-net --allow-read file_server deno.land/std@v0.34.0/http/file_server.ts
```

**Comment by kitsonk** [comment]
Yes, we deploy breaking changes to master at the moment, which can mean that unless you are using a version of Deno off of master, other things on master won't work.

We should either update the manual automatically with the current latest tag as the part of the build process, or put an example/caveat there of how to use the pinned version.  We can't just expect people to "know" that.

**Comment by kevinkassimo** [comment]
I feel it would be nice to have `https://deno.land/std/` pointing to the last tagged version, and make master located at `https://deno.land/std@dev` or similar.

**Comment by ry** [comment]
Someday we will stop making API changes... I apologize for the instability but we figure we should get it done quickly now rather than keeping warts forever.
