### ISSUE TITLE
Reading Blobs

### ISSUE THREAD

**Issue by morille** [denoland/deno#4142]
It would be great to have either the (old) FileReader API or the new Promise based Blob methods "text", "arrayBuffer" and "stream".

**Comment by hayd** [comment]
Note: Fixing this is required for JsZip to work in deno.
(Potentially it will work OOTB with this.)

API: https://developer.mozilla.org/en-US/docs/Web/API/Blob

**Comment by crowlKats** [comment]
agree, tho duplicate of #2303. I am currently looking into implementing these methods.

**Comment by brianleroux** [comment]
This would fix the browser builds for the `aws-sdk` in Deno also.

**Comment by crowlKats** [comment]
@brianleroux this was already solved. This issue should be closed

**Comment by brianleroux** [comment]
where was it solved?
<img width="475" alt="Screen Shot 2020-05-12 at 10 01 13 AM" src="https://user-images.githubusercontent.com/990/81723338-8abd5f00-9437-11ea-995c-6bdfd1e89e29.png">

**Comment by crowlKats** [comment]
FileReader API isnt implemented, but the `text`, `arrayBuffer` & `stream` are.

**Comment by brianleroux** [comment]
Yeah, didn't think so, but I should've been more specific. The browser builds of the `aws-sdk` require `FileReader` (and SubtleCrypto / `window.crypto`API) so there's some gaps left to fill before closing if web compat is truly a goal.

**Comment by crowlKats** [comment]
`SubtleCrypto` is indeed a wanted feature, just it's a decent amount of work to implement (#1891). Since this issue was made for the ability to read blobs with either of the two ways - and the goal has been reached - it should be closed. Best thing would be opening a new, more specific issue about `FileReader`.

**Comment by brianleroux** [comment]
sure. I don't want to make a bunch of noise opening fresh issues but knock yourself out.

**Comment by morille** [comment]
Indeed this issue is resolved, thanks.

**Comment by hayd** [comment]
@brianleroux can you create an issue for aws-sdk issue you faced? I thought, when I'd tried to use it previously, the issue was with missing XML apis.

(It would be amazing if aws-sdk worked ootb...)

**Comment by brianleroux** [comment]
since its resolved whats the point ;)

**Comment by brianleroux** [comment]
sorry I couldn't resist. this community, like most new communities, needs to work on its manners. or some new individuals do anyhow. 

https://github.com/denoland/deno/issues/5249
