### ISSUE TITLE
Implement deno.readFileSync and deno.writeFileSync

### ISSUE THREAD

**Issue by ry** [denoland/deno#415]
Here's a pointer to the prototype implementation: 
https://github.com/ry/deno/blob/golang/os.go#L171-L195

**Comment by benjamingr** [comment]
@ry given that we have promise APIs and async/await - maybe skip `*Sync` APIs entirely?

**Comment by ry** [comment]
#452 implements readFileSync

**Comment by NewLunarFire** [comment]
#519 has an implementation of writeFileSync
