### ISSUE TITLE
[example] Untarring a file (containing multiple files) which submitted via http

### ISSUE THREAD

**Issue by alexanderGalushka** [denoland/deno#4156]
http request:

`curl -F "bundle=mybundle.tar" localhost:8080/untarme`

mybundle.tar contains example1.txt and example2.txt

followed this gist, got the FormFile

between this https://deno.land/std/archive/tar.ts and https://deno.land/std/archive/tar_test.ts

still can't wrap my head around how to convert FormFile into the Tar or Deno.Reader to eventually Untart.extract and save example1.txt and example2.txt to the disk

**Comment by alexanderGalushka** [comment]
I've following this gist https://gist.github.com/artisonian/8297e5fe95f448ca98045f336bccf976 to get the file out of http request

@artisonian @kitsonk @bartlomieju any clues?

**Comment by artisonian** [comment]
The `extract` method of the Untar class can be used multiple times to unpack the entire archive, but it seems like this might be a good use case for it being an async iterator.
