### ISSUE TITLE
deno does not download ts source files on windows.

### ISSUE THREAD

**Issue by dinfer** [denoland/deno#4183]
According the document, all the ts source file is downloaded by deno

create a file named `a.ts`

```typescript
import { serve } from "https://deno.land/x/std/http/server.ts";
```

run in powershell

```
deno run --reload .\a.ts
```

in the dep folder, no ts file is downloaded

```
C:\Users\<username>\AppData\Local\deno\deps\https\deno.land
```

![image](https://user-images.githubusercontent.com/11496403/75605937-c035fa00-5b22-11ea-96f1-b75dae282477.png)

deno info

```
deno 0.34.0
v8 8.1.108
typescript 3.7.2
```

**Comment by bartlomieju** [comment]
Everything's fine. Deno turns URL into a hash to store downloaded files. There is no extension, but Deno knows it's a TS file

**Comment by dinfer** [comment]
@bartlomieju Yes, it works fine. But this behavior makes VS Code code completion very hard to work. I cannot map import paths to its source file.

I found the issue #4069 just now, This issue may closed, I will follow that issue.

Thanks
