### ISSUE TITLE
Incorrectly named Windows executable batch file

### ISSUE THREAD

**Issue by srackham** [denoland/deno#4199]
On Windows 10 the Deno install command adds a `..cmd` extension instead of `.cmd` to the executable batch file name e.g.

```
Microsoft Windows [Version 10.0.18362.657]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Users\srackham>deno --version
deno 0.34.0
v8 8.1.108
typescript 3.7.2

C:\Users\srackham>deno install --force -A drake https://raw.github.com/srackham/drake/master/drake.ts
  :
  :
✅ Successfully installed drake
C:\Users\srackham\.deno\bin\drake..cmd                 <---- should be drake.cmd

C:\Users\srackham\.deno\bin>C:\Users\srackham\.deno\bin\drake
'C:\Users\srackham\.deno\bin\drake' is not recognized as an internal or external command, operable program or batch file.
```
See https://github.com/denoland/deno/blob/master/cli/installer.rs#L146

    file_path = file_path.with_extension(".cmd");

should be:

    file_path = file_path.with_extension("cmd");

See also:

- https://github.com/denoland/deno/blob/master/cli/tests/integration_tests.rs#L192
- https://github.com/denoland/deno/blob/master/cli/tests/integration_tests.rs#L240
- https://github.com/denoland/deno/blob/master/cli/tests/integration_tests.rs#L1395

**Comment by bartlomieju** [comment]
Fixed in #4243
