### ISSUE TITLE
unit test flaky due to fs event -

### ISSUE THREAD

**Issue by ecyrbe** [denoland/deno#4204]
I get these on my PR, that do not seem to be related to code i pushed #4202  :
```bash
OK     fsEventsBasic (2.00ms)
##[error]thread '<unnamed>' panicked at 'fs events error: SendError(Ok(FsEvent { kind: "modify", paths: ["/tmp/8259b2ca/file2.txt"] }))', src/libcore/result.rs:1188:5
```

**Comment by ecyrbe** [comment]
@bartlomieju any idea why this fs event test panics ?

**Comment by bartlomieju** [comment]
Most likely because `FsWatcher` doesn't stop watching after it's closed an tries to push new notification on a channel that has been closed. 

CC @ry you might want to call ['unwatch'](https://docs.rs/notify/5.0.0-pre.2/notify/trait.Watcher.html#tymethod.unwatch) when closing watcher resource
