### ISSUE TITLE
sanitize resources in std/ code

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#4208]
Similar to https://github.com/denoland/deno/pull/4161 resource sanitization should be done in `std/` code. The `assertResources` sanitizer has proven quite useful in `cli/` allowing to find bugs in `fetch` implementation (#4194).

https://github.com/denoland/deno/blob/ba0991ad2ba89b7a788a866419759d858b125663/cli/js/test_util.ts#L109-L123

I ran `std/` tests with `assertResources` helper and there's about 60 tests that do not properly close resources. This is an easy, but time-consuming issue to resolve.

@nayeemrmn suggested that this sanitizer should be added to `Deno.test()` itself and I'm not 100% against it, but I'm also not fully convinced that we should do it - at least not yet. Let's first sanitize `std/` tests and then revisit the subject.

Before start working on this problem, please comment on the issue.

**Comment by lorenzofox3** [comment]
I have some time ahead of me and will be happy to help. I am just getting started with deno and will probably need some guidance though

**Comment by bartlomieju** [comment]
Hey @lorenzofox3 

> I have some time ahead of me and will be happy to help. I am just getting started with deno and will probably need some guidance though.
> 
> Do you think I could handle it with no prior experience with deno but good skills in JS/TS ?

Glad to hear that, you should be good :+1: can you please wait a few days though? We might be adding this sanitizer to `Deno.test()` anyway so there will be no need to carry code to `std/`.

**Comment by lorenzofox3** [comment]
ok keep me posted !

**Comment by bartlomieju** [comment]
@lorenzofox3 sorry I didn't ping you, but I had to add the API and fix all tests in one go!
