### ISSUE TITLE
listenAndServe should return a resolved promise

### ISSUE THREAD

**Issue by andrewrjohn** [denoland/deno#4229]
When using `listenAndServe`, it looks to me that it should return a resolved Promise once it is serving, am I misreading this?
```
export async function listenAndServe(
  addr: string,
  handler: (req: ServerRequest) => void
): Promise<void> {
  const server = serve(addr);

  for await (const request of server) {
    handler(request);
  }
}
```

Then we should be able to do something along the lines of:
```
listenAndServe({ port: 8000 }, handler).then(() => {
    console.log("Server running on port 8000")
})
```
However that is not working for me, is this a bug or am I misunderstanding `listenAndServe`?

**Comment by nayeemrmn** [comment]
That promise resolves after the loop breaks, as you can see. That means after the server closes, not after the server starts.

**Comment by andrewrjohn** [comment]
That makes sense. I'll close this issue.
