### ISSUE TITLE
Deno creating huge error messages from auto-generated JS

### ISSUE THREAD

**Issue by Sharpiro** [denoland/deno#4255]
deno 0.35.0
v8 8.1.310
typescript 3.8.2

I was working with [wabt.js](https://github.com/AssemblyScript/wabt.js) today and trying to get it working with deno as well as the browser.  When testing, I noticed deno was creating huge errors, so big in fact, I had to save them to a file to read them.  It almost seems like the error contains the entire program, or one of the huge lines.  wabt.js is built using emscripten, which creates pretty ugly javascript, so I'm not sure if this only occurs when deno runs something that emscripten has built.

An example of the error:
```sh
deno https://raw.githubusercontent.com/Sharpiro/bugs/0d41bbe0d3ee8cf2e052cbc76d7f00b917a933fd/deno/large_errors/index.js
```

add `&> temp` to output it to file
```sh
deno https://raw.githubusercontent.com/Sharpiro/bugs/0d41bbe0d3ee8cf2e052cbc76d7f00b917a933fd/deno/large_errors/index.js &> temp
```

As an aside here is a fork of WABT I got working today in deno after fixing the errors:
https://github.com/Sharpiro/wabt.js/blob/9ea629b1c31f80c70efdf9d01b489274beb0ddb1/index.js

**Comment by kevinkassimo** [comment]
Ahh yikes, the reason for this is due to us using a JS wrapper around the WASM file that got base64 encoded.

We should restrict the error line to be shorter than e.g. 150 characters IMO

**Comment by kevinkassimo** [comment]
So I have a new idea: maybe we should just show nothing if the error line is too long, since it is not likely going to help anyways. Also truncation has the problem of unicode substring handling, and I am reluctant to introduce a new crate line [`unicode-segmentation`](https://unicode-rs.github.io/unicode-segmentation/unicode_segmentation/index.html) just to deal with grapheme clusters

**Comment by kitsonk** [comment]
Given the problem with truncation (though I suspect that would be an edge case and if you mis truncated a line, we are talking about one char being mangled), I still think if the line is longer than say 120 or 150, it just doesn't make sense to output it.
