### ISSUE TITLE
NO_COLOR=true is working only partially

### ISSUE THREAD

**Issue by timonson** [denoland/deno#4261]
Since the last changes, the effects of setting `NO_COLOR` to `true` have stopped working in `vim`. I don't know if this is exclusively happening in vim, but I know that setting the variable to `true`  *oppressed* the colors until a couple of days ago.

Redirecting the `deno` output to a vim *buffer* now includes the *escape* sequences like the following example shows:

![deno_NO_COLOR-2020-03-05](https://user-images.githubusercontent.com/54777088/75981125-2389a880-5ee4-11ea-835c-5fbf3f17a838.png "TS Compiler Error")

What is strange tho - therefore the word *partially* is in the title - is the fact that the colors are *oppressed* when I run the same command and code in the same terminal **without** vim. 

I would be happy to add more information and examples if required.

**Comment by jsouto18** [comment]
[0m seem to be the ANSI reset sequence. I believe I've found the cause for this issue and will create a PR so solve this. @timonson thanks for the detail in the report 😄!
