### ISSUE TITLE
test_raw_tty hangs

### ISSUE THREAD

**Issue by keroxp** [denoland/deno#4262]
<img width="701" alt="スクリーンショット 2020-03-05 21 21 49" src="https://user-images.githubusercontent.com/927286/75981218-6456e100-5f27-11ea-8605-aeb5acda4e38.png">

**Env:**
- macOS 10.15
- iTerm2, Terminal
- zsh

**Comment by bartlomieju** [comment]
I'm experiencing the same issue

CC @kevinkassimo

**Comment by kevinkassimo** [comment]
I suspect there is some race condition with that test. I'll see if I can get a fix of it by next week. Is this a zsh only problem, or also occurs under bash?

**Comment by keroxp** [comment]
@kevinkassimo  Yes, always. `cargo test test_raw_tty` works for both.

**Comment by bartlomieju** [comment]
Happened in CI as well:
https://github.com/denoland/deno/runs/493335175

**Comment by ry** [comment]
test_raw_tty has been reenabled on mac, but continues to hang.

I can repeat it reliably in https://github.com/denoland/deno/pull/8520
