### ISSUE TITLE
Generate `deno.d.ts` and `console.d.ts` during build

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#427]
The built in module `deno.ts` should generate its runtime typings (`deno.d.ts`) during the build process and then be included as an asset, like `msg_generated.ts`.

**Comment by ry** [comment]
I agree.

**Comment by kitsonk** [comment]
This also should apply for `console.d.ts` and then `Console` can be imported into `lib.deno.d.ts` to ensure it has accurate types.

**Comment by kitsonk** [comment]
Closed in #479
