### ISSUE TITLE
opinionated web framework  

### ISSUE THREAD

**Issue by GerbenRampaart** [denoland/deno#4281]
I feel deno must not only have a web server but also a web framework.

The reason for this is that I think the main purpose of deno apps will disproportionately be apis. I feel it’s detrimental to the user experience of a new deno user when they must immediately search the internet for a web framework import for the main purpose of deno. Being a nodejs developer I always felt this was an omission in the framework. Writing a web api in node without dependencies feels icky and apis are such a common use case there is no reason not to include a simpel web framework in the base library.

**Comment by panov-andy** [comment]
This is the best candidate: https://mol.js.org/. Please look at it seriously.

**Comment by nin-jin** [comment]
I think Deno API should be isomorphic as more as possible. NodeJS API is very different with Web API and it's annoying.

**Comment by GerbenRampaart** [comment]
I disagree. ‘As isomorphic as possible’ really means ’as isomorphic as practical’. Not including a base library at all and let users do everything themselves with the runtime is super-isomorphic and incredible unpractical. There is always some degree of opinionation but a framework just needs to decide on the abstraction. 

And that’s my point: a simple web framework is an opinion deno is allowed to have. But that’s how I feel, there’s valid points on both sides.

**Comment by ry** [comment]
Your concerns are valid and if we had some opinions on web frameworks we might adopt them, but to a large extent Deno is focused on much lower level problems. 

I’m not against adding high level functionality to std but someone would need to argue and implement them.

Closing since this isn’t actionable for us.
