### ISSUE TITLE
Discussion: Sync methods obsolete?

### ISSUE THREAD

**Issue by timreichen** [denoland/deno#4299]
I wonder if Deno needs the ...Sync methods since

```ts
const data = readFileSync(…)
```
is the same use as
```ts
const data = await readFile(…)
```

**Comment by ry** [comment]
Yes it still needs it. This has to do with how syscalls are issued - synchronous FS syscalls should be issued from the main thread - if you do `await readFile` they will be dispatched to another thread, which is suboptimal for some programs.

**Comment by kitsonk** [comment]
And all await resolve at the end of turn, at best.  Not only is it suboptimal, but it can cause some unwanted side effects.
