### ISSUE TITLE
http server sample has no concurrency

### ISSUE THREAD

**Issue by jakajancar** [denoland/deno#4304]
The [example](https://deno.land/std/http/):

```
import { serve } from "https://deno.land/std/http/server.ts";
const s = serve({ port: 8000 });
console.log("http://localhost:8000/");
for await (const req of s) {
  req.respond({ body: "Hello World\n" });
}
```

... means that when inserting some non-trivial code, e.g.:

```
for await (const req of s) {
  const response = await generateResponseUsingASlowDatabase();
  req.respond(response);
}
```

... the server will handle just 1 request concurrently.

Being unfamiliar with "for await" and going with the example as a starting point, this just bit me.

Wouldn't it make sense to have as an example something that scales reasonably?

**Comment by ry** [comment]
I also tripped up on this initially - but the semantics of `for await` are clear once you learn them. Don't call `await` in a server loop.

**Comment by jakajancar** [comment]
What is a proper, elegant way, to achieve something like this:

```
const server = serve({ port: 8000 }, (req) => {
  
});
```

There is `listenAndServe()`, but that doesn't return a handle to `Server` to be able to close it (e.g. on SIGINT).

**Comment by jakajancar** [comment]
Short of:

```
import { serve } from "https://deno.land/std/http/server.ts";
const s = serve({ port: 8000 });
(async () => {
  for await (const req of s) {
    (async () => {
      const response = await generateResponseUsingASlowDatabase();
      req.respond(response);
    })()
  }
})()

```

🤮

**Comment by ry** [comment]
> There is listenAndServe(), but that doesn't return a handle to Server to be able to close it (e.g. on SIGINT).

Hmm it shouldn't be necessary to explicitly handle SIGINT. Could you open an issue for that?

**Comment by jakajancar** [comment]
I'll double-check and if it's not a problem with something on my side, open it.

But either way, I'd just like to be able to start the server, get a handle that allows me to close it, and have some concurrency. E.g. for use in end-to-end tests.

**Comment by kigiri** [comment]
```js
import { serve } from "https://deno.land/std/http/server.ts";
const s = serve({ port: 8000 });

for await (const req of s) {
  generateResponseUsingASlowDatabase().then(response => req.respond(response));
}
```
If you don't want to `await` you can use `.then` directly as it's non blocking no ?

**Comment by jakajancar** [comment]
Ah, doh, that's obvious.

**Comment by trusktr** [comment]
I think the best way is to call a single separate function in the for loop:

```js
import { serve } from "https://deno.land/std/http/server.ts"
const s = serve({ port: 8000 })
for await (const req of s) handleRequest(req)
async function handleRequest(req) {
  const response = await generateResponseUsingASlowDatabase()
  req.respond(response)
}
```

That said, something like the following would've been a fine API too:

```js
import { serve } from "https://deno.land/std/http/server.ts"
const s = serve({ port: 8000 })
s.on('request', async req => {
  const response = await generateResponseUsingASlowDatabase()
  req.respond(response)
})
```

I don't see a clear advantage of for-await-of, and some people are more prone to accidentally blocking the loop.
