### ISSUE TITLE
Possible .d.ts compiler hint issue

### ISSUE THREAD

**Issue by JoulesZapata** [denoland/deno#4313]
==========  index.ts ========== 

@deno-types="./types.d.ts"

import { getName } from './human.ts';

const name = getName({
    name: 'Ryan Dahl',
    age: 39
})

console.log(name)

========== human.ts ========== 

//@deno-types="./types.d.ts"

export const getName = (human: Human) : string => {
    return human.name
}

========== types.d.ts ========== 

type Human = {
    name: string,
    age: number
}

========== versions ========== 

deno version 0.35
v8 version 8.1.310
typescript version 3.8.2

========== bug info ========== 

Expected: "Ryan Dahl" in my console

Actually got: not "Ryan Dahl", but the compiler saying "error TS2304: Cannot find name 'Human'." as it was compiling human.ts

**Comment by nayeemrmn** [comment]
Not sure how `tsc` works, but the way `.d.ts` files are used here is you put the `// @deno-types="abc.d.ts"` above an import for the module `abc.js`.

https://deno.land/std/manual.md#compiler-hint

cc @kitsonk

**Comment by JoulesZapata** [comment]
@nayeemrmn Wouldn't that be what I have in index.ts? And also, how it would use the types inside the file that abc.ts file, does it automatically take care of that? because that's not working either

**Comment by kitsonk** [comment]
The compiler hint of `// @deno-types` is only intended for informing the compiler that there is a `.d.ts` file to use for type checking _instead_ of a JavaScript file for the next import statement.  It isn't designed to be used to just reference `.d.ts` files.

Everything in Deno is modular, with dependencies very clear.  There are obtuse ways to utilise ambient declarations in Deno (non-modular `.d.ts` files), but please don't.  Please use modular declarations:

**types.d.ts**

```ts
export type Human = {
  name: string,
  age: number
};
```

And then:

```ts
import { Human } from "./types.d.ts";

export const getName = (human: Human) : string => {
  return human.name;
}
```

There is then no need to import or reference the file in the `index.ts`.  Modules, modules, modules!

**Comment by JoulesZapata** [comment]
@kitsonk that's what I have been doing, and I guess there is nothing wrong with that, but is it not still a bug?

**Comment by kitsonk** [comment]
No, you are mis-using the syntax.

```
// @deno-types="./types.d.ts"
```

Says to the compiler, instead of using the next import of a module (which should be a JavaScript file) in type checking, use `./types.d.ts` instead.  That is not what you wanted at all.  Like I said, there are obscure ways to do what you were trying to do, but I am not going to tell you how to do them, because it is a bad idea, and not something we want to really support.

If you use something wrong, I am afraid that isn't a bug.

**Comment by JoulesZapata** [comment]
Not a bug
