### ISSUE TITLE
docs: write docs for Web APIs

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#4325]
Deno strives to be browser compatible where possible; that means we use quite a few Web APIs. 

There is not much docs for supported Web APIs at the moment and before 1.0 is released that situation must change. Some of APIs and not fully aligned to spec, while others are not fully implemented (#3557). All that knowledge should be written down and presented to end users to avoid multiple questions/bug reports about purposeful incompatibilities and/or missing implementations.

**Comment by kitsonk** [comment]
The manual is getting a bit heavy/complex.  Should we identify first a structure of documents/pages that we would want to cover. [lib.deno.shared_globals.d.ts](https://github.com/denoland/deno/blob/master/cli/js/lib.deno.shared_globals.d.ts) and [lib.deno.window.d.ts](https://github.com/denoland/deno/blob/master/cli/js/lib.deno.window.d.ts) provide available Web APIs that are not part of ECMAScript that Deno currently supports.

**Comment by bartlomieju** [comment]
> The manual is getting a bit heavy/complex. Should we identify first a structure of documents/pages that we would want to cover. [lib.deno.shared_globals.d.ts](https://github.com/denoland/deno/blob/master/cli/js/lib.deno.shared_globals.d.ts) and [lib.deno.window.d.ts](https://github.com/denoland/deno/blob/master/cli/js/lib.deno.window.d.ts) provide available Web APIs that are not part of ECMAScript that Deno currently supports.

I strongly agree on manual, but I'd prefer to get ball rolling on this subject. We're definitely gonna put more effort into restructuring docs after API freeze in the end of April. For now I think it's fine to extend manual.

**Comment by ematipico** [comment]
Hi there! I'd like to to take a stab to this issue, as it is marked as good first issue.

What should I do to help and how?

**Comment by bartlomieju** [comment]
@ematipico thanks! The very first thing would be to extend `cli/js/web/README.md` with a list of all supported Web APIs (so all APIs in `cli/js/web/` that are exposed globally).

**Comment by ondras** [comment]
@ematipico are you still working on this? I can start doing this if you do not have time.

**Comment by ematipico** [comment]
Hi @ondras, yeah feel free to go ahead! I got a mix up with my plans and I don't have much time now. Thank you and sorry!

**Comment by ondras** [comment]
> @ematipico thanks! The very first thing would be to extend `cli/js/web/README.md` with a list of all supported Web APIs (so all APIs in `cli/js/web/` that are exposed globally).

@bartlomieju would something like https://github.com/ondras/deno/blob/web-docs/cli/js/web/README.md make sense to you? What would be next?

I am somewhat unsure about the `streams/` subdirectory that contains quite a bit of a Streams implementation, but most of it seems to be commented out. Looks like a WIP, so probably not ready for public documentation.

**Comment by bartlomieju** [comment]
@ondras yeah that looks good! Next step would be to expand description for each API with its caveats (if there are any, eg. `Worker` doesn't support structured clone right now).

> I am somewhat unsure about the `streams/` subdirectory that contains quite a bit of a Streams implementation, but most of it seems to be commented out. Looks like a WIP, so probably not ready for public documentation.

That's correct, `streams` can be skipped for now.

**Comment by ondras** [comment]
> Next step would be to expand description for each API with its caveats (if there are any, eg. `Worker` doesn't support structured clone right now).

Great! May I publish the change now? I am afraid I cannot reliably describe individual caveats related to the implementation, as I am not the author of these modules. Will try to add some rudimentary description of what the stuff does, though.

**Comment by ondras** [comment]
> @ondras yeah that looks good! Next step would be to expand description for each API with its caveats (if there are any, eg. `Worker` doesn't support structured clone right now).

@bartlomieju I pushed another update with some rudimentary description texts and implementation notes for some APIs.

**Comment by bartlomieju** [comment]
@ondras feel free to open a PR, we can iterate there

**Comment by ondras** [comment]
Great, opened https://github.com/denoland/deno/pull/4578.

**Comment by euanmat** [comment]
Hello, help wanted ? 

Can I help in some way ?

**Comment by cknight** [comment]
Looks like streams could be added now?  Assuming @kitsonk is finished?

**Comment by kitsonk** [comment]
the `TranformStream` is still waiting to be merged

**Comment by douglaschalegre** [comment]
Hello! There still is something to be added to Web APIs docs? i would like to help if needed

**Comment by ktfth** [comment]
I can help too on that issue, what have to be done?

**Comment by keshav-bohr** [comment]
Would like to help. Let us know

**Comment by gungunfebrianza** [comment]
I really want to help also, let us know :) i was playing with Performance API last time :)

**Comment by patodeturing** [comment]
I would really like to contribute, How can I support ?

**Comment by waldyrious** [comment]
Looks like there's some overlap between [runtime/js/README.md](https://github.com/denoland/deno/blob/v1.6.3/runtime/js/README.md) and [docs/runtime/web_platform_apis.md](https://github.com/denoland/deno/blob/v1.6.3/docs/runtime/web_platform_apis.md). It may be worth at least adding a link from that README to the docs page, so content duplication and possible divergence can be avoided.

**Comment by LukasDoesDev** [comment]
While playing around with Deno Deploy I noticed that `BroadcastChannel` does not have proper documentation at [doc.deno.land](https://doc.deno.land/builtin/stable). I also saw that this issue is marked as a good first issue so how can I help?

**Comment by bartlomieju** [comment]
I'm going to close this issue now as Web APIs supported by Deno are now listed in MDN.
