### ISSUE TITLE
cleanup: remove docstrings from cli/js/ directory

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#4326]
`cli/js/` directory holds all of internal runtime code. Due to the way we ship the code, we ended up with situation where some of the docstrings are duplicated in declaration files (`lib.deno.ns.d.ts`, et al) as well as implementation files. It's mundane and error-prone to synchronise them manually so until we bring back auto-generation of declaration files docstrings should be removed from implementation code (that means docstrings should be left only in declaration files).

**Comment by kitsonk** [comment]
Our future selves are going to hate us, but it is a valid point.  I guess when we restore it, we should find a way to move the comments back.
