### ISSUE TITLE
discussion: Add --experimental flags for features that won't be stable for 1.0

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#4334]
These would be for all of the features which deno currently has but don't have a stable API yet.

An example of this are plugins (`--experimental-plugins`), which we probably can't stabilize before op crates (#2180) are added because they would probably share a lot of infrastructure in `deno_core`.

**Comment by lucacasonato** [comment]
Now that we have a `--unstable` runtime flag, the next question that comes up is if the unstable JS APIs should even be present on the Deno global if the `--unstable` flag is not present. I personally think they shouldn't. The next question after that is if the `unstable` ops should even get registered on the isolate if the flag is not present.

I think not exposing the unstable functions on the `Deno` global and unstable methods on classes like `Process` should be a 1.0 blocker. This would have to be combined with a `lib.deno.unstable.d.ts` file to correctly do type checking on the `--unstable` channel. @kitsonk did most of this work already in #4639.

**Comment by ry** [comment]
Yes I think we should not expose them on the global and also update the types as @kitsonk did. I'd welcome an adaption of #4639

**Comment by lucacasonato** [comment]
I’ll do this.
