### ISSUE TITLE
Missing -c Option On Deno Info

### ISSUE THREAD

**Issue by Skillz4Killz** [denoland/deno#4335]
`deno info` is missing the config option.

![image](https://user-images.githubusercontent.com/23035000/76546987-d2892f80-6462-11ea-9338-277a03c22553.png)

![image](https://user-images.githubusercontent.com/23035000/76547019-e0d74b80-6462-11ea-9e9a-af24d4d6a1bf.png)

**Comment by kitsonk** [comment]
What is the use case?  How would you expect a `tsconfig.json` to change the output of `deno info`?

**Comment by lucacasonato** [comment]
`deno info` first runs TS thru the TS compiler. The config is for the TS compilation that happens before the actual info getting takes place.

**Comment by kitsonk** [comment]
Again, what is the use case? How would you expect a `tsconfig.json` to change the output of `deno info`?  I do understand how it works, I am just trying to figure out under what conditions it would change anything.

**Comment by bartlomieju** [comment]
We need to land #4140 to get rid of TS compiler altogether for `deno info`...

**Comment by kitsonk** [comment]
Which would make `-c` totally useless for `deno info`, which is basically my point, it is useless now.  If people are using it to do a type check on their code, that is not the intention of `deno info`, that is the intention of the badly named `deno fetch`.

**Comment by bartlomieju** [comment]
> Which would make `-c` totally useless for `deno info`, which is basically my point, it is useless now. 

Yeah, I get to deps inspector eventually..

> If people are using it to do a type check on their code, that is not the intention of `deno info`, that is the intention of the badly named `deno fetch`.

Agreed

**Comment by kitsonk** [comment]
So this can be closed.

**Comment by bartlomieju** [comment]
Actually, one thing to consider even with `swc` based inspector is that we return this bit for .ts files:
```
type: TypeScript
compiled: /Caches/deno/gen/https/deno.land/std/http/server.ts.js
map: /Caches/deno/gen/https/deno.land/std/http/server.ts.js.map
```
That would still need TS compiler...

**Comment by kitsonk** [comment]
Still doesn't mean `-c` makes any sense for `deno info`.  What would it change?

**Comment by hayd** [comment]
--importmap would have an effect though?

**Comment by kitsonk** [comment]
Yes. Though that isn't what this issue is about.

**Comment by nayeemrmn** [comment]
We don't need to enable config for every subcommand that compiles, they can always use a different config when they're actually running or pre-fetch before doing either to avoid compiling twice. (We also need Deno to recompile a module every time a different config is used, or cache different copies for each config's hash.)

> Actually, one thing to consider even with `swc` based inspector is that we return this bit for .ts files:
> 
> ```
> type: TypeScript
> compiled: /Caches/deno/gen/https/deno.land/std/http/server.ts.js
> map: /Caches/deno/gen/https/deno.land/std/http/server.ts.js.map
> ```
> 
> That would still need TS compiler...

@bartlomieju We can just null those bits for non-compiled modules. What's wrong with that? It might actually be useful to know if a module is in your cache already or not.

**Comment by Skillz4Killz** [comment]
@kitsonk The initial goal was to find a way to have `tsc --watch` like functionality. tsc does not work well with deno so I was looking for alternatives. After discovering 99% of the deno tsconfig was the same as mine(love strict mode) I simply removed my custom config. Although that solved my need for a -c option. I still believe it would be very useful to devs like me to have a --watch functionality during development.
