### ISSUE TITLE
Enable noUnusedLocals and noUnusedParameters In Default Config

### ISSUE THREAD

**Issue by Skillz4Killz** [denoland/deno#4339]
Is there any reason these two options were not enabled in the default config? Can we have them enabled since i believe majority of users would prefer clean code and this would cause a need to create and use a custom tsconfig.

**Comment by lucacasonato** [comment]
For reference - Go does not allow unused locals and imports either, but it does allow unused parameters. Go has the `_ = myvar` syntax to suppress this error, TS does not.

**Comment by Skillz4Killz** [comment]
@lucacasonato You can add a _ in front of the parameter and TS will ignore that error.

![image](https://user-images.githubusercontent.com/23035000/76557149-5f3aea00-6471-11ea-8247-ef55529eba9f.png)

![image](https://user-images.githubusercontent.com/23035000/76557161-6530cb00-6471-11ea-9970-51d797965e42.png)

**Comment by kitsonk** [comment]
I've always felt that this is a linting issue (I argued that at the time they were introduced into TypeScript).  I would rather support `deno lint` (#1880 ) than change these as a default compile option in Deno.

**Comment by ry** [comment]
I agree with @kitsonk.

There are good reasons to disable these configurations - the intention is not to be maximally strict - when you're in the middle of development warnings like these can defeat the purpose of using a dynamic language in the first place. The great benefit of TypeScript, in my view, is that you can start programming very fast and sloppy without any types and as the code moves from prototype to production crank up the safety guarantees.
