### ISSUE TITLE
Deno's TypeScript does not handle triple slash directive (<reference path="..." />)

### ISSUE THREAD

**Issue by KSXGitHub** [denoland/deno#4343]
I created two files in a [gist](https://gist.github.com/KSXGitHub/659ea9774bec9ebab050fa0820d45540).

Then I created this file:

```typescript
// test.ts
import always from 'https://gist.githubusercontent.com/KSXGitHub/659ea9774bec9ebab050fa0820d45540/raw/7d746c5a0a43a34e5dc85bc62569b164eec909f7/index.js'
const f = always<5>(5)
const passed: 5 = f() // expect no error
const failed: 6 = f() // expect compilation error
console.log({ passed, failed })
```

I ran this command:

```sh
deno run test.ts
```

I expect a compile error at line `const failed: 6 = f()` but no error occurs.

---

**`deno --version`**

```
deno 0.36.0
v8 8.1.310
typescript 3.8.3
```

---

I have also tried changing `path` to absolute URL, but it still does not work.

**Comment by kitsonk** [comment]
I don't believe you have isolated the problem correctly.  When I run your example I get:

```
Compile file:///Users/kkelly/github/deno/test.ts
Download https://gist.githubusercontent.com/KSXGitHub/659ea9774bec9ebab050fa0820d45540/raw/7d746c5a0a43a34e5dc85bc62569b164eec909f7/index.js
Download https://gist.githubusercontent.com/KSXGitHub/659ea9774bec9ebab050fa0820d45540/raw/7d746c5a0a43a34e5dc85bc62569b164eec909f7/index.d.ts
```

The file is requested as appropriate.  Something else is going on here.

**Comment by KSXGitHub** [comment]
@kitsonk You ran without error, yes? That IS the problem. I expected Deno to emit a TypeScript error, but it didn't.

**Comment by KSXGitHub** [comment]
@kitsonk I also expect [Deno Language Server for VS Code](https://marketplace.visualstudio.com/items?itemName=axetroy.vscode-deno) to show correct type, but it shows `any` everywhere.

**Comment by kitsonk** [comment]
I just realised, it is working as designed.  [Please refer to the documentation](https://deno.land/std/manual.md#triple-slash-reference-directive-in-javascript-files).

```js
/// <reference types="./index.d.ts" />
export const always = x => () => x
export default always
```

**Comment by KSXGitHub** [comment]
Oh.

`types` and `path`, this is confusing!
