### ISSUE TITLE
Implement `message` event in `WorkerImpl`

### ISSUE THREAD

**Issue by aduh95** [denoland/deno#4344]
The following code should work as in browsers:

```js
const worker = new Worker('./worker.js', {type:'module'});
worker.addEventListener('message', console.log); // no op on Deno
```

Currently, only `worker.onmessage =` is supported and the argument passed to the "event handler" is not an actual `Event` object.

My guess is we should be creating an `Event` in this block and call `this.dispatchEvent`:
https://github.com/denoland/deno/blob/e435c2be158ce8657dbff0664b6db222fe4e586c/cli/js/web/workers.ts#L131-L137

**Comment by bartlomieju** [comment]
Yes, this is still in my backlog

**Comment by bartlomieju** [comment]
`WorkerImpl` already extends `EventTarget` but neither `error` nor `message` events are dispatched on it. 

For `message` event; as @aduh95 suggested above, a call to `this.dispatchEvent` should be added to that block; something like:
```ts
const ev = new Event("message", { cancelable: false });
ev.data = event.data;
this.dispatchEvent(ev);
```

For `error` event; a `dispatchEvent` call should be added to `WorkerImpl.handleError` method. 

Declaration file containing `Worker` and `WorkerImpl` should also be updated; it's `cli/js/lib.deno.shared_globals.d.ts. It's essential to add proper types for both events. 

Here's specification for both events:
- https://html.spec.whatwg.org/multipage/comms.html#messageevent
- https://html.spec.whatwg.org/multipage/webappapis.html#errorevent


And here's declaration for worker in `typescript`:
```ts
interface Worker extends EventTarget, AbstractWorker {
    onmessage: ((this: Worker, ev: MessageEvent) => any) | null;
    postMessage(message: any, transfer: Transferable[]): void;
    postMessage(message: any, options?: PostMessageOptions): void;
    terminate(): void;
    addEventListener<K extends keyof WorkerEventMap>(type: K, listener: (this: Worker, ev: WorkerEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
    addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
    removeEventListener<K extends keyof WorkerEventMap>(type: K, listener: (this: Worker, ev: WorkerEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
    removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
}
```
https://github.com/microsoft/TypeScript/blob/712967b2780e8ecd28f8f1e2e89c1ebd2592bb4c/src/lib/webworker.generated.d.ts

Tests demonstrating handling events added using `addEventListener` should be added to `cli/tests/workers_test.ts`.

Here's WIP branch of mine:
https://github.com/bartlomieju/deno/tree/worker_events

CC @crowlKats
