### ISSUE TITLE
Use swc instead of source-map-mappings for source maps

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#4348]
Yet another place where we want to use `swc` is source maps. `swc` has [`SourceMap`](https://swc-project.github.io/rustdoc/swc_common/struct.SourceMap.html) struct, that might be used for that purpose.

Currently source maps are generated by TS compiler and `source-map-mappings` crate is used to perform the lookup.

To boil down: wanted ability to parse `tsc` generated source map file in `swc` and provide high level interface to lookups using interface shown below:
```rust
pub trait SourceMapGetter {
  fn get_source_line(
    &self,
    script_name: &str,
    line_number: usize,
  ) -> Option<String>;
  fn get_original_position(
    &self,
    script_name: String,
    line_number: i64,
    column: i64,
  ) -> (String, i64, i64);
}
```

Ref #3983 #4323 #4140 

CC @ry @kdy1

**Comment by kdy1** [comment]
I think sec_common need some revamp.
I copied it from rustc source code, and caego works by creating multiple process. Due to multi-proxess aproach, rustc just leaks sourcemap.

I'm consideriing api like SourceMap.remove or storing Weak<SourceFile> instead of Arc<SourceFile>, but I'm not sure about it at now.

**Comment by kitsonk** [comment]
What is insufficient with the Rust crate we already use for source map remapping, it is the one from the team that created source maps to begin with.  Why move it to swc????

**Comment by bartlomieju** [comment]
@kitsonk `source-map-mappings` crate is sufficient, but it is very outdated causing our binary to have multiple versions of same crates. 

@kdy1 I read through Cargo.toml in sec repo and it seems your using `sentry/sourcemap` crate. It's API is very similar to `source-map-mappings` so I'll try to switch the crates
