### ISSUE TITLE
Bug: Promises don't handle asynchronous errors correctly

### ISSUE THREAD

**Issue by timonson** [denoland/deno#4350]
The following example is pretty much self-explanatory:

```javascript
new Promise(function(resolve, reject) {
  setTimeout(() => {
    throw new Error("Whoops!")
  }, 1000)
}).catch(console.log)
```

Instead of throwing the `Error` deno ignores it.

**Comment by kevinkassimo** [comment]
The problem here is not about why `.catch()` does not work (it is expected to not catch anything here).
Instead the main problem is that errors thrown in `setTimeout` is not properly logged and terminate the program.

An actual problem that causes this behavior is that `queueMicrotask` (used by timers) does not terminate the program on uncaught errors, e.g.
```js
queueMicrotask(() => { throw new Error("123"); });
// no error logged and program continues for future microtasks
```

**Comment by hayd** [comment]
I've also seen if you don't await certain promises the program never exits.
But haven't been able to get a clean example...

**Comment by bartlomieju** [comment]
Tested with `v0.42.0`:
```
// test.js
new Promise(function(resolve, reject) {
  setTimeout(() => {
    throw new Error("Whoops!")
  }, 1000)
}).catch(console.log)

$ deno test.js
error: Uncaught Error: Whoops!
    throw new Error("Whoops!")
          ^
    at file:///Users/biwanczuk/dev/deno/test.js:3:11
    at fire ($deno$/web/timers.ts:179:3)
    at handleTimerMacrotask ($deno$/web/timers.ts:44:5)
```

Seems it's been fixed.

**Comment by Liamolucko** [comment]
It's been fixed for `setTimeout()`, but not `queueMicrotask()`.

This code will continue to run:
```typescript
queueMicrotask(() => {
  throw new Error("Whoops!");
});

setInterval(() => {}, 100);
```

**Comment by bnoordhuis** [comment]
I've opened https://github.com/denoland/rusty_v8/issues/574, that's one avenue for fixing this issue.

Other avenues are the debug inspector (can catch uncaught exceptions) or add more hooks to V8.

**Comment by nayeemrmn** [comment]
We should close this in favour of #14158 for clarity
