### ISSUE TITLE
Request: inspect-like API

### ISSUE THREAD

**Issue by KSXGitHub** [denoland/deno#4361]
Node.js has `util.inspect` function that converts any type of object to string as it appears in debugging console. It also has `util.inspect.custom` symbol for customization.

Deno should support them too, preferably in `/std`, but a native function is also fine.

**Comment by kitsonk** [comment]
It already does. `Deno.symbols.customInspect` and that us used by `console.log`.

**Comment by JavaScriptDude** [comment]
Ignoring the custom inspect, how about the `util.inspect()` that returns a string without calling console.log()? That part of the question is not answered.

This feature would be very handy.

**Comment by KSXGitHub** [comment]
@JavaScriptDude There is already `Deno.inspect`

**Comment by JavaScriptDude** [comment]
Sweet. Thanks!
