### ISSUE TITLE
console.log({ [Symbol.toStringTag] })

### ISSUE THREAD

**Issue by KSXGitHub** [denoland/deno#4362]
`console.log` should treat `[Symbol.toStringTag]` property as class name, that is:

When running this code:

```javascript
console.log({
  abc: 123,
  [Symbol.toStringTag]: 'Foo',
});
```

Print this:

```
Foo { abc: 123 }
```

instead of this:

```
{ abc: 123 }
```

**Comment by kevinkassimo** [comment]
This is the behavior in Chrome, while Node/Safari has not implemented.

My understanding is that we could use this if passed in object does not come from a class. The main purpose of `Symbol.toStringTag` is for `.toString()`, which we don't normally use in console display.

**Comment by KSXGitHub** [comment]
@kevinkassimo 

> Node/Safari has not implemented.

Node does recognize `[Symbol.toStringTag]`: 
![screenshot](https://user-images.githubusercontent.com/11488886/76715148-8806fc00-675d-11ea-948b-e199f6efdeb6.png)

I don't know about Safari, but how many modern web features does Safari implemented?

**Comment by kevinkassimo** [comment]
@KSXGitHub Seems to be limited in this case.
```
// Chrome:
> console.log(Object.create({ [Symbol.toStringTag]: '123' }));
123 {}
> console.log({ [Symbol.toStringTag]: '123' });
123 {Symbol(Symbol.toStringTag): "123"}

// Node 13.3.0
> console.log(Object.create({ [Symbol.toStringTag]: '123' }));
Object [123] {}
> console.log({ [Symbol.toStringTag]: '123' });
{ [Symbol(Symbol.toStringTag)]: '123' }
```

While console has a standardized API, there is not really a standard about what should be printed to console. Also Safari does implement many of the modern web features, and is fully compliant with web-platform-tests console requirements per https://wpt.fyi/results/?label=experimental&label=master&aligned

I am now more hesitant about which behavior we should implement here after seening the comparisons

**Comment by KSXGitHub** [comment]
@kevinkassimo There isn't a standard to follow, that means we have to choose. Choosing to not implement this feature is still a choice that is not backed up by any standard. So why don't we choose to make debugging nicer?

**Comment by kevinkassimo** [comment]
@KSXGitHub I'm not say that we are not implementing this. What I meant is which flavor to implement.

**Comment by KSXGitHub** [comment]
@kevinkassimo The Chrome way is best in my opinion. The Node way is inconsistent. The Safari way is anathema to my request.

**Comment by kitsonk** [comment]
We tend to follow Node.js.  We already have issue #3165.  Feels like this concept should apply here too.

**Comment by kevinkassimo** [comment]
@kitsonk IMO I do like the behavior of Chrome better here. I don't really know how far should we follow the style of Node, since Node still occasionally change console output

**Comment by kitsonk** [comment]
> I don't really know how far should we follow the style of Node

🤷‍♂ I don't know either, but I guess if we are willing to take the "but this doesn't match Node.js" situations. Intentional variation is better than unintentional.
