### ISSUE TITLE
Request for `deno test`: Run every single test in isolation; And window.location.pathname should be URL of the test file

### ISSUE THREAD

**Issue by KSXGitHub** [denoland/deno#4366]
## Reasons

* Tests should be isolated from each other, to not affect each other.
* Reduce the differences between running a test (`deno test`) and running a script (`deno run`).
* And to make https://github.com/denoland/deno/issues/3635#issuecomment-599023737 possible.

**Comment by ry** [comment]
The unit tests in `cli/js/tests`, I guess you mean? We've discussed it - it seems desirable - but we're also concerned about how long it will take to start up an isolate for each test.

**Comment by KSXGitHub** [comment]
We can run them in parallel.

**Comment by KSXGitHub** [comment]
BTW, to be clear, I am talking about `deno test` that Deno users use to test their code, not about how Deno itself should be tested.

**Comment by bartlomieju** [comment]
`deno test` now runs *each module* in isolation and we currently don't plan to isolate per-test case as the overhead of creating new isolates was too great.
