### ISSUE TITLE
Coherence in the http documentation

### ISSUE THREAD

**Issue by lucas-deangelis** [denoland/deno#4367]
I'm trying to use the http module for a small project, and while at it I wanted to add a bit of documentation for listenAndServe. There's a problem though: serve is described as "Start a HTTP server", serveTLS as "Create an HTTPS server with given options", and listenAndServeTLS as "Create an HTTPS server with given options and request handler".

Maybe I'm missing something, but I think they should be the same, with the only difference being "HTTP" or "HTTPS". Another option would be to describe functions that returns a Server as "creating", and those who don't as "starting".

I'll add a pull request to help clarify what I think would be best.

**Comment by bartlomieju** [comment]
Documentation is always a very welcome contribution
