### ISSUE TITLE
shall We replace unwrap() with '?' wherever possible?

### ISSUE THREAD

**Issue by bartOssh** [denoland/deno#4374]
for example here: https://github.com/denoland/deno/blob/62f4a2a788a46af88e47472738d1a98fa247b9b0/cli/lib.rs#L356
we can do `let main_module = ModuleSpecifier::resolve_url_or_path(&script)?;`

**Comment by ry** [comment]
Yes, where possible.

**Comment by bartOssh** [comment]
I will try to find some time to go through code and propose changes.
