### ISSUE TITLE
Support `--importmap` with `deno bundle`

### ISSUE THREAD

**Issue by davidbailey00** [denoland/deno#4379]
## Reproduction steps

1. Create a script with some imports, e.g. `index.js`
2. Create an import map to resolve these imports, e.g. `import-map.json`
3. Run `deno bundle --importmap=import-map.json index.js`

Example where this can be reproduced: https://github.com/davidbailey00/deno-npm-demo

## Expected result

It works, like with `deno --importmap=import-map.json index.js`

## Actual result

The following output is displayed:

```
error: Found argument '--importmap' which wasn't expected, or isn't valid in this context

USAGE:
    deno bundle [OPTIONS] <source_file> [out_file]

For more information try --help
```

## Additional notes

I would love to create a PR to support this, but might need some pointing in the right direction since I'm relatively new to Rust programming! Would it be a matter of adding `.arg(importmap_arg())` to the [`bundle_subcommand`](https://github.com/bartlomieju/deno/blob/master/cli/flags.rs#L619-L636) function?

Based on #2687 I would expect this to already work, though it looks the behaviour has changed since this PR?

**Comment by kitsonk** [comment]
I suspect so.  There really shouldn't be much more than accepting it just like the `run` subcommand.  The rest of the infrastructure should "just work".

**Comment by davidbailey00** [comment]
I tried that and got the following error instead:

```
$ ~/Code/Rust/deno/target/debug/deno bundle --importmap=web_modules/import-map.json demos/preact.js
error: Uncaught URIError: relative import path "htm/preact" not prefixed with / or ./ or ../ Imported from "file:///Users/david/Code/JavaScript/deno-npm-demo/demos/preact.js"
► $deno$/ops/dispatch_json.ts:43:11
    at unwrapResponse ($deno$/ops/dispatch_json.ts:43:11)
    at sendSync ($deno$/ops/dispatch_json.ts:72:10)
    at resolveModules ($deno$/ops/compiler.ts:11:10)
    at resolveModules ($deno$/compiler/imports.ts:63:22)
    at processImports ($deno$/compiler/imports.ts:147:27)
    at processImports ($deno$/compiler/imports.ts:156:13)
```

It seems that the argument is parsed correctly but the `bundle` subcommand doesn't make use of it...

**Comment by kitsonk** [comment]
I don't have everything in my head at the moment to give you strong guidence, but if it were me, I would compare:

```
$ deno -L debug bundle --importmap=web_modules/import-map.json demos/preact.js
```

With:

```
$ deno -L debug run --importmap=web_modules/import-map.json demos/preact.js
```

The TypeScript `cli/js/compiler.ts` resolves modules in exactly the same way, so it is likely something is not being set in `cli/file_fetcher.rs` but I don't know the whole import maps logic that well.  IIRC @kevinkassimo had a hand in the implementation.

**Comment by noteScript** [comment]
> I expect to support -- importmap during installation。

#### example：

```bash
deno install --unstable --importmap=import_map.json test test.ts
```
