### ISSUE TITLE
lint: add "require-await" rule to ESLint config

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#4394]
https://eslint.org/docs/rules/require-await

> There is an eslint rule of [`require-await`](https://eslint.org/docs/rules/require-await) which would catch this as well. With TypeScript checking the return type it is very unlikely enforcing this would cause incorrect behaviour.

@kitsonk I did a quick check and we'd have to add a lot of supressions to tests (because there's a lot of mocks that assert async functions were called). I'm open to that change, but I'd open a new issue for that.

_Originally posted by @bartlomieju in https://github.com/denoland/deno/pull/4384#issuecomment-599469694_

A new rule "require-await" should be added to `.eslintrc.json`; then code in `core/`, `cli/` and `std/` should be linted accordingly.

**Comment by samrith-s** [comment]
I can pick this up. :)

**Comment by bartlomieju** [comment]
@samrith-s Great! It should be an error

**Comment by samrith-s** [comment]
Gotcha, and I'm guessing I need to run the linter as well on all the files?

**Comment by bartlomieju** [comment]
Yes, after adding new rule, make sure that `tools/lint.py --js` passes 👍

**Comment by kitsonk** [comment]
I was thinking about your comment, I suspect we have a lot of mocks that are using `async` to generate a Promise return (otherwise I can't figure out what the problem is).  If we have something like this:

```ts
async function foo() { return "foo"; }
```

It needs to be changed to:

```ts
function foo() { return Promise.resolve("foo"); }
```

**Comment by samrith-s** [comment]
Hey,

Can someone look at my PR #4401 and check if what I'm doing is okay? It's a lot of files changed, and I do not want to proceed in the wrong direction.

From what I discerned, a lot of the functions do not require an `async` but as some rule, all of the have their return types annotated to `Promise<DATA_TYPE>`.

**Comment by kitsonk** [comment]
@samrith-s yes, thank you, looks good so far!  What I expected (after @nayeemrmn feedback about not changing the return type by using `Promise.resolve(...)`.

**Comment by samrith-s** [comment]
Cool,

The build is failing and I am not able to setup TS to compile the files. I did recourse the submodules while cloning, but nothing seems to work. 

So for now, I’m actually using the CI to figure out the errors. 

Can anyone help me in setting it up? I have Rust, Python2 all setup. But when I run `python ./tools/lint.py` I get an error that says ESLint was not found in third party node modules.

**Comment by kitsonk** [comment]
hrmmm... usually cloning recursively works... once cloned `git submodule update` should ensure that the sub modules are checked out properly...  You still need a version of Node.js installed and available in the path too, outside of Rust and Python2.

**Comment by samrith-s** [comment]
I have all of that, but when I did `git submodule update`, it just downloaded 'Typescript`. My `third_party` folder is still empty.

It's a pain to debug issues since the getting started docs are very vague, and there's absolutely no troubleshooting FAQs or something.

**Comment by bartlomieju** [comment]
@samrith-s try `git submodule update --init --recursive`

**Comment by samrith-s** [comment]
Nope, nothing. My `third_party` folder is still empty. I don't know why it doesn't resolve it. I will delete the repo and retry it.

**Comment by jimmywarting** [comment]
I have not liked this rule

The problem, take the code below.

`async function test() { throw new Error("test"); }`

There is no await, but what the async does here is guarantee a Promise. So the following code will return got.

`test().catch(function (e) { console.log("got"); })`

Take away the async and the above code is going to fail big time Now if you can guarantee you are always going to call test with await, you are ok again as await will check if it's a Promise, but if you sent this to any other other Promise based consumers you have the above issue.

This can cause issues for people who are currently mixing Promise & async / await (like me)
I'm building polyfills and the spec says it should return/guarantee a promise. the polyfill is all synchronous but should behave async. Can be common when building mock functions also

I have encounter numerus time someone is doing something like this 

```js
/**
 *  @return promise
 */ 
function signup (usr, psw) {
  if (!usr || !psw) throw new Error('missing args')
  return mongodb.save(usr, psw)
}
```

This is bad code. No async where used cuz it didn't use await but it did validation and linter would complains about it if you where using async without await

Another thing is that code can detect if a function is async just by looking at the constructor `fn.constructor.name === 'AsyncFunction'` this can do different things depending on if it's sync or async, it's undetectable if you must return a Promise.resolve instead

...I can also see in your own repo that you have disabled it on some certain places

I don't think linters should enforce style rules. It should only detect errors such as duplicated variables, uses `this` before calling `super()` etc.
A linter should be as unopinionated as possible and fit everyones need, specially when faced to the public. We should not have to turn off rules. Everything that is valid to do should be allowed. A linters should be config-less. it should just work for everyone.
When it comes to your own organisation or project, then you can enforce whatever stylish/best practise rules you want, `;` or no `;`, tab vs space etc

This rule should be off by default

**Comment by shabbyrobe** [comment]
@jimmywarting - I agree that this should be off by default. Many times I have run into situations where something changes inside a function that removes the need for an `await`, but I still want to report to consumers of the API to _expect_ that it's still `async` in practice, when used. This could be either because I intend to move back to an implementation that does call await, or I wish to reserve the right to do so in future.

**Comment by tjconcept** [comment]
I too, belong to the group that thinks this rule is a poor recommendation.

I'd propose another rule: if a function may return a promise, it should be marked `async` to show and guarantee it always will.

> If we have something like this:
> 
> ```
> async function foo() { return "foo"; }
> ```
> It needs to be changed to:
> 
> ```
> function foo() { return Promise.resolve("foo"); }
> ```

I think this is a great example why the `async` keyword should be used more broadly than for `await` syntax.
