### ISSUE TITLE
Feature request:  Add 'access' to get a user's permissions for the file or directory

### ISSUE THREAD

**Issue by cknight** [denoland/deno#4405]
This feature would allow a user to get the permissions of a file or directory.  See also Node's [API](https://nodejs.org/api/fs.html#fs_fs_access_path_mode_callback).  This is also relevant to #3403, allowing us to provide a polyfill for fs.access in `std/node`.

cc: @dubiousjim

**Comment by kevinkassimo** [comment]
We essentially need a fs permission check binding for Windows (`PermissionsExt` suffice under unix, but Windows specific info is not available through std and might require explicit use of methods from `winapi` crate)
