### ISSUE TITLE
lint: disable "explicit-function-return-type" rule in ESLint config

### ISSUE THREAD

**Issue by Skillz4Killz** [denoland/deno#4409]
![image](https://user-images.githubusercontent.com/23035000/76875505-0095b780-6847-11ea-9f2e-b27357419b55.png)

This is a rule that is being brought into deno because of the recommended options. It has **severe** impacts on a developer experience making devs hate having to code for redundant things especially when something can be automated. Typescript is an amazing tool that has amazing inference abilities. This rule is really more harmful than helpful. Not only does it create a worse developer experience but it also is more error prone because of human error. A user can explicitly provide a type that is correct but still cause bugs.

The code below is a real world example of how explicit return types can cause unintended bugs. This code actually created an infinite loop which would break my entire project and took me hours to figure out by having to console.log line by line until i found out this was the function causing it. I started to ask myself why TS wasn't throwing any errors. After some testing, I discovered it was because of the explicit cast of the return type. As soon as I deleted that return type, TS started warning me. The explicit return type was actually hiding errors TS could have warned us about. I even had a chat with the other dev about this on why explicit typing of return functions are so much more error prone. This was when i started enforcing this on my project to not allow explicit return types any more. The code inside the function satisfies the `Promise<void>` ts check with strictest configs and yet its totally bugged.

```ts
async sendConstantHeartbeats (interval: number, previousSequenceNumber: number | null = null, shouldContinue: () => boolean = () => true): Promise<void> {
        await delay(interval);

        if (!shouldContinue()) {
            return;
        }

        // TODO: If the initial seq num is null, this will make it forever null until a restart. Is this good?
        this.sendHeartbeat(previousSequenceNumber === null ? previousSequenceNumber : previousSequenceNumber++);
        return this.sendConstantHeartbeats(interval, previousSequenceNumber);
    }
```

In my opinion, explicit casting is a potential problem option to enable that can cause issues that are not intended due to human error when TS itself can be aware of those issues. Sometimes the machine really does know better.

Last point, this is not a TS feature, this is a linter feature which is why TS has such an amazing inference. We should not get rid of a massive benefit from TS.

---

1. Improved developer experience
2. Less error prone

If desired, it would be my pleasure to send a PR to implement this. If not, no problem.

**Comment by nayeemrmn** [comment]
What was the error in that example and the warning that helped you find it?

**Comment by Skillz4Killz** [comment]
@nayeemrmn Hey 👋 the final `return` was the error.

Goal: Keep the gateway connection alive by sending a constant heartbeat at an interval. 

In this case, nothing else could run because this function was being `await`. The explicitly typed `: Promise<void>` hid the error which helped me find this bug.

Thank you Git History.
![image](https://user-images.githubusercontent.com/23035000/76897001-4a8f9500-6869-11ea-80d1-b18ab7420fcc.png)

As soon as I removed the `return` it fixed all the issues. A bug that caused hours of wasted time debugging was hidden by explicit return types. Never Again!

**Comment by nayeemrmn** [comment]
It's clear you still don't understand what happened there... that warning is merely telling you that the return type isn't annotated and can't be inferred because it's recursive.

The bug was that you expected an infinitely recursing function to return -- and a solution was to omit `return` so the function resolves without waiting for the next recursion.

The fact that you connected these two (just because they both mention the return expression!) was a lucky coincidence. Nothing was being hidden and it doesn't prove anything.

**Comment by bartlomieju** [comment]
As discussed on Discord `explicit-function-return-type` is only used for internal Deno code (runtime in `cli/js/` as well as `std/`), we don't intend to change that.
