### ISSUE TITLE
Use high resolution timing when available for testing

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#4419]
Before v0.35.0 testing used high resolution timing when available. Now it always uses Date to do timing, which is a lot less precise than using high resolution time. Could we query to check if the HR time permission is supplied, and if it is, use hr time instead?

**Comment by bartlomieju** [comment]
That's exactly why it was changed, see my comment in: https://github.com/denoland/deno/issues/4166#issuecomment-600110890
