### ISSUE TITLE
A way to require something without caching it.

### ISSUE THREAD

**Issue by Kompwu** [denoland/deno#442]
`NodeJS` doesn't have this feature. :trollface:

**Comment by benjamingr** [comment]
@Kompwu node is stuck in CommonJS land and is struggling to move to ESM.

Deno already uses ESM (es modules) - I think it should have semantics as clear as possible and compatible with the JavaScript language and browsers

**Comment by elderapo** [comment]
module.js
```js
console.log("module");
```
index.js
```js
require("./module");
require("./module");

// prints "module" once

function requireUncached(module) {
  delete require.cache[require.resolve(module)];
  return require(module);
}

requireUncached("./module");
requireUncached("./module");

// prints "module" twice
```

If you want to `require module without caching` just delete it from cache after require finishes like:
```js
function requireUncached(module) {
  delete require.cache[require.resolve(module)];
  const required = require(module);
  delete require.cache[require.resolve(module)];
  return required;
}
```

**Comment by Kompwu** [comment]
@elderapo Why there is two time `delete require.cache[require.resolve(module)];` ? 🤔

**Comment by elderapo** [comment]
@Kompwu because without second delete statement it doesn't really `require module without caching` =).

First delete statement takes care of scenario where you require module using normal `require` function before using `requireUncached`. For example:
```js
// if you delete first delete statement
require('./module'); // prints "module"
requireUncached('./module'); // doesn't print "module" because previous "require" statement cached "./module"
requireUncached('./module'); // prints "module"
```

Second delete statement +/- does what you asked for. It clears cache after requring module ~ it requires module without caching it. It's not exactly what you asked for but it's as close as it can get (I think) without changing implementation of `require` function in NodeJS sources.
```js
// if you delete second delete statement
requireUncached('./module'); // prints "module"
require('./module'); // doesn't print "module" because previous "requireUncached" didn't remove module from cache after requiring it
```

**Comment by bartlomieju** [comment]
CC @kitsonk can you give your opinion?

**Comment by hayd** [comment]
Why would someone want this?

**Comment by ry** [comment]
Won't implement.

**Comment by apiel** [comment]
To skip the cache, you can do:
```ts
const { default: page } = await import(`file:///file.ts?${+new Date()}.ts`;);
```
And here a full example:
```ts
import { writeFileStr } from "https://deno.land/std/fs/write_file_str.ts";
async function test(n: number) {
  const file = "./file.ts";
  await writeFileStr(
    file,
    `console.log(${n});`
  );
  await import(`${file}?${+new Date()}${Math.random()}.ts`);
}
async function main() {
  await test(1);
  await test(2);
  await test(3);
}
main();
```
But this hack doesn't always work. Also if you have some import in file.ts, then those import will use the cache. I have lot of issues with my tool to implement Hot Module Reloading https://github.com/apiel/adka/blob/master/generatePages/generatePages.ts#L32

I will try another approach, that will be to copy all the source code I want to dynamically import  without cache, inside another temporary folder (everytime a different folder) therefor deno should not be able to use cache.

I understand that deno want to be as much as possible browser compatible but in another way deno run on the server and not everything can work exactly the same. So I wonder if at some point, we should not offer some solution for tools that are not intended to run in browser. With hacking around, we will find solution but would be great to have simple way to do things instead to hack...

**Comment by benjamingr** [comment]
@apiel can't you implement a loader? That is the standards compliant way afaik

**Comment by apiel** [comment]
@benjamingr what do you mean by a loader?
