### ISSUE TITLE
(Network) Proxy API 

### ISSUE THREAD

**Issue by codehz** [denoland/deno#4422]
_(Read from environment variable for proxy is unreasonable and not working in windows...)_

Yes, the Fetch API can use proxy seamlessly, but `Deno.connect` or `Deno.connectTLS` could not...

2 possible solutions:

1. Add api to retrieve proxy configuration, and add new option `proxy: ProxyConfiguration` to ConnectOption (may require new permission, or just reuse --allow-env)
2. Add new option `useSystemProxy: boolean` to ConnectOption (more secure)

**Comment by ry** [comment]
I'm not clear on what you're asking for. Maybe you can provide some sample code of how you'd like it to work?

**Comment by codehz** [comment]
@ry 
I mean we need make Deno.connect (at least TCP) and Deno.connectTLS be able to connect server through http/socks5 proxy

For now
`fetch("http://example.com"); ` will use system proxy if present

But `Deno.connect({host:"example.com", port:80})`won't, and it's impossible to use proxy (even manually) for Deno.connectTLS because proxy protocol need specific header for every packet

http proxy can be used to proxy any TCP connection by using CONNECT request.

**Comment by ry** [comment]
> http proxy can be used to proxy any TCP connection by using CONNECT request

I wasn’t aware of that. Does Node support this?

**Comment by codehz** [comment]
No built-in support, but third-party package like socks can do it
It is **possible** to write proxy client in deno, but **TLS** is a problem, I don't think it is a good idea to re-implement the tls in ts/wasm 
In addition, I think there is another idea: allow create TLS connection with user-defined reader and writer(so the proxy protocol can be implemented for tls connection in deno)

**Comment by codehz** [comment]
Due to Deno.connect won't use proxy, the builtin https://deno.land/std/ws/mod.ts cannot connect server behind firewall that require proxy

**Comment by ry** [comment]
We would like to add `window.WebSocket` soon. I suppose that should use the `HTTPS_PROXY`.

**Comment by codehz** [comment]
But I also want a more general proxy API, which allows us to implement other protocols, while supporting the use of system proxy

**Comment by kitsonk** [comment]
A lot of that proxy detection in browsers is 100% convention and not based on standards.  I did an implementation in Electron a few years back (one that offered the same proxy options most browsers do).  That being said, I can see the challenge.  It would be nice if `fetch()` at least supported out proxy detection.

In Node.js there is [getProxy](https://github.com/Rob--W/proxy-from-env which) which could be ported and integrated into `fetch()` to do most common environment specified proxies.  Ultimately it would be better to have something like this in Rust, so that remote modules could also be fetched if the proxy is configured in the environemnt.

**Comment by codehz** [comment]
the library seems only working on *nix os, and don't working on windows.(Windows don't use environment variable), since we don't have windows registry api(and I don't expect it will), it cannot be implemented in script side.

**Comment by kitsonk** [comment]
Ah, yeah, you are bringing back horrible memories of having to integrate to the Window Registry now to do the proxy detection.  Arghhhh...  I had buried that memory.

**Comment by justinmchase** [comment]
Is there an update on this? I need to connect to kafka through a proxy using `Deno.connectTls`, I'm not sure how to get it to go through the proxy.
