### ISSUE TITLE
Default to V8_BINARY build 

### ISSUE THREAD

**Issue by ry** [denoland/deno#4432]
Since #4412, we do not need to build V8 from scratch as part of a Deno build. By specifying the environmental variable `V8_BINARY` during `cargo build`, a precompiled static lib of V8 will be downloaded from [the rusty_v8 releases on github](https://github.com/denoland/rusty_v8/releases).

We would like to turn this on by default in Deno. Almost everyone does not want to build V8 from scratch. However we need to ensure Deno, and all its dependencies, can be compiled from source. Furthermore in rusty_v8 it makes sense to default to build-from-source.

I don't have a good way of solving this.

See also https://github.com/denoland/rusty_v8#binary-build

**Comment by kitsonk** [comment]
Default to the binary build, except when building on CI.  GitHub actions has a set of [default environment variables](https://help.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables#default-environment-variables) which could be used to detect that it is appropriate to build from source.

**Comment by hayd** [comment]
But for plugins' CI you'd want to use the v8 binary.
Also e.g. brew uses jenkins, not GH actions, so gh env sniffing doesn't help ci there.

Should this count under `DENO_NO_BINARY_DOWNLOAD` ?

**Comment by ry** [comment]
This was fixed in 5837ce464c3283dc13f7bec237902b8c637f462d
