### ISSUE TITLE
[security] Can break fine-grained --allow-read/write permissions with symlinks

### ISSUE THREAD

**Issue by dubiousjim** [denoland/deno#4437]
If `test.ts` is:
```
const { symlinkSync, readFileSync } = Deno;

try {
  const s = readFileSync("./test_private/file");
  console.log(s);
} catch(e) {
  console.log("caught", e.name);
}

symlinkSync("./test_private/file", "./test_public/file");
const s = readFileSync("./test_public/file");
console.log("success!", new TextDecoder().decode(s));
```

Then:
```
$ deno --version
deno 0.36.0
v8 8.1.310
typescript 3.8.3
$ mkdir test_private test_public
$ echo data > test_private/file
$ deno --allow-read=./test_public --allow-write=./test_public test.ts
caught PermissionDenied
success! data
```

Hence, if I know that `./test_private/file` exists, and have `--allow-read --allow-write` access anywhere, I can create a symlink to `./test_private/file` and put it in the second location, giving me (at least) read access to `./test_private/file`. (I verified that I'll also have write access to it.)

Combined with the issues in #4423, if I have only `--allow-write` but not `--allow-read` access to `./test_private`, I have the means to query the existence of any paths underneath it.

We could partly address this by having `op_symlink` require `--allow-read` access on its source file. I don't know if that would break the ability to create symlinks to non-existent paths. I don't think it would prevent one from gaining write access to any path they had read access to, if they had read/write access to any other path (such as `/tmp`).

A different strategy for addressing might be to have our `state.check_read`/`check_write` machinery follow symlinks?

**Comment by dubiousjim** [comment]
#2319 may be related.

**Comment by kevinkassimo** [comment]
Yeah I have been aware of this issue for quite a while. See more previous discussion #2318

**Comment by dubiousjim** [comment]
Among the possible strategies for fixing, one on the lighter-weight end of the spectrum might be to focus the extra checks on the creation of symlinks. And we say, "If you give someone permissions X to /dir, then they have (at least) permissions X to the targets of any symlinks that already exist under /dir."

What do you think?

**Comment by Spoonbender** [comment]
> Among the possible strategies for fixing, one on the lighter-weight end of the spectrum might be to focus the extra checks on the creation of symlinks. And we say, "If you give someone permissions X to /dir, then they have (at least) permissions X to the targets of any symlinks that already exist under /dir."
> 
> What do you think?

As mentioned in the other issue, this approach plugs some holes but not all of them.
- If the script has the ability to create symlinks to parent directories (..), then it is nearly impossible to enforce the permissions over copy/move operations.
- Even if we disallow creation, if the script has access to a .. symlink, and can move or copy the symlink or its containing directory, then it is nearly impossible to enforce the permissions.

My suggestion is either integrate with o/s mechanisms (like chroot), or: enforce the permissions on the targets of filesystem ops. This means that the script can create symlinks freely, but any op on a path with a symlink will first resolve the true target path, get an fd to it, then verify permissions on the redolved path and operate on the fd.

**Comment by nayeemrmn** [comment]
Duplicate of #2318.
