### ISSUE TITLE
How can fetch function work with a base url?

### ISSUE THREAD

**Issue by saibing** [denoland/deno#4439]
```ts
const result = await fetch("/u-route/baas/doc");
console.log(result);
```
this code worked in browser but does not in deno.  deno will output as follow:

```bash
ompile file:///data/saibing/git/ts/deno/fetch.ts
error: Uncaught URIError: relative URL without a base
► $deno$/errors.ts:35:13
    at constructError ($deno$/errors.ts:35:13)
    at unwrapResponse ($deno$/dispatch_json.ts:41:12)
    at sendAsync ($deno$/dispatch_json.ts:96:10)
```

**Comment by ry** [comment]
What would you expect to happen?

**Comment by kitsonk** [comment]
Ref #203 as well.

**Comment by nayeemrmn** [comment]
The only way thing that would makes sense is for it to work relative to cwd, the resource resolution root. so ref #2150 and see https://github.com/denoland/deno/issues/4038#issuecomment-588330318 onwards.

**Comment by saibing** [comment]
@ry 

I recently tried to use deno as my testing tool for a web server project. I want to reuse the front-end SDK library, which uses a lot of this kind URL:

```ts

   async verify (params: Object) {
     let url = "/baas/auth/v1.0/resetpassword/step?step=verify";
     const resp = await fetch (url, {
       method: "POST",
       headers: {
         "content-type": "application / json"
       },
       credentials: "same-origin",
       body: JSON.stringify (params)
     });
     const data = await resp.json ();
     if (data.resCode! == "0") {
       throw data;
     }
     return resp.headers.get ("reset-password-token");
   }
```

I want to call the verify function directly in the deno test code. I don't want to modify the verify function because there are many similar functions of this kind.

**Comment by ry** [comment]
@saibing Sure, I appreciate the goal, but where should deno get the response for "/baas/auth/v1.0/resetpassword/step?step=verify" ? There's no obvious choice for where to send the request to.

**Comment by cindRoberta** [comment]
> @saibing Sure, I appreciate the goal, but where should deno get the response for "/baas/auth/v1.0/resetpassword/step?step=verify" ? There's no obvious choice for where to send the request to.

const response = await fetch("./instagram.json")
  .then(dados => dados.json()); 

console.log(response);

error: Uncaught URIError: relative URL without a base
    at unwrapResponse (rt/10_dispatch_json.js:24:13)
    at sendAsync (rt/10_dispatch_json.js:75:12)
    at async fetch (rt/26_fetch.js:279:29)
    at async file:///home/notecomm/testes/fetchDeno.ts:1:18

**Comment by nayeemrmn** [comment]
Forgot about this issue. Update: this is answered and blocked by #4981. Any relative URL (an origin-less absolute path is still a relative URL) should be relative to `globalThis.location`, which we don't have yet.
