### ISSUE TITLE
Deno.bundle does not seem to respect target compiler option

### ISSUE THREAD

**Issue by crazazy** [denoland/deno#4443]
Because the `deno bundle` command does not support passing a tsconfig file, i tried making a separate file dedicated to bundling my client-side files [the file in question](https://glitch.com/edit/#!/deno-file-browser?path=compileClient.ts:4:6)

However, when I pass the target/module options to the bundle function, I still get a [bundle with optional chaining](https://glitch.com/edit/#!/deno-file-browser?path=dist/app.bundle.js:21:37). 

The cause of this seems to be that the system loader gets pasted in, and then all the other files get thrown into the bundle. I suggest changing [this](https://github.com/denoland/deno/blob/b22f48970fc18c4e5fd72df15ac798477fbe49cb/deno_typescript/system_loader.js#L21) line in such a way that it doesn't use optional chaining, either that, or make it so that Deno first groups the required files together as one file, and then compiles the bundle as a whole instead of first compiling the separate files and then bundling the compiled files

**Comment by kitsonk** [comment]
Could you supply a reproducible example of what you are doing with `Deno.bundle()`, what version of Deno you are using, etc.

It is really hard to guess at what you are using and passing.

**Comment by crazazy** [comment]
Sorry, I am using v0.36.0.

You can reproduce this by targeting any javascript/typescript file, but I'll use "app.js" as a placeholder. But let's say that our app.js file makes a simple React app

for completions sake, here is a sample javascript file
```js
//we have to explicitly mention index.js because the bundler cares about the file extension
import React from "https://dev.jspm.io/react/index.js" 
import ReactDOM from "https://dev.jspm.io/react-dom"

function App(props){return (<button onClick={()=>{alert(1)}>I'm a button!</button>)}
ReactDOM.render(<App />, document.getElementById("app"))
```

now we can try to bundle it using Deno with the bundle function
```typescript
const { bundle, writeFileSync } = Deno;
const files = generateFileTree("./client");
export default function compiler(): void {
  const encoder = new TextEncoder();
  bundle("./client/index.js", undefined, { target: "es6", module: "umd" })
    .then(([diag, result]) => encoder.encode(result))
    .then(res => writeFileSync("./dist/app.bundle.js", res));
}

if (import.meta.main) {
  compiler()
}
```
**Expected**: an ES6-compatible bundle in UMD format
**What I got**: an ESNext-compatible bundle in the special System loader format that has been made

**Comment by kitsonk** [comment]
First, `Deno.bundle()` will always use the internal Deno bundling format.  We need to make that more explicit in the documentation.

Second, we default to `allowJs: false`, which I think is what is leading to the transformation of the syntax not happening.  We should also warn/throw on that.

If you want to use `umd` with your own loader, then also `Deno.compile()` is more appropriate, with an `outFile: ""` being set.  It would still require `allowJs: true` (and again, we should throw/warn if the main module is JavaScript).

**Comment by crazazy** [comment]
Ok. I will try to find workarounds for my own usecase then. Thanks for the info
