### ISSUE TITLE
Simplify public test API

### ISSUE THREAD

**Issue by ry** [denoland/deno#4450]
With improvements to the test runner, the public interface has grown quite complex

https://github.com/denoland/deno/blob/0adc86f105204b2475126c36dfc10e678f67df56/cli/js/lib.deno.ns.d.ts#L15-L129

It use to be just a single function, and now encompasses many structs and classes. `ConsoleTestReporter` is particularly egregious - it does not need to be public. The various test messages `TestStatus`, `TestResult`, `TestStats`, `TestEvent`, `TestEventStart`, `TestEventTestStart`, `TestEventTestEnd`, `TestEventEnd` could likely be merged into a single interface with some careful adjustments. `TestReporter` could probably be a single function.

Most of this stuff is just for internal function of the test runner. Does it need to live in the public namespace at all?

**Comment by kitsonk** [comment]
For `TestStatus` and `TestEvent` I wouldn't use an enums.  They require real runtime code, which is onerous and burdensome and decreases portability.  A type of string literals would perfectly suit here and be just as type safe.  Effectively the strings make it like that anyways.

The various messages could easily be turned into a single tagged union interface.  I can understand they are exposed so others can understand the output.

I agree about `ConsoleTestReporter` and `TestReporter` should just be a single function but why is that exposed at all (let alone `constructor()` is totally useless let alone why is it a class)?

**Comment by bartlomieju** [comment]
All of that cruft is my invention that I added as I was working on testing APIs. Now it's apparent that all of that code is unnecessary, so I'll gladly clean that up.

**Comment by nayeemrmn** [comment]
@kitsonk The refactor I've been working on today #4451 ended up pretty much exactly to your specification.

**Comment by bartlomieju** [comment]
Fixed in #4451

**Comment by apatrida** [comment]
Having a plugable test reporter is useful since many systems work off of standard test reports, not console output which is unpredictable and not designed to be machine readable.  So `TestReporter` interface and the ability to add a different one is neccessary.
