### ISSUE TITLE
CORS: Remote script should not be able to import local module file

### ISSUE THREAD

**Issue by KSXGitHub** [denoland/deno#4455]
## Steps to reproduce

1. Create a local JavaScript module file named `/test-data.js`: https://gist.githubusercontent.com/KSXGitHub/62cb052060dc169796ab3698ff53c33b/raw/9d7d84910b344eb8580be8b91cf539e18e565e5d/init.sh.
2. Execute <code>deno run <a href='https://gist.githubusercontent.com/KSXGitHub/62cb052060dc169796ab3698ff53c33b/raw/9d7d84910b344eb8580be8b91cf539e18e565e5d/deno.js'>https://gist.githubusercontent.com/KSXGitHub/62cb052060dc169796ab3698ff53c33b/raw/9d7d84910b344eb8580be8b91cf539e18e565e5d/deno.js</a></code>.

Resource: https://gist.github.com/KSXGitHub/62cb052060dc169796ab3698ff53c33b

## Expected behavior

Error, just like in Chrome.

## Actual behavior

It read data from local file and printed it.

**Comment by frank-dspeed** [comment]
@KSXGitHub Hello again my friend I think this is the wrong direction. deno is not a browser it aims also not to be a serverless function runner (running unknown user-supplied functions).

you can easily isolate the deno files into a container.

**Comment by kitsonk** [comment]
Duplicate of #2768

Please try to search before opening new issues.

**Comment by KSXGitHub** [comment]
@kitsonk GitHub search is pretty limited.

**Comment by kitsonk** [comment]
I used [`remote import local`](https://github.com/denoland/deno/issues?q=is%3Aissue+is%3Aopen+remote+import+local) and it came up with 10 issues, the title of the referenced issue made it rather obvious.
