### ISSUE TITLE
Switch to prettier 2.0 before releasing deno 1.0

### ISSUE THREAD

**Issue by trivikr** [denoland/deno#4456]
Prettier 2.0 is out https://prettier.io/blog/2020/03/21/2.0.0.html
Creating this issue for tracking whether deno should switch to it before 1.0 release

**Comment by ry** [comment]
We don't use prettier anymore - we use a formatter implemented in rust 
https://crates.io/crates/dprint-plugin-typescript

(We still use prettier for the internal code, but it's not public and hopefully we'd be able to use dprint for that too at some point.
