### ISSUE TITLE
WIP: create deno-plugin-actix - actix-deno bindings to be used via deno

### ISSUE THREAD

**Issue by frank-dspeed** [denoland/deno#4465]
I Would love to explore the most relevant part of deno.

Creating a useful binding useable inside v8 directly to the actix_web and actix_files.

The idea comes from the results with the graalvm language framework from oracle where we did nativ bindings in java for the java framework vertx which is the java equivalent of actix.

It Showed really high thruput.

So the question is does documentation for the custom binding's even already existed? If not someone like me should write that.

**Comment by hayd** [comment]
Webview is a nice plugin example https://github.com/eliassjogreen/deno_webview also https://github.com/crabmusket/deno_sqlite_plugin
Both use plugin prepare.

Will be interesting to see this as an alternative/baseline for perf.

**Comment by lucacasonato** [comment]
I don't think this is related to the main Deno repo. This sounds like a user land plugin?

**Comment by frank-dspeed** [comment]
@lucacasonato the only relation to main is that there is no plugin documentation:) this here helped me to get it started.

**Comment by frank-dspeed** [comment]
when plugins will work for that it is still WiP

**Comment by bartlomieju** [comment]
> @lucacasonato the only relation to main is that there is no plugin documentation:) this here helped me to get it started.

Closing in favor of https://github.com/denoland/deno/issues/7030 as it better describes the problem
