### ISSUE TITLE
Manual upgrade issues from v36 to v37 on Windows

### ISSUE THREAD

**Issue by trosel** [denoland/deno#4468]
1. I downloaded v37 `deno-x86_64-pc-windows-msvc.zip` from github.

2. put the exe inside of the existing deno location and told it to replace the old one.

3. Tried to run `deno` in **git bash** and got:  `C:/Users/MyName/.local/bin/deno.exe: error while loading shared libraries: api-ms-win-crt-multibyte-l1-1-0.dll: cannot open shared object file: No such file or directory`

4. Tried to run `deno` in **command prompt** and got: `VCRUNTIME140_1.dll was not found`

It's possible that I'm just missing some Visual Studio runtime files, or that I replaced the old exe with a different type of exe this time. Just not sure.

**Comment by tdillon** [comment]
I'm getting the same thing.  Upgrading from v36 to v37 using :
```powershell
iwr https://deno.land/x/install/install.ps1 -useb | iex
```

**Comment by ry** [comment]
We are investigating.

**Comment by ry** [comment]
Fixed in  #4469. We are releasing v0.37.1 to correct this. It should be out in the next hour or so.
https://github.com/denoland/deno/pull/4470

**Comment by elchinzadeh** [comment]
This .dll file should help

https://www.dll-files.com/vcruntime140_1.dll.html

Destination folder: C:\Windows\System32
