### ISSUE TITLE
Remove get_rust_ldflags.py

### ISSUE THREAD

**Issue by ry** [denoland/deno#447]
If it can be.. 

https://github.com/denoland/deno/blob/d63e03a8e75ff39cec60f8d6fd82e57078373207/build_extra/rust/get_rust_ldflags.py

**Comment by ry** [comment]
We had a long email exchange with Rust folks and the conclusion was that this is indeed the only way to link Rust code. I don't find this satisfactory - so I will leave this open. Maybe it will change in the coming years.

**Comment by bartlomieju** [comment]
@ry stale?
