### ISSUE TITLE
async op error: must be called from the context of Tokio runtime

### ISSUE THREAD

**Issue by runnerSnail** [denoland/deno#4479]
### writing a plug-in, called on the ts side and executed on the rust side
> I don't know if it's my problem so ask for help

##### command
```rust
use redis::{self, aio::MultiplexedConnection, RedisResult};
pub fn set(command: Command) -> CoreOp {
    println!("===>set");
    let fut1 = async move {
        // let connect = get_client(0).clone();
        let connect = redis::Client::open("redis://127.0.0.1:6379").unwrap();
        connect
            .get_multiplexed_tokio_connection()
            .and_then(|mut con| {
                async move {
                    redis::cmd("SET")
                        .arg("key1")
                        .arg(b"foo")
                        .query_async(&mut con)
                        .await?;
                    redis::cmd("SET")
                        .arg(&["key2", "bar"])
                        .query_async(&mut con)
                        .await?;
                    let result = redis::cmd("MGET")
                        .arg(&["key1", "key2"])
                        .query_async(&mut con)
                        .await;
                    assert_eq!(result, Ok(("foo".to_string(), b"bar".to_vec())));
                    Ok(util::async_result(&command.identity, "OK"))
                    // result
                }
            })
            .map_err(|err| panic!("{}", err))
            .await
    };
    CoreOp::Async(fut1.boxed())
}
```
##### register_op

```rust
// ....
init_fn!(init);

fn init(context: &mut dyn PluginInitContext) {
    context.register_op("redis_command", Box::new(op_command));
}

fn op_command(data: &[u8], zero_copy: Option<ZeroCopyBuf>) -> CoreOp {
    let args = CommandArgs::new(data);
    let executor = match args.command_type {
        CommandType::ConnectWithOptions => command::get_connection,
        CommandType::Cmd => command::operator::set,
    };
    executor(Command::new(args, zero_copy))
}
```
##### toml
```toml
[dependencies]
serde = { version = "1.0", features = ["derive"] }
redis = { version = "0.15.1", features=["tokio-rt-core"] }
bson = "0.14.0"
serde_json = "1.0.48"
futures = "0.3.4"
deno_core = "0.35.0"
lazy_static = "1.4.0"
rusty_v8 = "0.3.4"
log = "0.4.8"

```
#### my ts code
```ts
// ...
const localPath = path.resolve(".deno_plugins", urls[os]);
const Redis = Deno.openPlugin(localPath);
// ...
```
#### deno run 
```shell
RUST_BACKTRACE=1 deno run --allow-all test.ts
```
##### get error
> Finished release [optimized] target(s) in 0.13s
Copy "/Users/waniu/Desktop/study/deno_redis/target/release/libdeno_redis.dylib" to "/Users/waniu/Desktop/study/deno_redis/.deno_plugins/deno_redis.dylib"
running 1 tests
result--->1
redis://127.0.0.1:6379/0
data 0
result--->2
doc1
commondId 1
control {"command_type":"Cmd","client_id":0,"command_id":1}
===>set
thread '<unnamed>' panicked at 'there is no reactor running, must be called from the context of Tokio runtime', src/libcore/option.rs:1185:5
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: std::panicking::continue_panic_fmt
   7: rust_begin_unwind
   8: core::panicking::panic_fmt
   9: core::option::expect_failed
  10: tokio::io::registration::Registration::new
  11: tokio::net::tcp::stream::TcpStream::new
  12: <std::future::GenFuture<T> as core::future::future::Future>::poll
  13: <std::future::GenFuture<T> as core::future::future::Future>::poll
  14: futures_util::future::try_future::try_chain::TryChain<Fut1,Fut2,Data>::poll
  15: <std::future::GenFuture<T> as core::future::future::Future>::poll
  16: <futures_util::future::try_future::map_ok::MapOk<Fut,F> as core::future::future::Future>::poll
  17: <futures_util::future::try_future::map_ok::MapOk<Fut,F> as core::future::future::Future>::poll
  18: <&mut S as futures_core::stream::Stream>::poll_next
  19: futures_util::stream::stream::StreamExt::poll_next_unpin
  20: <deno_core::isolate::Isolate as core::future::future::Future>::poll
  21: <deno_core::es_isolate::EsIsolate as core::future::future::Future>::poll
  22: <std::future::GenFuture<T> as core::future::future::Future>::poll
  23: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on
  24: tokio::runtime::context::enter
  25: deno::tokio_util::run_basic
  26: deno::main
  27: std::rt::lang_start::{{closure}}
  28: std::panicking::try::do_call
  29: __rust_maybe_catch_panic
  30: std::rt::lang_start_internal
  31: main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

#### end
Deno is 👍. Thanks for the answer

**Comment by runnerSnail** [comment]
Tikio may not be open **enable_io**
```rust
let rt = runtime::Builder::new()
    .enable_io()
    .build()
    .unwrap();
```

I can't seem to find the code for how tokio runs the plug-in

**Comment by runnerSnail** [comment]
**enable_io**  Is called
```rust
pub fn create_basic_runtime() -> tokio::runtime::Runtime {
  tokio::runtime::Builder::new()
    .basic_scheduler()
    .enable_io()
    .enable_time()
    .build()
    .unwrap()
}

```
**cli toml**
tokio = { version = "0.2", features = ["rt-core", "tcp", "udp", "process", "fs", "blocking", "sync", "io-std", "macros", "time"] }

**plugin toml**
redis = { version = "0.15.1", features=["tokio-rt-core"] }

**Comment by bartlomieju** [comment]
@runnerSnail did you find a solution?

**Comment by runnerSnail** [comment]
@bartlomieju No, I'm still investigating the cause
#### With the same code, I could run the tests in the deno's test-plugin directory
![image](https://user-images.githubusercontent.com/40654631/77655060-db264d80-6fac-11ea-847c-f7f64a041dfc.png)
#### Error loading open_plugin
![image](https://user-images.githubusercontent.com/40654631/77655707-b9799600-6fad-11ea-9c71-2d4007de20f3.png)

**Comment by bartlomieju** [comment]
@runnerSnail can you share the line to repo? Maybe there's a problem in build setup

**Comment by runnerSnail** [comment]
@bartlomieju I'm sorry I didn't see it clearly
#### The test-plugin will also have errors，I feel like I have a problem with my writing
![image](https://user-images.githubusercontent.com/40654631/77655966-2b51df80-6fae-11ea-91ee-88fade4626dd.png)

**Comment by runnerSnail** [comment]
@bartlomieju Hi brothers
my [repo](https://github.com/runnerSnail/deno_redis)

**run** 
> RUST_BACKTRACE=1 deno run --allow-all test.ts

**Comment by runnerSnail** [comment]
#### Now it is work
![image](https://user-images.githubusercontent.com/40654631/77740405-29d7f400-704e-11ea-810f-feaf073348f1.png)

Is there something wrong with **CoreOp::Async(fut1.boxed())**

**Comment by runnerSnail** [comment]
I'm not doing thread control, I'm going to try it. If possible, I will add this problem

**Comment by runnerSnail** [comment]
There really is no runtime, I don't know why deno didn't provide the runtime of tokio or is the runtime lost

**Comment by kevinkassimo** [comment]
Some update to this (in case others are also interested in investigating):
It might be some issue with dylib: I tried just now, and noticed that `std::thread::current()` would return completely different information even if the function accessed through dylib is running on the same thread (`OpRegistry::call` would print 2 different thread info depending on if in or out of the actually invoked `op_xxx` function). Maybe this has to deal with problems of locating static var locations inside the dylib, which would the same problem here for finding no Tokio runtime instance (`tokio::runtime::Handle::current()` would panic if invoked in functions in dylib)
