### ISSUE TITLE
WIP: deno-chromium

### ISSUE THREAD

**Issue by frank-dspeed** [denoland/deno#4481]
To Replace NW.JS and Electron I should extend deno with simple rust-bindings-cfe via deno-plugin-chromium or if I should investigate into somehow directly modify deno to use the same v8 instance of the cfe NW.JS Demonstrates that well for nodejs

## Updates will create Optimized build that will share v8 with a chromium build
- [ ] https://github.com/dockerimages/docker-deno/issues/1
- [x] Asked someone from google to look into this and maybe supply additional info
- [x] Setup a local development env with chromium#master and cfe # master
  - [x] https://bitbucket.org/chromiumembedded/cef
  - [x] https://chromium.googlesource.com/chromium/src.git
- [ ] Get deno v8 build working with chromium

**Comment by ry** [comment]
It would be very cool to get a chromium build that shared V8. You should look into how we setup the build in rusty_v8 (our Rust bindings to V8) 
https://github.com/denoland/rusty_v8/blob/v0.3.8/.gn
https://github.com/denoland/rusty_v8/blob/v0.3.8/BUILD.gn

**Comment by frank-dspeed** [comment]
@ry can you line out all findings that you had as you tryed to use a prebuild v8 ? i remember you writed some where something about why we even need to compile v8 our self.

**Comment by frank-dspeed** [comment]
first experiment that i will try is to build cfe with chromium master and our gn settings for v8 and simply look what we get :)

**Comment by frank-dspeed** [comment]
I found out that this is a bigger project I found an eq one for nodejs https://github.com/nwjs I will go for https://github.com/dwjs and look into the implementation of them since they got the same shared heap concept that I have in mind

**Comment by frank-dspeed** [comment]
It turns out that it will bring not the expected performance benefits the project is abondonend with the conclusion that it is not worth the effort as it will not reduce the serialisation and context switching reduction as expected.
