### ISSUE TITLE
Deno

### ISSUE THREAD

**Issue by KarolineCat** [denoland/deno#4489]
// Copyright 2018-2020 the Deno authors. All rights reserved. MIT license.

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-empty-interface, @typescript-eslint/no-explicit-any */

/// <reference no-default-lib="true" />
// TODO: we need to remove this, but Fetch::Response::Body implements Reader
// which requires Deno.EOF, and we shouldn't be leaking that, but https_proxy
// at the least requires the Reader interface on Body, which it shouldn't
/// <reference lib="deno.ns" />
/// <reference lib="esnext" />

// https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope

**Comment by kevinkassimo** [comment]
Hi @KarolineCat , could you clarify what is the concrete problem and rename the issue?

**Comment by ry** [comment]
I don't know what this is about.
