### ISSUE TITLE
Promise exit behaviour

### ISSUE THREAD

**Issue by benjamingr** [denoland/deno#449]
So @ry , I'm taking a stab at implementing the promise behaviour we were talking about. 

 - I can detect it immediately after the function with an `async_hook` - which would cause a 2x slowdown for promises.
 - I can detect it after the next tick without the slowdown, but it would give other promises a chance to run.
     - If I do this, what mechanism should I use? 
          - I can change the deno code to call `RunMicrotasks` instead of doing it automatically and check if it's unhandled later 
           - or I can keep a map around of promises and schedule a microtask to check myself - if so, where should I do this? (with Tokio? with V8?)

**Comment by ry** [comment]
I'm not sure. Let's wait until tokio lands (#434)  it'll be easier to think about this then. I think the way to start this is to setup some tests first.

**Comment by bartlomieju** [comment]
Is this still relevant?

**Comment by benjamingr** [comment]
Yes

**Comment by hayd** [comment]
Could you explain what "the promise behaviour we were talking about" is?

**Comment by benjamingr** [comment]
@hayd abort on promises that reach a rejected state and no handlers were attached synchronously

**Comment by bartlomieju** [comment]
> abort on promises that reach a rejected state and no handlers were attached synchronously

It seems that's the current behaviour of Deno https://github.com/denoland/deno/blob/7d2d442a77343a3c4ab6c638bd817e51c6cadd2e/core/bindings.rs#L342-L349

Later that error is propagated and Deno exists. 

It seems we can close this issue now

**Comment by benjamingr** [comment]
Deno still does the incorrect unsafe thing here, and not what we discussed face to face for what it's worth @ry

**Comment by bartlomieju** [comment]
@benjamingr could you describe expected behavior?

**Comment by ry** [comment]
@benjamingr This issue is really old and there's no explicit examples. Please open a new one if you've got some example code - cheers!

**Comment by benjamingr** [comment]
Sure. whatever helps.
