### ISSUE TITLE
Proposal: Subcommand to "cat" a remote file

### ISSUE THREAD

**Issue by kizerkizer** [denoland/deno#4492]
Often I want to see the source of a URL import - unless I'm mistaken, there's no easy way aside from "curl"ing the URL to see the source? If so, I think a deno cat <URL> or something similar would be very handy. Maybe a way to navigate the cached dependency tree?

**Comment by kitsonk** [comment]
Why would something like this not be sufficient:

```
curl https://deno.land/x/foo/bar.ts
```

I guess why do you need Deno in the way?

**Comment by hayd** [comment]
There is an example deno script in std:

    deno --allow-net https://deno.land/std/examples/curl.ts URL

You could install/alias this on your machine. (Or you could just use curl as kitson mentions.)

---

I don't think deno is, or should be, in the business of making every unix tool a subcommand.

**Comment by kizerkizer** [comment]
> Why would something like this not be sufficient:
> 
> ```
> curl https://deno.land/x/foo/bar.ts
> ```
> 
> I guess why do you need Deno in the way?

For some reason I thought I'd need some flags. Yeah, you're right.
