### ISSUE TITLE
deno info should list dynamic import dependencies where possible

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#4494]
Currently if you have a file like this:

```ts
import * as foo from "./foo.ts";
const bar = import("./bar.ts");
```

Then `deno info` would only list `foo.ts` as a dependency, although in the TypeScript compiler, when the import resolves to a static string, TypeScript will include the module in the program and be able to type check the import.  I don't know if there is an equivalent APIs in V8 which allow that analysis where the import specifier resolves to a static string, but trying to have as many dependencies as it possible to statically determine.

**Comment by bartlomieju** [comment]
Closed in https://github.com/denoland/deno/pull/6786
