### ISSUE TITLE
Replace sys-info crate dependency with systemstat

### ISSUE THREAD

**Issue by ry** [denoland/deno#4496]
sys-info is broken on Windows for 3 releases now, and doesn't have proper CI. We cannot depend on that.

This other crate https://github.com/myfreeweb/systemstat looks like a good replacement

This should be a relatively easy Rust issue for someone who wants to look around the code base.

**Comment by Nimpruda** [comment]
I'm bored because of all this corona confinement stuff (I'm French) I'll take it.

**Comment by Nimpruda** [comment]
@ry There is no way to get the hostname or the os release version with systemstat shoul I just read from /proc/... for unix and execute hostname for windows (as there is no os_release).
I'm sorry I'm a bit noob with this stuff

**Comment by ry** [comment]
@Nimpruda you can return OpError::not_implemented() for those. We can get to it later.

**Comment by bsene** [comment]
Hello @Nimpruda , 
Are you still working in this issue ?

**Comment by Axighi** [comment]
@ry I'll work on it.

**Comment by Axighi** [comment]
I didn't find any usage of sys-info in the code base. What am I missing here?

**Comment by oberzan** [comment]
The sys_info seems to have fixed the issue: https://github.com/FillZpp/sys-info-rs/issues/50
@ry Can you confirm that?

**Comment by fmauricios** [comment]
@oberzan #4504

**Comment by ColinHarrington** [comment]
Looks like [@ry is reconsidering `systemstat`](https://github.com/denoland/deno/pull/4504#pullrequestreview-384049680) lacking hostname and release parsing functionality, dependency issues among others.  It's not a 1:1 replacement.  Should the _good first issue_ label be removed?

**Comment by joshdover** [comment]
sys-info was upgraded successfully to 0.6.1 a few days ago (https://github.com/denoland/deno/pull/5104) but the issue remains that they don't have a windows build in their CI.

**Comment by ktfth** [comment]
Have another way to test the changes?

**Comment by Gum-Joe** [comment]
I know it's been 28 days since the last comment, but would it be worth submitting a PR to sys-info to add windows CI?  It looks like it's as simple as adding an entry to Travis build files. Or am I missing something here, as it seems it's still to be decided if `systemstat` or `sys-info` will be used, particularly given Dahl comments on #4504?

**Comment by ry** [comment]
@Gum-Joe The latest releases of sys-info are working on Windows. It would be quite nice to help them get Windows CI working. For now I'm going to close this issue since it's not a problem anymore - and IIRC systemstat had its own issues.

**Comment by Gum-Joe** [comment]
@ry Ok, thank you.  I've created FillZpp/sys-info-rs#65 to add Windows CI.
