### ISSUE TITLE
Introduce Makefile into build process

### ISSUE THREAD

**Issue by NewLunarFire** [denoland/deno#450]
Hi @ry ,

As the project advances, I was wondering if introducing a Makefile in the build process would be a good idea.

Advantages:
- It would be simple to rebuild deno and could check for specific file dependencies to know if it should run setup.py, build.py or other scripts that could appear in the future.
- It would also allow to specify different build configurations (debug, release, testing?).
- It a standard and widely used method for this workflow. Building/Re-building becomes as simple as typing make

Disadvantages:
- It is a really Unix method and never works well on a Windows environment without adding other tools to the mix, like Cygwin
- It adds another step to the build process

I'm on the fence about this. The build process as is isn't really complicated as of now, so there's no absolute need for this. If it's something you would like to have I will gladly open a PR. It could also be introduced further down the road.

**Comment by ry** [comment]
Hi @NewLunarFire - make would be redundant, we already use ninja.
