### ISSUE TITLE
inspector should support source maps

### ISSUE THREAD

**Issue by ry** [denoland/deno#4501]

**Comment by bartlomieju** [comment]
I did some research on this topic; I changed some code to pass proper source map URL into `ModuleOrigin` for loaded modules, but it turns out that field value is ignored if JS source has `//# sourceMappingURL` directive at the end. 

It turns out all TS files that are compiled do have this directive, but unfortunately it has the wrong value:
```
eg. ~/dev/server.ts

will have this directive:
//# sourceMappingURL=server.js.map 

which causes error in console:
DevTools failed to load SourceMap: Could not load content for file:///Users/biwanczuk/dev/deno-debug/server.js.map: System error: net::ERR_FILE_NOT_FOUND
```

**Comment by bartlomieju** [comment]
@kitsonk do you think it'd be better to remove `//# sourceMappingURL` from the output and handle source map lookup completely in Rust or dispatch an op to get proper source map URL to get proper value for the directive?

**Comment by gvatn** [comment]
I've been doing some setup/implementation of a Deno debugger for vscode, with some modifications on a deno fork. I haven't worked out any complete suggestions, but seeing some activity, I thought I should chime in.

I did a write up with most of my findings to https://github.com/gvatn/deno-debug-explorations. Along with protocol dumps I haven't yet fully analyzed.

After wrangling a bit trying to implement the debugger (there are some idiosyncrasies that currently would require some mapping to a regular node debugger), I think my feeling is to try to make Deno adhere more to the output/behaviour of node. Maybe as a fallback one can make it close enough that a correctly configured node debugger could connect to Deno.

**Comment by kitsonk** [comment]
Is there no way to hook the inspector to provide the source map and/or do the remapping for the inspector in Rust?  I mean we would have to provide the source map anyways, removing the `// @ sourceMappingURL` seems like something we shouldn't need to do if we hooked things properly.  Modifying output of TypeScript just feels like a slippery slope, and if it breaks or we forget about it, it just seems like we should find a way without modifying every output.  Our error remapping doesn't care about that.

> I think my feeling is to try to make Deno adhere more to the output/behaviour of node

In what sense?  What behaviours are missing?

**Comment by gvatn** [comment]
> In what sense? What behaviours are missing?

I guess an alternative approach could be to go with `module_origin` set to the ts-file and make custom deno-debuggers. My meaning was that working on deno to approach node's output seems a better route.

I think the following is the main issues to adapt to existing debuggers. Could evaluate if there are more problems if we implement these changes.

The current node debugger in vscode, vscode-node-debug2, will look at `//# sourceMappingURL` as a fallback, if `outFiles` config property is not given/resolved, this is nice for config-free debugging. A current issue here is deno writes to `index.ts.js` and `index.ts.js.map`, while the ts default is `index.js` and `index.js.map` (https://github.com/denoland/deno/blob/1378df33647e2608733d88121b77ff2f839cddfa/cli/compilers/ts.rs#L465, https://github.com/denoland/deno/blob/1378df33647e2608733d88121b77ff2f839cddfa/cli/compilers/ts.rs#L525).

It seems neither vscode-node-debug2 use, or node provides `sourceMapURL` that can be registered through v8, though could be good to provide if available.

Together with `module_origin` set to the transpiled file, I think it's close can work with standard debuggers.

The remaining issue I know of is the [process.pid,...] that is undefined in deno. Seems it might pause until it gets these values, but could investigate this further.

**Comment by bartlomieju** [comment]
> Is there no way to hook the inspector to provide the source map and/or do the remapping for the inspector in Rust? I mean we would have to provide the source map anyways, removing the `// @ sourceMappingURL` seems like something we shouldn't need to do if we hooked things properly. Modifying output of TypeScript just feels like a slippery slope, and if it breaks or we forget about it, it just seems like we should find a way without modifying every output. Our error remapping doesn't care about that.

I thought the way to provide the maps is by settings proper value on `ModuleOrigin`/`ScriptOrigin` - I did that as an experiment, but it turned out that inspector ignores those values if there's a // @sourceMappingURL` pragma in the source code.

> The current node debugger in vscode, vscode-node-debug2, will look at `//# sourceMappingURL` as a fallback, if `outFiles` config property is not given/resolved, this is nice for config-free debugging. A current issue here is deno writes to `index.ts.js` and `index.ts.js.map`, while the ts default is `index.js` and `index.js.map` (

@gvatn I'm afraid that's a bit more compilcated - if you have a local source file, Deno reads it directly from disk but compiled source and source map are cached in `$DENO_DIR`. That means that relative URLs wouldn't really work in this case as source can be in `~/dev/mod.ts` while source map ends up in `$DENO_DIR/gen/file/home/dev/mod.ts.js`.

**Comment by gvatn** [comment]
> That means that relative URLs wouldn't really work in this case as source can be in ~/dev/mod.ts while source map ends up in $DENO_DIR/gen/file/home/dev/mod.ts.js.
I think this is the case when, as currently, `module_origin` is set to the .ts file, but not if `module_origin` were to be set to the transpiled js?

I was a little confused about the exact path you used with the `module_origin` experiment above, if you referenced `.js.map` or just the `.js`.

Node will give: https://github.com/gvatn/deno-debug-explorations/blob/master/protocol-node.txt#L72

When I added the transpiled `.js` as in: https://github.com/gvatn/deno-debug-explorations/blob/master/protocol-deno.txt#L41
The debugger correctly mapped to local `index.ts`

**Comment by bartlomieju** [comment]
<s>@gvatn if I understand correctly you're running it inside VSCode - I can't speak about it; as I was trying only with devtools from Chrome (which I expect do less magical stuff than VSCode).</s>

Nvm, I see this: 
```
Currently using a fork of deno where the compiled filename is added to ModuleSource and CompiledModule, passed into mod_new, and eventually added as bindings::module_origin. Atm it's not quite commitable with lots of println!()s, and tests failing as stack traces reference the transpiled files.

Uses https://github.com/gvatn/vscode-deno. Similarly edited noice-json. On debug panel, can just "Launch Client" as it stands. I think the debugger should run in it's own process eventually though.
```

Can you show your fork? It seems I did exactly same change and I'm ending up with different results.

**Comment by gvatn** [comment]
Yes, exactly. This change makes debuggers less confused.
I can clean it up to commit, just give me a little while.

**Comment by gvatn** [comment]
https://github.com/gvatn/deno/commit/6dbb43b96d5a699e5566b616bc99cc0582982300
I've used PathBuf, not sure if String would be better.
Also as noted an issue when making `ModuleSource` via `ResolveMain`.
Leaves a bunch of tests failing without mapping stacktraces back to source .ts filenames.

**Comment by bartlomieju** [comment]
@gvatn thanks for putting up the branch - I see you changed the actual module URL V8 sees - that's not really desirable; V8 should get the URL that the module was requested with (or its redirect) - source map URL should be passed to `v8::ScriptOrigin.source_map_url`, but that brings us full circle to the issue as described in https://github.com/denoland/deno/issues/4501#issuecomment-619524597

**Comment by gvatn** [comment]
I think if it gets the module it was requested with (this would be the .ts file?), there will be some confusion, as the associated given source will be the transpiled source, and source locations ie for breakpoints will be off. I think this would require debuggers to translate all locations in a deno-specific way.
The source maps in the debuggers perspective works in direction transpiled -> source.

**Comment by kitsonk** [comment]
Sometimes JavaScript files in Deno have source maps as well.

**Comment by bartlomieju** [comment]
> Sometimes JavaScript files in Deno have source maps as well.

So devtools probably picks them up automatically too. I think the way to go is to provide proper URL to source map in TS compiler. I can get proper paths from Rust, but I don't know how should I hook that up to TS output (at least not without using manual regex replace).

**Comment by kitsonk** [comment]
> I think the way to go is to provide proper URL to source map in TS compiler. I can get proper paths from Rust, but I don't know how should I hook that up to TS output (at least not without using manual regex replace).

What we really just want is to have it be `./something.js.map` right?  That should always be along side the cache.  I _think_ I know how to get the compiler to do that.  Let me look.

**Comment by bartlomieju** [comment]
> > I think the way to go is to provide proper URL to source map in TS compiler. I can get proper paths from Rust, but I don't know how should I hook that up to TS output (at least not without using manual regex replace).
> 
> What we really just want is to have it be `./something.js.map` right? That should always be along side the cache. I _think_ I know how to get the compiler to do that. Let me look.

Not necessarily - I think it should be absolute URL. V8 is not really aware that the file might be placed in DENO_DIR (but rather see a remote URL) so I think it's better to provide resolved URL to concrete location

**Comment by piscisaureus** [comment]
I think filling out [this](https://github.com/denoland/deno/blob/128dce0d8a2ae062d0d85918da841a6f6aa2198a/core/bindings.rs#L63) field with something other than "source_map_url" (literally) would go a long way.

**Comment by bartlomieju** [comment]
> I think filling out [this](https://github.com/denoland/deno/blob/128dce0d8a2ae062d0d85918da841a6f6aa2198a/core/bindings.rs#L63) field with something other than "source_map_url" (literally) would go a long way.

@piscisaureus I already tried that, please read this comment: https://github.com/denoland/deno/issues/4501#issuecomment-619360724 - Devtools ignores that value if there's a `// @sourceMappingURL=` pragma

**Comment by gvatn** [comment]
Some interesting things can also be done with `inlineSourceMap` and `inlineSources` turned on. Here it is done for both the cli bundle and as `defaultCompileOptions`:
![image](https://user-images.githubusercontent.com/310000/80387656-2cc24080-88a9-11ea-8d2d-1dffeaf626f7.png)
![image](https://user-images.githubusercontent.com/310000/80387694-377cd580-88a9-11ea-9eb0-6e5ddd7eb6d4.png)

**Comment by kitsonk** [comment]
We don't want to do `inlineSources` or `inlineSourceMap`, this will only bloat the cache unecessarily.  They are "great" when you are actually shipping code to a browser, where getting ahold of the source is "expensive" but even then, usually only a good idea in non-production.  Production, you _might_ want to do `inlineSources`.

(`inlineSources` puts the original source code in the source map, and `inlineSourceMap` creates a base64 encoding of the source map and places it in the emitted file, which is all horribly inefficient when the source file is literally sitting right next to the emitted file... we _might_ want to support inlining with Deno bundles, because they would be distributed, but that is another topic)
