### ISSUE TITLE
Q: strings/pad?

### ISSUE THREAD

**Issue by ondras** [denoland/deno#4529]
Hi,

is there any particular reason for the existence of the std `strings/pad` module? I think its usage can be safely replaced by the standard `padStart`/`padEnd` methods, because the `strict` mode of `strings/pad` does not seem to be used anywhere in the Deno code base.

Would it be useful if I submitted a PR that replaces calls to `strings/pad` with calls to `padStart` ?

**Comment by kitsonk** [comment]
Lots of `std` isn't used in the Deno code base.  It is a standard library to be used downstream.

It already uses `.padStart()` and `.padEnd()`:

https://github.com/denoland/deno/blob/3892d49165f00b2ce078825c204ba8ceaa21f386/std/strings/pad.ts#L57-L61

What are you proposing?  The strict mode feature is handy, as shown in the example, if you want to use ellipses to truncate a string that is running on too long.  Why remove a feature?

**Comment by ondras** [comment]
> What are you proposing? The strict mode feature is handy, as shown in the example, if you want to use ellipses to truncate a string that is running on too long. Why remove a feature?

My point was not using an additional abstraction layer where not necessary, i.e. https://github.com/denoland/deno/blob/master/std/datetime/mod.ts#L128

I understand that userland code might find the strict mode useful. Yet, this deno-specific module has a significant feature overlap with the client-side-standard pad{Start,End}.

**Comment by ondras** [comment]
> Why remove a feature?

To clarify: my point is not to remove this std module. My propsal was *not to use* it where not necessary.

**Comment by kitsonk** [comment]
Ah, yes, we should prefer built-in capabilities over std library ones, unless the abstraction makes things a lot easier, which I don't think it does in this case.  The abstraction actually adds complexity in the case you pointed out.  If we were padding start or end, based on other variables, then potentially `string/pad` would be useful, but that isn't this case.

**Comment by ondras** [comment]
Okay, I submitted https://github.com/denoland/deno/pull/4537.

**Comment by nayeemrmn** [comment]
I also don't like the `std/strings`. The `encode`/`decode` modules aren't used in a lot of places and we shouldn't encourage a dependency for trivial behaviour anyway. As for the pad module... it does some extra stuff but maybe it should more specifically target the things that the built-in doesn't do rather than abstracting over it.

**Comment by kitsonk** [comment]
I tend to agree... I wasn't specifically aware of it being there.  If it is part of Go's std lib, then we should keep it, IMO.  I can see the `strings/pad` a more complete solution if you are doing something fixed width, where you are using the strict mode.  Let's say you have a 6 column field, and you had an input of `deno` and `denoland`, you would get out: `deno  ` and `den...`.  Having that all in one is useful.

**Comment by ry** [comment]
The encode/decode are indeed dumb. Shall we remove them? Pad seems useful.

**Comment by kitsonk** [comment]
I wouldn't personally shed a tear.

**Comment by hayd** [comment]
Was this included by @rsp ?
https://github.com/rsp/deno-ende

My feeling is that if something is very popular and trivial then it is nice to be in std. Cos people are going to use them and it seems silly to have a tiny repo/file exporting one function ala isArray (or whichever example). 🤷‍♂️
