### ISSUE TITLE
umask unit tests failing

### ISSUE THREAD

**Issue by ondras** [denoland/deno#4530]
Hi,
the [umask_test](https://github.com/denoland/deno/blob/aab1acaed163f91aa5e89b079c5312336abb2088/cli/js/tests/umask_test.ts#L14) fails on my machine, because I have a default umask of 0o002. I assume this is not really a problem, because the test suite is primarily [executed against Github CI](https://github.com/denoland/deno/pull/4290), but it is still kinda weird to freshly build a project and fail the test suite.

**Comment by ry** [comment]
cc @dubiousjim

**Comment by dubiousjim** [comment]
Implementing a fix should be easy, the hard Q is deciding what to implement. Should the test verify that (on Unix builds) there is at least a 0o002 umask (leaving it open that there may be a stricter one)?

**Comment by ry** [comment]
Not sure - but it shouldn't fail.

**Comment by ondras** [comment]
> Implementing a fix should be easy, the hard Q is deciding what to implement. Should the test verify that (on Unix builds) there is at least a 0o002 umask (leaving it open that there may be a stricter one)?

Does it even make sense for a test to validate a status quo, e.g. a runtime condition that was present independently on the function being tested?

**Comment by dubiousjim** [comment]
What's being verified is that the op runs without error, that it can change the status, and that when it changes the status it reports what the previous status was.

**Comment by dubiousjim** [comment]
Can close, #4533 is merged.
