### ISSUE TITLE
Programmatic access to `deno doc --json`

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#4531]
Something like this would be nice:

```ts
const documentationNodes = Deno.doc("https://deno.land/std/http/server.ts");
```

It should probably have the same permission model as the compiler API.

**Comment by parkerdgabel** [comment]
Is anybody working on this? If not I'll do it.

**Comment by lucacasonato** [comment]
I already have a working branch, just need to do some cleanup and PR it.

**Comment by irustm** [comment]
@lucacasonato thanks!
any news on this issue? Is there anything I can do to help?

**Comment by wperron** [comment]
@lucacasonato as I understand it, `deno doc` is basically emitting a `.d.ts` annotated with JSdoc correct? following that logic, I think it'd make sense to add this under `Deno.emit` as a compilerOption rather than introduce another function to the namespace, wdyt?

**Comment by bartlomieju** [comment]
> @lucacasonato as I understand it, `deno doc` is basically emitting a `.d.ts` annotated with JSdoc correct? following that logic, I think it'd make sense to add this under `Deno.emit` as a compilerOption rather than introduce another function to the namespace, wdyt?

No, `deno doc` emits a string with custom formatting, while `deno doc --json` emits custom JSON format.

I'm not a fan of adding `Deno.doc` especially that it will lead to requests to add programatic access to other CLI tools. Maybe `Deno.cli` that would harbor other subcommands...

**Comment by crowlKats** [comment]
This can extremely easily be achieved by importing [deno_doc from /x](https://deno.land/x/deno_doc); the complexities mentioned in https://github.com/denoland/deno/issues/10731#issuecomment-986162143 in my opinion outweigh the little benefit from having this built-in compared to importing.

**Comment by crowlKats** [comment]
Closing as this issue predates the possibility to use deno_doc from /x, and as per https://github.com/denoland/deno/issues/10731#issuecomment-986162765 it should be the way to go.
