### ISSUE TITLE
Rust.lstat is broken

### ISSUE THREAD

**Issue by zakuro9715** [denoland/deno#4534]
I found an error when developping my script.

```
error: Uncaught NotFound: No such file or directory (os error 2)
► $deno$/ops/dispatch_json.ts:43:11
    at NotFound ($deno$/errors.ts:75:5)
    at unwrapResponse ($deno$/ops/dispatch_json.ts:43:11)
    at sendAsync ($deno$/ops/dispatch_json.ts:98:10)
```

I debug it. When i found this code is raises error

```typescript
await Deno.lstat('~/.zshrc')
```

But this code works

```typescript
await Deno.lstat('/home/zakuro/.zshrc')
```

And this C code works.

```c
#include <sys/stat.h>

int main() {
  struct stat s;
  lstat("~/.zshrc", &s);
}
```

I think lstat of Deno is broken. But I'm beginner for deno. I can't resolve it by myself. Please help.

**Comment by ry** [comment]
The path alias ~ is not evaluated by Deno and will not be. Use the HOME environmental variable.

**Comment by ry** [comment]
Your C example does not work.

**Comment by zakuro9715** [comment]
Sorry. I'm wrong. My check was not enough
