### ISSUE TITLE
Deno.utime() errors when supplied date parameter

### ISSUE THREAD

**Issue by cknight** [denoland/deno#4546]
Given the following code:
```javascript
await Deno.utime("my_file.txt", new Date(), new Date());
```
The process errors out on v0.38.0 with:

> error: Uncaught InvalidData: invalid type: floating point `1585688574.996`, expected u64

The same error is present with `Deno.utimeSync()` as well.

**Comment by parkerdgabel** [comment]
I'm looking to contribute. I'll take a look at it.
