### ISSUE TITLE
setCookie resets other cookies

### ISSUE THREAD

**Issue by jakajancar** [denoland/deno#4550]
`setCookie` in `std/http/cookie.ts` will reset other cookies being set (replace the entire `Set-Cookie` header). I did not expect this.

Perhaps the easiest fix is to change from:

    setCookie(res: Response, cookie: Cookie)

to

    setCookies(res: Response, cookies: Cookie[])

Alternatively, perhaps `res.headers.append()` can be used in `setCookie`.

As it stands now, there is no way to set/modify two cookies in a single response with these utilities (e.g. session id and nonce for OAuth).

**Comment by zhmushan** [comment]
@jakajancar This issue should be closed

**Comment by ry** [comment]
Fixed in #4558

**Comment by jakajancar** [comment]
👍 thanks @zhmushan
