### ISSUE TITLE
Request: `deno repl --inspect` to use Chrome console as Deno REPL

### ISSUE THREAD

**Issue by KSXGitHub** [denoland/deno#4554]
I have tried `deno repl --inspect` and it prints an error:

```
error: Found argument '--inspect' which wasn't expected, or isn't valid in this context
```

**Comment by ry** [comment]
This should be a pretty easy fix for someone wanting to explore the rust code. I'd guess 5 lines at most.

**Comment by KSXGitHub** [comment]
> I'd guess 5 lines at most.

and hours of compilation.

**Comment by zhmushan** [comment]
@KSXGitHub This issue should be closed.
