### ISSUE TITLE
print "Bad mode {}. Use 'release' or 'debug' (default)" % build_mode()

### ISSUE THREAD

**Issue by George35mk** [denoland/deno#457]
Hi want to test the deno project can someone explain to me how to run this on windows 10 x64 without errors.

### I get this error when i try to run `\deno\tools` with python 3.6 and 2.7
```
PS C:\Users\giorg\Documents\Development\Clones\deno\tools> python .\setup.py
  File ".\setup.py", line 20
    print "Bad mode {}. Use 'release' or 'debug' (default)" % build_mode()
                                                          ^
SyntaxError: invalid syntax
PS C:\Users\giorg\Documents\Development\Clones\deno\tools>
```

**Comment by hayd** [comment]
At the moment these scripts only support python 2. Also see https://github.com/denoland/deno/issues/118#issuecomment-394293252.

Note: a python 3 SyntaxError is a good way to show that only python 2 is supported. It's unclear if the deps (specifically v8) also need python 2 anyway i.e. no benefit of deno supporting python 3 yet.

**Comment by George35mk** [comment]
@haydI have tried and with 2.7 but I get the same error

**Comment by piscisaureus** [comment]
@George35mk 

It looks like you are using Python 3.
 
Our python scripts sometimes run other python scripts. If python3 is still in PATH that it'll run the child script with Python3.

Try this:

```cmd
set PATH=c:\Python27;%PATH%
python tools\setup.py
```

**Comment by ry** [comment]
I've opened a standalone issue for python3 compatibility #464
