### ISSUE TITLE
bug: deno web server ran from within docker container doesn't serve requests 

### ISSUE THREAD

**Issue by alexanderGalushka** [denoland/deno#4571]
Regression in v0.38.0
Works in v0.37.1

--- Dockerfile ---
...
EXPOSE 8080
CMD ["deno", "-A", "--allow-run", "--allow-net", "--allow-read", "--allow-env", "--v8-flags=--disallow-code-generation-from-strings", "main.ts"]
------------------

`curl http://localhost:8080`

returns

`curl: (52) Empty reply from server`

**Comment by zhmushan** [comment]
Could you provide the repo link?

**Comment by alexanderGalushka** [comment]
@zhmushan it is still broken as of v0.41.0 here is the github repository with a simple deno webserver app running on v0.41.0

**Comment by alexanderGalushka** [comment]
@kitsonk @hayd if you have a chance can you please look into this issue, should deno have a docker smoke test to prevent regressions like this?

**Comment by kitsonk** [comment]
You never linked to reproduction.

**Comment by alexanderGalushka** [comment]
@kitsonk my bad https://github.com/alexanderGalushka/deno-test

**Comment by zhmushan** [comment]
You are missing “host: 0.0.0.0”

**Comment by hayd** [comment]
Yeah, presumably this is something esoteric in docker (the local IP address handling is very particular) - no idea why it would have worked before, did you update docker itself?
The [example](https://github.com/hayd/deno-docker/blob/0cf43474eb718a6e2911dfb216796eccb4f3317d/example/main.ts#L4) works and uses 0.0.0.0.

The current smoke test is run welcome.ts 😄, it could/should be more.

**Comment by alexanderGalushka** [comment]
@hayd @zhmushan thank you, it works
