### ISSUE TITLE
Rename makeTemp{File,Dir} -> makeTemp{File,Dir}Path

### ISSUE THREAD

**Issue by dubiousjim** [denoland/deno#4592]
It'll eventually be desirable to have maketemp-like functions that return an open file or open directory (the latter needs more infrastructure to be in place first). Those will be the ones best meriting the names makeTemp{File,Dir} (or some shortened variation, I'm not going to get into that).

So before the API freeze, we should consider renaming the existing functions makeTemp{File,Dir} to `makeTempFilePath`, `makeTempDirPath`. Or something like that.

**Comment by bartlomieju** [comment]
[`Deno.makeTempDir`](https://doc.deno.land/https/github.com/denoland/deno/releases/latest/download/lib.deno.d.ts#Deno.makeTempDir) and [`Deno.makeTempFile`](https://doc.deno.land/https/github.com/denoland/deno/releases/latest/download/lib.deno.d.ts#Deno.makeTempFile) are now part of stable API so they won't change until next major version.
