### ISSUE TITLE
test command --quiet option not working

### ISSUE THREAD

**Issue by srackham** [denoland/deno#4596]
```
$ deno --version
deno 0.38.0
v8 8.2.308
typescript 3.8.3

$ deno test -A -q examples/tests/cat_test.ts 
running 1 tests
test [examples/cat] print multiple files ... ok (13ms)

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out (13ms)
```

**Comment by gcaptn** [comment]
I'm getting the same issue on the latest release (v1.10.1):
```
D:\repro>deno --version
deno 1.10.1 (release, x86_64-pc-windows-msvc)
v8 9.1.269.27
typescript 4.2.2

D:\repro>deno test -q
running 1 test from file:///D:/repro/test.ts
test _ ... ok (10ms)

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out (36ms)
```

**Comment by caspervonb** [comment]
That is expected result @gcaptn, what are you expectations?
Quiet only silences diagnostic messages and disables the global `console` object.

**Comment by gcaptn** [comment]
Thought it should completely silence non-errors just like the linked PR. Thanks for letting me know 👍

**Comment by caspervonb** [comment]
I'll be adding a terse reporter soon tho, so that'll provide an option for a quieter reporter.

**Comment by AuracleTech** [comment]
> Quiet only silences diagnostic messages and disables the global `console` object.
Now the question is why do I need to search the web to find this simple answer when it could be written in the --help
Currently there's `Suppress diagnostic output` ... what does that tell me, what diagnostics, for and from what, erf...

**Comment by Vasdranna** [comment]
Is there any update on this?

I'd love a flag like `deno test --quiet` (or similar) that suppresses successful test output and only prints information when a test fails.

A common workflow for me is running tests before running the program: `deno test && deno run main.ts`
However, I don't want to show any output of the tests if they pass.
