### ISSUE TITLE
Request: more native numeric types

### ISSUE THREAD

**Issue by dharmax** [denoland/deno#4605]
May be it's too much, especially for early stages, but i'd love to see native support for:

1. **Integers**, perhaps even bytes, 16bit, 32bit, 64bit, signed and unsigned. 
2. **Fixed-point** floating numbers

Is there any JS inherit issue preventing that?

**Comment by eliassjogreen** [comment]
This and #4606 and #4607 are issues that could be implemented by creating a custom module/plugin for it. It's not withing the scope the deno project. Deno also strives to be web compatible and these are not web compatible issues. I guess #4606 could get support with #1629 and #4607 could be done with webworkers.

**Comment by kitsonk** [comment]
We won't support non ECMAScript or TypeScript syntax.
