### ISSUE TITLE
Request: stronger multi-threading model

### ISSUE THREAD

**Issue by dharmax** [denoland/deno#4607]
i like the major aspect of the current node threading support, that dictates that the communication between with the thread is message based, and except for a specially built objects for that matter - only immutable data can be passed. However, i don't like that the code must be in a separate file; i'd like to be able to do something like that: 

``` 
const myThread = new Thread( (t:ThreadApi)=> myFunction(t)) 
myThread.on('event', e=> console.log(e.data))
await myThread.start()

async function myFunction(t:ThreadApi):Promise<any> {

for (let i=0; i<10; i++)
    t.postMessage('event', i)

return "I'm done"

}

```
Yes, **syntactically**, i don't know how to prevent the called function to have side-effects which will contradict the isolation principle, but let's say that we'd settle for a run-time exception in case the function attempts to touch anything outside its basic closure.... Wouldn't you like to have such a multi-threading support?

**Comment by kitsonk** [comment]
The threading model for Deno is to use web workers.

**Comment by bartlomieju** [comment]
As pointed by @kitsonk Deno uses browser standard [`Worker API`](https://developer.mozilla.org/en-US/docs/Web/API/Worker) to provide threading.
