### ISSUE TITLE
Check if location exists at DiskCache::new()

### ISSUE THREAD

**Issue by Drunpy** [denoland/deno#4616]
Attend the TODO at [disc_cache.rs](https://github.com/denoland/deno/blob/master/cli/disk_cache.rs)

DiskCache::new() to check if dir exists if not create the given dir.

**Comment by parkerdgabel** [comment]
I'll do it.

**Comment by Drunpy** [comment]
Hey @parkerdgabel, thanks for your interest but I've already done at #4617

**Comment by parkerdgabel** [comment]
Ok!

**Comment by bartlomieju** [comment]
Done in #4617
