### ISSUE TITLE
.deno.test.ts should be moved to temporary directory

### ISSUE THREAD

**Issue by KSXGitHub** [denoland/deno#4619]
Every time I execute `deno test`, a temporary `.deno.test.ts` is created in my project folder. I think this file should be renamed to `/tmp/${unique_id}.deno.test.ts`.

**Comment by bartlomieju** [comment]
`.deno.test.ts` is not written to file system, it's only kept in memory. Besides that, it's intentional that it's created per current directory to avoid unnecessary TS compilation.

**Comment by kitsonk** [comment]
The output is confusing though.  It looks like it is being written to the file system.  Maybe it shouldn't be mentioned at all.
