### ISSUE TITLE
Protecting against runaway scripts

### ISSUE THREAD

**Issue by newtack** [denoland/deno#463]
When running 3rd party scripts with Deno we want to ensure that the scripts can't go into infinite loop and hang the whole process. Ideally, we want to have a way of performing some timeout (run for maximum of 1 second for example) and then return an error, without crashing the process. 

Can this be supported in Deno (now or future)?

**Comment by ry** [comment]
No - we can't definitely tell if an infinite loop originated from a certain module due to monkey patching.  I think this will be best handled outside of deno.

**Comment by newtack** [comment]
Got it. Is there a way to do it outside of Deno without resorting to a separate process?

**Comment by ry** [comment]
I mean we could add a timeout or something to `main()` - but I think that's out of scope. I'm sure there's a unix utility to kill a process after some time.

**Comment by benjamingr** [comment]
@ry there is (`timeout`) though I thought the request was more about third-party modules you use with Deno or the ability to run them in a way that is isolated.

(I agree it's out of scope for v1 for sure)
