### ISSUE TITLE
Deno fails to compile when importing Typescript references.

### ISSUE THREAD

**Issue by Naragod** [denoland/deno#4630]
If I add the following import statement to my typescript file:
`import { ReadableStream } from "https://cdn.jsdelivr.net/npm/typescript@3.8.3/lib/lib.dom.d.ts";`

when trying to create a new ReadableStream

`const readStream = new ReadableStream({
  start(controller: any) {
    controller.enqueue("hello world");
  },
});`

I see 100+ typescript errors.

If I remove the import statement, I see the following error `error TS2304: Cannot find name 'ReadableStream'.`

**Comment by kitsonk** [comment]
Don't do that.

Deno includes all the types it supports.  Your example compiles fine under Deno 0.39.0.  What version of Deno are you using?

**Comment by Naragod** [comment]
@kitsonk I am using the latest release. I installed deno yesterday.

**Comment by kitsonk** [comment]
> Your example compiles fine under Deno 0.39.0.

**Comment by Naragod** [comment]
@kitsonk any suggestions? I am running on linux mint VERSION="19.3 (Tricia)"

**Comment by kitsonk** [comment]
What are you running on the command line?  You haven't provided a full reproduction.

**Comment by Naragod** [comment]
This is my index.ts file

`// import { ReadableStream } from "https://cdn.jsdelivr.net/npm/typescript@3.8.3/lib/lib.dom.d.ts";`

`const readStream = new ReadableStream({ start(controller: any) { controller.enqueue("hello world"); }, });`


This is what I am using to run it. `deno run index.ts`

**Comment by kitsonk** [comment]
My apologies, it was only added to master as part of #4581.  It won't be available until Deno 0.40.0 which should be in a couple of days.

**Comment by bartlomieju** [comment]
@Naragod does this problem still persist with latest version of Deno?

**Comment by bartlomieju** [comment]
Closing as stale
