### ISSUE TITLE
SUGGESTION To choose between cache module or no

### ISSUE THREAD

**Issue by cindRoberta** [denoland/deno#4643]
currently on Deno, it's done like this:

```javascript
// main.ts
import "https://deno.land/std/examples/welcome.ts";  
// output: Welcome to Deno 🦕
```

the file is cached in .cache/deno/gen/https/deno.land/std/examples/welcome.ts.js

my ideia is, the main.ts above wouldn't be cached that way

to cache would be like this:

________________________________________________________________________

to cache fragmented on .cache/deno/deps you could do like this:

```javascript
// main.ts
import "https://deno.land/std/examples/welcome.ts" cachefragmentedon ".cache/deno/deps/";
// output: Welcome to Deno 🦕
```

this would be cached on .cache/deno/deps/https/deno.land/std/examples/welcome.ts.js

________________________________________________________________________

to cache on a folder inside .cache/deno, you could do like this:

```javascript
// main.ts
import "https://deno.land/std/examples/welcome.ts" cacheon ".cache/deno/deps/module/version/";
// output: Welcome to Deno 🦕
```

this would be cached on .cache/deno/deps/module/version/welcome.ts.js

________________________________________________________________________

to cache fragmented in other folder out of .cache/deno/deps, would be:

```javascript
// main.ts
import "https://deno.land/std/examples/welcome.ts" cachefragmentedon "/home/user/folder/";
// output: Welcome to Deno 🦕
```

this would be cached on /home/user/folder/https/deno.land/std/examples/welcome.ts.js

________________________________________________________________________

to cache in other folder out of .cache/deno, would be:

```javascript
// main.ts
import "https://deno.land/std/examples/welcome.ts" cacheon "/home/user/folder/module/version/";
// output: Welcome to Deno 🦕
```

this would be cached on /home/user/folder/module/version/welcome.ts.js

**Comment by bartlomieju** [comment]
Thanks for the issue @cindRoberta but what you are proposing here:
a) is not a part of the language spec,
b) would complicate internal behavior of Deno significantly as it currently relies on deterministic paths in cache

There is a [module attribute proposal](https://github.com/tc39/proposal-module-attributes) currently in stage 1 that would allow similar syntax, but until it reaches stage 3 it won't make it to Deno.

**Comment by cindRoberta** [comment]
> Thanks for the issue @cindRoberta but what you are proposing here:
> a) is not a part of the language spec,
> b) would complicate internal behavior of Deno significantly as it currently relies on deterministic paths in cache
> 
> There is a [module attribute proposal](https://github.com/tc39/proposal-module-attributes) currently in stage 1 that would allow similar syntax, but until it reaches stage 3 it won't make it to Deno.

I understand the impossibility of make this if depends on Typescript and Javascript

I don't understood the relation of my proposal with [module attribute proposal](https://github.com/tc39/proposal-module-attributes)
