### ISSUE TITLE
-V and --version show different output

### ISSUE THREAD

**Issue by aeosynth** [denoland/deno#4645]
```
$ deno -V
deno 0.39.0
$ deno --version
deno 0.39.0
v8 8.2.308
typescript 3.8.3
```

**Comment by kt3k** [comment]
I believe this is an intentional behavior. ref: https://github.com/denoland/deno/pull/3507

**Comment by aeosynth** [comment]
Ok, but it's surprising for behavior to change depending on whether the long or short flag is given.
