### ISSUE TITLE
Guard deno install permissions

### ISSUE THREAD

**Issue by shian15810** [denoland/deno#4654]
If I grant only file write permission to a bin installed using `deno install --allow-write`, it can just modify its bin file to grant itself all permissions with `--allow-all` using `fs` module.

For example, `deno install --allow-write foo https://path/to/bar.ts` generate `~/.deno/bin/foo` with the following content:

```
#!/bin/sh
# generated by deno install
deno "run" "--allow-write" "https://path/to/bar.ts" "$@"
```

When `foo` is executed on the first run, it then `fs.writeFileStr()` the following content to `~/.deno/bin/foo`:

```
#!/bin/sh
# generated by deno install
deno "run" "--allow-all" "https://path/to/bar.ts" "$@"
```

On the second run, `foo` is granted all permissions.

To the end user, he/she **explicitly** grant only `--allow-write` to install `foo`, but on the second run, `foo` is granted all permissions without the end user knowing.

Should there be a file permission guard to deny write permission to `~/.deno`?

**Comment by bartlomieju** [comment]
I don't think this issue is really actionable, users can install scripts in various location and there's no way we can validate them all. To prevent such cases users might specify list of files/directories to `--allow-write`. @nayeemrmn @kitsonk thoughts?

**Comment by kt3k** [comment]
I think we should discourage the use of `--allow-write` with `deno install` at least in the documentation. Maybe it's better to print some warning in the console.

Personally I think `--allow-write` without path argument is usually anti-pattern because it gives too much permissions to the command. Most of decent CLI tools only write to `.` (cwd), `$HOME/.some-custom-dir`, etc, and don't need to write to the entire filesystem.

**Comment by rivy** [comment]
> Personally I think `--allow-write` without path argument is usually anti-pattern because it gives too much permissions to the command. Most of decent CLI tools only write to `.` (cwd), `$HOME/.some-custom-dir`, etc, and don't need to write to the entire filesystem.

As a counterpoint, the (widely-used) [XDG standard](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) makes using only specified directories (ie, `--allow-write=...`) problematic.

**Comment by hayd** [comment]
@rivy how is it problematic? 

You can pass env variable(s) to --allow-write to give explicit access.
(Note, I think, that deno itself already does write there.)

**Comment by rivy** [comment]
@hayd , there are at least a few difficulties:

1. *verbosity* - a user has supply some some script-dependent combination of the XDG environment variables on a case-by-case basis; for example, `deno run --allow-write=$XDG_CONFIG_HOME,$XDG_DATA_HOME,$XDG_CACHE_HOME,$XDG_STATE_HOME,$XDG_RUNTIME_DIR ...`
2. *path lists* - `XDG_CONFIG_DIRS` and `XDG_DATA_DIRS` are path lists and cannot be simply supplied as environment variables
3. *cross-platform use* ~ supplying an environment variable is platform-dependent (eg, `$XDG_CONFIG_HOME` (POSIX) vs `%XDG_CONFIG_HOME%` (Windows))
