### ISSUE TITLE
Dead code documentation link 

### ISSUE THREAD

**Issue by melkir** [denoland/deno#4657]
Hey folks,

I was reading the code about the [inspector](https://github.com/denoland/deno/pull/4484) support and found out that the following link is no longer available:
https://hyperandroid.com/2020/02/12/v8-inspector-from-an-embedder-standpoint/

Presented there in the code:
https://github.com/denoland/deno/blob/master/cli/inspector.rs#L5

I dunno if there's an alternative link for this documentation, but I suppose that it can be removed if not.

**Comment by ry** [comment]
Link works for me...

**Comment by melkir** [comment]
Thank @ry, apparently the domain was temporary down yesterday, it has been fixed.

**Comment by hyperandroid** [comment]
Sorry, I missed to renew my domain.
My apologies for any inconvenience coming from this.
