### ISSUE TITLE
In JS, flatbuffers.Builder allocates a new Uint8Array for each message.

### ISSUE THREAD

**Issue by ry** [denoland/deno#466]
Typed Array allocations cost time. We suspect this will show up high in profiles.

Do not try to solve this without discussing with me first, there are undocumented plans in this area. In particular, #462 should be landed before addressing this.

The solution is to provide a custom `flatbuffers.Builder` or modify the flatbuffers library to allowed for a shared buffers.

**Comment by benjamingr** [comment]
In general, I'd expect something like slab allocation - although I'd expect it to be something the flatbuffers package can solve.

**Comment by hiun** [comment]
ㅓ2018년 8월 7일 (화) 오후 5:00, Benjamin Gruenbaum <notifications@github.com>님이
작성:

**Comment by ry** [comment]
Fixed in 213885a9d00a913e3fd2eb21a5992efb63c888f5
