### ISSUE TITLE
Cannot be installed with Homebrew on Linux

### ISSUE THREAD

**Issue by davidbailey00** [denoland/deno#4664]
According to the Deno website, Deno can be installed using Homebrew on Linux:

![Using Homebrew (macOS or Linux): brew install deno](https://user-images.githubusercontent.com/4248177/78697570-e6587200-78f8-11ea-9dc4-01d039116907.png)

However, when attempting to install on Linux, the following error appears:

```sh
$ brew install deno
deno: macOS is required.
Error: An unsatisfied requirement failed this build.
```

See also https://github.com/denoland/deno/issues/1486#issuecomment-606393413

**Comment by hayd** [comment]
@chrmoritz  on related issue in [deno_install](https://github.com/denoland/deno_install/issues/93#issuecomment-595448673):

> This is unfortunately related to the fact that v8 (in rust_v8, a dependency of deno) still requires Python 2 to build. After the python@2 removal (from earlier this year), there is just no reliable way for Linuxbrew anymore to ensure that the python@2 build dependency is fulfilled, because not all Linux distribution are still shipping with a Python 2 version installed by default (unlike all current versions of macOS, but I'm not sure if this will still be the case after this fall).
> 
> In conclusion, we can't offer Linux support for installing deno with Homebrew anymore, until the Python 2 => 3 situation is sorted out and the Linux part should probably be removed from the docs until then.

But [pypy2 might be the workaround](https://github.com/denoland/deno_install/issues/93#issuecomment-595448673)...

**Comment by chrmoritz** [comment]
Exactly, it's related to the Python 2 EOL and the fact that Chromium/build unfortunately still only works with Python 2. Building anything which requires Python 2 on Homebrew (for Linux) is just no longer supported at all (it still works on macOS if the ancient system python 2 is working with it, but apple could decide to drop that anytime too).

I've now moved my experiment with `pypy2` in it's own tap: https://github.com/chrmoritz/homebrew-deno/blob/master/Formula/deno.rb.

You could try it out with `brew install chrmoritz/deno/deno` (it also includes a Github Actions built bottle for 0.40.0).
