### ISSUE TITLE
Response constructor is non-standard

### ISSUE THREAD

**Issue by ry** [denoland/deno#4667]
This is what we're using:

https://github.com/denoland/deno/blob/v0.39.0/cli/js/web/fetch.ts#L286-L295

Compare with 

https://github.com/microsoft/TypeScript/blob/3398c9bfe1e474e2f81e5ea05d01645e329e5860/src/lib/dom.generated.d.ts#L12604

**Comment by kitsonk** [comment]
Yucky...

I am in the throws of cleaning up events to align them to the standards, but this is another one.

**Comment by jimmywarting** [comment]
Well, this was unexpected when i first tried out `new Response('foo').arrayBuffer()`

**Comment by marcosc90** [comment]
I'm currently working on this.
