### ISSUE TITLE
Deno runtime documentation [src] links downloads source

### ISSUE THREAD

**Issue by viddler-no** [denoland/deno#4688]
From new https://doc.deno.land/, clicking [view the Deno runtime documentation](https://doc.deno.land/https/github.com/denoland/deno/releases/latest/download/lib.deno.d.ts), resolves to https://doc.deno.land/https/github.com/denoland/deno/releases/latest/download/lib.deno.d.ts

From here, [src] links downloads the source.

**Comment by lucacasonato** [comment]
Duplicate and wrong repo: https://github.com/denoland/doc_website/issues/57
