### ISSUE TITLE
Debugger not working in VS Code

### ISSUE THREAD

**Issue by David-Else** [denoland/deno#4691]
`deno 0.40.0`
`vs code 1.44.0`

`launch.json`
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Launch via npm",
      "type": "node",
      "request": "launch",
      "cwd": "${workspaceFolder}",
      "runtimeExecutable": "deno",
      "runtimeArgs": [
        "-A",
        "--inspect",
        "--importmap=./import_map.json",
        "mod.ts"
      ],
      "port": 9229
    }
  ]
}
```
`debug console output:`
```
/home/david/.local/bin/deno -A --inspect-brk --importmap=./import_map.json mod.ts 
Debugger listening on ws://127.0.0.1:9229/ws/b3434192-95e8-42ad-9245-3c939ce9d283
Debugger session started.
```
but nothing is showing in the debug window. 'loaded scripts` flashes on, the bottom of the screen flashes orange, but then nothing.

I used the info from https://medium.com/@akmittal/setup-vscode-for-deno-with-autocomplete-debugging-support-f66e58ecd1db that says it should work? Maybe I made an error? Thanks.

**Comment by hayd** [comment]
Issue is here: https://github.com/axetroy/vscode-deno/issues/111
I cannot get that example to work either (though haven't tried very hard)...

**Comment by gewoonwoutje** [comment]
You could add `"outputCapture": "std"` to your configuration to capture the console logs.

**Comment by David-Else** [comment]
@gewoonwoutje Thanks, I now see the output of the program... not still no debugging... anyone got this working or are we waiting on the next update?

**Comment by kitsonk** [comment]
Feels like this is discussion best suited for the plugin repo.
