### ISSUE TITLE
fmt is not platform independant

### ISSUE THREAD

**Issue by ronhippler** [denoland/deno#4709]
I run `deno fmt --check` as github action step.
It passed on linux and mac but found 9 not formatted files on windows.

deno v0.40.0

**Comment by kitsonk** [comment]
Can you provide more details please.

**Comment by ronhippler** [comment]
Sry I have no windows pc.
I would guess fmt wants to change the line endings because it complains about all files.

**Comment by kitsonk** [comment]
GitHub actions log... providing some of your log details would be useful.  Otherwise we are just guessing.  When you say 9 files, those were all the TypeScript files in you code.  Can you share a link to the repo?  Anything more than "it doesn't work" is helpful.

**Comment by ronhippler** [comment]
I created a testrepo and made a few tests.
https://github.com/ronhippler/deno_fmt_test/runs/580608083
Deno fmt is not the problem. It converts to LF as expected but the git checkout for github actions uses CRLF as default on windows.

see actions/checkout#135

**Comment by justjavac** [comment]
add a `.gitattributes` file:

```
* eol=lf
```
