### ISSUE TITLE
Support top-level await

### ISSUE THREAD

**Issue by ry** [denoland/deno#471]
https://github.com/Microsoft/TypeScript/issues/25988

https://github.com/tc39/proposal-top-level-await

https://bugs.chromium.org/p/v8/issues/detail?id=9344

**Comment by kitsonk** [comment]
If we wanted this to work while we are waiting on TC39/TypeScript, we would have to do a bit of _hackery_.

When emitting a module with TLA, we would have to specifically ignore the diagnostic error related to that.  TypeScript always emits, it is _us_ who then chooses to throw.  I _might_ be a good idea to actually log a warning, since when TLA arrives, it could be a different behaviour to what we would have.

Then we would have to modify the AMD factory function to be `async` and deal with awaiting the promise resolution returned from that factory before we consider the module "resolved".

**Comment by kitsonk** [comment]
The drawback, like the module specifiers ending in `.ts`, we won't be able to get any of the editors to accept this code... so while it will run properly under deno, it won't look pretty in editors.

**Comment by ry** [comment]
https://github.com/tc39/proposal-top-level-await#optional-constraint-top-level-await-can-only-be-used-in-modules-without-exports
Potentially it will be easier to do with this restriction. We only really need it for "main" scripts.

**Comment by aharonNF** [comment]
TC39 start promoting it.
Do we want to be part of it?
https://github.com/tc39/proposal-top-level-await/issues/42

**Comment by kitsonk** [comment]
Well, one member of TC39 is trying to get it moving again.  I am not sure we can really add anything to it.  The biggest challenge is that they need to address the functional challenge that [top-level await and how modules are evaluated](https://github.com/tc39/proposal-top-level-await/#proposed-solutions) and as Ry mentioned above, the optional restriction would make it a lot easier, but this is really needs the implementors to figure out how to do it, versus adding another voice to the mix.

**Comment by kitsonk** [comment]
Top level await has gone [Stage 3](https://github.com/tc39/proposal-top-level-await).  That means that the TypeScript team should be willing to implement it now.

**Comment by ry** [comment]
A V8 issue has been created for this https://bugs.chromium.org/p/v8/issues/detail?id=9344

**Comment by kitsonk** [comment]
The TypeScript team are indicating that it will be challenging to downemit and are considering not allowing a downemit.  That is find from our perspective, but that "problem" continues to delay them addressing the issue.

**Comment by kitsonk** [comment]
TLA is scheduled for TS 3.7 as well (early-November): microsoft/TypeScript#33352

**Comment by ry** [comment]
Relanded https://github.com/v8/v8/commit/798cb9045cc835d5ff3418e563643782fed823b2

**Comment by ry** [comment]
Parsing support has landed https://chromium.googlesource.com/v8/v8.git/+/0ceee9ad28c21bc4971fb237cf87eb742fc787b8

**Comment by ry** [comment]
Deno v0.19 has integrated the changes from V8 and [has a test demonstrating TLA](https://github.com/denoland/deno/blob/v0.19.0/cli/tests/top_level_await.js).

However this is JS only support. We still need TS to not barf on TLA syntax. Therefore I'm leaving this issue open until we have a corresponding `tests/top_level_await.ts`.

**Comment by kitsonk** [comment]
That should be doable without ignoring error codes with TS 3.7 on Nov 5th.

**Comment by somombo** [comment]
@kitsonk In this [latest TS 3.7 announcement](https://devblogs.microsoft.com/typescript/announcing-typescript-3-7-beta/), there is no indication that there will be any support for TLA by Nov 5th.

**Comment by kitsonk** [comment]
That is the beta, and the announcement is what is in the beta. The iteration plan mentioned above still lists it. I am sure Ry and I will chat to the team about it next week at TSConf.

**Comment by hayd** [comment]
In case people are following this, here's v8 issues for top-level for-await (not merged yet):

https://bugs.chromium.org/p/v8/issues/detail?id=9817
https://bugs.chromium.org/p/v8/issues/detail?id=9825

**Comment by somombo** [comment]
> In this latest TS 3.7 announcement, there is no indication that there will be any support for TLA by Nov 5th.

guess I was right then.. 
did Daniel R give a reason why it won't be included?

**Comment by hayd** [comment]
Actually, re-reading those commits above I think top-level for-await is in recent V8 versions. IIRC this means we can support it in ts easily once we upgrade V8.

**Comment by JavaScriptDude** [comment]
I see that TypeScript now has first release with [Top Level Await at 3.8](https://devblogs.microsoft.com/typescript/announcing-typescript-3-8/). Does this help the progress of TLA in Deno?

**Comment by kitsonk** [comment]
Deno has TLA. You are commenting on a closed issue.

**Comment by JavaScriptDude** [comment]
Thanks.

**Comment by anuragvohraec** [comment]
> Deno has TLA. You are commenting on a closed issue.

This exampl seems to not work :
```ts
function add(a: any,b: any,c: any): any{
	if(a+b>10){
		return c("My error",a+b);
	}else{
		return c(null, a+b);
	}
}

try{

 let r = await (async()=>{
	return add(4,5,(e: any, r: any)=>{
		if(e) throw e;
		return r;	
	});
 })();
}catch(e){
console.log("Yes! caught error from call back: ", e);
}
```

**Comment by kitsonk** [comment]
@anuragvohraec this is a TypeScript problem, and the error is a mis-leading... because you don't have any imports or exports in the module, TypeScript is treating this like a script instead of a module.  This is causing the parsing in the try block to be a bit off, and instead of telling you that the module isn't a module error, it is giving you this strange error.

To work around the issue just add the following at the start or the end of the module:

```ts
export {};
```

**Comment by anuragvohraec** [comment]
> To work around the issue just add the following at the start or the end of the module:
> 
> ```ts
> export {};
> ```

still same error :
```ts
export {};

function add(a: any,b: any,c: any): any{
	if(a+b>10){
		return c("My error",a+b);
	}else{
		return c(null, a+b);
	}
}

try{

 let t = await (async()=>{
	return add(4,5,(e: any, r: any)=>{
		if(e) throw e;
		return r;	
	});
 })();
 console.log(t);
}catch(e){
console.log("Yes! caught error from call back: ", e);
}
```

**Comment by JavaScriptDude** [comment]
@anuragvohraec - Pardon my N00b question, but when would you use the `(async(){...})()` in real world logic in Deno? 

From my understanding, all functions in `Deno` are implicitly async and I'm not sure if this makes this `async()...` method redundant?

**Comment by lucacasonato** [comment]
No, not all functions in are implicitly `async`. Only the global scope (so the top level of a module outside of a function scope) and all function scopes declared with the `async` keyword.

```ts
await foo() // valid here

function test1() {
  await foo() // invalid here
}

async function test2() {
  await foo() // valid here
}
```

More info on top level await: https://v8.dev/features/top-level-await

**Comment by JavaScriptDude** [comment]
@lucacasonato - Thanks, that makes sense.

I found a good example explaining the use of `async()=>` [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function).

@anuragvohraec - Here is a tweak to your code that works for me:

```
function add(a: any,b: any,c: any): any{
	if(a+b>10){
		return c("My error",a+b);
	}else{
		return c(null, a+b);
	}
}

(async()=>{
    try{
        let t = await (async()=>{
            return add(4,5,(e: any, r: any)=>{
                if(e) throw e;
                return r;	
            });
        })();
        console.log(t);
    }catch(e){
        console.log("Yes! caught error from call back: ", e);
    }
})()
```

**Comment by kitsonk** [comment]
@anuragvohraec it is a TypeScript lexing issue.  Upstream bug filed: https://github.com/microsoft/TypeScript/issues/38483.

**Comment by anuragvohraec** [comment]
> @anuragvohraec - Pardon my N00b question, but when would you use the `(async(){...})()` in real world logic in Deno?

The real world example for this will be to convert a call back based asynchronous function be converted to async await based without using a Promise API.

If you see my example:
```js
function add(a: any,b: any,c: any): any{
	if(a+b>10){
		return c("My error",a+b);
	}else{
		return c(null, a+b);
	}
}

try{

 let t = await (async()=>{
	return add(4,5,(e: any, r: any)=>{
		if(e) throw e;
		return r;	
	});
 })();
 console.log(t);
}catch(e){
console.log("Yes! caught error from call back: ", e);
}```

`c` is a callback function.
I was mere using a IIFE to convert my call back back based function to a async-await based function.

**Comment by anuragvohraec** [comment]
> No, not all functions in are implicitly `async`. Only the global scope (so the top level of a module outside of a function scope) and all function scopes declared with the `async` keyword.
> 
> ```ts
> await foo() // valid here
> 
> function test1() {
>   await foo() // invalid here
> }
> 
> async function test2() {
>   await foo() // valid here
> }
> ```
> 

The code I have shared do not commits any mistake mentioned in your code samples.

**Comment by kitsonk** [comment]
> The code I have shared do not commits any mistake mentioned in your code samples.

@anuragvohraec I don't think @lucacasonato was complaining about your code, but was just trying to inform @JavaScriptDude on how async/await works.  Your code is valid JavaScript, and should be valid TypeScript but TypeScript has a bug.

**Comment by somombo** [comment]
is TLA supported in deno REPL?

I cant seem to get the following to work.

> using Deno v.1.0.0

```ts
$ deno
> console.log(await Promise.resolve('Success'))
```

It just seems to await indefinitely without allowing me to input any further commands.

**Comment by josephrocca** [comment]
@somombo #3700 is tracking the addition of top-level await to the repl
