### ISSUE TITLE
deno test should run jsdoc example code

### ISSUE THREAD

**Issue by ry** [denoland/deno#4716]
As cargo test does. This makes example code way more robust.

We’d need a way to extract all the examples - but now that we have deno doc - this should be not too difficult.

**Comment by humancalico** [comment]
@ry Can I work on this?

**Comment by ry** [comment]
@humancalico Sure go for it. I'd start by defining an internal rust API for getting all of the code examples given a script's URL. Once that's working and tested, it should be just a bit more work to hook it into "deno test".

**Comment by humancalico** [comment]
@ry Should this be implemented directly for `deno test` or as a part of `deno doc --test` first? Kinda like Rust does it with `rustdoc --test`

**Comment by iykekings** [comment]
@humancalico and @ry what is the progress on this? I'm interested on working on it if nobody is on it.

**Comment by humancalico** [comment]
@iykekings I got sidetracked. Go ahead if you want to.😊

**Comment by bartlomieju** [comment]
For posterity: we now support type-checking docstrings, running examples is still a TODO that @caspervonb was looking into

**Comment by waldyrious** [comment]
> we now support type-checking docstrings

For the record, that was done in #10521, and later #11421 extended that to also type-check code blocks within markdown files.

**Comment by linus** [comment]
I have published a module which could potentially handle this: https://deno.land/x/doctest@0.1.2

A couple of issues I would like to get fixed:

1. It runs all tests using indirect `eval` in a Worker. The best case would be if we could implement this using something similar to Node's `vm.runInContext`.
2. Currently, it doesn't automatically discover and run the @example, it needs to be wrapped in `Deno.test((t) => doctest(t, file))` in a file under test. Any pointers on hooking it into `deno test` would be appreciated.
