### ISSUE TITLE
Weird issue on 0.40.0 with Deno.readFileSync

### ISSUE THREAD

**Issue by shian15810** [denoland/deno#4717]
I was trying `createRequire` and stepping into a weird issue.

This is only reproducible on deno 0.40.0, not 0.39.0.
I've only tested it on mac, 10.14 and 10.15, both with fresh installation of deno.
@lucacasonato also confirmed that this is reproducible on mac and linux with deno 0.40.0, not 0.39.0.

For demo purpose, I have created 2 branches for this,
`left_pad_fail` for failing and `left_pad_ok` for ok.

```sh
git clone https://github.com/shian15810/denosaur.git
cd denosaur

git checkout left_pad_fail
npm install
deno --allow-read --importmap import_map.json mod.ts # this is failing

git checkout left_pad_ok
deno --allow-read --importmap import_map.json mod.ts # this is ok
```

On branch `left_pad_fail`, deno is stuck at `require('left-pad')` indefinitely. I can only trace it down to this block of code:

https://github.com/denoland/deno/blob/0cf4ac91e6917b76c00d3d4b790e9fefc4dc5323/std/node/module.ts#L653-L658

<details>
  <summary>The debug log before it got stuck:</summary>

```
DEBUG JS - sendSync op_stat 17
⚠️️  Granted read access to "~/denosaur"
op_stat ~/denosaur false
DEBUG JS - sendSync op_stat 17
⚠️️  Granted read access to "~/denosaur/my_mod"
op_stat ~/denosaur/my_mod false
DEBUG JS - sendSync op_stat 17
⚠️️  Granted read access to "~/denosaur/my_mod.js"
op_stat ~/denosaur/my_mod.js false
DEBUG JS - sendSync op_read_link 23
⚠️️  Granted read access to "~/denosaur/my_mod.js"
op_read_link ~/denosaur/my_mod.js
DEBUG JS - sendSync op_open 8
⚠️️  Granted read access to "~/denosaur/package.json"
read rid=3
read rid=3
DEBUG JS - sendSync op_close 62
DEBUG JS - sendSync op_open 8
⚠️️  Granted read access to "~/denosaur/my_mod.js"
read rid=4
read rid=4
DEBUG JS - sendSync op_close 62
DEBUG JS - sendSync op_stat 17
⚠️️  Granted read access to "~/denosaur/node_modules"
op_stat ~/denosaur/node_modules false
DEBUG JS - sendSync op_open 8
⚠️️  Granted read access to "~/denosaur/node_modules/left-pad/package.json"
read rid=5
```
</details>

Adding some `console.log` to this block of code:

```ts
let json: string | undefined;
try {
  console.log('before');
  json = new TextDecoder().decode(
    Deno.readFileSync(path.toNamespacedPath(jsonPath))
  );
  console.log('after');
} catch {
  console.log('catch');
}
```

Only `before` is being printed before it got stuck.

<details>
  <summary>The debug log before it got stuck:</summary>

```
DEBUG JS - sendSync op_stat 17
⚠️️  Granted read access to "~/denosaur"
op_stat ~/denosaur false
DEBUG JS - sendSync op_stat 17
⚠️️  Granted read access to "~/denosaur/my_mod"
op_stat ~/denosaur/my_mod false
DEBUG JS - sendSync op_stat 17
⚠️️  Granted read access to "~/denosaur/my_mod.js"
op_stat ~/denosaur/my_mod.js false
DEBUG JS - sendSync op_read_link 23
⚠️️  Granted read access to "~/denosaur/my_mod.js"
op_read_link ~/denosaur/my_mod.js
before
DEBUG JS - sendSync op_open 8
⚠️️  Granted read access to "~/denosaur/package.json"
read rid=3
read rid=3
DEBUG JS - sendSync op_close 62
after
DEBUG JS - sendSync op_open 8
⚠️️  Granted read access to "~/denosaur/my_mod.js"
read rid=4
read rid=4
DEBUG JS - sendSync op_close 62
DEBUG JS - sendSync op_stat 17
⚠️️  Granted read access to "~/denosaur/node_modules"
op_stat ~/denosaur/node_modules false
before
DEBUG JS - sendSync op_open 8
⚠️️  Granted read access to "~/denosaur/node_modules/left-pad/package.json"
read rid=5
```
</details>

However, on branch `left_pad_ok`, everything is working just fine, with just 4 lines of code difference. You can see the diff here: https://github.com/shian15810/denosaur/compare/left_pad_fail...left_pad_ok

Commenting out these 4 totally unrelated lines, deno didn't get stuck anymore.
It seems like these 4 lines are making `Deno.readFileSync` to fail, but it doesn't make any sense.
If it really did fail, shouldn't it should be handled by the `catch` block?

Is this a bug?

**Comment by lucacasonato** [comment]
I want to add to this that this must have broken after https://github.com/denoland/deno/commit/52c1d308255a16b0cdb396be68f18683ff671329 because a release build from that commit still works.

**Comment by bartlomieju** [comment]
> I want to add to this that this must have broken after [52c1d30](https://github.com/denoland/deno/commit/52c1d308255a16b0cdb396be68f18683ff671329) because a release build from that commit still works.

I doubt 52c1d30 broke it, my bet is the same problem as in #4577 - ie. `futures::executor::block_on` used in `readSync` op doesn't play nicely with cooperative yielding introduced in Tokio 0.2.16

**Comment by lucacasonato** [comment]
Sorry I meant to say it broke in a commit some time after that one. I just know it still worked with that one because it was in my path for the last few days.

**Comment by srackham** [comment]
I am experiencing the same problem (Ubuntu 18.04).
After around 10 successive calls to `readFileSync` the example `hang-readfilesync.ts` script hangs:

```
$ deno --version
deno 0.40.0
v8 8.2.308
typescript 3.8.3

$ cat hang-readfilesync.ts
for (let i = 0; i < 20; i++) {
  let content = Deno.readFileSync("TODO.md");
}

$ deno -A -L debug hang-readfilesync.ts
  :
  :
  :
  :
⚠️️  Granted read access to "/home/srackham/local/projects/drake/tmp/TODO.md"
read rid=8
read rid=8
read rid=8
read rid=8
read rid=8
read rid=8
DEBUG JS - sendSync op_close 62
DEBUG JS - sendSync op_open 8
⚠️️  Granted read access to "/home/srackham/local/projects/drake/tmp/TODO.md"
read rid=9
read rid=9
read rid=9
read rid=9
read rid=9
read rid=9
DEBUG JS - sendSync op_close 62
DEBUG JS - sendSync op_open 8
⚠️️  Granted read access to "/home/srackham/local/projects/drake/tmp/TODO.md"
read rid=10
read rid=10
read rid=10
read rid=10
read rid=10
read rid=10
DEBUG JS - sendSync op_close 62
DEBUG JS - sendSync op_open 8
⚠️️  Granted read access to "/home/srackham/local/projects/drake/tmp/TODO.md"
```

At this point the script hangs with 100% CPU utilisation.
