### ISSUE TITLE
Cached code in .deno/gen should only be valid for a specific build of Deno

### ISSUE THREAD

**Issue by ry** [denoland/deno#472]
That is, somehow we need a "build id" or "version" in Deno and it needs to be passed to this function:

https://github.com/denoland/deno/blob/b8e0ce4d1673ccfe862f82b94be354e8f5d3bb2e/src/deno_dir.rs#L56-L64

The reason for this is that different builds of deno can have different outputs - and it's confusing if output corresponding to a different build is used.

**Comment by bartlomieju** [comment]
I think I could help out with that, but it would be great to have a few hints.

1. How should `build_id` or `version` be specified? AFAICT it is not version of Deno itself but rather a unique identifier for single build, so it probably would make sense for it to be some hash based on current repo contents.
2. What should happen to old cached files?

**Comment by bartlomieju** [comment]
I think those issues have already been addressed with latest compiler tweaks?

**Comment by ry** [comment]
Not yet. But I've just fixed it in #1751.
