### ISSUE TITLE
Error stack in worker missing

### ISSUE THREAD

**Issue by Fenzland** [denoland/deno#4728]
Currently, every error thrown in worker has no trusted stacks, but only
```
at WorkerImpl.#poll ($deno$/web/workers.ts:140:17)
```

**Comment by dkuroi** [comment]
```
error: Uncaught Error: Cannot resolve module "file:///C:/Users/hp/workspaces/stack-DORM-boilerplate/backend/writeWorker.ts"
    at WorkerImpl.#poll ($deno$/web/workers.ts:198:17```

**Comment by bartlomieju** [comment]
@nayeemrmn could you look into this issue? It would require to serialize the error in Rust, forward it to JS (worker host) and then properly reconstruct it

**Comment by nayeemrmn** [comment]
Based on browser behaviour, the worker should print errors to the terminal on its own. The parent worker is only made aware of the error if the user sets an error event listener on the worker object. I'll see what I can do.

**Comment by bartlomieju** [comment]
> Based on browser behaviour, the worker should print errors to the terminal on its own. The parent worker is only made aware of the error if the user sets an error event listener on the worker object. I'll see what I can do.

@nayeemrmn I think that's what happenning right now - if there's no error listener in the host then error is rethrown in host context. Thanks for looking into this 🙏

**Comment by bartlomieju** [comment]
@nayeemrmn I think that's not entirely correct - [according to spec](https://html.spec.whatwg.org/multipage/workers.html#runtime-script-errors-2) if there's no error handler attached to `Worker` then error should be propagated to the scope the worker was defined in - so send `error` event to the `window`

**Comment by nayeemrmn** [comment]
It seems the _event_ should travel upwards, but I'm saying only the source Worker where the error occurred needs to be responsible for printing the genuine error stack (if it doesn't have a handler itself).

I'm proposing that if the source worker has its own error handler which prevents default, nothing is printed. If it doesn't, it prints the error stack to stdout and propagates an event error upwards. If the event error reaches the main worker without being handled, we would just let it error out in `Worker.#poll()` like it does now and cause termination.
