### ISSUE TITLE
eval function seems to be not working as expected

### ISSUE THREAD

**Issue by anuragvohraec** [denoland/deno#4731]
Hi Team,

I was trying to test eval function.

Here is my code for that:
```javascript
let user= {name: 'Anurag'};
eval(`
function say_hello(user){
    console.log("hello", user);
}
`);

eval(`say_hello("${user.name}")`);//this one works in browser
say_hello("Another_user"); //this one will work too in browser
```
If I run this code in browser [tested in chrome], it works perfectly fine. And prints out "hello Anurag"
However if I run this in deno, it gives error:
`error: Uncaught ReferenceError: say_hello is not defined`

Is this deviation from browser is expected feature or this is a valid bug ? 
[Runtime code compilation is an amazing feature, please don't drop it.]

**Comment by kevinkassimo** [comment]
This is not an issue with Deno. This is due to Deno uses ES modules only, and ES module implicitly enables strict mode, and [`eval` of strict mode code does not introduce new variables into the surrounding scope.](http://whereswalden.com/2011/01/10/new-es5-strict-mode-support-new-vars-created-by-strict-mode-eval-code-are-local-to-that-code-only/)

**Comment by anuragvohraec** [comment]
> This is not an issue with Deno. This is due to Deno uses ES modules only, and ES module implicitly enables strict mode, and [`eval` of strict mode code does not introduce new variables into the surrounding scope.](http://whereswalden.com/2011/01/10/new-es5-strict-mode-support-new-vars-created-by-strict-mode-eval-code-are-local-to-that-code-only/)

is there any way to bypass that ?

**Comment by anuragvohraec** [comment]
Ok the closest way we can bypass the eval is see this example:
```js
let a ={};
eval('a.x=5;');
console.log(a); //will print {x:5} on console
```
So we created a dummy varibale "a" for maintaining scope for eval function.
This will serve as a refernce for people who may face similar problem.
