### ISSUE TITLE
Deno.compile caching/cache-busting not behaving as expected

### ISSUE THREAD

**Issue by jakajancar** [denoland/deno#4743]
**test.ts**
```
console.log('Hello')
```

**main.ts**
```
setInterval(async () => {
    const start = +new Date
    const [ diagnostics, emitMap ] = await Deno.compile('./test.ts')
    console.log(`Took ${+new Date - start} ms to compile`)
    console.log(emitMap)
}, 1000)
```

**deno main.ts output**
```
Took 357 ms to compile
{
 file:///Users/jaka/Desktop/deno-compile-caching/test.js.map: "{\"version\":3,\"file\":\"test.js\",\"sourceRoot\":\"\",\"sources\":[\"test.ts\"],\"names\":[],\"mappings\":\";AAAA,OAA...",
 file:///Users/jaka/Desktop/deno-compile-caching/test.js: "\"use strict\";\nconsole.log('Hello');\n//# sourceMappingURL=test.js.map"
}
[... identical output infinitely ...]
```

The `Deno.compile()` always takes 300ms+ and the output does not change even if `test.ts` is changed while the script is running. Curiously, mtime of `test{.ts.js,.ts.js.map,.meta}` in the cache directory are changing.

Expected:
  - When not changed: returns instantly, does not change files cache
  - When changed: takes a while, picks up changes, changes files in cache

Actual:
  - When not changed: takes a while, changes files in cache
  - When changed: takes a while, does not pick up changes, changes files in cache

deno 0.40.0

**Comment by bartlomieju** [comment]
Most likely caused by caching in `SourceFileFetcher` and/or caching in `TsCompiler`. Both of them have a hashmap with already loaded files.

**Comment by kitsonk** [comment]
This is still present in 1.5.2... it is due to the FileFetch in memory cache not reloading the source, like a few other issues.
