### ISSUE TITLE
There are two independent Body classes

### ISSUE THREAD

**Issue by ry** [denoland/deno#4748]
https://github.com/denoland/deno/blob/cb5dd69dda4872533b05a4e9184f7e35f21c2010/cli/js/web/body.ts#L120
https://github.com/denoland/deno/blob/cb5dd69dda4872533b05a4e9184f7e35f21c2010/cli/js/web/fetch.ts#L31

I don't know how it got this way, but it needs to be fixed.

It's not even clear to me that we need an actual runtime Body object. It's not something in the DOM. It's more of an internal interface to describe Request and Response. Likely there should be zero "class Body" in our code.

**Comment by kitsonk** [comment]
Correct, according to the spec, it is just a logical interface.  It shouldn't exist as a thing.  Looking at the current implementation though, it is going to be a bit of a challenge to unpick.

As I mentioned directly Ry, I am doing a re-write of the streams.  Once that is done, it feels like this needs a good hose-down as well.

**Comment by bartlomieju** [comment]
Fixed in #6793
