### ISSUE TITLE
inlineSourceMap, and inlineSources

### ISSUE THREAD

**Issue by jakajancar** [denoland/deno#4765]
I don't understand these two properties.

`inlineSourceMap` - Emit a single file with source maps instead of having a separate file.

OK...

`inlineSources` - Emit the source alongside the source maps within a single file

Isn't this saying the same thing?

And if I try to set both to `true` (when using `Deno.bundle`), even though `inlineSources` documentation says "requires inlineSourceMap or sourceMap to be set", I get:

> Option 'inlineSources can only be used when either option '--inlineSourceMap' or option '--sourceMap' is provided

**Comment by kitsonk** [comment]
These are just TypeScript compiler options. They aren't specific to Deno. See: https://www.typescriptlang.org/docs/handbook/compiler-options.html

But to explain, `inlineSources` embeds the original source content in the source maps, which is good when you when you want to see the source code and it isn't available at runtime where as `inlineSourceMap` embeds the source maps in the emitted file.

**Comment by jakajancar** [comment]
Are these supposed to work with `Deno.bundle()`? I'm not seeing any source maps.

**Comment by kitsonk** [comment]
Both `deno bundle` and `Deno.bundle()` do not currently support emitting accurate source maps (covered by #4549, it doesn't have a independent issue ATM), so they are turned off.  It has to do with that the source map produced by the TypeScript compiler doesn't account for the bundle loader code and needs to be remapped.

**Comment by jakajancar** [comment]
Got it, thanks!
