### ISSUE TITLE
base64 to/from Uint8Array

### ISSUE THREAD

**Issue by pgg** [denoland/deno#4794]
add deno/std/encoding/base64 support to/from Uint8Array

**Comment by crabmusket** [comment]
For reference: https://deno.land/x/base64/

**Comment by pgg** [comment]
Why does the current base64 implementation expose to/from ArrayBuffer and not Uint8Array like all the other encodings?

**Comment by ry** [comment]
@pgg Likely just an oversight...

**Comment by timonson** [comment]
I would like to mention the following issue here: https://github.com/denoland/deno/issues/6094

I wrote the following in the discord channel but didn't get a reply, so I try it again:

> Hi @kitsonk and the other devs, I would like to fix the base64 module based on this issue: https://github.com/denoland/deno/issues/6094. I would also improve the tests and other things.
> I have two questions:
> 1. Do you prefer Kitson's suggestion or a more low level alternative?
> 2. The base64 module now takes the type string | ArrayBuffer as argument, do you want to keep this?
> Thanks!
