### ISSUE TITLE
Is there a way to specify the compiler (CC/CXX) to use when building deno?

### ISSUE THREAD

**Issue by everestmz** [denoland/deno#480]
I may have missed some flags somewhere, but I can't seem to find any mention of how to specify that. Is there currently a way to do this?

**Comment by ry** [comment]
We use Chrome's build system - and they ship their own clang binaries. 
It's possible to use other compilers but I haven't tried it. See docs here https://chromium.googlesource.com/chromium/src/+/lkgr/docs/clang.md
