### ISSUE TITLE
q: how can this be a typescript runtime when typescript is first compiled to javascript ?

### ISSUE THREAD

**Issue by mobop** [denoland/deno#4800]

**Comment by nayeemrmn** [comment]
Please ask questions like this in the Discord server https://discordapp.com/invite/TGMHGv6.

**Comment by mobop** [comment]
explanation for this question should be on the wiki page. 
and i don't use discord , it ask me to give it my phone number

**Comment by kitsonk** [comment]
Why? It is an illogical question, so no need to add it to a wiki page.

**Comment by mobop** [comment]
why it is an illogical question? 
please explain?

**Comment by nayeemrmn** [comment]
> why it is an illogical question?

Well, if you're asking how it runs TypeScript then you've answered your own question: by compiling to JavaScript first. This is a given and ideally an implementation detail, no need to be directly written anywhere.

**Comment by shian15810** [comment]
https://en.m.wikipedia.org/wiki/TypeScript

> TypeScript is a strict syntactical superset of JavaScript, and adds optional static typing to the language.

**Comment by mobop** [comment]
@nayeemrmn i know how deno compile ts to js. i have read it.
my question is, when js is the thing that actually runs, how can it be ts runtime.

**Comment by mobop** [comment]
@shian15810 i know what ts is.

**Comment by crowlKats** [comment]
it's a TS runtime because it can "run" TS code without the user having to do some conversion manually (the case with node)...

**Comment by nayeemrmn** [comment]
> @nayeemrmn i know how deno compile ts to js. i have read it.
> my question is, when js is the thing that actually runs, how can it be a ts runtime.

@mobop That's why I pointed out that the compilation is basically an implementation detail, making it a TS runtime as far as you're concerned.

Did you open this to point out a technicality? What exactly did you want written in the wiki? 🙄

**Comment by kitsonk** [comment]
JS doesn't really run either.  It is compiled into op codes in V8. 🤷 Again, what would you expect a wiki to say?

**Comment by mobop** [comment]
@kitsonk , 
how deno is a typescript runtime?
does typescript's type information passed to V8?
does deno use vanilla v8 or it modified v8 to make it a typescript engine?

**Comment by mobop** [comment]
@nayeermn 
>Did you open this to point out a technicality? What exactly did you want written in the wiki?

yes, for technical details. 
an explanation in the wiki on this topic.

**Comment by lucacasonato** [comment]
No Deno does not pass typings into v8. It is raw JS.

V8 is not a Typescript engine because it can not deal with Typescript files. Deno is on the other hand because it can deal with typescript files. How this is implemented under the hood is completly irrelevant and the user should not care. A runtime is just a bit of software that is able to take in some data and execute it through some way. That is exactly what Deno does with Typescript.

**Comment by mobop** [comment]
@lucacasonato 
>How this is implemented under the hood is completly irrelevant and the user should not care.

what are you talking about? This is not a proprietary software. Why i shouldn't care about it's implementation details.

this is not a good mins set.

**Comment by mobop** [comment]
@ry

**Comment by kitsonk** [comment]
You are right, it isn't proprietary software.  The source code is there if you are curious.  @lucacasonato point is that from an end-user perspective, the implementation doesn't matter.  Deno consumes TypeScript files and runs them without any external libraries or modules.  Therefore it is a TypeScript runtime.

Understanding how a combustion engine works is not a requirement to know how to drive a car.

**Comment by mobop** [comment]
>Understanding how a combustion engine works is not a requirement to know how to drive a car.

many of us  might want to know. Because they are curious.

**Comment by crowlKats** [comment]
the combustion engine is displayed for everyone to see

**Comment by kitsonk** [comment]
And there are some excellent presentations on the internals of Deno. Right now Deno is in flux so some of them are quite dated, but a deep dive in the internals of Deno is likely not part of the end user documentation.

**Comment by mobop** [comment]
@kitsonk , i understand.
but for people who want to know the internal architectural details.

**Comment by kitsonk** [comment]
Again, at the risk of repeating itself, that is a wider community task.

**Comment by mobop** [comment]
how the community will know if the implementors don't documents it

**Comment by kitsonk** [comment]
> how the community will know if the implementors don't documents it

The implementors are part of the community.  And the documentation is called source code.  Ry, myself, Kevin, Bartek and Bert have all given public talks which touch on the internals in several aspects.  I am sure there are others.  Kevin has a great blog post, though it is outdated and he doesn't want to refresh it until 1.0 ships, which makes total sense.

This is not the forum to get up to speed on the internals of Deno, or debating why the internals aren't on a wiki, nor is it the forum for asking a single line topic question.

**Comment by mobop** [comment]
@kitsonk , thank you. 
I apology for wasting you and others time.
