### ISSUE TITLE
store cache files in  recommended  standard location

### ISSUE THREAD

**Issue by abdulkareemnalband** [denoland/deno#481]
I'm psyched about deno
I like decentralized library , sandbox by default

Just some nitpick

Instead of polluting home directory with `~/.deno`

Use [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-0.6.html) for linux

Use Mac OS specific locations https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/MacOSXDirectories/MacOSXDirectories.html#//apple_ref/doc/uid/TP40010672-CH10-SW1

**Comment by KeKsBoTer** [comment]
IMO for windows you should use  `%localappdata%/deno` as cache directory.

**Comment by flying-sheep** [comment]
We should use the [directories](https://crates.io/crates/directories) crate

**Comment by bartlomieju** [comment]
You can control location of deno directory with `DENO_DIR`. Check out [this article](https://denolib.gitbook.io/guide/advanced/deno_dir-code-fetch-and-cache#deno_dir-structure) for more info.

CC @ry

**Comment by abdulkareemnalband** [comment]
@bartlomieju It's not about configuring ENVIRONMENT , but playing nicely with current conventions

**Comment by flying-sheep** [comment]
That, and `DENO_DIR` sounds like it’s not exclusively for caches. If deno at some point does something else with it than storing its history and cache files in it, it won’t be sufficient anymore, as `XDG_CACHE_HOME` needs to be different from e.g. `XDG_CONFIG_HOME`
