### ISSUE TITLE
ServerRequest method should be an Typescript "enum"

### ISSUE THREAD

**Issue by Caesar2011** [denoland/deno#4813]
I suggest to change the declaration of the `method` field from `string` to `"GET" | "HEAD" | "POST" | "PUT" | "DELETE" | "CONNECT" | "OPTIONS" | "TRACE" | "PATCH"` in the file "https://deno.land/std@v0.41.0/http/server.ts". This makes switch statements easier and everything more fail-proof. Probably we should implement a type alias.

```ts
export class ServerRequest {
  url!: string;
  method!: "GET" | "HEAD" | "POST" | "PUT" | "DELETE" | "CONNECT" | "OPTIONS" | "TRACE" | "PATCH";
  proto!: string;
  protoMinor!: number;
  protoMajor!: number;
  headers!: Headers;

  ...
}
```

According to the following list:
[mozilla.org - HTTP request methods](https://developer.mozilla.org/de/docs/Web/HTTP/Methods)

**Comment by KSXGitHub** [comment]
Does HTTP standard forbid inventing new method?

**Comment by kitsonk** [comment]
Correct, and some servers implement non-standard ones.  We should not forbid non-standard HTTP methods.  String literals can help, but we can't limit them.

**Comment by Caesar2011** [comment]
Well, I is quite ugly and Node doesn't seem to support custom HTTP verbs either, but I guess you are right and we should be better. Let's keep it as it is 😭..

**Comment by nayeemrmn** [comment]
> EDIT: What about the following?
> 
> `"GET" | "HEAD" | "POST" | "PUT" | "DELETE" | "CONNECT" | "OPTIONS" | "TRACE" | "PATCH" | string`

Well that won't do anything. TS naturally resolves this to `string` even in intellisense.
