### ISSUE TITLE
Antivirus Software picks up deno.exe as Malware

### ISSUE THREAD

**Issue by AxDSan** [denoland/deno#4820]
![](https://i.imgur.com/MZDKzp3.png)

**Comment by ry** [comment]
Likely a false positive. But I see that it's a chocolatey binary - which we do not produce. To install binaries generated by us use this powershell command 
```
iwr https://deno.land/x/install/install.ps1 -useb | iex
```
or download the exe manually from https://github.com/denoland/deno/releases

I'd be interested if you get warnings on the official binaries.

**Comment by AxDSan** [comment]
Thank you so much!! 🎉

**Comment by AxDSan** [comment]
No issues whatsoever with the official binaries! thanks!
