### ISSUE TITLE
Source line formatting in errors looks bad

### ISSUE THREAD

**Issue by nayeemrmn** [denoland/deno#4822]
~~Good first issue.~~
```ts
throw new Error("abcd");
```
gives the output

<img src="https://user-images.githubusercontent.com/29990554/79696348-0d596100-8274-11ea-8afc-1f55ab2fb5e1.png" width = 420></img>

That second line, the "source name" is always the same as the first frame. The line number is written in three places and one of them is invisible here.

I'd rather see something like this:

<img src="https://user-images.githubusercontent.com/29990554/79696430-9cff0f80-8274-11ea-92d1-e4acbfe8d9e2.png" width = 420></img>

**Comment by ry** [comment]
I agree. Not sure if this is such a good first issue tho - there is a ton of clean up that can happen in the formatting of errors/diagnostics. There's a lot of duplicated code between the two. For example these two bits of formatting could probably be shared:

https://github.com/denoland/deno/blob/v0.41.0/cli/diagnostics.rs#L223-L228

https://github.com/denoland/deno/blob/v0.41.0/cli/fmt_errors.rs#L178-L184
