### ISSUE TITLE
`Bad resource ID` when awaiting a promise inside a `for await` loop over `fsEvents`.

### ISSUE THREAD

**Issue by samuelgozi** [denoland/deno#4830]
I'm running Deno v0.41.0.
The title probably doesn't describe the issue correctly, sorry about that.
I don't really know the reason for this bug, but the `Promise` inside the `runApp` function in the code below breaks the app. The error thrown is `error: Uncaught BadResource: Bad resource ID`.

The code listens for changes in a directory and re-runs a Deno app (with 2 seconds throttle).

```js
const throttle = 2000;
const args = ['--allow-net'];
let app;
let appInitTime;

async function runApp() {
	app && app.close();

	await new Promise(resolve => setTimeout(resolve, 1000)); // This line breaks the code.

	appInitTime = Date.now();

	app = Deno.run({ cmd: ['deno', ...args, 'src/main.js'] });
}

runApp();

for await (const _ of Deno.fsEvents('src')) {
	if (Date.now() - appInitTime < throttle) continue;
	runApp();
}
```

**Comment by Caesar2011** [comment]
Were able to reprduce it. The problem occures in line `app && app.close();` not within Promise.

**Comment by samuelgozi** [comment]
If you remove the promise, everything works.

**Comment by Caesar2011** [comment]
The program breaks because for await is called multiple times. Either you remove the 1000ms timeout or you make `runApp()` await. If you leave it as it is, the program gets closed and waits 1 second. Then the program gets closed a secound time. Only then, after the program has already crashed, would the first call set `app` again.

```
const throttle = 2000;
const args = ['--allow-net=127.0.0.1'];
let app: any|null = null;
let appInitTime: number = 0;

async function runApp() {
	app && app.close();

	await new Promise(resolve => setTimeout(resolve, 1000)); // This line breaks the code.

	appInitTime = Date.now();

	app = Deno.run({ cmd: ['deno', ...args, 'example.ts'] });
}

runApp();

for await (const _ of Deno.fsEvents('.')) {
  if (Date.now() - appInitTime < throttle) continue;
	await runApp();
}
```

or

```
const throttle = 2000;
const args = ['--allow-net=127.0.0.1'];
let app: any|null = null;
let appInitTime: number = 0;

async function runApp() {
	app && app.close();

	await new Promise(resolve => setTimeout(resolve, 1000)); // This line breaks the code.

	appInitTime = Date.now();

	app = Deno.run({ cmd: ['deno', ...args, 'example.ts'] });
}

runApp();

for await (const _ of Deno.fsEvents('.')) {
  if (Date.now() - appInitTime < throttle) continue;
	await runApp();
}
```

**Comment by samuelgozi** [comment]
@Caesar2011 So basically the `for while`  continues to run the next event, which in turn calls `runApp` again, which then tries to close an already closed process...

But the thing is that the error is thrown even after waiting a few seconds before making a change in `src` directory.

But I guess that might due to an error in my code...

Anyways, thank you very much for your help!

**Comment by Caesar2011** [comment]
> @Caesar2011 So basically the `for while` continues to run the next event, which in turn calls `runApp` again, which then tries to close an already closed process...
> 
> But the thing is that the error is thrown even after waiting a few seconds before making a change in `src` directory.
> 
> But I guess that might due to an error in my code...
> 
> Anyways, thank you very much for your help!

**Comment by Caesar2011** [comment]
Published a working version in this repo.

https://github.com/Caesar2011/rhinoder

**Comment by samuelgozi** [comment]
> During my testing it occurred immediately. :D Your code will also be executed on file access! Maybe your file editor triggers it.

That explains a lot... It's my first time writing something that works with the filesystem events...

> Published a working version in this repo.
> 
> https://github.com/Caesar2011/rhinoder

Cool. I'm not proficient with typescript, but maybe ill do a pull request with some nice features if that is okay.

**Comment by Caesar2011** [comment]
Sure!

**Comment by ValentinBossi** [comment]
from the doc:

deno --allow-read https://deno.land/std/examples/cat.ts /etc/passwd

also produces a "Bad resource ID"

**Comment by KTibow** [comment]
I'm getting this when trying to use Playwright
