### ISSUE TITLE
Allow Reading in Module's Own Directory

### ISSUE THREAD

**Issue by tubbo** [denoland/deno#4839]
When running `deno install your-binary https://url.to/your/module.js`, if that module includes code for reading files out of the filesystem, you'll need to `--allow-read`. This is awesome, but it sometimes feels a little too strict. For example, creating a CLI that generates code is somewhat challenging given this restriction. You must tell the end user to `--allow-read` for the entire filesystem, which doesn't really make sense if your module is only reading files that it came with. It seems like this permission is too broad. Ideally, I'd like to make it so the CLI tool can only read from its own directory, but that may change for other Deno users and furthermore, it seems like the dependencies directory is _every_ module Deno downloaded, so I'd have to allow access to that whole directory, which doesn't seem very secure and furthermore might not be the same path on different OSes.

Is there any way to potentially allow reading files that are located within the module's own directory without needing to ask the user for permission? Perhaps a switch would still need to be activated, like `--allow-internal-read` or something, so the user knows that the tool is still reading from the filesystem, but I suppose it could be automatic as well. I feel like if your module is a CLI that needs text files (like `.ejs` templates) which it itself downloaded onto the filesystem, it shouldn't need permission to read those files.

**Comment by crowlKats** [comment]
`--allow-read="."` will only allow to read the content of the current dir

**Comment by tubbo** [comment]
That’s true, but I don’t always know the directory Deno is installing my module to, right? Can I do something like `—allow-read=$DENOPATH/path/to/my/module`?

**Comment by Caesar2011** [comment]
So the question it whether `--allow-read="."` is relative to the entry script or relative to the current work dir? Or why do you think `--allow-read=.` is not sufficient?

**Comment by tubbo** [comment]
I think I was more unsure of how `--allow-read=.` worked. I assumed it was taking on `.` from the shell, that is, the current working directory. But it seems to be whatever the current directory is of the script that it's running, so for example if I run `cli` in `/home/tubbo` and the CLI code is located in `/projects/cli`, then it's capable of reading everything in `/projects/cli`, not `/home/tubbo`.

**Comment by Caesar2011** [comment]
@tubbo Is the issue solved and can be closed?

**Comment by tubbo** [comment]
@Caesar2011 yeah I think I was just confused about what `.` meant...
