### ISSUE TITLE
Remove dependency on winapi-0.2.x

### ISSUE THREAD

**Issue by piscisaureus** [denoland/deno#484]
Currently the rust crates 'mio', 'miow' and 'iovec' depend on an old version of the winapi crate.
Hence we bundle two versions of winapi, which is undesirable.

Find a way to remove the dependency on winapi-0.2.x
When this is is done, the 'kernel32' and 'ws2_32' crates can also be removed.

**Comment by ry** [comment]
Feb 24, 2020: Still an issue

**Comment by kitsonk** [comment]
`errno` depends on winapi-0.2.x now
`mio` 0.7.x depends on winapi-0.3.x, but mio-extras, mio-named-pipes, mio-uds, notify, tokio all depend on mio-0.6.
`miow` 0.3.x depends on winapi-0.3.x, but miow-0.2.x is required by mio-0.6.x

`iovec` no longer depends on winapi at all

gotta love transitive dependencies...
