### ISSUE TITLE
How to get file content through FileInfo?

### ISSUE THREAD

**Issue by asins** [denoland/deno#4843]
In the current version, the path attribute has been removed from the `FileInfo` object, so the question is, how to get the actual file content from the `FileInfo` data returned by `readDir` and other methods?

such as:
```ts
const files = Deno.readdirSync('./');
Array.from(files).forEach((fileInfo: Deno.FileInfo) => {
  // The readFile interface only accepts file path parameters
  // how do I provide file path information ????
  const data = await Deno.readFile(fileInfo.path); 
  const decoder = new TextDecoder('utf-8');
  const text = decoder.decode(data);
  console.log(text );
});

```

**Comment by SyrupThinker** [comment]
[`readdirSync` returns a `DirEntry`](https://doc.deno.land/https/github.com/denoland/deno/releases/latest/download/lib.deno.d.ts#Deno.readdirSync) that contains the name, joining the `readdirSync` path and name gives you the full path.

**Comment by ry** [comment]
As @SyrupThinker has said. Sometimes it's better to try to demo code in JS first
```
const files = Deno.readdirSync('.');
Array.from(files).forEach((f) => {
  console.log("f", f);
});
```

**Comment by asins** [comment]
Okay, if you see the std information on the website, you can accept the complete path by yourself.

```javascript
import { resolve } from "https://deno.land/std/path/mod.ts";
const files = Deno.readdirSync('./');

Array.from(files).forEach(file => {
  const fileName = file.name;
  const path: string = resolve(dirPath, file.name);
  const data = await Deno.readFile(path); 
  const decoder = new TextDecoder('utf-8');
  const text = decoder.decode(data);
  console.log(text );
});
```
