### ISSUE TITLE
Strip comments from inlined assets

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#486]
The inlined `.d.ts` files contain a lot of JSDoc comments that enrich the IDE experience but are totally useless in the runtime. These should be stripped out during the build process. I have an idea on how to do this.

**Comment by ry** [comment]
Yeah - sounds good

**Comment by Pato91** [comment]
A while back I was looking into that and I also do not know how to do it but there was an interesting conversation that caught my eye in the [TypesScript issues particulary issue 2,705](https://github.com/Microsoft/TypeScript/issues/14619) that seem to suggest that we either have the JSDoc comments or not but all in all it seems that we disable this within the TypeScript compiler by enabling the 

> `removeComments`
compile option in the tsconfig.js file

But all in all, there are interesting conversations going about on this within the typescript issues panel.

**Comment by kitsonk** [comment]
The challenge is that these are not transpiled files, they are existing declaration files, so they need to be passed and their "triva" removed.

**Comment by bartlomieju** [comment]
@kitsonk is this issue still relevant?

**Comment by kitsonk** [comment]
Still relevant, just my initial attempt didn't go so well. It extra binary weight we don't need.

**Comment by kitsonk** [comment]
It isn't straight forward and I think we can worry about it some other time.
