### ISSUE TITLE
Replace `Response` with a `ServerResponse` constructor in the HTTP module

### ISSUE THREAD

**Issue by samuelgozi** [denoland/deno#4861]
Hi, I have a suggestion that I think can simplify some common patterns when creating HTTP servers.

Right now if you want to respond to a `ServerRequest`, you have to use the `respond()` method, and pass it an object that adheres to the `Response` interface.

It is very common to want to create a `Response` object and pass it around for further manipulation before finally using it, that is why the FetchAPI has a `Response` class.

I think that replacing the `Response` interface with a `ServerResponse` class can help make the HTTP Server API more versatile and it will not clash with the FetchAPI `Request` class anymore.

I think that the defaults for that the `ServerResponse` class should be:
```ts
class ServerResponse {
  status = 200;
  headers = new Headers();
} 
```

In my opinion, the default status code should be `200` like in Django, Hyper, and Go as opposed to `302` in Express(which makes no sense).

If accepted I can try to submit a pull request myself.

**Comment by ry** [comment]
@samuelgozi Ok, sounds good to me.

**Comment by samuelgozi** [comment]
K then, I'll start working on this.

**Comment by jakajancar** [comment]
The nicest thing about this is that it removes the need to check `if (res.headers)`. You can count on `Headers` being there now.
