### ISSUE TITLE
Request: deno fmt --check should show diff

### ISSUE THREAD

**Issue by KSXGitHub** [denoland/deno#4863]
`deno fmt --check` should print differences between pre-format content and post-format content.

**Comment by Skillz4Killz** [comment]
This would 100% help solve the issue of not knowing which files are causing the Github Action to fail. 
![image](https://user-images.githubusercontent.com/23035000/82227851-509c0380-98f6-11ea-908a-a7a8f8e9da64.png)

**Comment by alisabzevari** [comment]
Should this be closed?
