### ISSUE TITLE
Write docs for Workers

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#4868]

**Comment by johningle** [comment]
@bartlomieju I see no pull request associated with the closure of this issue. Could you note the location of this documentation? Is the manual chapter found here the only documentation? https://deno.land/manual/runtime/workers

**Comment by bartlomieju** [comment]
> @bartlomieju I see no pull request associated with the closure of this issue. Could you note the location of this documentation? Is the manual chapter found here the only documentation? https://deno.land/manual/runtime/workers

@johningle that's right, that's the only documentation at the moment
