### ISSUE TITLE
Property 'iter' does not exist on type 'typeof Deno'.

### ISSUE THREAD

**Issue by CedricMeu** [denoland/deno#4880]
> deno v0.41.0
> v8 v8.2.308
> typescript v3.8.3

```
error TS2339: Property 'iter' does not exist on type 'typeof Deno'.

► https://deno.land/std/http/io.ts:167:34

167   for await (const chunk of Deno.iter(
```

My program ran perfectly until i restarted using the `--reload` flag. This error is thrown when using `https://deno.land/std/http/server.ts`.

**Comment by SyrupThinker** [comment]
You should add the std library version to ensure compatibility with your Deno version, currently you are using the master branch:
`https://deno.land/std@v0.41.0/http/server.ts`
