### ISSUE TITLE
discussion: --allow-exists permission

### ISSUE THREAD

**Issue by nayeemrmn** [denoland/deno#4895]
For read and write perms, we currently have that:
- `{ name: "read", path: "<path>"}` implies `{ name: "read", path: "child of <path>"}`
- `{ name: "write", path: "<path>"}` implies `{ name: "write", path: "child of <path>"}`

I propose having an "exists" perm which adds that:
- `{ name: "read", path: "<path>"}` implies `{ name: "exists", path: "<path>"}`
- `{ name: "write", path: "<path>"}` implies `{ name: "exists", path: "<path>"}`
- **`{ name: "exists", path: "<path>"}` implies `{ name: "exists", path: "parent of <path>"}`**

`{ name: "exists", path: "<path>"}` is required by:
- `Deno.cwd()` when `<path>` is the CWD
- `Deno.chdir("<path>")`
- `Deno.execPath()` when `<path>` is the executable path

<hr>

Justifications:
1. It formalises the logical overlap between the read and write perms. It documents the possibly unintended consequence of the write perm.
2. The natural property that the "exists" perm propagates upwards instead of downwards applies to no other permission.
3. The ops listed above are examples of those which only need this permission. Read is unnecessarily powerful.

**Comment by bartlomieju** [comment]
I'm not really in favor of adding new permission flag - I think we could use `--allow-env` for this purpose.

**Comment by nayeemrmn** [comment]
I can see `--allow-env` being nicely used to refer to "shell"-ish features like checking and navigating the cwd and reading environment variables. I thought the same thing before. But how would whitelisting work? Is it granular enough? I don't think it communicates the consequence of being able to sniff around for files.

This isn't just to give some permission to `Deno.cwd()` and `Deno.chdir()`, `--allow-exists` is the logical overlap between `--allow-read` and `--allow-write`. It needs to be extracted and formalised either way, honestly.

We need to consider all future ops that don't do any reading or writing, and aren't as nicely associated with the env. It's not uncommon for something to check the existence of a file. It's a unique permission.

**Comment by dubiousjim** [comment]
I think #4423 is worrying about some of the same issues.

**Comment by nayeemrmn** [comment]
I think a lot of the purpose expressed here was addressed by `check_read_blind()` in #5642... or at least it's made this more complicated. Closing.
