### ISSUE TITLE
copyN in std/io/ioutil.ts should be (src, dst) rather than (dst, src) to match Deno.copy

### ISSUE THREAD

**Issue by ry** [denoland/deno#4896]
We recently changed the order of the arguments 
https://github.com/denoland/deno/commit/0cb1bb98cc2de8dfe51b7adbe992666936146c90

copyN (and potentially other functions) should use the same convention.

This may effect #4865 if it's done before that lands.

**Comment by humancalico** [comment]
I'll do it

**Comment by trivikr** [comment]
Closed in https://github.com/denoland/deno/pull/4900
