### ISSUE TITLE
Question: What is node's Buffer.from equivalent in deno?

### ISSUE THREAD

**Issue by erfanium** [denoland/deno#4897]
I'm trying to convert HexString to Buffer. Do I have to write convert function myself?

Deno version: 0.35.0

**Comment by lucacasonato** [comment]
These types of questions are better suited for [Discord](https://discord.gg/TGMHGv6).

Deno doesn't have Buffer, only Uint8Array. A possible solution would be: 
```ts
const fromHexString = hexString =>
  new Uint8Array(hexString.match(/.{1,2}/g).map(byte => parseInt(byte, 16)));
```
from https://stackoverflow.com/questions/38987784/how-to-convert-a-hexadecimal-string-to-uint8array-and-back-in-javascript
