### ISSUE TITLE
lib.globals.d.ts seems redundant - remove

### ISSUE THREAD

**Issue by ry** [denoland/deno#493]
https://github.com/denoland/deno/blob/0e96125260f2d78718e57cac95c7dc672bb24e57/js/lib.globals.d.ts

**Comment by kitsonk** [comment]
I think there is a way to remove `lib.globals.d.ts` as well improve the way to maintain `global.ts` so that any of its exports become part of the global scope both from a runtime but also TypeScript view of the world.

**Comment by kitsonk** [comment]
Without modifying `globals.d.ts` when it is inlined.  We need the following lines in the "default library" we return:

https://github.com/denoland/deno/blob/0ec629d10555ad617f3ebbafcb3276a9d96a8a86/js/lib.globals.d.ts#L3-L4

And TypeScript will not allow those in `.ts` files, they need to be hard coded into a static `.d.ts` file.  There could be an option to just pre-prend that to the inlined `globals.d.ts` file when we are bundling.

Actually saying that out loud sounds like the right thing to do...
