### ISSUE TITLE
discussion: Import maps should be an unstable feature

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#4931]
Deno is currently the only runtime that implements import maps. They are not supported by any browser at the moment.

- **Chrome**: did an origin trial from M74 to M76, ending September 4th 2019. No action since then. Currently not scheduled for an upcoming release.
- **Firefox**: position unclear (https://github.com/mozilla/standards-positions/issues/146). Not implemented or experimented.
- **Safari**: No signals. Not implemented. No tracking issue.
- **Node**: No signals. Not implemented. No tracking issue.

We are taking quite the risk by implementing this spec and supporting it in stable before it becomes a w3c standard and is implemented by other runtimes. I think we should move the entire import map feature under the `--unstable` flag.

cc @ry @bartlomieju

---

Ref https://github.com/WICG/import-maps/issues/212

**Comment by ry** [comment]
Yes I’m all for it. We should make it fail without also specifying —unstable flag. Can be implemented using State::check_unstable()

**Comment by lucacasonato** [comment]
I'm on it.
