### ISSUE TITLE
JSX from stdin is not formatted correctly

### ISSUE THREAD

**Issue by axetroy** [denoland/deno#4961]
```
$ deno fmt pages/index.tsx
pages/index.tsx
$ cat pages/index.tsx | deno fmt -
Line 9, column 22: Unterminated regexp literal
```

**Comment by ry** [comment]
I guess dprint doesn't work with JSX - is that correct @dsherret ?

**Comment by dsherret** [comment]
It should work with JSX. That’s an swc compile error so it would be good to know why.

**Comment by dsherret** [comment]
Oh! This is from stdin. We will need to figure out a way to make that work. Right now it’s relying on the filename extension (.ts vs .tsx) to tell if JSX is in the file for TS code, but I think it doesn’t do that for stdin.

**Comment by axetroy** [comment]
I think @dsherret  has found the problem

```tsx
// mod.ts
function test () {
  return <div></div>
}
```

```
$ cat mod.ts | deno fmt -
```

It may need a new flag to tell dprint its file extension name

**Comment by dsherret** [comment]
I'm thinking that when `.ts` is provided it and there's an error then it should maybe try parsing a second time with JSX enabled.
