### ISSUE TITLE
Cannot access Application and Router files with import

### ISSUE THREAD

**Issue by vreymond** [denoland/deno#4975]
Hi,

I recently dig into Deno, and wanted make a simple Api server.
For that i use the import command on the mod.ts file to access de "Application" and "Router" elements
`import { Application, Router } from "https://deno.land/x/oak/mod.ts";`

Just with this line in my code, when executed i get this error: 

`
error TS2349: This expression is not callable.
  Type 'Boolean' has no call signatures.

► https://deno.land/x/oak/send.ts:62:36

62     return (await Deno.stat(path)).isFile();
                                      ~~~~~~

error TS2349: This expression is not callable.
  Type 'Boolean' has no call signatures.

► https://deno.land/x/oak/send.ts:139:15

139     if (stats.isDirectory()) {
                  ~~~~~~~~~~~
Found 2 errors.
`

Any ideas?
Thanks in advance

**Comment by lucacasonato** [comment]
The oak library has not been updated to use the latest version of Deno yet AFAIK - there were some breaking changes to Deno since the last release of oak. I presume @kitsonk will update the library once the Deno APIs have settled just before 1.0.

**Comment by kitsonk** [comment]
Correct, this issue should be closed.

**Comment by vreymond** [comment]
Thanks for answer!
