### ISSUE TITLE
Cannot bundle deps using "export * as X from..."

### ISSUE THREAD

**Issue by PeteJodo** [denoland/deno#4979]
I had a deps file that looks like:
```js
export * as React from "https://dev.jspm.io/react";
export * as ReactDOM from "https://dev.jspm.io/react-dom";
```
and then the file consuming it...
```jsx
import { React, ReactDOM } from "./deps.js";
const rootEl = document.getElementById("root");
ReactDOM.render(<div>hello, world</div>, rootEl);
```
I then ran `deno bundle mod.js app.bundle.js`. The outputted bundle was missing the react and react-dom dependencies entirely. Changing my deps file to the below fixed the issue:
```js
export { default as React } from "https://dev.jspm.io/react";
export { default as ReactDOM } from "https://dev.jspm.io/react-dom";
```
I realize they don't mean the exact same thing but for `React` and `ReactDOM`, it does. I'm not sure if I'm missing something here. Thanks!

**Comment by kitsonk** [comment]
Duplicate of #4542

**Comment by PeteJodo** [comment]
Oh my apologies, I tried doing a search for it too 🤷‍♂️
