### ISSUE TITLE
"deno install $URL" should be meaningful

### ISSUE THREAD

**Issue by ry** [denoland/deno#5004]
in particular, it should guess a name for the shell script

permissions should come before the url so that 

```
deno run --allow-net $URL
```
matches
```
deno install --allow-net $URL
```

**Comment by nayeemrmn** [comment]
I guess it could take the extensionless basename of the URL, or the parent if it's in a list of common generic names like `mod`, `main`, `index`.

When the guessed name already exists, it would need to be interactive most likely. Maybe interactive either way even. Unless `-f` is passed.

**Comment by ry** [comment]
I agree with your example except this bit:
```
Choose a different name, or enter "file_server" to overwrite.
(file_server2): <enter>
```
Probably better to just fail

**Comment by nayeemrmn** [comment]
So `clap` doesn't support optional first arguments without a bunch of other caveats being met and there's no nice way of doing it.

- The name as the first positional argument felt really unintuitive, but was probably necessary to have the `<url> [script args]...` next to each other.
- With this feature, authors will name their executable modules in a way that flexes it and manually specifying a name should be relatively uncommon.

@ry Is it then okay to make the executable name a hyphened option?

**Comment by ry** [comment]
@nayeemrmn Yes that would be great
