### ISSUE TITLE
Unstable flag doesn't work with deno install

### ISSUE THREAD

**Issue by MarcHanin** [denoland/deno#5008]
Hi,
It's currently not possible to install deno module with the `--unstable` flag like.

`deno install --unstable ....`

### Version
deno 0.42.0
v8 8.2.308
typescript 3.8.3

Don't hesitate if I can help.

**Comment by bartlomieju** [comment]
Fix for this problem is rather easy: `deno install` should accept `--unstable` flag (to be added in `cli/flags.rs`); and then it should be added to `executable_args` in `cli/installer.rs::install` function.

**Comment by shortdiv** [comment]
If this one isn't taken yet, I'm happy to hop on it!

**Comment by MarcHanin** [comment]
I forgot to say that I was going to take it but you can take it if you want since I'm not very familiar with rust

**Comment by shortdiv** [comment]
Thanks, didn't intend to step on your toes with this one!

**Comment by MarcHanin** [comment]
No you don't step on my toes I didn't begin ! :smile:

**Comment by cdaringe** [comment]
```
$ deno repl --unstable
error: Found argument '--unstable' which wasn't expected, or isn't valid in this context
```

repl support would be cool too, if you're all on it

**Comment by zhmushan** [comment]
@shortdiv @MarcHanin Is anyone doing this, I need this feature urgently.

**Comment by MarcHanin** [comment]
If I'm not wrong @shortdiv is on it

**Comment by kitsonk** [comment]
Closed via #5061

**Comment by cdaringe** [comment]
should we open another ticket for `deno repl`  or just keep this one open, generalized for backfilling --unstable support generally?

**Comment by kitsonk** [comment]
Please open another issue.
