### ISSUE TITLE
Unstable standard library

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#5012]
Parts of the standard library now require the `--unstable` option to function. I suggest we move all things that use unstable APIs into different files which are then re-exported by multiple entry points: `mod.ts` and `unstable.ts`. `unstable.ts` would re export `mod.ts` + all unstable features.

**Comment by Soremwar** [comment]
@lucacasonato I would like to take on this

**Comment by lucacasonato** [comment]
I should clarify that this is just an idea, and that @ry, @bartlomieju and @piscisaureus have to make the decision on if this is how they want to proceed or if they have other ideas in mind. I am not a maintainer so I am not the one to make decisions.

So I think you should wait until there is some feedback from them.

**Comment by githubmann** [comment]
Will be prefix of the unstable function named with ```UNSTATBLE_```? just like react.

**Comment by jsejcksn** [comment]
This bit me today when using `https://deno.land/std/permissions/mod.ts`;

If they aren't relocated to separate files, then some kind of clear indication that `--unstable` is required for use.

**Comment by astone2014** [comment]
I am new to deno and this was very strange to me. I can't use a standard library without a special flag?

**Comment by jsejcksn** [comment]
Convention is ok, but it would be better if there were a built-in mechanism for this as long as there is an unstable API—not just in the standard library, but for all modules. Currently, if a module uses the unstable API, I have no way of knowing, except to parse compilation error messages.

@lucacasonato suggested [on Discord](https://discordapp.com/channels/684898665143206084/689420767620104201/721465971583221772):

> it would be cool if `deno info` could tell you

**Comment by bartlomieju** [comment]
I think there's no reason to change it now, closing.
