### ISSUE TITLE
Caching source files should take --unstable flag into account

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#5016]
The issue is this:
```ts
// unstable.ts
Deno.cwd()
```

1. `deno cache unstable.ts` -> `Property 'cwd' does not exist on type 'typeof Deno'.`
2. `deno cache --unstable unstable.ts` -> OK
3. `deno cache unstable.ts` -> OK

**Comment by kitsonk** [comment]
This was fixed in Deno 1.5.
