### ISSUE TITLE
tools/format.py fails on Windows

### ISSUE THREAD

**Issue by seishun** [denoland/deno#5017]
```
prettier
Traceback (most recent call last):
  File "tools\format.py", line 70, in <module>
    sys.exit(main())
  File "tools\format.py", line 31, in main
    prettier()
  File "tools\format.py", line 43, in prettier
    quiet=True)
  File "C:\Users\Nikolai\deno\tools\util.py", line 63, in run
    rc = subprocess.call(args, cwd=cwd, env=env, shell=shell)
  File "C:\Python27\lib\subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "C:\Python27\lib\subprocess.py", line 394, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 644, in _execute_child
    startupinfo)
WindowsError: [Error 87] The parameter is incorrect
```
Probably because the size of `args` is 36716, but the maximum CreateProcess supports is 32768. One possible solution is to pass globs to prettier rather than a list of files.

**Comment by MarkTiedemann** [comment]
> One possible solution is to pass globs to prettier rather than a list of files.

Does prettier resolve globs?

Another solution would be to chunk the command into chunks < 2**15, and spawn prettier multiple times. Not sure whether prettier is still single threaded. If so, this should be even faster.

<details><summary>Off-topic PS</summary>I like to add a "last formatted" timestamp to formatted files using extended file attributes (or Alternate Data Streams on Windows). Then, before re-formatting, check which ones were modified in the meantime and thus may need to be re-formatted, skip formatting all others. This helps with quickly re-formatting even the largest codebases.</details>

**Comment by littletof** [comment]
Dont know, if its any help, but this problem came up for me on a non-english windows 10 system, but later I tried it on an english one and it ran fine.

**Comment by littletof** [comment]
@seishun I tried using this command again on my non-english win10 today and it worked for me, maybe this is not an issue anymore?

**Comment by seishun** [comment]
@littletof still fails. What's your Python version? Are you running in cmd?

**Comment by littletof** [comment]
@seishun My bad its still an issue. Sorry.

I missed that I should try without `--staged`. Without it, it still fails.

On my non-english system (`Python 2.7.10`) I get an `[Error 87]` just like you.
On my english system (`Python 2.7.16`) I get an `[Error 206] The filename or extension is too long`

With that, until its fixed maybe you can use the tool with `--staged` if its sufficient for you

**Comment by piscisaureus** [comment]
I haven't encountered this issue but it seems quite possible that we're exceeding the 32768 character limit. My working directory is in `d:\deno` and with that prettier command is already about ~23500 characters.



> Another solution would be to chunk the command into chunks < 2**15, and spawn prettier multiple times. 

That would be a great solution.
