### ISSUE TITLE
updating Deno to latest version breaks tests

### ISSUE THREAD

**Issue by adrai** [denoland/deno#5025]
Can some help me?
updating Deno from v0.36.0 to v0.42.0
is generating some errors in these tests and I don't know why: https://github.com/i18next/i18next-fs-backend/tree/master/test/deno
v0.36.0: https://github.com/i18next/i18next-fs-backend/runs/605678723?check_suite_focus=true
![image](https://user-images.githubusercontent.com/1086194/80798542-eae51300-8ba4-11ea-83a3-8875690ed3a4.png)

I'm new to Deno and probably doing something wrong, but I don't know what.
Any advice?

**Comment by adrai** [comment]
if I wait at the end of the test, it works:
![image](https://user-images.githubusercontent.com/1086194/80799273-b2decf80-8ba6-11ea-89aa-354fb6d27747.png)
But why?

**Comment by hayd** [comment]
If you run with the verbose flag you'll see which op is completed during the wait, that should help you narrow down the issue (likely an unawaited promise somewhere).
