### ISSUE TITLE
An import path cannot end with a '.ts' extension. Consider importing 'https://deno.land/x/abc/deps' instead.

### ISSUE THREAD

**Issue by slim-hmidi** [denoland/deno#5027]
I got tslint error when I import a file from deno like this:
```
import { path } from "https://deno.land/x/abc/deps.ts";
```
I installed [Deno VSCode pulgin](https://marketplace.visualstudio.com/items?itemName=axetroy.vscode-deno) and restart and nothing changes. the only solution for it is just adding `@ts-ignore` to fix this.
Any solution to fix that?

**OS:** Windows 10
**VSCODE:** 1.44.2
**Deno**: deno 0.41.0
v8 8.2.308
typescript 3.8.3

**Comment by zhmushan** [comment]
you should add the following in the settings of vscode
```
"deno.enable": true
```

**Comment by slim-hmidi** [comment]
@zhmushan  I added it and restart VSCode and it does not work.

**Comment by nayeemrmn** [comment]
@slim-hmidi This is a https://github.com/axetroy/vscode-deno issue, doesn't belong here.

**Comment by slim-hmidi** [comment]
@nayeemrmn even without the VSCode plugin I have the same issue, is not a question of plugin.

**Comment by nayeemrmn** [comment]
Are you talking about VSCode warnings? The plugin is supposed to suppress that. It's obviously not a Deno issue.

**Comment by ry** [comment]
Sounds like an issue to report to tslint.

**Comment by yayanbachtiar** [comment]
> you should add the following in the settings of vscode
> 
> ```
> "deno.enable": true
> ```

its work's 
thank you @zhmushan

**Comment by ridhosatriawan** [comment]
@yayanbachtiar its not working at me

**Comment by lucacasonato** [comment]
@ridhosatriawan Run `deno: Init` command from VS Code commands (press `F1`). Then restart VS Code.

**Comment by CyberKnight007** [comment]
> @ridhosatriawan Run `deno: Init` command from VS Code commands (press `F1`). Then restart VS Code.

Thanks a lot dude this solved my problem!

**Comment by kitravee** [comment]
> @ridhosatriawan Run `deno: Init` command from VS Code commands (press `F1`). Then restart VS Code.

Thank you

Follow your step, and then it works
![image](https://user-images.githubusercontent.com/50334192/114870787-c3716f80-9e22-11eb-9523-f36f493ed85b.png)

**Comment by khanakia** [comment]
It's not working in mac already tried everyting
