### ISSUE TITLE
Formatting misalignment on console.table [0.42.0]

### ISSUE THREAD

**Issue by pedropaulosuzuki** [denoland/deno#5043]
I was messing around with **Deno 0.42.0** today [**v8: 8.2.308**, **Typescript: 3.8.3**] and found out that **console.table** is generating misaligned outputs on some kinds of input, such as strings containing some characters, such as **á**, **é**, **í**, **ó**, **ú**, **ã**, **ñ**, **õ**, among others.

This behavior seems to be present both in Javascript and Typescript files. 

### **Javascript version:**
![Deno JS console table](https://user-images.githubusercontent.com/32345702/80843137-e6871d00-8bd9-11ea-8068-ebfbdb829449.png)

### **Typescript version:**
![Deno TS console table](https://user-images.githubusercontent.com/32345702/80843139-e7b84a00-8bd9-11ea-876f-49d809462428.png)

It is not a VS Code issue, as the same behavior happens on deno.exe executable.

![deno exe console table](https://user-images.githubusercontent.com/32345702/80843142-e850e080-8bd9-11ea-83a9-8afa293412ac.png)

On node.js, this behavior does not occur.

![Node JS console table](https://user-images.githubusercontent.com/32345702/80843140-e850e080-8bd9-11ea-81d5-4b885164712f.png)

Test code:
```
const test_array = ["Amapá", "Bahia", "Goiás", "Mato Grosso", "Paraná", "Rio de Janeiro", "Rondônia"];

console.table(test_array);
```

**Comment by lucacasonato** [comment]
I'm assuming you mean 0.42.0 instead of 0.4.2?

**Comment by pedropaulosuzuki** [comment]
> 
> 
> I'm assuming you mean 0.42.0 instead of 0.4.2?

Yeah, my bad.

**Comment by Caesar2011** [comment]
Error should happen in line 34

https://github.com/denoland/deno/blob/6ee00e4da31ba040d63c756d9354391310d6f1a7/cli/js/web/console_table.ts
