### ISSUE TITLE
How to update std lib along with deno bin?

### ISSUE THREAD

**Issue by fletcherist** [denoland/deno#5047]
I updated Deno to 0.42.0 however it not updated std with it, and so i got this:
```bash
Compile file:///Users/fletcherist/mod.ts
error TS2694: Namespace 'Deno' has no exported member 'EOF'.
export function assertNotEOF<T extends {}>(val: T | Deno.EOF): T {
                                                         ~~~
    at https://deno.land/std/testing/asserts.ts:383:58

error TS2339: Property 'EOF' does not exist on type 'typeof Deno'.
  assertNotEquals(val, Deno.EOF);
                            ~~~
    at https://deno.land/std/testing/asserts.ts:384:29

Found 2 errors.
```
I'm not using `testing` package in `mod.ts` here but it seems it's used in `Deno.test`
How to reset or maybe delete std, so i could fetch latest version?

**Comment by nayeemrmn** [comment]
Replace `https://deno.land/std/` with `https://deno.land/std@v0.42.0/` in all of your import statements.

**Comment by fletcherist** [comment]
@nayeemrmn thanks for a quick reply, it fixes the problem
