### ISSUE TITLE
hosting a 3rd party esm package without typescript in deno.land/x/ ?

### ISSUE THREAD

**Issue by mreinstein** [denoland/deno#5049]
My use case:
* pure esm only, no commonjs or other legacy module formats
* I don't yet use typescript, my modules are javascript only for the foreseeable future
* I'm not interested in publishing to or interacting with npm
* I miss some aspects of npm, like having a fast, available, centralized place I can host/find packages. The idea of having modules scattered all over the web and hard to discover is unpleasant.

the `https://deno.land/x/<packagename>/<filename>` convention seems really great, but:
* so far I've only seen libraries in here that include typescript
* it seems that there is a way to get at the javascript compiled version of these files (e.g., `https://deno.land/x/denofun/pick.ts?js` but the mime type isn't set to anything associated with javascript, so this url works in deno but it doesn't work in a browser.

Has this use case been considered? Any advice on where to throw my stuff? :)

**Comment by lucacasonato** [comment]
1. `/x/` can host any file format, so js or ts.
2. `?js` does not work at all right now (neither web nor Deno). https://github.com/denoland/deno_website2/issues/356

If I'm understanding you right your use case should already be supported. If you want to host on /x/ you can add your module to this file:
https://github.com/denoland/deno_website2/blob/master/src/database.json. Some other alternatives are just using `raw.github.com` URLs or `denolib.com`.

**Comment by mreinstein** [comment]
@lucacasonato  raw.github.com serves all assets with a mime type of text/plain, and this won't work when you attempt to import the resource in a browser (the loader will complain about it not being a javscript mime type.)

**Comment by mreinstein** [comment]
I believe (but maybe I'm mistaken) that denoland does not set mime type either, but maybe I'm just doing it wrong?

**Comment by lucacasonato** [comment]
You're right - can you open an issue about that on https://github.com/denoland/deno_website2?

**Comment by mreinstein** [comment]
> can you open an issue about that 

done!

So for my use case, I guess I'm relying on both https://github.com/denoland/deno_website2/issues/356 and https://github.com/denoland/deno_website2/issues/358 being fixed?

Thanks for your help on this!
