### ISSUE TITLE
Dynamic imports should accept dynamic URLs

### ISSUE THREAD

**Issue by ghost** [denoland/deno#5058]
Dynamic imports is a decent feature for what it is capable of, however, it currently seems to lack the ability to load dynamic URLs. As an example, we cannot import a module from the current working directory in CLI tools:

```ts
import(`${Deno.cwd()}/some_file.ts`).then(console.log);
```

For regular dynamic imports of relative modules, a similar approach with a static string representing a module in a relative directory works:

```ts
import("./relative.ts").then(console.log);
```

Is there something I'm missing?

**Comment by kitsonk** [comment]
> Dynamic imports is a decent feature for what it is capable of, however, it currently seems to lack the ability to load dynamic URLs. 

What error are you getting?

**Comment by nayeemrmn** [comment]
```
thread 'main' panicked at 'internal error: entered unreachable code', cli\state.rs:452:12
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
@undefinedbuddy This one, I assume? Looks like on Windows it interprets the drive letter as the protocol, whereas on unix it just gets an absolute path.

**Comment by undefinedbuddy** [comment]
@kitsonk Like @nayeemrmn mentioned.

**Comment by undefinedbuddy** [comment]
How do I fix this issue in a cross-platform way?

**Comment by nayeemrmn** [comment]
@undefinedbuddy It's an internal bug. You can prepend `file:///` to the import specifier for now, seems like it works.

**Comment by undefinedbuddy** [comment]
Great! Does it work for all platforms? Can I simply use:

```ts
import(`file:///${Deno.cwd()}/some_file.ts`).then(console.log);
```

On Windows, this would most likely concatenate it with the drive letter as `file:///C:\`.

**Comment by kitsonk** [comment]
#5048 is a bug and we could handle it better, but supporting import `/` actually feels like a side effect.

@undefinedbuddy technically you need to change the `\` to `/` in URIs (https://en.wikipedia.org/wiki/File_URI_scheme#Windows_2).  I believe there are some functions in `std/path/mod.ts` that help with all of this.

**Comment by undefinedbuddy** [comment]
Alright, I'll certainly give that a shot!

**Comment by nayeemrmn** [comment]
Seems fixed:
```
$ deno.exe eval 'await import(`${Deno.cwd()}/temp.ts`)'
error: Uncaught (in promise) TypeError: Unsupported scheme "c" for module "c:\Users\Nayeem\projects\deno/temp.ts". Supported schemes: [
    "data",
    "file",
    "http",
    "https",
]
```
