### ISSUE TITLE
Support importing data URLs

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#5059]
As pointed out in #5048, we should consider importing data URLs.  The following works in Chromium:

```js
await import("data:application/javascript;charset=utf-8;base64,Y29uc29sZS5sb2coImhlbGxvIHdvcmxkIik7");
```

Which which then will log `hello world` to the console.

**Comment by Fenzland** [comment]
base64 is additional feature, the basic usage is
```javascript
import('data:application/javascript,'+encodeURIComponent('console.log(3);'));
```

**Comment by Lonniebiz** [comment]
Firefox supports this too:
![ffDate](https://user-images.githubusercontent.com/151919/81775651-d9f4a580-94b2-11ea-944f-21633c6f8d00.png)

**Comment by nayeemrmn** [comment]
One of this and #7433 can be closed.

**Comment by kitsonk** [comment]
How so, what PR was this landed in?

**Comment by nayeemrmn** [comment]
I mean they're duplicates and one can be closed.
