### ISSUE TITLE
Build fails when working from a directory with special characters in name (Rollup)

### ISSUE THREAD

**Issue by partheseas** [denoland/deno#506]
**macOS:** 10.13.6
**Xcode:** 9.4.1
**rustc:** 1.28.0
**ccache:** 3.4.2
**deno:** master, up to date
**third_party:** master, up to date

From a fresh clone, these are the steps I followed and the outcome: https://pastebin.com/fg1BDQdY

Seems like some kind of TypeScript error. I'm not a TypeScript expert, and was trying to install deno to get some practice with TypeScript, but the code it complains about at the very end looks syntactically valid to my untrained eye.

**Comment by ry** [comment]
Very strange. I wonder if the symlinks are setup properly? is //node_modules pointing to //third_party/node_modules ?
Can you try to delete //out and re-run setup again? Maybe it's something left over from a previous build?

**Comment by partheseas** [comment]
node_modules does indeed show up as a symlink to the correct location. It couldn't have been something from a previous build because this is me trying to build it for the first time. I just barely did a fresh clone of the repo.

I tried removing the out directory and rerunning setup.py and build.py. It still breaks on the same "unexpected token" error.

**Comment by kitsonk** [comment]
Just for context, and I don't understand it, but there are similar errors with Rollup before where for some reason the plugins are not working right and so the TypeScript plugin isn't triggered.

Looking at the code, I am wondering if for some reason the root path of `/Users/partheseas/OneDrive/Source/\(miscellaneous\)/deno` is causing something somewhere to screw up the file paths (because there is `(` and `)` in the absolute path).

Would it be possible to try some other path for the project that doesn't include `(` or `)` and see if it works?

```
[215/1025] ACTION //:bundle(//build/toolchain/mac:clang_x64)
FAILED: gen/bundle/main.js gen/bundle/main.js.map
python ../../tools/run_node.py ./node_modules/rollup/bin/rollup -c ../../rollup.config.js -i ../../js/main.ts -o gen/bundle/main.js --sourcemapFile /Users/partheseas/OneDrive/Source/\(miscellaneous\)/deno --silent --environment BASEPATH:../..
[!] Error: Unexpected token
../../js/main.ts (9:23)
 7: import * as timers from "./timers";
 8:
 9: function startMsg(cmdId: number): Uint8Array {
                           ^
10:   const builder = new flatbuffers.Builder();
11:   fbs.Start.startStart(builder);
```

**Comment by partheseas** [comment]
@kitsonk Somehow you appear to be correct. No idea why that's causing problems, but the parentheses were the problem. It builds just fine now.

**Comment by kitsonk** [comment]
knowing it works, it means that some part of Rollup doesn't handle `(` or `)` well.  I will try to narrow it down a bit and hopefully open an issue with Rollup.

**Comment by ry** [comment]
stale - no longer using rollup
