### ISSUE TITLE
Deno.Writer docs are confusing

### ISSUE THREAD

**Issue by jakajancar** [denoland/deno#5081]
"resolves to the number of bytes written from p (0 <= n <= p.byteLength)"

but also

"must reject with a non-null error if would resolve to n < p.byteLength"

So which one is it: can it resolve with `n < p.byteLength` or not?

Also, would be nice to clarify if user can/implementor must support calling `write()` before previously returned promise has resolved.

**Comment by githubmann** [comment]
yep, it's confusing. i read the source, [Deno.Buffer 's write can resolve with ```n < p.byteLength```](https://github.com/denoland/deno/blob/master/cli/js/buffer.ts#L113). I think that the doc mean that we should reject if would resolve to n < p.byteLength when we implement the Deno.Writer.
