### ISSUE TITLE
transipileOnly is not a function

### ISSUE THREAD

**Issue by yisar** [denoland/deno#5084]
`deno version rc1.0`

```shell
deno install -A --unstable 'https://deno.land/x/deku/mod.ts'
```
When I use deno install --unstable, the unstable APIs(here is transipileOnly) will throw a not a funciton error.

It seems that `--unstable` is not effective.

```shell
deno run -A --unstable 'https://deno.land/x/deku/mod.ts'
``` 
deno run works well.

**Comment by kitsonk** [comment]
Duplicate of #5008

**Comment by yisar** [comment]
```shell
deno install -A -f --unstable 'https://deno.land/x/deku/mod.ts'
```
It is my mistack, use -f to install exist mod
