### ISSUE TITLE
[util/sha1] SHA1 hash of Uint8Array returned from read operation is wrong

### ISSUE THREAD

**Issue by trebler** [denoland/deno#5085]
`Sha1.update` does not handle `Uint8Array`-s, instead it uses their `.buffer` (`ArrayBuffer`) for hashing, but when `Uint8Array` comes from, e.g. `Deno.readFile` operation, its `.buffer` and actual file contents are not equivalent.

Current workaround would be:

```typescript
const data = await Deno.readFile(fileName);

const t = new Uint8Array(data.byteLength);
copyBytes(data, t);

const hash = new Sha1().update(t).hex();
```

**Comment by githubmann** [comment]
https://github.com/denoland/deno/blob/master/cli/js/buffer.ts#L20

should be ```copyBytes(data, t)```

**Comment by trebler** [comment]
> https://github.com/denoland/deno/blob/master/cli/js/buffer.ts#L20
> 
> should be `copyBytes(data, t)`

Fixed, thanks
