### ISSUE TITLE
Create unit tests and improve code resiliency for runtime.ts

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#509]
There are likely improvements to the logic, in particular, TypeScript invokes `host.resolveModuleNames()` several times to build a dependency graph, but currently `runtime.ts` will attempt to fetch the code each time from the privileged side of deno.

We also need unit tests to be able to better properly test the boundaries of the code and ensure it behaves as designed.

**Comment by swist** [comment]
This sounds pretty interesting. Are there any limitations/parameters to how you want this done?

**Comment by kitsonk** [comment]
@swist the only thing to mention is I do have my head around the problem and was likely going to try to tackle it over the next couple of days, though exactly how to expose and rationalise the API in runtime to be more testable was going to be sort of iterative.  @ry wanted to put the unit tests in `js/unit_tests.ts`.
