### ISSUE TITLE
change community chat platform

### ISSUE THREAD

**Issue by mobop** [denoland/deno#5099]
use one that is open source and free software licensed.

**Comment by IllusionPerdu** [comment]
I think https://zulipchat.com/ can do this !

**Comment by AnthonyLenglet** [comment]
https://keybase.io/ would work as well !

**Comment by SyrupThinker** [comment]
Ok, lets bikeshed, from most to least preferred.
- IRC
- Matrix

**Comment by ry** [comment]
we’re happy with discord

**Comment by mobop** [comment]
but that's a proprietary software. what's your opinion?

**Comment by mobop** [comment]
what the is going on? why no are cares about free software? open source is flawed

**Comment by mobop** [comment]
shut the f*ck off. i wanted to be good with people but i can't. it's just not for me.

**Comment by mobop** [comment]
@ry i respect you. But your opinion on this hurts me. good bye.

**Comment by sigmaSd** [comment]
a matrix bridge would be a nice step
