### ISSUE TITLE
Request for sendFile

### ISSUE THREAD

**Issue by SRNV** [denoland/deno#5101]
I went on this issue when i wanted my server to send the content of an svg file.
naturally I made something like
`req.respond({ body: contentOfFile })`

but the content-type header were missing into the headers of the response so I had to make one function to parse the extension and return the content-type

`req.respond({ body: contentOfFile, header: new Headers([ .../** here the function call */ ]), })`

I used to use express witch make it simple with a `res.sendFile( pathToFIle )`

this is more like a feature request than an issue, but I'm sure more than one dev will go on this case

**Comment by nayeemrmn** [comment]
`std/http/server.ts` is more analogous to Node's built-in server than express. Features like this could be found or requested on, say, https://github.com/oakserver/oak.

**Comment by SRNV** [comment]
thanks
