### ISSUE TITLE
Request: Deno.existsSync(path:string): boolean

### ISSUE THREAD

**Issue by SRNV** [denoland/deno#5103]
I don't really know if that already exists but
`Deno.existsSync(path:string): boolean`
I think is needed before any file or directory action, which throw errors when the file/directory doesn't exist.

**Comment by ry** [comment]
https://doc.deno.land/https/deno.land/std/fs/mod.ts#existsSync

**Comment by johndeighan** [comment]
The link above is broken. Please remove it. And, please, please, add an existsSync() function !!!
