### ISSUE TITLE
crypto is not accessible in a Worker scope

### ISSUE THREAD

**Issue by Skillz4Killz** [denoland/deno#5111]
Use Case: I am trying to spawn Workers that connect to the Discord API for each shard. To do this, each worker needs to connect to the websocket. It seems that `crypto` is not accessible inside a Worker so it makes it impossible to use Websockets with Workers.

Error:
![image](https://user-images.githubusercontent.com/23035000/81217780-2b7ccc00-8fab-11ea-8bb9-82d0d509ce8d.png)

**Comment by sunsetkookaburra** [comment]
I'll work on this.
I can confirm this with a simple `console.log(globalThis);` in the `Worker` script.
![image](https://user-images.githubusercontent.com/55334808/81227033-1d708f00-902f-11ea-8785-31242c9d9ca1.png).
This appears to be a legacy thing (before deno supported Workers) in runtime_main. It appears the Web spec supports this feature. (https://www.w3.org/TR/WebCryptoAPI/#crypto-interface)
