### ISSUE TITLE
Remove legacy python tests / tooling

### ISSUE THREAD

**Issue by ry** [denoland/deno#5114]
We used to have much of our test infrastructure written in python. These days we use Rust unit tests for almost everything. 

There are a few remaining places where we need to convert python code to Rust:

- [x] tools/target_test.py https://github.com/denoland/deno/pull/5112
- [x] [tools/deno_dir_test.py](https://github.com/denoland/deno/blob/76c77bb32c642283e61c9a6bb4936401fc43eaba/cli/tests/integration_tests.rs#L77-L82) https://github.com/denoland/deno/pull/5408
- [x] [tools/benchmark_test.py](https://github.com/denoland/deno/blob/76c77bb32c642283e61c9a6bb4936401fc43eaba/cli/tests/integration_tests.rs#L72-L75) - removing this requires first porting [tools/benchmark.py](https://github.com/denoland/deno/blob/76c77bb32c642283e61c9a6bb4936401fc43eaba/tools/benchmark.py) to rust.
- [ ] [tools/util_test.py](https://github.com/denoland/deno/blob/76c77bb32c642283e61c9a6bb4936401fc43eaba/cli/tests/integration_tests.rs#L788-L791) this can only be removed once we don't need tools/util.py. I think we are close to that.

**Comment by 06kellyjac** [comment]
I'm going to give porting benchmark a crack

**Comment by bartlomieju** [comment]
Done in #8247
