### ISSUE TITLE
How to query Permissions

### ISSUE THREAD

**Issue by dyedgreen** [denoland/deno#5118]
I'm curios how to query permissions? There used to be the `Deno.permissions` that could be queried, but that seems to have been removed in the `1.0.0-rc1`. However I can't seem to find in which PR and what API is going to replace it.

My use-case for querying the permission is to conditionally skip tests, if the required permissions are not granted.

**Comment by SyrupThinker** [comment]
`Deno.permissions` is marked unstable and requires the `--unstable` flag

**Comment by dyedgreen** [comment]
@SyrupThinker yes that's it. Thanks for pointing that out!
