### ISSUE TITLE
Manual link forwards to github

### ISSUE THREAD

**Issue by harkairt** [denoland/deno#5124]
`Manual` link [https://deno.land/std/manual.md](https://deno.land/std/manual.md) on the page [https://deno.land/](https://deno.land/) forwards to [https://github.com/denoland/deno/tree/master/docs](https://github.com/denoland/deno/tree/master/docs).

I assume because there is no `manual.md` file in the `docs` folder.
As far as I remember a few days back the `md` files' content was shown under each other.

**Comment by zjopy** [comment]
Probably caused by #5110 @lucacasonato

**Comment by bartlomieju** [comment]
That's expected behavior

**Comment by RobertAKARobin** [comment]
@bartlomieju It may be expected behavior, but is it desired? Sure makes the docs harder to read.

**Comment by kitsonk** [comment]
It is for the moment... There are some infrastructure changes going on in preparation for the 1.0 release, which means there are some loose ends, like this one for a couple more days.  Apologies that it is all a bit of a construction site at the moment.
