### ISSUE TITLE
Deno import module specifier shenanigans?

### ISSUE THREAD

**Issue by tomkcey** [denoland/deno#5129]
Hi,
Yesterday after work, I installed Deno and gave it a first go. Had some fun, then stopped coding and went to watch TV. This morning I open up my VSCode on some other Node.js project that uses TypeScript, and this happens.
![import-module-specifier](https://user-images.githubusercontent.com/30733005/81293534-7e05c900-903b-11ea-90b4-7578c8026618.jpg)

Initially, I thought it was just a matter of setting some specs in the VSCode TypeScript settings or somesuch. Looked around and found the `Import Module Specifier` specs. They were on `auto`, which seems to be what I want.

If I add `.ts` to these now-erroneous paths, the IDE stops screaming. The thing is I'm not alone in that project and all that changed since yesterday is I installed Deno. I don't want to have to remove it. I do have the `Deno` extension on VSCode by `justjavac` enabled.

Anyone had that pproblem in the past and knows a solution to allow me to work on other TypeScript projects?

**Comment by bartlomieju** [comment]
Try uninstalling the extension. Also I suggest @axetroy's extension: https://github.com/axetroy/vscode-deno

**Comment by tomkcey** [comment]
Yes, litteraly just did that and it looks like it works. Thanks! Will try! ( you can close this)
