### ISSUE TITLE
Support inline & lazy log evaluation

### ISSUE THREAD

**Issue by matthewadams** [denoland/deno#5142]
_NB:  This is not a plug for our package._

Please support inline & deferred logging, similar to https://www.npmjs.com/package/@northscaler/bunyaner.  It's a small, single-file monkey-patch to bunyan that reduces lines of code & increases performance.

TL;DR
```
// inline logging
const o = log.info({ foo: 'bar' }) // logs & returns given argument
```

```
// lazy evaluation
log.debug(() => expensive()) // only calls expensive() if log level is debug or lower
```

It's particularly useful as shown at https://www.npmjs.com/package/@northscaler/bunyaner#use-aspects-for-tracing

**Comment by ry** [comment]
Sounds good to me.

**Comment by cknight** [comment]
I'm currently looking at a number of logging improvements so would be happy to pick this up.

**Comment by matthewadams** [comment]
@cknight I'm the author of https://www.npmjs.com/package/@northscaler/bunyaner.  Hit me up if you'd like to chat about this feature.
