### ISSUE TITLE
Custom CA certificates

### ISSUE THREAD

**Issue by jajaperson** [denoland/deno#5148]
In node, I was able to get around my organisations custom certificate authority using the [`$NODE_EXTRA_CA_CERTS`](https://nodejs.org/api/cli.html#cli_node_extra_ca_certs_file) environment variable. It seems to me that no such environmental variable or flag exists in deno.

**Comment by WilcoKruijer** [comment]
Is the `--cert` flag what you're looking for?

**Comment by bartlomieju** [comment]
As suggested by @WilcoKruijer `--cert` flag is what you're looking for @jajaperson - it takes a path to file with certificate that will be later used by Deno's HTTP client - both for module downloads as well as `fetch()` API.

**Comment by mkkhedawat** [comment]
Do we have an `Environment variable` alternative as well?
It can be a useful feature when creating internal base images for corporates.

**Comment by bartlomieju** [comment]
@mkkhedawat `HTTP_PROXY` and `HTTPS_PROXY` should work as well

**Comment by jajaperson** [comment]
@mkkhedawat do either of those take a `.pem` file path like `--cert`?

**Comment by mkkhedawat** [comment]
I would guess they take proxy URLs (cntlm/pac) just like node js. But I don't want to proxy internal traffic. So for my use case, I wrote a small script :

```sh
#!/bin/sh

if [[ $1 == "run" ]];
	then command shift && command /bin/deno2 run --cert=/usr/local/share/ca-certificates/corporate.pem "$@" ;
else
	command /bin/deno2 "$@";
fi;
```
& Docker file as

```sh
# prebuild cert workaround until deno starts using native tls
RUN mv /bin/deno /bin/deno2
COPY deno.sh /bin/deno
RUN chmod +x /bin/deno
```
It replaces deno run with deno run --cert=blah
Rest as usual.

**Comment by JP-Ellis-KPMG** [comment]
It would be very useful to be able to set a global environment variable to configure an alternative default CA bundle, especially within corporate networks using their own custom certificates. Relying on a custom `--cert` flag is not very practical, and wrapping the `deno` executable in a bash script is rather fragile.

**Comment by bartlomieju** [comment]
> It would be very useful to be able to set a global environment variable to configure an alternative default CA bundle, especially within corporate networks using their own custom certificates. Relying on a custom `--cert` flag is not very practical, and wrapping the `deno` executable in a bash script is rather fragile.

@JP-Ellis-KPMG you can use these env vars:
```
deno --help
...
    DENO_TLS_CA_STORE    Comma-separated list of order dependent certificate
                         stores. Possible values: "system", "mozilla".
                         Defaults to "mozilla".
    DENO_CERT            Load certificate authority from PEM encoded file
...
```
