### ISSUE TITLE
More granular privilege separation 

### ISSUE THREAD

**Issue by Smithx10** [denoland/deno#515]
I don't know if this even makes sense, but instead of just - -allow-write and - - allow-disk, deno could use a model similar to OpenBSD's pledge when escalating privilege. 
https://man.openbsd.org/pledge.2

**Comment by ry** [comment]
It's something we've talked about - but we won't address it anytime soon. Filing this under future.

**Comment by Smithx10** [comment]
I saw this question brought up during this presentation.https://youtu.be/z6JRlx5NC9E?t=3089.  It didn't seem like the user contract on how to give out permissions was concrete yet.    I mentioned pledge earlier,  but since then openbsd has added "unveil" https://man.openbsd.org/unveil.   Inspiration from these 2 implementations may be worth investigating. 

https://www.openbsd.org/papers/BeckPledgeUnveilBSDCan2018.pdf

**Comment by JavaScriptDude** [comment]
Ever since I saw the OpenBSD [pedge](https://man.openbsd.org/pledge.2) mechanism presented several years ago at a BSD conference, I was wondering if this model could be implemented at the VM level. This design seems like a great fit for Deno. Glad to see that this may be is a possibility. 

If this is solved, it would be amazing if it could be implemented in Rust such that it could work for Rust only programs as well. Although Rust itself does run on a  VM, I believe that such a security switching layer could be stitched into compiled Rust such that it does not add too much runtime overhead. This would be especially beneficial for Rust programs that depend on external unsafe code in C/C++ etc...

**Comment by solson** [comment]
Maybe we should close this in favour of https://github.com/denoland/deno/issues/2620? It would be good to make sure all the discussion ends up in one place.

**Comment by JavaScriptDude** [comment]
I think that #2620 does answer and provide for a strong technical direction to answer the OP's request in this issue.

However for the record, there are other aspects of the OpenBSD Pledge design that can be quite useful, that were not formally discussed here or in #2620 .

If we could, at Deno boot, grant a "main" function of the program to have the exclusive right to grant and revoke authorizations during and after the bootstrapping process, this would be a great feature. The OpenBSD team has shown that this alone has a huge impact on the tightening of application as a majority of unique system calls are done during the bootstrapping and are no longer needed afterwards.

If we close this issue, maybe we should open a new issue opened to discuss this specific opportunity for Deno.

**Comment by solson** [comment]
On Deno `--unstable`, I think you may be able to implement something like `pledge(2)` already (see `deno doc --unstable --builtin Deno.Permissions`):

```
  revoke(desc: PermissionDescriptor): Promise<PermissionStatus>
    Revokes a permission, and resolves to the state of the permission.

          const status = await Deno.permissions.revoke({ name: "run" });
          assert(status.state !== "granted")
```

Which would let a program start with broad permissions, do some setup, and then restrict to much narrower permissions for the rest of its runtime, so I guess this issue ties into the possible stabilization of that API. Is there anything else particular to `pledge(2)` that should be discussed here?

**Comment by JavaScriptDude** [comment]
Awesome. That is the big feature for me. I'm OK with closing this ticket.

**Comment by Smithx10** [comment]
@solson That looks great!  Can we revoke file system paths also like in https://man.openbsd.org/unveil ?

**Comment by solson** [comment]
```ts
type PermissionDescriptor = RunPermissionDescriptor | ReadPermissionDescriptor | WritePermissionDescriptor | NetPermissionDescriptor | EnvPermissionDescriptor | PluginPermissionDescriptor | HrtimePermissionDescriptor

interface ReadPermissionDescriptor
  name: "read"
  path?: string
```

These types imply `Deno.permissions.revoke({ name: "read", path: "/a/b/c" })` should work (and likewise for `write`).

One thing I'm not sure of is whether we *actually can* implement a `pledge(2)`-like yet. It seems like we would need a function to revoke "all except for this explicit allowlist" (like `pledge(2)`), or at least a way to enumerate all currently granted permissions so we could revoke all outside the allowlist manually.
