### ISSUE TITLE
Svelte Integration

### ISSUE THREAD

**Issue by jackedai** [denoland/deno#5169]
**Is your feature request related to a problem? Please describe.**
Svelte is compiled to JavaScript, and takes some effort to integrate with Deno

**Describe the solution you'd like**
Deno to have a flag to compile Svelte components

**Describe alternatives you've considered**
Using React or Vue

**How important is this feature to you?**
Extremely, I love Svelte and my #1 priority for any new project is using Svelte as a front end framework, but I'm not an experienced developer and I'm struggling to integrate Svelte and Deno.

**Additional context**
I believe Svelte is the future of the front end, and Deno is the future of server-side JavaScript. If the two worked out of the box together I think it could result in a paradigm shift for extremely performant, low bundle size web apps with a far better developer experience than what is currently available with Node.js / React etc.

**Comment by shortdiv** [comment]
I love this idea and I agree that integrating with frontend frameworks would be super cool! However, this functionality would probably fit better as a third party library or framework

**Comment by Soremwar** [comment]
I raised the comment on Svelte quite a while ago (2 months +). The response they gave me and some others interested was it would be troublesome, due to the close relation between Svelte and Node. The right way would be to use Deno compilers API, but that required some work on the Svelte side, not Deno side.

I see however that Deno is better fitted to work with libraries that require compilation than Node, so we should see some benefits coming from it when it finally happens.

Be patient though, adoption is a long process and Deno's history is only begun

**Comment by jackedai** [comment]
I'm not very experienced, I've only started with Svelte and I haven't done much server-side, but is it feasible to have Svelte compiling JavaScript with 'rollup -c -w', and have Deno running in a separate process while developing for hot reloading?

Could a third party framework combine functionality from both to compile .svelte components on changes, and also have the built-in TypeScript support from Deno?

**Comment by Soremwar** [comment]
I develop in React and follow a similar process, though I do the step of transpilation with Node/Parcel. I writed my app server in top of Deno, so yeah, that is a possibility in the meanwhile

**Comment by zjopy** [comment]
> Deno to have a flag to compile Svelte components

It's not Deno that needs to support Svelte, but Svelte that needs to support to Deno. This is not specific to Svelte, but every framework, library and script out there. Deno is a runtime, it's the job of the code to make sure it runs on it.

Not an issue.

**Comment by jackedai** [comment]
No worries @zjopy I'll close this, and hopefully, someone creates a framework for this in the future (maybe me in a couple of years when I know more). For now, I'll use Sapper / Node.js
