### ISSUE TITLE
for await of not support await when Concurrency request

### ISSUE THREAD

**Issue by outshineamaze** [denoland/deno#5170]

**Comment by crowlKats** [comment]
What is the issue?

**Comment by outshineamaze** [comment]
`
import { serve } from "https://deno.land/std@v0.42.0/http/server.ts";
const s = serve({ port: 8009 });
console.log("http://localhost:8009/");
let count: number = 0

const sleep = (timeout: number): Promise<void> => {
  return new Promise(resolve => {
    setTimeout(() => {
      resolve()
    }, timeout); 
  })
}
for await (const req of s) {
  console.log("request start", count);
  if (count < 1) {
    await sleep(10000)
    console.log("wait for 10000ms", count);
    req.respond({ body: "Hello World233\n" });
  } else {
    console.log("no wait for 10000ms", count);
    req.respond({ body: "Hello World233\n" });
  }
  console.log("request end", count);
  count++
  
}

//  curl http://localhost:8009/  in 3 diffrent terminal, and get result
// request start 0
// wait for 2000ms 0
// request end 0
// request start 1
// no wait for 2000ms 1
// request end 1
// request start 2
// no wait for 2000ms 2
// request end 2
`

**Comment by kitsonk** [comment]
That is expected... if you are awaiting in in a loop, the loop does not continue execution until the await in the loop resolves.  This is the nature of await, it awaits the resolution of the promise...

If you want concurrency, don't await in the loop... use `.then()`s or other methods to resolve your code.

This isn't a Deno issue, it is a misunderstanding of how JavaScript works.

**Comment by sunsetkookaburra** [comment]
I think what your finding is that `for await` will `await` the code block it contains, meaning that it *will* block any other requests because the first one is awaiting the `sleep()`.
I think this can be closed.

**Comment by sunsetkookaburra** [comment]
@outshineamaze If you want your expected results , the `listenAndServe` function in std/http will suit your needs.
