### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by FredericLatour** [denoland/deno#5171]
Locking abruptly an Issue (#5154) is not really a **great example of Conduct**.   
Someone was questioning my former post and I should have been able to answer.  

The issue was anyway already closed and only people participating would have received a notification.
I remind you that it was suggested that the discussion on this matter moves from Discord to here.

At the very least if for some reason you can't handle those kind of discussion, you should have warned that the discussion was going to be locked before doing so.

Maybe a Code of Conduct is necessary after all...

**Comment by ry** [comment]
fixed in #5165
