### ISSUE TITLE
std@v1.0.0-rc1 files missing

### ISSUE THREAD

**Issue by dbohdan** [denoland/deno#5176]
For example, <https://deno.land/std@v1.0.0-rc1/util/sha256.ts> right now returns a code 404.
![404 page screenshot](https://user-images.githubusercontent.com/3179832/81474272-c831aa80-91f3-11ea-9d7c-a651e9ddcd60.png)

**Comment by ry** [comment]
Yes sorry about that. We are not stabilizing std - it was erroneously tagged as such the last couple days. Please use v0.42.0.  Ref #5158.

**Comment by nayeemrmn** [comment]
Also, `std@v0.42.0` will break under `deno v1.0.0-rc1`. You can wait for `std@v0.50.0` (#5177) which will be compatible, or temporarily downgrade to `deno v0.42.0` as well.

**Comment by ry** [comment]
we will make `deno.land/std@v0.42.0` work still. But yea https://deno.land/std@0.50.0/ for the latest. Hopefully this will all be made much less confusing in the coming days.

**Comment by dbohdan** [comment]
Thanks for taking care of this so quickly.  `std@0.50.0` seems to work [with](https://deno.land/std@v0.50.0/hash/sha256.ts) and [without](https://deno.land/std@0.50.0/hash/sha256.ts) the "v".
