### ISSUE TITLE
Test std with the latest released deno binary

### ISSUE THREAD

**Issue by nayeemrmn** [denoland/deno#5179]
With a different release cycle, it is no longer correct to test `std` with a `deno` binary from master. CI (and developers) should install and use Deno at the latest release when testing it, just like a third party library. The release notes of any new version of `std` should say "Tested with deno vX.X.X".

**Comment by sunsetkookaburra** [comment]
will work on this in #5188

**Comment by sunsetkookaburra** [comment]
deno during cargo build/test is testing std

**Comment by nayeemrmn** [comment]
If we're still releasing at the same time, this isn't necessary.
