### ISSUE TITLE
Deno fmt deletes constructor decorators

### ISSUE THREAD

**Issue by DanielRamosAcosta** [denoland/deno#5180]
![image](https://user-images.githubusercontent.com/11427028/81478090-f1156800-9212-11ea-87da-f2040810ca0a.png)

I'm playing around with [this repository](https://github.com/DanielRamosAcosta/YfisrevniJS/tree/9dfc3cc8d27cf30d3c3a9cc2ae32112dca371f56), and I've seen that `deno fmt` is removing constructor parameters decorators and breaking the code. Is this expected?

Here is an example file that breaks after being formatted:

```ts
import { injectable, inject } from "../../../src/yfisrevni.ts"
import { Greeter, GREETER_SYMBOL } from "./greeter.ts"

export const NAMER_SYMBOL = Symbol("Namer")

@injectable()
export class Namer {
  private greeter: Greeter

  public constructor(@inject(GREETER_SYMBOL) greeter: Greeter) {
    this.greeter = greeter
  }

  public greetWith(name: string) {
    return `${name} ${this.greeter.greet()}`
  }
}
```

```
deno 1.0.0-rc1
v8 8.2.308
typescript 3.8.3
```

**Comment by bartlomieju** [comment]
Definitely a bug.

CC @dsherret

**Comment by dsherret** [comment]
@bartlomieju yeah, this is https://github.com/dprint/dprint/issues/182 which is because of it not being supported downstream in swc (works ok for constructor parameter properties). I think I'm going to have to spend the time and implement it in swc.

**Comment by DanielRamosAcosta** [comment]
Wow thanks a lot for the fast response! good work @bartlomieju @dsherret! 👏
