### ISSUE TITLE
Deno upgrade does not work because version prefix was removed

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#5184]
https://github.com/denoland/deno/blob/master/cli/upgrade.rs#L143 expects the version to start with `v`

**Comment by ry** [comment]
I’m tagging it “v1.0.0-rc2”...

**Comment by lucacasonato** [comment]
Ok - is the next release going to be prefixed with `v` or not?

**Comment by bartlomieju** [comment]
We kept `v` prefix; no longer relevant
