### ISSUE TITLE
ci should discriminate between std and core

### ISSUE THREAD

**Issue by sunsetkookaburra** [denoland/deno#5186]
for discussion and tracking, i'll put together a PR.

Currently, even for a small change in std the entire 20 minute long build process is run. This would enable fixes to std to be tested much quicker.

This is related to #5179 .

**Comment by nayeemrmn** [comment]
Hmm, while the basic structure should theoretically allow this, it's a bit complicated. The tests in `cli/js/tests` and benchmarks depend on code in `std`. This makes it possible to break those tests and not know until a future PR which touches `cli`, unless I'm misunderstanding.

**Comment by sunsetkookaburra** [comment]
adding an exception to the ci, so that if any dependencies of `cli/js/tests` are modified in std, it'll do the full ci.

**Comment by sunsetkookaburra** [comment]
issue no longer relevant now that std is back in its own repo
