### ISSUE TITLE
BadResource exception thrown from `conn.read()` when `conn.close()` called

### ISSUE THREAD

**Issue by jdiamond** [denoland/deno#5194]
I'm creating a TCP connection and starting a loop to read bytes from it. If I close the connection, the loop throws an exception.

Here is a minimal test case using `Deno.iter()` (but it behaves the same with just `conn.read()`) and the output:

```
❯ cat client-iter.ts
async function clientIter() {
  const conn = await Deno.connect({
    port: 1122,
  });

  const timeout = setTimeout(() => {
    console.log('closing');

    conn.close();
  }, 2000);

  try {
    for await (const bytes of Deno.iter(conn)) {
      console.log(bytes);
    }

    console.log('connection closed');

    clearTimeout(timeout);
  } catch (err) {
    console.log('caught error while reading');
    console.log(err);
  }
}

clientIter();

~/code/deno-tcp
❯ deno -V
deno 0.42.0

~/code/deno-tcp
❯ deno run --allow-net client-iter.ts
Uint8Array(3) [ 1, 2, 3 ]
closing
caught error while reading
BadResource: Bad resource ID
    at unwrapResponse ($deno$/ops/dispatch_minimal.ts:63:11)
    at Object.sendAsyncMinimal ($deno$/ops/dispatch_minimal.ts:106:10)
    at async Object.read ($deno$/ops/io.ts:39:17)
    at async Object.iter ($deno$/io.ts:87:20)
    at async clientIter (file:///Users/jason/code/deno-tcp/client-iter.ts:13:22)
```

If the server closes the connection, the loop exits with no exceptions.

I feel like the loop should just exit to indicate the end of the stream so not sure if I'm doing something wrong?

**Comment by jdiamond** [comment]
FYI: Upgraded to deno 1.0.0-rc2. Same result.

**Comment by bartlomieju** [comment]
@jdiamond this is expected behavior. When there's a pending "read" op (initiated by `Deno.iter()`) there is no way to cancel that pending op. You catch catch the exception in the loop after closing the server and safely ignore the exception if it is of the type `Deno.errors.BadResource`. The same strategy is used in other Deno APIs, eg. 
https://github.com/denoland/deno/blob/6f52ad9052a02f354011d2727b2ad4a3d73b08d5/cli/js/net.ts#L65-L76

**Comment by jdiamond** [comment]
Thanks for the explanation. I did resort to catching the exception, but it made me feel like I was doing something wrong because closing a connection seems "normal" to me so I was surprised to see it resulting in an exception.

Is the way I'm opening a connection and starting a loop to asynchronously read data here a good approach?

https://github.com/jdiamond/MQTT.ts/blob/dd4d715a1f855d29d98f0b6e1c12b8c744d69290/client/deno.ts#L23

**Comment by bartlomieju** [comment]
@jdiamond sorry for slow response. Your code looks ok, we use the same pattern in `std/`. 

Closing as resolved.

**Comment by jdiamond** [comment]
Thank you.
