### ISSUE TITLE
docs: std/README.md should mention that std releases are decoupled

### ISSUE THREAD

**Issue by MariusVatasoiu** [denoland/deno#5206]
Since the `std` release cycle is decoupled from the `cli`, this text should be rephrased:

*These modules are tagged in accordance with Deno releases. So, for example, the v0.3.0 tag is guaranteed to work with deno v0.3.0. You can link to v0.3.0 using the URL https://deno.land/std@v0.3.0/. Not specifying a tag will link to the master branch.* 

I would take this, but I'm not sure what is the final decision about this.

**Comment by bartlomieju** [comment]
It is now explicitly mentioned in the manual: https://deno.land/manual/standard_library#versioning-and-stability
