### ISSUE TITLE
Deno not available in Worker Space Error

### ISSUE THREAD

**Issue by Skillz4Killz** [denoland/deno#5209]
Following up on #5111 with a similar issue testing in 1.0.0-rc2 @sunsetkookaburra @bartlomieju 

![image](https://user-images.githubusercontent.com/23035000/81500376-dd641300-929f-11ea-84df-c248bed064aa.png)

**Comment by lucacasonato** [comment]
https://github.com/denoland/deno/blob/master/docs/runtime/workers.md#using-deno-in-worker

**Comment by ry** [comment]
@Skillz4Killz Use the `--unstable` flag. We had to make this feature unstable because we expect more changes.

**Comment by Skillz4Killz** [comment]
Thank you
