### ISSUE TITLE
rfc: import(/absolute/path) behavior change in std 0.50.0 from 0.42.0 - regression or feature?

### ISSUE THREAD

**Issue by cdaringe** [denoland/deno#5212]
# problem

the following behavior previously worked in 42, changed in 1.x-rc
```ts
    opts.logger.info(radFilename) // /Users/cdaringe/src/rad/rad.ts
    const res = await import(radFilename).then((mod) => from(mod)); // used to honor abs path, now tries URL import
    // ^ throws: TypeError: Import 'https://raw.githubusercontent.com/Users/cdaringe/src/rad/rad.ts' failed: 404 Not Found
    opts.logger.info('ok?') // never reached
```

# research

- related? https://github.com/denoland/deno/pull/5055/files

**Comment by cdaringe** [comment]
im still trying to grok what Deno provisions i should be using when interoping between posix and URL style paths. when should deno give me URL strings back, when should it give me posix strings back, and/or what things should handle both? as i write this, its increasingly clear that Deno always wants `URL(...)` style things, and it's up to me to transform everything into that format? `posix.toUrl(...)` may be a nice thing 🤔

**Comment by bartlomieju** [comment]
@cdaringe if you want to dynamically `import()` something; then you definitely want a URL

**Comment by cdaringe** [comment]
ya, i feel like a doofus for even askin it ;). thinking out loud on github.

```ts
export const isFileUrl = (filename: string) => filename.startsWith("file://");
export const asFileUrl = (filename: string) =>
  isFileUrl(filename) ? filename : `file://${filename}`;
```

i added ^ to as little buddies to my internal `path` mod. maybe std would be interested in doing similar? i dunno. :) anyway, my head has been cleared, and i think the breaking change is 👍
