### ISSUE TITLE
Worker: Disable relative import specifiers

### ISSUE THREAD

**Issue by nayeemrmn** [denoland/deno#5216]
A quick check on Chrome shows that relative import specifiers for Workers are resolved from `globalThis.location`. We don't have this concept at the moment so it should fail.

(Currently our `Worker` resolves from the main module, which *used to* be our `globalThis.location`.)

**Comment by kitsonk** [comment]
Hmmm... module resolution logic will always differ from a browser and a runtime. `self.location` would seem to be easier to solve than `window.location` too. I think it is best to agree to the semantics instead of just ripping it out.

**Comment by nayeemrmn** [comment]
Good point, we can keep it enabled for Workers spawned from within Workers since we do have a clear `self.location` (URL of the Worker script). But `window.location` is a huge thing which ties into a bunch of other issues... we should just disable it for now IMO.
```js
new Worker(new URL("./worker.ts", import.meta.url), { type: "module" });
```
is going to be the common usage anyway.

**Comment by aniketbiprojit** [comment]
Can someone explain why this seems a good functionality as opposed to relative path? Is it because of the complexity to implement it or just opinion based?

**Comment by nayeemrmn** [comment]
@aniketbiprojit It's about being analogous to the web. We don't have a `globalThis.location` yet so anything that's supposed to be relative to it should fail for now. Ref #4981.
