### ISSUE TITLE
error: Uncaught Error: Import 'https://deno.land/std@v0.17.0/fmt/colors.ts' failed: 404 Not Found

### ISSUE THREAD

**Issue by juslin03** [denoland/deno#5217]
I was writing crud app using mysql but when I run `deno run index.js --allow-net`, it's outpout that fmt cannot be found although I have the latest version of deno.

**Comment by kitsonk** [comment]
Need lots more information than this...

What is in `index.js`?  What is the result of `deno --version`?

**Comment by juslin03** [comment]
Just solved now. the problem was _importing mysql_ which not working.
thank  to @lucacasonato for his repl.
The reason it is not working is because https://deno.land/x/mysql/mod.ts is importing https://deno.land/x/bytes_formater@1.1.0/mod.ts which is importing a very old version on std (0.17.0). It should be solved by this pr on deno_mysql: https://github.com/manyuanrong/deno_mysql/pull/41
Finally I changed my mysql import to https://raw.githubusercontent.com/MariusVatasoiu/deno_mysql/master/mod.ts and and all works perfectly.
