### ISSUE TITLE
sh: 39: unzip: not found - UBUNTU 18.04 WSL

### ISSUE THREAD

**Issue by jhonnattan123** [denoland/deno#5220]
when i try to install deno in my host, that happens
![image](https://user-images.githubusercontent.com/31730855/81528875-a0456280-932b-11ea-9c11-8207308d0daf.png)

i try this but nothing happens https://github.com/denoland/deno/issues/2072 ¿maybe WSL problem?
i dont cant found the problem. that is the file of curl:
![image](https://user-images.githubusercontent.com/31730855/81529127-2d88b700-932c-11ea-9b52-29e1e9aeb44d.png)

**Comment by jurgenzz** [comment]
You need to install `unzip`

`sudo apt-get install unzip` will fix the issue

**Comment by jhonnattan123** [comment]
> unzip
Sorry, I had not seen that another error had previously prevented me from installing unzipping, I assumed it had been read. Thank you very much for answering, now everything is fine.

![image](https://user-images.githubusercontent.com/31730855/81529713-683f1f00-932d-11ea-9978-a9c456fdbf36.png)
i solved that error with sudo apt-get purge mongodb-org*
but after retry the install and edit the .zshrc file nothing happens, i dont can use **deno -version**
![image](https://user-images.githubusercontent.com/31730855/81530396-c9b3bd80-932e-11ea-9b8f-1d66b1d469ab.png)

y follows the steps
![image](https://user-images.githubusercontent.com/31730855/81530813-9aea1700-932f-11ea-93d8-9e38fd041938.png)
i going to root/jhonny/.deno/bin and i found a zip file i user **unzip deno.zip**
![image](https://user-images.githubusercontent.com/31730855/81530966-e56b9380-932f-11ea-81f7-50252fa5c2d1.png)

and all is working! i can use deno --version i any folder 
![image](https://user-images.githubusercontent.com/31730855/81531076-10ee7e00-9330-11ea-8440-c7893a5578ac.png)

but no in normal user.
i tried the same but not working here :C only work in root user why?
![image](https://user-images.githubusercontent.com/31730855/81531903-873fb000-9331-11ea-9801-60cc9e082430.png)

**Comment by Impeekay** [comment]
@jhonnattan123 , pleas run the script as a normal user, if you run the script as a root user, it will be installed to the root user. now in the normal user, you've posted, please run the same script.

**Comment by jhonnattan123** [comment]
> @jhonnattan123 , pleas run the script as a normal user, if you run the script as a root user, it will be installed to the root user. now in the normal user, you've posted, please run the same script.


ready! I just had to run the command on the same console, no vim needed thx u @Impeekay  and @jurgenzz  I will create a video in Spanish to teach people how to use it thx
![image](https://user-images.githubusercontent.com/31730855/81532833-18635680-9333-11ea-8035-3d45a92d95aa.png)

**Comment by jhonnattan123** [comment]
I think it should be mentioned in the guide that this command should be executed,
**`$ export PATH="/home/XXXXXXXXXXXX/.deno/bin:$PATH"`**
_XXXXXXXXXXXX = my user name_
 since 70% of new developers do not read the console, they just want to copy paste, it is a bad practice but it is just a lack of experience especially for people who speak other languages ​​like me

**Comment by Impeekay** [comment]
@jhonnattan123 , yes I do agree with that. Also keep in mind just running that once does not solve it, rather you'll have to add that command `export PATH="/home/XXXXXXXXXXXX/.deno/bin:$PATH"` to your bash_profile which maybe `.bashrc` or `.zshrc` which will ensure deno path is loaded in all terminal instances.

**Comment by jhonnattan123** [comment]
> @jhonnattan123 , yes I do agree with that. Also keep in mind just running that once does not solve it, rather you'll have to add that command to your bash_profile which maybe or which will ensure deno path is loaded in all terminal instances.`export PATH="/home/XXXXXXXXXXXX/.deno/bin:$PATH"``.bashrc``.zshrc`

Thank you, I hope that does not create problems for me, in fact right now I will create some examples to see what happens. my aim is to facilitate this for more people . because despite everything being documented, it is very difficult to understand the technical language in Spanish
