### ISSUE TITLE
Prevent circular imports in internal TypeScript code.

### ISSUE THREAD

**Issue by ry** [denoland/deno#523]

**Comment by kube** [comment]
Does `good first issue` mean `good first contribution`?
I would be interested in starting contributing to this repo if possible, and was wondering if that kind of issue was done for that.

**Comment by ShinDarth** [comment]
any hint for a first-time-contributor?

**Comment by kt3k** [comment]
- Commenting out `--silent` option [here](
https://github.com/denoland/deno/blob/146bc93b81ef1775a3a22784c74cbf0c8bbd1c9e/BUILD.gn#L232) shows where circular deps are.
- `./tools/build.py :bundle` invokes the js bundling part of the build.

**Comment by ShinDarth** [comment]
@kt3k thanks a lot.

Here the PR, please review: https://github.com/denoland/deno/pull/576
