### ISSUE TITLE
tls upgrade

### ISSUE THREAD

**Issue by aricart** [denoland/deno#5232]
Looking at Deno start on [NATS](https://nats.io) client. Noticing that there doesn't seem to be an option to provide an existing TCP connection from which a TLS upgrade can be performed. The NATS server connection is initially not secured and upgraded when the server reports that it offers TLS.

In node and other language APIs, it is possible to pass the socket to upgrade to TLS `tls.connect({socket: soc})`. Wondering if I not looking in the right place.

Thanks!

**Comment by kitsonk** [comment]
Seems like a reasonable feature to me.  I don't believe it is supported at the moment, but simply by omission versus intention.

**Comment by ry** [comment]
Check out Deno.startTls (unstable feature) 
https://doc.deno.land/https/raw.githubusercontent.com/denoland/deno/master/cli/js/lib.deno.unstable.d.ts#Deno.startTls

**Comment by kitsonk** [comment]
🤦 should have remembered that... 😭
