### ISSUE TITLE
--reload flag with deno run automatically reloads modules for that file

### ISSUE THREAD

**Issue by akshgpt7** [denoland/deno#5233]
Currently, for the user to reload specific modules, they have to specify comma separated URLs like this: `--reload=https://deno.land/std/fs/copy.ts,https://deno.land/std/fmt/colors.ts`, whereas only `--reload` flag will refresh the entire cache.

It will be a better idea if rather than specifying explicitly which modules to reload, we can give something like a --reload-file flag to automatically detect the modules being used in that file and reload only those.

Example:
```ts
// test.ts

import { x } from "url1";
import { y } from "url2";
```
So, on running `deno run --reload-file test.ts`, only the url1 and url2 modules are reloaded rather than the entire cache, and without explicitly mentioning them.

**Comment by kitsonk** [comment]
That is the current behaviour.  The full dependency tree of `test.ts` is reloaded.  Other files in the cache are not touched.  Unless you are suggesting shallow reloading, which I am not sure is desirable.

What use case would that shallow rending support or what problems is the current behaviour of `--reload` causing?
