### ISSUE TITLE
doc: style guide is broken...

### ISSUE THREAD

**Issue by bin0x00** [denoland/deno#5234]
In the `README.md` the style guide is broken and redirects to https://deno.land/std/style_guide.md which gives a 404 error.

**Comment by ry** [comment]
fixed in eec0855

**Comment by rayleighko** [comment]
It's not same issue like eec0855. eec0855 is fix in [std/README.md](https://github.com/denoland/deno/blob/master/std/README.md). this case broken main [README.md](https://github.com/denoland/deno/blob/master/README.md).

**Comment by ry** [comment]
oops - thanks - will be fixed in https://github.com/denoland/deno/pull/5236
