### ISSUE TITLE
Fetch: response.body TS2531 Error

### ISSUE THREAD

**Issue by landel** [denoland/deno#5238]
Example:

```
let response = await fetch('https://api.github.com/repos/javascript-tutorial/en.javascript.info/commits?per_page=100');

const reader = response.body.getReader();  
```
Will throw an TS2531 [ERROR]: Object is possibly 'null'...referring to the 'body' attribute 

However, using optionals chaining:

`const reader = response.body?.getReader(); `

Will throw: error: Uncaught Error: not implemented
at Object.notImplemented ($deno$/util.ts:64:9)
at Body.getReader ($deno$/web/fetch.ts:244:12)

Is that a bug? I'm trying to implement a fetch with a progress emitter.

deno 1.0.0-rc2
v8 8.4.300
typescript 3.8.3

**Comment by crowlKats** [comment]
as the error says, `getReader()` has not been implemented yet:
https://github.com/denoland/deno/blob/eec085573707d1df2bb5fbec88b9a3240613ca1f/cli/js/web/fetch.ts#L243-L245

**Comment by landel** [comment]
Thanks

**Comment by kitsonk** [comment]
For fetch, there is a long running re-write to align it better to the specs (but it also is an experiment in how we break out features in Deno from a code perspective too) and you happend to trip across a dead end at the moment.
