### ISSUE TITLE
FileReader API missing

### ISSUE THREAD

**Issue by brianleroux** [denoland/deno#5249]
The browser global `FileReader` is missing which is in use by many popular modules such as the `aws-sdk` by AWS.

**Comment by ry** [comment]
Hey Brian :) 

I definitely want to get aws-sdk ported - that would be awesome.

**Comment by brianleroux** [comment]
Meeee too. I think we will have an S3 client shortly here anyhow. The community DynamoDB client is excellent starting point. And once we have SNS and SQS…I won't have a use case for Node anymore.

**Comment by jimmywarting** [comment]
Thinking we don't need another way of reading files when `.text()`, `.arrayBuffer()` & `.stream()` already exist

https://github.com/denoland/deno/pull/4581

Kinda the new way of reading blob's in browser now days

**Comment by crowlKats** [comment]
well aws-sdk and others use FileReader

**Comment by jimmywarting** [comment]
feels like the FileReader will become more obsolete when ppl switch to the new methods

**Comment by ashx404** [comment]
But it'll take time for them to become obsolete.

**Comment by kitsonk** [comment]
We have always supported standard browser APIs based on a compelling feature request and complexity of implementing, versus whether there are better ways to do it.  Supporting `aws-sdk` is a very compelling use case.

**Comment by PaulThompson** [comment]
I had an attempt at the aws-sdk 
https://github.com/aws/aws-sdk-js-v3/issues/1289

**Comment by PaulThompson** [comment]
I made a start on FileReader https://github.com/PaulThompson/deno/tree/feat-filereader

**Comment by PaulThompson** [comment]
Ready for review on https://github.com/denoland/deno/pull/6673

**Comment by bartlomieju** [comment]
Done in https://github.com/denoland/deno/pull/6673, will be released in `v1.3.0` on Thursday.

CC @brianleroux

**Comment by lucacasonato** [comment]
> Meeee too. I think we will have an S3 client shortly here anyhow. The community DynamoDB client is excellent starting point. And once we have SNS and SQS…I won't have a use case for Node anymore.

@brianleroux FYI I started work on a [S3](https://deno.land/x/s3) and [SQS](https://deno.land/x/sqs) client a while ago. Not fully featured yet, but it is a start.
