### ISSUE TITLE
Async Stack Trace Capturing For Typescript Users

### ISSUE THREAD

**Issue by Skillz4Killz** [denoland/deno#5251]
It would be really helpful to be able to use this as being able to preserve stack traces helps provide much better errors to end-users of a library.

![image](https://user-images.githubusercontent.com/23035000/81745845-86af3280-9473-11ea-83c0-89238a09d95d.png)

![image](https://user-images.githubusercontent.com/23035000/81745852-8ca51380-9473-11ea-96e5-2cae0809d615.png)

**Comment by nayeemrmn** [comment]
Ref https://v8.dev/docs/stack-trace-api#stack-trace-collection-for-custom-exceptions
