### ISSUE TITLE
Cannot use std/fs/mod.ts without --unstable

### ISSUE THREAD

**Issue by KSXGitHub** [denoland/deno#5264]
## Problem

I want to some stable functions provided by `std/fs/mod.ts` without enabling unstable features, but it does not compile.

## Proposal

Separate unstable part of standard libraries from stable part. For example: `std/fs/mod.ts` will only include stable functions, `std/fs/unstable/mod.ts` will include all functions.

**Comment by kitsonk** [comment]
Duplicate of #5012

Please use the search feature before opening new issues.
