### ISSUE TITLE
std URLs suddenly return 404

### ISSUE THREAD

**Issue by KSXGitHub** [denoland/deno#5267]
![screenshot](https://user-images.githubusercontent.com/11488886/81811610-1bd32980-954f-11ea-80b5-f6c226619b6f.png)

## Steps to reproduce

1. Delete `~/.cache/deno`
2. Clone https://github.com/KSXGitHub/deno-args
3. Run `deno cache --unstable **/*.ts`

## Expected behavior

It runs without error

## Actual behavior

404 Not Found.

**Comment by crowlKats** [comment]
0.50.0 would be the right version for release candidates

**Comment by nayeemrmn** [comment]
@KSXGitHub Change all `std@v1.0.0-rc3` to `std@0.50.0`. `deno` and `std` versions have been decoupled: #4515.

There have been some hitches in the registry while changing tag scheme and as a result some URLs which aren't supposed to work have been working until now. Sorry.

**Comment by ry** [comment]
std is not yet at 1.0. We were erroneously linking through earlier today (https://github.com/denoland/deno_website2/pull/381).
You can get the current version here: https://github.com/denoland/deno/blob/master/std/version.ts
