### ISSUE TITLE
Allow triple-slash reference directive in Typescript files

### ISSUE THREAD

**Issue by samuelgozi** [denoland/deno#5270]
Currently it is possible to tell the compiler to load a type definitions file from within a JS file.
In some cases I think it might be beneficial to allow it from a TS file.

Right now there is no way to tell deno to load a `d.ts` file that will also work properly with an IDE.
If I use `import * as foo from './globals.d.ts';` then Deno will not throw but the IDE won't understand it.

If I use `import 'globals.d.ts'` then Deno will throw, but the IDE does understand it.

So I thought that allowing `/// <reference types="./mod.d.ts" />` to be used inside TS files might be a good in-between. Right now the IDE understands it, but deno throws `not implemented`.

Another clean(and preferable, in my opinion) option would be to allow `import 'globals.d.ts`. It looks clean, and is easy to understand.

**Comment by kitsonk** [comment]
What about the feature that already exists is not working for you?  See: https://github.com/denoland/deno/blob/master/docs/getting_started/typescript.md as there are also other scenarios where there are other ways that might be more suitable too, depending on the problem.

**Comment by samuelgozi** [comment]
The only other solution I fount is `// @deno-types="./foo.d.ts"` and it only allows to tell the compiler to use the provided types for the next import. This doesn’t work stand alone.

I’m looking for a way of importing a types definition file that is not related to a specific import.

My specific use case is bootstrapping some global types, but I believe there are other uses for this.

**Comment by crowlKats** [comment]
rn i have to add `// @deno-types="./foo.d.ts"` in every file of my project for it to recognize the declaration file, which just doesnt seem like a reasonable thing

**Comment by kitsonk** [comment]
Can you provide a specific example.

When you say "deno throws" with `import "global.d.ts";` can you provide more details.

Using `/// <reference types="" />` would conflict with the normal behaviour of `tsc` which is why we have avoided it.  So I don't think allowing it would actually do what you want it to do.

**Comment by samuelgozi** [comment]
@kitsonk its not the import that throws.
It just fails to recognize types inside `declare globals`, so the compiler throws when the types are used(but viscose recognizes them).

Sorry for not being clear about that.

**Comment by kitsonk** [comment]
@crowlKats **deps.ts**:

```ts
// @deno-types="./foo.d.ts"
export * as foo from "./foo.js";
```

**a.ts**

```ts
import { foo } from "./deps.ts";
```

@samuelgozi ok, then we should fix that... because `import "globals.d.ts";` should work.

**Comment by crowlKats** [comment]
no no, i am not importing anything, i just need a global declaration file in all the files of my project.

**Comment by kitsonk** [comment]
I will look into this, as `import "./globals.d.ts";` should work, but a couple comment on code structure in general:

- Deno has all the types it needs to compile valid code for Deno.  If you have other JavaScript (or even TypeScript) that is adding to the global scope, it is much better to have "UMD"/modular type definitions for that describe that code for JavaScript or augment the global scope in TypeScript.
- Everything that is loaded in Deno is considered a module.  Adding even types to the global scope is not the best long term solution.  Just like modules benefit structuring runtime code, having your types modular so you have explicit dependencies means that you don't burden everyone else as well as yourself from "bad" decisions around polluting the global scope, be it runtime or types.  There is a reason we have worked hard as a larger community to have modules.

**Comment by samuelgozi** [comment]
> I will look into this, as `import "./globals.d.ts";` should work, but a couple comment on code structure in general:
> 
> * Deno has all the types it needs to compile valid code for Deno.  If you have other JavaScript (or even TypeScript) that is adding to the global scope, it is much better to have "UMD"/modular type definitions for that describe that code for JavaScript or augment the global scope in TypeScript.
> * Everything that is loaded in Deno is considered a module.  Adding even types to the global scope is not the best long term solution.  Just like modules benefit structuring runtime code, having your types modular so you have explicit dependencies means that you don't burden everyone else as well as yourself from "bad" decisions around polluting the global scope, be it runtime or types.  There is a reason we have worked hard as a larger community to have modules.

I agree. I generally try to avoid polluting the global scope. But there are some cases in which it might be helpful.

**Comment by ford04** [comment]
@samuelgozi The solution you already proposed here with `declare global` and side-effect imports worked for me in [this answer](https://stackoverflow.com/questions/62152444/how-do-typescript-interface-scope-is-working-how-to-make-interfaces-global/62157767#62157767).

I am not sure, if there is another ("better") way to do it - as pointed out, a modular structure not polluting global scope certainly is the best option.
