### ISSUE TITLE
Compiler APIs "does not exists on type 'typeof Deno'"

### ISSUE THREAD

**Issue by mdubourg001** [denoland/deno#5271]
From what I've read on [this documentation](https://github.com/denoland/deno/blob/master/docs/runtime/compiler_apis.md), Deno allows access to compiler API at runtime from functions `bundle`, `compile` and `transpileOnly`.

Problem is, these APIs seems to be unreachable for me (I'm using v1.0.0-rc3). See following screenshot:

<img width="608" alt="Capture d’écran 2020-05-13 à 17 05 28" src="https://user-images.githubusercontent.com/15685173/81830523-72833800-953c-11ea-8caa-963d6e010e38.png">

Do I do it wrong or is it a known problem ?

Anyways, thanks for your great work on Deno. 👍

**Comment by lucacasonato** [comment]
They are [unstable](https://github.com/denoland/deno/blob/master/docs/runtime/stability.md). That should be marked in the docs. You need the `--unstable` flag

**Comment by mdubourg001** [comment]
Ohhhh right, thanks for the fast answer !
