### ISSUE TITLE
Deno's types for setTimeout and friends are too strict

### ISSUE THREAD

**Issue by Mehgugs** [denoland/deno#5278]
After some discussion on discord, it seems that the [timers.ts](https://github.com/denoland/deno/blob/master/cli/js/web/timers.ts#L183) callback types are too strict: 

```ts
export type Args = unknown[];
``` 
`any[]` should be used here. By using `unknown[]` it means that we can only supply functions that accept unknown, which leads to trivially correct code having a type error.
```ts 
setTimeout((x : number) => {....}, 0, 1) // this raises an error since timers.ts says we can accept anything not just numbers
```

**Comment by kitsonk** [comment]
We should just be aligning to the TypeScript lib type definitions in this case instead of trying to do something fancy.  😭

**Comment by galkowskit** [comment]
I'm working on it, seems like an ez grab (and I wish to know the codebase better). I'll hopefully provide something usable (matching `any[]` from TS instead of `unknown[]`).

I'll try to create a PR shortly.
