### ISSUE TITLE
error when running: deno run main.js 

### ISSUE THREAD

**Issue by iamfredrickokereke** [denoland/deno#5280]
While trying to check deno today I noticed, the command "deno run main.js" fails but works with "deno run main.ts" or any other file name.

Example error:
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 0, error_len: Some(1) }', cli\file_fetcher.rs:622:41
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

![image](https://user-images.githubusercontent.com/38326256/81861182-c05d6780-955f-11ea-9d9a-3176330c3922.png)

**Comment by kitsonk** [comment]
Not able to reproduce on close to master on OSX.

What specific version (`deno --version`) and what operating system?

**Comment by nayeemrmn** [comment]
`deno run main.ts` runs `main.ts`. `deno run main.js` runs `main.js`. Can you show the content of `main.js`?

**Comment by iamfredrickokereke** [comment]
@kitsonk @nayeemrmn please find below both the content and version
NB: This is running on windows, and it was installed using the Admin privilege of PowerShell with this script "iwr https://deno.land/x/install/install.ps1 -useb | iex" from deno.land.


![image](https://user-images.githubusercontent.com/38326256/81862830-34990a80-9562-11ea-98bd-0c9ab091337d.png)

**Comment by gewoonwoutje** [comment]
I've had this before, try to change the file encoding to UTF-8 as a workaround.

![image](https://user-images.githubusercontent.com/9407072/81863435-82664080-956b-11ea-9a80-6aaa2e0c1a59.png)

**Comment by iamfredrickokereke** [comment]
Thanks, @gewoonwoutje, but mine was already on UTF-8, checked this on 2 other PCs the same issue.

![image](https://user-images.githubusercontent.com/38326256/81864125-16340e80-9564-11ea-900e-bba4b3e8bdf5.png)

**Comment by gewoonwoutje** [comment]
I can only reproduce this when I change the source file encoding to something non-UTF8.

What is the status bar saying in the bottom corner? It should show UTF-8 also, otherwise you can try forcing it to UTF8 by toggling and saving in another encoding and back again.

![image](https://user-images.githubusercontent.com/9407072/81865681-7b8cfd00-956e-11ea-9002-89305ea38856.png)

**Comment by iamfredrickokereke** [comment]
Thank you @gewoonwoutje, toggling it to UTF-8 resolves this issue, and returns expected output.

**Comment by kitsonk** [comment]
Feels like on Windows that we might want to at least trap a more informative error about not supporting non-UTF8 encoding.

**Comment by iamfredrickokereke** [comment]
yes @kitsonk that would be helpful for other windows users, Thank you.

**Comment by iamfredrickokereke** [comment]
Resolved.
