### ISSUE TITLE
Welcome.ts - Deno emoji renders garbled on Powershell, CMD on Windows 10

### ISSUE THREAD

**Issue by snerks** [denoland/deno#5286]
Steps to reproduce:

On Windows 10

Issue the following command in a terminal:

```
deno run https://deno.land/std/examples/welcome.ts
```

Actual output:

**CMD**
`Welcome to Deno �🦕`

**Powershell 7 Core**
`Welcome to Deno �`

**Comment by piscisaureus** [comment]
That's because the windows 10 console doesn't support emoji (or any non-BMP unicode code points for that matter). It's not something we can fix.

If you use the new `terminal` app:

![image](https://user-images.githubusercontent.com/218257/81879546-6377a680-958b-11ea-92ee-08587d10385d.png)
