### ISSUE TITLE
Type declaration file has examples using 5 spaces after the "* " which causes formatting errors in VS Code

### ISSUE THREAD

**Issue by Tyriar** [denoland/deno#5288]
Using a dev build of https://github.com/denoland/vscode_deno

![image](https://user-images.githubusercontent.com/2193314/81877046-f63b2580-9538-11ea-8a2e-74000abd08a4.png)

This is because of these lines:

https://github.com/denoland/deno/blob/d397b86c6cea1517342dfa92055d8ed00c564ee1/cli/js/lib.deno.ns.d.ts#L803-L805

Recommendation:

```
    *      await Deno.mkdir("new_dir"); 
    *      await Deno.mkdir("nested/directories", { recursive: true }); 
    *      await Deno.mkdir("restricted_access_dir", { mode: 0o700 }); 
```

Or:

```
    * ```ts
    * await Deno.mkdir("new_dir"); 
    * await Deno.mkdir("nested/directories", { recursive: true }); 
    * await Deno.mkdir("restricted_access_dir", { mode: 0o700 }); 
    * ```
```

We use the latter in the VS Code API:

![image](https://user-images.githubusercontent.com/2193314/81877301-89745b00-9539-11ea-9e99-429cf9d6bd8d.png)

**Comment by Siddharth11** [comment]
@Tyriar @bartlomieju i've raised a [PR](https://github.com/denoland/deno/pull/5475) for this fix
