### ISSUE TITLE
`deno --version` prints the version, but `deno -v` does not.

### ISSUE THREAD

**Issue by davidgilbertson** [denoland/deno#5289]
After squinting at the help screen I see that it's a **capital** V required when typing `-V`, so this isn't really a bug. But I imagine I'm not the only one who will type `-v` and get an error.

**Comment by startewho** [comment]
OPTIONS:
    -h, --help                     Prints help information
    -L, --log-level <log-level>    Set log level [possible values: debug, info]
    -q, --quiet                    Suppress diagnostic output
    -V, --version                  Prints version information

seems a lit confused

**Comment by frencojobs** [comment]
@davidgilbertson is right. Is there any specific reason why capital V is used? `-v` is more user friendly and preferable than `-V`.

**Comment by kevinkassimo** [comment]
> @davidgilbertson is right. Is there any specific reason why capital V is used? `-v` is more user friendly and preferable than `-V`.

This was intentional. `-v` might be confusing since it also can mean `--verbose` if we were to ever add this flag.

**Comment by frencojobs** [comment]
Ok, then I think this is no longer an issue since it was intentional. Someone close the issue, please.

**Comment by waldyrious** [comment]
> This was intentional. `-v` might be confusing since it also can mean `--verbose` if we were to ever add this flag.

@kevinkassimo Isn't a `--verbose` flag unlikely, given that there's `--log-level` already? I just bumped into this and had the same question/expectation as @davidgilbertson and @frencojobs.

FWIW, lowercase `-v` is associated with both `--version` and `--verbose` in the Linux Documentation Project's [Standard Command-Line Options](https://tldp.org/LDP/abs/html/standard-options.html), and in The Art of Unix Programming's [Command-Line Options](http://www.catb.org/~esr/writings/taoup/html/ch10s05.html) (though the latter also offers uppercase `-V` for `--version`).

**Comment by dsherret** [comment]
Deno 1.44+ supports the lowercase `-v` flag.
