### ISSUE TITLE
Compile fails when deno_dir is relative

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#5293]
```ts
// hello.ts
console.log('Hello World');
```

```shell
$ env DENO_DIR=denodir deno cache hello.ts
Compile file:///xyz/test.ts
thread 'main' panicked at 'Bad file URL for file: ()', cli/tsc.rs:722:7
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This is caused by `Url::from_file_path` not being able to handle relative paths.

This also occurs at `cli/tsc.rs:633:35` with a slightly different input.

**Comment by bartlomieju** [comment]
Note to self: as pointed by @lucacasonato in other issue this happens when `DENO_DIR` isn't fully resolved path - before creating `DENO_DIR` we should resolve relative path to get an absolute one.
