### ISSUE TITLE
Flags are not positional

### ISSUE THREAD

**Issue by frencojobs** [denoland/deno#5294]
## Description
I'm not sure if this is expected behavior or not, but flags should be positional. For instance, if I run this,
```bash
deno run --allow-net server.ts
```
it will work properly. But moving the flag to the end of the command will result in an error.
```bash
deno run server.ts --allow-net

error: Uncaught PermissionDenied: network access to "127.0.0.1:8000", run again with the --allow-net flag
    at unwrapResponse ($deno$/ops/dispatch_json.ts:43:11)
    at Object.sendSync ($deno$/ops/dispatch_json.ts:72:10)
    at Object.listen ($deno$/ops/net.ts:51:10)
    at listen ($deno$/net.ts:164:18)
    at serve (server.ts:261:20)
    at server.ts:3:11
```
## Expected Behavior
The flags after the filename should also work. As in this case,
```bash
cat server.ts --number-nonblank
# vs
cat --number-nonblank server.ts
```

## Environment
OS - Microsoft Windows 10 Pro
Shell - Powershell
Deno - 0.42.0
V8 - 8.2.308
Typescript - 3.8.3

**Comment by nayeemrmn** [comment]
Duplicate of #2708, #3469. Everything after the script name is given as an arg to the script (accessible in `Deno.args`). This is the behaviour of any other runtime.

**Comment by frencojobs** [comment]
Make sense. I'll close the issue as this is an expected behavior.
