### ISSUE TITLE
error sending request for welcome.ts : error trying to connect: invalid dnsname

### ISSUE THREAD

**Issue by U97F3** [denoland/deno#5296]
`$ deno run https://deno.land/std/examples/welcome.ts`
**showed the result :** 
line 1 : `Download https://deno.land/std/examples/welcome.ts`
line 2 : `error: error sending request for url (https://deno.land/std/examples/welcome.ts): error trying to connect: invalid dnsname
`
**how could i make it?**

**Comment by Pryrios** [comment]
I think you need to give net permissions to deno with:

> $ deno run --allow-net https://deno.land/std/examples/welcome.ts

**Comment by onyz4x** [comment]
try   
deno run --allow-net https://deno.land/std/examples/welcome.ts

**Comment by U97F3** [comment]
> try
> `deno run --allow-net https://deno.land/std/examples/welcome.ts`

thanks for apply, but it didn't workl.

**Comment by bartlomieju** [comment]
@U97F3 this looks like a problem related with your network, are you using some proxy?

**Comment by hanhduykaka** [comment]
I have same error, my network using proxy server.

`deno install https://deno.land/std/http/server.ts`
Download https://deno.land/std/http/server.ts
error: error sending request for url (https://deno.land/std/http/server.ts): error trying to connect: tcp connect error: No connection could be made because the target machine actively refused it. (os error 10061)

**Comment by hanhduykaka** [comment]
how to by pass proxy, I can't disabled or turn off proxy. I'm not an administrator

**Comment by isTomYang** [comment]
> how to by pass proxy, I can't disabled or turn off proxy. I'm not an administrator

I met the same problem as you, and I found my proxy is unstable, you can download that .ts files and run in local network like http://localhost:5000/welcome.ts

![image](https://user-images.githubusercontent.com/55040807/84593845-f3f22100-ae80-11ea-99e8-95e85e976735.png)

**Comment by hanhduykaka** [comment]
Oh, awesome!
I download all and run local
I look like node_modules ^^
https://github.com/hanhduykaka/deno

**Comment by juzi5201314** [comment]
I also encountered this problem and I was using a proxy.
`fetch("https://google.com")`:
`error: Uncaught Http: error sending request for url (https://google.com/): error trying to connect: invalid dnsname`

**Comment by kidonng** [comment]
[@hronro](https://deno.js.cn/u/hronro) [mentioned](https://deno.js.cn/t/topic/271/22) that this may be a upstream bug: ctz/rustls#184
