### ISSUE TITLE
Add/improve documentation for ops

### ISSUE THREAD

**Issue by sejr** [denoland/deno#5298]
The concept of _ops_ is mentioned in a few different locations in passing, but the manual should provide (at least) a high level overview of what they are, how they are consumed by the Deno "front-end," and the process for adding new ops.

Existing literature: https://github.com/denoland/deno/blob/master/docs/contributing.md#adding-ops-aka-bindings

**Comment by bartlomieju** [comment]
Closing in favor of https://github.com/denoland/deno/issues/8026
