### ISSUE TITLE
deno upgrade command gives error - Access is denied. (os error 5)

### ISSUE THREAD

**Issue by potham** [denoland/deno#5301]
Trying to upgrade deno, faced below error.
upgrading from:

- deno 0.38.0 
- v8 8.2.308
- typescript 3.8.3

![image](https://user-images.githubusercontent.com/31108412/81888194-76579e80-95be-11ea-9c57-339602cefbfe.png)

**Comment by piscisaureus** [comment]
There could be many reasons for this. Can you retry a couple of times and tell us if it keeps failing?

**Comment by potham** [comment]
Tried in powershell as Admin, resolved the issue.

**Comment by chandan-krishna115** [comment]
> There could be many reasons for this. Can you retry a couple of times and tell us if it keeps failing?

Yes i'm getting same error again and again

**Comment by ebebbington** [comment]
> > There could be many reasons for this. Can you retry a couple of times and tell us if it keeps failing?
> 
> Yes i'm getting same error again and again

Try run powershell as admin

If that doesn't work, run it as admin, type the following command: `Start-Process powershell -Verb runAs`, then try again

**Comment by espetro** [comment]
I'm still getting the same error, even running with Powershell as admin. I'm running it on Windows 10 and `deno --version`

```
deno 1.2.1
v8 8.5.216
typescript 3.9.2
```

**Comment by ebebbington** [comment]
@espetro have you tried the second step in https://github.com/denoland/deno/issues/5301#issuecomment-659399419

**Comment by espetro** [comment]
@ebebbington yeah! Anyway, it was not an error linked to this Issue.

I was trying to import from a directory, without specifying the `.ts` file extension (e.g. `import * as mod from "./myModule"`). I don't know if this error should be notified into another (probably existing) Issue tho.

**Comment by bakasmarius** [comment]
I just got the same error and simply closing VSCode helped (it had a deno project opened).

**Comment by hb20007** [comment]
In my case, it was the antivirus. I temporarily closed it and it worked.

**Comment by FractalHQ** [comment]
None of the solutions here have worked for me with the latest Deno version on Windows 10.  I've disabled all the windows defender firewall / windows security bloatware, closed all programs, ran powershell/windows terminal/cmder/cmd as administrator, tried using `runas`, etc, to no avail.
