### ISSUE TITLE
Deno manual style guide

### ISSUE THREAD

**Issue by Marcos-Costa** [denoland/deno#5304]
The table of contents in the [9.3. Style Guide](https://deno.land/manual/contributing/style_guide#table-of-contents) section is missing.

**Comment by bartlomieju** [comment]
Now fixed: https://deno.land/manual/contributing/style_guide

**Comment by Marcos-Costa** [comment]
![Screenshot from 2020-05-19 19-13-16](https://user-images.githubusercontent.com/19848508/82383756-d4441600-9a04-11ea-883f-980fe4f5c2e9.png)
It still empty

**Comment by kitsonk** [comment]
Your screenshot specifically shows it isn't empty.  If you are referring to the lack of a Table of Contents, that is a deno_website2 issue with supporting generating markdown TOCs.
