### ISSUE TITLE
Closing the deno repl affects PS1

### ISSUE THREAD

**Issue by shardyMBAI** [denoland/deno#5305]
Hello :wave: 

I installed `deno` following [the manual](https://deno.land/manual/getting_started/installation) and set up auto-complete. Then I ran `deno repl` and only ran `close()`. After my `PS1` seems to be affected and I need to exit the session. 

![Screen Shot 2020-05-14 at 12 18 57 AM](https://user-images.githubusercontent.com/27963753/81892613-86995a80-9579-11ea-8190-2028f4030a8f.jpg)

When I run 
1. deno repl
2. close()
3. echo $PS1 (it does not display typed the command, but it does seem to output a result)

![Screen Shot 2020-05-14 at 12 31 24 AM](https://user-images.githubusercontent.com/27963753/81892986-7170fb80-957a-11ea-976e-e2daa5242f74.jpg)

Using the other recommended exit `ctrl+d` everything runs fine.

![Screen Shot 2020-05-14 at 12 30 06 AM](https://user-images.githubusercontent.com/27963753/81892872-2b1b9c80-957a-11ea-8606-1c4eb7fd22e0.jpg)

OS: masOS - Majove v10.14.6

**Comment by brunohgv** [comment]
I am also having this issue.

Using `ctrl+d` is fine, but running the `close()` command it breaks the terminal.
It is still possible to type and run commands, but no text is displayed.
It is necessary to restart the terminal to fix it.

![image](https://user-images.githubusercontent.com/21175767/82005485-e48e7680-963b-11ea-8d10-ecfccc5112a3.png)

OS: Ubuntu 20.04 LTS

**Comment by shardyMBAI** [comment]
Hello again, 

I think I found the issue, [exit is not defined in the file](https://github.com/denoland/deno/blob/4e5e6da348fb6c6d289426f313e564d6fd6fe242/cli/js/repl.ts#L76). 

I can make a PR later tonight after work if that is okay.

Thanks again.

**Comment by bartlomieju** [comment]
Closing in favor of #5449
