### ISSUE TITLE
How to support Deno and Typescript compile with import from files

### ISSUE THREAD

**Issue by KieranP** [denoland/deno#5308]
Very simple application. Two files, world.ts and play.ts. play.ts includes world.ts.

`import {World} from './world.ts'`

`deno run play.ts` works great.

But breaks typescript compile (`tsc`):

```
play.ts:1:21 - error TS2691: An import path cannot end with a '.ts' extension. Consider importing './world' instead.
1 import {World} from './world.ts'
                      ~~~~~~~~~~~~
Found 1 error.
```

So if I switch it to just ./world, then deno fails:

```
Compile typescript/play.ts
error: Uncaught NotFound: Cannot resolve module "typescript/world" from "typescript/play.ts"
```

I understand that requiring extensions if a feature of deno. I can't find anything in the docs that explains how to properly support deno and tsc. Can it be done?

**Comment by Epskampie** [comment]
From what I understand, at this point it's impossible. The two import syntaxes are mutually exclusive. Deno requires the .ts extension, tsc forbids it.

**Comment by bordoley** [comment]
FWIW, it's possible but not easy. I have a node package i wrote that uses build steps to transform the import/exports to be deno compatible. see: https://github.com/bordoley/reactive-js/blob/master/packages/core/package.json#L68-L76

That said it requires to do so requires all your dependencies to also have deno equivalents. That package has 0 runtime node dependencies so it works.
