### ISSUE TITLE
/std/ws readme instructions cause blocking of Server's iterator

### ISSUE THREAD

**Issue by MarcDwyer** [denoland/deno#5322]
Following the https://deno.land/std/ws instructions to set up a ws server it seems to only allow one ws connection at a time. If I close the successfully connected ws it will than iterate to the next queue'd request and upgrade it to a ws. After tinkering with some of the source code I believe the issue exists somewhere in the MuxAsyncIterator class.

/std/util/async.ts
```
async *iterate(): AsyncIterableIterator<T> {
    while (this.iteratorCount > 0) {
      // Subsequent requests seem to block here and never yield a value
      await this.signal;

      for (let i = 0; i < this.yields.length; i++) {
        const { iterator, value } = this.yields[i];
        yield value;
        this.callIteratorNext(iterator);
      }
    // This code doesn't run after first successful ws connection is made
      this.yields.length = 0; 
      this.signal = deferred();
    }
  }
```

**Comment by MarcDwyer** [comment]
It also seems like the iterators done property never returns true unless the first successful ws connection is terminated.

**Comment by MarcDwyer** [comment]
I seemed to have found a temporary solution. However, it might cause other bugs that I am not currently aware of. The solution is to create another async function that listens to WebSocket iterator. Do not add the 'await' keyword as that will continue blocking the main iterator.

```
const s = serve({ port: 5010 });
for await (const req of s) {
  const { conn, r: bufReader, w: bufWriter, headers } = req;

  try {
    const sock = await acceptWebSocket({
      conn,
      bufReader,
      bufWriter,
      headers,
    });
    console.log("connected");

// Create seperate function so it does not block the current iterator
    listenWs(sock);
  } catch (err) {
    console.error(err);
  }
}

async function listenWs(ws: WebSocket) {
  for await (const ev of ws) {
    console.log(ev);
  }
}
```

**Comment by bartlomieju** [comment]
CC @keroxp

**Comment by keroxp** [comment]
@MarcDwyer Correct. `for await` in `for await` blocks server from processing next request. We should rewrite example.
