### ISSUE TITLE
Add the support for MSYS / Cygwin on Windows

### ISSUE THREAD

**Issue by MatteoGauthier** [denoland/deno#5330]
Deno install only create a .cmd file for windows but a lot of people using subsystem on their computer.
Maybe add a command argument to the `install `method like `--unix --win` or adding by default both `.sh` / `.cmd` file

**Comment by frencojobs** [comment]
WSL users should install the Linux version of Deno. Accessing the windows program from WSL can result in errors like [**this**](https://github.com/microsoft/WSL/issues/3882#issuecomment-468141196).

**Comment by MattixNow** [comment]
Yes, but with npm a .sh file is created for user using packages with Git Bash or Cygwin

**Comment by MattixNow** [comment]
@frencojobs i corrected the title of the issue (removing WSL) thanks for your reply

**Comment by promethyttrium** [comment]
In the meantime, `npm install -g .` to the rescue... :)

**Comment by MatteoGauthier** [comment]
Any updates ?
