### ISSUE TITLE
Router like express

### ISSUE THREAD

**Issue by silvanohirtie** [denoland/deno#5339]
For now I have this code in my server.ts file:
```js
import { serve } from "https://deno.land/std@0.50.0/http/server.ts";
const s = serve({ port: 3000 });
console.log("http://localhost:3000/");
for await (const req of s) {
  if (req.url === "/") {
    req.respond({
      body: "Index Page"
    });
} else if (req.url === "/about/" || req.url === "/about" ){
  req.respond({
    body: "About page"
  });
}
  else {
  req.respond({
    body: "404"
  })
}
}
```
How you can see I'm manually inserting that text into the body of the req.url. How Can I insert a .html file instead? And maybe create a router method like express one

**Comment by haqqer** [comment]
Why you not try Third Party Modules like Oak Deno Http Server https://github.com/oakserver/oak

**Comment by silvanohirtie** [comment]
> Why you not try Third Party Modules like Oak Deno Http Server https://github.com/oakserver/oak

Yeah I figured out after the post, thanks anyway! :)

**Comment by No54** [comment]
> For now I have this code in my server.ts file:
> 
> ```js
> import { serve } from "https://deno.land/std@0.50.0/http/server.ts";
> const s = serve({ port: 3000 });
> console.log("http://localhost:3000/");
> for await (const req of s) {
>   if (req.url === "/") {
>     req.respond({
>       body: "Index Page"
>     });
> } else if (req.url === "/about/" || req.url === "/about" ){
>   req.respond({
>     body: "About page"
>   });
> }
>   else {
>   req.respond({
>     body: "404"
>   })
> }
> }
> ```
> 
> How you can see I'm manually inserting that text into the body of the req.url. How Can I insert a .html file instead? And maybe create a router method like express one

Maybe it is really a common requirement.  

Thank you friends. I ll take look at the oak
