### ISSUE TITLE
Working directory for files

### ISSUE THREAD

**Issue by mathiasrw** [denoland/deno#5340]
It looks like the working directory for running code based on a url is not the same as when running code from a file. I consider this a bug, but there might be some higher reasoning I cant figure out. 

**Example:**

If I am in a folder and do a

    deno run --allow-read https://deno.land/std/examples/cat.ts myfile.txt

it will not be able to find the file unless I give an absolute path. 

However, if I take the content of https://deno.land/std/examples/cat.ts and save it as cat.ts and do a 

    deno run --allow-read cat.ts myfile.txt

It outputs the file perfectly. 

I would expect both examples to find the file because the deno command is initiated in the same directory in both examples.

**Comment by nayeemrmn** [comment]
Can't reproduce on 1.0.0. Can you give more info?

**Comment by mathiasrw** [comment]
I am _so_ sorry. Turns out I had one terminal open with deno v1.0.0 but the terminal I tested in for some reason used another deno file that was 0.42.0.

Thanks for a great product. Can't wait to see where this brings the ts developer community. 

![image](https://user-images.githubusercontent.com/1063454/81939810-1b8e6900-95f7-11ea-9deb-106f200dcd60.png)
