### ISSUE TITLE
Embedded Deno Support

### ISSUE THREAD

**Issue by colorhook** [denoland/deno#5342]
I want to embed a JS/TS vm to a native application, But `lib.rs` has removed from `cli` module.

I could create a deno instance before, but it won’t work now.

```rust
use deno::{
  state::{ State, DebugType },
  global_state::GlobalState,
  worker::Worker,
  ops,
  flags::{Flags},
};

let data = include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/CLI_SNAPSHOT.bin"));
let startup_data = StartupData::Snapshot(Snapshot::Static(data));
```

The `CLI_SNAPSHOT.bin` file copied from `deno` build result

**Comment by bartlomieju** [comment]
@colorhook we recently removed `lib.rs` from `deno` crate in: https://github.com/denoland/deno/pull/5226 

The reason is that we expect further rapid changes to the Rust side of CLI and can't guarantee stability at this moment.

**Comment by mduclehcm** [comment]
I wait for deno lib so long. 😫

**Comment by bartlomieju** [comment]
I know this issue was first but let's continue in #7928
