### ISSUE TITLE
upgrade instructions (from rc1 to 1.0.0)

### ISSUE THREAD

**Issue by btrauma8** [denoland/deno#5343]
What am I missing? Can't seem to get deno upgrade working (on windows) to get from rc1 to 1.0.0

![image](https://user-images.githubusercontent.com/4399964/81936312-ae0f1800-95b7-11ea-9186-d53326c3bf54.png)

**Comment by SyrupThinker** [comment]
Upgrading to a specific version has been added in version [v1.0.0-rc2](https://github.com/denoland/deno/releases/tag/v1.0.0-rc2). You need to use another method this time.

**Comment by btrauma8** [comment]
Thanks! deno upgrade --force did the trick.

**Comment by kerolloz** [comment]
@btrauma8 
Would you please close the issue
