### ISSUE TITLE
Add OS Notifications to std

### ISSUE THREAD

**Issue by bensleveritt** [denoland/deno#5348]
Looking to use Deno as a replacement to some Bash scripts, and I'd like to use OS notifications. I think I can see a way to do it with a Rust shim, but I was wondering if it would be considered for inclusion with std? Mirroring the Web Notifications API perhaps?

**Comment by bartlomieju** [comment]
Such library should start as a 3rd party module. If there's a lot of interest it could be later incorporated into standard library. It would most likely be a native plugin; here are some references to libs that use native plugins:
https://github.com/crabmusket/deno_sqlite_plugin
https://github.com/eliassjogreen/deno_webview

**Comment by divy-work** [comment]
@bensleveritt You could use https://github.com/divy-work/deno-notify
