### ISSUE TITLE
ccashe on windows 10 not exist

### ISSUE THREAD

**Issue by George35mk** [denoland/deno#535]
Hi, I am trying to play with the deno on windows 10 x64 pc I have and I notice that on **deno build instruction** is say something about `ccashe` so I follow the link and I redirected to Mozilla where is not mentioned about windows only Linux and Mac support I found.

Can someone tell me if this is possible on windows?
And if yes what are the steps to installing on windows.

Thanks.

**Comment by piscisaureus** [comment]
> Can someone tell me if this is possible on windows?

Using ccache (or something similar) is not possible on windows.
The gn toolchain definition from chromium (which is what we use) ignores "cc_wrapper", and alternative ways (like setting `CXX=ccache clang-cl` also don't work.

**Comment by George35mk** [comment]
Thanks

**Comment by MasterJames** [comment]
I think I saw a plan to provide builds soon but it will be for a Linux/Unix System/VM only initially.On Aug 17, 2018 1:32 PM, "George C." <notifications@github.com> wrote:Thanks
