### ISSUE TITLE
TextDecoder should support the stream option

### ISSUE THREAD

**Issue by bordoley** [denoland/deno#5351]
https://github.com/denoland/deno/blob/bced52505f32d6cca4f944bb610a8a26767908a8/cli/js/web/text_encoding.ts#L456

Ideally TextDecoder would support the stream option for spec compliance as well as for supporting incremental decoding of encoded text from streaming input that may include incomplete surrogate pairs.

**Comment by jimvandervoort** [comment]
I'd like to give this issue a try

**Comment by kfdf** [comment]
That's actually quite an inconvenience. Without the `stream` option and no utf-8 support in `TextEncoder` there's no straightforward way to work with large amounts of non-ascii text in Deno. Pehaps, removing encodings from TextEncoder wasn't necessary? Alignment with web standards is good, but Deno isn't just for web...

**Comment by lucacasonato** [comment]
> no utf-8 support in `TextEncoder`

This is wrong. TextEncoder supports UTF-8. It is actually the only encoding it supports...

**Comment by kfdf** [comment]
Yes, that was a typo. And the silly thing is, that for many single byte encodings the Encoder can be easily created from the corresponding Decoder. Again, this artifitial limitation is understandable for the web, but outside of it various encodings have very legitimate use-cases and aren't going anywhere.
