### ISSUE TITLE
SIGINT (CTRL+C) does not terminate process

### ISSUE THREAD

**Issue by dougcoburn** [denoland/deno#5352]
My setup
MacOS 10.15.4
Deno 1.0.0

Following instructions from https://deno.land/v1

created a file named serve.ts
```javascript
import { serve } from "https://deno.land/std@0.50.0/http/server.ts";
for await (const req of serve({ port: 8000 })) {
  req.respond({ body: "Hello World\n" });
}
```
Run it from the terminal (iTerm)
```bash
deno run --allow-net serve.ts
^C^C^D
```
CTRL+C / CTRL+D is not exiting the process.  If I open a new terminal window and run `kill <pid>` it kills the process and the terminal emulator (iTerm) instance running the deno process as well.

I can reproduce it sometimes in the built-in terminal app as well, but sometimes it works there.

**Comment by bartlomieju** [comment]
@dougcoburn I can't reproduce this problem locally; can you provide some more context? Try running with `-Ldebug` flag

**Comment by bartlomieju** [comment]
Closing as stale. Please reopen if problem persists.
