### ISSUE TITLE
The http server cannot automatically process "connection: close" and "connection: keep-alive" in headers to close the connection or maintain the connection.

### ISSUE THREAD

**Issue by masx200** [denoland/deno#5355]
The http server cannot automatically process "connection: close" and "connection: keep-alive" in headers to close the connection or maintain the connection.

**Comment by deepu105** [comment]
This still seems to be an issue. Try the below for example

```
import {
  listenAndServe,
  ServerRequest,
} from "https://deno.land/std/http/server.ts";

let count = 0;

listenAndServe(
  { hostname: "0.0.0.0", port: 8080 },
  async (req: ServerRequest) => {
    count++;
    // add 2 second delay to every 10th request
    if (count % 10 === 0) {
      console.log("Adding delay. Count: ", count);
      await sleep(2000);
    }
    // read html file
    const body = await Deno.readTextFile("./hello.html");
    const res = {
      status: 200,
      body,
      headers: new Headers(),
    };
    res.headers.set("Connection", "keep-alive");
    req.respond(res);
  }
);

function sleep(ms: number) {
  return new Promise((resolve) => {
    setTimeout(resolve, ms);
  });
}
```

Now run `ab -c 100 -n 10000 http://127.0.0.1:8080/` and it will fail, where as `ab -k -c 100 -n 10000 http://127.0.0.1:8080/` works. So seems like `keep-alive` in the header is not respected

**Comment by PoslinskiNet** [comment]
Any updates on this one?

> This still seems to be an issue. Try the below for example
> 
> ```
> import {
>   listenAndServe,
>   ServerRequest,
> } from "https://deno.land/std/http/server.ts";
> 
> let count = 0;
> 
> listenAndServe(
>   { hostname: "0.0.0.0", port: 8080 },
>   async (req: ServerRequest) => {
>     count++;
>     // add 2 second delay to every 10th request
>     if (count % 10 === 0) {
>       console.log("Adding delay. Count: ", count);
>       await sleep(2000);
>     }
>     // read html file
>     const body = await Deno.readTextFile("./hello.html");
>     const res = {
>       status: 200,
>       body,
>       headers: new Headers(),
>     };
>     res.headers.set("Connection", "keep-alive");
>     req.respond(res);
>   }
> );
> 
> function sleep(ms: number) {
>   return new Promise((resolve) => {
>     setTimeout(resolve, ms);
>   });
> }
> ```
> 
> Now run `ab -c 100 -n 10000 http://127.0.0.1:8080/` and it will fail, where as `ab -k -c 100 -n 10000 http://127.0.0.1:8080/` works. So seems like `keep-alive` in the header is not respected

Can you explain the reason behind this sleep logic here @deepu105?

**Comment by deepu105** [comment]
Was just to emulate workload.
