### ISSUE TITLE
Deno NPM Package

### ISSUE THREAD

**Issue by bordoley** [denoland/deno#5358]
I realize this would be very meta, but i have a package I'm building that supports both node and deno as well as traditional web apps. From a strictly practical build pipeline perspective, it would be useful to be able to install deno from npm as a dev dependency.

**Comment by wojpawlik** [comment]
https://npmjs.com/deno-bin

**Comment by bartlomieju** [comment]
Closing as resolved.

**Comment by Yamboy1** [comment]
That's a very very old version of deno (v0.20.0) btw

**Comment by bartlomieju** [comment]
CC @kt3k
