### ISSUE TITLE
Remove execute permissions from std/node/fs.ts

### ISSUE THREAD

**Issue by EvanHahn** [denoland/deno#5360]
`std/node/fs.ts` has execute permissions. This appears unnecessary and is inconsistent with other files in this directory (and elsewhere).

It looks like this was introduced in e8f639ce53c5a232c84d499b0d6375a2d2ad7131. That change appears unrelated to the mode change.

Happy to make a pull request if necessary.

**Comment by bartlomieju** [comment]
That would be helpful, thanks

**Comment by EvanHahn** [comment]
Done in #5363.
