### ISSUE TITLE
std/node: add util.callbackify

### ISSUE THREAD

**Issue by EvanHahn** [denoland/deno#5366]
For completeness, `std/node/util` should include [`callbackify`][0].

I can make a pull request for this if helpful.

[0]: https://nodejs.org/api/util.html#util_util_callbackify_original

**Comment by bartlomieju** [comment]
👍 any addition to `std/node` is highly appreciated

**Comment by EvanHahn** [comment]
Will do.

Should I create new GitHub issues tracking each missing piece?

**Comment by bartlomieju** [comment]
@EvanHahn an issue per point in [`std/note` README](https://github.com/denoland/deno/tree/master/std/node) should be fine

**Comment by EvanHahn** [comment]
Added several GitHub issues for those things, and made a pull request at #5415.
