### ISSUE TITLE
std/node: add assert module

### ISSUE THREAD

**Issue by EvanHahn** [denoland/deno#5373]
For completeness, we should add [Node's `assert` module](https://nodejs.org/api/assert.html).

We should also decide whether we want to include its [legacy assertion mode](https://nodejs.org/api/assert.html#assert_legacy_assertion_mode), or if we expect that to be deprecated.

**Comment by lucacasonato** [comment]
Duplicate of #5373

**Comment by EvanHahn** [comment]
Whoops. Closing.
