### ISSUE TITLE
std/node: add readline module

### ISSUE THREAD

**Issue by EvanHahn** [denoland/deno#5387]
For completeness, we should add a polyfill for [Node's readline module](https://nodejs.org/api/readline.html).

**Comment by moulikcipherX** [comment]
Hello @EvanHahn I want to work on this issue. How can I proceed on this?

**Comment by EvanHahn** [comment]
I'll defer to @bartlomieju on this one as I'm not a Deno maintainer.

I recently put up a pull request for `util.callbackify` in #5415, which may be helpful as inspiration. I copied the tests and source code from the Node source code, and then made modifications as needed.

Again, I'm not a maintainer, but maybe that info will help.

**Comment by sant123** [comment]
Hi, I wrote this code with Deno.stdin in mind.

```typescript
const decoder = new TextDecoder();

export async function readLine() {
  let stringInput = '';

  while (true) {
    const buffer = new Uint8Array(1);
    const readStatus = await Deno.stdin.read(buffer);

    // Found EOL
    if (readStatus == null) {
      break;
    }

    const char = decoder.decode(buffer);

    // On Enter, exit
    if (char === '\n') {
      break;
    }

    stringInput += char;
  }

  return stringInput;
}
```
Credit to @lucacasonato https://github.com/denoland/deno/issues/3614#issuecomment-572194220
