### ISSUE TITLE
std/node: add stream module

### ISSUE THREAD

**Issue by EvanHahn** [denoland/deno#5389]
For completeness, we should add a polyfill for [Node's stream module](https://nodejs.org/api/stream.html).

**Comment by balupton** [comment]
What is necessary for this? I imagine it would be converting https://github.com/nodejs/readable-stream to typescript would be the largest effort?

**Comment by balupton** [comment]
still needed

**Comment by nayeemrmn** [comment]
@balupton Yes, but it's fine not to have these individual issues for each module imo.

**Comment by Soremwar** [comment]
This was implemented over two months ago
