### ISSUE TITLE
std/node: add zlib module

### ISSUE THREAD

**Issue by EvanHahn** [denoland/deno#5396]
For completeness, we should add a polyfill for [Node's zlib module](https://nodejs.org/api/zlib.html).

**Comment by hazae41** [comment]
Maybe we could add bindings to https://deno.land/x/denoflate or something similar in WebAssembly

**Comment by Mehuge** [comment]
I have been searching for a node zlib replacement specifically I need streams support.

In nodejs this would be

```javascript
   const zlib = require('zlib');
   const reader = createReadStream(from);
   const writer = createWriteStream(to, Object.assign({ mode: 0o600 }, options));
   const gzip = require('zlib').createGzip();
   const task = reader.pipe(gzip).pipe(writer);
    ...
```

As far as I can see, the current Deno implementations all either operate on files or memory.

Currently converting some backup software written in node, to Deno.  It supports backing up over the network (https) in which case the client reads the file as a stream, which is piped into gzip which is in turn piped to the socket which is then piped from the socket on the server to the filesystem.  

This can only be achieved using streams.

**Comment by crowlKats** [comment]
@Mehuge see https://github.com/denoland/deno/issues/7113

**Comment by Mehuge** [comment]
> @Mehuge see #7113

It looks like I can do stream-like stuff with fflate, so I am using that for now.
