### ISSUE TITLE
Idea: Introduce GitHub Discussions feature

### ISSUE THREAD

**Issue by galkowskit** [denoland/deno#5398]
Since Deno is getting traction and it will bring in curious people wanting to check it out (which is great!) and Discord is not an automatic go-to for questions - I think Deno (and our dear contributors) might benefit from having Discussions feature to separate issues from help questions.

https://github.com/zeit/next.js/discussions <- here is an example from Next.js Discussions. It is a Beta but should be widely available in the repository's Settings.

**Comment by kerolloz** [comment]
@galkowskit 
Great idea. I am not sure whether Discussions is available for Deno. please check [GitHub blog about discussions]( https://github.blog/2020-05-06-new-from-satellite-2020-github-codespaces-github-discussions-securing-code-in-private-repositories-and-more/#discussions)

**Comment by galkowskit** [comment]
That's weird. I'd swear I saw it somewhere as a public beta already. Well, I guess it is an idea for the future then. 😅

**Comment by wusung** [comment]
It only seems to be available for some selected open source repository.  
https://dzhavat.github.io/2020/04/04/my-thoughts-on-github-discussions.html

**Comment by bartlomieju** [comment]
Most of the discussion happen on various channels on https://discord.gg/deno and I think that's the preferable solution for now. Respectfully closing.
