### ISSUE TITLE
Deno Landing Page

### ISSUE THREAD

**Issue by MehrdadKhnzd** [denoland/deno#5401]
![image](https://user-images.githubusercontent.com/49184153/81964857-72626580-962c-11ea-9561-51ddcb6077bd.png)
Hey there! I use Wappalyzer to detect websites' technologies, and today, I caught a weird one! :)
Is this some misdetection from Wappalyzer or not? :)

**Comment by kerolloz** [comment]
What is the misdetection exactly?

**Comment by galkowskit** [comment]
LGTM. I think the page is using Next.js and Vercel. Next.js uses webpack with React and Node.js (SSR).

**Comment by kerolloz** [comment]
@MehrdadKhnzd 
please check https://github.com/denoland/deno_website2#history

**Comment by MehrdadKhnzd** [comment]
@kerolloz Thanks, that was the point. It's somehow weird for me because I expected to see Deno's landing page server written in Deno, at least with the coming of version 1.0.0. For me, it's like saying "We have something way better than Node.js but we don't trust it that much so we keep using Node.js for our own landing page", and that's somehow anti-promotion. Besides these, I really understand the problems and the shortage of tools and frameworks for Deno, and the link explains this well. Thanks again!

**Comment by kerolloz** [comment]
You're welcome @MehrdadKhnzd. Yeah, I understand your point. You're right.

**Comment by lucacasonato** [comment]
Well Node is currently the more mature project with the bigger ecosystem, so for a frontend project it is currently still better. But it will move to Deno at some point im sure.
