### ISSUE TITLE
Naming suggestion for Deno mascot

### ISSUE THREAD

**Issue by tommica** [denoland/deno#5406]
I'm not sure if this is the right place for this, but if there is no name for the [mascot](https://deno.land/logo.svg), I would like to recommend the [name that was suggested in a youtube video comment](https://imgur.com/eVIOcPr) - "Sockasaurus", because it looks like a sock puppet.

**Comment by aapoalas** [comment]
I thought it's obviously a Denosaur.

**Comment by David-Else** [comment]
I thought his name was Deno the dinosaur! If not, Sockasaurus is quite funny :)

**Comment by mattd3v** [comment]
Deno the dinosaur, correct?

**Comment by bartlomieju** [comment]
Not actionable, please continue in [`Deno's Discord`](https://discord.gg/deno)
