### ISSUE TITLE
Copy/paste does not work on Windows

### ISSUE THREAD

**Issue by silvioprog** [denoland/deno#5409]
Hi.

Steps to reproduce:

1. Download latest Deno version (`1.0.0`) from releases page and hit <kbd>Enter</kbd> inside `deno.exe`;
2. Open [this page](https://www.typescriptlang.org/play/index.html), copy the first line, paste inside Deno terminal and hit <kbd>Enter</kbd>;
3. Copy the second line in the link above and paste inside Deno terminal, hit <kbd>Enter</kbd> again.

It should print `hello world`, but the window will looks like this:

![image](https://user-images.githubusercontent.com/1456829/81972787-82148680-95f9-11ea-89c2-9bc5c82424ed.png)

cheers

**Comment by hussnainwithss** [comment]
Hello so i tried this and yes it does not work, but i manually typed the type script code and it still didn't produce any output. whereas the JS equivalent of the code produces output.

**Comment by manisaiprasad** [comment]
It is working for me. I just copied and right clicked on the command line to past it

![Capture](https://user-images.githubusercontent.com/18515609/82106847-471d6a80-9741-11ea-8281-934746576e96.PNG)

**Comment by silvioprog** [comment]
@manisaiprasad Please notice my issue is related to TypeScript code inside Deno, not pure JavaScript which works properly.

**Comment by JohanWinther** [comment]
Typescript is not supported in the REPL (#1158), which is why your example is not writing "hello world" as you would expect.
