### ISSUE TITLE
More rich assertion errors?

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#541]
Given that the assertion pattern is the standard way for helping ensure robust code for deno, the standard `Error` class is a bit limited.  Would it make sense create a more richer `AssertionError` similar to what is used by [Node.js](https://github.com/nodejs/node/blob/43ee4d692afb7bae224e529c6088d3890b4ea31f/lib/internal/assert.js#L185-L270) or [Chai](https://github.com/chaijs/assertion-error/blob/master/index.js)?  In particular, value diffing and using a stack start function to make the stack traces a bit more logical are quite useful.

**Comment by ry** [comment]
Sure. Let's wait for #529 to land tho - as it will dictate the organization of exceptions.

**Comment by ry** [comment]
I think we have better errors now? Please open a new, more specific, issue if there's something still todo here.
