### ISSUE TITLE
import from `tslib` support in deno standard library

### ISSUE THREAD

**Issue by southpolesteve** [denoland/deno#5427]
I have a few modules that look like they should work with deno, except that they import from `tslib`. It looks like this was addressed in a PR, but never merged https://github.com/denoland/deno/pull/227. Would the core team be open to reconsidering a similar PR to what was closed?

**Comment by aadamsx** [comment]
I’m going to be using Azure CosmosDB on my next project and this change is needed to get the relevant lib to incorporate Deno.

**Comment by kitsonk** [comment]
@southpolesteve that PR didn't do what you wanted that PR to do.  It dealt with how internal Deno code would have worked and it wouldn't have been available for runtime code persay.

Though I can see the value in consuming already transpiled TypeScript files that import from `tslib`. A very logical feature request that just hasn't come up before.  Do you have a simple example file of what your emit looks like for one of these files?  We can certainly build `tslib` into the Deno binary and have them available for importing.

**Comment by kitsonk** [comment]
(as a temporary work around, I believe you could use `--unstable` and import maps to take the "`tslib`" import and remap it to somewhere else where tslib existed).

**Comment by southpolesteve** [comment]
Makes sense. Here is a simple example that would import `tslib` if `importHelpers` was turned on:

Source:
``` js
const foo = {}
const { bar, ...bax} = foo
```

Emitted code:
``` js
"use strict";
import { __rest } from 'tslib'
const foo = {};
const { bar } = foo, bax = __rest(foo, ["bar"]);
```

**Comment by bartlomieju** [comment]
@kitsonk is this issue something that you still want to support?

**Comment by kitsonk** [comment]
It is something that is fairly trivial to support with import maps, for those using already emitted TypeScript. Feels like something we should add to the manual of how to use an import map to do this.
