### ISSUE TITLE
Translation to Portuguese [pt/br]

### ISSUE THREAD

**Issue by glaucia86** [denoland/deno#5435]
Hi Denors!
We are from Brazil and we would like to help all of you to translate to Portuguese **[The Manual](https://deno.land/manual/)**.

So, we would like to know, if could we help all of you to make the translation to Brazilian Portuguese?
If so, I can make some movements with the Brazilian Community to help to translate it.

cc: @ry @fd @codeflo @mrkurt @yosmoc

**Comment by pedroknup** [comment]
Good one. You can count on me for that

**Comment by ry** [comment]
I'm happy to have translations. We can provide a link to it in the manual. But this should be maintained out of repo.

**Comment by guiananias** [comment]
Hi, how can I help with translation to PT-BR?

You can count on me! =)

**Comment by paulocordeiro** [comment]
great idea, I'm here!

**Comment by glaucia86** [comment]
@ry sorry for the delay. I was in the MS Build event.
That's awesome news!
Maybe we can do as same as we did with last year when the Brazilian Community translated the React documentation to Portuguese, creating a different branch for it. What do you think?

> if you want to see how we organize with the React Translation you can see **[HERE](https://github.com/reactjs/pt-BR.reactjs.org/issues/1)**

**Comment by jonathangaldino** [comment]
Oh yeah! How can I help?

The organization behind the translation of React was awesome. I hope it get implemented here and we can help by choosing sections :D

**Comment by strokirus** [comment]
Count on me

**Comment by imakecodes** [comment]
How can we help?

**Comment by eialanjones** [comment]
let's do it

**Comment by FranOnRails** [comment]
Count on me/2

**Comment by khaosdoctor** [comment]
@glaucia86 Let's make that happen! I'll be happy to help with anything you need! 

@ry Is it possible to use the https://github.com/denoland/doc_website to translate it?

**Comment by raryson** [comment]
Count with me o/

**Comment by alexsandro-xpt** [comment]
Me too!

**Comment by dtgfranca** [comment]
Count with me!!

**Comment by Jhonatanup** [comment]
Lets do it!

**Comment by dminella** [comment]
Count on me :)

**Comment by callebdev** [comment]
You can count on me like 1, 2, 3... 

> Bora fazer isso

**Comment by MarcusMann** [comment]
I'll help.

**Comment by lolivei** [comment]
You can count on me!

**Comment by DiegoTeles** [comment]
Come on, I'm together!
You can count on me

**Comment by jsaintz** [comment]
Come on, 
You can count on me :D

**Comment by glaucia86** [comment]
Waiting for the next steps with @ry folks.

cc: @khaosdoctor

**Comment by khaosdoctor** [comment]
Let's just wait for the final guidance here so we can make it happen :)

**Comment by ry** [comment]
We don’t have the capacity to maintain translations in the main repo. Once there is something up, send a PR adding a link to the manual.

**Comment by FelipeAlvesSilva** [comment]
Count with me 🎉

**Comment by FelipeAlvesSilva** [comment]
Count with me :)

**Comment by arnonrdp** [comment]
Hey guys, let's make it happen.

You can count on me. What do you guys need right now?
