### ISSUE TITLE
Is there currently any measure to use Deno with Rust.

### ISSUE THREAD

**Issue by sanket143** [denoland/deno#5443]
Ryan, in his talk in JS Fest 2019, he mentions Deno does have a lower-level API.
Which gives us a way to send typed arrays back and forth from v8.

```rust
fn dispatch {
    &mut self,
    control: &[u8],
    zero_copy_buf: deno_buf
} -> (bool, Box<Op>)
```
https://crates.io/crates/deno

**Comment by SyrupThinker** [comment]
You are looking for the unstable plugin system.
There is not much documentation, but you can take a look at [this](https://github.com/denoland/deno/tree/master/test_plugin) example.

**Comment by ry** [comment]
Also look here https://crates.io/crates/deno_core
