### ISSUE TITLE
Regex named groups doesn't work properly

### ISSUE THREAD

**Issue by xReveres** [denoland/deno#5444]
Hi, I'm trying to fetch named groups from string with regex.
String: `/cat/like/milk/`
Regex: `/\/(?<arg>[a-zA-Z0-9_-]+)\/(?<catch>[a-zA-Z0-9_-]+)\/(?<test>[a-zA-Z0-9_-]+)/`
Example code:
```javascript
const a = "/cat/like/milk/".match(/\/(?<arg>[a-zA-Z0-9_-]+)\/(?<catch>[a-zA-Z0-9_-]+)\/(?<test>[a-zA-Z0-9_-]+)/);
console.log(a);
```
NodeJS returns:
```
[
  '/cat/like/milk',
  'cat',
  'like',
  'milk',
  index: 0,
  input: '/cat/like/milk/',
  groups: [Object: null prototype] { arg: 'cat', catch: 'like', test: 'milk' }
]
```
Deno returns:
```
[ "/cat/like/milk", "cat", "like", "milk" ]
running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out (0ms)
```

So, Deno returns array without groups, which I needs

NodeJS version: `v13.7.0`
Deno version: `deno 1.0.0
v8 8.4.300
typescript 3.9.2`

**Comment by kitsonk** [comment]
This is just an inspection problem, as the return result is being improperly determined to be an array.

```js
const a = "/cat/like/milk/".match(/\/(?<arg>[a-zA-Z0-9_-]+)\/(?<catch>[a-zA-Z0-9_-]+)\/(?<test>[a-zA-Z0-9_-]+)/);
console.log(a.groups);
```

Will output:

```
{ arg: "cat", catch: "like", test: "milk" }
```

**Comment by SyrupThinker** [comment]
Also visible by using `console.table`.
> a = "/cat/like/milk/".match(/\/(?<arg>[a-zA-Z0-9_-]+)\/(?<catch>[a-zA-Z0-9_-]+)\/(?<test>[a-zA-Z0-9_-]+)/);
[ "/cat/like/milk", "cat", "like", "milk" ]
> console.table(a)
┌─────────┬───────┬────────┬────────┬───────────────────┐
│ (index) │  arg  │ catch  │  test  │      Values       │
├─────────┼───────┼────────┼────────┼───────────────────┤
│    0    │       │        │        │ "/cat/like/milk"  │
│    1    │       │        │        │       "cat"       │
│    2    │       │        │        │      "like"       │
│    3    │       │        │        │      "milk"       │
│  index  │       │        │        │         0         │
│  input  │       │        │        │ "/cat/like/milk/" │
│ groups  │ "cat" │ "like" │ "milk" │                   │
└─────────┴───────┴────────┴────────┴───────────────────┘
```

**Comment by xReveres** [comment]
Okay, thanks for help :)
I'm tested with JSON.stringify, but without expected results, now i know to try also console.table 🥇

**Comment by kitsonk** [comment]
There is still a bug here... inspection for RegularExpression array results is incorrect and should be fixed.
