### ISSUE TITLE
Deno.listen should return a promise?

### ISSUE THREAD

**Issue by manikawnth** [denoland/deno#5445]
Why is `Deno.listen()` returning a `Listener` and not a `Promise<Listener>` while its underlying tokio implements binding to a port completely asynchronous? 

Is there any specific reason?

**Comment by ry** [comment]
Because the listen syscall is sync. I guess tokio conflates listening and dns resolution? I'm not sure why they have it async. We also would do DNS resolution in this path, but I don't think listen() is ever in the hot path. Having this synchronous makes more sense.

**Comment by manikawnth** [comment]
The question was posed under wrong assumption that underlying `socket()` syscall was non-blocking. 

But learnt that tokio, indeed, uses it for dns lookup. And deno doesn't handover nslookup to tokio but done by rust standard library.
Closing this. Thanks.
