### ISSUE TITLE
Excited about Deno, but...

### ISSUE THREAD

**Issue by TriSysBusinessSoftware** [denoland/deno#5447]
_A picture is worth a thousand words._

Having spent 20 minutes learning about Deno this morning, I really feel that a few diagrams showing the architecture and how this fits in with the aspirations of future Deno developers would be a worthwhile investment.
Just an idea.

G.

**Comment by stefk** [comment]
There's already some material in the docs folder: https://github.com/denoland/deno/blob/master/docs/contributing/architecture.md#schematic-diagram.

**Comment by ry** [comment]
Probably we could use some better/updated diagrams. Thanks for the reminder. 

Closing just because this isn't very actionable - but thanks for reaching out.

**Comment by TriSysBusinessSoftware** [comment]
Thanks for replying Ryan. Typically your early adopters will persevere with your evolving code base, however in order to attract the early/late adopters, technology needs to be well documented with diagrams to pique the interest of those with less time to evaluate, who have to make recommendations to senior management who are often non-technical. This is where your pictures are most valuable. Think about tech journalists too. They love images, as do their readers.

**Comment by GarryLowther** [comment]
Hi Ryan
Congratulations on your recent investment.
Do you have a copy of your pitch deck?

Kind regards, Garry
