### ISSUE TITLE
Not getting Error when port is used by another process

### ISSUE THREAD

**Issue by samsif** [denoland/deno#5452]
Hello,
Given: a running deno app on port 8000
When: running another deno app on the same port
Then: it sames all right, but the second app is not run yet and there is no error indicating that the port 8000 is used by another process

**Comment by kitsonk** [comment]
Could you provide some example code.

**Comment by samsif** [comment]
`import { serve } from "https://deno.land/std@0.50.0/http/server.ts";
const s = serve({ port: 8000 });
console.log("http://localhost:8000/");
for await (const req of s) {
  req.respond({ body: "Hello World\n" });
}
`

run that code and 

`import { Application, Router } from "https://deno.land/x/oak/mod.ts";
const books = new Map<string, any>();
books.set("1", {
  id: "1",
  title: "The Hound of the Baskervilles",
  author: "Conan Doyle, Author",
});
const router = new Router();
const variableName = "Sifast";
router
  .get("/", (context: any) => {
    context.response.body =
      `<!DOCTYPE html><html><h2 style="color:red"> hello ` +
      variableName +
      ` </h2></html>`;
  })
  .get("/book", (context: any) => {
    context.response.body = Array.from(books.values());
  })
  .get("/book/:id", (context: any) => {
    if (context.params && context.params.id && books.has(context.params.id)) {
      context.response.body = books.get(context.params.id);
    }
  });
const app = new Application();
app.use(router.routes());
app.use(router.allowedMethods());
console.log(`server listening on http://localhost:8000`);
await app.listen({ port: 8000 });
`

run that also on the same port 8000, it works and for the two apps i had 
`PS E:\projet\deno> deno run --allow-net .\aok.ts
Compile file:///E:/projet/deno/aok.ts
server listening on http://localhost:8000`

but on the localhost:8000 only the first app is running, and there is no error in terminal telling that the port 8000 is already in use

**Comment by samsif** [comment]
![222222](https://user-images.githubusercontent.com/37840234/82059754-c457c980-96c6-11ea-9fb7-c2bb00356447.JPG)
For exemple, i run this code you can see at the console that server is listening at port 8000, i don't have any errors.
But actually, another code (another deno app, but it could another external process) is already run at the same port.

**Comment by pitust** [comment]
Can't reproduce it with stock HTTP server, running ` deno run --allow-net --allow-read https://deno.land/std/http/file_server.ts` twice gives me `error: Uncaught AddrInUse: Address already in use (os error 98)`. propably a bug in the third-party module

**Comment by kitsonk** [comment]
Yes, could you please open an issue in oak.

**Comment by piscisaureus** [comment]
What OS are you using?

(Some background: I have noticed that this happens (or rather, the expected error doesn't happen) when running under WSL. But when running on "real" linux and on "normal" windows it works as expected so this looks like a bug in WSL.)

**Comment by samsif** [comment]
After verification, it is related with aok module,
