### ISSUE TITLE
Needed: Intellij Plugin

### ISSUE THREAD

**Issue by luckycreationsindia** [denoland/deno#5453]
Hi,

I usually work and get used to IntelliJ Products. I can work on other IDEs too but it's convenient to use IntelliJ Webstorm or IntelliJ Idea for me.

**Comment by kerolloz** [comment]
Hey @luckycreationsindia,
Please check https://deno.land/manual/getting_started/setup_your_environment#editors-and-ides
>Support for JetBrains IDEs is not yet available, but you can follow and upvote these issues to stay up to date:
>
 >   https://youtrack.jetbrains.com/issue/WEB-41607
    https://youtrack.jetbrains.com/issue/WEB-42983
    https://youtrack.jetbrains.com/issue/WEB-31667

**Comment by luckycreationsindia** [comment]
Thanks

Will check that out.

**Comment by prigara** [comment]
Hi @luckycreationsindia, the plugin is now available: https://plugins.jetbrains.com/plugin/14382-deno

**Comment by luckycreationsindia** [comment]
Awesome... Thanks for informing...😍
