### ISSUE TITLE
Suggestion: Denolander as the official nickname for fellow Deno users

### ISSUE THREAD

**Issue by bobaekang** [denoland/deno#5455]
As an open source project, its community of users is a central part of the Deno project. So it would certainly make sense to pay attention to the community-building aspect of the project. A suggestion to add a GitHub Discussions feature (#5398) is just one example that speaks to the importance of building and engaging the community.

With that in mind, I think it's quite important(!) for Deno community to have an endearing term to refer to fellow Deno users--like Gopher in the Go community (though in this case it also refers to the official mascot itself). I've seen "denoer"(https://github.com/denoland/deno/issues/1564#issue-402015312) and "Denor"(https://github.com/denoland/deno/issues/5435#issue-618701711) used before, but since there is no consensus around this yet, I'd like to suggest **Denolander** 🦕. I think it reads better and also feels natural given the name of this GitHub Organization for the Deno project as well as the official website: https://deno.land/.

**Comment by NathanSMB** [comment]
How about "Denosaurs"?

[Don't lose your denosaur.](https://i.pinimg.com/originals/49/5b/eb/495bebe19213063e4b9fe6fea9a26ceb.png)

**Comment by ashx404** [comment]
Denorider lol.

**Comment by fox-cat** [comment]
ive heard denosaurs, denosaurases, denolanders ... i dont think there should be an "offical" name persay, community members should just call themselves what they want

**Comment by buckle2000** [comment]
"deno users" is as long as "Denosaurs". Is that a nick name?

**Comment by fox-cat** [comment]
denosaurs  is more playful
