### ISSUE TITLE
Deno bundle a incompatible javascript

### ISSUE THREAD

**Issue by Wallacy** [denoland/deno#5463]
server.ts
```javascript
import { serve } from "https://deno.land/std/http/server.ts";
const s = serve({ port: 8000 });
console.log("http://localhost:8000/");
for await (const req of s) {
  req.respond({ body: "Hello World\n" });
}
```
then:
```bash
deno bundle server.ts bundle.js
```
```bash
$ deno run --allow-net bundle.js
error: Uncaught SyntaxError: Unexpected reserved word
        for await (const req of s) {
            ~~~~~
    at file:///home/snews/Documents/Stuffs/Deno/bundle.js:5456:13
```

Of course `deno run --allow-net server.ts` works as expected

By the way, will be nice the bundle file be more "minified", all comments and other disposable things is there. Also appear to be good to preserve the shebang on files like: `https://deno.land/std/http/file_server.ts`

**Comment by bartlomieju** [comment]
Top-level-await is not yet supported in bundles. Let's continue in original issue: https://github.com/denoland/deno/issues/4207
