### ISSUE TITLE
[std/fmt] bright?

### ISSUE THREAD

**Issue by pitust** [denoland/deno#5464]
Will there be a way of setting text as bright in fmt?
AFAIK this is done by sending `\x1b[1m`

**Comment by pitust** [comment]
Oh, it looks like `\x1b[1m` can be interpreted as EITHER bold or bright

**Comment by Alhadis** [comment]
`\x1B[1m` is the code for bold text. Not every display is capable of rendering bold text, however, so some terminal drivers render "bold" text in a brighter colour by way of emphasis.

You might want to [keep this handy](https://en.wikipedia.org/wiki/ANSI_escape_code#SGR_parameters). 😉

**Comment by bartlomieju** [comment]
ANSI sequences for colors are available in https://deno.land/std/fmt/colors.ts 

As pointed by @Alhadis rendering bold text is not available in all terminals.
