### ISSUE TITLE
std: add dtls module

### ISSUE THREAD

**Issue by beriberikix** [denoland/deno#5479]
Consider adding DTLS to go with the existing UDP support and proposed TLS module (#5391.) This has been a long-standing gap in the Node world (nodejs/node#2398).

**Comment by bartlomieju** [comment]
That would most likely be a `cli` feature

**Comment by hironichu** [comment]
Just sending this back up on the suggestion list, as I have been working on making a webrtc library for deno, the biggest task i'm facing right now is passing the UDP stream onto many functions to apply the DTLS layer on top of it, could be great if this was in the STD

OpenSSL in rust has an function where it takes a stream and depending on the settings (here dtls) it returns the stream after the handshake

```rs
...
//Create a Certificate and a key for the handshake and pass them to the ssl builder


       let mut ssl_acceptor_builder = SslAcceptor::mozilla_intermediate(SslMethod::dtls())?; 
  //example not secure here, this means the server doesnt check Client certificate in order to accept arbitrary client.
        ssl_acceptor_builder.set_verify(SslVerifyMode::NONE);

        ssl_acceptor_builder.set_private_key(&key)?;
        ssl_acceptor_builder.set_certificate(&x509)?;
        let ssl_acceptor = ssl_acceptor_builder.build();
```
( this bit of code is from : https://github.com/kyren/webrtc-unreliable/ , which rely only on being a dedicated server and support only datachannels )

Could this be used ? idk.. but it could be great for a start, DTLS would allow basic datachannel support through WebRTC meaning a very fast communication method between a Deno server and a browser.

**Comment by lucacasonato** [comment]
We are not going to do `dtls` - we will however ship Quic and HTTP/3 at some point in the future, which are direct replacements for `dtls`. https://github.com/denoland/deno/issues/1558
