### ISSUE TITLE
Property 'openPlugin' does not exist on type 'typeof Deno' in 1.0.0

### ISSUE THREAD

**Issue by treeandgrass** [denoland/deno#5487]
console.log(Deno.openPlugin)

Property 'openPlugin' does not exist on type 'typeof Deno'.

**Comment by uki00a** [comment]
`Deno.openPlugin` is unstable.
You need the `--unstable` flag as follows:

```shell
$ deno run --unstable ./mod.ts
```

https://github.com/denoland/deno/blob/master/docs/runtime/stability.md
