### ISSUE TITLE
Use the same execution environment for REPL

### ISSUE THREAD

**Issue by buckle2000** [denoland/deno#5504]
Currently, the following code will run without error in deno REPL but will error out as a script:
```
# a.js
let a = {}
Object.preventExtensions(a)
a.c = 1
```

This shouldn't be the case.

**Comment by kitsonk** [comment]
Yeah, forgot REPL was evaluated as a script.  Fix should be easy.

**Comment by buckle2000** [comment]
I can't use top level await in REPL too.

**Comment by kitsonk** [comment]
@buckle2000 that is #3700.
