### ISSUE TITLE
Set gid/uid for subprocess

### ISSUE THREAD

**Issue by p8nut** [denoland/deno#5506]
I am not sure that i should create a new Issue (may be linked with #5501)

I am working on a program that watch over some processes but i would like to limit the rights of the child process before execution.

it is possible with nodejs to set an uid and/or a gid so then, just before the process is execve the parent process call setuid and/or setgid to drop privileges of the child.

[node way](https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback)

**Comment by v6** [comment]
> I would like to limit the rights of the child process before execution.

This is a sentiment I can co-sign.

**Comment by bartlomieju** [comment]
Should be possible to do using `CommandExt` API (for Unix of course):
https://doc.rust-lang.org/std/os/unix/process/trait.CommandExt.html
