### ISSUE TITLE
No way to start REPL with --unstable flag

### ISSUE THREAD

**Issue by piscisaureus** [denoland/deno#5508]
Or am I missing something?

**Comment by bartlomieju** [comment]
Do you mean REPL? `deno --unstable`?

**Comment by kitsonk** [comment]
Not missing something... I suspect when we de-hacked `run` it got missed.

**Comment by nayeemrmn** [comment]
`deno repl --unstable`?

**Comment by piscisaureus** [comment]
Ehh - I meant repl indeed.

**Comment by buckle2000** [comment]
I think you just use `deno repl --unstable`.

**Comment by piscisaureus** [comment]
> I think you just use `deno repl --unstable`.

Right, that does work indeed. I had a brain fart and tried to run "deno cli --unstable".
