### ISSUE TITLE
Feature request: Deno, compile to native binary

### ISSUE THREAD

**Issue by datdinhquoc** [denoland/deno#5512]
![image](https://user-images.githubusercontent.com/40449395/82129166-0aa64900-97eb-11ea-80ab-a5b289b8f19d.png)
As in the diagram above, Deno is still based on V8 Engine which is JavaScript, and JS is non-typed, this will make the run-time execution slow.

Is it possible to compile Deno to native binary for performance, coz Deno runs TypeScript that is typed? For example, compile through LLVM?

**Comment by kitsonk** [comment]
v8 does amazing things in optimising JavaScript.  It will always do a better job of optimising JavaScript than almost everyone would do trying to do that themselves.  It is a lot more than just trying to "translate" JavaScript (or TypeScript) to op codes, you have to provide all the expectations of a JavaScript runtime, like a GC system, etc.

We are very unlikely to ever not use v8.

**Comment by pirix-gh** [comment]
@kitsonk I'm wondering if it would be possible to optimize V8 thanks to the insights given by the types (for inline caching), and other code optimizations that could be done by the JS/SWC compiler. Do you think that this would be possible in the long term future

**Comment by kitsonk** [comment]
The Chromium team experimented with this a while back (strong mode R.I.P. 2015-2016) and it didn't and so they dropped it.

**Comment by Alhadis** [comment]
@pirix-gh As an aside, if you're interested in compiling JavaScript to standalone binaries, you should check out [QuickJS](https://bellard.org/quickjs/). It lends itself well to embedding.

As for V8... I echo @kitsonk's answer above. I doubt V8 would ever be suitable for compiling standalone binaries (size-efficient ones, at least). You've got the Ignition interpreter, lazy compilation, bytecode flushing, all sorts of memory-juggling techniques, and numerous other factors relevant in a VM-like environment, but not a precompiled binary.

Though it'd probably be fun to screw around with TurboFan by marking every function as hot, eagerly compiling everything, and treating deoptimised code as a compilation error. 😁

**Comment by bartlomieju** [comment]
Closing in favor of https://github.com/denoland/deno/issues/986

**Comment by kitsonk** [comment]
@Alhadis QuickJS is order of magnitudes slower than V8.  It maybe suitable for some embeddable workloads where there is tight control over the JavaScript it runs, but isn't suitable for Deno which needs to run general performance JavaScript.

**Comment by Alhadis** [comment]
@kitsonk I was bringing up QuickJS in case it was of interest to the OP. Read my response a bit closer:

> As an aside, **if you're interested in compiling JavaScript to standalone binaries**

At no point did I imply anything about engine performance.

**Comment by kitsonk** [comment]
@Alhadis you mentioned someone who was not the OP.  The person you mentioned questioned if performance could be improved by using types.  So maybe read the questions a bit closer?

**Comment by Alhadis** [comment]
Right, so I copy+pasted the wrong username when writing that. My mistake.

Regardless, it should have been obvious that my reply was tangential to the conversation.

**Comment by kitsonk** [comment]
Well the OP said:

> As in the diagram above, Deno is still based on V8 Engine which is JavaScript, and JS is non-typed, this will make the run-time execution slow.

Your suggestion would make runtime execution even slower... So in any context your thoughts were tangential to the conversation. 🤷

**Comment by Alhadis** [comment]
Jesus fucking Christ, I *said* it was an aside.

I regret posting. You're a fair dinkum gronk.

**Comment by slaveofcode** [comment]
I was expecting that deno would be possible to compile to binary, I'm a big fan of a single binary format (inspired by Go) which offers simplicity on fast scaling experience and small size (k8s)
