### ISSUE TITLE
Deno hangs on stdout.write

### ISSUE THREAD

**Issue by pirix-gh** [denoland/deno#5515]
I've noticed that Deno process never ends on this code

```ts
const te = new TextEncoder();

for (const file of files) {
  Deno.stdout.write(te.encode(file + "\n"));
}

console.log("end"); // never reaches
```

Where `files` is a very long list of file paths from my PC.

**Comment by jdiamond** [comment]
I think the `write` method is async. Can you try `await`'ing on each write? Might give the event loop a chance to breathe.

**Comment by cknight** [comment]
As stated above, write is async and doesn't do well with a flood of requests all at once. Either `await` the write or switch to `writeSync`.
