### ISSUE TITLE
Add prompt after "Compile" when compilation finishes and module runs

### ISSUE THREAD

**Issue by maxtnuk** [denoland/deno#5529]
When i run server with oak, the output looks like this
```bat
deno run --allow-net app.ts 
Compile file:///home/maxtnt/code_lab/typescript/app.ts
..some output
```
i think it would be good to add some output comment that compile is finished like rust

**Comment by malwarebo** [comment]
If there is any issue with compilation you will get an error straight there in the terminal and the build fails.
Since you are running a server and in order to see what you want in terminal, you can add a simple `console.log()` statement.

**Comment by kitsonk** [comment]
I agree... there is a lot of "noise" anyways when that is occurring.  It feels like if you want to know when your code starts running, you would `console.log("I've started running...");`

**Comment by malwarebo** [comment]
But yes a default prompt would be better.

**Comment by kitsonk** [comment]
Why?

**Comment by bartlomieju** [comment]
I agree with @kitsonk on this one, Deno has minimalistic output by default and we don't want to add more prompts.
