### ISSUE TITLE
window.onerror should be libdeno.setGlobalErrorHandler()

### ISSUE THREAD

**Issue by ry** [denoland/deno#553]
Although `window.onerror` is the proper DOM way to intercept and process errors, it's unwieldy as a global setter and requires us breaking thru our defined abstraction.

To get started here's a pointer to the C++ code which implements it:
https://github.com/denoland/deno/blob/27ef77e31b9bcaa026c1196b838858b0e9a750b2/libdeno/binding.cc#L41

The easiest way to do this is to first get this test working:
https://github.com/denoland/deno/blob/27ef77e31b9bcaa026c1196b838858b0e9a750b2/libdeno/libdeno_test.js#L125-L136

#518 should land first - so start any work on top of that branch.

**Comment by kt3k** [comment]
@ry I don't get the sentence `window.onerror should be libdeno.setGlobalErrorHandler()`.
Should we remove the handling of `window.onerror`? What interface should be exposed to the user for uncaught error handling? (I think `libdeno` is not exposed to the user. Is that right?)

**Comment by ry** [comment]
@kt3k Sorry that wasn't very clear. We use onerror internally to apply source maps to error stack traces. Because this is a very internal thing, I want it to look more internal. So instead of setting onerror, the deno code might do this:
```
libdeno.setGlobalErrorHandler((message, source, line, col, error) => {
  // blah
});
```
Later we will think about how deno can expose the DOM `onerror` API to users... but that's a different situation. Make sense?

**Comment by ry** [comment]
@kt3k The implementation should be quite similar to `libdeno.recv`, which also takes a callback.
https://github.com/denoland/deno/blob/59231d74b5e275b6cb1c7a551c3382202c3f0d9e/libdeno/binding.cc#L288-L290
https://github.com/denoland/deno/blob/59231d74b5e275b6cb1c7a551c3382202c3f0d9e/libdeno/internal.h#L15

**Comment by kt3k** [comment]
@ry Thanks! Makes perfect sense now! 😀
