### ISSUE TITLE
[Question] Hello world of TCP sample is not output

### ISSUE THREAD

**Issue by AkifumiSato** [denoland/deno#5534]
I tried a sample TCP server along with the manual.

But I couldn't get the 'Hello world' output.

Is this an environment dependent issue?

https://deno.land/manual/getting_started/first_steps#a-simple-tcp-server

OS: MacOS Mojave
deno version: 
```
deno --version
deno 1.0.0
v8 8.4.300
typescript 3.9.2
```

**Comment by buckle2000** [comment]
Need more info to reproduce.

**Comment by AkifumiSato** [comment]
I'm sorry, I made a basic mistake about the 'nc' command.

No problem.
