### ISSUE TITLE
Property 'compile' does not exist on type 'typeof Deno'

### ISSUE THREAD

**Issue by kacluk123** [denoland/deno#5536]
I have a problem with using compile. Console throws an error.
`error: TS2339 [ERROR]: Property 'compile' does not exist on type 'typeof Deno'.`

**Comment by buckle2000** [comment]
That is unstable API. Use `--unstable` to allow that.

**Comment by heathweaver** [comment]
Following this tutorial (https://dev.to/craigmorten/deno-bundle-for-server-side-rendered-react-11c2) I get the error in VS Code: Property 'compile' does not exist on type 'typeof Deno'.deno-ts(2339)

My settings.json
```
{
  "deno.enable": true,
  "deno.lint": true,
  "deno.unstable": true,
  "deno.importMap": "./import_map.json"
}
```
deno --version 
deno 1.19.0 (release, x86_64-apple-darwin)
v8 9.9.115.7
typescript 4.5.2

I can run deno compile without issue. 

The command to run the file: deno run --allow-read --allow-net --unstable ./compile.ts

**Comment by bartlomieju** [comment]
`Deno.compile()` was replaced by [`Deno.emit()`](https://doc.deno.land/deno/unstable/~/Deno.emit)
