### ISSUE TITLE
Can't see a compiled file.

### ISSUE THREAD

**Issue by kacluk123** [denoland/deno#5537]
Deno.compile doesn't throw anny error but i can't see a compiled file in my dist folder.

```
const [errors, emitted] = await Deno.compile("hello.ts", undefined, {
  lib: ["esnext"], // include "deno.ns" for deno namespace
  outDir: "dist",
});

if (errors) {
  console.log("There was an error:");
  console.error(errors);
} else {
  console.log(emitted); // normally we would write the file
}
```

Console output:
`{
 ./dist/hello.js.map: "{\"version\":3,\"file\":\"hello.js\",\"sourceRoot\":\"\",\"sources\":[\"file:///C:/Users/sakuy/Desktop/DENO%20TES...",
 ./dist/hello.js: "\"use strict\";\n//# sourceMappingURL=hello.js.map"
}`

**Comment by SyrupThinker** [comment]
This is because that function doesn't write to disk.
The return value is everything you get.
You need to create the files yourself where key is the path and value is the content.

**Comment by kacluk123** [comment]
> This is because that function doesn't write to disk.
> The return value is everything you get.
> You need to create the files yourself where key is the path and value is the content
How to do that, is this mentioned in docs?

**Comment by bartlomieju** [comment]
@kacluk123 https://doc.deno.land/https/raw.githubusercontent.com/denoland/deno/master/cli/js/lib.deno.unstable.d.ts#Deno.compile

**Comment by bartlomieju** [comment]
Closing as it's intended API behavior.
