### ISSUE TITLE
fail to download remote .ts or .js when using proxy

### ISSUE THREAD

**Issue by unbyte** [denoland/deno#5538]
when proxy is enabled:
```bash
> deno run --allow-all .\index.ts
Compile file:///****/index.ts
Download https://deno.land/std/http/server.ts
error: Uncaught Http: error sending request for url (https://deno.land/std/http/server.ts): error trying to connect: invalid dnsname
```
and after disable proxy it works normally.

**Comment by kidonng** [comment]
Your proxy setup seems to have a problem. DNS error has nothing to do with Deno itself.

**Comment by bartlomieju** [comment]
@unbyte if you're using a proxy then most likely you'll need to supply custom certificate - this can be done using `--cert` flag to point deno to PEM file.

**Comment by bartlomieju** [comment]
Closing as stale. Please reopen if problem persists.
