### ISSUE TITLE
Upgrade JavaScript deps to latest versions. [Aug 2018]

### ISSUE THREAD

**Issue by ry** [denoland/deno#554]
Edit the package.json https://github.com/denoland/deno/blob/master/package.json
Run `./tools/sync_third_party.py`
And send a PR to https://github.com/denoland/deno_third_party for the changes.

Ensure that `./tools/build.py && ./tools/test.py` passes.

**Comment by SilverLeaves** [comment]
Nice initiative, but really?  ๑乛◡乛๑I really want to have a try!

**Comment by satyarohith** [comment]
Hey @SilverLeaves do you mind if I make a PR for this? :)

**Comment by acconrad** [comment]
should this be updated for September now? i tried doing these instructions but when i called `./tools/build.py && ./tools/test.py` after running the sync script I get an error:

```bash
 ? > ./tools/build.py     

ninja: Entering directory `/Users/acconrad/Code/personal/deno/out/debug'
[1/1] Regenerating ninja files
FAILED: build.ninja
../../third_party/v8/buildtools/mac/gn --root=../.. -q gen .
/bin/sh: ../../third_party/v8/buildtools/mac/gn: No such file or directory
ninja: error: rebuilding 'build.ninja': subcommand failed
```

**Comment by ry** [comment]
Sorry about this - actually this is something I or @piscisaureus need to do just due to the overhead of dealing with deno_third_party. Thank you @satyarohith for looking into this.
