### ISSUE TITLE
(cli/js/lib.deno.ns.d) - No function to copy directories in Deno namespace

### ISSUE THREAD

**Issue by clarnx** [denoland/deno#5546]
Files can be copied from source to destination by using functions `copyFile` or `copyFileSync` in the **Deno** namespace. However there is no function to copy directories. 
I suggest a function to be added to the **Deno** namespace which will have the ability to copy directories 
_**e.g**_. `Deno.copyDir` or `Deno.copyDirSync`

**Comment by bartlomieju** [comment]
Available in `std/fs/copy.ts`: https://doc.deno.land/https/deno.land/std/fs/copy.ts

**Comment by clarnx** [comment]
> Available in `std/fs/copy.ts`: https://doc.deno.land/https/deno.land/std/fs/copy.ts

Yeah but if i'm writing a command-line script I would want to use functions in the Deno namespace without importing the **fs** module.
`Deno.copyFile` or Deno.copyFileSync exits in the **Deno** namespace so why not just also add Deno.copyDir  or Deno.copyDirSync to the namespace?

**Comment by bartlomieju** [comment]
Closing as won't fix, we've got no plans to add those helpers to `Deno` namespace.
