### ISSUE TITLE
why are source code written by rust, not c++? why std port to go, not rust?

### ISSUE THREAD

**Issue by anlexN** [denoland/deno#5547]
I'm reviewing deno source code, i have many problems. sorry.

**Comment by kitsonk** [comment]
We considered the Go std library APIs to be good set of ergonomic APIs.

This issue tracker is for tracking issues with Deno, not general questions.  Please use https://discord.gg/deno or StackOverflow for general questions.

**Comment by anlexN** [comment]
but in the [deno](https://deno.land/) website, can you make a faq list answering this quest?
