### ISSUE TITLE
Error installing deno with cargo on windows 10

### ISSUE THREAD

**Issue by lemaguilera** [denoland/deno#5554]
![image](https://user-images.githubusercontent.com/17011087/82153724-e0767a80-982e-11ea-8a21-84569648ecd1.png)

**Comment by kitsonk** [comment]
You aren't "installing" you are building Deno.

As the error says... "Python was not found"

Building Deno requires python 2 to be available.

**Comment by lemaguilera** [comment]
Thanks a lot! It worked
