### ISSUE TITLE
install.sh uses unzip without checking if it is installed

### ISSUE THREAD

**Issue by hardy613** [denoland/deno#5556]
Hello,

While setting up deno in docker I noticed the `install.sh` script uses `unzip` and the build will exit with the error `unzip is not installed`. I believe this is not a default program and `tar` can be used in place of `unzip`.

```docker
RUN curl -fsSL https://deno.land/x/install/install.sh | sh
```
https://github.com/denoland/deno_install/blob/master/install.sh#L39

The `RUN` command that worked for me was 

```
RUN sudo apt-get update && sudo apt-get install unzip -y && \
        curl -fsSL https://deno.land/x/install/install.sh | sh && \
        sudo mkdir "/usr/local/etc/bash_completion.d" && \
        sudo chown "$USER:$USER" "/usr/local/etc/bash_completion.d" && \
        sudo "$HOME/.deno/bin/deno" completions bash > "/usr/local/etc/bash_completion.d/deno.bash" && \
        sudo apt-get clean && \
        sudo rm -rf /var/lib/apt/lists/*

ENV DENO_INSTALL="/$HOME/.deno"
ENV PATH="$DENO_INSTALL/bin:$PATH"
```

**Comment by nayeemrmn** [comment]
Duplicate of https://github.com/denoland/deno_install/issues/117.

**Comment by shardyMBAI** [comment]
Ty! I did a search for `unzip` but this did not come up - apologies.

**Comment by hardy613** [comment]
Ty! I did a search for unzip but this did not come up - apologies.
