### ISSUE TITLE
Use Partial<T> for options

### ISSUE THREAD

**Issue by buckle2000** [denoland/deno#5560]
Currently, we have API like this:

```
  /// lib.deno.ns.d.ts
  export interface OpenOptions {
    read?: boolean;
    write?: boolean;
    append?: boolean;
    truncate?: boolean;
    create?: boolean;
    createNew?: boolean;
    mode?: number;
  }

  export function open(path: string, options?: OpenOptions): Promise<File>;
```

It would be better like this instead:

```
  export interface OpenOptions {
    read: boolean;
    write: boolean;
    append: boolean;
    truncate: boolean;
    create: boolean;
    createNew: boolean;
    mode: number;
  }

  export function open(path: string, options?: Partial<OpenOptions>): Promise<File>;
```

**Comment by kitsonk** [comment]
Why?

**Comment by buckle2000** [comment]
Is it by design that the default values are not available on the js side? I saw this and was worried:
https://github.com/denoland/deno/blob/4a8d25646aa58e3e59d622e69c41822b40415c46/cli/js/ops/fs/open.ts#L18-L21
What is the default `mode`?

**Comment by kitsonk** [comment]
`Partial` simply add another layer of type indirection that is wholly unnecessary.  It doesn't change the working types at all.

The code you site is just badly written badly, IMO.

It should be written as:

```ts
 export function openSync(path: string, { mode, ...options }: OpenOptions = {}): number { 
   return sendSync("op_open", { path, options, mode }); 
 } 
```

Which we can do a cleanup of such things, versus adding level of indirection in the types.

**Comment by buckle2000** [comment]
No, I mean that `op_open` can receive arbitrary JSON, as oppose to with fixed field and crash on missing fields. Is that an issue?

**Comment by kitsonk** [comment]
We do not currently strongly type ops.  We could with overloads, but we haven't, as they aren't exposed to users and should be well tested.  I am still not sure what that has to do with `Partial`.
