### ISSUE TITLE
Idea: Support common HTTP exceptions:

### ISSUE THREAD

**Issue by getspooky** [denoland/deno#5561]
Hi,
I think it would be great and useful to add `Built-in HTTP exceptions` . A set of standard exceptions that inherit from the base `HttpException`.
example : 
`BadRequestException`,
`UnauthorizedException`
...

**Comment by kitsonk** [comment]
How would these be raised and used?  This is really the domain of HTTP server frameworks.  It _might_ make sense in `std/http` but even then.  Not every workload run on Deno would be an HTTP server.

There are already community projects that provide this (e.g. https://github.com/oakserver/oak/blob/master/httpError.ts).

**Comment by getspooky** [comment]
hi @kitsonk ,
I agree with you on the fact that not every workload run on Deno would be an HTTP server, but i think it would be very useful for the developer to have basic exception related to the server and system build in deno core

**Comment by kitsonk** [comment]
> How would these be raised and used?

**Comment by getspooky** [comment]
@kitsonk 
1- All exception must inherit `Exception`
2- The `Exception` constructor takes two required arguments which determine the response:
- The `response` argument defines the JSON response body. It can be a string
- The `status` argument defines the HTTP status code.

example :
```
throw new HttpException('This is a custom message' ,Status.BadGateway);
```
In many cases, you will not need to write custom exception :

example : 
```
export class BadGatewayException extends Exception {
  constructor() {
    super('BadGateway', Status.BadGateway);
  }
}
```

**Comment by kitsonk** [comment]
There is no such thing as `Exception` and there are sufficient community packages that address this as pointed out earlier. This sort of workload specific stuff does not belong in the core of Deno. Maybe `std`, maybe.

**Comment by crabmusket** [comment]
Leaving [this here](https://golang.org/src/net/http/status.go) as something that might be nice if ported into `std`.

**Comment by getspooky** [comment]
so we can add exception to `std` ?
