### ISSUE TITLE
Docs: Edits and improvements to the Manual

### ISSUE THREAD

**Issue by mattd3v** [denoland/deno#5568]
This issue is for minor editorial suggestions to the Manual, and on-going proofreading work.

**Comment by madranet** [comment]
What manual?

![SS 2020-05-18 at 12 24 18](https://user-images.githubusercontent.com/669658/82207947-94950580-9902-11ea-8189-1c6f9cf979de.png)

https://deno.land/manual

**Comment by ry** [comment]
We appreciate the edits. We're absolutely flooded with messages after the release. Please help reduce traffic by combining everything into one PR and not opening extra issues - it's just more for us to sift through. Closing.
