### ISSUE TITLE
Upgrade V8 to 7.0

### ISSUE THREAD

**Issue by ry** [denoland/deno#557]
1. Change this line https://github.com/denoland/deno/blob/ca4ace6b1f054593029df4958538708c2fbbabc2/gclient_config.py#L2
1. Run `./tools/sync_third_party.py`, and "git add" all the changed/updated files in `//third_party/v8`.
1. Ensure that this passes: `./tools/build.py && ./tools/test.py` (This will take about 30 minutes)
1. Send a PR to https://github.com/denoland/deno_third_party and https://github.com/denoland/deno

**Comment by satyarohith** [comment]
I think this will be a good one for me

**Comment by ameerthehacker** [comment]
I will try this out @ry

**Comment by ameerthehacker** [comment]
Hey @ry created pull requests

**Comment by DanielRamosAcosta** [comment]
@ameerthehacker 's PR is the #569
