### ISSUE TITLE
stdout and stderr not printing all data and script hangs

### ISSUE THREAD

**Issue by JWebCoder** [denoland/deno#5570]
Hello,

I've created a small code example where I'm able to replicate this issue
```typescript
const { stderr, stdout } = Deno
let counter = 1
while(counter < 100) {
  stderr.write(new TextEncoder().encode(counter + '\n') )
  stdout.write(new TextEncoder().encode('out' + counter + '\n') )
  counter += 1
}
```

I'm using stdout and stderr to write data, in the end, you should see all the numbers between 0 and 99 show up on the screen, and this is the result:
<img width="52" alt="Screenshot 2020-05-18 at 00 19 10" src="https://user-images.githubusercontent.com/4250891/82162592-97a9da80-989d-11ea-9a85-c03c986da847.png">

As you can see the script never ends and also the log is incorrect.

Thank you for the great work by the way :)

**Comment by cknight** [comment]
`write` is an async function. You are flooding this with too many messages at once. Either use `await` or switch to `writeSync`.

**Comment by JWebCoder** [comment]
Only two call and the application hangs
```typescript
const { stderr } = Deno
stderr.write(new TextEncoder().encode('a\n'))
stderr.write(new TextEncoder().encode('a\n'))
```

If I have 4 calls I'm already missing logs.

I understand the point of it being async and that I may be flooding it, but with such low quantity of calls, this shouldn't happen. stdout and stderr should be used for logging purposes, if they are not able to handle more than 4 calls at a time, there is an issue there.

Also, the point of being async is so that I can use it in a call and forget method, but with only two calls it hangs the script.

**Comment by cknight** [comment]
There may be improvements to make here, but all bets are off when you send multiple concurrent requests to the underlying OS.  Ultimately, you should be using console.log and console.error for your purposes, or have a look at the [std/log](https://deno.land/std/log) library.

For your example:
```
let counter = 1
while(counter < 100) {
  console.error(counter)
  console.log('out' + counter)
  counter += 1
}
```

**Comment by JWebCoder** [comment]
Still, there's a big difference there, console.log is blocking, while stdout and stderr aren't. In terms of logging, it would be much better to have this working correctly.
The [std/log](https://deno.land/std/log) is good, but it doesn't handle this type of issue. Right now I'm using console.log but I would like to change it.

**Comment by ry** [comment]
This is expected behavior. As @cknight said, use await or writeSync.

**Comment by cknight** [comment]
@JWebCoder this may be of interest, but I've been working on an async implementation of std/log which may meet your need.  Should be ready for review soon.

**Comment by JWebCoder** [comment]
@cknight that will be more than welcome :)
