### ISSUE TITLE
Is it possible for tensorflow.js/onnx to run on deno?

### ISSUE THREAD

**Issue by chenxyzl** [denoland/deno#5575]
hope tensorflow.js/onnx can run on deno。

**Comment by Soremwar** [comment]
@chenxyzl It can. The question is if they support JavaScript and Deno specific API's or CommonJS and Node specific API's and if they are interested in supporting Deno as a runtime. Tensorflow codebase is quite huge so its a big step for them

**Comment by kitsonk** [comment]
Also, it is more a question for tensorflow or community help resources, not an issue with Deno that belongs in the issue tracker.

**Comment by chenxyzl** [comment]
thanks

**Comment by ry** [comment]
It can't really. Maybe with the wasm backend. But we need webGL support to do big matmuls.

**Comment by Danieliessen** [comment]
Did the situation change??

**Comment by Danieliessen** [comment]
Why not just use tensorflow with rust backend??

**Comment by Soremwar** [comment]
@Danieliessen Deno 1.8 added support for GPU based calculations, so it's just a matter of time

**Comment by tlightsky** [comment]
> 

is there some examples for this
