### ISSUE TITLE
Speeding up tsc

### ISSUE THREAD

**Issue by kizerkizer** [denoland/deno#5579]
In the 1.0 release blog post, it was mentioned that typescript compilation is a bottleneck. Aside from porting to Rust, has NectarJS https://www.npmjs.com/package/nectarjs been considered? From what I’ve read, it can compile JS to native binaries.

**Comment by Caesar2011** [comment]
Maybe worth checking out this issue

https://github.com/denoland/deno/issues/5432

**Comment by ry** [comment]
see #5432
