### ISSUE TITLE
deno run error 10061

### ISSUE THREAD

**Issue by hanhduykaka** [denoland/deno#5580]
I've install deno, but can not run deno welcome

deno run https://deno.land/std/examples/welcome.ts

Download https://deno.land/std/examples/welcome.ts
error: error sending request for url (https://deno.land/std/examples/welcome.ts): error trying to connect: tcp connect error: No connection could be made because the target machine actively refused it. (os error 10061)

**Comment by xReveres** [comment]
OS Windows/Linux ?
Also you can check firewall.
I don't have problem

**Comment by ry** [comment]
Can't repeat
