### ISSUE TITLE
How to know latest version of a deno pacakge from url?

### ISSUE THREAD

**Issue by nsisodiya** [denoland/deno#5581]
We can import distributed packages like this in deno. 
```
https://raw.githubusercontent.com/denoland/deno/std/0.42.0/std/http/server.ts
import * as pkg from 'https://cdn.pika.dev/lodash-es@^4.17.15';
```
If we want to upgrade a package, We can upgrade the package by going to the package website one by one and copy-paste latest version.
But how to do it automatically? 
How to know all the versions of a given deno package from URL?

**Comment by egoist** [comment]
I made a tool for this: https://github.com/egoist/dedep

However only specific domains are supported.

**Comment by bartlomieju** [comment]
Outside of scope for Deno. There are existing third party solutions existing, visit https://github.com/denolib/awesome-deno#tools for more info. 

Closing as this issue is not actionable.
