### ISSUE TITLE
Is it possible to turn the Rust Deno into webassembly and load it into browser?

### ISSUE THREAD

**Issue by cfcodefans** [denoland/deno#5585]
I learned that Rust code can be compiled as webassembly module, since Deno is written in Rust......

**Comment by kitsonk** [comment]
No, it can't, because the Deno's Rust code is mainly interfacing with v8 and the operating system, both of which are not available inside of v8 running web assembly.

**Comment by cfcodefans** [comment]
oh, Thanks for the explanation 
or maybe it would make a typescript runtime webassembly in browser

**Comment by ry** [comment]
no
