### ISSUE TITLE
allow-read to allow multiple directories

### ISSUE THREAD

**Issue by vinodsai-a** [denoland/deno#5588]
Can we add allow-read to support multiple directories?
tried to give --allow-read=dir1 --allow-read=dir2.  It didn't work.

**Comment by bartlomieju** [comment]
Try `--allow-read=dir1,dir2`

**Comment by vinodsai-a** [comment]
Cool, that seems to be working for directories. But if I include file it's not working.

**Comment by bartlomieju** [comment]
@vinodsai-a can you provide reproduction?

**Comment by bartlomieju** [comment]
Closing as stale. Feel free to reopen.
