### ISSUE TITLE
[Proposal] Deno command to manage modules in cache

### ISSUE THREAD

**Issue by Soremwar** [denoland/deno#5600]
*I'd like to take on this, if this proposal seems like a good idea to you*

A valid question came to me today. What if I'm not using a module I imported remotely anymore and want to delete it from my disk?

Asking someone to delete it in their DENO_DIR folder seems like quite a hassle, and is not really intuitive. A module manager in Deno (**not a package manager**) that allow the users to list and delete the modules available for import in their system seems like a good idea.

(Couple crazy ideas regarding a CLI app and an API to allow interop with possible GUI implementations to be discussed)

**Comment by nayeemrmn** [comment]
I proposed a `deno clean` specification in #3437. Could you clarify what else such a "module manager" would do?

**Comment by Soremwar** [comment]
Your issue seems to solve the issue that was told to me. The second part however (available module listing) might be desirable to check exactly what dependencies you have/wanna delete.

Given that they are of the same nature and are likely to be used together, I'd allow them as two different options in the same command (package managers such as pacman, apt, yum, etc seem to follow that mindset)

Third, an API for such operations might be useful for people who desire to use a dependency manager in their projects, perhaps even for a GUI that handles modules with greater ease than a CLI command

**Comment by lucacasonato** [comment]
Deno now has a `deno clean` subcommand.
