### ISSUE TITLE
[std/ws] connectWebSocket - connectTls certFile support

### ISSUE THREAD

**Issue by matthieudesprez** [denoland/deno#5604]
For the same connection, I have a node script working fine using
```
$ NODE_EXTRA_CA_CERTS=cert.pem node wss_client.js
open
```
```javascript
const WebSocket = require("ws");
const wss = new WebSocket("wss://...");
wss.onopen = () => console.log("open");
```

Trying the equivalent with deno, I got
```
$ deno run --allow-net --allow-read --cert cert.pem wss_client.ts
WARN RS - rustls::session:718 - Sending fatal alert BadCertificate
```
```typescript
import { connectWebSocket } from "https://deno.land/std/ws/mod.ts";
try {
  await connectWebSocket("wss://...");
  console.log("connected");
} catch (err) {
  console.log(err);
}
```

I've started to look in https://deno.land/std/ws/mod.ts and I suspect that in connectWebSocket, the Deno.connectTls is not passing the certFile

**Comment by matthieudesprez** [comment]
Yes, passing the certFile manually through the ws module connectWebSocket fn did the trick

ws/mod.ts
```typescript
export async function connectWebSocket(
  endpoint: string,
  headers: Headers = new Headers(),
  certFile?: string,
): Promise<WebSocket> {
  const url = new URL(endpoint);
  const { hostname } = url;
  let conn: Conn;
  if (url.protocol === "http:" || url.protocol === "ws:") {
    const port = parseInt(url.port || "80");
    conn = await Deno.connect({ hostname, port });
  } else if (url.protocol === "https:" || url.protocol === "wss:") {
    const port = parseInt(url.port || "443");
    conn = await Deno.connectTls({ hostname, port, certFile });
  } else {
    throw new Error("ws: unsupported protocol: " + url.protocol);
  }
...
}
```
./wss_client.ts
```typescript
import { connectWebSocket } from "https://deno.land/std/ws/mod.ts";
try {
  await connectWebSocket("wss://...", new Headers(), './cert.pem');
  console.log("connected");
} catch (err) {
  console.log(err);
}
```
```
$ deno run --allow-read --allow-net wss_client.ts
connected
```

does someone see a better way to handle cert files for wss connections ?

Can't the --cert arg value be kept somewhere and retrieved later during the binding or directly in rust ?

**Comment by bartlomieju** [comment]
@matthieudesprez `--cert` is used for Deno internal HTTP client - ie. downloading remote modules and `fetch()` API. User code needs to handle TLS manually. Using `wss://` is definitely desirable and `std/ws` should support that. Can you change issue name to reflect that?

**Comment by matthieudesprez** [comment]
@bartlomieju ok I've mixed things up about the --cert flag usage in deno because of the NODE_EXTRA_CA_CERTS env variable in node, and it's more clear now, thanks.

**Comment by crowlKats** [comment]
Now that the WebSocket API is implemented, this should be closed, as connect got removed.
