### ISSUE TITLE
Move config parsing out of js/compiler.ts

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#5606]
_This issue is for tracking purposes of something the core team is working on. Informed feedback is welcomed, but please think before commenting._

Moving tsconfig parsing out of compiler.ts requires a couple things:

- Ability to parse JSONC (@dprint has it cc/ @dsherret)
- Having default values and overrides depending on type of compile (e.g. bundle is slightly different to just plain which are also both slightly different from the runtime APIs)
- Changing the ops to just supply a parsed JSON structure of compiler options.

**Comment by bartlomieju** [comment]
Ref https://github.com/dprint/jsonc-parser

**Comment by kitsonk** [comment]
In my refactor of the compiler branch, I have all of the parsing and processing of the tsconfig, including the ignoring the options we ignore in Rust now.
