### ISSUE TITLE
Deno bundle doesn't include the dependencies properly

### ISSUE THREAD

**Issue by youknowriad** [denoland/deno#5610]
Hi there! and thanks for your amazing work on Deno.

I have the following code

```
import { createElement } from 'https://cdn.pika.dev/react@16.13.1';
import { render }  from 'https://cdn.pika.dev/react-dom@16.13.1';

const el = createElement;

export function run() {
    render(
        el( 'div', {}, 'Hello!' ),
        document.querySelector('#root')
    );
}
```

an my (maybe wrong) assumption is that running `deno bundle index.js index.bundle.js` would give a single JS file including my code and its deps that I could load in an HTML module using a script module tag but the result doesn't embed my deps at the moment (causing JS errors).

So I'm wondering:

 - Is my assumption wrong and the command not supposed to work this way?
 - Are my deps not compatible?
 - something else...

Thanks

**Comment by kitsonk** [comment]
Need to look into it a bit more to say one way or another...

**Comment by lusatiro** [comment]
@youknowriad, look at these issues: #3799, #3726 and this
PR that was merged #3863

**Comment by kitsonk** [comment]
@lusatiro I don't think those issues and that PR has anything to do with this issue, especially since I created one of those issues and the PR you mentioned. :-D

**Comment by lusatiro** [comment]
@kitsonk, I'm not telling that theses issues and PR solves the problem.
I know that it was you, I'm watching the threads. I was trying to give more context.
This works for me:

`
// x.ts
import { createElement } from 'https://cdn.pika.dev/react@16.13.1';
import { render }  from 'https://cdn.pika.dev/react-dom@16.13.1';

const el = createElement;

export function run() {
  render(
    el( 'div', {}, 'Hello!' ),
    document.querySelector('#root')
  );
}
`

`
// y.ts
const [errors, emitted] = await Deno.compile("./x.ts", undefined, {
  lib: ["dom", "esnext"],
});

const truncate_filename = (filename: string) => filename.replace('file:///', '');

for (const [filename, text] of Object.entries(emitted)) {
  console.log(`${truncate_filename(filename)}`);
  console.log(text.split('\n').map(line => `\t${line}`).join('\n'));
}
`

**Comment by lusatiro** [comment]
@kitsonk, I'm not telling that theses issues and PR solves the problem.
I know that it was you, I'm watching the threads. I was trying to give more context.
This works for me:

```
// x.ts
import { createElement } from 'https://cdn.pika.dev/react@16.13.1';
import { render } from 'https://cdn.pika.dev/react-dom@16.13.1';

const el = createElement;

export function run() {
  render(
    el( 'div', {}, 'Hello!' ),
      document.querySelector('#root')
   );
}
```

```
// y.ts
const [errors, emitted] = await Deno.compile("./x.ts", undefined, {
  lib: ["dom", "esnext"],
});

const truncate_filename = (filename: string) => filename.replace('file:///', '');

for (const [filename, text] of Object.entries(emitted)) {
  console.log(${truncate_filename(filename)});
  console.log(text.split('\n').map(line => \t${line}).join('\n'));
}
```

**Comment by lusatiro** [comment]
The approach used by @kitsonk result on a:
```
error: Uncaught AssertionError: Assertion failed.
```
I believe that this is caused by the missing types from DOM

**Comment by lusatiro** [comment]
Aqui é br-br, meu fi, si fudê.

**Comment by kitsonk** [comment]
Yeah, I had missed that it would have required lib `dom`.  Thanks for pointing that out.  I was just getting fixated that remote code wasn't being included, as the OP wasn't indicating he was getting any errors.

And yes, `deno bundle` only is intended to really work for bundling workloads for Deno.  If you are trying to create a bundle to run in a browser (or possibly Deno), using the `Deno.bundle()` API is what you should do, supplying the proper libs.

**Comment by gensior** [comment]
Where can I find documentation on the Deno.bundle() API?

**Comment by cknight** [comment]
@gensior the bundle() API is currently behind the unstable flag. Docs can be found at https://github.com/denoland/deno/blob/master/cli/js/lib.deno.unstable.d.ts#L648

**Comment by gensior** [comment]
@cknight thanks!

**Comment by youknowriad** [comment]
Thanks a lot of your answers, I'm closing this issue now. Feel free to reopen if there's anything left to consider here.
