### ISSUE TITLE
Why can I redefined the global variable `Deno` ?

### ISSUE THREAD

**Issue by zhanyuzhang** [denoland/deno#5612]
If I override the Deno directly :
```
Deno = null;
```
It will throw an error as follows:
```
error: Uncaught TypeError: Cannot assign to read only property 'Deno' of object '#<Object>'
```

It works as I expected.

However, If I use `const` or `let` to redifined it:
```
const Deno = null;
```

It won't throw error. 

In my opinion, it is necessary to disable redefining or override the `Deno`.

**Comment by kitsonk** [comment]
@zhanyuzhang this is called variable shadowing, a basic concept of JavaScript.  Each file loaded in Deno is treated as a module, each module has its own scope.  Variable declared in that scope shadow any global scope variables (though `let` and `const` are block scoped).  This works for any variable in the global scope.
