### ISSUE TITLE
deno doc is broken in master

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#5614]
I can't get anything to work, for example

```shell
$ deno doc https://deno.land/x/oak@v4.0.0/mod.ts
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', cli/doc/printer.rs:130:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I am surprised we don't have an integration test for this.

**Comment by LayZeeDK** [comment]
In v1.0.0, `deno doc` is outputting ASTs to stdout and doesn't seem to respect `--log-level` or `--quiet`.

**Comment by bartlomieju** [comment]
@LayZeeDK the issue you described has already been fixed in https://github.com/denoland/deno/pull/5356

I'm working on a fix for the issue described by @kitsonk

**Comment by LayZeeDK** [comment]
I thought they were related.

Thanks for fixing the `deno doc` issues 🙇‍♂️
