### ISSUE TITLE
Why the params order can affect the permission setting

### ISSUE THREAD

**Issue by zhanyuzhang** [denoland/deno#5619]
I copied the example code from [https://deno.land/#getting-started](https://deno.land/#getting-started) and saved it as `index.js` on local:

```
import { serve } from "https://deno.land/std@0.50.0/http/server.ts";
const s = serve({ port: 8000 });
console.log("http://localhost:8000/");
for await (const req of s) {
  req.respond({ body: "Hello World\n" });
}
```

Then, I use `deno run ./index.js` to run the code,  but it will throw errors: 
```
error: Uncaught PermissionDenied: network access to "0.0.0.0:8000", run again with the --allow-net flag
```

So, I add `--allow-net`  flag on the end of the line: 
```
deno run ./index.js --allow-net
```

And it will throws the same error.

Lastly , I replace the `--allow-net`   after `run` , and it works:
```
deno run --allow-net ./index.js 
```

I'm confused  why the params order can affect the permission setting

**Comment by xReveres** [comment]
Because, if you put arguments after script, it passes as script arguments not deno.

**Comment by Ragzouken** [comment]
Related to https://github.com/denoland/deno/issues/5450

**Comment by zhanyuzhang** [comment]
> Related to #5450

Ths
