### ISSUE TITLE
Any plan to compile to binary?

### ISSUE THREAD

**Issue by mhf-ir** [denoland/deno#5622]
Any plane to compile deno scripts to binary like ?
https://github.com/nectarjs/nectarjs/
https://github.com/zeit/pkg

Like Rust,

- Portable without Deno runtime dependency
- Faster runtime

If this could be **official** implementation we have both Scripting and Compiled language feature together, unique arccos any other interpreters.

**Comment by crowlKats** [comment]
what you are looking for is #986

**Comment by mhf-ir** [comment]
> what you are looking for is #986
yeah.
