### ISSUE TITLE
Define a default extension

### ISSUE THREAD

**Issue by yakanet** [denoland/deno#5623]
Is it possible to have a flag on the `deno run` command in order to specify a default extension when an import is using an URI without any file extension specified.

```
deno run --default-extension=ts mod.ts

/*
 * mod.ts
 */
import {myVar} from "https://foo.bar/variables";
```

That should work for the first level import and also the n-th level imports.
That could help to use typescripts dependencies that doesn't use deno syntax for imports.

**Comment by kitsonk** [comment]
I don't think we would consider this.  It is very intentional that we want to be explicit with the extensions.

**Comment by crowlKats** [comment]
No, this would break with browsers as it doesn't align with the spec.

>  That could help to use typescripts dependencies that doesn't use deno syntax for imports.

not really, as many modules will use node internals, so you would have to use jspm.io, unpkg.com or pika.dev anyways.

**Comment by yakanet** [comment]
I don't think that would break the browser spec as the bundle command would add the default-extension for the generated js files.

If I'm using the jspm.io or unpkg.com import, my imports will loose all types definitions as they publish only the js version. I'd rather import directly the typescript file from the github repository.

I understand the choice for the explicit definition of the extensions for the first level import. But there is a lot of node agnostic typescript libraries that we could't use just because of an import syntax.

Is there any plan to support those node agnostic typescript libraries or we should rewrite those libraries using the new import syntax ?

**Comment by kitsonk** [comment]
Where is a lot of the Node.js module resolution that doesn't work under Deno, a lot more than just a lack of extensions.  It resolves modules out of `node_modules` it resolve paths to `index.js`, etc.  Node.js is moving away from extensionless specifiers, as it has caused lots of challenges in supporting ESM natively.

> If I'm using the jspm.io or unpkg.com import, my imports will loose all types definitions as they publish only the js version.

There are solutions for this (see: https://deno.land/manual/getting_started/typescript).  In particular, Pika.dev CDN sends a header of `X-TypeScript-Types` which Deno understands which it sends when the types are available for a give package.  Your imports will be strongly typed and you won't have a load of modules that you have to run through the compiler to transpile.

There is also `https://deno.land/x/types` which is there to provide types that have been rewritten to not rely upon Node.js resolution.
