### ISSUE TITLE
Writing blob to local file.

### ISSUE THREAD

**Issue by fakoua** [denoland/deno#5626]
Hi,
I'm fetching a zip file form a url and I want to save the blob into a local file:

```
fetch(downloadUrl, {
            method: 'GET'
        })
        .then(response => response.blob())
        .then(blob => {
            console.log(blob.size)
            // Save the blob to a file
        })

```
any idea on how to save the blob?

Many thanks.

**Comment by nayeemrmn** [comment]
```ts
await Deno.writeFile("path/to/file", await blob.arrayBuffer())
```
Please use the discord first for help and questions: https://discord.gg/deno.

**Comment by fakoua** [comment]
Thank you very much, 

The provided solution does not work, it says: ArrayBuffer is not assignable to Uint8Array, 
Anyway, i will switch to discord, 

thank you again.

**Comment by kt-12** [comment]
@fakoua I am not sure if your question is answered. 
Just adding the solution, so if someone comes across this will be useful. 
```
fetch(downloadUrl, {
            method: 'GET'
        })
        .then(response => response.blob())
        .then(blob => {
             const buffer = await blob.arrayBuffer();
             const unit8arr = new Deno.Buffer(buffer).bytes();
              Deno.writeFileSync("path/to/file", unit8arr);
        })

```

**Comment by josephrocca** [comment]
Simplified version of the above code:
```js
let buffer = await fetch(url).then(r => r.arrayBuffer());
await Deno.writeFile("path/to/file", new Uint8Array(buffer));
```

**Comment by ledlamp** [comment]
> Simplified version of the above code:
> 
> let buffer = await fetch(url).then(r => r.arrayBuffer());
> await Deno.writeFile("path/to/file", new Uint8Array(buffer));

that what I do but it would be nice if the deno methods were more flexible and supported all the binary types like arraybuffer, blob, etc

**Comment by bartlomieju** [comment]
@ledlamp sounds like a good idea, can you open a new issue with a feature request?

**Comment by BlackAsLight** [comment]
If you want to take a Response and write it to a file then the best way would be via a stream.

```ts
await (await fetch("url"))
  .body
  .pipeTo((await Deno.create("file")).writable);
```

**Comment by ledlamp** [comment]
> If you want to take a Response and write it to a file then the best way would be via a stream.
> 
> await (await fetch("url"))
>   .body
>   .pipeTo((await Deno.create("file")).writable);

This is good idea, but one reason not to do it is that if the download is interrupted then it leaves an incomplete file.


> [@ledlamp](https://github.com/ledlamp) sounds like a good idea, can you open a new issue with a feature request?

sounds good... https://github.com/denoland/deno/issues/29291

**Comment by BlackAsLight** [comment]
> > If you want to take a Response and write it to a file then the best way would be via a stream.
> > await (await fetch("url"))
> > .body
> > .pipeTo((await Deno.create("file")).writable);
> 
> This is good idea, but one reason not to do it is that if the download is interrupted then it leaves an incomplete file.

If the download is interrupted then this code would throw an error. You'd simply catch said error and either delete the file to restart or write some code to resume the download, assuming the server supports it

**Comment by ledlamp** [comment]
> > > If you want to take a Response and write it to a file then the best way would be via a stream.
> > > await (await fetch("url"))
> > > .body
> > > .pipeTo((await Deno.create("file")).writable);
> > 
> > 
> > This is good idea, but one reason not to do it is that if the download is interrupted then it leaves an incomplete file.
> 
> If the download is interrupted then this code would throw an error. You'd simply catch said error and either delete the file to restart or write some code to resume the download, assuming the server supports it

Not if the process dies or the computer dies, and what if you are writing over an existing file... then you have to write to a tmp path and move when it's done... well I just use the memory as tmp because the files are mbs and there is plenty of memory and my scripts are simple tools doing single tasks in sequence
