### ISSUE TITLE
Deno.cwd's read permission is ineffective

### ISSUE THREAD

**Issue by SyrupThinker** [denoland/deno#5627]
The `PermissionDenied` error leaks the current working directory, thus the permission check can be circumvented like so:
```js
// cwd.js
function unauthenticatedCwd() {
  try {
    Deno.cwd();
  } catch (e) {
    return e.message.split('"')[1];
  }
}
console.log(unauthenticatedCwd());
```
```
: deno run cwd.js 
/home/syrup/downloads
: deno --version
deno 1.0.0
v8 8.4.300
typescript 3.9.2
```

**Comment by nayeemrmn** [comment]
For `Deno.execPath()`, we could add an option to `state.check_read()` or another function that allows you to pass a custom string in place of the path:
```
Uncaught PermissionDenied: read access to <exec path>, run again with the --allow-read flag
```

For `Deno.cwd()`, reading or writing any relative path also leaks it. And who knows what else 🤦‍♂️
