### ISSUE TITLE
Rust CoC should apply to Denoland Official social media account

### ISSUE THREAD

**Issue by trivikr** [denoland/deno#5628]
**Is this related to a problem? Please describe.**
* This concern is regarding a joke which was shared on @deno_land official twitter account https://twitter.com/deno_land/status/1262517004159913985
  <details>
  <summary>Screenshot</summary>

  ![Screenshot from 2020-05-19 05-42-54](https://user-images.githubusercontent.com/16024985/82327748-b38fa800-9993-11ea-9b28-daffe6cf3c2f.png)

  </details>

* This is an official twitter account listed in the footer of https://deno.land/ website

  <details>
  <summary>Screenshot</summary>

  ![Screenshot from 2020-05-19 05-46-13](https://user-images.githubusercontent.com/16024985/82328441-bb9c1780-9994-11ea-894d-f10e37805f74.png)

  </details>

* Deno follows Rust CoC as per it's [CONTRIBUTING.md](https://github.com/denoland/deno/blob/b0d62cdbd79a8dfcbe9ef8539fe2efae3f21890b/docs/contributing.md)
* Trolling is not welcome as per Rust CoC https://www.rust-lang.org/policies/code-of-conduct

**Describe the solution you'd like**
The official social media accounts of Deno should avoid trolling.

Questions to be answered by Deno core or moderation team before taking action (if any):
* Does the joke shared in the tweet fall under the definition of "Trolling"?
* If yes, should Rust CoC apply to official social media accounts of Denoland?

**Describe alternatives**
Denoland continues to share content which can classify as "trolling", thus encouraging it's users to do the same.

**Additional context**
This issue came up from discussions on Twitter thread https://twitter.com/trivikram/status/1262728805778550784

**Comment by galkowskit** [comment]
I must be sincerely dumb (or something is lost due to me not being native English).

How is this joke (a code snippet that turns "node" into "deno") is not following the CoC? It's just a small marketing joke from what I can see. Genuinely curious.

**Comment by trivikr** [comment]
Update: The original tweet which started discussions shared in Additional Context has been deleted with explanation in  https://twitter.com/poledesfetes/status/1262736211912712193

Closing this issue as the concern of CoC violation is not valid as per the author of the tweet. No action required.

**Comment by vdeturckheim** [comment]
To give a bit of context on why I started this thread:
This snippet has been used for the past few days to troll around along with "Deno will kill Node.js".

When I saw the official Twitter account's message I understood it in this context and felt it was one more occurence of it. That is pretty much why I took it badly.

Most of the replies to this original tweet were harmless and it makes me think that most people following this account do not have any hostile intentions.

I hope this clarifies it. Feel free to reach out to me :)

**Comment by trivikr** [comment]
> Most of the replies to this original tweet were harmless and it makes me believe that most people following this account do not have any hostile intentions.

Screenshot of the harmless replies to the original tweet from @deno_land official twitter account
<details>
<summary>Expand</summary>

![2020-05-19-06-56-twitter com](https://user-images.githubusercontent.com/16024985/82336289-38cc8a00-999f-11ea-8b83-be0b38ba06a8.png)

</details>
