### ISSUE TITLE
Deno.bundle uses cache

### ISSUE THREAD

**Issue by amatiasq** [denoland/deno#5631]
I'm creating [a script](https://amatiasq.com/deno/web.ts):

```sh
deno --allow-read=. --allow-net https://amatiasq.com/deno/web.ts my-script.ts
```

That watches the file system and bundles `my-script.ts` into a frontend-ready file.

The issue is that when a file system event is detected `Deno.bundle` bundles again from cache. Making the tool unusable.

I wasn't able to find a way to clear cache, I tried starting a process `deno bundle my-script.ts` but that doesn't allow me to pass a custom `tsconfig` to add `lib: ["DOM"]`.

**Comment by sholladay** [comment]
As a workaround, maybe you could run `deno cache` before `deno bundle`, each time the watcher triggers.

**Comment by amatiasq** [comment]
@sholladay good idea!

I tried this before the bundle:

```js
  await Deno.run({
    cmd: ['deno', 'cache', file],
  }).status();
```

And now suddenly `Deno.bundle` is ignoring the `lib` parameter:

```js
  const [diagnostics, content] = await Deno.bundle(file, undefined, {
    lib: ['dom'],
  });
```

Since it throws:

```
error: TS2584 [ERROR]: Cannot find name 'document'. Do you need to change your target library? Try changing the `lib` compiler option to include 'dom'.
const potato = document.querySelector('canvas');
               ~~~~~~~~
    at file:///Users/amatiasq/repos/deno-test/deno-test/run.ts:1:16
```

That same error doesn't happen if I comment the `deno cache` execution 😮

**Comment by bartlomieju** [comment]
Same problem as in #4743 and #5253
