### ISSUE TITLE
Behaviors from Deno.compile and Deno.bundle are confusing

### ISSUE THREAD

**Issue by lusatiro** [denoland/deno#5634]
When the issue #5610 come out I took the chance to get some doubts responded.
I was trying get this code working on browser yesterday:
```
import { LitElement, html, property, customElement } from 'https://unpkg.com/lit-element@2.3.1/lit-element.js?module';

@customElement('simple-greeting')
export class SimpleGreeting extends LitElement {
  @property() name = 'World';

  render() {
    return html`<p>Hello, ${this.name}!</p>`;
  }
}

```
I was using `deno bundle`
But I got the following error:
```
error: Uncaught AssertionError: Assertion failed.
    at Object.assert ($deno$/util.ts:33:11)
    at compile ($deno$/compiler.ts:1355:5)
    at async tsCompilerOnMessage ($deno$/compiler.ts:1548:22)
    at async workerMessageRecvCallback ($deno$/runtime_worker.ts:73:9)
```
So I went to the docs and try `Deno.compile` e `Deno.bundle`

Using this code:
```
const [errors, program] = await Deno.bundle(
  "./main.ts",
  undefined,
  {
    lib: ["dom", "esnext"]
  }
);
```
The problem is that output contains:
`const __exp = __instantiate("file:///home/name/project/main");`

Changing the `bundle` by `compile` I still get a `file:///` but at least it is a `object` not a `string`.
The `object` contains the source map and the code wanted.

This is the way the output is supossed  to be?
I know it is under the flag `--unstable` but it would be very important feature for
frontend developers and for who is developing isomorphic apps. Also prevents
that a webpack come out for Deno.

Thanks

**Comment by kitsonk** [comment]
> The problem is that output contains:
> `const __exp = __instantiate("file:///home/name/project/main");`

Why is that a problem?  That is the code that bootstraps the bundle, so if you want to load it in a browser, you need something to bootstrap the module.

Also, you are using experimental decorators, but not providing a configuration that enables them.
