### ISSUE TITLE
Implicitly using master branch Warning should log file

### ISSUE THREAD

**Issue by brandonkal** [denoland/deno#5644]
This would make locating the offending import much easier.

**Comment by hayd** [comment]
This could also be solved with external tools e.g. https://github.com/hayd/deno-udd/issues/2

I don't think deno itself should have an opinion on url versioning behavior...

**Comment by SyrupThinker** [comment]
Also [this](https://github.com/denoland/deno_website2/issues/250) issue for the deno.land website.

**Comment by lucacasonato** [comment]
> I don't think deno itself should have an opinion on url versioning behavior...

Deno doesn't. It just displays the contents of `X-Deno-Warning` when it is provided in a response.

**Comment by brandonkal** [comment]
> I don't think deno itself should have an opinion on url versioning behavior...

I tend to agree but unfortunately the CLI already has such an opinion.

It logs
> Warning Implicitly using master branch https://offendingimport.com/mod.tsx

Which isn't very useful because this import could be in any number of files.

> Deno doesn't. It just displays the contents of X-Deno-Warning when it is provided in a response.

Okay that makes more sense. So this may be a deno_website2 issue. But it would be nice to have some method in the CLI to debug which module requested the file that returns the X-Deno-Warning header. Same for 404 etc.

**Comment by lucacasonato** [comment]
I agree a sort of stack trace for the import would be nice.

**Comment by SyrupThinker** [comment]
> I agree a sort of stack trace for the import would be nice.

That would be part of #5419

**Comment by lucacasonato** [comment]
Just talked with @bartlomieju about this, and we came to the conclusion that the warning should be logged on every program start.
