### ISSUE TITLE
Possible vulnerability with TLS

### ISSUE THREAD

**Issue by lemaguilera** [denoland/deno#5654]
When configuring a server with a cloudflare origin server certificate, it works perfectly when you visit the site using the url with https:

![image](https://user-images.githubusercontent.com/17011087/82387270-31879980-99fc-11ea-8ab7-f76f8054b7ae.png)

But when directly visiting the server IP using https the process stops on the server with the following error:

![image](https://user-images.githubusercontent.com/17011087/82387291-3c422e80-99fc-11ea-9b27-3fe221234b78.png)

Would it be possible to ignore that error so that the server continues to run?
The connection may close or return an error message, but the server should continue to listen to other requests.

I hope you have a solution! regards

**Comment by kitsonk** [comment]
Duplicate of #5260
