### ISSUE TITLE
cargo installation

### ISSUE THREAD

**Issue by gotheer** [denoland/deno#5657]
I used cargo to install deno via
    cargo install deno
In Linux mint, but it throws an error.
It has a relationship with Hashmap.

**Comment by bartlomieju** [comment]
Please provide a stack trace, this information is not sufficient to help debug.

**Comment by gotheer** [comment]
Sorry, I'm a beginner. I don't know how to STACKTRACE. The terminal keep showing me this:

error[E0433]: failed to resolve: use of undeclared type or module `proc_macro`
  --> /home/iam/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_ecma_visit_macros-0.1.0/src/lib.rs:25:20
   |
25 | pub fn define(tts: proc_macro::TokenStream) -> proc_macro::TokenStream {
   |                    ^^^^^^^^^^ use of undeclared type or module `proc_macro`

error[E0433]: failed to resolve: use of undeclared type or module `proc_macro`
  --> /home/iam/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_ecma_visit_macros-0.1.0/src/lib.rs:25:48
   |
25 | pub fn define(tts: proc_macro::TokenStream) -> proc_macro::TokenStream {
   |                                                ^^^^^^^^^^ use of undeclared type or module `proc_macro`

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0433`.
error: could not compile `swc_ecma_visit_macros`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `deno v1.0.0`, intermediate artifacts can be found at `/tmp/cargo-install0EuVjv`

Caused by:
  build failed

**Comment by bartlomieju** [comment]
@gotheer it looks like you are using older version of Rust. Upgrade Rust to lastest stable (`1.43.0`): `rustup update stable`.

**Comment by gotheer** [comment]
After updating to (rustc 1.43.1) :

error: failed to run custom build command for `rusty_v8 v0.4.2`

Caused by:
  process didn't exit successfully: `/tmp/cargo-installeEi1H3/release/build/rusty_v8-8bda25bffcc8f95b/build-script-build` (exit code: 101)
--- stdout
static lib URL: https://github.com/denoland/rusty_v8/releases/download/v0.4.2/librusty_v8_release_i686-unknown-linux-gnu.a
cargo:rustc-link-search=/tmp/cargo-installeEi1H3/release/gn_out/obj
Downloading https://github.com/denoland/rusty_v8/releases/download/v0.4.2/librusty_v8_release_i686-unknown-linux-gnu.a
Downloading https://github.com/denoland/rusty_v8/releases/download/v0.4.2/librusty_v8_release_i686-unknown-linux-gnu.a...
HTTP Error 404: Not Found

--- stderr
Traceback (most recent call last):
  File "./tools/download_file.py", line 63, in <module>
    sys.exit(main())
  File "./tools/download_file.py", line 58, in main
    DownloadUrl(args.url, f)
  File "./tools/download_file.py", line 44, in DownloadUrl
    raise e
urllib2.HTTPError: HTTP Error 404: Not Found
thread 'main' panicked at 'assertion failed: status.success()', /home/iam/.cargo/registry/src/github.com-1ecc6299db9ec823/rusty_v8-0.4.2/build.rs:229:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

warning: build failed, waiting for other jobs to finish...
error: failed to compile `deno v1.0.0`, intermediate artifacts can be found at `/tmp/cargo-installeEi1H3`

Caused by:
  build failed

**Comment by maxtnuk** [comment]
@gotheer if there is error on it, how about use `docker image`?
[docker image](https://hub.docker.com/repository/docker/maxtnt/deno/general)
```bat
docker pull maxtnt/deno:base
```
you can use deno by container

**Comment by bartlomieju** [comment]
Closing as stale, feel free to reopen if problem persists on latest version.
