### ISSUE TITLE
[discussion] Process for adding bindings.

### ISSUE THREAD

**Issue by ry** [denoland/deno#566]
Deno is just about to hit its first binary release, v0.1. At this point it is usable to some extent. There are now many bindings to add to all sorts of operating system functionality. I want an organized and streamlined process for adding new bindings.

The main goal is to avoid having to add the function in many different locations.
Here is a first pass at the process.

1. Specify the signature with jsdoc in a github issue.
2. List the corresponding function signatures in Go, Node, Python, and Rust. We lean towards Go naming/conventions, but will deviate when it makes sense. Listing them is so that everyone making decisions is aware of the prior art.
3. Submit PR implementing it:
  3A. create privileged implementation src/ops/read_file.rs 
  3B. create JS frontend src/ops/read_file.ts
  3C. create tests src/ops/read_file_test.ts
  3D. specify any messages src/ops/read_file.fbs
  3E. add to read_file.rs and read_file.ts to src/ops/BUILD.gn

**Comment by NewLunarFire** [comment]
If the long-term plan is to keep using Github for future development, we should make use of Github's issue and PR templates.

https://blog.github.com/2016-02-17-issue-and-pull-request-templates/

**Comment by hayd** [comment]
I don't think it's a good idea to template every issue in the deno repo to this narrow use case, that will be confusing for bug reports etc. I wonder if these issues should be in another rep e.g. deno-rfcs.

**Comment by ry** [comment]
I'm for having a PR template. For the next 6 months of this project, if it even survives that long, it is going to be 60% adding bindings. 

That said, let's work it out first.  

Thanks for the template, @NewLunarFire, but I'm going to close it and wait until we've discussed this further. For example the whole bit about adding files to `src/ops/` -- that directory doesn't exist yet -- it's just an imaginary place where we'd have ops.

**Comment by NewLunarFire** [comment]
It's fine, at least we have a closed PR we can go back to if we decide to go this way forward.

**Comment by NewLunarFire** [comment]
As I mentionned another time on Gitter, we're currently writing and comitting boilerplate code by hand in both Rust and Typescript for framebuffer message passing. We should instead generate those from the flabuffers definition files, or some other DSL that would translate to the required code.

**Comment by ry** [comment]
> As I mentionned another time on Gitter, we're currently writing and comitting boilerplate code by hand in both Rust and Typescript for framebuffer message passing. We should instead generate those from the flabuffers definition files, or some other DSL that would translate to the required code.

Yes - I'm very aware and very concerned about it. We're never going to be able to scale the project to 1000 ops like this. Adding a simple op like `writeFileSync` should be no more a handful of lines of code on both sides.

**Comment by NewLunarFire** [comment]
With a little code re-organization and a templating engine we can get 80% of the way there. 

I know Servo uses Mako, in Python, and I feel that it would fit nicely in our current tooling. But maybe that'g getting too much into technical details for now. Maybe I'm drifting away from the discussion as well.

**Comment by NewLunarFire** [comment]
What about permissions when adding new bindings? You just created #593 for mkdir, and I'm pretty sure we want to enforce --allow-write on this one.

**Comment by Aaronepower** [comment]
In Rust for making large additions such as public APIs or language changes, we use a [RFC] (Request For Comments) process. Where there is a separate repository where people propose ideas and the community gets to provide feedback.

Once the feedback is settled and any changes were made in response a member of the team puts into a FCP(Final Comment Period) with a disposition on whether to accept and merge or to close. This time is about 2 weeks and lets people make a last minute call for any changes to the RFC or to the disposition.

There was even an RFC about the [RFC Process] that goes into a lot more detail.

[RFC]: https://github.com/rust-lang/rfcs
[RFC Process]: https://github.com/rust-lang/rfcs/blob/master/text/0002-rfc-process.md

**Comment by ry** [comment]
@Aaronepower Thanks for the link. That's interesting to see. Although I want an organized method of adding bindings, I also don't want to induce unnecessary bureaucracy. This is still a small project trying to bootstrap - we need to be agile. So definitely everything should happen in this repo... and I don't think we need to worry about ID numbers or anything. Really I'm just looking for a small text document (committed to the repo) which has a checklist of things to consider when adding a binding.

**Comment by NewLunarFire** [comment]
I think we need to organize the repo as people keep adding bindings. The process for adding new privileged calls to deno seems to be much easier to do now, so I strongly suggest we create a structure similar to the one you suggested and ask contributors to abide by it.

**Comment by hayd** [comment]
It would be good to have a hitlist of functionality to add. Perhaps having a central issue with a checklist (to which PRs can reference) would be a start/make this effort a little less ad hoc.

**Comment by ry** [comment]
We're about to refactor how "bindings" (soon to be called "ops") are written. See #674. Once that's complete, we'll add a pull request template describing the process.

@hayd Yes. After we've refactored the bindings. At the moment we're somewhat hesitantly accepting patches - and not ready for a flood of submissions.

**Comment by hayd** [comment]
[Top frequently used python modules](https://www.programcreek.com/python/index/module/?action=index&page=1). I pulled out the top from the first couple of pages:

https://gist.github.com/hayd/742dab707bee1d34f4503357f1909d72

Many deno already has / or v8 comes with. Just throwing this out there...

**Comment by bartlomieju** [comment]
Documentation available at [deno.land](https://deno.land/manual.html) as well as [denolib](https://denolib.gitbook.io/guide/)
