### ISSUE TITLE
debugger flag inspect working same as inspect-brk

### ISSUE THREAD

**Issue by MasterJames** [denoland/deno#5664]
unfortunately it seems the flag '--inspect' is working the same as '--inspect-brk' and does not start running without breaking on the first line of code.

**Comment by bartlomieju** [comment]
@MasterJames thanks for the report, can you provide reproduction example?

**Comment by MasterJames** [comment]
I never ceases to amaze me how quickly you guys resort to that question.
Go here to you help page. https://deno.land/manual/tools/debugger
Run the example but change it to --inspect instead of --inspect-brk

I run a VM on a different machine and IP then my workstation so you might (knowing well the material in question) explore/test or develop official 'tests' for using all the features of the Chrome debug API like --inspect=192.168.1.30:9229 or adding the --port 80 flag to the end of the command etc.

Anyway not sure how much easier you need this explained. Thanks for the timely response and good work your doing to help with this critical step of getting sandboxing right.

I usually open many tabs into multiple sessions while working on a socket communication solution.
Then I use this kind of link maybe you'll find that useful too.
devtools://devtools/bundled/inspector.html?experimental=true&v8only=true&ws=192.168.1.30:9229/ws/aef82016-839d-4607-be85-263130fe2a9d

Chrome on Windows doesn't currently allow links like that ('devtools' protocol) to open with this protocol even if you tweak your registry in win10 etc. but it's super handy shortcut in my situation (many debugger tabs in one window).

BTW (By The Way): Nothing but the title is relevant to understanding this issue.

What should happen is the program runs without having to open the inspector and manually clicking 'run' (in the debugger) to get it to run past the initial first line of code having a breakpoint added. That is exclusively what inspect-brk does. The brk is short for Break.

**Comment by MasterJames** [comment]
Just upgraded to 1.0.1 same issue there still too.

**Comment by bartlomieju** [comment]
@MasterJames thanks for detailed explanation; it is definitely a bug; I'll into it.

**Comment by MasterJames** [comment]
Yah thanks for that! Is there a nightly? No need to answer that. I'll wait for the official upgrade release 1.0.2, or look into that separately I guess thanks.
