### ISSUE TITLE
TextEncoder doesn't exist on type of globalThis

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#5666]
```ts
// main.ts
console.log(globalThis.TextEncoder);
```

```shell
$ deno run main.ts
Compile file:///Users/biwanczuk/dev/deno/main.ts
error: TS2339 [ERROR]: Property 'TextEncoder' does not exist on type 'typeof globalThis'.
console.log(globalThis.TextEncoder);
                       ~~~~~~~~~~~
    at file:///Users/biwanczuk/dev/deno/main.ts:1:24
```

I'd expect that `TextEncoder`/`TextDecoder` would be available on the `globalThis` type. 

Ref #5663

**Comment by bartlomieju** [comment]
Still valid, `lib.deno.window.d.ts` and `lib.deno.worker.d.ts` type declarations should be updated to reflect those values.

**Comment by nayeemrmn** [comment]
This issue isn't fixed for other symbols declared with `declare class`, which I think we decided to favour in the past. Seems like only `declare var` is accessible on `globalThis`, I think we need an upstream solution: https://github.com/microsoft/TypeScript/issues/39504.

**Comment by kitsonk** [comment]
#9782 was reverted

**Comment by bartlomieju** [comment]
Closing in favor of https://github.com/denoland/deno/issues/9957
