### ISSUE TITLE
passing v8 flags using env variables

### ISSUE THREAD

**Issue by rainder** [denoland/deno#5669]
It should be possible to pass v8-flags as env variable as well as command line args.

### Use case

when building docker images you bake command into the image itself
`CMD ["deno", "run", "--allow-net", "<...otherArgs>", "main.ts"]`

Sometimes you might want to allocate different amount of memory to the process based on the environment container is running. Or you might want to expose GC on dev env only.
ATM the only way to pass any v8 flag to deno is to overwrite the whole command.

### Proposal

add support for Deno to read v8 flag values from both sources - command args and env variable.
ie V8 flags could be passed by using `--v8-flags` argument or `V8_FLAGS` env variable.

**Comment by vegerot** [comment]
Would this require allow-env? Or would this just be during Deno startup

**Comment by rainder** [comment]
I believe this should not require allow-env as V8_FLAGS env variable would affect only Deno engine itself.
Code, which is being executed, doesn't really care if that env variable is set or not. Hence, no reason of requesting permission to access it.

**Comment by vegerot** [comment]
That's what I figured.  Thanks 🙂

**Comment by bartlomieju** [comment]
@ry WDYT? I'm not keen on adding another env variable, but the use case seems valid.

**Comment by ry** [comment]
Is there precedence for this in Node? 

I'm open to the idea - but also think we should strive to keep the number of env vars minimal.

**Comment by vegerot** [comment]
@ry sort of related there is [NODE_OPTIONS](https://nodejs.org/api/cli.html#cli_node_options_options), where you can specify some v8 flags
