### ISSUE TITLE
Uncaught ReferenceError: ErrorEvent is not defined

### ISSUE THREAD

**Issue by ljjumper** [denoland/deno#5674]
Trying to run following code:
```
// server.ts
import { Application, Router } from 'https://deno.land/x/oak/mod.ts'

const app = new Application()

const port = 5000
console.log(`Server running on port ${port}`)

await app.listen({ port })
```

with this startup command: 
`deno run --allow-net server.ts`

I know that there should follow a middleware error, but instead I seem to receive this error:
```
error: Uncaught ReferenceError: ErrorEvent is not defined
export class ApplicationErrorEvent<S extends State> extends ErrorEvent {
                                                            ^
    at application.ts:78:61
```

Probably a error with the oak dependency itself, but wanted to report it since it seems to be such an essential one.

**Comment by bartlomieju** [comment]
What is Deno version producing this error? It most likely outdated; `ErrorEvent` was added to global scope in https://github.com/denoland/deno/releases/tag/v1.0.0-rc3

**Comment by ljjumper** [comment]
@bartlomieju oh you are totally right, I forgot to update my deno version (0.42.0). 

Thank you very the quick help. Gonna close the issue again. Have a great day!

**Comment by GeekRishabh** [comment]
Hello @chrisfroeschl I am still getting this error.

```
deno 0.42.0
v8 8.2.308
typescript 3.8.3
```
Have got the latest version v1.0.2 but still facing this

**Comment by chrisfroeschl** [comment]
@GeekRishabh are you sure about that? 
If so, I don't understand why you would quote:
```
deno 0.42.0
v8 8.2.308
typescript 3.8.3
```
instead of:
```
deno 1.0.2
v8 8.4.300
typescript 3.9.2
```

Just try `deno upgrade` if you are unsure.

**Comment by GeekRishabh** [comment]
Thanks @chrisfroeschl It worked. I was updating it through `brew`

**Comment by chrisfroeschl** [comment]
You're welcome. Already thought about recommending `brew`, but since not everybody is on mac I didn't consider it. Have fun!
