### ISSUE TITLE
Broken module binding with top level await & dynamic import 

### ISSUE THREAD

**Issue by mdarse** [denoland/deno#5677]
Hi, I’m encountering an issue with a combination of modules, top-level `await` & dynamic `import`. Here is a [minimal example reproducting the issue](https://gist.github.com/mdarse/c27f5d52455938241cfc7ab7c0cec946/89773d3a100792298e7101444918da295311efef).

You can run it with the following command:
```sh
deno run --allow-net https://gist.githubusercontent.com/mdarse/c27f5d52455938241cfc7ab7c0cec946/raw/89773d3a100792298e7101444918da295311efef/a.js
```

What’s weird though, is that [it works as expected](https://gist.github.com/mdarse/c27f5d52455938241cfc7ab7c0cec946/875f44dce3c63224a9408464108c9ad20f647749) if I replace `export default x` with `export { x as default }` in `b.js`. You can try it with this command:
```sh
deno run --allow-net https://gist.githubusercontent.com/mdarse/c27f5d52455938241cfc7ab7c0cec946/raw/875f44dce3c63224a9408464108c9ad20f647749/a.js
```

Not sure if this is the same issue as #5215 though.

---
```
❯ deno --version 
deno 1.0.0
v8 8.4.300
typescript 3.9.2
```

**Comment by bartlomieju** [comment]
```
// a.ja
import B from "./b.js";
console.log(B); // "undefined"
```
```
// b.js
let x;
export default x;
x = await import("./c.js").then((mod) => mod.default);
```
```
// c.js
export default 'X';
```

Just tried on latest `master` and the result is still `undefined`.

**Comment by bartlomieju** [comment]
@mdarse I just verified this problem again - both Deno and Node return `undefined` when this module is run and I believe this is correct behavior.

**Comment by mdarse** [comment]
I just had another look at the issue & found [an article describing expected behaviour](https://v8.dev/features/top-level-await) on v8’s blog.

Quoting the author, here’s what should happen:
> 1. The execution of the current module is deferred until the awaited promise is resolved.
> 2. The execution of the parent module is deferred until the child module that called await, and all its siblings, export bindings.

I just tested on `v1.4.6` and I still get `undefined` instead of the expected value. I think this issue should be re-open the reflect that.

**Comment by lucacasonato** [comment]
The fix landed in `1.5.0` which was released a few hours ago. Would you mind testing on that version?

**Comment by mdarse** [comment]
Oh nice! I will try again on that version and report my results here.

**Comment by mdarse** [comment]
> ❯ deno --version && deno run --allow-net https://gist.githubusercontent.com/mdarse/c27f5d52455938241cfc7ab7c0cec946/raw/89773d3a100792298e7101444918da295311efef/a.js
deno 1.5.0
v8 8.7.220.3
typescript 4.0.3
undefined

Unfortunately, that doesn’t seem to be fixed.

**Comment by lucacasonato** [comment]
@mdarse The behaviour in 1.5.0 is intended as it is. Chrome, Deno, and Node all agree on the behaviour. They all output `undefined` when you run this script. To try TLA in Chrome, enable the `#enable-javascript-harmony` flag.

**Comment by kitsonk** [comment]
It is the expected behaviour.

It actually has nothing to do with top level await, ES modules are immutable, and are two phase.  Once the bindings are determined, the module is released, so you have to do something that blocks the creation of the binding.  Once you export default something, it's value becomes fixed.  V8 is smart enough to realise this and there doesn't block execution, because it "knows" the shape of the module (_and all its siblings, export bindings_).

For example if you run this under Deno or Node, you also get undefined:

*a.mjs*

```js
import b from "./b.mjs";
console.log(b);
```

*b.mjs*

```js
let b;
export default b;
b = "b";
```

This of course is why some people felt TLA could become a footgun! 😁

**Comment by mdarse** [comment]
That makes sense for me now, I thought module execution was deferred until both *definition* and `await` related *assignation* did take place.

My `b.js` should have been:
```js
let x;
// assignation & export in the same statement
export default x = await import("./c.js").then((mod) => mod.default);
```

Concerning the variation in behaviour between `export { x as default }` & `export default x;` that I did observe, I think this is due to the former expecting a variable name as `x` while the later expects an _expression_.

Thanks @kitsonk for articulating TLA related vs ESM related behaviour & to everyone else for your time 🙂

**Comment by kitsonk** [comment]
Yeah, I haven't dug into why a named export behaves different than a default export.  I suspect there are semantics buried deep in the spec.
