### ISSUE TITLE
Expose internal `assert` globally.

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#5684]
While it isn't a browser standard, Node.js includes an `assert()` globally.  We heavily use `assert()` in the internal code, but at runtime there is no `assert()` available.

Exposing it as `Deno.assert()` would be problematic in TypeScript because of https://github.com/microsoft/TypeScript/issues/37818 as it would require a type annotation all the time if you tried to destructure it and it looks like it is unlikely to ever be addressed in TypeScript because of design limitations.

We have `assert()` in `std/testing/asserts.ts` but including a testing module just to be able to do an `assert()` seems very heavy weight as it includes two other dependencies as well:

```
https://deno.land/x/std/testing/asserts.ts
  ├── https://deno.land/x/std/fmt/colors.ts
  └── https://deno.land/x/std/testing/diff.ts
```

So while it isn't ideal to have something in the global namespace that isn't in browsers, it is a minor variation that makes it significantly easier to write better code, especially since `assert()` also provides type narrowing in TypeScript now.

**Comment by nayeemrmn** [comment]
> Node.js includes an `assert()` globally.

It doesn't, I think you saw the behaviour where all of the built-in modules are automatically exposed as globals in the REPL.

**Comment by kitsonk** [comment]
Grr... you are right... 😢

(╯°□°)╯︵ ┻━┻

**Comment by ry** [comment]
I'm reluctant to add non-standard globals.

**Comment by bartlomieju** [comment]
In light of https://github.com/denoland/deno/pull/6252#issuecomment-680878871 this issue can be closed.
