### ISSUE TITLE
Incorrect/ Confusing documentation for `Deno.permissions`

### ISSUE THREAD

**Issue by bhumijgupta** [denoland/deno#5692]
Following the documentation of Deno.permissions.request on https://deno.land/typedoc/classes/deno.permissions.html#request, you can see the example mentions
```javascript
const status = await Deno.permissions.request({ name: "env" });
  if (status.state === "granted") {
    console.log(Deno.homeDir());
  } else {
    console.log("'env' permission is denied.");
  }
```
I could not find any reference to `Deno.homeDir()` in the documentation. Also when compiling this example, I get error `TS2339 [ERROR]: Property 'homeDir' does not exist on type 'typeof Deno'.`

Would like to confirm if it's a documentation error. If yes, then I'd like to take up this issue and replace it with `console.log(Deno.env.get("HOME"))`.

## Configuration
deno 1.0.0
v8 8.4.300
typescript 3.9.2

**Comment by bhumijgupta** [comment]
On running the full example, I get error `TS2339 [ERROR]: Property 'permissions' does not exist on type 'typeof Deno'.`

**Comment by nayeemrmn** [comment]
It's now `Deno.dir("home")`. You need the `--unstable` flag. Note that `deno.land/typedoc` may be removed soon.

(https://deno.land/typedoc shows up to date documentation, I'm not sure why https://deno.land/typedoc/classes/deno.permissions.html exists and why it shows out of date documentation...)

**Comment by bhumijgupta** [comment]
@nayeemrmn I guess the documentation is generated from https://github.com/denoland/deno/blob/6072755eadb7342a409f43260e5a17b956703a1c/cli/js/lib.deno.unstable.d.ts#L1210  Will it be fine, if I create a PR to change it to `Deno.dir("home")`

**Comment by bartlomieju** [comment]
> @nayeemrmn I guess the documentation is generated from
> 
> https://github.com/denoland/deno/blob/6072755eadb7342a409f43260e5a17b956703a1c/cli/js/lib.deno.unstable.d.ts#L1210
> 
> Will it be fine, if I create a PR to change it to `Deno.dir("home")`

@bhumijgupta yes, please
