### ISSUE TITLE
404 on importing type declarations files from pika.dev using Deno 1.0.1

### ISSUE THREAD

**Issue by mdubourg001** [denoland/deno#5696]
Hi there,

I've been working on some tooling that requires the use of a module I import from cdn.pika.dev. as follows:

```typescript
import { parse } from "https://cdn.pika.dev/html5parser@^1.1.0";
```

These imports used to work when I was using Deno 1.0.0-rc3, but ever since I upgraded to the last Deno release (1.0.1), these imports break to a 404 error:

```text
error: Import 'https://cdn.pika.dev/-/html5parser@v1.1.2-0fAkC9viFOtRB3VnrC0m/dist=es2019,mode=types/types.d.ts' failed: 404 Not Found
```

As mentioned in [this issue I commented on](https://github.com/pikapkg/cdn/issues/8) on the pika/cdn repo, I first thought the issues came from Pika, but I just tried to downgrade to Deno 1.0.0-rc3, and the imports work great again.

**Comment by bartlomieju** [comment]
Must be related to #5029; needs more investigation

**Comment by bartlomieju** [comment]
@mdubourg001 I'm not sure if that's a Deno bug, I've written down my findings: https://github.com/pikapkg/cdn/issues/8#issuecomment-632300743

**Comment by bartlomieju** [comment]
Okay I found the issue after all; #5029 introduced bad redirection handling which causes this problem. I'll fix it.
