### ISSUE TITLE
listen unix socket cause "Uncaught InvalidData"

### ISSUE THREAD

**Issue by codehz** [denoland/deno#5700]
Source code:
```typescript
const listener = Deno.listen({ transport: "unix", path: "./test.sock" });
```
Command line:
```bash
deno run --unstable --allow-all mod.ts
```
Result:
```bash
error: Uncaught InvalidData: data did not match any variant of untagged enum ArgsEnum
    at unwrapResponse ($deno$/ops/dispatch_json.ts:43:11)
    at Object.sendSync ($deno$/ops/dispatch_json.ts:72:10)
    at Object.listen ($deno$/ops/net.ts:51:10)
    at Object.listen ($deno$/net_unstable.ts:33:24)
    at file:///path/to/mod.ts:1:23
```
Deno Version: 1.0.1
OS: Windows 10 Version 10.0.18363.836

**Comment by danbulant** [comment]
Relevant: manyuanrong/deno_mysql#59

It looks like using `--unstable` flag cause problems with TCP connections (both `listen` and `connect`). Tested on 1.0.1, 1.1.0 and 1.1.1 (latest stable). Platform probably irrelevant, I reproduced it windows 10 and debian buster (+ on glitch).

**Comment by danbulant** [comment]
@codehz Does it still throw that error without using unstable?

**Comment by codehz** [comment]
> @codehz Does it still throw that error without using unstable?

it is expected, because it is marked as unstable api

**Comment by danbulant** [comment]
> it is expected, because it is marked as unstable api

I was asking since my error (which is similar) with the `Deno.connect` shows regardless if using stable or unstable (which isn't expected)

**Comment by lucacasonato** [comment]
`transport: "unix"` does not work on Windows. I think this is not a bug, it just needs a better error message.

**Comment by danbulant** [comment]
I think I somehow fixed the issue for myself, so I can't really help now.

I was using linux when I commented, so the error still happened even though I was on unix-compatible platform.

**Comment by codehz** [comment]
> `transport: "unix"` does not work on Windows. I think this is not a bug, it just needs a better error message.

It works since build 17063 https://devblogs.microsoft.com/commandline/af_unix-comes-to-windows/
