### ISSUE TITLE
Issue with Deno pulling older version of library from deno.land?

### ISSUE THREAD

**Issue by ansonfoong** [denoland/deno#5702]
So I have this library https://deno.land/x/katana and I'm trying to import it as so:

```
import { Client } from 'https://deno.land/x/katana/mod.ts'
```
However, when I run deno run ./nameoffile.ts it will download all modules but this one 
```
error: Import 'https://deno.land/x/katana/src/client/ws/Websocket.ts' failed: 404 Not Found
```
The issue is I think I used to have a file named "Websocket.ts", however I changed the name and capitalized it to WebSocket.ts, 
```
https://deno.land/x/katana/src/client/ws/WebSocket.ts
```
So it's not recognizing the new name it seems.
How can I fix this?

**Comment by fox-cat** [comment]
seems to be an issue on your end,
in [your code](https://deno.land/x/katana/src/client/Client.ts), you're still importing with the old name
![image](https://user-images.githubusercontent.com/30391304/82551617-60456300-9b15-11ea-878a-455bad620586.png)
