### ISSUE TITLE
imports bypass --allow-net

### ISSUE THREAD

**Issue by Rubybb** [denoland/deno#5705]
honestly it's pretty iffy, but you can pretty easily get around --allow-net.

```js
import test1 from "https://pine-cosmic-vibraphone.glitch.me/?url=https://jsonplaceholder.typicode.com/users";
console.log(JSON.parse(test1));

...
// server (pine-cosmic-vibraphone.glitch.me)
app.use(async (ctx) => {
  let url = ctx.request.url.searchParams.get("url");
  
  if (url) {
    let request = await fetch(url);
    let text = await request.text();
    
    ctx.response.type = "text/javascript";
    ctx.response.body = `export default ` + JSON.stringify(text) + `;`;
  }
});

**Comment by nayeemrmn** [comment]
How can you exfiltrate user data with this method?

**Comment by RubyBae** [comment]
I haven't been able to directly pass anything to the url, but regardless,
it's still a way to get around --allow-net for top level *fetch* requests.

**Comment by nayeemrmn** [comment]
@RubyBae No... that's how the source code server is coded. The server can do what it wants here as long as it isn't using data taken from the user's machine at runtime, which it can't for static imports.

**Comment by RubyBae** [comment]
`Secure by default. No file, network, or environment access, unless
explicitly enabled.`
That's clearly network access where it's not explicitly enabled.

and no, deno is designed so the server can't do what it wants.

**Comment by nayeemrmn** [comment]
Again, it's network access by the file server serving the module. It's not allowing runtime network access for a module running on your machine.

> I haven't been able to directly pass anything to the url

There is a reason for this 😄

**Comment by RubyBae** [comment]
Yes I understand that, but none the less, It's still a potential way to get around the flag.
I can see it easily being to log an install to statistic server or whatnot, just because it's not in runtime, doesn't mean the data returned isn't inaccessible.

**Comment by Soremwar** [comment]
@RubyBae Under that logic, Deno should also request access to the filesystem in order to execute your code. The sandbox isn't meant to prevent Deno from accessing your code, but to prevent any side effects this code can cause to your system.

Unless fetching resources contributes to a security breach, the sandbox remain secure.

**Comment by nayeemrmn** [comment]
> Yes I understand that, but none the less, It's still a potential way to get around the flag.

I just explained to you that it's not, what did you understand? Yes, when you fetch remote code, the entity providing you with that code can log that they did so. That's not what the flag is supposed to protect from.

**Comment by RubyBae** [comment]
> > Yes I understand that, but none the less, It's still a potential way to get around the flag.
> 
> I just explained to you that it's not, what did you understand? Yes, when you fetch remote code, the entity providing you with that code can log that they did so. That's not what the flag is supposed to protect from.

Right, and what's the flag designed to prevent?

**Comment by nayeemrmn** [comment]
> It's not allowing runtime network access for a module running on your machine.

**Comment by Soremwar** [comment]
@RubyBae The flag is supposed to prevent you from broadcasting.

You can still make `fetch` without a permission hassle.

**Comment by nayeemrmn** [comment]
@bartlomieju Can this be closed?
