### ISSUE TITLE
Inconsistency in std/http file naming

### ISSUE THREAD

**Issue by witcher112** [denoland/deno#5706]
Hi!

I've discovered a little file naming inconsistency in `std/http` module. While names in the module seem to be relative to `http` part (with some exceptions like `HTTPOptions`), just like file names, two files stand out from others:

- `http_status.ts`
- `http_bench.ts`

Is this intentional?

I'm bringing this issue here since Deno aspires to be a very interesting alternative to Node, so it would be cool to have file consistency in names, as of new way of importing modules via file names.

Cheers!

**Comment by bartlomieju** [comment]
I guess it makes sense. Contributions welcome.

**Comment by witcher112** [comment]
What would be the best way to approach this contribution, since it could result in major change?

Leave the old files/names to work as a proxy to the new ones, and mark the previous ones as deprecated (if there's any way for it)?

**Comment by bartlomieju** [comment]
@witcher112 `std` is currently unstable so a simple rename would be fine
