### ISSUE TITLE
Pronunciation

### ISSUE THREAD

**Issue by billythekid** [denoland/deno#5707]
How is Deno pronounced? 

Is it like the dinsoaur pet of the Flintstones, Dino "deeno"? (it has a similar looking dinosaur mascot after all)

Is it "denno", like the start of the audio company Denon's name?

so DE-no or DEN-o?

Thanks

**Comment by nayeemrmn** [comment]
Please use the Discord for questions like this: https://discord.gg/deno.

**Comment by pedropaulosuzuki** [comment]
It should be pronounced as ""Denno"", as **Ryan Dahl** himself presented at the [10 Things I Regret About Node.js](https://youtu.be/M3BM9TB-8yA?t=1000) presentation at [JSConf EU](https://2018.jsconf.eu/speakers/ryan-dahl-propel-a-machine-learning-framework-for-javascript.html). Anyway, the way you pronounce Deno is not more important than the code you write with it.

**Comment by kitsonk** [comment]
@pedropaulosuzuki that has been revised.  It is `dee-noh` (ref a talk Ry and I gave late 2019: https://www.youtube.com/watch?v=1gIiZfSbEAE)

But yes, as @nayeemrmn says, Discord is a better place to discuss questions like this.

**Comment by stannlee** [comment]
It should be De nno

**Comment by azim254** [comment]
yea deh - no

**Comment by billythekid** [comment]
Thanks everyone. Denno it is!

**Comment by SyrupThinker** [comment]
Lets stop using these writings because they don't help one bit for non-native speakers.
Its https://www.youtube.com/watch?v=1gIiZfSbEAE&t=41

**Comment by stannlee** [comment]
> Lets stop using these writings because they don't help one bit for non-native speakers.
> Its https://www.youtube.com/watch?v=1gIiZfSbEAE&t=41

Oops I'm so sorry for my insensitivity

**Comment by Firanolfind** [comment]
> Lets stop using these writings because they don't help one bit for non-native speakers.
> Its https://www.youtube.com/watch?v=1gIiZfSbEAE&t=41

hilarious stand-up

**Comment by SyrupThinker** [comment]
> > Lets stop using these writings because they don't help one bit for non-native speakers.
> > Its https://www.youtube.com/watch?v=1gIiZfSbEAE&t=41
> 
> hilarious stand-up

That was not an attempt to stand up for anyone but one for pointing out that using "dee-no" et all for
transcribing pronunciation is a futile effort because of pronunciation differences (which exist in English dialects as well, so my phrasing was kind of pointless)

**Comment by kitsonk** [comment]
International Phonetic Alphabet: [/diˈ-no̩/](http://ipa-reader.xyz/?text=di%CB%88no%CC%A9&voice=Joey)

**Comment by sheriffderek** [comment]
I can see Ryan saying it both ways - and more recently, pronouncing it "Deeeno." So, maybe we should tell him what was decided! hahaha (+1 for pronouncing it how it's spelled)
https://vimeo.com/432564160

**Comment by nayeemrmn** [comment]
@sheriffderek As in, decided by the author of this issue who ignored up-to-date video evidence in favour of responses from random people? Yeah someone should tell Ryan already, he clearly hasn't been updated!

**Comment by sheriffderek** [comment]
I have a feeling - that we could ask Ryan - and just decide. But - he also might just say - "either way."

**Comment by pedropaulosuzuki** [comment]
> I have a feeling - that we could ask Ryan - and just decide. But - he also might just say - "either way." (but he does like typescript...)

No need to ask Ryan. One of the lead developers already gave us the answer in this own thread: Kitson Kelly himself. Also, the thread is dead by a month, no need to revive it again. What you can do with software is more important than the name you give to it.

**Comment by StanleyMasinde** [comment]
> > I have a feeling - that we could ask Ryan - and just decide. But - he also might just say - "either way." (but he does like typescript...)
> 
> No need to ask Ryan. One of the lead developers already gave us the answer in this own thread: Kitson Kelly himself. Also, the thread is dead by a month, no need to revive it again. What you can do with software is more important than the name you give to it.

Relax man, 🤣🤣 You are too serious. loosen up a bit

**Comment by sheriffderek** [comment]
I know it's _silly_... but - if someone is going to spend months creating a course - or help the community by creating a tutorial etc. - then it's not really fair to put them in a position where they say "Deeeno" a thousand times - and then later - thousands of people with nothing better to do - make a comments about how they are saying it _wrong_. Based on this thread - I'm am sure that will be the case / But - I don't care anymore now.

**Comment by nayeemrmn** [comment]
> I can see Ryan saying it both ways ... (+1 for pronouncing it how it's spelled)

> he also might just say - "either way."

> it's not really fair to put them in a position where they say "Deeeno" a thousand times - and then later - thousands of people with nothing better to do - make a comments about how they are saying it _wrong_. Based on this thread - I'm am sure that will be the case

@sheriffderek The pronunciation is already decided: it used to be pronounced [/dɛno/](http://ipa-reader.xyz/?text=d%C9%9Bno&voice=Joey) but has been revised to [/di no/](http://ipa-reader.xyz/?text=di%20no&voice=Joey) ([ref](https://www.youtube.com/watch?v=1gIiZfSbEAE#t=20)). The references in this thread have already made that clear. You've expressed that you prefer the first way and have continued to muddy the waters by "voting" for it and speaking as if it's still up in the air. Your last comment says that you still haven't acknowledged the correct one. Won't that put someone in the position you speak of?

**Comment by ry** [comment]
As others have said, the pronunciation rhymes with the city Reno, Nevada. Or like the Flintstone's character.

I keep mispronouncing it tho.

**Comment by sheriffderek** [comment]
Sorry, fellas. It was not clear to me from reading the thread that there was any official conclusion - and I had no intention to push an agenda. I care 0% what way it's pronounced. I just want to pronounce it correctly. If it's not clear - after I spent hours researching it - then I guess I'm just a complete idiot. I'll think on this - and try to figure out how to not be so stupid in the future. Thanks for the gracious help. <sarcasm>I've got a really great feeling about this community already</sarcasm>.

**Comment by pedropaulosuzuki** [comment]
> 
> 
> Sorry, fellas. It was not clear to me from reading the thread that there was any official conclusion - and I had no intention to push an agenda. I care 0% what way it's pronounced. I just want to pronounce it correctly. If it's not clear - after I spent hours researching it - then I guess I'm just a complete idiot. I'll think on this - and try to figure out how to not be so stupid in the future. Thanks for the gracious help. I've got a really great feeling about this community already.

No need to play the victim. Github issues are for reporting bugs, suggesting features, contributing to the project. Off-topic questions should be posted somewhere else, such as in the forum.

**Comment by kitsonk** [comment]
For clarity, since people seem to be obsessed by this, originally there was no official pronunciation.  As Ry stated he was pronouncing it one way.  I was pronouncing originally as it is the official pronunciation, but then several of us had a conference call and Ry was saying it the way he originally said it, so I switched.

When Ry and I met up before our talk a TSConf 2019 in Seattle, it ended up being one of the big topics we talked about and Ry said "I keep calling it den-oh but maybe we should be calling it dee-noh as it makes more sense with our mascot".  I joked about how I had always assumed it was dee-noh because of that, but switched when I heard him pronounce it.  Both of us struggled on stage the next day to pronounce it right (and Ry makes a statement to the effect that the pronunciation was agreed).

So now everyone has a nice origin story they can hang their hat on.

**Comment by StanleyMasinde** [comment]
Aaa gentlemen, I believe we have open 615 issues to address

**Comment by mfulton26** [comment]
Can the official pronunciation be added somewhere on the deno site? I have been pronouncing it wrong myself and I think it would be nice for new folks who land on the home page, the manual, and/or an FAQ to get the right pronunciation early on instead of reading it wrong to themselves lots of times while learning deno only to have to change when they start speaking about it with others.
