### ISSUE TITLE
drun is not able to restart the server

### ISSUE THREAD

**Issue by RajatPalankar8** [denoland/deno#5710]
Drun is compiles and runs my code successfully in first run but when i make some changes and save it, is  giving me **Error: Not yet implemented**

**Terminal**
PS C:\Users\rajat\Desktop\demo> drun --entryPoint=./index.ts
Compile file:///C:/Users/rajat/Desktop/demo/index.ts
Serving on http://0.0.0.0:3000/
**Error: Not yet implemented**
    at Object.kill ($deno$/ops/process.ts:8:11)
    at Process.kill ($deno$/process.ts:89:5)
    at Runner.run (https://deno.land/x/drun@v1.0.0/src/runner.ts:69:17)
    at async main (https://deno.land/x/drun@v1.0.0/drun.ts:11:3)
    at async https://deno.land/x/drun@v1.0.0/drun.ts:16:5
PS C:\Users\rajat\Desktop\demo>

**Comment by SyrupThinker** [comment]
Please not that drun is not part of the Deno project, this should have been reported on their project first.

`kill` was not implemented for Windows before Deno version 1.0.1 . Please update your Deno installation, for example, with `deno upgrade`.

**Comment by bartlomieju** [comment]
Closing as stale. Feel free to reopen if needed.
