### ISSUE TITLE
Deno.connect() refuses to connect on windows

### ISSUE THREAD

**Issue by Clearbryan** [denoland/deno#5711]
Running `Deno.connect({options})` always fails on windows machines. Throws an `(os error 10061)`. Is this the behaviour or something else?

**Comment by lucacasonato** [comment]
Can you connect to the remote when using a different OS, or when using for example Node?

**Comment by Clearbryan** [comment]
Not sure about a different OS but I can connect to using Node

**Comment by lucacasonato** [comment]
Can you provide an example of what you are running?
