### ISSUE TITLE
MAKE deno SIMPLER and EASIEr with GUI instead on only commands

### ISSUE THREAD

**Issue by fisforfaheem** [denoland/deno#5728]
tired of commands we demand a GUI based creations and more GUI and less commands like no commands

**Comment by locness3** [comment]
LOL, there can't be GUIs for everything, you'll have to get used to the command line man.

**Comment by Wallacy** [comment]
https://github.com/you-dont-need/You-Dont-Need-GUI

**Comment by fisforfaheem** [comment]
No bro, i love making windows forms apps and also other platforms, aso
thier should be an easy way to make apps like that,, and oyu can make
alot with GUI command lines is so old

**Comment by Wallacy** [comment]
You need to use the right tool to the right problem;

The idea that a GUI is necessarily better is false;

**Comment by ry** [comment]
Deno is a command line program
