### ISSUE TITLE
Source maps are slow

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#5729]
Whenever error occurs it takes quite a lot of time before it's reported to the terminal. My guess is that source maps are written in such a way that for each frame file is read from disk, relevant line found and copied and the rest is discarded. This issue should be investigated to confirm the thesis. Ultimately acquisition of source maps should be rewritten by decoupling `TsCompiler` from `SourceMapGetter`.

**Comment by kitsonk** [comment]
Hrmmm... We added a benchmark for this when we had performance issues before, but there appears to be no issue: https://deno.land/benchmarks.  So either the test is wrong or we don't have a performance issue.

**Comment by bartlomieju** [comment]
![Screenshot 2020-05-22 at 11 55 45](https://user-images.githubusercontent.com/13602871/82655937-337f7180-9c23-11ea-8e00-d1ba8fec3c07.png)

@kitsonk problem can be seen in the picture - the red line that dropped significantly is the result of fix in #5422 - before that PR there was error raised. As soon as it was fixed execution time went from 0.5s to 0.22s.

**Comment by kitsonk** [comment]
This has been largely resolved.
