### ISSUE TITLE
Syntax error leads to non-sensible errors 

### ISSUE THREAD

**Issue by ThePrimeagen** [denoland/deno#5739]
With the following code I get almost no output.

```
import {
    serve,
} from "https://deno.land/std/http/server.ts";
const s = serve({
    port: 8000
});

for await (const req of s) {
    let lolomo:
}
```

Here is me running the script
```
> deno run -A index.ts
error: 
```

**Comment by kitsonk** [comment]
We must be choking on that dependency parse in a not very useful way @bartlomieju the debug logs don't help:

```
Deno isolate init with snapshots.
rust:shared_queue:reset
DEBUG JS - cwd /Users/kkelly
DEBUG JS - args []
main_module file:///Users/kkelly/test.ts
fetch_source_file specifier: file:///Users/kkelly/test.ts 
⚠️️  Granted read access to "/Users/kkelly/test.ts"
fetch_source_file specifier: file:///Users/kkelly/test.ts 
error: 

~ 
```

**Comment by DiegoTeles** [comment]
@ThePrimeagen Send the complete code, so we can test and validate some things.
In your example information is missing within the for (), and if possible send the error output so that we can analyze.

tks

**Comment by ThePrimeagen** [comment]
That is literally the complete example. I accidentally got distracted on stream tonight and left it in this state, then confused by the error.

Any extra code would be superfluous.

**Comment by kitsonk** [comment]
@DiegoTeles the OP has provided sufficient information.  Deno should not error on syntax errors this way.  The issue is valid.
