### ISSUE TITLE
Permission denied when using Deno.watchFs() relative path

### ISSUE THREAD

**Issue by evandropomatti** [denoland/deno#5742]
The following code will fail when running with `deno run --allow-read=./src app.ts`

```js
const watcher = Deno.watchFs("./src");
for await (const event of watcher) {
  console.log(">>>> event", event);
  // { kind: "create", paths: [ "/foo.txt" ] }
}
```

Error:

```sh
error: Uncaught PermissionDenied: read access to "./src", run again with the --allow-read flag
    at unwrapResponse ($deno$/ops/dispatch_json.ts:43:11)
    at Object.sendSync ($deno$/ops/dispatch_json.ts:72:10)
    at new FsWatcher ($deno$/ops/fs_events.ts:15:16)
    at Object.watchFs ($deno$/ops/fs_events.ts:38:10)
    at file:///home/pomatti/projects/dumb-deno/app.ts:1:22
```

However if i change the first line of the script to use an absolute path it works fine:

```js
const watcher = Deno.watchFs("/home/pomatti/projects/dumb-deno/src");
```

I guess `Deno.watchFs()` must allow relative paths when `--allow-read` is informed on startup?

**Comment by zhanyuzhang** [comment]
Maybe you should use `deno run -A` to try it again ? Because it's possible needing other permission.

**Comment by evandropomatti** [comment]
@zhanyuzhang if I put the absolute path it works, and also the initial error message says "read access". It is something to do with the fact that I specifying the path in `--allow-read`.

**Comment by bartlomieju** [comment]
Paths should be resolved relative to CWD when creating new watcher. Looks like a bug.
