### ISSUE TITLE
Could not install deno with curl (SSL Certificate problem)

### ISSUE THREAD

**Issue by anuraghazra** [denoland/deno#5748]
While running the cURL installation command on Git base i encountered this error, any way to fix it?

```sh
$ curl -fsSL https://deno.land/x/install/install.sh | sh -s v1.0.1
curl: (60) SSL certificate problem: self signed certificate in certificate chain
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

OS: Windows_NT x64 6.1.7601 (Windows 7 64bit)

**Comment by anuraghazra** [comment]
Update: I modified the install.sh script and added "-k" flag on curl calls and it successfully installed deno, but now i'm getting this

```sh
$ deno
bash: /c/Users/user/.deno/bin/deno: cannot execute binary file: Exec format error
```

**Comment by lucacasonato** [comment]
This seems like an issue with your local network. https://deno.land/ has a valid certificate.

**Comment by MarkTiedemann** [comment]
@anuraghazra For installing Deno on Windows, please use the PowerShell installer. The Shell installer only installs binaries for MacOS or Linux.
