### ISSUE TITLE
VS Code extension situation needs addressing urgently | Discussion

### ISSUE THREAD

**Issue by David-Else** [denoland/deno#5751]
Before Deno 1.0 we had https://github.com/axetroy/vscode-deno which had a huge amount of work done on it and was working great. The https://github.com/justjavac/vscode-deno had become abandon ware and was causing problems splitting the user base. No updates for months or support.

It was decided we needed an official extension, which was to live at https://github.com/denoland/vscode_deno.  Then the problems began.

- How come we did not use the working axetroy extension and build on that? We are a week and a half past 1.0 and the justavac extension that has become official is still not working properly for many users: https://github.com/denoland/vscode_deno/issues
- The working axetroy version is sitting on the market place marked as depreciated
- There is **still** no official working extension that users can find on the Market place. We have https://marketplace.visualstudio.com/items?itemName=justjavac.vscode-deno which is basically the same old  justjavac version. No mention it is official, and it does not work properly.

May I suggest:
1. A new official market place Deno plugin page is created which makes it clear it is the official plugin. It does not matter if it has zero downloads, simply link it in the official docs and depreciate the other extensions. Soon it will take over.
2. The axetroy extension is used as the base for the new version as it is working now and I have heard no evidence it is inferior in any way.

It seems like at the moment we are in the most confusing and bad situation for VS Code users we have been in. I really appreciate the hard work axetroy and justjavac have done on their extensions, but time is ticking on and users will be leaving Deno as they want VS Code support. Surely we should be using the best extension right now rather than waiting for the justjavac one to be finished? It is just taking too long, and I don't understand what the point is?

**Comment by vegerot** [comment]
Jooc, what is the coc Deno plug-in based off of?

**Comment by kitsonk** [comment]
This issue if for the plugin repo, https://github.com/denoland/vscode_deno/issues, not this repo.

**Comment by David-Else** [comment]
@kitsonk Please feel free to move it if you like, but I think someone senior needs to make a quick decision on this and it is less likely to get attention from them there. What do you think of my proposal?

**Comment by ry** [comment]
I've just now published https://marketplace.visualstudio.com/items?itemName=denoland.vscode-deno from https://github.com/denoland/vscode_deno

@David-Else I appreciate you raising the issue - I don't personally use vscode so any problems with the plugin aren't very visible to me. That said, "urgent" is a poor adjective to use when referring to free software - all of this is people's donated time - nothing is urgent. Please help make it better by contributing to the plugin.

**Comment by David-Else** [comment]
@ry sorry, you are right, urgent was the wrong word to use. I did contribute to the Axetroy extension, so it is quite annoying that all that work is going to waste for seemingly no reason.

Great news on the official marketplace entry! Hopefully the official plugin will soon be up to the standard of the Axetroy version and all will be well again in the wonderful world of Deno :)
