### ISSUE TITLE
Why logo looks like helminth?

### ISSUE THREAD

**Issue by Firanolfind** [denoland/deno#5753]
I know this is might be stupid issue, but I can't stand this logo :D It looks like a worm in some dark place, you know.

**Comment by leopiccionia** [comment]
It's a long-necked dinosaur (a pun with "Deno", [that's pronounced like _dee-noh_](https://github.com/denoland/deno/issues/5707#issuecomment-632450714)), as you can see in the [v1 blog post](https://deno.land/v1).

**Comment by crowlKats** [comment]
Also these kind of discussions do not belong in the issue tracker, but rather on the [discord](https://discord.gg/deno).

**Comment by bartlomieju** [comment]
Please use Discord chat for non-technical discussions.

**Comment by LayneTheEpic** [comment]
I thought it looked like a sock puppet :P
