### ISSUE TITLE
Uuid std lib module > 0.41.0 does not work in browsers

### ISSUE THREAD

**Issue by NathanKleekamp** [denoland/deno#5762]
Version 0.41.0 seems to be the last version supported in the browser.

I've created a small [reproduction repo](https://github.com/NathanKleekamp/deno-uuid-bug) to illustrate. If you clone the repo, and checkout each of the tagged versions, you'll see that it's only at 0.41.0 does it work in browsers.

In Chrome until 0.52.0, and Firefox between version 0.42.0 and 0.50.0, it complains `Uncaught ReferenceError: Deno is not defined`.

In Firefox, version 0.50.0 and greater, it complains `SyntaxError: private fields are not currently supported`.

**Comment by lucacasonato** [comment]
`std/uuid/v5` uses `std/testing/asserts` which uses the Deno namespace. As a workaround you can use `std/uuid/v1` or `std/uuid/v4` instead of `std/uuid/mod`. Ultimately I think the uuid module should not rely on the Deno global though.

**Comment by NathanKleekamp** [comment]
In that case, it seems other modules that rely on `std/testing/asserts.ts`will fail in the browser, or anywhere else that doesn't have access to the Deno global. Best case scenario, test helpers shouldn't be used in user-facing code, probably.
