### ISSUE TITLE
Add bufSize to DatagramConn

### ISSUE THREAD

**Issue by hazae41** [denoland/deno#5765]
Currently, if I want to increase the buffer size, I need to either call receive() with a custom array, or monkey patch the bufSize property 

```typescript
const listener = Deno.listenDatagram({ port, transport: "udp" });
(listener as any)["bufSize"] = 2048;
```

We should be able to modify the default buffer size by doing this

```typescript
const listener = Deno.listenDatagram({ port, transport: "udp", bufSize: 2048 });
```

and/or

```typescript
const listener = Deno.listenDatagram({ port, transport: "udp" });
listener.bufSize = 2048
```

**Comment by alisabzevari** [comment]
This is an unstable API. If there is no revolutionary changes planned, I can give it a try.
