### ISSUE TITLE
Architecture diagram is out-of-date

### ISSUE THREAD

**Issue by gewoonwoutje** [denoland/deno#5768]
The diagram shows libdeno (C++). I could be wrong, but isn't this replaced with rusty_v8?

https://deno.land/manual/contributing/architecture#schematic-diagram

**Comment by yoshixmk** [comment]
I wrote a draft to deepen my understanding.  
Is there anything that needs improvement? Is this correct?  
<img width="1123" alt="deno_architecture_draft_image" src="https://user-images.githubusercontent.com/6196702/84225200-7d1ff580-ab19-11ea-8e5c-6e087a04bb0d.png">

**Comment by xgqfrms** [comment]
> still not fix

https://deno.land/manual/contributing/architecture#schematic-diagram

![image](https://user-images.githubusercontent.com/7291672/166467194-76964441-d749-43e4-9544-daa6f94c542c.png)
