### ISSUE TITLE
Can't import React from different url

### ISSUE THREAD

**Issue by rouche-q** [denoland/deno#5772]
I tried to import React from jspm and pika.dev but i still can't import the package. 
It worked two day ago but not anymore. 
I tried in version 1.0.1 and 1.0.2 on Achlinux

### Error
`$ deno run index.ts`
`error: TS2307 [ERROR]: Cannot find module 'https://dev.jspm.io/react' or its corresponding type declarations.`
`import React from "https://dev.jspm.io/react"`

### Info
`$ deno --version`
`deno 1.0.2`
`v8 8.4.300`
`typescript 3.9.2`

How i can resolve that ?

Thank you

**Comment by bartlomieju** [comment]
It's a bug that will be fixed in #5785
