### ISSUE TITLE
completions help text for bash won't work on ubuntu

### ISSUE THREAD

**Issue by opensas** [denoland/deno#5777]
The `deno completions` help text gives the following message:

```shell
$ deno completions --help
deno-completions 
Output shell completion script to standard output.
  deno completions bash > /usr/local/etc/bash_completion.d/deno.bash
  source /usr/local/etc/bash_completion.d/deno.bash

USAGE:
    deno completions [OPTIONS] <shell>
```

But in ubuntu it won't work

```
$ deno completions bash > /usr/local/etc/bash_completion.d/deno.bash
bash: /usr/local/etc/bash_completion.d/deno.bash: No such file or directory
```

What did work for me was:

```
$ deno completions bash | sudo tee /etc/bash_completion.d/deno.bash > /dev/null
$ . /etc/bash_completion
```

**Comment by ry** [comment]
Thanks for the report. Feel free to update the example in the help text.

**Comment by opensas** [comment]
Thanks for the reply, I'm not sure how it's done on other distros (I'll see if I can try with one of them), perhaps the best would be to state in the short cli message that the solution provided is just an example and that you should check how it's done on your own distro, even better point to some kind of wiki or documentation telling how to achieve that in each distro
Do we have some wiki or some place in the docs where we could put that info?
I guess the best place would be here: https://deno.land/manual/getting_started/setup_your_environment#shell-autocomplete

**Comment by David-Else** [comment]
I can confirm that the example in `--help` and the manual does NOT work on Centos/RHEL (and therefore I am 99% sure Fedora too). What DOES work is:

```shell
deno completions bash | sudo tee /etc/bash_completion.d/deno.bash > /dev/null
source /etc/bash_completion.d/deno.bash
```
@opensas does `source /etc/bash_completion.d/deno.bash` work OK on your computer? If it does then I think we can call the above confirmed working on Ubuntu and Redhat.

Which distro does the original `--help` version work for? Maybe the above should be the official way of doing it, Ubuntu is the most popular distro.

I can make a pull request on this, but do we want to replace the recommended way or have two ways of doing it? The above is for Ubuntu and Redhat, but which distro is the original one intended for?

**Comment by opensas** [comment]
I think the help message could tell you how to achieve it on debian based distros, and tell you to check how to do it on your own distro. Moreover on the wiki we could add instructions for debia + fedora + arch based distros, which I guess will cover more than 95% of cases.

**Comment by JerryGreen** [comment]
Think of me as a complete mad man trying to do some development on Windows, but I made it work by doing so:

```bash
mkdir ~/.completions
deno completions bash >~/.completions/deno.bash
echo "[[ -d ~/.completions && -n $(ls -A ~/.completions) ]] && . ~/.completions/*" >>~/.bashrc
```

I also encountered problems, like no access to `/usr/share/bash-completion/**` or `/usr/local/etc/bash_completion.d/**` (as suggested by `deno completions --help`), because it's probably emulated, or requires admin rights, or whatever... Anyway, it works now!

GNU bash, version 4.4.23(1)-release (x86_64-pc-msys)

**Comment by GJZwiers** [comment]
Just want to add that on Ubuntu the bash completions can also be added to `/usr/share/bash-completion/completions` which is sourced by `~/.bashrc` by default.
