### ISSUE TITLE
`deno bundle` produce typescript file

### ISSUE THREAD

**Issue by davidcallanan** [denoland/deno#5781]
Are there plans to support typescript output for the `deno bundle` command?

Are there plans to emit typescript declaration files when creating an esm bundle with `deno bundle`?

I think these are important features.

**Comment by bartlomieju** [comment]
Ref #3385

As for outputting TypeScript - I'm not sure - @kitsonk WDYT?

**Comment by davidcallanan** [comment]
@bartlomieju  I thought the idea was that TypeScript was to be the "source of truth" and so if modules are being bundled it only makes sense to me that TypeScript output would be an option (if not a default).

Another thing that might have come up already is outputting source maps.

**Comment by kitsonk** [comment]
I don't think anyone said TypeScript is the source of truth. It is a first class language. Outputting to a TypeScript bundle is inefficient, as it would require reparsing again. Outputting the `.d.ts` file is just as truthful as outputting TypeScript and more efficient and subsequent consumption.

Source maps is #4499.

**Comment by pedropaulosuzuki** [comment]
Outputting typescript in bundler is great for modules. I think that option would be good as well.

**Comment by kitsonk** [comment]
I think the only action we would take on this is #3385.  So thanks for the suggestion, but politely declined.
