### ISSUE TITLE
Doc: Cached files aren't in DENO_DIR

### ISSUE THREAD

**Issue by LarryBattle** [denoland/deno#5782]
## Deno Version
1.0.2

## OS
Linux (Ubuntu 18+)

## Problem
I installed Deno today to play around with it and after running some example code, Deno told me it compiled my typescript file but didn't state where it stored it.

```s
$ deno run --reload example.ts 
Compile file:///home/me/deno_test/example.ts
hello world
```

The documentation says the default deno directory is at `$HOME/.deno` but only the deno binary was there.

```s
$ find $HOME/.deno -type f
/home/me/.deno/bin/deno
```

```markdown
`DENO_DIR` defaults to `$HOME/.deno` but can be set to any path to control where
generated and cached source code is written and read to.
```
* [setup_your_environment.md](https://github.com/denoland/deno/blame/36fde75d779078118af3b2b6c078bcbfb47b1a0f/docs/getting_started/setup_your_environment.md#L11) 

The code actually says it uses the OS cache directory. 

```rust
// We use the OS cache dir because all files deno writes are cache files
// Once that changes we need to start using different roots if DENO_DIR
// is not set, and keep a single one if it is.
let default = dirs::cache_dir()
```
* [deno_dir.rs](https://github.com/denoland/deno/blame/89fe81168e75a375a67e9d391b367d2a9749153c/cli/deno_dir.rs#L23)

After more digging I finally discovered the `deno info` command to reveal the true location of the cached content.

## Expected

```s
$ deno info
DENO_DIR location: "/home/me/.deno"
Remote modules cache: "/home/me/.deno/deps"
TypeScript compiler cache: "/home/me/.deno/gen"
```

## Actual

```s
$ deno info
DENO_DIR location: "/home/me/.cache/deno"
Remote modules cache: "/home/me/.cache/deno/deps"
TypeScript compiler cache: "/home/me/.cache/deno/gen"
```

## Possible Solutions:

To save Deno newbies time in finding the location for the cached content, could the  [setup_your_environment.md](https://github.com/denoland/deno/blame/36fde75d779078118af3b2b6c078bcbfb47b1a0f/docs/getting_started/setup_your_environment.md#L11) documentation be updated to mention that the `deno info` command will reveal the true location of your cached files?

<strike>Or maybe include a verbose option in the `deno run` command that prints out the location of the cached files.</strike> `verbose` logging reveals the location `deno run --log-level debug --reload example.ts`

**Comment by lucacasonato** [comment]
As you mentioned the information in the documentation is out of date. DENO_DIR defaults to the cache directory, not `~/.deno`.

**Comment by ry** [comment]
Doc improvements are very welcome!

**Comment by bartlomieju** [comment]
Docs updated in https://github.com/denoland/deno/pull/5835
