### ISSUE TITLE
HTTP Method constants for std/http ?

### ISSUE THREAD

**Issue by KwanJunWen** [denoland/deno#5790]
I've looked through the issues and can't seem to find one related to this. Do you think it is a good idea to include http method constants similar to [go's method constants](https://golang.org/pkg/net/http/#pkg-constants) ?

Can't seem to find relevant constants over here https://deno.land/x/std/http.

Thank you.

**Comment by ry** [comment]
If that's helpful for you, I think that's fine... Tho our server code should be changed to use those constants.

**Comment by alisabzevari** [comment]
Using an enum, we can make methods more strong without changing the server code:

```ts
export enum HttpMethods {
  GET = "GET",
  POST = "POST",
  PUT = "PUT",
  DELETE = "DELETE",
  OPTIONS = "OPTIONS",
  TRACE = "TRACE",
  PATCH = "PATCH",
  PURGE = "PURGE",
  HEAD = "HEAD"
}

export type HttpMethod = HttpMethods | string;
```
I can add this if it makes sense.

**Comment by KwanJunWen** [comment]
Thanks for the fast reply ! I am thinking if the `HttpMethods` enum should be called as `Method` instead following `http_status.ts` convention. Also maybe can update `mod.ts` to export `Method` enum as well so that we could do something like that :

```ts
import { serve, Method } from "https://deno.land/std/http/mod.ts";
const s = serve({ port: 8000 });
console.log("http://localhost:8000/");
for await (const req of s) {
  switch (req.method) {
    case Method.GET:
      // Handle GET request
    case Method.POST:
      // Handle POST request
    default:
      // ...
      break;
  }
  req.respond({ body: "Hello World\n" });
}
```

**Comment by WA9ACE** [comment]
I'm taking a stab at this atm, and should have a PR out in a few hours that we can discuss.
