### ISSUE TITLE
Not properly generating JSDoc documentation.

### ISSUE THREAD

**Issue by mattd3v** [denoland/deno#5798]
A few things seem off about the documentation generator.

This example code was run with Deno v1.0.2 on MacOS Catalina:
```ts
/**
 * Boolean helper functions.
 */

/** Returns a boolean representing if its argument was true. */
export function isTrue (bool: boolean): boolean {
  return bool || false;
}

/** Returns a boolean representing if its argument was false. */
export function isFalse (bool: boolean): boolean {
  return !isTrue(bool);
}
```

```
function isFalse(bool: boolean): boolean
  Returns a boolean representing if its argument was false.

function isTrue(bool: boolean): boolean
  Boolean helper functions.
```
The documentation text for the `isTrue` function actually contains the file header comment.

Also, when using `export { isTrue, isFalse }` the doc command yields no output, as if the exports weren't even there.

I have spent some time now familiarizing myself with the `cli/doc` source code, and can help out here. However, pointers from @bartlomieju and @lucacasonato would be much appreciated!

**Comment by lucacasonato** [comment]
Would be super awesome if you could get that working, but it's probably going to be somewhat challenging because of variable hoisting. But a first pass with no hoisting support would already be great.

Ref #4516

**Comment by bartlomieju** [comment]
> The documentation text for the isTrue function actually contains the file header comment.

@mattd3v  Definitely a bug - we need to add a test case for this situation.

> Also, when using export { isTrue, isFalse } the doc command yields no output, as if the exports weren't even there.

Correct, this situation is still not handled. 

Here's documentation for AST node for `export { isTrue, isFalse }`:
https://docs.rs/swc_ecma_ast/0.20.0/swc_ecma_ast/struct.NamedExport.html

Named exports should be parsed and then. based on collected specifiers, proper declarations from module body should be extracted.

**Comment by mattd3v** [comment]
I'm getting much more comfortable with the `cli/doc` code, and will implement named exports.

However, I've found a second bug, which occurs when given a comment like the following:

```js
/**
 * Print a custom greeting
 * by providing a name.
 *
 * @param {string} name
 */
export function greet(name) {
  console.log(`Hello, ${name}`);
}
```

Running the `doc` command yields:

```shell
$ deno doc greet.js
function greet(name)
  Print a custom greeting by providing a name.
```

I'm currently improving some of the tests to make them fail where they should.

**Comment by bartlomieju** [comment]
@mattd3v I'm not sure, I think that was added by @lucacasonato to save some space in terminal (to replicate how `go doc` works), but there's already been a report that it's surprising behavior (https://github.com/denoland/deno/issues/4755). I guess we could remove it altogether and always show full contents.

**Comment by mattd3v** [comment]
@bartlomieju can this be closed, or are there any other changes you know need to be made?
