### ISSUE TITLE
TS2322 [ERROR]: Type '"unix"' is not assignable to type '"tcp" | undefined'.

### ISSUE THREAD

**Issue by teleclimber** [denoland/deno#5801]
If I run this simple script:

```
async function run() {
        await Deno.connect({path: "blah", transport:"unix"});
}
run();
```

I get this TS compilation error:

```
error: TS2322 [ERROR]: Type '"unix"' is not assignable to type '"tcp" | undefined'.
 await Deno.connect({path: "blah", transport:"unix"});
```

Yet my code is a copy of the example in docs: https://doc.deno.land/https/github.com/denoland/deno/releases/latest/download/lib.deno.d.ts#Deno.connect

I get a similar result when doing `Deno.listen` with same parameters (although listen docs don't even mention possibility of `unix` transport).

If I add `//@ts-ignore` my code compiles and runs fine.

Thanks.

**Comment by SyrupThinker** [comment]
`Deno.connect` with the `unix` transport is considered unstable, you shouldn't be able to access it without the `--unstable` flag.

**Comment by teleclimber** [comment]
OK, good to know, thanks. Perhaps the docs should indicate this?

**Comment by ry** [comment]
@teleclimber Indeed the docs should indicate this. Thanks for the report - it helps.
