### ISSUE TITLE
[Examples] What is "a+" in the "Inspecting and revoking permissions" example

### ISSUE THREAD

**Issue by bolatovumar** [denoland/deno#5804]
See this line:

https://github.com/denoland/deno/blame/master/docs/examples/permissions.md#L16

What does `a+` mean here? It doesn't fit any of the accepted types.

```js
const log = await Deno.open("request.log", "a+");
```

**Comment by ry** [comment]
It's an error - we've since changed the API - it should be  `{ write: true, append: true }`
