### ISSUE TITLE
Deno.test not working

### ISSUE THREAD

**Issue by platinumindustries** [denoland/deno#5805]
Using the default [sample code linked in the documentation](https://github.com/denoland/deno/tree/master/std/testing):

```
Deno.test({
  name: "testing example",
  fn(): void {
    assertEquals("world", "world"); 
    assertEquals({ hello: "world" }, { hello: "world" });
  },
});
```

The test module seems to not be working correctly. Compiling and running the above code shows nothing in the console.

It doesn't tell if the tests passed or failed.

**Comment by alisabzevari** [comment]
You are probably running the script with `deno run`. Tests should be executed with `deno test`:
```
deno test your-test-file.ts
```
Run `deno test -h` for more info.

**Comment by platinumindustries** [comment]
You are right, `deno test` works. 
I used to use `deno run` before **v1**. I guess thats what confused me. :)

**Comment by platinumindustries** [comment]
@alisabzevari 
is there any way to save the results on a variable and serve them to a https server?
