### ISSUE TITLE
Cache does not have TS extension goofying up syntax highlighting.

### ISSUE THREAD

**Issue by ThePrimeagen** [denoland/deno#5806]
I am using Vim with CoC and when I jump to import definition (`<Plug>(coc-definition)`)

```
import {
    serve,
} from "https://deno.land/std/http/server.ts";
```
This will jump to `/home/prime/.cache/deno/deps/https/deno.land/c1723c570639ab9ac7b57b4c6169663cda9d5f85151d647088ae17884514b868` which, since it doesn't have TS file extension makes code inspection meh.

**Comment by bartlomieju** [comment]
Ref #4996 

I agree that DX is poor, however there is no easy solution to this problem, eg. `https://cdn.pika.dev/@pika/react-dom@v16.13.1` is a URL that has no extension. It could be JavaScript or TypeScript file (if proper content type header is set) - meaning that we'd have to add the extension ourselves.

**Comment by davidmathers** [comment]
IMO the easy solution is to just append to the cached file the extension that the source provides. If the source doesn't provide then the cached filed doesn't get an extension. It shouldn't be your responsibility to do anything beyond that.

**Comment by lucacasonato** [comment]
I'm going to close this as it is not anymore relevant with the LSP. Cache internals should be opaque to the user.
