### ISSUE TITLE
Function to delete an environment variable?

### ISSUE THREAD

**Issue by TooTallNate** [denoland/deno#5812]
Seems like there's no `Deno.env.delete('VAR')` or equivalent.

**Comment by ry** [comment]
This is a relatively easy feature, and it might be good for someone who is interested in exploring how deno creates bindings. Marking it as good-first-issue.


1. The corresponding Rust API is `std::env::remove_var()`. Follow the example of `op_set_env` to create a new Op https://github.com/denoland/deno/blob/526c9196e23af34d1ecd424d09c99c7003c33844/cli/ops/os.rs#L100-L109 
2. Create a corresponding JS wrapper around that op:
https://github.com/denoland/deno/blob/v1.0.2/cli/js/ops/os.ts#L22-L24
3. Add type declaration and documentation here https://github.com/denoland/deno/blob/v1.0.2/cli/js/lib.deno.ns.d.ts#L112
4. Add tests to cli/tests/unit/os_test.ts

**Comment by humancalico** [comment]
I'll take this one

**Comment by tumile** [comment]
Hi, I'm new to Deno and really want to contribute. Can I work on this one @humancalico ?

**Comment by humancalico** [comment]
@tumile I already had a working branch but if you really want to do it go ahead. If you have any queries feel free to ask.

**Comment by tumile** [comment]
> @tumile I already had a working branch but if you really want to do it go ahead. If you have any queries feel free to ask.

Thank you @humancalico, I just submitted a pull request. This is my first so inputs are very welcome.

**Comment by erfanium** [comment]
Should this issue to be closed?

**Comment by ry** [comment]
Fixed in #5859
