### ISSUE TITLE
snapshots shouldn't need to be rebuilt every time cli is recompiled

### ISSUE THREAD

**Issue by afinch7** [denoland/deno#5820]
Currently any changes to cli rust code cause snapshots to be rebuilt and this takes several seconds. If i'm only changing some code for a op I shouldn't need to rebuild the snapshots. 

In general `cli/build.rs` and `cli/js` are the only things in the `cli` folder that should cause snapshots to be rebuilt. We could save a lot of time if the snapshot generation in `cli/build.rs` was smarter and was skipped unless these files where changed.

We already have a list of files to check in the form of `cargo:rerun-if-changed=` outputs from `deno_typescript` and `cli/build.rs` is a single file to check that never changes. I figure this wouldn't really be too hard to implement.

tags: cli, build

**Comment by bartlomieju** [comment]
I think this issue no longer happens after #6813
