### ISSUE TITLE
--allow-read whitelist does not work with tilde 

### ISSUE THREAD

**Issue by cknight** [denoland/deno#5825]
Reproduction:
```
deno run --allow-read=~ https://deno.land/std/examples/cat.ts ~/.bashrc
```
Output:
```
error: Uncaught PermissionDenied: read access to "/home/chris/.bashrc", run again with the --allow-read flag
    at unwrapResponse ($deno$/ops/dispatch_json.ts:43:11)
    at Object.sendAsync ($deno$/ops/dispatch_json.ts:98:10)
    at async Object.open ($deno$/files.ts:37:15)
    at async https://deno.land/std/examples/cat.ts:4:16
```
Specifying an absolute path in `--allow-read` correctly outputs the file content.

This is on:
```
deno --version
deno 1.0.2
v8 8.4.300
typescript 3.9.2
```

**Comment by ry** [comment]
The tilde is expanded by the shell before it gets to the program. I'm not sure how exactly this works but I'm guessing that the equals sign is preventing this from happening.

**Comment by tumile** [comment]
```
pub fn main() {
  ...
  let flags = flags::flags_from_vec(args);
```
If you print `flags` you will see that `read_whitelist` is something like this `["/home/.../~"]`. The tilde is not expanded but appended to the current working directory. It is because of the way the flags are resolved:
```
// cli/flags.rs

fn permission_args_parse(flags: &mut Flags, matches: &clap::ArgMatches) {
  if let Some(read_wl) = matches.values_of("allow-read") {
    ...
    flags.read_whitelist = resolve_fs_whitelist(&raw_read_whitelist);
    ...
}

fn resolve_fs_whitelist(whitelist: &[PathBuf]) -> Vec<PathBuf> {
  whitelist
    .iter()
    .map(|raw_path| resolve_from_cwd(Path::new(&raw_path)).unwrap())
    .collect();
}
```
`resolve_from_cwd` checks for absolute path, otherwise join with current directory.

**Comment by armujahid** [comment]
I think we can utilize [shellexpand](https://crates.io/crates/shellexpand) crate here. What do you think?

**Comment by bartlomieju** [comment]
#5883 is a PR with solution to this problem, but as we don't want to expand special characters and leave it to user's shell I'm going to close this issue as well.
