### ISSUE TITLE
Add Windows unzip command to release notes

### ISSUE THREAD

**Issue by MarkTiedemann** [denoland/deno#584]
[https://github.com/denoland/deno/releases/tag/v0.1.0](https://github.com/denoland/deno/releases/tag/v0.1.0)

> These compressed files contain the deno executable. Here's an example of how you might extract it:
> 
> ```
> gunzip -c deno_mac_x64.gz > deno
> chmod u+x deno
> ./deno myscript.ts
> ```

Might be nice to add a Windows equivalent, too.

For example, using the `Expand-Archive` cmdlet which is available on Windows since PowerShell 5 in 2016:

```cmd
powershell expand-archive deno_win_x64.zip -destinationpath .
deno myscript.ts
```

Before that, you could unzip using a .NET 4.5 assembly which is available since 2012:

```cmd
powershell add-type -a System.IO.Compression.FileSystem; [IO.Compression.ZipFile]::ExtractToDirectory('deno_win_x64.zip', '.')
deno myscript.ts
```

Before that, I don't think there was a built-in command to unzip.

**Comment by ry** [comment]
We will be adding a much easier way to download and extract these releases soon (like rust does). Since Deno is quite "alpha", we expect users to have higher levels of computer competence now. I think people who want to run it will manage. Thanks trying it out tho - please report any bugs.
