### ISSUE TITLE
'npm audit' alternative

### ISSUE THREAD

**Issue by maximousblk** [denoland/deno#5840]
I don't know enough about how npm listed vulnerabilities about dependencies, but I was wondering if there is a solution or a plan for such a solution. This would be required when deno gets a bit more mainstream and new vulnerabilities are discovered. Then there has to be a system to notify the users of such issues for them to take action.

Just a thought.

**Comment by nayeemrmn** [comment]
As I commented there, we should consider documenting #5161 for this use.

**Comment by ry** [comment]
There isn't a solution nor a plan for it. It's certainly useful functionality. I'll leave this issue marked as feature, tho I'm not sure if this belongs in the CLI itself or should be done by source repositories.

**Comment by maximousblk** [comment]
In order for this to work, there needs to be a way to mark certain versions as deprecated or vulnerable. This is impossible to do by editing the file itself due to the integrity check.

A new standard module can be made for assigning files as insecure.

This would work like this:

In a separate file, an array of insecure versions are listed.

Then in the main module, the "security check function" is imported from the "security" module and passed in the current version of the module. If it matches any of the listed versions, it logs a message about the vulnerability listed in the separate file.

---

This can easily be a community effort but it would be better to have a standard module for that.

One more thing to consider about this solution is that it adds to the "boilerplate noise" which can be a deal breaker for being a standard module.

That's just a quick little workaround but I'm sure there can be better solutions.

**Comment by maximousblk** [comment]
here is an example: [maximousblk/audit](https://github.com/maximousblk/audit)

**Comment by maximousblk** [comment]
Discussion moved to #8699

**Comment by ghost** [comment]
Out of sight, out of mind 🥱

**Comment by bartlomieju** [comment]
`deno audit` is available in latest canary and will be included in the next stable release.

**Comment by ghost** [comment]
Honestly, I did not see this one coming - thanks, that's wonderful news! 🤩
