### ISSUE TITLE
Deno crashes while typing text in inspector console 

### ISSUE THREAD

**Issue by piscisaureus** [denoland/deno#5843]
Only if:
* script execution is not paused
* eager evaluation is on

![image](https://user-images.githubusercontent.com/218257/82821970-51f49f80-9ea5-11ea-85bd-f976b98e4cc0.png)

**Comment by gautam1168** [comment]
I would like to work on this

**Comment by piscisaureus** [comment]
@gautam1168 Did you get any further with this?

**Comment by caspervonb** [comment]
From the client's perspective; the context gets destroyed

> sdk.js:1 Execution context was destroyed.

**Comment by caspervonb** [comment]
Minimal reproduction, this happens on any error.

![Screenshot 2020-10-08 at 6 55 33 PM](https://user-images.githubusercontent.com/157787/95449821-dbf65e00-0997-11eb-8848-bdd7805fd968.png)

**Comment by bartlomieju** [comment]
This has been thorn in my side for the longest time, I'll try to look into it soon

**Comment by bartlomieju** [comment]
I just tried it and everything works fine. I guess this issue is resolved :)
