### ISSUE TITLE
How to execute deno without strict mode ?

### ISSUE THREAD

**Issue by vinodsai-a** [denoland/deno#5845]
Getting error Uncaught SyntaxError: Identifier 'list' has already been declared

Can we execute deno without strict mode?

Searched online but there is no clear documentation.

**Comment by lucacasonato** [comment]
You can not. Deno is always in strict mode.

**Comment by nayeemrmn** [comment]
More specifically, [ES modules are always in strict mode](https://stackoverflow.com/a/31685340) or they wouldn't comply with the spec.
