### ISSUE TITLE
Deno community forum

### ISSUE THREAD

**Issue by devYusuf** [denoland/deno#5846]
Hello guys, let's create an online forum for deno in deno itself.

**Comment by ry** [comment]
You're in it already. There's also our discord https://discord.gg/deno - that's about the extent of forums I'm willing to manage personally - so beyond that it's going to be unofficial.

**Comment by hoibuikms** [comment]
Hi everybody, I get issue after upgrade to deno 1.0.5
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src\command\connect.rs:63:24
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Can anyone help me explain why? 
thanks

**Comment by vicary** [comment]
How about an unofficial open source forum that also act as a live promotion of the usage of deno itself?

**Comment by richidev58** [comment]
> You're in it already. There's also our discord https://discord.gg/deno - that's about the extent of forums I'm willing to manage personally - so beyond that it's going to be unofficial.

upgrade to mongo@v0.8.0 to solve your problem.

**Comment by richidev58** [comment]
> Hi everybody, I get issue after upgrade to deno 1.0.5
> thread '' panicked at 'called `Option::unwrap()` on a `None` value', src\command\connect.rs:63:24
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> Can anyone help me explain why?
> thanks

upgrade to mongo@v0.8.0 to solve your problem.

**Comment by josephat-phat** [comment]
bonjour
je veux limiter le nombre de tentative lors de l'authentification,
quelqu'un peut m'aider
