### ISSUE TITLE
blob.constructor.name should return Blob not DenoBlob

### ISSUE THREAD

**Issue by therealadityashankar** [denoland/deno#5851]
- for browser compatibility and ensuring people don't have to change code to be deno specific

To recreate issue (linux):
type 'deno' in the terminal

type the following commands in the deno repl
`const b = new Blob()`
`b.constructor.name`

you should see the output
`DenoBlob`

this is non standard, as the same command in the browser returns `Blob`,

I found this error when I attempted to run jszip in deno

**Comment by therealadityashankar** [comment]
I attempted to run it by doing something similar to downloading the browser version of jsZip from [here](https://stuk.github.io/jszip/) and adding an `export default JSZip` in the bottom, it showed an error that it did not recognize a blob when attempting to load a zip file

**Comment by pevers** [comment]
I tried to come up with a solution as described in: https://github.com/denoland/deno/pull/4736#discussion_r407615942

Let me know what you think @ry : https://github.com/denoland/deno/pull/5879
