### ISSUE TITLE
Several Documentation links are broken

### ISSUE THREAD

**Issue by MatthewTFarley** [denoland/deno#5855]
The links defined in the following lines of code result in a 404 not found page when browsing the [Deno manual](https://deno.land/manual), due to their location being written relative to the repository file structure and not the docs website URL structure.

Found on https://deno.land/manual/contributing:
- https://github.com/denoland/deno/blame/master/docs/contributing.md#L3

Found in https://deno.land/manual/linking_to_external_code#how-can-i-trust-a-url-that-may-change:
- https://github.com/denoland/deno/blame/master/docs/contributing.md#L19

Found on https://deno.land/manual/linking_to_external_code:
- https://github.com/denoland/deno/blame/master/docs/linking_to_external_code.md#L3

Found in https://deno.land/manual/linking_to_external_code#how-can-i-trust-a-url-that-may-change:
- https://github.com/denoland/deno/blame/master/docs/linking_to_external_code.md#L84

Found on https://deno.land/manual/testing#resource-and-async-op-sanitizers:
- https://github.com/denoland/deno/blame/master/docs/testing.md#L55

Found on https://deno.land/manual/tools:
- https://github.com/denoland/deno/blame/master/docs/tools.md#L9-L14

Found on https://deno.land/manual/contributing/architecture#deno-and-linux-analogy:
- https://github.com/denoland/deno/blame/master/docs/contributing/architecture.md#L9
- https://github.com/denoland/deno/blame/master/docs/contributing/architecture.md#L12

Found on https://deno.land/manual/examples/os_signals:
- https://github.com/denoland/deno/blame/master/docs/examples/os_signals.md#L4

Found on https://deno.land/manual/getting_started/permissions:
- https://github.com/denoland/deno/blame/master/docs/examples/permissions.md#L4

Found on https://deno.land/manual/runtime/compiler_apis:
- https://github.com/denoland/deno/blame/master/docs/runtime/compiler_apis.md#L4

Found on https://deno.land/manual/runtime/workers#using-deno-in-worker:
- https://github.com/denoland/deno/blame/master/docs/runtime/workers.md#L67

Broken image links found on https://deno.land/manual/tools/debugger#chrome-devtools:
- https://github.com/denoland/deno/blame/master/docs/tools/debugger.md#L33
- https://github.com/denoland/deno/blame/master/docs/tools/debugger.md#L37
- https://github.com/denoland/deno/blame/master/docs/tools/debugger.md#L48
- https://github.com/denoland/deno/blame/master/docs/tools/debugger.md#L57
- https://github.com/denoland/deno/blame/master/docs/tools/debugger.md#L74

Broken images links found on https://deno.land/manual/tools/debugger#vscode:
- https://github.com/denoland/deno/blame/master/docs/tools/debugger.md#L121
- https://github.com/denoland/deno/blame/master/docs/tools/debugger.md#L123

**Comment by lucacasonato** [comment]
Duplicate of #5827

**Comment by MatthewTFarley** [comment]
Understood! Sorry for the duplication!

**Comment by lucacasonato** [comment]
Thanks a lot for the effort anyway :-)
