### ISSUE TITLE
Bigger refactors

### ISSUE THREAD

**Issue by ry** [denoland/deno#5858]
- [x] Further integration with module graph. A series of refactors to module loading that @bartlomieju is doing including #5029, #5817, #5785
  - #6080
  - #6082
- [x] set_slot / get_slot (use APIs added in https://github.com/denoland/rusty_v8/pull/360) https://github.com/denoland/deno/pull/5929
- [ ] op crates #6906 
- [x] rusty_v8 scopes refactor @piscisaureus https://github.com/denoland/rusty_v8/pull/401 https://github.com/denoland/rusty_v8/pull/385 https://github.com/denoland/rusty_v8/pull/380 https://github.com/denoland/rusty_v8/pull/386 https://github.com/denoland/rusty_v8/pull/406
- [x] port tools/http_server.py to rust https://github.com/denoland/deno/issues/1453 https://github.com/denoland/deno/pull/6364 
- [x] convert all code in cli/js to javascript.   [design doc](https://docs.google.com/document/d/1_WvwHl7BXUPmoiSeD8G83JmS8ypsTPqed4Btkqkn_-4/edit?usp=sharing). needs first to do experiments with snapshots and es modules in rusty_v8 https://github.com/denoland/rusty_v8/pull/396 https://github.com/denoland/deno/pull/6111 https://github.com/denoland/deno/pull/6793

**Comment by nnajiabraham** [comment]
Hi Ryan, would love to contribute to Deno and looking at converting cli/js to JavaScript...
Will love a better explanation on what the expectation is here and how I can go about that? @ry

**Comment by nayeemrmn** [comment]
@nnajiabraham Follow discussion and links here: #4750.

**Comment by ry** [comment]
@nnajiabraham Thanks for the offer of help - any help is much appriciated. This issue is for really involved long term projects. Have a look instead at the issues marked [good-first-issue](https://github.com/denoland/deno/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22)

**Comment by nnajiabraham** [comment]
Sure thing @ry will take a look at those

**Comment by yordis** [comment]
I hope you find a way to keep TypeScript.

It is really welcoming experience to open any file and figure out what the objects are without having to debug and relying on a strong understanding of all these objects in order to contribute (maybe add JSDoc everywhere?).

It is always a given and takes with typed languages but even languages like Erlang/Elixir require you to add types everywhere if you truly would like a broader range of people to contribute. Otherwise, only a few people will be able to; the rest will open issues and rely on those few people because we lack the understanding, and tools to even feel "confident" that we can give it a try (speaking from inside out).

😞

**Comment by CyriacBr** [comment]
I'm more worried about the message Deno is giving to the JS/TS community by removing TS from its internal. 
Imagine building a runtime with TS first class support being one of the main selling point, then NOT actually using it itself in its internals. Kind of a _do as i say not as i do_ story.

I hope @ry you realize how much influence you have on the JS community. The usage of TS internally should probably be reconsidered, or either properly addressed in a demystified official blog post of some sort.
Pretty sure people that supported Deno from the get go just for its TS features and for, indirectly pushing for TS usage more widely, are hella confused right now.

**Comment by Soremwar** [comment]
@CyriacBr 
> Imagine building a runtime with TS first class support being one of the main selling point, then NOT actually using it in its internals.

Well, most of the runtime isn't written in TypeScript either but that doesn't make it less useful for TS developers.

Typescript is a really nice tool for understanding what JavaScript is really doing behind curtains, but that convenience comes at a cost, and as discussed in the document, perhaps the advantages it might bring aren't worth the price in this case, and that's perfectly ok. And in your case and everyone else's that same question must be done at the moment of choosing the tool for building your application, __everything comes at a cost__.

_I don't think replacing TypeScript in the internals will discourage the people of using it in the first place_, and having a separate file with types as siggested in the document should keep dev experience on a similar level.

Not all tools are fit for all jobs, and building a runtime/compiler has more considerations than most applications, but don't let that stop you from using the great tool TypeScript is, specially after all the hard work that has been put into making Deno the great runtime it is now.

**Comment by ry** [comment]
@yordis @CyriacBr @Soremwar I saw that this design doc was being discussed more widely. Most people don't have the context to understand this narrow technical document - it is only applicable to a very particular, very technical situation in the internals of Deno. This is not at all a reflection on the usefulness of TypeScript in general. It's not a discussion about any publicly visible interface  in Deno. Deno, of course, will support TypeScript forever. A website or server written in TypeScript is a very very different type of program than Deno - maybe much more so than novice programmers can appreciate - very little of Deno is written in TypeScript. The target audience is the 5 to 10 people who work on this particular internal system. Please don't draw any broader conclusions.

**Comment by teleclimber** [comment]
> op crates @ry

Hey @ry, am I correct in assuming that refactor is to separate the Deno.* userland API handling from the cli project? If so 👍. I was just noticing that the CLI project includes all the rust and TS code that provides that API, which makes it harder to make a Deno-compatible runtime separate from CLI.

Thanks.

**Comment by getspooky** [comment]
hey @ry 
I am working on the `url` module implementation, this module require a constants for example in order to `Find first and last non-whitespace characters for trimming`. A lot of constants that i need actually exists on `std/path`, I suggest to add `_shared` folder to glob all shared files across the deno `std`.
Thanks.

**Comment by tooolbox** [comment]
> Deno, of course, will support TypeScript forever. A website or server written in TypeScript is a very very different type of program than Deno - maybe much more so than novice programmers can appreciate - very little of Deno is written in TypeScript.

This makes sense and I respect your judgement on this @ry 

I noticed this in the design doc:
> i considered stripping the types at build-time and using a unit test for the type check. unfortunately we don't have a good way to strip the types without spinning up TSC
also it doesn't solve the problem that TypeScript is getting in the way of producing the bundle we need, which is the main thing

I see [swc](https://github.com/swc-project/swc) is mentioned; wanted to comment that [esbuild](https://github.com/evanw/esbuild) strips types and bundles, if that's of any interest.

Either way, good luck and thank you to the Deno team!

**Comment by fwh1990** [comment]
]ۣۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖۖ

**Comment by ry** [comment]
Closing this issue because it's mostly complete.

op crates is still WIP - but I think it's time for a new roadmap.
