### ISSUE TITLE
Is a directory (os error 21)

### ISSUE THREAD

**Issue by aykhanhuseyn** [denoland/deno#5860]
There is OS error when I'm using OAK.
------------------------------------------

$ deno run --allow-net ./index.ts
Download https://deno.land/x/oak/mod.ts
error: Is a directory (os error 21)
------------------------------------------
$ deno --version
deno 1.0.2
v8 8.4.300
typescript 3.9.2
------------------------------------------
macOS Catalina 10.15.4 
------------------------------------------

**Comment by bartlomieju** [comment]
@aykhanhuseyn it seems to be a problem with oak not Deno; try opening issue in https://github.com/oakserver/oak

**Comment by anjanesh** [comment]
What exactly is causing this ? I'm getting the same thing with an npm published module.
```
import tfjs from "npm:tensorflow";
import toxicity from "npm:tensorflow-models/toxicity";
toxicity.load(threshold).then((model: any) =>
{
});
```

deno 1.29.2

```
error: Unable to load /Users/username/Library/Caches/deno/npm/registry.npmjs.org/tensorflow-models/0.0.1/toxicity imported from file:///Users/username/test/toxicity.ts

Caused by:
    Is a directory (os error 21)
```
