### ISSUE TITLE
Can't respond to an http client without consuming the body

### ISSUE THREAD

**Issue by toddself** [denoland/deno#5864]
I'm trying to respond to an http request in certain circumstances without consuming the request's body (like in the case where a POST request exceeds the maximum size allowed).  If I call `ServerRequest#respond` without reading `ServerRequest#body`, I leak handles and the tests fail.

I can do

```
res.status = 413
res.body = new TextEncoder().encode(STATUS_TEXT.get(413))
await writeResponse(req.w, res)
req.conn.close()
```

But it feels odd (also importing from `_io.ts` feels like something I shouldn't be doing?) -- is there a way I'm missing that allows for this?

**Comment by toddself** [comment]
Although, this pattern is odd -- _sometimes_ it closes the connection to the client before it finishes sending the response:

```
Http: error sending request for url (http://localhost:3000/): error writing a body to connection: Broken pipe (os error 32)
    at unwrapResponse ($deno$/ops/dispatch_json.ts:43:11)
    at Object.sendAsync ($deno$/ops/dispatch_json.ts:98:10)
    at async fetch ($deno$/web/fetch.ts:591:27)
```

**Comment by bartlomieju** [comment]
I think @marcosc90 figured this out lately

**Comment by marcosc90** [comment]
Can you show your full test @toddself? Because I can't reproduce the error, I'm not reading the server request body.

**Comment by toddself** [comment]
Ah yeah, sorry!

This is the test that is flaky:
https://github.com/toddself/take-five/blob/master/take-five_test.ts#L338-L368

I added a catch for when the server closes the connection prior to sending the reply.  That is handled by:

https://github.com/toddself/take-five/blob/master/take-five.ts#L297-L306

Thanks!

**Comment by marcosc90** [comment]
@toddself It seems you have a bug somewhere in your code since I can't reproduce that error in my server responding without reading the body, and if you modify your `_onRequest` to:

```
  async _onRequest (req: ServerRequest) {
    // I'm not reading the body.
    return req.respond({ status: 413, body: new TextEncoder().encode(STATUS_TEXT.get(413)) })
  }
```

The test you mention passes without any resource leak.

**Comment by toddself** [comment]
Oh!  Thank you! I will hunt down this leak then.
