### ISSUE TITLE
Parsing error on master with properties named delete

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#5867]
I did a build from master and the following now errors (which it didn't previously):

```ts
const foo = { delete<S>() {} };
```

I get:

```shell
$ deno run bad_parse.ts
error: TS1005 at file:///bad_parse.ts:1:20,Expected Comma, got Some(JSXTagStart) at file:///bad_parse.ts:1:20
```

Basically anything that contains a /method of `delete` and has some sort of generic blows up.  Likely related to `delete` being a reserved word in certain contexts, but being totally valid here.  TypeScript compiler has no problem with this.

**Comment by bartlomieju** [comment]
My bad, I used naive defaults for lexer which were wrong. PR with a fix #5870
