### ISSUE TITLE
404 when importing type declaration files from pika.dev using Deno 1.0.2

### ISSUE THREAD

**Issue by njbraun** [denoland/deno#5876]
I have the following source code:
```tsx
import * as pkg from 'https://cdn.pika.dev/node-fetch/^2.6.0';
console.log('PACKAGE:', pkg);
```

Running on latest (1.0.2) yields:
```
deno --version
deno 1.0.2
v8 8.4.300
typescript 3.9.2

deno run --reload <above_test>
Download https://cdn.pika.dev/node-fetch/^2.6.0
Download https://cdn.pika.dev/-/node-fetch@v2.6.0-AJHWZQobu33EvFJcmA2J/dist=es2019,mode=types/index.d.ts
Download https://cdn.pika.dev/-/node-fetch@v2.6.0-AJHWZQobu33EvFJcmA2J/dist=es2019/node-fetch.js
Download https://cdn.pika.dev/http/dist=es2019,mode=types/index.d.ts
Download https://cdn.pika.dev/url/dist=es2019,mode=types/index.d.ts
Download https://cdn.pika.dev/-/node-fetch@v2.6.0-AJHWZQobu33EvFJcmA2J/dist=es2019,mode=types/externals.d.ts
Download https://cdn.pika.dev/-/url@v0.11.0-4GEt8r64v6xtacsEmNHX/dist=es2019,mode=types/index.d.ts
Download https://cdn.pika.dev/-/http@v0.0.1-security/dist=es2019,mode=types/index.d.ts
error: Import 'https://cdn.pika.dev/-/url@v0.11.0-4GEt8r64v6xtacsEmNHX/dist=es2019,mode=types/index.d.ts' failed: 404 Not Found
```

FYI, the `http` and `url` packages do not exist on pika.dev.  It seems like the request tries to get type definitions for all sub-dependencies, but fails if they do not exist.

Possibly related to: #5029 #5726 

@bartlomieju 

Also possibly relating to: https://github.com/pikapkg/cdn/issues/3 and https://github.com/pikapkg/cdn/issues/8

**Comment by jamesseanwright** [comment]
Seeing the same thing in Deno 1.0.3:

`error: Import 'https://cdn.pika.dev/-/@sinonjs/fake-timers@v6.0.1-JhTh9R3cBdH83IL6Lnpd/dist=es2019,mode=types/index.d.ts' failed: 404 Not Found`

**Comment by jamesseanwright** [comment]
@njbraun You could potentially migrate to jspm, which works for me:

```
import * as pkg from 'https://dev.jspm.io/node-fetch/^2.6.0';
```

**Comment by bartlomieju** [comment]
I just triaged this issue - I can repeat the problem. Going to problematic url in the browser yield an HTTP 500 error:
```
https://cdn.pika.dev/-/http@v0.0.1-security/dist=es2019,mode=types/index.d.ts
Build Error: This package could not be built.
```

CC @FredKSchott can you check if that's a problem on your side?

**Comment by bartlomieju** [comment]
> Seeing the same thing in Deno 1.0.3:
> 
> `error: Import 'https://cdn.pika.dev/-/@sinonjs/fake-timers@v6.0.1-JhTh9R3cBdH83IL6Lnpd/dist=es2019,mode=types/index.d.ts' failed: 404 Not Found`

@jamesseanwright what was your entry point for this case? I get HTTP 404 in the browser for this type declaration as well - this might be a bug in parsing after all...

**Comment by jamesseanwright** [comment]
I'm now using `import sinon from "https://dev.jspm.io/sinon@7.5.0";` (Sinon is the overall dependency that then depends upon`fake-timers`).

**Comment by njbraun** [comment]
> import * as pkg from 'https://dev.jspm.io/node-fetch/^2.6.0';

While that does work:

```
➜  deno-test deno run --allow-net --reload fetch-test.ts
Download https://dev.jspm.io/node-fetch
Download https://dev.jspm.io/npm:node-fetch@2.6.0/browser.dew.js
Compile file:///mnt/c/Users/njbra/Projects/deno-test/fetch-test.ts
PACKAGE: [AsyncFunction: fetch]
```

There's no fetch any of the type definitions like what was happening w/ Pika. (Request Header: X-TypeScript-Types).  A reasonable stop gap until Deno can provide better error handling when a dependency graph results in 404/500 dead ends.

**Comment by jamesseanwright** [comment]
@njbraun There's a potential fix for that:

```ts
// deps.ts

import * as jsNodeFetch from 'https://dev.jspm.io/node-fetch/^2.6.0';
import Fetch from 'https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/aaf0e9573304fcaa1daef91484c2fc5cebdbbcd0/types/node-fetch/index.d.ts'

// the binding to use throughout your code
export const nodeFetch: Fetch = jsNodeFetch;
```

Specifically to your example, is there a reason you're pulling in `node-fetch`? Appreciate it might just be an example, but note that Deno provides `fetch` via the global `window` object.

**Comment by bartlomieju** [comment]
> I'm now using `import sinon from "https://dev.jspm.io/sinon@7.5.0";` (Sinon is the overall dependency that then depends upon`fake-timers`).

@jamesseanwright I just tried running this example on latest master and it compiles without a problem - I think the problem was fixed #6000, but I'm gonna keep this issue open until 1.0.4 is released.

**Comment by jamesseanwright** [comment]
I'll give it a whirl at some point in the next few days. Thanks for the update @bartlomieju! :)

**Comment by SquareMesh** [comment]
Not sure if I'm encountering same issue with the following import.

import {Button} from 'https://cdn.pika.dev/@material-ui/core@^4.10.1';

A slew of items are downloaded but fails with the following..

error: Import 'https://cdn.pika.dev/dist=es2019,mode=types/index.d.ts' failed: 404 Not Found

Tried on Deno 1.0.5, 1.0.4, 1.0.3.

**Comment by bartlomieju** [comment]
@SquareMesh I just run your example and found the problematic type declaration. Downloading https://cdn.pika.dev/-/@material-ui/core@v4.10.1-fc2SiMnxs3PyrtZEG3jY/dist=es2019,mode=types/Card/Card.d.ts yields:
```ts
import * as React from '/-/react@v16.13.1-ByypZEPVPs6cpkpGdpQK/dist=es2019,mode=types/index.d.ts';
import { StandardProps } from '/../dist=es2019,mode=types/index.d.ts';
import { PaperProps } from '../Paper.d.ts';

export interface CardProps extends StandardProps<PaperProps, CardClassKey> {
  /**
   * If `true`, the card will use raised styling.
   */
  raised?: boolean;
}

export type CardClassKey = 'root';

/**
 *
 * Demos:
 *
 * - [Cards](https://material-ui.com/components/cards/)
 *
 * API:
 *
 * - [Card API](https://material-ui.com/api/card/)
 * - inherits [Paper API](https://material-ui.com/api/paper/)
 */
export default function Card(props: CardProps): JSX.Element;
```

Notice the second import: `/../dist=es2019,mode=types/index.d.ts` <--- effectively it always resolves to `https://cdn.pika.dev/dist=es2019,mode=types/index.d.ts`. 

I think that might be problem originating in Pika, @FredKSchott can you confirm that it's expected import specifier?

**Comment by FredKSchott** [comment]
Yup, we just fixed that bug this weekend. I updated to Deno v1.1.0 and all type imports now resolve successfully.

Note that it looks like you need to have the "dom" lib added in your tsconfig from material-ui to compile properly.

**Comment by bartlomieju** [comment]
Thanks @FredKSchott! Closing as resolved.

**Comment by Bidek56** [comment]
I am seeing a slightly different material-ui with deno 1.1.1 error:
`error: 'implements', 'interface', 'let', 'package', 'private', 'protected',  'public', 'static', or 'yield' cannot be used as an identifier in strict mode at https://cdn.pika.dev/-/csstype@v2.6.10-9lGFwmNeuxj9xXremWKA/dist=es2019,mode=exports/index.d.ts:1:7,Expected Comma, got Some(Word(StandardLonghandProperties)) at https://cdn.pika.dev/-/csstype@v2.6.10-9lGFwmNeuxj9xXremWKA/dist=es2019,mode=exports/index.d.ts:1:17`
Is this a deno or a library problem? Thx

**Comment by bartlomieju** [comment]
@Bidek56 that's a different problem, please open a separate issue
