### ISSUE TITLE
Not able to import cjs files anymore

### ISSUE THREAD

**Issue by adrai** [denoland/deno#5878]
Modules like [i18next-fs-backend](https://github.com/i18next/i18next-fs-backend) or [i18next-http-backend](https://github.com/i18next/i18next-http-backend) are written to work for Deno, Node.js and browser environments...

And this works until Deno > v1.0.0...

But now stuff like this is not working anymore: https://github.com/i18next/i18next-fs-backend/issues/5

https://github.com/i18next/i18next-fs-backend/blob/master/lib/readFile.js#L4
`import * as fsMod from './fs.cjs'`

Any advice?

**Comment by bartlomieju** [comment]
Broken in #5029, should be an easy fix

**Comment by armujahid** [comment]
Can I claim this issue? I will ask if I need any help.

**Comment by bartlomieju** [comment]
@armujahid thanks, but this issue is currently blocked by another ongoing refactor in: https://github.com/denoland/deno/pull/5817

**Comment by bartlomieju** [comment]
@kitsonk do you think we could just map `.cjs` extension to `JavaScript` media type?

**Comment by adrai** [comment]
> @kitsonk do you think we could just map `.cjs` extension to `JavaScript` media type?

sounds good

**Comment by kitsonk** [comment]
@bartlomieju it appears in [IANA as](https://github.com/oakserver/media_types/blob/3d6e8bd35f79566d96166b17db2741d06e75154f/db.ts#L984-L987):

```
  "application/node": {
    source: "iana",
    extensions: ["cjs"],
  },
```

So it seems like we could treat it as JavaScript its own thing.  Also feels like we should handle the media type `"application/node"` as well.

[Also this](https://github.com/oakserver/media_types/blob/3d6e8bd35f79566d96166b17db2741d06e75154f/db.ts#L394-L398) where there is `.es` and `.ecma` and `application/ecmascript`:

```
  "application/ecmascript": {
    source: "iana",
    compressible: true,
    extensions: ["ecma", "es"],
  },
```

And `.mjs` which I think we already have:

```
  "application/javascript": {
    source: "iana",
    charset: "UTF-8",
    compressible: true,
    extensions: ["js", "mjs"],
  },
```
