### ISSUE TITLE
Redirected to CLI_SNAPSHOT.js when debugging

### ISSUE THREAD

**Issue by wsporto** [denoland/deno#5889]
When I try to debug a simple script I get redirected to CLI_SNAPSHOT.js. 

![image](https://user-images.githubusercontent.com/26843533/82974546-9c167780-9fb0-11ea-8615-4b21f48108af.png)

![image](https://user-images.githubusercontent.com/26843533/82974674-e4ce3080-9fb0-11ea-94d3-40dcf9bc537b.png)

Here is my launch.json

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "runtimeExecutable": "deno",
            "runtimeArgs": ["run", "--inspect-brk", "app.ts"],
            "port": 9229
        }
    ]
}
```
When I put the breakpoint at line 3, I am not redirected at first, but I can’t debug to the end of the script (using F10 - Step Over) without being redirected to CLI_SNAPSHOT.js.

**Comment by bartlomieju** [comment]
What version of Deno do you use? This problem was fixed in 1.0.0-rc3 and I can't repeat it locally

**Comment by wsporto** [comment]
deno 1.0.2, vscode 1.45.1 with all extensions disabled, Windows 10.

![image](https://user-images.githubusercontent.com/26843533/83064015-7a140800-a037-11ea-9c3e-22053a9e2433.png)

**Comment by bartlomieju** [comment]
VSCode extension has been upgraded several times since this bug was reported. I'm closing as resolved, feel free to reopen if problem persists.
