### ISSUE TITLE
Environment Variable in Deno undefined

### ISSUE THREAD

**Issue by rwieruch** [denoland/deno#5894]
I tried the following to get an environment variable in Deno with Deno's std library.

*.env* file:

```
PORT=8000
```

*index.ts* file:

```
console.log(Deno.env.get('PORT'));
// undefined
```

Now if I fallback to dotenv as third party library, it works as expected:

```
import { config } from 'https://deno.land/x/dotenv/mod.ts';

console.log(config()['PORT']);
// 8000
console.log(Deno.env.get('PORT'));
// undefined
```

I run this script with `deno run --allow-env --allow-read index.ts` whereas `--allow-read` is needed for dotenv and `--allow-env` for the std. Am I doing anything wrong here? I know everything is pretty early at the moment, so there is lots of development going on.

After all, I would like to use Deno's std library if this is the goal of Deno in the first place. I am not totally sure why there is a third-party library for this. I know it's the equivalent of Node.js' dotenv package, but I was under the impression that Deno wants to provide these functionalities under its std library.

**Comment by MarkTiedemann** [comment]
This works on my machine:

```
$ PORT=8000 deno eval "console.log(Deno.env.get('PORT'))"
8000
```

Do you expect Deno to read `.env` files by default?

`--allow-env` allows accessing environment variables via `Deno.env`.

**Comment by xXACCEXx** [comment]
`.env` files are not native to anything.

In order to use them, there has to be a framework for it; that's what the `https://deno.land/x/dotenv/mod.ts` lib does.

**Comment by xXACCEXx** [comment]
Actually, some native support for `.env` files would be handy for devOps... just sayin'.

**Comment by rwieruch** [comment]
> This works on my machine:
> 
> ```
> $ PORT=8000 deno eval "console.log(Deno.env.get('PORT'))"
> 8000
> ```
> 
> Do you expect Deno to read `.env` files by default?
> 
> `--allow-env` allows accessing environment variables via `Deno.env`.

Ah okay. Somehow I assumed naively that the *.env* would be picked up from Deno the same way as it is picked up for dotenv. So if I am using a *.env* file, then I would always opt-in dotenv? Thanks for the clarification here!

> `.env` files are not native to anything.
> 
> In order to use them, there has to be a framework for it; that's what the `https://deno.land/x/dotenv/mod.ts` lib does.

I understand! Thanks for clarifying this! 👍

**Comment by MarkTiedemann** [comment]
Note that in my example, I did not need to specify `--allow-env`, because I was using `deno eval`. Usually, you are gonna run a script using `deno run`, in which case you do need to specify `--allow-env` to access environment variables. Here's an example:

```bash
$ # Print the content of the script
$ cat example.js
console.log(Deno.env.get('PORT'))

$ # Set the environment variable
$ export PORT=1234

$ # Run the script
$ deno run --allow-env example.js
1234
```

**Comment by nestorPons** [comment]
file .env: 
YOU_CONSTANT=value

file app.ts: 
import { config } from 'https://deno.land/x/dotenv/mod.ts';
await config({export: true}); 

console.log(Deno.env.get('YOU_CONSTANT');

**Comment by typedashutosh** [comment]
How can I get environment variables stored in repositories 'deployment keys' in my deno application?
