### ISSUE TITLE
deno run with basic authentication

### ISSUE THREAD

**Issue by max-pub** [denoland/deno#5897]
Please support basic authentication for "deno run" like
```
deno run https://USER:PASS@xxxx.com/yyyyy.ts
```

**Comment by ry** [comment]
Yes we should support this. Not a high priority for me, but I'd be happy to lend some guidance to anyone who wanted to add this.

**Comment by tumile** [comment]
Hi @ry I can work on this, please let me know where to start.

**Comment by jakajancar** [comment]
Would you then expect that imports also contain username/pass?

Or would the username/pass from the root script magically apply to all imports with the same host (quasi "logged in")?

Or would it work only for single-file scripts?

#1 and #2 seem pretty weird to me. #3 seems clean, though not sure if still useful to people.

**Comment by Yamboy1** [comment]
For imports, especially as basic authentication isn't available all the time, think local urls, it seems like a decent idea to add a cli option for this, or preferably a path to a file with credentials similar to `ssh  -i ~/.ssh/identity_file`. Either this or environment variables seems plausable as well. These credentials would also work for accessing the original file if you're trying to run a file such as the original example: `deno run https://xxxx.com/yyyyy.ts -i ~/.deno/identity` or something like that.

**Comment by tumile** [comment]
Looks like Deno's underlying HTTP client reqwest already allows basic authentication. In the method to fetch remote source
```rust
pub fn fetch_once(
  client: Client,
  url: &Url,  // url: http://user:pass@52.90.21.56/welcome.ts
  cached_etag: Option<String>,
) -> ... {
  ...
  let mut request = client.get(url.clone());
  // request: RequestBuilder { method: GET, url: "http://52.90.21.56/welcome.ts", headers: {"authorization": "Basic dXNlcjpwYXNz"} }
  ...
}
```
Username and password are automatically extracted from URL and set to header. I put up a simple basic auth example, try this:
```
deno run http://user:pass@52.90.21.56/welcome.ts
```
```typescript
import * as script from "http://user:pass@52.90.21.56/welcome.ts";
script;
```

**Comment by max-pub** [comment]
I have to apologize. I was using  ```git clone https://user:pass@local.gitlab.com``` which was working fine, so I expected basic auth behind the scenes. 
Trying to run the project directly from the repository didnt work with deno.
Your example runs just fine.
git seems to to use another authentication method here.

**Comment by JerryGreen** [comment]
If you're going to make an implementation, please consider this suggestion: https://github.com/denoland/deno/issues/5239#issuecomment-726783602

Would be absolutely cool to hear feedback from Ryan (I suspect he loves curl as much as I do, and would like the idea)

**Comment by bartlomieju** [comment]
This is now supported using `DENO_AUTH_TOKENS` env variable: https://deno.land/manual@v1.11.2/linking_to_external_code/private#deno_auth_tokens
