### ISSUE TITLE
deno run with flags

### ISSUE THREAD

**Issue by alirealasad** [denoland/deno#5901]
I have a feature request.

`deno run --flags=myflags.json main.js`

where myflags.json will contains all the arguments like
```
{
    "args":[
        "--allow-net",
        "--allow-env",
        "--allow-read",
        "--allow-write",
        "--allow-plugin",
        "-c tsconfig.json",
        "--importmap=import_map.json",
        "--unstable"
    ]
}
```
because typing those argument again and again feels tedious.

**Comment by nayeemrmn** [comment]
This problem affects all CLI programs... it doesn't make sense for Deno to implement such a general problem and there is already a general solution:
`deno run $(cat myflags) main.js`
```
--allow-net
--allow-env
--allow-read
--allow-write
--allow-plugin
-c tsconfig.json
--importmap=import_map.json
--unstable
```
