### ISSUE TITLE
console.table() adds an extra empty column titled with the heading "Values" when tabulating 2D arrays

### ISSUE THREAD

**Issue by anirudhgiri** [denoland/deno#5902]
## Issue

Passing a 2D array into console.table() appends an empty column titled "Values".

### Code
```ts
let arr =[["Apples","Oranges"],["Bananas","Cherries"]];
console.table(arr);
```

### Expected Behavior

| (index) | 0 | 1 |
| ------------- | ------------- | ------------- |
| 0  | Apples  | Oranges |
| 1  | Bananas | Cherries |

### Actual Behavior
| (index) | 0 | 1 | Values |
| ------------- | ------------- | ------------- | ------------- |
| 0  | Apples  | Oranges |
| 1  | Bananas | Cherries |

![deno_console_table_issue_screenshot](https://user-images.githubusercontent.com/35490486/83050280-f32c5300-a069-11ea-9aa3-3accdb931cf4.png) 

### Specifications

  - Version: 1.0.0
  - Platform: Microsoft Windows

**Comment by pedropaulosuzuki** [comment]
Happens on 1.02 as well.

Deno: 1.0.2
v8: 8.4.300
Typescript: 3.9.2

![image](https://user-images.githubusercontent.com/32345702/83072568-61aaea00-a045-11ea-8315-47a62efb2ec2.png)

**Comment by pedropaulosuzuki** [comment]
And not only with arrays of arrays, but also on arrays of objects. And there might be other cases as well.

![image](https://user-images.githubusercontent.com/32345702/83073009-16450b80-a046-11ea-97ff-c2a6457db9a2.png)
