### ISSUE TITLE
Translation to Spanish

### ISSUE THREAD

**Issue by Angelfire** [denoland/deno#5911]
Hi Denors!

I'm from Colombia (spanish speaker), I just want to know, is there any plan to translate Deno manual into spanish? I am really interested in helping in this project.

Kind regards

**Comment by hugoruscitti** [comment]
I can help too !

**Comment by Soremwar** [comment]
You probably wanna close this and reopen it in the issue tracker for the  [Deno website](https://github.com/denoland/deno_website2). This repo only holds the code for the Deno runtime.

**Comment by nayeemrmn** [comment]
See https://github.com/denoland/deno/issues/5435#issuecomment-629255809 / https://github.com/denoland/deno/issues/5435#issuecomment-634883708. No translations can be maintained in this repo unfortunately, but we can link to them in the manual if you put them up elsewhere.

@Soremwar The manual is indeed maintained in this repo.
