### ISSUE TITLE
URL support for Deno FS methods

### ISSUE THREAD

**Issue by aduh95** [denoland/deno#5916]
I would like to be able to do something like that:

```ts
await Deno.open(new URL('../relative/path.txt', import.meta.url));
```

Currently this fails the TypeScript type checking, and even when bypassing it, it throws a `NotFound: No such file or directory (os error 2)` error.

FWIW Node.js `fs` module methods support it, and IMO it would be a neat addition to Deno.

**Comment by disizali** [comment]
in case of support for accepting URL type argument in fs methods, it should be an easy fix if Deno decides to have.
I think @marcosc90 is working on it as stated in [this comment](https://github.com/denoland/deno/pull/5652#issuecomment-633009323).

_However, it is now available with `fromFileUrl` function from path module._
```ts
import { fromFileUrl } from "http://deno.land/std@v0.52.0/path/mod.ts";
await Deno.open(fromFileUrl(new URL("../relative/path.txt", import.meta.url)));
```

**Comment by marcosc90** [comment]
I'm currently working on https://github.com/denoland/deno/issues/4877 so I don't mind if someone else picks it up.

**Comment by ry** [comment]
I'm all for it. We should be using URLs as much as possible.

**Comment by actual-size** [comment]
I'm pretty green but I'd like to give this a shot
