### ISSUE TITLE
feat(std): Add Package template implements data-driven templates for generating HTML

### ISSUE THREAD

**Issue by getspooky** [denoland/deno#5920]
Hi,
I think that it's good idea to add package template (html/template) that implements data-driven templates for generating HTML output safe against code injection.
what do you think ??

**Comment by Macil** [comment]
This seems like the sort of thing that could be done in user-space. I have an npm package [auto-html](https://www.npmjs.com/package/auto-html) which can be used with Deno through Pika CDN (`import autoHtml from "https://cdn.pika.dev/auto-html@^1.2.0";`).

**Comment by getspooky** [comment]
Hi @Macil,
I think deno should provide this in its core?

**Comment by bartlomieju** [comment]
I believe this functionality should be left to 3rd party libraries. Respectfully closing.
