### ISSUE TITLE
Deno.run throws file not found on windows

### ISSUE THREAD

**Issue by dorshinar** [denoland/deno#5921]
Hi 👋

I'm having some issues using `Deno.run` on windows 10. No matter what command I'm trying to run, it throws an error: `Uncaught NotFound: The system cannot find the file specified. (os error 2)`.
The file contains the following code:
```ts
await Deno.run({ cmd: ["echo", "hi"] }).status();
```
And when I run it in a PowerShell environment:
![83147012-c3c82580-a0ff-11ea-9077-f7a65d5c7b6c](https://user-images.githubusercontent.com/17943918/83147581-9039cb00-a100-11ea-8a04-7a4e981fb02d.png)
Running it in cmd results in the same output. 
Running it in zsh inside WSL works perfectly:
![image](https://user-images.githubusercontent.com/17943918/83147221-10136580-a100-11ea-883a-6b2ffbca4326.png)

Here are the versions I'm using:
![Annotation 2020-05-28 163524](https://user-images.githubusercontent.com/17943918/83148386-93818680-a101-11ea-803d-4473aea1ed51.png)
![Annotation 2020-05-28 163630](https://user-images.githubusercontent.com/17943918/83148286-72209a80-a101-11ea-902c-d154f4bc5b3d.png)

**Comment by marcosc90** [comment]
That's because `echo` is not a program in windows, it's a command from `cmd.exe`.

The following should work:

```javascript
Deno.run({cmd: ["cmd", "/c", "echo", "hi"]});
```

See: https://superuser.com/questions/1084349/where-is-the-echo-command-file-found/1084354#1084354

**Comment by dorshinar** [comment]
Thanks!
