### ISSUE TITLE
can't reexport modules typed by X-TypeScript-Types custom header

### ISSUE THREAD

**Issue by fjc0k** [denoland/deno#5935]
```ts
// mod.ts
export * from 'https://cdn.pika.dev/vtils@3.0.1-beta.2'
```

```ts
// a.ts
import * as vtils from './mod.ts'

console.log(Object.keys(vtils).includes('isNumber'))
```

`deno run -A -r a.ts`:

![image](https://user-images.githubusercontent.com/13151189/83218638-e6f6e180-a1a0-11ea-942a-fa1f01f1f0f2.png)

```ts
// b.ts
import * as vtils from './mod.ts'

console.log(vtils.isNumber)
```

`deno run -A -r b.ts`:

![image](https://user-images.githubusercontent.com/13151189/83218678-fe35cf00-a1a0-11ea-95bb-72f343ba9020.png)

```ts
// c.ts
import * as vtils from 'https://cdn.pika.dev/vtils@3.0.1-beta.2'

console.log(vtils.isNumber)
```

`deno run -A -r c.ts`:

![image](https://user-images.githubusercontent.com/13151189/83218935-a186e400-a1a1-11ea-8136-6a0c95ad73ce.png)

**Comment by marcushultman** [comment]
I see a similar effect when using `@deno-types` and re-export

**Comment by kitsonk** [comment]
Need to try to address in #7225.
