### ISSUE TITLE
Can't import JSON files 

### ISSUE THREAD

**Issue by SafaElmali** [denoland/deno#5936]
I have a JSON file that contains some data to use.

_todo.json_

``JSON
{
    "data":
    [
        {
            "id": 1,
            "detail": "Write a post about Deno with REST API",
            "doneStatus": false
        },
        {
            "id": 2,
            "detail": "Write a post about React connection With Deno REST API",
            "doneStatus": false
        },
        {
            "id": 3,
            "detail": "Love Deno",
            "doneStatus": true
        },
        {
            "id": 4,
            "detail": "Learn Preprocessers",
            "doneStatus": false
        }
    ]
}
``

I want to import and use it in another file.

```ts
import Todo from "../model/todo.ts";
import TodoList from '../data/todo.json';

export const getTodos = (context: any) => {
    context.response.body = TodoList;
}

export const getTodoItem = (context: any) => {
    const selectedId = context.params.id;
    const selectedTodo = TodoList.data.find((item) => selectedId == item.id);

    if (selectedTodo) {
        context.response.body = selectedTodo;
    } else {
        context.response.status = 404;
        context.response.body = { message: `There is no such todo item.` }
    }
}
```

But when I run the app it gives an error:

```error: Uncaught TypeError: Cannot resolve extension for "file:///Users/safaelmali/Desktop/Repos/deno-simple-rest-api-app/data/todo.json" with mediaType "Json".```

Any solution for this? Thanks :)

**Comment by lucacasonato** [comment]
JSON file imports are not supported in Deno. They used to be, but were removed before 1.0 because of security concerns.

**Comment by SafaElmali** [comment]
Thanks!
