### ISSUE TITLE
What are the enabled features for the V8 deno ships with?

### ISSUE THREAD

**Issue by flip111** [denoland/deno#5939]
Would be great to have a list of supported V8 features. I wanted to try [schism](https://github.com/google/schism) which needs `--experimental-wasm-return-call` and `--experimental-wasm-anyref`. I don't know how i can find out if that is enabled.

I guess there is a difference between compile time enabled features and runtime enabled features ... both are interesting to get some information about.

**Comment by ry** [comment]
Use this rather inelegant command to see a list of V8 flags: `deno run --v8-flags=--help _`

**Comment by flip111** [comment]
Thanks @ry that command indeed shows the available flags. How can i see which one is enabled though?

**Comment by bartlomieju** [comment]
@flip111 Deno doesn't pass any flags to v8 by default.

**Comment by ry** [comment]
@bartlomieju Actually we do
https://github.com/denoland/deno/blob/4feccdd3b7d7b1c4ef63c4ccc572a52403135df0/core/core_isolate.rs#L164-L169

**Comment by flip111** [comment]
Is it somewhere in build file encoded which options are passed to V8 on compile time?

**Comment by ry** [comment]
@flip111 it's not - it's hard coded. See link above.

**Comment by bartlomieju** [comment]
Closing as resolved.
