### ISSUE TITLE
Presses of special keys are not detectable by Deno on Windows

### ISSUE THREAD

**Issue by dd-pardal** [denoland/deno#5945]
It is currently impossible to know when the user presses a special key in Console Window Host (the default terminal, `conhost.exe`) or [Windows Terminal](https://github.com/microsoft/terminal).

Here's a test script (needs `--unstable` because of `Deno.setRaw()`):

```js
const stdinRid = Deno.stdin.rid;
if (Deno.isatty(stdinRid))
    Deno.setRaw(stdinRid, true);

(async () => {
    for await (const data of Deno.iter(Deno.stdin)) {
        if (data[0] === 0x03) // Ctrl+C
            Deno.exit();
        console.log(data);
    }
})();
```

This could log an escape sequence when the user presses, for example, the arrow keys (I think it does on Linux), but it logs nothing.

**Comment by apatrida** [comment]
@dd-pardal I get odd behavior from yours as well on Mac, have you tried:

```typescript
if (!Deno.isatty(Deno.stdin.rid)) {
  console.log("Cannot do raw input when not tty");
  Deno.exit(-1);
}

Deno.setRaw(Deno.stdin.rid, true);

while (true) {
    const buf = new Uint8Array(512);
    const bytesRead = await Deno.read(Deno.stdin.rid, buf);
    console.log(bytesRead);
    console.log(buf);
    if (bytesRead === 1 && buf[0] == 0x03) {
        break;
    }
}

Deno.setRaw(Deno.stdin.rid, false);
```

**Comment by prcdpr** [comment]
Any updates on that? Is there at least some workaround?

**Comment by ebebbington** [comment]
Can reproduce the issue windows for me - arrow keys arent being logged

**Comment by denyncrawford** [comment]
Any update about this issue? seems like in 1.8.x it is not possible still

**Comment by dale-roberts** [comment]
Well, Duh, you can also simply use **c:\windows\system32\msvcrt.dll** (the C runtime DLL) directly, and avoid needing the compiler:
```js
const dylib = Deno.dlopen("c:\\windows\\system32\\msvcrt.dll", {
  "_getch": { parameters: [], result: "i32" },
  "_kbhit": { parameters: [], result: "i32" },
});
```
