### ISSUE TITLE
Best way to make callback/signal between rust plugin and module

### ISSUE THREAD

**Issue by lemarier** [denoland/deno#5946]
Hi guys,

Actually I'm working on a mDNS implementation with a rust crate.

### lib.rs
```rust
[...]

#[no_mangle]
pub fn deno_plugin_init(interface: &mut dyn Interface) {
    interface.register_op("mdns_discover_all", op_mdns_discover_all);
}

[...]

#[derive(Deserialize)]
struct IDiscoverParams {
    host: String,
    delay: i16,
   // not sure about this lol?
    onDeviceFound: Fn,
}

fn op_mdns_discover_all(
    _interface: &mut dyn Interface,
    data: &[u8],
    _zero_copy: Option<ZeroCopyBuf>,
) -> Op {

    [...]

    let params: IDiscoverParams = serde_json::from_slice(data).unwrap();

    std::thread::spawn(move || {
        for response in mdns::discover::all(&params.host).unwrap() {
            let response = response.unwrap();

            let addr = response.records().filter_map(self::to_ip_addr).next();

            if let Some(addr) = addr {

                // --> A Callback should be sent to the OP Advertising the new device
                println!("found cast device at {}", addr);

            } else {
                println!("cast device does not advertise address");
            }
        }
    });

    [...]

}

[...]

Op::Async(fut.boxed())
```

I would love to know how you guys suggest implementing this?
Can we pass a function callback from Deno TS binding?
Otherwise, did we have access to a Signal or something like this?

### plugin.ts
```ts
type IDiscoverParams = {
  host: string;
  delay: number;
  onDeviceFound: Function;
};

export async function DiscoverAll(params: IDiscoverParams): Promise<any> {
  return unwrapResponse(await opAsync("mdns_discover_all", params));
}
```

I hope it's clear? If you guys need more details let me know!

Thanks again and good work!!!

**Comment by bartlomieju** [comment]
@lemarier I'm not sure what's the question here... Is it about passing JS callback into Rust op? If so then you cannot do that. Only binary array buffers data can be sent between JS and Rust.

**Comment by viztastic** [comment]
@bartlomieju I remember Ryan talking about having a way for rust apps to interface with typescript as part of the vision behind Deno. Is that no longer the case? Or are you saying there's a specific pattern to support that (binary array buffers). Is there an example? Couldn't seem to find one in the docs.

**Comment by crowlKats** [comment]
@viztastic https://github.com/denoland/deno/tree/master/test_plugin. currently no documentation available, still quite unstable

**Comment by lemarier** [comment]
Thanks guys! 

@bartlomieju -- Yes sorry for not being clear. We need a way to send a callback to JS but keeping the mod alive. I've been able to do it with a polling system. The main function init a thread who register and another op who get and dispatch to JS. (with a timeout on JS side to call the polling function)

Hopefully, there will be more elegant way to address it soon

Thanks!
