### ISSUE TITLE
Is it any alternative to run deno http server in cluster mode?

### ISSUE THREAD

**Issue by devalexqt** [denoland/deno#5965]
Is it possible to run deno http server on all available cpu?

**Comment by ry** [comment]
No, we don't have that functionality, yet, unfortunately.

**Comment by alxtsg** [comment]
Does using Worker count? Here is a prototype:

`app.ts`:

```
const START_PORT = 8000;
// Adjust to the number of CPU cores.
const WORKER_COUNT = 4;
for (let i = 0; i < WORKER_COUNT; i += 1) {
  const worker = new Worker(
    "./server_worker.ts",
    {
      type: "module",
      deno: true,
    },
  );
  worker.postMessage({
    port: START_PORT + i,
  });
}

```

`server_worker.ts`:

```
import { serve } from "https://deno.land/std@0.54.0/http/server.ts";

self.onmessage = async (e) => {
  const { port } = e.data;
  const server = serve({
    hostname: "127.0.0.1",
    port,
  });
  console.log(`Started an HTTP server listening on port ${port}.`);
  for await (const req of server) {
    req.respond({ body: "Hello World\n" });
  }
};

```

Start the server:

```
# Running Deno in worker is an unstable feature, so we need to add the
# --unstable flag.
deno run --allow-read --allow-net --unstable app.ts
```

In the example above, 4 HTTP servers will be started.

```
Started new HTTP server listening on port 8001.
Started new HTTP server listening on port 8000.
Started new HTTP server listening on port 8002.
Started new HTTP server listening on port 8003.
```

You can put a load balancer in front of the application and distribute the requests to each of the HTTP servers.

This is not the same as using [cluster](https://nodejs.org/dist/latest-v12.x/docs/api/cluster.html) in Node.js to start multiple HTTP servers, because the HTTP servers in the Workers cannot listen on the same port.

**Comment by devalexqt** [comment]
Thanks for reply, but do You guys planing add this features or its out of focus for now?

**Comment by devalexqt** [comment]
"same port" is a key

**Comment by alxtsg** [comment]
See #3403 and #5377, looks like not much progress on that area yet.

**Comment by ry** [comment]
@devalexqt We don’t have plans to add that feature - but I’d be open to discussing how it could be done with web workers. Basically we need the ability to send resources to other workers - then you would share the server resource...

**Comment by devalexqt** [comment]
Yea, resource sharing with workers will be elegant solution!

**Comment by ngot** [comment]
I had done a similar cluster module using the worker feature in another JS runtime called [fibjs](https://github.com/fibjs/fibjs). Transferring an object's ownership to another isolation(or call it worker) is the key point. (fibjs only supports transfer network socket and Buffer, tbh, socket is enough)

This is the module I wrote https://github.com/fibjs-modules/cluster-server#usage, the key implementation is https://github.com/fibjs-modules/cluster-server/blob/master/lib/cluster.js#L92

According to 
- https://developer.mozilla.org/en-US/docs/Web/API/Worker/postMessage
- https://nodejs.org/api/worker_threads.html#worker_threads_port_postmessage_value_transferlist
Both  Browser and Node support passing Transferable objects. But it seems they don't support transfering Socket object.

Anyway, if it is possible to support transfer `Deno.Conn`(or something smiliar) between workers, it will be feasible to implement cluster.

**Comment by kedicesur** [comment]
What @alxtsg suggested may work by starting a load balancer ahead. Such as [gobetween](http://gobetween.io/documentation.html) which is very simple. I just tried it with 4 sessions of [denotrain](https://github.com/Caesar2011/denotrain) working on localhost on 4 different ports and req/sec increased from ~17000 req/sec to ~55,000 req/sec when tested with wrk.

**Comment by abaldawa** [comment]
@alxtsg What's the point of starting HTTP servers within workers if you are gonna put a manual load balancer in the front? Just start 4 separate Deno HTTP server processes and manually put load balancer on the front then for even better performance. The whole point of cluster module was they do port sharing and load balancing for you. If Deno does not have that then there is no point in using workers to start listening on separate port when workers are not as efficient in IO as main thread.

**Comment by alxtsg** [comment]
@abaldawa It depends on what you want to do and the requirements. Maybe in some cases you can't put a load balancer in front of the application for whatever reasons.

**Comment by matthewharwood** [comment]
Cluster allows to vertical scale compute e.g 1 instance with many cores. We've been doing significant work on node and found that vertical scaling one instance with 6 core across  instances with load balancing has significant gains over single core with load balancer across more instances.

**Comment by alexindigo** [comment]
Wondering if anything changed in this area.
