### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by sanny-15** [denoland/deno#5968]
Compile file:///G:/node.js/FINAL/data/deno-mongo-rest/DB/mongo.ts
error: TS2339 [ERROR]: Property 'openPlugin' does not exist on type 'typeof Deno'.
  return Deno.openPlugin(localPath);
              ~~~~~~~~~~
    at https://deno.land/x/plugin_prepare@v0.6.0/mod.ts:64:15

**Comment by kitsonk** [comment]
`deno run --unstable`

**Comment by lucacasonato** [comment]
Try with Deno v1.0.3 - you should get a more helpful error message.

**Comment by ry** [comment]
As @kitsonk noted, use --unstable
