### ISSUE TITLE
How to open a file with right path

### ISSUE THREAD

**Issue by mtwzim** [denoland/deno#5971]
Hey guys, i tried open a file in a path with: Deno.open. But the terminal returns: "The system cannot find the file".
![image](https://user-images.githubusercontent.com/42474938/83331473-11ae6c00-a26d-11ea-8e6a-81a381e548d3.png)

I can't specify the entire path, is there any way to do this?

**Comment by lucacasonato** [comment]
The Deno filesystem APIs are relative to the working directory, not to the file it is being called from. The path relative from your working directory should would be `./src/core/next/next.html`.

**Comment by mtwzim** [comment]
> The Deno filesystem APIs are relative to the working directory, not to the file it is being called from. The path relative from your working directory should would be `./src/core/next/next.html`.
Is there no other way to do this? I cannot use the entire path.

**Comment by nayeemrmn** [comment]
> Is there no other way to do this? I cannot use the entire path.
```ts
import { fromFileURL } from "https://deno.land/std@0.53.0/path/mod.ts";
// ...
await Deno.open(fromFileUrl(new URL("next.html", import.meta.url)));
```
Note the modules are for organising code, not resources. Hence the hoops you have to jump through to do this.

**Comment by mtwzim** [comment]
> > Não há outra maneira de fazer isso? Não posso usar o caminho inteiro.
> 
> ```ts
> import  {  fromFileURL  }  de  "https://deno.land/std@0.53.0/path/mod.ts" ; 
> // ... 
> aguarde  Deno . open ( fromFileUrl ( novo  URL ( "next.html" ,  importação . meta . url ) ) ) ;
> ```
> 
> Observe que os módulos são para organizar código, não recursos. Portanto, os aros que você precisa pular para fazer isso.

Thank you. yes...
