### ISSUE TITLE
std/node: support Node errors.

### ISSUE THREAD

**Issue by marcosc90** [denoland/deno#5972]
Currently, we're not consistent with errors thrown in `std/node` and we should implement Node.js errors instead of throwing Deno errors.

For example a common check for Node.js `fs` is:

```
e.code === 'ENOENT'
```

The above is not currently supported.

**Comment by nayeemrmn** [comment]
Duplicate of #5944?

**Comment by marcosc90** [comment]
@nayeemrmn By bad again, Disizali did not reported here: https://github.com/denoland/deno/pull/5540#discussion_r432439095 and thought no one opened it.
