### ISSUE TITLE
Deno.close() does not work with plugins

### ISSUE THREAD

**Issue by Pandawan** [denoland/deno#5975]
I know plugins are currently unstable so this might be something that is in the works, but I thought I'd report it anyways.

It seems calling `Deno.close()` on a previously opened Deno plugin (with `Deno.openPlugin()`) does not actually do anything. The ops registered by the plugin are still available in `Deno.core.ops()` and they are still callable.

I've written a quick test script to reproduce the issue but you need your own plugin
```ts
import { resolve } from "https://deno.land/std@v0.53.0/path/mod.ts";
import { assert } from "https://deno.land/std@v0.53.0/testing/asserts.ts";

// Pass in the path to a plugin here
const pluginPath = Deno.args[0] || './target/debug/libdeno_notify.dylib';
const filename = resolve(pluginPath);
console.log("Opening plugin:", filename);

const pluginId = Deno.openPlugin(filename);

// This passes
assert((Deno as any).core.ops()['notify_send'], "Notify ops do not exist while they should be available.");

Deno.close(pluginId);

// This fails
assert(!(Deno as any).core.ops()['notify_send'], "Notify ops still exist while they should be removed.");
```
Note: I ran this with `deno 1.0.3`, `v8 8.4.300`, `typescript 3.9.2`

**Comment by bartlomieju** [comment]
CC @afinch7

**Comment by afinch7** [comment]
This is less of a big and more of a oversight. I'm working on a fix.

**Comment by afinch7** [comment]
We don't currently have any way to unregister ops in core. We need to address that first or not allow closing plugins. I struggle to find any good reason to need to call close on plugin.

**Comment by PandawanFr** [comment]
I wanted to close the plugin so I could test different approaches to plugin loading: testing my plugin when loaded or not, when loaded manually using `Deno.openPlugin()`, or when auto-loaded with `deno-plugin-prepare`, etc. 

But since `Deno.test()` instances "share" the same plugins (even across files), I needed a way to unregister the plugin at the start/end of tests.

I'm sure there are other use cases, but I think in general it's good to have a way to be able to reset your state/resource usage, including plugins.

**Comment by ry** [comment]
It's unclear to me whether it's useful to unload plugins. It's definitely going to complicate matters...

**Comment by afinch7** [comment]
After looking at the complexity involved in unloading plugins, it might make more sense to just support loading the same plugin more than once.

**Comment by lucacasonato** [comment]
Plugins are in the process of being removed in favor of FFI, so I'll close this issue.
