### ISSUE TITLE
Iterating frozen arrays is about 8x slower than normal arrays

### ISSUE THREAD

**Issue by iMarv** [denoland/deno#5981]
I do not know if this is a v8 or deno issue, there have been issues with perfomance of frozen _objects_ with v8 in the past, but I can't find any issue with arrays. Feel free to close this if it is not deno related.

Currently trying to restrict mutability in a project of mine by using `Object.freeze()`.
I came across some performance issues after refactoring to the freezing, which surprised me because I expected better perfomance as a frozen array should probably require less checks on runtime compared to a mutable array.

You can reproduce the issue with these benchmarks: https://gist.github.com/iMarv/28626689223eebe0c9fd1ffccaf8fd94/raw/72d9c6d113c3588922af81114d3efade7d577c53/bench.ts

**Comment by ry** [comment]
This is a V8 issue. I don’t have any idea what causes this - but I guess you’re getting kicked out of some optimization.

I don’t think there’s anything actionable for us on this.
