### ISSUE TITLE
Add support for rethinkdb

### ISSUE THREAD

**Issue by paavalan** [denoland/deno#5983]
please add module for rethinkdb

**Comment by crowlKats** [comment]
this is something that a module should resolve, not something that should be built-in into deno. This is the wrong place to ask for such a request.

**Comment by lucacasonato** [comment]
> please add module for rethinkdb

As crowlKats said this is not the place to ask. Anyway, I have a WIP driver for rethinkdb in the works, but I got fed up with some typescript issues so I never released it. Might release it soon.

**Comment by jcs224** [comment]
@lucacasonato put it out there anyway! If nothing else, it could help speed up the process for others who might want to create a package.

**Comment by hkong** [comment]
@lucacasonato that driver works quite well for the fairly simple requirements that I have at the moment.
