### ISSUE TITLE
addEventListener with CustomEvent

### ISSUE THREAD

**Issue by chrisands** [denoland/deno#5998]
Hi,

I tried to write an app with Deno and noticed that `addEventListener` doesn't return `detail` property on a `CustomEvent`.
It should return `detail` property.

UPD: my bad, it actually returns `detail` property, but it doesn't exist on type `EventListener`.

**Comment by chrisands** [comment]
Also there probably should be generic `CustomEventListener` or type `EventListener` should be generic with detail property.

**Comment by crowlKats** [comment]
this might be related to microsoft/TypeScript#28357

**Comment by deebloo** [comment]
@chrisands if you manually add the "DOM" lib to a custom tsconfig does that cause the issue to go away? I haven't seen this issue with ts in some time

**Comment by chrisands** [comment]
@deebloo it throws error that I should also add es* lib
```
TS2583 [ERROR]: Cannot find name 'Promise'. Do you need to change your target library? Try changing the `lib` compiler option to es2015 or later.
    readonly trailer: Promise<Headers>;
                      ~~~~~~~
    at $asset$/lib.dom.d.ts:12616:23
```
When I add esnext to tsconfig I get Deno errors
```
TS2304 [ERROR]: Cannot find name 'Deno'.
  private debug?: string = Deno.env.get("DEBUG_BOT")
                           ~~~~
    at file:///Users/osiyuk/Projects/telegram-netlify-bot/src/utils/logger.ts:3:28
```

**Comment by deebloo** [comment]
Ah that makes sense. I think if you do it this way you need to run 'deno types' and generate the type definitions manually.

**Comment by chrisands** [comment]
@deebloo thank you for explaining. Well, adding "dom" lib doesn't help the issue go away.
```
error: TS2339 [ERROR]: Property 'detail' does not exist on type 'Event'.
    console.log("message event", e.detail)
```

**Comment by deebloo** [comment]
@chrisands you will need to manually specify that your event is a "CustomEvent<any>"

**Comment by chrisands** [comment]
I did this to make it work:
```
// it's class method
  on = <T extends keyof Events>(
    type: T,
    callback: CustomEventListener<Events[T]>
  ) => {
    addEventListener(type, callback as EventListener)
  }
```
```
export interface CustomEventListener<T = any> {
  (evt: CustomEvent<T>): void | Promise<void>
}
```

**Comment by deebloo** [comment]
for simple examples this also works

```
addEventListener("something", (evt) => {
  const e = evt as CustomEvent<any>;

  console.log(e.detail);
});
```

**Comment by F3n67u** [comment]
@chrisands  Can you confirm this is still an issue?

**Comment by crowlKats** [comment]
@F3n67u This is still an issue as it is an upstream issue as per microsoft/TypeScript#28357.

**Comment by lucacasonato** [comment]
I'm going to close this as an upstream TS issue.
