### ISSUE TITLE
Python ctypes(foreign function interface) -like library to call C function from Deno

### ISSUE THREAD

**Issue by v-andrew** [denoland/deno#6016]
It very simple to use `C` libraries from Python. So you see every tool has Python wrapper and can be used in the Python app.

It would be nice to have similar functionality in Deno.

I believe it would a feature which will Deno popular in ML and as _wrapper_ for `C` libraries.

**Comment by ry** [comment]
This is probably not something we will be undertaking. We are working on a way to load Rust DLLs to extend functionality. The feature is currently unstable. Have a look at 

https://github.com/denoland/deno/tree/master/test_plugin
