### ISSUE TITLE
feat(std/io): Add LimitedReader

### ISSUE THREAD

**Issue by hastri** [denoland/deno#6019]
It would be nice to be able to limit the size of the returned Uint8Array, so you can use it without having to worry about running out of memory, e.g.

```typescript
try {
  const buf = await Deno.readAll(req.body, { limit: 4096 });
} catch {
  console.error('Request body exceeded 4096 byte');
}
```

**Comment by ry** [comment]
The way Go does this is by wrapping a Reader with a LimitedReader
https://golang.org/pkg/io/#LimitedReader
I would welcome this to be added to std/io

**Comment by hastri** [comment]
Interesting, the only problem I see is that limit reached and EOF behave the same, so you would have to extend the interface or make a read(new Uint8Array(0)) to check if there is any data left

**Comment by ry** [comment]
I'm not sure I follow you. The code can be ported directly from Go: https://golang.org/src/io/io.go?s=14905:14998#L429

**Comment by hastri** [comment]
Yes, but we would need some way to differentiate limit reached and EOF, since read(...) can only return number | null

**Comment by hastri** [comment]
Either way, this behavior certainly has it's uses, and a port should be simple enough for a first issue, so I'll get started on it

**Comment by ry** [comment]
> Yes, but we would need some way to differentiate limit reached and EOF, since read(...) can only return number | null.

Not sure I understand. `readAll(new LimitedReader(reader, N))` if you get N bytes back then it was limited. If you get less than N, you got an early EOF...

**Comment by hastri** [comment]
With N bytes, it could be either complete or limited

**Comment by hastri** [comment]
Maybe we could add a helper function like

```typescript
import { serve } from 'https://deno.land/std/http/server.ts';
import { LimitedReader } from 'https://deno.land/std/io/mod.ts';

const empty = new Uint8Array();

export async function isEol(reader: Deno.Reader) {
  return (await reader.read(empty)) == null;
}

for await (const req of serve({ port: 8080 })) {
  await Deno.readAll(new LimitedReader(req.body, 4096));
  if (!(await isEol(req.body))) {
    req.respond({ status: 413 });
  } else {
    req.respond({ status: 200 });
  }
}
```

I'd add it if that's okay

**Comment by bartlomieju** [comment]
@hastri sounds good 👍
