### ISSUE TITLE
Feature Request: Hidden Input

### ISSUE THREAD

**Issue by bfaulk96** [denoland/deno#6024]
It seems pretty common practice to allow reading hidden input (i.e. passwords) from the CLI. It appears there are Rust crates that support this as well; can we expose this ability to Deno? As a current workaround, one could probably just clear input on each raw byte that is read, but that seems pretty hacky for a simple task such as password input.

**Comment by deebloo** [comment]
Is this something that should be built into a std lib or is it best to live in a 3rd party module?

**Comment by caspervonb** [comment]
`Deno.setRaw` is currently behind the --unstable flag which is what we'll need to get raw input without echoing (whipped up https://github.com/caspervonb/deno-prompts as a quick and dirty example).

**Comment by bfaulk96** [comment]
Ah, thank you very much! I suppose this can be closed, maybe it would be a good 3rd party lib as deebloo suggested.

**Comment by alexgleason** [comment]
For anyone else who finds this in the future, there is now a [`promptSecret`](https://jsr.io/@std/cli/doc/~/promptSecret) function in `@std/cli`.
