### ISSUE TITLE
??? Failed to get directory listing ???

### ISSUE THREAD

**Issue by validate472** [denoland/deno#6025]
![Image of Yaktocat](https://i.ibb.co/TgDJxDc/deno.png)

pls fix, I want to learn more

**Comment by Pangoraw** [comment]
Probably linked to https://github.com/denoland/deno_website2/issues/433

**Comment by validate472** [comment]
oops sry i should go to deno_website2

**Comment by nayeemrmn** [comment]
Duplicate of https://github.com/denoland/deno_website2/issues/433.
