### ISSUE TITLE
Display commit in deno version.

### ISSUE THREAD

**Issue by jingkaimori** [denoland/deno#6037]
It's necessary to set the output of `deno --version` like the text below: 40419c664d402d4c3c5783d0ae337d23c106f619
```text
deno 1.0.3
build 40419c6<https://github.com/denoland/deno/commit/40419c664d402d4c3c5783d0ae337d23c106f619>
target x86_64-unknown-linux-gnu
v8 8.4.300
typescript 3.9.2
```
so we can easily refer to a specific version of source repository and target OS in an issue.

**Comment by kitsonk** [comment]
The [git tag](https://github.com/denoland/deno/tags) of the version already points at the specific commit, so the version number is sufficient for triaging defects.

If we start publishing "daily" builds, then some sort of information could be added then.  Building building from source should understand what they are doing to be able to open issues.
