### ISSUE TITLE
Update timers to not depend on globals

### ISSUE THREAD

**Issue by KyleJune** [denoland/deno#6040]
Currently [timers.ts](https://github.com/denoland/deno/blob/master/cli/js/web/timers.ts#L74) uses `Date.now()` to determine if timer callbacks should be called.
Sometimes people need to fake time in their tests to verify it behaves correctly. [SinonJS](https://sinonjs.org/releases/v9.0.2/fake-timers/) fakes time by temporarily replacing `globalThis.Date`, and the timer functions on `globalThis`. Currently if you replace `globalThis.Date` or `globalThis.Date.now` in deno, the callbacks for timers will not be called. In the browser setTimeout and setInterval do not use the global date object, so you can safely override those globals without disrupting timers. That is necessary to be able to create a fake date implemention that has time advancing forward on its own. The way SinonJS does it is by calling setInterval with a callback that advances the fake Date implementation forward in intervals.
I believe this could be accomplished by creating a local variable in the timers.ts file like `const now = Date.now.bind(Date);` then replacing all calls to `Date.now()` with `now()`. That would make it so that the timers are not effected by `globalThis.Date` being changed or replaced.

**Comment by kevinkassimo** [comment]
This is actually not just limited to timer, but all builtins. Deno currently just uses the globals from the environment, yet they subject to overwrites and can cause unexpected behaviors. For example, the simplest way to crash REPL is `window.Object = 1`.

**Comment by bartlomieju** [comment]
Fixed in #6552
