### ISSUE TITLE
Update swc_ecma_parser to 0.24

### ISSUE THREAD

**Issue by kdy1** [denoland/deno#6047]
I fixed lots of bugs related to typescript parsing.
I'm leaving an issue here because the bugs contain some serious bugs.

See: https://github.com/swc-project/swc/pull/811

**Comment by Pangoraw** [comment]
It should fix https://github.com/denoland/deno/issues/5978 as well :+1:

**Comment by bartlomieju** [comment]
Thanks for opening the issue @kdy1. CC @dsherret

**Comment by dsherret** [comment]
Ran my test suite and ran into this bug https://github.com/swc-project/swc/issues/814 so I don't want to upgrade until that's fixed.

It's a common use case for union types in arrow function expressions: https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAE8MEsoDmmAvJgBQA6UmNmADgIYBODAtkphk-gQDRW1MEGAAs4TDlACurAEbj+UAJRIBtAD6cY3Qmpqbpc8XswGZ8pibNHL1DVp0ErWmK7fuPnr25IA+KsAmTHAwUkzUAKwA3FQAvlEgvCAQdDC46MigzEwQAO4ACswIaMggDAA2uQwAniVJsixgANYhAMqMYDzI2lJwSSIwrOUA6iK4OB1wrcXjuABu49WlYGh1IPho4jD5LASsDMgAZhWbSQBWaAAeAEKNLTCtbHAAMvhwRyd9IBeXrTzlcAAilJhO8kMdyqcQIwmJsmKUYNU6HA0GBuKlEtCdDBhrgACaiZAADgADEk6DlNsMWHRShSUeI5u8kgBHEHwHYpEooBhoAC0UDgcDxwsxwTZuGCOwYewO4M+SU2rFw3SYvUV-yB7LBEKhMAYslxBJEyAATEltAxcOUeABhCCsfalFERTFSTYAFQN3N1XzmvQAklARbBWmjcKkAILB1qIgEfSFwWKxIA

**Comment by dsherret** [comment]
I opened a PR for this. I did a test and looks like #5978 is still occurring though.

**Comment by kdy1** [comment]
Note for #5978: While the bug is fixed, you can use `TsCondig.no_early_errors` to avoid error messages
