### ISSUE TITLE
Uncaught SyntaxError: Unexpected token I in JSON at position 0

### ISSUE THREAD

**Issue by gungunfebrianza** [denoland/deno#6049]
Hello guys try to execute fetch method on deno, but seems the problem is in the core :

```
async function postData(url = "", data = {}) {
  const response = await fetch(url, {
    method: "POST",
    mode: "cors", // no-cors, *cors, same-origin
    cache: "no-cache", // *default, no-cache, reload, force-cache, only-if-cached
    credentials: "same-origin", // include, *same-origin, omit
    headers: {
      "Content-Type": "application/javascript",
      // 'Content-Type': 'application/x-www-form-urlencoded',
    },
    redirect: "follow", // manual, *follow, error
    referrerPolicy: "no-referrer", // no-referrer, *no-referrer-when-downgrade, origin, origin-when-cross-origin, same-origin, strict-origin, strict-origin-when-cross-origin, unsafe-url
    body: JSON.stringify(data), // body data type must match "Content-Type" header
  });
  return response.json();
}

postData("http://127.0.0.1:8000/api/v1/signup", {
  name: "balagendir",
  email: "asepkumis@gmail.com",
  password: "tosblong",
}).then((data) => {
  console.log(data);
});
```

here is the error message : 

```
error: Uncaught SyntaxError: Unexpected token I in JSON at position 0
    at JSON.parse (<anonymous>)
    at Response.json ($deno$/web/body.ts:268:17)

```

**Comment by marchiore** [comment]
@gungunfebrianza what's the return of `http://127.0.0.1:8000/api/v1/signup`?

**Comment by gungunfebrianza** [comment]
hi math thank you fo response, i will take a look now,

**Comment by kitsonk** [comment]
> maybe we need a better deal for these cases, but i don't know now how the best approach for this problem

How would you improve an error that indicates that the input is invalid JSON when the input is invalid JSON?

**Comment by marchiore** [comment]
@kitsonk the only way i can see to solve it is checking before parse if the `raw` variable is a valid JSON something like this:

```js
function isJson(str) {
    try {
        JSON.parse(str);
    } catch (e) {
        return false;
    }
    return true;
}
```
and instead of show:
```
error: Uncaught SyntaxError: Unexpected token I in JSON at position 0
```

we show something like: 

```
The response body of your request is not a valid JSON.
```

what do you think? if this is a good solution I can work on a PR for this.

**Comment by kitsonk** [comment]
That would require parsing the JSON twice then, not very good from a performance perspective.

If the normal error that indicates that the JSON is not valid is not sufficient, a `try ... catch` around the actual `JSON.parse()` that throw a different error would be more logical, then you would only be parsing the JSON once.  Where ever the `.json()` is being called should implement a `try ... catch` that handles the error in a good way.  It is hard to tell from the code here, where the `.json()` is being called.

**Comment by marchiore** [comment]
The `.json` is called in the `fetch` response:

```js
const response = await fetch(url, {...});
response.json();
```

This error can really be dealt with outside deno (in the script running it) and i think there is no need to handle it in the framework. So I believe that this issue can be closed.
