### ISSUE TITLE
error: error sending request for url (https://deno.land/std/path/mod.ts)

### ISSUE THREAD

**Issue by niyarlatotep** [denoland/deno#6061]
I'm behind a corporate proxy and on tring to install script deno I get this error:
```
Download https://deno.land/std/path/mod.ts
error: error sending request for url (https://deno.land/std/path/mod.ts): error trying to connect: received corrupt message
```
I'm on windows, HTTP_PROXY and HTTPS_PROXY env variables are set.

**Comment by ry** [comment]
Hmm.. It's possible our HTTPS_PROXY isn't used for module resolution?

**Comment by jhonatantft** [comment]
The format of your environment variables looks like this `http://proxy-domain.com:PORT/`?

**Comment by Niyarlatotep** [comment]
@jhonatantft yes, exactly 
```
set HTTPS_PROXY=http://proxy-domain.com:PORT
set HTTP_PROXY=http://proxy-domain.com:PORT
```

**Comment by onyz4x** [comment]
same problem, no solution
i got "clashr for window" for proxy

![image](https://user-images.githubusercontent.com/15812120/83998165-99455a80-a992-11ea-8411-b7109ffdac98.png)

**Comment by Randysheng** [comment]
i have the same problem.

**Comment by yanglr** [comment]
I met the same issue when installing Deno on Windows 10, eventually I found it is a problem with my certificate files. There is an exsisting solutoin - [mkcert](https://github.com/FiloSottile/mkcert).

I opened PowerShell as admin, then run below command:
```powershell
choco install mkcert
```

Then I can run the `.ts` code successfully.

Linux or Mac, please refer to the README of [mkcert](https://github.com/FiloSottile/mkcert).

May it be helpful for you too.

**Comment by YuzhiZhang** [comment]
> same problem, no solution
> i got "clashr for window" for proxy
> 
> ![image](https://user-images.githubusercontent.com/15812120/83998165-99455a80-a992-11ea-8411-b7109ffdac98.png)

You could try like this, it work for me in Win 10(windows terminal/PowerShell)
![1611162197(1)](https://user-images.githubusercontent.com/29254365/105209154-79ab1d00-5b84-11eb-99b1-28314400ebfb.jpg)

**Comment by ouweiya** [comment]
**Clash starts the proxy terminal and will solve this problem.**


![Clash_for_Windows_AFoIi6rCSg](https://user-images.githubusercontent.com/28357731/108588313-69f54300-7393-11eb-80de-7e635b7f7b06.png)

**Comment by salemalem** [comment]
same problem
