### ISSUE TITLE
deno test simply prefixes everything with `test <testname>`

### ISSUE THREAD

**Issue by aricart** [denoland/deno#6083]
With multiple files, it would be more useful if the test runner simply listed `<test_file> <testname>`. To provide a hint of the location of the test.

**Comment by nayeemrmn** [comment]
Duplicate of #4644.

Not possible, a function can't know "what module it's being run from" without doing something really hacky which probably won't work for wrappers around `Deno.test()`. The error stack from a failing test should be enough, right?

**Comment by bartlomieju** [comment]
Please continue in #4644
