### ISSUE TITLE
datetime – more general aproach?

### ISSUE THREAD

**Issue by timreichen** [denoland/deno#6090]
I wonder if it would make sense for the std/datetime module to be more generalised so it could parse any kind of format with any kind of separator.

For example:

```ts
// uses "." as separator and different format
parseDate("03.06.2020", "DD.MM.YYYY") // parses as expected to Date(2020, 06, 03)
```

I created a minimal datetime module not too long ago with that exact functionality. I would happily contribute that code to this great project.

I would propose to have the following format fragments parsable ([ISO 8601](https://www.w3.org/TR/NOTE-datetime)):

```ts
export enum Format {
  fullYear = "YYYY",
  year = "YY",
  fullMonth = "MM",
  month = "M",
  fullDay = "DD",
  day = "D",

  fullHours = "hh",
  hours = "h",
  fullMinutes = "mm",
  minutes = "m",
  fullSeconds = "ss",
  seconds = "s",
  fullMilliseconds = "fff",
  milliseconds = "ff"
}
```

What are your thoughts on that?

**Comment by timreichen** [comment]
I ported it to Deno and ran the tests successfully. One change and two additions to the proposal:

## Format.milliseconds
To be consistent changing the Format.milliseconds to ```"f"``` to allow a single digit formatting.

## parseDate and parseDateTime
Since the format segments and separator would not be restricted anymore```parseDateTime``` can be dropped as the same can be achieved with ```parseDate```:

Example:
```ts
parseDate("2020-01-01", "YYYY-MM-DD") // output: Date(2020, 0, 1)
parseDate("01.01.2020 22:01", "DD.MM.YYYY hh:mm") // output: Date(2020, 0, 1, 22, 01)
```

## stringifyDate
to make ```std``` align close to native ```js``` (as in ```JSON.parse```and ```JSON.stringify```), I would suggest to have a ```stringifyDate``` function that turns a date instance into a custom format.

Example:
```ts
stringifyDate(new Date(2020, 0, 1), "YYYY-MM-DD") // output: "2020-01-01"
stringifyDate(new Date(2020, 0, 1, 22, 1), "DD.MM.YYYY hh:mm") // output: "01.01.2020 22:01"
```

Would that be in the interest of Deno @bartlomieju  ? If so I will open a pull request.

**Comment by cknight** [comment]
This seems like it would be a good improvement to `std/datetime`.  One thing I don't see covered above, would you intend to include parsing of 12-hour times?  E.g. 3:45pm.  Also, what about letting `f` specify an arbitrary number of millisecond digits?  For example `ffffff` for 6 digit milliseconds.

**Comment by timreichen** [comment]
Well, Millisecond by definition is 1/1000 of a second so 999 should be the maximum and therefore ```"fff"``` should suffice in my opinion. Also ```Date``` doesn't support microseconds at the moment.

As for 12-hour times: What format would you suggest?

**Comment by cknight** [comment]
`Date` may not support microseconds, but strings "can" and without the tokens to represent the microseconds you wouldn't be able to parse something like `2000-01-20 11:30:23.123456' into a `Date`.  I guess the key is to document the loss of precision. 

As for 12-hour times you could follow [moment's approach](https://momentjs.com/docs/#/parsing/string-format/) with the 'a' token to represent the location of either 'am' or 'pm' in the string.  The presence of the token 'a' would dictate if hours/full hours were 12 or 24 based.  E.g.
```
parseDate("01.01.2020 10:01pm", "DD.MM.YYYY hh:mma") 
// output: Date(2020, 0, 1, 22, 01)

stringifyDate(new Date(2020, 0, 1, 22, 1), "DD.MM.YYYY hh:mma"); 
// output: "01.01.2020 10:01pm" 
```

**Comment by timreichen** [comment]
The basic idea of this issue was to have a more general approach to the functionality the datetime std module already had and a stringify function.

Since this is concerning a more complete functionality like ```12-hour```:
@ry  I wonder how far the datetime std should be enriched. I would love to see Deno having a small module that covers all basic features while be compatible with the current ```js``` standards like ```Intl.DateTimeFormat```? What are your thoughts on that?

If so it would make sense to list the features and I would be eager to implement them.

@cknight I just found inspiration when looking up the [Intl.DateTimeFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/DateTimeFormat) specs. What would you think of this concerning 12-hour? 

```ts
export class Formatter {
  …
  format(date: Date): string {
    …
  }
  parse(string: string): Date {
    …
  }
}
```

```ts
const formatter = new Formatter("DD.MM.YYYY hh:mm", { hour12: true })
formatter.format(new Date(2020, 0, 1, 21:15)) // output: "01.01.2020 9:15 PM"
```
```ts
const formatter = new Formatter("DD.MM.YYYY hh:mm", { hour12: true })
formatter.parse("10.10.2020 09:15 PM") // output: Date(2020, 10, 10, 21, 15)
```

That looks very clean to me, is comparable to current ```js``` conventions and a similar case can be made with  ```fractionalSecondDigits``` instead of ```"fff"``` and ```"f"```.

**Comment by cknight** [comment]
It does look clean and I like keeping close to JS standards.  However, it is also less flexible.  Some people write 12-hour times as `4:45am`, `4:45a.m.`, `4:45 A.M.` or `4:45 a.m.` and probably others for example.  The above proposal doesn't allow for these variants.  I personally like having the power and flexibility of a full set of parsing/formatting tokens to allow exact specification of the format, a feature found in the widely used [moment](https://momentjs.com/docs/#/parsing/string-format/) library.  I guess it comes down to how far we want to take this.  For example, do we also want to support weekday names? E.g. Wed, W, Wednesday.  Same question for months. E.g. Jan, January.

**Comment by timreichen** [comment]
Yeah, I think this is a matter of defining the scope of functionality. Because If we implement weekdays etc. we probably should have I18n too. Either this is done by static typing every supported language (like dayjs) or some clever extractions and native functionality use once ```Intl``` is supported (what I would prefer).
I hope Ryan @ry  can give some guidance on how of a complete implementation he would like Deno to have. 

As for the flexibility:
You can achieve the same with tokens but you need a token for each case, no? momentjs only supports ```4:45am``` and ```4:45AM```  with ```a``` and ```A``` accordingly.

I was looking also at the [formatToParts](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/formatToParts) method. There is an example of how to modify the parts like ```dayPeriod```.
```js
var dateString = formatter.formatToParts(date).map(({type, value}) => { 
  switch (type) {
    case 'dayPeriod': return `<b>${value}</b>`; 
    default : return value; 
  } 
}).reduce((string, part) => string + part);
```
Giving access to the parts would be more standardized and also more flexible for custom modifications. Then the default can be the same as native ```js```.

That could be achieved by a method like
```ts
const formatter = new Formatter("DD.MM.YYYY hh:mm", { hour12: true })
formatter.parseToParts("10.10.2020 09:15 PM") // output: { { type: "day", value: "10" }, { type: "literal", value: "." }, … }
```

**Comment by timreichen** [comment]
In addition to the comment above: I think Deno should not have a built-in set of tokens that is not really a wide standard. momentjs, luxon, dayjs all have different tokens.
A better solution would be to allow the user to extend or even create a new formatter.

Example:

1. Allow user to declare own format tokens ```js``` style
  - ```type``` is same as ```parts```
  - ```test```for parsing (there might be a better name for ```test```)
  - ```value``` one of predefined values (example: ``` "2-digits"```,  ```"numeric"``` etc.)
  
```ts
const definitions = [
  {
    type: "hour",
    test: /^hh/,
    value: "2-digits"
  },
  {
    type: "minute",
    test: /^mm/,
    value: "2-digits"
  },
  {
    type: "dayPeriod",
    format: /^a/,
    value: {
      am: "a.m.",
      pm: "p.m."
    }
  },
  …,
  {
    type: "literal",
    format: /^.+?/,
  }
]
```
2. Generate custom formatter
```ts

const formatter = new Formatter("hh:mm a", { hour12: true }, definitions)
```

3. Use 
```ts
formatter.parse("09:15 p.m.") // output: Date(…, 21, 15)

formatter.format(new Date(…, 21, 15)) // "09:15 p.m."
```

In my view that would be elegant and allow the best of both standardisation and flexibility.
The default formatter would align nicely with ```js``` standards but can also be shared and extended, so if somebody wants to make a momentjs-like set of tokens it would possible using the deno std only.

**Comment by cknight** [comment]
I like the flexibility, but perhaps not the verbosity of having to create a full set of definitions every time you wanted to parse or format a date. Or were you thinking of shipping a default set of definitions which could be overridden?  As a user, I would like to format or parse a date with a custom format in a line or two of code ideally.

**Comment by timreichen** [comment]
You are right, that might be overkill.
I implemented a basic symbols set according to [ICU](http://userguide.icu-project.org/formatparse/datetime) while trying to make it compatible with ```Intl.DateTimeFormat``` and created a
[pull request](https://github.com/denoland/deno/pull/6602). The symbols can be extended if needed. Feel free to review it.
