### ISSUE TITLE
btoa and base64 module

### ISSUE THREAD

**Issue by timonson** [denoland/deno#6094]
The correct **base64** encoding of `ß` is `w58=`.

```typescript
import { assertNotEquals } from "https://deno.land/std@v0.56.0/testing/asserts.ts";
assertNotEquals(btoa("ß"), "w58=");  // true
```

The German letter `ß` is one of the ASCII characters below 255 and inside the *latin1 range*, but it has two bytes. Therefore `btoa` doesn't throw an error and converts it to incorrect **base64**. I know that browsers do the same, because the btoa specification  is based on **latin1** (all one byte) instead of **ascii** (128-255 have two bytes) encoding. This is impractical in my opinion (I hope somebody can convince me of the opposite) and deno shouldn't do that, because it causes problems like the following one.

If you want to keep `btoa` like it is, then we must fix the `base64` module nevertheless because it uses `btoa` under the hood and converts to incorrect base64:

```typescript
import { assertNotEquals } from "https://deno.land/std@v0.56.0/testing/asserts.ts";
import { encode } from "https://deno.land/std@v0.56.0/encoding/base64.ts";
assertNotEquals(encode("ß"), encode(new TextEncoder().encode("ß").buffer));  // true
```

**Comment by kitsonk** [comment]
UTF16 strings (which is what JavaScript uses internally) need to be escaped properly encoded when they contain multibyte characters like `ß`.  There is `unescape` but that is Annex B and while it exists in Deno, not something we should really depend on (we already dropped some Annex B stuff).  The encode in Base64 should look something like this:

```js
btoa(encodeURIComponent(value)
  .replace(/%([0-9A-F]{2})/g, (_, p) => String.fromCharCode(`0x${p}`)));
```

The above returns the following for ß:

```
w58=
```

**Comment by timonson** [comment]
Exactly @kitsonk. For an alternative (maybe more performant?) look here: https://gist.github.com/enepomnyaschih/72c423f727d395eeaa09697058238727
