### ISSUE TITLE
How to read messages off unix connection?

### ISSUE THREAD

**Issue by filburt-turle** [denoland/deno#6095]
I've gone through the documentation as well as the code and I'm drawing blanks as to how to read messages from a Unix domain socket. I'm able to listen on a socket:

```
const listener = Deno.listen({ path: "/tmp/socket", transport: "unix" });
```

I know how to connect to that very socket with:

```
const client = Deno.connect({ path: "/tmp/socket", transport: "unix"});
```

but I'm drawing blanks as to how am I supposed to read the message stream from a unix socket. I know the unix socket stuff is flagged w/`--unstable`, but looking to make any kind of progress with being able to grab messages off the listener or client.

Any help would be appreciated, thanks in advance.

**Comment by teleclimber** [comment]
```
// use await on call to listen
const listener = await Deno.listen({ path: "/tmp/socket", transport: "unix" });

// then wait for an incoming connection:
const conn = await listener.accept();

// You can read a chunk like this:
const first_chunk = new Uint8Array(100);
await conn.read(first_chunk);

// but it's probably better to iterate over chunks like so:
for await (const chunk of Deno.iter(conn)) {
	// do something with chunk.
}
```

Hope that helps.

**Comment by bartlomieju** [comment]
Hope that above response was enough. Please use "Help" channel on [`Discord`](https://discord.gg/deno) for questions.
