### ISSUE TITLE
incorrect code reference link in failures message 

### ISSUE THREAD

**Issue by rjoydip** [denoland/deno#6096]
While getting failures message the line reference showing incorrect. It should use `#` instead of `:` 

e.g: [https://deno.land/std/testing/asserts.ts#138:11](https://deno.land/std/testing/asserts.ts#138:11)

![image](https://user-images.githubusercontent.com/15318294/83721977-c542a200-a659-11ea-9e86-926df9e75947.png)

**Comment by kitsonk** [comment]
I don't know if it is _incorrect_ in that that is the standard way of writing out code points, but you point out an interesting thing that we _could_/_should_ rewrite the URLs for remote modules into a fully "clickable" link, because as you point out, using the anchor does actually bring you directly to the line if you can click on the link in your terminal.

**Comment by nayeemrmn** [comment]
Maybe `https://deno.land/std/testing/asserts.ts:138:11` can redirect to `https://deno.land/std/testing/asserts.ts#138`?

**Comment by ry** [comment]
I think it would be better if we used URLs that deno.land could actually serve, it wouldn't be much different. I like @rjoydip's suggestion... Tho I'm not sure what to do about the column

**Comment by ry** [comment]
https://github.com/denoland/deno/blob/4b1638dccc601ff0282172c7e3ef0f1126a603ed/cli/js/error_stack.ts#L122
Basically just this line needs to be changed, but the tests need to be updated as well.

**Comment by mitch292** [comment]
Submitted a PR!

**Comment by bartlomieju** [comment]
Is there a prior art for using `#` to denote line number? 

AFAICR I've always seen `:` - can't deno_website be updated to handle colons?

**Comment by Caryyon** [comment]
@ry can this be closed as the corresponding issue is closed? New comer here looking for some good starter issues. Just want to make sure I’m following along.

**Comment by bartlomieju** [comment]
The PR was reverted in #6119. This issue still needs to be resolved, but it's not a "good first issue".
