### ISSUE TITLE
Naming consistency in std/testing

### ISSUE THREAD

**Issue by caspervonb** [denoland/deno#6097]
The assertions in _std/testing/asserts.ts_ are somewhat arbitrarily abbreviated.

* assertArrayContains
* assertStrContains
* assertNotEquals
* assertStrictEq

Proposing we use the long form consistently

* assertArrayContains
* assertStrContains **-> assertStringContains**
* assertNotEquals
* assertStrictEq -> **assertStrictEqual(s)**

This would be a breaking change so I'm soliciting feedback before doing a pull request.

**Comment by ry** [comment]
Ok - thanks
