### ISSUE TITLE
Return a tuple from std/flags parse

### ISSUE THREAD

**Issue by caspervonb** [denoland/deno#6098]
We have destructuring these days so returning a tuple is (IMHO) cleaner than using the `_` property. 

Example:

```typescript
import { parse } from "https://deno.land/std/flags/mod.ts";

const [ opts, args ] = parse(Deno.args);
console.log(opts, args);
```

This would be a breaking change so I'm soliciting feedback before doing a pull request.

**Comment by kitsonk** [comment]
I am 👎 for this, as mentioned, it would be a breaking change.  It aligns to other parsing APIs (e.g. https://github.com/substack/minimist) and is sort of what is expected in this space.  People are welcome to use other APIs.  They are not required to use `std`.

**Comment by caspervonb** [comment]
Well, it aligns with minimist because **it is** minimist.

But I don't feel strongly about it so, I'll leave it.
