### ISSUE TITLE
deno how to load ts file?

### ISSUE THREAD

**Issue by yodfz** [denoland/deno#6099]
In this?
```rust
// cli/main.rs
// line:536
let mut worker =
    MainWorker::create(global_state.clone(), main_module.clone())?;
```
I want to know when TS compiles。

**Comment by bartlomieju** [comment]
Here's entry point for compilation:

https://github.com/denoland/deno/blob/b8872cd303584b28c0d6250184e4a1205bf2ad9b/cli/global_state.rs#L110-L172

Please use [Discord](https://discord.gg/deno) for questions like this
