### ISSUE TITLE
Move std/testing/asserts.ts to std/assert/mod.ts

### ISSUE THREAD

**Issue by nayeemrmn** [denoland/deno#6104]
The `testing` prefix is more noisy than helpful. `std/testing/bench.ts` should be moved out as well.

- `std/testing/asserts.ts` -> `std/assert/mod.ts`
- `std/testing/diff.ts` -> `std/assert/_diff.ts`
- `std/testing/bench.ts` -> `std/bench/mod.ts`

**Comment by cknight** [comment]
I'm happy to adjust #5838 to accommodate the above once consensus is reached.

**Comment by nayeemrmn** [comment]
@cknight It would be better to open a new PR at that point.

**Comment by getspooky** [comment]
This change will cause some breaking changes???

**Comment by cknight** [comment]
@getspooky Yes, there would be breaking changes, but the `std` library is [not yet stable](https://deno.land/manual/runtime/stability).

**Comment by kitsonk** [comment]
I think we should really consider #5684 in conjunction with this, as it is really silly to have to pull in a `std` dependency to just write some functional code that uses `assert()` (with loads of colours and other dependencies)
