### ISSUE TITLE
Deno upgrade doesn't work on Windows 8.1 with powershell 4.0

### ISSUE THREAD

**Issue by niyarlatotep** [denoland/deno#6109]
By default Windows 8.1 has powershell  4.0 that doesn't have "Expand-Archive" powershell commandlet. Expand-Archive is used in Deno's upgrade method so it fails with error:
```
iex : The term 'Expand-Archive' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
+                                                     ~~~
    + CategoryInfo          : ObjectNotFound: (Expand-Archive:String) [Invoke-Expression], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException,Microsoft.PowerShell.Commands.InvokeExpressionCommand
``` 
It's already fixed in powershell installer, see:
https://github.com/denoland/deno_install/issues/146

```
Command::new("powershell.exe")
          .arg("-Command")
          .arg("Expand-Archive")
          .arg("-Path")
          .arg(&archive_path)
          .arg("-DestinationPath")
          .arg(&temp_dir)
          .spawn()?
          .wait()?
```
As workarround powershell installer could be used for upgrade too. 
It can also be solved by updating powershell version:
https://docs.microsoft.com/en-us/powershell/scripting/windows-powershell/install/installing-windows-powershell#upgrading-existing-windows-powershell

**Comment by gewoonwoutje** [comment]
https://hackernoon.com/polyfill-with-powershell-ad70c6cd7703
Could this be something of interest?

**Comment by Remote-version-git** [comment]
why don't you upgrade yourself system?

**Comment by piscisaureus** [comment]
@gewoonwoutje Thank you that is helpful
