### ISSUE TITLE
Handle BigInt in console

### ISSUE THREAD

**Issue by benjamingr** [denoland/deno#611]
Deno does not handle BigInts in the console at the moment.

Need to:

 - go to the `stringify` switch case in `console.ts` 
 - Add a case for `"bigint"` in the `typeof`
 - Add test to `tests/` directory.

Note this is blocked on TypeScript 3.1 since TypeScript [doesn't support BigInts](https://github.com/Microsoft/TypeScript/issues/15096) yet.

I just opened this here so we don't forget about it since I was surprised. It's also possible to deal with it directly before TypeScript 3.1.

**Comment by kyranet** [comment]
Update: TypeScript 3.2.1 is out and supports BigInts out of the box, and deno upgraded TS to that version in #1248, I'll try to make a PR soon to support this
