### ISSUE TITLE
Is DNS querying/resolution exposed?

### ISSUE THREAD

**Issue by TooTallNate** [denoland/deno#6110]
Sorry, this isn't an _issue_ per-say, but I'm looking to do DNS queries in deno, and not finding anything about it in the Runtime API docs nor the std. Google isn't helping either.

Am I overlooking somewhere? Or is DNS not yet exposed in deno? Thanks!

**Comment by lucacasonato** [comment]
It is not exposed at the moment. Probably something that should be in the future.
