### ISSUE TITLE
add assertNotThrows/Async to asserts.ts

### ISSUE THREAD

**Issue by shawnthehumble** [denoland/deno#6115]
I'd like to add a function to asserts.ts that asserts that an Error wasn't thrown. 

Many of the testing libs include some way to express that a function doesn't throw an Error.  While it is preferred to write positive tests for all the expected cases, there are times where testing that an Error isn't thrown is a good idea:

- When porting 1000's of lines of test code from other libs in the NPM land that use a lot of "not throws" logic
- When testing a defect fix/regression that threw an Error previously, and you just want to ensure that the Error isn't thrown anymore
- When Errors are expected but for a particular case, it is not

The code would look this:

```ts
assertNotThrows(somethingThatShouldntThrow());    // the case that it shouldn't throw

assertNotThrows(somethingThatMightThrow(), SomeError); // the case that SomeError is acceptable

assertNotThrows(somethingThatMightThrow(), SomeError, ignoreSubText); / the case that SomeError is accaptle, or if the error.message contains ignoreSubText

```

Some Error is optional, ignoreSubText is optional.  These express the case that if the error is thrown, and matches, then cancel the assertion.  Those are the counterpart to the ErrorClass, msgIncludes optional in `assertThrows` / `assertThrowsAsync`

Even if only `assertNotThrows( fn );` were added to asserts.ts, that would be great.  As many other testing libs have it and it's a very legitimate case to test that a potentially throwy operation didn't throw.

**Comment by ry** [comment]
I don't understand this request. When a test throws its considered broken. There's nothing more to do. For the second two cases, these seem very niche and something you can check yourself with a try-catch.

**Comment by RobDWaller** [comment]
@shawnthehumble I added this functionality to my assertion library... https://github.com/RobDWaller/explicitly#assert-not-throws

Might help. 👍

**Comment by bartlomieju** [comment]
> I don't understand this request. When a test throws its considered broken. There's nothing more to do. For the second two cases, these seem very niche and something you can check yourself with a try-catch.

I agree with @ry on this one. Closing as won't fix.
