### ISSUE TITLE
Sync read is not allowed on stdin

### ISSUE THREAD

**Issue by caspervonb** [denoland/deno#6121]
This minimal example
```typescript
const data = new Uint8Array(32);
const nread = Deno.stdin.readSync(data);

console.log("read %d bytes", nread);
```

Results in the following error consistently across Ubuntu, MacOS and Windows:

```shell
Compile file:///Users/caspervonb/deno-sync-read-not-allowed-on-stdin/test.ts
error: Uncaught TypeError: sync read not allowed on this resource  
    at unwrapResponse ($deno$/ops/dispatch_minimal.ts:63:11)
    at Object.sendSyncMinimal ($deno$/ops/dispatch_minimal.ts:118:10)
    at Object.readSync ($deno$/ops/io.ts:19:17)
    at Stdin.readSync ($deno$/files.ts:110:12)
    at file:///Users/caspervonb/deno-sync-read-not-allowed-on-stdin/test.ts:4:26
```

**Comment by caspervonb** [comment]
Skimming through ops/io.rs it's apparent why this is failing; I'll take this one on.

**Comment by ccheng** [comment]
Is this related to #4789 ?  Would be great if it gets fixed!  Thanks

**Comment by caspervonb** [comment]
> Is this related to #4789 ? Would be great if it gets fixed! Thanks

This is the same issue; looking at the implementation of readFromSync it silently swallows errors and returns N which is set to 0 at the start.
