### ISSUE TITLE
refactor: cli/doc/ should be a separate crate

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#6123]
Code that facilitates `deno doc` subcommand should be moved into a separate crate, ie. code living in `cli/doc` should be made into a separate crate (and most likely moved into its own repo).

Keep in mind that `deno doc` depends on `cli/swc_util.rs` and this functionality is needed for `deno_lint` as well, so preferably `swc_util` should be made into its own crate as well.

CC @mattd3v

**Comment by mattd3v** [comment]
The mentioned SWC issue may be useful for this.

**Comment by bartlomieju** [comment]
Update: I got this split done, but still punting a bit as I'm unsure where each crate should live (each in separate repo vs `deno_ast` in main repo)

**Comment by bartlomieju** [comment]
Working on it
