### ISSUE TITLE
Conn.write() order guaranteed?

### ISSUE THREAD

**Issue by aricart** [denoland/deno#6128]
Trying to debug a problem in my application where I am queueing a number of writes to a connection. The writes in a benchmark type situation initiate writes of 8K or a few bytes more. In some cases to allow more liveliness, a smaller write (6 bytes) is inserted which will trigger data coming back on the read channel of the socket.

The module is not waiting for a pending write to complete before a new write is possibly initiated. I am noticing that on the remote server, it seems to be possible for a smaller write to interleave with a bigger write - this makes it so that a partial write from the 8K buffer is followed by the 6-byte sentinel. 

Is the order of the write promises guaranteed in any way? Documentation doesn't make any notices of this not being supported, so perhaps incorrectly assuming that multiple writes are not processed in the order they were scheduled.

My code is not reusing buffers.

**Comment by aricart** [comment]
I should add, that if I write the same input to a file, the file doesn't exhibit the interleaving.

**Comment by ry** [comment]
The order of write is not guaranteed. This is a low-level call directly mapping to the [write(2)](https://www.man7.org/linux/man-pages/man2/write.2.html) syscall. This is a desirable behavior in datagram applications where one wants to "fire and forget".

**Comment by aricart** [comment]
Please document that. That also may indicate that Conn needs a `writeSync` since there's no buffering.
