### ISSUE TITLE
Install Node during setup.py

### ISSUE THREAD

**Issue by ry** [denoland/deno#613]
To have completely reproducible builds we aim to include all dependencies. 

Chromium already has node binaries available:
https://cs.chromium.org/chromium/src/DEPS?l=2246-2284&rcl=67e51fc88b67211901082b7ddbfc13f9b14a520b

Remove "Node" from list of deps in README.

Update tools/run_node.py to point to downloaded binaries

**Comment by mirkojotic** [comment]
Wanted to work on this, but I wasn't able to find the location of the node binary that should come with chromium ( found Python 2 but no node ). Any help would be appreciated.

**Comment by ry** [comment]
@mirkojotic See the link above to DEPS. It should be very similar to how we downloaded gn: https://github.com/denoland/deno/blob/c42e4ddbb7973bfb0c57a49ab6bf6dc432baad7e/tools/setup.py#L13
https://github.com/denoland/deno/blob/c42e4ddbb7973bfb0c57a49ab6bf6dc432baad7e/tools/third_party.py#L145-L168
Where did you find python2?

**Comment by mirkojotic** [comment]
@ry I've found python2 
`/third_party/depot_tools/.cipd_bin/.cipd/pkgs/0/d26d9e2eebe6f6525bfcc03b0ba750d97f78319e/vpython`

I've looked around quite a bit but I couldn't locate any node binaries. I've found the reference to it in DEPS and some python scripts related to it but no node :(

**Comment by ry** [comment]
stale - no longer dependent on node
