### ISSUE TITLE
Importing from Pika after upgrade to 1.0.5 doesn't work (for Ramda library)

### ISSUE THREAD

**Issue by mk0y** [denoland/deno#6133]
Let's see if this is just me or it's some bug.

I'm using Ramda and trying to play around with Deno with it.

So far I was importing it using [pika.dev](https://www.pika.dev/npm/ramda) like:
```js
// myscript.js
import * as R from "https://cdn.pika.dev/ramda@^0.27.0";
console.log(R);
```
Make sure you're using version 1.0.0:
```sh
deno upgrade --version 1.0.0
```
Then run it:
```sh
deno run --allow-net --reload myscript.js
```
Works fine and all modules are logged to console.

Then:
```sh
deno upgrade --version 1.0.5
deno run --allow-net --reload myscript.js
```
Now there's error message:
```sh
error: relative import path "Iteration/Iteration" not prefixed with / or ./ or ../ Imported from "https://cdn.pika.dev/-/ts-toolbelt@v6.9.4-4dgRR6t63EUp6VbVv2Im/dist=es2019,mode=types/out/index.d.ts"
```

Can someone confirm? Maybe it's also related to other libraries loaded from third parties.

**Comment by deepakshrma** [comment]
I also did not like it. Module resolver treat, a path without `.ts` as a directory I think resolver should be smart as TypeScript. Since most of the library has written in that way.

**Comment by bartlomieju** [comment]
Quick look into the types shows:
```ts
declare module 'Iteration/Iteration' {
    /**
    An entry of **`IterationMap`**
    * `[0]`: Prev (<-)
    * `[1]`: Next (->)
    * `[2]`: Current **`string`**
    * `[3]`: Current **`number`**
    * `[4]`: Current Negative **`string`**
    * `[5]`: Cumulated Previous **`keys`** (for `Min` & `Max`)
    * `[6]`: Sign (- / 0 / +)
    */
    export type Iteration = [string, string, string, number, string, string, '-' | '0' | '+'];
}
declare module 'Misc/Iteration/Map' {
    import { Iteration } from "Iteration/Iteration";
    /**
    Describes a map of number relationships
    */
    export type Map = {
        [k: string]: Iteration;
        [k: number]: Iteration;
        '0': Iteration;
        'keys': Iteration;
        '__': ['__', '__', string, number, string, string, '-' | '0' | '+'];
    };
}
```

The situation where one TS module imports something from other module in the same file is not handled in `ModuleGraphLoader` currently.

CC @kitsonk could you take a look at this issue? Should imports inside `declare module` always resolve to modules in the same file?

**Comment by frankhale** [comment]
I'm wondering if the issue I created for lodash-es is related to what's going on here? https://github.com/denoland/deno/issues/6277

**Comment by bartlomieju** [comment]
@kitsonk could you take a look at this issue?

**Comment by kitsonk** [comment]
This is unactionable now, as it Pika CDN is now skypack.dev and no longer appears to serve up `X-TypeScript-Types`.  Manually trying to use `https://unpkg.com/@types/ramda@0.27.32/index.d.ts` with `@deno-types` doesn't work because the types are incompatible with Deno.

The original does work now, but just isn't strongly typed:

```js
import * as R from "https://cdn.skypack.dev/ramda@^0.27.0";
console.log(R);
```

**Comment by lucacasonato** [comment]
@kitsonk Skypack does serve the types of you append `?dts` to the import URL.

**Comment by kitsonk** [comment]
Ok, I rested with:

```ts
import * as R from "https://cdn.skypack.dev/ramda@^0.27.0?dts";
console.log(R);
```

And am getting errors the seem "legitimate" to how the package is configured on skypack.  In particular, one of the type dependencies is returning this:

```js
/*
 * [Package Error] "ts-toolbelt" no dependency version info found. (Imported by "ramda").
 *
 * The package "ramda" depends on "ts-toolbelt" as a dependency, 
 * but did not list any dependency version info in its package manifest. 
 * Without this information, the CDN is unable to properly resolve this import.
 * 
 * How to fix:
 *   - Let the "ramda" package author know that "ts-toolbelt" needs to be included in their package.json manifest.
 *   - Use https://pika.dev/ to find a web-friendly alternative to find another package.
 */

throw new Error("[Package Error] \"ts-toolbelt\" no dependency version info found. (Imported by \"ramda\").");
export default null;
```

But it seems that Deno is parsing this correctly now.
