### ISSUE TITLE
How to handle aborted requests with `std/http/server`

### ISSUE THREAD

**Issue by patrickkunka** [denoland/deno#6149]
It is possible for the std http server to handle an incoming request being aborted?

In Node, we have the `aborted` event:
```js
request.on('aborted', () => {
    // .. perform abort logic
});
```

I see that deno has an `AbortSignal` implementation, but I can't see it exposed anywhere on the `ServerRequest` object.

Thanks!

**Comment by ry** [comment]
Yes. The incoming request body should get an EOF if the upload was canceled. I guess response raises a ConnReset if the connection was terminated - but I'm not sure. AbortSignal is unrelated.
