### ISSUE TITLE
Cross platform install script

### ISSUE THREAD

**Issue by ry** [denoland/deno#615]
We now have fully automatic releases on mac, linux, and windows being published at https://github.com/denoland/deno/releases . We would like to make it easier for people to install or upgrade to the latest release.

Rust has this very convenient command to install:
```
curl https://sh.rustup.rs -sSf | sh
```
We would like to have a similar version of this. I believe we can use a modified version of [their script](https://gist.github.com/ry/a47dd53ddf660dda040b68a02044f44d). 

The script should figure out which platform its being run on, download the latest Deno binary for that platform, uncompress it, make it executable, and install it somewhere sane.

The script should **as simple as possible** to start.

**Comment by acconrad** [comment]
@ry should this be closed now that #639 is merged?

**Comment by ry** [comment]
@acconrad Yah - thanks. 

https://github.com/denoland/deno_install
