### ISSUE TITLE
'this' value is wrong

### ISSUE THREAD

**Issue by chenguzhen87** [denoland/deno#6150]
execute typescript file in deno
deno: 1.0.1
```` js
console.log(`this:${this}`); // undefined
````
![image](https://user-images.githubusercontent.com/28331609/83947517-14e7c000-a84a-11ea-9109-3c6414c8e354.png)

**Comment by nayeemrmn** [comment]
`this` is supposed to be undefined in ES modules. Try in browsers or `node index.mjs`.

**Comment by ry** [comment]
use globalThis

**Comment by chenguzhen87** [comment]
but in here
![image](https://user-images.githubusercontent.com/28331609/83947778-bcb1bd80-a84b-11ea-9601-6f9a2cce077d.png)

**Comment by nayeemrmn** [comment]
@chenguzhen87 The REPL is in a traditional script context, not an ES module. We'd love the semantics to be more similar but ES modules are "closed" and therefore don't accommodate REPLs at the moment.

**Comment by chenguzhen87** [comment]
thanks your reply
