### ISSUE TITLE
WebAssembly.instantiateStreaming is undefined

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#6154]
```
> deno
Deno 1.0.5
exit using ctrl+d or close()
> typeof WebAssembly.instantiate
function
> typeof WebAssembly.instantiateStreaming
undefined
```

https://github.com/denoland/deno/blob/8b037364ac269b7887f3420fefb38be8d0693e9e/cli/js/lib.deno.shared_globals.d.ts#L48

**Comment by caspervonb** [comment]
Same goes for `WebAssembly.compileStreaming`.

**Comment by ry** [comment]
Using `--v8-flags=--wasm-test-streaming` makes these available. Tho I'm confused as to why this isn't enabled by default.

This could easily be added to the default configuration by adjusting this:
https://github.com/denoland/deno/blob/f247423f206ea5c3ca07254413a1ff11709a2ada/core/core_isolate.rs#L160-L168

**Comment by caspervonb** [comment]
Portable code still has to check for the existence of `WebAssembly.instantiateStreaming` and fallback to `WebAssembly.instantiate` which all portable toolchains and loaders in the wild are currently doing.

Safari has no intent to implement.

> Tho I'm confused as to why this isn't enabled by default.

As far as I know `WebAssembly.compileStreaming` and `WebAssembly.instantiateStreaming` are vendor extensions, originally from Google then adopted by Mozilla.

[The webidl definition is the following:](https://webassembly.github.io/spec/js-api/#webassembly-namespace)
 ```webidl
[Exposed=(Window,Worker,Worklet)]
namespace WebAssembly {
    boolean validate(BufferSource bytes);
    Promise<Module> compile(BufferSource bytes);

    Promise<WebAssemblyInstantiatedSource> instantiate(
        BufferSource bytes, optional object importObject);

    Promise<Instance> instantiate(
        Module moduleObject, optional object importObject);
};
```

**Comment by dsherret** [comment]
@caspervonb looks like the streaming API is defined here: https://webassembly.github.io/spec/web-api/index.html#streaming-modules

> So this is technically not a bug, but a feature request.

I think it's a bug because it exists in the declaration file, but not at runtime.

**Comment by caspervonb** [comment]
Ah okay; it's defined as a web-api and not a js-api; which would also explain why it isn't enabled in V8 by default.
