### ISSUE TITLE
support bundling dynamic import with variable pointing to string

### ISSUE THREAD

**Issue by horihiro** [denoland/deno#6156]
I'm trying to bundle all files including imported dynamically

file structure and each files are following.

structure:
```
.
└── src
    ├── children
    │   └── child.ts
    ├── import-map.json
    └── parent_dynamic.ts
```

`src/parent_dynamic.ts`:
```typescript
const path = './children/child.ts';
const child = (await import(path)).default;
console.log(child.name);
```

`src/children/child.ts`:
```typescript
export default {
  name: "VALUE2"
}
```

`src/import-map.json`:
```json
{
  "imports": {
    "children/child.ts": "./children/child.ts"
  }
}
```

In this situation with following command, it seems that `src/children/child.ts` is not bundled.

```sh
$ deno bundle -L debug --unstable --importmap src/import-map.json src/parent_dynamic.ts
```

By the way, after editing `src/parent_dynamic.ts` as following, `src/children/child.ts` is bundled
even though not using import map.

`src/parent_dynamic.ts`:
```typescript
const child = (await import('./children/child.ts')).default;
console.log(child.name);
```

Could you please let me know which my mistake is?
Or is this unsupported?

**Comment by bartlomieju** [comment]
@horihiro bundling dynamic import with variable (`await import(path)`) is not supported, but bundling dynamic import with static specifier (`await import("./children/child.ts")`) is supported.

If `tsc` can bundle dynamic imports with variable then we should add it as well.

**Comment by horihiro** [comment]
Thanks @bardiarastin ,
I understand that this depends on `tsc`, not `deno`

I appreciate your explanation.

**Comment by bartlomieju** [comment]
> I understand that this depends on `tsc`, not `deno`
> I appreciate your explanation.

It does depend on Deno, files are analyzed using custom parser instead of `tsc`. What I meant is that if `tsc` can bundle such dynamic imports we should strive to have the same functionality.

CC @kitsonk

**Comment by kitsonk** [comment]
The TypeScript compiler resolves static strings for type assessment.  This is the "escape hatch" we talked about @bartlomieju in that the compiler always sees more things than any of the other static analysis does.

Outside of that, dynamic imports that can be statically resolved are included, those that cannot be statically determined cannot be included in the bundle and are resolved at runtime.

**Comment by kitsonk** [comment]
We no longer bundle dynamic imports.  If we allowed them to be bundled, in the future, it is unlikely that this issue would specifically apply.  So there is no logical action we can take with this now.
