### ISSUE TITLE
deno install to support file:///

### ISSUE THREAD

**Issue by reggi** [denoland/deno#6167]
When I try to install a path that is prefixed by `file:///` (the output from `import.meta.url` when the file is a local file) it will have an unexpected result in the install file generated.

Here's an example of what I ran:

```bash
deno install -f --allow-read \
         --allow-write \
         --allow-run \
         --unstable \
         file:///Users/thomas/Desktop/projects/deno-media-library/media-library.ts
```

Here's what it saved:

```bash
#!/bin/sh
# generated by deno install
deno "run" "--allow-read" "--allow-write" "--allow-run" "--unstable" "file:///Users/thomas/Desktop/projects/deno-media-library/file:/Users/thomas/Desktop/projects/deno-media-library/media-library.ts" "$@"
```

I ran into a similar issue when using the path module and `resolving` the output from `import.meta.url`.

```ts
import * as path from "https://deno.land/std/path/mod.ts";
console.log(path.resolve(import.meta.url))
```

```bash
$> deno run --allow-read ./example.ts
Compile file:///Users/thomas/Desktop/projects/deno-media-library/example.ts
/Users/thomas/Desktop/projects/deno-media-library/file:/Users/thomas/Desktop/projects/deno-media-library/example.ts
```

deno 1.0.5
v8 8.4.300
typescript 3.9.2

**Comment by bartlomieju** [comment]
This problem should be fixed by https://github.com/denoland/deno/pull/5276

**Comment by sant123** [comment]
I'm trying to install a local module but I'm getting the following error: 

![image](https://user-images.githubusercontent.com/7959437/97766541-cb438e80-1ae4-11eb-957b-6e6f84862e83.png)

No such file or directory (os error 2)

Just in case I have set the following environment variable:

`export DENO_INSTALL_ROOT="$HOME/.deno"`

Anyone has an idea of what's going on? Also I have tried with the `file://`protocol

![image](https://user-images.githubusercontent.com/7959437/97766648-5886e300-1ae5-11eb-96e6-bcb471bb121b.png)

Thanks.

**Comment by lino-levan** [comment]
https://github.com/denoland/deno/pull/5276 got merged a while ago... I'm pretty sure this issue is resolved.

**Comment by crowlKats** [comment]
This has been fixed, so closing
