### ISSUE TITLE
Mutual TLS authentication

### ISSUE THREAD

**Issue by jdiamond** [denoland/deno#6170]
`ConnectTlsOptions` (passed in to `connectTls`) does not allow a client certificate and key options.

`ListenTlsOptions` (passed in to `listenTls`) does not allow a flag to request certificates from clients or a certificate authority option to validate those certificates.

`ConnectTlsOptions` does have a `certFile` option. IMO, this is poorly named as it doesn't distinguish between the CA certificate and the client certificate. Most other APIs would call that option something with "CA" in the name. In Node.js, it's called `ca` and `cert` is for the client certificate. In curl, it's called `--cacert` and `--cert` is for the client certificate.

`certFile` does make sense in `ListenTlsOptions`, though. 

However, I don't think these options should be files as they could be loaded from a database or API (Consul, etcd, AWS Parameter Store, etc). See also #5810.

I propose deprecating `certFile` and adding the following options to `ConnectTlsOptions`:

- ca (to validate certificates from server, replaces `certFile`)
- cert (to present to server)
- key (to authenticate with server)

In `ListenTlsOptions`, deprecate `certFile` and `keyFile` and add the following options:

- cert (to present to clients, replaces `certFile`)
- key (to authenticate with clients, replaces `keyFile`)
- requestCert (to request certificates from clients)
- ca (to validate certificates from clients)

**Comment by Spoonbender** [comment]
Borrowing from other implementations, i suggest we also consider:
- Custom client certificate validation callback
- Option to select either chain trust (certificate is trusted if one of the issuers in the chain is trusted. the default) or peer trust (certificate is trusted only if it was individually added to the cert store)
- Cert store selection

**Comment by justinmchase** [comment]
Related To https://github.com/denoland/deno/issues/10516

**Comment by psi-4ward** [comment]
anything new with
* requestCert (to request certificates from clients)
* ca (to validate certificates from clients)

we would like to provide an mTLS service with deno

**Comment by psi-4ward** [comment]
:cry:

**Comment by tjconcept** [comment]
I too, would like to do mTLS between Deno (and currently Node.js) services, but is missing:

- A way to inspect the peer certificate
- A way to disable checking a server certificate against the hostname

**Comment by herenickname** [comment]
Any updates?

**Comment by lucacasonato** [comment]
Deno has support mTLS in `Deno.connectTls` and `Deno.createHttpClient` for a while now - just forgot to close this issue!

https://docs.deno.com/api/deno/~/Deno.connectTls#function_connectTls_1

**Comment by lucacasonato** [comment]
Please file separate issues for these.

**Comment by tjconcept** [comment]
Here's one for skipping the hostname check: #26190.
