### ISSUE TITLE
Build from source guidelines required

### ISSUE THREAD

**Issue by vishal-vvr** [denoland/deno#6172]
Hi,
I am planning to package denojs for Fedora, could please include steps/instructions to build from the source in the documentation.

Thanks :)

**Comment by Yamboy1** [comment]
I don't know especially much about fedora, but i would take a look at how the aur package does it: https://aur.archlinux.org/packages/deno

**Comment by kt3k** [comment]
See https://deno.land/manual/contributing/building_from_source

**Comment by caspervonb** [comment]
> I am planning to package **denojs** for Fedora

In case you're submitting the package upstream, the package name should probably be just *deno* unless there's a conflict.

**Comment by vishal-vvr** [comment]
> See https://deno.land/manual/contributing/building_from_source

This helps, Thanks :)
