### ISSUE TITLE
Unable to add dynamic import to lock file

### ISSUE THREAD

**Issue by cknight** [denoland/deno#6183]
My understanding is that dynamic imports should be able to be added to lock files.  However, this does not seem to work (or I am doing it incorrectly).  Example:

**mod.ts**
```
const child = (await import('https://deno.land/std@v0.50.0/testing/asserts.ts'));
console.log(child);
```
When running:
```
deno run --allow-net --lock=lock.json --lock-write mod.ts
```
I get the following lock.json produced:
```
{}
```
I've also tried `deno cache --reload --lock=lock.json --lock-write mod.ts` and end up with the same result.  Other things I've tried include adding another normal import (which gets properly cached and locked) and removing the `child` assignment, but the dynamic import still refuses show up in the lock file.

**Comment by bartlomieju** [comment]
Ref #5231
