### ISSUE TITLE
Deno

### ISSUE THREAD

**Issue by inshalayaz** [denoland/deno#6184]
I wrote an article on Deno contributing to the community maybe you guys can check [What is Deno?](https://frogtok.com/what-is-deno-deno-vs-node-2020/)

**Comment by bartlomieju** [comment]
Thanks, but repo is meant for bug reports and discussion about new features. Make sure to post it in ["Showcase" channel on Discord](https://discord.com/channels/684898665143206084/712010403302866974)

**Comment by inshalayaz** [comment]
Thanks for the guidance what is the channel name
