### ISSUE TITLE
Useless call in ensure_symlink.ts ?

### ISSUE THREAD

**Issue by franckLdx** [denoland/deno#6187]
In ensureSymlink function (std/fs/ensure_symlink.ts), I think that the statement ensureDirSync(path.dirname(dest)) (line 31) is useless as the previous statement is await ensureDir(path.dirname(dest));: both does the same in sync/async way.

**Comment by caspervonb** [comment]
Looks like a ghost left over from some copy paste action.

Good catch 💯

**Comment by bartlomieju** [comment]
Done in #6189
