### ISSUE TITLE
DENO command not found

### ISSUE THREAD

**Issue by damiantoczek** [denoland/deno#6199]
Hello,
after installing deno and trying to execute the test hello world file, there is a "Deno: deno command not found" error showing.

After installation it says to add two paths into $HOME/.bash_profile
`export DENO_INSTALL="/home/damian/.deno"
export PATH="$DENO_INSTALL/bin:$PATH"`

Could also someone add the info to run `source ~/.bash_profile` after saving the .bash_profile?
Would do it myself but don't know where to add this.

(Many people have searched for this issue on google, so might be a good idea to add this tiny info)

**Comment by humancalico** [comment]
Hey @damiantoczek. The scripts to install deno are in [deno_install](https://github.com/denoland/deno_install). What you are looking for is [here](https://github.com/denoland/deno_install/blob/63a4971358754db7ff2a68a3079cc99b15ba5013/install.sh#L61)

**Comment by jhonnattan123** [comment]
I had the same problem, in the end we were able to solve it and and has many screenshots

https://github.com/denoland/deno/issues/5220https://github.com/denoland/deno/issues/5220

**Comment by ry** [comment]
The executable needs to be in your path.
