### ISSUE TITLE
 "Cannot find name 'Deno'."

### ISSUE THREAD

**Issue by pradipmudi** [denoland/deno#6201]
denoland extension is installed in the VSCode IDE, but it still doesn't works.
![deno error](https://user-images.githubusercontent.com/6489613/84145237-24981c00-aa77-11ea-9a5e-7ffbaac4cc4e.png)

**Comment by David-Else** [comment]
https://github.com/denoland/vscode_deno/issues/80#issuecomment-640676940

**Comment by nayeemrmn** [comment]
Duplicate of https://github.com/denoland/vscode_deno/issues/80, wrong repo.
