### ISSUE TITLE
Cannot resolve module when flatbuffers type is in constructor.

### ISSUE THREAD

**Issue by Aaronepower** [denoland/deno#621]
if you place the following code in `js/os.ts` and run `./tools/test.py` the below error will be outputed. This doesn't appear to be the case for functions.
```typescript
export class Foo {
    constructor(msg: fbs.ReadFileSyncRes) {}
}
```

```
Test FAIL compilerRun_permW0N0
Error: Cannot resolve module "gen/msg_generated" from "$asset$/os.d.ts".
  Invalid source code or file name.
    at throwResolutionError (deno/js/compiler.ts:124:9)
    at DenoCompiler.resolveModule (deno/js/compiler.ts:525:14)
    at DenoCompiler.resolveModuleName (deno/js/compiler.ts:550:33)
    at moduleNames.map.name (deno/js/compiler.ts:679:33)
    at Array.map (<anonymous>)
    at DenoCompiler.resolveModuleNames (deno/js/compiler.ts:670:24)
    at Object.compilerHost.resolveModuleNames (deno/third_party/node_modules/typescript/lib/typescript.js:111649:117)
    at resolveModuleNamesWorker (deno/third_party/node_modules/typescript/lib/typescript.js:82561:106)
    at resolveModuleNamesReusingOldState (deno/third_party/node_modules/typescript/lib/typescript.js:82768:24)
    at processImportedModules (deno/third_party/node_modules/typescript/lib/typescript.js:84005:35)

DONE. Test passed: 3, failed: 1
Error: There were 1 test failures.
    at Object.setTimeout [as cb ] (file:///Users/aep/src/rust/deno/js/testing/testing.ts:83:13)
    at onMessage (deno/js/timers.ts:32:9)
    at onMessage$1 (deno/js/main.ts:37:7)
```

**Comment by ry** [comment]
Yeah - we've been trying to keep `msg_generated.ts` out of the public type declarations of Deno because it's quite big and not very userfriendly. When you export a class that references types in `msg_generated.ts` it wants to pull them in. 
It is caused by this part here:
https://github.com/denoland/deno/blob/4cadf6e6096de374c67d18e26422c5d452539b31/js/assets.ts#L106-L107

I *think* this is the behavior we want and that this is not a bug. Can you modify your exported types to not reference `msg_generated.ts` types?

cc @kitsonk

**Comment by Aaronepower** [comment]
@ry Well the problem I ran into was in #622 with the `Metadata` class I wanted essentially for it to be only instantiated by a message. Is there a preferred way to construct classes from flatbuffer messages?

**Comment by kitsonk** [comment]
My opinion is we need to try not to leak `msg_generated` types outside like that... We should create some sort of "public" abstraction type which we export from `os.ts`... It seems a bit arbitrary, but really no one will benefit from closely coupling to `msg_generated`.  So yeah, it is "working as designed" at the moment in my opinion.

**Comment by kitsonk** [comment]
I also don't think we would want to leak the constructor for something like that outside of `os`.  No one outside of `os.ts` should be able to construct a `Foo`, right?  What happens if you don't export `Metadata`?  We only need the structure exported.

**Comment by kitsonk** [comment]
@ry I also think we need to setup some guidelines as well...  There is no real "value" in having a `class` for things like this and my opinion returning an object literal is that is more straight forward in this case, just like:

https://github.com/denoland/deno/blob/a63d794c7fa6fe4a1178be0f2e8c9389da9435ca/js/os.ts#L51-L57

With the "cross cutting" type in `types.d.ts`.

**Comment by Aaronepower** [comment]
@kitsonk It is definitely not the intention to leak the message type, that just comes from me not knowing how to have a constructor that is only available in the file/module, while still having the type public available.

I think it's different from `codeFetch` as `codeFetch` wouldn't be part of the public API, where as `Metadata` is, people should be able to use it as a strong type. Especially as I mentioned in #622 I see this class expanding to also contain platform specific extensions, so users could easily build high level abstractions around `Metadata` for their specific platform.

**Comment by kitsonk** [comment]
Actually it looks like this would work as well:

```ts
export class Foo {
  /* @internal */
  constructor(private _msg: fbs. ReadFileSyncRes) {
    console.log(this._msg);
  }
}
```

It would emit:

```ts
export declare class Foo {
    private _msg;
}
```

**Comment by Aaronepower** [comment]
With #622 merged now I think we can safely close this
