### ISSUE TITLE
Unable to clone git on Windows

### ISSUE THREAD

**Issue by hazae41** [denoland/deno#6211]
When trying to clone deno on Windows, "filename too long" is thrown on some files.

    git config --global core.symlinks true
    git clone --recurse-submodules https://github.com/denoland/deno.git

> Cloning into 'deno'...
> remote: Enumerating objects: 39, done.
> remote: Counting objects: 100% (39/39), done.
> remote: Compressing objects: 100% (36/36), done.
> remote: Total 32892 (delta 8), reused 9 (delta 1), pack-reused 32853
> Receiving objects: 100% (32892/32892), 15.96 MiB | 9.28 MiB/s, done.
> Resolving deltas: 100% (24533/24533), done.
> Submodule 'typescript' (https://github.com/microsoft/TypeScript.git) registered for path 'deno_typescript/typescript'
> Submodule 'deno_third_party' (https://github.com/denoland/deno_third_party.git) registered for path 'third_party'
> Cloning into 'C:/Users/#####/Documents/deno/deno_typescript/typescript'...
> remote: Enumerating objects: 185654, done.
> remote: Counting objects: 100% (185654/185654), done.
> remote: Compressing objects: 100% (93423/93423), done.
> remote: Total 185654 (delta 111984), reused 151830 (delta 87499), pack-reused 0
> Receiving objects: 100% (185654/185654), 223.35 MiB | 7.82 MiB/s, done.
> Resolving deltas: 100% (111984/111984), done.
> Checking connectivity: 185654, done.
> Cloning into 'C:/Users/#####/Documents/deno/third_party'...
> remote: Enumerating objects: 14, done.
> remote: Counting objects: 100% (14/14), done.
> remote: Compressing objects: 100% (11/11), done.
> remote: Total 111166 (delta 5), reused 5 (delta 3), pack-reused 111152
> Receiving objects: 100% (111166/111166), 275.51 MiB | 10.11 MiB/s, done.
> Resolving deltas: 100% (54972/54972), done.
> error: unable to create file tests/baselines/reference/tscWatch/emitAndErrorUpdates/assumeChangesOnlyAffectDirectDependencies/updates-errors-when-file-transitively-exported-file-changes/when-there-are-no-circular-import-and-exports.js: Filename too long
> error: unable to create file tests/baselines/reference/tscWatch/emitAndErrorUpdates/assumeChangesOnlyAffectDirectDependenciesAndD/updates-errors-when-file-transitively-exported-file-changes/when-there-are-circular-import-and-exports.js: Filename too long
> error: unable to create file tests/baselines/reference/tscWatch/emitAndErrorUpdates/assumeChangesOnlyAffectDirectDependenciesAndD/updates-errors-when-file-transitively-exported-file-changes/when-there-are-no-circular-import-and-exports.js: Filename too long
> Submodule path 'third_party': checked out '9ad53352a9bc7cd179d9e06663a097352514d389'
> Unable to checkout '551f0dd9a1b57ecd527a665b0af7fc98cd107af6' in submodule path 'deno_typescript/typescript'

**Comment by MarkTiedemann** [comment]
Well, you hit the `MAX_PATH` limit which is 260 characters by default.

```js
> "deno/deno_typescript/typescript/tests/baselines/reference/tscWatch/emitAndErrorUpdates/assumeChangesOnlyAffectDirectDependencies/updates-errors-when-file-transitively-exported-file-changes/when-there-are-no-circular-import-and-exports.js".length
237
> "C:\Users\\Document".length
16
> 260 - 237 - 16
7
```

So I assume your Windows user name is longer than 7 characters.

Apart from cloning into a different folder or renaming your user, there's a few other options that you have: https://www.howtogeek.com/266621/how-to-make-windows-10-accept-file-paths-over-260-characters/

Hope this helps.

**Comment by hazae41** [comment]
Thanks for the workaround, but I may not be the only one facing this error. Maybe we could rename those files into something shorter?

**Comment by MarkTiedemann** [comment]
Those files are located in the git submodule for TypeScript: https://github.com/microsoft/TypeScript You'd have to ask the TypeScript team to do that.

**Comment by bartlomieju** [comment]
> Thanks for the workaround, but I may not be the only one facing this error. Maybe we could rename those files into something shorter?

As pointed by @MarkTiedemann not really possible as it's TypeScript source code. Closing as not actionable.
