### ISSUE TITLE
Switch to hard tabs

### ISSUE THREAD

**Issue by caspervonb** [denoland/deno#6224]
Currently `deno fmt` uses 2 spaces for indentation; I propose we switch to using hard tabs.

Tabs allow people in the same codebase to select their indentation widths across every tool including GitHub as even browsers support _tab-width_ in stylesheets these days.

Now this isn't just "a preference", a preference would be what brace style to use but a narrow indentation width is an accessibility issue.

You can still easily parse the opening brace after a statement if you put them on the same line or the next one making it a stylistic preference but narrow whitespace tends to just disappear and blend in with the line when you have less than perfect sight.

[This thread from Reddit comes to mind on the topic of accessibility of tabs](https://www.reddit.com/r/javascript/comments/c8drjo/nobody_talks_about_the_real_reason_to_use_tabs/)

Lastly, please refrain from getting into the X is better than Y debates, I used to think X was better than Y too but then I had to get glasses 😉

**Comment by ChrisBrownie55** [comment]
I agree with @caspervonb allowing the use of tabs is most definitely an accessibility issue. Tabs are inherently just characters that represent indentation. Due to that, any developer can configure their editor to be able to use any length they need to be able to work more efficiently.

And no, I have never seen an editor be able to represent a 2-space indentation as anything other than 2 spaces. Currently, it would have to change the number of spaces, which `deno fmt` would just change back, @nayeemrmn.

I think to say that 2-spaces is the JavaScript convention, @ry, is to force your opinion and inability to accept that tabs may help people with disabilities onto the rest of the community. [Tabs can help lots of people.][1]

Even if you prefer to stick to a [so-called "convention" for indentation in the JavaScript community][2], saying no to tabs altogether is reductive. Tabs may not be as preferable to some — however, to other people, it could mean being able to use the built-in formatter for Deno at all.

[1]: https://twitter.com/tjcrowder/status/1327965378052575232?s=20
[2]: https://twitter.com/JeremiahLee/status/1327742215234449409?s=20

**Comment by ChrisBrownie55** [comment]
I strongly believe the Deno team should consider providing a switch with the Deno formatter that allows for the use of tabs.

```bash
# Here are some options
deno fmt -t
deno fmt --tabs
deno fmt --use-tabs
deno fmt --with-tabs

# Or perhaps Deno could take a more simplistic approach of using existing indentation
deno fmt -d
deno fmt --detect
deno fmt --detect-indentation
```

Those were just some ideas, feel free to come up with your own ideas if you plan to implement this. Do, please, reopen this issue though. I don't believe there needs to be a total switch over just support for those who need hard tabs.

**Comment by nayeemrmn** [comment]
> And no, I have never seen an editor be able to represent a 2-space indentation as anything other than 2 spaces. Currently, it would have to change the number of spaces, which `deno fmt` would just change back, @nayeemrmn.

I'm not saying it exists, I'm wondering why people don't request this feature from editors. It would solve the issue for a lot more people at the same time while allowing individual projects to stick to their preference. It would be like changing font size.

**Comment by ChrisBrownie55** [comment]
@nayeemrmn That sounds good but at the same time, that seems quite difficult. The editor would have to change the size only of spaces that it recognizes as indentation. If it changes the style of any other spaces then the code will look very weird and probably make it harder to work with.

Once you look at this idea from the perspective of writing the code to style indentation spaces separately, then it makes sense why they only support adjusting the width of `\t` hard tabs. It's easy and `\t` tabs were designed to be used this way.

**Comment by nayeemrmn** [comment]
> That sounds good but at the same time, that seems quite difficult. The editor would have to change the size only of spaces that it recognizes as indentation. If it changes the style of any other spaces then the code will look very weird and probably make it harder to work with.

Again, it's an extremely simple problem. Editors already handle indent spaces differently.

**Comment by ChrisBrownie55** [comment]
@nayeemrmn
https://www.reddit.com/r/vscode/comments/da5dtj/an_extension_to_view_files_with_my_own/

That is an example of someone attempting to create a plugin in VS Code. Recognizing indentation isn't the hard part, it's changing the width of the indentation only visually that's hard. I apologize for wording it poorly.

Even with their attempt to create a plugin for this, their solution is terribly inflexible.

**Comment by dsherret** [comment]
It seems there exists a VS code extension for changing the visual width of indentation spaces: https://marketplace.visualstudio.com/items?itemName=kylepaulsen.stretchy-spaces

**Comment by ChrisBrownie55** [comment]
@dsherret I'm assuming there are a lot of places that don't have this functionality available to them, including the web. On the web, if you want to change the size of hard `\t` tab indentation, you can set the [`tab-size` CSS property](https://developer.mozilla.org/en-US/docs/Web/CSS/tab-size) and you're good to go. If you were using soft tabs, you would need to write your own syntax highlighting library/plugin specifically for giving only soft indent spaces an `"indent"` class.

## How I view the accessibility of it

* Soft tabs (spaces) can be made **accessible by implementing complex features** across every tool that displays or edits code but this seems to be left up to plugin developers a lot and **almost, if not never, included by default in an application**.
* Hard tabs (`\t`) are **generally accessible by default** and if they aren't, it is often a very simple process to add a feature that changes the width of the tab character anyway.

I am glad that someone made the `stretchy-spaces` plugin but unless we can remake that plugin for every editor and implement it into every online syntax highlighter as a plugin then we're still ignoring the inaccessibility of soft tabs in comparison to hard tabs.

### Solution

I still support the solution of adding a new switch for using hard tabs.

```bash
# Boolean flag
deno fmt -t
deno fmt --hard-tabs

# One of two values in: enum { soft, hard }
# This could allow future support for an auto mode `-t auto`
deno fmt -t hard
deno fmt --tabs=hard
```

**Comment by kitsonk** [comment]
We won't switch the Deno code or the `std` lib code away from two-spaces to hard-tabs.

We recognise though that formatting via `deno fmt` has strong personal, team, and accessibility concerns.  @bartlomieju and I have a goal of addressing #3179 during the next quarter, which would address the `deno fmt` issue.  At the moment we are leaning towards giving the same options that are available with `prettier`.

**Comment by ChrisBrownie55** [comment]
I'm not saying that the default has any need to change. A lot of people like 2 space tabs and it's convenient for a lot of neurotypical and able-bodied developers.

My solution was simply to add a flag that allows hard tabs as an additional option. Also, I see you want to stick to the same options/features as Prettier. **[Prettier also has the ability to use hard tabs.](https://prettier.io/docs/en/options.html#tabs)** It supports the use of hard tabs via `--use-tabs` in the CLI and the `useTabs` property in the configuration file.

**Comment by kitsonk** [comment]
I understand what you are saying.  I was just making it clear that we wouldn't be implementing what this issue originally requested, but implementing via a unified configuration file (and unlikely to implement via adding additional command line flags, but we might).

**Comment by Malix-off** [comment]
Furthermore, tabs are more semantically correct

**Comment by TopchetoEU** [comment]
this should be configurable. i find it annoying when i run "deno add my-package" and it just fucks up my formatting. in my opinion, .editorconfig should be respected (currently it isn't)

**Comment by bartlomieju** [comment]
You can switch to tabs using `--use-tabs` flag or `useTabs` config option in `deno.json`. https://docs.deno.com/runtime/reference/cli/formatter/#formatting-options-use-tabs

**Comment by Malix-Labs** [comment]
Indeed, but I think that issue is about redefining defaults
