### ISSUE TITLE
standard for config files

### ISSUE THREAD

**Issue by timreichen** [denoland/deno#6228]
This is not an issue but more a lookout for opinions of the authors of Deno.

As I was using lots of different tools which use different conventions for their config files. I was amazed that I could not find anything about an overarching standard. So I wrote this short [article](https://gist.github.com/timreichen/87a894c94a4c2258b15962d1754e34a8) to try to summarize the problem and a proposal for a possible solution.

Since Deno pushes for unified standards, I wonder if it would be a good idea to work out and then advocate for one for config files to have mess-less projects in the longrun.

What are your thoughts about this topic?

PS: I am also writing to authors of popular tools like typescript, babel etc. to get their opinion and some insights.

**Comment by bartlomieju** [comment]
Deno has only a single config file (`tsconfig.json`) and it requires to explicitly tell Deno about it using `-c` flag. We don't plan to automatically discover any configuration files.

**Comment by timreichen** [comment]
I think deno does it exactly right with a specific ```-c``` flag.
What I meant was if there should be a deno guideline for 3rd party libs/tools.
@ry did the "10 Things I Regret About Node.js" way back. I always thought there was one missing: standards and a clear guideline for 3rd party tools.

Since deno is still very young, I could imagine that if there would be some kind of **deno 3rd party guideline** that it would result in a unified experience when using deno and 3rd party libs/tools.

As an example: if the **deno 3rd party guideline** would suggest always to use ```--config``` ```-c``` flags to declare a config file and allow ```json``` ```ts``` and  ```js``` as types we could avoid having these inconsistencies between tools down the road. The same with config file naming as in the article.

What do you think?
