### ISSUE TITLE
Travis is slow due to OSX

### ISSUE THREAD

**Issue by ry** [denoland/deno#623]
Travis builds went from ~6m to ~20m since the addition of OSX. This really hinders development. 

We need OSX builds for automated releases (#563) but I would rather have fast PR builds that don't include OSX. Is it possible to only build OSX on tagged and master builds? What about only tagged?
<img width="833" alt="screen shot 2018-08-29 at 12 02 30 pm" src="https://user-images.githubusercontent.com/80/44800055-7104b700-ab83-11e8-9bc5-12fd73feac90.png">

cc @hayd

**Comment by hayd** [comment]
I might be reading [this](https://travis-ci.com/denoland/deno/builds/83426475) wrong, but I think the linux builds have increased too... both are ~11minutes and run in parallel, so should take ~11 minutes total?:

![screen shot 2018-08-30 at 6 09 44 pm](https://user-images.githubusercontent.com/1931852/44887240-0eddac00-ac80-11e8-90ee-cc7d52e38f9f.png)

Reading the build history, I think before OSX the linux build was [~9minutes](https://travis-ci.com/denoland/deno/builds/82748418).

Anyway, #644 builds osx only on master. If we want to do that.

**Comment by bartlomieju** [comment]
Current status:
![zrzut ekranu 2019-02-12 o 19 47 48](https://user-images.githubusercontent.com/13602871/52660044-1bd51b80-2eff-11e9-91b8-9e993b61d4c1.png)

CC @ry

**Comment by ry** [comment]
We must stick with OSX CI.
