### ISSUE TITLE
easy UDP todo

### ISSUE THREAD

**Issue by ry** [denoland/deno#6231]
1. Address TODOs in https://github.com/denoland/deno/commit/54c3f8e27fa1f38a3e2d65c2b297c415062d01c8

2. op_datagram_send should return an integer instead of `json!({})` so that the caller can know how many bytes were sent.

**Comment by Kermit-Xuan** [comment]
I want to try it.

**Comment by Kermit-Xuan** [comment]
@ry When I got byte_length of `ZeroCopyBuf`, I found it is private, should I change it to `pub` or add a function to get it?

**Comment by ry** [comment]
@Kermit-Xuan the number of bytes sent is returned from send_to_poll - currently there's a `map_ok` which ignores the result. You shouldn't need to look at the ZeroCopyBuf.

**Comment by Kermit-Xuan** [comment]
> @Kermit-Xuan the number of bytes sent is returned from send_to_poll - currently there's a `map_ok` which ignores the result. You shouldn't need to look at the ZeroCopyBuf.

👌， I may ask a stupid question.
