### ISSUE TITLE
Announcement: I made a Deno Playground out on Katacoda

### ISSUE THREAD

**Issue by reselbob** [denoland/deno#6232]
https://katacoda.com/reselbob/scenarios/deno-playground

For those who want to play around. Not sure if this the best place to make the announcement, but without a Gitter channel or the like, this is the best I could do.

I trust you all understand.

**Comment by lucacasonato** [comment]
Cool, but we actually do have a channel for this. It’s on Discord: https://discord.gg/deno 😀

**Comment by bartlomieju** [comment]
Cool @reselbob! As pointed by @lucacasonato make sure to add it to "Showcase" channel on Discord!

**Comment by reselbob** [comment]
Yes, posted it on the Showcase channel. Thanks!
