### ISSUE TITLE
dayOfYear returns wrong days

### ISSUE THREAD

**Issue by ajkimdev** [denoland/deno#6233]
I believe that the day of year of 2020-01-01 is 1.
However, I got 365 at my local machine (Windows 10).
Is this an error from my local enviroment?
![image](https://user-images.githubusercontent.com/43775732/84354504-d453b380-ab75-11ea-9258-991adaf3ef4e.png)

**Comment by lenkan** [comment]
What timezone are you in? I'd say this is probably expected behaviour:

```
> TZ="America/New_York" deno eval "console.log(new Date('2020-01-01').getFullYear())"
2019
```

```
> TZ="Europe/Amsterdam" deno eval "console.log(new Date('2020-01-01').getFullYear())"
2020
```

**Comment by ajkimdev** [comment]
@lenkan Pacific as well as America/LosAngles. Oh I see, it depends on GMT,, so 2020-01-01 in Pacific time zone is 2019-12-31 right? then, it counts 365

**Comment by bartlomieju** [comment]
Closing as resolved. Feel free to reopen if there's still something going wrong.
