### ISSUE TITLE
Support URL Query Parameters

### ISSUE THREAD

**Issue by ryanwhite04** [denoland/deno#6234]
Deno bundles javascript files with query parameters as typescript

If I run the following it works fine:

```
deno bundle https://unpkg.com/lit-html@1.2.1/lit-html.js lit-html.bundle.js
```

```
Bundling https://unpkg.com/lit-html@1.2.1/lit-html.js
Emitting bundle to "lit-html.bundle.js"
65445 bytes emitted.
```

But if I try to use [UNPKG](https://unpkg.com) ES6 module resolution with the ```?module``` query parameter which replaces bare import specifiers with absolute URLs I get an error.

```
deno bundle https://unpkg.com/lit-html/lit-html.js?module lit-html.bundle.js

TS7019 [ERROR]: Rest parameter 'values' implicitly has an 'any[]' type.
export const svg = (strings, ...values) => new SVGTemplateResult(strings, values, 'svg', defaultTemplateProcessor);
                             ~~~~~~~~~
    at https://unpkg.com/lit-html@1.2.1/lit-html.js?module:59:30

Found 229 errors.
```

This particular package doesn't actually need the the ```?module``` query parameter as all modules it uses are referenced using relative paths, but an example where it would be necessary is ```lit-element``` which uses ```lit-html```.

```
deno bundle https://unpkg.com/lit-element/lit-element.js lit-element.bundle.js

  Bundling https://unpkg.com/lit-element/lit-element.js
  error: relative import path "lit-html/lib/shady-render.js" not prefixed with / or ./ or 
../ Imported from "https://unpkg.com/lit-element@2.3.1/lit-element.js"
```

Supporting query strings would also allow for other arguments to be passed to modules as part of the ```import.meta.url``` property like shown [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import.meta)

```javascript
// index.mjs
import './index2.mjs?someURLInfo=5';

// index2.mjs
new URL(import.meta.url).searchParams.get('someURLInfo'); // 5
```

**Comment by kitsonk** [comment]
This is specifically about bundling with URLs that contain query parameters.

It is a defect, as there is fairly complex logic to guess at what the module specifier will be put in the bundle, as TypeScript interferes with it quite a lot, and that logic never accounted for the specifiers containing query parameters.

**Comment by ryanwhite04** [comment]
Yeah i'm trying to use it for bundling with URLS that contain query parameters, but it would be nice for local files too as another way to pass arguments to modules.

```deno info``` currently works fine with query strings which is nice, but it's a shame it doesn't return JSON or have an API like ```Deno.info()``` so I could use it to generate an import map from UNPKG and not have to use UNPKG's `?module``` query string module resolution.

If that's not possible due to issues caused by TypeScript, perhaps ```deno bundle``` and the ```Deno.bundle``` API could just strip query strings from URLs passed to them, ignoring them completely, but I guess this would cause problems if someone is using "?" somewhere in their path.

**Comment by nayeemrmn** [comment]
`deno bundle https://unpkg.com/lit-html/lit-html.js?module` and `deno bundle https://unpkg.com/lit-element/lit-element.js?module` seem to work. I think this is fixed.
