### ISSUE TITLE
`StartTlsOptions` doesn't include port, but example does, also missing other necessary options.

### ISSUE THREAD

**Issue by aricart** [denoland/deno#6238]
The unstable doc shows `{certificate, hostname, port}` as a snippet in https://doc.deno.land/https/raw.githubusercontent.com/denoland/deno/master/cli/js/lib.deno.unstable.d.ts#Deno.startTls.

[port is likely not needed for Deno.startTls]

However, https://doc.deno.land/https/raw.githubusercontent.com/denoland/deno/master/cli/js/lib.deno.unstable.d.ts#Deno.StartTlsOptions only has `{certificate, hostname}`.

Also - for client certificate authentication, the client certificate, key, and a ca certificate will be required (for self-signed cert conditions).

**Comment by bartlomieju** [comment]
This seems to be fixed now.
