### ISSUE TITLE
Git Bash denon: command not found

### ISSUE THREAD

**Issue by ngtantai1001** [denoland/deno#6239]
```bash
Administrator@TAIDEPTRAI-PC MINGW64 ~
$ deno install --allow-read --allow-run --allow-write -f --unstable https://deno.land/x/denon/denon.ts
Download https://deno.land/x/denon/denon.ts
Download https://deno.land/x/denon/deps.ts
...
Compile https://deno.land/x/denon/denon.ts
✅ Successfully installed denon
C:\Users\Administrator\.deno\bin\denon.cmd

Administrator@TAIDEPTRAI-PC MINGW64 ~
$ denon
bash: denon: command not found

Administrator@TAIDEPTRAI-PC MINGW64 ~
$
```

This happens even on other tools installed using the deno install command.
Powershell works well. 
Git bash not. 
But Git bash with command `denon.cmd` then it works.

**Comment by leonelv** [comment]
this is an issue with your configuration, please check your .bashrc or .profile config

**Comment by MarkTiedemann** [comment]
> Git bash with command `denon.cmd` works.

Well, Git Bash is weird. To work around Git Bash not resolving `PATHEXT` (as a proper Windows shell should), you can create a file called `denon` with the following content:

```
#!/bin/sh
denon.cmd "$@"
```

Make sure that the file is located in the `PATH`.

**Comment by dmacisso** [comment]
alias denon=denon.cmd

**Comment by dmacisso** [comment]
In git bash shell
alias denon=denon.cmd

**Comment by hchiam** [comment]
Even with `alias denon=denon.cmd` in .bash_profile, I'm getting `bash: denon.cmd: command not found`

**Comment by MarkTiedemann** [comment]
> Even with alias denon=denon.cmd in .bash_profile, I'm getting bash: denon.cmd: command not found

Have you `source`'d your `.bash_profile`?

**Comment by hchiam** [comment]
@MarkTiedemann yup, did that too - still no luck.

**Comment by bartlomieju** [comment]
Closing as resolved.
