### ISSUE TITLE
Logging nested object not readable

### ISSUE THREAD

**Issue by jtenner** [denoland/deno#625]
## 🙋‍♀️ Feature Request: Make objects readable when `console.log`ged.

```
{ matchType: 0, value: [ { nodeType: 2, type: BinaryExpression, props: { left: { nodeType: 0, type: literal, props: { value: 1 }, meta: { start: { line: 0, col: 0 }, end: { line: 0, col: 1 }, length: 1 } }, op: +, right: { nodeType: 0, type: literal, props: { value: 1 }, meta: { start: { line: 0, col: 4 }, end: { line: 0, col: 5 }, length: 1 } } }, meta: { start: { line: 0, col: 0 }, end: { line: 0, col: 5 }, length: 5 } } ], meta: { start: { line: 0, col: 0 }, end: { line: 0, col: 5 }, length: 5 } }
```
There is no tabbing or nested object logging logic, so everything simply appears on one line.

In the meantime, I can bypass this by creating my own log function which uses `JSON.stringify()`.

## 👀 Examples:

1. Strings are output without `"`s and it's hard to discern certain kinds of strings from identifiers.
1. Nested objects have no `\n` before their displayed contents either.
1. Deeply nested objects that are very large will not be truncated at deeply nested points, like the example provided.

## Version
Deno 1.1

**Comment by ry** [comment]
Can you give an example?

**Comment by jtenner** [comment]
Sorry about that! I accidentally submitted the issue before typing anything. The original issue is edited.

**Comment by mohsen1** [comment]
`JSON.stringify` will throw if you have circular refs. Something like Node's `util.inspect` is more proper for this.

Pretty printing can be done more elegantly than Node's inspect method. Specially now that JS has `WeakMap`s and `Proxy`s etc. Chrome devtools does a good job of this.

**Comment by kevinkassimo** [comment]
Totally agreed. I made most of the current `console.log` implementation months ago. `Console` was pretty much not functioning before that (as the original implementation used `JSON.stringify` which would simply errors out on non JSON values) and I was like first hacking up something that at least could handle most use cases. Should consider refactoring `Console` some time soon.

**Comment by kevinkassimo** [comment]
As for no `"`s around strings, my original implementation did have quotes, but they were dropped in #608 . Personally I do agree that `"` should be helpful around strings.

**Comment by jaydenseric** [comment]
Very frustrating things about Node.js `util.inspect` that excludes it from being used as part of a snapshot testing solution:

- It (and is documented to) outputs differently between Node.js patch or minor releases. If you test your package across multiple Node.js versions, snapshots will pass on some and fail on others.
- It has "smart" behavior that puts more details on one line if it is short enough. This makes for difficult to read diffs when a snapshot test fails.

Using JSON.stringify, as already mentioned, has the circular references headache. I currently use the [`circular-json`](https://npm.im/circular-json) package to help with that: https://github.com/jaydenseric/jsdoc-md/blob/v1.6.0/lib/outlineMembers.test.js#L34

It would be good if Deno had a function for displaying objects as a string that would serve both logging and snapshot testing use cases.

**Comment by bartlomieju** [comment]
`deno.inspect` is available for pretty formatting of objects.

CC @ry

**Comment by ry** [comment]
I want to move deno.inspect out of core and into deno_std... but ok.
