### ISSUE TITLE
Deno info as json

### ISSUE THREAD

**Issue by mathiasrw** [denoland/deno#6260]
# Feature request

It would be so lovely if the output from Deno info did not have to be parsed from the text (if used by a script) but there was a way of getting it as json. For example with a `--json` flag.

**Comment by MarkTiedemann** [comment]
ref https://github.com/denoland/deno/issues/3551#issuecomment-572174031

**Comment by implicitdef** [comment]
I'd like to take this one.

**Comment by ry** [comment]
@implicitdef please do : )

**Comment by mathiasrw** [comment]
Ohhh - just got released as part of 1.2.0 - epic work folks...
