### ISSUE TITLE
Narrowing type guard bug for Deno.Process.stdin in v1.1.0

### ISSUE THREAD

**Issue by jsejcksn** [denoland/deno#6270]
Consider this (contrived) example, `echo.ts`, which uses the `cat` binary to print `stdin`:

```ts
export const echo = async (data: string): Promise<void> => {
  const runOpts: Deno.RunOptions = {
    cmd: ['cat'],
    stdin: 'piped',
  };

  const p = Deno.run(runOpts);

  if (!p.stdin) throw new Error('stdin not available');
  await p.stdin.write(new TextEncoder().encode(`${data}\n`));
  p.stdin.close();

  const {success} = await p.status();
  if (!success) throw new Error('Process encountered an error');

  p.close();
}

const main = (): void => {
  const text = Deno.args.join(' ') || 'hello world';
  echo(text);
};

if (import.meta.main) main();

export default echo;
```

It compiles and runs using Deno v1.0.5:

```shell
> deno --version
deno 1.0.5
v8 8.4.300
typescript 3.9.2
> deno run --allow-run echo.ts
hello world
```

but in Deno v1.1.0, this TypeScript compilation error occurs:

```shell
> deno --version
deno 1.1.0
v8 8.4.300
typescript 3.9.2
> deno run --allow-run echo.ts
Compile file:///mnt/path/redacted/for/privacy/echo.ts
error: TS2531 [ERROR]: Object is possibly 'null'.
  await p.stdin.write(new TextEncoder().encode(`${data}\n`));
        ~~~~~~~
    at file:///mnt/path/redacted/for/privacy/echo.ts:10:9

TS2531 [ERROR]: Object is possibly 'null'.
  p.stdin.close();
  ~~~~~~~
    at file:///mnt/path/redacted/for/privacy/echo.ts:11:3

Found 2 errors.
```

I see that the type definition has changed from 1.0.5 to 1.1.0:

[1.0.5 `lib.deno.d.ts`](https://github.com/denoland/deno/releases/download/v1.0.5/lib.deno.d.ts#L1744):
```ts
export class Process {
    readonly rid: number;
    readonly pid: number;
    readonly stdin?: Writer & Closer;
```

[1.1.0 `lib.deno.d.ts`](https://github.com/denoland/deno/releases/download/v1.1.0/lib.deno.d.ts#L1782):
```ts
export class Process<T extends RunOptions = RunOptions> {
    readonly rid: number;
    readonly pid: number;
    readonly stdin: T["stdin"] extends "piped" ? Writer & Closer : null;
```

**Comment by jsejcksn** [comment]
Additional information:

Removing the `Deno.RunOptions` type annotation from `runOpts` and using `as const` for `stdin` fixes the errors:

```ts
const runOpts = {
  cmd: ['cat'],
  stdin: 'piped' as const,
};
```

**Comment by bartlomieju** [comment]
CC @nayeemrmn

**Comment by nayeemrmn** [comment]
> Removing the `Deno.RunOptions` type annotation from `runOpts` and using `as const` for `stdin` fixes the errors

Yep, when you do this you actually no longer need the type guard `if (!p.stdin) throw ...`.

However, the type `Deno.Process<Deno.RunOptions>["stdin"]` should be backward compatibly `(Writer & Closer) | null`. For some reason it's regressed to be `null`.
