### ISSUE TITLE
SRI for Deno

### ISSUE THREAD

**Issue by ematipico** [denoland/deno#6284]
Modern browsers implement a security measure for third party files loaded from a different domain: https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity

Are there any plans to "port" this security feature into deno? 

I believe that considering Deno's mission around security and browser interoperability, it should be supported somehow.

What do you think?

**Comment by kitsonk** [comment]
Duplicate of #170, #200

Please use the search functionality before opening new issues.  Search term used: ["subresource integrity"](https://github.com/denoland/deno/issues?q=is%3Aissue+Subresource+Integrity+)
