### ISSUE TITLE
Why not remove keyword await and let async and sync function behave the same?

### ISSUE THREAD

**Issue by randomhash** [denoland/deno#6286]

**Comment by crowlKats** [comment]
this is not in our hands, but rather with Ecmascript. Deno isnt here to change how JS works.

**Comment by randomhash** [comment]
@crowlKats  Maybe I'am to inexperienced, but would it not introduce more readable, clear code in all ways? Less possible promise not awaited errors in real-world applications and other stuff. I would be glad to understand what downsides it will introduce)
But anyway, if Deno here not to change how JS works, then I think this question has no point ;)
