### ISSUE TITLE
(cli/net) op_datagram_send panic for unixpacket transport

### ISSUE THREAD

**Issue by pevers** [denoland/deno#6290]
Very similar to https://github.com/denoland/deno/issues/6179 . Deno panics when doing a parallel write to the socket for the "unixpacket" transport.

```
const socket = Deno.listenDatagram({
  path: "/tmp/test.sock",
  transport: "unixpacket"
});

const a = socket.send(new Uint8Array(), socket.addr);
const b = socket.send(new Uint8Array(), socket.addr);
await Promise.all([a, b]);
socket.close();
```

Result:
```
thread 'main' panicked at 'already borrowed: BorrowMutError', /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libcore/cell.rs:878:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Caused by:
https://github.com/denoland/deno/blob/0ffc99a61ddfa958a436beef0d003ecead630d0f/cli/ops/net.rs#L216

There should be a way to safely borrow the resource in a thread.

**Comment by bartlomieju** [comment]
I tried fixing this problem, unfortunately Tokio doesn't expose public API to poll `UnixDatagram`. Opened an issue in Tokio repo: tokio-rs/tokio#2853

**Comment by ry** [comment]
@bartlomieju This is a concrete reason why we need this "weak ref" pattern.

**Comment by bartlomieju** [comment]
> @bartlomieju This is a concrete reason why we need this "weak ref" pattern.

Yes, I agree

**Comment by Soremwar** [comment]
Deno will now throw on attempt to send two packets at the same time

![image](https://user-images.githubusercontent.com/42647963/102395841-aaa69980-3fa9-11eb-9e0d-0b1376ef6bf6.png)

**Comment by ry** [comment]
Closing - we do not panic anymore (thanks for pointing it out @Soremwar). As mentioned, it still errors out, and that's debatable behavior. But let's continue that discussion in a new issue, if people have problems with it.
