### ISSUE TITLE
Disk cache is not handling reserved characters in file paths

### ISSUE THREAD

**Issue by qgustavor** [denoland/deno#6293]
[The code that handles disk cache](https://github.com/denoland/deno/blob/0ffc99a61ddfa958a436beef0d003ecead630d0f/cli/disk_cache.rs) is not handling [reserved characters in file paths](https://en.wikipedia.org/wiki/Filename#Reserved_characters_and_words). This issue affects mostly Windows users trying to import a module with a reserved character in the URL like `:`, which is used in https://deno.land/x/ to specify NPM and GitHub imports.

An example that fails on Windows:

```typescript
import * as html from 'https://deno.land/x/gh:qgustavor:leizm-html-parser/src/lib/index.ts'
```

Current output:

```
error: Could not create TypeScript compiler cache location: "C:\\...\\deno\\gen\\https\\deno.land\\x\\gh:qgustavor:leizm-html-parser\\src\\lib"
Check the permission of the directory.
```

Is possible to workaround this issue by replacing `:` with `%3A` in the URL.

**Comment by lucacasonato** [comment]
Mh, usually all remote file paths are hashed before they are stored in DENO_DIR - I guess files in `$DENO_DIR/gen` are not. If they just use the same file name hashing as files in `$DENO_DIR/deps` this issue should be resolved.

**Comment by bartlomieju** [comment]
Ref https://github.com/denoland/deno/issues/4070
