### ISSUE TITLE
Permissionless static imports of local modules still allowed

### ISSUE THREAD

**Issue by teleclimber** [denoland/deno#6294]
```
import hello from '../../outside/target.ts';
```

...successfully imports the module, which is outside the directory of the running script, even if no `--allow-read` permissions are given.

I don't think this is right. In my original issue on the topic (#3401) I used a JSON file as an example. That issue is now closed because JSON imports are all blocked. But the issue remains for JS and TS imports.

I don't think a "secure runtime for JavaScript" should be able to run code from the user's local drive without explicit permission. Just like JSON, a JS file can contain private data. A current trend is to make config files JS instead of JSON (think `webpack.config.js`, `jest.config.js`, etc...) so I don't think you can say that a JS file is just code, and therefore contains no sensitive data. That's just wrong.

I understand why remote imports are allowed without `--allow-net`: if the module is available on a public server, by definition nothing it contains can be secret. 

Furthermore, for some reason local imports from remote scripts are denied regardless of permissions. So we have this situation:

- Remote modules: can not statically import from local files under any circumstances even with `--allow-all`.
- Local modules: can import local modules (statically) without any permission granted whatsoever

What's the logic here? I don't get it.

**Comment by nayeemrmn** [comment]
> So we have this situation:
> 
> * Remote modules: can not statically import from local files under any circumstances even with `--allow-all`.
> * Local modules: can import local modules (statically) without any permission granted whatsoever
> 
> What's the logic here? I don't get it.

The logic is that a module can statically import any same origin or public module without permission. That's just the model... same origin modules shouldn't contain secrets. If you want isolation in this respect, you can just host the code in a local file server. The local modules that are available for import can be filtered as you please. This is only as inconvenient as the number of developers running untrusted local modules is few. 

If we were to characterise the fundamental problem that you're pointing out, it wouldn't be solved by blocking imports outside of the main module's directory. Modules located like that aren't special. That would be a _practical_ measure for what you think is a common development workflow. But there is a natural solution above. Why complicate module resolution by introducing a project root?

**Comment by bartlomieju** [comment]
> * Remote modules: can not statically import from local files under any circumstances even with `--allow-all`.

It follows browsers behavior - `file://` module can't be statically referenced from remote modules - you can still load `file://` modules from remote scripts using dynamic import (this will perform permission check).

> * Local modules: can import local modules (statically) without any permission granted whatsoever

The only way to run local file is by using `deno run <script>` - it means that user must explicitly run code by typing command. Surely you'd want to be able to run code from other directories and since you must do that explicitly hence requiring additional permissions in this situation doesn't make sense IMO.

**Comment by tv42** [comment]
Have I understood this right: The only way to trigger any real sandboxing in Deno is to serve the *.js to it from web server? And to avoid cross-project leaks in the fashion demonstrated here for local files, the URL has to have a unique origin, too?

**Comment by nayeemrmn** [comment]
@teleclimber @tv42 I've discovered you can simply apply the following import map to achieve this:
```json
{
  "imports": {
    "/": "undefined:undefined",
    "./": "./"
  }
}
```

**Comment by teleclimber** [comment]
@nayeemrmn interesting tip, unfortunately it completely blocks all imports outside the script directory. I can't figure out how to use `importmap` to allow some scripts from outside to run but not others, as I could do if imports followed the same rules as `--allow-read`.

**Comment by nayeemrmn** [comment]
@teleclimber The first entry of that import map sends imports to all file paths from root to `undefined:`. The second entry overrides that for the import map's containing directory, resetting it back to itself. Do the same for any exceptions you want to make.
```json
{
  "imports": {
    "/": "undefined:",
    "./": "./",
    "/home/nayeem/my-scripts/": "/home/nayeem/my-scripts/"
  }
}
```

**Comment by benatkin** [comment]
The docs have painted the permissions more rosy than it is, suggesting use for running untrusted code. https://docs.deno.com/runtime/manual/basics/permissions If you have the idea to run untrusted code with `--allow-net=semi-trusted.dev` it could expose stuff from local scripts. Also just unexpected behavior. This should be reopened IMO.

**Comment by lucacasonato** [comment]
If you run untrusted code that is stored on disk, it can read other files on disk (same origin). It can only import files that are statically analyzable. You can list out all files being imported by a script with `deno info`. Only files listed here will be statically importable at `deno run` without extra permission

**Comment by benatkin** [comment]
@lucacasonato I understand all that, but I think some might assume it only has access to the current directory, if they don't just fail to realize that they're in a mode which enables running multi-file programs (they may think they're in a mode for running single-file programs, as those can quite powerful).

Also the browser analogy falls flat. The browser's static imports don't have access to the whole disk. "same origin" has a meaning in this case that's given to Deno.

I understand Deno has had this behavior for a long time and it is considered part of the stable behavior, however I don't think it jibes with the permissions doc.

Neither does having access to localStorage. Someone could run one script thinking it has access to all files, and then get output, and send that output with another script that only has access to that file and a remote site. However, the first script could have saved something to localStorage which is used in the second request to send to the remote site.

**Comment by benatkin** [comment]
`deno info` does help

The localStorage problem can be solved by giving each run a random origin and/or making sure it's cleared out when untrusted code that doesn't depend on other stuff.

For clearing it out there is localStorage and Deno KV. I don't know if there are any others that I'm missing.
