### ISSUE TITLE
Support other targets with Deno.bundle

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#6297]
Currently the [bundle loader](https://github.com/denoland/deno/blob/master/deno_typescript/system_loader.js) requires ES2017+.  That means it isn't suitable for other targets and it isn't transpiled on the fly.

Originally I though we should just transpile for every target, but I think it is just easier to just have a single transpiled version that targets ES5 and if the target is less than < ES2017 it uses ES5.  ES3 isn't a realistic target to support for `deno bundle` or `Deno.bundle`.

**Comment by iugo** [comment]
How to use `deno bundle` target to ES5?

There are no related options in `deno bundle --help`.

deno 1.3.1
