### ISSUE TITLE
getting 404 on https://deno.land/x/oak

### ISSUE THREAD

**Issue by ajerni** [denoland/deno#6307]
What happened to oak? Seems not to be available anymore?

**Comment by nayeemrmn** [comment]
Duplicate of https://github.com/oakserver/oak/issues/169. Please check the correct repo.

**Comment by lucacasonato** [comment]
The issue is fixed now :-)

**Comment by ry** [comment]
Fixed in https://github.com/denoland/deno_website2/pull/1132
