### ISSUE TITLE
std/log: add loggers name to LogRecord

### ISSUE THREAD

**Issue by muuvmuuv** [denoland/deno#6310]
Creating loggers in Deno is nice, I really enjoy having a native log module. One thing I am missing is the possibility to output the logger name. So I am able to really see which part the log is coming from in my module.

Current behaviour:

```ts
const logger = log.getLogger('config')

logger.debug('debug')

// => DEBUG debug
```

Wanted behaviour:

```ts
const logger = log.getLogger('config')

logger.debug('debug')

// => DEBUG(config) debug
```

Additionally, a `LogRecord.filename` and `fileline` would be cool to add e.g. to the file output, but this is not mandatory, just something I thought of.

**Comment by cknight** [comment]
I'd be happy to look into this.

**Comment by bartlomieju** [comment]
Done in #6316
