### ISSUE TITLE
Allow specifying Typescript compiler options in Worker

### ISSUE THREAD

**Issue by wongjiahau** [denoland/deno#6312]
At the moment, there's no way to specify Typescript compiler options when spawning a `Worker`, which prevented user from using customized `tsconfig.json`.

**Comment by deebloo** [comment]
are you looking to have different compiler options in your workers than the rest of your code base?

**Comment by deebloo** [comment]
if you are just looking to add worker type definitions you can use a triple slash directive.
```TS
/// <reference lib="webworker" />
```

**Comment by wongjiahau** [comment]
@deebloo I'm actually wanted to change the `jsxFactory` value from `React.createElement` to something else, because I'm trying to use JSX for my own web frameworks. At the moment, I'm declaring the `React` namespace, now it's kinda awkward because user who wanted to use my library needs to import the `React` namespace without using it.

**Comment by kitsonk** [comment]
Why wouldn't you just specify it on the command line?  (`deno run --config tsconfig.json`)  Why would you want a different one for the worker?

**Comment by wongjiahau** [comment]
@kitsonk I actually thought of using `Deno.run` before, but @bartlomieju told me that `Deno.run` is spawning process, so it can be more expensive and slower than `Worker` which spawn threads.

**Comment by kitsonk** [comment]
But why would your top invocation of `deno run --config tsconfig.json` need to differ from your `new Worker()`?

**Comment by wongjiahau** [comment]
@kitsonk oh ok so you’re saying if I started my script X with a tsconfig A, the Worker spawn by X will use A?

**Comment by kitsonk** [comment]
It feels to me that having a different config for the `Worker()` from the main module is an edge case.  Something we might want to consider in the longer term after we have some major refactors of both the Worker (like structured cloning and the Deno namespace) and the compiler settled, but I would generally consider this a low priority.

**Comment by bartlomieju** [comment]
We're actually trying to limit number of options for configuring TypeScript so respectfully declining.
