### ISSUE TITLE
Add deno --types

### ISSUE THREAD

**Issue by ry** [denoland/deno#632]
I think we should start with something simpler than API docs. We need a way to get the full typescript declarations of what Deno provides. I propose adding a command line flag:
```
$ deno --types
declare global {
    interface Window {
        console: Console;
        define: Readonly<unknown>;
    }
    const clearTimeout: typeof timers.clearTimer;
    const clearInterval: typeof timers.clearTimer;
[...]
```
This should output, to stdout, the complete type declarations of all globals and all built-in modules inside Deno, including JS doc comments.
We can then work from there to provide more user friendly documentation (#573) by generating html from it.

**Comment by ztplz** [comment]
Should we  add a dom_type  file?

**Comment by ry** [comment]
@ztplz I'm not sure what that means.

Ideally the huge `deno.d.ts` file that we'd be outputting could be generated at build time. I imagine this thing getting modified - maybe to use tsc's outFile?
https://github.com/denoland/deno/blob/ceaf82268282d16b97101c00c75612745de416bb/BUILD.gn#L184-L219

**Comment by kitsonk** [comment]
> Should we add a dom_type file?

Why? Deno has no DOM.

**Comment by kitsonk** [comment]
For clarity, I am actively working on finishing this off.

**Comment by MarkTiedemann** [comment]
> We need a way to get the full typescript declarations of what Deno provides.

Since most existing TypeScript tooling gets the declarations from npm, is there anything wrong with publishing the declarations on npm, too?

See: [denoland/deno_install/#6](https://github.com/denoland/deno_install/issues/6)

**Comment by kitsonk** [comment]
I think we can finally close those (there is the other issue for the improvements of this).

**Comment by ry** [comment]
Thanks
