### ISSUE TITLE
@deno-types

### ISSUE THREAD

**Issue by blujedis** [denoland/deno#6321]
Quick question so what's the trick with type hints? The below doesn't seem to work in that React is still "any". What am I missing? Thx!

```ts
// @deno-types="https://deno.land/x/types/react/v16.13.1/react.d.ts"
import React from "https://cdn.pika.dev/react@16.13.1";
```

**Comment by mikolaj-leszczynski** [comment]
@blujedis AFAIK, you don't even have to add the `// @deno-types="https://deno.land/x/types/react/v16.13.1/react.d.ts"` part. `pika` will deliver the proper types in response header `x-typescript-types` and Deno should fetch the types by itself. Did you try to remove that line?

**Comment by blujedis** [comment]
Yeah that's sort of what I thought but I don't get any code help in vscode. Now if I import from those resources I do but...

BTW it doesn't error when I run and in fact downloads, in this case, React. Just no types/code help.

**Comment by kitsonk** [comment]
What plugin are you using? That would be an issue for the plugin to support that, not Deno itself.

**Comment by blujedis** [comment]
Just the primary Deno plugin for vscode, you can find it here https://github.com/denoland/vscode_deno

Right so the types are correct when compiling but there's no code help. Sort of deduced that's what the issue is here. So the type hints appear to have little to nothing to do with code completion/help as to types. 

Standard or native Typescript modules don't have this issue.

**Comment by kitsonk** [comment]
@blujedis this is an issue for vscode_deno in that it isn't respecting the header information which is written to the cache.

@bartlomieju can you move the issue to there?

**Comment by blujedis** [comment]
@kitsonk it is and realized this today...closing.
