### ISSUE TITLE
--allow-env permission list

### ISSUE THREAD

**Issue by jsejcksn** [denoland/deno#6322]
Apologies for noise if this has been asked/discussed before—I can't seem to find it.

[The manual](https://deno.land/manual/getting_started/permissions#permissions-list) explains permissions. Some of them have list options, but it doesn't appear that `--allow-env` currently allows for a list. Is there a reason for this? It seems desirable to be able to restrict access to environment variables while allowing access to specific values.

**Comment by nayeemrmn** [comment]
Duplicate of #3137. Shouldn't be a problem with the new `Deno.env` API as suggested there.

**Comment by jsejcksn** [comment]
Thanks @nayeemrmn!
