### ISSUE TITLE
Can't use module that exports a module from URL

### ISSUE THREAD

**Issue by sant123** [denoland/deno#6324]
Hi, I found an issue when importing a module that exports some remote modules. Please take a look:

![one](https://user-images.githubusercontent.com/7959437/84833540-202eae80-aff5-11ea-9649-3934d1f45885.png)

Also if a import the module with *

![two](https://user-images.githubusercontent.com/7959437/84833551-27ee5300-aff5-11ea-870b-7c25a5b87641.png)

I just can see the method inside the object, but still can't access it.

![three](https://user-images.githubusercontent.com/7959437/84833559-2fadf780-aff5-11ea-9dca-511cc73be504.png)

Thank you.

**Comment by actual-size** [comment]
If you cast `libs` as `any` then your example works fine. If possible, I'd recommend that you write typing to `readLine.js`, or just rewrite it in Typescript

**Comment by sant123** [comment]
You are right, I rewrote the file to Typescript and works like a charm.

Thank you!
