### ISSUE TITLE
Add support for fsync and fdatasync

### ISSUE THREAD

**Issue by caspervonb** [denoland/deno#6325]
Would be nice to have bindings for fsync and fdatasync.

These are exposed as `sync_data` and `sync_all` on both std::fs::File and tokio::fs::File so implementation is fairly trivial.

Proposed interface

```typescript
namespace Deno {
  export function syncDataSync() : void;
  export function syncData() : Promise<void>;

  export function syncSync() : void;
  export function sync() : Promise<void>;
}
```

**Comment by ry** [comment]
I'm all for it. Although these are very simple signatures, I think we ought to add them to unstable first as a matter of principle.
