### ISSUE TITLE
TLS ALPN support

### ISSUE THREAD

**Issue by yearsyan** [denoland/deno#6334]
## Feature request 
I thiink it is necessary to support alnp. For example, if a developer want to create a http2 server,  alpn can make handshake quicker.

**Comment by kitsonk** [comment]
ALPN would need to be implemented as part of HTTP/2, so effectively duplicate of #3995.

**Comment by lucacasonato** [comment]
@kitsonk Not per se - if the HTTP/2 server is Rust based, then an implementation of ALPN for `Deno.connectTls` or `Deno.listenTls` would need to happen separately from HTTP/2 right?

**Comment by kitsonk** [comment]
I mean we wouldn't have to implemented ALPN to implement HTTP/2, but it doesn't make sense... the whole thing should be addressed as one (likely along with moving HTTP/1.1 into Rust as well which is something we said we were going to have to do).

**Comment by yearsyan** [comment]
@kitsonk I think an implementation of ALPN for `Deno.connectTls` or `Deno.listenTls` is good for developer who want to create a protocol over tls, HTTP/2 is not the only protocol needs ALPN.
