### ISSUE TITLE
Deno.moveFile

### ISSUE THREAD

**Issue by ForgivenNin** [denoland/deno#6345]
Hello,

I suppose this will just remain as a suggestion from me, because I do not know how to write in the Rust or TypeScript. Looking through the runtimeAPI, I see that you can create files and directories, but there is no said way of moving things around. _Is there already a way of doing it?_

The first thing conclusion came to my mind to look for is a header similar to a shell's `mv` command.

**Comment by lucacasonato** [comment]
This might be slightly unintuitive at first glance, but you can rename files around. So `await Deno.rename("old/path", "new/path");` is actually what you are looking for.

**Comment by ForgivenNin** [comment]
That's definitely in the runtimeAPI. Thanks!
