### ISSUE TITLE
Difficulties using File URLs in Deno Filesystem Methods relating to URL encoding

### ISSUE THREAD

**Issue by Grunet** [denoland/deno#6349]
I was trying out the new feature @actual-size added in Deno 1.1.0 (on Windows) to allow file URLs to be used in Deno's fs methods (thanks for that, I was struggling to figure out why that wasn't working for me until I came across it), but was running into issues with those methods not being able to find my local files, which I eventually realized might have to do with my file paths containing spaces in some of the folder names.

After reading through more of #5990 's discussion, I tried switching all of the spaces to dashes and it worked, but I couldn't find any other issues out there documenting the limitation.

So I wanted to ask if this is the expected behavior for now (and if I should I aim to avoid including any characters that might get URL encoded in any folder names that Deno might be parsing) or if I'm maybe missing something else on this topic?

Thanks

**Comment by nayeemrmn** [comment]
Yeah, I noticed no call to `decodeURIComponent()` for the Windows function: https://github.com/denoland/deno/blob/ebf5c7b8cc79d8d164d95927168067083debef27/cli/js/util.ts#L84-L100

**Comment by actual-size** [comment]
@nayeemrmn Looks like I've also neglected to do any of the forward slash replacement/decoding for UNCs as well. I'll get a PR up for those fixes
