### ISSUE TITLE
Property 'permissions' does not exist on type 'typeof Deno'.

### ISSUE THREAD

**Issue by dan-online** [denoland/deno#6353]
As seen in #5692 when trying to use permissions to check whether a certain permission is allowed, an error occurs.

Sample code:
```ts
const yes = await Deno.permissions.query({ name: "read" });
if (yes.state != "granted") throw new Error("Permissions not granted");
```

In eval I also receive the error: ``Uncaught TypeError: Cannot read property 'query' of undefined`` as if Deno.permissions is not a thing even when its documented in the docs [here](https://deno.land/typedoc/classes/deno.permissions.html), although not in the [new docs](https://doc.deno.land). 

I assume I must be doing this wrong so any help would be appreciated!

deno 1.1.0
v8 8.4.300
typescript 3.9.2

Thanks, Dan

**Comment by kitsonk** [comment]
`deno run --unstable`

**Comment by dan-online** [comment]
Oh alright, thanks! Interesting that it doesn't throw an error like Workers about how you need to use the unstable flag

**Comment by kitsonk** [comment]
An oversight. Cc/ @lucacasonato

**Comment by lucacasonato** [comment]
@kitsonk Yeah - this is the issue with #5503. Keeping it in sync with the the d.ts. :-(

**Comment by dan-online** [comment]
Mainmodule is also affected by this and needs the --unstable flag, if that helps in any way

```bash
Property 'mainModule' does not exist on type 'typeof Deno'.
```

**Comment by zinthose** [comment]
I feel these --unstable dependent modules need a consistent means to determine if it is indeed running with the unstable flag
Maybe add "unstable" to the version object, although this feels like a band-aid solution to a long term problem.   

Example:

```bash
$ deno eval --unstable "console.log(Deno.version);"
{ deno: "1.1.1", v8: "8.5.104", typescript: "3.9.2", "unstable": true }
```

Hopefully we can get the Permissions module native to Deno with some way of testing for presence of these flags.

**Comment by dptole** [comment]
@zinthose agree, this is what I'm trying to do now. I'm trying to detect the absence of `Deno.setRaw`. This is my solution at the moment https://github.com/dptole/deno-playground/blob/master/src/std/01-io.ts

```ts
declare module Deno {
  function setRaw(rid: number, mode: boolean): void;
}

typeof Deno.setRaw === "function" // true if --unstable is present
```
