### ISSUE TITLE
Deno.Process close()/status()/kill()

### ISSUE THREAD

**Issue by aricart** [denoland/deno#6373]
Deno.Process probably needs a bit more documentation:

- if `close()` is called, `status()` will throw an exception with a bad resource id.
- `kill()` followed by a `status()` works fine
- I would expect `status()` to always work regardless of how the process was terminated.

I would have expected status() to resolve its promise regardless of how the Process is closed/kill or otherwise.

My use of Deno.run() is running a server that I can use for tests. So this creates interesting because if things don't close properly, the tests will fail with resource leaks (love that).

**Comment by caseyhoward** [comment]
I was also wondering what `close()` did since there is no documentation. I want to kill a process after a specified timeout. Do I use `close()` or `kill()`?

**Comment by ry** [comment]
Close releases Deno’s memory associated with the process. So the subprocess will continue to run. Kill actually sends a signal to the subprocess.

**Comment by aricart** [comment]
@ry one thing with close is that it doesn't address closing any of the file descriptors. Noticed that it must be handled by a try/catch to prevent tossing - for example, on some utility code I have I had to:

```typescript
  async stop(): Promise<void> {
    if (!this.stopped) {
      this.stopped = true;
      this.process.stderr?.close();
      this.process.kill(Deno.Signal.SIGKILL);
      this.process.close();
    }
    await this.done;
  }
```

The unexpected thing is that `stderr` had to be closed specifically - even though the close - which is owning it is getting called.

**Comment by martin-braun** [comment]
> Close releases Deno’s memory associated with the process. So the subprocess will continue to run. Kill actually sends a signal to the subprocess.

Thanks for the explanation. Is using `close()` mandatory, though? Shouldn't Deno release memory associated with the process on the end of the scope, automatically?
