### ISSUE TITLE
Cargo build error

### ISSUE THREAD

**Issue by ChaboCode** [denoland/deno#6374]
### Cargo output:
error[E0658]: use of unstable library feature 'matches_macro'
  --> /home/saul/.cargo/registry/src/github.com-1ecc6299db9ec823/deno_lint-0.1.10/src/rules/eqeqeq.rs:37:23
   |
37 |     Expr::Lit(lit) => matches!(lit, Lit::Null(_)),
   |                       ^^^^^^^
   |
   = note: for more information, see https://github.com/rust-lang/rust/issues/65721

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: could not compile `deno_lint`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `deno v1.1.0`, intermediate artifacts can be found at `/tmp/cargo-installRfpSyt`

Caused by:
  build failed

**Comment by crowlKats** [comment]
what rust version you on?

**Comment by ChaboCode** [comment]
1.41.0

**Comment by bartlomieju** [comment]
Please update Rust to `1.43.0` or `1.44.0`

**Comment by rodude123** [comment]
I'm getting the same error but with rust version 1.44.1 any idea. downloaded it from aur using yay tried to build it but failed

**Comment by lucacasonato** [comment]
@rodude123 Please update to rust 1.45

**Comment by rodude123** [comment]
Thanks but just used deno-bin instead
