### ISSUE TITLE
assert-* function not type-safe enough

### ISSUE THREAD

**Issue by wongjiahau** [denoland/deno#6375]
## Steps to reproduce
1. Create a file named `main.test.ts`
```ts
import { assertEquals } from "https://deno.land/std@0.53.0/testing/asserts.ts";
Deno.test('example', () => {
  assertEquals(1, "1")
})
```
2. Run `deno test main.test.ts`

## Expected result
Expected compile error, because number `1` does not equals to string `"1"` as they have different types.

## Actual result
No compile error, but instead got assertion failed error after test run finished.

**Comment by caspervonb** [comment]
assertEquals is a runtime assertion that's asserting that `a == b` which allow for coercion so unknown types has to be allowed.

**Comment by wongjiahau** [comment]
@caspervonb So are you saying that there are cases where user wanted to use `assertEqual` on two values that has different types?

**Comment by actual-size** [comment]
@wongjiahau but in both deno and haskell `a == b` and `assertEquals(a, b)` are typed consistently, this issue/your PR breaks the consistency.

In fact, having `assert(a == b)` and `assertEquals(a, b)` behave differently is surely strictly worse for testing than avoiding a needless comparison of two differently typed things.

**Comment by wongjiahau** [comment]
@actual-size what do you mean when you say "typed consistently"?

**Comment by ry** [comment]
https://github.com/denoland/deno/pull/6376#issuecomment-646580104
