### ISSUE TITLE
Log empty line would print "{msg}" unexpected.

### ISSUE THREAD

**Issue by zhengxiaoyao0716** [denoland/deno#6380]
Sometimes we just want to print an empty line, I used `logger.info("");` but it would print a line unexpected like "INFO {msg}".
![image](https://user-images.githubusercontent.com/12682063/85129624-fe882e00-b265-11ea-91fb-c946f5f6e2c9.png)

What I really need is just output an empty line, like this:
```
INFO fin.
INFO 
INFO fin.2
```

I found the problem is caused by [this line](https://github.com/denoland/deno/blob/master/std/log/handlers.ts#L44), as the code commenting above, it would not replace the `{msg}` placeholder where **missing values**, but we know that in javascript, `!value`  not only means `missing values`, it can also passed when the value is an empty string.

If it is works as designed, maybe we need some other way to output an empty line? or just used `console.log("");`?

**Comment by cknight** [comment]
Most likely a bug.  I'm happy to look at a fix for this.

**Comment by bartlomieju** [comment]
Resolved in #6381
