### ISSUE TITLE
Service Worker API support

### ISSUE THREAD

**Issue by mfulton26** [denoland/deno#6383]
As a developer, I want to be able to write a service worker and use it both in clients (user agents / web browsers) and in servers.

If `deno` adds support for installing service workers with support for `install`, `activate`, `fetch` and other `ServiceWorkerGlobalScope` events then isomorphic service workers become a possibility.

**Comment by nayeemrmn** [comment]
Duplicate of #5957.

**Comment by mfulton26** [comment]
good call, as long as #5957 includes more than just the `fetch` event then I think we can close this issue in lieu of that one

thank you

**Comment by kitsonk** [comment]
Duplicate of #5957

**Comment by mfulton26** [comment]
@kitsonk will #5957 include `install` and `activate` events too or just `fetch`?

**Comment by kitsonk** [comment]
I will make that clear.

**Comment by mfulton26** [comment]
thank you!
