### ISSUE TITLE
`jsx pragma` not works.

### ISSUE THREAD

**Issue by zhengxiaoyao0716** [denoland/deno#6396]
I tried `deno bundle -c tsconfig.json ...` and found that custom `jsxFactory` is supported, 
![image](https://user-images.githubusercontent.com/12682063/85203158-4f6b5580-b33e-11ea-81bd-b52093ccbb0d.png)

How ever if we only use [`jsx pragma`](https://babeljs.io/docs/en/babel-plugin-transform-react-jsx#customizing-with-the-classic-runtime) without `jsxFactory` option in `tsconfig.json`, it is unfortunately not works.
![image](https://user-images.githubusercontent.com/12682063/85203168-6316bc00-b33e-11ea-9e49-f94fcf3369db.png)

I think this is an useful feature that we can use different `React-like` frameworks in different source files, can we support for it?

**Comment by wongjiahau** [comment]
Hi @zhengxiaoyao0716, why do you want to un-specify the `jsxFactory` option?

**Comment by zhengxiaoyao0716** [comment]
> Hi @zhengxiaoyao0716, why do you want to un-specify the `jsxFactory` option?

The `jsxFactory` option works on whole project, but sometime people may only want it works for some special files.

**Comment by zhengxiaoyao0716** [comment]
I have some new thinks about this problem, in `deno`, we imported others package used `import "https://xxx/yyy/mod.ts"`, then what would happened if the package `xxx` used some special config but not defined in the `yyy/mod.ts`? for example a `jsxFactory` option in the `tsconfig.json` at the project root?

**Comment by wongjiahau** [comment]
@zhengxiaoyao0716 This might be actually an issue with Deno itself.

**Comment by zhengxiaoyao0716** [comment]
> @zhengxiaoyao0716 This might be actually an issue with Deno itself, not just related to `jsxFactory`.

I agree with you, other compiler options defined in `tsconfig.json` may caused same problem too.

In `NodeJS` we resolve it by npm package dependences and configured babel options, however in Deno, it allowed to import module from single remote file without package.json, so I think maybe the global `tsconfig.json` is not a nice idea, the file-scope progma is more important for Deno then Node.

**Comment by wongjiahau** [comment]
@zhengxiaoyao0716 I think it's better to create another issue regarding this problem (i.e. allow module to have their own tsconfig)

**Comment by zhengxiaoyao0716** [comment]
I create new issue for [this problem](https://github.com/denoland/deno/issues/6396#issuecomment-647102776), but now please let us back to the problem of `jsxFactory`.

I think maybe it's not an elegant designing that compile `jsx` and `tsx` with `React.createElement` as default factory and then support some way to custom the `jsxFactory`, it looks like a legacy compromise that limited other package who using jsx syntax.

Since `jsx` it not only used in `React`, as a universal solution maybe we should no longer inherit the  default `jsxFactory` behavour? If `Deno` want to support not only ``TypeScript` but `jsx` and `tsx` in default, then it should not bundle with `React`. Maybe we should allow programer to declare there `jsxFactory` more flexible, for example use `module.jsxFactory = React.createElement`?

Of cause it is a risks topic, we have already experienced the confusion process from `AMD`, `CMD` and `CommonJS` to `es-module` and `dynamic imports`, hopes the same confusion would not happened on `jsxFactory` compiler option.

**Comment by kitsonk** [comment]
We should support the `@jsx` pragma. (ref: https://www.typescriptlang.org/docs/handbook/jsx.html#factory-functions) I am not sure why it is working.  We didn't specifically try to disable it.

**Comment by zhengxiaoyao0716** [comment]
> 我们应该支持实用主义。（参考[：https://www.typescriptlang.org/docs/handbook/jsx.html#factory-functions）](https://www.typescriptlang.org/docs/handbook/jsx.html#factory-functions)我不知道为什么它工作。我们没有特别尝试禁用它。`@jsx`

I'm not sure maybe it is an problem of `tsc`. I use `tsc -jsx react App.tsx` and the `jsx progma` not works  too. Maybe it's only works for babel?

**Comment by zhengxiaoyao0716** [comment]
@kitsonk  I found the reason,  just put the `/* @jsx */` into the first line fix my problem...

![image](https://user-images.githubusercontent.com/12682063/85264067-b3a72a00-b4a2-11ea-9b1a-dd6085f20c02.png)
