### ISSUE TITLE
Versioning mismatching between std and deno binary

### ISSUE THREAD

**Issue by dionjwa** [denoland/deno#6407]
The docs say that "These [std]  modules are tagged in accordance with Deno releases.":

![image](https://user-images.githubusercontent.com/260221/85211821-b0286d00-b301-11ea-86d8-b4f03ad60a92.png)

However, the latest deno release (`v1.1.1`) goes with the std release of `0.58.0`:

![image](https://user-images.githubusercontent.com/260221/85211811-a43cab00-b301-11ea-8c14-12753121c9a0.png)

So I'm guilty of this myself, a project has multiple moving parts, and getting things in sync is work.

But could we? It's just another confusing extra thing to have to research (why isn't this module compiling when everything is latest). Can you just re-release the std module with the same version tag as the binary? That way, us users can sync things and make sure versions match. No-one will care if there's actually no difference between `std` versions if it was just a `deno` binary bugfix release, but having to do mental work to match up random versions is frustrating.

Also, deno is a great idea, for devops stuff the url import is the magic I've been looking for. Keep up the great work!

**Comment by lucacasonato** [comment]
That is an issue with the `//std/README.md`.

It will happen eventually: 
> Deno's standard modules (https://deno.land/std/) are not yet stable. We currently version the standard modules differently from the CLI to reflect this. Note that unlike the Deno namespace, the use of the standard modules do not require the --unstable flag (unless the standard module itself makes use of an unstable Deno feature).

From https://deno.land/manual/runtime/stability#standard-modules
