### ISSUE TITLE
@deno-types doesn't allow for inline comments that come after the path to the d.ts is specified

### ISSUE THREAD

**Issue by Grunet** [denoland/deno#6419]
I was trying to leave an inline comment about how to workaround [this issue](https://github.com/denoland/deno/issues/6338) with "deno bundle" and @deno-types, like this

```ts
// @deno-types="https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/deab75bde42b5a82aeb951f5a2edaa09922853f4/types/cheerio/index.d.ts" //Needs to be temporarily removed when bundling until https://github.com/denoland/deno/issues/6338 is fixed
```

But I ran into this error 

```cmd
error: Import 'https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/deab75bde42b5a82aeb951f5a2edaa09922853f4/types/cheerio/index.d.ts%22%20/Needs%20to%20be%20temporarily%20removed%20when%20bundling%20until%20https:/github.com/denoland/deno/issues/6338%20is%20fixed' failed: 404 Not Found
```

I think the issue is that [swc_util.rs](https://github.com/denoland/deno/blob/db70b77e4b6a24814e0045f7f6afcf77730878a7/cli/swc_util.rs)::get_deno_types is currently assuming that nothing will come after the closing quotation mark for the path to the d.ts

![image](https://user-images.githubusercontent.com/29322882/85243822-7beba400-b408-11ea-8397-3dc051903ed4.png)

The workaround of putting the comment on its own line above the @deno-types directive is very straightforward though.

**Comment by bartlomieju** [comment]
I think it's reasonable to expect only `// @deno-types=<url>` directive without any additional comments. @kitsonk WDYT?

**Comment by kitsonk** [comment]
Other TypeScript pragma allow additional text after the pragma.  There is clearly a pattern to figure out when the pragma stops, so I don't know why we wouldn't allow it.  Sometimes is is valuable to add commentary to why something is there.
