### ISSUE TITLE
Support DOM in Custom TypeScript Compiler Options

### ISSUE THREAD

**Issue by bsunderhus** [denoland/deno#6422]
Seems like right now I couldn't write a piece of code like this:

![image](https://user-images.githubusercontent.com/5483269/85267846-07e7e500-b476-11ea-933c-d44c146f0044.png)

Adding support for the `DOM` lib in the *tsconfig* simply doesn't work. Is this an expected behaviour?

# Version
deno 1.1.1
v8 8.5.104
typescript 3.9.2

**Comment by kitsonk** [comment]
You should be able to specify:

```js
{
  "compilerOptions: {
    "lib": [ "dom", "deno.ns" ]
  }
}
```

In a `tsconfig.json` and use it via `deno run --config tsconfig.json`.

**Comment by bsunderhus** [comment]
thx for the advice @kitsonk, that alone seems to solve the problems regarding the deno runtime, but unfortunately it doesn't help much with VSCode. I still have an error outlined under the unknown `document` saying:

> Cannot find name 'document'. Do you need to change your target library? Try changing the `lib` compiler option to include 'dom'

Funny because I do have the `dom` specified in my `tsconfig`.

Anyway. What solved for me was using the triple slash directive:

```ts
/// <reference lib="dom" />

if (window.Deno) {
  console.log('hello from deno')
} else {
  const div = document.createElement('div')
  console.log(div)
}
```

Still for me this sounds a bit like a hack... Should I close this?

**Comment by deebloo** [comment]
@bsunderhus I have had issues in the past where vscode just needed a few minutes to "catch up" to config changes. If you restart your IDE or start typing does it fix it?

**Comment by bsunderhus** [comment]
No @deebloo, the problem persists. Anyway, this seems to be more of a [plugin](https://github.com/justjavac/typescript-deno-plugin) problem than deno problem itself, since `deno run` is working properly. I'll be closing this! Thx for the help.

**Comment by rok-star** [comment]
Anyway, is there way to enable DOM api for intellisense while coding in VS Code?

**Comment by kitsonk** [comment]
It works with the vscode_deno canary plugin configured with a tsconfig.json and the proper libs. The canary release will soon become the stable release.
