### ISSUE TITLE
Documentation pages not loading when trying to navigate throught sidebar

### ISSUE THREAD

**Issue by joffarex** [denoland/deno#6429]
This is how it looks like:

![image](https://user-images.githubusercontent.com/41587092/85321378-ace5da80-b4d5-11ea-939e-ab69e13c3906.png)

It only works when i refresh the page. basically when making a get request to url, but when trying to navigate from sidebar, it fails to do that.

**Comment by lucacasonato** [comment]
Duplicate of https://github.com/denoland/deno_website2/issues/719. Or duplicate of https://github.com/denoland/deno_website2/issues/814

**Comment by joffarex** [comment]
Hm. Most likely duplicate of denoland/deno_website2#719

Opened it here because github link in docs took me in this repo/docs.

I'll close it.
