### ISSUE TITLE
deno scripts without an extension raise errors

### ISSUE THREAD

**Issue by aricart** [denoland/deno#6430]
With a shell script like this:
deno-hello.ts:
```typescript
#!/usr/bin/env deno run --allow-all --unstable
// do something cool
```
The program works as expected.

If you rename `deno-hello.ts` to `deno-hello` the result of what you get depends on the state of the deno cache. In some cases, the script continues to run without a problem (expected behavior).

In some cases, you'll get a weird issue like:
`thread 'main' panicked at 'Cached source file doesn't exist', cli/global_state.rs:188:15`

Or some bizarre typescript error:
```
Uncaught SyntaxError: Unexpected token ':'
nc.addEventListener("error", (err: Error): void => {
```

While `deno install` is the correct strategy for registering a script, the throwback is that in some cases it does work correctly until something else happens. If the lack of extension is the problem, it would be more helpful for deno to require that the file extension of the script be .ts or .js.

**Comment by frantisekhanzlikbl** [comment]
The same happens when the file does have an extension, but is invoked through a symlink.

**Comment by proteriax** [comment]
Given TypeScript is a first-class citizen in Deno, I think it’s reasonable that we have a way to write Deno scripts without having an explicit extension by introducing a `--typescript` flag or something like that.

**Comment by piscisaureus** [comment]
This has been fixed

**Comment by jeiea** [comment]
Is it really fixed? I got same error.
```
cmd> deno run a
thread 'main' panicked at 'Cached source file doesn't exist', cli\global_state.rs:196:8
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

cmd> type a
import { rollup } from 'https://unpkg.com/rollup@1.1.2/dist/rollup.browser.es.js';

cmd> deno --version
deno 1.4.1
v8 8.7.75
typescript 4.0.2
cmd> ver
Microsoft Windows [Version 10.0.19041.508]
```

**Comment by kigiri** [comment]
I confirm having this issue invoking a script with a symlink.

**Comment by kitsonk** [comment]
> I confirm having this issue invoking a script with a symlink.

Could you provide more details.

**Comment by jeiea** [comment]
I cannot reproduce this with deno 1.4.2.
