### ISSUE TITLE
[bug]: fails to create worker

### ISSUE THREAD

**Issue by alexanderGalushka** [denoland/deno#6431]
worker relative path is `./workers/myworker`

works with v0.56.0
fails with v0.58.0

`error: Uncaught URIError: invalid URL: relative URL without a base`

**Comment by nayeemrmn** [comment]
@alexanderGalushka Relative URLs for worker module specifiers are not supported: https://deno.land/manual/runtime/workers#workers. What is it supposed to be relative to?
