### ISSUE TITLE
SharedArrayBuffer not works

### ISSUE THREAD

**Issue by tigercosmos** [denoland/deno#6433]
Sample code looks like

main.js
```js
const u32Buf = new SharedArrayBuffer(2 * Uint32Array.BYTES_PER_ELEMENT);
const u32Arr = new Uint32Array(u32Buf);

const worker = new Worker(new URL("./worker.js", import.meta.url).href, { type: "module" });

u32Arr[0] = 1

worker.postMessage({
    buf: u32Buf,
});
```

worker.js
```js
self.onmessage = function (e) {
    const data = e.data;
    const u32Arr = new Uint32Array(data.buf);

    console.log(u32Arr[0])
};
```

The result is:
```shell
$ deno run --allow-read main.js
undefined                         
```
where I expect to get `1` instead of `undefined` 

Test in:
- Deno 1.1.1
- Windows 10

**Comment by kitsonk** [comment]
Yes, currently the structured cloning and shared array buffers don't work in workers.  Structured cloning is covered by #3557 but we don't specifically call out the lack of support for `SharedArrayBuffer` in that issue.

**Comment by inteon** [comment]
This can be implemented by adding the `get_shared_array_buffer_id` and `get_shared_array_buffer_from_id` functions in:
https://github.com/denoland/deno/blob/ac8ea823f5867e35715051176b6a2ff145a3afd1/core/bindings.rs#L498-L561

More info on `get_shared_array_buffer_id` and `get_shared_array_buffer_from_id`:
https://docs.rs/rusty_v8/0.22.2/rusty_v8/trait.ValueSerializerImpl.html#method.get_shared_array_buffer_id
https://docs.rs/rusty_v8/0.22.2/rusty_v8/trait.ValueDeserializerImpl.html#method.get_shared_array_buffer_from_id
