### ISSUE TITLE
suggestion: deno lint should output the count of checked files

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#6435]
Due to the speed of `deno lint` it is sometimes difficult to judge if it has actually picked up all of my files to lint. I think we should print a `Checked x files` message before exiting.

**Comment by caspervonb** [comment]
Behind -v flag? silence by default is the UNIX way...

**Comment by Qu4k** [comment]
I think the behaviour should be somewhat consistent with `deno fmt`

**Comment by lucacasonato** [comment]
I guess behind a `-v` flag would be fine.

**Comment by magurotuna** [comment]
This feature seems so kind to the users. I'd like to implement it.

### Design

#### input

```bash
# (1) normal usage
deno lint --unstable -v
deno lint --unstable --verbose

# (2) output as JSON
deno lint --unstable -v --json

# (3.1) read from stdin
cat file.ts | deno lint --unstable -v -

# (3.2) read from stdin, with json flag
cat file.ts | deno lint --unstable -v --json -
```

#### output

```bash
# (1) and (3.1)
(no-explicit-any) `any` type is not allowed
let b: any;
       ~~~
    at /foo/bar/main.ts:1:7

Found 1 problem

Checked 1 file

# (2) and (3.2)
{
  "diagnostics": [
    {
      "location": {
        "line": 1,
        "col": 7
      },
      "filename": "/tmp/denolinttmp/main.ts",
      "message": "`any` type is not allowed",
      "code": "no-explicit-any",
      "line_src": "let b: any;",
      "snippet_length": 3
    }
  ],
  "errors": []
}

Checked 1 file
```

Almost the same for `deno fmt`.

**Comment by magurotuna** [comment]
On second thoughts, `Checked x files` after a result in JSON would be sort of ugly...
`--verbose` flag should work fine only when `--json` flag doesn't exist, I guess.
