### ISSUE TITLE
Linter and formatter disagree on non camelCase identifiers

### ISSUE THREAD

**Issue by caspervonb** [denoland/deno#6436]
Linter wont accept the following;

```typescript
const instance = new WebAssembly.Instance(module, {
  wasi_snapshot_preview1: wasi.exports,
});
```

Easy fix, just change it into what the linter want and we end up with:
```typescript
const instance = new WebAssembly.Instance(module, {
  "wasi_snapshot_preview1": wasi.exports,
});
```

But the formatter won't accept that, so it changes it back into this:
```typescript
const instance = new WebAssembly.Instance(module, {
  wasi_snapshot_preview1: wasi.export
});
```

Linter in this context is eslint as the CI expects to run it; deno-lint is not as strict **yet**.

**Comment by bartlomieju** [comment]
Have you tried adding `// eslint-disable-next-line camelcase`?

**Comment by caspervonb** [comment]
> Have you tried adding // eslint-disable-next-line camelcase?

I just went for eslint-disable *for now*; as ignore pragmas would be littered all over the place.

**Comment by ry** [comment]
Ideally I guess dprint (cc @dsherret) shouldn't unquote object keys that have underscores in them? I would find that behavior a bit surprising tho.

So maybe instead should change the lint rule to not require quoted keys?

**Comment by ry** [comment]
Oh sorry - this is prettier. (Which we should get rid of ASAP.)

**Comment by dsherret** [comment]
@caspervonb I think this can be closed now.

**Comment by caspervonb** [comment]
Indeed, we now use dprint so this doesn't occur anymore 👍
