### ISSUE TITLE
Import Module w/ JavaScript

### ISSUE THREAD

**Issue by Zacharys-Hackery** [denoland/deno#6437]
Hello,

After looking around in `deno.land` and through the `issues`, I have not been able to find an answer to this question.
It is possible to import Deno modules using TypeScript, but would there be any way to also do the same thing using JavaScript? Because I know you can use Deno's runtime APIs through/with plain JS.

_If it is possible, I would not mind at all helping put the information in the documentation!_

**Comment by nayeemrmn** [comment]
Maybe I'm not understanding, but just import a file with JS extension or a URL with `text/javascript` content type? What documentation are you looking for besides
> A **secure** runtime for **JavaScript** and **TypeScript**.

**Comment by Zacharys-Hackery** [comment]
Sorry - you were close, though. I meant import a Deno TypeScript module/url with a JavaScript file (I know you can import JavaScript with JavaScript). As for tthe documentation, just a little explanation of how to do it just like it says with importing via TypeScript.

**Comment by nayeemrmn** [comment]
JS modules and TS modules can import each other, yes. I'm still not 100% sure if that's what you're asking. Questions like this are better suited for the Discord https://discord.gg/deno or experimenting yourself.

**Comment by Zacharys-Hackery** [comment]
Yes that is what I'm asking. Thank you for letting me know!
