### ISSUE TITLE
`NotFound` error is very unhelpful

### ISSUE THREAD

**Issue by rix0rrr** [denoland/deno#6439]
The default Deno NotFound error:

```
error: Uncaught NotFound: No such file or directory (os error 2)
```

Is supremely unhelpful. Yes, I probably should have added more logging or whatever, but I would really have preferred to see *what* file my script was expecting to find and was missing, diagnose the issue and continue, than that I have to guess at it or add `console.log()`s to find out.

Is it that hard to put the missing path in the error message? It would really help a lot.

**Comment by ry** [comment]
duplicate of https://github.com/denoland/deno/issues/6057
