### ISSUE TITLE
Module loading perf can be improved by using http2 push

### ISSUE THREAD

**Issue by nmalyschkin** [denoland/deno#6445]
Imagine the following application:
```js
// main.mjs
import test from "./test.mjs";

// test.mjs
import test2 from "./test2.mjs";

// test2.mjs
import sleep from "./sleep.mjs";
```

This is a sequential import and the module loading sequence will look something like this:
![http2_1](https://user-images.githubusercontent.com/44928856/85435745-36ee7b80-b588-11ea-9015-d7b93e2a5a13.png)

You might think: yeah, this is to be expected and there is no way we could do better, since we learn about the next import after we loaded the previous dependency!

What if I tell you, that we can achieve this:
![http2_2](https://user-images.githubusercontent.com/44928856/85435979-93519b00-b588-11ea-8d3b-bb86e443353c.png)

While we don't know whole dependency tree and can resolve it one layer at a time, the server can do it for us! Knowing the whole (declarative) dependency tree the server can HTTP/2 PUSH all dependencies at once, reducing the count of round trips to 1.

### Deno can work on two fronts here:
1. Using HTTP/2 for loading modules and enabling the server to PUSH modules to the module cache. This can increase load perf
2. Expose the dependency tree resolve function (which is written in Rust) to the Javascript environment, enabling HTTP/2 server to push all dependencies for a requested module.

**Comment by kitsonk** [comment]
Modules are not loaded or resolved in JavaScript and so exposing the resolution logic wouldn't be meaningful.  When a JavaScript module needs to be loaded, Rust instructs v8 to do its two pass dependency analysis and the dependencies are identified before the module is loaded and are requested in parallel via Rust and tokio.  If any of those dependencies are TypeScript, then a full dependency graph is determined in Rust using swc and all off the modules are resolved which are not in the cache and sent to the TypeScript compiler for compilation.

Supporting HTTP/2 connections for servers to more efficiently server module is certainly worth investigating.

**Comment by bartlomieju** [comment]
AFAIK `reqwest` (the HTTP client `deno` uses) automatically tries to use HTTP/2 when possible. So I think this issue can be considered resolved.
