### ISSUE TITLE
identifier in strict mode

### ISSUE THREAD

**Issue by Bidek56** [denoland/deno#6448]
When trying to import:
`import {Button, Grid} from 'https://cdn.pika.dev/@material-ui/core@^4.10.2';` 

I get:

`error: 'implements', 'interface', 'let', 'package', 'private', 'protected',  'public', 'static', or 'yield' cannot be used as an identifier in strict mode at https://cdn.pika.dev/-/csstype@v2.6.10-9lGFwmNeuxj9xXremWKA/dist=es2019,mode=exports/index.d.ts:1:7,Expected Comma, got Some(Word(StandardLonghandProperties)) at https://cdn.pika.dev/-/csstype@v2.6.10-9lGFwmNeuxj9xXremWKA/dist=es2019,mode=exports/index.d.ts:1:17`

Is this a deno or csstype issue? Thx

**Comment by kitsonk** [comment]
something strange is happening... it looks like Deno is treating the `.d.ts` file as JavaScript and trying to load it in V8, which it shouldn't be doing.

`deno --version` please...

**Comment by Bidek56** [comment]
I using Deno 1.1.1. thanks

**Comment by Bidek56** [comment]
So different CDNs produce different errors.
`import {AppBar} from 'https://unpkg.com/@material-ui/core@4.10.2'` results in:
`error: Uncaught SyntaxError: The requested module 'https://unpkg.com/@material-ui/core@4.10.2' does not provide an export named 'AppBar'`

but the export is clearly there:
`Object.defineProperty(exports, "AppBar", {
  enumerable: true,
  get: function get() {
    return _AppBar.default;
  }
});`

**Comment by Bidek56** [comment]
So far I have tried all the React UI libraries (Material-UI, Ant, react-select, react-md, react-bootstrap, etc..) and none of them work with deno.

**Comment by lucacasonato** [comment]
> but the export is clearly there: `Object.defineProperty(exports, "AppBar", { enumerable: true, get: function get() { return _AppBar.default; } });`

This is not an ES Module style export, so it doesn't get picked up by Deno. Deno can only use ES Modules.

**Comment by MarkoCen** [comment]
experienced the exactly same issue with Deno 1.1.1, it is working if I directly import `csstype`

```ts
// index.ts
import * as csstype from "https://cdn.pika.dev/csstype@^2.6.10";

console.log(csstype);
```

output:
```bash
deno run --allow-net index.ts 

Download https://cdn.pika.dev/csstype@^2.6.10
Download https://cdn.pika.dev/-/csstype@v2.6.10-9lGFwmNeuxj9xXremWKA/dist=es2019,mode=types/index.d.ts
Download https://cdn.pika.dev/-/csstype@v2.6.10-9lGFwmNeuxj9xXremWKA/dist=es2019/csstype.js
Compile file:///Users/markocen/repos/345tool-blog-examples/build-react-app-with-deno-and-pick-cdn/index.ts
Module { default: null, Symbol(Symbol.toStringTag): "Module" }
```

**Comment by sholladay** [comment]
A Pogo user reported this same problem in https://github.com/sholladay/pogo/issues/35. I haven't been able to reproduce it yet, but they are using Deno 1.1.1 on Windows 10.

**Comment by FredKSchott** [comment]
See here for some extra relevant debug info: https://github.com/pikapkg/cdn/issues/19#issuecomment-648397001

**Comment by kitsonk** [comment]
Yeah, I don't think they are related as well...  The other one has a `.d.ts` that isn't compatible with Deno for various reasons, this other one seems like something is going a bit odd that shouldn't which needs to be investigated.

**Comment by FredKSchott** [comment]
import {Button, Grid} from 'https://cdn.pika.dev/@material-ui/core@^4.10.2' works for me in Deno 1.1.0

Update: https://cdn.pika.dev/-/csstype@v2.6.10-9lGFwmNeuxj9xXremWKA/dist=es2019,mode=exports/index.d.ts is a URL that should only ever be used to serve JS. Not sure why Deno would be loading that as a type.

**Comment by kitsonk** [comment]
Ok, I am on master and getting something different, still doesn't work...

**test.ts**

```
import { Button, Grid } from "https://cdn.pika.dev/@material-ui/core@^4.10.2";

console.log(Button, Grid);
```

And then:

```
$ deno run test.ts
error: Import 'https://cdn.pika.dev/-/prop-types@v15.7.2-zP4vfWJ00Q8BlfFeEia7/dist=es2019,mode=exports/index.d.ts' failed: 404 Not Found
Imported from "https://cdn.pika.dev/prop-types/dist=es2019,mode=types/index.d.ts:23"
```

**Comment by FredKSchott** [comment]
Ah you're right, I can reproduce with the `--reload` flag. That's a bug introduced in our latest exports map work, I just pushed out a fix and can no longer reproduce. Thanks for catching!

**Comment by Bidek56** [comment]
I wish I could say that it works but when I try to use it like:

```
import {Paper} from "https://cdn.pika.dev/@material-ui/core@^4.10.2";
const NavBar: React.FC = (): JSX.Element => {
    return (
        <Paper>
        </Paper>
    );
}
```

I get: https://reactjs.org/docs/error-decoder.html/?invariant=321

**Comment by FredKSchott** [comment]
Are you also importing React from the Pika CDN? React gets made if you have two copies running on the same site.

**Comment by Bidek56** [comment]
I tried to import React from Pika using: `import React from 'https://cdn.pika.dev/react/^16.13.1' unfortunately it throws all kinds of errors.
Using "https://dev.jspm.io/react@16.13.1" works fine.

**Comment by FredKSchott** [comment]
If  you can share an example of what errors you were seeing, or code that was broken, I'd love to see it! I can't reproduce when I run that import statement in Deno, both the package code and its types seem to load fine.

**Comment by Bidek56** [comment]
I just posted a sample React [project](https://github.com/Bidek56/deno-material)
I am seeing these errors when I run: `deno run --allow-net --allow-read server.tsx` 

error: TS2304 [ERROR]: Cannot find name 'Comment'.
export type InsertionPoint = string | HTMLElement | Comment
                                                    ~~~~~~~
    at https://cdn.pika.dev/-/jss@v10.1.1-H35eD3Fwv3D86TSaz8bf/dist=es2019,mode=types/src/index.d.ts:37:53

TS2304 [ERROR]: Cannot find name 'CSSStyleRule'.
  setProperty(cssRule: HTMLElement | CSSStyleRule, prop: string, value: JssValue): boolean
                                     ~~~~~~~~~~~~
    at https://cdn.pika.dev/-/jss@v10.1.1-H35eD3Fwv3D86TSaz8bf/dist=es2019,mode=types/src/index.d.ts:108:38

TS2304 [ERROR]: Cannot find name 'CSSStyleRule'.
  getPropertyValue(cssRule: HTMLElement | CSSStyleRule, prop: string): string
                                          ~~~~~~~~~~~~
    at https://cdn.pika.dev/-/jss@v10.1.1-H35eD3Fwv3D86TSaz8bf/dist=es2019,mode=types/src/index.d.ts:109:43

TS2304 [ERROR]: Cannot find name 'CSSStyleRule'.
  removeProperty(cssRule: HTMLElement | CSSStyleRule, prop: string): void
                                        ~~~~~~~~~~~~
    at https://cdn.pika.dev/-/jss@v10.1.1-H35eD3Fwv3D86TSaz8bf/dist=es2019,mode=types/src/index.d.ts:110:41

TS2304 [ERROR]: Cannot find name 'CSSStyleRule'.
  setSelector(cssRule: CSSStyleRule, selectorText: string): boolean
                       ~~~~~~~~~~~~
    at https://cdn.pika.dev/-/jss@v10.1.1-H35eD3Fwv3D86TSaz8bf/dist=es2019,mode=types/src/index.d.ts:111:24

TS2304 [ERROR]: Cannot find name 'CSSRule'.
  insertRule(rule: Rule): false | CSSRule
                                  ~~~~~~~
    at https://cdn.pika.dev/-/jss@v10.1.1-H35eD3Fwv3D86TSaz8bf/dist=es2019,mode=types/src/index.d.ts:115:35

TS2304 [ERROR]: Cannot find name 'CSSRule'.
  deleteRule(cssRule: CSSRule): boolean
                      ~~~~~~~
    at https://cdn.pika.dev/-/jss@v10.1.1-H35eD3Fwv3D86TSaz8bf/dist=es2019,mode=types/src/index.d.ts:116:23

TS2304 [ERROR]: Cannot find name 'CSSRule'.
  replaceRule(cssRule: CSSRule, rule: Rule): false | CSSRule
                       ~~~~~~~
    at https://cdn.pika.dev/-/jss@v10.1.1-H35eD3Fwv3D86TSaz8bf/dist=es2019,mode=types/src/index.d.ts:117:24

TS2304 [ERROR]: Cannot find name 'CSSRule'.
  replaceRule(cssRule: CSSRule, rule: Rule): false | CSSRule
                                                     ~~~~~~~
    at https://cdn.pika.dev/-/jss@v10.1.1-H35eD3Fwv3D86TSaz8bf/dist=es2019,mode=types/src/index.d.ts:117:54

TS2304 [ERROR]: Cannot find name 'CSSRule'.
  indexOf(cssRule: CSSRule): number
                   ~~~~~~~
    at https://cdn.pika.dev/-/jss@v10.1.1-H35eD3Fwv3D86TSaz8bf/dist=es2019,mode=types/src/index.d.ts:118:20

TS2304 [ERROR]: Cannot find name 'CSSRuleList'.
  getRules(): CSSRuleList | void
              ~~~~~~~~~~~
    at https://cdn.pika.dev/-/jss@v10.1.1-H35eD3Fwv3D86TSaz8bf/dist=es2019,mode=types/src/index.d.ts:119:15

TS2304 [ERROR]: Cannot find name 'CSSStyleDeclaration'.
    styles: CSSStyleDeclaration;
            ~~~~~~~~~~~~~~~~~~~
    at https://cdn.pika.dev/-/popper.js@v1.16.1-lts-SitivdNweb3zL853sPMe/dist=es2019,mode=types/index.d.ts:107:13

TS2304 [ERROR]: Cannot find name 'CSSStyleDeclaration'.
    arrowStyles: CSSStyleDeclaration;
                 ~~~~~~~~~~~~~~~~~~~
    at https://cdn.pika.dev/-/popper.js@v1.16.1-lts-SitivdNweb3zL853sPMe/dist=es2019,mode=types/index.d.ts:108:18

TS2304 [ERROR]: Cannot find name 'Node'.
    referenceNode?: Node;
                    ~~~~
    at https://cdn.pika.dev/-/popper.js@v1.16.1-lts-SitivdNweb3zL853sPMe/dist=es2019,mode=types/index.d.ts:136:21

TS2304 [ERROR]: Cannot find name 'ClientRect'.
    getBoundingClientRect(): ClientRect;
                             ~~~~~~~~~~
    at https://cdn.pika.dev/-/popper.js@v1.16.1-lts-SitivdNweb3zL853sPMe/dist=es2019,mode=types/index.d.ts:138:30

TS2686 [ERROR]: 'React' refers to a UMD global, but the current file is a module. Consider adding an import instead.
        <Paper>
         ~~~~~
    at file:///C:/Users/deno-material/src/NavBar.tsx:10:10

Found 16 errors.

Any help would be appreciated. Thx

**Comment by FredKSchott** [comment]
Make sure that you've added the "dom" lib to your project tsconfig. I believe everything above is included in that.

See: https://github.com/denoland/deno/issues/3799

**Comment by Bidek56** [comment]
I would like to do: `deno run --allow-net --allow-read -c .\tsconfig.json server.tsx`
unfortunately all kinds of other errors appear. :(

**Comment by FredKSchott** [comment]
See my last comment, you need to add "dom" to your `tsconfig.json`
