### ISSUE TITLE
deno upgrade returns non-zero exit code when already at latest release

### ISSUE THREAD

**Issue by wperron** [denoland/deno#6461]
This is a really small issue but when running `deno upgrade` with no arguments while already being at the latest release, the command exits with an exit code 1. I think it should return an exit code 0 in this scenario as it better matches the idempotent behavior of the command.

**Comment by wperron** [comment]
Did a bit of research and found that the exit code 1 was put it place in commit abbf0339c. We can clearly see the same condition in the before and after, but the after has that `std::process::exit(1)` that wasn't there before and I can't find information in the pull request associated (#5156) as to why that was put in there. 

@crowlKats as the author of that commit, do you remember why that was implemented that way?

**Comment by crowlKats** [comment]
Oh hmm cant remember, must be a mistake i guess. i can have this changed together in #6352 if that's alright

**Comment by wperron** [comment]
I was looking at it, doesn't seem really hard to fix, but I don't think I'm confident enough in Rust to add a meaningful test for this case, so sure, by all means go ahead!
