### ISSUE TITLE
Fmt removes brackets from left side of assignment

### ISSUE THREAD

**Issue by littletof** [denoland/deno#6477]
When formatting this sample code:

```ts
const x: { [key: string]: string } = {};

(x.test as unknown) = 6;
```

`fmt` removes the brackets from the casting, making the code not compile:

![image](https://user-images.githubusercontent.com/32012862/85745982-688d5100-b706-11ea-81f5-d3ca78808e1e.png)
![image](https://user-images.githubusercontent.com/32012862/85746092-7e027b00-b706-11ea-9a48-65f658abbbd4.png)

**Comment by bartlomieju** [comment]
CC @dsherret

**Comment by dsherret** [comment]
Interesting. I didn't know people could write that code. I opened https://github.com/swc-project/swc/issues/861 and once that's resolved I'll figure out how to solve this in dprint-plugin-typescript.

@littletof for now, you can add a `// deno-fmt-ignore-file` comment to that file or `// deno-fmt-ignore` comment to the statement to ignore formatting

**Comment by littletof** [comment]
@dsherret Thanks, `// deno-fmt-ignore` works for now.
Well, didn't plan to use it either, but casting the value itself to the type I need would be more problematic in my original case 😄
