### ISSUE TITLE
Deno.realPath() does not seem to be working as expected 

### ISSUE THREAD

**Issue by JustinR93** [denoland/deno#6479]
I'm trying to use `Deno.realPath()` and I get the following error no matter how I enter the path to the directory
`Error: The filename, directory name, or volume label syntax is incorrect.`

I've tried the following formats to find the directory
`Deno.realPath("./api")`
`Deno.realPath("/api")`
`Deno.realPath("\\api")`
`Deno.realPath(".\\api")`
`Deno.realPath('${Deno.cwd()}/api')`
`Deno.realPath('${Deno.cwd()}\\api')`

OS: Window 10 and Linux (Pop-os)
Deno Version: 1.1.1
TypeScript: 3.9.5
Repo: https://github.com/bfgcoding/xenus

**Comment by ry** [comment]
I wonder if this is a problem with the path being interpreted as a URL again? https://github.com/denoland/deno/issues/6401

**Comment by actual-size** [comment]
@ry Don't think it is, I never touched `realPath` and it doesn't seem to interact with any of the parts that I did.

**Comment by caspervonb** [comment]
Seems like we had no unit tests for this on Windows until https://github.com/denoland/deno/pull/6463 landed and even with that the coverage is very weak.

**Comment by caspervonb** [comment]
Missing piece of information; what is the working directory?

**Comment by JustinR93** [comment]
I'm sorry all I'm an idiot. 

Everything is working fine I made some mistakes in my code, main one being I never awaited my build function to finish so I had a full path from `Deno.realPath()` which then made `Deno.chdir()` break which was throwing the error above. I'm sorry for all the inconvenience this was just a simple EBKAC error.

Thank you all

**Comment by caspervonb** [comment]
No worries; glad you figured it out!
