### ISSUE TITLE
Can console be nonblocking?

### ISSUE THREAD

**Issue by mohsen1** [denoland/deno#648]
It's likely I'm asking this question because I don't have a good understanding of how Operation Systems and I/O work!

A problem that occurs in Node is that printing large log statements will freeze the program. Can we make console printing async in deno?

**Comment by ry** [comment]
@mohsen1 I'd rather keep it synchronous for debugging now. In the future I would be open to changing that...

**Comment by NewLunarFire** [comment]
@ry @mohsen1 I think console should stay synchronous as it is elsewhere. I think we could have asynchronous console reading / writing through stdin and stdout streams with the Reader and Writer interfaces.

**Comment by MKRhere** [comment]
> as it is elsewhere

One thing to note here is that Chrome has async logging, at least for objects. They don't resolve until you expand them. But since you can't do that in the terminal, so that's there.

> I think we could have asynchronous console reading / writing through stdin and stdout streams

I agree with this part.

**Comment by kt3k** [comment]
Now we have deno.stdout.write() and it's async.

**Comment by bartlomieju** [comment]
I think we can close this @ry
