### ISSUE TITLE
Deno.watchFs recursive

### ISSUE THREAD

**Issue by Bidek56** [denoland/deno#6485]
Should this code generate  events for sub directories? If not what does the **recursive** do? Thx
```
const watcher = Deno.watchFs(Deno.cwd(), { recursive: true});

for await (const event of watcher) {
  console.log(">>>> event", event);
  // { kind: "create", paths: [ "/foo.txt" ] }
}
```

**Comment by ry** [comment]
Yes that's what the recursive option does.

**Comment by Bidek56** [comment]
I do not believe it works. Modifying any files in the sub-directory does not generate an event.

**Comment by Bidek56** [comment]
@bartlomieju Do you see the recursive option working correctly? Thx

**Comment by Bidek56** [comment]
This seems to be Ubuntu 20.04 on WSL2 issue only, it works on Windows and Linux. Thx
