### ISSUE TITLE
Lock file not supported by `deno bundle`

### ISSUE THREAD

**Issue by implicitdef** [denoland/deno#6491]
`--lock <FILE>` and `--lock-write` options are supported by `deno run`, `deno cache`, but not `deno bundle`. 
I don't see why, I think it should. Probably `deno test` too, maybe `deno doc` as well ?
In short, all methods that may fetch remote modules should offer to check the lock-file or overwrite it.

This is the workflow I had in mind :

```
# Create lock file the first time
deno cache --lock=lock.json --lock-write index.ts

# Then work locally everyday with this command
deno run --lock=lock.json index.ts

# then I want to create a bundle that I'll send in production
# I'll use the lock file to be sure of what I'm bundling
deno bundle --lock=lock.json index.ts dist/bundle.js
# error: Found argument '--lock' which wasn't expected, or isn't valid in this context

# For now we can do this in two steps, I thinks it's equivalent ?
deno cache --lock=lock.json index.ts
deno bundle index.ts dist/bundle.js
```

**Comment by kitsonk** [comment]
We should support consumption of lock files with `bundle`.

**Comment by bartlomieju** [comment]
Marking as "good first issue". Here's a gist of what needs to be done to implement this feature:
- in `cli/flags.rs` add `lock_arg()` and `lock_write_arg()` to `bundle` command - see `cache_subcommand` for example
- add test in `cli/flags.rs` exercising these flags
- add integration test in `cli/tests/integration_tests.rs` that exercises failure to bundle when integrity check fails - see `lock_dynamic_imports` test for example

**Comment by TETRA2000** [comment]
Hi! Can I take this?

**Comment by bartlomieju** [comment]
@TETRA2000 sure, go ahead
