### ISSUE TITLE
I need a CORS equivalent method.

### ISSUE THREAD

**Issue by mateusfg7** [denoland/deno#6492]
is there a method equivalent to the node's CORS that I can use in Deno? to limit who can use the server.

**Comment by kamranjon** [comment]
https://deno.land/x/cors

**Comment by kitsonk** [comment]
Questions like these should be asked on Discord: https://discord.gg/deno. The issue tracker is for bugs and feature requests, directly related to Deno, not questions.

**Comment by jsejcksn** [comment]
@kitsonk [Issue templates can be created](https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository) for this repository to help steer people. See [codesandbox/codesandbox-client/issues/new/choose](https://github.com/codesandbox/codesandbox-client/issues/new/choose) for an example. You might consider using the GitHub discussions feature, too.
