### ISSUE TITLE
wanted: Is there a way to get the local ip address ?

### ISSUE THREAD

**Issue by Colin6618** [denoland/deno#6498]
Q: Is there a better way to get the local ip address in a Deno Program ?

Background: I have a simple deno program running on my local environment and I want to get the local IP address for other devices to access. For example, in the common case, `192.168.1.XXX`. (like my phone visits a website running on PC).

I searched the documents, the most relevant item is the interface `Deno.NetAddr` and  but didn't find the exact match.

Although I think it is possible to get the local ipaddress by analysing the output of `Deno.run({cmd: ['ifconfig']})` and it is necessary to consider different types of system.

Is it possible to get it in a more deno way,like `os.networkInterfaces();`

If there's anything I've missed, please let me know.

**Comment by FractalHQ** [comment]
Can you use https://deno.land/x/ip ?

**Comment by Colin6618** [comment]
@FractalHQ Thanks for your advice. I will look into the module.

**Comment by EduardoCotta** [comment]
Hey @Colin6618 did you get to use the https://deno.land/x/ip? The website shows me that there's no module 'ip' uploaded yet. Can you tell me what worked for you to get the local IP Address?

**Comment by joakimunge** [comment]
I came across this issue and just wanted to mention I made this module to solve it while the actual implementation is being worked on. Hope it helps anyone

https://github.com/joakimunge/deno-local-ip

**Comment by Colin6618** [comment]
@joakimunge That's the module that solve the issue!  Thanks.
