### ISSUE TITLE
Proxy Authentication Not Honored In Fetch API for HTTP ( HTTPS Works Though )

### ISSUE THREAD

**Issue by zicklag** [denoland/deno#6502]
When following the basic HTTP fetch example behind an HTTP proxy *with authentication* I am getting a permission denied error from my proxy because the username and password for the proxy server are not being read from the `HTTP_PROXY` environment variables:

    deno run -A fetch.ts http://katharostech.com

**fetch.ts:**
```ts
const url = Deno.args[0];
const res = await fetch(url);

const body = new Uint8Array(await res.arrayBuffer());
await Deno.stdout.write(body);
```

The output is a the HTML for the 403 page of my proxy server.

Interestingly if I just query an HTTPS url instead, it works as expected:

    deno run -A fetch.ts http://katharostech.com

### Deno Version

```
deno 1.1.1
v8 8.5.104
typescript 3.9.2
```

**Comment by jacobgc** [comment]
Are both `HTTP_PROXY` and `HTTPS_PROXY` set?

**Comment by zicklag** [comment]
Yes they are in the format:


**.bashrc:**
```
export http_proxy=http://username:password@123.456.789.10:3128
export https_proxy=$http_proxy
export HTTP_PROXY=$http_proxy
export HTTPS_PROXY=$http_proxy
export ftp_proxy=$http_proxy
export FTP_PROXY=$http_proxy
```

**Comment by zicklag** [comment]
I just found that this is actually happening with plain ol' `reqwests` crate: https://github.com/seanmonstar/reqwest/issues/992. I'm assuming that's what you guys are using. :wink:

**Comment by zicklag** [comment]
I've got a pending fix for the Reqwests crate that should fix this: https://github.com/seanmonstar/reqwest/pull/1021. I haven't tested compiling Deno with it to test for sure, though.

**Comment by zicklag** [comment]
I just verified that https://github.com/seanmonstar/reqwest/pull/1021 fixes this issue. I've finished up the PR added the tests the maintainer requested and I'm thinking it should be merged soon.

**Comment by zicklag** [comment]
It's merged! Now we'll just have to wait for another release of `reqwest`.

**Comment by satyarohith** [comment]
Deno is using the latest version of `reqwest` so I think the issue shouldn't exist any longer.

.@zicklag can we close this issue?

**Comment by zicklag** [comment]
Yep, just tested it and it works! 🎉
