### ISSUE TITLE
Provide .exe and .tar releases

### ISSUE THREAD

**Issue by MarkTiedemann** [denoland/deno#6505]
ref: https://github.com/denoland/deno_install/issues/130

> As witnessed in denoland/deno#5727 and #129, people may not expect Deno to just be an .exe in a .zip.

ref:  https://github.com/denoland/deno_install/issues/153

`tar` is installed by default on Windows 10 since early 2018. `unzip` is not installed by default. Instead, unzipping requires using PowerShell cmdlets or Windows Script Host shenanigans. Providing a `.tar.gz` release would allow custom installations to just curl and untar a Deno release. (Extracting `.tar.xz` doesn't work on Windows. Only `.tar.gz` is supported.)

Not sure about Mac and Linux, but I'd guess that `tar` is more common on those platforms than `zip`.

Note that I'm not saying that we should get rid of `.zip` releases. I'm suggesting to provide binary and `.tar` releases _in addition to_ the `.zip` releases.

**Comment by jsejcksn** [comment]
This is a very reasonable request. The source code is already being released in `zip` and `tar.gz` formats.

I also like that you gave a 👍 to your own post 😄 .

**Comment by MarkTiedemann** [comment]
Just learned that `tar` on Windows supports extracting `.zip` files out of the box.

```
C:\dev>curl -LO https://github.com/denoland/deno/releases/download/v1.1.2/deno-x86_64-pc-windows-msvc.zip
C:\dev>tar xf deno-x86_64-pc-windows-msvc.zip
C:\dev>.\deno -V
deno 1.1.2
```

This removes the paint point of `unzip` not being available.

**Comment by jsejcksn** [comment]
Ref: [How are zlib, gzip and zip related? What do they have in common and how are they different?
](https://stackoverflow.com/a/20765054)
