### ISSUE TITLE
Deno JWT  Token Serialization Method

### ISSUE THREAD

**Issue by vertexinfobase** [denoland/deno#6507]
I have set up jwt token on my deno app. It works perfectly fine in postman but dont know how to serialize the generated token for subsequent requests. Any help will be highly appreciated.

**Comment by lucacasonato** [comment]
Questions like these should be asked on Discord: https://discord.gg/deno. The issue tracker is for bugs and feature requests, directly related to Deno, not questions.

**Comment by timonson** [comment]
@vertexinfobase maybe this helps: https://github.com/timonson/djwt
