### ISSUE TITLE
Docs: building V8 from source - macOS dependencies

### ISSUE THREAD

**Issue by raptazure** [denoland/deno#6513]
In the [building from source](https://deno.land/manual/contributing/building_from_source) document, "Mac users must have XCode installed" isn't that accurate. Having the Command Line Tool installed without XCode itself also works for me. Maybe it is ok to add "run `xcode-select --install` to get the CLT" as another option?

**Comment by ry** [comment]
That sounds correct to me. Doc patches are welcome!
