### ISSUE TITLE
bug(deno/fmt): Multiline destructured objects is formatted wrongly

### ISSUE THREAD

**Issue by wongjiahau** [denoland/deno#6517]
## Steps to reproduce
1. Create a file name `test.ts` with the following content:
```ts
function myFunction({
  options: {
    sing = 2
  } = {},
}: {
  options?: {
    sing?: number;
  };
}) {
}

```
2. Run `deno fmt test.ts`

## Expected result
Expect `test.ts` remain unchanged.

## Actual result
At line 2, `options` is dedented.
```ts
function myFunction({
options: {
    sing = 2
  } = {},
}: {
  options?: {
    sing?: number;
  };
}) {
}

```

## Environment
- deno v1.1.2

**Comment by lucacasonato** [comment]
cc @dsherret

**Comment by nayeemrmn** [comment]
It has nothing to do with the default value, but the nested multiline destructure pattern. Smaller repro:
```js
const {
  errors: {
    NotFound
  },
} = Deno;
```
->
```js
const {
errors: {
    NotFound
  },
} = Deno;
```

**Comment by wongjiahau** [comment]
@dsherret Please kindly refer to @nayeemrmn example for a more minimal reproducible input.
