### ISSUE TITLE
std/http: Allow using getCookies() without ServerRequest

### ISSUE THREAD

**Issue by jakajancar** [denoland/deno#6525]
`getCookies()` only really needs `req.headers.get("Cookie")`.

It would be handy if it didn't require constructing a fake `ServerRequest` just to use the parsing logic, and in addition to

```
export function getCookies(req: ServerRequest): Cookies
```

... it would also support one (or more) of these:

```
export function getCookies(req: { headers: Headers }): Cookies
export function getCookies(headers: Headers): Cookies
export function getCookies(cookieHeader: string): Cookies
```

**Comment by sholladay** [comment]
Yeah, this frustrated me, too. I ended up using `as any` in Pogo to work around it.

https://github.com/sholladay/pogo/blob/2af2f39e0294ff186156a810247b353a10d4962d/lib/request.ts#L32
