### ISSUE TITLE
Network permissions check doesn't account for well-known default ports

### ISSUE THREAD

**Issue by Spoonbender** [denoland/deno#6531]
Network permissions check for a URL without an explicit port number doesn't account for default ports of well-known schemes (80 for HTTP, 443 for HTTPS), resulting in a false negative in case permissions were indeed granted for that host:port combo explicitly.

### Steps to reproduce

1. Grant permissions to access www.google.com:443 (to ensure only secure access).
2. Try to access an https url without specifying the 443 port, i.e. fetch from https://www.google.com/robots.txt
3. Deno denies access to that address, even though the operation itself is indeed targeting the allowed port on the allowed address.
4. Try to fetch https://www.google.com:443/robots.txt
5. Deno denies access here as well

### Example
Consider the following test:
```ts
const res = await fetch('https://www.google.com/robots.txt');
const data = await res.text();
console.log(data);
```
Calling `deno run --allow-net=www.google.com:443 test.ts` fails on permissions.

Even if we explicitly try to fetch from  https://www.google.com:443/robots.txt we fail on permissions.

### Cause 
The Rust url crate kindly discards the port number if it is the default of the scheme:
```rust
use url::*;

fn main() {
    let uri = url::Url::parse("https://www.google.com:443").unwrap();
    println!("URI = {:?}", uri);  // prints https://www.google.com
    println!("port = {:?}", uri.port()); // prints None
}
```
Prints the URL without the port number, port is None.
To get the port number, we need to use `port_or_known_default()`:
```rust
println!("Seriously, port {:?}", uri.port_or_known_default()); // prints 443
```

**Comment by Spoonbender** [comment]
Suggested fix is simple: use `port_or_known_default()` in both calls to `get_state_net()` in permissions.rs

**Comment by jacobgc** [comment]
Started working on the fix provided by @Spoonbender
