### ISSUE TITLE
refactor: Rewrite terminal printer for "deno doc"

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#6541]
Currently `deno doc` uses very bare-bones formatting to output documentation to terminal.

Example:
https://github.com/denoland/deno/blob/2da084058397efd6f517ba98c9882760ec0a7bd6/cli/doc/printer.rs#L111-L128

It's a bunch of functions that perform formatting and coloring. They do their job, but code structure and tests for terminal output are very poor.

Most of the functions in `cli/doc/printer.rs` should be rewritten as implementations of [`Display trait`](https://doc.rust-lang.org/std/fmt/trait.Display.html) for respective definition structs (`DocNode`, `ParamDef`, etc.).

Additionally tests should be upgraded as most of them does only rudimentary checks that output contains certain string.

I'm marking it as a "good first issue" because it's mostly refactor work that can be based on existing code.

**Comment by ry** [comment]
Unmarking as good first issue because it's quite a bit in the weeds :)

**Comment by lucacasonato** [comment]
We have 'detailed' and 'simple' views, for the filtered and non filtered view. Do we want to just get rid of those and always display the detailed view? Because the `Display` trait can not distinguish us trying to display a detail view or a simple view we don't really have much choice right?

**Comment by SyrupThinker** [comment]
I'm already working on this. It's the reason for my last PR (:
