### ISSUE TITLE
Stack trace contains wrong paths

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#6542]
I don't know if it is related but since today the fullpath is missing in the stacktrace in my github [CI](https://github.com/apiel/adka/runs/814693690?check_suite_focus=true):

![image](https://user-images.githubusercontent.com/5873198/85932819-dafd5d00-b8cf-11ea-86bf-88614babb38f.png)

_Originally posted by @apiel in https://github.com/denoland/deno/issues/5202#issuecomment-650634379_

Most likely introduced in #6428 with the change to use inline source maps.

**Comment by kitsonk** [comment]
I don't think the source map logic pulls the locations out of the code.  It won't remap the code points if the source map is missing, just preserve it.  I had assumed when we moved to inlining the source maps that we also updated the logic that acquires the source maps and makes them available.  I guess not.

**Comment by kitsonk** [comment]
Hmmm... the code is there:

https://github.com/denoland/deno/blob/42464e922d0bc435f32cf9d2707537a9558271fb/cli/tsc.rs#L849-L889

But there aren't any tests, so it is a bit hard to tell where in the chain it is failing. 😕

**Comment by apiel** [comment]
Is there a work around to solve this in my CI? Cause on my laptop it is working well, only the CI is broken since 2 weeks.
What is the difference between the github CI and my laptop (ubuntu).
If there would be a work around, I would be really happy, the time to wait to get this issue solved.

**Comment by kitsonk** [comment]
There isn't a work around.

**Comment by lucacasonato** [comment]
This seems to have broken between 1.1.2 and 1.1.3. Curiously code compiled and cached to DENO_DIR in 1.1.2 will show the correct paths, even in versions after 1.1.2. Code compiled and cached in 1.1.3 or later always has broken paths when paths from multiple different origins is present in the same stacktrace:

https://deno.land imports https://deno.land -> stack traces correct :heavy_check_mark: 
https://deno.land imports https://raw.githubusercontent.com -> stack traces wrong :x:  
file:// imports https://deno.land -> stack traces wrong :x:  
file:// imports file:// -> stack traces correct :heavy_check_mark:
