### ISSUE TITLE
error: Invalid executable name: 018 - Script installer

### ISSUE THREAD

**Issue by rodevio** [denoland/deno#6546]
Hi guys,

So I am learning deno and doing some testing and this error ocurred.

Basically I created a environment variable on bash shell with: 

**$** echo $USER

_main.ts_ file contents: `console.log("Hello", Deno.env.get("USER"));`

Everything works great when I ran: **$** deno run --allow-env main.ts

Prints Hello and my computer username.

Does not work as I would predicted when I ran: 
**$** deno install --allow-env main.ts

I get this error:
Check file:///Users/rodrigocastro/IdeaProjects/deno/deno-course/018/main.ts
error: Invalid executable name: 018

Does anyone know if this is a known issue? Do you know how walk around it?

Thanks in advance.

**Comment by nayeemrmn** [comment]
@bartlomieju What is the executable name validation based on? `018` should be a valid one, right?

@rodevio To be absolutely clear, you expect the executable name to be selected validly as `018`, right?

**Comment by rodevio** [comment]
@nayeemrmn yes

So my folder is: /018/main.ts

**Comment by rodevio** [comment]
@nayeemrmn 
I just discovered the problem. Basically my folder cannot be a number. Needs to be text like:
/testing/main.ts
and not like:
/018/main.ts

Pretty sure this will help someone down the road. Closing this!
