### ISSUE TITLE
Module "./mod" has no exported member "..."

### ISSUE THREAD

**Issue by hazae41** [denoland/deno#6548]
I have a project that uses wasm-bindgen to generate a [`deflate.js`](https://github.com/hazae41/denoflate/blob/d16bb51da4de59d732ee0b6cf82c63d2f007eb2e/pkg/deflate.js) file.

Then, I import it and initialize the wasm module in a [`mod.ts`](https://github.com/hazae41/denoflate/blob/d16bb51da4de59d732ee0b6cf82c63d2f007eb2e/mod.ts) file.

But when running [`test.ts` ](https://github.com/hazae41/denoflate/blob/d16bb51da4de59d732ee0b6cf82c63d2f007eb2e/test.ts)...

    deno run -allow-net https://raw.githubusercontent.com/hazae41/denoflate/d16bb51da4de59d732ee0b6cf82c63d2f007eb2e/test.ts

...Deno throws an error:

```
error: TS2305 [ERROR]: Module '"./mod"' has no exported member 'inflate'.
import { inflate, deflate } from "./mod.ts";
         ~~~~~~~
    at https://raw.githubusercontent.com/hazae41/denoflate/d16bb51da4de59d732ee0b6cf82c63d2f007eb2e/test.ts:1:10

TS2305 [ERROR]: Module '"./mod"' has no exported member 'deflate'.
import { inflate, deflate } from "./mod.ts";
                  ~~~~~~~
    at https://raw.githubusercontent.com/hazae41/denoflate/d16bb51da4de59d732ee0b6cf82c63d2f007eb2e/test.ts:1:19

Found 2 errors.
```

### Luckily, I found several workarounds.

- It works when I rename `deflate.js` to `deflate.ts` and prepend `// @ts-nocheck`, but then I loose the definitions from `deflate.d.ts`

- It works when I add

  `export const hello = "world";` 

  (or `export default "world"`)

  in `mod.ts` (or any .ts file), and then import it into `deflate.js` using

  `import { hello } from "../mod.ts"` 

  (or `import hello from "../mod.ts"`)

**Comment by kitsonk** [comment]
If you have a `.d.ts` file, try doing:

```ts
// @deno-types=./pkg/deflate.d.ts
export * from "./pkg/deflate.js";

// @deno-types=./pkg/deflate.d.ts
import init from "./pkg/deflate.js";
```

I should still have worked in the first place but I suspect TypeScript is struggling with the `export *` from an untyped file, as it isn't sure what symbols are exported, so it drops the export.  Needs some further investigation to confirm.

**Comment by hazae41** [comment]
It works when I add denotypes to the "import" instruction
    
    deno cache -r https://deno.land/x/denoflate/test.ts
    deno run --allow-net https://deno.land/x/denoflate/test.ts

**Comment by bartlomieju** [comment]
Closing as resolved.
