### ISSUE TITLE
Adding Mock Functions that simulates the behavior of a real method/object in controlled ways

### ISSUE THREAD

**Issue by getspooky** [denoland/deno#6549]
Problem: 
You can stub a database by implementing a simple in-memory structure for storing records. The object under test can then read and write records to the database stub to allow it to execute the test. This could test some behavior of the object not related to the database and the database stub would be included just to let the test run.

Solution:
If you instead want to verify that the object under test writes some specific data to the database you will have to mock the database. Your test would then incorporate assertions about what was written to the database mock.

**Comment by kitsonk** [comment]
Why would this not be solved in user land by the community?

**Comment by bartlomieju** [comment]
@getspooky this seems like a great idea for 3rd party library (like https://sinonjs.org/), but I don't think it should be in `std/`.
