### ISSUE TITLE
Request: Add --parallel to `deno test`

### ISSUE THREAD

**Issue by jakajancar** [denoland/deno#6559]
Would be nice if tests could be run in parallel.

Of course, assuming you take care of any shared resources correctly.

I'm fine giving up "leaking async ops" checks, or maybe just have one at the end "One of your tests leaked async ops, run without --parallel to troubleshoot"...

**Comment by caspervonb** [comment]
Just an aside; you can test files in parallel with something like xargs or par

```bash
find -name "*_test.ts" | xargs -P4 deno test -A --unstable
```

**Comment by jakajancar** [comment]
With separate processes, coordinating shared resource (e.g. db) parallelism / locking is non-trivial.

Within the same process you can just have the tests call a function.

**Comment by kt3k** [comment]
Jest has parallel testing builtin. I think this feature might help contributing to the adoption of `deno test`.

**Comment by caspervonb** [comment]
Yeah I've got plans to work on the test runner soon.

**Comment by vaysagecitrus** [comment]
> Just an aside; you can test files in parallel with something like xargs or par
> 
> ```shell
> find -name "*_test.ts" | xargs -P4 deno test -A --unstable
> ```

I have tried the above comment. But still Deno test is running sequentially

**Comment by caspervonb** [comment]
> I have tried the above comment. But still Deno test is running sequentially
Might need `-n1 -P4`
