### ISSUE TITLE
Deno v1.1.2 panics when no `HOME` env var is set

### ISSUE THREAD

**Issue by TooTallNate** [denoland/deno#6566]
This is new behavior as of v1.1.2:

```
$ deno --version
deno 1.1.2
v8 8.5.216
typescript 3.9.2

$ unset HOME

$ deno
thread 'main' panicked at 'Could not get home directory.', cli/deno_dir.rs:18:20
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I think Deno should fall back to checking the result of `getpwuid()` (Rust-equivalent, Windows-equivalent), which I believe is what Node.js does (node doesn't require `$HOME` to be set and `os.homedir()` still works properly).

I am using a [workaround](https://github.com/TooTallNate/vercel-deno/blob/1252210069563c128fc3a248b56ed3feae9d9255/src/bootstrap#L7) that fixes the issue for now.

**Comment by Spoonbender** [comment]
I'll try to fix this one
