### ISSUE TITLE
Assert error message not very helpful sometimes 

### ISSUE THREAD

**Issue by wongjiahau** [denoland/deno#6572]
## Steps to reproduce:
1. Create a file named `test.ts`
```ts
import {assertEquals} from './deps.ts'
Deno.test("dummy", () => {
  assertEquals({a:3,x:{y:{z:2}}}, {a:3,x:{y:{z:3}}})
})
```
2. Run the test:
```
deno test test.ts
```

## Expected result
Expected the error message to tell me precisely which part is different, in this case `.x.y.z`. For example in Jest:
![image](https://user-images.githubusercontent.com/23183656/86071621-4ef75b00-bab2-11ea-89ab-cca05f3443d9.png)

## Actual result
The error message just tells me the whole value is different, without pointing out which part is different.
```
AssertionError: Values are not equal:


    [Diff] Actual / Expected


-   { a: 3, x: { y: { z: 2 } } }
+   { a: 3, x: { y: { z: 3 } } }

    at assertEquals (https://deno.land/std@0.59.0/testing/asserts.ts:170:9)
```

## Environment
Deno@1.1.2
Std@0.59.0

I will submit a PR to fix this.

**Comment by nayeemrmn** [comment]
@wongjiahau This only happens when the object is small enough to fit on one line. It might be inherently fine / natural to do that in this case. But it can be fixed by adding an option to `Deno.inspect()` which always prints objects over multiple lines (if it doesn't already have one).

**Comment by wongjiahau** [comment]
@nayeemrmn Printing multiple line might help, but not when the object is large, which is quite common especially when testing responses from 3rd party APIs.

**Comment by wongjiahau** [comment]
@nayeemrmn You're right. Sorry for the misinformation.

**Comment by wongjiahau** [comment]
It's actually still a problem for objects with short keys.

**Comment by wongjiahau** [comment]
Not just that actually, the error message is kinda messed up when the object keys are in different order.

**Comment by nayeemrmn** [comment]
> It's actually still a problem for objects with short keys.

Yes, like I said. Small-stringed objects are printed to one line in `console.log()`/`Deno.inspect()`, and this logic is used by the formatter in `std/testing/asserts`.

Try this:
```js
import { assertEquals } from "./std/testing/asserts.ts";

try {
  assertEquals({ a: 0, b: 0, c: 0, d: 0, e: 0, f: 0, g: 0, h: 0, i: 0, j: 0, k: 0, l: 0, m: 0, n: 0, o: 0, p: 0 }, {})
} catch (error) {
  console.log(error);
}
try {
  // Object is big enough to line-wrap.
  assertEquals({ a: 0, b: 0, c: 0, d: 0, e: 0, f: 0, g: 0, h: 0, i: 0, j: 0, k: 0, l: 0, m: 0, n: 0, o: 0, p: 0, q: 0 }, {})
} catch (error) {
  console.log(error);
}
```
```
AssertionError: Values are not equal:


    [Diff] Actual / Expected


-   { a: 0, b: 0, c: 0, d: 0, e: 0, f: 0, g: 0, h: 0, i: 0, j: 0, k: 0, l: 0, m: 0, n: 0, o: 0, p: 0 }
+   {}

    at assertEquals (file:///mnt/c/Users/Nayeem/projects/deno/std/testing/asserts.ts:171:9)
    at file:///mnt/c/Users/Nayeem/projects/deno/temp.js:4:3
AssertionError: Values are not equal:


    [Diff] Actual / Expected


-   {
-     a: 0,
-     b: 0,
-     c: 0,
-     d: 0,
-     e: 0,
-     f: 0,
-     g: 0,
-     h: 0,
-     i: 0,
-     j: 0,
-     k: 0,
-     l: 0,
-     m: 0,
-     n: 0,
-     o: 0,
-     p: 0,
-     q: 0
-   }
+   {}

    at assertEquals (file:///mnt/c/Users/Nayeem/projects/deno/std/testing/asserts.ts:171:9)
    at file:///mnt/c/Users/Nayeem/projects/deno/temp.js:9:3
```

Again, I think this is fine (though perhaps the limit should be smaller). But if you want, you can fix this the way I described above with a `Deno.inspect()` option to always wrap lines and using that option in `format()` in `std/testing/asserts.ts`.

**Comment by wongjiahau** [comment]
@nayeemrmn Thanks I will look into it.

**Comment by nayeemrmn** [comment]
> Not just that actually, the error message is kinda messed up when the object keys are in different order.

Sorry this comment hadn't loaded for me before I wrote my last response. Yeah, this is an issue that had occurred to me once but I forgot... it's bound to mess up the diff message sometimes. Please edit the issue description.

The fix is similar, though: add an option to `Deno.inspect()` which will make it sort keys alphabetically and use that in `format()`.
