### ISSUE TITLE
Deno install broken when no filename

### ISSUE THREAD

**Issue by keelii** [denoland/deno#6574]
Does `deno install` command should give a TS filename?

![1](https://user-images.githubusercontent.com/458894/86077538-b7e4d000-babe-11ea-80ed-76a923be8fa3.png)

**Comment by kitsonk** [comment]
You must always be explicit with Deno.  It doesn't "magically" add names to URLs.

**Comment by nayeemrmn** [comment]
@kitsonk It does, see #5004.

@keelii It has nothing to do with `deno install`, the first URL is failing to compile because it is a TS module without a `.ts`  extension (or content type `application/x-typescript`), and Deno assumes it is JS. This is expected behaviour.

**Comment by keelii** [comment]
@nayeemrmn OK，but in this case, The response content of the two different url is exactly the same, Then i thougth: with same input should deno response the same output?

**Comment by nayeemrmn** [comment]
> The response content of the two different url is exactly the same, Then i thougth: with same input should deno response the same output?

It's not the same input. The URL you give is part of the input.
