### ISSUE TITLE
Use setTimeout causes an error

### ISSUE THREAD

**Issue by prettyboyweiwei** [denoland/deno#6575]
I have a test.ts file:

```javascript
console.log(setTimeout)

setTimeout(() => {
    console.log("123")
}, 1000)

```

Run `deno test.ts` in the terminal, I got these:

```
MacBook-Pro:deno wei$ deno test.ts
Compile file:///Users/wei/Development/deno/test.ts
[Function: setTimeout]
error: Uncaught Error: assert
► js/util.ts:28:11
    at assert (js/util.ts:28:11)
    at getTime (js/timers.ts:37:3)
    at setTimer (js/timers.ts:201:15)
    at setTimeout (js/timers.ts:237:10)
    at file:///Users/wei/Development/deno/test.ts:3:1
```

Is this a bug

**Comment by Desibabe** [comment]
Try Deno run test.ts

Here is the result using the same code:
c:\deno\deno run test.ts
[Function: setTimeout]
123

**Comment by kitsonk** [comment]
What version of Deno are you using?

**Comment by Desibabe** [comment]
deno --version
deno 1.1.2
v8 8.5.216
typescript 3.9.2

-----Original Message-----

**Comment by Desibabe** [comment]
deno --version
deno 1.1.2
v8 8.5.216
typescript 3.9.2

**Comment by kitsonk** [comment]
No, I meant the person with the problem @prettyboyweiwei

**Comment by prettyboyweiwei** [comment]
@kitsonk 
wei$ deno version
deno: 0.12.0
v8: 7.7.200
typescript: 3.5.1

**Comment by prettyboyweiwei** [comment]
I installed it yesterday
`brew install deno`

**Comment by kitsonk** [comment]
There have been about 40+ releases of Deno since v0.12.0.

Please install the latest release of Deno: https://deno.land/#installation

**Comment by prettyboyweiwei** [comment]
Thank you, I get the correct result after upgrading to 1.1.2.
And the cause of the error is Homebrew installed an earlier version
