### ISSUE TITLE
`deno upgrade` doesn't support --cert flag

### ISSUE THREAD

**Issue by jacobgc** [denoland/deno#6579]
Being behind a corporate firewall with https snooping, all requests are signed with a cert stored in the OS cert store which from looking at many issues, deno currently doesn't support. 

`deno run` supports the `--cert` flag which allows me to load a custom pem file with these certificates.

`deno upgrade` does not support the `--cert` flag which causes the upgrade script to fail with the following known error:
> error: error sending request for url (https://github.com/denoland/deno/releases/latest): error trying to connect: invalid certificate: UnknownIssuer

Versions:

> deno 1.1.2
> v8 8.5.216
> typescript 3.9.2

**Comment by jacobgc** [comment]
Think I'm going to have a look at this one. Should be able to use the functionality from the `deno run` command I would hope.

**Comment by crowlKats** [comment]
Since this was resolved with #6609, could we get this closed?
