### ISSUE TITLE
Enhancing the Contributor License Agreement (CLA)

### ISSUE THREAD

**Issue by robpalme** [denoland/deno#6584]
Hello friends,

I, and potentially a few other folk at Bloomberg, would like to contribute to Deno.  The only hold up is the [Deno Individual Contributor License Agreement](https://cla-assistant.io/denoland/deno) (CLA).  

There are two issues with the CLA that mean our Open Source Program Office (OSPO) is unwilling to let employees sign it.  Other companies are likely to have similar blockers, so hopefully solving these issues will help other folk to contribute to Deno too.

## 1. Copyrights and patent licenses are assigned to an individual person

The CLA assigns copyrights and patent license to **an individual person**.  We can only sign it if some other type of legal entity is used.

Just to highlight how unusual this is, our OSPO team, that has been running for over six years, has never been asked to approve a CLA where the assignment is to a named person.

## 2. There is no Corporate Contributor License Agreement

Our employees do not have permission to license patents owned by the company, so they cannot sign the current agreement.

Introducing a Corporate Contributor License Agreement would solve this problem.  Here is one [example from Apache](https://www.apache.org/licenses/cla-corporate.txt).

As a success story, when we first started working with Microsoft on TypeScript, the project had no Corporate CLA.  We worked with them to put one in place and enhanced the CLA-assistant bot (that Deno also uses) to be super easy-to-use - checking compliance based on the origin org of a Pull Request.

**Comment by ry** [comment]
Hi @robpalme, thanks for relaying the explicit requirements you have. I've been meaning to update the CLA for a while - I'll get on that this week.

**Comment by kitsonk** [comment]
🎉 🎉  Really looking forward to having contributions from Bloomberg!  Have lots of respect what you folks have Bloomberg have been doing in the wider community!

**Comment by lucacasonato** [comment]
@robpalme Issue number 1 is now resolved. The CLA now assigns patents and licenses to Deno Land Inc, a legal entity.

**Comment by ry** [comment]
Hi @robpalme, I've updated the CLA with the entity Deno Land Inc rather than my personal name. However I'm unable to get the app we use (https://cla-assistant.io/) to display both the corp and individual. Is it possible that I send you all the corporate agreement and have you sign it manually? The corporate agreement is here https://gist.github.com/ry/3c2e34f5fcd5cc3e8ee91ddef80d73c1 - you can printed that out , have it signed, and email it back to me ry@tinyclouds.org. Then I can add any Bloomberg contributors manually to the CLA assistant accept list.

**Comment by ry** [comment]
@kpfleming Thanks for the tip. I was going to add people individually to the accept list, glad to know it supports orgs.
