### ISSUE TITLE
Deno executable on Windows should have an icon

### ISSUE THREAD

**Issue by Jack-Works** [denoland/deno#6593]
<img src="https://deno.land/logo.svg" width=128 height=128 />

🎉

**Comment by MarkTiedemann** [comment]
I've previously used [electron/rcedit](https://github.com/electron/rcedit) to do this. They provide a binary release [here](https://github.com/electron/rcedit/releases/tag/v1.1.1). Setting the icon is quite simple: `rcedit deno.exe --set-icon deno.ico`.

Here's an example of me setting the favicon.ico as the icon of deno.exe:

![Capture](https://user-images.githubusercontent.com/7062160/86284962-16f03500-bbe4-11ea-9b67-3f4a177ca05e.PNG)

(Note that I have Windows in dark mode so the dino being transparent doesn't look good - it should be white.)

**Comment by Spoonbender** [comment]
I'll try to take this one
