### ISSUE TITLE
Backside Deno Bundle

### ISSUE THREAD

**Issue by Zacharys-Hackery** [denoland/deno#6600]
When a user decides to bundle a script written using Deno's modules or runtime APIs, is there anything that remains usable for the front end?

For example, reading a file without an `<input type='file' />` element when someone is using a website. Obviously before compilation, there is `Deno.readFileSync` and such to get the job done; but will it work when embedded in an `.html` file? The answer may not represent every module and API, because some may be plausible and some may not.

Nevertheless, I think it would be a good idea to mention this question somewhere in the documentation, just to let users know.

**Comment by kitsonk** [comment]
I think what you are looking for is: https://github.com/denoland/deno/pull/5755
