### ISSUE TITLE
Suggestion: std datetime extend and cleanup

### ISSUE THREAD

**Issue by timreichen** [denoland/deno#6601]
# Extend
Since datetime has a function for ```dayOfYear``` I would suggest to add the following functions:
```weekOfMonth``` (values between 1-5)
```weekOfYear ``` (values between 1-53)

# Cleanup
Is it necessary to have ```currentDayOfYear``` as a sugar function since it just calls ```dayOfYear(new Date())``` or could it be removed?

**Comment by jacobgc** [comment]
IMO `currentDayOfYear` shouldn't be a thing, as for `weekOfMonth` and `weekOfYear` they sound like decent ideas

**Comment by jacobgc** [comment]
Going to have a look at implementing weekOfMonth and weekOfYear. Shouldn't take too long.

**Comment by timreichen** [comment]
Great, thank you! I just noticed the new ```difference``` function in std/datetime. It supports ```quarter```as a unit type. Therefore a ```quarterOfYear``` would maybe make sense too to have as a function?

**Comment by timreichen** [comment]
removing ```currentDayOfYear```: PR #7059
