### ISSUE TITLE
Issue with Deno.setRaw and subprocesses

### ISSUE THREAD

**Issue by Yamboy1** [denoland/deno#6604]
It seems like after using Deno.setRaw, even after setting it to false, and then doing the same thing in a subprocess, deno panics. I created an example script here: https://gist.github.com/Yamboy1/c9cb9e215d3a3433193044d96a62f62a.

```
$ deno run --unstable -A https://gist.githubusercontent.com/Yamboy1/c9cb9e215d3a3433193044d96a62f62a/raw/46680c56316343ee1206fcee7168242d23eb346b/test.ts
```

**Comment by uki00a** [comment]
I'll work on a fix.
