### ISSUE TITLE
[Issue] Seems like issue with import-map for https://deno.land/x/*

### ISSUE THREAD

**Issue by redradist** [denoland/deno#6605]
I have tested the following code:
```typescript
import * as oak from "https://deno.land/x/oak/mod.ts";
```
but if I add this to import-map:
```json
{
  "imports": {
    ...
    "oak": "https://deno.land/x/oak/",
    ...
  }
}
```
```typescript
import * as oak from "oak/mod.ts";
```
It shows the error:
```console
error: Unmapped bare specifier "oak/mod.ts"
```

**Comment by kitsonk** [comment]
You need to use a trailing slash for a "package" as per the specification: https://github.com/WICG/import-maps#packages-via-trailing-slashes

**Comment by redradist** [comment]
> 
> 
> You need to use a trailing slash for a "package" as per the specification: https://github.com/WICG/import-maps#packages-via-trailing-slashes

@kitsonk Thanks !!
