### ISSUE TITLE
iOS support

### ISSUE THREAD

**Issue by redradist** [denoland/deno#6607]
It would be nice if `Deno` will support `iOS` embedding

**Comment by lucacasonato** [comment]
As far as I am aware Apple does not allow any apps with JavaScript engines other than JavaScriptCore in the App Store if they do JIT - which V8 does. So this could probably be technically done, but you would likely not be able to distribute an app built with Deno through the Apple App Store. That would make this somewhat pointless.

**Comment by redradist** [comment]
> 
> 
> As far as I am aware Apple does not allow any apps with JavaScript engines other than JavaScriptCore in the App Store if they do JIT - which V8 does. So this could probably be technically done, but you would likely not be able to distribute an app built with Deno through the Apple App Store. That would make this somewhat pointless.

I forgot about it ... (

**Comment by yorkie** [comment]
I remember that the v8 has jitless mode now.

**Comment by hork71** [comment]
https://v8.dev/blog/jitless

**Comment by qwerasd205** [comment]
Actually, the [App Store Review Guidelines](https://developer.apple.com/app-store/review/guidelines/) only specify the following
> 2.5.6 Apps that browse the web must use the appropriate WebKit framework and WebKit Javascript.

So as long as it's not a web browser it doesn't matter if it's running a JavaScript engine other than WebKit.

**Comment by kitsonk** [comment]
There are embeddable versions of Node.js for both Android and iOS.  That being said, they are probably best handled by a wider community project than Deno itself (just like they are for Node.js).

**Comment by redradist** [comment]
> 
> 
> There are embeddable versions of Node.js for both Android and iOS. That being said, they are probably best handled by a wider community project than Deno itself (just like they are for Node.js).

I think `deno` also very good for embedding in app due to `rust` which makes easier to port application to other platforms

**Comment by frank-dspeed** [comment]
All this infos are correct about the jitless mode and it works also on IOS and Android i also want to add that the new v8 lite project will be merged soon into the --jitless mode flag https://v8.dev/blog/v8-lite so it will not only allow to pre alloc memory it will also save up to 35% memory traded for some performance so it will run even better on devices with small memory footprint.

**Comment by frank-dspeed** [comment]
You can already run Deno in V8 `jitless` mode: `deno run --v8-flags="--jitless"`. It is just painfully slow. V8 lite mode is also supported via `--v8-flags="--lite-mode"`. I am not sure everything works, but it is enough for initial testing.

_Originally posted by @lucacasonato in https://github.com/denoland/deno/issues/6621#issuecomment-653679807_

So it is time now for testing the New IOS Support that we already got :) Simply compile deno on IOS and use the jitless mode to run

**Comment by bartlomieju** [comment]
Closing as resolved.

**Comment by frank-dspeed** [comment]
@bartlomieju it should get documented in the IOS section of deno as current state

**Comment by lucacasonato** [comment]
Deno does not provide iOS builds

**Comment by frank-dspeed** [comment]
@lucacasonato at present but they are now possible we should keep focus on that there are some ios users around its a big platform and it is target able

**Comment by kitsonk** [comment]
This issue is sufficient memoization of the status.

**Comment by metacoding** [comment]
This is rather a year old, but Apple is replacing JavaScriptCore with NativeScript that brings V8 into iOS and iPadOS. Does this change have any positive result for deno support? 
https://www.infoq.com/news/2020/01/nativescripts-adopts-V8-ios/

**Comment by kitsonk** [comment]
Apple is not replacing JavaScriptCore with NativeScript.  The article you linked to is how NativeScript migrated to V8 JIT-less instead of JavaScriptCore, which allows them (NativeScript, nothing to do with Apple) to have feature parity with Android when using NativeScript on iOS.  JIT-less V8 on iOS has been possible for a while now as mentioned in this thread.  It changes nothing for Deno.

**Comment by zdavatz** [comment]
Any update on this for creating a native iOS App from a Deno application using github actions?
