### ISSUE TITLE
deno lint succeeds, build still fails

### ISSUE THREAD

**Issue by timreichen** [denoland/deno#6608]
I successfully executed ```deno lint``` for a fork, then created this [pull request](https://github.com/denoland/deno/pull/6602). The build failed during ```lint.py```.
```sh
warning  Missing return type on function  @typescript-eslint/explicit-function-return-type
```
I guess both linters have different settings or plugins loaded. Is this intential?

**Comment by jacobgc** [comment]
I'm fairly sure `deno lint` is just meant for basic typescript linting of applications you want to run with deno. in your deno source folder run tools/lint.py and you can see the errors before commiting.

**Comment by bartlomieju** [comment]
@timreichen `deno lint` is not used to lint `deno` codebase at the moment. As suggested by @jacobgc make sure to run `tools/lint.py` and fix any errors produced.

**Comment by timreichen** [comment]
Thanks for your replies and suggestions. That was what I was looking for.
