### ISSUE TITLE
Apache Tinkerpop Support

### ISSUE THREAD

**Issue by riccijs** [denoland/deno#6610]
Hi - I'm attempting to architect and build a new framework using Deno runtime, but in order to meet all requirements, I'm needing to connect to Cosmos Db using Gremlin. I have two questions related to this:

1. Is anyone currently working on a Gremlin driver for Deno or does one exist that I'm unaware of?
2. If no-one is working on this, how would I go about submitting a driver I developed to be added to the list of third-party packages?

Thanks in advance! :)

**Comment by lucacasonato** [comment]
Hi :wave:!

Questions like these should be asked on Discord: https://discord.gg/deno. The issue tracker is for bugs and feature requests directly related to Deno, not questions.
