### ISSUE TITLE
Proposal: support for v8-lite add a v8 jitless build to be used with deno

### ISSUE THREAD

**Issue by frank-dspeed** [denoland/deno#6621]
the new v8 lite project will be merged soon into the --jitless mode flag https://v8.dev/blog/v8-lite so it will not only allow to pre allocate memory it will also save up to 35% memory traded for some performance so it will run even better on devices with a small memory footprint

# Enables
- Running on IoT Devices more memory efficient
- IOS & Android Support
- Better for big Data and Memory based Cloud Computing like ML Research.

# Related Issues
- https://github.com/denoland/deno/issues/6607

**Comment by kitsonk** [comment]
This is more of a rusty_v8 thing than a Deno thing.  https://github.com/denoland/rusty_v8. Even if it made it to Deno it would first need to be in rusty_v8.

**Comment by frank-dspeed** [comment]
Oh you're correct but in general, as deno ships with v8, it can be open here as a reference till something is done in that direction.

**Comment by kitsonk** [comment]
Deno ships with rusty_v8, which includes v8.

**Comment by lucacasonato** [comment]
You can already run Deno in V8 `jitless` mode: `deno run --v8-flags="--jitless"`. It is just painfully slow. V8 lite mode is also supported via `--v8-flags="--lite-mode"`. I am not sure everything works, but it is enough for initial testing.

**Comment by frank-dspeed** [comment]
@lucacasonato amazing how fast we as a community did ship this features :+1:
