### ISSUE TITLE
Suggestion: Better error log for format.py

### ISSUE THREAD

**Issue by timreichen** [denoland/deno#6622]
Is occurring in this [pull request](https://github.com/denoland/deno/pull/6619).
```format.py``` fails during check, I cannot figure out why. The error log doesn't really give any useful information.
```sh
test_format.py
Run python ./tools/format.py
yapf (16 files)
rustfmt (125 files)
/opt/hostedtoolcache/Python/2.7.18/x64/bin/python tools/format.py
git status -uno --porcelain --ignore-submodules
Run tools/format.py 
  M std/datetime/formatter.ts
  M std/datetime/mod.ts
  M std/datetime/test.ts
  M std/datetime/tokenizer.ts
##[error]Process completed with exit code 1.
```
Any suggestions?

**Comment by lucacasonato** [comment]
Because the files are not formatted. You should run `./tools/format.py`

**Comment by timreichen** [comment]
Sorry to bother you again. This is my first bigger commit to Deno, I am not very familiar with the whole procedure and build chain yet and need some help.

So I ran ```./tools/format.py``` and it threw. Don't know exactly what is going on there.

```sh
deno % ./tools/format.py
yapf (16 files)
rustfmt (125 files)
Traceback (most recent call last):
  File "./tools/format.py", line 98, in <module>
    sys.exit(main())
  File "./tools/format.py", line 53, in main
    rustfmt()
  File "./tools/format.py", line 94, in rustfmt
    quiet=True)
  File "/…/deno/tools/util.py", line 63, in run
    rc = subprocess.call(args, cwd=cwd, env=env, shell=shell)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by Soremwar** [comment]
@timreichen Are you using python 3 or python 2

Those tools require python 2 to work correctly if I'm not wrong

Don't worry, this will get way less of a pain once the official linter and formatter are implemented internally :P

**Comment by timreichen** [comment]
> @timreichen Are you using Python 3 or Python 2?

Im using the MacOS system default which is ```Python 2.7.16```.


> Don't worry, this will get way less of a pain once the official linter and formatter are implemented internally :P

Thats great to hear!:)

**Comment by Soremwar** [comment]
@timonson So you ran `python --version` and that was the output? Weird

Try running `python ./tools/format.py`

**Comment by timreichen** [comment]
> @timonson So you ran `python --version` and that was the output? Weird

Yes
```sh
python --version
Python 2.7.16
```

> Try running `python ./tools/format.py`

getting exactly the same result.
```sh
python ./tools/format.py
yapf (16 files)
rustfmt (125 files)
Traceback (most recent call last):
  File "./tools/format.py", line 98, in <module>
    sys.exit(main())
  File "./tools/format.py", line 53, in main
    rustfmt()
  File "./tools/format.py", line 94, in rustfmt
    quiet=True)
  File "/Users/Tim/Sites/deno/tools/util.py", line 63, in run
    rc = subprocess.call(args, cwd=cwd, env=env, shell=shell)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by Soremwar** [comment]
Your github branch is up to date with your local changes? Imma download it and test it in my pc and see if I can figure it out

**Comment by timreichen** [comment]
Should be I created the fork earlier today.

**Comment by lucacasonato** [comment]
Did you clone the sub modules?

**Comment by timreichen** [comment]
I did clone ```deno_third_party``` since it is is referenced in the main ```deno``` repo. Did I miss any?

**Comment by jacobgc** [comment]
`deno_typescript/typescript` is another submodule

As per the deno manual, you should have cloned like this to ensure submodules are downloaded too `git clone --recurse-submodules https://github.com/denoland/deno.git
`

**Comment by timreichen** [comment]
Tried with ```git clone --recurse-submodules https://github.com/denoland/deno.git```. Same error again.

**Comment by jacobgc** [comment]
Interesting, what happens if you call `rustfmt` manually?

**Comment by Soremwar** [comment]
Ok I think I found the problem
You haven't setup Rust in your computer have you?

**Comment by Soremwar** [comment]
I submitted a pull request to your repo with the linting and formatting done to save you the hassle. Just merge it and the changes should appear in the PR that is failing

**Comment by timreichen** [comment]
Thank you! I did have rust installed, though after reading this I did a clean reinstall and now it also worked! I guess I had some messed up path configuration. 

> @timreichen I submitted a pull request to your repo with the linting and formatting done to save you the hassle. Just merge it and the changes should appear in the PR that is failing

Thank you for that, I merged your pull request, linting tests now succeed as expected. Sadly it fails on ``` Test release```, though on tests I think not connected to the changes. Needs more debugging...
