### ISSUE TITLE
Question on branding.

### ISSUE THREAD

**Issue by adam-cyclones** [denoland/deno#6625]
I am building a common.js to es_module transpiler. The premise is Deno for the browser because I have been building a lot of ES_module based frontends lately but its hard to find all the packages I need. I also think that Deno community could benefit from such a tool unless I am a bit behind the times on this one. 

The project currently know as Unpack (wont post links, this is not a plug) is hoping to become synonymous with a Deno stack, I have a mascot named Didi which I have designed from the ground up, it mimics the Deno logo and is meant to sit alongside Deno saying something like Didi loves Deno. 

I wanted to be courteous and ask permission, can I use this as a logo or mascot https://dev.to/adam_cyclones/didi-help-me-choose-a-logo-3mo4

With the greatest respect to Deno and the Deno team.

**Comment by ry** [comment]
> I wanted to be courteous and ask permission, can I use this as a logo or mascot

Yes of course. Good luck with Didi.
