### ISSUE TITLE
thread 'main' panicked at 'called after complete'.

### ISSUE THREAD

**Issue by buttercubz** [denoland/deno#6637]
When I try to do a deno test, the tests do not run and this message appears:

thread 'main' panicked at 'called after complete', D:\a\deno\deno/.cargo_home\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.21\src\sync\oneshot.rs:523:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by caspervonb** [comment]
Please try provide a minimal example.

Also run with RUST_BACKTRACE=1 environment variable to display a backtrace and provide it here.

**Comment by buttercubz** [comment]
for example: when i try to run this `deno cache --lock=lock.json --lock-write anyfile.ts` i get the error.

this error only pass when i try run deno test, deno cache and deno install.
I have wsl with ubuntu 20.04 and I don't have that error so I think it only happens in windows, a colleague also has that problem #6557

**info:**
deno: 1.1.3
 v8:  8.5.216
typescript: 3.9.2 

os: windows 10
version: 2004
build: 19041.329

**Comment by ry** [comment]
Can't repeat on mac:
```
~/src/deno> touch anyfile.ts
~/src/deno> deno cache --lock=lock.json --lock-write anyfile.ts
Check file:///Users/rld/src/deno/anyfile.ts
~/src/deno>
```

**Comment by buttercubz** [comment]
@ry I do not understand what you mean

**Comment by ry** [comment]
@buttercubz You need to provide more details about how this crash occurred in order for us to investigate.  Most importantly, what was the input program?

**Comment by jersou** [comment]
I have the same bug when I call Process::status() twice (= after complete...) :
```
const process = Deno.run({cmd: [ "deno", "--version"]});
await process.status();
await process.status();
```
No error on Linux, but on my Win7 VM, the output is:
```
deno 1.2.0
v8 8.5.216
typescript 3.9.2
thread 'main' panicked at 'called after complete', D:\a\deno\deno/.cargo_home\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.21\src\sync\oneshot.rs:523:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by ry** [comment]
@jersou No error on mac either. So maybe this is a Windows only bug?

**Comment by jersou** [comment]
@ry yes, it seems to be a Windows only bug.

No bug on Linux with this code.
Removing the repetition was a workaround for me on Windows.

**Comment by buttercubz** [comment]
@jersou I had this problem with deno 1.1.3 but with deno 1.2.0 it no longer happens

**Comment by jersou** [comment]
The output above has not been modified, I have the bug on Windows with deno 1.2.0.

If it helps, I reproduce the bug with Wine (test.ts == the 3 lines above) :
```
wine deno.exe run --allow-run test.ts 
Check file:///Z:/tmp/test.ts
deno 1.2.0
v8 8.5.216
typescript 3.9.2
thread 'main' panicked at 'called after complete', D:\a\deno\deno/.cargo_home\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.21\src\sync\oneshot.rs:523:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by lucacasonato** [comment]
@DjDeveloperr Can not reproduce on 1.12.1 anymore, so I assume this was an upstream Tokio bug that has been fixed.

![image](https://user-images.githubusercontent.com/7829205/126332303-204ce905-6733-4208-8568-a0c760bb41d1.png)

If you encounter this issue again, please open another issue.
