### ISSUE TITLE
How to set proxy for some fetch request not all

### ISSUE THREAD

**Issue by XGHeaven** [denoland/deno#6654]
I want to set proxy for some fetch request and others not. How to do that.

I know set `http_proxy`/`https_proxy` env which only proxy all fetch request.

**Comment by jacobgc** [comment]
As far as I'm aware, the fetch api doesn't support setting a proxy on an individual request basis.

**Comment by bartlomieju** [comment]
@jacobgc is correct. Please describe your use case and continue in #3444.

**Comment by chibat** [comment]
I tried creating the following.
https://github.com/chibat/rest_client_with_proxy

but we will be happy if it is implemented in runtime api.
