### ISSUE TITLE
deno test diff confusing

### ISSUE THREAD

**Issue by jacobgc** [denoland/deno#6658]
I'm not sure if its just me not reading the diff correctly, but from the screenshot below, I would quickly assume (by matching colours) that the `Actual` is the `- 2` and the `Expected` is the `+ 5`. However its the oposite way round? The 2 is the expected value. Am I just reading this wrong?

![image](https://user-images.githubusercontent.com/2946071/86584282-8ff0e300-bf7c-11ea-8f17-a16cdd2e22d9.png)

**Comment by nayeemrmn** [comment]
You have it right. How are you using the `assert()` function? It should be `assert(actual, expected)`.

**Comment by jacobgc** [comment]
Huh, just noticed that, turns out that some of the tests in std/datetime/test.ts are backwards... Serves me right for copy/pasting to save a bit of time. I'll swap them around while im working in that file.

Cheers
