### ISSUE TITLE
Deno.bundle() should accept the compiler flag `importsNotUsedAsValues`

### ISSUE THREAD

**Issue by timonson** [denoland/deno#6663]
This `tsc` compiler flag was implemented in TypeScript [3.8](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html). You can find the merged PR here: https://github.com/microsoft/TypeScript/pull/35200

This flag takes 3 different values:

- remove: this is today’s behavior of dropping these imports. It’s going to continue to be the default, and is a non-breaking change.
- preserve: this preserves all imports whose values are never used. This can cause imports/side-effects to be preserved.
- error: this preserves all imports (the same as the preserve option), but will error when a value import is only used as a type. This might be useful if you want to ensure no values are being accidentally imported, but still make side-effect imports explicit.

It would be very helpful for Web Components and other stuff.

**Comment by bartlomieju** [comment]
Ref https://github.com/denoland/deno/pull/6456

CC @kitsonk

**Comment by kitsonk** [comment]
@bartlomieju this is different... It just needs to be added to the compiler APIs Compiler Options and converted to the right internal TypeScript type.

**Comment by timonson** [comment]
Did the following PR fix this issue here? https://github.com/denoland/deno/pull/7413
