### ISSUE TITLE
Conditional expression not indented in this scenario

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#6667]
```ts
const es5Bundle = test ||
target === ts.ScriptTarget.ES2016
      ? true
      : false;
```

Incorrectly formats as:

```ts
const es5Bundle = test ||
  target === ts.ScriptTarget.ES2016
  ? true
  : false;
```

**Comment by dsherret** [comment]
Oops. Wrong repo. Sorry 😅

**Comment by Yamboy1** [comment]
I know you closed the issue, but can't you literally just do `target === ts.ScriptTarget.ES2016` without needing a conditiational? or is it just an example

**Comment by dsherret** [comment]
@Yamboy1 it's just an example. Full code internally in Deno is:

```ts
const es5Bundle = target === ts.ScriptTarget.ES3 ||
  target === ts.ScriptTarget.ES5 ||
  target === ts.ScriptTarget.ES2015 ||
  target === ts.ScriptTarget.ES2016
    ? true
    : false;
```

Moved this to https://github.com/dprint/dprint-plugin-typescript/issues/22
