### ISSUE TITLE
deno expects --alow-write to be passed after file name (not that friendly!)

### ISSUE THREAD

**Issue by manidlou** [denoland/deno#667]
So I've been playing with `deno` and noticed that the `--allow-write` flag only works if you pass it after the file name like this `deno somefile.ts --allow-write`, and if you use it like

 `deno --allow-write somefile.ts`

it will give you the error something like this `Error: Cannot resolve module "--allow-write" from "somefile.ts`,

Not sure if it is an expected behavior! just something to be aware of!

IMHP, if we want to be user friendly and easy to use, it should work regardless of where you pass it in a command!

**Comment by kevinkassimo** [comment]
Have just recompiled deno and could not reproduce this issue. I saw your error message showing `"--alow-write"` instead of `"--allow-write"`. Are you using the correct flag?

**Comment by manidlou** [comment]
You are right @kevinkassimo! I've been doing some crazy stuff! thanks for clarification!
