### ISSUE TITLE
Use TypeScript instead of JavaScript for internal Deno Code

### ISSUE THREAD

**Issue by xiaoxiangmoe** [denoland/deno#6678]
```ts
Object.defineProperty(URLSearchParamsImpl, "name", { value: "URLSearchParams" });
```

For detail:
```ts
function assertString(x: unknown): asserts x is string {
  if (typeof x !== 'string') {
    throw new Error();
  }
}

interface URLSearchParams {
  toFoo: (x: string) => string;
}

type URLSearchParamsType = URLSearchParams;

class URLSearchParamsImpl implements URLSearchParamsType {
  constructor(init?: unknown) {}
  toFoo(x: unknown) {
    assertString(x);
    return '114514 + ' + x;
  }
}
Object.defineProperty(URLSearchParamsImpl, "name", { value: "URLSearchParams" });

const URLSearchParams: {
  new (
    init: string[][] | Record<string, string> | string | URLSearchParams,
  ): URLSearchParams;
} = URLSearchParamsImpl;

export { URLSearchParams };
```
Another way for write it is using [block](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/block) in js.

See example:

```ts
function assertString(x: unknown): asserts x is string {
  if (typeof x !== 'string') {
    throw new Error();
  }
}

interface URLSearchParams {
  toFoo: (x: string) => string;
}

type URLSearchParamsType = URLSearchParams;

let URLSearchParamsImpl: {
  new (
    init: string[][] | Record<string, string> | string | URLSearchParams,
  ): URLSearchParams;
};

{
  class URLSearchParams implements URLSearchParamsType {
    constructor(init?: unknown) {}
    toFoo(x: unknown) {
      assertString(x);
      return '114514 + ' + x;
    }
  }
  URLSearchParamsImpl = URLSearchParams;
}

const URLSearchParams = URLSearchParamsImpl;

export { URLSearchParams };
```

* We can export URLSearchParams as both value and type.
* We can write type guard functions for internal type check. If the type signature written in impl is unknown, it will remind us that we need to perform type guard conversion.
* Our internal code and runtime TS declarations will auto kept in sync. And the type generated will be as good as write manually.
* The generated js code is not very different from the handwritten js code, and it does not prevent the optimization of v8.

result dts file

```ts
interface URLSearchParams {
    toFoo: (x: string) => string;
}
declare const URLSearchParams: new (init: string[][] | Record<string, string> | string | URLSearchParams) => URLSearchParams;
export { URLSearchParams };
```

result js file

```js
function assertString(x) {
    if (typeof x !== 'string') {
        throw new Error();
    }
}
let URLSearchParamsImpl;
{
    class URLSearchParams {
        constructor(init) { }
        toFoo(x) {
            assertString(x);
            return '114514 + ' + x;
        }
    }
    URLSearchParamsImpl = URLSearchParams;
}
const URLSearchParams = URLSearchParamsImpl;
export { URLSearchParams };
```

**Comment by kitsonk** [comment]
Why is 20+ lines of code better than 1 line of code?

**Comment by xiaoxiangmoe** [comment]
@kitsonk I updated the example. It is 28 lines to 32 lines. The purpose of this demo is to remove `Object.defineProperty`.

The previous discussion is in https://docs.google.com/document/d/1_WvwHl7BXUPmoiSeD8G83JmS8ypsTPqed4Btkqkn_-4/edit

**Comment by kitsonk** [comment]
I am aware of the previous discussion.

The point of the criticism was having to have arbitrary constructs to deal with type shadowing.  The suggestion does not eliminate the arbitrary constructs.  I would argue it makes it even more arbitrary.

**Comment by xiaoxiangmoe** [comment]
That's the debt you need to pay for having type safety for internal deno code.

**Comment by kitsonk** [comment]
We already have that with the current implementation. 😕

**Comment by ry** [comment]
I'm a bit confused by this discussion. I don't know what is being proposed.

The issue with TypeScript for internal code (linked design doc) has a lot more to do with size of source map in the binary, incremental build time when developing deno itself, and the complexity of op crates. There are some minor issues about us having problems with shadowing (I guess this is what is being addressed here) but it's only part of the problem.

**Comment by hax** [comment]
@ry So I guess some people (include @xiaoxiangmoe and me) have a misunderstanding that the main reason deno drop TS for internal code is because of shadowing issue 🤔

**Comment by ry** [comment]
@hax The shadowing problem is just makes a bad situation worse. It's a non-trivial situation that cannot be appreciated without having dealt with the internals of Deno.

Closing this issue.
