### ISSUE TITLE
Deno.watchFs("/home/rashid/myproject") throwing error "Permission denied (os error 13)"

### ISSUE THREAD

**Issue by thisrashid** [denoland/deno#6688]
My below code is not working. I am just trying what was given in documentation.

```
const watcher = Deno.watchFs("/home/warlog/projects/tamasha-api");
for await (const event of watcher) {
  console.log("event", event);
}
```

![Screenshot from 2020-07-08 19-10-05](https://user-images.githubusercontent.com/1191631/86925609-b6ff0e80-c14e-11ea-8ed0-bf3b7879afaa.png)

I tried to debug it and found that `core_ts_1.core.dispatchByName(opName, argsUi8, ...zeroCopy);` returns error as shown below:

![Screenshot from 2020-07-08 19-14-48](https://user-images.githubusercontent.com/1191631/86926263-7a7fe280-c14f-11ea-8728-d7b08cc69c8c.png)

### Environment
 - OS: Ubuntu 20.04 LTS
 - deno: 1.1.3
 
It seems it is a bug in `Deno.watchFs`. I do identified that it if current script is in the scope of watch it throws error.

**Comment by ebebbington** [comment]
That's a OS level error and permission denied, so I assume your host isn't allowing that script to do what it needs to do. I've ran your code (on MacOS) and pointed it to a different directory and it works.

Maybe check the permissions of `/home/warlog/projects/tamasha-api`? I know it's your own user but something might be out of whack

Try create a new tmp dir and chmod it to 777 then point your script to that and see if it works?

You'll get the exact same error message when running on powershell if PS isn't correctly ran as admin (not a bug for Windows, just saying)

**Comment by thisrashid** [comment]
I am trying to run `/home/warlog/projects/tamasha-api/index.ts`. My folder structure is as shown below:

![Screenshot from 2020-07-08 19-44-51](https://user-images.githubusercontent.com/1191631/86929613-a9985300-c153-11ea-9fef-cc8ed9238be4.png)

If I change the folder to any other folder of my repo, for example `/home/warlog/projects/tamasha-api/models`, it works. I also tried to watch some other folder in my home directory which is working.

The problem happens only when `/home/warlog/projects/tamasha-api/index.ts` file is in the scope. 

Probably it is platform dependent issue, since it is working in MacOS.

Also the error message "os error 13" is not helping in anyway to locate the issue. Which permission is required is not clear here.

**Comment by thisrashid** [comment]
Since you mentioned about PS I tried to run it root user. Since `deno`  is installed in my home folder I need to provide the complete path as below:

```
$ sudo bash
# /home/warlog/.deno/bin/deno run --allow-read index.ts
```
This is working. I want to understand what exactly changed in terms of permission?

My original issue was to use `denon` in my app. Now `denon` is working if I run it as root user, but it defeats the whole purpose of "secure by default".

**Comment by bartlomieju** [comment]
@thisrashid as described by @ebebbington the issue stems from your OS and fs permissions - it's not caused by Deno. 

> Since you mentioned about PS I tried to run it root user. Since deno is installed in my home folder I need to provide the complete path as below:

$ sudo bash
# /home/warlog/.deno/bin/deno run --allow-read index.ts
> This is working. I want to understand what exactly changed in terms of permission?

Root user has access to all directories in your FS. On the screenshot you provided there are `[error opening dir]` tags which suggest that these directories are owned by different user than the one your running currently.
