### ISSUE TITLE
Worker MessageChannel

### ISSUE THREAD

**Issue by rracariu** [denoland/deno#6691]
Seems that `MessageChannel` in missing from Deno APIs.

https://developer.mozilla.org/en-US/docs/Web/API/MessageChannel

It should be added as it allows safe communication between `Workers`

**Comment by lucacasonato** [comment]
Structured cloning support is a prerequisite for MessageChannel AFAIK. Ref #3557

**Comment by 00ff0000red** [comment]
@lucacasonato Do you think that https://github.com/denoland/deno/issues/9006 should be closed in favor of this?

**Comment by mhmdmar** [comment]
@lucacasonato  Is there any plan to add this API soon ?

**Comment by CrimsonCodes0** [comment]
@mhmdmar The prerequisite (<https://github.com/denoland/deno/issues/3557>) hasn't been finished yet, so not much can be done until then.

**Comment by mhmdmar** [comment]
> @mhmdmar The prerequisite (#3557) hasn't been finished yet, so not much can be done until then.

Thank you for your response :)

**Comment by surma** [comment]
With #3557 being closed now, is there anything else blocking `MessageChannel` from being implementable? I’m interested in helping out here (if desired), as I am keen to get [Comlink](https://github.com/GoogleChromeLabs/comlink) working with Deno.

**Comment by lucacasonato** [comment]
@surma I was just looking into it today. The main issue is that we do not support transferable for `Worker#postMessage` yet, so `MessageChannel` will not be super useful as the `MessagePort` can't be transferred between workers. What do you need to transfer between workers? Just the port, or also SAB?

**Comment by surma** [comment]
Oh of course, you are right. Transferables!

For Comlink itself I only need `MessagePort`. In user-space, the user can transfer any transferable using `Comlink.transfer()`. But I reckon the vast majority of Comlink use-cases don’t use transferables. So just having `MessagePort` support would allow me to get Comlink up and running.

**Comment by bartlomieju** [comment]
> The main issue is that we do not support transferable for `Worker#postMessage` yet, so `MessageChannel` will not be super useful as the `MessagePort` can't be transferred between workers.

That said I don't think there are any more blockers for that functionality. I remember that @inteon was looking into that at some point.

**Comment by lucacasonato** [comment]
I am sitting in a train with nothing better to do, so I'll give it a shot 🙃

**Comment by lucacasonato** [comment]
Got distracted and implemented `SharedArrayBuffer` sharing between Workers instead: #11040. Might be useful for WASM threads for someone. Have a pretty clear idea on how to do `MessageChannel` now though, so that will be up next.

**Comment by inteon** [comment]
Transferring `MessageChannel` via `postMessage()` probably can be done by implementing `write_host_object` and `read_host_object`. Although I'm not 100% sure this will just work.
And ofc all other logic (not related to transfer) also still needs to be added.
#10750 is related -> same issue for `BroadcastChannel` instead of `MessageChannel`

**Comment by lucacasonato** [comment]
@inteon Transferring `MessageChannel` happens via the `transferable` second argument to `postMessage`, not via the first argument that is structured cloned. `read_host_object` and `write_host_object` will only be needed for handling items that have the `[Serializer]` WebIDL extended attribute. `MessageChannel` doesn't have this, it only has `[Transferable]`.

I will open a WIP PR that adds `MessageChannel` and `MessagePort` very soon - just cleaning some stuff up right now. But to make them work properly with workers I will need to rewrite parts of our web worker implementation again - so might be couple more days until its actually ready.

**Comment by inteon** [comment]
> @inteon Transferring `MessageChannel` happens via the `transferable` second argument to `postMessage`, not via the first argument that is structured cloned. `read_host_object` and `write_host_object` will only be needed for handling items that have the `[Serializer]` WebIDL extended attribute. `MessageChannel` doesn't have this, it only has `[Transferable]`.
> 
> I will open a WIP PR that adds `MessageChannel` and `MessagePort` very soon - just cleaning some stuff up right now. But to make them work properly with workers I will need to rewrite parts of our web worker implementation again - so might be couple more days until its actually ready.

Thank you for explaining.
So structured cloning is only important for encoding the messages over the `MessageChannel` not for transferring the ports of the `MessageChannel`, that is done via the second argument to `postMessage`.

**Comment by CrimsonCodes0** [comment]
> Got distracted and implemented `SharedArrayBuffer` sharing between Workers instead: #11040. Might be useful for WASM threads for someone. Have a pretty clear idea on how to do `MessageChannel` now though, so that will be up next.

Actually, since you'd brought up WebAssembly threading, Wasm doesn't actually use JavaScript (Shared)ArrayBuffer objects, instead the JavaScript `WebAssembly.Memory` objects are supposed to be passed around instead. I can't find any references to how it works for them in particular, but I believe that `Memory { shared: false }` are serializable and transferable, while `Memory { shared: true }` can only be shared across the agent cluster (not transferred or serilalized).

With the implementation of that last PR, would passing `WebAssembly.Memory` objects work, or would that have to be done seperately?

**Comment by lucacasonato** [comment]
It should work. WASM.Memory with shared: true are really SABs internally.

**Comment by lucacasonato** [comment]
And we now have `MessageChannel` + `MessagePort`! Transferring them between workers has been broken out into #11074, and transferring them between `BroadcastChannel` into #11075

**Comment by lucacasonato** [comment]
Message port transfer across workers is now implemented too. It will be in the next canary release in about 40 minutes (`deno upgrade --canary`).

**Comment by surma** [comment]
Amazing. I’ll have a play! :D Thanks for your work on this, @lucacasonato!

**Comment by mhmdmar** [comment]
@lucacasonato I tried a simple script where I pass the port to a worker, the worker thread receives an empty object, I am using the latest version (deno 1.11.2+d54e3ea (canary, x86_64-pc-windows-msvc)) 

![image](https://user-images.githubusercontent.com/25887184/123239503-184af980-d4e8-11eb-967e-0d54ea811626.png)

**Comment by mhmdmar** [comment]
Also I thought that you should know, when I try to pass a shared array buffer to the worker, I get a cloning error

![image](https://user-images.githubusercontent.com/25887184/123240275-d8d0dd00-d4e8-11eb-96a5-798074c5ad8d.png)

**Comment by surma** [comment]
@mhmdmar Looking at the code, you need to _transfer_ the message port.

```js
worker1.postMessage({port: port1}, [port1]);
```

**Comment by mhmdmar** [comment]
@surma This doesn't match the syntax in the browser, but even when I try this I still get the same behaviour, any ideas how to fix this ?

**Comment by lucacasonato** [comment]
@mhmdmar It does match browser behaviour (message ports must always be included in the `transfers` array). You are likely running into bug #11102 though. As a workaround, get the port through the `.ports` array on the `MessageEvent` you receive in the worker.

**Comment by surma** [comment]
Yeah you definitely need to transfer a `MessagePort` :D

<img width="577" alt="Screen Shot 2021-06-24 at 19 00 33" src="https://user-images.githubusercontent.com/234957/123310911-7c88b000-d51e-11eb-89d5-fd936d2f0348.png">

**Comment by mhmdmar** [comment]
@lucacasonato  Cool, I tried the workaround and it works, still even though I can get the port, I don't see the postMessage handler triggered from the parent

![image](https://user-images.githubusercontent.com/25887184/123311809-40f6e180-d530-11eb-9ff4-1bba46657ffe.png)

**Comment by surma** [comment]
You need to listen on `port2` if you are sending `port1` to the worker.

**Comment by mhmdmar** [comment]
@lucacasonato  @surma  Thank you both so much, it works  :)
