### ISSUE TITLE
Consequent fetch requests sometime doesn't use DNS cache

### ISSUE THREAD

**Issue by danielbeeke** [denoland/deno#6696]
While doing a lot of fetch requests (3500) on 3 API's sometimes the dns can not be fetched.

Shouldn't this be cached and only possible fail in the beginning of the running of the script instead of somewhere in between?

```
Http: error sending request for url (REDACTED_INTERNAL_API): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known
    at unwrapResponse ($deno$/ops/dispatch_json.ts:43:11)
    at Object.sendAsync ($deno$/ops/dispatch_json.ts:98:10)
    at async fetch ($deno$/web/fetch.ts:296:27)
```

**Comment by ry** [comment]
I'm pretty sure we're using the system resolver, so the cache is out of our hands. I would guess this is not a Deno bug.

**Comment by bartlomieju** [comment]
FTI HTTP client used in `fetch` is one-off - ie. for each call to `fetch` a new instance of client is created

**Comment by danielbeeke** [comment]
@bartlomieju Does this may it may be a Deno bug?

**Comment by bartlomieju** [comment]
@danielbeeke we can discuss whether or not Deno should have a "singleton" HTTP client, but that must be dictated by spec for `fetch` API. If it should be shared between all calls then this issue is indeed a bug and should be fixed.

**Comment by danielbeeke** [comment]
See: https://fetch.spec.whatwg.org/#concept-connection-pool

It seems there is a concept 'Connection pool' were connections are reused.
I am not sure if this would mean Deno should reuse the connection.
For me (not too familiar with this spec) it looks like it.
