### ISSUE TITLE
Contributing guidelines

### ISSUE THREAD

**Issue by msal4** [denoland/deno#670]
Hey,
I noticed that the repo doesn't have contributing guidelines or a code of conduct, I could write one if I get the green light.

**Comment by benjamingr** [comment]
> I noticed that the repo doesn't have contributing guidelines or a code of conduct, I could write one if I get the green light.

I think adopting the standard CoC and contributing guidelines would help.

Between the two, I'd argue contributing guidelines (what's where in the code) would be the far more helpful part at this stage.

That said, I don't think a lot of work should be put into meta things as it increases noise (and churn) and Deno is still very very early.

**Comment by ry** [comment]
I’d rather get further along in functionality. Feel free to add to the readme if there’s something unclear about contributing. (Mentioning tools/format.py would be good.)

**Comment by msal4** [comment]
👍
