### ISSUE TITLE
createSync overwrites file if already exists

### ISSUE THREAD

**Issue by 3dfoster** [denoland/deno#6700]
According to [docs](https://doc.deno.land/https/github.com/denoland/deno/releases/latest/download/lib.deno.d.ts#Deno.createSync), createSync
> Creates a file if none exists or truncates an existing file and returns an instance of Deno.

Running a script with createSync however, will overwrite a file if it does exist.

To reproduce:
1. Run a file with the contents `Deno.createSync("db.json");`
2. After `db.json` has been created, enter an arbitrary value within it
3. Run the file from step 1 again
4. Notice contents of `db.json` have been erased

**Comment by yum650350** [comment]
I think it does what it says, `truncates an existing file`.

**Comment by 3dfoster** [comment]
> 
> 
> I think it does what it says, `truncates an existing file`.

Yes, I hadn't caught that initially. It would be nice if there was an option in the scenario I described, similar to the `a+` system flag in Nodejs for writing to files.

**Comment by yum650350** [comment]
> > I think it does what it says, `truncates an existing file`.
> 
> Yes, I hadn't caught that initially. It would be nice if there was an option in the scenario I described, similar to the `a+` system flag in Nodejs for writing to files.

Actually you can use [Deno.openSync](https://doc.deno.land/https/github.com/denoland/deno/releases/latest/download/lib.deno.d.ts#Deno.openSync) or  [Deno.open](https://doc.deno.land/https/github.com/denoland/deno/releases/latest/download/lib.deno.d.ts#Deno.open) and pass the [OpenOptions](https://doc.deno.land/https/github.com/denoland/deno/releases/latest/download/lib.deno.d.ts#Deno.OpenOptions).

Such as something like this:  

`const file = await Deno.open('./path/to/your/file', { read: true, write: true, create: true })`
