### ISSUE TITLE
Any module or api to encrypt with public key?

### ISSUE THREAD

**Issue by wenjoy** [denoland/deno#6712]
# How can I encrypt content with public key in deno?

I was working on a deno  project then I encountered a requirement to encrypt a content with public key. 
I can complete such thing with `crypto.publicEncrypt` easily but I cant find out a appropriate way with deno. 
I try to google but no luck.

**Comment by bartlomieju** [comment]
`crypto` APIs are not yet fully implemented. Please continue in #1891

**Comment by 89z** [comment]
https://github.com/denoland/deno/issues/1891
https://github.com/denoland/deno/issues/2372

https://github.com/denoland/deno/issues/6712
https://github.com/denoland/deno/issues/8006
https://github.com/denoland/deno_std/issues/48
