### ISSUE TITLE
Node Compatibility Issue

### ISSUE THREAD

**Issue by robeartoe** [denoland/deno#6720]
Hello all,
I'm having issues using the node compatibility modules.
I'm running everything according to the documentation..
```typescript
import { createRequire } from "https://deno.land/std/node/module.ts";
const require = createRequire(import.meta.url);
const path = require("path");
```

And I am trying to run a server with this command:
```bash
deno run --unstable --allow-net --allow-read index.ts
```

And I get the following errors:
```bash
error: TS2339 [ERROR]: Property 'dir' does not exist on type 'typeof Deno'.
  return Deno.dir("home");
              ~~~
    at https://deno.land/std/node/os.ts:139:15

TS2339 [ERROR]: Property 'dir' does not exist on type 'typeof Deno'.
  return Deno.dir("tmp");
              ~~~
    at https://deno.land/std/node/os.ts:185:15

Found 2 errors.
```

I've upgraded to the latest versions and I have not had any luck.
```bash
deno --version
deno 1.1.3
v8 8.5.216
typescript 3.9.2
```

Is there anything I'm doing wrong? I've checked through the issues and thought running the --unstable argument will solve the issue. Thank you!

**Comment by nayeemrmn** [comment]
Run `deno cache -r index.ts` to reload those modules.

Better, replace imports from `https://deno.land/std/` with `https://deno.land/std@0.60.0`.

**Comment by robeartoe** [comment]
Interesting how that did the trick.
Hmm. Now I know. I'm slowly understanding deno as a whole.

Thank you so much @nayeemrmn for the answer!

I have a quick question, for all of Deno's standard library modules, do we always have to include the version for all of them when we import them? Or will it come to a point, when we'll import the module, and it'll just fetch the latest by default?

Thanks again!

**Comment by kitsonk** [comment]
> Or will it come to a point, when we'll import the module, and it'll just fetch the latest by default?

It is fetching the latest by default, the problem is latest has breaking changes to make it work with the `master` version of Deno.  That is why we print the warning in the console when you import `std` off master.
