### ISSUE TITLE
bufio in serve throws "error: trailing characters at line 31 column 2"

### ISSUE THREAD

**Issue by trivikr** [denoland/deno#6724]
Refs: https://github.com/fastrodev/fastro/issues/7

This issue appears to be specific to Ubuntu/Linux

<details>
<summary>System Information</summary>

```console
$ deno --version
deno 1.1.3
v8 8.5.216
typescript 3.9.2

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04 LTS
Release:        20.04
Codename:       focal
```

</details>

<details>
<summary>Code</summary>

```ts
import { serve } from "https://deno.land/std@0.60.0/http/server.ts";

const port = 3000;
const s = serve({ port });

console.log("deno_http listen on", port);
for await (const req of s) {
  req.respond({ body: "Hello World\n" });
}
```

</details>

<details>
<summary>Output</summary>

```console
$ deno run --allow-net deno_http.ts &
[1] 47720
$ error: trailing characters at line 31 column 2
Imported from "https://deno.land/std@0.60.0/io/bufio.ts:9"
```

</details>

**Comment by hork71** [comment]
Can't reproduce

![afbeelding](https://user-images.githubusercontent.com/66360109/87315740-10878480-c525-11ea-972d-b62def362dff.png)


![afbeelding](https://user-images.githubusercontent.com/66360109/87315649-f0f05c00-c524-11ea-944a-1090924cb060.png)


![afbeelding](https://user-images.githubusercontent.com/66360109/87315381-bedefa00-c524-11ea-857f-9276c78e85bb.png)

$ deno run --allow-net mod.ts &
[1] 1729
$ deno_http listen on 3000

**Comment by trivikr** [comment]
This issue is not reproducible after upgrading to `deno@1.2.0` and `std@0.61.0`
It can be resolved, but can also be kept open to check investigate why it was happening in the past.
