### ISSUE TITLE
performanceMeasure in //cli/tests/unit/performance_test.ts is flaky

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#6725]
Example: https://github.com/denoland/deno/runs/863630775

Test failed on unrelated change in docs.

Ref #6421, cc @kitsonk

**Comment by kitsonk** [comment]
Hmmm... a timer is scheduled to fire at 100ms, and the duration is expected to be between 100 and 200ms, and it appears that in this case the duration was in excess of 200ms (the whole test ran in 203ms)... so on contended servers it seems timing are really poor!  Crazy that there was that much delay in the scheduling.
