### ISSUE TITLE
False Alarm AVAST - Deno 1.2 Detected as Malware

### ISSUE THREAD

**Issue by gungunfebrianza** [denoland/deno#6739]
Hello guys , i was tried to upgrade my deno into version 1.2 but my avast recognized the binary as virus?
what do you think ?

![image](https://user-images.githubusercontent.com/5908094/87413061-01bbd300-c5f4-11ea-8176-02e02fdf54a7.png)

**Comment by Spoonbender** [comment]
Same as #5690

**Comment by MarkTiedemann** [comment]
Seems to be fixed already: https://www.virustotal.com/gui/file/eeb5fcdeda31929a6e58469e554af0a4dd7067eb7f17af0fe083630d3e5c62f6/detection

**Comment by el3um4s** [comment]
![image](https://user-images.githubusercontent.com/23579630/97007566-e8ef8180-1541-11eb-9ebc-6d8da5656aeb.png)

I have the same problem

**Comment by TheAndroidGuy** [comment]
AVG Antivirus detects the same.
