### ISSUE TITLE
Date.toLocaleDateString options not working

### ISSUE THREAD

**Issue by daquinoaldo** [denoland/deno#6740]
Hi,

the `toLocaleDateString` method of the class Date seems ignoring the options.

**Example**
```
console.log(new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" }))
```

Output on Node.js and browsers (expected)
```
July 14, 2020
```

Output on Deno v1.2.0 (not working)
```
Tue Jul 14 2020
```

I tested both on a TS file and through deno command line (`deno eval ...`).

**Comment by SyrupThinker** [comment]
Known issue, due to #1968

**Comment by daquinoaldo** [comment]
There is an ETA for the fix?

**Comment by bartlomieju** [comment]
@daquinoaldo not ETA currently, please continue in #1968

**Comment by daquinoaldo** [comment]
Thank you anyway for your time.
