### ISSUE TITLE
Latest update breaks application.

### ISSUE THREAD

**Issue by xReveres** [denoland/deno#6744]
After updating Deno to latest version 1.2.0 I got 2 errors:
```bash
error: TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname
                 ~~~
    at https://deno.land/std@v0.53.0/path/win32.ts:911:18

TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname;
                 ~~~
    at https://deno.land/std@v0.53.0/path/posix.ts:433:18

Found 2 errors.
```
I have global deps.ts file with dependencies but are actual @0.61.0
Also I tried run with argument `-L debug` but no more information.
Any ideas what i can do to locate problem ?

**Comment by ebebbington** [comment]
@xReveres see https://dev.to/srnv/deno-1-2-0-url-argument-type-solutions-37m0

The issue most likely resides in any third party dependencies you have, that themselves have outdated dependencies - something is importing from std v0.53.0

**Comment by nayeemrmn** [comment]
Duplicate of #6737.

**Comment by xReveres** [comment]
@nayeemrmn Thank you, but this issue doesn't help my issue.
@ebebbington Thanks, few minutes ago i tried to do similar steps like in this article:
`deno info --unstable --no-check startup.ts`
Where startup.ts is entry to my application but I got:
`error: Uncaught SyntaxError: The requested module 'https://deno.land/std@0.53.0/async/mod.ts' does not provide an export named 'Deferred'`
Also when I tried:
`deno info --unstable --no-check deps.ts`
`error: Uncaught SyntaxError: The requested module 'https://deno.land/std@0.53.0/async/mod.ts' does not provide an export named 'Deferred'`

**Comment by ebebbington** [comment]
> @nayeemrmn Thank you, but this issue doesn't help my issue.
> @ebebbington Thanks, few minutes ago i tried to do similar steps like in this article:
> `deno info --unstable --no-check startup.ts`
> Where startup.ts is entry to my application but I got:
> `error: Uncaught SyntaxError: The requested module 'https://deno.land/std@0.53.0/async/mod.ts' does not provide an export named 'Deferred'`
> Also when I tried:
> `deno info --unstable --no-check deps.ts`
> `error: Uncaught SyntaxError: The requested module 'https://deno.land/std@0.53.0/async/mod.ts' does not provide an export named 'Deferred'`

In a nutshell, to upgrade to deno v1.2.0, your dependencies must be updated (everything, so dependencies of your dependencies too) though this isn't the case for everything, it's just generally easier to manage - so the `async` module should really be using std v0.61.0. Downgrade to the previous version you were on for the time being

**Comment by xReveres** [comment]
@ebebbington Yes as you said, for now I must downgrade deno and restore dependencies.
