### ISSUE TITLE
deno cache should allow self to cache worker scripts

### ISSUE THREAD

**Issue by brandonkal** [denoland/deno#6753]
As the title says, I expect `deno cache` to work on all files deno understands. It shouldn't require a special flag.

I should be able to do this in a docker build:
```Dockerfile
RUN deno cache main.ts host.ts my.worker.ts 
```

**Comment by kitsonk** [comment]
Hrmmm... I think the way we would have to solve this is to add a seperate flag to cache, so you would have to do this:

```bash
$ deno cache main.ts host.ts
$ deno cache --worker my.worker.ts
```

**Comment by brandonkal** [comment]
Yes that wouldn't provide a very good experience.

1. VSCode TypeScript allows self everywhere. I don't see the harm in doing the same.
2. Having two common tools say different things about the types isn't fun.
3. If I write tools that compile a batch of files I have to read the file contents and decide if I have to include this extra `--worker` flag.
4. I have to run more commands.
5. I can't just watch files and run `deno cache` on change.
6. It adds complexity

What if I want to write a module that starts up a websocket client if it is not running in a worker context but otherwise uses self.postMessage? It's not a runtime error unless I call it in a context where it doesn't exist.

Users can easily use an eslint rule if they want to ban self inside of files. Leaving it until `deno cache` or `deno run` isn't as productive.

**Comment by kitsonk** [comment]
One of the main purposes of having TypeScript support is the ability to have your files validated against the types that are available at runtime.  "Just because VSCode is permissive" isn't a compelling argument to weaken the type checking of Deno.  It is harmful if you are expecting Deno to catch runtime type errors.  One extra command which is typed one in a docker configuration file doesn't sound burdensome to me.  You are focused on `self` but that isn't the only difference in a worker.

Another option is you can use:

```dockerfile
RUN deno cache --no-check main.ts host.ts my.worker.ts
```

Where you are confident your code is type safe.

**Comment by brandonkal** [comment]
That would be giving users a false sense of security. Where it depends on the flags you used and not the runtime it actually executes in.

Even if Deno must be pendantic here, convention is better than piling on more flags.
Example:
*.worker.ts -- allow worker context


Deno is particularly slow to start up the typechecker so that's another reason to avoid adding a flag.

This is something that is better in deno lint than TypeScript IMHO.

**Comment by nayeemrmn** [comment]
This should be reopened, `deno cache --worker` was reverted.

**Comment by nayeemrmn** [comment]
No nevermind, tracked in #8219.

**Comment by kitsonk** [comment]
@nayeemrmn I will champion this again inside the core team and try to agree on a solution. We also have the challenge of supporting worker scripts in the language server in editors too. Both those are necessary and should compliment each other.
