### ISSUE TITLE
Why not make a powerful args parser?

### ISSUE THREAD

**Issue by mrmaxnest** [denoland/deno#6763]
Why not make an args parser that can do more than `std/flags`? (similar to `yargs`)

**Comment by srepollock** [comment]
Have you checked out the third party module [args](https://deno.land/x/args)?

**Comment by mrmaxnest** [comment]
@srepollock Thank you, I have not seen. But I think it would be nice to add this (or something similar) to `std`.

**Comment by buttercubz** [comment]
> @srepollock Gracias, no lo he visto. Pero creo que sería bueno añadir esto (o algo similar) a .`std`

it's already in `std`  

```javascript
import { parse } from "https://deno.land/std/flags/mod.ts";

console.dir(parse(Deno.args));
```

**Comment by srepollock** [comment]
Yo I did not see that! Fantastic!

**Comment by timreichen** [comment]
Could be closed?
