### ISSUE TITLE
Unit tests should run with `--reload` flag

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#677]
I had a unit test pass locally, but fail on CI due to the tests not being run with the `--reload` flag and the TypeScript file being pulled from cache.  We should use `--reload` for units like we do for the functional tests.

**Comment by ry** [comment]
Yes - I agree but - that suggests a deeper problem of the cache not being updated or pulled from correctly. Do you know any more?

**Comment by kitsonk** [comment]
@ry, no, the unit test (`compiler_test.ts`) was actually unchanged, but I made a breaking change in just the types in deno (which is what unit tests are good for 😄 ).  So the cache was "valid", but I forgot to manually clear my cache, and so it simply reran the unchanged code, which was still valid at runtime, but had a type only error what didn't get picked up until it ran on CI. (It was why I thought #662 was ready to go)

**Comment by ry** [comment]
@kitsonk Ideally the cache would also include which a version for deno (#472). Even if we had the version included in the cache checksum, you would have still experienced the bug - so ideally we'd even have a build number...  Let's add the --reload parameter for now.
