### ISSUE TITLE
Windows installation path

### ISSUE THREAD

**Issue by amur-tiger** [denoland/deno#6779]
Currently, using the command `iwr https://deno.land/x/install/install.ps1 -useb | iex` (as per documentation) installs Deno into `%USERPROFILE%/.deno`.

I see two issues with this:
* This ignores Windows conventions. Programs should not put their working files directly into the user folder.
* Dot-files and -folders do not have any special meaning on Windows.

A better place for installation (if installed per user profile) would be `%LOCALAPPDATA%/Deno`.

**Comment by MarkTiedemann** [comment]
> Dot-files and -folders do not have any special meaning on Windows.

Yes. How is this an issue?

> This ignores Windows conventions. Programs should not put their working files directly into the user folder. A better place for installation (if installed per user profile) would be `%LOCALAPPDATA%/Deno`.

Deno already puts working files (`\deps`, `\gen`, `deno_history.txt`) into `%localappdata%\deno`.

`$home\.deno` is only used for the executable (`.\bin\deno.exe`).

I think `$home\.deno` was originally chosen for simplicity since a home directory exists on all platforms.

(Note that `$home` in powershell  is equivalent to `%userprofile%` in cmd.)

AFAIK, there's no official binary directory on Windows (except maybe `%systemroot%\system32`, but that one requires elevation).

**Comment by amur-tiger** [comment]
Having a dot-file is not an issue per-se, but not idiomatic. But fair enough.

I'm happy to see that Deno already uses `%localappdata%` for working files, but why not the installer?

`system32` though is definitely not a good place for 3rd-party executables. `%programfiles%` is the place to go for system-wide installations, and the user folder for user installations, as @Spoonbender said. Though I'm arguing that putting it directly into the user folder instead of in a sub-folder like `%localappdata%` is sub-optimal, because it mixes executables and other program data with the users actual documents.

**Comment by MarkTiedemann** [comment]
> Additionally most installers let the user specify a custom location.

That's what the `DENO_INSTALL` env var is for.

> I'm happy to see that Deno already uses `%localappdata%` for working files, but why not the installer?

AFAIK, `%localappdata%` is for user-specific local data of an application. This is data that you can usually delete without uninstalling the application itself.

TBH, I kinda like that I can run `rd /s %localappdata%\deno` to clear all temporary deno data.
