### ISSUE TITLE
Assert: 'sorted' does not exist in type 'InspectOptions'

### ISSUE THREAD

**Issue by tarsupin** [denoland/deno#6780]
I have a very simple oak server running both locally and on an external server. It is hosting static content, nothing else.

I ran `deno cache --reload server.ts` yesterday, and got the following:

```
error: TS2345 [ERROR]: Argument of type '{ depth: number; sorted: boolean; trailingComma: boolean; compact: boolean; iterableLimit: number; }' is not assignable to parameter of type 'InspectOptions'.
  Object literal may only specify known properties, and 'sorted' does not exist in type 'InspectOptions'.
        sorted: true,
        ~~~~~~~~~~~~
    at https://deno.land/std@0.61.0/testing/asserts.ts:26:9
```

I ran `deno cache --reload server.ts` again today with the same result, so I figured I should probably post the issue here.

**Comment by nayeemrmn** [comment]
Upgrade to Deno 1.2.0, whatever version of oak you're using isn't compatible with earlier versions of Deno.

**Comment by tarsupin** [comment]
Yep, that resolved everything. Well spotted.
