### ISSUE TITLE
A dependency with dependencies - how to load it?

### ISSUE THREAD

**Issue by Swader** [denoland/deno#6784]
I'm a bit puzzled on how to load a project that has dependencies of its own based on relative paths. For example, I tried loading 

```ts
// deps.ts
import u8aToString from "./vendor/polkadot-js/common/packages/util/src/u8a/toString.ts";
export { u8aToString };
```

and then 

```ts
// test.ts
import { u8aToString } from "./deps.ts";

console.log(u8aToString(new Uint8Array([0x68, 0x65, 0x6c, 0x6c, 0x6f])));
```

This works.

But when I try to import and export another, bigger package:

```ts
// deps.ts
import u8aToString from "./vendor/polkadot-js/common/packages/util/src/u8a/toString.ts";

import ApiPromise from "./vendor/polkadot-js/api/packages/api/src/index.ts";
import WsProvider from "./vendor/polkadot-js/api/packages/api/src/index.ts";

export { u8aToString, ApiPromise, WsProvider };
```

I get the error:

```bash
error: relative import path "@polkadot/util" not prefixed with / or ./ or ../ Imported from "file:///home/swader/repos/deno-scripts/vendor/polkadot-js/api/packages/api/src/index.ts"
```

The path `@polkadot/util` is part of the `index.ts` file. It would be nice if I could define an alias of some kind:

```json
// deno.config
{
  "alias": {
    "@polakdot/util": "/vendor/polkadot-js/common/packages/util"
  }
}
```

... so that Deno could use this package I already have locally.

Or am I missing something elementary on how to include bigger projects that have interdependent modules?

**Comment by Soremwar** [comment]
You are probably leaving out import maps, they accomplish exactly what you described in your "alias" example

https://deno.land/manual/linking_to_external_code/import_maps

However I can't seem to find where the alias you are specificying is being called in the example you just provided

Is there anywhere inside the files of the second example something like `import x from 'your_alias';`?

**Comment by Swader** [comment]
Yes, the files in that package have such imports. I'll take a look at import maps, thanks

**Comment by bartlomieju** [comment]
As pointed by @Soremwar it seems your imports require import-map.
