### ISSUE TITLE
error: The subcommand 'run' wasn't recognized. Did you mean 'run'?

### ISSUE THREAD

**Issue by fritzblue** [denoland/deno#6790]
The command `deno --quiet -- run <my_script>` produces the following error:

```
error: The subcommand 'run' wasn't recognized
        Did you mean 'run'?

If you believe you received this message in error, try re-running with 'deno -- run'

USAGE:
    deno --quiet

For more information try --help
```

Version information:

deno 1.2.0
v8 8.5.216
typescript 3.9.2

**Comment by Spoonbender** [comment]
This seems related to a `clap` behavior: https://github.com/clap-rs/clap/issues/1744

**Comment by Spoonbender** [comment]
Notice that it does work with the following syntax:
`deno --quiet run -- <my_script>`

We need to decide if the format specified in the bug is valid or not, and perhaps improve some documentation, or try to issue a PR to improve `clap`

**Comment by caspervonb** [comment]
Ignoring the parsing details of clap, the usage says this is invalid.

```
USAGE:
    deno run [OPTIONS] <SCRIPT_ARG>...
```

**Comment by nayeemrmn** [comment]
@caspervonb If you're referring to the placement of `--quiet`, it's a global flag so putting it before the subcommand does work: `deno --quiet run mod.ts`.

It's apparently intentional that subcommands must come before `--`, so as @Spoonbender said this is strictly an error message problem tracked in https://github.com/clap-rs/clap/issues/1744.

**Comment by caspervonb** [comment]
> @caspervonb If you're referring to the placement of --quiet, it's a global flag so putting it before the subcommand does work: deno --quiet run mod.ts.

Was referring to the placement of the subcommand; anything after -- is conventionally positional args given to the invoked command, as is the case here.

So this works as I'd expect based on the usage message, error message from clap could be a bit clearer however.

**Comment by bartlomieju** [comment]
Clap issues is closed, but the error output is the same. I'm not sure if we can fix this easily.

**Comment by lino-levan** [comment]
This issue seems to be resolved:

```
$ deno --quiet -- run mod.ts
error: Found argument 'run' which wasn't expected, or isn't valid in this context

	If you tried to supply `run` as a subcommand, remove the '--' before it.
```

(not relevant but this is from an m1 mac, deno 1.29.1)
