### ISSUE TITLE
Does Deno support before_test and after_test events?

### ISSUE THREAD

**Issue by reselbob** [denoland/deno#6798]
If so, how?

I've been reviewing the documentation. Can seem to find anything.

Thanks in advance.

**Comment by nayeemrmn** [comment]
There isn't. Test hooks were proposed as part of #4092. There were some suggestions as to how it could be implemented separately or on top of `Deno.test()`. It was ultimately declared out of scope since Rust has fared well without this feature.

**Comment by ry** [comment]
That feature isn’t necessary.

**Comment by reselbob** [comment]
Oh, but I have a test where I want to start am API REST server I wrote in Deno and then want to run HTTP tests against it. 

Thus, my desire to start the server before testing, do the tests and then nuke the server.

As of now, the way I'll handle it is to spin up the REST API in a Docker container, do my tests and then nuke the container.

Is this the best way to go about things?

**Comment by lucacasonato** [comment]
You can do that without a before test or after test event.

```ts
await startServer()

window.unload = () => {
   stopServer()
};

Deno.test(...)
Deno.test(...)

**Comment by nayeemrmn** [comment]
```ts
Deno test("start server", async () => {
  await startServer();
});

Deno.test(...);
Deno.test(...);

Deno test("start server", async () => {
  stopServer();
});
```
works I think.

**Comment by thesmart** [comment]
> ```ts
> Deno test("start server", async () => {
>   await startServer();
> });
> 
> Deno.test(...);
> Deno.test(...);
> 
> Deno test("start server", async () => {
>   stopServer();
> });
> ```
> 
> works I think.

A issue with this approach is that it makes using test `--filter` brittle because it is too easy to accidentally filter out the start/stop tests.
