### ISSUE TITLE
std/fs: writeJson missing newline at the end of file

### ISSUE THREAD

**Issue by tranzystorek-io** [denoland/deno#6810]
The `writeJson` function does a `JSON.stringify()` without appending a newline to the end of file. This creates an incorrect file (POSIX-wise).

**Comment by tranzystorek-io** [comment]
I would gladly make a PR, but i would need guidance as to how the platform specific EOLs (LF, CRLF) are inserted into text with Deno

**Comment by jacobgc** [comment]
You could use [Deno.Platform.os](https://deno.land/typedoc/interfaces/_deno_.platform.html#os) It will return `win`, `mac` or `linux`. windows use the `\r\n` line ending and linux/macos use `\n`. The solution should also probably go just after [here](https://github.com/denoland/deno/blob/cde4dbb35132848ffece59ef9cfaccff32347124/std/fs/write_json.ts#L24).

Good luck with your contribution!

**Comment by tranzystorek-io** [comment]
> 
> 
> _Edit_ ignore this info for now. Deno.Platform doesn't actually exist*
> You could use [Deno.Platform.os](https://deno.land/typedoc/interfaces/_deno_.platform.html#os) It will return `win`, `mac` or `linux`. windows use the `\r\n` line ending and linux/macos use `\n`. The solution should also probably go just after [here](https://github.com/denoland/deno/blob/cde4dbb35132848ffece59ef9cfaccff32347124/std/fs/write_json.ts#L24).
> 
> Good luck with your contribution!

Seems like `Deno.build` can give me the `os` property

**Comment by jacobgc** [comment]
> 
> 
> > _Edit_ ignore this info for now. Deno.Platform doesn't actually exist*
> > You could use [Deno.Platform.os](https://deno.land/typedoc/interfaces/_deno_.platform.html#os) It will return `win`, `mac` or `linux`. windows use the `\r\n` line ending and linux/macos use `\n`. The solution should also probably go just after [here](https://github.com/denoland/deno/blob/cde4dbb35132848ffece59ef9cfaccff32347124/std/fs/write_json.ts#L24).
> > Good luck with your contribution!
> 
> Seems like `Deno.build` can give me the `os` property

So it can. Doing a quick google of getting OS in deno I landed [here](https://deno.land/typedoc/interfaces/_deno_.platform.html). But it looks like it isn't actually exported. And looking at the std/node/os.ts its unstable to use. So yeah it looks like Deno.build looks like the way to do it!
