### ISSUE TITLE
No shared code between compiler and runtime snapshots

### ISSUE THREAD

**Issue by ry** [denoland/deno#6812]
[Currently the runtime and compiler snapshot share a lot of code.](https://github.com/denoland/deno/blob/fa61956f03491101b6ef64423ea2f1f73af26a73/cli/build.rs#L103-L120) Currently every function available in the runtime is available in the compiler snapshot: `fetch()`, `setTimeout()` etc. However the compiler snapshot has no need for much of this code.

The compiler and runtime have ultimately very different purposes. The runtime is exposed to users, the compiler is completely internal.

We want the compiler snapshot to be as small as possible.

Ref https://github.com/denoland/deno/pull/6809

**Comment by kitsonk** [comment]
As I mentioned in other threads, I have started work on a stand alone compiler crate that would only have the code it needs to do TypeScript compiling, which would be a single file `.js` file, plus the ability to create snapshots.  It is based on `deno_typescript` but should be able to provide all that is needed for the CLI, but also be independent, and so in theory reusable.  It will be abstracted from the cache.

**Comment by kitsonk** [comment]
(It also incorporates the re-worked bundling that was in my PR for deno_typescript that moves the bundling out of TypeScript and emits valid source maps)
