### ISSUE TITLE
Advanced formatting for logger

### ISSUE THREAD

**Issue by benkeil** [denoland/deno#6821]
It would be very nice if the logger would support more formatting features, like e.g. log4j in java.

```
log.info("Key: %s - value: %o", "foo", { foo: "bar" }, { depth: 10 });
```

Also maybe some extra configuration for e.g. how deep `%o` should print child properties.

**Comment by bartlomieju** [comment]
Logger already supports function-based formatting as well as template literals, and we're thinking about removing string interpolation in #7056. So I think we won't implement that.
