### ISSUE TITLE
Custom errors missing name of class

### ISSUE THREAD

**Issue by benkeil** [denoland/deno#6822]
If you print an error, it should have the name of the class.

```typescript
export default class RuntimeError extends Error {

  constructor(message: string) {
    super(message);
    this.name = new.target.name; // something like this is missing per default
  }

}
```

**Comment by lucacasonato** [comment]
Deno is currently doing the same thing as Chrome and Firefox, which is not automatically setting the name of the `Error`. This is how it is specified in ECMA262.

What Deno is doing is the correct behaviour.

**Comment by benkeil** [comment]
Your Right, I was in the wrong way.
