### ISSUE TITLE
deno bundle @ts-nocheck must appear in first 5 lines

### ISSUE THREAD

**Issue by brandonkal** [denoland/deno#6824]
The comment is ignored if it doesn't appear within the first 5 lines at least in VSCode. The copyright header for the loader is throwing this off.

**Comment by kitsonk** [comment]
> the first 5 lines at least in VSCode

Using what plugin? Why would this be an issue for the Deno CLI?  Not entirely sure what problem this is causing either.

**Comment by brandonkal** [comment]
The deno plugin. The issue is that if you open a bundled JS file, TypeScript underlines everything in red. Moving the comment to the top fixes the issue and it is a simple fix.

**Comment by kitsonk** [comment]
So, why wouldn't it be an issue for the plugin?

**Comment by brandonkal** [comment]
I just tested without the deno plugin enabled. The issue remains. It doesn't really make sense to work around how the TypeScript ecosystem works within a plugin. It's useful to be able to open these files in an editor without needing extra plugins to mute the noise. Given that Deno inserts this comment, it would make sense to place it at the top as it should be.

I'm happy to make a PR for this.

**Comment by kitsonk** [comment]
As of Deno 1.5 we emit just a single ES module with no special annotations or copyright header.  This means re-importing it into Deno will behave as default as any other JS file.  Therefore at this point this is unactionable.
