### ISSUE TITLE
Go-like Importing Scheme

### ISSUE THREAD

**Issue by ZiQiLN** [denoland/deno#6825]
Actual import scheme of Deno is a little inefficient and can be done in better way - scheme used in Golang would be ideal for Deno.

For example:

```
// for core deno libraries
import * as path from 'path'

// for community libraries
import * as sample from 'github/sample/sample'
```

I would like to hear community opinion about that idea.

**Comment by crowlKats** [comment]
we are following the web spec. this is not something we can do.

**Comment by kitsonk** [comment]
Everything is just an explicit URL with no "magic" resolution.  This proposal would require magical resolution and coupling to things like how code is structured in GitHub.  That is not something that Deno wants to do.

For the `Deno` namespace, if the [Built-in modules](https://github.com/tc39/proposal-built-in-modules) proposal for ECMAScript/JavaScript ever got close to being adopted, Deno would consider using that syntax to make the `Deno` namespace a built-in module.

**Comment by Soremwar** [comment]
That's some news @kitsonk !

**Comment by timreichen** [comment]
I think you also could set up [importmaps](https://deno.land/manual/linking_to_external_code/import_maps) to make it work as you intended?

**Comment by ZiQiLN** [comment]
Thanks, @kitsonk and @timreichen for your response. I didn't see import maps in the documentation, and that's something that I was searching for. I think this issue can be closed now.
