### ISSUE TITLE
proposal: conditional functions

### ISSUE THREAD

**Issue by muuvmuuv** [denoland/deno#6826]
This proposal might not match any ECMA or JavaScript/TypeScript standard but I came across the idea after working with many if statements when checking for a device or environment conditions (e.g. if it is an iOS device). 

At the moment an if-statement looks like that:

```js
if (isIos()) {
  console.log("iOS Device")
}
```

I would like to introduce conditional-functions:

```js
isIos { // without `()` would call a function without passing params, less writing
  console.log("iOS device")
} else {
  console.log("Not an iOS device")
}
isIos(window) {
  console.log("iOS device")
}
```

This is just an idea for simpler writing, and I am aware that this only works with a compiler to work in web but I kind of like it because it is simpler to read and write. 

Would like to hear your opinions and if __deno__ is open for such optimizations.

---

Edit: Just noticed that ofc they must return a boolean but I am open for other suggestions regarding the syntax

**Comment by kt3k** [comment]
Deno follows TypeScript/JavaScript standards. What you propose is out of scope of Deno.

If you want to propose such changes to JavaScript, you have to submit your proposal to [TC39](https://tc39.es/). They should be open for such contribution. cf. https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md#new-feature-proposals
