### ISSUE TITLE
Upgrade TypeScript before 1.3.0 release

### ISSUE THREAD

**Issue by David-Else** [denoland/deno#6827]
```shell
deno --version
deno 1.2.0
v8 8.5.216
typescript 3.9.2
[david@gigabot ~]$ 
```
The current version is `3.9.7`, many bugs and regressions have been fixed:
https://github.com/microsoft/TypeScript/releases/tag/v3.9.7

**Comment by nayeemrmn** [comment]
Closed in #7036.
