### ISSUE TITLE
[Discussion] std/path: rename methods

### ISSUE THREAD

**Issue by timreichen** [denoland/deno#6829]
I came across a naming inconsistency. I know that the naming convention for some of these methods has historic reasons,  but in ```JS``` there are normally no abbreviations for functions and methods.

Affected exports are
- ```sep```
- ```extname(path: string)```
- ```dirname(path: string)```

So I wonder if it would make sense to rename them to have full descriptive names. Maybe something like this:

- ```separator```
- ```extension(path: string)```
- ```directory(path: string)```

What do you think?

**Comment by nayeemrmn** [comment]
- `sep` -> `separator`
- `extname(path: string)` -> `getExtension(path: string)`
- `dirname(path: string)` -> `getParent(path: string)`
- `basename(path: string)` -> `getFileName(path: string)`

These are taken from [Rust](https://doc.rust-lang.org/std/path/struct.Path.html). Other than the `get` prefixes, that is... so I guess you can fight me there.

**Comment by caspervonb** [comment]
So these are well known names that you'll find in the std libraries of pretty much any language or runtime including but not limited to:
- C
- C++
- Rust
- Rython
- Puby
- Node

Go is slightly different but variation is small enough that there's no need to read the docs, e.g dirname is `filepath.Dir`.

**Comment by nayeemrmn** [comment]
As far as I can remember, we usually favour Rust names in these situations. They're more modern and consistent with each other. The module system they are delivered through is more similar to JS's. It's especially easy when the Unix names are so terrible. A path has a parent, not a directory. And maybe we _shouldn't_ arbitrarily violate camel case?

**Comment by caspervonb** [comment]
Hmm based on the Deno namespace seems to have more POSIX influence, but I digress.

My point was just that basename, extname etc have well established prior art and with that comes intrinsic knowledge associated with those names, proposed names do not.

Renaming sep to separator seems appropriate tho.

**Comment by nayeemrmn** [comment]
> with that comes intrinsic knowledge associated with those names, proposed names do not.

A name which is direct and constructed logically is inherently familiar. For example, no one can be reasonably surprised by [`path.extension()`](https://doc.rust-lang.org/std/path/struct.Path.html#method.extension). There is nothing opinionated about its construction, like an abbreviation or a meaningless suffix. No misuse of terminology. The casing is consistent with the rest of the lib; we won't end up with `basename()` and [`fileStem()`](https://doc.rust-lang.org/std/path/struct.Path.html#method.file_stem) side-by-side.

**Comment by timreichen** [comment]
> A name which is direct and constructed logically is inherently familiar. For example, no one can be reasonably surprised by [`path.extension()`](https://doc.rust-lang.org/std/path/struct.Path.html#method.extension). There is nothing opinionated about its construction, like an abbreviation or a meaningless suffix. No misuse of terminology. 

I agree with that. And ```std/fs``` module has the same naming problem btw. I opened a separate issue with examples and and a possible solution  [here](https://github.com/denoland/deno/issues/6837).

I am pretty sure a good and consistent naming convention will be a win in the long run.

**Comment by timreichen** [comment]
Closing in favor of #6829
