### ISSUE TITLE
deno bundle should ignore `import type`

### ISSUE THREAD

**Issue by brandonkal** [denoland/deno#6834]
When importing a large type-only module, the generated code should exclude the imported module.
In my case, the imported module has many unused `export function isX` functions that get emitted.

**Comment by lucacasonato** [comment]
This will likely be fixed when we move to bundling with SWC.

**Comment by kitsonk** [comment]
If it is a type only module, it should be a `.d.ts` file, or if you are only using types from a file it should be a `import type` declaration.

That being said, bundling now does tree shaking as of 1.5.
