### ISSUE TITLE
[Discussion] std/fs: Rename abbreviated methods

### ISSUE THREAD

**Issue by timreichen** [denoland/deno#6837]
Also in dicussion [here](https://github.com/denoland/deno/issues/6829), abbreviated method names are not really a thing in ```JS```. ```std/fs``` has naming inconsistencies as of today due to historical naming conventions. For example ```mkdir``` (lowercase and abbreviated) and ```makeTempDir``` (camelcase and semi-abbreviated).

I therefore propose to drop some historical console terms in favor of full descriptive and unified names:
- ```iter```-> ```iterator``` (as used in ```Symbol.iterator```)
- ```iterSync```-> ```iteratorSync```

- ```mkdir```-> ```makeDirectory``` (alternative: ```createDirectory```)
- ```mkdirSync```-> ```makeDirectorySync``` (alternative: ```createDirectorySync```)
- ```makeTempDir```-> ```makeTemporaryDirectory``` (alternative: ```createTemporaryDirectory```)
- ```makeTempDirSync```-> ```makeTemporaryDirectorySync``` (alternative: ```createTemporaryDirectorySync```)
- ```readDir```-> ```readDirectory```
- ```readDirSync```-> ```readDirectorySync```

---
Not sure about these:
- ```chdir```-> ```changeDirectory``` (alternative ```changeCurrentDirectory``` as in rust)
- ```chmod```-> ```changeMode``` (alternative: ```setPermissions``` as in rust)
- ```chmodSync```-> ```changeModeSync``` (alternative: ```setPermissionsSync```)
- ```chown``` -> ```changeOwner```
- ```chownSync``` -> ```changeOwnerSync```

Or maybe Deno should have a separate ```POSIX``` module for these methods altogether like rust has [unistd](https://docs.rs/nix/0.9.0/nix/unistd/index.html)?
What are your thoughts on this?

**Comment by ry** [comment]
You seem to be discussing names in the Deno namespace. These are stable and cannot be renamed.

**Comment by timreichen** [comment]
Thank you for your fast response. I get that this would be a breaking change. Maybe something to keep in mind for the next major release? I just cannot get over the fact that the Deno namespace schema in kinda inconsistent.
On another note: Does Deno have some sort of a  ```deprecated``` warning/log/feature built-in?

**Comment by ry** [comment]
I don't think these will ever change and it's not inconsistent. We use the posix names where appropriate. No one wants to write `changeMode` - it's unintelligible - `chmod` is much clearer. There's no posix function for `watchFs` - so we looked at all of the various programming platforms and decided on a name that was most common.
