### ISSUE TITLE
ReferenceError doesn't pretty print/hold any metadata from eval

### ISSUE THREAD

**Issue by hayd** [denoland/deno#684]
```
try {
  eval("xxx");
} catch(err) {
  console.log(err);
}
```

Deno:
```
ReferenceError {}
```

Chrome:
```
ReferenceError: xxx is not defined
    at eval (eval at <anonymous> (newtab?ie=UTF-8:2), <anonymous>:1:1)
    at <anonymous>:2:3
```

Firefox:
```
ReferenceError: "xxx is not defined"
<anonymous>debugger eval code line 2 > eval:1:1<anonymous>debugger eval code:2:3 debugger eval code:4:3 
```

**Comment by kitsonk** [comment]
I suspect this is a limitation of `console.ts` at the moment.  For objects that are `instanceof Error` we need to look for their stack and log them out better.  It isn't limited to `eval()` or `ReferenceError`...  For example:

```ts
try {
  throw new Error("foo bar");
} catch (e) {
  console.log(e);
}
```

Produces:

```
Error {}
```

**Comment by kevinkassimo** [comment]
@kitsonk Yeah currently `console.ts` is not able to handle that. #676 is trying to port Node's `inspect` to Deno and should be able to resolve this issue.
