### ISSUE TITLE
Add commit style to contributing docs

### ISSUE THREAD

**Issue by caspervonb** [denoland/deno#6843]
When I first came here It wasn't immediately obvious to me that we are aiming for conventional commits, had a chat with @ry after like 10 commits before I figured that one out 😁

While it won't lead to a perfect commit log by itself, I think it could be useful to new contributors if we had a section on the commit style we are striving for in the style guide.

**Comment by nayeemrmn** [comment]
This corresponds to PR titles, right? It hasn't been a big deal because the maintainer can override it when squashing. Going through the commit log it seems the only rule we've kept to is imperative mood. Are you proposing to make them stronger?

**Comment by caspervonb** [comment]
> This corresponds to PR titles, right? 

This would be nice side effect for searching, altho labels can serve the same purpose.

> It hasn't been a big deal because the maintainer can override it when squashing. Going through the commit log it seems the only rule we've kept to is imperative mood. Are you proposing to make them stronger?

Yeah we're seem to be fairly loose about it. Really just depends on who's committing and who authored the commit. Sometimes it looks like conventional commits sometimes imperative non scoped, sometimes scoped, sometimes uppercase "Fix thing", sometimes lowercase "fix thing", etc.

My understanding from chatting with ry a while back was that conventional commits is the preferred style, we just don't really enforce it which is understandable given that it's not reviewable on GitHub and we have a bunch of commits are landing on release days.

**Comment by nayeemrmn** [comment]
> > This corresponds to PR titles, right?
> 
> This would be nice side effect for searching, altho labels can serve the same purpose.

No I mean the PR title is what becomes the commit message by default, so that's where contributors need to worry about.

**Comment by caspervonb** [comment]
> No I mean the PR title is what becomes the commit message by default

Ah on squash you mean, then in that case yes.

I was thinking of this in terms of rebasing, but as the pull request title and message is taken from the first commit message when opening a pull-request I think this still applies.

Always squash is also probably worth mentioning.

> We prefer this commit style
> ...
> Pull requests are **always squashed** so please maintain the aforementioned style for the title and body of pull requests.

**Comment by ry** [comment]
Ideally we would have a lint-like service that could check the commit message before it lands in master. Ideally we could review commit messages. Unfortunately it seems like the github workflow doesn't operate like that.

**Comment by caspervonb** [comment]
> Ideally we would have a lint-like service that could check the commit message before it lands in master. Ideally we could review commit messages. Unfortunately it seems like the github workflow doesn't operate like that.

Indeed, GitHub's not including the commit message in the merge request is an annoying limitation. Gerrit and friends do this part much better.

But regardless of the short comings of the tooling, as a first step documenting the preferred style with some examples of 'good' and bad couldn't hurt?

**Comment by ry** [comment]
> But regardless of the short comings of the tooling, as a first step documenting the preferred style with some examples of 'good' and 'bad' couldn't hurt.

agreed.

**Comment by caspervonb** [comment]
We at-least have something as of #7820, closing.
