### ISSUE TITLE
std/fs/mod.ts is broken

### ISSUE THREAD

**Issue by gera2ld** [denoland/deno#6849]
```
error: Import 'https://deno.land/std/fs/write_file_str.ts' failed: 404 Not Found
Imported from "https://deno.land/std/fs/mod.ts:12"
```

Caused by #6848

**Comment by nayeemrmn** [comment]
@caspervonb You forgot to to delete the imports to the removed modules in `std/fs/mod.ts`.

We should have a `std/fs/test.ts` which contains
```ts
import "./mod.ts";
```

**Comment by caspervonb** [comment]
> @caspervonb You forgot to to delete the imports to the removed modules in std/fs/mod.ts.

Ops, yeah should be make sure we're importing mod.ts in test.ts for every std module that has one.
