### ISSUE TITLE
Is there native solution or any working `prompt` module for Deno v1.2.0?

### ISSUE THREAD

**Issue by Jax-p** [denoland/deno#6856]
I'm trying to find any module or native solution for **prompts/ask** in CLI for Deno v1.2.0 but after last Deno upgrade no one of them works. Does anybody know some walkaround or I have to downgrade back to 1.1.0?

I know it's probably problem of third party modules but I am sure that I am not the only one who uses CLI prompts.
I would be happy for any help.

Is there any dependency list for https://deno.land/x? Like "list modules which passed tests with Deno v1.2.0".

```
deno 1.2.0
v8 8.5.216
typescript 3.9.2
Ubuntu 20.04
```

----

https://deno.land/x/ask
Both run & reload throws:
```
TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname
                 ~~~
    at https://deno.land/std@0.51.0/path/win32.ts:911:18

TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname;
                 ~~~
    at https://deno.land/std@0.51.0/path/posix.ts:433:18
```

----

https://deno.land/x/prompt
Both run & reload throws:
```
Cannot find name 'PromptError'.
                    throw new PromptError("input must be [male] or [female]");
```

**Comment by caspervonb** [comment]
Made this as an example a bit while back; https://deno.land/x/prompts

**Comment by lucacasonato** [comment]
Questions like these should be asked on Discord: https://discord.gg/deno. The issue tracker is for bugs and feature requests, not questions.
