### ISSUE TITLE
Deno does not find /usr/bin/bluetoothctl

### ISSUE THREAD

**Issue by antoniohps** [denoland/deno#6861]
O.S.: Ubuntu 20.04
Deno version: v1.1.2 fom latest/stable snapstore channel

The following code:

    Deno.run({
        cmd: ["/usr/bin/bluetoothctl"]
    });
throws:
    "error: Uncaught NotFound: No such file or directory (os error 2)"

The same code works for some other executables (e.g. /bin/echo), but does not for others. 

Just to be sure that the executable exists, the result of
    which bluetoothctl
is
    /usr/bin/bluetoothctl

**Comment by taraka** [comment]
Could you post the output of running the application with strace? 

`strace deno run <script>`

**Comment by lucacasonato** [comment]
This seems to be caused by you using snap. The deno snap uses `strict` confinement, so I think it can not access anything outside of its sandbox. Can you try with Deno installed using curl?

```
curl -fsSL https://deno.land/x/install/install.sh | sh
```

**Comment by lucacasonato** [comment]
Nothing actionable here. Please ask questions on https://discord.gg/deno.
