### ISSUE TITLE
Efficiency/speed proposal: just strip types

### ISSUE THREAD

**Issue by sdegutis** [denoland/deno#6870]
Just read the 1.0 blog post, and saw the TSC performance section, which mentions to chime in (somewhere) with ideas. This idea is something I also suggested to the QuickJS team last year:

Most devs just let their IDE run its own internal TypeScript compiler for continuous type-checking and showing errors inline in the IDE. So, why not just strip types (and transform TS enums) from within the deno runtime, basically ignoring the actual semantics of TypeScript entirely?

**Comment by kevinkassimo** [comment]
See https://deno.land/manual/getting_started/typescript#--no-check-option

**Comment by kitsonk** [comment]
As stated this is already implemented, and we have plans for improving it.

Also see #5432 which is effectively the master issue for all this work.
