### ISSUE TITLE
feat: Importmap resolution

### ISSUE THREAD

**Issue by timreichen** [denoland/deno#6871]
Is it possible to resolve a path in Deno with an importmap? Does some kind of ```resolveWithImportMap``` function in ```Deno``` or ```std``` exist?

example:
```ts
const importmap = {"imports": { "foo/": "https://path/to/somewhere/" } }
resolvePathWithImportMap("foo/bar", importmap) // output: "https://path/to/somewhere/bar"
```

**Comment by bartlomieju** [comment]
No there is no such API. What is the use case for it?

**Comment by timreichen** [comment]
Im experimenting with a pure deno webbundler that compiles a typescript module with .ts suffix Imports (ts cannot resolve that natively) to a js file and all the dependecies alike (not a single bundle file like Deno.bundle does).

Since deno modules can use importmaps there is no way at the moment to resolve these import paths properly.
So I think the usecase is to help and simplify the creation of deno native build/dev tools.

**Comment by nayeemrmn** [comment]
It's still too esoteric to include in CLI or `std`, especially for a spec so far from being standardised.

**Comment by timreichen** [comment]
I get that, though deno supports importmaps. Maybe it would be good to at least publish the algorythm how deno resolved the paths internally?

**Comment by bartlomieju** [comment]
@timreichen Deno uses this algorithm to resolve module specifiers: https://html.spec.whatwg.org/multipage/webappapis.html#resolve-a-module-specifier

If import map is loaded Deno first tries to resolve module specifiers according to this algorithm: https://wicg.github.io/import-maps/#resolving

**Comment by timreichen** [comment]
@bartlomieju Thank you!
I created an [importmap module](https://deno.land/x/importmap) that offers the functionality.
Closing this issue for now. Can be reopened when importmap specs are stable and functionality should become part of ```std```.
