### ISSUE TITLE
Using @deno-types breaks Deno.bundle() imports

### ISSUE THREAD

**Issue by randallb** [denoland/deno#6875]
Hi all--

Inline with #4539 and #5665, I've discovered when you declare deno-types in an import directive, it causes the `Deno.bundle()` command to ignore the imports.

Gist example: https://gist.github.com/randallb/745dd7cdd638f0e1018e3875641b542c

If I omit the deno-types declaration, it seems to bundle correctly. Might be a dupe of those other issues or might be unrelated, but I figure all three of these usecases would probably be useful to fix at once.

**Comment by kitsonk** [comment]
Duplicate of #6338
