### ISSUE TITLE
[std/testing/asserts] Rename *Contains to *Includes

### ISSUE THREAD

**Issue by jsejcksn** [denoland/deno#6888]
I think sticking with the existing naming conventions used by the JavaScript ecosystem (when practical) can help reduce potential confusion (or at minimum reduce cognitive load), so I propose renaming these functions:

- [`assertArrayContains`](https://doc.deno.land/https/deno.land/std/testing/asserts.ts#assertArrayContains) ➡️ `assertArrayIncludes`
- [`assertStringContains`](https://doc.deno.land/https/deno.land/std/testing/asserts.ts#assertStringContains) ➡️ `assertStringIncludes`

Ref: [`Array.prototype.includes()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes), [`String.prototype.includes()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes)

If there is agreement, I'd like to work on this PR.

**Comment by jacobgc** [comment]
I think your propsal is a good idea, might be best leaving in contains for a few versions with a deprication notice however!

**Comment by zekth** [comment]
`Contains` was firstly introduced in inspiration of Jest `expect` functions : https://jestjs.io/docs/en/expect.html

**Comment by kevinkassimo** [comment]
Aliasing might work? I remember when people originally introduces `Array.prototype.includes()` it is due to `.contains()` collision with some existing popular libraries (`.contains()` preferred over `.includes()`, but forced to go the other direction. We don't have this problem here)

**Comment by caspervonb** [comment]
If we're just testing for `a.includes(b)` then `assertIncludes` would be preferable IMHO.

**Comment by jsejcksn** [comment]
@caspervonb There are two functions listed, one for strings and one for arrays whose members can contain non-string types as well. Do you mean that you want a single, overloaded function instead of one for each data type? Will you clarify?

**Comment by timreichen** [comment]
@jsejcksn In favor of renaming.
@kevinkassimo Not in favor of aliasing. Since std is versioned, we can do breaking changes and have so in the past.
@caspervonb In favor of  your idea: `assertIncludes` that handles both string and array.

**Comment by caspervonb** [comment]
> @caspervonb There are two functions listed, one for strings and one for arrays whose members can contain non-string types as well. Do you mean that you want a single, overloaded function instead of one for each data type? Will you clarify?

If the intent is to check for `target.includes(source)`, yes a single function.

And It's fine to break std; within reason.

**Comment by bartlomieju** [comment]
Closed in #7951
