### ISSUE TITLE
How to uninstall when built from source?

### ISSUE THREAD

**Issue by nougator** [denoland/deno#6899]
Hello, I want to know to uninstall Deno when we downloaded and build it from source (with `cargo install deno
`).

**Comment by lucacasonato** [comment]
`cargo uninstall deno`

**Comment by nougator** [comment]
It says `error: package ID specification 'deno' matched no packages`

**Comment by Yamboy1** [comment]
Considering it's just an executable once it's compiled, you could try to see where the executable is and delete that. Something like `whereis deno` or `which deno`

**Comment by nougator** [comment]
It worked, thanks a lot!
