### ISSUE TITLE
Using Deno bundle programmatically requires the --unstable flag

### ISSUE THREAD

**Issue by shardyMBAI** [denoland/deno#6923]
`$ deno bundle mod.ts` does not require the `--unstable` flag, however, if I use `$ deno run --allow-read my_script.ts` where my_script.ts` contains 

```ts
const [, source] = await Deno.bundle("./mod.ts");
console.log(source);
```

I need the `--unstable` flag.

**Comment by lucacasonato** [comment]
This is correct, programmatic access to the TS compiler APIs is still unstable. We have not finalized the APIs yet.

**Comment by shardyMBAI** [comment]
Thank you.

**Comment by kitsonk** [comment]
In fact we will be breaking those APIs: #4752
