### ISSUE TITLE
bundle output contains top-level await.

### ISSUE THREAD

**Issue by zhengxiaoyao0716** [denoland/deno#6924]
I'm not sure is it a problem, but according to [the manual](https://deno.land/manual/tools/bundler), it said that "bundles can also be loaded in the web browser".

However, if module used top-level await, then the output bundles would contains this syntax too, and could not be loaded in the web browser directly.

For example, try to bundle the `std/log` module:
> deno bundle "https://deno.land/std/log/mod.ts"

Then the output would looks like:
``` javascript
// ...
const __exp = await __instantiate("log/mod", true);
export const getLogger = __exp["getLogger"];
export const debug = __exp["debug"];
// ...
```

**Comment by trivikr** [comment]
Verified that deno bundle for std/log does output top level await

Command run:
```console
deno bundle https://deno.land/std@0.62.0/log/mod.ts
```

Deno version:
```console
$ deno --version
deno 1.2.0
v8 8.5.216
typescript 3.9.2
```

**Comment by kitsonk** [comment]
It should read "some bundles can also be loaded in the web browser".  There are all sorts of things that can make bundles incompatible with browsers.

Top level await is already in V8 and [being implemented in Chromium](https://chromestatus.com/feature/5767881411264512), so it will eventually end up in Chrome and Edge.

**Comment by bartlomieju** [comment]
Not a bug, `deno bundle` produces bundles that are supposed to be consumed by Deno. As pointed by @kitsonk some of them will work in the browser.

**Comment by quaos** [comment]
Ah, it's a shame as I'm trying to use Deno as build system for React apps, bundling to browser JS.

But because of this issue, when some dependencies use top-level await the whole thing does not work anymore.
