### ISSUE TITLE
`deno test` fails to load `Deno` when a tsconfig.json file is present

### ISSUE THREAD

**Issue by matsko** [denoland/deno#6926]
When running tests using `deno test` the `Deno` object is loaded globally, however, the `Deno` object disappears when a tsconfig.json file is passed into the command (e.g. `deno test -c ./tsconfig.json my_test.ts`).

**Comment by matsko** [comment]
I got around this error for the time being by loading `deno.ns` into the `lib: []` array within the connected `tsconfig.json` file.

**Comment by kitsonk** [comment]
If you supply a `lib` attribute in your compiler options, it will always override the defaults, and you need to include `deno.ns`.  What happens when you omit a `lib` attribute in your `tsconfig.json`?

**Comment by bartlomieju** [comment]
Kitson provided exhaustive answer above.
