### ISSUE TITLE
Deno.exe failed

### ISSUE THREAD

**Issue by anivaisu** [denoland/deno#6927]
Hi,
 in my system configuration windows 7,32 bit.

 I have installed deno on my machine using this command

`iwr https://deno.land/x/install/install.ps1 -useb | iex`

My pwershell version is 5.1

I got this error.

`Program 'deno.exe' failed to run: The specified executable is not a valid application for this OS platform.At line:1`

How can i fix this pblm.Please advice me,

Thanks & regards,

Anitha.G

**Comment by lucacasonato** [comment]
Deno does not ship 32 bit binaries (only 64 bit). Duplicate of #3438.

**Comment by bartlomieju** [comment]
Closing in favor of #3438
