### ISSUE TITLE
Suggestion: Better error description

### ISSUE THREAD

**Issue by timreichen** [denoland/deno#6933]
```Deno.readTextFile``` error is not too descriptive my opinion:

```sh
error: Uncaught NotFound: No such file or directory (os error 2)
...
```
Maybe it could include a bit more information, like the path it was trying to read?
```sh
error: Uncaught NotFound: No such file or directory (os error 2): "path/to/file.ts"
```

**Comment by caspervonb** [comment]
See also https://github.com/denoland/deno/issues/6440

**Comment by bartlomieju** [comment]
We now use `anyhow` crate for error handling (https://github.com/denoland/deno/pull/7476), which means we can use `.context()` method to attach additional info to errors. PRs that update call sites with better descriptions are welcome!
