### ISSUE TITLE
Deno info should not type check

### ISSUE THREAD

**Issue by ry** [denoland/deno#6935]

**Comment by kitsonk** [comment]
Just for context, there is a small amount of dependencies that not type checking would not catch currently, that would be caught under type checking.

For example:

```ts
const a = "./a.ts";
const a_mod = await import(a);
```

Would be caught under type checking, as the TypeScript compiler realises that value being passed to the dynamic import is statically determinable at call point, and would then make `"./a.ts"` a dependency of the module.
