### ISSUE TITLE
Failed to get directory listing

### ISSUE THREAD

**Issue by fauzan121002** [denoland/deno#6936]
Got an error (403) while querying the GitHub API: {"message":"API rate limit exceeded for 180.253.11.147. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://developer.github.com/v3/#rate-limiting"}

it gots me this url https://deno.land/x/accepts

**Comment by nayeemrmn** [comment]
Duplicate of https://github.com/denoland/deno_website2/issues/433.

**Comment by lucacasonato** [comment]
Should be fixed in the coming week.

**Comment by fauzan121002** [comment]
> Should be fixed in the coming week.

Thanks!!
