### ISSUE TITLE
TS2345 [ERROR]: Importing serve from server.ts produces an error

### ISSUE THREAD

**Issue by mk0y** [denoland/deno#6938]
How to reproduce:

Import serve from server.ts:
```js
// play.js
import { serve } from "https://deno.land/std/http/server.ts";
console.log('play');
```

Run it:
```sh
deno run play.js
```

I'm getting error:
```sh
error: TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
Type 'URL' is not assignable to type 'string'.
return new URL(url).pathname
at https://deno.land/std/path/win32.ts:911:18
at https://deno.land/std/path/posix.ts:433:18
Found 2 errors.
```

However, I noticed that using `Deno.listen` works well. Is there a change in API regarding this?

Looking at `serve`'s implementation I can tell that API doesn't match:
```js
export function serve(addr: string | HTTPOptions): Server {
  if (typeof addr === "string") {
    addr = _parseAddrFromStr(addr);
  }

  const listener = Deno.listen(addr);
  return new Server(listener);
}
```

Because in https://deno.land/manual/examples/tcp_echo `Deno.listen` receives options:
```js
const listener = Deno.listen({ port: 8080 });
```

As seen in docs:
https://doc.deno.land/https/github.com/denoland/deno/releases/latest/download/lib.deno.d.ts#Deno.listen

```ts
function Deno.listen(options: ListenOptions & { transport: "tcp" }): Listener
```

Deno version: 1.2.2

**Comment by lucacasonato** [comment]
Please use a locked version of std: https://deno.land/std@0.63.0

**Comment by mk0y** [comment]
Great thanks. I was actually using locked version 0.50.0, so need to update it.

Then, general practice would be after `deno upgrade` to check newest versions of std dependencies in your code afterwards.
