### ISSUE TITLE
Deno.iter async HTTP request bug

### ISSUE THREAD

**Issue by trgwii** [denoland/deno#6945]
Am I doing something wrong here?

```ts
import { serve } from 'https://deno.land/std@0.63.0/http/server.ts';

const arr = [];
for (let i = 1; i < 10000; i++) {
	arr.push(i);
}
const str = arr.map(x => String(x)).join('\n');
const data = new TextEncoder().encode(str);
console.log('Writing file synchronously - length: ' + data.byteLength);
Deno.writeFileSync('file1.txt', data);

const server = serve({ port: 8080 });

(async () => {
	for await (const req of server) {
		let total = 0;
		const file = await Deno.open('file2.txt', { create: true, write: true });
		for await (const chunk of Deno.iter(req.body)) {
			total += await file.write(chunk);
			// Changing the above line to this makes it work:
			// total += file.writeSync(chunk);
		}
		console.log('Wrote file asynchronously - length: ' + total);
		req.respond({ body: String(total) });
	}
})();

fetch('http://127.0.0.1:8080/', { method: 'POST', body: data });
```

Usage:
```sh
deno run --allow-net --allow-write=. deno_http_bug.ts
```

Gives the following output for me:
```sh
Writing file synchronously - length: 48887
Wrote file asynchronously - length: 32503
```

But if I understand the APIs I'm using correctly they should be the same length?

Deno version:
```sh
deno 1.2.2
v8 8.5.216
typescript 3.9.2
```

This bug happens on both Windows 10 and Debian WSL (inside Windows 10).

Inspecting the files closely I see that something must be going wrong here:

![image](https://user-images.githubusercontent.com/11262022/89213431-5d5ef800-d5c5-11ea-8a07-9b5d9c890bb3.png)

**Comment by caspervonb** [comment]
See the documentation.

> **It is not guaranteed that the full buffer will be written in a single call.**


Basically the same semantics as write(2) applies.

> write() writes up to count bytes from the buffer pointed buf to the file referred to by the file descriptor fd.
The number of bytes written may be less than count if, for example, there is insufficient space on the underlying physical medium, or the RLIMIT_FSIZE resource limit is encountered (see setrlimit(2)), or the call was interrupted by a signal handler after having written less than count bytes. (See also pipe(7).)

**Comment by Naeemo** [comment]
FYI, writeAll looks like this:
```
  async function writeAll(w, arr) {
    let nwritten = 0;
    while (nwritten < arr.length) {
      nwritten += await w.write(arr.subarray(nwritten));
    }
  }
```

But I also find this in the Writer interface's documentation, does this matter?

>  `write()` must reject with a non-null error if would resolve to `n` < `p.byteLength`.
     
---
I'm new to deno, correct me if I'm wrong.

**Comment by trgwii** [comment]
replacing `file.write(chunk)` with `Deno.writeAll(file, chunk)` solves the issue, as does using the inner loop written by @Naeemo above (within the implementation of writeAll. Thanks everyone!
