### ISSUE TITLE
UDP not supported

### ISSUE THREAD

**Issue by minioin** [denoland/deno#6950]
Even though #3946 has been merged, udp does not work. For a minimal following example:
```
const listener = Deno.listen({port: 8888, transport: "udp"});
console.log(listener)
```
Following error is generated:
error: TS2322 [ERROR]: Type '"udp"' is not assignable to type '"tcp" | undefined'.

Version tested on: deno 1.2.2 on Fedora 32.

**Comment by minioin** [comment]
Even if I run with --unstable flag, I get following error.
```
error: TS2769 [ERROR]: No overload matches this call.
  Overload 1 of 2, '(options: UnixListenOptions & { transport: "unix"; }): Listener', gave the following error.
    Type '"udp"' is not assignable to type '"unix"'.
  Overload 2 of 2, '(options: ListenOptions & { transport?: "tcp" | undefined; }): Listener', gave the following error.
    Type '"udp"' is not assignable to type '"tcp" | undefined'.
const listener = Deno.listen({port: 8888, transport: "udp"});
```

**Comment by lucacasonato** [comment]
UDP was moved to Deno.listenDatagram. You need the --unstable flag for that.

**Comment by minioin** [comment]
Can confirm. Thanks. Can you point me towards the rationale behind this decision?

**Comment by ry** [comment]
We use a different method because it returns a different type (DatagramConn vs Conn). Although typescript can express these conditions in the types we prefer to simply have a different method.

**Comment by minioin** [comment]
I was curious about the technical reasons. Thanks.
