### ISSUE TITLE
Deno CLI - allow ts-ignore comments

### ISSUE THREAD

**Issue by Keimeno** [denoland/deno#6956]
### The problem
If we run `deno lint --unstable` on my package https://github.com/Keimeno/segno, we get a few `no-explicit-any` warnings, etc. However, we also receive an enormous amount of `ban-ts-comment` warnings. 
Quite frankly I use a `// @ts-ignore` comments above every import like such;
```ts
// @ts-ignore
import { isFQDN } from './isFQDN.ts';
```
because I am using typedoc to automatically generate documentation for my library. The problem with typedoc is, that has no option to detect if it's a deno library and since that is not the case we cannot import typescript modules by supplying the `.ts` file-type at the end of an import. See https://github.com/microsoft/TypeScript/issues/27481, there is an ongoing issue about allowing to specifically set the file-type.

Not this isn't too big of a deal, I don't use `deno lint` anyways currently, and it isn't significant to me, since I can use eslint or gts to lint my code. However, it was stated that in the future, it is planned to rank packages according to their performance https://deno.land/posts/registry2#future-plans with CLI tools. That means making `deno lint` allow ts-ignore is essential as long as https://github.com/microsoft/TypeScript/issues/27481 isn't resolved or typedoc specifically adds support for deno.

**Comment by kitsonk** [comment]
This should be moved to https://github.com/denoland/deno_lint/

**Comment by Keimeno** [comment]
Moved to https://github.com/denoland/deno_lint/issues/254
