### ISSUE TITLE
Main thread panic at Error throw

### ISSUE THREAD

**Issue by AndreJesusBrito** [denoland/deno#6965]
I'm experiencing a strange bug with `Deno`.

When a exception is thrown the main process panics. This is the trace:
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', cli\fmt_errors.rs:86:8
stack backtrace:
   0:     0x7ff7af88a45b - <unknown>
   1:     0x7ff7af53cecc - <unknown>
   2:     0x7ff7af889483 - <unknown>
   3:     0x7ff7af888bb8 - <unknown>
   4:     0x7ff7af887d2e - <unknown>
   5:     0x7ff7af88efe5 - <unknown>
   6:     0x7ff7af53a4b0 - <unknown>
   7:     0x7ff7af53a2cc - <unknown>
   8:     0x7ff7af36cbf2 - <unknown>
   9:     0x7ff7af48ada8 - <unknown>
  10:     0x7ff7af48b345 - <unknown>
  11:     0x7ff7af53cecc - <unknown>
  12:     0x7ff7af751885 - <unknown>
  13:     0x7ff7af349c1d - <unknown>
  14:     0x7ff7af4daf6f - <unknown>
  15:     0x7ff7af8aa3f6 - <unknown>
  16:     0x7ff7af4ea67e - <unknown>
  17:     0x7ff7b048bf10 - CrashForExceptionInNonABICompliantCodeRange
  18:     0x7ff8e9777bd4 - BaseThreadInitThunk
  19:     0x7ff8ea16ce51 - RtlUserThreadStart
```

I don't know how to reproduce the bug but it happened in my project so I tried to isolate it in a separated branch:
https://github.com/AndreJesusBrito/WebAssembly-Language-Compiler/tree/rust-exception-bug-isolation

The bug happens in file `src/SyntaxAnalysis/SyntaxRule.ts` at line 25 when I throw an exception.
```ts
...
public getDerivation(terminal: string): RuleDerivation {
  const derivation = this.derivations.get(terminal);
  if (derivation) {
    return {
      derivationSymbols: [...derivation.derivationSymbols].reverse(),
      actions: derivation.actions,
    };
  } else {
    throw SyntaxError("Unexpected token '" + terminal + "' at rule " + this._name);            // THIS IS LINE 25
  }
}

public setDerivation(rule: SyntaxSymbol[], actions: ActionObj[], ...terminals: string[]): void {
  for (const terminal of terminals) {
    if (this.derivations.get(terminal) instanceof Array) {
      console.warn("'" + terminal + "' repeated terminal for rule " + this._name);
...
```

Even though I'm using a SyntaxError (that is not a very good idea and will change later) it seems to happen for any error including the base Error class.

The most strange thing to me is that by changing the white space on this file it can work correctly.
For example, when I remove line 28 it works fine:
```
error: Uncaught SyntaxError: Unexpected token '' at rule none
  public setDerivation(rule: SyntaxSymbol[], actions: ActionObj[], ...terminals: string[]): void {
            ^
    at SyntaxRule.getDerivation (file:///C:/Users/Andr%C3%A9%20Brito/Documents/GitHub/WebAssembly-Language-Compiler/src/SyntaxAnalysis/SyntaxRule.ts:28:13)
    at file:///C:/Users/Andr%C3%A9%20Brito/Documents/GitHub/WebAssembly-Language-Compiler/src/main.ts:4:1
```

I'm running using the command:
```
deno run src\main.ts
```

and my specs are:
```
deno 1.2.2
v8 8.5.216
typescript 3.9.2
OS: Windows_NT x64 10.0.18362
```

Hope this helps! :)

**Comment by bartlomieju** [comment]
CC @nayeemrmn probably related to formatting of errors

**Comment by nayeemrmn** [comment]
Looks like the row number we get from the source mapper is mistakenly 28 instead of 25. Line 28 is obviously shorter than what the formatting code expects it to be given the `start_column` it received. So it's a source mapping bug as we've seen here and there recently. I guess we can make the formatting code a bit more safe so it doesn't panic at least.

**Comment by JayHelton** [comment]
is this open for work or does it need more discussion? @nayeemrmn

**Comment by ry** [comment]
@AndreJesusBrito Thanks for the bug report. It would be great to have a small standalone example that demonstrated the bug so that we can try it locally - as it stands we can't actually repeat the failure.

**Comment by AndreJesusBrito** [comment]
ok, I have been playing with the file and got it isolated.

However, apparently seems that the path to file also dictates if the main thread panics or not.
My file is called `SyntaxRule.ts` and is in the directory: `C:\Users\André Brito\Documents\GitHub\WebAssembly-Language-Compiler\src\SyntaxAnalysis`.
If I change the filename to `Ab.ts` its doesn't panic. If I change the folder name from `SyntaxAnalysis` to `ABC` it doesn't panic.
I moved the `src` folder to my desktop an it doesn't panic as well.

I don't know if this is due to cache but I'm using `-r` flag and the file doesn't have any dependencies, but I could be missing something.

Probably this will not reproduce the bug but I will leave here what I have [src.zip](https://github.com/denoland/deno/files/5064330/src.zip)

**Comment by bartlomieju** [comment]
> Looks like the row number we get from the source mapper is mistakenly 28 instead of 25. Line 28 is obviously shorter than what the formatting code expects it to be given the `start_column` it received. So it's a source mapping bug as we've seen here and there recently. I guess we can make the formatting code a bit more safe so it doesn't panic at least.

@nayeemrmn I have a feeling this is related to `col` vs `col_display` in case of multi-byte characters (like `é`). Unfortunately I don't have a solution at hand.

**Comment by 00ff0000red** [comment]
@bartlomieju I just closed my duplicate report over at https://github.com/denoland/deno/issues/9077, my reproduction only used ASCII characters that would fit into a signed byte (i.e. no multi-bytes), if it helps at all.

**Comment by lucacasonato** [comment]
Can you retry on the latest canary? `deno upgrade --canary`

This might have been fixed

**Comment by nayeemrmn** [comment]
(Ref https://github.com/denoland/deno/issues/9392#issue-800713883) @MierenManz If you have a consistent repro for the panic, it would be a massive help if you could post a self-contained one here.

**Comment by MierenManz** [comment]
First thing I'll do in the morning

**Comment by nayeemrmn** [comment]
Nevermind, I found the issue. The source map loader gives precedence to external `.js.map` files in the cache over inlined ones, even though the former aren't meant to be used by default anymore and aren't kept up to date.

**Comment by nayeemrmn** [comment]
I've found another source map bug that also causes this panic, related to #6542. Fix coming.
