### ISSUE TITLE
Deno manuals have only introduction link at the end of every page.

### ISSUE THREAD

**Issue by maitysubhasis** [denoland/deno#6968]
<img width="1920" alt="Screenshot 2020-08-06 at 11 39 22 AM" src="https://user-images.githubusercontent.com/16653067/89497299-ad160d00-d7d9-11ea-9eb8-ad5c0b8d59e8.png">

I suppose there should be a **next** link

**Comment by lucacasonato** [comment]
Duplicates of https://github.com/denoland/deno_website2/issues/1425
