### ISSUE TITLE
Feature Request: A file for project config

### ISSUE THREAD

**Issue by ShardulNalegave** [denoland/deno#6969]
I know that one of the main features of deno is that it doesn't need any package manager and instead can use code from the web. But I think that might be a problem in some cases, for example, if I want to change the version of a dependency I have used I then need to change the url from all my files. Instead I think the following approach can be useful.

### Instead of:-
````typescript
import { serve } from "https://deno.land/std@0.63.0/http/server.ts";
const s = serve({ port: 8000 });
console.log("http://localhost:8000/");
for await (const req of s) {
  req.respond({ body: "Hello World\n" });
}
````

### We can do the following:-

- In `/config.toml`
````toml
[dependencies]
server = "https://deno.land/std@0.63.0/http/server.ts"
````

- In `server.ts`
````typescript
import { serve } from "server";
const s = serve({ port: 8000 });
console.log("http://localhost:8000/");
for await (const req of s) {
  req.respond({ body: "Hello World\n" });
}
````

So suppose now I want to downgrade `server` to version `0.60.0` then I can change it in the config file and no more changes will be required.

I am new to deno so I might be wrong but I thought that this would be a good feature to have so shared it. 😄

**Comment by axetroy** [comment]
There is already a standard. use `--importmap`
```bash
$ deno run --help | grep importmap
        --importmap <FILE> 
```

**Comment by ShardulNalegave** [comment]
Ok! I didn't know that. Thanks. 😄
