### ISSUE TITLE
Nightly Builds

### ISSUE THREAD

**Issue by crowlKats** [denoland/deno#6974]
Would it be possible to have nightly builds?
Currently there is https://github.com/maximousblk/deno_nightly, but having an official source would be great.
It could fit in well with deno upgrade: `deno upgrade --nightly`. The `version` flag could be passed to be the date of the nightly build (else the latest is grabbed, just like with normal releases), and since the `output` flag exists, one could have stable & nightly separate.

cc @maximousblk

**Comment by maximousblk** [comment]
Yes this would be very helpful if it was official.

This should (imo) look something like this:

install:
```sh
# default
deno upgrade --nightly

# specific build
deno upgrade --nightly YYYY.MM.DD
```

Release notes:
- include direct link to a git diff between the last commit of the previous build and the latest commit of the current build
- include a link to the stable (as per the build) runtime API docs
- include a link to the unstable runtime API docs

a release for reference: https://github.com/maximousblk/deno_nightly/releases/tag/2020.08.06

**Comment by crowlKats** [comment]
For specific build, i think we should rather use the `version` flag than an optional value for the `nightly` flag

**Comment by bartlomieju** [comment]
Core team has discussed this issue and we decided that providing nightly builds would be pretty useful. We should start by setting up CI to release those builds every night, after that we can think about integrating it into `deno upgrade`. We might have to address https://github.com/denoland/deno/issues/6037 first. 

@maximousblk would you be interested in integrating your solution to main repo?

**Comment by maximousblk** [comment]
imo setting it up on the main repository won't be a good idea as it would flood the releases page with the nightly builds. (not to mention all the notifications)

I'd suggest we could transfer [my repository](https://github.com/maximousblk/deno_nightly) to the deno org and do it there? this way the older builds are also preserved.

Other than that, we need a way to automatically determine the version (semver) based on the pull request titles. What I currently do is inject the build date in the [version.rs](https://github.com/denoland/deno/blob/master/cli/version.rs) ([how?](https://github.com/maximousblk/deno_nightly/blob/master/.github/inject.ts)) file using a deno script. I don't know enough about Rust so I couldn't work out any other way of doing it. so we need an easy way to set the cli version without modifying the source.

Release notes seem to be good enough as is

regarding #6037, I think we should do it similar to how Rust does it. so it would be

compact: `${next-version}-nightly`
```sh
λ deno -V
deno 1.5.0-nightly
```

full: `${next-version}-nightly (${commit} ${date})`
```sh
λ deno --version
deno 1.5.0-nightly (ece1e1d 2020-10-26)
v8 8.7.220.3
typescript 4.0.3
```
and remove `-nightly` for stable versions.

**Comment by bartlomieju** [comment]
@maximousblk thanks for detailed description. #6037 has been resolved in #8133 and the output is as follows:
```
$ ./target/debug/deno --version
deno 1.5.0 (UNKNOWN, debug, x86_64-apple-darwin)
v8 8.7.220.3
typescript 4.0.3
```

Before setting up the builds we still need to figure out how they would work with `deno upgrade` (because URL to releases page is hardcoded there). I think sensible solution would be to add `--nightly` flag to `deno upgrade`.

**Comment by crowlKats** [comment]
sounds reasonable to me. How would the nightly flag behave tho? as i described it or as @maximousblk did?

**Comment by bartlomieju** [comment]
@crowlKats I think format proposed by @maximousblk is very reasonable and easy to grep:
```
# default
deno upgrade --nightly

# specific build
deno upgrade --nightly YYYY.MM.DD
```

**Comment by crowlKats** [comment]
hmm what would happen if one passes both version and nightly flag tho?
that is one reason why i was considering rather to have:
```
# default
deno upgrade --nightly

# specific build
deno upgrade --nightly --version YYYY.MM.DD
```
over maximous' one, and imo feels more intuitive

**Comment by bartlomieju** [comment]
@crowlKats they could be mutually exclusive. Let's get some more feedback before deciding on the flag, and also it should be behind `--unstable` anyway.

**Comment by ThatsNoMoon** [comment]
I think it would be most seamless if it was integrated into the existing `--version` flag.
```
# latest nightly
deno upgrade --version nightly

# specific nightly
deno upgrade --version nightly-YYYY-MM-DD
```

**Comment by pedropaulosuzuki** [comment]
> I think it would be most seamless if it was integrated into the existing `--version` flag.
> 
> ```
> # latest nightly
> deno upgrade --version nightly
> 
> # specific nightly
> deno upgrade --version nightly-YYYY-MM-DD
> ```

Maybe using something in the lines of:

```shell
deno upgrade -v nightly
```
And when we see a YYYY.MM.DD, we just recognise it with pattern matching as a nightly build?
```shell
deno upgrade -v YYYY.MM.DD
```

**Comment by ThatsNoMoon** [comment]
> And when we see a YYYY.MM.DD, we just recognise it with pattern matching as a nightly build?

I think this is an option but not one I would personally pick. It's not as obvious to someone not familiar with deno's versioning that it's not a normal, stable, version.

**Comment by pedropaulosuzuki** [comment]
> > And when we see a YYYY.MM.DD, we just recognise it with pattern matching as a nightly build?
> 
> I think this is an option but not one I would personally pick. It's not as obvious to someone not familiar with deno's versioning that it's not a normal, stable, version.
> 
> This could be relevant if anyone ever publishes something suggesting running such a command that installs a nightly build.

True, and gets into that problem Ryan said on his first Deno speak of "doing things for the sake of being cute and not explicit". My mistake.

**Comment by maximousblk** [comment]
@bartlomieju I think this can be closed in favor of the canary builds?
