### ISSUE TITLE
[DISCUSSION] cache to read from a deno_modules concept

### ISSUE THREAD

**Issue by narwy** [denoland/deno#6982]
Hey, so there's a certain industry standard to sectors like healthcare, insurance, finance etc where certain laws restrict you pulling in resources from external sources. An example is pulling a module from /x. The requirements are that applications need to go pre built like with node_modules for example vs running npm install on a server or in deployment stage (nodejs example).

Proposal:
- `deno cache --mounted` will create a folder called `deno_modules` caching the modules into that folder within your app;
- `deno run --mounted-cache main.ts` will read from the `deno_modules` folder vs the main cache (docker envs etc so you can mount)
- The ability to commit `deno_modules` also (don't frown on this, as certain types of industry require this method I'm afraid :( )

I've not seen this topic discussed before but it's basically certain industry's and security policies due to the type of data they process etc something that needs to be considered.

**Comment by Soremwar** [comment]
There is already a way to do this. You can set DENO_DIR to a folder in your project, run `deno cache` and push that folder to your GitHub repo.

The when you run your app you just do

`DENO_DIR=cache_folder deno run your_app.js|

**Comment by nayeemrmn** [comment]
We have `deno bundle`, but what you're suggesting is also modelled almost to a tee: https://deno.land/manual/linking_to_external_code#but-what-if-the-host-of-the-url-goes-down-the-source-wont-be-available

**Comment by narwy** [comment]
> We have `deno bundle`, but what you're suggesting is also already modelled almost to a tee: https://deno.land/manual/linking_to_external_code#but-what-if-the-host-of-the-url-goes-down-the-source-wont-be-available

That's exactly what i'm looking for! cheers @Soremwar and @nayeemrmn 

However if I run it unversioned (/x/foobar vs /x/foobar@v1.x.x) will that still pull the latest version and override my cache folder based off the hashing?

**Comment by nayeemrmn** [comment]
> However if I run it unversioned (/x/foobar vs /x/foobar@v1.x.x) will that still pull the latest version and override my cache folder based off the hashing?

You'll have to run with `--reload` and then re-commit the difference every now and then. This also applies to your suggestion.

**Comment by narwy** [comment]
So if it runs using DENO_DIR and we use a /x/foobar module, will it still do a call to that via http to get the hash or just instantly load from the dir without doing any outbound call to that module?

**Comment by Soremwar** [comment]
Deno will always check if a module is already cached before trying to download it. So in the case you configure correctly DENO_DIR it won't attempt to download

**Comment by nayeemrmn** [comment]
> So if it runs using DENO_DIR and we use a /x/foobar module, will it still do a call to that via http to get the hash or just instantly load from the dir without doing any outbound call to that module?

@narwy The latter, yes. The three commands in the manual's example exactly satisfy your three bullet points:
```
# "deno cache --mounted deps.ts" ->
DENO_DIR=./deno_dir deno cache deps.ts

# "deno run --mounted-cache main.ts" ->
DENO_DIR=./deno_dir deno run main.ts

# Commit deno_modules ->
git add -u deno_dir
git commit
```

**Comment by narwy** [comment]
Is there anyway to disable pulling if a module doesn't exist in the cache. Bit like a either find the module cached or fail the app and refuse to pull it ? I know this sounds stupid but it's certain industry policies we have to follow.

**Comment by nayeemrmn** [comment]
> Is there anyway to disable pulling if a module doesn't exist in the cache. Bit like a either find the module cached or fail the app and refuse to pull it ? I know this sounds stupid but it's certain industry policies we have to follow.

`deno run --cached-only`, not stupid at all :)

**Comment by narwy** [comment]
Someone thought of everything it seems. Thanks for all of this 🤟
