### ISSUE TITLE
 add mod.ts file in standard libraries

### ISSUE THREAD

**Issue by buttercubz** [denoland/deno#6983]
Is it possible to add a `mod.ts` file in standard libraries that don't have it?

since some packages like `_util` or `fmt` don't have a `mod.ts` file

**Comment by nayeemrmn** [comment]
The ones that don't have it are intended not to, unless you have a case to make for some specific directory. If the exports in that directory aren't likely to all be used together, it won't have a `mod.ts`. `_util` is private by the way. Nobody should be importing from there.

**Comment by buttercubz** [comment]
@nayeemrmn I understand, and in the case of the libs like `fmt` and `testing` is it possible?

**Comment by Soremwar** [comment]
In the case of testing, the files in there are intended to each be a module in their own, so there is no real need to reexports them in the same file

Is there a specific reason you want those to be that way?

**Comment by buttercubz** [comment]
> In the case of testing, the files in there are intended to each be a module in their own, so there is no real need to reexports them in the same file

i got it, thanks
