### ISSUE TITLE
deno exiting silently

### ISSUE THREAD

**Issue by martunta** [denoland/deno#6989]
I have this odd issue. I have been working on this application for more than a month now, but today deno suddenly started crashing after I add a new import statement. Looks like I can add this import statement in any file, and deno gives up couple of seconds after starting.

import statement can also point to an existing file, already used in another place. Or it can point to a new file with an empty function. 

I am not sure how to go about it, as there is no error message thrown, and -L debug is also not showing anything interesting. also, cache --reload didn't help. 

version is 1.2.2, but I tried and with 1.2.1 it is the same. the application seems to be working perfectly, it would somehow seem that it has reached some sort of limit on imports. Though I don't even have that many. 

I understand that you probably can't help me without more data, but maybe you can help me to figure out how to get more data? 

Sorry about the unstructured issue, maybe issue is somehow related to my mac, maybe something with the filesystem. not sure. I will do some more restarts and so on, but this is odd

**Comment by lucacasonato** [comment]
Could you give us the import + the contents of that file?

And as a sanity check can you remove your DENO_DIR manually and try again?

**Comment by martunta** [comment]
```
import { some } from '../services/something.js';
...
```
and this is file to import. 
```
export const some = () => {
  return "Test";
}
```
Then again, this happens also with import files that are already used in other parts of the system, not with only the new file. Somehow it feels like I have reached some threshold of total imports. 

So, if stop importing one of the files, then I can start importing this new file - and the system works. But if I import both, then it breaks, with no messages.

This makes me think about some sort of system limitations, but no idea how to test it. I will try and see if I can replicate on the new project reliably (or at all).

**Comment by martunta** [comment]
couldn't replicate it within new project. while in the existing project behavior was very consistent - silent "too many imports".

deleted `~/Library/Caches/deno` and now it all works normally. the behavior has disappeared.

so probably issue can be closed. Doubt that anything can be done. But silent part is scary :)

**Comment by martunta** [comment]
and its back.

**Comment by lucacasonato** [comment]
Is the project open source? If so could you:

1. delete your entire `~/Library/Caches/deno` again
2. run the code again until the issue occurs
3. zip up your DENO_DIR
4. send the DENO_DIR zip + a zip or GH link of the project (source code) + the commands you are running?

It would make debugging a lot easier.

**Comment by martunta** [comment]
it is not open source. but yes, now it seems that pattern is like this - delete deno folder, run the server, it downloads everything, and server works well. kill it, start again, and it doesn't work anymore. there is no change buildinfo file in between the two occasions.

**Comment by caspervonb** [comment]
Really going to need a more concrete narrow example of how to reproduce this.

**Comment by martunta** [comment]
I will try to come up with a repo like that

**Comment by martunta** [comment]
I am trying to create new repo where I could replicate it without having to open source my application, but I am not able to do it. The issue persists, and then after the deletion of the cache, it disappears. but when I use my main repo, after deletion of cache it disappears, but then reappears within one restart of the application. 

Is there any way I could debug it myself? Maybe it is somehow connected to the database or something else within the environment? what exactly were you planning to do with the repo and the zip? Is there some kind of debug mode that I could activate to see where it fails exactly? Something besides -L debug as it doesn't show anything

**Comment by bartlomieju** [comment]
@martunta please try again on latest `deno` (`1.5.2`). If the issue persist then it'd be useful if we could look into the reproduction code. Running with `-L debug` flag would also be useful.

**Comment by bartlomieju** [comment]
Closing as stale
