### ISSUE TITLE
Test fails on CI but works fine on my local machine

### ISSUE THREAD

**Issue by qti3e** [denoland/deno#701]
When I run tests locally it works just fine, but it fails on CI with the following error:
```
ERROR: Operands of '+' operation must either be both strings or both numbers, consider using template literals
```

Probably, the test script uses a different version of something and it's against reproducible builds which is one of Deno's build system goal.

Creating this issue so that we can investigate this behaviour later:
Head: e12b94aa717542c2fe90b2cf29a4000265d9a4aa
CI: https://ci.appveyor.com/project/deno/deno/build/961.master

**Comment by kitsonk** [comment]
Just to note, I am getting a strange behaviour with TypeScript running on Windows too, where it is requesting additional files that it shouldn't be requesting: https://ci.appveyor.com/project/deno/deno/build/957.master#L213

It doesn't happen on other operating systems, and none of the code we run directly against TypeScript should be requiring that either.

**Comment by MarkTiedemann** [comment]
@qti3e I saw the following code in your commit: `console.log("SET " + kind);` where `kind` is not a string. Not sure about the discrepancy between your machine and CI, but I'm pretty sure you can fix the error by just cleaning up that log statement.

**Comment by qti3e** [comment]
@MarkTiedemann Yeah, that was a left-over debug statement, and I removed that eventually, the problem here is why I haven't got the error on my local machine? If something is wrong, it _must_ be wrong everywhere not only CI.

**Comment by qti3e** [comment]
Thanks, Sajjad!
