### ISSUE TITLE
Test std with "isolatedModules" on

### ISSUE THREAD

**Issue by nayeemrmn** [denoland/deno#7015]
This will ensure or mostly ensure that everything works with `--no-check`.

The following currently does not work due to a type export not using the explicit `export type` syntax:
```
deno cache --no-check -r std/log/mod.ts
```

We can catch these errors at testing with:
```
deno test -c std/tsconfig.json std
```
```ts
{
  "compilerOptions": {
      "isolatedModules": true
  }
}
```
Are there things that conversely _only_ work with `"isolatedModules"` rules? If so we should check `std` with it both on and off.

It is a goal for v2.0.0 is to have this setting on by default / always.

**Comment by kitsonk** [comment]
> Are there things that conversely only work with `"isolatedModules"` rules?

Not that I am aware of.

We only would need to modify: https://github.com/denoland/deno/blob/master/std/tsconfig_test.json

**Comment by nayeemrmn** [comment]
Ah, I see `"importsNotUsedAsValues": "error"` was supposed to achieve this, but it thinks re-exporting suffices as using as a value. We can replace that setting then.
