### ISSUE TITLE
Error at /std@0.65.0/textproto/mod.ts

### ISSUE THREAD

**Issue by SirKastic** [denoland/deno#7058]
I'm getting the following error when trying to compile:
```
$ deno run server.js --allow-net
Compile https://deno.land/std@0.65.0/http/server.ts
error: TS2322 [ERROR]: Type 'Uint8Array | undefined' is not assignable to type 'Uint8Array | null'.
  Type 'undefined' is not assignable to type 'Uint8Array | null'.
    return line;
    ~~~~~~~~~~~~
    at https://deno.land/std@0.65.0/textproto/mod.ts:149:5
```

my code:
```
import { listenAndServe } from 'https://deno.land/std/http/server.ts'
import { acceptWebSocket, acceptable } from 'https://deno.land/std/ws/mod.ts'

import chat from './chat.js'

listenAndServe({port: 3000}, async req => {
  if (acceptable(req)) {
    acceptWebSocket({
      conn: req.conn,
      bufReader: req.r,
      bufWriter: req.w,
      headeres: req.headers
    }).then(chat)
  }
})

console.log('Server started on port 3000')
```

**Comment by Sparkenstein** [comment]
What version of Deno are you on?
Using official example of [client](https://deno.land/std@0.65.0/ws#client) I was able to connect to the server you have given above. I did the following changes though:
 - `headers` spelling is incorrect in your example
 - run it like `deno run --allow-net server.ts` and not like `deno run server.ts --allow-net`.

**Comment by SirKastic** [comment]
> 
> 
> What version of Deno are you on?
> Using official example of [client](https://deno.land/std@0.65.0/ws#client) I was able to connect to the server you have given above. I did the following changes though:
> 
>     * `headers` spelling is incorrect in your example
> 
>     * run it like `deno run --allow-net server.ts` and not like `deno run server.ts --allow-net`.

```
$ deno --version
deno 1.0.0-rc2
v8 8.4.300
typescript 3.8.3
```

I corrected the headers mispelling, and changing the order of the argument in the run command but I kept getting the same error
I tried to uptade it but I got:
```
+ Expand-Archive -Path C:\Users\User\AppData\Local\Temp\.tmp1pWriP\deno.zip -Desti ...
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Expand-Archive:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

thread 'main' panicked at 'assertion failed: unpack_status.success()', cli\upgrade.rs:200:3
```

**Comment by Sparkenstein** [comment]
This looks like the same issue as #6109 which is fixed. can you try fresh installation of latest deno?

**Comment by SirKastic** [comment]
Uninstalling and doing a fresh install of deno worked, thanks!
