### ISSUE TITLE
How could I consume Deno compiler from Go

### ISSUE THREAD

**Issue by jmsegrev** [denoland/deno#7062]
[Dgraph](https://dgraph.io) has an [RFC](https://discuss.dgraph.io/t/implement-custom-js-hooks-in-graphql/9361) for adding to their graphql api, JS pre/post hooks to process data. While reading it I got curious if it could be possible to use Deno for this.

Would it be possible to consume Deno compiler from go?

I know Deno runtime unstable compiler api could be exposed via http server. But would there be another way, one that would allow for a more seamless integration?

**Comment by bartlomieju** [comment]
Whole compilation stack in Deno is very much internal and deeply integrated with other parts of the CLI and it wouldn't be feasible to expose it as a lib callable from other languages.
