### ISSUE TITLE
Execute deno on empty dir, wrong error message.

### ISSUE THREAD

**Issue by gungunfebrianza** [denoland/deno#7065]
So i was forgot to change directory, into directory that contain index.ts.
i am not aware that i was execute
deno run -A --unstable index.ts on empty dir...

and i got this error message, so i thought the problem is on my apps

```
error: TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname
                 ~~~
    at https://deno.land/std@0.50.0/path/win32.ts:911:18

TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname;
                 ~~~
    at https://deno.land/std@0.50.0/path/posix.ts:433:18

Found 2 errors.
```

**Comment by Soremwar** [comment]
`deno info --no-check your_entry_file.js`

Better suited for discord though discord.gg/deno

**Comment by gungunfebrianza** [comment]
and if we execute this command in empty directory : 

deno run -A --unstable index.ts

the error above also coming

**Comment by lucacasonato** [comment]
You should be importing std@0.65.0. Also make sure you are on Deno v1.3.0. (run `deno upgrade` to update)

**Comment by Soremwar** [comment]
You sure the dir is empty? Cause then it should throw because `index.ts` doesn't exist

**Comment by gungunfebrianza** [comment]
yes on my windows OS, it does not return wrong error message like above so i was confused.

**Comment by gungunfebrianza** [comment]
> 
> 
> You should be importing std@0.65.0. Also make sure you are on Deno v1.3.0. (run `deno upgrade` to update)

yes its the newest version. i change the title and problem

**Comment by Soremwar** [comment]
Can you run `dir` on the folder you say it's empty?

**Comment by jeroenptrs** [comment]
make sure you are on std@0.65.0. The log clearly states you are on an old version of std

**Comment by Yamboy1** [comment]
Do you have any other dependencies? Maybe one of those also depends on std@0.50.0, use `deno info mod.ts` to see a full dependency list
