### ISSUE TITLE
Politics playground

### ISSUE THREAD

**Issue by golavr** [denoland/deno#7073]
I see the BLM banner in nodejs main page thinking that some open source projects have become platform for self righteous and gospel carriers.
Do you think you can keep deno out of this war games?
Have open source project w/o color/gender/race and all things that make people divided?
I was silenced brutally in SASS github project by people talking about "the rights of our fellow human beings".

"Sass in particular has always been a political project. From its earliest days it sought to empower designers, who tended to have a much stronger representation of marginalized groups than their engineering counterparts, and in so doing it gave these marginalized people a larger place and a louder voice in tech as a whole. The most prominent voices in the Sass community have always been people of color, queer people, and women, and empowering those people is a political act in an industry dominated by straight white men."

**Comment by golavr** [comment]
I'll take it as a no.
Good luck building second political platform.

**Comment by Abhishek12345679** [comment]
lmao @golavr you deserved it.
