### ISSUE TITLE
cli: wrong output for deno help --help 

### ISSUE THREAD

**Issue by timreichen** [denoland/deno#7078]
```sh
deno help --help
```
expected:
```
error: Found argument '--help' which wasn't expected, or isn't valid in this context
```
actual:
```
error: The subcommand '--help' wasn't recognized
```

**Comment by nayeemrmn** [comment]
`deno -h` says:
```
SUBCOMMANDS:
    help           Prints this message or the help of the given subcommand(s)
```
so `deno help <subcommand>` is the correct usage, meaning the current error message is fine. This is `clap`'s scope anyway.

**Comment by timreichen** [comment]
OK. I was confused by that error message. But I guess it makes sense if it is interpreted as a subcommand rather than an argument.
