### ISSUE TITLE
Feature-Request - Add Join,Room,Broadcast Functionality in std websocket

### ISSUE THREAD

**Issue by WhoAdarshPandya** [denoland/deno#7079]
Hey i come from **node.js** background where i used **socket.io**, but when i tried **deno** i saw that Sockets have different implementations **in socket.io** once we are connected **they provided facility to Broadcast or emit the messages , also they have functionality of joining a room for specific 2 persons chat** , over there i used to write like **```io.to(room id).emit(msg)```** , **i don't know how to broadcast messages or create rooms** in deno web sockets

it would be nice if we have functionalities like **room/join/broadcast** in standard library , or else please let me know how to **implement that functionality of the same**

Thank You 👍

**Comment by narwy** [comment]
You could create a module to support that functionality but it shouldn't be standard.

**Comment by WhoAdarshPandya** [comment]
@narwy that's the thing buddy, i don't know how to write implementations for the same , i've just used it in node

**Comment by narwy** [comment]
@WhoAdarshPandya I would look at modules like https://github.com/ryo-ma/deno-websocket and make suggestions or ideas on modules vs this being core functionality.

**Comment by ry** [comment]
higher level functionality can be built on top of std/ws ...
