### ISSUE TITLE
Suggestion: Improve --v8-flags documentation

### ISSUE THREAD

**Issue by stonetwig** [denoland/deno#7084]
When running deno with v8-flags the documentation is a bit vague with examples.

For example, running these following has no effect and gives no errors:

```
--v8-flags="--max-old-space-size=8192"
--v8-flags="--max-old-space-size 8192"
--v8-flags="asd 123"
```

This should probably give some sort of error (at least) so the users don't have a false belief that their options actually work.

```
--v8-flags=--max-old-space-size=8192 // works
--v8-flags="--max-old-space-size=8192" // seems to have zero effect
```

**Comment by ry** [comment]
At least in version 1.3.0 there is an error when a V8 flag is not recognized:
```
> deno run --v8-flags="asd 123" cli/tests/002_hello.ts
error: V8 did not recognize flag 'asd 123'

For a list of V8 flags, use '--v8-flags=--help'
```
What version are you using?

**Comment by stonetwig** [comment]
Sorry, my bad Ryan. I am on 1.2.1 and I didn't try it with the latest version.

Thanks for all of your work, I really admire you.
