### ISSUE TITLE
carriage returns are improperly parsed in console.log 

### ISSUE THREAD

**Issue by EmNudge** [denoland/deno#7090]
Windows 10, Deno v1.1.2
Carriage returns are parsed when used inside of a `console.log`. This manifests itself when parsing lines from a text file in Windows and forgetting to split by `\r\n`.

When given a list of names
```
George
Greg
Alvin
Norman
Alice
Sarah
```
and then some code to retrieve them
```ts
const names = Deno.readTextFileSync("./file.txt").split('\n');

console.log({ names })
```
An unexpected and unactionable error occurs. 
![image](https://user-images.githubusercontent.com/24513691/90457326-388c7980-e0c9-11ea-904c-9a3f10273689.png)
Text appears to be mangled and concatenated. 
Contrast this with other JavaScript environments, such as Node.js
![image](https://user-images.githubusercontent.com/24513691/90457442-8903d700-e0c9-11ea-89ea-be9c350f56ab.png)
Where carriage returns are not parsed at all.
In Chrome, carriage returns seem to be stripped from the output, which I've been told falls in line with the spec.

**Comment by tumile** [comment]
Another example, deno 1.3.0
```js
console.log(["one\r", "two\r", "three\r"]);

// Node
[ 'one\r', 'two\r', 'three\r' ]
// Deno
" ]"three
```
