### ISSUE TITLE
Deno is unable to convert Proxy object to a string, thus unable to log

### ISSUE THREAD

**Issue by 00ff0000red** [denoland/deno#7096]
Because of Deno logs stuff (`console.log`) by converting them to strings using its own built-in functions, it appears that when an object has a proxy denying any access to any properties, it cannot be converted, and throws an error.

I accidentally encountered this after wrapping an array with a proxy, while I had yet to set up my handers.

Example recreation code:
```ts
console.log(
	new Proxy([], { get() { } })
);
```

**Comment by sebastienfilion** [comment]
Moreover, it seems that the process just hang when trying to log the proxy.

**Comment by kitsonk** [comment]
> using its own built-in functions

Everyone has to do that... it isn't unique to Deno.  `console` is not part of the language specification, it is a convention for browsers and other runtimes.

It is a bug though.

**Comment by uki00a** [comment]
I'll work on a fix.

**Comment by 00ff0000red** [comment]
> > using its own built-in functions
> 
> Everyone has to do that... it isn't unique to Deno. `console` is not part of the language specification, it is a convention for browsers and other runtimes.
> 
> It is a bug though.

Well, I guess. Also, might I mention some other console-related bugs I've noticed? Should I open another issue?

**Comment by 00ff0000red** [comment]
> Moreover, it seems that the process just hang when trying to log the proxy.

Really? I was getting errors along the lines of "cannot convert to a string" and later after creating a recursive problem with the Proxy, "precision depth exceeded" errors. Currently on Deno 1.10.
