### ISSUE TITLE
How does WebAssembly.Module run under Deno?

### ISSUE THREAD

**Issue by reselbob** [denoland/deno#7100]
Hi:

Using this as an example:

```
const wasmCode = await Deno.readFile("./rust_for_deno/target/wasm32-unknown-unknown/release/cube_it.wasm");
const wasmModule = new WebAssembly.Module(wasmCode);
const wasmInstance = new WebAssembly.Instance(wasmModule);
```

I am wondering how a WebAssembly binary runs under Deno server-side. Is the binary hosted in some sort of implicit WebAssembly VM or does Deno just load the binary into memory using a bit of automagic and then extract the operational function logic via a standard interface such as WASI again using some sort of automagic?

I am very interested to know where and how the WebAssembly binary lives under Deno.

Thanks in advance for helping me get a better understanding.

Bob

**Comment by ry** [comment]
@reselbob This is for the most part all built-in to the V8 VM. So this is pretty much the same way WASM is handled in the Chrome browser. https://github.com/v8/v8/tree/master/src/wasm

**Comment by reselbob** [comment]
Thank you @ry. This is important, useful information for me. I've been doing a series of articles on Deno. This information will appear in an upcoming installment.

**Comment by caspervonb** [comment]
> Is the binary hosted in some sort of implicit WebAssembly VM or does Deno just load the binary into memory using a bit of automagic and then extract the operational function logic via a standard interface such as WASI again using some sort of automagic?

As Ryan mentioned, WebAssembly itself is entirely managed by V8.

Host bindings like WASI have the same semantics as they would in a Browser environment and are provided in JS. They get passed in as WebAssembly.Instance imports upon instantiation.

**Comment by reselbob** [comment]
PS @ry : Anyway I can read up on the mechanics of how a WebAssembly binary is accessed via the V8 VM? For example, if I am want to work with a MySQL database, to access it, I declare <IPAddress:port>  and the mechanics of the protocol takes care of the interaction. How is interaction facilitated with a WASM binary operating in the V8 VM? Is simply identifying the binary via its filespec enough? If I am asking a lot, please feel free to say, "Too much". You won't hurt my feelings. I will understand completely.

**Comment by ry** [comment]
@reselbob Web assembly doesn't have the ability to open sockets, or perform any I/O. It's a purely computational thing. The "WASI" effort (https://deno.land/std@0.65.0/wasi) is a work-in-progress to add something like syscalls to wasm. The way this works is by calling out, through javascript, to various functions in the Deno namespace.
