### ISSUE TITLE
Does deno working on Win7? cause nodejs are not working on win7 now.

### ISSUE THREAD

**Issue by lygstate** [denoland/deno#7111]
Win7 are still broadly used platform

**Comment by caspervonb** [comment]
For better or worse, Windows 7 has reached end of life.

It's a pain to even re-install Windows 7 these days as Microsoft will try to up-sell you on every single update you download.

In practice tho, most of Deno does work on Windows 7.

**Comment by lucacasonato** [comment]
As Casper said, Windows 7 is EOL. Deno mostly works on old Windows releases, but some features might not work. The support is kinda best effort basis, but it is not a high priority target.

I will close this issue as it is a question without any actionable bug or feature request. Questions are usually better suited for https://discord.gg/deno.
