### ISSUE TITLE
Implement CompressionStream

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#7113]
Compression streams allow for compression and decompression of data in a streaming way.

Example:
```js
const res = await fetch ("https://example.com/gzipcompressedfile.txt");
const data = res.body.pipeThrough(new DecompressionStream("gzip")).getReader();
// do something with the data here
```

Spec: https://wicg.github.io/compression/

This is a web standard, and it is implemented in Chrome stable.

**Comment by kitsonk** [comment]
This one I am less convinced on... Chrome was intent to prototype only, and it has been in Blink since 80, it doesn't seem to be overly common.  There are no public signals outside of Chrome (https://www.chromestatus.com/feature/5855937971617792) and there isn't even an MDN page.  This feels still quite experimental, with changes to the the specification as recently as mid-Feb this year.  Feels like this should bake in the oven longer to me.

**Comment by crowlKats** [comment]
i'd be in favour of this api and would start working on it if it is wanted. i disagree that we shouldnt implement it because recent changes to the spec; quite a few apis still get recent changes including the streams api which is one of the main subjects of this api.
Regardless if we implement this or not, i think we should have bindings/ops for compression.

**Comment by lucacasonato** [comment]
Because the API is available in Chrome stable, I think it won't change in any breaking ways in the future. It is still not implemented in Safari and Firefox, because they don't even implement the TransformStream API yet.

@crowlKats If you want to work on this, maybe you could move `11_streams.js` from the fetch op crate to the web op crate first (or new streams op crate?).

**Comment by kitsonk** [comment]
@lucacasonato Chrome has shipped a lot of things in stable and removed them later, much to a lot of frustration. It is still an intent to prototype, which makes it  very risky. I think we need stronger evidence of some sort of support and stability.

**Comment by MarkTiedemann** [comment]
> There are no public signals outside of Chrome

Mozilla considers this feature "worth prototyping", see: https://github.com/mozilla/standards-positions/issues/207

> there isn't even an MDN page

MDN pages for the API do exist now: https://developer.mozilla.org/en-US/docs/Web/API/Compression_Streams_API

Might be worth to reconsider.

**Comment by jed** [comment]
Given that Deno Deploy doesn't handle compression for unsupported mime types, it would be nice to have this to allow users to handle compression themselves. For example, I'd like to compress an outgoing `event-stream` content type that has base64-encoded data lines.

**Comment by o-t-w** [comment]
This just landed in [Node 16.7.0 ](https://nodejs.org/api/webstreams.html#webstreams_class_compressionstream)

**Comment by jimmywarting** [comment]
> Chrome has shipped a lot of things in stable and removed them later, much to a lot of frustration. It is still an intent to prototype, which makes it very risky. I think we need stronger evidence of some sort of support and stability.

can't agree more, it has become it's own little version of internet explorer that adds chrome only features while firefox and safari laggs behind and they can't do anything other than hammering on new browser api that floods in. Chrome has trully gotten a monopoly in the browsers usage and a unfair advantage over competitor... the fact that IE stepped down is both good and bad.
ppl only use chrome cuz we keep telling user that sites only works in chromium browser to get the new latest features. 
I only use chrome cuz it gets the new features first, but i wish to use safari cuz it's so much faster but it lacks many new shiny web things and the devtool is pretty bad in comparison. 

Vendors should agree upon something before shipping stuff.

**Comment by o-t-w** [comment]
It looks like Safari Technology Preview 152 just shipped this. Release notes [here](https://webkit.org/blog/13137/release-notes-for-safari-technology-preview-152/#:~:text=Implemented%20Compression%20Streams%20API%20(253093%40main)).
