### ISSUE TITLE
Implement TextEncoderStream

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#7114]
Text encoder streams allow you to easily encode or decode binary data streams.

Example:
```js
const res = await fetch ("https://example.com/file.txt");
const data = res.body.pipeThrough(new TextDecoderStream()).getReader();
// do something with the data here (which is now a readable stream of strings)
```

Spec: https://encoding.spec.whatwg.org/

This is a web standard, and it is implemented in Chrome stable.

**Comment by kitsonk** [comment]
It is effectively "low cost" in that we already have all the stream infrastructure and this just builds on it, but then again we really haven't found a lot of uses for the streams as a whole because they are such a complex way to achieve things.  Was there a specific use case you had in mind?

**Comment by lucacasonato** [comment]
I think it makes a lot of sense when #4898 will eventually be implemented. Streaming request handling will be very, very simple to do then:

```ts
function handle(event: FetchEvent) {
  const capitalizer = new TransformStream({
    start() {},
    async transform(chunk, controller) {
      controller.enqueue(chunk.toUpperCase())
    } 
  })

  event.respondWith(new Response({
    status: 200,
    headers: { 'Content-Type': 'text/plain' },
    body: event.request.body
      .pipeThrough(new TextDecoderStream())
      .pipeThrough(capitalizer)
      .pipeThrough(new TextEncoderStream())
      .getReader()
  }))
}
```
