### ISSUE TITLE
No tests are run - Running 0 tests  test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

### ISSUE THREAD

**Issue by johny1614** [denoland/deno#7122]
Reproduction steps: create file testStart.ts

`Deno.test("hello world #1", () => {
  const x = 1 + 2;
 console.log('hello world');
  assertEquals(x, 3);
});
`

run with:

> deno test testStart.ts -A

Actual result: Test does not run, cmd prints:
`running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out (0ms)
`

**Comment by lucacasonato** [comment]
This works for me:

```ts
import { assertEquals } from "https://deno.land/std@0.65.0/testing/asserts.ts"
Deno.test("hello world #1", () => {
  const x = 1 + 2;
  console.log("hello world");
  assertEquals(x, 3);
});
```

Ran with `deno test testStart.ts -A`:

```
running 1 tests
test hello world #1 ... hello world
ok (2ms)

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out (2ms)
```
What version of Deno are you using? `deno --version`

**Comment by johny1614** [comment]
Im not sure why I didn't have any alert about not importing assertEquals, but now I have if not imported.
Perhabs there should be import in docs import, [https://deno.land/manual/testing](url).
Everything works now, Thanks  :)
