### ISSUE TITLE
Using `export * as` pattern in deps.ts with asserts from stdlib causes type annotation error

### ISSUE THREAD

**Issue by MasterKale** [denoland/deno#7129]
Some version info before I begin:

```
$> deno --version
deno 1.3.0
v8 8.6.334
typescript 3.9.7
```

### Issue:

I discovered a weird quirk using `assert` from the **asserts** module in the stdlib.

Assume my **deps.ts** file has the following export:

```ts
export * as asserts from "https://deno.land/std@0.65.0/testing/asserts.ts";
```

I then attempt to use `asserts.assert` to write a test in **assertTest.ts**:

```ts
import { asserts } from "./deps.ts";
import { assert as assert2 } from "https://deno.land/std@0.65.0/testing/asserts.ts";

const { assert } = asserts;

assert(true === true);
assert2(true === true);
```

However, when I execute `deno run assertTest.ts`, Deno reports an error:

```
$> deno run src/assertTest.ts
Check file:///Users/masterkale/Repos/deno-test/assertTest.ts
error: TS2775 [ERROR]: Assertions require every name in the call target to be declared
with an explicit type annotation.
assert(true === true);
~~~~~~
    at file:///Users/masterkale/Repos/deno-test/assertTest.ts:8:1

    'assert' needs an explicit type annotation.
    const { assert } = asserts;
            ~~~~~~
        at file:///Users/masterkale/Repos/deno-test/assertTest.ts:6:9
```

If I comment out that first assertion, the second assertion succeeds as expected.

There seems to be something wrong with my using `export * as asserts` to include the Deno testing lib in my project, type annotations are getting dropped?

I _did_ discover that if I go into my cached copy of asserts and change the return type from `asserts expr`:

```ts
export function assert(expr: unknown, msg = ""): asserts expr {
  if (!expr) {
    throw new AssertionError(msg);
  }
}
```

To `void`:

```ts
export function assert(expr: unknown, msg = ""): void {
  if (!expr) {
    throw new AssertionError(msg);
  }
}
```

The issue is resolved. I don't quite know what to make of this in the context of Deno. I'm new to Deno (but not JS dev) so I'm reporting this with a hint of "maybe it's operator error?"

**Comment by kitsonk** [comment]
This is not a Deno issue. It is a limitation of TypeScript. See microsoft/typescript#37818

**Comment by MasterKale** [comment]
Aha! Thank you for linking that, I'll follow the conversation over there ✌️
