### ISSUE TITLE
Support preload scripts

### ISSUE THREAD

**Issue by qti3e** [denoland/deno#713]
As [previously disscused](https://github.com/denoland/deno/issues/428) in issues, it would be nice to support registering custom protocol handlers for imports, so, for example, people can use codes like:
```ts
import * as x from "github://user/repo/file.ts"
```
This process requires Deno to support preload scripts (something like electron's preload scripts)

A preload script might look like this:
```ts
import * as deno from "deno";

// I like electron's approache for this
// https://github.com/electron/electron/blob/master/docs/api/protocol.md
deno.registerCustomProtocol("github", url => {
  return new URL("http://github.com/...")
});
```
It can be used like:
```
deno app.ts --preload github.proto.ts
```

**Comment by ry** [comment]
I don't want to do this any time soon. I can understand a potential need for this - but Deno needs more functionality first.

**Comment by metanomial** [comment]
@ry Any reconsideration for this feature now that v1.0.0 is stable?
