### ISSUE TITLE
pm2 & deno 

### ISSUE THREAD

**Issue by michael-spengler** [denoland/deno#7137]
First of all again thank you for the great work and with that for deno.

Is there a plan to have something like pm2 for deno - e.g. pm_deno? 

Background:
Today I published a module which might seem off topic but it actually saves me and potentially others some time:
https://deno.land/x/http_to_https@v1.1.0

I thought it would be cool to be able to write something like:

pm2 start  --interpreter="deno" --interpreter-args="run --allow-net --allow-read" **https://deno.land/x/http_to_https@v1.1.0/forwarder.ts**

instead of 

```sh
git clone https://github.com/michael-spengler/http_to_https.git
cd http_to_https
pm2 start  --interpreter="deno" --interpreter-args="run --allow-net --allow-read" forwarder.ts
```

**Comment by nayeemrmn** [comment]
`pm2` is third-party to NodeJS, isn't it? Nothing to do here.

**Comment by michael-spengler** [comment]
> Pretty sure you can just drop that in

I tried - pm2 needs the file locally - this luxury of just using https... is from my perspective something deno specific - I almost already forgot this because I got so used to it already :)

**Comment by lucacasonato** [comment]
This seems better suited for discussion on https://discord.gg/deno. This issue tracker is for issues or feature requests related to Deno, not questions :-)

**Comment by michael-spengler** [comment]
ok - closing it

**Comment by BoltDoggy** [comment]
create `app.sh`

```
#!/bin/bash
deno run -A myCode.ts
```

then `pm2 start ./app.sh`

You don't need to clone for deno.

**Comment by Hexagon** [comment]
Just for reference - now there is a "native" alternative to pm2 - Pup

See https://hexagon.github.io/pup or https://deno.land/x/pup
