### ISSUE TITLE
x-typescript-types is not used on initial load with deno cache/deno run

### ISSUE THREAD

**Issue by jeroenptrs** [denoland/deno#7145]
> Little context as preface: I'm trying out some polyfilling tricks to serve modules from jsdelivr/jspm with std/node and type declarations loaded in the background. The URLs below are from a dev instance of that project and code can be checked [here](https://github.com/denofn/dreg)

Given the following dependency `https://cdn-dev.dreg.dev/package/picomatch@2.2.2`, which gets loaded with type declarations with a `x-typescript-types`, plainly running `deno cache https://cdn-dev.dreg.dev/package/picomatch@2.2.2` will error unless you also add `--no-check`. The same is true for a script that uses this dependency:

```ts
import picomatch from "https://cdn-dev.dreg.dev/package/picomatch@2.2.2";

const isMatch = picomatch("*.js");
console.log(picomatch.test("foo/bar", /^(?:([^/]*?)\/([^/]*?))$/));

console.log(isMatch("abcd")); //=> false
console.log(isMatch("a.js")); //=> true
console.log(isMatch("a.md")); //=> false
console.log(isMatch("a/b.js")); //=> false
```

Running `deno cache --no-check` runs as expected and also stores the type hints, so consecutive runs of `deno run` do not need the no-check flag and actually respect the type declarations.

In the case of (also) adding a `--reload` flag: this does *not* work with `deno cache` but *does* with `deno run` so I'm a little confused.

**Comment by kitsonk** [comment]
This is no longer and issue in 1.5.2.
