### ISSUE TITLE
deno fmt - Automatically sort named import and export specifiers?

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#7150]
I am working a new feature in dprint-plugin-typescript to sort import and export specifiers in alphabetical order.

For example, given the following:

```ts
import { Person, doWork, buildMap, Car } from "./file.ts";
```

It would do:

```ts
import { buildMap, Car, doWork, Person } from "./file.ts";
```

Should this be turned on for `deno fmt`?

**Case Insensitive Comparison or Case Sensitive?**

Also, should this be case insensitive or case sensitive? Above is case insensitive. Case sensitive looks like this:

```ts
import { Car, Person, buildMap, doWork } from "./file.ts";
```

It seems eslint will do case sensitive by default: https://eslint.org/docs/rules/sort-imports#ignorecase -- so that might be reason to make it case sensitive (also less work doing the comparison)

**Comment by bartlomieju** [comment]
I'm in favor of this change, I think we'll also want to add `sort-imports` rule to `deno lint`.

**Comment by kitsonk** [comment]
I would say if you have something that `deno fmt` does then you don't check it with `deno lint`. We don't lint for ASI for example.

**Comment by igorbrasileiro** [comment]
How can I use the organizeImports from deno with neovim (nvim_lsp) ?

**Comment by dsherret** [comment]
Just disable that and only use deno fmt.

**Comment by dsherret** [comment]
Or did you mean the organize imports quick action? That's unrelated to this issue.

**Comment by igorbrasileiro** [comment]
> Or did you mean the organize imports quick action? That's unrelated to this issue.

Yeah, I mean organize imports with editor quick action. I'm trying to do this via neovim LSP, like vscode does.
