### ISSUE TITLE
Deno calls object getters when logging, resulting in code that performs differently than expected.

### ISSUE THREAD

**Issue by 00ff0000red** [denoland/deno#7153]
In all browser vendors and Node.js, when using `console.log` on an object containing getters, the getters are shown as getters, they aren't actually called.

Example:
```ts
let i = 0n;

const objectContainingGetter = {
	get x() {
		return ++i;
	}
};

console.log(objectContainingGetter);
// expected to be something along the lines of
// { [x: getter] }

console.log(objectContainingGetter.x);
// expected to be "1n"
```

**Comment by 00ff0000red** [comment]
Has this been fixed in the pull request connected to getters and setters in general allowing them to be logged?

**Comment by solson** [comment]
For reference, node prints it like this:

```console
> console.log(objectContainingGetter)
{ x: [Getter] }
```
