### ISSUE TITLE
Signal default actions never restored after `sig.dispose()` called

### ISSUE THREAD

**Issue by kevinkassimo** [denoland/deno#7164]
Example:

```ts
const sig = Deno.signal(Deno.Signal.SIGINT);
// don't exit
const exitBlocker = setTimeout(() => {}, 100000);
await sig;
sig.dispose()
console.log("Signal disposed");
// Now if you try Ctrl-C it will still never exit the program, as default is never restored.
```

This is due to upstream Tokio behavior: See https://github.com/tokio-rs/tokio/blob/138eef352671aadffca304d62c69cb2582e64f2a/tokio/src/signal/unix.rs#L346-L361

It is debatable if we should reset to [`SIG_DFL`](https://man7.org/linux/man-pages/man2/sigaction.2.html) ourselves, but it will break Tokio's handling due to Tokio having no idea we secretly resets and it relies on the presence of some `SigInfo` struct to determine if we have ever registered for listeners, meaning future reregistration will no longer work.

While it is probably more of a Tokio issue here if we want the default handling back, it might be worthy for us to discuss even if reset to default is the right thing to do. Also we need tracking of this issue on our side.

Notice Node.js does seem to reset to default correctly:
```js
let counter = 0;
function handler() {
  console.log("Register");
  counter++;
  if (counter == 3) {
    console.log("Unregister");
    process.off('SIGINT', handler);
    // Ctrl-C after this kills the program
  }
}

process.on('SIGINT', handler);
setTimeout(() => {}, 100000);
```

**Comment by lucacasonato** [comment]
@kevinkassimo Should I classify this is a bug. Is there something actionable to do here?

**Comment by bartlomieju** [comment]
Tokio documentation (https://docs.rs/tokio/1.5.0/tokio/signal/unix/struct.Signal.html#caveats) explicitly states that dropping a signal handler won't restore default behavior; we need to handle that situation ourselves. Most likely we'll need to keep track of number of registered/unregistered `SIGINT` signal and if it goes to zero we should add default handler that exits the process.
