### ISSUE TITLE
There should be separate MediaType for .d.ts files

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#7168]
Although `.d.ts` files are mostly treated just like `TypeScript` files it turns out SWC needs special setting in `Syntax(TypeScript)` to properly handle declaration files. 

Therefore I think we should have a separate `MediaType` variant for `.d.ts` files (maybe `MediaType::Dts`?) to avoid having to manually handle it every time we use `Syntax` to configure AST parser.

Ref https://github.com/denoland/deno/pull/7167
Ref https://github.com/denoland/deno/issues/7163

CC @kdy1 @kitsonk @ry

**Comment by kitsonk** [comment]
We could bring it up with core team, though I am not sure what it would result in.  There is only some syntax allowed in `.d.ts` files, it is sort of like arguing that header files in C are a language design bug.

@bartlomieju I was thinking about that too... the only problem I see is that it isn't really a seperate media type, in that everywhere it is served, it would not be that, and we would be needing to parse the path of the specifier to "guess".  I ran into an issue with the compiler rewrite, where TypeScript internally treats them different based on extension and I did this:

```rust
impl MediaType {
  /// Convert a MediaType to a `ts.Extension`.
  ///
  /// *NOTE* This is defined in TypeScript as a string based enum.  Changes to
  /// that enum in TypeScript should be reflected here.
  pub fn to_ts_extension(&self, specifier: &ModuleSpecifier) -> &str {
    match self {
      MediaType::JavaScript => ".js",
      MediaType::JSX => ".jsx",
      MediaType::TypeScript => {
        let url = specifier.as_url();
        let path = url.path();
        if path.ends_with(".d.ts") {
          ".d.ts"
        } else {
          ".ts"
        }
      }
      MediaType::TSX => ".tsx",
      MediaType::Json => ".json",
      // TypeScript doesn't have an "unknown", so we will treat WASM as JS for
      // mapping purposes, though in reality, it is unlikely to ever be passed
      // to the compiler.
      MediaType::Wasm => ".js",
      MediaType::BuildInfo => ".tsbuildinfo",
      // TypeScript doesn't have an "unknown", so we will treat WASM as JS for
      // mapping purposes, though in reality, it is unlikely to ever be passed
      // to the compiler.
      MediaType::Unknown => ".js",
    }
  }
}
```

Part of me would want to keep it strictly to things that represent a unique media type and then have a method like that above that can convert it into something more specific (like `is_dts` where you also have to provide the module specifier?)

Though I wouldn't resist the seperate variant though, just bothers me that it would be a lie.

**Comment by bartlomieju** [comment]
@kitsonk I was thinking about exactly the same thing. Even if we don't settle on a separate `MediaType` we'll have to pass specifiers anyway and treat `.d.ts` in a special way. I guess it's just a question which approach is more ergonomic. OTOH `BuildInfo` is also not a separate media type but a JSON file 🤷‍♂️

**Comment by kitsonk** [comment]
> OTOH BuildInfo is also not a separate media type but a JSON file 🤷‍♂️

I suspect if you ever requested it over the network it would not have one.  It _could_ be given a seperate media type because it is a unique extension, but yeah, maybe the easiest thing to do is break `.d.ts` files out as `MediaType::Dts`.  When mapping it from a real media type we look at the logic above in regards to the `.path()`.

**Comment by bartlomieju** [comment]
Closed in https://github.com/denoland/deno/pull/7456
