### ISSUE TITLE
Thoughts on using existing Request / Response types for http server?

### ISSUE THREAD

**Issue by lorenbrichter** [denoland/deno#7176]
Hi,

Has there been any thought to using the existing `Request` / `Response` types for the http server in lieu of the custom `ServerRequest` type?

In a tangentially-related thought, it might be nice to mirror something like the Cloudflare Worker API (which has a very small API surface area) so some common subset of Deno scripts / Workers scripts could seamlessly be deployed either place.

Thanks for the consideration, and the project!
Loren

**Comment by lorenbrichter** [comment]
Good argument for using existing types from https://deno.land/posts/v1 : 

> Deno is careful to not deviate from standardized browser JavaScript APIs. Of course, not every browser API is relevant for Deno, but where they are, Deno does not deviate from the standard.

Also, I haven't dived into it yet, but is there a tremendous impedance mismatch between the almost-standard `ReadableStream` and `WritableStream` and the existing custom Deno.Reader/Writer types?

**Comment by lucacasonato** [comment]
Yes: https://github.com/denoland/deno/issues/4898

**Comment by caspervonb** [comment]
> Also, I haven't dived into it yet, but is there a tremendous impedance mismatch between the almost-standard ReadableStream and WritableStream and the existing custom Deno.Reader/Writer types?

Most of the Deno namespace is very lightweight exposure of nearly bare metal syscalls.

Reader's and Writer's aren't really streams, they're just lightweight wrappers around rid's (sandboxed file descriptors) and syscalls that operate those file descriptors.

Eventually, it might make sense to provide an implementation of the native file system proposal (https://wicg.github.io/native-file-system) but that's still far from stable.

**Comment by lorenbrichter** [comment]
@lucacasonato Awesome! can't wait.
@caspervonb That makes sense. Appreciate the response.
