### ISSUE TITLE
Fix std/testing/bench_test.ts

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#7182]
Running `std` tests in debug mode is prohibitively slow. It takes over 2 minutes to run test suite for benchmarks which is unacceptable.
```
test benching ... running 5 benchmarks ...
benchmark forIncrementX1e9 ...
    64331.947119000004ms
benchmark forDecrementX1e9 ...
    61848.622626ms
benchmark forAwaitFetchDenolandX10 ...
    4852.3491839999915ms
benchmark promiseAllFetchDenolandX10 ...
    220.42760699999053ms
benchmark runs100ForIncrementX1e6 ...
    100 runs avg: 63.27022525000066ms
benchmark result: DONE. 5 measured; 1 filtered
ok (137615ms)
```

Tests should be adjusted to iterate over smaller values so the test doesn't take longer that a few seconds in debug build.

**Comment by ry** [comment]
Yeah that sucks. Maybe we can just skip the benchmark tests entirely on debug?

**Comment by bartlomieju** [comment]
> Yeah that sucks. Maybe we can just skip the benchmark tests entirely on debug?

Or just lower hot loops to smaller values, I think `1e6` instead of `1e9` would work. Marking as "good first issue".

**Comment by caspervonb** [comment]
> Or just lower iteration count in hot loops to smaller values, I think 1e6 instead of 1e9 

Any particular reason why we're not going with a reasonable number of iterations like 1e3?
