### ISSUE TITLE
Import maps not supported in `deno info`

### ISSUE THREAD

**Issue by ykis-0-0** [denoland/deno#7183]
I used import maps in my scripts. When I want to see the dependencies of my scripts by using `deno info --import-map=import_map.json .\src\mod.ts`, Deno says

> error: Found argument '--import-map' which wasn't expected, or isn't valid in this context
>
>USAGE:
>    deno info [OPTIONS] [file]
>
>For more information try --help

and I can't find `--import-map` in `deno info --help`.

Is it possible to make import maps usable in `deno info`?

**Comment by wperron** [comment]
I can take a look at this one
