### ISSUE TITLE
Lint problems in std/

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#7193]
Trying to update `deno_lint` to latest version and more rules I got following errors in `std/`:

```
(no-self-assign) "pathname" is assigned to itself
  url.pathname = url.pathname;
                 ~~~~~~~~~~~~
    at /Users/biwanczuk/dev/deno/cli/tests/unit/url_test.ts:186:17

(no-self-assign) "pathname" is assigned to itself
  url.pathname = url.pathname;
                 ~~~~~~~~~~~~
    at /Users/biwanczuk/dev/deno/cli/tests/unit/url_test.ts:190:17

(no-self-assign) "hash" is assigned to itself
  url.hash = url.hash;
             ~~~~~~~~
    at /Users/biwanczuk/dev/deno/cli/tests/unit/url_test.ts:198:13

(ban-types) Define the function shape Explicitly.
function syscall(target: Function): Function {
                         ~~~~~~~~
    at /Users/biwanczuk/dev/deno/std/wasi/snapshot_preview1.ts:231:25

(ban-types) Define the function shape Explicitly.
function syscall(target: Function): Function {
                                    ~~~~~~~~
    at /Users/biwanczuk/dev/deno/std/wasi/snapshot_preview1.ts:231:36

(ban-types) Define the function shape Explicitly.
  exports: Record<string, Function>;
                          ~~~~~~~~
    at /Users/biwanczuk/dev/deno/std/wasi/snapshot_preview1.ts:301:26

(no-control-regex) Unexpected control character(s) in regular expression: \x0.
  /[\x00-\x08\x0B\x0C\x0E-\x1F\x7F-\x84\x86-\x9F\uFFFE\uFFFF]|[\uD800-\uDBFF](?![\uDC00-\uDFFF])|(?:[^\uD800-\uDBFF]|^)[\uDC00-\uDFFF]/;
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at /Users/biwanczuk/dev/deno/std/encoding/_yaml/loader/loader.ts:29:2
```

@kitsonk I saw that you recently disabled `ban-types` when upgrading TypeScript - is there a specific reason for that?

**Comment by magurotuna** [comment]
I wonder if `url.pathname = url.pathname;` or something like that has any effect.
Are there some reasons these self-assignments are needed?

**Comment by nayeemrmn** [comment]
It's to invoke the setter. That should be `deno-lint-ignore`'d.

**Comment by magurotuna** [comment]
I understood! Thanks for telling.

**Comment by magurotuna** [comment]
I dealt with the cases of `no-self-assign` and `ban-types`.
Only the last one `no-control-regex` is still left, and it seems to me that this error should be ignored as well.

**Comment by kitsonk** [comment]
@bartlomieju I disabled it on some lines where we really couldn't use something else, but no I didn't disable it, in fact it wasn't being enforced until I did an update to eslint as part of the TS4.0 upgrade.  I made a lot of updates to `std` to fix violation of ban-types... the one I disabled that is now on default is `ban-ts-comment`.

**Comment by caspervonb** [comment]
> (ban-types) Define the function shape Explicitly.
function syscall(target: Function): Function {
                         ~~~~~~~~
    at /Users/biwanczuk/dev/deno/std/wasi/snapshot_preview1.ts:231:25

This probably can be stricter but lint-ignore for now.

> (ban-types) Define the function shape Explicitly.
  exports: Record<string, Function>;
                          ~~~~~~~~
    at /Users/biwanczuk/dev/deno/std/wasi/snapshot_preview1.ts:301:26

Lint ignore this, I don't want to deviate from WebAssembly's definition of import values (context exports are instance imports).

**Comment by bartlomieju** [comment]
> @bartlomieju I disabled it on some lines where we really couldn't use something else, but no I didn't disable it, in fact it wasn't being enforced until I did an update to eslint as part of the TS4.0 upgrade. I made a lot of updates to `std` to fix violation of ban-types... the one I disabled that is now on default is `ban-ts-comment`.

@kitsonk Yikes, I must have misread something. Anyway, thanks for explanation. 

@magurotuna I think we can now close this issue and enable the rest of `deno_lint` rules.
