### ISSUE TITLE
Format & Lint Problem in std/

### ISSUE THREAD

**Issue by getspooky** [denoland/deno#7198]
When I run `./tools/format` i got this error in my console

```sh
/usr/bin/python tools/format.py
Traceback (most recent call last):
  File "tools/format.py", line 89, in <module>
    sys.exit(main())
  File "tools/format.py", line 51, in main
    dprint()
  File "tools/format.py", line 59, in dprint
    run(command, shell=False, quiet=True)
  File "/home/getspooky/Documents/OpenSourceProject/deno/tools/util.py", line 62, in run
    rc = subprocess.call(args, cwd=cwd, env=env, shell=shell)
  File "/usr/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

I am using Ubuntu 18

**Comment by nayeemrmn** [comment]
Did you run `git submodule update`?

**Comment by getspooky** [comment]
When i run `git submodule update` i got Permission denied (publickey).

**Comment by ry** [comment]
I guess that's because we're using ssh for wasi submodule
```
[submodule "std/wasi/testdata"]
	path = std/wasi/testdata
	url = git@github.com:khronosproject/wasi-test-suite.git
```
cc @caspervonb

**Comment by caspervonb** [comment]
Oops, my bad 😅

**Comment by getspooky** [comment]
Hi @piscisaureus 
The problem is still exist.

**Comment by ry** [comment]
@getspooky You're on the latest master with all the submodules checked out? What does your `git status` report?

**Comment by nayeemrmn** [comment]
@getspooky On master, try `rm -rf  std/wasi/testdata; git submodule update`. I remember needing to delete the old dir first for some reason.

**Comment by getspooky** [comment]
I run the following commands: 
1. `git fetch upstream`
2. `git merge upstream/master`
3. `rm -rf -rf std/wasi/testdata `
4. `git submodule update`

The Output : 

```sh
Warning: Permanently added the RSA host key for IP address '140.82.121.3' to the list of known hosts.
git@github.com: Permission denied (publickey).

```

**Comment by ry** [comment]
@getspooky I don't know but I'm relatively sure there's something messed up with your checkout. Try deleting it and cloning again.

**Comment by lucacasonato** [comment]
> ```shell
> Warning: Permanently added the RSA host key for IP address '140.82.121.3' to the list of known hosts.
> git@github.com: Permission denied (publickey).
> ```

Pull master again - we changed the wasi test submodule to use the https:// git protocol instead of ssh:// a few hours ago.
