### ISSUE TITLE
refactor(std/log): A classy approach

### ISSUE THREAD

**Issue by timreichen** [denoland/deno#7211]
I briefly used the  `std/log`. To me it seems really unintuitive compared to the other std modules since it does not use js conventions all the way through. I had a look at the code and noticed that it can be simplified while retaining the full functionality by making a few structural changes.

# proposed Changes

## 1.  Restructure mod exports
`mod.ts` exports
- default logger
- handler object
- types
- constants
at the moment. 

To simplify the export structure, let the default logger be the default export of `mod.ts`.
Export handlers directly instead of an object.

before
```ts
import * as log from "https://deno.land/std/log/mod.ts";

log.debug("Hello world");
log.info(123456);
log.warning(true);
log.error({ foo: "bar", fizz: "bazz" });
log.critical("500 Internal server error");

const ConsoleHandler = log.handlers.ConsoleHandler
```
after
```ts
import log from "https://deno.land/std/log/mod.ts";
import { ConsoleHandler } from "https://deno.land/std/log/mod.ts";

log.debug("Hello world");
log.info(123456);
log.warning(true);
log.error({ foo: "bar", fizz: "bazz" });
log.critical("500 Internal server error");

// no need for const ConsoleHandler = log.handlers.ConsoleHandler
```

## 2.  Make default logger unchangable
At the moment `setup(…)` changes the behavior of the default logger behind the scenes. This is very confusing because a function call changes a global variable. Let the default logger be unchangable and let the user create new custom loggers that inherit the default logger's behavior.

## 3. Classes instead of function calls
Let the user have control over all Loggers instead of getting them by passing a string
before
```ts
await log.setup({
  handlers: {
    console: new log.handlers.ConsoleHandler("INFO")
  },
  loggers: {
    default: {
      level: "INFO",
      handlers: ["console"],
    },
  },
});
const defaultLogger = log.getLogger(); // gets default logger
```
after
```ts
const consoleHandler =  new ConsoleHandler("DEBUG")

const fileHandler =  new FileHandler("WARNING", {
  filename: "./log.txt",
  formatter: ({ levelName, msg }) => `${levelName} ${msg}`,
})

const defaultLogger = new Logger({
  level: "DEBUG",
  handlers: [consoleHandler, fileHandler],
})
```

# Code comparison

before
```ts
import * as log from "https://deno.land/std/log/mod.ts";

// Simple default logger out of the box. You can customize it
// by overriding logger and handler named "default", or providing
// additional logger configurations. You can log any data type.
log.debug("Hello world");
log.info(123456);
log.warning(true);
log.error({ foo: "bar", fizz: "bazz" });
log.critical("500 Internal server error");

// custom configuration with 2 loggers (the default and `tasks` loggers)
await log.setup({
  handlers: {
    console: new log.handlers.ConsoleHandler("DEBUG"),

    file: new log.handlers.FileHandler("WARNING", {
      filename: "./log.txt",
      // you can change format of output message using any keys in `LogRecord`
      formatter: "{levelName} {msg}",
    }),
  },

  loggers: {
    // configure default logger available via short-hand methods above
    default: {
      level: "DEBUG",
      handlers: ["console", "file"],
    },

    tasks: {
      level: "ERROR",
      handlers: ["console"],
    },
  },
});

let logger;

// get default logger
logger = log.getLogger();
logger.debug("fizz"); // logs to `console`, because `file` handler requires "WARNING" level
logger.warning(41256); // logs to both `console` and `file` handlers

// get custom logger
logger = log.getLogger("tasks");
logger.debug("fizz"); // won't get output because this logger has "ERROR" level
logger.error({ productType: "book", value: "126.11" }); // log to `console`

// if you try to use a logger that hasn't been configured
// you're good to go, it gets created automatically with level set to 0
// so no message is logged
const unknownLogger = log.getLogger("mystery");
unknownLogger.info("foobar"); // no-op
```
after
```ts
import { Logger, ConsoleHandler, FileHandler } from "https://deno.land/std/log/mod.ts"
import log from "https://deno.land/std/log/mod.ts"

log.debug("Hello world");
log.info(123456);
log.warning(true);
log.error({ foo: "bar", fizz: "bazz" });
log.critical("500 Internal server error");

const consoleHandler =  new ConsoleHandler("DEBUG")
const fileHandler =  new FileHandler("WARNING", {
  filename: "./log.txt",
  formatter: ({ levelName, msg }) => `${levelName} ${msg}`,
})

const defaultLogger = new Logger({
  level: "DEBUG",
  handlers: [consoleHandler, fileHandler],
})
const tasksLogger = new Logger({
  level: "ERROR",
  handlers: [consoleHandler],
})

defaultLogger.debug("fizz"); // logs to `console`, because `file` handler requires "WARNING" level
defaultLogger.warning(41256); // logs to both `console` and `file` handlers

tasksLogger.debug("fizz"); // won't get output because this logger has "ERROR" level
tasksLogger.error({ productType: "book", value: "126.11" }); // log to `console`

// cannot happen
// const unknownLogger = log.getLogger("mystery");
// unknownLogger.info("foobar"); // no-op
```

To me this approach feels more straight forward easier to understand and gets rid of boilerplate as well as strings. What are your thoughts?

**Comment by cknight** [comment]
For point 1, I'm for decomposing the handlers to allow the handler to be imported directly.  I'm not of strong opinion for a default log export.

I'm unsure of point 2.  Most users will want to use the 'unnamed' logger (aka default), but also want to customise it.  It's therefore not unreasonable to want to change it globally.

For point 3, this approach seems to do away with the global state.  How do you propose to reuse logger instances across modules?

**Comment by timreichen** [comment]
# Default logger and default export
Up for debate. I also could see the module not exporting any logger instance at all and instead having reasonable default values set on `Logger` so `new Logger()` will generate a good default logger instance but can be customized easily by passing arguments.

default logger
```ts
import { Logger } from "https://deno.land/std/log/mod.ts"
const defaultLogger = new Logger()
```
custom logger
```ts
import { Logger } from "https://deno.land/std/log/mod.ts"
const defaultLogger = new Logger({
  …
})
```

# Global state
I honestly do not see the necessity of global state approach. An instance of logger can be easily shared between modules by creating and exporting it and then importing it where needed.

```ts
// logger.ts
import { Logger } from "https://deno.land/std/log/mod.ts"
export const logger = new Logger({
  …
})
```

```ts
// a.ts
import { logger } from "./logger.ts"
logger.warn("warning…")
```

```ts
// b.ts
import { logger } from "./logger.ts"
logger.error("error…")
```

**Comment by timreichen** [comment]
@ry @bartlomieju Would you agree to have a simplified restructured implementation of `std/log` without losing functionality? If so I would be glad to make a PR. This would be a breaking change but for the good in my opinion.

**Comment by timreichen** [comment]
# Reasons for the rewrite
## Modularity in favor of global state
The current implementation of std/log contains a global state object that is manipulated functions.
This approach is confusing, because it can be manipulated and changed from anywhere and will potentially change desired behaviors in other modules.
This problem is solved by having a `Logger` class, which instances are not interconnected and can be exported if manipulation/changes are desirable.
## Formatter
Removes string based handler in favor of template strings as discussed [here](https://github.com/denoland/deno/issues/6701).
## Handler instance assignment in favor of string based assignment
Handlers are currently set in the global state and then assigned to loggers by string name.
This is prone to spelling mistakes and might need lookups to receive the right name.
This problem is solved by assigning the `Handler` instances directly.
## Renamings
Follow `js` convention in namings.
## Further ajdustments to be (discussed) and made
### No Critical
`console` has doesn't have a `critical` method. [logLevel](https://www.npmjs.com/package/loglevel) also doesn't use `critical` or `fatal`. Imo the best approach would be to scratch that log level to align with console.
### debug, info, warn, error
some of these methods do not behave the same as in `console`. Not all take multiple arguments and log them correctly. Imo it would be best to align with console.

**Comment by bartlomieju** [comment]
> The current implementation of std/log contains a global state object that is manipulated functions.
This approach is confusing, because it can be manipulated and changed from anywhere and will potentially change desired behaviors in other modules.
This problem is solved by having a Logger class, which instances are not interconnected and can be exported if manipulation/changes are desirable.

Agreed, current behavior stems from my original implementation of the module based on Python's `logging` module. Now I can see that's not the best approach and we should remove global state.

> Template strings instead of string formatter

SGTM

> Handlers are currently set in the global state and then assigned to loggers by string name.
This is prone to spelling mistakes and might need lookups to receive the right name.
This problem is solved by assigning the Handler instances directly.

Also SGTM

> console has doesn't have a critical method. logLevel also doesn't use critical or fatal. Imo the best approach would be to scratch that log level to align with console.

> debug, info, warn, error

>some of these methods do not behave the same as in console. Not all take multiple arguments and log them correctly. Imo it would be best to align with console.

I also agree on this one.

PRs welcome

**Comment by vwkd** [comment]
I like the simplification, but don't like the reduction of error levels. Why does it need to align to the console levels? Error logging is most necessary in production when you don't even have a console, and you can only inspect the files afterwards. The more granularity the better. Also the error levels are totally opt-in. You can use as many as you want and the others will not impact you at all if you don't use them. The six levels have already proven themselves in many languages, like Java, Go, PHP, and Python.

I honestly don't see a strong argument for the reduction of error levels.
