### ISSUE TITLE
function tracing of deno for development

### ISSUE THREAD

**Issue by honggyukim** [denoland/deno#7214]
Hi all,

I have been developing a function tracing tool called uftrace.
https://github.com/namhyung/uftrace

You can have more details from the tutorial slide at https://uftrace.github.io.

It can record and replay all the function execution without source code modification. The simple usage is as follows.
```
# It requires to recompile with `-Z instrument-mcount` option to insert `mcount` calls at the entry of each function.
$ export RUSTFLAGS="-Z instrument-mcount"
$ cargo build

# record the entire function trace
$ uftrace record ./target/debug/deno run cli/tests/002_hello.ts

# replay only functions that spent more than 100ms and filter functions that begins with deno and tokio.
$ uftrace replay -t 100ms -F ^deno -F ^tokio
# DURATION     TID     FUNCTION
            [ 14101] | deno::main() {
            [ 14101] |   deno::tokio_util::run_basic() {
            [ 14101] |     tokio::runtime::Runtime::block_on() {
            [ 14101] |       tokio::runtime::handle::Handle::enter() {
            [ 14101] |         tokio::runtime::context::enter() {
            [ 14101] |           tokio::runtime::Runtime::block_on::_{{closure}}() {
            [ 14101] |             tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on() {
            [ 14101] |               tokio::runtime::basic_scheduler::enter() {
            [ 14101] |                 tokio::macros::scoped_tls::ScopedKey<T>::set() {
            [ 14101] |                   tokio::runtime::basic_scheduler::enter::_{{closure}}() {
            [ 14101] |                     tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::_{{closure}}() {
            [ 14101] |                       std::thread::local::LocalKey<T>::with() {
            [ 14101] |                         std::thread::local::LocalKey<T>::try_with() {
            [ 14101] |                           tokio::coop::with_budget::_{{closure}}() {
            [ 14101] |                             tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::_{{closure}}::_{{closure}}() {
            [ 14101] |                               _<core..pin..Pin<P> as core..future..future..Future>::poll() {
            [ 14101] |                                 _<core..future..from_generator..GenFuture<T> as core..future..future..Future>::poll() {
            [ 14101] |                                   deno::run_command::_{{closure}}() {
 113.479 ms [ 14101] |                                     deno::worker::MainWorker::create();
 190.676 ms [ 14101] |                                   } /* deno::run_command::_{{closure}} */
 190.683 ms [ 14101] |                                 } /* _<core..future..from_generator..GenFuture<T> as core..future..future..Future>::poll */
 190.684 ms [ 14101] |                               } /* _<core..pin..Pin<P> as core..future..future..Future>::poll */
 190.690 ms [ 14101] |                             } /* tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::_{{closure}}::_{{closure}} */
 190.697 ms [ 14101] |                           } /* tokio::coop::with_budget::_{{closure}} */
 190.703 ms [ 14101] |                         } /* std::thread::local::LocalKey<T>::try_with */
 190.704 ms [ 14101] |                       } /* std::thread::local::LocalKey<T>::with */
 190.736 ms [ 14101] |                     } /* tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::_{{closure}} */
 190.737 ms [ 14101] |                   } /* tokio::runtime::basic_scheduler::enter::_{{closure}} */
 190.755 ms [ 14101] |                 } /* tokio::macros::scoped_tls::ScopedKey<T>::set */
 190.772 ms [ 14101] |               } /* tokio::runtime::basic_scheduler::enter */
 190.773 ms [ 14101] |             } /* tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on */
 190.774 ms [ 14101] |           } /* tokio::runtime::Runtime::block_on::_{{closure}} */
 190.832 ms [ 14101] |         } /* tokio::runtime::context::enter */
 190.842 ms [ 14101] |       } /* tokio::runtime::handle::Handle::enter */
 190.842 ms [ 14101] |     } /* tokio::runtime::Runtime::block_on */
 192.079 ms [ 14101] |   } /* deno::tokio_util::run_basic */
 225.965 ms [ 14101] | } /* deno::main */
```
The recorded function trace can be transformed and can be viewed in chrome trace viewer and flame-graph.
- chrome: https://uftrace.github.io/dump/deno.html
- flame-graph: https://uftrace.github.io/dump/deno.svg

[![uftrace-chrome-dump](https://user-images.githubusercontent.com/19642328/91412333-8e87bc80-e841-11ea-9d4f-75c87a86a4a4.png)](https://uftrace.github.io/dump/deno.html)

[![deno.svg](https://uftrace.github.io/dump/deno.svg)](https://uftrace.github.io/dump/deno.svg)

I hope it can be useful when debugging and analyzing the internals during development.

**Comment by honggyukim** [comment]
If anyone is interested, then I can write a guide document at [docs/contributing/development_tools.md](https://github.com/denoland/deno/blob/master/docs/contributing/development_tools.md).

**Comment by ry** [comment]
@honggyukim Very nice! I assume this is a wrapper around dtrace?

**Comment by honggyukim** [comment]
Hi @ry, thanks very much for your feedback.

uftrace is started as a userspace implementation for ftrace in Linux kernel, but supports more filters and visualization. You can easily reproduce the same thing by following the steps in https://github.com/namhyung/uftrace/wiki/uftrace-for-deno.

I actually don't know the details about dtrace, but you can learn more about the usage from the slide at https://uftrace.github.io/slide.

Are you okay if I write a guide document at [docs/contributing/development_tools.md](https://github.com/denoland/deno/blob/master/docs/contributing/development_tools.md)?

**Comment by ry** [comment]
@honggyukim Your slides show a lot of interesting tooling - very cool.

Yes you may write a guide - I would like to try out uftrace some day. But I think the guide should be relatively terse - giving a few concrete examples, but referring the user to the uftrace wiki/homepage/docs for more.

**Comment by honggyukim** [comment]
Thanks a lot @ry! I know the guide is quite terse as I didn't want to make it too verbose to new users.

To be honest, I actually don't have deep knowledge of deno as I'm very new to the project. If you could suggest me to visualize more interesting workloads, then I will try with them.

I think it could be interesting if the workload contains many processes/threads interaction as the chrome trace viewer is timeline based so might be useful to newbies to understand what's going on inside deno execution.

I will try to write better document and ask your feedback Thanks!

**Comment by ry** [comment]
@honggyukim I'm not sure if you've seen our benchmarks page https://deno.land/benchmarks

One of our most important benchmarks in there is the HTTP server performance. Among the various servers running in there, we're most interested in improving the "deno_tcp" program. The code for that is here: https://github.com/denoland/deno/blob/master/tools/deno_tcp.ts

It would be super interesting to see a flamegraph and/or other analysis for that.

**Comment by honggyukim** [comment]
I actually haven't gone through the benchmark yet. Could you please drop me the execution command to properly run and test `deno_tcp`? Thanks.

**Comment by ry** [comment]
```
deno run -A cli/bench/deno_tcp.ts
```
Then you need to create load on the server by runnning
```
wrk http://127.0.0.1:4500
```

**Comment by honggyukim** [comment]
Thanks a lot. But I get some error messages when I run the command you gave as follows.

At terminal 1, prepare `deno` running `deno_tcp.ts`.
```
$ deno run --allow-net https://deno.land/x/deno@v1.3.1/tools/deno_tcp.ts
Listening on 127.0.0.1:4500
```
At terminal 2, create the load on the server.
```
$ wrk http://127.0.0.1:4500
Running 10s test @ http://127.0.0.1:4500
  2 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   465.39us    4.03ms  79.71ms   99.07%
    Req/Sec    35.28k     4.49k   38.66k    90.10%
  709011 requests in 10.10s, 34.48MB read
Requests/sec:  70198.05
Transfer/sec:      3.41MB
```
Then `deno` is terminated at terminal 1 as follows.
```
$ deno run --allow-net https://deno.land/x/deno@v1.3.1/tools/deno_tcp.ts
Listening on 127.0.0.1:4500
error: Uncaught ConnectionReset: Connection reset by peer (os error 54)
    at unwrapResponse (rt/10_dispatch_minimal.js:53:13)
    at sendAsync (rt/10_dispatch_minimal.js:96:12)
    at async read (rt/12_io.js:99:19)
    at async handle (https://deno.land/x/deno@v1.3.1/tools/deno_tcp.ts:15:17)
```
If this is the expected behavior, then I will generate a trace report with it. Thanks!

**Comment by ry** [comment]
That is expected behavior

**Comment by honggyukim** [comment]
@ry Sorry for the late reply. I've recorded and dumped the example above, but it seems that some background threads might not be captured so spent some time to investigate.

I've uploaded the dump output for both debug and release builds with `100us` time-filter, which means functions executed less than `100us` are discarded to reduce overhead and the data size.

**debug build**
chrome: https://uftrace.github.io/dump/deno_tcp.debug.100us.html
flamegraph: https://uftrace.github.io/dump/deno_tcp.debug.100us.svg

**release build**
chrome: https://uftrace.github.io/dump/deno_tcp.release.100us.html
flamegraph: https://uftrace.github.io/dump/deno_tcp.release.100us.svg

Please note that release build output has less info because some function calls are not captured when they are inlined.

Could you please have a look and confirm if deno engine runs `deno_tcp.ts` example with only a single thread? Otherwise, it would be helpful if you can explain how deno internally creates and manages processes/threads.

FYI, uftrace follows only the target process and follows up the child processes/threads when
- the process is forked (with `fork()`)
- the process creates a pthread (with `pthread_create()`)
- the process spawns itself (with `posix_spawn()`)

**Comment by honggyukim** [comment]
I expected the chrome trace output something like https://uftrace.github.io/dump/node-marked.html that shows multiple threads are running in a single timeline.

There might be some difference between node and deno process/thread creation.

**Comment by ry** [comment]
> Could you please have a look and confirm if deno engine runs deno_tcp.ts example with only a single thread? Otherwise, it would be helpful if you can explain how deno internally creates and manages processes/threads.

The TCP server only runs in a single main thread - which is the one of interest to us. The other threads are V8's own internal profiler thread (and maybe more?)

The release flamegraph looks odd. I would expect to see some read/write syscalls as a large part of the profile...

**Comment by honggyukim** [comment]
> The TCP server only runs in a single main thread - which is the one of interest to us. The other threads are V8's own internal profiler thread (and maybe more?)

Thanks for the confirmation. V8 creates some worker threads but we have to recompile V8 with `-pg` option as well to see the trace result for both deno and V8 in a single timeline.

> The release flamegraph looks odd. I would expect to see some read/write syscalls as a large part of the profile...

Hmm.. I'm not sure about it. We may have to compare the profiling result with other tools.

**Comment by namhyung** [comment]
I'm not familair with Rust nor deno, but looking at the flamegraphs I can see it spent most of the time during `poll` operation which looks reasonable for servers.

**Comment by namhyung** [comment]
@ry About your dtrace comment: no it's not a wrapper of dtrace - uftrace was written from scratch and we try to avoid adding external dependencies for its core functionality.
