### ISSUE TITLE
Invalid Executable Name

### ISSUE THREAD

**Issue by ebebbington** [denoland/deno#7221]
See [here](https://github.com/drashland/dmm/issues/61) for reference, where this problem originated from.

I can also re-produce the error.

**What is the Problem**
Getting a `invalid executable name` when installing a module

**What is Expected**
Can install the module

**How to Reproduce**
1. run: `deno install --allow-net --allow-read --allow-write https://deno.land/x/dmm@v1.1.5/mod.ts`
2. see error: `invalid executable name: dmm@v1.1.5`
3. pass in the `--name` flag, and it works. Although in the above link, someone is unable to install even when using the `--name`

**Comment by BunnyTheLifeguard** [comment]
The one mentioned in 3. is me. I'm on Deno 1.3.1 and if I try to install dmm even with the name flag the following error occurs on my system (Manjaro Linux 20.1):

```
$ deno install -f --allow-net --allow-read --allow-write --name dmm https://deno.land/x/dmm@v1.1.5/mod.ts
Download https://deno.land/x/dmm@v1.1.5/mod.ts
Compile https://deno.land/x/dmm@v1.1.5/mod.ts
Download https://deno.land/x/dmm@v1.1.5/deps.ts
Download https://deno.land/x/dmm@v1.1.5/src/options/help.ts
Download https://deno.land/x/dmm@v1.1.5/src/options/version.ts
Download https://deno.land/x/dmm@v1.1.5/src/commands/info.ts
Download https://deno.land/x/dmm@v1.1.5/src/commands/check.ts
Download https://deno.land/x/dmm@v1.1.5/src/commands/update.ts
Download https://deno.land/std@0.65.0/fmt/colors.ts
Download https://deno.land/std@0.65.0/testing/asserts.ts
Download https://deno.land/std@0.65.0/testing/diff.ts
Download https://deno.land/x/dmm@v1.1.5/src/services/deno_service.ts
Download https://deno.land/x/dmm@v1.1.5/src/interfaces/module.ts
Download https://deno.land/x/dmm@v1.1.5/src/services/module_service.ts
error: TS2345 [ERROR]: Argument of type '{ depth: number; sorted: boolean; trailingComma: boolean; compact: boolean; iterableLimit: number; }' is not assignable to parameter of type 'InspectOptions'.
  Object literal may only specify known properties, and 'sorted' does not exist in type 'InspectOptions'.
      sorted: true,
      ~~~~~~~~~~~~
    at https://deno.land/std@0.65.0/testing/asserts.ts:26:7
```

**Comment by lucacasonato** [comment]
> I'm on Deno 1.3.1 and if I try to install dmm even with the --name flag the following error occurs on my system (Manjaro Linux 20.1):

Can not reproduce with Deno 1.3.1 on Ubuntu 20.04.

**Comment by nayeemrmn** [comment]
We should improve the name inference by stripping any `@*` suffix. The fact that `@` is already an invalid character makes this simple.

@BunnyTheLifeguard `deno upgrade`.

**Comment by BunnyTheLifeguard** [comment]
> We should improve the name inference by stripping any `@*` suffix. The fact that `@` is already an invalid character makes this simple.
> 
> @BunnyTheLifeguard `deno upgrade`.

Rip, now we know. My global installation of deno was 1.3.1, the one in the vscode project was still on 1.0.0 🥴
The normal installation still resultes in the `error: Invalid executable name: dmm@v1.1.5` tho.
With the `--name` flag and Deno on 1.3.1 in the project folder it is working like @ebebbington said.

**Comment by ebebbington** [comment]
Related to the original issue of "Invalid Executable Name", i can see removing the tag does work: `deno install -f -A https://deno.land/x/dmm/mod.ts` - haven't tried with other installable modules though, only dmm
