### ISSUE TITLE
WebSockets fail due to missing pong

### ISSUE THREAD

**Issue by mschwartz** [denoland/deno#7231]
https://github.com/ryo-ma/deno-websocket/issues/5#issuecomment-682590648

See issue in the WebSocket repository.

**Comment by ribizli** [comment]
The original error tells `Client MUST mask all frames (RFC-6455: Section 5.1)`.

https://deno.land/std@0.68.0/ws/mod.ts#L272-L279

The code above missing the mask from the frame, I guess this could be the issue.

**Comment by bartlomieju** [comment]
`WebSocket` client landed in #7051 which will be available in `1.4.0` on Sunday. We've also deprecated client in `std/ws/`.

**Comment by bartlomieju** [comment]
I think this issue is no longer relevant given `WebSocket` API.
