### ISSUE TITLE
Remove Deno.SymlinkOptions

### ISSUE THREAD

**Issue by caspervonb** [denoland/deno#7234]
Currently we expose Deno.SymlinkOptions which just a leak of an internal implementation for Windows.
I propose we remove it while the ops using it are still unstable.

Also, seems we have zero coverage for it so who knows if it works.

**Comment by piscisaureus** [comment]
Nope

**Comment by piscisaureus** [comment]
Nope

**Comment by piscisaureus** [comment]
Nope
