### ISSUE TITLE
--lock-write should lock-check pre-existing deps by default

### ISSUE THREAD

**Issue by nayeemrmn** [denoland/deno#7237]
The behaviour of `--lock-write` is to rewrite the lock file without checking against the existing one. This is problematic in the edge case that you're calling `--lock-write` to add a new dependency but you hadn't yet downloaded the pre-existing dependencies, it turns out that their content has changed, and their hashes are overwritten without you realising. The existing hashes should be checked against before any writing.

**Comment by bartlomieju** [comment]
@nayeemrmn what do you mean by "delete old deps"? I'm working on a proposal for new lock file format and functionality, eg. lock file should be discovered by default similar to `Cargo.lock`.

`--lock-write` is already quite cumbersome and adding `--update` and `--append` as values would be even less user friendly to use.

**Comment by nayeemrmn** [comment]
I included a lot of convoluted things in the issue description, it's now reduced to just the (niche) security issue mentioned in the title.

> I'm working on a proposal for new lock file format and functionality, eg. lock file should be discovered by default similar to `Cargo.lock`.

I'm strongly in favour of this and have proposed it in the past. Yes this issue would most likely be fixed as a side-effect.

I think users should be able to do `touch deno.lock` to opt into locking for their project. Deno upon any invocation will scan upwards from CWD for a directory with `deno.lock` in it and apply lock checking / writing using that file if and only if it finds one.   This makes locking very easy to opt into, while for regular usage no lock file is automatically created in the current dir if you choose not to, unlike `package-lock.json`.

**Comment by ry** [comment]
> I think users should be able to do touch deno.lock to opt into locking for their project. Deno upon any invocation will scan upwards from the entrypoint module location for a directory with deno.lock in it and apply lock checking / writing using that file if and only if it finds one. This makes locking very easy to opt into, while for regular usage no lock file is automatically created in the current dir if you choose not to, unlike package-lock.json.

That's an interesting and reasonable suggestion.

The idea I've been toying with is that we're likely going to introduce a configuration file for Deno. I was thinking that the lock files could be written automatically if the config file was present in the cwd.

**Comment by bartlomieju** [comment]
One aspect I still haven't figured out is how do we handle dynamic imports - currently if you have `--lock-write` flag then dynamic imports will end up in the lock file. This gets slightly harder if lock file is to be written automatically - either we just always update lockfile with dynamic imports or require a separate flag. 

This actually relates to the issue at hand - checking already locked deps before writing new ones. In case of Cargo this happens automatically - ie. if you add a new dependency the old ones are checked against `Cargo.lock` and new one are automatically added.

For the sake of simplicity and user friendliness I think we should:
a) if lockfile doesn't exist always create it
b) if lockfile exists validate dependencies against it
c) if a new dependency is added and lockfile exists verify already locked dependencies and add new one
Point b) and c) would always be applied for dynamic imports.

> This makes locking very easy to opt into, while for regular usage no lock file is automatically created in the current dir if you choose not to, unlike package-lock.json.

IMO this contradicts the easiness aspect a bit - you'd still have to create/touch file manually before it would be filled, which means most users will not do that (or forget to do that). Maybe locking should be an opt out operation?

> Deno upon any invocation will scan upwards from the entrypoint module location for a directory with deno.lock in it and apply lock checking / writing using that file if and only if it finds one.

This is another thing we need to discuss in depth - should we walk upwards from entrypoint/CWD up to the root, or should we expect the lock file be placed next to entrypoint (or configuration file @ry's suggesting).

**Comment by nayeemrmn** [comment]
> For the sake of simplicity and user friendliness I think we should:
> a) if lockfile doesn't exist always create it

> IMO this contradicts the easiness aspect a bit - you'd still have to create/touch file manually before it would be filled, which means most users will not do that (or forget to do that). Maybe locking should be an opt out operation?

The thing is that the other tools this logic is taken from have separate package managers and executors, with Deno this means a file is created in the current dir if ever you `deno run` something with a remote module in the graph. This would make me always think twice before calling `deno run` in a random dir, and check that I didn't leave any rubbish afterwards. It's also not clear what would happen with `deno install`ed scripts. It's true my proposal would make it opt-in, but IMO it has to be with a tool like Deno and having to `touch` a file at the project root is a minimal mechanism for this.

> This is another thing we need to discuss in depth - should we walk upwards from **entrypoint/CWD** up to the root

(Tangential, but I want to clarify.) Between these two it should be upwards from the entrypoint location and not CWD. There is the problem of identifying whether or not the code being run is "part of the project" or the user running some unshared script, this is a good way of distinguishing the two cases. Node does the same when checking what project scope to apply, it looks at the entrypoint location and not CWD.

> or should we expect the lock file be placed next to entrypoint

This doesn't accommodate multiple entrypoints and testing, and is generally less precedented probably for this reason.

> (or configuration file @ry's suggesting).

I wonder if we should keep lock files and other configuration decoupled. I'd want to be able to opt into one and not the other. It's also kind of unintuitive because this configuration file wouldn't be a dependency manifest unlike with other tools.

**Comment by bartlomieju** [comment]
> > For the sake of simplicity and user friendliness I think we should:
> > a) if lockfile doesn't exist always create it
> 
> > IMO this contradicts the easiness aspect a bit - you'd still have to create/touch file manually before it would be filled, which means most users will not do that (or forget to do that). Maybe locking should be an opt out operation?
> 
> The thing is that the other tools this logic is taken from have separate package managers and executors, with Deno this means a file is created in the current dir if ever you `deno run` something with a remote module in the graph. This would make me always think twice before calling `deno run` in a random dir, and check that I didn't leave any rubbish afterwards. It's also not clear what would happen with `deno install`ed scripts. It's true my proposal would make it opt-in, but IMO it has to be with a tool like Deno and having to `touch` a file at the project root is a minimal mechanism for this.

That's a good point - ideally in that case we'd use the lock file for that entry point (potentially remote lockfile). Still I believe if you have to opt-in into lockfile then it will make a lot of people skip it. Maybe it should only be automatically created for local entry points?

> > This is another thing we need to discuss in depth - should we walk upwards from **entrypoint/CWD** up to the root
> 
> (Tangential, but I want to clarify.) Between these two it should be upwards from the entrypoint location and not CWD. There is the problem of identifying whether or not the code being run is "part of the project" or the user running some unshared script, this is a good way of distinguishing the two cases. Node does the same when checking what project scope to apply, it looks at the entrypoint location and not CWD.
> 

You're right, it should be searching from entry point not CWD.

> > or should we expect the lock file be placed next to entrypoint
> 
> This doesn't accommodate multiple entrypoints and testing, and is generally less precedented probably for this reason.
> 

Not sure what you mean here - I think a single lockfile could be shared by multiple entry points, isn't that what Node does?

> > (or configuration file @ry's suggesting).
> 
> I wonder if we should keep lock files and other configuration decoupled. I'd want to be able to opt into one and not the other. It's also kind of unintuitive because this configuration file wouldn't be a dependency manifest unlike with other tools.

Yes, definitely - Deno should always work without config file (if we introduce one) so lockfile shouldn't ever depend on anything besides the entrypoint.

**Comment by nayeemrmn** [comment]
> > > or should we expect the lock file be placed next to entrypoint
> > 
> > 
> > This doesn't accommodate multiple entrypoints and testing, and is generally less precedented probably for this reason.
> 
> Not sure what you mean here - I think a single lockfile could be shared by multiple entry points, isn't that what Node does?

If the lock file must be a sibling of the entrypoint without any upwards scanning, it wouldn't be shared with secondary entrypoints in subdirs. And for `deno test`, "entrypoint" can mean any module with tests in it.

**Comment by bartlomieju** [comment]
> If the lock file must be a sibling of the entrypoint without any upwards scanning, it wouldn't be shared with secondary entrypoints in subdirs. And for deno test, "entrypoint" can mean any module with tests in it.

Good point, thanks.

**Comment by lucacasonato** [comment]
`--lock-write` is now gone.
