### ISSUE TITLE
cargo install deno error

### ISSUE THREAD

**Issue by carpRed** [denoland/deno#7249]
Compiling swc_ecma_transforms_macros v0.1.0
   Compiling swc_ecma_codegen_macros v0.5.0
   Compiling darling v0.10.2
   Compiling tokio v0.2.22
   Compiling ast_node v0.7.0
   Compiling thiserror v1.0.20
   Compiling which v4.0.2
   Compiling rusty_v8 v0.8.1
   Compiling tokio-util v0.3.1
   Compiling tokio-rustls v0.14.0
   Compiling tokio-rustls v0.13.1
   Compiling swc_visit v0.2.0
   Compiling swc_visit v0.1.1
error: could not find native static library `rusty_v8`, perhaps an -L flag is missing?

error: aborting due to previous error

error: could not compile `rusty_v8`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `deno v1.3.1`, intermediate artifacts can be found at `C:\Users\user\AppData\Local\Temp\cargo-installM87hIE`

Caused by:
  build failed

**Comment by lucacasonato** [comment]
Does your environment match these prerequisites: https://deno.land/manual/contributing/building_from_source#prerequisites?

**Comment by carpRed** [comment]
@lucacasonato thanks , different from what i thought

**Comment by bartlomieju** [comment]
Fixed in v1.3.3
