### ISSUE TITLE
WebAssembly.instantiateStreaming does not work with Response

### ISSUE THREAD

**Issue by hazae41** [denoland/deno#7259]
https://github.com/hazae41/denoflate/issues/1

Since Deno 1.3.1, WebAssembly.instanciateStreaming throws the following error when module is an instance of Response (from fetch)

> error: Uncaught TypeError: WebAssembly.compile(): Argument 0 must be a buffer source

**Comment by lucacasonato** [comment]
@caspervonb do we have a test for this?

**Comment by caspervonb** [comment]
> @caspervonb do we have a test for this?

Hmm, apparently I used a buffer source in the test when I enabled that flag 🤔

**Comment by hazae41** [comment]
@caspervonb Do we need to temporarily disable instantiateStreaming? Or implement it with Response?

Because modules using Response are broken since they check for the existence of instantiateStreaming before 

```typescript
if (WebAssembly.instantiateStreaming) {
  // use instantiateStreaming()
} else {
  // get the buffer then use instantiate()
}
```

**Comment by caspervonb** [comment]
> Because modules using Response are broken since they check for the existence of instantiateStreaming before

Oh right, that's bad.. uhm, I'll get back to you.

**Comment by dsherret** [comment]
I'm able to make this work by doing `WebAssembly.instantiateStreaming(response.then(r => r.arrayBuffer()) as any)`

**Comment by 00ff0000red** [comment]
Ahh, saw that Deno had WebAssenbly.{compileStreaming, instantiateStreaming}, and thought that it would be fun to try to instantiate ~6 wasm files and set up a project. Then some particularly misleading errors appeared :)

In my opinion, If it doesn't work correctly, it should not be exposed at all. Can we get the PR that caused this to be reverted until this is properly sorted out?

**Comment by vovacodes** [comment]
Hey folks, is there any progress here? I'd like to use Deno for testing my wasm compiled from Rust with `wasm-bindgen` but unfortunately, due to this issue Deno chokes on it. I don't control the JS wrapper that calls to `WebAssembly.instantiateStreaming` (that one is generated by `wasm-pack`) and even though it does feature detection, that one is broken too (https://github.com/denoland/deno/pull/8968), so it's kinda a blocker.

**Comment by lucacasonato** [comment]
Temporary workaround could be to call `delete WebAssembly.instantiateStreaming;` before instantiating the `wasm-pack` code.
