### ISSUE TITLE
ensure Option in WriteFileOptions

### ISSUE THREAD

**Issue by timreichen** [denoland/deno#7262]
To ensure a file can be created without an error of a dir not existing, we have to call `fs.ensureFile` before write:
```ts
await ensureFile(filePath)
await Deno.writeTextFile(filePath, content)
```
What would you think of an `ensure` option for `Deno.writeTextFile` `Deno.writeTextFileSync` and `Deno.writeFile`  `Deno.writeFileSync` likewise?

```ts
await Deno.writeTextFile(filePath, content, { ensure: true })
```

For directories: `Deno.mkdir` basically has that functionality built in with the `recursive` option.

**Comment by caspervonb** [comment]
We already have this in std/fs.

Deno ops should stay as close to the syscalls as possible IMHO.
