### ISSUE TITLE
Suggestion(std/examples): relocate

### ISSUE THREAD

**Issue by timreichen** [denoland/deno#7278]
It seems a bit odd to me to have an extra std/examples directory when each std module has own examples in readme or tests. Would it make sense to remove `std/examples` and make an example folder in std modules to contain example files?

**Comment by bartlomieju** [comment]
Actually those examples were scattered all over `std/` and we moved them into single directory before 1.0 release. IMO current setup is preferable as `exmaples` directory easily visible compared to grepping through each directory in `std/`.

**Comment by timreichen** [comment]
@bartlomieju  Ok, I get your point of view. But I also find it a very confusing structure at the moment.
1. because `example` is not really a feature module like the others but a collection of examples. Why does it have to be in std and not in in /x for example?
2. there is a `test.ts` file which in any other std module is the Deno.test file. In example it is an example file on how to use tests. And for tests themselves it has a `test` directory that contains all test files.

I am just a little worried about std consistency.

**Comment by timreichen** [comment]
After some more research I guess the std file structure is not the best at the moment in general. I think we could do better before std 1.0. Going to open a separate issue.

**Comment by timreichen** [comment]
Would it make sense for deno to have an `examples` repo where the current `std/examples` files would be located? That would cleanup `std`.
