### ISSUE TITLE
Support compiler hints during export

### ISSUE THREAD

**Issue by jsejcksn** [denoland/deno#7281]
Ref: https://deno.land/manual/getting_started/typescript#compiler-hint

Would it be possible to support the pattern of providing compiler hints during export? That way, they could be added to `deps.ts` once and could be used in any files without further annotation.

So, instead of this:

`main.ts`:
```ts
// @deno-types="./foo.d.ts"
import * as foo from "./foo.js";
```

Something like this:

`deps.ts`:
```ts
// @deno-types="./foo.d.ts"
export * as foo from "./foo.js";
```

`main.ts`:
```ts
import {foo} from "./deps.ts";
```

**Comment by kitsonk** [comment]
That seems like a valid and reasonable feature request.

**Comment by bartlomieju** [comment]
Note: all information needed to support this feature is already there, ie. the reference is extracted from AST and downloaded - it's just that compiler doesn't utilize those hints during type checking.

**Comment by jsejcksn** [comment]
This seems to be working in v`1.5.4`. Has it been been incorporated into the compiler, intentionally or otherwise?

**Comment by jsejcksn** [comment]
Can anyone report on the current status at this point in time?

**Comment by bartlomieju** [comment]
I believe this is now supported, but I'd like @dsherret to confirm.

**Comment by lucacasonato** [comment]
This is now working.

![image](https://github.com/user-attachments/assets/49edc5bb-eb57-4fa4-a6ac-93a62f6ff338)
