### ISSUE TITLE
Formatting misalignment on `console.table(Deno)`

### ISSUE THREAD

**Issue by humancalico** [denoland/deno#7294]
**version**: 1.3.2
![console-table-deno](https://user-images.githubusercontent.com/51334444/91774468-7b406c80-ec06-11ea-86e4-b262c762dfb9.png)

**Comment by ry** [comment]
I think console.table doesn't support very wide tables. I'm not sure it's actually broken...

**Comment by nayeemrmn** [comment]
Yes, just checked that Node also doesn't do any special readable wrapping based on terminal size. I think this is a wontfix.
