### ISSUE TITLE
Make dates in Deno.futime and Deno.utime optional

### ISSUE THREAD

**Issue by caspervonb** [denoland/deno#7300]
Currently it's not possible to only update atime or mtime with with Deno.futime or Deno.utime, both have to be provided.

This is an artificial limitation imposed by the JavaScript API that we can easily remove.

**Comment by caspervonb** [comment]
I already have a patch for this as it's blocking, I just need to write tests for it 😅

**Comment by mustafapc19** [comment]
No problem :)

**Comment by caspervonb** [comment]
Also keep in mind that this hasn't been triaged by anyone yet 😉

After thinking about this for a bit more, I'm going to push towards getting utime(2) syscalls deprecated in favor of utimes(2) variants to deal with some peculiarities of the implementation.
