### ISSUE TITLE
stdout output limited with 16384 symbols

### ISSUE THREAD

**Issue by zored** [denoland/deno#7302]
I run this code:
```typescript
await Deno.stdout.write(new TextEncoder().encode('v'.repeat(20000)))
```
I expect 20000 `v` symbols. But I get 16384 of them.

This code worked previously. Is something different now? 😃 

[Here is example Gist](https://gist.github.com/zored/be7481c7b450685f45ec812c14bbd87c).

**Comment by bartlomieju** [comment]
Use `await Deno.writeAll(Deno.stdout, new TextEncoder().encode('v'.repeat(20000))`

[`Deno.write`](https://doc.deno.land/builtin/stable#Deno.write) does not guarantee to write whole buffer in a single call. 

[`Deno.writeAll`](https://doc.deno.land/builtin/stable#Deno.writeAll) does.

**Comment by caspervonb** [comment]
For reference, this is because Deno.write is effectively just write(2) https://linux.die.net/man/2/write
