### ISSUE TITLE
discussion: introduce a --future flag for non experimental 2.0 changes

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#7306]
This would be used to enable breaking changes (like adding `"isolatedModules": true` to our default TS config) before the next major. Anything behind `--future` would be unflagged for the next major release (v2.0.0).

The difference between this and `--unstable` is that these changes are stable, not experimental, they can just not be released right now because they would violate semantic versioning.

---

This has been done before in other projects. Example: Tailwind CSS has a `future` option in the config which you can use to opt into breaking 2.0 changes: https://tailwindcss.com/docs/upcoming-changes

**Comment by kitsonk** [comment]
Our question our discipline in our ability to not make changes to `--future`, but yeah, I get the point that there are certain.  I would prefer `--experimental` for things we are 99% convinced are fully done but need that feedback and are unsure when we will promote them.

Either way, we should keep it to as few flags as possible... not doing things like `--future-isolated-modules` or whatever, as it dramatically increases the need of good testing.

**Comment by ry** [comment]
I don't want to introduce more flags. Closed in favor of https://github.com/denoland/deno/issues/7326.
