### ISSUE TITLE
Plans for nonstandard fetch features?

### ISSUE THREAD

**Issue by mrkurt** [denoland/deno#7307]
We're trying to use Deno for a bunch of HTTP proxy projects, which means we need a lot that `fetch` standard doesn't provide. Deno unstable has an `HttpClient` that seems like a nice way of encapsulating things-fetch-can't-do.

I submitted a PR to add HTTP timeouts to the client in #7188, but it was not merged because it's not standard (despite the HTTP client also being not standard).

So the question is, is the HTTP client going to go away? Or, alternatively, where's the best place to build features for client certificates, HTTP connection pools, and (possibly) tcp timeouts to get future PRs accepted?

**Comment by ry** [comment]
HttpClient indeed seems like the right place to put functionality that doesn't exist in the fetch standard. We  just want to avoid extensions to the API which overlap with functionality in the standard.

**Comment by lucacasonato** [comment]
#7188 was not merged because timeouts are something that can be fully done with the standard `AbortController`. For features that do not make sense on the web (custom root ca certificates, mutual tls, connection pools) we can use `Deno.HttpClient`. But for all use cases that we can make happen with the web standard API, should not add proprietary options.

**Comment by mrkurt** [comment]
Would you consider connect/read timeouts as overlapping with AbortController or would those make sense on the HTTP client?

**Comment by lucacasonato** [comment]
I would consider them to overlap, because I think `AbortController` should be able to abort the fetch whatever state it is in (connecting, sending headers, waiting for headers, reading body, sending body).

**Comment by mrkurt** [comment]
@lucacasonato part of the problem there is that there's no way within the JS runtime to detect how long it takes to get the next bit of a data from a connection. Maybe part of the answer is exposing the connection fetch is using itself, and then figuring out how to implement connect/read/write timeouts at the TCP level.

**Comment by nayeemrmn** [comment]
Tangential to what's being discussed here, but my vision for non-standard options (using `Deno.HttpClient` and #6868 as an example) is:
```ts
const client = createHttpClient();
await fetch(
  "https://example.com/",
  {
    headers: new Headers({ "Accept": "text/html" }),
    [Deno.extension]: {
      client,
      headers: new Headers({ "Cookie": "foo=bar" }), // Forbidden headers.
    },
  },
);
```
I know `Deno.HttpClient` is compatible the way it is, but we wouldn't be able to do that if it happened to be a string field or something. It would pay off in the long term to have a consistent and plain-to-see convention for non-standard extensions.
