### ISSUE TITLE
Overload Deno.test with a variant that just takes a function

### ISSUE THREAD

**Issue by caspervonb** [denoland/deno#7310]
Not a fan of a bunch of overloads but feels like we're missing the most obvious basic overload.

```typescript
namespace Deno {
    export function test(fn: Function);
}
```

Where test name is dervived from fn.name.

**Comment by ry** [comment]
This was the original form of the test, but we removed it in (half-hearted) effort to align more closely with other JS testing libraries.

**Comment by nayeemrmn** [comment]
This was already removed in #4951.

**Comment by caspervonb** [comment]
> This was the original form of the test, but we removed it in (half-hearted) effort to align more closely with other JS testing systems.

> This was already removed in #4951.

Ah... closing then assuming no one is itching to bring it back.
