### ISSUE TITLE
Do you all have a a branching and release policy?

### ISSUE THREAD

**Issue by reselbob** [denoland/deno#7316]
I am doing an article on branching and release policies for the more popular open-source projects. Deno is a significant emerging project. Thus, my interest.

Tell me please, do you have have a branching and release policy/pattern that I can read? Or is it a matter of convention and tribal knowledge? If so, what is the policy/pattern?

Thanks in advance,
Bob Reselman

**Comment by kitsonk** [comment]
I don't think we will write it down, as it then becomes something more difficult to change.

Effectively it is "trunk based development" in the sense that we avoid long running branches if at all possible, with `master` being the branch that gets released when a release occurs.

Current release cadence in a path release weekly, on Friday, monthly minor releases, usually on the 13th.

**Comment by bartlomieju** [comment]
@kitsonk's description is completely accurate. Closing as resolved.
