### ISSUE TITLE
path: URL | string is under-documented and could be more user friendly

### ISSUE THREAD

**Issue by callionica** [denoland/deno#7320]
The built-in file functions in Deno (such as Deno.open) take a path parameter typed as URL | string.

What's not clear about this type of parameter is the following:
1. Can a URL object use a protocol other than file://?
2. Can a URL be passed as a string?
3. Can either URL or string be relative paths?
4. What format is expected of the string path when it's not a URL? (e.g. which direction do slashes go on Windows?)
5. What happens if the path/URL refers to a link of some kind? Is it the same behavior on all operating systems?
6. What about expansions?

Two changes might help.
1. If a user passes "file:///volume/path/file.ext" as a string, it would be nice if the functions just dealt with it
2. Instead of using URL and string, define more specific types and document the expectations on those types

**Comment by caspervonb** [comment]
> 1. Can a URL object use a protocol other than file://?

No

> 2. Can a URL be passed as a string?

No, because filepaths are strings and there is no way to distinguish if a string is supposed to be a url or path.

> 3. Can either URL or string be relative paths?

- There is no such thing as a relative file URL.

- Paths can be relative or absolute paths.

> 4. What format is expected of the string path when it's not a URL? (e.g. which direction do slashes go on Windows?)

Both delimiters are fine on Windows, but has to be consistent throughout the path.

> 5. What happens if the path/URL refers to a link of some kind? Is it the same behavior on all operating systems?

Symlinks need to be resolved explicitly.

> 6. What about expansions?

As in glob expansions? nope.

> If a user passes "file:///volume/path/file.ext" as a string, it would be nice if the functions just dealt with it

Impossible, "file:///volume/path/file.ext" is a valid filepath.

> Instead of using URL and string, define more specific types and document the expectations on those types

Specifically?

**Comment by callionica** [comment]
Thanks for the details, Casper.

Personally, I would use the string prefix "file://" to distinguish file URLs from paths. That certainly seems possible. I don't believe it would prevent you gaining access to any files, would it?

For the types:
type FileURL = URL
and
type FilePath = string
might do the trick.

It's just a way of giving you a single place to add documentation instead of having to provide the details on every function.

The point being that people who might choose Deno as a cross-platform tool for dealing with files are going to want to know the basics of how file paths and URLs are handled, so it should be documented somewhere. My suggestion is to tie the documentation to specific types that explain what's going on.

**Comment by caspervonb** [comment]
> Personally, I would use the string prefix "file://" to distinguish file URLs from paths. That certainly seems possible. I don't believe it would prevent you gaining access to any files, would it?

mkdir -p file://foo/bar/ext 😉 

The two concepts do clash without type checks unfortunately.

> The point being that people who might choose Deno as a cross-platform tool for dealing with files are going to want to know the basics of how file paths and URLs are handled, so it should be documented somewhere. My suggestion is to tie the documentation to specific types that explain what's going on.

Yeah documentation might be assuming too much intrinsic knowledge about what system calls things boil down to.

Generally speaking we haven't gotten in the habit of type aliasing describe concepts tho and I don't think we will but I'll defer to the maintainers on that.

**Comment by nayeemrmn** [comment]
I think all of those questions have obvious answers. They're either acquired knowledge about what a path/URL/Windows are or don't make sense. What would an expansion do? Maybe the fact that you can't provide a file URL as a string is worth writing somewhere.

**Comment by kitsonk** [comment]
> Maybe the fact that you can't provide a file URL as a string is worth writing somewhere.

Inline JSDoc comments are always welcome, as they feed the overall documentation.

**Comment by callionica** [comment]
Just a quick follow up regarding obviousness. It's not obvious to me whether you would or wouldn't actively prevent Windows-style separators, or whether you would or wouldn't do work to enable ~ as user home on multiple platforms in the name of cross-platform consistency. Users shouldn't have to guess about this stuff, nor write a bunch of tests to find out how it works currently (in the hope that the current implementation matches your long term direction). 

In terms of increasing engagement with your project, if someone suggests additional documentation, responding that it's unnecessary because it's obvious is not helpful to your long term goals. There are plenty of ways to "won't fix" suggestions like this that don't discourage participation.

**Comment by nayeemrmn** [comment]
@callionica Excuse me for lazily using the word "obvious", but you're deliberately making it sound like that's the only thing I said. I explained that it was acquired knowledge about pre-existing concepts not specific to Deno. As in, the paths are resolved by the OS or by the OS's rules as they are in any runtime. In my opinion, it's a fair assumption that Deno isn't doing anything special in between if no such thing is mentioned. Is that a helpful response to a doc suggestion?

**Comment by callionica** [comment]
I've reread my comments and I am happy with the feedback I have provided.

**Comment by kitsonk** [comment]
Again, accepting PRs for enhancing inline documentation for anything non-obvious.
