### ISSUE TITLE
TS parser dies on bigint literal in a type

### ISSUE THREAD

**Issue by solson** [denoland/deno#7321]
I found this issue while trying to import [a TypeScript library that uses a bigint literal in a type](https://github.com/dubzzz/fast-check/blob/533422fc3d87fcf84b300ae49f4a0e5ef5044b9f/src/check/arbitrary/FalsyArbitrary.ts#L24). I imported with `import fc from "https://cdn.skypack.dev/fast-check@2.2.1?dts";`, resulting in:

```
Download https://cdn.skypack.dev/new/pure-rand@v3.1.0/dist=es2020?from=fast-check
Download https://cdn.skypack.dev/-/fast-check@v2.2.1-P01vjCp4pLrQD4pLMvUp/dist=es2020,mode=types/lib/types/check/runner/configuration/Parameters.d.ts
Download https://cdn.skypack.dev/-/fast-check@v2.2.1-P01vjCp4pLrQD4pLMvUp/dist=es2020,mode=types/lib/types/check/arbitrary/BigIntArbitrary.d.ts
error: Unexpected token `bigint literal`. Expected an identifier, void, yield, null, await, break, a string literal, a numeric literal, true, false, `, -, import, this, typeof, {, [, ( at https://cdn.skypack.dev/-/fast-check@v2.2.1-P01vjCp4pLrQD4pLMvUp/dist=es2020,mode=types/lib/types/check/arbitrary/FalsyArbitrary.d.ts:15:4
```

More simply:

```console
$ deno eval -T '0n' # OK: bigint expressions
Check file:///home/scott/__$deno$eval.ts

$ deno eval -T 'let x : 0' # OK: numeric literals in types
Check file:///home/scott/__$deno$eval.ts

$ deno eval -T 'let x : 0n' # ERR: bigint literals in types are rejected
error: Unexpected token `bigint literal`. Expected an identifier, void, yield, null, await, break, a string literal, a numeric literal, true, false, `, -, import, this, typeof, {, [, ( at file:///home/scott/__$deno$eval.ts:1:8
```

This was tested on deno master @ 5db200b6abcf335b9caad94c4992aac8a04d6caf. I'm not sure if this should be reported on the swc parser itself, or what exactly the right fix might be, so I thought I'd come here first. (I'm no expert on TypeScript or the ES standards.)

**Comment by bartlomieju** [comment]
Most likely caused by the fact that `https://cdn.skypack.dev/fast-check@2.2.1?dts` is treated as JavaScript/TypeScript file instead of `Dts`. 

Ref #7168

**Comment by solson** [comment]
I don't think this problem is `.d.ts`-specific:

```console
$ cat foo.ts
let x : 0n;

$ tsc foo.ts

$ cat foo.js
var x;

$ deno run foo.ts
error: Unexpected token `bigint literal`. Expected an identifier, void, yield, null, await, break, a string literal, a numeric literal, true, false, `, -, import, this, typeof, {, [, ( at file:///home/scott/Projects/dotfiles/scripts/foo.ts:1:8
```

**Comment by bartlomieju** [comment]
CC @kdy1

**Comment by kdy1** [comment]
Let me see...
I found the root cause.
Currently the parser does not accept bigint lteral in the type position.

I'll see how it is parsed using ast explorer

**Comment by kdy1** [comment]
I published a new version.
