### ISSUE TITLE
Does Deno have a plan to support subtests?

### ISSUE THREAD

**Issue by saibing** [denoland/deno#7330]
Does Deno have a plan to support subtests as golang test?

[Using Subtests and Sub-benchmarks](https://blog.golang.org/subtests)

```go
func TestTime(t *testing.T) {
    testCases := []struct {
        gmt  string
        loc  string
        want string
    }{
        {"12:31", "Europe/Zuri", "13:31"},
        {"12:31", "America/New_York", "7:31"},
        {"08:08", "Australia/Sydney", "18:08"},
    }
    for _, tc := range testCases {
        t.Run(fmt.Sprintf("%s in %s", tc.gmt, tc.loc), func(t *testing.T) {
            loc, err := time.LoadLocation(tc.loc)
            if err != nil {
                t.Fatal("could not load location")
            }
            gmt, _ := time.Parse("15:04", tc.gmt)
            if got := gmt.In(loc).Format("15:04"); got != tc.want {
                t.Errorf("got %s; want %s", got, tc.want)
            }
        })
    }
}
```

**Comment by bartlomieju** [comment]
We've already had discussion about extending testing interface in https://github.com/denoland/deno/issues/4092 which lead to decision not to include such functionality. 

That said, more and more people ask for this feature, so we might want to reconsider our position on it. 

CC @ry

**Comment by balupton** [comment]
Is this for the rust and go code, or for the typescript code?

In userland, I will be porting https://github.com/bevry/kava to Deno with promise support soon.

**Comment by bartlomieju** [comment]
This is being actively discussed in https://github.com/denoland/deno/discussions/10771
