### ISSUE TITLE
Reading a file only works when I start deno in the script's directory 

### ISSUE THREAD

**Issue by bidoubiwa** [denoland/deno#7337]
Reading a file only works when I start deno in the script's directory 
```javascript
import { readJsonSync, existsSync } from "https://deno.land/std/fs/mod.ts";

console.log(existsSync("./small_movies.json"))
const json = readJsonSync("./small_movies.json");
```

This is my architecture : 
```
- demo
   - test_1.ts
```

When I use the following command from the `demo` directory
```bash
deno run --unstable --allow-read --allow-net test_1.ts
```
The scripts works as expected and output `true`.

If I run the script from the root directory like this:
```bash
cd ..
deno run --unstable --allow-read --allow-net demo/test_1.ts
```

I get the following error: 
```
false
Check file:///[...]/demo/test_1.ts
error: Uncaught NotFound: No such file or directory (os error 2)
    at unwrapResponse (rt/10_dispatch_json.js:24:13)
    at sendSync (rt/10_dispatch_json.js:51:12)
    at openSync (rt/30_files.js:31:17)
    at Object.readFileSync (rt/40_read_file.js:8:18)
    at readJsonSync (read_json.ts:21:39)
    at test_1.ts:3:14
```

**Comment by lucacasonato** [comment]
The fs methods are relative to the current working directory (cwd) - this is the folder from which you started the script. It is not relative to the path of the script. If you want your path to be relative to the script you can do `existsSync(new URL("./small_movies.json", import.meta.url))`.

[import.meta reference](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import.meta)

**Comment by bidoubiwa** [comment]
Hey! Thanks for the quick answer.

Nevertheless, `URL` is not a valid type for `string` and when logging `import.meta` in both situations I get the same result:

`demo` folder
```bash
➜  ✗ deno run --unstable --allow-read --allow-net test_1.ts
Check file:///[...]/project/demo/test_1.ts
{
  url: "file:///[...]/project/demo/test_1.ts",
  main: true
}
```
`root` folder
```bash
➜  ✗ deno run --unstable --allow-read --allow-net demo/test_1.ts
{
  url: "file:///[...]/project/demo/test_1.ts",
  main: true
}
error: Uncaught NotFound: No such file or directory (os error 2)
    at unwrapResponse (rt/10_dispatch_json.js:24:13)
    at sendSync (rt/10_dispatch_json.js:51:12)
    at openSync (rt/30_files.js:31:17)
    at Object.readFileSync (rt/40_read_file.js:8:18)
    at readJsonSync (read_json.ts:21:39)
    at test_1.ts:13:14

**Comment by bidoubiwa** [comment]
Thanks ! It works with the following code:

```javascript
import { readJsonSync } from "https://deno.land/std/fs/mod.ts";

const path = new URL("./small_movies.json", import.meta.url)
const json = readJsonSync(path.pathname);
```

**Comment by lucacasonato** [comment]
The version of std you are using seems to be very old - in current versions existsSync accepts a URL.

> logging import.meta in both situations I get the same result

That is the point - it gives you the module specifier of the module that called it.

Also try logging `Deno.cwd()` in both cases. This might clarify things.
