### ISSUE TITLE
Failure to install one or more dependencies due incompatibility with aarch64 android architecture

### ISSUE THREAD

**Issue by d3ck** [denoland/deno#7340]
The sys_info dependency package v0.7.0 is not compatible with the aarch64 android architecture. Perhaps there are more incompatible dependencies, but the installation fails from this point.

**Comment by ry** [comment]
@d3ck sys-info isn't a critical dependency - you could try just commenting out the various places it's used:
```
> rg sys_info cli/
cli/ops/os.rs
131:  match sys_info::loadavg() {
145:  let hostname = sys_info::hostname().unwrap_or_else(|_| "".to_string());
157:  let release = sys_info::os_release().unwrap_or_else(|_| "".to_string());
```
I'd be happy to remove those features (loadavg, hostname, os_release) if it meant that we could compile on aarch64 android.
