### ISSUE TITLE
deno fmt should format Markdown including code blocks

### ISSUE THREAD

**Issue by David-Else** [denoland/deno#7352]
At the moment Deno only formats JS and TS, but dprint can also format markdown including JS and TS code blocks:

https://github.com/denoland/deno/pull/6682#issue-445589767

This would be an awesome feature for documentation, is it possible to enable it? Then we can get rid of Prettier.

**Comment by bartlomieju** [comment]
I think @dsherret is working on it

**Comment by bartlomieju** [comment]
dprint has [`dprint-plugin-markdown`](https://github.com/dprint/dprint-plugin-markdown) which we could use for this purpose. I wonder if `dprint-plugin-typescript` could take an option to format markdown code blocks (which would make `dprint-plugin-markdown` its dependency?). @dsherret thoughts?

**Comment by dsherret** [comment]
@bartlomieju why would it be that way instead of the other way around?

Though kind of not documented well, `dprint-plugin-markdown` has API for formatting code in markdown code blocks (see the third parameter): https://docs.rs/dprint-plugin-markdown/0.4.1/dprint_plugin_markdown/fn.format_text.html

I need to make dprint-plugin-markdown MIT, which I will do soon.

**Comment by bartlomieju** [comment]
@dsherret thanks for pointing that out, indeed the other way around seems like a better option.

> I need to make dprint-plugin-markdown MIT, which I will do soon.

No rush :)

**Comment by dsherret** [comment]
@bartlomieju it's now MIT in 0.4.2.

**Comment by David-Else** [comment]
I see https://github.com/denoland/deno/commit/a1a806ae0cb132ac63cdf83543e45a958010aeb2 just landed in master :)

Can we use `deno fmt myfile1.md` and it also formats js/ts code blocks in the file?

**Comment by bartlomieju** [comment]
> I see [a1a806a](https://github.com/denoland/deno/commit/a1a806ae0cb132ac63cdf83543e45a958010aeb2) just landed in master :)
> 
> Can we use `deno fmt myfile1.md` and it also formats js/ts code blocks in the file?

@David-Else no, above commit changed only internal tooling used in repo, still need to implement it for `deno fmt`

**Comment by David-Else** [comment]
@bartlomieju I think you can remove the upstream label now?

**Comment by bartlomieju** [comment]
> @bartlomieju I think you can remove the `upstream` label now?

@David-Else sure I removed it and added appropriate labels

**Comment by David-Else** [comment]
@bartlomieju Thanks. 

The title is wrong for what I was requesting. Deno needs to format Markdown, that is `.md` files. That needs to include formatting code blocks inside that markdown.

There is no 'Markdown in code blocks'. The code blocks are in the Markdown. A better title would be `deno fmt should format Markdown including code blocks`. You might want to specify what types of code blocks are covered, JS and TS I assume.

**Comment by satyarohith** [comment]
I'll take a stab at it.
