### ISSUE TITLE
better std module file structure

### ISSUE THREAD

**Issue by timreichen** [denoland/deno#7353]
Coming from https://github.com/denoland/deno/issues/7278#issuecomment-687260874:

I think we should consider to restucture `std` modules for std 1.0 as there are inconsistencies present at the moment (see #7278).
There are several problems that can occur or already are occuring:
- file cluttering in toplevel
- file separation by purpose
  non-link files, test files, *feature* files are only distinguishable by name prependices (`_`) or appendices (`_test`)
- file misnaming or ambiguities

Suggestion for structural enhancement
- directory for tests
As present in std/examples at the moment, I really like the idea of a `tests` directory for all test files instead of `_test` appendices. That way files can have the same name as the file the tests are for (test file for `mod.ts` -> `tests/mod.ts`) and all tests are in one place for a better overview.
- directory for underscore files
Files that should not be linked to could be put in an `interal` (for the lack of better word) directory to clean the toplevel up.
- directory and *mod* files
Could be in a `mods` directory.

example: 

- std/http
  - internal
    - _io.ts
    - _mock_conn.ts
  - mods
    - cookie.ts
    - file_server.ts
    - http_bench.ts
    - http_status.ts
    - racing_server.ts
    - server.ts
  - mod.ts
  - readme.md
  - tests
    - _io.ts
    - cookie.ts
    - file_server.ts
    - racing_server.ts
    - testdata

This would solve the upper problems as well as giving a roust module structure that possibly could resonate with developers and be used in 3rd party modules.

What are your thoughts on this?

**Comment by nayeemrmn** [comment]
> * directory for tests
>   As present in std/examples at the moment, I really like the idea of a `tests` directory for all test files instead of `_test` appendices. That way files can have the same name as the file the tests are for (test file for `mod.ts` -> `tests/mod.ts`) and all tests are in one place for a better overview.

Disagree. The test modules should be side-by-side with the feature modules as much as possible. This is a common convention. Putting it in a `tests` directory and removing the suffix won't work with `deno test`'s file matcher. The current convention has already been thought-through and integrated into stable API.

> * directory for underscore files
>   Files that should not be linked to could be put in an `interal` (for the lack of better word) directory to clean the toplevel up.
> * directory and _mod_ files
>   Could be in a `mods` directory.

That's terrible... you're adding a `mods` path segment to every imported module for no reason.

A module being private doesn't affect how you want to maintain the source structure. It's not "clutter" to have them next to the public modules, unless you're talking about hiding them in the registry viewer which would be a valid issue. We just need _some_ pattern for them so we can say in the docs "modules names which match that pattern aren't stable". Again, `_foo.ts` is a common convention for this.

---

These structure decisions are deliberately written in the style guide and there's no good argument here against them, so let's just address the few inconsistencies like `std/examples/tests`.
