### ISSUE TITLE
Slight mismatch between crate::colors and rt/colors

### ISSUE THREAD

**Issue by caspervonb** [denoland/deno#7358]
Minor but seems that crate::colors use the bright variants where-as our rt utils use the regular colors.

![Screenshot 2020-09-04 at 12 58 01 PM](https://user-images.githubusercontent.com/157787/92292323-32165280-ef4f-11ea-8bdd-3a6c33a0cbe6.png)

**Comment by nayeemrmn** [comment]
Yep, you can see this in the yellow of runtime error stack frames vs type error stack frames 😓

**Comment by stmtk1** [comment]
What is bright variants and regular colors.

**Comment by caspervonb** [comment]
> What is bright variants and regular colors.

Escape sequence 40 through 49 (regular) and 100 through 109 (bright).
