### ISSUE TITLE
Slow TypeScript Incremental Compilation (Possible Bug)

### ISSUE THREAD

**Issue by Skillz4Killz** [denoland/deno#7371]
Hello 👋 

_Sorry for the long read, I wanted to provide as much details as possible_

Something I have noticed is an extremely slow compilation time when working in a relatively speaking large project. In my case, I had hundreds of TS files that needed to be compiled and ran. This took about 2-3 minutes on the first time, I started the process which isn't a big issue. The main headache/annoyance is when it still takes 2-3 minutes after that. When changing one minor file it would rebuild almost every single file again taking up another 2 minutes. Having to code when every small change in a file could trigger a 2-minute rebuild was not really plausible. It got annoying real fast. In comparison, I use TS the same within my node.js version where I have this working within second because when I code i use `tsc --watch` in a separate terminal. I believe the implementation of this is missing/lacking possibly.

This is an example of what happens. This is what I would like it to do. I change 1 file and this happens.

```ts
[02:39 PM] => "Beginning Bot Startup Process. This can take a little bit depending on your system. Loading now..."
Check file:///Users/gamer-deno/src/events/reactionAdd.ts#7
[02:39 PM] => "Loading Languages..."
[02:39 PM] => "Loading Database"
[02:39 PM] => "Loaded 16 Argument(s)"
[02:39 PM] => "Loaded 81 Command(s)"
[02:39 PM] => "Loaded 9 Event(s)"
[02:39 PM] => "Loaded 6 Inhibitor(s)"
[02:39 PM] => "Loaded 4 Monitor(s)"
[02:39 PM] => "Loaded 3 Task(s)"
[02:39 PM] => [TASK: botlists] Started.
[02:39 PM] => [TASK: botstats] Started.
[02:39 PM] => [TASK: collectors] Started.
[02:39 PM] => "Loading Cached Settings:"
[02:39 PM] => "[READY] Bot is online and ready in 2 guild(s)!"
```

This is an example of what happens that annoys me after just modifying 1 minor thing in 1 file. 1 file changed and this will happen.
```ts
[03:03 PM] => "Beginning Bot Startup Process. This can take a little bit depending on your system. Loading now..."
Check file:///Users/gamer-deno/src/constants/general.ts#0
Check file:///Users/gamer-deno/src/helpers/utils.ts#0
Check file:///Users/gamer-deno/src/constants/personalities.ts#0
Check file:///Users/gamer-deno/src/helpers/discord.ts#0
Check file:///Users/gamer-deno/src/constants/emojis.ts#0
Check file:///Users/gamer-deno/src/helpers/database.ts#0
Check file:///Users/gamer-deno/src/constants/time.ts#0
Check file:///Users/gamer-deno/src/helpers/reactions.ts#0
Check file:///Users/gamer-deno/src/helpers/collectors.ts#1
Check file:///Users/gamer-deno/src/commands/settings/language.ts#2
Check file:///Users/gamer-deno/src/commands/vip/analyze.ts#2
Check file:///Users/gamer-deno/src/commands/basic/ping.ts#2
Check file:///Users/gamer-deno/src/commands/fun/randomquote.ts#2
Check file:///Users/gamer-deno/src/commands/roles/unique/remove.ts#2
Check file:///Users/gamer-deno/src/commands/roles/roles.ts#2
Check file:///Users/gamer-deno/src/commands/mirrors/mirrors.ts#2
Check file:///Users/gamer-deno/src/commands/dev/ddb.ts#2

// Imagine a couple hundred of these now

Check file:///Users/gamer-deno/gamer-deno/src/arguments/command.ts#19
Check file:///Users/gamer-deno/gamer-deno/src/arguments/voicechannel.ts#19
[03:05 PM] => "Loading Languages..."
[03:05 PM] => "Loading Database"
[03:05 PM] => "Loaded 16 Argument(s)"
[03:05 PM] => "Loaded 81 Command(s)"
[03:05 PM] => "Loaded 9 Event(s)"
[03:05 PM] => "Loaded 6 Inhibitor(s)"
[03:05 PM] => "Loaded 4 Monitor(s)"
[03:05 PM] => "Loaded 3 Task(s)"
[03:05 PM] => [TASK: botlists] Started.
[03:05 PM] => [TASK: botstats] Started.
[03:05 PM] => [TASK: collectors] Started.
[03:05 PM] => "Loading Cached Settings:"
[03:05 PM] => "[READY] Bot is online and ready in 2 guild(s)!"
```

Note, that these imports are being dynamically imported using the following function. In case, this is a possible reason for the issue.
```ts
// Very important to make sure files are reloaded properly
let uniqueFilePathCounter = 0;
/** This function allows reading all files in a folder. Useful for loading/reloading commands, monitors etc */
export async function importDirectory(path: string) {
  const files = Deno.readDirSync(Deno.realPathSync(path));

  const directories: string[] = [];
  for (const file of files) {
    if (!file.name) continue;

    const currentPath = `${path}/${file.name}`;
    if (file.isFile) {
      await import(`file:///${currentPath}#${uniqueFilePathCounter}`);
      continue;
    }

    directories.push(currentPath);
  }

  // Wait untill all files are processed before processing folders. Important for nested subcommands
  for (const directory of directories) {
    importDirectory(directory);
  }

  uniqueFilePathCounter++;
}
```

So I realized that this would happen after modifying just one file, when I tried to change `types/helpers.ts` file and it caused it. This file is required in the mod.ts file, so perhaps when that happens it will rebuild mod.ts and mod.ts is used everywhere so when mod.ts is rebuilt, it basically rebuilds every file in my project. 

I would be more than happy to test any solutions you believe could solve this. This is a really problematic issue for me and all my modules users.

**Comment by ry** [comment]
Thanks for the detailed report. The extreme slowness is probably due to the dynamic import - but I’m not sure.

There’s nothing more frustrating than very slow incremental build steps. We need to figure this out.

**Comment by kitsonk** [comment]
Yeah. Each check file is a separate spin up of the TypeScript compiler. Thanks for the example, we clearly need to look into how we can properly form a more complete module graph and compile more of the program in one shot.

**Comment by bartlomieju** [comment]
> Thanks for the example, we clearly need to look into how we can properly form a more complete module graph and compile more of the program in one shot.

I don't think it's possible in the given example - all dynamic imports are done during runtime and we have no way of knowing that upfront. 

@Skillz4Killz are you loading directories in the same order? I think that `#${uniqueFilePathCounter}` suffix might cause cache busting (and hence not using `.tsbuildinfo` file for caching type-checking result) if order of iterated directories changes between the runs.

**Comment by Skillz4Killz** [comment]
@bartlomieju The order of the directories is not that important. 3 directories are loaded first 1 by 1 before the others are all done together.

![image](https://user-images.githubusercontent.com/23035000/92492214-1ade9b80-f1c1-11ea-87f6-94f2cff9197f.png)

The `#${uniqueFilePathCounter}` is extremely important for me as there is no other way to do "hot-reloading". Unless there is some alternative solution that re-compiles and re-executes files. As far as I know, there is no way to control/update the files that deno is going to run. There is also no way to control the compiler.

**Comment by kitsonk** [comment]
Yeah, I hadn't looked at the example code, if we can't determine the code statically, even dynamic imports, then we can't guess at what needs to be converted. The best we could do is try to see if they can be "batched" up per module, instead of being evaluated serially, or some sort of denounce logic to give us time to collect as many as possible.

The other thing I know we looked at one point was keeping the compiler running. Maybe if we hit a dynamic import like this, we keep the compiler spun up?

No matter what, this needs to likely be addressed, to whatever fashion after the other bits get rewritten.

**Comment by prcdpr** [comment]
I have also encountered that problem and my case is very similar. I have a directory with tens of .ts files that need to be imported at once. I don't care about particular order of import, just need to import the whole directory.

Allowing to import multiple scripts in batch quickly, for example by allowing to pass an array of paths to import function, would solve it for me.

I would also suggest to rename this issue to "slow dynamic import of multiple scripts" as it would better represent the real problem.

**Comment by Skillz4Killz** [comment]
I will close this issue as I have found a really good solution for this. 

1. Loop over the files and for each file create a string path for a static import
![image](https://user-images.githubusercontent.com/23035000/105229179-894d4600-5b31-11eb-9df0-509057dfb8cd.png)

2. Write all the files you wish to import into 1 file and just import that 1 file

![image](https://user-images.githubusercontent.com/23035000/105229201-923e1780-5b31-11eb-8f59-349807e45c62.png)

This dropped me from several minutes to a couple of seconds of load time.

Note: I am loading several hundred files so this is a pretty useful method for most users I'd imagine.

**Comment by kitsonk** [comment]
I'm still not satisfied with the way it works nkw, so let's reopen.

**Comment by bartlomieju** [comment]
@kitsonk do you still consider this issue not resolved?

**Comment by kitsonk** [comment]
I think there are other issues now that supersede this and there isn't anything specifically actionable here.
