### ISSUE TITLE
Do we need virtualenv feature just like python?

### ISSUE THREAD

**Issue by CGQAQ** [denoland/deno#7374]
Do we need virtualenv feature just like python? if so, I could try to implement it 

Add a `venv` subcommand to deno support something like 
* deno venv create
* deno venv remove
* etc.

### Generates a script 
1.  Set DENO_DIR to $venv/cache folder
1.  Set DENO_INSTALL_ROOT to $venv/bin folder
1.  Run deno in $venv folder

**Comment by tokiedokie** [comment]
similar issue #5214

I don't think deno itself needs a version system

**Comment by CGQAQ** [comment]
> similar issue #5214

The `venv` is more like a dependencies vendor to make a project self-contained

**Comment by tokiedokie** [comment]
python needs tools like `venv` because we can't specify the package version in code
but we must specify the module version in deno code
so I don't think deno needs tools like `venv`

**Comment by CGQAQ** [comment]
> python needs tools like `venv` because we can't specify the package version in code
> but we must specify the module version in deno code
> so I don't think deno needs tools like `venv`

`venv` just a convenient way to let a project self-contained (not use global deno-cache and global deno-executable, and also `deno install` will be installed inside venv), I think its a pretty neat feature to have. Of course, you can specify the package version in the Deno, but that's not the point

**Comment by hayd** [comment]
This can be a third party tool (and should be tested as such before it could be considered into deno itself).

**Comment by MarkTiedemann** [comment]
Here's a "virtual environment" implementation using make: https://github.com/MarkTiedemann/deno.mk

**Comment by kitsonk** [comment]
I don't see how `venv` would effectively differ from `deno bundle main.ts` in the sense that it contains a self contained, single module file without external dependencies.  I agree with @hayd that this is something that could/should be solved in the community and proven out and thanks for @MarkTiedemann for having such an approach.

**Comment by bartlomieju** [comment]
I agree with previous comments, such functionality could be a 3rd party tool.
