### ISSUE TITLE
acceptWebSocket doesn't support `Sec-WebSocket-Protocol`, preventing Chrome to connect

### ISSUE THREAD

**Issue by esquevin** [denoland/deno#7377]
Chrome refuses websocket connection if the header `Sec-WebSocket-Protocol` is set, because it's not returned by Deno.
> Error during WebSocket handshake: Sent non-empty 'Sec-WebSocket-Protocol' header but no response was received

MDN documentations specify that the server should return a header with the selected protocol in that case:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Protocol_upgrade_mechanism#:~:text=The%20Sec-WebSocket-Protocol%20header,header%20included%20in%20the%20response.

As far as I can see, there are no way to specify custom headers in `acceptWebSocket`

https://github.com/denoland/deno/issues/3539#issuecomment-643461959 reports the same issue

**Comment by MarkTiedemann** [comment]
I believe this was fixed in https://github.com/denoland/deno/pull/7051. Deno WebSockets are working for me in Chrome.

**Comment by bartlomieju** [comment]
Thanks for pointing this out @MarkTiedemann, closing as resolved.
