### ISSUE TITLE
Introduce a "NotCapable" error

### ISSUE THREAD

**Issue by caspervonb** [denoland/deno#7394]
Right now we do not differentiate between errors raised by our sandbox and actual permission errors raised by the operating system (altho you can visually distinguish them if you squint and scan carefully for errno 13 which is _EPERM_).

I think WASI does this better in that it distinguishes between _EPERM_ which is just errno EPERM and provides an additional extended errno enumeration member _ENOTCAPABLE_ which is raised when the caller is not capable (it's a capability based sandboxing model) of performing an operation.

The benefit of separating these is that NotCapable (name subject to bike-shedding) is potentially a recoverable state; you can ask for permissions where-as PermissionDenied is just defacto this is not allowed and won't be allowed without external intervention.

**Comment by caspervonb** [comment]
This would be a fairly fundamental breaking change; so it would have to be for a 2.0 milestone.

**Comment by caspervonb** [comment]
Still very much something I want to change for 2.0, tag as suggestion please.

**Comment by hazae41** [comment]
👍 Sounds like HTTP errors `Forbidden` and `Unauthorized`
