### ISSUE TITLE
various async fs ops are not actually async 

### ISSUE THREAD

**Issue by ry** [denoland/deno#7400]
Example op_fdatasync_async

https://github.com/denoland/deno/blob/11afd071aec2d5ea6eb37a934c0835d8f6b1e764/cli/ops/fs.rs#L285-L300

This ought to be calling `tokio::task::spawn_blocking`.

op_stat_async is properly implemented 
https://github.com/denoland/deno/blob/11afd071aec2d5ea6eb37a934c0835d8f6b1e764/cli/ops/fs.rs#L864-L886

**Comment by caspervonb** [comment]
> This ought to be calling tokio::task::spawn_blocking.

Hmm I know I made them fake async (as in, not calling tokio::fs variants which are available) but this looks unfamiliar 🤔

**Comment by caspervonb** [comment]
Bit of churn recently in ops; I'll revisit once the interface has been the same for a couple of days in a row ;)

**Comment by wperron** [comment]
I can take a crack at this one

**Comment by caspervonb** [comment]
Non trivial to fix at the moment until resource locks are sorted out.

**Comment by wperron** [comment]
I'll check around anyway, I spotted another op that had a todo comment saying it was a fake async op, maybe some of them are easy to fix, but thanks for pointing it out.

**Comment by caspervonb** [comment]
New resource table landed, so I'll get this done today.
