### ISSUE TITLE
consider borrowing the concept of "primordials" from Node

### ISSUE THREAD

**Issue by schwarzkopfb** [denoland/deno#7407]
I'm actively working on improving the compatibility layer with Node. I came up with the idea of implementing Node's concept of "primordials". Throughout my research on this issue, I found out that it could be useful outside the scope of `std/node`. For now I'm just going to start a conversation about integrating this into `std`.

Please take a look at [this](https://github.com/schwarzkopfb/typescript_primordials).

**Comment by bartlomieju** [comment]
Discussed yesterday with @ry and @bnoordhuis. This is something we want to do for `deno_core` and runtime code.

**Comment by bartlomieju** [comment]
Let's continue in https://github.com/denoland/deno/issues/10756
