### ISSUE TITLE
std/log library discards additional arguments by default

### ISSUE THREAD

**Issue by SirJosh3917** [denoland/deno#7418]
It seems that the additional arguments in the logger do not get written to the console. This behavior may be present in other loggers.

Sample code:
```ts
import * as log from "https://deno.land/std@0.68.0/log/mod.ts";

log.debug("Message", "Argument", 1234);
log.info("Message", "Argument", 1234);
log.warning("Message", "Argument", 1234);
log.error("Message", "Argument", 1234);
log.critical("Message", "Argument", 1234);
```

Output:
![image](https://user-images.githubusercontent.com/9854865/92822533-42d52700-f39a-11ea-9b0a-01f72fa30641.png)

This can be partially mitigated with a custom formatter for the logger, but I believe a similar functionality should be the default - the arguments shouldn't be discarded like how they are currently.
```ts
await log.setup({
  handlers: {
    console: new log.handlers.ConsoleHandler("DEBUG", {
      formatter: (record) => `[${record.levelName}] ${record.msg} ${record.args.join(" ")}`
    }),
  },
  loggers: {
    default: {
      level: "DEBUG",
      handlers: ["console"]
    }
  }
});
```

In addition, it would be nice if the console handler had the default logging foreground colors brighter since terminals are typically dark, and perhaps color coding the passed arguments (what `console.log` and friends already do) would be a nice touch too.

**Comment by sebastienfilion** [comment]
Most terminals have a way to define the value for blue, red, yellow, green, magenta and cyan - the logger only uses these token when displaying your text.

![Screen Shot 2020-09-10 at 8 00 28 PM](https://user-images.githubusercontent.com/1426491/92828271-d90c4b80-f3a0-11ea-93d5-01cdcda4f375.png)
