### ISSUE TITLE
Question: Does Deno has any limit on Workers?

### ISSUE THREAD

**Issue by ianchen0119** [denoland/deno#7419]
I know, In the Deno, Workers are essentially separate threads (multiple threads).
But I can't get more further details on Policy of Workers as following:

1) How many threads can be used at the same time in Deno?
2) How much maximum of memory can be allocated to every each threads?

Thanks.

**Comment by bartlomieju** [comment]
@ianchen0119 

1. There are no limits, you can create as many as you want
2. Again, there are no limits. We now have facilities to set heap limits on the isolate, but it's not possible to set them for workers.

**Comment by ianchen0119** [comment]
@bartlomieju 
Thanks for your fast reply.

**Comment by bartlomieju** [comment]
Closing as resolved.
