### ISSUE TITLE
[Feature Request] CLI option for REPL imports

### ISSUE THREAD

**Issue by solson** [denoland/deno#7425]
### Motivation

Being able to run `deno repl` with module imports would be very useful to me for experimenting with new libraries and for general desktop calculator use (by defining my own module of helper functions). This would be roughly equivalent to `node --require`.

It is currently difficult to import from the REPL, requiring hard-to-discover incantations like `let colors; import("https://deno.land/std@0.68.0/fmt/colors.ts").then((m) => colors = m)` which might allow you to observe `colors` being `undefined` if the import doesn't complete fast enough. Top-level await in the REPL would make this cleaner, but it would still not be easy to make a shell script or alias that invokes the REPL with pre-defined imports, since piping to `deno repl` makes it non-interactive. An explicit import flag can sidestep these problems.

### Design

We should add a new CLI option to `deno repl` tentatively called `-i, --import` which takes a list of `NAME=URL` pairs and makes the given modules available as if by `import * as NAME from "URL";`.

### Use cases

Example 1:

```console
$ deno repl -i hash=https://deno.land/std@0.68.0/hash/mod.ts
Download https://deno.land/std@0.68.0/hash/mod.ts
Download https://deno.land/std@0.68.0/hash/_wasm/hash.ts
Download https://deno.land/std@0.68.0/hash/hasher.ts
Download https://deno.land/std@0.68.0/hash/_wasm/wasm.js
Check https://deno.land/std@0.68.0/hash/mod.ts
Deno 1.3.3
exit using ctrl+d or close()
> { const h = hash.createHash("sha256"); h.update("hello world"); h.digest() }
Uint8Array(32) [
  185,  77,  39, 185, 147,  77,  62,
    8, 165,  46,  82, 215, 218, 125,
  171, 250, 196, 132, 239, 227, 122,
   83, 128, 238, 144, 136, 247, 172,
  226, 239, 205, 233
]
> { const h = hash.createHash("sha256"); h.update("hello world"); h.toString() }
b94d27b9934d3e08a52e52d7da7dabfac484efe37a5380ee9088f7ace2efcde9
```

Example 2:

```console
$ cat ~/scripts/calc.ts
import { createHash } from "https://deno.land/std@0.68.0/hash/mod.ts";

export function sha256(s: string): string {
  const h = createHash("sha256");
  h.update(s);
  return h.toString();
}

$ alias calc='deno repl -i calc=$HOME/scripts/calc.ts'

$ calc
Deno 1.3.3
exit using ctrl+d or close()
> calc.sha256("hello world")
b94d27b9934d3e08a52e52d7da7dabfac484efe37a5380ee9088f7ace2efcde9
```

### Open questions

1. **Permissions**: Right now, `deno repl` runs with all permissions enabled (like `deno run -A`), which seems unsafe as soon as we add imports. It would be good if we could change the default or opt-out of this behaviour and enable a minimal subset of permissions. It might be best to keep the current default, but detect the presence of `--import` and then disable all permissions that aren't explicitly enabled.
2. **Pre-evaluated snippets**: It may be useful if `deno repl` also accepted an `-e, --eval` flag for code to run between the imports and REPL start, allowing a use case like `deno repl -i calc=path/to/calc.ts -e 'const { sha256 } = calc'` (likely inside a shell alias, as above).
3. **Top-level await**: Having TLA in `deno repl` along with `--eval` could allow us to replace `-i` with `deno repl -e 'const { sha256 } = await import(URL)'`. REPL static imports would make it even cleaner. However, I think `-i NAME=URL` would remain a useful shorthand anyway.
4. **The eval subcommand**: It would be nice if `deno eval` accepted `--import` flags in the same way as `deno repl`. It's already possible to write `deno eval 'import { foo } from "URL"; console.log(foo("hello world"))'`, but it doesn't work with `deno eval -p` and it might be more convenient to test with `deno eval -i NAME=URL -p 'NAME.foo("hello world")'`. The same question about permissions for `deno repl` should be applied to `deno eval`.

### Implementation

I already have a working implementation of this at https://github.com/denoland/deno/pull/7427. There are a couple of implementation details I'd like to get advice on in the PR.

**Comment by dsherret** [comment]
I believe both the use cases shown here are now covered by import declarations being supported in the REPL (#10955).

I'm going to close this issue, but please let me know if you don't think this covers it. I believe import declarations in the repl is more preferable and discoverable than adding a CLI flag.


```
# use case 1
> deno repl
> import * as hash from "https://deno.land/std@0.68.0/hash/mod.ts";
> { const h = hash.createHash("sha256"); h.update("hello world"); h.digest() }

# use case 2
> deno repl
> import * as calc from "./scripts/calc.ts";
> calc.sha256("hello world")
```

**Comment by solson** [comment]
As far as I know, it's still not easy to define a shell alias that launches the Deno REPL with predefined imports. I would consider this need still unmet.

**Comment by dsherret** [comment]
@solson would a flag that runs a script or snippet of code immediately when launching the REPL make more sense than providing a list of defined imports? I think it would be more flexible. For example, similar to what you mentioned:

```ts
deno repl --eval "import * as calc from './scripts/calc.ts';"
```

I think #3173 would cover this?

**Comment by solson** [comment]
@dsherret Yeah, that would be ideal. Let's keep this closed in favour of that.
