### ISSUE TITLE
New Crate: wasm-bindgen-futures [Convert between Rust Futures to JS Promises]

### ISSUE THREAD

**Issue by brucod** [denoland/deno#743]
Your conversions between Rust Futures and JS Promises is probably mature, but thought I'd make you aware of this new crate owned by Rust team members Alex Crichton and Nick Fitzgerald, [wasm-bindgen-futures](https://crates.io/crates/wasm-bindgen-futures).  It might allow you to remove code so you don't duplicate work, or improve your existing.  

API Docs [here](https://rustwasm.github.io/wasm-bindgen/api/wasm_bindgen_futures/), GitHub Repo [here](https://github.com/rustwasm/wasm-bindgen/tree/master/crates/futures).

Crate description:

> This crate bridges the gap between a Rust Future and a JavaScript Promise. It provides two conversions:
> 
> 1. From a JavaScript Promise into a Rust Future.
> 2. From a Rust Future into a JavaScript Promise.

**Comment by bartlomieju** [comment]
@ry is this something you'd be interested in?

**Comment by ry** [comment]
It's on our radar @brucod - thanks. It's not something we're immediately going to do but as we try to benchmark and optimize our FFI, we try to use wasm-bindgen-futures, but for now we've got our own setup that works.
