### ISSUE TITLE
Simple example console.log(file) does not return the rid

### ISSUE THREAD

**Issue by tibi77** [denoland/deno#7444]
**First time Deno user. I am not sure if this behavior is intended.**

This code:
```
async function main() {
    console.table(Deno.resources());

    const file = await Deno.open('input.txt');

    console.log(file.rid);
    console.log(file);
    console.table(file);

    console.table(Deno.resources());
}  

main();

```

Prints: 
```
┌───────┬──────────┐
│ (idx) │  Values  │
├───────┼──────────┤
│   0   │ "stdin"  │
│   1   │ "stdout" │
│   2   │ "stderr" │
└───────┴──────────┘
3
File {}
┌───────┐
│ (idx) │
├───────┤
└───────┘
┌───────┬──────────┐
│ (idx) │  Values  │
├───────┼──────────┤
│   0   │ "stdin"  │
│   1   │ "stdout" │
│   2   │ "stderr" │
│   3   │ "fsFile" │
└───────┴──────────┘


```
The File class:
```
  export class File 
    implements
      Reader,
      ReaderSync,
      Writer,
      WriterSync,
      Seeker,
      SeekerSync,
      Closer {
    readonly rid: number;
    constructor(rid: number);
    write(p: Uint8Array): Promise<number>;
    writeSync(p: Uint8Array): number;
    read(p: Uint8Array): Promise<number | null>;
    readSync(p: Uint8Array): number | null;
    seek(offset: number, whence: SeekMode): Promise<number>;
    seekSync(offset: number, whence: SeekMode): number;
    close(): void;
  }

```

## Expected behavior
When `console.log` the `file` object the output should not be an empty object, rather a object containing the `rid`.
When `console.table` we should not have `idx` as a header.

**The file `input.txt` does exist. When I run on a non-existing file I get `Not found` error message.**

**Comment by solson** [comment]
I think this is because the `rid` property is set to `enumerable: false`:

```console
> Object.getOwnPropertyDescriptor(Deno.File.prototype, 'rid')
{ get: [Function: get rid], set: undefined, enumerable: false, configurable: true }
```

(See [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/getOwnPropertyDescriptor#Description) for details.)

**Comment by tibi77** [comment]
@solson so this is the desired behavior?

**Comment by solson** [comment]
I'm not sure that it was a conscious decision — it looks like it's coming from [this class definition](https://github.com/denoland/deno/blob/b3fa81f867f933df41f274bd8eec10dddf1b1b28/cli/rt/30_files.js#L71-L109), where it's just a regular `get rid()` property.

Also, I think I was wrong about `enumerable`. Even with `Object.defineProperty(File.prototype, 'rid', { enumerable: true })` it doesn't seem to show up in `console.log`/`console.table`. I'll defer to the people who know more about how this works.

**Comment by kitsonk** [comment]
What problem does the `.rid` not being enumerable cause?

**Comment by tibi77** [comment]
@kitsonk I find it harder to debug if the File object is printed just as an empty object.
