### ISSUE TITLE
std/datetime: day of year test fails in certain timezones

### ISSUE THREAD

**Issue by wperron** [denoland/deno#7447]
I'm in the east coast timezone and the `dayOfYear` test from std/datetime fails on the first assertion (aka it thinks January 1st 00:00 is December 31st). Changing the timezone on my machine fixes the issue.

**Comment by lucacasonato** [comment]
cc @timreichen

**Comment by wperron** [comment]
Did some digging, I _think_ it has to do with the fact that we use `getFullYear` instead of `getUTCFullYear` to compare the date with Jan 1st of the same year. I did some tests locally and that seemed to fix the problem, but I got stuck because the fix broke the tests for 400 BC

**Comment by timreichen** [comment]
I am on it. @wperron: you are right. `getUTCFullYear ` fixes the problem.
The 400 BC test is broken, because a zero is missing. `new Date("-00400-01-01")` gets parsed to year 400 instead of -400.  `new Date("-000400-01-01")`  works as expected.
PR #7466

**Comment by wperron** [comment]
@timreichen I noticed it that too actually, I figured if it was `-00400` it was probably right 😅 I should've just asked

**Comment by timreichen** [comment]
PR is merged. I think this issue can be closed.

**Comment by j4qfrost** [comment]
https://github.com/denoland/deno/pull/7726 this is a slightly more robust way of resolving the timezone issue.
