### ISSUE TITLE
The websocket API example in Deno 1.4 release post fails with "Cannot resolve module"

### ISSUE THREAD

**Issue by trivikr** [denoland/deno#7448]
First of all, congratulations on Deno v1.4 release! :tada:

**Describe the bug**
The websocket API example in Deno 1.4 release post fails with "Cannot resolve module"
Refs: https://deno.land/posts/v1.4

**To Reproduce**
```console
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal

$ deno --version
deno 1.4.0
v8 8.7.75
typescript 4.0.2

$ deno run --allow-net echo.websocket.org https://deno.land/posts/v1.4/websocket.js
error: Cannot resolve module "file:///home/trivikr/echo.websocket.org"
```

**Expected behavior**
Output:
```console
$ deno run --allow-net echo.websocket.org https://deno.land/posts/v1.4/websocket.js
WebSocket ready!
Received data: Hello World!
WebSocket closed!
```

**Comment by lucacasonato** [comment]
Whoops - you should run `deno run --allow-net=echo.websocket.org https://deno.land/posts/v1.4/websocket.js`. I'll update the post now.

**Comment by trivikr** [comment]
> Whoops - you should run `deno run --allow-net=echo.websocket.org https://deno.land/posts/v1.4/websocket.js`. I'll update the post now.

Verified that `--allow-net=echo.websocket.org` works!
