### ISSUE TITLE
Remove Deno.File constructor from types

### ISSUE THREAD

**Issue by nayeemrmn** [denoland/deno#7462]
https://github.com/denoland/deno/blob/v1.4.0/cli/dts/lib.deno.ns.d.ts#L702

Like `Deno.Process` etc. I don't think it was left in for any good reason. We should leave this for us as an implementation detail. This can probably be done for 1.5.0.

**Comment by jkomyno** [comment]
@nayeemrmn So you're proposing to delete any `constructor(/** */)` definition in the `**/lib.deno.*.d.ts` files?
I can do it if no one else is working on this.

**Comment by nayeemrmn** [comment]
> So you're proposing to delete any `constructor(/** */)` definition in the `**/lib.deno.*.d.ts` files?

Just the one for now, thanks.

**Comment by jkomyno** [comment]
@nayeemrmn I've opened PR #7702

**Comment by nayeemrmn** [comment]
I changed my mind about this. The errors in #7702 reminded me that `new File()` is a short way of wrapping an rid under Deno's IO interfaces. It's not that I think it _should_ be used for that, rather it makes it likely that this change would break a not insignificant amount of code.

**Comment by kitsonk** [comment]
Yes. I agree, we should not remove it.
