### ISSUE TITLE
Support base64 output encoding of Sha3

### ISSUE THREAD

**Issue by kaleidawave** [denoland/deno#7464]
Currently the only output of `Sha3_256` is in hexadecimal. Would it be possible to enable `base64` output (and other encodings?). The [base64 encoding library](https://github.com/denoland/deno/blob/master/std/encoding/base64.ts) already exists so it would only require connecting the dots

[source](https://github.com/denoland/deno/blob/530f48d2fda74c2329fd293c516a583e316024cb/std/hash/_sha3/sponge.ts#L102)

```ts
/** Returns the hash in given format */
toString(format: "hex" = "hex"): string {
  const rawOutput = this.squeeze(this.#option.bitsize >> 3);
  switch (format) {
    case "hex":
      return hex.encodeToString(rawOutput);
    default:
      throw new Error("sha3: invalid output format");
  }
}
```

**Comment by caspervonb** [comment]
New style hashes probably won't have any toString specializations at all (#7298).
