### ISSUE TITLE
The simpler overload of `Deno.test` should have an options argument

### ISSUE THREAD

**Issue by solson** [denoland/deno#7474]
Currently `Deno.test` has two overloads:

```ts
function test(name: string, fn: () => void | Promise<void>): void;
function test(t: TestDefinition): void;

interface TestDefinition {
  fn: () => void | Promise<void>;
  name: string;
  ignore?: boolean;
  only?: boolean;
  sanitizeOps?: boolean;
  sanitizeResources?: boolean;
};
```

The `name`/`fn` overload is nicer for simple tests, but if we ever want to temporarily use an option like `only: true` we have to completely rewrite to the `TestDefinition` overload. If the first overload was changed to...

```ts
function test(
  name: string,
  fn: () => void | Promise<void>,
  options?: TestOptions,
): void;

type TestOptions = Omit<TestDefinition, "name" | "fn">;
```

...then we could easily switch between these two calls:

```ts
Deno.test("my test", () => { assertSomething() });

Deno.test("my test", () => { assertSomething() }, { only: true });
```

**Comment by bartlomieju** [comment]
@solson we had this overload before 1.0 release but decided to remove it to keep API surface minimal. 

Deno tries to keep testing interface minimal (like Rust) and I believe we shouldn't change it before 2.0.

**Comment by nayeemrmn** [comment]
@bartlomieju We never had this overload. This issue is about appending the remainder of options to the secondary overload. I don't think that's conceptually less minimal than what we have now.

**Comment by ry** [comment]
I agree with @bartlomieju - we shouldn't further complicate the already-complicated `Deno.test` signature.

**Comment by nayeemrmn** [comment]
The proposal as written here includes an unnecessary type definition making it seem more complicated than it is.

We're talking about going from:
```ts
function test({
  fn,
  name,
  ignore,
  only,
  sanitizeOps,
  sanitizeResources,
});
function test(name, fn);
```
to
```ts
function test({
  fn,
  name,
  ignore,
  only,
  sanitizeOps,
  sanitizeResources,
});
function test(name, fn, {
  ignore,
  only,
  sanitizeOps,
  sanitizeResources,
});
```
Currently, the secondary overload brings out the compulsory options as positional arguments and doesn't support the rest. In this proposal, the secondary overload brings out the compulsory options as positional arguments and keeps the rest in the options bag. It's not more complicated by any means, it removes a weird unjustified difference between the overloads making it simpler in my opinion.
