### ISSUE TITLE
Where do I add link to other languages docs?

### ISSUE THREAD

**Issue by tokiedokie** [denoland/deno#7490]
I made a Japanese language site https://deno-ja.vercel.app/ (repo: https://github.com/tokiedokie/deno_website2_japanese)
I want to submit PR to add link to this site to the deno manual

where should I submit PR to?

ref: #5435, #5911, denoland/deno_website2#550

**Comment by nayeemrmn** [comment]
https://github.com/denoland/deno/issues/5435#issuecomment-629255809

We want it to appear in the manual, but the website's wrapper of the manual would probably be best so it can appear in the header/footer or something like that.

**Comment by kitsonk** [comment]
Closing as I believe the question has been answered.
