### ISSUE TITLE
Revert "feat: bundle installed script"

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#7492]
Unfortunately users are having quite a few problems with bundling of installed script (eg. https://github.com/denoland/deno/issues/7455).

We should revert this change for 1.4.1 and revisit the topic once we migrate bundling to SWC (#7461)

**Comment by bartlomieju** [comment]
@kt3k could you look into this problem? I tried reverting but got a bit lost in the config bit...

**Comment by kt3k** [comment]
I was able to reproduced the issue reported in #7455 with the following command:

```
deno bundle --unstable https://deno.land/x/lume@v0.2.2/cli.js > out.js
deno run out.js
```

I think it is caused by the bundler itself. (Maybe our bundler is not mature enough to handle general cases?) I'll look into it more tomorrow.

But I agree with reverting with #7522 for the moment.

**Comment by piscisaureus** [comment]
I'd suggest to add the `--bundle` flag for now, so we can get some real life experience with it.
