### ISSUE TITLE
Change Console class to interface in types

### ISSUE THREAD

**Issue by nayeemrmn** [denoland/deno#7494]
https://github.com/denoland/deno/blob/v1.4.0/cli/dts/lib.deno.shared_globals.d.ts#L572-L588
->
https://github.com/denoland/deno/blob/v1.4.0/cli/dts/lib.dom.d.ts#L18972-L18995

The declaration is left over from when we concretely exported this class.

**Comment by kitsonk** [comment]
PR #7514 supercedes this... any thoughts/concerns should be raised there.

**Comment by nayeemrmn** [comment]
This isn't covered by #7514 since there is no concrete `Console` object. It can't be a class.
