### ISSUE TITLE
Lint --ignore doesn't normalize file seperators

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#7495]
`deno run ./tools/lint.ts` works on unix and Windows.

`deno lint --unstable --ignore=./tools/lint.ts` does not work on Windows, but it does work on Unix. From my preliminary testing it seems you have to do `deno lint --unstable --ignore=.\tools\lint.ts` on Windows. I think we should normalize these separators.

**Comment by tokiedokie** [comment]
`deno lint --unstable --ignore=.\tools\lint.ts` does not work for me on Windows
`deno fmt --unstable --ignore=./tools/lint.ts` and `deno fmt --unstable --ignore=.\tools\lint.ts` also don't work
