### ISSUE TITLE
`deno test` mis-ordering with top-level await

### ISSUE THREAD

**Issue by dylanpyle** [denoland/deno#7503]
I'm trying to use `deno test` to run several test files, but with some setup and teardown procedures (in their own files) before and afterwards. Unfortunately one of the tests themselves tests a file which depends on a 3rd-party module, which in turn uses top-level `await`. The result is that my tests are not run in the order I expect.

Here's a contrived example:

```ts
// first.ts:
import './some-slow-dependency.ts';
Deno.test('first.ts test name', async () => { console.log('first.ts test body'); });

// second.ts:
Deno.test('second.ts test name', async () => { console.log('second.ts test body'); });

// some-slow-dependency.ts:
await new Promise((resolve) => setTimeout(resolve, 500));
```

```
$ deno test first.ts second.ts
running 2 tests
test second.ts test name ... second.ts test body
ok (2ms)
test first.ts test name ... first.ts test body
ok (2ms)
```

I understand this might not be a bug per se (top-level await working as expected?) but it's definitely confusing behavior and took a while to debug, especially since the test runner obviously knew at the time it logged `running 2 tests` that there were two tests.

Any pointers?

**Comment by nayeemrmn** [comment]
@dylanpyle The order guarantees we provide for test runs and module execution are both correctly satisfied here.

Here's your problem: you require that the `Deno.test()` in `first.ts` is run before the `Deno.test()` in `second.ts`, but you haven't expressed that dependency in your imports. (The order you write them in the CLI is not a correct way of expressing this. It's linear.)

I've checked that if you put `import "./first.ts";` at the top of `second.ts`, the tests will run in the desired order.

**Comment by dylanpyle** [comment]
Yep, totally fair — in my "real" use case I solved this by having both setup and teardown import `deps.ts`, which accomplishes the same thing. Appreciate the confirmation that this is expected 😄 . I'll close for now!
