### ISSUE TITLE
deno run fails when local app data location path length exceeds 260 characters on Windows

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#7510]
Thought I would open this as an FYI, but feel free to close as it's unlikely people will run into this.

1. Use Windows with [long paths enabled](https://superuser.com/a/1119980/214182).
2. Create a directory path with a long name.
3. Create a file `test.ts` inside this directory.
4. `deno run test.ts`
5. Keep increasing the file path length until it fails.

Relates to https://github.com/rust-lang/rust/issues/76586 ...the fix is to use UNC paths, but it seems std::path does not handle UNC paths nicely.

**Sample output 1**

```
~\projects\going-deeper\and-deeper\and-deeper\and-deeper\and-deeper\and-deeper\and-deeper\and-deeper\and-deeper\and-deeperrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr
> deno run test.ts
Check file:///C:/Users/david/projects/going-deeper/and-deeper/and-deeper/and-deeper/and-deeper/and-deeper/and-deeper/and-deeper/and-deeper/and-deeperrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr/test.ts
error: Could not create TypeScript compiler cache location: "C:\\Users\\david\\AppData\\Local\\deno\\gen\\file\\C\\Users-deeper\\and-deeperrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"
```

**Sample output 2**

```
echo "console.log('test')" > testingggh.ts; deno run testingggh.ts
Check file:///C:/Users/david/123456789/123456789/123456789/123456789/123456789/123456789/123456789/123456789/123456789/123456789/123456789/123456789/123456789/123456789/123456789/123456789/123456789/123456789/testingggh.ts
error: The system cannot find the path specified. (os error 3) (for '"C:\\Users\\david\\AppData\\Local\\deno\\gen\\file\\C\\Users\\david\\123456789\\123456789\\123456789\\123456789\\123456789\\123456789\\123456789\\123456789\\123456789\\123456789\\123456789\\123456789\\123456789\\123456789\\123456789\\123456789\\123456789\\123456789\\testingggh.ts.buildinfo"')
```

**Comment by piscisaureus** [comment]
I suspect the restriction you’re running into is that the current working directory can’t use UNC paths.

This is why e.g. node can work long paths just fine, but it can’t chdir() into them or run executables with long paths.

Note that the “long paths feature“ that you’re talking about is something else - it goes a step further and allows “regular” paths to be long.

I wasn’t aware that enabling long paths allows chdir()ing into a directory of over 260 characters long. But I think it still can’t be an “\\?\” path.

**Comment by lucacasonato** [comment]
This should be fixed now, because we hash file paths in `DENO_DIR` now.

**Comment by devingfx** [comment]
Hi !
Is there some deno's api to get the current OS max path length ?
