### ISSUE TITLE
Failed building Deno from source due to librusty_v8.a

### ISSUE THREAD

**Issue by nathanblair** [denoland/deno#7517]
I've seen some other threads pop up with this exact problem. I tried clearing as much of the rust cache as possible - which did a redownload of the librusty crate from what I can tell. I can see the crate in the ~/.cargo/registry/src directory, anyway.

I imagine the library archive is being put in that directory as part of some previous build-dependency step? So this is probably an issue with an upstream package being able to properly build; would that be librusty_v8?

System specs:
- Void Linux, WSL 4.19 kernel
- musl libc variant

Here is the exact error:

`failed to add native library /tmp/cargo-installRaTPXe/release/gn_out/obj/librusty_v8.a: file too small to be an archive`

The file size happens to be:
```
 > ls -lA /tmp/cargo-installRaTPXe/release/gn_out/obj
total 4
-rw-r--r-- 1 [redacted] [redacted] 9 Sep 16 07:59 librusty_v8.a
```

**Comment by lucacasonato** [comment]
rusty_v8 does not support musl. See https://github.com/denoland/rusty_v8/issues/49
