### ISSUE TITLE
Parsing HTML with XPath. Is there anything available?

### ISSUE THREAD

**Issue by suchislife801** [denoland/deno#7527]
Is there a way to scrape HTML at the moment?

Something like [https://html-agility-pack.net/from-web](https://html-agility-pack.net/from-web)

**Comment by exside** [comment]
Some related discussion going on over here https://github.com/denoland/deno/issues/7505

**Comment by kitsonk** [comment]
As pointed out, both #7505 and #6794 cover this off.

**Comment by The-Solomon** [comment]
any updates?
