### ISSUE TITLE
Inspect should quote non-simple object keys

### ISSUE THREAD

**Issue by solson** [denoland/deno#7548]
This is a follow-on from https://github.com/denoland/deno/issues/7532 where I noticed Deno is not doing what I expected for object keys.

In node we get this:

```console
> ({ "foo\b": 1, "bar": 2 })
{ 'foo\b': 1, bar: 2 }
```

While in deno (latest commit, https://github.com/denoland/deno/commit/e4188f7dfb95ad16750874dd2cdd4a80b48b1ecc) we get this:

```console
> ({ "foo\b": 1, "bar": 2 })
{ foo\b: 1, bar: 2 }
```

I think we essentially need to detect when object keys would be valid unquoted keys in a JS object literal, and otherwise quote them.

cc @caspervonb

**Comment by solson** [comment]
We'll also have to deal with cases like this:

```console
> ({ "\"": 1, "\\": 2 })
{ ": 1, \: 2 }
```

Where node does:

```console
> ({ "\"": 1, "\\": 2 })
{ '"': 1, '\\': 2 }
```

Post https://github.com/denoland/deno/issues/7545, it should just be a matter of doing the check I described and then optionally invoking `Deno.inspect` or equivalent, I hope?

**Comment by caspervonb** [comment]
Yeah saw this when I wrote a test for escaped keys, simple enough to detect with a regex test.

Patch incoming.

**Comment by caspervonb** [comment]
Do symbols need to be special cased? I don't think so but might be missing something.

**Comment by solson** [comment]
I saw your (deleted?) comment about symbols, and I think there's a couple interesting details, so I opened https://github.com/denoland/deno/issues/7551.

**Comment by caspervonb** [comment]
> I saw your (deleted?) comment about symbols, and I think there's a couple interesting details, so I opened #7551.

Yeah, was about to move it to the review.
