### ISSUE TITLE
Lint: no-inferrable-types for a declared type

### ISSUE THREAD

**Issue by rodolphocastro** [denoland/deno#7549]
Hello!

Currently when running `deno lint --unstable` I get some issues with `no-inferrable-types` on fields that I'm actually **declaring** the type and **then assigning a value**.

For instance the following snippet causes the output from deno lint:

```
export function createString(
  prefix: string = "",
  params: GeneratorParameters = defaultParameters,
): string {
  if (!validateGeneratorParameters(params)) {
    throw new Error(`The parameters ${params} aren't valid`);
  }

  const suffix = generateRandomNumber(params).toString();
  return prefix !== "" ? prefix + suffix : suffix;
}
```

```
(no-inferrable-types) inferrable types are not allowed
  prefix: string = "",
  ^^^^^^^^^^^^^^^^^^^
    at E:\Src\dixture\src\_simpleGenerator.ts:45:2
```

Even tho the `lint` option is flagged as `unstable` I was unable to find this reported elsewhere so hopefully this is just a duplicate and this is a know issue 😅

You can find the failing snippet on [this GitHub repository](https://github.com/rodolphocastro/dixture/blob/60ef43d1d98f66d5d95f8411fae6b9284da73936/src/_simpleGenerator.ts#L62), just nevermind the `no-explicit-any` (as those are intended by me right now 😅)

**Comment by solson** [comment]
This is actually working as intended according to [eslint's definition](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-inferrable-types.md) of `no-inferrable-types`. Under "The following are invalid" they include this example:

```ts
function fn(a: number = 5, b: boolean = true) {}
```

So the idea of this lint is that even types in signatures should be removed when they are trivially inferrable from a literal value. There is an `ignoreParameters` option that makes it work how you expect, but I don't think `deno lint` allows configuration currently.

**Comment by solson** [comment]
Also, in case it is unclear, note that the parameter *does* still end up with the expected type (hence why the lint considers declaring it redundant):

![image](https://user-images.githubusercontent.com/26806/93551396-a85e8000-f965-11ea-8a52-2fab2995508f.png)

**Comment by rodolphocastro** [comment]
Thanks for the clarification @solson ! 

That makes sense haha. If only I hadn't included Deno as a hardcoded search term I might've ended up on eslint's docs 😅.
