### ISSUE TITLE
Inspect could be better for symbols

### ISSUE THREAD

**Issue by solson** [denoland/deno#7551]
Here's a look at the current handling of `Symbol`s in `Deno.inspect`.

**1.** Neither Node nor Deno quote symbol names with unprintable characters, but both do escaping in object keys:

Deno

```console
> ({ [Symbol("foo\n\0bar")]: 1 })
{ Symbol(foo\n\x00bar): 1 }
```

Node

```console
> ({ [Symbol("foo\n\0bar")]: 1 })
{ [Symbol(foo\n\u0000bar)]: 1 }
```

**2.** However, note that Node puts `[]` around symbol keys, which is clearer in this contrived example:

Deno

```console
> ({ [Symbol()]: 1, 'Symbol()': 2 })
{ Symbol(): 2, Symbol(): 1 }
```

Node

```console
> ({ [Symbol()]: 1, 'Symbol()': 2 })
{ 'Symbol()': 2, [Symbol()]: 1 }
```

**3.** Lastly, while inspecting a symbol *directly*, neither Node nor Deno even do escaping (output is the same for both):

```console
> Symbol("foo\n\0bar")
Symbol(foo
bar)
```

### To do
  * [ ] 1. It seems okay not to quote symbol names, but maybe we should?
  * [ ] 2. I think we should add `[]` for object symbol keys like Node.
  * [ ] 3. When inspecting symbols directly we should at least do escaping — make it identical to the output for symbols in object keys (aside from the `[]`).

cc @caspervonb

**Comment by caspervonb** [comment]
Excellent digging 😁 

So for strings, browser behavior was also considered; e.g console.log("%o", "foo") does result in a quoted string in the developer console across browsers.

1. Browsers disagree on this, Chrome does quote this (`{"Symbol(foo↵bar)": 1}`), Safari does not and did not try Firefox. All the characters are selectable tho so if you select it you do get the \0 in your clipboard; the CLI equivalent of that would be to quote and escape. An interesting thing about Chrome tho if you do a well-known symbol like `{Symbol(Symbol.iterator): 1}` it doesn't quote.
2. Not sure, probably as it makes for a valid computed key.
3. Should reflect 1, yes.

**Comment by solson** [comment]
The browsers mostly make me think "we can do better", so I hope we're not *too* constrained by what they tend to do. (Of course, we should care about compatibility, but this pretty-printing stuff seems drastically incompatible between implementations already.)

Firefox:

![image](https://user-images.githubusercontent.com/26806/93571557-89271900-f98c-11ea-94ca-e5eadf52d5df.png)

Chrome:

![image](https://user-images.githubusercontent.com/26806/93571590-9512db00-f98c-11ea-8360-ddad20530a58.png)

I find it curious that *any* implementation handles symbol-in-key differently than a symbol directly, but all of Deno, Node, and Chrome do, only Firefox doesn't. Can we make sure we use the same code to handle both cases, so it's impossible for them to differ? (Ideally implying escaping in both cases, unlike Firefox.)

Also, if we *do* quote symbol names, I was imagining something like `Symbol("foo\n\x00bar")` — I find Chrome's `"Symbol(foo↵�bar)"` misleading, because it just looks like a string. Also, I guess Chrome decides whether to quote symbols the same way as object keys, so since `{"a": 1}` prints as `{a: 1}`, `Symbol("a")` prints as `Symbol(a)`.

**Comment by solson** [comment]
For reference, this is how it would look if we implemented all 3 of the ideas in this issue:

```console
> ({ [Symbol("foo\n\0bar")]: 1 })
{ [Symbol("foo\n\x00bar")]: 1 }

> ({ [Symbol()]: 1, 'Symbol()': 2 })
{ "Symbol()": 2, [Symbol()]: 1 }

> Symbol("foo\n\0bar")
Symbol("foo\n\x00bar")
```

The implementation would ideally be like:
* For printing a symbol property in an object, call the one routine we have for pretty-printing symbols, then surround with `[]`.
* For printing a symbol, call the one routine we have for pretty-printing strings on `description` if it's not undefined, then surround with `Symbol(` and `)`.

This should avoid a bunch of the weird behaviours we see in other implementations.

<details><summary>Side note</summary>


Incidentally, we'd also be able to tell the difference between these two:

```console
> Symbol()
Symbol()

> Symbol("")
Symbol("")
```

Since the former has `description: undefined` and the latter has `description: ""`. Not that it's particularly important to distinguish, since the `description` isn't what gives a symbol its unique identity, but this distinction is still visible to code.

</details>

**Comment by caspervonb** [comment]
> Incidentally, we'd also be able to tell the difference between these two:

That's simple enough as `Symbol().description === undefined`.

**Comment by solson** [comment]
Oh, I didn't mean it would gives us a new capability in code, I just meant it makes the pretty-printing more precise.

**Comment by caspervonb** [comment]
Internal implementation detail, as in yeah that's fine to add.

**Comment by solson** [comment]
Ah, sorry for the misinterpretation. Carry on. :smile:
