### ISSUE TITLE
Code sample for WebAssembly doesn't compile on 1.4.0

### ISSUE THREAD

**Issue by ozanmuyes** [denoland/deno#7556]
The code sample at [Manual - Using WebAssembly](https://deno.land/manual/getting_started/webassembly) doesn't compile on Deno 1.4.0, the error message above is shown instead;

```bash
error: TS2349 [ERROR]: This expression is not callable.
  No constituent of type 'ExportValue' is callable.
console.log(wasmInstance.exports.main().toString());
```

To fix this I changed 11th line (last line) with;

```js
console.log((wasmInstance.exports.main as Function)().toString());
```

by that it shows the result.

<details><summary>Spoiler Alert</summary>
<span>42 is the result.</span>
</details>

**Comment by ry** [comment]
it runs as javascript

**Comment by tokiedokie** [comment]
I got this error on v1.3.3 and v1.4.0. I did't get this on v1.0.0-v1.3.2

**Comment by caspervonb** [comment]
For a little bit of context; this used to work in both JavaScript and TypeScript but I updated the WebAssembly type definitions to a more recent version in https://github.com/denoland/deno/pull/7216 which no longer uses `any` for imports and exports.
 
Ties into https://github.com/denoland/deno/issues/6844.

**Comment by pschyska** [comment]
I think this is not fixed. I had to actually use the `const main` to make it work, as in:
````
console.log(main().toString());
````
