### ISSUE TITLE
suggestion(std/examples): import from URL instead of relative path

### ISSUE THREAD

**Issue by tokiedokie** [denoland/deno#7570]
New users use examples as tutorial. They change scripts to understand how deno works.
However present scripts use import from relative path therefore they have to change it to import from URL before they modify script.

I suggest to use import from URL instead of relative path for easy to start

**Comment by bartlomieju** [comment]
@tokiedokie I'm not sure I understand what you're proposing here, could you provide an example?

**Comment by nayeemrmn** [comment]
@bartlomieju 
https://github.com/denoland/deno/blob/ab7b8ba8d15f37d6244784a16a3f4f3c96e38769/std/examples/flags.ts#L2
```diff
- import { parse } from "../flags/mod.ts";
+ import { parse } from "https://deno.land/std@0.78.0/flags/mod.ts";
```
I think it's okay if the version falls out of date because `std/examples` is to showcase Deno usage, not each std module.
