### ISSUE TITLE
createWalkEntry and createWalkEntrySync should probably not be exported from std/fs

### ISSUE THREAD

**Issue by caspervonb** [denoland/deno#7572]
There's two functions exported in std/fs/walk.ts (`createWalkEntry` and `createWalkEntrySync`) that don't make much sense to keep public and seem to be just exported to share internally between modules.

**Comment by nayeemrmn** [comment]
`std/README.md`:
> Don't import any symbol with an underscore prefix: `export function _baz() {}`.

Use this convention to mark them private, if anyone is interested.
