### ISSUE TITLE
换语言了吗？之前不是用Go的么？编程rust了？

### ISSUE THREAD

**Issue by linushp** [denoland/deno#758]
？换语言了吗？之前不是用Go的么？编程rust了？

**Comment by kevinkassimo** [comment]
(For others, he is asking if and why Deno has switched to Rust. I speak Chinese so I'll reply answer to his question and request no more such questions in the issues)

@linushp 你好。的确是从Go换成了Rust，核心原因是Go也是一门自动垃圾回收语言，对性能会造成一定程度的消耗。详见 #208 #165 
还有希望不要再在issue里进行提问（首先issue是用来追寻现存问题和设计讨论用，而非问答，特别是直接用中文，主要的maintainer都看不懂啊。。。）。个人建议这类问题可以去stackoverflow/segmentfault甚至在知乎上问（比如向justjavac几位）。Deno也有一个[gitter群](https://gitter.im/denolife/Lobby)，如果你能使用英语交流的话欢迎加入讨论！
