### ISSUE TITLE
Import Fails on Directory References

### ISSUE THREAD

**Issue by cawoodm** [denoland/deno#7594]
> deno 1.4.1
> v8 8.7.75
> typescript 4.0.2

Can't seem to import anything successfully from ramda. It has modules which reference directories like ` import _arity from './internal/_arity';` and deno seems to struggle with directories.

From the ramda docs:

    import * as R from "https://deno.land/x/ramda/index.js";

Fails with random 404 (different each time):
> error: Import 'https://deno.land/x/ramda@v0.27.1/internal/_arity' failed: 404 Not Found
> Imported from "https://deno.land/x/ramda@v0.27.1/pipe.js:1"

    import {pipe} from "https://deno.land/x/ramda@v0.27.1/pipe.js";

Fails with random 404 (different each time):
> error: Import 'https://deno.land/x/ramda@v0.27.1/internal/_arity' failed: 404 Not Found
> Imported from "https://deno.land/x/ramda@v0.27.1/pipe.js:1"

    import {pipe} from "https://deno.land/x/ramda@v0.27.1/index.js";

Fails. Downloads the internet (everything in ramda) (not what I want) and fails with:
> error: Import 'https://deno.land/x/ramda@v0.27.1/aperture' failed: 404 Not Found
> Imported from "https://deno.land/x/ramda@v0.27.1/index.js:14"

**Comment by Soremwar** [comment]
@cawoodm Where did you get that import statement from?

If you go to that same address in your browser, you'll see that there isnt even anything published under ramda :(

**Comment by Soremwar** [comment]
Bad news man :(

Looks like Ramda is just a commonJS module someone uploaded to deno.land/x. It doesn't have JavaScript imports so it isn't usable by Deno

**Comment by nayeemrmn** [comment]
Isn't it usable with `std/node`'s `require()`?

**Comment by cawoodm** [comment]
I though Ryan or someone checks what lands on deno.land otherwise it will be all kinds of garbage.

**Comment by lucacasonato** [comment]
@cawoodm `deno.land/x` is a public code hosting service - anyone can put anything on there. `deno.land/std` is the curated standard library.

**Comment by lucacasonato** [comment]
This is not a bug anyway - the code you are trying to load uses node module resolution. Deno only supports the browser standard resolution algorithm.

**Comment by cawoodm** [comment]
```javascript
import * as R from "https://x.nest.land/ramda@0.27.0/source/index.js";
```

**Comment by kevlarr** [comment]
@lucacasonato Why only support browser standard (ie. "classic" strategy)? Deno is a runtime for backends, and Typescript itself [encourages "node" strategy](https://www.typescriptlang.org/docs/handbook/module-resolution.html#module-resolution-strategies) as the default. That implies most Typescript projects are going to use node's strategy, which means Deno can't be used without asking *every project to update its imports*.

That seems like an arbitrary decision that could really hinder adoption of Deno, and we *need* Deno to be more widely adopted.

**Comment by Soremwar** [comment]
It's unlikely that Deno will work in existing TypeScript projects even if module resolution was identical. You'd have to deal with compatibility issues such as Node's internal libraries not found in Deno, Deno not having a "node_modules" like resolution strategy for external libraries, Deno's embed-ability into other programs given it's Rust based tech stack and so on. It's clear to me that Deno was meant to work as a clean slate for JavaScript development, not an alternative that you can switch to or from Node

However if that was the case the real question would be, what would even the point in creating a new runtime if it behaves exactly like the already existing one?
