### ISSUE TITLE
`setTimeout` still consumes time even if it's followed by `clearTimeout`

### ISSUE THREAD

**Issue by magurotuna** [denoland/deno#7599]
### 

Take the following code as an example:

```js
const handle = setTimeout(() => {
  console.log("timeout finish");
}, 10000);
clearTimeout(handle);
console.log("finish");
```

We expect that this program finishes _immediately_ after `console.log("finish");`, because the timeout has been canceled. But actually when running it by `deno run`, we need to wait 10 seconds until the program finishes.
(In Node.js, the program behaves as we expect.)

This unexpected behavior in Deno is likely because `opStartGlobalTimer` is an async operation, which means that turning event loop is required to let `GlobalTimer` in Rust start working. 
https://github.com/denoland/deno/blob/0a9d7e4e397a688dbd5d9448cdcbb119182ed446/cli/rt/11_timers.js#L11-L13

I guess `GlobalTimer` should start counting time synchronously, but callback needs to be executed asynchronously - we may have to do a big change to achieve this?
I've just started referring to the implementation of Node.js, but I don't get any solution so far.

This issue also has something to do with the FIXME comment below:
https://github.com/denoland/deno/blob/0a9d7e4e397a688dbd5d9448cdcbb119182ed446/cli/rt/11_timers.js#L309-L316

**Comment by bartlomieju** [comment]
I've debug this problem. Underlying timer is Rust is created **after** timeout is cleared in JS:
```
opStartGlobalTimer before
opStopGlobalTimer before
sending None <-- no timeout to cancel here
opStopGlobalTimer after
finish
new timeout <-- timer in Rust is created here
opStartGlobalTimer after
```
This is most likely caused by fact that creating a new timer is an async op - it is polled after next tick of event loop.
