### ISSUE TITLE
Main thead panics upon worker thread panicing

### ISSUE THREAD

**Issue by 00ff0000red** [denoland/deno#7620]
Just for confirmation, the Rust / Deno main thread isn't supposed to panic if `self.close();` is called in a worker, right?

**Comment by kitsonk** [comment]
Deno generally shouldn't panic.

It would be great to get a bit more information than this.

**Comment by 00ff0000red** [comment]
I literally did nothing more than merely create a worker that called `self.close();`. There's nothing more to say; the process ended with a normal main thread panic saying the usual "use RUST_TRACEBACK to debug" argument. I'm going to see if I can recreate it with two lines.

**Comment by 00ff0000red** [comment]
1.1 Deno

> thread 'deno-worker-0' panicked at 'Failed to post message to host: TrySendError { kind: Disconnected }', cli/ops/worker_host.rs:144:7
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'Worker thread panicked: Any', cli/ops/worker_host.rs:332:11
exit status 101

index.ts
```ts
new Worker(
	new URL(
		"./worker.ts",
		import.meta.url
	).href, {
		type: "module"
	}
);
```

worker.ts
```ts
self.close();
```

**Comment by kitsonk** [comment]
@bartlomieju any ideas?

**Comment by bartlomieju** [comment]
Looks like an edge case that wasn't considered. Obviously worker shouldn't panic when called `self.close()`. So this is a bug
