### ISSUE TITLE
Import Assertions/JSON Modules

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#7623]
[Import Assertions](https://github.com/tc39/proposal-import-assertions) has just been moved to Stage 3.  [JSON Modules](https://github.com/tc39/proposal-json-modules) is still at Stage 2 (and JSON Modules depends on Module Assertions).

I haven't found a tracking issue for v8.

TypeScript issue: microsoft/TypeScript#40694

cc/ @kdy1

**Comment by kdy1** [comment]
I'll implement it soon.

**Comment by kitsonk** [comment]
@kdy1 the TypeScript PR is open now for inspiration: https://github.com/microsoft/TypeScript/pull/40698

**Comment by kdy1** [comment]
I have a question. Will deno support json modules when it is in stage 2?

**Comment by kitsonk** [comment]
Personal opinion, it would be triggered by v8 supporting it, that _might_ come in advance of Stage 3, but import assertions are a pre-req for support.  Basically there are some runtime semantics that need to be resolved (if I am reading the [slides properly](https://docs.google.com/presentation/d/1_dgRPueD2dwSIsVOXVexYOncCRrDPcm_CPnswq9zOe4/edit#slide=id.p)).

I know there is a lot of desire from the community to have it, so we would want to go as fast as reasonably possible.

**Comment by kdy1** [comment]
Got it, thanks for the clarification.

**Comment by kdy1** [comment]
I added support for it within the parser.

**Comment by bartlomieju** [comment]
[Intent to Prototype and Ship: Import Assertions](https://groups.google.com/a/chromium.org/g/blink-dev/c/Xft04J07Oh0/m/s-kUUljbCQAJ) from Chromium

Tracking issue in V8 - [Implement Import Assertions](https://bugs.chromium.org/p/v8/issues/detail?id=10958&q=import%20assertions&can=2)

**Comment by kitsonk** [comment]
Updates:

- V8 8.9 contains import assertions which rusty_v8 will be upgraded to.  We need to expose this in rusty_v8
- TypeScript has an issue https://github.com/microsoft/TypeScript/issues/40694.  They say they are going to parse it, but not enforce it.  Hard to tell when it will land in TypeScript though.
- swc added it in https://github.com/swc-project/swc/pull/1100

**Comment by kitsonk** [comment]
JSON Modules has gone Stage 3 with TC39.  Hopefully that will flush out TypeScript.

**Comment by probins** [comment]
[Blink intent to ship](https://groups.google.com/a/chromium.org/g/blink-dev/c/dppzCKHI874) both import assertions and JSON modules. I assume this is aimed at Chromium 91/v8 9.1

**Comment by mko-io** [comment]
Chrome just updated their [chromestatus page, ](https://chromestatus.com/feature/5749863620804608)JSON module  and import assertions are enabled by default on Chrome 91

**Comment by bartlomieju** [comment]
I will try to get import assertions into 1.13

**Comment by kitsonk** [comment]
@bartlomieju TypeScript is still working on it. The PR seems to be finally edging closer to reality to be merged.

**Comment by bartlomieju** [comment]
Thanks for the heads, I'll look into `deno_core` implementation anyway and we can wait on TS support before merging

**Comment by bartlomieju** [comment]
Unfortunately bumping to Q4 because of missing TypeScript support.

**Comment by nnmrts** [comment]
Looks like TypeScript supports it now. 🚀

**Comment by kitsonk** [comment]
It supports it in a yet to be released version of TypeScript.  The timelines coincide for the Deno 2.0 release, therefore that is why it is part of the release plan and tagged for Deno 2.0.

**Comment by nnmrts** [comment]
@kitsonk I know that, I really just wanted to point it out since no one here did yet. Sorry if it seemed like something else. 😕
