### ISSUE TITLE
Import Error - Could not find module

### ISSUE THREAD

**Issue by ohadkoren** [denoland/deno#7625]
https://github.com/denoland/deno/blob/cca8856fbf9552ccd7c6fe4eb6cbb8d521978a21/cli/bench/deno_http_proxy.ts#L2

This `import` returns an error: `Could not find module "../std/http/server.ts" locally.`
That's because it is not located there. It should be at `"../../std/http/server.ts"`

Unfortunately, that change affects the code and generates other errors from the references.

**Comment by salemalem** [comment]
Hi, could you please show us your directory?
like this
![image](https://user-images.githubusercontent.com/42411937/93896502-cdab0f80-fd12-11ea-8df9-966ff5e5e30e.png)

**Comment by kitsonk** [comment]
I'm really confused on how you expect this to be resolved.  The file structure of the project really isn't open for debate.

**Comment by ohadkoren** [comment]
> Hi, could you please show us your directory?

@salemalem I went to parent directory ( `cli`) and there's no `std` folder (The `std` folder is actually located at the root directory).

![missingDir](https://user-images.githubusercontent.com/52351606/94106161-7e183100-fe43-11ea-9e5f-dbecc30f0f22.PNG)
------

> I'm really confused on how you expect this to be resolved. The file structure of the project really isn't open for debate.

@kitsonk I'm not asking to change the project structure, I'm just trying to report a missing folder.

**Comment by kitsonk** [comment]
Ah, I see your confusion.  The problem is that when these are run as intended, their root isn't actually `deno/cli/bench`.  How are you trying to run it?  It should only be run via `cargo bench`.

**Comment by bartlomieju** [comment]
@kitsonk yes, IIRC benchmarks are run from `cli/` directory

**Comment by ohadkoren** [comment]
@kitsonk @bartlomieju Thanks, I didn't know that. Much appreciation for your help!
