### ISSUE TITLE
Watcher stucked into a infinite restart

### ISSUE THREAD

**Issue by SRNV** [denoland/deno#7627]
infinite restart due to multiple changes
**version**: 1.4.1
**how to repoduce ?**: 
- rename a directory
- rename paths of various imports at the same time with Search and Replace tools

**screenshot**: 
![Screenshot from 2020-09-22 10-52-06](https://user-images.githubusercontent.com/37340675/93905407-3c7c6e80-fcfb-11ea-8242-2640fd4c5fa0.png)

**video**: https://cdn.discordapp.com/attachments/684911491035430919/757907082937761812/watcher_issue.mp4

**Comment by magurotuna** [comment]
I think this issue is also fixed by #8013

**Comment by bartlomieju** [comment]
Should have been fixed in https://github.com/denoland/deno/pull/8083
