### ISSUE TITLE
console.log dies on null prototype function

### ISSUE THREAD

**Issue by 00ff0000red** [denoland/deno#7633]
So, I was honestly acting dumb, and ended up with essentially just this:
```ts
const f = <T>(x: T): T => x;

Reflect.setPrototypeOf( f, null );

console.log( f );

console.log(( f( NaN ) );
```

Attempting to log the function causes an error.

> Uncaught TypeError: Cannot read property 'constructor' of null...

**Comment by bartlomieju** [comment]
CC @nayeemrmn seems like a bug in `Deno.inspect()`
