### ISSUE TITLE
Deno.readLink path parameter is string only (not string | URL like Deno.readFile)

### ISSUE THREAD

**Issue by callionica** [denoland/deno#7639]
There's inconsistency in the Deno functions that deal with paths. Specifically `Deno.readLink` accepts a file path only as a `string`, whereas `Deno.readFile` accepts `string | URL`. It would be good if readLink also accepted URLs.

**Comment by wperron** [comment]
is anyone working on this one? if not I can look at it.

**Comment by bartlomieju** [comment]
@wperron I don't think anyone's working on this. Please do look at it
