### ISSUE TITLE
(Deno.customInspect) Symbol doesn't have an effect on functions

### ISSUE THREAD

**Issue by 00ff0000red** [denoland/deno#7650]
(If this is not a bug, I ask that it is at least documented.)

The `Deno.customInspect` Symbol supposed to be called by `console.log` and other output functions, if the object has the key.
I applied this to a function, yet it seems to have outright ignored it.

```ts
//@ts-nocheck

const temp = Object.assign(
	() => { }, {
		[Deno.customInspect]: () => "[ null, NaN, undefined, \"[Object object]\" ]"
	}
);

console.log(
	"%o\n%o\n%o\n%o",
	Deno.customInspect in temp, // true
	temp[Deno.customInspect], // function [Deno.customInspect]
	temp[Deno.customInspect](), // [ null, NaN, ... ]
	temp // [Function]; expected to be [ null, NaN, ... ]
);
```

*(Ran on Deno 1.1, if it matters)*

**Comment by lucacasonato** [comment]
> Ran on Deno 1.1

Please upgrade to 1.4: `deno upgrade`

**Comment by 00ff0000red** [comment]
> > Ran on Deno 1.1
> 
> Please upgrade to 1.4: `deno upgrade`

Sorry, I really wish that I could; I don't have a personal PC right now. Been using https://repl.it

**Comment by 00ff0000red** [comment]
Neat, that was fast. Great to see that's fixed!
