### ISSUE TITLE
(std/datetime): dayOfYear returns different values depending on the time zone

### ISSUE THREAD

**Issue by tokiedokie** [denoland/deno#7665]
I cannot pass std tests because of this issue

---

js file:
```javascript
import * as datetime from "https://deno.land/std@0.70.0/datetime/mod.ts"

console.log(datetime.dayOfYear(new Date("1582-10-04T03:24:00+0000")));
console.log(datetime.dayOfYear(new Date("1582-10-04T03:24:00+0900")));
```
output:
```
277
276
```

**Comment by bartlomieju** [comment]
CC @timreichen

**Comment by timreichen** [comment]
I don't quite get why this is marked as a bug.
`std/datetime` does not check the `dayOfYear` of a `string` but of a `Date` object.
Setting the offset will change the timestamp. So `new Date("1582-10-04T03:24:00+0900")` effectively is the 276th day.
I think this is the desired functionality. `Moment.js` handles that the same way to my knowledge.

**Comment by tokiedokie** [comment]
@timreichen the following script produces the same result
It's confusing

---

javascript:
```
console.log((new Date("1582-10-04T03:24:00+0000")).getDate());
console.log((new Date("1582-10-04T03:24:00+0900")).getDate());
```
output:
```
4
4
```

**Comment by timreichen** [comment]
What timezone are you in? Be aware that `getDate` returns local timezone date.
I am in MESZ for example and get
```
4
3
```
The `+0900` doesn't set the date offset, it means that the date string is 9h ahead of UTC.
```
console.log((new Date("1582-10-04T03:24:00+0000")).toISOString());
console.log((new Date("1582-10-04T03:24:00+0900")).toISOString());
```
should give you 
```
1582-10-04T03:24:00.000Z
1582-10-03T18:24:00.000Z
```

**Comment by tokiedokie** [comment]
I'm in JST(+09:00)

In momentjs, when the system is set to JST, the following script produces the same result with or without parseZone()

```
var moment = require("moment");
var utc = moment("1582-10-04T03:24:00+0000"); // or moment.parseZone()
var jst = moment("1582-10-04T03:24:00+0900"); //or moment.parseZone()
console.log(utc.toDate());
console.log(jst.toDate());
console.log(utc.dayOfYear());
console.log(jst.dayOfYear());
```

**Comment by timreichen** [comment]
Get you now. I think `dayOfYear` function is fine, tests are missing timezone.
PR #7675
