### ISSUE TITLE
WeakRefs / FinalizationRegistry bugs?

### ISSUE THREAD

**Issue by trgwii** [denoland/deno#7674]
I was testing some of these new APIs out and it seems like Deno might be holding more references to JS objects than it should?

Running the below code with node, it outputs:
```
2020-09-25T11:50:06.491Z
2020-09-25T11:50:14.617Z meme
2020-09-25T11:50:14.617Z meme
2020-09-25T11:50:14.618Z meme
...
```

Signalling that GC has happened for each of the Foo instances, however, running the same file in Deno gives this:

```
2020-09-25T11:50:18.118Z
```

And no GC callback ever runs, which is quite interesting, I'm not sure if this could be a Deno issue or maybe caused by different V8 versions?

`node -p process.versions`:
```js
{
  node: '14.12.0',
  v8: '8.4.371.19-node.16',
  uv: '1.39.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.16.0',
  modules: '83',
  nghttp2: '1.41.0',       
  napi: '7',
  llhttp: '2.1.2',
  openssl: '1.1.1g',       
  cldr: '37.0',
  icu: '67.1',
  tz: '2020a',
  unicode: '13.0'
}
```

`deno --version`:
```
deno 1.4.1
v8 8.7.75
typescript 4.0.2
```

Edit: OS is Windows 10.0.19041

The code used in both node and deno tests:

```js
"use strict";

const reg = new FinalizationRegistry((key) => {
  console.log(new Date().toISOString(), key);
});

class Foo {
  n = Math.random();
}

console.log(new Date().toISOString());

setInterval(() => {
  reg.register(new Foo(), "meme");
}, 0);

```

**Comment by TradeIdeasPhilip** [comment]
I was also having trouble with WeakRef and FinalizationRegistry in Deno.  The details were very chaotic, so I wasn't able to create a good bug report.  It seems that sometimes just adding code like
```
const x = new WeakRef({});
const y = new FinalizationRegistry(() => {});
console.log(x, y);

```
was enough to make the system fail badly.  Sometimes the code would hang.  Sometimes I'd get a nonsense exception in the built in JavaScript code, before it ever got to my code.

This worked fine, suggesting that the APIs are available.
`console.log("WeakReference",` WeakRef, "FinalizationRegistry", FinalizationRegistry);

I'd love to know what you find out.

**Comment by TradeIdeasPhilip** [comment]
I tried again.  I'm still getting inconsistent results.  Some of that might be the Deno plugin for VS Code.  When I see the craziest errors, like breaking in the standard Deno code, I just restart VS Code and try again.

Something has changed and I think it is recent.  TypeScript can no longer find WeakRef or FinalizationRegistry!  It looks perfect in VS Code.  I can hover my mouse over an identifier (like "deref()") and the tooltip will show me the correct type info ("X | undefined" for a WeakRef<X>).  But when I try to run I get error messages.

If I type
`console.log("WeakReference", WeakRef, "FinalizationRegistry", FinalizationRegistry);`
or
`console.log("WeakReference", window.WeakRef, "FinalizationRegistry", window.FinalizationRegistry);`
into a *.ts file I see something like
```
Check file:///C:/Users/Philip%20Smolen/CVS_for_SmartCVS/TradeIdeas/cpp_alert_server/deno/overnight/CandleMain.js
error: TS2339 [ERROR]: Property 'WeakRef' does not exist on type 'Window & typeof globalThis'.
console.log("WeakReference", window.WeakRef, "FinalizationRegistry", window.FinalizationRegistry);
                                    ~~~~~~~
    at file:///C:/Users/Philip%20Smolen/CVS_for_SmartCVS/TradeIdeas/cpp_alert_server/deno/overnight/RawDataManager.ts:6:37

TS2339 [ERROR]: Property 'FinalizationRegistry' does not exist on type 'Window & typeof globalThis'.
console.log("WeakReference", window.WeakRef, "FinalizationRegistry", window.FinalizationRegistry);
                                                                            ~~~~~~~~~~~~~~~~~~~~
    at file:///C:/Users/Philip%20Smolen/CVS_for_SmartCVS/TradeIdeas/cpp_alert_server/deno/overnight/RawDataManager.ts:6:77

Found 2 errors.
```
when I try to run.

On the other hand, if I type
console.log("WeakReference", (window as any).WeakRef, "FinalizationRegistry", (window as any).FinalizationRegistry);
into a *.ts file I get what I expect,
`WeakReference [Function: WeakRef] FinalizationRegistry [Function: FinalizationRegistry]`

If I put either of the first two examples into a *.js file, I get the expected result, but I was hoping to use TypeScript!

VS Code version info:
Version: 1.50.1 (user setup)
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T15:06:15.712Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363

TypeScript version:  4.1.0-dev.20201019.  (If I'm reading that right, VS Code automatically downloaded something new in the last day.)

Deno version 1.4.6.  That's the current version.  I think I've been running this for a while.

Windows 10.

I would love to know the state of these Features.  Is it just a bug to fix, or a feature that's not ready yet?

**Comment by ry** [comment]
@trgwii I can repeat your failure but I don't know what is causing the discrepancy in behavior between Node and Deno. Deno isn't holding extra object references. Is it just that Node has tuned V8 to run the GC more often? Maybe @bnoordhuis has some idea.

@TradeIdeasPhilip Let's just deal with Deno behavior and not VS Code extension behavior in this issue. We are missing FinalizationRegistry and WeakRef typescript type declarations - I created an issue for that https://github.com/denoland/deno/issues/8051

**Comment by bnoordhuis** [comment]
Deno never calls `v8::Isolate::ClearKeptObjects()` - which isn't too surprising because there's no rusty_v8 binding for it. :-)

I'll open a rusty_v8 PR and see if I can find the right place in deno to slot in the call.

**Comment by TradeIdeasPhilip** [comment]
I'll start doing some tests from the Windows Power Shell or Linux command line.  The IDE has issues, but I still prefer it to the command line.

I can add one more detail, regarding the previous test.  If I run the test code listed above, Deno will hang.  Normally my test program asks for a lot of data, formats it, prints it, then exits.  I don't explicitly tell it to exit, Deno is smart enough to know when the last async is done.  But when I add `console.log("WeakReference", (window as any).WeakRef, "FinalizationRegistry", (window as any).FinalizationRegistry);`, Deno never exits.  Everything else seems to work.  I hit pause to make sure Deno was still alive.  (Sometimes VS Code thinks Deno is still running when it is not.)  Sure enough it was in an idle loop and the console responded to me (sorta).  I've attached a screenshot from that time.

![Screenshot (398)](https://user-images.githubusercontent.com/18409827/96640883-ba22a280-12d8-11eb-98fa-c2d9e48b9f3b.png)

If you need some test code, here's my first attempt at a cache manager.  In the C++ and Java versions I have to explicitly tell it to decrement the reference count.  I was hoping to avoid that because JavaScript is magic.  Obviously I haven't gotten very far in my testing, but the idea is pretty simple.

```
// I can't currently get this to work!  See https://github.com/denoland/deno/issues/7674 for more notes.

/**
 * This is like a normal Map, but the values are all stored as WeakRef objects.
 * This is NOT a WeakMap.  A WeakMap holds weak references to the keys but normal strong references to the values.
 * A CacheMap flips that around.
 *
 * The interface for CacheMap is purposely very similar to Map, so you don't have to learn something new.
 * 
 * The idea behind CacheMap is that the key is a short string that's easy to save or recreate.  The value
 * is expensive to recreate and uses a lot of memory, and is easy to share.  If someone is already holding
 * the object I want, it should be easy for me to get a pointer to the same object..  When the last person
 * lets go of the object, it will be eligible for automatic garbage collection.  When the system garbage 
 * collects the object, CacheMap automatically removes the entry.  If we have a lot of entries that have
 * keys and WeakRef objects, even if the WeakRef objects all point to undefined, that's still a memory leak.
 */
export class CacheMap<X extends object> {
  /**
   * This holds the data.
   * The WeakRef objects are completely hidden by this object.
   * The keys in map are exactly the same as the keys in this.
   */
  private map : Map< string, WeakRef< X > > = new Map();

  clear() : void {
    return this.map.clear();
  }

  /**
   * If the key is in the map, delete it and return true.
   * Otherwise return false and make no changes.
   * @param key To delete.
   */
  delete(key : string) {
    return this.map.delete(key);
  }

  /**
   * Return the item associated with this key.
   * Return undefined if nothing is associated with this key.
   * @param key To search for.
   */
  get(key : string) : X | undefined {
    const inMap = this.map.get(key);
    if (!inMap) {
      return undefined;
    }
    const result = inMap.deref();
    if (!result) {
      console.error("Unexpected missing data!", key);
    }
    return result;
  }

  private finalizationRegistry : FinalizationRegistry;

  private destructor(key : string) : void {
    const deleted = this.map.delete(key);
    if (!deleted) {
      console.error("Unexpected missing data!", key);
    } else {
      // This will eventually go away, but for now I want to see my data disappear.
      console.info("Successfully removed key!", key);
    }
  }

  constructor() {
    this.finalizationRegistry = new FinalizationRegistry(this.destructor.bind(this));
  }

  /**
   * Add this key value pair. 
   * If the key is already in the map, replace the old value with the new one.
   * @param key 
   * @param value 
   */
  set(key : string, value : X) {
    this.map.set(key, new WeakRef(value));
    this.finalizationRegistry.register(value, key);
    return this;
  }

  /**
   * Returns an iterator to a list of keys in insertion order.
   * Warning:  Values might automatically disappear between when you ask for this and when you call get()!
   */
  keys() {
    return this.map.keys();
  }
}

/**
 * This is a simple wrapper around CacheMap.  The format is more like Map because the template
 * takes two arguments.  The first argument, the key type, has to be a string.  This makes it
 * easy to switch between CacheMapS and Map.
 */
export class CacheMapS<Key extends string, Value extends object> extends CacheMap<Value> {

};
```

**Comment by TradeIdeasPhilip** [comment]
@ry said

> Let's just deal with Deno behavior and not VS Code extension behavior in this issue. 

My problems with the program hanging seems to be unrelated to VS Code and to the WeakRef code.  After adding more log statements I can see the code hanging on some MySQL requests.  Very strange.  I've tested the heck out of that part of the code, and the WeakRef stuff was my only recent change.  Sorry about that.

**Comment by kitsonk** [comment]
@bnoordhuis did denoland/rusty_v8#507 fix this?  Or is there more we need to do here other than update rusty_v8?

**Comment by bnoordhuis** [comment]
@kitsonk Deno needs to call `isolate.clear_kept_objects()` in the right place but I haven't figured out yet what the right place is. It's supposed to be called regularly, say every event loop iteration.

**Comment by 00ff0000red** [comment]
I was using a `FinalizationRegistry` to free Wasm memory when JS handles were GCed.

Suspiciously, the expected memory wasn't being freed, so I assumed that my memory offsets were incorrect and started attempted to debug the situation.

Eventually, I realized that Deno was simply never calling the callback.
Quite an unfortunate situation.
+1 to getting this handled soon.

**Comment by bnoordhuis** [comment]
Just calling `clear_kept_objects()` doesn't seem to fix the issue. I don't have a good hypothesis why not.
```diff
diff --git a/core/runtime.rs b/core/runtime.rs
index c9ecca9aa..765e653bb 100644
--- a/core/runtime.rs
+++ b/core/runtime.rs
@@ -515,6 +515,7 @@ impl JsRuntime {
       self.async_op_response(overflow_response)?;
       self.drain_macrotasks()?;
       self.check_promise_exceptions()?;
+      self.v8_isolate().clear_kept_objects();
     }
 
     // Dynamic module loading - ie. modules loaded using "import()"
```
That ensures `clear_kept_objects()` is called abundantly. Calling it whenever deno calls `perform_microtask_checkpoint()` doesn't work either. I'm afraid I'm out of ideas for now.

**Comment by cztomsik** [comment]
FYI I think this is the relevant part in nodejs https://github.com/nodejs/node/blob/8e8dea36cc98050371bdc2a3c462399b78a6c0f2/deps/v8/src/heap/mark-compact.cc#L2482

**Comment by bartlomieju** [comment]
This is most likely related to `PumpMessageLoop` API in V8, which will be implemented in https://github.com/denoland/rusty_v8/pull/706 and subsequently in Deno.

**Comment by trgwii** [comment]
I retested my initial code in Node `16.11.0` and now Node seems to have the same bug as Deno.
