### ISSUE TITLE
[Discussion]: Nodes that should be crawled for JSDoc tests

### ISSUE THREAD

**Issue by iykekings** [denoland/deno#7676]
This is in regards to #6124, we need to visit different nodes recursively to get their JSDoc.

**Comment by bartlomieju** [comment]
Discussed offline with @iykekings; for the first pass of #6124 we decided to extract tests only from functions.

**Comment by iykekings** [comment]
Since we are using visit, I added option to crawl
1. functions
2. classes
3. var declarations as far as their init is a function, class or object
4. Also methods inside classes and objects are crawled too
