### ISSUE TITLE
Unable to run deno script using a shebang on Linux

### ISSUE THREAD

**Issue by lpil** [denoland/deno#7700]
Hello! Thanks for this excellent project.

I have a deno script that I would like to be able to run from the command line by taking its name.  With node I would add a shebang to the top of the file like so:

```js
#!/usr/bin/env node
```
Here's the (non functional) deno version.
```js
#!/usr/bin/env deno run --allow-net
```
I'm unable to do this with deno because it requires additional arguments to be passed to the env, but this is not a standard env feature and as such this now no longer works on Linux.

Is there a way to work around this limitation of Linux and deno? It would be wonderful to be able to write command line programs using deno.

Thank you,
Louis

**Comment by lucacasonato** [comment]
Duplicate of https://github.com/denoland/deno/issues/5863

**Comment by lpil** [comment]
Hi @lucacasonato , while related this issue is not a dupliate of #5863

That issue is about read the shebang when running a deno script using `deno run -S scriptname`, this issue is about being able to specify scripts on non-OSX platforms when running the script directly i.e. `./my-script`.

A solution that resolves #5863 would not be sufficient to also resolve this issue.

It would be great to open this again so we can find a solution, thank you.

**Comment by lucacasonato** [comment]
Ah sorry

**Comment by nayeemrmn** [comment]
> Is there a way to work around this limitation of Linux and deno? It would be wonderful to be able to write command line programs using deno.

The workaround is to write:
```
#!/usr/bin/env -S deno run --allow-net
```
which is supported by `env` under GNU coreutils 8.30+ (Ubuntu 19.04+). It'll split the args for you and just work. For those that are using versions earlier than this, there's nothing Deno can or should do. This is entirely a limitation of Linux shebangs.

**Comment by lpil** [comment]
>  This is entirely a limitation of Linux shebangs.

Very much so! It is quite frustrating situation.

I was hoping there might be some way to get this working without the -S flag as it's not widely available yet. I understand if you only wish to support newer env versions.

**Comment by nayeemrmn** [comment]
@Ipil There's logically no way, sorry. The limitation literally doesn't leave any room for interpreters to implement their own solution like `-S`.
```
#!/usr/bin/env deno <nothing else can be put here or the Deno executable won't be found in the first place>
```

**Comment by lpil** [comment]
I thought perhaps a second line could be used to specify further information, like vim / perl / python / ruby's magical comments.

I understand you may not wish to do this, thank you for your time!

**Comment by b-fuze** [comment]
@lpil well, I wrote a hack for it that should work on a majority of older systems
```typescript
#!/bin/sh
//bin/true; exec deno run "$0" "$@"

function hello(name: string) {
  console.log(`Hello, ${ name }!`);
}

hello(Deno.args[0] ?? "stranger");
```
