### ISSUE TITLE
Integration test timeout_clear fails when machine resources are taxed

### ISSUE THREAD

**Issue by j4qfrost** [denoland/deno#7705]
When running this test with the entire suite, this fails. Running the test via ```cargo test js_unit_tests``` passes. I did a print out on the times and when running all the tests the elapsed time is about 12s which is a failure. Running with just the js_unit_tests the elapsed time is about 7s. Extending the timeout to 20s fixes the issue, but it seems like a hack. Is there a way to make the test more robust?

**Comment by j4qfrost** [comment]
Fixed https://github.com/denoland/deno/pull/7726

**Comment by Dygear** [comment]
Same issue on a Raspberry Pi 400. Given that it's a slower than normal CPU (But really pretty fast for a computer of it's class, about 15% faster than a Raspberry Pi 4.).

```
---- timeout_clear stdout ----
target_dir /home/pi/deno/target/debug
thread 'timeout_clear' panicked at 'assertion failed: end - start < Duration::new(10, 0)', cli/tests/integration_tests.rs:1943:3
stack backtrace:
   0: std::panicking::begin_panic
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:497
   1: integration_tests::timeout_clear
             at ./tests/integration_tests.rs:1943
   2: integration_tests::timeout_clear::{{closure}}
             at ./tests/integration_tests.rs:1914
   3: core::ops::function::FnOnce::call_once
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/ops/function.rs:227
   4: core::ops::function::FnOnce::call_once
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/ops/function.rs:227
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```
