### ISSUE TITLE
deno test doesnt work with --no-check

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#7709]
Since v1.4.2 `deno test` does not work with `--no-check` anymore.

```
/m/f/P/g/l/deno_s3 ❯❯❯ deno test --allow-net --allow-env --no-check
error: Cannot resolve module "file:///mnt/f9/Projects/github.com/lucacasonato/deno_s3/.deno.test.ts"
```

Example test file:

```ts
// foo_test.ts
import { assertEquals } from "https://deno.land/std@0.71.0/testing/asserts.ts";

Deno.test("test", () => {
  assertEquals(1 + 1, 2);
});
```

I have not bisected, but possibly related: #7621

cc @kitsonk @bartlomieju

**Comment by kitsonk** [comment]
Yeah, it is related to that. We don't have a `test --no-check` integration test, so we didn't catch it. I will fix it.

**Comment by kitsonk** [comment]
Gargh... This isn't super straight forward...

When we test, we create a "fake" module and insert it in the `global_state.file_fetcher` but the new `Graph` doesn't use the `global_state.file_fetcher` but instead creates its own, in an effort to start pulling out the file fetcher and eventually refactoring it out totally.  I've never been happy with the fake module, that should ultimately be a truly abstract module, but that will need to happen after other refactors.

So I think the most straight forward mechanism at the moment is to pass a reference to the `global_state` file fetcher, but that won't be the easiest I think as well, as it will require lifetime parameters.  Hrmph...

**Comment by caspervonb** [comment]
>  I've never been happy with the fake module, that should ultimately be a truly abstract module, but that will need to happen after other refactors.

I have a new parallel capable test runner that doesn't use the intermediate module that I'll raise for discussion soon'ish.

It's basically https://github.com/denoland/deno/pull/7165 with the test runner and reporter(s) moved to Rust.

**Comment by bartlomieju** [comment]
> When we test, we create a "fake" module and insert it in the global_state.file_fetcher but the new Graph doesn't use the global_state.file_fetcher but instead creates its own, in an effort to start pulling out the file fetcher and eventually refactoring it out totally.

@kitsonk there's a lot of interactions to consider if we were to stop using "global" file fetcher - especially how multiple file fetchers in single process would access/save to cache and how `--reload` flag would work in that situation. 

I believe we should go back to using the "global" file fetcher when wrapping up compiler refactor and address the problems with file fetcher afterwards (it's still on my radar).

@caspervonb I'm looking forward to seeing your idea.
