### ISSUE TITLE
[Question] Is It Possible to Write stdin to Sub Process Multiple Times?

### ISSUE THREAD

**Issue by ebebbington** [denoland/deno#7713]
Say i have a sub process, and i want to write 2 commands to stdin, is it possible?

```typescript
const p = Deno.run({
  cmd: [...}
  stdin: "piped",
  stdout: "piped"
})
await p.stdin.write(...)
const output1 = decoder(await p.output())
await p.stdin.write(...)
const output2 = decoder(await p.output())
```

**Comment by bartlomieju** [comment]
@ebebbington `p.output()` will read all output from subprocess and close its `stdout` pipe - you want to read manually using `p.stdout.read()` or wrapping it in a [`Buffer`](https://doc.deno.land/builtin/stable#Deno.Buffer)

**Comment by ebebbington** [comment]
@bartlomieju thanks :) i don't suppose you could provide an example? I'm having trouble finding the resources i need to have a play with it (and eventually get a solution), for example I'm not sure what to pass to `p.stdout.read` :/

My current actual example is:

```typescript
const command = `the command to run`;
const p = Deno.run({
  cmd: ... 
  stdin: "piped",
  stdout: "piped",
  stderr: "piped"
})
await p.stdin.write(new TextEncoder().encode(command));
await p.stdin.close(); // It seems this is needed, because the process just hangs, but i don't want to close stdin do i?
const rawOutput = new TextDecoder().decode(await p.output()))
```
But of course i want to do something like: (pseudo-code)
```typescript
const p = ...
await p.stdin.write('echo $HOME')
const output1 = p.output()
await p.stdin.write(`ls ${output1}`)
const output2 = p.output()

// and after many times writing and reading, i wanna close
await p.output()
await p.stderrOutput()
await p.stdin.close()
await p.close()
```

**Comment by ebebbington** [comment]
On top of this, i think it might be good to add some docs? I know i haven't found one example have have really struggled (maybe due to not understanding the Deno API as much as i thought), but i've also came across a few results on google where people have tried the same thing but never got a proper response

**Comment by ebebbington** [comment]
Also realised I have to close the stdin (`p.stdin.close()`) to actually read from aything, so i'm also unnsure how i'd 'open' it again (which i don't think is possible)

**Comment by nayeemrmn** [comment]
Is there a bug here? @ebebbington I think you have a better idea of how to read from `Deno.Reader`s now, is this issue okay?

**Comment by ebebbington** [comment]
I wouldn’t say so, and yeah I do have a better idea :) will close this issue

**Comment by ebebbington** [comment]
Hey @Schotsl, so unfortunately I don’t think my answer will be any help :/ instead of writing to stdin of the sub process, I connected a websocket client to a websocket server that was started by my specific sub process, and used that to send and receive messages

**Comment by Schotsl** [comment]
Thanks for the update! Sad to hear you never resolved the issue so I'm guessing this is still a missing feature or a bug :(

**Comment by nayeemrmn** [comment]
@Schotsl Try the help channel in our Discord: https://discord.gg/hXSwymy56J.

**Comment by Schotsl** [comment]
I got the help I needed and solved the issue, the simple solution was just adding `\n` to my command, so this line:

 ```await process.stdin.write(encoder.encode(`${command}`));```

became this:

```await process.stdin.write(encoder.encode(`${command}\n`));```

Way easier than expected tbh, but I'm hoping this will help somebody out in the future!
