### ISSUE TITLE
Cannot remap a transitive dependency to a local file

### ISSUE THREAD

**Issue by vovacodes** [denoland/deno#7723]
https://github.com/denoland/deno/pull/5050 introduced the logic that prohibits static imports of local modules from remote modules. While I understand the security issues it solves, I believe, it also makes impossible some nice and valid use-cases, in particular, remapping a transitive dependency to a local module using an import map.
Can we somehow allow this use-case?

**Comment by kitsonk** [comment]
This is a legitimate use case we should support. We should address it during #7225.
