### ISSUE TITLE
Getting Output from Deno.run Hangs If `stdin` is Not Closed

### ISSUE THREAD

**Issue by ebebbington** [denoland/deno#7727]
I have checked with all other `Deno.run` issues and whilst some are similar, they dont have the same issue

**Description**
I am creating a subprocess, and wanting to write to it and get output. Rise and repeat this X times

**Code I Am Using**
```typescript
const p = Deno.run({
  cmd: ["/Applications/Google Chrome.app/Contents/MacOS/Google Chrome", "--headless", "--crash-dump-dir=/tmp", "--virtual-time-budget=1000", "--repl", "https://chromestatus.com"],
  stdin: "piped",
  stdout: "piped",
  stderr: "piped"
})
await Deno.writeAll(p.stdin, new TextEncoder().encode(`window.location.href`))
for await (let line of readLines(p.stdout)) { // Hangs here
  console.log(line)
}
```
I can stop it from hanging by doing `p.stdin.close()` before the `for await`, but then i can't write anymore

**What I Want To Be Able To Do**
```typescript
const p = Deno.run({
  cmd: ["/Applications/Google Chrome.app/Contents/MacOS/Google Chrome", "--headless", "--crash-dump-dir=/tmp", "--virtual-time-budget=1000", "--repl", "https://chromestatus.com"],
  stdin: "piped",
  stdout: "piped",
  stderr: "piped"
})
let lines = []
await Deno.writeAll(p.stdin, new TextEncoder().encode(`window.location.href`))
for await (let line of readLines(p.stdout)) { // Hangs here
  lines.push(line)
}
await Deno.writeAll(p.stdin, new TextEncoder().encode(`window.location.href`))
for await (let line of readLines(p.stdout)) { // Hangs here
  lines.push(line)
}
console.log(lines) // [">>> { result: ... }", ">>>", "", ">>> { result: ... }", ">>>", ""]
await p.output()
await p.stderrOutputt()
await p.stdin.close()
await p.close()
```

**Comment by ebebbington** [comment]
Same result with the following example:
```
$ cat ask.sh
read -p "name" input
echo $input

$ cat a.ts
const p = Deno.run({
  cmd: ["bash", "ask.sh"],
  stdin: "piped",
  stdout: "piped",
  stderr: "piped"
})
await Deno.writeAll(p.stdin, new TextEncoder().encode(`window.location.href`))
for await (let line of readLines(p.stdout)) {
  console.log(line)
}
```
It hangs, but if you add `p.stdin.close()` before the `for await` line, it works

**Comment by ebebbington** [comment]
This only seems to be a problem when the sub process is **directly asking for input**

**Comment by ebebbington** [comment]
Tried it in Rust too (hoping to use Rust for this instead due to this issue) but i came across the same problem, though unsure if this is due to my inexperience with Rust (very very new to it)

**Comment by ElectroGamez** [comment]
Any updates on this? If there is a workaround available, can it be noted here? I'm running into the same issue.

**Comment by bartlomieju** [comment]
`Deno.run()` is now deprecated and `Deno.Command` is the recommended way of spawning subprocesses. I'm gonna close this issue.
