### ISSUE TITLE
Lint errors for rule "camelcase" in std/hash

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#7739]
[`camelcase` lint rule is ready to be merged](https://github.com/denoland/deno_lint/pull/302), however there are a few lint problems it causes in `std/`. Most of them have already been addressed in #7360, however `std/hash` still causes some errors and I don't see an easy way out of it:
```
(camelcase) Identifier 'Sha3_224' is not in camel case.
export class Sha3_224 extends Sponge {
             ^^^^^^^^
    at /Users/biwanczuk/dev/deno/std/hash/_sha3/sha3.ts:7:13

(camelcase) Identifier 'Sha3_256' is not in camel case.
export class Sha3_256 extends Sponge {
             ^^^^^^^^
    at /Users/biwanczuk/dev/deno/std/hash/_sha3/sha3.ts:19:13

(camelcase) Identifier 'Sha3_384' is not in camel case.
export class Sha3_384 extends Sponge {
             ^^^^^^^^
    at /Users/biwanczuk/dev/deno/std/hash/_sha3/sha3.ts:31:13

(camelcase) Identifier 'Sha3_512' is not in camel case.
export class Sha3_512 extends Sponge {
             ^^^^^^^^
    at /Users/biwanczuk/dev/deno/std/hash/_sha3/sha3.ts:43:13

(camelcase) Identifier 'Sha3_224' is not in camel case.
export { Sha3_224, Sha3_256, Sha3_384, Sha3_512 } from "./_sha3/sha3.ts";
         ^^^^^^^^
    at /Users/biwanczuk/dev/deno/std/hash/sha3.ts:3:9
```
We could of course ignore those diagnostics in the relevant files, but that's not the proper solution as users importing this file will get the same errors in their files. 

CC @caspervonb @magurotuna

**Comment by magurotuna** [comment]
We could rename `Sha3_224` to `SHA3_224` for example, so that the diagnostics won't be generated.
Referring to [sha3 - npm](https://www.npmjs.com/package/sha3), a class named `SHA3` is exported. Therefore in our case it'd be good to name `SHA3_224` or something like that.

**Comment by bartlomieju** [comment]
@magurotuna thanks for pointing that out. There's already a PR (#7258) that would remove `Sha3_*` completely in favor of WASM library, but your solution might be a good middle-ground before it happens.

**Comment by magurotuna** [comment]
Ah I missed that PR, then this problem seems like more complex than I thought. I'd say the practical way is that we adopt my solution for now to enable `camelcase` rule, and then we will discuss #7258 further

**Comment by Hamish-Bassett** [comment]
Should this ticket have #7258 as a linked pull request? Or should it be closed?

**Comment by bartlomieju** [comment]
Resolved in `deno_lint`.
