### ISSUE TITLE
Request: Allow ts_version to be run from anywhere

### ISSUE THREAD

**Issue by j4qfrost** [denoland/deno#7744]
It might be better in the long term to allow this function to run from anywhere within the deno directory. Something like this would work but depend on there being one parent being named deno:
```
pub fn ts_version() -> String {
  let mut manifest_dir =
    PathBuf::from(std::env::var_os("CARGO_MANIFEST_DIR").unwrap());
  let deno_root = Some(OsStr::new("deno"));
  while manifest_dir.file_name() != deno_root && manifest_dir.pop() {}
  manifest_dir.push("cli/tsc/00_typescript.js");
  std::fs::read_to_string(manifest_dir.into_os_string().to_str().unwrap())
    .unwrap()
    .lines()
    .find(|l| l.contains("ts.version = "))
    .expect(
      "Failed to find the pattern `ts.version = ` in typescript source code",
    )
    .chars()
    .skip_while(|c| !char::is_numeric(*c))
    .take_while(|c| *c != '"')
    .collect::<String>()
}
```

**Comment by bartlomieju** [comment]
@j4qfrost I don't really understand what you're suggesting. Does this solve some concrete problem?

**Comment by j4qfrost** [comment]
This lets me access the ts version without having to duplicate code to grab it from an external crate. Finding the path for the ts file varies because the depths are different, so I just opted to jump up to the root.

**Comment by kitsonk** [comment]
We are in the process of doing heavy refactoring on how we compile code (#7225), anything like this would need to wait, and even then, I am not sure what problem it is solving.

**Comment by j4qfrost** [comment]
Alright, seems like a non issue.
