### ISSUE TITLE
worker.addEventListener wrong type

### ISSUE THREAD

**Issue by crowlKats** [denoland/deno#7746]
```ts
worker.addEventListener("message", (msg) => console.log(msg.data));
```
gets me a `Property 'data' does not exist on type 'Event'.`
I checked lib.dom.d.ts on the typescript repo and there it is correct.
https://github.com/microsoft/TypeScript/blob/43b5fec3c04cf416c1298a4b449c4333e700edc2/lib/lib.dom.d.ts#L18650

**Comment by OhBonsai** [comment]
Hi, I would like to do some work on this. Could you @kitsonk get me up to speed quickly on this? :)
