### ISSUE TITLE
Missing Buffer functions (API)

### ISSUE THREAD

**Issue by HerryYT** [denoland/deno#7751]
Buffer lacks functions like: readIntLE/BE(offset, length).. readUIntLE/BE...

**Comment by lucacasonato** [comment]
Do you mean `Deno.Buffer`? It is based off the [Go Buffer](https://golang.org/pkg/bytes/#Buffer), not the Node `Buffer`. It is feature complete. You should likely be using Typed Arrays (Uint8Array, Uint16Array, ArrayBuffer, DataView).

**Comment by HerryYT** [comment]
I saw, but I think there are too many Buffersoul and it wd be better to make one, it's very confusing now

**Comment by lucacasonato** [comment]
Deno is explicitly not compatible with Node. We use the web standard typed arrays instead of the Node `Buffer`. Deno favors web standards instead of proprietary types wherever possible. `Deno.Buffer` is not the Deno equivalent of the Node `Buffer`.

**Comment by HerryYT** [comment]
I got it, no problem. Thank you for the time 👍
