### ISSUE TITLE
Deno Bundle causing undefined variable error

### ISSUE THREAD

**Issue by ryanwhite04** [denoland/deno#7761]
I'm using Deno to [bundle javascript imports](https://deno.land/manual/tools/bundler).

It works with no errors for all imports i've used apart from [mwc-select](https://github.com/material-components/material-components-web-components/tree/master/packages/select) which shows the following in a browser.

"Uncaught TypeError: Cannot set property 'BOTTOM' of undefined"

## To Reproduce
1. Install [Deno](https://deno.land/)
2. Run `deno bundle https://cdn.skypack.dev/@material/mwc-select select.js`
3. Serve a webpage with the following

```html
<script type="module" src="./select.js"></script>
<mwc-select></mwc-select>
```

## Expected behavior
There should be no errors in the browser upon viewing the page

## System Information
 - OS: Windows
 - Browser Chrome
 - Version 84.0.4147.135 (Official Build) (64-bit)
 - Typescript 3.9.7
 - Deno 1.4.2

## Additional context
The skypack module runs without any error if not bundled, so this seems to be an issue with Deno's bundling.

I get the same error when bundling from unpkg, and when I bundle this component along with all the other components.

This is the code causing the error specifically from the import of "@material/menu-surface/constants"
I've replace code that doesn't seem to be relevant with **[...]** but you can also find the full code at an issue I posted on the mwc-select github page [here](https://github.com/material-components/material-components-web-components/issues/1739)

```Javascript
System.register(
  "-/@material/menu-surface@v8.0.0-canary.096a7a066.0-jIFt5GoeO68rmIhSgqhj/dist=es2020,mode=raw/constants",
  [],
  function (exports_20, context_20) {
    "use strict";
    [...]
    var CornerBit, __esModule;
    var __moduleName = context_20 && context_20.id;
    return {
      setters: [],
      execute: function () {
        [...]
        // tslint:disable:object-literal-sort-keys
        [...]
        // tslint:enable:object-literal-sort-keys
        [...]
        exports_20("numbers", numbers);
        (function (CornerBit) {
          CornerBit[CornerBit["BOTTOM"] = 1] = "BOTTOM"; // This line gives the error: "Uncaught TypeError: Cannot set property 'BOTTOM' of undefined"
          [...]
        })(CornerBit || (exports_20("CornerBit", CornerBit = {})));
        [...]
        exports_20("default", null);
        exports_20("__esModule", __esModule = true);
      },
    };
  },
);
```

and this is the unbundled code from [UNPKG.com](https://unpkg.com/@material/menu-surface@7.0.0/constants.js) which is being bundled into the incorrect code above.

```Javascript
// tslint:disable:object-literal-sort-keys
[...]

// tslint:enable:object-literal-sort-keys
[...]
var CornerBit;
(function (CornerBit) {
    CornerBit[CornerBit["BOTTOM"] = 1] = "BOTTOM";
})(CornerBit || (CornerBit = {}));

export { CornerBit };
//# sourceMappingURL=constants.js.map

**Comment by kitsonk** [comment]
Ok, this is going to get complex...

Here is a minimum reproduction:

```js
var A;
(function (A) {
    A[A["A"] = 1] = "A";
})(A || (A = {}));
export { A };
```

Which [TypeScript transpiles to](https://www.typescriptlang.org/play?module=4&useJavaScript=true#code/G4QwTgBAgg3AUACgGYFcB2BjALgSwPZoQJQCUEA3nBNdANpS0BEUjAuhALwQCM7XzjeAF8SxCAB9xRKJwoiS8AKYAPAA54wWCtAhD4QA):

```js
System.register([], function (exports_1, context_1) {
    "use strict";
    var A;
    var __moduleName = context_1 && context_1.id;
    return {
        setters: [],
        execute: function () {
            (function (A) {
                A[A["A"] = 1] = "A";
            })(A || (exports_1("A", A = {})));
        }
    };
});
```

Which if you put a minimal loader in front of it, and you run it, you get:

```
error: Uncaught TypeError: Cannot set property 'A' of undefined
        A[A["A"] = 1] = "A";
                 ^
    at file:///test.js:20:18
```

Basically TypeScript is trying to be "smart" on how it exports the symbol, but it is making a mistake.  The odd thing is that it looks exactly like a TypeScript `enum` transpiled to JavaScript.  If I have the following input:

```ts
enum A {
  A = 1
}

export { A }
```

I will get the following [output](https://www.typescriptlang.org/play?#code/KYOwrgtgBAglDeAoKsoF4oEZEF9GOAA8AHAewCcAXBVHIA) from TypeScript:

```js
var A;
(function (A) {
    A[A["A"] = 1] = "A";
})(A || (A = {}));
export { A };
```

I will open an issue with TypeScript on this, but we are in the process of re-writing all of our bundling logic and won't be using the TypeScript compiler for the emit of bundles in the near future.  I will check this test case with the new bundler as well.

**Comment by kitsonk** [comment]
Actually, thinking about it, it might be an edge case with our implementation of the System loader.  I am going to try something before I open the issue with TypeScript.
