### ISSUE TITLE
writeFile vs writeFileSync

### ISSUE THREAD

**Issue by han-tyumi** [denoland/deno#7769]
When using `writeFile` to write data to a file which I've downloaded using `fetch`, I get a corrupted file, but when using `writeFileSync` I do not.

My use case can be found here: https://github.com/han-tyumi/tools/blob/master/src/installer.ts#L70.
The issue can be simplified to:
```ts
const url = 'https://update.code.visualstudio.com/1.49.2/linux-x64/stable'
const response = await fetch(url)
const buffer = await response.arrayBuffer()
const data = new Uint8Array(buffer)
await Deno.writeFile('./code-1.49.2.tar.gz', data)
```
If you then try to untar the downloaded file, you will not be able to because it is corrupted.
If you instead use `Deno.writeFileSync('./code-1.49.2.tar.gz', data)`, you will be able to.

I would not expect these results to be different between the two functions.

**Comment by jsejcksn** [comment]
@han-tyumi Will you please provide a complete example with all commands used?

I cannot reproduce this issue using the test below: `writeFile` and `writeFileSync` produce identical files.

Note: The download URL in your example is a redirect address, so I've used a static GitHub URL to a file of the same type instead.

`test.ts`:
```ts
import {assertEquals} from 'https://deno.land/std@0.71.0/testing/asserts.ts';
import {exists} from 'https://deno.land/std@0.71.0/fs/exists.ts';

Deno.test('Written files are identical', async () => {
  const filePath = 'deno-1.4.2.tar.gz';
  const filePathSync = 'deno-1.4.2-sync.tar.gz';

  try {
    const url = 'https://github.com/denoland/deno/archive/v1.4.2.tar.gz';
    const response = await fetch(url);
    const responseBuffer = await response.arrayBuffer();
    const responseData = new Uint8Array(responseBuffer);

    await Deno.writeFile(filePath, responseData);
    Deno.writeFileSync(filePathSync, responseData);

    const data = await Deno.readFile(filePath);
    const dataSync = await Deno.readFile(filePathSync);

    assertEquals(data, dataSync);
  }
  finally {
    for (const fPath of [filePath, filePathSync]) {
      if (await exists(fPath)) await Deno.remove(fPath);
    }
  }
});
```

output:
```
% deno test --allow-net --allow-read=. --allow-write=. test.ts
running 1 tests
test Written files are identical ... ok (6363ms)

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out (6364ms)
```

**Comment by han-tyumi** [comment]
@jsejcksn Thank you for confirming this.
I just ran some additional tests and it appears to be an issue with that particular URL.
When using either function, sometimes the file would be corrupted and others not.
It must've been pure coincidence that I was only seeing the issue when using the asynchronous write.
Apologies for not seeing this earlier.
I think I can safely close this issue and will instead look into why this is happening with this particular URL.
