### ISSUE TITLE
Proposal: std/jwt

### ISSUE THREAD

**Issue by timreichen** [denoland/deno#7771]
As there was a discussion about different specs including JSON web tokens [here](https://github.com/denoland/deno/issues/4203) and there is a [3rd party module](https://deno.land/x/djwt)  implementation at the moment, I think it would be an enrichment to `std` to have JWT included.

What are your thoughts on that?

**Comment by axetroy** [comment]
JWT depends on the crypto (SHA256) module.

So again, implement the crypto module before implement jwt.

**Comment by timonson** [comment]
Hi @axetroy sha256 and sha512 already exist in std: https://deno.land/std@0.69.0/hash/sha256.ts

I am the author of [djwt](https://github.com/timonson/djwt) and would love to help moving jwt to std.

**Comment by timreichen** [comment]
@timonson awesome!
I had a look at your module, looks really good! Though some structural changes and function renames will be needed to be well-aligned with `js` and deno `std` conventions. I would be glad to help you with that.

@ry @bartlomieju would you be in favor of that integration?

**Comment by ry** [comment]
Happy to have it, patches welcome.

**Comment by timonson** [comment]
@timreichen I have the same username on the discord channel and I would love to hear more about your perspective of these things. So if you can, please dm me in the following days.
