### ISSUE TITLE
Add deno test --no-run

### ISSUE THREAD

**Issue by nayeemrmn** [denoland/deno#7775]
- `deno cache foo.ts bar.ts --test` -> `deno cache foo.ts bar.ts <...files captured by "deno test">`
- `deno cache foo.ts bar.ts --test=baz/,qux/` -> `deno cache foo.ts bar.ts <...files captured by "deno test bar/ qux/">`

Alternatively `deno test --no-run` (`cargo` has both).

EDIT: Went with the second option `deno test --no-run` to avoid the awkward flag value for `--test=dir1,dir2`.

**Comment by nayeemrmn** [comment]
@bartlomieju Can you reopen this? I don't have the button.

**Comment by bartlomieju** [comment]
@nayeemrmn I'm not sure about the proposed flag values, seems a bit complex and error prone to capture "regular", "worker" and "test" files in a single command.

How about supporting only a single "lib" type in a single invocation?
```
deno cache foo.ts
deno cache --test bar/  // files captured by "deno test bar/"
deno cache --worker foo.worker.ts
```

CC @kitsonk
