### ISSUE TITLE
Add REPL

### ISSUE THREAD

**Issue by kyranet** [denoland/deno#779]
It would be very nice to have a [REPL](https://en.wikipedia.org/wiki/Read%E2%80%93eval%E2%80%93print_loop) in deno, which would help us to test code quickly. Currently, it exits the process with error code 1 and the message "No input script specified.".

**Comment by ry** [comment]
Yes definitely. I’d like to wait until a couple of important refactors are landed before trying to do the REPL: #733 and #721

There’s some debate as to whether we should use a readline/repl library from rust or develop our own in JS (as we did in node). I am leaning towards using a rust lib...

**Comment by ry** [comment]
Both of the above mentioned issues are now solved. I'm open to patches for REPL now.

Thoughts:
- I think this should be done using a Rust readline crate (e.g. https://github.com/kkawakam/rustyline).  Discuss in this issue first which crate you would use. 
- I am open to a pure JS implementation, but skeptical that this can be done more easily than with a rust lib.
- Windows must be supported.
- Each eval could be done using [`Isolate::execute`](https://github.com/denoland/deno/blob/b635553fd7eaca4bd27c4242935984bdb8e9365f/src/isolate.rs#L118)https://github.com/denoland/deno/blob/master/src/isolate.rs#L118
- We don't need to support TS for the first version.

**Comment by cedric05** [comment]
will try to implement

**Comment by cedric05** [comment]
came across https://github.com/sfackler/cargo-tree, which will print dependencies in tree, will try to change build files.

**Comment by cedric05** [comment]
using rustyline i created a repl loop, but i'm not able to import any deno modules/functions defined in deno.ts . how can we import them from pure js runtime ?
@ry

**Comment by ry** [comment]
@cedric05 cool! we will have to hook into the ES module import hooks in V8 or pass the input thru TS... if you upload your patch as a PR, I’ll take a look and provide some more concrete guidance

**Comment by cedric05** [comment]
i can raise pr, but this is half baked

**Comment by ry** [comment]
@cedric05 that’s fine - just add WIP to the title

**Comment by cedric05** [comment]
raised https://github.com/denoland/deno/pull/947. build will because of not having third_party FYI

**Comment by kitsonk** [comment]
This can be closed.  We should handle any enhancements to the REPL under different issues.
