### ISSUE TITLE
Assertion examples not working

### ISSUE THREAD

**Issue by jero-at-github** [denoland/deno#7801]
The following example mentioned in the documentation doesn't work:
https://deno.land/manual/testing/assertions

```
import { assert } from "https://deno.land/std@0.72.0/testing/asserts.ts";

Deno.test("Test Assert String Contains", () => {
  assertStringContains("Hello World", "Hello");
});
```

```
error: TS2304 [ERROR]: Cannot find name 'assertStringContains'.
```

**Comment by TTtie** [comment]
Hi, according to your provided example, you're missing an `assertStringContains` import in your code - import it and the example will work.

**Comment by jero-at-github** [comment]
Sorry... my bad, stupid failure, thanks for quick response!
