### ISSUE TITLE
deno upgrade doesn't update Cargo state to match new reality

### ISSUE THREAD

**Issue by nabijaczleweli** [denoland/deno#7802]
AFAICT `cargo install deno` is a supported way to install the binary, and `deno upgrade` is a supported way to update it.

However the updater doesn't update `~/.cargo/.crates.toml` so the on-disk binary is of a different version than what is stated, which confuses users. You probably want to either preferably (a) update this state with the new version or otherwise (b) purge it.

Downstream issue: https://github.com/nabijaczleweli/cargo-update/issues/146

**Comment by kitsonk** [comment]
`cargo install deno` is a [way to install Deno](https://deno.land/#installation).  Very few people should be installing Deno from source though, `deno upgrade` is not updating Deno from source, and putting all the cargo infrastructure in the binary to be able to update it is non-sensical for the minority of people who would installing that way.

A simple note in the documentation that if you are building from source, that `deno upgrade` would _invalidate_ your source installation is sufficient.
