### ISSUE TITLE
Warm up snapshot

### ISSUE THREAD

**Issue by ry** [denoland/deno#781]
Optimize cold startup - we should see an improvement in the benchmark (See `tools/benchmark.py`)

maybe running thru the unit tests is a good way to warm it up.

A good solution to this issue will only touch code in  `//libdeno/`.

Hint 1: warm up execution should take place approximately here: https://github.com/denoland/deno/blob/3ad48bdb3e6372f55579808535ce2c17809178ff/libdeno/snapshot_creator.cc#L35-L36

Hint 2: here's an example from the V8 tests of how to do warm ups:
https://github.com/denoland/deno_third_party/blob/09c4885d0bb302c7c0547763bf07485578567251/v8/test/cctest/test-serialize.cc#L1245-L1309

**Comment by kevinkassimo** [comment]
(Warning: I'm not familiar with v8)
It seems that the two example tests from V8 are [skipped](https://github.com/denoland/deno_third_party/blob/09c4885d0bb302c7c0547763bf07485578567251/v8/test/cctest/cctest.status#L217-L218) a while ago. Stuff has been moved to [`mksnapshot.cc`](https://github.com/denoland/deno_third_party/blob/09c4885d0bb302c7c0547763bf07485578567251/v8/src/snapshot/mksnapshot.cc) ([commit](https://github.com/v8/v8/commit/5f9af1e7b56846950f134a198d150822e75337b6)) and the old API has been dropped.

**Comment by ry** [comment]
@kevinkassimo good info.

One other thought I had on this: it would be nice to add a new native function
```
libdeno.write_snapshot_and_exit("snapshot.bin")
```
then we can call it from `js/unit_test.ts`

**Comment by piscisaureus** [comment]
Depends on #814.

**Comment by bartlomieju** [comment]
Current benchmarks:
![zrzut ekranu 2019-02-12 o 19 33 01](https://user-images.githubusercontent.com/13602871/52659183-0ced6980-2efd-11e9-84d2-e9df129b8983.png)

@ry is this still relevant?

**Comment by ry** [comment]
Yes, still an issue. We recently fixed #814 - which was a blocker for this. 

Our warm startup time is very good - 0.01 seconds as shown above. But the cold startup is quite bad - at 0.6 seconds. By storing JIT optimized code in the snapshot, I hope we can reduce that number.

**Comment by kitsonk** [comment]
Yes, Ry and I have been chatting. There are some ideas and we have reached put to the TypeScript team directly to see if we can figure out the best way to optimise startup.

**Comment by ry** [comment]
In #3644 @kitsonk introduced oldProgram  which is built at compile time. This effectively warms up the compiler.
