### ISSUE TITLE
new Request(...) ignores url property

### ISSUE THREAD

**Issue by bnoordhuis** [denoland/deno#7836]
```
> new Request(undefined, { url: "https://deno.land/" });
Request {
  _bodySource: "",
  _stream: null,
  headers: Headers {},
  method: "GET",
  url: "",              // <- WRONG
  credentials: "omit"
}
```
https://github.com/denoland/deno/blob/6b8aef5103e6c77cc89ae4c7da959b39b1c4af4a/op_crates/fetch/26_fetch.js#L973-L974

**Comment by bnoordhuis** [comment]
Apologies, I retract this bug report. I believe the real bug is that `new Request(undefined)` should throw an "invalid URL" TypeError.

**Comment by nayeemrmn** [comment]
In browsers, the `undefined` gets stringified. Seems easier.

**Comment by bnoordhuis** [comment]
FWIW, Firefox 81.0.1 throws an "undefined is not a valid URL" TypeError.

**Comment by lucacasonato** [comment]
> In browsers Chrome, the undefined gets stringified. Seems easier.

That sounds like a Chrome bug:

https://fetch.spec.whatwg.org/#dom-request says first param may be a string, otherwise it must be asserted to be a `Request` object. I assume that means throw a TypeError if it is not one of the two.

**Comment by lucacasonato** [comment]
> FWIW, Firefox 81.0.1 throws an "undefined is not a valid URL" TypeError.

Actually can't reproduce on 81.0. For me it does the same as Chrome (which does the same as Safari)

**Comment by lucacasonato** [comment]
So it seems the stringified undefined is intended behavior:

![image](https://user-images.githubusercontent.com/7829205/95188535-67e26d00-0781-11eb-96ff-6d946f28f2bf.jpeg)
