### ISSUE TITLE
new Request(undefined).url should return "undefined" 

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#7837]
See https://github.com/denoland/deno/issues/7836

This is what Chrome, FF, and Safari do, and it is intended behaviour:

- The constructor takes a union type https://fetch.spec.whatwg.org/#requestinfo
- Here's how to process a union type https://heycam.github.io/webidl/#es-union
- Which falls through to step 12
- Which sends us to https://heycam.github.io/webidl/#es-USVString
- Which sends us to https://heycam.github.io/webidl/#es-DOMString
- Which sends us to https://tc39.es/ecma262/#sec-tostring
- Which returns the string "undefined"
- So we process the request constructor with the string input, which takes us to step 6 https://fetch.spec.whatwg.org/#dom-request

**Comment by nayeemrmn** [comment]
```diff
- new Response(undefined).url should return "undefined"
+ new Request(undefined).url should return "undefined"
```

**Comment by wperron** [comment]
for the sake of clarity, both FF and Chrome stringify `undefined` and interpret it as a relative url when doing `new Request(undefined)`
