### ISSUE TITLE
"test" output from `deno test` seems redundant

### ISSUE THREAD

**Issue by ebebbington** [denoland/deno#7840]
**What Am I Talking About**
1.  You have a test file
2. You run the tests
3. You see the output, marked bit below is what i'm talking about
```
test My function returns true when it works ... ok (2ms)
^^^^ this bit

1 tests; 1 passed; 0 failed; ...
```

**What is this issue about**
It feels redundant to have the "test" bit display, because we already know it's a test as we're running `deno test` - and i don't think many other places do this, if any.

**Comment by yacinehmito** [comment]
> i don't think many other places do this, if any.

The output of `deno test` mirrors the output of `cargo test`, from Rust. It is the exact same formatting.

**Comment by ebebbington** [comment]
> @ebebbington Can you give an example of how you think it should be formatted?

@ry This is how im kinda thinking, in terms of readabillity

*Note this is all my own opinion and how I feel, i'm purely trying to think of UX*

```
running 2 tests from file:///D:/.../a.ts
getUser() ...
  returns false ... ok (22ms)
  returns true ... ok (15ms)
name ...
  is Edward ... ok (13ms)
  
running 1 test from file:///D:/.../b.ts
getAdmin()
  returns true ... ok (12ms)

test result: ok. 3 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out (133ms)
```

Note the lack of:

- `ok (20ms)`: Feel this in reality doesn't provide anything on top if the way it's added to the output not feeling pretty. I cant imagine someone finding the execution time of a whole 'suite' useful, where they could just tally up each individual test. I also feel most people would want to check execution time **per test case**, if a test case has the time, then why the need for the time for suites? You'd usually want to ask yourself "Ok im just going to check is any tests take longer than they should... hmmm the <test case> takes 13000ms, whereas all other test cases for the <test suite> take about 1100ms
- `test` prefix: i mean it's obvious i guess, we know it's a test - i didn't prefix my test cases with "test" so why is it even there. Adds uncessary characters to the output leading to a more 'bunched' output

And note the addition of:

- newline for every test file **after** the first one: i really think this improved readabillity, so the output isn't so 'bunched'

**Comment by ebebbington** [comment]
Compare this: https://github.com/denoland/deno/issues/7840#issuecomment-942744927

With this:

```
running 8 tests from file://.../tests.ts
close()
    Should close the server ... ok (47ms)
    Should not error if server is not set or not defined ... ok (17ms)
    Should not error if server is already closed ... ok (4ms)
on()
    Registers callbacks for the name ... ok (11ms)
    Type checks pass when using generics for channels ... ok (17ms)
to()
    Should send a message to all clienta ... ok (31ms)
    Should send a message to a specific client ... ok (32ms)
run()
    Runs the server ... ok (33ms)

test result: ok. 8 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out (286ms)
```

**Comment by bartlomieju** [comment]
This was done in v1.21
