### ISSUE TITLE
Writing a text file - TS2339 Property 'then' does not exist on type 'void' in example code

### ISSUE THREAD

**Issue by makohn** [denoland/deno#7841]
**Description**

`Promise.then()` is invoked although the promise has been handled by `await`.

Error: `error: TS2339 [ERROR]: Property 'then' does not exist on type 'void'.`
Docs: https://deno.land/manual@v1.4.4/examples/read_write_files#writing-a-text-file

**To Reproduce**

```typescript
// deno run --allow-write write.ts

const write = await Deno.writeTextFile("./hello.txt", "Hello World!");

write.then(() => console.log("File written to ./hello.txt"));
```

**Actual behavior**

```
$ deno run --allow-write write.ts
error: TS2339 [ERROR]: Property 'then' does not exist on type 'void'.
write.then(() => console.log("File written to ./hello.txt"));
      ~~~~
```

**Expected behavior**

The message `File written to ./hello.txt` is logged to the console after the text has been written to the file.

**Deno version**

```
$ deno --version
deno 1.4.4
v8 8.7.75
typescript 4.0.3
```

**Comment by Soremwar** [comment]
@makohn This is the expected behavior.

After you `await` that operation, the result is no longer a promise. I'd you want to chain a `.then` function to `readTextFile`, you do so in the same line it is executed.

Otherwise just console.log what you want without `then`. Await will finish the write of the file and only then execute the code that follows.

**Comment by makohn** [comment]
@Soremwar Thanks for the clarification. I refer to [this](https://deno.land/manual@v1.4.4/examples/read_write_files#writing-a-text-file) example from the docs. I think the example should then be replaced with one of your variants, shouldn't it?

**Comment by Soremwar** [comment]
@makohn Could you point me to that example?
