### ISSUE TITLE
Deno.run options for shell control

### ISSUE THREAD

**Issue by josh-hemphill** [denoland/deno#7847]
At the moment, when running on windows, I seem to be locked in to using the Win32 CMD shell, which seems to be having issues running npm. I'm currently using Git-Bash which has all the correct environment variables/path set up, so being able to specify a shell would be really useful.

If I'm not just missing something and there's a consensus on what the api should be, I'd be happy to put in the leg work to create a pull request.

**Comment by kitsonk** [comment]
cc/ @piscisaureus @bnoordhuis

**Comment by bnoordhuis** [comment]
@josh-hemphill Apologies if I misunderstand your question but doesn't this work?
```js
Deno.run({ cmd: ['cmd.exe', '/d', '/s', '/c', '"npm ls"'] }) // note the double quotes
```

**Comment by josh-hemphill** [comment]
Thanks. I think I can use that for my purposes. However, it only sort of works. It always seems to return error codes, especially if I try it in the REPL. 

Do you think adding something to the docs about how the right way to use other shells might be warranted?

**Comment by bnoordhuis** [comment]
More documentation is always good, pull request welcome.

What kind of errors do you see?

**Comment by josh-hemphill** [comment]
In REPL it would just return 
```
'\"npm ls\"' is not recognized as an internal or external command,
operable program or batch file.
```
and in code `cmd.exe` would always return the expected output but with `{ success: false, code: 1 }`
and with `bash` it would also return the expected result but with a similar output of `{ success: false, code: 127 }`
