### ISSUE TITLE
Add shorter aliases for permission flags

### ISSUE THREAD

**Issue by max-pub** [denoland/deno#7852]
Using the deno CLI is very verbose right now.
```deno run --allow-read --allow-write code.js```

could maybe simplified into something like
```deno -rw code.js```

- please make the ```run``` keyword optional (as in the dart CLI)
- please consider shortcuts for ```--allow-read```, ```--allow-write```, ```--allow-net```

this could even improve security, as many people probably use the catch-all ```-A``` even for just 1 or 2 permissions

**Comment by crowlKats** [comment]
`run` was optional in the past, but this was removed.

**Comment by kitsonk** [comment]
It is more complex than that `run` was optional, `run` was required, `run` was optional, and then run was required.  The final decision was made in #4701 after quite a lot of discussion.

As for shorter flags... well I am sort of 🤷  personally, but we can see what others say.

**Comment by bartlomieju** [comment]
I'm against this proposal, I'd much rather see a way to express permission flags in some kind of metadata file instead of adding one-letter aliases. I think @ry is one the same page

**Comment by bartlomieju** [comment]
Not much going on in this issue, so I'd err on keeping status quo and close this issue.
