### ISSUE TITLE
Label issues that are relevant for Hacktoberfest

### ISSUE THREAD

**Issue by ravimashru** [denoland/deno#7854]
It would be cool to have issues that can be solved during the hackathon on 23 October labeled with "hacktoberfest" so that they are easy to discover.

//cc @michael-spengler

**Comment by kitsonk** [comment]
At this point, we are not participating in Hacktoberfest.

**Comment by ry** [comment]
Please see the ["Good First Issue"](https://github.com/denoland/deno/labels/good%20first%20issue) label.

**Comment by F3n67u** [comment]
will deno participate the hacktoberfest this year？this year's event has just started.

**Comment by kitsonk** [comment]
Unlikely.
