### ISSUE TITLE
WebGPU Implementation

### ISSUE THREAD

**Issue by crowlKats** [denoland/deno#7863]
I have been looking at the [WebGPU spec](https://gpuweb.github.io/gpuweb/) and the [`wgpu` crate](https://github.com/gfx-rs/wgpu-rs) for a possible WebGPU implementation which arose from a discussion on the discord server.
Problem is, how would we handle the window on which the user would draw to? Adding a window manager to deno would definitively not be a viable solution. `wgpu-rs` does actually allow to have a windowless setup, but i think most end users would actually want a way to have some sort of window. A window is also required for usage of swap chains; which, once again, many users would want.

**Comment by ry** [comment]
Glad you're looking into this. I was imagining we would start with a windowless setup. The goal is to run tensorflow.js's WebGPU backend.
https://github.com/tensorflow/tfjs/tree/master/tfjs-backend-webgpu

**Comment by 0kku** [comment]
> i think most end users would actually want a way to have some sort of window

[citation needed]

I think the more useful use-case would be ML (TF with WebGPU backend), server side image processing, and other GPU compute tasks. I'm not sure how much sense it would make to write a UI in raw wgpu when you're writing JS/TS. Seems like a questionable pairing, and people probably should just host a PWA on the localhost and render in their browser if they want a GUI.

**Comment by crowlKats** [comment]
@0kku good point

**Comment by kitsonk** [comment]
Ref #5701, #1629

**Comment by crowlKats** [comment]
https://github.com/gfx-rs/wgpu/issues/869

**Comment by crowlKats** [comment]
I came up with a solution for adding window support for webgpu without adding any other deps.
This would require plugins to have access to the resourcetable tho.
The community (or we in std) would create plugins for rust window handlers. The surface which you pass to wgpu is created with a param that needs to be a [`raw_window_handle::HasRawWindowHandle`](https://docs.rs/raw-window-handle/0.3.3/raw_window_handle/trait.HasRawWindowHandle.html) (which is a standarized way to get a raw window handle by the different rust window mangers). We would have a deno property on the descriptor for `GPU.requestAdapter` (like on workers) where you could pass a rid for such a `HasRawWindowHandle`.

**Comment by chances** [comment]
Considering the open PR, shall I formally abandon [chances/deno-wgpu](https://github.com/chances/deno-wgpu)?

**Comment by crowlKats** [comment]
@chances would make sense

**Comment by cztomsik** [comment]
Hey, not sure where to ask, is this going to be optional somehow? It seems like quite a big feature, including WSGL parser, compiler, there's some runtime memory overhead as well. I'd expect this to be a native plugin. Webview was also possible with plugin so why not this?

**Comment by lucacasonato** [comment]
@cztomsik This is a Web API. We implement these out of the box, without the need for external plugins (see `fetch`, `TextEncoder`, etc). Deno is modular, so if you want to build a runtime that does not contain WebGPU, that is totally possible. Deno however has shipped this experimental feature feature in 1.8.0. We are hoping to be able to reduce the runtime memory overhead in the coming weeks (the overhead is about 1MB of extra heap). It will not be optional in the Deno binary that we ship.

**Comment by cztomsik** [comment]
Unless something changed recently, WebGPU is still just working name for future standard. There is no initial release yet and support is very basic even in latest browsers:
![image](https://user-images.githubusercontent.com/3526922/110692033-2fd6ce80-81e6-11eb-863d-778dcb266358.png)
![image](https://user-images.githubusercontent.com/3526922/110692101-4846e900-81e6-11eb-8e46-369c819b75d0.png)
![image](https://user-images.githubusercontent.com/3526922/110692146-509f2400-81e6-11eb-9781-79fd56efe5d3.png)

**Comment by lucacasonato** [comment]
@cztomsik That is why it is _experimental_, and locked behind the `--unstable` flag. We are very aware that it is not stabilized anywhere yet - it is a highly unstable API, and the spec is far from complete. It is implemented in Chrome Canary behind a flag, in Firefox Nightly behind a flag, and in Safari TP and Safari stable behind a flag. This API will land sooner or later, and it opens up some amazing possibilities for out of the box general purpose GPU accelerated processing (for example ML inference and learning).

**Comment by felipetesc** [comment]
What about winit binding to Deno?

**Comment by birkskyum** [comment]
Times are changing, and WebGPU is enabled by default in Chrome. Can this be reopened for a discussion around this in the present context?

**Comment by birkskyum** [comment]
- https://github.com/denoland/deno/pull/20812

**Comment by felipetesc** [comment]
> I came up with a solution for adding window support for webgpu without adding any other deps.

Perhaps this is out of the scope, but what about ressurrecting the project https://github.com/denosaurs/pane, or to create winit bindings. winit works well with wgpu. rust-windowing also has the repo https://github.com/rust-windowing/softbuffer which would allow creating 2D buffer/image, and would help on https://github.com/denoland/deno/discussions/3234 .

**Comment by eliassjogreen** [comment]
> > I came up with a solution for adding window support for webgpu without adding any other deps.
> 
> Perhaps this is out of the scope, but what about ressurrecting the project [denosaurs/pane](https://github.com/denosaurs/pane), or to create winit bindings. winit works well with wgpu. rust-windowing also has the repo [rust-windowing/softbuffer](https://github.com/rust-windowing/softbuffer) which would allow creating 2D buffer/image, and would help on #3234 .

Totally! I think it would not require much to bring back pane now that webgpu support is coming back.
