### ISSUE TITLE
GlobalState should be a global variable

### ISSUE THREAD

**Issue by ry** [denoland/deno#7872]
Currently GlobalState is created in many places and passed through many functions. But according to the name, and as far as I can tell, it represents Global State - state shared between all workers/contexts inside the CLI. Therefore we should create a proper static global variable that holds GlobalState. Everywhere there's a function that has a `GlobalState` parameter, the parameter should be removed and `crate::GLOBAL_STATE` should be used instead.

By using a global static variable `crate::GLOBAL_STATE`, we can use the type system to ensure the state is actually global. Such a construct is useful - there are truly global states - for example has the NO_COLOR environmental variable been supplied or not? It would be nice to be able to reference `crate::GLOBAL_STATE.no_color`.

```
> rg GlobalState::new cli/
cli/module_graph.rs
604:    let global_state = GlobalState::new(Default::default()).unwrap();

cli/main.rs
167:  let global_state = GlobalState::new(flags)?;
193:  let global_state = GlobalState::new(flags.clone())?;
226:  let global_state = GlobalState::new(flags)?;
248:  let global_state = GlobalState::new(flags)?;
291:  let global_state = GlobalState::new(flags)?;
329:  let global_state = GlobalState::new(flags.clone())?;
424:  let global_state = GlobalState::new(flags)?;
432:  let global_state = GlobalState::new(flags.clone())?;
464:  let global_state = GlobalState::new(flags.clone())?;
496:    let gs = GlobalState::new(flags.clone()).unwrap();
523:  let global_state = GlobalState::new(flags.clone())?;
541:  let global_state = GlobalState::new(flags.clone())?;

cli/global_state.rs
273:    GlobalState::new(flags::Flags {
```

**Comment by bartlomieju** [comment]
I still believe we shouldn't make `GlobalState` a global variable. Making it a global variable will significantly complicate test setup - right now, we're creating `GlobalState` struct on demand as needed. 

The main problem with this struct is that ongoing refactors all depend on what's going on in `GlobalState` - we keep `TsCompiler`, `InspectorServer`, as well as `SourceFileFetcher` - all of those structs are pretty much in flux or will be in flux in the coming days.

Naming of this struct is a bit unfortunate and renaming it to `CliState` might be enough for now. I would rather not undertake this refactor at this point of time - I have a feeling it would be a net negative.

**Comment by ry** [comment]
Ok thanks for the explanation. I concede it's useful to change that for tests and that we shouldn't change this while we're refactoring module_graph/tsc/file_fetcher.
