### ISSUE TITLE
performance.measure throws when measuring from navigation by providing undefined startMark

### ISSUE THREAD

**Issue by jsejcksn** [denoland/deno#7876]
Attempting to measure from navigation by supplying `undefined` for `startOrMeasureOptions` results in the following error:

```
error: Uncaught TypeError: Options cannot be passed with endMark.
    at Performance.measure (deno:cli/rt/40_performance.js:254:17)
    at file:///main.ts:6:13
```

Code to reproduce (works in supported browsers):

```ts
const markerName1 = '1';
const markerName2 = '2';
performance.mark(markerName1);
performance.mark(markerName2);
performance.measure('measure between markers', markerName1, markerName2);
performance.measure('measure from navigation', undefined, markerName2);
console.log(performance.getEntriesByType('measure'));
```

Spec:
https://w3c.github.io/user-timing/#dom-performance-measure

Source: https://github.com/denoland/deno/blob/d8879feb8c832dbb38649551b1cb0730874f7be6/cli/rt/40_performance.js#L247-L323

**Comment by kitsonk** [comment]
It is a mistake in my implementation of the spec.  It says:

> 3.1.3.1 If startOrMeasureOptions is a non-empty PerformanceMeasureOptions object,

It isn't checking if it is a non-empty object (which is the default value of the argument). Line 252 should be something like this:

```ts
if (startOrMeasureOptions && typeof startOrMeasureOptions === "object" && Object.keys(startOrMeasureOptions).length) {
```

And it needs some tests added to the unit tests.

**Comment by jsejcksn** [comment]
> And it needs some tests added to the unit tests.

@kitsonk Where are they located?
