### ISSUE TITLE
Deno.test() and browser javascript

### ISSUE THREAD

**Issue by EricPoggel** [denoland/deno#7877]
There appears to be no feasible way to use Deno.test() to test code meant to run in the browser, which is the most common use of JavaScript:

```JavaScript
// Use jsdom to create a document element.
import jsdom from 'https://dev.jspm.io/jsdom'
if (!window) {
	const {JSDOM} = jsdom;
	var dom = new JSDOM(`<!DOCTYPE html><html><head></head><body></body></html>`);
	var document = dom.window.document;
}

import createElement from 'some/module.js';

Deno.test('dom', () => {
	document.createEl('div'); // Works	
	createElement('<div>hi!</div>'); // Fails bc some/module.js doesn't use jsdom to create the document element.
});
```

If there's a way to do this, please document it.

Perhaps Deno could provide a global "document" variable that uses jsdom?  Or a way to define our own global variables present in all modules?

**Comment by nayeemrmn** [comment]
You're using `if (!window) {}` to test for a browser environment, which won't work because Deno has that variable. Use `if (globalThis.Deno == null) {}` instead.

**Comment by EricPoggel** [comment]
Thanks for the correction, but that doesn't help the main issue.

**Comment by nayeemrmn** [comment]
I don't know what the main issue is. What's in `some/module.js`? Is that code block supposed to be two different modules? Which part are you running in the browser?

**Comment by EricPoggel** [comment]
createElement() is a common function in many libraries that uses document.createElement() to create html elements.  I used some/module.js as a generic example of importing it from such a library.

Your previous comment mentions globalThis, which seems to not be documented on Deno.land?  A google of `site:deno.land globalThis` doesn't find any docs.

If I add `globalThis.document = dom.window.document`, then document is a global variable in my imported module.

**Comment by Soremwar** [comment]
`globalThis` is a JavaScript feature

**Comment by EricPoggel** [comment]
Interesting.  Thanks for the JavaScript help.  I'm now closing this issue.
