### ISSUE TITLE
Second Deno.test() leaking async ops if JSDOM is used.

### ISSUE THREAD

**Issue by EricPoggel** [denoland/deno#7878]
Why does the first test pass but the second test fail?  Normally I'd assume JSDom is leaking async events and submit the issue there.  But it only fails if the 'b' test is also present, making me think it's a Deno issue?

Minimal code to reproduce the issue.  All tests will succeed if JSDom is not used, or if the 'b' test is removed.  If writing complex code across multiple tests, they succeed if they're all moved to a single Deno.test() callback function body, but fail otherwise.

```JavaScript
import jsdom from 'https://dev.jspm.io/jsdom'
let win = new jsdom.JSDOM(``).window;

Deno.test('a', () => {});
Deno.test('b', () => {});

// Terminate running timers and remove event listeners.
// Although we never created any.
win.close();
```

Output of `deno test` on the command line:

```
running 2 tests
test a ... ok (2ms)
test b ... FAILED (1ms)

failures:

b
AssertionError: Test case is leaking async ops.
Before:
  - dispatched: 2
  - completed: 1
After:
  - dispatched: 3
  - completed: 3

Make sure to await all promises returned from Deno APIs before
finishing test case.
    at assert (deno:cli/rt/06_util.js:33:13)
    at asyncOpSanitizer (deno:cli/rt/40_testing.js:44:7)
    at async Object.resourceSanitizer [as fn] (deno:cli/rt/40_testing.js:68:7)
    at async TestRunner.[Symbol.asyncIterator] (deno:cli/rt/40_testing.js:240:13)
    at async Object.runTests (deno:cli/rt/40_testing.js:317:22)

failures:

        b

test result: FAILED. 1 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out (
```

**Comment by qwerasd205** [comment]
It would seem that during the 'b' test, an async op is completed in the background, causing the diff to be, well, different. This behaviour of basing it on absolute diffs does seem wrong to me. It can be reproduced much more simply with the following code:
```js
const asyncLoop = async () => {
    new Promise(resolve => {
        setTimeout(resolve, 1);
    }).then(asyncLoop);
}
asyncLoop();

Deno.test('a', () => {});
Deno.test('b', () => {});
```

**Comment by EricPoggel** [comment]
Is there a way to make it only track async ops that are started and completed from within the test code, ignoring those happening outside?

**Comment by EricPoggel** [comment]
As a crude solution, I've found that adding a small sleep before the tests solves the problem:

```javascript
const sleep = (milliseconds) =>
	new Promise(resolve => setTimeout(resolve, milliseconds));
await sleep(10);
```
