### ISSUE TITLE
Add deno.trace()

### ISSUE THREAD

**Issue by ry** [denoland/deno#788]
This can and should be implemented purely in JS. The idea is to be able to get a trace of which ops were executed for a given promise.

Example:
```typescript
function trace(p: Promise): Promise<string[]>;

let ops = await deno.trace(fetch("http://tinyclouds.org/"));
console.log(ops);  // Expected output: [ "FetchReq" ]
```
Alternative name `deno.opTrace()` maybe `deno.strace()`?

**Comment by kevinkassimo** [comment]
Just curious, what would be a reasonable output if someone does
```js
let ops = await deno.strace(deno.strace(deno.strace(fetch("http://tinyclouds.org/"))));
console.log(ops);
```
? (I would with a simplest implementation it could result in `ops -> []`)
