### ISSUE TITLE
URLSearchParams: \n not encoded correctly

### ISSUE THREAD

**Issue by 5chulzi** [denoland/deno#7888]
When encoding newline characters with URLSearchParams they result in value `%A` instead of `%0A`.

```javascript
// Deno 1.4.5
console.log(new URLSearchParams({ test: "\n" }).toString()) // "test=%A"
```

```javascript
// Browser as well as Node.js v14.10.0
console.log(new URLSearchParams({ test: "\n" }).toString()) // "test=%0A"
```
I'm not sure if I'm missing something in the docs or elsewhere, but that's what I noticed while using URLSearchParams in Deno.

**Comment by lala7573** [comment]
Hello, can I try this?
