### ISSUE TITLE
Add flag --compile / -c  to force re-compilation of TS.

### ISSUE THREAD

**Issue by ry** [denoland/deno#790]
This is needed to properly benchmark cold vs warm startup #780 

start here https://github.com/denoland/deno/blob/master/src/flags.rs

This will require hacking js/compiler.ts

**Comment by bartlomieju** [comment]
AFAIK I think we should add check for `--compile` flag here https://github.com/denoland/deno/blob/master/js/compiler.ts#L419
to force compilation.

I am not sure how to get flags passed down to compiler though

**Comment by bartlomieju** [comment]
This issue can be closed
