### ISSUE TITLE
Represent type-only dependencies in deno info

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#7927]
Currently we do not represent type only dependencies (`@deno-types`, `X-TypeScript-Types` and triple slash types directives in JS files) in the output of `deno info`, even though they are part of what gets loaded and cached and are part of the module graph.  We should reflect this in both the output to the terminal as well as the JSON structure.

**Comment by bartlomieju** [comment]
I'm in favor of this change, I think we should land it for `1.6.0` similar to previous `deno info` overhaul in `1.4.0`

**Comment by kitsonk** [comment]
I've assigned it to myself and will do it when we get closer to 1.6.0... We should wait for the JSON restructure to be aligned to the current output.
