### ISSUE TITLE
Feature request: CLI available as library

### ISSUE THREAD

**Issue by AndyBarron** [denoland/deno#7928]
I'm working on a project where I'd like to instantiate multiple instances of the full Deno runtime from within Rust code. Because the `cli` package only provides a binary, that isn't currently possible. I'd like to avoid the inefficiencies of shelling out to multiple separate Deno processes, and instead spin them up in Rust threads.

Adding a `[lib]` target to `Cargo.toml` in the `cli` package would fix this, but it would probably require changes to the package to expose a Rust API with all of the CLI options.

**Comment by bartlomieju** [comment]
We had `lib` option specified some time ago, but in https://github.com/denoland/deno/pull/5226 we decided to remove it - Deno is being developed very fast and each patch release would introduce breaking changes in the Rust interface - that's why it's considered private. There are no plans in the immediate future to change that.

**Comment by olanod** [comment]
This would be very useful, I'm trying to create a plug-in system where the JS/WASM plug-ins can run in the browser and server unchanged using the `WebWorker` interface. I see in the cli package most of my homework is done already but can't use it if is not exposed, doing it myself on top of deno-core seems like a non trivial work. Knowing that the API is unstable. what about publishing it as a pre-release version known to be unstable for the people that are willing and expecting things to break? say `deno-lib v1.x-alpha` from there I get my unstable web worker abstraction and be happy that fixing some breaking API changes is easier than implementing the whole thing myself.

**Comment by bartlomieju** [comment]
> what about publishing it as a pre-release version known to be unstable for the people that are willing and expecting things to break? say deno-lib v1.x-alpha from there I get my unstable web worker abstraction and be happy that fixing some breaking API changes is easier than implementing the whole thing myself.

This is not possible, `deno` is at current version `1.4.6` and we have no way to version Rust crate differently.

**Comment by jahtalab** [comment]
@bartlomieju , Currently the way to reuse any of cli internal implementations is to fork the repo and add the required `lib.rs`. Is there anyway we can improve on this?

Also, are there any parts that can be exposed initially? Specifically the `Worker` struct (not `MainWorker` or `WebWorker`).  
I can work on the necessary changes.

**Comment by bartlomieju** [comment]
@jahtalab my comment from above still holds (https://github.com/denoland/deno/issues/7928#issuecomment-706689428). Every release introduces a lot of changes in Rust code, eg. `refactors` from https://github.com/denoland/deno/issues/7915. We just had a series of PRs which rewritten about 20% of `cli` codebase and there are a few more such rewrites coming. I'll be happy to revisit this topic when the codebase stabilizes but I don't think we should provide CLI as library at this point of time. @ry thoughts?

**Comment by trevyn** [comment]
Would it be possible to only expose a "pipe" interface to the CLI? That would be trivially stable and that way we could embed Deno easily and avoid the overhead of shelling out, even if it's not as fancy as a proper API.

**Comment by bartlomieju** [comment]
> Would it be possible to only expose a "pipe" interface to the CLI? That would be trivially stable and that way we could embed Deno easily and avoid the overhead of shelling out, even if it's not as fancy as a proper API.

@trevyn I'm not sure what you're suggesting here, could you elaborate?

**Comment by trevyn** [comment]
Like, instead of the CLI reading/writing to `stdout`/`stdin`, it just piped those to a Rust byte channel or something.

One way would be to mimic the interface to [`std::process`](https://doc.rust-lang.org/std/process/index.html), but there's probably a simpler way.

**Comment by olanod** [comment]
That sounds quite hacky 🤔 besides cli args/flags don't come from the stdin, does the cli even read anything from stdin? and what is the output of a command? do I have to write a parser for whatever different commands output?

**Comment by bartlomieju** [comment]
@olanod @trevyn agreed, that does indeed sound hacky. Core team had discussion on this topic and we're actually going to expose `cli` as a library in some near future.

**Comment by bartlomieju** [comment]
@AndyBarron @olanod @jahtalab @trevyn we now provide library crate that exposes runtime functionalities of Deno: https://crates.io/crates/deno_runtime
