### ISSUE TITLE
Deno.repl() feature suggestion 

### ISSUE THREAD

**Issue by JeremyJaydan** [denoland/deno#7938]
It'd be neat if we could trigger the deno repl from within a script and specify the initial input.

Below script here would launch a deno repl that inputs `1 + 1`, then returns the result, and waits for further inputs.
```typescript
Deno.repl(`1 + 1`);
```

A possible use case is for cli tools that have apis, the below script would launch a deno repl with your own prelude:
```typescript
Deno.repl(`const foo = await import('path/to/mod.ts')`);
```
Above could be executed by your main cli command, similar to the deno cli.

Could also be an alternative to making cli tools in general for simple stuff by combining this with `deno install`.

**Comment by andreespirela** [comment]
This could be nice, I can see several use cases such as running external scripts in a dynamic way. It may even work for dynamic automation & having the Deno namespace available

**Comment by kitsonk** [comment]
How would this be better than `eval()` or `new Function()`?

**Comment by andreespirela** [comment]
> How would this be better than `eval()` or `new Function()`?

As far as I am aware, eval doesn’t have acess to the Deno namespace, eval is purely javascript code (is this right?) with `Deno.repl` you could have access to the Deno namespace and execute deno scripts dinamically. 

Note: I didn’t suggest this feature, I’m just commenting from what makes sense to me, since “eval” would be the same thing so I’m guessing Deno.repl is to be used for deno scripts

**Comment by kitsonk** [comment]
@andreespirela `eval()` runs in the same context where it is invoked.  Just try `eval("Deno.cwd()");` (same with `new Function()`)

**Comment by andreespirela** [comment]
You’re right @kitsonk , then I guess my question is the same as yours, how is it different from eval.

**Comment by JeremyJaydan** [comment]
Hey @kitsonk @andreespirela 

What I'm referring to is starting a deno repl via script. When you type the `deno` command in the terminal, that is the deno repl I'm referring to.

1. Imagine having the following in a script called `lodash.ts`
```typescript
Deno.repl(`const foo = await import('https://deno.land/x/lodash@4.17.19/lodash.js')`);
```

2. Then you did `deno install ./lodash.ts`

That would install that script with the command `lodash`.

3. When you type `lodash`, an interactive deno repl starts up and imports the lodash library.

I hope that makes more sense, let me know if it doesn't!

Also I just noticed this pr here, maybe the above could be an alternative solution to #7427

**Comment by JeremyJaydan** [comment]
Also regarding the above pr mentioned, instead of adding a flag to the deno cli you could write a script that takes in an argument like this:
###### custom_repl.ts
```typescript
const url = Deno.args[0];
Deno.repl(`await import('${url}')`);
```
installing: `deno install ./custom_repl.ts`
running: `custom_repl https://deno.land/x/lodash@4.17.19/lodash.js`
```
Deno 1.4.6
exit using ctrl+d or close()
> await import('https://deno.land/x/lodash@4.17.19/lodash.js');
Last evaluation result is no longer saved to _.
Module { [Symbol(Symbol.toStringTag)]: "Module" }
> _.join(["a", "b", "c"], ".")
"a.b.c"
```

**Comment by bartlomieju** [comment]
@JeremyJaydan I agree that this feature is useful, however I don't agree on the API - @solson proposed similar solution in #7427, but I think we should accept `<script>` argument to `deno` or `deno repl` and execute provided script on REPL startup.

**Comment by JeremyJaydan** [comment]
I'd be happy with either, though I think Deno.repl has potential in terms of being a tool you can use in your code to manipulate state within a script similar to browser devtool repls, that's somewhat a different idea to this whole issue though.

**Comment by 00ff0000red** [comment]
This seems like it ought to be done using `eval` or a `Deno.process` instead. What is presented at the start is perfectly equivalent to eval, with top-level await and module execution context.

**Comment by kitsonk** [comment]
Now that I understand the feature, @bartlomieju I agree with you, `deno repl something.ts` should setup whatever before starting the REPL loop.

For the `deno install` challenge, a simple `--repl` flag? Or maybe a `--subcommand` flag to be future proof?

Cc/ @caspervonb

**Comment by caspervonb** [comment]
Providing an API for the REP; not unless we want to allow the user to override completion, highlighting, validation, hinting, et cetera (I'm defenitivly against).

These are all now are in Rust which let us dump quite a bit of internal state, we're also in control of the threading model now so we can add gdb like debugging commands to it as-well, *eventually*.

Issue #3173 already asks for something ala

```console
deno eval --interactive <script>
```

And also #7425, indirectly.

I think what we *actually* want long term is an --interactive flag.

Any command that runs code like "eval" and "run" should be able start an isolate according to its execution rules and drop down into an interactive debugging console when provided with the --interactive flag.

As for running something in the *global context*; is there anything wrong with just using pipes to stdin?

```
(echo "console.log('do your stuff')" && cat) | deno
```

**Comment by caspervonb** [comment]
> As for running something in the *global context*; is there anything wrong with just using pipes to stdin?

Except for that particular example not working, should be possible to echo && cat to unbuffer(1) tho.

**Comment by solson** [comment]
> As for running something in the global context; is there anything wrong with just using pipes to stdin?

Yes, this will disable interactive readline features. I'm not familiar with `unbuffer` and didn't have it installed (so this would be an extra dependency for this usecase, and one that may not work on Windows at all), but when I try to do things like `(echo "console.log('do your stuff')" && cat) | unbuffer deno` it seems to hang and ignore input.

In general, I've never seen anything piping to an interactive REPL work well.

**Comment by JeremyJaydan** [comment]
`--interactive` flag makes sense, also with the globals, perhaps if the interactive flag is specified then the repl could expose the evaluated script exports under the file name.

###### foo.ts
```typescript
export function add(a: number, b: number){
  return a + b;
}
```
`> deno install foo.ts --interactive`
`> foo`
```
Deno 1.4.6 { foo }
exit using ctrl+d or close()
> foo.add(5, 5);
10
```

A problem with this though is that you couldn't have both interactive and non interactive for things like sub-commands unless more functionality is added. Only thing I can think of for this is if you specified within the script whether it should be interactive or not.

**Comment by bartlomieju** [comment]
This is partially implemented by https://github.com/denoland/deno/pull/11590

**Comment by NightMachinary** [comment]
I like to be able to start the REPL in the middle of the execution as a debugger tool. 

Similar stuff in other languages:
- `from IPython import embed; embed()`
- https://github.com/JuliaDebug/Infiltrator.jl

**Comment by bartlomieju** [comment]
https://github.com/denoland/deno/pull/14247 adds `--eval-file` flag to `deno repl` that allows to achieve the same proposed functionality. I'm considering this issue as resolved.
