### ISSUE TITLE
Move js/*_test.ts to tests/ 

### ISSUE THREAD

**Issue by ry** [denoland/deno#794]
Including unit_test.ts js/testing/ and test_util.ts.

js/ is now going to be reserved for code that gets bundled into the runtime. (Uses node imports to resolve modules in //third_party/node_modules.)

tests/ is now code that runs against the runtime. (Uses deno imports.)

**Comment by Mefffiu** [comment]
Let me give a try.

**Comment by kumaran-14** [comment]
Is it still availabe?

**Comment by Mefffiu** [comment]
@kumaran-14  Feel free to implement, first come, first served.

**Comment by hardik140397** [comment]
Is the issue still available? Can I gice it a try?

**Comment by kumaran-14** [comment]
@ry @kevinkassimo , I get this error while trying to run test.py.
I have node lts, python 2.7.15 installed.
I first forked this repo and cloned the fork using --recurse-submodules option.
`kumaran-14@Zeus:~/Development/OSS/deno$ python ./tools/test.py`
`Deno test server http://localhost:4545/`
`Required target doesn't exist: /home/kumaran-14/Development/OSS/deno/out/debug/deno`
`Run ./tools/build.py`
`kumaran-14@Zeus:~/Development/OSS/deno$`

**Comment by kevinkassimo** [comment]
@kumaran-14 Have you run `./tools/build.py` ?

**Comment by ry** [comment]
I will take this issue. Please do not submit a PR.

**Comment by kumaran-14** [comment]
Is this a difficult issue?

**Comment by bartlomieju** [comment]
@ry `BUILD.gn` has `ts_sources` defined so AFAICT `_test.ts` files are not included in final bundle. Do you still want to move them to `tests/`?

**Comment by ry** [comment]
Closing this one. See my comment here: https://github.com/denoland/deno/pull/819#issuecomment-427394139
