### ISSUE TITLE
Main thread panic with DOMParser.parseFromString() - Deno DOM WASM

### ISSUE THREAD

**Issue by fauzan121002** [denoland/deno#7943]
I'm running into strange issues while running domparser parseFromString() function.

Example code usage :
```ts
  import { DOMParser } from "https://deno.land/x/deno_dom@v0.1.2-alpha5/deno-dom-wasm.ts"; 
  import * as Eta from "https://deno.land/x/eta@v1.11.0/mod.ts";

  async render(path: string, data: object) {
    try{
      const domparser = new DOMParser();

      const output = Eta.renderFile(path,data);
      return domparser.parseFromString(output,"text/html");
    }catch(e){
      console.log(e);

      return "template errors";
    }
  }
```

the errors i getting is :

```bash
> deno run -A --unstable server.ts

thread 'main' panicked at 'not implemented: Don't know how to create cache name for scheme: d', cli\disk_cache.rs:107:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

PS: My deno version is 1.3.1

**Comment by kitsonk** [comment]
What happens when you upgrade to a new version of Deno?

Also what is the operating system?  I suspect it is a windows machine and there were several challenges/fixes related to file name handling on windows between 1.3.1 and the current release.

**Comment by bartlomieju** [comment]
Most likely the `path` argument is something like `d:\foo\bar` - try prefixing with `file://`

**Comment by fauzan121002** [comment]
> 
> 
> Most likely the `path` argument is something like `d:\foo\bar` - try prefixing with `file://`

Thanks! i figured it out , it was from some file who need to use d scheme , and for now i use TextEncoder for parse it.

**Comment by fauzan121002** [comment]
> 
> 
> What happens when you upgrade to a new version of Deno?
> 
> Also what is the operating system? I suspect it is a windows machine and there were several challenges/fixes related to file name handling on windows between 1.3.1 and the current release.

yes, it is a windows machine , but now i solve that in my own way by built in TextEncoder instead of that deno-dom lib.

**Comment by fauzan121002** [comment]
I will close this issue, thanks guys for your comment.
