### ISSUE TITLE
Awaiting never-resolved promise makes Deno hang & hot spin.

### ISSUE THREAD

**Issue by piscisaureus** [denoland/deno#7945]
`deno run` this.

```js
// x.js
await new Promise(() => {});
```

It spins because there is nothing happening any more, and tokio can't block the event loop for us (there's nothing to poll).

Deno should either:
* exit
* throw an exception similar to `UncaughtException`. Maybe `AwaitNeverException` or something?

**Comment by bartlomieju** [comment]
I've tried this in latest node and it exits silently with exit code 13. 

```
~/dev/deno
▶ node --version
v14.13.1

~/dev/deno
▶ node foo.mjs

~/dev/deno
▶ echo $?
13
```

**Comment by 00ff0000red** [comment]
How would Deno know that the promise will never resolve? Shouldn't it just keep the process alive?

I would check how browsers handle this, except... they don't have top-level await yet.

**Comment by lucacasonato** [comment]
> How would Deno know that the promise will never resolve? Shouldn't it just keep the process alive?

Because no IO ops or timers are going on anymore (ie no timers scheduled to fire, no file reading going on). There is nothing the event loop is waiting for to complete. That means there is no way JS execution will be resumed ever (because there is nothing to trigger that), so the promise can never be resolved.

**Comment by 00ff0000red** [comment]
> Because no IO ops or timers are going on anymore (ie no timers scheduled to fire, no file reading going on). There is nothing the event loop is waiting for to complete. That means there is no way JS execution will be resumed ever (because there is nothing to trigger that), so the promise can never be resolved.

Ah yes, it can be determined if the event loop is depleted, and no code is being executed. Guess then it should be safe to error or exit.
Does the ECMAScript standard define what to do about never resolving promises in TLA, or just never resolving promises in general, and any specific conditions that must be met to mark it as never resolving?

Also, what about situations like:
```ts
const temp = () => {};

self.addEventListener(
    "message",
    temp
);

await new Promise( temp );
```

Can it be safely determined that the promise will not resolve, as there are still events being listened to?
