### ISSUE TITLE
Bug: asm.js line numbers are incorrect; Suggestion: Disable V8's asm.js code paths

### ISSUE THREAD

**Issue by 00ff0000red** [denoland/deno#7949]
*I had originally written out a few hundred lines, attached an example module, and gave clear reasoning behind this. but had forgotten that my device's power was at 1% :)*

It seems that Deno logs completely bogus line numbers when validation fails on code ran under the "use asm" directive, can someone else confirm?
An approximately 50 line module was telling me that my error was in the 400s, yet I checked the Deno output file and didn't see anything that suggested that was possible at all.

If this is indeed a bug, I do **not** suggest fixing it, instead, it should be rightfully deprecated and ran as normal JiT / interpreted JavaScript.

It is only used as a fallback in older browsers that don't support Wasm.

It is highly unlikely that any code has been written in Deno that uses asm.js yet, so there may still be time to prevent it and/or discourage its usage.

## Update ##
Here is a quick example of an erroneous module that you should be able to copy and paste to confirm the error:
```ts
const asm_js_module = function() {
	"use asm";

	type f64 = number;

	function add(
		x: f64,
		y: f64
	) {
		x = +x;
		y = +y;

		~x; // error, what line is this on in your output file? What does Deno say?

		return x + y;
	}

	return {
		add: add
	};
}();

console.log(
	asm_js_module.add(4, 56)
);
```

**Comment by 00ff0000red** [comment]
@lucacasonato If I might ask since you marked it as such, what about this makes it a "breaking change"?

**Comment by lucacasonato** [comment]
Thinking about this again, you're right. This isn't a breaking change. The worst it would do is potentially slow down some ASM.js code. But as you mentioned, likely no-one is using it.
