### ISSUE TITLE
Confusing Claim on website[Request to edit website]

### ISSUE THREAD

**Issue by bhavya32** [denoland/deno#7954]
I do not know if this is the right place for this issue. The deno website claims shipping single executable. A lot of people including me are getting confused that it compiles typescript to single executable file. Whereas it means that deno compiler is a single executable. What do you think of it?

**Comment by lucacasonato** [comment]
Deno is both a single file (deno.exe) and a can bundle JavaScript and typescript into a single file. So the wording is correct.
