### ISSUE TITLE
Issues building for void-linux

### ISSUE THREAD

**Issue by shizonic** [denoland/deno#7958]
After unpacking a release tarball (e.g. 1.4.6) the third_party folder is empty. Guess the step https://github.com/denoland/deno/blob/master/.github/workflows/ci.yml#L61 needs to be updated...

**Comment by lucacasonato** [comment]
Actually, why do you wan't the third_party folder? It shouldn't be required for building Deno.

**Comment by shizonic** [comment]
In this case I don't need it. Thought it is required because my build always failes.

Background: Try to package it for the Void linux distribution.

May you help me whats going wrong? Here is the Travis CI build log: https://travis-ci.org/github/void-linux/void-packages/builds/735400951

**Comment by lucacasonato** [comment]
I think this distro only ships with musl right? Deno requires glibc.

**Comment by shizonic** [comment]
Not it ships with glibc too! This isn't the problem becsuse I can skip the musl builds. But it even doesn't build on glibc.

**Comment by lucacasonato** [comment]
The minimum supported rust version is 1.46.0. It seems your release is older. Also you need a very recent version of clang: https://github.com/denoland/rusty_v8#build-v8-from-source

**Comment by shizonic** [comment]
Oh okay this may be the cause. I will give it a try. Thanks for your help!

**Comment by shizonic** [comment]
As far as I see void

> The minimum supported rust version is 1.46.0.
Where did you see that? As far as I see Voidlinux uses version 1.46.0: https://github.com/void-linux/void-packages/blob/master/srcpkgs/rust/template#L7

> Also you need a very recent version of clang.
LLVM 10.0 works too, right? (https://github.com/void-linux/void-packages/blob/master/srcpkgs/llvm/template#L3)

**Comment by lucacasonato** [comment]
> LLVM 10.0 works too, right? (https://github.com/void-linux/void-packages/blob/master/srcpkgs/llvm/template#L3)

LLVM is a compiler backend, and not the same as something like gcc or clang (which is the compiler frontend that parses c / c++ and translates it LLVM IR). rusty_v8 hasnt been built with anything other than recent clang for a long time, so anything else (like gcc) likely won't work.

**Comment by piscisaureus** [comment]
Note that rusty_v8 will actually download clang automatically so it should "just work".
But we don't test on void-linux so I'm sure there will be some surprises.

**Comment by shizonic** [comment]
Thanks @lucacasonato and @piscisaureus for your great explanations and help. I really appreciate it!

Actually I guess the problem has something to do with gn because of this error log:

```
Caused by:

  process didn't exit successfully: `/builddir/deno-1.4.6/target/release/build/rusty_v8-4793fc38ad031d22/build-script-build` (exit code: 101)

  --- stdout

  Downloading https://github.com/denoland/ninja_gn_binaries/archive/20200827.tar.gz... Done.

  using Chromiums clang

  clang_base_path /builddir/deno-1.4.6/target/release/clang

  Downloading https://commondatastorage.googleapis.com/chromium-browser-clang/Linux_x64/clang-llvmorg-12-init-4187-g33ce275f-1.tgz .......... Done.

  The current directory is /root/hostdir/cargo/registry/src/github.com-1285ae84e5963aae/rusty_v8-0.11.0

  gn gen --root=/host/cargo/registry/src/github.com-1285ae84e5963aae/rusty_v8-0.11.0 /builddir/deno-1.4.6/target/release/gn_out

  running: "/builddir/deno-1.4.6/target/release/ninja_gn_binaries-20200827/linux64/gn" "--root=/host/cargo/registry/src/github.com-1285ae84e5963aae/rusty_v8-0.11.0" "gen" "/builddir/deno-1.4.6/target/release/gn_out" "--args=is_debug=false v8_enable_handle_zapping=false clang_base_path=\"/builddir/deno-1.4.6/target/release/clang\" cc_wrapper=\"/usr/bin/ccache\""



  --- stderr

  thread 'main' panicked at '

  failed to execute command: No such file or directory (os error 2)

  is `gn gen` not installed?
```

I gonna investigate further. Love deno and want it be packaged on Voidlinux.

**Comment by piscisaureus** [comment]
gn should also be automatically installed though.

I wonder if you’re on a 32 bit system. We don’t support 32 bit builds.

**Comment by shizonic** [comment]
> gn should also be automatically installed though.

hmm okay

> I wonder if you’re on a 32 bit system. We don’t support 32 bit builds.

Voidlinux supports many archs: x86_64, i686, aarch64, armv7l, armv6l and all for glibc and musl libc. I can't build deno on any... even x86_64 glibc. Have a look at: https://travis-ci.org/github/void-linux/void-packages/builds/735400951

**Comment by piscisaureus** [comment]
Gn is typically downloaded by the cargo_gn crate somewhere into the build directory.
You can bring your own, but then you need to set the GN environment variable to point at it.
We download it from here btw - https://github.com/denoland/ninja_gn_binaries/tags

**Comment by shizonic** [comment]
> Gn is typically downloaded by the cargo_gn crate somewhere into the build directory.
> You can bring your own, but then you need to set the GN environment variable to point at it.
> We download it from here btw - https://github.com/denoland/ninja_gn_binaries/tags

Oh okay I used https://gn.googlesource.com/gn

**Comment by shizonic** [comment]
How can I prevent fetching precompiled binaries during build process? See: https://github.com/void-linux/void-packages/pull/22043#issuecomment-629819836 and https://github.com/void-linux/void-packages/pull/25436#issuecomment-708605940

**Comment by notramo** [comment]
Any progress on this?

**Comment by lucacasonato** [comment]
There is nothing actionable here. If you are still struggling with building Deno from source, please open a new issue.
