### ISSUE TITLE
Typos in `consoleTestStringifyFunctionWithPrototypeRemoved` unit test

### ISSUE THREAD

**Issue by solson** [denoland/deno#7962]
https://github.com/denoland/deno/blob/f42d0fc99e37bb0583cddeca5367a1dcf83d53b8/cli/tests/unit/console_test.ts#L350-L363

In this unit test, `gf` and `agf` are currently both regular functions but appear to be intended to test against `GeneratorFunction` and `AsyncGeneratorFunction` the same way `f` and `af` are testing `Function` and `AsyncFunction`. Note that the output shouldn't change since it's intentionally setting prototypes to `null` to test the fallback to `"Function"`. As discussed at https://github.com/denoland/deno/pull/7930#discussion_r504127789.

**Comment by kitsonk** [comment]
Fixed in #7930

**Comment by kt3k** [comment]
@solson Thank you for catching this! That was a mistake.
