### ISSUE TITLE
deno_core shouldn't use "get_identity_hash()" to identify v8 objects

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#7969]
Ref https://github.com/denoland/deno/pull/7946#discussion_r504192165

**Comment by bartlomieju** [comment]
Ref https://github.com/denoland/deno/issues/1745

**Comment by bnoordhuis** [comment]
I suggested implementing `Hash` and `Eq` with `promise.get_identity_hash()` and `promise.strict_equals(other)` respectively but I realize that means you need a `HandleScope` to unwrap the `v8::Global<v8::Promise>`.

Strictly speaking, you don't need one - a strong `Global` can be transmuted to a `Local`. Something like this could work:
```rust
let a: v8::Global<v8::Promise> = f();
let b: v8::Global<v8::Promise> = g();
let is_eq = a.map(|a| b.map(|b| a.strict_equals(b)));
```
Where `.map()` transmutes to `Local`.

Then again, maybe it's better to just assign ids and store those using private symbols. I've opened https://github.com/denoland/rusty_v8/pull/498 to flesh out `v8::Private` more.

**Comment by bnoordhuis** [comment]
A post on v8-users made me revisit this again. I don't think we need `a.strict_equals(b)` here, we can just compare the `v8::Global` handles.

V8's C++ API has `bool v8::PersistentBase::operator==(const v8::PersistentBase&) const`, which is basically a couple of pointer checks. It returns true when the handles point to the same JS object.

rusty_v8 implements `PartialEq` for `Global` and it behaves the same way, if I read the code right, no need to unbox.
