### ISSUE TITLE
REPL incorrect behaviour on specific RegExp match

### ISSUE THREAD

**Issue by cknight** [denoland/deno#7978]
The following RegExp causes the REPL to jump to a new line (expecting more input?) without executing the line, though more simple RegExp seem to work fine.  Using Deno 1.4.6 on Linux.

```
console.log("{test1} abc {test2} def {{test3}}".match(/{([^{].+?)}/));
```
I've narrowed it down to the `[^{]` condition.  Taking out the `[^{]` condition allows the REPL to run the RegExp without the new line/more input needed behaviour.  Also the original RegExp works fine when run via `deno run`.

**Comment by caspervonb** [comment]
> I've narrowed it down to the [^{] condition. Taking out the [^{] 

Yeah that would do it, its a simple brace balance check validator from rustyline.
Might have to go back to compiling in the validator.

**Comment by caspervonb** [comment]
Blocked on #7896
