### ISSUE TITLE
Move `deno lint` to Stable

### ISSUE THREAD

**Issue by ebebbington** [denoland/deno#7983]
**References**
![image](https://user-images.githubusercontent.com/47337480/96120932-35eeaa80-0ee7-11eb-934b-e3e88095347e.png)

**Why**
The main show stopper for some people i know of, for **not** using `deno lint`, is the fact it is unstable. Judging by @bartlomieju's response,  it doesn't seem to need the unstable flag anymore either.

I believe that people feel they would adjust their code base to be in line with `deno lint`, then say, the next day a change to `lint` was made, and there's a gazillion errors when doing another `deno lint` (eg the whole idea of unstable, which i'm not saying is bad btw)

**Comment by kitsonk** [comment]
I am supportive of it being unflagged for 1.5.

**Comment by bartlomieju** [comment]
Forgot to reply to this issue 🤦 

Linter has been around for a few months new and it seems to work quite well. IMO we can mark it as stable minus JSON output (ie. `deno lint --json` would still require `--unstable`).
