### ISSUE TITLE
upgrade to tokio 1.0

### ISSUE THREAD

**Issue by ry** [denoland/deno#7984]
https://github.com/tokio-rs/tokio/releases/tag/tokio-0.3.0

**Comment by bartlomieju** [comment]
I'm working on this

**Comment by caass** [comment]
Hey just wanted to comment in case folks were unaware, [tokio 1.0 was recently released](https://tokio.rs/blog/2020-12-tokio-1-0).

**Comment by lucacasonato** [comment]
We are working on it: #8779

**Comment by magurotuna** [comment]
Seems we can close this issue since #8779 was merged.
