### ISSUE TITLE
React v17 JSX Transform

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#7993]
React introduces a new JSX transform that is supported in TypeScript 4.1: https://devblogs.microsoft.com/typescript/announcing-typescript-4-1-beta/#jsx-factories

We should consider the impact of this on Deno and specifically `--no-check`.

**Comment by kitsonk** [comment]
Ref: https://github.com/swc-project/swc/issues/1103

**Comment by lucacasonato** [comment]
Duplicate of #8440 (closing this because the other issue is more active).

**Comment by kitsonk** [comment]
🤦
