### ISSUE TITLE
Unlexable script causes Deno to panic

### ISSUE THREAD

**Issue by 00ff0000red** [denoland/deno#7995]
Ran on an outdated Deno 1.1.0, no, I do not have the permissions necessary to update it, but can someone confirm this in a newer version? If it is not present in the current version, this can be closed right away.

I was writing some code, copy & pasted some linter/TS info, didn't finish commenting it out and/or creating actual code out of it, but accidentally hit ran.

It came down to this incorrect code:

```ts
const toString: (local)(this: Function) => string) = undefined;
```

It can be shortened to just this:
```ts
let toString:(l)(this:
```
`const` or `let` work there, I'm not sure about others, I didn't even try `var`, maybe it's keywords, maybe it needs to be three letters or more, I have no clue, but I'm not about to make blind assumptions.

Deno showed the following error:
```
Thread 'main' panicked at 'internal error: entered unreachable code: invalid pattern: Span { lo: BytePos(26), hi: BytePos(30), ctxt: #0 }', /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/macros.rs:16:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
exit status 101
```

**Comment by kitsonk** [comment]
You've made some incorrect assumptions of how Deno works internally.  It does not just pass everything to the TypeScript and let it sort it out, it uses swc to attempt to determine the dependencies before doing anything, and swc is throwing here, because the code is not valid JavaScript or TypeScript.

Ultimately we need to give a better error when encountering un-lexable code like this.

**Comment by 00ff0000red** [comment]
> You've made some incorrect assumptions of how Deno works internally...

My apologies, would you recommend that I rename the issue?

**Comment by bartlomieju** [comment]
This is bug in SWC, opened an issue: https://github.com/swc-project/swc/issues/1170

**Comment by 00ff0000red** [comment]
> This is bug in SWC, opened an issue: [swc-project/swc#1170](https://github.com/swc-project/swc/issues/1170)

It seems the issue that you had opened in SWC has since been closed, should this be closed down too, to indicate that issue no longer affects Deno?

**Comment by bartlomieju** [comment]
Yes, Deno no longer panics so this issue is resolved.

**Comment by xianqiangliu** [comment]
n
