### ISSUE TITLE
TextDecoder converts string to lower case before throwing error

### ISSUE THREAD

**Issue by 00ff0000red** [denoland/deno#8003]
Bit of background: I had encountered an encoding issue in a webpage with accepting user files at runtime, and had sought to resolve the encoding issue using the browser's native `TextDecoder`. To start, I needed a good list of supported encodings, I checked out MDN and a polyfill GitHub https://github.com/inexorabletash/text-encoding. Combined the lists and ran a loop to see what threw errors, and what didn't.

It happened to be that Deno was already open, so I just ran the loop there, I later contrasted with the browser to get a reasonable view of what I could expect. I had spotted a tiny difference.

Test code:
```ts
new TextDecoder("GBK");
```

> Uncaught RangeError: The encoding label provided ('gbk') is invalid.

Yet, notice that I never used "gbk," the only difference being the case sensitivity.
Chromium shows the error with the original case that was input.

I have no clue whether or not the spec has anything on this, and couldn't test another browser at the moment.

**Comment by kitsonk** [comment]
It is supposed to be case insensitive: https://www.w3.org/International/docs/encoding/#concept-encoding-get

**Comment by 00ff0000red** [comment]
> It is supposed to be case insensitive: https://www.w3.org/International/docs/encoding/#concept-encoding-get

I am not sure if we are on the same page, I was merely referring to the error message, if you are too, then Chromium has a bug, not Deno.

**Comment by kitsonk** [comment]
Ah, I see what you were referring to.

It should be a `RangeError` though, instead of a `TypeError`... that message text though is never specified in the standards and runtimes vary quite a lot, though we should return what was input instead of modifying it.

**Comment by aca** [comment]
It seems like an easy fix. Can I try this?

**Comment by lucacasonato** [comment]
@aca Sure. You can find the code for this in op_crates/web/08_text_encoding.js.

**Comment by 00ff0000red** [comment]
> It should be a `RangeError` though, instead of a `TypeError` ...

I only saw `EncodingError`s and `TypeError`s being thrown in the specification web page that you had linked, but it seems like both, Deno and Chromium throw a `RangeError`, so what are you suggesting?

> ... that message text though is never specified in the standards and runtimes vary quite a lot, though we should return what was input instead of modifying it.

Yes, this is the point that I was referring to when I had mentioned a spec. I didn't think they specifically say what the error should say, how it should be formatted, etc. Is that all up to the implementor/runtime?

For example, this is the format that Chromium's message would be in:

> RangeError: Failed to construct 'TextDecoder': The encoding label provided ('GBK') is invalid.

They are both set up differently, but they convey the same meaning, and they both show the label that was supposably input.
(actually, Chromium's is more specific but that's beside the point)

**Comment by kitsonk** [comment]
[`RangeError`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError) should be used when matching a list of enumerated values. Sometimes the specs specify the error type, sometimes they don't. While it might be strictly open for interpretation, we want to interpret the same error type as Chromium.

**Comment by 00ff0000red** [comment]
> [`RangeError`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError) should be used when matching a list of enumerated values. Sometimes the specs specify the error type, sometimes they don't. While it might be strictly open for interpretation, we want to interpret the same error type as Chromium.

There was no prior mention of the error type, and Deno is throwing a RangeError, just like Chromium

Deno:
> Uncaught **RangeError**: The encoding label provided ('{label}') is invalid.

Chromium:
> Uncaught **RangeError**: Failed to construct 'TextDecoder': The encoding label provided ('{label}') is invalid.

So you already throw the same error.

It seems like we aren't focusing on the same issue, was I vague, indirect, or otherwise confusing in my wording?
I'm not quite sure that we are looking at the same issue.

**Comment by kitsonk** [comment]
@00ff0000red 

```
❯ deno
Deno 1.4.6
exit using ctrl+d or close()
> new TextDecoder("GBK");
Uncaught TypeError: Internal decoder ('gbk') not found.
    at new TextDecoder (deno:op_crates/web/08_text_encoding.js:984:15)
    at <anonymous>:2:1
```

That doesn't look like a `RangeError` to me.  It should be a `RangeError`.

**Comment by 00ff0000red** [comment]
> ```
> Uncaught TypeError: Internal decoder ('gbk') not found.
> ```
> ...
> 
> That doesn't look like a `RangeError` to me. It should be a `RangeError`.

Whoa, quite the change. In an older version of Deno (the one I'm stuck with), the error was in fact a `RangeError`, this must have changed over time.
