### ISSUE TITLE
Constant condition in "std/archive/tar.ts"

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#8008]
Upgrading `deno_lint` yielded a fragment of code that doesn't make any sense (line 496):

https://github.com/denoland/deno/blob/46b892ad37df9ba9bed77fb923a1cfe284b208dc/std/archive/tar.ts#L494-L498

It should probably be `if (n == null)`... 

CC @marcosc90

**Comment by marcosc90** [comment]
Ouch. I'll take care of it today. (I've been quite busy last few months).
