### ISSUE TITLE
DevTools profiler

### ISSUE THREAD

**Issue by FredrikNoren** [denoland/deno#8021]
Hi,

I was playing around with the devtools and noticed that the profiler (under "performance") doesn't seem to work. It displays a `"Tracing.start" wasn't found` error.

**Comment by caspervonb** [comment]
Tracing domain is not supported, see

https://chromedevtools.github.io/devtools-protocol/v8/

**Comment by kitsonk** [comment]
Since v8 doesn't support it, we can't easily support it, so closing.
