### ISSUE TITLE
Some WebSocket messages are getting queued

### ISSUE THREAD

**Issue by l2ig** [denoland/deno#8022]
There seems to be an internal minimum queue size limit for the messages to be send to the client. That's at least what I would guess since smaller messages are often only sent to the client after sending another message after it (pushing to the internal queue `socket.send(...)`).

Is there any way to force a message to be sent, regardless of the queue size?

**Comment by MarkTiedemann** [comment]
@l2ig Do you have a minimal example that shows how to reproduce this behavior? I'm unable to reproduce it so far - in my tests, all of the messages sent via `ws.send` are flushed immediately.

**Comment by l2ig** [comment]
Seems to have been fixed in std@0.76.0 of the HTTP module.
