### ISSUE TITLE
repl hangs on unclosed braces in string literals.

### ISSUE THREAD

**Issue by a2800276** [denoland/deno#8034]
What the title says. Steps to reproduce:

```
$ ./deno --version⏎
deno 1.4.6
v8 8.7.220.3
typescript 4.0.3

$ ./deno repl⏎
Deno 1.4.6
exit using ctrl+d or close()
> let a = "{"⏎   // ... silence
```

Fails independently of quote " ' backtick and brace [ ( { and with let, var and const as well as with naked literals ( `if (a !== "{") console.log("here")` )

I imagine this is some sort of completion gone terribly wrong. No well versed enough in deno internals to spontaneously dig deeper at the moment sorry.

**Comment by a2800276** [comment]
Possibly related: 
https://github.com/denoland/deno/issues/7978

Hangs on unmatch braces in regexp's as well at any rate.

**Comment by caspervonb** [comment]
Related to https://github.com/denoland/deno/issues/7978 (same cause)
