### ISSUE TITLE
Code samples in readme files don't work due to $STD_VERSION 

### ISSUE THREAD

**Issue by KotlinIsland** [denoland/deno#8043]
The std versioning changes made in [this PR](https://github.com/denoland/deno/pull/7442)  break the readme examples on Github.

[Github](https://github.com/denoland/deno#getting-started)
![image](https://user-images.githubusercontent.com/65446343/96539089-931a9f80-12dd-11eb-8811-5825bbb8b431.png)
[deno.land](https://deno.land/#getting-started)
![image](https://user-images.githubusercontent.com/65446343/96539152-bcd3c680-12dd-11eb-80d7-d98a574e0d83.png)

This is extremely confusing to someone who don't understand what this means.

```
user@machine~> deno eval 'import {serve} from \'https://deno.land/std@$STD_VERSION/http/server.ts\''
Download https://deno.land/std@$STD_VERSION/http/server.ts
error: Import 'https://deno.land/std@$STD_VERSION/http/server.ts' failed: 404 Not Found
```

**Comment by peterlyq** [comment]
source not found  change origin maybe work
![AB)AHGITQPP6W1EY37RY3%3](https://user-images.githubusercontent.com/52620161/96549097-9879e900-12e1-11eb-8cef-03228dddaa00.png)

**Comment by peterlyq** [comment]
https://cdn.bootcdn.net/ajax/libs/typescript/0.9.5/typescript.js

**Comment by peterlyq** [comment]
https://github.com/denoland/deno/blob/master/std/http/server.ts  
I think you can download it locally and import this file

**Comment by KotlinIsland** [comment]
I know how to fix it, the issue is that the code samples don't work by default.

Someone looking at deno for the first time will see the example and it will fail and they will be like "deno sucks".
