### ISSUE TITLE
internal tsconfig is not used for determining emit hash

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#8047]
During testing of #7920 I discovered that our emit hashing is not working correctly. We only seem to hash the tsconfig passed in through flags, rather than the entire tsconfig after it has been merged with our defaults. This leads to web worker compile emits and main worker compile emits being hashed the same. That leads to this bug:

```ts
// foo.ts
console.log("hello world");
self.onmessage = () => {}
```
```
> deno cache foo.ts
Check file:///mnt/f9/Projects/github.com/denoland/deno/foo.ts
error: TS2339 [ERROR]: Property 'onmessage' does not exist on type 'Window & typeof globalThis'.
self.onmessage = () => {}
     ~~~~~~~~~
    at file:///mnt/f9/Projects/github.com/denoland/deno/foo.ts:2:6

> deno cache --worker=foo.ts
Check file:///mnt/f9/Projects/github.com/denoland/deno/foo.ts

>  deno cache foo.ts
```

The third call to deno cache should error, but it doesn't.

This might already be fixed in `ModuleGraph2`.

cc @kitsonk

**Comment by kitsonk** [comment]
It is fixed in `ModuleGraph2`.  When the migration to `run`/`cache` lands we can close this.
