### ISSUE TITLE
Proposal: Change the behaviour of --reload flag

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#8066]
Currently `--reload` not only "cache busts" remote modules, but it also forces a re-emit of modules, irrespective of if we know it won't change the emit.

Ultimately this was a legacy situation where we couldn't be 100% sure if the emit was valid.  Our emitted cache invalidation detection had "issues" before, but with the new module graph, we think we have closed off all the scenarios (the new graph will resolve #8047 which is the last known issue).

That means if we think all the emitted files are "valid" because we know none of the sources have changed, nor the configuration, nor the version of Deno, then we can be confident that we don't need to reemit, and so the `--reload` becomes redundant and wasted, forcing recompilation in scenarios that don't make sense.

This will have some big impacts on things like our benchmarks which rely on the behaviour to benchmark "cold" starts, which we need to rework.

**Comment by dsherret** [comment]
> but it also forces a re-emit of modules, irrespective of if we know it won't change the emit.

I believe this no longer occurs and it will always use the cached emit if it's valid for the current source, so closing, but please let me know if I'm mistaken though.
