### ISSUE TITLE
std/node/fs tests fail locally

### ISSUE THREAD

**Issue by Soremwar** [denoland/deno#8074]
![image](https://user-images.githubusercontent.com/42647963/96887479-40122b00-144a-11eb-9a0a-6a5b9c9bb00b.png)

They all fail by expecting a value but getting undefined in an assertion

OS: Linux 5.8.16-2-MANJAROx64
Deno: 1.4.6
Command runned: `deno test -A --unstable std/node/_fs`

**Comment by AliBasicCoder** [comment]
> ![image](https://user-images.githubusercontent.com/42647963/96887479-40122b00-144a-11eb-9a0a-6a5b9c9bb00b.png)
> 
> They all fail by expecting a value but getting undefined in an assertion
> 
> OS: Linux 5.8.16-2-MANJAROx64
> Deno: 1.4.6
> Command runned: `deno test -A --unstable std/node/_fs`

error log
