### ISSUE TITLE
fs.walk followSymlinks unimplemented

### ISSUE THREAD

**Issue by andykais** [denoland/deno#8076]
adding the flag `followSymlinks: true` to `fs.walk` results in the error:
```
error: Uncaught Error: unimplemented
                    throw new Error("unimplemented");
                          ^
    at Object.walk (file:///home/andrew/.deno/bin/wallpal.js:2600:27)
```

fs.walk appears to be the only std module that has tjrows an `unimplemented` error. That makes me believe perhaps this was not intentional? https://github.com/denoland/deno/blob/master/std/fs/walk.ts#L110. Either way, it would be awesome to re-enable this flag, there are file systems including symlinks I would like to walk over. Is there a workaround that exists in deno currently?

**Comment by Liamolucko** [comment]
I can try and fix this.
