### ISSUE TITLE
Bad import.meta handling in bundles

### ISSUE THREAD

**Issue by nayeemrmn** [denoland/deno#8088]
Input:
```ts
console.log(import.meta);
```

Actual output:
```js
console.log(import.meta);
```

Expected output:
```js
const import_meta_1 = { url: "file:///path/to/original/source", main: import.meta.main /* or false */ };
console.log(import_meta_1);
```

---

We're here again: https://github.com/swc-project/swc/issues/1115#issuecomment-700638446. `import.meta` is an object that can be wholly referenced and is even writable. SWC should not substitute individual fields, but call back to the loader for the initialising value of `import_meta_1`.

cc @kitsonk @kdy1

**Comment by kdy1** [comment]
I didn't know about it. Thanks for reporting.

**Comment by nayeemrmn** [comment]
@kdy1 This will require a breaking API change for swc. The bundler hook should instead be expected to return a list of key-value pairs which will initially populate the `import.meta` object.

For reference, the hook supplied by the host (Deno) to the JS engine (V8) is specified here: https://tc39.es/proposal-import-meta/#sec-hostgetimportmetaproperties. The hook supplied by Deno to swc should be the lexical equivalent of that.
