### ISSUE TITLE
How shoud we report security issues?

### ISSUE THREAD

**Issue by hhc0null** [denoland/deno#8094]
I found some behaviors that are seemed to vulnerability in deno however there is no guide for reporting security issues in the website or here.
Should we contact to ry at tinyclouds.org with an email or open a new dedicated issue?

**Comment by Soremwar** [comment]
This is the issue tracker for Deno runtime, any possible security you might encounter with it will fit in here.

**Comment by ry** [comment]
ry@tinyclouds.org

I have plans for a better system, but not yet.
