### ISSUE TITLE
Add a new timer API that won't prevent Deno from exiting automatically

### ISSUE THREAD

**Issue by lideming** [denoland/deno#8095]
https://github.com/manyuanrong/deno_mysql/issues/87
I have used `setTimeout` to implement the idle connection timeout for the connection pool.
But when user write some short-running app like this:
```ts
const client = new Client().connect(/* ... */);
console.log(await client.query("SELECT ..."));
// End of file, but Deno won't exit
```
Deno won't exit after it finishes querying. It still waits for some timer (by `setTimeout`) that can close pooled connection when it stayed idle for too long.

I think there should be a timer API that won't prevent Deno from exiting automatically.

**Comment by kt3k** [comment]
Maybe a duplicate of https://github.com/denoland/deno/issues/6141 ?

**Comment by lideming** [comment]
Yes, it is. Thanks.
