### ISSUE TITLE
Dynamic import of remote modules should be allowed when they are in the cache

### ISSUE THREAD

**Issue by teleclimber** [denoland/deno#8109]
Say I have this "app":

```
import type {ServerRequest} from "https://deno.land/std/http/server.ts";
import { multiParser } from 'https://deno.land/x/multiparser@v2.0.1/mod.ts';

export default async function(req:ServerRequest) {
	const form = await multiParser(req);
	console.log(form);
}
```

And I have a "runner" that runs such an app dynamically:

```
import type {ServerRequest} from "https://deno.land/std/http/server.ts";

async function run() {
	const mod = await import('./app.ts');

	mod.default(<ServerRequest>{});
}

run();
```

Deno tells me I need `--allow-read` for the app.ts and `--allow-net` for the multiparser module. OK.

But now if I do:

```
deno cache app.ts
```

Caching `app.ts` means all the deps are downloaded and future imports of them are served from the local cache. From the CLI help for cache:

```
Future runs of this module will trigger no downloads or compilation unless
--reload is specified.
```

Despite that Deno still requires the same permissions, even though it would not perform a network request at all even if I gave it `--allow-net`. 

Given this, can we allow modules that have a remote URL to be used without `--allow-net` if they are present in the cache and therefore trigger no net access?

Thanks ✌️

**Comment by kitsonk** [comment]
I don't think we would want to "ignore" permissions just because something is in the cache.  It being cached or not should not change if we apply permissions in my opinion.  Dynamic imports require appropriate permissions irrespective of the state of the cache.  It would be like saying for `fetch()` that if a remote resource is already cached, then don't require `--allow-net`.

**Comment by nayeemrmn** [comment]
I also don't like the state of the cache affecting required permissions in general, but this one might be worth it for the practical advantage. Why should it require net permission if it's not interacting with the network? The only protection I see is not exposing information about the state of the cache -- but the requested permission is net. That's always bothered me.

> It would be like saying for `fetch()` that if a remote resource is already cached, then don't require `--allow-net`.

If I implemented my own `fetch()` and cache system in user space, it wouldn't require net permission if the resource is already cached. So maybe, I think the only fundamentally consistent way of approaching net permission is to only guard "genuine" (as far as Deno can see) network access.

**Comment by teleclimber** [comment]
I can understand that exposing the state of the global cache to an app could be problematic. Maybe there are other ways to solve this.

The real problem is that dynamic `import` in Deno is completely broken in practice.

In an idiomatic Deno app you import library code via URLs. So most Deno code is written with static imports to public URLs. This works great because Deno does not require net permissions to import remote static URLs. From a developer's POV there is lots to like: you write the import, it runs. No `npm install`, no `package.json`, etc.. Nice!

The problem hits as soon as you want to run that same app or module via a dynamic import. Any non-trivial app or module will have multiple imports of 3rd-party packages, and most of those will import yet more packages. The result is there could be dozens or hundreds of URLs to allow, and currently there is no mechanism that I know of that lets you safely and easily allow them.

There really ought to be some way to safely use dynamic imports of real-world code, without undue burden on the developer or user. I don't know what the right solution is. It could be that there needs to be a whitelist that can ship with the app, and a way of generating that list from code. Or we need to go back to generating vendor dirs? Or maybe it's something else?

I asked to allow use of cached modules because the current behavior doesn't make much sense, and from my POV that would solve the problem well enough, and doesn't fundamentally alter what makes Deno great.

Having said that it may not be a good solution for the general case. Will developers have to put in their readme `Please run deno cache ./some/module.ts if you get allow net errors!!!`. Not great UX.

**Comment by bartlomieju** [comment]
@kitsonk and I had a discussion about this problem. 

I think requiring `--allow-net` or `--allow-read` for dynamic import/workers code is not the perfect solution and it became apparent in #8215. 

We're thinking about introducing another flag that would control what files can be loaded during runtime. `--allow-imports` flag could be a solution - this flag would accept filepaths and URLs similar to both `--allow-read` and `--allow-net`, but it would affect only calls to `import()` and `new Worker()`.

Unfortunately this would be a huge breaking change in behavior and we need to think it through very carefully, after finishing refactors to file fetcher (#8245) and runtime compiler API.

**Comment by lucacasonato** [comment]
I am going to close this in favor of #8266.
