### ISSUE TITLE
支持deno

### ISSUE THREAD

**Issue by ayepig** [denoland/deno#8112]
我是支持deno的，但生态是个问题。

**Comment by kitsonk** [comment]
I suspect you are looking for support for Deno in Chinese.  At the moment, that is via community support.  The repository can be found here: https://github.com/deno-china. I am sure they would welcome further help from the community.

我懷疑您正在尋找對Deno中文的支持。目前，這是通過社區支持。該存儲庫可以在這裡找到：https：//github.com/deno-china。我相信他們會歡迎社區的進一步幫助。
