### ISSUE TITLE
deno fmt --column-width option

### ISSUE THREAD

**Issue by crookse** [denoland/deno#8117]
it'd be nice to have a column width option so that users can specify where the formatter wraps texts. 80 is cool, but some people have bigger screens and prefer/use 100-120... maybe even larger idk.

**Comment by nayeemrmn** [comment]
Config for `deno fmt` was ultimately decided against in https://github.com/denoland/deno/issues/3827#issuecomment-708479969. The same naturally applies to individual flags like this, effective duplicate.
