### ISSUE TITLE
deno fmt --check should not show entire file when only line endings differ

### ISSUE THREAD

**Issue by littletof** [denoland/deno#8118]
When running `deno fmt --check` it should only show relevant changes, or a radius of it, it shouldn't print simple line changes, or it could result in quite bad outputs in my opinion. 

Running it, basically printed my whole codebase because of some import reordering, and organizing.

<details>
<summary>Examples</summary>

![image](https://user-images.githubusercontent.com/32012862/97111556-c5623d80-16df-11eb-8d7e-485418de7203.png)
![image](https://user-images.githubusercontent.com/32012862/97111543-a95e9c00-16df-11eb-8927-fdb1821e2c5e.png)

</details>

**Comment by kitsonk** [comment]
Define "relevant changes"...  That term is highly subjective.

**Comment by lucacasonato** [comment]
> Define "relevant changes"

Well printing a diff for unchanged lines seems not great.

**Comment by littletof** [comment]
@kitsonk relevant for me, is what a user might care about, running fmt with --check. Its even highlighted with green and red background.
Relevant might mean something else for others, but I dont think the hundreds of lines printed because the first 10 import lines were merged into one, doesnt really fit any of it.

I think a git diff is a good example, how it should work.

(As an example, if you check out [v0.0.3](https://github.com/littletof/prettyBenching/tree/v0.3.0) tag of [prettyBenching](https://github.com/littletof/prettyBenching) and run `deno fmt --check`, I dont think, the output helps you in any way. But if you run it without --check, and see the git diff, it shows you the reasonable amount of code for the changes)

**Comment by Soremwar** [comment]
If `fmt` added a trailing comma or changed spaces for tabs it's still a diff between the two contents, any text editor will tell you so as well.

But I agree something could be done about it, so perhaps a `--detail` level flag could be added in order to exclude this "irrelevant" changes? (I think it would be hard to implement though, as kitsonk pointed out "significative" is very subjective)

**Comment by kitsonk** [comment]
An intelligent diff, that is actually a diff output that could be applied using `patch` on the command line sounds useful (same type of output as `git diff`), but the changes are whatever the changes are.

**Comment by littletof** [comment]
Today I had a bit of time to look at this again, I think I have to correct myself/rephrase things, apologies, for that.

I'm on windows 10, deno 1.4.6, working with the previously linked repo's `tests/test_deps.ts` on tag v0.3.0 as an example.

If I run `deno fmt --check` I get this:
![image](https://user-images.githubusercontent.com/32012862/97758763-dfe15000-1aff-11eb-93a2-da32328ce4e6.png)

When I run `deno fmt` there are no changes in the file, nothing in git status. (when I stage the "change" in VSCode, it disappears)
![image](https://user-images.githubusercontent.com/32012862/97758744-d7891500-1aff-11eb-8870-d2895771dedf.png)

Change in file encoding should show in git status, if im correct, so its not that.

So with this, can anyone help me out what's happening, what is the actual change fmt is presenting for me with this --check output?

The statement that these reports are caused by _simple linechanges_, (that I mentioned above) from the testing seems like is not true.

---

On the whats relevant, whats not: The  irrelevant was meant for cases like this above, when no change was seen even in git status, altough --check showed lines.

I think every change is relevant, that fmt actually makes (even whitespace changes, etc.). Maybe it would be better to say that _a change that can be committed, or shows up in git status, thats relevant_ , and maybe an intelligent diff tool could help filter these further.

**Comment by wperron** [comment]
could it be a change in whitespaces, like tabs to spaces? If you enable all whitespaces in VSCode you should be able to see that change more clearly, or confirm that it's not that.

**Comment by littletof** [comment]
@wperron I dont think so :/ I checked it again, and also no change appears for it in the commit itself, which it should for whitespace change if I'm correct. I think it has to be something that it changes or think it changes, but cant actually be committed.

**Comment by wperron** [comment]
I had the hypothesis that it might be due to line-endings configuration in git for Windows, but I can't reproduce locally using all three possible values for that setting. I cloned the repo you linked with deno 1.4.6, 1.5.0 and 1.5.3, on CMD and PowerShell. The only diff I can get are valid ones. If you can provide more details on your setup and configs to consistently reproduce the issue that would be super helpful.

**Comment by bartlomieju** [comment]
It's perfectly possible that our `diff` implementation is broken (`cli/diff.rs`), we should use some existing crate for that purpose.

**Comment by wperron** [comment]
@littletof is this issue still relevant? last I checked I wasn't able to reproduce on Windows, are you still having the issue on your setup?

**Comment by littletof** [comment]
@wperron Yes, it still happens, but you were right. It's **line-endings**. I still couldn't make `git` to show any changes, but the hex shows the change.

<details>
<summary>HEX diff</summary>

Before:
![image](https://user-images.githubusercontent.com/32012862/104091234-59be5400-527c-11eb-9d83-23f22f5b6384.png)
After:
![image](https://user-images.githubusercontent.com/32012862/104091239-6478e900-527c-11eb-9d4f-f8f3010032bb.png)

</details>

Knowing this, I'm fine, with closing this issue, but I think there should be an option to disable formatting line-endings, or to not show them, when printig the `fmt` diff, because line-ending changes can prevent you from seeing more relevant (**IMO**) changes in a big project.

**Comment by bartlomieju** [comment]
@dsherret could you please look into this?
