### ISSUE TITLE
Get all the network interfaces in Deno

### ISSUE THREAD

**Issue by mayankchoubey1** [denoland/deno#8137]
Add a method Deno.networkInterfaces() to get the list of all network interfaces with some details like:

- MAC address
- up or down
- IP Addresses

**Comment by mayankchoubey1** [comment]
@bartlomieju : I've submitted this enhancement today. Do you think this will be useful? Is it okay if I assign it to myself and work on it?

**Comment by mayankchoubey1** [comment]
@lucacasonato  Can I work on it? If yes, please assign to me. Thanks!

**Comment by eliassjogreen** [comment]
It should probably provide pretty much the same properties as in [node](https://nodejs.org/api/os.html#os_os_networkinterfaces) if that is possible.

**Comment by silverwind** [comment]
`netmask` can probably be ommited in favor of `cidr`.

**Comment by rektide** [comment]
It'd be lovely to be able to get changes to the network interfaces too.

Ideally that covers both a change in what interfaces there are, and changes in status of an interface.

There's addons like https://github.com/JacobFischer/netlinkwrapper for node. There's a subfeature required to do this well in Linux: one communicates with a netlink socket over UDP. libuv has a wip [pr](https://github.com/libuv/libuv/pull/2558) to enable non AF_INET{,6} communication, for example.

**Comment by bartlomieju** [comment]
@bnoordhuis is working on this feature.
