### ISSUE TITLE
bug(windows): prompt() adds "\r" to inputs and doesn't consider the default value

### ISSUE THREAD

**Issue by maximousblk** [denoland/deno#8146]
to reproduce:

Linux (WSL) | Windows

![image](https://user-images.githubusercontent.com/28438021/97340972-761c3880-18aa-11eb-89d5-1a51d6ba1226.png)

isn't limited to repl

![image](https://user-images.githubusercontent.com/28438021/97341736-77019a00-18ab-11eb-980d-5ca55ae1b496.png)

**Comment by pedropaulosuzuki** [comment]
There is another problem with the prompt, confirm and alert methods... they seem to not print correctly some characters (ãñõâêîôûü, for example)

![image](https://user-images.githubusercontent.com/32345702/97512662-da053680-1968-11eb-86ac-b2042a130248.png)

It happens both on the alert/confirm/prompt message and on the return value. This does not happen on console.log, though.

deno 1.5.0
v8 8.7.220.3
typescript 4.0.3

If this is too unrelated to the main problem, I can open a new issue

**Comment by pedropaulosuzuki** [comment]
As #8146 can be fixed with something similar to a simple trim method, and the problem I brought with special UTF-8 (or UTF-16?) probably isn't that simple, I'm opening a new issue.

**Comment by lucacasonato** [comment]
Fixed by #8149
