### ISSUE TITLE
Implement deno.symlink() for Windows

### ISSUE THREAD

**Issue by manidlou** [denoland/deno#815]
```js
// Creates newname as a symbolic link to oldname.
// The type argument can be set to 'dir' or 'file' and is only available on Windows.
function symlink(oldname: string, newname: string, type?: string): Promise<void>;
```

**Comment by ry** [comment]
See discussion here https://github.com/denoland/deno/pull/742

**Comment by ry** [comment]
Feb 24 2020: Still an issue

https://github.com/denoland/deno/blob/5da7c7df1d8649ddb5628b4dc830aa8c23ccb488/cli/ops/fs.rs#L460-L463

**Comment by bartlomieju** [comment]
Implemented in https://github.com/denoland/deno/pull/5533
