### ISSUE TITLE
Division operator gets mistaken for regex literals in multi-line REPL editor

### ISSUE THREAD

**Issue by caspervonb** [denoland/deno#8160]
The following hangs waiting for another line of input

```
Deno 1.5.0
exit using ctrl+d or close()
> (3 / 4)
```

Cause is quite simple, the validator believes that the `/` token is the start of a regex literal.

**Comment by kevinkassimo** [comment]
Did some investigation, yet realized that our manual parsing strategy would suffer badly from distinguishing cases as follows eventually (this similarly breaks regex based syntax highlighting badly):
```js
[ 1/2, /[regex]*/g ] / 2; /* // ] */ 1 // comment ]
```
We might as well eventually switch to using an actual JS parser (maybe swc could work?) and simply investigate the output error to determine we should allow continued input.

**Comment by caspervonb** [comment]
> We might as well eventually switch to using an actual JS parser (maybe swc could work?) and simply investigate the output error to determine we should allow continued input.

Yeah probably about time to just drop swc in there.

**Comment by sanderhahn** [comment]
The es5-lexer uses this lookbehind for [`guess_is_regexp`](https://github.com/mikesamuel/es5-lexer/blob/master/src/guess_is_regexp.js).
