### ISSUE TITLE
Deno 1.5.0 bundle regression: bad Unicode character encoding

### ISSUE THREAD

**Issue by nktpro** [denoland/deno#8161]
Bundling in deno `1.5.0` would produce invalid code, due to what appears to be bad Unicode encoding in the output.

Here's a quick reproducer:

```typescript
import { stringify } from "https://deno.land/std@0.75.0/encoding/yaml.ts";

console.log(stringify({
  foo: "bar",
}));
```
`1.5.0` bundle will contain:

![image](https://user-images.githubusercontent.com/59050/97384870-fb9de980-18a6-11eb-8621-20c26a3ec613.png)

as opposed to the same snippet in `1.4.6`

![image](https://user-images.githubusercontent.com/59050/97384906-0c4e5f80-18a7-11eb-89d8-7a62801732fb.png)

**Comment by kitsonk** [comment]
I will isolate it a bit more, but it looks like an upstream issue with swc.

**Comment by kitsonk** [comment]
I think this would impact bundling as well as `--no-check`.  It is a defect with swc, which hopefully will be fixed quickly.
