### ISSUE TITLE
"Permission denied (os error 13)" with read-only Deno cache dir and `--config` flag using Deno 1.5.0

### ISSUE THREAD

**Issue by TooTallNate** [denoland/deno#8163]
### Error

```
$ deno run --config tsconfig.json hello.ts
Check file:///home/hello.ts
error: Permission denied (os error 13) (for '"/home/cache/gen/file/home/hello.ts.js"')
```

### To reproduce

**tsconfig.json**

```json
{
  "compilerOptions": {
    "strict": false,
    "noImplicitAny": false,
    "noImplicitThis": false,
    "alwaysStrict": false,
    "strictNullChecks": false,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": false,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true
  }
}
```

**hello.ts**

```typescript
import { ServerRequest } from 'https://deno.land/std@0.75.0/http/server.ts';

export default async (req: ServerRequest) => {
	req.respond({ body: `Hello, from Deno v${Deno.version.deno}!` });
};
```

Run commands:

```bash
$ deno --version
deno 1.5.0
v8 8.7.220.3
typescript 4.0.3

$ export DENO_DIR=cache

$ deno cache --config tsconfig.json hello.ts
Download https://deno.land/std@0.75.0/http/server.ts
Download https://deno.land/std@0.75.0/encoding/utf8.ts
Download https://deno.land/std@0.75.0/async/mod.ts
Download https://deno.land/std@0.75.0/http/_io.ts
Download https://deno.land/std@0.75.0/io/bufio.ts
Download https://deno.land/std@0.75.0/_util/assert.ts
Download https://deno.land/std@0.75.0/http/http_status.ts
Download https://deno.land/std@0.75.0/textproto/mod.ts
Download https://deno.land/std@0.75.0/bytes/mod.ts
Download https://deno.land/std@0.75.0/async/mux_async_iterator.ts
Download https://deno.land/std@0.75.0/async/delay.ts
Download https://deno.land/std@0.75.0/async/deferred.ts
Download https://deno.land/std@0.75.0/async/pool.ts
Check file:///home/hello.ts

# Before `chmod` - works
$ deno run --config tsconfig.json hello.ts
Check file:///home/hello.ts

# Mark cache dir as read-only (simulating AWS Lambda runtime environment)
$ chmod -R -w cache

# After `chmod` - errors
$ deno run --config tsconfig.json hello.ts
Check file:///home/hello.ts
error: Permission denied (os error 13) (for '"/home/cache/gen/file/home/hello.ts.js"')
```

### Notes

* This appears to be a regression in Deno 1.5.0. Following the reproduction steps above using Deno 1.4.6 works as expected.
* The error seems to only happen when using the `--config` flag (perhaps something related to this specific tsconfig setup). Following the reproduction steps above using Deno 1.5.0, _and omitting the `--config tsconfig.json` flag_ works as expected.

**Comment by kitsonk** [comment]
It looks like the way we hash the configuration in 1.5.0 is not deterministic. We changed this in 1.5.0, and thought it was, need to look at why. It should still have not caused an emit though.

**Comment by TooTallNate** [comment]
It might be worth noting that the file `/home/cache/gen/file/home/hello.ts.js` does indeed exist. So perhaps it's just a matter of accessing the file with `rw` permissions, while only `r` is required in this case.

**Comment by kitsonk** [comment]
I realised that actually if the `tsconfig.json` isn't deterministic, then it will create a different hash for `tsc` which will think that it needs to be emitted and the abstraction that handles the files hasn't changed, so I am pretty certain the behaviour you are seeing is that something is wrong with the hashing of the `tsconfig.json`.

**Comment by kitsonk** [comment]
So I was able to reproduce what I thought was the issue in a test case, basically our hash is non-deterministic when a `tsconfig.json` file is provided.  We use `serde` to deal with managing the configuration and a discussion with others indicates that it isn't by default guaranteed to be deterministic when deserailizing.  So I am working on a fix.
