### ISSUE TITLE
Deno bundle error in 1.5.0 - shared module not bundle into the result

### ISSUE THREAD

**Issue by colorhook** [denoland/deno#8164]
share.js

```js
export default 'share.js';
```

a.js

```js
import value from './share.js';
export default function() {
  console.log("a print:", value);
}
```

main.js

```js
import a from './a.js';
a();
```

`deno run main.js` is OK
`deno bundle main.js bundle.js` is OK
`deno run bundle.js` is OK

---------------

create b.js copy from a.js

```js
import value from './share.js';

export default function() {
  console.log("b print:", value);
}
```

add b.js to main.js

```js
import a from './a.js';
import b from './b.js'

a();
b();
```

`deno run main.js` is OK
`deno bundle main.js bundle.js` is OK
`deno run bundle.js` is NOT OK

`Uncaught ReferenceError: value is not defined` output

and the bundle.js content is

```js
const a = function() {
    console.log("a print:", value);
};
const b = function() {
    console.log("b print:", value);
};
a();
b();

```

**Comment by bartlomieju** [comment]
Fixed in https://github.com/denoland/deno/pull/8197
