### ISSUE TITLE
Deno does not complain with Decorators and no tsconfig in 1.5.0

### ISSUE THREAD

**Issue by andreespirela** [denoland/deno#8170]
Deno is accepting running `TS decorators` without needing a _tsconfig.json_. 

**Deno 1.4.6 (Expected)**
![image](https://user-images.githubusercontent.com/60560109/97451774-75b38a00-190a-11eb-9416-a4cfb6d2a392.png)

**Deno 1.5.0 (Not expected)**
![image](https://user-images.githubusercontent.com/60560109/97451943-9ed41a80-190a-11eb-80e3-db0eaf3d6093.png)

**1.5.0** runs without issues when it should in fact complain since no `tsconfig.json` is being used

**Comment by andreespirela** [comment]
Thanks @lucacasonato for providing the configuration. https://github.com/denoland/deno/blob/e01664d0ae6259022a901b0dea026ca350a49446/cli/module_graph2.rs#L705-L718 Seems like it is enabled by default.

cc @kitsonk @bartlomieju does this have something to do with https://github.com/denoland/deno/issues/7732 ?

**Comment by kitsonk** [comment]
As the comment states, we have decorators enabled by default with `--no-check` and so to have predictable output between `--no-check` and check, it is better to have it on.  Sorry it wasn't mentioned in the blog post, but there was a lot of reworking of the infrastructure.

I am working on a whole update to the TypeScript documentation in the manual which will be more precise in what is configured as a default and why.
