### ISSUE TITLE
New prompt, alert and confirm methods get confused when escaping special characters [ã]

### ISSUE THREAD

**Issue by pedropaulosuzuki** [denoland/deno#8179]
The new adition of prompt, alert and confirm methods are great news for all of us!! Glad to have those!

However, after the small #8146 issue, there is yet another unrelated problem with the new tools: special UTF-8 (maybe UTF-16?) characters (ãñõâêîôûü, for example):

![image](https://user-images.githubusercontent.com/32345702/97512662-da053680-1968-11eb-86ac-b2042a130248.png)

It happens both on the alert/confirm/prompt message and on the return value. This does not happen on console.log, though. May be related or similar to old #5046.

deno 1.5.0
v8 8.7.220.3
typescript 4.0.3

**Comment by pedropaulosuzuki** [comment]
May have something to do with [this](https://github.com/denoland/deno/blob/6be6c517d0691bf1d14eef67668e575c84cdfdf4/op_crates/web/08_text_encoding.js#L989). But not sure.

**Comment by pedropaulosuzuki** [comment]
Another example, this time with some kanji.

![image](https://user-images.githubusercontent.com/32345702/97653375-68e48280-1a3f-11eb-86a4-6de5321206a7.png)

```js
console.log(prompt('My prompt: 你好;').trim());
```

Latin example:
```js
console.log(prompt('My prompt: ãõâêîôûüïáéíóúàèìòùç;').trim());
```

**Comment by kt3k** [comment]
I found that `Deno.stdout.writeSync(new TextEncoder().encode("ã"))` causes the same problem (tested in powershell in windows).

<img width="883" alt="スクリーンショット 2020-10-30 17 55 14" src="https://user-images.githubusercontent.com/613956/97680171-9978fa80-1ad9-11eb-9e1f-667c8e7ed11d.png">

It seems that Deno.core.print can be a workaround.

**Comment by sanderhahn** [comment]
Was looking at the rustyline crate and it seems to use utf16 for reading input: https://github.com/kkawakam/rustyline/blob/master/src/tty/windows.rs#L105

**Comment by kt3k** [comment]
#8199 fixes the output of non-ascii characters, but the problem in reading non-ascii chars from stdin (in windows) is still remaining. The above utf-16 decoding could be a solution.

Addition of utf-16 encoding is in progress at https://github.com/denoland/deno/pull/8108

**Comment by pedropaulosuzuki** [comment]
> 
> 
> #8199 fixes the output of non-ascii characters, but the problem in reading non-ascii chars from stdin (in windows) is still remaining. The above utf-16 decoding could be a solution.
> 
> Addition of utf-16 encoding is in progress at #8108

That's only part of the problem, unfortunately. When capturing input, there is also a problem regarding the escaped characters. For example, try running the code below and inserting the characters 'a' and 'ã', one at a time:

```js
const a = prompt('Insert your character');

console.log(`a===a => ${a === 'a'}`);  // When inserting the character 'a', returns true, as expected!
console.log(`ã===ã => ${a === 'ã'}`); // When inserting the character 'ã', returns false...
```

**Comment by pedropaulosuzuki** [comment]
@piscisaureus I don't know if we can call this issue fully fixed. The output part of it is solved, it seems, but the input part of it is still nor recognizing special UTF-16 characters.

For example, when running the code below and inserting the characters 'a' and 'ã', one at a time, this is what we get:

```js
const a = prompt('Insert your character');

console.log(`a===a => ${a === 'a'}`);  // When inserting the character 'a', returns true, as expected!
console.log(`ã===ã => ${a === 'ã'}`); // When inserting the character 'ã', returns false, not what we expected.
```

Maybe we can open a new issue just for the input part, or reopen this one.
