### ISSUE TITLE
Deno bundle producing incorrect code in 1.5.0

### ISSUE THREAD

**Issue by giggio** [denoland/deno#8180]
I just tried running a simple http app with Deno, and after bundling I get an undefined error:

````
error: Uncaught TypeError: Cannot read property 'Continue' of undefined
        (void 0).Continue,
                 ^
    at file:///proj/dist/hello1.js:616:18
````

This is the source:

````ts
import { serve } from "https://deno.land/std@0.75.0/http/server.ts";

const port = 8000;
const host = "0.0.0.0";
const server = serve(`${host}:${port}`);
const body = new TextEncoder().encode("Hello, World!\n");

async function main() {
  for await (const request of server) {
    console.log(`Got a ${request.method} at ${request.url}.`);
    request.respond({ body });
  }
}
console.log(`Listening at http://${host}:${port}.`);

main();
````

This is a snippet, starting at line 614 of the generated .js:

````js
const STATUS_TEXT = new Map([
    [
        (void 0).Continue,
        "Continue"
    ],
    [
        (void 0).SwitchingProtocols,
        "Switching Protocols"
    ],
````

You can see all the `(void 0)...` there.

This are the commands I ran:

````
$ deno cache --lock deno-lock.json --lock-write src/hello1.ts
$ deno bundle --config tsconfig.json --lock deno-lock.json src/hello1.ts dist/hello1.js
````

I tried an empty `tsconfig.json`, it still fails.

This works with Deno `1.4.6`. This is a working version compiled with `1.4.6`:

````js
            exports_11("STATUS_TEXT", STATUS_TEXT = new Map([
                [Status.Continue, "Continue"],
                [Status.SwitchingProtocols, "Switching Protocols"],
````

`deno run` works in `1.5.0`.

This was ran on a Ubuntu machine. Let me know if you need more info.

**Comment by bartlomieju** [comment]
CC @kdy1

**Comment by kdy1** [comment]
@bartlomieju Does deno invoke some transforms of swc? I'm not sure where `(void 0)` came from.

**Comment by bartlomieju** [comment]
@kdy1 this is function that TS files are run through prior to bundling: https://github.com/denoland/deno/blob/b0482400c96476946514f03f27f139dd505b06fb/cli/ast.rs#L411-L473
