### ISSUE TITLE
Deno.fsync marked as stable, but needs --unstable flag (1.5.0)

### ISSUE THREAD

**Issue by jannes** [denoland/deno#8185]
When running a script that makes use of Deno.fsync I get the following error:  
`TypeError: Deno.fsync is not a function`  
(`deno run --allow-write --allow-read deno_scripts/testing_fsync.js `)  

Passing the `--unstable` flag resolves this.
(`deno run --allow-write --allow-read --unstable deno_scripts/testing_fsync.js`)  
However with 1.5.0 fsync/fdatasync are marked as stable in the documentation.

**Comment by bartlomieju** [comment]
CC @caspervonb
