### ISSUE TITLE
feat: Passing certificate data directly to HttpClient

### ISSUE THREAD

**Issue by danopia** [denoland/deno#8190]
In #6918 this signature was added:

```typescript
  /** **UNSTABLE**: New API, yet to be vetted.
   * The options used when creating a [HttpClient].
   */
  interface CreateHttpClientOptions {
    /** A certificate authority to use when validating TLS certificates.
     *
     * Requires `allow-read` permission.
     */
    caFile?: string;
  }
```

## Problem

When connecting to a Kubernetes API from within a cluster, `caFile` is useful, because there's a `ca.pem` file ready to go. However, when connecting from a workstation, the CA data is generally nested inside a YAML file instead:

```
> cat ~/.kube/config
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JS....
```

In order to use this CA with `Deno.createHttpClient` I have to extract the CA certificate and write it out to disk for Deno to read back in:

```typescript
    const caPath = `/tmp/ca-${clusterName}.pem`;
    await Deno.writeTextFile(caPath, caData);
    const httpClient = Deno.createHttpClient({
      caFile: caPath,
    });
```

... and now I need `--allow-write` as well as `--allow-read` (and `--allow-net`).

## Solution

There should be a separate parameter ([in nodejs it's called `ca`](https://nodejs.org/api/tls.html#tls_tls_createsecurecontext_options), and something like `caData` could also work) that allows us to pass certificate data in directly.

```typescript
    const httpClient = Deno.createHttpClient({
      ca: caData,
    });
```

The `key` and `cert` fields, when they are added (mentioned in #3444), should take similar consideration for inline data.

**Comment by yonbav** [comment]
Hi @danopia I've started to work on that issue hope it will be fixed soon.

**Comment by danopia** [comment]
Awesome, I'm looking forward to progress on this :crab: :pray:

**Comment by danopia** [comment]
Looks like this is merged and will be in the next Deno release; I'll close now in anticipation of it shipping. Thanks!!

**Comment by danopia** [comment]
I see this in 1.6.2:

```typescript
    const { cluster } = config.fetchCurrentContext();
 
    const caPath = `/tmp/ca-${context.cluster}.pem`;
    await Deno.writeTextFile(caPath, atob(cluster["certificate-authority-data"]));
 
    const httpClient = Deno.createHttpClient({
      caFile: caPath,
    });
```

⬇️ 

```typescript
    const { cluster } = config.fetchCurrentContext();
 
    const httpClient = Deno.createHttpClient({
      caData: cluster["certificate-authority-data"];
    });
```

A little Christmas gift for me! 🎄 

Now the only remaining problem I see with Deno talking to Kubernetes clusters is the dreaded #7660...
