### ISSUE TITLE
New .ico files

### ISSUE THREAD

**Issue by piscisaureus** [denoland/deno#8196]
I created some [new .ico files](https://gist.github.com/712aaff5436be6fa1a32a0e63c960c37). Below is how they look -- **but I can't make up my mind which one to use**.

* The large icons in explorer all look pretty decent but the new ones look slightly better.
* On the task bar the colorful one looks best I think.
* The little icon in the top left window corner looks crappy for all variants. I feel that maybe the image should be sharper and the background maybe should be removed entirely. Or we could pick the colorful one and add a black circle around it?

![image](https://user-images.githubusercontent.com/218257/97705379-46d91780-1ab4-11eb-9f74-48e03a45aa1d.png)

**Comment by hazae41** [comment]
My vote goes to the black and white icon 👍

**Comment by ije** [comment]
prefer **bw** one

**Comment by littletof** [comment]
I like the first one (_deno_) the most. I think its recognisable even, when blurry. If not that, than the colorful one, with a dark(er) border.

**Comment by piscisaureus** [comment]
Tangentially related - it turns out that windows will always show a **low resolution** 32x32 icon on the task bar, unless the user pins deno to either the task or to the start menu.

We don't do that automatically and it doesn't make a whole lot of sense for our users to do so... I guess that means our friendly dino will always look blurry...? Does anyone here have an uncle at MSFT who can shed some light on this?  

[To see it with your own eyes, download this webm file (github won't display it...)](https://gist.github.com/piscisaureus/fb68c6bac14123306bb366f154646092/raw/ba48de85b6bc2d8d64e65ba327bd6cd1db947d5e/wtfwin.webm)

**Comment by MarkTiedemann** [comment]
@piscisaureus Did you check how these icons look in the explorer when using Windows in dark mode? This was an issue with earlier designs (see https://github.com/denoland/deno/pull/6693).

**Comment by caspervonb** [comment]
New black white reads the best.

**Comment by MarkTiedemann** [comment]
Just tested on my Windows 10 in dark mode with "Extra large icons".

![Capture](https://user-images.githubusercontent.com/7062160/97904228-7bf99a00-1d40-11eb-90f2-e928f2504e5a.PNG)

It looks like the eye of the dino is either grey or transparent. Also there are a few white pixels in around the curvature.

> Tangentially related - it turns out that windows will always show a low resolution 32x32 icon on the task bar, unless the user pins deno to either the task or to the start menu.

Hmm, I can't reproduce this. Perhaps this is only with certain taskbar, start menu, or other related settings? For example, I have "Use small taskbar buttons" set to "Off", "Combine taskbar buttons" set to "Never", and "Use Start full screen" set to "On". But there are a ton of taskbar, start menu, and related settings so I won't even attempt to find out which ones might have an effect on this...
