### ISSUE TITLE
TextEncoder.encode TypeError: Invalid argument should give more details

### ISSUE THREAD

**Issue by Noah-Huppert** [denoland/deno#8201]
I believe that the `TypeError` returned by `TextEncoder.encode` is too ambiguous.  I think for any other method which isn't dealing with text encoding an ambiguous error message like `Invalid argument` would be okay. However text encoding is full of many hairy input situations, and more details to narrow down which bad input situation you are experiencing would be very helpful. 

---

Here is a short story highlighting where just a little more detail in the error message could have helped a lot:

I had an error where some code before a call to `encode()` was accidentally returning objects instead of strings. It was hard for me to find because I even had Typescript annotations on the argument I was passing to `encode()` asserting that the argument should be a string, like so: 
```ts
let foo = shouldReturnAStringButReturnedAnObject();

function whichCallsEncodeWithArg(arg: string) {
  // arg never touched in any way until here
  new TextEncoder.encode(arg);
}

whichCallsEncodeWithArg(foo);
```

However type checks were passed and the error occurred. 

This small self contained example effectively reproduces passing an object to `encode()`:

```ts
new TextEncoder().encode({});
```

The resulting error is something like:

```ts
error: Uncaught TypeError: Invalid argument
    at TextEncoder.encode (deno:op_crates/web/08_text_encoding.js:1066:21)
    at main.ts:171:27
    at Array.forEach (<anonymous>)
    at main.ts:170:8
```

Due to the ambiguaty of the error, and my confidence is what turned out to be false assumptions about the type of an argument, I went down a long rabbit hole trying to figure out if my program was producing any invalid unicode glyphs or something like that. I think it would be helpful for `encode()` to throw an error more like `TypeError: Invalid argument, must be a string`.

**Comment by kitsonk** [comment]
Actually we should be more spec compliant here...

```ts
new TextEncoder().encode({})
```

Results in the following in Chrome:

```
Uint8Array(15) [91, 111, 98, 106, 101, 99, 116, 32, 79, 98, 106, 101, 99, 116, 93]
```

It is only values that are not coercible to strings that throw.  For example:

```ts
new TextEncoder().encode(Symbol("a"));
```

Results in:

```
Uncaught TypeError: Cannot convert a Symbol value to a string
```

We should leave the type enforcement up to TypeScript.

**Comment by Noah-Huppert** [comment]
Thanks for the quick reply. Yea that seems reasonable. Definitely agree that the type checking should be left up to typescript. Just to be clear the details about types and such was more of an illustration of a tricky debugging situation where a more verbose error would have been nice, and not meant to put any emphasis on type checking.

Since you labeled this as good first issue I thought I'd point readers to the `TextEncoder`source code: https://github.com/denoland/deno/blob/master/op_crates/web/08_text_encoding.js#L1061

**Comment by kitsonk** [comment]
Well, I don't think we shouldn't worry about `Deno.core.encode()`.  It should be a slightly better error on line 604:

https://github.com/denoland/deno/blob/2a36e2f892d6e0855b4e3d927cca399299038f80/core/bindings.rs#L596-L609

But that isn't as important as it is that we should try to coerce to a string in `TextEncoder.encode()`:

https://github.com/denoland/deno/blob/2a36e2f892d6e0855b4e3d927cca399299038f80/op_crates/web/08_text_encoding.js#L1063-L1082

Like something on 1064 that just does `input = String(input)`.  That should likely generate a proper `TypeError` anyways.

**Comment by benjamingr** [comment]
I'll take a look at this - better TypeError doesn't sound correct but @kitsonk 's fix actually seems to generate the correct behaviour (of coercing to string). In the web:

```
encoder.encode({toString() { return "text" }}); // returns Uint8Array(4) [116, 101, 120, 116]
```

I think Deno should behave like the WHATWG spec requires - but still use `string` in its own d.ts for better dx.
