### ISSUE TITLE
deno install not reading flags properly? when --force is used after --allow-net

### ISSUE THREAD

**Issue by phocks** [denoland/deno#8214]
Not sure what is happening and it's only a minor issue, but when I use this command I get this error

`deno install --allow-net -force --name myapp .\index.ts`

`error: Found argument '-o' which wasn't expected, or isn't valid in this context`

If I put `--force` before the `--allow-net` I get no error. And no error if I use the shortened -f

Using deno version 1.5.1

**Comment by nayeemrmn** [comment]
You miswrote it as `-force`. `deno install --allow-net --force --name myapp .\index.ts`

**Comment by phocks** [comment]
Ahh damn 🤦
