### ISSUE TITLE
deno bundle should support type checking worker scripts

### ISSUE THREAD

**Issue by nekdolan** [denoland/deno#8219]
When I try to bundle my worker.ts it raises an error
```
error: TS2339 [ERROR]: Property 'postMessage' does not exist on type 'Window & typeof globalThis'.
        self.postMessage(data);
```
Code
```
self.postMessage(data);
```
In Deno
```
deno 1.5.1
v8 8.7.220.3
typescript 4.0.3
```

**Comment by kitsonk** [comment]
We need to think about this more, but there are two workarounds.

```
> deno bundle --no-check
```

Or:

```
> deno bundle --config tsconfig.json
```

Where the `tsconfig.json` contains:

```js 
{
  "compilerOptions": {
    "lib": [ "deno.worker" ]
  }
}
```

**Comment by nekdolan** [comment]
Thanks @kitsonk `deno bundle --no-check` works

**Comment by kitsonk** [comment]
Actually, I realised I made a comment in the code.

https://github.com/denoland/deno/blob/96e03e0b93bf75035887ce02880b832123e3c86d/cli/main.rs#L344

Ultimately we just need to agree on how to deal with this.  @ry @bartlomieju thoughts?

**Comment by nayeemrmn** [comment]
This is basically #6753 (`deno cache --worker`), the flag would be shared like [similar ones](https://github.com/denoland/deno/blob/5f7c80986fd9cff6a65d4e419fc2972abe992ccf/cli/flags.rs#L503-L513) are.

**Comment by kitsonk** [comment]
@nayeemrmn you are right as usual... `deno bundle --worker` is what it should be, nothing to debate... I forgot we had agreed that for `deno cache`.

**Comment by kitsonk** [comment]
Actually based on #8089 there is clearly things to discuss...

**Comment by nekdolan** [comment]
I'm not sure how it could be done without the proposed/reverted flag `--worker` . I can understand that cache could work without it but how would you keep the linkage when you bundle them, given that you don't know where or how the scripts will be deployed. Would we just keep a relative link to the bundled worker in the script? Would that work on a normal webpage?

**Comment by lucacasonato** [comment]
`deno bundle` was removed in Deno 2.
