### ISSUE TITLE
Benchmark wanted: travis compile time

### ISSUE THREAD

**Issue by ry** [denoland/deno#822]
This should be queryable from travis or github. Just interested in how long people are waiting for their PRs to build. We don't need to store any data locally. I just want to be able to see it on [the benchmark page](https://denoland.github.io/deno/), as this is a major source of problems.

**Comment by kevinkassimo** [comment]
Does recording just time period of `./tools/build.py` suffice for this requirement?

**Comment by ry** [comment]
Yes

**Comment by kevinkassimo** [comment]
Haven't being able to find a nice way to plug travis total time running into benchmark, but there is a simple bash trick with `SECONDS` variable to record total seconds from `before_install` to `./tools/build.py` complete

**Comment by lucacasonato** [comment]
@ry is this still relevant?

**Comment by ry** [comment]
nope
