### ISSUE TITLE
Rewrite "tools/" scripts in Deno

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#8223]
Various utility scripts in `deno` repository, that are used during development and CI, are written in Python. Those are scripts in `tools/` directory. They are used for formatting, linting, parsing benchmarks output, etc. 

I think it would be beneficial to rewrite them to use Deno instead of Python. Doing so would completely remove dependency on Python (unsure about that, `rusty_v8` probably still needs it?) and close #5114 and #2893.

Changes needed to resolve this issue:
- install `deno` in CI script (`.github/workflows/ci.yml`)
- for each script in `tools/`:
   - rewrite the script in `deno`
   - replace invocation of the script to call `deno`

The easiest to rewrite would be `tools/format.py` and `tools/lint.py`. Here are respective example scripts from `deno_lint` repository which can be used as a basis for this refactor:
- https://github.com/denoland/deno_lint/blob/master/tools/format.ts
- https://github.com/denoland/deno_lint/blob/master/tools/lint.ts

**Comment by crowlKats** [comment]
for installing deno in CI script, would be using https://github.com/denolib/setup-deno alright, or rather do it manually?

**Comment by bartlomieju** [comment]
@crowlKats I think we should use [`deno_install`](https://github.com/denoland/deno_install) script

**Comment by MarkTiedemann** [comment]
If you just want to determine the latest Deno executable, download and unzip it, you can do that in a shell or cmd one-liner (or 3-liner, nicely formatted).

```shell
v=$(curl -sSf https://github.com/denoland/deno/releases | grep -o \/denoland/deno/releases/download/.*/deno-x86_64-unknown-linux-gnu.zip | head -1 | cut -d/ -f6)
curl -Lo deno.zip https://github.com/denoland/deno/releases/download/$v/deno-x86_64-unknown-linux-gnu.zip
unzip deno.zip
```
```batch
for /f "delims=/ tokens=6" %%v in ('"curl -sSf https://github.com/denoland/deno/releases | findstr \/denoland/deno/releases/download/.*/deno-x86_64-pc-windows-msvc.zip | findstr /n . | findstr ^1:"') do (
    curl -Lo deno.zip https://github.com/denoland/deno/releases/download/%%v/deno-x86_64-pc-windows-msvc.zip
    tar xf deno.zip
)
```

Both `setup-deno` and `deno_install` deal with edge cases, different arguments, versions, putting Deno in the PATH, etc. If the requirements are simpler than that, you could get away with simpler scripts...

// Note that `curl` and `tar` are installed by default on recent Windows. `unzip` is not available by default on all *nixes.
