### ISSUE TITLE
New prompt method gets confused when receiving special characters as input [ã]

### ISSUE THREAD

**Issue by pedropaulosuzuki** [denoland/deno#8239]
While #8179 got partially fixed by #8199 (nice one btw, thanks for everyone involved!!), the prompt method still has some issues regarding input (related to stdin). For example, the code below doesn't perform as expected when non-ascii characters are used.

```js
const a = prompt('Insert your character');

console.log(`a===a => ${a === 'a'}`);  // When inserting the character 'a', returns true, as expected!
console.log(`ã===ã => ${a === 'ã'}`);  // When inserting the character 'ã', returns false, not what we expected.
```

Opened a new issue because the other one got closed before this got adressed.

**Comment by wperron** [comment]
I tried this with 1.5.1 and I couldn't reproduce. Here's what I tried in the REPL (running Ubuntu 20.04)

```text
Deno 1.5.1
exit using ctrl+d or close()
> 'a' === 'ã'
false
> 'a' == 'ã'
false
> const target = 'ã';
undefined
> const answer = prompt("enter a char");
enter a char ã
undefined
> target === answer
true
```

**Comment by zhmushan** [comment]
As I pointed out in #8492, `const c = new Uint8Array(1)` will cause the read content to be lost (because some characters are more "wider"). This should not be a Windows unique problem.

**Comment by F3n67u** [comment]
Cannot reproduce on my computer. 

```
~ % deno
Deno 1.12.2
exit using ctrl+d or close()
> const a = prompt('Insert your character');
Insert your character ã
undefined
> console.log(`ã===ã => ${a === 'ã'}`);
ã===ã => true
undefined
```

System Info:
MacOs 11.2.3
deno 1.12.2

@pedropaulosuzuki  Can you confirm this is still an issue?

**Comment by pedropaulosuzuki** [comment]
> Cannot reproduce on my computer.
> 
> ```
> ~ % deno
> Deno 1.12.2
> exit using ctrl+d or close()
> > const a = prompt('Insert your character');
> Insert your character ã
> undefined
> > console.log(`ã===ã => ${a === 'ã'}`);
> ã===ã => true
> undefined
> ```
> 
> System Info:
> MacOs 11.2.3
> deno 1.12.2
> 
> @pedropaulosuzuki Can you confirm this is still an issue?

I'd like to, but I dropped Windows on december 31 2020, so now I'm running on Pop!_OS 21.04, on which I cannot test the Windows behaviour with Deno input, unfortunately. Maybe someone with a Windows build could test it and see it the issue persists.

**Comment by ayame113** [comment]
I can confirm that the problem still occurs on windows.
```
Windows 10.0.19042.1110
Deno 1.12.2
```

```shell
C:\Users\azusa>deno
Deno 1.12.2
exit using ctrl+d or close()
> const a = prompt('Insert your character');
Insert your character ã
undefined
> console.log(`ã===ã => ${a === 'ã'}`);
ã===ã => false
undefined
```
Maybe `prompt()` will not accept input of multibyte characters.
```shell
C:\Users\azusa>deno
Deno 1.12.2
exit using ctrl+d or close()
> prompt()
Prompt ã
"a"
> prompt()
Prompt こんにちは
"�����"
>
```

**Comment by caspervonb** [comment]
> Cannot reproduce on my computer.
> 
> ```
> ~ % deno
> Deno 1.12.2
> exit using ctrl+d or close()
> > const a = prompt('Insert your character');
> Insert your character ã
> undefined
> > console.log(`ã===ã => ${a === 'ã'}`);
> ã===ã => true
> undefined
> ```
> 
> System Info:
> MacOs 11.2.3
> deno 1.12.2
> 
> @pedropaulosuzuki Can you confirm this is still an issue?

You're trying to reproduce a Windows bug on a Mac.

**Comment by F3n67u** [comment]
> > Cannot reproduce on my computer.
> > ```
> > ~ % deno
> > Deno 1.12.2
> > exit using ctrl+d or close()
> > > const a = prompt('Insert your character');
> > Insert your character ã
> > undefined
> > > console.log(`ã===ã => ${a === 'ã'}`);
> > ã===ã => true
> > undefined
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > System Info:
> > MacOs 11.2.3
> > deno 1.12.2
> > @pedropaulosuzuki Can you confirm this is still an issue?
> 
> You're trying to reproduce a Windows bug on a Mac.

My bad. I am still learning issue triage.

**Comment by rafawalter** [comment]
This is still an issue.

```
const a = prompt('Insert your character');
console.log(`${a}===a => ${a === 'a'}`);  // When inserting the character 'a', returns true, as expected!
console.log(`${a}===ã => ${a === 'ã'}`);  // When inserting the character 'ã', returns false, not what we expected.
```
```
Insert your character ã
�===a => false
�===ã => false
```

System Info:
Windows 10 Pro 20H2 19042.1083
Deno 1.13.1

**Comment by marvinhagemeister** [comment]
Just tried to reproduce it with the latest Deno release, but wasn't able to. It works as expected for me. Not sure which exact version resolved this, but updating to the latest Deno version will.
