### ISSUE TITLE
Can Apache MPM Event be used to call Deno?

### ISSUE THREAD

**Issue by volomike** [denoland/deno#8243]
Can Apache MPM Event be used to call Deno, such as via `FilesMatch` and `SetHandler`, or perhaps `ProxyPass` and `ProxyPassReverse`?

**Comment by kitsonk** [comment]
That would be more for the Apache MPM community on how to integrate a stand alone binary.  I don't think it is really feasible or doable.  If someone wanted to run JavaScript within Apache HTTPD via MPM, then [rusty_v8](https://github.com/denoland/rusty_v8) could be a way to create a Rust based Apache MPM module, but both are way beyond the scope and intent of the rusty_v8 and Deno project.
