### ISSUE TITLE
std/encoding/binary.ts does not produce same result as go binary pkg

### ISSUE THREAD

**Issue by sunsetkookaburra** [denoland/deno#8250]
there is a mismatch between the two, despite the same function names.
i've been working on a solution and should be able to produce a PR to solve, and allow for varying numbers of any size, not just set data-types, to be inline with go

**Comment by lucacasonato** [comment]
I would actually like to see that module go. It is just a wrapper function over the methods on `DataView`.

**Comment by sunsetkookaburra** [comment]
instead of removing it, i think it should be done how go does it. the go pkg uses the most-significant bit as a bit to say there are more bytes to be read.
[https://golang.org/src/encoding/binary/varint.go](https://golang.org/src/encoding/binary/binary.go)
[https://golang.org/src/encoding/binary/varint.go](https://golang.org/src/encoding/binary/varint.go)
and google uses this method in protobufs [https://developers.google.com/protocol-buffers/docs/encoding](https://developers.google.com/protocol-buffers/docs/encoding).
the real varint involves shifts and other functions that would be good in a module, unlike the wrapped functions currently that don't really do varints as go sees them

**Comment by sunsetkookaburra** [comment]
i'll close this. if i do get a polished and updated version of binary.ts, i'll report back. i don't think its something high on the list right now for std.
