### ISSUE TITLE
Rewrite tests to not depend on Python

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#8254]
After https://github.com/denoland/deno/issues/8223 we no longer rely on Python
for development (unless you're building `rusty_v8` from source). However there
are still quite a few tests that use Python (main for subprocess tests):
- `cli/tests/permission_tests.ts`
- `cli/tests/unit/chown_test.ts`
- `cli/tests/unit/process_test.ts`

It'd be great if we could eventually remove dependency on Python altogether.

**Comment by mrmodise** [comment]
@bartlomieju I will take `cli/tests/unit/chown_test.ts`. If all goes well I will take the rest.

**Comment by mrmodise** [comment]
Had to split them. The process_test.ts needs a bit of attention

**Comment by bartlomieju** [comment]
Solution used in https://github.com/denoland/deno/pull/8404 seems preferable.

**Comment by bartlomieju** [comment]
Fixed in #8291, #8841 and #8843!

**Comment by waldyrious** [comment]
@bartlomieju would it be adequate to change the lines below as well?

https://github.com/denoland/deno/blob/4033b390367e025e73c851a6ce7021631b27e3c0/cli/dts/lib.deno.unstable.d.ts#L1043-L1047

I was thinking something like this to mimic the change in #8291 and #8843:

```diff
    *      const p = Deno.run({
-   *        cmd: ["python", "-c", "from time import sleep; sleep(10000)"]
+   *        cmd: ["sleep", "10000"]
    *      });
```

WDYT?

**Comment by bartlomieju** [comment]
@waldyrious that sounds good, PRs welcome :)

**Comment by waldyrious** [comment]
@bartlomieju I hope you don't mind — since it's a very small change, I embedded it in another PR I was preparing :) I've submitted the changes in #8848.
