### ISSUE TITLE
eval() do not support TypeScript.

### ISSUE THREAD

**Issue by Ayfri** [denoland/deno#8256]
You can't use any typescript features in the native `eval()` function, you can't use `import/export` also, it would be great to be able to use these.

**Comment by RDambrosio016** [comment]
this would probably require overriding the native eval to first detect if its typescript, if so, then start up the entirety of tsc, compile the javascript, ensure there's no errors, then give it to v8 to actually run it. This would incur a huge performance loss because tsc is relatively slow. I don't see benefits in ever allowing this because of that.

**Comment by Ayfri** [comment]
You could add an option `eval(code: string, options?: { ts?: boolean });` like this ?
Or a `Deno.eval()` that will be different than `Deno.run()` as it is run in the local scope.

**Comment by RDambrosio016** [comment]
This would also not work correctly for type checking because eval can grab variables from its scope but the tsc checker does not know about the outer context and eval is invoked at runtime

**Comment by Ayfri** [comment]
And it would require a lot of time to find a way to make it work I suppose?
Can't you "simulate" the variables by declaring them when compiling?

**Comment by RDambrosio016** [comment]
You would have to know what variables are declared in the scope, so either plug into the tsc type checker api, which is complicated, or get it from v8 somehow, also complicated. Overall i don't think the drawbacks outweight the pros:
- Huge performance cost
- Hard to implement correctly
- Most likely causes a lot of technical debt

**Comment by Ayfri** [comment]
Okay, it's too bad...

**Comment by thgh** [comment]
@Ayfri  If you wanted to use import/export, this is a step forwards:
```ts
const mod = await tseval(`
  import { red } from "https://deno.land/std@0.82.0/fmt/colors.ts";
  export function echo(message: string) {
    return red(message)
  }
`)

console.log(mod.echo('hello'))

async function tseval(code: string) {
  const moduleURL = import.meta.url.replace('file://', '') + '$eval.ts'
  await Deno.writeFile(moduleURL, new TextEncoder().encode(code))
  return import(moduleURL)
}
```

**Comment by Ayfri** [comment]
Oh, that is neat!
Thank you!

**Comment by Ayfri** [comment]
I'm getting an error :
```ts

Error: The syntax of the file, directory, or volume name is incorrect. (os error 123)
    at processResponse (deno:core/core.js:223:11)
    at Object.jsonOpAsync (deno:core/core.js:240:12)
    at async open (deno:runtime/js/30_files.js:44:17)
    at async Object.writeFile (deno:runtime/js/40_write_file.js:54:18)
    at async tseval (mod.ts:5:2)
```

**Comment by thgh** [comment]
If you want to use that code from a remote module, you will need to change the moduleURL to a writable path.

But when https://github.com/denoland/deno/issues/5059 is released, it will get easier:
```ts
function tseval (code: string) {
  return import('data:application/javascript,' + encodeURIComponent(code));
}
```

**Comment by sbuettner** [comment]
Just in case you find this ticket and want to run TypeScript:
```
import { encodeBase64 } from "jsr:@std/encoding/base64";

async function tseval (code: string) {
  return import('data:application/typescript;charset=utf-8;base64,' + encodeBase64(code));
}
```

**Comment by Ayfri** [comment]
Thanks, after this time the process to achieve that is now simple!
