### ISSUE TITLE
bundling same module with different local names

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#8258]
I also have a bug with "deno bundle" (deno 1.5 regression), it seems to be the same bug.
I was able to reduce the test size:
![bug](https://user-images.githubusercontent.com/5874319/98298579-86bd6480-1fb6-11eb-9831-4985208570ce.png)
bug.ts:
```
import { posix  } from "https://deno.land/std@0.74.0/path/mod.ts";
import { posix as posix74 } from "https://deno.land/std@0.74.0/path/mod.ts";
console.log( posix.sep, posix74.sep);
```
the script:
```
$ ./deno-1.4.6 bundle ./bug.ts bug.js && ./deno-1.4.6 run ./bug.js
$ ./deno-1.5.1 bundle ./bug.ts bug.js && ./deno-1.5.1 run ./bug.js
```
----
Originally, I got this bug when I launched "deno bundle" on the project https://github.com/jersou/markdown-explorer-server
```
$ deno bundle --unstable https://raw.githubusercontent.com/jersou/markdown-explorer-server/main/server.ts mds.js
$ deno run mds.js
error: Uncaught ReferenceError: _posix is not defined
const path3 = isWindows1 ? _win321 : _posix;
                                     ^
    at file:///home/jer/mds.js:10940:38
```
----
I hope it helps

_Originally posted by @jersou in https://github.com/denoland/deno/issues/8246#issuecomment-722666991_

**Comment by kitsonk** [comment]
@jersou it is a different underlying issue, but still an issue, so I broke it out to its own.

**Comment by kdy1** [comment]
@kitsonk Is this a bug of `swc_bundler`?

**Comment by kitsonk** [comment]
I am not 100% sure yet.  I haven't had the time to try to re-produce or re-create it.

**Comment by lucacasonato** [comment]
@kitsonk Possible dupe of https://github.com/denoland/deno/issues/8530 which is now resolved?

**Comment by kitsonk** [comment]
Yeah looks like a dupe of #8530 though this was first.
