### ISSUE TITLE
Multiple concurrent `trace`s with reordered & postponed `await`s yields unexpected result

### ISSUE THREAD

**Issue by kevinkassimo** [denoland/deno#829]
Code demonstrating the problem:
```ts
import * as deno from "deno";

(async () => {
  const trace1 = deno.trace(async () => await deno.makeTempDir())
  const trace2 = deno.trace(async () => await deno.stat("."))
  console.log(await trace2);
  console.log(await trace1);
})()
```
__Expected output__:
```
[ { sync: false, name: "Stat" } ]
[ { sync: false, name: "MakeTempDir" } ]
```
__Actual output__:
```
[ { sync: false, name: "MakeTempDir" }, { sync: false, name: "Stat" } ]
[ { sync: false, name: "Stat" } ]
```
__Cause__:
Current `trace` implementation assumes user would immediately `await`s for the trace once it is created, so that inner trace (living inside the function/promise being traced) could simply stack on current trace's stack. However, this is no longer true in the sample code, `trace2` would seems to live on top of `trace1`. During popping, the order is reversed (`trace1` popping the `trace2`'s node) and causes the confusing output

@ry is this the bug you discovered before on trace?

**Comment by kevinkassimo** [comment]
My intuition is fix for this might be non-trivial, as there should be no simple way of associating calls (without using `caller`) with their called environment, and that the current `trace` implementation relies heavily on execution order

**Comment by kevinkassimo** [comment]
@ry The main challenge I feel is to give `maybePushTrace` in `sendSync/sendAsync` some hint about which stack it should try to push command info onto. A solution currently in my mind is to create a masked version of `deno` with injected info about the specially created trace stack independent for each `trace` call:
```ts
const ops = await deno.trace(async (deno) => await deno.stat("."));
```
This would require an API change to `trace` (no longer support promises as param) and would also require injecting an extra optional parameter about stack top to all currently APIs, which I feel is probably a very bad idea.

**Comment by im-not-a-programmer** [comment]
232323232323

**Comment by ry** [comment]
trace was removed back in October. closing this issue.
