### ISSUE TITLE
Incorrectly writing tsbuildinfo when check fails

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#8309]
We are incorrectly writing out `.tsbuildinfo` when a build fails, but we don't write out the emitted files.

This means that if you have a problem with code, and you fix it, you can end up in a situation where for some/all of your dependencies their emits don't get committed to disk, but the `.tsbuildinfo` does.  When the issue is fixed, the `.tsbuildinfo` exists and is "valid" which but some of the dependencies haven't changed, and so `tsc` things it doesn't need to do any emits for them, and therefore the emits go "missing".

We need to ensure that we don't flush tsbuildinfo if the module it is associated with is not dirty.

**Comment by jsejcksn** [comment]
Would this also be a cause for stale cache of compiled TS modules?

**Comment by kitsonk** [comment]
No, in theory not, as "stale" would indicate the source file or configuration had changed, which should impact the version and cause `tsc` to emit the file.
