### ISSUE TITLE
Sometimes print "undefined" when close() in REPL since 1.5.0

### ISSUE THREAD

**Issue by KNnut** [denoland/deno#8338]
And 1.4.6 works well.

**Comment by kitsonk** [comment]
cc/ @caspervonb

**Comment by caspervonb** [comment]
Race condition I suppose, the result of calling close is undefined, we check if closing is set before printing eval

**Comment by caspervonb** [comment]
Am unable to reproduce this at all, had like 100-200 runs at it.
`close` and `globalThis.closing` are synchronous so my initial theory of a race was wrong.

**Comment by KNnut** [comment]
@caspervonb Still on latest `master`.
![](https://user-images.githubusercontent.com/9387720/100727943-de0df380-3401-11eb-8a11-166f28f47fa8.gif)
![](https://user-images.githubusercontent.com/9387720/100727952-e1a17a80-3401-11eb-9abd-403475596c8c.gif)

**Comment by caspervonb** [comment]
Yeah forgot, moved the condition to the loop condition.
Have a PR moving it back but this might be wontfix as close isn't necessarily the same as Deno.exit.
