### ISSUE TITLE
Is there a demand for Apollo servers to be compatible with Deno? 

### ISSUE THREAD

**Issue by stellaliao01** [denoland/deno#8350]
Is it feasible to create a module that would allow Apollo servers to work with Deno-oak x Deno-graphql?

**Comment by kitsonk** [comment]
These sort of general questions are not suitable for the Deno issue tracker. Please check out other community resources like Discord (https://discord.gg/deno) or StackOverflow (https://stackoverflow.com/questions/tagged/deno).
