### ISSUE TITLE
TypeError from Deno >= 1.5.1

### ISSUE THREAD

**Issue by oscarotero** [denoland/deno#8355]
Hi.
We have a port of postcss to Deno here: https://github.com/postcss/postcss-deno/tree/master/deno
The code is converted automatically so it keeps synced with the original repository.
From Deno 1.5.1 and upper, we are getting the following error on make the conversion and running the tests:
https://github.com/postcss/postcss/runs/1380656312?check_suite_focus=true#step:5:185
```
Check file:///home/runner/work/postcss/postcss/$deno$test.ts
error: TypeError: Cannot read property 'kind' of undefined
    at Object.isEntityNameExpression (deno:cli/tsc/00_typescript.js:17115:21)
    at serializeMaybeAliasAssignment (deno:cli/tsc/00_typescript.js:48356:42)
    at serializeSymbolWorker (deno:cli/tsc/00_typescript.js:47874:49)
    at serializeSymbol (deno:cli/tsc/00_typescript.js:47825:38)
    at deno:cli/tsc/00_typescript.js:47800:25
    at Map.forEach (<anonymous>)
    at visitSymbolTable (deno:cli/tsc/00_typescript.js:47799:33)
    at serializeAsNamespaceDeclaration (deno:cli/tsc/00_typescript.js:48162:25)
    at serializeModule (deno:cli/tsc/00_typescript.js:48071:25)
    at serializeSymbolWorker (deno:cli/tsc/00_typescript.js:47949:25)
```

The code works fine in Deno 1.5.0. It seems like a Typescript error but I couldn't find anything wrong in the code.
Any hint?

**Comment by kitsonk** [comment]
It is an internal TypeScript error of some sort. The challenge seems that it looks like it is only raised when there is an internal in memory module we are generating for the tests. Will need to do a bit of investigation to narrow down why it is occurring.

**Comment by oscarotero** [comment]
Ok, thank you for the quick reply. Yes, it seems something related with testing.

**Comment by andreubotella** [comment]
This isn't a testing-related to bug; here's a minimal test case that can be run with `deno run`:

```ts
// This must be a .ts file run from `deno run`
import "./dep.js";
```

```js
// dep.js
class CssSyntaxError extends Error {}

CssSyntaxError.default = CssSyntaxError;
```

**Comment by kitsonk** [comment]
It is a testing related bug.  Just because one test case works, doesn't mean there isn't a bug. 😁

**Comment by andreubotella** [comment]
I meant that it isn't a testing-related bug because the error shows up in the above test case even when running `deno run`, rather than `deno test`. The fact that on `postcss-deno` non-test runs don't reach the causing conditions doesn't make it a testing bug.

**Comment by kitsonk** [comment]
Ah, ok, thanks for isolating it a bit better.  I mis-read your comment.  I thought you were point out it as I mis-understood "minimal test case" implied "minimal reproduction".

**Comment by oscarotero** [comment]
Yes, I can confirm that this is the cause of the error.
After removing this code in the Deno conversion (here https://github.com/postcss/postcss-deno/blob/master/to_deno.js#L29) the build works fine now.

In theory, this change would provide better support for typescript (https://github.com/postcss/postcss/pull/1459)

**Comment by oscarotero** [comment]
It seems like the latest version of Deno fixes this error, so I'm closing this.
