### ISSUE TITLE
Make welcome.ts more welcoming

### ISSUE THREAD

**Issue by MarkTiedemann** [denoland/deno#8356]
First run on Windows after reading the readme:

```
C:\> deno run https://deno.land/std/examples/welcome.ts
Download https://deno.land/std/examples/welcome.ts
Warning Implicitly using latest version (0.77.0) for https://deno.land/std/examples/welcome.ts
Download https://deno.land/std@0.77.0/examples/welcome.ts
Check https://deno.land/std/examples/welcome.ts
Welcome to Deno �
```

- Prints a warning
- Prints unicode tofu

Also, if you want to check the script you are supposed to run before running it, a quick `curl` is empty:

```
C:\> curl https://deno.land/std/examples/welcome.ts
```

Since it redirects, `-L` is required.

How about changing the script to:

```typescript
// Copyright 2018-2020 the Deno authors. All rights reserved. MIT license
if (Deno.build.os === "windows") {
  console.log("Welcome to Deno!");
} else {
  console.log("Welcome to Deno 🦕");
}
// Or equivalent:
// console.log(`Welcome to Deno${Deno.build.os === "windows" ? "!" : " 🦕"}`);
```

And placing it at `https://deno.land/welcome.ts` - without any redirects?

**Comment by PaintNinja** [comment]
It should be noted that the [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701) supports emojis and works properly, only the legacy Windows consoles such as conhost show the unknown unicode symbol.

**Comment by MarkTiedemann** [comment]
Similarly, it should be noted that the Windows Terminal is an (optional) app that users can install from the Microsoft Store (if they know that the Microsoft Store exists (and if they know that it contains an app called Windows Terminal)), which had its first stable release half a year ago, whereas the "legacy console" is installed on roughly 90% of desktop computers world-wide.
