### ISSUE TITLE
Suggestion: using new system info crate

### ISSUE THREAD

**Issue by jopemachine** [denoland/deno#8357]
### Issue

The `sys-info` crate seems that it doesn't provide enough APIs for `deno` and `deno`'s node compatibility.

I think in this issue (#7774), `Deno.systemCpuInfo` discarded node compatibility because of it.

### Suggestion

How about using a new crate like [heim](https://github.com/heim-rs/heim)?

### Example

For example, I think the `uptime` function could be implemented by the below code using `heim`

```rust
fn op_uptime(
  state: &mut OpState,
  _args: Value,
  _zero_copy: &mut [ZeroCopyBuf],
) -> Result<Value, AnyError> {
  super::check_unstable(state, "Deno.uptime");
  state.borrow::<Permissions>().check_env()?;

  let uptime = (host::uptime().await?.get::<time::second>() as u32);

  Ok(json!({
    "uptime": uptime
  }))
}
```

This function would be needed to implement node compatibility.

Related issue: #3802.

### Notes

If we need another package other than `heim`, I would be appreciated if you let me know.

**Comment by kitsonk** [comment]
Achieving 100% compatibility with Node.js is not achievable with Deno, nor is it a goal of Deno.

What APIs that are critical that are missing where there are use cases where mocking the API isn't feasible?

heim is a lot of crates, and haven't gone through all the dependencies yet, and it seems like it is fairly slow development that has slowed, wit the biggest version being downloaded being a beta release.  That doesn't feel comfortable having such an "immature" set of a crates in Deno.

**Comment by littledivy** [comment]
Looking at host::uptime https://github.com/heim-rs/heim/blob/master/heim-host/src/sys/linux/uptime.rs - `heim` basically reads `/proc/uptime` on linux.  Adding a heavy dependency for such small task is unnecessary.

**Comment by jopemachine** [comment]
> Looking at host::uptime https://github.com/heim-rs/heim/blob/master/heim-host/src/sys/linux/uptime.rs - `heim` basically reads `/proc/uptime` on linux. Adding a heavy dependency for such small task is unnecessary.

Thanks for letting me know this :)

I think I could implement `uptime` by this method.

I will look into if other methods could be implemented without additional dependencies.

**Comment by bartlomieju** [comment]
I'm -1 on bringing `heim` as dependency. As pointed out it's pretty heavy dependency for the task at hand. Respectfully closing.
