### ISSUE TITLE
$DENO_DIR is empty on Windows

### ISSUE THREAD

**Issue by JerryGreen** [denoland/deno#8361]
```echo
$ bash --version
GNU bash, version 4.4.23(1)-release (x86_64-pc-msys)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

$ deno --version
deno 1.5.2 (71d7482, release, x86_64-pc-windows-msvc)
v8 8.7.220.3
typescript 4.0.5

$ echo $DENO_DIR


```

It results into all my installed scripts are not available as CLI. But I think it's only a tip of iceberg, and more features might be broken.

**Comment by nayeemrmn** [comment]
`DENO_DIR` isn't automatically set, but it doesn't need to be because it has a default. Run `deno --info` to see where it is.

> It results into all my installed scripts are not available as CLI.

This has nothing to do with `DENO_DIR`. Find the directory your scripts are being installed to (it should be outputted when you install them) and add it to your PATH.
