### ISSUE TITLE
cargo test failing

### ISSUE THREAD

**Issue by mayankagarwals** [denoland/deno#8371]
After fetching latest changes from github, cargo test fails

OS : Linux
Distro: Ubuntu Bionic

Output of target/debug/deno --version:
deno 1.5.2 (031a037, debug, x86_64-unknown-linux-gnu)
v8 8.7.220.3
typescript 4.0.5

Following is displayed at the end of cargo test:

```
failures:

---- timeout_clear stdout ----
target_dir /home/i-exceed.com/akanksha.agarwal/Documents/Mayank/deno/target/debug
thread 'timeout_clear' panicked at 'assertion failed: end - start < Duration::new(10, 0)', cli/tests/integration_tests.rs:1943:3
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    timeout_clear

test result: FAILED. 309 passed; 1 failed; 6 ignored; 0 measured; 0 filtered out
```
The failed test is related to issue https://github.com/denoland/deno/issues/7599. So I ran the following code snippet with the same build of deno
```
const handle = setTimeout(() => {
  console.log("timeout finish");
}, 10000);
clearTimeout(handle);
console.log("finish");
```
Output is just ```finish```. Also cargo test timeout_clear passes.

**Comment by iammack** [comment]
After doing some debugging, for some reason on running the test timeout_clear standalone, the values of start and end are:
```Instant { tv_sec: 112379, tv_nsec: 633075245 }, Instant { tv_sec: 112382, tv_nsec: 555510565 }```
while when running cargo test are
```Instant { tv_sec: 111271, tv_nsec: 290439176 }, Instant { tv_sec: 111282, tv_nsec: 547283054 }```. 
Not sure what causes this

**Comment by kitsonk** [comment]
This fails on my local machine as well, I thought we had an issue for it, but I don't think we do.

**Comment by Dygear** [comment]
Same issue on the arm64 build I've done on the Raspberry Pi.

**Comment by lucacasonato** [comment]
I haven't had this test fail in the last couple months. Anyone still run into it?

**Comment by MierenManz** [comment]
I can test it on kubuntu if you want me to

**Comment by bartlomieju** [comment]
I hadn't had this problem in last months as well, closing for now. Please report if issue persists.
