### ISSUE TITLE
regression: deno fmt directory matching fails 

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#8374]
Running deno fmt in this repo: https://github.com/lucacasonato/dext.ts, causes an error since some time after 1.5.2. Possibly related to #8040. I have not been able to narrow it down yet.

```
> deno fmt
error: Is a directory (os error 21)
```

**Comment by magurotuna** [comment]
I'm looking into it. This is likely because `WalkDir` yields not only files but also directories, so `dext.ts` is mistakenly included in the target paths although it is a directory.
