### ISSUE TITLE
Logging error types with stack trace and message

### ISSUE THREAD

**Issue by willm** [denoland/deno#8393]
Currently, when you log an error, it seems the error gets converted to a string using `JSON.stringify()` which loses both the error message and the stack trace. It would be nice if there was a custom way of serialising error types to prevent loss of this information.

```typescript
import * as log from "https://deno.land/std@0.77.0/log/mod.ts";

try {
  throw new Error('something broke');
} catch  (err) {
  const logger = log.getLogger();
  logger.error(err); // will log "ERROR {}"
}
```

Happy to help out with this issue if people think it's a good idea.

**Comment by MarkTiedemann** [comment]
If you don't want to lose the message and stack trace, you can use the `.stack` property of the `Error`, e.g. `logger.error(err.stack)` will print something like:

```
ERROR Error: something broke
    at test.ts:4:9
    at <anonymous> (<anonymous>)
```

**Comment by willm** [comment]
That works, but the problem is that JavaScript allows you to throw non `Error` types so if someone has done something like

```
throw "invalid input";
```
Then `error.stack` will be undefined. Of course the calling code could check that error is an instance of error first before logging. But to me it seems that this should be done in the logging module to prevent having to guard against that in every catch block.

**Comment by ry** [comment]
fixed in https://github.com/denoland/deno/pull/8401
