### ISSUE TITLE
SQLITE3 datetime show different dates

### ISSUE THREAD

**Issue by Desibabe** [denoland/deno#8396]
import { DB } from "https://deno.land/x/sqlite/mod.ts";

// Open a database
const db = new DB("test.db");
db.query("CREATE TABLE IF NOT EXISTS people (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, date DATE)");

db.query("INSERT INTO people (name, date) VALUES ('Ryan', datetime('now','localtime'))");

// Print out data in table
for (const [name,date] of db.query("SELECT name,date FROM people"))
  console.log(name,date);

// Close connection
db.close();

*** Deno Log
Ryan 2020-11-16 01:51:50

*** SQLITE3
SELECT datetime('now', 'localtime');
2020-11-15 19:51:50

*** Version
deno 1.5.2 (71d7482, release, x86_64-pc-windows-msvc)
v8 8.7.220.3
typescript 4.0.5

**Comment by kitsonk** [comment]
Why do you feel this is an issue with Deno and not the 3rd party dependency `https://github.com/dyedgreen/deno-sqlite`?

**Comment by Desibabe** [comment]
Moved to deno-sqlite3. Thanks.
