### ISSUE TITLE
cargo test fails on windows

### ISSUE THREAD

**Issue by iammack** [denoland/deno#8397]
The problem is introduced by this PR: https://github.com/denoland/deno/pull/8291. printf doesn't work on powershell.

**Comment by getspooky** [comment]
Hi @iammack 
Can please share the terminal output error

**Comment by iammack** [comment]
I don't have access to powershell for now. Can you answer this @MarkTiedemann as you have already provided a fix? Thanks!

**Comment by MarkTiedemann** [comment]
Didn't run the test in PowerShell but in cmd, but the result should be the same:

```
error: Uncaught NotFound: The system cannot find the file specified. (os error 2)
```

This is because `printf` cannot be executed on Windows - there's no `printf.exe` binary.

More details: https://github.com/denoland/deno/pull/8404#issuecomment-728340753

**Comment by ry** [comment]
fixed in https://github.com/denoland/deno/pull/8404
