### ISSUE TITLE
1.5.2+, Compiler API types option not considered

### ISSUE THREAD

**Issue by SRNV** [denoland/deno#8406]
`types` are no more considered since 1.5.2. 
not fixed in 1.5.3

```ts
Deno.compile({
  types: [new URL ('../path/to/types.d.ts', import.meta.url).pathname]
})
```

**Comment by kitsonk** [comment]
@SRNV this is intentional, because of the way `tsc` internally handles these options which make them hard to resolve.

What is the use case, because there is likely a better way to accomplish it then using the `types` property in a configuration.

**Comment by SRNV** [comment]
I'm using a declaration file, which embed a JSX's namespace and the jsxFactory/jsxFrag' declaration.
this allows us to not import the `jsxFactory` into the `tsx/jsx` files.

![Screenshot from 2020-11-17 09-44-48](https://user-images.githubusercontent.com/37340675/99367032-b5daac80-28b9-11eb-9a37-a64954c50428.png)

so since 1.5.2 these errors are popped

knowing that the compiler APIs are unstable, is there any alternatives to this ?
