### ISSUE TITLE
Deno.bundle() option target 2015 is invalid in v1.5.2/v1.5.3

### ISSUE THREAD

**Issue by iugo** [denoland/deno#8411]
https://github.com/iugo/deno-with-ts/tree/a290847df25c8ac505afecad3fd5bfe3845d66a4

1. `deno upgrade --version 1.4.6`, `deno run --unstable --allow-all run.ts`.
2. `deno upgrade --version 1.5.3`, `deno run --unstable --allow-all run.ts`.

version | result
-- | --
v1.4.6 | valid
v1.5.0 | valid
v1.5.1 | valid
v1.5.2 | invalid
v1.5.3 | invalid

In v1.5.2+, deno loses the ability to compile.

**Comment by lucacasonato** [comment]
@iugo The repository is private.

**Comment by iugo** [comment]
> @iugo The repository is private.
> 
> cc @kitsonk

Sorry, it has now been fixed.

**Comment by kt3k** [comment]
Do we support `es3` target?

**Comment by satyarohith** [comment]
> Do we support `es3` target? (ref: https://github.com/iugo/deno-with-ts/blob/a290847df25c8ac505afecad3fd5bfe3845d66a4/run.ts )

From [`lib.deno.unstable.d.ts`](https://github.com/denoland/deno/blob/4b2df87c5440a653bffa181bd57964b6fcd01cfc/cli/dts/lib.deno.unstable.d.ts#L461), yes.

FYI: The compiler APIs consolidated into `Deno.emit()` (See https://github.com/denoland/deno/pull/8799).

**Comment by kitsonk** [comment]
ES3 target may or may not work. We don't test for it and if there are issue with it we won't fix them.
