### ISSUE TITLE
UDP DatagramConn.receive doesn’t always settle

### ISSUE THREAD

**Issue by callionica** [denoland/deno#8415]
DatagramConn.receive is a Promise-returning function with no obvious way to cancel other than closing the connection. If a client is awaiting the result of receive, closing the connection should ensure that the promise is settled.

Unfortunately, `close` doesn't always resolve/reject the promise returned by receive.

```ts
Deno.test("udp_repro", async function () {
    // Change sync to false to see the problem hang
    const sync = true;

    const connection = Deno.listenDatagram({
        port: 35353,
        hostname: "0.0.0.0",
        transport: "udp" as const,
    });

    const p = connection.receive();

    if (sync) {
        connection.close()
    } else {
        setTimeout(() => connection.close(), 1000);
    }

    console.log("Awaiting receive");
    await p; // We expect a settlement of some kind here - a failure is OK
});
```

In the code above, you get the expected failure when `sync` is true (expected), but you get a hang when `sync` is false (unexpected).

This behaviour can result in user code hanging, or it can result in reports about async ops being leaked.

**Comment by Soremwar** [comment]
Tested on latest canary, both async and sync close work correctly.

If the timeout for async is increased and a package is received before close the test suite will finish the test and report the resource as still open, so everything is expected behavior regarding this.
