### ISSUE TITLE
WebSocket: Client doesn't send closing control code on SIGINT

### ISSUE THREAD

**Issue by timonson** [denoland/deno#8419]
Closing a running deno client process with Ctrl-C will not result in an appropriate *control code* on the server side.

**Comment by MarkTiedemann** [comment]
@timonson Not sure whether that's a bug or working as intended.

If you want to close the connection properly, you may be able to do that by [handling SIGINT](https://deno.land/manual@v1.5.3/examples/os_signals) and calling [`WebSocket#close`](https://doc.deno.land/builtin/stable#WebSocket) before exiting the Deno process (but I haven't tried it yet).

**Comment by timonson** [comment]
Yeah I am starting to believe that it is a WebSockets issue on the back end because I don't receive a control code using the browser neither (and I am not 100% familiar with the spec). So this might actually be *intended*, as you stated @MarkTiedemann .

But, when I close the connection, e.g. by closing the browser window, the deno server throws the following error which I am not able to catch correctly and always kills the process.

> error: Uncaught (in promise) BrokenPipe: Broken pipe (os error 32)
    at unwrapResponse (deno:cli/rt/10_dispatch_minimal.js:59:13)
    at sendAsync (deno:cli/rt/10_dispatch_minimal.js:98:12)
    at async write (deno:cli/rt/12_io.js:117:20)
    at async Object.writeAll (deno:cli/rt/13_buffer.js:223:19)
    at async BufWriter.flush (bufio.ts:468:7)
    at async writeFrame (mod.ts:141:3)

It is kinda strange because the error goes through one of my `catch` statements first but it still terminates the process afterwards.

**Comment by MarkTiedemann** [comment]
@timonson I think there should be a way to catch the broken pipe error. If not, this is a bug indeed.

Can you post a reproduction?

**Comment by timonson** [comment]
Hi @MarkTiedemann , I am able to catch the error now. The reason was that I forgot to put `await` in front of `socket.send()`. I must have removed it between my last two posts here.

Such a `BrokenPipe` error happens, when you close the connection from the client side while the server waits for an async function from a previous message to end. My main issue here is, that the server doesn't receive the following closing control code when this error happens. Therefore I have to put *clean up* functions both to the `isWebSocketCloseEvent` handler and the `catch` statement. But I don't know if it would be even possible to improve this. Here is a small reproduction: https://github.com/timonson/salad/tree/master/webSocket

But another thing I wrote before was wrong. The browser actually sends the closing control code `1001` to the server when the client closes the connection automatically. This doesn't happen using the deno client and `CTRL-L`. I don't think this is a big deal but maybe something to keep in mind.

**Comment by mvolkmann** [comment]
I am hitting what I believe is the same issue. I start my Deno WebSocket server and connect to it from a browser client successfully. The server sends a message to the client(s) every 5 seconds. If I close the browser tab, the next time the server tries to send a message to that client I get a "Broken pipe" error. That part is reasonable. The problem is that I can't catch it and my server crashes. Here is my server code:

```ts
import {serve} from 'https://deno.land/std@0.80.0/http/server.ts';
import {
  acceptWebSocket,
  WebSocket
} from 'https://deno.land/std@0.80.0/ws/mod.ts';

let clients: WebSocket[] = [];

async function addClient(client: WebSocket) {
  clients.push(client);
}

async function reload() {
  const event = 'reload';
  for (const client of clients) {
    try {
      if (!client.isClosed) await client.send(event);
    } catch (e) {
      client.close();
    }
  }

  clients = clients.filter(client => !client.isClosed);
}

setInterval(reload, 5000);

const PORT = '1234';
for await (const req of serve(':' + PORT)) {
  const {conn, r: bufReader, w: bufWriter, headers} = req;
  try {
    const sock = await acceptWebSocket({conn, bufReader, bufWriter, headers});
    addClient(sock);
  } catch (e) {
    console.error(`failed to accept WebSocket: ${e}`);
    await req.respond({status: 400});
  }
}
```

**Comment by MarkTiedemann** [comment]
@mvolkmann Have you tried putting a `try { await client.close(); } catch { /* Ignore broken pipe error */ }` around the `client.close` in your `reload` function?

**Comment by mvolkmann** [comment]
Good idea. But I tried it and got the same result. The server still crashes with "BrokenPipe" after the client is terminated.

**Comment by MarkTiedemann** [comment]
@mvolkmann Hmm, the server doesn't crash on my machine running Deno `1.6.0` on Windows. With the following minimal example, I can properly catch the `ConnectionAborted` errors - as expected.

```typescript
import { serve, ServerRequest } from "https://deno.land/std@0.73.0/http/server.ts";
import { acceptable, acceptWebSocket, WebSocket } from "https://deno.land/std@0.73.0/ws/mod.ts";

let wss: WebSocket[] = [];

async function reload() {
  for (let i = 0; i < wss.length; i++) {
    let ws = wss[i];
    if (ws.isClosed) {
      wss.splice(i, 1);
      i--;
    } else {
      try {
        await ws.send(performance.now().toString());
      } catch (e) {
        console.error("[Error: send]", e);
        try {
          await ws.close();
        } catch (e) {
          console.error("[Error: close]", e);
        } finally {
          wss.splice(i, 1);
          i--;
        }
      }
    }
  }
}

setInterval(reload, 1000);

async function handleWebsocket(req: ServerRequest) {
  try {
    let ws = await acceptWebSocket({ bufReader: req.r, bufWriter: req.w, ...req });
    wss.push(ws);
  } catch (e) {
    console.error("[Error: acceptWebSocket]", e);
  }
}

function handleHttp(req: ServerRequest) {
  req.respond({
    body: `
    <!DOCTYPE html>
    <script>
        let ws = new WebSocket("ws://" + location.host);
        ws.onmessage = (ev) => document.write(ev.data + "<br>");
    </script>`,
  });
}

for await (let req of serve({ port: 3000 })) {
  if (acceptable(req)) {
    handleWebsocket(req);
  } else {
    handleHttp(req);
  }
}
```

What happens if you `deno run --allow-net` the code above, `open localhost:3000`, wait 1 second, then close the browser tab? On my machine, I get two `ConnectionAborted` errors -  one when `ws.send` fails and one when `ws.close` fails. The server is not affected, though.

**Comment by mvolkmann** [comment]
I get a BrokenPipe error just like with my code. I'm running in macOS 10.15.7 (Catalina) with Deno 1.6.1.

**Comment by MarkTiedemann** [comment]
@mvolkmann I also get a `BrokenPipe` error on MacOS when closing a tab with an open websocket connection in Chrome. This does not crash the server, however.

I don't get an error on MacOS when using Firefox.

Which browser are you using?

**Comment by mvolkmann** [comment]
I am using Chrome. I’d be happy to ru any tests you’d like to help isolate the issue.

---
R. Mark Volkmann
Object Computing, Inc.
