### ISSUE TITLE
Deno.iter Sometimes Doesn't Read The Full Message

### ISSUE THREAD

**Issue by ebebbington** [denoland/deno#8425]
**I will note**:  This may be down to 'thats just how it works'

Using `for await (const chunk of Deno.iter(conn))` (`conn` being Deno.Conn`), it doesn't **always** read the whole data, so essentially what happens is, what **should be 1 event** received from the socket, turns into two because there is still data left unread. 

Eg

```
Data:

Action: Hello
Event: Ev
```

Turns into:
```
for await (const chunk of Deno.iter(conn)) {
  const data = decoder.decode(chunk) // "Data:\n\n" on first event, "Action: ...\r\n" on second, but it should be one event
}
```

Should it function. like this? I've tested reading the event using `BufReader#readFull` and i get the **whole response** **every time**

**Comment by ebebbington** [comment]
Alternatively, are the any **other** methods to read/receive a message from a socket connection within Deno? (be it std, or through the API) that will read the full message)

**Comment by nayeemrmn** [comment]
`Deno.readAll(conn)` to read everything from the connection, but that's most likely not what you're looking for. Note that the boundaries of a "message" are defined by your application. Using `BufReader` for this seems like the right way to go.

**Comment by ebebbington** [comment]
The only problem I had with the `BufReader` is `readFull` needs to take a byte length for the message, but for example, i'd need to use `readFull(new Uint8Array(180)`, `80` and so on.

Should `Deno.iter()` act the way it does above?

**Comment by nayeemrmn** [comment]
@ebebbington The length you're giving it is likely why `readFull()` gives you what you want it to. `Deno.iter()` (which is a thin wrapper around `Deno.read()`) is behaves as expected.

**Comment by ebebbington** [comment]
Hm, alright then :/ I'll close this then - do you know if there is a way to do a '`readFull`' without passing a byte length?

**Comment by nayeemrmn** [comment]
> do you know if there is a way to do a '`readFull`' without passing a byte length?

You're trying to delimit the data into application-level "messages", right now you're using an overestimate of its length to do that. Find an alternative way of parsing isolated messages.

If each of your messages end with `\r\n`, the following may work:
```ts
import { readStringDelim } from "https://deno.land/std@0.78.0/io/mod.ts";

for await (const message of readStringDelim(conn, "\r\n")) {
  console.log(message); // "Data:\n\nAction: ..." on first event, and so on...
}
```

**Comment by ebebbington** [comment]
yo @nayeemrmn... I think that solves it... !!! 🎉 I am having to use `\r\n\r\n` as the delimeter, but i am consistently getting the exact data, and it isn't split across several events! This has just saved me maintaining horrible code, time for some refactoring ;). Thanks @nayeemrmn, i appreciate the support and answers
