### ISSUE TITLE
Refactoring TypeScript pushes `deno` into trying to run stale type analysis in refactored code

### ISSUE THREAD

**Issue by icyJoseph** [denoland/deno#8429]
Hi!

I've been practicing for Advent of Code rewriting my solutions to run in Deno. However I often run into this situation:

```
Check file:///home/joseph/dev/advent_of_code/2019/deno/two.ts
error: Uncaught (in promise) TypeError: machineA.writeAt(...).writeAt(...).tick is not a function
await machineA.writeAt(1, 12).writeAt(2, 2).run();
```

The types are stale, because I did rename `tick` to `run`. The type analysis finds `tick`, and then when printing the error, shows the refactored line.

What is going on? The only way to break out is to add a new line.

**Comment by kitsonk** [comment]
What version of Deno are you using and what does your command line look like?

**Comment by icyJoseph** [comment]
I should've included that from the start...

```
➜ deno --version
deno 1.5.2 (71d7482, release, x86_64-unknown-linux-gnu)
v8 8.7.220.3
typescript 4.0.5

➜ deno --allow-read nine.ts
```

However, I have a small and reproducible (I hope) setup.

```
// mod.ts
type Operations = {
  sum: (...args: number[]) => number;
};

export const operations = (): Operations => {
  return {
    sum: (...args) => args.reduce((acc, curr) => acc + curr, 0)
  };
};

```
And 

```
// main.ts
import { operations } from "./mod.ts";

console.log(operations().sum(1, 2, 3));

``` 

1. Change in either `mod.ts` or `main.ts` the word `sum` to `add`. 
> I choose `main.ts` as first file.
2. Run `deno main.ts`

```
➜ deno run main.ts
Check file:///home/dev/temp/deno_demo/main.ts
error: TS2339 [ERROR]: Property 'add' does not exist on type 'Operations'.
console.log(operations().add(1, 2, 3));
                         ~~~
    at file:///home/dev/temp/deno_demo/main.ts:3:26
```
3. Go to the second file (in this case `mod.ts`) to **fix the type issue**
4. Run again `deno main.ts`

```
➜ deno run main.ts
Check file:///home/dev/temp/deno_demo/main.ts
error: Uncaught TypeError: operations(...).sum is not a function
console.log(operations().add(1, 2, 3));
                         ^
    at file:///home/dev/temp/deno_demo/main.ts:3:26
```

> No amount of change in the second file fixes this. For example, add another function.

```
// mod.rs
type Operations = {
  add: (...args: number[]) => number;
};

const what = () => console.log(what.name);

export const operations = (): Operations => {
  return {
    add: (...args) => args.reduce((acc, curr) => acc + curr, 0)
  };
};

```

5. Run `deno run main.ts` again
```
➜ deno run main.ts
Check file:///home/dev/temp/deno_demo/main.ts
error: Uncaught TypeError: operations(...).sum is not a function
console.log(operations().add(1, 2, 3));
                         ^
    at file:///home/dev/temp/deno_demo/main.ts:3:26
```

6. Try and run `deno run mod.ts` and then `deno run main.ts`. No luck.
7. Modify `main.ts` and run `deno run main.ts`

```
➜ deno run main.ts
10
```

Is this expected? or am I not understanding a core concept of Deno? 

If I change `sum` to `add` or vice-versa on both files before running `deno run main.ts` then it's all good.

**Comment by kitsonk** [comment]
Thanks for the information.  Need to work through it a little bit to figure out what is actually going on, and if it is expected or not.  It seems like you might have found a "loophole" in how we detect changes to files and invalidate the cached output of TypeScript.  We detect changes not on the modified time of the file, but in the contents of the file.  That hash is stored in two places, in the cache itself, and in the incremental `.tsbuildinfo` file.  That file gets written for each `deno run` that you do, _if_ the `run` succeeds without type errors.  So what I think is happening is interplay between the state of the cached file and the state of the `.tsbuildinfo` from previous runs.

What we might need to do is follow up #8311 with a change that actually removes any cached `.tsbuildinfo` if the diagnostics fail, instead of preserving it from previous runs.

**Comment by bartlomieju** [comment]
We've had massive refactors to this part of the codebase in recent months, that completely overhauled integration with TypeScript. This issue should no longer occur and I'm going to tentatively close it. Please let us know if the problem persists on the latest version.
