### ISSUE TITLE
(std/encoding/toml) date parse error

### ISSUE THREAD

**Issue by lisonge** [denoland/deno#8433]
```ts
import { parse } from 'https://cdn.jsdelivr.net/gh/denoland/deno@std/0.78.0/std/encoding/toml.ts';
console.log(parse(`sign='2020-01-01x'`));
```

will output
`
{ sign: Invalid Date }
`

but it  should output
`
{ sign: "2020-01-01x" }
`

Is this my mistake?

**Comment by MarkTiedemann** [comment]
> Is this my mistake?

No, this is a bug. According to the [spec](https://github.com/toml-lang/toml/blob/master/toml.abnf), the value of your `sign` key is of type string, not date.
