### ISSUE TITLE
Remove Deno.applySourceMap()

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#8436]
I believe we should remove `Deno.applySourceMap` API. 

Currently this API is used internally to remap error stack frames because of missing V8 APIs (https://github.com/denoland/deno/issues/7644) but in my opinion it's quite misleading
and has no practical applications for users. `Deno.applySourceMap` actually just maps location
using source map and provides no way to apply source map to code snippet. 

So I propose to remove public `Deno.applySourceMap()` and keep existing op as an internal 
op (similar to `op_start`) until #7644 is resolved. Making this API internal is useful for preparing
"lean binary" and https://github.com/denoland/deno/issues/7928.

CC @kitsonk

**Comment by kitsonk** [comment]
The API is useful when users implement `.prepareStackTrace()` themselves, for things like logging libraries.
