### ISSUE TITLE
Support new JSX transforms

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#8440]
React 17 introduced [new JSX transforms](https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html) and they are available in [TypeScript 4.1](https://devblogs.microsoft.com/typescript/announcing-typescript-4-1/#jsx-factories).  There are two new options for `"jsx"` in TypeScript:

- `"react-jsx"`
- `"react-jsxdev"`

Currently with _check_ these should be supported without any further changes, but are unsupported in `--no-check` and `deno bundle`.

We need support from swc before integrating.  Ref: https://github.com/swc-project/swc/issues/1103

cc/ @kdy1

**Comment by shadowtime2000** [comment]
It seems support has been added to SWC, just wondering - what exactly is left that is blocking support for this?

**Comment by kitsonk** [comment]
A fair amount, as we need to integrate it and test it. It landed too close to 1.8 for us to do the remaining work, so it will likely be in 1.9.

**Comment by kitsonk** [comment]
I have kept kicking this down the road, but I have started this now.  A couple notes so far...

- tsc "blindly" take whatever is in `--jsxImportSource` and appends onto it `/react-runtime` or `/react-dev-runtime`. Same behaviour with swc.  This causes a bit of a problem, because we always expect specifiers to end in an extension.  We can insert some "magic" based on the settings/configuration, but it means we need to add it to the dependency analysis as well, to pickup the `@jsxImportSource` pragmas.
- Both tsc and swc support `@jsxImportSource` pragmas.
- swc doesn't appear to be changing the import with `react-jsxdev` setting.  I am not 100% sure if that is my code or not, need to investigate more.

**Comment by kdy1** [comment]
If required, I'm open to accepting a trait to override logic for determining import sources.

**Comment by kitsonk** [comment]
> If required, I'm open to accepting a trait to override logic for determining import sources.

Thank you. At the moment, swc is "behaving" like I expect. Considering the behaviour is consistent between swc and tsc, it feels like it would be better to have the Deno module graph do the "magical" resolution.

**Comment by kitsonk** [comment]
Need https://github.com/swc-project/swc/issues/1933 resolved, but there are other challenges beyond that (mostly how to deal with the types when using the transforms).

**Comment by kitsonk** [comment]
swc-project/swc#1933 has been fixed now... will get back to this soon-ish

**Comment by kitsonk** [comment]
Not going to be able to address this for 1.14.  There are still some barriers in how we deal with resolving auto-imported specifiers.
