### ISSUE TITLE
Cargo install failure

### ISSUE THREAD

**Issue by faith** [denoland/deno#8453]
When ran cargo install using `cargo install deno` it failed with a error of (also sorry for not adding a code block as i couldn't find a way to add multiple line code block)

error[E0308]: mismatched types                     --> /home/aldas/.cargo/registry/src/github.com-1ecc6299db9ec823/deno-1.5.3/main.rs:470:7         |                                           470 |       syntax,                                 |       ^^^^^^ expected enum `swc_ecma_parser::Syntax`, found enum `swc_ecmascript::swc_ecma_parser::Syntax`                                    |                                               = note: perhaps two different versions of crate `swc_ecma_parser` are being used?                                                           error[E0308]: mismatched types                     --> /home/aldas/.cargo/registry/src/github.com-1ecc6299db9ec823/deno-1.5.3/main.rs:480:60        |                                           480 |       .parse_with_reexports(&module_specifier.to_string(), syntax)                            |                                                            ^^^^^^ expected enum `swc_ecma_parser::Syntax`, found enum `swc_ecmascript::swc_ecma_parser::Syntax`                               |                                               = note: perhaps two different versions of crate `swc_ecma_parser` are being used?                                                           error[E0308]: mismatched types                     --> /home/aldas/.cargo/registry/src/github.com-1ecc6299db9ec823/deno-1.5.3/lint.rs:132:13        |                                           132 |     .syntax(syntax)                           |             ^^^^^^ expected enum `swc_ecma_parser::Syntax`, found enum `swc_ecmascript::swc_ecma_parser::Syntax`                              |                                               = note: perhaps two different versions of crate `swc_ecma_parser` are being used?                                                           error: aborting due to 3 previous errors                                                        For more information about this error, try `rustc --explain E0308`.                             error: failed to compile `deno v1.5.3`, intermediate artifacts can be found at `/tmp/cargo-installywQu0o`

**Comment by faith** [comment]
Seems to be fixed

**Comment by bnoordhuis** [comment]
What version of cargo/rustc are you using?

By the way, wrapping text in triple backticks renders it as a code block.

**Comment by faith** [comment]
> What version of cargo/rustc are you using?
> 
> By the way, wrapping text in triple backticks renders it as a code block.

rustup 1.22.1 (b01adbbc3 2020-07-08)
rustc 1.48.0 (7eac88abb 2020-11-16)
cargo 1.48.0 (65cbdd2dc 2020-10-14)

**Comment by bartlomieju** [comment]
@faith it seems like an intermittent failure caused by upgrade of some crates. `cargo install` should work properly with latest version.
