### ISSUE TITLE
Add support for moving cursor with ctrl key in REPL

### ISSUE THREAD

**Issue by TheWizardBear** [denoland/deno#8454]
Currently, you can move the cursor left and right with the arrow keys, but it would be nice if using `ctrl` was also supported, so that when `ctrl`+`left` is pressed it will jump to the begging of a block of characters (and to the end with `ctrl`+`right`) and when `ctrl`+`delete` is pressed all of the text to the right of the cursor that is in the same block of characters will be deleted (and the left side with `ctrl`+`backspace`).

For comparison, this is how the node REPL behaves:
If you have the following line (where the cursor is at the very left):
`let foo = "hello world";`
pressing `ctrl`+`right` will first move the cursor to the `f`, then to the `=`, then the `h`, then the `w`, then the `"`, and finally the end of the line.

Of course, it doesn't have to work exactly the same way, but it would be nice to be able to do something like this, as currently `ctrl`+`left`, `ctrl`+`right` and `ctrl`+`delete` don't do anything at all and `ctrl`+`backspace` behaves the same as `backspace`.

**Comment by bartlomieju** [comment]
FYI currently REPL supports Emacs key bindings.

CC @caspervonb

**Comment by caspervonb** [comment]
Yeah we're using the default readline bindings at the moment, in other words emacs bindings.
You move between words with alt, seems that node has the same behavior, I get the same behavior in both deno and node here and can't spot any defects in the bindings.

**Comment by hayd** [comment]
On the update to 7.0.0 ctrl+left and ctrl+right are supported https://github.com/kkawakam/rustyline/issues/146

(I agree that it'd be nice to add ctrl+delete as well... perhaps worth adding an issue on rustyline?)

**Comment by caspervonb** [comment]
Will bump rustyline dep :)

**Comment by TheWizardBear** [comment]
Also `shift`+`left`/`right` (and `ctrl`+`shift`+`left`/`right`) to select text would be nice too, although I don't know if this would be possible.

**Comment by caspervonb** [comment]
Defects where the mappings don't match say, bash should probably be brought up in the upstream rustyline repository as preferably we won't have anything custom, at-least not for the basic editor.

**Comment by hayd** [comment]
For the ctrl+delete issue, i think it makes sense to ask for this on rustyline, IMO deno shouldn't be adding in/deciding on a bunch of random shortcuts.... but if they are in rustyline then deno gets them for free :) (and so do all of rustyline's users)
