### ISSUE TITLE
Question: How to determine which V8 flags are supported?

### ISSUE THREAD

**Issue by 00ff0000red** [denoland/deno#8467]
I'm trying to find what flags that Deno supports, and which ones it doesn't.

I wanted to opt into all of V8's experimental Wasm flags, for example, Chrome's "#enable-experimental-webassembly-features" flag.

In my Linux shell, I could pass `--v8-options` to Node.js and get a list of supported flags, yet Deno seems to not offer such functionality.

```bash
node --v8-options;
```

The [Deno manual](https://deno.land/manual@v1.5.2/getting_started/command_line_interface#other-runtime-flags) didn't give much on the flag. Is there a way to check the supported flags, and is there a documentation page on it?

**Comment by lucacasonato** [comment]
`deno run --v8-flags="--help" -`

**Comment by 00ff0000red** [comment]
@lucacasonato Okay, that worked thank you.

But, might I ask where this was documented, so that I may review what I had overlooked?

**Comment by bnoordhuis** [comment]
@00ff0000red The generic `--help` flag mentions it:
```
$ deno eval --help | grep v8-flags
        --v8-flags=<v8-flags>         
            Set V8 command line options (for help: --v8-flags=--help)
```

**Comment by 00ff0000red** [comment]
@bnoordhuis
Didn't know about `deno eval --help`, thank you.
