### ISSUE TITLE
bundle error： export namespace

### ISSUE THREAD

**Issue by sdweiyu** [denoland/deno#8478]
deno@v1.5.4

_mod.ts_
```
export namespace Bar {
  export function foo() {
    console.log("foo");
  }
}
```
_main.ts_
```
import { Bar } from "./mod.ts";
Bar.foo();
```

```bash
deno bundle main.ts main.bundle.js
```

but _main.bundle.js_:
```
Bar.foo();
```

```bash
deno run main.bundle.js
```

```
error: Uncaught ReferenceError: Bar is not defined
Bar.foo();
.....
```

**Comment by lucacasonato** [comment]
cc @kdy1

**Comment by kitsonk** [comment]
I am not sure this is a bug as TypeScript `namespace` is generally not supportable by things like swc or Babel (see: https://babeljs.io/docs/en/babel-plugin-transform-typescript#impartial-namespace-support).  I think we should really really really discourage the use of `namespace` in Deno for non-type-only dependencies.  While it won't be removed from TypeScript, there are a lot better ways to write code like this.

Is there a reason what `namespace` is being used?

**Comment by kdy1** [comment]
`swc` does not suport namespace, although there's  a request for it.
But I'm not sure if implementing it would worth.

**Comment by bartlomieju** [comment]
Should be fixed in https://github.com/denoland/deno/pull/9374
