### ISSUE TITLE
path.relative uses Deno.cwd() implicitly

### ISSUE THREAD

**Issue by whosmayank** [denoland/deno#8487]
```path.relative``` in the std library uses ```Deno.cwd()``` implicitly. This would require the user to allow read access to cwd. I can't think of a way to implement ```path.relative``` without using ```Deno.cwd()``` though. Inputs are appreciated !:)

**Comment by iammack** [comment]
The solution here is to introduce `fs.relativePath` as fs api's are assumed to use priviliged api's like `Deno.cwd()`. Refer https://github.com/denoland/deno/pull/8387. I've started to work on it:)
