### ISSUE TITLE
"prompt" should support utf8

### ISSUE THREAD

**Issue by zhmushan** [denoland/deno#8492]
```ts
const msg = prompt();
console.log(msg);
```
Then enter `你好`, it outputs `�`.
It looks like we should reconsider the implementation of `readline`

https://github.com/denoland/deno/blob/d40b0711a786d04b5e6321ae9bbf73c11220e865/cli/rt/41_prompt.js#L48-L73

**Comment by bartlomieju** [comment]
Duplicate of https://github.com/denoland/deno/issues/8239, let's continue there
