### ISSUE TITLE
contributing Style Guide JavaScript vs. TypeScript

### ISSUE THREAD

**Issue by mvolkmann** [denoland/deno#8522]
I heard on a podcast recently that Deno now uses JavaScript instead of TypeScript internally for performance reasons. But the page at https://deno.land/manual@v1.5.4/contributing/style_guide still says "Use TypeScript instead of JavaScript." Should that be changed?

**Comment by magurotuna** [comment]
Indeed JavaScript is used in Deno, but note that it's _internally_. This "internally" points to the codes that are directly loaded by V8 (JS engine).
High-level codes, including standard libraries, are recommended to be written in TypeScript. TypeScript is certainly the first citizen in Deno.
