### ISSUE TITLE
Parse errors from SWC could be better

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#8529]
Currently if SWC parser encounters error its output is pretty minimal:

```ts
import b, { c } from "./b.js";

console.log(b);
console.log(c
```

```
error: Unexpected eof at file:///Users/biwanczuk/dev/deno/a.js:4:13
```

It'd be great if produced error could contain snippet of code pointing to problematic bit of code, similar to errors from TS and V8:

```ts
import b, { c } from "./b.js";

foo
console.log(b);
console.log(c);
```

```
error: Uncaught ReferenceError: foo is not defined
foo
^
    at file:///Users/biwanczuk/dev/deno/a.js:3:1
```

CC @kdy1

**Comment by kdy1** [comment]
Did you provide `Lrc<SourceMap>` to the `Handler` from `swc_common`?
If then, it should point the error just like rustc.

There are some error reporting tests. 
See: https://github.com/swc-project/swc/tree/8ca3d1160db804322724a6e30181e9c86bdd396a/ecmascript/parser/tests/typescript-errors

**Comment by bartlomieju** [comment]
@kdy1 doesn't look like it, here's our handler:
https://github.com/denoland/deno/blob/d9b41828684a5e1ed620d7324ad6c27a83687622/cli/ast.rs#L381-L388

Unfortunately I can't find API that would allow to pass `Lrc<SourceMap>` and not emit to tty.

**Comment by kdy1** [comment]
Oh, you are correct. It accepts `Lrc<SourceMap>` only if `tty-emitter` is enabled.

I'll see if I can make a handler with cm but without tty.

**Comment by bartlomieju** [comment]
> Oh, you are correct. It accepts `Lrc<SourceMap>` only if `tty-emitter` is enabled.
> 
> I'll see if I can make a handler with cm but without tty.

Thanks @kdy1!

**Comment by kdy1** [comment]
You can now update `swc_common` and use [`EmitterWriter`](https://docs.rs/swc_common/0.10.6/swc_common/errors/emitter/struct.EmitterWriter.html)

**Comment by bartlomieju** [comment]
@kdy1 thank you, that was very fast turnaround!

**Comment by bartlomieju** [comment]
Reference implementation: https://github.com/swc-project/swc/blob/46b553ecc3efd3ddcaff6531535b27526dc16781/testing/src/string_errors.rs#L11-L30

**Comment by kdy1** [comment]
Does it work?
I expect it to work correctly as the parser test successed, but just to be sure.
