### ISSUE TITLE
`deno --watch` is very slow in Docker

### ISSUE THREAD

**Issue by ebebbington** [denoland/deno#8531]
I have two projects that use `deno --watch`:

Project 1 - When making file changes, app restarts pretty much instantly

Project 2 - When making file changes, app can take from 1s to 31.59s to restart, all whilst i'm sitting there doing nothing, watching the terminal for 30+ seconds.

The difference between the two projects is project 2 is a lot larger. Not sure what causes the restart process to take a looong time

Project 1: https://github.com/ebebbington/chatsterisk
Project 2: https://github.com/drashland/deno-drash-realworld-example-app

**Comment by mvolkmann** [comment]
It would be interesting to know if using `denon` is faster. Maybe it uses a different approach.

**Comment by magurotuna** [comment]
The file watcher resolves module dependency every time it detects file change since Deno v1.5.4, so the bigger dependency your project has, the more time it takes when restarting.
Every time dependency resolution is required because otherwise the watcher cannot detect a change on a new file.
But taking 30 sec is too long (I didn't expect it to be that longer), we should consider some solution.

**Comment by magurotuna** [comment]
I've come up with two solutions:

1) makes the watcher take an argument that indicates "which directory a user wants it to observe"

Example: `deno run --watch --unstable foo.ts /path/to/some/directory` -> `foo.ts` would be ran and the watcher would observe the files in `/path/to/some/directory` and its descendant. Every time dependency resolution would not be necessary.

2) adds another flag like `--resolve-dep`. Iff this flag is present, the watcher would resolve dependency whenever it restarts. If it's not present, the watcher would observe files that were resolved at the initial attempt, so it would be fast to restart.

**Comment by bartlomieju** [comment]
@ebebbington does cold start for project 2 without watcher takes 30s as well? If not, then it's clearly some quirk in watcher.

**Comment by ebebbington** [comment]
@bartlomieju what does a "cold start" mean? sorry

I'm guessing you mean how long the takes for the app to start - which i will check now just in case that is what you mean

**Comment by ebebbington** [comment]
Ill get some more real timings, give me 10 mins

**Comment by bartlomieju** [comment]
> @bartlomieju what does a "cold start" mean? sorry
> 
> I'm guessing you mean how long the takes for the app to start - which i will check now just in case that is what you mean

Yeah I meant just running the project using `deno run`

**Comment by ebebbington** [comment]
Allow at least 1 second or less for the differences due to human reflexes of pressing stop on a stopwatch :)

Running the app inside docker with `--watch`: `11.02s`

Running the app inside docker without `--watch`: `11.53s`

Running the app outside docker with `--watch`: `5.95s`

Running the app outside docker without `--watch`: `5.16s`

Time taken for app to **trigger** a restart with `--watch` inside docker when adding `console.log('test')`: `50.86s`

Time taken for app to **start** the app after a restart inside docker: `6.79s`

**Comment by bartlomieju** [comment]
Oh, so you're running in docker, that's pretty significant. 

> Time taken for app to trigger a restart with --watch inside docker when adding console.log('test'): 50.86s

By trigger do you mean to see "Restarting" message, or is that time it takes from "Restarting" message to actually run reloaded code?

**Comment by ebebbington** [comment]
> Oh, so you're running in docker, that's pretty significant.
> 
> > Time taken for app to trigger a restart with --watch inside docker when adding console.log('test'): 50.86s
> 
> By trigger do you mean to see "Restarting" message, or is that time it takes from "Restarting" message to actually run reloaded code?

Yes, so with that specific test, i did the following:

1. Start my whole docker environment. App is now ready
2. Make a change in the file. 
3. Start stopwatch **instantly**, wait and do nothing
4. As soon as i saw `Watcher File change detected! Restarting!`, i stopped the stopwatch
5. The time taken from step 2 to step 4 was 50.86s

Then it took 6.79s for the `run` command to start the app again, resulting in:
```
Check file:///var/www/src/app.ts
realworld_drash | Drash server running on realworld_drash:1667
```

For more reference, here's some extra info:

- I start the app
```
realworld_drash | Drash server running on realworld_drash:1667
```
- I make a change, 50s later i see:
```
realworld_drash | Watcher File change detected! Restarting!
```
- 5s later i see:
```
realworld_drash | Check file:///var/www/src/app.ts
realworld_drash | Drash server running on realworld_drash:1667
```

```

**Comment by ebebbington** [comment]
It is actually instant for the watcher to restart the app when i make a change **outside of docker**

**Comment by magurotuna** [comment]
Thanks for the detailed info. That looks really strange... the watcher has some quirk when working with docker :/
I will look into it.

**Comment by bartlomieju** [comment]
> It is actually instant for the watcher to restart the app when i make a change **outside of docker**

So it's a problem with Docker env 😬 I'm not sure we can do anything about it, it boils down to `notify` crate we use for that purpose.

**Comment by ebebbington** [comment]
@magurotuna i think you're right though, in assuming it shouldn't be a problem, cause it 'technically' isn't, as it's only problematic inside docker

**Comment by ebebbington** [comment]
Thanks for the title change @bartlomieju

**Comment by magurotuna** [comment]
Taking a quick look at `notify` issues, there seems no issue about this.

@ebebbington 
What's your host OS? macOS?

**Comment by ebebbington** [comment]
> Taking a quick look at `notify` issues, there seems no issue about this.
> 
> @ebebbington
> What's your host OS? macOS?

Yeah, high sierra 10.13.6

**Comment by ebebbington** [comment]
I should note though, that the `chatsterisk` app i posted above detects changes waaay faster, i'm gonna tets it again to make sure, will post the results in 5 minutes

**Comment by ebebbington** [comment]
Yep, the watcher detecting a file change is instant, and this is **inside** docker. So i guess it can be narrowed down to the `realworld` repo dependencies, or maybe the `src/vue` or `src/node_modules` directories are being included in the 'watcher process'? Only reason i say that is because those are the largest part of the realworld app

**Comment by ebebbington** [comment]
So now i think about it, i don't think it is a docker issue

**Comment by bartlomieju** [comment]
> or maybe the src/vue or src/node_modules directories are being included in the 'watcher process'? 

That's actually a pretty good lead, we need to add some debug output to watcher to at least print paths that are being watched. Also, @magurotuna did a few PRs to file watcher that haven't been yet released though I doubt they would have impact on performance.

**Comment by ebebbington** [comment]
Same kind of issue i had (and raised) with `deno fmt --ignore` and `deno lint --ignore` - they were still 'kind of' checking the ignored files and directories

Sorry for so many comments, i'll stop now 😬

**Comment by eezing** [comment]
@ebebbington Just curious, do either of the following improve the situation?

1. `--no-check` flag on `deno run` command
1. In `tsconfig.json`:
  ```json
  {
    "compilerOptions": {
      "assumeChangesOnlyAffectDirectDependencies": true
    }
  }
  ```

**Comment by ebebbington** [comment]
Closing, seems the issue was fixed form 1.5.1 to 1.5.4, as the ddeno version used in that problamatic repo was using 1.5.1, so i upgraded and the detecting was instant - so it isn't a problem with `deno`. Sorry if i wasted anyone's time!

**Comment by lucacasonato** [comment]
@eezing We dont use TSC for file watching, so that option has no effect in Deno.

**Comment by eezing** [comment]
@lucacasonato Yep, was implying that maybe it's compilation related.
