### ISSUE TITLE
Module Graph crate

### ISSUE THREAD

**Issue by wperron** [denoland/deno#8533]
Would be interesting to move the module graph and module graph builder to a separate crate. The use-case I have in mind would be writing a stand-alone dependency analyser in Rust without having to rewrite the module graph code or importing the whole of deno_core to make that work.

cc @lucacasonato @bartlomieju

**Comment by littledivy** [comment]
There is a dependency analyzer for Rust here: https://github.com/nestdotland/analyzer/tree/master/analyzer_tree
Still, +1 for a module graph crate.

**Comment by kitsonk** [comment]
[`deno_graph` crate](https://crates.io/crates/deno_graph/) and [a JS `deno_graph` api](https://deno.land/x/deno_graph) exist now.
