### ISSUE TITLE
bundler: escape character error

### ISSUE THREAD

**Issue by ije** [denoland/deno#8541]
here is my `entry.ts`:

```typescript
const React = {
    createElement: function (...args: any[]) { console.log(args) }
}

React.createElement("span", null, "\u{b7}")
```

i got a wrong result with `deno bundle entry.ts out.js` command:

```javascript
// out.js
const React = {
    createElement: function(...args) {
        console.log(args);
    }
};
React.createElement("span", null, "\u");
```

`"\u"` should be `"\u{b7}"`

deno **1.5.4** (bc79d55, release, x86_64-apple-darwin)

**Comment by bartlomieju** [comment]
Still a bug on latest `master`, CC @kdy1

**Comment by kdy1** [comment]
This is fixed. (I've added test for it)

**Comment by ije** [comment]
@kdy1  thanks so much!

**Comment by lucacasonato** [comment]
For tracking lets keep this issue open until we update to the swc release with the fix.
