### ISSUE TITLE
Bundler results in incorrect ordering of code

### ISSUE THREAD

**Issue by burkeholland** [denoland/deno#8545]
**System Info**
OS: Windows 10 V20H2 / WSL 2
Deno: 1.5.4
TypeScript: 4.0.5
V8: 8.8.278.2

## Description
This issue is so...intentional....that I feel like I'm missing something obvious.

I've got an Oak project where bundling it results in the `app.ts` code being re-ordered so that the app starts first and middleware is `use`d after. This results in a failure to start the server because "There is no middleware to process requests". 

#### app.ts
```typescript
import { Application, Router } from "./deps.ts";

const app = new Application();
const router = new Router();

router.get("/", (ctx) => {
  ctx.response.body = "Index Page";
});

router.get("/users", (ctx) => {
  ctx.response.body = "Users Page";
});

app.use(router.routes());
app.use(router.allowedMethods());

console.log(`Now listening on http://0.0.0.0:3000`);
await app.listen("0.0.0.0:3000");
```

#### bundle.js
_line 6802_
```javascript
const app2 = new Application();
app2.listen("0.0.0.0:3000");
```

_line 7234_ (the last lines of the bundle)
```javascript
use1("/", router);
use("/users", router);
app2.use(router.routes());
```

## Steps to Replicate

1. Clone [oak-bundle-issue](https://github.com/burkeholland/oak-bundle-issue)
1. Run `deno bundle --unstable app.ts build.js`
1. Run the bundle with `deno run -A --unstable build.js`

### What should happen

The application should run on port 3000

### What happens instead

The application fails to start with the following error...

```bash
error: Uncaught TypeError: There is no middleware to process requests.
            throw new TypeError("There is no middleware to process requests.");
                  ^
    at Application.listen (file:///home/burkeholland/dev/burkeholland/oak-bundle-issue/app.build.js:6746:19)
    at file:///home/burkeholland/dev/burkeholland/oak-bundle-issue/app.build.js:6802:12
```

**Comment by kitsonk** [comment]
cc/ @kdy1 (don't know if it is in the latest batch of fixes or not)

**Comment by kdy1** [comment]
@bartlomieju I think this isn't fixed yet.
