### ISSUE TITLE
Request constructor allows passing non-dictionary object as second parameter

### ISSUE THREAD

**Issue by CrimsonCodes0** [denoland/deno#8565]
In Chromium, calling fetch with a second parameter that isn't an object causes the promise to reject:

```js
const not_an_object = 0;

fetch(url, not_an_object);
```

```
TypeError: Failed to execute 'fetch' on 'Window': cannot convert to dictionary.
```

Deno lets it pass without error.

It may not just be checking for a generic object, I'll try to figure out the specifics of the "dictionary" referenced soon.

## Update: ##
https://fetch.spec.whatwg.org/#dom-global-fetch
The HTML fetch specification says the following:

> The fetch(input, init) method steps are:
> 
> Let p be a new promise.
> 
> Let requestObject be the result of invoking the initial value of Request as constructor with input and init as arguments. If this throws an exception, reject p with it and return p.

It is the `Request` constructor that should throw when not given an object.

https://fetch.spec.whatwg.org/#request says that the second parameter `init ` is an optional "dictionary" I'm not going to check out the details of that, but Chromium allows the following to pass:
```js
new Request(url, {});
new Request(url, []);
new Request(url, () => {});
new Request(url, null);
new Request(url, undefined);
```
and the following fail:
```js
new Request(url, 0);
new Request(url, 0n);
new Request(url, "");
new Request(url, false);
new Request(url, Symbol());
```

Deno only rejects on passing a Symbol, because a symbol is a truthy value, and the `in` operator was used on the init.

**Comment by 00ff0000red** [comment]
While checking the source, I realized that it wouldn't allow `String` objects to be used as a URL, only string primitives, updating that to work too.

**Comment by CrimsonCodes0** [comment]
Fixed quite some time ago, during the full rewrite.
