### ISSUE TITLE
Supporting extension-less module resolution

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#857]
Supporting extension-less module resolution should be considered for Deno.  It would help adoption, specifically because it would allow authoring of local code in editors with full "out of the box" TypeScript support.

## Resolution

This would likely require Deno to attempt to resolve modules in a specific order, applying the extensions.  For example:

* Module Specifier: `./foo/bar`
* Try to resolve: referencing module path + `/foo/bar.ts`
* Then: referencing module path + `/foo/bar.js`

And:

* Module Specifier: `https://example.com/foo/bar`
* Try to resolve: `https://example.com/foo/bar.ts`
* Then: `https://example.com/foo/bar.js`

This could become very costly for remote modules.

## Other considerations

Currently Deno doesn't support any sort of "magical" resolution of things like `./foo/bar` resolving to `./foo/bar/index.ts` and IIRC was part of Ryan's "10 things I did wrong" list.  On the other hand, TypeScript, when using in an editor, would follow a module resolution like that.  It also has a few other "magical" resolution in line with NodeJS, like namespace resolutions which Deno does not support.

A lot of userland code likely could be already transpiled TypeScript with a `.d.ts` file and a `.js` file.  It might be worth considering if Deno would add the feature to then type check that code before running it.

Related to #852

**Comment by ry** [comment]
Yes I ageee - we can support it to help adoption - but I think the code/docs should be heavily commented it’s meant as a stop gap solution.
I guess where this would happen is in src/deno_dir.rs during resolve_module().
A patch should introduce unit tests in deno_dir.rs and compiler_test.ts

**Comment by guybedford** [comment]
Note that Node.js itself is currently in the process of considering if this should be removed entirely. There have also been issues with ".mjs" and ".js" extensions both being checked as well causing instance issues with libraries such as GraphQL which seems to also be leading in the direction of remaining explicit.

For what it is worth, my opinion currently is that we should mandate extensions for modules, as a resolver that doesn't touch the file system is a fast resolver.
