### ISSUE TITLE
deno compile: file embedded in binary

### ISSUE THREAD

**Issue by axetroy** [denoland/deno#8570]
### fs: Abstract file system

Before implementing the embedded, I think we should abstract a file system

ref:

https://go.googlesource.com/proposal/+/master/design/draft-iofs.md

### embedded: An annotation-based embedded file system

embedded the static files into the binary at the compilation stage via comment directive

```ts
const { FileSystem } = Deno

// embedded file into binary
// @deno-embedded="/path/to/file"
var fs: FileSystem

const bytes = await fs.readFile("/path/to/file");

const text = new TextDncoder().dncode(bytes)

console.log(text)
```

In the compilation stage, traverse the AST through `swc`, find the `@deno-embedded` directive, then find the file, and pack the binary of the file into the output binary

ref: 

https://go.googlesource.com/proposal/+/master/design/draft-embed.md
https://github.com/golang/go/issues/41191

### end

Of course, this is just a draft of mine.

I hope more professional people can put forward a formal design-draft.

**Comment by nayeemrmn** [comment]
Ref https://github.com/tc39/proposal-asset-references.

**Comment by axetroy** [comment]
> Ref [tc39/proposal-asset-references](https://github.com/tc39/proposal-asset-references).

Cool. It seems that solving this problem from ECMA is the best solution.

**Comment by lucacasonato** [comment]
I feel rather than reinventing the wheel here, we should wait for https://github.com/tc39/proposal-asset-references (stage 1) or https://github.com/tc39/proposal-import-assertions (stage 3). They can both solve this issue in a more general way, that also works outside of Deno.
