### ISSUE TITLE
Reenable flaky watch tests

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#8571]
In #8557 following tests were disabled due to high flakiness when running CI:
- `fmt_watch_test`
- `bundle_js_watch`
- `bundle_watch_not_exit`
- `run_watch`
- `run_watch_not_exit`
- `run_watch_with_importmap_and_relative_paths`

They should be rewritten and enabled.

**Comment by magurotuna** [comment]
CI logs when it failed due to the watcher-related tests:

- https://github.com/denoland/deno/actions/runs/392331654
- https://github.com/denoland/deno/actions/runs/389935305

**Comment by magurotuna** [comment]
Still seems flaky
https://github.com/denoland/deno/runs/1542414977#step:24:4089

**Comment by magurotuna** [comment]
ref #9306 

@bartlomieju Maybe it's okay to close this issue?

**Comment by bartlomieju** [comment]
Yes, thanks
