### ISSUE TITLE
[bundler] Uncaught TypeError: mod.join is not a function

### ISSUE THREAD

**Issue by jsejcksn** [denoland/deno#8573]
The bundler is returning empty objects in some modules when converting them to IIFEs. Here is a repro case:

`deps.ts`:
```ts
export * as path from 'https://deno.land/std@0.79.0/path/mod.ts';
```

`main.ts`:
```ts
import {path} from './deps.ts';
console.log(path.join('/', 'example'));
```

```
example % deno --version  
deno 1.5.4 (bc79d55, release, x86_64-apple-darwin)
v8 8.8.278.2
typescript 4.0.5

example % deno run main.ts
/example

example % deno bundle main.ts main.bundle.js
Bundle file:///Users/jesse/example/main.ts
Check file:///Users/jesse/example/main.ts
Emit "main.bundle.js" (58.21KB)

example % deno run main.bundle.js 
error: Uncaught TypeError: mod.join is not a function
console.log(mod.join('/', 'example'));
                ^
    at file:///Users/jesse/example/main.bundle.js:1524:17
```

If you look at the generated bundle, you can see that an empty object is returned from the IIFE for `path`:

`main.bundle.js`:
```js
const mod = function() {
// actual module code ...
    return {
    };
}();
console.log(mod.join('/', 'example'));
```

I know it's too late to revert any changes introduced in Deno 1.5.x, but I haven't been able to bundle, install, and successfully run even one script since that minor version update back in October. ☹️ I wonder if there's a way to improve the testing strategy for swc before it's released in Deno builds. I'm not strong in Rust yet, but if there's a way that I can help, I'd like to know.

**Comment by lucacasonato** [comment]
> but I haven't been able to [..] install and successfully run even one script since that minor version update back in October.

`deno install` doesn't bundle. What is the error there?

**Comment by jsejcksn** [comment]
@lucacasonato 

> `deno install` doesn't bundle. What is the error there?

I install after bundling. I treat bundles like releases.

**Comment by kitsonk** [comment]
cc/ @kdy1
