### ISSUE TITLE
"Uncaught TypeError" after running `deno bundle`

### ISSUE THREAD

**Issue by maximousblk** [denoland/deno#8574]
screenshot:

![image](https://user-images.githubusercontent.com/28438021/100752955-339ccd00-340f-11eb-8041-c1922ad19060.png)

code:

```ts

// mod.ts

import { request } from "https://cdn.skypack.dev/@octokit/request";

const { data } = await request('GET /repos/{owner}/{repo}/license', {
  headers: {
    authorization: `token ${Deno.env.get('GITHUB_TOKEN')}`,
  },
  owner: 'denoland',
  repo: 'deno'
})

console.log(data.license.name);

```

**Comment by kitsonk** [comment]
Tried with master and it seems to be related to this [module](https://cdn.skypack.dev/-/universal-user-agent@v6.0.0-UDk8BQrp4SMRicujmCB4/dist=es2020/universal-user-agent.js).  The following is getting dropped from the bundle, which is causing the variable to be undefined:

```js
if (typeof window !== "undefined") {
  globalContext = window;
} else if (typeof self !== "undefined") {
  globalContext = self;
} else {
  globalContext = {};
}
```

cc/ @kdy1
