### ISSUE TITLE
Deno file APIs should support URL strings

### ISSUE THREAD

**Issue by jsejcksn** [denoland/deno#8579]
This suggestion was originally a bug report due to misunderstanding an API. The relevant conversation begins at https://github.com/denoland/deno/issues/8579#issuecomment-736819861.

---

Passing a URL to `Deno.readTextFile` throws with a NotFound error, while passing a native fs path string works fine.

Repro:

`message.txt`:
```
hello world
```

`main.ts`:
```ts
import * as path from 'https://deno.land/std@0.79.0/path/mod.ts';

const dir = path.dirname(import.meta.url);
const fileUrl = path.join(dir, 'message.txt');
const filePath = path.fromFileUrl(fileUrl);

const message = await Deno.readTextFile(fileUrl); // throws
// const message = await Deno.readTextFile(filePath); // ok

console.log(message);
```

```
example % deno run --allow-read=. main.ts
error: Uncaught (in promise) NotFound: No such file or directory (os error 2)
    at processResponse (core.js:223:11)
    at Object.jsonOpAsync (core.js:240:12)
    at async open (deno:cli/rt/30_files.js:44:17)
    at async Object.readTextFile (deno:cli/rt/40_read_file.js:30:18)
    at async main.ts:7:17
```

and when I comment out the line that throws and uncomment the line below it:

```
example % deno run --allow-read=. main.ts
hello world
```

**Comment by lucacasonato** [comment]
`Deno.readTextFile` only accepts plain paths as strings. File urls must be passed as `URL`.

**Comment by jsejcksn** [comment]
> or file urls (must be passed as `URL`)

@lucacasonato Do you mean a [`URL` object](https://developer.mozilla.org/en-US/docs/Web/API/URL)?

**Comment by lucacasonato** [comment]
Yes

**Comment by jsejcksn** [comment]
@lucacasonato Is there a reason the behavior I demonstrated is not acceptable input? It is unreasonably difficult to parse a string as a file URL?

**Comment by lucacasonato** [comment]
Yes. Parsing a string to a file url is ambiguous. Is the string `file:///foo/bar/my.txt` a file url to `/foo/bar/my.txt`, or a path to `./file:/foo/bar/my.txt`?

**Comment by jsejcksn** [comment]
Alright—thanks!

**Comment by jsejcksn** [comment]
> Is the string `file:///foo/bar/my.txt` a file url to `/foo/bar/my.txt`, or a path to `./file:/foo/bar/my.txt`?

@lucacasonato I thought more on this. While I understand the ambiguity in your example, I think that if any path value begins with `file://` that it should be treated as a file URL string.

I recognize that this would prevent relative linking to a directory whose name ends with a `:`, but I think those are very niche corner cases which could be handled with `path.resolve`, and the benefit of being able to pass a file URL string will be much greater to everyone else.

**Comment by jsejcksn** [comment]
@lucacasonato Unless I'm missing something else here, I'd like for this issue to be reopened so that others can share feedback. If the title needs to be changed to reflect a suggestion instead of a bug report, that's great, too—please feel free to change it.

**Comment by jsejcksn** [comment]
@kitsonk Is that "invalid" label in reference to the original bug report or to my suggestion?

**Comment by kitsonk** [comment]
Sorry, GitHub only showed me the first few comments for some reason as I was flipping through.

**Comment by lucacasonato** [comment]
@jsejcksn What are you proposing exactly?

cc @nayeemrmn

**Comment by jsejcksn** [comment]
> What are you proposing exactly?

That methods (e.g. [`Deno.readTextFile`](https://doc.deno.land/builtin/stable#Deno.readTextFile)) which currently accept a parameter which is:

  - a path `string`

or

  - a `URL` whose [`protocol`](https://developer.mozilla.org/en-US/docs/Web/API/URL/protocol) is `file://`

should also accept:

  - a valid file URI ([wiki](https://en.wikipedia.org/wiki/File_URI_scheme)/[spec](https://tools.ietf.org/html/rfc3986))

---

👉 Essentially, if a `string` is provided, _and_ begins with `file:/`, it should be parsed as a file URI (_not_ a relative path).

---

This would prevent providing a relative path to a directory whose name is `file:`, but I think that is a _very_ uncommon case<sup>1</sup> which could be handled with the [`path`](https://deno.land/std/path) module or by simply prepending it with `./` (or `.\` in Windows). The benefit of being able to pass a file URIs will be welcome in every other case, I think.

I'm not sure, but I think this function is where the change would need to be made:

https://github.com/denoland/deno/blob/abc883e6a744beaf4fab6d098b7d88b227a8a6d0/cli/rt/06_util.js#L89-L100

<sup>1</sup> Colons are disallowed in directory and file names in Windows, and are widely discouraged in *nix due to the problems they can cause. See https://www.google.com/search?q=colon+filename+problem

**Comment by 00ff0000red** [comment]
> `Deno.readTextFile` either takes plain paths (as a `string`), or file urls (must be passed as `URL`). You are trying to pass a file URL as a string.

How about supporting String objects?
ex:
```js
const str = new String("./file.txt");
Deno.readFile(str);
```

**Comment by kitsonk** [comment]
> How about supporting String objects?

What problem does that solve?

**Comment by nayeemrmn** [comment]
> While I understand the ambiguity in your example, I think that if any path value begins with `file://` that it should be treated as a file URL string

We had this feature at [my suggestion](https://github.com/denoland/deno/pull/5990#pullrequestreview-424466927), but it was quickly reverted after people realistically hit the bug: #6401, https://github.com/denoland/deno/issues/6401#issuecomment-648388203. The ambiguity is not acceptable.

@jsejcksn Don't use the `std/path` functions on URLs. Joining and resolving URLs is really easy with the constructor:
```diff
  import * as path from 'https://deno.land/std@0.79.0/path/mod.ts';

- const dir = path.dirname(import.meta.url);
- const fileUrl = path.join(dir, 'message.txt');
- const filePath = path.fromFileUrl(fileUrl);
+ const filePath = path.fromFileUrl(new URL(import.meta.url, "message.txt"));

  const message = await Deno.readTextFile(fileUrl);

  console.log(message);
```

**Comment by jsejcksn** [comment]
> We had this feature at [my suggestion](https://github.com/denoland/deno/pull/5990#pullrequestreview-424466927), but it was quickly reverted after people realistically hit the bug: #6401, [#6401 (comment)](https://github.com/denoland/deno/issues/6401#issuecomment-648388203). The ambiguity is not acceptable.

@nayeemrmn Interesting! I didn't know it existed before.

This is different than your suggestion. This is a special case for the `file:` scheme only (no other URI schemes). Any other scheme would still be recognized as a path string, so it would mitigate those issues.

**Comment by kitsonk** [comment]
> This is a special case for the `file:` scheme only (no other URI schemes). Any other scheme would still be recognized as a path string, so it would mitigate those issues.

Having "magical" strings feels wrong to me.  A URL is a URL and a string file path is a string file path... they are unambiguous in how they are to be resolved and handled.  I personally don't think adding a magical string of `file:///` would be generally a good idea.

**Comment by nayeemrmn** [comment]
> This is different than your suggestion. This is a special case for the `file:` scheme only (no other URI schemes). Any other scheme would still be recognized as a path string, so it would mitigate those issues.

It doesn't mitigate the issue, just makes it more rare. This is not just a corner case that you only need to handle if you "have paths like that". Any good lib which doesn't know what paths it will get needs to add handling. It's also a really bad and arbitrary design for Deno.

> _and_ begins with `file:/`, it should be parsed as a file URI (_not_ a relative path).

FYI, file URL **inputs** can look like `file:foo/bar`.

**Comment by kitsonk** [comment]
> FYI, file URL inputs can look like `file:foo/bar`.

And `file://hostname/path/file.js`.  Something being strongly discouraged (colons in paths) doesn't make them invalid.  You can quite trivially create a `/path/to/file:/mod.js` in a *NIX system, which means we are simply dodging a bullet.  a URL is a URL and is explicit about how it is should be parsed.  A string is unambiguous if it is parsed as a "path", not sometimes magically parsed as a URL.

**Comment by jsejcksn** [comment]
@kitsonk and @nayeemrmn Thanks for providing feedback!

> Having "magical" strings feels wrong to me. A URL is a URL and a string file path is a string file path... they are unambiguous in how they are to be resolved and handled.

I'm not sure I fully agree with this. I will explain more below:

> Any good lib which doesn't know what paths it will get needs to add handling.

I completely agree with this. My thinking is that if a path is needed, the `path` module would be used. If a URL is needed, the `URL` constructor would be used. Each of them accepts strings, but according to the rules of their respective domains. This suggestion is about recognizing that string paths are actually more "magical" than string URLs (especially relative ones) since they don't include identifying syntax like URI scheme, and that both are actually structured data types that can be represented as strings. Wouldn't it make sense for these kinds of functions to also accept the output of [`path.parse`](https://doc.deno.land/https/deno.land/std@0.79.0/path/posix.ts#parse)?

Nayeem: There are a few parts of your comment that I didn't understand:

> It doesn't mitigate the issue, just makes it more rare.

It addresses all of the issues you linked to in your comment here: https://github.com/denoland/deno/issues/8579#issuecomment-736899131. When you say "the issue", which issue do you mean?

> It's also a really bad and arbitrary design for Deno.

I agree that it's arbitrary. However, arbitrary and bad are not synonymous, so why do you think that this arbitrary decision would be "bad"?

> FYI, file URL **inputs** can look like `file:foo/bar`.

I'm not sure what you mean here by "inputs". Will you clarify?

**Comment by nayeemrmn** [comment]
> > It doesn't mitigate the issue, just makes it more rare.
> 
> It addresses all of the issues you linked to in your comment here: [#8579 (comment)](https://github.com/denoland/deno/issues/8579#issuecomment-736899131). When you say "the issue", which issue do you mean?
> 
> > It's also a really bad and arbitrary design for Deno.
> 
> I agree that it's arbitrary. However, arbitrary and bad are not synonymous, so why do you think that this arbitrary decision would be "bad"?

It's bad because it makes relative paths starting with `file:` impossible to use just because it's a corner case, even though there's no good reason to have this feature in the first place.

> > FYI, file URL **inputs** can look like `file:foo/bar`.
> 
> I'm not sure what you mean here by "inputs". Will you clarify?

Just saying that scanning for a `file:/` prefix makes no sense since `new URL("file:foo")` is valid.

**Comment by bartlomieju** [comment]
This issue should be now resolved - most of FS APIs support `URL` overload.
