### ISSUE TITLE
Rename std/datetime to std/date

### ISSUE THREAD

**Issue by nayeemrmn** [denoland/deno#8594]
Also rename identifiers that have `DateTime` in them. `formatter.ts` and `tokenizer.ts` should be private, they have clean wrapper functions in `mod.ts`.

The module wraps around `Date` (`DateTimeFormatter::format(date: Date)`), which we should match. `DateTime` is used in other specs like `Intl`, there's nothing wrong with the term except that this module is strictly bound to the `Date` class.

In light of https://tc39.es/proposal-temporal/docs/index.html, it's possible we never want to stabilise this module in favour of `std/temporal` (or nothing). But unless we're removing it outright in the near future, the rename is still needed i.e. no sense in keeping `datetime` as a "neutral" name whose internals can just be swapped out -- that would be breaking either way.

**Comment by wperron** [comment]
Relates to #8405

**Comment by bartlomieju** [comment]
I believe we should refrain from changing the module name before relevant meeting of Standard Library Working Group

**Comment by nayeemrmn** [comment]
https://github.com/denoland/deno/pull/8596#issuecomment-747546556
