### ISSUE TITLE
Integrating other compilers with Deno like TSC?

### ISSUE THREAD

**Issue by 00ff0000red** [denoland/deno#8608]
Forwarning, my understanding of Deno may be incorrect, please, correct me if I am wrong.

Currently, Deno chooses between either JavaScript or TypeScript by using the file's extension. (I think?)

When JavaScript attempts to import a .ts file, the cache is checked, if the file has not been changed, the cached code is used, otherwise, TSC is invoked and its JavaScript output is imported.

Can the same functionality be easily provided for other languages?

Say, I wanted to use Dart's dart2js transpiler on Dart source code files (.dart), is there a way that I could do this using Deno itself?

If I were to do something like:
```js
import foo from "./mod.dart"
```
the transpiler program would be fed the file and emit JS, which is then used by the importing JS module.

If this does not exist, can this be considered a suggestion to offer such functionality?

**Comment by nayeemrmn** [comment]
Duplicate of #1739.

**Comment by 00ff0000red** [comment]
Ah, closing in favor of already opened issue.
