### ISSUE TITLE
text-decoration-color not supported by console methods

### ISSUE THREAD

**Issue by mvolkmann** [denoland/deno#8609]
The news post here https://deno.land/posts/v1.4#css-styling-in-consolelog says that the console methods support these CSS properties: color, background-color, font-weight, font-style, text-decoration-color, and text-decoration-line. But text-decoration-color doesn't seem to work. The issue where this feature is described is at https://github.com/denoland/deno/issues/2778. The issue does not list the text-decoration-color property as one of the supported properties. Perhaps the easiest way to resolve this is to just correct the news post by removing the mention of this CSS property that doesn't seem to be supported yet.

**Comment by nayeemrmn** [comment]
The post says:
> Support for these properties, and custom rgb, hex, and hsl colors depend on your terminal's support for ANSI.

The ANSI code for text-decoration-color is implemented so the feature is "supported by Deno", it's just not commonly supported by terminals.

**Comment by mvolkmann** [comment]
Do you know of any specific terminals that support it?

**Comment by nayeemrmn** [comment]
Haven't played with any terminals, but the code that we use for it is included here: https://en.wikipedia.org/wiki/ANSI_escape_code#SGR_parameters (58 | set underline color). There's no question that the feature is supported by Deno as much as it can be.
