### ISSUE TITLE
TS5009 error when working directory path different from .deno directory path

### ISSUE THREAD

**Issue by Ashniu123** [denoland/deno#861]
### Code
```
import { printHello } from 'https://raw.githubusercontent.com/denoland/deno/master/tests/subdir/print_hello.ts';

printHello();
```

### Execution
```
PS E:\Workspace\Github\deno>  C:\Github\deno\out\debug\deno.exe example.ts
[91merror[0m[90m TS5009: [0mCannot find the common subdirectory path for the input files.
```
*I don't know why the weird characters show up.*

### Reason
In Windows where absolute path differs `E:\...` and `C:\...` this issue is and will be prevalent

### Solution
Keep working directory and deno in same partition (example: both in `C:\...`)

*Better Solution:* Download deps in working directory?
This is because generally people have their working directory different from `C:\...`.

Original issue [here](https://github.com/denoland/deno/issues/807)

**Comment by hayd** [comment]
@Ashniu123  Is this fixed now?
