### ISSUE TITLE
fsync/fdatasync running on main thread

### ISSUE THREAD

**Issue by jannes** [denoland/deno#8613]
I recently wrote a few scripts to benchmark different sizes for the tokio pool 
that is used for running blocking disk IO calls such as write, read.
I noticed that fsync/fdatasync system calls are made from the main thread.

As these are blocking calls, I believe they should also be executed by the Tokio pool.
Otherwise for workloads that make heavy use of these system calls 
the main thread will be constantly blocked.

**Comment by bartlomieju** [comment]
CC @caspervonb 

Related https://github.com/denoland/deno/issues/7400
Blocked by https://github.com/denoland/deno/issues/7984

**Comment by caspervonb** [comment]
Kind-of blocked on #8416 (altho not impossible, tedious to make this async with the current resource table).

**Comment by bartlomieju** [comment]
Let's continue this topic as part of #7400
