### ISSUE TITLE
Consider resolving external JavaScript as "typeless" and assumed AMD/UMD

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#862]
Importing existing external JavaScript, especially either UMD or AMD bundles, could provide exports to deno just fine, but currently deno _barfs_ on these files with things like:

```
error TS1192: Module '"some/module.js"' has no default export.
```

For files that the resolved module specifier is `.js` we could just inform TypeScript the module is an "any" module and go ahead and run the module through an environment with `define()` to collect any module factories and make the exports available.

This should mean that any UMD modules, or AMD bundles should _just work_.  The `define()` though will provide a module specifier, which deno would have to track and resolve and return when required/imported.

Global scripts would just execute, but not return any exports, and CommonJS modules would throw.

**Comment by bartlomieju** [comment]
@kitsonk is this still relevant with ES Modules support?

**Comment by kitsonk** [comment]
Yeah, I don't know.  Closing for now.

**Comment by flying-sheep** [comment]
I think so. I think people usually publish a “browser” bundle as UMD, a commonjs module depending on node APIs, and an ES module relying on node APIs.

In order to consume the “browser” bundles we need UMD support.

**Comment by kitsonk** [comment]
I'm not sure the point you are trying to make.  What are you trying to do that you can't because I don't think this issue is relevant anymore.  What are you trying to do that you can't?

**Comment by flying-sheep** [comment]
As I said, a viable alternative is to lobby people into offering a dependency-less ES bundle.
