### ISSUE TITLE
Deno miss-bundles THREE.js from Skypack

### ISSUE THREAD

**Issue by jcc10** [denoland/deno#8620]
When trying to bundle https://github.com/Immersive-Recording/livestream-subview-controller/blob/Prototype/client/script/test.ts the bundle generates without error. However, when trying to run, the following error is thrown:
```test.js:12991 Uncaught SyntaxError: Identifier 'b2' has already been declared```

Original:
```
function splitPolygon( a, b ) {

	const a2 = new Node( a.i, a.x, a.y ),
		b2 = new Node( b.i, b.x, b.y ),
```
Bundled:
```
function splitPolygon(a, b2) {
    const a2 = new Node1(a.i, a.x, a.y), b2 = new Node1(b2.i, b2.x, b2.y), an = a.next, bp = b2.prev;
```

deno 1.5.4 (bc79d55, release, x86_64-unknown-linux-gnu)
v8 8.8.278.2
typescript 4.0.5

**Comment by jcc10** [comment]
cc @kdy1

**Comment by jcc10** [comment]
I haven't tested the Deno packing without Skypack, I'll try and get on that soon.

**Comment by kdy1** [comment]
@jcc10  Can you provide an input to test this?

**Comment by jcc10** [comment]
@kdy1The following has the issue on line `12984` of a deno build.
```
/// <reference lib="esNext" />
/// <reference lib="dom" />
/// <reference lib="webworker.importScripts" />
/// <reference lib="ScriptHost" />
/// <reference lib="dom.iterable" />
/// <reference no-default-lib="true"/>
import * as THREE from 'https://cdn.skypack.dev/three?dts';
```

**Comment by kdy1** [comment]
@jcc10  Thanks!
