### ISSUE TITLE
Stabilize Deno.utime and Deno.utimeSync

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#8630]
This topic was briefly discussed during recent Standard Library Working Group meeting. Stabilizing these two APIs should make a few APIs from `std/fs` stable. There have been no changes to `Deno.utime` in quite some time so I believe we could safely stabilize it for `1.6.0`

**Comment by bartlomieju** [comment]
Actually there's https://github.com/denoland/deno/issues/7300 and comment on `Deno.utime`:
```
**UNSTABLE**: needs investigation into high precision time.
```

So maybe we shouldn't yet stabilize these APIs.

**Comment by caspervonb** [comment]
I intend to replace these with utimens variants, the current semantics are a bit weird.

**Comment by bartlomieju** [comment]
Closing in favor of https://github.com/denoland/deno/issues/8634
