### ISSUE TITLE
Deprecate Deno.utime and Deno.utimeSync

### ISSUE THREAD

**Issue by caspervonb** [denoland/deno#8634]
Deno.utime is modeled after utime(2) but it has some weird semantics in that if you pass it a date you get millisecond precision but if you pass it a unix timestamp in the form of a number you get second precision.

Changing the resolution of the timestamp is going to cause a lot of breakage so the more reasonable approach would be to deprecate it in favour of a new set of functions modeled after utimes and/or utimens.

**Comment by caspervonb** [comment]
For reference https://github.com/denoland/deno/issues/7301

**Comment by wojpawlik** [comment]
What's the point of `number` of seconds overload anyway? Why not have `Deno.dateFromUnixTimestamp(s: number)` instead?

**Comment by caspervonb** [comment]
> What's the point of `number` of seconds overload anyway? Why not have `Deno.dateFromUnixTimestamp(s: number)` instead?

Mirroring system calls here.

So I've left this pending, because Temporal is going to be a thing soon.
So this might just be a 2.0 change.

**Comment by lino-levan** [comment]
@bartlomieju Just saw the 2.0 announcement. Would deprecating `Deno.utime` and `Deno.utimeSync` possibly be on the agenda for that? I agree with the commentary that the semantics are pretty janky. Thoughts?

**Comment by lucacasonato** [comment]
We are going to maintain the current behaviour.
