### ISSUE TITLE
Reader only <Uint8Array>?

### ISSUE THREAD

**Issue by LuvbCa** [denoland/deno#8636]
**hey guys,**

im trying to create a library with sox to get microphone input.
But now im encountering that a `Deno.Reader` can only read Uint8Array and that cerntainly limits sox because i can only get a very limited amount of data.

Now i don't really know how to cahnge this behaviour?

Thanks in advance.

**Comment by lucacasonato** [comment]
What do you mean? What do you want instead of a Uint8Array?

**Comment by LuvbCa** [comment]
i want a Uint16Array or Int16Array so i can atleast retrieve 16 bits of information

**Comment by lucacasonato** [comment]
A `Uint8Array` holds _mulitple_ 8bit unsigned intergers (bytes) of data. You can convert a Uint8Array with a length that is a multiple of 2, to a `Uint16Array` like this: `new Uint16Array(buf.buffer)`.

**Comment by LuvbCa** [comment]
Thanks, i will try! Have a nice day
