### ISSUE TITLE
Better re-use of swc source files

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#8641]
We don't really leverage swc source files efficiently, where `deno lint`, `deno doc`, `deno bundle`, the module graph and dependency analysis can often reparse the same file multiple times.  With the forthcoming language server it becomes even more evident.  We should consider a better was of refactoring to reuse this structures where applicable.

**Comment by dsherret** [comment]
Closing this because of #11780.

The rest of the re-use will be done with the more complete integration of deno_graph.
