### ISSUE TITLE
ensureFile / ensureDir fail on symlink

### ISSUE THREAD

**Issue by glowingblue** [denoland/deno#8645]
Not sure if this is intentional or if I'm doing it wrong, but when I have a symlink folder in my cwd pointing to some other location (outside of the app folder) in the filesystem (for deno to write to) and call `ensureFile` on a path that has the symlink folder in it, I get the error

`Error: Ensure path exists, expected 'dir', got 'symlink'`

which of course is correct, but shouldn't that work?

trying to visualize it:
```
cwd
 - main.js
 - somedir/somefile.js
 - .tmp/ => this is the symlink, pointing to somewhere else on the drive, like /Users/x/y/z/
```

so I want to ensure that a file within `.tmp/` exists, e.g. `.tmp/data.json`

so I do `ensureFile('.tmp/data.json')`, which fails with the above error.

**Comment by jaeheonji** [comment]
`ensureFile`  can only get correct results if the target is a file. You can check this in `deno/fs/ensure_file.ts`.

```typescript
export async function ensureFile(filePath: string): Promise<void> {
  try {
    // if file exists
    const stat = await Deno.lstat(filePath);
    if (!stat.isFile) {
      throw new Error(
        `Ensure path exists, expected 'file', got '${getFileInfoType(stat)}'`,
      );
    }
  } catch (err) {
    // if file not exists
    if (err instanceof Deno.errors.NotFound) {
      // ensure dir exists
      await ensureDir(path.dirname(filePath));
      // create file
      await Deno.writeFile(filePath, new Uint8Array());
      return;
    }

    throw err;
  }
}
```

If you only want to check the existence of an object regardless of the type, it is recommended to use `exists` or `existsSync`.
These functions can be found in `std/node/fs.ts`.

```typescript
import { exists, existsSync } from "https://deno.land/std/node/fs.ts";
```

For a detailed these function, Node.js documentation(https://nodejs.org/api/fs.html#fs_fs_existssync_path) will be helpful.
