### ISSUE TITLE
Include language service completions in repl completions

### ISSUE THREAD

**Issue by caspervonb** [denoland/deno#8652]
LSP has more static knowledge than the runtime does, but the inspector has knowledge of runtime properties so merging the two as the completion source is probably the best of both worlds.

**Comment by dsherret** [comment]
If this is implemented it can be done without the language server and instead use the language service. The [getCompletionsAtPosition](https://github.com/dsherret/ts-morph/blob/edd0e03fa0b2c8c2c97c725414ae58754e0147ff/packages/common/lib/typescript.d.ts#L5597) would be useful.

**Comment by bartlomieju** [comment]
This has actually been implemented some time ago.
