### ISSUE TITLE
`deno compile` does not have web worker support

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#8654]
This is a tracking issue to investigate how we can support web workers in `deno compile`.

**Comment by Zizaco** [comment]
+1 to this. could base64 be a first step?

```js
new Worker(
  "data:application/typescript;base64,Y29uc29sZS5sb2coImhlbGxvIHdvcmxkIik7CnNlbGYuY2xvc2UoKTs=",
  { type: "module" },
);
```

```
thread 'deno-worker-0' panicked at 'not yet implemented: Worker are currently not supported in standalone binaries', cli/standalone.rs:163:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', runtime/ops/worker_host.rs:522:46
fatal runtime error: failed to initiate panic, error 5
Aborted (core dumped)
```

**Comment by adamdbradley** [comment]
This feature would be a great addition and allow us to use the standalone binary since web workers is one of our requirements. Encoding the worker modules as  `data:` URLs would work great if possible.

**Comment by bartlomieju** [comment]
Ref for a PR https://github.com/denoland/deno/pull/9936

**Comment by authcompanion** [comment]
@lucacasonato would you have any updates on how you're thinking on this! tyvm.

**Comment by mweichert** [comment]
> Ref for a PR #9936

@bartlomieju even with data URIs, workers don't seem to be available yet in compiled binaries.

**Comment by pokatomnik** [comment]
This would be the most wanted feature since compilation has been implemented.

**Comment by jcs224** [comment]
Just want to bump this, I've been working on an project that doesn't use just one, but _two_ workers :sweat_smile: It's the foundation for working on a desktop app using [webview_deno](https://github.com/webview/webview_deno), and using a worker to serve the page, assets, and a websocket connection from an [oak](https://github.com/oakserver/oak)-based web server. The second worker runs a long-running subprocess. I compile the static web assets into binaries using [denobundle](https://github.com/txthinking/denobundle) so they can be bundled with the binary. This is the best way so far I've found to build a GUI with deno. Just need the final step of wrapping it all together!

Definitely not ready for widespread use yet, but it's a simple GUI for managing Docker containers.

https://github.com/jcs224/dockersaurus

**Comment by pokatomnik** [comment]
any updates on this?

**Comment by jcs224** [comment]
Just tried this with 1.32, works now! I think this can be closed now, per https://github.com/denoland/deno/pull/17657

**Comment by Hexagon** [comment]
Is this supposed to be working using now `data:`? Can't seem to get it to work

**Comment by andreubotella** [comment]
> Is this supposed to be working now using `data:`-urls? Can't seem to get it to work

With `deno compile`, all module fetching and Typescript compilation happens at compile time, so you can be sure that remote imports haven't changed under the hood, for example. With regular imports, the whole module graph can be tracked, fetched and transpiled at compile time. However, with workers, the worker's main module is given as a string which might be built up at runtime, and combined with other factors it means it's not easy to statically analyze a worker's main module at compile time.

Starting in 1.32, `deno compile` has an `--include` flag which lets you specify additional modules which will be fetched and transpiled at compile time, along with their imports, recursively. You can use it as `deno compile --include ./worker1.ts --include ./worker2.ts --output compile main.ts`

**Comment by Hexagon** [comment]
That clears it up, thanks! 👍

**Comment by cowboyd** [comment]
Curious what the reasons are to not implement this. Development resources? Security Concerns? Architectural concerns?

**Comment by lucacasonato** [comment]
It's supported now

**Comment by cowboyd** [comment]
Is there any chance that workers could be created without knowledge of the worker module at compile time? Specifically, I'm wondering if this feature might evolve into a safe alternative to #18327 since it allows for restricting permissions.

**Comment by lucacasonato** [comment]
Refer to https://github.com/denoland/deno/issues/18327 for more discussion on that.
