### ISSUE TITLE
support cross compiling to different platforms with `deno compile` 

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#8657]
It would be great if you could cross compile binaries for different platforms when using `deno compile`.

Example: `deno compile --target x86_64-apple-darwin https://deno.land/std@0.79.0/http/file_server.ts` from Linux or Windows to create a macOS binary.

This should be relatively trivial to implement. Instead of using the current binary as the base binary for the compilation, we would download the binary for the specified target (using the same code as `deno upgrade`), and then use that as a compilation base binary.

**Comment by nayeemrmn** [comment]
Duplicate of #8567.

**Comment by lucacasonato** [comment]
Ah right.
