### ISSUE TITLE
Remove url crate, use http::uri::Uri instead

### ISSUE THREAD

**Issue by ry** [denoland/deno#866]
Hyper is our http library and has [its own url parsing](https://hyper.rs/hyper/master/hyper/struct.Uri.html) functionality. Therefore we should use that instead of the standalone "url" crate. This should reduce binary size slightly.

Also check that the dependencies of url aren't orphaned. If they are, remove them too 
https://github.com/denoland/deno/blob/f51903f7736e3969ba0003c074d80950aca74f70/build_extra/rust/BUILD.gn#L20-L27

**Comment by ry** [comment]
WIP branch here https://github.com/ry/deno/tree/remove_url_crate

Need a utility function to join Uri paths. See #955

**Comment by bluetech** [comment]
I have not looked at the details at all, but thought I'd mention anyway. The `url` crate and hyper's `Uri` type (a reexport of [`http::Uri`](https://docs.rs/http/0.1.13/http/uri/struct.Uri.html)) serve different purposes. Hyper's `Uri` has a misleading name IMO - it is not actually a URI parser but an HTTP ["Request Target"](https://tools.ietf.org/html/rfc7230#section-5.3) parser, which has several forms not all of which are URLs (it is neither a superset or a subset). For example `*` is a valid Request Target. Which of these does Deno want?

**Comment by ry** [comment]
@bluetech We essentially only need it for extracting the path/domain/port from http urls. 

Because we're depending on hyper, hyper::uri will already be used - so ideally we wouldn't have another url crate.

**Comment by romandev** [comment]
I sent a PR to implement `uri_join()`. It's still under review but I'll send follow-up PR for this issue after landing existing PR (if you don't mind).

**Comment by ry** [comment]
ref https://github.com/denoland/deno/pull/991

**Comment by bartlomieju** [comment]
@ry I've checked current usage of `url::Url` throughout project and it's used quite extensively now in `cli/`. I'm pretty sure we can't replace it with hyper's `Uri`. Should we close this issue?

**Comment by ry** [comment]
Yes thanks ... I decided a while ago to myself that url isn’t bad and maybe even preferable to hyper.
