### ISSUE TITLE
deno_cli crate 0.23.3 is missing exports/documentation?

### ISSUE THREAD

**Issue by brandonros** [denoland/deno#8665]
all of these seem to be broken:

https://docs.rs/deno_cli/0.23.1/deno_cli/index.html
https://docs.rs/deno_cli/0.23.2/deno_cli/index.html
https://docs.rs/deno_cli/0.23.3/deno_cli/index.html

different than

https://docs.rs/deno_cli/0.23.0/deno_cli/index.html

**Comment by brandonros** [comment]
Also running into this:

```
error[E0432]: unresolved import `deno_cli::test_util`
 --> tests/integration_tests.rs:1:15
  |
1 | use deno_cli::test_util::*;
  |               ^^^^^^^^^ could not find `test_util` in `deno_cli`


```

with

```
[dev-dependencies]
deno_cli = "0.23.0"
```

in Cargo.toml

**Comment by brandonros** [comment]
So it seems like deno_cli is deprecated, the native plugin example relies on `test_util` which was exported from `deno_cli` (not 0.23.0+, only 0.22.0), and `deno_core` nor `deno` crates export `test_util`

https://docs.rs/crate/deno/1.5.4 is not a library but it can be a crate? kind of confusing. wondering if the test_plugin should be updated to show newcomers what to add to Cargo.toml to be able to import  what used to be `deno_cli::test_util`

**Comment by brandonros** [comment]
```
$ ./target/debug/deno --allow-plugin tests/test.js 
error: Found argument '--allow-plugin' which wasn't expected, or isn't valid in this context

USAGE:
    deno [OPTIONS] [SUBCOMMAND]

For more information try --help
```

whole thing seems broken

**Comment by bartlomieju** [comment]
@brandonros `deno_cli` is a deprecated crated that is no longer maintained. [`deno`](https://crates.io/crates/deno) is the actual crate, but it does not provide library target. If you want to write a plugin then you should use `deno_core` as seen in https://github.com/denoland/deno/blob/master/test_plugin/src/lib.rs

**Comment by lucacasonato** [comment]
1. `deno_cli` doesn't exist anymore.

2. You have to use the `run` subcommand to run a file (`./target/debug/deno run --allow-plugin tests/test.js `)

3. https://github.com/denoland/deno/tree/master/test_plugin is the example plugin. The `test_util` is not actually needed, it is just a convenience method.
