### ISSUE TITLE
deno_core::ModuleLoader::load should not be async

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#8667]
In the CLI we have moved all async functionality to `::prepare_load()` and every other implementation of the trait responds synchronously.

**Comment by bartlomieju** [comment]
CLI is only one of the consumers of `deno_core::ModuleLoader` and it so happens that it leverages `prepare_load()` method to load everything upfront and doesn't need `load()` to be async. However there are other implementations that depend on `load` method being async, eg. `dlint` for plugins, `deno_core::FsModuleLoader`. IMO this is a non-issue and I'm gonna close this one.

**Comment by kitsonk** [comment]
> `deno_core::FsModuleLoader`

Is sync in its use of `load` and converts at the edge... 😕

**Comment by bartlomieju** [comment]
> > `deno_core::FsModuleLoader`
> 
> Is sync in its use of `load` and converts at the edge... 😕

You're right I wrote that myself 😅  okay, then another case: if we make `load()` sync then implementors will have to always implement `prepare_load()` and perform full graph analysis to load module asynchronously.

**Comment by kitsonk** [comment]
> and perform full graph analysis to load module asynchronously.

Or do nothing, like `deno_core::FsModuleLoader` already does. One noop future per run versus potentially thousands.
