### ISSUE TITLE
Deno 1.6.0 bundle regression - skypack default export

### ISSUE THREAD

**Issue by nktpro** [denoland/deno#8677]
This snippet is bundled correctly in deno `1.4.x` and `1.5.x`:

```typescript
import safeStringify from "https://cdn.skypack.dev/fast-safe-stringify@^2.0.7?dts";

console.log(safeStringify({ foo: "bar" }));
```

The end of the bundled output looks like this:

```javascript
// ...
var fastSafeStringify = stringify;
stringify.default = stringify;
stringify.stable = deterministicStringify;
stringify.stableStringify = deterministicStringify;
console.log(fastSafeStringify({
    foo: "bar"
}));
```

In deno `1.6.0`, the bundle contains invalid code (notice the 2 invalid `const __default = __default` statements at the end of the bundle)

```javascript
// ...
stringify.default = stringify;
stringify.stable = deterministicStringify;
stringify.stableStringify = deterministicStringify;
console.log(__default({
    foo: "bar"
}));
const __default = __default;
const __default = __default;
```
The culprit is most likely this generated export statement from `skypack`:

```javascript
export {default} from '/-/fast-safe-stringify@v2.0.7-WDeodjUgEmHi5ciJNBKi/dist=es2020/fast-safe-stringify.js';
```

Since `deno compile` relies on bundling behind the scene, this affects it as well.

**Comment by kitsonk** [comment]
cc/ @kdy1

**Comment by nktpro** [comment]
I managed to create a much better reproducer with https://github.com/denoland/deno/issues/8679, closing this issue.
