### ISSUE TITLE
Logo in readme does not work well with the new GitHub dark mode

### ISSUE THREAD

**Issue by MarkTiedemann** [denoland/deno#8678]
Screenshot:

![image](https://user-images.githubusercontent.com/7062160/101552531-4a18ca80-39b3-11eb-86d4-3d14603afbc5.png)

To use the dark mode, select it in your appearance settings: https://github.com/settings/appearance

**Comment by caspervonb** [comment]
Hm didn't we do an adjusted version of the icon in relation to windows dark mode that worked okay in both light and dark?

**Comment by caspervonb** [comment]
Not quite the issue I was looking for but related https://github.com/denoland/deno/issues/6593

**Comment by kitsonk** [comment]
It should be fixed in the same way Windows was.

**Comment by Vishal19111999** [comment]
@kitsonk I have tried to fix it and made a PR!
