### ISSUE TITLE
Deno bundle regression in both 1.5.4 and 1.6.0 when a module re-exports both * and default

### ISSUE THREAD

**Issue by nktpro** [denoland/deno#8679]
I've managed to narrow this issue down to a bare-minimal reproducer: Given 3 files:

`one.ts`
```typescript
export default "one";
export const one = "one";
```

`two.ts`
```typescript
export * from "./one.ts";
export { default } from "./one.ts";
```

`three.ts`
```typescript
import two from "./two.ts";
console.log(two);
```

Only deno `1.4.x` would produce a valid bundle for `three.ts` (very verbose output but valid regardless, since we didn't have bundle tree-shaking until `1.5.x`)

```bash
deno bundle ./three.ts
```

The bundle output of deno `1.5.4` will simply contain a single invalid statement of:

```javascript
console.log(__default);
```

The bundle output of deno `1.6.0` is also invalid, in a slightly different way:

```javascript
console.log(__default);
const __default = __default;
const __default = __default;
```

It's worth noting that the re-exporting pattern in `two.ts` is basically what `skypack.dev` does, so this issue would usually manifest in the wild by importing some libraries via skypack.

**Comment by kitsonk** [comment]
cc/ @kdy1

**Comment by kdy1** [comment]
The problem is that a module exports `default` multiple times.
I think a removing `default` from `export *` could be a solution.

**Comment by nktpro** [comment]
@kdy1 As per [the example on MDN](https://developer.mozilla.org/en-US/docs/web/javascript/reference/statements/export) `export * from ...` re-exports everything **except** the default export. If `swc` exports `default` as well as part of `export * from ...` then perhaps it didn't implemented ES specification correctly?

**Comment by kdy1** [comment]
@nktpro Oh, thanks! I didn't know it. Then fixing it will be much easier.
I just normalized all imports to ease handling and as a result `default` was exported too.
