### ISSUE TITLE
Deno.dir is not a function

### ISSUE THREAD

**Issue by githubmann** [denoland/deno#8682]
according to [runtime doc](https://doc.deno.land/builtin/unstable#Deno.Permissions), I code ```Deno.dir("home")```.
![image](https://user-images.githubusercontent.com/13065289/101563493-4bbeae80-3a04-11eb-8515-2b73bc251f68.png)

but output as follow:
```
Uncaught TypeError: Deno.dir is not a function
    at <anonymous>:2:6

```

env:
```
deno 1.5.4 (bc79d55, release, x86_64-apple-darwin)
v8 8.8.278.2
typescript 4.0.5
```

**Comment by caspervonb** [comment]
Outdated docs, thanks 👍

**Comment by rivy** [comment]
@caspervonb @bartlomieju , what's the replacement for this functionality?

**Comment by milahu** [comment]
> what's the replacement

something like

```ts
// const homedir = Deno.dir("home");

const homedir = Deno.env.get("HOME");



// const tmpdir = Deno.dir("tmp");

import {
  join as pathJoin,
  basename as pathBasename,
} from "https://deno.land/std@0.55.0/path/mod.ts";

const tmpdir = Deno.env.get("XDG_RUNTIME_DIR") || pathJoin(homedir, ".tmp")
```

see also
https://deno.land/manual@v1.26.1/getting_started/permissions#configurable-permissions
https://deno.land/x/xdg@v10.5.1
