### ISSUE TITLE
Deno.compile improperly handles side-effect-only modules.

### ISSUE THREAD

**Issue by jcc10** [denoland/deno#8684]
(v1.6.0)

`main.ts`
```ts
const [diagnostics, emitMap] = await Deno.compile(
  "./a.ts",
  undefined,
  {},
);
console.log(emitMap);
```
`a.ts`
```ts
/// <reference lib="esNext" />
/// <reference lib="dom" />
/// <reference no-default-lib="true"/>

declare var document: Document;

const messages: HTMLDivElement = <HTMLDivElement> document.getElementById(
  "messages",
);
const socket = new WebSocket(`ws://${window.location.host}/ws`);
socket.onmessage = (event) => {
  const data = "STRING:" + event.data;
  messages.innerHTML = data.toString() + "<br />" + messages.innerHTML;
};
```

Obviously this file should output a side-effect only module. However it doesn't.

More importantly the following `a.ts` file does generate valid output.
```ts
/// <reference lib="esNext" />
/// <reference lib="dom" />
/// <reference no-default-lib="true"/>

declare var document: Document;

const messages: HTMLDivElement = <HTMLDivElement> document.getElementById(
  "messages",
);
const socket = new WebSocket(`ws://${window.location.host}/ws`);
socket.onmessage = (event) => {
  const data = "STRING:" + event.data;
  messages.innerHTML = data.toString() + "<br />" + messages.innerHTML;
};
export const sideEffectOnly = undefined;
```

I think this may have to do with tree-shaking, the fact that there is no export means it can drop the module. But it would be nice if that could emit a diagnostic when explicitly compiling a file that is being tree-shaken.

**Comment by kitsonk** [comment]
It isn't a Deno issue and technically it isn't a TypeScript issue either, as TypeScript compiles both scripts and modules. When modules lack and import or export statement, they are treated as scripts. This is explained here: https://www.typescriptlang.org/docs/handbook/modules.html

The current canonical way to denote a module is `export {}` when there are no other exports. There is a TC39 proposal to clarify this ambiguity though: https://github.com/tc39/proposal-modules-pragma.

**Comment by jcc10** [comment]
@kitsonk  I think I may not have been entirely clear. No code is generated. At all. The result of Deno.compile is `emitMap == {}`. The only way to get emitMap to have content is to explicitly declare it as a module. I guess I thought that a compile on a script/side-effect-only module would be the same as running Deno.transpileOnly (which I have not tested to see if it also outputs nothing.) and simply remove the TS and output the JS.

Should I replace 'module' with script in the top post to remove ambiguity?

**Comment by nayeemrmn** [comment]
https://www.typescriptlang.org/docs/handbook/modules.html:

> In TypeScript, just as in ECMAScript 2015, any file containing a top-level `import` or `export` is considered a module. Conversely, a file without any top-level `import` or `export` declarations is treated as a script

The "just as in ECMAScript 2015" part is false 🙃 none of this guesswork is specified by ES. It would be proper for TS to allow the host to specify that everything is a module or otherwise out-of-band.

**Comment by kitsonk** [comment]
`Deno.transpileOnly()` is slightly different than `Deno.compile()` in that it uses a different emitter.  We will reconcile it one way when we replace `Deno.compile()` and `Deno.transpileOnly()` with `Deno.emit()` (#4752), but as stated above, because the first module isn't considered a "module" by the TypeScript emitter (what `Deno.compile()` uses) it does not emit anything and technically the code of the first "module" is ambiguous.  It is a TypeScript design limitation, one we cannot fix.  The workaround is to add an import or export statement to the module so it is no longer ambiguous (with the canonical way for a module with no other exports or imports is `export {}`).
