### ISSUE TITLE
Expose JavaScript minification for bundler

### ISSUE THREAD

**Issue by jveres** [denoland/deno#8685]
Since swc is capable of minifying the generated JavaScript code, maybe this could be exposed via command line parameter, e.g. `--minify`. I already made a [fork](https://github.com/jveres/deno) and smoke tested. It works but has some bugs.
@kdy1 do you think it's mature enough to bring into Deno?

**Comment by kdy1** [comment]
@jveres swc does not have minifier at the moment. `minify` in `codegen::Config` is just about skipping semicolons.

**Comment by jveres** [comment]
then it's maybe too early, I still have to stick with `terser`
