### ISSUE TITLE
ARM Raspberry Pi support?

### ISSUE THREAD

**Issue by elgs** [denoland/deno#8697]
I am running Arch Linux on Raspberry Pi and it seems deno is not working on it yet. I wonder if this is something on the road map or not? Thanks.

**Comment by crowlKats** [comment]
Duplicate of https://github.com/denoland/deno/issues/1846

**Comment by elgs** [comment]
Thanks!

**Comment by a-x-** [comment]
Why is it duplicate?
#1846 is about arm64, but raspberry has other arch: armv7l

So, currently deno binary does not work on Raspberry, 
Event hayd/alpine-deno:1.8.2 docker image does not work on Pi.

**Comment by a-x-** [comment]
Building Deno on rpi4 does not work too...
```
   Compiling naga v0.3.2
error: failed to add native library /tmp/cargo-installmGoXAQ/release/gn_out/obj/librusty_v8.a: file too small to be an archive

error: aborting due to previous error

error: could not compile `rusty_v8`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: failed to add native library /tmp/cargo-installmGoXAQ/release/gn_out/obj/librusty_v8.a: file too small to be an archive

error: aborting due to previous error

error: failed to compile `deno v1.8.2`, intermediate artifacts can be found at `/tmp/cargo-installmGoXAQ`
```

**Comment by a-x-** [comment]
Looks like more relevant issues is: #2295
