### ISSUE TITLE
Utilise the emit from swc instead of tsc

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#8706]
In Deno 1.6 we added isolated modules to the _ignored options_, which means that Deno is forcing the built-in TypeScript type checker (`tsc`) to not use type dependent emits, which means the same TypeScript code that compiles under normal operations also supported under `--no-check`.  This "unlocks" us using swc to do all the emitting and stop using tsc to do the emit.

My estimates are that it will sped up "checking" of TypeScript by 20-30%, which is significant.

**Comment by kitsonk** [comment]
@ry on my machine with tsc emit:

```
Benchmark #1: deno cache --reload test_util/std/examples/chat/server_test.ts
  Time (mean ± σ):     954.6 ms ±  63.6 ms    [User: 1.510 s, System: 0.061 s]
  Range (min … max):   898.6 ms … 1069.2 ms    10 runs
```

And without tsc emit:

```
Benchmark #1: deno cache --reload test_util/std/examples/chat/server_test.ts
  Time (mean ± σ):     868.3 ms ±   8.1 ms    [User: 1.382 s, System: 0.047 s]
  Range (min … max):   857.0 ms … 881.3 ms    10 runs
```

So more like a 10% reduction instead of a 20-30% reduction like I thought.

**Comment by bartlomieju** [comment]
@kitsonk are there any blockers for this at the moment? If not, I would like to take a stab at it.

**Comment by kitsonk** [comment]
@dsherret has a better idea of the current state of swc. It should be a trivial change.
