### ISSUE TITLE
 CTRL V freezes the REPL and computer in Linux Desktop

### ISSUE THREAD

**Issue by JoanaBLate** [denoland/deno#8719]
Typing  **CTRL V** freezes the REPL and the desktop (Linux Mint 18.3 Cinnamon 64-bit).

Using Deno 1.6.0

**Comment by caspervonb** [comment]
Hmm, I can't reproduce on Mac nor Ubuntu.

Maybe someone else is able to reproduce?

**Comment by AnInternetTroll** [comment]
On Ubuntu’s default terminal and alacritty if I press twice ctrl+v it freezes. (Also it might have frozen my computer just now not sure)

**Comment by caspervonb** [comment]
Also at @JoanaBLate is ctrl-v bound to anything in your terminal emulator?

**Comment by JoanaBLate** [comment]
@caspervonb 


CTRL V is ok without any CLI
CTRL V is ok with nodes repl

Problem is with deno

I use the standard bash

**Comment by caspervonb** [comment]
> I use the standard bash

That's your shell, I'm wondering what the program (terminal emulator) that is running the shell is, e.g gnome-terminal, terminator, xterm, etc because I'm wondering if it has bound anything to ctrl-v.

What are you expecting the outcome of hitting ctrl-v to be?

**Comment by JoanaBLate** [comment]
@caspervonb 

CTRL V was pressed by accident. I wanted CTRL SHIFT V.

CTRL V has no use. I never configured it.

About the terminal:

> GNOME Terminal 3.18.3
> A terminal emulator for the GNOME desktop using VTE version 0.42.5 +GNUTLS

**Comment by SyrupThinker** [comment]
I can reproduce this with Deno 1.6.0 and a master build at 31935c6b8d8f763a5cf809b940427024da01a71c.

Pressing Ctrl-v, the readline quote command,
and then another control combination like Ctrl-v, Ctrl-a or Ctrl-g,
thus inputting `\x16`, `\x01` or `\x07` respectively, makes the repl unresponsive.

I narrowed the issue down to a call into swc's lexer [here](https://github.com/denoland/deno/blob/31935c6b8d8f763a5cf809b940427024da01a71c/cli/ast.rs#L469-L474), called from the repl's highlighter, which never returns.

I currently don't have time to investigate this further, so if someone wants to take a stab at this, go for it.
