### ISSUE TITLE
SyntaxError with nullish coalescing operator and logical operator only when compiling

### ISSUE THREAD

**Issue by xaviripo** [denoland/deno#8722]
I think there are some syntax issues with the `??` operator.

Given a file `test.ts` like:

```ts
console.log((true || false) ?? true);
```

Running it with `deno run` works fine, but compiling and then running it throws `SyntaxError`:

```
$ deno run test.ts
Check file:///Users/xaviripo/dev/test/test.ts
true
$ deno --unstable compile test.ts
Check file:///Users/xaviripo/dev/test/test.ts
Bundle file:///Users/xaviripo/dev/test/test.ts
Compile file:///Users/xaviripo/dev/test/test.ts
Emit test
$ ./test
error: Uncaught SyntaxError: missing ) after argument list
    at file://$deno$/bundle.js:1:20
```

Replacing the `||` with `&&` also has this behavior.

Any of the following compile and run properly:

```ts
console.log(true ?? true);
```
```ts
console.log(true || false);
```
```ts
console.log(true ?? (true || false));
```
```ts
console.log(true || (false ?? true));
```

I tried inspecting the generated binary but I'm not knowledgeable enought to find the embedded TypeScript/JavaScript.

`deno --version`:
```
deno 1.6.0 (release, x86_64-apple-darwin)
v8 8.8.278.2
typescript 4.1.2
```
OS: macOS 11.0.1 Big Sur

**Comment by bartlomieju** [comment]
This is most likely problem with the bundler. The issue should be repeatable when doing `deno bundle` and trying to run generated bundle.

**Comment by xaviripo** [comment]
You are right:

```
$ deno bundle test.ts bundle.ts
Bundle file:///Users/xaviripo/dev/test/test.ts
Check file:///Users/xaviripo/dev/test/test.ts
Emit "bundle.ts" (36B)
$ cat bundle.ts
console.log(true || false ?? true);
```

The bundler is dropping the parentheses.

**Comment by bartlomieju** [comment]
CC @kdy1 is this a known issue?

**Comment by kdy1** [comment]
No, but fixing it will be easy. I'll fix it tomorrow.
