### ISSUE TITLE
Logger Setup is not global

### ISSUE THREAD

**Issue by jw2476** [denoland/deno#8723]
I define my desired logging setup eg:

```typescript
// main.ts

import * as log from "https://deno.land/std/log/mod.ts"

await log.setup({
    handlers: {
        console: new log.handlers.ConsoleHandler("DEBUG"),

        file: new log.handlers.FileHandler("WARNING", {
            filename: "./log.txt",
            formatter: "{levelName} {msg}",
        }),
    },
    loggers: {
        default: {
            level: "DEBUG",
            handlers: ["console", "file"],
        }
    }
});
```

Then when I use it in other files the configuration is not saved eg:

```typescript
// notMain.ts

import * as log from "https://deno.land/std/log/mod.ts"

log.debug("Hello, World!") // Nothing prints
```

I think this should be global as it will save a lot of code re-use

**Comment by lucacasonato** [comment]
The configuration is global. The issue is likely that that you are importing `notMain.ts` from `main.ts` - that means code in `notMain.ts` is run before `main.ts`.

**Comment by jw2476** [comment]
Won't this make logging in libraries impossible though, as they can't import the application it's being used in?
