### ISSUE TITLE
deno 1.6.0 bundler still not working quite right

### ISSUE THREAD

**Issue by aricart** [denoland/deno#8725]
The bundler in 1.6.0 is referencing symbols in using their exported names, rather than the internal names it assigned.
Here's an example (stack trace from Chrome):
```
nats.mjs:3910 Uncaught (in promise) ReferenceError: setUrlParseFn is not defined
    at connect2 (nats.mjs:3910)
    at Object.run (bench.js:55)
    at HTMLButtonElement.onclick (bench.html:46)
```

If we look at the mjs file:
```
3910: function connect2(opts7 = {
}) {
    setUrlParseFn(wsUrlParseFn);
    setTransportFactory(()=>{
        return new WsTransport();
    });
    return NatsConnectionImpl.connect(opts7);
}
```
setUrlParseFn is defined in the exports:
```
7575: export { ..., setUrlParseFn1 as setUrlParseFn,...
```

Internally the function that is defined by the library is:
```
370: function setUrlParseFn2(fn) {
    urlParseFn = fn;
}
...
1404: const setUrlParseFn1 = setUrlParseFn2;
```

To generate the same file you can:
`deno bundle https://raw.githubusercontent.com/nats-io/nats.ws/deno-1.6.0/src/mod.ts`

**Comment by aricart** [comment]
Last version of the bundler that worked correctly was with `deno 1.4.6` - that version can still be used to generate a proper mjs file.

**Comment by bartlomieju** [comment]
CC @kdy1

**Comment by kitsonk** [comment]
This is still broken.
