### ISSUE TITLE
deno coverage

### ISSUE THREAD

**Issue by aricart** [denoland/deno#8726]
the coverage feature is super awesome - however, if I have a project directory structure like:
```
other/
src/
tests/
```

Where tests references code exported by src/ and src references code exported by other, I only see coverage for non-test files in test/ (which are test support files).

**Comment by bartlomieju** [comment]
CC @caspervonb

**Comment by caspervonb** [comment]
Related #7563

This is being addressed in #8664

**Comment by lucacasonato** [comment]
@caspervonb is this resolved now?

**Comment by caspervonb** [comment]
It's not that strict now but still need *better* filtering.

**Comment by caspervonb** [comment]
We've added a new subcommand for reporting which changed the filtering.

You you can control the filter via two flags, --include and --exclude which are used to match against urls.
By default these only include file urls and exclude files ending with `test.<ext>` but can be overridden.

See the documentation for more information.

Cheers!
