### ISSUE TITLE
Compiling Executables don't work with upx

### ISSUE THREAD

**Issue by skywalker512** [denoland/deno#8728]
I found that the generated file was close to 50 mb in size, so I tried to see if I could compress it using upx, and although the executable was reduced to about 20 mb, it did not execute properly.

Environment.
deno 1.6.0
macos 11.0.1(intel)
upx 3.96

I found a discussion of this in the relevant project issue：
https://github.com/vercel/pkg/issues/50
https://github.com/vercel/pkg/issues/121
https://github.com/upx/upx/issues/2

**Comment by MarkTiedemann** [comment]
Did you pack deno before compiling? See https://github.com/denoland/deno/issues/986#issuecomment-742041812

**Comment by bartlomieju** [comment]
We'll provide lite binaries for `deno compile` (about 20Mb) in the next release once #8640 lands.
