### ISSUE TITLE
import local module with relative path

### ISSUE THREAD

**Issue by vyushin** [denoland/deno#8741]
Code:

```typescript
import { parse } from 'https://deno.land/std@0.80.0/flags/mod.ts';
import { resolve } from 'https://deno.land/std/path/mod.ts';
import { generate } from '../modules/generator';
const args = parse(Deno.args);

const IN_DIR = resolve(args.in);
const OUT_DIR = resolve(args.out);

generate(IN_DIR, OUT_DIR);
```

Error
```bash
error: Access denied. (os error 5)
```

When I remove string with import generator from relative path then the error doesn't happen.
I tried run Deno with `-A`, but that doesn't resolve the case.
How can I import any modules from relative path?

**Comment by Soremwar** [comment]
That error is really cryptic, check your Deno version is up to date.

That relative module (generator) should have extension as well, so that's probably it

**Comment by vyushin** [comment]
@Soremwar 
> That relative module (generator) should have extension as well, so that's probably it

Adding extention resolved the case. Thanks!
