### ISSUE TITLE
Bug in regex test

### ISSUE THREAD

**Issue by guilhermewebdev** [denoland/deno#8747]
I want report a bug, when I test the regex into variable, it match sometimes.

![image](https://user-images.githubusercontent.com/39817303/102027953-58d1f980-3d86-11eb-8ee6-880f1beb2622.png)

**Comment by lucacasonato** [comment]
This is not a bug. Deno runs standard JS through V8 (same JS engine as Chrome and Node), and what you have discovered is actually a JS "feature". JavaScript regular expression objects are stateful when they have `/g` or `/y` flag in the pattern to match. See https://medium.com/javascript-in-plain-english/most-surprising-behavior-of-javascript-regular-expression-you-have-ever-seen-1ddb84539163
