### ISSUE TITLE
Deno saves file in the wrong place

### ISSUE THREAD

**Issue by darklight9811** [denoland/deno#8751]
When I try to use writeAll/Deno.open, it saves in the wrong place. Entire code can be found [here](https://github.com/darklight9811/binance-demo-bot)

## Code
``` typescript
import { ensureDirSync } from "https://deno.land/std@0.80.0/fs/ensure_dir.ts";
import { join, parse } from "https://deno.land/std@0.80.0/path/mod.ts";

const encoder  = new TextEncoder();
const text = encoder.encode("somebody save me");
const savePath = join('logs', `file.log`);

ensureDirSync(parse(savePath).dir);

const file = Deno.openSync(savePath, { write:true, create:true, append:true });
Deno.writeAllSync(file, text);
Deno.close(file.rid);
```

It saves at:
```
C:\VTRoot\HarddiskVolume4\documentos\projetos\javascript\deno\binance\logs
```

Instead of (where the project is at)
```
D:\documentos\projetos\javascript\deno\binance
```

I also tried appending Deno.cwd() to the join command

## Config
deno version: 1.6.0
windows: 10.0.18363 Compilação 18363

**Comment by ebebbington** [comment]
I tried replicating it on windows, running the script from my D drive. Couldn't replicate.

Example of what i did:
```
PS D:\Development\ebebbington\some-repo> touch a.ts # then added the code above to the file
PS ... > deno run -A a.ts
PS ... > ls
logs
PS ... > ls logs
file.log
```
Deno version 1.6.0

**Comment by darklight9811** [comment]
@ebebbington, the strange thing that this was working on Deno 1.0, when I updated it stopped working. Should I log my windows also here?

**Comment by ebebbington** [comment]
@darklight9811 when the script is ran, are you sure your `cwd` is in the D drive?

You could also do `deno upgrade --version 1.0.0`, re-run the script and check the issue isn't present

**Comment by darklight9811** [comment]
@ebebbington, now that I downgraded, it didn't work also. But I don't understand, there are no correlation to the path it saves and the project path.

**Comment by caspervonb** [comment]
Sanity check please (I sure as heck am stumped).

```
console.log(savePath)
```

**Comment by littledivy** [comment]
![deno_issue](https://user-images.githubusercontent.com/34997667/102089439-34d3ee00-3e42-11eb-839f-134867d2bdf1.png)

Cannot reproduce on Ubuntu.

**Comment by ebebbington** [comment]
Also below, add `console.log(Deno.cwd())` if that's ok?

**Comment by darklight9811** [comment]
![image](https://user-images.githubusercontent.com/20667774/102089542-22829180-3dfb-11eb-930c-e05ecadaddf6.png)
![image](https://user-images.githubusercontent.com/20667774/102089552-27474580-3dfb-11eb-8c3e-56ccdfa803f4.png)

**Comment by darklight9811** [comment]
@caspervonb 
![image](https://user-images.githubusercontent.com/20667774/102090065-c1a78900-3dfb-11eb-923b-b70ebf190179.png)

![image](https://user-images.githubusercontent.com/20667774/102090082-c9672d80-3dfb-11eb-9e7f-db850b76a607.png)

**Comment by ebebbington** [comment]
try upgrading back to v1.6.0 and clearing the cache? (the `DENO_DIR` path in `> deno info`), then run again

**Comment by darklight9811** [comment]
@ebebbington, still nothing. I don't know where he is taking this saved path from :(

**Comment by ebebbington** [comment]
can do you the following:

```
PS ... > pwd
PS ... > deno run -A app.ts
PS ... > ls
```

**Comment by darklight9811** [comment]
@ebebbington

```
PS D:\documentos\projetos\javascript\deno\binance> pwd

Path
----
D:\documentos\projetos\javascript\deno\binance
```

```
PS D:\documentos\projetos\javascript\deno\binance> deno run -A test.ts     
D:\documentos\projetos\javascript\deno\binance\logs\14-12-2020asds.log     
 D:\documentos\projetos\javascript\deno\binance
```

```
PS D:\documentos\projetos\javascript\deno\binance> ls                      


    Diretório: D:\documentos\projetos\javascript\deno\binance


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       13/12/2020     02:22                .vscode
d-----       14/12/2020     01:11                logs
d-----       13/12/2020     23:47                src
-a----       14/07/2020     00:50            129 .editorconfig
-a----       14/07/2020     00:50            165 .env
-a----       14/07/2020     00:50             65 .env.example
-a----       14/12/2020     01:36             19 .GITIGNORE
-a----       14/12/2020     01:12            728 index.ts
-a----       14/07/2020     00:48           1558 LICENSE
-a----       14/07/2020     00:48             18 README.md
-a----       14/12/2020     10:52            711 test.ts


PS D:\documentos\projetos\javascript\deno\binance>
```

**Comment by ebebbington** [comment]
Isn't the file inside that `logs` dir in the last screenshot?

**Comment by darklight9811** [comment]
@ebebbington , no, it's the savePath that I'm logging. The funny thing is that if I delete the logs directory (that is in the right place), ensureDir complains that the file already exists (os error 183). Something really wrong is happening here.

**Comment by ebebbington** [comment]
can you `ls logs` just for sanitisation and post the screenshot?

**Comment by darklight9811** [comment]
@ebebbington
![image](https://user-images.githubusercontent.com/20667774/102092720-1d274600-3dff-11eb-9adf-bbd0078a8937.png)

**Comment by darklight9811** [comment]
@ebebbington, I'm really sad because this is holding me back in finishing my project. And I already spent hours and hours trying to figure it out.

**Comment by ebebbington** [comment]
A few things you can try out (but don't really offer a solution), are try running the script in different dirs:

```
PS ...> cd somewhere/else
PS ...> cp path/to/app.ts ./app.ts
PS ...> deno run -A app.ts
PS ...> ls logs
```

Maybe worth doing this for both the C and D drives - it could just be that dir that is problamatic

Maybe even try uninstall deno completely then reinstall it

**Comment by darklight9811** [comment]
@ebebbington, just tried different directories and in the C drive, also tried reinstalling deno. Nothing worked.

**Comment by lucacasonato** [comment]
cc @nayeemrmn

**Comment by nayeemrmn** [comment]
@darklight9811 Can you confirm the value of `parse(savePath).dir` as well? If that's as expected please make the reproduction smaller.

**Comment by Seally** [comment]
Cannot reproduce either on Windows 10. 

Is this run in Comodo sandbox or something? I get the sense that you have a external program that somehow redirects file write locations and Comodo sandbox is my first hit on Google search for `VTRoot`.

**Comment by darklight9811** [comment]
@nayeemrmn Confirmed that is as expected.

``` typescript
// Packages
import { ensureDirSync } 	from "https://deno.land/std@0.80.0/fs/ensure_dir.ts";
import { join, parse }		from "https://deno.land/std@0.80.0/path/mod.ts";

const encoder 	= new TextEncoder();
const text 		= encoder.encode("hi" + "\n");
const savePath	= join(Deno.cwd(), 'logs', `test.log`);

//Make sure the path exists
ensureDirSync(parse(savePath).dir);

console.log(parse(savePath).dir, '\n', savePath, '\n', Deno.cwd());

//Write to file
const file = Deno.openSync(savePath, { write:true, create:true, append:true });
Deno.writeAllSync(file, text);
Deno.close(file.rid);
```

Tested the following code in many different directories.

@Seally no, just normal windows

@ebebbington just noticed that using `deno upgrade --version 1.0.0` doesn't change anything. Also:
![image](https://user-images.githubusercontent.com/20667774/102108477-bfe8c000-3e11-11eb-8a8a-411775b6189e.png)

**Comment by Seally** [comment]
@darklight9811 I still think you have a software that somehow sandboxes Deno, or the terminal it runs in, since I can't fathom why else a file-write operation would redirect to `VTRoot`, which doesn't even exist under normal Windows, so it's highly unlikely there's any code in Deno that would reference it.

The path it actually saves to is a mirror of the intended path

`C:\VTRoot\HarddiskVolume4\documentos\projetos\javascript\deno\binance\logs`
`D:\documentos\projetos\javascript\deno\binance`

with `D:\` => `C:\VTRoot\HarddiskVolume4\`.

This person on Steam apparently had similar issues with Comodo sandboxing, and you'll probably need to check its settings and unblock it for the Deno executable: https://steamcommunity.com/discussions/forum/1/617328967248066054/

**Comment by darklight9811** [comment]
@Seally thank you thank you thank you, I can't thank you enough for that help. It was that. The strange thing that this doesn't happen to Node or PHP.

**Comment by Seally** [comment]
I suspect that Node and PHP, both having been around for much longer, may have already been added to whatever exceptions list the software used, but Deno wasn't recognized and so got sent to the untrusted bin.

In any case, congrats on the getting the problem solved. And now we're all a little wiser. 😄
