### ISSUE TITLE
Uncaught dynamic import promise error should log the stack...

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#8769]
We should log the stack trace in uncaught promise errors.  Currently we get something like:

```
error: Uncaught (in promise) TypeError: Cannot resolve module "file:///a/bad.js".
```

When if the error is caught on the rejected promise and the stack logged manually, you get something like:

```
TypeError: Cannot resolve module "file:///a/bad.js" from "file:///a/b.js".
    at file:///a/b.js:1:0
```

**Comment by nayeemrmn** [comment]
Is there a reproduction that doesn't use dynamic imports?

**Comment by kitsonk** [comment]
Hmmmm...

```js
Promise.reject(new Error("ooops"));
```

```
error: Uncaught (in promise) Error: ooops
Promise.reject(new Error("ooops"));
               ^
    at file:///Users/kitsonk/github/deno/test.js:1:16
```

So only loader/core promises?  @bartlomieju any ideas?

**Comment by bartlomieju** [comment]
Now that I'm thinking about it, it might be that only dynamic imports are missing stack traces: https://github.com/denoland/deno/issues/3813 and https://github.com/denoland/deno/issues/2887 but I'm pretty sure this was fixed at some point and tests were added 🤔  

It looks like this errors is thrown from `module_resolve_callback` in `core/bindings.rs`, need to investigate more.

**Comment by nayeemrmn** [comment]
> When if the error is caught on the rejected promise and the stack logged manually, you get something like:
> 
> ```
> TypeError: Cannot resolve module "file:///a/bad.js" from "file:///a/b.js".
>     at file:///a/b.js:1:0
> ```

I'm actually not able to reproduce this. I'm seeing on #8750's branch that V8 is not giving us any stack frames (the "giving" happens in the `prepareStackTrace()` callback) for loader errors, which makes sense. The stacks from regular thrown errors at the construction of the `Error`, and I assume the `TypeError` for these errors are constructed anonymously by V8. Also, isn't this issue only applicable on #8750's branch?

**Comment by kitsonk** [comment]
#8750 fixes something that exposes an issue with `core/bindings.rs` it would seem...

When I did the following on #8750's branch I got the stack frame:

```js
import("./b.js").catch((err) => {
  console.log(err.stack);
});
```

Where `b.js` is something like:

```js
export * as bad from "./bad.js";
```

Which feels like the prepare stack trace is not occurring when there are type errors thrown from outside before the runtime realises the promise is not caught.

**Comment by bartlomieju** [comment]
I wonder if explicitly accessing `stack` in `module_resolve_callback` would help with the issue, something along the lines:
```
diff --git a/core/bindings.rs b/core/bindings.rs
index d9c875e60..9743298d5 100644
--- a/core/bindings.rs
+++ b/core/bindings.rs
@@ -754,7 +754,12 @@ pub fn module_resolve_callback<'s>(
     r#"Cannot resolve module "{}" from "{}""#,
     specifier_str, referrer_name
   );
-  throw_type_error(scope, msg);
+  let message = v8::String::new(scope, message.as_ref()).unwrap();
+  let exception = v8::Exception::type_error(scope, message);
+  let key = v8::String::new(scope, "stack").unwrap();
+  // Should force to call `prepareStackTrace`
+  object.get(scope, key.into());
+  scope.throw_exception(exception);
   None
 }
```

**Comment by nayeemrmn** [comment]
Some notes.

- The relevant type error is actually this one: https://github.com/denoland/deno/blob/6356345365e766d984f591506fb475d7935685de/core/runtime.rs#L942
- Because it's constructed in Rust, it doesn't have any stack frames.
- The stack frame we see for static imports and previously saw for dynamic imports is not from any of our structured stack trace handling, it's appended as a string to the "message" here: https://github.com/denoland/deno/blob/6356345365e766d984f591506fb475d7935685de/cli/specifier_handler.rs#L43-L51 But this function is no longer invoked by our dynamic import error formatting.
- We can fix this by moving the appendage down to: https://github.com/denoland/deno/blob/6356345365e766d984f591506fb475d7935685de/cli/specifier_handler.rs#L273-L280 But it would be ideal to pass the location through our structured stack trace handling, which seems difficult.

**Comment by bartlomieju** [comment]
@nayeemrmn nice analysis! 

I'm thinking about one more approach that might work and would be `deno_core` only: when initiating a new dynamic import we could construct `TryCatch` and throw an error there to get stack trace; storing the relevant frames alongside the promise that must be resolved/rejected for that dynamic import. It would required to restructure some code related to handling of dynamic imports, the only question is: will that manually constructed exception have proper stack trace.

**Comment by bnoordhuis** [comment]
https://github.com/denoland/rusty_v8/issues/574 will probably help address this. `isolate.set_capture_stack_trace_for_uncaught_exceptions()` means you get stack traces for, well, uncaught exceptions.

Notable, uh, exception: exceptions from microtrask callbacks still won't have usable stack traces because there are no JS stack frames underneath them - that requires async stack trace support.

**Comment by bnoordhuis** [comment]
As it turns out... `isolate.set_capture_stack_trace_for_uncaught_exceptions()` already exists and is used:

https://github.com/denoland/deno/blob/1728b3ba1972faf532f261d2a7cfd6130d0f548f/core/runtime.rs#L320

So that means the issue here is likely a lack of async stack trace support.

**Comment by nayeemrmn** [comment]
I checked Chrome and Firefox and it looks like our current behaviour is correct. When a dynamic import fails, the promise rejects with the "inner" error that the imported module threw and its stack doesn't include the call site of the dynamic import. Of course when the inner error happens at module loading, there is no stack, as is the case in browsers. However:
- In Node, the call stack for any dynamically imported code includes the call site for the dynamic import at the bottom:
  ```
  Error: bar
      at bar (file:///mnt/c/Users/Nayeem/projects/deno/temp2.mjs:3:11)     <-- inner error frame 1
      at file:///mnt/c/Users/Nayeem/projects/deno/temp2.mjs:9:1            <-- inner error frame 2
      at ModuleJob.run (node:internal/modules/esm/module_job:154:23)       <-- <internal>
      at async Loader.import (node:internal/modules/esm/loader:166:24)     <-- <internal>
      at async foo (file:///mnt/c/Users/Nayeem/projects/deno/temp.mjs:2:3) <-- dynamic import call site frame 1
      at async file:///mnt/c/Users/Nayeem/projects/deno/temp.mjs:7:5       <-- dynamic import call site frame 2
  ```
  I think this is just an architectural quirk of its ES modules implementation. Like, that is the actual V8 call stack for Node. But it happens to provide what this issue asks for.
- In Chrome, the `error.stack` matches our current behaviour. But the red boxed message that appears for _uncaught_ dynamic import rejections (equivalent to our uncaught error message printed on termination) can be expanded to also show the dynamic import call site underneath: 
![image](https://user-images.githubusercontent.com/29990554/108471426-4ba02200-7283-11eb-918d-c1bba0609781.png)
We should match this behaviour if any.

**Comment by nayeemrmn** [comment]
I went with a fix that only enhances _resolution_ errors like in the top example, which otherwise have no stack. This ensures all dynamic import errors have at least some call site the user can refer to.
