### ISSUE TITLE
Deno Mongo - crashing when passing an id that does not exist in db 

### ISSUE THREAD

**Issue by chansdad** [denoland/deno#8774]
I am using Mongo/Oak/Deno (MOD)  , and a simple rest api to find a document by id .

My controller code 
```

getAssetById: async ({ params, response,}: { params: { id: string }; response: any; }) => {
    console.log("Passed Id is ........", params.id); 
    const asset = await assets.findOne({ _id: { $oid: params.id } });
    if (!asset) {
      response.status = 404;
      response.body = {
        success: false,
        message: "No asset found , unable to find by id....",
      };
      return;
    }
```
Router is 
```
import { Router } from "https://deno.land/x/oak/mod.ts";
const assetRouter = new Router();
import assetController from "../controllers/asset.ts";

assetRouter
  .get("/api/assets/:id", assetController.getAssetById)
export default assetRouter;

```
Note that when i pass in an id that exists in the collection , I get a successful response , but when I pass an id that does not exist in the collection , deno server crashes . Here is the stack trace . Behavior is same even for put as well  

Appreciate if anyone can let me know if this is a bug or if i am missing something?

Thanks in advance.

Listening on: http://localhost:8080
Passed Id is ........ 5fd81eed0ac3e302d554d9b
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: FromHexError(OddLength)', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/bson-0.14.1/src/bson.rs:575:71
stack backtrace:
   0:        0x110e3074e - _ZL12preoptimized
   1:        0x110e56b9c - _ZL12preoptimized
   2:        0x110e29819 - _ZL12preoptimized
   3:        0x110e32445 - _ZL12preoptimized
   4:        0x110e32182 - _ZL12preoptimized
   5:        0x110e329a5 - _ZL12preoptimized
   6:        0x110e32572 - _ZL12preoptimized
   7:        0x110e6deaf - _ZL12preoptimized
   8:        0x110e6ddb5 - _ZL12preoptimized
   9:        0x110c9db5b - _ZL12preoptimized
  10:        0x110c9b3fa - _ZL12preoptimized
  11:        0x110ca5fcd - _ZL12preoptimized
  12:        0x110c9b3ef - _ZL12preoptimized
  13:        0x1109deb8c - _ZL12preoptimized
  14:        0x1109ae1a1 - _ZL12preoptimized
  15:        0x1109aed0a - _ZL12preoptimized
  16:        0x10db9015c - <futures_util::future::future::Inspect<Fut,F> as core::future::future::Future>::poll::hd24f7d792f74d7b1
  17:        0x10ddfe44e - <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll::h5a425c0ebbcf4c87
  18:        0x10de0344f - <futures_util::stream::futures_unordered::FuturesUnordered<Fut> as futures_core::stream::Stream>::poll_next::h51fc83ad3470a723
  19:        0x10de117e3 - deno_core::runtime::JsRuntime::poll_event_loop::h7ff06937a36d8c26
  20:        0x10dcb3e81 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h37546b3645967836
  21:        0x10dcb4f69 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h3ee3a07e397ab9e8
  22:        0x10dc83da1 - tokio::runtime::Runtime::block_on::h41ff2cae773925f7
  23:        0x10dd99545 - deno::main::hb0c93d63f515d33f
  24:        0x10dc1fdf2 - std::sys_common::backtrace::__rust_begin_short_backtrace::hd9f62a358ed77836
  25:        0x10dda0c87 - main

**Comment by kitsonk** [comment]
This is an issue with the Mongo plugin you are using. You will need to open an issue there.
