### ISSUE TITLE
Windows REPL: AltGr input no longer working

### ISSUE THREAD

**Issue by hastri** [denoland/deno#8777]
Since Deno version 1.6 the REPL ignores characters that are typed with the AltGr key. Even when pasting text those characters are skipped. Since it is working when i use the bash of the Linux Subsystem I'm assuming it is a Windows problem.

**Comment by bartlomieju** [comment]
Possibly related to https://github.com/kkawakam/rustyline/pull/476, need to upgrade `rustyline` to `7.1.0`
