### ISSUE TITLE
Remove dependency on "warp" in "deno_runtime" crate

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#8782]
In https://github.com/denoland/deno/pull/8781 it became apparent that `warp` crate is used only in `runtime/inspector.rs`. 

Following TODO can be found in `runtime/inspector.rs`:
https://github.com/denoland/deno/blob/6356345365e766d984f591506fb475d7935685de/runtime/inspector.rs#L151-L154

Additionally it's becoming a bit challenging to keep `warp` and other crates that depend on `hyper` in sync to use only a single version of `hyper`. 

Let's remove `warp` as a dependency and rewrite `runtime/inspector.rs` in such a fashion that create a simple WS server using `hyper` ourselves.

CC @piscisaureus @ry

**Comment by lucacasonato** [comment]
This is not trivial as hyper does not have a built in WS server. See https://github.com/seanmonstar/warp/blob/master/src/filters/ws.rs for inspiration.

**Comment by bartlomieju** [comment]
Turns out warp is based on [`tokio-tungstenite`](https://docs.rs/tokio-tungstenite/0.12.0/tokio_tungstenite/), so we should use it to rewrite the WS server.

**Comment by bartlomieju** [comment]
Example WebSocket server using `tokio-tungstenite`: https://github.com/snapview/tokio-tungstenite/blob/master/examples/server.rs

**Comment by lperlaki** [comment]
Hey, if it is ok I would like to implement this.

**Comment by bartlomieju** [comment]
@lperlaki sure, much appreciated!
