### ISSUE TITLE
FetchPermissions should support async lookup

### ISSUE THREAD

**Issue by ry** [denoland/deno#8783]
https://github.com/denoland/deno/blob/892d6cc99749247884fdbe2d89ca13def3af8bdb/op_crates/fetch/lib.rs#L64-L67

In order to do DNS resolution during the permission check.

Use async_trait https://docs.rs/async-trait/0.1.42/async_trait/

**Comment by bnoordhuis** [comment]
That leaves open a TOCTOU window where the address of the domain name to can change between the permissions check and creation of the connection, when it's looked up again.

I didn't think too deeply about it but `FetchPermissions::check_net_url()` should probably either:

1. do DNS resolution and return a list of addresses, or

2. create the connection and return it to the caller

In both cases it needs to be async.

**Comment by lucacasonato** [comment]
I think tracking this here is not helpful anymore. We should still do this, but not like this.
