### ISSUE TITLE
Add benchmark for "fetch" that downloads some big file

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#8787]
Currently we benchmark `fetch` API only in a single scenario (proxy). 

It'd be great if we benched some more real-life scenario like:
- download single big file (eg. 100Mb)
- download multiple smaller files (eg. 1Mb)

Benchmarks should use local test server for that purpose.

**Comment by WingZer0o** [comment]
Seems like this PR just didn't go through because of a contributor license? 
https://github.com/denoland/deno/pull/11508

**Comment by lucacasonato** [comment]
Going to close this, because it is stale.
