### ISSUE TITLE
"op_fetch_read" should use zero copy buffers

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#8788]
Currently "op_fetch_read" uses JSON dispatch and performs unnecessary serialization. The op should be rewritten to use zero copy buffers instead.

https://github.com/denoland/deno/blob/9fe26f8ca189ac81d9c20c454b9dbfa5e1011c3f/op_crates/fetch/lib.rs#L188-L222

Ref https://github.com/denoland/deno/issues/8787

**Comment by Soremwar** [comment]
@bartlomieju Dibs on this

**Comment by bartlomieju** [comment]
> @bartlomieju Dibs on this

@Soremwar do you mean you're working on this?

**Comment by Soremwar** [comment]
Yeah, had some trouble with cargo build but PR should come this afternoon

**Comment by 00ff0000red** [comment]
@bartlomieju Closed in https://github.com/denoland/deno/pull/9036?

**Comment by lucacasonato** [comment]
#9036 does not resolve #4735.

**Comment by 00ff0000red** [comment]
@lucacasonato Oops, my apologies, I was referring to https://github.com/denoland/deno/issues/4735#issuecomment-752193475, but yes, the root of the issue remains to be fixed.
