### ISSUE TITLE
atob should throw DOMException

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#8795]
`atob('foobar!!')` returns a `DOMException` in chrome, but it returns a `DataDecodeError` in Deno. This should be aligned to match Chrome behaviour.

**Comment by 1234567-glitch** [comment]
> `atob('foobar!!')` returns a `DOMException` in chrome, but it returns a `DataDecodeError` in Deno. This should be aligned to match Chrome behaviour.

@lucacasonato ok
