### ISSUE TITLE
brew install deno failed

### ISSUE THREAD

**Issue by elgs** [denoland/deno#8801]
```
$ brew install deno
==> Downloading https://homebrew.bintray.com/bottles/deno-1.6.0_1.big_sur.bottle.tar.gz
#=#=#                                                                         
curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "deno"
Download failed: https://homebrew.bintray.com/bottles/deno-1.6.0_1.big_sur.bottle.tar.gz
```

**Comment by proflylab** [comment]
me too

**Comment by caspervonb** [comment]
Everything seems to be in order, no broken links from our side as far as I can tell (https://github.com/Homebrew/homebrew-core/blob/4bb1f725f4e9cd7ef54ba2615f31f7d5ff7082b1/Formula/deno.rb).

**Comment by alexdohmen** [comment]
@caspervonb after brew fails downloading binaries it tries to build deno from sources. This also fails.

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "deno"
Download failed: https://homebrew.bintray.com/bottles/deno-1.6.0_1.big_sur.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading https://github.com/denoland/deno/commit/cea42bec3272a8020f1d94afcf1a4cd7e3985553.patch?full_index=1
Already downloaded: /Users/ad/Library/Caches/Homebrew/downloads/a8004fa7d98c83572d92b559955397984deae9d7043d0572e3ecbfd33dde0180--cea42bec3272a8020f1d94afcf1a4cd7e3985553.patch
==> Downloading https://github.com/denoland/deno/releases/download/v1.6.0/deno_src.tar.gz
Already downloaded: /Users/ad/Library/Caches/Homebrew/downloads/c1cce7691d7f54b11679a65a751caaaf09aba7827c7d21e7c7624d6d7c759dce--deno_src.tar.gz
==> Patching
==> Applying cea42bec3272a8020f1d94afcf1a4cd7e3985553.patch
patching file cli/flags.rs
==> cargo install -vv
Last 15 lines from /Users/ad/Library/Logs/Homebrew/deno/01.cargo:
[rusty_v8 0.14.0] [248/1250] CXX obj/v8/torque_base/torque-parser.o
[rusty_v8 0.14.0] ninja: build stopped: subcommand failed.
[rusty_v8 0.14.0] thread 'main' panicked at '
[rusty_v8 0.14.0] command did not execute successfully, got: exit code: 1
[rusty_v8 0.14.0]
[rusty_v8 0.14.0] build script failed, must exit now', /Users/ad/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/cargo_gn-0.0.15/src/lib.rs:203:3
[rusty_v8 0.14.0] note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
The following warnings were emitted during compilation:

warning: Not using sccache or ccache

error: failed to compile `deno v1.6.0 (/private/tmp/deno-20201217-30939-v1rgax/deno/cli)`, intermediate artifacts can be found at `/private/tmp/deno-20201217-30939-v1rgax/deno/target`

any idea?

**Comment by elgs** [comment]
@caspervonb who usually is the maintainer of the homebrew rb file?

**Comment by caspervonb** [comment]
> @caspervonb who usually is the maintainer of the homebrew rb file?

Am not sure, git blame is usually a good way to tell tho https://github.com/Homebrew/homebrew-core/commits/master/Formula/deno.rb

**Comment by hayd** [comment]
Will be closed by https://github.com/Homebrew/homebrew-core/pull/66920

**Comment by carlocab** [comment]
>who usually is the maintainer of the homebrew rb file?

Homebrew formulae don't have specific maintainers. However, I will admit that the `deno` bottle went missing after my PR here: https://github.com/Homebrew/homebrew-core/pull/66285 

Apologies; Rust takes nearly two full days to complete a Homebrew CI run. So we made the decision to just merge it and fix anything that breaks after, or else the Rust PR would've never gotten merged.

**Comment by carlocab** [comment]
Here is a potential workaround for the current homebrew formula:
```
cd $(brew --repo homebrew/core)/Formula
sed -i'' '/revision 1/d' deno.rb
HOMEBREW_NO_AUTO_UPDATE=1 brew install deno
brew pin deno
```
This should pick up old `deno` bottles from bintray. You can do `brew unpin deno` when this is fixed.

**Comment by carlocab** [comment]
This should be fixed now. https://github.com/Homebrew/homebrew-core/pull/67043
