### ISSUE TITLE
Add JS Doc for addEventListener

### ISSUE THREAD

**Issue by ry** [denoland/deno#8804]
Ideally with example code. This is the first method to show up on the docs. It would be great if it looked more fleshed out.

<img width="1440" alt="Screen Shot 2020-12-17 at 9 30 57 AM" src="https://user-images.githubusercontent.com/80/102500684-936bb880-404a-11eb-8f2d-a5949a212430.png">

**Comment by lucacasonato** [comment]
There is actually JS doc for this, deno doc just doesnt pick it up. See https://github.com/denoland/deno_doc/issues/31.

**Comment by championshuttler** [comment]
@lucacasonato should I close the PR then?

**Comment by ry** [comment]
-> denoland/deno_doc#31

**Comment by bartlomieju** [comment]
This issue is fixed by https://github.com/denoland/deno/pull/8836

![Screenshot 2020-12-19 at 18 37 03](https://user-images.githubusercontent.com/13602871/102695724-6cb7a880-4229-11eb-9990-2db0f5e67fc2.png)
