### ISSUE TITLE
can deno compile into bytecode?

### ISSUE THREAD

**Issue by liesauer** [denoland/deno#8820]
i just found that `deno compile` just embeds all the source codes at the end of the executable, and it is very easy to extract them. so, can deno compile the source codes into bytecodes(or any future plans) so it can protect the code.

**Comment by chenguzhen87** [comment]
I'm curious. How do you know all the source codes at the end of the executable

**Comment by caspervonb** [comment]
> I'm curious. How do you know all the source codes at the end of the executable

Can be seen in any hex editor or even objdump.

**Comment by liesauer** [comment]
> > I'm curious. How do you know all the source codes at the end of the executable
> 
> Can be seen in any hex editor or even objdump.

u are right

**Comment by kitsonk** [comment]
It is a complicated process, as we would have to generate a custom snapshot, which is also architecture specific. It is being considered, but I wouldn't expect it any time soon.

**Comment by chenguzhen87** [comment]
I was doing a comparison between Deno compile and go build products, and found that the .exe file generated by Deno is 31.4mb, and go is 2.02mb, [tests article](https://juejin.cn/post/6907850138983596046/).
Can Deno be less

**Comment by RDambrosio016** [comment]
That is an unfair comparison because go compiles to machine code plus some runtime and gc stuff, javascript cannot be compiled to machine code, therefore deno has to ship v8 and its runtime in each executable.

**Comment by lucacasonato** [comment]
Deno compiled executables will get smaller in the future though. We estimate 15-20 MB for a hello world.

**Comment by liesauer** [comment]
supporting both framework(or runtime)-dependent deployment mode and standalone deployment mode would be nice,  just like `.NET Core` does.

**Comment by wwderw** [comment]
> It is a complicated process, as we would have to generate a custom snapshot, which is also architecture specific. It is being considered, but I wouldn't expect it any time soon.

It would be nice to have something like how NW.js has.  The main thing that I had always liked about it over Electron, only downside is that it is much bigger for final product size then even electron.  Looking at 300+ MB for deployment with NW.js and about 90MBs for electron deployment.  Had to make sure making some pretty big apps to justify that harddrive size consumption.  RAM usage was about the same.

**Comment by abflow** [comment]
Related to #3335

**Comment by heyheyhello** [comment]
Related to https://github.com/denoland/deno/issues/9243 about Deno's size

**Comment by lucacasonato** [comment]
There are no plans to compile to raw instructions in `deno compile` - that would be a monumental feat for us. Consider looking into https://porffor.dev/ instead.

We will continue to work on reducing `deno compile` binary size, but this issue is not actionable for that.

**Comment by felipecrs** [comment]
Out of curiosity, [Bun 1.1.30 has shipped compilation to bytecode](https://bun.sh/blog/bun-v1.1.30#compile-to-bytecode-for-2x-faster-startup-time) which allegedly improves start time by 2x.

Improvements of such magnitude would be a huge deal for certain projects, even at the cost of bigger binaries.

FWIW [Electron Vite](https://electron-vite.org/) also allows for bytecode compilation, for V8-based runtimes.

**Comment by 0f-0b** [comment]
What about compiling to code caches? Cached code can be executed without the corresponding source code if all functions are eagerly compiled and the checksum is zeroed out.

**Comment by petamoriken** [comment]
I'm looking forward to waiting for [the Binary AST proposal](https://github.com/tc39/proposal-binary-ast).

**Comment by SerJaimeLannister** [comment]
> Out of curiosity, [Bun 1.1.30 has shipped compilation to bytecode](https://bun.sh/blog/bun-v1.1.30#compile-to-bytecode-for-2x-faster-startup-time) which allegedly improves start time by 2x.
> 
> Improvements of such magnitude would be a huge deal for certain projects, even at the cost of bigger binaries.
> 
> FWIW [Electron Vite](https://electron-vite.org/) also allows for bytecode compilation, for V8-based runtimes.

I was also thinking of the same thing!

I do hope that deno could also add bytecode support

**Comment by bartlomieju** [comment]
FYI this should be available in Deno v2.1.0 - PR to follow https://github.com/denoland/deno/pull/26528

**Comment by toomanylogins** [comment]
Can someone clarify for me that #26528 means that we can ship an executable with the code cache only ie the source does not need to be included and is therefore secure including any secret ?
Thanks

**Comment by bartlomieju** [comment]
> Can someone clarify for me that https://github.com/denoland/deno/pull/26528 means that we can ship an executable with the code cache only ie the source does not need to be included and is therefore secure including any secret ?

No, that PR adds support for V8 code cache which makes subsequent starts faster. You still need to ship source code.

**Comment by SerJaimeLannister** [comment]
> No, that PR adds support for V8 code cache which makes subsequent starts faster. You still need to ship source code.

Sorry for my ignorance but lets say that I build code cache on machine A then can I send code cache to machine B and then call that code cache from machine B directly in some sense?

**Comment by bartlomieju** [comment]
> > No, that PR adds support for V8 code cache which makes subsequent starts faster. You still need to ship source code.
> 
> Sorry for my ignorance but lets say that I build code cache on machine A then can I send code cache to machine B and then call that code cache from machine B directly in some sense?

I'm not really sure, I haven't inspected the bytecode. I would say there's a slim chance this is portable.

**Comment by toomanylogins** [comment]
The original question related to source code protection and the discussion morphed into binary size so the answers appear to be slightly mixed. As mentioned https://github.com/denoland/deno/issues/8820#issuecomment-2411776258 both Bun and electron-vite do bytecode compilation which protects the source code. Whereas the answer below refers to raw instructions which I assume is not bytecode.

> There are no plans to compile to raw instructions in `deno compile` - that would be a monumental feat for us. Consider looking into https://porffor.dev/ instead.
> 

Therefore can somebody please clarify from me if bytecode is likely to be available in Deno later in 2025 as I'm trying to make a development platform decision.

**Comment by lucacasonato** [comment]
Neither electron-vite or Bun prevent the source code from being extracted out of the binary.

We have no explicit plans to further obfuscate the source code in the binary - this would ultimately be a cat and mouse game.
