### ISSUE TITLE
Remove dependency on "warp" in "test_util" crate

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#8823]
Follow up to #8782

In `test_util` crate `warp` is used as to crate an HTTP and WS server that is used by many unit and integration tests. 

We should rewrite the server to use `hyper` instead of `warp` in an effort to reduce number of dependencies.

**Comment by yos1p** [comment]
I'd like to try to work on this.

**Comment by bartlomieju** [comment]
@yos1p great! Looking forward to a PR

**Comment by bartlomieju** [comment]
@yos1p you can use https://github.com/denoland/deno/pull/8813 as a reference for this issue
