### ISSUE TITLE
There seems to be a problem in windows 10. I click the executable file deno- compile.exe , there is no pop-up layer?

### ISSUE THREAD

**Issue by chenguzhen87** [denoland/deno#8825]

**Comment by Soremwar** [comment]
@chenguzhen87 Can you provide more information about this? What are you executing, a file compiled with Deno?

**Comment by chenguzhen87** [comment]
> @chenguzhen87 Can you provide more information about this? What are you executing, a file compiled with Deno?


I wrote a dead loop. It's OK. It may have nothing to do with Deno. It's the CMD mechanism

**Comment by chenguzhen87** [comment]
it's ok
