### ISSUE TITLE
Add performance counters 

### ISSUE THREAD

**Issue by ry** [denoland/deno#883]
I want to keep some internal counters for various statics. The prototype implementation [began work on this](https://github.com/denoland/deno/commit/a1c0862047c47f02fb07bcf01f35e3cf5c2266d3) 
https://github.com/denoland/deno/blob/golang/dispatch.go#L14-L20

The stats should be stored in `IsolateState`:
https://github.com/denoland/deno/blob/eba58b718860035b830d0739a02c6a382e1f3307/src/isolate.rs#L53-L60

I think for starters it would be interesting to have:
* a counter for how many ops were executed. (Probably best incremented inside [`msg_from_js()`](https://github.com/denoland/deno/blob/eba58b718860035b830d0739a02c6a382e1f3307/src/handlers.rs#L49) but maybe can be done on every call of `pre_dispatch()`.)
* a counter for the total bytes received from the VM (probably best to do this in [`pre_dispatch()`](https://github.com/denoland/deno/blob/eba58b718860035b830d0739a02c6a382e1f3307/src/isolate.rs#L192-L197)
* a counter for total bytes sent from the VM. (Also probably best done in `pre_dispatch()`.)
Are there other counters people want?

A complete solutions should have: 
* A test in `src/isolate.rs` that demonstrates the counters being updated.
* Adds two new messages to `src/msg.fbs` called `Stats` and `StatsRes` (would that be confusing with `Stat` and `StatRes` ? Maybe call it `Analytics` and `AnalyticsRes` ? 
* Implements the frontend TypeScript code in `js/stats.ts` (again - maybe too close to `stat.ts` - please suggest better names)

**Comment by bartlomieju** [comment]
I'm working on basic implementation of this. I'll post PR later tonight

**Comment by bartlomieju** [comment]
Closed in #917
