### ISSUE TITLE
Server aplication stops responding

### ISSUE THREAD

**Issue by hviana** [denoland/deno#8833]
I'm using Deno 1.6.0 witk oak@6.4.0 and mongo@v0.13.0 in my project:
The server sometimes gives the following error:
TypeError: Invalid URL.
at new URL (deno:op_crates/web/11_url.js:722:15)
at Request.get url (request.ts:95:19)
at dispatch (router.ts:841:45)
at dispatch (middleware.ts:41:13)
at server.ts:187:11
at dispatch (middleware.ts:41:13)
at composedMiddleware (middleware.ts:44:12)
at Application.#handleRequest (application.ts:252:34)
at Application.listen (application.ts:385:28)
at async server.ts:210:3

When the error is thrown, sometimes the server stops responding, and the application keeps running, what can it be?
I'm using Deno in production and I need to resolve this urgent problem.

**Comment by timonson** [comment]
Do you use http or https?

**Comment by hviana** [comment]
Http, but i have a aplication load balancer in amazon that converts https->http. O change the oak server for my middleware server implementation now. If problem stops, i notify here.

**Comment by bnoordhuis** [comment]
@hviana If the problem still persists, can you recheck with v1.6.3? Thanks.

**Comment by hviana** [comment]
I didn't check with version 1.6.3, however, with my server implementation (without using oak) I'm not having any problems.
