### ISSUE TITLE
Remove caFile from Deno.createHttpClient options

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#8837]
`Deno.createHttpClient` now can be configured to use a CA using the `caData` field. They `caFile` field is this not needed anymore.

**Comment by mrmodise** [comment]
@lucacasonato I will take this. Thanks

**Comment by iamkacperwasik** [comment]
I created a pull request here: https://github.com/denoland/deno/pull/8882

**Comment by mrmodise** [comment]
@iamkacperwasik thanks. You didn't update the tests. Also, the Rust files still have the change for the caFile. Anyways, I will leave it to you since you beat me to it. Happy holidays
