### ISSUE TITLE
The quotation in cmd of Deno.run

### ISSUE THREAD

**Issue by septbr** [denoland/deno#8852]
---
```typescript 
    await Deno.run({ cmd: ['TortoiseProc', '/command:commit', '/path:"D:\\xx\\yy"', '/logmsg:"update yy"']).status();
```

> Expect

```shell
    TortoiseProc /command:commit /path:"D:\\xx\\yy" /logmsg:"update yy"
```

> Result

```
    TortoiseProc /command:commit /path:\"D:\\xx\\yy\" /logmsg:\"update yy\"
```
---
```typescript 
    await Deno.run({ cmd: ['cmd', '/c', 'echo', '"x\\y"'], stdout: 'inherit', stderr: 'inherit'}).status();
```
> Expect

```cmd
    echo "x\y"
```

> Result

```cmd
    echo \"x\y\"
```
---
```typescript 
    await Deno.run({ cmd: ['cmd', '/c', 'echo', '""x\"'], stdout: 'inherit', stderr: 'inherit'}).status();
```
> Expect

```shell
    echo ""x"
```

> Result

```cmd
    echo \"\"x\"\"
```

**" in the result has been replaced by \\"**
**"" or \\"  in the result has been replaced by \\"\\"**

**Comment by rivy** [comment]
Not stale.
This is still a problem for windows applications.

**Comment by nayeemrmn** [comment]
This seems expected, and rather a limitation of the CLIs of the applications being run. Does Node have different behaviour?

**Comment by rivy** [comment]
It's not a CLI limitation.
It's an [ongoing problem](https://github.com/rust-lang/rust/issues/29494) with Rust's `process::Command`. Rust has the escape hatch of using the Win32 `CreateProcess` but Deno doesn't (and [likely won't](https://github.com/denoland/deno/issues/3892)). The windows `CreateProcess` can take an arbitrary string, but Deno isn't set up to directly call the Win32 CreateProcess function.

And, yes, it's up to the target executable to interpret it, but any arbitrary command line string should be generable by the runtime.

This is definitely a problem when spawning child processes with arbitrary command lines on Windows. It is subtle and occurs as random command lines which panic with weird quoting errors (as the examples noted above). It's very problematic when trying to work around the windows `cmd` shell quoting quirks (which is needed for task runners; `denox`, `devo`, `drake`). 

I'm not sure of the best course forward.

**Comment by rivy** [comment]
@nayeemrmn , here's a simple, specific example of why this is a problem...

* from [Propose changes to the Deno.run() API](https://github.com/denoland/deno/discussions/9435) discussion

...

Currently, it's impossible to execute certain valid Windows command lines in Deno. For example, `cmd /d/c "deno eval -T "console.log('a string')""` is a valid executable command line ...

```shell
C:>cmd /d/c "deno eval -T "console.log('a string')""
Check file:///C:/Users/Roy/OneDrive/Projects/deno/$deno$eval.ts
a string
```

when implemented via `Deno.run(...)` ...

```js
await Deno.run({cmd: ['cmd', '/d/c', '"deno eval -T "console.log(\'a string\')""']}).status();
// => `The system cannot find the path specified.`
```

or ...

```js
await Deno.run({cmd: ['cmd', '/d/c', 'deno eval -T "console.log(\'a string\')"']}).status();
// => `error: Unterminated string constant at file:///C:/Users/Roy/OneDrive/Projects/deno/$deno$eval.ts:1:0`
```

It's not possible to construct this command line because the inner double quotes are escaped, which, in turn, breaks the interpretation by `cmd`.

...

**Comment by rivy** [comment]
@nayeemrmn , can you re-open this?

**Comment by nayeemrmn** [comment]
I'm not a maintainer (cc @lucacasonato).

The issue seems valid, if `exec('cmd /d/c "deno eval -T "console.log(\'a string\')""', ...)` in Node doesn't have a working equivalent in Deno.

**Comment by lucacasonato** [comment]
cc @piscisaureus

**Comment by max-pub** [comment]
any progress on this?

**Comment by piscisaureus** [comment]
Rust actually has [raw_arg](https://github.com/rust-lang/rust/issues/92939). We could use that.

**Comment by FKPSC** [comment]
I am running into many issues with Deno.run  as well. Running commands like `start "app\\Cool app.exe"` seems to be literally impossible. If there is a way to do it, please let me know and document it somewhere. 

This command is also seemingly impossible to run:
`reg query "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion" -v ReleaseID`

A viable workaround would be to echo the command into a `.cmd` file and then run it.

**Comment by kt3k** [comment]
In Node.js, child_process.spawn has `windowsVerbatimArguments` option for controlling arg escaping enabled/disabled. https://nodejs.org/api/child_process.html#child_processspawncommand-args-options

And that option is used by [cross-spawn](https://www.npmjs.com/package/cross-spawn) npm module. ref: https://github.com/moxystudio/node-cross-spawn/blob/5d843849e1ed434b7030e0aa49281c2bf4ad2e71/lib/parse.js#L59

This issue causes the usage of cross-spawn (via compat feat) always failing on windows.
