### ISSUE TITLE
deno.open() doesn’t support write or append

### ISSUE THREAD

**Issue by ry** [denoland/deno#886]
Only read currently.

https://github.com/denoland/deno/blob/3c080ca39abff28ed2cc6ac618558cced9c2e842/js/files.ts#L29-L52

**Comment by piscisaureus** [comment]
Assigning self to not forget about this.

**Comment by kanishkarj** [comment]
Hey! Can I work on this?

**Comment by kevinkassimo** [comment]
@kanishkarj I think there is still some decisions need to make about the mode design before implementation could start

**Comment by kanishkarj** [comment]
Okayy..

**Comment by bartlomieju** [comment]
Done in #1282 #1336.

Released in v0.2.3

CC @ry

**Comment by ry** [comment]
thx
