### ISSUE TITLE
Inspector server does not implement runtime exception notifications

### ISSUE THREAD

**Issue by caspervonb** [denoland/deno#8869]
We're actually missing most notifications in all the domains, but in the context of getting #8858 working we need to wire up `Runtime.exceptionThrown`.

**Comment by bartlomieju** [comment]
@caspervonb it seems we're now collecting all received notification, but we actually discard them right away. I think this could now be addressed by checking for received notifications?

**Comment by bartlomieju** [comment]
Ref https://github.com/denoland/rusty_v8/pull/717
