### ISSUE TITLE
Stack frames report wrong promise index

### ISSUE THREAD

**Issue by eloff** [denoland/deno#8871]
Check out https://github.com/denoland/deno/blob/master/core/error.rs#L295

That probably shouldn't be the property "columnNumber" for promise_index, which is used above, unsurprisingly, for columnNumber.

While I'm here, __callSiteEvals is a Deno thing? I didn't find a reference to it anywhere else online.

**Comment by bartlomieju** [comment]
@nayeemrmn can you take a look?

**Comment by nayeemrmn** [comment]
Good catch, that's a typo. Good first issue. The JS property keys that this code reads from are listed here: https://github.com/denoland/deno/blob/b15539587e7cf6b67c2ae7d4dc39901634bf6bd5/core/error.js#L157-L175

**Comment by nayeemrmn** [comment]
Not sure why https://github.com/denoland/deno/blob/master/cli/tests/error_024_stack_promise_all.ts.out didn't catch this, apparently the column number of the test case's error is also 0? :/

**Comment by bartlomieju** [comment]
@nayeemrmn good catch, we should definitely harden the test. It might not be a good first issue after all though.

**Comment by nayeemrmn** [comment]
Hmm I still think it is with this guidance, just add an extra placeholder `Promise.resolve()` at the beginning of the array passed to `Promise.all()` in https://github.com/denoland/deno/blob/master/cli/tests/error_024_stack_promise_all.ts and change the expected index to 1.

**Comment by duci9y** [comment]
Hi there, I'm going to take a stab at this.
