### ISSUE TITLE
TLS SSL Session Reuse Support

### ISSUE THREAD

**Issue by nullobsi** [denoland/deno#8875]
I am trying to write an FTP client in Deno using the unstable `Deno.startTls` functions. However, some FTP servers require SSL session reuse. It would be nice if these functions had this, so that applications requiring session reuse would be possible.

**Comment by bnoordhuis** [comment]
I'm at a bit of a loss how to write a test for that but I'll open a PR that implements a global session cache, maybe someone has an idea.
