### ISSUE TITLE
Some test cases are being skipped in CI?

### ISSUE THREAD

**Issue by kt3k** [denoland/deno#888]
Starting from this build https://travis-ci.com/denoland/deno/jobs/147902463, the log output of test cases in CI seems incomplete. (The unit tests seem stopping in the middle without error.)

---
update:
When I set DENO_BUILD_MODE=release, the same thing happens on my local machine (mac).

**Comment by kevinkassimo** [comment]
Same thing happened to me. Seems that most `async` tests are dead.

**Comment by ry** [comment]
It seems we have some sort of memory corruption happening - somewhere. I haven’t experienced it yet but we need to correct it.

 Chrome has all sorts of memory check tools 
https://www.chromium.org/developers/testing/addresssanitizer
https://www.chromium.org/developers/testing/memorysanitizer
It shouldn’t be too much work to hook into these - I think it could be helpful debugging this issue.

**Comment by ry** [comment]
Related fix: https://github.com/denoland/deno/commit/cfa54cabbdaca48d7623cd5fd5aada59b5e02040

**Comment by kt3k** [comment]
Now all test cases seem passing in CI. Thanks for the fixes!
