### ISSUE TITLE
Remove reqwest dependency from fetch API

### ISSUE THREAD

**Issue by yos1p** [denoland/deno#8886]
After looking at `op_crates/fetch`, I believe we can just use hyper::client features with (hyper-tls or rustls). This should reduce the dependency that we need for runtime.

**Comment by lucacasonato** [comment]
I don't think so. `reqwest` does a few important things on top of hyper, most essentially compression with `gzip` and brotli.

**Comment by bartlomieju** [comment]
Agree with Luca, there's no point in re-implementing all of that functionality ourselves.
