### ISSUE TITLE
logger.debug(...) is a no-op for the default logger

### ISSUE THREAD

**Issue by lizraeli** [denoland/deno#8889]
When using the default logger from [std@0.82.0/log](https://deno.land/std@0.82.0/log), it does not log with the `debug` method, but it does log with the [higher log levels](https://deno.land/std@0.82.0/log/levels.ts#L4) `info`, `warning`, `error`, `critical`:

```ts
import * as log from "https://deno.land/std@0.82.0/log/mod.ts";

log.debug("logging with debug"); // will not log
log.info("logging with info"); // will log 
// ..
log.critical("logging with critical") // will log 
```

The reason for `debug` not logging is that the value of the `DEFAULT_LEVEL` constant in [log/mod.ts](https://deno.land/std@0.82.0/log/mod.ts#L32) is `"INFO"`.  This is used to initialize the default logger and handler, both of which consider it a no-op to log at a value below the configured level.

While this behavior can be overridden using the `setup` method, I was wondering if it's intended for the default not to log for `debug`. If it is intended, I could submit a PR to clarify this in the documentation for [log](https://deno.land/std@0.82.0/log). Otherwise I could submit a PR to update the `DEFAULT_LEVEL` to `"DEBUG"`.

**Comment by yos1p** [comment]
I think by default it should stay on INFO level. "DEBUG" logs should be printed only when developers intend to debug.

**Comment by wperron** [comment]
I jsut checked the docs and the default values aren't mentioned anywhere. I agree that `"INFO"` makes sense - I'll go ahead and update the README for this module to include a "defaults" section.

**Comment by lizraeli** [comment]
Great, thanks @wperron!
