### ISSUE TITLE
Better control of "deno test" output

### ISSUE THREAD

**Issue by hb20007** [denoland/deno#8890]
It would be nice to have better control over how the results of `deno test` are displayed.

## Current Situation

Currently, there is the `--quiet` flag, which seems to suppress all messages printed during testing. The only thing which is printed is the exit code. There is also `--log-level info` which didn't change anything in the output for me.

## Requests

1. An option to suppress printing the `Check`  message at the start, but still run the actual check and then print the test results.
2. An option to print the test results without the stack traces.

**Comment by bartlomieju** [comment]
Ref https://github.com/denoland/deno/issues/7840

**Comment by lucacasonato** [comment]
We provide more different test reporters now, including `pretty`, `dot`, and `junit`. I am going to close this issue because it is very general, and test output has changed over the last 4 years. If you have more specific suggestions, please open new issues.
