### ISSUE TITLE
--new flag, idea for an entrypoint

### ISSUE THREAD

**Issue by JeremyJaydan** [denoland/deno#8892]
Ability to instantiate a class as an entrypoint could be useful.
e.g.
```
deno run --new=MyApp ./MyApp.js
```
the above command would instantiate a new `MyApp` class with `Deno.args` as the constructor arguments. Also if the module has a default export, perhaps you could just use `--new` without specifying the class.

**Comment by bartlomieju** [comment]
Deno is very conservative when it comes to adding new CLI flags and this feature is definitely on the "magical" spectrum that we avoid. Additionally this request can be implemented as a userland script in a few lines so it's definitely outside of scope for Deno.
