### ISSUE TITLE
deno 1.6.2 build failure

### ISSUE THREAD

**Issue by chenrui333** [denoland/deno#8905]
👋 trying to build the latest release, but run into some build issue. The error log is as below:

```
error: error opening 'obj/third_party/zlib/zlib/crc32.o.d': No such file or directory
```

full build log in here, https://github.com/Homebrew/homebrew-core/runs/1596608667
relates to https://github.com/Homebrew/homebrew-core/pull/66920

**Comment by bnoordhuis** [comment]
Can you try with v1.6.3?
