### ISSUE TITLE
inaccurate deno test coverage

### ISSUE THREAD

**Issue by claudio-felicioli** [denoland/deno#8917]
I'm getting consistently odd results from` deno test --coverage --unstable`:
- the coverage report line numbers are off by some small number (the offset error is not constant, even when reporting multiple pieces of code from the same source file)
- more importantly, the reported uncovered code lines seems to be the wrong one (reporting code text lines that have been covered, that in the source code are near to rows that are not covered, but unreported)

I started to check coverages at 1.5.4 with these issues, that are still present in 1.6.2

**Comment by caspervonb** [comment]
> the coverage report line numbers are off by some small number

Likely this is just from compilation?

Reports are for the raw JavaScript as v8 saw it.
We don't do source map looks ups (yet, working on that next).

> the reported uncovered code lines seems to be the wrong one (reporting code text lines that have been covered, that in the source code are near to rows that are not covered, but unreported)

So the content is all wrong and there are lines that definitively should be covered?

I've got one known bug here at-least from 1.6 caused by this break https://github.com/denoland/deno/blob/master/cli/tools/coverage.rs#L172, not sure if this is the same cause tho.

**Comment by kitsonk** [comment]
> We don't do source map looks ups (yet, working on that next).

Do we have an issue for this, if not we should for tracking purposes.

**Comment by caspervonb** [comment]
> Do we have an issue for this, if not we should for tracking purposes.

Talked about it being the plan a lot in dicsord but don't believe we have an open issue for it so raised one here 
https://github.com/denoland/deno/issues/8923

**Comment by claudio-felicioli** [comment]
thanks for opening the source map issue :)

**Comment by claudio-felicioli** [comment]
> > the coverage report line numbers are off by some small number
> 
> Likely this is just from compilation?
> 
> Reports are for the raw JavaScript as v8 saw it.
> We don't do source map looks ups (yet, working on that next).
Yes, seems source map

> 
> > the reported uncovered code lines seems to be the wrong one (reporting code text lines that have been covered, that in the source code are near to rows that are not covered, but unreported)
> 
> So the content is all wrong and there are lines that definitively should be covered?
the number of reported uncovered parts of the code is the expected one, just the numbers of the lines and the code displayed is wrong, therefore should be the source map only, at least for the cases that I have tested.
