### ISSUE TITLE
Incorrect bundle

### ISSUE THREAD

**Issue by subtle-byte** [denoland/deno#8930]
I tried to bundle my frontend with Preact and ran into the problem `n is undefined`. I left only the parts related to the error and got the example below.

main.js:
```javascript
import {render, h} from './preact.js';
const app = h();
render(app);
```

preact.js:
```javascript
let n, o;
function h() {
    ++n.a
}
function render() {
    o;
}
function S() { render(o); }
n = {
    a: 1
}, o = 1;
export { render, h }; 
```

Result of `deno bundle main.js`:
```javascript
let n, o;
function h() {
    ++n.a;
}
const app = h();
function render() {
    o;
}
n = {
    a: 1
}, o = 1;
render(app);
```

Expected: `const app = h();` is placed after `n = `.

Problem: before bundling - `n` is initialized when used in `++n.a`, after bundling - `n` is `undefined`.

I use Deno 1.6.2.

**Comment by bartlomieju** [comment]
Most likely already fixed in #8901, can you try canary build?

**Comment by kitsonk** [comment]
The output from master:

```js
let n, o;
function h() {
    ++n.a;
}
function render() {
    o;
}
n = {
    a: 1
}, o = 1;
const app = h();
render(app);
```

So yes, it looks like it is fixed in canary/next release.

**Comment by subtle-byte** [comment]
Yeah, canary build works for the example and for my frontend, thanks!
