### ISSUE TITLE
Don't require --unstable flag for CLI features

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#8934]
Currently `--unstable` flag is used to enable both unstable runtime API as well as enable new features in CLI. It means that if one wants to use only a single unstable feature of CLI one must opt into all unstable runtime APIs as well.

After discussion with @ry we propose to remove requirement for `--unstable` flag for CLI features and make the flag affect only runtime APIs.

This change would impact following subcommands:
- `deno compile`
- `deno lint`
- `deno test --no-run`
- `deno test --coverage`
- `--import-map` flag in various subcommands
- `--watch` flag in various subcommands

Ref https://github.com/denoland/deno/issues/8129

**Comment by MierenManz** [comment]
I think it would be a good idea to still keep the idea of unstable in there.
So we get rid of the unstable flag for the subcommands that were mentioned but we have a followup Y/N prompt which says something along these lines
"this feature is not fully stable yet, do you want to continue Y/N"

**Comment by kitsonk** [comment]
I doubt we would ever want to inflict that pain on users.  There is little benefit to that sort of UX IMO.  Especially if you are using Deno in a server environment, last thing you want is prompts blocking the execution of your code with no way to get past it.

**Comment by caspervonb** [comment]
I'm for splitting the concerns, unstable should be for just the unstable parts we have in the deno namespace.

For CLI features, marking it as `(unstable)` in --help and printing a big bold yellow warning when used should be sufficient warning in my opinion.

**Comment by MierenManz** [comment]
> For CLI features, marking it as `(unstable)` in --help and printing a big bold yellow warning when used should be sufficient warning in my opinion.

I think this is a good idea but users don't always look into the --help option

Recently I had this issue with `deno fmt` because I thought it was unstable thus I could just run the command and see the options for it, but it actually formatted everything.

Because the behaviour is changed I think it is a good idea to still indicate that the feature is unstable and that the user should be able to cancel it before it does the action (like not using --unstable does)

**Comment by MierenManz** [comment]
> I doubt we would ever want to inflict that pain on users. There is little benefit to that sort of UX IMO. Especially if you are using Deno in a server environment, last thing you want is prompts blocking the execution of your code with no way to get past it.

that is also true, but if we look at the listed command
 - `deno compile`
 - `deno lint`
 - `deno test --no-run`
 - `deno test --coverage`
 - `--import-map` flag in various subcommands
 - `--watch` flag in various subcommands
 these commands are mostly used in dev environments where the developer has easy access to the terminal

**Comment by grian32** [comment]
Perhaps add a new flag `--cliunstable` or something along those lines?

**Comment by nayeemrmn** [comment]
Closed in #10190.
