### ISSUE TITLE
More deno bundle errors: Improve swc testing strategy

### ISSUE THREAD

**Issue by jsejcksn** [denoland/deno#8943]
<details>
<summary>Here is the latest failing minimal reproduction case using Deno version <code>1.6.3</code>:</summary>

```
example % deno --version
deno 1.6.3 (release, x86_64-apple-darwin)
v8 8.8.294
typescript 4.1.3

example % cat deps.ts
export * as flags from 'https://deno.land/std@0.83.0/flags/mod.ts';

example % cat main.ts
import {flags} from './deps.ts';
console.log(flags.parse(Deno.args));

example % deno run main.ts
{ _: [] }

example % deno bundle main.ts main.bundle.js 
Bundle file:///Users/jesse/example/main.ts
Check file:///Users/jesse/example/main.ts
Emit "main.bundle.js" (9.25KB)

example % deno run main.bundle.js 
error: Uncaught ReferenceError: __boolean is not defined
        if (__boolean !== undefined) {
        ^
    at Object.parse (file:///Users/jesse/example/main.bundle.js:52:9)
    at file:///Users/jesse/example/main.bundle.js:257:17
```
</details>

I have been trying to bundle modules and run them since the release of Deno `1.5.x` (without success).

During that time, I have raised these related issues at each release: #8211, #8573, #8308, #8302, #8148

With every release, I am finding new errors that either prevent modules from being bundled, or prevent bundles from running when using modules from the Deno standard library. With each report, the specific error is being fixed—however, this pattern of individual report/fix is giving me a feeling that there is a larger underlying problem in the bundling process.

I would like to restate [a previous comment](https://github.com/denoland/deno/issues/8573#issue-754412882) again:

> I know it's too late to revert any changes introduced in Deno 1.5.x, but I haven't been able to bundle, install, and successfully run even one script since that minor version update back in October. ☹️ I wonder if there's a way to improve the testing strategy for swc before it's released in Deno builds. I'm not strong in Rust yet, but if there's a way that I can help, I'd like to know.

**Comment by kitsonk** [comment]
cc/ @kdy1

**Comment by RDambrosio016** [comment]
In my opinion there needs to be a tool similar to rust's crater which runs swc on a lot of real world code, maybe not all of it because that's millions of packages but a few thousand of the most used libraries will help

**Comment by kdy1** [comment]
Seems like a dce bug and I think I know the fix for it.


I'll create a something simillar to crater for the bundler.

I'm not sure how can I include it in the ci task though.

**Comment by RDambrosio016** [comment]
CI can just build and run a rust crate, it shouldnt be a problem, although i think it should only run on release.

**Comment by kdy1** [comment]
> it should only run on release 

This part is what I meant. But I found a solution. I'll automate crate publishing and I'll configure the CI to run heavy tests before it.

**Comment by RDambrosio016** [comment]
Would it be possible to make a generic crate for this to publish? then you make another crate which just gives it a function to run? Id like to use this testing strategy in my own project eventually and it would be great to have an existing runner for it 😄

**Comment by RDambrosio016** [comment]
> This part is what I meant. But I found a solution. I'll automate crate publishing and I'll configure the CI to run heavy tests before it.

Github actions is able to run a CI task if the commit is tagged automatically by using `if: startsWith(github.ref, 'refs/tags')`

**Comment by kdy1** [comment]
> Would it be possible to make a generic crate for this to publish to crates.io? then you make another crate which just gives it a function to run? Id like to use this testing strategy in my own project eventually and it would be great to have an existing runner for it 😄

It's absolutely possible.

> Github actions is able to run a CI task if the commit is tagged automatically by using if: startsWith(github.ref, 'refs/tags')

I initially considered something similar, but it means wrong code can come into master. I'll create a CI pass which fails by default without running tests but runs heavy tests when I add a comment with specific keyword.

I also considered using approval system of github, but approval is not possible because the creator of PR cannot approve it. 


I'm also considering using bors again, if it supports github actions well. As bors uses separate branch before merging, running heavy tests only before merging would be easy to implement.

**Comment by jsejcksn** [comment]
@kdy1 It's been a while since I've looked at this. Has there been a new testing strategy implemented for swc?

**Comment by kdy1** [comment]
No. Not yet.

**Comment by jsejcksn** [comment]
@kitsonk Does denoland use issues to track things like this?

If so, will you please reopen this issue?

If not, how are they tracked?

**Comment by kitsonk** [comment]
@jsejcksn it feels like swc's testing strategy is a good issue potential discussion for swc.  There is no need to re-open this issue in my opinion.

**Comment by jsejcksn** [comment]
> it feels like swc's testing strategy is a good issue potential discussion for swc

@kitsonk I agree, although the issue title might not be appropriately named. The issue is actually about testing swc as deno's bundler. In consideration of that, how will this be tracked within denoland?
