### ISSUE TITLE
v1.6.3 - does not add `deno` binary to `/usr/bin` under linux;

### ISSUE THREAD

**Issue by whatever-art** [denoland/deno#8946]
IT does not currently seem to have a similar command, && I don't know if IT would even be necessary, however, I used to be able to do `npm link` to resolve this issue in `node`;

Maybe even a list of `I used to be able to do command `X` in `node`` would be sweet;

I currently have to run `sudo ln ~/.cargo/bin/deno /usr/bin/deno`;

This would be something that I would add to y'all's build servers when you get a chance;

Happy Holidays;

**Comment by lucacasonato** [comment]
Could you clarify what your proposal is here?

**Comment by whatever-art** [comment]
@lucacasonato well, I was thinking, having not looked at the source code whatsoever that, adding something along the lines of `sudo ln ~/.cargo/bin/deno /usr/bin/deno` for every supported architecture, should do the trick?

**Comment by lucacasonato** [comment]
I don't understand what the issue is you are trying to fix.

**Comment by bnoordhuis** [comment]
It sounds like @whatever-art wants to install deno site-wide. But, seeing it's the cargo build, that's a cargo issue more than a deno issue.

@whatever-art Perhaps you were looking for `cargo install ---root /usr/local`? (`/usr/local` because I wouldn't recommend installing to `/usr`.)

**Comment by timonson** [comment]
I think, he just wants this command to be executed while installing: `sudo ln ~/.cargo/bin/deno /usr/bin/deno`. One reason why this might be *handy* is that we need to run deno as `sudo` when running a `https` server (or did this change in the last weeks?).

**Comment by crowlKats** [comment]
Closing as stale as author hasnt given further information after 2 years.
