### ISSUE TITLE
 ReferenceError: __boolean is not defined

### ISSUE THREAD

**Issue by ztamizzen** [denoland/deno#8952]
Whatever I compile (or bundle), that contains a boolean, gets this error.
For instance the "parse" function from "https://deno.land/std@0.82.0/flags/mod.ts".

**Comment by xaviripo** [comment]
I'm also getting this error from this exact same dependency. Also happens in version 0.83 of the std library, deno 1.6.3.

**Comment by kitsonk** [comment]
cc/ @kdy1

**Comment by bartlomieju** [comment]
Should be fixed in Should be fixed in https://github.com/denoland/deno/pull/9374
