### ISSUE TITLE
setInterval does not type check the callback parameter

### ISSUE THREAD

**Issue by 00ff0000red** [denoland/deno#8956]
Deno 1.6.3

Code:
```js
setInterval();
```

Stack trace:
```
Error: Uncaught TypeError: Cannot read property 'bind' of undefined
    at setTimer (deno:runtime/js/11_timers.js:466:25)
    at setInterval (deno:runtime/js/11_timers.js:515:12)
    at ...
```

After checking the source, it seems that the implementation does not type-check the parameter `cb` before calling `.bind` on it.

Yet, running that code on Chromium just returns an interval ID and never throws, so someone might want to check [the spec](https://html.spec.whatwg.org/multipage/timers-and-user-prompts.html) for reference.

Chrome does the same for numbers, null, booleans, etc, except strings, which it evaluates as code.

**Comment by 00ff0000red** [comment]
Ah, figured it out, if the argument is not a function, it is stringified via a call to `String`, regardless of whether or not it throws.
Updating runtime/js/timers right now.

**Comment by benjamingr** [comment]
> it is stringified via a call to String

😮  why? I don't think the timer spec requires implementing this legacy behaviour IIRC

**Comment by 00ff0000red** [comment]
> > it is stringified via a call to String
> 
> 😮 why? I don't think the timer spec requires implementing this legacy behaviour IIRC

Wait really? I almost submitted a PR *adding* the functionality.

If anyone can find it in the spec, I will avoid implementing it. I hate `eval`, so please give me a reason not to do it :)

https://html.spec.whatwg.org/multipage/timers-and-user-prompts.html
