### ISSUE TITLE
`deno compile` output fails with a SyntaxError on startup

### ISSUE THREAD

**Issue by DerNamenlose** [denoland/deno#8959]
As the title says: I have an API program which I want to turn into a single executable using `deno compile`. Everything works fine when using `deno run`, but using `deno compile` produces an executable which fails with:

```
error: Uncaught SyntaxError: Identifier 'i2' has already been declared
    at file://$deno$/bundle.js:7872:0
```

I've managed to narrow the error down to the following fragment:

```typescript
export { Database } from 'https://deno.land/x/denodb@v1.0.18/mod.ts';

console.log('Hello world.');
```
The `export` is the issue. Changing this to an `import` makes the binary work. (In the original program this export is in my `deps.ts`, so changing it to `import` is not an option.) It also seems to happen only with denodb, but I'm not sure about what exactly triggers this.

Any ideas on how to further debug this?

**Comment by lucacasonato** [comment]
What Deno version are you using?

**Comment by DerNamenlose** [comment]
It's always the obvious ones you forget to answer...
I'm at the current 1.6.3.

I've done a bit more digging through the output of `deno bundle` (which exhibits the same error) and found, that the ominous `i2` is a `function` declaration and there are a bunch of `var i2` in the file as well. I've changed basically all of them to `let` and get a different, probably unrelated error now.

The offending declaration is
```js
    var n4 = Object.prototype.hasOwnProperty, o3 = Object.prototype.toString, c3 = r$1, l2 = Object.prototype.propertyIsEnumerable, i2 = !l2.call({
```
in line 8333 in the output of `deno bundle`.
If I change this to `let n4....`, the `SyntaxError` goes away (and I get the other error somewhere else, but I'm not sure, whether those are related).

**Comment by bartlomieju** [comment]
This is a bug in bundler, CC @kdy1

**Comment by aaron-harvey** [comment]
I ran into this same issue yesterday as well.

I had two areas in the output bundle that needed to be fixed, so I ended up with the following script as a stopgap (osx).
```bash
#!/bin/sh

# There is currently (v1.6.3) and issue with deno compile
# See https://github.com/denoland/deno/issues/8959

file='index.bundled.js'
deno bundle index.ts "${file}"

# $1 <string> "linestoreplace\n"
# $2 <number> of times $1 is repeated
# $3 <string> replace $1 with this
replace () { perl -0777 -i -pe "s/$(perl -e "print '$1' x$2")/$3/gms" "${file}"; }

# Remove the entire offending section
replace "const readEnum = mod7.readEnum;\n" 10 "\n"
# Replace duplicate occurance
replace "const readEnumReq = mod7.readEnumReq;\n" 2 "const readEnumReq = mod7.readEnumReq;\n"

# deno run -A "${file}"
deno compile "${file}" --unstable && rm "${file}"

```
