### ISSUE TITLE
Combine ModuleId and ModuleSpecifier

### ISSUE THREAD

**Issue by ry** [denoland/deno#896]
https://github.com/denoland/deno/blob/3c080ca39abff28ed2cc6ac618558cced9c2e842/js/compiler.ts#L40-L49

@kitsonk - correct me if I'm wrong - but these seem to be the same thing. Whichever name is chosen, it should be consistent with what's used in `src/deno_dir.rs` (which I think is `module_specifer`)

If these are indeed distinct concepts the docs could use some improvement.

**Comment by kitsonk** [comment]
@ry I believe they are distinct concepts, or could be, depending on what happens with `ModuleId` in real life.  Originally we just had `ModuleId` and the comment indicated it was absolute (e.g. often resolves to the local cache).  For the `--deps` we want/need something that isn't the cached ID, therefore the `ModuleSpecifier` which will always be the "requested" ID which gets resolved, which is what is needed for `--deps`.  To be honest, I took the `ModuleId` at face value, that it would/could resolve to the local cache file but haven't actually introspected it.

**Comment by bartlomieju** [comment]
Both of them are now extensively used throughout `compiler.ts`, should we update the docs?

**Comment by ry** [comment]
let's close this - since it's very specific and aging anyway.
