### ISSUE TITLE
Trying to use HTTP Server and use within Webview

### ISSUE THREAD

**Issue by wwderw** [denoland/deno#8966]
I've got some programs that need to be used in conjunction with a simple webserver.

With node, I would use express and webview.

With these 2 in node, I would use(just a portion of my entry js code):

`const app = express()

app.get("/", (req, res) => {
    res.send("./index.html")
});

app.listen(8000)`

and for the url in the webview, I would have:

'url: "http://localhost:8000/index.html"'

and it would work flawlessly.

Apparently I am not finding the correct app.get() to send the file for webview to pick it up.  

Any thoughts on that?  Just needing something to bootstrap the html to send to webview to help satisfy CORs for some of my programs.

Thanks

**Comment by kitsonk** [comment]
This really should be asked in discussions, but it appears that GitHub has removed the ability to transfer issues to discussions.

**Comment by wwderw** [comment]
Ill close it here and open it in discussions
