### ISSUE TITLE
bundler: import * as XXX is not expected from esm.sh

### ISSUE THREAD

**Issue by ije** [denoland/deno#8970]
```js
// entry.js

import * as React from "https://esm.sh/react@17.0.1"
console.log(React) // ❌
```

the bundler can work fine with command `deno bundle entry.js output.js`, but `deno run output.js` will throw an error: `__default is not defined`.

replace `import * as React` to `import React` can fix it:

```js
import React from "https://esm.sh/react@17.0.1"
console.log(React) // ✅
```

**deno 1.6.3 (release, x86_64-apple-darwin)**

**Comment by kitsonk** [comment]
cc/ @kdy1
