### ISSUE TITLE
Websocket API dying on Deno but not on Chrome

### ISSUE THREAD

**Issue by elizeuangelo** [denoland/deno#8972]
There are two different streams im trying connecting my client using the standard [WebSocket API](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket) (I have no libraries imported).

In Deno the connections **always die after a couple of minutes**... in Chrome Browser they dont. Using the exact same code. I have not tested in a third web stream but I believe its no coincidence.

Testing code:

> let connection = new WebSocket('wss://stream.binance.com:9443/ws/btcbrl@trade');
> connection.onmessage = (message) => console.log(new Date(), 'msg received');
> setInterval(() => console.log('idle'), 30000); // So Deno dont closes?

In one manual they mention to kill any connections that dont answer pings for **3 minutes**, hypothesis one.

I have noticed if you dont 'setInterval' or wait for something deno closes the application after some time without provocation... maybe its not a ping issue but Deno itself doing something to the websocket (while the process is still running and the socket receiving msgs) believing its idle? hypothesis two

**Comment by glowingblue** [comment]
I think this is related to some of the comments in this issue https://github.com/denoland/deno/issues/7457#issuecomment-693631074

**Comment by lucacasonato** [comment]
> In one manual they mention to kill any connections that dont answer pings for 3 minutes, hypothesis one.

This should be fixed in the latest deno canary build (will be available in about 40 minutes). You can try it out with `deno upgrade --canary`.
