### ISSUE TITLE
Bundle error with overlapping type/variable names, such as when bundling Zod

### ISSUE THREAD

**Issue by jeremyBanks** [denoland/deno#8978]
I have been working on Deno compatibility for [the TypeScript data validation library "Zod"](https://github.com/colinhacks/zod/). The development branch is now working properly under `deno run`, but I am still encountering some errors in the output of `deno bundle`. I filed a reduction of the error I previously encountered at #8680 (now fixed 👍) but a new one popped up.

In the case of running `deno bundle` on `zod/deno/lib/mod.ts` in Zod's `v3` branch (410dd7b479), the result is the attached [`bundle.js`](https://github.com/denoland/deno/files/5762484/bundle.js.txt). Attempting to `deno run bundle.js` produces the following error:

```
error: Uncaught SyntaxError: Export 'anyType' is not defined in module
    at <anonymous> (file:///mnt/c/Users/_/src/github.com/jeremyBanks/zod/deno/bundle.js:2340:866)
```

If we look at that line, it appears to be trying to `export { anyType as any }`, but the corresponding definition in the module seems to have been renamed to `const anyType1 = ZodAny.create;`, so the export declaration produces an error.

I'm not sure if this is the same root issue or not, but here's an attempted reduction with obnoxiously-weird type exports that also confuses the bundler:

### dep.ts
```ts
export const f = () => "hello world";
type f = number;
export const any = f;
```

### test.ts
```ts
import { any } from "./dep.ts";

export { any };
export type { any as t };
```

### actual bundle.js output
```js
export { any as any };
```

### deno run bundle.js output
```
error: Uncaught SyntaxError: Export 'any' is not defined in module
export { any as any };
         ~~~~~~~~~~
    at <anonymous> (file:///mnt/c/Users/_/src/github.com/jeremyBanks/zod/deno/test-bundle.js:1:10)
```

### expected bundle.js output
Something like this:
```
export const any = () => "hello world";
```

**Comment by kitsonk** [comment]
@jeremyBanks could you confirm what version of Deno you are using?

**Comment by jeremyBanks** [comment]
@kitsonk Oops, sorry, forgot to include that. 🤦 I was using the latest stable, `deno 1.6.3`. I have just tested again with `deno nightly 2021.01.03` from `curl -fsSL https://denonightly.now.sh/sh | sh` with the same results.

**Comment by kitsonk** [comment]
cc/ @kdy1

**Comment by ry** [comment]
@jeremyBanks Just FYI we now provide official "nightly" builds (actually updated on every commit, not every day) https://deno.land/manual@v1.6.3/contributing/release_schedule#canary-channel
