### ISSUE TITLE
Reland #8894

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#8979]
In #8977 we reverted #8894 because it introduced openssl to our dependency tree (even if it was only for tests). It also added a lot of `hello` messages to the output logs in testing. The openssl issue can be solved by using the `reqwest` that is exported from `deno_fetch`.

@lperlaki We would appreciate if this PR could be re-landed with fixes. Do you have time to address these issues?

**Comment by lperlaki** [comment]
@lucacasonato yes I will rework the PR.
