### ISSUE TITLE
_parseAddrFromStr doesn't accept string number

### ISSUE THREAD

**Issue by YSonobe-git** [denoland/deno#8980]
## env

- deno 1.6.0
- v8 8.8.278.2
- typescript 4.1.2

# 
Created index.ts file inside root directory and wrote code below.
Note: ` const s = serve({ port:8000 }); ` works fine

**index.ts**
```
import { serve } from "https://deno.land/std/http/server.ts";
const s = serve("8000");
console.log("http://localhost:8000/");
for await (const req of s) {
  req.respond({ body: "Hello World\n" });
}
```
Ran ` deno run --allow-net ./index.ts `
But gave me a following error

```
error: Uncaught AddrNotAvailable: Can't assign requested address (os error 49)
    at processResponse (deno:core/core.js:223:11)
    at Object.jsonOpSync (deno:core/core.js:246:12)
    at opListen (deno:cli/rt/30_net.js:32:17)
    at Object.listen (deno:cli/rt/30_net.js:207:17)
    at serve (server.ts:315:25)
    at index.ts:2:11
```

But if changed inside ` _parseAddrFromStr ` function like below, works fine.
**server.ts**
```
const host = addr.startsWith(":") ? `0.0.0.0${addr}` : `localhost:${addr}`;
```

## expected output in console
` http://localhost:8000/ `

**Comment by satyarohith** [comment]
The error usually means that the port (8000) is not available. Check if you have something running at http://localhost:8000 already or use a different port.

**Comment by YSonobe-git** [comment]
I can see Hello World on browser if I do ` const s = serve({ port:8000 }); `

**Comment by satyarohith** [comment]
Right. When you're passing a string to `serve()`, you need to prepend `:` if you're just passing the port number (e.g. `serve(":8000")`) or you need to pass the hostname + port (e.g. `serve("localhost:8000")`).

**Comment by YSonobe-git** [comment]
Thank you for your comment @satyarohith 

As you mentioned that passing the ` localhost:8000 ` to ` serve() `,
I think we can do simplify an interface.

As I wrote above,
if we do like inside ` _parseAddrFromStr() ` ,
` const host = addr.startsWith(":") ? `0.0.0.0${addr}` : `localhost:${addr}`; `

the interface is going to be more simple.
e.g) ` serve(":8000") ` or ` serve("8000") `
