### ISSUE TITLE
Assertion error in asysn await array.foreach

### ISSUE THREAD

**Issue by zsattari** [denoland/deno#8983]
```
 listWareClasses.foreach(async(x)=>{
      const w=await wareClasses.updateOne({_id:x._id},wareClass);
      console.log(w);
    });
```
In this code, when it reaches the await line, it gives an assertion error

**How Do I Do?**

**Comment by caspervonb** [comment]
Third party but what is the error exactly?

**Comment by kitsonk** [comment]
This is a general question about JavaScript and a third-party library.  The issue tracker here is not the appropriate place to ask such questions.

You could use the discussions, but what you are asking isn't specific to Deno, so StackOverflow is a better place to ask such questions.
