### ISSUE TITLE
[bundle] DenoStdInternalError is not defined when compiling

### ISSUE THREAD

**Issue by FrageDev** [denoland/deno#8985]
Hi, from what I read the issue with OAK is supposed to be fixed. I download the latest version or Deno (1.6.3) and I tried to compile my app again.

Now the "There is no middleware to process requests" is gone, seems to be fixed. But now I've got this error.

"
error: ReferenceError: DenoStdInternalError is not defined
    at assert2 (file://$deno$/bundle.js:7476:9)
    at getLogger (file://$deno$/bundle.js:7601:9)
    at file://$deno$/bundle.js:7614:16
"

App is working fine from deno console. the getLogger function is a function from https://deno.land/std@0.83.0/log

```
function getLogger(name3) {
    if (!name3) {
        const d = state1.loggers.get("default");
        assert2(d != null, `"default" logger must be set for getting logger without name`);
        return d;
    }
    const result = state1.loggers.get(name3);
    if (!result) {
        const logger = new Logger(name3, "NOTSET", {
            handlers: []
        });
        state1.loggers.set(name3, logger);
        return logger;
    }
    return result;
}
const logger = getLogger();
```

**Comment by FrageDev** [comment]
I removed the log function from the app and the compiler seems to have a lot of issue.

I bundle my app.ts to see what deno is compiling and I can see a lot of "parameter implicitly has any type" which is not a real problem.

Also I found a lot of duplicate variable, here an example : 
```
const router = new Router();
const home1 = home;
const hw1 = hw;
const process1 = process;
const status1 = status;
const inactivity1 = inactivity;
const connection1 = connection;
const password1 = password;
const getPassword1 = getPassword;
const mod2 = function() {
    return {
        home: home,
        hw: hw,
        process: process,
        status: status,
        inactivity: inactivity,
        connection: connection,
        password: password,
        getPassword: getPassword
    };
}();
const inactivity1 = mod2.inactivity;
const app2 = new Application();
const home1 = mod2.home;
const hw1 = mod2.hw;
const process1 = mod2.process;
const status1 = mod2.status;
const connection1 = mod2.connection;
const getPassword1 = mod2.getPassword;
```

Here the app I'm developing if you want to test it (ssl key / crt not included) : https://we.tl/t-n1Jxro7yQm

**Comment by kitsonk** [comment]
cc/ @kdy1

**Comment by FrageDev** [comment]
If I remove the "throw new DenoStdInternalError(msg);" which is causing the error by a simple "throw msg;" I can catch this error from the Deno compiler : "error: Uncaught "default" logger must be set for getting logger without name"

This error is caused by Deno or the SWC compiler ?

I'm using the std log lib from Deno, maybe this lib got an an issue with the compiler ?

When I use the deno bundle --unstable app.ts, I should get a JS or a TS output file ?

Sorry I'm not a dev, I don't understand everything :/
