### ISSUE TITLE
deno bundler issue with using 'throws'

### ISSUE THREAD

**Issue by jveres** [denoland/deno#8988]
Deno bundler replaces `throws` with `__throws` and breaks bundled code.
This issue breaks all bundled runs using e.g. `MuxAsyncIterator` from the standard libs.
Affected version: `1.6.3`

Example `test.ts`:
```typescript
class T {
  private throws : number[] = [];
  m(): void {
    console.log(this.throws.length);
  }
}

new T().m();
```
```sh
deno run test.ts
0
deno bundle test.ts test.bundle.js
deno run test.bundle.js
error: Uncaught TypeError: Cannot read property 'length' of undefined
        console.log(this.throws.length);
                                ^
...
cat test.bundle.js
class T {
    __throws = []; // this is the cause
    m() {
        console.log(this.throws.length);
    }
}
new T().m();
```

**Comment by jveres** [comment]
cc @kdy1

**Comment by jveres** [comment]
fixed in `deno 1.6.3+eaabef3`

**Comment by jonahbron** [comment]
Not sure what Deno's release cadence is... when will this go out?  I tried `duno upgrade` with `1.6.3+eaabef3`, but that didn't work.  Guessing it only works with binary releases.

**Comment by jveres** [comment]
@jonahbron this is the canary release I tested with: `deno upgrade --canary --version eaabef30d08b47c9a90c12ec736c7d53f42a1208`
