### ISSUE TITLE
deno 1.6.3 bundler doesn't properly handle re-exports of upstream lib

### ISSUE THREAD

**Issue by aricart** [denoland/deno#8989]
At some point I recall some 'best practice' of isolating external imports into a single file, re-exporting the imported symbols, and then referencing them from the reexported file, ie:

externaldep.ts:
```
export * from "https://something";
```
local code would then:
```
import {foo} from "externaldep.ts"
```

This pattern is quite useful as it provides a very specific place where an external dependency is loaded and referenced (ie one file to change).

Alas, this pattern doesn't work with `deno bundle` - see  https://github.com/denoland/deno/issues/8725 - the issue being that for files referencing the full import URL, the symbols are remapped properly. But on files where the references are from the re-export, no renames happen thus, and the symbols that should be found upstream are not.

As you can tell - I have found a workaround, but it means referencing the remote URL from all files (wondering if the issue is local resolution mixed with remote).

**Comment by kitsonk** [comment]
@aricart can you provide a specific re-production, as I believe we have tests (as well as swc) where this is done, but might fail under certain conditions.

**Comment by aricart** [comment]
@kitsonk the description of #8725 has steps, the branch is still there so it should work for you to just `deno bundle https://raw.githubusercontent.com/nats-io/nats.ws/deno-1.6.0/src/mod.ts` - the issue has a flow through one of the symbols.

**Comment by aricart** [comment]
Alternatively you can close this issue and reopen #8725.
