### ISSUE TITLE
Benchmark wanted: listener.accept() latency

### ISSUE THREAD

**Issue by ry** [denoland/deno#899]
The setup should be a tcp server which accepts and closes connections as fast as possible. The time between each accept is kept and a large numerical set is formed on which we calculate statistics. Should plot several lines: median, 90% percentile, 99% percentile over time

Not sure how to do the client side. Maybe use deno too.

**Comment by kevinkassimo** [comment]
Was working on this, but encountered the problem mentioned in #888 (event loop `ntasks` unexpectedly decrement and exit too early...) After applying #911 , things starts to work.
I feel debugging #888 would take longer time, dunno if we should temporarily land #911 to get async tests working first

**Comment by alexhultman** [comment]
#890 is similar. Solving both is simple and can lie in one single script that'll plot you everything about TCP perf. you want to know. Server client in the same script is a good idea and will measure both parts.

**Comment by ry** [comment]
Update Feb 24, 2020: This is still something I'd like to have, but not a high priority. In terms of benchmarks we're still trying to get deno_tcp to be on par with node_tcp.
