### ISSUE TITLE
lsp: JSX cannot be used

### ISSUE THREAD

**Issue by FallingSnow** [denoland/deno#8993]
How can I pass the `--jsx` flag to the deno lsp?

**Describe the bug**

While using the Canary extension, I get the following errors all over my project.

```ts
JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists. deno-ts(7026)
Cannot use JSX unless the '--jsx' flag is provided. deno-ts(17004)
```
**Versions**

vscode: 1.52.1
deno: 1.6.3
extension: 0.0.6

**Comment by kitsonk** [comment]
It should just work, it is a bug with the lsp that we need to fix.

**Comment by FallingSnow** [comment]
Is there a work around I can use in the mean time?

I tried adding a tsconfig.json which from what I've read should fix it. But it seems like deno_vscode doesn't pick up on it.
```json
{
    "compilerOptions": {
        "jsx": "react-jsx",
    }
}
```

Or maybe no changes in a tsconfig.json can help, it must be done in the lsp?

**Comment by lucacasonato** [comment]
If you use the canary channel of Deno, there should be support for `tsconfig` in the recent builds. You can specify the tsconfig path via the `deno.config` preference.

**Comment by FallingSnow** [comment]
I set `"deno.config": "./tsconfig.json"` on `.vscode/settings.json` but still see the same errors. I tired excluding everything to see if the tsconfig was being picked up but the errors still come through.

`settings.json`
```
{
    "files.eol": "\n",
    "files.trimTrailingWhitespace": true,
    "files.exclude": {
        "**/.git": true,
        "**/.DS_Store": true,
        "**/Thumbs.db": true,
        "**/.aleph": true
    },
    "deno.enable": true,
    "deno.config": "./tsconfig.json",
    "deno.unstable": false,
    "deno.import_map": "./import_map.json"
}
```

`tsconfig.json`
```
{
    "exclude": [
        "**/*"
    ],
    "compilerOptions": {
        "jsx": "react-jsx"
    }
}
```


Also are you referring to Canary for the deno or vscode_deno? (I'm using `denoland.vscode-deno-canary 0.0.6`)

**Comment by LRNZ09** [comment]
I'm having this error with the Canary version of the vscode extension, no problem with the stable one.

**Comment by reggi** [comment]
Just got this out of nowhere after working with fresh for about 2 hours. 👀

**Comment by reggi** [comment]
I think it's because I had some malformed TSX, if you're seeing this just piece it back together and check for bugs. Weird message tho
