### ISSUE TITLE
Parsing errors cause --watch to stop

### ISSUE THREAD

**Issue by 00ff0000red** [denoland/deno#9008]
When running a TS project with `--watch`, whenever I get a syntax error that is not caused by TSC (I think these are SWC), the file watcher never restarts on the next file change.

Example error:
```
error: Unexpected token `]`. Expected this, import, async, function, [ for array literal, { for object literal, @ for decorator, function, class, null, true, false, number, bigint, string, regexp, ` for template literal, (, or an identifier at {my project file here}
Watcher Process finished! Restarting on file change...
```

Is that an SWC error?
I wanted to say that this could be related to SWC issue https://github.com/swc-project/swc/pull/1274, but the watcher still was able to log to stdout that it was finished, so maybe it's Deno?

(*Currently, I just restart Deno when it happens, but it beats the purpose of the file watcher in the first place*)

___

If it helps, I'm using Deno 1.6.3 on an x86_64 GNU/Linux 19-Ubuntu.
Other flags enabled:
--unstable
--lock='...'
--lock-write
--allow-all
--v8-flags='...'

___

Update:
Added an import-map and whenever it was edited, if it caused a syntax error, then the same effect as observed above ^ occurred again.

**Comment by bartlomieju** [comment]
CC @magurotuna

**Comment by 00ff0000red** [comment]
Not sure if it should be closed or not, but I can't replicate this anymore, seemed to have disappeared up overnight...

**Comment by bartlomieju** [comment]
@00ff0000red as far as I remember @magurotuna explicitly handled the situation where there's an error during startup with `--watch`. Are you running on latest Deno?

**Comment by 00ff0000red** [comment]
1.6.3, unless there's anything newer.
What are we considering "startup" here? Startup of Deno with --watch, or startup of the next iteration of the watcher?
But when it was happening, it wasn't on startup exactly, it was occurring well after having --watch working, but once a syntax error was encountered, it halted.

**Comment by magurotuna** [comment]
@00ff0000red 
Could you show me the source code you were trying to run?

**Comment by 00ff0000red** [comment]
I just figured it out, so it's not that --watch breaks, it's that once it encounters an error in my imported file it ignored that specific file.

If I go and edit my "main" file (i.e. the importee), then --watch resumes like normal, until encountering another error.
If it encounters an error in my main file, it works fine and continues regardless of errors on the next iteration.

@magurotuna My source is roughly 600+ lines, I'll try to reproduce with less first ;)

**Comment by 00ff0000red** [comment]
@magurotuna

Yeah, that seemed to do the trick:
main.ts:
```ts
import * as X from "./lib.ts";

console.log(X);
```

lib.ts:
```ts
export const a = 0;
```

Run with:
* --unstable
* --no-check
* --watch

Steps:
Run (should be fine)
Cause a syntax error (e.g. place a random `]`)
Fix the syntax error
Add another export (e.g. `export const b = 1;`)
Observe that the file watcher hasn't rerun the script

**Comment by magurotuna** [comment]
@00ff0000red 
Thanks for the minimal reproducible example! I am able to reproduce it on my environment.
I'll investigate it.
