### ISSUE TITLE
Syscall usage spiked after timer refactor

### ISSUE THREAD

**Issue by ry** [denoland/deno#901]
The benchmarks page is working! https://denoland.github.io/deno/

<img width="848" alt="screen shot 2018-10-04 at 1 10 31 am" src="https://user-images.githubusercontent.com/80/46454051-70f36a80-c772-11e8-9324-e0801ff5b6ba.png">

The commit it points to is https://github.com/denoland/deno/commit/6cfc6b5d51fccdb1e5ae6ea0940dd87aadda4a82 which is the last of PR #885

Any ideas what the extra syscalls are?

**Comment by ry** [comment]
Relaying a comment from @piscisaureus
> Probably much more clock_gettime calls. [If we could use recv_deadline instead of recv_timeout that would save a bunch](https://github.com/denoland/deno/blob/6a649012bcd780f4b3adfa55647772fce0012fde/src/isolate.rs#L175-L181)

What we really need to be doing is epoll on the main thread. It's ridiculous that we're dedicating a thread to it already. This would kill two birds with one stone.

**Comment by alexhultman** [comment]
I don't know how the history unfolds but I saw a massive amount of futex syscalls in a way I've never seen a server do yesterday when benchmarking. You told me you weren't going to do actual IPC between Rust and V8 but this looks an awful lot like actual IPC between actual processes.

**Comment by bartlomieju** [comment]
Current values are now half the original. 
<img width="766" alt="zrzut ekranu 2019-02-12 o 19 13 08" src="https://user-images.githubusercontent.com/13602871/52658002-42dd1e80-2efa-11e9-886b-ca2083759799e.png">

CC @ry
