### ISSUE TITLE
more consistent way to handle transpiling, linting standards and errors/warnings

### ISSUE THREAD

**Issue by starkpsmichael** [denoland/deno#9014]
# Problem

```ts
const _ = (data) => {} // Parameter 'data' implicitly has an 'any' type.deno-ts(7006)
const _ = (data: any) => {} // `any` type is not alloweddeno-lint(no-explicit-any)
const _ = (data: unknown) => {} // Deno.emit messageText: "Object is of type 'unknown'.",
```

Using `// deno-lint-ignore no-explicit-any` for the second case:
This is inconsistent - [deno-lint recommends to using unknown type](https://lint.deno.land/#no-explicit-any).

Ok, now - what should be done, everything is wrong. ;)
This should really be more consistent.

The above is only an example, what iam aiming for is a consistent way to handle the standards/recommendations that are coming from deno(-ts, -lint), there should be one way, not 2, 3 or 4.

Using: deno canary and deno-vscode-canary

**Comment by nayeemrmn** [comment]
The first two messages seem fine, other than that maybe the linter error for the second one could suggest trying `unknown`. I'm not sure what the third message is, is `Deno.emit()` giving this error? I don't see it.

**Comment by kitsonk** [comment]
Linting is always optional and advisory.  There are hints to suppress linting errors if you have a better context.  Linting recommendations are not a "cure all" and cannot cover every case.  In some cases, `unknown` might make sense, in others, using a specific type is better, but of course it depends on what you are actually doing with the code.  None of the examples provided are "real world" examples, so it is hard to suggest what the right solution might be.

**Comment by starkpsmichael** [comment]
Following the discussion on discord, my wish/best case would be a deno binary, wich uses deno-ts and integrates deno-lint, they use the same configurations/configs/suggestions.
Also for these who would like to opt out of linting, there would be an option.
Like useStrict in typescript (yeah i know, linting is not strict at all, but hey)

This would be for me the best enduser exp.
Rules and recommendations from deno that are all the same.

Just a thought, try to install deno and deno-vscode, and program a frontend and backend project.
There is so much confusion which rules/suggestions you should follow.
Plus the problem that the one supports thinks like typescript directives and the other not (known issue btw).

**Comment by lucacasonato** [comment]
Closing this, as I can not reproduce it anymore. Also `Deno.emit` is no more.
