### ISSUE TITLE
Idea: Deno/STD/expandGlob with watchFS

### ISSUE THREAD

**Issue by michailVestnik** [denoland/deno#9038]
Hi!
If we run:

```
for await (const page of expandGlob('./folder/*.html')) {
	console.log(page.name)
	myFunction(page.name)
}
```

we see index.html, test.html, more_test.html etc... But if add a new .html file in 'folder' this code will not see it. 
Is it possible to combine dynamic watchFS with expandGlob?
For example, we will add a new file to a folder and the 'expandGlob' will automatically restart, like these:

```
for await (const page of expandGlob('./folder/*.html', watch)) {
	console.log(page.name)
	myFunction(page.name)
}
```

Вы самые лучшие, спасибо!

**Comment by lucacasonato** [comment]
No. `Deno.watchFs` needs to know beforehand exactly what files to watch. If you are not sure, you can watch the entire directory and filter the output of that according to your glob.

**Comment by michailVestnik** [comment]
Thanks for the answer! I close issue
