### ISSUE TITLE
Deno.bundle() generates (calls) function name that is not defined

### ISSUE THREAD

**Issue by greenya** [denoland/deno#9055]
Hello!

I have a small module, which has a function named "int". The function is exported and is used in other modules. Deno runs code as expected. But for some reason, Deno.bundle() doesn't generate correct Javascript. In browser I'm getting `Uncaught ReferenceError: __int is not defined`.

I dont know when this issue started to happen (what exact Deno version, but i can say that in 1.5.6 it was ok, and now, in 1.6.3, it is not ok). So the issue is:
- [OK] **int** -- is a name of the function
- [NOT OK] **__int** is a name that is used to call the function in this module (for some reason it adds double underscores, and this call is not valid ofcause -- no function with this name)
- [OK] **__default1.int** -- is a name how it is called from other modules (this is correct reference, it has correct definition `const __default1 = { int, ... };`)

I have attached image that shows the comparison of what is generated.
![image](https://user-images.githubusercontent.com/1086543/104042053-a05f7000-51e2-11eb-83a7-b5833b60f4b4.png)

P.S.: Thank you for your support and work on such awesome project <3

**Comment by greenya** [comment]
One more place (detail).

This part is generated incorrectly too. Here this is no call to any int() fucntion, its a property from the object above. Instead of **__int** it should be **int1** (in older version generated correctly).
![image](https://user-images.githubusercontent.com/1086543/104044043-6479da00-51e5-11eb-9797-3fc56991b00c.png)

**Comment by lucacasonato** [comment]
cc @kdy1

**Comment by greenya** [comment]
Hello!
This issue not fixed. Checking in 1.7.0, it is fixed partially, but property destructure is broken.
Here is a small example that reproduce the bug; maybe add this as a test case for future, so its known if it passes it.

```ts
const x = {
    n: 123,
    t: 'text',
    int: '==INT=='
}

const { n, t, int } = x

console.log(n, t, int)

// "deno run x.ts" output (correct):
// 123 text ==INT==

// "deno bundle x.ts" output (incorrect):
// const x = {
//     n: 123,
//     t: 'text',
//     int: '==INT=='
// };
// const { n , t , __int  } = x;
// console.log(n, t, __int);

// __int is undefined :(
```

Thank you for your hard work <3

**Comment by bartlomieju** [comment]
Should be fixed in https://github.com/denoland/deno/pull/9374
