### ISSUE TITLE
Error.prepareStackTrace is exposed to user code

### ISSUE THREAD

**Issue by 00ff0000red** [denoland/deno#9062]
Title should describe this well enough.

Input:
```js
console.log("prepareStackTrace" in Error);
```

Expected output:
```js
false
```

Actual output:
```js
true
```

I don't think any browsers do this.

Exposed here:
https://github.com/denoland/deno/blob/f3ead9c6a7184d2b592f018795f73d34399a9c83/runtime/js/99_main.js#L158-L167

**Comment by nayeemrmn** [comment]
This is intentional, `Error.prepareStackTrace()` is a V8 concept supported in Chrome, but it doesn't have a default value. It does for us because we use it for internal purposes. There's a TODO to expose it _properly_ for users in the way Chrome does: https://github.com/denoland/deno/blob/f3ead9c6a7184d2b592f018795f73d34399a9c83/cli/dts/lib.deno.shared_globals.d.ts#L884-L885.

**Comment by 00ff0000red** [comment]
> This is intentional, `Error.prepareStackTrace()` is a [V8 concept](https://v8.dev/docs/stack-trace-api#customizing-stack-traces)...

Exactly, it's a nonstandard V8 "feature."
Imho, to use it at all breaks web compatibility to a certain degree.

**Comment by nayeemrmn** [comment]
This is discussed in https://github.com/denoland/deno/pull/5254 about `Error.captureStackTrace`. The gist of it is that Deno is tightly coupled to V8, and if V8 exposes something like this with documentation that suggests it's for user code (not host environments) to take advantage of, we would just pass it on. It's not clear how feasible it is to hide it, and we're only making the web compatibility trade-offs which any V8-based web browser is.

**Comment by 00ff0000red** [comment]
Oh, there was a PR explicitly exposing it, didn't find that.

In that case, is there a plan to allow users to take advantage of it?
Where is it used internally?

~~Could I try setting up a hacky workaround in the meanwhile?~~

**Comment by nayeemrmn** [comment]
(Its friend `Error.captureStackTrace` was explicitly exposed, `Error.prepareStackTrace` is the one that's used internally for now.) In the future I think we can replace our internal use of `Error.prepareStackTrace = ourCallback` with `Isolate::set_prepare_stack_trace_callback(our_callback)` in Rust. This is mentioned as point 2 in https://github.com/denoland/deno/issues/7644.

**Comment by 00ff0000red** [comment]
Closing, as this is known and intentional.
