### ISSUE TITLE
JSDoc standards

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#910]
Now that we are exposing a lot of APIs, it would be good to agree the standards/_pro forma_ of documentation.

In particular, what a good JSDoc block would contain, like a description, examples, etc.  Also standards around if we doc each parameter, or generally admit them.

A decent example is the following which uses markdown indents for example code, which gets parsed by consumers of the TypeScript language services as full syntax highlighting:

https://github.com/denoland/deno/blob/ce9148943c4ffa43252e3692014489ebcff3d51e/js/mkdir.ts#L6-L11

Which looks like this (in VSCode):

<img width="459" alt="main_ts_ _deno_example" src="https://user-images.githubusercontent.com/1282577/46518845-a0f95580-c8b9-11e8-9a7a-d28398fa453a.png">

An example which is "rich" but could be dramatically improved via better use of markdown:

https://github.com/denoland/deno/blob/ce9148943c4ffa43252e3692014489ebcff3d51e/js/net.ts#L96-L110

Which looks like this in VSCode:

<img width="501" alt="main_ts_ _deno_example" src="https://user-images.githubusercontent.com/1282577/46518907-d1d98a80-c8b9-11e8-8e38-17dbd7eeac3d.png">

And this would be much better:

```ts
/**
  * Listen announces on the local network address.
 *
 * The network must be `tcp`, `tcp4`, `tcp6`, `unix` or `unixpacket`.
 *
 * For TCP networks, if the host in the address parameter is empty or a literal
 * unspecified IP address, Listen listens on all available unicast and anycast
 * IP addresses of the local system. To only use IPv4, use network `tcp4`. The
 * address can use a host name, but this is not recommended, because it will
 * create a listener for at most one of the host's IP addresses. If the port in
 * the address parameter is empty or `0`, as in `127.0.0.1:` or `[::1]:0`, a
 * port number is automatically chosen. The `Addr` method of `Listener` can be used
 * to discover the chosen port.
 *
 * See `dial()` for a description of the network and address parameters.
 */
```

Because this would look good in editors which use TypeScript language services, it would also form the basis of generated documentation as well.

**Comment by ry** [comment]
Thanks for raising this issue. A few thoughts:
* I've never liked the syntax for jsdoc - it's very hard to type. I would much rather if any '//' comments before a function were interpreted as docs. However! I realize TS doesn't parse this - and it's beyond the scope of this project to address this issue.  Therefore we should just use what TS can parse.
* Code and documentation ought to first and foremost be readable in a dumb editor like notepad. Therefore:
  * I want to forbid the use of HTML tags in jsdoc. I'm not sure if this is standard or not - but I've seen it before and it's difficult to read in code.
  * Multiline example code in docs should not be surrounded by triple ticks, nor by tags. It should only be indented from the rest of the doc text. The leading `*` is in column 2 - then a space in column 3 - then normal doc text would start in column 4. Therefore example code ought to begin in column 6.
  * If a JSDOC can be made into a single line it should be. [Here is an example of this that should be corrected.](https://github.com/denoland/deno/blob/6a649012bcd780f4b3adfa55647772fce0012fde/js/compiler.ts#L50-L53)
  * More generally vertical space should be minimized. Example code should almost always not have blank lines.
   * Example code should not have comments. It is already inside a comment. If it needs further comments is not a good example.
* Is there someway we can get the linter to enforce any of these rules? Probably not all of them. Therefore we should start a style guide of some sort outlining this.  Maybe `/.github/PULL_REQUEST_TEMPLATE.md` is a good place for this.
