### ISSUE TITLE
Can not import module due to error: An unsupported media type was attempted to be imported as a module

### ISSUE THREAD

**Issue by xReveres** [denoland/deno#9100]
Hi. I'm trying to import module `sanitize-html` from:
https://www.skypack.dev/view/sanitize-html
But deno throws error:
```
error: An unsupported media type was attempted to be imported as a module.
  Specifier: https://cdn.skypack.dev/-/entities@v2.1.0-S0DhGXdQlvcmp698ExI8/dist=es2020,mode=raw/lib/maps/xml.json
  MediaType: Json
```
Steps to reproduce:

1. Create file test.ts
2. Import module:
```
import sanitizeHtml from 'https://cdn.skypack.dev/sanitize-html';
```
3. Run

Deno version:
```
deno 1.6.3 (release, x86_64-unknown-linux-gnu)
v8 8.8.294
typescript 4.1.3
```

**Comment by Soremwar** [comment]
view-sanitize doesn't seem to be usable from skypack, however there is a esm.sh transform available that seems to be working correctly https://esm.sh/sanitize-html@2.3.0

**Comment by xReveres** [comment]
@Soremwar thanks, it works fine with one change.
When I try import it like:
`import * as test from 'https://esm.sh/sanitize-html@2.3.0'`
Deno throws many errors like:
```
TS2580 [ERROR]: Cannot find name 'Buffer'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.
        end(buffer?: Buffer): string;
                     ~~~~~~
    at https://cdn.esm.sh/v14/@types/node@14.14.20/string_decoder.d.ts:5:22
etc...
```
At all there is 105 errors.
On main ESM.sh page there is Deno compatibility, also there is query 'no-check' to disable the `types`.
Finally I can sanitize html input.

Solution:
`import * as test from 'https://esm.sh/sanitize-html@2.3.0?no-check'`

Anyway really thanks for help.
