### ISSUE TITLE
Fetch SNI of TLS handshake

### ISSUE THREAD

**Issue by imjamesb** [denoland/deno#9109]
# Feature Request

A very useful feature for TCP listeners using the TLS protocol would be to fetch the SNI of the TLS handshake (client hello) after the handshake is done. For instance, adding a `sni?: string;` property to the `Deno.Conn` interface.

**Comment by matt1** [comment]
It would also be useful to be able to specify the SNI (and ALPN) for creating a TLS connection with `ConnectTls()` too.

**Comment by ihack2712** [comment]
> It would also be useful to be able to specify the SNI (and ALPN) for creating a TLS connection with `ConnectTls()` too.

When connecting with TLS the SNI will be added automatically based on the hostname property.

**Comment by ignoramous** [comment]
Without SNI, TLS middleware cannot be written in Deno, which is a shame since its tokio/tower based IO is pretty darn fast (especially, after the recent Deno<->V8 serde changes).

**Comment by bartlomieju** [comment]
@lucacasonato is this something we could address?

**Comment by timonson** [comment]
Is SNI on the roadmap?

**Comment by Codevendor** [comment]
Just wondering if SNI support for deno webserver is in the works. Without it, how would you handle virtual domains?

**Comment by imjamesb** [comment]
> Just wondering if SNI support for deno webserver is in the works. Without it, how would you handle virtual domains?

request.headers.host

**Comment by Codevendor** [comment]
> [imjamesb](/imjamesb)

How do you serve up the ssl certificate for each different host over same ip?

**Comment by imjamesb** [comment]
@Codevendor I'm not sure Deno has that yet. I've stopped followinging Deno's development. Anyways, for non SSL you can use `request.headers.host`, but with SSL you will need to wait until Deno lets you serve certificates based on hostname.

**Comment by danopia** [comment]
I'm implementing a TLS proxy and want to passthru specific connections&mdash;without decryption&mdash;based on the requested SNI. (Similar to [https://github.com/dlundquist/sniproxy](sniproxy).)

Unfortunately, `request.headers.host` is an HTTP concept, and so it's not available until after TLS is already set up.
So it doesn't seem I can use Deno for this feature today.

**Comment by mmastrac** [comment]
Moving this to the planning stage and closing in favour of a planning issue for the feature: #23233. Thanks for the early discussion on this issue.
