### ISSUE TITLE
[Std] Add CoreJs as Proxy object accessing common api between Browsre and Deno

### ISSUE THREAD

**Issue by redradist** [denoland/deno#9113]
I have created very simple object that will help to develop cross-platform libraries (Browser, Deno)

Using global object for creating cross platform library can lead to issue that developer will access some api that is available on Deno and not available on Browser ...

I decided to create proxy object that will help writing cross-platform libraries and application

Cross-platform API is available trough `coreThis` proxy object:
```javascript
import { coreThis } from "https://raw.githack.com/redradist/CoreJs/main/core.js";

console.log(coreThis.atob("aGVsbG8gd29ybGQ=")); // Print `hello world`
console.log(coreThis.someWierdName); // Return undefined
```

**Comment by lucacasonato** [comment]
The issue tracker is not for advertisement.
