### ISSUE TITLE
TLS Listener `for await` loop throws on client disconnection before TLS has established.

### ISSUE THREAD

**Issue by ihack2712** [denoland/deno#9123]
see title and screenshot.

<img width="667" alt="image" src="https://user-images.githubusercontent.com/35933830/104694542-a1752d80-570b-11eb-91c0-9ea1a801e461.png">

**Comment by nullobsi** [comment]
The TLS methods don't have very good error messages. Check issue #6427, older TLS ciphers are not supported by the underlying Rust crate.

**Comment by ihack2712** [comment]
This example didn't use TLS on the connecting side at all, problem is that the listener crashed when the client unexpectedly closed during a TLS handshake.

Here's the client code:

```ts
Deno.connect({hostname, port});
setTimeout(() => Deno.close(), 1000);
``

This crashed the `for await` loop on the TLS listener.

**Comment by lucacasonato** [comment]
@ihack2712 What do you expect to happen instead? The error was passed to JS gracefully (no panic occured). You just have to handle errors gracefully in your code. I would say this is intended behaviour.

**Comment by Spoonbender** [comment]
Is the listener really "crashed" or did it just throw an error trying to `accept` this one connection (and does catching this error enable it to `accept` the next valid connection attempt?) 
Can you provide the code of the server-side as well?

**Comment by ihack2712** [comment]
> I would say this is intended behaviour. @lucacasonato 

Maybe it is, I find it kinda weird to have a `for await` loop throw though.

> You just have to handle errors gracefully in your code. @lucacasonato 

How?

This is the best way I can think of:

```ts
const listener = Deno.listenTls({ ... });
async function acceptLoop () {
  try {
    for await (const conn of listener) {
      handleConn(conn);
    }
  } catch {
    await acceptLoop();
  }
}
```

Which to me seems like a lot of work just to avoid having errors spat at your face.

> What do you expect to happen instead? @lucacasonato 

I would most likely expect it to ignore connections that weren't fully established in the first place.

> Is the listener really "crashed" or did it just throw an error trying to accept this one connection (and does catching this error enable it to accept the next valid connection attempt?) @Spoonbender 

The error was of course gracefully sent to JS and rejected on the `.accept()` promise. One can continue to accept other connections.

**Comment by ihack2712** [comment]
Sorry if my tone sounds a bit toxic, that was not at all my intention. I just have a weird way of speaking :joy:

**Comment by bnoordhuis** [comment]
> What do you expect to happen instead?

An argument can be made that a TLS connection was never established and that the error isn't really actionable. Really the only thing you can do is log it (if you care about that kind of logging) and move on. So why not make that the default?

**Comment by ihack2712** [comment]
> > What do you expect to happen instead?
> 
> An argument can be made that a TLS connection was never established and that the error isn't really actionable. Really the only thing you can do is log it (if you care about that kind of logging) and move on. So why not make that the default?

Exactly the point I was trying to make, thank you!

**Comment by Spoonbender** [comment]
Inactive, but probably still relevant

**Comment by ihack2712** [comment]
Inactive, but probably still relevant

**Comment by lucacasonato** [comment]
I think this was resolved a few releases ago. Could you try with 1.10.3?

**Comment by ihack2712** [comment]
I'm on phone, without a pc or Mac for the next week, would somebody else try?

**Comment by ihack2712** [comment]
@lucacasonato Doesn't seem resolved 
<img width="1026" alt="image" src="https://user-images.githubusercontent.com/35933830/120927556-89fe0780-c6e1-11eb-89f5-b2bd485da781.png">

I did test on the latest version of Deno. I also tested on canary just now, neither work.

**Comment by lucacasonato** [comment]
That looks resolved to me... it throws on `r.read` now, not on the `for await` loop acceptor.

**Comment by ihack2712** [comment]
> That looks resolved to me... it throws on `r.read` now, not on the `for await` loop acceptor.

Oh, yes.. I did not see the code line, I just looked at the error message and it looked the same! The new way of throwing the unexpected eof looks way better than the last one :P Closing.
