### ISSUE TITLE
Deno cache breaks on redirected libraries.

### ISSUE THREAD

**Issue by xReveres** [denoland/deno#9129]
Today I wanted to implement this library:
`https://deno.land/x/hmac@v1.0.2`
But the problem is that, deno tries recompile whole project every time.
After day of test I found that this library imports own deps.ts with own third party libraries for example:
`https://denopkg.com/chiefbiiko/sha1@v1.0.3/mod.ts`
If we go under this address, we are redirected to:
`https://raw.githubusercontent.com/chiefbiiko/sha1/v1.0.3/mod.ts`
In $HOME/.cache/deps directory I see denopkg.com and raw.githubusercontent.com directories, so I don't know if this is a deno or denopkg problem.

Steps to reproduce:
1. Create test.ts file
2. Inside put:
```
import * as test from 'https://denopkg.com/chiefbiiko/sha1@v1.0.3/mod.ts'
```
3. `deno run test.ts`

**Comment by lucacasonato** [comment]
cc @kitsonk

**Comment by xReveres** [comment]
In version 1.6.1 the problem disappears.

**Comment by xReveres** [comment]
On Deno 1.6.1 looks good, file is not compiling every time

**Comment by lucacasonato** [comment]
@xReveres Does this succeed in 1.6.3?

**Comment by xReveres** [comment]
@lucacasonato Sorry. I'm forgot add information about Deno version in main post. No, this "bug"? exists only on Deno v1.6.2 and v1.6.3, as far as I'm tesing it.

**Comment by xReveres** [comment]
@lucacasonato Sorry. I'm forgot add information about Deno version in main post. No, from my tests, this "bug"? exists only on Deno v1.6.2 and v1.6.3.

**Comment by PaulThompson** [comment]
This issue exists on code I wrote that also uses denopkg for importing some dependencies from github.
Checked your test case just now on 1.7.0 - still with behaviour that it runs the typescript compile/checks on each call to `deno run test.ts`
