### ISSUE TITLE
Use sccache exclusively

### ISSUE THREAD

**Issue by ry** [denoland/deno#913]
We currently use a mixture of ccache and sccache to avoid hour long recompilations.

sccache caches rust builds.
ccache has better "sloppiness" settings. 

It would be nice if we could remove ccache completely and only use sccache.

**Comment by piscisaureus** [comment]
The sloppiness feature we really don't need actually. The chrome build system undefines the date/time macros, you can't use them.

**Comment by kt3k** [comment]
This seems done in #1369

**Comment by ry** [comment]
Thx
