### ISSUE TITLE
Parsing errors cause --watch to stop - 2

### ISSUE THREAD

**Issue by 00ff0000red** [denoland/deno#9130]
Originally reported and fixed in https://github.com/denoland/deno/issues/9008

Running on latest canary build.

@magurotuna Same stuff happening again, but with JavaScript instead of TypeScript.
Before I try setting up a repro, do think any of your code specifically targetted TS, as opposed to JS?

I'll try getting a reproducable example here with 12 hours.

**Comment by magurotuna** [comment]
@00ff0000red 

> Before I try setting up a repro, do think any of your code specifically targetted TS, as opposed to JS?

I don't think so, but I'm not really sure. The implementation code of the watcher doesn't contain TS specific stuff. So the issue might be caused by another code like module dependency resolution I guess.
I will look into it as well.

**Comment by 00ff0000red** [comment]
Yeah, here I am, only 12 hours later.

Okay, well, I could never get it to happen again, and it hasn't happened since then, so I'll close this up.
If there's a stray bug out there, then there's not much we can do until then.
