### ISSUE TITLE
Cant postmessage Webassembly Module or Memory

### ISSUE THREAD

**Issue by K0IN** [denoland/deno#9140]
I can't postmessage a shared WebAssembly memory or module to a worker:
![image](https://user-images.githubusercontent.com/19688162/104839764-8ea55900-58c3-11eb-9c57-2fd8d255eddb.png)

results in:
![image](https://user-images.githubusercontent.com/19688162/104839772-a41a8300-58c3-11eb-915e-3317c45adeec.png)

Same happens with wasm module, also I cant use any of them to move wasm execution into a worker
Do I need a special flag for this? 

Command I used to run this:
docker run -it --init -v ${PWD}:/app hayd/alpine-deno run --allow-read --unstable --v8-flags="--experimental-wasm-threads" /app/main.ts

[test.zip](https://github.com/denoland/deno/files/5826010/test.zip)

**Comment by lucacasonato** [comment]
Deno does not support structured clone between workers yet. See #3557
