### ISSUE TITLE
Compile-time constants

### ISSUE THREAD

**Issue by LukeChannings** [denoland/deno#9152]
Consider the following:

```typescript

const VERSION = __VERSION__ ?? "development"

console.log(VERSION)
```

It is common in the JavaScript ecosystem to replace variables a compile time, e.g. `process.env.NODE_ENV`, `__DEBUG__`. 

Deno does not appear to have this functionality, which makes compiling a version of your application to hard-code a version, or to optimise away debug blocks, etc. a bit of a pain.

SWC appears to support the equivalent of this functionality with [`jsc.transform.constModules`](https://swc.rs/docs/configuring-swc#jsctransformconstmodules), although the functionality appears to be scoped to a particular module, unlike [`DefinePlugin`](https://webpack.js.org/plugins/define-plugin/), for example.

**Comment by sno2** [comment]
If we were to introduce a global constants object, I think we might be better putting it in the `globalThis` to have the closest functionality to the web.  Although, Deno is all pro-no config, so where would you even be getting this development variable from?  You would probably be best off loading it from a json file yourself.

**Comment by shadowtime2000** [comment]
I mean like replacing of those variables isn't really something that Deno should do, it seems something more fit for a tool that is a Deno pkg.

**Comment by lucacasonato** [comment]
@LukeChannings You can compile `Deno.args` into your program since 1.6.3. Does this solve the issue for you?

**Comment by LukeChannings** [comment]
Hey @lucacasonato,

Any kind of build-time persistence is useful, so this can definitely solve my problem.
Futhermore, when Deno gets import assertions this will likely be less of an issue too - I'll probably have a JSON doc that contains build-specific metadata that gets embedded into the bundle.

I'll close this for now, since there's already a ticket tracking import assertions.

Thanks

**Comment by sik-asn** [comment]
> @LukeChannings You can compile `Deno.args` into your program since 1.6.3. Does this solve the issue for you?

How is this done? :) couldn't find my way to any docs on how, online, with the CLI or otherwise.

**Comment by sik-asn** [comment]
This is exactly what I needed - thank you! :)
