### ISSUE TITLE
Deno does not run on Alpine Linux / iSH

### ISSUE THREAD

**Issue by michal-minich** [denoland/deno#9153]
I Installed Deno on iSH on iPhone using script from home page:

`curl -fsSL https://deno.land/x/install/install.sh | sh`

the install says it was successful.

after running `deno` I get:
```
./deno: line 1: can't create �D?@X%@8: Illegal byte sequence
./deno: line 1: ELF: not found
./deno: line 2: D_9#: not found
./deno: line 2: @,+@@@0ppp�!�!: not found
./deno: line 3: syntax error: unexpected ")"
```

Are there any steps to make it work?
Is there plan to support it out of the box?

Thank you.

**Comment by ry** [comment]
-> #1658

**Comment by chrda81** [comment]
I ran into this issue today and was wondering, if there is any progress/work-a-round to make deno work on iSH for iOS? It seems that the iSH emulator for Alpine Linux is stuck on 32bit. This is what I was trying so far:

Download glibc package from https://github.com/sgerrand/alpine-pkg-glibc:

```sh
wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub
wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.35-r1/glibc-2.35-r1.apk
apk add glibc-2.35-r1.apk
```

Then I installed deno:

```sh
curl -fsSL https://deno.land/install.sh | sh
```

After that I patched the deno binary as mentioned in https://github.com/denoland/deno/issues/1658:

```sh
patchelf --set-interpreter /usr/glibc-compat/lib/ld-linux-x86-x64.so.2 --set-rpath /usr/glibc-compat/lib:/usr/lib /root/.deno/bin/deno
```

But I still get the error:

```sh
-bash: /root/.deno/bin/deno: cannot execute binary file: Exec format error
```

Any help is appreciated :)
