### ISSUE TITLE
error: Uncaught (in promise) TypeError: Cannot read property 'status' of undefined

### ISSUE THREAD

**Issue by GCSBOSS** [denoland/deno#9155]
- Deno: **1.6.3 (release, x86_64-pc-windows-msvc)**
- V8: **8.8.294**
- TS: **4.1.3**

While trying to port some test cases over from node.

```js
import { serve } from 'https://deno.land/std@0.83.0/http/server.ts'

Deno.test('Anything', async function(){
    let srv = serve({ port: 8008 })
    fetch('http://localhost:8008')
    let { value: req } = await srv[Symbol.asyncIterator]().next()
    req.respond()
    srv.close()
});
```
I got this weird error. 

```
running 1 tests
test Anything ... error: Uncaught (in promise) TypeError: Cannot read property 'status' of undefined
  const statusCode = r.status || 200;
                       ^
    at writeResponse (_io.ts:237:24)
    at ServerRequest.respond (server.ts:89:13)
    at file:///C:/Users/.../init.js:7:9
    at async asyncOpSanitizer (deno:runtime/js/40_testing.js:36:7)
    at async Object.resourceSanitizer [as fn] (deno:runtime/js/40_testing.js:70:7)
    at async TestRunner.[Symbol.asyncIterator] (deno:runtime/js/40_testing.js:245:13)
    at async Object.runTests (deno:runtime/js/40_testing.js:322:22)
    at async file:///C:/Users/.../$deno$test.ts:3:1
```

Since I'm new and using undocumented code paths, I might just be doing non-sense. Nevertheless, the exception I get is unclear. Hope anyone knows what's up.

Thanks!

**Comment by cmorten** [comment]
I suspect this is because there are no null guards along that code path, so in not providing an object to the `req.respond()` method, you are hitting a "cannot read property 'xxx' of undefined" error very early on into the std libs codepath. Try providing an empty object and see if that resolves the issue?

REFs:
- https://github.com/denoland/deno/blob/master/std/http/server.ts#L89
- https://github.com/denoland/deno/blob/master/std/http/_io.ts#L237

If this is the case, it is curious why Typechecking has not kicked in (are you using `.js` for your tests?), and whether there should be an error thrown for missing the `Response` argument, or simply `undefined` being cast to an empty object from the outset, e.g.

```ts
  async respond(r: Response = {}): Promise<void> {
```

at https://github.com/denoland/deno/blob/master/std/http/server.ts#L85.

**Comment by GCSBOSS** [comment]
I am using `.js`. When I send an empty object (`{}`), I get the following, kinda cryptic, error:

```
running 1 tests
test Anything ... error: Uncaught (in promise) BadResource: Bad resource ID
    at unwrapResponse (deno:runtime/js/10_dispatch_minimal.js:59:13)
    at sendAsync (deno:runtime/js/10_dispatch_minimal.js:98:12)
    at async write (deno:runtime/js/12_io.js:117:20)
    at async Object.writeAll (deno:runtime/js/13_buffer.js:223:19)
    at async BufWriter.flush (bufio.ts:468:7)
    at async writeResponse (_io.ts:288:3)
    at async ServerRequest.respond (server.ts:89:7)
```

**Comment by cmorten** [comment]
The `Response` interface implies otherwise, see https://github.com/denoland/deno/blob/master/std/http/server.ts#L394 in the code - it should all be optional.

In your code example you are not `await`ing the response so you are likely closing the server before the response is fully written. It is then expected that attempted to write a response to a closed port results in a `BadResource` error.

Try:

```ts
    // ...
    await req.respond({})
    srv.close()
});
```

**Comment by GCSBOSS** [comment]
Nice. That solves it. Is there anything we can do to have a default empty object on `res.respond()`? 
Otherwise this issue can be closed.

**Comment by kt3k** [comment]
@GCSBOSS 
`srv.close()` seems causing `BadResource: Bad resource ID` error. You need to await `req.respond({})` before closing the server.

```js
import { serve } from 'https://deno.land/std@0.83.0/http/server.ts';

Deno.test('Anything', async function(){
    let srv = serve({ port: 8008 });
    const fetching = fetch('http://localhost:8008');
    let { value: req } = await srv[Symbol.asyncIterator]().next();
    await req.respond({ body: 'hello' });
    srv.close();
    const res = await fetching;
    console.log(await res.text());
});
```

`await fetching` and `await res.text()` are necessary for preventing the resource leak in the test case.

**Comment by nayeemrmn** [comment]
You're passing a value which violates the TS types, so this is undefined behaviour. This is expected.

**Comment by kt3k** [comment]
@nayeemrmn 
> You're passing a value which violates the TS types, so this is undefined behaviour. This is expected.

I thought the same thing first, but after checking it in VSCode I found that the example is valid as TypeScript.

The reason is that `srv[Symbol.asyncIterator]().next()` returns `Promise<IteratorResult<T, any>>` and therefore `req` is any in the above example unfortunately.

**Comment by nayeemrmn** [comment]
Ah, I see the issue. It's unfortunate that TS defaults to `any` as opposed to `unknown` [here](https://github.com/denoland/deno/blob/3505823e20baf961865ddb1d2c74fd420b79f13e/cli/dts/lib.es2018.asynciterable.d.ts#L32).

@GCSBOSS Use the following correction to get TS to enforce the correct types:
```ts
import { serve } from 'https://deno.land/std@0.83.0/http/server.ts'

Deno.test('Anything', async function(){
    const srv = serve({ port: 8008 })
    fetch('http://localhost:8008')
    const result = await srv[Symbol.asyncIterator]().next()
    if (!result.done) {
        const req = result.value
        req.respond({})
    }
    srv.close()
});
```

My previous response still stands, though. _Assuming_ `req` has the correct type, empty args for `req.respond()` is invalid with undefined behaviour.

**Comment by GCSBOSS** [comment]
@nayeemrmn Thanks for your response! 
Am I wrong to think this is not very good support for `.js` users? 
Or is Deno/stdlib targetting `.ts` only?

**Comment by nayeemrmn** [comment]
> Am I wrong to think this is a little odd for `.js` users?
> Or is Deno/stdlib targetting `.ts` only?

No, the JS users are expected to still use the TS type definitions as documentation. It would conversely be odd for TS users if they incurred the costs of complete runtime type validation when they get that at compile time. That means JS users may see a cryptic reference error now and again if they misuse a _documented_ API, but it's worth it.

**Comment by GCSBOSS** [comment]
I understand. Can you please point me to the documentation for `Response`? You can close the issue also.

**Comment by nayeemrmn** [comment]
- https://github.com/denoland/deno/blob/v1.6.3/std/http/server.ts#L85
- https://github.com/denoland/deno/blob/v1.6.3/std/http/server.ts#L395-L400

I can't close the issue, but you or a maintainer can.

**Comment by GCSBOSS** [comment]
I wonder if we will get those as textual files eventually.
Thank you for your help!
