### ISSUE TITLE
Export function for HTTP server to await for a single (the first) request

### ISSUE THREAD

**Issue by GCSBOSS** [denoland/deno#9156]
Hi, there! 
I wonder if it's feasible/desirable to implement a function on `Server`, to await for a single (the first) request. Like so:

```js
// Readers Notice! This code does not work as of 0.83.0
import { serve } from 'https://deno.land/std@0.83.0/http/server.ts'

let srv = serve()
let req = await srv.next() // Or any better name
req.respond()
srv.close()
```
Seems very useful for writing tests and single-run utilities.

Apparently, something like this already works: 
```js
let { value: req } = await srv[Symbol.asyncIterator]().next()
```
Just not very elegant.

**Comment by sholladay** [comment]
Rather than having something built into `server` for this, I would suggest adding a function to `std/async` that returns the first value from an async iterable.

I'll just call the function `first` for demonstration purposes, you would use it like this...

```js
import { first } from 'https://deno.land/std@0.83.0/async/mod.ts'
import { serve } from 'https://deno.land/std@0.83.0/http/server.ts'

const server = serve();
const request = await first(server);
request.respond();
server.close();
```
