### ISSUE TITLE
cannot find deno_runtime 0.6.0 from crates.io

### ISSUE THREAD

**Issue by aircloud** [denoland/deno#9164]
I found that the version of `deno_runtime` has been changed to 0.6.0

But from crates.io I can only download 0.5.0

I want to know when I can download 0.6.0, Thank you~

**Comment by bartlomieju** [comment]
It's a mistake; we forgot to release `0.6.0` to crates.io. We'll be releasing `0.7.0` tonight so I'm gonna close this issue.
