### ISSUE TITLE
[LSP] Add hover support for regex patterns which explains what a node is matching

### ISSUE THREAD

**Issue by RDambrosio016** [denoland/deno#9177]
inspired by https://regex101.com/

Oftentimes for beginners and even intermediate programmers it is difficult to remember what something inside of a regex matches. Tools to aide in figuring regex out exist such as https://regex101.com/. However, it would be helpful to have hover info at a glance for this. This should be relatively easy as i have developed a regex parser for ES2021 regex for my own project [here](https://github.com/rslint/rslint/tree/master/crates/rslint_regex). Implementing this feature would involve:

- once parsed, crawl the swc ast using a regex visitor to collect regex literals as well as `new RegEx("pattern", "flags")` calls.
- extract the pattern and flags
- parse the pattern into a regex AST, if successful, go on, otherwise, continue.
- cache this list of ~~regrets~~ regexes.
- on hover, if a containing regex pattern is found, try to find the containing node of the cursor position
- generate the appropriate text based on the matched node.

Example:

```js
/[\d]/
// ^ `\d` matches a single digit `0 - 9` (equivalent to `[0-9]`
```

```js
/[\d]/
//  ^ matches a single character present in the set
```

**Comment by kitsonk** [comment]
Why would this need to be a Deno thing?  It sounds like much better suited as a seperate plugin.  For example, there is already one available for VSCode: https://github.com/chrmarti/vscode-regex.

**Comment by RDambrosio016** [comment]
I don't see how this is different from something such as jsdoc highlighting or regex highlighting, it is a generally nice quality of life feature, and people are very unlikely to explicitly search for something like this when they could benefit from such a thing.

**Comment by kitsonk** [comment]
This is out of scope for the lsp.  Respectfully declining.
