### ISSUE TITLE
deno fmt won't allow optional methods in an exported abstract class, or export abstract

### ISSUE THREAD

**Issue by shardyMBAI** [denoland/deno#9184]
Hello, 

I just updated to v1.7.0 and `deno fmt` has some issues with exporting an abstract class

<img width="432" alt="Screen Shot 2021-01-20 at 1 33 58 AM" src="https://user-images.githubusercontent.com/27963753/105136600-ef998080-5abf-11eb-9cde-ceff0cc6e380.png">

```ts
export abstract class Serializable {
  /** allow empty class serialization */
  constructor() {
    getOrInitializeDefaultSerializerLogicForParents(this.constructor.prototype);
  }
  /** key transform functionality */
  public tsTransformKey?(key: string): string {
    return key;
  }
  /** to JSON String */
  public toJSON(): string {
    return toJSON(this);
  }
  /** Deserialize to Serializable */
  public fromJSON(json: string | JSONValue | Object): this {
    return fromJSON(this, json);
  }
  /** to JSONObject */
  public tsSerialize(): JSONObject {
    return toPojo(this);
  }
}
```

also, if an abstract class has an optional method with `?` the `deno fmt` adds a second `?` like it is expecting the `null coalescing operator`

```ts
  public tsTransformKey?(key: string): string {
    return key;
  }
```
becomes 

```ts
  public tsTransformKey??(key: string): string {
    return key;
  }
```

**Comment by shardyMBAI** [comment]
https://github.com/denoland/deno/pull/8887 might be related

**Comment by Liamolucko** [comment]
I've opened a PR to fix this at dprint/dprint-plugin-typescript#88.

**Comment by shardyMBAI** [comment]
That's awesome, thank you @Liamolucko. 

I'll head over there and see if there is a PR for the `export abstract` issue.

Cheers.

**Comment by Liamolucko** [comment]
At least on my end the `export abstract` issue only shows up after `deno fmt` messes up the question marks, so I think it's just a bad error message.
