### ISSUE TITLE
Invalid output for JSX comment

### ISSUE THREAD

**Issue by thgh** [denoland/deno#9188]
Input:
```
function Test() {
  return <View
    // comment
  ></View>;
}
```

Output: (comment is moved into children)
```
function Test() {
  return <View> // comment
  </View>;
}
```

Expected:
```
function Test() {
  return <View
    // comment
  />;
}
```

**Comment by lucacasonato** [comment]
> I will repost on dprint, is that OK?

Sounds good. Lets keep this issue open here for tracking too, and link to the upstream dprint issue when you open it.

**Comment by thgh** [comment]
Alright: https://github.com/dprint/dprint-plugin-typescript/issues/89
