### ISSUE TITLE
Deno bundle and compile issues Where compile dosnt work but bundle does

### ISSUE THREAD

**Issue by spkier12** [denoland/deno#9189]
So i tried to compile my main.ts file 
and i wrote deno bundle main.ts deno.bundle.js and it works flawlessly and i can run the file with no issues and visit my website
but as soon as i write: deno compile --allow-net --allow-read --allow-write deno.bundle.js 
it compiles to .exe and that's fine but as soon as i start the .exe it starts the web server with no issues but when visiting my website i get the following in console: CHAR_COMMAND_FORWARD_SLASH NOT DEFINED
but i did not get this when bundeling?

**Comment by kitsonk** [comment]
It would be really helpful if you:

- Provided the version of Deno you are using.
- Provided a more complete example of what is in your main.ts, as it is really difficult to guess what is in there.


Also, `deno compile` already bundles for you... what happens when you try `deno compile --allow-net --allow-read --allow-writer main.ts`?

**Comment by spkier12** [comment]
I had that added however not sure where the rest of my text went but either way.
So i'm very well aware that it bundels however when i also wrote: deno compile --allow-net --allow-read --allow-writer main.ts 

it did compile and deno bundle does bundle like it's supposed to however when you run either of these .exe whatever you do if you run a web server you will just get the  CHAR_COMMAND_FORWARD_SLASH NOT DEFINED when you visit the website

Just start a website using OAK(latest per date) and deno (1.7.0) using parameters if that's helpful and then it compile it to a src.exe and when you visit the website you should get the exact same error, hope that's helpful (i never do bug reports)

**Comment by kitsonk** [comment]
You provided the version of Deno you are using, but it would be really helpful if you:

- Provided a more complete example of what is in your `main.ts`, as it is really difficult to guess what is in there.
