### ISSUE TITLE
`1.7.0` release zips denort but doesn't upload it

### ISSUE THREAD

**Issue by 06kellyjac** [denoland/deno#9193]
https://github.com/denoland/deno/commit/a44349dfdfecacdd4ccd343a984b05abb728bf88

https://github.com/denoland/deno/blob/v1.7.0/.github/workflows/ci.yml#L291-L307

https://github.com/denoland/deno/releases/tag/v1.7.0

---

Is it intentional to zip but not upload `denort` just yet as it needs more work before release?

**Comment by bartlomieju** [comment]
`denort` is not published to Github, it's uploaded to `dl.deno.land`, it's working as expected.

**Comment by 06kellyjac** [comment]
Thanks. I'm guessing when packaging for distros that should be deleted or not compiled in the first place?

**Comment by bartlomieju** [comment]
> Thanks. I'm guessing when packaging for distros that should be deleted or not compiled in the first place?

I'm not sure I understand the question; can you elaborate?

**Comment by 06kellyjac** [comment]
Well since it's not published to GH I'm wondering if I should keep it in my deno package for nixpkgs or delete it? Or if I'm just going to delete it, a way to tell cargo not to bother compiling it?

```
├── bin
│   ├── deno
│   └── denort
└── share
    ├── bash-completion
    │   └── completions
    │       └── deno.bash
    ├── fish
    │   └── vendor_completions.d
    │       └── deno.fish
    └── zsh
        └── site-functions
            └── _deno
```

**Comment by bartlomieju** [comment]
@06kellyjac `denort` is not needed for using `deno` binary I think you can safely delete it; when using `deno compile --target/--lite` Deno will download it from `dl.deno.land`.

**Comment by 06kellyjac** [comment]
Thanks for your help. I just had a read through https://github.com/denoland/deno/commit/9ff468df730e330370d90b33db5b2cfc0f508601

So if I understand it correctly:
Without flags it uses the current deno
With any flags it'll look in `<DENO_DIR>/dl/release/v<VERSION>/<deno or denors depending on flag>-<TARGET>.zip`
If the file exists it unzips and uses as is or it'll download it?

---

Since nix/nixOS is pretty different programs need to be correctly compiled to work with it or be patched with [patchelf](https://github.com/NixOS/patchelf)

```
λ ./result/bin/deno compile --allow-read --lite --unstable https://deno.land/std@0.79.0/examples/cat.ts
Check https://deno.land/std@0.79.0/examples/cat.ts
Bundle https://deno.land/std@0.79.0/examples/cat.ts
Compile https://deno.land/std@0.79.0/examples/cat.ts
Checking https://dl.deno.land/release/v1.7.0/denort-x86_64-unknown-linux-gnu.zip
Download has been found
Archive:  /tmp/.tmpinJrgq/denort..zip
  inflating: denort
Emit cat
λ mv cat cat-slim
λ ./result/bin/deno compile --allow-read --unstable https://deno.land/std@0.79.0/examples/cat.ts
Check https://deno.land/std@0.79.0/examples/cat.ts
Bundle https://deno.land/std@0.79.0/examples/cat.ts
Compile https://deno.land/std@0.79.0/examples/cat.ts
Emit cat
λ ls -al cat*
.rwxrwxrwx jk users 44 MB Wed Jan 20 11:48:26 2021  cat
.rwxrwxrwx jk users 33 MB Wed Jan 20 11:47:46 2021  cat-slim
λ ls /tmp/.tmpinJrgq/denort..zip
 /tmp/.tmpinJrgq/denort..zip
λ ls /tmp/.tmpinJrgq
 denort   denort..zip
λ ./cat-slim README.md
zsh: no such file or directory: ./cat-slim
λ docker run -v $PWD:/dir -it debian:buster-slim
$ cd dir
$ ./cat-slim README.md
<p align="center">
# ...
```

I'll need to have a think how I'll do things.
A flag to specify a specific `denort` binary might help & then I can document somewhere nix users need to use that flag if they want to run the output locally.

On the flip side it's nice to now be able to compile deno results in nixOS that can be ran on more normal non-nixOS distros.

---

And as a note the unzip file name doesn't look right `Archive:  /tmp/.tmpinJrgq/denort..zip` (from the logs before)

Just using `unzip` in the cli myself the folder name comes out correct

```
λ mkdir tmp
λ cd tmp
λ cp ~/.cache/deno/dl/release/v1.7.0/denort-x86_64-unknown-linux-gnu.zip .
λ unzip denort-x86_64-unknown-linux-gnu.zip
Archive:  denort-x86_64-unknown-linux-gnu.zip
  inflating: denort
```
