### ISSUE TITLE
Return an exit code on "unload"

### ISSUE THREAD

**Issue by oscarotero** [denoland/deno#9201]
Hi.
I have a function that execute some stuff. And I want to return different exit codes, depending on the result of this execution. Something like this:

```js
const success = await run();
Deno.exit(success ? 0 : 1);
```

Sometimes is impossible to know when `run()` finished (because there may be async functions that don't return a promise), so `Deno.exit()` can break the execution of some things inside `run()`. To prevent that, I fixed it with this code:

```js
const success = await run();
window.addEventListener("unload", () => Deno.exit(success ? 0 : 1));
```

This ensures that only after finish all process, subprocess, etc inside `run()`, the proper exit code is returned.

After upgrading to Deno < 1.7 I'm getting the following error: `error: Uncaught RangeError: Maximum call stack size exceeded`. I guess this is because #9088, so `Deno.exit()` dispatches `unload` event that executed `Deno.exit()` that dispatches `unload` and so on.

To prevent this, I think `unload` should be triggered only once. Or if there's any other way to set an exit code without using `Deno.exit()`, that would be fine too.

**Comment by 00ff0000red** [comment]
The unload event should only be fired once, I think that's a bug.

**Comment by kitsonk** [comment]
It should only fire once. We should hold on to a global reference for the event when it is raised and not raise it again if present.
