### ISSUE TITLE
Wasm error stack traces are too similar to JS traces

### ISSUE THREAD

**Issue by CrimsonCodes0** [denoland/deno#9205]
Example script:
```js
const { loop } = (await WebAssembly.instantiate(
	BigUint64Array.of(
		0x16D736100n,
		0x203000060010401n,
		0x6F6C040108070001n,
		0x401060A0000706Fn,
		0x6E040A000B001000n,
		0x10302656D61n
	)
)).instance.exports;

loop();
```

`loop` is a function that just recurses into itself, so we can get a `RangeError` and a stack trace.

Chrome gives this stack trace:
```
RangeError: Maximum call stack size exceeded
  at loop (<anonymous>:wasm-function[0]:0x20)
  at loop (<anonymous>:wasm-function[0]:0x21)
  ...
  at loop (<anonymous>:wasm-function[0]:0x21)
```
This tells me that the first function in my Wasm module threw the error, at byte `0x21`, and that it was called via the JS identifier `loop`.

Here's Deno's stack trace:
```
error: Uncaught RangeError: Maximum call stack size exceeded
  at loop (<anonymous>:0:32)
  at loop (<anonymous>:0:33)
    ...
  at loop (<anonymous>:0:33)
```

Personally, I'd say that this is very misleading, binary blobs don't exactly have columns and rows (`0:33`).
I would consider that part to be a bug.

Otherwise, imo, it would be great to have the common `wasm-function[N]` that FF and Chromium show in the stack trace, for debugging.

Also, I believe that double `<anonymous>` here is unnecessary:
```js
WebAssembly.instantiate(
	Uint8Array.of(
		0x0, 0x61, 0x73, 0x6D,
		0x1, 0x0, 0x0, 0x0,
		0x1, 0x4, 0x1, 0x60,
		0x0, 0x0, 0x3, 0x2,
		0x1, 0x0, 0x8, 0x1,
		0x0, 0xA, 0x6, 0x1,
		0x4, 0x0, 0x10, 0x0,
		0xB, 0x0, 0xA, 0x4,
		0x6E, 0x61, 0x6D, 0x65,
		0x2, 0x3, 0x1, 0x0,
		0x0
	)
);
```
Deno:
```
error: Uncaught (in promise) RangeError: Maximum call stack size exceeded
  at <anonymous> (<anonymous>:0:25)
  at <anonymous> (<anonymous>:0:26)
  ...
  at <anonymous> (<anonymous>:0:26)
```
Chromium:
```
RangeError: Maximum call stack size exceeded
  at <anonymous>:wasm-function[0]:0x19
  at <anonymous>:wasm-function[0]:0x1a
  ...
  at <anonymous>:wasm-function[0]:0x1a
```

what was the reasoning for overriding `Error.prepareStackTrace` in the first place?

**Comment by bnoordhuis** [comment]
> what was the reasoning for overriding Error.prepareStackTrace in the first place?

#7644 explains it and why it's not ideal. The idea is to RIIR.

V8's CallSite API that deno's prepareStackTrace hook uses doesn't expose the relevant information so that's one more reason to expedite #7644. The C++ API doesn't expose everything either, however, and that's the current blocker.

(That's partially on me - I submitted a CL to V8 last year that I promptly forgot about. I just checked and it looks like I never got notified of the review feedback.)

**Comment by 00ff0000red** [comment]
@bnoordhuis Yes, I know that it's in the plans to move it over to the Rust, but V8 already provides the stack trace, and formats it, so why does Deno cover that up with another set of formatting?

Also, do you have any suggestions regarding the issue raised?
Should the formatting be changed?
I would've tried to do this myself, but it seems like CallSite doesn't expose whether or not a function is JS or Wasm.

**Comment by CrimsonCodes0** [comment]
@bnoordhuis Sorry to potentially annoy you, but are you aware of whether the JS or C++ APIs provide whether the source function was ECMAScript or WebAssembly source code? If so, which one(s)?

**Comment by bnoordhuis** [comment]
@CrimsonCodes0 In C++ there's `v8::StackFrame::IsWasm()`, called `v8::StackFrame::is_wasm()` in rusty_v8.

With a reference to a `v8::Function`, I think you can call `function->GetScriptOrigin().Options().IsWasm()` but there are no rusty_v8 bindings for those yet.

**Comment by CrimsonCodes0** [comment]
@bnoordhuis Thank you for that information, when the stack trace is handled in Rust, I'll come back around to this, that is, if the core team is interested in my suggestion at all.
