### ISSUE TITLE
[bundle] Bundled code still doesn't work as expected

### ISSUE THREAD

**Issue by MariusVatasoiu** [denoland/deno#9220]
I still have this problem with Deno 1.7.0

_Originally posted by @MariusVatasoiu in https://github.com/denoland/deno/issues/8770#issuecomment-759756937_

**Comment by kitsonk** [comment]
You are going to have to be significantly more specific than this.

**Comment by MariusVatasoiu** [comment]
I investigated even deeper and I found that if you bundle this file:

`

**Comment by kitsonk** [comment]
Cc/ @kdy1

**Comment by bartlomieju** [comment]
Should be fixed in https://github.com/denoland/deno/pull/9374
