### ISSUE TITLE
[STD/FS] Copy method doesn't overwrite folder with such option enabled

### ISSUE THREAD

**Issue by ilovewine** [denoland/deno#9223]
**ENV**: Linux

**Steps to reproduce**:

- create ./foo with a file.txt (with some data X)
- create ./folder with a file2.txt (with some data Y)
- create the script copy.ts:
```
import { copy } from "https://deno.land/std@0.81.0/fs/mod.ts";

copy("./foo", "./folder", {overwrite: true});
```
- run deno run --unstable --allow-read --allow-write copy.ts
**Expected result**: folder ./folder contains only file.txt with data X
**Actual result**: folder ./folder contains both file.txt with data X and file2.txt with data Y

**Comment by ilovewine** [comment]
#9222 - This is the equivalent for synchronous method.

**Comment by grosto** [comment]
I think this is an expected behaviour. Most of the overwrites are implemented this way. Maybe the docs should be more clear that it will overwrite *existing* files but will not delete anything extra.

**Comment by ilovewine** [comment]
@grosto agreed :) even if this is expected, the documentation should be as clear as possible in order to avoid any misinterpretations :)

**Comment by ry** [comment]
We recently discussed this method in the [std working group](https://github.com/denoland/deno/discussions/8405) I will make a note that we should clarify the documentation of fs.copy. The behavior is expected.
