### ISSUE TITLE
Publish on NPM?

### ISSUE THREAD

**Issue by shadowtime2000** [denoland/deno#9236]
So this is going to seem really dumb but I think it would be pretty cool if you published Deno binaries on NPM. It would be nice for projects that publish to Deno and NPM because then it would be easier to have one consistent version used by contributors and maintainers. Kind of like `hugo-bin` I guess. Also maybe make sure it has a different command in that (`deno-bin`?).

**Comment by kitsonk** [comment]
There are sufficient ways to obtain Deno binaries already. Respectfully closing.
