### ISSUE TITLE
Deno bundle gets stuck after/during SWC Merge

### ISSUE THREAD

**Issue by marcopennekamp** [denoland/deno#9238]
I am trying to bundle the runtime of my programming language Lore with Deno. The runtime is written in Typescript and has worked fine with Deno for some time. I just updated to Deno 1.7.0 from 1.5.4. The bundle command previously worked for me using 1.5.4 (with the same Typescript code).

I executed the following command to bundle the runtime from the root folder of my language project: `deno bundle --log-level=debug runtime/src/lore/runtime/Lore.ts lore.js`

The last debug log entries are the following:

```
DEBUG RS - swc_bundler::bundler::chunk::merge:401 - Merged <file:///home/marco/work/lore/runtime/src/lore/runtime/intersections.ts> into <file:///home/marco/work/lore/runtime/src/lore/runtime/Lore.ts> as a transitive es module
DEBUG RS - swc_bundler::bundler::chunk::merge:401 - Merged <file:///home/marco/work/lore/runtime/src/lore/runtime/shapes.ts> into <file:///home/marco/work/lore/runtime/src/lore/runtime/Lore.ts> as a transitive es module
DEBUG RS - swc_bundler::bundler::chunk::merge:401 - Merged <file:///home/marco/work/lore/runtime/src/lore/runtime/structs.ts> into <file:///home/marco/work/lore/runtime/src/lore/runtime/Lore.ts> as a transitive es module
DEBUG RS - swc_bundler::bundler::chunk::merge:401 - Merged <file:///home/marco/work/lore/runtime/src/lore/runtime/tuples.ts> into <file:///home/marco/work/lore/runtime/src/lore/runtime/Lore.ts> as a transitive es module
DEBUG RS - swc_bundler::bundler::chunk::merge:401 - Merged <file:///home/marco/work/lore/runtime/src/lore/runtime/types/types.ts> into <file:///home/marco/work/lore/runtime/src/lore/runtime/Lore.ts> as a transitive es module
DEBUG RS - swc_bundler::bundler::chunk::merge:401 - Merged <file:///home/marco/work/lore/runtime/src/lore/runtime/types/kinds.ts> into <file:///home/marco/work/lore/runtime/src/lore/runtime/Lore.ts> as a transitive es module
DEBUG RS - swc_bundler::bundler::chunk::merge:401 - Merged <file:///home/marco/work/lore/runtime/src/lore/runtime/types/util.ts> into <file:///home/marco/work/lore/runtime/src/lore/runtime/Lore.ts> as a transitive es module
DEBUG RS - swc_bundler::bundler::chunk::merge:401 - Merged <file:///home/marco/work/lore/runtime/src/lore/runtime/utils/hash.ts> into <file:///home/marco/work/lore/runtime/src/lore/runtime/Lore.ts> as a transitive es module
DEBUG RS - swc_bundler::bundler::chunk::merge:401 - Merged <file:///home/marco/work/lore/runtime/src/lore/runtime/utils/HashMap.ts> into <file:///home/marco/work/lore/runtime/src/lore/runtime/Lore.ts> as a transitive es module
DEBUG RS - swc_bundler::bundler::chunk::merge:401 - Merged <file:///home/marco/work/lore/runtime/src/lore/runtime/types/equality.ts> into <file:///home/marco/work/lore/runtime/src/lore/runtime/Lore.ts> as a transitive es module
DEBUG RS - swc_bundler::bundler::chunk::merge:401 - Merged <file:///home/marco/work/lore/runtime/src/lore/runtime/utils/TinyMap.ts> into <file:///home/marco/work/lore/runtime/src/lore/runtime/Lore.ts> as a transitive es module
DEBUG RS - swc_bundler::bundler::chunk::merge:401 - Merged <file:///home/marco/work/lore/runtime/src/lore/runtime/utils/TinySet.ts> into <file:///home/marco/work/lore/runtime/src/lore/runtime/Lore.ts> as a transitive es module
```

After this, the command doesn't finish (while the console stays silent). The Deno process uses a full CPU core and keeps allocating more memory. I've seen the process hit 8GB RAM before I killed it.

I could narrow down the problem to a single line of code in my runtime. This is the overall project URL: https://github.com/marcopennekamp/lore. The line in question is here: https://github.com/marcopennekamp/lore/blob/ef7d83a3a558d0886b2d3c2d4b90b1ae71d80ae9/runtime/src/lore/runtime/intersections.ts#L36. 

Commenting out this line allows the Bundler to finish. Alternatively, one may also comment out the line here: https://github.com/marcopennekamp/lore/blob/ef7d83a3a558d0886b2d3c2d4b90b1ae71d80ae9/runtime/src/lore/runtime/shapes.ts#L46.

`Shape.combine` depends on `Intersection.simplified` and vice-versa. This works quite fine when using `deno run` and also worked fine with the bundler from version 1.5.4. But it seems to trip up the current bundler. Because both functions (and the objects they're contained in) depend on each other, I'd hazard a guess that the bundler is somehow not detecting the circular dependency here.

You can find the full log here: https://gist.github.com/marcopennekamp/c95fe79b772899614cd945abfd5f3ea0

I haven't tried to build a reproducible example outside the context of my language runtime and hope you'll be able to reproduce it with the runtime. If that's not possible, let me know and I'll try to reproduce it with a small example.

**Comment by Liamolucko** [comment]
Minimal repro:

```ts
// bar.ts
import { Foo } from "./foo.ts";

export const Bar = {
  bar(depth = 10): string {
    if (depth === 1) {
      return "bar";
    } else {
      return Foo.foo(depth - 1);
    }
  },
};
```

```ts
// foo.ts
import { Bar } from "./bar.ts";

export const Foo = {
  foo(depth = 10): string {
    if (depth === 1) {
      return "foo";
    } else {
      return Bar.bar(depth - 1);
    }
  },
};

console.log(Foo.foo());
```

**Comment by Soremwar** [comment]
@Liamolucko That example is no longer valid as of 1.7.5

However I found a new reproduction on canary (using the lates import-map by URL feature)
```bash
deno bundle --unstable --import-map=https://raw.githubusercontent.com/Soremwar/procalidad_app/master/libraries.json https://raw.githubusercontent.com/Soremwar/procalidad_app/master/app.ts bundle.js
```
