### ISSUE TITLE
`deno compile` fails with exported default anonymous functions

### ISSUE THREAD

**Issue by oscarotero** [denoland/deno#9250]
Hi. I've found the following issue. Let's say we have this app with two javascript files (`log.js` and `cli.js`):

```js
// log.js

export default function (message) {
  console.log(message);
}
```

```js
// cli.js

import log from "./log.js";

if (import.meta.main) {
  cli();
}

export default async function cli() {
    log("It works!");
}
```

After compile this with `deno compile` and execute the result, I have the following error:

```
error: ReferenceError: Cannot access '__default' before initialization
    at cli (file://$deno$/bundle.js:12:5)
    at file://$deno$/bundle.js:6:5
```

Note that in `log.js` the exported function is anonymous. If I set a name, for example:

```js
// log.js

export default function log(message) {
  console.log(message);
}
```

It works fine.

Other way to prevent the error (without set a name to log) is execute first the function outside cli:

```js
// cli.js

import log from "./log.js";

log("Execute first"); //Execute the function here

if (import.meta.main) {
  cli();
}

export default async function cli() {
    log("It works!"); //Now it works here too
}
```

Now, after compile I get the expected result:

```
Execute first
It works!
```

**Comment by nayeemrmn** [comment]
More general repro:
```ts
import { foo } from "./temp2.js";

bar();

function bar() {
  console.log(foo);
}
```
```ts
// foo.js
export const foo = {};
```
`deno bundle`s to
```js
bar();
const foo = {
};
function bar() {
    console.log(foo);
}
```
@kdy1 Imported definitions are inlined just before their first usage, but that usage may occur in a hoisted function that can be accessed anywhere earlier. Imported definitions need to be inlined at the top to avoid this TDZ.

**Comment by oscarotero** [comment]
I've upgraded to deno 1.7.1 but seems like this bug is not fixed yet. I'm creating a new issue.
