### ISSUE TITLE
Simplify error handling in benchmark runner

### ISSUE THREAD

**Issue by ry** [denoland/deno#9253]
Use anyhow::Error instead of 

https://github.com/denoland/deno/blob/66e99d349b31f5cd30b868d80ebdab6ba749fd96/cli/bench/main.rs#L494-L526

Or maybe just unwrap in place, rather than passing errors around. The benchmark program exits on any failure...

**Comment by wperron** [comment]
I'll take this one, I already played a bit in the benchmark runner recently 👍
