### ISSUE TITLE
Plugin not initialized when compiling in Deno 1.7

### ISSUE THREAD

**Issue by wwderw** [denoland/deno#9257]
When trying to compile on 1.7 it gives an error about plugin not being initialized (importing webview for this program), however, when doing deno run in 1.7 or when compiling on 1.6, everything works as expected without any changes to the code.

**Comment by nayeemrmn** [comment]
The 1.6 behaviour is expected, flags weren't supported then. Could you clarify what you're seeing for 1.7? Is your program using a plugin?

**Comment by wwderw** [comment]
In this case, I'm using webview.  At most it's a combo of webview and abc.  Although, I do have something coming down the pipeline for SQLite.  But those would be my biggies for the foreseeable.  

It compiles and runs fine in 1.6 (as long as I'm not attempting to change cache location), but it gives me that error with 1.7, everything else being the same.

**Comment by nayeemrmn** [comment]
Putting 1.6 aside, does this happen in 1.7 _without_ changing the cache location?

**Comment by wwderw** [comment]
Yes.

**Comment by nayeemrmn** [comment]
Okay, please adjust the title and description of this issue to give less detail about that red herring and more about the error that you're seeing in 1.7 irrespective of DENO_DIR.

**Comment by wwderw** [comment]
That I couldn't tell you if it was a panic or not.  All I know that it works in 1.6, but it throws that error in 1.7.  If everything else is equal.

**Comment by nayeemrmn** [comment]
Show the error exactly as it appears.

**Comment by wwderw** [comment]
`error: Uncaught The plugin must be initialized before use`

That's all that it give back.

**Comment by lucacasonato** [comment]
I assume this is a SWC bug with ordering of statements in the compiled bundle. We have a swc_bundler upgrade coming up, that might fix this. Lets hold this for 1.7.1 (should release some time this week).

**Comment by wwderw** [comment]
I did try the canary build and got 
`error: ReferenceError: joinGlobs is not defined
    at file://$deno$/bundle.js:2638:20`

Don't know if that would have been fixed when a point release came out or not, but thought I would mention it.

**Comment by wwderw** [comment]
Yep, same error on 1.7.1 as I mentioned from 2 days ago using the official 1.7.1 release today.

**Comment by Miaourt** [comment]
Can confirm, getting the exact same error mentioned there https://github.com/denoland/deno/issues/9257#issuecomment-768553702

Using the [webview](https://github.com/webview/webview_deno) plugin too.

**Comment by realJoshByrnes** [comment]
Same error on 1.7.1 on MacOS: `error: ReferenceError: joinGlobs is not defined at file://$deno$/bundle.js:2638:20`

**Comment by jcc10** [comment]
Just for reference the following code: 
```
import { Webview } from "https://deno.land/x/webview@0.5.5/mod.ts";

const html = `
  <html>
  <body>
    <h1>Hello from deno v${Deno.version.deno}</h1>
  </body>
  </html>
`;

const webview = new Webview(
  { url: `data:text/html,${encodeURIComponent(html)}` },
);
await webview.run();
```
When compiled and ran returns
```
error: ReferenceError: joinGlobs is not defined
    at file://$deno$/bundle.js:2638:20
```
with
```
deno --version
deno 1.7.1 (release, x86_64-unknown-linux-gnu)
v8 8.9.255.3
typescript 4.1.3
```
running normally encounters no issues.

**Comment by Miaourt** [comment]
Still getting this with Deno 1.7.2 + webview 0.5.6, on Windows 10 20H2
```
error: ReferenceError: joinGlobs is not defined
    at file://$deno$/bundle.js:2975:20```

**Comment by wwderw** [comment]
Same here.

**Comment by jcc10** [comment]
```
deno 1.7.5 (release, x86_64-unknown-linux-gnu)
v8 9.0.123
typescript 4.1.4
webview 0.5.6
```
No change

**Comment by RoXuS** [comment]
+1 same here on 1.7.5

**Comment by wwderw** [comment]
The program appears to now compile, at least with Webview 0.5.3.

**Comment by jcc10** [comment]
With Deno 1.7.5 and webview_deno 0.5.6 the following occurs:
```
./test1
Download https://github.com/webview/webview_deno/releases/download/0.5.6/libwebview_deno.so
error: ReferenceError: joinGlobs is not defined
    at file://$deno$/bundle.js:2975:20
```

With webview_deno 0.5.3 (Was testing report from @wwderw) the following occurs:
```
./test1b
error: ReferenceError: joinGlobs is not defined
    at file://$deno$/bundle.js:2599:20
```

I don't know when that changed or if I never noticed it. I'm still on Linux (Pop_OS! 20.04) so it might be that it's fixed on windows but not Linux IDK.

**Comment by wwderw** [comment]
I'm on Ubuntu Studio Beta 21.04, not Windows, but I am using an older webview .so then you.

**Comment by wwderw** [comment]
I'm on Linux, Ubuntu Studio beta 21.04, but I am using Deno 1.8, try the latest.  It looks like you were still trying with 1.7.5 Deno.

**Comment by Miaourt** [comment]
Can confirm it now works on Deno 1.8.

**Comment by jcc10** [comment]
I swear I did try updateing before posting my last comment.

```
$ ./test1
Download https://github.com/webview/webview_deno/releases/download/0.5.6/libwebview_deno.so
$ ./test1b
$ 
```

Same web-views as before but on Deno1.8.0 Seems like something weird is happening with 0.5.6 downloading something every run but it does work. 

I'm going to try cross-compiling for windows real quick.

**Comment by jcc10** [comment]
Cross-compile from Linux to Windows works for webview_deno 0.5.6 so I think it is in fact fixed with 1.8.0 :tada:

**Comment by wwderw** [comment]
@realJoshByrnes Let me know how it fairs for you using 1.8 on a Mac.

If it appears to be good to go for you, I'll close this.  Otherwise I'll leave it open if you are having issues.

**Comment by chovy** [comment]
how do I compile my script?

**Comment by eliassjogreen** [comment]
`deno compile --unstable --allow-all main.ts`
