### ISSUE TITLE
Use panic hook to produce custom error report

### ISSUE THREAD

**Issue by satyarohith** [denoland/deno#9263]
Rust has an API (https://doc.rust-lang.org/std/panic/fn.set_hook.html) to set a custom panic hook. Assuming that rust panics are errors, we can leverage the set_hook function and produce a custom error report when Deno panics.

We can include all required details for our debugging in the report and instruct users to open an issue on GitHub with the information generated by the hook.

**Comment by Spoonbender** [comment]
@satyarohith beyond the capability itself, do you have a suggestion of what the content custom error report will include that we're missing today?

**Comment by satyarohith** [comment]
> @satyarohith beyond the capability itself, do you have a suggestion of what the content custom error report will include that we're missing today?

This is how a panic might look like currently:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', cli/flags.rs:1478:28
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

My inspiration for a custom hook is from Redis crash reports. We can essentially include system information (and also the backtrace without having the user run again) that we might have to ask users in case they don't provide the details in the issue (which might be less number of cases). And a readable report clarifies to the user that it's something that needs to fixed in the runtime.

After the above thoughts, it feels like it's just a "nice" thing to have. Feel free to close the issue if it feels like unnecessary baggage.

**Comment by bartlomieju** [comment]
I think we should add that hook. It should print a message telling users that this is internal Deno error and ask for a report with link to the issues page. @satyarohith can you look into it?
