### ISSUE TITLE
import map breaks relative importing

### ISSUE THREAD

**Issue by romdotdog** [denoland/deno#9272]
* Environment: Windows 10
* Version: Deno 1.7.0

Reproduction sample:

> /main.ts
```ts
import { constant } from "./import/constants.ts";

console.log(constant)
```

> /import/constants.ts
```ts
export const constant = "Hello, world!";
```

> /import_map.json
```json
{
  "imports": {
    "/": "./import/"
  }
}
```

If I add an import map to my project that uses relative imports anywhere then I get a strange error.
```
C:\Users\rom\Documents\deno-issue>deno run --allow-all --unstable --import-map import_map.json main.ts
Check file:///C:/Users/rom/Documents/deno-issue/main.ts
error: TS2305 [ERROR]: Module '"deno:///none.d.ts"' has no exported member 'constant'.
import { constant } from "./import/constants.ts";
         ~~~~~~~~
    at file:///C:/Users/rom/Documents/deno-issue/main.ts:1:10
```

**Comment by nayeemrmn** [comment]
Given the import map you're using, shouldn't the correct import specifier be `import { constant } from "/constants.ts";`? That error message is definitely a bug, though. cc @kitsonk

**Comment by romdotdog** [comment]
It works, but if I'm in a file importing a file from the same directory deep into my project, then I'd still like to have the feature of relative importing.

**Comment by nayeemrmn** [comment]
> It works, but if I'm in a file importing a file from the same directory deep into my project, then I'd still like to have the feature of relative importing.

Use this import map:
```json
{
  "imports": {
    "/": "./import/",
    "./": "./"
  }
}
```
It redirects absolute paths like you want, but resets this for anything in the directory of the import map. Then both forms will work.

**Comment by romdotdog** [comment]
Strange, but it works, thank you. I'd like to suggest to consider putting this in the documentation. Shall I close this issue, or does the bug concerning the error message require this issue to be open?

**Comment by romdotdog** [comment]
Upon further testing, the vscode Deno linter seems to only test the import map directory when doing a relative import using your import map, although the project compiles fine.

Reproduction sample (compiles, but doesn't pass linting):

> /import/main.ts
```ts
import { constant } from "./constants.ts";

console.log(constant)
```

> /import/constants.ts
```ts
export const constant = "Hello, world!";
```

> /import_map.json
```json
{
  "imports": {
    "/": "./import/",
    "./": "./"
  }
}
```

Summary:
The Deno vscode plugin with linting enabled gives this error: `Could not find module "C:\Users\rom\Documents\deno-issue\constants.ts" locally.`
It occurs in the first line of `/import/main.ts`

**Comment by nayeemrmn** [comment]
> Strange, but it works, thank you. I'd like to suggest to consider putting this in the documentation. Shall I close this issue, or does the bug concerning the error message require this issue to be open?

No problem. I wouldn't call it strange, it's an intuitive and useful mechanism which I've previously given as a way to block imports going outside of project roots. Nevertheless it's very niche. Plus this isn't deno-specific, it would go in the proposal's doc if anywhere.

I've opened #9275 for the issue so you can close this.

> Upon further testing, the vscode Deno linter seems to only test the import map directory when doing a relative import using your import map, although the project compiles fine.

Have you entered the import map in the extension settings? If you have and there's still an issue, check for and open a new one in https://github.com/denoland/vscode_deno/issues.

**Comment by romdotdog** [comment]
I have, thanks for your help!
