### ISSUE TITLE
Named imports from non-existent module give strange type errors

### ISSUE THREAD

**Issue by nayeemrmn** [denoland/deno#9275]
```ts
// deno run temp.ts
import { foo } from "./non-existent.ts";
```
Actual:
```
error: TS2305 [ERROR]: Module '"deno:///none.d.ts"' has no exported member 'foo'.
import { foo } from "./non-existent.ts";
         ~~~
    at file:///mnt/c/Users/Nayeem/projects/deno/temp.ts:2:10
```
Expected:
```
error: Cannot resolve module "file:///mnt/c/Users/Nayeem/projects/deno/non-existent.ts"
    at file:///mnt/c/Users/Nayeem/projects/deno/temp.ts:2:1
```
Versions: 1.6.2+

cc @kitsonk

**Comment by kitsonk** [comment]
We need to scan the module graph for any terminal errors and exit early, versus spinning up `tsc` and starting a type check.

**Comment by kitsonk** [comment]
Ok, digging into this a bit more, everything works as expected if the import is a default import, namespace import or dynamic import.  It is only named imports where TypeScript is "ignoring" the "any" module we substitute, causing the error.

As I said though we should error early when type checking to avoid this error, which at least saves spinning up tsc, but it isn't as straight forward as one might think.
