### ISSUE TITLE
deno test - Cannot resolve module

### ISSUE THREAD

**Issue by LukeChannings** [denoland/deno#9284]
```
λ deno --version
deno 1.7.0+ada43cc (canary, x86_64-apple-darwin)
v8 8.9.255.3
typescript 4.1.3
```

I have an import map:

```import_map.json
{
  "imports": {
    "/": "./",
  }
}
```

My program runs correctly with:

```
deno run -A --unstable --import-map=./import_map.json ./cmd/moviematch/main.ts
```

I have a simple test file:

```typescript
import { assertEquals } from "https://deno.land/std@0.84.0/testing/asserts.ts";

import { getDirectories } from "/internal/app/plex/api.ts";

Deno.test("getDirectories", async () => {
 // test getDirectories
});
```

When I run:

```
λ deno test --import-map ./import_map.json -A --unstable
```

I get:

```
Check file:///Users/luke/Developer/MovieMatch/$deno$test.ts
error: Cannot resolve module "file:///Users/luke/Developer/MovieMatch/Users/luke/Developer/MovieMatch/internal/app/plex/api_test.ts" from "file:///Users/luke/Developer/MovieMatch/$deno$test.ts".
```

Things I've tried:

- Moving the test into a standalone test folder and selecting it with `deno test --import-map ./import_map.json -A --unstable tests`
- Importing the source relatively (works, but absolute imports are used throughout so it fails further on)

Why is the behaviour of `deno test` different to `deno run`?

**Comment by kitsonk** [comment]
`deno test` creates a "synthetic" module which imports all the test modules it find, that is why the behaviour is different.

**Comment by nayeemrmn** [comment]
I was going to say we should reconsider a non-file URL for `$deno$test.ts` so it's not subject to this, but `$deno$eval.ts` and `$deno$repl.ts` etc. can't be helped because we want relative specifiers to work for them.

I think the fake module specifier we use should be put through the import map, and the result of that should be passed to `insert_cached()` instead.

**Comment by kitsonk** [comment]
> I think the fake module specifier we use should be put through the import map, and the result of that should be passed to `insert_cached()` instead.

That sounds reasonable.

**Comment by caspervonb** [comment]
If https://github.com/denoland/deno/pull/9662 ends up landing we'll be removing the synthetic test module as a side effect.

**Comment by LukeChannings** [comment]
As a side note, I've found that I can work around this issue by being more specific with aliases:

```json
{
  "imports": {
    "/internal/": "../internal/",
    "/types/": "../types/"
  }
}
```

I'm not sure *why* this works, but it does.
