### ISSUE TITLE
Deno bundle not removing namespace used just for types

### ISSUE THREAD

**Issue by larrybahr** [denoland/deno#9289]
When trying to bundle my code for production it looks like a class and a namespace with the same name (used just for types) are not being merged. Using deno test all the tests pass and everything works fine. It is just the bundling that is breaking.

I know modules should be used over namespaces, but I think this case (type only namespaces) is valid since interfaces cannot be declared inside classes and for the sake of organization it is better to keep class types/interfaces in the same scope as the class. 

Here is a simple gist to reproduce https://gist.github.com/larrybahr/fc62c446b1a981649a518bcb6fc6eddf
So you can see what is happening quickly here is my code
```typescript
export class TestClass {
    public testMethod (args: TestClass.TestArgs)
    {
        return args.param1;
    }
}

declare namespace TestClass {
    export interface TestArgs {
        param1: boolean;
    }
}
```
and here is the build
```cmd
C:\>deno upgrade --canary --version=40fc5f55ea582755d221a3445a2f5f388845bc23

C:\>deno --version
deno 1.7.0+40fc5f5 (canary, x86_64-pc-windows-msvc)
v8 8.9.255.3
typescript 4.1.3

C:\>deno bundle https://gist.githubusercontent.com/larrybahr/fc62c446b1a981649a518bcb6fc6eddf/raw/6681247de5d66b74fe93eee6a571dc5ef3b12bb7/mod.ts
Bundle https://gist.githubusercontent.com/larrybahr/fc62c446b1a981649a518bcb6fc6eddf/raw/6681247de5d66b74fe93eee6a571dc5ef3b12bb7/mod.ts
Download https://gist.githubusercontent.com/larrybahr/fc62c446b1a981649a518bcb6fc6eddf/raw/6681247de5d66b74fe93eee6a571dc5ef3b12bb7/mod.ts
Check https://gist.githubusercontent.com/larrybahr/fc62c446b1a981649a518bcb6fc6eddf/raw/6681247de5d66b74fe93eee6a571dc5ef3b12bb7/mod.ts
class TestClass1 {
    testMethod(args) {
        return args.param1;
    }
}
var TestClass1;
(function(TestClass1) {
})(TestClass1 || (TestClass1 = {
}));
export { TestClass1 as TestClass };
```
Running the code in browser results in
![image](https://user-images.githubusercontent.com/8782684/105945921-d5195700-602b-11eb-8624-3d23cda0c745.png)

Edit:
Example updated to use `declare namespace` as suggested by https://github.com/denoland/deno/issues/9289#issuecomment-768040201

**Comment by kitsonk** [comment]
Deno [doesn't support `namespace`](https://deno.land/manual@v1.7.0/typescript/faqs#why-are-you-forcing-me-to-use-isolated-modules-why-can#39t-i-use-const-enums-with-deno-why-do-i-need-to-do-export-type).

What happens when you change it to `declare namespace`?

That being said, we should see if we can error there instead of just failing.

**Comment by larrybahr** [comment]
Thanks for the quick suggestion, but the output is the same with or without `declare`.

I knew that namespaces where not supported, but I thought I could uses them for types since no code should be created for them.

Is there a better way to encapsulate the types created for a single class? My use case is that some of the method args are complex objects and I would prefer to use an interface as opposed to in lining them in multiple places.

**Comment by Soremwar** [comment]
You could export the interface as well, that way you don't have to declare it inside the class or inline them

**Comment by larrybahr** [comment]
That is true, but it is not as organized. When importing types from multiple libraries you could also run into collisions (e.g. constructorArgs is an OKish name, but is likely to be used by other libs). I have been doing my class interfaces like this for years, because of the issues I ran into when trying to consume the types from internal libs and 3rd party libs.

**Comment by kitsonk** [comment]
@kdy1 I know swc doesn't support `namespace` (nor would I want it to) but is it possible when bundling to just elide and `namespace` nodes from the emit?

**Comment by kitsonk** [comment]
> When importing types from multiple libraries

`import type` should allow you to rename things locally, just like other imports, the advantage of modular code...

**Comment by kdy1** [comment]
Swc supports namespace but I forgot handling type-only namespaces.

I'll add support for it soon.

**Comment by Soremwar** [comment]
JavaScript allows you to rename exported items, so you can coordinate exported symbols with same names to suit your needs

```js
import { ConnectionParams } from "randomlib";
import {
  ConnectionParams as InternalConnectionParams,
} from "./config.ts";
```

However I'm quite sure that the issue you reported initially is a bug, namespaces should only emit code on cases like enum declaration

**Comment by larrybahr** [comment]
That will work great for me and I cannot believe I did not think of `import type`. I guess I still have a few habits to break from the days of importing Definitely Typed packages in all my nodejs projects. 😅

Thank you all for your feed back, it helped a lot!

**Comment by kdy1** [comment]
Fixed it at upstream.

`cargo update -p swc_ecma_transforms_typescript` will fix the issue.

**Comment by bartlomieju** [comment]
Done in https://github.com/denoland/deno/pull/9374
