### ISSUE TITLE
Is it possible to run subprocess in the background?

### ISSUE THREAD

**Issue by lukejagodzinski** [denoland/deno#9300]
Hey, I've look for the similar problem in stackoverflow and here in the repository but I haven't found anything. I hope it's not a duplicate.

I'm running subprocess command using code like this:

```ts
const process = Deno.run({ cmd, stdout: "piped", stderr: "piped" });

const buffer = await process.output();
const str = new TextDecoder().decode(buffer);
console.log(str);

process.close();
```

The command that I'm running is "persistent"/"not exiting" and it doesn't close but just waits for the connections and then it displays some data to the output. However, Deno expects subprocess to close and then display some data. I've also tried iterating over `stdout` with `Deno.iter` but the same effect - nothing is logged to the console.

How can I run "persistent"/"not exiting" subprocess and still be able to get output whenever something is written to stdout?

**Comment by nayeemrmn** [comment]
Detached subprocess are tracked in #5501. But I think you just don't want to pipe the streams:
```ts
const process = Deno.run({ cmd });
await process.status();
```

**Comment by lukejagodzinski** [comment]
Oh so it's not implemented yet. Thanks for info!

And thank you for the suggestion about not piping streams. It's actually a good enough solution for now :) Thanks!

**Comment by nayeemrmn** [comment]
> I've also tried iterating over `stdout` with `Deno.iter` but the same effect - nothing is logged to the console.

This should have also worked. Could you share the code that you used? Otherwise, you can close this issue if everything works.

**Comment by lukejagodzinski** [comment]
It was something like that:

```ts
const process = Deno.run({ cmd, stderr: "piped", stdout: "piped" });
  for await (const buffer of Deno.iter(process.stdout)) {
    const str = new TextDecoder().decode(buffer);
    console.log(str);
  }
  process.close();
```

It would probably work if I didn't pipe. Closing this issue. Thanks again!
