### ISSUE TITLE
chore: skip CI for PRs that make changes to .md files

### ISSUE THREAD

**Issue by satyarohith** [denoland/deno#9304]
Does it make sense to skip CI for PRs that make changes to `*.md` files or am I missing something?

**Comment by meszarosdezso** [comment]
`*.md` files get formatted during the CI runs. As you can see in #9303, I added _one single character_ to the doc, and it made the CI fail. (:

**Comment by caspervonb** [comment]
Yeah linting and fmt checks still takes place so branching in the workflow would just convolute things more when we should try to simplify it (quite a bit of branching currently).

**Comment by satyarohith** [comment]
> Yeah linting and fmt checks still takes place so branching in the workflow would just convolute things more when we should try to simplify it (quite a bit of branching currently).

Agree. Probably not worth it. Closing the issue for time being.
