### ISSUE TITLE
Busy: Resource is unavailable because it is in use by a promise calling Deno.consoleSize

### ISSUE THREAD

**Issue by andykais** [denoland/deno#9315]
I am not completely certain this is a bug, but I see this error intermittenly when calling `Deno.consoleSize`. I do not know what causes it. It appears to happen randomly (the terminal is not resizing or anything when this error happens). This is the error:
```
error: Uncaught (in promise) Busy: Resource is unavailable because it is in use by a promise
    throw new ErrorClass(res.err.message);
          ^
    at processResponse (deno:core/core.js:212:11)
    at Object.jsonOpSync (deno:core/core.js:235:12)
    at Object.consoleSize (deno:runtime/js/40_tty.js:7:17)
    at progress_callback (ffmpeg-templates.ts:60:30)
    at copied_options.progress_callback (ffmpeg-templates.ts:106:54)
    at ffmpeg (mod.ts:763:9)
    at async render (mod.ts:937:3)
    at async render_sample_frame (mod.ts:951:10)
    at async try_render_video (ffmpeg-templates.ts:113:9)
    at async ffmpeg-templates.ts:189:1
```

and it is caused in this block of code:

```ts
function progress_callback(execution_start_time: number, ffmpeg_progress: FfmpegProgress) {
  const { out_time, progress, percentage } = ffmpeg_progress
  const console_width = Deno.consoleSize(Deno.stdout.rid).columns
  // const unicode_bar = '\u2588'
  const unicode_bar = '#'
  const execution_time_seconds = (performance.now() - execution_start_time) / 1000
  const prefix = `${human_readable_duration(execution_time_seconds).padStart(4)} [`
  const suffix = `] ${(percentage * 100).toFixed(1)}%`
  const total_bar_width = console_width - prefix.length - suffix.length
  const bar = unicode_bar.repeat(Math.min(percentage, 1) * total_bar_width)
  const message = `\r${prefix}${bar.padEnd(total_bar_width, '-')}${suffix}`
  Deno.stdout.write(encoder.encode(message))
}
```
(specifically this line: `const console_width = Deno.consoleSize(Deno.stdout.rid).columns`). 

`deno --version` info:
```
deno 1.7.0 (release, x86_64-unknown-linux-gnu)
v8 8.9.255.3
typescript 4.1.3
```

**Comment by bartlomieju** [comment]
I presume this function is called multiple times, if so then you're missing `async` before `Deno.stdout.write(encoder.encode(message))` which makes for intermittent failures of `Deno.consoleSize`. Also `Deno.stdout.write` is not guaranteed to write whole message in one go, you should probably use `Deno.writeAll` instead.

**Comment by ebebbington** [comment]
> I presume this function is called multiple times, if so then you're missing `async` before `Deno.stdout.write(encoder.encode(message))` which makes for intermittent failures of `Deno.consoleSize`. Also `Deno.stdout.write` is not guaranteed to write whole message in one go, you should probably use `Deno.writeAll` instead.

Sorry to interject, but I just wanted to mention, maybe the docblock/example in the API docs should be adjusted then to mention using `.writeAll` instead of `.stdout.write`?

**Comment by andykais** [comment]
thanks all. It seems like this was my issue so I will close this issue

**Comment by andykais** [comment]
as a follow up, can someone explain why `Deno.stdout.write` and `Deno.writeAll` are async, but `console.log` is not? Does that mean that console.log doesnt get flushed to stdout right away?
