### ISSUE TITLE
[docs] correct docs for a released version?

### ISSUE THREAD

**Issue by Songkeys** [denoland/deno#9317]
It seems that we have different tags for different versions which reflects on the dropdown on the doc website. Versions are tagged after releasing, but after that, we might need to complete more missing docs for this version. This "offset" makes version-to-doc relationship not accurate.

I noticed this problem when I want to find out the "Cross Compilation" for v1.7. But only "master" branch tells me how to do it, while v1.7 says "not currently possible". This is due to #9258 was merged into "master" branch rather than "v1.7" tag.

Any good thoughts we can make this better? If we want to add something to a released version?

**Comment by kitsonk** [comment]
The docs get updated when versions are released, which is appropriate.  If users are using a canary release, they should refer to the documentation that is part of the repo, as it is yet to be "published" and I think it is realistic to expect people to understand they are working on an experimental unpublished version.

Closing as unactionable.

**Comment by Songkeys** [comment]
@kitsonk I think you misunderstood what I was saying.

1. v1.7 was published as a stable version
2. Then it was tagged as v1.7
3. Then the docs about a feature in v1.7 is added to "master" branch
4. However the v1.7 tag is still missing that doc
5. So the doc website is misleading - if you select "v1.7" version of the doc, you won't see the new feature doc

**Comment by kitsonk** [comment]
That is a mistake then, one we will try to avoid in the future.
