### ISSUE TITLE
import relative dependencies from home ( using ~ )

### ISSUE THREAD

**Issue by JeremyJaydan** [denoland/deno#9320]
What if we could import relative to the user's home directory using `~`? 

e.g.
```javascript
import { parseFlags } from "~/lib/cli.js";
```
If my home directory is `/home/jeremy`, the above would import `/home/jeremy/lib/cli.js`.

could be useful for:
- sharing dependencies across projects
- a single place for potential package management tooling to interact with

**Comment by lucacasonato** [comment]
Thanks for the suggestion, but we will not implement this because it is not browser compatible (import specifier resolving follows URL semantics).

If you do want to do something like this, take a look at import maps.
