### ISSUE TITLE
[Doubt] Version handling

### ISSUE THREAD

**Issue by darklight9811** [denoland/deno#9322]
This is actually a doubt I have about some aspects/good practices about Deno.

# Multiple versioning
What is the best practice to handle imports of the same module in multiple files? For example, I have a module that declares a global that you can add data into. If I import two or more versions, it creates that global data for each version. Kinda breaking the purpose. With node, that would be handled by `package.json`.

# Semantic version scaling
How can I handle automatic version update inside the semantic versioning? (non breaking changes 0.0.x)

**Comment by Soremwar** [comment]
> I have a module that declares a global that you can add data into.
Jesus. We have many conventions to do that, the most famous ones being deps.ts and import maps (they give you a node like experience, but for optimizing deps I find deps.ts way superior).

https://deno.land/manual@v1.7.1/examples/manage_dependencies
https://deno.land/manual@v1.7.1/linking_to_external_code/import_maps

> Semantic version scaling
Ah yes, the illusion that someone will respect a made up convention for publising packages.

Straight answer, it works exactly the same as in Node. You trust the library publisher to not have broken anything and just bump the version. However no specific versioning convention is the default in Deno. It's up to every publisher to decide how to do this process.

However it's a best practice to always version your imports. While some people might think this is a good idea
```js
import {readLines} from "https://deno.land/std/io/mod.ts"; //Yay, now I get automatic updates when I run with --reload
```

ALWAYS version your imports, or at least use a lock file to guarantee that you are actually importing whatever you did the first time around

```
import {readLines} from "https://deno.land/std/io@0.85.0/mod.ts"; //Boring module, guaranteed to never change unless I change the version myself
```

**Comment by darklight9811** [comment]
@Soremwar, in case about worrying about people respecting semantic versioning, this is more about the packages that I'm making, and since I know I will respect it, I wanted to know if I could use that.

About the import map, I didn't see it, thx <3
