### ISSUE TITLE
Mapped coverage reporting quirk caused by lack of mappings

### ISSUE THREAD

**Issue by caspervonb** [denoland/deno#9328]
Take the following simple function:

```ts
export function foo()
{
  console.log("foo");
}
```

Newlines get stripped on compilation so this gets compiled to the following:

```js
export function foo() {
  console.log("foo");
}
```

Annotating where each mapping is with the `|` character for visualisation it looks something like the following

```js
|export |function |foo|() {
  |console|.|log|(|"foo"|)|;|
|}
```

Note the parameter list and opening paren don't get any mappings.

What happens with coverage is that it'll look up if line 2 in the original has been mapped to anything in the compiled source and since there are no mappings it'll assume it's part of non executable declaration like an interface.

This seems to apply to only function declarations but all of them (arrow functions, and nested or not does not matter).

Both swc and tsc seem to agree on this but cc @kdy1 if you have any insights as to why this is the case.

**Comment by kdy1** [comment]
It's because and both of swc and tsc is compiler.
To provide source mapping for an opening paren, span of it should be stored, but swc and tsc uses AST, not CST.

For example, swc stores parameters as

`Vec<Param>`, not `Params {
   opening: Span,
   params: Vec<Param>,
   closing: Span,
}`.

**Comment by caspervonb** [comment]
Hmm parameters; yeah suppose there's no node with a span for that.

But what about the body a function? there is a node for that when parsed with tsc at-least and it has the correct span yet it there is no mapping for it?

**Comment by kdy1** [comment]
There are mapping for it, namely in `BlockStmt`. Does swc drop mapping of it?

**Comment by caspervonb** [comment]
> There are mapping for it, namely in `BlockStmt`. Does swc drop mapping of it?

Seems both swc and tsc seem to drop the opening paren, but do emit mappings for the closing one.
Basically given this:

```ts
function foo() // this line is in the mappings.
{ // I can't find any mappings that have this line as the the source line.
} // this line is also in the mappings.
```

**Comment by bartlomieju** [comment]
I tried this again and reported coverage is 100%, so this is no longer issue. Most likely fixed by https://github.com/denoland/deno/pull/13334
