### ISSUE TITLE
Mongo Connection Error on runtime

### ISSUE THREAD

**Issue by NaderBhrr** [denoland/deno#9329]
Hello
I have tried to run a project on deno, but I receive the following error when trying to run it using "deno"

```javascript
error: Uncaught Error: MongoError: "Connection failed: Connection refused (os error 111)"
        throw new MongoError(`Connection failed: ${e.message || e}`);
              ^
    at MongoClient.connect (client.ts:93:15)
    at async db.ts:5:12

```
### Note:
I have tried it several times but the problem still persists.

Thanks in advance

**Comment by caspervonb** [comment]
Better raise this with the mongo library you're using instead.

**Comment by NaderBhrr** [comment]
Thank you for the feedback, I did as you suggested.
