### ISSUE TITLE
Error code 5 when upgrading while LSP is running

### ISSUE THREAD

**Issue by MierenManz** [denoland/deno#9331]
On windows deno upgrade gives OS error 5 when the LSP is still running

**Comment by kitsonk** [comment]
Having the lsp running is like having a serve in Deno running and trying to upgrade the binary.  So I don't think the error can be avoided, but I suspect with the upgrade we should look for any running `deno` processes on the machine and inform the user to terminate them before attempting the upgrade.

**Comment by MierenManz** [comment]
wouldn't it be possible that the lsp get closed when you type `deno upgrade`?

**Comment by kitsonk** [comment]
No, because it is vscode that is executing Deno as a seperate process which it manages.

**Comment by piscisaureus** [comment]
Maybe it is possible to terminate the deno LSP process after upgrading? I'm pretty sure vscode will just restart it when that happens.

**Comment by kitsonk** [comment]
> Maybe it is possible to terminate the deno LSP process after upgrading? I'm pretty sure vscode will just restart it when that happens.

Yes, if it does terminate, vscode will attempt to restart it up to 5 times.  Not sure what other LSP clients do, but I suspect it would be similar.  It would only fail if the user under which the upgrade occurs doesn't have rights to terminate the processes.  I suspect we should warn that we are terminate running existing Deno processes.

**Comment by lucacasonato** [comment]
I don't think this happens anymore. We have not gotten reports about this in a long time.
