### ISSUE TITLE
rename --inspect-brk to --inspect-break

### ISSUE THREAD

**Issue by timreichen** [denoland/deno#9344]
I was wondering if the deno run option `--inspect-brk` should be renamed to `--inspect-break` since non of the other flags are abbreviated and it would be more expressive. I think 13 over 15 chars does not make the difference.
Maybe it could be aliased and then `--inspect-brk` could be dropped with the 2.0 release?

**Comment by kitsonk** [comment]
While it is poorly named `--inspect-brk` is aligned to other Chrome based inspectors.  My opinion is changing this breaks more expectations than it fixes.  We should have wider consensus before #10366 is merged.  @ry @bartlomieju @lucacasonato thoughts?

**Comment by lucacasonato** [comment]
I would prefer to keep current naming. It aligns with node, and is already widely known.

**Comment by timreichen** [comment]
@lucacasonato while it is true that it aligns with node, this proposal is more about the aesthetics of cli, which makes no functional difference but I think is really important as well and deno has the opportunity to be aesthetically more pleasing than node.
Even if someone coming from node types `--inspect-brk`, cli will probably throw `Did you mean --inspect-break` no?

**Comment by jsejcksn** [comment]
```
deno run --👀-✋
```
😅
