### ISSUE TITLE
`deno compile` keeps failing with export anonimous default functions

### ISSUE THREAD

**Issue by oscarotero** [denoland/deno#9346]
The bug reported here #9250 is not fixed yet.

I have the following script:

```js
import log from "./log.js";

cli();

export default async function cli() {
    log("It works!");
}
```

That imports the following code:

```js
export default function (message) {
  console.log(message);
}
```

After compile and run it, I get this error:
```
error: ReferenceError: Cannot access '__default' before initialization
    at cli (file://$deno$/bundle.js:6:5)
    at file://$deno$/bundle.js:1:1
```

Checking with `deno bundle` the output code is the following:

```js
cli();
const __default = function(message) {
    console.log(message);
};
async function cli() {
    __default("It works!");
}
export { cli as default };
```

As you can see, `cli()` is executed before define `__default`.

If I set a name to the function in log.js:

```js
export default function log (message) {
  console.log(message);
}
```

The ouput code of `deno bundle` is a bit different:

```js
function log(message) {
    console.log(message);
}
cli();
async function cli() {
    log("It works!");
}
export { cli as default };
```

As you can see, the function is defined before `cli()`, its name is `log` instead `__default` and it's declared instead assigned to a variable. As possible solution could be build a similar code, independently of whether the function has name or not:

```js
function __default(message) {
    console.log(message);
};
cli();
async function cli() {
    __default("It works!");
}
export { cli as default };
```

**Comment by kdy1** [comment]
FIxed on upstream

**Comment by bartlomieju** [comment]
Done in https://github.com/denoland/deno/pull/9374
