### ISSUE TITLE
[bug] generic dynamic module import

### ISSUE THREAD

**Issue by darklight9811** [denoland/deno#9349]
When I try to import a module dynamically

``` typescript
await import ("./file.ts");
```

Throws the following error:
``` log
error: Dynamically imported module evaluation is still pending but there are no pending ops. This situation is often caused by unresolved promise.
error Command failed with exit code 1.
```

This error is too generic, I can't seem to find where this bug is being cause (if it's actually this import that I'm making, or how to solve it.

**Comment by lucidNTR** [comment]
@darklight9811  why was this issue closed? It seems to still be the same error message in the latest release and this really needs at least the import path of the pending module to debug...

**Comment by bartlomieju** [comment]
Will be fixed in https://github.com/denoland/deno/pull/10385

**Comment by lucidNTR** [comment]
sorry i did not see it was fixed in that PR : )
