### ISSUE TITLE
Error handler always reads error.stack, regardless of type (and blows up)

### ISSUE THREAD

**Issue by qoh** [denoland/deno#935]
The uncaught error handler seems to always try to display the `stack` property of the caught value, regardless of whether that value is an instance of `Error` or even an object at all.

This can either just be confusing:

```
$ cat object.ts
throw {};
$ deno object.ts
Compiling /.../object.ts
undefined
```

Or worse, fail entirely:

```
$ cat null.ts
throw null;
$ deno null.ts
Compiling /.../null.ts
ERROR RS - 
```

It isn't good practice to throw values that aren't instances of `Error`, but it happens.

**Comment by kitsonk** [comment]
For comparision, this is what Node.js does:

```
$ node
> throw {};
Thrown: [object Object]
> throw null;
Thrown: null
> 
```

And Chrome:

```
throw {};
VM121:1 Uncaught {}
(anonymous) @ VM121:1
throw null;
VM137:1 Uncaught null
(anonymous) @ VM137:1
```
