### ISSUE TITLE
Use generics when handling tsc reponses

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#9354]
We should be using generics as part of the processing when we handle responses back form tsc in code, so that the JSON values automagically get deserialized.

**Comment by sno2** [comment]
Hi, do you know where the code is that you are referencing?

**Comment by kitsonk** [comment]
Yes I do, this issue though was just to help me to remember something I needed to do.

**Comment by kitsonk** [comment]
This refactoring actually has been done, forgot we did it.
