### ISSUE TITLE
[docs] add benchmark for bundle & compile modes

### ISSUE THREAD

**Issue by Songkeys** [denoland/deno#9355]
Since v1.7, we have two modes for production environment: **bundle mode** and **compile mode**.

I'm deploying my deno web server to serverless platform, so I'm curious about how the different mode performs differently. Like, the **cold start time**, **execution time**, etc. I think the cold start time is the most concerning part.

Hope to see these benchmarks to be added to <https://deno.land/benchmarks> page.

**Comment by lucacasonato** [comment]
We don't have time to do this, but we have ran these benchmarks. Some examples: https://deno.com/blog/aws-lambda-coldstart-benchmarks
