### ISSUE TITLE
Number as properties are being transformed into strings

### ISSUE THREAD

**Issue by andreespirela** [denoland/deno#9356]
Deno (including both runtime and REPL):
![image](https://user-images.githubusercontent.com/60560109/106413589-73d0f980-6418-11eb-819a-9023f11b0c9e.png)

Chrome:
![image](https://user-images.githubusercontent.com/60560109/106413615-89462380-6418-11eb-9308-7571689ff9df.png)

**Comment by DjDeveloperr** [comment]
Same behavior on Chrome, Node and Deno.

![image](https://user-images.githubusercontent.com/43033058/106415297-c3451300-6474-11eb-9171-4806cf833113.png)

**Comment by andreespirela** [comment]
Closing as invalid

**Comment by caspervonb** [comment]
Indeed, working as intended.

This is because object keys have to be strings.
When you're passing it a number there it's just implicitly being stringified.

Looks like Chrome is doing some kinda tryParse thing when rendering.

**Comment by kitsonk** [comment]
> This is because object keys have to be strings.

Being pedantic, _or symbols_. 😄

**Comment by caspervonb** [comment]
> > This is because object keys have to be strings.
> 
> Being pedantic, _or symbols_. 😄

Fair enough, symbols are special cased in Deno.inspect tho.
