### ISSUE TITLE
cannot import (std/node/_crypto) randomBytes function without a trick

### ISSUE THREAD

**Issue by jd1378** [denoland/deno#9358]
Hi
I'm not sure if this is intended or even a bug, but I can't use deconstructing to import the randomBytes function from node/_crypto in std library in the way I use rest of std.

what worked for me looks like this:
```js
import { default as randomBytes } from "https://deno.land/std@0.85.0/node/_crypto/randomBytes.ts";
```
what I was expecting was:
```js
import { randomBytes } from "https://deno.land/std@0.85.0/node/_crypto/randomBytes.ts";
```
and `default` does not show up in intellisense

**Comment by caspervonb** [comment]
So `_crypto` is not public, hence the underscore.

See https://deno.land/std@0.85.0/node/crypto.ts instead.

**Comment by jd1378** [comment]
right, sorry, didn't see in the search
