### ISSUE TITLE
Unable to catch error thrown inside async function

### ISSUE THREAD

**Issue by qoh** [denoland/deno#936]
```javascript
async function fn() {
	throw new Error("message");
}
async function call() {
	try {
		console.log("before await fn()");
		await fn();
		console.log("after await fn()");
	} catch (error) {
		console.log("catch");
	}
	console.log("after try-catch");
}
call().catch(error => console.log("outer catch"));
```

```
$ deno async-fn.ts
Compiling /.../async-fn.ts
before await fn()
Error: message
    at fn (file:///.../async-fn.ts:2:8)
    at call (file:///.../async-fn.ts:7:9)
    at eval (file:///.../async-fn.ts:14:1)
    at DenoCompiler.eval [as _globalEval] (<anonymous>)
    at DenoCompiler._gatherDependencies (deno/js/compiler.ts:214:10)
    at DenoCompiler.run (deno/js/compiler.ts:560:12)
    at denoMain (deno/js/main.ts:72:12)
    at deno_main.js:1:1
```

---

If `fn` is synchronous instead, it works fine:

```diff
- async function fn() {
+ function fn() {
```

```
$ deno sync-fn.ts
Compiling /.../sync-fn.ts
before await fn()
catch
after try-catch
```

I thought it might be related to #919, but this also happens with my own build of master after that was closed.

**Comment by kevinkassimo** [comment]
I think it is probably related to the following code:
https://github.com/denoland/deno/blob/ffb41e61f138a683aac5fd89e0dd72b720c929d6/libdeno/binding.cc#L394-L400
From the [doc](https://v8.paulfryzel.com/docs/master/classv8_1_1_isolate.html#a702f0ba4e5dee8a98aeb92239d58784e), it seems that the handler could also [fire another event saying that a handler is later added](https://v8.paulfryzel.com/docs/master/namespacev8.html#a307b3674d4966684f8170a4fbd932eaf)

This is probably a related Node issue: https://github.com/nodejs/node/issues/1912

**Comment by kevinkassimo** [comment]
Okay so I think this is indeed the problem.
I did the following locally in `binding.cc`
```patch
void ExitOnPromiseRejectCallback(
    v8::PromiseRejectMessage promise_reject_message) {
  auto* isolate = v8::Isolate::GetCurrent();
  Deno* d = static_cast<Deno*>(isolate->GetData(0));
  DCHECK_EQ(d->isolate, isolate);
  v8::HandleScope handle_scope(d->isolate);
  auto exception = promise_reject_message.GetValue();
  auto context = d->context.Get(d->isolate);
+ printf("Promise reject try_catch caught, with %d\n", promise_reject_message.GetEvent());
- HandleException(context, exception);
}
```
The following is printed when running the provided code:
```
before await fn()
Promise reject try_catch caught, with 0
Promise reject try_catch caught, with 1
catch
after try-catch
```
From the [doc](https://v8.paulfryzel.com/docs/master/namespacev8.html#a307b3674d4966684f8170a4fbd932eaf), `0` should correspond to `kPromiseRejectWithNoHandler` and `1` corresponds to `kPromiseHandlerAddedAfterReject`. So for some reason V8 first complains about promise rejection, but then decides that actually it is already handled...

@ry

**Comment by kevinkassimo** [comment]
@ry I created an [experimental branch](https://github.com/kevinkassimo/deno/commit/a60f3d45df162e3e1dd9481ff93af175c55aab29) to play around with this issue (I am not familiar with v8 so would definitely make some mistakes).
However, my attempt seems somehow fixed the issue (now with the intended output), but is also causing a test case to fail:
https://github.com/denoland/deno/blob/ffb41e61f138a683aac5fd89e0dd72b720c929d6/tests/async_error.ts#L1-L8
With my attempted fix, the output changes from
```
hello
before error
Error: error
    at foo ([WILDCARD]tests/async_error.ts:4:9)
    at eval ([WILDCARD]tests/async_error.ts:7:1)
    at DenoCompiler.eval [as _globalEval] (<anonymous>)
    at DenoCompiler._gatherDependencies (deno/js/compiler.ts:[WILDCARD])
    at DenoCompiler.run (deno/js/compiler.ts:[WILDCARD])
    at denoMain (deno/js/main.ts:[WILDCARD])
    at deno_main.js:1:1
```
to
```
hello
before error
world
Error: error
    at foo ([WILDCARD]tests/async_error.ts:4:9)
    at eval ([WILDCARD]tests/async_error.ts:7:1)
    at DenoCompiler.eval [as _globalEval] (<anonymous>)
    at DenoCompiler._gatherDependencies (deno/js/compiler.ts:[WILDCARD])
    at DenoCompiler.run (deno/js/compiler.ts:[WILDCARD])
    at denoMain (deno/js/main.ts:[WILDCARD])
    at deno_main.js:1:1
```
which actually matches the output if running under Node. All other tests passes as usual though.

Would like to know comments before submitting a possible PR.

**Comment by ztplz** [comment]
@kevinkassimo  Yes, I think this is the reason why the test is not normal.
