### ISSUE TITLE
"Unable to build http client error message" when specifying CA Cert using --cert

### ISSUE THREAD

**Issue by mmartinsky** [denoland/deno#9364]
I'm trying to run deno behind a corporate proxy, but running into a blocker regarding our certificates / proxy setup. I try to run the base command straight out (HTTPS_PROXY:PORT is using my correct proxy, masked for this issue - but the variables are being read appropriately)

```
machine:~ user$ deno run -L debug https://deno.land/std/examples/welcome.ts
DEBUG RS - deno_runtime::js:9 - Deno isolate init with snapshots.
DEBUG RS - deno_core::shared_queue:75 - rust:shared_queue:reset
DEBUG JS - args []
DEBUG RS - deno:969 - main_module https://deno.land/std/examples/welcome.ts
DEBUG RS - deno::file_fetcher:526 - FileFetcher::fetch() - specifier: https://deno.land/std/examples/welcome.ts
DEBUG RS - deno_runtime::permissions:694 - ⚠️️  Granted network access to "deno.land"
DEBUG RS - deno::file_fetcher:446 - FileFetcher::fetch_remote() - specifier: https://deno.land/std/examples/welcome.ts
DEBUG RS - deno_runtime::permissions:694 - ⚠️️  Granted network access to "deno.land"
DEBUG RS - deno::file_fetcher:365 - FileFetcher::fetch_cached - specifier: https://deno.land/std/examples/welcome.ts
Download https://deno.land/std/examples/welcome.ts
DEBUG RS - reqwest::connect:525 - starting new connection: https://deno.land/
DEBUG RS - reqwest::connect:393 - proxy(http://HTTPS_PROXY:PORT) intercepts 'https://deno.land/'
DEBUG RS - rustls::client::hs:89 - No cached session for DNSNameRef("deno.land")
DEBUG RS - rustls::client::hs:211 - Not resuming any session
DEBUG RS - rustls::client::hs:430 - ALPN protocol is None
DEBUG RS - rustls::client::hs:598 - Using ciphersuite TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
DEBUG RS - rustls::client::tls12:209 - ECDHE curve is ECParameters { curve_type: NamedCurve, named_group: secp256r1 }
DEBUG RS - rustls::client::tls12:508 - Server DNS name is DNSName("deno.land")
Sending fatal alert BadCertificate
error: error sending request for url (https://deno.land/std/examples/welcome.ts): error trying to connect: invalid certificate: UnknownIssuer
```

Fair enough, after some digging I found the `--cert` option. Retrying with our cert:

```
machine:~ user$ deno run -L debug --cert ~/certs/cert.pem https://deno.land/std/examples/welcome.ts
error: Unable to build http client
machine:~ user$ 
```

This is confusing to me. The cert is certainly valid for accessing other internal services, but more concerning is that the debugging gets short circuited - **I don't have a lot of visibility as to why the http client failed to build other than that I added this cert to the command**. Is there a way to debug the underlying issue with why deno doesn't like my cert? I would at least expect the BadCertificate error if it was invalid.

```
machine:~ user$ deno --version
deno 1.7.1 (release, x86_64-apple-darwin)
v8 8.9.255.3
typescript 4.1.3
```

**Comment by bnoordhuis** [comment]
I opened #9380 to improve the error message. I'd be curious to know what it prints for you because I wasn't actually able to make it fail.

**Comment by mmartinsky** [comment]
Thanks @bnoordhuis! New here - is there any sort of preview / snapshot published for an MR that I download, or is the best way to test just building the branch from source a la https://deno.land/manual@v1.7.1/contributing/building_from_source?

**Comment by bnoordhuis** [comment]
@mmartinsky There are canary builds on https://dl.deno.land/ - #9380 should show up there soon.

Building from source is easy too, if you have rust+cargo installed. Clone the repo, check out submodules, and run `cargo build` - that'll build `target/debug/deno`.

**Comment by lucacasonato** [comment]
@mmartinsky You can upgrade to the specific canary that fixed it with `deno upgrade --canary --version fb358380c0570103619b0ce71c7fcb1b5a17986c`
