### ISSUE TITLE
existsSync crashes on long path

### ISSUE THREAD

**Issue by JoanaBLate** [denoland/deno#9365]
Running on Linux 5.4.0-58-generic

```
"use strict"

import { existsSync } from "https://deno.land/std@0.85.0/fs/exists.ts"

const filename = "bug".repeat(250)

console.log(existsSync(filename))

/*
error: Uncaught Error: File name too long (os error 36)
    at processResponse (deno:core/core.js:223:11)
    at Object.jsonOpSync (deno:core/core.js:246:12)
    at Object.lstatSync (deno:runtime/rt/30_fs.js:216:22)
    at existsSync (exists.ts:23:10)
    at file://*************:7:13
*/
```

Also, could existsSync be included in the deno builtin library?

Thanks

**Comment by servusDei2018** [comment]
In [Windows 10](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#maximum-path-length-limitation), the maximum file length is 260 characters. On Linux, max filename lengths depend on the filesystem but generally is no more than 255. Your code references a filename which cannot even logically exist; hence, this is not a bug.

**Comment by Soremwar** [comment]
Even though the file name in itself is limited to 255-ish characters, this function receives a whole path that can be way longer than this 255 characters

**Comment by JoanaBLate** [comment]
The problem is I wrote a local server, for development, that crashes each time the URL is too long. The long URL entered as a mistake. But I think Deno should more robust and not crash. NodeJS does not crash in same situation.

**Comment by lucacasonato** [comment]
@JoanaBLate Where do you use the `exists` function? You should not be using it to check if a file exists before opening or editing it, instead you should just try to open / edit the file and handle any thrown errors. This is faster, and can help prevent race conditions. Example:

```js
// Bad:

let fileContents;
if (existsSync("./foo.txt")) {
  fileContents = Deno.readTextFileSync("./foo.txt");
}

console.log(fileContents);
```

```js
// Good:

let fileContents;
try {
  fileContents = Deno.readTextFileSync("./foo.txt");
} catch(err) {
  // we don't care about the error, so ignore it.
}

console.log(fileContents);
```

If you really need to use `exists` and you don't care about any errors, you should catch the error with a try catch block. The `exists` function in std is only there to check if a file exists or not. If the operation you are trying to do is invalid for another reason (for example badly formatted path), the `exists` function will propagate the error to the caller. The current implementation of `exists` is working as intended.

**Comment by JoanaBLate** [comment]
@lucacasonato

Thanks!
