### ISSUE TITLE
docs(style_guide/ts): prefer `interface` over `type` for object typings

### ISSUE THREAD

**Issue by sno2** [denoland/deno#9369]
I think that we should always prefer to use the `interface` over the `type` keyword for creating object types.  TypeScript has a way to declare only an object type definition, therefore I think we should be preferring it for its only use case.

**Comment by mvolkmann** [comment]
You may be correct, but can you explain why that is preferred?

**Comment by sno2** [comment]
> You may be correct, but can you explain why that is preferred?

It should be preferred because Microsoft specifically created the `interface` to define the shape of objects.  It also allows you to use the `extends` keyword to extend any given interface.  Finally, you are able to use the `implements` keyword for having a class implement a given interface.  This allows us to have a more ergonomic and understandable method which is follows the concepts of OOP better.

```ts
interface ReadFileOptions {
  fileLocation: string;
  /* ... */
}

interface ReadFileDepreciatedOptions extends ReadFileOptions {
  callback: () => void;
}

// instead of

type ReadFileOptions = {
  fileLocation: string,
};

type ReadFileDepreceiatedOptions = ReadFileOptions & {
  callback: () => void;
};
```

**Comment by mvolkmann** [comment]
In cases where I only want a collection of fields and don't need inheritance or methods, why is `interface` better than `type` which can also define the shape of an object? In my experience this is the most common case.

**Comment by sno2** [comment]
> In cases where I only want a collection of fields and don't need inheritance or methods, why is `interface` better than `type` which can also define the shape of an object? In my experience this is the most common case.

`interface` is only _objectively_ better than `type` because it was made to only define the shape of an object while allowing a better syntax for extending another `interface` and other OOP features.  The style guide includes other _objectively_ better things such as limiting each function parameters to only 3 and then using an `interface` for the rest of the options.  I have noticed that most of the code uses `interface`, so I thought this would be better in writing.

**Comment by 0kku** [comment]
>  It also allows you to use the `extends` keyword to extend any given interface. 

How is this better than extending `type`s using intersections (`&`)?

> Finally, you are able to use the `implements` keyword for having a class implement a given interface.

This is not exclusive to `interface`s. [Object types declared using `type` can also be used with `implements`.](https://www.typescriptlang.org/play?#code/C4TwDgpgBAYg9nKBeKBvAsAKCjqAzBALigDsBXAWwCMIAnAGiwF8BuLLAYwBsBDAZz5QAQj1pQAlhTBcIFCCWCD4iDNlwFEKACwAmNpiZYgA)

> This allows us to have a more ergonomic and understandable method which follows the concepts of OOP better.

[citation needed]

---

`interface` and `type` used to have more differences, but these days they have significant overlap. 

What `interface`s can do that `type`s can't:
- `interface`s implicitly merge with similarly named class definitions and other similarly named interfaces, which can be useful when declaring fields on classes that are not declared in the class definition but need to be in the type defs, and when you want to extend interfaces of a third party library.
- `this` is not allowed in `type`s, whereas you can use it in `interface`s to refer to the interface itself: 

```ts
inteface Foo {
  bar: 42,
  baz: this["bar"],
}
```

What `type`s can do that `interface`s can't:
- unions
- inline mapped type intersections
- primitive types

**Comment by sno2** [comment]
> > It also allows you to use the `extends` keyword to extend any given interface.
> 
> How is this better than extending `type`s using intersections (`&`)?

It is not better.  It is simply a method that is _objectively_ easier for people to understand.

> > Finally, you are able to use the `implements` keyword for having a class implement a given interface.
> 
> This is not exclusive to `interface`s. [Object types declared using `type` can also be used with `implements`.](https://www.typescriptlang.org/play?#code/C4TwDgpgBAYg9nKBeKBvAsAKCjqAzBALigDsBXAWwCMIAnAGiwF8BuLLAYwBsBDAZz5QAQj1pQAlhTBcIFCCWCD4iDNlwFEKACwAmNpiZYgA)

Sorry, I must be misremembering from a post a while ago.

> > This allows us to have a more ergonomic and understandable method which follows the concepts of OOP better.
> 
> [citation needed]

This is all in my opinion.  I think that it is more readable to do

```ts
interface Component {
  width: number;
  height: number;
  enableEvents: (enable: boolean) => void;
}

interface Button extends Component {
  label: string;
}
```

than

```ts
type Component = {
  width: number;
  height: number;
  enableEvents: (enable: boolean) => void;
};

type Button = Component & {
    label: string;
};
```

and the `interface` method looks just like how you can extend your classes with `extends`.

> `interface` and `type` used to have more differences, but these days they have significant overlap.
> 
> What `interface`s can do that `type`s can't:
> 
> * `interface`s implicitly merge with similarly named class definitions and other similarly named interfaces, which can be useful when declaring fields on classes that are not declared in the class definition but need to be in the type defs, and when you want to extend interfaces of a third party library.
> * `this` is not allowed in `type`s, whereas you can use it in `interface`s to refer to the interface itself:
> 
> ```ts
> inteface Foo {
>   bar: 42,
>   baz: this["bar"],
> }
> ```

Yup.

> What `type`s can do that `interface`s can't:
> 
> * unions
> * intersections (largely the same as `extends` for `interface`s, but allows some extra things like inline mapped types, for example)
> * mapped types
> * primitive types

Please note that I specifically said that we should ***prefer*** using `interface` for declaring object shape types with properties.  In all other cases, it is _completely fine_ to use the `type` keyword to define our types.  Therefore, the following would still follow this style rule:

```ts
interface PersonData {
  name: string;
  age: number;
}

type PersonDataDraft = Partial<PersonData>; // we can also do this and assign `createPerson`'s `data` parameter's type to it as usual

function createPerson(data: Partial<PersonData> = {}) { // we can use mapped types inline
  /* ... */
}


```

**Comment by kitsonk** [comment]
As you can see from the conversation here, it isn't clear cut.  We have gotten along so far without making firm statements about this in the style guide, and I don't see a compelling need to add them now.  So respectfully decline.
