### ISSUE TITLE
1.7.1: Deno emit removing ambient functions/classes

### ISSUE THREAD

**Issue by SRNV** [denoland/deno#9373]
I need to expose some classes and functions on a ambient way and to avoid them to be erased by the tree shake I put an export statement
but in 1.7.1 these functions and classes are renamed when they are exported so it's like they doesn't exist (a number is added).

so there's like two problems:
- all exports are renamed
- tree shaking is good but need to be configurable IMO (sometime we need to set what code is exposed and important)

seen into 1.7.1
```typescript
// this part of the code is bundled
// A.ts
import things from '...';
export function A() {...} // renamed to A1
function B() {...} // removed
// etc...

// this part of the code is added
A(); // throws because the function A is renamed to A1
B(); // undefined
```
1.7.0 works well

**Comment by kitsonk** [comment]
Could you provide a complete reproduction.

**Comment by SRNV** [comment]
**./dep.ts**
```typescript
export default {};
```
**./runtime.ts**
import defaultObj from './dep.ts';
```typescript
export function renamedFunction() {
  return null;
}

function erasedFunction() {
  return defaultObj;
}
```

**./mod.ts**
result to 
```typescript
const anotherPartOfCode = `
  const defaultObj = erasedFunction() // throws
  renamedFunction() // throws
`;

const runtimeCode = await Deno.emit('./runtime.ts', {
  check: true,
});
const browserCode = `
  ${runtimeCode}
  ${anotherPartOfCode}
`;
console.log(browserCode) // =>
// ...
function renamedFunction1() {
  return null;
  }
  const defaultObj = erasedFunction() // throws
  renamedFunction() // throws
```
