### ISSUE TITLE
All built in runtime/js/*.js, op_crates/**/*.js, core/*.js should run in strict mode

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#9375]
All the internal runtime files should start with `"use strict";` to force them to use strict mode. Currently they are all running in sloppy mode.

**Comment by shadowtime2000** [comment]
I think I could take a go at this.

**Comment by pawanakhil** [comment]
@shadowtime2000 hey buddy.  I am a newbie to open source contributions. It would be very helpful if you would let me work on this issue. Please.

**Comment by shadowtime2000** [comment]
@pawanakhil Sure, my PR had a ton of formatting issues because of my VSCode and I don't think I will be able to find time to fix those for a while.

**Comment by lucacasonato** [comment]
Closed by #9391
