### ISSUE TITLE
test: bad assumption in cli/tests/unit/fetch_test.ts

### ISSUE THREAD

**Issue by bnoordhuis** [denoland/deno#9379]
https://github.com/denoland/deno/blob/9690ce5e872f1873538b8cea7c93fa3ea8bfd9d1/cli/tests/unit/fetch_test.ts#L23-L34

The test assumes it won't be able to connect to port localhost:4000. Surprise! On my system there's something listening there.

Not sure how to best fix this but picking a port number that isn't an obvious Schelling point is probably a good first step. :-)

**Comment by DavidDeSimone** [comment]
My initial thought for this was to check if the port is available via a call to listen - if you can an AddrInUse error, just try the next port up. Repeat that process until you find an available port and then fetch on that port.

The only issue I see with that approach is that there is a small timing window between calling close on your listening connection, and calling fetch. In that time, another process could snag that port, and you would see this issue. However, that timing window is really small and specific, and overall I think that approach is better then trying a specific port that may or may not have something already listening on it.

**Comment by bnoordhuis** [comment]
That's already a step up from the status quo. Do you want to send a PR?

**Comment by DavidDeSimone** [comment]
I'll submit a PR for this later today.
