### ISSUE TITLE
Deno.emit elides imports not used in code

### ISSUE THREAD

**Issue by buttercubz** [denoland/deno#9386]
This error was debated on the discord channel, here is the recreation:

using deno 1.7.1

`test.ts`
```typescript
import Root from "./Root.svelte";

let count: number = 1;

$: doubled = count * 2;
$: quadrupled = doubled * 2;

function handleClick(): void {
  count += 1;
}
```
`app.ts`
```javascript
const { files, diagnostics } = await Deno.emit("./test.ts", {
  check: false,
  compilerOptions: { checkJs: false },
});

console.log({ files, diagnostics });
```
`output`
```
diagnostics: []
files: {
  "file:///C:/Users/buttercubz/Desktop/test/test.ts.js.map": '{"version":3,"sources":[<file:///C:/Users/buttercubz/Desktop/test/test.ts>"],"sourcesCo...',
    "file:///C:/Users/buttercubz/Desktop/test/test.ts": "let count = 1;\n$: doubled = count * 2;\n$: quadrupled = doubled * 2;\nfunction handleClick() {\n    cou..."
  }
}
```
`file:///C:/Users/buttercubz/Desktop/test/test.ts.js`
```javascript
let count = 1;

$: doubled = count * 2;
$: quadrupled = doubled * 2;

function handleClick() {
  count += 1;
}
```
i'm spect that throws an error why .svelte files are not supported for Deno.emit

**Comment by kitsonk** [comment]
`Root` isn't being used anywhere in the module. TypeScript by default elides imports which are unused. What happens if you use `Root` in your code? If you have an import that you want just the side effects for, just do:

```ts
import "./Root.svelte";
```

**Comment by buttercubz** [comment]
I am trying to create a plugin to transpile the typescript code into the[ .svelte](https://svelte.dev/examples#nested-components) components, the syntax that svelte uses to import the components is ESM, so when I try to transpile the typescript code `Deno.emit` ignores the components because their reference is not made in the script but in the component template.

```svelte
<script>
  import Nested from './Nested.svelte';
         ^^^^^^
</script>

<style>
 p {
  color: purple;
  font-family: 'Comic Sans MS', cursive;
  font-size: 2em;
 }
</style>

<p>These styles...</p>
<Nested/>
 ^^^^^^
```
If I refer to the import within the `Deno.emit` script, it does not ignore the component import, ask within discord about how to disable tree shaking within `Deno.emit` so that the amounts that are not referenced are not removed from the final transpile. but i understand that it is not possible to disable tree shaking

**Comment by kitsonk** [comment]
It isn't tree shaking, it is import eliding and it is a feature of TypeScript. If you just want type stripping consider using the `"check": false` option. It should leave the import untouched.

**Comment by buttercubz** [comment]
I have done the test again leaving the check option in false and it continues to eliminate the import.
`test.ts`
```typescript
import Root from "./Root.svelte";

let count: number = 1;

$: doubled = count * 2;
$: quadrupled = doubled * 2;

function handleClick(): void {
  count += 1;
}
```
`app.ts`
```typescript
const { files, diagnostics } = await Deno.emit("./test.ts", {
  check: false,
});

console.log({
  file: files["file:///C:/Users/buttercubz/Desktop/test/test.ts.js"],
  diagnostics,
});
```
`output`
```javascript
{
  file: "let count = 1;\n$: doubled = count * 2;\n$: quadrupled = doubled * 2;\nfunction handleClick() {\n    cou...",
  diagnostics: []
}
```
I also did the test in deno 1.7.2 and had the same result

**Comment by kitsonk** [comment]
Ok, it appears there is consistency between tsc and the no check emit, in that code that is imported that isn't used in the module that is imported is elided.  This is the behaviour of "transpiling" TypeScript.  It has nothing to do with the fact that the file ends in `.svelte`.

This is a design "limitation" if you will.  Ultimately if you need to import something and give it a local symbol which the code doesn't use, you will need to do post processing of the emit.

**Comment by buttercubz** [comment]
that makes sense to me, I'm going to remove the imports that are from `.svelte` components and add them after transpilation, thanks for the follow-up
