### ISSUE TITLE
deno 1.7 fmt checks markdown files by default

### ISSUE THREAD

**Issue by jeiea** [denoland/deno#9387]
## Reproducible steps
1. Create README.md with the following.
```
Remember, contributions to this repository should follow its contributing guidelines and code of conduct.
```
2. Run `deno fmt --check` in the same directory.

## Expected behavior
deno 1.6.3 emits the following.
```
Checked 0 file
```

## Actual behavior
deno 1.7.0, 1.7.1 emits the following.
```
from \\README.md:
1 | -Remember, contributions to this repository should follow its contributing guidelines and code of conduct.
1 | +Remember, contributions to this repository should follow its contributing
2 | +guidelines and code of conduct.
```

## Additional context

deno fmt help says:
```
OPTIONS:
        --check                    Check if the source files are formatted
        --ext <ext>                Set standard input (stdin) content type [default: ts]  [possible values: ts, tsx, js, jsx, md]
```
`--ext ts` didn't work. I think it's a regression.

This blocks [this pull request](https://github.com/denofn/denopack/pull/48).

**Comment by nayeemrmn** [comment]
This is expected behaviour. We got markdown support for `deno fmt` and it's enabled without flags. The `--ext` specifies how to interpret stdin, as it says.

**Comment by jeiea** [comment]
Do you have desirable solution for this? I can't sure deno's markdown formatting is acceptable to every repository. Is there any option for this?

**Comment by nayeemrmn** [comment]
> Do you have desirable solution for this? I can't sure deno's markdown formatting is acceptable to every repository. Is there any option for this?

It should be if they are using `deno fmt`, just run `deno fmt`.

**Comment by Soremwar** [comment]
Add `//deno-fmt-ignore-file` to the markdown
