### ISSUE TITLE
watchFs is not abortable

### ISSUE THREAD

**Issue by magnattic** [denoland/deno#9399]
Right now there is no way to cancel a watch on the file system.

This function will never return and is not abortable from the outside:
```typescript
async function* onDbChange(dbPath: string) {
  console.log(`Watching for changes to ${dbPath}...`);
  const watcher = Deno.watchFs(dbPath);
  for await (const event of watcher) {
    if (event.kind === 'modify') {
      yield;
    }
  }
}
```

Possible solution would be to pass an `AbortSignal`:

```typescript
Deno.watchFs(dbPath, { signal });
```

**Comment by lucacasonato** [comment]
It is abortable. Call `watcher.close()`.

**Comment by jsejcksn** [comment]
> Call `watcher.close()`

This method is undocumented.

https://doc.deno.land/builtin/stable#Deno.watchFs

**Comment by kt3k** [comment]
`watcher.close` also seems throwing runtime error. It seems that the correct way to do that is `Deno.close(watcher.rid)`. I'm going to open a PR to fix the typing of it.

**Comment by jsejcksn** [comment]
> It seems that the correct way to do that is ~`Deno.close(watcher.rid)`~ `watcher.return()`

Just a note for anyone else looking at this issue: `Deno.close(watcher.rid)` does work and is called by `watcher.return()` internally:

https://github.com/denoland/deno/blob/48659c374d769b877905827362387da48cf57a9c/runtime/js/40_fs_events.js#L5

https://github.com/denoland/deno/blob/48659c374d769b877905827362387da48cf57a9c/runtime/js/40_fs_events.js#L36-L39
