### ISSUE TITLE
lsp should support formatting md files

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#9415]
We support `deno fmt README.md` since Deno 1.7. We should also enable the LSP to format MD files.

**Comment by kitsonk** [comment]
Yeah, I was trying to figure out how to do that without doing the whole support for the documents.

**Comment by KotlinIsland** [comment]
Doesn't deno fmt format all MD files?

**Comment by kitsonk** [comment]
Yes, but integrating it from an language server perspective is more complicated, which is why this issue is open.
