### ISSUE TITLE
Feature: Strongly typed deserialization of JSON ops

### ISSUE THREAD

**Issue by jbellerb** [denoland/deno#9422]
I've been messing with deno_core a bit and I found it a bit strange that JSON ops only work on loosely typed serde_json::Values given serde is capable of directly converting between JSON and Rust types. This can be changed by simply updating the type signatures of json_op_sync/async. Since serde_json::Value implements Deserialize/Serialize, very little code needs to be changed, however as json_op_sync/async are now generic, type inference is broken in some cases (see [cli/build.rs:146](https://github.com/denoland/deno/commit/643303694360f9152ca6cb52ccab8a044f560044#diff-fa76844bfec3519648a2d7493933ff3317fa3250dd913cc26d0e86b3b5d4465aR146)).

Since the changes required for this feature are so simple, I've made them on a [fork](https://github.com/jbellerb/deno/tree/generic_json_ops) of deno (which can be upgraded to a PR if there is interest) for testing. I've also updated the [deno_core examples](https://github.com/denoland/deno/commit/4782f3ec8d0232cd14222ab67dead9f94f0e4f28) and found that this change removed a lot of boilerplate. Finally, since serde now has more information about the types it is working with, serialization and deserialization should be faster, but I don't have benchmarks to back up that claim. Is there any interest in making this change? Thanks.

**Comment by lucacasonato** [comment]
Please open a PR to discuss this further. Sounds interesting - benchmarks would be nice.

**Comment by jbellerb** [comment]
I've created a PR (#9423) . I'll try to get some basic benchmarks based on [http_bench_json_ops](https://github.com/denoland/deno/blob/master/core/examples/http_bench_json_ops.rs) soon.
