### ISSUE TITLE
lsp: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists

### ISSUE THREAD

**Issue by ynwd** [denoland/deno#9425]
Deno: 1.7.2
Extension: Canary v0.0.8

PS:
No issue when use v2.3.3

![Screenshot from 2021-02-06 20-39-31](https://user-images.githubusercontent.com/10122431/107119619-72417e80-68bb-11eb-827a-7f1aa91368d6.png)

**Comment by aadamsx** [comment]
I'm still seeing this:

```
 $ deno --version
deno 1.8.2 (release, x86_64-apple-darwin)
v8 9.0.257.3
typescript 4.2.2
```

![image](https://user-images.githubusercontent.com/5341158/112758916-476bd080-8fb6-11eb-87bf-1fdbef0ba37f.png)

**Comment by kitsonk** [comment]
As you can see from the code, the `react` import us not resolved, because of that, the types for intrinsic elements are not being set. Deno does not support bare specifiers without an import map. You need to set an import map that properly resolves `react` if you wish to import it that way.

**Comment by vanjaoljaca** [comment]
How do you "set an import map" that "properly resolves react"? This is default behavior of create-react-app-deno

**Comment by AntonOfTheWoods** [comment]
@vanjaoljaca , unless you found something (please post if you did!), I'm guessing this is because the `vscode_deno` extension doesn't know how to deal with `TSX` properly. Obviously things run fine using `deno-create-react-app run` but a lack of TSX support for vscode is likely a massive drag on uptake of deno... Probably not an issue for this repo though.

**Comment by yohanstesfaye** [comment]
I do know why but when I add 
```TSX
/** @jsx h */ 
```
In the first line of the document, it will fix it.

**Comment by YYX-KISS** [comment]
或许可以尝试一下在setting.json中指定tsconfig.json的路径来解决。
[JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.](url)

**Comment by MrJ0se** [comment]
currently im pointing for types of npm as a temporary workaround for this problem, in deps.ts of /x/create_react_app template...

<deps.ts>
`
// @deno-types="./node_modules/@types/react/index.d.ts"
import * as React from "https://jspm.dev/react@17.0.0"
`

**Comment by MrJ0se** [comment]
@YYX-KISS  this remove the alert, but the jsx types ill be all any... so, i found that adding types with npm in deps.ts of the deno-react-app template is better...

`// @deno-types="./node_modules/@types/react/index.d.ts"`
![ref](https://user-images.githubusercontent.com/37480421/189483082-1b18696a-2581-479d-8090-67b3de364795.png)
seems works well...

**Comment by MrJ0se** [comment]
![image](https://user-images.githubusercontent.com/37480421/189483581-cfac67dd-1381-4290-b856-7fb863c83819.png)
and the little workaround for the deno-react-app:
```ts
//React.ts
import {React} from './deps.ts';
export default React;
```

**Comment by MrJ0se** [comment]
+1 obs.: this method need too to change the node like imports of the d.ts file to "deno like"... as:
```
// react/index.d.ts
/// <reference path="global" />

import * as CSS from 'csstype';
import * as PropTypes from 'prop-types';
import { Interaction as SchedulerInteraction } from 'scheduler/tracing';
```
to
```ts
/// <reference path="./global.d.ts" />

import * as CSS from '../../csstype/index.d.ts';
import * as PropTypes from '../prop-types/index.d.ts';
import { Interaction as SchedulerInteraction } from '../scheduler/tracing.d.ts';
```
among other files... (~5) to fix all types and run...

**Comment by reggi** [comment]
I just had to figure this out:

> deno.json
```
{
  "compilerOptions": {
    "jsx": "react-jsx",
    "jsxImportSource": "preact"
  },
  "importMap": "./import_map.json"
}
```

> import_map.json
```
{
  "imports": {
    "preact": "https://esm.sh/preact@10.11.2",
  }
}
```

**Comment by theowenyoung** [comment]
It seems not working on Deno 1.31.1

**Comment by bielsesa** [comment]
I created a new fresh app today and yes, it seems it's not working with Deno 1.31.1 as @theowenyoung said

![image](https://user-images.githubusercontent.com/43356045/222371541-7ddc2a55-ebcb-4eb5-9094-a5b4c4068565.png)

The import_map.json file

```json
{
  "imports": {
    "$fresh/": "https://deno.land/x/fresh@1.1.3/",
    "preact": "https://esm.sh/preact@10.11.0",
    "preact/": "https://esm.sh/preact@10.11.0/",
    "preact-render-to-string": "https://esm.sh/*preact-render-to-string@5.2.4",
    "@preact/signals": "https://esm.sh/*@preact/signals@1.0.3",
    "@preact/signals-core": "https://esm.sh/*@preact/signals-core@1.0.1",
    "twind": "https://esm.sh/twind@0.16.17",
    "twind/": "https://esm.sh/twind@0.16.17/"
  }
}
```

And the deno.json file

```
{
  "tasks": {
    "start": "deno run -A --watch=static/,routes/ dev.ts"
  },
  "importMap": "./import_map.json",
  "compilerOptions": {
    "jsx": "react-jsx",
    "jsxImportSource": "preact"
  }
}
```

deno --version

![image](https://user-images.githubusercontent.com/43356045/222371803-8fc3eadd-8c90-4303-b607-37e84432602f.png)

I am working in a devcontainer so I don't know if that affects anything

**Comment by theowenyoung** [comment]
This is an error from  esm.sh , see: 

- https://github.com/denoland/fresh/issues/1052
- https://github.com/ije/esm.sh/issues/534

now it fixed, please `--reload` your deno dependencies.

```bash
deno run --reload -A main.ts
```

**Comment by tunnckoCore** [comment]
The above seems to not work.

Especially because there are some weird `*` in the `esm.sh` links for the preact packages. It not make sense to me why they are there. Plus, it fails to run.

```
error: The source code is invalid, as it does not match the expected hash in the lock file.
  Specifier: https://esm.sh/*preact-render-to-string@5.2.4
```

Solution:

1. Remove the deno.lock if you have one
2. Put `--reload` to your `start` script.
3. Clean the cache with `deno cache --reload dev.ts` and for the `main.ts`
4. Run, then remove the `--reload`

Seems to work now. The in-editor errors disappeared.

**Comment by tunnckoCore** [comment]
Okay... put again all the `*` but this time to all the `preact` packages from the import map.

Also, if you are using Fresh, put the `import { h, Fragment { from 'preact';` in _all_ your jsx/tsx files. No `@jsx` pragma, no `@jsxSourceImport preact` and etc.

**Comment by dv1651st** [comment]
I got this same error. When I created the Fresh project, it was inside a different folder which I had opened inside of VS Code. I would just cd into the Fresh project folder and run deno start task. The problems went away once I opened into the Fresh project folder directly from VS Code. Seems like a bug that should be fixed.

**Comment by TheYuriG** [comment]
If you are getting this issue when trying to start or upgrade a project after Fresh 1.2, make sure you run once and restart the deno language server, because your issue might just be that your files are not yet cached to resolve JSX.

**Comment by cirne** [comment]
I struggled with this for a couple hours, finally found something that made the problem go away for me: From the VSCode Command Palette, select "Deno: Cache Dependencies". Voila, all those noisy errors gone.

https://share.getcloudapp.com/bLuZQ19E

**Comment by dv1651st** [comment]
> I struggled with this for a couple hours, finally found something that made the problem go away for me: From the VSCode Command Palette, select "Deno: Cache Dependencies". Voila, all those noisy errors gone.
> 
> https://share.getcloudapp.com/bLuZQ19E

Are you really using light mode? 😛

**Comment by fhucko** [comment]
I found that adding this import helped, even though VSC shows it is unused:
`import * as JSX from "https://esm.sh/react@18.2.0/jsx-runtime";`
Without this, deno check returns errors.
To avoid VSC showing unused import, i changed it to export like this:
`export * as JSX from "https://cdn.jsdelivr.net/npm/react/jsx-runtime/+esm";`

**Comment by Si3rr4wow** [comment]
Running `deno check` fixed it for me, just ran it against the root file of my project. Credit to @sant123 for [this comment](https://github.com/denoland/deno/issues/20582#issuecomment-1727309469)

**Comment by scriptmaster** [comment]
For react projects:
```
/// <reference path="https://unpkg.com/@types/react@18.2.39/index.d.ts" />
```

Adding this to the top of the .tsx file resolved the intrinsic types error.

Wait for a few seconds or do:
VS Code command `> Deno: Restart Language Server`

---

On react projects, this is the compiler options setting in `deno.json`

```
    "compilerOptions": {
        "jsx": "react-jsx"
    }
```
For preact projects it will be different.

---

You could also do (then you may get a blue indicator about redirection, then specify the latest react@x.y.z version)
```
/// <reference path="https://unpkg.com/@types/react/index.d.ts" />
```

**Comment by rtbarnes** [comment]
If you googled this error after setting up the VSCode extensions while setting up a Fresh project for the first time, first try what I did:

**Make sure you open the workspace to the folder your Fresh project is in.**

For example, I have a `~/dev` folder on my machine. I wanted to try out deno, so I made a `~/dev/denotest` folder. I opened VSCode to the `~/dev/denotest` folder. Then I scaffolded out a new Fresh project in there, inside `~/dev/denotest/fresh-project`. 

I was getting the error this thread is about in all of the `.tsx` files. All I needed to do was open ~/dev/denotest/fresh-project` as a VSCode workspace instead.
<img width="867" alt="image" src="https://github.com/denoland/deno/assets/25183392/4d191fff-c3c6-4916-8c80-3ee9b56c0829">

**Comment by revgum** [comment]
I'm using preact and preact-render-to-string alongside htmx. After bumbling through the various options and then finding this issue.. I went with;

```
// deno.json
{
  "compilerOptions": {
    "jsx": "react-jsx",
    "jsxImportSource": "preact"
  },
  "importMap": "./import_map.json"
}

// import_map.json
{
  "imports": {
    "preact": "https://esm.sh/preact@10.19.3",
    "preact-render-to-string": "https://esm.sh/preact-render-to-string@6.3.1",
    "preact/jsx-runtime": "https://esm.sh/preact@10.19.3/jsx-runtime"
  }
}
```

**Comment by felipezarco** [comment]
After trying all of the above it finally worked by:

👉🏻  **Opening the fresh folder directly with VSCode ** as pointed out by @rtbarnes 

Basically, you have now a folder above the fresh project, like this:
![image](https://github.com/denoland/deno/assets/11004919/6033573d-ca0a-4733-bf4f-15f3662d34c1)

It will work if you just open the fresh generated folder as the project workspace, like this:
![image](https://github.com/denoland/deno/assets/11004919/4f0ea669-b4a3-465e-af8f-0f90d64e2575)

So this pretty much closes the issue.

**Comment by ooker777** [comment]
Make sure you have a `deno.json` file at **the root of the web source** (not the root of your project). If you use `deno.jsonc`, or [Changing the source directory | Fresh docs](https://fresh.deno.dev/docs/examples/changing-the-src-dir "Changing the source directory | Fresh docs"), then there should be two `deno.json` file, one in the root of your project, and one in the root of the web source.

- Issue on this bug specifically: https://github.com/denoland/deno/issues/23223
- Duplicated (but newer) issue: https://github.com/denoland/deno/issues/20582

**Comment by 3498972895** [comment]
> Follow documentation at https://docs.deno.com/runtime/manual/advanced/jsx_dom/jsx. There are multiple options, the least intrusive seems to be having deno.jsonc with this (at least for for react):
> 
> ```
>   "compilerOptions": {
>     "jsx": "react-jsx",
>     "jsxImportSource": "https://esm.sh/react@18.2.0"
>   }
> ```
works 2024-08, use deno run -A npm:create-vite-extra

**Comment by sant123** [comment]
@3498972895 please can you share the whole deno.json?

**Comment by 3498972895** [comment]
> @3498972895 please can you share the whole deno.json?

{
  "tasks": {
    "dev": "deno run -A --node-modules-dir npm:vite",
    "build": "deno run -A --node-modules-dir npm:vite build",
    "preview": "deno run -A --node-modules-dir npm:vite preview",
    "serve": "deno run --allow-net --allow-read https://deno.land/std@0.157.0/http/file_server.ts dist/"
  },
  "imports": {
    "react": "npm:react@^18.2.0",
    "react-dom": "npm:react-dom@18.2.0"
  },

  "compilerOptions": {
    "allowJs": true,
    "esModuleInterop": true,
    "experimentalDecorators": false,
    "inlineSourceMap": true,
    "isolatedModules": true,
    "jsx": "react-jsx",
    "jsxImportSource": "react",
    "lib": ["dom"],
    "module": "esnext",
    "moduleDetection": "force",
    "strict": true,
    "target": "esnext",
    "useDefineForClassFields": true
  }
}

This is my deno.json file.  notice that you must use import from  "imports".
I use deno run -A npm:create-vite-extra command.

**Comment by 3498972895** [comment]
> @3498972895 please can you share the whole deno.json?

I think the problem is 
Relative import path "react" not prefixed with / or ./ or ../ and not in import map from "file:///home/fukuda/code/react-component/src/main.tsx"deno(resolver-error).
file in src works well, but the vscode propose the error. If I repalce them with "imports" from deno.json. the error is fixed. But If I only replace them with the same version of react from vite.config.mts. the browser console will throw an compatible error. It is very confused to me. 
But I just use it for react-leaning, I think it could be a problem of compatibility between vite and deno.

**Comment by 3498972895** [comment]
> @3498972895 please can you share the whole deno.json?

[deno.json](https://github.com/user-attachments/files/16756100/deno.json)
no problems.

**Comment by 3498972895** [comment]
> @3498972895 please can you share the whole deno.json?

[deno.json](https://github.com/user-attachments/files/16756172/deno.json)
I have modified it so many times, and now it seems no error when I reload windows. Hope it works for you too.

**Comment by sant123** [comment]
Just copied and pasted your deno.json but I'm getting:

![image](https://github.com/user-attachments/assets/f7dbb90b-5042-439e-8a5d-17f36185baa9)

😅

**Comment by 3498972895** [comment]
> Just copied and pasted your deno.json but I'm getting:
> 
> ![image](https://private-user-images.githubusercontent.com/7959437/361647303-f7dbb90b-5042-439e-8a5d-17f36185baa9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NDE5NTAsIm5iZiI6MTcyNDc0MTY1MCwicGF0aCI6Ii83OTU5NDM3LzM2MTY0NzMwMy1mN2RiYjkwYi01MDQyLTQzOWUtOGE1ZC0xN2YzNjE4NWJhYTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjdUMDY1NDEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWE5YWVlNThkNzkxYjAwMzAzMmMwNTA3MmRlZDQ2YzIxYmYxNTY4OThmODcxMDgzMjU1YjIxZTgwZDE3MmNiOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.kDvo271Wgf7EtHlSuT3nm3TspBvF6_N7B2-oHKnGGrI)
> 
> 😅

you fisrt recreate a project by npm:create-vite-extra, then choose the deno-react, typescript.
then run deno task dev,  then only keep write ‘hello world' in app.tsx. delete unrelated files in src like svg, app.css,... keep project simple.
second delete node module folder, deno.lock file. 
third, run deno clean command.
last, copy deno.json file. save and run deno task dev again.
just try many times... I have no good idea about this.

**Comment by 3498972895** [comment]
> Just copied and pasted your deno.json but I'm getting:
> 
> ![image](https://private-user-images.githubusercontent.com/7959437/361647303-f7dbb90b-5042-439e-8a5d-17f36185baa9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NDM5NzIsIm5iZiI6MTcyNDc0MzY3MiwicGF0aCI6Ii83OTU5NDM3LzM2MTY0NzMwMy1mN2RiYjkwYi01MDQyLTQzOWUtOGE1ZC0xN2YzNjE4NWJhYTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjdUMDcyNzUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDVjOTYxNTY0YzFiMjg3MTNhMTQzZjY4ZDcwNWYwOWFkZDIyOGY2N2U5ZTgxMjJkNGViYjY3MjQ0NTM5NjU2YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.GcF-ER4MKPifZVUDcmeYaLQU5wzktlRGiTfwRY_y3eo)
> 
> 😅

try use deno add npm:@types/react@^18.2.0 command. If you still have problem, I will put the simple demo in my repo.

**Comment by sant123** [comment]
The project keeps giving me errors. Do not worry @3498972895 perhaps in a future there will be better support for this.

**Comment by 3498972895** [comment]
> The project keeps giving me errors. Do not worry @3498972895 perhaps in a future there will be better support for this.

all right.  may be it will be fine when deno comes to 2.0 version.

**Comment by sant123** [comment]
@3498972895 thank you so much

**Comment by LylianPerson-Gay** [comment]
Based on the deno.json provided by @3498972895, adding `"jsxImportSourceTypes": "@types/react"` worked fine for me. I'm using deno 2.0.0.
Here is my deno.json :
```json
{
  "tasks": {
    "dev": "deno run --watch --allow-env --allow-net=0.0.0.0:8000"
  },
  "compilerOptions": {
    "jsx": "react-jsx",
    "jsxImportSource": "react",
    "jsxImportSourceTypes": "@types/react"
  },
  "imports": {
    "react": "npm:react@^19.0.0",
    "react-dom": "npm:react-dom@^19.0.0",
    "@types/react": "npm:@types/react@^19.0.1"
  }
}
```
https://docs.deno.com/runtime/reference/jsx/#jsximportsourcetypes

**Comment by 3498972895** [comment]
> Based on the deno.json provided by @3498972895, adding `"jsxImportSourceTypes": "@types/react"` worked fine for me. I'm using deno 2.0.0. Here is my deno.json :
> 
> ```json
> {
>   "tasks": {
>     "dev": "deno run --watch --allow-env --allow-net=0.0.0.0:8000"
>   },
>   "compilerOptions": {
>     "jsx": "react-jsx",
>     "jsxImportSource": "react",
>     "jsxImportSourceTypes": "@types/react"
>   },
>   "imports": {
>     "react": "npm:react@^19.0.0",
>     "react-dom": "npm:react-dom@^19.0.0",
>     "@types/react": "npm:@types/react@^19.0.1"
>   }
> }
> ```
> 
> https://docs.deno.com/runtime/reference/jsx/#jsximportsourcetypes

Recently the new version of deno has released, so I suggest you check the  documents.
