### ISSUE TITLE
Propose changes to the Deno.run() API

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#9431]
[Given unintuitive way of `Deno.run()` API usage](https://github.com/denoland/deno/issues/4568#issuecomment-772463496) I think we should consider changing that API for Deno 2.0.

Tokio provides a great abstraction for running subprocess by the means of [`Command`](https://docs.rs/tokio/1.1.1/tokio/process/struct.Command.html) and [`Child`](https://docs.rs/tokio/1.1.1/tokio/process/struct.Child.html) APIs
especially if user wants to just [run process to completion](https://docs.rs/tokio/1.1.1/tokio/process/struct.Command.html#method.status) or [run it to completion while collecting output](https://docs.rs/tokio/1.1.1/tokio/process/struct.Command.html#method.output).

Currently Deno APIs requires users to handle both situations manually; and I believe it's worth considering to add some helper methods.

Hereby I propose to align Deno's subprocess APIs to follow Tokio's API as closely as possible.

```typescript

// run process to completion
const command = new Deno.Command({
    cmd: ["ls"],
});
const status = await command.status();

// run process to completion, collecting output (will configure stdout/stderr to be piped automatically)
const command = new Deno.Command({
    cmd: ["ls"],
});
const status = await command.output();

// spawn a subprocess and return a handle to it
const command = new Deno.Command({
    cmd: ["ls"],
});
const subprocess = command.spawn();

// wait for subprocess to complete
const status = await subprocess.wait();

// check if subprocess has completed
const maybeStatus = subprocess.tryWait();

// wait for subproces to complete and collect output
const { status, stdout, stderr } = await subprocess.waitWithOutput();

// force subprocess to exit
await subprocess.kill();
```

With the proposed changes to the API all appropriate resources used to facilitate subprocess
would be automatically cleaned up (especially stdio resources), meaning that for the most popular
use cases users wouldn't have to remember to call `Deno.close()` on the resources. 

For more advanced use cases (eg. streaming data from stdout/stderr) there wouldn't be much difference
in the API usability besides changing API names.

**Comment by caspervonb** [comment]
You used a string for cmd here as a positional; so I assume this means a command with args can be created like this?

```ts
const cmd = new Command("ls", {
  args: ["-A"],
  env: { ... },
);
```

And just the options in general; since Rust's std and tokio use a builder pattern how do we do the options? still an options bag?

Also, do we keep `Deno.run` around as a convenience function (we don't have many but we do have some) for create a command and spawn a subprocess?

**Comment by caspervonb** [comment]
Also the program always has to be present right, so why not make that positional?

**Comment by bartlomieju** [comment]
> You used a string for cmd here as option; so I assume this means a command with args can be created like this?
> 
> ```ts
> const cmd = new Command({
>   cmd: "ls",
>   args: ["-A"],
>   env: { ... },
> );
> ```
> 
> And just the options in general; since Rust's std and tokio use a builder pattern how do we do the options? still an options bag?
> 
> Also, do we keep `Deno.run` around as a convenience function (we don't have many but we do have some) to create a command and spawn a subprocess with said command?

Actually not, I think the current `cmd` is fine. I'll update the examples.

**Comment by lucacasonato** [comment]
> ```ts
> // check if subprocess has completed
> const maybeStatus = subprocess.tryWait();
> ```

I feel like this should be `subprocess.status()` and return `Status | null`. `tryWait` doesn't really make much sense IMO.

**Comment by nayeemrmn** [comment]
> ```ts
> // check if subprocess has completed
> const maybeStatus = subprocess.tryWait();
> ```

We should avoid this one; I think it's an antipattern in JS. It can be done with `.then()`  closures instead.

**Comment by bartlomieju** [comment]
> > ```ts
> > // check if subprocess has completed
> > const maybeStatus = subprocess.tryWait();
> > ```
> 
> We should avoid this one; I think it's an antipattern in JS. It can be done with `.then()` closures instead.

Not sure I understand, the crux of this method is that it's sync and won't wait for process completion, currently there's no way in Deno API to check if process has already finished.



> > ```ts
> > // check if subprocess has completed
> > const maybeStatus = subprocess.tryWait();
> > ```
> 
> I feel like this should be `subprocess.status()` and return `Status | null`. `tryWait` doesn't really make much sense IMO.

What's wrong with `tryWait`? One of premises for this change is to follow Tokio's API as closely as possible including naming of APIs.

**Comment by lucacasonato** [comment]
> We should avoid this one; I think it's an antipattern in JS. It can be done with .then() closures instead.

Yeah - agree. Polling is very much an anti-pattern.

**Comment by nayeemrmn** [comment]
> Not sure I understand, the crux of this method is that it's sync and won't wait for process completion, currently there's no way in Deno API to check if process has already finished.

```ts
  const maybeStatus = null;
  subprocess.status().then(status => {
    maybeStatus = status;
  });
  
  // check if subprocess has completed
  if (maybeStatus != null) { ... }
```

**Comment by bartlomieju** [comment]
> > Not sure I understand, the crux of this method is that it's sync and won't wait for process completion, currently there's no way in Deno API to check if process has already finished.
> 
> ```ts
>   const maybeStatus = null;
>   subprocess.status().then(status => {
>     maybeStatus = status;
>   });
>   
>   // check if subprocess has completed
>   if (maybeStatus != null) { ... }
> ```

@nayeemrmn that's not really equivalent - calling `Child::wait` in Tokio API closes `stdin` handle automatically to avoid a deadlock, while `Child::try_wait` does not close `stdin`.

**Comment by nayeemrmn** [comment]
> calling `Child::wait` in Tokio API closes `stdin` handle automatically to avoid a deadlock

So is there no way to asynchronously listen for subprocess exit without closing stdin?

**Comment by bartlomieju** [comment]
> > calling `Child::wait` in Tokio API closes `stdin` handle automatically to avoid a deadlock
> 
> So is there no way to asynchronously listen for subprocess exit without closing stdin?

I believe so, at least that what `Child` docs say.
