### ISSUE TITLE
Reenable shutdown tests for net_test.ts

### ISSUE THREAD

**Issue by kevinkassimo** [denoland/deno#944]
Currently, tests are disabled for `netCloseReadSuccess`, `netDoubleCloseRead`, `netCloseWriteSuccess`, `netDoubleCloseWrite`. The tests always pass on my local machine (macOS), but it seems the behavior is different on other platforms. (I myself don't have a windows machine)

Add this issue to avoid forgetting about it & in case others would like to contribute and fix them

**Comment by sasurau4** [comment]
Is this still alive?
I'll work on this issue 👍

**Comment by ry** [comment]
@sasurau4 Sadly, yes. https://github.com/denoland/deno/blob/1386b6ead586da15d0285941f2d980acc1d75eee/js/net_test.ts#L171-L204
If you could look into it, that would be great.

**Comment by ry** [comment]
Feb 24, 2020 - still an issue. Shouldn't too hard to fix. We should rename `closeWrite` to `shutdown` probably.

**Comment by lucacasonato** [comment]
I think these tests can be reenabled now because of the recent with the resource table fixes.

**Comment by ry** [comment]
fixed in #9181
