### ISSUE TITLE
Uncaught (in promise) ReferenceError: Deno is not defined - when deno namespace is set to false in WebWorker

### ISSUE THREAD

**Issue by starkpsmichael** [denoland/deno#9446]
Don`t know how to reproduce this for now, but using a worker without deno namespace set to true is not possible for now, in some situations.

I mean it makes sense in the context that the error message is build with some "Deno stuff" - but this shouldnt be the case, when i dont allowed the deno namespace to be used at all.

Thrown Error: `"Uncaught (in promise) ReferenceError: Deno is not defined\n    return ${obj.constructor.name} ${Deno...",`

Feel free to look into this, for now its just a placeholder - will update this when i have more informations.

**Comment by bartlomieju** [comment]
This is expected error if `Deno` is not added to the worker scope, it's the exact same error as for any other not defined variable. 

Please provide reproduction code.

**Comment by nayeemrmn** [comment]
Ooh, that looks like an internal custom inspect error. I guess there is a reason to do https://github.com/denoland/deno/pull/9332#issuecomment-770534157 after all, as long as workers can disable the Deno namespace, which is unfortunate.

**Comment by bartlomieju** [comment]
> Ooh, that looks like an internal custom inspect error. I guess there is a reason to do [#9332 (comment)](https://github.com/denoland/deno/pull/9332#issuecomment-770534157) after all, as long as workers can disable the Deno namespace, which is unfortunate.

Good catch, that is indeed an internal bug.

**Comment by starkpsmichael** [comment]
Thx for looking into this @nayeemrmn. 👍🏻
