### ISSUE TITLE
why std/encoding/binary don't have encode & decode

### ISSUE THREAD

**Issue by gcxfd** [denoland/deno#9463]
why std/encoding/binary don't have encode & decode

Just like in nodejs Buffer.from(string, "binary") and buffer.toString("binary")

**Comment by zhangyuannie** [comment]
There are [TextEncoder](https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder) and [TextDecoder](https://developer.mozilla.org/en-US/docs/Web/API/TextDecoder).

You can use `new TextDecoder('latin1').decode(string)` which is functionally equivalent to `buffer.toString("binary")`.

Fortunately (or unfortunately), TextEncoder does not support anything other than `utf8` anymore. You can use `new TextEncoder().encode(string)` which is equivalent to `Buffer.from(string, "utf8")` instead.

Deno tries to stay close to the Web APIs, so this will probably not be included in `std`.

**Comment by gcxfd** [comment]
https://developers.google.com/web/updates/2012/06/How-to-convert-ArrayBuffer-to-and-from-String

I founded function from there

https://github.com/rmw-deno/blake3
```
import * as blake3 from '../pkg/blake3.js';
import * as hex from "https://deno.land/std/encoding/hex.ts";
import {encode} from "https://deno.land/std/encoding/utf8.ts"

function ab2str(buf) {
  return String.fromCharCode.apply(null, new Uint16Array(buf));
}

function str2ab(str) {
  var buf = new ArrayBuffer(str.length*2); // 2 bytes for each char
  var bufView = new Uint16Array(buf);
  for (var i=0, strLen=str.length; i < strLen; i++) {
    bufView[i] = str.charCodeAt(i);
  }
  return buf;
}

for(var i of ["hi", "test"]){
  var hash = blake3.hash(encode(i));
  console.log(`\n${i}`)
  console.log(hash);
  console.log(hex.encodeToString(hash));
  var bin=ab2str(hash.buffer);
  console.log(bin);
  console.log(new Uint8Array(str2ab(bin)));
}
```

**Comment by staticlibs** [comment]
> You can use `new TextDecoder('latin1').decode(string)` which is functionally equivalent to `buffer.toString("binary")`.

@zhangyuannie , please correct me, if I am missing something, but I think this part is misleading and "latin1" is not equivalent to "binary". For example:

```
> new TextDecoder("latin1").decode(new Uint8Array([142])).charCodeAt(0)
381
```

**Comment by zhangyuannie** [comment]
> > You can use `new TextDecoder('latin1').decode(string)` which is functionally equivalent to `buffer.toString("binary")`.
> 
> @zhangyuannie , please correct me, if I am missing something, but I think this part is misleading and "latin1" is not equivalent to "binary". For example:
> 
> ```
> > new TextDecoder("latin1").decode(new Uint8Array([142])).charCodeAt(0)
> 381
> ```

Yeah it is indeed misleading, however not exactly for the reason you mentioned. Let me explain.

First, "latin1" is indeed equivalent to "binary". You can see that in [Node](https://nodejs.org/docs/latest-v16.x/api/buffer.html#buffers-and-character-encodings), "binary" is an alias for "latin1"

The issue is that I made the mistake to assume that "latin1" of Web API is the real "latin1" codec (i.e. ISO/IEC 8859-1), like in Node.

Well, thanks to you, I now know that it is not the case 😅. In fact, [Web API](https://developer.mozilla.org/en-US/docs/Web/API/Encoding_API/Encodings) and thus deno view "latin1" as "windows-1252", which is different for most symbols in range 128 to 159.

### The fix

```js
const binary = new Uint8Array([142])
String.fromCharCode(...binary).charCodeAt(0) // 142
```

Let me know if this is good.

**Comment by staticlibs** [comment]
Thanks for the explanation, I've stumbled upon this recently and was surprised by the behaviour.

Something like this should be more robust:

```
function toBinaryString(buffer: ArrayBuffer): string {
  let result = "";
  let offset = 0;
  while (offset < buffer.byteLength) {
    const length = Math.min(buffer.byteLength - offset, 1<<10);
    const view = new Uint8Array(buffer, offset, length);
    const chunk = String.fromCharCode(...view);
    result += chunk;
    offset += length;
  }
  return result;
}
```

It may be a good idea to add something like this to `std/encoding/binary` for interaction with legacy API that expects [binary strings](https://developer.mozilla.org/en-US/docs/Web/API/DOMString/Binary).

**Comment by zhangyuannie** [comment]
I would suggest you to discuss more at [deno_std](https://github.com/denoland/deno_std) if you want this to be included in std.

A note that `buffer.toString("binary")` has already been ported to [std/node](https://github.com/denoland/deno_std/blob/d7bdbfa3ef606c21882d8489ca149f6a312c338c/node/_buffer.js#L968), a workaround would be to use that instead.
