### ISSUE TITLE
fetch() broken for all URLs 

### ISSUE THREAD

**Issue by jaredforth** [denoland/deno#9468]
I installed `Deno` today using [Cargo](https://crates.io/crates/deno) by running `cargo install deno` as specified in the documentation. However, the `fetch()` method is throwing the following error for all URLs: 

```
error: Uncaught (in promise) TypeError: error sending request for url (https://httpbin.org/get): error trying to connect: dns error: failed to lookup address information: Temporary failure in name resolution
    throw new ErrorClass(res.err.message);
          ^
    at processResponse (deno:core/core.js:213:11)
    at Object.jsonOpAsync (deno:core/core.js:230:12)
    at async sendFetchReq (deno:op_crates/fetch/26_fetch.js:1291:12)
    at async fetch (deno:op_crates/fetch/26_fetch.js:1379:25)
```

The endpoint (I am using https://httpbin.org/get here as an example) is accessible through Chrome and cURL, but Deno is not able to access it. I am running my file with the `--allow-net` flag and the full command is: `deno run --allow-net pageGenerator.ts`. Is it possible that there is a compile flag that needs to be passed when compiling Deno with Cargo? Am I missing something or is this a bug?

**Comment by lucacasonato** [comment]
Deno tries to use the nameservers specified in resolv.conf. Make sure these are accessible.
