### ISSUE TITLE
deno lint: empty object type is recognized as any type

### ISSUE THREAD

**Issue by c4spar** [denoland/deno#9469]
I wonder about the following lint error. 
```
(ban-types) if you want a type meaning `any object` use `Record<string, unknown>` instead,
or if you want a type meaning `any value`, you probably want `unknown` instead.
export class HelpCommand extends Command<{}, [command?: string]> {
                                         ^^
```
Because it makes a big difference if i use `Record<string, unknown>`, `unknown` or `{}`. Because i don't want to create an `any object` or a `any value`, but an object type without properties.

For example:
```typescript
const a: Record<string, unknown> = {}; // Can have any unknown properties.
const b: ThisType<void> = {}; // Does not have any properties (empty interface).
const c: {} = {}; // Does not have any properties (empty type).
const d: unknown = {}; // Could be a different type than an object.

if (a.test) {} // Does not throw an error.
if (b.test) {} // TS2339: Property 'test' does not exist on type 'ThisType '.
if (c.test) {} // TS2339: Property 'test' does not exist on type '{}'.
if (d.test) {} // TS2571: Object is of type 'unknown'.
```

The only way to workaround this is by using the build in `ThisType` interface or by disabling the lint rule:
```
class HelpCommand extends Command<ThisType<void>, [command?: string]> {}
// or:
// deno-lint-ignore ban-types
class HelpCommand extends Command<{}, [command?: string]> {}
```

If you try to create your own empty interface, you get this lint error.
```
(no-empty-interface) An empty interface is equivalent to `{}`.
interface Options {}
class HelpCommand extends Command<Options, [command?: string]> {}
```
But the `{}` type cannot be used because of this error:
```
(ban-types) if you want a type meaning `any object` use `Record<string, unknown>` instead,
or if you want a type meaning `any value`, you probably want `unknown` instead.
type Options = {};
class HelpCommand extends Command<Options, [command?: string]> {}
```

**Comment by magurotuna** [comment]
Not only deno_lint but also [typescript-eslint](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/ban-types.md) also emits that error message.
In short, the `{}` type doesn't mean "object without properties", but it means "any non-nullish value" effectively.
deno_lint suggests `Record<string, unknown>` because it is considered to be a general hint.

You may find the following links informative:
 https://github.com/denoland/deno_lint/issues/572
https://github.com/typescript-eslint/typescript-eslint/issues/2063#issuecomment-675156492

**Comment by c4spar** [comment]
Ah, i remember, there was some issues with the `{}` type. I think it was way too late for me yesterday 😄 
Thx for the quick response and detailed explanation @magurotuna! `Record<string, never>` works for me 👍

Will close this issue.

**Comment by c4spar** [comment]
**Just as note**: `Record<string, never>` didn't work at all for me.
Because it is still valid to check for none existing properties:
```typescript
const foo: Record<string, never> = {};
if (foo.bar) {} // <-- No error.
```
But i figured out, if i use `void`instead of `never`, ts will throw an error for none existing properties:
```typescript
const foo: Record<string, void> = {};
if (foo.bar) {} // <-- TS1345: An expression of type 'void' cannot be tested for truthiness.
    ~~~~~~~
```
But than it is possible to assign void values to any property.
```typescript
const foo: Record<string, void> = {};
foo.bar = test(); // <-- No error.
function test(): void {}
```

So i think it is just not possible to define an object type with realy no properties.

But i found a different solution for my problem:
```typescript
class Command<O = void> {
    option<T>(): Command<O extends void ? T : O & T> {
        return this as any;
    }
    action(fn: (options: O) => void): void {}
}

new Command()
    .option<{ foo: string }>()
    .option<{ bar: string }>()
    .action((options) => {
        if (options.foo) {}
    });
```
