### ISSUE TITLE
deno fmt deletes code sometimes with invalid syntax

### ISSUE THREAD

**Issue by 00ff0000red** [denoland/deno#9477]
I was writing some code, here's an example:

```js
const Methods {
  f: (x, y) => x + y,
};

export default Methods;
```

Look closely, notice how I forgot my assignment operator after "Methods."

`deno fmt` decides to, instead of throwing an error, eat the entire object, emitting this:
```js
const Methods;

export default Methods;
```

I'll test on an updated Deno, and canary right now.

___

Update: this affects 1.7.2, but I couldn't try canary; opened a new issue about that.

**Comment by 00ff0000red** [comment]
Seems to be fixed on SWC's side; closing here.

**Comment by kitsonk** [comment]
I would like to keep it open until we merge the version of dprint that this is fixed in.

**Comment by 00ff0000red** [comment]
Ah, okay, fine with me.

**Comment by 00ff0000red** [comment]
I'm not sure if it's related, but I've got another snippet where I got a comment deleted:
```js
const _ = [
  1,
  /* 2 */,
  3,
  4,
];
```

Can someone investigate?

**Comment by kitsonk** [comment]
It is a slightly different issue, so have opened a new issue.
