### ISSUE TITLE
Deno version 1.7.3 throwing error (version `GLIBC_2.29' not found) on start up under Debian 10

### ISSUE THREAD

**Issue by copyrighthero** [denoland/deno#9484]
After downloading the latest version of Deno 1.7.3 from GitHub, the binary throws the following error under Debain 10 64Bit:

`./deno: /lib/x86_64-linux-gnu/libm.so.6: version GLIBC_2.29' not found (required by ./deno)`

`uname` output:

`Linux 4.19.0-14-amd64 #1 SMP Debian 4.19.171-2 (2021-01-30) x86_64 GNU/Linux`

The binary is, however, functional under `Ubuntu 20.04 64Bit`.

**Comment by bnoordhuis** [comment]
Duplicate of #9478. It's probably caused by the system the binaries are built on.

**Comment by ry** [comment]
I have deleted the 1.7.3 release. We will release 1.7.4 soon that works on older glibc.
