### ISSUE TITLE
Please upload 1.7.3 releases

### ISSUE THREAD

**Issue by LitoMore** [denoland/deno#9492]
The GitHub Actions failed because the 1.7.3 release pack does not exist.

https://github.com/denolib/setup-deno/runs/1892711261?check_suite_focus=true

**Comment by LitoMore** [comment]
Or there is a problem with the method of calculating the latest version.

**Comment by crowlKats** [comment]
1.7.3 was taken down because of an error. it is being work on.

**Comment by LitoMore** [comment]
@crowlKats Thanks. I also created an issue for https://github.com/denolib/setup-deno/issues/81.

**Comment by LitoMore** [comment]
v1.7.4 is out. Closing.

**Comment by LitoMore** [comment]
v1.7.4 is out. Closing.

**Comment by LitoMore** [comment]
BTW, I decide to drop `denolib/setup-deno` from my project.

I look forward the GitHub Actions scripts from Deno official.
