### ISSUE TITLE
deno bundle: add some way to bundle type declarations

### ISSUE THREAD

**Issue by jajaperson** [denoland/deno#9495]
Deno bundle currently allows users to bundle typescript code to a single js file. It would be good to be able to bundle type declarations into a single d.ts file to go with it.

Currently, tools exist to make an npm project suitable for Deno, but not for going the other way. Allowing users to bundle a Deno library into two files, a `mod.js` and `mod.d.ts` would make this much easier.

**Comment by ebebbington** [comment]
Duplicate of https://github.com/denoland/deno/issues/3385
