### ISSUE TITLE
Workers with base64 URL can have a very large stacktrace

### ISSUE THREAD

**Issue by andreespirela** [denoland/deno#9501]
Note: While this is the expected behavior, what this ticket will only be a suggestion.

I have a worker which is created with a base64 of more than 3000 characters. If the worker throws an error, the parent will receive a huge stacktrace:
![image](https://user-images.githubusercontent.com/60560109/107869334-0f238f00-6e5b-11eb-9beb-c28456c89fdf.png)
which can take seconds to be written in stdout. 

My suggestion is, whenever a worker is created with a base64 URL, then it should have a fake path when generating an stacktrace, like `file://$deno.ts` for example.

**Comment by kitsonk** [comment]
How would you suggest differentiating from one base64 URL to another?

**Comment by kitsonk** [comment]
The best solution would be to use ellipses when printing out, something like `data:application/javascript;base64,ZXhwb3...KfQo=`.

**Comment by andreespirela** [comment]
> The best solution would be to use ellipses when printing out, something like `data:application/javascript;base64,ZXhwb3...KfQo=`.

I think this is the best as well, first 5 characters and last 5 characters.

**Comment by lucacasonato** [comment]
We truncate data URLs in stack traces now.
