### ISSUE TITLE
Deno.emit deprecate importMapPath option

### ISSUE THREAD

**Issue by timreichen** [denoland/deno#9502]
`Deno.emit` can take two options: `importMapPath` and `importMap`. Depending if one or both are used, their behavior is inconsistent:

`importMap` only: throws error since `importMapPath` for resolution is needed
`importMapPath` only: reads file and converts it to importMap
`importMapPath` and `importMap`: `importMap` is resolved with `importMapPath`

Proposal: deprecate `importMapPath` and have `importMap` be a fully resolved importMap.
To do so, we need a function that does the resolution.
```ts
function resolveImportMap(importMapPath: string, importMap: ImportMap) {
// …
}
```
Since importmap seems to become the standard (chrome has it now behind a flag: https://www.chromestatus.com/feature/5315286962012160) I think it would make sense to have a std/importmap repo for that.

**Comment by bartlomieju** [comment]
I'm strongly in favor of deprecating that option, user could load the import map themselves using `fetch` or `Deno.readTextFile`.

> I think it would make sense to have a std/importmap repo for that

I'm not sure I'm following; what would be in that repo?

**Comment by kitsonk** [comment]
@bartlomieju I'm not sure I follow the "deprecation" agreement bit. Users can already fetch their own import map and provide it.

**Comment by timreichen** [comment]
@bartlomieju a `resolveImportMap` function, since importmaps can have relative specifiers dependant on a baseURL.
And I guess it could also have a `resolve` function to resolve a path. My [importmap repo](https://github.com/timreichen/importmap) came in handy on multiple occasions already.
@kitsonk true, but why would special treat importmaps, since there is a way to provide a an importmap. Why should there be that implementation instead of one more line of code? compilerOptions also don't take string to a tsconfig.json file.

**Comment by kitsonk** [comment]
I've been thinking about this, and I am wondering if we could simply do this:

```
interface EmitOptions {
  importMap?: string | URL | ImportMap;
}
```

And if a `string | URL` then the import is resolved as if passed on the CLI using `--import-map` and if an import map object is supplied, it is assumed that the Deno CLI CWD is used as the base.  A little bit of documentation to make the behaviour clear, but simplifies things dramatically.

**Comment by timreichen** [comment]
@kitsonk I see what you mean, but I think `Deno.emit` should have as least abstractions as possible. Being able to pass a `string | URL` would be convenient, but I think deno would be better of providing the functions for the user to be able to do importmap resolutions themselves. After all, `Deno.emit` also requires compilerOptions to be an object, not a filepath to a tsconfig.json file. And providing a flexible importmap resolution solution would be neat anyway.

**Comment by kitsonk** [comment]
> After all, Deno.emit also requires compilerOptions to be an object, not a filepath to a tsconfig.json file.

Then you are arguing that we don't change anything, as `importMap` is required to be an object and `importMapPath` is required to be a string representing the location, physical or logical pointing at the `importMap`.\

The problem with the function is that it requires either resolution before sending to Rust or a callback from Rust into the runtime to then resolve it.  It is best to have all the configuration resolved without additional manipulations before op'ing to Rust.  As you are also realising with the `compilerOptions` comment, we don't have any callbacks for configuration at all.  Callbacks make it harder for people to consume the API.  Potentially having a callback in addition to an object literal and a string, maybe, but forcing people to only use callbacks I don't think is a good idea from a usability perspective.

**Comment by timreichen** [comment]
Maybe I didn't express well what I meant.

As far as I understood there are the following algorithms that the importmap specification specifies: 
- parsing (string to object, part 1 of https://wicg.github.io/import-maps/#parsing)
- sorting and normalizing importmap (with a baseURL, normalizes relative specifiers to absolute ones, part 2 of https://wicg.github.io/import-maps/#parsing)
- resolving module specifier (with a resolved importmap, https://wicg.github.io/import-maps/#resolving)

`parsing` is just parsing a json string to an object and validating it and is not of any importance of this particular discussion.

I argue that the `sorting and normalizing importmap` algorithm should be accessible by the user in a `std/importmap` module and `Deno.emit` should take an already sorted and normalized importmap instead of doing the resolution itself.

Once the importmap has been sorted and resolved the importmap is not dependent on a `importMapPath` anymore  because all relative paths have been resolved. This `resolved` importmap would then be passed to `Deno.emit`.

Reason: If there is another function that needs an importmap passed I think it is not a good practice to have the importmap resolved twice. 

```ts
import { resolveImportMap } from "https://deno.land/std/importmap/mod.ts"
const importMap = await Deno.readTextFileSync(…)
const baseURL = Deno.cwd()
Deno.emit(…, {
  importMap: resolvedImportMap
})
Deno.emit(…, {
  importMap: resolveImportMap(importMap, baseURL)
})
```
*Side note*: Alternatively, importMap functions could also be added in the deno namespace instead of std/importmap, like `Deno.resolveImportMap` to avoid the import statement.

**Comment by kitsonk** [comment]
If browsers don't allow you to hook the algorithms of import maps, we won't implement them.  It only causes divergent behaviour and requires quite intimate knowledge of how import maps work.  We will only continue to support the expression of import maps as they are expressed in a browser, (e.g. a JSON object with two keys).

**Comment by timreichen** [comment]
Closing this issue because `Deno.emit` is a 3rd party mod now.
