### ISSUE TITLE
Deno LSP does not accept Shebang using native Neovim LSP

### ISSUE THREAD

**Issue by David-Else** [denoland/deno#9507]
Deno LSP is working like a dream with the native LSP in Neovim https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md#denols apart from shebangs. They seem OK in VS Code, but in Neovim:
![Screenshot from 2021-02-14 21-20-47](https://user-images.githubusercontent.com/12832280/107889525-186c3480-6f0b-11eb-8177-65bb938dbf11.png)

**Comment by kitsonk** [comment]
could you provide the details of the diagnostic at that point?  I am not sure they are coming from the Deno LSP.

I am not sure how to access them in neovim, but a diagnostic should include a source and a code.  Both would be helpful in trying to figure out what is going on.  I suspect there is some other extension that is supplying the diagnostic.  What is there is valid JavaScript and TypeScript though according to the Stage 3 proposal which pretty much everyone has implemented: https://github.com/tc39/proposal-hashbang.

**Comment by David-Else** [comment]
I have good news, the error seems to have gone away with the latest version of Neovim and the associated LSP plugin.
