### ISSUE TITLE
Upgrade Deno Failure

### ISSUE THREAD

**Issue by gungunfebrianza** [denoland/deno#9513]
i am tryin to upgrade deno from my windows OS 64 bit

C:\WINDOWS\system32>deno upgrade
Looking up latest version
Found latest version 1.7.4
Checking https://github.com/denoland/deno/releases/download/v1.7.4/deno-x86_64-pc-windows-msvc.zip
Download has been found
Deno is upgrading to version 1.7.4
thread 'main' panicked at 'assertion failed: output.status.success()', cli\tools\upgrade.rs:254:3
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

C:\WINDOWS\system32>

**Comment by lucacasonato** [comment]
What us the current version of deno that you are using?

**Comment by gungunfebrianza** [comment]
deno 1.6.3

**Comment by gungunfebrianza** [comment]
hello just to update its success to install after i reinstall using choho on windows

**Comment by gungunfebrianza** [comment]
so the problem is when we call using upgrade command does not work on windows
