### ISSUE TITLE
data URLs not well handled in lsp

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#9514]
Data URLs are only partially handled in the LSP at the moment.  They first appear as "not found" until they are cached.  This feels like the right behaviour, though the code action and the diagnostic message could be more informative.

The problem is that the source is unavailable, and cannot be opened in the editor as a virtual text document.  This means that it is impossible to do goto definition and other "challenges" with using data URLs in the editor.

**Comment by heavenshell** [comment]
Hello!

>This means that it is impossible to do goto definition and other "challenges" with using data URLs in the editor.

Yes, this is very annoying.
I use `vim-lsp` with `deno lsp`.
Currently GoTo definition did not work well even if `deno cache` ran.

It would be very grad to GoTo proper cached file.

**Comment by lucacasonato** [comment]
@heavenshell Is this regarding `data:` urls specifically, or all cached urls?

**Comment by heavenshell** [comment]
> regarding data: urls or all cached urls?

What dose mean all cached urls?
Sorry I don't know about deno so much(I'm deno newbie 😉)

e.g.
```typescript
import { serve } from "https://deno.land/std@0.87.0/http/server.ts";
// my serve code
...
```

My cached `std@0.87.0/http/server.ts` file is `/path/to/cached/https/deno.land/f2c8b5dbf74ee5191a5ffbd0e14ccb8f76bf452fc3d615b1dad17e78b93e2d3`.


If deno can returns cached file path as targetUri, editor can open cached file.
`"targetUri":"file:///path/to/https/deno.land/f2c8b5dbf74ee5191a5ffbd0e14ccb8f76bf452fc3d615b1dad17e78b93e2d3"`

**Comment by lucacasonato** [comment]
Deno returns a URI with the prefix `deno://` in target URI of the response. All files that start with `deno://` should get their content using the deno text document provider (using the lsp command `deno/virtualTextDocument`). You can see how this is done for the official VS Code extension here: https://github.com/denoland/vscode_deno/blob/main/client/src/extension.ts#L141-L145. I am not sure how you would go about implementing something like this in `vim-lsp`. Also, lets hop onto [Discord](https://discord.gg/deno) for further discussion instead of hijacking this unrelated issue :-)

**Comment by heavenshell** [comment]
Thank you for response I'll look VSCode's code!

**Comment by kitsonk** [comment]
@heavenshell in fixing this, I realised the README for the LSP wasn't quite as informative as it needed to be.  I have updated the following:

---

## Custom requests

The LSP currently supports the following custom requests. A client should
implement these in order to have a fully functioning client that integrates well
with Deno:

- `deno/cache` - This command will instruct Deno to attempt to cache a module
  and all of its dependencies. If a `referrer` only is passed, then all
  dependencies for the module specifier will be loaded. If there are values in
  the `uris`, then only those `uris` will be cached.

  It expects parameters of:

  ```ts
  interface CacheParams {
    referrer: TextDocumentIdentifier;
    uris: TextDocumentIdentifier[];
  }
  ```
- `deno/performance` - Requests the return of the timing averages for the
  internal instrumentation of Deno.

  It does not expect any parameters.
- `deno/virtualTextDocument` - Requests a virtual text document from the LSP,
  which is a read only document that can be displayed in the client. This allows
  clients to access documents in the Deno cache, like remote modules and
  TypeScript library files built into Deno. The Deno language server will encode
  all internal files under the custom schema `deno:`, so clients should route
  all requests for the `deno:` schema back to the `deno/virtualTextDocument`
  API.

  It also supports a special URL of `deno:/status.md` which provides a markdown
  formatted text document that contains details about the status of the LSP for
  display to a user.

  It expects parameters of:

  ```ts
  interface VirtualTextDocumentParams {
    textDocument: TextDocumentIdentifier;
  }
  ```

**Comment by heavenshell** [comment]
Thank you!
I'll try to request `deno/virtualTextDocument`!

**Comment by fannheyward** [comment]
@kitsonk the data URIs has been changed:

In 1.7.4 and earlier LS returns `deno:///https/deno.land/x/mod.ts`
in 1.7.5 LS returns `deno:/https/deno.land/x/mod.ts`

I don't find the any _stand_ format in LSP, but from [vscode-uri](https://github.com/microsoft/vscode-uri), there may be two slashes like `deno:///https/deno.land/x/mod.ts`?

**Comment by yaegassy** [comment]
Thank you for reporting the issue to deno itself.

I modified the code of "deno" itself and build. https://github.com/denoland/deno/blob/main/cli/lsp/urls.rs#L95

### from

`format!("deno:/{}", path)`

### to

`format!("deno://{}", path)`

I'm not sure if this is an appropriate fix, but I will continue to watch this issue first. https://github.com/denoland/deno/issues/9514#issuecomment-783140787

**Comment by kitsonk** [comment]
Yes. The format changed, as vscode would modify the document URI. Now all responses which include a Uri should be replaysble back to the language server exactly as they were received. Ideally a client should never determine a `deno:` scheme URI itself outside of the status virtual document.

**Comment by fannheyward** [comment]
@kitsonk yes, the client should not determine the scheme, my question is :

1. 1.7.4 and earlier returns `deno:///` with three slashes
2. 1.7.5 returns `deno:/` with only one slash
3. from vscode-uri, maybe there should be _two_ slashes?

**Comment by kitsonk** [comment]
vscode was returning them as `deno:/` no matter how they were sent across, so it was changed so that what was sent was not modified by vscode. Vscode was also percent encoding some of the values. This was making it difficult to memoize the URLs the server was sending.
