### ISSUE TITLE
deno lint doesn't work with URLs

### ISSUE THREAD

**Issue by ry** [denoland/deno#9518]
```
> deno lint --unstable https://deno.land/x/oak@v6.4.2/router.ts
Checked 0 file
```
At minimum it should error out...

**Comment by caspervonb** [comment]
So `deno fmt` use the exact same code for file resolution and will have the problem.

If i recall correctly both of them just discard invalid paths that aren't paths on the file system instead of erroring out (happens in `fs_util::collect_files`).

**Comment by magurotuna** [comment]
I'll look into it.
