### ISSUE TITLE
Deno.exit should throw when called from a test

### ISSUE THREAD

**Issue by caspervonb** [denoland/deno#9528]
Originally mentioned in https://github.com/denoland/deno/issues/9213

Go recently introduced this behaviour

> When using go test, a test that calls os.Exit(0) during execution of a test function will now be considered to fail. This will help catch cases in which a test calls code that calls os.Exit(0) and thereby stops running all future tests. If a TestMain function calls os.Exit(0) that is still considered to be a passing test.

Which makes a lot of sense to me, calling exit will always mess up your test run and we should have a sanitizer to catch it.

I will be working on this.

**Comment by hayd** [comment]
It'd be great to configure exit behavior e.g. in deno-lambda an exit should throw an exception (to be caught) rather than end the process (which fatally times out the lambda).

**Comment by wperron** [comment]
@caspervonb do you think we can fix #9213 at the same time?
