### ISSUE TITLE
Allow --ignore to be used with directories and filenames containing a comma

### ISSUE THREAD

**Issue by caspervonb** [denoland/deno#9535]
This is the same issue as with `--allow-read` described in https://github.com/denoland/deno/issues/6553 but for the --ignore option.

Today, this wont work because we use a comma delimited list for this option:

```
mkdir "foo, bar, "baz"
deno lint --unstable --ignore="./foo, bar, baz"
```

I intend to change this to be a "multiple" option configuration so that we can pass in paths with commas, multiple will be specified by repeating the option:

```
mkdir "foo, bar, "baz"
deno lint --unstable \
  --ignore="./foo, bar, baz"
  --ignore="other directory"
```

Breaking change  CLI in multiple commands so probably 2.0.

**Comment by lucacasonato** [comment]
We'll use the same solution as https://github.com/denoland/deno/issues/6553#issuecomment-2324291087 here.
