### ISSUE TITLE
Naming convention for tool configs in Deno projects

### ISSUE THREAD

**Issue by ChristianGrete** [denoland/deno#9536]
Yesterday,  I have opened an issue (https://github.com/dprint/dprint/issues/342.) on the `dprint` repository after I found out that [they have changed their default config file name to `.dprintrc.json` because of Deno](https://github.com/dprint/dprint/issues/257).

I just want to raise the same questions in here:

According to the Deno Style Guide, Deno strives to [follow Rust conventions](https://deno.land/manual/contributing/style_guide#rust). Using Rust and Cargo, configuration files are usually non-hidden `.toml` files in project directories and hidden dot files in parent directories for global settings. This does make sense as you probably don't want a bunch of visible configuration files in your `$HOME` directory but you want  them to be visible in your projects.

`rustfmt` for example, supports both a `.rustfmt.toml` file and a `rustfmt.toml` file but also searches in parent directories, so that hiding configuration files with a leading dot makes totally sense. They also use the `dirs` crate to search the config directory (e.g. `$HOME/.config/rustfmt`)  for global configuration `.toml`-files.

I don't get why anyone wants to hide configuration files in a project directory as this forces the users of Unix-like systems to show hidden files in their file browsers and/or editors. Currently, Deno is doing so as well which made the developers of `dprint` change their default configuration file name to `.dprintrc.json`.

Another thing is this annoying pattern, where any config file is called an `rc`-file which evolved in the Node.js world with the rise of `cosmiconfig`. Originally, Rc files were meant to act as initializer files that set environment variables and/or run a bunch of commands when launching a program to set it up internally. A `.dprintrc.json` file for example does not do that. Instead it holds project-specific command options as properties of a JSON object, which makes sense as you don't want to pass all these options on the command line when executing `dprint fmt`. Nonetheless, that is not the job of an Rc file which is why you will not find this pattern in the Rust world.

Please consider to not adopt this pattern in Deno and related tools. What speaks against a simple `dprint.json` or `dprint_config.json` file? Same with `dlint.json` for `deno_lint` and so on... Thank you.

**Comment by lucacasonato** [comment]
We don't have any config files for deno CLI, especially none with a required name.

**Comment by kitsonk** [comment]
The issue you mention gives no indication that the change was made because of Deno, so I am not sure what point or suggestion is being made.

**Comment by ChristianGrete** [comment]
Yes, I know that Deno itself does not do or require that in its CLI. It seems that developers adopt coding styles from this project and its style guide, which is a good thing but should also make aware of that users also adopt how to structure and name their projects and configuration files. As a result, `dprint` has changed their default configuration filename to `.dprintrc.json` just because Deno uses this filename. And I am afraid that `deno_lint` could follow the same pattern.

@kitsonk See: https://github.com/dprint/dprint/issues/257
> The files deno uses are all `.<name>rc`. It would probably be best to support a `.dprintrc.json` file as another default file name in addition to `dprint.config.json` [...] Actually, perhaps it should be this instead of `dprint.config.json`? I'm not sure what the standard is across tools. [...] Edit: Going with this instead.

I know that this should not be a thing to Deno itself but as this project grows and gains attention, people adopt your stuff. Just wanted to raise awareness. 😉
