### ISSUE TITLE
Use forward slashes for paths on Windows

### ISSUE THREAD

**Issue by ry** [denoland/deno#957]
The backslash vs forward slash difference between Unix and Windows is one of the oldest yet continually painful parts of making cross-platform software.

Windows itself accepts forward slashes in most (all?) of its API at this point. 

I suggest that Deno always output forward slash paths on Windows. 

For example, `deno.cwd()` might return `"/C:/Documents/Foo"`.

If we ensure that all APIs in Deno return forward slashes, we can alleviate this cross-platform issue from our users.

Issues:
* In the Windows command line, arguments are specified using forward slash instead of dash. To solve this we will provide `deno.pathBackwards(string): string`. This will allow users to convert any forward slash path to the backward slash variety. This confines path portability issues to users who interact with such command line programs.
* Paths may come from sources other than deno, and these paths may very well be using backslashes. To solve this we will ensure any Deno APIs that take paths do accept the backslash variety. Furthermore we will provide `deno.pathForwards(string): string` to convert into the forward slash variety.

cc @piscisaureus

**Comment by TehShrike** [comment]
This would make life way easier...

On what file systems/versions of Windows are forward-slashes handled?

**Comment by bartlomieju** [comment]
Reference: #2572 - that PR should ensure that

**Comment by ry** [comment]
Closing this because @piscisaureus objects.

**Comment by bartlomieju** [comment]
> Closing this because @piscisaureus objects.

Could you elaborate? Does this block my idea to use forward slashes internally for `DenoDir`?

**Comment by ry** [comment]
@bartlomieju https://github.com/denoland/deno/pull/987#issuecomment-438573356

> Does this block my idea to use forward slashes internally for DenoDir?

No, I think that's fine... I mean, ideally we would use URLs which have saner semantics.
