### ISSUE TITLE
Support for reserved space in a `deno compile` binary

### ISSUE THREAD

**Issue by heyheyhello** [denoland/deno#9574]
Hello! Thanks for all the great work on compiled executables recently. I've been using them as local-first web apps (offline, double-click to run, etc). I needed Deno to serve static HTML/CSS/JS files as a webserver and still be a single executable. This was harder to do than I'd hoped since Deno only allows a JS bundle as a payload. I used https://github.com/denoland/deno/issues/6879#issuecomment-667687963 which works but as my data grows it keeps me up at night knowing Deno/V8 is parsing, loading, and unencoding 40+MB of strings on startup. I'd prefer to load the data as its needed instead.

I've read discussions about loading non-importable resources via fetch, url, base64, and dynamic import: 
- https://github.com/denoland/deno/issues/5987
- https://github.com/denoland/deno/issues/8655

For importable resources and module loading I agree that waiting for import assertions to official land is good. Still, I think a lot of people have a simpler usecase like mine - general static data.

To help keep the JS bundle small I think Deno could very easily support a region of the compiled binary that is skipped (i.e not the JS bundle or the metadata) and allow developers to do anything they'd like with it; how it's structured and used is our problem not yours. As a Deno app I could seek to the end of the binary, read the pointer, seek, and read the content I need.

![image](https://user-images.githubusercontent.com/44614862/108678086-7cf53980-749f-11eb-8537-94da0f421d6c.png)

This would involve changing the pointer math and string lengths here: https://github.com/denoland/deno/blob/f4980898cd4946a9e5c1d194ab7dbc32de28bf43/cli/standalone.rs#L49-L78

Having a skipped region should be general purpose enough to support many future usecases beyond files and virtual filesystems. Maybe custom metadata, checksums, copyright, WASM binaries.

CC @lucacasonato

Curious to see what you think!

**Comment by heyheyhello** [comment]
Oh I poked around in a hex editor and it looks like placing binary data _before_ the JS bundle and simply adjusting the pointers works.

How does Deno/Rust know where its own binary ends? Is it safe to place any binary code this way?

**Comment by lucacasonato** [comment]
> Is it safe to place any binary code this way?

Yes, this is safe on all platforms. I can't guarantee that this will work in future Deno versions, because the binary layout of the file might change, but it should work for the foreseeable future.

**Comment by heyheyhello** [comment]
Lovely, I'll switch to that. Haven't seen anyone else do this yet, no docs or issues, so I'll report back later about how it goes. Hopefully this thread can steer others away from string encoding their assets into TS. Thanks!
