### ISSUE TITLE
Expose window.navigator.hardwareConcurrency

### ISSUE THREAD

**Issue by Skillz4Killz** [denoland/deno#9584]
Hello 👋 

MDN: https://developer.mozilla.org/en-US/docs/Web/API/NavigatorConcurrentHardware/hardwareConcurrency

Use Case: Determine how many CPU cores are available to create that many workers.

Note: This is already doable in `Deno. systemCpuInfo().cores` but this is unstable.

Thank You!

**Comment by caspervonb** [comment]
**assigns self**
