### ISSUE TITLE
Add --jobs flag to relevant subcommands

### ISSUE THREAD

**Issue by caspervonb** [denoland/deno#9585]
Add a `-j, --jobs N`(most common name in the wild) flag to `deno lint` and `deno fmt` to let users control how many concurrent threads it will consume.

Might be applicable for other subcommands, like deno test soon'ish.
Not sure if we should apply this to the runtime commands like run, eval, etc.

**Comment by caspervonb** [comment]
Not stale, deno test has this in a pending PR and got one for lint locally, will raise that soon.

**Comment by lucacasonato** [comment]
I don't get why we should have this for `deno lint` or `deno fmt`. They should have good defaults, and not have any configuration for this.

@dsherret WDYT?

**Comment by caspervonb** [comment]
Going back a bit here, but iirc lint spins wild with threads and used to die on my Mac mini a lot.

**Comment by dsherret** [comment]
I don’t think it should be a flag. If anything just an environment variable that users can set for their system like what rust does.

**Comment by mrkldshv** [comment]
@lucacasonato @bartlomieju WDYT about this?

**Comment by bartlomieju** [comment]
I agree with David, there's no point adding `--jobs` to `fmt` and `lint` since they use multiple threads by default.

**Comment by nayeemrmn** [comment]
I think
- Deprecate `--jobs` flag by printing a warning when it's used
- Add a `DENO_JOBS` env var to replace it
- `DENO_JOBS` default should be 1 for `deno test`
- `DENO_JOBS` default should be system cores for `deno fmt` and `deno lint` (separate PR from above)

This is good because `--jobs` syntax was a bit broken anyway: #14533.

**Comment by caspervonb** [comment]
Can always do `DENO_TEST_THREADS` and less than zero as a condition to fallback to `num_cpus`

**Comment by lucacasonato** [comment]
We are using the `DENO_JOBS` env var for this now, in combination with a `--parallel` flag.
