### ISSUE TITLE
deprecate Deno.Buffer

### ISSUE THREAD

**Issue by ry** [denoland/deno#9588]
Move to std

**Comment by caspervonb** [comment]
Depending on the outcome of this proposal (https://github.com/tc39/proposal-resizablearraybuffer) it may not be worth keeping around at all.

**Comment by bartlomieju** [comment]
This would be a breaking change so should probably be considered for 2.0. 

Additionally `Deno.readAll` and `Deno.readAllSync` depend on `Buffer`, but it should be straight-forward to rewrite them not to depend on `Buffer`.

**Comment by kitsonk** [comment]
Deprecating it wouldn't, right?  Removing it would.

**Comment by bartlomieju** [comment]
> Deprecating it wouldn't, right? Removing it would.

Sure, how would we go about deprecating? Printing something to console when new instance of `Buffer` is created? I guess it's a good point to consider how we'll be deprecating APIs going forward (IIRC we haven't done this yet)

**Comment by lucacasonato** [comment]
`/** @deprecate Use buffer from https://deno.land/std/io/buffer.ts instead. */`

**Comment by kitsonk** [comment]
I would say no... I would say we simply use `@deprecated` in the JSDoc... that would highlight it in the documentation and would give anyone using an intelligent editor a visual indication.  Logging to stderr/stdout is painful for such things and unnecessary in my opinion.

<img width="316" alt="Notification_Center" src="https://user-images.githubusercontent.com/1282577/108917134-63144c00-7683-11eb-9d3b-f2043cd77b7e.png">

**Comment by kitsonk** [comment]
👍 for `deno lint` but ideally `deno lint` should just parse the JSDoc and warn on any `@deprecated` use instead of having to maintain a list of APIs.

**Comment by lucacasonato** [comment]
>  ideally `deno lint` should just parse the JSDoc and warn on any `@deprecated` use instead of having to maintain a list of APIs.

I don't think this isn't possible until `deno lint` has type information like TS does.

**Comment by kitsonk** [comment]
@lucacasonato I commented in denoland/deno_lint#623... it is simply tracking symbols across module boundaries, which swc does... it wouldn't work for type only constructs true, but `deno doc` doesn't have type information and it reads and tracks stuff just fine, right?

**Comment by lucacasonato** [comment]
Closing in favor of #9795
