### ISSUE TITLE
dynamically imported module without import / export is treated as script by tsc

### ISSUE THREAD

**Issue by kt3k** [denoland/deno#9593]
(Note: This probably doesn't affect any meaningful use cases, but I create issue for record.)

When we have the following scripts:

a.ts
```ts
const a = 1;
await import("./b.ts");
```

b.ts
```ts
const a = 2;
```

Then execute `a.ts` and it causes the following error.

```shellsession
$ deno run --allow-read a.ts
error: TS2451 [ERROR]: Cannot redeclare block-scoped variable 'a'.
const a = 2;
      ^
    at file:///Users/kt3k/0/di-test/b.ts:1:7

    'a' was also declared here.
    const a = 1;
          ^
        at file:///Users/kt3k/0/di-test/a.ts:1:7
```

This doesn't happen when:
- b.ts has any import or export statement
- import of b.ts is not dynamic import

---

```
$ deno --version
deno 1.7.5 (release, x86_64-apple-darwin)
v8 9.0.123
typescript 4.1.4
```

**Comment by bartlomieju** [comment]
For the record this is TSC error and not error coming from V8.

**Comment by nayeemrmn** [comment]
This is an example of where simply _ignoring_ `TS2306`: https://github.com/denoland/deno/blob/ae8874b4b2015453e53965dae2a2dae9cacbce70/cli/tsc/99_main_compiler.js#L145-L147 is not enough, and we need a real way of telling the TypeScript compiler out-of-band that all source files should be treated as ES modules. Unfortunately no such compiler option is provided by TypeScript, so we tell users to work around this by adding `export {};` in the imported module.

**Comment by nayeemrmn** [comment]
Ref https://github.com/microsoft/TypeScript/issues/18232.

**Comment by kitsonk** [comment]
That old problem. There is no easy way around it except `export {}`, but is dynamically importing a module that doesn't export anything actually a common realistic problem?

I suggest we simply add a note to the docs FAQs about this know TypeScript issue and be done with it.

**Comment by nayeemrmn** [comment]
Ref https://github.com/microsoft/TypeScript/issues/18232#issuecomment-932972722.

**Comment by kitsonk** [comment]
As stated in the response, the option doesn't fix the issue and can't fix the issue as tsc is currently artchitected.
