### ISSUE TITLE
Unable to upgrade deno to the latest version for System.IO.Compression.FileSystem

### ISSUE THREAD

**Issue by AhsabAli2000** [denoland/deno#9608]
Hello today I tried to update deno from 1.7.0 to the latest version with the `deno update` command. However it was unable to update and threw an error of System.IO.Compression.FileSystem . The operating system I am using is Windows 7 SP1. Here is the complete log of the error 

```cmd
Looking up latest version
Found latest version 1.7.5
Checking https://github.com/denoland/deno/releases/download/v1.7.5/deno-x86_64-p
c-windows-msvc.zip
Download has been found
Deno is upgrading to version 1.7.5
Add-Type : Cannot add type. The assembly 'System.IO.Compression.FileSystem' cou
ld not be found.
At line:4 char:21
+             Add-Type <<<<  -AssemblyName System.IO.Compression.FileSystem
    + CategoryInfo          : ObjectNotFound: (System.IO.Compression.FileSyste
   m:String) [Add-Type], Exception
    + FullyQualifiedErrorId : ASSEMBLY_NOT_FOUND,Microsoft.PowerShell.Commands
   .AddTypeCommand

System.InvalidOperationException: Cannot add type. One or more required assembli
es are missing.
   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(Error
Record errorRecord)
thread 'main' panicked at 'assertion failed: unpack_status.success()', cli\tools
\upgrade.rs:230:3
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

**Comment by bnoordhuis** [comment]
Windows 7 is end-of-life and not tested by us. You're probably out of luck but if you figure out a non-intrusive way to fix the issue, please send a pull request.

**Comment by AhsabAli2000** [comment]
Ok ill close this issue when it is solved or ill close if i mange to get it

**Comment by pedropaulosuzuki** [comment]
Hey man, could you check the version of PowerShell that you are using? I think your problem may be related to that.

**Comment by pedropaulosuzuki** [comment]
> 
> 
> Hey man, could you check the version of PowerShell that you are using? I think your problem may be related to that.
> 
> If your version is prior to Powershell 5.1, then you might want to update it with the [Windows Management Framework 5.1](https://www.microsoft.com/en-us/download/details.aspx?id=54616).

@AhsabAli2000 if this doesn't work, try running the same command but allowing for RUST_BACKTRACE='full' so that we can get a better understanding of the issue. On powershell, you can run:

```powershell
$Env:RUST_BACKTRACE='full'
deno upgrade --version 1.7.5
```
