### ISSUE TITLE
mirror older releases to `dl.deno.land`

### ISSUE THREAD

**Issue by maximousblk** [denoland/deno#9615]
currently, releases prior to `v1.7.0` are not present on `dl.deno.land/release`.

This would also make it very easy for automation applications (particularly GitHub Actions) to fetch older builds (like `v0.30.0`) that did not follow the current file naming convention for the release artifacts.

**Comment by maximousblk** [comment]
any updates on this?

**Comment by maximousblk** [comment]
Any updates on this?

**Comment by bartlomieju** [comment]
@maximousblk no update, it seems no one has bandwidth to do that. Is this something that is much desired?

**Comment by maximousblk** [comment]
I opened it when working on https://github.com/maximousblk/setup-deno so that it's easier and more "consistent" but a lot of versions have been released since then and i don't know if anyone would use builds before `1.0.0` but i think at least builds after v1 should be available on `dl.deno.land`

**Comment by crowlKats** [comment]
I personally would say this is not really relevant anymore, and using such an old version should be discouraged.
