### ISSUE TITLE
wrong type for regex match, breaks named groups

### ISSUE THREAD

**Issue by Pyrolistical** [denoland/deno#9621]
This is related to https://github.com/denoland/deno/issues/5444

Currently the type returned by `String.match(RegExp)` does not includes groups which leads to this situation

```
const {groups: {filename}} = path.match(/^\/play\/(?<filename>.+)$/);
```
```
error: TS2339 [ERROR]: Property 'groups' does not exist on type 'RegExpMatchArray | null'.
      const {groups: {filename}} = path.match(/^\/play\/(?<filename>.+)$/);
             ~~~~~~
```

Tested on Deno 1.7.2

Works in node.js

**Comment by Pyrolistical** [comment]
I think the cause is https://github.com/microsoft/TypeScript/issues/29465

**Comment by Soremwar** [comment]
This is not an issue. `match` can always return null if the provided string doesn't contain any items that match the regex expression
```js
"b".match(/a/) // Will return null
```

What you should be doing instead of trying to destructure, is to add a validation for such cases
```js
const result = path.match(/^\/play\/(?<filename>.+)$/);
if(result !== null){
  // Throw or handle case
}

const {groups: {filename}} = result;
```

**Comment by Pyrolistical** [comment]
that makes sense thanks.
