### ISSUE TITLE
Variables in .env files

### ISSUE THREAD

**Issue by aadamsx** [denoland/deno#9629]
Typically .env these files are small and manageable, but there are times when you run into situations where you duplicate the same data within the file. Here is an example:

MAIL_USERNAME=hello@laravel-news.com
MAIL_FROM_ADDRESS=hello@laravel-news.com

The dotenv package that Laravel relies on can use variables with other defined variables in this same file. For example:

MAIL_USERNAME=hello@laravel-news.com
MAIL_FROM_ADDRESS=${MAIL_USERNAME}

This simple trick allows you not to repeat yourself and can be useful when you have multiple services requiring the same piece of data.

I tried using this with the deno dotenv package and the deno standard library for env files and both parsers don't pick up the variable, intead the console log value in the MAIL_FROM_ADDRESS example above would be just ${MAIL_USERNAME} instead of hello@laravel-news.com.

**Comment by caspervonb** [comment]
Hi there.
Uhm, we don't have a .env parser in deno_std?

**Comment by bartlomieju** [comment]
Not a Deno issue, please report the problem with appropriate module author.

**Comment by aadamsx** [comment]
Wait, what am I looking at here? It says Deno runtime documentation: https://doc.deno.land/builtin/stable#Deno.env

**Comment by bartlomieju** [comment]
@aadamsx the API you linked to is used for accessing or setting env variables at runtime; it doesn't have an ability to load `.env` files. 

There's [`dotenv`](https://deno.land/x/dotenv@v2.0.0) module on `deno.land/x` that can does loading from `.env` files, so I suggest to open feature request issue there. 

All things considered, loading `.env` files is a useful and very popular feature, so it might be a good idea to consider such module for https://github.com/denoland/deno_std

**Comment by aadamsx** [comment]
@bartlomieju, yes I consider .env a very important component, it is how many getting the initial values into projects of all types.

Also, is there a place to make a feature request to have this included in the Deno std lib?

For what it's worth, I opened a issue over at the deno dotenv but it's like a graveyard over there -- I doubt I'll get any movement on this issue.

**Comment by caspervonb** [comment]
@bartlomieju there's a caveat tho and that is that in many scenarios the env file needs to be sourced before the process is run for it to have an effect.

@aadamsx  here's a bash equivalent:

```bash
# .env
A=2
B=2
C=$A
```

```bash
set -a
source .env
set +a
deno run program.ts
```

**Comment by aadamsx** [comment]
@caspervonb using removing the {  } and just using $MAIL_USERNAME ( instead of ${MAIL_USERNAME} ) doesn't work either:

MAIL_USERNAME=hello@laravel-news.com
MAIL_FROM_ADDRESS=$MAIL_USERNAME

The result from MAIL_FROM_ADDRESS is still $MAIL_USERNAME and not hello@laravel-news.com.

**Comment by caspervonb** [comment]
Ok.

**Comment by kitsonk** [comment]
> Also, is there a place to make a feature request to have this included in the Deno std lib?

https://github.com/denoland/deno_std/issues/new
