### ISSUE TITLE
.env file support for Deno

### ISSUE THREAD

**Issue by linux-china** [denoland/deno#9631]
.env file is small and convenient to setup env variables,  and lots of tools support .env file. could Deno add .env file support?    It's easy to customize Deno and add env variables  by .env file. 

```
DENO_AUTH_TOKENS=xxxx@raw.githubusercontent.com
DENO_PERMISSIONS="--allow-net"
DATABASE_USER="xxxx"
```

Of course, you can use dotenv third party module, but some tricky: 

*  Most developers just add  "--allow-read" to read .env file, but "--allow-read" is almost a back door to malicious code. If Deno has .env file support, and "--allow-read" is not necessary for permissions.  
*  It's fast for Deno to load .env file with Rust code, and code base is  very small

**Comment by LukeChannings** [comment]
Note that `--allow-read` need not allow *all* read access, you can specify `--allow-read=.env`, or multiple files by comma-separating: `--allow-read=.env,envFile`.

Won't comment on performance, but I'd hazard a guess that your env file would have to be hundreds of thousands of lines for it to make a difference.

**Comment by caspervonb** [comment]
Your shell can handle that.

For example

```bash
set -a
source program.env
set +a

deno run program.ts
```

**Comment by bartlomieju** [comment]
There's no plan to support `.env` files in Deno, this functionality can and already is handled by 3rd party modules. Respectfully closing.
