### ISSUE TITLE
Windows10 can't read HTTP_PROXY environment variable

### ISSUE THREAD

**Issue by Checkpoints** [denoland/deno#9634]
I have asked the same question at Stackflow. Not sure if it's my code wrong, or it's a Windows related bug.

I set the Proxy url like
Deno.env.set('HTTP_PROXY', 'https://138.68.60.8:3128/');
Deno.env.set('HTTPS_PROXY', 'https://138.68.60.8:3128/');

In face the manual doesn't say how shall I set the environment variables. These are googled from somewhere.

yet the fetch() still fetches without the proxy. Instead, if I set up a proxy in the Windows system setting, the fetch() does use the system set proxy. Which doesn't solve the problem though as I am trying to read the proxy list from an API.

**Comment by lucacasonato** [comment]
You have to see these environment variables before you start Deno, not from within the runtime.
