### ISSUE TITLE
Inspector blocked during top-level await 

### ISSUE THREAD

**Issue by nayeemrmn** [denoland/deno#9643]
```ts
// deno run --inspect temp.ts
setTimeout(null, 1e8); // Keeps the process alive.
await new Promise(r => {});
```
When I run this and go to `chrome://inspect/`, the remote target is there but when I click "trace", there is **no** `Debugger session started.` in the terminal and the inspector rejects input.

Doesn't occur when the same code is wrapped in an async iife:
```ts
// deno run --inspect temp.ts
(async () => {
  setTimeout(null, 1e8); // Keeps the process alive.
  await new Promise(r => {});
})();
```

**Comment by bartlomieju** [comment]
@nayeemrmn this is the same issue as #9619 - inspector is part of `MainWorker`/`WebWorker` and it is never polled during module evaluation with TLA
