### ISSUE TITLE
Flatten the Deno.errors namespace into the Deno namespace

### ISSUE THREAD

**Issue by caspervonb** [denoland/deno#9646]
This would have to be a v2.0 thing but feels like our error names are a bit awkward living inside a lowercase namespace without an error suffix.

WebAssembly would be a good example of a builtin namespace in JavaScript that exposes its own errors; a linking error is at `WebAssembly.LinkError`.

So I propose we look into giving the Deno namespace errors the same treatment: `Deno.errors.PermissionDenied` becomes `Deno.PermissionError` and so on.

**Comment by vwkd** [comment]
Just as a sidenote, one advantage with using a sub namespace `Deno.errors` is that autocomplete is better, since errors don't show up *except* when typing `Deno.err...` and do *all* show up when typing `Deno.err`. But that's probably secondary, and I'm fine with changing them.

**Comment by vwkd** [comment]
Just as a sidenote, one advantage with using a sub namespace `Deno.errors` is that autocomplete is better, since errors don't show up *except* when typing `Deno.err...` and do *all* show up when typing `Deno.err`. But that's probably secondary, and I'm fine with either change.

**Comment by bartlomieju** [comment]
Not gonna do that, we now have other examples of namespaces, like `Deno.jupyter`.
