### ISSUE TITLE
`deno fmt` lexical parse error

### ISSUE THREAD

**Issue by aricart** [denoland/deno#9650]
If you have some dodgy code like this:
```typescript
export class X {

  constructor() {
  }
  bad(target :number) {
    const d = 1;
    const min = 0;
    const max = 100;
    console.log("x", `duration ${d} not in range - ${min} ≥ ${d} && ${max} ≥ ${d}`),;
  }
}
```
Note the trailing `,` before the `;`.

and run `deno fmt`, you get:
```bash
❯ deno fmt
memory allocation of 18446744073709551615 bytes failed
[1]    8481 abort      deno fmt

```

**Comment by kdy1** [comment]
I tried this and I found that the parser reports errors for this.

**Comment by dsherret** [comment]
@kdy1 yeah, this is a dprint problem with its code for printing diagnostics. See here: https://github.com/dprint/dprint-plugin-typescript/issues/113#issuecomment-789246224
