### ISSUE TITLE
when i use frp and ngnix, BrokenPipe: Broken pipe (os error 32) .But i use localhost:8080 ,it is ok

### ISSUE THREAD

**Issue by anthonyyuan** [denoland/deno#9658]
BrokenPipe: Broken pipe (os error 32) 
    at unwrapResponse (deno:runtime/js/10_dispatch_minimal.js:60:13)
    at sendAsync (deno:runtime/js/10_dispatch_minimal.js:99:12)
    at async write (deno:runtime/js/12_io.js:118:20)
    at async ResponseWriter.flush (file:///home/anthony/Downloads/deno_note-master/demo/response/mod.ts:116:15)
    at async file:///home/anthony/Downloads/deno_note-master/demo/web/application.ts:52:9
    at async createHTTP (file:///home/anthony/Downloads/deno_note-master/demo/server/mod.ts:125:4)
error: Uncaught (in promise) BrokenPipe: Broken pipe (os error 32) 
      throw new ErrorClass(res.err.message);

**Comment by bogdanbiv** [comment]
Could you provide some context? How do you start NginX and Deno? In particular I don't quite see the link from what do FRP and NginX (both quite generous discussion topics) have to do with Deno?

**Comment by anthonyyuan** [comment]
HI：
   https://github.com/fatedier/frp  and public cloud server run nginx. when I use my computer at home to run deno, and use www.xxx.com and get BrokenPipe: Broken pipe (os error 32).
   core code is async function createHTTP(
  opts: Deno.ListenOptions,
   handler: (ctx: Context) => void
) {
  const server = serve(opts);
  for await (const ctx of server) {

    //await handler(ctx);
    try { 
      await handler(ctx);
    
    } catch (err) { /* render pretty error page */ }
   
  }
}
