### ISSUE TITLE
Optimize per-isolate baseline heap-size for core libs

### ISSUE THREAD

**Issue by AaronO** [denoland/deno#9660]
Apps with many workers (scaling I/O & processing or running untrusted user-code) will suffer memory overhead of functionally identical items replicated in each heap.

Heap-size probably doesn't hugely affect isolate startup performance, since we use snapshots, so the main concern here is memory usage.

Most apps with a handful of workers may not be too concerned by the isolate heap-baseline, but this could also impact environments (e.g: cloud functions, AWS lambda, etc...) where memory is limited or at a premium

### What takes up heap space ?

Nearly everything in JS does to some extent, but the larger "offenders" are:
- JS source code 
- Large strings / large arrays (e.g: TextEncoder mappings)
- Large WASM

### Current baseline

As of `1.8.0` the baseline heap-size is `~2.25MB` (after GC), it was `2MB` prior to `1.8.0` (explained by WebGPU and other additions).

~As of `1.8.0` the baseline heap-size is `3MB` (after GC), it was `2MB` prior to `1.8.0` (explained by WebGPU and other additions).~ (this was slightly higher due to being measured on a debug build)

### What can we optimize ?

Optimizing heap-size will often come with different tradeoffs (build complexity, stacktrace debugability, ...) but here are some low hanging fruit:
- Core JS code: minimize core JS and crate code for release builds (maybe "trim" off stack traces)
- `TextEncoder`: move the encoding arrays to rust or implement the bulk of it
- Crypto: implement WebCrypto via rust & ops vs WASM (unlike `std/hash`)

### Future take-aways

It would be nonsensical to over-optimize heap-size (e.g: implementing all of the core in pure rust ...), but there are cases where there's little advantage to having it in JS/WASM vs Rust and minifying core JS could also be a user-transparent improvement, since most users shouldn't/don't care about stacktraces of below core functions (since all core features are assumed stable and core APIs are "blackboxes" in browser runtimes).

### Notes

This issue is a follow-up of https://github.com/denoland/deno/pull/9659 and conversations with the core team.

**Comment by lucacasonato** [comment]
This is not actionable, we are generally tracking this issue all the time and are continually working on it. I will close this.
