### ISSUE TITLE
WebGPU API invalid utf-8

### ISSUE THREAD

**Issue by Desibabe** [denoland/deno#9661]
deno run --unstable https://deno.land/posts/v1.8/webgpu_discover.ts
error: invalid utf-8 sequence of 1 bytes from index 6

Example from https://deno.land/posts/v1.8

deno 1.8.0 (release, x86_64-pc-windows-msvc)
v8 9.0.257.3
typescript 4.2.2
windows 10

**Comment by crowlKats** [comment]
See denoland/deno_website2#1684

**Comment by lucacasonato** [comment]
duplicate of #
