### ISSUE TITLE
deno compile add the .exe extension on windows even if the target is specified

### ISSUE THREAD

**Issue by buttercubz** [denoland/deno#9667]
I am trying to compile an example for different targets, but deno compile it adds the `.exe` even though the target is specified.

![image](https://user-images.githubusercontent.com/47539192/109817320-3377bd80-7c08-11eb-923e-0b1b888becab.png)

![image](https://user-images.githubusercontent.com/47539192/109817389-44283380-7c08-11eb-88c4-dab6a95aac26.png)

removing `.exe` the executable works on its respective platform

https://github.com/denoland/deno/blob/79e2e6a1f47b9d24abab14cfd69376d825b52e03/cli/tools/standalone.rs#L135 I think this condition is responsible

**Comment by lucacasonato** [comment]
Ah yes, that conditional should be the target platform, not the current platform.
