### ISSUE TITLE
Fill Navigator

### ISSUE THREAD

**Issue by shadowtime2000** [denoland/deno#9676]
It seems `navigator` isn't modifiable because it contains the WebGPU APIs, and you don't want people to be able to change those. It seems though, that `navigator` only contains the WebGPU APIs, while we would still like the other information there because well, you can use it then. This is not good for SSR because we can't change it in anyway, and it doesn't contain appropriate information. 

I think some information in navigator could probably be filled on their own, and then maybe have CLI arguments for the other ones like connection or env variables.

And then maybe also just special user agent and stuff because it's serverside, like [what we do in AlephJS](https://github.com/alephjs/aleph.js/blob/master/server/helper.ts#L27-L28).

**Comment by shadowtime2000** [comment]
🤦 

Actually `navigator` is modifiable, but I think still some information could probably be filled by Deno.

**Comment by lucacasonato** [comment]
What is actionable here for us? You can assign properties to navigator at runtime.

**Comment by littledivy** [comment]
> could probably be filled by Deno.

Afaik no modifications are made to global APIs by Deno at runtime. So you're good to assign to `navigator`

**Comment by shadowtime2000** [comment]
Yes, you can assign properties to navigator at runtime.

But I still think Deno could polyfill it, with stuff like `navigator.onLine` and all.

Because your trying to make it compatible with web standards right?

**Comment by kitsonk** [comment]
When we choose specific web standards features to support, and they exist in `navigator`, they will be added to `navigator`.  Specific requests to add web standard features should be raised as a specific feature request.  This is unactionable.
