### ISSUE TITLE
Feature: loading modules in a folder like `require.context()` of Webpack

### ISSUE THREAD

**Issue by betterRunner** [denoland/deno#9677]
Any plans to support function like `require.context()` of Webpack to load modules in a folder?

**Comment by lucacasonato** [comment]
No. This is incompatible with remote modules as we can not get a directory listing for those. For local files you can use `Deno.readDir()` to get a directory listing.

**Comment by betterRunner** [comment]
@lucacasonato thanks for the reply. Since `Deno.readDir()` can just get the name of the files in the directory, then how to import these files as es6 modules? (`Deno.readFile` will read the Uint8Array so I think it is not the choice)

**Comment by lucacasonato** [comment]
@betterRunner You use dynamic imports. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import
