### ISSUE TITLE
import.meta.main is always false on 'deno test' but not 'deno run'

### ISSUE THREAD

**Issue by darkdamp** [denoland/deno#9679]

**Comment by lucacasonato** [comment]
Are you saying this is a bug? `deno test` doesn't have a main file. Please clarify what you expect to happen.

**Comment by guybedford** [comment]
Might be an alternative approach to the pattern in https://github.com/denoland/deno/issues/8007, which I enjoy using for my tests personally via `import.meta.main` in Deno currently.

**Comment by darkdamp** [comment]
@lucacasonato 
I got `Deno.TestDefinition` for different test cases in different modules. Each module has a anonymous invoker to run all the tests for that module. I could always put these test cases in functions but it'd be nice to be able to invoke them all in a row. Below is a small concept to prove the idea

`a.ts`
```
import { B } from "./b.ts";

class A extends B {
    
}

(() => {
    console.log("A", import.meta.main);
})();
```

`b.ts`
```
export class B {
    
}

(() => {
    console.log("B", import.meta.main);
})();
```

`deno run` returns
```
B false
A true
```

Whereas `deno test` would return
```
B false
A false
```

**Comment by lucacasonato** [comment]
I still don’t understand. Which module would be main if you run multiple test files at once?

**Comment by caspervonb** [comment]
Not sure what your use case here @darkdamp? doesn't look like you're using the test harness at all?

This might change with https://github.com/denoland/deno/pull/9662 for 1.9 (a side effect of running test modules in their own isolates), we'll see.

**Comment by darkdamp** [comment]
Closed in favor of discussion at https://github.com/denoland/deno/issues/8007
