### ISSUE TITLE
Wanted: A simple TS/JS code formatter using the TS compiler

### ISSUE THREAD

**Issue by ry** [denoland/deno#968]
It should run under deno. It should be as little code as possible. It should probably try to look like prettier. It should not require any special permissions.

I'd like to have a blessed formatting system for Deno. EG `deno fmt myfile.ts`

Probably we wouldn't ship the formatter inside the Deno executable, but instead just load a URL.

The formatter does not need to support options. The point of code formatting is to remove configuration. However it does need to meet these constraints:
* Code wrapped at 80 columns
* 2 space indent

```
import * as ts from "typescript";
```
^--- this is available inside of deno today, and it's all that should be needed.

**Comment by kitsonk** [comment]
TypeScript has a full set of formatting APIs built into it, see: https://github.com/Microsoft/TypeScript/blob/master/src/services/formatting/formatting.ts

They should be exposed through the language services APIs in some fashion.  As for TypeScript and JavaScript documents, it is the default formatter of VSCode.  I couldn't quite figure it out, but the formatting options should be capable of meeting the requirements above, though the formatting wouldn't be as "intelligent" as Prettier.

**Comment by dsherret** [comment]
@kitsonk I don't believe the public api supports specifying the max line length (see [here](https://github.com/Microsoft/TypeScript/blob/master/lib/typescript.d.ts#L5193) and `EditorSettings` a few lines above---used via `getFormattingEditsForDocument` on `LanguageService`), but I may be mistaken. Perhaps there's something internal that could be exposed?

**Comment by bartlomieju** [comment]
It is now available from [deno_std](https://github.com/denoland/deno_std/blob/master/prettier/README.md)

**Comment by ry** [comment]
Also `deno --fmt blah.js`

**Comment by JLarky** [comment]
It doesn't seem to support `.prettierrc` though...

**Comment by dsherret** [comment]
@JLarky from the original post:

> The formatter does not need to support options. The point of code formatting is to remove configuration.

**Comment by saadq** [comment]
I think that's on purpose. It's probably going to be more like `gofmt` where all Deno code will have the same formatting rather than letting people customize their Prettier config. Might be wrong though.

**Comment by JLarky** [comment]
> @JLarky from the original post:
> 
> > The formatter does not need to support options. The point of code formatting is to remove configuration.

As if he can't be OP and be wrong at the same time

**Comment by JLarky** [comment]
> I think that's on purpose. It's probably going to be more like `gofmt` where all Deno code will have the same formatting rather than letting people customize their Prettier config. Might be wrong though.

I see. Still kind of awkward to setup separate prettier infrastructure just if you want to use prettierrc or prettierignore. But given the history that prettier didn't have that options in first version I guess it makes sense that people are so stubborn on zero config solutions

**Comment by kitsonk** [comment]
The intent of the feature was to have a consistent formatter built into Deno, not to support prettier in Deno.  It just happened that the default configuration for prettier was sufficient for our needs.

**Comment by hayd** [comment]
@JLarky This could be supported in deno_std, even if not with `deno fmt`.
