### ISSUE TITLE
Upgrade to TypeScript 3.1

### ISSUE THREAD

**Issue by ry** [denoland/deno#969]
ts-simple-ast does not yet support it, [but will soon](https://github.com/denoland/deno/pull/952#issuecomment-428630063).

cc @dsherret @kitsonk

**Comment by dsherret** [comment]
@ry I'm doing a release probably tonight to support 3.1.x. Will comment back here when done.

Side note: In TS 3.1.1 some of my kind of large mapped w/ conditional types were resolving to `any` in my declaration file build script and I was going to spend time investigating, but seems like the TypeScript team fixed that in 3.1.3, which was released about an hour ago :)

**Comment by dsherret** [comment]
I released 17.0.0 which is tested against a few versions of the compiler including 3.1.1 and 3.1.3. I also opened an issue on my repo to run a cron job on the CI that will test ts-simple-ast against the latest TypeScript RC package. That will help me stay on top of new compiler API releases and be aware if there are any problems before an actual release occurs.

I believe it should work fine and yarn should not pull in a separate version of typescript, but let me know if you run into any problems. I was going to test with deno, but it's building on a linux vm right now and taking a bit of time (I got [this error](https://gist.github.com/dsherret/85865d8674115706710696518d240ab4) building on windows and then gave up).

By the way, I highly recommend storing *lib.deno_runtime.d.ts* in source control as well. That way you will more noticeably see all the changes and if anything goes wrong (like my experience with the ts compiler resolving some types to `any` in v3.1.1) you will notice the problem before publishing. It will also help catch types you meant to mark with `internal`.

**Comment by ry** [comment]
> I released 17.0.0 

Great!

> By the way, I highly recommend storing lib.deno_runtime.d.ts in source control as well

Hmm I'd rather not... but maybe. I think `lib.deno_runtime.d.ts` gets extensively tested in our tests - so I'm hoping if it gets malformed that something will break. That said, let's see what happens over the next week.
