### ISSUE TITLE
Skip type checking for modules outside of user's control

### ISSUE THREAD

**Issue by KSXGitHub** [denoland/deno#9704]
Yesterday, [someone reported that `deno.land/x/args@2.0.7` stopped working on Deno 1.8.0](https://github.com/KSXGitHub/deno-args/issues/67). The cause for this bug is that the TypeScript version that Deno uses no longer infer generic argument correctly (in the past, `new Set()` would give `Set<T>`, but the new TypeScript gives `Set<unknown>`).

I know that this problem is outside of Deno's control. However, surprise breaking change is not a desirable behaviour. As such, Deno must minimize unintentional breaking change that may cause by upgrading TypeScript. One way to do it is to stop checking for type correctness of the implementation part of third-party modules.

**Comment by nayeemrmn** [comment]
Can you get type information without type checking, for an arbitrary segment of the module graph?

**Comment by KSXGitHub** [comment]
@nayeemrmn Can [swc](https://github.com/swc-project/swc) parse TypeScript AST? If it can, it is possible to separate declarations from implementation.

**Comment by kitsonk** [comment]
We can't/won't stop type checking the whole "program".  We could consider making the diagnostics non-fatal.  I thought we had an issue for it, but we don't, so I created #9737.  I think that is the only viable solution.

So this suggestion is respectfully declined.

**Comment by dsherret** [comment]
Related discussion in #5460 (This is essentially a duplicate of that)

**Comment by cowboyd** [comment]
Ran in to this just now, and the current DX feels like a pretty blunt tool: abandon type checking in your project altogether because of a problem in type compatibility with a dependency. 

Of the top of my head, it would be nice to be able to 

1. skip type checking on a per module basis.
2. override type declarations per module.

Is anything like this possible today?
