### ISSUE TITLE
How to typecheck whole project

### ISSUE THREAD

**Issue by KotlinIsland** [denoland/deno#9726]
I think it's something like:
`deno test {**,.}/*.ts --no-run`

**Comment by nayeemrmn** [comment]
`deno test --no-run` should do it. Or if for example you run `deno test -A src` to run your tests, it would be `deno test --no-run src`.

**Comment by KotlinIsland** [comment]
```
>deno test --no-run --unstable
No matching test modules found```

**Comment by nayeemrmn** [comment]
Does `deno test --unstable` find the files?

**Comment by KotlinIsland** [comment]
```
> deno test --unstable
No matching test modules found
```

There are no test files, I just want to check types on src files.

**Comment by KotlinIsland** [comment]
I would expect `deno lint` to check types tbh
