### ISSUE TITLE
Deno self-contained executable size increase

### ISSUE THREAD

**Issue by niyarlatotep** [denoland/deno#9729]
Since Deno 1.8.0 released deno self contained executable size increased for example ```console.log('Hello World!');``` compiled with flag --lite in old version (1.7.5) was ~18 mb now with new version (1.8.0) it's about 34,6 mb on Windows. Is it possible to reduce size? P. S. It's probably related to WebGPU API.

**Comment by crowlKats** [comment]
it is mainly related to ICU, but webgou has indeed increased the size by a decent amouunt as well. we are looking into reducing the size for webgpu a bit, but for ICU thats to say.

**Comment by lucacasonato** [comment]
This is not very actionable for us, so I will close, but be assured that we are always looking at ways to reduce the binary size.
