### ISSUE TITLE
🐛 `deno eval ...` doesn't automatically re-compile/eval supplied CODE_ARG (Windows)

### ISSUE THREAD

**Issue by rivy** [denoland/deno#9733]
```shell
C:>ver

Microsoft Windows [Version 10.0.18363.1379]

C:>deno --version
deno 1.8.0 (release, x86_64-pc-windows-msvc)
v8 9.0.257.3
typescript 4.2.2
```

When serially executed from a Windows command line, `deno eval CODE_ARG` falls back to a previously successfuly compiled CODE_ARG.

```shell
C:>deno eval console.log(0)
0
C:>deno eval console.log(1)
0
```

This can be mitigated by using the `-T`/`--ts` or, recently, `--ext ts` flags which forces a check when CODE_ARG is new.

```shell
C:>deno eval --ext=ts console.log(0)
Check file:///C:/Users/Roy/OneDrive/Projects/deno/dexter/repo.deno.dexter/$deno$eval.ts
0

C:>deno eval --ext=ts console.log(1)
Check file:///C:/Users/Roy/OneDrive/Projects/deno/dexter/repo.deno.dexter/$deno$eval.ts
1

C:>deno eval console.log(2)
1
```

**Comment by solson** [comment]
This affects me on Linux with Deno 1.11.0 as well.

**Comment by luke-john** [comment]
This affects me on Mac OS with deno 1.12.0 (release, x86_64-apple-darwin).

For some extra context, until I run deno eval with `--ext=ts` multiple runs of deno eval will work correctly, however after running deno eval with `--ext=ts`, subsequent runs without the `--ext` flag will return the result of the last run with `--ext=ts`.

ie.

```sh
% deno eval "console.log(0)"
0
% deno eval "console.log(1)"
1
% deno eval --ext=ts "console.log(2)"
2
% deno eval "console.log(3)"
2
% deno eval --ext=ts "console.log(4)"
4
% deno eval "console.log(5)"
```

**Comment by bartlomieju** [comment]
I can't repeat the problem anymore; I'm going to tentatively close this issue. Please comment if you're still hitting the problem.

**Comment by rivy** [comment]
Looks good; I'll re-open if I stumble back upon it.

Thanks!
