### ISSUE TITLE
Make TypeScript diagnostics non-fatal

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#9737]
We might want to consider making TypeScript diagnostics effectively only "warnings" and go ahead and still attempt to run the program, instead of treating all TypeScript diagnostics as fatal.

It can get frustrating when trying to develop code, and get type checking, to have Deno exit all the time, when you know there is a type error (or the type error is outside of your control).

**Comment by wperron** [comment]
I think I remember a similar discussion on the Discord server, iirc the suggestion was to make `--no-check` the default behavior. I'd be happy with that, we'd just have to figure out a proper flag for the "strict type checking" behavior

**Comment by KotlinIsland** [comment]
https://github.com/DetachHead/ts-helpers/issues/97

We can't use our project with deno because tsc strips `@ts-ignore` comments from the d.ts file.

`"skipLibCheck": true` is how you would work around with this in npm land, but I don't think it would work in deno.

**Comment by lino-levan** [comment]
@kitsonk I believe `--no-check` is essentially the default now. Should this issue be closed?

**Comment by bartlomieju** [comment]
Yes, that's for pointing this out.
