### ISSUE TITLE
How to use env vars?

### ISSUE THREAD

**Issue by reggi** [denoland/deno#974]
```ts
console.log(deno.env('EXAMPLE'))
```

running with:

```bash
EXAMPLE=true deno --allow-env ./file.ts
```

**Comment by reggi** [comment]
is giving back "Cannot find name 'deno'."

**Comment by ry** [comment]
```typescript
import { env } from "deno";
console.log(env()["EXAMPLE"])
```

**Comment by brandonros** [comment]
```
import { env } from 'deno';
```

yields

```
error: Uncaught URIError: relative import path "deno" not prefixed with / or ./ or ../ Imported from "file:///app/index.ts"
```

**Comment by lucacasonato** [comment]
The deno namespace has moved to the Deno global. Use Deno.env()

**Comment by kitsonk** [comment]
So:

```js
const env = Deno.env();
console.log(env["example"]);
```

**Comment by brundonsmith** [comment]
Is there a way to get your editor to recognize the `Deno` global?
<img width="647" alt="main_ts_—_jlox" src="https://user-images.githubusercontent.com/3674979/82163102-9ca36580-986e-11ea-965d-d508ebf141d3.png">

**Comment by kitsonk** [comment]
Use an editor plugin: https://deno.land/manual/getting_started/setup_your_environment#editors-and-ides

**Comment by brundonsmith** [comment]
Ah. I was using a different Deno plugin (by "axetroy") which I'm pretty sure was linked from somewhere else in the docs, though I can't find the reference now. This new one worked, thanks.
