### ISSUE TITLE
lsp: Extension reports spurious errors on Windows because of path encoding issues

### ISSUE THREAD

**Issue by elisee** [denoland/deno#9744]
(EDIT: See comments below, this goes beyond import maps, there's a mismatch in how paths are encoded between the extension and the LSP on Windows)

I'm using an import map to remap `.js` imports to `.ts` in code I share between the browser and Deno.  
It is working fine in Deno, but the extension reports the following errors:

    Unable to load a local module: "file:///c%3A/vscode-deno-import-map/browser/secondary.js".
    Please check the file path.

and

    Property 'value' does not exist on type 'typeof import("file:///c%3A/vscode-deno-import-map/browser/shared")'.

**To Reproduce**

See screenshot below or minimal repro here: https://github.com/elisee/vscode-deno-import-map 

**Expected behavior**

The import map should be properly applied by the extension and there should be no errors.

**Screenshots**

![image](https://user-images.githubusercontent.com/446986/109956763-56779f80-7ce4-11eb-8b5d-30f5d12dbb49.png)

**Versions**

vscode: v1.53.2
deno: v1.8.0
extension: v3.1.0
os: windows (seems important, see comment below)

**Comment by kitsonk** [comment]
We need to properly URL decode before creating the import map.

**Comment by elisee** [comment]
In case that's useful, the following hack makes things work on my end. It required both percent-decoding and patching the case mismatch in the disk labels ("c:" vs "C:"). A proper solution will require an actual understanding of where all those differences come from...

```diff
diff --git a/cli/import_map.rs b/cli/import_map.rs
index 487c0d87..e1be47da 100644
--- a/cli/import_map.rs
+++ b/cli/import_map.rs
@@ -416,8 +419,12 @@ impl ImportMap {
     specifier: &str,
     referrer: &str,
   ) -> Result<Option<Url>, ImportMapError> {
+    let decoded_referrer = percent_encoding::percent_decode_str(&referrer).decode_utf8().unwrap().replace("c:", "C:").replace("d:", "D:").to_string();
+
     let as_url: Option<Url> =
-      ImportMap::try_url_like_specifier(specifier, referrer);
+      ImportMap::try_url_like_specifier(specifier, &decoded_referrer);
     let normalized_specifier = if let Some(url) = as_url.as_ref() {
       url.to_string()
     } else {
@@ -428,7 +435,7 @@ impl ImportMap {
       &self.scopes,
       &normalized_specifier,
       as_url.as_ref(),
-      &referrer.to_string(),
+      &decoded_referrer,
     )?;
 
     // match found in scopes map

**Comment by elisee** [comment]
Regarding the case of the drive letter, this seems relevant: https://github.com/microsoft/language-server-protocol/pull/1019

**Comment by antoniogamiz** [comment]
I'm facing all those problems too! Though if you reload vscode, all errors go away (until they start appearing again if you change something hehe)

**Comment by kitsonk** [comment]
I have a potential fix.  I think it works, but I have yet to specifically test it on windows.  I am going to try to do that to make sure I have fully resolved the issue.

**Comment by elisee** [comment]
Thanks a lot! Just tested on Windows by upgrading to canary with `deno upgrade --canary`, and it looks like it's much better.

Paths in module tooltips still display as `d%3A` fwiw:
![image](https://user-images.githubusercontent.com/446986/113922854-17a79e80-97e8-11eb-89c0-db90b02868ca.png)

And I'm getting some spurious errors in complex situations where an interface extends an imported interface that itself uses imported interfaces from another module, or something like that. I've yet to find a reliable way to reproduce it with a minimal test case though.

**Comment by kitsonk** [comment]
The fix is not merged yet.

**Comment by elisee** [comment]
Oh so it's not in canary 😅. My bad, guess the placebo effect got me.
