### ISSUE TITLE
`deno test --coverage` doesn't seem accurate

### ISSUE THREAD

**Issue by aricart** [denoland/deno#9754]
I have the following report for coverage for a function:
```
      40         407 : export function parseInfo(s: string): DeliveryInfo {
      41         501 :   const tokens = s.split(".");
      42           0 :   if (tokens.length !== 9 && tokens[0] !== "$JS" && tokens[1] !== "ACK") {
      43           0 :     throw new Error(`not js message`);
      44           0 :   }
      45             :   // "$JS.ACK.<stream>.<consumer>.<redeliveryCount><streamSeq><deliverySequence>.<timestamp>.<pending>"
      46         501 :   const di = {} as DeliveryInfo;
      47         501 :   di.stream = tokens[2];
      48         501 :   di.consumer = tokens[3];
      49         501 :   di.redeliveryCount = parseInt(tokens[4], 10);
      50         501 :   di.streamSequence = parseInt(tokens[5], 10);
      51         501 :   di.deliverySequence = parseInt(tokens[6], 10);
      52         501 :   di.timestampNanos = parseInt(tokens[7], 10);
      53         112 :   di.pending = parseInt(tokens[8], 10);
      54         507 :   return di;
      55         413 : }
```

Notice how lines 42:44 report zero coverage.

But elsewhere:
```
Deno.test("jsmsg - parse rejects subject is not 9 tokens", () => {
  const fn = (s: string, ok: boolean) => {
    try {
      console.dir(s)
      parseInfo(s);
      if (!ok) {
        fail(`${s} should have failed to parse`);
      }
    } catch (err) {
      if (ok) {
        fail(`${s} shouldn't have failed to parse: ${err.message}`);
      }
    }
  };

  const chunks = `$JS.ACK.stream.consumer.1.2.3.4.5`.split(".");
  for (let i = 1; i <= chunks.length; i++) {
    fn(chunks.slice(0, i).join("."), i === 9);
  }
});
```

Clearly, the code is executed, so it should leave some sort of trace.

I wonder if there's some sort of mismatch - my tests live in a `tests`  directory, while the module is elsewhere.
Is it possible it is getting skewed by imports?

**Comment by caspervonb** [comment]
Still occurs in 1.8.1? Corrected the line intersection test a few days ago.

**Comment by caspervonb** [comment]
Hmm first pass at it and am unable to reproduce.
Presumably this is from genhtml via lcov output right?
Could you dump the lcov file to a gist?

**Comment by aricart** [comment]
@caspervonb  - sure thing, how about this:
https://gist.github.com/aricart/c383ef4739ad3b8385771c742c3d53b3

**Comment by aricart** [comment]
I tried 1.8.1 before filing just to make sure the fix you just put there didn't solve it.

**Comment by caspervonb** [comment]
Thanks @aricart!

The tracefile (lcov) file matches the output above so genhtml is doing what it's supposed to, just wanted to rule that out quickly.

Tried reducing it to down to this:
```ts
export function parseInfo(s: string) {
  const tokens = s.split(".");
  if (tokens.length !== 9 && tokens[0] !== "$JS" && tokens[1] !== "ACK") {
    throw new Error(`not js message`);
  }
}
```

```ts
import { parseInfo } from "./test.ts";

Deno.test("parseInfo 1", function() {
  parseInfo("");
});
```

Which got a 100% coverage; will have to dig around in your repository.
Hopefully this will age well: give me of days and I'll figure it out.

**Comment by aricart** [comment]
The branch where I started looking is called "js" . Will likely merge to main today. That branch has coverage integrations.

**Comment by aricart** [comment]
@caspervonb while looking at the repo may be a bit daunting, it isn't.
The only wrinkle is getting a build of the nats-server, but if you look at the GitHub actions, that will be much easier than you think. If you have `go` installed, it is simply:
```bash
git clone https://github.com/nats-io/nats-server.git
cd nats-server
go install
cd ..
git clone --branch js https://github.com/nats-io/nats.deno.git
make test
make cover
```

**Comment by caspervonb** [comment]
Is it rolled into master? went to dig into it now and js branch doesn't exist 🙃

**Comment by aricart** [comment]
@caspervonb yes it is in master

**Comment by caspervonb** [comment]
Not stale

**Comment by aricart** [comment]
@caspervonb any progress on this?

**Comment by caspervonb** [comment]
I'll try to get this done for 1.13 :)

**Comment by rivy** [comment]
Not stale.

**Comment by bartlomieju** [comment]
@aricart when you got some uncovered lines, were you testing that API in multiple test files?

**Comment by aricart** [comment]
@bartlomieju yes it is possible that tests in different files were doing the exercise.

**Comment by bartlomieju** [comment]
Thanks, this is most likely related to https://github.com/denoland/deno/issues/10944

**Comment by hildjj** [comment]
Note for others: I think it also happens if you don't delete data from previous runs, change the covered file, and run tests again.

**Comment by aricart** [comment]
my workflow deletes all gathered metrics before redoing...
