### ISSUE TITLE
Auto read import_map.json

### ISSUE THREAD

**Issue by blackshot** [denoland/deno#9759]
i think deno should automatically use `import_map.json` only if present on the root directory without having to use `--import-map` flag on `deno run` command because it sounds kinda boilerplatey. and it should leave that flag for using it when running with custom import maps.

**Comment by umucorn** [comment]
I like this idea and would like to work on it

**Comment by kitsonk** [comment]
That is against the design philosophy of Deno.  We do not automatically resolve items, they are always opt in.

Respectfully declined.

**Comment by blackshot** [comment]
What about an opt in config like `deno config auto-import-map true`

**Comment by kitsonk** [comment]
We don't have any external static configuration for Deno, and would be unlikely to add it in the near future.  "Binding" a command line to a specific program can be done with `deno install` or if you want to create a redistributable with all the import map being resolved, `deno bundle` and `deno compile` are available.

**Comment by blackshot** [comment]
ok! makes sense to me. but it would be nicer if the default value for the flag were "./import_map.json" in order to use just `--import-map` instead of redundantly write `--import-map=./import_map.json` it also could have a short flag version something like `-i` or `-I` this will still being considered as an opt in.
