### ISSUE TITLE
Windows does not highlight undefined in REPL

### ISSUE THREAD

**Issue by AkiaCode** [denoland/deno#9761]
In deno REPL, only the code becomes the highlight, so it would be nice to apply the result value as well.

deno:
![image](https://user-images.githubusercontent.com/71239005/110880285-bf34cc80-8321-11eb-8355-9f7bce8a468d.png)

**Comment by caspervonb** [comment]
Got any more details? this is not the expected behavior.
Version? What terminal is this in? 

![image](https://user-images.githubusercontent.com/157787/110883039-ceb21680-831d-11eb-8bad-15985e654d4f.png)

**Comment by caspervonb** [comment]
Could it be that your color scheme just doesn't have a gray color set?

**Comment by AkiaCode** [comment]
> Got any more details? this is not the expected behavior.
> Version? What terminal is this in?
> 
> ![image](https://user-images.githubusercontent.com/157787/110883039-ceb21680-831d-11eb-8bad-15985e654d4f.png)

Microsoft Windows [Version 10.0.19041.804]
(c) 2020 Microsoft Corporation. All rights reserved.

node:
![image](https://user-images.githubusercontent.com/71239005/110883749-4f294500-8327-11eb-87af-bd8909fb4875.png)

 I think my color scheme has a gray color set

**Comment by caspervonb** [comment]
What does this look like:

```js
let foo = undefined;
```

**Comment by AkiaCode** [comment]
> What does this look like:
> 
> ```js
> let foo = undefined;
> ```

![image](https://user-images.githubusercontent.com/71239005/110884404-69afee00-8328-11eb-8e93-30535b173fe0.png)

**Comment by caspervonb** [comment]
Last one, could you snap a screenshot of this:
```js
console.log("the value is %o", undefined)
```

**Comment by AkiaCode** [comment]
> ```js
> console.log("the value is %o", undefined)
> ```

![image](https://user-images.githubusercontent.com/71239005/110886654-57d04a00-832c-11eb-8525-1e281da27871.png)

**Comment by caspervonb** [comment]
Yeah so this is just console not having colors.

Is this cmd.exe?
Is noColor set to false?

```ts
console.log(Deno.noColor)
```

**Comment by AkiaCode** [comment]
> Yeah so this is just console not having colors.
> 
> Is this cmd.exe?
> Is noColor set to false?
> 
> ```ts
> console.log(Deno.noColor)
> ```

 Yes

![image](https://user-images.githubusercontent.com/71239005/111030547-3e232580-8446-11eb-9f00-0522e3c581b9.png)

**Comment by AkiaCode** [comment]
It looks like a bug (Windows)

**Comment by sant123** [comment]
I think this is related: 

v1.9.0

![image](https://user-images.githubusercontent.com/7959437/115942382-9e5aad80-a46f-11eb-951a-838873722618.png)

v1.9.2

![image](https://user-images.githubusercontent.com/7959437/115942396-aadf0600-a46f-11eb-903d-6f96d946b191.png)

**Comment by caspervonb** [comment]
> I think this is related:
> 
> v1.9.0
> 
> ![image](https://user-images.githubusercontent.com/7959437/115942382-9e5aad80-a46f-11eb-951a-838873722618.png)
> 
> v1.9.2
> 
> ![image](https://user-images.githubusercontent.com/7959437/115942396-aadf0600-a46f-11eb-903d-6f96d946b191.png)

Most likely someone implemented customInspect by returning a string, it's a bug but separate issue.

**Comment by sant123** [comment]
> > I think this is related:
> 
> > 
> 
> > v1.9.0
> 
> > 
> 
> > ![image](https://user-images.githubusercontent.com/7959437/115942382-9e5aad80-a46f-11eb-951a-838873722618.png)
> 
> > 
> 
> > v1.9.2
> 
> > 
> 
> > ![image](https://user-images.githubusercontent.com/7959437/115942396-aadf0600-a46f-11eb-903d-6f96d946b191.png)
> 
> 
> 
> Most likely someone implemented customInspect by returning a string, it's a bug but separate issue.
> 
> 

Do you know if that issue already exists? I want to follow it, or do you think I should create an issue?

**Comment by AkiaCode** [comment]
I want to follow it

**Comment by dsherret** [comment]
I'm able to reproduce.
