### ISSUE TITLE
'--unstable' flag message is not displayed

### ISSUE THREAD

**Issue by AkiaCode** [denoland/deno#9763]
![image](https://user-images.githubusercontent.com/71239005/110886416-ee503b80-832b-11eb-8c06-3f4ab9d113f4.png)

**Comment by nayeemrmn** [comment]
The message is only available as a TS type error. This is working as intended. Of course, I don't think we should consider intercepting vanilla JS type errors to add it there as well.

**Comment by AkiaCode** [comment]
> The message is only available as a TS type error. This is working as intended. Of course, I don't think we should consider intercepting vanilla JS type errors to add it there as well.

However, it may be confusing to users who use javascript why this is the case.

**Comment by caspervonb** [comment]
We don't want to interfere with users ability to probe for wether or not these functions are available I don't think there's anything actionable here.
