### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by timo-cmd2** [denoland/deno#9765]
Yo guys 👋🏻

Hows about implementing a docker image base support for deno. 

Deno is so awesome 😎❤️

Regards

Timo

**Comment by caspervonb** [comment]
Hayd maintains some very good docker images, see https://github.com/hayd/deno-docker.

**Comment by lucacasonato** [comment]
'Hey Guys' isn't very inclusive. Not all people on this repo are guys.

We already have an open issue about docker support.
