### ISSUE TITLE
REPL: Get help about a variable or type

### ISSUE THREAD

**Issue by bergercookie** [denoland/deno#9768]
If I were using a REPL like [IPython](https://ipython.org/) I could append a question mark at the end of a variable or object and get its documentation and possibly usage instructions:

```
In [1]: dict?
Init signature: dict(self, /, *args, **kwargs)
Docstring:
dict() -> new empty dictionary
dict(mapping) -> new dictionary initialized from a mapping object's
    (key, value) pairs
dict(iterable) -> new dictionary initialized as if via:
    d = {}
    for k, v in iterable:
        d[k] = v
dict(**kwargs) -> new dictionary initialized with the name=value pairs
    in the keyword argument list.  For example:  dict(one=1, two=2)
Type:           type
Subclasses:     OrderedDict, defaultdict, Counter, _EnumDict, Bunch, Config, Struct, ColorSchemeTable, Dict, Dict, ...
```

I don't think there's a similar functionality in Deno and I think something like this would be very useful while prototyping

**Comment by lucacasonato** [comment]
This would be a JS syntax extension, which we don't do. You can use `deno doc` instead: `deno doc --builtin Deno.create`.
