### ISSUE TITLE
Deno bundle error with constructor property initialisation

### ISSUE THREAD

**Issue by c4spar** [denoland/deno#9773]
Following example works with `deno run` but fails after bundling it with `deno bundle`.

**Example code:**
```typescript
export class Foo {
  bar = this.options.bar;
  constructor(
    protected options: { bar: string },
  ) {}
}

console.log(
  new Foo({ bar: "baz" }),
);
```

**Bundled code:**

```javascript
class Foo1 {
    bar = this.options.bar;
    constructor(options){
        this.options = options;
    }
}
console.log(new Foo1({
    bar: "baz"
}));
export { Foo1 as Foo };
```

**Error message:**
```
error: Uncaught TypeError: Cannot read property 'bar' of undefined
    bar = this.options.bar;
                       ^
    at Foo1.<instance_members_initializer> (file:///bundle.js:2:24)
    at new Foo1 (file:///bundle.js:3:16)
    at file:///bundle.js:7:13
```
**Version:**
```
deno 1.8.1 (release, x86_64-apple-darwin)
v8 9.0.257.3
typescript 4.2.2
```

**Comment by nayeemrmn** [comment]
This was fixed in https://github.com/swc-project/swc/issues/930. We need to add a `typescript_class_properties` pass for it, but there were bugs/complications: https://github.com/swc-project/swc/issues/987.

**Comment by nayeemrmn** [comment]
Actually, we ultimately decided to have `"useDefineForClassFields": true` in our internal tsconfig (https://github.com/denoland/deno/issues/7148#issuecomment-678754613), so tsc (the unbundled behaviour) would match the current behaviour of swc and we would consolidate like that instead.

It seems we added `"useDefineForClassFields"` on the sly to the list of ignored compiler options in #7228 and documented it in #9196... but grepping through the code base I don't see anywhere it's actually set to true 😅
