### ISSUE TITLE
[feat] Enumerate granted permissions

### ISSUE THREAD

**Issue by rivy** [denoland/deno#9780]
It would be nice to be able to enumerate granted permissions, especially for those permissions taking path/scope arguments.

**Comment by lucacasonato** [comment]
You can make use of the Deno.permissions.query API for this.

**Comment by nayeemrmn** [comment]
Enumeration is distinct from querying. However, this was wontfixed by the web permissions spec: https://github.com/w3c/permissions/issues/13. So, if there is a real use case, it should go through there IMO.

**Comment by rivy** [comment]
@lucacasonato @nayeemrmn , thanks for taking a moment to respond.

The use-case that I'm thinking of is enumerating permissions for task runners for help display (specifically, showing a command to run/re-run a task) and for running tasks with a subset of permissions. The boolean permissions are straight-forward, only requiring multiple queries, but the scoped permissions ('read', 'write', 'net') are semi-opaque as to coverage. And, future added  permissions will be missed in a brute force multi-query approach without a re-write.

I don't yet have a fully fleshed out scheme for my use case. But, philosophically, IMO, everything you can do to make permissions easier, more pleasant to use, and more automated should be considered. Right now, most applications are just throwing in the security towel and asking for `-A` permissions as well as using the same permissions for sub-processes. I'm leaning that direction as well. Long-term, that's a total security killer.

Again, thanks for your time.
