### ISSUE TITLE
error: Uncaught (in promise) BadResource: Bad resource ID

### ISSUE THREAD

**Issue by linux-china** [denoland/deno#9788]
I created a HTTP Server to receive http requests, then route the requests to Deno WASI, and WASI can not write data into stdout(redirected to request.conn.rid).

I found that it was caused by `Deno.writeSync(conn.rid, bytes);`  when writing bytes into request.conn.  Code as following: 

```typescript
import {serve} from "https://deno.land/std@0.90.0/http/server.ts";
const server = serve({hostname: "0.0.0.0", port: 8282});

for await (const request of server) {
    let bytes = new TextEncoder().encode("HTTP/1.1 200 OK\r\n" +
        "content-type: text/html; charset=utf-8\r\n" +
        "\r\n" +
        "Hello World!")
    let conn = request.conn;
    //await Deno.write(conn.rid, bytes); // it works
    Deno.writeSync(conn.rid, bytes); // failed
    await conn.closeWrite();
}
```

The error stackstack as following: 

```
error: Uncaught (in promise) BadResource: Bad resource ID
        Deno.writeSync(conn.rid, bytes);
             ^
    at unwrapResponse (deno:runtime/js/10_dispatch_minimal.js:60:13)
    at sendSync (deno:runtime/js/10_dispatch_minimal.js:107:12)
    at Object.writeSync (deno:runtime/js/12_io.js:109:20)
    at file:///Users/xxx/DenoProjects/wasi-cgi-demo/demo2.ts:15:14
    at new Promise (<anonymous>)
```

Code in snapshot_preview1.ts

![image](https://user-images.githubusercontent.com/46711/111098728-5441ec00-8501-11eb-9be1-fb88ef803ba0.png)

**Comment by caspervonb** [comment]
> WASI can not write data into stdout(redirected to request.conn.rid).

A file descriptor is not the same as a resource descriptor, each WASI context has it's own sandbox, stdio, etc.
How are you redirecting? setting passing `stdout: rid` to context?

**Comment by linux-china** [comment]
@caspervonb ,  pass request.conn.rid to  stdout  rid in  WASI Context.   It works if you pass the File.rid to WASI context. 

```typescript
async function runWasi(rid: number) {
    const context = new Context({
        stdout: rid,
        stderr: rid,
        args: Deno.args,
        env: {REQUEST_METHOD: "GET", SERVER_PROTOCOL: "HTTP/1.0", SCRIPT_NAME: "wasi-cgi-demo.wasm"}
    });
    const instance = await WebAssembly.instantiate(module, {
        "wasi_snapshot_preview1": context.exports
    });
    context.start(instance);
}
```
