### ISSUE TITLE
[Docs] Subprocess example leaves pipes open

### ISSUE THREAD

**Issue by leolabs** [denoland/deno#9790]
Related Doc: https://github.com/denoland/deno/blob/v1.8.1/docs/examples/subprocess.md

In a script I'm writing, I need to run tens of thousands of subprocesses via `Deno.run`, but I noticed that after the first ~4096 commands, I'd always get a `Bad file descriptor (os error 9)` error.

After some investigation, I found out that Deno leaves pipes open unless you read their contents with `process.output()` or `process.stderrOutput()`, so there's a bunch of unused open pipes otherwise.

It might be good to mention that in the docs, maybe with an updated example like this:

```ts
/**
 * subprocess.ts
 */
const fileNames = Deno.args;

const p = Deno.run({
  cmd: [
    "deno",
    "run",
    "--allow-read",
    "https://deno.land/std@$STD_VERSION/examples/cat.ts",
    ...fileNames,
  ],
  stdout: "piped",
  stderr: "piped",
});

const { code } = await p.status();

// Reading the outputs closes their pipes
const rawOutput = await p.output();
const rawError = await p.stderrOutput();

if (code === 0) {
  await Deno.stdout.write(rawOutput);
} else {
  const errorString = new TextDecoder().decode(rawError);
  console.log(errorString);
}

Deno.exit(code);
```

**Comment by jsejcksn** [comment]
> After some investigation, I found out that Deno leaves pipes open unless you read their contents with `process.output()` or `process.stderrOutput()`, so there's a bunch of unused open pipes otherwise.

Doesn't [`process`](https://doc.deno.land/builtin/stable#Deno.Process)`.close()` also close the pipes?

**Comment by leolabs** [comment]
I thought so as well, but just using `process.close()` lead to the same `Bad file descriptor (os error 9) ` errors. Closing the pipes by reading their output fixed the issue.

**Comment by jsejcksn** [comment]
Seems like a bug. Should an issue be opened for this @kitsonk?
