### ISSUE TITLE
prompt occasionaly malforms user input

### ISSUE THREAD

**Issue by kfdf** [denoland/deno#9794]
Any character that is entered the very moment the `Prompt` word pops up gets turned into a `d` (charcode 100). Windows 7, same effect in windows command prompt.
![bug](https://user-images.githubusercontent.com/19566825/111161009-b48d6800-85ab-11eb-905a-ef5f4da7ab76.gif)

**Comment by crowlKats** [comment]
Can't reproduce this on windows 10.
We don't support nor test Windows 7 as it is EOL.
