### ISSUE TITLE
Make op_crates truly self-contained with inter-crate deps

### ISSUE THREAD

**Issue by AaronO** [denoland/deno#9803]
**Disclaimer:** This is a brain dump of a conversation with @nayeemrmn @littledivy 

This would build off https://github.com/denoland/deno/pull/9800 and https://github.com/denoland/deno/issues/9738, by making `op_crates` truly self-contained for 3rd-parties allowing them to be easily cherrypicked without double-checking deps or ordering ...

### Context & Problem

Multiple `op_crates` (`fetch/web/websocket`) depend on `deno_url` implicitly today, this could be further exacerbated by future op_crate splitting (like https://github.com/denoland/deno/pull/9635)

### Suggested solution

A potential solution could be implemented as following:
- Have explicit crate deps in `Cargo.toml` (e.g: `op_crates/fetch/Cargo.toml` referencing `deno_url`)
- Have `*::init()` return `MultiModule`s of ordered deps and their "self module"
- Then have JsRuntime dedupe initialization of internal modules, so `deno_url`and co are not initialized N times
   (this could be solved by giving `JsRuntimeModules` IDs then tracking them in a `HashSet`)

### Notes

I'm not personally against this and would suggest it be done independently of #9800, but it would be great to have the core team's input. @lucacasonato @ry Thoughts ?

**Comment by crowlKats** [comment]
Since #17301 landed, which is more than enough, i will be closing this
