### ISSUE TITLE
SignalStream#dispose triggers then onfulfilled

### ISSUE THREAD

**Issue by KotlinIsland** [denoland/deno#9806]
This code triggers the callback, with no way of knowing if the signal actually appeared, or if the stream was disposed.
```ts
const s = Deno.signal(Deno.Signal.SIGABRT);
s.then(() => {
  console.log("I found a SIGABRT");
});
s.dispose();
```

**Comment by kt3k** [comment]
Note: The following code (uses AsyncIterable interface) doesn't print "I found a SIGABRT":

```ts
const s = Deno.signal(Deno.Signal.SIGABRT);
(async () => {
  for await (const _ of s) {
    console.log("I found a SIGABRT");
  }
})();
s.dispose();
```

Seems like something wrong with promise version API.
