### ISSUE TITLE
Headers is not compliant with the current spec

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#981]
It appears the `Headers` interface we based the implementation does not match the current spec.  See: https://developer.mozilla.org/en-US/docs/Web/API/Headers and https://fetch.spec.whatwg.org/#headers-class

We are missing the "iterable" type APIs (and likely the iterable symbol) and the spec does not include a `forEach`.

**Comment by ztplz** [comment]
#### implementation in chrome:
``````
const header = new Headers({a: 1})
undefined
"append" in header
true
"delete" in header
true
"entries" in header
true
"get" in header
true
"getAll" in header
false
"has" in header
true
"keys" in header
true
"set" in header
true
"values" in header
true
"forEach" in header
true
``````
#### implementation in firefox:
``````
const header = new Headers({a: 1})
undefined
"append" in header
true
"delete" in header
true
"entries" in header
true
"get" in header
true
"getAll" in header
false
"has" in header
true
"keys" in header
true
"set" in header
true
"values" in header
true
"forEach" in header
true
``````

@ry  @kitsonk   Should  we add `entries` `keys`  and `values` to the `header` interface?

**Comment by kitsonk** [comment]
In my opinion yes...

There is also `[Symbol.iterator]` in there as well which would allow `for (const header of headers)` for example.  In Chrome:

```
> Symbol.iterator in Headers.prototype
true
```
