### ISSUE TITLE
Support import completions + cache quick fix in @deno-types and triple slash

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#9823]
Follow up to #9821 

We should support the cache quick fix, import diagnostics, and import completions for import specifiers in `// @deno-types=""` and `/// <references types="" />` comments, like we did in the old extension.

**Comment by kitsonk** [comment]
Add the completions is a bit more complicated than adding the diagnostics and the quick fixes, so first step is to add the diagnostics and quick fix.  I will open another issue for completions.
