### ISSUE TITLE
Fetch questions/issues

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#983]
I was taking a look at `fetch.ts` and several issues/questions arose with the current implementation:

- `fetch()` returns `Promise<domTypes.Response>` instead of `FetchResponse`.  Was there a good reason for this?  Added public API surface for `FetchResponse` would then be hidden (though I have a question about that as well).

  https://github.com/denoland/deno/blob/d92c99eabaf28100a8d181b6f289e2e3fc295107/js/fetch.ts#L181-L184

- The `init` argument is not used in the function.  This will get exposed in the types, and users will think it _will_ do something when it doesn't.  We should remove it until we implement it.
- `FetchResponse` contains `onError`, `onHeaders`, and `onMsg`:

  https://github.com/denoland/deno/blob/d92c99eabaf28100a8d181b6f289e2e3fc295107/js/fetch.ts#L162-L178

  But two are totally non functional, and because it is not returned from `fetch()` these are never exposed, so they are totally redundant.  If `onMsg` has some special internal meaning, we should mark it with `@internal` and maybe put more comments in the code about what they are.  It also has a big block of code commented out with no hint as to why.
- `FetchResponse.arrayBuffer()` is not marked `async` and likely should be.

  https://github.com/denoland/deno/blob/d92c99eabaf28100a8d181b6f289e2e3fc295107/js/fetch.ts#L126-L128

- `FetchResponse.json()` has a return type of `object`.  This is incorrect.  It should be `any` as there are quite valid JSON responses that are not objects. (see: Microsoft/TypeScript#15225)  For example:

  ```js
  JSON.parse("1") === 1; // true
  ```

  https://github.com/denoland/deno/blob/d92c99eabaf28100a8d181b6f289e2e3fc295107/js/fetch.ts#L142-L145

**Comment by ztplz** [comment]
I agree,  `domTypes.Response` shoule be hidden and just return `FetchResponse`.

**Comment by ry** [comment]
I agree with all your points. 

> fetch() returns Promise<domTypes.Response> instead of FetchResponse. 

There was no thoughtful reason for this.

**Comment by bartlomieju** [comment]
Fetch landed in v0.2.0 and has been improved several times since. I guess we can close it?
