### ISSUE TITLE
Deno Language Server can't start through VS Code extension

### ISSUE THREAD

**Issue by tseyt** [denoland/deno#9836]
![image](https://user-images.githubusercontent.com/1750676/111779691-cd886880-888c-11eb-86b9-da41e5ec1112.png)

**Comment by kitsonk** [comment]
What version of Deno are you using?

**Comment by tseyt** [comment]
Fixed.

On Windows 10, I had deno installed on WSL but not Windows. I just had to install deno on Windows as well.
