### ISSUE TITLE
`Deno.emit` ast manipulation

### ISSUE THREAD

**Issue by timreichen** [denoland/deno#9851]
Ref: https://github.com/denoland/deno/issues/3354
I would like to be able to manipulate the ast when using `Deno.emit`. Something similar to typescript compiler API transfomers. I think this functionality would render the use of the `ts` module obsolete in most cases in favour of native and faster `Deno.emit`.

Maybe something like this:
```ts
const { files } = await Deno.emit("/mod.ts", {
  sources: {
    "/mod.ts": `import * as a from "./a.ts";\nconsole.log(a);\n`,
    "/a.ts": `export const a: Record<string, string> = {};\n`,
  },
  transformers: [
    (node) => {
      const visitor = (node) => {
        if (node.type === "ImportDeclaration") {
          // do something
        }
        return node
      };
      return visitor(node)
    }
  ]
});
```
What do you think?

**Comment by kitsonk** [comment]
Personal opinion is that it is overly complex to even considering implementing anytime in the foreseeable future.

**Comment by shadowtime2000** [comment]
I feel like an AST API would be cool and nice and stuff, but I don't think it is necessary to implement a visitor API or other API for modifying ASTs.

**Comment by MKRhere** [comment]
Would be a cool addition, even later down the roadmap.

**Comment by timreichen** [comment]
closing this beClosing this issue because Deno.emit is a separate mod now.
