### ISSUE TITLE
`Deno.osRelease()` in Windows

### ISSUE THREAD

**Issue by moncefplastin07** [denoland/deno#9862]
hi guys I think there is a problem extracting the OS version via the `Deno.osRelease()` method in Windows because when I run this code,
```ts
console.log(Deno.osRelease());
```
 I get `6.2.9200` in the console even though I am using Windows 10

Deno: v1.8.1
Windows: 10.0.19042

**Comment by littledivy** [comment]
`Deno.osRelease()` uses `sys-info` crate which uses [`GetVersionExW`](https://docs.microsoft.com/en-us/windows/win32/api/sysinfoapi/nf-sysinfoapi-getversionexw) in Windows.

And according to the documentation -
> Applications not manifested for Windows 8.1 or Windows 10 will return the Windows 8 OS version value (6.2).  Once an application is manifested for a given operating system version, GetVersionEx will always return the version that the application is manifested for in future releases.

Deno needs to be a manifested application. See https://docs.microsoft.com/en-us/windows/win32/sysinfo/targeting-your-application-at-windows-8-1

Solution is to use `Deno.build` wherever possible.

**Comment by moncefplastin07** [comment]
Thanks for your interest .. I tried to suggest this code but I don't know if it works in a practical way 
```ts
async function getWindowsVersion() {
    const procces = Deno.run({
        cmd: ["wmic", "os", "get", "Version", "/value"],
        stdout: "piped",
        stderr: "piped",
      });
      return new TextDecoder().decode(await procces.output()).split("=")[1].trim();
    
}

console.log(await getWindowsVersion())
```

based on `Deno.run` and `wmic` cli in windows os .. I know it's not a practical method, just a try 😁

**Comment by Spoonbender** [comment]
@littledivy unfortunately, making deno a "manifested application" won't solve the issue: if deno is manifested for some version X of Windows, then `GetVersionEx` will always return the version number of the target Windows version specified in the manifest and not the actual Windows version.

**Comment by Spoonbender** [comment]
Aside for a WMI-based option like @moncefplastin07 suggested, a few other options are:
1. [GetProductInfo](https://docs.microsoft.com/en-us/windows/win32/api/sysinfoapi/nf-sysinfoapi-getproductinfo?redirectedfrom=MSDN)
2. From registry: `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion`
3. Check the version number of a system DLL like `kernel32.dll`
[Source](https://stackoverflow.com/questions/47581146/getting-os-build-version-from-win32-api-c)

But perhaps we should just post a bug at the `sys-info` crate...

**Comment by littledivy** [comment]
@Spoonbender Yup, using RtlGetVersion and falling back to GetVersionEx sounds good? It better aligns with Node's `os.version` https://nodejs.org/api/os.html#os_os_version
(Need to be done in `sys-info`)
