### ISSUE TITLE
install command with import-map error

### ISSUE THREAD

**Issue by ije** [denoland/deno#9877]
```
deno install -A -f --unstable -n aleph \
--location=https://deno.land/x/aleph \
--import-map=https://deno.land/x/aleph@v0.3.0-alpha.11/import_map.json \
https://deno.land/x/aleph@v0.3.0-alpha.11/cli.ts
```
i got an error:

**error: No such file or directory (os error 2)**

remove `--import-map` can work.

_

deno 1.8.2 (release, x86_64-apple-darwin)

**Comment by kitsonk** [comment]
It appears that `deno install` cannot handle remote URLs for the `--import-map`, if the `--import-map` is a local file, it copies it to the DENO_DIR `/bin/` directory, but appears to fail to do so when the remote import map is used.
