### ISSUE TITLE
`Object.defineProperty` on `Event` prototype panics in repl

### ISSUE THREAD

**Issue by crowlKats** [denoland/deno#9880]
running `Object.defineProperty(Event.prototype, 0, {})` in repl will panic with `thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', cli/tools/repl.rs:564:49`

**Comment by dsherret** [comment]
This can actually be reproduced by just running the expression `Event.prototype` (issue is that it inspects getters that will throw an error). Will fix it soon.
