### ISSUE TITLE
`dom.asynciterable` seems to have been removed, breaking a module

### ISSUE THREAD

**Issue by ebebbington** [denoland/deno#9881]
## Overview

Was dom.asynciterable removed from the allowed lib options in tsconfig? What was working that used deno 3 releases ago, is broken due to apparently, dom.asynciterable not being a supported lib

```shell
$ deno test -A --config .\tsconfig.json

error: TS6046 [ERROR]: Argument for '--lib' option must be: ...

$ cat tsconfig.json

{
  "compilerOptions": {
    "lib": [
      "deno.ns",
      "dom",
      "dom.iterable",
      "dom.asynciterable",
      "es2018"
    ]
  }
}

$
```

## Deno Version

```
deno 1.8.2
v8 9.0.257.3
typescript 4.2.2
```

**Comment by kitsonk** [comment]
It is still there and there is a test for it: https://github.com/denoland/deno/blob/main/cli/tests/lib_dom_asynciterable.ts

**Comment by kitsonk** [comment]
Hmmm... not sure why it isn't working now. Investigating.

**Comment by kitsonk** [comment]
The test was dropped here: https://github.com/denoland/deno/pull/9282/files#diff-b5caf9a6af88c42ab9299ff53e1be01045c018338746f960fb9947e48c323bd9L3102-L3105 cc/ @bartlomieju so at some point it broke, but we never knew it.

**Comment by ebebbington** [comment]
Thanks @kitsonk!
