### ISSUE TITLE
Resource leak in test case when using `Deno.run` even if await status

### ISSUE THREAD

**Issue by vedantroy** [denoland/deno#9885]
Inside a Deno test, I have the following:

```js
const proc = await Deno.run({ cmd: [ <some command split into params> ]{)`
const status = await proc.status();
```

Deno then complains with:

```
AssertionError: Test case is leaking resources.
Before: {
  "0": "stdin",
  "1": "stdout",
  "2": "stderr"
}
After: {
  "0": "stdin",
  "1": "stdout",
  "2": "stderr",
  "4": "child"
}
```

I can fix this issue by calling `Deno.close(4)`, but this seems brittle.

Am I doing something wrong?

**Comment by bartlomieju** [comment]
Calling `proc.close()` after awaiting status will fix the problem.

**Comment by ebebbington** [comment]
To reiterate on this, @vedantroy, it's because the process is still running, thats why you see "child" as an extra list item in the After part - `p.status()` will resolve the process, whereas `.close()` will close up the resource
