### ISSUE TITLE
How to send headers in deno?

### ISSUE THREAD

**Issue by Scientific-Guy** [denoland/deno#9890]
I am working with an socket api where i need to send headers with the socket connections. However in nodejs it allows me to input headers in the second param. But as deno uses the browser like `WebSocket` api. I can't send headers with it. Any way so how can i send it with deno?

**Comment by crowlKats** [comment]
You can't set headers for the WebSocket API, as the spec doesnt allow such. See https://github.com/whatwg/html/issues/3062

**Comment by Scientific-Guy** [comment]
![Uploading image.png…]()

**Comment by Scientific-Guy** [comment]
I have viewed all of those and finally ended up here. So is there any other way?
