### ISSUE TITLE
deno test support filtering

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#9908]
We should consider that `deno test` support a `--filter` argument which would be a glob pattern. `deno test` would then only run tests that the test name matches the filter.

This would be similar to the way `cargo test` works to allow you to only run certain tests. A glob string is the most common, easily understood, matching pattern, which allows inclusions and exclusions.

This would also enable us to integrate a "run test" code lens into extensions, giving users the ability to run specific tests from their IDE.

**Comment by bartlomieju** [comment]
`deno test --filter` already supports regex syntax if the value is wrapped in slashes: `deno test --filter=/check\wPermission/`.

**Comment by kitsonk** [comment]
Doh! I guess I should check things before hand. 😊
