### ISSUE TITLE
import.meta.url is incorrect on windows

### ISSUE THREAD

**Issue by c4spar** [denoland/deno#9911]
On windows, `import.meta.url` and `Deno.cwd()` are inconsistent.

* `import.meta.url` uses the unix directory separator on windows
* it has a leading directory separator
* and it useses the wrong directory name for mounted file systems

Windows 10 vagrant vm:
```typescript
// leading and unix directory seperator
console.log(import.meta.url); // --> file:///C:/fast-forward/encoding_test.ts
console.log(Deno.cwd());      // --> C:\fast-forward
```
Expected output:
```typescript
console.log(import.meta.url); // --> file://C:\fast-forward\encoding_test.ts
console.log(Deno.cwd());      // --> C:\fast-forward
```

Windows 10 vagrant vm, within a mounted directory:
```typescript
// wrong directory name: vboxsvr
console.log(import.meta.url); // --> file://vboxsvr/fast-forward/encoding_test.ts
console.log(Deno.cwd());      // --> C:\fast-forward
```
Expected output:
```typescript
console.log(import.meta.url); // --> file://C:\fast-forward\encoding_test.ts
console.log(Deno.cwd());      // --> C:\fast-forward
```

Deno version:

```
deno 1.8.2 (release, x86_64-pc-windows-msvc)
v8 9.0.257.3
Typescript 4.2.2
```

**Comment by nayeemrmn** [comment]
> Expected output:
> 
> ```ts
> console.log(import.meta.url); // --> file://C:\fast-forward\encoding_test.ts
> console.log(Deno.cwd());      // --> C:\fast-forward
> ```

Wrong, the current behaviour is the correct way of handling Windows paths as file URLs. Backslashes become forward slashes, and the third leading slash is required. The syntax of file URLs is `file://<host>/<pathname>`.

`std/path/mod.ts` provides functions to convert between paths and file URLs, if you need them.

**Comment by c4spar** [comment]
Ahh right file url's 🤦 thx for your quick reply @nayeemrmn!
But i suppose the `vboxsvr` directory naming within the mounted file system is not the correct behaviour, is it?

**Comment by nayeemrmn** [comment]
> Windows 10 vagrant vm, within a mounted directory:
> 
> ```ts
> // wrong directory name: vboxsvr
> console.log(import.meta.url); // --> file://vboxsvr/fast-forward/encoding_test.ts
> console.log(Deno.cwd());      // --> C:\fast-forward
> ```

Perhaps `import.meta.url` is being canonicalized, while cwd isn't. I don't know if that's a problem or not. Could you try running the following in Node in the same directory and tell me the output? **`temp.mjs`** (note the file extension):
```js
import process from "process";

console.log(import.meta.url);
console.log(process.cwd());
```

**Comment by c4spar** [comment]
Ok, i think it is the correct behaviour. Same output with node.
Sry for creating this issue, but i'm not a windows user and i thought it is wrong, because a ffmpeg process i started with Deno.run got stuck. So i thought it was because of the wrong looking path, but it gets stuck as soon as i set `stderr` to `piped`.
