### ISSUE TITLE
Uncaught ReferenceError: {VARIABLE} is not defined

### ISSUE THREAD

**Issue by alaadahmed** [denoland/deno#9918]
My environment:
__macOS 11.2.3__
__deno 1.8.2__

I opened deno and tried to assign some variable like so:
```
Deno 1.8.2
exit using ctrl+d or close()
> events = [{id: 1, title: "Elixir Meetup", isFeatured: true},{id: 2, title: "Ruby Meetup", isFeatured: true},{id: 3, title: "PHP Meetup", isFeatured: false},{id: 4, title: "JavaScript Meetup", isFeatured: false}]
Uncaught ReferenceError: events is not defined
    at <anonymous>:2:8
> anything = []
Uncaught ReferenceError: anything is not defined
    at <anonymous>:2:10
> maybe_string = "Hi"
Uncaught ReferenceError: maybe_string is not defined
    at <anonymous>:2:14
```
I can't assign any variable or initialize it with any value.
Is this something normal? Or I miss something about how deno works?

**Comment by bartlomieju** [comment]
> Is this something normal? Or I miss something about how deno works?

Yes this is expected, you need to prefix variable definition with `var/const/let` just like you do in regular JS files, REPL is no different in this regard.

**Comment by alaadahmed** [comment]
I am sorry, I thought it is like node and normal browser. OK thanks.

**Comment by kitsonk** [comment]
Deno always interprets REPL code in strict mode.

**Comment by caspervonb** [comment]
Technically, we evaluate in REPL mode which is V8 specific mode that allows you to re-declare `let` bindings.
Some background available here https://docs.google.com/document/d/1bIKMRrLVObsAfmMAQ-tmsWkQZu1cFg87RRrPpiwTL2M/
