### ISSUE TITLE
LSP: intellisense inserts `?` after every completion

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#9920]
All completions for optional fields of an object insert a `?` after the property name in the completion. Issue here is likely that completion label should have the `?` to mark that the completion is optional, but the actual edit text should not. Present in canary. Was introduced very recently, likely in #9789

**Comment by kitsonk** [comment]
Could you give a more specific example of what is/isn't working so I can reproduce it?

**Comment by lucacasonato** [comment]
https://user-images.githubusercontent.com/7829205/112767605-fdb3d200-9017-11eb-9e72-6f40199ee184.mp4

**Comment by elisee** [comment]
Using latest canary Although the base bug is fixed, intellisense inserts an extra `?` when completing further:

![question-mark](https://user-images.githubusercontent.com/446986/113924623-52aad180-97ea-11eb-97e2-cc53a2e965e5.gif)

(the regular TypeScript extension doesn't do that)

**Comment by kitsonk** [comment]
That it what it is supposed to do, because `a` maybe undefined. I'm pretty sure the regular TypeScript extension would do this too.

**Comment by elisee** [comment]
Ah, ineded. It doesn't do it by default, which is why I found it strange, but I've just tested by explicitly setting `"strict": true` in `tsconfig.json` file and now it does. Since Deno has strict enabled by default, I guess that explains it. 👍
