### ISSUE TITLE
Dynamic import function type error

### ISSUE THREAD

**Issue by lkiii** [denoland/deno#9927]
I am building multiple handlers which I would like to include dynamically during the execution and when I am using `await import` I am getting type checking error. Is it a bug or should I implement this in a different way?
Run with:
```bash
deno run --allow-read tst.ts
```
tst.ts:

```typescript
export type TType = (input: boolean) => Promise<boolean>;

const a: TType = await import('./tst2.ts')
```
tst2.ts:
```typescript
import {TType} from './tst.ts' 

const a: TType = async (input) => {
  await Promise.resolve()
  return input
}
```
error:
```
error: TS2322 [ERROR]: Type 'typeof import("file:///mnt/c/Work/Projects/tst/tst2.ts")' is not assignable to type 'TType'.
  Type 'typeof import("file:///mnt/c/Work/Projects/tst/tst2.ts")' provides no match for the signature '(input: boolean): Promise<boolean>'.
const a: TType  = await import('./tst2.ts')
```

**Comment by kitsonk** [comment]
The error is correct.

Nothing is being exported from `tst2.ts` so the `typeof import('./tst2.ts');` that has been await is an empty object.  It certainly isn't a function that returns a promise.

**Comment by lkiii** [comment]
@kitsonk thank you for the quick response. My bad, I  have missed the last line in the tst2 file. Updated initial question with `export default a`

**Comment by kitsonk** [comment]
```ts
const a: TType = await import('./tst2.ts').default;
```
