### ISSUE TITLE
Fetch - extract redirect headers?

### ISSUE THREAD

**Issue by Maximilian5189** [denoland/deno#9933]
Hi,

in the built-in fetch function, currently there is no way to stop the redirecting of a request and to extract the redirect headers.

This is for example built into the node module node-fetch, there you can stop redirecting and extract all redirect headers, by setting `redirect: 'manual'`. (https://github.com/node-fetch/node-fetch#options)

I know the Deno implementation of fetch is according to the spec, so probably it will stay as is. However, is there any way around this behaviour? Can the API under the hood be accessed? If I debugged correctly, this would be "send" in the Deno core? For this, I could not find any documentation in the Deno core docs.

Many thanks in advance for the help.

**Comment by lucacasonato** [comment]
> there is no way to stop the redirecting of a request and to extract the redirect headers

There is. Set `redirect: 'manual'`.
