### ISSUE TITLE
Invalid UTF-8 char in typescript file causes serde_v8 error

### ISSUE THREAD

**Issue by kt3k** [denoland/deno#9952]
If a typescript file contains an invalid utf-8 string, that causes `serde_v8 error: ExpectedUtf8`.

The command below reproduces that error.
```
deno run https://raw.githubusercontent.com/denoland/deno_std/d42b5d141cf637d40e0430d065eab91cb66b7e2b/fmt/printf_test.ts
```

(The above file (test case of printf in deno_std) contains invalid utf-8 char in line 274)

ref: https://github.com/denoland/deno_std/pull/828

---
```
$ deno -V                                                                                                                  
deno 1.8.2+fec1b2a
```

**Comment by AaronO** [comment]
@kt3k Thanks for sharing, this should be an easy fix. I had introduced that error in #9843, specifically https://github.com/denoland/deno/pull/9843/commits/ab60c84e3197c3d7afd683fa36e8be5417e44094 to replicate the previous json-ops' failure on some WPT url parsing tests.

Chrome & Node can parse those URLs fine, so it looks like the best course of action be to revert that commit and remove those WPT tests as expected failures (so just expect them to pass)

**Comment by AaronO** [comment]
@kt3k Will submit a PR to fix this later today
