### ISSUE TITLE
async await should be reversed

### ISSUE THREAD

**Issue by modukon** [denoland/deno#9997]
Instead of waiting for a function to complete, all functions should be awaited on default and you should use a keyword if you don't want to await a function.

for example, right now you might write something like this:
```
var x = 1 + 5;
await sleep(1000);
saveSomethingToAFile();
```
the program will wait for the first 2 lines but not the last line. (the file write happens asynchronous)
instead this should be written like this:
```
var x = 1 + 5;
sleep(1000);
dontAwait saveSomethingToAFile();
```
(dontAwait is probably not a good keyword name, its just an example)

Right now if you see a function call somewhere in the code, you don't know if its sync or async
`functionThatDoesSomething()`
But if you were to reverse how async await works and replace it with "dontAwait" you would always know what it is, sync or async. If you see the "dontAwait" keyword you know its async, if not you know its sync.

It is natural to assume one line will execute after another:
```
x += 100;
y = Math.sqrt(20);
console.log("hello world");
x = y * 50;
```
Most of the code we write will execute in order and doesn't have any await keyword in front of it
async await are fundamentally flawed they way they work right now.

**Comment by caspervonb** [comment]
We provide a runtime, we won't change language semantics.
Deciding where JavaScript goes is up to tc39.

**Comment by modukon** [comment]
ok thank you for the reply
